### ISSUE TITLE
Just a suggestion to see if it can be done?

### ISSUE THREAD

**Issue by CRK1918** [signalapp/Signal-Android#10007]
Signal is great, but i wish they have a option to register with your own privacy email address or we can use a ID# from signal, so we do not have to use the phone number, I understand that it is very easy to send text messages, but this functions should be separated or a option to join...

**Comment by Nisc3d** [comment]
Hi @CRK1918 

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this over to the [community forum](https://community.signalusers.org/). Thanks!

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

But note that you will find this feature request already if you search.

**Comment by CRK1918** [comment]
OK. (:
