### ISSUE TITLE
Incoming message appears only after sending a response

### ISSUE THREAD

**Issue by Flygrounder** [signalapp/Signal-Android#10006]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A person has sent me two messages at once. Only first message appeared. After I sent them my own message, the second one appeared with a timestamp in the past.
This was discussed on [reddit](https://www.reddit.com/r/signal/comments/ioi5dy/random_chance_to_not_receive_message_until_ive/) but I was unable to find it on GitHub.

### Steps to reproduce
- Send multiple messages at once
- Reciepient should send their message

**Actual result:** Recipient sometimes gets the second message only after the response.
**Expected result:** They should get two messages at once.

### Device info
**Device:** Honor 10i
**Android version:** 10
**Signal version:** 4.71.2

### Link to debug log
[logs](https://debuglogs.org/c6d623cd46560515d13abbb67c065468711517d7cbc9be7a90319c970c13fbfa)

**Comment by mattspew** [comment]
I have the same issue with a contact of mine, and like others have noticed in the Reddit thread, they're also a Samsung user.

I sent this contact a message via Signal and it was marked as sent immediately, but sat as undelivered for 10 mins, so I sent them an SMS using Signal, and the Signal message was marked as received. Could be coincident, but it would appear that the SMS forced Signal out of the background.

**My Device**
Device: Huawei Nova 3i
Android: 9.1
Signal: 4.70.5

**Contacts Device**
I will get the exact model and update.
