### ISSUE TITLE
Unable to remove person from group

### ISSUE THREAD

**Issue by jgspratt** [signalapp/Signal-Android#10001]
### Bug description

While it is easy to add people's numbers to groups, there does not seem to be a way to remove people's numbers from groups.

I need to do this because my friend changed his phone number.  I see that I can "block" him, but that's not what I want to do: I want to remove that old number but not add it to a block list.

**Comment by cody-signal** [comment]
Hi @jgspratt, thanks for reaching out. Unfortunately blocking the old number is the only option right now, as removing isn't possible with the current version of groups. However, a new version of groups is coming very soon that will provide these types of capabilities. Stay tuned!

Additionally, these types of feature requests belong in our [Community Forums](https://community.signalusers.org/) as we try to reserve Github issues for bug reports. Thanks for being a Signal user!

**Comment by UserX404** [comment]
Will V1 groups be converted to V2 automatically, so that existing groups (with history) can be modified after V2 gets enabled?
