### ISSUE TITLE
Error Connecting to Service - Can't Register - SMS Verfication Method - 4.71.4

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#10012]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Getting "Error connecting to service" at registration.

### Steps to reproduce
- Once the verification code is entered, the registration process throws the error.

**Actual result:** Once the verification code is entered, the registration process throws the error.
**Expected result:** Once the verification code is entered, the registration process should work.

### Screenshots

![IMG_00232](https://user-images.githubusercontent.com/55331939/93019749-7eedcf00-f5c8-11ea-92f0-7e6340453a8e.jpg)

### Device info

**Device:** Mi 9T Pro (AKA Redmi K20 Pro)
**Android version:** 10
**Signal version:** 4.71.4

### Link to debug log

[debug_log.txt](https://github.com/signalapp/Signal-Android/files/5214873/debug_log.txt)

(Also where is the advanced menu to capture a log in such condition where user can't even register the app to get going? Under normal condition, we can use the menu. Not here.)

### Info
This issue only persists with Signal while rest of the apps just work fine. There is no firewall or network filtration going on. No VPN or Proxy. Signal app was downloaded from Play Store and has been given all the permissions along with Play Services. Also, tested without Play Services. Same error. Stock ROM in use.

**Comment by desmonk** [comment]
Problem appears to have been solved in version 4.71.5 of app.

**Comment by winkelnp** [comment]
I'm having the exact same issue on version 5.48.3 when trying to migrate my number to my new one....
