### ISSUE TITLE
Signal loses track of dark mode setting

### ISSUE THREAD

**Issue by mikeymop** [signalapp/Signal-Android#10017]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal seems to lose track of the system's current dark theme preference when set to 'Use System Theme'. The photo viewer activity seems to trigger it, however just opening the application from a notification can trigger signal to become confused.

On the Pixel 4a I have an option to set dark theme based on sunrise/set. This is available in both Googles Android 10 and Android 11 builds, and the issue with Signals dark theme occurs on both Android 10 and on 11.

### Steps to reproduce
- Set Signal to follow System theme
- wait for android to transition from light to dark theme or visa versa
- open signal from a notification or view an image from a message
- observe that signal is set to the wrong theme
- force close or swipe signal away from recents and reopen
- observe signal has reopened to the correct theme

**Actual result:** Signal may randomly open in the opposite theme color of the system theme
**Expected result:** Signal should always respect and reflect the system theme preference

### Device info
**Device:** Pixel 4a
**Android version:** 10 and 11
**Signal version:** 4.70.5

### Link to debug log

It is hard to catch the debug log since this occurs seemingly randomly but I will update if I can catch the issue while debugging.

**Comment by strugee** [comment]
> wait for android to transition from light to dark theme or visa versa

You don't have to wait. If you swipe down to get notifications, then again to get the quick access tray, you can tap the pencil icon in the lower-left of the tray which will allow you to add a "Dark theme" toggle.

**Comment by Tursko** [comment]
I encountered this today. My system theme is dark, but my Signal theme switched to white.

**Comment by mikeymop** [comment]
This can also be triggered by tapping the message icon in a contact card.

I suspect it happens when the activity stack is reset.

**Comment by Herohtar** [comment]
I encountered this once on my Pixel 2XL running Android 11 when opening Signal via a notification, but I have been unable to reproduce it.

**Comment by j710** [comment]
I'm seeing it routinely. Pixel 2 with Android 11. Auto dark mode with sunset. I can trigger it semi-reliably:
- after automatically switching from one mode to another
- click on a reaction to my message, showing who sent it
- click back
- theme has changed

**Comment by Herohtar** [comment]
Just experienced this again: tapped a message notification, conversation opened in dark theme (correctly), then when I hit "back" to go back to the conversation list, Signal switched to light theme:
https://debuglogs.org/27ad869a07c6b90c47a1a20415c71e1cb4cb5bcc335c9ae772d9ec44f96812a2

**Comment by mikeymop** [comment]
I have not yet experienced this issue in this weeks `4.72.5` release on stable or beta channels on the play store.

I feel this was in relation to [fed7d](https://github.com/signalapp/Signal-Android/commit/fed7d911a32a4aeb96fb5f3372fcb22854c26d8e)
