### ISSUE TITLE
Read Receipts only get sent after exiting and reentering conversation or are delayed

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#10016]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When messaging, I often send a message that gets delivered to the other device and then my chat partner answers me immediately (he is in the conversation screen). But I get the read receipt of my message only about 10-30 seconds after he already answered my message if we continue chatting. Another Problem is, if he doesn't answer and he exits the conversation, the conversation is highlighted, like the message was not read before. If he re-enters it the read receipts is send.

### Steps to reproduce
- Phone A: Be in one conversation, scrolled to the bottom
- Phone B: Send message
- Phone A: Exit conversation
- Phone A: Re-Enter conversation

**Actual result:** It only sends the read receipt after you close and re-enter the conversation or if you keep chatting
**Expected result:** It should always send a read receipt if you are in the Conversation screen

### Device info
Phone A:
**Device:** Nokia 7.2
**Android version:** 10
**Signal version:** 4.70.5

Phone B:
**Device:** Asus Zenfone 6
**Android version:** 10
**Signal version:** 4.70.5

### Link to debug log
Phone A:
https://debuglogs.org/d170ba473c6d454a0cf95efb46fe792ad5b8330a083a1971b7fc0aa0c383b6ab

Phone B:
https://debuglogs.org/fe2b71f10d6066debe469e1e3504ec154781f9dba8c0200f4f1b358e7df50cfb

**Comment by Tursko** [comment]
Oh yeah this looks to be similar to my issue as well. This is applying to all message notifications. 
https://github.com/signalapp/Signal-Android/issues/10018
