### ISSUE TITLE
Button to return conversation to inbox from Archive doesn't work

### ISSUE THREAD

**Issue by condemnedmeat** [signalapp/Signal-Android#10010]
- [x] I have searched open and closed issues for duplicates
- I am submitting a bug report for existing functionality that does not work as intended - Can it be sent privately?
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Pressing the button to return a conversation from archive says it's worked but it doesn't do anything. I have to swipe to do it instead.

In the gif you can see the button tap - shown as a purple circle - then Signal says "Moved conversation to inbox" but it hasn't. Then you see I swipe the conversation and that works.

![Untitled](https://user-images.githubusercontent.com/42522540/92999274-21e21280-f50f-11ea-918a-f2df8b7e8e51.gif)

Happens for both sms and Signal conversations.

### Device info

**Device:** Pixel 2 XL
**Android version:** 11
**Signal version:** 4.70.5

**Comment by Nisc3d** [comment]
I can confirm this, here is a debug log:
https://debuglogs.org/4a1b7cb546fd2468683b80d0ba9968dc3f01350a936caaacce88be5354ed395f

**Comment by alex-signal** [comment]
This has been fixed in 4.71.3 at commit bf4cac0c8
