### ISSUE TITLE
ConversationList - delayed refresh or notifications not being read

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#10018]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This doesn't happen all the time, but it's been happening quite frequently. What seems to be happening is that the conversation list isn't properly refreshing.

I get a message, open Signal, view the message, and then close Signal. When I reopen Signal, I will see that message as unread, and then it will quickly clear its unread status (because the list refreshes). 

### Steps to reproduce
- Receive a message/reaction
- Open Signal and read the message
- Close Signal
- Reopen

**Actual result:** Message will show as unread, and then the list will refresh and clear.
**Expected result:** The conversation list should have already been refreshed and no unread messages should show.

### Device info

**Device:** Google Pixel 4
**Android version:** 11
**Signal version:** 4.70.6

### Link to debug log
https://debuglogs.org/a3d488e7132c4949b5f73f637f83eedead4180ffaaaf2e12058660ff6d1df420

On this log I opened a thread, read the message. Came back to the app and the message is completely unread. 
https://debuglogs.org/cfd0fcfd177b4469269e0d6375624de8d6dbf9d31d4185319a1326dcd3263130

**Comment by Nisc3d** [comment]
I think this happend after #9803 got fixed.

**Comment by Tursko** [comment]
> I think this bug appeard after #9803 got fixed.

I believe you're correct. After reporting this bug I seem to constantly notice it.

**Comment by Tursko** [comment]
Here's another. Very annoying issue. 

Opened signal, read a message. Swiped home. Then came back to signal and the message was unread.

https://debuglogs.org/1efbe63ea2d7325286d5c3fb883b34ec16620e02fe5645e34fbf078400b53a06
