### ISSUE TITLE
Continuous crashing after restoring backup, only when connected to network (AssertionError: Must have either a UUID or a phone number)

### ISSUE THREAD

**Issue by billsmugs** [signalapp/Signal-Android#10014]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A relative has transferred their signal data to a new phone by following the steps here: https://support.signal.org/hc/en-us/articles/360007059752#android_restore

The restore from backup on the new phone appeared to complete successfully, but the app crashed afterwards and now instantly crashes when launched. If the phone is in flight mode the app works normally, and it appears to be able to send and receive messages in the background, (if minimised and connected to the network). If mobile data is on (regardless of WiFi connectivity status), the app crashes immediately upon launching the UI, if mobile data is off, but WiFi is connected then it reportedly takes a second or two to crash after launching (but still crashes every time). From the logs, the only exception from within signal appears to be an AssertionError "Must have either a UUID or a phone number!" in StorageSyncModels.localToRemoteContact()

They've tried reinstalling signal and recreating the backup and the same issue occurs. Signal has all available permissions (but is not the default SMS app - they have tried with it as the default, which had no effect).

### Device info

**Device:** Motorola G8 Plus
**Android version:** 9 (Security version 1st August 2020)
**Signal version:** 4.70.5

### Link to debug log
Can't send the log from within signal, due to the crash (as a side note, it would be really useful for issues like this if you could copy the text on the debug log screen, or export to a file!) See here for logs captured through adb logcat (this log contains two consecutive launches of the app, with WiFi and mobile data enabled): 

`09-13 19:47:13.795 11803 11850 I StorageSyncJob: Our version: 0, their version: 9
09-13 19:47:13.797 11803 11850 I StorageSyncJob: [Remote Newer] Newer manifest version found!
09-13 19:47:13.812 11803 11850 I StorageSyncJob: [Remote Newer] There's a difference in keys. Local-only: 8, Remote-only: 6
09-13 19:47:13.819 11803 11850 D WakeLockUtil: Released wakelock with tag: signal:********---****-**********55
09-13 19:47:13.829 11803 11850 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
09-13 19:47:13.829 11803 11850 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 11803
09-13 19:47:13.829 11803 11850 E AndroidRuntime: java.lang.AssertionError: Must have either a UUID or a phone number!
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:42)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:33)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:28)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.java:277)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:150)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:101)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
09-13 19:47:13.829 11803 11850 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler: java.lang.AssertionError: Must have either a UUID or a phone number!
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:42)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:33)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:28)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.java:277)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:150)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:101)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
09-13 19:47:13.830 11803 11850 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)`

**Comment by condemnedmeat** [comment]
You may wish to edit out a small amount of the info in the log. The logcat logs I think are more revealing than the in app logs.

Comparing at a glance you can search for WakeLockUtil. The in app log lines look like this as an example: WakeLockUtil: Released wakelock with tag: signal:********-****-****-****-**********55. I don't know how much of a big deal this is, perhaps you already knew this and it wasn't worth the trouble. I don't really know what I'm looking at so there may be more detail present you'd rather not have others see.

You can also delete github edits if you want to remove access to them after modifying the log. Just thinking about this, the log is hosted in a non public part of the repository - `github.com/signalapp/Signal-Android/files` - so I'm not sure why you couldn't just give it a distinctive name and post the name of it, not a link to it and the devs can find it and there is less of a privacy concern.

**Comment by billsmugs** [comment]
I've edited the first post to just include what I think is the relevant part of the log and redacted the WakeLocUtil line, thanks. I didn't realise the GUIDs were sensitive, I just skimmed through looking for e.g. phone numbers. The file was just uploaded as an attachment to the comment but I've contacted Github support to delete it (as there appears to be no other way to do so?)

**Comment by condemnedmeat** [comment]
I didn't mean to alarm you, see what Signal say. The file looks as though it's hosted in the repository at `github.com/signalapp/Signal-Android/files/-a set of numbers-/log.txt`. So perhaps it will be easy to delete if that's what you want. I obviously deleted the version I downloaded.

**Comment by billsmugs** [comment]
This appears to have been fixed in v4.71.5
