### ISSUE TITLE
Backup files not detected because of bad file ending

### ISSUE THREAD

**Issue by lumaku** [signalapp/Signal-Android#10013]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I followed the steps as described in [Backup and Restore](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages). But the backup file was not detected.

### Steps to reproduce
- created backup on old phone. The backup file has this format: `signal-year-month-date-hour-minutes-seconds.backup.bin`
- all backup files generated by the app have a `.bin` ending.
- copied the backup file over to new phone. Copied into the following folders: `/Internal Storage/Signal/Backups`, `/Internal Storage/Signal` and `/Internal Storage`
- Installed Signal on the new phone
- After granting all asked permissions, the input form for the phone number appeared.

**Actual result:** No backup file detected. No option to restore from backup appeared.
**Expected result:** Backup file detected and option to restore backup

### Solution to the problem

- The file `signal-year-month-date-hour-minutes-seconds.backup.bin` has a `.bin` extension.
- After renaming the file and removing the `.bin` ending, the backup file was successfully detected

### Device info
**Device:** Google Pixel 3
**Android version:** Lineage OS 17.1
**Signal version:** 4.69.6. The backup file was created with Signal version 4.69.6.

### Link to debug log
[Debug Log ](https://debuglogs.org/86bd9d8b9aa252276051703866dc275dc075b78b862b7e67837c74b58629fdf9)

**Comment by alan-signal** [comment]
It definitely had a `.bin` extension before you copied it?

What are the details of the old phone please? And log from that might be useful.

**Comment by lumaku** [comment]
Here is the [log](https://debuglogs.org/76dc6d15492130c52fc7bfe444bc57139b1fed27a0eaef0b44a8102a8cba3150). After checking the files in the Signal `/Internal Storage/Signal/Backups` folder, they did *not* have a `.bin` extension. However, all the files in the mirrored folder had the `.bin` extension.

What happened: I uploaded all of the backup files from the file browser to the nextcloud app using the "send to" feature; that's where the renaming happens. It's reproducible and does not happen with the "copy to" function.

This is an issue in either the Nextcloud Android app or the Lineage OS file browser; and not an issue with Signal. (It would be nice if Signal could have a more verbose dialogue for searching/importing backups though.) This issue can be closed.

**Comment by abe-winter** [comment]
ugh this happened to me too with signal for android, using owncloud to transfer the file. owncloud took a `.backup` file and added an extension to make it a `.backup.bin`

restoring the `.backup.bin` failed silently and shunted me to the 'enter your phone number' screen. renaming to just `.backup` fixed it and allowed the import to work.

not exactly a signal bug, definitely weird behavior by ownlcoud, but +1 for clearer error popups
