### ISSUE TITLE
Signal sending encrypted messages to non-signal users

### ISSUE THREAD

**Issue by foosroos** [signalapp/Signal-Android#10026]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app is creating Signal-contact info for non-signal contacts

### Steps to reproduce
- Have a non-contact (that doesn't use signal) message you via SMS
- In the Signal app, add them as a contact
- Send the contact a message

**Actual result:** Signal identifies them as a Signal user, and sends encrypted messages
**Expected result:** The contacts have no prior use of Signal, thus, SMS should be the default message type.

### Screenshots
N/A

### Device info

**Device:** Google Pixel 3
**Android version:** 10
**Signal version:** 4.71.5 (just updated before submitting the log. Not sure what prior version was)

### Link to debug log
None available.

**Comment by Genis-Sage** [comment]
hey @foosroos

just to not make wrong assumption:
you have set up Signal as your default SMS app?

what happens, if you don't save the person in your contacts, but simple add the persons phone number into the new message dialogue... is the person then also identified as signal users?

does the behaviour change, when you set another app as default SMS app?

and why do you say, there is no log available? (sorry, if the questions sounds dump, but logs really help)

**Comment by foosroos** [comment]
Signal is my default SMS app

If I don't have them in my contacts, it does not identify them as a signal user

Haven't tested with another SMS app as default. I will do more testing tomorrow since I will be around one of my contacts that caused the issue.

I say log not available in that too much time has passed since I deleted and remade the contacts in a way that works. When I recreate the issue again, I will have an accurate, useful log.

**Comment by greyson-signal** [comment]
If the contact is a Signal user, we will send them Signal messages. It's our default to use the safest communication option available. If the messages are sending (i.e. you get at least a single checkmark on the bubble), then they are, in fact, Signal users.

If you'd like to switch to sending SMS, you can long-press the send button and switch to SMS. The conversation will stay SMS unless the other person sends you a Signal message (or you switch it back). Hope that helps!
