### ISSUE TITLE
Sending same message repeatedly

### ISSUE THREAD

**Issue by sonjamvalenta** [signalapp/Signal-Android#10029]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- XI have searched open and closed issues for duplicates
- X I am submitting a bug report for existing functionality that does not work as intended
- X I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- X This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is repeatedly resending the last message I sent to the receiver.  The message was sent hundreds of times and only stopped when I uninstalled the application.  I did receive a pop up saying that Signal was sending a large number of messages.  When I click on deny, the pop up would disappear and reappear in less than a second.

### Steps to reproduce
- I sent a message to a recipient
- around an hour after I sent the original message (which was received within minutes) the recipient then received the message repeatedly over a hundred times

**Actual result:** The recipient continues to receive the same message.  My device continues to give me the pop up telling me that Signal is sending a large number of messages, but clicking on deny or cancel has no affect.
**Expected result:** Signal sends the message from my device to the recipient once only.

### Device info

**Device:** Samsung S10+ Note
**Android version:** 10
**Signal version:** 4.71.5

**Comment by Genis-Sage** [comment]
hey @sonjamvalenta 
as you said you deleted Signal, i guess, you can't privide any debug logs from the time, when the problem occured

i guess, that without a log, it's quite impossible to find the bug

did you do anything special, when this happened?
do you have any hints, how to reproduce the behaviour?

did you try force stopping the app?
did you try clearing the cache?
did you try to put your phone offline, for example by putting it into flight mode?

**Comment by greyson-signal** [comment]
Let's centralize discussion here: #8390
