### ISSUE TITLE
Profile picture is not correctly displayed when 

### ISSUE THREAD

**Issue by lallenfrancisl** [signalapp/Signal-Android#10027]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The profile picture of contacts is not correctly displayed when we have assigned a photo ourselves to the contact. Then the photo we assigned is shown rather than the one the they have set themselves.

### Steps to reproduce
- Add a photo to your contact in your contacts app
- refresh contacts in the signal app 
- You will see that the contact's profile picture has changed to the one you uploaded
**Actual result:** the contact's profile picture has changed to the one you uploaded
**Expected result:** The profile picture should be the one they have set

### Device info
**Device:** Poco M2 Pro
**Android version:** 10.0
**Signal version:** 4.71.5

**Comment by Genis-Sage** [comment]
hey @lallenfrancisl 

this is no bug, but intended issue
as you can see in #9833 , #8749 , #7132

for further discussion, please go to the community forum: https://community.signalusers.org/

**Comment by greyson-signal** [comment]
Correct, you can read my reply here for more details: https://github.com/signalapp/Signal-Android/issues/9833#issuecomment-655784917

**Comment by lallenfrancisl** [comment]
A toggle would be better. It would probably make a lot of people switching from whatsapp unhappy.

**Comment by killathe** [comment]
I'm not happy with the way Signal handles profile pictures. The current state can be default, but let the users decide to change it. I'd like to have a toggle as well. Maybe even on a per contact basis.
