### ISSUE TITLE
app closes on verification screen

### ISSUE THREAD

**Issue by CouldBeThis** [signalapp/Signal-Android#10022]
Thank you everyone who contributes to this really excellent app.  It makes secure/private messaging accessible to so many people who are too intimidated to try other options. No one I know uses telegram, wire, xmpp or any other program but lots of people are switching to signal. Integrating it with am plain text message app was a stroke of genius. 

- [x] I have searched open and closed issues for duplicates (_but I am not very confident of my search; possibly I missed something_)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have been running signal for some time on stock android. Recently, I switched to LineageOS. I installed signal but skipped backup restore. It installed and was working fine for a week or so. 

However now I wish to restore the backup. I understand from the documentation it must be uninstalled/reinstalled to do this.  

I am unable to reinstall successfully; the app crashes at the verification screen. 

### Steps to reproduce

1. uninstall/reinstall signal
   - from f droid store and also later apk from website
2. open signal
3. restore backup (phone reports it decrypts the messages)
   - by way of troubleshooting, I have now attempted to skip backup as before; no difference in end result
4. enter phone number

**Actual result:** 

screen comes up that says "enter the code that was sent to [phone number]" and the option to call instead of SMS. But after a second or less it closes itself; the app is quit. I don't get any SMS verification code. I can't use the voice option. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

On the first install, I recall seeing the number fill itself into the 6 boxes automagically. 

**Other troubleshooting info**

* If I re open the app I can try again a couple times but eventually I get errored for doing it too much. I can wait and repeat this later.
  * I assume this error comes from the server from which I infer that the request for verification code is being received. So maybe someone can figure out what problem could happen in that moment? 
* I subsequently installed whatsapp and I did get the SMS verification successfully so I know that part of it works fine. 
* *Maybe* one of the many apps I have installed in the past week is doing something to interfere somehow? I have been having lots of fun going through the free software options in f droid store. 
  * I actually thought I had solved the problem: I noticed that in [Blockada](https://blokada.org/) there was a blocked a connection from whisper-something-something server. To be simple I just uninstalled it and everything else that might be doing that kind of thing. Same problem though. 

### Device info

**Device:** samsung galaxy a5
**Android version:** 10
**Signal version:** 4.71.5

### Link to debug log

impossible to generate :(

**Comment by greyson-signal** [comment]
You can generate a debuglog by tapping the title on any of the registration screens 8 times. Try that and then post that here.

Also, is Signal still set at the default SMS app? There's a known crash around receiving the SMS code while Signal is the default SMS app. If that's the case, try making some other app the default until after you've registered.

Thanks!

**Comment by CouldBeThis** [comment]
Fixed. It did seem to have something to do with what app was handling SMS. 

If this is something that would commonly happen during uninstall/reinstall maybe a caution could go on the restore backup page or elsewhere? Possibly I accidentally created a strange situation tho. 

thank you the problem at hand is solved and it sounds like I don't have a new issue?

**Comment by greyson-signal** [comment]
Ah glad that was it. I'll close this only because we're tracking it elsewhere. Thanks, and sorry for the confusion!

**Comment by Aspire1Inspire2** [comment]
@CouldBeThis Hi I have this exactly same issue. Can I borrow some knowledge from you? Could you let me know how you fix it?
