### ISSUE TITLE
Cannot update "Half-loaded" blurred thumbnail

### ISSUE THREAD

**Issue by hklene** [signalapp/Signal-Android#10028]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending a single photo (never seen it for received pics) from my phone sometimes produces broken thumbnails in a "lower half blurred" version to show in the conversation. The thumbnail will stay like this forever. I cannot find a way to update/recalculate the thumbnail.

The image itself is fine, if enlarged full screen. It will get a proper thumbnail on occasion in the "all media" folder, though that gallerie produces quite a few blurred images if scrolling back and forth, but usually different images are blurred and they are either blurred completely or show completely.

The desktop app and the receiving phone both also displayed a proper thumbnail.

### Steps to reproduce
- take a single picture / or share one picture from the gallery app
- type a caption under the preview of the image (still fine)
- send the image
- an animation symbolized the sending progress
- the image is stuck with a bad thumbnail
- no way to recalculate the broken thumbnail

### Screenshots
![Screenshot_20200920-100929](https://user-images.githubusercontent.com/7427503/93707301-95da7700-fb1c-11ea-9063-ada4595a1f18.jpg)
![Screenshot_20200920-100738](https://user-images.githubusercontent.com/7427503/93707318-b1de1880-fb1c-11ea-842d-45f2b82bb6c5.jpg)

### Device info
**Device:** OnePlus Nord
**Android version:** OxygenOS 10.5.7.AC01BA
**Signal version:** 4.71.5

**Comment by Nisc3d** [comment]
This is a duplicate of #9082.

**Comment by hklene** [comment]
You are right - I thought there is a difference, because the others have black thumbs or they were fumbling with the crop tool. But in the end, the workaround is the same - clear the cache and all the thumbnail will be recreated as necessary. In addition it freed up some 200 MB of valuable space ... and even scrolling over a group of 10 pics, I barely perceive a minimal delay, until the thumbs appear for the first time. So my phone could even do without the cache.
