### ISSUE TITLE
Forwarding SMS Message to "Note to Self" Crashes App

### ISSUE THREAD

**Issue by Major-Mike** [signalapp/Signal-Android#10038]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I attempt to forward a non-signal user message to "Note to Self", it immediately crashes the app.

### Steps to reproduce
- Go to any SMS user conversation (non-signal)
- Long-press any message and click on forward
- Select "Note to Self"

**Actual result:** Immediately crashes the app
**Expected result:** Should forward the message like any other forward action

### Screenshots
N/A

### Device info

**Device:** Motorola One Zoom
**Android version:** 10
**Signal version:** 4.71.5

### Link to debug log
https://debuglogs.org/838ce0214b1d445ed2ec323746449a878ce13c28e3339c3d246a4c228a59ee13

**Comment by Tursko** [comment]
I tried to reproduce this but no luck.
