### ISSUE TITLE
Received SMS no notifications or sounds

### ISSUE THREAD

**Issue by hipitihop** [signalapp/Signal-Android#10039]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I use signal as the default SMS application on my Android phone. When an SMS arrives, from a contact or not, there is NO notification posted into the normal Android notifications stack, and there is no audio indication that a new one has arrived. If I happen to open the signal App, I will see new message counts, and see the new messaged. This causes me to miss important ones, as I only tend to open the app if I have been pinged by a Signal contact/user (encrypted) or if I go to send a message. I also run the Desktop app on my Ubuntu desktop, so there I get normal Signal contact/user notifications of messages, and I tend to reply on the desktop too. Since Signal does not clone the new received messages to other connected device (in this case my desktop) then I can go for a couple of days not needing to check my phone (since I have not had any notifications) and in turn miss important SMS messages.

### Steps to reproduce
- receive unencrypted SMS from a standard Android contact (not a Signal user or a non contact (someone you have never received a SMS from or not in your Android contact list.

**Actual result:** 
See Description above.

**Expected result:** 
I expect my phone to add a notification for received SMS messages and respect notification sound settings.

### Device info
**Device:** HD1900 OnePlus 7T
**Android version:** 10.0.12.HD65AA (Oxygen OS)
**Signal version:** 4.71.5
All permissions and notification settings in Signal are enabled

**Comment by blazevivan** [comment]
I have the same issue with any message sent to Signal - no notification or sound from the phone. 
The only sound that works is Call sound. 

Device: Mi Note 8 Pro
Android version: 10.0.2.0 (MIUI 12.0.2)
Signal version: 5.0.5

**Comment by WhatsThatNoise** [comment]
> I have the same issue with any message sent to Signal - no notification or sound from the phone.
> The only sound that works is Call sound.
> 
> Device: Mi Note 8 Pro
> Android version: 10.0.2.0 (MIUI 12.0.2)
> Signal version: 5.0.5

This is nothing you have to live with as a Xiaomi/MIUI-user. I had the same problem on Redmi Note 8. All settings fine, but no more notifications on incoming messages (except when using the app in this very moment). Seemed to be caused by an update. Simple deleting and re-installing the latest version did the trick for me. (Consider backing up your Signal-data first. Takes only a minute.) Good luck!
