### ISSUE TITLE
Android Tablet as Linked Device Support

### ISSUE THREAD

**Issue by 1Yanik3** [signalapp/Signal-Android#10032]
not much to say here, would just be very very useful to have

**Comment by Taeluf** [comment]
According to the [contributing guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) , feature requests belong on the [community forum](https://community.signalusers.org/c/feature-requests)

**Comment by Sytten** [comment]
This should be considered a bug at this point...
