### ISSUE TITLE
All contacts wiped out except for Signal connections

### ISSUE THREAD

**Issue by j-james** [signalapp/Signal-Android#10031]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- I opened up Signal and texted my friends normally (through SMS). 
- A bit later I opened up Signal again to notice that all of my contacts had disappeared - save for the ones of those who have the app installed.
- I rebooted, and they were still missing, so I opened up this issue.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- All of my contacts should be there.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.71.5

### Link to debug log
https://debuglogs.org/f4b2c7c368c569440c57a49bd29a2c54ee733c6e5771f2351bb000ad3be4cdb2

I'm running this app with [Simple Contacts](https://github.com/SimpleMobileTools/Simple-Contacts/), but it seems more likely that this is an issue caused by Signal. 

I'd like any ideas on how to recover these contacts. I have Signal set up to take incremental backups (which may have caused this - I remember it backing up sometime today) and a raw-contacts `.vcf` file from March. Preferably, if there's any way to recover contacts from Signal, that'd be nice.

**Comment by alan-signal** [comment]
Why did you close this @j-james ? Did you resolve the issue, if so can you elaborate?

**Comment by j-james** [comment]
@alan-signal I'm now pretty sure this wasn't caused by Signal - I had removed and put back in my SIM card earlier in the day (which shouldn't alone delete my contacts, but Signal hadn't been doing anything particularly strange), and found that my contacts were still deleted without Signal. The Signal contacts remaining is probably issue #9852 .
