### ISSUE TITLE
Clearing group chat messages causes group to disappear

### ISSUE THREAD

**Issue by callumtilbury** [signalapp/Signal-Android#10033]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Deleting the messages from a group chat causes the group to disappear.

### Steps to reproduce
- Open Signal
- Long-press on group chat
- Press 'delete messages' button

**Actual result:** Group chat disappears, no longer listed as "groups in common" with group members, can only access the group chat again by going onto Signal Desktop (where the chat hasn't been cleared) and sending a message. Then the chat reappears on phone.
**Expected result:** Ideally I would be able to delete the messages from the group, but the group itself remains in place—just with an empty chat.

### Screenshots

Long-press on chat, and press 'delete messages' button
![signal-2020-09-22-094309_001](https://user-images.githubusercontent.com/37700709/93855747-4af56680-fcb8-11ea-86d1-82a9d0db8228.jpeg)

Can no longer find group chat. Navigate to contact who is in the group, can't view group in common:

![signal-2020-09-22-094309_002](https://user-images.githubusercontent.com/37700709/93855828-72e4ca00-fcb8-11ea-8f3c-b1b1ef0ee0b8.jpeg)

Send a message to the group from Signal Desktop (where chat hasn't been cleared), and it appears on phone:
![signal-2020-09-22-094309_003](https://user-images.githubusercontent.com/37700709/93855869-84c66d00-fcb8-11ea-9fb3-aa26f58b1fa4.jpeg)

Now group has returned, both in the main window, and in the 'groups in common' tab:
![signal-2020-09-22-094309_004](https://user-images.githubusercontent.com/37700709/93855872-85f79a00-fcb8-11ea-9d0a-6eee3135875e.jpeg)

### Device info

**Device:** Samsung Galaxy A20 (SM-A205F)
**Android version:** 9
**Signal version:** 4.71.5

### Link to debug log

Unfortunately when I try submit the Debug Log, it just loads for ~60 seconds, and then says "Failed to submit logs"

**Comment by Tursko** [comment]
That is a delete chat button, not a delete messages button.

**Comment by callumtilbury** [comment]
> That is a delete chat button, not a delete messages button. Group references are stored locally, so if you delete that chat then you'll lose the reference. This is how it works on most messaging platforms.

Hmm yes, I understand. But could it not continue storing the chat reference, even when the messages have been cleared? When you delete in WhatsApp (for example), it keeps the chat, but it just has no messages within it.

> Another solution is for someone else to message in the group chat after you delete it (you'll have to coordinate this). Afterwards your chat will pop back up on the list.

Yes, but this is frustrating.

> There is a new feature in Settings -> Storage -> Keep Messages. This will allow you to set a personal time limit on all messages (so its a global action).

That is interesting, thanks. However, people might still want to clear a group chat without, in essence, losing access to the actual group.

**Comment by Tursko** [comment]
> When you delete in WhatsApp (for example), it keeps the chat, but it just has no messages within it.

Sure. This sounds like a feature request though, not a bug. Everything you've talked about on this bug report is intended functionality. 

If you'd like to request this feature, you can go to the Signal forums and search/make a post about the subject. https://community.signalusers.org

**Comment by callumtilbury** [comment]
> Sure. This sounds like a feature request though, not a bug. Everything you've talked about on this bug report is intended functionality.

Hmm, yeah, sorry about that. I pursued it as a bug based on my understanding of what a delete button/'clear chat' feature should do.

Thanks though!

**Comment by 143premsai** [comment]
If we have the group invitation link we can retrieve the reference of the group.
