### ISSUE TITLE
Chat Heads/Bubbles

### ISSUE THREAD

**Issue by AzureB1te** [signalapp/Signal-Android#10034]
I have not yet gog my Android 11 update,but since Android 8.1 I'm looking to get a way,to force signal to have chat bubbles.
There is an app on the Play Store that uses the quick reply function to enable bubbles,but well it doesn't work with signal.
Can we have chat heads? Or quick replies at least?

**Comment by Herohtar** [comment]
Quick replies are an Android OS feature, and they already work with Signal in the versions of the OS that provide it.

Chat heads is a feature request, which belongs on the [community forum](https://community.signalusers.org) (as stated in the issue template that you deleted). And indeed, there is [already a request for them there](https://community.signalusers.org/t/facebook-like-floating-chat-bubble/5333?u=herohtar).
