### ISSUE TITLE
Video playback controls (pause/play/seek) not visible.

### ISSUE THREAD

**Issue by nofxy** [signalapp/Signal-Android#10048]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video playback controls (pause/play/seek) not visible.

### Steps to reproduce
- Receive video from a contact.
- Open said contact's messages.
- Click on video to play it back.
- Watch video. 

**Actual result:** The video starts playing in full screen, I see the playback buttons for a split second and then they disappear. Touching the display to exit "full screen video mode" doesn't bring back the video buttons (pause/play/seek). If I click where I expect the buttons to be, it allows me to pause/play/seek the video.
**Expected result:** The video plays back in full screen, the playback buttons don't show at all. I touch the display to exit full screen video mode and see the playback buttons to control pause/play and seek. 

### Device info

**Device:** Google Pixel 4XL
**Android version:** 11.
**Signal version:** 4.71.5

### Link to debug log
https://debuglogs.org/d90ed74114da3377ace03b64904696aee67216a617ec42e4cc7366139542e2ba

**Comment by cody-signal** [comment]
See #9993
