### ISSUE TITLE
Fingerprint verification instructions do not work

### ISSUE THREAD

**Issue by sifr01** [signalapp/Signal-Android#10049]
The instructions for how to verify the APK download from https://signal.org/android/apk/ do not work. 
They link to [android developers](https://developer.android.com/studio/command-line/apksigner#usage-verify) which suggests to run:
`apksigner verify [options] app-name.apk`

However, this command only supports APKs up to version 2 whereas your APK is version 3. Instead it throws error message:
`DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: Malformed additional attribute #1
WARNING: APK Signature Scheme v2 signer #1: Unknown signature algorithm: 0x421
`

The verification command needed is:
`keytool -printcert -jarfile <Signal-website-download-file.apk> | grep SHA256`

You may suggest that I report a documentation bug with android developers, but personally, I dont have a google account because theyre creepy.

**Comment by sifr01** [comment]
For the meanwhile, I have provided some [alternative documentation](https://github.com/sifr01/signal_updates) for people.

**Comment by alan-signal** [comment]
It can depend on the version of build tools you are using.

E.g. `28.0.2` does what you said, but this works fine:

```
$ANDROID_HOME/build-tools/29.0.2/apksigner
```

**Comment by alan-signal** [comment]
Can I take it this works for you?

**Comment by EmberHeartshine** [comment]
I had a similar issue when adding this to my fdroid repo. See #9151.

Update your build-tools to the latest version. For me, that required downloading them manually from the Android website and replacing the executables since my distro didn't have up-to-date build tools.

**Comment by alan-signal** [comment]
Duplicate #9151

**Comment by sifr01** [comment]
For me, the issue never was being able to verify the download. I am able to do that like [this](https://github.com/sifr01/signal_updates). The issue is that the suggested methodology is not user friendly and not accessible to the majority except power users/devs. 

There is the issue that the stable debian repos come with the apksigner version that only verifies APKs up to version 2. But rather than putting the responsibility of a security workaround on the few users that make the effort to verify their downloads, can I suggest we either push debian to bring android build tools 29.0.2 into their stable repos or could you give an alternative method of verification such as PGP or SHA checksums.

**Comment by sifr01** [comment]
I think the apksigner method of verification is not very user friendly as it is such a niche method of verification compared to other software on the internet. There is very little documentation available on the internet about this method of verification. Im afraid to ask the average user to also update their android build tools and then execute the verification methodology is a step that will prevent a lot of users from verifying what is essentially supposed to be a user friendly method of gaining security in their communication.

**Comment by EmberHeartshine** [comment]
You'll not get openwhisper to make the standalone APK more user-friendly. They seem to have an irrational hatred of ecosystems outside Google. It's the reason I have to run my own F-Droid repository to provide Signal for F-Droid instead of openehisper submitting it to the mainline repo themselves.

**Comment by sifr01** [comment]
I really appreciate your attempts to make an Fdroid repo which would make the update process both secure and user friendly. I really think bringing user friendly secure systems should be something we all work together towards. But I am very disappointed with openwhisper's lack of co-operation on their issue of verification.

**Comment by EmberHeartshine** [comment]
Yeah, me too. I've since moved over to XMPP now that OMEMO is working moderately well and haven't looked back. The iOS clients are rough but at least the Android and desktop clients work well. (I actually have a script running on one of my VPSs that checks for Signal updates and notifies me on Jabber so I can update the repo, lol)

**Comment by sifr01** [comment]
Fair enough. I much prefer XMPP and all its clients. And everything Iv read about OMEMO sounds good.

That script on your VPS sound neat! I just have a change monitor watching https://signal.org/android/apk/ to email me if the version number changes.
