### ISSUE TITLE
Media sent to V2 group by desktop client are not received by own handset

### ISSUE THREAD

**Issue by ProactiveServices** [signalapp/Signal-Android#10046]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

When sending a photo from Ubuntu desktop to a V2 group it is not received by my Android handset, unless the photo is accompanied by a caption. Both are received by other group members. Both are received by self and others in a V1 group.

### Steps to reproduce
- Join V2 group
- Send a photo via Desktop client, without a caption
- Observe own Android handset, photo does not appear
- Send a photo via Desktop with a caption
- Photo and caption appear on own handset

Ubuntu 20.04 Signal Beta 1.36.3-beta 2
https://debuglogs.org/e539d7affaba288b99a933166f5f1b401d8bcfa490b98c6104a24d1d5f8cfd28

Android 9.0 Signal Beta 4.72.2
https://debuglogs.org/90c5e2aa503e612994b7d6ddfa226fe1ae3e6bb424cbc862f5ec589759526d4b

**Comment by severus-tux** [comment]
I can confirm this issue. 

Ubuntu 20.04 Signal Beta v1.36.3-beta2
https://debuglogs.org/bbe0ab8cf251aa3370682f6d8e45d1c1a04cb950ce3c9a2e9336222a68062d12
![image](https://user-images.githubusercontent.com/21301040/94367627-90bd8f00-00fd-11eb-9f83-97e37d3b36ed.png)


Lineage OS (Android 9)  Signal Beta 4.72.2
https://debuglogs.org/6dba3653134163607d9424b5791a0b0d266defdf17f6ca31c385b4342067c13c
![signal-2020-09-27-201204](https://user-images.githubusercontent.com/21301040/94367684-e98d2780-00fd-11eb-803a-d482ebce927a.jpeg)

**Comment by ProactiveServices** [comment]
Also applies to videos.

**Comment by dinosmm** [comment]
Same thing here.
Android v4.72.2
Desktop v1.36.3-beta.2

After sending an image from the desktop to a v2 group (not showed on my phone) and the same image to a v1 group (showed on my phone)...

Debug log from desktop:
https://debuglogs.org/a71eb008f21c087118c9efef2c62bfda75d530e5ee09e3465f003881793bb19b

Debug log from phone:
https://debuglogs.org/9485fcac19d4f279185c8e8d1cb7ff9bfc511ee75fe38536df0f59984485b5e5

**Comment by ProactiveServices** [comment]
I think https://github.com/signalapp/Signal-Android/commit/caf8bb39d860675c301d20ba8188bfa04f7de592 may resolve this issue, although it doesn't reference any specific issues.
