### ISSUE TITLE
New messages don't get marked as read if the contact is typing

### ISSUE THREAD

**Issue by lnwor** [signalapp/Signal-Android#10047]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you read new messages while the contact is still writing, the messages keep appearing as unread until the contact stops typing.
### Steps to reproduce
- make your contact send you a message
- make your contact continue typing while you read the new message
- go back from the chat to notice that the messages you have read still appear as unread and the notification of the new message hasn't disappeard

**Actual result:** The messages appear as unread if the contact is typing, even if you have read them.
**Expected result:** The new messages should appear as read and the notification of those messages should disappear
### Screenshots

It's hard for me to screenshot it all

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** 4.71.5

### Link to debug log

https://debuglogs.org/866ad02adbccca8c6caac6949c4193f782959ce706d384f8db7353cc0b3f83bb

**Comment by jaeheonshim** [comment]
Can confirm, was able to reproduce this behavior on my Google Pixel XL running Android version 10, Signal version 4.71.5. I'll try looking into why this happens

**Comment by Tursko** [comment]
Can also confirm. This has been happening to me on the daily.
