### ISSUE TITLE
Signal behaves buggy/laggy in countries with censorship

### ISSUE THREAD

**Issue by VaderXA** [signalapp/Signal-Android#10043]
- [✔️ ] I have searched open and closed issues for duplicates
- [✔️ ] I am submitting a bug report for existing functionality that does not work as intended
- [✔️ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ✔️] This isn't a feature request or a discussion topic

----------------------------------------

 **Bug description**

in country where censorship is enabled there is really huge serious problems, first no profile picture appears and no typing indicator(it’s activated in both sides) also delay in sending and receiving messages(like 3 sec when sending and receiving while app in opened) in both partners, all this problems even when the partner is in your contacts too.

**Steps to reproduce**
- reset session
- reinstall the app
- and unregistered then register my number again

**Actual result**: still massages dealy no profile pic appears and no typing indicator
**Expected result**: as both are in contacts list everything should work without problems

**Device info**
Device: lenovo A7000
Android version: 8.1
Signal version: 4.71.5

**Link to debug log**
I will post the log asap

**Comment by psxda97** [comment]
Bump
