### ISSUE TITLE
No notifications and sounds when app is closed

### ISSUE THREAD

**Issue by D4708** [signalapp/Signal-Android#10051]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Device info

**Android version:** 10
**Signal version:** 1.5.4 (995)

**Comment by Nisc3d** [comment]
No, there should be Notifications. First check all the steps in this support article: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

Also please don't delete the bug report template when opening a new issue. Here is a guide to submitting useful bug reports for this project: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by D4708** [comment]
Thanks for reply, today I have successfully received, but just vibro signals without any sound alerts (enabled in the app and phone settings)... I have checked all tips from article, network and phone settings looks fine.

p.s. Sorry about template removing, will know.
