### ISSUE TITLE
Cannot answer calls, call dialog box does not appear unless I open the app and tap the phone button

### ISSUE THREAD

**Issue by capitolfrills** [signalapp/Signal-Android#10058]
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

**Bug description**
When I receive a call on Signal, I can hear the call ringing, but the dialog box to answer the call never pops up. In order to answer the call, I have to go to app, open the app, and click on the phone icon under any contact to prompt the dialog box to appear. This essentially makes the call function unusable. This has been happen for several months since an update.

**Steps to reproduce**
- Incoming Signal call is received
- Open Signal app
- Open a conversation and tap the phone icon

**Actual result:** The dialog box appears and the call can be answered.
**Expected result:** The dialog box should appear when the call is received and I should not have to open the app.

**Device info**
**Device:** One Plus 7
**Android version:** 10
**Signal version:** 4.72.5

**Comment by szotsaki** [comment]
I have experienced something similar with a Huawei phone many months ago.

I vaguely remember that I had to go into the application settings window, open a "special rights" menu and grant them the listed rights there (like be allowed to occupy the lock screen while ringing).

This is clearly Signal's fault of not requesting them and since I don't have a Huawei phone, I cannot reproduce it but if you could list the rights you found in that settings window, you could possibly help the developers a bit.

**Comment by shadowstabbing** [comment]
> 
> 
> I have experienced something similar with a Huawei phone many months ago.
> 
> I vaguely remember that I had to go into the application settings window, open a "special rights" menu and grant them the listed rights there (like be allowed to occupy the lock screen while ringing).
> 
> This is clearly Signal's fault of not requesting them and since I don't have a Huawei phone, I cannot reproduce it but if you could list the rights you found in that settings window, you could possibly help the developers a bit.

Thanks @szotsaki ! I did check for a setting like that and all permissions are allowed on my Signal app, so I'm not sure what else I could enable.
