### ISSUE TITLE
Pinned contacts drop off list if message list is empty

### ISSUE THREAD

**Issue by Benhgift** [signalapp/Signal-Android#10054]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the disappearing message timer eats the last message for a contact, that contact will drop off the pinned contacts list.

### Steps to reproduce
- pin any contact
- set disappearing messages to a small amount, such as 5 minutes
- send and receive a message
- close signal and wait until the disappearing timer finishes
- contact is now dropped from pinned list the next time you open signal

**Actual result:** Contact is removed from pinned contact list.
**Expected result:** Contact should not be removed from pinned contact list.

### Device info

**Device:** Pixel 2
**Android version:** 11 latest
**Signal version:** 4.71.5

### Link to debug log

https://debuglogs.org/320cf9b22129f1bf824652955a4a884ba089cd0724632a1038a7477cfe684a0b

**Comment by Sgn-32** [comment]
related to #10100

_Currently, when the last message in a thread is deleted, the thread itself is deleted. I can recommend either sending a "dummy" message into the thread (with countdown timer off), or not deleting the status message "Blah enabled disappearing messages". I realize these are "workarounds" but might get you to the point you want to be at. If you have suggestions for feature enhancements, the best place to post those is over at community.signalusers.org._
