### ISSUE TITLE
Remove Signal Group Member

### ISSUE THREAD

**Issue by charlyromero** [signalapp/Signal-Android#10062]
Bug description
Hi. I actually want to make an observation. Of something that would be very useful to implement. One should be able to remove a member from a Signal group while being an administrator. As indicated on this page https://support.signal.org/hc/en-us/articles/360007060712-Leave-Groups it says that a member can be removed as an administrator. But in practice this is not the case. It only allows blocking a contact within a group, even so, that contact still belongs to the group. I hope that in a next update you will incorporate this function, elementary to moderate

Device info
Device: Samsung S5
Android version: 6.0.1
Signal version: 4.72.5

**Comment by u32i64** [comment]
Removing members is already supported, but only in New Groups. Please see the [Legacy Group and New Group Features](https://support.signal.org/hc/en-us/articles/360046317752-Legacy-Group-and-New-Group-Features) support article for more details.

**Comment by alan-signal** [comment]
Yes, new groups have this ability, and more, and they are coming soon.

Please also use the community forum for feature requests https://community.signalusers.org/
