### ISSUE TITLE
Bad User Agent used for generating link preview 

### ISSUE THREAD

**Issue by LogoiLab** [signalapp/Signal-Android#10060]
- [x] I have searched open and closed issues for duplicates (Too many references to WhatsApp to find a duplicate)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal app utilizes the user agent string `WhatsApp` when querying servers for a link preview.
### Steps to reproduce
- set up a web server with logging and a default page.
- send a message to a friend with the url for a page on this test server. (do not copy and paste, type it manually)
- observe the web server's log, find `WhatsApp` user agent string.

**Actual result:** `WhatsApp` user agent string is present and in use by the Signal Android app.
**Expected result:** Signal should be identifying itself as `Signal` or some other generic web crawler.

### Screenshots

![Screenshot_2020-10-05_01-02-29](https://user-images.githubusercontent.com/5545218/95042328-08288b00-06c9-11eb-8462-e45442c27cd3.png)

### Device info

**Device:** Samsung Galaxy S9 SM-G960U1
**Android version:** 10
**Signal version:** 4.71.5

### Link to debug log
Not applicable, bug is not present in your debug log as it is a design issue.

**Comment by LogoiLab** [comment]
Line in question: https://github.com/signalapp/Signal-Android/blob/f9a9ee6b0cdb694d1d3490e96271863a224a4794/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewRepository.java#L77-L82

**Comment by LogoiLab** [comment]
Just as a comment. This looks REALLY bad from a security perspective, using the user agent of your insecure competitor. It looks a lot like copy-pasted code. Which is even more questionable.

**Comment by u32i64** [comment]
This is a duplicate of #9958. Quoting https://github.com/signalapp/Signal-Android/issues/9958#issuecomment-680845132:

> WhatsApp isn't rate-limited. This is to allow previews for specific sites like Twitter. It's funny that we need to do this yet here we are.

**Comment by Genis-Sage** [comment]
@LogoiLab 

also, please clarify, why using whatsapp as user agent is a security risk
I don't see any harm by doing that

> It looks a lot like copy-pasted code.
and also, who should someone copy-paste code from a closed source app

**Comment by LogoiLab** [comment]
@Genis-Sage it's not that its a security risk, its that Signal is an application people require trust in. Using the WhatsApp user agent causes people to question that trust. I understand the implications of rate limiting, but I am sure there is a different more generic user agent that would work better. Since this seems to be a duplicate of #9958 I will close this issue.

**Comment by greyson-signal** [comment]
@LogoiLab If you don't set your user agent to WhatsApp or Telegram, Twitter literally doesn't put the open graph tags in their response. I heard they may be changing this, but we also don't know what other sites may be doing the same thing, so for now we just kinda gotta roll with the punches. I understand it's not ideal :)

> It looks a lot like copy-pasted code.

Don't worry, typed every character myself :)
