### ISSUE TITLE
CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by testt98** [signalapp/Signal-Android#10061]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Any picture or sticker sent from Signal will not reach my correspondant.
Debug logfile mentions the following : 
 BaseJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Same issue whether I am on wifi or on data

I saw multiple posts with the same issue, but could not find out which certificate was the culprit for this malfunction.
Can someone help and explain which certificate must be installed - and how .

The app was perfectly working few days back - not sure what I did. I checked my certificate store, and all are activated (none are disabled)
I also switched on/off the phone, and reinstalled Signal - did not work better

### Steps to reproduce
Send sticker or photo to my correpondant
Message will loop indefinitely - cannot send it
Standard text messages can be exchanges (send and received)
I can receive pictures/stickers

### App
App          : Signal 4.72.5 (7142)
Manufacturer : samsung
Model        : SM-A515F
Product      : a51nsxx
Android      : 10 (A515FXXU3BTH4, QP1A.190711.020.A515FXXU3BTH4)

### Link to debug log
https://debuglogs.org/62efd45e9f12a1e805cd2789e2d119a921797fb1947c40db6d3f8db229771416

**Comment by Nisc3d** [comment]
Someone on the forum had the same problem:
https://community.signalusers.org/t/cant-send-messages-with-media-signal-4-72-5-on-android-10/17268/6

**Comment by testt98** [comment]
Yes - thanks for pointing it 
Looks like it is the same issue. I believe we just need to know **which SSL certificate is required** - and how to make sure it is installed

**Comment by nah95** [comment]
> 
> 
> Someone on the forum had the same problem:
> https://community.signalusers.org/t/cant-send-messages-with-media-signal-4-72-5-on-android-10/17268

It was me who posted on the forum. Seems like it's a device specific problem. My OnePlus 7T has issues while my 2nd account on a Galaxy S8 is working fine.

**Comment by testt98** [comment]
Samsung A51 here

**Comment by testt98** [comment]
Would be great if someone could let us know **which certificate is required for uploading media.**
I tried to search for the url on the source code, but it is too complex for me.
Thank you guys for your help

**Comment by dodyg** [comment]
Xiaomi here (Nougat)

https://debuglogs.org/79176c651d590813ee1d9a47b617f3a9a058f15db752d37c3c90d23fc8ce2049

**Comment by batirch** [comment]
Samsung A70

https://debuglogs.org/ecb00b54729403a649a1aed5de8c598b484b23a45ce82c190b9fac58a291ecbe

**Comment by Lithiumion** [comment]
Google Pixel 3

https://debuglogs.org/6fbfad5f6777ca0c8271cfc16f0344068c7a278940cc9fa5c653ae0108ab31f5

**Comment by iamhereforhelp** [comment]
Team, users from dubai and egypt here, android. No multimedia files can be sent by signal! No pics neither videos nor links or voice messages....this is since a week now. Only calls and chat works. The worst part is that i recently "converted " several people to signal and they are now frustrated..what can be done to solve the same? I can receive pics from other users from other countries.

**Comment by batirch** [comment]
> Team, users from dubai and egypt here, android. No multimedia files can be sent by signal! No pics neither videos nor links or voice messages....this is since a week now. Only calls and chat works. The worst part is that i recently "converted " several people to signal and they are now frustrated..what can be done to solve the same? I can receive pics from other users from other countries.

I can confirm. Replying to this from Dubai. My MacBook Air is sending but 2 different samsung devices do not send any type of media over a week. For nearly over a month I can't send any videos.

**Comment by Nisc3d** [comment]
Hello,
I want you to give you all a quick update.
I asked a developer on the forum and he confirmed that this is an issue that is being looked at. So they know it's happening and are not ignoring you.
Here is the link: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-73-release/17319/144?u=nisc3d

**Comment by iamhereforhelp** [comment]
Thanks for taking the time to do that Nisc3d, and also keeping us posted about it :)

**Comment by greyson-signal** [comment]
Hey folks, we figured this out and a fix will be out in the next beta release, which will likely be tomorrow. Thanks for your patience!

**Comment by batirch** [comment]
Hi @greyson-signal Samsung Galaxy S9 phones didn't receive any updates yet. When will be released for all devices?

**Comment by greyson-signal** [comment]
@batirch The release is still in beta. If you'd like to get it now, you can join the beta, or sign up to get releases through [Firebase App Delivery](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538).

**Comment by dodyg** [comment]
I joined the beta and got Signal 4.74.1. It works. Thank you!

**Comment by mmBesar** [comment]
> Hey folks, we figured this out and a fix will be out in the next beta release, which will likely be tomorrow. Thanks for your patience!

Sorry but this is not good enough, I'm using Signal as my main messaging service and I "forced" all my friends and family to contact me using it. Now I don't have Google on my phone, so I couldn't get the beta release! My family and friends they don't even know what is beta! Now they all agreed that Signal is not a reliable service! So I'm forced to use Telegram to keep my life going!

Why are you guys doing this to me, I forced my self to live with this [ignored issue](https://github.com/signalapp/Signal-Android/issues/9638).

I love Signal, but you need to help Signal to grow!

**Comment by jabu325** [comment]
To who ever it may concern, i was able to solve this problem which was caused when a friend accidentally disabled some certificates in my settings. 

this guy really helped

https://youtu.be/BlTYMOZsyO8?si=So-xiTPDyhH5vj0R
