### ISSUE TITLE
"Smiling Face with Tear" missing from available Reactions.

### ISSUE THREAD

**Issue by iago-lito** [signalapp/Signal-Android#10068]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Arbitrary reactions are now supported by Signal, which is awesome and closes #3986.
Well.. almost arbitrary. There is at least 1 missing reaction, the ["Smiling Face with Tear"](https://emojipedia.org/smiling-face-with-tear/), a recent (2020) addition to Unicode 13.0.

How often is the set of available reactions updated with respect to Unicode and Emoji standards? Do we just need to wait a bit or is adding missing reactions a more involved process?

This is it, thank you for Signal anyway :')

**Comment by greyson-signal** [comment]
Hi there, our entire emoji library is one version out of date, so I'm sure there's a slew of other missing emoji. I'm waiting on the emoji library to update, and then a few related issues will get fixed. We can track it here: #10002
