### ISSUE TITLE
Signal sending the wrong attachment

### ISSUE THREAD

**Issue by sorcix** [signalapp/Signal-Android#10066]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal sometimes sends the wrong attachment (other file from my phone, or even something that's shared in a different conversation) instead of the file/picture I selected. Sometimes it also sends a second file together with the one I selected.

### Steps to reproduce
I have not found a good way to reproduce it, most of the time sending files works as expected.

**Actual result:** Signal sends wrong file (or selected file + wrong file)
**Expected result:** Signal sends selected file

### Device info

**Device:** Oneplus 5T
**Android version:** 10 (2005130017, ONEPLUS A5010_43_200513)
**Signal version:** Signal 4.72.6

### Link to debug log

Debug log from a week ago, on an older version:
https://debuglogs.org/db19e02f4d8a1c3d624e168d89eca3292636efc26257ffea4ba88fbeba5e9ede

Forgot to save the debug log when it happened with 4.72.6 today, will post new ones when it happens again.

**Comment by Genis-Sage** [comment]
hey @sorcix 

when you attach a file, signal still waits for you to press the send button

do you already see the wrong file in the "message preview", or only after pressing the send button?

does it happen for all file types?

how to you choose files? do you choose picture from the photorail? do you use the share menu from another app?

**Comment by sorcix** [comment]
It once sent a docx instead of an image (that I selected in the the photorail). As I mainly send images and it doesn't happen that much I don't know if it would happen when sending other file types. I don't remember seeing the wrong images in the preview.

I've waited a long time to submit this as it doesn't happen frequently, should have collected logs every time it happened though.

**Comment by sorcix** [comment]
I'll close this until it happens again and I can give more useful input. :smiley:
