### ISSUE TITLE
New messages delayed until pop-up/notification closes

### ISSUE THREAD

**Issue by nitrox-github** [signalapp/Signal-Android#10064]
### Bug description
Upon receiving a new message, I have to wait for it to appear in the main messaging area. Its delayed until pop-up/notification closes. I´d not call it a bug, more a minor annoyance.

**Actual result:** ...wait...
**Expected result:** Show up immediately, so i can read or answer from the main messaging area. That was the default behaviour 2-3 releases ago *iirc*.

### Device info
**Device:** Pixel 3
**Android version:** 11
**Signal version:** currently on 4.72.6, but showed up a few releases before

**Comment by luser** [comment]
I've noticed this recently as well. I think it might be a regression on Android 11? I was using the app on my Pixel 3 with Android 10, but I bought a Pixel 4a that shipped with Android 11 and that's when I started noticing the issue.

**Comment by nitrox-github** [comment]
That would be a good catch, it might indeed relate to going from Android 10 -> 11.

As there are not that many who made the switch (non Pixel-device :-)) we might just be among a few out there experiencing it.

**Comment by 0660fi** [comment]
I also have had this issue for some time now with Pixel 3 and Android 11.

**Comment by rt-chang** [comment]
I will add that I have also been seeing similar behaviour recently.
I usually have to exit out of my current conversation to the main list of conversations, and then re-open the specific conversation to have it "refresh"

OS: Android 11
Device: Pixel 2
Signal Vers: 4.76.2

**Comment by nitrox-github** [comment]
Disabling "bubbles" in notifications seemed to have fixed it...

**Comment by greyson-signal** [comment]
Lmk if this gets better in 4.79.2 :+1:

**Comment by nitrox-github** [comment]
Everything ok, thx!
