### ISSUE TITLE
Unable to open the share menu to share a received picture to another app (mail, message,...) 

### ISSUE THREAD

**Issue by MuadDibIII** [signalapp/Signal-Android#10078]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Genis-Sage** [comment]
hey @MuadDibIII 
as you did not really fill out any text in the template, I can only guess from the issue name:

this is simply not implemented right now, so it is not a bug, but a feature request, so please got to the community forum:
https://community.signalusers.org/t/share-to-another-app/3396

**Comment by MuadDibIII** [comment]
Thank you very much for your quick reply, 



You were right about my request, I just saw the thread... 

Can I ask you if you count to implement the option? As I understand from the thread, it exists on iOS, so why not make it possible on Android? 



thanks again,

Marc



De : Genis-Sage <notifications@github.com>
À : signalapp/Signal-Android <Signal-Android@noreply.github.com>
Sujet : Re: [signalapp/Signal-Android] Unable to open the share menu to share a received picture to another app (mail, message,...) (#10078)
Date : 12/10/2020 10:28:54 Europe/Paris
Copie à : MuadDibIII <mdii@netc.eu>;
   Mention <mention@noreply.github.com>


hey @MuadDibIII
as you did not really fill out any text in the template, I can only guess from the issue name:

this is simply not implemented right now, so it is not a bug, but a feature request, so please got to the community forum:
https://community.signalusers.org/t/share-to-another-app/3396

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
