### ISSUE TITLE
Audio feedback when talking and can hear myself talk and recipient getting middle of sentence when talking

### ISSUE THREAD

**Issue by Goldmaster** [signalapp/Signal-Android#10077]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are seamingly random times when I video call that I would hear myself when talking on my own phone. it's as if there's feedback. then if I'm doing something like typing on my laptop, I can hear the sound of myself typing on my own phone. My recipient will often complain that they can only hear the middle of the sentence and not the 1st and last part if I'm talking for a long period. Im not sure if its an internet issue as my device is on 5mb up and 100mb down. but my recipient is on less than a mb up and 5mbps down.

### Steps to reproduce
- video call with someone on Samsung s10 and a Nokia 5 android phone both running the latest signal version.
- make sure to video call along with having loud speaker sound enabled as well as camera.

**Actual result:** you should hear the sound of your own voice when talking with about a second delay and when typing on a computer, you would hear rustling or a keyboard typing sound on your phone. the recipient may only hear the middle of the sentence when the user is talking for a while and not the full sentence.
**Expected result:** recipient should be able to hear the full sentence and user shouldn't have feedback and shouldnt hear there own voice or any other background sounds.

### Screenshots
No screenshots as this is an audio issue

### My Device info

**Device:** samsung S10
**Android version:** 9
**Signal version:** 4.73.2

### My recipemnts Device info

**Device:** Nokia 6
**Android version:** 7
**Signal version:** 4.73.2

### Link to debug log

Samsung s10
https://debuglogs.org/a4ee5de1750e5349c23b8aba27910d6ba32650dd2d7b4370721fb7265de9ce98 This is my phone

Will try and get debuglog for Nokia phone if possible.

**Comment by alan-signal** [comment]
Please tell us if this is new to this version or not.

**Comment by Goldmaster** [comment]
Hi there, this has happened in previous versions before.

**Comment by PrSunflower** [comment]
Hi, just to inform that some people like me are having a similar problem with Nokia 7.2: https://github.com/signalapp/Signal-Android/issues/9817 
Whenever I make/receive an audio/video call on Signal, my correspondent hears themselves. On my end everything works fine.

**Comment by yogeshpaliyal** [comment]
Also facing problem in redmi 6

**Comment by PrSunflower** [comment]
Hi, problem has been fixed on my Nokia 7.2. Could you update Signal on your phones and try?

**Comment by PrSunflower** [comment]
Hi @jimio-signal , I saw your comment on 9817 and I think this issue is worth closing too 😄
