### ISSUE TITLE
'Mute' option missing from context menu on Group V2 chats

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#10088]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The mute option doesn't show on the context menu for a Group v2 group. Although, you will see the 'unmute' option if the chat is already muted, or you go into the group settings and mute.

### Steps to reproduce
- Create/Open/Join a Group V2 group
- Try to mute the chat using the 3 dot menu
- Option to mute isn't on the list

**Actual result:** Mute option isn't on the list, but unmute will be listed if the chat was previously muted. 
**Expected result:** Mute option should be on the list

### Screenshots

![Screenshot_20201015-111221~2](https://user-images.githubusercontent.com/18274896/96164970-a09ce780-0ee1-11eb-85f5-ced5ede4c0fb.png)
![Screenshot_20201015-111200~2](https://user-images.githubusercontent.com/18274896/96164980-a4306e80-0ee1-11eb-83ff-a5a42fa5400b.png)

### Device info

**Device:** Pixel 4
**Android version:** 11
**Signal version:** 4.73.4 -> 4.74.3

**Comment by Tursko** [comment]
This issue still exists in 4.74.3

**Comment by marxistvegan** [comment]
This is happening again, using the Beta version. version 5.3.6

**Comment by Tursko** [comment]
> This is happening again, using the Beta version. version 5.3.6

It's not a bug, it's an intentional change.

**Comment by marxistvegan** [comment]
> > This is happening again, using the Beta version. version 5.3.6
> 
> It's not a bug, it's an intentional change.
> 
> https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-75-release/17727/67

I looked at the thread but did not see an explanation, seems like a good fair to me for a l period of time, no?

**Comment by Tursko** [comment]
> > > This is happening again, using the Beta version. version 5.3.6
> > 
> > It's not a bug, it's an intentional change.
> > 
> > https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-75-release/17727/67
> 
> I looked at the thread but did not see an explanation, seems like a good fair to me for a l period of time, no?

The answer is the post that's linked. The mute settings are moved to the group conversation settings. 

So you'll still see the mute option in group v1 groups and 1-1 chats, but it was removed from the context menu on Group v2 chats.

**Comment by marxistvegan** [comment]
Yeah I will go that route, it is a helpful feature when a group chat messages so much and need to mute it for a period of time with less steps.

**Comment by Tursko** [comment]
> Yeah I will go that route, it is a helpful feature when a group chat messages so much and need to mute it for a period of time with less steps.

I went ahead and created a topic.

https://community.signalusers.org/t/re-add-option-to-mute-gv2-chats-via-the-context-menu/26284
