### ISSUE TITLE
Messages not delivered due to SignalServiceMessageSender: java.io.IOException: No connection!

### ISSUE THREAD

**Issue by ydinath** [signalapp/Signal-Android#10082]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug Description

I've been having the same issue for a bit now, but haven't found a way to reliably reproduce.
When this happens, I only see the one checkmark like in the screenshot of the original description.
If I continue to send messages shortly after, one of them will work, and will trigger the rest.

> does this only happen from your desktop? or does this also happen if you send a message from your phone?

This issue occurs on both the desktop application and through the app. Doesn't matter if it's quick reply or not either

> can the person receive messages from other persons?

Yes

> can you send other persons messages?

Yes

> can the person send messages to you and you receive them?

Yes

In the situation below, _A_ always seems to receive the messages from _B_, but _B_ doesn't always receive the messages from _A_.

Signal _A_ log: https://debuglogs.org/717d1cb4e1015a0a55662c765ca7927a0871ef94192491ab24b9100dc99872e5
Signal _B_ log https://debuglogs.org/98e143cdf08528e1d9c552755df1b6401a10c9ce48345818babe3e18a94fdc23

_A_ sent: `2020-10-11 15:34:03.327`
Conversation is initiated. Message sent and delivered
_B_ received: `2020-10-11 15:34:04.320`

_B_ sent: `2020-10-11 15:34:46.501`
Message sent and delivered
_A_ received: `2020-10-11 15:34:47.009`

_A_ sent: `2020-10-11 15:34:53.482`
Message sent and delivered
_B_ received: not really sure when, but between `2020-10-11 15:34:53` and `2020-10-11 15:34:54`

_B_ sent 2 separate messages: `2020-10-11 15:34:58.065` and `2020-10-11 15:35:02.944`
Message sent and delivered
_A_ received: `2020-10-11 15:34:58.736` and `2020-10-11 15:35:03.234`

_A_ sent (through quick reply in notification): `2020-10-11 15:35:10.408`
**NOT Delivered**

_A_ sent (through app): `2020-10-11 15:35:52.229`
**NOT Delivered**

_A_ sent: `2020-10-11 15:36:16.096`
**NOT Delivered**

_A_ sent: `2020-10-11 15:36:45.579`
The three previous plus the latest have been marked as delivered. 
_B_ received: not really sure when, but between `2020-10-11 15:36:46.500` and `2020-10-11 15:37:10.129`

_B_ sent: `2020-10-11 15:37:10.129`
A received it (but not in log)

-------------------------------------------------------------------------------

I have another case where _C_ sends messages to _A_, and _A_ receives them much later in the future. In this case, messages were sent on 2020-09-14 and 2020-09-22 from _C_, but only received by _A_ on 2020-10-09 when _A_ sent message to _C_.
_A_ side only: https://debuglogs.org/5f1573a94dab4e65adca8105f5ca7d555c2aaec9a53c0391bd0bfc1adf79fafc

_A_ sends `2020-10-09 15:19:23.286`
_A_ receives 4 message at `2020-10-09 15:19:30.801`. Timestamps of messages are
Sent by _C_: 2020-09-14 19h24min19s
Sent by _C_: 2020-09-14 19h25min34s
Sent by _C_: 2020-09-25 15h19min35s
Photo sent by _C_: 2020-09-25 15h19min36s

-------------------------------------------------------------------------------

If you think of a way to reproduce when you check the logs, please let me know and I'll try

### Steps to Reproduce
Not able to reliably reproduce, but it happens rather frequently with no common theme.
Actual Result: Messages not delivered.
Expected Result: Messages should be delivered.

### Screenshots
N/A

### Platform Info
See logs

### Link to Debug Log
See Bug Description

**Comment by ydinath** [comment]
Any update on this? It's making Signal unusable for me.

**Comment by androdebugur** [comment]
Does this happens when you are using mobile data?
Can you try and post if this happens also on wifi? Please make sure the wifi is not using mobile data but cable ethernet or fiber connection.

**Comment by ydinath** [comment]
This happens with only one friend.
Their WiFi at home is through a mobile connection, but when connected to that, their phone doesn't seem to have an issue.

But when connected directly to mobile, this issue occurs.

Let me know how I can narrow this down further for you.

**Comment by ydinath** [comment]
Additional info: both connections are with Rogers.
Mobile connects directly to Rogers tower doesn't work.
Mobile connects to WiFi, which connects to Rogers tower works.

Basically, I can't message them anytime they leave the house.
