### ISSUE TITLE
[Feature Request] Support for blob emoji

### ISSUE THREAD

**Issue by Oymate** [signalapp/Signal-Android#10086]

**Comment by Cerberus0** [comment]
Hi @Oymate,

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this over to the [community forum](https://community.signalusers.org/). Thanks!
