### ISSUE TITLE
Help screen does not make a email draft properly

### ISSUE THREAD

**Issue by Oymate** [signalapp/Signal-Android#10087]

**Comment by Meteor0id** [comment]
Without any information this bug ticket is useless, on my device the help screen does create a perfectly fine email draft.

How come this ticket hasn't been closed yet? Seems it just hadn't been read?

**Comment by Oymate** [comment]
The issue seems to be present on tutanota and protonmail but not on gmail.

**Comment by Oymate** [comment]
Ping

**Comment by cody-signal** [comment]
Not enough details.
