### ISSUE TITLE
Create backup option in settings does nothing

### ISSUE THREAD

**Issue by cbondurant** [signalapp/Signal-Android#10080]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am completely unable to make backups of my chat history for transfer to a new phone. 

### Steps to reproduce
- Open Signal
- Go to settings
- Chats and media
- Create Backup

**Actual result:** The create backup option flashes as if pressed and nothing occurs, continues to say "Last Backup: Never"
**Expected result:** The backup should begin to be created.

### Device info

**Device:** LG Velvet
**Android version:** 10 (Phone refuses to give more detail here)
**Signal version:** 4.72.5

### Link to debug log

https://debuglogs.org/565b9801a2d0aa05b019ba1868303ec00c7b83c0324e1eb87088deef6e09fce8

**Comment by Sgn-32** [comment]
Please update to 4.73.4. This version has a fix for manually updates working as expected.
