### ISSUE TITLE
Profile Picture from phone contacts streched in Signal when maximized

### ISSUE THREAD

**Issue by longride** [signalapp/Signal-Android#10094]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes Signal displays pictures I set myself from my phone contacts as profile pictures in Signal. So far so good. When I maximize these profile pictures in Signal, they get displayed streched. While they are little, they are ok. Only when maximized. they get streched to become smaller in the horizontal axis by a bit. Profile pictures set in Signal by my friends themselfs do not get streched.

### Steps to reproduce
- Maximize Profile Picture signal took out of my phone contacts.

**Actual result:** Profile Pictures get streched to become smaller in the horizontal axis by a bit.
**Expected result:** No distortion of the Profile Picture when maximizing it.

### Screenshots

Screenrecording provided to Gregg over private Signal message.

### Device info

**Device:** Google Pixel 3a
**Android version:** Android 11 with GrapheneOS, no Goolge Play Services
**Signal version:** Beta 4.74.0

### Link to debug log

https://debuglogs.org/51136522828ca9da834d6aedd3264c943ab48eea6d9c0012de38da3c856384f8

**Comment by longride** [comment]
still present on some contacts in Signal 5.30

**Comment by alex-signal** [comment]
Sounds like a scaleType isn't set. Thanks for the report!
