### ISSUE TITLE
Problem with opening PDF file from app

### ISSUE THREAD

**Issue by DirkPitt1** [signalapp/Signal-Android#10096]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my contacts have sent me some PDF file through Signal. Then they tried to open the sent file from Signal app and got error message about wrong file type, even though they can open the file from their phone and I don't have problem with opening it from Signal. I attached their debug logs.

### Steps to reproduce
- send some pdf file
- tap the file in the Signal app

**Actual result:**
Error message about wrong file type.

**Expected result:**
File gets opened in PDF viewer app.

### Device info

**Device:** KrugerMatz 5 Flow 5
**Android version:** 7.0
**Signal version:** 4.73.4

### Link to debug log

https://debuglogs.org/cb497a588788422c60a8956b9812f27e60b2807d029e0305417fdec68b70d5fd

**Comment by wislander9** [comment]
I'm facing a similiar issue. I received two pdf files. If I try to open these two files inside the app, a toast is coming which says "file corrupted" (rough translation from german)
After saving the files to the storage I am able to open the files and everything works. No corrupted files.
I can provide logs if needed.

**Comment by WarmongeringBeaver** [comment]
May be related to [issue 8561](https://github.com/signalapp/Signal-Android/issues/8561).

**Comment by ka223** [comment]
My PDF file was sent with the correct name, but when I tap it, "Error opening file".
Maybe related to this issue?

**Comment by cressidacressida** [comment]
I still experience this bug with Signal 5.41.14 on Android 6

**Comment by cressidacressida** [comment]
@alex-signal can this be reopened?

**Comment by alex-signal** [comment]
Hello! Unfortunately the debug log originally posted has expired. If you are still seeing this issue, please post another debug log here so we can take a look :)

**Comment by cressidacressida** [comment]
Hi, here is the log: https://debuglogs.org/android/5.42.8/bd1124d9206262f9181556f5ffd50b514007786dc82fe481c772ed2525770a3f

What I experience is that when someone send me a pdf and I try to open it in the app, I get the error "file corrupted" or similar.
Whereas if I download the file first and then open it with the same viewer, it works.

**Comment by Rihcus** [comment]
Same issue
