### ISSUE TITLE
Recording voice message with handset to ear does not blank screen

### ISSUE THREAD

**Issue by ProactiveServices** [signalapp/Signal-Android#10098]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While recording a voice message via the locking input method, when the handset is raised to ear the screen remains active. This allows for accidental pressing of the profile / call elements, OS draw-down menu etc., all of which interrupt recording and cause unwanted UI input.

### Steps to reproduce
- Start recording a voice message via locking input method
- Hold handset to ear
- Repeat until your ear presses some UI elements
- Observe that your ear does not respond to requests not to interrupt. Ears do whatever they want.

**Expected result:**
Screen blanks while handset is raised to ear to prevent accidental UI input.

**Device:** Huawei P20 Lite
**Android version:** 9.0
**Signal version:** 4.74.0

### Link to debug log
https://debuglogs.org/45df57133574cc15053d039ff89b76941bcef3344a64ea75a0a05008c629715f

**Comment by EnasKaram** [comment]
https://github.com/signalapp/Signal-Android/pull/10198

**Comment by EnasKaram** [comment]
So I have tried more and more times to solve this, but finally I found that it's a solo issue and after checking Huawei support website
that there are some solutions that you can perform may help to solve this:

https://consumer.huawei.com/uk/support/content/en-gb00451600/

1- Lock and unlock the screen to exit Mistouch prevention without covering the top of the screen. Alternatively, press the Volume up and Power buttons simultaneously to exit Mistouch prevention.
2-Check to see if the proximity sensor is blocked by oil, moisture, the screen protector, or the protective case (the position of the sensor varies depending on the phone model). If so, clean the top of the screen with a clean tissue or cloth.
3- If the issue persists, back up your data, update the system to the latest version, then restart your phone and try again.
4- If the issue still persists, you may have deleted a system file by mistake. Restore your phone to its factory settings and try again.
5- If the issue remains unresolved, take your device and proof of purchase to an authorised Huawei Customer Service Centre for assistance.

**Comment by ProactiveServices** [comment]
> So I have tried more and more times to solve this, but finally I found that it's a solo issue and after checking Huawei support website

#1 doesn't work for me but disabling the feature entirely seems to have resolve this for me, as well as playback problems at https://github.com/signalapp/Signal-Android/issues/7576. I'll be slightly mortified if this is the root cause as I ought to have guessed as much.

**Comment by ProactiveServices** [comment]
Just had the playback issue recur whilst "mistouch prevention" is still disabled. If these issues share a common root, it's not that.
