### ISSUE TITLE
Audio device is switched back to default when a person picks up the call

### ISSUE THREAD

**Issue by maximbaz** [signalapp/Signal-Android#10097]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When making a call and changing audio device, as soon as a person picks up the audio device is reset back to the original value.

### Steps to reproduce

- Connect a bluetooth headset.
- Now imagine your headset is in different room, and you want to make a call using phone itself.
- Start a call (it's going through bluetooth device by default)
- Before the person picks up, switch audio device from "Bluetooth" to "Phone earpiece"
- When the person picks up the phone, the audio device...

**Actual result:** is switched back to "bluetooth", leaving me wondering why I suddenly cannot hear them and why they cannot hear me
**Expected result:** is still "phone earpiece" as I have just configured it

### Screenshots
N/A

### Device info
**Device:** Samsung A50
**Android version:** 10
**Signal version:** 4.73.4

### Link to debug log
https://debuglogs.org/88b691dcc43ea7edf47a04e1b8819d9bf06f5ca8127711bd93222b1b50af8e57

In this debug log, I make a call, switch from bluetooth to "phone earpiece", then person picks up, I switch again from bluetooth to "phone earpiece" and end the call.

**Comment by patryk-siewiera** [comment]
i could confirm this issue

**Comment by cody-signal** [comment]
Please try the latest beta, it has some fixes around audio routing. If still encountering the issue, updated debuglogs would be helpful.

**Comment by maximbaz** [comment]
It does not reproduce on the current version, thank you for the fix!
