### ISSUE TITLE
"No link preview available" above input field after sending link before preview generated

### ISSUE THREAD

**Issue by longride** [signalapp/Signal-Android#10093]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pasting a link into the type field and sending before preview gets generated. The message "No link preview available" stays above the now empty input field.

### Steps to reproduce
- Past link and send before preview is generated

**Actual result:** "No link preview available" stays above the now empty input field.
**Expected result:** Link preview is still generated and displayed after sending. Or not. In either case no message should be displayed above input field.

### Screenshots

![signal-2020-10-16-091142](https://user-images.githubusercontent.com/66530025/96236988-08643880-0f9d-11eb-93d6-3f934e248db4.png)

### Device info

**Device:** Google Pixel 3a
**Android version:** Android 11 with GrapheneOS, no Goolge Play Services
**Signal version:** Beta 4.74.0

### Link to debug log

https://debuglogs.org/4cdb3289227ceefd967f3f0573f3c1166acecb442d9b6ef2c1553579ac7b3c31

**Comment by hiqua** [comment]
This bug is still here as of 5.19.4:
https://debuglogs.org/4bd85ac8a293f55e1ac7a9b36bd0576b3e52caaaeff0dbdd2f500fbc7a91cd53
![signal-2021-08-08-231150](https://user-images.githubusercontent.com/3812042/128645976-00b1bb3e-8151-4b25-b068-d7483f9bcd4a.png)

**Comment by cody-signal** [comment]
This may be fixed in 5.20.2: https://github.com/signalapp/Signal-Android/commit/2bac1a7707c8e01d8ac9fca2c885c173e5a0b111

**Comment by longride** [comment]
seems to not occur anymore on 5.20.2
