### ISSUE TITLE
targetSDK 29 - FileNotFoundException Bug for New App Installations Only

### ISSUE THREAD

**Issue by brandnewx** [signalapp/Signal-Android#10095]
### Bug description
Apparently, the latest targetSDK 29 will work without any problem for app upgrade on Android 10, but if you install from scratch, it will throw these FileNotFoundException when you try to open media gallery to pick images to send. All file access permissions had been granted.

### Steps to reproduce
- Open a conversaion.
- Click media icon.
- All images are blank. Logcat will print a bunch of FileNotFoundException.
- Pick a blank image in the list.
- Click send.
- Get FileNotFoundException once more and the image wasn't uploaded.

**Actual result:** Got FileNotFoundException and blank image thumbnails.
**Expected result:** Images in gallery should be shown and image should be able to be sent without FileNotFoundException.

### Device info

**Device:** Samsung S9+
**Android version:** 10
**Signal version:** 4.74

**Comment by Nisc3d** [comment]
Can you capture a debug log please?

**Comment by bme13** [comment]
I had the same issue here and was about to create a debug log but first checked the latest commits. After updating to 4.74.3 this is fixed for me.

**Comment by brandnewx** [comment]
> I had the same issue here and was about to create a debug log but first checked the latest commits. After updating to 4.74.3 this is fixed for me.

Yes, apparent it was fixed in the [4.74.3 commit](https://github.com/signalapp/Signal-Android/commit/dc64a186d55a84444b294b0d9981cf2fe7be63c9)
