### ISSUE TITLE
Contact disappear when all countdown of messages are finished

### ISSUE THREAD

**Issue by freeroot** [signalapp/Signal-Android#10100]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Contact disappears in main display (disusssion list of contact) when the last message configured with a countdown to disappear is done.
It produces even if it's a pinned contact and it's make me frustration for use countdown whereas I like this functionnality.

### Steps to reproduce
- write a countdown message to a contact with no message yet.
- wait to the countdown to finish
- this contact disappears in main page/discussion list.

**Actual result:** Contact disappear.
**Expected result:** Contact is still here.

### Device info
**Signal version:** 4.73.4

**Comment by Meteor0id** [comment]
Whg should it work the way you expected it to work? It might have been designed to delete the whole conversation once no more messages are left, and it could actually be practical to have it wirk that way. I'm not so sure this is a bug.

**Comment by freeroot** [comment]
I believe it's a bug because messages with countdowns are unusable everyday because of this behavior.

Countdown can be set for each contact, so countdown can be the rules and not only exceptions.

When it's a rule for every messages, delete the conversation itself is a really issue. When it's not the rule, I understand that it was thinking as you describe and not be a bug.

**Comment by freeroot** [comment]
Maybe delete conversation when not messages should be done only if it's not a pinned conversation ? Just an idea.

**Comment by freeroot** [comment]
Another idea to fix this issue could be to create something call "pinned contact" to prevent for deleting when no message in a conversation even if it's because of automatically deleting by countdowns.

**Comment by freeroot** [comment]
But for the moment, there is no solution to using countdown messages as well, so I continue to believe that is a bug.

**Comment by alex-signal** [comment]
Currently, when the last message in a thread is deleted, the thread itself is deleted. I can recommend either sending a "dummy" message into the thread (with countdown timer off), or not deleting the status message "Blah enabled disappearing messages". I realize these are "workarounds" but might get you to the point you want to be at. If you have suggestions for feature enhancements, the best place to post those is over at community.signalusers.org.
