### ISSUE TITLE
Signal Not Requesting Storage Premission When Trying To Update Group/Profile Photo

### ISSUE THREAD

**Issue by chantisnake** [signalapp/Signal-Android#10104]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Typically, if storage permission is not given, then Signal will request storage permission when the user uses a feature (send photo) that require storage permission to work.
However, when user are trying to update group photo, there is no permission request dialog, there is simply a blank screen there.

### Steps to reproduce
- create a signal group
- revoke the storage permission for Signal
- go to group setting (or personal setting)
- click the pen (edit) button on the top right to "Edit the group name and photo" (or go into your personal profile page)
- click on the current group/profile photo 
- Select "Choose from gallery"

**Actual result:** The image selection screen will be blank
**Expected result:** Signal would request the storage permission from the user: if the permission is given, then show all the media; if not, exit the image selection screen.

### Device info

**Device:** Oneplus 7T
**Android version:**  10
**Signal version:** 4.73.4

**Comment by cody-signal** [comment]
Can you try on 4.75.7?

I believe this commit fixed the issue: d36ec9af4

**Comment by chantisnake** [comment]
I have joined the beta and can confirm that this is fixed in 4.76.2
