### ISSUE TITLE
Setting a message disappearing time limit does not clear all history from that moment forward.

### ISSUE THREAD

**Issue by Swoy** [signalapp/Signal-Android#10101]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When chosing a message time limit of say 1 day, entries such as call logs (missed and incomming) and the disappearing message status does not get cleared after the time frame has been consumed.

### Steps to reproduce
- Open the Signal App on either your Desktop or your Handheld device.
- Ensure that your Signal App is running the latest public version.
- Create a new chat with someone in your contacts list.
- Set the time limit for messages to 1 minute.
- Write a message and post it to the chat.
- Make a call to your contact.
- Wait one minute and observe the issue.

**Actual result:** When following the steps to reproduce, only messages posted to the chat will disappear after the set amount of time. Other entry types will linger until you either delete the entire history of that session, unlink or re-install the app.

**Expected result:** All entries from after the time frame was set should be cleared.

**Additional information:**
Several items has mentioned this and similar issues in the past, but no fix seems to have made it into stable. 
(#4190, which is noted as fixed in [d7e4928](https://github.com/signalapp/Signal-Android/commit/d7e4928f22e0a0e123eadd7442c32296b6eb6fad))
(#9002 seems to be a PR that apparently implements features that could fix this issue, but it was closed due to an [issue](https://bugs.chromium.org/p/project-zero/issues/detail?id=1943) that has later been resolved)

### Screenshots
![image](https://user-images.githubusercontent.com/5272077/96366124-cb877580-1145-11eb-882e-68978dc937b7.png)

### Device info
**Device:** Desktop App
**Signal version:** v1.37.1

### Link to debug log
Nothing in the logs can shed light on this issue.

**Comment by Meteor0id** [comment]
This is not a bug but a design choice. It has often been discussed on the forum and many people have requested to also delete any mention of calls. Yet again, this isn't a bug.

**Comment by landry314** [comment]
well it is a security flaw then. to leave records of calls in a private messenger by default is a security problem.

**Comment by Swoy** [comment]
I also think this deserves a reopen. I don't think disclaiming this as a design choice is the right route to take here.
