### ISSUE TITLE
Failing to Send SMS messages longer than 160 characters

### ISSUE THREAD

**Issue by Ninjawolf0007** [signalapp/Signal-Android#10111]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending an SMS message that is over 160 characters to a number that is not registered with the Signal App, the sending will always fail.

### Steps to reproduce
- Find contact with a number that is not linked/registered with the signal app to send an unsecure SMS to
- Type out a message that is over 160 characters
- Make sure that WiFi or Mobile Data or Both are turned on or off (it doesn't make a difference in the bug)
- hit send

**Actual result:** The message will fail to send. When trying to resend, the message will continue to fail. When looking at the error information, the app will say "Some issues need your attention." with an option to resend and the resend will fail.
**Expected result:** The message should be broken into 160 or fewer character segments and be sent to the recipient

### Screenshots

![e917e8d0253313068a35b84a91bc5c001b617d564a39a32966cbb2941af02fe6](https://user-images.githubusercontent.com/11599572/96650777-0f6eac00-12f9-11eb-8e21-00afd013254a.jpg)
![5027db9a7313fff9947f0ae99be2e81b05915f2757b1ca1ec16a2399c9ed2992](https://user-images.githubusercontent.com/11599572/96650784-11d10600-12f9-11eb-8a08-8fd7fb3e0377.jpg)

### Device info
**Device:** Samsung SM-G960U
**Android version:** 10
**Signal version:** 4.73.4 (7202)

### Link to debug log
https://debuglogs.org/23c96d5dcd43949dcf9c0b2cde808c069a828da630217ed2d3c7281a5e5c6beb

**Comment by Ninjawolf0007** [comment]
Yes, this is still relevant. I'm not sure what's blocking the message from sending and I'm not sure how to figure that out in all honesty.

**Comment by cody-signal** [comment]
Can you provide an updated debuglog?

**Comment by Ninjawolf0007** [comment]
Here is the most recent debug log. This happens with every message that's longer than 160 characters and it doesn't matter if my data is on or off. It always fails to send. https://debuglogs.org/android/5.31.6/6c049cf5d9d7d7c98118f95a7d356c59d5db0286c882a59b8f6b8e8929a32dae

**Comment by greyson-signal** [comment]
Hi there, unfortunately all of the logs have expired. Can you please upload a new one when you get a chance? Thanks!

**Comment by Ninjawolf0007** [comment]
Sorry for the late reply. Here is a new debug log.
https://debuglogs.org/android/5.39.3/de297f0beb6796699221f4db90e2c022bb1c619d92a2440c284a4f78985f9704

**Comment by cyb3rko** [comment]
SMS messages are no longer supported by Signal, so this issue is no longer necessary
