### ISSUE TITLE
Calls only ring on desktop, not on phone, if desktop app is running (intermittent)

### ISSUE THREAD

**Issue by dinosmm** [signalapp/Signal-Android#10112]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If one or more desktop apps are running and connected, incoming Signal calls only ring on the desktop apps. The phone does not ring. If the call is missed, I see a missed call notification after the caller has hung up.
This seems to be intermittent. It does not happen all the time.
Empirically I am seeing this about 70% of the time. 
I have checked all battery optimisation settings etc.

### Steps to reproduce
- Open a desktop app.
- Receive an incoming call

**Actual result:** 
Phone does not ring. Missed call notification is shown if caller hangs up.
**Expected result:** 
Phone should ring.

### Device info
**Device:** Samsung Galaxy S20 5G
**Android version:** 10
**Signal version:** 4.74.2 beta

### Link to debug log
The following logs are from the devices receiving the incoming calls, and contain 3 incoming calls as follows:
1st call - phone did NOT ring, desktop rang
2nd call - both devices rang
3rd call - phone did NOT ring, desktop rang

Debug log from phone:
https://debuglogs.org/fadb8229649bda2b705188df140b80ccd3896d097c51fcccd5ae1e9eb3dd4c93

Debug log from desktop:
https://debuglogs.org/426259d1c2588fd126f61ec204bcdd7c8890d6c82aff73e2303261d79ddb85d0

**Comment by CGA11** [comment]
This has also started happening to me lately, highly inconvenient if I leave the computer on at home while away. Results in lots of missed calls.

**Comment by jeee** [comment]
I have the same; only desktop is ringing.

**Comment by Tronic** [comment]
Still happens and is relevant.

**Comment by Tronic** [comment]
Not stale.

**Comment by dinosmm** [comment]
Not stale.

**Comment by greyson-signal** [comment]
Can ya'll submit new logs if this is still happening to you?

**Comment by dinosmm** [comment]
Just tested - now I am getting the following:

Caller (S6): error message is "recipient unavailable"
https://debuglogs.org/android/5.40.2/37f713e030eccc248429d672e7698105d9db2edbf363fa9a43b1e6f44103b991

Call receiver (S20): says "missed call" (never rang)
https://debuglogs.org/android/5.40.2/d89501aec466bd59a068a57a9d17673ea666e51868d2acc6eaecfdeb6adca21b

Call receiver (Signal Desktop on Win10): says "you declined an audio call" (rang for maybe 1/5th of a second)
https://debuglogs.org/desktop/5.45.0-beta.1/6b23c384b3cc69b981b6458a4ee78055f8ac27decb669c0eee5c00e76cdf715a.gz

Not sure if this is the same issue.
I will test from my wife's phone tomorrow, which is the one most frequently producing the originally posted problem.
If the above is not the same issue please do let me know and I will report it as a new issue.

**Comment by gediminasel** [comment]
Same issue with xiaomi phones and win10.
