### ISSUE TITLE
Flickering while scrolling a lot of unread messages in groupV2

### ISSUE THREAD

**Issue by BeTmAsTeR** [signalapp/Signal-Android#10114]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Strange flickering while scrolling a lot of unread message in a groupV2

### Steps to reproduce
- Enter a big group
- Wait for new messagges (i tested with ~100 unread messages)
- Manually scroll to the bottom

**Actual result:** A lot of flickering/stuttering while scrolling
**Expected result:** Smooth scrolling without flickering/stuttering

### Video
I recorded a sample video
https://streamable.com/xeddmf

### Device info
**Device:** Asus Zenfone 6
**Android version:** Android 10
**Signal version:** 4.74.2

### Link to debug log
I forgot to create a  debug log, i will try tomorrow when the chat will be full again

**Comment by DirkPitt1** [comment]
I encountered this with about 60 unread messages. It was just one flicker but when there's more unread messages (>100)
 flickers happen more often.
https://debuglogs.org/8715fd3578d9e9e96b68bf2eba78dcd795783d70f3876239cc40803d56e28f10

**Comment by sivaraam** [comment]
I observed this too. The flickering is annoying and disrupts continuous message reading. A recording could be found in the following link: https://drive.google.com/file/d/1e191fCZNYLMz8Jupwi6-PI0ARKLfTD8U/view?usp=sharing

**Comment by rainerzufall** [comment]
Do more debug logs help in this case? I experience this also regularly when many messages have accumulated in our large beta testing group.

From what I can see, it has something to do with the recalculation of the unread messages count. While scrolling it seems to count down in the background, but at certain points in time the app wants to display a new count of unread messages (together with the message divider line). Both is shortly shown and disappears again and thereby changing the placement of the message bubbles => generating the "flickering"

**Comment by BeTmAsTeR** [comment]
Another video with more than 350 messages, a LOT of flickering: https://streamable.com/omu70d
Debug log: https://debuglogs.org/83fdfffc84d9b1fa393d15ee24ca63ae7826a9f1b32f084fef0e0559bd879d33

**Comment by RandolphNimmer** [comment]
Also getting this, as are other people in my group chats, both Android and iPhone. The flickering is a result of the horizontal 'unread' line shifting down--when a person sends 2 consecutive message, normally their name only displays on the first message. When the horizontal rule is between the 2 messages, both display their name, changing the overall height of the messages. It causes the whole thing to shift unexpectedly. Pretty sure that's what is going on anyway.

**Comment by error401de** [comment]
Can reproduce on multiple devices. Are there any news on a fix? For people in groups this is a daily occurring issue.
