### ISSUE TITLE
[Question] Where is 4.73.4 source code?

### ISSUE THREAD

**Issue by isabsent** [signalapp/Signal-Android#10113]
There is 4.73.4 version on Google Play from 20.10.2020. Where can I find the source code of it? Current master version is 4.74.3.

**Comment by alan-signal** [comment]
We tag all releases.

Search for v4.73.4 in the tags:

![image](https://user-images.githubusercontent.com/48254818/96745645-bd7f6200-139c-11eb-975a-f19ab64856db.png)
