### ISSUE TITLE
Signal does not properly use the Pixel 5 proximity sensor

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#10126]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Pixel 5 is already known for having an under the display proximity sensor which is blinking when active. When listening to voice notes it's blinking as well as it is active. I don't know if google provides a way to disable the light of it and only use the IR part if possible.

### Steps to reproduce
- listen to voice notes on a pixel 5
- proximity sensor blinks and is activated

**Actual result:** 

Proximity sensor uses visible light for measuring distance

**Expected result:** 
Proximity sensor should be used in IR mode . Also the sensor should be deactivated properly so it can't be seen anymore

### Screenshots
There are several videos on the internet how it looks

### Device info

**Device:** Google Pixel 5
**Android version:** 11.0
**Signal version:** 4.75.0

### Link to debug log
https://debuglogs.org/f968d748ae18ac3918272af48f7a009f7e437124d8314abb501a6edb0fc4fd5d

**Comment by alex-signal** [comment]
Does the proximity light continue to flash after the voice note has terminated (several seconds after)? 
If you hit "stop" on the playback notification does it disappear?

**Comment by piratenpanda** [comment]
The light flashes once for me when playing the first voice note and then does not flash again but the sensor does not disappear again unless force closing Signal or rebooting the phone. When playing voice notes after force closing no light but the sensor is visible again and does not disappear.

**Comment by piratenpanda** [comment]
Sensor flashes when signal is not the currently used app. Stops as soon as I force close signal.

**Comment by piratenpanda** [comment]
I don't even know if this is something signal ca fix or google will themselves

**Comment by alex-signal** [comment]
It's a mixture. We should definitely be handling the lifecycle of our usage of the proximity sensor properly, and it sounds like we might not be. (evident by the behaviour when you force quit). As for the led itself it's possible this is in hardware. I see a lot of folk complaining about it in general.
