### ISSUE TITLE
Cannot create groups since V2 update UAE

### ISSUE THREAD

**Issue by 3WfMeCuUqzgXBh** [signalapp/Signal-Android#10122]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Groups seem to have been broken for users in UAE (possibly related to censorship circumvention?) since the update to groupsV2. If I create a new group from a UAE number the creation fails with error 'Try Again later'.

### Steps to reproduce
- From a signal account registered to UAE number attempt to create a group
- Add members to group and tap next

**Actual result:** 
Error 'Try again later' is received.

**Expected result:** 
The group should be created.

**Device:** Google Pixel 4a
**Android version:** 11.0
**Signal version:** 4.74.3

### Link to debug log
https://debuglogs.org/0e4b1a9dd031358c14d97bbf59131ddbe6fd7a007ea96fd31010e03b92ee2e54

**Comment by alan-signal** [comment]
How many times have you attempted this?

Is it possible you are double tapping the "Create" button. I've been able to reproduce like this.

**Comment by alan-signal** [comment]
Please try again now.

**Comment by 3WfMeCuUqzgXBh** [comment]
> Please try again now.

Seems to be working now on both Android and iOS. Thanks

**Comment by AckslD** [comment]
I'm having the same problem on android (Signal version 5.0.8). Is there any more information about this issue or a solution somewhere?

**Comment by mehdisadeghi** [comment]
> I'm having the same problem on android (Signal version 5.0.8). Is there any more information about this issue or a solution somewhere?

I'd guess there is a mass migration to signal happenning and their infra is under pressure. I have the issue too and simply will wait.
