### ISSUE TITLE
Crash on opening V2 group chat

### ISSUE THREAD

**Issue by sellth** [signalapp/Signal-Android#10123]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening a certain V2 group chat my app crashes reliably. The same chat worked fine before, maybe related to open join requests?

### Steps to reproduce
Kinda hard to reproduce with what I have, but this is roughly what happened:
- have a V2 group chat
- be an admin
- use the "join via link with admin permission" feature
- close the app while join requests are coming in
- try to open the group chat with open join requests

**Actual result:** the app crashes
**Expected result:** the app doesn't crash

### Device info
**Device:** Google Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.74.3

### Link to debug log
https://debuglogs.org/f3f29bfb58786d46a242da3abe6db034ebcde3f1c4e6a4c41019ab51b6ae64c3

Update: Another group admin using Android on a Galaxy S8 has the same problem (still waiting on feedback from the iOS people). So our group chat seems to be in a state that a state that crashes all admins apps on opening.

**Comment by sellth** [comment]
We could resolve the situation because one of our admins is using the iOS app, which didn't show this behaviour. After the pending join requests were dealt with the reported crash bug was gone.

**Comment by cody-signal** [comment]
Should be fixed in 4.75.1
