### ISSUE TITLE
Backups silently disabled

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#10129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backups got disabled silently. Last backup is from 2020-10-19 which would mean this likely happened on the update to 4.74.2. I also noticed that there are too many backups around, but that might very well have been fixed by 3163e09b9811b8ac589407d4ba94d0a803303980.

### Device info

**Device:** Motorola One Vision
**Android version:** 10
**Signal version:** 4.75.1

**Comment by alex-signal** [comment]
Hi, if you re-enable backups, you should see that the old ones are cleaned up automatically. We have added some better handling for backups being disabled. Please verify that you have backup notifications enabled, and try enabling backups again.

**Comment by eike-fokken** [comment]
Hi,
had the same issue and I think the issue is not so much that old backups stay around but that backups got silently disabled.
I stumbled upon it by a stroke of luck but many users out there might stumble upon it when they want to use a backup to reinstate their messages, which might be many months from now.

As bad as it is, I would suggest to write a welcome message on the next update that states clearly, whether backups are enabled and how old the last backup is (if this information is stored even if backups are disabled, I don't know), so that users can be warned of the silent stop to backups.

**Comment by greyson-signal** [comment]
We'll be posting a notification in the next release if we detect that you have backup files, but your backups are currently disabled. Not perfect, but at least users will be notified.

**Comment by bungabunga** [comment]
i had the same two issues. i only found about that when my space on the phone was filled up with old backups. it seems it works ok now, after i enabled backups again and the latest changes. 

android 11
latest Signal beta

**Comment by affinityv** [comment]
Not happy, backups were silently disabled for me too.  I have v4.75.7 now, v5.75.8 isn't showing up yet for me on play store on two mobiles.

I only noticed the problem when my phone backup didn't include new Signal backups (I backup using an rsync tool).

**Comment by greyson-signal** [comment]
@affinityv 4.75.7 should have notified you if your backups were disabled. To be clear, the fact that they were disabled without any notification was a bug, not intentional. Appears to happen to some Android Q users.

Did you see a 'backup failed' notification when you launched 4.75.7?

**Comment by affinityv** [comment]
@greyson-signal Okay, but I didn't get 4.75.7 until after I had found this situation; it just wasn't yet offered as an update for me.
Never saw any 'backup failed' messages at any time.
