### ISSUE TITLE
[Bug] Video Calls show last video call and has frozen Picture

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-Android#10127]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- Start a call with the same person
- Wait 5 mins or no time to start video call: doesn't really matter to much.
- Shows frozen picture of last video call on what they were showing. The Android Phone is doing the video call itself.
- Don't have to be on the same call for this to happen, you can see the last video call or current video call inside that call itself that hasn't ended before starting this new video call that is now current.
- The picture is frozen on the call you made to the same person. (Android side: not on my ios device - everything is normal) 

Extra:
This has been broken for 2 weeks at least.

### Steps to reproduce
- Start a call with the same person
- wait 5 mins or no time to start video call: doesn't really matter to much.
- Picture is frozen of the last video call or last call of that video call. (Android side) 

**Actual result:** Frozen Picture sometimes, not every time. Mostly happens at a lot!
**Expected result:** No Frozen Picture of the video call.

### Screenshots

![signal](https://user-images.githubusercontent.com/49108816/97091140-75f01480-15ee-11eb-901e-3849b17a6954.jpeg)

### Device info

**Device:** Samsung SM-G930F
**Android version:** Latest Android Version
**Signal version:** Updated Last Night: 4.74.3

### Link to debug log

https://debuglogs.org/f99c75e92433f979c06562fe7148a4ba1cbaac54431e70356fe6b10356923b3a

**Comment by cody-signal** [comment]
Thanks for the report @MrWaste. I'm having trouble reproducing, could you confirm I'm following your steps correctly? Also you mention iOS, is the callee an iOS device or does this happen when both are Android as well?

# Start and connect a video call with a contact
# Hang up
# Start and connect a voice call with the contact
# Enable video
# See frozen video of contact from previous video call on your device

**Comment by MrWaste** [comment]
@cody-signal This is ONLY happening from the Android side. IOS isn't having any of the problems.

**Comment by MrWaste** [comment]
@cody-signal

1. You can only see this on the Android Phone side
2, The Android phone has a black screen, frozen. Sometimes frozen picture of some sort from last video call. (I'm talking about the Same Person ONLY)

 
![signal](https://user-images.githubusercontent.com/49108816/98163940-5da6b200-1e98-11eb-8ce0-85f954bfc6ec.jpeg)

**Comment by MrWaste** [comment]
With the Picture above.
Yes its a blank screen, not the background of the person's video call. This is what signal gave on the Android Phone Screen.

Still Broken.

**Comment by MrWaste** [comment]
Still a problem time to time but not as much.

**Comment by cody-signal** [comment]
I've tried to reproduce this, and have made tons of calls since you originally reported it, but am unable to do so.
