### ISSUE TITLE
Getting "bad encrypted" messages

### ISSUE THREAD

**Issue by bitwave** [signalapp/Signal-Android#10139]
- [x] I have searched open and closed issues for duplicates, but they are old
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Getting "bad encrypted messages" from a single person, I share some groups together.

### Steps to reproduce
- be in a group or more
- random person sends bad encrypted messages
- can send messages, but can't receive any

**Actual result:** signal is a send only messenger, one chat have 100+ messages
**Expected result:** everything works as expected

### Device info

**Device:** Moto G pro
**Android version:** 10
**Signal version:** 4.74.3

### Link to debug log
https://debuglogs.org/857348f6531a766a38cdb0b0ed79390de0367e1def8f82b4c5e170e4036df1ba

**Comment by bitwave** [comment]
https://debuglogs.org/45274c9a95c1db9bfb86c4da39f81bc99541a1e04c69265fbe96b6a1bed3ebc3

other corresponding person

**Comment by bitwave** [comment]
The person deregistered its account and the messages keep coming...

**Comment by bitwave** [comment]
The person mentioned (person A) ealier called a third person (person B), via desktop signal. the mobile version was offline at this moment. after this call i got bombared with "bad encrypted" messages (timestamps delta ~100ms). I hadn't direct contact to person A or B. Then I and person A reset the encryption. no help. then person A completely disabled its account. nothing changes.
The only thing now is, the messages are coming slower (probably due to rate limiting)

**Comment by kettenfett** [comment]
I have the same problem with someone I know. 

Her *device keeps sending _"bad encrypted message"_ to multiple other people randomly*. User says, he isn't using any desktop app, just his iPhone. He says, he knows more people who have this problem, also on android.

This is **very* frustrating for people, because they get answers from the receivers, who are understandibly confused by a multitude of messages just saying "bad encrypted message". This keeps happening is turning people away from signal.

![grafik](https://user-images.githubusercontent.com/23098362/98095917-7066ba00-1e8b-11eb-9046-1a5774b17eea.png)

**Comment by wil3** [comment]
My self and others I am in a group chat with are experiencing this too as of a week ago. What is the cause for this behavior? Everyone is using the mobile app, one Iphone user, the rest Android.

**Comment by wil3** [comment]
FWIW I just noticed that in the settings the group said it was a legacy group. I created a new group and as of now the problem is not occurring. Maybe this will help someone else, if it happens again back I'll provide an update.

**Comment by JanZerebecki** [comment]
Not sure if this is the same issue, but with v5.0.5 my messages to a group create this problem for one user with 4.73.4, but for another user with 4.75.8 they work. I guess this is related to the lagacy to new group migration. Sadly this makes Signal unusable.

**Comment by JanZerebecki** [comment]
After the recipient that couldn't decrypt upgraded to 5.x this problem didn't go away.

**Comment by JanZerebecki** [comment]
Reregistration (reinstallation) did make it work.

**Comment by ponder2000** [comment]
I recived bad encrypted from **Note to self** !!
I don't know what's happening nd why??

![Screenshot_2021-01-12-19-19-01-40_4b14b257287ac0a6d1fd5fbb2487716f.jpg](https://user-images.githubusercontent.com/59143746/104322741-4ecd2300-550b-11eb-804f-eb98aba339f2.jpg)

**Comment by grandchild** [comment]
@ponder2000 please file a new issue and provide a debug log. Don't hijack other people's issues.

one idea where this might happen: did you register two different phone numbers in the same app install?

**Comment by ponder2000** [comment]
@grandchild I was just suggesting that I am also having trouble with that!

And nope just one number but having multiple linked devices. Running on android, ipad and macOs too.

**Comment by subrayamallya** [comment]
![signal-2021-01-12-171838](https://user-images.githubusercontent.com/917979/104624671-b0df7280-5648-11eb-9df3-c771d066770d.jpeg)
Multiple users in our group also keep getting this message. Only happening on Android. Any suggestion to resolve this?

**Comment by subrayamallya** [comment]
not sure if it helps people here but I found a AMA that was done recently by Signal team and this was there in that thread
https://www.reddit.com/r/signal/comments/as1hp2/bad_encrypted_message/

**Comment by bitwave** [comment]
I haven't encountered this problem anymore. If someone has the same problem again, after a comment I can reopen this...
