### ISSUE TITLE
BackupUtil.hasBackup:219 NullPointerException

### ISSUE THREAD

**Issue by keeferrourke** [signalapp/Signal-Android#10148]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the latest Signal Beta (package version 7292, updated today from the Play Store), Signal repeatedly encounters a null pointer exception and crashes. This crash occurs in the background, and also immediately upon app launch.

### Steps to reproduce
- Open Signal
- Observe crash

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Immediate app crash due to NPE.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The app should not crash.

 

### Device info

**Device:** OnePlus 7 Pro 5G (GM1925)
**Android version:** 10
**Signal version:** 4.7.5 (7292)

### Link to debug log

It is not possible to capture a debug log with Signal's advanced settings because the app fails to launch. However the Android system reporter details the following.

java.lang.NullPointerException on line 219 of BackupUtil, in the hasBackupFiles method.

**Comment by keeferrourke** [comment]
Some additional information: I was able to stop the constant crashes by removing the backup directory from my device.

**Comment by keeferrourke** [comment]
Some additional information: I was able to stop the constant crashes by removing the backup directory from my device.

Here is the requested debug log as a result.

https://debuglogs.org/1b08f48d6a70c53f516e0b3bf62ee4029629c4fd40002ff51d19e6839909a38a

**Comment by greyson-signal** [comment]
Thank you! Fixed in 4.75.6.
