### ISSUE TITLE
Bug: Back button, emoticons and adding images not working

### ISSUE THREAD

**Issue by klues** [signalapp/Signal-Android#10147]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my wife's Galaxy A41 suddenly these basic things aren't working anymore (I think there was no update):
1. After opening a conversation, pressing the system "back" button (bottom of the screen) doesn't do anything. However using the back button on the upper left corner works and navigates back to conversation overview.
2. Pressing the blue "+" icon on the bottom right in writing a new message doesn't do anything (not possible to attach images or files).
3. Tapping the emoticon icon on writing a new message doesn't do anything, no emoticons are opened to choose from.

### Device info

**Device:** Samsung Galaxy A41
**Android version:** 10
**Signal version:** 4.74.3 (7242)

### Link to debug log
https://debuglogs.org/f5bad71928549e1c97dc2f214637d7b48aaa0d7472603a7a925803990e2b9dd2

**Comment by Sgn-32** [comment]
The new version 4.75.4 is available. This has a fix for the back button on OnePlus phones, maybe this solves also with the Samsung Galaxy A41.

**Comment by klues** [comment]
Thanks, updating fixed it 👍 
Should have checked for an update before, sorry.
