### ISSUE TITLE
signal send first message to new contact

### ISSUE THREAD

**Issue by DougBrownVancouver** [signalapp/Signal-Android#10144]
----------------------------------------

### Bug description
-When trying to send a message to a signal user for the first time (never messaged with that user before). 

-You are booted back to the main screen after accepting the "Let [Signal Number] message you and share your name and photo with them? They won't know you've seen their message until you accept." (instead you should be taken to the conversation screen so that you can start writing your message to that user........ ). 

-Now you have to click the Pen Icon again, type the signal number in again and click new message to again in order to message them.

### Steps to reproduce
**Only happens the first time you are messaging with a signal user
- 1. press pen icon from main screen
- 2. type in the signal number
- 3. press new message to
- 4. click "Accept" when the "Let [Signal Number] message you and share your name and photo with them? They won't know you've seen their message until you accept." message appears.
- after you click accept you are booted back out to the main screen instead of staying in the conversation screen where you could start typing your message...... because of the bug you are forced to repeat steps 1-3 before you can start typing your message.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
-You are booted back to the main signal screen

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
-You should be taken to the conversation screen so that you can write the message you wanted to send.

### Screenshots
![Signal Photo Showing Accept Screen for Debug](https://user-images.githubusercontent.com/73547467/97332194-67486e00-1837-11eb-96a9-5000d7715d15.jpeg)

### Device info

**Device:** Samsung Galaxy Tab A SM-T387W
**Android version:** 9 One UI Version 1.1
**Signal version:** 4.74.3

### Link to debug log

https://debuglogs.org/cecd73e6cffeead4229123f3380e2631135bb06f943a8270aed716ffd517f815

**Comment by greyson-signal** [comment]
Hi there, this is fixed in 4.75.1, which is currently rolling out :+1: Thanks!

**Comment by DougBrownVancouver** [comment]
Amazing, thank you!
Do you know where I can get the APK for  4.75.1

When I go to https://signal.org/android/apk/ the latest is 4.74.3

Thanks for all you do.
Sincerely,
Doug.

Doug Brown, MD, FRCPC
Emergency Physician, Royal Columbian Hospital
Clinical Assistant Professor, UBC Department of Emergency Medicine
www.drdougbrown.ca

**Comment by greyson-signal** [comment]
We update the website APK after we've fully rolled out to the Play Store. That'll likely happen tomorrow :+1:

**Comment by DougBrownVancouver** [comment]
Thanks, I just tried it using a beta 4.75.1 and experienced the same
problem......here is the debug log (
https://debuglogs.org/2ab2e6dd5be6dccfda2cbdca2dc92e3f1e27bbe0b275ceece93501b1e009747d
)

Version: 4.75.1 (7261)
armeabi-v7a
Package: org.thoughtcrime.securesms

from
 https://www.apkmirror.com/apk/signal-foundation/signal-private-messenger/signal-private-messenger-4-75-1-release/signal-private-messenger-4-75-1-2-android-apk-download/
<https://www.apkmirror.com/apk/signal-foundation/signal-private-messenger/signal-private-messenger-4-75-1-release/signal-private-messenger-4-75-1-2-android-apk-download/>


Doug Brown, MD, FRCPC
Emergency Physician, Royal Columbian Hospital
Clinical Assistant Professor, UBC Department of Emergency Medicine
www.drdougbrown.ca
