### ISSUE TITLE
Voice Messages UI Button issues - Switches from play to pause multiple times.

### ISSUE THREAD

**Issue by XxBlackHatxX** [signalapp/Signal-Android#10146]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Play pause button freak out when in the newest version of signal for android

### Steps to reproduce
Receive an audio message from an iPhone user and try to play the message
We had disappearing message activated. 

Note that the person has already tried clearing cache restarting the app and phone. And update both the OS and Signal. We will try to turn off disappearing messages as see if that fixed anything.

**Actual result:** 
When you clicked the play pause button it would switch between play and possible multiple times a second. The message would play normally.

**Expected result:** When i play a message it shows the pause button and when i pause a message it should show the play button.

### Screenshots

*I have a screen recording please tell me how i can upload that*

### Device info

**Device:** Samsung
**Android version:** 10
**Signal version:** ?? Newest as of Oct 28th 2020

### Link to debug log

I'll add this when it happens again.

**Comment by XxBlackHatxX** [comment]
To be clear I'm submitting this report for the friend that i chat with they are on android. It seems the issue only happens when the disappearing messages is enabled AND you send multiple messages back to back. When we turn it off it doesn't happen. Then we turn it back on it happens again.

**Comment by cody-signal** [comment]
@XxBlackHatxX Thanks for the report, I'm having difficulty reproducing this. Can you confirm my steps?

# Open a conversation
# Ensure disappearing messages are enabled
# Send a voice memo from a iOS device to an Android device
# Play the memo on the Android device
# Observe the issues of the play/pause button toggling back and forth

Also do you know if there were any bluetooth or headset devices attached to the phone? I've noticed in other apps that they can cause weird playback things to happen.

**Comment by XxBlackHatxX** [comment]
The person is not using any Bluetooth headsets when playing the messages. It happen when you send multiple voice messages back to back. My messages are usually about 8-10 minutes long each.
