### ISSUE TITLE
Image received from another signal user can't be forwarded to a non-signal user.

### ISSUE THREAD

**Issue by jbehrends** [signalapp/Signal-Android#10145]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Any time I receive an image from another signal user (happens with multiple signal users) I receive an error (Send Failed) when trying to forward the image to a non-signal user.  This does NOT happen when natively attaching/sending an image from my phone to a non-signal user.  This has been happening for quite a while (at least last 6 months or longer) and happens on two devices in my household: Pixel 3XL and Pixel 2.  Both devices are on the carrier Varizon Wireless.

### Steps to reproduce
1. Another signal user send me an image
2. Select message/image, select three button menu, and select "Forward"
3. Select a non-signal user from contacts and attempt to send.
4. Immediately get a "Send Failed" message.

**Actual result:** 
Immediately get a "Send Failed" message upon forwarding the image to a non-signal user.

**Expected result:** 
The image should be successfully be sent/forwarded. 

### Device info
**Device:** Pixel 3 XL
**Android version:** 11 (6782484, RP1A.201005.004)
**Signal version:** Signal 4.75.2 (7272)

### Link to debug log
https://debuglogs.org/d3b3e68d23614c54fbd6b12ee0b2607c7632dbc780ad6e9fafe3b35223b9165f

**Comment by boggle247** [comment]
Same issue on the pixel 1.

Im running lineageos 17.1 (android 10) without Google services. Using signal apk 5.4.7 from signal website. Been happening to me for a few months as well.
