### ISSUE TITLE
messages disorder in a group V1 chat

### ISSUE THREAD

**Issue by Schweineschwarte** [signalapp/Signal-Android#10156]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a group V1 chat, old and read messages from yesterday will show always as new. New unread messages will show before this old read messages of the past.
It is not a duplicate of [#10155](https://github.com/signalapp/Signal-Android/issues/10155), because we have no different timezones.

### Steps to reproduce
- every time I open this chat, I see 7 new messages, but it are the old read messages from yesterday (saturday). Realy new unread messages (from sunday) are shown before this old messages.
- this is my last group V1 chat. I can't say if it is simply reproduceable for other chats.

**Actual result:** Every time I open this chat, I see 7 new messages, but it are the old read messages from yesterday (saturday). Realy new unread messages (from sunday) are shown before this old messages.
**Expected result:** Old read messages of the past are not new. New unread messages should be show as new.

### Screenshots
![signal-2020-11-01-121542](https://user-images.githubusercontent.com/12170903/97801598-49677880-1c3e-11eb-90ee-a10460087fa0.jpeg)

### Device info
**Device: Samsung Galaxy S7
**Android version:  8.0.0
**Signal version: 4.75.4

### Link to debug log
https://debuglogs.org/43ad8854eb71f093172ae18d768f1a4f96928a7691085b9785f5f19d807a715a

**Comment by greyson-signal** [comment]
Messages in Signal are always rendered in the order they are received, but the timestamp shown is the time they are sent. If you long-press a message and click the info button on the top bar you'll see the received time. Can you confirm that your messages are rendered in the order they are received?

There's several reasons some messages may be received before others. Notably, a sender could have a poor network connection and take a long time to send messages, causing message they started to send a while ago not *really* send until the next day or something. It's hard to say without seeing more details about message send/receive times and asking the senders directly.

**Comment by Schweineschwarte** [comment]
The "7 unread messages" was shown _every time_ the time, if I opened this chat (same, if I had no new messages, too!). If I received a new message, the realy new message was put before this "7 unread messages". I have "solved" this problem, through I deleteted all this 7 messages. Now it works, but I can't tell you more about this "7 unread messages".
