### ISSUE TITLE
New groups not possible without admin, can't remove myself from admin

### ISSUE THREAD

**Issue by JanZerebecki** [signalapp/Signal-Android#10157]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When creating a new version group I can't remove myself as admin, so they are not possible without any admin. This removes the possibility for me to show that a group will not play authoritarian games. This was the default for old groups. There is no option to create old groups and AFAIK the intent is to remove old groups, thus classifying this as a bug instead of a feature request.

### Steps to reproduce
- create new group
- look at options for other person in the group, see that there is an option to make them admin, don't use it
- try to remove yourself as admin

**Actual result:** Option to remove yourself as admin is shown and works
**Expected result:** Option to remove yourself as admin is not shown

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 4.75.4

**Comment by greyson-signal** [comment]
Needing to have at least one admin is a technical requirement that prevents a whole slew of tricky edge cases around group management behavior. It's also pretty common in messaging apps. If you'd like to have the equivalent of an old group, the closest approximation would just be to make everyone an admin, or simply just don't limit what non-admins can do. Hope that helps!
