### ISSUE TITLE
Link preview for YouTube music showing "your browser is deprecated" 

### ISSUE THREAD

**Issue by Genis-Sage** [signalapp/Signal-Android#10158]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Just copying over the bug from ios issue tracker

A 'link share preview' for a YouTube Music link is showing a "Your browser is deprecated" message in the link preview.

Link shared: https://music.youtube.com/watch?v=jg51kFe7CWU

### Steps to reproduce
- copy and paste the link into a Signal conversation

**Actual result:**
Error message about deprecated browser. 

**Expected result:**
Working link preview. 

### Screenshots
See iOS issue:
https://github.com/signalapp/Signal-iOS/issues/4609

### Device info
**Device:** Nokia 7 plus 
**Android version:** 10
**Signal version:** 4.75.4

Nice to know:
WhatsApp can create the link preview properly

**Comment by Genis-Sage** [comment]
Now it works.
not sure what changed

**Comment by rifftual** [comment]
Does not, for me.
