### ISSUE TITLE
Disturbing embedded sound in voice recordings can not be turned off

### ISSUE THREAD

**Issue by teknokatze** [signalapp/Signal-Android#10150]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Since version 4.74.3 on two different vendors of Android there is a sound either at the beginning or (/ and) at the end of voice recordings.
There is no way to turn this sound off other than muting all notification sounds system wide.

### Steps to reproduce
- receive a voice message
- play it

alternatively:
- record voice message
- implicitly send it
- receiver will step through the points above

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Corrected behavior: It is possible to customize the behavior of the sound, in our case the preference would be to
completely turn it off.

### Device info

**Device:** Redmi Note 8T
**Android version:** 9 PKQ1.190616.001
**Signal version:** 4.47.3

**Comment by greyson-signal** [comment]
We'll be disabling the tones when playing back a single voice note. Change should be in 4.76.x.

**Comment by thedustyrover** [comment]
I'm on version 6.39.1 on Android, did this behavior get reintroduced? I'm hearing the beeps on all voice messages now and can't find a way to disable.
