### ISSUE TITLE
Timezone difference results group chat messages disorder

### ISSUE THREAD

**Issue by honur** [signalapp/Signal-Android#10155]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am in a group chat with a friends, one of which is in different time zone. His sent messages are displayed in his timezone. For example, he sent last message a minute ago, but the chat says an hour ago.
But this was not disturbing me, until I got my internet off for a couple of hours, when it came back, I first received the messages sent from a friend with another timezone, then the messages sent my other friends (in the same timezone as me). So, the conversation is disordered.
### Steps to reproduce
- start a group chat with at least 3 participants, one of them is in different timezone
- go to flight mode
- tell your friends to have conversation in the group chat
- turn back the internet

**Actual result:** You will see the conversation is disordered. The messages sent by a friend with different timezone will show earlier (or later) than the others. 
**Expected result:** The conersation should be in the same order as they happen.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by costaht** [comment]
Something different here. My messages are getting in order, but the timestamp are all messed up.

![Point Blur_Feb212021_193520](https://user-images.githubusercontent.com/50637431/108644216-1f032a80-747c-11eb-8f54-e62bd1547d2a.jpg)
