### ISSUE TITLE
MMS locked after upgrade (...no longer a member)

### ISSUE THREAD

**Issue by DavidWiesner** [signalapp/Signal-Android#10162]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I had a MMS group before I have updated the Signal app around July or september in the beta channel. After this upgrade I can not send any message to the group. Instead of the text input field an message is displayed:

"You can't send messages to this group because you're no longer a member." (See first screenshot)

When I open the group settings and go back to the group chat without changing anything the text input wil be displayed but nothing happens when clicking the text input (no blinking cursor, no keyboard woll open)

### Steps to reproduce
This seems to be a regression bug, so I'm not able to provide reproducing method, without downgrading the app. 
Here are the expected steps to reproduce
- Install older version of signal (maybe from june 2020)
- create a MMS group and write some messages within
- upgrade to newest version of the app
- go into the MMS group and try to write a message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
There is no way to write a message to the old MMS group. Only a message is displayed "You can't send messages to this group because you're no longer a member."

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
To my knowledge there is no way another person can me remove from the MMS group. So it should be possible to write a message to the group.  

### Screenshots

![Screenshot_01](https://user-images.githubusercontent.com/243115/97991216-68ead680-1de1-11eb-9e0d-71029caf8a34.png)
![Screenshot_02](https://user-images.githubusercontent.com/243115/97991242-74d69880-1de1-11eb-9742-a9bbd53c0d7e.png)
![Screenshot_03](https://user-images.githubusercontent.com/243115/97991249-7acc7980-1de1-11eb-8c40-7290cb775f90.png)

### Device info

**Device:** Google Pixel 4
**Android version:** 11.0
**Signal version:** 4.75.8

**Comment by greyson-signal** [comment]
Hi there, have a fix planned for the next beta :+1:
