### ISSUE TITLE
Block all messages from non-contacts

### ISSUE THREAD

**Issue by ehidle** [signalapp/Signal-Android#10161]
Seriously, why can Signal still not do this?

**Comment by greyson-signal** [comment]
Whenever you get a message for the first time from a non-contact, we show a 'Message Request' interface that lets you block them. 

Is some setting to automatically block messages from non-contacts a common feature of other messaging apps? I'm not familiar with any other app doing this. Seems like it's not exactly what most people would want, and could cause some frustrating situations.

**Comment by ehidle** [comment]
I have never once been prompted as you describe.

**Comment by greyson-signal** [comment]
The next time you get a message that starts a new conversation from a non-contact, if you don't see Approve/Block/Deny buttons at the bottom of the UI, please post a debuglog (Settings > Advanced > Submit debug log, post link here). Thanks!

**Comment by Genis-Sage** [comment]
Hey @ehidle 
Also, are you talking about Signal messages or SMS / MMS? 

I guess the message request is only available for Signal messages, but I am not sure:
https://signal.org/blog/message-requests/

And please don't delete the issue template, but fill it out.

Just for completeness:
1) The issue template also states, that github is reserved for bugs, and feature requests belong in the forum
https://community.signalusers.org

2) starting with the word "seriously" is not nice
(that's my opinion, but I am no Signal dev, just a normal Signal user)

**Comment by ehidle** [comment]
Hi @Genis-Sage, I am not aware that I deleted anything? I just posted my message as normal. It is also a lot less nice to be dishonest about my feelings when expressing my exasperation with the frustrating omission of what is in my opinion an obviously necessary feature. Would you rather I lied? Just an honest question (seriously).

Thanks

**Comment by Genis-Sage** [comment]
To stay on topic
are talking about Signal messages or SMS / MMS 

Also, if you look at other issues, you will see how the issue template looks like
(I guess, some github apps will delete templates, but if you create an issue via a web browser, the template will be automatically inserted)

**Comment by ehidle** [comment]
I created the issue on desktop using a web browser and there was no template. Sorry.

Just to be clear, I am talking about any incoming message. I don't care what the sender is using, or if it is end-to-end encrypted. If a message comes from someone who is not in my contact list, I want it blocked. But, as you alluded to, I suppose this is more of a feature request and probably should go somewhere else. I will close this.

**Comment by TGBCoding** [comment]
> I suppose this is more of a feature request and probably should go somewhere else. I will close this.

Was a feature request created for this or did anyone look into this any further?

**Comment by ehidle** [comment]
> Was a feature request created for this or did anyone look into this any further?

I'm not sure I ever made one. I haven't used Signal in a long time so the issue is moot for me now. Good luck.

**Comment by TGBCoding** [comment]
> > Was a feature request created for this or did anyone look into this any further?
> 
> I'm not sure I ever made one. I haven't used Signal in a long time so the issue is moot for me now. Good luck.

Damn, it's something I'm trying to implement (or change) now but struggling with it.
