### ISSUE TITLE
Push messages delayed (failed to connect to textsecure-service.whispersystems.org)

### ISSUE THREAD

**Issue by swgrrt** [signalapp/Signal-Android#10168]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Push messages come in delayed (up to 30min)
I am using microg push services, other messaging apps like whatsapp or threema work fine.

### Steps to reproduce
- someone sends me a message on signal
- I observe that the message notification is delayed

**Actual result:** Push messages are delayed. When opening the app I instantly receive the messages. Otherwise they come in late (up to 30min)
**Expected result:** Instant push messages like on other apps

### Link to debug log
[Debug](https://debuglogs.org/81a7230f0d06e7f69686997a91d2f065038522eddf9177c5da1765bb7eaa0c83) 

The message was sent on 11-05 at 08:24. I received the messag ca. 08:27 on my device (pretty fast this time, but same errors on debug log).
 
In the debug log I noticed this line:
`11-05 08:26:36.995  6864  3858 W RestStrategy: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: failed to connect to textsecure-service.whispersystems.org/76.223.92.165 (port 443) from /192.168.178.50 (port 45928) after 10000ms`

So it seems that it can't connect to the server in order to fetch the message.

Do you have an idea how to solve this?

**Comment by cschmidat** [comment]
I have the same issue -- I'm on build 7282 at the moment. Here's my debug log:
[Log](https://debuglogs.org/f6819cd04daac217b3b8c05689eed3e086ef2b824e686e77130a0808aa77e78b)

**Comment by MJC579** [comment]
Hi. Could you please tell me how to stop these emails? I took interest in
the GitHub website but I have no idea how to read the UI or how to navigate
it or what any of it means. It's the most frustrating and confusing shit
ever and for some reason I'm getting notifications and emails and I hate
it. I've come to this page to try to get them to stop multiple times and
there is no clear way to do it.

**Comment by cschmidat** [comment]
> Hi. Could you please tell me how to stop these emails? I took interest in the GitHub website but I have no idea how to read the UI or how to navigate it or what any of it means. It's the most frustrating and confusing shit ever and for some reason I'm getting notifications and emails and I hate it. I've come to this page to try to get them to stop multiple times and there is no clear way to do it.

Lol. Go to [github.com/watching](https://github.com/watching) and unwatch the repo :)

**Comment by Ornanovitch** [comment]
Same issue here !
