### ISSUE TITLE
Expired after update

### ISSUE THREAD

**Issue by camdit** [signalapp/Signal-Android#10163]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I upgraded to 4.75.8 because my previous version was out of date, however, it still says that it is out of date and needs to be updated.

### Steps to reproduce
- build 4.75.8 from source

**Actual result:** Will not continue, claims that the version is out of date
**Expected result:** Should see that the version is current

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 11.0
**Signal version:** 4.75.8

### Link to debug log
https://debuglogs.org/5e0dd12b9c4dd4bb15adbe582cf3a2fddf127a81958133e84ca04dc1f1f301b3

**Comment by Genis-Sage** [comment]
hey @camdit 
I am no Signal developer,
but the last time someone had this issue with a self built version,
he was asked to go to the community forum: https://community.signalusers.org/

As signal devs can fully support only official production releases: #7121

**Comment by camdit** [comment]
@Genis-Sage 
I see other's that have posted on 4.75.8, but that is neighter here nor there. A search on the community has given me direction. Thank you. I will report back if it ends up being fruitful.

**Comment by camdit** [comment]
I found the issue, it was in the Manifest, the line:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                     android:maxSdkVersion="28" />`

This was keeping Android 11 from writing the buildconfig. removing maxSdkVersion fixed the issue.
