### ISSUE TITLE
Unable to open gallery on Android 10 for profile picture 

### ISSUE THREAD

**Issue by shahsurajk** [signalapp/Signal-Android#10169]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to open gallery for selecting a profile picture on android 10. This happens only when you're a new user. The problem is that Signal doesn't ask for media permissions while on the profile picture screen

### Steps to reproduce
- Be a new user, or have the storage permission reset or clear data and come back (make sure you don't have the storage permission)
- Open the profile picture screen and try adding one

**Actual result:** didn't ask for any permissions, opened a blank screen
**Expected result:** Should ask for permission and then should show me the contents of my gallery

### Screenshots

![image](https://user-images.githubusercontent.com/12149313/98248985-b612a800-1f9b-11eb-967c-9723eeff4cbe.png)

### Device info

**Device:** Nokia 7.1
**Android version:** 10.0
**Signal version:** 4.75.4

### Link to debug log

NA

**Note**: I'm new to this project, if this get triaged, i could pick this up. I'm also a contributor to Fenix (Firefox mobile).

**Comment by Genis-Sage** [comment]
hey @shahsurajk 

thanks for the report, and your offer to help out

1) your issue is a duplicate of #10104

2) everyone is invited to create pull request according to the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#pull-requests)

(just to note, I am just a Signal user, not Singal dev)

**Comment by shahsurajk** [comment]
Oh I did try searching, but couldn't find this issue. Maybe I used the wrong keywords. Closing cause it's a duplicate of #10104
