### ISSUE TITLE
Clicking on notification does NOT open conversation (but the App home page)

### ISSUE THREAD

**Issue by Nojevah** [signalapp/Signal-Android#10175]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I click on a notification (in statusbar, or in popup, or in lock screen), instead of opening the conversation it opens Signal home page (with all conversations). I have this only on my Samsung Galaxy S8 (another contact of mine has the same behavior with S8+).
I have this behavior since the beginning I've used Signal (1 year I'd say).

### Steps to reproduce
- receive a message
- go to your notification bar
- click on the Signal notification

**Actual result:**
Signal main page is opened.

**Expected result:**
I should be on the conversation page of my contact.

### Screenshots

Here is a video of the problem:
https://drive.google.com/file/d/1dafoOnOK3JNDS_XBo8TfsIWIValM11vY/view?usp=sharing

And a screenshot of debug log where the problem is (I guess the problem is the yellow line):

![Screenshot_07 11 20-11 27 30_Signal](https://user-images.githubusercontent.com/7541249/98439085-76f56b80-20ef-11eb-859f-517168cfc950.png)

### Device info

**Device:** Samsung Galaxy S8 (SM-G950F)
**Android version:** 9
**Signal version:** 4.75.4

### Link to debug log

https://debuglogs.org/88ea881bbeff71bbe368a5e2ff6187e1f806c1205f2c366707811e497e3ccb57
I clicked on notification at 11:53

**Comment by Nojevah** [comment]
It seems it has been fixed recently. Someone to confirm there was a fix/commit for this (and close this ticket) ?

**Comment by greyson-signal** [comment]
There's certainly been some churn in that area, could have been fixed incidentally. Free free to re-open if it crops back up. Thanks!
