### ISSUE TITLE
Need help, who has good knowledge on this code

### ISSUE THREAD

**Issue by 160040-370** [signalapp/Signal-Android#10177]
Hello all, 
I need help regarding this code. If any one is free for one or two hours. Can you please contact me via mail
crusaderkarthik@gmail.com

Thank you so much in advance. Looking forward for any one of your mail

**Comment by Cerberus0** [comment]
Hi @160040-370,

Welcome to the Signal Android issue tracker! Please note that this issue tracker is only meant for bug reports. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!
