### ISSUE TITLE
Huge amount of time to upload big file

### ISSUE THREAD

**Issue by n0sign4l-official** [signalapp/Signal-Android#10176]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to send a file of 80MB to a recipient and it's like 3 hours i'm trying to upload it. Looking at the logs I read a enormous amount of: `EventBus: No subscribers registered for event class ...`

### Steps to reproduce
- send a big file

**Actual result:** File takes hours to upload
**Expected result:** File should be uploaded in a reasonable time compared to the internet connection speed

### Device info

**Device:** Pixel 3a
**Android version:** 10
**Signal version:** Signal 4.75.8

### Link to debug log

I'll send it privately to signal developers when asked. Lemme know if you prefer through mail or community DM :+1:

**Comment by hiqua** [comment]
It's the same with any kind of file? I just tried with the file `out` from `dd if=/dev/urandom of=out_random bs=1M count=80` (so random bits) and I don't have this problem, on the same version.

How stable / fast is your Internet connection?

**Comment by n0sign4l-official** [comment]
It was an apk, and my connection is quite stable not very but quite. Consider that anyway it should not that for sure hours to upload it..
