### ISSUE TITLE
Video orientation mismatch between iOS and Android

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-Android#10178]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
(This report was first submitted as an iOS issue, but Imperiopolis-Signal requested that I resubmit it under Android: https://github.com/signalapp/Signal-iOS/issues/4598)

If iOS video is landscape, then Android video renders as the middle third of this rectangle, as portrait orientation. There is then a gross mismatch between what the iOS user thinks is being shown, and what the Android user actually sees. There's no obvious way to toggle this behavior, for that matter.

### Steps to reproduce
- Initiate a video call between iOS and Android Signal installations. (This might also apply to other combinations that I didn't test.)

- Hold the iOS phone horizontally so as to create a landscape orientation. Then, no matter how the Android phone is oriented, it will always show the middle third vertical strip of the landscape.

**Actual result:**
Android: "I said, hold the phone horizontally!"
iOS: "I am! Can't you see the left and right side of the street?"
Android: "No! I see only the road ahead! Don't you know the difference between portrait and landscape?!"

**Expected result:**
WYSIWYG, like it's been since the dark ages of UI design.

This sounds related, but not quite the same issue:

signalapp/Signal-Android#9865

### Device info
**Device:** (Recent iPhone and Android)

**Android version:** 10

**Signal version:** (latest as of this date)

**Comment by nishaero** [comment]
Facing the same issue, is this already fixed?

**Comment by hiisukun** [comment]
Experienced this a couple of days ago, exactly as described.

Android: 11 (2021 01 05)
Signal: 5.1.9

On the same day I also experienced #9865, while calling another Android user. Seems related (incoming video orientation) so I thought I'd mention it here too.

**Comment by gdish** [comment]
I'm facing the same issue.

Signal: 5.3.12
Android 9
Device: Motorola Moto G6

Debug log:
https://debuglogs.org/48bae43e3b57f0384eb010719d3b562360e24c51ec1d1eb2d4688c6dd12e525c

**Comment by gdish** [comment]
Updated to 5.4.7 and don't seem to have the issue any more.

I'm assuming one of these two commits fixed the issue (2678a0078173a0cb88746ad3341657951b6fd024, 0b639e01698e9e15024367ad276767456d2ec0ac) but haven't looked into either of them beyond the commit message

Does anyone else still have this issue with an updated version of Signal?

**Comment by kevinlambert** [comment]
Related post in Signal Community: https://community.signalusers.org/t/video-orientation-issues-across-devices-and-platforms/28272

**Comment by greyson-signal** [comment]
I believe this behavior has been addressed, and should work on the latest Android builds. Thanks!
