### ISSUE TITLE
FEATURE REQUEST: Two or multiple accounts in the same app instance

### ISSUE THREAD

**Issue by Filbuntu** [signalapp/Signal-Android#10180]
I would like to run two to three Signal accounts (private/work) at the same time in the Signal App. Will this be possible in the near future?
[Wire supports to log in to Wire with up to 3 accounts](https://support.wire.com/hc/en-us/articles/115003863149-How-many-Wire-accounts-can-I-log-in-to-at-once-) and this feature has been there for years.
Thanks for looking into this!

**Comment by greyson-signal** [comment]
Hi there, we only use github to track bugs. For feature requests, please use [the forum](https://community.signalusers.org/). Thanks!

**Comment by Filbuntu** [comment]
Thank you, @greyson-signal, for the quick and helpful feedback.

**Comment by Filbuntu** [comment]
I agree with [the last comment](https://community.signalusers.org/t/multiple-separate-user-profiles-for-example-but-not-exclusive-to-dual-sim-phones/2361/31):  
"This topic is open since almost 3 years now, i wonder why Signal did not implement it yet."  
Although it is a feature request it could be treated as bug 😉 as the request has not been implemented for so many years and the other messengers have it already.

**Comment by hardhub** [comment]
@greyson-signal It is crucial thing and I personally think the issue should be reopened. Forum is not enough well. At least I did not find any topic there except 2 SIMs.

It is really "must have" feature, we often use more than 1 number. And at least 2 worlds should be in 1 device.    
Even shitty Telegram has such feature...
