### ISSUE TITLE
Incorrect year applied to saved photos

### ISSUE THREAD

**Issue by Frivolous2** [signalapp/Signal-Android#10189]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I save an image to Gallery from Signal, the year is vastly into the future, and the date is wrong. This might have started happening after I quit Beta and updated to Stable. I have not yet tried a reinstall.

### Steps to reproduce
- tap on a photo in the chat
- click the three dots, and then "Save"
- open gallery app or Signal's photo share menu

**Actual result:** 
Any saved photos will always be first because their date is vastly in the future.
**Expected result:** 
Signal puts the correct timestamp on the photo, either the original, or when it was saved to gallery.

### Screenshots
![signal-2020-11-12-235459](https://user-images.githubusercontent.com/57101103/99010751-82f38a00-2542-11eb-89ec-9ea48fc9257f.jpg)

### Device info
**Device:** Samsung Galaxy A3(2017)
**Android version:** 8.0.0
**Signal version:** 4.76.3

### Link to debug log
https://debuglogs.org/03c6bcdbc756a2ff9da2c22fa7eeecebaae9426c1760d6ca46095bcfbcea054c

**Comment by Frivolous2** [comment]
The issue seems to have resolved itself after starting and cancelling a backup...?

**Comment by Genis-Sage** [comment]
Hey @Frivolous2 
For me this sounds like a duplicate of #10142 

Can you tell us the name of the files?

**Comment by Frivolous2** [comment]
You're right. I didn't examine that issue closely, sorry about that. The file names are similar:
![Screenshot_20201113-171448_Gallery](https://user-images.githubusercontent.com/57101103/99100926-22ad2880-25d4-11eb-8d74-8f023854c4ee.jpg)
![Screenshot_20201113-171501_Gallery](https://user-images.githubusercontent.com/57101103/99100957-2476ec00-25d4-11eb-9d72-a99813656e82.jpg)

**Comment by thenlich** [comment]
I can reproduce this with Signal 5.2.3 on Samsung A6plus Android 10.

When I send an image named 20210122_224051.jpg, saving it and viewing details in gallery:

27. Januar 53033 14:28
signal-2021-01-22-224135.jpg
