### ISSUE TITLE
Navbar color in dark theme is not consistent between menus

### ISSUE THREAD

**Issue by AnonWombat** [signalapp/Signal-Android#10182]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Android navigation bar color isn't consistent across menus in dark mode. 
In chats and most main menus, the navigation bar color correctly matches the rest of the app. 
However, in the following pages the navigation bar color does not match:
- Settings and every page in it
- Group settings --> 'Custom notifications'
- Group settings --> 'Member requests & invites'
- Group settings --> 'Group link'
- Insights
- Hold down on message --> 'Message details'
(These are all examples I could find, there may be more)

### Steps to reproduce
- Set theme to dark 
- Open the menus listed above
- Notice the difference in navigation bar color

**Actual result:** The navigation bar color varies for different menus (black, light grey, dark grey)
![Screenshot_20201109-194930__01](https://user-images.githubusercontent.com/44946401/98590264-7400a380-22c6-11eb-82fe-dad752099c00.png)
**Expected result:** The navigation bar color should always be the same color as the rest of the app
![Screenshot_20201109-194921__01__01](https://user-images.githubusercontent.com/44946401/98590275-782cc100-22c6-11eb-848e-64caf2efe4c8.png)

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 4.76.3

**Comment by Salt505** [comment]
As of the Settings redesign in 5.11.x, the situation has improved! All pages in settings now have a consistent navbar background color. The other pages listed in the original post still do have inconsistent navbar backgrounds. However, the progress is very much appreciated! :)
