### ISSUE TITLE
Do not implement EU backdoor as it may be EU law soon

### ISSUE THREAD

**Issue by SomeStrangeName** [signalapp/Signal-Android#10183]
There is current plan in the EU to force backdoors on encryption software.
Sources are:
* https://www.heise.de/hintergrund/EU-Regierungen-planen-Verbot-sicherer-Verschluesselung-4951415.html
** They liked the documents:
*** https://www.heise.de/downloads/18/2/9/9/8/5/2/0/eu-council-draft-declaration-against-encryption-12143-20.pdf
*** https://www.heise.de/downloads/18/2/9/9/8/5/2/0/783284_fh_st12143-re01en20_783284.pdf
* https://fm4.orf.at/stories/3008930/

There is already at least one - probably more - petition against that.
https://www.change.org/p/council-of-the-european-union-eu-weites-verschl%C3%BCsselungsverbot-verhindern-um-die-pers%C3%B6nliche-privatsph%C3%A4re-zu-bewahren?recruiter=1162764633&recruited_by_id=cf135170-2206-11eb-845f-012f30f210b6

So compared to this ticket https://github.com/signalapp/Signal-Android/issues/8974 the mentioned topic is real.

**Comment by Cerberus0** [comment]
Hi @SomeStrangeName,

Welcome to the Signal Android issue tracker! Please note that this issue tracker is only meant for bug reports. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!

**Comment by SomeStrangeName** [comment]
https://community.signalusers.org/t/eu-member-states-about-to-ban-secure-end-to-end-encryption/18229/3
