### ISSUE TITLE
GV2 admin can be lost

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#10191]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If the last/only admin of a GV2 group blocks the group, the admins leaves the group without selecting a new admin.

### Steps to reproduce
- the last/only admin blocks the group
- the person leaves the group without choosing a new admin

**Actual result:** No admin anymore in the group
**Expected result:** An admin is in the group

### Screenshots
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-72-release/17019/86

**Comment by candoumbe** [comment]
Additionnally if you
1. Create a group with no one in it => you're admin
2. Generate the group link
3. Leave the group
4. Join the group via the link created in step 2

=> you're no longer admin and there's no admin in the group

**Comment by bme13** [comment]
In addition to the comment of @candoumbe above if you do execute that sequence multiple times every time there is an extra instance of you added to the group. See the image below.
![image](https://user-images.githubusercontent.com/25846829/104472981-cc9d3700-55bc-11eb-8395-e3d4f1c9557c.png)

**Comment by Meteor0id** [comment]
These are bugs and should be fixed, however at the sane time there is denand for a feature which allows to create grouos without an admin. If these bugs are fixed, please xonsider leaving at least one proper method of creating a group without an admin.

**Comment by axlevxa** [comment]
> These are bugs and should be fixed, however at the same time there is demand for a feature which allows to create grouos without an admin. If these bugs are fixed, please xonsider leaving at least one proper method of creating a group without an admin.

Yes, please don’t fix these bugs without adding this feature (back)! There is an urgent need for egalitarian groups. It was possible in GV1 as I recall and GV2 should not be a regression.

**Comment by Sgn-32** [comment]
Not tested if an admin can be lost, but issue should be analyzed more.

**Comment by Sgn-32** [comment]
From the Android 5.33 beta. 
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-33-release/42513/85

Signal Server had a commit
https://github.com/signalapp/storage-service/commit/914383417733c17124277d8d373da821753026a5

This hadn't worked on my test group with no admin. Maybe because one group member isn't a Signal user anymore?
The group has also enabled the group link with admin approval.
