### ISSUE TITLE
Verify pin success flow is confusing

### ISSUE THREAD

**Issue by jsoref** [signalapp/Signal-Android#10207]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal periodically prompts to verify the PIN, and at times will say `We'll remind you again later.` (`SignalPinReminders_well_remind_you_again_later`) .
It's unclear whether the user got the PIN wrong after too many times or the user got it right.

### Steps to reproduce
- Open Signal (after a couple of days of non use)
- Get a verify PIN prompt
- Enter a couple of guesses for the PIN

**Actual result:**
At some point see a message about checking later and the prompt goes away.

It's hard to tell if the PIN prompt went away because of "too many guesses, I don't want to let the user test all possible values" or "User guessed right".

**Expected result:**
Something slightly more affirmative to indicate that the PIN was correct in addition to that it will ask again later.

### Screenshots
![image](https://user-images.githubusercontent.com/2119212/151466260-ff847423-e47a-418d-9f99-4cfa904b25b0.png)

### Device info

**Device:** Pixel 3a
**Android version:** 11 (Security update 2020-11-05)
**Signal version:** 4.77.3

**Comment by Meteor0id** [comment]
I have raised this on the forum too, I think I wrote a feature request for a better confirmation, I am thinking a green checkmark or something like that. Also the confirm button is bad UX because if you enter the correct PIN the dialog auto dismisses without waiting for you to press the button. This is unexpected brhavior, the user sees buttons but doesn't get a sure change to read them after entering his PIN.

**Comment by jsoref** [comment]
Here's the simplest change which I think would probably address this:
> Verified. We'll remind you again later.

Or:

> PIN Verified. We'll remind you again later.

**Comment by Meteor0id** [comment]
No, the way to solve it is with signal word (they are coincidentally called that way). It would be:

PIN verified successfully.

The signal word is "success".

Yet still there shouldn't be any text below the input field nor should there be any buttons if the dialog dismissed by itself. Users read top to bottom and might not yet have read the text or the buttons when they already interact with the input field.

**Comment by Sarath9087** [comment]
Yeah, it is confusing but if you enter the correct pin then you will see "we will remind you again later".

**Comment by jsoref** [comment]
Bad bot.

https://github.com/signalapp/Signal-Android/blob/2dd887cd17ab37a8814da046d8b0cb16a86abf74/app/src/main/res/values/strings.xml#L1624

**Comment by jsoref** [comment]
I still care about this. I don't know how to make it progress.
