### ISSUE TITLE
Cannot select Backup for restore

### ISSUE THREAD

**Issue by z3dd1cu55** [signalapp/Signal-Android#10201]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a new installation of the Signal app I am not able to select the backup I want to restore.
When I browse to the location of the backup I can see it in the directory but it is greyed out and I cannot select it. 
The backup was done using Signal v4.76.3 from the Playstore (Aurorastore). 
The restore was tried with the apk v4.76.3 from the Homepage. After it didn't work with the downloaded apk I tried again with the version from the Playstore and had the same result. 
I also tried an older backup from the time when the backup location was fix (/Signal/Backups/) with the same result.

### Steps to reproduce
- delete Signal App
- reinstall it
- select "restore Backup"
- browse to file location
- realize you cannot select the .backup file

### Device info
**Device:** Motorola Moto G5
**Android version:** Android 10 (LineageOS 17.1 without gApps)
**Signal version:** 4.76.3

### Link to debug log
[debug log](https://debuglogs.org/34eeee7bf7808702d3c0935068ee03caa7b5960b643c86e8ff7fbbb80daf36e0)

(Info: to get the debug log I tried to restore the backup. When I wasn't able to select the backup I went back, selected "continue" instead of "restore backup" and tapped the headline several times)

**Comment by cody-signal** [comment]
Hi @z3dd1cu55, can you provide debug logs? You should be able to tap 8 times on the title of any of the registration flow screens to trigger it.

**Comment by z3dd1cu55** [comment]
Hi @cody-signal, thanks for looking into this.
I edited the OP and added the debug log and a description what I did before I took it

**Comment by z3dd1cu55** [comment]
I have deleted the App again and installed the latest version from PlayStore. This time I was able to select the backup.
