### ISSUE TITLE
Audio & Video Issues

### ISSUE THREAD

**Issue by aliveinchrist14** [signalapp/Signal-Android#10200]
Everytime I send or receive any type of audio in a message or a video in a message it's completely messed up. Audio for some reason compresses itself. For example, a 3 minute file will compress to two minutes and then when you play it back it just skips like crazy because it's too compressed when it shouldn't compress at all in the first place. With video, I sent someone a video today and they played it and they said it was just nothing but black for the whole video. This is an ongoing problem I've had for months, can this please be fixed?!?!

**Comment by Genis-Sage** [comment]
Hey @aliveinchrist14 
As this is quite surely not a problem which affects every user, it would be helpful, if you give more information by filling out the issue template and also posting a debug log



- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log
