### ISSUE TITLE
When playing consecutive voice notes, the last second of the voice note gets cut off

### ISSUE THREAD

**Issue by AnonWombat** [signalapp/Signal-Android#10214]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you play consecutive voice notes, the ding at the end cuts off the last second or so of the voice note.

### Steps to reproduce
1. Send two voice notes, both with audio all the way to the end
2. Play them back
3. Notice that the last second of the voice note gets cut off by the ding

**Expected result:** The whole voice note should play, *then* the ding should play.

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 4.78.2

### Link to debug log
https://debuglogs.org/a9799729acefdb4fda64ca0610f70d3c8bbe65bab36060cb2f5588e5b99dadc5

**Comment by iDuck12** [comment]
Having the same issue here on my Pixel 2 XL running Signal v5.2.3 on Android 11.

**Comment by va1entin** [comment]
Same issue with these devices:

OnePlus Nord N10 5G (BE2029)
Android 10
Signal version: 5.10.8

Samsung galaxy xcover 4s
Android 10
Signal version: 5.10.8
