### ISSUE TITLE
Can't "Delete for Everyone" on messages sent via Note to Self

### ISSUE THREAD

**Issue by Victor239** [signalapp/Signal-Android#10218]
- [X] I have searched open and closed issues for duplicates
  

---

### Steps to Reproduce

1.  Send a message in Note to Self on either Desktop or Android
2.  Try to delete it from Android

**Actual Result:**

Only "Delete for Me" option available.

**Expected Result:**

Should be able to choose "Delete for Me" or "Delete for Everyone". It's quite annoying that if I try to delete something from my phone then I also have to delete it from my desktop manually also. 

### Screenshots

![](https://i.imgur.com/PuXGATe.png)

### Platform Info

Signal Version: 4.77.3

Operating System: Android

Linked Device Version: v1.38.1

**Comment by losuler** [comment]
I think it's worth mentioning that the desktop version of Signal currently has this ability (and it deletes the message on android) but as this issue describes, you can't initiate the same from android.

**Comment by hldrm** [comment]
A few days ago, I *thought* I had found out that yes, indeed, on desktop it works, and not on Android – like @losuler is describing.
After researching and fiddling around, I _actually_ found out that the option “delete for all” in general is **only** possible for messages sent within the **last 3 hours**, independent from the current app you are using.
And then I verified that, indeed, it works like that, also on Android: new messages can be deleted for “everyone”.
Described here: https://support.signal.org/hc/en-us/articles/360050426432-Delete-for-everyone

So, I found this feature request, which requests exactly the behaviour we want:
https://community.signalusers.org/t/allow-delete-for-everyone-in-note-to-self-with-no-time-limit-or-tombstone/17528

Thus, this is technically not a bug, @Victor239 .
But we should in any way support the feature request :-)

**Comment by Chuhtra** [comment]
I still experience this. Android version 5.28.10, Linked device version 5.28.0 (Linux).
