### ISSUE TITLE
Signal fails to send SMS to certain numbers (forcing users to fallback to Android Messages)

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#10211]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal fails to send or deliver SMS to certain phone numbers, while other factory installed SMS clients (Android Messages etc.) successfully do it.

I've tested this with various devices with differing Android versions, always arriving at the same results.

**Note:**
These numbers are organizational numbers, that, are used for SMS-based registration processes.

### Steps to reproduce
Since I tried this only for domestic numbers, It wouldn't be possible for others to reproduce.

**Actual result:** Failure to send or deliver
**Expected result:** Successfully send or deliver, like other clients

### Screenshots
![image](https://user-images.githubusercontent.com/34171942/99664308-3d244d80-2a7d-11eb-9545-d9a16da2d897.png)

### Device info

**Device:** *
**Android version:** *
**Signal version:** 5.20.1

### Link to debug log

https://debuglogs.org/60914ba78494a9d5f1ee2189766ee3c3b4e76218bd333cdef94bef9c1675bf2d

**Comment by palday** [comment]
I think occurs when the Signal number is registered to a different country code than the country whose networks you're on. I have this when trying to reply to verification SMS -- Signal prepends the country code of my Signal registration instead of using the raw number for special / network-local numbers.

**Comment by Xashyar** [comment]
> a different country code than the country whose networks you're on

Not in the case which I've reported above.

I tried messaging the same number using https://github.com/moezbhatti/qksms (a dedicated SMS app) and it sends and delivers messages with the same country code prepended.

**Comment by Xashyar** [comment]
This is still reproducible.

**Comment by palday** [comment]
sill reproducible

**Comment by greyson-signal** [comment]
Unfortunately I see no failed sends in the original log. Can you post an updated one to see if we have any better luck?

**Comment by vurokkk** [comment]
Hey guys. This issue still exists in the app. There are national numbers that can't include the country code as prefix, otherwise the SMS will fail. Maybe we need a way to enable/disable the country code per contact. I confirmed that the contact is saved WITHOUT a country code but Signal still prefixes it, resulting in a failed SMS.

**Comment by opseasoi** [comment]
Hi, same issue here. 
Signal is always adding prefix to numbers, even with special local or operator numbers like 275 or other short number. Signal is always adding +262 (my country code), so +262 275 in this example and the message is not sent. 
Please at least add a way to edit number before sending. 
Thanks,
Pascal.

**Comment by Ost99** [comment]
Same issue as #4478.
That issue is marked as closed, but the problem occurs for all short numbers with 5 digits in Norway and likely caused by the automatic addition of country code.

**Comment by zeha** [comment]
This is still reproducible.

**Comment by Xashyar** [comment]
With the advent of [SMS support removal](https://signal.org/blog/sms-removal-android/) I think this issue won't correspond to an actual bug any longer.

**Comment by Xashyar** [comment]
With the advent of [SMS support removal](https://signal.org/blog/sms-removal-android/) I think this issue won't correspond to an actual bug any longer. Closing.
