### ISSUE TITLE
Need person/team to create a Signal Custom Build for HCWs fighting Covid 19

### ISSUE THREAD

**Issue by DougBrownVancouver** [signalapp/Signal-Android#10216]
Not sure where to post a request like this, apologies for using the issues section.

In the hospital we are using Signal on public tablets provided to patients, so that patients can communicate virtually with the healthcare team. We recently uncovered a credible security threat (https://community.signalusers.org/t/option-to-require-pin-to-access-settings/18345). We need to rapidly build and roll out a custom Signal Build with the settings area disabled. I have a small budget that could either be used to pay those who create the custom build or could be donated as thanks into the Signal community.  

A custom Signal APK is required with the following modifications:
1) Settings Locked out so that users cannot change them (disable the top left corner button and the settings option accessible from the three dots menu in the top right corner)
2) Default Settings Changed: Privacy->Incognito Keyboard ->On, Privacy->PIN Reminders -> Off, Privacy ->Registration Lock-> On
3) Auto-Update disabled (so that our custom App is not replaced by the generic app during the next automated update). Ideally we might have a custom auto-update feature that only activated when a new Custom Version was ready for upload & installation.

Ideally we would make the Custom Build available publically so that other healthcare teams or other people who want to use Signal for communication on publically available / shared devices can use it. 

Thank you to everyone who works on Sigal and thank you for considering this request. Sincerely, Dr. Doug Brown. Emergency Physician.

**Comment by figbux** [comment]
I'm not sure how reasonable it'd be; but if no 'forward' engineers comes up, I might be trying 'reverse' engineering to accomplish these tasks. Though seems not so hard, I'd need some time to fit this job into my free times schedule. However, some concerns should pop up on your side:

- As reverse engineering starts from APK rather than the open source code, there will not be something to release open for other people to inspect (in terms of security). I can report the changes I made, though.
- This will not be so sustainable if you'd like get updates, because the newer version would require all the reversing steps reproduced for the new version. A better 'forward' engineering approach would be like "fork the project -> edit and build -> get the necessary small updates from main repo from time to time'. 

So I'll be waiting a proper forward engineer to approach this issue before starting. I'm on the last position in the queue. I hope you find.

**Comment by DougBrownVancouver** [comment]
Thank you fixbug, good comments, fork & edit is the method that has been suggested by others. Here is some reference material that demonstrates the worthiness of the cause:

https://covidvirtualtools.ca/ 
"This is a crowdsourced program, free for hospitals, simple to implement, where patients and healthcare workers communicate securely via donated tablets and smartphones"

For hospitals suffering nursing shortages we have demonstrated nurses on home isolation/lock down, virtually caring for patients to help their own department when they are short staffed: https://youtu.be/EStBnaZ0xe0

Here is our current Healthcare Worker Instructions Page: https://covidvirtualtools.ca/ed-hcw/

Here is our current support page for patients downloading Signal on their own device to be able to communicate with HCWs securely: https://covidvirtualtools.ca/install/

**Comment by duchampdev** [comment]
Independently from the very usecase, I think this feature would be worth having. So I'd be interested to have a look at it and maybe propose it as a PR to the upstream Signal project. Don't take it as a promise, but I might find time to come up with a solution in a week or so. It would be an honor to support this hospital initiative.
But, @DougBrownVancouver , I'm not sure if the Signal team is fine with widespread use of a custom build on their infrastructure. Basically, this should be no problem because the changes would not affect the communication with the servers, but hey, better safe than sorry. So I'd suggest you clarify this first.

**Comment by DougBrownVancouver** [comment]
Thank you @duchampdev, good question about the custom build on their infrastructure. It was in discussion with @alan-signal that the solution of using a custom build was born. The Signal team has been very, very supportive of this project and helping where they can with our quest to leverage the Signal communication platform to help healthcare workers and patients in hospital to have access to inexpensive, safe virtual communication tools (many hospitals don't have the infrastructure and were caught off-guard by this need). @moxie-signal has also been involved and helped us to overcome a couple of initial hurdles. It has been slow going on the hospital front getting administrators to allow these unfamiliar tools to be used but in the last 6 weeks we got a number of key approvals and finally moved out of the shadows and into the realm of approved technologies..... unfortunately as I was deploying more devices and started needing to do some remote management of devices, I discovered the security threat when I realized how easy it would be for someone to link a device to one of my public facing tablets and then monitor Signal communications on that device.

**Comment by duchampdev** [comment]
This is a very informative reply, thanks for taking the time @DougBrownVancouver . Well in that case, I think they will be fine if you run custom builds on your devices. So my spare time is somewhat limited currently, but I'll look what I can do asap. Luckily, I've already some experience with the Signal code.

Just to be sure after reading the forum post briefly: Would re-using the System PIN be fine as well or do you strongly prefer the Signal PIN (although it might be forgotten by the user)?

**Comment by DougBrownVancouver** [comment]
Re-Using the Signal PIN is my preference (forgetting the PIN is not a concern in my workflow). Looking at the big picture, here are a few options that I think would solve my problem:

Option A) Custom Build with Settings Disabled, Auto-update Disabled, Default Settings are Changed to Privacy->Incognito Keyboard ->On, Privacy->PIN Reminders -> Off, Privacy ->Registration Lock-> On, and prevent User Access to Settings from the App.

Option B) Custom Build, require the Signal PIN in order to access Settings from the App.

Options C) No Custom Build but instead the Public Signal App is modified, such that the Settings->Privacy->Signal PIN area (Change Your PIN, PIN Reminders, Registration Lock), gets a fourth Option: Settings PIN Lock (On/Off Slider), as per my post on the Signal Community (https://community.signalusers.org/t/option-to-require-pin-to-access-settings/18345).

Likely there are other permutations that would work, but those are the ones that seem 'easiest' to me..... but if someone who knows the code thinks there is an easier work around, then I am very open to suggestions. In the mean time, I will likely need to shut down the twenty devices I currently have spread around the hospital that we are using to run the different pilot projects..... sad because we finally seem to be reaching a critical mass where HCWs are finally starting to get comfortable with the devices and using them solve problems without being prompted or taught the steps.....

**Comment by duchampdev** [comment]
This would be very sad, to stop the project, especially when it is really about to gain comfortable adoption!

So option A should be something I could do within 1-2 day(s).
Option B, well, it depends on the code, I can't give an estimate for this right now, I'll have to investigate.
Option D seems superior to Option C for the short term, I'd say, to really get a fast solution.
Apart from this, option D appears to be the cleanest and most beautiful solution to me.

My gut feeling would be that Option A + Option D would be the best way to go for now, to keep the project running without interruption. If you want, you can write me an email to the address in my profile and we can discuss details for Option A this way (details that might be off-topic here for the Signal community).

**Comment by Leptopoda** [comment]
Maybe bring this up to someone allready having thier fork (johanw or the guy behindert Molly) 
As theyre allready familiär to the code they might geht this done fast 

Maybe ping them here or on the forum

**Comment by DougBrownVancouver** [comment]
Thank you @Leptopoda , @duchampdev has answered the call and is currently working on it but if we need more help we will definitely reach out as you have suggested.
