### ISSUE TITLE
Notes to self desappear after reinstalling signal with same number

### ISSUE THREAD

**Issue by BruceMustache** [signalapp/Signal-Android#10223]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notes to self desappear after reinstalling signal with same number

### Steps to reproduce
- Install signal
- Delete it and install again using the same number
- Don't backup
- Notes to self isn't reached

### Device info

**Android version:** 10
**Signal version:** 4.76.3

**Comment by Genis-Sage** [comment]
Hey @BruceMustache  
Just to understand it right

Do you mean, that your "note to self" history is lost, when you delete Signal, and reinstall Signal without backup

If yes, that's expected, as note to self messages is saved similarly to all other messages, which you also lose without backup

**Comment by BruceMustache** [comment]
No @Genis-Sage it even appear the notes to self doesn't show to me even if it has nothing
I can't send messages to notes to self

**Comment by BruceMustache** [comment]
There's no option to create a new notes to self
And I don't have one because I reinstall signal

**Comment by grandchild** [comment]
You have to write a message to your own phone number, like any other number (New message button, type or look for the number). The conversation with your own number will turn into "Note to self".

**Comment by BruceMustache** [comment]
Hmm thank you @grandchild I thoght it not trivial
I would like to siggest note to self button in 3 dots menu
But it is out of scope 'cause is a feature request right? Not a bug
