### ISSUE TITLE
Video compression is failed

### ISSUE THREAD

**Issue by NightDeveloper-wq** [signalapp/Signal-Android#10222]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I keep getting this error when I want to send videos over 5 minutes. Some videos are posted, some progressbar just keeps turning and notification has shown. When it does not give an error, the compress process takes a long, long time and it never ends.

### Steps to reproduce
- I pressed the bottom + menu
- Selected gallery menu
- Selected 7 videos in Camera folder
- Trim videos and click send button

**Actual result:** All videos are sending
**Expected result:** Sometimes videos aren't sending

### Device info

**Device:** Huawei P30 Pro
**Android version:** 10.0.0
**Signal version:** 4.78.5

### Link to debug log

```2020-09-14 14:36:55.787 3646-4017/?  E/media-converter: error converting
    java.lang.IllegalStateException: encoded (62) and decoded (64) video frame counts should match
        at .Preconditions.checkState(Preconditions.java:7)
        at .VideoTrackConverter.verifyEndState(VideoTrackConverter.java:419)
        at .MediaConverter.doExtractDecodeEditEncodeMux(MediaConverter.java:262)
        at .MediaConverter.convert(MediaConverter.java:143)
        at .InMemoryTranscoder.transcode(InMemoryTranscoder.java:182)
```

**Comment by greyson-signal** [comment]
Can you please post a full debuglog?
