### ISSUE TITLE
Split Screen Mode Breaks UI with Dark Theme

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10220]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The dark theme gets temporarily broken when entering/leaving split screen mode 

### Steps to reproduce
- Be in dark mode
- Open a conversation
- Enter split screen mode with another app 
- Dismiss the second app 

**Actual result:** Some of the conversation suddenly isn't in dark mode. App also becomes difficult to read
**Expected result:** App should visually be the same as it was before going into split screen mode

### Screenshots

![dark](https://user-images.githubusercontent.com/22125581/100161205-fbc9de80-2e7e-11eb-8dd7-94212f5180a6.gif)

### Device info

**Android version:** 10
**Signal version:** 4.78.5

**Comment by Genis-Sage** [comment]
I tried to reproduce this behaviour, but I could not reproduce it at first, because my Android was set to dark theme and Signal to follow System theme

The issue only seems to happen, if system is set to light theme, and Signal is set to dark theme

**Comment by cody-signal** [comment]
@bitmold @Genis-Sage I'm unable to reproduce this with the latest Signal beta (5.0.x). We included a slight change around multi-window support that may have fixed this issue. Would you be able to test on the latest beta and see if the issue still occurs? You can register via the play store or get more info here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-0-release/18811

**Comment by Genis-Sage** [comment]
hey @cody-signal 
I just tried it after update to 5.0.3 (beta)

it is still reproducible

my current settings
System: dark theme
Signal: light theme
the second app was Firefox (following system theme, so also dark)
