### ISSUE TITLE
spinning circle for creating the debug log has a square in background

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#10229]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
spinning circle for creating the debug log has a square in background

### Steps to reproduce
- generate a debug log
- While waiting for the debug log, see the spinning circle

**Actual result:** spinning circle for creating the debug log has a square in background
**Expected result:** spinning circle for creating the debug log hasn't a square in background
Maybe the spinning circle has blue color, like other spinning circles in Signal

### Screenshots

![Screenshot_1606592958](https://user-images.githubusercontent.com/49990901/100526208-08c03800-31c7-11eb-9c35-b3feefa35fe3.png) ![Screenshot_1606592986](https://user-images.githubusercontent.com/49990901/100526210-0958ce80-31c7-11eb-9dc7-8a48b26503d3.png)

**Comment by greyson-signal** [comment]
We're just using a generic "pending spinner" thing we use in several places throughout the app. I think it's suitable for what it is, but feel free to discuss alternate designs on the [forum](https://community.signalusers.org/). Thanks!
