### ISSUE TITLE
Incorrect camera preview after changing device orientation

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#10235]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Signal shows the camera preview and I rotate it (e.g. from portrait to landscape), the camera preview gets screwed up. I.e., it only shows the bottom part (?) of the actual image.
The same happens vice versa, i.e. starting from landscape and rotating to portrait.

(This behavior was also at least present on 4.78)

### Steps to reproduce
- Use the in-app camera
- Rotate the device (e.g. portrait to landscape)

**Actual result:** The camera preview shows an incomplete (and mostly unusable) image.
**Expected result:** The camera preview should be the same (or as similar as possible) to the actual image.

### Screenshots
1) Phone in portrait orientation --> correct:
![signal-2020-12-01-110710](https://user-images.githubusercontent.com/23025712/100727164-2c050600-33c6-11eb-9c95-fec3ca8e32b1.png)

2) Preview after changing it to landscape:
![signal-2020-12-01-110705](https://user-images.githubusercontent.com/23025712/100727210-3921f500-33c6-11eb-84c1-58f92f29b691.png)

3) Image captured in landscape (very different from preview):
![signal-2020-12-01-110619](https://user-images.githubusercontent.com/23025712/100727229-3f17d600-33c6-11eb-9814-5053aabe9c54.jpeg)

### Device info

**Device:** Google Pixel 4
**Android version:** 11 
**Signal version:** 4.79.0

### Link to debug log
https://debuglogs.org/15ba6068693239e9d7d0b7db1b7840418c9a714a311ec795d3205e872d8af418

**Comment by minnmann** [comment]
After having installed the latest Android update as well as Signal 5.0.1, I just want to ask if there is anything I can help, or provide additional details, logs, instructions, screenshots etc.

I would very much appreciate this issue to be fixed, as it currently renders the in-app camera basically useless for me. Thanks!

**Comment by nicolaus-hee** [comment]
Can confirm I still have this in 5.0.8 on a Google Pixel 4 XL with Android 11 (Dec 2020 update).

For me, the preview is not just a different angle but completely distorted / squeezed before taking the picture:

![Screenshot_20210108-154557](https://user-images.githubusercontent.com/48563755/104028576-2b337100-51c9-11eb-9f59-2164a3040f81.png)

**Comment by xCruziX** [comment]
Have this on Mi 9 Miui 12 Android 10.
Signal 5.4.12

**Comment by luopa** [comment]
Same issue here. 

Honor COL-L29
Huawei EMUI 10.0.0, Android 10
Signal 5.21.6
