### ISSUE TITLE
SMS are received with a delay

### ISSUE THREAD

**Issue by sirlada** [signalapp/Signal-Android#10248]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS are received with a delay of up to 12 min. With 2-factor authentication, as with Internet banking sites, this can be a serious problem that can lead to the cancellation of the login. It is worth noting that also sending SMS seems to be delayed. Could be related to #10233, as after switching to 'Google Messages' and back the issue was resolved. Provider was informed, no problem on their end.

### Steps to reproduce
- send SMS with timestamp from other phone

**Actual result:** SMS is received with a delay of up to 12 min (tested various times)
**Expected result:** SMS is received within a reasonable timespan

### Device info

**Device:** Nokia 6.1
**Android version:** 10.0.0
**Signal version:** 4.78.5

### Link to debug log

https://debuglogs.org/d7922ea35fbdfd2121422ad3fd573b1f63af9ea84ebd5dd325e1c8408aad7430

**Comment by greyson-signal** [comment]
Not sure what's happening :/ We have to hook into system events to be told about SMS messages. In your log, I see two instances where we were told about SMS messages, and then they were processed immediately. So no delay after we were told by the system. Only explanation in my mind would be that the system took 12 min to tell us about the message.
