### ISSUE TITLE
Image not displayed on Android but on Desktop

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#10241]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was sent a media message with a photo. This image is not shown in Signal on Android. Instead, a seemingly half-decoded jpeg is shown with an image icon that has a read exclamation-mark  sign attached to it. Interstingly, the same image is displayed on Signal desktop without issues.

### Steps to reproduce
Receiving the same image again reproduces the issue. However, I cannot provide that very image for privacy reasons.

**Actual result:** Image should be shown.
**Expected result:** Half-decoded image and warning icon are displayed.

### Screenshots
![signal-2020-12-03-122111](https://user-images.githubusercontent.com/1287825/101010246-8a66eb80-3562-11eb-9058-0adda66a8e84.jpeg)

### Device info
**Device:** Motorola Moto G7 plus
**Android version:** 10 patch level October
**Signal version:** 4.78.5

### Link to debug log
https://debuglogs.org/49d15750767f79dee202f81c7a03e17a43b71683fbcf5e3766809b3c48b4bb0d

**Question:** Does sending the problem description via the App's help menu suffice (and results in an issue being added here) instead of creating a github issue manually?

**Comment by PiCob** [comment]
Still an issue on Signal v5.1. Happened several times now within a few days, on different Android phones in the same WiFi network, in 1:1 conversations as well as in (v2) groups. The log has been retrieved immediately after facing this error again:
https://debuglogs.org/5b5ac96112be00fc8493dd99ce7fba1c1db333c2a46195c1826f327d21a97dea

For someone else in the group, the image shows correctly (it's simply a Memoji from an iOS user), so the image itself shouldn't be the culprit. If we could at least "re-download" this media...
