### ISSUE TITLE
in some circumstances messages appear to get send without sealed sender

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#10243]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See actual and expected result
### Steps to reproduce
- In a group something happens to some user(s), probably they removed their Signal app without deregistering first
- Send a message in the group, notice the message details show the message has been sent to them, but the sealed sender indicator is missing
- Send more messages over the coming hours or days, and notice that at some point messages are "not send" to this contact anymore.
- Try again the next day and messages are being "sent to" again.

**Actual result:**
Messages get send without sealed sender or at least that's what it looks like, giving the service information it didn't need to have, without any warning to the sender that he will reveal more than he did before to the service.
**Expected result:** 
Don't send a message without sealed sender without approval if previously messages were send with sealed sender.

### Screenshots

![Screenshot_20201203-035340](https://user-images.githubusercontent.com/34976212/101057342-3a9d1a00-358c-11eb-86a3-101e9d7910a9.png)
![Screenshot_20201203-035158](https://user-images.githubusercontent.com/34976212/101057349-3bce4700-358c-11eb-8085-07979d2e9cc2.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0
**Signal version:** 4.79.3

### Link to debug log

Originally raised on the forum here:
https://community.signalusers.org/t/what-happens-with-sealed-sender-once-someone-deletes-signal/18762

**Comment by greyson-signal** [comment]
We don't have any plans to raise a non-sealed-sender message to a level where a user has to interact to approve the send. Sealed sender is best-effort, although it should be happening on almost all messages.

**Comment by Meteor0id** [comment]
@greyson-signal sending a message is currently irradic, some sent, some do not send to these contacts. It may have nothing to do with sealed sender, but there appears to be a bug at play.
