### ISSUE TITLE
most messages do not display "not sent" but instead falsly report "sent to" everyone

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#10250]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On some messages, message details reveal they have been send, on others they reveal the message has not been send. Sending appears to be inconsistent. It may be related to linked Signal-Desktop.

### Steps to reproduce
- In a group something happens to some user(s), probably they removed their Signal app without deregistering first
- Send a message in the group, notice the message details show the message has been sent to them.
- Send more messages over the coming hours or days, and notice that at some point messages are "not send" to this contact anymore.
-Try again the next day and messages are being "sent to" again.

### Screenshots

![](https://user-images.githubusercontent.com/34976212/101057342-3a9d1a00-358c-11eb-86a3-101e9d7910a9.png)

![](https://user-images.githubusercontent.com/34976212/101057349-3bce4700-358c-11eb-8085-07979d2e9cc2.png)

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0
**Signal version:** 4.79.3

### Link to debug log

After a message was sent
https://debuglogs.org/b0ac82e46dd0a6c5941ce3c28236c8c2050ba1e33335d86ac981dd611efd0ab1

After a message was not send
https://debuglogs.org/2c4c2d039ef4aa0730d26e4cc4db55a79ed1dfe912673cb12e9ec78e39d0d036

Not that this bug was previously reported as an issue with sealed sender, and that bug report was closed as it was stated that no work will be done to make sealed sender reliable. It might however not have anything to do with sealed sender, but rather with whether a message is send or not in the first place.
because the inconsistent behavior does not seem to have a trigger moment in mobile, the trigger might be the linked desktop device, but that is only a suspicion.

**Comment by Sgn-32** [comment]
Maybe related to #9941 Group chat inconsistencies accross different clients, message 'sent or not sent'?

**Comment by Meteor0id** [comment]
It could be related but do remark this is happening on the same OS (Android). Some messages appear to get send while they shouldn't, other don't get send. It could be getting caused by a linked desktop device.

**Comment by Sgn-32** [comment]
I looked at the source code for delivery / read receipts because of another problem.
In RecipientDeliveryStatus.java five types are defined:

```
  enum Status {
    UNKNOWN, PENDING, SENT, DELIVERED, READ
  }
```
In MessageDetails.java each message with status UNKNOWN is assigned to "Not sent"

if (conversationMessage.getMessageRecord().isOutgoing()) {
      for (RecipientDeliveryStatus status : recipients) {
        switch (status.getDeliveryStatus()) {
          case UNKNOWN:
            notSent.add(status);
            break;
```
At least, even a Signal user has uninstalled Signal without to unregistering the phone number, the message should be sent to the server.
