### ISSUE TITLE
signal crashing on sending multiple photos to multiple contacts

### ISSUE THREAD

**Issue by nex3n** [signalapp/Signal-Android#10259]
i opened signal clicked on camera button clicked on gallery button selected 13 photos on next screen i selected 3 signal contacts and pressed send signal crashed and now its in loop trying to send messages rotating thing

https://debuglogs.org/77bd48778f0cbbe8f933e23f9413b2d8a89dbdf8e3d9589134340ab143c9b815

**Comment by nex3n** [comment]
fixed it by reinstalling signal and reseting secure session for contacts

**Comment by n0sign4l-official** [comment]
Hi @nex3n since you said it is fixed can you please close this issue?

**Comment by nex3n** [comment]
me nuking signal from orbit is not fixing the bug
how much you get paid by bothering me to close issuse and can i get your job?
