### ISSUE TITLE
Any alternate to Google reCAPTCHA service to verify a user upon registration? - This might fingerprint user without their knowledge.

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#10263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is not a bug but more of a procedure used by Signal to verify a user upon registration using Google reCAPTCHA service.

### Steps to reproduce
- Install the app.
- Use a VPN/Proxy to get Google reCAPTCHA browser prompt quickly.
- No option to bypass this.

**Actual result:** 
Google reCAPTCHA will not allow registration to complete. This process also uses System WebView that is a built in component of android and might have more serious privacy implications.

**Expected result:** 
To find a way other than using Google's services that might fingerprint a user unknowingly.

### Device info

**Device:** OnePlus
**Android version:** 10.
**Signal version:** 4.78.5

**Comment by Genis-Sage** [comment]
hey @desmonk 

i guess the community forum is a better point for that, especially since there is already a thread about it:
https://community.signalusers.org/t/use-something-else-instead-of-google-recaptcha-for-registration/6289

**Comment by desmonk** [comment]
You're right. I did check on forums. Unfortunately, no progress so far.

**Comment by greyson-signal** [comment]
Hi there, we don't use Github for discussion topics. Thanks!

**Comment by desmonk** [comment]
Totally understood. 

Only raised this serious concern here after finding out no progress on the forum. This is not something to be taken lightly. Who knows what Google does with these services. Not to mention the usage of built-in Android WebView/Chrome, which is even more of a privacy risk as the reCAPTCHA service exclusively calls up to use it and no way to bypass any of these.

**Comment by lukefromdc** [comment]
https://github.com/signalapp/Signal-Android/issues/10999
Note that if I were on a rooted device with my desktop hosts file (which blocks ALL of Google) I would not have been able to register Signal due to the Recaptcha silently not showing up, and I would not have known why. I intend to block this on my phone too when I find a way to make hosts files work on difficult to root $50 unlocked Chinese phones, hope I don't have to revert that on future Signal activations.

Last time I had to reactivate Signal I did not get a recaptcha, sometime early last year

**Comment by lukefromdc** [comment]
I would consider being asked to store a code and wait 24 hours to activate Signal an acceptable alternative for those of us who do not want to deal with Google. Use an interstitiaal screen (as either Protonmail or Tutanota does) and you could offer recaptca/donate/wait 24 hours options. I would take the delay, probably accept even a WEEK to avoid Google.
