### ISSUE TITLE
second sim

### ISSUE THREAD

**Issue by Wandelstock** [signalapp/Signal-Android#10267]
as of the new Android version the second sim isn't recognized anymore. So I have no incoming messages anymore on my 2ND sim.

as of version 4.79.3
Android 9

**Comment by greyson-signal** [comment]
Please include debuglogs

**Comment by Wandelstock** [comment]
https://debuglogs.org/308200edb24ac30b6c0e8e8ab66024bd26fa6ecd0947d88b16db9f791324a1d2

**Comment by Wandelstock** [comment]
Problem disapeared, could be the Google carrier v50 problem, I am on v48 back and no problem.

**Comment by Wandelstock** [comment]
for me it isnt. It showed me that Signal wasnt handling sms correct so i stopped using Signal.
