### ISSUE TITLE
Can't attach photos nor see their preview when selecting

### ISSUE THREAD

**Issue by IvanStanul** [signalapp/Signal-Android#10264]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I press blue "+" on bottom right to attach photo I don't see previews of photos. Downloaded images or screenshots appear fine, but photos taken on phone are just black rectangles. Trying to attach aforementioned photo without preview for the first time causes app to return to conversation list. Attaching for second time- crashes the app.
Describe here the issue that you are experiencing.
(Same thing appears when pressing + -> Gallery -> Camera. Can't see previews/attaching causes crash.)

### Steps to reproduce
- Open Signal app
- Choose any conversation
- Press + button in bottom right

**Actual result:** See previews only for downloaded images and screenshots. Previews for actual photos are black.
**Expected result:** See previews for photos taken on phone

### Device info
**Device:** Google Pixel XL
**Android version:** Android 10
**Signal version:** 4.49.3 (although bug occurred in at least few previous versions also)

### Link to debug log
https://debuglogs.org/f82b15db1c89cf01034aadf75530983d03bd96a40b5f03d76d3ce9f9bd1b4f9f

**Comment by jacobvenborg** [comment]
Thanks for submitting this. I'm experiencing the same, quite annoying to be frank. Can't remember exactly when this started happening, but has been going on for at least some weeks. I'm on a Mi A2 Lite, Android 10, Signal 5.0.8. [Here's a debug log](https://debuglogs.org/9da56394624a28b683125381341549081b2821013b085e798034d6204062ed74).

**Comment by blaueente** [comment]
maybe related to https://github.com/signalapp/Signal-Android/issues/10394 ?
