### ISSUE TITLE
Layout shift and loss of android level back functionality after lock/unlock

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#10269]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Noticing some keyboard overlap if my keyboard is open, I lock my phone, and unlock again. This also prevents you from using androids back functionality. You have to click the back arrow on the Signal UI to go back to conversations.

### Steps to reproduce
- open a conversation
- open keyboard 
- lock phone (or wait for screen timeout)
- unlock phone 
You may have to repeat those steps a couple of times and maybe scroll up into a conversation before locking. It happens maybe 50 percent of the time. 

**Actual result:** View layout shifts/breaks
**Expected result:** It's shouldn't break

### Screenshots

![signal-2020-12-15-223551_001](https://user-images.githubusercontent.com/18274896/102431538-b78eb180-3fd8-11eb-8bc4-47968131a077.png)
![signal-2020-12-15-223551_002](https://user-images.githubusercontent.com/18274896/102431556-b8bfde80-3fd8-11eb-9fd3-808694978b4d.png)

### Device info

**Device:** Pixel 4 with GBoard
**Android version:** 11
**Signal version:** 4.79.3 - 5.4.12

### Link to debug log

https://debuglogs.org/c081e0d07713112382a327f8f22caa3e121cc7b355f59e3c49a3cf7c842df72e

**Comment by Tursko** [comment]
This is also happening consistently on 5.0.5. 

https://debuglogs.org/cd4072d70df41c0db5e10dcfe5d2e390173428dafaa489fc18e26b5ef5268c29

**Comment by Tursko** [comment]
Updated log. 
https://debuglogs.org/732120a35ea1e2cfa6cf70847d5bdf9c8dda81175198d6953d8ff21dee52d75b

**Comment by stefanovazzocell** [comment]
Commented about this in the signal community site [already](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/82) but I've been able to reproduce it too. Differently than what OP saw, though.
I have a Google Pixel 4XL (for reference). Here's how to reproduce this bug for me (works 100% of the times):


1. Open a conversation
2. Open keyboard
3. Do NOT lock phone, let it time out and lock itself (screen goes blank and all)
4. Unlock phone

For me this works 100% of the times. @Tursko can you confirm if this is also what you're seeing?

**Comment by Tursko** [comment]
> Commented about this in the signal community site [already](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/82) but I've been able to reproduce it too. Differently than what OP saw, though.
> I have a Google Pixel 4XL (for reference). Here's how to reproduce this bug for me (works 100% of the times):
> 
> 1. Open a conversation
> 2. Open keyboard
> 3. Do NOT lock phone, let it time out and lock itself (screen goes blank and all)
> 4. Unlock phone
> 
> For me this works 100% of the times. @Tursko can you confirm if this is also what you're seeing?

Yes, this also works for me.

**Comment by stefanovazzocell** [comment]
I've been unable to reproduce this in 5.3.4
I wonder if it got fixed sometimes during the 5.3.# release

**Comment by Tursko** [comment]
> I've been unable to reproduce this in 5.3.4
> I wonder if it got fixed sometimes during the 5.3.# release

I updated and I still encounter the issue if I follow your method.

**Comment by csnover** [comment]
I can reproduce this (with the automatic screen lock only, manual lock always seems to be OK) on latest Signal 5.3.12 on Galaxy S10e. This only started happening after upgrading to Android 11.

**Comment by longspell** [comment]
Still happens in 5.4.4

**Comment by Vertiqo** [comment]
Still happens for me, pixel 4a, gboard.

**Comment by Tursko** [comment]
Not sure why but it feels worse in 5.4.12

**Comment by RJ97GH** [comment]
Happens for me on a pixel 4

**Comment by Tursko** [comment]
> Happens for me on a pixel 4

I've seen it on a Pixel 4, Pixel 4a 5g, and my new Pixel 5. All using gboard.

**Comment by cody-signal** [comment]
Hope to have a fix in 5.10.3 which is will be out in beta later today.

**Comment by Tursko** [comment]
Has anyone tested Cody's fix in 5.10.3?

**Comment by Tursko** [comment]
Seems to be fixed. Thank you!!
