### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Juanca24692** [signalapp/Signal-Android#10278]
I have cloned the Signal-Android repository all fine so far, when I run 'gradlew.bat build' in terminal it throws me this error

"" C: \ work \ Signal-Android> gradlew.bat build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ': core-util'.
> Could not create task ': core-util: lint'.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C: \ work \ Signal-Android \ local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s

C: \ work \ Signal-Android> gradlew.bat build

> Configure project: Signal-Android
The com.google.protobuf plugin was already applied to the project:: Signal-Android and will not be applied again after plugin: android
WARNING: API 'BaseVariant.getApplicationIdTextResource' is obsolete and has been replaced with 'VariantProperties.applicationId'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see TBD.
To determine what is calling BaseVariant.getApplicationIdTextResource, use -Pandroid.debug.obsoleteApi = true on the command line to display more information.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ': Signal-Android'.
> Failed to notify project evaluation listener.
   > Could not create task ': Signal-Android: minifyPlayProdDebugWithR8'.
      > Cannot query the value of this provider because it has no value available.
   > Could not create task ': Signal-Android: minifyPlayStagingDebugWithR8'.
      > Cannot query the value of this provider because it has no value available.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 22s ""

**Comment by greyson-signal** [comment]
Hi there, we only handle bugs on Github. For assistance with builds, please visit the [forum](https://community.signalusers.org/). FWIW we have a daily Github Action that verifies our reproducible builds, which is still green at the time of writing, so whatever build problem you're experiencing is a result of some misconfiguration of your build environment.
