### ISSUE TITLE
 Signal source code does not save changes !!

### ISSUE THREAD

**Issue by LucianoCM7** [signalapp/Signal-Android#10273]
Good morning everyone ... someone ka messed with the source code of the signal ... I can generate the apk but the changes are not saved ... I am changing the text from within the application so that when I install the apk the changes in text does not appear

I found the xml file I change everything else but not saved in time to generate the apk ... when I see inside the application it is not my changes I made in the text

Keep the default text of the application ... it looks like it's blocked ... but it's on git to download

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by greyson-signal** [comment]
Might be an Android Studio bug we see occasionally during development. Try cleaning before you build. You can also always build from the command line. Regardless, we use github for application bugs. For development help, please check out the [forum](https://community.signalusers.org/). Thanks!
