### ISSUE TITLE
botton position rotates together with screen when in camera mode

### ISSUE THREAD

**Issue by Genis-Sage** [signalapp/Signal-Android#10274]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
the buttons in the camera view are on different places, depending if you open the camera and then turn the phone, or if you turn the phone and then open the camera

### Steps to reproduce
- open a conversation
- click on the camera icon
- observe, that the trigger button is near your (right) thumb
- turn your phone from portrait to landscape or vice versa

**Actual result:** position of all bottons rotate with the screen
**Expected result:** the buttons only rotate themself, but keep the position

### Screenshots
have phone in landscape and open camera --> good
![landscape](https://user-images.githubusercontent.com/6865155/101817352-8cace500-3b22-11eb-9338-9b4d777122dc.jpg)

keep camera open and turn to portrain --> bad
![landscape to portrait](https://user-images.githubusercontent.com/6865155/101817365-920a2f80-3b22-11eb-9029-fac06834c904.jpeg)

have phone in portrait and open camera --> good
![portrait](https://user-images.githubusercontent.com/6865155/101817879-5cb21180-3b23-11eb-8c8b-c189c1223b07.jpeg)

keep camera open and turn to landscape --> bad
![portrait to landscape](https://user-images.githubusercontent.com/6865155/101817925-6e93b480-3b23-11eb-8b5a-035c2e13b277.jpeg)

### Device info
**Device:** Nokia 7 Plus
**Android version:** 10.0.0
**Signal version:** 4.79.3

### Link to debug log
I can post one if needed

**Comment by minnmann** [comment]
Seems related to https://github.com/signalapp/Signal-Android/issues/10235

**Comment by Genis-Sage** [comment]
@minnmann 
it could be related, but I can't reproduce the behaviour from #10235

**Comment by mckeowbc** [comment]
On a Pixel 4a 5g running Signal 5.1.9 on Android 11 build RQ1A.210105.003 I get the behavior as shown. The shutter button moving to the center of the screen makes it very difficult to use the camera. 

![Screenshot_20210117-113211](https://user-images.githubusercontent.com/7218329/104849502-0bcad100-58b8-11eb-95dd-e9da7ba96e8c.png)


![Screenshot_20210117-113219](https://user-images.githubusercontent.com/7218329/104849505-11c0b200-58b8-11eb-90f6-49b7d0700d11.png)

**Comment by tyu1996** [comment]
Is this issue under development? I use Signal all the time and it makes the UX minus every time I wanted to take a photo directly from Signal.

**Comment by ProfEibe** [comment]
I think this is already fixed and can be closed.
