### ISSUE TITLE
Network Failed! happening several times when calling between our Samsung S8s

### ISSUE THREAD

**Issue by gab81** [signalapp/Signal-Android#10281]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Network Failed! happening several times in last 2 months when calling between our Samsung S8s

### Steps to reproduce
- Do an audio or video call
- Phone that makes the call rings for a bit (maybe 5 seconds) so you think it works OK, then you get network failed!
- Random, 2 times it works fine, 2 times it drops and you have to call twice every time. more often audio only drops

**Expected result:** Call to connect first time properly, like Telegram or Whatsapp, etc

### Device info

**Device:** Samsung S8
**Android version:** 9.0
**Signal version:** 4.79.3

Debug Log: https://debuglogs.org/9c10750e9a950dca5dfdee99f64597357725d0c583a4b07597ca7365eb13ac02

**Comment by gab81** [comment]
again, this was happening today - i had low signal, and "signal" couldn't get a phone or audio call no matter what! not even messages. I managed to have a choppy video call on WhatsApp and an OK normal voice call. Why is Signal so struggling to connect when the signal is not PERFECT? when the video calls work they are beautiful but it seems that if everything isn't perfect signal wise (can't get any other word sorry), then it will not even bother connecting and not even delivering messages.

Can you please address these issues? thanks

**Comment by gab81** [comment]
have to report it again, today, called my contact that uses Signal, call, ring ring ring ring for 30 40 seconds, call just went off on my end, then called again, and other end ringed and picked up, when i asked "hey did you hear it ring, other end said no", so this consistently happens.

My phone was on 4G LTE on KPN (NL) 4G+ full signal and other end was on strong wireless indoors.

**Comment by Blacktail92** [comment]
> have to report it again, today, called my contact that uses Signal, call, ring ring ring ring for 30 40 seconds, call just went off on my end, then called again, and other end ringed and picked up, when i asked "hey did you hear it ring, other end said no", so this consistently happens.
> 
> My phone was on 4G LTE on KPN (NL) 4G+ full signal and other end was on strong wireless indoors.

The exact opposite happens to me since a couple of weeks ago. I can make calls successfully but when I get a call, phone doesn't ring at all only displays a network error and a missed call afterwards. Tested on both good cellular and wifi networks, same.

**Comment by gab81** [comment]
ok this only confirms that something's going on and they should fix it.

**Comment by n0sign4l-official** [comment]
I can confirm this issue too, if developers need more logs I can provide them since it is quite reproducible

**Comment by Blacktail92** [comment]
I've tried to reproduce this issue today with 2 phones running Signal 5.0.8(7592).

Device 1: xiaomi mi9t, rooted, no gapps (microg only), resurrection remix 8.6.3 a10 aosp rom.

Device 2: Samsung A31 (SM-A315F/DS), no root, full gapps, oem a10 rom.

Issue: Device 1 can succesfully call device 2 without any problems whatsoever. However when device 2 tries to call device 1, following happens in device 1:

- Incoming call notification comes in but no call ui comes up.
- If Signal is in foreground it gets closed gracefully and incoming call notification disappears.
- No indication of a call reappears at all even if Signal gets opened by user.
- Missed call notification comes in after device 2 eventually hangs up after timeout.

Here is my debug log: 

https://debuglogs.org/bac438fc44e64f78df8ea21581a95d2eaa31e93a4356d55b13b01837bf030619

**Comment by gab81** [comment]
thanks for sharing  @Blacktail92 - i really hope they pick this one up as it's not just one or two people...

**Comment by gab81** [comment]
and by the way, it should always ring when you "don't know" somebody is calling you, obviously otherwise it defeats the purpose.

**Comment by gab81** [comment]
did anyone have any luck from support with this? happened again today, called my wife, ring ring ring ring, then failed, then called her again, asked her hey did it ring? No. disappointing. how can you even know if it rings

**Comment by n0sign4l-official** [comment]
Hi, please do not bump issues, they will look into it asap, they are probably on vacation rn.
Let's just wish them the best holidays, they did an amazing job in 2020. Keep up the good work signal team!

**Comment by gab81** [comment]
sorry but i have to share this one again

again network failed. **i turned on the option in sms mms for wifi calling compatibility mode with voice over LTE**. going better couple of days now again called my wife ring ring ring, she picked up and i got network failed! had to call twice again. She is at home on wifi voice over wifi, me out on mobile network over voLTE.

i cannot imagine journalists or who really really needs encryption being frustrated with dropping calls and not answering so you never know of the other end answers or is just the connection that sucks.

one last thing, even if bad signal whatsapp always connects even crappy video but usually goes through. why cant signal too?

thank you

**Comment by JsBergbau** [comment]
Just want to mention a very similiar issue. I'm on Wifi, 4 meters from AP away, no obstacles inbetween, so best signal. Try calling another phone, immediately "Network failed". Tried again, no calling worked. Had this several times today when testing call function.

**Comment by cody-signal** [comment]
Hey Folks, thanks for sticking with us. We recently pushed some fixes and hopeful changes to calling in the [latest 5.6 beta](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-6-release/30590).

I'm hopeful it'll fix some issues for some of you but I believe gremlins are still lurking in calling. So, after updating to the beta, if you are still encountering the issues above please provide updated debug logs and anything interesting about your calling situation. Examples of things that are interesting: phone has non-standard hardware (like no camera), using bluetooth, in a region that has internet restrictions, using a VPN, etc.

**Comment by Blacktail92** [comment]
I can confirm that if installed to both phones, v5.6.2 (80702) solves the issue I previously submitted. Thank you devs!

https://github.com/signalapp/Signal-Android/issues/10281#issuecomment-751377826
