### ISSUE TITLE
Execution failed for task ':libsignal-service:test'

### ISSUE THREAD

**Issue by Juanca24692** [signalapp/Signal-Android#10280]
I am compiling the source code but at some point during the compilation I have problems

"" * What went wrong:
Execution failed for task ':libsignal-service:test'.
> There were failing tests. See the report at: file:///C:/work/Signal-Android/libsignal/service/build/reports/tests/test/index.html ""

if i checked the above mentioned file by the console i get 4 failed tests

test_sticker_decryptFailOnBadKey
"" java.lang.UnsatisfiedLinkError: C: \ Users \ juan \ AppData \ Local \ Temp \ resource3573644187819422539.so:% 1 no es una aplicación Win32 válida
	en java.base / jdk.internal.loader.NativeLibraries.load (método nativo)
	en java.base / jdk.internal.loader.NativeLibraries $ NativeLibraryImpl.open (NativeLibraries.java:383)
	en java.base / jdk.internal.loader.NativeLibraries.loadLibrary (NativeLibraries.java:227)
	en java.base / jdk.internal.loader.NativeLibraries.loadLibrary (NativeLibraries.java:169)
	en java.base / java.lang.ClassLoader.loadLibrary (ClassLoader.java:2407)
	en java.base / java.lang.Runtime.load0 (Runtime.java:747)
	en java.base / java.lang.System.load (System.java:1857)
	en org.signal.client.internal.Native.copyToTempFileAndLoad (Native.java:37)
	en org.signal.client.internal.Native.loadLibrary (Native.java:53)
	en org.signal.client.internal.Native. <clinit> (Native.java:64)
	en org.whispersystems.libsignal.kdf.HKDF.deriveSecrets (HKDF.java:23)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.expandPackKey (AttachmentCipherTest.java:232)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.test_sticker_decryptFailOnBadKey (AttachmentCipherTest.java:174)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en junit.framework.TestCase.runTest (TestCase.java:176)
	en junit.framework.TestCase.runBare (TestCase.java:141)
	en junit.framework.TestResult $ 1.protect (TestResult.java:122)
	en junit.framework.TestResult.runProtected (TestResult.java:142)
	en junit.framework.TestResult.run (TestResult.java:125)
	en junit.framework.TestCase.run (TestCase.java:129)
	en junit.framework.TestSuite.runTest (TestSuite.java:252)
	en junit.framework.TestSuite.run (TestSuite.java:247)
	en org.junit.internal.runners.JUnit38ClassRunner.run (JUnit38ClassRunner.java:86)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass (JUnitTestClassExecutor.java:110)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:58)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:38)
	en org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass (AbstractJUnitTestClassProcessor.java:62)
	en org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass (SuiteTestClassProcessor.java:51)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch (ContextClassLoaderDispatch.java:33)
	en org.gradle.internal.dispatch.ProxyDispatchAdapter $ DispatchingInvocationHandler.invoke (ProxyDispatchAdapter.java:94)
	en com.sun.proxy. $ Proxy2.processTestClass (Fuente desconocida)
	en org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass (TestWorker.java:119)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:182)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:164)
	en org.gradle.internal.remote.internal.hub.MessageHub $ Handler.run (MessageHub.java:414)
	en org.gradle.internal.concurrent.ExecutorPolicy $ CatchAndRecordFailures.onExecute (ExecutorPolicy.java:64)
	en org.gradle.internal.concurrent.ManagedExecutorImpl $ 1.run (ManagedExecutorImpl.java:48)
	en java.base / java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
	en java.base / java.util.concurrent.ThreadPoolExecutor $ Worker.run (ThreadPoolExecutor.java:630)
	en org.gradle.internal.concurrent.ThreadFactoryImpl $ ManagedThreadRunnable.run (ThreadFactoryImpl.java:56)
	en java.base / java.lang.Thread.run (Thread.java:832)  ""

test_sticker_decryptFailOnBadMac
"" java.lang.NoClassDefFoundError: No se pudo inicializar la clase org.signal.client.internal.Native
	en org.whispersystems.libsignal.kdf.HKDF.deriveSecrets (HKDF.java:23)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.expandPackKey (AttachmentCipherTest.java:232)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.test_sticker_decryptFailOnBadMac (AttachmentCipherTest.java:191)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en junit.framework.TestCase.runTest (TestCase.java:176)
	en junit.framework.TestCase.runBare (TestCase.java:141)
	en junit.framework.TestResult $ 1.protect (TestResult.java:122)
	en junit.framework.TestResult.runProtected (TestResult.java:142)
	en junit.framework.TestResult.run (TestResult.java:125)
	en junit.framework.TestCase.run (TestCase.java:129)
	en junit.framework.TestSuite.runTest (TestSuite.java:252)
	en junit.framework.TestSuite.run (TestSuite.java:247)
	en org.junit.internal.runners.JUnit38ClassRunner.run (JUnit38ClassRunner.java:86)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass (JUnitTestClassExecutor.java:110)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:58)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:38)
	en org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass (AbstractJUnitTestClassProcessor.java:62)
	en org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass (SuiteTestClassProcessor.java:51)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch (ContextClassLoaderDispatch.java:33)
	en org.gradle.internal.dispatch.ProxyDispatchAdapter $ DispatchingInvocationHandler.invoke (ProxyDispatchAdapter.java:94)
	en com.sun.proxy. $ Proxy2.processTestClass (Fuente desconocida)
	en org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass (TestWorker.java:119)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:182)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:164)
	en org.gradle.internal.remote.internal.hub.MessageHub $ Handler.run (MessageHub.java:414)
	en org.gradle.internal.concurrent.ExecutorPolicy $ CatchAndRecordFailures.onExecute (ExecutorPolicy.java:64)
	en org.gradle.internal.concurrent.ManagedExecutorImpl $ 1.run (ManagedExecutorImpl.java:48)
	en java.base / java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
	en java.base / java.util.concurrent.ThreadPoolExecutor $ Worker.run (ThreadPoolExecutor.java:630)
	en org.gradle.internal.concurrent.ThreadFactoryImpl $ ManagedThreadRunnable.run (ThreadFactoryImpl.java:56)
	en java.base / java.lang.Thread.run (Thread.java:832)  ""

test_sticker_encryptDecrypt
"" java.lang.NoClassDefFoundError: No se pudo inicializar la clase org.signal.client.internal.Native
	en org.whispersystems.libsignal.kdf.HKDF.deriveSecrets (HKDF.java:23)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.expandPackKey (AttachmentCipherTest.java:232)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.test_sticker_encryptDecrypt (AttachmentCipherTest.java:151)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en junit.framework.TestCase.runTest (TestCase.java:176)
	en junit.framework.TestCase.runBare (TestCase.java:141)
	en junit.framework.TestResult $ 1.protect (TestResult.java:122)
	en junit.framework.TestResult.runProtected (TestResult.java:142)
	en junit.framework.TestResult.run (TestResult.java:125)
	en junit.framework.TestCase.run (TestCase.java:129)
	en junit.framework.TestSuite.runTest (TestSuite.java:252)
	en junit.framework.TestSuite.run (TestSuite.java:247)
	en org.junit.internal.runners.JUnit38ClassRunner.run (JUnit38ClassRunner.java:86)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass (JUnitTestClassExecutor.java:110)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:58)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:38)
	en org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass (AbstractJUnitTestClassProcessor.java:62)
	en org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass (SuiteTestClassProcessor.java:51)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch (ContextClassLoaderDispatch.java:33)
	en org.gradle.internal.dispatch.ProxyDispatchAdapter $ DispatchingInvocationHandler.invoke (ProxyDispatchAdapter.java:94)
	en com.sun.proxy. $ Proxy2.processTestClass (Fuente desconocida)
	en org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass (TestWorker.java:119)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:182)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:164)
	en org.gradle.internal.remote.internal.hub.MessageHub $ Handler.run (MessageHub.java:414)
	en org.gradle.internal.concurrent.ExecutorPolicy $ CatchAndRecordFailures.onExecute (ExecutorPolicy.java:64)
	en org.gradle.internal.concurrent.ManagedExecutorImpl $ 1.run (ManagedExecutorImpl.java:48)
	en java.base / java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
	en java.base / java.util.concurrent.ThreadPoolExecutor $ Worker.run (ThreadPoolExecutor.java:630)
	en org.gradle.internal.concurrent.ThreadFactoryImpl $ ManagedThreadRunnable.run (ThreadFactoryImpl.java:56)
	en java.base / java.lang.Thread.run (Thread.java:832)  ""

test_sticker_encryptDecryptEmpty
"" java.lang.NoClassDefFoundError: No se pudo inicializar la clase org.signal.client.internal.Native
	en org.whispersystems.libsignal.kdf.HKDF.deriveSecrets (HKDF.java:23)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.expandPackKey (AttachmentCipherTest.java:232)
	en org.whispersystems.signalservice.api.crypto.AttachmentCipherTest.test_sticker_encryptDecryptEmpty (AttachmentCipherTest.java:161)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en junit.framework.TestCase.runTest (TestCase.java:176)
	en junit.framework.TestCase.runBare (TestCase.java:141)
	en junit.framework.TestResult $ 1.protect (TestResult.java:122)
	en junit.framework.TestResult.runProtected (TestResult.java:142)
	en junit.framework.TestResult.run (TestResult.java:125)
	en junit.framework.TestCase.run (TestCase.java:129)
	en junit.framework.TestSuite.runTest (TestSuite.java:252)
	en junit.framework.TestSuite.run (TestSuite.java:247)
	en org.junit.internal.runners.JUnit38ClassRunner.run (JUnit38ClassRunner.java:86)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass (JUnitTestClassExecutor.java:110)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:58)
	en org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute (JUnitTestClassExecutor.java:38)
	en org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass (AbstractJUnitTestClassProcessor.java:62)
	en org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass (SuiteTestClassProcessor.java:51)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch (ContextClassLoaderDispatch.java:33)
	en org.gradle.internal.dispatch.ProxyDispatchAdapter $ DispatchingInvocationHandler.invoke (ProxyDispatchAdapter.java:94)
	en com.sun.proxy. $ Proxy2.processTestClass (Fuente desconocida)
	en org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass (TestWorker.java:119)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (método nativo)
	en java.base / jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
	en java.base / jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	en java.base / java.lang.reflect.Method.invoke (Method.java:564)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:36)
	en org.gradle.internal.dispatch.ReflectionDispatch.dispatch (ReflectionDispatch.java:24)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:182)
	en org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection $ DispatchWrapper.dispatch (MessageHubBackedObjectConnection.java:164)
	en org.gradle.internal.remote.internal.hub.MessageHub $ Handler.run (MessageHub.java:414)
	en org.gradle.internal.concurrent.ExecutorPolicy $ CatchAndRecordFailures.onExecute (ExecutorPolicy.java:64)
	en org.gradle.internal.concurrent.ManagedExecutorImpl $ 1.run (ManagedExecutorImpl.java:48)
	en java.base / java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
	en java.base / java.util.concurrent.ThreadPoolExecutor $ Worker.run (ThreadPoolExecutor.java:630)
	en org.gradle.internal.concurrent.ThreadFactoryImpl $ ManagedThreadRunnable.run (ThreadFactoryImpl.java:56)
	en java.base / java.lang.Thread.run (Thread.java:832)  ""

**Comment by Genis-Sage** [comment]
hey @Juanca24692 

as the Signal devs already mentioned to you last building problem

the Github issue tracker is reolved for bugs in the app

and not for problems about building it on your own
so please, go to the https://community.signalusers.org/ for help


also, I assume, you are not using the producible builds as descibed here:
https://github.com/signalapp/Signal-Android/tree/master/reproducible-builds
