### ISSUE TITLE
[5.0.4] Signal thinks its version is deprecated and stopped working + backup not working

### ISSUE THREAD

**Issue by Elbchillharmonie** [signalapp/Signal-Android#10287]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My wife just updated Signal to the latest version 5.0.4 after it complained that its outdated. However, even after updating to the latest version, Signal still thinks its deprecated! Signal will neither send nor receive any further messages.
I would try to reinstall the app, but the backup function is also not working. When tapping on "create backup", nothing happens. However, it wasn't activated before, so it might be that this is a separate issue. This is the worst case. I've no idea how to fix this so she can use Signal again.

### Steps to reproduce
- open Signal -> black banner on top appears that Signal stopped working because it is outdated
- tap on "update now"  -> store opens, but Signal is up-to-date
- Additional issue: tap "create backup" in the settings -> nothing happens

**Actual result:** Signal stopped receiving and sending messages +no backup possible
**Expected result:** Being able to send and receive messages + save backup

### Screenshots
N/A

### Device info
**Device:** Samsung Galaxy A3 (2017)
**Android version:** 8.0.0
**Signal version:** 5.0.4

### Link to debug log
https://debuglogs.org/0490d5e9744b9ef82f4d0eb1aaf238c7c33ec91cb6c69d4361fbf2d88fc9c888

**Comment by Sgn-32** [comment]
After a first look into the debuglog:
There are a lot of pending jobs for migration, even the GV2 (global) is `NOT_SUPPORTED` and the GV1 migration is `UNKNOWN`.
These jobs could block the backup job.

`id: JOB::6046a505-9934-4831-9381-e391aae4b2bd | factoryKey: LocalBackupJob | queueKey: __LOCAL_BACKUP__ | createTime: 1607876538381 | nextRunAttemptTime: 0 | runAttempt: 0 | maxAttempts: 3 | maxBackoff: 30000 | maxInstances: 1 | lifespan: -1 | isRunning: false | memoryOnly: false`

But maybe plug in the device to charge, could help to make a backup.
Normally a manually backup should always work.
The automatic backup only works when the device is charging.

When was Signal updated?
Some features uses flags, which refresh every 2 hours.

Can you also check the linked device(s) for updates?

**Comment by Elbchillharmonie** [comment]
Charging the device did not help.

Signal was updated today, approximately 3 hours ago. 

Signal is linked to a Windows PC, but the coupling is lost (again, this happens quite often). I can't link them again, Signal is complaining about the missing network connection.

**Comment by Sgn-32** [comment]
Probably only the developers can help here. But here are a few suggestions to try out:

- set the mobile device in airplane mode and wait
- update Signal4Desktop to the newest release 1.39.2 and wait

Send also a new debug log to check if anything has changed.

Note to others:
It appears that this job is blocking the other jobs.

`id: JOB::1b8b08ba-3209-4aa4-931e-9fd3e473c912 | factoryKey: DirectoryRefreshMigrationJob | queueKey: MIGRATION | createTime: 1607869245462 | nextRunAttemptTime: 1607877301515 | runAttempt: 224 | maxAttempts: -1 | maxBackoff: 30000 | maxInstances: 1 | lifespan: -1 | isRunning: false | memoryOnly: false`

**Comment by hhe** [comment]
Same problem on 4.79.3 and Android 9! I've been putting off the update nag because I feared something like this would happen, but today it became mandatory. And now I'm stuck in a loop even with the updated version.

Is QA a thing at Signal?

![20201213_094512](https://user-images.githubusercontent.com/417267/102019549-057d8e00-3d29-11eb-8af6-2834c86671b5.gif)

https://debuglogs.org/e5d2466b719f615d5e9d43d4b4cd89b1e45f32c2dd278a7b507f17227dc3706a

**Comment by Aufschlauer** [comment]
I've the same issue on Android 7.1.2: After updating from 4.71.5 to 4.79.3 the App still stats that the software is outdated.
A click on "Update now" shows the website with exact the installed version 4.79.3.

Any ideas?

Thanks.

**Comment by greyson-signal** [comment]
Working on a fix, we'll get something out shortly :+1:

**Comment by greyson-signal** [comment]
Should be fixed in 5.0.5 :+1:

**Comment by Elbchillharmonie** [comment]
I can confirm that it's working again. Thanks for the quick fix!
