### ISSUE TITLE
Edge lighting not working correctly with Signal's Messages on Galaxy S8

### ISSUE THREAD

**Issue by gab81** [signalapp/Signal-Android#10288]
Hi,

not going to write a regular bug report as it's a bit different.

So Samsung has Edge light notifications (that are super useful when the screen is off and all black), well it turns out that when you get a message in Signal, the screen edges do not light up as they should. With a phone / video call they do though. 

Samsung Messages / Telegram messages / Whatsapp messages do light up the edges correctly instead, as well as phone / video calls.

So since for phone calls they correctly light up, it shouldn't be hard to fix. Checked all options, notifications enabled, etc but does not work.

**Device info**
Device: Samsung S8
Android version: 9.0
Signal version: 4.79.3

thanks!

**Comment by Raine-Dawn** [comment]
I would like to say this is still an issue that I personally would enjoy having fixed

**Comment by wertzuz** [comment]
Why are signal messages not priority? 
@gab81 @cody-signal can you reopen

**Comment by gab81** [comment]
Please reopen (i do not have permission?) - i changed phone however
