### ISSUE TITLE
Country code 0 when opening Account Delete View

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#10296]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the Account Delete View, the country code input shows a 0 and the phone number input field is highlighted.

### Steps to reproduce
- open Signal settings -> Advanced -> Delete account

**Actual result:** Seeing a 0 in the country code inputbox
**Expected result:** The country code inputbox is empty at beginning

### Screenshots
![Screenshot_1608064002](https://user-images.githubusercontent.com/49990901/102269486-feb76c80-3f1c-11eb-8abf-1baf96e56419.png)

### Debug log

Also seeing this in the debug logs:

12-15 17:34:11.170  6532  6532 W PhoneNumberUtil: Invalid or missing region code (001) provided.
12-15 17:34:11.171  6532  6532 W PhoneNumberUtil: Invalid or missing region code (001) provided.
12-15 17:34:11.175  6532  6532 W PhoneNumberUtil: Invalid or missing region code (ZZ) provided.

**Comment by Sgn-32** [comment]
Yes, the 0 is there.

**Comment by Sgn-32** [comment]
Closed by mistake. Actually just wanted to write a normal comment.

**Comment by Sgn-32** [comment]
Yes, the 0 is there.

**Comment by alex-signal** [comment]
FYI there will be a fix out for this in `5.35`

**Comment by Sgn-32** [comment]
In 5.35.0
https://github.com/signalapp/Signal-Android/commit/b8bb2e234bf1bd8e1c4f7b7e31235c2bb7a0cff2
