### ISSUE TITLE
[RTL] Navbar masks the Signal media gallery UI button

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#10298]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the media gallery back button gets located to the top-right corner in RTL, it overlaps with the Android Navbar making it inaccessible, as shown in the screenshot.

### Steps to reproduce
- Open a photo inside Signal in landscape mode

**Actual result:** Back button is inaccessible
**Expected result:** Back button becomes accessible

### Screenshots
![image](https://user-images.githubusercontent.com/34171942/102276712-721ca680-3f3c-11eb-9bf0-4ad9c6dae61c.png)

### Device info

**Device:** All*
**Android version:** All*
**Signal version:** All*

**Comment by Xashyar** [comment]
Still reproducible.

**Comment by fumiakiy** [comment]
https://github.com/signalapp/Signal-Android/pull/10320 should fix it.
