### ISSUE TITLE
Typing Indicators triggers a switch from SMS to Signal messages to the receiver

### ISSUE THREAD

**Issue by jbleonesio** [signalapp/Signal-Android#10307]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When two phones using Signal are configured to exchange SMS, if the typing indicators are enabled on both side and the recipient start to type some text that automatically triggers a change to Signal messages. This behavior does not occur when typing indicators are disabled.

### Steps to reproduce
- Enable typing indicators on both participant side
- Configure phone 1 to send SMS (unencrypted) messages
- Start typing some text from phone 2

**Actual result:**
Phone 1 is now automatically configured to send Signal messages instead of SMS : this is dishonoring the wish of both recipients to continue exchanging SMS (unencrypted) messages when a data connection is not available.

**Expected result:**
Signal should keep phone 1 configured to send SMS instead of forcing Signal messages.

### Device info

**Device:** Samsung Galaxy S10e (phone 1) / Samsung Galaxy Core Prime (phone 2)
**Android version:** 10 (phone 1) / 5.1.1 (phone 2)
**Signal version:** 5.0.5 (both phones)

**Comment by greyson-signal** [comment]
The way Signal works is that the SMS setting is sticky... as long as the other party never sends a signal message. As soon as they send you a signal message, we'll switch back to sending signal messages. In this case, their phone is sending typing indicators because they're typing a signal message. I checked and we shouldn't be sending typing indicators if SMS is forced, so I'm assuming Phone 2 doesn't have SMS forced on the conversation?

**Comment by jbleonesio** [comment]
Both phones have forced SMS but typing indicators are sent anyway (from both sides, I just double checked).

**Comment by Tursko** [comment]
> The way Signal works is that the SMS setting is sticky... as long as the other party never sends a signal message. As soon as they send you a signal message, we'll switch back to sending signal messages. In this case, their phone is sending typing indicators because they're typing a signal message. I checked and we shouldn't be sending typing indicators if SMS is forced, so I'm assuming Phone 2 doesn't have SMS forced on the conversation?

I also encountered this, both using Signal Android with SMS forced.

**Comment by jbleonesio** [comment]
Typing indicators seems to be the only needed factor to be able to reproduce this behavior with 100% accuracy.

**Comment by Tursko** [comment]
> Typing indicators seems to be the only needed factor to be able to reproduce this behavior with 100% accuracy.

Yep certainly a bug. If forced SMS is enabled on both sides then typing indicator messages shouldn't be sent from either side.

**Comment by Sgn-32** [comment]
@greyson-signal isSmsForced() does not work as expected. Evaluates always to "false".
More details see PR #10987

**Comment by greyson-signal** [comment]
I think this issue should be fixed in a recent release, forget which one.

**Comment by Sgn-32** [comment]
Isn't fixed. Tested with two devices on 5.15.6.

**Comment by cody-signal** [comment]
Can you try with 5.16.3?

**Comment by Tursko** [comment]
I'm going to test this soon. Waiting for another user to update to 5.16.3.

**Comment by Tursko** [comment]
Just tested it on 5.16.3. Worked great. Thank yall!
