### ISSUE TITLE
Error sending MMS/image/attachment

### ISSUE THREAD

**Issue by vertigo220** [signalapp/Signal-Android#10309]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tried sending an image to a non-Signal user the other day and it kept failing. I kept manually retrying and it didn't work until I went outside. It's possible that, despite what my phone (Moto Z Play, Android 8.0) showed, the reception wasn't good enough to send it, since it wasn't using data, as it would be if sending to another Signal user. However, it would have been nice if a) it alerted me to the failure (I only knew because I checked), told me the reason, and retried on its own (or maybe it was but didn't give any indication). A while back, one of the updates claimed a big improvement to send failures and that they should be eliminated (or retried until success or something along those lines), but since then I've experienced issues like this multiple times.

### Steps to reproduce
- Send MMS (image, etc) to non-Signal user, probably while in a weak-signal area
- Watch as sending fails with no further action or indication of anything

**Actual result:** Image sending fails.
**Expected result:** Signal should keep trying (or if it is, show that) as well as give an indication as to why it failed

### Device info

**Device:** Moto Z Play
**Android version:** 8.0
**Signal version:** 5.0.5

### Link to debug log

This was a couple days ago and is already outside of the log timeframe. Considering I don't text a lot, it seems it doesn't keep a very long log. If there were at least an option to periodically append log entries to a file, so I could keep a long-term log on the SD card, I could have found it, as well as possibly entries for other issues I've had. Also, Signal crashed while viewing the log, ironically, and I was going to submit the log for that, but I'm not going to spend an hour scrolling through it on a small screen to ensure it doesn't contain any private info, especially when scrolling around causes the text to flutter, which I can see giving me a headache. And it can't be copied to view elsewhere and "editing" involves laboriously deleting one line at a time.

**Comment by jbaker6953** [comment]
Can confirm unable to send images to non-Signal users. Receive immediate "failed to send" error.

**Comment by caitsith01** [comment]
I also have this problem suddenly.  Did you ever get a solution?  I also get "failed to send" instantly when trying to send MMS images to non-Signal users.
