### ISSUE TITLE
Signal data is missing from native android encrypted backups.

### ISSUE THREAD

**Issue by jameshilliard** [signalapp/Signal-Android#10303]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal backups aren't included in normal encrypted android backups

### Steps to reproduce
- Create a full backup using a backup application such as seedvault which uses standard android backup API's with encryption
- Backup does not include/restore signal data

As of android 9 it should be possible to include signal data in backups when encrypted by setting `requireFlags="clientSideEncryption"`, see [here](https://developer.android.com/guide/topics/data/autobackup#define-device-conditions) for details. This should reduce the chance of data loss when backing up a phone while still preserving encryption.

**Comment by greyson-signal** [comment]
Best I can tell, all the backup stuff in the linked documentation is for putting things in a special Google Drive backup location. Not only do we not want to put data there, but it also limits you to 25mb anyway. On top of that, most of our data is encrypted with a key derived from the android keystore, so we'd have to think through those interactions. At the end of the day, Seedvault may also look at these tags, but that's not their primary use.

**Comment by jameshilliard** [comment]
> Best I can tell, all the backup stuff in the linked documentation is for putting things in a special Google Drive backup location. Not only do we not want to put data there, but it also limits you to 25mb anyway.

I'm pretty sure setting the require `clientSideEncryption` flag disables the normal Google Drive backups as they are not client side encryption.

The [docs](https://developer.android.com/reference/android/app/backup/BackupAgent#FLAG_CLIENT_SIDE_ENCRYPTION_ENABLED) say this so I think it should be safe:
> The transport has client-side encryption enabled. i.e., the user's backup has been encrypted with a key known only to the device, and not to the remote storage solution. Even if an attacker had root access to the remote storage provider they should not be able to decrypt the user's backup data.

Also for full backups/devicetodevice transfers there is no size limit for `full-backup-content` backups.

This looks to be roughly what a file based config for enabling encrypted backups/device transfers would look like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <!-- App data isn't included in user's backup
         unless client-side encryption is enabled. -->
    <include 
            domain="file" 
            path="."
            requireFlags=["clientSideEncryption" | "deviceToDeviceTransfer"] />
<full-backup-content>
```

> On top of that, most of our data is encrypted with a key derived from the android keystore, so we'd have to think through those interactions.

Yeah, you would need to use a custom [`BackupAgent`](https://developer.android.com/reference/android/app/backup/BackupAgent) I think to export the data in a manner similar to the normal signal backup process.
