### ISSUE TITLE
Request for comment: Recently discovered alleged vulnerability by Cellebrite

### ISSUE THREAD

**Issue by kiplingw** [signalapp/Signal-Android#10308]
As the maintainers are probably already well aware by now, articles like this [one](https://www.haaretz.com/israel-news/tech-news/.premium-israeli-spy-tech-firm-says-it-can-break-into-signal-app-previously-considered-safe-1.9368581) published 15 December, 2020, have been making rounds on the internet.

There will undoubtedly be questions from the Signal user community on whether the alleged vulnerability or vulnerabilities are real, and if so, when users might expect a patch. We all appreciate the hard work that you've done to try and make all of us safer.

**Comment by grandchild** [comment]
There have been multiple statements:
- There was another issue: #10277 with a comment from Greyson.
- There are multiple mentions in the forums (which would be a much better place for your request as well): https://community.signalusers.org/t/signal-media-coverage-please-post-articles-you-found-about-signal/1458/883
- Also a comment from Moxie on Twitter: https://twitter.com/moxie/status/1337434126186553345

tl;dr: When someone has your phone and root access, they can read your messages. But they could also do that in the app. So it's ~bullshit~ marketing.

Please search first.
