### ISSUE TITLE
Default to incognito

### ISSUE THREAD

**Issue by truelai** [signalapp/Signal-Android#10304]
Signal is mostly used by unsophisticated users and aimed at number of people who face nation state adversaries. Thus, default settings should be set to protect such users.

Most users would be unaware of the potential for data leaks due to use of third party keyboard. Signal provides a feature - "incognito keyboard" - as remediation. Due to users being unaware of the attack surface, I propose the following:

1. Enable Incognito Keyboard by default
2. If user changes keyboard, use a modal that informs the user
`"You are using a third party keyboard - to prevent data leakage to third parties, enable Incognito Keyboard in Privacy Settings"`

**Comment by greyson-signal** [comment]
Hi there, we use Github for tracking bugs. If you'd like to discuss features, please use the [forum](https://community.signalusers.org/). Thanks!
