### ISSUE TITLE
[Feature Request] Video Messaging

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#10311]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------
Can you please add support for video messaging by direct capture from the camera.
Thanks

**Comment by Nisc3d** [comment]
Feature Requests belong to the forum: https://community.signalusers.org/

**Comment by Genis-Sage** [comment]
@zero77
Also, Signal supports in-app video recording already for a long time, if your Android Version is new enough:
https://community.signalusers.org/t/signal-android-features-only-available-on-newer-android-versions/18153

Just open the camera and keep pressing on the button to record a video in-app

**Comment by zero77** [comment]
Thanks @Genis-Sage 
I had no idea that was available, perhaps it needs better in app documentation.

**Comment by makkussu** [comment]
It looks like in-app video recording works on Android 8 and newer only. Any possibility of adding Android 7(API 24) support?

**Comment by Genis-Sage** [comment]
@zero77
perhaps you can place a similar feature request like this one:
https://community.signalusers.org/t/add-tooltips-to-controls/9245

@makkussu 
this would only be possibly if Signal devs brake the principle to never save unencrypted data to the disk
only newer Android versions offer APIs which enable the Signal to record videos in-app without saviong it unencrypted

**Comment by makkussu** [comment]
@Genis-Sage 
Thank you for the reply! Did not know that starting from Android 8 in-app records can be saved encrypted. This does make sense now.
