### ISSUE TITLE
Can’t verify APK

### ISSUE THREAD

**Issue by scytho** [signalapp/Signal-Android#10316]
I downloaded version 5.0.5 a few days ago and 5.0.8 today. I followed the instructions the download page links to, but I am not able to verify either of the APKs:

```bash
$: apksigner verify --print-certs Signal-Android-website-prod-universal-release-5.0.8.apk 
DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: Malformed additional attribute #1
WARNING: APK Signature Scheme v2 signer #1: Unknown signature algorithm: 0x421
```

I cannot open them with Engrampa. It gives an error followed by a lot of output. I cannot copy the entire text for some reason (looks like it lists all files inside the APK). This is the beginning of the error message:

```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=***.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs ***)

Scanning the drive for archives:
1 file, 78559661 bytes (75 MiB)

Listing archive: …/Signal-Android-website-prod-universal-release-5.0.8.apk

--
Path = …/Signal-Android-website-prod-universal-release-5.0.8.apk
Type = zip
ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
Physical Size = 78230790
Tail Size = 328871

[…]
```

Are the APKs corrupted?

**Comment by richardddd98** [comment]
From https://signal.org/android/apk I just downloaded a file (version 5.0.8) with SHA2-256 51b60388f7166dbd5782b254e51951f111ccc9e46798fe881ba14038a70d6807. Can you tell me if the hash of the file you downloaded matches mine?

**Comment by scytho** [comment]
Yes, it’s the same. But how can I verify the SHA256 fingerprint given on the download page?

**Comment by greyson-signal** [comment]
You're probably using an old version of apksigner. I just tested with apksigner from buildtools `30.0.2` and all works as expected.
