### ISSUE TITLE
Recording voice messages is being aborted on app switch

### ISSUE THREAD

**Issue by genodeftest** [signalapp/Signal-Android#10319]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- open Signal app
- open a chat (does not matter whether I open a 1-on-1, old style or new style group chat)
- start recording a voice message
- leave the Signal app using Android's "home" button or the square button used to open the app overview
- go back to the Signal app (e.g. by using the square button)

**Actual result:** Recording the voice message has stopped without warning. The already recorded part of the voice message is lost. There is no indication that the voice message is still recording. There is no indication that the voice message recording has even started. There is no way to get the already recorded message back.
**Expected result:** Signal should continue to record the voice message when switching apps. It should display an overlay over the app just like the native phone app does when being in a call. If this is not possible, it should try to warn the user *before* aborting recording the voice message. If that is not possible, it should at least display something like _recording voice message was interrupted by switching apps_ to give a hint why the recording has stopped.
**Reproducible:** always, on different devices

### Screenshots
There is no indication on the aborted voice message recording whatsoever, so there are no useful screenshots to make.

### Device info

**Device:** HMD Global Nokia 5
**Android version:** 9 patchlevel 2020-10-01
**Signal version:** 5.0.5 (has been present in the 4.x cycle for a long time too, i.e. this is no recent regression)

### Link to debug log
https://debuglogs.org/819292680173d54f69040d97be2c89f1331c84ad2a09da4a819c9f6ae3e7c5f5

**Comment by JohnVeness** [comment]
I have noticed this too. You can also test it on "note to self", so no need to actually send a message to someone else.

As a workaround, I record messages in a separate voice recorder app (which doesn't seem to mind app switching) and then attach the audio file to the chat later. But this isn't very compatible with Signal's privacy-minded ways, as I would have to delete the audio file afterwards, and trust the voice recorder app, and so on.

**Comment by SebastianReitzner** [comment]
Similarly when you accidentally lock the screen, the message is just gone.
WhatsApp behaves in a way that it simply stops the recording and keeps it as previous input similar to when you type a message without sending and return to the chat later.

**Comment by JohnVeness** [comment]
Yeah, saving the recording so far as a draft would be a good minimal fix, rather than (as currently) discarding it. And a draft would be preferable, I think, than sending what's been recorded so far on one of these interrupting events, in case the user wasn't ready to send yet.

**Comment by Gladcraft** [comment]
I was successfully convincing my team to switch from Voxer to Signal, but this is a deal breaker.  We were leaving Voxer in part because of Voxer's glitches with lost voice messages (under different circumstances).  This problem with voice messages dissapear with an incoming call, other app switching, or turning off the screen is a deal breaker.  It puts Signal on a par with the inconvenience of Voxer.  I like Signal's platform and philosophy better, but can't justify the switch with this issue unaddressed.

**Comment by major-mayer** [comment]
Seems like the voice message get's saved as a draft now when you lock your phone or switch to another app. 
I think this can be closed as "good enough".

**Comment by genodeftest** [comment]
You're right. Thanks for the update!

Many thanks to the developers for fixing this issue!
