### ISSUE TITLE
data folder grew too large - allow choosing storage for media and quality of photos

### ISSUE THREAD

**Issue by aleqx** [signalapp/Signal-Android#10322]
Signal stores all media (photos, movies, etc) on the same storage as the app and there is no setting to store them elsewhere. I just discovered that SIgnal is the main culprit for my phone's internal storage running out of space.

I don't want to delete/detach old media from messages (kind of defeats the purpose for me as friends and family switched to Signal from Whatsapp).

Can we please get an option to store media elsewhere on the device, particularly external storage?

Can we also get an option to resize/resample photos that we can use on the fly? Everyone now attaches 30+ MB photos (grr). Whatsapp doesn't give any choice and butchers all photo quality when uploading. An option would be good - would be great to have it when attaching a photo. Aquamail did a great job - when you attach a photo it brings 4 choices you can tap: original (30Mb), high (10MB), medium (2MB), low (400 KB) ... it tells you the file sizes too, which is nice.

**Comment by jedie** [comment]
Think there should be a default setting like "let 10% storage free"  that will delete old entries

**Comment by richardddd98** [comment]
> Think there should be a default setting like "let 10% storage free" that will delete old entries

I don't think it would be a safe default, but it would be nice to have the option though that you have to manually enable.

Storing media on an external storage is less secure, since other apps may have access to it and the SD card might even be removed, so this shouldn't be the default too. You actually compromise security.

**Comment by aleqx** [comment]
I don't want to delete any of it, so defaulting to delete old stuff defeats the whole purpose for me. Storing anywhere can be encrypted in the same way. None of these have to be defaults, I just want the option to do it. Inform the user of any security/privacy compromises but let them make the choice, don't make it for them.

**Comment by Genis-Sage** [comment]
Hey @aleqx
This is definitely a feature request, and the Github issue tracker is reserved for bugs

So please got to https://community.signalusers.org/

**Comment by GitHubbet** [comment]
Just an advanced Computing user - not a developer

What about manual exporting to 'External Storage' but filtering whatever it could compromise security?
I do delete everything once in a while anyway, but a feature to choose what to keep, would be nice.

Personally if I wish to keep a photo, I just save it manually, then I know I can delete the whole lot... at present it is what I do.

**Comment by GitHubbet** [comment]
Is keepass totally secure? If so, the way they encrypt might be an idea.

**Comment by richardddd98** [comment]
@GitHubbet It's not only about confidentiality, it's also about integrity and protection from deletion. If data is stored in an external storage, an app with access to it could delete all your media or damage them. You would lose the guarantee that other apps won't be able to tamper with your Signal data, as it is now. It has drawbacks, so the best is to store your data in a non shared portion of memory. It can be good for users who recognize the risks and don't care to move their data, but I don't think it's good for Signal to have this behavior as the default. Right now, when you store your data inside Signal you're sure other apps won't be able to do absolute anything to any of it (of course if you don't set an app as device administrator with factory reset privilege).

@aleqx The default as far as I remember is to keep all your data (I might be wrong), so the deletion of your data is solely at your discretion. You have to manually delete your messages or to enable the limit of number of messages in Signal settings.

**Comment by aleqx** [comment]
Not sure why folks in here are arguing about defaults or changing whatever the defaults are. That's besides the point. The point was to give an option to move media to a different storage (warn the user about the risks if you want to, etc, but don't make the choice for them).

@Genis-Sage Will try to post in the community forum.
