### ISSUE TITLE
Unable to restore backups following a fresh install

### ISSUE THREAD

**Issue by eminemesis** [signalapp/Signal-Android#10323]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to restore backup. The option to restore backup doesn't appear.

I've tried reinstalling multiple times, looked every nook and corner to be sure that I'm not overlooking anything. FAQs page mentions two ways to restore:
1. Manually press restore and select the backup file
2. Accept the permissions and let the app recognize the backup

Note:
Copied the backup to the internal and external storages
Tried restarting the device 
Verified that the backup file format matches "signal-year-month-date-time.backup"
Tried providing permissions in advance to starting the app for the first time

### Steps to reproduce
- move backup file on to the device
- install the application
- open the application and click continue
- provide prompted permissions
- proceeds to phone number (should've received the restore option by now)
- verifies the number
- verifies previous pin linked to the number
- profile setup page
- home page

**Actual result:** Restore backup option doesn't appear anywhere during the above steps
**Expected result:** A Restore option should've been made available during the setup process

### Screenshots
![1_Terms](https://user-images.githubusercontent.com/68422418/102715740-82969d80-42fd-11eb-84d0-73f3169f9875.jpg)
![2_Permissions](https://user-images.githubusercontent.com/68422418/102715741-83c7ca80-42fd-11eb-8943-2cf47c758688.jpg)
![3_Permissions_Contacts](https://user-images.githubusercontent.com/68422418/102715742-83c7ca80-42fd-11eb-90fe-8bb0e0f1a989.jpg)
![4_Permissions_Files](https://user-images.githubusercontent.com/68422418/102715743-84606100-42fd-11eb-9f9b-9456114a0ede.jpg)
![5_Permissions_Calls](https://user-images.githubusercontent.com/68422418/102715745-84f8f780-42fd-11eb-958a-cab566cc8959.jpg)
![6_Phone_Number](https://user-images.githubusercontent.com/68422418/102715746-84f8f780-42fd-11eb-85c2-8f194a888236.jpg)
![7_verification_code](https://user-images.githubusercontent.com/68422418/102715747-85918e00-42fd-11eb-9609-9a6f9497a0a8.jpg)
![8_Pin](https://user-images.githubusercontent.com/68422418/102715748-862a2480-42fd-11eb-9183-b8247e137911.jpg)
![9_Profile_Setup](https://user-images.githubusercontent.com/68422418/102715749-862a2480-42fd-11eb-944c-18cc82d37a0e.png)
![10_Home](https://user-images.githubusercontent.com/68422418/102715752-86c2bb00-42fd-11eb-815e-13db0ecd53ed.jpg)

### Device info
**Device:** Asus Zenfone Max Pro M1 (X00TD)
**Android version:** 9.0
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/3d34ef8f5bc8ef24c30f16b628d7833eccba8fb9615e779118565a8664f08035

**Comment by eminemesis** [comment]
Edit: Upon inspecting the debug log, I've found that the backup was copied to the home directory instead of Signal/Backups. Migrating the file fixed the issue.

**Comment by Genis-Sage** [comment]
Hey @eminemesis
What is the full path of the backup file on your new phone?
