### ISSUE TITLE
Sticker suggestion box remains after sending sticker through keyboard

### ISSUE THREAD

**Issue by kitchenstickersignalissue** [signalapp/Signal-Android#10325]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using Gboard (default android keyboard for Pixel phones) typing an emoji, and selecting a sticker from the keyboard (not the Signal sticker), the box of suggested Signal stickers remains despite no draft text in the "Signal message" field. This occurs when using the "Emoji Kitchen" stickers (https://blog.google/products/android/emoji-kitchen-new-mashups-mixing-experience/) in Gboard, and perhaps other stickers as well.

### Steps to reproduce
- Use latest version of Gboard for android
- In Gboard preferences, enable "Emoji browsing suggestions"
- In Signal, download one or more sticker packs
- Type an emoji that corresponds to a sticker in one of the Signal sticker packs, causing the sticker suggestion box to appear
- In the keyboard, select an Emoji mashup/emoji kitchen sticker corresponding to that emoji (not the sticker from the Signal sticker pack)

**Actual result:** The sticker sends, message window clears but the box of suggested Signal stickers remains
**Expected result:** The box of suggested Signal stickers should be dismissed

### Screenshots

![emoji 1](https://user-images.githubusercontent.com/76405812/102722059-324f1980-42c4-11eb-9f8f-fa83e718f7e9.png)
![emoji 2](https://user-images.githubusercontent.com/76405812/102722067-4430bc80-42c4-11eb-89ae-a63ab44dc7a6.png)
![emoji 3](https://user-images.githubusercontent.com/76405812/102722075-4bf06100-42c4-11eb-829c-d548f843f198.png)
![emoji 4](https://user-images.githubusercontent.com/76405812/102722080-501c7e80-42c4-11eb-998a-9461162a52ad.png)

### Device info

**Device:** Google Pixel 4 XL
**Android version:** 11
**Signal version:** 5.0.8

**Comment by valposv** [comment]
Might be an issue with Gboard itself, checked the feature in several other messengers, for me the problem is that it doesn't clear the emojis pasted in the input field after you click on stickers and send them. Works alright everywhere on Android 10 though
