### ISSUE TITLE
I read about the Cellebrite blogpost and now I'm wondering if...

### ISSUE THREAD

**Issue by 0x747972** [signalapp/Signal-Android#10337]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

Ok, this isn't really a bug report or anything. Just asking this because I'm curious...

(Disclaimer: I'm no expert... So this might be a stupid and ignorant question. Also it's more of a general questions about cryptography.)

I read about the recent Cellebrite blogpost and I know that signal's threatmodel doesn't really include protecting messages (or attachments) on an unlocked device.

Now I'm wondering, just out of curiosity, what the consequences would be if I hypothetically forked the signal client and made some small modifications, so that it uses HmacSHA512 instead of HmacSHA256, xored the first and last 32 bytes of this hash and used this as the key for attachments?
Could similar shenanigans be pulled with the key material that is stored in the Android Keystore? I don't really understand this API, but I understood that one doesn't get access to the key directly. So simply just xoring the key with some static string like "ACAB" wouldn't be possible, right?

I know this doesn't add real security, but would it in someway impede the strength of the cryptography involved? (Mainly asking about the change from HmacSHA256 to HmacSHA512...)

Thanks,

ryt

**Comment by Genis-Sage** [comment]
Hey @0x747972

As you seem to have read the template, please also follow it and ask your question on the community forum.

You should only open a github issue, if all 4 check boxes are true.

**Comment by 0x747972** [comment]
Ah, i didn't even know this existed...
