### ISSUE TITLE
Cannot install Signal app on Android 5.1.1 (LMY47V) image

### ISSUE THREAD

**Issue by kookuukookuu** [signalapp/Signal-Android#10343]
Cannot install Signal app on Android 5.1.1 (LMY47V) image (Nexus 7 tablet)

I have no other option of using other versions of Android, hardware costs money. This hardware works fine. Not everybody can throw money at new hardware all the time. 

Signal App on Android is catering for the rich by not being installable on hardware people already have, effectively forcing hardware upgrades onto people.

If I am unable to install it on my tablet, I am unable to use the app and have no other option but to use insecure dystopian WhatsApp or something less secure (and encourage others to do so to stay in touch with me), how can I recommend an app that I cannot install and run myself?

I thought Android compatibility library in the SDK was to be backwards compatible. There is no later images than 5.1.1 available for the Nexus 7 tablet (if there was I could at least run later versions but I cannot). Buying new hardware to run your app is not an option.

**Comment by Genis-Sage** [comment]
Hey @kookuukookuu

Signal devs reserved Github issue tracker for bugs

What you describe is a discussion topic or feature request
Please go to the forum:
https://community.signalusers.org/t/android-tablet-support/5590/38

And for completeness:
Your issue has nothing to do with Android version, but with using a tablet, while Signal is only made available for phones.

Workaournd:
Simply download and install the website apk:
https://signal.org/android/apk/

And just a tip:
Before putting so much effort in a comment, you should simply habe searched, how to install Signal on a tablet

**Comment by kookuukookuu** [comment]
Fine, No Signal app then
