### ISSUE TITLE
APKSIGNER not working, can you OpenPGP sign the APK please?

### ISSUE THREAD

**Issue by kookuukookuu** [signalapp/Signal-Android#10346]
apksigner not working (and not everybody may have the Android SDK tools installed), can you OpenPGP sign the APK please so we can use GPG on Linux to verify the APK after downloading to a secure area?

I tried the verification on the web APK download, apksigner spews out lots of errors, I would prefer to use GPG and my keyring to verify the APK post download as this is the typical method we use on Linux, instead of me messing with apksigner, let me just use gpg

Not all users will have the Android SDK installed, so this makes it much easier for many people by giving the option to verify using OpenPGP also.

**Comment by Genis-Sage** [comment]
Hey @kookuukookuu

Again, as your last issue

Openpgp is a feature request, so please go to the forum:
https://community.signalusers.org/latest

Regarding the apksigner bug:
See  #10316 , perhaps it's the same issue

And again some tips:
1) Keep your issues short and factual.
your "not everyone" style does not help anyone

2) Also, there is an issue template which should be filled out

And just fyi:
I am no Signal employee or anything. Just a committed user.

**Comment by kookuukookuu** [comment]
I would prefer to not have to depend on having Android tools installed in order to verify a download.

**Comment by kookuukookuu** [comment]
I also prefer not to have to create another account on yet another system to file a feature request, dear god this tiring, I have to keep making throw away accounts on your systems just to file something that can be done here
