### ISSUE TITLE
Since introducing charging event constraint backup runs erratically

### ISSUE THREAD

**Issue by CarlosCastaneda** [signalapp/Signal-Android#10341]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Before  the introduction of the charge event constraint backup used to run very reliably. Because of memory shortage due to signals backup size I introduced a „move to external storage feature“ (with automate) to be able to store and keep even older messages.

Now I noticed that the backup job only starts to run if and only if Wien the time frame has been passed (that‘s as it used to be) and additionally (and that‘s the new constraint) when the mobile phone is being plugged for charging, without respect to the current charging state nor how long the time frame constraint has been fullfilled. Even if the device is being unplugged immediately the backup job continues to run which makes the new constraint absurd.

Furthermore I noticed that there are 2 backups written within a shorter period of another time frame window.

### Steps to reproduce
- wait if time frame window has been passed
- plug device for charging, backup will immediately
- wait some time period for second backup (about 1,5-2h)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I‘d expect to run backup even if it‘s Not nessecarilly plugged for charging, rather take schedule, intervall and charging capacity into consideration, also best if configurable by user!

### Device info

**Device:** Motorola moto e4
**Android version:** 7.1.1
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/d5c7ea609f3dd0a0b8a5c0d787a720d8ddc6d11277b9de747360a6ecbcb50259

**Comment by Genis-Sage** [comment]
hey @CarlosCastaneda 

I would see most of your issue as a feature request, not as a bug.
(time AND charging constraints together is the logic for which Signal devs decided at the moment)
so you should look here: https://community.signalusers.org/t/allow-users-to-configure-when-backups-are-taken-or-perform-backups-only-manually/2475

the only thing I see as a bug, is that two backups were created in 2 hours

**Comment by greyson-signal** [comment]
We made this decision because backups were frequently happening at bad times for users. We use the charging constraint as an indicator that the phone is more likely to be at rest. We may look into more options in the future, but we only track bugs on github. Thanks!
