### ISSUE TITLE
ZKParam InvalidInputException: length supplied is 159 expected 161

### ISSUE THREAD

**Issue by boggerapp** [signalapp/Signal-Android#10354]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes during startup with error: InvalidInputException. Length of array supplied was 159 expected 161

```
-- Gradle config--------------------------------------------------
    implementation 'org.signal:zkgroup-android:0.7.0'
...
buildConfigField "String", "ZKGROUP_SERVER_PUBLIC_PARAMS", "\"AAyh7oY0uLmhMY2cImGPAnUQyPNuAgJJsW8cqtjdqNAYQkK1CaSpijFQxZ1B+o482AhzLb98aPT5qK2WTe58oTPIB9IDZ8SyaIv2v0ThcgHSa1Jg2chLSQxK11LUDwadTYRwi1Giu9yq65N3NnVLfjk7PLilgmFl/4EmFRtqHtMlyAd/Z3fF0JbEl8VRwKKpZi3Qa8UfXGBksYlUj7oCUGo\""
--------------------------------------------------------------------
```

I also tried appending "=" to the end of ZKGROUP_SERVER_PUBLIC_PARAMS but no difference.

### Steps to reproduce
- Just start android app

**Actual result:** App crashes with error (InvalidInputException)
**Expected result:** Start app and proceed to Phone number verification screen

### Screenshots

![Screenshot_69](https://user-images.githubusercontent.com/48287153/103670006-56c01c80-4f79-11eb-9cd8-d4e2db778f71.jpg)

### Device info

**Device:** Oukitel C12 Pro (Oreo)
**Signal Android version:** v5.0.3
**Signal Server version:** v3.2.1

**Comment by alan-signal** [comment]
Please use the community forum for development help https://community.signalusers.org/

I would have expected the equals sign to have resolved, make sure it's before the `\`: `=\""`.
