### ISSUE TITLE
Changing pin does not work correctly

### ISSUE THREAD

**Issue by kbirger** [signalapp/Signal-Android#10353]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I changed my pin. Verify PIN works correctly because it expects the new pin. Unlocking with pin (skip biometrics) still requires me to enter old pin 😭.

I suspect that removing the pin altogether from the advanced settings would resolve the issue, but I have avoided doing so because I would like to do what I can to get this fixed. 

### Steps to reproduce
- PIN is disabled
- set a pin
- lock signal and unlock it with the pin (sanity check)
- go and change your pin
- close signal, or whatever it takes to get Verify PIN to pop up
- Enter in new pin. It should accept it
- Lock Signal
- Attempt to unlock with new PIN 

**Actual result:** New PIN does not unlock signal, but old pin does
**Expected result:** Old PIN should not unlock signal; new PIN should.

### Device info

**Device:** Google Pixel 4
**Android version:** Android 11 RQ1A.201205.008
**Signal version:** 5.0.8 (but originally started happening on an older version. not sure which)

### Link to debug log
https://debuglogs.org/03099f5db89e2cd48ff99e42452cb162e39f447dfcacb364bc9da4eb6afb7ac7
I'm not sure if this log is relevant because whatever issue occurred has most likely occurred a long time ago, once, and it has left my Signal in a bad state.

This one may be more interesting. I changed the pin again and attempted to unlock using new pin, but only the first (original) pin works:
https://debuglogs.org/f328051085729c7054346c0c7048456b9b52f39e87d52f5df53679bf4f4995a3

**Comment by greyson-signal** [comment]
One point of confusion I'd like to clear up is the difference between the Signal PIN (set in Settings > Privacy > Change your PIN) and the screenlock PIN.

These are two different PINs -- the Signal PIN is set in our app, and used as part of our [Secure Value Recovery](https://signal.org/blog/secure-value-recovery/) system. The screenlock is just the same PIN you use to unlock your phone, and is set in your system settings.

Does that clear up anything?

**Comment by kbirger** [comment]
Yup. Sorry for the misunderstanding. Thanks @greyson-signal

**Comment by hubyhuby** [comment]
On TOP of that users do NOT whant a PIN code. Its the first reason WHatsapp had success.  PLease just copy whatsapp. Remove this PIn code. I have at least already two persons removing Signal for that reason,  I had a hard time convincing them and it is all lost.
After 1 month here is the typical message from your friends : 
![image](https://user-images.githubusercontent.com/26340942/218016372-f0d976b2-c3f1-4175-9784-a14e12b4be41.png)
ANd back to whatsapp :(

**Comment by bme13** [comment]
Why didn't you suggested to either disable the reminder or disable the pin all together? 
settings->account-> pin reminders or
settings->account-> advanced PIN settings
This is what I've done. No complains anymore ;-)
