### ISSUE TITLE
Add Redmi Note 3 and Redmi note 5 to AEC blacklist

### ISSUE THREAD

**Issue by rawlife56** [signalapp/Signal-Android#10351]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Please add Redmi note 3 and Redmi Note 5 to AEC blackilist according to [ #7635](https://github.com/signalapp/Signal-Android/issues/7635)

 ro.product.model=Redmi Note 3
 ro.product.model=Redmi Note 5

**Actual result:** Echo of my own voice
**Expected result:** Clean audio in voice/video call

### Devices info

**Device:** Xiaomi Redmi Note 3 (Snapdragon), Xiaomi Redmi Note 5
**Android version:** 9, 10
**Signal version:** 5.0.8

**Comment by greyson-signal** [comment]
To be clear, this represents the *receiving* device, correct? If you're using device A to talk to device B, and you  hear an echo on A, that means the problem is with device B. Just wanted to clarify before adding anything to a blacklist.

**Comment by rawlife56** [comment]
> To be clear, this represents the _receiving_ device, correct? If you're using device A to talk to device B, and you hear an echo on A, that means the problem is with device B. Just wanted to clarify before adding anything to a blacklist.

Yes, exactly!
When I make a call to these devices, I hear an echo of my own voice on my device which has good AEC implementation. They don't hear any echo on their end. Well, that's exactly what you described but just reassuring.

**Comment by greyson-signal** [comment]
Hi there, these we added in 5.1.x, thanks!

**Comment by isestag** [comment]
Hi there. Thanks for adding our devices. I'm using 5.1.9 on the Redmi Note 5, and callers are still getting an echo. I've tried clearing Signal's cache and resetting the phone. Any other ideas?

**Comment by rawlife56** [comment]
Hey @greyson-signal 

I was about to mention the same but couldn't find time to login. As @isestag already mentioned, both the devices are still causing echo on 5.2.3
Are you sure they were added to blacklist ?

**Comment by mateusz-kolecki** [comment]
Same for me, I have Redmi Note 5 and people calling to me complain that they hear their own voice.
