### ISSUE TITLE
Can't download Picture

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#10352]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A picture sent to me doesn't download from the server. The loading circle keeps spinning.

### Steps to reproduce
- go into chat with a new picture

**Actual result:** The picture doesn't load
**Expected result:** The picture should load from the server

### Device info
**Device:** Asus Zenfone 6
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/440b2de7aa5bb0a851853a75497fe6e529b8fb77ab3fd5143f544325d9994dc4

**Comment by alan-signal** [comment]
What Signal client did the sender use? Android/iOS/desktop?

**Comment by Nisc3d** [comment]
Android 10 on a Nokia 6.1 with the latest Signal Version from Google Play.

**Comment by Nisc3d** [comment]
Didn't happen again. I will close it.
