### ISSUE TITLE
circular-progress-button:library:1.1.3-S2 and build Failed

### ISSUE THREAD

**Issue by wuxuan2811** [signalapp/Signal-Android#10356]
### Bug description
In app/build.gradle,circular-progress-button:library:1.1.3-S2 is not valid, so I change to circular-progress-button:library:1.1.3.
However, when Run app, I have error:
      Caused by: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class 
                        com.dd.CircularProgressButton
     Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class com.dd.CircularProgressButton

### Steps to reproduce
- modify dependencies ",circular-progress-button:library:1.1.3-S2"
- Run app

### Screenshots

![微信图片_20210106103914](https://user-images.githubusercontent.com/24578985/103722676-70aa3f80-500b-11eb-82e9-1ce8f1ca3b21.png)

**Comment by wuxuan2811** [comment]
If build Signal through "gradlew build", build falied with an exception
![image](https://user-images.githubusercontent.com/24578985/103745404-5cca0200-503a-11eb-8490-be807fe7ae76.png)

**Comment by bme13** [comment]
Hi @wuxuan2811,
What do you mean by circular-progress-button:library:1.1.3-S2 is not valid? I also build Signal but don't run into that issue, though I build it from AndroidStudio.
Anyway the github issue tracker is not for development support. I suggest you post this on the community forum. https://community.signalusers.org. Thanks.

**Comment by alan-signal** [comment]
You shouldn't need to change anything to get it to build, so yes I'd be interested in hearing more about the original problem, "is not valid".

**Comment by wuxuan2811** [comment]
![image](https://user-images.githubusercontent.com/24578985/103965678-39699900-5199-11eb-9c3c-b1a0de70f53f.png)
I have check the library, the latest version is 1.1.3
![image](https://user-images.githubusercontent.com/24578985/103965733-5c944880-5199-11eb-86fa-0ed1a7cf7e1b.png)
@alan-signal

**Comment by wuxuan2811** [comment]
Because build exception like this
![image](https://user-images.githubusercontent.com/24578985/103966811-97977b80-519b-11eb-9f50-9c65a4bfcba3.png)
Besides, I need modify the /Signal-Android/build.gradle
![image](https://user-images.githubusercontent.com/24578985/103966011-f3610500-5199-11eb-8064-0eb963749095.png)
