### ISSUE TITLE
LED notification doesn't work

### ISSUE THREAD

**Issue by donjoe0** [signalapp/Signal-Android#1036]
I had the LED set to blue and normal blinking pattern in TextSecure v2.0.3 and upon receiving messages from service "numbers" (like my mobile carrier and my bank) I saw no LED notification whatsoever. I checked this with the screen still off because the Motorola Droid 3 only lights the notification LED when the screen is off, but there was no LED action (though the ringtone and vibration had worked just fine).

**Comment by rhodey** [comment]
@donjoe0 @Martuh if you could provide a debug log documenting this behavior that'd be a great help, thanks!

**Comment by donjoe0** [comment]
I'm not using the Droid 3 anymore and my Asus Padfone 2 has no notification LED.

**Comment by jimbo0848** [comment]
https://gist.github.com/557de22561ccae235218

**Comment by agrajaghh** [comment]
@jimbo0848 there is nothing in that log, what are you experiencing?

**Comment by jimbo0848** [comment]
Feb 24, 07:20

I have a LGG3 D850 AT&T the Led notification is not working at all. I tried selecting all colors to see if that was the problem. Nothing seem to work to get Led notifications to work. Really need those so when phone is in silent mode you are able to see that you received a text or incoming call. Absolutely love the program! Would like to see this fixed in a future update. Believe I am not complaining one bit but I am a believer in if you don't know it is broken than how can you fix it. Keep up the great work!!!!!! Thank you for keeping private private!!!!

**Comment by 2-4601** [comment]
#5189 2016/02/07:
>The LED used to work fine with text messages prior to the installation of Signal. It still works correctly with WhatsApp. Signal seems to be the only app where the LED is malfunctioning.
>
>Here's my debug log : https://gist.github.com/anonymous/a4338e57a0ee8ddfc0a3

**Comment by p4nci** [comment]
@devs
maybe similar issue(???):
https://github.com/SMSSecure/SMSSecure/commit/d1afcf1e08ee3e1d9caad078c729255e6ca067bb

**Comment by Pazu** [comment]
I reported this same issue a few months ago using an older version of Signal on my Sony Ericsson Xperia Mini ST15i, but at some point the issue was resolved. I'm not sure when. Now, I'm using Signal v3.20.4 and the notification LED works as expected.

**Comment by FeuRenard** [comment]
https://github.com/WhisperSystems/Signal-Android/commit/bd2fc82360c2a2fbd5e92194074104d465b8bf19 possibly resolved this issue.

**Comment by ajvpb** [comment]
Same problem as above. The led on the front of the phone does not blink to notify of a text message. Audio notification works fine, and I've tried changing the color if the notification with no luck. Phone is an lg lancet, running android 5.5.1. Thank you


https://gist.github.com/f59c160f1d28967a24e9665e3a765814

**Comment by k1rah** [comment]
I am also experiencing the LED not working. I'm on a Cubot X9 with Android 4.4.4. My LED by default displays either red, green, or blue. I have notifications set to blue.

**Comment by Martuh** [comment]
2016-11-09 18:57 GMT+01:00 k1rah <notifications@github.com>:
>
> I am also experiencing the LED not working. I'm on a Cubot X9 with Android 4.4.4. My LED by default displays either red, green, or blue. I have notifications set to blue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


Hello,
could You please unsubscribe my mail. I changed my phone few months
ago, so this matter does not concern me anymore.

Thanks!

-- 
Martuh
