### ISSUE TITLE
Disappearing Messages are visible in reply messages

### ISSUE THREAD

**Issue by joda01** [signalapp/Signal-Android#10363]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When replying to message, a copy of the message is added to the reply message. This mechanism can be used to bypass the disappearing message function. The copy of the message is also available when the original message has been disappeared.

### Steps to reproduce
- Enable disappearing messages
- Send a disappearing messages
- Disable disappearing messages
- Reply to the disappearing message.

**Actual result:**  The original message will disappear as expected but the message can still be read i the reply message.
**Expected result:** I would expect that also the message text in the reply message will disappear.

### Screenshots
![2021-01-07 21-04-28](https://user-images.githubusercontent.com/46405460/103939508-25d41900-512c-11eb-877d-eae0adf73edf.jpeg)

### Device info
**Device:** iPhone SE
**Signal version:** 5.0.3.0

**Comment by Genis-Sage** [comment]
hey @joda01 
as you really just make a copy of a message, this is expected
it's nothing else than copy & pasting the content of the message with some extra styling
same goes for forwarding messages

also, your issue is a duplicate of #9229

**Comment by joda01** [comment]
Seems to be a duplicate of #9142
