### ISSUE TITLE
Share intent should use setClipData(uri) for content:// uris

### ISSUE THREAD

**Issue by rejhgadellaa** [signalapp/Signal-Android#10369]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Share intent should use setClipData(uri) for content:// uris

While I can't be sure, I suspect that Signal is relying on the legacy EXTRA_STREAM to supply a content:// uri to the destination app.

Instead of only setting Intent.EXTRA_STREAM...

```
Intent intent = new Intent();
intent.putExtra(Intent.EXTRA_STREAM, uri);
Intent chooserIntent = Intent.createChooser(intent, null);
startActivity(chooserIntent);
```

..please also use setClipData() and then call addFlags(FLAG_GRANT_READ_URI_PERMISSION):

```
Intent intent = new Intent();
intent.setClipData(ClipData.newRawUri(null, uri));
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
intent.putExtra(Intent.EXTRA_STREAM, uri); // keep this for compatibility with old applications
Intent chooserIntent = Intent.createChooser(intent, null);
startActivity(chooserIntent);
```

### Steps to reproduce

- Share an image from a chat

**Actual result:** 

The share sheet does not show a preview because it doesn't have read permission for the `EXTRA_STREAM`.  
Third party share menu replacement apps like [Sharedr](https://sharedr.rejh.nl) do not have system privileges and can't force the read permission for the target app. The share fails.

**Expected result:** 

The share sheet should show a preview of the image  
Third party share menu's should be able to handle the shared image as well.

### Screenshots

Please refer to the following example videos filed on the AOSP bug tracker for the underlying problem:  
https://issuetracker.google.com/issues/176280829

Sharing a file with and without ClipData on Android 10+
https://issuetracker.google.com/action/issues/176280829/attachments/32033725?download=true
https://issuetracker.google.com/action/issues/176280829/attachments/32034124?download=true

### Device info

**Device:** Pixel 3
**Android version:** Android 11
**Signal version:** 5.0.8

## More information

Please refer to this AOSP bug tracker ticket:
https://issuetracker.google.com/issues/176280829

This blog article by CommonsWare explains the problem and solution:
https://commonsware.com/blog/2021/01/07/action_send-share-sheet-clipdata.html

**Comment by frazzydee** [comment]
I can confirm the problem still exists in Signal-Android version 5.5.1. It is impossible to share directly via Sharedr- the only way to do it is to save the file first.
