### ISSUE TITLE
Messages that contain only a single 5 character word are display on 2 lines.

### ISSUE THREAD

**Issue by LucaSkywalkerMT** [signalapp/Signal-Android#10365]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Within a chat, if I receive or send a message that is 5 characters long, the message is broken up, placing the 5th character on a new line. For example, if I receive the message "Fruit", the message will appear as:
Frui
t
This has also happened once with a sentence, where one of the words that could easily fit on the end of a line, was on a new line, but it is much harder to replicated this bug on a sentence. 

Changing resolution up or down (from 2400x1080 to 3200x1440 or 1600x720) fixes the problem. Changing system font size, or app font size, also fixes the problem

### Steps to reproduce
Sending or receiving **most** 5 character words.

**Actual result:** Word is split up, wth the 5th character on a new line.
**Expected result:** Word is shown as one word, on a single line. 

### Screenshots
![Screenshot_20210108-005647_Signal](https://user-images.githubusercontent.com/30926582/103958281-e7028b00-514c-11eb-859e-512ea1e6c7b1.png)
The above 3 words were written as one word each  sent individually, with no space or return.

### Device info
**Device:** Samsung S20+ 
**Resolution:** 2400x1080
**Android version:** OneUI 3.0
**Signal version:** 5.0.8 (Tried on Beta too)

### Link to debug log
https://debuglogs.org/fdf78bd2f88380f3dcda0c999588b65f25a9b5af89072f065565d1b66b65abc9

**Comment by cdenyar** [comment]
This happens for short, multiple word messages, too. For example, "ah ok" will be broke into:
ah 
ok

**Comment by cdenyar** [comment]
I'm having a similar issue, certain strings break into two lines for no apparent reason. For example `V fun` will come out with a line break instead of a space. Signal 5.3.1, pixel 4xl, android 11.

**Comment by longspell** [comment]
Still happens in 5.3.6.  For example a message with just `23.99`, the last nine trails on a new line.

Debug logs: 
https://debuglogs.org/532f0cfef3ad16b16eb952d46227d1b97b04e197bdb086aeb292b091ab877554

**Comment by longspell** [comment]
Confirming the issue exists in 5.3.7 as well.

**Comment by longspell** [comment]
Debug logs for the same issue on 5.3.10

https://debuglogs.org/27847be5cfd83ca4ac61a79b8253b7a352ff83e216401bd42637ae5a1feda748

**Comment by longspell** [comment]
Same issue in 5.3.12.  Noticed this time it was on a received message, the message was `Nope.` and the period appeared on my device on a new line by itself. Changing the text size from `Normal` to `Small` shows the period correctly on the same line as the letters. Setting the font size back to `Normal` and the message again displays as broken up over two lines.

**Comment by Jawshy** [comment]
I've also noticed this issue on version 5.3.12. My OS font size is default and app message font size is normal. Affected words were 'Close' and 'Ready'. Happens whether you're the sender or recipient. Doesn't occur on Signal desktop.

**Comment by longspell** [comment]
I can confirm this morning the issue still persists in 5.4.4 after getting that update overnight.

**Comment by longspell** [comment]
This is still happening in 5.4.12 on my Pixel 4 XL, but doesn't happen to my contact on the same version using a Pixel 4A, seems like it's possibly related to device resolution.

**Comment by LucaSkywaIker** [comment]
My guess is that it has something to do with resolution and font pt mismatch. An over or under estimation of how many pixels the string takes up, as it can happen with longer strings, just harder to reproduce.

**Comment by kosaimgmg2021** [comment]
Phyoe

**Comment by siccovansas** [comment]
I have the same issue on my Samsung Galaxy S10 (Android 11), Signal 5.10.8 (it has been happening on earlier versions as well).

In the screenshot below you see that it only seems to happen if a line contains one word that is exactly 5 characters long. I've tried this on different resolutions, but that doesn't seem to matter.
![Screenshot_20210518-173518_Signal](https://user-images.githubusercontent.com/696839/118681618-0185f880-b800-11eb-95f7-a36f913aa315.jpg)

**Comment by mrliptontea** [comment]
Same (still) on Signal 5.25.8, OnePlus 7, Android 11 (but has been happening before on 10)

**Comment by siccovansas** [comment]
This actually seems to be fixed! At least the problem doesn't occur any more on a Samsung Galaxy S10 with Signal 5.28.10.

@LucaSkywalkerMT and others, do you still have this problem? Otherwise this issue can be closed.

**Comment by mrliptontea** [comment]
After @siccovansas I checked and yes, it does appear to be fixed :smile:

**Comment by LucaSkywalkerMT** [comment]
Confirmed, it is now fixed :)
