### ISSUE TITLE
Wallpaper in chat

### ISSUE THREAD

**Issue by fusionneur** [signalapp/Signal-Android#10373]
Allow setting custom wallpaper (Similar to whatsapp)

**Comment by fusionneur** [comment]
Now that everyone is moving from whatsapp to signal, it would be great to make it more visually appealing for everyone.

**Comment by bme13** [comment]
Hi @fusionneur and welcome,
Please note github is only used for bug reports. The preferred place for a feature request is the community forum. https://community.signalusers.org/. In fact there is already a feature request for custom wallpapers. See https://community.signalusers.org/t/wallpaper-custom-background-for-chats/2975. Perhaps you can add your support for it there. Thanks!
