### ISSUE TITLE
Typing Breakout when the person on the other side texts you

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#10376]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When texting to my friend, I experienced a typing Breakout at the moments when he replied. Like, the texts that you typed freezed until and unless you start from the place where it stopped.
In other words, to be more specific, explained in Steps to reproduce section.

### Steps to reproduce
- Start typing to a person
- Receiver must be online and should be texting you.
- When you're typing, you should his/her message. 
- At that instant of time, your typing is interrupted and you're supposed to type again(not from the beginning, but from where it stopped.)
- Example text: (under square brackers)
[You: Typing...
Receiver: Sent you a message.
You: Typing interrputed]

**Actual result:** My typing is interrupted. Like if was supposed to write "Hello" and I receive the message at the time of typing "He" (either by typing letter by letter or glide typing) You're now supposed to click back button and type again.
**Expected result:** Even you're typing a message and you recieve a message when typing, your typing must not be interrupted.

### Device info

**Device:** Nokia 6.1 Plus*
**Android version:** 10.0
**Signal version:** 5.1.1 (latest beta)

### Link to debug log
https://debuglogs.org/1155817aba73adc28848dd0bd51019b97640abfb1628eaea62329d09b2edc9c1

**Comment by cr-trojan23** [comment]
Bug exists on this device too:
Device : Redmi Note 9 Pro Max
Android Version : 10.0
Android Security Patch : November
Signal Version : 5.1.1 (Beta, latest version)

**Comment by DaBozzz** [comment]
Same on Xiaomi Redmi Note 9 Pro with Android 10 and latest Signal Beta (5.1.1).

**Comment by greyson-signal** [comment]
This should be fixed in 5.1.4. Thanks!

**Comment by pixincreate** [comment]
Ok, waiting for an update now.
@greyson-signal can we expect Signal Messenger to be free of Google Play Services? Or beta version available on signal.org/Android/apk?

**Comment by pixincreate** [comment]
> Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->
> 
> * [x]  I have searched open and closed issues for duplicates
> * [x]  I am submitting a bug report for existing functionality that does not work as intended
> * [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
> * [x]  This isn't a feature request or a discussion topic
> 
> ### Bug description
> When texting to my friend, I experienced a typing Breakout at the moments when he replied. Like, the texts that you typed freezed until and unless you start from the place where it stopped.
> In other words, to be more specific, explained in Steps to reproduce section.
> 
> ### Steps to reproduce
> * Start typing to a person
> * Receiver must be online and should be texting you.
> * When you're typing, you should his/her message.
> * At that instant of time, your typing is interrupted and you're supposed to type again(not from the beginning, but from where it stopped.)
> * Example text: (under square brackers)
>   [You: Typing...
>   Receiver: Sent you a message.
>   You: Typing interrputed]
> 
> **Actual result:** My typing is interrupted. Like if was supposed to write "Hello" and I receive the message at the time of typing "He" (either by typing letter by letter or glide typing) You're now supposed to click back button and type again.
> **Expected result:** Even you're typing a message and you recieve a message when typing, your typing must not be interrupted.
> 
> ### Screenshots
> ### Device info
> **Device:** Nokia 6.1 Plus*
> **Android version:** 10.0
> **Signal version:** 5.1.1 (latest beta)
> 
> ### Link to debug log
> https://debuglogs.org/1155817aba73adc28848dd0bd51019b97640abfb1628eaea62329d09b2edc9c1

I still feel I'm facing the same issue even on 5.1.5 beta @greyson-signal
