### ISSUE TITLE
App-switcher closes when closing TextSecure

### ISSUE THREAD

**Issue by sendiulo** [signalapp/Signal-Android#1037]
When closing the Textsecure app from the default app-switcher (see screenshot) it also closes the app-switcher itself unlike if i close other apps from the app-switcher.

I'm using Cyanogenmod-Version 11-20140210-SNAPSHOT-M3-mako, my TextSecure is up-to-date.

Although it is not a big issue, it is annoying (might annoy others too) and i think it might lead to other errors.

The following screenshot was taken right before closing Textsecure by swiping from left to right. After that, the app-switcher closes.

![app_switcher_screenshot](http://i.imgur.com/HoQ2SYc.png)

**Comment by sedrubal** [comment]
Is this bug still present in Android 5, 5.1 and 6?

**Comment by McLoo** [comment]
@sedrubal looks like it's back. 
Noticed that the other day but ignored it. 

Can reproduce if closing the unlocked Signal  :confused: 
Play store. Rooted Sony stock. Xposed but no xprivacy.

**Comment by sedrubal** [comment]
I meant the bug in android, @moxie0 explained [above](https://github.com/WhisperSystems/Signal-Android/issues/1037#issuecomment-36767446) ;)

**Comment by McLoo** [comment]
Obviously. 😴

**Comment by nils-werner** [comment]
Has the root cause bug in Android been fixed? None of the other messengers have this really annoying problem.

**Comment by nils-werner** [comment]
I am not an Android developer but reading the [`WakefulBroadcastReceiver`](https://developer.android.com/reference/android/support/v4/content/WakefulBroadcastReceiver.html) docs and comparing it to [`Signal/GcmBroadcastReceiver`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/gcm/GcmBroadcastReceiver.java#L31) I have the suspicion that you are not allowed to do

```java
@Override
public void onReceive(Context context, Intent intent) {
  String data = ...
  ApplicationContext.getInstance(context)
                    .getJobManager()
                    .add(new PushContentReceiveJob(context, data));
}
```

because the execution of `onReceive` or your `JobManager` may be interrupted and put to sleep at any time.

If instead you invoked an [`Intent`](https://developer.android.com/reference/android/content/Intent.html) using `startWakefulService()` the execution would not be interrupted.

```java
@Override
public void onReceive(Context context, Intent intent) {
  String data = ...
  Intent service = new Intent(context, PushContentReceiveService.class);  // PushContentReceiveService currently doesn't exist

  Bundle extras = new Bundle();
  extras.putString("data", data);
  service.setExtras(extras)

  startWakefulService(context, service);
}
```

**Comment by Raindeer44** [comment]
This behavior still exists in Android 7.0 and remains mildly annoying.

Has anyone looked at @nils-werner's comment?

**Comment by moxie0** [comment]
@Raindeer44 I think that comment is unrelated to this issue.

I honestly can't remember how this was originally manifesting, but I think it was through SMS messages. Maybe this wouldn't apply to people who aren't using Signal for SMS.  Someone would have to disable this workaround and test all the different scenarios.

**Comment by zehkaiser** [comment]
Still a problem in 8.1. It would be nice to find a better alternative.

**Comment by burntcookie90** [comment]
I am unable to reproduce this issue on Android P, fwiw. It's still occurring consistently on older OS levels (8.1 for example).

**Comment by Benhgift** [comment]
Issue still occurs for me. Android Oreo, pixel 2.

It's rather annoying

**Comment by CosmoJG** [comment]
Still experiencing this on Android Oreo 8.0.0, Samsung Galaxy Note 8.
