### ISSUE TITLE
Allow us to set change default notification settings for groups

### ISSUE THREAD

**Issue by gazm2k5** [signalapp/Signal-Android#10374]
I want to be able to set a notification sound for groups. I found this issue raised way back in 2014, and it was suggested that it'd be even better if we could set notifications per conversation/group. This seems to be implemented, but this isn't what I want, as it means every new group I join, I have to go in and change the notification settings manually.

I would like a low priority alert, eg. a short quiet sound and a short vibrate for groups, and a high priority alert; a louder sound and long vibrate if the message is sent directly to me, or if for example I was @mentioned. When people are spamming groups, I know I can safely ignore the alert if I'm busy, but if someone is messaging me personally I know to check my phone.

To get the best of both methods, it'd be great if we had default settings for regular conversations, a separate set of default settings for groups, and then have the ability to mute/change notifications on a per conversation basis.

**Comment by bme13** [comment]
Hi @gazm2k5 and welcome,
Please note github is only used for bug reports. The preferred place for a feature request is the community forum. https://community.signalusers.org/. A similar request seems to be https://community.signalusers.org/t/more-options-in-notifications/19587. Perhaps you can add your support for it there. Thanks!

**Comment by gazm2k5** [comment]
Ok thanks, will do.
