### ISSUE TITLE
Wrong contact in main screen list

### ISSUE THREAD

**Issue by ikino** [signalapp/Signal-Android#10370]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I switch to Signal app from another, wrong contact show on some line on conversation (first image). When I scroll down to bottom and up, contact shows correctly (second image). Or when I open a conversation, the contact is fixed.

### Steps to reproduce
- switch to another app
- switch to signal
- sometimes show wrong contact on conversation

**Actual result:** wrong contact (random from another contacts) show on conversation
**Expected result:** right contact

### Screenshots

![wrong](https://user-images.githubusercontent.com/43843741/103991766-6e72ed00-5193-11eb-9154-617a50aba048.png)
![right](https://user-images.githubusercontent.com/43843741/103991787-75016480-5193-11eb-9c4e-326ca013d4f7.png)

### Device info

**Device:** Samsung S7
**Android version:** 8.0.0
**Signal version:** 5.1.0

**Comment by Genis-Sage** [comment]
hey @ikino 
could you update to 5.1.1
it seems to be fixed there:
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/33

**Comment by ikino** [comment]
@Genis-Sage thanks, I look before for update, but no update shown. Now I update and it's fixed. Thanks
