### ISSUE TITLE
Allow chat history import from CSV

### ISSUE THREAD

**Issue by janisz** [signalapp/Signal-Android#10372]
It will be great if chat have option to import history from CSV. It will make easier to migrate from different cominicators.
We can start simple and import text only messages. The import CSV scheme can look like this

```csv
datetime,phonenumber,text
2004-02-12T15:19:21+00:00,+1123456789,Ping 🏓 
2004-02-12T15:19:31+00:00,+1222222222,Pong 🏓 
```

Refs: https://github.com/signalapp/Signal-Android/issues/1014

**Comment by Genis-Sage** [comment]
hey @janisz 

please follow the [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md)

Signal Android devs reserved the Github issue tracker for bugs

Feature request have to be discussed on the community forum: https://community.signalusers.org/c/feature-requests/17

**Comment by janisz** [comment]
Closing in favour of https://community.signalusers.org/t/import-whatsapp-chat-history/19748
