### ISSUE TITLE
Add Story/Status Feature

### ISSUE THREAD

**Issue by Abhishekkr93** [signalapp/Signal-Android#10371]
Due to new whatsapp privacy policy , we  moved from Whatsapp to Signal for more secure privacy.

But an awesome feature of story or status is missing here. We Request to add this feature in your new update.

Thanks!

**Comment by vikasshah0** [comment]
##### This feature is really indeed and Useful.

**Comment by Mamta7870** [comment]
This is required , eagerly waiting for this amazing feature.****

**Comment by vikasshah0** [comment]
Yes ---- On Fri, 08 Jan 2021 15:22:56 +0530  notifications@github.com  wrote ----
This is required , eagerly waiting for this amazing feature.****

**Comment by Genis-Sage** [comment]
hey @Abhishekkr93 , @vikasshah0 and @Mamta7870 

please follow the [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md)

Signal Android devs reserved the Github issue tracker for bugs

Feature request have to be discussed on the community forum: https://community.signalusers.org/c/feature-requests/17

**Comment by Abhishekkr93** [comment]
> hey @Abhishekkr93 , @vikasshah0 and @Mamta7870
> 
> please follow the [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md)
> 
> Signal Android devs reserved the Github issue tracker for bugs
> 
> Feature request have to be discussed on the community forum: https://community.signalusers.org/c/feature-requests/17

ok , sure. got it.

**Comment by greyson-signal** [comment]
Hi there! Welcome to the community :) Glad to have you, but as mentioned, we only track bugs on Github. Thanks!
