### ISSUE TITLE
Signal Doesn't support image insertion here

### ISSUE THREAD

**Issue by FredHappyface** [signalapp/Signal-Android#10380]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Sending .webp stickers from gboard fails with a toast notification (I think from gboard with the text: 'Signal Doesn't support image insertion here')

### Steps to reproduce
- Create a note to self/ navigate to a message
- Using gboard, navigate to the sticker tab
- Attempt to send a sticker (webp image) 
- (Note that other image types such as jpeg send successfully) 

**Actual result:** fails with a toast notification (I think from gboard with the text: 'Signal Doesn't support image insertion here'). Image/ Sticker is not sent 
**Expected result:** No user facing error + image/ sticker is sent as with other formats 

### Screenshots

![Screenshot_20210108-170139](https://user-images.githubusercontent.com/41634689/104043305-879b8e00-51d3-11eb-9180-fde56754328c.png)

### Device info

**Device:** Nokia 8 Sirocco
**Android version:** 10.0.0
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/5b638729001fef842ce38f382bd06798fb27d9239305872ac99610aac92e8fdc

**Comment by Genis-Sage** [comment]
could be related to #8593

**Comment by FredHappyface** [comment]
Is that issue not caused by lack of native support for webp? Sending a webp as a standard image (from the device gallery) works

**Comment by FredHappyface** [comment]
Is this worth closing at this point? Worth mentioning that signal still won't accept a webp image from an InputMethodService

**Comment by trmz** [comment]
Seems like the latest version introduced a regression around this, (whether same or different cause).

My Pixel 7 auto-updated around midnight, to v6.27.10 (2023-08-01), and I can no longer send Stickers - same error, "Signal doesn't support image insertion here". Used to work perfectly, of course.

**Comment by shatteredeagle** [comment]
> Seems like the latest version introduced a regression around this, (whether same or different cause).
> 
> My Pixel 7 auto-updated around midnight, to v6.27.10 (2023-08-01), and I can no longer send Stickers - same error, "Signal doesn't support image insertion here". Used to work perfectly, of course.

Same for me, Galaxy S22 Ultra

**Comment by stevemk14ebr** [comment]
This bug has indeed returned, please reopen!

**Comment by archonic** [comment]
Saw this issue for the first time today. It's refusing to insert images which I know have worked before from my recents. That would suggest it's not a webp issue.

**Comment by krosseyed** [comment]
This bit me too...

**Comment by alex-signal** [comment]
Hi folks, turns out there was a race condition here when initializing the composer. It should be resolved in 6.28.2 which is rolling out to beta over the next couple days.

**Comment by stevemk14ebr** [comment]
Interesting, thanks for the fix and update here

**Comment by TheWrightDev** [comment]
Getting it here but it's thread specific which is strange. Some people still works fine, others I get the "Signal doesn't support image insertion here" message.
