### ISSUE TITLE
Encrypted messages are not received by others

### ISSUE THREAD

**Issue by roberdorfer** [signalapp/Signal-Android#1038]
Whenever I try to write an encrypted message (push) to somebody else, they don't receive anything at all. Normal sms work just fine, and I receive their encrypted messages just fine, too.

The registration for the service worked without problems. 

Nexus 5
Android 4.4.2

**Comment by duaneking** [comment]
This is STILL an issue.  This issue is harmful to the userbase, puts lives at risk, and should be considered the priority of the dev team.
