### ISSUE TITLE
For the login I got the code and the app itself copy the code but after that nothing happens.

### ISSUE THREAD

**Issue by AlexyPulivelil** [signalapp/Signal-Android#10381]
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For the login I got the code and the app itself copy the code but after that nothing happens. And there is no button to go to next screen. 

### Steps to reproduce
- No Button Avaliable
- Error connecting to the network is the toast message
- call also not working

**Actual result:**  So I can't join or login
**Expected result:** There should be a **next button*

### Screenshots

![WhatsApp Image 2021-01-08 at 10 47 16 PM](https://user-images.githubusercontent.com/44542655/104047579-debb5600-5207-11eb-8f1f-70ca3fa0fa2d.jpeg)

### Device info

**Device:** 10.OR D
**Android version:** 8.1.0
**Signal version:** 5.0.5

**Comment by androdebugur** [comment]
Please try again with the latest version from app store 5.0.3. The latest version of Signal on app store at this moment is 5.0.3.
If you still have the same problem, can you please upload Debug Logs? See this for instructions [https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports)

**Comment by AlexyPulivelil** [comment]
I installed it in my iPhone. It works fine. No issues at all. Thanks let me check this with older version

**Comment by androdebugur** [comment]
> I installed it in my iPhone. It works fine. No issues at all. Thanks let me check this with older version

Hi,
Sorry, current version is 5.0.8 and not 5.0.3. Please try again with 5.0.8.
If everything works find please close otherwise please provide logs.

**Comment by greyson-signal** [comment]
Hi there, we were experiencing some server issues at the time, and this should be resolved. Please make a new issue if it persists. Thanks!
