### ISSUE TITLE
build.gradle

### ISSUE THREAD

**Issue by ivineethalli** [signalapp/Signal-Android#10397]
Could not compile build file 'D:\folder\Signal\app\build.gradle'.
> startup failed:
  build file 'D:\folder\Signal\app\build.gradle': 451: unable to resolve class ApkSignerUtil 
   @ line 451, column 9.
             new ApkSignerUtil('sun.security.pkcs11.SunPKCS11',
             ^

**Comment by androdebugur** [comment]
Please check this [https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources](https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources) to see if this helps.

**Comment by Genis-Sage** [comment]
hey @ivineethalli 
the github issue tracker is not for building support, especially if you don't use the reprodicible builds

you should ask your question on the [community forum](https://community.signalusers.org/)
