### ISSUE TITLE
When Someone Add A User To A Group The User Got A Fake Extra Profile In Group, See screenshot.

### ISSUE THREAD

**Issue by Priyanshu-Dholu** [signalapp/Signal-Android#10396]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Someone Add A User To A Group The User Got A Fake Extra Profile In Group, See screenshot.

### Screenshots

![Screenshot_20210109-143442_Signal](https://user-images.githubusercontent.com/64322538/104090419-a0bc4180-529c-11eb-9a14-e1c4f289643d.jpg)

### Device info

**Device:** Manufacturer Galaxy A50 SM-A505F
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/9a9c450f76e5ad6f7ceefca2abe86cb85b3605cae905bf5332dd8593936fe29e

**Comment by CrazyPriyans** [comment]
If I Made A Mistake Forgive Me This Is My **First Time Posting A Issue**, Thanks.
