### ISSUE TITLE
App Navigation issue after launching app from a notification 

### ISSUE THREAD

**Issue by TejasTiwari** [signalapp/Signal-Android#10390]
After opening a chat from a notification, the back button leads to the home screen of the phone instead of the chat history page of the app.

**Comment by C4P4E7** [comment]
Same thing happens with me

**Comment by Genis-Sage** [comment]
hey @TejasTiwari and @C4P4E7 

could you fill out the issue template and upload debug logs?

what you describe is not a general issue, as I could not reproduce it

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

**Comment by C4P4E7** [comment]
**Bug description**
When I click on the new message notification then after clicking back button(in the app) it closes the app.

**Steps to reproduce**
-Click on the notification when new message arrives.
-Chat screen opens
-Then press back button(in the app)

**Actual result**: When I click the back button it closes app screen.
**Expected result**: It should show the chat list screen(Home screen of the app)

**Screenshots**
N/A

**Device info**

**Device**: Xiaomi Redmi Note 7 Pro
**Android version**: 10
**Signal version**: 5.0.8

**Link to debug log**
https://debuglogs.org/2e6149db62341fb7a541ae1687d6ece144b4071ea1d40ccd3388eab51c38d7da

**Comment by C4P4E7** [comment]
> **Bug description**
> When I click on the new message notification then after clicking back button(in the app) it closes the app.
> 
> **Steps to reproduce**
> -Click on the notification when new message arrives.
> -Chat screen opens
> -Then press back button(in the app)
> 
> **Actual result**: When I click the back button it closes app screen.
> **Expected result**: It should show the chat list screen(Home screen of the app)
> 
> **Screenshots**
> N/A
> 
> **Device info**
> 
> **Device**: Xiaomi Redmi Note 7 Pro
> **Android version**: 10
> **Signal version**: 5.0.8
> 
> **Link to debug log**
> https://debuglogs.org/2e6149db62341fb7a541ae1687d6ece144b4071ea1d40ccd3388eab51c38d7da
@Genis-Sage

**Comment by C4P4E7** [comment]
@greyson-signal

**Comment by rinukkusu** [comment]
Seems it "works as intended": [Back button in ShareActivity doesn't route back to 3rd party sharing source ](https://github.com/signalapp/Signal-Android/issues/7312)

I really don't like this behaviour as well. If I click a back button inside the app UI, I expect to navigate inside the app. I understand that behaviour for the Android back button, though!

**Comment by leonardo2204** [comment]
@rinukkusu I'm not sure how this issue and the one you shared have a co-relation.
IMO, and from other apps UX, it is expected to return to the home screen after you are deeply thrown by a Push notification, for instance.
[In the docs](https://developer.android.com/guide/navigation/navigation-deep-link#implicit), they specify as: 

As with explicit deep linking, when nesting graphs, the start destination from each level of nesting—that is, the start destination from each <navigation> element in the hierarchy—is also added to the stack. This means that when a user presses the Back button from a deep link destination, they navigate back up the navigation stack just as though they entered your app from its entry point.

**Comment by rinukkusu** [comment]
@leonardo2204 I'm not debating that behaviour for the android back button on the bottom of the screen.

When I tap on the back button on the top left I'd expect to navigate inside the app itself.

Telegram and WhatsApp both behave like that and interestingly also the iOS version of the Signal app. :)

**Comment by leonardo2204** [comment]
I see, I think I misunderstood it, my bad!
