### ISSUE TITLE
Camera feed blank when trying to scan QR code for linking device

### ISSUE THREAD

**Issue by shehrozeee** [signalapp/Signal-Android#10408]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was trying to add a linked device and the when I tap the add fab next activity where I am supposed to scan the QR code is not getting updated from the camera feed. So I cant link the device as I cant scan the QR code.

### Steps to reproduce
- Open Signal App
- got to settings
- Linked devices -> add device

**Actual result:** Camera feed is blank
**Expected result:** Camera feed should work and should allow me to scan the QR code

### Screenshots
![image](https://user-images.githubusercontent.com/33824420/104095426-b7df3d00-5264-11eb-82bd-d3c8d6fae8be.png)

### Device info

**Device:** Samsung Galaxy s10 SM-G973F
**Android version:** 10-Dec1 Sec Patch
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/b2431e35eee28fbe1a6ec8145e27016fa9cad56a0e05ce6827bad6497e15d81f
https://debuglogs.org/6257849a24eb3ce2e1d7b5ac4a4b34f1f30dd31b8932d31d603b36feb1d7a2df

**Comment by SenorFusion** [comment]
@shehrozeee Many people have had this issue.

It looks like this has been an issue since ~2015, with no updates so fixes. We are probably just out of luck.

See #4843 and #7967

**Comment by shehrozeee** [comment]
Ok,
Since I am able to reproduce the issue randomly, I'll try to see if I can
contribute a fix to this.

**Comment by cody-signal** [comment]
@jbagg can you provide updated debuglogs after attempting to link?

**Comment by jbagg** [comment]
Below is the output of logcat | grep thoughtcrime when I open the linked devices screen.  Probably not useful.  I can do something else if specified.  I'm Qt developer, so I'm used to getting debug right in the QtCreator IDE....not too familiar with developing java apps.

```
07-21 17:26:35.316   771  1465 I ActivityManager: START u0 {cmp=org.thoughtcrime.securesms/.DeviceActivity (has extras)} from uid 10086 on display 0
07-21 17:26:35.442   771   792 I ActivityManager: Displayed org.thoughtcrime.securesms/.DeviceActivity: +117ms
07-21 17:26:35.449 22062 22062 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1923 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.thoughtcrime.securesms fieldId=-1 fieldName=null extras=null}, false)
07-21 17:27:12.248 22062 22062 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1923 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.thoughtcrime.securesms fieldId=2131364226 fieldName=null extras=null}, false)
07-21 17:27:21.697   771  1470 I ActivityManager: START u0 {cmp=org.thoughtcrime.securesms/.DeviceActivity (has extras)} from uid 10086 on display 0
07-21 17:27:21.795   771   792 I ActivityManager: Displayed org.thoughtcrime.securesms/.DeviceActivity: +90ms
07-21 17:27:21.803 22062 22062 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():1923 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.thoughtcrime.securesms fieldId=-1 fieldName=null extras=null}, false)
```

**Comment by jbagg** [comment]
I decided to check that my camera actual works and it does not.  Connector was disconnected.  False alarm.  Nothing wrong with the app.

**Comment by savegame** [comment]
same problem, cant link desktop app, camera show QR but nothing happens

**Comment by cody-signal** [comment]
@savegame can you provide a debuglog?

**Comment by savegame** [comment]
@cody-signal , https://debuglogs.org/android/5.44.3/01817d68799632ada5dad4c13a3298878bfb370327fce21362744e95eb0d2b79

**Comment by cody-signal** [comment]
@savegame It appears the camera is capturing data, but when attempting to process the QR code it's invalid or fails a checksum. To me this feels like something weird in the camera code.

We have a new version coming to beta today that has updated camerax which might help here, but unsure. Please try again when you can install 5.45.x.

Are you running a custom rom?

**Comment by savegame** [comment]
@cody-signal 
>  but when attempting to process the QR code it's invalid or fails a checksum.

you mean android camera should recognize QR by it self? looks like mine android camera doesn't that

>Are you running a custom rom? 

yes, i have custom rom. Its SailfishOS with android container as subsystem, it very cuted version of AOSP.

> lease try again when you can install 5.45.x.

i'll try

**Comment by rpsu** [comment]
I have the same issue, camera seem to not react to QR code at all. Based on logs QR code is detected but checksum verification fails (side note: would be nice to have some UI hint QR code _was_ detected). 

I'm on Samsung Galaxy S20 FE, with Android 12, Signal 5.46.1 (just updated) and the Signal Desktop is 5.54.0 (just updated). 

My phone nor laptop have nothing unusual AFAIK and it did work before just fine. OSX and Android (as well as the Signal apps) have been upgraded since the last time I connected this laptop and phone, though.

Logs: https://debuglogs.org/android/5.46.1/2a9204f74f0d26cd7db5eae659262b1e7a22f2734004b07312d731a5f67793f2

**Comment by cody-signal** [comment]
Hi folks, there's going to be a tweak coming in our latest beta (5.46.2) that should help with this.

**Comment by savegame** [comment]
@cody-signal , sorry for stupid question, but: where i should get beta application?

**Comment by cody-signal** [comment]
See the top post here for how to join the beta: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-46-release/46450

Note it's a beta, there will be the occasional bugs and rough edges if you decide to continue running it. You can also wait until it's out in production, likely early next week. You can also enroll in the beta now, and exit it later if desired. Just a heads up though, if you join the beta you won't be able to exit until we push another version.

**Comment by rpsu** [comment]
`5.46.3` now and works like a dream <3 Thank you!

**Comment by savegame** [comment]
5.46.6 now works perfect on SailfishOS inside Android lxc container (aliendalvik) Thanks a lot! 👍
