### ISSUE TITLE
Add Nokia 7.2 to AEC blacklist or more better make it configurable

### ISSUE THREAD

**Issue by bammab** [signalapp/Signal-Android#10402]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Everybody I call hear an echo of its own voice. If I call another Nokia 7.2 (multiple in family) I hear me, too. So my device makes trouble.
It's the same as #7635 and much more.

I tried to test by my own build, but I could not install/test it, because of mismatched signature and I don't want to delete all data/settings. (How do you do this?! Backup, uninstall, install fix, test, uninstall, install original, restore all the time?!)

I know this would be a kind of feature request, but it would be great, if this would be configurable (under advanced option or something else). Most people would not do a bug report and could not/don't want to test before releasing mainstream. Also you could not check it without having the same device. But is it the real problem? So the signal community could help other users. Until now - I had a few people who sad signal sucks because of this problem. It don't work out of the box - most people have no interest why?! It would be great to ease this procedure...
Second a user could easily check, if the hardware AEC is fixed in a later Android release of the manufacture.

```
[ro.product.manufacturer]: [HMD Global]
[ro.product.model]: [Nokia 7.2]
[ro.product.model.display]: [TA-1196]
```

### Steps to reproduce
- Call another signal contact or another contact call me

**Actual result:** Others hear an echo
**Expected result:** No echo for other parties

### Device info

**Device:** HMD Global Nokia 7.2
**Android version:** 10 Build 00WW_2_390_SP01 (latest update from dec 2020)
**Signal version:** 5.0.8

**Comment by marfrh** [comment]
See also #9817

**Comment by Nisc3d** [comment]
Having the same problem with a Nokia 7.2

**Comment by LoveIsGrief** [comment]
I don't know who to ask here, so @moxie-signal  or @greyson-signal , would you mind me taking a stab at implementing a toggle for `WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler` and ? Under "Advanced" settings maybe?

According to [StackOverflow](https://stackoverflow.com/questions/62479789/webrtc-android-echo-cancellation) that might not even work and toggles for `setUseHardwareAcousticEchoCanceler(...)` and `setUseHardwareNoiseSuppressor(...)` might be needed. I have a device I can use to test with (ONEPLUS A3003) that has terrible echo with Signal.

**Comment by PrSunflower** [comment]
Hello!

Echo cancellation is now working fine on my Nokia 7.2. See my reply here: https://github.com/signalapp/Signal-Android/issues/9817#issuecomment-772737402

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
