### ISSUE TITLE
Signal Message Notifications Not showing up

### ISSUE THREAD

**Issue by nishithshowri006** [signalapp/Signal-Android#10405]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I install and use signal I am not receiving notifications. Until I turned off intelligent control of my os settings while the other apps are getting notifications even though the have intelligent control turned on. This is not just the case with my phone even in bunch of my other friends phones (samsung phones they are not showing up). It's not like showing up late, they are completely not showing up until I open the app. 

**Actual result:** :Notification aren't showing up until I open the app.
**Expected result:**: Messages should show up in notifications.

### Device info

**Device:** OnePlus Nord 
**Android version:** 11.0.0
**Signal version:** 5.1.1

**Comment by Sgn-32** [comment]
Have you looked at the support pages for troubleshooting?

https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

**Comment by Genis-Sage** [comment]
hey @nishithshowri006 
also a debug log would be great

if your OS kills Android, Signal devs can not do much about it

**Comment by nishithshowri006** [comment]
@Genis-Sage hey thanks for the reply but whatsapp and other apps like twitter are showing the message notifications right even though those intelligent controls are on. I just checked with my friends samsung he also turned off the battery setting then they started showing up.

Here is the debug log:
https://debuglogs.org/b81b7cdb2a673df201a0648d37beff24903beabdb7282900f338e42b8170a3f7

**Comment by Genis-Sage** [comment]
hey @nishithshowri006 
the point is, that the device manufacturers are "biased" and create white lists for "big apps" which are not killed
and only the device manufacturers can edit these white lists

see https://dontkillmyapp.com/

**Comment by nishithshowri006** [comment]
Okay thanks man. I am also checking comments of some users on twitter trends found that many users have the same problem. Closing the issue then
