### ISSUE TITLE
Not able to Send media(link/image) to multiple users in Signal at once

### ISSUE THREAD

**Issue by Tanzeel159** [signalapp/Signal-Android#10401]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I want to share any link or media (image) from any external app (like reddit) or a browser to multiple recipients in signal(not in same group) , I am not able to send them the media/link at once. I have to send them one by one which is tedious. 
Media stored on my device can be sent to multiple recipients at once.
On WhatsApp if I select any image or link I can easily share it to multiple users

### Steps to reproduce
- Select any image or link 
- Select the share button 
- Select Signal
- Try to select multiple users 

**Actual result:** there is no feature implement to select multiple users at once to send file to everyone
**Expected result:** there is option to select more than one user to send the file

### Device info

**Device:** Oneplus 7T
**Android version:** 10.0
**Signal version:** 5.0.8

**Comment by Genis-Sage** [comment]
hey @Tanzeel159 
as you state by yourself "there is no feature implement[ed]"

so this is a feature request which belongs on the [community forum](https://community.signalusers.org/c/feature-requests/17), as clarified in [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md)

**Comment by Tanzeel159** [comment]
> hey @Tanzeel159
> as you state by yourself "there is no feature implement[ed]"
> 
> so this is a feature request which belongs on the [community forum](https://community.signalusers.org/c/feature-requests/17), as clarified in [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md)

Hey I will mention it in the Community forum thanks !

**Comment by mWaltari** [comment]
This is the only major problem from me, after other apps I've used (WhatsApp, FB messenger, Telegram etc).

I really would like this NOT to have 5 contacts limit like FB messenger and WhatsApp now has. 

If I've find interesting bit of news and would like to share it people, it'll just wastes time to resend it two three times.
