### ISSUE TITLE
Can only send SMS to contact on Signal from Android, works regularly on Ubuntu

### ISSUE THREAD

**Issue by Dzegheim** [signalapp/Signal-Android#10407]
Bug Description

I was messaging with a contact regularly when suddenly I could not message them with Signal messages, only regular SMS. Holding the icon doesn't work with them (the menu to choose secure message or SMS does not appera), but does with everyone else. We both tried reset secure session, I rebooted my phone and the app multiple times. From the client on my computer I can still message with them regularly. I still receive messages on my phone. Secure call is also unavailable.
Steps to Reproduce

I don't know how to reproduce this.

Actual Result:
I can no longer send secure messages or secure call my contact (and only that contact) only on my phone.

Expected Result:
The standard app behaviour.
Platform Info

Signal Version:
On Android (not working): 5.0.8.7592
On Desktop (working): 1.39.4

Operating System:
GrapheneOS RQ1A.210105.002.2021.01.05.03
Link to Debug Log

Problems started around 14.00 (2 p.m.)
https://debuglogs.org/f0b95acfd7f3d3469663b7ad48959b7253f0c47f92fa9c980b15c7e16fc8ee35

**Comment by PinkDev1** [comment]
Same here.
My device:
- Signal v5.0.9
- Android 9
- Moto e6 plus

other device:
- Signal v5.0.8
- Android 7.0
- LGM250AR

**Comment by Dzegheim** [comment]
@PinkDev1 in a few hours I wanted to try and delete the app and download it again, have you already tried this solution? In any case I'll edit the issue to see how this goes.

**Comment by PinkDev1** [comment]
@Dzegheim Already tried on the Android 7 device. Issue persists :/

**Comment by PinkDev1** [comment]
I'm not sure whats wrong. I uninstalled and downgraded to v5.0.8 (Playstore release), and while I was setting it up, I saw a brief toast that said something along the lines of "Failed to retrieve contacts, verify your internet connection". Obviously, I have an internet connection so idk what happened.

Here are my fresh logs:
https://debuglogs.org/dafe40b399dde9a90d6b0d4fbf3ab612062b2235cd276ceb6b27f1c4bc1a9010

**Comment by PinkDev1** [comment]
@greyson-signal @alex-signal

**Comment by greyson-signal** [comment]
Hi there, we were experiencing some server issues earlier that could have resulted in you not being able to tell if a number was a Signal user or not. Are you still having this problem?

**Comment by Dzegheim** [comment]
Hello, unistalling and reinstalling solved the issue. I could not access Github before now to close the issue, thanks for the service you provide!
