### ISSUE TITLE
Sending large up to 50mb is not working

### ISSUE THREAD

**Issue by Goku35x** [signalapp/Signal-Android#10417]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I try to send a video to a friend which is 47mb large. It fails the whole time. Started multiple times but it does not work.

### Steps to reproduce
send a full HD 30fps video which is about 50mb large.

### Device info

**Device:** Poco M3
**Android version:** Android 10 QKQ1.200830.002
**Signal version:** 5.0.8

**Comment by kashyapraval** [comment]
This might be a temporary issue as many people have migrated to Signal. Bandwidth can't handle the same at the moment. The infra would need to be scaled.

**Comment by cody-signal** [comment]
Could you provide a debuglog?
