### ISSUE TITLE
Keyboard lags after sending message

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#10419]
### Checklist

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a message and starting to type right after it, the keyboard will lag and won't register the first few inputs

### Steps to reproduce
- Write a message (ex. Note to self)
- Send the message
- Start typing immediately

**Actual result:** The keyboard will not register the first few key inputs
**Expected result:** New message is typed into the text input field

### Screenshots
https://user-images.githubusercontent.com/10947344/104107718-cce8ba00-52be-11eb-9902-366635666710.mp4

#### Device 1
**Device:** Xiaomi
**Android version:** 10.0
**Signal version:** 5.1.1 (Play Store beta channel)
**Keyboard:** Gboard (both incognito and normal)

#### Device 2
**Device:** Xiaomi
**Android version:** 11.0
**Signal version:** 5.1.2 (compiled form master at caf4f1a7ba432f324404d3e1c318b17331a0a191)
**Keyboard:** AOSP Keyboard

### Link to debug log
https://debuglogs.org/b0bc6a310815bd5d17c3429227fb33df40883382e163de9cc43666cf3e471218

**Comment by greyson-signal** [comment]
Hi there, this should be fixed in 5.1.4. Thanks!
