### ISSUE TITLE
backup restore fail on two files: both count msgs; one says wrong passphrase, one crashes app

### ISSUE THREAD

**Issue by jwhendy** [signalapp/Signal-Android#10416]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am trying to use the restore backup feature and Signal is failing in two unique ways depending on the file.

Possibly related: #7560, #9136, #9154, #10053, #9867, #9808, #9756 (unlikely), #9398, #9394, #9327, #9302, #9177

If one of these match, feel free to close this as duplicate. I have three different backup files with three different behaviors, so I wasn't sure which of these to add to, nor how to interpret the logs to figure out if my situation is actually a duplicate.

### Steps to reproduce
- turn on backups on signal, store 30 digit passphrase
- mount phone via USB via `simple-mtpfs` and copy backup file(s) using `cp` to linux laptop on btrfs
- factory reset phone
- copy a backup file back to `/Phone/Signal/Backups/file`
- install signal
- grant permissions, then attempt to restore backup file

**Actual result:**
I have three signal backups. I first enabled backups on 2020-07-23 in preparation to factory reset (phone feeling laggy), but it took me until more recently to backup everything else and actually do it. I also have backups from 2021-01-02 and 2021-01-03 which were auto-generated by signal since I left backups enabled. I copied these over on 2021-01-03 before my factory reset on 2021-01-04.

Results are:
- 2020-07-23: texts restored as expected
- 2021-01-02: accepts passphrase, counts to ~56k messages, then says "incorrect passphrase" and stays at restore screen
- 2021-01-03: accepts passphrase, counts to ~56k messages, then crashes/closes

This isn't the *worst* thing ever, but I lost ~5mos of texts as-is.

**Expected result:** any chosen backup file would restore as expected.

### Device info
**Device:** Samsung S8
**Android version:** 9
**Signal version:** 5.0.8

### Link to debug log
- 2020-07-23 (successful): [signal log](https://debuglogs.org/98a5ac48d74468ce493e8a3ee3dca030b974c633376bea34cb99ffdc03cdc9dc), `adb logcat` [gist](https://gist.github.com/jwhendy/c1f7e72275ec9f03a7b950040cbfb166)
- 2021-01-02 (bad passphrase after counting): [signal log](https://debuglogs.org/4e485b0bbdd458a2af8281066d508b5bcd14cbfd42e88ec555c6b8ca72152a81), `adb logcat` [gist](https://gist.github.com/jwhendy/7cd4136bb16f6b4cc6e0b86dc700e273)
- 2021-01-03 (crash after counting): can't capture signal, `adb logcat` [gist](https://gist.github.com/jwhendy/87ac269fde95bec3d4f2a859f5a669a9)

**Comment by jwhendy** [comment]
Hi @stale, yes it's still relevant. If you take a look above, you can see that I posted a lot of information and that the primary issue is... no one has looked at it. I'm unable to debug android apps, as much as I want to. I did what I think I should: provide as much detail as possible.

For what it's worth, I never did recover those ~5mos of texts. They're gone, and I tried to help future users avoid this by posting the above. I now await anyone from Signal to see what the potential cause could be, and I'd be happy to provide additional information upon request.

**Comment by jwhendy** [comment]
Yes, still relevant.

**Comment by jwhendy** [comment]
It's still relevant. Anyone from signal able to engage? Lack of activity is due to needing next steps to diagnose.

**Comment by cody-signal** [comment]
Hey there, it looks like the files for the later two backups are corrupt and cannot be decrypted. In the upcoming quarter we are planning on adding some data integrity checks for backup creation to help detect this, but as it stands there's not much we can do. There are a couple tools out there that attempt to read/fix backup files you can search for.
