### ISSUE TITLE
Feature Request: Add capability to respond to an individual pic/video in a collection

### ISSUE THREAD

**Issue by kashyapraval** [signalapp/Signal-Android#10413]
A feature request not a bug report (Apologies)

lets call a collection of pics bundled up together in a conversation as Album.

Currently, one cannot respond(like/comment) to an individual element of that album but can do so only on the entire album

**Comment by Genis-Sage** [comment]
hey @kashyapraval 
as the [contributung.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) states, the issue tracker is reserved for bug

for feature requests, please visit the [community forum](https://community.signalusers.org/c/feature-requests/17)

**Comment by kashyapraval** [comment]
not a place for feature requests. hence closing the same.
