### ISSUE TITLE
Feature Request : Live location sharing

### ISSUE THREAD

**Issue by losthero15** [signalapp/Signal-Android#10414]
Live location sharing with timeout, like 30, 60 minutes, 2, 4, 8 hours and so would be nice.

**Comment by Genis-Sage** [comment]
hey @losthero15 
as the [contributung.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) states, the issue tracker is reserved for bug

for feature requests, please visit the community forum:
https://community.signalusers.org/t/live-location-sharing/2564
