### ISSUE TITLE
Account creation. HUGE delay between seeing the verification page, receiving the validation SMS and receiving the Calls

### ISSUE THREAD

**Issue by tionebrr** [signalapp/Signal-Android#10410]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Did Elon Musk created a panic on your registration server? 😄 

### Bug description
I created my account yesterday and I still receive codes by phone calls. The SMS were also very slow to get to my phone, and by the time I received them, the verification code had already expired. That was making me make more attempts and there is surely a queue of pending verifications for a lot of new users.

### Steps to reproduce
For the best experience in reading this issue, I highly recommend this background music:
https://www.youtube.com/watch?v=sRJTfTWidhU
- Be me
- Install Signal on your Oneplus 5 
- Fill the phone number
- Wait for the SMS
- Wait a bit more
- Try to get the code by phone call
- Wait
- Wait more
- Think that there is a problem with your install
- Desinstall and resinstall, flush cache etc...
- Try again
- Ah ! Received an SMS
- Try the code: it doesn't works
- Wait about 15 minutes
- Receive a new code, try it 
- Doesn't works because your session has expired and the app is deconnected
- Relaunch the app
- Try again the code
- Code is invalid
- Think: "DAMN ELON MUSK"
- Wait more
- Try the call again
- Repeat above step about 3 times
- Hit the max attempt limit
- Start to figure out that millions of people are doing this and that your a part of the problem

In the end I waited one hour and it worked. But the SMS validation came only about one minute after filing the phone number.
I received the calls during the night, hours later.

**Actual result:** I totally screwed up your registration server with ton of attempts
**Expected result:** You shouldn't let me do this 😄 

### Device info

**Device:** OnePlus 5
**Android version:** 10
**Signal version:** latest in Play
**Provider** Free (France)

### Link to debug log

Creating issue way after the bug occured. I think the app worked fine.

And I'm still receiving calls 😄

**Comment by rajatrao777** [comment]
Same issue here
Not able to register ,heavy delay between entering phone number and receiving otp.

**Comment by petermax0908** [comment]
This is a known issue and also not really a bug since the servers are just under heavy load.
Signal official statement: https://twitter.com/signalapp/status/1347240006444675072?s=20
Also please could you shorten your report a bit? It may be funny to you but i think it will not be to the developer that has to read it in time. thank you.

**Comment by tionebrr** [comment]
@petermax0908 Thanks for the link to the official statement. 
I know it is not a bug (registration worked), but there still might be an overlook. You shouldn't accumulate a queue of hours when the app can't stay connected more than 5 minutes waiting for the verification code. Also, it is looking like the app sends a verification code request every time you reopen it. No bug but if this is putting a server on its knee, then there is a problem.

Hopefully this is the only time this is going to manifest itself.

I'm not going to shorten my report, everything I wanted to say is there, and I wanted to convey how a basic user will try to interact with the app. It may not be funny to you, but being waken up at 3:30 am by calls from servers is not funny neither, yet I laughed.

Damn Elon... 😆
Kudos to the Signal team. 🎉
