### ISSUE TITLE
Can not open backup settings anymore

### ISSUE THREAD

**Issue by Franzl123** [signalapp/Signal-Android#10415]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
yesterday i noticed that the backup was disabled. i enabled it again (and saved the passphrase of course). now i want to change the location for the backup, however, the setting for the backup can no longer be opened. every time i try, signal freezes and has to be terminated.

### Steps to reproduce
- go to settings -> chats an media -> tap on "chat backups" (at the bottom) -> freeze

### Device info

**Device:** One Plus 5T
**Android version:** LineageOS 17.1 (Android 10)
**Signal version:** 5.0.9

**Comment by Genis-Sage** [comment]
hey @Franzl123 
could you post a debug log?

with that, Signal devs will definitely have a hard time finding out the root cause

**Comment by Franzl123** [comment]
hi,

yes, you are absolutely right! in the moment of posting i thought "shit, i forgot the log!" and after an call it was completely out of my brain!

now i wanted to capture the log with adb and found out that the setting works! it only took a while!

i had set the backup directory to my pretty well filled download folder. maybe the "problem" is the large number of files.
now the backups go back to signal/backups and the option is fast as an arrow again.

so, the "problem" is fixed :)
