### ISSUE TITLE
GPS location link is re-directing to Uber app (Android)

### ISSUE THREAD

**Issue by serisaigeetha** [signalapp/Signal-Android#10427]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When GPS location is sent using Google Map, the link redirects it to Uber app.

### Steps to reproduce
- Send GPS location 

**Actual result:**  If either sender or receiver clicks on GPS location link, it redirects to Uber App.
**Expected result:** Expected behaviour is that GPS location link should redirect to Google Maps.

### Device info

**Device:** Manufacturer Model - ONEPLUS A6013
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/56d5efec8d19f32c5ab33303845209466a6fe954aaa3a1e9e2cfa2a3d8cae6de

**Comment by mvhk** [comment]
Kindly change your default application for location, by using **Reset App Preference**
