### ISSUE TITLE
Possible to (accidentally) send a message to a blocked contact

### ISSUE THREAD

**Issue by rbtr** [signalapp/Signal-Android#10428]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a user is blocked, we're prevented from sending them a message via the normal routes - the text field and send button are hidden behind a dialogue with "Delete" or "Unblock" buttons.

However, it's possible to _share_ to that blocked contact, allowing us to (accidentally?) send them a message (or photo, or link, etc), and the thread opens without the Delete/Unblock overlay. It's also possible to _forward_ them a message from within the app. Leaving a draft and re-entering the thread with your blocked contact will show both the Delete/Unblock dialogue and enough of the text entry field and Send button to finish that mistake. 

### Steps to reproduce
- User A blocks user B
- User A shares via an Android Intent to: 
  - Signal, and selects B's thread
  - or directly to B's thread if that appears in their sharing intents

**Actual result:** The thread opens with the shared content (link, image, etc) and an editable text field for the message, which can then be sent.
**Expected result:** It should not be possible to send to a blocked contact? Unclear.

### Screenshots

<image src=https://user-images.githubusercontent.com/2940321/104115718-3fb65d00-52e0-11eb-91b2-ef968a079f69.png width="300">

### Device info

**Device:** Pixel 5
**Android version:** Android 11 
**Signal version:** 5.1.1

**Comment by rbtr** [comment]
Extra note: read and delivery reports from the blocked user _are_ delivered and processed by the blocker's client, and the blocker will see delivered/read status of the message they have sent to the blocked user.

**Comment by UserX404** [comment]
Featur requests are handlen within the [community forum](https://community.signalusers.org/) and Github is for bugs only.

**Comment by rbtr** [comment]
@UserX404 I consider this a bug - I expect to be prevented from sending a message to a blocked contact, and I am usually. But if I enter the conversation with that blocked user via a share intent, the overlay that would prevent me from sending a message to them is not shown.
