### ISSUE TITLE
Screen lock problem

### ISSUE THREAD

**Issue by akshayd002** [signalapp/Signal-Android#10424]
We need to give lock signal every time if we want to lock the signal application. So it should be enabled immediately, or should be given timings. So this fix will be good

**Comment by Sgn-32** [comment]
It's possible in the Signal settings -> Privacy -> Screen lock

![Screenshot_1610280640](https://user-images.githubusercontent.com/49990901/104122474-7a9eac00-5345-11eb-9626-0bd34044ab31.png)


https://support.signal.org/hc/en-us/articles/360007059572-Screen-Lock

**Comment by ayaankhan98** [comment]
i think this is not working as expected. i set the screen lock inactivity timeout to 1 second but this is not automatically locking the app. i do have to manually lock the app from the notification bar everytime.

**Comment by Sgn-32** [comment]
Minimum screen lock time is 1 min, also when is possible to enter only few seconds.

**Comment by akshayd002** [comment]
Everytime I exit the app I should give lock signal manually. So what iam
telling is don't make user to give manually. Give immediately option to
lock when user exit the app.

**Comment by ayaankhan98** [comment]
> Minimum screen lock time is 1 min, also when is possible to enter only few seconds.

yes, we can set it to 1 sec but as soon as we press OK after setting it to 1 sec it does set to 1 minute instead of 1 sec. Moreover, after 1 minute it is not working as expected.

**Comment by AliabbasMerchant** [comment]
A proper, more detailed bug report is available in #10208  

Basically, the changes required are:
1. Allow immediate locking (0 seconds)
2. Allow minimum inactivity time in seconds also (currently the minimum is 1 min. Lower values can be entered, but the value shifts to a minimum of 1 minute) [Note: Seconds level granularity is accepted. i.e., a value of 1min30sec is accepted]
3. Ensure that the inactivity timeout feature works as intended (@ayaankhan98 has reported that it was not working for him)

**Comment by Sgn-32** [comment]
@ayaankhan98 please post a debug log, if the screen lock with 1 min doesn't work.

**Comment by ayaankhan98** [comment]
> A proper, more detailed bug report is available in #10208
> 
> Basically, the changes required are:
> 
> 1. Allow immediate locking (0 seconds)
> 2. Allow minimum inactivity time in seconds also (currently the minimum is 1 min. Lower values can be entered, but the value shifts to a minimum of 1 minute) [Note: Seconds level granularity is accepted. i.e., a value of 1min30sec is accepted]
> 3. Ensure that the inactivity timeout feature works as intended (@ayaankhan98 has reported that it was not working for him)


@Sgn-32 
There was some sort of issue with my device may be, now it is working as intended. Therefore i would say that only points 1 and 2 are relevant now.

1 - Allow immediate locking (0 seconds)
2 - Allow minimum inactivity time in seconds also (currently the minimum is 1 min. Lower values can be entered, but the value shifts to a minimum of 1 minute) [Note: Seconds level granularity is accepted. i.e., a value of 1min30sec is accepted]
