### ISSUE TITLE
Video sent from iPhone is blank but plays audio

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#10422]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I received a video from someone with an iPhone and the video is blank with audio. If I download it on my phone, the audio still plays but there is a freeze-frame from the video.

The iPhone user shot the video through the Signal app.

Video plays perfectly fine on the desktop app.

### Steps to reproduce
- Have a friend with an iPhone send you a video
- Try to play the video

**Actual result:** Video is played but you can only hear the audio. There is no video. 
**Expected result:** Video should play as intended. 

### Screenshots

![image](https://user-images.githubusercontent.com/18274896/104108987-11f4f800-528f-11eb-863f-515f35f30946.png)

### Device info

**Device:** Pixel 4
**Android version:** 11
**Signal version:**  5.0.8 
### Link to debug log

https://debuglogs.org/fb183bf97ef84cefc84aa36f5fa29f86dec13c539029b8fb28ebd40ea276c9b4

**Comment by DhruvaSambrani** [comment]
I've seen such an issue in a completely unrelated context, but it is probably due to differing encodings. My guess is that it was encoded with H265 instead of H264, and Android can't decode it. 

Try viewing the file with VLC, and if it works fine it's most probably this. If so, probably have to add a decoder.

**Comment by Tursko** [comment]
> I've seen such an issue in a completely unrelated context, but it is probably due to differing encodings. My guess is that it was encoded with H265 instead of H264, and Android can't decode it.
> 
> Try viewing the file with VLC, and if it works fine it's most probably this. If so, probably have to add a decoder.

Yep, video file works perfectly fine on VLC.

**Comment by MatthK** [comment]
I have the same problem. Interesting though is, when the video is recorded with the normal camera app (not in the Signal App) and then sent from the iPhone to the Android, the video plays normally.

**Comment by zzzb123** [comment]
I have the same issue, however attempts to save the file are met with an exception stating the file does not exist: https://debuglogs.org/8d3dc5fb3ebca1c2e22fe531afc5cb0844fd78211719963b2e454fcfba226c06

**Comment by Tursko** [comment]
This is still a valid issue.
