### ISSUE TITLE
Group call not work

### ISSUE THREAD

**Issue by ikino** [signalapp/Signal-Android#10438]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Group call not work.... Show for a while Joining, than hang up.

### Steps to reproduce
- open group
- click camera icon
- click start call button

**Actual result:** call not work
**Expected result:** call work

### Device info

**Device:** Samsung S7 / Moto G7S+
**Android version:** 8.0.0 / 10
**Signal version:** 5.1.1 / 5.1.1

**Comment by hchr** [comment]
It works again here.

**Comment by greyson-signal** [comment]
Are you able to post a link to a debuglog? Instructions [here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports).
