### ISSUE TITLE
Add to Home Screen isn't working

### ISSUE THREAD

**Issue by AbhishekDoshi26** [signalapp/Signal-Android#10433]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Add to Home Screen isn't working. When we click on Add to Home Screen for any contact, toast appears but it's not adding the chat to home screen. 

### Steps to reproduce
- Click on any contact
- Click on Add to home screen

**Actual result:** Toast stating "Added to home screen" appears as expected but it's not doing anything and the chat doesn't appear at home screen or any other screen too.

**Expected result:** The specific chat should be available on home screen / any other screen. 

### Screenshots
Screenshots aren't applicable for this bug as nothing is happening.

### Device info

**Device:** Vivo 1907 aka Vivo S1
**Android version:** Funtouch OS_10 (Android 10)
**Signal version:** V5.0.8

### Link to debug log

https://debuglogs.org/863d5ddb3f4338bbc0153089121fcf34a39c7dc3d4456a0e0964bb104173fa02

**Comment by deepsingh132** [comment]
I've tried to reproduce this issue but it's working with nova launcher and also default launcher which I'm using. Is this bug for your stock launcher ? My device is Huawei Honor 8x android 10. After displaying added toast it also asks for your permission to add the icon to your home screen. Have you allowed that ? 

Here's an example: 
![Screenshot_20210110_144928](https://user-images.githubusercontent.com/18049003/104119073-30242c00-5353-11eb-9483-275833fe6851.jpg)

**Comment by CITGuru** [comment]
@deepsingh132 The same for me also on Pixel 4 default launcher. Works well. Probably try using another launcher

**Comment by AbhishekDoshi26** [comment]
@deepsingh132 and @CITGuru yes in my friend's phone also it's working. But I am not even getting the pop-up for permission. Directly toast is been shown. And I am not using any launcher, it's the default one.

I also checked the permissions in the settings, there also no permission is specified.

![Uploading Screenshot_20210110_141725.jpg…]()

**Comment by Ralms** [comment]
Just tried this on an Samsung S9+ running Android 10 with default launcher and is working fine for me. 
When I go to the chat in question and select "Add to Home screen", it will show me a small option window in the bottom if I want to drag and drop the new icon, or I can just do "Add" and it will add it on the first available location.

**Comment by AbhishekDoshi26** [comment]
Weird. I am not even getting that. When I click on Add to Home Screen, it just shows the toast and app remains on the same screen

**Comment by Ralms** [comment]
I've took a quick look at your log and I don't see any error. 
Also compared it with mine and they have very similar entries. On yours we have:
```
5.0.8 2021-01-10 13:43:30.176 GMT+05:30 I ConversationActivity: Creating home screen shortcut for recipient RecipientId::1
5.0.8 2021-01-10 13:43:30.179 GMT+05:30 W ConversationActivity: Utilizing fallback photo for shortcut for recipient RecipientId::1
5.0.8 2021-01-10 13:43:30.390 GMT+05:30 I GroupCallViewModel: Ignore call event for different recipient.
5.0.8 2021-01-10 13:43:30.393 GMT+05:30 I ConversationActivity: Loaded 1 identities in 2 ms
5.0.8 2021-01-10 13:43:30.456 GMT+05:30 I ConversationActivity: Got identity records: false
```

The line ``GroupCallViewModel: Ignore call event for different recipient.`` doesn't happen on mine. 

The other 4 do.

**Comment by AbhishekDoshi26** [comment]
Edit: I explicitly turned on 'Create Shortcut' permission from the settings of my phone and now it's working.

Suggestion: May be it was device/OS specific so team need to work on legacy permissions I guess. Because when I clicked on Add to home screen, it didn't ask for any permission and due to that the shortcut was not creating. But, once I enabled it from Settings -> All Permissions, it's working now!

**Comment by Ralms** [comment]
> Edit: I explicitly turned on 'Create Shortcut' permission from the settings of my phone and now it's working.
> 
> Suggestion: May be it was device/OS specific so team need to work on legacy permissions I guess. Because when I clicked on Add to home screen, it didn't ask for any permission and due to that the shortcut was not creating. But, once I enabled it from Settings -> All Permissions, it's working now!

Would you mind sharing a screenshot of the Signal permissions on your device? 
My Samsung doesn't have that permission.

**Comment by Ralms** [comment]
Even on Android Dev docs, at first sight, it doesn't seem to be required any permission for this:
https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#inner-elements

So I wonder if this is a modification to Android from Vivo.

**Comment by AbhishekDoshi26** [comment]
> > Edit: I explicitly turned on 'Create Shortcut' permission from the settings of my phone and now it's working.
> > Suggestion: May be it was device/OS specific so team need to work on legacy permissions I guess. Because when I clicked on Add to home screen, it didn't ask for any permission and due to that the shortcut was not creating. But, once I enabled it from Settings -> All Permissions, it's working now!
> 
> Would you mind sharing a screenshot of the Signal permissions on your device?
> My Samsung doesn't have that permission.

In App Manager -> Signal, the permissions won't be there. As you can see in below screenshot:
![Screenshot_20210112_160505](https://user-images.githubusercontent.com/52591247/104303462-21bf4700-54f0-11eb-9e16-5f505edb24b4.jpg)


But, In permission manager of your phone, you will find a permission for Create Shortcut and in that I turned on for Signal

![Screenshot_20210112_160513](https://user-images.githubusercontent.com/52591247/104303580-41566f80-54f0-11eb-8bee-3d5e3be67e38.jpg)

**Comment by AbhishekDoshi26** [comment]
> Even on Android Dev docs, at first sight, it doesn't seem to be required any permission for this:
> https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#inner-elements
> 
> So I wonder if this is a modification to Android from Vivo.

Yes that can be possible because Vivo uses Funtouch OS

**Comment by Ralms** [comment]
@AbhishekDoshi26 thanks. 
Yeah those are what Android calls "Special permissions" that are OEM specific. 
https://developer.android.com/guide/topics/permissions/overview#special

Samsung in this case didn't add that. 
I wonder how could this be added and the effort, because it would almost require to do it a per brand implementation.

**Comment by AbhishekDoshi26** [comment]
> @AbhishekDoshi26 thanks.
> Yeah those are what Android calls "Special permissions" that are OEM specific.
> https://developer.android.com/guide/topics/permissions/overview#special
> 
> Samsung in this case didn't add that.
> I wonder how could this be added and the effort, because it would almost require to do it a per brand implementation.

In Android O (API level 26) and higher, the INSTALL_SHORTCUT broadcast no longer has any effect on your app because it's a private, implicit broadcast. Instead, you should create an app shortcut by using the requestPinShortcut() method from the ShortcutManager class.

Read this in documentation and my OS version is Oreo
