### ISSUE TITLE
mi ped 4 plus. can not install  signal

### ISSUE THREAD

**Issue by ronen11** [signalapp/Signal-Android#10431]
do not support 
whte can be dun?

**Comment by letkemanpete78** [comment]
@ronen11, may I ask how you have tried installing it?

I know that there is in the Google store method, but there may be workarounds such as downloading the APK and then installing it.
You may need to enable Android developer mode and an Android File Manager to do this.
**However, untrusted APK files from the web may not be as secure or work as expected.**

**Comment by letkemanpete78** [comment]
There may be alternative ways to install this.
However, most likely your device is not running a new enough version of Android.

How to check if your device meets the minimum requirements:
In Android, you can find the version number e.g. Android 8.1. in your device.

In this file
https://github.com/signalapp/Signal-Android/blob/master/build.gradle

Look at the compile_sdk, target_sdk, and minimum_sdk lines. Then you'll need to find out what API version you get for your Android version as noted here 
https://developer.android.com/studio/releases/platforms
to see if you have the correct version.
If you don't meet the requirements, then you'll need to upgrade your devices firmware if possible.

An other option is try for an older version of Signal, which may not be as stable or as secure.

One final option is to rewrite the parts that require a higher API level to use a lower version.
