### ISSUE TITLE
Trying to join group with group link results in "Unable to get group information, please try again later"

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-Android#10436]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Users who click on a Group Link to join an existing group are unable to. The error message is: "Unable to get group information, please try again later"

Background:
- I created the group about 4 hours ago via the iOS app.
- I created a group link so that people in a WhatsApp group I'm in could move to this new Signal group.
- 7 people successfully joined
- I then attempted to change the "require admin approval for group link" setting from ON to OFF. That resulted in a "Group could not be updated." error.
- Ever since, I have been unable to edit the group settings, or manually add new members - all I get is "Group could not be updated".
![signal-2021-01-10-125328](https://user-images.githubusercontent.com/2001138/104123425-0ebb4400-5343-11eb-8ff8-c94db87e4133.png)

- Debug log from the iOS app: https://debuglogs.org/28169f9d3d56a6864416deb9e9a3e81e38844535ede75f0f636adef0e8b65aa3.zip 

### Steps to reproduce
- Be a Signal user
- Receive a Group Link
- Click on the Group Link

**Actual result:** Error message, and you don't join the group.
**Expected result:** No error message, and you join the desired group.

### Screenshots
![signal-2021-01-10-123400](https://user-images.githubusercontent.com/2001138/104123055-be42e700-5340-11eb-8c95-73b47debb549.jpeg)

### Device info
**Device:** Samsung SM-G935F
**Android version:** 8.0.0
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/faf59284f070aaed0bceb46351367b686266413f4deeaf9faf7f15885aec9cb6

**Comment by Sgn-32** [comment]
It seems that many users are currently switching. That seems to be a bit of a burden on the servers.
There are also messages that currently no groups can be created.

**Comment by xXBeekeyXx** [comment]
Does that also happen to you if you change the group picture for instance? I get a freezed loading button and then an error message. This happens when I want to create a new group, when I want to change the group picture and when other people want to join the group. I am getting the feeling that this is a major bug, as it is happening across a variety of devices (all of my family's).

Interestingly, the group WAS created and other people COULD join after a delay of a few minutes, even though the app stated to try again later.

I have not yet managed to change the profile picture though.

Can any one of you reproduce these issues?

![signal_error](https://user-images.githubusercontent.com/45722052/104124047-ca35a580-534e-11eb-894d-6c96f6922400.jpeg)

**Comment by xXBeekeyXx** [comment]
EDIT: There was a name and a picture when I clicked on the button, I just removed them for the upload.

**Comment by cperrin88** [comment]
Same issues here. Can't invite anyone to my new group and can't create a join link.

**Comment by bkqtnte10** [comment]
@Sgn-32 is there an indicator of the server usage?

could these performance-related issues be pinned on top for the time being?

Am I wrong in assuming that signal runs on AWS? Is this not scalable?

**Comment by UsmanMaqbool** [comment]
I also faced this problem today while new members are unable to join

**Comment by Sgn-32** [comment]
@bkqtnte10 there is a simple website for server status:
https://community.signalusers.org/t/signal-service-status/11320
And yes, Signal is running on AWS. Signal team working on the issues.
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/65

**Comment by i7u** [comment]
This all seems to be working now. It appears to be platform overload indeed, from the many people moving to Signal. Very exciting!

**Comment by rupeshonline** [comment]
[https://chaatsapp.com/](https://chaatsapp.com/) is whatsapp group links list website which help me out with study.,

**Comment by onlyforgamingiq** [comment]
[Discover WhatsApp group Links](https://whatsgrouplink.app)

**Comment by onlyforgamingiq** [comment]
[Join WhatsApp Group Links](http:whatsgrouplink.app)
