### ISSUE TITLE
We NEED a Seamless feature to migrate from Whatsapp !!

### ISSUE THREAD

**Issue by derei** [signalapp/Signal-Android#10435]
Although this is a feature request, it is urgently needed in order to ensure a good migration, especially considering the current WhatsApp situation.

I have researched and could not find anything consistent to help the average user to move chats from WhatsApp to Signal. Even if the migration would be limited to text messages alone, it is essential to have some sort of support, because many people use their WhatsApp for business, having critical information in their chat history.

Hoping this will receive the serious commitment and attention that it deserves, I thank you!

**Comment by C4P4E7** [comment]
And also syncing the mobile and desktop is not similar to WhatsApp level. It needs some development.

**Comment by xXBeekeyXx** [comment]
I don't think having critical Information solely in your chat history is good practice... I don't think that should be the purpose of a text messenger

**Comment by Symonen** [comment]
> I don't think having critical Information solely in your chat history is good practice... I don't think that should be the purpose of a text messenger

This is a different thing. The truth is that some people want to preserve their history, by developing this feature, making it simple and seamless will attract more users. Personally, love the signal and the values it represents but the app needs to be improved.

**Comment by Sgn-32** [comment]
The Signal community is the place for feature requests and general discussion:

https://community.signalusers.org/t/import-whatsapp-chat-history/19748
https://community.signalusers.org/t/migrate-from-whatsapp/10566
https://community.signalusers.org/t/restore-backups-from-whatsapp-threema-telegram-etc-to-signal/4896

**Comment by RaviPunarnava** [comment]
A must need feature to migrate from whatsapp backup to Signal

**Comment by derei** [comment]
> I don't think having critical Information solely in your chat history is good practice... I don't think that should be the purpose of a text messenger

critical doesn't mean bank details, but for example discussions with clients... they are critical until a certain job is done (this is one example out of many)

**Comment by derei** [comment]
> The Signal community is the place for feature requests and general discussion:
> 
> https://community.signalusers.org/t/import-whatsapp-chat-history/19748
> https://community.signalusers.org/t/migrate-from-whatsapp/10566
> https://community.signalusers.org/t/restore-backups-from-whatsapp-threema-telegram-etc-to-signal/4896

Few reasons why I posted here:
1. I already have a github account (didn't want to just make a forum account for the time being)

2. I consider it to be a more urgent issue than a community discussion. Although it is technically a feature request, not having it from the beginning is more like a bug (a bad development thinking) - if you want to win market, you must think how to facilitate a smooth transition. People are lazy, most of them value comfort and some of them simply cannot drop for example the information in old apps in order to make a clean slate transition

3. I already looked over the community discussions and is all useless and with no perspective or promise that it will be taken seriously or considered anytime soon. So, please forgive me if I don't put any faith in that.

**Comment by Genis-Sage** [comment]
hey @derei 

what you do is simply disrespectful to the signal devs
you get something for free of them, but you dont follow their simple request to not spam them by creating unneeded github issues

and regarding point 1:
you can use "log in with github" on the forum

**Comment by derei** [comment]
> hey @derei
> 
> what you do is simply disrespectful to the signal devs
> you get something for free of them, but you dont follow their simple request to not spam them by creating unneeded github issues
> 
> and regarding point 1:
> you can use "log in with github" on the forum

Thanks for letting me know about issue 1. solution
In regards to being disrespectful, I disagree... whilst I do understand the purpose of the request, I explained my reasons clearly why I considered it is needed to be addressed here. It was not arrogance, but to show this issue (especially now) is an urgent one, not a simple feature request. But you may have your opinions and I respect those.

**Comment by Ralms** [comment]
> > hey @derei
> > what you do is simply disrespectful to the signal devs
> > you get something for free of them, but you dont follow their simple request to not spam them by creating unneeded github issues
> > and regarding point 1:
> > you can use "log in with github" on the forum
> 
> Thanks for letting me know about issue 1. solution
> In regards to being disrespectful, I disagree... whilst I do understand the purpose of the request, I explained my reasons clearly why I considered it is needed to be addressed here. It was not arrogance, but to show this issue (especially now) is an urgent one, not a simple feature request. But you may have your opinions and I respect those.

You come here requesting a feature that doesn't make any sense in the first place. 
Something that is not even possible because WhatsApp forces you to use Google and Google doesn't give you the option to download the backup file. 
On top of that, one of the biggest problems out of the box is that each chat is associated with an user, so many of your chats in WhatsApp, don't even have a matching user in Signal. 

Also yes, you have been very disrespectful not only to the devs but also to the community.
You show up out of nowhere demanding something as you are entitled for it, even though you clearly haven't contributed to the project in any way. 

You called all community discussions "useless" with this comment: 
"community discussions and is all useless and with no perspective or promise that it will be taken seriously "

Then, calling the original code that powers WhatsApp and many other services "a bad development thinking" is also very ironic. 

Lastly, to answer to this "if you want to win market, you must think how to facilitate a smooth transition".
Signal is not a traditional company, Signal is not here to make money, it's a Non-Profit organization focused on privacy first.
If people want to switch, they are welcomed, if not is their decision. 
But if giving a phone number and a name not easy enough, then you are just stupid in the head.

**Comment by greyson-signal** [comment]
I think the idea of a WhatsApp import of interesting, but it raises a ton of questions. What does it look like if the conversation you imported isn't a Signal user? What if you import a group chat, but only *some* of those users are Signal users? Gets really weird, really quick. We may think about it more, but I don't see us taking action in the immediate future.
