### ISSUE TITLE
Refresh of contacts does not show network errors

### ISSUE THREAD

**Issue by bkqtnte10** [signalapp/Signal-Android#10439]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Refreshing of contacts does not work when there is no internet connection. Signal does not indicate that there is a problem with the network.

### Steps to reproduce
- set phone to airplane mode (or have no internet connection)
- refresh contacts list

**Actual result:** indicator spins for a very short time
**Expected result:** Show error "no network connection"

### Device info
**Signal version:** 5.0.8

**Comment by Abcdma** [comment]
Can I work on this issue?
