### ISSUE TITLE
Video / Audio Call :: No notification for incomming calls

### ISSUE THREAD

**Issue by rehanguha** [signalapp/Signal-Android#10430]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When there is a incoming call there is no notification and the call is missed.

### Steps to reproduce
- Open the app
- Put the app in background 
- (If someone call when the app is open then there is a notification) I did not get any call notification

**Actual result:** No notification for the incoming voice or video call.
**Expected result:** There should be a audio notification for the incoming calls.

### Screenshots

N/A

### Device info

**Device:** Samsung M30s (SM-M307F/DS)
**Android version:** Android 10 (Kernel 4.14.62-19694174)
**Signal version:** 5.0.8

### Link to debug log

N/A

**Comment by AbhishekDoshi26** [comment]
+1 even I faced this issue!
@rehanguha

**Comment by bkqtnte10** [comment]
Dupe of #7733,  #8302, #9633

**Comment by rehanguha** [comment]
> Dupe of #7733, #8302, #9633

Yup they are similar the title keywords were not specific so couldn't find it.

**Comment by szotsaki** [comment]
Could you please be so kind and close this report (since it is a duplicate)?

**Comment by rehanguha** [comment]
> Could you please be so kind and close this report (since it is a duplicate)?

Sure.
