### ISSUE TITLE
Feature Request: Using Signal without a phone number or SIM card, especially for children

### ISSUE THREAD

**Issue by stulluk** [signalapp/Signal-Android#10432]
This is not a bug, but a feature request. I couldn't find where to request for a feature. You can delete this if not in the proper location.

I searched for all issues, and couldn't find a similar request for this one.

For kids, we usually give them Android tablets / phones without a SIM card. Therefore they don't have a phone number, and they can not receive SMS for confirmation / validation.

I also don't want to use virtual/fake phone numbers.

These devices are connected to internet via WIFI.

Is there a way to support using Signal without a SIM card / phone number ?

**Comment by Sgn-32** [comment]
Hi stulluk,

there is the Signal community website for feature request and general discussion about Signal.
https://community.signalusers.org/

Some relevant threads about registration without phone number:
https://community.signalusers.org/t/registration-without-a-phone-number/2222
https://community.signalusers.org/t/usernames-lets-throw-phone-numbers-in-the-dustbin-of-history/7282
https://community.signalusers.org/t/registering-with-an-email-address/919
