### ISSUE TITLE
Profile pic not refreshed after removing contact pic.

### ISSUE THREAD

**Issue by kprikshit** [signalapp/Signal-Android#10437]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When we have added a picture to our contact for someone, the same picture is shown as profile pic in Signal app too. But when we have removed the contact picture, signal profile pic is not refreshed to show the picture which is set by the person.  

### Steps to reproduce
- look for contact with profile pic
- check profile pic for the same contact
- delete the pic from contact in your phone
- refresh the contact in signal and verify that the old contact pic is still there

**Actual result:** Old contact picture is still shown
**Expected result:** old contact picture should be removed and the actual profile pic as set by the contact should be visible

### Screenshots
NA (since this would cause sensitive info to reveal)

### Device info

**Device:** Oneplus 7T (HD1901)
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/95807d72d361a8f5d615cc6abe51f4250d16b03d5bb71c8e10aab85a54df3ed2

**Comment by kprikshit** [comment]
On the mac app, this doesn't happen. I have refreshed the cache for android app too. Still the profile pic is not shown as intended

**Comment by harishvishwakarma** [comment]
Noticed similar issue on iOS. If a contact image is set already, the Signal image is not shown. Since all my referrals are moving from WhatsApp, we expect same feature. 
Is this by design @moxie0 ? If not, I will help debug this.

**Comment by Genis-Sage** [comment]
hey @kprikshit 
this is a duplicate of #10411
so most probably it simply needs some time
perhaps because of the high amount of new users right now

@harishvishwakarma 
1) what you are asking is a behaviour change, which belongs onto the community forum
2) don't directly ping the devs, that's completely unneeded (especially as moxie does not even programm the Android client anymore)
3) your question is a duplicate of #10027

**Comment by harishvishwakarma** [comment]
@kprikshit Got it

**Comment by kprikshit** [comment]
@harishvishwakarma @Genis-Sage got it. 
Closing this. 
Looks like a server overload issue. Exception thrown in Debug logs might have been due to this only. 

Closing this issue since
