### ISSUE TITLE
Ringing tones not correctly localized

### ISSUE THREAD

**Issue by salakis** [signalapp/Signal-Android#10447]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The ringing tone in an audio call is not adapting to the country code of the dialed contact.
Assuming that I'm calling a contact with a British phone number (+44...), I still get the US ringing tone (low 440 Hz + high 480 Hz / cadence: 2 seconds on - 4 seconds off), instead of the British ringing tone (low 400 Hz + high 450 Hz / cadence: 0.4 seconds on - 0.2 seconds off - 0.4 seconds on - 2 seconds off). The same applies to other countries and regions with a 
Considering Signal's reliance on phone numbers and for the sake of localization and user familiarity, Signal should follow [Recommendation E.180/Q.35 as provided by the ITU](https://www.itu.int/rec/T-REC-E.180-199803-I/en), WhatsApp in comparison is already following this.

### Steps to reproduce
- Dial contact with a non-American phone number
- Listen to the ringing tone

**Actual result:** US ringing tone
**Expected result:** Correct local ringing tone

### Device info

**Device:** Xiaomi Mi 8
**Android version:** Android 10 (QKQ1.200909.002)
**Signal version:** 5.0.8

**Comment by greyson-signal** [comment]
Hi there, I think this is a good feature request, but we only track bugs on Github. Please checkout the [forum](https://community.signalusers.org/). Thanks!
