### ISSUE TITLE
Chat Color Bug!

### ISSUE THREAD

**Issue by yessGlory17** [signalapp/Signal-Android#10444]
When you change the color of the chat, the old messages sometimes remain in their old color.

**Comment by ayaankhan98** [comment]
> When you change the color of the chat, the old messages sometimes remain in their old color.

yes same observed on my device. for sometime some messages remain in old color but if we scroll a bit up and down things get fixed automatically.

### Expected Behaviour
Visible chat section should change immediately

**Comment by ChewTeaYeah** [comment]
I was able to reproduce this once by chance, but haven't been able to reliably reproduce it since then

**Comment by dschrempf** [comment]
The new update 5.13.8 brought a new way of managing colors. Now my messages have different colors in different groups... I didnt fiddle around any of the settings.

**Comment by UserX404** [comment]
This is a intended change and is discussed here:
https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048

**Comment by dschrempf** [comment]
Thank you!
