### ISSUE TITLE
We can't open groups

### ISSUE THREAD

**Issue by selimrecep** [signalapp/Signal-Android#10440]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't open any groups with someone or more than two people.

### Steps to reproduce
- Open Signal
- - Click "pen" icon
- Click "Create group ("Yeni Grup" in TR Language)
- Choose someone or more people
- Click the blue button on the bottom right
- Have an error like "Try again later"

**Actual result:** The app keeps asking me try again
**Expected result:** It should create the group

### Screenshots

![image](https://user-images.githubusercontent.com/16990318/104124850-1a6b3280-5364-11eb-8e7a-9ccbd0047dcb.png)

### Device info

**Device:** Samsung A7 (2017) [SM-A720F]
**Android version:** 8.0.0
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/a05e8d1d52679dec4894515ab9d6447878875ba48f31c8548e66eda959388550

Note: I have 3 friends that wants to create a group too (one of them uses iOS and other one uses Android), they get same error too. I am using app in Turkish

**Comment by bkqtnte10** [comment]
Duplicate of https://github.com/signalapp/Signal-Android/issues/10436#issuecomment-757474941

Probably server load related

**Comment by Sgn-32** [comment]
It seems that many users are currently switching. That seems to be a bit of a burden on the servers.

See also community forum:

https://community.signalusers.org/t/cant-create-groups/20348

**Comment by selimrecep** [comment]
Sorry, I saw that issue actually but I thought it was something another releated issue.

**Comment by GuruAswath** [comment]
I too have an issue I can't open new groups Group Video Calls
Probably Server Load Issue

**Comment by selimrecep** [comment]
I can open groups now. Thank you!
