### ISSUE TITLE
Broken certificate on production server?

### ISSUE THREAD

**Issue by dgtlmoon** [signalapp/Signal-Android#10442]
I was curious which address(es) the android client connects to in production, So I simply grepped the source

```
./flavors.gradle:            buildConfigField "String", "SIGNAL_URL", "\"https://textsecure-service-staging.whispersystems.org\""
./app/build.gradle:        buildConfigField "String", "SIGNAL_URL", "\"https://textsecure-service.whispersystems.org\""
./app/build.gradle:            buildConfigField "String", "SIGNAL_URL", "\"https://textsecure-service-staging.whispersystems.org\""
```

![image](https://user-images.githubusercontent.com/275001/104125836-9dd35680-5359-11eb-99b3-7316998d61da.png)

Seems to me that there's an intermediate certificate missing, but I simply do not see that in the source here the project

https://www.ssllabs.com/ssltest/analyze.html?d=textsecure%2dservice.whispersystems.org&s=13.248.212.111&hideResults=on
```
dgtlmoon@acer:/tmp/Signal-Android$ find .|grep -i cert$
./libsignal/service/src/test/resources/ias.cert
```

Am I reading this right? why don't I get an error from the android client when it's connecting?

thanks for your work!

**Comment by Nisc3d** [comment]
Does this help? https://signal.org/blog/certifiably-fine/

**Comment by dgtlmoon** [comment]
Fanastic!!!! thank you :)
