### ISSUE TITLE
Cannot update group image

### ISSUE THREAD

**Issue by rohit256** [signalapp/Signal-Android#10441]
- [ ] I have searched open and closed issues for duplicates
- [ y ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No one from the group is able to update the grp image

### Steps to reproduce
- create a grp of 2/ more people
- try updating the grp image by choosing an image from the gallery

**Actual result:** Problem setting image
**Expected result:** Image updated successfully

### Screenshots

![Screenshot_20210110-193420_Signal](https://user-images.githubusercontent.com/25497762/104125343-14814b80-537c-11eb-9805-7b6b588a5a25.jpg)

### Device info

**Device:** Samsung Note 10
**Signal version:** 5.0.8

**Comment by Sgn-32** [comment]
It seems that many users are currently switching to Signal.
That seems to be a bit of a burden on the servers.
