### ISSUE TITLE
Contacts are Not Showing Then Crash

### ISSUE THREAD

**Issue by Jatinverma0786** [signalapp/Signal-Android#10448]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When i open contacts then the will get crash on device

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** XIAOMI REDMI 9 PRIME
**Android version:** 10.0.0
**Signal version:** 5.1.4

**Comment by anirudhmpai** [comment]
![Screenshot_2021-01-10-23-27-01-768_com miui bugreport](https://user-images.githubusercontent.com/26567346/104131427-41455b00-539c-11eb-89cb-9ea768690271.jpg)

**Comment by Jatinverma0786** [comment]
now how can we solve this

**Comment by greyson-signal** [comment]
The contact problems should be resolved now (there was a server issue) and the crash should be resolve din 5.1.4. Thanks!
