### ISSUE TITLE
Error while leaving the group

### ISSUE THREAD

**Issue by C4P4E7** [signalapp/Signal-Android#10443]

**Comment by C4P4E7** [comment]
![Screenshot_2021-01-10-20-06-42-188_org.thoughtcrime.securesms.jpg](https://user-images.githubusercontent.com/73741669/104125956-fe758a00-537f-11eb-96ad-516e39e6a6d3.jpg)

**Comment by Sgn-32** [comment]
It seems that many users are currently switching to Signal.
That seems to be a bit of a burden on the servers.

**Comment by greyson-signal** [comment]
There were some server issues earlier today. Should be resolved now. Thanks!
