### ISSUE TITLE
Star message 

### ISSUE THREAD

**Issue by 1711shashank** [signalapp/Signal-Android#10445]
There are no such option of star message for important massage's

**Comment by Genis-Sage** [comment]
hey @1711shashank 
just from your short description, i guess nobody knows, what you mean

aside from that, as [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) states:
please visit the [community forum](https://community.signalusers.org/c/feature-requests) for feature requests

**Comment by 1711shashank** [comment]
> hey @1711shashank
> just from your short description, i guess nobody knows, what you mean
> 
> aside from that, as [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) states:
> please visit the [community forum](https://community.signalusers.org/c/feature-requests) for feature requests


I know its a short description, but the quite self explanatory

but still I am adding the snapshot 
![cfca14cc-cc5f-43de-8115-b861a1d9e45b](https://user-images.githubusercontent.com/34642119/104126786-865d9300-5384-11eb-8400-88fef92d5966.jpg)

**Comment by 1711shashank** [comment]
> There are no such option of star message for important massage's

Also this option is there in other chatting apps

**Comment by evrifaessa** [comment]
That would be awesome!

**Comment by UserX404** [comment]
Feature request are discussed in the Forum [https://community.signalusers.org/] and please search for similar topics before creating a new one. Github is for bugs only.

**Comment by Sgn-32** [comment]
https://community.signalusers.org/t/bookmarks-favorites-starred-messages/6004
