### ISSUE TITLE
Group creation is failing every time

### ISSUE THREAD

**Issue by rohitg00** [signalapp/Signal-Android#10455]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by rohitg00** [comment]
Every time, I'm trying to create group or add members or change name of group it's showing. Profile change: Failed

**Comment by Nisc3d** [comment]
https://twitter.com/signalapp/status/1348303100759560196

**Comment by greyson-signal** [comment]
Hi there, we were experiencing some server issues during this time -- should be good now. Thanks!
