### ISSUE TITLE
I want to suggest a new feature

### ISSUE THREAD

**Issue by kimfom01** [signalapp/Signal-Android#10450]
Due to the fact that many of your new users are those who ditched WhatsApp, I want to suggest that you should add status update feature (maybe call it something else like "moments") so that we won't miss WhatsApp 😭

**Comment by Genis-Sage** [comment]
hey @kimfom01 
sure, you can suggest features, but please at the right place

as stated in the [contributing.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) , feature request belong in the [community forum](https://community.signalusers.org/c/feature-requests)

also, your feature was requested like 10 times here on github already, and every requester was sent to the forum

so also, please search first, before open a new issue
