### ISSUE TITLE
Signal could not be started!

### ISSUE THREAD

**Issue by yessGlory17** [signalapp/Signal-Android#10458]
Upon entering and exiting, it gives "Signal could not be started" error and the application is closed in the background.

**Comment by Noah670** [comment]
Clear the app cache

**Comment by yessGlory17** [comment]
> Uygulama önbelleğini temizleyin

it does not work

**Comment by aria-blip** [comment]
Try using a vpn

**Comment by greyson-signal** [comment]
Hi there, unfortunately we can't do anything with this information. If you are able to use the app at all, please post a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports). If you can't use the app at all, you can try getting logs using [ADB](https://developer.android.com/studio/command-line/adb), although I'm aware that's a more difficult thing to do.

**Comment by ccuser44** [comment]
You nees to give more information so the issue can be adressed.
