### ISSUE TITLE
<FEATURE REQUEST> Separate sections for Signal conversations and phone SMS.

### ISSUE THREAD

**Issue by tejas-alpha** [signalapp/Signal-Android#10456]
----------------------------------------

### Bug description
If we could have separate sections for Signal conversations and phone SMS then that would be awesome. It's just a suggestion.

**Comment by Sgn-32** [comment]
Hi tejas-alpha,

there is the Signal community website for feature request and general discussion about Signal.
https://community.signalusers.org/
