### ISSUE TITLE
Add Reproducible Builds support

### ISSUE THREAD

**Issue by gautamkrishnar** [signalapp/Signal-Android#10457]
Telegram Android and iOS apps have reproducible builds. Anyone can independently verify whether the version of the app published on the play store and app store matches the release available on GitHub, any plans to add this to the signal apps?

More info: https://core.telegram.org/reproducible-builds

Community thread: https://community.signalusers.org/t/add-reproducible-builds-to-the-apps/20516

**Comment by Sgn-32** [comment]
https://github.com/signalapp/Signal-Android/blob/master/reproducible-builds/README.md

**Comment by gautamkrishnar** [comment]
@Sgn-32 Thanks for the prompt reply. We should mention this properly on the signal.org website as well so that users won't confuse it.
