### ISSUE TITLE
"Save" function causes photo being saved with wrong timestamp (Like 3 Fab 52998) 

### ISSUE THREAD

**Issue by selimrecep** [signalapp/Signal-Android#10453]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I save a photo in app to disk, the app saves photo with wrong timestamp (like it is captured in far far future).

### Steps to reproduce
- Send a photo to a friend
- Click on it to see in full size (in-app)
- Click on settings icon (three dots)
- Click save
- Confirm the dialog
- The photo is saved with wrong timestamp.

**Actual result:** The photo is saved with wrong timestamp
**Expected result:** The photo should be saved with CURRENT timestamp

### Screenshots
![Adsız](https://user-images.githubusercontent.com/16990318/104130338-2dd8c680-5381-11eb-9d59-60264791d908.png)

### Device info

**Device:** Samsung AY (2017) - SM-A720F
**Android version:** 8.0.0
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/98710b40d76ab4da9ff2875957fdce8d752b2cf57c3a0cd3e73132f85bdf2e9c

**Comment by Nisc3d** [comment]
This is a duplicate of #10142.

**Comment by Nisc3d** [comment]
A suggestion to the Signal team: As more people install Signal this bug will be reported more and more. Maybe you can merge the pull request that should fix this (mentioned in the original issue). That would be so nice.

**Comment by selimrecep** [comment]
Sorry, I have searched for this bug but finding the bug in issues tab isn't that easy when a lot of different names can fit there. I am closing the issue and move to #10142
