### ISSUE TITLE
Unable to add this text to group name

### ISSUE THREAD

**Issue by vairam-svs** [signalapp/Signal-Android#10464]
Unable to add this text to group name after I create the group: "வருத்தப்படாத வாலிபர் சங்கம்"

- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- create a group with small number of texts as name
- navigate to group settings
- try to edit the group name as follows வருத்தப்பட (unable to type past ட even though in Tamil it is one character டா , it treats as two and it allows to enter only 9 characters) 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Unable to enter more than 10 characters

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Able to enter more than 10 characters: வருத்தப்படாத வாலிபர் சங்கம்
### Device info

**Device:** Samsung 9 plus
**Android version:** latest
**Signal version:** 5.0.8

**Comment by vairam-svs** [comment]
Interestingly the same text is possible to be set when creating a new group

**Comment by Harish-Dhoni** [comment]
Audit log shows the name of the creator 😂

**Comment by vairam-svs** [comment]
I have signed my CLA today. Please show me the location where the documentation that shows how the edit view of Group Title code is, so that I can submit a PR to accommodate change

Also, Do you have a reason that you don't allow to have more than 10 characters in title while editing but not while creating?

**Comment by rprabu1984** [comment]
Same issue here.. There is a character limitation when using 'Tamil' language for group name

**Comment by rprabu1984** [comment]
**Steps to reproduce**

- Create a group 
- Rename it to 'அமெரிக்கா தமிழ் சங்கம்'

**Actual result:**
அமெரிக்கா த
Unable to enter more than 10 characters

**Expected result:**
Group should be named as 'அமெரிக்கா தமிழ் சங்கம்'

Device info: samsung SM-G950U1 (dreamqlteue)
Android version: 9 (G950U1UES8DTJ1, PPR1.180610.011.G950U1UES8DTJ1)
Signal version: 5.0.8
Signal package: org.thoughtcrime.securesms (doDiFGKPO1r)
Registration lock: true
Locale: en_US

**Debug Logs:**
[https://debuglogs.org/e3f042c42e7490ff5f68d2ed062162aae26cc13f5911b93c918af32370ae6a7a](url)

**Comment by Jsnkenk** [comment]
Facing the same issue for Tamil characters. Character Length limitation when using தமிழ் (Tamil).

**Comment by vairam-svs** [comment]
Signal 5.3.7.1 fixes this issue @Jsnkenk @rprabu1984
