### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by azim254** [signalapp/Signal-Android#10465]
Feature suggestions

- add status stories like  WhatsApp and instagram
- star important messages 
-  chat wallpapers
- swipe left to tag and reply message 
- Disable group members to only admin only can chat and edit group profile

if also a roadmap could be provided it would be nice

**Comment by GuruAswath** [comment]
Yeah I vote this Feautures too

**Comment by Rixon46** [comment]
Yea i vote too

**Comment by daimonsix** [comment]
I vote too :)

**Comment by ayaankhan98** [comment]
Thanks for your suggestions. But please suggest features at right place, Kindly go through the `Contribution.md` you can suggest features at https://community.signalusers.org/
also make sure issues are not duplicate.

Moreover
- Swip left to tag messge is already their in Android version
- only admin allow to edit group profile is already their in Android version

Other features listed above seems duplicate to me, as there are a lot of posts about them in community forum.

**Comment by greyson-signal** [comment]
Hi there, thank you for the suggestions, but please discuss feature requests on the [forum](https://community.signalusers.org/). We only track bugs on Github. Thanks!

**Comment by azim254** [comment]
thanks for the feedback @ayaankhan98
