### ISSUE TITLE
Create feature parity between Android and iOS apps

### ISSUE THREAD

**Issue by vairam-svs** [signalapp/Signal-Android#10463]
Create feature parity between Android and iOS apps when a feature is released
There can be as many number of builds that will fix issues, but the Semantic Version should mean all features in Android and iOS are same

Example: Unable to change group name in the iOS app

- [ x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by greyson-signal** [comment]
You can definitely change the group name in both the Android and iOS apps, provided you have permission to do so in the group.
