### ISSUE TITLE
Unread messages look same as read ones in UI

### ISSUE THREAD

**Issue by vpfaiz** [signalapp/Signal-Android#10469]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The UI does not make spotting the Unread messages from the read messages easy. The color / font /size / bold for both read and unread look almost same.. Can we change this?

### Steps to reproduce
- Just open the mobile app
- look at read and unread messages

**Actual result:** They look almost same
**Expected result:** They look different, with read messages looking less flashy or grayed out

### Screenshots
Just look at the screen shot at signal.org

### Device info
Pixel 3a
**Device:** Google
**Android version:** 11
**Signal version:** 5.0.5

### Link to debug log

N/A

**Comment by greyson-signal** [comment]
We also put an unread badge on the icons of chats with unread messages. We use Github for bug tracking. If you'd like to discuss features, please use the [forum](https://community.signalusers.org/). Thanks!
