### ISSUE TITLE
Video Playback does not prevent screen timeout.

### ISSUE THREAD

**Issue by zeroprobe** [signalapp/Signal-Android#10461]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When playing videos sent in messages, if my Android screen timeout is 30 seconds, after 30 seconds, even if watching a video the screen will timeout.

### Steps to reproduce
- Send a Video attachment longer than current Android screen timeout
- Play the video

**Actual result:** The screen will timeout during the video playback
**Expected result:** Video playback takes preference and overrides screen timeout

### Device info

**Device:** - Samsung Galaxy S10
**Android version:** - 10.0
**Signal version:** 5.0.8

**Comment by mcrajah** [comment]
Same issue on LG V30, running Android 9 and signal 5.3.7
