### ISSUE TITLE
Group chat bubbles weirdly color coded (Android) ! 

### ISSUE THREAD

**Issue by karangupta25** [signalapp/Signal-Android#10460]
Chat bubbles in a group chat are by default weirdly colour coded which can only be altered by specifically going to that person's chat box and changing the colour from over there. It would be great if a group followed a specific colour pallet or maybe provided an option in that group itself via a layover or something.

**Comment by Nisc3d** [comment]
Please use the community forum for feature requests:
https://community.signalusers.org
Thanks!
