### ISSUE TITLE
Unable to choose Tamil (ta) as a translation language while joining team in transifex

### ISSUE THREAD

**Issue by vairam-svs** [signalapp/Signal-Android#10467]
unable to choose Tamil (ta) as language 

https://www.transifex.com/signalapp/signal-android/

- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
 - signed up with transifex,
 - selected signal android and chose join team
 -  when prompted with available language, Tamil or Tamil (ta) does not provide the option to choose that language
 - 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Genis-Sage** [comment]
hey @vairam-svs 
i was just able to please a join request to the tamil team:
![image](https://user-images.githubusercontent.com/6865155/104164251-ef322300-53f7-11eb-820b-a66921473ca4.png)

I simply entered "ta"

now, after I requested it, i am not able to find it anymore

can it be, that you already requested to join the team?

https://www.transifex.com/signalapp/teams/90238/ta/
