### ISSUE TITLE
Contact joined Signal notification not working

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#10477]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Lately I've checked my Signal contacts and noted there are quite a few new contacts available however I didn't seen a notification that a contact joined Signal. In my notification settings I've enabled the 'Contact joined Signal' setting. This used to work. The last notification of a new contact I've received dates from April last year so back then it still worked. Since I don't know when those contacts were added I don't think a debug log is useful. (might been weeks ago) What I did notice is that for the contacts that did trigger a notification the conversation shows 'x is on Signal' for the new contacts that didn't trigger the notification there was no such message. Note this is mentioned by more users on https://community.signalusers.org/t/why-are-users-who-have-my-phone-number-in-their-contacts-notified-that-ive-joined-signal/1320/376

### Steps to reproduce

**Actual result:** No notification was given when a new Signal contact was added
**Expected result:** A notification that 'x has joined Signal' was given once x is in the Signal contact list

### Device info

**Device:** Samsung S9
**Android version:** 8
**Signal version:** 5.1.4

**Comment by GuruAswath** [comment]
Refresh is not Working

**Comment by Lion-box** [comment]
> Refresh is not Working

Quite a bit of server overload going on in this last few days and this is sometimes delaying contact discovery.
Please be patient and they will appear without  refreshing the list again and again (which generates additional load on an already quite busy server).
Signal is adding new servers as fast as they possibly can, so again be patient

**Comment by Herohtar** [comment]
This has been broken since at least 2020-12-17, because I added a coworker who was already on Signal to my phone's contact list on that date and never received the notification, even though the option was enabled and they showed as a valid Signal contact. I'm not sure how much longer before then it was broken though.

**Comment by bme13** [comment]
Since I've received a couple of notifications for new contacts joining (not enough of course ;-) ) I think this is fixed so I guess it can be closed.
