### ISSUE TITLE
Adding me to a group

### ISSUE THREAD

**Issue by TechieNK** [signalapp/Signal-Android#10475]
Whoever has my contact, can add me to the group. Please, add a privacy feature for the user to restrict this one with options like everyone, contacts or nobody.

**Comment by ninjan3rd** [comment]
Agree to this,a great privacy feature !

**Comment by ccuser44** [comment]
This is a feature request. Please send it here https://community.signalusers.org/c/feature-requests/17 and close the issue.

**Comment by SureshCBE** [comment]
Yes this feature is necessary for private messanger app.
