### ISSUE TITLE
 public static final long BUILD_TIMESTAMP = Microsoft Windows [Version 10.0.18363.1256]       (c) 2019 Microsoft Corporation. All rights reserved.              C:\Users\as660\AndroidStudioProjects\Signal-Android-master\app>000L;

### ISSUE THREAD

**Issue by ashutoshlovpry** [signalapp/Signal-Android#10474]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Genis-Sage** [comment]
hey @ashutoshlovpry 
with the current state of you github issue, nobody knows, what your issue is
just a title is not enough

if you need development or building support, please visit the [community forum](https://community.signalusers.org/)
