### ISSUE TITLE
Problem with making channel like structure of groups, There is no feature that can disable everyone to chat in group beside only admin can have rights to send message.

### ISSUE THREAD

**Issue by rohitg00** [signalapp/Signal-Android#10470]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Lion-box** [comment]
This is a feature request, not a bug report.
Please submit it in the appropriate section of the [community forum](https://community.signalusers.org/c/feature-requests/android-feature-requests/18)
And please, as this has been already requested, do a search and your like to the existing topic without starting a duplicate one.
