### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by ccuser44** [signalapp/Signal-Android#10478]
I know this is a feature request but this is github related. But anywyas a SECURITY.md would be necessary for something like Signal.

**Comment by grandchild** [comment]
What is commonly in a SECURITY.md? Information about the protocol? Then perhaps a link in the README to https://signal.org/docs/ would be sufficient?

**Comment by ccuser44** [comment]
Github has a security.md template automaticly. It has info like how to report security vulns. What versions are supported for security etc.
