### ISSUE TITLE
Tamil translation is not complete

### ISSUE THREAD

**Issue by vairam-svs** [signalapp/Signal-Android#10472]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
All display text is not translated to Tamil
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
expected results will be submitted as a PR since it is too many to point out

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Ashok314** [comment]
can you share more info and a screenshot? 
It is not an issue on my end.
