### ISSUE TITLE
Please add status feature 

### ISSUE THREAD

**Issue by jak3456** [signalapp/Signal-Android#10488]
Feature request.

**Comment by wapfalls** [comment]
+1 to this. This is that one feature missing in signal that basic users are seeing as hurdle when I suggest them to switch over to Signal from other messaging apps like Whatsapp.

**Comment by grandchild** [comment]
This is a feature request. Please discuss these in the [Signal Forums](https://community.signalusers.org/).

Also, please don't delete the issue template, it mentions this exact preference about where to file feature requests.

Thank you!
