### ISSUE TITLE
Background wallpapers like Whatsapp

### ISSUE THREAD

**Issue by RaviMauryaHootowl** [signalapp/Signal-Android#10480]
Add feature to add a background wallpaper like WhatsApp.

**Comment by Genis-Sage** [comment]
hey @RaviMauryaHootowl 

as stated in the [contributing.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) and in the issue template, feature request are handled on the [community forum](https://community.signalusers.org/c/feature-requests)
