### ISSUE TITLE
No search result overlaps with empty inbox placeholder text

### ISSUE THREAD

**Issue by thiagoschreck** [signalapp/Signal-Android#10485]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When searching for messages with an empty inbox, the "No results were found for << Something >>" overlaps with the placeholder text for empty inbox.

### Steps to reproduce
- Have an empty inbox.
- Type something in the search bar.

**Actual result:** No results found text overlaps with empty inbox placeholder text.

**Expected result:** No result found text should not overlap with empty inbox placeholder text. It probably should either appear elsewehere or maybe move the empty inbox placeholder text.

### Screenshots
![Screenshot_2021-01-11-08-24-59-877_org thoughtcrime securesms](https://user-images.githubusercontent.com/56611782/104177099-0583b300-53e7-11eb-8f0b-164110613156.jpg)
![Screenshot_2021-01-11-08-15-28-760_org thoughtcrime securesms](https://user-images.githubusercontent.com/56611782/104177117-0ddbee00-53e7-11eb-86ae-8e19b4eac38a.jpg)

### Device info
**Device:** Xiaomi Redmi 8 Pro
**Android version:** 10 QKQ1.19014.001
**Signal version:** 5.0.8

### Link to debug log
N/A

**Comment by Dayakargoud** [comment]
Yes. This is happening when there is no chats available example: after Installing Signal for first time then start searching something in search bar the place holdertext and search results is overlapping.

**Comment by ankit167** [comment]
Is this issue still valid? I tried reproducing the issue. I do not see any overlap.

![Screenshot_20210501-124217.jpg](https://user-images.githubusercontent.com/13795085/116774549-efbff980-aa7a-11eb-94d1-3cee1b7ffe7c.jpg)

**Comment by Dayakargoud** [comment]
This issue was in previous version of the signal having text under the image but it's looks signal removed that image so there is no overlapping issue.

**Comment by ankit167** [comment]
Sure. We can close the issue and the PR in that case.

**Comment by Dayakargoud** [comment]
Yes close this issue

**Comment by thiagoschreck** [comment]
Closed!
