### ISSUE TITLE
Self deleting messages should be styled according to chat color when viewed.

### ISSUE THREAD

**Issue by mathis-m** [signalapp/Signal-Android#10489]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Self deleting messages(or pictures that only can be viewed once) are colorless instead of respecting the chat color after view.

### Steps to reproduce
- Open Signal
- Receive self deleting message
- Open chat
- View picture
- Exit picture

**Actual result:** see background color of self deleting message is colorless, foreground color is black
**Expected result:** background color should be chat color, foreground color should be white.
### Screenshots

![WhatsApp Image 2021-01-11 at 13 38 40](https://user-images.githubusercontent.com/11584315/104184271-793bb500-5413-11eb-9f15-e9ad79f0cb49.jpeg)

### Device info

**Device:** OnePlus 6
**Android version:** 10
**Signal version:** 5.0.8

**Comment by grandchild** [comment]
I am pretty sure, this is a conscious design choice. Which would make this a feature request. Please post these in the [Signal Forums](https://community.signalusers.org/). Thank you!

**Comment by mathis-m** [comment]
Alright! @grandchild Thanks for the response I will do so and close this issue.
