### ISSUE TITLE
[Request] Allowing creating sticker packs in mobile and add a favorites section

### ISSUE THREAD

**Issue by pallupz** [signalapp/Signal-Android#10490]
1. Not everyone has a laptop to create sticker packs - especially in developing countries. It would be great if this option could be brought to mobile as well
2. Kindly add a favorites tab for stickers as well. It would help people curate their stickers instead of just downloading whole packs.

**Comment by grandchild** [comment]
This sounds like a feature request. Please discuss these in the [Signal Forums](https://community.signalusers.org/).

Also, please don't delete the issue template, it mentions the exact preference about where to file feature requests.

Thank you!
