### ISSUE TITLE
Deleted account still displays in group members

### ISSUE THREAD

**Issue by ajayshinde1993** [signalapp/Signal-Android#10497]
**Summary:** Deleted account displays in the group

**Steps to reproduce**
1. Create a new group or join an existing group.
2. Join the group.
3. Delete account.

**Actual result:**
You will notice that even if you have deleted the account it still displays in the group members,

**Expected result:**
Once the user deletes the account he should automatically get removed from the group

**Comment by Sgn-32** [comment]
See community forum for details why user isn't removed from groups:

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-0-release/18811/135

**Comment by NisJorgensen** [comment]
I just discovered that some 50+ member groups I am part of have several of these users, including some admins.

The rationale for not removing these users seems wrong. The user is in fact leaving the group (and Signal). If other people want to see that people are leaving the group, they should be notified. If they DON'T want to see this, we should give them the option to ignore the leave messages. 
 
If we decide that users should never be notified about users leaving groups in this way, we should add a "remove without notifications" option.

**Comment by includesec-erik** [comment]
I came here seeking to see if this was reported. I agree this is an annoying issue that Signal UI team should address, I'm seeing it in groups I'm in. Having "Deleted User" present as admin and group members adds no value and is confusing. This thread doesn't help justify it IMHO: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-0-release/18811/147

CC @alex-signal @cody-signal @mtang-signal 

Either give admins the option to control this in some way, or just have a user's unregistered Signal user automatically unjoin all groups they're in.
