### ISSUE TITLE
Last Seen

### ISSUE THREAD

**Issue by anishkr** [signalapp/Signal-Android#10496]
### Bug description
 I am not able seen last seen option and if users is online or not. And I am facing type indicator

**Comment by williamspacefire** [comment]
I think it's not a bug, the idea of the app is to be secure and private, I don't think it's cool if they log every time you are online and last seen

**Comment by bme13** [comment]
Hi @anishkr and welcome,
Last seen functionality is not available in Signal. If you like it you can support the feature request in the community forum. See https://community.signalusers.org/t/last-seen-indicator/4375/45.
Don't know what you mean by 'And I am facing typing indicator'.

**Comment by anishkr** [comment]
@bme13 I am not able to see typing indicator. If some one is trying to reply for messages, its not showing(three dotts).

**Comment by bme13** [comment]
Are typing indicators enabled in the settings (settings->privacy->typing indicators) for both you and your communication partner? Are you using Signal for Signal messages or unsecure sms?

**Comment by UserX404** [comment]
@anishkr If your partner has switched off this setting you are not able to see. This is the same functionality as read receipt. Both have to enebled it.
