### ISSUE TITLE
App getting crash in 5.1.4 version when click on pencil button for Contacts Check

### ISSUE THREAD

**Issue by Jatinverma0786** [signalapp/Signal-Android#10494]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App getting crash in 5.1.4 version when i click on pencil button it load and get crashed i think its a error of code not in server connection.i am using signal contact directory ( not using my own server )

### Device info
**Device:** Xiaomi Redmi 9 Prime
**Android version:** 10.0.0
**Signal version:** 5.1.4

**Comment by Nisc3d** [comment]
Can you share a debug log?

**Comment by Jatinverma0786** [comment]
> Can you share a debug log?

![Screenshot_2021-01-11-03-46-29-577_com miui bugreport](https://user-images.githubusercontent.com/68986290/104197402-fd5d5f00-544a-11eb-8aae-554dc2e32d45.jpg)
![Screenshot_2021-01-11-03-46-25-197_com miui bugreport](https://user-images.githubusercontent.com/68986290/104197408-00f0e600-544b-11eb-933c-445d581d06a8.jpg)

**Comment by Sgn-32** [comment]
https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by greyson-signal** [comment]
What is com.WhatsIn? Is it some fork of Signal? There's some conflict happening with adding accounts to the system.

**Comment by Jatinverma0786** [comment]
> What is com.WhatsIn? Is it some fork of Signal? There's some conflict happening with adding accounts to the system.

Yeah com.WhatsIN is Fork of Signal and Please Tell me How can i solve this Issue

**Comment by grandchild** [comment]
@Jatinverma0786 Forks are not supported here, you'd have to file an issue with the fork.

**Comment by greyson-signal** [comment]
@Jatinverma0786 Yeah, so the fork screwed up their forking :) They need to make sure to choose their own account info. See `DirectoryHelper#getOrCreateSystemAccount()`. Nothing you can do to fix things in the app interface.
