### ISSUE TITLE
Trouble with incoming messages insecure messages from one contact

### ISSUE THREAD

**Issue by rockafellershank** [signalapp/Signal-Android#10498]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I upgraded my phone and reinstalled signal. For one contact (my wife, so it's an important one) outgoing messages are delivered to her but the incoming responses from her are not. If i switch back to the default android messenger the messages will appear in that app. She's never had a signal account and there are no issues with other contacts. They are standard insecure SMS messages.

### Steps to reproduce
-Message is sent to me
-Message never arrives in signal
-If I switch back to the default android messenger the messages from this one contact are delivered in the native android app.

**Actual result:** I get the incoming messages
**Expected result:** Signal doesn't process the incoming messages from one contact but if I switch back to the default android messenger the messages come through.

### Device info
**Device:** Pixel 4a 5G
**Android version:** 11
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/44c6d67a996a2ea57221cb2cbe40e94e29a5e38b8cffa5be6b3c84d5288402a4

**Comment by Sgn-32** [comment]
Can you please send a SMS to your wife and try get a SMS from your wife's phone and another third phone.
Please post then a new debug log with the time of sending and receiving the 3 SMS.

**Comment by Rupersman** [comment]
Turn off chat features in the default Messages app. This was the issue for me for any contact who used the default android Messages app from Google. It should fix your problem if you had it enabled.

**Comment by rockafellershank** [comment]
> Turn off chat features in the default Messages app. This was the issue for me for any contact who used the default android Messages app from Google. It should fix your problem if you had it enabled.

That solved it, was driving me crazy and I didn't see this posted anywhere else. Thank you!
