### ISSUE TITLE
 SMS import running twice resulting in duplicates

### ISSUE THREAD

**Issue by erdnaxeli** [signalapp/Signal-Android#10492]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is possible to run the import twice, resulting in messages being duplicated.

### Steps to reproduce
- open a fresh signal, create an account
- the app ask if we want to use it as default for sms, accept
- the app ask if we want to import the existing SMS, accept
- open your previous sms app which should ask you if you want to use it as default (or change it in the parameters)
- open signal back : the app ask if we want to import the existing SMS, accept

**Actual result:** the SMS are imported twice
**Expected result:** Do not ask aout importing SMS when there is already a running import.

### Device info

**Device:** Moto G5 Plus
**Android version:** 8.1.0
**Signal version:** 5.0.8

**Comment by SpandanBasu** [comment]
Yes, it's true, Saw the bug. Can I please work on this issue? I want to solve it. Please assign this task to me

**Comment by UserX404** [comment]
It has been removed. Sms import isn't suported anymore.
You can try [johanw666‘s fork](https://github.com/johanw666/Signal-Android/releases), import, backup, uninstall, install signal, restore backup.
