### ISSUE TITLE
Doesn't receive flash SMS when no system SMS app is installed.

### ISSUE THREAD

**Issue by steve77** [signalapp/Signal-Android#105]
rooted phone (tmobile mytouch slide 4G)  and deleted default messaging app, replaced with text secure, however sometimes certain automated SMS (such as from bank (chase) / google 2 step authentication) aren't received for some reason. Is there a way to force the app (make system app) to take control / manage the SMS database? Or is this a bug?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
