### ISSUE TITLE
Make lock menu always exist even when encryption has not been established yet

### ISSUE THREAD

**Issue by landry314** [signalapp/Signal-Android#1050]
when i dont have a key for a contact then the lock menu does not appear when i select them with the plus sign to compose a new message so i can not initiate secure communications. i need to send them plain text then have them initiate in return. this is less efficient than letting me straight off initiate. if i know someone has textsecure on their phone then i should be able to send a key request off the bat, like i could in textsecure version 1. it is cleaner this way.

if they dont have textsecure then there is a wasted request but so what? you could add something that says "this user is trying to establish encrypted communications using textsecure. to communicate privately, please download textsecure from the play store." then you are promoting textsecure. i remind you are am talking about using the lock menu to manually start a secure session, not to spam everyone, that wouldnt be right.

Adium for Mac OS does exactly what i am talking about with their OTR system.

**Comment by landry314** [comment]
still this is a big issue. today i got a new phone and because textsecure has been so buggy not receiving messages for me and since you can no longer export the keys cleanly (i could root navigate and move the "files" folder but i highly doubt that would be clean) i decided to start fresh with a new install and then redo all the keys.

i had to text users and tell them to end the session and to start a new one. if they didnt end the session then i could not start a new one and their texts would all be for non-existent sessions. most of them could do this but a few were like "i dont see the lock menu" and one of them figured out it was because he was using PUSH. if he disabled push then the menu appeared.

i understand why you make the lock disappear. if everyone were using push then there would be no need for this menu but by removing it for people using push you are assuming that everyone they know is also using push which is NOT TRUE. you are disabling an important feature due to a false assumption. i do not have a data plan and i do not use push but i still use textsecure a lot. you should enable the menu all the time in case one end of the communication is not using push.

am i right here, come on!! :-)

**Comment by moxie0** [comment]
The push user didn't have to do anything, it would have worked fine with no action.  Only the SMS users would have needed to do something, which is one of the many reasons why we're planning to eliminate encrypted SMS.

**Comment by landry314** [comment]
how could textsecure eliminate the basis of its existence? it was created for encrypted sms. for a while, data users have been able to use a variety of encrypted IM apps if they wanted. the reason i got into textsecure was for encrypted SMS. if you switch to only the data channel you are eliminating many people: people without data, people without google apps, people who have unlimited text but not unlimited data, people in areas that have a strong cell signal but weak or no data access... you really think people wont care about eliminating sms?
