### ISSUE TITLE
Wrong translation in French version

### ISSUE THREAD

**Issue by jsspc** [signalapp/Signal-Android#10508]
### Bug description
The message "Invite your friends" in the French version is spelled wrong: instead of writing "plus ça devient intéréessant", you should spell it "plus ça devient intéressant".

### Steps to reproduce
Using Signal in French.

### Device info

**Device:** Android A5 2017

**Comment by Sgn-32** [comment]
Hi jsspc,

the strings of Signal are translated on transifex.

https://www.transifex.com/signalapp/signal-android/language/fr/

**Comment by jsspc** [comment]
Nice to know! The link you sent is unavailable to me, from what I can see French is not part of the team you can request to join anymore. But if you can change it feel free to :)

**Comment by inzkhan** [comment]
Thanks for the correction. I will send a pull request.

**Comment by AO-LocLab** [comment]
Thank you for bringing this to our attention. The correction has be made in Transifex.

All translations should come from Transifex, NOT from GitHub pull request.

**Comment by inzkhan** [comment]
@AO-LocLab  Thanks .I got it.

**Comment by AO-LocLab** [comment]
@inzkhan I’m not sure what you mean by "I got it".
As written previously, the correction has been made in Transifex and will now be automatically be pulled into GitHub, the normal procedure.
Let me know if I can help further.
