### ISSUE TITLE
Error retrieving contacts, check your network connection

### ISSUE THREAD

**Issue by physx2494** [signalapp/Signal-Android#10503]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to synchronize contacts on the first setup itself. 

### Steps to reproduce
- Signup for Signal by installing via Google Play Store
- Allow permissions for Telephone, Contacts, Storage, SMS
- Make Signal the default for SMS/MMS
- Click on compose icon
- Wait for contacts to show up

**Actual result:** Toast message: **Error retrieving contacts, check your network connection**
**Expected result:** Contacts that are available on Signal and other invitable contacts must appear

### Screenshots

![image](https://user-images.githubusercontent.com/4197707/104214054-01927800-545d-11eb-9fcc-5ddee3def90b.png)

### Device info

**Device:** samsung SM-M515F
**Android version:** 10 (M515FXXU1BTK4, QP1A.190711.020.M515FXXU1BTK4)
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/7dbaa4631cac9a5c78e41c632652610e68339a461a845526d85dbea957ebb8ef

### Additional Description

I've noticed some interesting logs under **LOGGER** head. Maybe that'll give someone a kick start in debugging.

> ========= LOGGER ==========
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: null
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: Error type: TOO_LONG. The string supplied is too long to be a phone number.
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3258)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3046)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3036)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.phonenumbers.PhoneNumberFormatter.format(PhoneNumberFormatter.java:142)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.contacts.ContactAccessor.getAllContactsWithNumbers(ContactAccessor.java:80)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:101)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:436)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:422)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
5.0.8 2021-01-11 22:19:12.874 IST W PhoneNumberFormatter: 	at java.lang.Thread.run(Thread.java:919)
01-11 22:18:31.428 27124 27124 I V...@... ViewPostIme pointer 0
01-11 22:18:31.459 27124 27124 I V...@... ViewPostIme pointer 1
01-11 22:18:31.468 27124 31008 V Cursor  : Filling cursor window with start position:0 required position:0
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: null
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: Error type: INVALID_COUNTRY_CODE. Could not interpret numbers after plus-sign.
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3207)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3046)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3036)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.phonenumbers.PhoneNumberFormatter.format(PhoneNumberFormatter.java:142)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.contacts.ContactAccessor.getAllContactsWithNumbers(ContactAccessor.java:80)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:101)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:436)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$3.doInBackground(ContactSelectionListFragment.java:422)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: 	at java.lang.Thread.run(Thread.java:919)
01-11 22:18:31.574 27124 31008 I chatty  : uid=10307(org.thoughtcrime.securesms) identical 1 line
01-11 22:18:31.574 27124 31008 W PhoneNumberFormatter: null

- The above set of lines, repeat at least 100 times.
- Contacts are stored and synchronised via Google account
- There are exactly 4934 contacts as reported from contacts.google.com
- WhatsApp works perfectly though with the same set of contacts
- I believe this toast message is a catch all notification for any unknown bugs

**Comment by mneiger** [comment]
Same here. but Signal is not the default SMS app.
I also have around 4k contacts.

**Comment by am242** [comment]
Same bug on my device with 4K contacts
