### ISSUE TITLE
Audio message icon is small,so that affect to user experience

### ISSUE THREAD

**Issue by Ajnash-ibn-umer** [signalapp/Signal-Android#10504]
audio message button in bottom panel is very small. i think if increase the size of this button, then that useful for easy to access 
![sc](https://user-images.githubusercontent.com/62911231/104290783-c5a0f680-54e0-11eb-9354-c9bd15d689d0.png)

**Comment by MahmoudMabrok** [comment]
@ajnash-aju 
please attach a screenshot so we can figure out it

**Comment by PrajjwalDatir** [comment]
Please provide the description. @ajnash-aju 

You can provide description by answering following Questions
- Where should be the audio message icon in your opinion?
- What should be the size of icon?
- please provide screenshots

Thank you

**Comment by ero55** [comment]
I have similar issue with the audio message button. As you can see on the screenshot I use the swipe navigation buttons of my samsung device. While using the voice message button it happens very often that a little movement triggers the back event. I would suggest to switch the + plus button with the voice message button and/or disable the "back" navigation event, while the voice recording is pressed and hold. 
![20210327_121508](https://user-images.githubusercontent.com/81469046/112719118-65263080-8ef7-11eb-8b56-2bc48fc67eab.jpg)
