### ISSUE TITLE
No ringtone/notification during group call

### ISSUE THREAD

**Issue by AmoghM** [signalapp/Signal-Android#10501]
Whenever a group call is initiated, the group members don't receive the call notification. It works perfectly on a 1-1 call but not in a group.

**Comment by bme13** [comment]
Hi @AmoghM and welcome,
Currently there is no ringtone for group calls although you should receive a notification in the group. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-0-release/18811/222 for a related discussion about it. Group calls are relatively new to Signal so I assume this will be added. You can always create a feature request for it on the forum if it's not there already.

**Comment by TomaszWieczorek-Jeppesen** [comment]
Any info about when this will be added. I cannot get rid of WhatsApp until this is fixed/implemented.

**Comment by TomaszWieczorek-Jeppesen** [comment]
Any info about when this will be added. I cannot get rid of WhatsApp until this is fixed/implemented.

**Comment by AsamK** [comment]
In the near future there will be optional ringing for group calls: db7272730ea6510285acb82b318d32e78b11e12c
