### ISSUE TITLE
Better Dark Mode

### ISSUE THREAD

**Issue by Sureshjh** [signalapp/Signal-Android#10502]
The interface is not pitch black, it's kind of grayish. It would be lot better if anyone can make it pitch black, so that it is comfortable for our yes.

**Comment by grandchild** [comment]
Using a dark gray background is [generally recommended](https://material.io/design/color/dark-theme.html#properties) over pure black for dark theme backgrounds.

The dark-theme background color was picked consciously like this. Which makes this is a feature request, and please discuss it in the [Signal Forums](https://community.signalusers.org/).

Also, please don't delete the issue template.
