### ISSUE TITLE
Some Chat Bubbles have no user image

### ISSUE THREAD

**Issue by marcodenic** [signalapp/Signal-Android#10507]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Chat bubble heads don't show the image they should do.

### Steps to reproduce
Not sure, seems random. Some contacts have images, some don't. Unsure if it's related to contacts who set their own image and contacts who have an image set on-device in my contacts. Either way it's not right.

**Actual result:** User has no image in the chat bubble, only a letter.
**Expected result:** Show the correct user image.

### Device info

**Device:** Pixel 4
**Android version:** 11
**Signal version:** 5.1.1

### Link to debug log
N/A

**Comment by marcodenic** [comment]
just to add to this..  how are the chat head coulors selected?

why is the chat bubble blueish? shouldn't it match the selected chat colour (purple) at the very least?

**Comment by aj-34719** [comment]
Can i fix it
