### ISSUE TITLE
No alerts/notifications/rings received for group video calls

### ISSUE THREAD

**Issue by krishnav888** [signalapp/Signal-Android#10513]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal for Android. Group with 3 members. When a group video call is initiated by 1 person, the other 2 do not receive any alert/notification/ring/etc. 

One to one phone calls work fine.

### Steps to reproduce
- Create a group
- Add 3 members to group
- Initiate video call to group members
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
No alert/notification/rings/sounds are received by the other 2 members of the group to tell them that one of the 3 people is trying to call them.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
When a group video call is initiated, the other 2 members would receive a notification/alert/ring/something to tell them that a member of the group is trying to initiate a video call with them.

### Device info

**Device:** Samsung S10e
**Android version:** 10
**Signal version:** 5.1.1

### Link to debug log

https://debuglogs.org/4939a8ef224d5f97a274d133dd934fda8393314e6e46c439af578cb04e4faaa3

**Comment by krishnav888** [comment]
This issue is still relevant. I've updated to the latest version on Android and I still see this problem with call.

**Comment by greyson-signal** [comment]
Are the other users not receiving a notification *at all*? We don't actively ring devices for group calls today, but they should get a notification that a group call is happening. If not, could you get a log from one of the receivers?

**Comment by KruyKaze** [comment]
Hello @greyson-signal , can you share the reasoning behind Signal not ringing group participants when a call is started?
Thank you!

**Comment by greyson-signal** [comment]
The feature is built on Android, but hasn't been implemented yet on all of the clients for various scheduling reasons. But you'll have it in the not-to-distant future :)

**Comment by u32i64** [comment]
It seems there is a slightly newer duplicate issue with the same content: #10514. Although it has more comments than this one, so perhaps this one should be closed instead.

**Comment by cody-signal** [comment]
#10514

**Comment by Meteor0id** [comment]
The strings in Dekstop would need to be updated for that as well since they now speak of "will be notified". While they are at it I hope they rewrite those strings to future time rather than present time since the notifying (or ringing) only happens once you continue past the pre-call screen.
