### ISSUE TITLE
Migrating codebase to Kotlin for multiple reasons and accepting contributions

### ISSUE THREAD

**Issue by aditmodhvadia** [signalapp/Signal-Android#10517]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Feature Request
Describe here the issue that you are experiencing.
Request fort migration to Kotlin and accepting Pull requests for it.

**Comment by Tursko** [comment]
This issue tracker is for bugs only. 

If you want to request a feature then please visit the forums: https://community.signalusers.org/t/kotlin-for-android-development/5393 (this has already been discussed by some forum users).
