### ISSUE TITLE
Feature Request: Allow forwarding chats to more than one user at time

### ISSUE THREAD

**Issue by Salmon-Bard** [signalapp/Signal-Android#10529]
Thanks for the great project!!

To throughway WhatsApp forever
I hope forwarding to at least 5 contacts at time is allowed to make it easier for users to migrate without looseing any functionality they had on WhatsApp.

I'm one of them :-) !!

**Comment by fduraibi** [comment]
This is a very **important** feature.

In whatsapp it was unlimited before, but to combat spam, as they said, it was limited to 5 (groups, people or both)
