### ISSUE TITLE
60fps animated stickers

### ISSUE THREAD

**Issue by vegedb** [signalapp/Signal-Android#10522]
### Signal Requirements
![image](https://user-images.githubusercontent.com/72070424/104274440-d0a55800-54db-11eb-8e5a-a4158d7b37df.png)

### Telegram
![image](https://user-images.githubusercontent.com/72070424/104274484-e7e44580-54db-11eb-8539-a60b2582b8fb.png)

### Notes
Coming from telegram stickers (60fps), signal stickers looks so **choppy**.
As you can see **size is not the issue**, however signal doesn't have support for 60fps. Please enable 60fps stickers on your latest update that you announced today.

**Comment by greyson-signal** [comment]
Hi there, we only use Github for tracking bugs. For discussing features, please use [the forum](https://community.signalusers.org/). Thanks!
