### ISSUE TITLE
Feature Request: Add "I'm on Signal" banner to profile picture and export to use in other apps

### ISSUE THREAD

**Issue by olliegilbey** [signalapp/Signal-Android#10535]
To increase reach and uptake of Signal usage, informing those on other platforms that a user is available on Signal would be useful.
Being able to add a banner to images in-app and export this image to be used in other apps would be hugely helpful to get Signal visibility across various platforms.

See below image of Mr. Tesla with a banner as an example of what could be automatically added to images.

![TeslaImOnSignal](https://user-images.githubusercontent.com/4788298/104299579-506ffa00-54bd-11eb-8a1f-478987b033df.png)

**Comment by bme13** [comment]
Hi @olliegilbey and welcome,
Please use the community forum https://community.signalusers.org/ for feature requests. Thanks!

**Comment by olliegilbey** [comment]
Feel free to close this, as it is likely time-sensitive, a Github issue is probably more pertinent than the community forum 😄  Will repost there nonetheless.
Thanks, have a good one!

**Comment by grandchild** [comment]
@olliegilbey could you close your own issue? Because most of us are not Signal devs, so we can't. Thank you.
