### ISSUE TITLE
Unknown is on Signal!

### ISSUE THREAD

**Issue by fridaybabe** [signalapp/Signal-Android#10538]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When someone joined, there is a new chat appeared with notification. But, suddenly it changes to 'Unknown is on Signal!'.

When the user joins it shows the user's name and notification correctly. After 2 second it changes to unknown. And sometimes before showing 'unknown' it randomly shows unsaved contact name from one of my group.

In my case i have 1 group having some unsaved contacts.

### Steps to reproduce
- It happens when someone joins.

### Screenshots

![Screenshot_20210112-182918_Signal](https://user-images.githubusercontent.com/20503541/104317961-baf85880-5504-11eb-976c-832989bc4991.png)
![Screenshot_20210112-182926_Signal](https://user-images.githubusercontent.com/20503541/104318001-cc416500-5504-11eb-9a1b-ea186f2542ec.png)

### Device info
**Device:** Asus Zenfone Max Pro M1
**Android version:** 11
**Signal version:** 5.1.7

### Link to debug log

https://debuglogs.org/3d4ba8a7b6af316f63ddd809624b7d5432a74b44a4a34dba1f9b628ccdaba0ab

**Comment by smashCode** [comment]
It seems like, the app is taking some time to pull the details. I faced a similar issue, but the details were updated after 30sec.

**Comment by fridaybabe** [comment]
> It seems like, the app is taking some time to pull the details. I faced a similar issue, but the details were updated after 30sec.

But, When the user joins it shows the user's name and notification correctly. After 2 second it changes to unknown.

**Comment by fridaybabe** [comment]
> It seems like, the app is taking some time to pull the details. I faced a similar issue, but the details were updated after 30sec.

But, When the user joins it shows the user's name and notification correctly. After 2 second it changes to unknown. And sometimes before showing 'unknown' it randomly shows unsaved contact name from one of my group.

**Comment by Sgn-32** [comment]
To you mean joining a group?
This could be something with message request.

https://support.signal.org/hc/en-us/articles/360007459591-Signal-Profiles-and-Message-Requests

**Comment by smashCode** [comment]
@Sgn-32 No. When someone new joins Signal App. Apart from what @fridaybabe specified, even if you navigate to contacts selection view, many of the newly joined contacts would show "Unknown".

**Comment by Sgn-32** [comment]
Ok, it is worth a try to reset the secure session with this contact(s).
The secure session can be reseted in the conversation settings.

**Comment by greyson-signal** [comment]
FYI this was a relatively nuanced bug related to how we were managing contact entries in our database. Shouldn't be a super-common bug, but given that our contact discovery service has been flaky, some users will definitely see this. We have a fix rolling out. Thanks!
