### ISSUE TITLE
Immediate crash when opening app after update to 5.0.9

### ISSUE THREAD

**Issue by ozvoz** [signalapp/Signal-Android#10531]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app crashes immediately when trying to open it after automatic update via Play Store to version 5.0.9 on January 12, 2021.

### Steps to reproduce
- Try to open the app

**Actual result:** System message: "Signal" was closed
**Expected result:** App opens

### Screenshots
None

### Device info

**Device:** Asus Zenfone 2 (ASUS_Z00AD)
**Android version:** 5.0
**Signal version:** 5.0.9

### Link to debug log
None

**Comment by Sgn-32** [comment]
Ok,
what could be done is to set the mobile phone in airplane mode before opening Signal.
That has sometimes helped. Then should be possible to create a debug log.
https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

Maybe you could update to 5.0.10. This is released today.

**Comment by ozvoz** [comment]
Update to 5.0.10, airplane mode, rebooting phone and emptying cache did not help, app is still crashing when opening.

**Comment by mvn-gesp** [comment]
I have the same phone and the same problem.

**Comment by ali77gh** [comment]
same phone and same problem

here is logs:
```
01-13 15:16:47.144  6816  6816 E AndroidRuntime: FATAL EXCEPTION: main
01-13 15:16:47.144  6816  6816 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6816
01-13 15:16:47.144  6816  6816 E AndroidRuntime: java.lang.AssertionError: Unable to load ringrtc library
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at org.signal.ringrtc.CallManager.initialize(CallManager.java:114)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.initializeRingRtc(ApplicationContext.java:330)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:133)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(ActivityThread.java)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5480)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-13 15:16:47.144  6816  6816 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ozvoz** [comment]
Automatic update to 5.1.8 via Play Store resolved prolem, app opens and functions normally, closing Issue.
