### ISSUE TITLE
Suggestion: Add multiple account support

### ISSUE THREAD

**Issue by sleeplife** [signalapp/Signal-Android#10533]
Hi
dont know is it a good place to suggest new feature or not but anyway...
as Signal is growing thesedays and whatsapp is going down (thanks god, I'm really happy), I think its better to ask **add multiple account support**
For example, I have two different number which can seperate "friends and family" and "work" groups
in other hands, the other competitor of Signal (Telegram) has multiple account support
hope make Signal the best and most popular Messaging app in the world <3

**Comment by Sgn-32** [comment]
Hi sleeplife,

the community website https://community.signalusers.org is the place for feature requests.

https://community.signalusers.org/t/multiple-separate-user-profiles-for-example-but-not-exclusive-to-dual-sim-phones/
https://community.signalusers.org/t/allow-multiple-phone-numbers-linked-to-one-signal-profile
