### ISSUE TITLE
Increasing the number of members in the group

### ISSUE THREAD

**Issue by nivetha-o2** [signalapp/Signal-Android#10548]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
signal app permits only 150 members to  be in the  group ,where whatsapp allows 256 member to be  in the  group.as we compared to signal ,whatsapp allows to have more number in the group .so probable most of the people feel discomfort with this .If we allow more member in the group , it would probably make the app more efficient .

**Comment by Sgn-32** [comment]
Hello nivetha-o2,

150 members is just a recommendation. Hard limit 1000.

https://community.signalusers.org/t/new-group-size-of-150-is-too-small/17643/23
