### ISSUE TITLE
Colors are too agressive. Could we at least reduce contrast of color palette?

### ISSUE THREAD

**Issue by RockScience** [signalapp/Signal-Android#10544]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Sgn-32** [comment]
https://support.signal.org/hc/en-us/articles/360007320951-How-do-I-change-colors-

**Comment by RockScience** [comment]
Thank you but in both light and dark themes the color palette is super aggressive. Most of my contacts who migrated on Signal report same feedbacks

**Comment by RockScience** [comment]
That works... thanks

**Comment by Sgn-32** [comment]
Hi RockScience,

this is then more a feature request. See the community website. Here are some topics with chat color.

https://community.signalusers.org/t/on-restoring-i-e-increasing-the-color-palette/3695
https://community.signalusers.org/t/new-color-scheme-color-accessibility-issue/12900
https://community.signalusers.org/t/pick-custom-colour-in-conversation/6412
https://community.signalusers.org/t/improve-privacy-of-chat-colors/1183
https://community.signalusers.org/t/simple-theme-colors-for-android-app/9954

**Comment by theGeekyLad** [comment]
The forums are enticing but if skills permit can we implement the feature ourselves and raise a PR? Or do we take a call and get work assigned?

Also, just checked out all those links. What do you think about an accent picker? Imparts a slant onto the customizability element.

**Comment by grandchild** [comment]
@theGeekyLad You can create PRs all you want, but they will often be thrown out with only _"Sorry we're not going to do this"_. If you're fine with spending the effort with the chance of being disregarded, fine.

But it's easier to just ask in the forums if the devs would be willing to merge a feature (and spend the considerable work giving feedback on your PR). If you then don't get the go-ahead, you can save yourself the time.

**Comment by anupbvr** [comment]
This is definitely a need of the hour. Groups look like a board painted with too many contrasting colors, it is very difficult to focus on content, rather the dark colors are being highlighted all over.. 

The minimum, if there are light near to white colors available in pallette, it would have helped. 

It is also difficult to go and set same color for all members of the group. Looking for some better usability their as well.

**Comment by RockScience** [comment]
I think an easy change would be to make colors optional. At least people could deactivate them if they find them too aggressive.

**Comment by greyson-signal** [comment]
Hi there, we hear you, and we will likely be taking a look at our usage of color in message bubbles in the near future. However, as other have noted, please continue discussion on the forum. Thanks!
