### ISSUE TITLE
Group join alert does not mention phone numbers

### ISSUE THREAD

**Issue by andrazznidar** [signalapp/Signal-Android#10549]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When joining a group with a group link, I was alerted that "your name and photo" will be shared with its group members. But after I joined the group, its members saw my phone number and not my Signal name.

### Steps to reproduce
- Click on a group link
- Observe the alert that does not mention anything about sharing your phone number.
- Join
- Check how do other group members see you

**Actual result:** Group members see only your phone number.
**Expected result:** Alert accurately tells you what info will be shared. For example: "Your mobile number will be shared with group members".
Or better: Group members see only your name and photo and not the phone number.

### Screenshots

My perspective, before joining the group. Notice that it does not say anything about my phone number:
![SignalGroup-01](https://user-images.githubusercontent.com/8482843/104331715-ac537680-54ef-11eb-8c13-7975d1818f6a.png)

Perspective of a different group member, after I joined the group, been in there for a minute and left:
![SignalGroup-02](https://user-images.githubusercontent.com/8482843/104331737-b2495780-54ef-11eb-94dc-09f9d62d3d63.png)

### Device info

**Device:** Samsung Galaxy S8+
**Android version:** 9
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/417785edbf59ae860afb3dbaf78bf6e0bd863f2d8f08995c60d4aeef86253d3a

**Comment by satyadev1** [comment]
I agree with you. This might raise a privacy concern if it is not shown to the user that his number will be shared and the group admin should know the number from which the request has come.

**Comment by andrazznidar** [comment]
The issue is still relevant.
