### ISSUE TITLE
Problem With share Invite Link 

### ISSUE THREAD

**Issue by ravimakwana015** [signalapp/Signal-Android#10542]
![Screenshot_20210112-185044_One UI Home](https://user-images.githubusercontent.com/77336061/104321883-33ade380-550a-11eb-8f01-bc7ba7d5a7f5.jpg)

**Comment by ravimakwana015** [comment]
![Uploading Screenshot_20210112-191215_Signal.jpg…]()

**Comment by Edu4rdSHL** [comment]
Hello, please be more specific when reporting issues, you aren't explaining what's the error actually. If the problem is that the message is not sent, please disable "Ultra data saving mode" and try again.

**Comment by yash-chudasama** [comment]
Hello, you have enabled ultra data saving mode, that's why issue occurred. Try to disable it and then see, issue is fixed or not.

**Comment by aj-34719** [comment]
May fix it??
