### ISSUE TITLE
including dark mode to enhance the visual quality of the app

### ISSUE THREAD

**Issue by nivetha-o2** [signalapp/Signal-Android#10547]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
*I personally prefer to have dark mode in my phone as well as in every possible app which I am using .
* so if we add dark mode in the signal app it will make profitable result of the app.
*  As well it will make the app more cool .we can also add adjustable brightness as one of the feature ,it will make the app more user friendly .

**Actual result:** make the app more user friendly.
**Expected result:**most of the people prefer to use.

**Comment by williamspacefire** [comment]
I don't really understand what you are saying, but the app has Dark mode
![Screenshot_20210112-132231](https://user-images.githubusercontent.com/4999076/104342216-5b388800-54d9-11eb-8ea8-93f32eac5e7e.jpg)
