### ISSUE TITLE
No group video call button

### ISSUE THREAD

**Issue by KrE80r** [signalapp/Signal-Android#10540]
### Bug description
In a group chat of 6 people, some have linked devices (laptops) with mixed OSes (windows & Linux). The video call button is visible only on one user's android device, while other users' android devices not. 
The desktops linkeddo see the video call button though.

### Steps to reproduce
- Create a new group
- Add multiple users
- link some devices to desktop signal
**Actual result:** Users on andriod cannot start a group video call
**Expected result:** All users in a group can start a group video call

### Device info
**Signal Desktop Version: 1.39.4
**Device:** ONEPLUS OnePlus6T A6013
**Android version:** 10 
**Signal version:** 5.0.9 

### Link to debug log
https://debuglogs.org/2b698734ec8ace057fa435331106fa26df3e6b655149804636ff4f36fca30540

**Comment by Edu4rdSHL** [comment]
Hello, latest version is 5.0.10, anyways there are other things you should check:

- Are all the users using the latest Signal version?
- What's the Android version on the devices having issues?
- Is the group a group v2?

**Comment by KrE80r** [comment]
- Users are on 5.0.9, didn't verify all, would one old version cause this?
- Let me collect android versions on all devices and share it
- Group was created yesterday so it should be V2

**Comment by Edu4rdSHL** [comment]
> Users are on 5.0.9, didn't verify all, would one old version cause this?

* Older versions can cause it because videocall in Signal's groups is a relatively new feature.

> Let me collect android versions on all devices and share it

:+1: 

> Group was created yesterday so it should be V2

If the group has admins and you can create a group link, then it's a V2 group.

**Comment by KrE80r** [comment]
Signal version is 5.0.9 is the one used between these devices, one beta tester on 5.1.7. They run Android 10, except for one running Android 9(Signal 5.0.9).

**Comment by KrE80r** [comment]
> > Users are on 5.0.9, didn't verify all, would one old version cause this?
> 
>     * Older versions can cause it because videocall in Signal's groups is a relatively new feature.
> 
> 
> > Let me collect android versions on all devices and share it
> 
>     * +1
> 
> 
> > Group was created yesterday so it should be V2
> 
>     * If the group has admins and you can create a group link, then it's a V2 group.

So, one old version of Signal client in the group can cause this?
if yes, how old, what version to look for?

**Comment by Edu4rdSHL** [comment]
Latest desktop version is v1.39.4, you can check that in https://github.com/signalapp/Signal-Desktop/releases

**Comment by KrE80r** [comment]
> Latest desktop version is v1.39.4, you can check that in https://github.com/signalapp/Signal-Desktop/releases

The problem is not in the desktop version, the problem is in Andriod version of signal, v5.0.9.

Actually, linked desktop clients work fine and the video call button is there, on the same group, while Andriod clients miss the button.

Did I confuse you?

**Comment by Edu4rdSHL** [comment]
Ohh, I missread, sorry. If the older version is 5.0.9 then there shouldn't be problems, I'm out of ideas right now about the problem. The only recommendations I can make is to check that all users have given permissions for camera and audio to Signal app and restart their phones but I doubt that helps.

**Comment by KrE80r** [comment]
Thank you. At least on my side the permissions are there. Unless all users has to check permissions for the button to be viewable for other users, which I suspect TBH.

Maybe someone else can look into this and help?

**Comment by grandchild** [comment]
Are some users using Android 4.4? Because group calling is disabled for Android 4.4 / Kitkat / API 19 (these 3 all mean the same).

**Comment by KrE80r** [comment]
> Are some users using Android 4.4? Because group calling is disabled for Android 4.4 / Kitkat / API 19 (these 3 all mean the same).

Double checking now, but highly doubt it. Any similar limitations for iphone?
if yes, what versions of the OS?

**Comment by grandchild** [comment]
Wouldn't know about iphone, if any. It was a very specific UI bug that prompted group calls being disabled on kitkat, so I doubt they did anything similar on ios.

**Comment by grandchild** [comment]
Is the debuglog from a phone that can't see the button?

**Comment by KrE80r** [comment]
> Is the debuglog from a phone that can't see the button?

Yes, one of them

**Comment by grandchild** [comment]
Okay, then this is as far as I can help -- someone else again will have to step up :)

**Comment by KrE80r** [comment]
Another debuglog[1] after a video call was initiated from an Iphone, if that adds any benefit.

Still, on andriod the button is not there.

[1] https://debuglogs.org/606a499ea1d70ce7e80c8cba7a538ba06c133cd352e891d7e24360528dfb8cff

**Comment by KrE80r** [comment]
Since the versions of the app and OS have been brought up, here is the list of clients:

- Signal 5.1.0.31, IOS 14.3, no desktop client
- Signal 5.1.0.31, IOS 14.0, no desktop client linked, video call icon visible
- Signal 5.1.7, Android 10, linked desktop client, no video call icon on Andriod, yet there is an icon on desktop client
- Signal 5.0.9, Android 10, linked desktop client, no video call icon on Andriod, yet there is an icon on desktop client
- Signal 5.0.9, Android 9, no desktop client linked, no video call icon visible
- Signal 5.0.9, Android 10, no desktop client linked, video call icon visible

IMHO the versions are not outdated to cause the video call icon to disappear. PLus there is one Android device that have the icon visible.

Would linking a desktop client be a factor? I tried unlinking the desktop client already but didn't make a difference.

**Comment by joel6548** [comment]
I am also facing the same issue, the group video call is not shown in the group chat. 

Clarification:
- I had faced this issue in my main group with 4 members. Then to check if the problem continuing again , I tried to recreate it. 
- I created a group with 2 members, I am the owner of the 2 phones used in here.

Phone Specifications:
1. Samsung Galaxy A51 running Android 10 
2. Samsung Galaxy A5 running Android 7 

Signal App Version: 5.1.8 (on both phones)

I tried Troubleshooting it:
- Deleted the app from both the phones and downloaded the latest version on both again
- Restarted both the devices. 
- Messaged from both phones on the groups to make the group active.

But I am still facing the same issue 

 Here is a screenshot of the group, the group doesn't contain any group call icon. 
![WhatsApp Image 2021-01-14 at 2 57 09 PM (1)](https://user-images.githubusercontent.com/73167639/104588018-d97f6080-5678-11eb-973c-82021bf57bbe.jpeg)

**Comment by mfmansour** [comment]
Same issue here:
I am part of the beta program on android play store.
v5.2.0 installed on Google Pixel 5 Android 11 4.19.110.

I am in a new group with 2 iPhone users that have the latest version installed. I do not have the option to group call. When using Signal Desktop on Windows PC, I can call both of them. They both have the option and can initiate calls that I am unable to join.
The video call icon does not appear on Signal Android, and I am unable to join group calls. This issue has been going on since the group call feature was released.
How do I resolve this?
