### ISSUE TITLE
Allow creating an empty group

### ISSUE THREAD

**Issue by mbarak** [signalapp/Signal-Android#10543]
I just tried to quickly invite a WhatsApp group to a signal group via a link and I could not create an empty group to do so.

Luckily I had one of the members of this group chat already on signal so I managed but this should be possible to make it easy to invite people to signal.

**Comment by Sgn-32** [comment]
Hi mbarak,

the community website https://community.signalusers.org/ is for feature requests.
This feature is implemented in the Signal 5.1.2 beta, see:
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/47

**Comment by mbarak** [comment]
Thank you so much! My apologies

**Comment by grandchild** [comment]
It was also backported for 5.0.9, which I just got today, so it should work with an update.

**Comment by Tursko** [comment]
Since this is both a feature request and something that's already fixed, please close this issue :)
