### ISSUE TITLE
Edit your contact's photo

### ISSUE THREAD

**Issue by virendracarpenter** [signalapp/Signal-Android#10552]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Edit your contact's photo

Please change the local contract profile after the contract upload there profile on signal

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by virendracarpenter** [comment]
Do something

**Comment by Sgn-32** [comment]
Do you have issues with contact's photos or is it a feature request?
For feature request, you can discuss on the community website:
https://community.signalusers.org/t/switch-avatars-between-contact-info-and-profile-info/4953

**Comment by greyson-signal** [comment]
Hi there, we currently prioritize contact photos over profile photos, but we're looking into changing that soon (with a setting people can enable to preserve the old behavior). Thanks!
