### ISSUE TITLE
Text Input dropping character input with new update 5.0.10

### ISSUE THREAD

**Issue by zezba9000** [signalapp/Signal-Android#10559]
### Bug description
Text Input dropping character input with new update 5.0.10
Tested with Samsung keyboard & Simple-Input keyboard

### Steps to reproduce
* Try typing some text on a Samsung phone.
* Major lag or characters not picked up by the app

### Device info

**Device:** Samsung Galaxy Express prime 3
**Android version:** 9.0
**Signal version:** 5.0.10

**Comment by UserX404** [comment]
It should have been fixed. You also can report it [here](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-1-release/19567/107) and please append a debug log.

**Comment by zezba9000** [comment]
https://debuglogs.org/b190ac542d10dd97eed8cfe79c1134c73f5ddd81bfd7d3bf35144d63f77f70d4

**Comment by tanujkucp** [comment]
I have also noticed laggy and character dropping behaviour with GBoard.

**Comment by zezba9000** [comment]
This has been fixed with the 5.1.8 release on GooglePlay store!
