### ISSUE TITLE
Signal dropped several SMS messages

### ISSUE THREAD

**Issue by nertim** [signalapp/Signal-Android#10556]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Dropped messages from SMS integration from specific contact

### Steps to reproduce
- Installed Signal
- Setup Signal as the default SMS app
- Sent messages to a specific contact. Contact ack'd verbally they received the message.
- Contact's replies did not make it back to my Signal app.

**Actual result:** Contact's SMS replies did not show up in my Signal app.
**Expected result:** Contact's SMS replies should have shown up in my Signal app. 

### Screenshots
Signal App
![signalapp](https://user-images.githubusercontent.com/493476/104357650-54eae180-54c2-11eb-8dd9-164e8a570efd.png)

Messaging App
![messagingapp](https://user-images.githubusercontent.com/493476/104357667-5a482c00-54c2-11eb-9e78-4477e6407338.png)

### Device info

**Device:** Google Pixel 4
**Android version:** 11
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/9fc301de4661ae9d4c2d29136b3c10c5dba565e4af847113f77d881478d3641f

The issue occurred between 2020-12-09 1:00pm PST. - 2020-12-09 9:00pm PST. 
Unfortunately I removed the integration as I did not want to loose any more messages.

At about 8:36PM PST I turned out the SMS integration with Signal and received a flood of messages from the contact.

Some of the things I tried:
- Removed the contact and re-added
- Deleted the conversation thread in Signal and tried again

**Comment by Sgn-32** [comment]
Can you look at the comment from issue #10498, maybe related.

https://github.com/signalapp/Signal-Android/issues/10498#issuecomment-758739975

**Comment by nertim** [comment]
@Sgn-32 yup! that was the issue. Thank you. Although I still think this is an issue/bug on Signal. Either they should honor the chat feature enablement and/or provide a message to the user to turn off the feature.

**Comment by ctomayer** [comment]
Signal dropped sms messages from at least 2 contacts that I am aware of, one on Android and one on iphone.
Device: Armor 3W
OS: Android 9
Build: Armor_3W_RF2_V02
Not rooted
Signal 5.1.9
