### ISSUE TITLE
Add seperate section for SMS only chats

### ISSUE THREAD

**Issue by specdrake** [signalapp/Signal-Android#10558]
It would be great if I could view conversations that are over SMS only in a seperate section. Also, while searching for a contact to send a message to, if there could be some sort of marker to allow me to identify whether that person is on Signal that would be great.

**Comment by specdrake** [comment]
I opened a feature request(on https://community.signalusers.org/) instead.

**Comment by vamshi9666** [comment]
could like post link to exact feature-request

**Comment by specdrake** [comment]
I had tried posting but it said I cannot post and some staff member will verify first, now it says you have basic member permissions but I can't find a way to make a post. Quite strange.
