### ISSUE TITLE
Suggestion: Possibility to change primary color

### ISSUE THREAD

**Issue by JulioCGMC** [signalapp/Signal-Android#10553]
Hello, I just installed your application and it is beautiful, but (always kkk) there is only one thing that I think would make it even better; the possibility to change the primary color of the app, from this light brown to something different.

**Comment by JulioCGMC** [comment]
Nevermind, just find what i was looking for in the chat config. Thanks.

**Comment by Sgn-32** [comment]
https://support.signal.org/hc/en-us/articles/360007320951-How-do-I-change-colors-
