### ISSUE TITLE
Chat Color Will Not Change !!!!

### ISSUE THREAD

**Issue by ArmTimDev** [signalapp/Signal-Android#10551]

**Comment by grandchild** [comment]
Hi, Arman.

When you write about a problem here, it's not easy for us to understand what you mean. You wrote just the title.

Which chat color do you mean? What do you want to happen?

It would be nice if you could explain yourself a bit more than just one sentence. :)

(_Note for others, the issuer's profile says they're 11 years old, so I'm cutting them some slack_ 🙂 )

**Comment by ArmTimDev** [comment]
Hi :) I Meant If I Go To Chat Settings Then I Change Chat Color It Will Change Only For Me ! Not My Friend, Or If Its Not Signal Feature So... Forgot It :) But Its Better To Add This Feature, Like Viber, In Viber If I Change That It Will Change For My Friend Also... Thanks For Answering :) And Sorry For Giving Little Info About That 😃

**Comment by Sgn-32** [comment]
Hello ArmTlmDev,

changing to color affects only your app. More info about color changes on the support pages.
https://support.signal.org/hc/en-us/articles/360007320951-How-do-I-change-colors-

**Comment by ArmTimDev** [comment]
Hello :) No, I Said Add Feature Which If I Change Chat Color It Will Change For My Friend Too. ( My Suggestion ) And Thanks For Answering @Sgn-32 😃

**Comment by greyson-signal** [comment]
Hi there, yeah, chat color is only for your device. Thanks!
