### ISSUE TITLE
add status or stories feature like whatsapp-status or Instagram-stories

### ISSUE THREAD

**Issue by AkuSarma** [signalapp/Signal-Android#10554]

**Comment by aniteshreddy** [comment]
Yes, we are eagerly waiting for this feature.

**Comment by sweetcock69** [comment]
No cancerous feature please

**Comment by Sgn-32** [comment]
Hello AkuSarma and co,

please use the community forum for feature requests.

https://community.signalusers.org/t/stories-status-updates/2565
https://community.signalusers.org/t/the-ability-to-set-an-away-status-message/5237

**Comment by Rhahkeem** [comment]
> No cancerous feature please

Yeah I'm with you. If you want whatsapp status, use whatsapp.

**Comment by rahuldeo2047** [comment]
I wonder what is a 'cancerous feature' ?
Definition?

**Comment by SundusAdwan** [comment]
so you want to write what I am going to do and when I will be back 
or I will reserve message from .... pm to .... pm 
and when anyone wants to talk with me will see this message 
PLZ told me if  I understand you and it is correct
and I will do it for you

**Comment by patoessy** [comment]
No need for statuses like for whatsapp. But if the feature is added, we should be able to disable it if we do not want it.

**Comment by AkuSarma** [comment]
>What does cancerous feature mean?

**Comment by AkuSarma** [comment]
> No cancerous feature please

A Small feature just to share pictures or small videos is not cancerous.
It would be nice to have one and if anyone have any problem with it there should a option to disable it for them.

**Comment by Rhahkeem** [comment]
> A Small feature just to share pictures or small videos is not cancerous.

If you'd like to share, why not just share with the contacts you need to share it with? Why impose it on people and then ask them to turn it off? 

Also worth noting:

Feature requests should go through the forums. Github issues are being used to track actual bugs
