### ISSUE TITLE
Dead link in wiki 

### ISSUE THREAD

**Issue by Rhahkeem** [signalapp/Signal-Android#10564]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

This is more a bug with the documentation :

When trying to figure out how to build Signal locally I saw that this page:
https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources

points to a dead link for BUILDING.md. Hopefully a quick fix.

**Comment by Rhahkeem** [comment]
Actually also looks like this link:

https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources

points to the old repo. Github will handle the redirects but probably just better to get that updated to avoid confusion

**Comment by Rhahkeem** [comment]
Looks like @manuel-91 fixed the first issue yesterday. I can create a PR for the second one

**Comment by manuel-91** [comment]
@Rhahkeem I found the edit button in the wiki before thinking about opening an issue and was happy that me (a default user) has the right to edit there:-) I don't see "the second one" you are referring to. Please file a PR if there is a deadlink in the code.

**Comment by Rhahkeem** [comment]
Already edited it too. It was in the wiki. I'll close this issue next time
I'm online
