### ISSUE TITLE
Replace endorsement from Jack Dorsey on Signal.org with endorsement from Elon Musk 

### ISSUE THREAD

**Issue by gentleShark** [signalapp/Signal-Android#10565]
The H1 tag on signal.org contains the text "SPEAK FREELY," however, currently beneath the text "SPEAK FREELY" there is an endorsement from "Jack Dorsey, CEO of Twitter and Square". 

Dorsey and Twitter are antithetical to free speech and privacy. Consider replacing Dorsey with Elon Musk who on January 7th, 2021 tweeted "Use Signal" given the direct affronts to free speech occurring on Twitter.

Perhaps the most egregious violation of both free speech and privacy is the TASK platform which a Facebook whistleblower revealed is used at Twitter, Facebook, and Google to, in Mark Zuckerberg's own words, "share signals" about users who violate their community rules. The community rules, however, tend to only uphold the right to free speech when it aligns with the ideological echo chamber at Twitter, Facebook, and Google and that has led to dissenting facts and opinions being flagged, "shared," and censored.

Information related to the TASK platform, sharing "signals", and censorship at Twitter, Facebook, and Google (Mark Zuckerberg congressional testimony):
https://www.youtube.com/watch?v=pOdrPruSnrw   

Information related to censorship at Twitter (Jack Dorsey congressional testimony):
https://www.youtube.com/watch?v=7oeHylP48ws

**Comment by satyadev1** [comment]
This is not a bug. This is a suggestion. Please move this to the Signal community https://community.signalusers.org/
