### ISSUE TITLE
Someone Updated Group notifications

### ISSUE THREAD

**Issue by wunnavabk** [signalapp/Signal-Android#10563]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a bug in Groups. Every now and then I am getting notification saying "<contact name> Updated Group" regularly.

### Steps to reproduce
- Create a Group
- Add other contacts to the group
- just Open group from one Phone
- 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
There is a notification saying "<Contact name> Updated group" on the other contacts phone
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
there should not be any notifications if there is no change in the group

### Screenshots

![20210112_215601](https://user-images.githubusercontent.com/13430918/104380760-6adcbe80-5523-11eb-9505-086ee78f2220.jpg)

### Device info

**Device:** Samsung A70, Samsung A40
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/ac0a5bfd8869623d40aafd26a1dea10c3da5f673bd7d72bb4d2c67b109ff357e

**Comment by inthewaves** [comment]
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/10344, and the upcoming 5.1 update addresses this.

**Comment by wunnavabk** [comment]
With 5.1.8 update this issue is not appearing anymore.
