### ISSUE TITLE
Clear all messages in a chat

### ISSUE THREAD

**Issue by ndm123** [signalapp/Signal-Android#10569]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Please provide an option to clear all msgs in a chat or grp chat in android

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by qystan** [comment]
Its available.  Select group chat icon that you want to clear and choose delete but it has a bug, see #10572

**Comment by Tursko** [comment]
This issue tracker is for bugs only. If you would like to **discuss a new feature or submit suggestions**, please visit the community forum:
https://community.signalusers.org
