### ISSUE TITLE
Stop video download midway

### ISSUE THREAD

**Issue by ndm123** [signalapp/Signal-Android#10568]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is no option to stop opening or downloading a video msg once you click on it.
There is no option to find out the size of video and images before download from chat screen 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by tr1xy** [comment]
Yeah, there should be a label somewhere like **2.47mb**

**Comment by Tursko** [comment]
This issue tracker is for bugs only. If you would like to **discuss a new feature or submit suggestions**, please visit the community forum:
https://community.signalusers.org
