### ISSUE TITLE
API to check if number exist on signal???

### ISSUE THREAD

**Issue by rupali-mishra** [signalapp/Signal-Android#10579]
Can anyone help me to check if there is any API to just check if the phone number exist on signal or not????

**Comment by pgerber** [comment]
As stated in the new issue template, this tracker is only used for reporting issues:

> Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.
>
> If you would like to discuss a new feature or submit suggestions, please visit the community forum:
> https://community.signalusers.org

Please ask this there, preferably after searching the community forum for existing answers first. Thank you.

**Comment by aj-34719** [comment]
I can work on it....may i to go with it

**Comment by rupali-mishra** [comment]
> I can work on it....may i to go with it

Yes Please, It would be very helpful.

**Comment by aj-34719** [comment]
Thank you

**Comment by Genis-Sage** [comment]
Hey @rupali-mishra and @aj-34719
Please don't use github for discussions, as you will spam signal devs with notifications

Please use something else, like community.signalusers.org 
And close the issue here
