### ISSUE TITLE
Colours in chat for each contact

### ISSUE THREAD

**Issue by ndm123** [signalapp/Signal-Android#10571]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Each contact having a different colour in chat window is making signal platform look too colourful and childish. Please give a default single colour. The user can be given option to change colours if reqd for their contacts. In gros having more than 100 members it is difficult to go and change colour of each contact. Instead the colour can be set to default at the beginning

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Tursko** [comment]
This issue tracker is for bugs only. If you would like to **discuss a new feature or submit suggestions**, please visit the community forum:
https://community.signalusers.org

**Comment by Sgn-32** [comment]
From the 5.13 beta thread:

_`We plan on giving users more tools and options to set their own avatar in the near future, and we want to try to change the mental model of the avatar color away from something that you control.`_


https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-13-release
https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes
