### ISSUE TITLE
When scanning the QR code nothing happens

### ISSUE THREAD

**Issue by mlchlko** [signalapp/Signal-Android#10570]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I scan the qr with my phone for

### Steps to reproduce
- i scan qr for  "link this tablet to your phone", 
- 
- that reproduce the bug

**Actual result:** phone wants to share a url. 
**Expected result:** capability of call & text on this tablet 

### Device info

**Device:** Manufacturer Model # - lg-q710Al
**Android version:** LG stylo4 real
**Signal version:** 
Hardware version - rev.1.0

### Link to debug log

I'll be able to add more if the pos phone decides to charge some. 😿😭 ty for your time, reader!!!!!

**Comment by supermar1010** [comment]
Your bug description is quite incomplete, I think you might have better chances at it being looked at, if you add some more information. I think the bug description could use some more text, as well as the reproduce steps

**Comment by Caerbannog** [comment]
Please submit a debug log, it's explained here:
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log

Then you can try to follow these instructions for a similar problem: https://github.com/signalapp/Signal-Android/issues/10756#issuecomment-764959634
