### ISSUE TITLE
Add delete option for SMS on notification

### ISSUE THREAD

**Issue by pokegamer5547** [signalapp/Signal-Android#10576]
It would be convenient for some users like me able to delete unnecessary messages  quickly by clicking on notification option.

**Comment by pgerber** [comment]
As stated in the new issue template, this tracker is only used for reporting issues:

> Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.
>
> If you would like to discuss a new feature or submit suggestions, please visit the community forum:
> https://community.signalusers.org

Please suggest it there, preferably after checking if this has been suggested already. Thank you.

**Comment by pokegamer5547** [comment]
> As stated in the new issue template, this tracker is only used for reporting issues:
> 
> > Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.
> >
> > If you would like to discuss a new feature or submit suggestions, please visit the community forum:
> > https://community.signalusers.org
> 
> Please suggest it there, preferably after checking if this has been suggested already. Thank you.

Oh my bad :( I'm really sorry for not reading it first. And yeah I will check it out rn, Thankyou :)
