### ISSUE TITLE
Bug: Clear All Messages for Group Chats

### ISSUE THREAD

**Issue by qystan** [signalapp/Signal-Android#10572]
The clear all messages uses the chat delete feature.  While it works, it also removes the chat group icon.  It correctly does not remove the user from the group but without the group icon, the user cannot post anything to the group.  The group icon will reappear if someone posts a new message in the group.

The screen shots are in the zipped file, the last picture shows the group icon reappearing automatically after a new post.

----------------------------------------

### Bug description
Clear all messages from chat groups loses the group chat icon and inhibits message posting by the user due to the missing icon.

### Steps to reproduce
- select group chat to clear all messages
- select delete
- the group chat icon is also removed - should NOT be removed.

### Screenshots
![1](https://user-images.githubusercontent.com/63985586/104402255-db6df480-5590-11eb-9f1b-b4d183e0fcfd.jpg)
![2](https://user-images.githubusercontent.com/63985586/104402258-dd37b800-5590-11eb-86ef-097975ec224b.jpg)

The caht group icon should not be removed.
![3](https://user-images.githubusercontent.com/63985586/104402264-df9a1200-5590-11eb-95e1-c0757b5eb864.jpg)

Icon returns when a user posts a new message.
![4](https://user-images.githubusercontent.com/63985586/104402270-e0cb3f00-5590-11eb-9fa6-951bedd6b217.jpg)

### Device info
**Device:** Huawei P30, Samsung 
**Android version:** 9
**Signal version:** 5.0.90

**Comment by Tursko** [comment]
Make sure you attach a link to the debug log after trying to delete a chat.

**Comment by Tursko** [comment]
This is actually intended functionality, not a bug.

**Comment by qystan** [comment]
Ah, understand.  Will follow with the discussion.  Thank you.
