### ISSUE TITLE
Measure issue is when I am sending message though internet at both end is active it's not delivering message

### ISSUE THREAD

**Issue by keyurmakwana** [signalapp/Signal-Android#10575]
- [ X] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
many times message is not delivering to other hand thought internet is available at both the end

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
![1](https://user-images.githubusercontent.com/47387695/104408365-e3766600-5589-11eb-9bd7-73f94bbc9ace.jpeg)
![2](https://user-images.githubusercontent.com/47387695/104408368-e40efc80-5589-11eb-8800-f830ae6355bf.jpeg)

### Device info

**Device:** Samsung J6

**Android version:** 5.0.10
**Signal version:** 0.0.0

**Comment by tushartripathi** [comment]
Could be due to traffic.

**Comment by pgerber** [comment]
Likely an issue on the side of the recipient. Try the [Phone-Specific Troubleshooting](https://support.signal.org/hc/en-us/articles/360028198711-Phone-Specific-Troubleshooting) and the [Troubleshoot receiving messages](https://support.signal.org/hc/en-us/articles/360027913252-Troubleshoot-receiving-messages) instructions from the support page.

This tends to happen as a side-effect battery saving features not working well.
