### ISSUE TITLE
app crashing on entering a group chat 

### ISSUE THREAD

**Issue by eyal670** [signalapp/Signal-Android#10587]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when entering a group chat, app restart and take me back to the main screen or crash completely

### Steps to reproduce
- open signal or signal beta
- Click on a group

**Actual result:** app is crashing or restarting and take you back to the main screen.
**Expected result:** stay in group chat screen and let me read and send msagges.

### Screenshots

![a - opening app](https://user-images.githubusercontent.com/664254/104444463-82a65800-55a0-11eb-8549-663e37853cf3.png)
![b - entering a group](https://user-images.githubusercontent.com/664254/104444468-83d78500-55a0-11eb-958e-3127a0a9b338.png)
![c - app crash after about 3 sec](https://user-images.githubusercontent.com/664254/104444471-84701b80-55a0-11eb-8860-51bc93303ca5.png)
![d - app restart to main screen](https://user-images.githubusercontent.com/664254/104444472-84701b80-55a0-11eb-8015-511b13403765.png)

### Device info

**Device:** Samsung Galaxy J7 (2016)
**Android version:** 6.0.1
**Signal version:** 5.1.8

### Link to debug log

https://debuglogs.org/12412fe5ee25340dcb3916c8fdae5c05907a4271cc371a4da9e48fe4ad2529d2

**Comment by andylinton** [comment]
Having a similar issue - Signal crashes or goes back to the main screen only with a single group chat, all other chats (single contact or groups) work fine.
