### ISSUE TITLE
Enable censorship circumvention in Iraq or atleast add the option to enable it manually

### ISSUE THREAD

**Issue by Foro38** [signalapp/Signal-Android#10583]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi
I can't send images or receive them with signal, I think signal is censored here
Can you enable censorship circumvention if someone has an Iraqi number? or at least add the option to enable it manually?

### Steps to reproduce
- Be in Iraq
- send a picture to your friend
- friend doesn't receive picture 
**Actual result:** Friend doesn't receive picture
**Expected result:** Friend receives picture

### Screenshots

https://i.redd.it/g8rk705rp2b61.jpg

### Link to debug log

https://debuglogs.org/d4f6ed73e7aabe2e327d90faea2ae0d2943dce6165ddc1bb9a151a530ca4de74.zip

**Comment by Sgn-32** [comment]
Hi Foro38,

this is only for Signal on Android. For issues with Signal on iOS use following:
https://github.com/signalapp/Signal-iOS

Maybe searching in the community website can also help:
https://community.signalusers.org/search?q=censorship
