### ISSUE TITLE
Group automatically deleted 

### ISSUE THREAD

**Issue by vikkurocks** [signalapp/Signal-Android#10586]
- when I make group and text message to others and when I delete all messages it automatically group also delete 
- and the other side it available until others will not delete his messages

**Comment by Sgn-32** [comment]
Hi vikkurocks,

when you delete all messages in a group conversation, the group isn't deleted. Only the entry in the conversation list disappears.

See the following topic in the community website:
https://community.signalusers.org/t/list-of-group-names-to-be-displayed-in-contacts-section-to-start-new-conversation-after-deleting-groups-old-chat-history/19957/10

**Comment by aj-34719** [comment]
I can fit it may i continue
