### ISSUE TITLE
An ability in to hide the messages from blocked used from group chat.

### ISSUE THREAD

**Issue by joshyjoseph** [signalapp/Signal-Android#10582]

**Comment by pgerber** [comment]
As stated in the new issue template, this tracker is only used for reporting issues:

> Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.
>
> If you would like to discuss a new feature or submit suggestions, please visit the community forum:
> https://community.signalusers.org

Please report it there, preferably after checking if this has been suggested already. Thank you.
