### ISSUE TITLE
Registration not done

### ISSUE THREAD

**Issue by webix-209** [signalapp/Signal-Android#10590]
> Process 'command 'git'' finished with non-zero exit value 128

**Comment by webix-209** [comment]
Build Version ;- 1.1

**Comment by webix-209** [comment]
Build file 'C:\Users\PC - 12\Desktop\Signal-Android-5.1.7\app\build.gradle' line: 497

A problem occurred evaluating project ':Signal-Android'.
> Process 'command 'git'' finished with non-zero exit value 128

**Comment by webix-209** [comment]
def getLastCommitTimestamp() {
    new ByteArrayOutputStream().withStream { os ->
        def result = exec {
            executable = 'git'
            args = ['log', '-1', '--pretty=format:%ct']
            standardOutput = os
        }

        return os.toString() + "000"
    }
}

**Comment by patrick-Karungari** [comment]
the fastest work-around

def getLastCommitTimestamp() {
    new ByteArrayOutputStream().withStream { os ->
       /* def result = exec {
            executable = 'git'
            args = ['log', '-1', '--pretty=format:%ct']
            standardOutput = os
        }*/

        return os.toString() + "000"
    }
}
