### ISSUE TITLE
Can't send message to user that uses Signal if I don't give access to Contacts or allow SMS integration

### ISSUE THREAD

**Issue by StyXman** [signalapp/Signal-Android#10595]
- [ ] I have searched open and closed issues for duplicates

Putting 'Contacts' in any search query gives tons of issues. I used `send message phone number not in contacts` and I checked the first 3 pages, does that count?

- [ ] I am submitting a bug report for existing functionality that does not work as intended

Frankly I don't know if this is by design, I consider it a bug. Feel free to close if invalid.

- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

See above.

----------------------------------------

### Bug description
I was expecting to send messages to any number without having to hand over my contacts or set it as the SMS application.

### Steps to reproduce
- Install Signal, register phone number
- Do *not* allow access to Contacts or SMSs.
- Try to send a message to a phone number you know runs Signal.

**Actual result:** Compose 'window' does not have a text entry, just a button saying 'Enable Signal for SMS'.
**Expected result:** I should be able to send messages to any phone number, and at most be dropped or rejected if it doesn't have Signal installed.

### Screenshots

Will come in a comment below.

### Device info

**Device:** FairPhone 2
**Android version:** 7.1.2
**Signal version:** 5.0.8

**Comment by Sgn-32** [comment]
Can you receive a Signal message from this contact/phone number, knowing that using Signal.
Also please post a fresh debug log after trying to send/receiving a message to/from the phone number.

**Comment by StyXman** [comment]
Receive yes, since they gave access to their contact list, I suppose. I'll post logs later.

**Comment by LoganDupont** [comment]
I had the same problem. I didn't allow access to Contacts or SMSs and wasn't able to see messages from certain people in a group chat. When that person answered from the desktop app I was able to see his message. Suddenly it was solved. The person thinks that I was still a SMS contact in his signal app.
