### ISSUE TITLE
Back button issue

### ISSUE THREAD

**Issue by Srikrishna-Adiga** [signalapp/Signal-Android#10597]
When chat opened from a notification and back button is clicked the app closes instead of going to the participants screen.

**Comment by BobbyESP** [comment]
Yes. It's a little hard to explain if u are not a developer of Android, but when u open a chat from a notification, you just open that activity (screen), but if you open the app from the home screen, you open at least, 2 activities, the main activity, and the chat activity, so, if you click the back button, what it does its go to the last activity. You understand me?

**Comment by Natanel-Ziv** [comment]
That is correct, but the question here is what we want to have?
Maybe we should come up with a mechanism that opens the main activity as well.

**Comment by syedfaisaljaved** [comment]
This can be easily fixed. I'll try to fix it

**Comment by Ashvith** [comment]
> That is correct, but the question here is what we want to have?
> Maybe we should come up with a mechanism that opens the main activity as well.

I think he is suggesting that the main window should come, when back is pressed, instead of closing the app.

**Comment by leonardo2204** [comment]
It's pretty annoying, but yeah, I think it's kinda simple to fix (TaskStackBuilder, perhaps?).
@syedfaisaljaved I can take a look at your PR (or help to come up with the code) if you don't mind!

**Comment by VijayJaybhay** [comment]
Duplicate of #10390

**Comment by VijayJaybhay** [comment]
Duplicate of #10390
