### ISSUE TITLE
Export chat from WhatsApp Export to Signal

### ISSUE THREAD

**Issue by Saikat2019** [signalapp/Signal-Android#10593]
Hey, there is already an option in WhatsApp to export chat from WhatsApp. So, it is possible to develop functionality in Signal using which we would be able to import that exported WhatsApp chat in Signal. Please look into this.

**Comment by itsakhileshh** [comment]
If that happens i will right away delete my WA account.

**Comment by happychameleon** [comment]
Hi this sounds like an interesting feature that other people seem to also be interested in on [signal forum](https://community.signalusers.org/t/migrate-from-whatsapp/10566/4)

The github issue tracker is used for bugs in existing functionality and not feature requests (if you don't mind you could close the issue and join the discussion over there).

**Comment by Saikat2019** [comment]
Sure, thank you.
