### ISSUE TITLE
Groups: Personal info should be wiped when leaving a group.

### ISSUE THREAD

**Issue by jonathancross** [signalapp/Signal-Android#10592]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was added to a large group not long ago and decided to leave because I was not comfortable with so many strangers seeing my phone number.

When I leave a group, I expect my phone number and other data to also become invisible to group members who did not add me to their contacts already.

### Steps to reproduce
- join a group
- write a message
- leave the group
- have a group member tap on my avatar in the group next to the message.

**Actual result:** Phone number, profile picture and name are still visible to group members.
**Expected result:** Phone number, pic should be blank and username should be "ghost", etc.

Furthermore, even **blocking the group** does not prevent group members from seeing the personal information.

**Comment by Mr-Carobon** [comment]
Good question.

**Comment by jonathancross** [comment]
As far as I know it is not addressed yet.

**Comment by jonathancross** [comment]
Frustrating this stale bot just closes issues which have not even been responded to.
Is this goal just to hide issues from devs & users?

**Comment by cody-signal** [comment]
We have continually been working towards of world with better phone number privacy. As of right now, this isn't possible. Your phone number has already been sent to those in the group and stored locally. You are asking us to try to remote delete information from another person's device which isn't great nor 100% reliable.

Change Number recently shipped and is one of the first steps to the behavior you desire.

**Comment by jonathancross** [comment]
@cody-signal Thank you for responding.
Since a hash of the phone number is used for contact lookup, maybe there is a way to use that (in place of the real phone number) in groups during this interim period?  "Phone number privacy" has been in the works for many years, so it might be good to have a patch for this issue in case it takes longer than expected.  Groups really should not be a way to harvest phone numbers, etc.

Note: profile picture and name are also leaked permenantly, but phone number is top priority.

Thanks!
