### ISSUE TITLE
Automatic disabling the notifications after a specific number of missed notifications on a specific chat

### ISSUE THREAD

**Issue by gexgik** [signalapp/Signal-Android#10601]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There's no need to be notified after each message in a specific chat. If I miss more than 5(for example) messages on the same chat, disable the notification.
### Steps to reproduce
- ask another user to write more than 5 messages to you
- 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- you will get notified for each and every message

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- Get notified only for first 5 messages, then mute notifications.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Sgn-32** [comment]
Hi gexgik,

please use the community forum for feature requests.

**Comment by nikoul** [comment]
Hi @gexgik ,

Have you added this as a feature request in the community forum ?
I'm also desperate to have this one !
