### ISSUE TITLE
N Group members have the same name

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#10605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When 2 participants have the same name, there's an annoying popup in the Android app with the "N Group members have the same name".

### Steps to reproduce
- Create a group.
- Wait for participants to join.
- Wait that two or more participans have the same name.

**Actual result:** Annoying popup with "N Group members have the same name" is show everytime an admin opens the Android app requiring a review. It's annoying, the group I have created has more than 300 participants, it's hightly possible that two users have the same name.

**Expected result:** It isn't a problem, user's unique identifier is the phone number, not the names. There can be X users with the same name without problem.

### Screenshots

![image](https://user-images.githubusercontent.com/32582878/104503647-58a86200-55af-11eb-9a08-13184342859a.png)

![image](https://user-images.githubusercontent.com/32582878/104503700-6362f700-55af-11eb-94f6-20c8f60c8d28.png)

### Device info

**Device:** Samsung Galaxy A71
**Android version:** 10
**Signal version:** 5.1.8

### Link to debug log

Not needed.

**Comment by kavana5git** [comment]
This is totally still a problem, sigh.  See #13477 for identical more recent post.
