### ISSUE TITLE
Stickers can't be tagged with messages. 

### ISSUE THREAD

**Issue by rameshkmscct** [signalapp/Signal-Android#10609]
I tried to reply with sticker for one of the previous message. But sticker send them seperately without tagging the message.

**Comment by Sgn-32** [comment]
Hello rameshkmscct,

this behavior is intentional. You can discuss on the community forum about this.
https://community.signalusers.org/t/send-stickers-with-a-caption/12918

**Comment by rameshkmscct** [comment]
No. If somebody sent a message in a group. I want to reply as a sticker for that message. But sticker posted seperately. But if i reply as a smily  for particular message. It tagged correctly.

**Comment by PrajjwalDatir** [comment]
@rameshkmscct 
> No. If somebody sent a message in a group. I want to reply as a sticker for that message. But sticker posted seperately. But if i reply as a smily for particular message. It tagged correctly.

That's What he meant, Exactly the working you described earlier, is intentional.
You can discuss on the community forum about this.

https://community.signalusers.org/t/send-stickers-with-a-caption/12918
