### ISSUE TITLE
Feature request: Add contact without sharing phone number

### ISSUE THREAD

**Issue by ikender** [signalapp/Signal-Android#10616]
Looking to be able to create a connection with users,  without needing to provide a phone number.  Using possibly a unique user identifier

**Comment by bme13** [comment]
Hi @ikender  and welcome,
Please note github is only used for bug reports. The community forum ( https://community.signalusers.org/ ) is the preferred place for feature requests. A lot of discussing about usernames can be found there and it's actually something already being worked on. See e.g. https://community.signalusers.org/t/signal-introducing-usernames/9157.

**Comment by ikender** [comment]
> Hi @ikender and welcome,
> Please note github is only used for bug reports. The community forum ( https://community.signalusers.org/ ) is the preferred place for feature requests. A lot of discussing about usernames can be found there and it's actually something already being worked on. See e.g. https://community.signalusers.org/t/signal-introducing-usernames/9157.

Thanks for that, I will look
