### ISSUE TITLE
Crash when trying to send pictures from the gallery

### ISSUE THREAD

**Issue by manwefm** [signalapp/Signal-Android#10611]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashed multiple times when attempting to send a picture from the gallery. The pictures show up as black, then the conversation disappears, and the screen gets blank when i go back to see the other conversations.

### Steps to reproduce

1. Open conversation
2. click on the +, the pictures are then all black.

**Actual result:** 
The pictures are all black.

**Expected result:** 
The pictures should be displayed

### Device info

**Device:** Samsung A6+
**Android version:** 10
**Signal version:** 5.0.10 (I have had this issue for a long time...)

### Link to debug log
https://debuglogs.org/788443b49a8a9b0fd079826d032d5672400ab155635716e468ae67e09c42ea0d

**Comment by g42d** [comment]
I have the same issue
