### ISSUE TITLE
SMS receiving not working inside Huawei Private Spaces

### ISSUE THREAD

**Issue by gillhofer** [signalapp/Signal-Android#10617]
---------------------------------------
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal does not receive/show SMS messages if, - that's my theory - signal was installed inside [Huawei Private Spaces](https://consumer.huawei.com/en/support/content/en-us00754246/). Note: Signal is set as the default SMS app. 

### Steps to reproduce
- Install Signal on a Huawei Phone inside the Private Space.
- Set Signal as the default SMS App
- Receive a SMS-message

**Actual result:** SMS-messages will not be received. If the default SMS App gets changed to the systems "Messages"-App, "Messages" then receives this SMS-message. Signal does not show nor notify about that SMS-message. 
**Expected result:** Signal receives the SMS-message and shows it next to all other messages sent via signal.

### Device info

**Device:** Huawei P30 (MAR-LX1A)
**Android version:** 10.0.0.365
**Signal version:** 5.0.10

### Link to debug log
https://debuglogs.org/7982e58a4f849aa0dd83773403e825d39b8c7207bad9dba8287c2f4e57aebe4f

**Comment by nertim** [comment]
I am seeing this issue as well:

Link to debug log: https://debuglogs.org/0184dbc99d078ab209569a50d65e21ae407e7e2228e05853b23bacd16b9188f7

Device: Pixel 4
Android Version: 11
Signal version: 5.1.8

**Comment by Caerbannog** [comment]
To check if Huawei Private Spaces is indeed a factor, could you try if this solution works?
https://github.com/signalapp/Signal-Android/issues/10498#issuecomment-758739975

**Comment by gillhofer** [comment]
This solution does not work. 

Chat functionality has been deactivated in the "messages" app's settings. Then test SMS have been requested. Signal did not receive them. The messages app did not receive them either. Only when I changed the default SMS app back to the messages app, it received the messages. Signal did never show those test messages.
