### ISSUE TITLE
Share Link Cuts of at '#" Character

### ISSUE THREAD

**Issue by Royal-lobster** [signalapp/Signal-Android#10614]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When ever a link contains '#', it cuts of at that place only linking before part '#' of that link.

### Steps to reproduce
- Open Signal and open any chat.
- Type any link which contain '#' or copy paste the below example to the chat box.
   Example : https://example.com/file/yyyyyyy#bbbbbbbbbbbbbbbbbbb
- Then Send the message.
- that reproduce the bug

**Actual result:** Signal only links the message till # (https://example.com/file/yyyyyyy) and rest of it becomes as plain text.

**Expected result:** The Entire link (https://example.com/file/yyyyyyy#bbbbbbbbbbbbbbbbbbb) must be linked.

#### Link Send from Android Signal App :
![Screenshot_2021-01-14-06-16-49-31_4b14b257287ac0a6d1fd5fbb2487716f](https://user-images.githubusercontent.com/52039218/104529626-2be85f00-5630-11eb-85c4-37d59e5d4a5b.png)

#### Link seen from Signal Desktop App (Perfectly linked entirely link).
![signal Link Bug](https://user-images.githubusercontent.com/52039218/104530645-694dec00-5632-11eb-8c92-3c80cfe2d21b.png)

### Device info
**Device:** Realme U1 (RMX1833)
**Android version:** 9
**Signal version:** 5.1.8

**Comment by Rushi98** [comment]
can't reproduce 


|**OS** | Android 8.1.0|
|---|---|
|**Device**| Moto G5S Plus|
|**Version** |5.1.8|

**Comment by Royal-lobster** [comment]
> can't reproduce 
> 
> 
> |**OS** | Android 8.1.0|
> |---|---|
> |**Device**| Moto G5S Plus|
> |**Version** |5.1.8|
> 
> ![signal-2021-01-15-004713](https://user-images.githubusercontent.com/16462824/104638078-b16d1d00-56cb-11eb-9103-9c8e1286c207.png)
> 

Ohh I think it's device specific problem. I tried with all the links you tried with but all the links gets cut at '#' 

## Here is the screenshot:

![Screenshot_2021-01-17-06-37-01-60.png](https://user-images.githubusercontent.com/52039218/104828355-83840600-588e-11eb-8e11-a3acd52e003e.png)

**Comment by Rushi98** [comment]
Hello Bot,
It is not relevant for me because I no longer use Signal. I do not know if the issue still exists for others or not 🤷🏼‍♂️
