### ISSUE TITLE
Empty Groups with name "Unbenannte Gruppe"

### ISSUE THREAD

**Issue by PfefferT** [signalapp/Signal-Android#10612]
Hello,

I've got a  new phone. So I installed the signal app und recovered my normal messages. So far... so bad. 2 of my 3 groups are now named with "Unbenannte Gruppe". I am not able to see anybody inside of the group and I cannot write anything. I tried to leave the group and the admins reinvite me, but this did not help me. We also tried to update any information of the group without any success. I have read in some posts that my key needs to get updated inside this group, but how can I or the admins achieve that ?

Thanks for the Help

For reproducing:
I have a freshly installed Google Pixel 5 with Android 11.

**Comment by PfefferT** [comment]
What is the status here? I have still the problem with my groups and no one answeres. Neither this ticket nor the support itself.

**Comment by PfefferT** [comment]
Problem is not solved. I cannot write to some of my groups and i cannot
leave them.

stale[bot] ***@***.***> schrieb am Do., 3. Feb. 2022, 04:22:

**Comment by cody-signal** [comment]
Please open and a new issue and follow the template provided instead of deleting it. Also include a debuglog, without one it's hard to tell what's going on.
