### ISSUE TITLE
[feature] Adding custom stickers support like whatsapp 

### ISSUE THREAD

**Issue by Hrushi2406** [signalapp/Signal-Android#10628]

**Comment by Sgn-32** [comment]
Hi Hrushi2406,

please use the community forum for feature requests:

https://community.signalusers.org/search?q=sticker%20%23feature-requests

**Comment by Nisc3d** [comment]
There is custom sticker support in Signal: https://support.signal.org/hc/en-us/articles/360031836512-Sticker

**Comment by greyson-signal** [comment]
Indeed, we've got a sticker uploader built into our desktop client, and some great community members maintain the unofficial [signalstickers.com](signalstickers.com).
