### ISSUE TITLE
Group names are too short

### ISSUE THREAD

**Issue by MenachemICTBIT** [signalapp/Signal-Android#10625]
Please lengthen group names. I am trying to convert my groups to Signal from WhatsApp and some of my non-tech friends are complaining that they can't use the same names since Signal has a much lower limit of group name length.

**Comment by MenachemICTBIT** [comment]
I'm on version 5.0.10 on Android (this is the Android repo after all) but all apps (android, iOS, desktop, Linux) should have the same group name limit. My carryover group name that I was unable to use is 23 chars. 

Just curious, why was 32 chosen? It seems pretty reasonable but wondering if that was random of conscious choice.

P.S. (To be honest, I wouldn't mind the Navy SEAL copypasta as a group name. That's always a laugh. )

**Comment by EwoutH** [comment]
Wait for the 5.2.0 update, that might make things better.

If you find 32 characters too short I would leave a feature request here: https://community.signalusers.org/c/feature-requests/

**Comment by alan-signal** [comment]
I just looked and whatsapp group names are limited to 25.

On Signal we were limited to 32 but for some non-English languages characters and emojis, single characters can take up more than 1 of this count.

So yes, in 5.2, I expect this to be resolved and you to be able to use all 32 no matter what your language. LMK if that's not the case, but closing for now.

**Comment by MenachemICTBIT** [comment]
Yes. I was writing a name in Hebrew.
Thanks for the update. Looking forward to the new release.
Keep up the good work!
