### ISSUE TITLE
Gboard cuts off text input field

### ISSUE THREAD

**Issue by longspell** [signalapp/Signal-Android#10637]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I wake up my device and it was previously in a signal chat, upon the screen turning on the text input field gets cut off by Gboard

### Steps to reproduce
- Open a chat, while the keyboard (Gboard) is showing, press hardware button to turn off device screen
- Wake up device, observe gboard

**Actual result:** Text input field is cut off
**Expected result:** Text input field is not cut off

### Screenshots
![image](https://user-images.githubusercontent.com/60353706/104651348-852ead80-5685-11eb-8ca8-2afaa92ecb33.png)

### Device info

**Device:** Pixel 4 XL
**Android version:** 11
**Signal version:** 5.1.8

### Link to debug log
https://debuglogs.org/74e514875c1144935fe62dca184be49b5dc3f34c1933c0e3f44105df1d2f8493

**Comment by JoelMon** [comment]
The latest Signal version on **Android is 5.1.9**. Try updating and see if the problem persists. I just checked on my device and it looks fine.

**Comment by longspell** [comment]
Thanks, I checked for an update and Google Play Store offered me 5.2.1, I updated but the issue remains.

**Comment by Vertiqo** [comment]
Yup same here, to reproduce it, it seems you have to wake up the device without unlocking it first though.(!)
Waking the device up with the fingerprint does NOT lead to the cut off text field for me.

So to reproduce:

Open a chat, Gboard needs to be visible. > Press power Button to lock the device > press power Button again to wake it > unlock the device > text field is cut of as shown by the original screenshot in this post.

Pixel 4a
Android 11
Version 5.2.3

**Comment by longspell** [comment]
Good catch, on my pixel 4 xl, due to face unlock, I have to angle the phone away from my face, press the side button to turn on the screen and then look at my device to unlock it in order to have the input field cut off. If I look at the device without pressing the side button and the devices wakes/unlocks itself the input field is not cut off.
-------- Original Message --------

**Comment by Vertiqo** [comment]
Persists in Version 5.3.7, also i wonder if another issue i have is related.

It seems that when the textfield is cutoff the "back" gesture doesnt quite work right. i have to minimize the keyboard first.

**Comment by longspell** [comment]
I'm seeing the same thing re: unable to use the back gesture. I haven't tried minimizing the keyboard but resorted to tapping back in the top left of the screen instead of using the gesture.

-------- Original Message --------

**Comment by longspell** [comment]
Can confirm continues to happen in 5.3.10

**Comment by longspell** [comment]
Still happens in 5.4.4

Looks like a potential duplicate of https://github.com/signalapp/Signal-Android/issues/10269
