### ISSUE TITLE
Clear chat is not available 

### ISSUE THREAD

**Issue by ypshukla55** [signalapp/Signal-Android#10631]
I tried to clear chat with delete conversation button. After deleting conversation the group disappeared until some group member send some message in the same group. 

So there should be clear chat option available for group chat as well as personal chat too.

**Comment by Sgn-32** [comment]
Hi ypshukla55,

please use the community forum for feature requests:

https://community.signalusers.org/t/list-of-group-names-to-be-displayed-in-contacts-section-to-start-new-conversation-after-deleting-groups-old-chat-history/19957
