### ISSUE TITLE
Keyboard pops up every time you click on new chat button

### ISSUE THREAD

**Issue by parthbrahmaxatri** [signalapp/Signal-Android#10649]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Keyboard pops up every time you click on new chat button.

### Steps to reproduce
- click on new chat button

**Actual result:** Keyboard pops up every time you click on new chat button.
**Expected result:** Keyboard should not pop up every time. Instead, it should pop up only when you want to search your contacts.

### Device info

**Device:** Xiaomi Redmi Note 5 Pro
**Android version:** 9 PKQ1.180904.001
**Signal version:** 5.1.9

**Comment by Maheshbsv** [comment]
I believe the keyboard pop up is a feature by itself to type and search for a contact.

**Comment by PalashBansal** [comment]
@sidharthmittal
