### ISSUE TITLE
Group Leaving vs Thread Deletion

### ISSUE THREAD

**Issue by n00b42** [signalapp/Signal-Android#1064]
Deleting a group thread looks like leaving a group. But deleting the thread does not remove me from a group, but until someone writes to that group or updates it, i am not able to write to that group, as i have no open thread i could select.
I propose: thread deletion for groups should just clear all messages without removing the group from the thread list

**Comment by Jens14L** [comment]
When will this feature be included?

You should consider to add a tab for groups like in Threema.
