### ISSUE TITLE
Chat history doesn't transfer on linking new devices.

### ISSUE THREAD

**Issue by shaurya-src** [signalapp/Signal-Android#10648]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just linked my Signal account to PC and none of my chat got synced from my mobile. I understand that this is intended as a security feature but there are situations where we often need to access Signal on newly linked devices to work around on-going conversations. This security feature kills all the possibility for that.

### Steps to reproduce
- Download Signal on PC (Windows).
- Link signal account by scanning QR code.
- Check the chat history.

**Actual result:** Unable to view any of my previous chats on linked device.
**Expected result:** Chat history with contacts should be available on all devices concurrently.

### Screenshots
![Capture](https://user-images.githubusercontent.com/41169759/104692382-e8741a80-572d-11eb-9d9d-192cde87f898.PNG)

### Device info

**Device:** Samsung M31
**Android version:** 10
**Signal version:** 5.0.9

### Link to debug log
https://debuglogs.org/7be222246160ec6245eb62f54b6e5e85058033676c20f2884ff03683ab0bf25f

**Comment by minnmann** [comment]
As you mentioned yourself, this is working as intended. 

Thus, this is not a bug but a feature request, which has been discussed for almost 2.5 years, see https://community.signalusers.org/t/message-history-sync-for-newly-linked-desktop-devices/2839. 

You can voice your support for that feature by liking the initial post.

That being said, the Github issue tracker should only be used to track actual bugs (https://github.com/signalapp/Signal-Android#contributing-bug-reports; i.e. when something is not working as intended), while the forum is the right place to participate in higher level discussion such as feature requests (https://github.com/signalapp/Signal-Android#contributing-code).
