### ISSUE TITLE
Draining more battery then other applications

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [signalapp/Signal-Android#10645]
I tracked the battery usage, but the battery usage is very high compare to other application.

**Comment by KushagraKarira** [comment]
Please attach relevant information / screenshot supporting how you reached to the conclusion.

**Comment by roppppp** [comment]
if you have a degoogled phone please use https://github.com/signalapp/Signal-Android/issues/9729

**Comment by Rhahkeem** [comment]
@swarupbhanjachowdhury could you at least fill out the template. The developers have spent a lot of time putting it together,  filling it out would actually be helpful for them to understand if this is actually a problem
