### ISSUE TITLE
status.signal.org says "Signal is up and running" while everyone in my geographic region gets 502s

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#10657]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Virtually all my signal contacts I am writing with right now are complaining about connectivity issues, but your status page says "Signal is up and running".

**Actual result:** Signal appears to have server issues, but the status page says "everything is fine"
**Expected result:** Status page says "we know something is wrong and are working on it"

### Link to debug log
Signal-Desktop: https://debuglogs.org/9f685f91d3b6b565d06863917f611913f8c4e9d26e6635c60eb7933a88d8721e
Signal-Android: https://debuglogs.org/f43de9c593aff14ed1ad3499758ac0b971ee63fe08239d9fa567e4b48781371a

**Comment by Mushoz** [comment]
Seems like the servers are overloaded. They will probably scale up the number of servers to serve all the new people that started using Signal. They had some similar issues a few days ago, which were fixed relatively quickly (a few hours tops). I agree that first impression is extremely important, but the current growth they are experiencing is just staggering, which makes it extremely difficult to stay on top.

**Comment by i0x71** [comment]
I have the same issue,
textsecure-service.whispersystems.org
resolves to 2 servers
One is reporting 
[main] ERROR org.asamk.signal.Main - Error while checking account: Bad response: 500                                                                    

another is reporting
[main] ERROR org.asamk.signal.Main - Error while checking account: Bad response: 502

**Comment by Trolldemorted** [comment]
Yeah, running infrastructure at that scale is a nightmare. Nevertheless, a "we are working on it" statement would be helpful, after I saw the "everything is fine" statement on the status page I began looking for issues within my own infrastructure.

**Comment by Mushoz** [comment]
Technically, everything is still up. And I am able to send / receive messages if I try often enough. So that's why the status page might show the service as still being up. However, requests are failing due to the load being too high.

**Comment by Trolldemorted** [comment]
>Technically, everything is still up

With all due respect, if our connections are failing every few seconds and the servers are responding internal server errors at an abnormal rate, then "everything is still up" is a false statement.

**Comment by Penguin-Guru** [comment]
Same problem on desktop client and Android (WiFi and mobile data). Attempting to call from Android returns an immediate "network failed" message. Attempting to call from desktop produces no apparent error, but also no ringing tone (and no answer). Some messages on desktop fail to send (with the red exclamation mark). Other messages on both desktop and mobile are either one or more of: (1) marked as delayed for minutes before sending, (2) marked as delayed for minutes before receiving, (3) never marked as delivered, or (4) never marked as read. The protocol is clearly being disrupted. At one point, one of my contacts was able to call me and the call was perfectly normal, but I was completely unable to call them immediately before or after and they were unable to call me again (network failed). I uploaded a debug log but won't post it here unless someone wants it.

**Comment by Mushoz** [comment]
Which is why I included the word "technically", @Trolldemorted . Of course the current situation isn't acceptable and doesn't leave a good first impression for people trying out Signal. However, we will have to bear with the team while they are resolving the issue.

**Comment by bkqtnte10** [comment]
@Mushoz I think Trolldemorted has a point. Can status.signal.org be made more sensitive/fragile/verbose so that problems that happen "often enough" also show up in the status?

**Comment by Mushoz** [comment]
@bkqtnte10 It's currently showing Signal is experiencing issues :)

**Comment by TheRealCuran** [comment]
Might be related to signalapp/Signal-Desktop#4853

I'm seeing issues with sending too and also receiving. I have messages on my phone (Android) shown as sent but not delivered. And indeed my contact hasn't gotten them. They also don't show up on linked devices. And from the desktop version I do get the 502 errors too sometimes (see also signalapp/Signal-Desktop/#4858).

This looks a lot like a backend server issue. Maybe it's time to decentralise the network as much as possible? So it can be more robust, even if lots of new users join in large droves.

**Comment by TheRealCuran** [comment]
Just for information: the devs are on it: https://github.com/signalapp/Signal-Desktop/issues/4853#issuecomment-761034317

**Comment by Sevyls** [comment]
> Just for information: the devs are on it: [signalapp/Signal-Desktop#4853 (comment)](https://github.com/signalapp/Signal-Desktop/issues/4853#issuecomment-761034317)

still got problems sending messages, both in iOS app and macOS Signal desktop app

**Comment by greyson-signal** [comment]
Apologies, status.signal.org was updated appropriately, and you should see status messages in-app as well.

**Comment by i0x71** [comment]
No messaging for today, everyone go play outside :rofl:

**Comment by Leptopoda** [comment]
As the outage is over this should be closed now

**Comment by Trolldemorted** [comment]
>As the outage is over this should be closed now

This issue is about the lack of monitoring, not the outage itself.

**Comment by Leptopoda** [comment]
How is this a bug with existing signal android behaviour?

**Comment by Trolldemorted** [comment]
The client repositories are being used to [track server issues for years](https://github.com/signalapp/Signal-Desktop/issues/1826) because the server issue tracker is closed. Where else should I raise this issue?

**Comment by ghost** [comment]
dear stale bot, this is still relevant
