### ISSUE TITLE
Message sent to wrong group/person

### ISSUE THREAD

**Issue by gondoi** [signalapp/Signal-Android#10659]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During the server issues on Jan 15 2021 around 9:50am CST, I sent a message to a person but immediately switched over to a group I have going. After switching the message was sent and appeared in the group.

### Steps to reproduce
- simulate outage
- send a message to a single person
- switch to someone else or a group
- allow connection to go through

**Actual result:** Messages are delivered to the wrong person or group.
**Expected result:** Messages should be queued and tagged specifically for delivery to group or person so there is no chance of sending to others, even during quick switching.

### Device info

**Device:** OnePlus 7 Pro
**Android version:** 10 (Oxygen OS 10.3.7.GM21AA)
**Signal version:** 5.1.1

### Link to debug log
https://debuglogs.org/b08fbead2e14375a9f310cc37a3e6278f006af84b3fd6a8becdd960b824fc7e7

**Comment by Frivolous2** [comment]
I'm not sure if this will solve your issue, but the latest Signal version is 5.1.9; updating to it might potentially help.
