### ISSUE TITLE
Signal users profile picture not retrieved from server

### ISSUE THREAD

**Issue by atarek1** [signalapp/Signal-Android#10656]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My signal contacts profile pictures not retrieved from server, it only shows my phone address book picture if exist else displays letters. 
This behavior is not exist on signal desktop for windows or signal ios.
I'm facing this behavior for a week and I tested with signal version 5.2.0 chat settings to force using address book photo but nothing is changed after toggling this option on and off closing app and reopen.

I noticed that issue #10411 faced same behavior but it's resolved on his side after a while so it seems in his case it was an overload on server at his request time , mine still exist for more than a week.

### Steps to reproduce
- Open signal android app
- look for contacts profile pictures

**Actual result:** Contact profile picture is displayed from my phone address book picture if exist else displays letters. 
**Expected result:** Display profile picture from contacts profile stored in signal server.

### Device info
**Device:** Samsung note 3 hlte n9005
**Android version:** 9.0.0
**Signal version:** 5.2.0

### Link to debug log
https://debuglogs.org/a368b1f4a3b13bfaa97847a46db95506469237937f66c76f27cd12e99548bb46

**Comment by atarek1** [comment]
I noticed that issue https://github.com/signalapp/Signal-Android/issues/10411 faced same behavior but it's resolved on his side after a while so it seems in his case it was an overload on server at his request time , mine still exist for more than a week.

**Comment by pz64** [comment]
`CascadingFuture: java.io.IOException: No pipe available!
	at org.thoughtcrime.securesms.util.ProfileUtil.getPipeRetrievalFuture(ProfileUtil.java:113)
	at org.thoughtcrime.securesms.util.ProfileUtil.lambda$retrieveProfile$0(ProfileUtil.java:76)
	at org.thoughtcrime.securesms.util.-$$Lambda$ProfileUtil$F0soKnIql05DHsuGf3wm-v3uJZw.call(Unknown Source:8)
	at org.whispersystems.signalservice.internal.util.concurrent.CascadingFuture.doNext(CascadingFuture.java:69)
	at org.whispersystems.signalservice.internal.util.concurrent.CascadingFuture.<init>(CascadingFuture.java:33)
	at org.thoughtcrime.securesms.util.ProfileUtil.retrieveProfile(ProfileUtil.java:76)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.lambda$onRun$3(RetrieveProfileJob.java:254)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.lambda$onRun$3$RetrieveProfileJob(Unknown Source:0)
	at org.thoughtcrime.securesms.jobs.-$$Lambda$RetrieveProfileJob$AMkc_prxNjnAFh1Qg9DVjAbwkBM.apply(Unknown Source:4)
	at com.annimon.stream.operator.ObjMap.nextIteration(ObjMap.java:24)
	at com.annimon.stream.iterator.LsaIterator.next(LsaIterator.java:22)
	at com.annimon.stream.Stream.toList(Stream.java:1539)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.onRun(RetrieveProfileJob.java:255)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:30)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)`

I think the issue come this part of code

**Comment by abdulradcliffe** [comment]
Facing Exactly same issue. here are debug logs.
https://debuglogs.org/e41469c5cf1399193d2fdfbd9f1aa0e3f81961c982048188eccad5df8df62d1c

**Comment by akndev** [comment]
@greyson-signal updated log from signal beta 5.2.1 same issue exist.
https://debuglogs.org/5521a8f9409c6cbf2b6e7c51789a5a23db0fab0c249879078fb5ce8c6ac2177d

**Comment by atarek1** [comment]
@greyson-signal updated log from signal beta 5.2.1 same issue exist.
https://debuglogs.org/5521a8f9409c6cbf2b6e7c51789a5a23db0fab0c249879078fb5ce8c6ac2177d

**Comment by atarek1** [comment]
Updated log from beta 5.3.1
https://debuglogs.org/e6af30782763171d4f8642f0ebc0b476236f316866440796e08b126c520965ac

**Comment by hiqua** [comment]
I have a possibly related problem: the picture from a contact was the one locally saved (not the Signal profile picture). I deleted this picture to get their Signal profile picture, but now I just get the default avatar (with their initials) instead of their profile picture. I know that they do use a profile picture.

https://debuglogs.org/7f5819fe7a2ec5e6c80f3274f165ed5244e98068dd7385939a920e983c79459f

**Comment by greyson-signal** [comment]
Hi there, changes went out in 5.17.x that hopefully solve this problem. Is it better?

**Comment by hiqua** [comment]
No, still the same on 5.17.3 for me.

https://debuglogs.org/39bbd274fe2d68c8cccce6cb1e55a83de85332baa5dffabe50cc8b12fcdc127f

**Comment by atarek1** [comment]
Hello @greyson-signal , thanks for your great effort , it's a way more better now in 5.18.1.

Current behavior I need to open manually each user profile chat & wait for secs then user profile photo will be rendered correctly and when i go back user profile photo in chat list is updated correctly.

It will be better with user experience if there is a job that can update users profile pictures (ex: on app launch) and update contacts list with new photos automatically.

Debug log:
https://debuglogs.org/52e18a1c11ced6aeb6d296c02eed2ad54dc6ff2154dd84fa3333c494f830143d

**Comment by greyson-signal** [comment]
Great to hear! Sorry it took a while -- the solution was that we had to re-implement some crypto primatives in our [rust library](https://github.com/signalapp/libsignal-client), which took some time to get the right people working on it. 

We do have a job that will periodically fetch profiles for users on launch, but it only runs once every 12 hours, so you probably just haven't hit it yet :)
