### ISSUE TITLE
Splash Screen Feature Request

### ISSUE THREAD

**Issue by ksdkamesh99** [signalapp/Signal-Android#10655]
It would be great if you introduce a splash screen on the signal app with its logo

**Comment by kashyapraval** [comment]
Unfortunately, not a space for feature requests.

**Comment by Frivolous2** [comment]
You can search for, upvote, and create feature requests for Signal here:

https://community.signalusers.org/c/feature-requests/17

You can even use your existing GitHub account: simply choose the GitHub option under the Log In menu at the top right.

I hope this helps. 😇

**Comment by oxygi** [comment]
@ksdkamesh99: Please close your "issue" and use our community forum as already mentioned. The issue tracker is for bugs, not for feature requests.
