### ISSUE TITLE
Signal Donation Link against Play Store TOS

### ISSUE THREAD

**Issue by PaulWoitaschek** [signalapp/Signal-Android#10653]
Currently there is a donation link in the signal app under settings. There are several cases where that lead to an app ban for open source projects:

https://github.com/andOTP/andOTP/issues/396
https://www.reddit.com/r/WireGuard/comments/diprvn/wireguard_removed_from_google_play_store_due_to/

I'm worried that this will get signal banned too.

**Comment by kamaravichow** [comment]
I think open-source apps are allowed to get donations externally. 

And I also think that google doesn't support accepting donations from In-App Billing.

https://news.ycombinator.com/item?id=21270739#:~:text=Google%20Play%20policies%20do%20not,such%20as%20Patreon%20is%20forbidden.&text=>%20One%20time-payments%2C%20including,%2C%20online%20auctions%2C%20and%20donations.

**Comment by PaulWoitaschek** [comment]
> I think open-source apps are allowed to get donations externally.

Well all these ban news say otherwise. In you reddit post the conclusion is also say that there is just no way. 😕

**Comment by bme13** [comment]
Based on:
https://pay.google.com/intl/en_in/about/policy/?visit_id=637463108645092769-3470620818&hl=en&rd=1
This is allowed for a 501(c)(3) organisation which Signal is.
Anyway please note that github is for bug reports. I suggest if you want to discuss this further this should be done on the community forum. See https://community.signalusers.org/.

**Comment by PaulWoitaschek** [comment]
All right, hopefully this won't cause trouble.

**Comment by greyson-signal** [comment]
Yeah, the reason those other apps had problems was that they were not 501(c)(3) non-profits. We are, so we'll be just fine :)
