### ISSUE TITLE
SMS goes slowly while Signal servers are being overloaded

### ISSUE THREAD

**Issue by kyleedwardsny** [signalapp/Signal-Android#10669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In light of the recent swell of the Signal user base, and the downtime it's causing, I've reverted to using SMS. However, sometimes even the SMS messages don't send when they should. It seems to me like SMS should always work, barring a cell network outage.

**Comment by kyleedwardsny** [comment]
One thing I noticed is that this only seems to happen when I have outgoing Signal messages in the queue, which are prevented from sending due to the outage. Once they get sent, the SMS messages get sent too.

**Comment by pixincreate** [comment]
You already have the answer. Just close this issue now.
When the servers are restored, everything will be normal once again:)

**Comment by kyleedwardsny** [comment]
But my point is that the SMS functionality should not be dependent on the servers being up. It should work independently of the Signal servers.

**Comment by Tursko** [comment]
> But my point is that the SMS functionality should not be dependent on the servers being up. It should work independently of the Signal servers.

This has already been reported here 

https://github.com/signalapp/Signal-Android/issues/10594

**Comment by kyleedwardsny** [comment]
Closing as duplicate of #10594.
