### ISSUE TITLE
Unable to submit message via Desktop App

### ISSUE THREAD

**Issue by jwgn** [signalapp/Signal-Android#10667]
![2021-01-16 01_05_17-Signal](https://user-images.githubusercontent.com/15985023/104790461-8bad4a00-5797-11eb-80ff-0d2482ecea16.png)
Hi,

Desktop App advises to submit a bug report, so here I am:

Windows 10 Version 20H2 (Build 19042.746)
Signal v1.39.5

### Steps to reproduce
Send a message to a Signal contact

**Actual result:** 
"The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 503)"
**Expected result:**
Send the message

**Comment by nrizzio** [comment]
Hi there, Signal is down. You can track the status at https://status.signal.org. I am sure that the developers will update the messaging for the Desktop app if it ever happens in the future.
