### ISSUE TITLE
Signal failed to delete your account.

### ISSUE THREAD

**Issue by rajmondburgaj** [signalapp/Signal-Android#10666]
I am trying to delete my account in signal but for some reason it does not work. Everytime I click the delete account it shows: 'Failed to delete account. Do you have a network connection ?' message. I used this number in the past for signal which means I installed the app, deleted the account, reinstalled it and tried to delete it again. Second time did not work. I am not sure if the behavior is triggered due to second time trying to delete the account or some other bugs. 
My phone is Samsung Note 10 +

I tried to do the same with another number in iphone 12 max pro and I get the same error, failed to delete the account.

**Comment by williamspacefire** [comment]
Right now, Signal severs are down, i can't even send messages, that's why you can't delete your account, when servers come back you can delete it.

**Comment by bershanskiy** [comment]
@rajmondburgaj You should be able to delete account now.

**Comment by rajmondburgaj** [comment]
Yep it solved the issue, thanks :)

**Comment by kintonc** [comment]
Hi all - I have this issue right now (03:46 am UTC time), AFAIK Signal is not down anymore, does anyone know what may be the cause?
