### ISSUE TITLE
Unable to switch to light theme

### ISSUE THREAD

**Issue by mrudultora** [signalapp/Signal-Android#10663]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When System default theme is dark, then after selecting the theme does not changes to light. In other cases, everything works fine. 

### Steps to reproduce
- set your system theme as dark.
- select light theme from the Appearence Fragment

**Actual result:** Theme remains dark.
**Expected result:** Theme must change to light. 

### Device info
**Device:** Redmi Note 7S
**Android version:** 10
**Signal version:** 5.1.9

**Comment by mayweed** [comment]
Hello
Works for me on my redmi note 10 with signal 5.2.0. Your issue might be solved with the next update.

**Comment by mrudultora** [comment]
@mayweed  Updated to  v5.2.0 but then also not working. Tested in debug mode then also not working. If there is a bug I will make a PR soon.

**Comment by batunii** [comment]
MIUI 12 has a pretty strict dark mode enabled. Please see if it's been turned off for the Signal app. The dark mode forces the app to show its white elements in the darker shade.

**Comment by mrudultora** [comment]
@batunii I don't think this as a appropriate reason. There are other apps that are completely fine with such feature.

**Comment by batunii** [comment]
I am just asking you to check if the theming works as it should if you have removed Signal from following the MIUI's Dark Mode. It would make debugging the issue for developers easier.

**Comment by mrudultora** [comment]
@batunii  Yes you were right. After removing this app it works fine now. Closing the issue !
