### ISSUE TITLE
Signal is experiencing technical difficulties

### ISSUE THREAD

**Issue by Rex-0x7CB** [signalapp/Signal-Android#10661]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I sent a message to a group using Signal Desktop and it was sent only to one of the group members. When I checked my mobile to see if it was delivered, I could confirm that it wasn't. Now there's a constant popup with error suggesting that there's a technical difficulty. I made sure that my internet connection is not a problem here. Please check the Screenshots.

### Steps to reproduce
- Send message to a group

**Actual result:** Message not sent to all the members.
**Expected result:** Message sent to all the members.

### Screenshots

![1  Signal Desktop Snapshot](https://user-images.githubusercontent.com/7991220/104763785-59332b00-575e-11eb-9024-186833b9ab7b.PNG)
![2  Signal Android Snapshot - Delivery Report](https://user-images.githubusercontent.com/7991220/104763817-64865680-575e-11eb-988e-9659970c2766.png)
![3  Signal Android Snapshot - Error](https://user-images.githubusercontent.com/7991220/104763840-6cde9180-575e-11eb-85c3-9c2e38a94831.png)

### Device info

**Device:** motorola Moto G (5S) Plus sanders_n
**Android version:** 8.1.0 (05c0, OPSS28.65-36-6)
**Signal version:** Signal 5.1.9 (769, 7691)

### Link to debug log

https://debuglogs.org/196c7dddff8ccbc8c7a3d8edc41086eb3a09c1c1e354bf7c85df0e7841111e7e

**Comment by michaelb-ae** [comment]
it's because of the massive arrival of news user, they do their maximum to update the server please wait a bit

**Comment by Rex-0x7CB** [comment]
> 
> 
> it's because of the massive arrival of news user, they do their maximum to update the server please wait a bit

Thanks for the info. I thought it was a bug. Really appreciate the developers! Keep up the good work!

**Comment by MrWaste** [comment]
Thank you for letting me know. Makes sense

**Comment by MrWaste** [comment]
@michaelb-ae

 How many hours do you think this will take?

**Comment by KeyWeeUsr** [comment]
@MrWaste
> https://twitter.com/signalapp/status/1350165610936766464

I think it can take a while, what you see is basically a human DDoS and a real-time optimization from the devs' side :)

**Comment by oxygi** [comment]
@Rex-0x7CB: Please close the "issue". It is not a software bug. They are working on it. For all other stuff, please use our community forum.
