### ISSUE TITLE
How can we migrate WhatsApp export chat to Signal ?

### ISSUE THREAD

**Issue by jdaku** [signalapp/Signal-Android#10672]
I want to move WhatsApp chat to Signal. ofcourse, we can't import WhatsApp database, but we can Export chat from Group or 1-1 chat and I am expecting from you to make tool which migrate WhatsApp export chat to Signal and make it clone.

Please help for same & Signal is wonderful communication app

**Comment by Sgn-32** [comment]
Hi jdaku,

please use the community forum for general discussion. Github is only for issue tracking.

https://community.signalusers.org/search?q=migrate%20whatsapp

**Comment by christoph-conrads** [comment]
> I am expecting from you to make tool which migrate WhatsApp export chat to Signal

You could [donate to Signal](https://signal.org/donate/) to make your wish come true.

**Comment by oxygi** [comment]
@jdaku: Please close your "issue" because it is not a bug. Please discuss your question in our community forum.
