### ISSUE TITLE
All messages being sent from the background never getting delivered, but sent to the server

### ISSUE THREAD

**Issue by T1mmyK0** [signalapp/Signal-Android#10675]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
**Note:** Despite the issues Signal has with their servers currently, I'm able to send normal messages without problems.
The bug I noticed always happens in my tested scenario while normal messages are always being sent.

**Bug:** For all messages Signal starts the sending process for, while the Signal Android app is in the background, the message will be sent to the Signal servers, but never be delivered to the receiver. Even if you open the Signal app manually afterwards. If you then send a message directly from within the Signal app, the message is being delivered to the receiver while the prevoious background message has only one tick and never arrives.
Receiving messages while Signal is in the background also works without problems and also shows a notification.

**Scenarios when this is the case:** Replying directly from the Android notification while Signal is closed leads to the message never being sent - even after launching the Signal app afterwards. Same happens if you click on "Mark as read" - then the receiver will never receive the Read Ticks. (Replying from within the notification while the Signal app is in the foreground works fine)
Another scenario is if you type a message within the Signal app while your internet connection is turned off, then leave the Signal app, turn the internet connection on, wait a moment, then you can return to the Signal app and the message is never being delivered, but sent to the server.

Looks like it might be an issue with the encryption while the app is in the background or a general issue with the background process.

### Steps to reproduce
Scenario 1
- Go to the home screen of your device
- Ask a friend to send you a Signal message
- Then you receive an Android notification in the status bar of your device
- Within the notification click on "Reply" or "Mark as read" and send the message
- Your friend then never receives this reply or the ticks which show when the message was read even if you open the Signal app afterwards

Scenario 2
- Open a chat in the Signal app
- Disable your internet connection
- Type and send a message
- Close the Signal app
- Turn on your internet connection
- Your friend then never receives this message even if you open the Signal app afterwards

**Actual result:** The message was sent to the Signal servers, but never arrives at the receivers device.
**Expected result:** The message should be delivered without any issues

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** Tested: 5.1.9 & 5.2.0

### Link to debug log

https://debuglogs.org/03bd154c27a4c81c40cb609e1305571533a45aa08096650a8774975e3fae6a4b

**Comment by Sgn-32** [comment]
It is also possible that you just don't get the delivery receipt.
Have you asked your contact, if he has received the message?

**Comment by T1mmyK0** [comment]
I have 2 phone numbers and tested myself in all different scenarios 👍

**Comment by Sgn-32** [comment]
Strange, but then important is to have the debug log of both devices.
Perhaps the message is thrown away at the receiving device. Should
be logged in the debug log. Nice also the timestamps of message send.

**Comment by T1mmyK0** [comment]
Last message sent from background was at 01/16/2021 14:55:34 MEZ.

Wait, I also create new logs.
I'm just using one device. One copy of Signal installed normally on the device and the other on the work profile of the phone.
Both profiles are completely separate and cannot access each other.
Issue happens in both directions and only with background messages.

Can't this be reproduced?

**Comment by Arnab771** [comment]
It doesn't seem to be just for messages sent in background. Some of my friends are trying to send me messages after yesterday's outage but they simply can't. I asked them to reinstall, it's still the same. Sometimes it works while sometimes it doesn't.

**Comment by T1mmyK0** [comment]
I know that there's an outage, but normal message are sending!
This is an issue with the background process only!

**Comment by Arnab771** [comment]
> I know that there's an outage, but normal message are sending!
> This is an issue with the background process only!

I agree.

**Comment by T1mmyK0** [comment]
@Sgn-32 Here are the new logs from both apps as well as the screenshots with messages and timestamps:

**Normal profile on my device:**
https://debuglogs.org/6f65bc890078ea1e23e9f54539dfd68f6a557590a90010e6083c419783cc0b19
![normal_profile](https://user-images.githubusercontent.com/58298629/104815031-71648200-5812-11eb-8301-07bab1847eec.jpeg)

**Work profile on my device:**
https://debuglogs.org/03bd154c27a4c81c40cb609e1305571533a45aa08096650a8774975e3fae6a4b
![work_profile](https://user-images.githubusercontent.com/58298629/104815032-7295af00-5812-11eb-94be-a43decb4ea69.jpeg)

Reply from background means reply from notification while Signal was in the background.
As you can see, reply from background messages are just shown in the senders chat.

**Comment by Sgn-32** [comment]
While testing, i found a related issue with delivery receipts.
A sends a message to B. Message is marked as send.
B receives that message, the app sends also the delivery receipts, but no change at A, only send indicator is shown.
B reads the message, the message of A shows the read indicator.

**Comment by qosch** [comment]
I have the same issue but can also confirm that this does not only happen when replying from the notification bar. In fact, I experienced this issue without ever having replied from the notification bar but was also able to reproduce it by replying from the notification bar.
In the situation where I encountered it I sent three messages and the first oft them was the one that didn't arrive.

**Comment by T1mmyK0** [comment]
> While testing, i found a related issue with delivery receipts.
> A sends a message to B. Message is marked as send.
> B receives that message, the app sends also the delivery receipts, but no change at A, only send indicator is shown.
> B reads the message, the message of A shows the read indicator.
> 
> Devices with 5.1.9 (A) and 5.0.10 (B)

Yes, that's also an issue I have. You see this in my screenshots. There are also some "not delivered" marks, despite that the message was delivered and read.

**Comment by T1mmyK0** [comment]
Another interesting fact regarding the screenshots:
All messages where the "read marks" show were read by opening the Signal app manually, then clicking on the chat.
The other messages were read by clicking on the notification. In this case the "read marks" didn't arrive at the other Signal app.

**Comment by Arnab771** [comment]
> Another interesting fact regarding the screenshots:
> All messages where the "read marks" show were read by opening the Signal app manually, then clicking on the chat.
> The other messages were read by clicking on the notification. In this case the "read marks" didn't arrive at the other Signal app.

Even if the messages are read by opening the signal app it still doesn't show as "read" in the other signal app as I have tested on 5.1.9 and 5.2.0.  Sometimes it does though.

**Comment by T1mmyK0** [comment]
> > Another interesting fact regarding the screenshots:
> > All messages where the "read marks" show were read by opening the Signal app manually, then clicking on the chat.
> > The other messages were read by clicking on the notification. In this case the "read marks" didn't arrive at the other Signal app.
> 
> Even if the messages are read by opening the signal app it still doesn't show as "read" in the other signal app as I have tested on 5.1.9 and 5.2.0. Sometimes it does though.

I have also tested this a little and it looks like it shows the "read marks" if you open the Signal app and then click on the chat.
But it does not work if you were within a chat, return to the home screen and then read the message by entering this chat from the task list again.

**Comment by Arnab771** [comment]
> > > Another interesting fact regarding the screenshots:
> > > All messages where the "read marks" show were read by opening the Signal app manually, then clicking on the chat.
> > > The other messages were read by clicking on the notification. In this case the "read marks" didn't arrive at the other Signal app.
> > 
> > 
> > Even if the messages are read by opening the signal app it still doesn't show as "read" in the other signal app as I have tested on 5.1.9 and 5.2.0. Sometimes it does though.
> 
> I have also tested this a little and it looks like it shows the "read marks" if you open the Signal app and then click on the chat.
> But it does not work if you were within a chat, return to the home screen and then read the message by entering this chat from the task list again.

I'll test it again. If it doesn't work then maybe I'll share the debug logs too. Thanks.

**Comment by Arnab771** [comment]
https://debuglogs.org/17dfdb010207ce0665b4e9b84cb9193f89b2e9294502ea15ff1712e335ff4cf3
![img](https://i.postimg.cc/zBMqgq6w/Screenshot-20210116-212315-2.png)

https://debuglogs.org/a1328a4974c4cd54294dffbbf484c782e397685e3bd403674d3c337aa54a9d92
![img](https://i.postimg.cc/BQndGrz4/Screenshot-20210116-212241-2.png)

As you can see messages didn't even appear on the other device and read and delivered receipts aren't working either.

**Comment by T1mmyK0** [comment]
Fixed in version 5.2.2
