### ISSUE TITLE
Importing/showing all contacts

### ISSUE THREAD

**Issue by johan974** [signalapp/Signal-Android#10673]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whatever I try, my contactslist is very, very small. Only a few old items are shown. 

### Steps to reproduce
- Screen opens with Signal contats
- Pencil = add/use a contact from my contacts list. 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Then only a very, very limited set of my contacts is shown. 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- All my contacts should be shown. 
- I have transferred (and synchronised) my contacts in Android settings from SIM to phone ... tried
- I have transferred (and synchronised) my contacts in Android settings from Phone to SIM ... nothing helps 

### Screenshots
- The list is very limited, so only eight of my 130+ contacts are shown. 

### Device info

**Device: Samsung A71
**Android version: 10
**Signal version: newest at 13-01-2021

### Link to debug log

- There is no debug log, because the functionality seems to be missing without any warning. 
- I am an Android developer myself.

**Comment by johan974** [comment]
Only in this way I can invite other peoples simply and directly to Signal. So this helps me moving to this platform. And others.

**Comment by Frivolous2** [comment]
This list is only your Signal contacts. If you scroll to the bottom, you will see an "Invite to Signal" link. This will give you a link you can share to people using your existing SMS app/WhatsApp/Facebook Messenger/etc.

**Comment by Sgn-32** [comment]
All contacts are shown only if Signal is also your default SMS app.
See suppport: https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts
