### ISSUE TITLE
Can't switch between Secure Signal and Insecure SMS when sending media

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#10670]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't switch between secure and insecure when trying to send an image.

### Steps to reproduce
- Select an image
- Hold down on the send button to switch to Insecure SMS

**Actual result:** Phone vibrates to indicate you are opening a menu, but nothing opens.
**Expected result:** Menu to choose between secure and insecure message should open up.

### Screenshots

![Screenshot_20210115-223035](https://user-images.githubusercontent.com/18274896/104797142-7b8a7000-5781-11eb-8ea7-35bfd7987820.png)

### Device info

**Device:** Manufacturer Pixel 4
**Android version:** 11
**Signal version:** 5.1.9

### Link to debug log

Debug log not needed for this issue.

**Comment by dreua** [comment]
I think that's a feature because you can't send media via SMS. That would be an MMS which could be quite expensive depending on your contract and is not commonly used in my experience.

**Comment by Tursko** [comment]
> I think that's a feature because you can't send media via SMS. That would be an MMS which could be quite expensive depending on your contract and is not commonly used in my experience. 

You can send media via MMS. Just switch to Insecure SMS and send an image.

In the US, SMS/MMS is essentially free.

**Comment by dreua** [comment]
> You can send media via MMS. Just switch to Insecure SMS before attaching an image.

I wasn't aware of this, thanks for the clarification. Maybe you could edit your main first post to clarify this and we can hide those unproductive comments. At least for me it was confusing that it only mentioned SMS but not MMS.

**Comment by Tursko** [comment]
I call it 'Insecure SMS' because that's what Signal calls the button.
