### ISSUE TITLE
Discrepencies in source strings: WiFi or Wi-Fi

### ISSUE THREAD

**Issue by sveinki** [signalapp/Signal-Android#10678]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
The source strings use alternatively WiFi or Wi-Fi, I'd think the latter is the official version. 
In Signal-Android the propotions are WiFi = 3 ocurrencies and Wi-Fi = 1, don't know about the other components.
I think this should be harmonized, perhaps as an 'easy hack' for someone getting acquainted with the Signal code?

**Comment by balamsoft** [comment]
https://github.com/signalapp/Signal-Android/pull/10707

**Comment by sveinki** [comment]
Fixed: https://github.com/signalapp/Signal-Android/actions/runs/492277031
