### ISSUE TITLE
Cannot accept or reject the call (both "Accept" and "Reject" buttons do not respond 90% of the time)

### ISSUE THREAD

**Issue by raindropsfromsky** [signalapp/Signal-Android#10686]
- [ y] I have searched open and closed issues for duplicates
- [y ] I am submitting a bug report for existing functionality that does not work as intended
- [y ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ y] This isn't a feature request or a discussion topic
----------------------------------------
### Bug description
In the incoming call screen, the "Accept" and "Reject" buttons are unresponsive for 90% of the time 

### Steps to reproduce
Call someone. 
That person sees the screen but cannot take the call or reject the call. Both buttons do not respond.

(Note: There is yet another bug, where the called party does not hear a ring. But here, we were checking out Signal, and thus kept in touch with each other via GSM calls or WhatsApp calls. So the called party already knew that a call would be coming, and was looking at the mobile at that expected moment. Thus the called party could see a screen popping up. But both buttons were unresponsive. So the party can neither accept nor reject the call.

After several attempts to press the buttons, occasionally the buttons respond (like once in 15 attempts). But the user cannot be expected to fiddle with the phone so patiently.

**Actual result:** 
Buttons respond once in 15 attempts (approx)

**Expected result:** 
Both Accept and Reject buttons should be responsive.

### Device info
Various.

**Comment by tanujkucp** [comment]
You should provide debug logs for the both devices you used to test signal calls. That will help the Dev's to solve your problem.

**Comment by acujl** [comment]
Same here. The phone dosen't ring too.

Xiaomi Redmi Note 9

**Comment by raindropsfromsky** [comment]
> You should provide debug logs for the both devices you used to test signal calls. That will help the Dev's to solve your problem.

Unfortunately the **Settings > Advanced** menu does NOT allow us to save the device log as a text file, so that we can save it and upload the file along with the bug report. It forces us to submit the log directly to Signal servers; and I am unable to attach any other information along with it. For example, I cannot attach the bug number to the log.

Secondly, I have to request the called party to hand over his log to me, which is awkward. And then he is also not able to copy and send it to me as a file, even if he wanted to.

Thus the design of Signal does not have a provision to attach its logs at both ends of the call with the bug.

Should I raise this itself as a separate bug?

**Comment by tanujkucp** [comment]
Go to Advanced>Submit debug log and then click on submit button at bottom.
It will first upload your code to a website and provide you a link to it. Then just copy it and share it here.

**Comment by raindropsfromsky** [comment]
Yes, but that is not locked to the bug we raise. It is an independent
submission.

Secondly, is the called party also submits the log, it is neither licked
with the bug not to the log submitted by the calling party!

**Comment by r1williams** [comment]
Same here. The phone dosen't ring too.

Xioami phone.
