### ISSUE TITLE
Group invitations not sent to contacts already in another group

### ISSUE THREAD

**Issue by geros62** [signalapp/Signal-Android#10689]
When creating a new group all contacts that are members of another of my groups do not get invitations, they are joined to the group automatically.
Expected: all contacts of the new group should get the invitation and have to accept it before joining the group

Version: Signal 5.1.8
Device: Xiaomi Note 8T
Android version: Android 10, MIUI-Version 12.0.1 stable

**Comment by Sgn-32** [comment]
Can you explain this in more details?
Have you created an empty group and activated the group share link with admin approval?
How you have shared the group link?

**Comment by geros62** [comment]
I did not create an empty group, I added members first
Steps:
- create a new group
- add contacts, at least one of them already exist is another of my groups
- Set the group name (all members are shown in a list)
- Create the group
- -> a message is shown: <n> invitations are sent where <n> is the count of new group members without myself AND without all contacts which are already members of another of my groups
- -> all <n> contacts get invitations, the contacts which already exist in another of my groups do not get invitations, they are members of the group without confirmation

**Comment by geros62** [comment]
Step 5 shoud be
-> a message is shown: "n invitations are sent" where "n" is the count of new group members without myself AND without all contacts which are already members of another of my groups
sorry: "n" was not shown in the last comment
