### ISSUE TITLE
MMS incorrectly handled on dual sim phone, creates group chat

### ISSUE THREAD

**Issue by h4nstr4pp** [signalapp/Signal-Android#10681]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Text messages are activated. I have a dual sim phone. MMS are correctly sent from both SIMs. But whenever I receive an MMS on the number that is not registered with Signal (SIM2), a separate group chat is created with MMS sender, SIM1 and SIM2.

### Steps to reproduce
- Receive MMS on number not registered with Signal

**Actual result:** New group chat is created
**Expected result:** MMS added to the existing conversation thread

### Screenshots

![Screenshot_20210116-224936011](https://user-images.githubusercontent.com/77553848/104824049-04bba880-584f-11eb-82e4-49629f4a670b.jpg)
I successfully sent a picture to Joe from SIM2 (not on Signal)
Joe sent a picture (cat) : group chat created with recipient (SIM2 number xxx56) and N (SIM1 registered with Signal)

### Device info

**Device:** OnePlus 5
**Android version:** 10
**Signal version:** 5.2.1

**Comment by NotStepbro** [comment]
This happens to me aswell. It's obnoxious.

**Comment by thevorpalblade** [comment]
I have what's probably the same problem. I also have a dual sim phone, but only one sim card is installed. The number I have signal registered with is a Google voice number not associated with the sim card.

When I get a MMS, it goes to a new group containing the sender, "you" and also the number associated with the sim. I'm assuming this is the same underlying issue so I'm commenting here but I'm also happy to open a new issue if deemed appropriate.
