### ISSUE TITLE
Suggestion to port to Windows 10 Phone

### ISSUE THREAD

**Issue by BennoMP** [signalapp/Signal-Android#10682]
Would this be feasible?
I really want to daily drive my Lumia and I wouldn't be able to without Signal to be honest.

**Comment by Rhahkeem** [comment]
Probably worth following the community guidelines and checking here
https://community.signalusers.org/

**Comment by Frivolous2** [comment]
Hello!

You should definitely check out the community link, as that is where all the feature requests are proposed and addressed, and you can even use your GitHub account to login and make a thread about a feature request. That said, here are my thoughts on that dillemma.

After doing some quick research, I rather doubt the possibility, considering the (very, very) limited marketshare of Windows Phone. According to Statcounter, it's at 0.02%. And that's a whole bunch of design, programming, and then support costs, if they decide to support a new OS, for which I believe the Signal team might not be able to do now, especially with all the new users, especially with such a tiny, tiny, tiny marketshare OS.

The only way I would've thought it possible is if Signal expanded their team and decided to do native desktop apps, including a UWP port, but I just read that [UWP is dead](https://www.theverge.com/2019/5/30/18645609/microsofts-universal-windows-app-dead-microsoft-store-windows-store). 

I really think you should look at second-hand phones, and upgrade. Or maybe use Anbox on your computer to run Signal there. I don't know if that will work, but it's worth a try. Windows Phone is a dead end, I'm afraid. 

I hope this helps.

**Comment by Frivolous2** [comment]
If you wish, you are welcome to create a feature request on the community forum, as linked by Rhahkeem, but please close this issue here, as this is only for reporting bugs and issues, and not for suggestions. 😇

**Comment by BennoMP** [comment]
I understand. My love for the OS made me forget the fact that it's dead and has no market share whatsoever

**Comment by Frivolous2** [comment]
We are all blinded by love sometimes. 😉😁

Best of luck with getting Signal to work. 😇👍
