### ISSUE TITLE
Links won't open in new tabs on stock chrome on Android

### ISSUE THREAD

**Issue by laurencebgood** [signalapp/Signal-Android#10684]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 It is once again impossible for me to open multiple links from Signal in separate browser tabs, as every link will be opened in the same tab and so, overwrite the previously opened link.

This is similar to #4874 except that it seems like fewer people are experiencing it, and I don't know why.

Note that Signal does not ever set https://developer.android.com/reference/android/provider/Browser#EXTRA_CREATE_NEW_TAB but that near as I can tell it doesn't need to because it removes EXTRA_APPLICATION_ID. However, I do not have this problem with *any other app* on my phone, including other chat apps, so I do think this will need to get fixed by Signal, not by Android or Chrome.

### Steps to reproduce
- open a link from Signal
- leave the browser tab for that link open
- open a different link from Signal
- observe that you cannot find the browser tab from the first link, anymore
- repeat this process, note you can only ever find the link you just opened, all others are gone.

**Actual result:** Only the last clicked link has a browser tab.
**Expected result:**  Clicking multiple links results in multiple browser tabs, one with the page from each link

### Screenshots
I don't think this is something I can usefully demonstrate with a screenshot

### Device info

**Device:** Google Pixel 3
**Android version:** Android 11 Build RQ1A.201205.003 (ie Android December 5, 2020 security update)
**Signal version:** 5.1.9

### Link to debug log

https://debuglogs.org/b83615b6dd50a5ced97644783c9738807103036e5a1d0db2e775cf9d897172ad (though I find it unlikely this will be helpful)

**Comment by Leptopoda** [comment]
Is this something with the system webView?
I use firefox and don't have the problem.

**Comment by laurencebgood** [comment]
This is definitely still relevant. I don't really know what else can be done to fix it, though.

**Comment by laurencebgood** [comment]
This is still not fixed.

**Comment by laurencebgood** [comment]
I'm using totally stock Android 12 with stock chrome on a pixel 3 and still
have this problem with Signal (and only with Signal). I'm happy to try to
gather any useful information to figure this issue out, but I don't know
what would be useful to you.
