### ISSUE TITLE
Not able to share multiple files from file manager

### ISSUE THREAD

**Issue by r0hitm** [signalapp/Signal-Android#10687]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not able to send multiple files or entire folder(in which those files were) from file manager. However, I am able to send one file from file manager.
I have tried multiple times closing and opening both file manager and signal.

Note: I was trying to send 5 pdf files from size 100-500 kb.

### Steps to reproduce
- open file manager on android phone
- select multiple files
- click on send 

**Actual result:** Signal app is not listed in the send via prompt.

**Expected result:** Signal app should be listed in send via prompt.

### Device info

**Device:** Realme RMX 2030
**Android version:** 10
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/f81f375d9e048e108d8a9de63b97bad6c1965892306de65afdcde5364c815e9d

**Comment by rajasekharponakala** [comment]
any progress on this ?

**Comment by rohitmehtainventor** [comment]
No. The bug is still present.

**Comment by Flova** [comment]
This issue is still relevant and a missing feature. Would it be possible to reopen?

**Comment by greyson-signal** [comment]
Hi there, this is a feature request, not a bug report. We only use github for bugs. You can discuss features on [the forum](https://community.signalusers.org/). Thanks!

**Comment by Flova** [comment]
Ah okay. Thanks for the info!
