### ISSUE TITLE
Background service is still running in background when Notification settings is off

### ISSUE THREAD

**Issue by amirmahdi-nsh** [signalapp/Signal-Android#10697]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello everyone, I have google play services disabled so Signal will be in background to deliver notifications.
But due to my low-mid phone only has 1gb ram and I have no problem with not having incoming notification so I disabled all notifications from Signal Settings but the still Signal service is remain in background(and the notification saying that signal is running in background)

### Steps to reproduce
- Install Signal on a device without Google Play Services
- After login and etc go to Signal settings -> Notifications -> Turn off Notifications from all sections
- Go back from app and force stop app and reopen it 

**Actual result:** notification service starts running in background again 
**Expected result:** Then notification settings is off it's expected the notification service didn't run in background. because it have not any benefit

### Screenshots
I don't think it's required to provide screenshot for this particular issue :)

### Device info

**Device:** Nokia 2.1
**Android version:** 10
**Signal version:** 5.1.9

Sorry if I have some grammatical mistakes.

**Comment by Leptopoda** [comment]
As this is a fairly edge case I can't see much development commuted to this one hence I'll share some ideas.
You could try doing the opposite of what the [help Center suggests] (https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#android_notifications_troubleshooting_os) when messages are not coming in
As this is a fairly long article I'll just quote one thing
>Nokia

>  -  Android phone settings > Battery > Background activity manager > ensure that the toggle is disabled for Signal.
![Screenshot_20210117-235902_Settings](https://user-images.githubusercontent.com/25266387/104858616-e3c38800-5920-11eb-9c06-e90b9a25b921.png)


There might also be more Info's

**Comment by amirmahdi-nsh** [comment]
Thanks but unfortunately it doesn't affect much.
I also tried to turn on background restriction but it doesn't stop Signal to running in background.

I think the reason of this is because Signal shows a notification when it's run in background and so system thinks it's running in foreground not background and do not force stop it.

**Comment by Leptopoda** [comment]
You can also disable that particular notification in the notification channel 'other' 
keep in mind that while being in a call no status notification to quickly return to the call will be displayed

**Comment by amirmahdi-nsh** [comment]
I know how to disable `Background connection enabled` notification. But the main problem is the signal is still runs in background and use some memory(RAM) space.
My goal is stop signal to consume less resources.

I never used and don't want use Signal calling because I just want to use signal as a simple text only messenger app.
What I'm saying is please add an option in Signal settings which bring the ability to disable Signal background service.
This is useful for someones who don't takes care of Signal calling and don't want to have any notification until he/she didn't open in the program.

thanks a lot

**Comment by Leptopoda** [comment]
this seems like a feature request to me and therefore should be made on the [community forum](https://community.signalusers.org)
something related might be
https://community.signalusers.org/t/chat-only-signal-apk/19521
which could be adapted to to something like 'make signal run on low end devices'

**Comment by amirmahdi-nsh** [comment]
Now that  I think more about it, yes. It can also be a feature request. but the purpose of this issue wasn't publish something like Signal lite version.

Anyway I will close this issue and open a new this feature request issue. Thanks

**Comment by Leptopoda** [comment]
Yeah I just wanted to point out that devs will probably not see this as a bug and therefore would overlook it when posted here instead of the forum

**Comment by amirmahdi-nsh** [comment]
Corresponding feature request is https://community.signalusers.org/t/an-option-to-making-able-to-disable-signal-to-run-in-background-in-nogsm/24538
