### ISSUE TITLE
After clicking on pencil button the contact list opens but some contact names are shown as "unknown" 

### ISSUE THREAD

**Issue by C4P4E7** [signalapp/Signal-Android#10691]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After clicking on pencil button the contact list opens but some contact names shown as "unknown" 

### Steps to reproduce
- Open signal app
- Click on pencil button
- Contact list opens but with some "unknown " contact names

**Actual result:** It should show same name as saved in contacts
**Expected result:** It shows the name as "Unknown"

### Screenshots

![Screenshot_2021-01-17-17-27-15-721_org.thoughtcrime.securesms~2.jpg](https://user-images.githubusercontent.com/73741669/104839810-a8f22d80-58e9-11eb-8716-abe740e7d1c5.jpg)

### Device info

**Device:** Redmi Note 7 Pro
**Android version:** 10
**Signal version:** 5.1.9

### Link to debug log

https://debuglogs.org/eb8cd7a88511a02efcfb4bcf1500a83b5d3f77b1019eb3a7413efc42a1e025d5

**Comment by oxygi** [comment]
Same here.

**Comment by PythonCreator27** [comment]
Same here... but it loads within a minute and the contact name is shown.

**Comment by oxygi** [comment]
No, not for me. It is still there.
