### ISSUE TITLE
Cannot register with Signal APK from website without Google Play Services

### ISSUE THREAD

**Issue by aranym0** [signalapp/Signal-Android#10695]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The latest Signal APK (version 5.1.9 at the time of writing) from the Signal website (https://signal.org/android/apk/) does not work past the initial phone number prompt without Play Services installed. I believe it is intended to be usable on a device without Play Services installed, which is why I am making this issue.

### Steps to reproduce
- Install Signal APK from above website on a device without Google Play Services installed
- Open Signal app and press continue button, then enter phone number on next screen
- Observe an error popup that reads "Google Play Services is updating or temporarily unavailable. Please try again."

**Actual result:** I receive the Play Services error and cannot continue with registration.
**Expected result:** The registration continues normally.

### Screenshots

![Screenshot_20210117-095354_Signal](https://user-images.githubusercontent.com/73146467/104849074-7b878e80-58ad-11eb-8560-6bd3412cbf1e.jpg)

### Device info

**Device:** Samsung A11 (SM-A115U)
**Android version:** 10
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/5e10473005a331a84e1880d5e79621895879f936aeda0f4a4244cff44c27fe92

**Comment by Leptopoda** [comment]
> (Captured using ADB, since I cannot access app settings to use the built-in "Submit debug log" tool.)

from the signal [support article](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) about debug logs

> Steps to share a debug log from Signal's registration or PIN flow:
>
> Select Contact Support from the screen or follow steps below.
>
>    - Tap 8x on an empty space on the screen.
>    - Tap and hold to copy the URL.
>    - Paste the URL into a new issue form.


Sorry for not contributing to the issue just stumbled across it and wanted to let you know

**Comment by aranym0** [comment]
Ah, haven't seen that page. Thanks!
URL in issue updated to new debug log.
