### ISSUE TITLE
Selection of multiple Messages 

### ISSUE THREAD

**Issue by alxris1** [signalapp/Signal-Android#10690]
Hi there,

at the current moment it is not possible to select multiple Messages (when trying to delete them for example).
You can only select one at a time, which can be quite frustrating.

Please add a feature, that allows selection of multiple messages.

Kind regards

**Comment by sandeepkota** [comment]
Support is already there, please read documentation.
https://support.signal.org/hc/en-us/articles/360007320491-Delete-messages-and-alerts

**Comment by alxris1** [comment]
Hi, 

thanks for your answer.
Unfortunately i dont see where this link says anything about deleting multiple messages at once.

**Comment by Sgn-32** [comment]
From the [link](https://support.signal.org/hc/en-us/articles/360007320491-Delete-messages-and-alerts):

To delete alerts or messages:

    Open the chat.
    Tap and hold on a message bubble or alert.
    Optional, select multiple messages:
        Tap more select.png and then tap any additional message bubbles or alerts.
        Tap settings More.png > Select multiple and then tap any additional message bubbles or alerts.
    Tap delete TrashCan.png.
    Select Delete for me to confirm.

**Comment by alxris1** [comment]
Oh i see, thanks for the explanation.

I still think it would be easier if you could select multiple messages "right away", like:
Hold one message until it's selected, select the other ones by simply tapping.

Selecting one messsage, then tapping the option to select multiple ones and then selecting the other ones seems quite unintuitive to me, it doesn't really "flow".

But maybe that's just me being too used to using whatsapp and telegram.

**Comment by Sgn-32** [comment]
That "flow" was before introducing the emoji reaction. After Long-pressing a message, you had could select more messages.
Now this is possible, when you do that on an alarm message, like "missed call 23:12", or "Mike added Joe to that group".

You can continue discussing on the community forum, for example here:
https://community.signalusers.org/t/double-tap-to-add-an-emoji-reaction-to-a-message/17608

You can use your github account to login to https://community.signalusers.org

**Comment by alxris1** [comment]
Alright, thanks for the info :D
