### ISSUE TITLE
Add Nokia 2.3 to the AEC blocklist

### ISSUE THREAD

**Issue by happychameleon** [signalapp/Signal-Android#10706]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When calling a Nokia 2.3 I hear a distorted echo of my own voice, when it is on loud speaker

### Steps to reproduce
- Call user with Nokia 2.3
- Speak
- Appreciate the sweat discomfort of your own voice being piped back to you

**Actual result:** I hear my own words be repeated back to me with a slight delay
**Expected result:** When speaking I would like to not hear my own words repeated back to me

### Device info

**Device:** Nokia 2.3
**Android version:** 10
**Signal version:** Signal 5.1.9

### Link to debug log
https://debuglogs.org/e37b18f29e5cb5fd61f8b0ccdb63b0bd870d9165e5be8793e78cdbd5b5e2bd3e

**Comment by bkqtnte10** [comment]
related to #10402

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
