### ISSUE TITLE
Text on Startup Screen after fresh install is aligned wrong

### ISSUE THREAD

**Issue by simonmueck** [signalapp/Signal-Android#10705]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When installing Signal on an Huawei p20 the text "Nutzungsbedingungen und Datenschutzerklärung" is not aligned correctly. It's aligned to the left and not in the center. I believe the fix is quite important since it's the first thing people are going to see. - the first impression so to say

### Steps to reproduce
Reinstalling Signal on my device and launching the app.

**Actual result:** Text is aligned to the left with no padding at all
**Expected result:** Text should be aligned in the center

### Screenshots

![Signal Screenshot](https://user-images.githubusercontent.com/71900957/104856085-b66ede00-5910-11eb-8bfc-261ca4ed0360.jpg)

### Device info

**Device:** Huawei P20
**Android version:** 10
**Signal version:** 5.1.9

**Comment by Caerbannog** [comment]
This will fix it: https://github.com/signalapp/Signal-Android/pull/10694
