### ISSUE TITLE
Unable to send or receive messages

### ISSUE THREAD

**Issue by abh-oss01** [signalapp/Signal-Android#10712]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to send or receive any messages on signal beta app since over 6 days now, there might be some issue with signal beta on android, because I can send & receive messages on my pc signal app without any problems.

### Steps to reproduce
- Open signal app on the phone
- Write a message to any contact (including self) and send 
- It is not sent, the circle keeps spinning forever

**Actual result:** The message is never sent, it keeps spinning forever.

**Expected result:** Message gets sent

### Screenshots

![20210118_090909.jpg](https://user-images.githubusercontent.com/56572179/104872149-0da59a80-5973-11eb-897a-b12bff0db30b.jpg)

### Device info

**Device:** Realme 6 pro
**Android version:** 10
**Signal version:** 5.2.3 from play store

**Comment by bme13** [comment]
Hi,
Did you already followed the troubleshooting page.  https://support.signal.org/hc/en-us/articles/360009303072-Troubleshooting-sending-messages?
In addition to that it it advised to include a debug log. If you think it's beta related you can also post it in the beta thread on the community forum. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-2-release/22202/77.

**Comment by abh-oss01** [comment]
Thanks for replying, I found out the issue is with Beta version, so I uninstalled it, and downgraded to stable signal, which "fixed" it for me.

**Comment by abh-oss01** [comment]
Sure, thanks :)
