### ISSUE TITLE
Gradle Build error 

### ISSUE THREAD

**Issue by Shubzz-02** [signalapp/Signal-Android#10713]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi when I am trying to build  android source, gradle is giving an error.

### Steps to reproduce
-  ./gradlew build

**Actual result:** It should compile successfully and give me an apk.
**Expected result:**  Getting some error

### Error 
` Execution failed for task ':buildSrc:compileJava'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not resolve com.android.tools.build:apksig:3.5.1.
     Required by:
         project :buildSrc
      > Could not resolve com.android.tools.build:apksig:3.5.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.5.1/apksig-3.5.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.5.1/apksig-3.5.1.pom'.
               > Connect to dl.google.com:443 [dl.google.com/203.208.39.225] failed: connect timed out `

### Detail Log link
[Gradle Build Error Log](https://gradle.com/s/lc3skwhwujqfq)

**Comment by Shubzz-02** [comment]
Well issue solved .....
https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/  gives 404 error

I modified build.gradle

replaced  :- 
```
repositories {
    google()
}
```
with 
```
repositories {
        mavenCentral()
        jcenter()
}
```
and it worked for me..

**Comment by shiv-u** [comment]
@Shubzz-02 I think it's better to close this issue if it's solved.
