### ISSUE TITLE
Update Troubleshooting Notifications Page - Ulefone Armor 9 Specific information

### ISSUE THREAD

**Issue by hal88** [signalapp/Signal-Android#10714]
See #10276 

Please add the following information for the Ulefone 9 to Troubleshooting Notifications page
https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

settings->smart assistant->app blocker select the signal app from the list

uncheck "boot blocker" "start blocker" "background blocker" "background cleanup"

This was a showstopping bug for me until @MrTuffaha proposed this solution for the Ulefone Armor 9. I don't know if it is applicable to other phones experiencing the same issue. It is /very/ nice to have a functioning signal on my phone again.

**Comment by Leptopoda** [comment]
Hi there!
This does not seem like an app specific question but rather like a request regarding the website. 
Requests usually go through our [community forum](community.signalusers.org)

Join us over there maybs there already is an open thread regarding this.

**Comment by hal88** [comment]
Hi.

This was a horrible show-stopping bug resulting in embarassment etc. It is now understood. Adding 2 lines to the "troubleshooting notifications page" for the Ulefone Armor 9 will save someone else all that grief and keep everyone affected joyful about signal. I have no doubt at all that the sofware did not behave as expected (a bug is present) and the result caused pain. For me that makes it an issue. The ideal fix would be signal just working without having to find obscure, unusual settings and change them. Failing that the signal app telling you that you will have to do that for it to work. Failing that have it in the troubleshooting documentation that is obviously incomplete for anyone affected. Or some better idea I haven't thought of.

I've dropped more than a few hours into it and donated some money in the great capacity crunch over the past few days. 

I'll leave the rest to you to do it the way you see fit keeping the avoidance of user-misery paramount as I'm sure you want to when you close this as "FIXED". 

At the very least these issues are potentially findable with a search engine now. 

Thanks again @MrTuffaha

**Comment by Leptopoda** [comment]
Hi there,
- I'm a normal user of signal and not affiliated to them at all. So please stop yelling at me (that's what I feel regarding your reply)
- The problem with those hardware optimizations is because of the device manufacturer and not signal. Signal can't do anything about that, you rather have to file an issue with your device
- the android devs have nothing to do with the team related to the website/support articles. That's why I suggested posting it on the forum as there is no repo regarding the website.

And if you still share the same opinion:
- I DON'T CARE
- I just wanted to help you with your problem and direct to the right hands.
- not my problem if this issue will never be fixed

**Comment by hal88** [comment]
Hmm. Ok. This is a communication failure if I've ever seen one.

Bugs exist. There is no implicit criticsim of yourself or anyone associated with the signal project in reporting a bug. A bug is frequently nobody's fault just a thing that exists in software. Some bugs users can live with. Some bugs developers can live with. Some not. I can't decide for anyone else whether they can live with the bug. It does appear to be the sort of thing that developers might find interesting to me. So what?

Any user trying to install signal on a Ulefone Armor 9 is extremely likely to have a bad time and what will be visible to them is that signal is not working correctly. (In contrast WhatsApp is whitelisted to work fine, go figure). Some will try to get it to work correctly. Some will give up. Signal's mission of encryption to the masses suggests that the good people at signal would prefer it to work for all with the minimum of fuss and not fail for those who might want it even if they're not super-tech-literate.

The fix for the issue with the Ulefone Armor 9 has been found. Hurrah! 

This may or may not be instructive for other phones where users report critical issues with their signal installation once they have installed it that I have been reading about here. Is it the same on the Nokias? Or a different cause of the same symptom? I can't know. But I can report it.

Given the incredible difficulty of making a general purpose messaging app work on multiple versions of android (and IOS! and destkop windows,apple,linux), multiple devices and multiple vendor "modifications" to android, such as this one /appears/ to be (again I don't /know/ that is for sure). Signal devs may want to know about this. I think I would? At the minimum the quick fix of adding to the list of broken on default installation on the page mentioned with the necessary workaround seems like a good idea to me to fix the bug.

There are other possible fixes. They may or may not be truly horrendously bad ideas for so many reasons that only someone working closely on the app could decide if any of them or any other fix is an appropriate trade-off. (Introspect device, throw up a link for troublesome ones on installation?) Is this particular cause of a critical issue one that generalises to other devices. SIgnal developers will not know and have a chance of making the best call if they've never heard about it.

I'll let them make the necessary call on how they wish to close that bug. I don't wish to join documentation projects or web teams or any of that sort of thing. The overhead of time and emotional energy involved for a 2 line edit is usually prohibitive and I don't wish to do it. I think that's a valid and reaonable preference to have. You are quite entitled to disagree.

On a personal experience note it is unpleasant not to recieve messages one would consider important until after they have gone stale because one's messaging app is silently broken. How important that mode of failure is to the development team given their estimate of the number of users affected is up to them.

Thanks for your thoughts on this issue.
All the very best to you.
