### ISSUE TITLE
Signal says backups can be done on external memory, but they can't, actually

### ISSUE THREAD

**Issue by klint** [signalapp/Signal-Android#10720]
- [X ] I have searched open and closed issues for duplicates
- [ ]X I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
Signal parameters screen says conversation can be saved on external memory, but conversations backup does not ask for backup location when SD card installed and all backups are saved on internal card..

### Steps to reproduce
- Make sure an SD Card is installed in the phone (ExFAT)
- Open Signal
- Go to Parameters/Conversations (sorry, Signal is in French for me, I don't know the exact wording in the English version)
- Click on "Backup conversations" (check that the message just below says" Sauvegarder les conversations dans la mémoire externe"
- If backups are already active, then deactivate them
-  Click on the Activate button

**Actual result:** A pop up is displayed showing the passphrase. Then, when proceeding with the backup, it appears that the target folder is signal/backups on the INTERNAL card.

**Expected result:** A pop up should be displayed to ask for the backup target folder which can then be chosen on the SD Card.

### Screenshots

![image](https://user-images.githubusercontent.com/218971/104918361-ecee3c80-5994-11eb-906f-95ff059c7e6d.png)

### Device info
**Device:** Redmi Note 7 (with SD Card installed, in ExFAT)
**Android version:** 9
**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/83031037fd01be7c1650630c5554d0355b9ebfaabfa1d0b4e1a428b2262a4786

**Comment by Leptopoda** [comment]
The string in question is located in https://github.com/signalapp/Signal-Android/blob/ff11609a823fc95bee9d438183a4ee95fe011ab2/app/src/main/res/values-fr/strings.xml#L2367
the original string is here
https://github.com/signalapp/Signal-Android/blob/ff11609a823fc95bee9d438183a4ee95fe011ab2/app/src/main/res/values/strings.xml#L2840
In this case external storage states the non signal internal and encrypted one and not where the storage is located i.e. not external SD card

As the string is not making any technical difficulites (bug) and you rather propose to change it I still think you are actually making a feature request.
Also you could've easily changed the topic of your last post.

When you still think this is a bug and should not be reported to the forum as a feature request I give up. Your problem when devs won't look as it as it isn't a bug.


have a great day Leptopoda

**Comment by klint** [comment]
Thanks again. Now that I understand what "external" means, I agree this is not a bug. Yet, this is worded rather ambiguously, but I can live with it and will go on with that conversation on the forum for the moment.
Also, maybe it would worth updating the support pages (this one here: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages) by mentioning the cases where the user is able to select a target folder (is it on Android 10+ only for instance ?), and also by clarifying the meaning of the word "external"? 
Do you know where such a suggestion for the support pages can be placed? Thanks

**Comment by Leptopoda** [comment]
> Also, maybe it would be worth updating the support pages (this one here: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages) by mentioning the cases where the user is able to select a target folder (is it on Android 10+ only for instance ?), and also by clarifying the meaning of the word "external"?

there currently is no official way to communicate this just post it in #generral-discussion on the forum 

> Yet, this is worded rather ambiguously, but I can live with it and will go on with that conversation on the forum for the moment.

**Comment by klint** [comment]
Will do. thanks

**Comment by klint** [comment]
See https://community.signalusers.org/t/2-proposed-updates-for-the-support-page-about-backup-restore/24272
