### ISSUE TITLE
Slightly too small icons on Samsung's new One UI 3.0 (Android 11)

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-Android#10723]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating a Samsung Galaxy S10 with the new One UI 3.0/Android 11 update I noticed that the contact icons are slightly too small resulting in black edges in two interface elements outside the Signal app (see the screenshots below for clear examples):
- When I receive a Signal message, the contact's icon in the notification panel is too small
- When I long press the Signal app icon to open the quick actions, the icon's of the shown contacts are also too small

I'm not 100% sure this issue is with Signal or with Samsung, but I didn't notice similar design problems with notification/quick action icons in other apps. Also, this is a really minor issue, but I thought I'd report it as Samsung has quite a large market share and more and more Samsung phones will be running One UI 3.0/Android 11, so it would be nice if the design of these frequently viewed icons looks good. Thanks for developing Signal 🎉!

### Steps to reproduce
- Use Signal on a Samsung phone with One UI 3.0/Android 11
- Receive and view a Signal notification
- Open the quick actions by long pressing the Signal app icon on the home screen/launcher

**Actual result:** The contact icon's have black edges
**Expected result:** Show the contact icons without black edges

### Screenshots
Screenshot showing the black edges around a contact's icon when receiving a Signal notification:
![Screenshot_20210114-133746_Settings](https://user-images.githubusercontent.com/696839/104936547-f71c3500-59ac-11eb-8a7f-b185708167e1.jpg)

Screenshot showing the black edges around contact icons when long pressing the Signal app icon on the home screen/launcher:
![Screenshot_20210114-133805_One UI Home](https://user-images.githubusercontent.com/696839/104936845-5c702600-59ad-11eb-8fe0-ff2dfa576f11.jpg)

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 11.0
**Signal version:** 5.1.9

**Comment by MasterEvarior** [comment]
I am having the exact same issue on my Galaxy S10+ since updating to One UI 3.0.

**Comment by Leptopoda** [comment]
This seems to be an issue with the usage of adaptive icons 

The black bar you see is because Samsung likes to use the so called 'squarecle' but the icons provided by signal are sircle only.

As signal currently does not support adaptive 'user icons' when provided the system ui this rather seems like a feature request to me instead of an issue.

**Comment by siccovansas** [comment]
This is fixed since 5.16.0 via this commit https://github.com/signalapp/Signal-Android/commit/e20d6b63cf3480c0d3e5497be09038884796885b

Thanks 🎉!
