### ISSUE TITLE
Cannot receive / send messages from / to some of my contacts.

### ISSUE THREAD

**Issue by meinto** [signalapp/Signal-Android#10727]
Some of my contacts can't send me messages and they don't get my messages either. There is also only one checkmark on my sent messages with these contacts. 

Possibly connected:

https://github.com/signalapp/Signal-Android/issues/10693
https://github.com/signalapp/Signal-iOS/issues/4792
https://github.com/signalapp/Signal-iOS/issues/4779
https://github.com/signalapp/Signal-iOS/issues/4781

**Comment by wurstsemmel** [comment]
I can confirm this partially. After using the Signal Desktop App once, my Signal Mobile App is almost back to normal. A few contacts still show the faulty behaviour. Receiving messages from those contacts does not work reliably, sent messages are stuck in the message status "sent" and do not change to "delivered".

Signal 5.2.3
Samsung Galaxy S9
Android 10
One UI-Version 2.5

**Comment by meinto** [comment]
Assuming my device is the sender, I finally resolved it by reinstalling the app on the receiver device. Sadly this only worked for us by reinstalling without using the option to restore from backup. So the past messages where lost.

**Comment by wurstsemmel** [comment]
> A few contacts still show the faulty behaviour.

In the meantime my Signal App works as expected for all contacts. My guess is that all communication partners need to have the most recent App version installed and in addition the Signal network needs time to get back to normal operation.

**Comment by greyson-signal** [comment]
Ok, I'm going to assume this was related to our outage. Please open a new issue if it happens again, thanks!
