### ISSUE TITLE
I got out of a group, but people were added in the group by me 

### ISSUE THREAD

**Issue by mohdmaskati** [signalapp/Signal-Android#10728]
I was in a group and I got out of the group, I was informed that I added a person before I left (and this did not happen because this person I do not know) and this happened with 3 people in the group
![signal-2021-01-18-090442](https://user-images.githubusercontent.com/63052666/104969863-b814d080-59fa-11eb-8401-c9beed42370a.jpeg)

**Comment by telemetrieTP23** [comment]
Same here, I guy that left our group month ago,
suddenly added 5 persons all already left the group also month or days ago.
The Strange is everyone in the group got the Message that the Owner of the group added the peoples,
only the owner of the Group got the Message that the guy that left the group month ago added the people.
