### ISSUE TITLE
Cannot load or see any contacts

### ISSUE THREAD

**Issue by timc986** [signalapp/Signal-Android#10739]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot see any contact in the Signal app. 
Only managed to see one contact after asking him to send me a message first, but in the Signal app this contact still appears as "Unsaved Signal user" [link to official guide](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts)
All my phone contacts are saved and synced with the google contacts

Have tried a lot of things but none of those helps. 
Eg. 
Checked the android setting option to allow access to contact
Clear cache
Clear data
Refresh contact in Signal
SMS Enabled or Disabled
Uninstall and reinstall

### Steps to reproduce
- Grant access to contact in android settings
- Enabled or Disabled SMS in Signal app settings
- In the Signal app, click on the pencil button then click refresh

**Actual result:** Contact list is empty
**Expected result:** Contact list should show my phone contacts

**Extra information**:
I have tried to follow the official article to refresh the contact list and re-sync the contacts. [link to official guide](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts)

> Go to Android Settings > Accounts > Signal > Menu > Remove Account. The alert of clearing data is incorrect, your messages will not be deleted.
In Signal, tap Android_Compose.png Compose to view your Signal contact list.
Pull down on your contact list to refresh and update. 

However on my phone, there is no Signal app under the Accounts.
I tried to press on the plus button to add it, nothing happen and then my phone just freezed until I press the android back button.

I have also tried to add a new contact in the Signal app. 
The contact is successfully added to my phone, however it still doesn't show up in the Signal app and I also can't seach for it.

Have asked a few friends on Android and some of them are having the same problem. 
My other group of friends on IPhone have the Signal app works fine though.

### Screenshots

Can't take screenshots

### Device info

**Device:** HTC 10
**Android version:** 7.0
**Signal version:** 5.2.3

### Link to debug log

Added: My debug log after enabling sms and refresh the contact list: [https://debuglogs.org/8c3b27c4d212334e8d965b675298390e585fab1422d1bc2bf96068c7ae2bdded](https://debuglogs.org/8c3b27c4d212334e8d965b675298390e585fab1422d1bc2bf96068c7ae2bdded)

**Comment by Genis-Sage** [comment]
Hey @timc986
a debug log would definitely help here

Also, when you are in the Android settings about accounts

Does it directly freeze, when the press the +, or only after you selected the type of account?

Does the freeze also happen, when you delete Signal?
If yes, already your Android seems to have a strange problem

**Comment by timc986** [comment]
Hi @Genis-Sage 

My debug log after enabling sms and refresh the contact list: [https://debuglogs.org/8c3b27c4d212334e8d965b675298390e585fab1422d1bc2bf96068c7ae2bdded](https://debuglogs.org/8c3b27c4d212334e8d965b675298390e585fab1422d1bc2bf96068c7ae2bdded)

My phone started to freeze after I select the Signal app inside the + menu. However I also tried to select another app such as the Google Duo, the Duo app did open up and works as expected, so I guess my phone is okay? Not quite sure what is going on here.

Thanks

**Comment by direc85** [comment]
This seems to be the case with all devices (almost all?) devices running Sailfish OS, too. It's [an old issue](https://together.jolla.com/question/220136/signal-does-not-show-contacts/), with [newer reports](https://forum.sailfishos.org/t/support-of-signal-messaging-application/1564) too, but the cause can be different...

I'm having a very similar error on Sailfish OS 4.0.1.45/.48 with Signal 5.3.12:

    Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/org.thoughtcrime.securesms/databases/signal.db, table = recipient, query = SELECT _id, system_display_name, phone, email, system_phone_label, system_phone_type, registered, ab
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
    	at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:237)
    	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:71)
    	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
    	at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1740)
    	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1692)
    	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1781)
    	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$query$2(SQLiteDatabase.java:138)
    	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$query$2$SQLiteDatabase(Unknown Source:0)
    	at org.thoughtcrime.securesms.database.-$$Lambda$SQLiteDatabase$cvMxOy0u0-aa46LyDnbjGx12KKk.run(Unknown Source:16)
    	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:92)
    	at org.thoughtcrime.securesms.database.SQLiteDatabase.query(SQLiteDatabase.java:138)
    	at org.thoughtcrime.securesms.database.RecipientDatabase.getSignalContacts(RecipientDatabase.java:2300)
    	at org.thoughtcrime.securesms.contacts.ContactRepository.querySignalContacts(ContactRepository.java:117)
    	at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.getContactsCursors(ContactsCursorLoader.java:309)
    	at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.addContactsSection(ContactsCursorLoader.java:162)
    	at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.getUnfilteredResults(ContactsCursorLoader.java:128)
    	at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.loadInBackground(ContactsCursorLoader.java:102)
    	at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.loadInBackground(ContactsCursorLoader.java:54)
    	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
    	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
    	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
    	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    	at java.lang.Thread.run(Thread.java:764)

It tries to synchronize 29 contacts, so it sees them. This error message is repeated four times, after which I get this:

    ContactsDatabase: Adding number: +REMOVED ( <-- repeated 29 times )
    DatabaseUtils: Writing exception to parcel
    DatabaseUtils: android.content.OperationApplicationException: insert failed
    DatabaseUtils: 	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:292)
    DatabaseUtils: 	at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:286)
    DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:2405)
    DatabaseUtils: 	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
    DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:181)
    DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:731)
    DirectoryHelper: Failed to update contacts.
    DirectoryHelper: android.content.OperationApplicationException: insert failed
    DirectoryHelper: 	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:156)
    DirectoryHelper: 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:522)
    DirectoryHelper: 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
    DirectoryHelper: 	at android.content.ContentResolver.applyBatch(ContentResolver.java:1626)
    DirectoryHelper: 	at org.thoughtcrime.securesms.contacts.ContactsDatabase.setRegisteredUsers(ContactsDatabase.java:107)
    DirectoryHelper: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:321)
    DirectoryHelper: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:261)
    DirectoryHelper: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:101)
    DirectoryHelper: 	at org.thoughtcrime.securesms.ContactSelectionActivity$RefreshDirectoryTask.doInBackground(ContactSelectionActivity.java:144)
    DirectoryHelper: 	at org.thoughtcrime.securesms.ContactSelectionActivity$RefreshDirectoryTask.doInBackground(ContactSelectionActivity.java:133)
    DirectoryHelper: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
    DirectoryHelper: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    DirectoryHelper: 	at java.lang.Thread.run(Thread.java:764)
    Cursor  : Filling cursor window with start position:0 required position:0
    DirectoryHelper: [refresh] network: 6697  process-cds: 193  handle-unlisted: 2  update-registered: 29  contacts-db: 1216  total: 8137
    JobSchedulerScheduler: JobScheduler enqueue of NETWORK (-1733499378)
    Job     : [JOB::ff052796-1a8d-472a-8a75-4d58d8e1b134][StorageSyncJob] onSubmit() (Time Since Submission: 83 ms, Lifespan: 86400000 ms, Run Attempt: 1/1)
    JobSchedulerScheduler: Waking due to job: -1733499378
    JobRunner: [JOB::ff052796-1a8d-472a-8a75-4d58d8e1b134][StorageSyncJob][1] Running job. (Time Since Submission: 165 ms, Lifespan: 86400000 ms, Run Attempt: 1/1)
    GoogleInputMethodService: GoogleInputMethodService.onStartInput():1906 
    SessionManager: SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first
    Cursor  : Filling cursor window with start position:0 required position:0
    Cursor  : Filling cursor window with start position:0 required position:0
    Cursor  : Filling cursor window with start position:0 required position:0
    Cursor  : Filling cursor window with start position:0 required position:0
    Cursor  : Filling cursor window with start position:0 required position:0
    Cursor  : Filling cursor window with start position:0 required position:0
    StorageSyncJob: Our version: 16, their version: 16
    Cursor  : Filling cursor window with start position:0 required position:0
    chatty  : uid=10056(org.thoughtcrime.securesms) signal-JobRunne identical 6 lines
    Cursor  : Filling cursor window with start position:0 required position:0
    StorageSyncJob: [Local Changes] No local changes.
    JobRunner: [JOB::ff052796-1a8d-472a-8a75-4d58d8e1b134][StorageSyncJob][1] Job finished with result SUCCESS in 363 ms. (Time Since Submission: 528 ms, Lifespan: 86400000 ms, Run Attempt: 1/1)

And I believe that's all there is to it in the log. I can, of course, submit more, but the support function doesn't seem to work on Sailfish OS either, so I'm stuck with `logcat` output.
