### ISSUE TITLE
Data Usage issues 

### ISSUE THREAD

**Issue by JunaidLone17** [signalapp/Signal-Android#10733]
----------------------------------------

### Bug description
When sending images or videos, like WhatsApp the size gets reduced thereby decreasing data usage and sent time, Add this feature

### Steps to reproduce
- open signal
- go to any chat
- send a video or image, it doesn't compress thereby decreasing size and helping data usage and time to send a file. 

### Device info

**Device:** Realme 3 pro  
**Android version:** 10
**Signal version:** latest

**Comment by Genis-Sage** [comment]
Hey @JunaidLone17

As stated in the issue template and the contributing guide, github is reserved for buds

Feature request belong into the community forum
community.signalusers.org


Also, Signal does compress media already, if they are large
Perhaps you picture are under the limit (I am not completely sure about the limits etc)
