### ISSUE TITLE
KbsEnclave not working

### ISSUE THREAD

**Issue by webix-209** [signalapp/Signal-Android#10732]
C:\Users\PC - 12\Desktop\Signal-Android\app\build\generated\source\buildConfig\debug\org\avenue\secure\BuildConfig.java:23: error: cannot find symbol
  public static final KbsEnclave KBS_ENCLAVE = new KbsEnclave("fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe","fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe", "a3baab19ef6ce6f34ab9ebb25ba722725ae44a8872dc0ff08ad6d83a9489de87");
                      ^
  symbol:   class KbsEnclave
  location: class BuildConfig

**Comment by bme13** [comment]
Hi,
Please note that github is used for bug reporting. If you need support for building please reach out to the community forum. See https://community.signalusers.org/.
