### ISSUE TITLE
Signal doesn't find US contacts with +1 in phone number

### ISSUE THREAD

**Issue by dzg** [signalapp/Signal-Android#10741]
Having lived abroad (not US) many of my contacts have a +1 in front of their US phone number.

Signal is NOT finding these contacts when I search by name, until I manually remove the +1.

Seems rather silly.

**Comment by happychameleon** [comment]
I can't reproduce your bug with my US American contacts.

Do you have a debug log?

**Comment by Leptopoda** [comment]
Just as @dzg said a debuglog would help a lot!
also you seem to not have used the ISSUE TEMPLATE so could you please update your post with it?
the raw version of the issue template can be located here https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE/bug_report.md
just copy paste all the contents into your issue and fill it out accordingly.

when done your post should look something like this



- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

**Comment by Serphentas** [comment]
Not sure if that's related, but I had the same case with a +41 number. I ended up doing a manual search for that number in Signal and the contact eventually showed up.

**Comment by Caerbannog** [comment]
if your contact joined Signal after you, refreshing the contact list might help.
You can do this by going on Signal's home screen, clicking the "pen" icon, then clicking a "Refresh" menu item.
