### ISSUE TITLE
Incognito keyboard setting not respected during pin creation

### ISSUE THREAD

**Issue by mrtenda** [signalapp/Signal-Android#10746]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When the keyboard opens to input the PIN in the "Create your PIN" screen, and the "Incognito keyboard" setting is enabled, the keyboard is not an incognito keyboard.

### Steps to reproduce
- Open Signal on Android and go to Settings > Privacy
- Ensure that a PIN has not yet been created
- Ensure that the "Incognito keyboard" setting is enabled
- Click "Create a PIN"
- Observe that the numpad-style keyboard that opens is not an incognito keyboard (bug)
- Click "CREATE ALPHANUMERIC PIN"
- Observe that the alphanumeric keyboard that opens is not an incognito keyboard (bug)

**Actual result:** The keyboards that open on the "Create your PIN" screen are not incognito keyboards
**Expected result:** The keyboards that open on the "Create your PIN" screen should be incognito keyboards

### Screenshots

![Screenshot_20210120-111651](https://user-images.githubusercontent.com/1281326/105203500-18129080-5b3b-11eb-8c7d-61aa394aa195.png)
![Screenshot_20210120-111657](https://user-images.githubusercontent.com/1281326/105203503-1b0d8100-5b3b-11eb-937c-556cf24d7d85.png)

### Device info

**Device:** Pixel 4a
**Android version:** 11
**Signal version:** 5.2.3

### Link to debug log
Seems unnecessary in this case but I can provide it if needed

**Comment by mrtenda** [comment]
This issue still seems to exist.

**Comment by cody-signal** [comment]
Hey there, this input is marked as password, which already disables anything related to auto-complete, suggestions, etc. In fact, trying to set the incognito IME option does nothing here because password is already more restrictive.
