### ISSUE TITLE
My Recipients Not Seeing My Typing Indicator

### ISSUE THREAD

**Issue by DarBeck** [signalapp/Signal-Android#10747]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am able to see the typing indicator when the person I'm texting is typing but they are not seeing my typing indicator even though the typing indicator setting is on.

### Steps to reproduce
- open chat with a contact
- ensure both parties have typing indicator turned on
- type a message

**Actual result:** Recipient does not see typing indicator
**Expected result:** Recipient should see typing indicator

### Device info
**Device:** Moto E (4) Plus
**Android version:** 7.1.1 (21, NDRS26.58-33-9-16)
**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/add1197fbf64764a8607930729fdc8f165f010e4cda52e9ede280453b8d7922c

**Comment by Caerbannog** [comment]
Hi @DarBeck !
I've looked at your debug log. Note: I'm not a member of the Signal team.

The typing indication seems to be sent correclty, there are mulitple lines like this:
> TypingSendJob][1] Job finished with result SUCCESS in 427 ms. 

1. Does the typing indicator work when you text another Signal contact?

2. Can you submit a debug log from the phone of the contact that can't see your typing indicator?

**Comment by DarBeck** [comment]
@Caerbannog it happens for every contact I try to text. Both Android and IPhone contacts.

This is the debug for an iPhone:

https://debuglogs.org/45f0bc7357196bb59143acd569a54ff57d20dc31edb0cafbf76d1b214ae28e75.zip

**Comment by Caerbannog** [comment]
> recipient debuglog:
> [TypingIndicators.swift:183 didReceiveIncomingMessage(inThread:address:deviceId:)]: 

I don't know how the iOS app works, but this might indicate that indicators are recevied but not displayed.

> Typing indicators are sent via sealed sender whenever possible and they are queued on an ephemeral channel which only delivers to devices that are “online” (e.g. actively connected to a WebSocket in Signal already).
> Source: https://community.signalusers.org/t/remember-the-current-message-mode-sms-or-mms-for-each-contact/2382/41

Did you configure your Signal app in a special way? Is your phone special in some way? (ex: no Google Play Services)

**Comment by DarBeck** [comment]
@Caerbannog Based on the testing I did the problem seem to be with the device. On the iPhone I am getting the typing indicators for all other contacts so that can be eliminated. 

There is no special setup that I am aware of. I am wondering if there is some type of glitch/bug with the Android OS version on the device. I would need to replicate this issue on a device running a similar OS.

**Comment by NilsIrl** [comment]
I am having the same issue except that I cannot see the typing indicator of person B, person B can see my typing indicators. I can however see typing indicators when someone else than person B is typing. This would suggest that the problem is coming from person B and not me. Person B and I are both on android.

**Comment by DarBeck** [comment]
> I am having the same issue except that I cannot see the typing indicator of person B, person B can see my typing indicators. I can however see typing indicators when someone else than person B is typing. This would suggest that the problem is coming from person B and not me. Person B and I are both on android.

Yea that's exactly what is happening. Could you provide the OS version for person B and device details if you have it

**Comment by NilsIrl** [comment]
> Could you provide the OS version for person B and device details if you have it

**Device**: `SM-G960F`
**Android version**: `8.0.0`
**Signal version**: `5.3.12`

**Comment by NilsIrl** [comment]
One thing I've also noticed is that the person who doesn't send typing indicators (even though they are turned on) takes a very long time to receive messages compared to other people. (the tick takes a long time to become a double tick and then to become filled double tick indicating the message was read)

**Comment by NilsIrl** [comment]
Other observations: if person B is using signal desktop then I can see their typing indicators. Also the chat with person B has a lot of latency in general. For example, sending messages (I'm talking the time it takes before there is 1 tick) is very slow compared to other contacts.

**Comment by DarBeck** [comment]
> Other observations: if person B is using signal desktop then I can see their typing indicators.
> 
> Also the chat with person B has a lot of latency in general. For example, sending messages (I'm talking the time it takes before there is 1 tick) is very slow compared to other contacts. Which is very surprising considering sending messages itself (intuitively) is something that isn't dependent on who you're talking to. May be linked to #9930
> 
> Also 1 difference between this contact and other contacts is that they joined when Signal was down in January.

I can also confirm that if person B is on desktop then the typing indicator shows. 

I think the problem is directly related to the device or the OS version. In my case it was Android OS 7 and the one you reported was Android OS 8. I haven't seen this issue with anyone running the latest Android versions. 

I will check to see if there is also a delay when I send a message to person B to see if its a common symptom for this issue.

**Comment by aeJ0E** [comment]
>     * [x]  I have searched open and closed issues for duplicates
> 
>     * [x]  I am submitting a bug report for existing functionality that does not work as intended
> 
>     * [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
> 
>     * [x]  This isn't a feature request or a discussion topic
> 
> 
> ### Bug description
> 
> I am able to see the typing indicator when the person I'm texting is typing but they are not seeing my typing indicator even though the typing indicator setting is on.
> ### Steps to reproduce
> 
>     * open chat with a contact
> 
>     * ensure both parties have typing indicator turned on
> 
>     * type a message
> 
> 
> **Actual result:** Recipient does not see typing indicator
> **Expected result:** Recipient should see typing indicator
> ### Device info
> 
> **Device:** Moto E (4) Plus
> **Android version:** 7.1.1 (21, NDRS26.58-33-9-16)
> **Signal version:** 5.2.3
> ### Link to debug log
> 
> https://debuglogs.org/add1197fbf64764a8607930729fdc8f165f010e4cda52e9ede280453b8d7922c

I had a similar issue where phone A (both android) could see typing indicators and the correct timestamp from phone B. But B did not see indicators nor correct timestamps from A. The read receipts worked for both phones. Settings were correct in signal app on both. Reinstalled signal on both phones but didn't fix. The problem was phone A was set to the wrong time zone. Changing that has fixed both issues.

**Comment by DarBeck** [comment]
@aeJ0E Thanks for that info. Will try that and report if it worked (or not) in my case.

**Comment by DarBeck** [comment]
@aeJ0E changing the time and time zone to automatic actually worked! That's such a weird bug though. Hopefully it gets fixed by the team.

**Comment by nitram147** [comment]
Same happened to my friend. After little investigation we found out that she had delayed time (unsynced) by -2 minutes. Once she changed setting to automatic time synchronization from mobile network, typing indicator started working.

**Comment by abdu1aziz** [comment]
I am also having the same issue with my signal app, on my android signal app, we are both running latest version of signal and we are both using same phones (make/model). No Typing indicator on both sides.

**Comment by greyson-signal** [comment]
If you're still having the issue, we would need logs from both you and your friend.

**Comment by IamRezaMousavi** [comment]
Typing and status icon don't showing

Me:
https://debuglogs.org/android/6.1.4/b15bbdd24ef70ae0728960c6dccdd605dff4122c4cd81cded0138bf1a9832c5a

My friend:
https://debuglogs.org/android/6.1.4/cea1c056d6d7fb3e88179d8ce96dce8f635644d8aa59e530c31550a880b90710
