### ISSUE TITLE
Not receiving text message

### ISSUE THREAD

**Issue by bljusruk** [signalapp/Signal-Android#10755]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using signal as default messaging aoplication on my Huawei P30 Pro phone, Android 10.

When my wife, who doesn't use signal, sends me a text message, I don't receive it in signal. It's only when I switch back to my phone's version of text messaging as a default that I receive her text message. 
**Expected result:**
Text message is received by my signal app when sent by non-signal user. 

### Device info
**Device:** Huawei P30 Pro
**Android version:** 10.1.0.181
**Signal version:** 5.2.3

**Comment by Caerbannog** [comment]
Try this: 

> Turn off chat features in the default Messages app. This was the issue for me for any contact who used the default android Messages app from Google. It should fix your problem if you had it enabled.
> https://github.com/signalapp/Signal-Android/issues/10498#issuecomment-758739975

**Comment by Leptopoda** [comment]
Without a debuglog it's nearly impossible to diagnose the problem

**Comment by bljusruk** [comment]
@Caerbannog Thank you, your tip worked.
