### ISSUE TITLE
Video calling issue

### ISSUE THREAD

**Issue by jaissugam** [signalapp/Signal-Android#10754]
- I have searched open and closed issues for duplicates
- I am submitting a bug report for existing functionality that does not work as intended
- I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video call is not getting through even though both the caller and receiver have healthy internet connection. The app shows calling on the caller's device but there's no ringing at the receiver's device for a long time and sometimes the call gets hung up itself.

### Steps to reproduce

**Actual result:** Call gets ringing after waiting for a while and sometimes the call disconnects though both devices have strong signals
**Expected result:** If the receiver has good internet connection, his/her device should immediately ring when the caller calls.

### Device info

**Device:** Huawei and Samsung
**Android version:** 9.0 and 10.0

**Comment by Caerbannog** [comment]
Hi @jaissugam,
I'm not an expert here, but I think that your problem will be hard to diagnose with this information.

Can you capture a debug log to help troubleshooting? I'm not sure on which device, so could you capture the log on both after an unsucessful call?
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log

**Comment by jaissugam** [comment]
Hey @Caerbannog ,
Thanks for the concern. The video calling has been smooth now after an update.
