### ISSUE TITLE
echo on Xiaomi Mi A1

### ISSUE THREAD

**Issue by csipu** [signalapp/Signal-Android#10768]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am calling a Xiaomi Mi A1 (destination) phone using video call (my phone is OP6T) and it has terrible echo on my side only, because the Mi A1 has some problem with the echo cancellation.
I have found the same issue is reported in #7956, but there Android version was 8.0.0. In my case the Mi A1 is on 9.0
Can you please add the Mi A1 to the Hardware AEC Blacklist?
I have added the debuglog.

### Device info

**Device:** Xiaomi Mi A1
**Android version:** 9.0.0
**Signal version:** 5.2.3

### Link to debug log

https://debuglogs.org/91348f59caeb726aaa607276389727847847eb1bfded8ceef8fb1fcec6fc8add

**Comment by LoveIsGrief** [comment]
The `Mi A1` seems to be on the list already. https://github.com/signalapp/Signal-Android/blob/29d6d3c041d857bfc5f94b4631f2f7587f599c06/app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L306

The problem could lie elsewhere.

**Comment by newuser-web** [comment]
I'm also facing this issue on calls to Mi A1. There is definitely some problem.

**Comment by UserX404** [comment]
I also had issues with calling to Mi A1 hearing my echo in the past. Afterwards I checked the HARDWARE_AEC_BLACKLIST and saw 'Mi A1' was already added but i didn't dig deeper into it.

**Comment by csipu** [comment]
> The `Mi A1` seems to be on the list already.
> 
> https://github.com/signalapp/Signal-Android/blob/29d6d3c041d857bfc5f94b4631f2f7587f599c06/app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L306
> 
> The problem could lie elsewhere.

Yeah, I can see it in the code, so it is not release dependent, but ignore the HW AEC totally for Mi A1. Unfortunately it does not work. Any other idea to check it further why we have the echo?

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
