### ISSUE TITLE
Messages take too long to send/arrive

### ISSUE THREAD

**Issue by Luancs50** [signalapp/Signal-Android#10760]
Messages take 1 to 3 minutes to send. Which makes having a live, ongoing chat very difficult and annoying. 

The issue doesn't seem to be an Internet one as this happens no matter what network both users are. 

Been using Signal as a main chat app for the past year, and was hoping this issue would get fixed but it still hasnt.

I am have a Samaung A70 running Android 10 (OneUI 2.5)

**Comment by Nisc3d** [comment]
This is Duplicate of #9930.
Could you post this comment and a debug log in the above mentioned issue and close this issue?

**Comment by Luancs50** [comment]
Will post on the duplicate. I'm sorry i didnt see it.
