### ISSUE TITLE
Minor mistake in the Spanish translation

### ISSUE THREAD

**Issue by DColadas** [signalapp/Signal-Android#10765]
https://github.com/signalapp/Signal-Android/blob/a3176bbb67c2214eca705b114b4b7927f547f35e/app/src/main/res/values-es/strings.xml#L2047

`Avanzar` should read `Reenviar` instead.

I've tried to fix this through Transifex, but it won't let me contribute to the Spanish translation for some reason.

**Comment by Mr-Mime** [comment]
Thanks for reporting this.

A better place to post a translation related feedback is on the [community forums category.](https://community.signalusers.org/c/translation-feedback/27) (you can use your GitHub account to login there)

I am not familiar with Transifex, but I think you were not able to contribute, as you have to be approved first. (see [this](https://community.signalusers.org/t/unable-to-join-transifex-team/20526/5) comment on the community forum).

**Comment by DColadas** [comment]
Thanks for the help! I've created a [new topic](https://community.signalusers.org/t/minor-mistake-in-the-spanish-translation/25206) in the community forum.
