### ISSUE TITLE
App Crashes when delete multible chats in group 

### ISSUE THREAD

**Issue by TwinsCodeInc** [signalapp/Signal-Android#10769]
The app crashes and reload when delete long list of group conversation , this issue happened in Android Huawei P10

1- Create group for 3 persons
2- make a long conversation
3- Select on of conversations log tap
4- choose multiple select button from the action bar 
5- select over than 30 line of conversation between members and observe the issue the app reloaded and crash

**Comment by rboyer** [comment]
This may be the same as my bug. On a very long (10,000+ messages) conversation with one contact if I scroll back 20-50 messages and start deleting batches of more than 8 it'll eventually crash and reload the app.
