### ISSUE TITLE
Voice Message does not stop when leaving the app

### ISSUE THREAD

**Issue by MksHmr** [signalapp/Signal-Android#10763]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When playing back a voice message the playback does not stop when going back to your message overview and will not stop when leaving the app as well.

### Steps to reproduce
- select a chat
- playback a voice message
- return to your message overview 

**Actual result:** Voice message still plays even when you left the app. You have to go back to the app, to the specific chat and pause the voice message. 
**Expected result:** Voice message should immediately stop when leaving the chat. Voice message should immediately stop when leaving the app.

### Device info

**Device:** Google Pixel 4a 5G
**Android version:** 11
**Signal version:** 5.2.3

**Comment by haffenloher** [comment]
This is not a bug, it's by design. You should also be able to stop playback from the notification area.

**Comment by rgherta** [comment]
I can confirm this playback is starting a foreground service and this service has a lifecycle independent of the chat activity of the app itself. If it is a long running voice message, you can always stop it from the foreground service notification by clicking the stop button.

**Comment by MksHmr** [comment]
Oh wow! I did not see the service notification.
I'm missing an icon on the status bar that this is running. If that would have shown up it would be more clear. How else would you know?
