### ISSUE TITLE
Minor UI Bug - Signal and WhatsApp's "Mark as read" action show up in different order in the Android Notification bar

### ISSUE THREAD

**Issue by ashishb** [signalapp/Signal-Android#10762]
### Bug description

Signal and WhatsApp's "Mark as read" action show up in different order in the Android Notification bar

### Steps to reproduce

- Receive a message on WhatsApp, leave it unread, and don't dismiss the notification
- Recieve a message on Signal, leave it unread, and don't dismiss the notification

**Actual result:** "Mark as read" for WhatsApp is the second action. "Mark as read" for Singal is the first action
**Expected result:** Given the popularity of WhatsApp, consider making "Mark as read" the second action in Signal for consistency. I mistakenly dismiss Signal notification even though my goal is to do a quick reply

### Screenshots

![WhatApp vs Signal](https://user-images.githubusercontent.com/389236/105462961-4203aa00-5c44-11eb-8dc1-68a9c338b2cc.png)

### Device info

**Device:** Google Pixel 3a
**Android version:** SDK version 30 
**Signal version:** 5.2.3

### Link to debug log
Not applicable

**Comment by ninjan3rd** [comment]
Wondering how it becomes a bug..Signal is not following WhatsApp methods or design paradigm !

**Comment by ashishb** [comment]
I'm willing to call it a feature request if that helps. My phone stands, Signal should try to resolve such minor discrepancies as many new users are coming from WhatsApp.

**Comment by ashishkhatri** [comment]
The Android standard is what Signal has implemented, look at most other popular apps.  The affirmative action should be on the right.  Whatsapp is the black sheep.

**Comment by rafialikhan** [comment]
I agree with @ashishb ; users need to migrate seamlessly. Signal is a messaging app, so the black sheep is unfortunately the right way to follow, not random majority of notifications. WA may have messed up privacy policy, but they got their user interaction right. 

This notification feature is in android that allows for reply from the notification window, just need to implement it. Lets not reject the user interaction that makes sense.

**Comment by mueller-ma** [comment]
> I'm willing to call it a feature request if that helps. 

This issue tracker is for bugs only: "This isn't a feature request or a discussion topic" (from https://github.com/signalapp/Signal-Android/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
