### ISSUE TITLE
Toggle between FCM and Websocket

### ISSUE THREAD

**Issue by gthbusrr** [signalapp/Signal-Android#10766]
I used a VPN to block all outgoing traffic by Google Play Service. It would be great if Signal could add a toggle to disable FCM and enable Websocket for notification.

**Comment by Genis-Sage** [comment]
Hey @gthbusrr
As stated in the contributing.md, Signal devs reserved Github issue tracker for bugs

You should go to community.signalusers.org and open a feature request there

Thank you

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
