### ISSUE TITLE
[UI Bug][Beta 5.3.1] Wallpaper malaligned in Chatbubble mode

### ISSUE THREAD

**Issue by mad-de** [signalapp/Signal-Android#10778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When the Chat is in bubble mode the chosen wallpaper is misaligned and doesn't fit the chat width in landscape and horizontal mode.

### Steps to reproduce
- choose wallpaper for chat
- Enter Bubble mode

### Screenshots
![signal-2021-01-23-161850](https://user-images.githubusercontent.com/7095883/105606072-79cf3680-5d97-11eb-99af-86d29e9d6ad7.jpg)
![signal-2021-01-23-162828](https://user-images.githubusercontent.com/7095883/105606190-2c06fe00-5d98-11eb-8605-ec4cc06eab80.jpg)

### Device info

**Device:** Xiaomi mi 9T
**Android version:** Android 11 - PixysOS-v4.0.2-GAPPS-OFFICIAL-20201213-080536
**Signal version:** 5.3.1

**Comment by tanujkucp** [comment]
I observed the same issue myself.

**Comment by greyson-signal** [comment]
Should be fixed in 5.3.3, thanks!
