### ISSUE TITLE
Back button and home button dark in dark theme

### ISSUE THREAD

**Issue by Arnab771** [signalapp/Signal-Android#10772]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Back button and home button become black when I open a chat. It is hard to notice them in dark mode. I have marked the buttons with green in the screenshot.

### Steps to reproduce
- Open the Signal app and turn on dark theme in settings.
- Open any chat

**Actual result:** Home button and back button become dark as well making it harder to see.
**Expected result:** The color of back button and home button should be white.

### Screenshots
![img](https://i.postimg.cc/wvjdwJYJ/Screenshot-20210123-083921-4.png)

### Device info

**Device:** Asus Zenfone Max Pro M1
**Android version:** 9
**Signal version:** 5.3.1

### Link to debug log
https://debuglogs.org/533ff52214920e0c874f04bccd814d5eeb36ecf3eec3dba9a7670f18c1fc69c0

**Comment by Queuecumber** [comment]
I have a similar issue, not sure if it's the same problem, this is with a galaxy note 10, Android 10, signal 5.3.1

![Screenshot_20210123-133556_Signal](https://user-images.githubusercontent.com/5865387/105610926-564cc180-5d80-11eb-8cdc-174a8b897c88.jpg)

On the chat select screen it looks fine

![Screenshot_20210123-133601_Signal~2](https://user-images.githubusercontent.com/5865387/105610930-6369b080-5d80-11eb-99b4-b4bdc9df5d75.jpg)

Selecting a chat I get some graphical glitch on the navigation bar.

@Arnab771 you might want to block out the phone number in your screenshot.

**Comment by Arnab771** [comment]
@Queuecumber Thanks. I guess I uploaded the wrong image.

Seems to be the same.
