### ISSUE TITLE
App forgets conversations allowed to bubble

### ISSUE THREAD

**Issue by gadgetfan10** [signalapp/Signal-Android#10779]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal forgets which conversations are allowed to bubble in Android 11 notification/conversation settings.

### Steps to reproduce
- Go to Android settings, app settings, open Signal settings
- open Notification settings
- In Conversations, Change Bubbles to "Selected conversations can bubble"
- After receiving an incoming message, use the notification to create a bubble.
- Check: In the Notification settings above, tapping "Selected conversations can bubble" should show the conversation that is now in a bubble.
- Swipe the bubble away to the bottom of the screen to make it disappear

**Actual result:** At some point Signal forgets that the conversation is allowed to bubble. Have not been able to determine a time or condition that causes it. But a message in the same conversation received later in the day will not bubble. Check: Go back into the Notification settings, tap "Selected conversations can bubble" and find that the conversation is no longer listed as allowed to bubble. Possibly related to receiving a message in another Signal conversation, but can't definitively confirm.

**Expected result:** Once a conversation has been allowed to bubble, new message(s) in the same conversation should open a bubble if one is not already open. You should be able to check which conversations are allowed to bubble at any time.

Other apps (Google Messages, Facebook Messenger) remember which conversations have been allowed to bubble and messages received days/weeks later will open a bubble.

### Device info
**Device:** Google Pixel 5
**Android version:** 11
**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/1098d21038178df57d69a784ec5de56af6ae6dc3c9ac160b9361b0167bce1f00

**Comment by JaxonWright** [comment]
I can confirm that this also happens for me on my OnePlus 8 Pro running Android 11.

**Comment by AeroEchelon** [comment]
I believe this may be related to this issue
https://github.com/signalapp/Signal-Android/issues/10937#issue-803770504

I've noticed that when you check Signals App Info Settings the conversation channels are not there which could explain why conversations no longer bubble.

An interesting side effect, if you long press the notification that you had previously set to Bubble, it will bubble after the long press interaction.

**Comment by cody-signal** [comment]
Could you try with the latest 5.14 beta and see if the problem is resolved.

**Comment by gadgetfan10** [comment]
Thanks @cody-signal. Haven't received too many Signal messages since I saw your comment, but so far so good. Will follow up in the next day or two with more feedback.

**Comment by gadgetfan10** [comment]
@cody-signal This seems to be working as I'd expect as of 5.14. Thanks!
