### ISSUE TITLE
One Fix for Signal SMS messages not being received on Android 10 phone. 

### ISSUE THREAD

**Issue by braveheart777** [signalapp/Signal-Android#10780]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS recipients are not receiving SMS messages from Signal. 

### Steps to reproduce
- Make Signal the default SMS app in Android
- Send an SMS from the Signal app on an Android phone to another Android user
- Android user(recipient) is not using Signal. Instead, using Google Messages. :(
- Message is never received
- Signal does not show any error that message was not delivered
- Recipient phone does not receive SMS regardless of being on LTE or WiFi

### Device info

**Device:** Lenovo Moto G7 Power
**Android version:** 10 Build QPOS30.85-21-5
**Signal version:** 5.2.3

### Solution
- After trouble shooting this for hours, I found the cause to be on the recipient phone running Android 10 and Google Messages (Signal was not installed). 
- On the recipient phone, open Google Messages app, go to Settings, click on Chat features, DISABLE Chat features. SMS now works both ways.

**Comment by Caerbannog** [comment]
Thank you for contributing!

There have been other reports of this solution: https://github.com/signalapp/Signal-Android/issues/10498#issuecomment-758739975
