### ISSUE TITLE
 Weird text in copied message

### ISSUE THREAD

**Issue by arps18** [signalapp/Signal-Android#10784]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I copy a message, I can copy it the same (Function works properly). But after some time, whenever I paste the same message, its shows some kind of ciphertext!

### Steps to reproduce
- Select a message and choose a copy to the clipboard
- After some time, paste it a couple of time or so
- It doesn't copy the same message 

**Actual result:** A weird Ciphertext/encryption text can be found
**Expected result:** The actual message

### Device info

**Device:** Xiaomi Mi A3
**Android version:** 11.0.0
**Signal version:** 5.2.3

**Comment by Masqueey** [comment]
In order for the developers to fix this you will need to provide either actual example messages/screenshots and/or provide the log of the moment this issue occurs.

Furthermore, I think this is a problem caused by your keyboard or phone, not by the Signal app.

**Comment by arps18** [comment]
Seems like that's the case! 
Apologies for the trouble! 
I'll close the issue, thanks for the assist!
