### ISSUE TITLE
URLs that contain underscore are not converted into a hyperlink correctly

### ISSUE THREAD

**Issue by Arpanio** [signalapp/Signal-Android#10796]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
URLs that contain underscore are not converted into a hyperlink correctly. The underlying hyperlink-generating logic ignores all characters in the URL from underscore onwards.

For example: Signal will ignore everything from the underscore onwards in this URL: "https://en.wikipedia.org/wiki/Trade_(nightclub)"

Thus, the hyperlink will actually point to the Wikipedia article on [trade](https://en.wikipedia.org/wiki/Trade) and not to the Wikipedia article on the [Trade nightclub](https://en.wikipedia.org/wiki/Trade_(nightclub)). 

### Steps to reproduce
- Open Signal
- Open any chat/group chat
- Paste a URL that includes underscore (https://en.wikipedia.org/wiki/Trade_(nightclub))
- Send
- Click on the URL that you just sent to verify if the hyperlink points to the same URL

**Actual result:** The URL takes me to the Wikipedia article on Trade.
**Expected result:** The URL should instead take me to the Wikipedia article on the Trade nightclub

### Device info

**Device:** Realme one
**Android version:** 9
**Signal version:** 5.2.3

### Link to debug log

https://debuglogs.org/98e49b47fb8aa29c22cebdce30b725bf073f3502a714ea395037b23bedd65d09

**Comment by Caerbannog** [comment]
I can't reproduce this exactly.

Device: Xiaomi Mi A2
Android version: Android 10
Signal version: 5.3.4

Here are three cases. The 2 messages without text after the URL detected the URL correctly, and showed a link preview. The last one didn't because it had text after the URL. But the last one failed only to include the last parenthesis ")". It included the underscore allright everytime.

<img src="https://user-images.githubusercontent.com/242172/105644436-dca6f780-5e95-11eb-9bd3-b9c9c78dfe2d.png" width="289" height="443" />

Could you confirm that you only sent the URL, no other text? And try the variants? Maybe send a screenshot?

Note: Signal sometimes uses this code to detect and create links, without custom regular expression.
https://developer.android.com/reference/android/text/util/Linkify#addLinks(android.text.Spannable,%20int)

**Comment by vcwild** [comment]
Got similar results with bugs.

#### Setup
Device: Xiaomi Mi Max 3
Android version: Android 10 QKQ1.190910.002 - MIUI 12.0.1.0
Signal version: 5.2.3

#### Reproduced by following the steps

- Installed the app
- Registered a new account
- Created an empty group named 'test'

#### The results as follows:
**[hyperlink with underscores]**
- URL detected correctly.

**[text] (empty space) [hyperlink with underscores]**
- URL detected correctly.

**[hyperlink with underscores] (empty space) [text]**
- Failed to concatenate, got  'https://en.wikipedia.org/wiki/Trade_(nightclub', expected 'https://en.wikipedia.org/wiki/Trade_(nightclub)'

**[text] (empty space) [hyperlink with underscores] (empty space) [text]**
- Failed to concatenate, got  'https://en.wikipedia.org/wiki/Trade_(nightclub', expected 'https://en.wikipedia.org/wiki/Trade_(nightclub)'

#### Screenshots

<img src="https://user-images.githubusercontent.com/49621396/105715841-d8fa8b80-5efc-11eb-8729-00a4144051d3.jpg" width="250">
<img src="https://user-images.githubusercontent.com/49621396/105715843-d9932200-5efc-11eb-9234-f6e176531965.jpg" width="250">

**Comment by Arpanio** [comment]
**[hyperlink with underscores] (copy-pasted)**

Bug reproduced on my device. Steps:

1. Open the link to the Wikipedia Trade Nightclub article on Chrome mobile browser
2. Copy URL
3. Open Signal and go to a Signal group
4. Paste URL
5. Signal fetches thumbnail image from the parsed URL. The image seen there is from the Trade wikipedia article (and not the Trade nightclub article)
6. Send message
7. Check sent message. The URL takes me to the Trade wikipedia article instead of the Trade nightclub article

Screenshots:
![GitHub_Signal_Bug_10796_Step_5](https://user-images.githubusercontent.com/7851954/105725614-1113c580-5f21-11eb-8493-0d51a07a15ac.jpg)

![GitHub_Signal_Bug_10796_Step_7](https://user-images.githubusercontent.com/7851954/105727575-27228580-5f23-11eb-94db-103dfac0018d.jpg)

**[hyperlink with underscores] (manually typed)**

Bug reproduced. Steps:
1. Open Signal and go to a Signal group
2. Type URL (start from https and type till the last character)
3. Signal fetches thumbnail image from the parsed URL, while typing.
    1. First, the Wikipedia homepage thumbnail is fetched (when "https://en.m.wikipedia.org/" is fully typed out)
    2. Next, the Trade article is fetched (when "https://en.m.wikipedia.org/wiki/Trade" is fully typed out)
    3. Finally, writing the rest of the URL characters `_(nightclub)` does not change the hyperlink at all. The final hyperlink (and fetched thumbnail image stays at the Trade URL)
4. Send message
5. Check sent message. The URL takes me to the Trade wikipedia article instead of the Trade nightclub article

**[text] (empty space) [hyperlink with underscores]**

The text has no impact. Bug persists as reported.

**[hyperlink with underscores] (empty space) [text]**

The text has no impact. Bug persists as reported.

**[text] (empty space) [hyperlink with underscores] (empty space) [text]**

The text has no impact. Bug persists as reported.

**Comment by call-me-matt** [comment]
I noticed something very similar, might be related:

**sending a wikipedia link with brackets**
*https://en.wikipedia.org/wiki/Trade_(nightclub)* - works fine

**sending a link in brackets**
*(https://signal.org)* - works

BUT

**sending a wikipedia link in brackets**
*(https://de.wikipedia.org/wiki/Signal)* - does not work, as it does not strip the brackets correctly

All links are stripped correctly with the desktop client, by the way.

**Comment by Arpanio** [comment]
I tried the testcases @call-me-matt and did not face the same bugs on my device (Realme one, Android version 9, Signal version upgraded to 5.3.7).

**Comment by call-me-matt** [comment]
> I tried the testcases by @call-me-matt and did not face the same bugs on my device

OK, well. Same version here (on a pixel 4a), but I'll open a separate issue then.

**Comment by Arpanio** [comment]
Sorry, not saying your issue isn't correct @call-me-matt 😄 Just creating a record here, so developers know which phones have what kind of issues.

**Comment by NikkiDelRosso** [comment]
There seems to be a similar issue with square brackets, which are used in URL parameters. Technically this is against the URL specification, but it is not uncommon in use (thanks, PHP). 

Example (dummy) URL: http://www.example.com/foo.php?bar[]=1&bar[]=2&bar[]=3 

(Real world use: I ran into this while sending a Bugsnag link)

I can confirm that it links correctly on the desktop version of signal.

**Comment by greyson-signal** [comment]
Hi there, we use the default android linkifier. I don't anticipate writing a custom one anytime soon, apologies.
