### ISSUE TITLE
Signal won't let me register keeping google away

### ISSUE THREAD

**Issue by bugith** [signalapp/Signal-Android#10793]
I read there is a fallback way but it is no available in my phone: I have no google account, all google apps are disabled in my phone but an old Maps version. Only 3 or 4 google services I can't kill as they auto restart.
https://community.signalusers.org/t/initial-registration-without-a-google-account/25486

**Comment by Caerbannog** [comment]
Are you describing the same problem as #10695 or #9376 ?

**Comment by bugith** [comment]
No, it is no the same as #9376 because I couldn't reach this step with official apk picked from website. With the foss version I could successfully deny Signal to become SMS messaging default app... but please keep the feature as I figure allowing it soon.
It is also not the same as #10695 because the message I get is not the exact same. See my linked post above with screeshots.
Great app, thank you.

**Comment by bugith** [comment]
No, it is no the same as #9376 because I couldn't reach this step with official apk picked from website. With the foss version I could successfully deny Signal to become SMS messaging default app... but please keep the feature as I figure allowing it soon.
It is also not the same as #10695 because the message I get is not the exact same. In my phone, play services still run and don't know how to prevent them to restart when I stop them. See my linked post above with screeshots.
Great app, thank you.
