### ISSUE TITLE
High Battery Usage, even if the App is not actively used

### ISSUE THREAD

**Issue by TobaYn3** [signalapp/Signal-Android#10804]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is using A LOT of battery, even if it has not been opened at all. It is (by far) the topmost process of the battery usage list. Since I've installed Signal, I can not even use my phone for one day without recharging it sometime in the afternoon. I tried switching battery optimization off, didn't help. Turned it back on again. Background activity is enabled, because otherwise I don't get any push messages.

### Steps to reproduce
Install Signal

### Screenshots
![Screenshot_20210125-081341_Device care](https://user-images.githubusercontent.com/72782362/105673250-156ebd00-5ee6-11eb-8eaf-4ca6b34c13dc.jpg)

### Device info
**Device:** Samsung Galaxy S8
**Android version:** 9 (G950FXXSBDTJ1, PPR1.180610.011.G950FXXSBDTJ1)
**Signal version:** 5.3.4

### Link to debug log
https://debuglogs.org/4ff20fb2acb215500cfec3dea946f2a6ac3312bab933d207bc4efae75d5668ba

**Comment by TobaYn3** [comment]
**Additional info:** From time to time, about once a day, Android notifies me, that Signal has to be stopped, because it causes too high CPU activity.

**Comment by Caerbannog** [comment]
Did you configure something special on this phone for Google Play Service? For instance, did you disable it in any way? Because Google Play Services handles push messages (FCM).

It will be useful to have a debuglog right after one of this times when Signal has to be stopped.

**Comment by TobaYn3** [comment]
No, Google Play Services are enabled. All I did was to disable some notifications from Google Play Services, i.e. for App Updates, but the service itself is running.

OK, will start Signal and create a debuglog right after the next time Android wants it to be closed.

**Comment by TobaYn3** [comment]
After I have rebooted the phone, installed the latest Signal beta (5.3.5), uninstalled several unused Apps and freed some more disk space (~95% was used), the problems seem to be gone for the moment.
