### ISSUE TITLE
The server rejected our query: promiseAjax: error response; code: 500

### ISSUE THREAD

**Issue by mlncn** [signalapp/Signal-Android#10803]
For two out of 33 people in a group, after sending a message from Signal Desktop it said "Partially sent, click for details" and then the message:

"The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 500)"

This seems slightly different from https://github.com/signalapp/Signal-Android/issues/10667

(500 error not 503, and the fact that Signal isn't in global meltdown today :joy: )

**Comment by mlncn** [comment]
Sorry realizing i should have opened this in https://github.com/signalapp/Signal-Desktop/issues can someone with more permissions move it/

**Comment by Genis-Sage** [comment]
Hey @mlncn

You can also just create a new issue for desktop, and close it here

**Comment by hex-m** [comment]
There are two issues about Error 500 in the desktop client: https://github.com/signalapp/Signal-Desktop/issues/2569 https://github.com/signalapp/Signal-Desktop/issues/4989
