### ISSUE TITLE
Signal Can Still Send SMS/MMS even if it is not the defualt SMS Client 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10814]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can send SMS/MMS texts with Signal even if it is not the default SMS Client. 

### Steps to reproduce
- Set Signal as the default SMS client
- Open an SMS converstation
- Open another SMS/MMS client and set that other app as the default SMS client 
- Return to that Signal conversation
- You can still compose/text that person so long as the conversation is open. If you exit the conversation  and return to it it will show the normal button at the bottom of the conversation that reads "ENABLE SIGNAL FOR SMS"

**Actual result:** You can still send SMS messages with Signal not set as the default client
**Expected result:** Upon resuming a Signal conversation it should check to see if it is still the default SMS client like it does when you open a conversation from the conversation list fragment, if it isn't the default SMS client anymore the UI should be updated to reflect that with the aforementioned "ENABLE SIGNAL FOR SMS" button 

### Device info

**Signal version:** 5.2.3

**Comment by bitmold** [comment]
Similarly you can send SMS from the "Invite friends" screen:
- have Signal be the default SMS client 
- open the "Invite friends" screen 
- leave Signal, set another app as the default SMS client 
- return to Signal and you can still pick clients to SMS from within the app from the "Invite friends" screen

**Comment by bitmold** [comment]
yes

**Comment by cody-signal** [comment]
Pretty sure any app granted the SMS_SEND permissions can send SMSs. The default behavior is mostly for receiving.
