### ISSUE TITLE
Message Timestamp will be Wrong When Device is Unlocked

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10811]
- [x] I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you have a conversation in Signal and sleep your device, when you open it, the message timestamps do not update. Instead you have to go to the conversation list, and reopen your conversation to get the timestmaps to refresh within your conversation.

### Steps to reproduce
- Open a conversation that has some messages in it.
- Sleep your device with that  conversation still being open
- Unlock your device like ten minutes later

**Actual result:** The timestamps will be the same as they were ten minutes ago. 
**Expected result:** The timestamps should be updated on device resume such that they reflect the amount of time that has passed.

### Device info

**Signal version:** 5.2.3

**Comment by xoloki** [comment]
I've hit this so many times, including just now.  I finally decided to do something about it, and searched before adding a github issue, and found this.

I'm gonna try to fix it and add a PR. I'll update this ticket when the PR is live.

**Comment by hulloanson** [comment]
@xoloki any luck on this?

**Comment by xoloki** [comment]
Sorry @hulloanson haven't had any time to look at this yet.

**Comment by jdepypere** [comment]
This issue has been annoying me for quite some time as well.

Just a small addition - you don't necessarily need to put your device to sleep. Leaving the app in general and going back results in this behavior, regardless of leaving your device inactive or not.

**Comment by bitmold** [comment]
I fixed it by redrawing the timestamps on visible messages when the app resumes (which addresses when you leave/reopen the app or when you sleep/awake, among other scenarios)

**Comment by xoloki** [comment]
> I fixed it by redrawing the timestamps on visible messages when the app resumes (which addresses when you leave/reopen the app or when you sleep/awake, among other scenarios)

Yeah that's exactly what I was going to do, thanks @bitmold .  But that was like the day before I left Mobile Coin so I've been busy...
