### ISSUE TITLE
When Signal Messages Are Unable to Send, SMS/MMS won't send with outstanding unsent Signal messages 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10812]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not entirely sure if this is a bug, but it was a problem that I experienced when Signal was down not too long ago. 

I use Signal as my default SMS/MMS client, and when I couldn't send encrypted messages over Signal I found myself sending some unencrypted ones using my carrier. For people who I was texting that I tried to send Signal messages to and found that those messages didn't deliver, my subsequent SMS/MMS texts to them also would have the circular loading symbol on them as if they were queued up behind the Signal messages that wouldn't send. Whereas with people who I had no outstanding Signal messages I was trying to send, I could continue to use Signal as an SMS/MMS client to reach those people. Ultimately I had to switch away from Signal as my SMS/MMS client to make sure that my messages were actually reaching people.

SMS/MMS sucks in so many ways, but in the event that Signal is ever down again (or presumably the user has no access to a data connection and has outstanding Signal encrypted texts) the SMS/MMS functionality can also be broken which will confuse users. 

Also thanks to everyone who worked to get Signal back online as fast as possible, I feel y'all got a lot of undeserved flack for that <3 

**Actual result:** SMS/MMS texts won't send until all outstanding Signal texts have been sent.
**Expected result:** I don't know, *I at least*, feel like the SMS/MMS should be queued separately or something. At least in the event that Signal is down.

### Device info
**Signal version:** 5.2.3 (I think)

**Comment by Tursko** [comment]
Duplicate of https://github.com/signalapp/Signal-Android/issues/10594

**Comment by bitmold** [comment]
my mistake, closing
