### ISSUE TITLE
Inviting Users to Signal in New Picture UI Flow Can Cause User to Lose Message They were Composing 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10815]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you click the camera floating action button to send an image to 1+ of your Signal contacts, you can lose the image/message you are composing 

### Steps to reproduce
- Click the camera floating action button from the conversations list fragment
- take some pic, click next to get to the "Select Signal recipients" screen
- Scroll to the very bottom of the list, click the "INVITE A CONTACT TO JOIN SIGNAL" link button thingy at the bottom 
- Now you'll be on the "Invite friends" screen, maybe you invite a friend maybe not. But once you are done here if you click the back arrow at the top of the screen (next to "Invite friends") instead of taking you back to the "Select Signal recipients" screen you are taken allllllllllll the way back to the conversations list fragment. Any photo/message you had composed and Signal recipients you were planning to send it to will have been totally lost. Interestingly clicking the regular Android back button takes you back to the previous screen as you would expect. 

**Actual result:** Your message is totally lost alongside all recipients that you had planned to send it to
**Expected result:** You should be taken back to the previous screen (not the one prior to that) with your message and selected recipients sitting there as you've left them 

### Device info
**Signal version:** 5.2.3

**Comment by bitmold** [comment]
Ya

**Comment by cody-signal** [comment]
Hey there, with upcoming work, I don't believe this flow (inviting on the fly) will exist anymore and the camera first flow will only allow you select existing contacts, for better or worse.
