### ISSUE TITLE
Image caption text is unreadable

### ISSUE THREAD

**Issue by vvps** [signalapp/Signal-Android#10828]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When captioning an image with a bright background and text, the text is unreadable due to lack of contrast.

### Steps to reproduce
- Select an image to share with some text
- Start writing a caption

**Actual result:** Caption text is not readable
**Expected result:** Caption text should be readable (by decreasing the transparency of the black background)

### Screenshots
![image_caption_issue](https://user-images.githubusercontent.com/2164106/105898030-413e8f80-6019-11eb-86ed-573a0ff50f1e.jpg)

### Device info

**Device:** One Plus 7T
**Android version:** 10
**Signal version:** 5.3.5

**Comment by vvps** [comment]
![image caption unreadable](https://user-images.githubusercontent.com/2164106/105903354-1146ba80-6020-11eb-8065-432aba7aaa31.jpg)

Another screenshot showing the problem.

**Comment by militaryCoder** [comment]
I think caption background should be blackened even a little more.
