### ISSUE TITLE
Signal chats can be read by other applications on Android

### ISSUE THREAD

**Issue by RoStCode** [signalapp/Signal-Android#10821]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android parental control program [Kroha](https://play.google.com/store/apps/details?id=ua.com.tim_berners.parental_control) (and probably other applications as well) can read all Signal chats on child's phone and transfer them to parents phone.

### Steps to reproduce
- Install parental control program [Kroha](https://play.google.com/store/apps/details?id=ua.com.tim_berners.parental_control) on child and parent phones according to instructions.
- Install Signal on child's phone according to instructions.
- Start a Signal chat from the child's phone and send a chat message to a contact.

**Actual result:** The child's Signal chat can be read on parent phone.
**Expected result:** The child's Signal messages are truly private and can not be read by other applications.

Note that the parental control program [Kroha](https://play.google.com/store/apps/details?id=ua.com.tim_berners.parental_control) on the child's phone is a "device admin app".

### Device info

**Child Device:** Sony Xperia X Compact
**Child Android version:** 8.0.0
**Child Signal version:** 5.2.3
**Parent Device:** Google Pixel 3a
**Parent Android version:** 11
**Parent Signal version:** 5.2.3

**Comment by tanujkucp** [comment]
I also think that even admin apps should not be able to access any data from inside signal app.

**Comment by Genis-Sage** [comment]
Hey @RoStCode
can you be more precise, what you can read? 
all messages, outgoing and ingoing? 

Also, is this still possible, after disabling accessibility services?

**Comment by greyson-signal** [comment]
Apps like that use a combination of administrator privileges and accessibility services. Accessibility services are the same things screen readers use, so they are literally reading the content off the screen. If there is content on the screen, that app will be able to see it. Nothing we can do about it.

**Comment by RoStCode** [comment]
My observation is that the phone can sleep with Signal inactive with nothing on screen. Kroha still capture all messages in realtime.
