### ISSUE TITLE
Verify safety number button gets cut out 

### ISSUE THREAD

**Issue by Xrasure** [signalapp/Signal-Android#10820]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The button to check someone's safety number is cut out a bit in landscape mode

### Steps to reproduce
- open signal
- turn phone to landscape mode
- click on a contact's profile picture 

**Actual result:** verify safety number button gets cut out 

**Expected result:** you should see the whole button or at least be able to scroll up, which you can't

### Screenshots

![Screenshot_20210125-190706__01.jpg](https://user-images.githubusercontent.com/60069045/105747155-b68a6180-5f40-11eb-9c57-4d3c8856697e.jpg)

### Device info

**Device:** OnePlus 6t McLaren edition
**Android version:** 10.3.7
**Signal version:** 5.3.5

### Link to debug log (not sure if it helps)

https://debuglogs.org/b47fc1b480bc38c6154bfdfa4ccff871b1fc2407000689a7d92e1e5d7ef0f157

**Comment by bitmold** [comment]
This same UI control gets cut out all across the app. I've reported it in two places at #10818 and #10103

**Comment by bitmold** [comment]
Another instance of this UI control getting cut out is when you click on someone's avatar on the main conversation list screen: 
![blur](https://user-images.githubusercontent.com/22125581/105783213-f0a93280-5f43-11eb-87fc-5e86b36c4fd6.jpeg)

**Comment by bitmold** [comment]
Ya
