### ISSUE TITLE
Exporting Plaintext SMS "Error, unable to write to storage."

### ISSUE THREAD

**Issue by xNyxNox** [signalapp/Signal-Android#10830]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When click the "Export plaintext backup" button, an error message appears saying "Error, unable to write to storage."  I believe that this is due to the app only requesting media access in Android 11 instead of access to all storage.

Edit: after asking for help on reddit, someone offered their advice on how this could be handled and asked me to include his comments in this request.  I'm editing this to include them.  [Here is the link](https://www.reddit.com/r/AndroidQuestions/comments/l5psr3/how_to_manually_add_permissions_in_android_11/gkw4fzt?utm_source=share&utm_medium=web2x&context=3)
### Steps to reproduce
- Tap 3 dots in top right
- Tap "Import / export"
- Tap "Export plaintext backup"

**Actual result:** "Error, unable to write to storage." appears on the bottom of the screen.
**Expected result:** A backup should begin to be created.

### Screenshots

https://imgur.com/a/xis6qPV 
https://imgur.com/a/0tVo8oF 

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 11
**Signal version:** 5.3.6.0-JW

### Link to debug log

https://debuglogs.org/1e03c87453b7fd4a6f68bb5cf518e1150c8162d59c034cec706a96f41dd9d585

**Comment by greyson-signal** [comment]
Where did you install Signal from? This is not an official version, and we do not have this feature.

**Comment by Genis-Sage** [comment]
Hey @xNyxNox
Assuming from the "-jw" in your version, you use this fork
https://github.com/johanw666/Signal-Android/issues

So you should post your ssue there

**Comment by xNyxNox** [comment]
> Hey @xNyxNox
> Assuming from the "-jw" in your version, you use this fork
> https://github.com/johanw666/Signal-Android/issues
> 
> So you should post your ssue there

Yes thank you, as you can see from my account I'm new to GitHub.  On that page I clicked the bugs button but I see now that somehow I ended up here.  Thanks, this is definitely the wrong place.
