### ISSUE TITLE
No video/voice call notification (Security Exception)

### ISSUE THREAD

**Issue by bluumb** [signalapp/Signal-Android#10838]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive a voice or video call, I don't get a notification. For group video calls, however, the notification works.
If I have Signal Desktop open at the same time, I get a notification there, but not on the phone. Notifications for calls are enabled in the settings. As a note, I do not use GApps or MicroG. All other text message notifications work as well.

### Steps to reproduce
- Turn on call notifications
- Receive a 1:1 voice/video call

**Actual result:** Don't get a notification. As soon as the calls terminated, I get a notification that I missed a call
**Expected result:** Get a notification that I get called

### Device info
**Device:** Samsung Galaxy S7 (without GApps)
**Android version:** 10
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/de4e5ca1ae494cae35e031e72729c2963f94e5607157bf02884a1b44f9863318
(Calls appear around 23:04:32 and 23:42:55)

**Comment by tdawg-shipit** [comment]
Maybe update to the latest version and see if you can reproduce? Your installed version is several versions behind the current.

**Comment by bluumb** [comment]
I use the website build from [Signal Website](https://signal.org/android/apk/) and there is the latest version 5.1.9. I don't know why the app has not been updated there already. But of course, I will try to reproduce it again as soon as the latest version is available.

**Comment by tdawg-shipit** [comment]
You can build it using https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources and download the latest release from https://github.com/signalapp/Signal-Android/releases .

I'm not sure why that apk build is out of date but...

**Comment by BytesOfBinary** [comment]
Duplicate of #7733.

**Comment by bluumb** [comment]
Now that the website build has reached version 5.3.7, I tested it again, but nothing changed. I got a message that Signal get closed repeatedly. 
Here is a new debuglog from Version 5.3.7:
https://del.dog/zunyfuppep
https://debuglogs.org/0a577d9325c6ec71119b046e039951d634078719c9bd3c357923649517e46597

**Comment by AdrianLxM** [comment]
Same behaviour on a Nokia 7.2.

The call sometimes is signaled to the OS - if I listen to podcasts, they will stop as expected with an incoming call.

**Comment by MenachemICTBIT** [comment]
I have this same issue on my OnePlus 7, with the Beta version of Signal (also had the same issue with stable). High priority!!

**Comment by cody-signal** [comment]
This should be fixed in the latest 5.6 beta, please try it and let me know otherwise so I can keep digging.

**Comment by bluumb** [comment]
I tested it again with version 5.6.4, unfortunately I didn't get a notification for either a video or voice call. However, the security exception is no longer visible in the log either, so that doesn't seem to be the problem anymore. Maybe you can find another cause of the error in the log.

Voice/Video calls appear at:
- 2021-04-09 10:27
- 2021-04-09 10:31

https://debuglogs.org/e77500f3b3e5d11194acbb624ac7d19631864e1f6c00c2654826e78b06f2f172

**Comment by csavard-sudo** [comment]
Okay... But the latest version is 5.7.2 . You should upgrade to that and see if you can reproduce the issue. No use reporting a bug on an obsolete version .

**Comment by cody-signal** [comment]
> Maybe you can find another cause of the error in the log.

Thanks for the updated logs. Here's what happened:

First call: App started to setup a call, but a second after being told there is a call coming we received a hangup message and terminated the call.

Second call: When trying to send information to the caller to establish the call the network request failed.

For the first instance, if would be helpful to have the caller's log so we can correlate timestamps and see where the delay was. For the second, we can look at adding better retry logic and investigate our messaging pipe.

**Comment by bluumb** [comment]
Thank you for the further investigation! I have just tested again:
Voice call at 15:28
Video call at 15:30
I let it ring for about 15 seconds both times.

Debug logs from caller: https://debuglogs.org/e76967c60be9ddb70d9245fd65d6928f15c55b5d2be12b9480c0ab901f6ff72f
Debug logs from receiver: https://debuglogs.org/1cc15d48f3e6f9263698a0a99fe020a8c76c679ed7dd60981bdc808be17e4bae

**Comment by cody-signal** [comment]
@bluumb do you have any other issues with sending messages? Both logs indicate that neither device can communicate over the pipe to send the call setup information to each other. Is there any unique about your network setup or internet provider that would causing this? I'm assuming both devices are on the same network.

**Comment by bluumb** [comment]
> Is there anything unique about your network setup
That was a good hint. Both devices are on the same wifi and I have configured a custom DNS server. I have now selected the default DNS server and now the notifications work :)

So I guess I have to look for a new DNS server.

**Comment by cody-signal** [comment]
Would you mind sharing which DNS service you were using if you're comfortable doing so, or was it a custom job?

**Comment by bluumb** [comment]
I used the DNS service from [dismail.de](https://dismail.de/info.html#dns) (fdns1). It uses some filterlists for ad- or trackingblocking, maybe that caused the issue.

**Comment by cody-signal** [comment]
Awesome, thanks. I'll see if we can get it remedied, but at least you have a work around for now. Thanks for being responsive.
