### ISSUE TITLE
Typing indicator counted as unread message + a wallpaper issue

### ISSUE THREAD

**Issue by tanujkucp** [signalapp/Signal-Android#10833]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The typing indicator is counted as an unread mesage. The message is not even received still but its showed in the unread count. See picture.

Also look at the black line above unread messages label. Its an issue with custo wallpaper.

### Steps to reproduce
- let someone message you
- open their chat
- when they start typing something , you can see that the unread counter shows an extra unread message counting the typing indicator

**Actual result:** 1. Typing indicator counted as unread message.
2.  Black line above unread messages label
**Expected result:** 1. Typing indicator should not be counted in unread messages
2. There should be no black line above unread messages label

### Screenshots
![Screenshot_20210127-200131_Signal~2](https://user-images.githubusercontent.com/32611332/106008530-6694d180-60dd-11eb-9294-24505e6f2033.png)

### Device info

**Device:** Redmi Note 5 Derpfest Custom ROM
**Android version:** 11
**Signal version:** 5.3.5

### Link to debug log
Not needed

**Comment by ShivanshGoel221B** [comment]
> * [x]  I have searched open and closed issues for duplicates
> * [x]  I am submitting a bug report for existing functionality that does not work as intended
> * [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
> * [x]  This isn't a feature request or a discussion topic
> 
> ### Bug description
> The typing indicator is counted as an unread mesage. The message is not even received still but its showed in the unread count. See picture.
> 
> Also look at the black line above unread messages label. Its an issue with custo wallpaper.
> 
> ### Steps to reproduce
> * let someone message you
> * open their chat
> * when they start typing something , you can see that the unread counter shows an extra unread message counting the typing indicator
> 
> **Actual result:** 1. Typing indicator counted as unread message.
> 2. Black line above unread messages label
> **Expected result:** 1. Typing indicator should not be counted in unread messages
> 2. There should be no black line above unread messages label
> 
> ### Screenshots
> ![Screenshot_20210127-200131_Signal~2](https://user-images.githubusercontent.com/32611332/106008530-6694d180-60dd-11eb-9294-24505e6f2033.png)
> 
> ### Device info
> **Device:** Redmi Note 5 Derpfest Custom ROM
> **Android version:** 11
> **Signal version:** 5.3.5
> 
> ### Link to debug log
> Not needed

That line on the wallpaper is not an issue, that separating line is indeed intentional. However, I have linked a pull request that I hope will solve the other issue i.e., the unread message counter.
