### ISSUE TITLE
When archiving a group and a new message is sent in the group, the group gets unarchived.

### ISSUE THREAD

**Issue by jacoby149** [signalapp/Signal-Android#10834]
When archiving a group, and a new message is sent in the group, the group gets unarchived. The archive function should keep the group archived even when a new message is sent by someone in the group.

**Comment by rubo77** [comment]
thats not the point of an archive. An archive should contain something in a certain state, that is not changed any more.

What you want is either

1. close that group and archive it
2. leave the group but keep the messages up to now archived

**Comment by jacoby149** [comment]
I see, I should probably suggest a feature to filter/hide chats, so that if
you still want to be in the group but you dont want it to show up on the
screen, you can do that.

**Comment by rubo77** [comment]
Why not just mute the Notifications for that group? This works for me

**Comment by Fmstrat** [comment]
From a true privacy perspective, if we take into account over-shoulder watching, keeping things in an archive or hidden folder is a highly valuable feature.

**Comment by greyson-signal** [comment]
To address the original bug report, this is actually working as intended. The archive feature is supposed to be an "inbox zero" thing, where you archive chats after you read them, but they'll come back when there's new messages to read. For further discussion of new possible features, please check out [the forum](https://community.signalusers.org/). Thanks!
