### ISSUE TITLE
Reply with sticker for a particular message

### ISSUE THREAD

**Issue by suganth215** [signalapp/Signal-Android#10832]
As of now, there is no option to reply to a specific message with stickers. When we swipe a message and select a sticker, it just gets sent without mentioning the message which we supposed to reply. Kindly add this feature, because it will be super helpful for a lot of users for me who uses stickers a lot.

**Comment by Genis-Sage** [comment]
Hey @suganth215
as stated in the issue template and in the contributing guide, signal devs reserved Github for issues

For feature request, please visit community.signalusers.org
