### ISSUE TITLE
Android app crashes immediately after opening, every time!

### ISSUE THREAD

**Issue by lachlansleight** [signalapp/Signal-Android#10840]
This is actually a duplicate of #10726, however I think the title of that issue doesn't properly communicate its severity, and it's already long been buried.

As I mention in my comment on that issue, once signal finishes loading all the new messages that have come in since it was last open, it immediately crashes with the following adb output. Rebooting device doesn't help. Issue began around 18 hours ago.

```
01-27 22:32:05.617 17817 17888 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
01-27 22:32:05.617 17817 17888 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 17817
01-27 22:32:05.617 17817 17888 E AndroidRuntime: java.lang.AssertionError: Had an update, but it didn't match any rows!
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.database.RecipientDatabase.applyStorageSyncUpdates(RecipientDatabase.java:873)
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:203)
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:110)
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
01-27 22:32:05.617 17817 17888 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
01-27 22:32:05.613 17817 17888 I chatty  : uid=10228(org.thoughtcrime.securesms) signal-JobRunne identical 3 lines
01-27 22:32:05.614 17817 17888 V Cursor  : Filling cursor window with start position:0 required position:0
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler: java.lang.AssertionError: Had an update, but it didn't match any rows!
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.database.RecipientDatabase.applyStorageSyncUpdates(RecipientDatabase.java:873)
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:203)
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:110)
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
01-27 22:32:05.618 17817 17888 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

Device: Xiaomi 9T Pro
Signal Version: 5.3.6
Android Version: 10 QKQ1.190825.002
UI Version: MIUI Global 12.0.3 (QFKMIXM)
Android Security Patch Level: 2020-10-01

**Comment by francwalter** [comment]
I think I have the same issue. 
When I open Signal the first time (so I guess it is not still in memory) it crashes every time. After this crash then I can open and use Signal normally. 

This crashing is a bit annoying, because any notification of a new signal message will also mostly result in first crashing signal and the message (in that notification) is not opened, I have to reopen manually.

I am quite sure that it would be "fixed" if I would reinstall Signal (or wipe data). But then I loose all my chats' histories. 

By search here in the issues with "crash" as search term and checking the answers, I can see that the support cue of these issues is miles long and it makes me not much hope that my issue will be fixed soon.
Seems to me that the massive hype of Signal (when WhatsApp changed its rules) did that, which is clear.

On Xiaomi Mi A1 with Android 9.0 (rooted).
frank

**Comment by breversa** [comment]
@francwalter Have you tried creating a backup of your conversations (in Signal settings), uninstalling/reinstalling the app then restoring your backup?

**Comment by francwalter** [comment]
Does a backup restores pictures etc. too?

**Comment by breversa** [comment]
Yup.

**Comment by francwalter** [comment]
OK, did it. Was easy 😄 

Backup was some 200 MB! I think maybe I should change my way to deal with Signal chat and stop to keep all this chat.

On first try, Signal doesnt crash anymore the first time opening, will see...

@breversa  Thank you!
frank

**Comment by breversa** [comment]
200 MiB ? These are rookie numbers ! My backups rank up to about 3.5 GiB currently. ;)

Boasting aside, there are options to keep the last x messages, and/or in the y days/weeks/months, and automatically clean the rest.

**Comment by francwalter** [comment]
Thank you againly, that hint with syncthing too, I didnt know it! Very interesting!!!

**Comment by francwalter** [comment]
It happened again unfortunately.
And furthermore: I had to change the phone, the old one wont boot anymore, so happily i had that backup for the new phone, and Signal crashes again on the new phone. So it is surely related to some of the chat contents in this backup.
Could start new anyway now...

**Comment by cody-signal** [comment]
@francwalter which version of Signal are you using? Could you try grabbing the latest beta if you aren't running it already?

https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta

**Comment by francwalter** [comment]
5.12.2 now, just did the update from 5.12.1, was already beta channel.

The first impression is that the crash has gone, but I was wrong about that already once before ;)

Will test more and post it then here.

The crash reason was in my backup as I noticed already, so I thought of deleting all history and start new to solve it.
But is there a way to backup single chat histories? 
Export the text of the history at least?
Or to make the complete backup searchable?

**Comment by francwalter** [comment]
No, sorry, doesn't change it.
Still crashes initially.

**Comment by francwalter** [comment]
As I didnt want to live with this notorious crashes on Signal App start, I made a backup and flushed all my chats.
I decrypted the Backup with [signal-back](https://github.com/xeals/signal-back), and now I have all my chats in an sql file (output: raw) and all media in a big folder.
Not very user friendly though, no direct way to see, which message is from who, see [my comment in issue 70](https://github.com/xeals/signal-back/issues/70) 
This repo is unfortunately not anymore under development 😢
