### ISSUE TITLE
When I Will Scroll Down, Name Will Go To Profile Photo 

### ISSUE THREAD

**Issue by ArmTimDev** [signalapp/Signal-Android#10844]
### Bug, Visual

When I Will Scroll Down, Name Will Go To The Profile Photo !

#### Screenshots

![PicsArt_01-28-10 13 00](https://user-images.githubusercontent.com/76068426/106184073-51d83c80-61b6-11eb-8afb-307c59f29472.jpg)

![PicsArt_01-28-10 17 47](https://user-images.githubusercontent.com/76068426/106184375-b3001000-61b6-11eb-8d11-bfa420083965.jpg)

**Device : Samsung Galaxy S10e**

**Comment by SunnyXD233** [comment]
When scrolling down, name may overlap the avatar.

**Comment by ArmTimDev** [comment]
Yes
