### ISSUE TITLE
Reaction picker + message spotlight misaligned when conversation is bubbled

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#10843]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The reaction picker is misaligned when conversations are bubbled.

### Steps to reproduce
1. Open conversation in a bubble
2. Long press a message to open the reaction picker

**Actual result:** See screenshot

**Expected result:** Hopefully you know what this should look like 😜

### Screenshots
![Screenshot_20210128-121706](https://user-images.githubusercontent.com/10427164/106182538-976c1980-6164-11eb-9cd8-a20540422b8d.png)

### Device info

**Device:** Pixel 5
**Android version:** 11
**Signal version:** 5.3.7 

### Link to debug log
https://debuglogs.org/d8bec2268d82ad4fea36163ac1e32b83430e599df5848e2af6a4cd3a68847be9

**Comment by u32i64** [comment]
Can confirm this on:

**Device:** Pixel 3 XL
**Android version:** 11
**Signal version:** 5.3.7

Additionally, same thing occurs when using Signal in split screen mode, which I think was reported somewhere... but I can't quite find it. I only found [this post of mine](https://community.signalusers.org/t/buttons-dont-work-in-split-screen-with-signal-as-the-2nd-app/16403/2) that suggests that this wasn't an issue as of Signal 4.69.6.

https://debuglogs.org/b7c0c9a39920805cc0a639bd079069a18dd426ac01155c4f8db3d0370564facf

<details><summary>Screenshots of the issue in split screen mode</summary>

Signal on top | Signal on bottom
---|---
![](https://user-images.githubusercontent.com/19972511/106184506-ae395d00-61b2-11eb-9f6e-0acb0b796eba.png) | ![](https://user-images.githubusercontent.com/19972511/106184533-b5f90180-61b2-11eb-954b-c1e4ac30eee8.png)

</details>
