### ISSUE TITLE
Signal not available on Google Play Store for Tablets

### ISSUE THREAD

**Issue by offero** [signalapp/Signal-Android#10855]
I tried to install Signal on a Samsung Galaxy S7+ and it was not available in the Google Play store. I presume there is not an android tablet build? I use it well on my iPad and I was trying to install it on a friend’s device but it was not available.

**Comment by MagicFab** [comment]
For now if you install the APL directly it will work:
https://signal.org/android/apk/

**Comment by J-Sorenson** [comment]
To be clear, do you intend to use your tablet as a primary device (using a dumb-phone number), or as a "linked device" that channels messages through your phone? I really want to be able to use my Android Tablet (M4) as a linked device, but that's only available on iPad tablets. No Android and (even worse) no ChromeOS support: https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices

**Comment by offero** [comment]
I want to use it as a linked device. It’s already installed on the phone.

**Comment by Rhahkeem** [comment]
This may be a better discussion for the [Forum](https://community.signalusers.org/) rather than an issue

**Comment by fourofspades** [comment]
Also having this problem. I want to move from WhatsApp, but this is a blocking issue for me.   It's seems crazy I can't have this on multiple devices, a primary and as many linked devices as I wish.

What are Android tablet owners being treated as second class citizens?  It's clearly possible, as it's available on iPad.

**Comment by fourofspades** [comment]
Any forks that provide this?

**Comment by granthgh** [comment]
I also want to be able to link my Android tablet.

**Comment by greyson-signal** [comment]
Hi there, please discuss feature requests on [the forum](https://community.signalusers.org/). Thanks!

**Comment by fourofspades** [comment]
Does that mean no further action?  That's really poor.

I would suggest people just use Telegram. it works correctly across all platforms, it doesn't team some users like second class citizens..

Also, the APK sideload suggestion doesn't work, this is not a solution, or even a workaround.

**Comment by greyson-signal** [comment]
It is no trivial matter to support larger screen sizes and also add support for Android being a linked device. It's a massive project. We want to do it as some point, but as with all things, we have a small team and lots of things we want to do, so prioritization has to happen.

**Comment by MagicFab** [comment]
Relevant forum link :

https://community.signalusers.org/t/android-tablet-support/5590/128

**Comment by fourofspades** [comment]
Pretty sure nobody really cares about layout support (i.e. difference screen sizes), Android takes care of that mostly, the real issue here is linked device support.   Signal only working on 1 of my 4 devices that I use, that's absolutely no use to me whatsoever.   No other secure messaging platform has this limitation.

**Comment by granthgh** [comment]
Seems to me that iPhone/iPad getting priority over Android as this feature request and issue has been around for a number of years. 

Format for large screen seems to be OK if you sideload the app, but no linking is a real pain.

**Comment by greyson-signal** [comment]
Sorry, didn't mean to give the impression that I was opening up discussion here. As noted, we use the forum for that. Was just trying to respond to say "this is harder than you think, we want to do it eventually".
