### ISSUE TITLE
Read Receipt not working properly.

### ISSUE THREAD

**Issue by nikhilbadyal** [signalapp/Signal-Android#10858]
- [✓ ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ✓] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ✓! This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages which was seen with Read receipt off. Remain with single tick always. Even if we turn read receipt on. 

In the image 1 and 2 message were sent when I(receiver) turned off read receipt. So it's Ok. That sender can't see dark double tick. After that I(receiver) turned on Read receipt and received 3rd message. That message is also Ok at sender end with dark double tick. But the 1 and 2 remains same like they are still unseen.

### Steps to reproduce
- Ask someone to send you a message
- Turn off Read Receipt from settings.
- Read the message. 
-Turn on read receipt back.
-Now any future message will work as intended and the other person will see double tick. 
-The message in the first line will still be a single tick message.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

From sender end. 

![signal-2021-01-30-094324~01.jpg](https://user-images.githubusercontent.com/59223300/106347365-e42a2e80-62e3-11eb-9ce0-1c54ab266234.jpg)

### Device info

**Device:** Redmi Note 7 pro
**Android version:** 10
**Signal version:** 5.3.8

**Comment by teynav** [comment]
This is working as it was intended to work. Turning on Read receipt won't change what happened before it was turned on because before that the chat session didn't share read receipt.
