### ISSUE TITLE
Typing "_" (U+005F LOW LINE) suggests all stickers

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#10852]
Typing `_` (`U+005F LOW LINE`, aka the normal "underscore" character) suggests all installed stickers. When adding another `_`, most of the suggestions are removed, but some still remain.

### Steps to reproduce
- Go into a conversation and type `_`.

**Actual result:** (Looks like) all installed stickers are suggested.
**Expected result:** No stickers should be suggested.

### Screenshots

In this example, only the blessed [Bandit the Cat](https://signal.art/addstickers/#pack_id=9acc9e8aba563d26a4994e69263e3b25&pack_key=5a6dff3948c28efb9b7aaf93ecc375c69fc316e78077ed26867a14d10a0f6a12) and [Zozo the French Bulldog](https://signal.art/addstickers/#pack_id=fb535407d2f6497ec074df8b9c51dd1d&pack_key=17e971c134035622781d2ee249e6473b774583750b68c11bb82b7509c68b6dfd) sticker packs are installed.

`_` | `__`
---|---
![](https://user-images.githubusercontent.com/19972511/106272002-64e41e80-6241-11eb-807d-5d5c6c280232.png) | ![](https://user-images.githubusercontent.com/19972511/106272018-6b729600-6241-11eb-942a-4bde0588faa7.png)

### Device info

**Device:** Pixel 3 XL
**Android version:** 11
**Signal version:** 5.3.8

### Link to debug log
https://debuglogs.org/8fb18c7e322a3d4e8bd93ee19671b4219bc51b17aa0e8e3d251fc701f040c96a

**Comment by Xrasure** [comment]
I could reproduce this on the newest signal beta, but I'm not sure if that's a bug
