### ISSUE TITLE
Can not be accessed in the Play Store with Android 10 device. Why? no apk available for manual installation?

### ISSUE THREAD

**Issue by pgmr2** [signalapp/Signal-Android#10867]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by thgoebel** [comment]
This is a place for bug reports related to the app, not problems with the app distribution. Please use the [forum](https://community.signalusers.org/c/support/9) next time.

Most likely, Signal is not available on Google Play in your region. You can get the apk from https://signal.org/android/apk/ though it's not recommended and you should try to use Google Play whenever possible.

**Comment by pgmr2** [comment]
Thank you

Am 31. Januar 2021 12:10:19 MEZ schrieb Thore Goebel <notifications@github.com>:
>This is a place for bug reports related to the app, not problems with
>the app distribution. Please use the
>[forum](https://community.signalusers.org/c/support/9) next time.
>
>Most likely, Signal is not available on Google Play in your region. You
>can get the apk from https://signal.org/android/apk/ though it's not
>recommended and you should try to use Google Play whenever possible.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/Signal-Android/issues/10867#issuecomment-770364872

Gruß
Reinhard Fiebelkorn
