### ISSUE TITLE
.apk files cannot be sent from PC 

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#10863]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.  
You cannot send apk files on Windows PC.

### Steps to reproduce
- Drag and drop / Select an apk file to share from pc.
- Hit enter to send.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)  
You'll be notified with "Selected file cannot be sent due to security reasons". And .apk(android apps) caanot be shared with others until you change the extension.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)  
It should user to send any file.

**Comment by Masqueey** [comment]
I think this is intended behaviour (especially since they give you a security warning). The warning is totally fair, because for all Signal knows, you're trying to send someone a virus that would run on their phone once they tap it. This is probably why .exe files are also not allowed to be sent.

**Comment by pixincreate** [comment]
Sorry, I've to disagree with this. You can send the same thing from mobile but not from pc. If you change the extension of the file , then you can easily send it from pc. No security can save anyone, if you're allowed to send the file with changed extension and ask the receiver to change it.
Hope you got my point. 
There's no sense in stopping users from sending apk files on pc.

**Comment by AbandonedCart** [comment]
@pixincreate Until more recently, blocking APK files was typical functionality for messaging apps. The reason changing the extension works is that the most common verification is mimetype. 
Most people still install an antivirus even if it isn't going to eliminate all risk, but it is reduced. It's the same logic.

**Comment by greyson-signal** [comment]
Hi there, this is the android repository. If you'd like to bring up an issue with desktop, they're over here: https://github.com/signalapp/Signal-Desktop :slightly_smiling_face:
