### ISSUE TITLE
Link preview fetches low-resolution icon when high-resolution one is available

### ISSUE THREAD

**Issue by GitMatze** [signalapp/Signal-Android#10878]
### Bug description
In the following, I'm referring to www.zeit.de, a big German news website. As can be seen from the screenshots below, Signal's preview image has quite a poor quality compared to Whatsapp's one. I believe that WhatsApp uses the `apple-touch-icon-precomposed` 114x114px icon while Signal loads the 32x32px `shortcut icon`.
Furthermore, see that the previews posted from Signal Android and Signal Desktop differ. The one from Signal Desktop looks correct. 

On a side note, I'd like to mention two more things: 
1. A 32x32 icon should not be displayed this large. A lot of space taken up by something looking very unpleasant. 
2. The link preview is just WAY TOO BIG. If it is intended to look like this, I think you have to find a way to indicate to the user before sending that this massive thing will appear. Certainly many people will like to avoid this.

### Screenshots

Sent from Signal Android  --- Sent from Signal Desktop  --- WhatsApp
![image](https://user-images.githubusercontent.com/45139485/106400216-68cc9800-641d-11eb-84e9-4364d733c1c7.png)

### Device info

Device: Galaxy S7
Android version: 8.0.0
Android Signal version:** 5.3.10
Desktop Signal Version:1.39.6

**Comment by Caerbannog** [comment]
The http://www.zeit.de/ webpage contains this code:
```html
<link rel="shortcut icon" sizes="16x16 32x32" href="https://www.zeit.de/favicon.ico">
<link rel="apple-touch-icon-precomposed" href="https://img.zeit.de/static/img/ZO-ipad-114x114.png">
```

It seems that Signal Android uses the first picture with a dark background (the .ico is mostly transparent), that's what causes the mostly dark preview.
It seems that Signal Desktop uses the first picture with a white background. The second picture would be bigger and better, and that's what WhatApp uses.
