### ISSUE TITLE
Allow admin to mute people

### ISSUE THREAD

**Issue by zaz** [signalapp/Signal-Android#10876]
Allow the creation of groups where only certain people can talk.

This allows organizations to create broadcast groups to send information to employees, without allowing it to be buried by chatter.

Many organizations already follow the pattern of having one group which is just for leadership to send important information, and another for general discussion. Unfortunately, employees often accidentally post in the leadership chat.

**Comment by Genis-Sage** [comment]
Hey @zaz

Signal devs reserved Github for bug reports

For feature requests, please visit community.signalusers.org
