### ISSUE TITLE
location isn't been invoked when internet!&

### ISSUE THREAD

**Issue by alexbodn** [signalapp/Signal-Android#10879]
-----------------------

### Bug description
if i attach the location when not connected to the internet (but may send by sms), the gps is not invoked, and i get the last location it has been invoked before.

### Steps to reproduce
- disconnect wifi and mobile data.
- enter a conversation.
- press + to attach the location.
- you will see a blank google map, with the red pin in the center. this is normal, since there's no internet to retrieve the map through.
- send the message.
- 
**Actual result:** 
the receiver will get the location of the previous gps fix, not the one at the place of the location invokation.

**Expected result:** 
i would expect the gps / other location service to be invoked when i choosed to add the location to the message.

### Device info
**Device:** Kyocera duraforce pro.
**Android version:** 6.0.1
**Signal version:** 5.3.7.1

thank you in advance,
alex``

**Comment by Caerbannog** [comment]
Hi @alexbodn,
Can other applications access a good location in the same scenario?
For instance, try to disconnect wifi and mobile data, then open Google Maps (with data already downloaded) or another map app that works offline.

**Comment by alexbodn** [comment]
i've tested it again.
of course i set the internet off.
i can send a textual sms to another sms client.
regarding a location message sending blocks for some time on the sender
but shows nothing at the receiver at all.

**Comment by alexbodn** [comment]
> Hi @alexbodn, Can other applications access a good location in the same scenario? For instance, try to disconnect wifi and mobile data, then open Google Maps (with data already downloaded) or another map app that works offline.

hello @Caerbannog , 
please see my detailed test [here](https://github.com/signalapp/Signal-Android/issues/10879#issuecomment-1026300572)
