### ISSUE TITLE
Exif Date of Saved Photos is wrong

### ISSUE THREAD

**Issue by Demian98** [signalapp/Signal-Android#10872]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Photos are saved to the Galerie the Exif Date of the File is completely wrong.

### Steps to reproduce
- Save a Photo from any Chat to the Galarie

### Screenshots

![20210131_142811](https://user-images.githubusercontent.com/77210091/106385761-334e8d00-63d2-11eb-875f-d20cf0017c95.jpg)
![20210131_142823](https://user-images.githubusercontent.com/77210091/106385773-3a759b00-63d2-11eb-8e66-6033c449c1a1.jpg)

### Device info

**Device:** Samsung Galaxy Note 10+
**Android version:** 10
**Signal version:** 5.3.7

### Link to debug log

https://debuglogs.org/87fd2094c6bc5b6233fc55fad38a3ce92201f5651fa23d5f1c589bec132e857d

**Comment by Genis-Sage** [comment]
Hey @Demian98
This is a duplicate of  #10142

**Comment by Demian98** [comment]
Hey @Genis-Sage
I think it is not a Duplicate of #10142. There the problem is the File Name of the saved Photo.

I have a Problem with the Exif Date of the Photo. The Datetime when the Images was taken from the Metadaten of the File. It is thousands of Years in the future, then they always appear at the top in the gallery which is very annoying.

**Comment by Genis-Sage** [comment]
@Demian98
if you look at the other issue to the comment around one month ago, you will exactly find the behaviour you describe

**Comment by Demian98** [comment]
You are right, many thanks😊 Ich will close the issue.
