### ISSUE TITLE
Sending unsaved screenshot from Signal on Android shows up as WAI file on iOS Signal

### ISSUE THREAD

**Issue by dotnetdesigners** [signalapp/Signal-Android#10871]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

If I take a screenshot on my Android device and share it with Signal (without saving them image first) and send it to a Signal user on iOS, they see a WAI file, and not the image. This might be similar to or related to issue #9404

### Steps to reproduce
- Press volume down and power to capture a screenshot.
- Click on the screenshot
- without saving, click on the share icon
- select Signal
- click on a contact that is an iOS user

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The iOS user gets a WAI file

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

They should see the image of the screenshot that I sent

### Device info

**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 5.3.10

**Comment by dotnetdesigners** [comment]
Here is a screenshot from the perspective of the iOS user:
![Point Blur_Jan312021_122110](https://user-images.githubusercontent.com/61983266/106384122-73594400-63c1-11eb-8249-8c89ebc48c00.jpg)

**Comment by Caerbannog** [comment]
Could you post a debug log? Just to check that there was no error logged.
Also, could you attach the WAI file here or post it somewhere? Alternatively, try renaming it to "abc.jpg" to check that its content is an image.

Note to other developpers: issue #9404 was probably fixed by commit 0a883dc.

**Comment by dotnetdesigners** [comment]
The WAI file

Attached is the WAI file. It is indeed the image that is sent.

**Comment by dotnetdesigners** [comment]
After some experimentation, I have realised that I left out an important step in his to reproduce this bug. After taking the screenshot, you need to crop the screenshot image first, and then click the share button, without saving it first. This reproduces the bug every time.

**Comment by rohitbal77** [comment]
Observing the same behavior. It happens only if you crop or edit the image and send it before saving. 
Sending from OnePlus 5, Oxygen OS 10.0.1, Signal 5.3.11. 
Receiving phone: iPhone 7, iOS 14.4, Signal 5.3.2.1

Received image on iPhone
![WhatsApp Image 2021-02-04 at 17 47 12](https://user-images.githubusercontent.com/15013456/106896618-d1ff2480-6717-11eb-8666-4af19c9cc1bd.jpeg)
