### ISSUE TITLE
Cannot Edit Group Name, Remove Member, or Add Member To Group

### ISSUE THREAD

**Issue by volomike** [signalapp/Signal-Android#10886]
Multiple members, who are currently Group Admin in a group, with various Android models and OS versions, who have all updated to the latest Signal Private Messenger, are reporting tonight that they cannot edit the group name, nor remove a member, nor add a member to the group.

We all get the same message: "Failed to update the group".

**Comment by Sgn-32** [comment]
Can a or more debug logs posted?

**Comment by volomike** [comment]
I don't know what the programming team did on the server end, but the bug is now resolved in my test case with a group created in December of 2020 (I think, to the best of my recollection, on that date). Today, on that same group, we were able to add a group member as well as remove another one.

**Comment by volomike** [comment]
Consider merging this with #10851. https://github.com/signalapp/Signal-Android/issues/10851
