### ISSUE TITLE
Typing box overlapping with keyboard. 

### ISSUE THREAD

**Issue by nidri** [signalapp/Signal-Android#10883]
On Android 11 typing box and send button overlapping with keyboard. This behavior was observed when keyboard suggestions are popped on top line.

![Screenshot_20210201-070945~2](https://user-images.githubusercontent.com/8284626/106460124-d817ab80-6460-11eb-85fa-5d1b6c5b7f1c.png)

**Comment by Xrasure** [comment]
Please provide your debug log

**Comment by nidri** [comment]
Link to debug logs.

https://debuglogs.org/5082d1471dad99407db29548a5e83fb3d269d37b8bbb02c9970280a18ca17f4d

**Comment by Tursko** [comment]
Duplicate of https://github.com/signalapp/Signal-Android/issues/10269

**Comment by RJ97GH** [comment]
Same thing for me as well.

**Comment by nidri** [comment]
Issue seems to be fixed now.

**Comment by Tursko** [comment]
Was fixed here 
https://github.com/signalapp/Signal-Android/issues/10269#issuecomment-831264913
