### ISSUE TITLE
One contact endlessly spamming "Chat session refreshed"

### ISSUE THREAD

**Issue by DeadWalkingDeath** [signalapp/Signal-Android#10887]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Today a conversation with one contact started notifying me with "Chat session refreshed" (German: "Unterhaltungssitzung aktualisiert"). This notification is generated repeatetly every few seconds. A few hundred notifications in a few minutes are quite annoying.
I've spoken to the contact and we both hit the "Reset secure session" (German: "Sichere Sitzung zurücksetzen") on our phones. But it didn't help.
He also said another contact had talked to him yesterday about having the same issue.
My contact doesn't seem to have any issue himself. He also is on the same Signal version as me.
It seems to have slowed down to a few notifications a minute now, while writing this bug report.

### Device info

**Device:** Motorola g7 plus
**Android version:** 10
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/614766d55d8fe87997e7255e3e145a77f725ffbd42deba310c6fd5564f204e29

**Comment by Sgn-32** [comment]
This issue was discussed in one of the last beta threads in the community forum.
Is related to linked devices. Maybe send some message to your contact from the linked
device or if possible unlink your device.

**Comment by DeadWalkingDeath** [comment]
I did indeed tried the desktop app a few days ago and therefore linked it.
After thousands of notifications today they stopped at some point.
I unlinked the desktop app anyway and we tried sending messages to each other.
He doesn't receive my messages, but I get his messages.
I'm also not receiving messages he writes in groups, in which we are both part of.

**Comment by Sgn-32** [comment]
Maybe your contact should "reset the secure session" now. This reset should be received by your devices and renew the encryption keys and further values/settings of the conversation.

**Comment by DeadWalkingDeath** [comment]
Sorry, forgot to mention.
After the first failed attempts to send him a message, at first I reset the secure session and then I asked him too.
But it did not change anything.

**Comment by Sgn-32** [comment]
I would now wait a few hours and then test again. If it still doesn't work, a debug log from both sides would be helpful.

**Comment by DeadWalkingDeath** [comment]
The notifications started appearing again this morning. It was shortly after I booted up the PC where the signal desktop app was installed. Although I unlinked it yesterday, it seems to have still worked in the background.
I uninstalled the desktop app and since then no new notifications arrived.
Unfortunately my contact is not as patient as I am. He removed Signal from his phone today. So I guess I can't provide any logs from both sides anymore.

**Comment by m93a** [comment]
Me and my friends are using Signal as the main messaging app and we have a lot of groups there. Every time someone gets a new phone, they start spamming "Chat session refreshed" and "Security number changed" to every single group they're in. It ruins everyone's day, since the person spamming usually doesn't notice it for quite a while. This is terrible, please fix :(

**Comment by bjoernenders** [comment]
I'm having the same issue right now. Are there any fixes for this?

**Comment by m93a** [comment]
@bjoernenders The person spamming “session refreshed” is probably logged in on two different phones. They need to log out on one of them. Apart from this, I don't think there's currently any other walkaround, sadly.

**Comment by bjoernenders** [comment]
@m93a Thanks for the reply. I'll ask my friend to reset/restart/logout in the hope that the problem disappears.

**Comment by wayneworkman** [comment]
I'm having this error too. I don't know how to troubleshoot. The other person has signed out of all other devices. We've reset security. I have no way to troubleshoot.

**Comment by bjoernenders** [comment]
However is spamming the "Chat session refreshed" needs to wipe the app from all the devices and do a reinstall. That helped for us @wayneworkman
