### ISSUE TITLE
Signal Crashes during voice call.

### ISSUE THREAD

**Issue by mage1k99** [signalapp/Signal-Android#10892]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While on Signal voice call, automatically crashes when I switch to a different app or locked my screen.

So to test this I tried to stay in signal app while in call and the app doesn't crash at that time. but when switched to other apps for doing works it crashes after 10 mins.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** 

While on call signal automatically crashes after sometime.

**Expected result:** 
during signal call the application doesn't crash

### Screenshots
N/A

### Device info
**Device:** Redmi K20 Pro
**Android version:** 10.0
**Signal version:**  5.3.10

### Link to debug log

`FATAL EXCEPTION: Thread-4
Process: org.thoughtcrime.securesms, PID: 24764
java.lang.IllegalStateException: Not allowed to start service Intent { act=SEND_HANGUP cmp=org.thoughtcrime.securesms/.service.WebRtcCallService (has extras) }: app is in background uid UidRecord{222dc45 u0a142 SVC  bg:+1m0s119ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
	at android.app.ContextImpl.startService(ContextImpl.java:1571)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at org.thoughtcrime.securesms.service.WebRtcCallService.onSendHangup(WebRtcCallService.java:1018)
	at org.signal.ringrtc.CallManager.onSendHangup(CallManager.java:1049)`

The [Debug logs](https://del.dog/k20prologs.log)

**Comment by cody-signal** [comment]
Can you try the latest beta (5.6.2)? It should have fixes for this type of crash.

**Comment by mage1k99** [comment]
Yes, I'm on the latest beta (5.6.2) the crashes reduced.

The chances of crash is high when I close the PIP (Picture-in-Picture) of the outgoing call.

So I keep the PIP active on the screen to reduce the chances of crashes.

**Comment by cody-signal** [comment]
Can you submit a new debug log after a crash while running 5.6.2?

**Comment by mage1k99** [comment]
ok, I'll try to get debug logs

**Comment by mage1k99** [comment]
closing the issue currently as there are no crashes of now.

**Comment by jthall** [comment]
This bug can be triggered in 6.19.3 if the device does not support picture-in-picture. You can get that to happen by enabling Talkback in accessibility. It will turn off picture-in-picture for you and refuse to allow the mode.

how to reproduce:

- turn on talkback in accessibility -> vision
- make an audio or video call
- app will crash when it expects picture-in-picture mode.

**Comment by nicholas-signal** [comment]
> This bug can be triggered in 6.19.3 if the device does not support picture-in-picture.

Would you mind filing this as a new GitHub issue for easier tracking? Thank you for using Signal!

**Comment by jthall** [comment]
sure.

I was trying to follow the policies that say to search all open and closed issues before opening a new one. I'll open a new one and file appropriately.
