### ISSUE TITLE
Closing Signal doesn't exit the last conversation: Re-opening doesn't always show the conversation list anymore

### ISSUE THREAD

**Issue by l3u** [signalapp/Signal-Android#10899]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Until the recent update(s), Signal's behavior was comparable to e. g. QKSMS and others: If a conversation was open, the app closed it when hitting the "home" button. When re-opening Signal, not the last viewed conversation showed up, but the list of all conversations (including notification counts for each).

Now, the last viewed conversation is still open after closing Signal and re-opening it. Only workaround for now to get the "old" behavior is to hit the "back" button at least once, to go to the conversations list before closing Signal, or even twice: once to close the keyboard and another time to get to the list.

### Steps to reproduce
- Open Signal
- Open a conversation
- Hit the "home" button
- Open Signal again

**Actual result:** The last conversation is shown
**Expected result:** The list of all conversations should be shown, as before

### Device info
**Device:** Nokia 4.2
**Android version:** 10
**Signal version:** 5.3.7.1

**Comment by DonovanDiamond** [comment]
I think this is more of a feature and a bug.

**Comment by l3u** [comment]
Well, the behavior was okay until the recent updates, and now it's not … so it's a bug or at least a regression.

**Comment by Tursko** [comment]
This is intended functionality. They changed this a couple updates ago.

**Comment by greyson-signal** [comment]
Quite the contrary, it was a bug that when you backgrounded the app and tapped the icon, it took you back to the conversation list :) Signal now works like every other app in the world -- regardless of how you resume it, it now brings you back to where you left off.
