### ISSUE TITLE
Messages not disappearing

### ISSUE THREAD

**Issue by bljusruk** [signalapp/Signal-Android#10893]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have set disappearing messages for a chat to 10 seconds. Messages I received after I've set disappearing messages are not disappearing.

### Steps to reproduce
- Set disappearing messages to 10 seconds.
- Receive a message after the setting.
- The message is still there after 10 seconds.

**Actual result:** Received message that came in after setting the parameter does not disappear after the time set in disappear message elapsed.
**Expected result:** Message should disappear.

### Screenshots
![Screenshot_20210203_162254](https://user-images.githubusercontent.com/52827396/106768770-8cb9f480-663c-11eb-8970-27e32d88377a.jpg)

### Device info

**Device:** Huawei P30 Pro

**Android version:** 10.1
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/40d5f632193ae838bd0364a227c222aed77af9540587446741298a9d9168b403

**Comment by makultar** [comment]
Well I can confirm that this works fine for me. Both regular and note to self, same time interval (10 seconds).

**Comment by makultar** [comment]
Well I can confirm that this works fine for me. Both regular and note to self, same time interval (10 seconds).

**Comment by bljusruk** [comment]
I confirm that disappearing messages works when the message is sent from signal to signal. If sent from non-signal texting application to signal it doesn't work.

Shouldn't it work no matter where the message is sent from?

**Comment by bljusruk** [comment]
No relevant anymore. Closing.
