### ISSUE TITLE
Sometimes received images are invalid

### ISSUE THREAD

**Issue by bermeitinger-b** [signalapp/Signal-Android#10895]
- [x] I have searched open and closed issues for duplicates 
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes, some images that a received (not for the sender) are invalid and shown either fully black or shown invalid. In the screenshot, you can see that the first image is working, the second one not. They are taken with the same phone, the same camera, and individually selected to share inside the Google Photos app.

### Steps to reproduce
- receive image

**Actual result:** Second image is invalid
**Expected result:** Image is shown as the one above

### Screenshots

![signal-2021-02-03-162515](https://user-images.githubusercontent.com/581257/106780331-c93b1f80-663f-11eb-946c-40c00d355ede.png)

### Device info

**Device:** Motorola Moto G Play
**Android version:** 7.1.1
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/f78346450ded0ac0af3d36a1fa4f52e8f8ca26c9e1ec741802a8bee14e3368f5

**Comment by hwinnemoe** [comment]
I have experienced this as well intermittently. In my case, the images still show up correctly after exporting them to my phone, but not inside Signal.
