### ISSUE TITLE
Unable to send messages to a specific contact

### ISSUE THREAD

**Issue by StefanoWoerner** [signalapp/Signal-Android#10905]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to send messages to one of my contacts from the android app, the messages get stuck on the spinning circle. Receiving messages works as intended. Sending messages to that same contact through desktop works as intended. Sending messages to all other contacts/groups through desktop or app works as intended. Resetting the session did not help.

### Steps to reproduce
I don't know how to exactly reproduce the bug, here is how I think it happened:
- While signal was down a few weeks ago, I tried to send a message which did not go through
- I deleted the message (for all) before it was sent
- I then deleted the message (for me) to remove it from my history
- All subsequent messages since then are stuck on the spinning circle (sending)

**Actual result:** Message is stuck on sending
**Expected result:** Message is sent

### Screenshots
![sendbug](https://user-images.githubusercontent.com/6840165/106931780-3bcafe80-6717-11eb-9102-63496c9c2aeb.png)

### Device info

**Device:** Moto G5
**Android version:** 8.1.0
**Signal version:** 5.3.7.1

### Link to debug log
https://debuglogs.org/5a8873b3d82d886a92da2d59c48d08819e160bd253cff17d2102b9d693ecaca7

**Comment by AsamK** [comment]
You seem to have many jobs in the queue for RecipientId::162. It's a FIFO queue and the first sms send job seems to be stuck because the `CellServiceConstraint` is not fullfilled.
```
id: JOB::504b024d-5a7e-4052-aa14-a068e4333d5e | factoryKey: SmsSendJob | queueKey: RecipientId::162 | createTime: 1610729189324 | nextRunAttemptTime: 0 | runAttempt: 0 | maxAttempts: 15 | maxBackoff: 30000 | lifespan: -1 | isRunning: false | memoryOnly: false
```
`CellServiceConstraint         : false`

Are you maybe in flight mode or have SIM disabled?

**Comment by StefanoWoerner** [comment]
Yes this could be the reason. I am currently abroad and have no cell service on one of my two SIM cards. I am not in flight mode, there is no service for that card. During the time Signal was down, I mistakenly tried sending an SMS to my contact through that card.
Is this working as designed? If this means that sending SMS also blocks subsequent push messages, this seems like undesired behaviour. It may be better if sending just fails when there is no service instead of waiting indefinitely.
