### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by niloygazi4** [signalapp/Signal-Android#10902]
![Screenshot (10)](https://user-images.githubusercontent.com/65735895/106847568-5c746380-66d9-11eb-8901-8546d24c4bb7.png)
![Screenshot (12)](https://user-images.githubusercontent.com/65735895/106847571-5e3e2700-66d9-11eb-8eb5-182602819caa.png)

**Comment by greyson-signal** [comment]
Hi there, for development assistance, please use [the forum](https://community.signalusers.org/). We know builds are working because of our [reproducible build guide](https://github.com/signalapp/Signal-Android/tree/master/reproducible-builds). Thanks!

**Comment by niloygazi4** [comment]
can you guys give the final code of 2021
