### ISSUE TITLE
TranscodingException results in message being sent with text content but without video

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#10912]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to share a video, and added some text to the same message. The transcoding apparently crashed (low-spec phone), but the message was sent anyway, with the text content but without the video. Since the text usually relates to the video in this kind of case, the message should not be sent at all if the transcoding fails.

### Steps to reproduce
- Share a video through Signal
- Add a text message to the sharing message
- Make the transcoding job crash

**Actual result:** Message is sent with the text content but without the video
**Expected result:** The message is either not sent at all or sent completely

### Device info
**Device:** LG G2
**Android version:** 10
**Signal version:** 5.3.7.1

### Link to debug log
https://debuglogs.org/ba1ab3d3336fa05b8312034bfe0a74f12bf9de61d2e0877b405ae0a87846b227

**Comment by richardddd98** [comment]
I think I have this issue too. In my case if I keep the caption empty, then:
1) I see the video is sent
2) The other party does not receive anything at all. If I quote that message, the other party receives a message with the quote saying that the original message couldn't be found

Could you, @hiqua, please tell me if you encounter the same behavior I described if you keep the caption empty?

**Comment by hiqua** [comment]
@richardddd98 can you attach a debug log?

If you see the video it might not be the same bug, although it could be related (no check that the message is full before sending it).
