### ISSUE TITLE
You Cant Search the Conversation of a Blocked User

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10911]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can't search a conversation you have with a blocked user. since this functionality has nothing to do with sending/receiving messages I'd expect the search option to be in the context menu like it is with unblocked users.

### Steps to reproduce
- block someone
- open your convo with them

**Actual result:** you can't search
**Expected result:** you should be able to

### Device info

**Signal version:** 5.3.7.1

**Comment by bitmold** [comment]
for lengthy convos spanning lots of time this can be really unfortunate as the user either has to scroll a lot or go through the process of unblocking -> searching -> blocking which is pretty unideal

**Comment by bitmold** [comment]
Similarly, the *Mute notifications* menu item shouldn't be there since you can't ever receive any notifications from a blocked user.

Was poking in ConversationActivity and it seems like there's a line to remove this menu item on blocked users but it doesn't seem to do anything 
```java
   if (recipient != null && recipient.get().isBlocked()) {
      if (isSecureText) {
        hideMenuItem(menu, R.id.menu_view_media);
        hideMenuItem(menu, R.id.menu_call_secure);
        hideMenuItem(menu, R.id.menu_video_secure);
        hideMenuItem(menu, R.id.menu_expiring_messages);
        hideMenuItem(menu, R.id.menu_expiring_messages_off);
      } else {
        hideMenuItem(menu, R.id.menu_call_insecure);
      }

      hideMenuItem(menu, R.id.menu_mute_notifications);
    }
```

**Comment by bitmold** [comment]
Ya

**Comment by bitmold** [comment]
Oui

**Comment by greyson-signal** [comment]
The search item is present in the context menu for blocked users. Can't reproduce.
