### ISSUE TITLE
Message Preview Widget for Home Screen

### ISSUE THREAD

**Issue by ModnarUser** [signalapp/Signal-Android#10925]
A _received messages preview window_ for the home screen similar to some email-clients or other messenger apps would be a nice to have feature.
[feature]

**Comment by Genis-Sage** [comment]
hey @ModnarUser 
Signal devs reserved github for bugs in existing functionality
For feature request, the [community forum](https://community.signalusers.org/c/feature-requests/17) is the right address

there is already a request for it:
[Android Widget Similar to Messenger?](https://community.signalusers.org/t/android-widget-similar-to-messenger/727)

**Comment by ModnarUser** [comment]
Perfect, thanks for clarifying :)
