### ISSUE TITLE
Cannot forward SMS to non-signal contact

### ISSUE THREAD

**Issue by sorenmogensen** [signalapp/Signal-Android#10929]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have received a (spam) SMS message and want to forward to 7726 (generic number for reporting spam in UK). Have done several times in the past with signal, but with current version (5.3.7.1) I only see signal contacts when attempting to forward.

### Steps to reproduce
- Open a plain text SMS discussion / thread
- Press and hold a message
- Click the forward/share button

**Actual result:** You cannot forward to non-Signal contacts or non-contact numbers
**Expected result:** Should be able to forward to any contact or even non-contact numbers

### Device info
**Device:** moto g(8) plus
**Android version:** 10
**Signal version:** 5.3.12

### Link to debug log
https://debuglogs.org/2a82dca995e7c17afb22760a7a07bf8aea8eba4bdf75a4b68cbdcdf18f180d55

**Comment by Robt456** [comment]
I'm having the same problem, but with Signal 5.3.12

**Comment by UserX404** [comment]
@sorenmogensen 
When opening a new issue please don't delete the issue template and append a debug log.

Forwarding sms got (temporary) disabled by [this](https://github.com/signalapp/Signal-Android/commit/b49e4004ab3d121089989f9eb13bdcb63a7373a3) commit.
No clue if it's intended or by mistake.

**Comment by caitsith01** [comment]
It must be a mistake, otherwise Signal is offering itself as an SMS app but failing to provide basic SMS functionality. This seems to be the same problem as the sudden inability to share media to non Signal contacts. Both are borderline app-breaking problems for many common use cases.

**Comment by sorenmogensen** [comment]
@UserX404
I definitely did not intend to delete any template - I did go through password reset as part of opening the issue, maybe that somehow caused the new issue to not have the template. Anyway, have updated ticket with template.

**Comment by UserX404** [comment]
Maybe it's a mistake due to the introduction of multi-forward where non-Signal contacts gets filtered to reduce complexity and shipping out this feature fast.
BUT at the moment there is no dev response to this issue.

Offtopic:
Combined with the [import issue](https://github.com/signalapp/Signal-Android/issues/10618) there is some inconvenience for SMS usage atm. But for that there is some response that it has to be rewritten.

**Comment by liar666** [comment]
+1

**Comment by OsBlaineOra** [comment]
I have had the same issue ever since the multi-forward feature* was added.

Current Signal - 5.3.12
Android - 11

*More of a hindrance than a feature.  Almost all of my contacts are non-signal users and the "feature" only works with signal users.  This causes an extra step, for example, when I'm trying to send an image from a web page.

**Comment by OsBlaineOra** [comment]
I've found a workaround.

1. I attempt to share an MMS message.
2. I am only shown contacts who are on Signal and group texts.
3. Select any contact on the list.
4. De-select the contact.
5. Wait a couple of seconds.
6. The proper full list of contacts is displayed and I can share with anyone.

**Comment by jmbhill** [comment]
I'm still having this problem with Signal 5.4.11 on Android 11. Can't forward to non-signal contacts.

**Comment by j-dexx** [comment]
Also having this issue

**Comment by olimju** [comment]
Same issue, with workaround I've confirmed works:
[https://github.com/signalapp/Signal-Android/issues/10929#issuecomment-783719234](url)

**Comment by fanf** [comment]
I have a different instance of that bug: if I try to share an image with signal from the gallery, only the signal contacts and groups are shown. But from signal, I have the full list of contacts, including non signal ones.
Some things that let me think it's the same problem:

- I discovered the same (horrible) workaround as explained by @ OsBlaineOra
- it used to work and broke with groups / multi-sending.

Funny (sort of) thing: when I click on "share with > signal", I clearly see at first the list of recent conversations with all contacts, then there's a refresh which filter out non-signal contacts and add groups.

**Comment by liar666** [comment]
> I've found a workaround.
> 
>     1. I attempt to share an MMS message.
> 
>     2. I am only shown contacts who are on Signal and group texts.
> 
>     3. Select any contact on the list.
> 
>     4. De-select the contact.
> 
>     5. Wait a couple of seconds.
> 
>     6. The proper full list of contacts is displayed and I can share with anyone.

Hi, Thanks for sharing the wark around... I can confirm it's working for me too.

I don't know how many times I've written this in Signal's GitHub issues, but it would be great that tests (at least for the core functionalities) would be introduced in the codebase or that TDD would be put in practice. Every new version of Signal that has come out since at least 2 years has come with several dysfunctions to core functionalities. This is very annoying, even to proponents of FLOSS like me, that are able to trade a few dysfunctions for more freedom.
@dev please stop adding new "eye candy" functionnalities and start fixing the base of the code ! If the "security" functions of Signal are as badly developped as the GUI and the new releases, this is very scary....
People are fleeing Telegram,etc because of the EULAs, this is THE opportunity for Signal to gain "Market" shares... But if it continues to be as dyfunctional and insert new regressions, nobody will trust the app anymore and EVERYBODY will go away....

**Comment by clampak** [comment]
I have this issue as well, and the workaround @OsBlaineOra gave works for me.

**Comment by ikanakova** [comment]
I have this issue as well and it is very annoying and I agree with @liar666  and @clampak! I downloaded Signal because Signal is offering itself as an SMS app and almost all my contacts are non-signal users.

**Comment by ednl** [comment]
Same problem. I need to forward a message to a phishing reporting number via normal SMS but it doesn't work because non-Signal contacts are not shown. Unfortunately the workaround doesn't seem to work for me (Android 9, Signal 5.5.5).

**Comment by caitsith01** [comment]
This is still a problem.  It should be trivial to fix.  The workaround demonstrates that there is a bug in the way contacts are first displayed.

**Comment by ikanakova** [comment]
@caitsith01 It seems it isn't trivial to fix because now I have a 5.7.5 version and I have still this issue.

**Comment by TheLastGimbus** [comment]
@ikanakova not that it isn't trivial, they are just busy with their shitcoin :sparkling_heart: :tada:

**Comment by benzvan** [comment]
Thanks for the workaround but it doesn't work for me.

**Comment by pgnd** [comment]
Attempting to woraround this^ same problem, I've a clean-install of

  **Signal v5.9.0 (Beta)**

, installed from PlayStore,

on new install of a OneUI Android 10.

I've multiple accounts set up on the device.

All contacts in all accounts are seen/usable by other apps (email, messaging, etc) in all cases.

In Signal, creating a NEW message pulls up access to & displays all those contacts (several thousand, atm); the available list can be searched & results added to recipient list.

OTOH, when *forwarding* a received message -- select/highlight message, click forward icon -- only a list of ~ 20 'Recent chats' and ~5 contacts that are "just in Signal" contacts is shown.

Share with / Search on known-contacts returns no results.


Simple refresh via

```
Settings -> Accounts -> Signal -> Remove
open Signal -> click to edit new -> pull down to refresh
```

has no effect. Full contact list missing when Forwarding.



Uninstall/reinstall of Signal also has no effect. Full contact list missing when Forwarding.



Workaround from above,

https://github.com/signalapp/Signal-Android/issues/10929#issuecomment-783719234

```
I attempt to share an MMS message.
I am only shown contacts who are on Signal and group texts.
Select any contact on the list.
De-select the contact.
Wait a couple of seconds.
The proper full list of contacts is displayed and I can share with anyone.
```

also has no effect.


Again, this is ONLY in the Forwarding case. Full contact list missing when Forwarding.

Otherwise fully functional.

**Comment by caitsith01** [comment]
Workaround no longer seems to work for me.  So not only is Signal ignoring this issue, they are actually making it worse!

**Comment by pgnd** [comment]
ping @greyson-signal

I see you've redir'd dupes here; can you provide any comment/insight, or ask for specifics that signal @devs might need to help get this dealt with?

**Comment by caitsith01** [comment]
> 
> 
> ping @greyson-signal
> 
> I see you've redir'd dupes here; can you provide any comment/insight, or ask for specifics that signal @devs might need to help get this dealt with?

Seconded, this is clearly a very minor error somewhere in the code (given the previous workaround) yet no-one seems to be at all interested in addressing it.  It is also a problem in getting less engaged users to try/stick with Signal.  I have had several people I convinced to use Signal complain to me about their inability to forward media and messages to non-Signal contacts.

**Comment by ednl** [comment]
I think everyone should give a 👍 to the first comment, perhaps that would give this a bit a bit more traction.

**Comment by pgnd** [comment]
fyi, installing today's Signal version bump 5.9.0 -> 5.9.1, apart from the addition of 'MobileCoin', I notice in "About this app:"

"Be yourself - You can use your existing phone number and address book to securely communicate with your friends."

Hmmm.

Unfortunately, this^^ current issue continues; no ability to forward to any listing of non-Signal contacts.

**Comment by Tursko** [comment]
> fyi, installing today's Signal version bump 5.9.0 -> 5.9.1, apart from the addition of 'MobileCoin', I notice in "About this app:"
> 
> "Be yourself - You can use your existing phone number and address book to securely communicate with your friends."
> 
> Hmmm.
> 
> Unfortunately, this^^ current issue continues; no ability to forward to any listing of non-Signal contacts.

That's unrelated to SMS integration. You're address book is still used to find other users, that's what they're talking about.

**Comment by pgnd** [comment]
it's just mktg blather anyway.

the take home was -- still in 5.9.1

**Comment by pgnd** [comment]
> Forwarding sms got (temporary) disabled by this commit.

re this commit

https://github.com/signalapp/Signal-Android/commit/b49e4004ab3d121089989f9eb13bdcb63a7373a3

could @alex-signal @greyson-signal respond/comment *here* ?

**Comment by Tursko** [comment]
> > Forwarding sms got (temporary) disabled by this commit.
> 
> re this commit
> 
> [b49e400](https://github.com/signalapp/Signal-Android/commit/b49e4004ab3d121089989f9eb13bdcb63a7373a3)
> 
> could @alex-signal @greyson-signal respond/comment _here_ ?

It was disabled for multi-share because of MMS restrictions. They cannot guarantee that the video you're forwarding to others is small enough to send via MMS (since MMS limits differ per carrier). Funny enough, that commit doesn't prevent you from multi sharing to MMS groups, only single MMS conversations.

**Comment by pgnd** [comment]
> It was disabled for multi-share

so nothing to do with the issue at hand?  specifically, inability to "forward SMS to non-signal contact" , and the lack of contacts listings when forwarding?

**Comment by Tursko** [comment]
> > It was disabled for multi-share
> 
> so nothing to do with the issue at hand?  specifically, inability to "forward SMS to non-signal contact" , and the lack of contacts listings when forwarding?
> 

I believe the bug was introduced in that commit, but there intention was to prevent SMS/MMS during multishare. We gave them this feedback during that beta release.

**Comment by pgnd** [comment]
> We gave them this feedback during that beta release

+1.

so back to the 

"... respond/comment _here_ ?"

**Comment by alex-signal** [comment]
Hi! I'm tracking this internally and will try to get to it over the next week or so.

**Comment by Smith-Zhou-CN** [comment]
I have met the same problem here too (HONOR X10 Max), and I found that when choosing to send a SMS message and the app shows loading, as long as I disconnect the Internet connection, the problem is solved

**Comment by ArchmageArcane** [comment]
Finally found this thread.  Signal Community thread looked inactive.  I've had this issue gor several months.  Was too busy to complain until now.  Going to agree with comments above.  Never mind shiny bells and whistles.  Please fix this basic functionality.

**Comment by Tursko** [comment]
Re-enabled 
https://github.com/signalapp/Signal-Android/commit/56f7564ce4466cead47654b32dd44c5f9b8d5e31

**Comment by alex-signal** [comment]
Yup, I meant to post last night that I'd (hopefully) fixed it. It's in beta now and should be coming soon to a prod build near you.

**Comment by pgnd** [comment]
confirmed in 5.9.4.  thx!

**Comment by ArchmageArcane** [comment]
Yep.  Working now.  Many thanks!

**Comment by olimju** [comment]
Thank you, donation made!!  Now if we can get [SMS import](https://github.com/signalapp/Signal-Android/issues/10618) fixed, that'll remove the other glaring barrier to entry.

**Comment by caitsith01** [comment]
> 
> 
> confirmed in 5.9.4. thx!

Dumb question, but if I have the standard app store app installed, how do I move to this version (app store version claims to be up to date at 5.8.10)?

**Comment by alex-signal** [comment]
@caitsith01 5.9.4 is the beta version, the final production version for 5.9.x is 5.9.5 and currently in a staged rollout. You should get the update within the next couple of days if you haven't already.

**Comment by lokihiker** [comment]
> @caitsith01 5.9.4 is the beta version, the final production version for 5.9.x is 5.9.5 and currently in a staged rollout. You should get the update within the next couple of days if you haven't already.

Hello Alex, I have a Pixel 3a, Android 11, running Signal v5.9.7 (updated May 7th, 2021).  I can confirm that this issue is *not* fixed.  Please advise.

**Comment by ArchmageArcane** [comment]
I have 5.10.5 beta on LG Phoenix 4, Android 8.1.0.

Mixed results.  Can forward texts to non-signal contacts.  Sharing pictures (from gallery) still not working.  Works if I open same contact in Signal and add the image.

**Comment by sorenmogensen** [comment]
For me the issue is partly fixed. With 5.9.5 you can forward text messages to any contact, but strangely not to any number. 
Workaround is simple enough, i.e. add a number to contacts before being able to forward a message.

**Comment by caitsith01** [comment]
Confirming that this is also fixed for me, but **only** for plain text SMS messages, not for MMS messages or sharing media.  Hence this issue is still open: 

https://github.com/signalapp/Signal-Android/issues/10942

**Comment by caitsith01** [comment]
> Yup, I meant to post last night that I'd (hopefully) fixed it. It's in beta now and should be coming soon to a prod build near you.

This is still not fixed for forwarding MMS messages - only Signal contacts are shown. This should not be closed.

**Comment by OsBlaineOra** [comment]
Still not fixed for MMS messages. Version 5.11.5

Should be open.

**Comment by ArchmageArcane** [comment]
Can forward text and images in 5.13.2 beta.  Will have to find a video or have someone send me one to see if that forwards.

**Comment by Rahulpudhari** [comment]
I have the modified the signal app source code changed the package name
splash screen and some ui . I want to publish my app in playstore. Did
playstore will publish it?

**Comment by Tabby** [comment]
Still broken on version 5.24.14
Cannot forward spam SMS to 7726
![Screenshot_20211010-084753](https://user-images.githubusercontent.com/2601930/136687276-afa16ca8-78c6-4707-b980-9e509d7ea4fc.png)

**Comment by Tursko** [comment]
> Still broken on version 5.24.14
> Cannot forward spam SMS to 7726
> ![Screenshot_20211010-084753](https://user-images.githubusercontent.com/2601930/136687276-afa16ca8-78c6-4707-b980-9e509d7ea4fc.png)

Not broken, that's just not a feature that's implemented. There's a feature request on the forums for forwarding to phone numbers. I know that the Signal team wants to add it at some point.

**Comment by Tursko** [comment]
> > > Still broken on version 5.24.14
> > > Cannot forward spam SMS to 7726
> > 
> > 
> > Not broken, that's just a feature that's not yet implemented.
> 
> Incorrect. This is functionality that used to work but no longer does. It is broken.

A signal developer says otherwise: https://github.com/signalapp/Signal-Android/issues/11650#issuecomment-938677846

**Comment by ArchmageArcane** [comment]
I'm able to forward to 7726 here.  That functionality was broken, but returned several months ago.

**Comment by Tabby** [comment]
Yeah it does work if you add it as a contact. I honestly don't understand _why_ you can send to a contact but not a typed in number given that a number has to be pulled out of the contact to send to so it should be trivial to accept one that's typed in, but as long as there's a workaround that isn't too complex it's not a huge problem

Thanks for the clarification

**Comment by criptych** [comment]
> A work around for now is to add that phone number to your contacts, you'll be able to forward to it after that.

I also had to refresh my Signal contacts list before the new entry appeared – which was not very straightforward either.  You have to start a new message and select "Refresh" from the menu in the contacts list there; I only found it somewhat by accident.
