### ISSUE TITLE
Receiving SMS as email from unknown account.

### ISSUE THREAD

**Issue by CyberBismark** [signalapp/Signal-Android#10928]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When my partner sends me an SMS from their iPhone (iOS 14.4) to my Samsung S20 (Android 11), Signal does not receive or notify me of the SMS. Instead, if I check my email, I see that I have received an email from an account they don't own: [their number]@optusmobile.com.au. This is doubly strange because neither they nor I use Optus Mobile. This email has a TXT file attached with the content of the intended SMS.

This doesn't seem to happen with other SMSs from other senders, just my partner's, for some reason.

### Steps to reproduce
- Have an iPhone with iOS 14.4 send an SMS to an Android 11 device using Signal as default messenger.
- Check Signal, verify that the message has not been received.
- Check email.
- Find email from unknown account (eg. 0412345678@optusmobile.com.au) with attached TXT file.
- Open TXT file to find content of SMS.

**Actual result:** Message arrives as TXT file in an attached email. Signal does not notify recipient that any such SMS even exists.

**Expected result:** SMS should be received normally by Signal.

### Device info
**Device:** Samsung Galaxy S20
**Android version:** 11 (One UI version 3.0)
**Signal version:** 5.3.12

### Link to debug log

https://debuglogs.org/8c336ca208aa880ac5b3bbda5425264534eadd53eeee6ba8bbc624747fa02400

**Comment by Genis-Sage** [comment]
Hey @CyberBismark
what happens, when you use another sms app on Android side? So the Samsung native app or Android messages...

I can't believe, that this is related to Signal in any way

**Comment by Caerbannog** [comment]
Could you check on your partner's phone what phone numbers are saved for your contact?
Could your partner be sending messages to your "land line" phone number by mistake, and your carrier delivers it to the email of your account? 
But this is a wild guess. Check what @Genis-Sage says.

**Comment by CyberBismark** [comment]
> Hey @CyberBismark
> what happens, when you use another sms app on Android side? So the Samsung native app or Android messages...
> 
> I can't believe, that this is related to Signal in any way

I tried switching my default SMS app to be the standard Android Messages. The issue still persists and I can't receive messages on there either, so you might be right that this isn't a Signal problem.

**Comment by CyberBismark** [comment]
> Could you check on your partner's phone what phone numbers are saved for your contact?
> Could your partner be sending messages to your "land line" phone number by mistake, and your carrier delivers it to the email of your account?
> But this is a wild guess. Check what @Genis-Sage says.

I'll check on their phone as soon as I can.

**Comment by CyberBismark** [comment]
I verified the number on their phone. Turned out that they were texting my email address by mistake. I deleted the conversation sent to my email address and sent a text to my actual mobile number. Signal received it fine, so I'm closing this issue. Thanks for all the help!
