### ISSUE TITLE
Can no longer share over SMS/MMS

### ISSUE THREAD

**Issue by sesse** [signalapp/Signal-Android#10920]
Hi,

It seems Signal recently changed its sharing UI to be able to share with multiple people. (Share as in long-pressing a message and pressing the thick right-arrow button.) This has three issues for me:

1. It makes the flow much more cumbersome for the common case of sharing with one.
2. If I share with multiple, it's unclear what the semantics are. Do I open new group chat? Does it duplicate the messages?
3. Most critically, I can't share with anyone not on Signal anymore. People on SMS/MMS are simply gone from the dialog box.

Sharing messages from Signal to SMS/MMS users always had its issues—in particular, images would not get properly transcoded without going in and making a fake edit (e.g. a 1px crop). But taking it out entirely seems a bit odd?

**Comment by caitsith01** [comment]
I have the issue too. The problem is not limited to images and includes forwarding messages too. Signal displays only recent conversations and Signal contacts but not non-Signal contacts.

**Comment by UserX404** [comment]
Maybe related: #10929

**Comment by jmbhill** [comment]
I'm still having this problem with Signal 5.4.11 on Android 11.

**Comment by j-dexx** [comment]
I've also got this issue

**Comment by caitsith01** [comment]
Still experiencing this behaviour...

**Comment by caitsith01** [comment]
This now appears to be fixed for SMS but not MMS.  Related bug here still open: https://github.com/signalapp/Signal-Android/issues/10942
