### ISSUE TITLE
SVG media files hide gallery selection button on Camera view

### ISSUE THREAD

**Issue by kon14** [signalapp/Signal-Android#10922]
I stumbled upon this issue and was able to successfully reproduce it after downloading an SVG file as my latest image file.
I'm not particularly familiar with Android development and how the ecosystem handles file previews (app-side exposed or os-side exposed), but I'm fairly sure anyone having just downloaded an corrupted file as their latest media file, or more accurately one that's either unsupported by the system or otherwise unpreviewable as a thumbnail, will hit this.

### Bug description
When the user's **latest** media file to be downloaded is an SVG file, the gallery selection button that normally shows a preview of the latest image available turns transparent and is therefore completely indistinguishable from the camera view spanning most of the screen.
Thus the user ends up with no visual cues as to whether the ui supports bringing up the gallery and so on.

In contrast to this, the media asset's preview shows up as a blank/black rectangle once you actually get into the gallery selection.

### Steps to reproduce
- Download an SVG file.
- Open a Signal Chat.
- Click the Camera/Media button in the text input area.

**Actual result:** Notice how there's no Gallery preview ui element on the bottom-left of the display.
**Expected result:** Show a corrupted image thumbnail (similar to FB Messenger's), a blank rectangle or even the first valid gallery thumbnail available.

Are SVGs supported by Signal at all? If not, shouldn't the app prevent the user from seeing/selecting them in the gallery app?
Unless of course such behaviour differs per platform or os version.

I'm attaching a screenshot comparison between normal and buggy behaviour.

![compare](https://user-images.githubusercontent.com/1786609/107125585-84b7ba00-68b3-11eb-9020-1095b456c9f1.png)

I was originally going to provide my SVG file, but I tested with a random one off the web and it seemed to also hit this.
Let me know if you have trouble reproducing this so I can link to it.

### Device info
**Device:** LG G8S ThinQ
**Android version:** 10
**Signal version:** 5.2.3

**Comment by Nisc3d** [comment]
Still not fixed.
