### ISSUE TITLE
Contact Profile picture and About Status is not getting refreshed

### ISSUE THREAD

**Issue by SignalAppTester** [signalapp/Signal-Android#10927]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Contact Profile picture and About Status is not getting refreshed whenever my contacts are seeing my profile

### Steps to reproduce
1: Change your profile picture and About Status
2. Take one of contact's mobile and check your changed profile picture and about status and it is not seen in your Contact mobile

**Actual result:** My changed profile picture and about status should gets refreshed whenever my contacts seeing those
**Expected result:** But it is showing old one or not showing at all

### Screenshots
NA

### Device info
Real me 7i

### Link to debug log
NA

**Comment by hiqua** [comment]
Debug log?

I have the same problem with some contact: I used to have "use address book photos" ticked, and this contact had a picture saved in my local contacts. I removed the picture, and unticked the option, but Signal does not download their profile picture, it looks like they have none (and I know they do have one).

https://debuglogs.org/52eb4027424b2f456a7da4ced996eed9652b0437e662372f62962f32d5743d0c
