### ISSUE TITLE
Notification not shown due to missing permission to access custom ringtone file

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#10934]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal stopped showing notifications after a few weeks. The debug log below reveals that an exception is thrown on accessing the custom ringtone file. However, is used to function properly for quite some time. Oddly enough, after selecting the same file again as ringtone, notifications are shown again without issues.

### Steps to reproduce
I honestly don't know how to reproduce the loss of the file access rights. Maybe the following works:
- set a custom ringtone for notifications
- receive some messages
- revoke access to the ringtone file for signal (But how? Renaming?)
- receive some messages

**Actual result:** No notifications on incoming messages are shown and an exception is written to the log
**Expected result:** I either expect the notifications to be shown no matter whether the ringtone can be accessed or not. If the file is inaccessible, a some default ringtone should be played as fallback and the users should be notified about the issued, e.g. "Can't finde ringtone file. Has it been moved? Please set a new ringtone."

### Device info
**Device:** Redmi8T MIUI 12.0.2
**Signal version:** 5.3.7.1

### Link to debug log
https://debuglogs.org/9a84d43aa10d55ebad32654fbbff91890c1d7da9b3776d1dea6bee96d314fc90

**Comment by despider001** [comment]
Wanted to add this issue, thanks. Notification is not coming through!

**Comment by konbeto** [comment]
I have the same problem and also use the Xiaomi Redmi 8T Device. 

However, thanks to the hint from @merkste , that this issue is based on a permission/accessing problem of the notification sound file, I was able to find a work around:

I copied my sound file directly into the Signal folder (the folder where Signal also stores its backup folder). 
After  setting Singal to to use the sound file in this folder, noticfications worked again.

**Comment by JonathanHarford** [comment]
I had the same problem on my Pixel 3XL, and fixed it by copying the audio file from my audio recorder directory (/EasyVoiceRecorder) to /Notifications.

**Comment by tswast** [comment]
Same problem here on a Pixel 3. https://debuglogs.org/22ee39484180480525a61c75d24d306708804b2f9251c546652a3cd0e897d7df

Switching from a custom (but still built-in) notification to the system default restored notifications. I'd much rather use a louder sound for Signal than what I use for notifications in general, though.

**Comment by dandoor** [comment]
In my case, the ringtone file was moved to a different location. It was driving me crazy why notifications were show consistently for particular users and consistently not shown for others.

Signal team, please use some sort of fallback or even show the notification silently. The current behavior of failing silently is not a good solution at all. Thank you.
