### ISSUE TITLE
Devices with Legacy level Camera2 API show badly rotated video preview, when changing phone orientation

### ISSUE THREAD

**Issue by clauz9** [signalapp/Signal-Android#10940]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening the camera in Signal in portrait mode and rotating it to landscape, makes the preview window display the video rotated 90 degrees opposite to the direction in which you've rotated the phone. This also happens if your start the camera in landscape mode and rotate to portrait. I've tested this on 3 phones, 2 have this bug,  but the third does not. a Samsung SM-A105FN. 
The pictures get saved correctly. 

### Steps to reproduce
- Open Signal
- Open the camera, in portrait or landscape
- Rotate to landscape or portrait

**Actual result:** The preview window shows the video rotated opposite to the orientation of the phone. 
**Expected result:** I expect it to work the same way, most default camera apps work, keeping the video stream locked in the preview window and just rotate the overlay icons in place around their axis to correspond to gravity. 

### Screenshots
- Signal landscape preview window

![pic](https://user-images.githubusercontent.com/77681918/107303619-18da7a80-6a88-11eb-807e-f60b6b08005c.jpg)

- default camera app landscape preview (overlay controls rotated only) 

![image](https://user-images.githubusercontent.com/77681918/107303942-bcc42600-6a88-11eb-9fd9-1b09ab1711fa.png)

- default camera app portrait preview 

![image](https://user-images.githubusercontent.com/77681918/107304034-f432d280-6a88-11eb-9c11-5c5532f7c568.png)

### Device info

**Device and Android version:** Nokia 3.1, with Android 10 
**Device and Android version:** Philips S326, with Android 5.1

**Signal version:**  5.3.12 but it also happens in 5.3.5 

### Link to debug log
- Nokia with Signal v5.3.5 
log: https://debuglogs.org/fce7da1c7e47bcbc947014f41b67b5f1a56fb8b08d7bd0613c55dec180755b78

- Philips with Signal v5.3.5 
log: https://debuglogs.org/a917cbbcfb28140af44b1e9e460c2a5426d3e4d80557799e5343e2df22ee73cb

- Nokia with Signal 5.3.12
log: https://debuglogs.org/ba751ebace4a90e449fb6c009d42d402dbab1460e19a130ed58ed4b5e8372d98

- Philips with Signal v5.3.12
log: https://debuglogs.org/89c74b9dae7897a5125f9bd00a0b6c0712b368ff7d851667f53e09ddbb968371

**Comment by rainerm77** [comment]
I was able to confirm and reproduce this bug with a different device (Moto G5, Android 8.1) and Signal Beta v5.4.6, Andorid-screen-autorotate mode switched on.

@Developers:
Please keep in mind that this bug might annoy/discourage recently new WhAp-switchers, because it happens quite often, and the workaround is not very intuitive. Because the most intuitive way to use it, is using Signal in portrait mode, and thus also intuitively press the camera-button when still holding the phone in portrait mode. And only 1-2 seconds later, when the camera already started turn it to landscape. I do this since years intuitively in the same order when starting the main Android-Camera from the Homescreen…

Remark: Since I was not aware of the bug-report here before, I've also documented the bug with screenshots in the signal community forum here:
https://community.signalusers.org/t/starting-built-in-camera-in-portrait-and-then-turning-phone-to-landscape-mode-shows-the-preview-video-90degrees-wrong/28603

**Comment by suther** [comment]
I have the same issue on Xiaomi A1 with Android 9.
I don't see what you mean with "Android-screen-autorotate". Do you mean the Android-Functionality for the whole device "auto rotate", or an Signal option to set?

BTW@ Your workaround didn't work. If I open the Camera while Signal is in portrait mode, and wait 10 seconds... rotate the device, the issue still appears.

**Comment by rainerm77** [comment]
@suther sorry, if it was confusing: What I actually meant with "Android-screen-autorotate = on" was the Android-Functionality to globally (for all apps) turn on "auto rotate".

And with "workaround" I meant the following sequence: If "auto-rotate=on", then the workaround is to rotate the device already into the desired position (either portrait or landscape) *BEFORE* starting the built-in Signal-camera, but then during camera is running until the shutter has been pressed *never* rotating it. In this order it should work (at least with my Moto G5 / Android 8.1) - could you please try the workaround in this order?

**Comment by suther** [comment]
Ah ok. I still know the "rotate before take a photo", but was wondering what exactly you mean. 
So that means at least this bug still exist!

Maybe it would help to check in the app-sourcecode if auto-rotation is on or of to fix this issue on Android.

**Comment by kosaimgmg2021** [comment]
#9297
