### ISSUE TITLE
Beta 5.4.0: Notifications only delivered when the app is open

### ISSUE THREAD

**Issue by 4n0nym0u53** [signalapp/Signal-Android#10949]
### Bug description
Message notifications only gets delivered when the app is open, even if it's open in the background. They don't get delivered when the app is closed from the recents screen, but the sender sees the message as delivered. This only applies to Signal messages, not SMS. Battery optimization for the app is set to "Don't optimize".

### Steps to reproduce
- Update to latest beta version 5.4.0
- Close the app by swiping it up from the recents screen
- Get someone to message you (Signal message)
- Wait a bit before opening the app, and see the message get delivered in front of your eyes

**Actual result:** Messages/notifications only gets delivered when the app is open (even in background).
**Expected result:** Messages/notifications should get delivered even if the app is closed.

### Device info
**Device:** OnePlus 8T
**Android version:** 11
**OxygenOS version:** 11.0.6.9.KB05BA
**Signal version:** 5.4.0 Beta

### Link to debug log
https://debuglogs.org/f9fe51ec88f17479eac125ddd0dd8b8e30f149edb81bb755f3ba398ecc2765ce

**Comment by cody-signal** [comment]
This particular issue should be fixed in 5.4.1 Beta

**Comment by 4n0nym0u53** [comment]
Yup, it's fixed, great job! Closing this issue.
