### ISSUE TITLE
Fingerprint Unlock Crashes App

### ISSUE THREAD

**Issue by tracerTres** [signalapp/Signal-Android#10954]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal had passphrase enabled. On upgrade to android 11, Signal was not locking hence I enabled screen lock under settings. After unlocking using fingerprint the app crashes.

### Steps to reproduce
- Signal with passphrase enabled (android 10)
- Upgrade to android 11
- Enable Screen lock in settings
- Try to unlock using fingerprint
- App crashes

**Actual result:** App crashes
**Expected result:** Finger print unlocks

### Device info

**Device:** Samsung S10+
**Android version:** 11
**Signal version:** 5.4.2
### Link to debug log

https://debuglogs.org/93fb9fce33a46aa335fef20bc03f186c738e3932ce1750c10c209a1849f8259a

**Comment by Dhanurjan** [comment]
Did you try reinstall signal?

**Comment by tracerTres** [comment]
Tried clearing the app cache, still didn't work. I cannot backup data since I cannot unlock Signal.

**Comment by henryk** [comment]
I have identical symptoms and mostly same backtrace on Android 8.1.0, so probably not an Android version issue.
Maybe we can get access back once https://github.com/signalapp/Signal-Android/pull/10133 is shipped in Signal 5.4.8 (by putting the *wrong* finger on, which shouldn't trigger the crash code path and instead go to fallback pin after 5 mistries).

**Comment by henryk** [comment]
Ok, forget the idea with the wrong finger, that would only apply if the fingerprint were the issue.

I think @tracerTres and me have triggered https://github.com/signalapp/Signal-Android/blame/b809008291136ab1490688e3df2e5de358be76df/app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L281 which already had that as a comment by @johanw666 https://github.com/signalapp/Signal-Android/commit/a3556d9f68d102022d69bb0fbe955e414d38dacd#comments

I do have root access to my phone and a two year old backup of the raw `/data/data/org.thoughtcrime.securesms` data, but I'm unsure how much state (for example in the hardware backed keystore?) has been destroyed.
I might try to backdate the Signal installation date in my phone's package registry (to not trigger the abovementioned code path) and then manually flip `pref_disable_passphrase` to off and `pref_enable_passphrase_temporary` to on? Would that restore things?
