### ISSUE TITLE
Message preview flickers if it contains smileys

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#10957]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If the last message of a conversation contains a smiley or several, the message preview flickers, seemingly hesitating in what to display. On this video (AVD emulator, Nexus 4 API 30), it only flickers once, but I have a slower device where it flickers at least 3 times.

### Steps to reproduce
- receive a long message containing a smiley
- open the conversation
- go back to main screen (back button)
- look at the message preview

**Actual result:** the message preview flickers, e.g. in the video a smiley either appears or is replaced by `...`
**Expected result:** the message preview should not flicker

### Video

https://user-images.githubusercontent.com/3812042/107829738-aa98ff00-6d8a-11eb-9823-8b67b6e0407b.mp4

### Device info
**Device:** AVD Nexus 4 API 30
**Android version:** 11
**Signal version:** 5.4.3

also reproduced on an actual device where I saw it first.

### Link to debug log (I don't think it's relevant)
https://debuglogs.org/a4885d1868cb6fef48fff8f8a7b2df16362e4ff3c9ca333e3a765f4dfb909914

**Comment by qosch** [comment]
I can reproduce this on my phone and would like to add that the message preview also flickers when the smileys aren't part of the preview because they are at the end of the message that was cut off.

**Comment by rainerzufall** [comment]
another video and log:

![signal-2021-05-06-160044](https://user-images.githubusercontent.com/12666598/117322078-fb059180-ae8d-11eb-91c1-d5db69751013.gif)

https://debuglogs.org/8dd7c76420fae815ca450a2201c766110704ce905f05780c572619fead327dd2

**Comment by hiqua** [comment]
Fixed recently, I think.
