### ISSUE TITLE
Reactions require two or more attempts in the latest beta

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#10959]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Reactions require two or more taps in the latest beta.

### Steps to reproduce
- Update to Signal >= 5.4.3 (my actual version is 5.4.4 but the bug started in 5.4.3)
- Try to react to the messages consecutively

**Actual result:** Reactions only appears after two or more attempts.
**Expected result:** Reactions will work fine in the first attempt.

### Screenshots

https://user-images.githubusercontent.com/32582878/107844181-45033d80-6d9f-11eb-906b-f2d6ea44d92c.mp4

### Device info

**Device:** Samsung
**Android version:** 10.0.0
**Signal version:** 5.4.4

### Link to debug log

https://debuglogs.org/95d01d324b5ff0637f63c2178747fe4f8036caa0aef8de2051e07797f10e7b94

**Comment by Kwasow** [comment]
I think the issue is that the touch area for specific icons is too small and therefore it's very easy to miss it. I've been experiencing it too and it's very annoying.

Android version: 10
Signal version: 5.4.4
