### ISSUE TITLE
Changed Safety number can't send message

### ISSUE THREAD

**Issue by Leptopoda** [signalapp/Signal-Android#10950]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Bob changed device (new safety number). Trying to send a message will display the `Safety Number Changes` screen. Hitting `SEND ANYWAY` does not work

### Steps to reproduce
1. I'm in a group with Bob (never texted in PM)
2. Bob changes Safety Number
![signal-2021-02-11-144643](https://user-images.githubusercontent.com/25266387/107644846-44bc5280-6c78-11eb-9217-d61ac95a941f.jpeg)
3. Bob messages me in PM (first time)
4. I can't send him a message anymore from Android

Also: 
- I can still send messages to the group or to Bob from iOS or the desktop (I sent one to the group between 2. and 3.)
- **I never marked the safety number with Bob as verified**

**Actual result:** Hitting `SEND ANYWAYS` does just close the prompt and still fail the sending
**Expected result:** The message should go through

### Screenshots
![signal-2021-02-11-144630](https://user-images.githubusercontent.com/25266387/107644877-4dad2400-6c78-11eb-8a5f-fb54a40c135e.jpeg)

### Device info

**Device:** Xiaomi Mi A3
**Android version:** 10 (LOS 17.0)
**Signal version:** 5.4.1
**Play Services:** Nope

### Link to debug log
https://debuglogs.org/64fe84ed76d4bf426f0ce77eec484beb3fcd1a96ae3da01281677ad090667894

>02-11 14:51:45.956 14224 14296 W TextSecureIdentityKeyStore: Identity keys don't match...
02-11 14:51:45.957 14224 14296 W PushTextSendJob: [JOB::0f00dbb9-29c5-4ef5-97dd-703f18ac39b6][PushTextSendJob][1613046417132] Failure (Time Since Submission: 181 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: org.whispersystems.signalservice.api.crypto.UntrustedIdentityException: Untrusted on send
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1579)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1537)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1384)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:275)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:179)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onPushSend(PushTextSendJob.java:94)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:102)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:42)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
02-11 14:51:45.957 14224 14296 W PushTextSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

**Comment by jmechnich** [comment]
Could be the same or at least related to https://github.com/signalapp/Signal-Android/issues/10256 ?

In any case, seeing the same issue after my buddy had to reinstall his app.

**Comment by Leptopoda** [comment]
Thanks @jmechnich
