### ISSUE TITLE
Signal Android 5.4.3 crashes on opening

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#10956]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgrading from 5.4.2. to 5.4.3. Signal crashes when I try to open it.

### Device info
**Device:** Pixel 3
**Android version:** GrapheneOS, Android 11
**Signal version:** 5.4.3

### Link to debug log
Couldn't make debug log because of the crash. :(

**Comment by Dhanurjan** [comment]
Hmm i didnt got the 5.5.3 update yet

**Comment by bungabunga** [comment]
Solved in 5.4.4. ✨🎉
