### ISSUE TITLE
Videos 1440p and above either crash Signal when I send them or they get corrupted in transit

### ISSUE THREAD

**Issue by clauz9** [signalapp/Signal-Android#10955]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have tested this on 3 phones, a Samsung A10, a Nokia 3.1 and a Philips S326, the Samsung and the Nokia crash when I try to send a 1440p or above video, but I think the video editor that opens before you actually send the file is at fault, and on the Philips I've had differing results depending on the video resolution. 

I've also corroborated this with the original finder of this bug on the signal forum. 
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-3-release/25088/434?u=clauz

### Steps to reproduce
- download a 1440p or above, resolution video from youtube, or use the 4K one from here 
https://up2sha.re/file?f=DzkdRvWmURmDhlZ7hn
- try to send it to someone, using the "gallery" tab.

**Actual result:** On two devices (Samsung and Nokia) it crashes Signal, and on the Philips it gets corrupted in transit, for the 1440p version and the 4k version failed to send.

**Expected result:** It should not crash, and when it get's sent it should work on the other side. 

### Screenshots
![image](https://user-images.githubusercontent.com/77681918/107819535-01e6a180-6d82-11eb-93c4-3d948f407018.png)

### Device info
**Device and Android version:**  Samsung A10 running Android 10
**Device and Android version:**  Nokia 3.1 running Android 10
**Device and Android version:**  Philips S326 running Android 5.1

**Signal version:** The tests have been done on 5.3.12 and 5.4.2

### Link to debug log
- Crash log from Nokia 3.1 running Signal 5.3.12 sending a 4K video
https://debuglogs.org/0da9d22894ffbf019a5853c5abdb160027649aa00d19c1363c17631b020f4b40

- Crash log from Nokia 3.1 running Signal 5.4.2 sending a 1440p video
https://debuglogs.org/9934afa0bf0fef5a3df27b8b66709a911c3b9cd7aa7ce3c61543876b0c701f62

- Crash log from Samsung A10 running Signal 5.4.2 sending a 1440p video https://debuglogs.org/8d17cac7120761e950ff2de1e552158b93912cd6bfd540ccda97965a97643d76

- Send Fail log from Philips running Signal 5.3.12 sending a 4K video
https://debuglogs.org/70cbf5d4b7a374d29382a5908b49b2d1d3b539fdd1470abaf8aca2dcce44053a 

- Log from Philips running Signal 5.4.2 after sending and corrupting a 1440p video
https://debuglogs.org/44b0a3daced80dd8f6f0e913b83dd38cc7822d21310f295537fea741eecdcb56

**Comment by fr33tux** [comment]
To add some details, on a Pixel 3a with the stock camera app on Android 11. I did two sets of tests, always with the stock camera app:

* recorded 1080p and 4k videos of the same duration, and I could only trigger the crash during previsualisation/editor for 4k videos. 1080p ones are fine.
* recorded 1080p and 4k videos of (approximately) the same filesize. And same thing, the 4k videos are the only ones that make Signal crash at the previsualization/editor phase.

**Comment by fr33tux** [comment]
I'm still facing the crash on a Pixel 3a when I send a 4k video to a Signal contact, Android 11 with latest patches:

```
--------- beginning of crash
04-11 16:31:55.471 31128 18406 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #48
04-11 16:31:55.471 31128 18406 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 31128
04-11 16:31:55.471 31128 18406 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at android.media.MediaCodec.native_stop(Native Method)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at android.media.MediaCodec.stop(MediaCodec.java:2251)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsExtractor.extractThumbnails(VideoThumbnailsExtractor.java:108)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:185)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:165)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-11 16:31:55.471 31128 18406 E AndroidRuntime: 	... 4 more
```

Might be a related error here: https://github.com/google/ExoPlayer/issues/5935 ?

**Comment by tomkel** [comment]
> I'm still facing the crash on a Pixel 3a when I send a 4k video to a Signal contact, Android 11 with latest patches:
I also get the crash
