### ISSUE TITLE
Version 5.3.12 Android not compatible with New Groups, cannot update it

### ISSUE THREAD

**Issue by RiverC** [signalapp/Signal-Android#10958]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot access "new groups" despite being updated to the latest version of Signal on Android

### Steps to reproduce
- I go to upgrade our group to 'new group'
- l am listed as a person who will be removed from the group because my version does not support new groups
- Check my apps under Google Play Store
- I cannot update Signal, it is version 5.3.12 and was updated 2 days ago
- I restart my phone, still not compatible
- I edit my profile to 'refresh it' (unsure how to refresh profile)
- Still incompatible
- I force stop the app and start it again
- Still incompatible

**Actual result:** Cannot make my Signal app compatible with new groups
**Expected result:** Latest version of Signal should be compatible with new groups

### Device info
**Device:** Galaxy A10e
**Android version:** 10
**Signal version:** 5.3.12

### Link to debug log
https://debuglogs.org/680dfe37548d8d726cbcd4b290507b982f75665d5f15daaeb6d3c90bbcda9095

**Comment by Dhanurjan** [comment]
Im not sure about the stable version. Im a beta tester on version 5.4.2 and everything working fine for me. Soon they will release the update for stable version.

**Comment by Dhanurjan** [comment]
Wait for another stable version update or switch to beta version on playstore.
[https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=Signal+beta](signal beta apk download)

https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=Signal+beta

**Comment by hiqua** [comment]
Do you have any linked device running an older version of Signal-Desktop? All your devices have to support newer groups. If you have older devices that you no longer us, try disconnecting them first.
