### ISSUE TITLE
You can Initiate Video/Audio Calls with Blocked Users From Conversation List

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10971]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can Initiate calls with people you block on Signal. The calls won't actually go through but you def shouldn't be able to do this at all. also on your conversation screen with that blocked user it'll say that you tried to audio/video call them

### Steps to reproduce
- block someone 
- return to the main conversation screen
- click their avatar/icon
- there will be buttons to text/call/video them

I guess these buttons shouldn't exist, basically. 

Clicking the texting button takes you your conversation with them

Clicking the video chat button initiates your camera, the person that you blocked won't receive a video call from you but it'll appear to the user that you are being filmed ringing someone blocked 

Clicking the audio call button starts a call, which also won't go through, but signal will tell the user that they cant be calling blocked people

**Actual result:** buttons appear to contact the blocked user. they can be clicked and are scary
**Expected result:**  those buttons shouldn't appear whatsoever

### Device info

**Signal version:** 5.3.12

**Comment by Sgn-32** [comment]
Yes

**Comment by Sgn-32** [comment]
PR was merged in 5.31.0 beta. https://github.com/signalapp/Signal-Android/commit/befb720edad8566b891370898f6fe779eb10d942
