### ISSUE TITLE
Can't send messages to particular person who just joined app

### ISSUE THREAD

**Issue by dspacejs** [signalapp/Signal-Android#10974]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't send messages to a friend who just joined the app, but I can send it to other people fine. I sent the same person a message using Signal on Linux and it worked, therefore the issue must be because of Signal on Android.

I was also able to call this person on Android, so something is wrong with messaging specifically. And they were able to send me messages without problems.

I also tried restarting my phone, but that didn't work.

### Steps to reproduce
- get someone to join and make an account
- send them a message

**Actual result:** it's stuck in the "sending" state
**Expected result:** the message should send successfully without issues

### Device info
**Device:** Pixel 2 XL
**Android version:** 11
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/04fa23d862963ae0ce7ff49eb6dafa42b66930cd8d623dee3cd23ca7a61efff0

**Comment by Dhanurjan** [comment]
Update your application and try again

**Comment by dspacejs** [comment]
@Dhanurjan still doesn't work.

**Comment by ibby89** [comment]
I can report that this seems to be happening to two contacts on my contact list as well (I'm on iPhone so it's not affecting me). Everyone in a specific group chat can send messages, but one user who is on Android cannot see messages from one other group member only (even mentions don't seem to work).
We've tried getting that user to follow the contact refresh and resync guides on the KB but it hasn't done anything. I suspect this might be due to encryption keys as the group member's messages he is unable to see deleted Signal and reinstalled it and now he does not show up in the user's contact list (even when searching by number).

**Comment by dspacejs** [comment]
I still can't message this person. They've been using the app for several days now.

**Comment by dspacejs** [comment]
Now this is happening with another friend, who I've been speaking to for months. They can message me, but I can't message me. It randomly started happening.

Because of this, this is a major bug and should therefore be a high priority issue.

**Comment by dspacejs** [comment]
Now I can suddenly send messages to the first person. I'm not aware of anything changing since then. But I can't message the second person.

**Comment by greyson-signal** [comment]
@dspacejs Looking at your original log, it seems like you have an SMS that is failing to send in that chat, which is then blocking all future messages (we send messages serially). I imagine that for whatever reason we don't think you have cell service (which is different from generic internet service) and therefore aren't even attempting to send the SMS. I'd suggest turning on Settings > Sms and MMS > Wifi-calling. That'll let us send SMS over wifi if your carrier permits it.

**Comment by dspacejs** [comment]
@greyson-signal my carrier doesn't have WiFi calling, so how would this work for SMS? And wouldn't that only be useful for calls, I don't get how that enables you to send SMS over WiFi if it was working perfectly fine before without this setting.

I can't find these setting despite it showing on search results, either. I'm on Graphene OS, so I'd have to look into it further. I haven't noticed this bug in a fair while though, so I'll go back and do this if it happens again.

**Comment by greyson-signal** [comment]
@dspacejs This is a signal in-app setting, not something in your system settings. I know it's labeled 'wifi calling', but when it's on it means we'll attempt to send SMS with only a wifi connection.

And we can definitely send SMS fine without it on if you have a cellular connection -- but your logs showed an SMS message that was stuck, and usually that means that, for whatever reason, we don't believe you have cell service and therefore don't attempt to send the message. Turning on our in-app wifi calling setting would let us try to send the SMS message with just wifi.

If everything is fine now you obviously don't have to do anything, was just trying to debug with the log you provided :)

**Comment by dspacejs** [comment]
@greyson-signal thanks, I turned it on to hopefully prevent this in the future (if it ever happens again).

> This is a signal in-app setting, not something in your system settings. I know it's labeled 'wifi calling', but when it's on it means we'll attempt to send SMS with only a wifi connection.

IIRC I did have a cellular connection. So I'm not sure what happened here. It may have been a bug?
