### ISSUE TITLE
You Can Add Blocked Users to Groups

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10970]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can add blocked users to Groups and seemingly they are actually added

### Steps to reproduce
- block a user 
- return to the conversation list main screen thing
- click on the icon/avatar of the user you blocked
- Click add to a group... add them to one

**Actual result:** blocked user is added to a group
**Expected result:** you shouldn't be able to add them to a group. the add to a group menu item should not be there whatsoever 

### Device info

**Signal version:** 5.3.12

**Comment by bitmold** [comment]
this is somewhat related to #10971 except this issue is more dangerous because it allows you to actually communicate with someone you blocked

**Comment by Sgn-32** [comment]
https://community.signalusers.org/t/group-messages-are-also-sent-to-blocked-contacts-is-this-the-correct-behavior

**Comment by bitmold** [comment]
huh i didn't know that's how groups worked that's funky - definitely good to prevent you from adding blocked users at least so thanks for implementing that

**Comment by Sgn-32** [comment]
PR was merged in 5.31.0 beta. https://github.com/signalapp/Signal-Android/commit/537a1fa2ea4c1de6c1c7aebdf186e6507719f849
