### ISSUE TITLE
Signal crashes wgen sending inage with invalid file extension

### ISSUE THREAD

**Issue by Frivolous2** [signalapp/Signal-Android#10980]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Signal's "+" menu detects images with invalid file extensions(such as .bin), but upon sharing them the app will crash.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/229a35f2214cca5ec9399133d4732f118e200181732db040acc4e64925f886bd

**Comment by mage1k99** [comment]
## Issue not in issue template format.

seems like they haven't fixed the issue till now.
