### ISSUE TITLE
Cal Notification Sound Extremely Low on Xperia 5 II

### ISSUE THREAD

**Issue by toxpal** [signalapp/Signal-Android#10993]
I don't know if this is related to Signal or phone itself because I used Signal on many different Android phones (stock and custom ROMs), and never had such problems.

Got Xperia 5 II (stock Android 10) 4 months ago and Signal call notification sound is so low I can only hear it when phone is right next to me (if phone is in pocket, can't even hear notification). No problems with SMS notification (loud as it should be) and/or in-call volume. Standard (non-Signal) call notifications are also loud. Other apps are loud too.

Tried uninstalling Signal, changing ringtone - no luck. Today received Android 11 upgrade, but problem still remains. Always using the latest version of Signal. Suggestions?

**Comment by Brn9hrd7** [comment]
Same issue on my Dad's phone, which is a Motorola Moto G8 Plus

**Comment by toxpal** [comment]
OK, so at least I'm not the only one and there's a small chance devs will take a look...

**Comment by toxpal** [comment]
Did full factory-reset today, re-installed Signal, the problem still exists.

**Comment by Brn9hrd7** [comment]
Issue still persists on Motorola G8 Plus

**Comment by dsvk** [comment]
This is now fixed for a relative with a Moto G8 Plus (was previously affected) as of Signal 5.34.5 where Android [telecom integration](https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-1071184150) was apparently enabled (except temporarily excluded OnePlus devices where it causes [another bug](https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-1068560653)).

**Comment by dsvk** [comment]
For anyone coming across here, telecom integration has been [disabled again in 5.35](https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-1102553638) with no further movement since so this issue is almost certainly back as well (and users will eventually be forced to upgrade past 5.34 due to the mandatory 90-day build expiration period).

**Comment by cody-signal** [comment]
Telecom integration is coming back to the app in 5.44 for Google and Samsung devices as we slowly try to reintroduce it.
