### ISSUE TITLE
Stickers are close together an inside each other

### ISSUE THREAD

**Issue by konstantintch** [signalapp/Signal-Android#10997]
**Description:**
The Stickers are inside and ontop of eacht other. They're also very close to each other.

**Reproducing:**
- just happened randomly

**Screenshot:**
![Screenshot_20210218-221656.png](https://user-images.githubusercontent.com/77486385/108425184-669a7400-723a-11eb-8e44-69b9d7d36c8c.png)

**Device and Software Information:**
**Device:** Motorola One Action
**Android version:** 10
**Signal version:** 5.3.12

**Comment by Dhanurjan** [comment]
![Screenshot](https://user-images.githubusercontent.com/64047298/108503021-b67c4800-72d9-11eb-8d19-709ae11198b2.png)
Working fine for me.
Signal version - 5.4.6

**Comment by konstantintch** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/64047298/108503021-b67c4800-72d9-11eb-8d19-709ae11198b2.png)
> Working fine for me. Update your app and try again.
> Signal version - 5.4.6

Its not there anymore after I restardet my phone.

**Comment by hiqua** [comment]
This seems to be the pack in question:
https://signalstickers.com/pack/bc593c890809a5374f42448acb1bbbd2

**Comment by konstantintch** [comment]
Its back to normal
