### ISSUE TITLE
The wiki-page for F-Droid contains errors

### ISSUE THREAD

**Issue by Elendil211** [signalapp/Signal-Android#10994]
Contrary to the [wiki](https://github.com/signalapp/Signal-Android/wiki/F-Droid), F-Droid does not require people to enable "unknown sources". 
If installed as system app (as part of the ROM, via TWRP, via adb, etc.) the [Privileged Extension](https://f-droid.org/en/packages/org.fdroid.fdroid.privileged/) enables F-Droid to work in the same way as the PlayStore.

Since F-Droid does not require manual intervention to update apps, the assertion that Signal offers the same update mechanism, is wrong.

**Comment by Cerberus0** [comment]
Hi @Elendil211,

Please note that this issue tracker is [only meant for tracking bugs in the Signal Android app](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues), not for questions, comments, general discussion, or feature requests. That wiki was created and maintained by the Signal user community, not Signal. I have now moved the wiki over to the Signal Community forum, where we can also continue this discussion:

* https://community.signalusers.org/t/wiki-signal-android-app-on-f-droid-store-f-droid-status/28581

I also made a minor adjustment to the phrasing in response to your feedback. Out of respect for this project's contribution guidelines, please close this issue and continue this discussion over on the community forum. Thanks!
