### ISSUE TITLE
Signal on Desktop crashes - URIError: URI malformed

### ISSUE THREAD

**Issue by Coughey** [signalapp/Signal-Android#11002]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my Windows Desktop Signal app, I am experiencing for the past three days crash of the application, which is resolved for a couple of minutes or hours just be reinstallation of the app. The time frame in which it doesn't crash after reinstall is shortening. The message it tells before a crash is:

Unhandled Error

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at _urlToPath ([REDACTED]\app.asar\app\protocol_filter.js:19:19)
    at Function.<anonymous> ([REDACTED]\app.asar\app\protocol_filter.js:30:35)

### Steps to reproduce
- Install Windows Desktop Signal app (on Windows 10)
- Link it with Mobile Phone device (Android) to start working
- Use it for some time
- It crashes

### Device info
**Signal version:** 1.40.0

### Link to debug log
Unhandled Error

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at _urlToPath ([REDACTED]\app.asar\app\protocol_filter.js:19:19)
    at Function.<anonymous> ([REDACTED]\app.asar\app\protocol_filter.js:30:35)

**Comment by Cerberus0** [comment]
Hi @Coughey,

Welcome to the Signal Android issue tracker! Is there a reason you're posting this issue here instead of the [Signal Desktop issue tracker](https://github.com/signalapp/Signal-Desktop/issues)?

**Comment by Coughey** [comment]
Yes, the reason is I am very bad at looking at project names. :) Sorry and thank you for pointing it out!
