### ISSUE TITLE
sound files get cut off by auto play

### ISSUE THREAD

**Issue by r4g-d0ll** [signalapp/Signal-Android#11001]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

if you send multiple sound files directly after each other, they all get played automatically directly after the previous one ends. 
the problem here is that the last few milliseconds of each file get cut off by some kind of system sound played by the app. 

this might not be a problem with voice recordings that often do not have sound in the last seconds, but if you would send sounds that are only a second or less long, the sound files get cut off almost entirely.

### Steps to reproduce

send multiple sound files of short length.

**Actual result:** sound files are automatically played but not entirely, the last few milliseconds are cut off.
**Expected result:** sound files are played automatically and entirely, before the next one starts to play.

**Comment by ptalmeida** [comment]
I can confirm this.
