### ISSUE TITLE
Editing mode shown after sending an image and retrieving Signal from the apps running in the background

### ISSUE THREAD

**Issue by marcelglueck** [signalapp/Signal-Android#11007]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
After sharing an image from the Gallery, leaving Signal, and opening the instance running in the background, the editing mode is shown again.

This issue might be related to this bug report: https://github.com/signalapp/Signal-Android/issues/9181

### Steps to reproduce

- Share an image from the gallery
- After having sent the image, leave Signal (go back to the phone’s home screen by touching the "home button")
- Open Signal from the selection of apps running in the background

**Actual result:** The draft mode is shown again, where one can choose a caption, rotate the image, etc.
**Expected result:** The chat shown before leaving the app should be displayed.

### Device info

**Device:** Samsung SM-G950F
**Android version:** 9
**Signal version:** 5.3.12

**Comment by cody-signal** [comment]
Can you provide a debug log as per the template request? It's helpful, especially when we are unable to reproduce your issue with our devices (tried on S7 Android 9, Pixel 3a Android 10, and Pixel 4a 5G Android 11).

**Comment by Nisc3d** [comment]
I have a debug log: https://debuglogs.org/a02cdfd7848dc01f910e8dca6da11468b542b3eefc5d95c05cb3f48a00edd004
Asus Zenfone 6, Android 11.
Steps to reproduce everytime for me: 
-Signal is not open in the background
-share image from gallery to signal
-image is sent in the chat
-press android back button
-I am now in the gallery
-use the android app switchter to switch back to signal
-Now I am back in the editing mode

I can also privatly give you a video or more debug logs if you want.

**Comment by marcelglueck** [comment]
> 
> 
> I have a debug log: https://debuglogs.org/a02cdfd7848dc01f910e8dca6da11468b542b3eefc5d95c05cb3f48a00edd004
> Asus Zenfone 6, Android 11.
> Steps to reproduce everytime for me:
> -Signal is not open in the background
> -share image from gallery to signal
> -image is sent in the chat
> -press android back button
> -I am now in the gallery
> -use the android app switchter to switch back to signal
> -Now I am back in the editing mode
> 
> I can also privatly give you a video or more debug logs if you want.

Exactly. Thank you for the clarification. Here my debug log: https://debuglogs.org/150118347cc1a228f470b5695b7444376aa7876e48b8fad945476c33e0220ed6

**Comment by fumiakiy** [comment]
One way to easily reproduce the similar symptom is to turn on `Don't keep activities` in the developer options in the Android settings. After turning it on it always goes through `onCreate` in `ConversationActivity` after `MediaSendActivity` is dismissed, so it always reopen the `MediaSendActivity`.

That said I am not sure if this is what is normally happening in the folks' phones.

**Comment by Tomptez** [comment]
Hello, for me this happens all the time and I never touch the back Button. Using Galaxy S9 Android 10 Signal 5.4.7.

**Steps to reproduce:**
Irrelevant if Signal is open in the background
Open image in gallery
Share
Select Signal
Select user in Signal
I am not in editing view of the image
Press send
The image is sent but I am immediately back in the editing view of the image

This goes on indefinitely and every time I click on send the image is sent and I am back in the same view. Back button doesn't even exit this view. I need to hit back multiple (3 or more) times to exit this view.

https://debuglogs.org/5c69987211dd1ed162444a83c940f8a9a9bd4e15ee6f3bf645c17d93ff8513cf

**Comment by sweah** [comment]
> **Steps to reproduce:**
> Irrelevant if Signal is open in the background
> Open image in gallery
> Share
> Select Signal
> Select user in Signal
> I am now in editing view of the image
> Press send
> The image is sent but I am immediately back in the editing view of the image

The same is happening for me, but not always and I am only thrown back to edit view once. If I hit the send button again, I am back in the normal chat view...the picture is sent twice then. If I don't hit the send button, but the back button, I am back in chat view and the picture is only sent once. Here is a debug log...I hit the button twice and the picture was sent 2 times:
 https://debuglogs.org/8aee447d5f8e458c92673f38385b4b18274064bbcf6c31ec7dd668abcf55065e

**Comment by Tomptez** [comment]
For me this has been resolved. I am using Signal 5.5.5
