### ISSUE TITLE
Video call doesn't rotate to landscape in TV when screen is mirrored to it but rotates on device. 

### ISSUE THREAD

**Issue by rawlife56** [signalapp/Signal-Android#11018]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
First of all thanks for implementing video call screen rotation which was the only reason I was using Duo for calls until now as I mirror cast my screen to TV and place the phone away from me while on video call.
Signal used to just fill small portion of the TV when mirrored as it didn't support landscape video calls until today. 

### Bug description
As the landscape video call support went live, everything worked perfectly on both the ends. The video call rotated perfectly on both devices but when I mirrored my screen to TV, the screen on TV is just stuck in portrait mode filling only part of the TV with a rotated video feed of the caller just in call screen. (Rest of the app mirrors perfectly in landscape) 

### Steps to reproduce
-Make an individual call on Signal
-Both the users are in portrait mode
-I screen mirror cast my phone to TV
-The video feed of the caller appear in only small portion of the TV obviously because both of us are in portrait mode.
-Now, both of us rotate to landscape mode
-Phone screens show the right orientation of the video feed in landscape mode. The TV is also expected to fill the entire screen.
-But the screen mirror on TV wouldn't rotate and gets stuck in earlier portrait cut out with rotated image of the caller. 

**Actual result:** When screen mirrored to my TV during video call, the picture on TV doesn't rotate along with the device. 
**Expected result:** The picture on TV should rotate and fill the entire screen of the TV during video call.

**Key takeaways:** 
-The entire signal app works well in landscape mode filling the TV screen when mirrored except calls UI. 
-I assume signal is just rotating the video feed in call but not letting the phone know it's actually rotated during landscape call. 
-I think it's an easy fix as I guess it's just missing to send an intent to phone asking it to switch into landscape mode in calls considering the rest of the UI works well when mirrored in landscape except calls.

### Device info

**Device:** Should affect almost every android device. Using Android TV for mirroring if that's important.
**Android version:** 9.0, 10.0
**Signal version:** 5.4.7

**Comment by Kwasow** [comment]
May be connected to #10975. Seems that Signal is not rotating the screen, but only the content of the app.

**Comment by rawlife56** [comment]
> May be connected to #10975. Seems that Signal is not rotating the screen, but only the content of the app.

Yeah looks like it. I'm assuming it should be easy to fix now as everybody is on stable and have a ability to rotate.They should just let the OS know to rotate the screen. Hopefully it'll be prioritized.
