### ISSUE TITLE
Pictures sometimes render incorrectly

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#11015]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes a sent picture preview won't render correctly. At first it is black with just a strip of the picture on one side and later the black part turns into a blurred preview (screenshot attached). The picture looks fine if opened in fullscreen preview.

### Steps to reproduce
- Send a picture
- Sometimes the preview won't render correctly

**Actual result:** The preview appears mostly black/blurred
**Expected result:** I should be able to see the preview correctly.

### Screenshots
![IMG_20210222_175708.jpg](https://user-images.githubusercontent.com/10947344/108742129-b11c3900-7537-11eb-8d46-b31159f71993.jpg)

### Device info
**Device:** Xiaomi Redmi Note 9 Pro
**Android version:** 10.0
**Signal version:** 5.4.7

### Link to debug log
The picture in question was sent at 16:23 (device time).
https://debuglogs.org/592b7622f8d9800904a386381ef950e359789325b75d7fc162316fee68afadec

**Comment by Kwasow** [comment]
May be related to #11040

**Comment by Nisc3d** [comment]
Most likely a duplicate of #9082.

**Comment by Kwasow** [comment]
Seems to be a bit different, because the picture is positioned incorrectly and it happens after cropping it in app. The issue I'm describing happens with both with edited and unedited pictures. They are also placed correctly but covered with the black/blurred overlay.

Although agreed - these issues may have something in common.

**Comment by hiqua** [comment]
How reliably can you reproduce this bug? Meaning, if you get the picture again (maybe changed a tiny bit), do you encounter this bug again?

In https://github.com/bumptech/glide/releases/tag/v4.12.0 (the library mentioned there: https://github.com/signalapp/Signal-Android/issues/9082#issuecomment-552039006) they mention:

> Fix a bug where we could decode partial images for large PNG files where obtaining the metadata caused us to skip past the limit of our buffer (https://github.com/bumptech/glide/commit/2b61482baa90175e0efdf4ec90f06a5051e1b370)

so I'm wondering if that could be this bug. I guess we'll be able to tell once the library has been upgraded in Signal.

**Comment by Kwasow** [comment]
Unfortunately I'm unable to reproduce the issue reliably. I've sent over 100 pictures now and didn't encounter the issue. It doesn't even happen again with the same picture. Over the past month it has happened to me around 4-5 times at random with pictures from different sources (ex. screenshot or camera) while a friend of mine has also mentioned it once (on the stable builds).

The issue described in glide might be the one we are seeing here, but as you said we'll have to wait and see after they upgrade.

**Comment by fatpat** [comment]
try https://github.com/signalapp/Signal-Android/pull/11016

on my P30 pro I had similar issues, since I added this patch, the problem is also gone. Not sure how it's related.

**Comment by Tursko** [comment]
This looks like the glide but from #9082

**Comment by Kwasow** [comment]
Closing as duplicate of #9082
