### ISSUE TITLE
Emoji reaction not synced from Android to Desktop

### ISSUE THREAD

**Issue by gensitu** [signalapp/Signal-Android#11027]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji reactions submitted on the Android app does not appear in the desktop client, but when the emoji reaction was entered from the desktop client, it shows in the Android app.

### Steps to reproduce
- Open both Android app and desktop client.
- Send a message in note to self on the Android app. Desktop client shows the message that was sent.
- Add an emoji reaction to the message on the Android app.

**Actual result:** No emoji reaction shown next to the message in the desktop client.
**Expected result:** Emoji reaction shown next to the message in the desktop client.

### Screenshots
![deskt](https://user-images.githubusercontent.com/33381267/109117563-1d3bae80-777d-11eb-8472-9bd7ef4af37a.png)
![and](https://user-images.githubusercontent.com/33381267/109118298-1b261f80-777e-11eb-9b03-88304b0f71f7.jpeg)

### Device info

**Device:** Samsung Galaxy A70
**Android version:** 10
**Signal version:** 5.4.7

### Link to debug log
Desktop: https://debuglogs.org/b4c76ce5696274a4df15fed892b767c027ac521e52a7af580d43e9a3cbf3253a
Android: https://debuglogs.org/8517e1e77021c4a0d221f747fa216af6c0cb4ba44fdb49e13f4e41b27877bf97

**Comment by AsamK** [comment]
I've made a PR to fix this here: https://github.com/signalapp/Signal-Android/pull/11008
