### ISSUE TITLE
BiometricAuthentication sometimes appears twice

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#11028]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The biometric authentication will sometimes (~50%) appear once again after successfully authenticating. It doesn't disappear when the fingerprint is touched again - you can get rid of it by clicking somewhere else on the screen or pressing the back button.

### Steps to reproduce
- Set up app lock in settings
- Exit Signal
- Lock from notification
- Open Signal
- Unlock with fingerprint

**Actual result:** The prompt will disappear when authenticated and then appear again.
**Expected result:** The prompt appears only once.
### Screenshots
![SignalBug](https://user-images.githubusercontent.com/10947344/109127357-9ec81800-774e-11eb-85b4-501b6a65d62a.gif)

### Device info
**Device:** Redmi Note 9 Pro
**Android version:** 10.0
**Signal version:** 5.4.8

### Link to debug log
https://debuglogs.org/46bf78d652e3e1d925278902bae0e125013c370bc37323295fe53a1357713a8b

**Comment by Leptopoda** [comment]
just for compleatnes this is caused by the recently introduced 
https://github.com/signalapp/Signal-Android/commit/3c4252a933a800f5f6dd8ec61bda4ec113350903
and also reported in the forum here
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-4-release/27904/271?u=leptopoda

**Comment by vachan-maker** [comment]
I am also facing this exact issue with the latest beta version on Android 10.

**Comment by Kwasow** [comment]
Fixed in e0d9c3f149e485c8387ff97899901e1206993d17
