### ISSUE TITLE
Message read receipts not synced to phone notifications

### ISSUE THREAD

**Issue by tobiscode** [signalapp/Signal-Android#11021]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When reading a message on Signal Desktop, the "marked as read" information does not sync to the phone. Even though the desktop app log seems to be sending the read receipt, the notification on the phone for that message does not disappear, even after a long time. This only started happening in the last couple of months.

### Steps to reproduce
- Have Signal Desktop linked to the phone
- Receive a message (notification appears on the phone and desktop)
- Read the message on the desktop app

**Actual result:** The message is marked as read in the desktop app, but the notification remains on the phone. If I open the phone app, it does correctly show the message as read.
**Expected result:** If I read the message on the desktop, the phone notification should disappear.

### Device info: Phone
**Device:** Google Pixel 2 XL
**Android version:** 11
**Signal version:** 5.4.7

### Link to debug log
https://debuglogs.org/faa3ed2352313bdb9ba94ef9391fcedb49086e3c15df00bd87442f3b5169c039

### Device info: Desktop
**OS:** Windows 10 20H2 19042.804
**Signal version:** 1.40.1

### Link to debug log
https://debuglogs.org/457c56f5378e8798e2cb8a52b83793eaa6eea23bf2b4abc1b23e52641a1e65e6

**Comment by haffenloher** [comment]
I only observe this for message reactions, not for actual messages. I.e., to mark an incoming message reaction as "read" from the desktop, I have to send another message or message reaction in the same chat.

**Comment by tobiscode** [comment]
This is specifically about the message itself, and not the reaction. There is already an issue about the reactions: https://github.com/signalapp/Signal-Desktop/issues/4696 but this is actually just not implemented yet, so not a bug.

**Comment by tobiscode** [comment]
With one of the last updates it seems to work again. Closing this for now and will reopen if it starts to happen again.
