### ISSUE TITLE
"Invite friends by message" does not allow to choose phone numbers.

### ISSUE THREAD

**Issue by vonorlow** [signalapp/Signal-Android#11025]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the "Invite friends by message" feature, one cannot pick which phone number is used, leading to landline numbers, fax etc. being used.

### Steps to reproduce
- open invite friends by message
- select address book contact with landline and mobile number in address book
- message is sent to landline or fax number

**Actual result:** Can only send invite message to landline or fax number
**Expected result:** Being able to select an appropriate number from my contacts, or landline numbers being auto-ignored

### Device info

**Device:** iPhone 8 Plus

**Comment by miningape** [comment]
Repost here if you haven't already since the bug was initially found on iOS https://github.com/signalapp/Signal-iOS

**Comment by nereocystis** [comment]
Yes, this is still a problem
Let's re open bug

**Comment by alex-signal** [comment]
This is an iOS issue, not an Android issue.

**Comment by vonorlow** [comment]
> This is an iOS issue, not an Android issue.

Seems to occur on both OSes

**Comment by alex-signal** [comment]
The device posted in the issue description is an iPhone 8, is this inaccurate? The Android invite friends screen does not use the system level contacts screen, it uses our own, and each row of it displays which type of number you're choosing (Mobile, Home, etc).

**Comment by nereocystis** [comment]
For me, the problem showed up on an iPhone 6S Plus

**Comment by nereocystis** [comment]
For the 6S Plus, software version 15.5, signal 5.41.0.12

**Comment by nereocystis** [comment]
On my Android, the signal app does ask for permission to access Contacts. @alex-signal 
I have denied permission to Signal, but Signal does ask

**Comment by nereocystis** [comment]
My apologies. I added my experience to an already existing bug, and didn't notice that it was for *android* app
