### ISSUE TITLE
App crashes with version 5.4.7

### ISSUE THREAD

**Issue by ialokim** [signalapp/Signal-Android#11030]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Fails to open database when opening a chat after update to version 5.4.7

### Steps to reproduce
- update Signal to 5.4.7 (Google-Play-free version from website)
- open app after update
- see list of chats as usual
- open some chat
- app crashes

**Actual result:** App crashes
**Expected result:** App should not crash

### Device info
**Device:** Wileyfox Swift
**Android version:** 10.0
**Signal version:** 5.4.7

### Link to debug log
https://debuglogs.org/5d7bf6dfac8fd381cae0f7095a409a4d42ca2009fa65291e67fd99c158e5c7a1

**Comment by alan-signal** [comment]
Why do you think this is related to a database migration?

**Comment by ialokim** [comment]
I just had a glimpse into the debug log, but I think I misinterpreted the "update" calls. So, most probably indeed not related to database migration. After all, the chat list with all contacts loads as usual.

**Comment by alan-signal** [comment]
Yes, that's what I see, SQL `update` calls failing when trying to mark some messages as read.
