### ISSUE TITLE
Signal crash while making or receiving a call on v5.4.7 and later

### ISSUE THREAD

**Issue by sjys** [signalapp/Signal-Android#11041]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After I updated signal to 5.4.7 and later I can't make or receive a call. When I press call button signal can't do any actions and report problem dialogue appears.

### Steps to reproduce
- open the chat or profile directly
- press the call button
- signal hangs

**Actual result:** Signal hangs and report problem dialogue appears
**Expected result:** It should make a call

### Device info

**Device:** Samsung Galaxy J1 mini (SM-J105F)
**Android version:** 5.1.1
**Signal version:** 5.4.10

### Link to debug log
https://debuglogs.org/72f6834ef4c01f018df6aaf986e3efe4542e39e52682d2dbd1a6c125e3d42cc9

**Comment by SDS1337** [comment]
I too have been having this issue. If I get a call, Signal stops ("Signal has stopped"  Android prompt).
