### ISSUE TITLE
I have Android. Was talking to someone on an iPhone with Signal 2 days ago. I got their messages instantly, mine were delayed 10 mins to several hours. 

### ISSUE THREAD

**Issue by Sedryn** [signalapp/Signal-Android#11048]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Genis-Sage** [comment]
Hey @Sedryn
Without filling out anything of the template, it is hard to say anything
Just the title is too general for signal devs to find anything

If you see, that your message reaches the server (one checkmark), then most probably, it's an issue on iOS side, and your friend should go the the iOS issue tracker 


If your messages do not got to the server immediately, then at least a debug log of your side is needed
