### ISSUE TITLE
Skin tone when grouping emojis 

### ISSUE THREAD

**Issue by real-or-random** [signalapp/Signal-Android#11046]
> - Skin tone variations of the same 'base emoji' will be grouped together in the badge.
> - When picking which variation to show in the reaction bubble, we will always prefer the variation you selected if you are participating in the reaction, and show the most recent if not.

_Originally posted by @greyson-signal in https://github.com/signalapp/Signal-Android/issues/9776#issuecomment-662440375_

I don't think the choice described in the second bullet point is optimal or natural. It's confusing, unexpected and can lead to strange situations. Moreover, it emphasizes the order in which emojis arrive  which is counterintuitive when grouping (because the entire point of grouping is to abstract away from the information about the individual emojis.) 

I just encountered this in a group where 7 people used tone A "thumbsup" emoji and then one person used tone B and then the badge changed to B. This was surprising and unexpected, in particular if B is is not the neutral tone. Some people in the group who commented on this considered this a bug. 

Moreover, the badge shown was inconsistent between the participants because of the rule that it depends on your own choice. I think strictly speaking, one could even make the point that this is a unnecessary violation of a security property load because different users will disagreements over what the state is. (Sure, we live in an   asynchronous world, so we can't reach this property... But here all messages have arrived, so we don't need to violate agreement.)

I suggest that grouping for the badge either
 * always uses the neutral/yellow tone (That is less surprising because the tone will never change but it's still surprising when there's only a single tone different from the neutral one), or
 * uses the unique tone if there's one and uses the neutral tone when there's one than one tone present in the set. (That still means the tone can change but it changes at most once.)

I'd prefer the second option.

**Comment by Genis-Sage** [comment]
Hey @real-or-random
github is the wrong place for discussions, as signal devs reserved it for bugs

As you cited it already, the current behaviour is intended by signal devs, so it's not a bug

For discussions, you should use community.signalusers.org
