### ISSUE TITLE
Signal changes contact custom names to 'Other'

### ISSUE THREAD

**Issue by jdsys271** [signalapp/Signal-Android#11045]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If say you have a local contact, lets call it CompanyA, and under that specific contact you have obviously created multiple 'custom' names with their numbers called: John, Susan, etc.  As soon as you download Signal and allow contact permissions on Signal and refresh, and you go back to your local contact to view it, you will see it changed your local contact custom name Susan to 'Other'  (since Susan is the only name that has Signal, it was the only one affected) John doesnt have Signal, so it stayed with its Custom name i set initially.

Why does Signal change the custom names of my Local Contacts?

To revert back from this mess, i had to go to Android Account Settings, and remove the Signal Account from Sync completely. Only then will i get the name Susan back in my contacts from where Signal changed it to 'Other'

I searched quite a bit and have not seemed to find this bug on here. Im very surprised this has not been seen by anyone and its very annoying as well.

### Steps to reproduce
Option A
- To view the issue, you need at least one contact that has Signal and one contact that doesnt.
- Use an Android phone without Signal and create a contact called CompanyA, with custom names and numbers of John(who doesnt have Signal) and Susan(who has Signal).
- Download Signal and register, allow contact permissions and refresh list in Signal.
- Go back to your local contacts and find CompanyA
- See that Susan custom name has disappeared and been replaced with 'Other'

Option B
- Instead of downloading and re-registering, you can also reproduce by going to Android Account Settings, and remove the Signal Account from Sync completely.
- Deny contacts permission on Signal.
- Go to your local contacts and create a contact called CompanyA, with custom names and numbers of John(who doesnt have Signal) and Susan(who has Signal).
- re-Allow Signal permissions to your contacts, Go to Signal app and refresh your Signal contacts.
- Go back to your local contacts and find CompanyA
- See that Susan custom name has disappeared and been replaced with 'Other'

**Actual result:** Susan custom name has disappeared and been replaced with 'Other'
**Expected result:** Signal should **not** have changed my local contact custom names to 'Other', instead its obviously just supposed to **read** from my local custom contacts.

### Device info

**Device:** Tested on Oneplus, Xiaomi with custom roms.
**Android version:** Tested on v9 & v10.
**Signal version:** 5.3.12

**Comment by hiqua** [comment]
What do you mean by custom names? Just the first name? Or which field is changed exactly? Any chance you could export the .vcf of the contacts (without the numbers if you prefer) or share a screenshot of what the contact looks like?

Can you add a debug log (even when that seems easy to reproduce, just in case)?
