### ISSUE TITLE
Signal crashing when saving large amounts of media files

### ISSUE THREAD

**Issue by AlertSubject** [signalapp/Signal-Android#11042]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When opening the "shared media" section of a Chat and saving a large amount of them and once signal will crash at a random time. 
The amount of pictures and videos saved before the crash seems to be random. 
Mostly just happens when saving more than 100 ish media files at once 
Only workaround is manually selecting all the files and saving them that way. 
Only trying to save all images seems to crash the app

### Steps to reproduce
- open the "shared media" section of a chat 

(note that chats with more media files are a much more reliable way to crash the app. Around 130 seems to be the cut-off) 

- tap and hold one image 
- click select all in the right corner 
- click save all

**Actual result:** 
Signal crashed after a few seconds without having saved all the pictures 
It will save a seemingly random amount of media files before that though 
Numbers vary on each different attempt

**Expected result:** 
All selected media files should have been saved to the phones storage 

### Device info

**Device:** Oneplus 6
**Android version:** 10
**Signal version:** 5.4.10

### Link to debug log
https://debuglogs.org/6319275b3ea27ee0f57a0e126ea1b5bdbac0defdff297824488bca9b0452aa78

**Comment by n-gao** [comment]
This issue also happening on my Pixel 6, is there any update on this?

**Comment by AlertSubject** [comment]
> This issue also happening on my Pixel 6, is there any update on this?

I'm afraid not

Has been like this ever since I started using the app in 2019
Recently they changed the filenames when saving media files. So maybe they'll touch on this issue eventually

Have you figured out how to reproduce this crash consistently?
For me it always crashed at different points in time. Even when saving the same media files

**Comment by davidMichaelLevy** [comment]
The bug is still there.  I've attached another debug log.  I think the bug might be related to saving images which were received via SMS messages, not encrypted Signal messages.  For some reason those files are named things like imagejpeg_0.jpeg or 123_1.jpeg, and often all of the pictures in a conversation will have the same name.  This causes a lot of naming collisions on the file-system that are resolved by incrementing a suffix.  But I wonder if there isn't a concurrency bug in that logic.

Just speculation.  Hopefully the log will be more helpfu
[3f20f8d9d91557a64ee2d2d17ec5fd700d349314384c9c510f126d2bf0b05974.gz](https://github.com/signalapp/Signal-Android/files/7990259/3f20f8d9d91557a64ee2d2d17ec5fd700d349314384c9c510f126d2bf0b05974.gz)
l.

https://debuglogs.org/3f20f8d9d91557a64ee2d2d17ec5fd700d349314384c9c510f126d2bf0b05974

**Comment by Himeko7** [comment]
> The bug is still there. I've attached another debug log. I think the bug might be related to saving images which were received via SMS messages, not encrypted Signal messages. For some reason those files are named things like imagejpeg_0.jpeg or 

I don't think that's related, none of my images are from SMS

**Comment by AlertSubject** [comment]
The problem also occurs woru media files from group chats. Those can't be SMS related. And in general I don't use SMS and still face the issue

And I believe one of the latest updates changed it so that all file names will receive a unique name when downloading them to your phones storage

**Comment by Himeko7** [comment]
This is still not fixed.

**Comment by greyson-signal** [comment]
@Himeko7 Can you provide a log taken after you experience the crash?

**Comment by Himeko7** [comment]
> 

I provided logs in issue #11670

**Comment by AlertSubject** [comment]
Personally, the issue has been resolved for me
A few betas ago the issue disappeared and saving works mostly fine almost aways ™

But seems like this ain't the case for all users

**Comment by greyson-signal** [comment]
@Himeko7 Yes, but we've made attempted fixes since you've posted your last log. So if it's still happening, an updated log from a recent version would be a big help. Thanks!

**Comment by Himeko7** [comment]
It seems to be working fine now, thanks.
