### ISSUE TITLE
Signal fails to open conversation list or send and receive messages

### ISSUE THREAD

**Issue by nrizzio** [signalapp/Signal-Android#11044]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open Signal, the conversation list fails to load. I see a blank screen, with only the word "Signal" at the top, an empty circle where my profile picture should be, and the three dots that open the "more" menu. When I tap on the settings button, either nothing happens, or a new page opens that is completely blank, and I am unable to go back.

When the app is in this broken state, I cannot send or receive messages. I have to repeatedly force quit the app multiple times until the app works like normal again. Many times, I see the "checking for new messages" notification that doesn't go away, as referenced in issue #11043.

### Steps to reproduce
- Open the app as normal
- Observe that no conversations are visible

**Actual result:** The list of conversations fails to load. No conversations are visible or selectable. No messages can be sent or received.
**Expected result:** Signal works normally as expected.

### Screenshots

I was unable to gather screenshots but I have disabled screen security and will send one as soon as the issue returns.

### Device info

**Device:** Motorola moto g(7)
**Android version:** 10 (Build QPUS30.52-23-13-3)
**Signal version:** 5.4.10 (issue was present with version 5.4.9 and possible earlier versions too)

### Link to debug log

https://debuglogs.org/89f80e0e4ae98001a71d0f13518bd8f3b246230662425fb5eeed954cf2032b04

**Comment by stoppablemurph** [comment]
Seeing the same issue on my end I think.
![Here's a screenshot of what it looks like for me](https://user-images.githubusercontent.com/5564311/109400380-4daa5680-78fd-11eb-9bf6-85262921b0aa.png). I've tried force stopping the app and clearing the cache with no luck. I can still use signal from my laptop, but I'm not even getting notifications or anything on my phone now.

Using a Pixel 5 with whatever the latest stable android version is for this device. Google Play Store says Signal updated earlier today and is on 5.4.10.

**Comment by Masqueey** [comment]
Force stopping the app seemed to work for me. (Going to app info and stopping it there.) Saved me a reboot.

**Comment by dusscloud** [comment]
I had the same issue twice (yesterday, today).
I use Signal app 5.4.10 on a Motorola moto g(6) with Android 9. [Debug log](https://debuglogs.org/c35d7de7d82f58e4fb96dd9e7e2db35c5023a28ff9ac130bb691c10471a93512)
I am not 100% sure but it seemed to be back after I used Signal on a desktop.

**Comment by nrizzio** [comment]
I have not observed this behavior since 1b9efeb049ef34701cb7888dd042e63caea67f6d, but I'm not sure if that's just pure chance or if that commit fixed the issue.

**Comment by nrizzio** [comment]
Still haven't observed this behavior again. Closing as fixed by 1b9efeb049ef34701cb7888dd042e63caea67f6d but will re-open if bug reappears.
