### ISSUE TITLE
When replying from notification, new messages minimize keyboard 

### ISSUE THREAD

**Issue by summersab** [signalapp/Signal-Android#11052]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When responding to a message from the notification bar, the keyboard is minimized/hidden if a new message is received. This often results in accidentally tapping other notifications present in the notification bar.

Some users (like myself) often wish to keep notifications from other apps as unread until they can address them at a more convenient time. The behavior of Signal to minimize the keyboard once new messages are received often causes users to accidentally tap and open these notifications.

### Steps to reproduce
- Receive new message
- Begin replying to the message via the notification bar
- Receive new message
- Keyboard will be minimized

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The keyboard is minimized/hidden if a new message is received when responding to a message from the notification bar.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The keyboard should stay open when responding to a message from the notification bar even if a new message is received. This behavio(u)r doesn't impact other messaging apps from what I recall.

### Device info

**Device:** LG Nexus 5X (bullhead)
**Android version:** 10 (LineageOS 17)
**Signal version:** 5.4.7

**Comment by summersab** [comment]
This is still a bug even in the most recent versions. I don't know what else to provide.

**Comment by alex-signal** [comment]
Have you seen this work properly with other apps? The only thing I  can think of is that the notification is being destoryed / re-created when a new message comes in. Otherwise, this keyboard behaviour would be the fault of the system.
