### ISSUE TITLE
No audio heard by callee on the first call (regression in 5.3.12)

### ISSUE THREAD

**Issue by mr-brunes** [signalapp/Signal-Android#11051]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Third party callee cannot hear my audio on the first call. This behaviour is a regression only experienced on updating to Android app v 5.3.12.

### Steps to reproduce
- Ensure both caller and callee handset have power saving feature on apps and phone disabled
- Both caller and callee are connected to wifi

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Caller calls callee and callee answers. Callee hears no audio.
- Caller hangs up and calls back.
- Callee answers hears audio normally.
- 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
On Signal app before v5.3.12 audio would work fine, though calls were often subject to the "Missed call" issue that was fixed in 5.3.12.
### Device info

**Device:** Caller Samsung S10e, Callee Samsung S7
**Android version:** Caller - stock Android 11. Callee - stock Android 8.0
**Signal version:** 5.3.12 and 5.4.7

### Link to debug log

Caller https://debuglogs.org/fcfccada1f6c6145010119c8977d6e07fa73abcc25a26d7605279c51beeb8df3
Callee https://debuglogs.org/06f0991a6e887b5b5c332ca12c0527296277c8239ba1db9e583d4c3840a3c2d4

and after another silent call (caller end only).
https://debuglogs.org/6eefda98d0501b5f665ca4bb49faddf7ea823f33e4ec229c2491d8096e5b06fe
Problem calls at 11:56, 11:57 (ok), 12:18, 12:19 (ok)

Some more debug logs (from my caller end):
https://debuglogs.org/9dcb3956078740db4c2587ec9de2a8099663037aa5f8066422707b0f6e312b4f
https://debuglogs.org/6ed0aff5e2e7b11723d3b813b51ff07156fa6b7d1ceb87096743b05ef918ffa3

**Comment by jonpaterson** [comment]
Same issue... Android 11 on pixel 5. Second call always works perfectly. Running 5.4.12

**Comment by mr-brunes** [comment]
This time the second call was silent too, it was the only the third one that was audible. Both parties using v5.5.5.
27-Mar-21 11:43, 11:44 silent, 11:44 OK.

Debug log from the callee:
https://debuglogs.org/72e0e64f65c62869646caef064298d6889d4f2ec5b2e54064eff578f910bff61

Caller:
https://debuglogs.org/87631cc0c6047a23a9a60994b83132457a68d84ab74ace3b53959339aa97c5b8

**Comment by mr-brunes** [comment]
Callee could not hear me again (@12:03 06-Mar-21) - this time I was using 5.6.3 beta. Second call a few seconds later was fine.

Caller log:
https://debuglogs.org/9c3966ceb0b210d0ae2518317b29e595fa8bc151175f808582343b0b8f5ec8d7

**Comment by cody-signal** [comment]
Thanks for the updated logs, looking into it with our calling team.

**Comment by mr-brunes** [comment]
No audio on first call issue happened again - second call straight afterwards was fine.
Log from callee on 5.5.5 on Android 8.

https://debuglogs.org/480f5314df6278843003d2b28133d27ebfeab2f86d569a931750225b053b37fc

**Comment by mr-brunes** [comment]
Android bugreport from the callee's S7 also sent to greyson as per https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

**Comment by jed84** [comment]
This is starting to be even worst.
Currently I have to make calls up to three times so the callee can finally hear me.

Note 20 Ultra, Android 11.

**Comment by mr-brunes** [comment]
Still happening.
Caller on 5.8.9
Callee on 5.7.6, and their log https://debuglogs.org/dac77dd4d974508ed83256b0451643fb4c0a9dd2e383a17c804b2d31fc0fbdef

**Comment by jed84** [comment]
I believe this might have something to do with the smart cover (I am using the official Samsung LED smart cover for Note 20 Ultra) and the screen being turned off before the receiver answers the call.

Steps to reproduce:
1. Make sure you make a call via any phone with a smart cover
2. Try to call any Signal contact 
3. Before the receiver answers the call, close the smart cover so the screen turns off
4. The receiver answers the call and is not able to hear the caller

Would be great if other people who experience the issue could confirm using any type of smart cover.
Perhaps the smart cover is even not needed and its enough to just turn off the screen before the receiver answers the call?

**Comment by mr-brunes** [comment]
FWIW I don't have a smart cover, the only thing that might be relevant is that I nearly always use a BT earpiece, though as mentioned before it has never caused an issue when making calls via other methods. The main trouble is that it is anintermittent issue.

I just spotted the edit above from cody-signal about the caller's device not being completely "ready" - yes this sounds plausible as it seems similar things have affected Signal before (the missed call issue now seemingly fixed, and where a pre-call msg seemed to get everything in order).

**Comment by AlvaroBro** [comment]
Hi! Is it possible that some other app is somehow interfering with the audio input/output? I'm asking this because I just found out that this was happening to me with a call recorder app. When the phone with the call recorder app received an incoming call, the caller could not hear the callee. Uninstalling the app solved it. I must say I am using not the vanilla Signal app, but a mod of mine forked from the Signal app version 4.56.4.
The call recorder app: https://play.google.com/store/apps/details?id=com.appstar.callrecorder&hl=en_US&gl=US

**Comment by mr-brunes** [comment]
Still seeing this with 5.12.2 beta caller, callee 5.11.5.

**Comment by jed84** [comment]
After a month of testing, I can say that for me the issue is related to Samsung Smart Cover.
The issue no longer occurs IF I close the smart cover AFTER the call is initiated.

Still, would be nice if devs could address the problem.

**Comment by mr-brunes** [comment]
Still happening for me with 5.24.0, other party on current release.

**Comment by mr-brunes** [comment]
Still occurring on the first call of the morning of 23-Dec-21. Debug logs FWIW:

Caller:
https://debuglogs.org/9482dd9211a5eddb19a949c83bbae439071d3a7264afef7a3586ca2fccfd350e

Callee:
https://debuglogs.org/e005f8cd873233391cc1883c8d309f53584551341fbcc769c7e1e94f5998c83f

Given this ongoing issue, I've moved to Whatsapp for voice calls as it doesn't have these problems and the audio quality is nearly as good as Signal. But I'm happy to test if someone actually diagnoses a root cause.

**Comment by mr-brunes** [comment]
I tried it again after supposedly some voice fixes have gone in to Signal. But of course it's still present. :-(

I'm on 5.30.3 on Android 12.
https://debuglogs.org/92dfef580355e5272053c46c1ef6e62ad59d8ccfd8cfab0c63ec3697106ca5b0

Callee is on 5.29.7 on Android 8.
https://debuglogs.org/675ba41ff809dd1e5898f79397f4844d09bd2678b5ed9b37603434bf301339e3

Call made at 12:20 on 29th Jan 2022.

Is no one actually looking at this? Losing faith in Signal TBH, updates with new fancy emojis don't make up for buggy basic functionality. Whatsapp works fine for calls between these phones.

**Comment by alex-signal** [comment]
Forwarding this to the calling team.

**Comment by loveisfoss** [comment]
Experiencing this issue also on poco F3 with LOS4microg 18.1 (A11).

Callee cannot hear me the first time and sometimes also the second time and I need to call again or ask them to call me.

**Comment by mr-brunes** [comment]
Still happening with latest beta, although it has not happened for quite a while so I'd hoped it had been fixed!

First call about 12:19, the audio was silent as heard by calleee. Second call, the audio was heard fine.

Caller
https://debuglogs.org/android/5.34.10/09855b66b02f539adc4e3b9a6130ef69a0aa689e36dfd94431d57fe4dc7625f7

Callee
https://debuglogs.org/android/5.34.10/ed3097e17b5da53ca113ff3286bb2cdfa0de08f832a466ca1d770f439f1d040a

**Comment by Anton-Latukha** [comment]
Serving as a military telecommunication manager/engineer during ongoing war, being responsible for quite a lot of lives of people.

And making a decision to use Signal for our formation.

It was embarrassing to find-out that on my new phone I can not talk with people, I need to recall and person needs to take a phone call 2-3 times to hear me.

It created a lot of unnecessary overhead and every call is a nervous situation. Also imagine emotional background of a person who needs to take call 3 times for me - let's say, responsible for telecommunications in the firmation - to be able to reach the person and say something.

**Comment by greyson-signal** [comment]
@mr-brunes Do you ever start a call on bluetooth and then immediately lock the screen (while the call is still ringing/connecting)? We've seen reports where that may make it more likely, wondering if that's what's happening here.

**Comment by mr-brunes** [comment]
@greyson-signal Half of that is right i.e. I do start the call with a BT headset connected but I never lock the screen afterwards.

**Comment by Anton-Latukha** [comment]
I personally do not have headset.

And I have audio problem seems like 100% of time.

**Comment by mr-brunes** [comment]
Different callee this time -same symptom - first call silent, second call straight after fine:
https://debuglogs.org/android/5.34.10/2ff66f71d68953c9ef127165699d414f5a081b80c7ca5e8902e2cb5ac7b3d0f4

Caller: 
https://debuglogs.org/android/5.35.2/93a412f1c6f7a952f299720f05a3ceee875d5213ec7fa0e219fb6d35b9b841ea

**Comment by Anton-Latukha** [comment]
Some of my subordinates also have the same problem. We all have different phones. My direct deputy with Meizu has this problem. So when we call each other - no one of us can reach another one on the first call.

Bug is also present even on iPhone of my other subordinate.

It seems pretty frequent, but underreported problem.

**Comment by point-source** [comment]
I am also experiencing this problem on a PIxel 6 Pro and I experienced it on my OnePlus 8 Pro before that and my Pixel 2 XL before that.

**Comment by Anton-Latukha** [comment]
@signal-app

As a Free Software proponent and active contributor for the last N (5-10) years, I've taken the risk to use Signal as the basis in department of Ukrainian army I am responsible for.

Since this thread and messages are unaddressed. Not even the problem, the messages are not addressed.

Currently I spend all my money on telecommunication equipment for the war and this month have no to donate.

Seems like project is dormant and my zone of responsibility in the army would be switched to WhatsApp .

And I would stop reasoning to managing the server and advocating for funding Signal in Ukrainian military.

Now I need to migrate everyone in the formation.

**Comment by mr-brunes** [comment]
> Looking at @mr-brunes latest logs it appears the networking is establish properly, and packets are flowing, but no audio is being recorded/sent.In the latest beta we've added speaking indicators. I'd be curious to know if when this happens you see your own indicator moving when the other person can't hear you.

@cody-signal Tx for the info. I've just checked on a normal call and the dots don't animate when I speak, only when the other party speaks. Is that expected behaviour?
Aside:  I can see the Release Notes channel but I've not seen anything posted since 12th Feb.

**Comment by mr-brunes** [comment]
Udate - just had the issue again and the callee found that the speaking indicator dots didn't animate at all when I was doing the "Can you hear me?" preamble.

**Comment by jed84** [comment]
The issue still occurs.

**Comment by jed84** [comment]
This is still a valid issue.

**Comment by shift18** [comment]
I'm experiencing this issue as well except that **it only happens** for me when I'm **using mobile data** (4G), not when I'm on WiFi.

When and how does it happen?
When I'm in town and need to make a call, it doesn't make a difference whether I'm outside or inside a building.
I place the call and the Callee can't hear me although i can hear the callee.
I redial and it usually works as normal although sometimes i need to redial a second time in order for the callee to hear me.

P.S. I'd just like to add that this happens every time i make a signal call with the callee, there is no deviation.


Details about Caller
Device: Pixel 6a (bluejay)
OS: GrapheneOS build 2024032100  - android version 14
I'm using a wireguard VPN (tried different servers/locations)
Network quality on 4G through vpn:
<img src="https://github.com/signalapp/Signal-Android/assets/37035227/a3a584fa-139f-46bd-82c1-53018b3584fa" alt="image" width="300" height="auto">

**Comment by nicholas-signal** [comment]
@shift18 Hello, would you mind creating a new GitHub issue using our template, including a debug log? That would be very helpful for debugging and coordination.
