### ISSUE TITLE
Signal slow to download images and stickers

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#11059]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal sometimes takes up to 5 minutes downloading images or stickers. The Desktop Version works without a Problem, and on another Android Phone it also works without a problem, so the Wifi connection should not be the Problem.

### Steps to reproduce
- download images or stickers in a chat
- wait too long

**Actual result:** Images and Stickers take too much time to download. On other devices it is much quicker.
**Expected result:** Images and Stickers take a normal time to download

### Device info
**Device:** Motorola Moto G Pro
**Android version:** 11
**Signal version:** 5.4.7

### Link to debug log
https://debuglogs.org/8b6fe758884ed18b2de2f459ed3791e6f9b728ef504aa45f07bde4ac5a08db04
Debug log taken after downloading 2 images.

**Comment by NotSoImportant** [comment]
could be related to https://github.com/signalapp/Signal-Android/issues/7208

**Comment by Nisc3d** [comment]
I think this might be something with specific german isps. If someone can confirm that they have the same Problem sometimes with Telekom or 1&1 this would be helpful.
Related to #11684

**Comment by Nisc3d** [comment]
It's maybe related to #11684 so I think it is relevant.

**Comment by cody-signal** [comment]
Could you get an updated log after this occurs?

**Comment by Nisc3d** [comment]
Yes, I will try. But this problem happens a bit less often, so it could take a bit.

**Comment by cody-signal** [comment]
Fair enough, tag me in the comment when it does.

**Comment by Nisc3d** [comment]
Sorry it took a bit longer @cody-signal https://debuglogs.org/android/5.40.4/88ed4974433b366ccee8324a12cf72a12068cf88a3ddb3ee21c0338994ca1816

May I also ask if you already changed the upload and download timeouts?
