### ISSUE TITLE
Push-Service for Custom ROMs without GCM

### ISSUE THREAD

**Issue by SecUpwN** [signalapp/Signal-Android#1106]
Dear @moxie0, as much as I enjoy using TextSecure as a complete replacement for the standard SMS app, I am not happy with the registration process for the Push-Service of TextSecure. To be specific, I am running [AOKP](http://www.aokp.co) and TextSecure tells me that registering with the Push-Service is not possible without having the Google PlayStore-App installed. To be very clear about this: Google Play will NEVER EVER gain permission to land on my phone. The way I see it, being required to install Google Play (in my eyes one of the most dangerous privacy-breaking apps out there) just to be able to use the Push-Service of TextSecure (which focuses on PRIVACY) is like a snake biting its own tail. I guess TextSecure utiltizes Google Cloud Messaging (GCM), and as such Google Play is "absolutely necessary", am I right?

Don't get me wrong: Using TextSecure feels awesome. It just does feel that way leaving WhatsApp behind and knowing that TextSecure is being recommended by [The Guardian Project](https://guardianproject.info/apps) and can be safely relied on to protect my data. But having to have Google Play just feels wrong. My intention is to DITCH Google completely (except for Android Custom ROMs) in the long run, not creating yet another tie for myself. So why don't we make an effort to find an alternative for this crappy Google Cloud Messaging?

**Comment by robertvanbregt** [comment]
Another GCM alternative would be Pushy.

https://pushy.me 

Which recently got implemented by Fastmail in their android app.

**Comment by psyvisions** [comment]
What about http://www.pushlets.com/ ? It's open source. 
The whitepaper: http://www.pushlets.com/doc/whitepaper-toc.html

**Comment by SafwatHalaby** [comment]
Does signal work at all without GCM? I don't mind a push-less experience.

**Comment by JavaJens** [comment]
Yes, when you open the app a direct connection to the server us established and messages downloaded.

However, you can't use the play store version I'm afraid as it will complain about missing play services.
So you might have to compile your own version.

**Comment by SafwatHalaby** [comment]
Did anyone fork it and strip the Play Services part?

**Comment by SecUpwN** [comment]
Signal without GCM? Check out [LibreSignal on F-Droid](https://eutopia.cz/experimental/fdroid/repo/) and read [this German article](http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging/)! Safe new year. ;-)

**Comment by SafwatHalaby** [comment]
@SecUpwN is this sms-only? I want Internet based signal without push.
ftr: an sms-only [fork](https://f-droid.org/repository/browse/?fdfilter=smssecure&fdid=org.smssecure.smssecure) of Textsecure is available.

**Comment by SecUpwN** [comment]
@SafwatHalaby, I am using `SMSSecure` since TextSecure removed encrypted SMS. `LibreSignal` is a fork of this repository, but without GCM spyware and using **WEBSOCKETS** instead. Enjoy! ;-)

I will likely make the full switch to `LibreSignal` soon, [here]( http://git.io/vEoFZ) you can see how I found out how to port SMS from `SMSSecure` to `LibreSignal`. Hope my mesage is a small christmas present for you.
