### ISSUE TITLE
Signal verification SMS/call can not be received in Iran.

### ISSUE THREAD

**Issue by VanGHub** [signalapp/Signal-Android#11062]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have received reports from inside Iran that users can not receive their activation codes via SMS or voice call. This is very likely a new move from the Iranian authorities in line with their previous efforts on blocking access to Signal within the country. They have probably blocked the number(s) from which Signal sends out activation codes to users?.
If so, this needs to be fixed otherwise no one in Iran will be able to join Signal or reinstall Signal on a new device/number. I am already aware of the Iranian government ban on Signal on ISP level, but that has so far been bypassed by Iranians using VPNs or proxies. While this new activation code delivery ban means users inside Iran have no way around it, something needs to be done by Signal urgently. An alternative solution might be sending out the activation codes to users' other devices with Signal installed on them, similar to what Telegram does. For example my friend has previously installed Signal on Windows and the activation code can be sent out to his Signal on Windows. Or Signal can possibly send out the activation codes from random numbers or using Sender ID, similar to what Google does.

**Comment by UserX404** [comment]
It's an already known issue and is discussed in the [forum](https://community.signalusers.org/t/signal-got-censored-in-iran-jan-25th/25677).
Feel free to participate.
