### ISSUE TITLE
Not Stopping sending SMS

### ISSUE THREAD

**Issue by wbkwbk** [signalapp/Signal-Android#11060]
### Bug description
I've sent an SMS using Signal. Now the recipient was Spammed with dozens of the same SMS. The recipient had to block my sender number. I've disabled the SMS Feature in Signal. But the SMS is STILL being sent out.
How can this be stopped? 

### Steps to reproduce
I do not want try to reproduce, as I cannot spam/annoy another colleague.

### Device info

**Device:** Noka 7.2.
**Android version:** 10.0
**Signal version:** 5.4.7.

**Comment by UserX404** [comment]
Where is your debug log?
Nobody can help you without your logs.

**Comment by wbkwbk** [comment]
Sorry about that:

https://debuglogs.org/ccb43dcf6988e2d0d776c8adfb6dcf1d293ee69aeffd4cb4d48dafbd35b2d956 

The issue is the following.

I've sent 1 SMS via Signal. The recipient is being spammed since 2 days now. He had to block my mobile nummer - so I cannot call him anymore from my mobile phone. Yesterday I've disabled the Signal SMS access. So basically in Signal I've disabled  phone access, SMS acces. Still this morning the SMS being sent out again. So it seems there is a sever Signal server issue that the SMS is being sent. Please disable continuing sending this one SMS.

Thank you

**Comment by wbkwbk** [comment]
It seemed that after deleting sending did not stop. This was two days ago. Since then I did not recheck with the recipient if it now finally stopped for good.

**Comment by UserX404** [comment]
I use it for years now and the only issues i was facing were problems with mms sending, which now works without problems.
Maybe a dev is able to find the root cause within your logs.

**Comment by wbkwbk** [comment]
ok, that would be great, thanks

**Comment by wbkwbk** [comment]
Hi Thank you
No: not relevant anymore. The issue fit not occur anymore

stale[bot] ***@***.***> schrieb am Mi., 26. Jan. 2022, 19:30:
