### ISSUE TITLE
You can Initiate Video/Audio Calls with Blocked Users From Manage Recipient Screen

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#11064]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is very similar to #10971 

You can Initiate calls with people you block on Signal. The calls won't actually go through but you def shouldn't be able to do this at all. also on your conversation screen with that blocked user it'll say that you tried to audio/video call them. This is done on the profile screen for a recipient. 

### Steps to reproduce
- block a user
- on the conversation list screen click their avatar/icon
- in the dialog that appears, click their avatar/icon a second time - taking you to the Manage Recipient Screen
- There will be buttons to text/call/video the blocked user
Clicking the texting button takes you your conversation with them

Clicking the video chat button initiates your camera, the person that you blocked won't receive a video call from you but it'll appear to the user that you are being filmed ringing someone blocked

Clicking the audio call button starts a call, which also won't go through, but signal will tell the user that they cant be calling blocked people

Actual result: buttons appear to contact the blocked user. they can be clicked and are scary
Expected result: those buttons shouldn't appear whatsoever

### Device info

**Signal version:** 5.4.12

**Comment by bitmold** [comment]
Ya

**Comment by Sgn-32** [comment]
On 5.30.6 only the buttons for mute and search are displayed on blocked recipients.

**Comment by alex-signal** [comment]
Looks like this was resolved via another PR? In that case I can close this out.
