### ISSUE TITLE
Sent messages appear in wrong persons chat

### ISSUE THREAD

**Issue by escoand** [signalapp/Signal-Android#11066]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When chatting with one person my sent messages appear in the chat of a different person. Received messages are shown in the right place. When showing the message info I can see the original recipient has read the message. This is only happening with one contact.

### Steps to reproduce
Don't know.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Samsung Galaxy A41
**Android version:** 10
**Signal version:** 5.4.12

**Comment by Nisc3d** [comment]
Can you post a debug log after you notice this? That way the developers can investigate further.

**Comment by escoand** [comment]
https://debuglogs.org/6b0e2d66222c2479783baa15ae365d37df241936c8d57d3b98a017839edcd28e

Messages sent at:
- 2021-03-06 16:53:13
- 2021-03-06 18:41:56
- 2021-03-06 19:55:51
