### ISSUE TITLE
Signal no longer allows fingerprint unlock if a device pin is set.

### ISSUE THREAD

**Issue by ryancdotorg** [signalapp/Signal-Android#11077]
- [x] I have searched open and closed issues for duplicates
- [ ] ~I am submitting a bug report for existing functionality that does not work as intended~
    _Intended functionality is unclear, but behavior changed and a previously working thing no longer works._
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

As of a recent update (in the last week or two), Signal is requiring a device PIN to unlock rather than accepting a fingerprint as it used to.

### Steps to reproduce
- Install Signal
- Enable "Screen Lock"
- Configure Android with PIN
- Enable fingerprint unlock in Android
- Install AdminControl
- Use AdminControl to disable fingerprint on lockscreen

https://github.com/linux-colonel/AdminControl

**Actual result:** Signal prompts for fingerprint unlock
**Expected result:** Signal prompts for PIN unlock

### Device info
**Device:** Pixel 3
**Android version:** 10
**Signal version:** 5.4.12

This seems specifically related to the KEYGUARD_DISABLE_FINGERPRINT policy flag.

Appears to be caused by or related to https://github.com/signalapp/Signal-Android/commit/3c4252a933a800f5f6dd8ec61bda4ec113350903

**Comment by greyson-signal** [comment]
The intention with Signal screenlock feature is to match what happens on your phone lock screen. We're just using standard auth stuff. The purpose of 3c4252a was to update the auth so that it allows PIN fallback (previously we'd always use fingerprint auth if enabled, with no fallback option). 

I'm guessing that because you disabled fingerprint auth on the lockscreen, that we'll just skip over it now too. Not sure if there's much we can do there, unless you had any specific suggestions?

**Comment by ryancdotorg** [comment]
My primary motivation for my configuration is that I have several banking apps that require a password every time I open the app unless fingerprints are enabled, however I aggressively do not want to allow that as a way to unlock the phone.

In Signal's case, this change reduces security - two factors are reduced to one, and I don't see any point in having the lock option there if it uses the same PIN I mash into the screen many times a day, and I've simply turned it off now.

Perhaps fallback behavior should be separate toggle? I'm not sure what the recovery case looks like there, though.

Not clear how difficult this would be to implement.
