### ISSUE TITLE
Random messages are delivery delayed

### ISSUE THREAD

**Issue by n0sign4l-official** [signalapp/Signal-Android#11079]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi all,
I am wondering if any of you has the same issue of mine. It is now around 3 days that I do receives messages of some friends like 1 hour later than they sent me. (No is not due to bad internet connection cause in the mean while a can talk with other friends on signal without any problem).
And I got this issue with many signal users from iOS to Android.

Here is the debug log:
https://debuglogs.org/d68c0ce73da6f1bf2ba1130d04cc1a8fcc57f2eb8a285022f201b078a935ad43
I really hope that some developer can look into it ASAP, since this is really really really annoying

### Steps to reproduce
- Dunno

**Actual result:** Messages are delivery delayed
**Expected result:** Messages should be delivered 

### Link to debug log
https://debuglogs.org/d68c0ce73da6f1bf2ba1130d04cc1a8fcc57f2eb8a285022f201b078a935ad43

**Comment by greyson-signal** [comment]
Hmm, not seeing anything weird in your logs. One known issue on iOS is that they can't easily send messages in the background if a user sends a message and then closed the app right away. Could your friends be doing that?

**Comment by n0sign4l-official** [comment]
It is possible, but I'm having issues also with android users. And by close you mean put it in background or literally close the app? If you mean put it in background it is possible otherwise I do not think so.

**Comment by sadortun** [comment]
I also have this same issue since January. 

I can use the app, talk/chat to people, and hours later receive messages from another contact.

Example, I just received a few minutes ago about 20 messages that were sent 13h earlier. Phone was charged, on Wifi + LTE, and app in the foreground.

![SmartSelect_20210318-210651_Signal.jpg](https://user-images.githubusercontent.com/794449/111717237-0e9d6000-882e-11eb-8ea5-01b25291672a.jpg)

**Comment by n0sign4l-official** [comment]
Hi @sadortun can you please provide logs too so that Greyson maybe will be able to find the issue?

**Comment by sadortun** [comment]
@greyson-signal @n0sign4l-official 

https://debuglogs.org/521f6d0803f9639163336ca0c7f71b0205fc09b49549c96e3b0f28b12d983e0d

**Comment by greyson-signal** [comment]
We've been tracking delayed notifications/message receives here: #8692.
Closing this one in favor of that one.
