### ISSUE TITLE
Storage leak in auto-delete settings

### ISSUE THREAD

**Issue by nkr0** [signalapp/Signal-Android#11086]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Media auto-deleted by signal's "Keep messages" and "Conversation length limit" settings removes them from chats, but storage is still occupied.

### Steps to reproduce
- set auto-delete settings low. 30 days and 10 messages length etc.
- send enough media so that they are deleted by these storage management settings

**Actual result:** User data storage space used grows, although messages have been removed from chats.
**Expected result:** Storage should be freed after auto-deleting messages

### Screenshots
In the first 3 images you can see that I've deleted all my chats by selecting them one by one, but data storage still shows about 25MB used. Furthermore, review storage shows no media. I've no stickers installed.
![1](https://user-images.githubusercontent.com/42086312/110591684-aa1d3980-8179-11eb-8089-aaa490a14f85.png)
![2](https://user-images.githubusercontent.com/42086312/110591718-b30e0b00-8179-11eb-9746-b0259d9e20ab.png)
![3](https://user-images.githubusercontent.com/42086312/110591724-b5706500-8179-11eb-80bb-fc8e455fd7d5.png)

App info shows 32MB of user data.
![4](https://user-images.githubusercontent.com/42086312/110591827-d0db7000-8179-11eb-99a8-3ce42ed027bb.png)

Once I hit "Clear message history", this space is recovered.
![5](https://user-images.githubusercontent.com/42086312/110591923-f0729880-8179-11eb-9c63-a9c287f9f51e.png)
![6](https://user-images.githubusercontent.com/42086312/110591928-f23c5c00-8179-11eb-93ad-16dae4f8e88f.png)

### Device info

**Device:** Xiaomi Redmi Go
**Android version:** 8.1.0
**Signal version:** 5.4.12

**Comment by nkr0** [comment]
On another device running a more recent version of android, storage usage shows 213 MB. But, selecting all media in "Review storage" totals to only 14 MB.
![1](https://user-images.githubusercontent.com/42086312/110622459-c5993c00-819b-11eb-9e13-71522d62abd1.png)
![2](https://user-images.githubusercontent.com/42086312/110622572-f11c2680-819b-11eb-8de1-6a44d1b81c67.png)

### Steps to reproduce
- same as in the issue report

**Actual result:** Storage usage and total from "Review storage" are significantly different
**Expected result:** They should be more or less same

### Device info
**Device:** Xiaomi Mi A3
**Android version:** 11
**Signal version:** 5.4.12

**Comment by andrazznidar** [comment]
I have observed the same issue and have appended a debug log.

### Device info

**Device:** Huawei P9 (With only 32 GB of internal storage)
**Android version:** 7.0
**Signal version:** 5.16.3

### Link to debug log
https://debuglogs.org/bc841f9913286c902d774ab20bc59000b86c50bc6c29dae78b27675e0f1e4ae2
Debug log was created immediately after the conversations were trimmed.

**Comment by greyson-signal** [comment]
Hi, thanks for the update. We made some improvements in 5.17.x, let me know if the issue still happens there.

**Comment by andrazznidar** [comment]
Signal version 5.17.3 (Beta) immediately fixed the issue for me. Thank you.

**Comment by nkr0** [comment]
yep, retroactively cleared storage.
