### ISSUE TITLE
Signal can't use Google Cloud Messaging (Notification push) 

### ISSUE THREAD

**Issue by shadowmedicis** [signalapp/Signal-Android#11080]
![Screenshot_20210308_232808_com huawei android launcher](https://user-images.githubusercontent.com/80291786/110390399-39392d00-8066-11eb-9977-1ba259ef9b18.jpg)
Bonjour, 

J'utilise un Huawei P40 Pro, ce nouveau smartphone ne dispose pas des services Google. 
Signal fonctionne tout de même correctement hormis pour les notifications des messages.
Quand j'ouvre l'application un message d'erreur m'indiquant que Signal ne peut pas s'inscricrire auprès du service de notification Google. 

Merci de faire le nécessaire pour soit ne plus dépendre du service de notification de Google soit intégrer le service de notification de Huawei en utilisant les HMS de Huawei et en publiant l'application sur AppGallery.

Pour plus d'informations:
https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/push-receipt

Merci d'avance

**Comment by hiqua** [comment]
> Merci de faire le nécessaire pour soit ne plus dépendre du service de notification de Google soit intégrer le service de notification de Huawei en utilisant les HMS de Huawei et en publiant l'application sur AppGallery.

Apk available here: https://signal.org/android/apk/

If you install Signal on a system with no Google services, it should fall back to an always-on notification that keeps the notification active in the background. I guess Huawei does something more and pretends it has Google services and provides an alternatives which is not 100% compatible, hence the error message you got.

Does it fall back to this notification once you've swiped this warning?

**Comment by hiqua** [comment]
@shadowmedicis also please add a debug log to your issue.

**Comment by shadowmedicis** [comment]
Hi everyone,

Thank you for your answers.
I found a solution to re-operate signal notifications and other mobile applications on the Huawei P40 Pro

![Screenshot_20210310_192948_com.google.android.gms.jpg](https://user-images.githubusercontent.com/80291786/110681133-c355d280-81d9-11eb-8e6b-a946a4d2e778.jpg)

The app is called microg and allows you to use some of Google's services freely.
The Google Cloud Messaging service can be used on the phone even if it doesn't have Google services as long as it's registered with Google

To learn more about the subject:
 https://microg.org/

 Without this application I would not receive notifications of messages or call notifications. 

Once microg is installed and configured. 
I had to erase the data from the Signal app and then recocery the data from after backup. 
Then the notifications were refunctioned

On the other hand I still have the error notification that I sent you when the application first started.
Maybe the app needs Google api to work?

I'm sending you my logs to find out more:
https://debuglogs.org/b6dfaa3ad32f310327f89f0e7bb3ec3139525d648a42edb18959c47258d67cd5

I remain available if you need to do further tests.

Thank you in advance,

**Comment by shadowmedicis** [comment]
@hiqua 

Thank you for your quick return. Not as mentioned above I installed microg to receive notifications because I did not receive them without the mobile phones in the background. Even by disabling microg I still have the error.

![Screenshot_20210310_215228.jpg](https://user-images.githubusercontent.com/80291786/110696592-8eeb1200-81eb-11eb-8d7b-a85ba4467abd.jpg)

![Screenshot_20210310_215244_com.google.android.gms.jpg](https://user-images.githubusercontent.com/80291786/110696607-91e60280-81eb-11eb-8d3e-17fbc160f221.jpg)

**Comment by hiqua** [comment]
To be clear, anything microg-related is out of the discussion here since it's not a Signal bug (see e.g. https://github.com/signalapp/Signal-Android/issues/9702#issuecomment-652519890). Feel free to open a topic on the forum for that: https://community.signalusers.org/c/support/android-support/11

Now, if you have no notification when you install Signal on a phone without GCM *and* without microg, then this would be a bug, and the debug log could be interesting in this case.

**Comment by shadowmedicis** [comment]
Hello everyone, 

after installation and reinstallation of Signal and the new version of Microg I managed to remove the error message. So I confirm that the error seems to come from Microg. 

Thank you all for your feedback and help. 

So I'm closing this issue
