### ISSUE TITLE
HTML entities aren't completely processed in link previews

### ISSUE THREAD

**Issue by oittaa** [signalapp/Signal-Android#11083]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

It looks like titles were fixed recently, but the rest is still HTML encoded. https://github.com/signalapp/Signal-Android/issues/10020 https://github.com/signalapp/Signal-Android/commit/0c73ddc08b404474b69c36b287b228899952fca7
The same issue affects at least the latest Signal Desktop, but I don't know about the iOS client.

For example this twitter link https://twitter.com/elonmusk/status/1369379914139451406
Notice the `&amp;` entity.
![Screenshot 2021-03-09 at 22 55 36](https://user-images.githubusercontent.com/8972248/110543457-a31b0a80-812a-11eb-8229-f4be12151e45.png)

### Device info

**Device:** Google Pixel 5
**Android version:** 11, 2021-03-05 security update
**Signal version:** 5.4.12

**Comment by greyson-signal** [comment]
I think Twitter may have some bug. The literal content of the og tag is:

```html
<meta  property="og:description" content="“@austinbarnard45 SN10 engine was low on thrust due (probably) to partial helium ingestion from fuel header tank. Impact of 10m/s crushed legs &amp;amp; part of skirt. Multiple fixes in work for SN11.”">
```

Notice the `&amp;amp;`. So we are decoding it, it's just bad original content.

Other online html decoders produce the same output we produce:

https://emn178.github.io/online-tools/html_decode.html
https://codebeautify.org/html-decode-string
