### ISSUE TITLE
Read Icon gets activated even in one person reads the message in a group chat

### ISSUE THREAD

**Issue by SoulNinja-dev** [signalapp/Signal-Android#11093]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

-------------------------------------------------------------------------------
#### please read this 👇
small spelling change so that it makes sense: 
read - pronounced _reed_
red - normally spelled as read, but I'll use red to indicate past tense 

### Bug description
In group chats, a message turns into red even if one person reads it.
normally, only if all the members of the group chat reads the message, it will turn to red, but here it changes to red even if one member reads it.

### Steps to reproduce
- Signal group chat with min. 3 people, on both desktop and android, its the same on both
- send a message
- let one person read the message
- It will turn into the red message icon
- check message info, only one person would have red it, not everyone would have.

**Expected result:** 
Only if everyone in the group reads the message, it should turn into the red icon.

### Screenshots
![image](https://user-images.githubusercontent.com/68557696/110944421-75200b00-8362-11eb-9736-09e35f9ed578.png)
![image](https://user-images.githubusercontent.com/68557696/110944516-941e9d00-8362-11eb-892c-bee4323ff3d1.png)

### Device info
**Android version:** 10.0
**Windows desktop version** Windows 10

**Comment by greyson-signal** [comment]
Because read receipts on android are optional, there are some people who will just never send them. As a result, the best we can do is change the overall read state when *someone* has read the message.
