### ISSUE TITLE
Impossible to press "send" button again when getting back from the contact list

### ISSUE THREAD

**Issue by CamilleKaze** [signalapp/Signal-Android#11096]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The blue "send" button appears but nothing happens when pressing it when I try to send the photo.
That only occurs when I try to take a picture from the main conversation list ("home" of the app), then click send (which gets me to the contact list to select the people I want to send the picture to), then go back because I want to modify it. At that moment it's impossible to click the "send" button again.

### Steps to reproduce
- Open Signal
- Go to the main conversation list
- Click the camera button in the bottom right corner
- Take a picture
- Click the blue button with an arrow on it ("send") in the bottom right corner to send the picture
- That should take you to the contact list. Go back to picture you just took (let's imagine you forgot to add a message on it)
- Try to click the "send" button again. Nothing happens.

**Actual result:** You can still modify your text (both on your picture or in the actual message) but nothing happens when you click on the "send" button. You're stuck on that screen, you can only go back.
**Expected result:** Clicking on that button should take you to the contact list to select the people you want to send the picture to.

### Screenshots

![signal-2021-03-13-101555](https://user-images.githubusercontent.com/30692513/111025571-45fead80-83e5-11eb-9042-72e02373936e.jpeg)

### Device info

**Device:** Xiaomi Poco M3 from Xiaomi France
**Android version:** 10 QKQ1.200830.002 (MIUI Global 12.0.6 Stable 12.0.6.0(QJFEUXM)
**Signal version:** 5.4.12

### Link to debug log

https://debuglogs.org/dd501b5fd2b0cda62494d460f50318cb816e046fec8f54cdca77bcc5697b970f

**Comment by kartikeysaran** [comment]
Can i work on this issue !?

**Comment by IronJunkie** [comment]
#10941 seems like share issue
