### ISSUE TITLE
Missing permission to read folder (to attach an image)

### ISSUE THREAD

**Issue by yan796** [signalapp/Signal-Android#11105]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The gallery is empty although it should be with pictures present on the phone. This ONLY happens when we did not give permission to Signal to READ our internal storage, not because we declined, but because this was never asked if we follow the steps described bellow.

### Steps to reproduce
After a fresh install (no permission granted yet)
- directly click on camera (accept permission to use camera and microphone)
- take a picture, 
- then click the "+" button. 

**Actual result:** 
The gallery is empty although it should be with pictures present on the phone
**Expected result:** 
The gallery display the pictures present on the phone
### Screenshots

This is following the steps
![device-2021-03-15-142503](https://user-images.githubusercontent.com/10091822/111168762-49876580-859a-11eb-8277-b44f81b08a55.png)

If before capturing a picture we start a chat an attach a file, we are asked to give access,
![device-2021-03-15-142739](https://user-images.githubusercontent.com/10091822/111169190-a4b95800-859a-11eb-8993-5a4a6484ccd4.png)

then after granting the access, following the steps above give the expected results
![device-2021-03-15-143048](https://user-images.githubusercontent.com/10091822/111169797-33c67000-859b-11eb-8ff6-7ccc1f95ccf7.png)

### Device info

**Device:** Manufacturer Model Huawei p20
**Android version:** 10.0.0
**Signal version:** 5.5.1

**Comment by greyson-signal** [comment]
Fixed via 21252aad0f3917e08173cdde638f7c210ae146bd
