### ISSUE TITLE
Sticker and Emoji are not shown correctly on Android 11 Bubble chat

### ISSUE THREAD

**Issue by quyleanh** [signalapp/Signal-Android#11104]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sticker and Emoji are not shown correctly on Android 11 Bubble chat

### Steps to reproduce
- Turn on and allow Signal Android use bubble chat on Android 11
- Open any Signal chat on bubble chat type
- Press Sticker/Emoji button on the left of textbox

**Actual result:** Sticker and emoji are not shown correctly on Android 11 Bubble chat. They are chopped.
**Expected result:** Show sticker and emoji table correctly and fully

### Screenshots

![photo_2021-03-15_15-23-48](https://user-images.githubusercontent.com/9365035/111124552-35943180-85a3-11eb-93ac-0a65654d8f3d.jpg)

### Device info

**Device:** Xiaomi Mi 8
**Android version:** 11
**Signal version:** 5.4.12

### Link to debug log

https://debuglogs.org/49c1bbaa4511f217d17314750cd8a75e756e6e54db35b659a883eec3bc6c946c

**Comment by ChapmanCheng** [comment]
Reporting same problem, 
Device: nokia 8.3 G
Signal version: 5.5.5

**Comment by quyleanh** [comment]
Since the bug is fixed in the latest version of Android app. I would like to close this issue.
