### ISSUE TITLE
Information from Google Contacts' "Name prefix" field altered or incompletely imported

### ISSUE THREAD

**Issue by Thusid** [signalapp/Signal-Android#11109]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The information from Google Contacts' "name prefix" field is altered or incompletely imported.

For example, 
   "Dipl.-\<suffix>" is shown as "Dipl. -\<suffix>." (additional blank),
   "Dr. sc. nat." is shown as "sc. nat." (missing Dr.),
   "Prof. Dr." is shown as "Dr" (missing Prof., missing trailing period).

### Steps to reproduce
- Open Signal.
- The list of conversations shows the incomplete or altered designations of the participants..

**Actual result:** 
The designations are incomplete or altered.

**Expected result:** 
The designations should appear as in Google Contacts.

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 11
**Signal version:** 5.5.1 (Beta)

**Comment by greyson-signal** [comment]
Hi there, we have a fix that will be going out in 5.5.2. Thanks!

**Comment by Thusid** [comment]
Issue fixed with 5.5.2.
