### ISSUE TITLE
Fido - Visual Voicemail - Recent Message play not working, Old messages works

### ISSUE THREAD

**Issue by khoa81** [signalapp/Signal-Android#11113]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have visual voicemail setup for my phone so all voicemails are transcribed with the option of playing the voicemail audio.  The problem is recently voicemail audios play no sound at all.  I can play the audio file but no sound comes out.  But for the same contact, I can scroll up and click on to play a previous voicemail audio and it'll play just fine.  I can replicate this problem with all other contacts.

### Steps to reproduce
-voicemail audios play no sound at all
-same contact, scroll up and click on to play a previous voicemail audio, audio plays with sound. 
-same issue can be replicated with all other contacts.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
This audio file works:
![image](https://user-images.githubusercontent.com/80849221/111517691-92fac080-8712-11eb-98b9-c774fd8f8307.png)

This audio file doesn't work, note it also doesn't show any voice audio ranged just a flat line
![image](https://user-images.githubusercontent.com/80849221/111517792-b160bc00-8712-11eb-8e65-232d13ae1f4e.png)

### Device info
Device:** Samsung Note 9 - SM-N960W
Android version: Stock Android version 10
Signal version: 5.4.12

### Link to debug log
https://debuglogs.org/1299112b6ddf52ab1faae33c4d0f6f94152d1865e52e15be6275a0e5c9a738bc

**Comment by Tursko** [comment]
Debug logs are still valid. You should attach it. It might show an error reading the file on the actual log.

**Comment by khoa81** [comment]
> Debug logs are still valid. You should attach it. It might show an error reading the file on the actual log.

Added link to debug file :)

Thanks!
