### ISSUE TITLE
Crash open chat/sms

### ISSUE THREAD

**Issue by xunil89** [signalapp/Signal-Android#11119]
the app seems to work correctly, you can browse the settings menu quietly, but if you try to open any chat / SMS it stops opening and stops.

--- Informazioni supporto ---
Filtro: Signal Android Support Request
Informazioni sul dispositivo: Xiaomi Redmi Note 9 Pro (arrow_miatoll)
Versione di Android: 11 (6508, RQ2A.210305.007)
Versione di Signal: 5.4.12
Pacchetto di Signal: org.thoughtcrime.securesms (doDiFGKPO1r)
Blocco registrazione: false
Lingua: it_IT

**Comment by hiqua** [comment]
Are you able to submit a debug log?

**Comment by xunil89** [comment]
> Are you able to submit a debug log?

It is probably a 💩 ROM problem other bugs were born after the ota update, however I attach the log
https://debuglogs.org/6327722949769822cef699682e95ef41b53d21e39988a1ac05fdad0004d6ecf8

**Comment by xunil89** [comment]
There was a fix on the ROM, solved sorry for the bug not attributable to you ...

**Comment by hiqua** [comment]
Ok you can close this issue then!

**Comment by UserX404** [comment]
@xunil89 
Pls close!
