### ISSUE TITLE
Account transfer happens even when signal is registered with a different number in the new device

### ISSUE THREAD

**Issue by abhinavtk97** [signalapp/Signal-Android#11112]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have recently transferred my chats from my old phone to my new phone, but I accidently registered with a different number in the new phone. Signal did not stop me from copying all the chat messages from my old phone to new one even when the number used in both the phones are different. I don't know if this is actually intentionally or if you missed to include the condition, but I think this can be used by people to copy their chats to a different phone if they got access to the original phone.
I came to know about this only after I found that I was no longer a part of some groups I used to be in, but I can see old chats.  Except this, everything else looks as if I am using my old account itself.

### Steps to reproduce
- Use transfer account feature in old phone with number 'A'
- Use a different number in new phone with number 'B'
- Continue the account transfer process and the process with succeed even when the phone number used in the second device is different

**Actual result:** Account gets transferred even when the phone number is different.
**Expected result:** Account should not transfer as the phone numbers are different

### Device info

**Device:** OnePlus Nord
**Android version:** 11.0
**Signal version:** 5.5.2

**Comment by Leptopoda** [comment]
Hi there,
This behavior is expected as some people might wanna switch numbers that way

**Comment by greyson-signal** [comment]
Yeah, I suppose I'd say that this "isn't unintended" :) We may revisit this in the future. Backups restored with different numbers does cause funny things to happen with group membership and whatnot.
