### ISSUE TITLE
Signal blocked in China

### ISSUE THREAD

**Issue by peteh** [signalapp/Signal-Android#11110]
Since this morning signal seems to be blocked in China. 

Are there any workarounds for this known already? 

I'm using latest signal 5.4.12 from Google store

**Comment by hiqua** [comment]
Yes it's known, news outlets have reported about it, it's same to assume the Signal team knows about it by now.

To discuss further: https://community.signalusers.org/t/signal-has-been-blocked-in-china/29901

**Comment by greyson-signal** [comment]
We're aware of this, thanks!

**Comment by Russiarain** [comment]
So upset. I've been using signal for several months, it's really good. I know it will be blocked by GFW since the day it was recommended by Elon Musk on Twitter , it's just a matter of time. They just block everything they can't surveil.
