### ISSUE TITLE
Screen lockup on biometric unlock prompt

### ISSUE THREAD

**Issue by Ndr6** [signalapp/Signal-Android#11120]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when using Signal, letting the screen lock, and coming back to the phone after some time, the biometric unlock prompt is on top of screen (above the OS lock screen) and the whole screen apart from the navigation bar at the bottom become unresponsive. Putting my finger unlocks the phone lock screen, but the Signal unlock prompt is still there and the screen is still unresponsive. The only way I found to fix this is to restart the phone, as the shutdown menu appears above the biometric unlock prompt.

### Steps to reproduce
This bug happened multiple times to me but I haven't been able to isolate steps to reproduce it.

**Actual result:** Screen is unresponsive on a biometric unlock prompt
**Expected result:** Biometric unlock prompt does not appear over the OS lock screen

### Screenshots
I will try to get screenshots the next time this bug happens

### Device info
**Device:** Huawei Nova 5T (YAL-L21)
**Android version:** 10 (EMUI version: 10.1.0)
**Signal version:** 5.5.5

### Link to debug log
https://debuglogs.org/db9039dcab5ccdca7da31cf5ae4d0024a3d4ce3e8e5403794b833e41273fc2b2
The bug happened sometime after 15h45, and after the reboot I tried multiple times to reproduce the bug without success. If the bug happens again I will share a debug log just after the reboot.

**Comment by oittaa** [comment]
>  The only way I found to fix this is to restart the phone, as the shutdown menu appears above the biometric unlock prompt.

On my phone (Pixel 5) I don't have to restart the phone. I just kill the app and then the fingerprint authentication works again for some time.

**Comment by Ndr6** [comment]
> > The only way I found to fix this is to restart the phone, as the shutdown menu appears above the biometric unlock prompt.
> 
> On my phone (Pixel 5) I don't have to restart the phone. I just kill the app and then the fingerprint authentication works again for some time.

How do you kill the app ? My screen is unresponsive, I can only use the navigation bar at the bottom

**Comment by oittaa** [comment]
I have gesture navigation enabled and I'm able to swipe up to expose the application scroller.

**Comment by Ndr6** [comment]
You mean the app switcher ? I can expose it but cannot use it since the screen is not responsive, the biometric prompt stays above it

**Comment by oittaa** [comment]
Yeah. My phone is on the latest Android 11 version. Maybe the behavior changed so that an app can't stay on top of the OS components like app switcher?

**Comment by Ndr6** [comment]
https://debuglogs.org/90d6cc07208d53f7e339e5af6a160b71bac218e5b1a1cd00fc6337b5b08516e9

Log taken just after the reboot, when the bug happened

![Screenshot_20210320_124221_com.huawei.android.launcher.jpg](https://user-images.githubusercontent.com/9055775/111868437-1c5ffc00-897a-11eb-8b03-afb86e317d32.jpg)

Screenshot of the prompt above the app switcher

**Comment by oittaa** [comment]
![Screenshot_20210320-225704](https://user-images.githubusercontent.com/8972248/111886662-c0c05d80-89cf-11eb-9914-6cfc2bc0527b.png)

Happened to me again here's what it looked oks like. I can't get past the screen unless I kill the app. https://debuglogs.org/5f6ba3b3a1ab2f7cd030c9c7c0deaeeeece4cd49dc7546093f034fdfca90d924

**Comment by BubbaRayFett** [comment]
Pixel 3a, Android 11 (security update March 5, 2021), Signal 5.4.12, when I get to that screen the "TAP TO UNLOCK" button does nothing, no amount of tapping on the screen will allow the app to open. I have to close the app and reopen it in order to access messages.

**Comment by pandalamp** [comment]
I think two separate issues are being discussed here, although I'd guess both are caused by the same problem.

1. Biometric prompt is unresponsive and freezes above other UI elements
2. Biometric prompt won't appear at all

Both issues seem to be intermittent, and in my experience with the second one, often happen when trying to open the app after receiving a notification from it. This only started happening within the past few weeks. I'm on up-to-date Pixel 3, Signal 5.5.5 ([log](https://debuglogs.org/1c71b495482507922759b57cfedce9c4344e861a66fe9170705a0a60313efb48)).

**Comment by pandalamp** [comment]
Any updates on this? It has been almost two months since this started happening. At this point I'm considering abandoning Signal altogether since I can't even unlock the app most of the time I use it.

**Comment by oittaa** [comment]
Super annoying bug that's still present in the latest version. A lot of people seem to have this issue since these all recent bug reports are probably related #11215 #11233 #11285

**Comment by cody-signal** [comment]
Please try a recent build, some fixes were made for this, sorry it took so long.

**Comment by Ndr6** [comment]
I got a new device since then, so I can't test if the problem is fixed

**Comment by BubbaRayFett** [comment]
I can verify that the issue is resolved for me in Android 12 beta.
--
Sent from myMail for Android Wednesday, 29 September 2021, 03:55PM -05:00 from Cody Henthorne  ***@***.*** :
