### ISSUE TITLE
Appearance/Chat wallpaper option not localized for some languages

### ISSUE THREAD

**Issue by Timbo2192** [signalapp/Signal-Android#11123]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Appearance/Chat wallpaper option not localized for some languages.

### Steps to reproduce
- Open Signal
- Tap on three dots icon
- Select Settings
- Select Appearance
- Select Language
- Select one of: 
  - Ukrainian
  - Quechua
  - Punjabi
  - Malay
  - Luganda
  - Latviesu
  - Kiswahili 
  - Khmer 
  - Kannada 
  - Hindi 
  - Hausa
  - Gujarati 
  - Gaeilge
  - Filipino 
  - Burmese 
  - Bengali
  - Basa Jawa
  - Azerbaycan

**Actual result:** "Chat wallpaper" option is not localized, shown in English

**Expected result:** "Chat wallpaper" option is localized, shown in selected language

### Screenshots

<img src="https://user-images.githubusercontent.com/68671029/111850045-28e24700-88dd-11eb-9f1a-3f6ed402953b.png" width="400">

### Device info

**Device:** Samsung Galaxy S6 Edge
**Android version:** 7.0
**Signal version:** 5.4.12

### Link to debug log

N/A

**Comment by Sgn-32** [comment]
This is not an issue in Signal. The languages listed are not fully translated in Transifex.

https://www.transifex.com/signalapp/signal-android/languages/

**Comment by Timbo2192** [comment]
Thanks for the information! Closing the issue.
