### ISSUE TITLE
Icons blocking each other in landscape mode

### ISSUE THREAD

**Issue by Timbobeek** [signalapp/Signal-Android#11124]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Icons are blocking each other in landscape mode.

### Steps to reproduce
- Open Signal
- Rotate to landscape mode

**Actual result:** Some icons/buttons are blocking each other, making it impossible to select them
**Expected result:** All icons/buttons are in their appropriate spots and are easy to select

### Screenshots

![image](https://user-images.githubusercontent.com/68671029/111853379-cbec8e00-88e8-11eb-815b-257d011befa7.png)

### Device info

**Device:** Samsung Galaxy S6 Edge
**Android version:** 7.0
**Signal version:** 5.4.12

### Link to debug log

N/A

**Comment by cyrilbeyo** [comment]
Happening also in Google Pixel/Android 10 
![signal](https://user-images.githubusercontent.com/23119827/111861802-270e9700-8962-11eb-87d0-adc71c69e0fd.png)
