### ISSUE TITLE
Add OnePlus 8 Pro to AEC blacklist 

### ISSUE THREAD

**Issue by Klitsa** [signalapp/Signal-Android#11127]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I call someone on my OnePlus 8 Pro and use speakerphone the person I call hears a clear echo of themselves. This also happens with video calling as that enables speakerphone.  My device is running LineageOS 18.1 without Google play services. 

### Steps to reproduce
- Call anyone in Signal app and use speakerphone

**Actual result:** Call recipient hears echo of themselves. 
**Expected result:** Call recipient shouldn't hear an echo of themselves. 

### Device info

**Device:** OnePlus 8 Pro
**Android version:** 11 (LineageOS 18.1)
**Signal version:** 5.4.12

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5

**Comment by Klitsa** [comment]
I think this issue is OBE now. It has been working fine for months! Thanks!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
