### ISSUE TITLE
Signal adds contacts of foreign SIM-card to your phones address book without asking

### ISSUE THREAD

**Issue by Flexmaen** [signalapp/Signal-Android#11129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I temporary did insert the SIM-card of a friend into my phone.
(There might be reasons to do this, e.g. her phone is out of battery and she expects an urgent call, etc.).

After this I noticed that I suddenly had many of her contacts in my phone book.
Turned out that she had stored her contacts on her SIM-card and that only contacts were added that also are on Signal.
So it must have been Signal that added these contacts without asking.

**This is a privacy issue!**

### Steps to reproduce

I was able to reproduce this:

1.  I used a card reader to add two contacts to a 2nd SIM-card that weren't in the phones address book yet. One who has Signal, one who hasn't. (You might use a 2nd phone instead of a card reader)
2.  I added this SIM-card to my phone, did a restart and a speed test for testing the internet connection, and took a look on my contacts with [Simple Contacts](https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/) (which I did not have installed when this happened the 1st time)
2.  Then I removed the SIM-card again and inserted my regular SIM-card.

**Actual result:** The contact that also is on Signal remained in my adress book while the other contact didn't.
**Expected result:** Signal should at least ask me if I want to copy contacts from the SIM card into my phones adress book.

### Device info

**Device:** Blackberry Key1
**Android version:** 8.1.0
**Signal version:** 5.4.12

### Link to debug log
https://debuglogs.org/096dd0ee8435c85eb7f454e96e72c8b0752807aec07082d8ea2bcc4e1dfb7ad8

**Comment by samuraikidXDA** [comment]
Yep its over writting my deny contacts permissions whats going on ?

**Comment by Flexmaen** [comment]
The Blackberry comes with DTEK, so you can see which apps does access privacy data when.

The screenshot here **proves** that Signal did create these contacts as a background job.
So, it is not something that happens on your own user interaction, instead it happens in the background without notification.

Language is set to German, so the translation for the content in the red squares is:
1. Access in background
2. Anmount of contacts created by this app: 2

![signal](https://user-images.githubusercontent.com/6330276/112457155-c2857a80-8d5b-11eb-9a28-e20797a22b8a.png)

Some might say "your fault when you insert other SIM-cards". However, I never experienced this from any other phone or app, and least expected this from an app that cares about privacy. It least you should be asked if you want to copy the contacts.

**Comment by Flexmaen** [comment]
Yes, still relevant and also a **privacy issue**.

**Comment by greyson-signal** [comment]
We don't query for contacts by a specific SIM or anything. We just ask android "what are the contacts" and we act accordingly.
If you do not contact anyone and they're not signal users, then when the contacts are removed you'll see them disappear from your signal contacts list.

**Comment by Flexmaen** [comment]
@greyson-signal The problem is not that Signal queries these contacts. The problem is that Signal messes with the contact list and contacts of the SIM card will be copied into the contact list of the phones memory without asking the user.
Please reopen this if it is not solved yet.
