### ISSUE TITLE
Whay Don't support FireBase ?

### ISSUE THREAD

**Issue by anasselkadi** [signalapp/Signal-Android#11125]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Kwasow** [comment]
Signal does use Firebase for the builds distributed through the Play Store while also providing a build for devices without Google Play Services under https://signal.org/android/apk.

Your issue doesn't seem to fit on github so if you want to discuss the pros and cons of this solution please start a topic at https://community.signalusers.org/
