### ISSUE TITLE
Feature Request: Stickers should be double tap to send

### ISSUE THREAD

**Issue by SwartzCr** [signalapp/Signal-Android#11128]
Current behavior:
When browsing stickers tapping on one instantly sends it, with no confirmation
This is extremely nerve wracking. Assuming I am browsing a sticker pack with many edgy or NSFW stickers and a single SFW sticker that I would like to send to a group chat, I may accidentally send a sticker unintentionally while browsing.
The result is I am afraid to use stickers since it seems too easy to accidentally send the wrong one.

Proposed change:
Stickers should highlight on tap (or foreground or be put into the message box) and require a 2nd tap to send.
For examples of how this could work see other messaging apps such as Line.

**Comment by SwartzCr** [comment]
One additional benefit of this would be that small details in stickers would be visible before sending as well.
Currently if a sticker has not been used yet, certain text in it may not be readable from the list view. A preview before send confirmation would allow users to read the text and determine whether the sticker was appropriate to send before sending it

**Comment by Kwasow** [comment]
Github issues should not contain feature requests. For feature requests please visist https://community.signalusers.org/ where you can discuss the changes with the community.
