### ISSUE TITLE
ScreenLockTimeout GUI is not behaving like expected

### ISSUE THREAD

**Issue by yan796** [signalapp/Signal-Android#11132]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The screenlocktimeout gui is not behaving like expected. 
- 1) When one input a value < 60s but > 0s, the value is clamped to 60s without warning
- 2) When input a value a second time, the gui is rested instead of displaying the value stored in preference

### Steps to reproduce
- go to privacy
- activate Screen lock
- input value less than 60s, e.g. 30 and validate (fig 1)
- Notice the value display is actually 00:01:00 (clamped to 60s, see fig 2)
- open the dialog again, the value is back to 0 instead of 00:01:00 (see fig 3)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

fig 1:
![step1_bug](https://user-images.githubusercontent.com/10091822/112345134-ad0d4380-8cbc-11eb-9f8f-a0f341653c31.png)

fig 2:
![step2_bug](https://user-images.githubusercontent.com/10091822/112345158-b26a8e00-8cbc-11eb-852c-26e2febe70ea.png)

fig 3:
![step3_bug](https://user-images.githubusercontent.com/10091822/112345173-b696ab80-8cbc-11eb-8efd-e13514cb8a61.png)

### Device info

**Device:** Huawei p20
**Android version:** 10.0.0
**Signal version:** 5.5.5

**Comment by Sgn-32** [comment]
The ScreenLockTimeOut was redesigned on an earlier version. Seconds aren't possible anymore.
