### ISSUE TITLE
Emoji reaction is lagging

### ISSUE THREAD

**Issue by peterpanondrugs** [signalapp/Signal-Android#11145]
This is a bug report template. By following the instructions below and filling out the sections with your information, you will help the developers get all the necessary data to fix your issue.
You can also preview your report before submitting it. You may remove sections that aren't relevant to your particular case.

Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.

If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When choosing a emoji reaction, the popup time differ in time (lagging)

### Steps to reproduce
-  ER (emoji reaction) on a message
- choose any reaction
- repeat with another message
- doesnt matter which you click first

**Actual result:** lagging in reaction time
**Expected result:** should popup immediately
### Screenshots

[
**Device:** Samsung S7
**Android version:** 9
**Signal version:** 5.4.10

### Link to debug log

https://debuglogs.org/fa3e86cc31caee4d5b7392d4c241a4f86ca6f50552c43adaff50b91a2981655f

**Comment by Dyras** [comment]
I think Signal is experiencing issues atm
