### ISSUE TITLE
After transfer: Theme not applied

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#11142]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After transferring messages from an old Android Phone to the new one, the Theme was not applied.
The information about the setting itself was transferred I guess, since its shown correctly in the settings but it is not applied, so Signal is in bright mode. 

### Steps to reproduce
- Choose Dark Theme on Old Device
- Transfer to new (with the new direct-transfer method)

**Actual result:** New Signal is in bright mode, while the settings show that it is in dark mode.
**Expected result:** Dark Theme is selected in the settings *and* applied to Signal

### Device info

Old:
**Device:** OnePlus 5T
**Android version:** 10.0.1
**Signal version:** 5.5.5

New:
Old:
**Device:** OnePlus 8T
**Android version:** 11
**Signal version:** 5.5.5

### Link to debug log
https://debuglogs.org/e637fd30080f85136996cf23fd5d9ad0a4a3136f7ed7ec9e7a3e1ace2e2ec221

**Comment by Sgn-32** [comment]
This is also when restoring from a backup.
App setting for theme is "dark", but Signal is in "light".

Signal: 5.18.5
