### ISSUE TITLE
Messages are sometimes not delivered until a new message has been sent by sender or receiver

### ISSUE THREAD

**Issue by Chr3is** [signalapp/Signal-Android#11140]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

- A contact sent me a message which was not received by my client. After some time I asked another thing and the missing message was delivered (see screenshots and timestamps). 

- Second scenario was that a message was not received by me until the sender wrote a second message. 

- Third scenario was that the message was received on all devices by me after I opened the desktop client approximately a day later.

The missing messages were also not delivered after the android app or phone was restarted.
**Note**: The message was not delivered in the windows client as well for scenario one and two. It seems to be a server issue.

Probably similar to this one: https://github.com/signalapp/Signal-Android/issues/10693

### Steps to reproduce
- don't know

**Actual result:** Messages are sometimes not received.
**Expected result:** Messages are received. At least when the app was restarted.

This issue makes Signal almost unusable for me because I can not be sure if the sender didn't want to reply till now or the sender waits for my response.

### Screenshots
![scenario_one_0](https://user-images.githubusercontent.com/17119245/112718130-4fae0800-8ef1-11eb-9915-8643fc941809.jpeg)
![scenario_one_1](https://user-images.githubusercontent.com/17119245/112720513-285e3780-8eff-11eb-82d6-b2680cf3c0d7.jpeg)
![scenario_two_0](https://user-images.githubusercontent.com/17119245/112718234-f72b3a80-8ef1-11eb-8141-dba0c587b61b.jpeg)
![scenario_two_1](https://user-images.githubusercontent.com/17119245/112720516-2e541880-8eff-11eb-8c26-b24a4bd2ef83.jpeg)

### Device info
**Device:** OnePlus HD1903 (OnePlus 7T)
**Android version:** 10 (Oxygen OS 10.0.16.HD65BA)
**Signal version:** 5.5.5

### Link to debug log
Not available anymore.

**Comment by samuraikidXDA** [comment]
Its happening since 12h ago cant send messages

**Comment by adi2k5** [comment]
Same here, since few weeks messages are not being received on the day when they have been sent by the people that I'm writing to, and usually those messages do appear a next day (or even later) with the timestamp of the previous day. For me, this is mostly noticeable in the group chats as using them the most. Also I know that the same happened to colleague of mine, os it's not a one person case, but rather a general issue which makes using signal very hard atm.

**Comment by cody-signal** [comment]
If you are still experiencing this issue, debuglogs would be very helpful for us to try and figure out what's going on.

**Comment by Chr3is** [comment]
@cody-signal I can provide some debug logs but the problem is that this issue seems not to be deterministic and appears randomly. I'm also not sure if this is a server issue rather than a client issue because the android app & windows client are both affected.

Here's a debug log from 27 march: https://debuglogs.org/27b23e0dd744f1a443f9e56c63ec1601671d90e3b624ec62454fc83cc721480f
Here's one from today: https://debuglogs.org/357443203e59deff9e04a2232c13c1af6b61b843e26faa34204c64ffc5cc135d

The mentioned scenario 3 happend yesterday but I forgot to take a debuglog. I try to capture a log next time I notice this issue.

**Comment by greyson-signal** [comment]
What type of device does the sender have?

**Comment by Chr3is** [comment]
@greyson-signal the sender told me it's an Iphone 7 with iOS Signal v5.8.2

**Comment by greyson-signal** [comment]
Yeah, so this is almost certainly a case of the iPhone not sending the message (especially if both your desktop and android clients aren't receiving it).

iOS has some additional restrictions that can make reliability harder. Notably, there's limited ability to work in the background. If the iOS user sends a message but then swipes away the app, they won't be able to retry the message send until the app is foregrounded or until they receive a message or something (which gives them another window of processing time). I'll forward this to the iOS team, but this isn't an android issue, so I'll close it.

**Comment by Chr3is** [comment]
@greyson-signal First of all thanks for the explanation. This could explain scenario 1 and 2 **but not** scenario 3. 

I also asked the sender if he could have an eye on the two ticks and he meant there would be always two tickets instantly but this claim could be false positiv.

**Comment by greyson-signal** [comment]
@Chr3is 

> Third scenario was that the message was received on all devices by me after I opened the desktop client approximately a day later.

When you open a desktop instance, it very well could be sending a bunch of delivery/read receipts, which would also wake up the sending device and put you back into scenario 2 territory.

**Comment by Chr3is** [comment]
@greyson-signal well that could be possible. But does the windows client behave differently than the android app? Shouldn't it be possible to force this behavior with restarting the android app too? I don't know the difference in the behavior of the desktop and android app I'm just asking out of curiosity. 
Hower you may pointing already into the right direction that this is an issue related to the ios client which can be fixed hopefully 👍

**Comment by Chr3is** [comment]
@greyson-signal I have another questionen just for clarification:  Is the senttimestamp in the message information the point in time where the message object was created on the device or where the server received the message?
