### ISSUE TITLE
Soms messages are sent after 1 minute, instead of a few seconds

### ISSUE THREAD

**Issue by JordyEGNL** [signalapp/Signal-Android#11159]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Messages send to one of my contacts sometimes takes over 10 seconds to sent (1 checkmark), sometimes more than that, debug is from message that took 1 minute to sent

### Steps to reproduce
- Go to a contact you have chatted with for a long time and has lots of messages
- Send a message

It does not always take so long, so it may not be reproducable

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Message takes a long time to send

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Message is sent after a few secondd

### Screenshots
.

### Device info

**Device:** Samsung Galaxy A71
**Android version:** 11
**Signal version:** 5.6.1

### Link to debug log

https://debuglogs.org/683c1d01361c0e5361c2d89d2d2ce11610e397be43de8b268fefbb30dcd50ee9

**Comment by mariachini** [comment]
Duplicate of #9930

**Comment by JordyEGNL** [comment]
Duplicate of #9930
