### ISSUE TITLE
🔔 notifications don't arrive

### ISSUE THREAD

**Issue by gatomo-oficial** [signalapp/Signal-Android#11158]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
(I'm from spain so I don't speak very good the english) If someone send me a message when I have the app closed I don't receive the notifications and they only arrive when I open the app
### Steps to reproduce
- Close the app
- ask to someone to send the message
- wait the notification (but they never arrive)
- open the app
- look your flooded notification box

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)  you receive all messages wich people sent to you when you had the app closed

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
You would receive notifications with the app closed

### Device info

**Device:** Ulefone Armor X 5
**Android version:** Android 9 (Pie)
**Signal version:** 5.5.5

### Link to debug log

https://debuglogs.org/1c79fffa9e39b7e1025c0bbcd8877593b856b415de71c7288df8f87c35be5032

**Comment by Kwasow** [comment]
This is probably due to Android killing background apps to free resources. You'll have to disable optimizations for Signal. Have a look here: https://www.geekdashboard.com/stop-android-killing-apps-background/#others

I don't know how to do it on Ulefone, so you'll have to figure that part out on your own.

**Comment by alex-signal** [comment]
A lot of device manufacturers really mess with the Android background mechanisms. It's recommended that you take a look at the support steps here: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

Some devices won't even let apps run in the background unless the manufacturer has explicitly whitelisted them.

**Comment by pixincreate** [comment]
+1 on this issue. I'm running on stock Android one, I'm started facing this issue few days back after I received an update and it's quite noticible. Even after opening the app, after some, notification are being received.  
It's been 2 days since I disabled battery optimisation for the app specially, and still no resolution.  
I was able to receive notifcations within 10 seconds previously.

**Comment by UserX404** [comment]
@pixincreate
Please at least share your logs when you create such +1 posts.
Nobody knows your device model and is able to give hints without them.
There are also some other settings (data saving....) which can lead to success.
Check the link Alex has posted above. Specially the phone specific section.

**Comment by pixincreate** [comment]
> @pixincreate
> Please at least share your logs when you create such +1 posts.
> Nobody knows your device model and is able to give hints without them.
> There are also some other settings (data saving....) which can lead to success.
> Check the link Alex has posted above. Specially the phone specific section.  

Sure why not.  
I flashed my phone 2 days back. And installed Signal again.  
Logs: 
https://debuglogs.org/06043cee3a32bc7a2eda85da529bbd014406e929346ec4bd3f58257248a8f824

**Comment by gatomo-oficial** [comment]
@Kwasow and @alex-signal thanks for the support I fixed the problem, but I suggest to fix the problem because is a waste of time install signal and go to settings to disable optimization and people without knowledge of computing will migrate to another app. I'd like to help but I'm a noob in java. Oh, another thing. I suggest remake the frontend of signal doing a cross platform app with react native or flutter for have an unique source code and not two separated. 
Well, I'll shut up. Thanks 😸

**Comment by alex-signal** [comment]
@gatomo-oficial No problem!

To answer your concerns:

1) If we could just go mucking about with people's battery settings on their device, we could set this all up for them, but we cannot. Different device manufacturers are going to employ their own policies about task management and background process lifecycles, and there's not much we can do if a manufacturer decides to prevent us from running in the background besides do our best to detect when it happens and try to give the user some feedback.

2) (Please keep in mind this is my personal opinion, based off my own experiences, and does not necessarily represent the opinion of Signal) We're a small team, and the Signal app is very large. A cross platform app would take a very significant amount of effort (think: probably years) and resources, and it's not obvious that there'd be any benefit whatsoever to the users. In fact, if anything, user experience would likely be degraded. Writing native apps for each platform allow us to really tailor the experience to the platforms themselves, and to try to give the best performance and best end user experience possible no matter what device you're on, be it a flagship model or a low end device.

**Comment by bkqtnte10** [comment]
> and there's not much we can do if a manufacturer decides to prevent us from running in the background

How do the other messengers solve this? If a manufacturer only whitelists some apps maybe they can be contacted to also whitelist signal? Are there numbers as to what devices have the most problems?
