### ISSUE TITLE
Voice Memos Continue to Play When you Open a Video 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#11156]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you are playing a voice message, and then you play a video, the voice message still plays such that the user hears both the voice message **and** the video's audio. 

### Steps to reproduce
- be in a conversation with a voice message and video 
- play the voice message 
- play the video 

**Actual result:** The video plays with the voice message continuing to play in the background
**Expected result:** The voice message should pause before the video player opens 

### Device info

**Signal version:** 5.6.0

**Comment by bitmold** [comment]
Yes it is I submitted a PR To deal with this ongoing bug

**Comment by bitmold** [comment]
Yes

**Comment by bitmold** [comment]
Yes

**Comment by cody-signal** [comment]
Sorry stalebot is being dumb
