### ISSUE TITLE
Unable to get back to call when exiting on lock screen

### ISSUE THREAD

**Issue by chaptergy** [signalapp/Signal-Android#11150]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Normally, when you are in a call and press the home button, the call pops up in PIP mode. But when pressing the home button while the phone is locked (the call screen looks the same), the call closes and there is no way to get back to it. It keeps running in the background, but I can't open the call screen again.

### Steps to reproduce
- start a signal call (doesn't matter if audio or video)
- lock the phone
- wake your phone screen and press the home button

**Actual result:** You won't be able to get back to the call screen to hang up or see the other person
**Expected result:** There is a notification or a banner in signal I can tap to get back to the call screen

### Screenshots
![signal-2021-03-30-121247](https://user-images.githubusercontent.com/26956711/112973175-904f9080-9140-11eb-9a25-bf70d9111ed5.jpeg)
Just the normal notifications show up, but no notification about the ongoing call

### Device info

**Device:** Pixel 4a
**Android version:** CalyxOS 2.2.0 (Android 11)
**Signal version:** 5.4.7

**Comment by slaven92** [comment]
You should first check the notification settings for the signal app. You do this in the settings app of the Android, not signal.
Make sure that all notifications are enabled (other notifications settings is also important). Then you will have a notification to get back to call.

_If this does not work_, you can get back to the call by opening the signal app, going to the chat of the person you are currently talking to and then press the call or video button (It is the same as if you want to call them again). This will get you back into the call screen again. 

I hope I made my self clear.

**Comment by chaptergy** [comment]
Ah, that makes sense. I disabled the "Other" channel to remove the background service notification, but it seems this notification no longer exists? If it does, it would make sense to have a separate notification channel for this.
I still think it is useful to have a dedicated "back to call" button somewhere, like almost all messengers with calling capabilities have.
