### ISSUE TITLE
Priority conversations not working on subsequent notifications

### ISSUE THREAD

**Issue by wolfedme** [signalapp/Signal-Android#11151]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Priority conversation settings for notifications are not carried over to the next notification. When setting a notification to 'priority' in the notification's settings, it is correctly shown as such. But as soon, as the next notification of the sender pops up, the notification is displayed as a standard conversation, even though the setting is still enabled in the menu. Resetting does work for the current notification and breaks with the next again.

### Steps to reproduce
- Long-tap a conversation notification
- Mark as 'Priority'
- Wait for the next message
- Message should displayed as non-priority (signal icon instead of avatar, grouped with all non-priority conversations)

**Actual result:** Priority conversations gets displayed as non-priority with subsequent notification after enabling the priority-setting
**Expected result:** Priority conversation gets displayed as priority, until the setting gets disabled.

### Screenshots
---

### Device info

**Device:** OnePlus 8T
**Android version:** 11 (OxygenOS 11.0.7.10)
**Signal version:** 5.5.5

### Link to debug log
https://debuglogs.org/c3b6f734609729749c16acc2761f1446113531378a983683a5270553f13d5f2e

**Comment by AeroEchelon** [comment]
I believe this is also related to https://github.com/signalapp/Signal-Android/issues/10937

**Comment by wolfedme** [comment]
Signal Beta 5.10.2 does seem to fix it partially. I still have to reassign the priority setting occasionally, but not after every screenlock anymore.
