### ISSUE TITLE
Signal Crash Whenever Create or Opening Chat on Android 8.0.0

### ISSUE THREAD

**Issue by amaliahajarani21** [signalapp/Signal-Android#11167]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal app stopped whenever I tried to create or open chat. I installed Signal from Android Studio and cannot create or open message

### Steps to reproduce
- Open Signal
- Create message
- Choose contact

**Actual result:** 
App crash with "Signal has stopped"
**Expected result:** 
Creating new new messages

### Screenshots
![WhatsApp Image 2021-04-05 at 1 58 09 PM](https://user-images.githubusercontent.com/54462906/113567618-23089780-9639-11eb-8362-7069c94fec7a.jpeg)

### Device info

**Device:** Samsung Galaxy A8 Star SM-G885F
**Android version:** 8.0.0
**Signal version:** Signal 5.5.5

### Link to debug log
https://debuglogs.org/708a6a6e777737e67f1105d58743f406a91b2f549e63d5cc09cf112241e6b75f

**Comment by hiqua** [comment]
Does it work with the .apk?
https://signal.org/android/apk/

You're not using the official 5.5.5, according to your log (the top commit is different).

**Comment by amaliahajarani21** [comment]
> Does it work with the .apk?
> https://signal.org/android/apk/
> 
> You're not using the official 5.5.5, according to your log (the top commit is different).

Yes, it works with the .apk. But since I need to debugged it, I downloaded/installed it via the source code with Android Studio because I need it for my assignment.

**Comment by hiqua** [comment]
@amaliahajarani21 please use https://community.signalusers.org/c/development/android-development/22 for this kind of question.

**Comment by amaliahajarani21** [comment]
> @amaliahajarani21 please use https://community.signalusers.org/c/development/android-development/22 for this kind of question.

thank youu

**Comment by cody-signal** [comment]
Closing as development question.
