### ISSUE TITLE
Posting Multiple Photos

### ISSUE THREAD

**Issue by JamesCann** [signalapp/Signal-Android#11165]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Often I will send photos to various people. Often it will post multiple photos I haven't chosen to post but are images from recent messages.

Example : I send photo A, then I may send a new photo but my previous photo is also send with the new one.

This will also happen across conversations. I may send someone a photo then send a diff photo to a diff person but it may include a photo from my previous photo from the other person I dont want to send.

So Km sending stuff to people i dont intend to making it confusing or out of context between people.

### Steps to reproduce
- see above

**Actual result:** 
See above
**Expected result:**
Omly send the photo to the person I intended to send it to

### Screenshots
No screenshots but I assume that's pretty explanatory

### Device info
Pixel 4a 5G
**Android version:** 11
**Signal version:** 5.5.5

### Link to debug log
N/a

**Comment by hiqua** [comment]
Debug log?

**Comment by cody-signal** [comment]
Thanks for the report, debug logs would be very helpful, taken right after experiencing the issue.
