### ISSUE TITLE
Improve battery life by adding notification sync delay option for non-GMS devices

### ISSUE THREAD

**Issue by matteqa** [signalapp/Signal-Android#11166]
Signal uses quite a lot of battery without Google Cloud Messaging installed due to the fact that it is constantly running a WebSocket to check the server for messages.

In Element, I have the option to set a background sync delay so that it only checks the server every few minutes saving battery life. Could something like this be added to Signal as an option to improve battery life?

**Comment by hiqua** [comment]
Unlikely: https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology

There's also the problems of calls: if you don't have a persistent connection, calls will almost never ring on time. If a user has this option activated but forgets about it, they will not receive calls but won't understand why, and just think it's a bug.

It would also be nice to measure how much battery this actually takes. In my experience it was fine, but I guess it depends on the device. Could it be that another bug was inducing more battery consumption than what you expected?
