### ISSUE TITLE
OutOfMemoryError, Android S preview

### ISSUE THREAD

**Issue by cyrusboadway** [signalapp/Signal-Android#11162]
- [✓] I have searched open and closed issues for duplicates
- [✓] I am submitting a bug report for existing functionality that does not work as intended
- [✓] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [✓] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Android 12 preview. App crashes 9/10 times, immediately as I open it.

```
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler: java.lang.OutOfMemoryError: Failed to allocate a 8589934600 byte allocation with 50490000 free bytes and 495MB until OOM, target footprint 67320000, growth limit 536870912
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler:  at java.util.ArrayList.<init>(ArrayList.java:166)
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler:  at org.thoughtcrime.securesms.jobs.ConversationShortcutUpdateJob.onRun(ConversationShortcutUpdateJob.java:76)
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler:  at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-02 22:37:53.096 10286  7798  7846 E SignalUncaughtExceptionHandler:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

### Steps to reproduce
- Immediately on opening the app.

**Actual result:** OutOfMemoryException
**Expected result:** Smooth sailing

### Screenshots
n/a

### Device info
**Device:** Pixel 5
**Android version:** S preview 2
**Signal version:** 5.5.5

### Link to debug log
https://debuglogs.org/35021f17904b84ac8e9b0917771afcb553e650ad2eb6d6d0d405025ce7bef228

**Comment by hiqua** [comment]
It would be nice to rule out a bug from Android. Given that it's not even in beta yet, and that there's at least one more developer preview before the first beta, with a release in August[0], that's a lot of iterations for the bug to possibly resolve itself without any code change in Signal.

Was it happening with S preview 1?

[0]: https://developer.android.com/about/versions/12

**Comment by cyrusboadway** [comment]
I don't recall precisely when it started, so I don't know if it was on preview 1. I'll report back if anything changes.

**Comment by cyrusboadway** [comment]
With a very quick read of the code, the OOM is from [allocating an ArrayList](https://github.com/signalapp/Signal-Android/blob/44d014c4459e9ac34b74800002fa86b402d0501c/app/src/main/java/org/thoughtcrime/securesms/jobs/ConversationShortcutUpdateJob.java#L76) of size [`getMaxShortcutCountPerActivity`](https://developer.android.com/reference/android/content/pm/ShortcutManager#getMaxShortcutCountPerActivity()). Perhaps the `ShortcutService` [is parsing](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/pm/ShortcutService.java;l=732-733) an absurdly high shortcut count. That could be a framework bug, but it might be prudent to defensively cap the allocation size anyway.

**Comment by hiqua** [comment]
8783d150e8f8c6e1b8962e6cce2b65f10587d49d
