### ISSUE TITLE
Deleted messages from android still viewable on Desktop client

### ISSUE THREAD

**Issue by Rhahkeem** [signalapp/Signal-Android#11163]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When deleting messages on the android app, every message is still viewable from the desktop client

### Steps to reproduce
- Send a bunch of messages to a contact
- Select the messages and choose "Delete for me"
- Open the Desktop client

**Actual result:** All the deleted messages are still present and viewable 
**Expected result:** Any deleted messages should no longer be viewable

### Device info

**Device:** Google Pixel 2
**Android version:** 11 Security Update 5 October 2020 
**Signal version:** 5.6.1

### Link to debug log
https://debuglogs.org/cc648bfc0f3b525cb0d68d9bec0813635fce68a6cbdcc4c9d94fded17619fbff

**Comment by Rhahkeem** [comment]
Desktop client is on linux machine. 
version 1.40.1

**Comment by Rhahkeem** [comment]
Seems like this is closely related to 
https://github.com/signalapp/Signal-Desktop/issues/4117

**Comment by WampyCakes** [comment]
I really think you should be able to delete a text from your phone and still have it available on your desktop. There are many reasons for this, one being space. Maybe a better way would be an option "Delete for me everywhere"

**Comment by Rhahkeem** [comment]
Sure it may affect you wanting to use it, but realistically the option "Delete for me" implies it's deleted for me. If "Delete for me" doesn't actually delete it for me, then it's a bug. Rather than add a new option that says "Delete for me everywhere", that should be the default and a new option that says "Delete for me on this device"

**Comment by WampyCakes** [comment]
I don't care which way is default as long as there is a clear way to do either option. It's a very legitimate function to only want to delete on one device.

**Comment by Rhahkeem** [comment]
Ok I can agree with that

**Comment by cody-signal** [comment]
The intended behavior for "Delete for me" is to only delete locally and has been for some time. However, I could see a desire to have something akin to "delete for me everywhere". If the feature is important to you, please [go to our community forum for feature requests](https://community.signalusers.org/c/feature-requests/17).
