### ISSUE TITLE
Unable to create group with beta versions

### ISSUE THREAD

**Issue by djetzen** [signalapp/Signal-Android#11175]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With the newest beta I cannot create groups. Every time I try to create a group I am able to proceed to the screen where I should enter a name, but the button for creating a group is always greyed. Also other people cannot invite me to a group and experienced this issue with some other peoples as well. I still have a company phone where the stable version(5.5.5) is running, where this does not happen. 
Some contacts of mine are not able to create groups, even if they run the 5.5.5 version and only try to invite people with 5.5.5 version. 

### Steps to reproduce
- click on the pencil
- select "create new group"
- add members
- enter name

**Actual result:** 
The button for creating a group is greyed. 
**Expected result:** 
I should be able to create a group.

### Device info
**Device:** Pixel 3A
**Android version:** 11
**Signal version:** 5.7.1

**Comment by tbo15** [comment]
I am seeing this on stable (5.5.5) as well, on 2 separate devices.

**Comment by hiqua** [comment]
Same with 5.5.5. It works with desktop.

**Comment by greyson-signal** [comment]
This should be resolved now. You might have to restart the app first (i.e. dismiss it from the app switcher).
