### ISSUE TITLE
Group issue

### ISSUE THREAD

**Issue by keystrike** [signalapp/Signal-Android#11173]
I transferred Signal to a new phone and it asked if I wanted to upgrade a group I have not used in some time. I clicked yes. It then said some users could not use the newer group and asked if I wanted to remove them. I said yes. Now the group info box shows only 3 members in the group but members who are not shown in the group are sending messages to the group. The group functionality is severely broken.

**Comment by cody-signal** [comment]
Hi @keystrike , thanks for the report. Could you please template provided when submitting your issue. Things like debug logs and device/app version is really important to help us fix issues and without them there's not much we can do.

**Comment by keystrike** [comment]
I believe this is related to #8890 so I will close the issue.
