### ISSUE TITLE
<name prefix> is incompletely shown in messages overview

### ISSUE THREAD

**Issue by Thusid** [signalapp/Signal-Android#11172]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After opening Signal, the \<name prefix\> (from Google Contacts) is incompletely shown (cut off in front).

## Steps to reproduce
- open Signal
- check the messages overview

**Actual result:**  A leading part of the  \<name prefix\> is cut off at the beginning.

**Expected result:**  The \<name prefix\> should be completely shown.

### Screenshots
![Screenshot_20210406-164935](https://user-images.githubusercontent.com/6843821/113732134-9d98ec00-96f9-11eb-833b-241fdab964ef.jpg)

### Device info

**Device:** Pixel 3 XL
**Android version:** 11
**Signal version:** 5.6.3 (Beta tester)

**Comment by tribut** [comment]
The correct resolution to this issue is to show just the first name imho. Showing "Dr: <Message>" for "Dr. Jane Doe" does not make sense.

**Comment by Thusid** [comment]
In my example, "Dr. sc. nat." is shown as "sc. nat."

**Comment by Thusid** [comment]
![Screenshot_20220126-191021](https://user-images.githubusercontent.com/6843821/151235619-d11a9428-f55d-4efd-a4a7-267fa9d8cbbd.jpg)

As of now, the \<name prefix\> is still not shown completely (see current screenshot).
