### ISSUE TITLE
Group update pop-up message blocks the message input field

### ISSUE THREAD

**Issue by mgrobarek** [signalapp/Signal-Android#11176]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When navigating to a group chat that is using the old group version, the pop-up message that asks you to update the group version is positioned over the message input field, making it impossible to write messages in such groups. If you try to click the pop-up away by pressing Continue, you get the choice to force-update the group by kicking out the incompatible users, or you can abort the group update, which throws you back to square one because the pop-up message doesn’t go away.

### Steps to reproduce
- Update to Signal-Android 5.5.5
- Go to a group using the old group version

**Actual result:** The group update pop-up message blocks the message input field.
**Expected result:** The group update pop-up message should be placed in a spot that doesn’t make the group chat unusable.

### Screenshots
![Signal group chat edited](https://user-images.githubusercontent.com/70602401/113849170-80b3f580-9799-11eb-8b2d-e96bb9b2192d.jpeg)

### Device info
**Device:** Shiftphone Shift6m
**Android version:** 8.0.0
**Signal version:** 5.5.5

### Link to debug log
See https://debuglogs.org/7cfe57ebbd43f86d42d7199b122aebee3980f1eee26c4386a5935ffe6aed5012

**Comment by greyson-signal** [comment]
This isn't a bug -- the intention is that the group must be updated to continue. When you click the button, it'll tell you who will be invited and who is no longer capable. Things should return to normal in the group relatively quickly :)
