### ISSUE TITLE
Can't hear me voice message Samsung s21

### ISSUE THREAD

**Issue by xpwd-lab** [signalapp/Signal-Android#11188]
Hello,

I have a friend of mine, who has a Samsung s21, since the last Signal update, when he sends a voice message on Signal, I can't hear it.
The microphone works fine, as he can talk in his videos, and calls work fine with the microphone. 
He has already sent you to the Signal team, several reports via the Help menu in the app.

Can you take care of it? Please do.

Thank you.

**Comment by hiqua** [comment]
Could it be a problem on your device instead? A debug log from you could be helpful.

**Comment by xpwd-lab** [comment]
Here is the Signal debug from my friend who owns the Samsung S21: https://debuglogs.org/d0821086e8e50bc292712a33f443ea557978a8a554ab4d6e3fd59191e0bf3138

Here is my Signal debug from my Samsung Galaxy S20 device: https://debuglogs.org/8df8fd64c84077d5592cf0a960b6aec33ebd010857e78048032019e56d7d7ebe

Before doing the debugs, we have of course, test sending a voice message from my friend's device (Samsung Galaxy s21) and I read it on my device (Samsung Galaxy s20)
I still can't hear it or very little from far, with the volume turned up. And I can hear the end of the voice with the little melody

Here is an excerpt from a voice message sent from his phone (Samsung Galaxy S21):

https://voca.ro/174PTmkFwJr7
