### ISSUE TITLE
please release compiled installer .apk

### ISSUE THREAD

**Issue by juanpc2018** [signalapp/Signal-Android#11182]
please release compiled installer .apk

Using Google PlayStore does Not compute with  "Secure", Free and Private.
Inconsistent, not reflect, not agree, not compartible with...
https://www.powerthesaurus.org/do_not_match/synonyms
https://www.macmillanthesaurus.com/us/something-does-not-compute

Downloading Signal from Google Store is painting a giant Red Bull Target on your ***.
Strange you dont know or dont care...

Maybe Snowden is a covert-op C14, like the other hollywood actor that allowed to catch "El Chapo" Guzman.
And this app is a mouse trap, like Parler.
At least Parler had .apk installer in the web site.

There is No Free and Private anymore, unless you unplug everything... And still ther is 5g facial & voice recognition cameras everywhere...
And deep fake to put your face and voice in any crime they want.

Like the movie: Anon (2018)
https://imdb.com/title/tt5397194/

**Comment by cheriimoya** [comment]
wat? head to https://signal.org/android/apk/ and hit the gigantic download button
