### ISSUE TITLE
Can't create group on Android - 'create' button is greyed out

### ISSUE THREAD

**Issue by samuelkdavis** [signalapp/Signal-Android#11183]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Create Group button is greyed out

### Steps to Reproduce

3 dots -> New Group -> Skip -> type anything -> Create button is greyed out

Actual Result:

Create button is greyed out

Expected Result:

Create button should be accessible

### Platform Info

Signal Version:
5.5.5

Operating System:
android 6.0.1. 

Linked Device Version:
Galaxy s5 SM-G900F

**Comment by hiqua** [comment]
Can you double-check that's still the case? It was an issue that was supposed to be resolved: https://github.com/signalapp/Signal-Android/issues/11175

**Comment by alan-signal** [comment]
Please force close the app and try again, or swipe away from recents. This was triggered by a remote feature flag that won't get picked up until the app restarts.

**Comment by samuelkdavis** [comment]
Seems to be working now, my version wasn't a beta version afaik, but was fixed as part of this. 

Was it this change that fixed it?

https://github.com/signalapp/Signal-Android/commit/33cb02b9e4ab46ad5bd3f6b9c9c34a0698e3e56f

**Comment by hiqua** [comment]
> Seems to be working now, my version wasn't a beta version afaik, but was fixed as part of this.
> 
> Was it this change that fixed it?
> 
> [33cb02b](https://github.com/signalapp/Signal-Android/commit/33cb02b9e4ab46ad5bd3f6b9c9c34a0698e3e56f)

I think it was a change on the server (some dynamic setting), not in the client.

**Comment by samuelkdavis** [comment]
I can't see anything related there:

https://github.com/signalapp/Signal-Server/commits/master

Or do you mean dynamic setting like not committed to code?

**Comment by hiqua** [comment]
> Or do you mean dynamic setting like not committed to code?

This.
