### ISSUE TITLE
Crash at open since upgrade to current beta rollout 5.7.2 on Android 4.4.2

### ISSUE THREAD

**Issue by Trombonista** [signalapp/Signal-Android#11185]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes every time at app start (auto after reboot and manual) since today's update to 5.7.2 (according to system app manager).

### Steps to reproduce
- install current update from beta rollout
- start the app or reboot device

**Actual result:** crashes always. 2nd "Signal terminated" popup after ca. 20 seconds
**Expected result:** app starting, database update maybe, lauch of conversations list

### Device info
**Device:** Samsung S4mini GT-I9195
**Android version:** 4.4.2
**Signal version:** 5.7.2 according to system app manager (can not access Signal app internal version print)

### Link to debug log
Unable to generate debug log, crash happens too early

**Comment by dCosminn** [comment]
Same here, now on version 5.7.3 and still crashing.

Lenovo A328, Android 4.4.2

**Comment by Trombonista** [comment]
I don't know which (working) version was installed before the update. I do updates often, but the last working update was at least a few days before 5.7.2.
The bug applies to 5.7.3 as well.

**Comment by UserX404** [comment]
Since it's a beta feedback you should report issues in the corresponding [beta feedback thread](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-7-release/30836/) in the forum.
Please prepare a debug log (if possible) or a logcat for the devs.

**Comment by Trombonista** [comment]
I have not been aware of that thread, issue "how to" did not mention it if I'm correct. Should I *only* post there or (also no great idea) duplicates? IMO here is an important location for such a severe issue - or what am I missing?
Debug log not possible as I have stated.

**Comment by UserX404** [comment]
Since you were beta-tester the beta feedback thread is the place to report. GH is used for bugs in production release.
So, as Alan mention in his first post (you are right!) please report your issue in the [5.6. beta feedback](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-6-release/30590) thread.

When you are not able to get a debug log devs usually asks for a [logcat](https://developer.android.com/studio/command-line/logcat). Keep in mind there are sensitive data withing this logs and you should search for and remove them.

**Comment by alan-signal** [comment]
Please email me the crash from the logcat if you can, alan@signal.org, or send me a 1:1 on the forum, or if it's just the crash, paste here.

**Comment by wizardofid** [comment]
The 5.6 Beta-Thread is already closed. As it is no payment-related problem, here is the correct location for the report.

**Comment by alan-signal** [comment]
The 5.7 thread is fine. It's clearly a regression, and probably related to payments TBH. I just didn't want the usual wave of preexisting bugs.

**Comment by Trombonista** [comment]
Hi all! You all seem to be right with your views regarding issue ticket placement to some extent IMO. No problem, I was just a little confused, because to me github-issues seemed to be the obvious landing page for a github-hosted project, but of course discussion of current beta stuff in the thread makes a lot of sense too - so I later posted this GH-issue to the 5.7 beta thread.
I just saw Alans log request and am pleased to see it being fixed already, would have taken some while for me to (hopefully) provide some log. Now looking forward for shipment of the fix.

**Comment by alan-signal** [comment]
We were able to reproduce and fix in 5.7.5 now in beta and on firebase, thanks for the report!

**Comment by Trombonista** [comment]
Thank you for the information. Looks like a nasty bug and the workaround looks a little strange to me - but if it works...
Well we all learn something every day. I am used to C++ development but not to Android/Java, interesting to read though.
Btw. "desugaring" looks like (selective) static compilation to me with my "old" wording.

**Comment by alan-signal** [comment]
> the workaround looks a little strange to me

And to us!
