### ISSUE TITLE
Off-Topic: Signal-Server has no issues board

### ISSUE THREAD

**Issue by casaper** [signalapp/Signal-Android#11184]
Can you please open the issues board on the [signalapp/Signal-Server](https://github.com/signalapp/Signal-Server), because it is currently not existing. Thx.

**Comment by hiqua** [comment]
It's by design.

**Comment by casaper** [comment]
By design not having any issues?

**Comment by casaper** [comment]
@alan-signal 

By design being a closed siurce project actually?

By design only updated once in a year?

**Comment by casaper** [comment]
Considering signal being a communication tool, the communication arround it isn't very convincing... ¯\(°_o)/¯

**Comment by alan-signal** [comment]
@casaper I did not write "by design" that was another member of the public.

I closed because it was not a bug report for Signal Android.

Please use the community forum to discuss more https://community.signalusers.org/

**Comment by alan-signal** [comment]
> By design being a closed siurce project actually?

If that is your complaint, please see:

https://github.com/signalapp/Signal-Android/issues/11101#issuecomment-815400676

And also you will find community threads on the forum related like this https://community.signalusers.org/t/where-is-new-signal-server-code-why-not-share-signal/15068.

**Comment by casaper** [comment]
@alan-signal 

Fair enough. [That was the comment me and others were waiting for.](https://github.com/signalapp/Signal-Android/issues/11101#issuecomment-815400676)

The comment you mentioned did not exist at the time, and in the meantime I was getting a bit frustrated because some rather paranoid tinfoil hat discussions seemed to have started to take of there but it being closed did not leave any room to disagree and disassociate with that kind of thing :wink:
