### ISSUE TITLE
Speaker audio does not work during video chat

### ISSUE THREAD

**Issue by KaypieCode** [signalapp/Signal-Android#11194]
Dear Signal Team,

When I'm connected to a Bluetooth device during a video chat (SmartWatch with a small speaker), I'm presented with two audio output options:
- the Bluetooth device &
- "Speaker"

However, "speaker" is then no longer the speaker, but just the earpiece on top of the phone. Without a Bluetooth connection, however, it works fine.

**Comment by minnmann** [comment]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As described above, the speaker does not work correctly in a video call. 

While there are some other issues that are similar (https://github.com/signalapp/Signal-Android/issues/10744, https://github.com/signalapp/Signal-Android/issues/9796), this is the only one that explicitly mentions a connected Bluetooth device. If the Bluetooth device is not connected, everything works as expected.

### Steps to reproduce
- Have a Bluetooth device connected (in my case a smart watch)
- Answer an incoming video call

**Actual result:** Earpeace is used for sound. If camera is deactivated and activated again, speaker is used. In another call, I could not get it working after several tries. 
**Expected result:** Speaker is used for sound from the beginning.

More info: 
For the call on 2021-04-16 at 21:50, I could not get it to work after several tries.
For the calls on 2021-04-17 at ~13:00, I could fix the problems by deactivating and activating the (outgoing) video.

### Device info
**Device:** Pixel 4
**Android version:** 11
**Signal version:** 5.8.6

### Link to debug log
https://debuglogs.org/6d5a63dcf440d96eb72a584db78427c4dd9f6d1800034dcd5cd6af92792b84b9

**Comment by Andar1911** [comment]
It is also happening with me. I also used to be able to force it by disabling outgoing video and re-enabling it but that stopped working within the last week or two.
I can't change the audio output to the bluetooth speaker either.

Device info:
Device: Pixel 4 XL
Android version: 11
Signal version: 5.7.6
Samsung Gear S3 smart watch

https://debuglogs.org/19aa83abea8682df66d4576d3672f9c28357633a5e21ef9fd10a47af1e61afba

https://debuglogs.org/d838f40744de959e4dcbc43eecc2563d164243edeb73410780df1f8f456f1948

**Comment by lengthofrope** [comment]
I can also confirm this issue with the latest TicWatch Pro and the Pixel 3a XL.
Disabling en re-enabling the video stream has stopped working. I can only get it to work by completely disabling bluetooth if a (video)call comes in.

**Comment by cody-signal** [comment]
Please try out the latest beta, we have improved the audio routing for calls.

**Comment by Andar1911** [comment]
As of 5.24.13 it works. I have to manually switch to speaker output each time, but that's a lot better than having to turn off Bluetooth and then turn the camera off and on and then remembering to turn Bluetooth back on after the call.

Thank you for fixing this.

Debug log attached just in case it's needed.
https://debuglogs.org/922bde3e0910f748653f4d522df9c29041928cc520aaae0a43f053ab9b6772c5
