### ISSUE TITLE
Wallpaper doesn't rescale properly on orientation switch

### ISSUE THREAD

**Issue by sivaraam** [signalapp/Signal-Android#11197]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening a chat in landscape mode and switching orientation, the wallpaper doesn't rescale accordingly. The rescale of walpaper when switching from portrait to landscape and back to portrait works fine, though.

### Steps to reproduce
- Open Signal
- Switch to landscape
- Open a chat
- Switch to portrait

**Actual result:** Wallpaper appears badly oriented for portrait.
**Expected result:** Wallpaper appears properly oriented.

### Screenshots

![Screenshot_2021-02-20-16-07-33_1](https://user-images.githubusercontent.com/12448084/114307587-fef7fb00-9afd-11eb-8f16-7debc8a2c2a6.png)

### Device info

**Device:** OnePlus Nord
**Android version:** 11
**Signal version:** 5.7.5

**Comment by supriya-pd** [comment]
I would like to work on this issue, is anyone working on it?

**Comment by sivaraam** [comment]
This one still occurs.

**Comment by sivaraam** [comment]
Tested in 5.34.4. Seems like its fixed.
