### ISSUE TITLE
received image fails to render, log says java.io.FileNotFoundException

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#11199]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just got sent 4 images where one of them failed to render, even when sending them each by each the same image failed to render and only showed a blurry background, the image clipart with a red exclamation mark sign.

### Steps to reproduce
- I actually don't know how to reproduce. Maybe it's something with the image but it renders fine on the sending device 

**Actual result:** 

image fails to show 

**Expected result:** 
image should show or lead to an error message on the sending side before sending

### Device info

**Device:** Google pixel 5
**Android version:** 11.0
**Signal version:** 5.7.5

### Link to debug log
https://debuglogs.org/17195ec2844376406c4329d85fede70361c5c2e37aa5231340a45080f37db767

**Comment by Epse** [comment]
I have the same situation on a Moto G6, occured on Android 10 and now still on 11.
