### ISSUE TITLE
Min. phone-number-length=5 for sending text to new recipient is too long

### ISSUE THREAD

**Issue by sirtet** [signalapp/Signal-Android#11192]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I try to send a SMS to a service-number like 414 but the option "send text to 12345" (actually for me: "Neue Nachricht an ...")
only appears after entering at least 5 digits.
(I found out, the workaround is to enter a country-code first, but from a user-view, i still consider this as a bug.)

### Steps to reproduce
- use the button to send new SMS
- enter 12345
- only after the 5th digit the option to send a text shows up

### Device info
Samsung
Android 11
OneUI 3.1
Signal 5.6.4

**Comment by hiqua** [comment]
I have the option as soon as I type one digit. Example with 4 digits to avoid showing my contacts.

Android 10
Signal 5.6.4

Can you send a screenshot of what you mean, since we seem to have different results?

![signal-2021-04-11-104544](https://user-images.githubusercontent.com/3812042/114297806-178ef380-9ab3-11eb-8a52-c489dcf6c197.png)

**Comment by sirtet** [comment]
Sure, here they are.
(I updated the device info in the original Post, my device is on Android 11, not 10 as initially reported.
)
![image](https://user-images.githubusercontent.com/3509308/114300427-93dc0380-9ac0-11eb-8df0-e98b8d7180d8.png)

![image](https://user-images.githubusercontent.com/3509308/114300444-a8200080-9ac0-11eb-9c4e-a3158575a279.png)

**Comment by Sgn-32** [comment]
You can scroll down the contact list. At the end you will find "New message to"/"Neue Nachricht an".

**Comment by sirtet** [comment]
Ah, that's what happes...
If u type fast or matching contacts are reduced fast, 
as soon as there are no more hits in the contact list, it looks like the option is added at top.
but it actually is the matching contacts being reduced to zero that create that impression.

So the solution would be to have the two lines "new message to..." and "invite to signal" before the contact-matches.

**Comment by hiqua** [comment]
> So the solution would be to have the two lines "new message to..." and "invite to signal" before the contact-matches.

This would help for this use case, but it would be worse overall. The SMS feature of Signal is nice, but it's only meant to help people migrate, Signal messages should still have the priority.

The real workaround for you is to add this number to your contacts, then search by name rather than by number when you want to send a text message.

If it's just a one-off, then scrolling to the bottom is also not that bad.

**Comment by sirtet** [comment]
1. I don't see how this would worsen anything other than 2 contacts less in the initial viewport.
2. Service-numbers will never migrate to Signal.
3. Workarounds? Let's try to avoid these. But yes, prefixing a country code is another one.
4. Actually, another way might be that hitting ENTER on the Keyboard would continue to the SMS-composition step, instead of currently just hiding the keyboard.
But maybe there's another good reason to not change this current behaviour too?

I see the SMS-Feature as more than a transition tool: 
It lowers the barrier for users who say "i don't want two messaging apps".
With signal, you get safe comms without the need to have different apps for the same tasks.
This is why i think the SMS Feature should be a smooth as possible too.

So, the problem i see is: 
People do switch to Signal, use the sms-feature, and when they need to query a service number, they get angry about Signal, because they don't see how to do it and dont want to research a workaround. So this is harming Signal's Mission, IMHO.
Signal's success comes in big part from compromising some safety for usability, and this would be a usability improvement where i don't see much negative impact, so i guess it's worth discussing to find out actual negataive impacts.

**Comment by sirtet** [comment]
Yes, the points made [above](https://github.com/signalapp/Signal-Android/issues/11192#issuecomment-817595006) are still relevant.
There's even another argument for the suggestion to have "write to..." and "invite...." above of phonebook matches:
Having "invite..." as prominent as possible helps signal attract new users.

>  Is there anything you can do to help move it forward?

Not sure, maybe this issue should be closed and another one opened with a better Title? Or change the Title?
Something like
Recipient selection UI: Move "Write to..." and "Invite..." from beleow to above Phonebook-matches
