### ISSUE TITLE
Group update pop-up message blocks the message input field (mobile AND desktop)

### ISSUE THREAD

**Issue by mgrobarek** [signalapp/Signal-Android#11193]
- [X] I have searched open and closed issues for duplicates (see below)
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In group chats using the old group version, the pop-up message that asks you to update the group version is positioned over the message input field, making it impossible to write messages in such groups. For groups like ours that have users like me that aren’t capable of switching to the new groups, this effectively means they are excluded from group chats altogether.
Oddly, users with outdated Signal clients don’t get this message and can still post in old groups, creating the paradox situation that an old client has an advantage over a newer one.

Please note that I’m fully aware that I’m basically posting a duplicate of (my own) issue 11176. I’m opening this new one because the whole thing is obviously a regression. Previously it was **never** mandatory to update a group: the pop-up appeared on the top of the screen and you could just click it away, which was fine and which is what should be restored IMHO.
The pop-up blocking the input field is not only unnecessary but it nudges people into unnecessary action as well, since the (old-versioned) group just works fine for everyone, and we can perfectly live with not updating it. That group has a good reason for sticking with the old version: there are users like me whose phones are too old for recent Signal versions and thus are stuck with old ones, and yet we want to include them in the group chats. As I said, this has been working perfectly fine, only the pop-up placement is the problem.
If there is actually a _technical_ reason to put the pop-up there, please explain it to me, because I fail to see one and there was none given in either the FAQ or the Signal blog. If there is some kind of roadmap regarding the group migration, it would be (or, at this point rather: have been) nice to make that official and visible for the sake of transparency and preparation.

To be perfectly clear: I’m not seeking support for my outdated Android phone or its outdated Signal version. I’m asking you to fix the regression so that old groups can chat again.

### Steps to reproduce
- Update to a recent mobile or desktop version of Signal
- Go to a group using the old group version

**Actual result:** The group update pop-up message blocks the message input field for everyone. Reacting to messages with emojis or replies isn’t possible.
**Expected result:** The group update pop-up message should be placed in a spot that doesn’t make the group chat unusable. Reactions should work again as before.

### Device info
**Device:** Fairphone FP1U
**Android version:** 4.2.2
**Signal version:** 4.36.2 (the last one supported on Android 4.2)

**Comment by greyson-signal** [comment]
Hi there, this is not a regression. This is the intended behavior moving forward. We have new "v2" groups that everyone is being migrated to. Besides v2 groups having things like better state management, group links, and admin roles, "v1" groups have an unfortunate property where membership lists are based on phone numbers. Meaning as long as they exist, it is impossible to create a system where people can use Signal without sharing their number (or without someone else unknowingly sharing their number through a v1 group update). As a result, we are fully deprecating them, making them unusable.

The version of Signal you're using is over two years old at this point. I really am sorry, and I know it's frustrating, but according to the Play Console, you're one of only a couple dozen or so people who are using a version this old. We unfortunately can't continue to support it. We did put a banner at the top saying that your version of Signal will no longer get updated, and over time your version of the app is going to become less and less functional.

According to Wikipedia, your Fairphone 1 does have an unofficial update to 4.4 available to it, which will get you back on track to get updates. I hope you are able to do so!

https://en.wikipedia.org/wiki/Fairphone_1

**Comment by ralphstone1** [comment]
- ![image](https://user-images.githubusercontent.com/62073582/119001025-9ea87480-b959-11eb-85ab-5176532bbeb3.jpeg)
