### ISSUE TITLE
Message typed is being dropped if a message for a group-chat comes in while typing

### ISSUE THREAD

**Issue by t-reyerf** [signalapp/Signal-Android#11190]
[X]  I have searched open and closed issues for duplicates
[X]  I am submitting a bug report for existing functionality that does not work as intended
[X]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
[X]  This isn't a feature request or a discussion topic

**Bug description**
When during the typing of a message to a direct contact in the app another message with a destination to a group chat is received, the message being typed is dropped and the app returns from the typing screen to the start screen (overview of all chats). Everything which has been written is lost.

**Steps to reproduce**
1. Start writing a message to a direct contact
2. Recieve a group-chat-message while typing

**Actual result:** The message being typed is lost and the app returns to the start screen.

**Expected result:** The message being typed is kept and not influenced by the incoming message. The user can continue typing.

**Device info**
Device: Motorola G7 Plus
Android version: 10
Signal version: 5.5.5

Link to debug log
https://debuglogs.org/e6bd2c9868ded79d56f14a76fa140f4bf0db9873cec5042ba2fdd556a860ec11

**Comment by cody-signal** [comment]
Thanks for the report and debug logs. Looks like the app is crashing. Does this happen with only MMS group chats? If you have a signal group and get a message in that group does it crash as well?

**Comment by t-reyerf** [comment]
Thank you for your fast response. It only happened while typing a message and receiving a group-chat message simultaneously. If the group chat is opened while receiving or if i am not typing while receiving, the app does not crash.
