### ISSUE TITLE
Unusually long ANR and crash upon openning group chats after each cold start

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#11200]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening a group chat after the app cold starts causes a long ANR and sometimes a crash.

### Steps to reproduce
- Cold start Signal
- Open a group chat right after

### Device info

**Signal version:** 5.8.0

### Link to debug log

https://debuglogs.org/9975a2ffecf0bf1f095eed1ad5afd118448affc4c796ed8babae68f5eaf9692c

**Comment by Xashyar** [comment]
I'm still able to reproduce this 10/10 on the latest **v5.10.0**:

https://debuglogs.org/9a6bd2bbef6bc81a95403bbab8198ef4885b6f07d42fa0aa2a9f7f8dea2ec89e

**Comment by Anti-ctrl** [comment]
Do you experience slow sending messages in the Group chat too ? So, that it takes a few seconds/Minutes till the first tik of a message is shown, even tho your connection is fast?

**Comment by Xashyar** [comment]
This is still reproducible.
