### ISSUE TITLE
Crash when pasting image into message input

### ISSUE THREAD

**Issue by davidtakac** [signalapp/Signal-Android#11206]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When pasting an image into the message input box, the app crashes. Possibly related to #10813 

### Steps to reproduce
- take a screenshot
- go to any Signal chat
- long click the message input box
- tap "Clipboard"
- tap the screenshot

**Actual result:** The app crashes
**Expected result:** One of the following
1. the user is notified that this isn't possible
2. nothing happens
3. the image gets added as an attachment (not sure if possible/appropriate)

### Screenshots
N/A

### Device info
**Device:** Samsung Galaxy S8 SM-G950F
**Android version:** 9.0
**Signal version:** 5.6.4

### Link to debug log
https://debuglogs.org/b981935cd790585e6830d8ac1fb7f54abaf52033df51f8ea01a3bf890856e56b

**Comment by davidtakac** [comment]
I tested this behavior on Facebook Messenger, WhatsApp and Discord. Messenger immediately sends the image, WhatsApp displays a "File format not supported" toast and Discord adds the image as an attachment. Also, this is probably a Samsung-only thing, since stock Android doesn't have a clipboard manager. 

The crash is caused by this method: https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaSendFragmentPagerAdapter.java#L41 because the vendor-specific image MIME type `vnd.android.cursor.dir/image` is not checked for in `MediaUtil.isImageType`. This leads to the `UnsupportedOperationException` which crashes the app. 

After adding the check to the method, the image from the clipboard is opened inside of the image editor and it can be sent normally (expected result 3 in original post). However, `MediaUtil.isImageType` is used 30 or so times across the app, so I am not sure what consequences it may have. 

Should we go for expected result 3 like Messenger and Discord, or 1 like WhatsApp? Personally, I think 1 is more robust, because the vendor-specific MIME types are subject to change and it would be hell to keep track of all of them. Users can still add screenshots by selecting them from storage.

**Comment by Sgn-32** [comment]
in 5.13 beta there is a commit about "Support pasting of images into input text."

https://github.com/signalapp/Signal-Android/commit/c08199659b561d784490fd7cb8297ab575197f57

**Comment by greyson-signal** [comment]
Yeah, I *think* this should be fixed in 5.13. Re-open if not. Thanks!
