### ISSUE TITLE
Screen Lock: app crashes after entering passphrase

### ISSUE THREAD

**Issue by gnurpsnewoel** [signalapp/Signal-Android#11215]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open my Signal app and enter the passphrase for screen lock and press ok/submit, the app returns to the screen "Signal is locked. Tap to unlock" but after a short second crashes and closes, instead of unlocking and opening.
I have enabled Signal's screen log feature with passphrase authentification. I put 00:15:00 as time setting. It happens when I enter my Android unlock start screen password.

### Steps to reproduce
- enable Signal's screen lock feature, choose passphrase as st, and set time to 00:15:00
- close Signal, open Signal, see the screen "Signal is locked. Tap to unlock"
- tap, enter passphrase as in Adnroid's start screen unlock, press okay / submit

**Actual result:** The app crashes after entering screen lock passphrase and pressing ok, Signal does not open.
**Expected result:** The app unlocks and doesn't crash after entering screen lock passphrase and pressing ok, Signal opens and the list of conversations / standard start screen of the app becomes visible.

### Screenshots

![20210416_163252](https://user-images.githubusercontent.com/82660750/115040481-c6776900-9ed1-11eb-8e95-7476cd7b11d7.png)
![20210416_151618](https://user-images.githubusercontent.com/82660750/115040504-cbd4b380-9ed1-11eb-8584-7ae3fc6906f7.png)

### Device info

**Device:** Samsung A310F (A3-2016)
**Android version:** 7.0
**Signal version:** 5.7.6 for Android 

### Link to debug log

https://debuglogs.org/321d6c92933e29b71fb49c27a27bcaba5d5fe4772e3931a49e7d407638332c01

**Comment by cody-signal** [comment]
Please try a recent build, some fixes were made for this, sorry it took so long.
