### ISSUE TITLE
User is not registered error.

### ISSUE THREAD

**Issue by Netscaping** [signalapp/Signal-Android#11210]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Only a few of my contacts show as signal users, while in reality all of them use signal. And they can't see me as a signal user too.

### Steps to reproduce
- Install signal
- Register an account
- Only a few contacts show as signal users.

**Actual result:** Only a few contacts show as signal users.
**Expected result:** Everyone show as signal users.

### Device info

**Device:** Nokia 6.2
**Android version:** 10
**Signal version:** 5.7.6

### Link to debug log
https://debuglogs.org/e347298d1eccafa27cbd1c60aaafa4e7e9eadb757058bd9b704c0e26a3d0b152

**Comment by Sgn-32** [comment]
Have you checked that the phone numbers of your contacts using the country code?
https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts#android_contacts_edit_number

**Comment by Netscaping** [comment]
Yes, I have the correct country code in all of my contacts entry. I also tried refresh the signal contact list, reinstalled the app, unregistered and registered the number again, tried refreshing using wifi and mobile data, cleared data and cache etc.....
But none of it worked. Also as I've written my contacts can't see me in the signal list too, so they can't write me.
I've seen some threads on reddit about such problem too.

**Comment by Netscaping** [comment]
Nvm it fixed itself after a few days and multiple account deletions(?!).
