### ISSUE TITLE
Random "XYZ is on Signal!" when they're clearly not.

### ISSUE THREAD

**Issue by Chinoman10** [signalapp/Signal-Android#11211]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Random "Locked Message" notifications that supposedly just say: "Contact XYZ is on Signal!";
The thing is... they're not! On multiple occasions, I've called these people and they've never even heard about the app.
For most of my contacts, especially friends and family, I'm their "go-to IT person", so I'm pretty darn sure they would ask me if it's OK or safe to move from WhatsApp/Telegram/Messenger/whatever to Signal since they've done exactly that previously on other occasions. However, I see complete non-technical people pop up (and I'll say it again, I've confirmed with them and they've never heard about Signal) in my notifications.

### Steps to reproduce
- can't really reproduce it myself... it just happens randomly, it seems?

**Actual result:** Random message about my contacts supposedly joining Signal (and they haven't).
**Expected result:** Only get the notification if they indeed have already joined Signal.

### Screenshots
I don't have the notification right now, but you can see my chat list...
*[redacted]*

### Device info
**Device:** One+ 6T
**Android version:** 10 (Oxygen 10.3.9)
**Signal version:** 5.8.3

### Link to debug log
https://debuglogs.org/480377deea5a18f44c54c9efb71c9931a067b6e277d763121c925a26c01c5c97

**Comment by Chinoman10** [comment]
Hello @greyson-signal, I thought the screenshot could pose a privacy problem, but I thought it would be best to include it anyway since I was just exposing my contact list names.
In any case, I've sent some messages to some of them, to see if it was being delivered, or whatever, and looks like they're sent but not delivered (there's only one ☑️ ).

**Comment by greyson-signal** [comment]
If you're getting a single checkmark on your message, that means the server accepted it, meaning we think that number corresponds to a registered user. They may not have the app installed, but they are registered. Are you 100% sure this person has never installed the app ever, and that they're phone number was not used to register by anyone else?

**Comment by Chinoman10** [comment]
Hello @greyson-signal , most of these people are not tech-savvy at all, and they come to me for tech questions.
It was already a nightmare to move them from Messenger to WhatsApp, and I'm in no position (mentally speaking) to endure having to push yet another app into the family...
While I can't of course be 100% certain that **all** of them (we're talking like 20-30 people) never installed Signal by mistake, I'm confident enough to assume there's an issue somewhere.

Is it possible that someone is mass registering users for known/captured phones from marketing lists and whatnot?
I don't recall, but I guess Signal requires an SMS verification? If that's the case then mass registration wouldn't _really_ be possible (unless there was a loophole somewhere, or a vulnerability somewhere).
