### ISSUE TITLE
FLAC playback completely broken

### ISSUE THREAD

**Issue by chiraag-nataraj** [signalapp/Signal-Android#11217]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Something recorded with an external recording app and attached as a file ends up not playing. File format details are listed below in "Steps to reproduce".

### Steps to reproduce
- Record something using [Audio Recorder](https://gitlab.com/axet/android-audio-recorder) with the following settings: "Recording Source": Unprocessed; "Sample Rate": 48kHz; "Encoding": .flac; "Audio Channels": Stereo; All filters disabled; No encoding on the fly.
- In Signal, hit the "+" -> "File" button, navigate to where the recording is stored (e.g. `/sdcard/Android/data/com.github.axet.audiorecorder/files/recordings/<x>.flac`.
- Hit the send button (no text).
- Note that you cannot play the sent message. Desktop can play it fine, but it seems it might be broken on the receiving end for Android as well. iOS might be able to play it as well.

**Actual result:** Unable to play audio.
**Expected result:** Audio should play.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 5.7.6

### Link to debug log

https://debuglogs.org/e9c974c3fba4097af9143d463313b69aed309c6271efead0e462c86309ff3793

**Comment by chiraag-nataraj** [comment]
Just as an update: It seems that even more 'standard' (aka 44.1kHz, 16-bit) FLAC files are completely broken on Android and cannot be played. Desktop supports these files and iOS might (I don't have an iOS device to test). This is a severe bug that is hampering usability.

**Comment by Xashyar** [comment]
Related: #8761

**Comment by hebu** [comment]
Same issue on Huawei P10 Lite with Android 8.0.0 and Signal 5.27.13.

Whenever I send a .flac audio I cannot play it back, although the recipient might be able to play it (maybe the recipient is using a different version/OS).

**Comment by hebu** [comment]
Is there a test phone number I can send a message to in order to reproduce the bug?

**Comment by hiqua** [comment]
@hebu Note to Self? You can also create a group with no one else.

**Comment by hebu** [comment]
@hiqua Oh yes, I totally forgot about that note-to-self feature :-D

**Comment by hebu** [comment]
Yes, the bug still exists: I sent a flac via SIgnal to myself and when the audio is played back, it is silent.

**Comment by Xashyar** [comment]
Reproducible.

**Comment by Xashyar** [comment]
reproducible.

**Comment by cody-signal** [comment]
To be honest crew, I'm not sure this is something we'll take on. If someone has a clean way to support this please open a PR and tag me on it.

**Comment by hebu** [comment]
It's still reproducable.

**Comment by Xashyar** [comment]
Still reproducible.

**Comment by Xashyar** [comment]
Still reproducible.

**Comment by greyson-signal** [comment]
I'm going to close this as 'not planned'. We use exoplayer, the best media playback library available on android, to play audio files. If it can't play flac's properly on some devices, I don't see us writing custom code or importing ffmpeg or something to fix this.

**Comment by hebu** [comment]
But isn't it curious that the FLAC recording could be played back on the recipient's side while on the sender's side the playback is running, but silently? I can't imagine that it is an issue with the audio library, but maybe with the playback parameters?

**Comment by nicholas-signal** [comment]
> But isn't it curious that the FLAC recording could be played back on the recipient's side while on the sender's side the playback is running, but silently? I can't imagine that it is an issue with the audio library, but maybe with the playback parameters?

Exoplayer will defer to the device's native implementation, as provided by the manufacturer. FLAC support varies by device, so in this situation it would appear that the sender's device does not properly play back FLAC files.

When it comes to how Signal treats the files, it will send along the data you ask, *without* checking compatibility with your own device. It is then up to the device, at playback time, to correctly render it.
