### ISSUE TITLE
Signal removes contacts from system list

### ISSUE THREAD

**Issue by vascotenner** [signalapp/Signal-Android#11222]
Since today, signal ask for my chats if I want to share my name and picture with the contact in the chat. When I approve, signal removes that contact from my system address book. The contact is still available in signal. When clicking in signal on Add to system list, it is back in the system list, however, email address and other contact details are lost.

Issue on:
signal 5.7.6

Log: https://debuglogs.org/d4e60763c1f502ac83721ff5472a7a1a3ccf11a8a40d05770afb8bae3d5cb2b1

**Comment by greyson-signal** [comment]
Like the contact is removed from your system contacts app? Signal can't really do that :/

**Comment by vascotenner** [comment]
I was also very suprised that i could not find the number my girlfriend anymore in my address book anymore :(

Greyson Parrelli ***@***.***> schreef op April 22, 2021 2:08:43 PM UTC:

**Comment by vascotenner** [comment]
Today this happend again for another contact: when signal asks to share my name and picture, the contact is already disappeared from the address book. 

How to debug this issue?

**Comment by vascotenner** [comment]
It seems that all my contacts that had signal are removed from my address book. Could it be something todo with linked contacts, that signal replaced in a the last update all its contacts to a signal address book in order to enhance privacy and by that action removed also the linked contacts?

**Comment by landry314** [comment]
signal's contacts keep getting deleted for me recently. i am always refreshing the contacts. it is super annoying.
