### ISSUE TITLE
Signal randomly removed me from a group

### ISSUE THREAD

**Issue by kyleedwardsny** [signalapp/Signal-Android#11227]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal randomly removed me from a group chat. It said "You are no longer in the group." and I was not able to send messages. One of the members told me that I was still in the group on their end. After they removed and added me back to the group, I was able to post and receive messages again.

### Steps to reproduce
Unknown

**Actual result:** Randomly removed from group
**Expected result:** Should not be randomly removed from group

### Screenshots

![signal_group_screenshot](https://user-images.githubusercontent.com/7741429/115646537-55c8b600-a2f0-11eb-92d4-5408e329700e.png)

### Device info

**Device:** LG G8X
**Android version:** 10
**Signal version:** 5.7.6

### Link to debug log
https://debuglogs.org/c6d12b7b52a3fc4a7d6d96e960ca9351a5c55857089053a8fe68abccce14d2f8

**Comment by AntoineMurat** [comment]
I have the same issue with 2 group chats.
The phenomenon appeared consecutively in both of them. In at least one of them it happened after sending a message. Other chats (including group ones) are just fine.

As I wasn't removed/re-added from them, I still experience issues:
* "You are no longer in the group" randomly appears,
* The text input randomly disappear,
* Some messages I send fail (and sending them again doesn't help),
* Some messages are never delivered to me.

Intermittently, the groups work.
I'm using the Linux app and no issue there. :)

Device: X Compact
Android version: 8.0.0
Signal version: 5.9.6
