### ISSUE TITLE
App constantly crashes a few seconds after opening with "Must have either a UUID or a phone number" assertion

### ISSUE THREAD

**Issue by agret** [signalapp/Signal-Android#11228]
App constantly crashes for me a few seconds after opening due to this assertion

https://github.com/signalapp/Signal-Android/blob/763aeabdddcbeff526589afa964d61defdd3e589/app/src/main/java/org/thoughtcrime/securesms/storage/StorageSyncModels.java#L91

Can you please add proper error handling for this issue so it doesn't kick me out of the app? One invalid contact should not be crashing out the entire app. I can briefly use the app for a few seconds sometimes before it crashes to try and read new messages but I have no way of replying to anything until this gets fixed.

Debug Log:
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6849
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: java.lang.AssertionError: Must have either a UUID or a phone number!
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:91)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.buildStorageUpdatesForLocal(StorageSyncHelper.java:146)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.performSync(StorageSyncJobV2.java:372)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.onRun(StorageSyncJobV2.java:181)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
> 04-20 09:52:16.779  6849  8866 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 2069
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: java.lang.AssertionError: Must have either a UUID or a phone number!
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:91)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.buildStorageUpdatesForLocal(StorageSyncHelper.java:146)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.performSync(StorageSyncJobV2.java:373)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.onRun(StorageSyncJobV2.java:182)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
> 04-22 14:28:17.556  2069  3339 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: java.lang.AssertionError: Must have either a UUID or a phone number!
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:91)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.buildStorageUpdatesForLocal(StorageSyncHelper.java:146)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.performSync(StorageSyncJobV2.java:373)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJobV2.onRun(StorageSyncJobV2.java:182)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
> 04-22 14:28:17.556  2069  3339 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

**Comment by agret** [comment]
If you need help debugging this I'll help out however I can. Really need this fixed ASAP. Is there any way to get more info dumped into the logs?

**Comment by NigelGoldenfeld** [comment]
I would like to upvote this issue.  I am also experiencing the same problem.  It makes the app unusable, even trying to block the user and delete the conversation did not work.

**Comment by agret** [comment]
I somehow managed to get into the app tonight, here is my debug log

https://debuglogs.org/ca001e68e100f1426de4e7161a6b8f148da3c01684ac53c882f92ce2eab5641c

**Comment by agret** [comment]
This was possibly fixed by this commit for 5.9.3

https://github.com/signalapp/Signal-Android/commit/5e715ffcce95bf82f17aced450b239275d672cbf

**Comment by NigelGoldenfeld** [comment]
Thank you for letting me know.  I was hoping that would be the case, will try.
_________________
Nigel Goldenfeld

Sent from my phone via UIUC. Please excuse my brevity.

Disclaimer: This email represents research materials, preliminary drafts, notes, recommendations, memoranda and other records in which opinions are expressed, or policies or actions may be formulated, and is purely pre-decisional. Under the Illinois Freedom of Information Act (FOIA), any written communication to or from University of Illinois employees regarding U of I business is a public record and may be subject to public disclosure.

**Comment by greyson-signal** [comment]
Hi there, hopefully 5.9.4 fixes this issue for you based on your log. There will also be additional improvements to prevent your situation in 5.10.x
