### ISSUE TITLE
Intermittent echo heard even with loudspeaker turned off

### ISSUE THREAD

**Issue by mr-brunes** [signalapp/Signal-Android#11225]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Caller's voice after a short delay (about 0.5s) is heard by caller. 

### Steps to reproduce
Intermittent issue, there appears to be no reliable way to reproduce it.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Turning off the callee's loudpeaker i.e. to use the normal earpiece, helps a little but the echo is still clearly heard by the caller and still makes the call impossible to continue. Caller hangs up, calls the callee again and this time there is no echo.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
No echo is heard on a subsequent call immediately afterwards.

### Device info

Caller Samsung S10e SM-G970F
Android 11
Signal version 5.9.0

Callee Samsung S7 SM-G930F
Android 8.0

### Link to debug log

Callee https://debuglogs.org/fb1c65cfa577633113dd35dd2618d26d713b306b600ab1ea10deea8242e0e0eb

Caller https://debuglogs.org/2096be499c5af1b30cb3b627b957c3ca04185d5d97845887ffd4c7983fcae9ab

First call around 10:50 21-Apr-21 has echo, second call immediately afterwards has no echo.

Callee Android bug report sent to greyson-signal.

Other echo related bug reports seem to be consistent issues with certain phone models, but this is intermittent, hence a different bug report.
Caller and callee phones have not experienced an echo when using normal Phone Dialler or Whatsapp.

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
