### ISSUE TITLE
Crash when opening bubbled conversation

### ISSUE THREAD

**Issue by thefirstofthe300** [signalapp/Signal-Android#11224]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I bubbled a conversation on my Android phone. When I received a message in that conversation and attempted to open the bubble by clicking on the bubble (not the notification), the bubble disappeared and the message never opened. I had to open the app and click on the conversation to view the message.

### Steps to reproduce
The issue is intermittent and I haven't been able to reliably reproduce it.

### Device info
**Device:** Google Pixel 5
**Android version:** 11 (security update on April 5th; Play system update on March 1)
**Signal version:** 5.7.6

### Link to debug log
https://debuglogs.org/f1f6873688219b2af2b5d8b4e543d8b7336b17e493fc1058dba579a698341b4e

**Comment by cody-signal** [comment]
Nothing in your logs jumps out, and there isn't a crash. Most likely something is falsely triggering the notification to be dismissed which dismiss the bubble, could be seen as a crash but isn't.

What would be helpful (if you can find consistent reproducible steps) is a log right after this occurs and including the time about when it occurred.

**Comment by cody-signal** [comment]
Log was super helpful, I think I know what's causing the issue in your situation. Will try to fix. Thanks!

**Comment by thefirstofthe300** [comment]
Feel free to tell me to open a new bug report if the following is unrelated.

I enrolled in the Android 12 beta and now the conversation bubble dismisses a lot more.

https://debuglogs.org/509bd1096ae9414e83f01914d00d5ea7bc1656e3bcf88899a0a7689ae2810650

**Comment by alabiaga** [comment]
@cody-signal there has been changes in Android 12 that is causing this issue.  Can you assign this to me. More than happy to address this change early in June. Thanks

**Comment by cody-signal** [comment]
@alabiaga feel free to make a PR and tag me on it.

**Comment by cody-signal** [comment]
@alabiaga heads up, I have a fix coming in 5.14.1 that may help with this, not sure if it'll resolve it 100% though, but it's aimed at improving bubble support.

**Comment by alabiaga** [comment]
Ok, I planned on a fix this week and will see if it's required after your
change. Thanks

**Comment by cody-signal** [comment]
@alabiaga there's definitely something wrong with bubbles and Android 12, even after my change (just tested it). Any help would be appreciated, my related/unrelated fix should be available on master hopefully tomorrow.

**Comment by thefirstofthe300** [comment]
I installed the most recent beta (5.15.6) and it looks like the issue with bubbles disappearing has been mitigated heavily at the very least on Android 12 beta. I'm not 100% sure that it is fully fixed, but at least the bubbles don't disappear every time I attempt to open them.

**Comment by cody-signal** [comment]
@thefirstofthe300 if you can submit a debuglog after encountering the issue again that would be helpful.
