### ISSUE TITLE
Signals calls are worst than before. 

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11231]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I could hear nothing on a signal call. All that I could hear was a random sound breaking at every single second. Like "A.a.a.a...aa......a.a.a...a......z..f..v..a.a.............a..a."  
Can you blame me for my bad internet and turning on "relay calls"?  No. I've set up 50Mbps WiFi which works flawlessly for me.So, relaying calls. Shouldn't be a problem as I didn't find any issues on my pc.

### Steps to reproduce
- Call a person
- talk to them
- Hear to them.

**Actual result:** There should be no voice breaks or stutters.  
**Expected result:** Calls are bloated with stutters and voice breaks.

### Screenshots
It was an audio which couldn't be recorded.

### Device info
**Device:** Nokia 6.1 Plus DRG
**Android version:** 10.0
**Signal version:** 5.9.1

### Link to debug log
https://debuglogs.org/c348a44482a2c7fd3b4f55cfa9fc35c5a1f98b9f728478f6460949ffc1ef6e93

**Comment by hiqua** [comment]
Is it reproducible? Does it happen at every call?

**Comment by pixincreate** [comment]
Yes, I've been facing this problem on every single call

**Comment by hiqua** [comment]
What was the last good version?

You seem to be using a beta version, the feedback for that should be given in https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-9-release/31524/46 ideally.

**Comment by pixincreate** [comment]
I don't remember the last good version exactly as everytime tye call started to stutter, I usually hang up the call and and either call again from Signal desktop or place a normal call

**Comment by gab81** [comment]
i am experiencing a similar issue on Android, although i've isolated that to wifi only. as in when the phone is on mobile 4G+ network then it's perfect both HD audio and HD video.
