### ISSUE TITLE
Signal contact sync breaks after adding a new contact

### ISSUE THREAD

**Issue by rosenpin** [signalapp/Signal-Android#11236]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't show up (disappears) in contact apps nor when queried using `ContentResolver`.  
Normally, when you query contacts using `ContactsContract.RawContacts.ACCOUNT_TYPE` you should be getting the package name associated with a contact (the app used to sync the contact, for example Google/WhatsApp/Signal)
```
        /**
         * The type of account to which this row belongs, which when paired with
         * {@link #ACCOUNT_NAME} identifies a specific account.
         * <P>Type: TEXT</P>
         */
        public static final String ACCOUNT_TYPE = "account_type";
```
But it seems that after adding a new contact Signal just disappears or removes all its contacts.   

Uninstalling -> reinstalling the app/clearing the app data temporary fixes the issue, but it occurs again after adding a new contact.  

This commit seems to have introduced the bug: https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97

### Steps to reproduce

- Make sure sync is enabled for Signal and that your contacts are synced correctly
- Add a new contact
- Open Signal
- Got to settings and manually sync Signal if auto sync is disabled
- Open contacts app and open a contact that has Signal
- See that it doesn't have Signal as a communication method

**Actual result:** Signal stops showing up in contacts/Signal contacts stop sync
**Expected result:** Signal shouldn't stop syncing contacts/contacts shouldn't disappear  

### Bad behavior:
![Screenshot_20210426-181552_Contacts](https://user-images.githubusercontent.com/5289630/116108180-57152c80-a6bc-11eb-8b39-62995c3b7d7f.jpg)
![Screenshot_20210426-181557_Contacts](https://user-images.githubusercontent.com/5289630/116110356-4a91d380-a6be-11eb-83ba-8fe2ea4ca533.jpg)

### Good behavior (after clearing the app data)
![Screenshot_20210426-181926_Contacts](https://user-images.githubusercontent.com/5289630/116108324-7ca23600-a6bc-11eb-88b3-2c9754904964.jpg)
![Screenshot_20210426-181929_Contacts](https://user-images.githubusercontent.com/5289630/116110331-449bf280-a6be-11eb-8422-e74b13c0b857.jpg)

### Device info

**Device:** Galaxy S10
**Android version:** 11
**Signal version:** 5.9.3

### Link to debug log

Logs are irrelevant, I found the line that causes this bug, I ran it and debugged it, the issue happens when adding less than 10 contacts and running sync, in my testing I added 1 contact leading me to `There are 1 unknown contacts..` log. You can follow the flow from here:
https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97#diff-6c090eefdf3ea4ba7d7c39fa0e3e2488facaa234c7ac3f27b122af3184fd6b56R64

But I saved you the trouble, the problem line is this: https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97#diff-973ca3d23ec70a73c09dc70e4b40e97e26988696392dcdd8f446468db7a96db2R269

Specifically passing `true` to the function, in this case, when providing only one recipient for example, this function will remove all pre-existing contacts

**Comment by rosenpin** [comment]
After further research I found that this can be reproduced consistently by adding a new contact, this is probably what causes the bug.  
### Adding a new contact causes Signal to disappear from the contacts app and breaks sync.

Further, I located the commit that introduced this bug, this is the one: https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97

**Comment by rosenpin** [comment]
I managed to "solve" the issue making the following change:  
https://github.com/rosenpin/Signal-Android/commit/ff2fce7d6f8b3eed05c9425f7f2eb9084c89dd00

Basically what I take from this, your individual contacts sync implemented by @greyson-signal and @alan-signal is flawed, I narrowed it down to this block to make it easier for you, please fix it as soon as possible so I can return to the Google Play version of the app :)
```
else if (unknownSystemNumbers.size() > 0) {
      Log.i(TAG, "There are " + unknownSystemNumbers.size() + " unknown contacts. Doing an individual sync.");
      List<Recipient> recipients = Stream.of(unknownSystemNumbers)
                                         .filter(s -> s.startsWith("+"))
                                         .map(s -> Recipient.external(getContext(), s))
                                         .toList();
      try {
        DirectoryHelper.refreshDirectoryFor(context, recipients, true);
      } catch (IOException e) {
        Log.w(TAG, "Failed to refresh! Scheduling for later.", e);
        ApplicationDependencies.getJobManager().add(new DirectoryRefreshJob(true));
      }
    } else {
      Log.i(TAG, "No new contacts. Just syncing system contact data.");
      DirectoryHelper.syncRecipientInfoWithSystemContacts(context);
    }
```

**Comment by alex-signal** [comment]
@rosenpin Do you mind opening a pull request with your work? If it's accepted as a change, you deserve the credit for it.

**Comment by rosenpin** [comment]
I opened a PR with an actual fix, the previous fix I mention in this thread is basically a stupid revert to the feature that introduced this bug, the new PR should be the actual fix
