### ISSUE TITLE
Multiple message indicators from same person

### ISSUE THREAD

**Issue by Niccalo** [signalapp/Signal-Android#11238]
Hello,

I'm receiving multiple message indicators from signal in my swipe down.  I'm on Android 11, RQ2A.210405.005 on a Pixel 4A.  I have attached an image to show what it looks like. If your require any other information, please let me know.  Thank you.

**Comment by alex-signal** [comment]
Could you please share the image? I do not see it attached. Please remember to remove any sensitive information before sharing.

**Comment by Niccalo** [comment]
Hi Alex,

My apologies, I must not have saved it right.

That is all from the same person, I had them message me a few times so I
could share with you.
