### ISSUE TITLE
Biometric unlock for Signal unresponsive

### ISSUE THREAD

**Issue by pengc99** [signalapp/Signal-Android#11233]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

This may or may not be related to  #11120, but I've noticed that in some cases (happens about 50% of the time), when double-tapping a Signal notification from my lockscreen the unlock screen for Signal will lock up.

Expected normal behaviour: 
1. Double-tap Signal notification on phone's lock screen
2. Phone prompts for biometric - I tap my finger on the sensor
3. Phone unlocks, Signal is opened. Signal prompts for biometric - I tap my finger on the sensor
4. Signal unlocks, and displays the message

Current behaviour:
1. Double-tap Signal notification on phone's lock screen
2. Phone prompts for biometric - I tap my finger on the sensor
3. Phone unlocks, Signal is opened. Signal prompts for biometric - I tap my finger on the sensor
4. Nothing happens. Cannot unlock signal. Screen appears frozen. No feedback from touching fingerprint sensor. 
5. I have to swipe up to open the task manager, then close Signal, and then re-open it to be able to unlock it with biometric.

Phone: 
Open market Pixel 3 128gb
Sprint account, T-Mobile LTE service
Stock un-rooted Android 11 with April 5th OTA security update. 

Signal App version 5.7.6

Debug log:
https://debuglogs.org/c5e79ead9bd7a932175f5525f31311a587c36d1487ff91ced6912ca338bdfe08

**Comment by pengc99** [comment]
I've added a video of this issue:

https://pithos.tacocat.org/files/24da480e9cb3cd/239c74f9.mp4

**Comment by cody-signal** [comment]
Thanks, could you provide updated logs as well?

**Comment by pengc99** [comment]
Yup, just had this happen right just now and immediately pulled a log. This happens about 2-3 times a day for me. 

https://debuglogs.org/a58c7a9b0d8d7d5885758ab6ed0ca4edc290d5b84eecc157b682e6f59a112e67

**Comment by cody-signal** [comment]
Thanks! We get lots of reports about it but have never been able to reproduce it. We have some time coming to spend on fixing this screen up (it's needs some general TLC) and hope to address this then as well.

Curious, if you swipe the app away from recents or go settings force close, does it become responsive again?

**Comment by pengc99** [comment]
> Curious, if you swipe the app away from recents or go settings force close, does it become responsive again?

If I force close it by swiping it away from recents, it will work fine the next time. This is my current workaround.

**Comment by pengc99** [comment]
Another log of it happening:

https://debuglogs.org/219a29d1e81d99f779195e43ea9e5e54204ef8955a8a22995edb159689219020

**Comment by pandalamp** [comment]
For the sake of visibility, this is still not fixed.

**Comment by greyson-signal** [comment]
Thanks, we're going to be taking a look at this soon.

**Comment by pengc99** [comment]
I have noticed this to be much better and more consistent in the past week. Have you guys made any changes in 5.24.4?

**Comment by cody-signal** [comment]
There was a fix in 5.23 or 5.24 that helps, sounds like it's working for you? If you are still experiencing problems, an updated log and repro steps would be appreciated.
