### ISSUE TITLE
Instagram link preview doesn't work anymore (Region based)

### ISSUE THREAD

**Issue by markorakita** [signalapp/Signal-Android#11239]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed this week that when you paste Instagram links into Signal there is no preview, just _"No link preview available"_ message. My friends also noticed that it happens to them too, so it is not device dependent. Links are from public account images.

If you paste the same link into WhatsApp, you will get preview for Instagram login page, so it seems to be related to the new Instagram change where you can only access limited number of images from public accounts before being asked to signup.

I understand that this might not be in your power to fix, but I wanted to at least give you a heads up since it seems that this Instagram change is not yet global, it seems to be region based (maybe some A/B testing), so you might be unaware that it is happening. My region is Serbia, so if you have access to some VPN you can test it that way.

### Steps to reproduce
- Copy link to some image from any public Instagram account
- Paste it in Signal conversation

**Actual result:** There will be no image preview, only "No link preview available" message
**Expected result:** Proper image preview.

### Screenshots
![Screenshot_20210427_131225_org thoughtcrime securesms](https://user-images.githubusercontent.com/25534110/116238182-5aaebf00-a761-11eb-8c77-999650975b2b.jpg)
![Screenshot_20210427_131202_com whatsapp](https://user-images.githubusercontent.com/25534110/116238193-5da9af80-a761-11eb-8b7a-e604bf42d4b3.jpg)

### Device info
**Device:** Huawei Mate 10Pro
**Android version:** 10
**Signal version:** 5.8.10

**Comment by piratenpanda** [comment]
WIthout an instagram account I can't access it at all for quite some time now so this might be related.

**Comment by UserX404** [comment]
It's maybe related.
For me on Firefox W10x64 Instagram images with Firefox 88.0 are also not working since today.

![grafik](https://user-images.githubusercontent.com/14954521/116281655-374c3a00-a78a-11eb-8c3e-019713e6a250.png)

**Comment by UserX404** [comment]
It's maybe related.
Since today (27.04.2021) on Firefox W10x64 with Firefox 88.0 Instagram images are also not working anymore.
It seams Instagram has some problems and is broken.
Wondering the world isn't on fire jet. :-)

![grafik](https://user-images.githubusercontent.com/14954521/116281655-374c3a00-a78a-11eb-8c3e-019713e6a250.png)

**Comment by markorakita** [comment]
It is still relevant, Instagram is blocking access without account and you have limited number of images you can see. So when you paste link in Signal it can parse image thumbnail for a limited number of links, and then it stops.

I don't know how Viber does it, when you parse instagram link there it can always parse thumbnail even when I have reached the instagram limit from my phone. I've noticed that they don't parse link until you send the message, so maybe they do it on the server where they use some dummy Instagram credentials or they use Instagram API.

**Comment by swetaVanjara** [comment]
I can see still login with instagram in link preview. Any update on this ?

**Comment by greyson-signal** [comment]
I think instagram in general has added many restrictions around what kind of content you can view when not logged in. I don't anticipate there will be much we can do here.

**Comment by swetaVanjara** [comment]
Yeah, After some request, showing login with instagram. 

Any solution ??? I want to get data from particular shared post.

**Comment by blackinitial** [comment]
in whatsapp like that, share link instagram got login preview thumbnail.
