### ISSUE TITLE
Echo from Huawei Honor 9 Lite during video calls

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-Android#11249]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

A family member uses Signal on a Huawei Honor 9 Lite. For the past year since we’ve been using Signal, during our video calls, I can hear the echo of my voice coming out of their phone’s speaker. I don’t have this problem with any of my other contacts. 

_(In my case, I’m calling from an iPhone 11)_

Looks related to #7635 

### Steps to reproduce
- start a video call to a user on a Honor 9 Lite
- speak into your device

**Actual result:** hear the sound of your voice being played through the speakers of the Honor 9 Lite and retransmitted to your device. 
**Expected result:** not hear your own voice being played back through your device’s speaker. 

### Screenshots

N/A

### Device info

**Device:** Huawei Honor 9 Lite
**Android version:** 9.0
**Signal version:** 5.8.10

### Link to debug log

Will get next time I can visit the family member in person

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
