### ISSUE TITLE
Service Issue Notification Not Readable on Dark Mode Theme.

### ISSUE THREAD

**Issue by fuzzzerd** [signalapp/Signal-Android#11258]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During a signal outage today, the banner displayed in-app was visible, but the contrast between text and background was not readable. The issue and resolved itself before I could grab a screenshot, and there is no way to reproduce the issue short of another signal outage. 

Switching to light theme and the message was visible and readable. This appears to be an issue only with contrast on dark mode.

### Steps to reproduce
- Open signal app in dark mode with a system alert visible

**Actual result:** Can not read text of banner/alert.
**Expected result:** Banner is visible, with high enough contrast for text to be readable.

### Screenshots
Was unable to grab a screenshot as the outage and associated banner was removed before I thought to grab one.

### Device info

**Device:** Pixel 4a
**Android version:** 11
**Signal version:** 5.8.10

### Link to debug log
https://debuglogs.org/de9322c82fe02a9ec81b5976306d4eb48b2af943e134769ea3ed976e16e123c0

**Comment by mueller-ma** [comment]
Screenshots for comparison:
Bright:
![signal-2021-05-04-231603_001](https://user-images.githubusercontent.com/22525368/117724232-c40fe280-b1e3-11eb-91d5-9583844180f0.jpeg)
Dark:
![signal-2021-05-04-231603_002](https://user-images.githubusercontent.com/22525368/117724235-c4a87900-b1e3-11eb-8246-db386a275b1d.jpeg)

**Comment by fuzzzerd** [comment]
> Screenshots for comparison:
> Bright:
> ![signal-2021-05-04-231603_001](https://user-images.githubusercontent.com/22525368/117724232-c40fe280-b1e3-11eb-91d5-9583844180f0.jpeg)
> Dark:
> ![signal-2021-05-04-231603_002](https://user-images.githubusercontent.com/22525368/117724235-c4a87900-b1e3-11eb-8246-db386a275b1d.jpeg)

Thank you. I was unable to reproduce it but that screen shot is exactly what I saw.
