### ISSUE TITLE
Back button doesn't work in conversation activity after lock/unlock cycle

### ISSUE THREAD

**Issue by ellenhp** [signalapp/Signal-Android#11252]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed on my device that the conversation activity will occasionally get into a state where the back button doesn't do anything. I'm not sure why this only happens on my device, but I think I found the root cause.

### Steps to reproduce
- Open a conversation (I have 100% repro rate in 1:1 conversations but groups don't seem to repro for some reason)
- Begin composing a message to open the keyboard
- Lock the screen
- Unlock the screen (critically, on my device the keyboard is closed by the system during this lock/unlock cycle and the bug does not repro on my friends' devices where this is not true)
- Press the back button

**Actual result:** 
The app will be in a state where the back button has no effect regardless of how many times it's pressed.

**Expected result:** 
The back button should pop the conversation activity and bring up the conversation list.

### Screenshots
Not comfy sharing screenshots since I don't have a burner phone sorry :(

### Device info

**Device:** Pixel 4A
**Android version:** 11 (running GrapheneOS not the stock rom)
**Signal version:** 5.8.x (Going from memory here) and a build built from the current master branch.

### Link to debug log

Let me know if you need this.

### Probable root cause

For some reason the system chooses to close the soft keyboard during the lock/unlock cycle. I'm not entirely sure why this happens. When the system is unlocked, `onMeasure` is called in `KeyboardAwareLinearLayout`, but I don't think the resize has actually completed yet. My hypothesis is that `getAvailableHeight` returns the old height, which causes the keyboard state to not be updated during the device unlock. Since the old state sticks around, the layout continues to believe that the keyboard is open. That bad state in `KeyboardAwareLinearLayout` causes the `onBackPressed` logic in `ConversationActivity` to trigger the keyboard closure flow instead of the `super.onBackPressed` flow. Since the keyboard isn't actually open, it can't be closed so the entire back button press is a no-op.

It seems like triggering `updateKeyboardState` and `onRotation` in `KeyboardAwareLinearLayout.onSizeChanged` instead of `KeyboardAwareLinearLayout.onMeasure` fixes this issue, which supports the theory that onMeasure is called too early in the resize operation for `getAvailableHeight` to return the correct (new) value. That could have ripple effects elsewhere in the codebase but it seems like a fairly safe change overall, so I'm going to send a PR for it.

**Comment by Tursko** [comment]
Duplicate of 
https://github.com/signalapp/Signal-Android/issues/10269

**Comment by ellenhp** [comment]
Looks like you're right. Sorry I didn't find that searching.
