### ISSUE TITLE
Checksum failed for [androidx.annotation:annotation:1.2.0

### ISSUE THREAD

**Issue by HosseinKurd** [signalapp/Signal-Android#11251]
Hi
There are some issues to run the project

```
Execution failed for task ':Signal-Android:verifyChecksums'.

> Checksum failed for [androidx.annotation:annotation:1.2.0, 9029262bddce116e6d02be499e4afdba21f24c239087b76b3b57d7e98b490a36]```

**Comment by hiqua** [comment]
Which commit? It works for me with the latest commit.

**Comment by HosseinKurd** [comment]
> Which commit? It works for me with the latest commit.
> 
> Also use https://community.signalusers.org/c/development/6 for dev questions.

Last commit on branch master

**Comment by cody-signal** [comment]
> Also use https://community.signalusers.org/c/development/6 for dev questions.
