### ISSUE TITLE
Note To Self cannot be selected without forcibly allowing Contacts permission

### ISSUE THREAD

**Issue by marcel263** [signalapp/Signal-Android#11256]
- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Use Signal without Contacts permission
- Delete any currently ongoing Note To Self 'conversation'
- Try starting a new Note To Self conversation

**Actual result:** No contacts are shown, even Note To Self is absent as well. Instead, user is only permitted to allow Contacts permission. Manually inserting user's own phone number into "Enter name or number" activates Note To Self. Inserting "note to self" in text as a contact produces an Invite option.
**Expected result:** Selecting Note To Self is possible as it is separate from and not a contact requiring the system's contacts list

### Screenshots
it is not allowing this for me due to a security policy within the device/Signal

### Device info

**Device:** Samsung Galaxy
**Android version:** 11
**Signal version:** 5.8.10

### Link to debug log
Please allow that debug log can be requested. If very important only.

**Comment by hiqua** [comment]
You can send a new message to your number to recreate the convo.

**Comment by marcel263** [comment]
> You can send a new message to your number to recreate the convo.

Yes as I stated that's a workaround however it is cumbersome, it also requires the user to have their own cell number at hand. It also complicates self-destructing Notes.

I don't support this method as it should be obvious, like a gallery app should not request camera permissions just for the sake of it.

Advocating still for restructuring this useful Signal feature.

**Comment by marcel263** [comment]
Solved in 5.17.3 . Tap the compose (pencil) button and enter your Signal profile there. "note to self" will pop up. Also, entering any string for it to be erased after, the option also appears. 

Thank you Signal team for putting in the effort for a human UX, closing the bug
