### ISSUE TITLE
No notifications on Android Auto

### ISSUE THREAD

**Issue by Kage1** [signalapp/Signal-Android#11254]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For several minor revisions now Android Auto is not receiving any notifications of new Signal Messages. One of the beta forum responses is having the same issue. This is over AA wired and AA wireless. It's across at least Android 10 and 11. This appears to have started around Signal Version 5.8.x.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-10-0-release/31813/37

### Steps to reproduce
- Attach to Android Auto
- Receive a new signal message
- Notification is received on the device
- No notification received on Android Auto

**Actual result:** No Notification received in AA
**Expected result:** AA should get the notification 

### Device info

**Device:** OnePlus 7Pro
**Android version:** 11
**Signal version:** 5.10.2

### Link to debug log
https://debuglogs.org/376a2c3b7e558706ae4ae6b43a279979572c63e151fe7821843b9d608f1f9645

**Comment by Tursko** [comment]
Same issue on my Pixel 5. I'll try to grab a debug log soon.

**Comment by cody-signal** [comment]
Don't be alarmed by the recent commit in 5.10.4, it's only temporary, Google is doing some interesting things with auto and won't let us submit updates until we jump some hoops so we had to temporarily disable.

**Comment by Tursko** [comment]
Seems to be fixed! Thank you!!

**Comment by Tursko** [comment]
Added back.

https://github.com/signalapp/Signal-Android/commit/51856c4f064f9de93b1e569b3c7203d1349d8901

**Comment by cody-signal** [comment]
This still may not work until we work a few more things out, just fyi.

**Comment by kmdm** [comment]
I have Android Auto notifications now on 5.12.2 but I'd defer to @cody-signal's comment above given I don't know what "may not work" means :-)

**Comment by cody-signal** [comment]
This appears to be working if you install from the Play Store. If you build it yourself or install from the website APK, you'll need to turn on "Untrusted Sources" [in the Android Auto developer settings](https://developer.android.com/training/cars/testing#step1).

**Comment by breversa** [comment]
I'm having the same issue with:
- Signal 8.13.2 (from Play Store)
- Android Auto version 16.9.662034-release com.google.android.projection.gearhead (from Play Store)
- aa4mg 0.6.4
- /e/OS 3.7 (Android 15) running on a Fairphone 5

I **have** granted access to Android Auto to the notifications.

What else can I check?
