### ISSUE TITLE
No emoji in the app as of 5.10.5

### ISSUE THREAD

**Issue by kpuljek** [signalapp/Signal-Android#11267]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to 5.10.5, I no longer see emojis in the app. They are not visible in neither the emoji pane nor messages.  Switching to system emoji allows me to type them in messages and see the ones I receive, but reactions are still blank.

### Steps to reproduce
- update to 5.10.5
- try to react to a message or send an emoji with System emoji turned off

**Actual result:** 
No emoji

**Expected result:** 
Emoji 

### Screenshots
![emoji1](https://user-images.githubusercontent.com/9851336/117326557-0eb2f700-ae92-11eb-984f-c3227c542bd0.png)

![emoji2](https://user-images.githubusercontent.com/9851336/117326562-0f4b8d80-ae92-11eb-9c7b-47cd86635447.png)

### Device info

**Device:** Samsung S10e
**Android version:** 11
**Signal version:** 5.10.5

### Link to debug log
I'll gladly attach some if they make sense for this bug.

**Comment by alex-signal** [comment]
Please add debug logs :) They are very useful for this bug.

**Comment by kpuljek** [comment]
Here it is! https://debuglogs.org/47da1e7ab94a42361c8c0c85552aef0dcf51a43b2907a59364d6bb9abe25c9b8

And you're right, it's loaded with these:

`[5.10.5] [23020] 2021-05-07 10:11:27.128 GMT+02:00 D EmojiProvider: Failed to load emoji bitmap resource
[5.10.5] [23020] 2021-05-07 10:11:27.128 GMT+02:00 D EmojiProvider: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[5.10.5] [23020] 2021-05-07 10:11:27.128 GMT+02:00 D EmojiProvider: There was 1 cause:
[5.10.5] [23020] 2021-05-07 10:11:27.128 GMT+02:00 D EmojiProvider: java.io.FileNotFoundException(PartAuthority couldn't load Uri resource.)
[5.10.5] [23020] 2021-05-07 10:11:27.128 GMT+02:00 D EmojiProvider:  call GlideException#logRootCauses(String) for more detail`

**Comment by kpuljek** [comment]
5.10.6 crashes whenever there's an emoji in sight (even on the conversation list). When System emoji is used, it crashes only when I open a conversation where there's a reaction present on screen (or when I scroll up)

**Comment by alex-signal** [comment]
@kpuljek If you can get a debug log of 5.10.6 that would be awesome. We stopped loading Emoji via Glide. However, it looks like somehow the spritesheet file can't be read:

java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_emoji/********-****-****-****-**********3d/********-****-****-****-**********f0: open failed: ENOENT (No such file or directory)

Which is curious, because we calculate an MD5 hash of the file as we write it and compare it to what the server says we should have gotten, and if we don't completely write it out and get a match, we delete the file and never write the version (I see in your debug log you've downloaded version 2, as expected)

I can add more protections and checks against this in the meantime.

**Comment by IHadAThoth** [comment]
Having the same issue as well, here's a debug log
https://debuglogs.org/d917a31f2c0788b13a946573ea032244b517b8c79b858286dce346fbf7fd45a6

**Comment by alex-signal** [comment]
@kpuljek The emoji set only takes about 7mb so you should have plenty of space. It's possible something bad happened trying to write the emoji to disk. The changeset I'm making will be much more aggressive about verifying what it's downloaded as it goes (so we don't use too much bandwidth)

**Comment by juppees** [comment]
> I'm not sure how this could be happening. Do any of you have a very full device? It's possible we're hitting up against some memory limit. Alternatively, if any of you have access to ADB, could you check what you see @ the directory specified in the exception? (data/user/0/org.../emoji/...) There should be a directory with a UUID as it's name, and a bunch of files in the directory also named with UUIDs.
> 
> If you do have this capability, there's a `.version` file in that directory you can delete and it should restore your emoji (using the baked in ones) for the time being.

In my case, deleting the `.version` file (and restarting) did not change anything. Afterwards I deleted the whole directory (the one named with as a UUIDs). It contained 19 files with UUID names. Now, all emoticons are back :)

**Comment by IHadAThoth** [comment]
> > @IHadAThoth Thanks! Looks like you've hit the 5.10.6 version of this issue. I've added some code that should alleviate this and will target it for 5.10.7

> Looking forward to the next version!

5.10.7 available via Firebase delivery. Installed. The new version fixed the issue. Thank you!
