### ISSUE TITLE
Impossible to send high-resolution photos.

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#11260]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All photos are ”optimized“ to really low quality when sent by Signal, overriding the will and intent of the user, instead of letting him choose. 

This makes sending high-resolution photos impossible. As if they wete banned by a dictatorship.

### Steps to reproduce
- Take a ~4K photo with your best camera, showing fine, beautiful details.
- Send it to another phone over Signal.
- Save the received image to you phone's memory.

**Actual result:** All the details are replaced by a blocky mess with washed-out colors when zooming in inside Sigal. The saved photo is now 1600×1200px in size.
**Expected result:** The full size should be available to the recipient, even on a slow connection and an old device. As that was the intent, and there is no point of what was to be communicated is censored and lost. If necessary, the full resolution version can be deferred, and the user visually informed that this is not the full version intendee, and that he csn wait until a better connection is available or force it now. On wifi, pictures should never be recompressed. (Unless until is guaranteed to he lossless to the actual pixel data.)
Sending it as a file is not a solution either, as there is no preview, and even if there was, it might still be low-resolution, still ruining the intent of the communication.

### Screenshots

(Let's hope, github does not recompress those…)
![Original photo](https://user-images.githubusercontent.com/58148887/117117800-40439980-ad90-11eb-8591-198f730de850.jpg)
![Signal’s abomination](https://user-images.githubusercontent.com/58148887/117117830-476aa780-ad90-11eb-8bf4-83238cf9564b.jpg)
Zoom in on the former, and note how the entire point is lost in the latter.

### Device info

**Device:** Huawei Mate 10 Pro (with a beautiful Leica camera)
**Android version:** 10.0.183
**Signal version:** 5.8.10

### Link to debug log

(If this is necessary to resolve this, please ask.)

**Comment by hiqua** [comment]
They're working on this, see for instance https://github.com/signalapp/Signal-Android/commit/2aad00df858d3f1bb52c5bd44f0eb60e0a809007

It would be useful to revisit this in one month or so.

**Comment by ExTechOp** [comment]
Well, here we are, over a month later.

Now all I can send through my Signal app from my Sailfish phone is 768×432 images (the camera original on Sony Xperia XA2 Ultra is 5312×2988). For a while you could avoid the downscaling by sending the picture as "file" instead of "image", but now even that gets munged to ridiculously low resolution.

`<rant>`How about **not** adding "features" like this which make the app almost unusable for everyone because some people live in mobile communications 3rd World countries (yes, I'm looking at you, USA)? Or at least before adding it, add something in Preferences to control it?  `</rant>`

**Comment by hiqua** [comment]
@ExTechOp  are you saying that setting the image quality to "high" doesn't fulfill your expectations?

**Comment by ExTechOp** [comment]
This is the first time I hear of such a setting, where is it?

**Comment by hiqua** [comment]
It's the icon left to the text input when you attach a picture. You can then select "standard" or "high". Note that it's a relatively new feature so you have to use a recent version of Signal. For more details look it up in the forum.

**Comment by hiqua** [comment]
I think it could be because your device is considered not powerful enough to handle it: https://github.com/signalapp/Signal-Android/commit/dd934e0095197b30d760a4a12441381606f0d39f#diff-d24ef1676cdeee2aca633bfd5757571dcad72f2d772aaa51e4d0ffd9d9351477R362

But I don't know exactly, I suggest you ask on the forum, maybe others will know more.

**Comment by ExTechOp** [comment]
> But I don't know exactly, I suggest you ask on the forum, maybe others will know more.

Exactly which forum would this be, https://community.signalusers.org/ or something else?

**Comment by hiqua** [comment]
Yes.

**Comment by ExTechOp** [comment]
Opened a discussion thread there: https://community.signalusers.org/t/image-resolution-selector/34002

**Comment by ExTechOp** [comment]
Turned out that SFOS was telling all Android applications they were running in a limited-memory environment. This has since been remediated, and this ticket can be closed, I now correctly get the resolution selector tool when adding images from my phone.
