### ISSUE TITLE
Reply notification persists after reply - should disappear after moving away from notifications dropdown - reply in notifications does not mark as read

### ISSUE THREAD

**Issue by marko-kovacevic** [signalapp/Signal-Android#11264]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I receive a message and I reply in the notifications pane. However, the notification still persists and does not disappear until I 'mark as read' or swipe it away. Replying to the message through notifications does not 'mark as read', however it should. Replying to the message makes the assumption that the user has read the message, and therefore the notification should be dismissed. 

### Steps to reproduce
- get message
- In notifications, press reply and type message, and reply 
- leave notification area
- notification persists

**Actual result:** Notification stays in notification area after replying
**Expected result:** notification stays in notification area after replying BUT when navigating away from notification area, notification should disappear. I believe the issue lies in that replying through notifications does not generate a 'read message' state and therefore does not remove the message from my notifications. It should generate a 'read message' state similar to clicking the conversation in the app.

### Device info

**Device:** Pixel 5
**Android version:** 11
**Signal version:** 5.9.5

**Comment by cody-signal** [comment]
This is working as designed. We interpreted Android's guidance on direct reply as discussed here: https://developer.android.com/training/notify-user/build-notification#reply-action

**Comment by marko-kovacevic** [comment]
Seems at odds with how most other apps user experience design works in this area. Is there a setting I can toggle to remove it after replying? I want to use signal but having to swipe it away each time is frustrating and inefficient.

> This is working as designed. We interpreted Android's guidance on direct reply as discussed here: https://developer.android.com/training/notify-user/build-notification#reply-action

Seems at odds with how most other apps user experience design works in this area. Is there a setting I can toggle to remove it after replying? I want to use signal but having to swipe it away each time is frustrating and inefficient.

**Comment by cody-signal** [comment]
Just verified that Google Messages and WhatsApp do the same thing. There is no setting to change this behavior. Feel free to hop over to the community forum and start a feature request thread if you feel strongly the behavior should be different.

**Comment by marko-kovacevic** [comment]
> Just verified that Google Messages and WhatsApp do the same thing. There is no setting to change this behavior. Feel free to hop over to the community forum and start a feature request thread if you feel strongly the behavior should be different.

My mistake on whatsapp and Google Messages. I just verified as well - that was what I was used to using an older build of Facebook Messenger Lite.

I see positives to both workflows, and I appreciate the response!
