### ISSUE TITLE
Can not build in Android Studio (Latest)

### ISSUE THREAD

**Issue by dsf-java** [signalapp/Signal-Android#11261]
I can not build Gradle files from the project. I can not run it in the Android studio. 
It say's

5/5/2021
3:14 PM	Clone failed: Repository 'https://github.com/signalapp/Singal/' not found

3:17 PM	Gradle sync started

3:17 PM	Gradle sync failed: Process 'command 'git'' finished with non-zero exit value 128
				Consult IDE log for more details (Help | Show Log) (14 s 120 ms)

3:17 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:19 PM	Gradle sync started

3:19 PM	Gradle sync failed: Process 'command 'git'' finished with non-zero exit value 128
				Consult IDE log for more details (Help | Show Log) (709 ms)

3:19 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:20 PM	Gradle sync started

3:20 PM	Gradle sync failed: Process 'command 'git'' finished with non-zero exit value 128
				Consult IDE log for more details (Help | Show Log) (664 ms)

3:20 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:22 PM	Gradle sync started

3:22 PM	Gradle sync failed: Cause: startup failed:
				build file 'C:\Users\dsfhs\AndroidStudioProjects\Signal\app\build.gradle': 1: unable to resolve class org.signal.signing.ApkSignerUtil
				@ line 1, column 1.
				import org.signal.signing.ApkSignerUtil
				^
				1 error
				Consult IDE log for more details (Help | Show Log) (551 ms)

3:22 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:22 PM	Gradle sync started

3:22 PM	Gradle sync failed: Cause: startup failed:
				build file 'C:\Users\dsfhs\AndroidStudioProjects\Signal\app\build.gradle': 496: unable to resolve class ApkSignerUtil 
				@ line 496, column 9.
				new ApkSignerUtil('sun.security.pkcs11.SunPKCS11',
				^
				1 error
				Consult IDE log for more details (Help | Show Log) (436 ms)

3:22 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:22 PM	Gradle sync started

3:22 PM	Gradle sync failed: Plugin with id 'witness' not found.
				Consult IDE log for more details (Help | Show Log) (1 s 413 ms)

3:22 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

3:22 PM	Gradle sync started

3:22 PM	Gradle sync failed: Could not find method dependencyVerification() for arguments [witness_verifications_zt58toucxdd2wxrygyu6gh80$_run_closure1@77b33d6f] on project ':Signal-Android' of type org.gradle.api.Project.
				Consult IDE log for more details (Help | Show Log) (742 ms)

3:22 PM	Android Studio is using the following JDK location when running Gradle:
				C:\Program Files\Java\jdk1.8.0_291
				Using different JDK locations on different processes might cause Gradle to
				spawn multiple daemons, for example, by executing Gradle tasks from a terminal
				while using Android Studio.
				More info...
				Select a JDK from the File System
				Do not show this warning again

And 

Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method dependencyVerification() for arguments [witness_verifications_zt58toucxdd2wxrygyu6gh80$_run_closure1@77b33d6f] on project ':Signal-Android' of type org.gradle.api.Project.

Resolve it.

**Comment by hiqua** [comment]
GH issues are for bugs only, please use the forum.

**Comment by cody-signal** [comment]
> GH issues are for bugs only, please use the forum.

https://community.signalusers.org/c/development/6
