### ISSUE TITLE
Signal fails to open, blank screen only

### ISSUE THREAD

**Issue by roteiro** [signalapp/Signal-Android#11268]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal was working until a few days ago. Since then, trying to open the app results in a blank screen. The logcat log indicates that the database fails to open. Is there anything which I can do or is the database corrupted?

### Steps to reproduce
- open Signal

**Actual result:** Blank screen. 
**Expected result:** Signal should open.

### Device info

**Device:** Motorola G4 Play
**Android version:** 7.1.1
**Signal version:** 5.9.6

### Link to debug log
https://gist.github.com/roteiro/f0cb55356539150927c04e9ec9c4a996#file-logcat-log

**Comment by endofthebeginning** [comment]
It's the same here, with a friend of mine. When the app is opened, white screen appears for a few seconds, and then it reverts back to the android home screen. It's been a few days. Tried, force stopping, reinstalling, restarting the phone, clearing the cache and data, all to no avail.

**Comment by h-h-** [comment]
I could solve this by uninstalling and reinstalling Signal. This is no longer an issue for me.
