### ISSUE TITLE
Crash on sharing image from Firefox Android to Signal contact via Android sharing ui

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#11269]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is crashing when I want do share an image directly from my android browser (Firefox) to a Signal contact.

### Steps to reproduce
- Open Image in browser (e.g. https://www.mann.tv/thumbs/article_picture/2017-04/werner-teaser-breit.jpg)
- Long click on image and select share
- Select a user in the recent menu or Signal itself.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
App crashes and on second run a Android popup appears "Signal crashed again" (not sure, i'm on german)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Image is inserted into desired chat or a contact has to be selected.

### Screenshots

<img src="https://user-images.githubusercontent.com/14954521/117353893-01f1cb80-aeb1-11eb-9bcc-cfe4a977d23a.jpeg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/14954521/117353956-146c0500-aeb1-11eb-9566-7584f7f3ef02.jpeg" width=50% height=50%>

### Device info

**Device:** Sony Xperia XZ2c
**Android version:** 10
**Signal version:** 5.9.6

### Link to debug log

https://debuglogs.org/b60d50be5a677b22f371eacd234020c282decb6cbc23303c067a715bf40fe6db

Edit:
It seems to be browser related. Works with Firefox Focus and LOS Browser (org.lineageos.jelly)
But Signal shouldn't crash or should support a failure message.

**Comment by greyson-signal** [comment]
Seems firefox has a bug. When sharing to direct contacts, it doesn't grant the proper read permissions. Same operation fails in other apps. But we shouldn't crash.
