### ISSUE TITLE
Signal wrongly prepends country code to SMS recipient, even when it's a special number (e.g. "8080")

### ISSUE THREAD

**Issue by jotaf98** [signalapp/Signal-Android#11274]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal prepends country code to all SMS, even for special numbers that do not work with country codes (usually 4 or 6 digits; this is the case for many automated SMS interfaces).

### Steps to reproduce
- Find an automated SMS interface into a service in your country with 4-6 digits (I tried this in the UK)
- Attempt to send SMS

**Actual result:** A country code is appended and the SMS fails
**Expected result:** No country code should be appended

### Related bugs
Issue [#7321](https://github.com/signalapp/Signal-Android/issues/7321) (and others linked there) is similar, but it's about wrongly guessed country codes. The issue here is that no country code should be appended at all in some cases.

### Device info
**Android version:** 4.4
**Signal version:** 5.9.7

**Comment by greyson-signal** [comment]
Hmm, for 4 digits we should just be using the bare number. For 6 digits, it's possible libphonenumber is screwing up something with UK numbers. Will be addressed in 5.11. Thanks!

**Comment by jotaf98** [comment]
It's great to hear that, thanks!

**Comment by driuba** [comment]
How is this closed?  
Issue still present today. Four digit numbers get country code prepended and cannot be used.

Android version 10  
Signal version 5.23.7

**Comment by jotaf98** [comment]
Same, I still get the prepended country code for short codes (like "123" to see your balance, etc) on Signal 5.24.

It doesn't seem to be specific to UK codes. The same happens with +351 for Portugal.

**Comment by danielocdh** [comment]
Issue is present with 4, 5 and 6 digit numbers on +52
