### ISSUE TITLE
Disappearing messages not appearing in the backup

### ISSUE THREAD

**Issue by trevdan88** [signalapp/Signal-Android#11270]
Dear team,

Phone: Android Samsung A10
Signal version: latest as of 2021 May 05

I took a backup of Signal from my A10 and restored it to a Samsung s21.

After restore I noticed that the s21 does not appear to have the disappearing messages.

While taking the backup the disappearing messages had 6 weeks more before they expired.

Is this the way the backup works? Does it exclude disappearing messages while performing a backup?

**Comment by trevdan88** [comment]
If this is expected as per design, providing users the option to include or not include this would be really helpful.

**Comment by greyson-signal** [comment]
This is intentional. We do not back up disappearing messages because doing so would be a way to extend the life of disappearing messages beyond what was intended. Hope that clears things up!
