### ISSUE TITLE
"Can't open signal" toast after Activity is dead

### ISSUE THREAD

**Issue by RunYouCleverBoy** [signalapp/Signal-Android#11276]
Bug:
When returning to Signal from "recents" after being dismissed - it won't open.
Steps to reproduce:
Open Signal
Tap Back
Tap Android recents key
Try to open Signal
Getting a toast "Can't open Signal"

Platform: Samsung S7 Oreo

**Comment by greyson-signal** [comment]
Hi, please include a debuglog.

**Comment by RunYouCleverBoy** [comment]
Hi
Tried to extract this right after reproducing the bug.
https://debuglogs.org/14a032de86f9a2a6255b78246bf632970c51d305a1778dbe441338c653094327


Thanks.
  Shmuel Meymann
