### ISSUE TITLE
Signal Lock Screen for Fingerprint is not Working after turning off the Phone Screen

### ISSUE THREAD

**Issue by theDeal** [signalapp/Signal-Android#11285]
I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
As expected, if you have the auto Lock Mode from Signal on (my Phone one Minute) , after turning off* your Phone Signal Locks itself after one Minute. If you turn your Phone back and you unlock your Phone Signal shows the Lock-screen. Signal is on this screen stuck. You can not "Tap To Unlock", the button is not working. You have to relaunch the App to fix the Issue :-)

*I mean here with Turning of the Phone to just leave it and it's shutting it self off.

### Steps to reproduce
- Go to Signal Settings and turn on the Auto Lock feature 👍 
- Add a Time Signal should Lock itself 🕒
- Leave your Phone until it locks itself 
- After the Lock Time from Signal is over turn on your Phone again... ...now there should be the Bug at least on Android

**Actual result:** Signal is Stuck on the Screen and you can not lock back in, the Button is not Working...
**Expected result:** Press on the Button... and read my Fingerprint

### Device info
**Device:** Pixel 3a
**Android version:** 11
**Signal version:** 5.9.7

**Comment by greyson-signal** [comment]
Can you please include a debuglog?

**Comment by theDeal** [comment]
For sure :)
https://debuglogs.org/abc99b3c7d2af0ce7a4d8a82cad8f35b2a8b37b0b74d1182651f0a61275ab03e

**Comment by cody-signal** [comment]
Please try a recent build, some fixes were made for this, sorry it took so long.
