### ISSUE TITLE
Bogus unread notification shown out of the blue

### ISSUE THREAD

**Issue by sivaraam** [signalapp/Signal-Android#11286]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For the last couple or so of beta releases, I've been noticing bogus unread messages notification being shown out of the blue. I have notifications enabled in such a way that the name and message are shown. But the bogus notification is unusual. It doesn't show the message. It only shows the name (not sure if there's a patter for which name is shown).

### Steps to reproduce
Sadly, I don't know specific steps to reproduce this thing. It just happens at random times.

**Actual result:** Bogus unread notifications are shown which starts like "Most recent from ...". Using the notification to open the app shows me that there are no new unread messages.
**Expected result:** No such bogus notifications are shown.

### Screenshots
![Screenshot_20210511-181523](https://user-images.githubusercontent.com/12448084/117859730-03563600-b2ad-11eb-99b7-c8831921b214.jpg)

### Device info

**Device:** OnePlus Nord
**Android version:** 11
**Signal version:** 5.11.0

### Link to debug log
I don't have one yet. I'll be sure to get one the next time I see that notification.

**Update**
I managed to get a couple of them. Each shortly after seeing the bogus notification. Here they are:
https://debuglogs.org/f404087c19b419854399a2bf7dfeb9ba5f91bcd2c5d38fd52224bd8c89afe0b6

https://debuglogs.org/a00f834b301ae26475e2fa2e640f58c2c2e1a4bdf7476616dcf202d87f8476b9

**Comment by cody-signal** [comment]
> I don't have one yet. I'll be sure to get one the next time I see that notification.

This would be helpful, thanks!

**Comment by sivaraam** [comment]
I managed to get a couple of them. Each shortly after seeing the bogus notification. Here they are:

https://debuglogs.org/f404087c19b419854399a2bf7dfeb9ba5f91bcd2c5d38fd52224bd8c89afe0b6

https://debuglogs.org/a00f834b301ae26475e2fa2e640f58c2c2e1a4bdf7476616dcf202d87f8476b9

I'll add these to the first comment too.

**Comment by cody-signal** [comment]
Sorry for the delay, thanks for the logs. Do you happen to use notification bubbles or conversation priorities? Looking at the logs I suspect it may be related to the same issue impacting those that use bubbles just showing a little differently for you.

**Comment by sivaraam** [comment]
> Do you happen to use notification bubbles or conversation priorities?

I do use bubbles a lot. I'm not sure what you mean by conversation priorities, though. Do you mean setting custom priorities for specific conversations? Is that even possible? 🤔 If not, kindly clarify. 🙂

**Comment by cody-signal** [comment]
> I'm not sure what you mean by conversation priorities

If you long press on a conversation notification, you can change the priority for that conversation, but don't think that should matter, the conversation bubble usage is enough to trip up the app currently.

I have a fix in 5.14.1 that'll be in beta sometime this week hopefully that may fix it.

**Comment by sivaraam** [comment]
I haven't seen this issue in a while. I'll re-open if I see it.
