### ISSUE TITLE
App Crashing With Specific Phone Number

### ISSUE THREAD

**Issue by snorkeldimes** [signalapp/Signal-Android#11284]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal App on android crashes within moments of launch with a (my) specific phone number. In have tried different phone numbers on the same device with no issues whatsoever. App only crashes with, what appears to be, one (1) specific number. 

I have reproduced the issue on multiple handsets and multiple operating systems. All with the same result. 

### Steps to reproduce
- Register with specific phone number
- Launch Signal android

**Actual result:** Signal app crashes within moments of opening. 

**NOTE:** Does NOT crash when using other phone numbers on the same handset. 

**Expected result:** 

Signal app should open as normal. 

### Screenshots
Cannot add, Signal only opens momentarily.

### Device info

**Device:** Pixel 4a 5g
**Android version:** 11
**Signal version:** 5.9.7

### Link to debug log
Unable to produce due to app crashing

**Comment by snorkeldimes** [comment]
I can, but am traveling abroad at the moment.....I won't be back to my machine for another 8 days. 

In the meantime does this sound like something that's happened before? 

Again, multiple other numbers work and register fine on the same handset.....this ONE particular (which is my primary number) just crashes the app....on three different devices .....its really odd.

**Comment by snorkeldimes** [comment]
UPDATE: 

On install / re-register with the same number I am having issues with, there was just BARELY enough time to link Signal with an iPad. 

The app keeps crashing in about 3-5 seconds on my Android Handset(s), but seems to work OK on my iPad. 

This is obviously not an acceptable solution since I have moved ALL communication to family, friends, and co-workers to signal, and I can’t simply carry an iPad around everywhere. But for the time being it will work. 

Please let me know if this helps at all. Need to find a solution, or jump ship and get a new number altogether.

**Comment by NoStepSnek** [comment]
# LOGCAT...

`05-18 05:53:29.493 13339 13394 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
05-18 05:53:29.493 13339 13394 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13339
05-18 05:53:29.493 13339 13394 E AndroidRuntime: org.thoughtcrime.securesms.storage.StorageSyncValidations$MultipleAccountError
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validateManifestAndInserts(StorageSyncValidations.java:130)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validate(StorageSyncValidations.java:37)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:339)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:181)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
05-18 05:53:29.493 13339 13394 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: org.thoughtcrime.securesms.storage.StorageSyncValidations$MultipleAccountError
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validateManifestAndInserts(StorageSyncValidations.java:130)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validate(StorageSyncValidations.java:37)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:339)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:181)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
05-18 05:53:29.493 13339 13394 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
05-18 05:53:29.505 13339 13394 I JobManager: Successfully flushed.
05-18 05:53:29.510  1283 13425 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-18 05:53:29.511  1283  2626 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
05-18 05:53:29.549 13339 13394 I Process : Sending signal. PID: 13339 SIG: 9
05-18 05:53:29.585  1283  1332 D CompatibilityChangeReporter: Compat change id reported: 136219221; UID 10207; state: ENABLED
05-18 05:53:29.612  1283  4349 I ActivityManager: Process org.thoughtcrime.securesms (pid 13339) has died: fg +50 FGS 
05-18 05:53:29.613  1283  7791 I WindowManager: WIN DEATH: Window{f1ba6af u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}
05-18 05:53:29.613  1283  1379 I libprocessgroup: Successfully killed process cgroup uid 10207 pid 13339 in 0ms
05-18 05:53:29.613  1283  7791 W InputDispatcher: Attempted to unregister already unregistered input channel 'f1ba6af org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity (server)'`

**Comment by NoStepSnek** [comment]
I have now attempted on 6 additional handsets... running everything from stock android, samsungs trash OS, GrapheneOS, and CalyxOS. 

On all of the above, Signal crashes with my number, and my number only. Every other number attempted works just fine on the above devices.

**Comment by NoStepSnek** [comment]
# UPDATE 2

I do not have an iPhone, but was successfully able to get signal to load on my iPod, then relink it to desktop and tablet. OK workaround at the moment. 

The issue is still with Android handsets - Tested and still does *NOT* work on the following: 

- Galaxy Note9 - Whatever the stock Samsung OS is called
- Galaxy S9 - w/Custom OS
- Pixel 3a - GrapheneOS
- Pixel 3 - CalyxOS
- Pixel 4a5G - GrapheneOS

**Comment by NoStepSnek** [comment]
@greyson-signal You asked nearly 20 Days ago for logcat.... I provided that nearly two weeks ago. 

This is concerning my primary number, and Signal continues to crash ONLY with that number. While this is not the end of the world, it is wildly inconvenient given that I have put a lot of time and effort into getting most family and ALL business contacts on Signal, and using that specific phone number. 

Tried again today, and again, Signal just crashes within moments of opening. A response would be greatly appreciated regarding this matter. 

Thank you.

**Comment by greyson-signal** [comment]
Hi there, it's looking like you're hitting a crash with a Storage Service sync. Since 5.9.7 (the version you originally experienced the problem on), there's been some major changes to how storage sync works. Do you mind confirming what version of Signal you're using now?

**Comment by NoStepSnek** [comment]
Hi, just to be safe, I made sure to re-download 5.11.5.... 

I am still experienceing the exact same issues - again, with just a single phone number. 

Assuming this is stemming from SVR. If so, if I am able to keep signal open long enough, I should be able to solve the issue by removing the pin, no?
