### ISSUE TITLE
app crashes/ doesn't sync name of group created on desktop 

### ISSUE THREAD

**Issue by adiOdi** [signalapp/Signal-Android#11288]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I created a group on desktop (non beta), but clicking on it on mobile crashes the app.

The group is also called "unknown"

While recreating, the crashing doesn't reoccur, But the not named thing persists ('unknown Group' this time) until A message from somebody else comes in.

### Steps to reproduce
- create group on desktop 
- try opening Group on mobile

**Actual result:** app crashes/name of group isn't shown 
**Expected result:** own message/ creation of group should sync name/not crashing behaviour 
### Screenshots

![SmartSelect_20210511-215124_Signal](https://user-images.githubusercontent.com/49091894/117878354-f6821400-b2a5-11eb-90bf-4dab2bd3ae9c.jpg)

### Device info

**Device:** Samsung Galaxy s8
**Android version:** 9
**Signal version:** 5.10.7

### Link to debug log

https://debuglogs.org/a62a50ae001ae145e8fa962a660816ff554d5a7ed06be0923f02b43db750f85d

**Comment by tobiscode** [comment]
Same problem here! Pixel 2 XL, Signal 5.10.8, Android 11. Debug log: https://debuglogs.org/fc7ab207aefd39d544ed674f2e7b57fe8eafed66fe88732031b9563b6707f2a6

**Comment by peterkarsten02** [comment]
Same problem here too! I found out that if you rename the group via the rename tool in the group settings, than you can access the group on your mobile device normally too. 

Debug log from the desktop client: https://debuglogs.org/c9c5428b34a77f908224b198cdf438554e737eb8f985f5ca6f84e6769b424d60
