### ISSUE TITLE
Message bubble with GIF rendered incorrectly

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#11287]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I received a GIF message from a friend and the message bubble was rendered incorrectly. See screenshot.

Additionally, tapping the GIF does not bring up the full screen image viewer. However, the image can still be saved to the device if the message is selected, and it also shows up in All Media.

My guess is that Signal for some reason thinks it is a sticker rather than a regular GIF attachment. This is the only time I have seen it happen.

### Steps to reproduce
Unknown

**Actual result:** Message bubble seems to be rendered as if the GIF was a sticker.
**Expected result:** GIF should be shown as a regular image.

### Screenshots
![Screenshot_20210511-131936~2](https://user-images.githubusercontent.com/10427164/117870027-2e1a9d00-b261-11eb-957f-7753255634f8.png)

### Device info
**Device:** Pixel 5
**Android version:** 11
**Signal version:** 5.9.7

### Link to debug log
https://debuglogs.org/462807108930f0e8118a0b26ee706cd523510bc733fc6e285f708dddec1cf37d

**Comment by greyson-signal** [comment]
Do you know what device/signal version the sender was using?

**Comment by greyson-signal** [comment]
There was a bug in an old android version, so mostly trying to track down if they're using that version.

**Comment by Herohtar** [comment]
I haven't seen this recently, so maybe it has been resolved.
