### ISSUE TITLE
New contact not showing up in Signal

### ISSUE THREAD

**Issue by MajestyZ** [signalapp/Signal-Android#11290]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A friend that I had Signal installed, doesn't show up in my Signal contacts list and I can't send that person messages. The person can send me messages though and when I use Signal for Windows, I can send this person messages fine. I have no trouble with any other contacts I have on Signal.

### Steps to reproduce
- Open Signal
- Open chat with specific contact
- "Enable signal for SMS" is displayed hence making me not able to send this person a message
- Open Signal for Windows --> sending messages is working

**Actual result:** "Enable signal for SMS" shows and I can't send messages to this person on my phone
**Expected result:** I should be able to send this person messages, because person has installed Signal on the phone

### Device info

**Device:** OnePlus 8 Pro
**Android version:** 11.0
**Signal version:** 5.11.0

### Link to debug log

Made a debuglog right after a 'refreshed' the contactslist:
https://debuglogs.org/88d278499dde887ec87087a43da5ba3fdfbd207355420bb6c9d6afb5a20b98e5

### Other things I tried
- Clear data/cache of Signal on Android
- Remove contact from phone and from Google account
- Looked for inconsistencies in contacts accounts (all my contacts are stored in Google)
- Obviously tried refreshing the contacts list
- Made Signal default app for SMS 
- This has been going on for about 5 days now

Any help would be appreciated :).

**Comment by greyson-signal** [comment]
Hi there, what country are you in/what country is the person you're talking to in? Has there been any changes to their phone number format?

I thought we had code to make sure inbound signal messages mark people as registered, but somehow it seems that was lost. So I've added it back in 5.11.1, which should at least help.

**Comment by MajestyZ** [comment]
Thanks for your response.

Country: both the Netherlands. Forgot to write that I already tested with different number formats: added country code, removed country code etc., to no avail though.

**Comment by MajestyZ** [comment]
Well I just installed 5.11.1 and all is fixed! That's amazing. Any information needed for debugging purposes? If not, this thread can be closed.

**Comment by greyson-signal** [comment]
Nothing else I need, no. I still have your original log. Glad it was resolved for your case :)
