### ISSUE TITLE
"Confirm your Signal PIN" - layout issue in non-english-languages e.g. german or netherlands

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#11297]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The button "ABBRECHEN" ("CANCEL") isn't fully visible in the "Confirm your Signal PIN" screen.

### Steps to reproduce
- set app language to german or netherlands
- go to Settings > Account > PIN reminders

### Screenshots

In german the button "ABBRECHEN" ("CANCEL") isn't fully visible. The A is missing and one B is only half shown.
In netherlands the PIN input field and both buttons aren't visible.

![signal-2021-05-13-182921](https://user-images.githubusercontent.com/49990901/118156848-218d7480-b41a-11eb-88b8-58ac3e8c5a82.png) ![signal-2021-05-13-183302](https://user-images.githubusercontent.com/49990901/118157269-a11b4380-b41a-11eb-96e5-744f92a629e2.png)

for comparison: the "Enter your Signal PIN" screen is wider. (And uses round corners.)

![signal-2021-05-13-183302 (1)](https://user-images.githubusercontent.com/49990901/118157275-a37d9d80-b41a-11eb-9085-bfc3542d69dd.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 7.1.1
**Signal version:** 5.11.1

**Comment by Meteor0id** [comment]
Oh that is much worse than what I see on my test device, had I know the buttons fall of entirely in Dutch I would have tried to fix that. Thanks for showing that screenshot I will see if I can shorten the text, but the real solution would be to fix the layout by making this window wider.

**Comment by alex-signal** [comment]
Should be fixed in 5.11.3

**Comment by Sgn-32** [comment]
@Meteor0id

Screenshots of 5.11.3:

![signal-2021-05-15-141048 (1)](https://user-images.githubusercontent.com/49990901/118360489-23754600-b588-11eb-8f39-b3fcb4b9c051.png) ![signal-2021-05-15-141048](https://user-images.githubusercontent.com/49990901/118360490-240ddc80-b588-11eb-85b2-70c1fa327b76.png)

**Comment by Meteor0id** [comment]
@Sgn-32 What happens if you open de keyboard on the Dutch screen on that device? Will the buttons still be easy to reach? Thank you for checking Dutch as well

**Comment by Sgn-32** [comment]
@Meteor0id

Buttons are hidden by the keyboard.

![Screenshot_20210515-160547](https://user-images.githubusercontent.com/49990901/118364199-c5505f00-b597-11eb-833f-9bbcd25c4179.png)

**Comment by Meteor0id** [comment]
That's not acceptable. I'll see if I can shorten this text further but it's probably going to lose some relevant information. @alex-signal  is there any additional layout enhancement you can make to prevent any such pop-up screens from occuping the lower half of the screen? Maybe make it possible for that margin around the input field to collapse when needed.

**Comment by alex-signal** [comment]
@Meteor0id Hi! The next beta is going to go out later today and I'll make sure this has been fixed. I applied a global style to all `MaterialAlertDialogBuilder` dialogs in an effort to make more of our dialogs look consistent and apparently this one doesn't appreciate it very much.
