### ISSUE TITLE
GIF searching is terrible on Android

### ISSUE THREAD

**Issue by goadah** [signalapp/Signal-Android#11298]
I don't know why most messaging platforms have this problem but now Signal has this problem as well. The search engine for GIFs is at an all time low. It used to be okay and now you can't do more than one word without the search turning into nothing you're looking for. Revert the GIF search engine back to what it used to be or improve on it.

**Comment by Meteor0id** [comment]
This was also discussed shortly on the forums recently, the devs could not reproduce the issue at the time. Please elaborate exactly what isn't working (which words) and also share your debug log right after you tested this in your app.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-10-0-release/31813/125?u=meteor0id

**Comment by orkil123** [comment]
I'm having the same issue. For example doing a gif search for "Wolf of Wall Street" used to return search results for the movie. Now it only returns results for the first word "wolf". This happened right after the update that was supposed to improve gif loading speeds. I emailed logs and screenshots to Signal support.

**Comment by hiqua** [comment]
I'm having better results with 5.11.2 than with 5.9.7 FWIW, maybe wait until 5.11 is released and revisit this bug.
