### ISSUE TITLE
Video messages received doesn't play

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11291]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Videos that I received from one of my contacts doesn't play. It freezes at time stamp 0.  
  
### Steps to reproduce
- Play a video someone has sent to you

**Actual result:** Videos doesn't play
**Expected result:** Videos should be playable

### Screenshots

Null

### Device info

**Device:** Nokia 6.1 Plus DRG 
**Operating System:** Lineage OS Unofficial
**Android version:** 11.0
**Signal version:** 5.11.0

### Link to debug log

https://debuglogs.org/1c2c6648f3380ff2f585c08c9667238ea42a260155486df6b794eb2f0228b121

**Comment by clauz9** [comment]
Can you link to such a video, so I can try and replicate this, because my phone doesn't do that, and it might be file dependent.

**Comment by pixincreate** [comment]
> Can you link to such a video, so I can try and replicate this, because my phone doesn't do that, and it might be file dependent.

I don't think it's file for dependent, may be ROM issue of with the app.

**Comment by pixincreate** [comment]
https://user-images.githubusercontent.com/69745008/118230790-d0c65c00-b4ab-11eb-9cc7-060c1dbcc30e.mp4
