### ISSUE TITLE
Giphy search results poor after recent change, don't match top results for same search term on Giphy site

### ISSUE THREAD

**Issue by altmank** [signalapp/Signal-Android#11293]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Giphy integration was recently updated. This update introduced a new UI look for the Giphy component that shows more tiles. This change also appears to have introduced a different way GIF results are returned. The GIF results are now very often not relevant or poor matches for the search term. Comparing the same search term on the Giphy website to the Giphy integration in Signal highlights this difference.

### Steps to reproduce
1. Search "what is love" in Signal GIF functionality
2. Search "what is love" in Giphy website

**Actual result:** Results differ greatly between the two, the Giphy site has the more relevant results, which are for the Haddaway "What is Love" song. Signal Giphy has none of the same relevant images.
**Expected result:** Signal Giphy search should mimic the results on the Giphy website, which are the most relevant to the search term

### Screenshots
None

### Device info
Not applicable

### Link to debug log
Not applicable

**Comment by greyson-signal** [comment]
What version are you using? There was a bug in earlier 5.10.x releases that causes this, but it was fixed later in the release cycle. If I search 'what is love' on the latest android release, it matches giphy's search results on their website.

**Comment by altmank** [comment]
Ahh that looks to be the issue. My client didn't auto-update to that
version yet. I manually updated and the issue is fixed.
