### ISSUE TITLE
SIgnal app crashes on visiting "Contact us" and "Debug log".

### ISSUE THREAD

**Issue by Akash0123G** [signalapp/Signal-Android#11303]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended No
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports 
- [x] This isn't a feature request or a discussion topic Yes

----------------------------------------

### Bug description
Signal app does not behave normally on visiting "Contact us" and "Debug log" option in the app. The app jumps back to the 'chats tab' (in case of Contact us) and falls back to the 'help' tab when trying to enter "Debug log". And also the app crashes if you repeatedly keep trying to visit "Contact us" or "Debug log". I am noticing this behavior since Signal 5.11.1

### Steps to reproduce
- Go to settings > Help > Contact us / Debug log
- Keep repeating the above step, signal app crashes or shows a message "Signal keeps stopping" 
- that reproduce the bug

**Actual result:** On visiting the Contact us and Debug log option on Signal app, user is taken back to the main chat screen or the app crashes.  (i.e. the buggy behaviour)
**Expected result:** Signal app should not go back to the chats tab or crash, when trying to visit Contact us or Debug log.  (i.e. what would be the correct behaviour)

### Device info

**Device:** Nokia 4.2
**Android version:** Android 11
**Signal version:** 5.11.3

**Comment by hiqua** [comment]
Please use https://community.signalusers.org/c/beta-feedback/25 for beta (like 5.11.3) feedback.

**Comment by Akash0123G** [comment]
> Please use https://community.signalusers.org/c/beta-feedback/25 for beta (like 5.11.3) feedback.

Okay, thank you for informing. Also this issue has been fixed.
