### ISSUE TITLE
Signal takes a long time to send messages

### ISSUE THREAD

**Issue by sunflowerspeed** [signalapp/Signal-Android#11306]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal seems to intermittently take a long time (1-5 minutes) to send messages. Specifically, it takes a long time for the rotating dotted circle to be replaced with a single checkmark. The double-checkmark appears almost instantly. This is **not** only the case for long conversations; even a group chat with a current total of 46 messages shows this problem. It does not appear to happen with specific contacts, nor does it matter whether I am sending a message in a group chat or a one-on-one chat. I also use Signal Desktop, so I can confirm that it takes a long time for the message to reach my desktop instance. Signal Desktop does not exhibit this slow behavior, and my internet connection is very fast (gigabit down/up). It does not matter whether I use wifi or mobile data. I first noticed this problem within the past week, and I use Signal daily.

### Steps to reproduce
- Open a chat in Signal
- Send a message

**Actual result:** Signal successfully sends the message, eventually. This can take 1-5 minutes. This is not always the case.
**Expected result:** Signal sends the message within a matter of seconds.

### Device info

**Device:** Samsung Galaxy S10 (SM-G973F)
**Android version:** 11 (G973FXXU9FUCD, RP1A.200720.012.G973FXXU9FUCD)
**Signal version:** 5.10.8

### Link to debug log
https://debuglogs.org/c0e1e98bbb818507e879ae11dc405f285fa3339285e46d3123bc6dd8bcdd5d8d

**Comment by JulioNahum** [comment]
It happens exactly the same. Sometimes he sends them to me normally, and other times it takes a long time. The audios or stickers sometimes take 50 seconds to send. I do not know what is the problem.

**Comment by elitejake** [comment]
It has been more than 25 minutes here and my messages are not sent. And I do have a stable Internet connection.

By the way, is this a duplicate of #9930

**Comment by Arcuna** [comment]
If I understand correctly, #9930 is specifically for chats with long history. As I said in my original post, this is not the case for me. I am experiencing long sending times even for group chats with under 100 messages.

**Comment by tsikmartin** [comment]
you have similar issue to me as well in your debug log, but mine is with group chats with non signal users, however may fall in same line as mine may be a duplicate.

[5.10.8] [440  ] 2021-05-18 12:52:24.734 CDT W SignalServiceMessageSender: java.io.IOException: No connection!
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:185)
	at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:195)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1498)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:210)
	at org.thoughtcrime.securesms.jobs.SendReadReceiptJob.onRun(SendReadReceiptJob.java:139)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

**Comment by sunflowerspeed** [comment]
Had another interesting connection problem a little while ago. I was on a group call with three people on another continent and at some point the call became too laggy to comfortably be able to chat. I eventually hung up and tried to send a message to the group, and this message took a very long time to go through. (Meanwhile my Desktop client worked fine, and my internet connection seemed fine). I suspect this is the same issue I have been dealing with, but I have included a new debug log:

https://debuglogs.org/f523fca2c0cbb3c1a61422565b8b3c7053c50e50b8bb6dec0c171ede506a31ad

**Comment by tsikmartin** [comment]
I am still having the same issues as well still. wonder when @cody-signal will acknowledge this issue.

**Comment by sunflowerspeed** [comment]
I have not experienced this issue for a while now (I think it went away on its own after some update), so I am going to close my ticket.

**Comment by jaymehta-g** [comment]
Experiencing this same problem still. It happened both with my old and new phones but not through signal desktop
