### ISSUE TITLE
No notofications

### ISSUE THREAD

**Issue by ZiOLONwe** [signalapp/Signal-Android#11307]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, I have problem with Signal. I no have notifications push. I have to open signal and now give me new messages. My problem is only Signal, another app works noemal(Message, Whats app, Telegram, gmail itp. I search solution try basic solution no work.

### Device info

**Device:** Oneplus 8 Pro
**Android version:** 11
**Signal version:** last from google play

Debug log: https://debuglogs.org/67fadbbcce4c2d5c9e92f1380528e62bdb06e8c4a5a909b5cbfc2013c151b7bb

**Comment by abhilashkrishn** [comment]
I also have the same issue, but no solution.

**Comment by hiqua** [comment]
Have you followed these steps: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications ?

**Comment by abhilashkrishn** [comment]
Hi,
Yes, I have followed these steps already.
By the way, there is no battery optimization and data saver for Signal. This issue happened after the last update. Not only in my phone but also my wife is also facing the same issue.We observe this issue only in Signal.

Sent from Yahoo Mail on Android 
 
  On Mon, May 17, 2021 at 9:58 PM, Quentin ***@***.***> wrote:   


Have you followed these steps: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications ?

**Comment by hiqua** [comment]
You mean the update from 5.9 to 5.10.8? Can you add a debug log?

**Comment by abhilashkrishn** [comment]
Yes, exactly.

Here is the debug log.
https://debuglogs.org/7ac92c68713184e7574eedf76fed3a806ac8797722f6ff1fe4ff8f13872baa41

**Comment by ZiOLONwe** [comment]
> Have you followed these steps: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications ?

Of course.

**Comment by hiqua** [comment]
@ZiOLONwe is your problem also specific to 5.10? Was everything working properly in 5.9?

**Comment by ZiOLONwe** [comment]
@hiqua 


I have been using signal for four days. Used latest version from goole play. The problem is on all conection.
I dont understand this log. Can you explain?

**Comment by hiqua** [comment]
Sorry I didn't mean this as something you can solve, more like this could be a hint for a bug in Signal.

According to https://github.com/signalapp/Signal-Android/issues/7186#issuecomment-343975668 your logs could mean that something is wrong with your connection, possibly because of your device if that happens all the time. How many different connections did you try? Are you based in Poland, or somewhere else?

**Comment by ZiOLONwe** [comment]
> Sorry I didn't mean this as something you can solve, more like this could be a hint for a bug in Signal.
> 
> According to [#7186 (comment)](https://github.com/signalapp/Signal-Android/issues/7186#issuecomment-343975668) your logs could mean that something is wrong with your connection, possibly because of your device if that happens all the time. How many different connections did you try? Are you based in Poland, or somewhere else?

I live in Poland. I try 3-4 networsk Wifi and mobile data. 
I'll probably stay on whatsapp, no problem. 
I don't have time to mess around with the signal.

**Comment by bkqtnte10** [comment]
This problem still occurs. Can we open this again?
