### ISSUE TITLE
<a href="sms:"> links do not work with Signal

### ISSUE THREAD

**Issue by brendonlamb** [signalapp/Signal-Android#11312]
Testing with links on this page:
https://bradorego.com/test/sms.html

You can get a phone number from the browser into Signal, but not any preset/default "body" text... would really love this feature to work on Signal since it works for most major messaging apps.

**Comment by hiqua** [comment]
Feature requests should be done there: https://community.signalusers.org/c/feature-requests/android-feature-requests/18
