### ISSUE TITLE
No notification after closing the application with task manager

### ISSUE THREAD

**Issue by Loopbuilder** [signalapp/Signal-Android#11324]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Hello everybody.

The Signal Messenger does not receive any more messages on Android 10 and a Xioami mobile phone after closing the Signal app (that is running in the foreground) via the task manager. 

### Steps to reproduce
  - Switch on the mobile phone and connect to the internet
  - Start the Signal app via the icon so that Signal runs with background services
  - Call up the task manager
  - Close the signal app with the task manager (foreground app closed)
  -> From then on, no more messages will be received (no display via icon symbol, no acoustic notification of incoming messages)

### Expected result:
  - Switch on the mobile phone and connect to the internet
  - Start the Signal app via the icon so that Signal runs with background services
  - Call up the task manager
  - Close the signal app with the task manager (foreground app closed, background service still running to receive messages)
  -> Messages are received (display via icon symbol, acoustic notification of incoming messages) 
 

### Device info
Xiaomi Redmi Note 9 Pro
Android version:** 10 QKQ1 MIUI 12.0.2
Signal version: 5.10.8

**Comment by cody-signal** [comment]
What task manager are you using to close the app? If it forces closes, then it'll stop all notifications and processes from apps closed that way.

**Comment by sonata-chen** [comment]
I have the same issue on my Asus phone.

Have you tried to  [**reset app preferences**](https://mobileinternist.com/reset-app-preferences-android)? It works for me.

Android version: 8.1.0

**Comment by eabase** [comment]
Pleas beware that many vendors have bloatware that closes background apps and services that are not used within some specified time. **Make sure to check you phones energy saving settings!**

:zap:  That said, Signal should help user check the energy savings settings...
