### ISSUE TITLE
Flag emojis not available in reaction menu

### ISSUE THREAD

**Issue by kyleedwardsny** [signalapp/Signal-Android#11320]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to react to a message with an emoji, the flags section is not available. (It is still available for inserting emojis into a message.)

### Steps to reproduce
- receive a message
- hold down to bring up reaction menu
- select the "..." for more emoji options

**Actual result:** No flags menu available
**Expected result:** Flags menu should be available

### Screenshots
![Screenshot_20210518-221424](https://user-images.githubusercontent.com/7741429/118746679-a61b3100-b826-11eb-83b0-55020d2c78d4.png)
Note that this is in landscape mode but it happens in portrait too.

### Device info

**Device:** LG G8X Thinq
**Android version:** 10
**Signal version:** 5.10.8

**Comment by hiqua** [comment]
Same here.

Note that if you have a flag in the "recently used" emojis, you can use it perfectly fine.

**Comment by rogersapp** [comment]
Same here, can react with a flag if it's in my recents and can on desktop, but the option is gone on mobile. Running Android 11 and just factory reset for unrelated reasons, but the issue was there before and after reset.

**Comment by Sgn-32** [comment]
In 5.13.3 the flag emojis are available again.
