### ISSUE TITLE
Attachment reselection

### ISSUE THREAD

**Issue by n00b42** [signalapp/Signal-Android#1132]
When I select an attachment and without sending select another one, then the second attachment is shown before sending, but the first one is sent (received at the other device) and displayed (at my device) after I sent the message.

**Comment by castanley** [comment]
Please fix!

**Comment by nrizzio** [comment]
@castanley please don't [bump issues.](https://github.com/WhisperSystems/Signal-Android/blob/f53d64ab7a77d4d79723729bfc4fba9685703c61/CONTRIBUTING.md#dont-bump-issues)
