### ISSUE TITLE
ASCII Art has vanished from emoji picker

### ISSUE THREAD

**Issue by chaoscommander** [signalapp/Signal-Android#11328]
There used to be an ASCII tab in the integrated emoji picker. It contained, among others, the beloved Table Flip ASCII figure which I used frequently. The entire tab is now gone. Please bring it back.

You will probably reject this as a "feature request", but I view the removal as a downgrade for which there seems to be no pressing reason. (╯°□°）╯︵ ┻━┻

**Comment by pleiozc** [comment]
It's gone, here is how it looked like

![signal-ascii 2](https://user-images.githubusercontent.com/79718929/120005041-d5136e80-bfad-11eb-9e87-a9a82dd7322d.png)
![signal ascii 1](https://user-images.githubusercontent.com/79718929/120005073-da70b900-bfad-11eb-9c0d-4573d78e26f4.png)

**Comment by Sgn-32** [comment]
These are back in 5.13.4
