### ISSUE TITLE
The app has a bug which should be fixed as soon as possible.

### ISSUE THREAD

**Issue by nandwanatanmay** [signalapp/Signal-Android#11326]
The chat area has bug which can lead to data breach.

**Comment by cody-signal** [comment]
Could you provide additional details via security@signal.org

https://support.signal.org/hc/en-us/articles/360007320791-How-can-I-report-a-security-vulnerability-

**Comment by nandwanatanmay** [comment]
Issue has been fixed. I just got the report for the same too clarifying that the issue and bug will be fixed in the  next android update

**Comment by nandwanatanmay** [comment]
We cannot get back the backup when fresh copy of signal is installed.. I
have to install the previous version .

**Comment by nandwanatanmay** [comment]
Yess ... The app has this error till now..
Fix this sir.
