### ISSUE TITLE
Much too much mobile data demand

### ISSUE THREAD

**Issue by Loopbuilder** [signalapp/Signal-Android#11325]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The signal messenger eats up an insane amount of mobile data, even if not a single message is sent or received.
This is done after reinstalling the app. 

### Steps to reproduce
 - Signal app is startet
 - Cell phone, connected to the mobile network, lies around untouched on the table
 - No message will be sent
 - No messages are received from others (no text messages, no pictures, no videos)
 
**Actual result:**  The Signal App uses approx. 634kB every hour. For 24 hours, 30 days, these are:
 - <b>0.45GB data volume per month without sending or receiving a message</b>.
So my small data volume is completely overloaded and costs extra ($$$$$).

**Expected result:**
 - Signal app is startet
 - Cell phone, connected to the mobile network, lies around untouched on the table
 - No message will be sent
 - No messages are received from others (no text messages, no pictures, no videos)
 - Very little data volume is used (<50MB per month) if no messages are sent / received.

On my old cell phone and after using account transfer option, the data required was about 140kb per day.
However, due to a bug during account transfer, it was not possible to receive an acoustic notification of incoming messages, so i installed signal completely new.

This extreme data consumption occurred after an uninstallation and reinstallation of signal.
Account synchronization when signal is disabled,
Notification of new contacts is disabled

For comparison: the Telegram messenger additionally installed on the mobile phone only needs approx. With Whatsapp it was always very little.
Signal uses around 120 times as much data as comparable messengers!!!

Another bug in Signal means that it is not possible to close the Signal app in the foreground via the task manager, since no more notifications will be received afterwards.
As a result, the signal app must always run in the foreground and a possibly data-saving operation in the background is not possible. 

### Device info
Xiaomi Redmi Note 9 Pro
Android version:** 10 QKQ1 MIUI 12.0.2
Signal version: 5.10.8

**Comment by hiqua** [comment]
Debug log

**Comment by eabase** [comment]
> ... Signal App uses approx. 634 kB every hour.

I find this very hard to believe. Mine is using only 23 kB for half a day. 
* Are you sure that, your **day** starts at the time you expect? 
* Are you sure you didn't get a video or other picture messages in this time frame?
* Are you sure it's actually Signal using this data?

**Screenshots!!**
(And debug log)

**Comment by rrd1** [comment]
I can confirm similar behaviour with v5.13.8 which I got 2 or 3 days ago. Android System warned already twice about increased data usage of Signal app. As per Android mobile data statistics, Signal used approx 385MB this month. Around half of that traffic was caused during last two days. This does not match to my usage.
I quickly went through the media collections of most recent conversations. It sums up to around 50MB in total for this month. So this can't (and shouldn't be) the reason for that high data usage.
Only reason I could imagine is the new Gif/Giphy feature. I just searched few keywords for fun, but just sent one Gif finally. I don't believe that this should cause that much traffic.

**Summary:**
- Signal v5.13.8
- Android 9, Security Updates from May 2021
- Traffic of Signal App in June:
  - Foreground: 385MB
  - Background: 0MB
- Average traffic of last months is less than 100MB! 

Any idea how to measure the traffic in more detail? Maybe something with ADB? Does Signal print out something to logcat about network traffic?

**Comment by hiqua** [comment]
See https://community.signalusers.org/t/signals-data-usage-is-too-high/30346/4

In short, yes Giphy is usually the culprit.

**Comment by rrd1** [comment]
Thanks for your feedback. I think it would be worth to introduce an option to let the user enable/disable the Giphy feature. This would be also good from privacy perspective.

**Comment by grandchild** [comment]
Disabling the Giphy feature would accomplish nothing that just-not-using-it would. What would disabling it change? It doesn't load gifs in the background or anything. You browsed gifs, so gifs were loaded.

As for the "privacy perspective", it's already pretty good. The Signal server already proxies all your Giphy searches, so it's as private as it gets. See https://signal.org/blog/signal-and-giphy-update for details.

**Comment by rrd1** [comment]
> Disabling the Giphy feature would accomplish nothing that just-not-using-it would. What would disabling it change? It doesn't load gifs in the background or anything. You browsed gifs, so gifs were loaded.

That's true, but even opening the Giphy tab accidentally without searching something seem to cause additional network traffic. This could be prevented by a config option in my opinion.

> As for the "privacy perspective", it's already pretty good. The Signal server already proxies all your Giphy searches, so it's as private as it gets. See https://signal.org/blog/signal-and-giphy-update for details.

That's fair enough, didn't know that. Thanks!
