### ISSUE TITLE
Unable to zoom on picture while using pen drawing mode

### ISSUE THREAD

**Issue by ayaankhan98** [signalapp/Signal-Android#11334]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to zoom image while using pen drawing mode, suppose we are sending some image to someone and if we wish to write something on image we choose the pen icon to get into drawing mode while in drawing mode unable to zoom image using two fingure pinch in and pinch out gesture. Therefore it makes hard sometimes to highlight or mark things properly on images.

### Steps to reproduce
- open any contact for conversation
- choose image to send
- choose pen icon on the top right corner to write/highlight something on image
- now try to use two fingure pinch in or pinch out gestures (to zoom in or zoom out the image)

**Actual result:** Unable to zoom in or zoom out.
**Expected result:** Should be able to zoom in or zoom out using two fingure pinch in/out gesture.

### Device info

**Device:** Motorola One Fusion +
**Android version:** 10
**Signal version:** 5.11.5 (updated on May 19, 2021)

**Comment by UserX404** [comment]
Hello!
At the moment this is the intendend behavior. Github is used as bug tracker only and feature requests should be discussed in the forum.
Here the corresponding thread:
https://community.signalusers.org/t/ability-to-zoom-into-pictures-when-editing-them/30550
