### ISSUE TITLE
Add smooth keyboard animation in signal Android

### ISSUE THREAD

**Issue by singhalrishi27** [signalapp/Signal-Android#11332]
When using signal on android keyboard animation feels jittery and sluggish with Android 11 google introduced new windowinsets APIs for smoothly animation keyboard this already works on Google messages.

Please implement smooth keyboard functionality in Signal for Android.
Examples are given below also give me feedback if you agree or not

**Comment by singhalrishi27** [comment]
Uploading screen-20210525-120914~2.mp4…

Signal app with no smooth keyboard animation

**Comment by singhalrishi27** [comment]
https://photos.app.goo.gl/VnKLeuVA7mC2TsYv7

**Comment by singhalrishi27** [comment]
https://photos.app.goo.gl/ANvQ8n947c6AeiBt9
Signal's glitchy animation

**Comment by Tursko** [comment]
This is for bug reports only. Feature requests can be made on the forum. https://community.signal.org

**Comment by singhalrishi27** [comment]
> This is for bug reports only. Feature requests can be made on the forum. https://community.signalusers.org

I'm requesting for lag fix not requesting to add any feature

**Comment by electr1fy0** [comment]
I still see this on Signal 6.2.1

Google Messages and Telegram smoothly slide the page up while Signal just jumps the page a little.

And the keyboard slide up and page slide up animations aren't simultaneous either.
