### ISSUE TITLE
No notification after switching to other apps

### ISSUE THREAD

**Issue by abhilashkrishn** [signalapp/Signal-Android#11331]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Once we have switched to other apps (any apps), the signal immediately stops providing notifications unless we open it again. There is no battery restriction or data saver. Already tried the troubleshooting methods provided in the Signal support. The issue is happening with all the phones I have. Also the same issue has been reported with my friend's phone and he is living in another city. It seems the issue has not related with our wifi or mobile network as other apps are providing notifications at the same time.

### Steps to reproduce
- Update the signal to current version 5.11.5
- After using signal for some time, switch to any other apps.
- No more notifications from signal unless we open it again.

**Actual result:** No notifications from signal
**Expected result:** Notifications from signal

### Screenshots

![Screenshot_2021-05-25-02-55-00-717_com miui home](https://user-images.githubusercontent.com/3692781/119409268-aaeb5380-bd04-11eb-90e7-f4f1818ba0be.jpg)

### Device info

**Device:** Xiaomi Redmi Note 6 Pro (tulip)
**Android version:** 9 (V12.0.1.0.PEKMIXM, PKQ1.180904.001)
**Signal version:** 5.11.5

### Link to debug log

https://debuglogs.org/74f54d796e8d0d88e58489dc054d3311f8eb5305c92b85445f9f39fcbff77188

**Comment by bme13** [comment]
Hi, Are all your other phones also Xiaomi ones? I think you're looking in the right direction for the battery optimization. Perhaps https://dontkillmyapp.com/xiaomi contains some additional information that can be helpful.

**Comment by UserX404** [comment]
Xiaomi (MIUI) also has a toggle for disabling miui optimization within android developer options. If you are on MIUI this could also help you out.

**Comment by abhilashkrishn** [comment]
> Hi, Are all your other phones also Xiaomi ones? I think you're looking in the right direction for the battery optimization. Perhaps https://dontkillmyapp.com/xiaomi contains some additional information that can be helpful.

My other phone is Samsung, my friend's phone is Oneplusone. 
I have looked into the battery optimization and auto start already, but none of these resolves the notification issue.
Moreover different brands of phones having the same issue with Signal.

**Comment by abhilashkrishn** [comment]
> Xiaomi (MIUI) also has a toggle for disabling miui optimization within android developer options. If you are on MIUI this could also help you out.

Thank you for the input, however this one I have already tried. But it doesn't resolve the issue. My issue is only with Signal app and there is no battery restriction for it. Other apps which are still in battery restriction is providing the notification. I am wondering why Signal is only having the issue when there is no battery optimization for it.

**Comment by bme13** [comment]
A while ago a developer asked debug logs for these kind of issues. Perhaps you can add logs from you're different phones in that thread. See: https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

**Comment by UserX404** [comment]
An other attempt is to use signal as default sms app due to the sms app should not be included in optimization.
Can you give it a try with this settings? Just for testing. ;-)

**Comment by abhilashkrishn** [comment]
> A while ago a developer asked debug logs for these kind of issues. Perhaps you can add logs from you're different phones in that thread. See: https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

Sure. I will upload another debug file.

**Comment by abhilashkrishn** [comment]
> An other attempt is to use signal as default sms app due to the sms app should not be included in optimization.
> Can you give it a try with this settings? Just for testing. ;-)

Tried it now. But still the issue is there.

**Comment by mlsem** [comment]
Any news about this issue ??

**Comment by mlsem** [comment]
Make sure you are not using a tracker controler @abhilashkrishn , Are you using one ?

**Comment by abhilashkrishn** [comment]
> 
> 
> Make sure you are not using a tracker controler @abhilashkrishn , Are you using one ?

What is tracker controller?

**Comment by mlsem** [comment]
> > Make sure you are not using a tracker controler @abhilashkrishn , Are you using one ?
> 
> What is tracker controller?

Some kind of VPN to block or track API called by other apps.

**Comment by abhilashkrishn** [comment]
> 
> 
> > > Make sure you are not using a tracker controler @abhilashkrishn , Are you using one ?
> > 
> > 
> > What is tracker controller?
> 
> Some kind of VPN to block or track API called by other apps.

No, I am not using it in my phone.

**Comment by kpeace** [comment]
This is what I did and it fixed my "No Notification" issue.
Apps & Notifications -> All Apps -> Signal -> Notifications -> Lock Status -> Choose Alerting

It was on Silent for me. Once I changed it to Alerting, I got notifications.

Asus ZenPhone 5
