### ISSUE TITLE
Redmi Note 5 echo in voice calls / videocalls

### ISSUE THREAD

**Issue by todoesUno** [signalapp/Signal-Android#11330]
- [X]  I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal users calling a Redmi Note 5  hear their own voice as an echo.
(It seems echo cancellation does not work on Redmi Note 5)

### Steps to reproduce
- Call a Redmi Note 5 via Signal
- Speak
- Hear echo of own voice

**Actual result:** The person who calls a Redmi Note 5 hears his own voice
**Expected result:**  No echo should be heard

### Device info
**Device:** Redmi Note 5
**Android version:** 9.0
**Signal version:** 5.11.5

The issue may be related with: https://github.com/signalapp/Signal-Android/issues/7635 https://github.com/signalapp/Signal-Android/issues/8935 https://github.com/signalapp/Signal-Android/issues/10768 https://github.com/signalapp/Signal-Android/issues/9351 https://github.com/signalapp/Signal-Android/issues/10215

According to this closed thread https://github.com/signalapp/Signal-Android/issues/10351#issuecomment-757618823 , Redmi Note 5 has already been added to AEC blacklist, but the echo issue keeps happening.

Looking at the code, it seems Redmi Note 5 is already in AEC blacklist, but echo problem persists, the issue may be elsewhere:
https://github.com/signalapp/Signal-Android/blob/3d227e2f1622ad9cff2f90210a8e9123f5b81a7b/app/src/main/java/org/thoughtcrime/securesms/RtcDeviceLists.java#L28

**Comment by bidhovbizar** [comment]
I found a work around for the echo. If we directly use the video call facility then the echo is present. But if you call audio first and then turn on the video then the echo is removed. I did this 

Dell Laptop to Redme Note 5 Pro
Dell Laptop to Lenovo Laptop
Redme Note 5 Pro to Redmi Note 5 Pro

Hopes this helps

Hope this helps temporarily.

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
