### ISSUE TITLE
Send and received messages color switched

### ISSUE THREAD

**Issue by Masqueey** [signalapp/Signal-Android#11339]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since update 5.13.1, chat colors have been flipped: instead of my messages being a bland color and the person I'm chatting with having colored chat boxes, mine are colored and the other is now blandly colored.
(I'm not sure whether this is behaviour as intended or a bug. I liked the last one better because I don't look at my own messages so often, but if this is intended, I'll drop a post about it on the forum.)

### Steps to reproduce
- Update to 5.13.1
- Pick a custom chat color (not sure whether this matters, I only noticed it after I did)

**Actual result:** My messages are now a custom color and the other person's messages are now bland white.
**Expected result:** My messages are bland, the other person's messages are colored.

### Screenshots
![screenshot1](https://user-images.githubusercontent.com/19656058/119798222-3c142300-bedb-11eb-8d2f-2c14c06ad7e4.jpg)

### Device info

**Device:** Xiaomi Redmi 9S
**Android version:** 10
**MIUI version:** 11.0.4.0
**Signal version:** 5.13.1

### Link to debug log

https://debuglogs.org/54fd8e7814560138ad75a8b7a78e89b0fc47e023a789bffc58abdd84242cd11a

**Comment by hennjo** [comment]
Hi @Masqueey ,

this behavior is intended as per the description here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-13-release/32995

**Comment by Masqueey** [comment]
Thanks for your feedback. Sorry for the useless issue.

**Comment by bearfriend** [comment]
Why should I not be able to override these colors? The colors I had set were exactly as I needed them to be for me to differentiate clearly between people. The randomly selected colors are far more difficult for me to see (and frankly they just hurt my eyes). They also make it nearly impossible to identify clearly who messages are from while scrolling. Additionally, the colors are no longer consistent for the same person between individual conversations and group chats.

For me, this is a really big problem as I am extremely visual and can no longer identify items in my chats easily. Please consider allowing the old system to be a setting, at least for small groups.
