### ISSUE TITLE
Signal on the Huawei AppGallery

### ISSUE THREAD

**Issue by shadowmedicis** [signalapp/Signal-Android#11333]
Hello,

I am creating this issue because I think it would be a good idea to publish the Signal app on the Huawei Store (AppGallery) for phones without google services. The interest would be twofold, automating the background update of the application for phones without google services and facilitating the installation of the application for new users with phones without google services.

Here is the documentation to publish applications on AppGallery: https://developer.huawei.com/consumer/en/doc/distribution/app/agc-release_app

If you wish, I can publish it myself. But the ideal would be that it is the developers of Signal which takes care of it to be able to maintain the updated version on this store.

Thank you in advance

**Comment by shadowmedicis** [comment]
Based on the AppGallery wishlist.  More than 57,000 users are waiting for the application on this store.

![Screenshot_20210525_131839_com.huawei.appmarket.jpg](https://user-images.githubusercontent.com/80291786/119489237-c6357d80-bd5b-11eb-8b74-ffbb9995b0f0.jpg)

**Comment by ayaankhan98** [comment]
@shadowmedicis Please discuss this issue on signal community forum, Github issues are only supposed for reporting bugs in pre-existing features.

**Comment by shadowmedicis** [comment]
Ah ok no worries, I'll create the topic then.
