### ISSUE TITLE
Background access is Mandatory. No option to opt out

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-Android#11341]
- [X ] I have searched open and closed issues for duplicates
- [ ]X I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Description
I would like the option to disable signals background access in order to save battery. I know when disabled you won't receive any messages. This use to be an option 3 months ago. Right now, I have a kill switch to stop the app every time, it mores steps then I would like to be doing every time I open it. Signal isn't the best on battery life. I would like the option to disable background access.

### Screenshots

![Signal](https://user-images.githubusercontent.com/49108816/119912176-c70f1080-bf0f-11eb-90f6-cb747cc27ae9.png)

### Device info

**Device:** Samsung S9+
**Android version:** 10
**Signal version:** Lastest

![](smb://management2.local/drive_data_1/MrWaste's%20Data/Pictures/Signal.png)

**Comment by greyson-signal** [comment]
Is Signal set as your SMS app? If so, the system will disable the option to restrict background access.

**Comment by MrWaste** [comment]
Thank You for pointing that out. Thank you for your time!!
