### ISSUE TITLE
Signal cannot be unlocked when the device uses a secure screen lock method

### ISSUE THREAD

**Issue by floss4good** [signalapp/Signal-Android#11340]
- [x] I have searched open and closed issues for duplicates.
  - #11120 might be related.
- [x] I am submitting a bug report for existing functionality that does not work as intended.
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic.

- - - - - - - - - -

#### Bug description

When I try to open the app while using a secure screen lock method for my device (i.e. 'Pattern', 'PIN' or 'Password') and have the 'Screen lock' setting enabled within Signal I see the unlock screen with the following text:
> Signal is locked
> TAP TO UNLOCK

However, no matter where or how many times I tap, nothing happens. And no pattern / PIN / password prompt appears.
Maybe it worth mentioning that even though I have seen this unlock screen many times, I've almost never had to tap since it was self-unlocking after a second or so.

The issue first happened after updating Signal from version 5.4.7 to version 5.4.12.

#### Some context

I should also say that I don't have play services installed. Back in 2017 when I first installed Signal I remember that I was asked something regarding this, but I don't remember exactly what (maybe if I want to use the app without play services?!). Anyway, I can see the 'Background connection enabled' sticky notification and I was updating the app using Yalp Store until about 1-2 years ago when I discovered that you provide the APK directly on your website (and I manually check - since I rarely connect to WiFi networks - from time to time if new versions were released).

The device do not have a fingerprint reader (or other biometric authentication features).

#### Steps to reproduce
- Make sure the Signal 'Screen lock' setting is enabled.
- Choose 'Pattern', 'PIN' or 'Password'.
- Go to your device settings and select 'Pattern', 'PIN' or 'Password' for 'Screen lock'.
- Wait for the time defined at 'Screen lock inactivity timeout' to pass or manually lock Signal.
- Open Signal.
- The 'TAP TO UNLOCK' message is presented.
- Try to unlock the app by tapping the screen.

**Actual result:**
- No pattern / PIN / password prompt appears and the app is never unlocked; the conversations list cannot be accessed.

**Expected result:**
- I should be asked to enter my pattern / PIN / password
- After a successful authentication the app should be unlocked and the conversations list should be presented.

#### Screenshots

![locked2](https://user-images.githubusercontent.com/60218583/120243757-1c7d5180-c271-11eb-9692-38b20578945f.jpg) ![locked1](https://user-images.githubusercontent.com/60218583/120243793-31f27b80-c271-11eb-9eb0-0da7e7bafb6b.jpg)
This might only be a theming issue, but for the Light theme the 'TAP TO UNLOCK' text is not visible.

#### Device info

- **Device:** Samsung Galaxy Note 3 LTE (SM-N9005)
- **Android version:** rooted Android 4.4.2 with various system apps (like play services) uninstalled
- **Signal version:** 5.11.5

#### App state

- Signal messages and calls registered, SMS and MMS disabled, PIN created

#### Link to debug log

https://debuglogs.org/da41062075608535915c1bf95a4bb106812b97313bc26e328b818c2a77e215a9

**Comment by floss4good** [comment]
Thanks for the hint, @Sgn-32!
I use a PIN for unlocking my Android device, but until now I didn't knew how this works with Signal because, as already mentioned, even though I have seen this 'TAP TO UNLOCK' message many times, I've almost never had to tap since it was self-unlocking after a second or so.

Anyway, I tried all the screen lock methods and the issue also occurs for 'Pattern' or 'Password'. But after selecting 'Swipe' or 'None' I can open the app (since it is actually disabling the lock for these methods).

Also checked this on another device (with LineageOS) and the Signal unlock worked as expected.

As an workaround, in order to be able to use Signal while keeping a secure screen lock method for my device, I used the following steps:
- Go to your device settings and select 'Swipe' or 'None' for 'Screen lock'.
- Open Signal; it should now unlock (although you might have to wait a few seconds or force stop the application before this step).
- Go to your device settings and select a secure method for 'Screen lock': 'Pattern', 'PIN' or 'Password'.
- Go to Signal Privacy settings and disable the 'Screen lock' setting (this step should be done before Signal gets locked after the time defined at 'Screen lock inactivity timeout' passes).

I will update the title and description of the issue since now I know that it occurs only in certain circumstances.

**Comment by floss4good** [comment]
Since I no longer have access to that device (with that specific, old, OS) this issue is not relevant anymore from my point of view (therefore it can remain closed).

**Comment by baack** [comment]
Does Signal expect user to share the encryption password of the phone? What is unlock password then? 

If it does. then it is insane and is a security disaster to ask for encryption password. 

Please reopen the ticket, the issue still exists on the latest Android version.
