### ISSUE TITLE
Colored contact name instead of colored message.

### ISSUE THREAD

**Issue by gartenriese2** [signalapp/Signal-Android#11344]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening a group conversation, the contact color is used for the name of the contact in the conversation bubbles instead of for the bubble itself.

### Steps to reproduce
- Open any group conversation that contains messages from someone else.

**Actual result:**  The color of the conversation bubble is gray. The name of the contact inside the conversation bubble is colored.

**Expected result:** The color of the conversation bubble is colored. The name of the contact inside the conversation bubble is white (I'm not sure what color it was before).

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 11
**Signal version:** 5.13.2

**Comment by Bolpat** [comment]
It's #8245 all over again. Please tell me this is an error and not a design choice. Having a clear visual cue who wrote what in a group message is important. But now, all bubbles but mine are gray, only the others' names are colored. I have Signal beta.

**Comment by gartenriese2** [comment]
> It's #8245 all over again. Please tell me this is an error and not a design choice. Having a clear visual cue who wrote what in a group message is important. But now, all bubbles but mine are gray, only the others' names are colored. I have Signal beta 5.13.2, too.

I don't think it's the same bug as back then. Back then, the bubble color of your own messages was the color of the contact. Now, the bubble color of your own messages is a color independent of the contact color that you can set yourself. Which is fine, I guess. Not something I'll be using, but maybe others will. (I think a setting to switch the color of all your conversations at once is missing, though. Yesterday, I had to go through all my conversations and change the color to be the same color for all conversations, that was kinda annoying.)

**Comment by greyson-signal** [comment]
Hi there, this was an intentional change. We're discussing it on the forum [here](https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/491).
