### ISSUE TITLE
Conversation color picker in settings does not work

### ISSUE THREAD

**Issue by gartenriese2** [signalapp/Signal-Android#11346]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When setting a conversation color through the app-wide settings, the color is not applied.

### Steps to reproduce
- Open any conversation. In this example, let's say the conversation color is green.
- Go to app settings (*not* conversation settings) and set the color for all conversations to blue.
- Open the conversation again.

**Actual result:** The conversation color is still green.
**Expected result:** The conversation color should be blue, like it's set in the app settings.

### Screenshots
![Screenshot_20210531-084417](https://user-images.githubusercontent.com/4339033/120152659-08dcd700-c1ee-11eb-864c-65c85caad30d.jpg)
![Screenshot_20210531-084510__01](https://user-images.githubusercontent.com/4339033/120152691-12663f00-c1ee-11eb-9e56-c354f39457ba.jpg)
![Screenshot_20210531-084604__01](https://user-images.githubusercontent.com/4339033/120152738-214cf180-c1ee-11eb-80c8-23ec6ae54107.jpg)

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 11
**Signal version:** 5.13.2

**Comment by bme13** [comment]
Hi, I think that after the upgrade to 5.13 the existing conversation colors are handled as custom colors. If you want to set all conversation colors at once you first have to reset the colors. E.g. In chat color & wallpaper chose Reset chat colors->Reset all colors. After that the selected color is applied to every conversation. (At least it was for me)

**Comment by gartenriese2** [comment]
@bme13 That worked for me, thank you.
