### ISSUE TITLE
number verification requirement seems back-asswards

### ISSUE THREAD

**Issue by CrackerjackCracker** [signalapp/Signal-Android#1135]
Hi, I meant not to be crude with the title, just direct.

As it is now, if you want to use the data/IM channel you have to associate TextSecure with your mobile number. I realize that "data channel" refers to mobile data plan, which of course should require a phone number, but if userperson wishes to use TextSecure over wifi purely as an IM, it is bizarre to ask for phone number verification. So, at this point I'd like to suggest a "wifi only" option at hangin' out with the setup wizard time, wherein no number is asked for. Shouldn't IM over wifi, which has no technical need for a number, be the option that does not request it for setup? Obviously mobile communication must; but wifi has no justifiable reason to.

I hope that requesting a number isn't considered an "anti-abuse" measure, as if users who have accounts with telcos are sweet little darlings who'd nary hurt a fly, but wifi users are criminals from the wrong side of the tracks; Telegram seems to do this too, it sucks.

If it's just about spam accounts, there are many ways to demand "proof of work" from a user. To use someone's account with a telco to verify that they are an actual individual sort of flies in the face of the modern countersurveillance movement.

Thanks for your excellent work, thanks for the new IM feature which is awesome, and thanks for reading.

**Comment by ghostlands** [comment]
Did the this page in the roadmap fly out the window?

**Comment by ghostlands** [comment]
Did this page in the roadmap fly out the window?
