### ISSUE TITLE
Signal chat colours swapped in 5.13.2 beta

### ISSUE THREAD

**Issue by kmdm** [signalapp/Signal-Android#11358]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the latest Signal beta 5.13.2 the colours have swapped round. 

Usually the other person is the set colour and your own messages are in the dark colour. 

Now they've swapped round and your own messages are shown in the selected colour.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

Open any conversation

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Google pixel 4a
**Android version:** 11
**Signal version:** 5.13.2

**Comment by cody-signal** [comment]
This is intentional, see the forums for more information: https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048
