### ISSUE TITLE
Multiple seconds of delay before audio works when answering voice or video call

### ISSUE THREAD

**Issue by spagy** [signalapp/Signal-Android#11354]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

#### Video call
When I receive a call, I press the green button to start the call.
The screen remains unchanged, still displaying the buttons to answer the call. 
After multiple seconds I will hear a noise that indicates the start of a call.
The screen shown during the call then appears and video becomes visible.
At the point when the video becomes visible, the call duration is usually already about 12 seconds.

#### Voice call
When I receive a call, I press the green button to start the call.
The screen changes to the normal in-call screen, I can see the duration of the call at the top of the screen, the seconds start to count.
However, I cannot hear the other person and I don't think they can hear me.
After multiple seconds I will hear a noise that seems to indicate the start of a call.

### Steps to reproduce
- Have someone call you, video or voice, from Android or iOS (desktop untested)
- Answer the call

**Actual result:** The call will start, but there is no audio or video for multiple seconds. This causes confusion and results in lots of calls starting with "can you hear me"s.
**Expected result:** The call starts audio and video work almost instantaneously (within less than a second at least).

### Device info

**Device:** Motorola Moto G6
**Android version:** 11
**Signal version:** 5.11.5 

### Link to debug log

https://debuglogs.org/65d25d427534c953fe6c607bb4348d1f7f698c9bd6b06eadbdc028f973a58780
To my untrained eye it looks like the call is answered at 2021-06-01 18:29:00 and video becomes visible at 2021-06-01 18:29:12

**Comment by spagy** [comment]
this is still an issue.

i can submit more logs if that's helpful, not really sure if there's any other way i can progress this.

if there's anything useful i could do to help track this down, i'd be happy to help

**Comment by spagy** [comment]
thanks for re-opening the issue.

i'll provide some updates on the issue as well as a few debug logs.

## updates

* this affects both calls that i make and that i recieve. (it's possible this isn't a change and that i just only tested answering calls not making calls when i raised this issue.)
* the video now starts as soon as the green answer button is pressed. you can see the other person for about 10-12 seconds before the a 'ping' noise indicates that audio is connected and you can start your call.

this affects _almost_ every call. although, today i answered a call and unexpectedly the audio was connected straight away (or at least it wasn't the normal 10-12 second delay). i have a debug log from just after this call. i cannot remember any other recent video call, regardless of who started it, that didn't start with a delay.

## debug logs
* [receiving a call, no delay](https://debuglogs.org/android/5.35.3/e8bf23c5067c0d9da3e98696188a7340dbed01a8cf26b66399fdc764cc7abfe8) (exceptional)
* [making a call, with delay](https://debuglogs.org/android/5.35.3/6657f443e23dc7567de46d22b57d9af34bf54d220b771aa3e0a62b6154a8012a)
* [receiving a call, with delay](https://debuglogs.org/android/5.35.3/0ac7cb0903add788ef78fc340b652e420b760a09527617cdb60f48c008e006df)

**Comment by cody-signal** [comment]
Could provide timestamps of when the delayed calls were made/received? The logs have multiple calls in them so it's hard to know exactly which ones are experiencing the problem.

**Comment by spagy** [comment]
yep, will do. the last call in each log should be the relevant one. i've edited my comment above to include the timestamp (provided in the app UI) of the call next each debug log link.

i think debug log links used to point to plain text files but now point to encrypted or compressed logs that i don't know how to view. are the logs only available to signal contributors or is there still some way for me to view them?

**Comment by cody-signal** [comment]
Thanks!

They are compressed gz files now to save data/space. You can extract them by downloading the file, adding .gz to the end and then using gzip to decompress them into raw text.

**Comment by spagy** [comment]
fab, thanks! i got as far as running `gunzip` (without adding `.gz`) and promptly gave up when it didn't work :)

**Comment by spagy** [comment]
i no longer have this issue and haven't had it for a while (years?)

seems like no one else is having this issue so will close!
