### ISSUE TITLE
Messages to non Signal users sometimes are not sent at all

### ISSUE THREAD

**Issue by sputnick-dev** [signalapp/Signal-Android#11355]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x]  have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages to non Signal users sometimes takes forever

### Steps to reproduce
- type a message, can be a new contact or a old one, same thing
- hit 'send'
- that reproduce the bug, the checkmark will never apperas
- if I kill the app, message are sent usually 
- 
**Actual result:** Checkmark not validate
**Expected result:** Double checkmark and message sent
### Screenshots

![](https://i.imgur.com/tuGOP9c.png)

### Device info

**Device:** Galaxy A5, a5y17lte
**Android version:** 10,  LineageOS 17.1 (clean recent install)
**Signal version:** 5.8.10

**Comment by BigOdie77** [comment]
Hey, 

I've got the exact same issue. 

**Bug Description:**

When sending text messages to friends/family not on signal, or sending via "unsecure message" message is not sent and constant idling symbol is seen.

I've tested with a friend of mine who is also on signal, we sent the following combinations back between each other
Secure Message - With and Without Wifi connected - Successful
Insecure Message - With and Without Wifi - Mine keeps idling, while his went came in fine

I've noticed this with friends and family who are not on Signal quite often then not. Over a large length of time the messages will usually be sent, but its not perfect (off/on device even)

**Steps to Reproduce**

- Send a message to any contact or new via "Insecure SMS"
- Observe loading circle and no update within a reasonable time

Conversely sending a "Secure SMS" is received and check marked or double check marked within a reasonable time frame

**Screenshot**
![Screenshot_20210614-225113](https://user-images.githubusercontent.com/16144730/121987365-59177580-cd66-11eb-93ee-a55c3fa61b8d.png)

**Device Info**
**Device:** Google Pixel 2
**Android Version:** 11 - No other updates available
**Signal Version:** 5.13.8

**Comment by x539** [comment]
I remember me having a similar problem until I changed some setting.

Does it help to turn "Wifi Calling" compatibility mode ON?

Settings -> Chats -> SMS and MMS -> "WiFi Calling" compatibility mode -> ON

**Comment by xxxxme** [comment]
I also have this issue, but it's not consistent. 
Oneplus 7T Pro,  AOSIP 10, microG 0.2.21.212158, signal 5.15.6.87300 from F-Droid.

**Comment by PieterHartzer** [comment]
I am experiencing the same problem for all SMS messages using either of my sims.  It only started recently and worked in the past.  Receiving messages works fine.

Phone: Google Pixel 3a
Dual sim: Physical UK based sim and Spanish eSim.

I managed to get it working again as I was typing this. 

1. Settings -> Apps & Notifications -> SMS Permissions Controller -> Signal -> Select Deny and then Allow again.
2. Settings -> Apps & Notifications ->  Default SMS App -> Select Messages and then Signal again.
3. Restart the phone.

This automatically fixed the issue and an SMS I sent two weeks ago automatically went through.

Note: This stopped working immediately after I sent an MMS.  Not sure whether this is coincidence or not.

**Comment by krychu90** [comment]
I have the same issue. My sms is not sent to non-signal users (but sent icon appears).
