### ISSUE TITLE
wrong camera  when trying to scan QR code for linking device

### ISSUE THREAD

**Issue by ggrrll** [signalapp/Signal-Android#11357]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

cannot link device from desktop client because the android app activates the wrong camera, to scan the QR code 

### Steps to reproduce

try to link device --> scan QR code

**Actual result:** 

front camera opens (I tried to scan the QR code, although uncomfortable -- the code is not read)

**Expected result:**

back camera should open -- in order to scan the QR code

### Device info
**Device:** Xiaomi A2
**Android version:** 10
**Signal version:** 5.11.5

**Comment by Sgn-32** [comment]
Please submit a debug log directly after trying to scan a QR code.

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

when scanning for safety number verification, is also the back camera chosen?

https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-#safety_number_view

**Comment by ggrrll** [comment]
I cannot find a the sub-menu described in that link (account > advanced -- there is no 'advanced' in my app version )

**Comment by ggrrll** [comment]
> Please submit a debug log directly after trying to scan a QR code.
> 
> https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

I cannot find a the sub-menu described in that link (account > advanced -- there is no 'advanced' in my app version )
 
> when scanning for safety number verification, is also the back camera chosen?
> 
> https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-#safety_number_view

yes, same problem

**Comment by ggrrll** [comment]
btw, there might be something weird with the way Mi A2 handles the camera...
 I have the same issue for instance with https://stocardapp.com/en/ch

**Comment by Sgn-32** [comment]
> I cannot find the sub-menu described in that link (account > advanced -- there is no 'advanced' in my app version )

Sorry, with 5.12 there was a change in the menu structure. Seems that the support articles are not actual.
The debug log is now in the Signal settings > Help

**Comment by ggrrll** [comment]
here you go
https://debuglogs.org/f02f92bfedfcf1e2d6c301045405cb66159a2b7357b1943e1961e112439762b5

**Comment by greyson-signal** [comment]
I'm confused by the specifics here. If you're scanning a QR code, you'd *want* to use the back/rear camera, yes? The camera that's on the opposite side of the screen? So you can point the phone at the QR code while still seeing the screen?

Just want to make sure we're not using the same name for different things.

**Comment by ggrrll** [comment]
sorry, my confusion -- I edited the issue

**Comment by ggrrll** [comment]
looks fixed -- thanks
