### ISSUE TITLE
Unable to message newly added contact

### ISSUE THREAD

**Issue by ajeshh** [signalapp/Signal-Android#11356]
If I have not messaged a contact before on signal or if I add a new contact, it does not let me message them. The only way I can message new contacts is if they message me first. 

Pixel 5 and have the latest version of Signal installed.

**Comment by DonovanDiamond** [comment]
I have the same occur very frequently with some of my organization's staff and myself. We use mainly Samsung A or S series phones.

**Comment by greyson-signal** [comment]
Do contacts appear if you pull-to-refresh on the contact selection screen?
