### ISSUE TITLE
Hard to scroll emoji bar when using bubbles since 5.13

### ISSUE THREAD

**Issue by sivaraam** [signalapp/Signal-Android#11369]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In 5.13.7, I find it difficult to use emojis with bubbles. While it’s a lot better in 5.13.7 than how it was in 5.13.6, it would be great if there was some more space for scrolling. The top bar appears to be taking up too much space. Before 5.13, at least one line of emoji used to be visible.

### Steps to reproduce
- Open a conversation bubble
- Tap the message box to open the keyboard
- Tap on the emoji icon

**Actual result:** Observe that not even a single line of emoji is visible making it difficult to scroll.
**Expected result:** At least a single line of emoji should be visible to aid scrolling.

### Screenshots
![image](https://user-images.githubusercontent.com/12448084/120889733-31b10200-c61c-11eb-917c-ea16d5c77908.png)

### Device info

**Device:** OnePlus Nord
**Android version:** 11
**Signal version:** 5.13.7

**Comment by psisquared2** [comment]
I second this issue. For me, it appears even when Signal is in full screen. I assume that the layout change was not tested on older devices with lower screen resolution (mine is 1440 x 2560). In past versions, I would see 4 or 5 rows of emojis without scrolling, now it only shows 2. As can be seen in the screenshot, more than 50 % of vertical space is dead space now. I would greatly appreciate a reconsideration of this layout at least on lower screen resolutions.
![Screenshot_20210703-104830](https://user-images.githubusercontent.com/17198703/124361505-cc0e6080-dc2f-11eb-883c-2635196cc54e.png)


### Device info
**Device**: Samsung Galaxy S6
**Android version:** stock Android 7.0
**Signal version:** 5.15.6

**Comment by sivaraam** [comment]
I'm not able to reproduce this anymore in v5.30.0. So, closing this. Let me know in case this is still relevant.
