### ISSUE TITLE
Camera rotating randomly during video call

### ISSUE THREAD

**Issue by SinTan1729** [signalapp/Signal-Android#11367]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Camera is rotating randomly during video call

### Steps to reproduce
- Make a video call

**Actual result:** Camera rotates randomly during video call.
**Expected result:** Camera should always be in portrair (since auto rotation is off).

### Device info

**Device:** Redmi K20
**Android version:** 10
**Signal version:** 5.13.3

It's also happening on a Samsung Galaxy M30 (same versions).

### Link to debug log
https://debuglogs.org/483c51947275234f6b894ece3202b21d85ca1b6429b30c4a425f9f753b600269

**Comment by cody-signal** [comment]
When you said randomly, do you mean if the phone is stationary the feed will rotate, or are you moving the phone around and the video feed is rotating with it when you don't expect to?

**Comment by SinTan1729** [comment]
It happens when I move around a little. Usually gets fixed after rotating it back and forth a few times (not always though). But it really shouldn't happen.

**Comment by rawlife56** [comment]
Hey @cody-signal 
I've been requesting this since forever. Send an intent to the device to rotate instead of just rotating the calling screen which is very sensitive and confuses the user.

**Comment by SilverMight** [comment]
This is a horrible issue that make video calls unusable. Why is auto rotation being ignored??

**Comment by xcelente** [comment]
I am here also for the same reason. It's happening very often, flipping vertically. Randomly tilting the phone will sometimes fix it but most of the time I have to turn off the cam and then back on again. But then a short while after it will flip vertically again. It's also happening to the person I'm calling. Very annoying and verging on unusable.

I don't want any picture flipping, not even edge cases.

Whatever is causing this, it seems very sensitive.

**Comment by samsunga50** [comment]
Same bug happening here. Samsung A50. If the other user rotates their phone by 90°, then I see them upside down, the buttons are also rotated by 90°, auto rotation being on or off doesn't matter.

**Comment by samsunga50** [comment]
> When you said randomly, do you mean if the phone is stationary the feed will rotate, or are you moving the phone around and the video feed is rotating with it when you don't expect to?

When the other rotates their phone by 90°, you see them upside down on your phone.

**Comment by xcelente** [comment]
Yes, still happens and quite predictably. Basically the other user is tilting their phone at a certain angle and then it flips. Personally, I would rather it didn't auto-rotate at all.

**Comment by xcelente** [comment]
Am curious what is happening with this issue? I've been applying Signal updates yet this remains. Can someone explain why the video needs to rotate in the first place? If, for some strange reason, you don't want to remove this "feature", then can you add a "Do not rotate" option to Settings?

When the video rotates my end, the other side of the call sees me in the normal rotation. Turning my phone upside down to compensate then makes me upside down to the other party. I'm thinking, maybe when you're testing this, you're doing it as civilized people in upright chairs and sitting at desks, which is not how real world people use their phones! lol

**Comment by GoldenDragonfly** [comment]
Nothing happened. I don't think dev team going to fix this bug. You can see more details about this bug here 👇 https://community.signalusers.org/t/disable-signals-auto-rotation-implementation-in-video-calls/42264

**Comment by alex-signal** [comment]
Rotation is controlled by a bit sent by the other caller, so it can change if they rotate their device. We get that the implementation is not the best, and we're taking a look at it :)

**Comment by xcelente** [comment]
I think you're assuming the other person rotates their phone by mistake and you're trying to auto-correct it. I really think rotation should be under my control, not the other side. You could just provide a manual rotate button, but if you want to de-clutter the interface then maybe shake-to-rotate?

**Comment by GoldenDragonfly** [comment]
Haven't fixed yet. Oh god.

**Comment by rawlife56** [comment]
At this point, I totally lost hopes on the signal's calling efforts. It is extremely buggy and power angry at the same time.
