### ISSUE TITLE
Signal not showing as an option on any of my contacts in the system contacts app

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11362]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I see "Audio-call using WhatsApp", "Video-call using WhatsApp" and "Message using WhatsApp" on many of my contact in the system contacts app, however Signal is not shown as an option on any of my contacts, even on ones which are able to message me on Signal.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Monterola Moto G7 Plus
**Android version:** 10.0
**Signal version:** 5.13.4

### Link to debug log

https://debuglogs.org/c33eec78a75f510b39d1a4604e0e687dc644aca8da6cc1c1b8b4014f214f57ea

**Comment by greyson-signal** [comment]
I believe there was a bug that was patched in 5.13.3, but you may still have to pull-to-refresh in the contact select to get the badges back. Is the badging still missing after doing that?

**Comment by Meteor0id** [comment]
@gram-signal tis isn't within the Signal app, tjis is within the Android Contacts app. Signal is not showing as an option while WhatsApp is.

**Comment by Meteor0id** [comment]
Oh hold on, refreshing contacts in the app also fixes the issue in the system contacts. That's what you meant.

But how will this refresh get triggered for people who hardly ever open the contscts list within Signal? Shouldn't Signal occasionally refresh the list in the background, or at least once to fix this bug for anyone who is still affected? @greyson-signal

**Comment by greyson-signal** [comment]
We do a periodic refresh every couple days. You probably just hadn't hit it yet since getting the new release.
