### ISSUE TITLE
Text is in English (not the language I use in signal)

### ISSUE THREAD

**Issue by Xrasure** [signalapp/Signal-Android#11363]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The text about new colors is in English(check attachment)

### Steps to reproduce
Download newest version (I'm using the beta)
Open the app

**Actual result:** English popup
**Expected result:** popup in the language I use in signal 

### Screenshots

![Screenshot_20210603-155802__01.jpg](https://user-images.githubusercontent.com/60069045/120657607-f16b4b80-c484-11eb-898a-44bd5015d1fc.jpg)

### Device info

**Device:** OnePlus 6t
**Android version:** 10
**Signal version:** 5.13.3

**Comment by Sgn-32** [comment]
Which language you are using? Most likely the string has not yet been translated in 5.13.3.
5.13.5 beta is released since a hour. Please test this new version.

**Comment by Xrasure** [comment]
> Which language you are using? Most likely the string has not yet been translated in 5.13.3.
> 5.13.5 beta is released since a hour. Please test this new version.

Im using german

**Comment by piratenpanda** [comment]
That's typical for betas that translations come in at the end of the cycle.

**Comment by greyson-signal** [comment]
Yeah, so during beta we're often releasing things before they're fully translated. Usually they'll trickle in during the beta, and we'll have good coverage by the time we go to production. Thanks for being a beta tester!
