### ISSUE TITLE
Reading marks not working properly in group chats (?)

### ISSUE THREAD

**Issue by deesnook** [signalapp/Signal-Android#11368]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not sure if this really is a bug or intended behavior, but the reading marks do not seem to work properly in group chats. A message is marked as read as soon as the first person in the group has read it, regardless if the message hasn't even been delivered to the other group members. To my understanding a message should only be marked as read when all group members have read it

### Steps to reproduce
- send message in group chat
- wait for the first person in group chat to read it

**Actual result:** The message is marked as read
**Expected result:** The message should only be marked as read if all group members have read them

### Screenshots

In this example, the message has been sent to the two other group members at 0:08h. At 7:40h one of the two has read the message. The other one hasn't yet. Still, the message is marked as read
![Screenshot_20210601-092059_Signal_an](https://user-images.githubusercontent.com/17967431/120868010-5f059d80-c593-11eb-9e60-0a2de6c3dc1f.png)

### Device info

**Device:** OnePlus 3T
**Android version:** 18.1-20210509-microG-oneplus3
**Signal version:** 5.12.3

**Comment by vaibspider** [comment]
I guess this is how they have designed it -- a message sent in a group will be marked as read if at least one person in the group reads it.

**Comment by deesnook** [comment]
Yeah maybe. Not sure if this is a good design choice though. The purpose of reading marks is to give quick and easy information about whether the message has been read without having to look at the message details. In a group chat, this purpose is essentially defeated by this design, because the info that one of n members of the group has read the message is of very limited use. You can neither infer who has read it, nor if all members of the group have (finally) read it. Which means you have to go to the message details anyway if you want to get meaningful information. Doing it the other way would at least mean that I can immediately see that everyone has read it. 

Also it's a marked (pun intended, hehe) departure from what other messengers do. As far as I'm aware, e.g. both WhatsApp and Threema mark messages in group chats as read only when all members have done so

I'll leave the issue open for now

**Comment by Sgn-32** [comment]
To do this, however, all members would have to have activated the read receipt. If only one member has disabled this feature, the message will not be marked as read. At that time (beta phase) the design decision was made, but I can't find it at the moment. I think it was 2019.

**Comment by Tursko** [comment]
This is how it's designed. Not only that but some people could have their read receipts off. So as long as 1 person (with read receipts on) reads the message, the message is marked as read. 

This isn't an issue and should be closed. Feature requests and overall design discussions are found on the forums. https://community.signalusers.org
