### ISSUE TITLE
chat color picker saturation can't reach 100%

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11371]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I thought initially my phone simply can't display the color cyan very well, but I now noticed that the cyan looks more like cyan on the hue picker than it does on the saturation picker and in the preview. I suspect the real issue is that the saturation picker doesn't let me reach 100% saturation.
I don't know of a tool to analize these colors on my screen, but I encourage you to analize the color of the hue picker and the saturation picker in the included screenshot.

The satuafion picker should allow to choos 100% so my cyan will actually look like cyan.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20210606-111922](https://user-images.githubusercontent.com/34976212/120919377-8e162f00-c6b9-11eb-84f8-372f9c94715c.png)

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0.0
**Signal version:** 5.14.0

**Comment by greyson-signal** [comment]
For now, saturation is kept within bounds so that you could read white text over top of it. In the future, we may allow brighter colors and have the text switch over to black, but not for now. Thanks!
