### ISSUE TITLE
Report successful backup restoration to user

### ISSUE THREAD

**Issue by hwinnemoe** [signalapp/Signal-Android#11370]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the backup restoration process is finished, no feedback is reported back to the user. The screen looks like the backup restoration process was never started and I can start the process again. I did try this twice. By inspecting the size of the Signal app in the system settings, I was able to see that it actually imported the backup. I checked the debug log for errors but did not find any errors regarding the backup process. I then used the registration steps and was able to restore the app to full functionality.

### Steps to reproduce
- Create a backup
- Reinstall Signal
- Start "Restore backup"

**Actual result:** There is no feedback after the restoration process finishes.
**Expected result:** There is a visible feedback to the user that informs the user that the process successfully finished and then continues to the registration process.

### Screenshots

- none

### Device info

**Device:** Sony Xperia Z2
**Android version:** 6.0.1
**Signal version:** 5.12.3

### Link to debug log

https://debuglogs.org/c2286c90652b5efa90537a6314744ceafec4703fc299f5ec09685ce5f4e50921 
- captured directly after the backup import but before starting the registration process

**Comment by cody-signal** [comment]
Did you happen to minimize the app while the backup was restoring? It shouldn't matter, but there may be a bug that if the app goes into the background during the restore it may miss the event that the restore was successful.

**Comment by hwinnemoe** [comment]
The screen was not active while the backup was restoring, but I did not background/minimise the app.

**Comment by cody-signal** [comment]
Should be fixed in https://github.com/signalapp/Signal-Android/commit/6c55916cda36ce28044e79040eed595019c4da6d
