### ISSUE TITLE
when deleting message, please remove the option delete only for me

### ISSUE THREAD

**Issue by audioscavenger** [signalapp/Signal-Android#11383]
what is the purpose of deleting only for yourself?
once you deleted it for yourself by MISTAKE because you tapped with fat fingers, you cannot delete it for all because well, you don't see the message you want to delete/edit anymore
Please keep this app simple. The simpler the better.
happened to me many times

thanks for considering this improvement

**Comment by hldrm** [comment]
maybe there is another way of achieving your goal which does include taking away a feature that some other users actually use

**Comment by rehork** [comment]
> what is the purpose of deleting only for yourself?
> once you deleted it for yourself by MISTAKE because you tapped with fat fingers, you cannot delete it for all because well, you don't see the message you want to delete/edit anymore
> Please keep this app simple. The simpler the better.
> happened to me many times
> 
> thanks for considering this improvement

The purpose might be like that I want to share some video to many different contacts, but I don't want to use my internal memory for storing it, so I send it and delete only on my side cause the intention was to share video with someone else but not store the history or video locally. It's about text, pictures, etc. Sometimes I want to send information and that's it I don't need to keep the conversation so I delete only on my side other person also can do that or not it's up to the person. 
Your perception of improvement might be a regression for others in terms of using the app.

**Comment by infinitewaveparticle** [comment]
I personally like the idea of extreme customization. There should be a setting for customizing the menu that appears when deleting a message. We should be able to customize everything about the app.

**Comment by greyson-signal** [comment]
Hi, thank you for the suggestion, but we use [the forum](https://community.signalusers.org/) for feature requests.

Concerning this particular request, there are many reasons that you may only want to delete something on your phone. To save storage, to delete an old conversation without notifying others, etc. And given that 'delete for everyone' is only available for 3 hours to prevent abuse means that this flow starts getting more complicated if people thought it happened all the time.
