### ISSUE TITLE
Clearing group chats deleted the groups?

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11399]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There exist no clear chat option. So I deleted !essages one by one spending about an hour. Once everything got cleared, I cliced the back button, and BOOM! 2 cleared chats frm 2 groups, and they were gone! I dunno what happened to that group...

### Steps to reproduce
- Clear all chat from a group
- Click back button to go to main menu where you can see all the chats
- You'll not see the group exisitng anymore on your phone.

**Actual result:** It just deletes the entire group from my phone! It's really annoying to see that!
**Expected result:** It shuld not remove the group from my phone if there exist no messages in it.

### Screenshots

I couldn't take screenshots as it all happened unexpectedly.

### Device info

**Device:** Nokia 6.1 Plus
**Android version:** 11 LineageOS
**Signal version:** Latest version

### Link to debug log

I dont think itnis necessary here.

**Comment by bme13** [comment]
Hi, I think clearing the entire chat removes the chat from the recent chat list which is the main view. You should still be able to share something to that group I assume or find it by going to compose (pencil) and search for the group name.
This seems related to #8406 and personally I think groups should be listed directly in the compose view which would make empty groups easier to find.

**Comment by pixincreate** [comment]
What! I dunno whether to call this a feature or a bug, as @bme13  suggested, searching via pencil icon shows the group.  But why!?  It's really annoying to see that. Groups MUST NOT GO! They should exit in the menu itself even if every chat is cleared
