### ISSUE TITLE
Feature Request: Rich Text / Markdown Support

### ISSUE THREAD

**Issue by larrydewey** [signalapp/Signal-Android#11397]
I think it would be absolutely amazing to be able to send a message to someone with an interactive list of checkbox items (shopping lists, todos, etc). I am not sure what the architecture around this might look like, but I think it would be a killer feature that no one else offers. I will provide a mockups of how I envision this looking.

**Comment by bme13** [comment]
Hi @larrydewey, please note that github is only used for bugs. Feature requests are handled in the community forum. There is actually already a related feature request. See https://community.signalusers.org/t/font-styling-for-signal-messages-e-g-using-markdown/612/140. Perhaps you can add your suggestion there. Thanks!
