### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by RagonEbker** [signalapp/Signal-Android#11395]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Android does not build

### Steps to reproduce
- follow the Build guide from the wiki
- Run ./gradlew build
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

**Actual result:** Error gets thrown
**Expected result:** Build finishes successfully

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0
**Signal version:** Newest Development branch

**Comment by Sgn-32** [comment]
5.15.0 is working again.

https://github.com/signalapp/Signal-Android/commit/2d93d74b9f513f4a41c150d921598e187a82e583

**Comment by RagonEbker** [comment]
Hello Sgn-32,

switiching to your commit did not fix the issue for me. Any help appreciated.
