### ISSUE TITLE
Not able to communicate

### ISSUE THREAD

**Issue by Darouls** [signalapp/Signal-Android#11404]
After last beta version update, it's not posible to receive/send message/call
With samsung a50 / android 11

**Comment by Darouls** [comment]
https://debuglogs.org/77c66a193b39e8d85a115336eddac9e8d58ea3539eb976863146dbdb1bdfd1ce

**Comment by oldeb** [comment]
Confirming the issue, it's been 2 days I no longer receive nor can sens messages.
When reinstalling it works for a short period of time (few jours) then the issue comes black.

**Comment by oldeb** [comment]
@cody-signal send I click "submit" on the debug log, it loads for like 40 seconds then display an error message "failed to send debug log"
I'm connected in 4G full signal and all the other apps are working fine ...

**Comment by oldeb** [comment]
Yesterday morning (like 5 hours before the bug occured again), I paired Signal to my computer and oddly it is still working fine on the computer but not on the phone ...
It's like something is preventing Signal to communicate on my phone.

**Comment by oldeb** [comment]
@cody-signal Is there a way to access the debug log via USB ?

**Comment by greyson-signal** [comment]
@oldeb You can use  `adb logcat > log.txt` to get logs. You can download `adb` here:
https://developer.android.com/studio/releases/platform-tools
