### ISSUE TITLE
SMS intent does not work for multiple recipients

### ISSUE THREAD

**Issue by Caerbannog** [signalapp/Signal-Android#11408]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Android the SMS intent (`vnd.android-dir/mms-sms`) can be used with multiple recipients. In this case, the recipient phone numbers are separated by semicolons ([one source](https://stackoverflow.com/a/23466981/1933135) amongst others). Both the legacy SMS app and the "Message" app by Google support this. Signal does not, and will try to send to a single invalid recipient (the long string containing semicolons).

### Steps to reproduce
- Connect your phone to a computer with adb installed
- Run this to simulate the intent:
`adb shell am start -a android.intent.action.SENDTO -d 'smsto:+33600000001%3b+33600000002'`
Note: I'm not sure of why `%3b` needs to replace `;`.

**Actual result:** If the default SMS application is Signal, redaction of a text message will start with a single invalid recipient (+33600000001+33600000002).
**Expected result:** If the default SMS application is Messages by Google, redaction of a text message will start with two recipients (+33600000001 and +33600000002).

### Device info
**Device:** Mi A2
**Android version:** 10
**Signal version:** 5.15.1

**Comment by zied777** [comment]
I confirm this issue.

**Comment by Caerbannog** [comment]
Yes, this is still relevant.
What's missing is code and a Pull Request.

The problem can be triggered from any app that sends the right intent.
An example is the "Contacts" app by Google.

Steps to reproduce: 
- open the "Contacts" app by Google
- in the sidebar, click on a contact label (for some reason this is needed, it won't work from the home screen)
- select two or more contacts from this label (long press shows a checkbox)
- in the action bar, click "Send a message"
- if prompted, select "Signal" as handler for the intent

Result:
Signal opens on a new conversation with a single invalid recipient, ex: +33600000001+33600000002.
Expected result:
Signal opens on a new conversation with a group of SMS recipients.
