### ISSUE TITLE
Incorrect "Available on Signal" notification

### ISSUE THREAD

**Issue by CJam25** [signalapp/Signal-Android#11403]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
From a person who made a Signal account around a year ago and did not use it anymore I received suddenly the notification that he is available on Signal. However, when I look at the chat, I could not send a Signal message only text messages. So, I refreshed my contact list in which there was no sign of the person in blue and the person came back and I received the notification again. Thus, now going back to my conversation I tried to change from text to Signal and succeeded however after some time it became back grey. Thus, now I wondering is the person back on Signal or is the person due to long inactivity removed from Signal and unreachable, but is this wrong processed? 

### Steps to reproduce
- Have a contact that has probably did not use Signal for a long time.
- Receive a notification he is available on Signal
- Don't have the possibility to send Signal messages
- Refresh your contact list
- Get the notification
- After some time, the ability to send Signal messages disappears (couple of seconds)

**Actual result:** Notification person is reachable via Signal. You now can send Signal messages but after a couple seconds this ability disappears and only text messages are possible. The person is also not show in the contact page anymore.
**Expected result:** Get a notification the person is available on Signal and be able to send Signal messages or get a notification the person is not reachable anymore via Signal and is than shown or not in the contact list in blue respectively.

### Screenshots
In this case I the send button was still blue. You can also see by refreshing the notification comes back, what you don't expect if the person was already reachable thus he was not reachable before. (Vandaag = Today)
![signal-2021-06-21-233959](https://user-images.githubusercontent.com/76212814/122887053-ca47c180-d340-11eb-8aa7-a84ae3a08f12.png)

### Device info
**Device:** Oneplus 3T
**Android version:** Lineage OS 18.1
**Signal version:** 5.13.8

### Link to debug log
https://debuglogs.org/20521dac0a22fd180dce8ac58ac0bf88372a5d9fdf9ce379b8e0a2da982328d0

**Comment by greyson-signal** [comment]
Hi there, seems like two places where we check registration status seem to disagree. We're looking into it!
