### ISSUE TITLE
Signal group invite link not working

### ISSUE THREAD

**Issue by Joeperdefloep** [signalapp/Signal-Android#11405]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

The group ivite link is spread over multiple lines and only the first line is recognized as a link. As a result it does not work. Adding random text before so it does not break after https://signal.group/ does not resolve the issue.

### Steps to reproduce
- on Android
- share an invite link through signal messenger

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

the link is not working - it tries to go to https://signal.group/

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

the link should work over multiple lines like it does with other links

### Screenshots

![image](https://user-images.githubusercontent.com/33122845/123002373-2860bd00-d3b2-11eb-8ab4-9638625b5e88.png)
![image](https://user-images.githubusercontent.com/33122845/123003034-e97f3700-d3b2-11eb-8ab7-d6e815bce57c.png)

### Device info

**Device:** Blackview BV9700Pro
**Android version:** 9
**Signal version:** 5.15.0

### Link to debug log

[link](https://debuglogs.org/c3454cd5a591697bf561cdc298d2e767c2644c26fb0781a087d6a2055cb53ccc)

**Comment by jeroen7s** [comment]
It's probably the # that's seen as an end for the URL, should definitely be fixed by signal

**Comment by Joeperdefloep** [comment]
That's funny, I mean '#' is more often part of an url to link to a specific part of a page. like in: https://en.m.wikipedia.org/wiki/URL#History

Weird that it is a terminating character...

**Comment by jeroen7s** [comment]
I also don't have the issue on Miui12 apparently (Xiaomi device)
maybe something specific with your device? or older android versions?

**Comment by greyson-signal** [comment]
We use the standard URL highlighting provided by the android system. It's possible that some manufacturers alter this behavior. We might be able to move to some standard non-OEM-dependent linkifier.

**Comment by greyson-signal** [comment]
I've switched to a compat library for linkifying things in 5.16. Hopefully that will help! Let me know if it's not working when we release that version, thanks!
