### ISSUE TITLE
Can not toggle Speaker Setting during Video call

### ISSUE THREAD

**Issue by ZagButNoZig** [signalapp/Signal-Android#11407]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If you are in a video call you have to disable your camera in order to toggle the Speaker setting and since it doesn't save that setting you have to disable your camera to enable speaker and the reenable the camera which is not very intuitive!

### Steps to reproduce
- Get into a video call

**Actual result:** 
**Expected result:** 

### Device info

**Device:** Samsung Galaxy S20 FE
**Android version:** 11
**Signal version:** 5.13.8

**Comment by greyson-signal** [comment]
Speakerphone should automatically enable in a video call. Is that not happening?

It sounds like you're in a video call, but want to disable speakerphone? Why is that?

**Comment by ZagButNoZig** [comment]
I have re-tested it and it automatically enables. So this should be fixed.
