### ISSUE TITLE
"Mute notifications" missing from the conversation's menu in group conversations

### ISSUE THREAD

**Issue by butla** [signalapp/Signal-Android#11402]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a group chat on the Android app, to get to "mute notifications" I need to go to group settings, which is inconsistent with how it works with one-to-one chats. Also, the desktop version has "mute notifications" in the conversation's menu.

Ok, I'm not sure if UI inconsistency counts as a bug (it does decrease usability), I can move this to the forum if needed.

### Steps to reproduce
- enter a group chat
- press the "three dots" menu (conversation menu) in the bottom right corner
- see that there is no "mute notifications"

**Actual result:** There's no "mute notifications" item.
**Expected result:** There **is** a "mute notifications" item, the UI is consistent across one-to-one and group conversations, also the same as on the desktop app.

**Comment by Tursko** [comment]
I reported this when the change was made and it was unfortunately deliberate. So this would be more of a feature request than a bug.

**Comment by butla** [comment]
Oh... Thanks for the info. I started watching the feature request at https://community.signalusers.org/t/re-add-option-to-mute-gv2-chats-via-the-context-menu/26284.

I'm gonna close this one then.
