### ISSUE TITLE
"Import SMS to signal" dialog doesn't appear while configuring the app.

### ISSUE THREAD

**Issue by salustre** [signalapp/Signal-Android#11417]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I wanted to move my signal messages to new device and also import my SMS messages to signal, restoring from backup works perfectly, but no SMS import dialog appears.

### Steps to reproduce
- backup messages
- reinstall signal
- start configuration wizard

**Actual result:** Signal is configured, and signal messages are restored.
**Expected result:** Signl should ask if user want to import SMS from system database.

### Device info

**Device:** Cubit Nova
**Android version:** 8.1.0
**Signal version:** 5.14.5

**Comment by greyson-signal** [comment]
We removed the SMS import option until we're able to fix some core issues with it, apologies!
