### ISSUE TITLE
Sharing something, the contacts i choose are changing.

### ISSUE THREAD

**Issue by tegutistgut** [signalapp/Signal-Android#11410]
```- [ ] I have searched open and closed issues for duplicates```
Yes
```- [ ] I am submitting a bug report for existing functionality that does not work as intended```
Yes
```- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports```
Yes
```- [ ] This isn't a feature request or a discussion topic```
Yes

----------------------------------------

### Bug description
The contact list changes after clicking on the contact but the message is send to the right contact. (See gif)

### Steps to reproduce
Go to any app where you can share anything. (File, link, Youtube Video, it doesn't matter). Then click on share and select Signal. After that tap the contact you want to send the message to. You'll see that the contacts changed visually to other contacts, but when you hit "send", the message is being sent to the real contact.

Beware: it doenst happen everytime. Try force stopping and clearing the cache

**Expected result:**
The contacts shouldnt change

### Device info

**Device:** Samsung Galaxy A51 
**Android version:** 11, OneUI 3.1
**Signal version:** 5.14.5

### Link to debug log
https://debuglogs.org/200b6a85c9446312c219e180923e419664c063d9c8fb8b2d88cf4358c34a25af

**Comment by A3r0Sp1k3** [comment]
Can confirm this on 5.14.5 as well.

For example, I share a photo to Signal. Tap on contact A, and it will change the name and icon to a random contact B (but still show contact A's correct phone number). This same behaviour will happen for a couple of the contacts in the list as well, but not all. Unselecting contact A brings all names and icons back to what they should be, and reselecting no longer does this.

Force closing the app and doing this again might leave contact A untouched, but change some other ones in the list. The name and icon it can change to doesn't even have to be a Signal contact, it can also change to a phone only one.

Scrolling through the contact list before tapping the contact stops this happening, and scrolling down and back up after selecting also reverts the changes to what they should be.

**Comment by greyson-signal** [comment]
This should be resolved in 5.15.x, which is rolling out to production. Thanks!
