### ISSUE TITLE
Crash on Android 6.0 immediately after startup - FileSourceProxy Open dupFd fail for file and other errors in log

### ISSUE THREAD

**Issue by ThiloteE** [signalapp/Signal-Android#11418]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- Signal closes itself at random times, but recently usually immediately after the startup. A message pops up that says a failure has occured. After it has done so, it will still run in background, but when i try to enter the program again, i can't. It will usually fail again.
- This whole process happens OFTEN, but NOT EVERYTIME.
- I can then close the program (that was still running in background) manually. I then usually wait a few seconds for my phone to process it and then try to open it again. Sometimes it fails again and i repeat the process, but often after one, two or three iterations, Signal actually opens normally and works just fine.

### Steps to reproduce
- Start Signal

**Actual result:** Signal closes itself
**Expected result:** Signal should not close itself and remain in the starting screen

### Device info

**Device:** OUKITEL C3
**Android version:** 6.0 (1470125231, OUKITEL-C3-V2.7-20160802)
**Signal version:** Signal 5.14.5 (866, 86601) (1c80e65) 

### Link to debug log
https://debuglogs.org/d50ff8965df134dc2162afc6c0b3130c7a0197a85c87a4ee1d391eab3ef1eb88

The debuglog was taken immediately after one of the crashes (today 30.06.2021 roughly 8:30 or something.)

If this has something to do with the old android version ... unfortunately my manufacturer doesn't support update to a newer version. I will have to buy myself a new phone for other reasons this year, but alas it will have to do its job for at least another 5 months or so, so yeah maybe this report helps in doing that and maybe it also helps others with such an old device. Thanks to anybody who might help in solving this :-)

**Comment by greyson-signal** [comment]
Hey there, are you able to see if there are any tombstone files that you could send to use? They'd be located on your phone at `/data/tombstones/`. If so, you can email them to me at greyson@signal.org and hopefully that'll give us a better idea what's going on. Thanks!

**Comment by ThiloteE** [comment]
Sorry, no tombstone folder in any of the data folders on the device. I don't have root access to /data/tombstones. Can't check. Do i really have to jailbreak root?

**Comment by ThiloteE** [comment]
I tried using 3 different programmes to root my device, but to no avail, they all failed half way through. (Kingo root, king root, Dr.Fone - Root) ...

**Comment by ThiloteE** [comment]
Here is another log taken directly after a crash this morning. To get a crash, i just repeatedly opened and closed signal (roughly 5-6 times or so), until the crash happened. This was done with my Wi-Fi repeater turned off.

https://debuglogs.org/7d2c6ca823e47092bc5760da28124326391c1b1f5ce5114aaa00c4f56ef5694b

I should mention that i am connected via Wi-Fi 4 (2,4 GHz) in medium distance to the router, but there are walls. I remember it crashed a lot more often, when i did not have my wi-fi-repeater installed. When the repeater is on, the signal goes through 2 walls, whereas when the repeater is off, it goes through 3 walls, which made me think, the crashes also could have something to do with the way the connection is handled.  Not sure if my repeater doing wonders, or if there was a patch/fix that was introduced at roughly the same time i installed my repeater. Since the crash doesn't happen every time, it is hard to verify. All i know is, that currently it crashes a lot less often. Signal is the only program that repeatedly crashes on my phone to be honest. Maybe i should try a clean install?

I can't seem to manage rooting it, so what can i do otherwise to help you?

**Comment by ThiloteE** [comment]
I managed to capture logs of the crash via logcat. I sent you the file via e-mail @greyson-signal just now.
