### ISSUE TITLE
Signal 5.15.6: Button for the Image-Quality-Selector disappears after a short time

### ISSUE THREAD

**Issue by wheelseal** [signalapp/Signal-Android#11425]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Button for the Image-Quality-selector is dissappeared.

### Steps to reproduce
Open a Chat and select a Image to send

**Actual result:** Button for the Image-Quality-selector is displayed at a very short time an disappear.
**Expected result:** Button for the Image-Quality-selector should be displayed all the time.

.

### Screenshots
![Quality Selector](https://user-images.githubusercontent.com/61382908/124203890-04058e80-dade-11eb-8062-4236cdfdbb49.jpg)

### Device info

**Device:** Sony Xperia XA2
**Android version:** 10
**Signal version:** 5.15.6

### Link to debug log
https://debuglogs.org/ca2dc845f6f4e2b2a205609a191e6f3641da6fb2895d20fa89f35d6fac2c1dba

**Comment by cody-signal** [comment]
What type of image are you sending? I'm unable to reproduce. We now hide the quality selector for content it does not apply to, which at this time is videos and gifs. Is the image a GIF? Does it happen with all images?

**Comment by u32i64** [comment]
@cody-signal This was first posted on the forum in [this](https://community.signalusers.org/t/34610) topic (as the OP later confirms [there](https://community.signalusers.org/t/34610/8), this is the issue they created). There are some more details in that topic.

**Comment by cody-signal** [comment]
@wheelseal is there a particular flavor of Android ROM you are running?
