### ISSUE TITLE
Can't install from Google Play Store

### ISSUE THREAD

**Issue by MiepHD** [signalapp/Signal-Android#11423]
- [x]  I have searched open and closed issues for duplicates

- [x] I am submitting a bug report for existing functionality that does not work as intended

- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

- [x] This isn't a feature request or a discussion topic

### Bug description
Installation not working on Google Play.

### Steps to reproduce
Have a Samsung Galaxy Tab s5e
Go to Signal's Google Play Store site

**Actual result:**
Can't install Signal from Google Play Store.

**Expected result:** 
Can install Signal from Google Play Store

### Screenshots
![SmartSelect_20210701-200049_Google Play Store](https://user-images.githubusercontent.com/63968466/124170259-7dce5580-daa7-11eb-922e-3680d4cec2e0.jpg)

### Device info

**Device:** Samsung Galaxy Tab s5e
**Android version:** 10
**Signal version:** 5.15.6

**Comment by alex-signal** [comment]
Hi! Signal on Android is not supported for tablets right now. There's a whole pile of work we need to do in order to make that a reality.

**Comment by simodmund** [comment]
hi dear ones,
but it would be really great if you could make this work.

**Comment by jlost** [comment]
It would be nice to see this? Disheartening to see the issue immediately closed, when this has in fact been an open issue since 2014.
