### ISSUE TITLE
Signal 5.15.6:  Thumbs up-Emoji in the Reaction-bar has the false color and i can`t change it

### ISSUE THREAD

**Issue by wheelseal** [signalapp/Signal-Android#11426]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Thumbs up-Emoji in the Reaction-bar has the false color and i can`t change it

### Steps to reproduce
Long press on a post and the Reaction-bar is displayed. 

**Actual result:** If I open the Reaction-Bar with long press on a Post the thump up-Emoji is not yellow. I try to change the color with the new settings and after a few time it works.

**Expected result:** If I open the Reaction-Bar with long press on a Post the thump up-Emoji should displayed yellow at the first time.

### Screenshots
![reactions](https://user-images.githubusercontent.com/61382908/124206328-6c0aa380-dae3-11eb-9c5c-c7b487d6771a.jpg)

### Device info

**Device:** Sony Xperia XA2
**Android version:** 10
**Signal version:** 5.15.6

### Link to debug log
https://debuglogs.org/ca2dc845f6f4e2b2a205609a191e6f3641da6fb2895d20fa89f35d6fac2c1dba

**Comment by alex-signal** [comment]
Variant icons will change appearance in the reaction scrubber according to individual usage. This is an artifact of when you could not edit the reactions menu yourself. I can bring this up with design to see whether we should remove this functionality now that you can pick and choose reactions at will.
