### ISSUE TITLE
Wrong contacts are selected in the "Share with" window when selecting a contact without an avatar.

### ISSUE THREAD

**Issue by snir** [signalapp/Signal-Android#11431]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing from a different app (e.g. Gallery), selecting a contact results in a different random contact being selected. When selecting a contact from the recent chat section, the result is 2 random contacts being selected - one in recent and one in the "all contacts" part.

### Steps to reproduce
- force close signal from the task switch pane.
- open gallery and share an image with signal
- select a contact **without an avatar**

**Actual result:** 1 or 2 random contacts are being selected
**Expected result:** The correct contact should be selected

### Device info

**Device:** Samsung S9+
**Android version:** 10
**Signal version:** 5.14.5

### Link to debug log
https://debuglogs.org/c2d4d9d5ba2fe9ab6c376ea9589cd8ac19c427a311f59f478a059d66f7b202c2

**Comment by alex-signal** [comment]
Hi! Thanks for the bug report! This issue should be resolved in 5.15.x, so please update to the latest Signal version.
