### ISSUE TITLE
Signal shows -1 days remaining for update to new version instead of version expired

### ISSUE THREAD

**Issue by abdulsmapara** [signalapp/Signal-Android#11438]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal shows -1 days remaining for update to new version.

### Steps to reproduce
- Wait for Signal version to expire till it shows "This version of Signal expires in -1 days"

**Actual result:** Signal shows shows "This version of Signal expires in -1 days"
**Expected result:** Signal app should show Version is expired, please update (i.e just update screen)

### Screenshots
![signal-version-expires-in_-1-days](https://user-images.githubusercontent.com/32198670/124376159-39b79c80-dcc3-11eb-83a7-37556da2ed64.jpg)

### Device info
**Device:** Samsung Galaxy A50s
**Android version:** 9
**Signal version:** Version before updating to 5.13.8

**Comment by alex-signal** [comment]
The public PR was accepted and will be coming soon to a 5.16.x near you.
