### ISSUE TITLE
When scrolling in a chat the date can be incorrect

### ISSUE THREAD

**Issue by linde9821** [signalapp/Signal-Android#11432]
When scrolling within a chat the date of the top message is displayed. 

![Screenshot_20210702-184554~2](https://user-images.githubusercontent.com/26818030/124349948-fe00d200-dbf1-11eb-815c-1a1c695c3803.jpg)

The date is updated when scrolling.  

But it seems that the date is updated to late. Meaning the date of the day before is sometimes shown even when no messages of the date are visible.

To illustrate the issue i provided some screenshots which show the behavior.

![Screenshot_20210702-184546~2](https://user-images.githubusercontent.com/26818030/124349916-e6294e00-dbf1-11eb-9978-38e99583c421.jpg)

![Screenshot_20210702-184551~2](https://user-images.githubusercontent.com/26818030/124349911-e32e5d80-dbf1-11eb-84cb-92a09e1de41d.jpg)

![Screenshot_20210702-184553~2](https://user-images.githubusercontent.com/26818030/124349917-e88ba800-dbf1-11eb-980b-27c55f34ec47.jpg)

It gets updated when scrolling a bit further. 

If this behavior is wanted then just close the issue.

**Comment by loku0** [comment]
do you have any isshu about battary ??
