### ISSUE TITLE
Insane battery drain on samsung A51 Running Android 11

### ISSUE THREAD

**Issue by loku0** [signalapp/Signal-Android#11433]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 I started noticing insane battery drain which didn't happen when I was using WhatsApp as my primary communications method. In 9 min chat its takes 1% battary 

### Steps to reproduce
- Own a A51 Device (Exynos) with same OS version as the screenshots
- Install Signal
- Insane battery drain

**Actual result:** Battery drains insanely fast when using the app
**Expected result:** is this ok??

### Screenshots

![image](https://user-images.githubusercontent.com/86878284/124353624-70d96f80-dc29-11eb-95c8-da14b9db0c6a.png)
![image](https://user-images.githubusercontent.com/86878284/124353778-5784f300-dc2a-11eb-976e-ea50f530105a.png)

### Device info

**Device:** Samsung Galaxy A51 / Exynos 9611
**Android version:** upgradable to Android 12, One UI 3.1
**Signal version:** 5.15.6

### Link to debug log
https://debuglogs.org/daafefc27b88227c579d0dd4e3ce3ea13221482e2773b131671ef9b014cc37e0

**Comment by alex-signal** [comment]
Do you mind attaching a debug log? We will have a better idea of what jobs are running, etc. that will give us a clue as to what's eating your battery.

**Comment by loku0** [comment]
@alex-signal okh sir

**Comment by loku0** [comment]
@alex-signal sir I have facing another issue while I chating with someone 40 min without call and voice chat my phone of display got heating but not too much .i am also used tested others apps WhatsApp ,threema, fb messenger when I using no heating... my phone battery has no problem I donno why this happen can see were is this problem ..   if  its problem plz fix this I like this but this condition I feel sad😥

**Comment by alex-signal** [comment]
@loku0 You're saying that being in a call specifically caused your phone to start heating? I'll pass this debug log onto the calling team.

**Comment by major-mayer** [comment]
The problem with Signal eating insane amounts of battery during calls is well known and exists for quite a long time. 

Just today I had a 45 min video call and lost about 40% of my battery, that's just incredible, but not surprising if you consider the heat that my phone generated...

**Comment by major-mayer** [comment]
For reference https://github.com/signalapp/Signal-Android/issues/9798

**Comment by C-Higgins** [comment]
I am also having this problem. Signal used 73% of battery in 35 minutes of usage. This problem only started happening in the last few days and is intermittent. 

This may be related to #11398 because while this was happening, I could not preview any ringtones, getting the message "Can't play while a call is in progress" or something, but no call was in progress. This was also after waking up in the morning.

**Comment by citizenserious** [comment]
I also have this problem on Android 11 with the v5.21.6. There is a massive battery drain. I already reinstalled Signal, than the problem was gone for about 2 days, but now it is has draining my battery again, so my battery is empty in around 3 hours.

**Comment by alex-signal** [comment]
It *sounds* like there might be some kind of really bad hot loop

Basically:

Thing A happens
Which triggers thing B
Which triggers thing A
etc.

I'll bring this up w. the rest of the devs and see if we can at least start getting some profiling done to detect these kinds of things and eliminate them.

**Comment by greyson-signal** [comment]
I'm going to merge this into #11031
