### ISSUE TITLE
gallery is only partly loaded.

### ISSUE THREAD

**Issue by Glasses8448** [signalapp/Signal-Android#11435]
### Bug description
When sending a picture, signal can't access my full galery anymore. The gallery is only partly loaded.

### Steps to reproduce
Send photo, wait till gallery loads

**Actual result:**  All my images in the gallery are visible
**Expected result:** gallery is only partly visible

### Screenshots
![signal-2021-07-03-181246](https://user-images.githubusercontent.com/53970121/124360665-54d6cd80-dc2b-11eb-9121-fc185fef12b7.png)

### Device info

**Device:**  Xiami Mi Mix 2
**Android version:** 11
**Signal version:** 5.15.6

### Link to debug log
https://debuglogs.org/34acc428b770fa08e76109ba8803dce2afedc4083f5f2f4bbd9a905289de2919

**Comment by Nisc3d** [comment]
Can you please attach a debug log? Without that a bug report is almost useless.

**Comment by Glasses8448** [comment]
edit: added link to debug log

**Comment by Tom-Archer** [comment]
Duplicate of #10394

**Comment by alex-signal** [comment]
Closing as a duplicate. Please note we are tracking this issue internally.

**Comment by DarkoVeberic** [comment]
Duplicate of #10394
