### ISSUE TITLE
Standardized ?params to prefill correctly, resulting in API issues (eg, QR code SMS template)

### ISSUE THREAD

**Issue by dylanh724** [signalapp/Signal-Android#11447]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For example, Taiwan gov't COVID tracking program will need me to register via QR code (that submits a pre-filled text containing the identity of the venue):

The result is an empty text compose with a broken "to" field (I'll edit this later with a screenshot). Eg:

`{smsNum}?body={body} : {realPhoneNumHere}{messageHere}`

The actual message has 0 prefilled.

### Steps to reproduce
1. Scan a QR code that has ?parameters to send a prefilled text message.
2. Watch the "to" field containing the entire API line.
3. Even if you filled the body and sent, it's still broken due to the to field being messed up.

**Actual result:**
Prefill params are all in the "to" area: Need to change default app to anything _except_ Signal to work (it's just you guys that don't follow these standards, it appears).

**Expected result:**
Message should be prefilled as standardized.

### Screenshots
TODO

### Device info

**Device:** Samsung S20+
**Android version:** 11
**Signal version:** 5.15.6

### Link to debug log

n/a

**Comment by dylanh724** [comment]
Still relevant.

**Comment by cody-signal** [comment]
Would you be able to provide a sample QR code and example of expected/actual data.

**Comment by dylanh724** [comment]
![image](https://user-images.githubusercontent.com/8840024/153624787-e1f2ab0c-8dec-4bae-bd08-9f53930954ec.png)

Randomly found this on Google. This seems to be a demo, so ignore the actual phone number (random Google-pulled example).

**Comment by FlorianObermayer** [comment]
Another example for broken parsing:

![image](https://user-images.githubusercontent.com/4497761/165554448-300fdb79-3971-40df-a42f-0e4d45288d17.png)

Here, the recipient will be parsed incorrectly, resulting in: `?body=www.whisp.ly/r/cjN0iYN`
