### ISSUE TITLE
Signal complain that I don't have Google Play Services while I have it [on LineageOS 18.1, Android 11]

### ISSUE THREAD

**Issue by ElucGeek** [signalapp/Signal-Android#11445]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've just updated my phone to Android 11 (coming directly from 9) by updating (I mean fresh install) LineageOS 16 to 18.1. Everything went quite smooth, I have GooglePlayServices installed and it works for all apps using it, I'm not rooted.

Signal worked for a day without issue, I could register, send/receive message and notification, and then after a day, Signal started complaining that Google Play Services was missing.

Now the notification: "Permanent Signal communication faillure!, Signal was unable to register with Google Play Services." If I click the notification I got a popup saying: " Signal won't run without Google Play services, which are not supported by your device."

This last sentence triggered me as it's twice false. Signal is supposed to working without Google (with WebSocket) and my device do have Google Play services installed and updated to the latest version, I'm logged to a Google account (thus I disable all sync as I don't use my account for other than Play Store).

On top of that, if I ignore the notification, Signal is working perfectly, without any delay in notification or whatever.

Any idea why it's doing that? I have used Signal since it was TextSecure and I was using it on CyanogenMod at the time, I have always used CM and then LineageOS (thus always rooted, it's no more the case) with Google Play Services and Signal has always worked without any single issue (like any other app). Now Signal is the only one have trouble so I don't think it's an issue on the ROM side or Play services side.

Any clue how to solve that, beside disabling the failure notification from Signal (that will prevent me to know when there will be a real failure then)?

### Steps to reproduce
Just wait that Signal complain.

### Screenshots
None

### Device info
**Device:** Xiaomi Mi Mix 2
**Android version:** Lineage OS 18.1, Android 11
**Signal version:** 5.15.6

### Link to debug log
https://debuglogs.org/faa5dd73a8446293d84bb9a1d8c6bb6e700b821a4417f7b75bb61357d4f64d68

**Comment by ElucGeek** [comment]
6 days and still nobody has any clue where to look for? I'm getting desperate, everything else if working fine, even better than LineageOS 16, just Signal app is not happy, I really don't get it why. And I have been using Signal since it was TextSecure always with similar setup without a single issue so far.
Any help is welcome.

**Comment by greyson-signal** [comment]
Hi there, looking at your logs, it appears that when we ask Play Services if they're available, we get back error code 9, which means `SERVICE_INVALID`. The documentation for that constant is `The version of the Google Play services installed on this device is not authentic.`

Signal hasn't changed anything with how it interacts with Play Services. My guess is that something is up with your ROM, or the version of Play Services installed on your device updated to add more checks around authenticity. I don't have much knowledge of your specific setup, so I can't really comment much on it further than that.

**Comment by ElucGeek** [comment]
Hi thanks for trying to help. In the meantime I think I figure out the issue, I have installed Shelter (from F-Droid) to create a work profile and isolate some app on my phone (mostly app that I use for work, especially Microsoft stuff). I have also installed a second copy of Signal in the work profile registered with a second number (I have a dual SIM but it might as well work with a SIM from another device). In the past it was never a problem but here it might be the issue. I have remove the second Signal app but I still had the error message, I then remove completely the work profile and Shelter then notifications were working again in Signal but still with the error message. After reinstall of Signal it looks OK so far. But know I really need to have separate working app, maybe I will try again without the second Signal app, to figure out if it's the work account created by Shelter that mess up or the second Signal app.

Another option is to re-install LineageOS with OpenGapps instead of MindtheGapps as in between my install and now, OpenGapps finally release an Android 11 version.

**Comment by RobertoWa** [comment]
how do u install signal messenger?

by apk or play store?

**Comment by ElucGeek** [comment]
Play Store

**Comment by UserX404** [comment]
@ElucGeek 
I also run on Mindethegapps firstly and switched to opengapps afterwards (LOS18.1) but i had no problems with Signal on both packages. 
So my thoughts are your issues has something to do with Shelter.

**Comment by akorn** [comment]
I think I hit a similar issue, and for me it's a regression.

My phone is a Oneplus 6 with the latest AICP (tried with 2021-12-06 and 2021-12-13 builds).

Signal used to to work fine until today when I upgraded it  to `Signal 5.28.5 (978, 97802) (c6d0ef2)` using apkpure. Now I get the same error notification about missing Google Play Services. Unfortunately I don't know how to check what the previous version I had was, but it can't have been older than a few weeks old.

In my debug log (https://debuglogs.org/9b61637fe8a5223d0ae91302962e984da43f0fb9315e31590e9a194c55bf303b) I also see `Play Services : false (9)`.

I've had this ROM for a long time and unfortunately I don't remember which gapps I installed, but I'm going to guess NikGApps.

Possibly interesting: the Lidl Plus app used to complain about missing Google Play Services for months on the same phone (while Signal worked), but the publisher fixed it somehow a few weeks ago. Maybe you guys broke whatever Lidl fixed?

Other apps that use Google Services still work.

**Comment by akorn** [comment]
Update: the Signal notification about the Google Services failure comes and goes. It'll be there for a few hours, then gone for a few, then back. There is no obvious pattern. I don't know if this is expected behaviour.

**Comment by greyson-signal** [comment]
Hi there, unfortunately we don't support any Play Services alternatives. If you have real Play Services, we support that. If you don't have any Play Services, we also support that. But if you choose to install fake Play Services, you're on your own, sorry :) Feel free to reach out on [the forum](https://community.signalusers.org/) to see if anyone has similar issues. Thanks!

**Comment by akorn** [comment]
Excuse me, but how are these Play Services "fake"? I was under the impression that all the various "gapps" packages (including NikGApps, OpenGapps, MindTheGapps etc., except microG) were the real proprietary thing, by Google, just repackaged. I can certainly update its components from the Play Store, it's signed by Google etc.

**Comment by akorn** [comment]
FWIW, uninstalling Signal, then reinstalling it, seems to have helped in my case; at least the phantom "no google play services" notification hasn't popped up in a day or so.
