### ISSUE TITLE
Signal crashes with network connection

### ISSUE THREAD

**Issue by timpauli** [signalapp/Signal-Android#11459]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes directly after starting the app when a network connection is available.

### Steps to reproduce
- don't be in airplaine mode
- open Signal
- experience crash

### Device info
**Device:** Oneplus 3T
**Android version:** Android 11 (LineageOS with microg 18.1)
**Signal version:** 5.15.6

### Link to debug log
sorry, can't post a link to a debug log, because signal directly crashes with a network connection but here is the top line!
`GroupDatabase$MissedGroupMigrationInsertException: Tried to create a new GV2 entry when we already had a V1 group that mapped the new ID! __...group_v2...ca`
thanks a lot!

**Comment by cody-signal** [comment]
Hi @timpauli , sorry to hear about the crash. With out some sort of logs, there's not much we can do. If you launch with airplane mode, and get to the submit debuglog screen and turn on networking then, could you try that?

**Comment by timpauli** [comment]
Tried that before. But it crashes before the debug log uploads. It is the same behaviour as #11214
Here is a screenshot of the debug log.
![debug1](https://user-images.githubusercontent.com/9436381/125471904-ad90f21a-acd1-4a11-bd05-303fd5384e43.jpg)
![debug2](https://user-images.githubusercontent.com/9436381/125471921-10c455a9-dc1a-4013-b104-68e94c37293d.jpg)

**Comment by greyson-signal** [comment]
Hi there! I believe this will be fixed in 5.17. Thanks!

**Comment by timpauli** [comment]
Hi there!
I am on 5.17.3 now and the bug is still there.
Thanks!

**Comment by timpauli** [comment]
Please reopen this issue because the bug is still there.

**Comment by greyson-signal** [comment]
Can you post a new log? I'm fairly confident it can't be *the same* crash. I'm guessing the crash moved somewhere else.

**Comment by timpauli** [comment]
![bug report signal](https://user-images.githubusercontent.com/9436381/127338723-01da4ecb-638f-4372-9750-2255595b2702.jpg)

**Comment by timpauli** [comment]
On 5.18.5 the log looks now like this:
![signal-2021-08-01-133337_003](https://user-images.githubusercontent.com/9436381/127769494-4fcecdb5-11f7-420c-9a73-0fe785f293aa.jpg)
![signal-2021-08-01-133337_002](https://user-images.githubusercontent.com/9436381/127769496-bf4171ad-07ea-40cf-94f4-494c6179e5d9.jpg)
![signal-2021-08-01-133337_001](https://user-images.githubusercontent.com/9436381/127769500-50cd31c0-f692-4a90-9980-0e4ba4de8684.jpg)

**Comment by jkuchar** [comment]
I'm experiencing the same bug in iOS version of Signal. Maybe there is something wrong on the Signal server / protocol level / shared app core? [iOS issue](signalapp/Signal-iOS#5105)

**Comment by greyson-signal** [comment]
@jkuchar These are two different issues, sorry.
