### ISSUE TITLE
App crash when re-opening conversation with empty quote draft

### ISSUE THREAD

**Issue by anisse** [signalapp/Signal-Android#11457]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When reopening a conversation with a draft message that is a quote of one of your previous messages,
 the app will crash.

### Steps to reproduce
- quote the latest message you sent in conversation (swipe right)
- do not type anything in the message
-  leave the conversation
- try to open the conversation again

**Actual result:** The app crashes.
**Expected result:** The conversation opens, maybe with the empty quote draft.

### Screenshots
N/A

### Device info

**Device:** One Plus 7 Pro
**Android version:** 11
**Signal version:** 5.16.1

### Link to debug log

There's a stack trace in the debug log. Tell me if you can't reproduce it, I’ll upload it.

**Comment by x539** [comment]
Can't reproduce.

### Device Info:
**Device:** HTC 10
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 5.15.6 / 5.16.3

**Comment by anisse** [comment]
Fixed in https://github.com/signalapp/Signal-Android/commit/060dffc9cc1cf7b175de149068be9d09140bfca7
