### ISSUE TITLE
.onion addresses are not links

### ISSUE THREAD

**Issue by jtracey** [signalapp/Signal-Android#11458]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
URLs that convey [onion addresses](https://en.wikipedia.org/wiki/.onion) are not links when viewed in Signal Android. Signal Desktop behaves correctly here. I suspect this problem was introduced in 3f7dd2118654516aea26cd87e095a4ad87d2a606, which I believe is preventing the URL from being treated as a link at all, rather than the intended effect of preventing link previews. Since onion addresses (especially now that only the v3 format is supported) are intended to be used as non-human readable identifiers, similar to e.g. IPv6 addresses, that are conveyed via links rather than typing in the domain, this winds up being a pretty annoying behavior to work around.

### Steps to reproduce
- send or receive a message with a .onion URL in it (e.g., https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/)
- attempt to tap on URL to open (presumably in Tor Browser, though others exist as well)

**Actual result:** URL is displayed and treated as unformatted text
**Expected result:** URL functions as a hyperlink, similar to other URLs, albeit without preview functionality

### Device info

**Device:** Samsung Galaxy A5 (2017)
**Android version:** 10 (LineageOS 17.1)
**Signal version:** 5.15.6

**Comment by jtracey** [comment]
This is still an issue.

**Comment by jtracey** [comment]
Is there something I need to do to keep this open?

**Comment by cody-signal** [comment]
We use Android's linkify methods to turn text into links. We currently don't have any plans to write our own linkify framework, sorry.

**Comment by jtracey** [comment]
You don't need to write your own linkify framework, as I said, you appear to have broken Android's built-in one, and I'm asking you to undo that. If you need me to write a patch, feel free to ask.

**Comment by cody-signal** [comment]
Have at it.
