### ISSUE TITLE
Sent images are being corrupted when sent to sms group chats.

### ISSUE THREAD

**Issue by GildartsClive** [signalapp/Signal-Android#11469]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images get corrupted when sent from Signal's android client through SMS or anyone not using Signal.

### Steps to reproduce
In a group or a one on one chat use the + sign to attach an image to my message either type in text or not it doesn't matter. then send it. everyone else can see the image but it comes out corrupted see examples below for what it looks like, but it always corrupts the bottom have of the image. I have a second phone number that I use for work and we use signal for communication but not SMS. So I was able to reproduce this issue with my two accounts and two phone numbers. I also tested with my wife's phone as well.

**Actual result:**  Images sent to nonsignal users are corrupted 
**Expected result:** Images should go through with no corruption at all to everyone.

### Screenshots
image before it was sent: [https://imgur.com/Qplo9t8](https://imgur.com/Qplo9t8)
image after it is sent to a group chat that is SMS: [https://imgur.com/H1D5WCv](https://imgur.com/H1D5WCv)

### Device info

**Device:** Google Pixel 4a
**Android version:** 11
**Signal version:** Beta Signal Client ver 5.16.2

**Comment by GildartsClive** [comment]
update: if I switch to googles messages app it works just fine, ALL images sent out get corrupted when sending from signal to anyone over SMS.

**Comment by waded** [comment]
I can reproduce this on a Pixel 4a on Signal 5.28.5. I'm seeing the same issue sending images from Google Messages or Facebook Messenger via SMS/MMS, though - for people not seeing it in both Signal and Messages, perhaps Messages is set to RCS - that is a different delivery mechanism than over carrier SMS/MMS.

I suspect a carrier compatibility issue of some kind personally - I've had this issue with Messages on and off with Cricket and the Pixel 4a for a year.

**Comment by greyson-signal** [comment]
Yeah, unfortunately I wouldn't be surprised if this is carrier-specific. MMS messages are unencrypted, and carriers will often perform their own compression on media in-transit, which could be buggy.
