### ISSUE TITLE
Case-insensitive search does not handle non-ASCII characters correctly

### ISSUE THREAD

**Issue by l3u** [signalapp/Signal-Android#11464]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When searching the contacts/groups list using non-ASCII characters, typing lower-case characters does not yield matches in contacts or groups containing the respective upper-case ones

### Steps to reproduce
- Have a group with e. g. a German Umlaut in it. In my case it's "Ärbert".
- Search for contacts/groups
- Type "ä"

**Actual result:** The "Ärbert" group is not found
**Expected result:** "Ärbert" should be listed, as "ä" is a lower-case "Ä". You actually have to type "Ä" to get the match.

This works as expected on iOS. Apparently, this only affects Android.

### Device info
**Device:** Nokia 4.2
**Android version:** 11
**Signal version:** 5.15.6

**Comment by l3u** [comment]
This still happens with Signal 5.28.10 on Android.

**Comment by l3u** [comment]
Dear Stalebot, it's still the same 5.34.4 on Android. And I still can't provide more information than a detailled bug report on how to exactly reproduce it.

**Comment by greyson-signal** [comment]
I find that case-insensitive search for non-ASCII characters *does* work for contact names, but not for group names. Does that match your experience?

**Comment by l3u** [comment]
I only saw this for group names, but I actually don't have a contact that starts with a non-ASCII character. Maybe I can add some contact with a respective name to see if it works for contact names, but if you see the described behavior for group names, but not for contact names, I supppose this is the current state ;-)
