### ISSUE TITLE
Reading a bubble notification doesn't mark the message as read. 

### ISSUE THREAD

**Issue by Masteroshi430** [signalapp/Signal-Android#11462]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Reading an Android Bubbles notification
https://developer.android.com/guide/topics/ui/bubbles
doesn't mark the message as read. 

### Steps to reproduce
- receive a message
- Read the bubble notification 
- see the signal app icon with a notification dot as if you haven't read the message

**Actual result:** 
see the signal app icon with a notification dot as if you haven't read the message

**Expected result:**  
The signal app icon doesn't have a notification dot because the message has been read in the bubble

### Device info

**Device:**  OnePlus 6
**Android version:** 11
**Signal version:**  latest beta as of today

**Comment by cody-signal** [comment]
Can you provide a screenshot of the situation where you're reading the incoming message, and a debug log after encountering the issue.
