### ISSUE TITLE
Finer export controls

### ISSUE THREAD

**Issue by aprescott** [signalapp/Signal-Android#1146]
I think it would be useful to allow exporting:
- Everything (as now).
- Specific conversations.
- Within specific date ranges.

So for example, if I want to export only a single contact within the last 3 days of conversation, I can set those values in the export screen.

**Comment by AW-UC** [comment]
Also nice to have:
- Only export encrypted messages
This way you can avoid including data from imported SMS that is either outdated or includes duplicates (see #780).

**Comment by Lyle-Tafoya** [comment]
I would also greatly like to be able to export a single conversation. I lost all my conversations by accident and wanted to restore one of them from a backup of the same conversation on my friend's device. I see this issue has been open for about 3 years. Is this something which is planned for the future?
