### ISSUE TITLE
No confirmation when cancelling editing a picture (UX)

### ISSUE THREAD

**Issue by Timbobeek** [signalapp/Signal-Android#11466]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When editing a picture, there is no confirmation shown if a user hits "back" button on their device

### Steps to reproduce
-Open Signal
-Tap on "Camera" button
-Take a picture
-Tap the back button on the device

**Actual result:** The picture is lost: the app does not provide a chance to confirm discarding edits
**Expected result:** At minimum, a user should be able to confirm discarding edits

### Screenshots

https://user-images.githubusercontent.com/68671029/125526834-cad6d3ed-3ead-4b07-9722-c440ef6d8cab.mp4

### Device info

**Device:** Samsung Galaxy S6 Edge
**Android version:** 7.0
**Signal version:** 5.15.6

### Link to debug log

https://debuglogs.org/1c517272ddc58e154ef741b51895428b4779fbf0664f192af8c0863a820c564b

**Comment by adam-a** [comment]
Hey, can I take this one? First time contributor
