### ISSUE TITLE
Registration and login mechanism

### ISSUE THREAD

**Issue by Pantyhose-X** [signalapp/Signal-Android#11470]
-  I have searched open and closed issues for duplicates
- I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

###Expected result
Hello developer

It is recommended to use this login mechanism

* You can only log in with the verification code, and the email receives the verification code of the mobile phone
* Give the user a random phone number. You can create your own area code example There are several unused prefixes. Too many three-digit prefixes, two-digit prefixes are three; +23, +83, +89...

**Comment by Genis-Sage** [comment]
hey @Pantyhose-X 
please do not delete half of the issue template

and it sounds you are requesting some new features, and are not describing an issue with an existing functionality here

as GIthub is reserved for bugs, please visit the community forum:
https://community.signalusers.org/
