### ISSUE TITLE
PDF openend in wrong app

### ISSUE THREAD

**Issue by CJam25** [signalapp/Signal-Android#11476]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
PDF files send in a groupschat are not opened in the correct app or give not the possibility to chose an app that can open the file. Instead the file is directly opened in an app that cannot read the file. In this groupchat this only the case for messages sent from other Android clients the message send from an Iphone gives the desired result. The document I sent is posible to open on the other phones.

This behavior was reproducible with all members of the group. People with less apps on their phone had a toast message no app to open this file is found. The iphone user had no problems to view the documents.

It is possible to first save the document and then open it with an app to your liking, but not directly from within Signal.

### Steps to reproduce
- Sent pdf in groupchat
- Open the document from whitin Signal
- The document is opened in an app that cannot read the file.

**Actual result:** The document is opened in an app that cannot read the file.
**Expected result:** The app gives a suggestion to open the app with a pdf reader or opens it immeadiately in the app that is chosen as standard.

### Screenshots
Message overview:
![signal-2021-07-20-141453](https://user-images.githubusercontent.com/76212814/126322182-8265fe3b-fd27-408a-b472-d9c7ae52dd67.jpg)
Error toast message from other app after trying to open pdf:
![signal-2021-07-20-141453 (1)](https://user-images.githubusercontent.com/76212814/126322284-45c2e6ee-afbc-43dc-a499-78e29f59b3df.jpg)

### Device info
**Device:**  Onplus 3T
**Android version:** Lineage OS 18.1
**Signal version:** 5.16.3

### Link to debug log
https://debuglogs.org/ccbc0e12df303cbd26df5c02b09993229b8180c188e72fcd8db1b59e2e293be5

**Comment by Swasti877** [comment]
Hey, Can I work on it?

**Comment by cody-signal** [comment]
@Swasti877 feel free to submit a PR, you may want to posit here what you think the issue is before starting work to get input from the community.
