### ISSUE TITLE
Voice message volume logic reversed

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#11473]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I expect a voice message to be played through the loudspeaker when the device is not held to my ear, and conversely, to use the regular telephone speaker when holding the phone as I would during a phone call. Unfortunately, this logic seems to be switched around. 

### Steps to reproduce
- Play a voice message
- Notice how the volume is low when phone is in front of you
- Block proximity sensor. Either hold your hand in front of the top bezel or hold the device to your ear.
- Notice how the volume increases as the loudspeaker is now used.

### Device info

**Device:** Google Pixel 4a (sunfish)
**Android version:**  11
**Signal version:** 5.17.0

### Link to debug log
https://debuglogs.org/78c2590549cd9928cc7c3dc288e03b42f476d41ea61f22edc1660e0290e49157

**Comment by haffenloher** [comment]
I also get into this state from time to time on a Mi A2 Lite. Haven't found a way to consistently reproduce it yet.

**Comment by jnns** [comment]
Thank you @haffenloher for confirming. 

A device restart seems to have fixed the issue and the behaviour is now as one would expect. Will report back when the behaviour changes again to the state described in the bug report.

**Comment by Leptopoda** [comment]
Reminds me of this device specific issue
https://github.com/signalapp/Signal-Android/issues/7576

Also this commit from the current beta might help regarding this issue
https://github.com/signalapp/Signal-Android/commit/c78e283084a1ae6ee8f281bf04db2d90d102482c

**Comment by mr-gosh** [comment]
I can confirm this issue for 5.29.3 on an OnePlus8Pro (in2023) on Android 11

**Comment by alex-signal** [comment]
Looks like we aren't switching the volume stream for the activity when we change audio streams in exoplayer. I've done the work that should make this function, but alas it's deciding to be uncooperative so I've got a bit of digging to do.

**Comment by jnns** [comment]
Seems to be fixed. I don't know since when.
