### ISSUE TITLE
How to open Signal Video Call Screen from another app via Intent?

### ISSUE THREAD

**Issue by sagarzala123** [signalapp/Signal-Android#11480]
How to open Signal Video Call Screen from another app via Intent?

**Comment by greyson-signal** [comment]
Hi there, we only use the forum for bug reports. For development help, please use [the forum](https://community.signalusers.org/). Thanks!

**Comment by sagarzala123** [comment]
Hi @gaul ,

I already posted in your forum but no one can reply.

https://community.signalusers.org/t/how-to-open-signal-video-call-screen-from-other-app/35229?u=sagar_zala
