### ISSUE TITLE
Voice message ui is looking inconsistent 

### ISSUE THREAD

**Issue by major-mayer** [signalapp/Signal-Android#11486]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For incoming voice messages the bubble is sometimes to small in comparison to my own voice messages. 
Its looking weird cropped. 

### Steps to reproduce
- get a voice message 

**Actual result:** Voice message bubble is cropped on top 
**Expected result:** it should not be cropped 

### Screenshots
![Screenshot_20210726-005927](https://user-images.githubusercontent.com/17907799/126916146-c1475c70-b0d6-40c7-9fd7-6127b65e736e.png)

### Device info

**Device:** Xiaomi POCO F3
**Android version:** 11
**Signal version:** 5.18.3

**Comment by greyson-signal** [comment]
Thanks! This will be addressed in 5.18.4

**Comment by major-mayer** [comment]
Thank you for the quick fix, that's some good news :)
