### ISSUE TITLE
Open lock after sending message

### ISSUE THREAD

**Issue by mollyuser** [signalapp/Signal-Android#11488]
Hi, i sometimes get an open lock after sending secure encrypted signal to signal message. After pressing send a circle appears thats going round , that means he is trying to send i guess, then a small open lock appears and after that 2 circles for deliverwd message. But the open lock is strange, it just comes for a second or 2 and dissapears, isnt that only suppose to come with unencrypted messages? I am running 5.17.3 version

**Comment by alex-signal** [comment]
Hi! What kind of messages are you seeing this happen to?

Signal does this thing where we "stage" an outgoing message, which really just means we fake it as "sent" in the UI to give you a bit of a faster feel (don't need to wait for the round trip from the UI to the database and back). There was an instance I noticed and fixed for `5.20.1` which was staging an improper version of an outgoing media message. However, on the surface it looks like other messages are being properly staged with the right security flag.

**Comment by valldrac** [comment]
Steps to reproduce the glitch: set a default value for disappearing messages, open a chat with a new contact, and send a text message.
