### ISSUE TITLE
Group call mutes everybody, but only on wifi

### ISSUE THREAD

**Issue by pixelnull** [signalapp/Signal-Android#11481]
Android Signal is updated as of today (5.17.3).

When I use wifi, everybody is muted (actually has the icon), then after about 10 seconds I get asked to join. Switching to cellular works fine. Single calls work fine on cellular and wifi. It's just group calls.

Any ideas what this might be?

**Comment by greyson-signal** [comment]
Hi, can you please provide a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by pixelnull** [comment]
https://debuglogs.org/64ecbb6d73078ed94e8eaefcd706d990582fb47b4100270ed5009b2b3ca44221

Call was at about 8am

**Comment by pixelnull** [comment]
This doesn't happen on my LG G8, but it does on my my OnePlus 9, on the same wifi network. I don't have any other issues on the OnePlus 9 when I'm connected to wifi.
