### ISSUE TITLE
Sudden unusual high mobile data usage

### ISSUE THREAD

**Issue by dcferreira** [signalapp/Signal-Android#11485]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I experienced an unusually high data usage on the signal app tonight, so much that my phone provider sent me a message saying that my data allowance was almost finishing (I'm usually very far from the limit).
Signal used 2.5GB of mobile data, without any apparent reason for it.

I found a [reddit user with the same complaint](https://www.reddit.com/r/signal/comments/okr8b5/how_did_signal_waste_my_entire_data_in_just_1_day/), but nothing in the support forums or github issues.

Unfortunately I don't have a way to reproduce the issue.
I did leave the phone overnight charging and with wifi turned off (and mobile data turned on), and got the data usage warning from my provider at 08:06 (25.07.2021), so I expect that the excess data usage was shortly before that.
I did not receive any message during this night, so I'm quite confused as to how this could have happened.

Here is my debug log (taken a few hours after I noticed this): https://debuglogs.org/d0b60fceba2d5c6ddc45d5b0b2f5d94809e0bb7e9583e269679f670e2d069f61
The only activity I see around the suspected time, is a backup being performed, but as far as I understood that should require no data.

### Screenshots
![signal-2021-07-25-145321_002](https://user-images.githubusercontent.com/7372804/126899912-025063ef-396b-4fe0-a6c2-2cf0b2522e0f.jpeg)
![signal-2021-07-25-145321_001](https://user-images.githubusercontent.com/7372804/126899915-fa28f341-389f-485c-a2b0-9052469278d1.jpeg)

### Device info

**Device:** OnePlus 6
**Android version:** OxygenOS 10.3.11 (Android 10)
**Signal version:** 5.17.3

### Link to debug log

https://debuglogs.org/d0b60fceba2d5c6ddc45d5b0b2f5d94809e0bb7e9583e269679f670e2d069f61

----------------------------------------

I'd be willing to further debug this issue, but don't really know where to go from here.
Any guidance would be appreciated :)

**Comment by greyson-signal** [comment]
Backups definitely don't use data, unless you chose a backup location that does uploading? Like if you chose dropbox or some other syncing platform as the location. Although it would be weird for the system to attribute the data usage to us in that case.

I don't notice any issues downloading attachments or anything, but did you receive any messages with media attachments over night?

**Comment by dcferreira** [comment]
I didn't get any message overnight (with or without attachments), except for one message some minutes **after** I got the notification from my provider (so I guess shouldn't matter).

Just to reiterate, I'm not 100% sure that the data usage was all overnight.
The only things I have is the plot from the picture above, and the message from my phone provider.
Combined with the report on reddit from another user, I think the usage was overnight, but don't know how to verify it 100%.

**Comment by greyson-signal** [comment]
Is your backup location definitely *just* on your local SD card and not hooked up to any other syncing thing?

**Comment by dcferreira** [comment]
The backup is in local storage, and the file is only ~340MB.

I'm grasping at straws here, but I do cloud backups with Titanium backup overnight, of most data on my apps.
**But**, it's set to only use wifi, and the android data usage menu indeed has an entry for the Titanium Backup app (with a lot of data, on wifi, as would be expected).
I can't really see how this would affect anything :/

Any other ideas?

**Comment by elementalhuman** [comment]
Hi, I had exactly this happen to me overnight last night, 3.7GB used by Signal and I also can't see anything in the log. I neither sent nor received any messages overnight.
Battery use was also huge - phone was fully charged at about 4pm yesterday, by 7am this morning, down to 15% with Signal having used 65%. I've sent info to Signal, but it's slightly worrying....
Link to debug log: https://debuglogs.org/d461133321f447acf7fe5f7e6fafbc7c4fa364d8bc3ee43b67a2abfaa3754a48
![Screenshot_2021-07-31-08-22-02-510](https://user-images.githubusercontent.com/88224723/127730699-ab17f79e-0433-403d-94ca-2be2aebb968c.jpg)

**Comment by SenorFusion** [comment]
Same thing happened to me.

Out of nowhere Signal started using a ton of data and crushed my battery.

I do not have any kind of backups enabled, so I do not think it is caused by Backup issues.

A security conscious user might think that there was a bug in Signal that is allowing user data to be extracted remotely.

**Until this bug is explained and addressed I'll assume signal has been compromised.**

![7e2026c2-5056-41ba-8c88-78a4c42b8a0c](https://user-images.githubusercontent.com/1929777/128041993-f10d5092-43b6-48f2-bc56-39e638244789.png)

**Comment by greyson-signal** [comment]
Unfortunately our current logging doesn't give us a lot of visibility into data usage, and I'm not really seeing anything suspicious in the logs ya'll have submitted. We're going to think about a system that may allow us to track our own data usage.

For those of use using the non-play-services version, you *will* experience higher battery drain and data usage since we're forced to keep the websocket open ourselves to get notifications. However, the additional data usage should not be as high as you're reporting.

**Comment by greyson-signal** [comment]
@dcferreira When I look at your logs at that time, literally the only thing that happened even close to the data usage bump is the backup operation. But Signal backups definitely do not perform any network activity. We just write to the location the user chose. The app was inactive for hours before then.

In situations like these, the best thing we could possibly get as developers is an [Android Bug Report](https://developer.android.com/studio/debug/bug-report). However, this is a system-wide report, and it provides not just information about Signal usage, but also the usage of all of your other apps. So we generally do not ask for them. However, battery/network issues are extraordinarily difficult to track down without them.

So I'll throw this out there: if anyone experiences this issue again and is comfortable providing us a Bug Report, you can send one to greyson@signal.org. Just be sure it's a bug report taken within a few hours of you noticing the problem (they tend to have around 12 hours of data, maybe).

**Comment by Seifenlude** [comment]
I had the same problem a few minutes ago 4.3 GB of Background Data. No Backup enabled.

**Comment by cody-signal** [comment]
@LarryLurch Please provide bug or if possible do as Greyson suggested and submit an Android Bug Report.

**Comment by LarryLurch** [comment]
@cody-signal I enabled the Developer mode after the issue. Can i provide the debug log anyway or is it empty because it wasnt enabled before

**Comment by UserX404** [comment]
Developer mode and Adb has to be enabled to get the logcat from the phone to your computer. The logs should be created independent from adb settings.

**Comment by cody-signal** [comment]
Yes you can. Also an app debuglog is independent of it all so that'll be fine. As for the android bug report that should also be fine. You can put the link to the Signal debuglog here, but *do not* post the Android bug report zip here, send that to Greyson (greyson@signal.org) or me (cody@signal.org)

**Comment by LarryLurch** [comment]
https://debuglogs.org/cb7a96f32796736aff77784d7d7a75b3ca461ed53a3f219a6e713871b9e771ff

I will send the android bug report after work

**Comment by cody-signal** [comment]
Thanks! Sorry to nag @LarryLurch , but the sooner the better with the android debug log, those don't have a long window before stuff starts falling off.

**Comment by cody-signal** [comment]
Thank you!

**Comment by cody-signal** [comment]
@LarryLurch thank you sooooo much for the logs, you've helped us a great deal! Hopefully we can track this down now that we've reduced the haystack from the entire app to just a small part. Thank you!!!

**Comment by LarryLurch** [comment]
You're welcome.. glad I could help

**Comment by greyson-signal** [comment]
5.23.1 should have a potential fix for the data usage issue.

**Comment by LarryLurch** [comment]
Thank you keep up the good work

**Comment by Martin-H-42** [comment]
I had the same experience today, here is what happened:

- Writing a message, open insert GIF dialog, search for a gif, but don't select one yet
- Got interrupted, kept GIF dialog open, locked screen with power button directly
- About an hour later got a warning by Android about high data usage of one of my apps
- Unlocked screen, GIF select dialog still open
-> I assume the dialog kept loading GIF's while screen was locked and created ~1,4GB traffic in 1h

Phone: Pixel 4a
Android: 11, Build RQ3A-210805.001.A1, Security Patch Level 05. August 2021
Signal: 5.21.6 from Play Store

Hope that helps! Thanks for the fix in advance!

**Comment by cody-signal** [comment]
The fix in 5.23.1 addresses this scenario. Thanks for the extra details!

**Comment by bumi** [comment]
fyi. I've seen something similar with the Desktop app (but could not debug it further)

**Comment by UserX404** [comment]
@bumi 
This should be reported within the desktop repo due to it has nothing in common with the android app.
