### ISSUE TITLE
#11459

### ISSUE THREAD

**Issue by timpauli** [signalapp/Signal-Android#11493]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a reminder that #11459 is not fixed in 5.17.3
Thank you very much for working on Signal.

**Comment by cody-signal** [comment]
Please reopen the previous issue if it is still a problem.

**Comment by timpauli** [comment]
I don't have the rights to reopen it.
