### ISSUE TITLE
Signal's emojis are not being displayed in conversation list on application's cold start

### ISSUE THREAD

**Issue by pkorba** [signalapp/Signal-Android#11506]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On cold start (application removed from recents screen) Signal for Android doesn't display emojis in conversation list. Switching to some other activity (opening concrete conversation or settings screen) and going back to conversation list "fixes" the issue. This behavior has been introduced in the latest stable release (5.18.5) - everything worked fine in the previous version from release channel. This doesn't happen when "Use system emojis" option is being used. It only happens with Signal's own emoji set.

### Steps to reproduce
- Remove Signal from recents screen
- Open Signal app

**Actual result:** In conversation list, emojis being part of conversation previews are not visible (there's blank space instead). User has to switch to different activity and then go back to conversation list screen to make emojis visible.
**Expected result:** Emojis should be visible in conversation list right away.

### Screenshots
Actual behavior:
![signal-bad](https://user-images.githubusercontent.com/32198274/127744273-b0b76ad3-320f-4bce-aa09-54e2164f470b.png)

Expected behavior:
![signal-good](https://user-images.githubusercontent.com/32198274/127744276-53dcbaca-ffa6-4787-bcdf-0b581aa3bc50.png)

### Device info

**Device:** Nokia 6.1
**Android version:** stock Android 10.0
**Signal version:** Signal 5.18.5

### Link to debug log

https://debuglogs.org/487da09e29d989d5019df0700d90e87568615ed04c9d05883b815e5247172a57

**Comment by Sgn-32** [comment]
A comment from the 5.19 beta thread (https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-19-release/35396/46)
`Yeah, it bums us out too. Aiming to fix, but may not make it until 5.20.`

**Comment by pkorba** [comment]
Fixed in 5.19.4
