### ISSUE TITLE
Google Play Store: UI Bug in App Images for Files

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#11501]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Not a 100% sure whether that is the right place for this report, but I do not know where else to bring that to the attention. I think it makes a bad impression when even the "advertising" screenshots show a misbehaving UI.

### Steps to reproduce
- Got to Signal in Google Play Store (https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms)
- View the 4th image

**Actual result:** file title and icon leaves bubble border
**Expected result:** File title and icon are kept within the message bubble

### Screenshots

![grafik](https://user-images.githubusercontent.com/62468040/127610570-898b907f-14c7-4205-8b1b-09da3953b5cc.png)

**Comment by Kwasow** [comment]
Probably affects only the German store page as the issue is not present in English.

**Comment by cody-signal** [comment]
Passed this on to the folks that handle it, they say should be fixed soon if not already. Please close once you verify.

**Comment by Sgn-32** [comment]
Fixed.

https://play-lh.googleusercontent.com/0pl8VVzxmnIRX9Lb5JFx2DKtZrUo1HWQyv86g21P-Qqhbx9hkOhpHNPOzexq2wSeBCc=w1920-h905

**Comment by MorgeMoensch** [comment]
Yes, this is fixed. Thanks for the quick response & action
