### ISSUE TITLE
Chat colours reversed in conversation view

### ISSUE THREAD

**Issue by ijackson** [signalapp/Signal-Android#11500]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The colours used for the conversation view are reversed.  The colour that shiould be used for the conversation partner is grey, and the colour used for self is the chat colour.  This is backwards anc confusing and a change from previous behaviour.

### Steps to reproduce

- Open a conversation

**Actual result:**

My conversation partner's messages show up with a background the same as the selected chat colour for them.

My messages show up with a grey background.

**Expected result:**

My messages show up with a background colour of the chat colour I have chosen for this conversation partner.

My conversation partner's messages show up on a neutral grey background.

### Discussion

This was correct until some weeks ago; it was broken in an update that also introduced a wider range of chat colours.  The new arangement of colours seems confusing and illogical.  I feel sure it must be a mistake.

### Screenshots

https://www.chiark.greenend.org.uk/~ijackson/2021/screenshot-2021-07-30.png

### Device info

**Device:** Fairphone 2
**Android version:** 7.1.2
**Signal version:** 5.18.5

### Link to debug log

I doubt the debug log will be necessary.  Let me know if it is.

**Comment by Kwasow** [comment]
What you're seeing is not a bug but a redesign of the app. Have a look at the Signal community forum if you want to voice your opinion about the change - GitHub is for issues only.
