### ISSUE TITLE
Built in emoji don't include "face in clouds"

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#11502]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The built-in emoji do not support/include the [face in clouds](https://emojipedia.org/face-in-clouds/) emoji.

### Steps to reproduce
1. Make sure "Use system emoji" setting is *disabled*
2. Try to enter the face in clouds emoji from Gboard (or any other keyboard that supports it)

**Actual result:** Signal displays the "face without mouth" and "fog" emoji
**Expected result:** Correct emoji should be shown.

### Device info

**Device:** Pixel 5
**Android version:** 11
**Signal version:** 5.18.5

**Comment by issteve** [comment]
Yes, Android Signal App emojis seem stuck on 13.0 (as others from https://emojipedia.org/emoji-13.1/ are missing, too). 
Maybe we could get soon even https://emojipedia.org/emoji-14.0/ which are (mostly?) already on Signal Desktop? :-*

**Comment by Herohtar** [comment]
Looks like emoji were updated at some point.
