### ISSUE TITLE
Do not use MediaPlayer for incoming calls ringtone

### ISSUE THREAD

**Issue by jknockaert** [signalapp/Signal-Android#11512]
It's been a while ago since this type of issues was discussed, so I wondered if there's been a change in the Android API framework that would allow to move away from `MediaPlayer` for the ringtone for incoming calls.
In short: Signal currently uses `MediaPlayer` for the ringtone. That results in a number of issues, such as #5503: the Do Not Disturb function handles it as media rather than an incoming call. That's quite a limitation. So I wondered if there's an opportunity now to move away from `MediaPlayer` to use an appropriate Android API for incoming calls ringtones.

**Comment by Sgn-32** [comment]
There is `Ringtone.play()` (https://developer.android.com/reference/android/media/Ringtone#play())
Maybe this can replace the `MediaPlayer` in `IncomingRinger.java`

**Comment by jknockaert** [comment]
@cody-signal Could the use of `MediaPlayer` for ringtones be one of the underlying causes of #7733?

**Comment by supermar1010** [comment]
For me signal never rings, i guess that might also be related to this.

**Comment by jknockaert** [comment]
@alex-signal Perhaps this one too can be refered to calling team when they're reviewing the incoming calls issue?

**Comment by alex-signal** [comment]
The code that actually triggers the ringer is in the signal app, and isn't part of the calling component. We've looked into Ringtone.play but last I heard that also uses MediaPlayer under the hood.

**Comment by cody-signal** [comment]
The next thing we want to try is integration with the telecom system. However, that is not a trivial integration, and drastic change to our state machine. But it's on our radar to do. 

Here is the source for Ringtone, and it's internal media player. The one difference is the inclusion of a remote ringer.

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/media/java/android/media/Ringtone.java;l=79;drc=master;bpv=1;bpt=1?q=Ringtone

**Comment by cody-signal** [comment]
We are not likely to move away from MediaPlayer, nor is there a really good alternative to it. We have updated the way we configure our ringer in the latest beta that will be coming out soon.

Additionally, we are working on the telecom integration. We are in the testing phase and hope to be in the _next_ beta.

**Comment by jknockaert** [comment]
@cody-signal Thank you for the update and for the good work. Much appreciated.

**Comment by cody-signal** [comment]
Try on 5.33 where we've integrated with the Android telecom system, and made some changes to how we ring. Please post an updated debuglog to one of the many other ringing issues on GitHub. I'm going to close this one as it's not something we're considering doing.
