### ISSUE TITLE
Broadcast groups

### ISSUE THREAD

**Issue by uxai** [signalapp/Signal-Android#11517]
I would like to suggest broadcast groups in signal. Unlike regular messaging groups these may hold thousands of members, whereby only the admins of a group may post to it.

* These groups should NOT reveal members and their phone numbers to other members, except the admin (sans their phone numbers too)
* It's purely one way messages to share updates on a website, news or other food for thought.
* These broadcast groups should also be able to have a public invite link to share with others to join.
* Some basic data would be nice for each post, like number of views and possibly number of shares.
* Regular members should be able to see the public share link to invite their friends too

Thanks!

**Comment by alex-signal** [comment]
Good news! Announcement groups are in the works.

https://github.com/signalapp/Signal-Android/commit/25234496bfd1fadadb59fa84867a118aacfe95cd

**Comment by natrius** [comment]
Is an estimation possible when this might be available?
