### ISSUE TITLE
Pastel icons showing in dark mode

### ISSUE THREAD

**Issue by NickwithaC** [signalapp/Signal-Android#11510]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Light mode pastel icons are displaying in dark mode.

### Steps to reproduce
- settings > appearance > theme > dark
- look at contacts

**Actual result:** icons that fit light mode are shown no matter the mode that is set.
**Expected result:** the icons should change to darker colours.

### Screenshots
![Screenshot_20210801-181407-250](https://user-images.githubusercontent.com/88286071/127780510-3958fc5c-37d1-41bf-9530-22706231951c.png)

### Device info
**Device:** Moto G8 power
**Android version:** 11
**Signal version:** 5.18.5

### Link to debug log

https://debuglogs.org/b7c460ab2ee0959dd01319da8367168de26b2dd45033cb9ad88d82c8e59764c1

**Comment by alex-signal** [comment]
Hi! Thanks for the report. This isn't a bug, but I'll pass your feedback on to design.

**Comment by piratenpanda** [comment]
I think it's another step down in accessibility and thus a bug or regression. Now all contacts look almost the same and I have a hard time concentrating to select the right contact as almost no one of my contacts is using avatars. The backgrounds look closely the same and the only different thing is the color of the initials. In light mode it works much better.

**Comment by beantaco** [comment]
I believe this is a design bug. The icons are more difficult to differentiate and harder on the eyes.
