### ISSUE TITLE
voice call microphone stops working at 00:00

### ISSUE THREAD

**Issue by ShaqibK** [signalapp/Signal-Android#11514]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While on a voice call, as soon as clock hits 00:00 the other person is unable to hear my voice until call is disconnected and reconnected.

### Steps to reproduce
- Voice call someone
- Talk until its midnight, i.e. clock hits 00:00
- The other person somehow is unable to hear me, i can hear them fine.
- Disconnect and reconnect the call, now everything is fine.

**Actual result:** the reciever of call is unable to hear me while i can hear them.
**Expected result:** The call should continue without interruption

### Link to debug log

https://debuglogs.org/d98c106d28381ec3adb13b63683945e48d8388fd835d48487747e26e62702ed3

**Comment by alex-signal** [comment]
Well that's a weird one! I'll pass this on to our calling team! Thanks for the report!
