### ISSUE TITLE
Improve app's RNG for generating keys

### ISSUE THREAD

**Issue by yodaforces** [signalapp/Signal-Android#11527]
How does it come the site states it uses insecure RNG and why?

https://beta.pithus.org/report/64d955a99a9e649185110fdf49d1f26f423ec7d16d6dc335443ebc057e80ac93

**Comment by cody-signal** [comment]
Hello, we use security@signal.org for concerns regarding security. Please e-mail there with any additional information that would be helpful in addressing your concern.
