### ISSUE TITLE
SMS/MMS with URL will not send to some contacts

### ISSUE THREAD

**Issue by voicelex** [signalapp/Signal-Android#11533]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I use Signal as my default SMS/MMS app and while this doesn't happen with every non-Signal contact, I am sometimes unable to send messages of any size (SMS/MMS) with a URL in it. I have been unable to trace this to specific device OS (iphone/android) but I'd bet it's only to users with iphones. I've tried turning Wifi off and/or data off to no avail. 

### Steps to reproduce
- I can send a message to Contact A that says "hey, hello" and they will get it but when sending a message with "checkout this link www.link.com" they won't receive it but will get my next message asking if they got it. It's maddening and not repeatable with every non-Signal contact.

### Screenshots
![Screenshot_20210810-183845](https://user-images.githubusercontent.com/23534381/128944166-bedb3da5-3b51-4b8f-a117-7eed75d91ba8.png)

### Device info
Google Pixel 4a
Android Version: RQ3A.210705.001
Signal version: 5.19.4

**Comment by Sgn-32** [comment]
i think it is more an issue with the contacts device. But please post a debug log after sending some SMS to that contact.

**Comment by Techie007L** [comment]
I submitted a bug report email for this same issue back in June.  The issue is definitely the Signal app on the sender's side.  Signal will not send an SMS/MMS with a URL in it.
