### ISSUE TITLE
First message in conversation is missing date-stamp

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#11536]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
First message in conversation is missing date-stamp

### Steps to reproduce
- scroll up in a conversation to the first message

**Actual result:** First message in conversation is missing date-stamp
**Expected result:** First message in conversation has a date-stamp

### Screenshots
![signal-2021-08-11-215335](https://user-images.githubusercontent.com/49990901/129095618-4b3d99fb-0289-4471-a415-8957785f5145.png)

### Device info
**Signal version:** 5.20.4

**Comment by webcompas** [comment]
This issue still exists with version 5.24.7. I hope it will be fixed soon.

**Comment by webcompas** [comment]
Unfortunately this issue still exists with the latest version 5.28.10.
