### ISSUE TITLE
Heavy battery drain after 3/8/2021 update

### ISSUE THREAD

**Issue by rickymohk** [signalapp/Signal-Android#11535]
Noticeably worse battery drain after 3 August update. It looks like forever running in foreground in battery profile, even I am not using it.

![Screenshot_20210811-183001824](https://user-images.githubusercontent.com/17548814/129015030-a8a79425-1d00-4af1-a1e7-85a25f488e70.jpg)
![Screenshot_20210811-183612190](https://user-images.githubusercontent.com/17548814/129015057-06b7de15-7fb6-493f-bb8c-8643a0168ffe.jpg)

**Comment by UserX404** [comment]
Don't delete the issue template!
Search for open and closed issues as mentioned in the template!
Append your logs!

**Comment by ciconi** [comment]
Same here. I'm using Signal without Play Store (signal web site install with the auto updater). 
https://debuglogs.org/50a7bc5c7d5e2046e2192e8f7ef7453909e2b12146d5a1dc437f05bfb8775de6

![Screenshot_20210817-081727_Einstellungen](https://user-images.githubusercontent.com/31411407/129674290-efdf26f6-2ba4-4e10-ac4c-2fd0b56f2b10.png)

**Comment by greyson-signal** [comment]
Let's discuss in #11031
