### ISSUE TITLE
Unnamed conversations are omitted from search results.

### ISSUE THREAD

**Issue by fleapower** [signalapp/Signal-Android#11532]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When searching for a group conversation by contact, group conversations are not listed in the results unless the conversation has been given a name. For example, if I have a conversation with John and Jane Smith and do a search for "John," the conversation doesn't show up. However, if I name the group "John and Jane" and do a search for "John," the conversation is listed in the results. Additionally, searching for John's phone number only shows the one on one conversations, not the group conversation.

### Steps to reproduce
- Start at the list of conversations.
- Tap the magnifying glass.
- Enter name or number (any search criteria) which would identify a member of a group conversation.
- Unnamed group conversations are not included in the conversation list (matching messages are still listed).  Named groups are also omitted unless the search criteria matches the name of the group.

**Actual result:**
Unnamed groups are not listed.  Named groups are omitted unless the search criteria matches the name of the group.

**Expected result:**
Groups conversations are listed based on search criteria for one individual member of the group (name or phone #).

### Screenshots
NA

### Device info
**Device:** Samsung SM-A516U1
**Android version:** 11
**Signal version:** 5.19.4

### Link to debug log
https://debuglogs.org/df416a5ba065a6482090f6f69676542ee851a43ce06af236bf8cfa0a825fef06

**Comment by Tursko** [comment]
Same experience here.

**Comment by fleapower** [comment]
Still happening.  The latest text I received this morning was a group text.  I tried searching for it and it was not included in the search results.

**Comment by fleapower** [comment]
Still a problem.

**Comment by clauz9** [comment]
wait a minute.. can you explain a bit more  @fleapower   ? 🤔 

so you have a group chat started with someone and you want to search for the last message in that group chat, and you don't find it ? 

or are you searching for a member of a group, and you're expecting the app to find the group ? 🤔

**Comment by clauz9** [comment]
as far as I know the app doesn't do what you want it to do 🤔 ... that would be a feature request 

so it searches for contact names containing your search string, 
for conversation names, that contain your search string, or for messages that contain your search string, 
it does not search for groups that contain members with a name that contain your search string 🤔 

so if your searching for "marvel" it will find all messages that contain that word, all contacts who's name contain "marvel" and all already started conversations that contain the word "marvel" meaning, groups named "marvel", or chats with contacts named "marvel"

**Comment by fleapower** [comment]
Gotcha.  I figured that would be something which would be obvious to have and therefore a bug.  I'll request it.
