### ISSUE TITLE
Videos recorded directly from Signal on Iphone are freezing at the beginning and the end

### ISSUE THREAD

**Issue by dibok** [signalapp/Signal-Android#11542]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My friend often sending me short videos and some of them are freezing (2-3 seconds) at the beginning and the end but sound is fine. If video is very short then you basically see only one frame. He even see this same when try to play own video directly from signal message list. We tried figure it out and this happens only when he record it directly from Signal. Videos recorded normally and then added as attachment are fine. When I try to play such broken video on Signal PC (linux) then it is freezing only at the end. Videos recorded that way on my Android phone are fine for both of us.

### Steps to reproduce
- Tap on camera icon in Iphone Signal app
- Hold camera icon to record some video instead of taking picture
- Record some short video and play it in same Iphone app but better on Android recipient

**Actual result:** Video is freezing few seconds at the beginning and the end. Sound is fine
**Expected result:** I should immediately see whole video

### Device info
**Device:** Iphone 12
**iOS version:** 14.7.1 (18G82)
**Signal version:** 5.18.0.64

**Comment by Anonban** [comment]
Sameeee on my iPhone

**Comment by Anonban** [comment]
https://github.com/signalapp/Signal-iOS/issues/5046

**Comment by cody-signal** [comment]
See iOS issue posted by @Anonban
