### ISSUE TITLE
MMS to multiple recipients with picture attachment frequently fails

### ISSUE THREAD

**Issue by mruptown** [signalapp/Signal-Android#11541]
App version: 5.20.4
Android version: 11
Build number: Oxygen OS 11.0.2.1.GM21AA
Device: OnePlus 7 Pro

Steps to reproduce at least 50% of the time:
1) With Signal as your default SMS app, create a message to two non-Signal users
2) Type in text and attach a picture to the message
3) Send message

Expected result:
1) Message sends successfully

Actual result:
1) Receive error message that "Message could not be sent.  Check your connection and try again." despite having a perfectly good signal

This does not appear to occur if there is only one recipient.

**Comment by Tursko** [comment]
Please attach a debug log
