### ISSUE TITLE
Signal restarts/crashes when starting new sms/mms/unsecurechat with a picture and text

### ISSUE THREAD

**Issue by jeremiah-miller** [signalapp/Signal-Android#11548]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal restarts/crashes when starting new sms/mms/unsecurechat with a picture and text

### Steps to reproduce
- start new chat with thenew message button on the chat list
- pastein the phone numberyouwant to send to - one that isn't linked to signal and start the chat
- send an image with text

**Actual result:** 
Signalsoft resets,going blackthen showing the message list which doesn't have the new chat you just tried to start
**Expected result:** 
The message sends and you stay in the chat you just started

### Device info

**Device:** Oneplus 5
**Android version:** 11
**Signal version:** 5.20.4

### Link to debug log

I don't have a new phone number to try it with, i already started a chat with the one i was having the issue with by sending only text and then i was able to send a pic with text

**Comment by Tursko** [comment]
Yes I actually experienced this a couple days ago. The message successfully sends but it doesn't create a thread.

**Comment by greyson-signal** [comment]
Hi there! This is fixed in 5.21.x via 0838c0be2, which is currently in beta. Thanks!
