### ISSUE TITLE
Sound drops randomly when listening to audio messages

### ISSUE THREAD

**Issue by Einenlum** [signalapp/Signal-Android#11547]
Hi. First, before getting to the annoying bug, I want to say thanks to the whole team for your great work :wave: :heart: 

### Bug description

When listening to audio messages, the sound very often drops randomly (every one to two minutes I would say). The app seems to still play the audio message, but no sound can be heard.
This has been the case since a few months. On my previous android phone (Wiko Lenny) too.
The problem does not happen on Signal for Linux Desktop.

### Steps to reproduce

Listening to some audio messages and wait for the problem to happen.

**Actual result:** The sound drops and I need to quit Signal and launch it again.
**Expected result:** The sound should still play until the message is over.

### Device info

**Device:** Oppo A54 5G. Model: CPH2195
**Android version:** Color OS V11.1, Android 11
**Signal version:** 5.19.4. Could also be reproduced on 5.20.4

### Link to debug log

https://debuglogs.org/de5b3b9ae24bf212a35e593131fef4000f56fb63acba217644e95dd7802139fc

**Comment by piratenpanda** [comment]
Are you sure you are not triggering the proximity sensor?
