### ISSUE TITLE
Location Sharing From iPhones Parsed as Contacts

### ISSUE THREAD

**Issue by DHerls** [signalapp/Signal-Android#11549]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Android cannot properly receive "current locations" sent from iPhones over MMS.

iPhones share locations over MMS via vCards. Signal interprets all vCards as shared contacts.

### Steps to reproduce
- Have someone with an iPhone send you their current location over MMS

**Actual result:** Signal interprets the vCard as a shared contact
**Expected result:** Signal extracts the shared location data from the vCard and displays it to the user

### Screenshots
![Screenshot_20210816-155001_Signal](https://user-images.githubusercontent.com/5505389/129783575-8c697c57-01a7-4970-9d5e-0324ec7d55a1.jpg)

### Device info

**Device:** Samsung Galaxy S21 Plus
**Android version:** 11
**Signal version:** 5.21.2

**Comment by DHerls** [comment]
I can submit a PR to fix this issue, since I inadvertently caused it with PR #9667, but I would like guidance on what path to take. 

Options:
- Simply extract the Apple Maps URL and display it in the body of the message
- Convert the Apple Maps URL to a Google Maps URL with the same coordinates
- Convert the URL and also attach a screenshot like how Signal shares locations natively

**Comment by Tursko** [comment]
> I can submit a PR to fix this issue, since I inadvertently caused it with PR #9667, but I would like guidance on what path to take.
> 
> Options:
> 
> * Simply extract the Apple Maps URL and display it in the body of the message
> * Convert the Apple Maps URL to a Google Maps URL with the same coordinates
> * Convert the URL and also attach a Google Maps screenshot like how Signal shares locations natively

In your other PR the Signal team wanted the experience to be as similar as possible. So I would convert the URL and attach the Google Maps screenshot.
