### ISSUE TITLE
Some animated stickers play really quickly in android app

### ISSUE THREAD

**Issue by parrajustin** [signalapp/Signal-Android#11559]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports <- Doesn't work?
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Certain stickers play really fast, faster than they should. If a sticker's duration is 5 seconds the playback will loop the sticker in under a second. Only some stickers are affected by this even in the same sticker pack, see the example screen recording:
https://user-images.githubusercontent.com/1360989/130343368-404fb303-ddc8-4d7b-bd7d-6c65e0cc5f3b.mp4

This only happens on my android device no matter the source of the sticker. On my linked desktop and the other participant in my conversation's IOS device don't face this. Everywhere the sticker is on my android device has this speed playback effect on signal.

FFmpeg command:
The animated stickers were created from a webp that had the individual sticker frames and were cropped and concated together through a complex filter on a window machine. An example command:
`ffmpeg -loop 1 -framerate 60 -t 0.130 -i animation.webp -loop 1 -t 0.200 -framerate 60 -i animation.webp -filter_complex "[0:v]crop=256:256:0:0[0v];[0:v]crop=256:256:256:0[1v];[0v][1v]concat=n=2:v=1 [v]" -map "[v]" -plays 0 output.apng`

Link to apngs:
https://drive.google.com/drive/folders/1Ux9m2EpkqvU6xBYAqB_KNvgz6orqTOj-?usp=sharing

### Steps to reproduce
- Upload stickers in a sticker pack
  - Emojis/name/author name doesn't seem to affect it.
- Send emoji in conversation or have emoji sent to you
  - Source doesn't matter, it could be from a linked desktop app or another's phone
- Observe animated sticker is playing really fast (like fast forwarded)
- Can also add sticker pack and see fast playback in the sticker selection screen

**Actual result:** Animated stickers has Nx playback where N > 1 (speedup playback)
**Expected result:** Animated sticker plays at 1x speed (normal speed)

### Screenshots
https://user-images.githubusercontent.com/1360989/130343368-404fb303-ddc8-4d7b-bd7d-6c65e0cc5f3b.mp4

### Device info

**Device:** Pixel 4 XL
**Android version:** 11
**Signal version:** 5.21.5

### Link to debug log
https://debuglogs.org/49e228331f02ade703174bf1d58d2636e6071de1fda7c4826d160eb710bbb41c

**Comment by Frivolous2** [comment]
This is still relevant.

https://debuglogs.org/android/6.11.7/35c24ed7932463d024848742607d2f257d0b1535deb707e6e2ab98f599d0a1a0

https://signalstickers.com/pack/c7e3d8df4a74cbe278c3d94f975d1792
