### ISSUE TITLE
Application Signal crash in Professional Env. on Signal

### ISSUE THREAD

**Issue by dlevequeIT** [signalapp/Signal-Android#11552]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello,
I use Island to have a Professional sandbox on my Phone. The app work a little as "Parallel Space Pro" but with a separate Professional tab in the launcher.
I used Signal into Island than more 1 year as I have a dual SIM phone since more than 1 year and all was perfect until now.

I wanted to reset my Island Professional sandbox and all previous installed apps have been re-cloned and works perfectly except Signal.
Signal work perfectly in the mainland but not in the Island. I tried to rollback with previous Signal version but not better.

I requested help from the [Island Github channel](https://github.com/oasisfeng/island/issues/257), so please find [logs here](https://github.com/oasisfeng/island/files/6974514/logcat_08-12-2021_11-51-34.txt)
I'm on OnePlus 7T Pro (Android 11 Oxygen OS 11.0.1.1), Signal 5.21.4 and Island 5.4.3. Could you help me please ?

Thanks. Regards,
Damien

### Steps to reproduce
- install island
- install signal from playstore
- clone signal in Island from MainLand to Island
- Launch Signal from Professionnal Env

**Actual result:** Application Signal crash at each launch
**Expected result:** The screen to initialize the application in Island

### Screenshots
Unable to make screenshot. Application crash directly after launch in Island

### Device info
**Device:** OnePlus 7T Pro
**Android version:** 11
**Signal version:** 5.21.4
[logcat_08-12-2021_11-51-34.txt](https://github.com/signalapp/Signal-Android/files/7016160/logcat_08-12-2021_11-51-34.txt)

### Link to debug log
https://github.com/oasisfeng/island/files/6974514/logcat_08-12-2021_11-51-34.txt

**Comment by greyson-signal** [comment]
Hi there, I don't know what this Island app is doing, but it seems to be doing some pretty wild stuff, and we don't support it. The provided log doesn't seem to have any Signal-specific errors. You might be able to find some help on [the forum](https://community.signalusers.org/).

**Comment by dlevequeIT** [comment]
The Island application is only a professional sandbox which permits to separate personnal contacts/mails/applications in comparison with professional. You could decide to clone application from mainland or use the PlayStore in order to install other application. In my case I tried both but it does not work. In the log there is Signal error :
`[08-12 11:51:31.440 1621:3387 I/WindowManager]
WIN DEATH: Window{7f75dbd u11 org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity}

[08-12 11:51:31.440 1621:3387 W/InputDispatcher]
Attempted to unregister already unregistered input channel '7f75dbd org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity (server)'

[08-12 11:51:31.441 836:836 I/Zygote]
Process 29905 exited due to signal 9 (Killed)`

Island is probably to blame but I also think that Signal expects something at this point, before the crash.
Could you help me please. Any idea or workaround please ?
