### ISSUE TITLE
When signal window is not in focus, the close button does not work.

### ISSUE THREAD

**Issue by resuna** [signalapp/Signal-Android#11567]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the Signal window is not in focus the close button does not work.

### Steps to reproduce
- Open the Signal window
- Click on another app to remove focus from Signal
- Click on the red close button in the upper left corner of the window.

**Actual result:** The button reacts normally to indicate a press, but the window remains open.
**Expected result:** The window closes.

### Screenshots

None.

### Device info

**Device:** Mac mini (2018) 3.2 GHz Intel Core i7, 16GB 
**Mac OS version:** 10.14.6 (Mojave)
**Signal version:** Signal Desktop v5.14.0

### Link to debug log

Can not locate this in Desktop app.

**Comment by bogdanguranda** [comment]
@resuna you should post this issue on the desktop app repository: https://github.com/signalapp/Signal-Desktop
