### ISSUE TITLE
UNABLE TO FORWARD MESSAGES -- BULL SHIT -- YOU'RE ATTACKING OUR ABILITY TO SHARE. FIX IT!!!

### ISSUE THREAD

**Issue by engineering1** [signalapp/Signal-Android#11566]
STOP LIMITING THE NUMBER OF CONTACTS TO 5 AND GIVE ME BACK MY ABILITY TO SELECT CONTACTS RATHER THAN TYPING THEM IN.

DON'T GIVE ME ANY BULL SHIT ABOUT HOW YOU NEED TO LIMIT THE NUMBER OF CONTACTS, I DON'T FALL FOR IT.

FIX IT!

MY FRIENDS AND I ARE ALL DITCHING YOUR STUPID APP WITH ALL ITS INTENTIONALLY BROKEN SECURITY AND IMPEDIMENTS TO FREE SPEECH! STOP IT!!!

**Comment by happychameleon** [comment]
This is an incredibly bad bug report:

You have removed the template, which means the information to solve your bug has not been given.

For example, i have no idea if you mean you can only add five people to a group or if you can only add five contacts to your signal contacts? In any case both are not a bug I have discovered (i have groups with more than five members and far more than five signal contacts).

I would recommend you update your bug report to a useful state/restore and fill out the issue template, if you want to do something other than complain and have the developers fix the issues you're encountering.

**Comment by winskil** [comment]
This really isn't the right forum to give feedback. For that go to the signalusers forum.
