### ISSUE TITLE
Self-note : can't "delete for all" on phone

### ISSUE THREAD

**Issue by Its-Just-Nans** [signalapp/Signal-Android#11560]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] I have fix https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Cannot do "delete message for all" on Signal for phone in "self note conversation"

### Steps to reproduce
- have "Signal Android" on your phone
- have "Signal Desktop"
- link them
- send a message with signal desktop => to => your phone
- delete the message on your phone

**Actual result:** The message will not be deleted on Signal Desktop

**Expected result:**

Two choice :
- Delete the message for all so the message will be deleted on Signal Desktop
- Display options "Delete message for all or only for me ?" before deleting

**Comment by piratenpanda** [comment]
Delete for all doesn't mean all your devices but the other person you are talking to. That's why this option is not available in note to self

**Comment by Its-Just-Nans** [comment]
This options is available on Signal Desktop.

If you consider this option not good for self-note, there is a sync bug between signal and Signal Desktop

**Comment by Tursko** [comment]
> Delete for all doesn't mean all your devices but the other person you are talking to. That's why this option is not available in note to self

Not true. You can delete from note to self within 3 hours. That feature should work in all circumstances. I previously have used it, so I'm sure this is a bug.

**Comment by piratenpanda** [comment]
But that doesn't make any sense as you only delete for yourself in every case. What does delete for all even mean then in note to self? Delete for all means deleting the message for all conversations partners in normal conversations. There is no other party involved so this would be very inconsistent imho.

**Comment by issteve** [comment]
I would prefer having "delete message for all" meaning delete message on all devices (and that's how I did understand it in the first case anyhow).

**Comment by Tursko** [comment]
> But that doesn't make any sense as you only delete for yourself in every case. What does delete for all even mean then in note to self? Delete for all means deleting the message for all conversations partners in normal conversations. There is no other party involved so this would be very inconsistent imho.

Delete from all also means delete from 'all' devices, not just all recipients.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by Tursko** [comment]
> Please use the community forum for feature requests https://community.signalusers.org/

Hey Alex can you please clarify, I know this functionality exists on the desktop app and the iPad app. Is this just something that hasn't been implemented on the Android side?

**Comment by alex-signal** [comment]
@Tursko Are you sure? On my desktop version I don't see a "Delete for everyone" option

**Comment by Tursko** [comment]
> @Tursko Are you sure? On my desktop version I don't see a "Delete for everyone" option

Weird maybe it was removed because even during the beta people were mentioning that they could delete note to self messages from their desktop. I'm not home so I can't verify.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-desktop-1-37-1-release/17441/49?u=tursko

I also see on that reply that someone complained that they couldn't do it on Android. I guess I've only ever used that feature on my linked devices?

**Comment by alex-signal** [comment]
I'd love this as well. I'll bring it up with design. However, it's not a bug. At the time, it was an intentional decision. I'm not privy to all the ins and outs of that decision, however.

**Comment by Tursko** [comment]
> @Tursko Are you sure? On my desktop version I don't see a "Delete for everyone" option

On my desktop notes btw. 
![image](https://user-images.githubusercontent.com/18274896/131428745-fa17f48a-d72a-4223-9d65-3fa02092aefc.png)

**Comment by alex-signal** [comment]
Interesting, this isn't available on my desktop version (latest beta)

**Comment by pawepaw** [comment]
Any update on that? It's annoying that removing notes from phone doesn't remove them from desktop app.
