### ISSUE TITLE
Pin entry could be

### ISSUE THREAD

**Issue by xternaal** [signalapp/Signal-Android#11563]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by xternaal** [comment]
I thought I left this issue awhile ago, but maybe not I can't find a response. Sorry if duplicate.

Entering the pin on the app you can enter unlimited entries and them hit submit to them get a wrong answer. But if you enter the correct pin it accepts without having to hit enter. 

Doesn't this break the verify pin security?

**Comment by greyson-signal** [comment]
If you have physical access to the app, you can just change the PIN. The 'verify' flow is just a reminder system to help make sure you don't forget it.
