### ISSUE TITLE
Verification code never received [Chinese phone number, previously working]

### ISSUE THREAD

**Issue by ksl1989** [signalapp/Signal-Android#11561]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have been using the same Signal account for years but, after my phone died last week, I am unable to login in a new phone, as the verification text message is never received. Note: I am living in China, using a [China Unicom](https://en.wikipedia.org/wiki/China_Unicom) phone number. When I signed up for the first time, Signal wasn't yet blocked. I am using a VPN service from ExpressVPN, the same have been using without issues with Signal since it was put behind the Great Firewall. To confirm this isn't an issue with my phone, I tried to log into Google (which is also blocked in China) from a VPN server I never used before so it would ask to send a verification code. It did and I received it and logged into my Google account without issue. I have never had any similar issues with any other app.

### Steps to reproduce
- Install the app from APK or from the Aurora store (tried both sources);
- Tap "Continue";
- Confirm that the automatically filled out number is correct;
- Tap "OK";
- Tap "I understand" (o the missing Google services warning);
- Solve captcha;
- Repeat two steps before solving captcha;
- Wait forever
(Optionally)
- Tap "Call me instead" (once available)
- Wait forever

**Actual result:** Verification code is never received and I'm unable to log in
**Expected result:** Verification code is received and entering it allows me to log in

### Screenshots
![Screenshot_20210823-034107_Signal](https://user-images.githubusercontent.com/40713728/130367956-bc6b96fd-bcfe-47ee-96fc-0cd4268ea019.png)
![Screenshot_20210823-030851_Signal](https://user-images.githubusercontent.com/40713728/130368070-34031ba3-bac8-4b56-920a-0148cda1fcac.png)
![Screenshot_20210823-030900_Signal](https://user-images.githubusercontent.com/40713728/130368105-f7fa4cf3-0fb7-4907-a1a0-48e33b106222.png)
![Screenshot_20210823-030922_Signal](https://user-images.githubusercontent.com/40713728/130368111-ca38a2ea-a252-4d16-b008-7d94ee040789.png)
![Screenshot_20210823-030932_Signal](https://user-images.githubusercontent.com/40713728/130368124-11e3f2d4-3afd-4393-a91e-260599823285.png)
![Screenshot_20210823-031017_Signal](https://user-images.githubusercontent.com/40713728/130368149-e2b1dc79-596d-49e8-ace1-87352408590f.png)

### Device info
**Device:** Pixel 3
**Android version:** 11 (lineage-18.1-20210817-nightly)
**Signal version:** 5.20.4

### Link to debug log
[I don't think I can get a Signal log without logging in first, but let me know if I can.]

**Comment by issteve** [comment]
I think this doesn't have to do anything with the app, but the great firewall blocking (easily) the verification SMS and verification calls. Those are not controlled by the App or could used by a VPN or ... Those verification methods are using the "normal" (mobile) telephone network which is under Chinese law. So I guess as long as you are using a Chinese telephone number under Chinese law there is no way to register this (again). 
As long as Signal is only usable with phone numbers I guess the only workaround would be to get a number from outside of China (like a VoIP number) and use this with a verification call (instead SMS) over the VPN for the registration process.

**Comment by alex-signal** [comment]
Hi! Thanks for reporting this. I've passed this onto our support team. Given this isn't an issue with the Android client, I'm going to close this out.

**Comment by ksl1989** [comment]
@alex-signal thanks for looking it this.

Not asking to reopen, I'm sure you know better than me if it is Android related. I'd just like to add that, while @issteve is correct, and they probably can easily block these text messages, it's not likely that is the issue. Larger and more well known social media platforms like Facebook, which have been blocked for many years, can usually still send text verification text messages. It's not likely they would do this for Signal, which is barely used in China and was only blocked recently. In my experience, when something like this happens it's more likely than not some service (Signal itself or any service used during the login process) blocking known VPN IPs, or other "shared IPs".

**Comment by alex-signal** [comment]
@ksl1989 As far as I'm aware, the Signal client itself does not block texts, but the server might. I'll ping the support team again about this, but as far as I know, it's a broader, known issue with Chinese phone numbers.

**Comment by Hercu1es** [comment]
Still can not receive verification SMS message for chinese phone number at now.

**Comment by greyson-signal** [comment]
Unfortunately our SMS's *are* being blocked, but we're trying our best to remedy the situation.

**Comment by mountainwest** [comment]
> Unfortunately our SMS's _are_ being blocked, but we're trying our best to remedy the situation.

Wanted to chime in that I, too am having this same issue (though on iOS). I also want to confirm that a number of other prominent sites (Facebook, top of list) that are blocked by The Great Firewall are able to send confirmation SMS messages without any issue to Chinese mobile numbers on all networks (CM, CT, CU).

This is an issue that clearly can be solved by Signal, and I would think (hope) that given Signal's philosophical commitment to equitable access to secure communication this issue should receive greater attention (there are approximately 1 billion smartphones in use in China today).

**Comment by greyson-signal** [comment]
Yes, as I mentioned, we're working on resolving this.

**Comment by brianwulbern** [comment]
Should this issue be reopened in light of the current work being done to remedy it, or is there another active thread we can follow?  In the same boat as others - not receiving SMS on new iPhone in China :/

**Comment by mountainwest** [comment]
@brianwulbern thanks for commenting here. @greyson-signal would be grateful for any update on this. thanks again.

**Comment by SJTUboy** [comment]
Same issue.
not receiving SMS on new iPhone/Android in China :/

**Comment by mountainwest** [comment]
@greyson-signal checking in to see if there might be any guidance available on this issue. Thank you.

**Comment by WoodpeckerBaby** [comment]
Same. That means I have lost my account registered to a Chinese phone number. Still got the other ones though. 

This illustrates how vulnerable the sms registration system is. 

Even in the US, if the FBI wants to disrupt your communication, they can start with blocking your text, so you can't sign in to Signal.

**Comment by SJTUboy** [comment]
@moxie0 
checking in to see if there might be any guidance available on this issue. Thank you.

**Comment by SJTUboy** [comment]
Update, my solution:
==== mainland China ====
1- Sign up a Google Voice virtual number (US), OR you can buy one at Alibaba Taobao
2- Use that Google Voice number, log in Signal
3- Done


Maybe you guys others solutions, hope to hear


Across the Great FireWall we can reach every corner in the world.

**Comment by issteve** [comment]
> Update, my solution: ==== mainland China ==== 1- Sign up a Google Voice virtual number (US), OR you can buy one at Alibaba Taobao 2- Use that Google Voice number, log in Signal 3- Done

Yes, I already suggested something similar in August (see above https://github.com/signalapp/Signal-Android/issues/11561#issuecomment-904408526 ) and it already did work for some others too. (You can even use a free "burner" phone number or some free SMS service numbers.)

Just make sure: https://www.howtogeek.com/712592/how-to-turn-on-registration-lock-in-signal/

Greetings!

**Comment by romain130492** [comment]
> Unfortunately our SMS's _are_ being blocked, but we're trying our best to remedy the situation.
Twilio Verify should work for China, or Aliyun. 
https://www.twilio.com/verify

**Comment by romain130492** [comment]
this is when the text confirmation should not be the only way;)

**Comment by JayCroghan** [comment]
Telegram and Whatsapp are able to use verification providers that get around this for Chinese numbers. It's not a good enough excuse for an app that bills itself as a censorship circumvention tool to just say "oh well the problem is the user".

**Comment by romain130492** [comment]
i guess Signal could use a proxy to validate text messages,,,

**Comment by WoodpeckerBaby** [comment]
The problem is, why Telegram is so hell bent on using phone numbers as the only form of authentication? 

What's wrong with a simple username, passcode and 2FA app authentication?

**Comment by WoodpeckerBaby** [comment]
> i guess Signal could use a proxy to validate text messages,,,

Why do you intentionally take up so much white space?

**Comment by romain130492** [comment]
> > i guess Signal could use a proxy to validate text messages,,,
> 
> Why do you intentionally take up so much white space?

What do you mean?

**Comment by Hercu1es** [comment]
I think it is OK now，I've tried to using a Chinese local number to verify the Signal code and succeed

**Comment by JayCroghan** [comment]
Wow. That’s a good find and explains a lot. But doesn’t explain why
Telegram doesn’t have this problem? Maybe you either haven’t tried Telegram
or it doesn’t need these permissions?

**Comment by nicholas-signal** [comment]
> For Signal to send you a code it is mandatory to have google play services online with "phone" and "sms" permissions on.

I tested Signal registration to work even if those permissions were denied; Google Play Services sent me a notification suggesting I enable the permissions but I was still able to register.

Nonetheless, I added some code in 05f07d17884770c9fd777e8f353d4e9893faad22 to be more defensive against this failure condition as well as some logging to better understand what's happeningm so hopefully that helps. If anyone encounters this specific issue on version 6.22+, please file a new GitHub issue and attach a debug log.

**Comment by ahsan3803** [comment]
I was facing same issue in iOS. I tried using different VPN servers but nothing worked for me. 
Finally I tried with China server using Astrill VPN and I got verification code. 

So if you are in China then try with Chinese server using any VPN because Telegram has dedicated SMS services for China as I also received OTP from a Chinese SMS service. 

I hope it will resolve the OTP issue. 

PS: My mobile network is China Unicom.

**Comment by javokhirajabov** [comment]
@ahsan3803  I am facing a similar problem with Telegram, I have been trying for weeks to receive OTP. Could you please be more specific, or kindly share your WeChat ID. I have different types of VPNs, and I tried multiple times with Hong Kong servers, no use at all. I would appreciate your help!

**Comment by herei0147** [comment]
I've been lurking on this sub for a week, searching the internet, reading every bit of information available, and trying to find or contact any HUMAN who can actually help. However, I'm beginning to realise that my problem will not be easily solved. I was referred to Marieconsultancyoz@gmail.com. I'm one of the thousands of Instagram users affected by this farce. Also on Instagram under the handle Marie_consultancy. You can also get in touch with her. She successfully unlocked my locked Instagram and Facebook account, demonstrating her ability to provide me with appropriate and sincere services.

**Comment by ahsan3803** [comment]
> @ahsan3803 I am facing a similar problem with Telegram, I have been trying for weeks to receive OTP. Could you please be more specific, or kindly share your WeChat ID. I have different types of VPNs, and I tried multiple times with Hong Kong servers, no use at all. I would appreciate your help!

@javokhirajabov  Did you try with China mainland server, not with Hong Kong one. 
Please share your ID then I'll add you.

**Comment by herei0147** [comment]
Hey text me on my email ***@***.***

**Comment by Emma031818** [comment]
I was facing same issue in iOS. my phone number is Union number from China mianland.
Whatsapp works well in my previous Android phone( died suddently), but with different VPN(When I am in China),  I can not receive any verification SMS and verification calls in my new Apple Phone.  
I also tried to log when I was in America last month, same issue.
<img width="585" alt="1" src="https://github.com/signalapp/Signal-Android/assets/160569722/4f9ceaea-db84-4ae2-a711-9509b5d4f707">
<img width="585" alt="2" src="https://github.com/signalapp/Signal-Android/assets/160569722/f9eaff3b-1eaf-41e5-9c9a-62b0dc03dc72">

**Comment by andrea85vi** [comment]
> I was facing same issue in iOS. I tried using different VPN servers but nothing worked for me. Finally I tried with China server using Astrill VPN and I got verification code.
> 
> So if you are using any Chinese network (phone number) then try with Chinese server using any VPN because Telegram has dedicated SMS services for China as I also received OTP from a Chinese SMS service.
> 
> I hope it will resolve the OTP issue.
> 
> PS: My mobile network is China Unicom.

Hi, I have the same problem, I’ve been logged out of my Telegram for more than a month now after changing phone. Can’t received the sms. 
Can you please be more specific, what do you mean by Chinese server using Astrill? There is no Mainland China server on Astrill, only Hong Kong, but it doesn’t work. I’ve tried in many ways, even when I was abroad on a recent trip, I can’t get that sms on my Chinese phone number.
Hope someone can help, thanks.

**Comment by lida2003** [comment]
Can't receive SMS activation message, so I can't register the telegram.

**Comment by Delicate12** [comment]
Please anyone who can help me with receiving a WhatsApp code using a Chinese phone number?
Its been a week now

**Comment by Daviecj** [comment]
> Please anyone who can help me with receiving a WhatsApp code using a Chinese phone number? Its been a week now

For me its been more than 5months, I have ran out of solutions.

**Comment by UjuiUjuMandan** [comment]
Weird, I successfully received every verification code.

**Comment by lida2003** [comment]
It's NOT possible in China.
