### ISSUE TITLE
Message gets lost if user has signal account but not actively using it

### ISSUE THREAD

**Issue by sarunluitel** [signalapp/Signal-Android#11568]
### Bug description
A good thing about using signal is that if my friends don't have signal it's just sent as a regular text message. I can use signal as my only texting app and app will automatically deliver the message to signal or text message

### Steps to reproduce
- send a message to a user who created a signal account but is not actively using it.

**Actual result:** The message is sent
**Expected result:** prompt to send as regular message or notify saying the receiving party is not currently using the signal app

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
