### ISSUE TITLE
Microphone issue with Wear OS-watch connected

### ISSUE THREAD

**Issue by jivarson** [signalapp/Signal-Android#11576]
Whenever I have a wear os watch connected to my android phone (oneplus 7T, android 11), I can't use any microphone, and I can't hear anything. Also the speaker/phone/Bluetooth-switch in signal doesn't work.

I have to disable Headset-functionality completely on the watch in order to make or receive calls on Signal.

This has been the case for at least 6 months, and I've used two different watches, fossil gen 5 carlyle and ticwatch pro 3., and the latest stable versions of signal for Android

**Comment by Tolsto** [comment]
I have the same problem. With my Samsung Watch 4 connected to the phone Signal will always select the Watch as a bluetooth headset which is very annoying.

**Comment by LaPeste** [comment]
This is very much still the case. The issue should be kept alive.
In 2 words, the feeling I got is that signal grabs the watch as the "speaker" and everything breaks from there on. This happens for both, calls and audio messages while recording them.
I can help with logs etc if you tell me what you'd like to see.
