### ISSUE TITLE
sending sms infinite loop of warnings when low to no cell signal

### ISSUE THREAD

**Issue by d1820** [signalapp/Signal-Android#11574]
when you have very low cell signal 1 bar or less and you try to send a message to a non-signal user you get an infinite pop-up that prompts about sending too many messages and it gets stuck and the only way to clear the pop-up is to reboot the phone. 

hitting accept or deny just loops you into an infinite loop of prompts

![20210827_192713](https://user-images.githubusercontent.com/377631/131228721-01e010aa-32b2-4d52-bf6d-e6126c871512.jpg)

expected behavior: it should fail to send the SMS message when low cell service is detected.

a retry timeout should be hit

hitting deny should apply to all prompts related to the sms being sent

**Comment by Tursko** [comment]
Attach a debug log.
