### ISSUE TITLE
Cannot send/recieve any kind of message, export chats in 5.21.6 or 5.22.3

### ISSUE THREAD

**Issue by crudlover** [signalapp/Signal-Android#11578]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since updating Signal on August 20th 2021, all Signal/SMS/MMS messages have been stuck sending. If I try to delete the messages in the process of sending, the app stalls. I figured this was related to the large amount of media on my Signal account (~3.8GB), so I exported it all and backed it up. My storage is now listed as "0 B", and when I try to generate a backup, the messages count up to ~11000 and then displays a message "Last backup: Never." It also fails to generate a backup file under /Signal/Backups. I've reset storage permissions multiple times then re-started this backup to no avail. I later retried this with the beta version 5.22.3 only to receive the same result. Android OS constantly prompts me that "Signal isn't responding", with an option to terminate the program.

Even creating a bug report is futile, it simply stalls. At this point I just want to find a way to get my chats exported off this app. Please advise if you have any idea of what is going on. It feels as though all functionality of the app has broken completely.

### Steps to reproduce
- Use 5.21.6 or beta 5.22.3
- Have a chat archive from 3-4GB large
- Try creating an export

### Device info
**Device:** Samsung Galaxy A20
**Android version:** 9
**Signal version:** 5.21.6 and 5.22.3

### Link to debug log
Cannot produce debug log.

**Comment by cody-signal** [comment]
Thanks for the report @crudlover, sorry this is happening. We aren't seeing this elsewhere, and without a log there's not much we can do to help.

If possible could you try using [adb](https://www.xda-developers.com/install-adb-windows-macos-linux/) and [logcat](https://developer.android.com/studio/command-line/logcat) to get logs from there? Logcat can sometimes have extra information, so if you're up for getting them, you can send them directly to me via cody@signal.org or DM me on the community forum at [cody-signal](https://community.signalusers.org/u/cody-signal).

**Comment by crudlover** [comment]
Emailing you now, thanks Cody.

**Comment by crudlover** [comment]
Hi Cody, any word on this? Thanks.

**Comment by cody-signal** [comment]
Looks like ya got flagged as spam, will look into tomorrow when I'm back online fully.

**Comment by crudlover** [comment]
Any word? Signal is taking up 3-4GB of space on my phone with no way to use it... I just wanna export my chats at this point

**Comment by cody-signal** [comment]
It looks like one of the database files became corrupt. I sent to logs to the team in hopes they could find something but it's been busy here (end of quarters are always hectic) and got dropped. I could potentially get you a special build to ignore that file but not sure that would get you much further based on what else I'm seeing in the logs.

**Comment by crudlover** [comment]
Hi Cody, would you be able to send me that special build? I'd like to give it a shot and see. Let me know, thanks!

**Comment by cody-signal** [comment]
Try anything 5.24.4 or later. It should be available via Play Store or the beta channel.

**Comment by crudlover** [comment]
I've since updated to 5.32.10. Launching Signal just prompts a screen that reads "Signal is updating..." for around 30 seconds until it crashes.

I've since been able to run adb and logcat, here is my log during the crash: https://paste.c-net.org/RummageEarliest

**Comment by greyson-signal** [comment]
Hi there, unfortunately the log indicates there was some irrecoverable database corruption. I unfortunately can't really deduce much else. The damage to the file is such that it's not even recognized as a database anymore.
