### ISSUE TITLE
Sending a text file changes its content

### ISSUE THREAD

**Issue by mgerlach-phys** [signalapp/Signal-Android#11573]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send a `UTF-8` encoded text file with `JSON` conent the receiver gets a slightly changed one.
Test issue was with the following file: [send.txt](https://github.com/signalapp/Signal-Android/files/7071142/send.txt)

The send file has 531B, the received one has 541B and looks like this: [received.txt](https://github.com/signalapp/Signal-Android/files/7071141/received.txt)

The content is equal except for a second line with some chunk from the end of the original file and no newline at the end.

It also occurred with sender/receiver switched.

### Steps to reproduce
- Send file `send.txt` to another user and noting its size
- Check file on receiving device and see that file size and content differ

**Actual result:** The file I send is not the file others receive.
**Expected result:** The files should (obviously) be the same.

### Screenshots

File name was changed to upload it to github.

#### Sender:
![sender](https://user-images.githubusercontent.com/55398943/131226417-af88dcd3-2192-4b7f-841b-4e7feb328d7d.png)

#### Receiver:
![receiver](https://user-images.githubusercontent.com/55398943/131226409-525547ef-cf5d-4065-a14f-2ed5560dc3f1.png)

#### Sender:
**Device:** OnePlus One
**Android version:** 11
**Signal version:** 5.21.6

#### Receiver:
**Device:** OnePlus 5
**Android version:** 10
**Signal version:** 5.21.6

### Link to debug log

Not Immediately after occurrence but maybe it is sufficient:
https://debuglogs.org/991ef852ac763bb50e1d87e3c82f9eea95ae75868f82a9168f601ebf07a19ea6

Please let me know if you need more details.

Thanks in advance.

**Comment by Sgn-32** [comment]
"Sending" the file in "Note to Self" don't change it.
Receiving it on the device with no auto-download shows first 531B
![Screenshot_1630336654](https://user-images.githubusercontent.com/49990901/131362905-bd95dcc3-79aa-4ea9-b2c3-d241b8587b4b.png)
After downloading 541B
![Screenshot_1630336670](https://user-images.githubusercontent.com/49990901/131362907-59e03cf3-5d1d-4068-9eb2-3b0842f263ed.png)

**Comment by issteve** [comment]
I can reproduce this, too. By using note to self some characters got added at the end - but not always parts of the text before, sometimes just other unreadable (unicode?) characters. Maybe this is a charset coding/decoding issue?
