### ISSUE TITLE
Signal crashes instantly after update to Beta 5.22.5 when android device is online

### ISSUE THREAD

**Issue by markusd112** [signalapp/Signal-Android#11583]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Last night there was an update to Signal 5.22.5 and now signal crashes instantly after starting it. When switching my phone in offline mode (airplane mode) Signal app doesn't crash. When activiting network, it crashes instantly.

### Steps to reproduce
- start signal app
- it crashes immediatly

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
It crashes

### Device info

**Device:** Samsung Galaxy A51
**Android version:** 11
**Signal version:** 5.22.5

### Link to debug log

unable to do that, because it crashes immediatly after start, but I have sent several crash reports via android crash reporting... maybe that helps to find the bug

**Comment by markusd112** [comment]
I tried to connect a computer via adb to my android phone and get a logcat with the log entries in the moment when signal crashes. Mabye this could help....

`09-01 17:19:58.241 18106 18314 W ContactRecordProcessor: Newly discovering a registered user via storage service. Saving a storageId for them.
09-01 17:19:58.247 18106 18314 I DefaultStorageRecordPro: [0][SignalContactRecord] [Remote Update] [ID, UUID]
09-01 17:19:58.247 18106 18314 I DefaultStorageRecordPro: [0][SignalContactRecord] [Local Update] [ID, IdentityKey]
09-01 17:19:58.253 18106 18314 I libsignal-client: rust/bridge/jni/src/logging.rs:173: Initializing libsignal-client version:0.8.4
09-01 17:19:58.258 18106 18314 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
09-01 17:19:58.258 18106 18314 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18106
09-01 17:19:58.258 18106 18314 E AndroidRuntime: java.lang.AssertionError
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.externalPush(Recipient.java:223)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:98)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:89)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.fromExternalPush(RecipientId.java:68)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.IdentityDatabase.saveIdentityInternal(IdentityDatabase.java:329)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.IdentityDatabase.updateIdentityAfterSync(IdentityDatabase.java:263)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.RecipientDatabase.applyStorageSyncContactUpdate(RecipientDatabase.java:849)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.updateLocal(ContactRecordProcessor.java:144)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:23)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:279)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:175)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
09-01 17:19:58.258 18106 18314 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: java.lang.AssertionError
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.Recipient.externalPush(Recipient.java:223)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:98)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:89)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.RecipientId.fromExternalPush(RecipientId.java:68)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.IdentityDatabase.saveIdentityInternal(IdentityDatabase.java:329)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.IdentityDatabase.updateIdentityAfterSync(IdentityDatabase.java:263)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.RecipientDatabase.applyStorageSyncContactUpdate(RecipientDatabase.java:849)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.updateLocal(ContactRecordProcessor.java:144)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:23)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:279)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:175)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
09-01 17:19:58.258 18106 18314 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
09-01 17:19:58.259 18106 18320 D ConversationListDataSou: [size(), UnarchivedConversationListDataSource] 3 ms`

**Comment by cody-signal** [comment]
We just pushed .6 to beta, you can get it right away via [Firebase](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538) or wait the handful of hours for Google to publish to Play Store.

Could you report back if installing that version fixes this problem?
