### ISSUE TITLE
Wrong day being displayed for messages

### ISSUE THREAD

**Issue by alex-bellon** [signalapp/Signal-Android#11589]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages that were sent/received on previous days are marked with the correct time but incorrect date. For example, in the screenshot below, a message was sent yesterday at 1:09pm but shows as being sent today at that time (even though that time is in the future as you can see from the system time at the top). The preview in the messages/group chat list shows the correct time for the latest message (~22h in this case). The issue only happens when a message arrives when Signal is not open, the day is correct if I receive a message while I have the chat pulled up.

### Steps to reproduce
- Open Signal to chat after a message has been sent
- Look at date for the latest message

**Actual result:** The day of the message is incorrect but the time is correct
**Expected result:** The day should be correct as well

### Screenshots
![signal-bug](https://user-images.githubusercontent.com/24237402/131899297-f1dd77de-fd6a-4c67-b503-4aa6f0358b68.jpg)

### Device info
**Device:** OnePlus 6 - as a note, I have the system fingerprint lock enabled for Signal (in addition to Signal's fingerprint lock)
**Android version:** 11
**Signal version:** 5.21.6

**Comment by Dakkaron** [comment]
I have the same bug on a Moto Z Play, Android 7.11, also Signal 5.21.6.
I wonder if it has to do with time zones. My time zone is GMT+1 or (currently) UTC+2.

**Comment by alex-bellon** [comment]
I'm in Pacific Daylight Time, GMT-7. The messages are usually sent around noon and I am usually checking them around noon.

**Comment by issteve** [comment]
Are the messages originally sent from the same or a different time zone?

**Comment by alex-bellon** [comment]
The messages are sent from the same time zone

**Comment by Dakkaron** [comment]
I actually don't think its the time zone anymore.
I had the same occur with a message sent at 22:39 (displayed as yesterday) and a message sent at 22:45 (displayed as today). But I put my phone in airplane mode in between and only disabled airplane mode the day after.

So maybe it has to do with the time when was received, instead of the time it was sent?

**Comment by alex-bellon** [comment]
Yes, this issue is still occurring.

**Comment by alxgb** [comment]
Same here. I was sent a message yesterday at 5pm & received it today at 3pm. Desktop app shows it correctly as Yesterday 5pm, phone app shows it incorrectly as Today 5pm (actually in the future when I first saw it, I got confused).

**Comment by alxgb** [comment]
@greyson-signal, sure! But I don't think that's it. Message details for the one I got is correct, that's how I figured out why I got a message in the future:
![details-android](https://user-images.githubusercontent.com/35918323/155211937-f5a33581-04ed-4025-abd7-6a1cb0eb1d78.png)

And this is how it looks in the conversation view (of course, it **incorrectly** says Yesterday as it's now 22nd)
![convo-android](https://user-images.githubusercontent.com/35918323/155212095-684216cd-d328-4d8d-b6ad-6d808b74a07e.png)

Desktop shows Sunday correctly
![desktop-convo](https://user-images.githubusercontent.com/35918323/155212324-f84537f9-2244-428e-bc1d-667d0ba677bb.png)
