### ISSUE TITLE
Messages and calls do not send notifications

### ISSUE THREAD

**Issue by omargoda** [signalapp/Signal-Android#11599]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages and calls do not send notifications unless the application is launched manually.

### Steps to reproduce
- Install signal
- Try calling yourself from another device
- Call does not reach you unless the application is open
- Messages also do not send notification unless you launch the application manually

**Actual result:** Messages and do not send notifications unless the application is launched manually
**Expected result:** Messages should send notifications even if the application is not running in the background and calls have to ring and show call screen without the need of keeping the application open on the screen all the time to receive a call.

### Device info
**Device:** Huawei Nova 7i
**Android version:** 10
**Signal version:** 5.21.6

**Comment by cody-signal** [comment]
Could you follow the directions here to help out? Thanks!

https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

**Comment by omargoda** [comment]
@cody-signal Of course, I will Inshallah. Thanks a lot!
