### ISSUE TITLE
Unable to delete messages that have been read

### ISSUE THREAD

**Issue by tsikmartin** [signalapp/Signal-Android#11590]
Previously I was able to delete messages for everyone that have been read or not read. And now I cannot. Was this a feature change? 

https://debuglogs.org/3e107bd0ab5a449297185fb01526ee936545ba7af1d8fd8cd3232be71ec517eb

**Comment by tsikmartin** [comment]
This seems to occur when the message is a few hours old

**Comment by UserX404** [comment]
'Delete for everyone' is only available within the first 3 hours.
This is the actual implementation and isn't a bug.

**Comment by tsikmartin** [comment]
Ah okay thank you, did not know that
