### ISSUE TITLE
High CPU usage in background causing battery drain

### ISSUE THREAD

**Issue by bronsonarnold** [signalapp/Signal-Android#11604]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Yes, yet another battery drain issue but I think this one is interesting.

Sometimes, when the phone is plugged in and on LTE with USB tethering, `org.thoughtcrime.securesms` starts using 20-30% CPU in the background. This happens randomly and does not coincide with receiving messages. The high CPU usage continues indefinitely (once my phone ran out of battery and shut down) if left untouched. Unplugging from the charger does not stop it. The only way to stop it is to either open Signal, rebooting or force stop Signal. Doing any of these stops the high CPU usage immediately.

Output from `adb shell top` (probably not helpful, but this is how I found out it was Signal)
```
User 26%, System 10%, IOW 0%, IRQ 1%
User 318 + Nice 0 + Sys 124 + Idle 734 + IOW 3 + IRQ 12 + SIRQ 10 = 1201

PID  USER     PR  NI CPU% S  #THR     VSS     RSS PCY Name
8596 u0_a324  20   0  25% R    89 4130916K 240436K  bg org.thoughtcrime.securesms
1485 system   18  -2   2% R   218 2704476K 296628K  fg system_server
679  system   -2  -8   1% S    15 258936K   8544K  fg /system/bin/surfaceflinger
1871 u0_a80   20   0   1% S    39 1861412K 152232K  fg com.android.systemui 
```

Because the phone is plugged in, Android battery monitoring doesn't seem to measure its usage and it actually took me a while to realize it was Signal. I have had Signal for over a year now and this only started happening around 1.5 months ago. I didn't update Signal until it said it would expire so the last working version would've been around 4 months ago.

### Things I have tried
- Scratch head - No change
- Reboot phone - Issue returns after a few days
- Reinstall Signal (twice) - No change

Looked through debug logs and bug report to find any correlation.
In the latest occurrence (02:44 AM today, screenshot below), it coincided with a `RESET:TIME` event and the battery dropped from 100% to 95%. Then it plummets from there and Signal goes crazy. Looking at the Signal logs at that time, however shows nothing.

I am not super familiar with Android but in many devices, the battery stops charging when it reaches 100% and allows it to drop to around 95% before recommencing charging to reduce wear to the battery from constantly keeping it at 100%. Is it possible that the event triggers something in Signal that causes it to get stuck in a loop? I know it monitors the charging state to determine when it should do a backup so maybe that's a lead.

```
         +23m59s020ms (2) 100 d2080020 stats=0:"write"
         +27m32s088ms (2) 100 d2080020 temp=255
         +31m12s192ms (2) 100 d2080020 stats=0:"get-stats"
         +31m55s540ms (2) 100 d2080020 status=full
       +6h18m41s076ms (50) RESET:TIME: 2021-09-09-02-44-26
       +6h18m41s076ms (3) 096 d2080020 status=charging health=good plug=usb temp=315 volt=4129 charge=0 +running +wake_lock +wifi_full_lock +mobile_radio +plugged phone_signal_strength=great +wifi_running +charging wifi_suppl=disconn fg=u0a254:"com.digibites.accubattery"
                 Details: cpu=9310u+10120s
                          /proc/stat=9820 usr, 9590 sys, 1210 io, 970 irq, 640 sirq, 67900 idle (24.7% of 15m 1s 300ms), PlatformIdleStat null
       +6h18m41s076ms (2) 096 d2080020 fg=u0a285:"com.mc.miband1"
       +6h18m41s076ms (2) 096 d2080020 fg=u0a271:"com.gsamlabs.bbm"
       +6h18m41s076ms (2) 096 d2080020 top=u0a91:"com.sonymobile.home"
       +6h18m41s076ms (2) 096 d2080020 user=0:"0"
       +6h18m41s076ms (2) 096 d2080020 userfg=0:"0"
       +6h18m41s076ms (2) 096 d2080020 longwake=u0a254:"Charging"
```

I can't think of anything else but to install Android Studio and install Signal with debug symbols so I can profile it the next time this happens. Any tips would be appreciated as I am not super familiar with the Android ecosystem.

### Steps to reproduce
- Install Signal
- Plug into a router/laptop and turn on USB tethering (don't know if this is relevant)
- Wait for phone to get hot and battery to drain faster than it can charge (500mA source) (may take a day or two)

**Actual result:** CPU usage increases, phone gets hot
**Expected result:** Not the above

### Device info
**Device:** Sony Xperia XZs Dual G8232
**Android version:** 7.1.1
**Signal version:** 5.21.6

Extra info:
- **Google Play Services installed and enabled** and I am getting FCM messages so it's not [this](https://github.com/signalapp/Signal-Android/issues/9729)
- Battery optimizations for Signal is disabled
- Background data unrestricted
- I am not in any large groups (2 groups with ~20 people each)

### Screenshot
![0-02-07-fe58704a89f939c590f5bd4cb37f6e57a575ecdf98069b32b9868e6cb7872dc4_953aac312d0aa73c](https://user-images.githubusercontent.com/85420642/132643498-91006e35-7fda-472e-b226-6c808783854a.jpg)

### Link to debug log
https://debuglogs.org/1e3fc3ea0e4cfcf5eeec04b67aab547341662ae04fac5b56a87ebe2ee0ab7f49

Bug reports also available. One is just after opening the Signal app and stopping the high CPU usage and another taken during the high CPU usage.

**Comment by jujumo** [comment]
I suffer something very similar, Even such drastic, that phone could not even charge.
I tried the same solutions, and I get the same outcomes.

I was also wondering if its not related to desktop app that is endlessly loading messages (counter incrementing for no reasons?).

**Comment by 17twenty** [comment]
![Screenshot_20210930-073320](https://user-images.githubusercontent.com/379176/135351706-80be6233-424d-4149-961f-0092c0b7ebd0.png)
Also seeing high drain on Pixel 3.

Killing signal saves half my daily battery (there's no way signal should be doing as much as Chrome for example)

**Comment by LoveIsGrief** [comment]
Same on OnePlut 3T
![signal-2021-10-03-110808](https://user-images.githubusercontent.com/2829538/135925889-198ab546-00c4-4a41-9bfa-6a6a1d62d3d9.png)

When Signal is killed and only used on my PC the battery life **doubles**.

**Comment by heinrich-ulbricht** [comment]
For me a drain issue reappeared a few weeks ago(?), always after updating the Signal app. And as in the past it could be fixed (so it seems) by opening Signal, disabling notifications and enabling them again.

Bit maybe the pure act of opening Signal was enough to stop the drain, like with the OP? Who knows. But there seems to be a correlation with notifications for me, so this might be a different bug.

Poco F1
Lineage OS
Android 11

**Comment by greyson-signal** [comment]
Hey folks, per usual, we can't do much with screenshots. At minimum, please provide a debug log. Ideally, for battery issues, we need an [Android Bug Report](https://developer.android.com/studio/debug/bug-report) which I recommend you email to me at greyson@signal.org. Thanks!

**Comment by bronsonarnold** [comment]
Thanks for the extra information everyone. I don't have the desktop app so we might be looking at two different bugs here or maybe the desktop app is just another trigger for the same issue.

**Comment by greyson-signal** [comment]
Hi there, let's merge this into #11031
