### ISSUE TITLE
Razer Phone 2 Loudspeaker Echo (AEC Blacklist?)

### ISSUE THREAD

**Issue by Cjkeenan** [signalapp/Signal-Android#11601]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Echo can be heard from the other party of themselves when loudspeaker is initiated once the call has been started. If the loudspeaker was turned on while the call was still ringing or waiting for a response, there is no echo reported. However if loudspeaker is turned off and then back on, there now is an echo reported.

### Steps to reproduce
- Initate call
- Call is picked up
- Turn on loudspeaker

**Actual result:** Other user reports being able to hear themself on their side.
**Expected result:** What is coming out of the loudspeaker and into the microphone should be canceled so that the other user does not hear themselves.

### Device info
**Device:** Razer Phone 2
**Android version:** 9
**Signal version:** 5.23.1

### Link to debug log
[Loudspeaker turned on when ringing then toggled in call](https://debuglogs.org/7dfa1842ed01603bd14dc30a6e3f91f28f3084e5d5f536d397dda2917d7718b9)
[Loudspeaker turned on during call only](https://debuglogs.org/168594bc84f0a4dce26dd82750004e21996b4f156faf234bc52ea1996de14f6e)

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
