### ISSUE TITLE
Sending MOB doesn't work, receiving is OK 

### ISSUE THREAD

**Issue by sweah** [signalapp/Signal-Android#11600]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not able to send MOB to other signal users. Payments are enabled and I can choose a receiver, set a comment and adjust the amount. But after that, the pay button is still greyed out.

### Steps to reproduce
- go to settings
- choose payments
- choose send
- choose receiver
- set amount and comment
- pay button is still greyed out

**Actual result:** pay button is still greyed out
**Expected result:** payment should be possible via pay button

### Screenshots

![pay_button](https://user-images.githubusercontent.com/1198892/132297183-677011ff-0333-4fda-a0e8-b60f213e6c2e.jpeg)

### Device info

**Device:** Redmi Note 8T
**Android version:** 10
**Signal version:** 5.23.1

### Link to debug log
https://debuglogs.org/cc6a6c9ea4cc64bc379a61a77077133aed739d355bd9fca3cc739c5069d5b8e2

**Comment by cody-signal** [comment]
This will be fixed in the next release, it was an issue validating amounts with a decimal amount.

**Comment by sweah** [comment]
Is fixed in 5.23.2. Thank you for all the good work!!
