### ISSUE TITLE
Duplicate code offered for quick copy in notification (verification code by PayPal) 

### ISSUE THREAD

**Issue by kofaysi** [signalapp/Signal-Android#11615]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Duplicate code is offered for quick copy in notification (verification code by PayPal). Only one quick copy field is expected.

I have not found the help/manual page describing this feature of quick copy fields in notification. I may have use incorrect or false terms. screenshots shall help to ex[plain. Please, correct the terminology in comments, if needed.

### Steps to reproduce
- Receive a verification code by PayPal
- Observe the notification of that message

**Actual result:**

The code is offered twice for copying.

**Expected result:**

The code is offered in a single instance, i.e., only one quick copy field.

### Screenshots

The duplicate quick copy field in notification:
![image](https://user-images.githubusercontent.com/17022173/133154868-3cc07a0c-5738-4832-b4fe-5112777f7652.png)

The original message that was parsed in the notification:
![image](https://user-images.githubusercontent.com/17022173/133154805-aa292601-6b6a-4688-acb5-64949a0ed87f.png)

### Device info

**Device:** LG G5 aka h850 with eOS version 0.18-q
**Android version:** 10
**Signal version:** 5.17.3

**Comment by greyson-signal** [comment]
We actually don't generate those suggestions, they're generated by your operating system. Feel free to file a bug with them :)
