### ISSUE TITLE
Video thumbnail shows trimmed-out part of the video

### ISSUE THREAD

**Issue by righy** [signalapp/Signal-Android#11612]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

#### Bug description

When I send a video on which I trimmed out the beginning, the resulting message on the sender's phone displays a thumbnail/poster that is based on the trimmed out part of the video.

#### Steps to reproduce
- Make sure you have a video more than 10 seconds long on your device.
- Open Signal.
- Open a recipient's conversation.
- Tap the `+` icon and select the video. The video preview opens.
- Use the slider at the top of the screen to trim out the first 10 seconds of the video.
- Send the video.

**Actual result:** On the sender's phone, the video thumbnail is a image taken from the first 10 seconds of the video. As a user, I am afraid that the recipient is seeing an image from the video I didn't want him/her to see. In reality though, the recipient sees a different thumbnail, one that actually matches the part of the video that was sent, so there is no "breach of privacy", but the UI is misleading.

**Expected result:** On the sender's phone, the video thumbnail should be an image taken from whatever part of the video that was actually sent to the recipient. Ideally, the sender and the recipient should just see the same thumbnail.

#### Device info

**Device:** OnePlus 5

**Android version:** Android 11 with LineageOS

**Signal version:** 5.22.8

**Comment by Tursko** [comment]
I have also noticed the same thing.
