### ISSUE TITLE
Large images displayed in incorrect orientation

### ISSUE THREAD

**Issue by goughy000** [signalapp/Signal-Android#11614]
When receiving high dimension photos from one of my contacts (iPhone X), the photos show in the correct orientation when in the thumbnail but are rotated 90 degrees when tapped on to show full screen.  Other users in our group chat who are on Android also see the same issue when receiving these images, but users on iOS don't see the issue.  This suggests it's something to do with the way the Signal App on Android is parsing orientation data.  When receiving images from users on older iPhones we don't see the issue on Android.

I've not been through with the debugger yet but read through what I think are the relevant bits of code..

**Version**: 5.22.8

This line in ZoomingImageView sets the orientation mode to be set from EXIF data: https://github.com/signalapp/Signal-Android/blob/v5.22.8/app/src/main/java/org/thoughtcrime/securesms/components/ZoomingImageView.java#L69

The image dimensions are over 2048 px in height and so subsampling is used: https://github.com/signalapp/Signal-Android/blob/v5.22.8/app/src/main/java/org/thoughtcrime/securesms/components/ZoomingImageView.java#L108

This calls setImage on the SubsamplingImageView: https://github.com/signalapp/Signal-Android/blob/v5.22.8/app/src/main/java/org/thoughtcrime/securesms/components/ZoomingImageView.java#L131

I'm not really sure what goes wrong next.. it must be possible to calculate the correct orientation as it is correct in the thumbnail.  When I get some time I'll attach the debugger to see what's happening after this point but if anyone else has time before and is interested then feel free to pick it up

**Comment by artnc** [comment]
I've just opened PR #11881 to fix this :crossed_fingers:

**Comment by artnc** [comment]
My fix above is still intact in this repo but yes, the bug also started reappearing again for me at some point in the intervening 2.5 years 🙁
