### ISSUE TITLE
MOB Wallet adress: Invalid adress format.

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#11621]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to send MOB from an external wallet (Mixin Messenger) to my signal wallet, I get an error message: "Invalid address format." 

### Steps to reproduce
- use the address given via settings -> payment -> receive
- give it as receiver from external wallet.

**Actual result:** The given address seems to be in a wrong format.  
**Expected result:** show correct formatted address

### Device info
**Signal version:** 5.23.7

**Comment by alex-signal** [comment]
Hi! Is the "Invalid address format" message coming from Mixin Messenger or from Signal? Could you please include a debug log?

**Comment by mawed** [comment]
The error message is shown within Mixin Messenger when trying to send MOB to any signal wallet.

Tried the addresses of several friends Signal Wallet.

So a debug won't help, as the problem seems to be the formatting of the wallet address. It is for example much longer then mixins Wallet address.

**Comment by alex-signal** [comment]
@mawed Thanks! Signal displays the Base58 public address in this view. I *believe* this is made of two components, the fog service uri and your public address. There's a possibility that Mixin Messenger doesn't expect the fog service API. However, Signal is just using what the official MobileCoin SDK gives us to display. Thus I do not think this is an issue with Signal, rather it's an issue with Mixin Messenger.

**Comment by mawed** [comment]
Ok, then I will close this issue.
Thanks for your full answer.
