### ISSUE TITLE
Unable to edit pictures when forwarding

### ISSUE THREAD

**Issue by Anston** [signalapp/Signal-Android#11629]
While forwarding a picture there is no option to edit it.

**Comment by UserX404** [comment]
Please don't delete the issue template and append your logs.
There were some changes in the workflow. When you forward a message with a picture form the chat by longpress you are not able to modify the image anymore. But when you open the image (fullscreen) and forward it via the 3-dot-menu in the upper right you were able to do some changes after selecting the recipient.

**Comment by alex-signal** [comment]
Hi, this was an intentional change when forwarding directly from a conversation. If you'd like to edit media before sending, you can always open the media preview (click once on the media in conversation) and then in the 3dot menu, you can share it or forward it.
