### ISSUE TITLE
App crashes on sharing images

### ISSUE THREAD

**Issue by fuufdiji** [signalapp/Signal-Android#11628]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing an image, Signal crashes.

### Steps to reproduce
- Go to system gallery and open a picture
- hit share via Signal
- In Signal's "Share with" menu choose a contact and hit the blue arrow button to confirm

**Actual result:** Signal crashes. (popup with "Signal angehalten - OK" in the German version)
**Expected result:** Chat window with the chosen contact opens. The picture is attached and I can edit the picture.

The same happens if I look at an image in Signal (that I previously received via Signal) and try to forward that image (since it leads to the share screen, not the forward screen). Forwarding works as intended.

### Device info

**Device:** Samsung Galaxy S3 Neo
**Android version:** 4.4.2
**Signal version:** 5.23.8

### Link to debug log

https://debuglogs.org/4ed7dcbf84baeb8f8384bc99ee0a6d08a1fa4cd54acf7537c5f241317cdf2ad4

**Comment by alex-signal** [comment]
Ahh, looks like we used a vector image in a way that is incompatible with KitKat. Thanks for the report!

**Comment by fuufdiji** [comment]
As far as I can see the fix you commited is a part of version 5.24.2. However, the same behaviour occurs with version 5.24.6
This is a new debug log with 5.24.6:
https://debuglogs.org/3ab1839ba408e6d4138e419df02668baf8d322475642dd765e57b9d9ab9337d9

**Comment by alex-signal** [comment]
@fuufdiji Sorry about that! I'll take a look.

**Comment by alex-signal** [comment]
This'll be fixed in `5.25`, sorry again!

**Comment by fuufdiji** [comment]
works again as of 5.24.14, thanks! Also thanks for the fast replies throughout the issue =)
