### ISSUE TITLE
images missing corners

### ISSUE THREAD

**Issue by orangecms** [signalapp/Signal-Android#11625]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I send an image, in the message view itself, the corners are missing, somewhat strongly rounded, even in the image editor. Only in the full image view, the corners are there, or in the editor, when e.g. in crop mode.

### Steps to reproduce

- in a chat, select an image for sending
- (optionally) send the message

**Actual result:** The corners of the image are missing/rounded
**Expected result:** The image should be visible as is

### Screenshots

![Screenshot_20210918-195341_Signal](https://user-images.githubusercontent.com/4245199/133898065-cd472d35-4f4d-478e-aff2-7c469d58706e.png)

### Device info

**Device:** Xiaomi sagit / Mi 6
**Android version:** 11
**Signal version:** 5.23.7

**Comment by UserX404** [comment]
This certainly is intendent and not a bug.
Feature requests should be discussed in the [forum](https://community.signalusers.org/).
