### ISSUE TITLE
Only call buttons icons rotate in landscape view

### ISSUE THREAD

**Issue by omargoda** [signalapp/Signal-Android#11623]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Buttons icons rotate on a call without other components on the screen rotating with them. It is better either that nothing rotates on landscape view, or the whole view rotates with the screen (e.g, text, photo, etc....)

### Steps to reproduce
- Open Signal
- Start a call with a contact
- Make sure you enable screen rotation
- Turn the device to the landscape view

**Actual result:** Buttons icons turn horizontally without other components on the screen rotating with them
**Expected result:** Either nothing rotates, or the whole view rotates to landscape view with the text and other data on the screen

### Screenshots
![Screenshot_20210917_151557](https://user-images.githubusercontent.com/50413030/133788912-5fd8ba25-05d0-4250-89cb-25478c15f7e4.jpg)

### Device info
**Device:** Huawei Nova 7i
**Android version:** 10
**Signal version:** 5.22.8

**Comment by alex-signal** [comment]
Hi! Thanks for your report. This was originally an intentional design decision for phone-sized devices due to screen real estate, but that was before we had labels on the buttons. I'll bring this up with design.

**Comment by omargoda** [comment]
@alex-signal Great, happy to hear that. Good luck 👍
