### ISSUE TITLE
Images fails to load randomly and sharing sometimes fails on Fold 3

### ISSUE THREAD

**Issue by Racle** [signalapp/Signal-Android#11620]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug 1 description
Images fails to load randomly.

### Steps to reproduce
- Recieve image
- Randomly image recieved is broken (with image icon + red triangle)

**Actual result:** Random images are broken/unloaded. Happens even with link image preview.
**Expected result:** Image should load normally. Works as intended on PC app.

### Screenshots
![image](https://user-images.githubusercontent.com/759091/133458105-a631c6b3-7b65-4195-8936-8e96a53599f9.png)

### Bug 2 description
When sharing to signal, sometimes it's shared to wrong group/person.
Sometimes it also tries to share older thing what I've shared.

I believe this might be happening because Fold 3 and using it both folded and unfolded state. 
Signal might be broken because of changing aspect ratio or something like that.

Swiping signal away from recent apps menu fixes this situation. (it doesn't fix bug 1)

### Device info

**Device:** Samsung Galaxy Fold 3
**Android version:** 11
**Signal version:** 05.23.7 (beta channel @ play store)

**Comment by UserX404** [comment]
Hi @Racle
For such an issue please append your log and specially for this image issue one a log of from the other user would be helpfull.

**Comment by Racle** [comment]
@UserX404 
I get log when this happens again. It's random so I really don't know when that happens. I'll get log when that does
And image issue is happening in happening in group chat.

For second bug, I got it repeat and here's the log for that (should be near 1min before log ends, as it took little time to find correct menu. Also your readme isn't up to date on that): 
https://debuglogs.org/e4f6cdb201885b75e810e6dab7d60dc991889e37fcef9acbc21df725ad147062

**Comment by greyson-signal** [comment]
We believe we've found that this bug is related to thread trimming (in your case, the setting where you delete messages older than a certain time period). We have a fix for 5.24. In the meantime, my suggestion would be to disable thread trimming until we get the fix out. Thanks!

**Comment by Racle** [comment]
> We believe we've found that this bug is related to thread trimming

Bug 1 or 2? Or both?

**Comment by greyson-signal** [comment]
Ah, I was talking about #1. Usually we do one bug per issue, didn't see there was a second problem. We'll try to repro ASAP.

**Comment by alex-signal** [comment]
@Racle 

Hi! Can you confirm reproduction steps for me?

When you say sharing, which method of sharing are you specifically talking about? (It sounds like you're trying to forward individual parts of messages?)

**Comment by alex-signal** [comment]
(misclicked close, my bad)

**Comment by Racle** [comment]
@alex-signal 
> When you say sharing, which method of sharing are you specifically talking about? (It sounds like you're trying to forward individual parts of messages?)

I shared via share button from YouTube and from Samsung own Gallery app (this is also happened when I'm sharing screenshot).

With that log, IIRC I tried to share one or two different chats. Folding / unfolding phone between sharing tries usually triggers this for me. And you don't have to send the message, you can just close image / delete YouTube link in signal.

Steps (+ logs from signal) are in message above:
> For second bug, I got it repeat and here's the log for that (should be near 1min before log ends, as it took little time to find correct menu. Also your readme isn't up to date on that):
https://debuglogs.org/e4f6cdb201885b75e810e6dab7d60dc991889e37fcef9acbc21df725ad147062
When bug happened, I shared image, cancelled that, folded, shared youtube link, removed link from messagebox, unfolded, shared image again, but signal tries to share that youtube link for some reason.

**Comment by UserX404** [comment]
@greyson-signal 
After updating to 5.23.7 i also run into this broken image issue. I had trimming enabled (1000) and disabled it as you mentioned.
I asked the other user to resend the picture but an other broken image arrived shown.

Timestamp:
1631784798386

https://debuglogs.org/fb6f974d5d87c979f96d5cd81213f9265105cd2e8733aad4d9cf7fb9e8fe4680

**Comment by greyson-signal** [comment]
@UserX404 So what happened here is that the original image attachment broke because of the bug. But then because the *same* image was sent again, we de-duped it based on the file hash and instead just made it a reference to the same (now-missing) underlying file.

For now, if you want to get that same file again, I'd delete all messages that reference that broken attachment and then ask for it to be resent again. We can add additional checks in the next release to prevent this bad interaction.

**Comment by UserX404** [comment]
@greyson-signal

Can confirm a correctly received image after deleting the old dupes.

**Comment by alex-signal** [comment]
Hooo boy so this ended up being due to launching the ShareActivity with `singleTask`... After you open the phone, go to gallery, and share the Activity is created but handed the old intent. My guess is maybe there's a bug in how the record keeping works for moving activities between screens (in Android, not Signal) or I am misunderstanding how `singleTask` works.

Removing the launchmode seems to have fixed the issue, so we'll release that in the next beta but we'll have to keep an eye on it, as there's a chance it will cause issues on API19.

**Comment by piratenpanda** [comment]
Does this also fix my issue https://github.com/signalapp/Signal-Android/issues/11199
