### ISSUE TITLE
Internationalized domain names not recognized as link

### ISSUE THREAD

**Issue by donovaly** [signalapp/Signal-Android#11636]
### Bug description

Links containing non-ASCII characters are not recognized as links

### Step to reproduce

* Share a link that contains an accented character e.g. https://stühlinger-magazin.de/

### Result 

There is no link preview, the URL is not recognized as a proper link (not clickable)

### Expected

non-ASCII characters in webdomains are standardized since 11 (sic!) years since many languages have accented characters:
https://en.wikipedia.org/wiki/Internationalized_domain_name
Therefore Signal should not have a problem with them.

I see that Signal is programmed in Java. Java fully supports IDNs: https://docs.oracle.com/javase/7/docs/api/java/net/IDN.html

Maybe this bug has the same cause as #11247 since an IDN can contain any Unicode character.

### Signal Version

5.23.8
(on Android 11)

**Comment by greyson-signal** [comment]
We only linkify links that are either all in the ASCII range or all *not* in the ASCII range. We do not linkify links that contain a mixture. We do this to avoid [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack). 

An example would be that this link: 

[sіgnal.org](https://sіgnal.org) 

isn't what you think it is. The 'i' has been swapped out with a lookalike character. 

I don't anticipate we'll change this behavior in the near future.

**Comment by donovaly** [comment]
> either all in the ASCII range or all not in the ASCII range

I understand that IDN attackes are an issue, but accented characters are in many languages essential part of the alphabet. So when a link contains characters which are in the same ISO 8859-x code, there is no IDN attack possible because no ISO 8859-x table contains no identical characters.

Especially for the non-latin scripts this is important. For example I noticed that there are many domains with all characters within
https://de.wikipedia.org/wiki/ISO_8859-5
for example official government sites to provide easy access for people not speaking English or being able to read Latin script. So Signal should not exclude them.

I find it a bit discriminating to focus on an US American standard rather than to the worldwide ISO character sets to decide if there is an IDN attack or not.

**Comment by levino** [comment]
Why not whitelist some characters? Like `äöü` for german domains etc. Should not be a problem...

**Comment by chiraag-nataraj** [comment]
I know you all decided not to linkify IDNs. And for a long time, it really didn't matter for me (I don't run into IDNs very often).

Long story short, I registered https://ಮಿಲನ.net (or https://xn--6sclm5c.net) and Signal Android doesn't linkify it (at least it linkifies the Punycode).

I understand the phishing risks. Why not consider something like this? If an IDN is detected, linkify with a warning ("Warning: This link is an international domain. If this is unexpected, please proceed with caution." or something like that). If this is implemented, it would be nice to be able to turn off the warning after the first time ("Do not ask me again" or whatever).
