### ISSUE TITLE
Notification sound broken in 5.23.8

### ISSUE THREAD

**Issue by tomeczeka** [signalapp/Signal-Android#11631]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notification sound for Signal messages (both Signal messages and SMS received in Signal) seems to be bound to media volume, instead of notification and ringer volume. Changing system volume setting for ringer and notifications does not seem to change the sound for these. It also seems to use the default notification sound from system settings, even though I changed Signal message sound to something else. Signal call ringer seems to work fine.

### Steps to reproduce
- receive Signal message
- set notification and ringer volume setting to maximum and media volume to minimum
- receive another Signal message, it will be very quiet
- set notification and ringer volume to mute/vibrate and media volume to maximum
- receive another message, it will be very loud instead of muted

**Actual result:** the message notification volume is bound to system MEDIA volume and uses system default sound regardless of in-app settings for custom sounds
**Expected result:** notification volume should use system settings for notification and ringer volume

### Screenshots
**Does not apply**

### Device info
**Device:** Redmi Note 10 Pro
**Android version:** crDroid based on LineageOS 18.1 (Android 11)
**Signal version:** Version 5.23.8, also happens in 5.24.1 beta

### Link to debug log

https://debuglogs.org/2c165a8e717d82cfd5bd20ad5b2ce119014810f629dbdfa217d449027cea2555

**Comment by UserX404** [comment]
Hi
Without a log devs aren't able to help.
The [support](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) page seems to be outdated.
Try:
Settings -> help -> debug log -> submit

**Comment by tomeczeka** [comment]
> Hi
> Without a log devs aren't able to help.
> The [support](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) page seems to be outdated.
> Try:
> Settings -> help -> debug log -> submit

Found it, updated the post

**Comment by cody-signal** [comment]
All message notifications are displayed via the System OS. We simply send the notification data to the OS and it determines what audio to play and how. This feels more likely to be a bug in crDroid implementation for your device. Nothing in your logs jump out as an issue.

**Comment by tomeczeka** [comment]
> 
> 
> All message notifications are displayed via the System OS. We simply send the notification data to the OS and it determines what audio to play and how. This feels more likely to be a bug in crDroid implementation for your device. Nothing in your logs jump out as an issue.

This does make sense, however the issue started with 5.23.8 update and I'm 100% positive it wasn't there before. I will ask on crDroid channel if anyone's facing similar issues then
