### ISSUE TITLE
Support for payments/MobileCoin not working in German

### ISSUE THREAD

**Issue by jannnis** [signalapp/Signal-Android#11635]
If you use a device with German as system language and click on the link "Mehr erfahren" (en: Learn more), you won't come to the support page, but an 404 will appear. [This site is shown](https://support.signal.org/hc/de/articles/360057625692#payments_which_ones)
The issue is not present, when the system language is English. The same issue appears when switching to Spanish, so more language might be affected by this issue.
It looks like you only get the issue with the Brave browser and Chrome, but not with the Firefox. This indicates it might be an issue with the website not the app itself.

**Comment by alex-signal** [comment]
Passing onto support, thanks!

**Comment by GAS85** [comment]
Same with Russian https://support.signal.org/hc/ru/articles/360057625692#payments_which_ones
