### ISSUE TITLE
Receiving Private Notes about Delivery Failure on Phone When Using Desktop Application

### ISSUE THREAD

**Issue by flosincapite** [signalapp/Signal-Android#11632]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am receiving private notes indicating that a message could not be delivered. The private notes only show up on my phone, and only after I send a message using the Signal Desktop application for Linux.

### Steps to reproduce
- open Signal in Desktop
- send a message
- receive private note

**Actual result:** I receive private notes indicating a failed delivery.
**Expected result:** I would not expect these notifications to arrive in my private notes.

### Screenshots

![Screenshot_20210919-135350](https://user-images.githubusercontent.com/4074974/133939675-4e12fcb4-be77-4e07-9e60-b59a17b17a0c.png)

### Device info

**Device:** Google Pixel 4a
**Android version:** 11
**Signal version:** 5.24.1 (Desktop version 5.17.2)

**Comment by greyson-signal** [comment]
Please post a debuglog from both your desktop instance and android device after experiencing the issue. Thanks!

**Comment by flosincapite** [comment]
I don't have any more information and haven't used the desktop app for a
while. Feel free to close this issue.
