### ISSUE TITLE
Groups lost after deleting older messages

### ISSUE THREAD

**Issue by matthias-ronge** [signalapp/Signal-Android#11649]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was deleting older messages, to free memory. Now I am missing the groups I was in, but which didn't write for awhile.

### Steps to reproduce
- Go to "data and memory" » "manage memory" » "keep messages"
- set to 30 days, confirm delete
- set back to "forever"

**Actual result:** In the chats list, all groups that had no communication in the last few weeks are gone. I don't know if the other users have received a message that I left the group, or if the groups will pop up again if any other member writes in them, but I don’t see a way to communicate to these groups any more
**Expected result:** Groups should remain. They may be empty, but it should be possible still to send a message to the group

### Device info

**Device:** Sony Model G8341
**Android version:** 9 (build number: 47.2.A.11.228)
**Signal version:** 5.23.8 (updated 17.09.2021)

### Link to debug log

The bug happened quite a week ago or so, but I didn't realize it yet. Second, I don't see an option to create a debug log.

**Comment by Genis-Sage** [comment]
hey @matthias-ronge 
the groups are not really lost...
they show up again, as soon as somebody writes a new message
see duplicate issue: #10572

apart from that, you can press the blue pencil icon, and search for the name of the group... 
the groups still show up there

see also the feature request to change the current behaviour:
https://community.signalusers.org/t/list-of-group-names-to-be-displayed-in-contacts-section-to-start-new-conversation-after-deleting-groups-old-chat-history/19957/17

**Comment by matthias-ronge** [comment]
Thanks for the explanation. I am glad that the groups can still be retained if the name is still remembered, and it can be typed on the keyboard.

After the duplicate issue is closed, I would leave this one open until the bug is fixed.

As an aside, I consider it a bug if a delete function deletes more than it should, even if the group is only apparently deleted.

**Comment by Sgn-32** [comment]
There is a PR for showing empty threads in the conversation list.

https://github.com/signalapp/Signal-Android/pull/11343

Deleting all messages in a conversation thread only removes it from the conversation list.
A group is deleted when all members has left the group.
Either when you leave the group or you are removed by an admin.

https://support.signal.org/hc/en-us/articles/360007060712-Leave-a-group
https://support.signal.org/hc/en-us/articles/360050427692-Manage-a-group#remove

**Comment by matthias-ronge** [comment]
If that works the way you describe it, it will fix this bug.
