### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by ikanakova** [signalapp/Signal-Android#11648]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot send Signal message. An error message is displayed: "Signal is experiencing technical difficulties. We are working hard to restore service as quickly as possible."

### Steps to reproduce
- Send a signal message.
- Endless sending status and then An error message is displayed: "Signal zaznamenal technické potíže. Pracujeme tvrdě na co nejrychlejší obnově služby." (in English: "Signal is experiencing technical difficulties. We are working hard to restore service as quickly as possible.")
- restart the application
- still error message
- delete unsent message
- reboot a smartphone
- still error message

**Actual result:** Cannot send messages and error message is displayed.
**Expected result:** Can send a message and no error message about technical difficulties.

### Screenshots

![adfbadc0-16d6-4637-ae7b-967858a094d6](https://user-images.githubusercontent.com/38765251/134854923-adcef4b4-1983-45dd-b9bb-8c41e1623536.png)

### Device info

**Device:** Nokia 6.1
**Android version:** 10
**Signal version:** 5.24.4

### Link to debug log

https://debuglogs.org/e80caa893f1ab3de5acb7a71a93cd765d40e96646074795ea739e6fe7ee614cf

**Comment by akc3n** [comment]
https://mobile.twitter.com/signalapp/status/1442354759009247232

**Comment by ikanakova** [comment]
Seems to be working now for me as well.
