### ISSUE TITLE
Show "Name only" not working

### ISSUE THREAD

**Issue by bje-** [signalapp/Signal-Android#11641]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Despite setting "Show" to "Name only", I am seeing message content in the main Signal window.

### Steps to reproduce
- Note message text appearing below a contact's message in the main Signal window.
- Go to Settings -> Notifications -> Show. Set to "Name only".

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

No change in output.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

There should be no message text in the main window, only names of contacts.

### Device info

**Device:** Samsung SM-J530Y
**Android version:** 9
**Signal version:** 5.23.8

**Comment by bme13** [comment]
Hi. Please note that this setting is to configure what is displayed in the message notification. Not in the main Signal window. It's used to prevent leaking message/name details to other apps that have access to the notifications. e.g. notification loggers.

**Comment by bje-** [comment]
OK, thanks.
