### ISSUE TITLE
SMS import option

### ISSUE THREAD

**Issue by salustre** [signalapp/Signal-Android#11653]
Hi @greyson-signal 

Has this option been restored yet? This doesn't affect me personally, because I imported my SMS DB back in the old days, but I wanted to convince more people to signal, so that they would have everything in one place.

I am looking forward to it.
Best regards!

_Originally posted by @greyson-signal in https://github.com/signalapp/Signal-Android/issues/11417#issuecomment-870824028_

**Comment by Tursko** [comment]
It hasn't been restored. This tracker is only for issues. Please use the forum for questions like this.

**Comment by Tursko** [comment]
Should be closed.

**Comment by salustre** [comment]
Please restore this functionality, many people are still waiting.

**Comment by jasonpolites** [comment]
As with others.. I'd love to switch to signal for all messaging, but I still need to straddle SMS/Messages due to lack of import capabilities.

**Comment by salustre** [comment]
> Should be closed.

Should be fixed.

**Comment by greyson-signal** [comment]
Sorry, but I don't anticipate spending large chunks of time on SMS/MMS import in the future. The old implementation was very broken, and we have many higher-priority tasks.

**Comment by MaxTranced** [comment]
I think this is a valid issue that does belong to the tracker, from the following viewpoint: if Signal does present itself as an SMS app, it should let the data flow both ways, both importing the existing messages when it becomes the default and allowing the export of messages when it is no longer the default. Missing this functionality can lead to user frustration and definitely will result in it not being recommended as an SMS app. From this viewpoint one could say that the SMS experience is broken at present.

**Comment by MaxTranced** [comment]
Also, please correct me if I'm wrong, but I think that Facebook messenger does allow the data to flow both ways in this scenario?

**Comment by jasonpolites** [comment]
Without an import capability, it's not really possible to switch to Signal for all messaging, so I still need to straddle multiple apps. Heterogeneity in messaging protocols (for mobile) means SMS is still the baseline for interoperability between platforms. There are (likely) a large number of people who still need or use SMS, and it feels like Signal (et. al) would benefit from engaging those users 🤷‍♂️

**Comment by salustre** [comment]
@jasonpolites so true!
