### ISSUE TITLE
Friend shows as being "on signal" in home screen, but not listed in "new message" window.

### ISSUE THREAD

**Issue by mnissov** [signalapp/Signal-Android#11659]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A friend and I are looking to use signal. We have both installed and setup the app, when I go to the "new message" window to start a chat, they are nowhere to be seen. Then, a day later, on the home screen is shows up saying "Friends name is on signal", but I am still only able to send a sms through my carrier. I have checked my contacts, the number is written correctly with area code as "+45".

In addition, I can see and send messages to other contacts through signal with the same country code.

### Steps to reproduce
- go to "new message"
- search name
- nowhere to be find

**Actual result:** Must enable signal for sms to send messages to this person.
**Expected result:** To just be able to send messages, without using carrier.

### Device info
**Device:** Xiaomi Redmi Note 8
**Android version:** 10 QKQ1.200114.002
**Signal version:** 5.24.7.1

### Link to debug log
https://debuglogs.org/702f82051320d42c0c9309608d42cbd0f1fbb6f2682a09bb8469841cc05f6d62

**Comment by Defiana** [comment]
I have downloaded the [Signal For Windows app](https://www.downloadsignalapp.com/2021/07/signal-app-download-for-windows.html), and it runs flawlessly.
