### ISSUE TITLE
Shared contact name on incoming quote not shown

### ISSUE THREAD

**Issue by signalien** [signalapp/Signal-Android#11656]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Shared contact name on incoming quote not shown

### Steps to reproduce
- User A send a contact.
- User B replied with the contact quoted.
- User A's incoming quote on the contact name is not shown.

**Actual result:** Shared contact name on incoming quote not shown
**Expected result:** Shared contact name on incoming quote should be shown

### Screenshots

![Screenshot_20211004-112212](https://user-images.githubusercontent.com/19525001/135789750-e66ab6f5-ba61-4bab-b96a-500622572aa3.png)

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 11
**Signal version:** 5.24.7.1

**Comment by Aeonitis** [comment]
Can you tell me which text should have been replaced with which text?

It all looks natural to me.

You sent John Doe contact, they referenced and said test, you referenced your own contact message replying Yo.

Did I misunderstand you? I really don't get what's missing, I'm sorry.

**Comment by signalien** [comment]
The "test" message received with quote/reference on the contact should show the "👤 John Doe" text. Just like the one in the "Yo" message.

**Comment by Aeonitis** [comment]
I'll hopefully try and investigate this tomorrow, but I'll keep you updated.

Me (LG V40 with Signal v5.26.7 on Android 9) sending a contact to my friend...
![IMG-20211117-WA0000.jpg](https://user-images.githubusercontent.com/1273824/142262116-94b5e49f-3507-4f21-9f53-3bf15b9df2af.jpg)

My friend (OnePlus 6T with Signal v5.25.7 on Android 11, yes he doesn't auto-update) is receiving my messages as follows...
![IMG-20211117-WA0002.jpg](https://user-images.githubusercontent.com/1273824/142262262-bf04f477-06de-4f72-8184-2a06fa25d867.jpg)

Note: Arrows are just signifying our names.

@signalien if possible, in the meantime, could you help me as a second head and search other issues for possible duplicates? Just so we're sure we're following the rules(no duplicates)?

**Comment by Porkins4** [comment]
As I've found, the client seems to be receiving the correct message with correct quote (can be seen in 
_IncommingMessageObserver.java 
method handleMessage_ message -> quote -> reference -> text

Will post more info as soon as possible,
