### ISSUE TITLE
Unable to forward message to number not in contacts

### ISSUE THREAD

**Issue by kevinoid** [signalapp/Signal-Android#11650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There does not appear to be a way to forward a message to a phone number which is not already assigned to a contact.

### Steps to reproduce
- Long-tap on a message to select it.
- Press the "Forward message" button.  The "Forward to" dialog appears.
- Tap  the "Search name or number" text box to focus it.
- Enter a phone number not assigned to a contact.  (With either the text or phone keyboard.  Any number should work.  Tested with NANP 7-digit, 10-digit, and 11-digit numbers without formatting in addition to 4-digit shortcode.)
- Press blue checkmark to dismiss the keyboard.

**Actual result:** The keyboard disappears and the number remains in the search box with search results and no obvious way to proceed.
**Expected result:** An option "Forward message to... \$number", as in the "New message" dialog when a number does not match any contacts.

### Screenshots
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/336433/134956755-7160d316-fad2-47f1-ba33-9c3f93d0f58c.png"><img src="https://user-images.githubusercontent.com/336433/134956755-7160d316-fad2-47f1-ba33-9c3f93d0f58c.png" alt="Screenshot of Signal Forward to dialog with a phone number in the search box and no search results." width="270" height="480"></a>

### Device info
**Device:** Google Pixel (sailfish)
**Android version:** 10
**Signal version:** 5.24.7

Thanks for considering,
Kevin

**Comment by Genis-Sage** [comment]
hey @kevinoid 
for me, this sounds more like a feature request (which should be discussed on the [community forum](https://community.signalusers.org/)), rather than bug report

**Comment by kevinoid** [comment]
Hey @Genis-Sage, thanks for the input.  Are you affiliated with the Signal project, or just trying to help triage issues?
