### ISSUE TITLE
Signal group message can not be seen by everyone

### ISSUE THREAD

**Issue by WinnetouL** [signalapp/Signal-Android#11669]
### Bug description
We created a group chat. When person **A** sends any kind of message in this chat person **B** does most of the time (~95%) not receive anything (nor notifications or any kind of msg). In some rare cases there was a bot message like "message transfer issues", but most of the time there was nothing at all. Person **A** and **B** can chat in there private chat without any issues. Also all other members of the group do not have a problem to read any msg of person **A** also within the group chat.

Older story:
First we had two persons with this issue of having trouble receiving messages of Person **A**. We tried to add/remove members by number or adding admin permissions, but nothing helped. Then we created a seperate group with just some members and in this smaller group it actually worked. But I think as soon as we added the rest of the members the issue started again for person **B**. For person **C** it was fixed for some reason.

### Steps to reproduce
I would assume this is a rare issue as I didn't found anything similar in the web. We don't face this issue in other groups.

### Screenshots
It is german, but I guess you know your screens  ;)
![signal-2021-10-04-224327](https://user-images.githubusercontent.com/50875993/136634273-d0202f0d-b2d3-471c-91a4-13a57c69aec7.jpeg)

### Device info (person B)
**Device:** Galaxy S9
**Android version:** 10
**Signal version:** 5.24.14 (issue occured also in older versions)

Any idea what to do? Happy to help if I can :)

### Edit: Logs of dev of person **B**
(the one who don't receive msg of person **A** in that grp)
https://debuglogs.org/231d0fe9cac75b6338b0fc64cbf65d145c829a2695071d126f284f588aa36b84
https://debuglogs.org/9e05fac537f96ef7c0adcf47ebdbc363f624a8c05aa35c760cd5ba661d012bb4

**Comment by greyson-signal** [comment]
Hi there! I think this should be resolved in an upcoming release. There was an issue where we some data fell out of sync across a couple tables. Keep a look out for the next release (unsure if it's going to be 5.24.15 or 5.25.0).

**Comment by WinnetouL** [comment]
@greyson-signal that would be awesome news! Thanks for your reply mate :)
Additional information:
While we created the second group we only added a subset of the members from the inital group. During that time person **B** was able to receive messages from person **A**. After we added the rest of the inital group the issue occured again for person **B**.

**Comment by WinnetouL** [comment]
Hey @greyson-signal :)
unfortunately I have to report that the issue still remains.
If the updates fixed the issue would I have to recreate the group or do other special things?
Best regards!
