### ISSUE TITLE
Signal app crash since I reinstalled

### ISSUE THREAD

**Issue by dlevequeIT** [signalapp/Signal-Android#11663]
Hello,
My Signal app crash when I start him since I have reinstalled (after resetting my OnePlus 7T Pro on Android 11 and Oxygen OS 11.0.3.1). Somebody could help me to understand and resolve please ?

Please find log in attachment ;)
[logcat_10-07-2021_10-53-46.txt](https://github.com/signalapp/Signal-Android/files/7300860/logcat_10-07-2021_10-53-46.txt)

Thanks. Regards,
Damien

**Comment by rushikeshsuryawanshi** [comment]
Did you tried reinstalling the app ? @dlevequeIT

**Comment by greyson-signal** [comment]
@dlevequeIT If you reinstall, how far do you get into registration before the app crashes?

**Comment by dlevequeIT** [comment]
If I reinstall application, application crash on the first registration screen. Some time it crash too quickly than I can't saw any screen. I tried to give all permissions required by the application but it's the same
