### ISSUE TITLE
Signal crashes on tapping a message (for some seconds)

### ISSUE THREAD

**Issue by fuufdiji** [signalapp/Signal-Android#11675]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to get details on a message (reactions, send status, copy, forward) by tapping on the message for 2~3 seconds, the app crashes.

### Steps to reproduce
- Open any conversation (one on one or group chat doesn't matter)
- press on a message for 2~3 seconds

**Actual result:** Signal crashes (popup with "Signal angehalten - OK" in the German version)
**Expected result:** A pop-up bar at the top of the screen allowing to react, get more info in a new screen, copy, or forward the message.

### Device info

**Device:** Samsung Galaxy S3 Neo
**Android version:** 4.4.2
**Signal version:** 5.24.14

### Link to debug log

https://debuglogs.org/8b61d5234e87e9e0a540898d341614e164d65897c3d645ca1f1eaa8ee244c25d

**Comment by fuufdiji** [comment]
Unexpectedly, I can access the menu on deleted messages. At least with v5.24.17 (didn't try with prior version). Otherwise, the behaviour is the same with the new version.

**Comment by antgeth** [comment]
also having this issue, on android 4.4. can attach log if that would help.

**Comment by fuufdiji** [comment]
As of v5.26.11, I realised this issue only affects Signal messages, not regular, unencrypted text messages (SMS in German).
I don't know if this was the case with prior versions.

Is there any more diagnostics/help I can provide to get this fixed?

**Comment by antgeth** [comment]
this is still occurring on 5.28.10

**Comment by alex-signal** [comment]
Hold tight! We have incoming updates to the long-press experience in the conversation that *should* resolve this issue.

**Comment by clauz9** [comment]
This is fixed right @fuufdiji ? can you close the issue if it has been fixed ?

**Comment by gnrfzui** [comment]
lost account to my old account @fuufdiji , then I had some trouble with the new account. By now my reply (two posts above) should be visible, right?

So, no, the issue persists. (or a related issue; I can't really tell.)

**Comment by cody-signal** [comment]
Looks like it's kitkat related, we'll see what we can do. Thanks for sticking with us.

**Comment by gnrfzui** [comment]
works again as of 5.34.10.

Feel free to close the issue. (Cannot close it myself due to different account.)
