### ISSUE TITLE
SMS and Call not working for verificationCode in Iran

### ISSUE THREAD

**Issue by arminghm** [signalapp/Signal-Android#11679]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I don't receive verificationCode, both SMS and CALL not working.

### Steps to reproduce
- select country as Iran
- enter you number
- click next to receive verification code

**Actual result:** Don't receive verificationCode
**Expected result:** Receive verificationCode

### Device info

**Device:** Moto g 5G plus
**Android version:** 11
**Signal version:** 5.24.14

**Comment by UserX404** [comment]
Hello
Iran has blocked Signal.
Please close this issue and use the [forum](https://community.signalusers.org/search?q=iran) for discussion and solution.

**Comment by arminghm** [comment]
I confirm that I can receive verificationCode via SMS now. 👍
