### ISSUE TITLE
Short messages displayed in multiple lines

### ISSUE THREAD

**Issue by cstaykov** [signalapp/Signal-Android#11688]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The messages I see on my android device are wrapped in odd and inconsistent ways. See screenshots.

### Steps to reproduce
- Continuously send/receive messages

**Actual result:**  

See screenshot, where my friend (on iOS) sent me "Exactly:))" and my Android Signal app broke that down into 2 lines on the display.  

See the next screenshot where my friend sent me multiple messages, and my app decided to display a short message, "still a cutie though", on multiple lines.

**Expected result:**  Those messages should be displayed on one line like on iOS.

### Screenshots

**Example 1**

Android
![AND1](https://user-images.githubusercontent.com/44845137/137373814-c0566aa5-c21c-42c4-aa95-e99bfd762baf.jpg)

iOS
![IOS1](https://user-images.githubusercontent.com/44845137/137373822-899b1031-acb1-4636-9574-5078ac856606.jpg)

**Example 2**

Android
![AND2](https://user-images.githubusercontent.com/44845137/137373819-98010993-745d-42ff-bb73-955597937b6e.jpg)

iOS
![iOS2](https://user-images.githubusercontent.com/44845137/137373824-7e15272f-edae-41bc-b49f-1d9da5f389c4.jpg)

### Device info

**Device:** Samsung S20 (Model SM-G981W)
**Android version:** Android 11 and One UI version 3.1
**Signal version:** 5.24.14

**Comment by cstaykov** [comment]
Happens every day at least once. Here's another example (screenshot taken on the iPhone, with the embedded screenshot being from the Android in question):

![IMG_0FB93E58A0A1-1](https://user-images.githubusercontent.com/44845137/137540180-52714340-3d94-4472-9832-010caacda87a.jpeg)

**Comment by not-a-feature** [comment]
This also happens when sending from a android device.
![Screenshot_20211030-125945-741](https://user-images.githubusercontent.com/25013642/139530265-443e26c0-c9bb-4881-983c-21e93e755732.png)

Device: Moto G9 Plus
System: Android 11
Signal: 5.24.17

**Comment by mark56034** [comment]
Happens also to me. Maybe this is some screen resolution thing?

Had a phone (Nokia 7 Plus) where this did not happen, changed to a new phone (Fairphone 4) and this situation began to occur. When I receive a message from the Nokia only the Fairphone shows this line break. Sending a message from Fairphone to Nokia 7 Plus shows the problem on the Fairphone but not on the Nokia. Sent and received messages on Nokia look always fine.

When I increase the text size on the Fairphone to something bigger then "normal" the line break in the messages disappears.

**Comment by cody-signal** [comment]
Please update to the latest version or beta. The issue should be fixed.
