### ISSUE TITLE
5.24.15 (beta): Signal doesn't start up, just blank screen

### ISSUE THREAD

**Issue by KommX** [signalapp/Signal-Android#11681]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm on the Beta track. After updating to 5.24.15 today, I can't start up Signal at all anymore.

### Steps to reproduce
- Update to 5.24.15 (beta).
- Open Signal.

**Actual result:** There is only a blank screen, see screenshot below. Reboot didn't help.
**Expected result:** Signal should launch like it did yesterday.

### Screenshots

![Screenshot_20211013-102237](https://user-images.githubusercontent.com/7859245/137097221-ca77fbaa-593b-42cf-840b-f8b32c1343b5.png)

### Device info

**Device:** Google Pixel 3a
**Android version:** 11, last update from October 1st, 2021
**Signal version:** 5.24.15 (beta)

### Link to debug log

Unfortunately, I can't generate a debug log in this case.

**Comment by KommX** [comment]
Although #11680 looks similar, I run another version and the screenshot also looks different, as I don't have any UI elements in my screenshot.

**Comment by Bolpat** [comment]
Same for me, my screen is white though.
Signal version: 5.24.15 (beta)
Device: Sony Xperia Z5 Compact (E5823)
Android version: 7.1.1

**Comment by crnh** [comment]
Experiencing the same issue.

Signal v5.24.15
Device: Motorola One Vision
Android version: 10

**Comment by KommX** [comment]
Good to know. I'll confirm once 5.24.16 is available to me.

**Comment by Sgromm** [comment]
Looking for resolution to same issue here & I know this is Closed but seeing as how the app produces a black screen/won't open After it updated TO 5.24.15 this morning 10/13/21,how do I get from 5.24.15 to 5.24.16 w/no apparent way to update again?

**Comment by greyson-signal** [comment]
> After it updated TO 5.24.15 this morning 10/13/21,how do I get from 5.24.15 to 5.24.16 w/no apparent way to update again?

We make Android releases pretty regularly. Unfortunately the Play Store can take 12+ hours to roll out a release after we click the "publish" button. It's out of our hands at that point. If you want releases faster, I direct regular forum users to get the app via [Firebase App Delivery](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538).

**Comment by vsessink** [comment]
> It's out of our hands at that point.

https://signal.org/android/apk/ still contains the .14 release, that hopefully isn't out of your hands?
