### ISSUE TITLE
5.24.16 (beta): Signal doesn't start up

### ISSUE THREAD

**Issue by skdubg** [signalapp/Signal-Android#11683]
Bug description

I'm on the Beta track. After updating to 5.24.16, I can't start up Signal at all anymore.
Steps to reproduce

    Update to 5.24.16 (beta).
    Open Signal.

Actual result: There is only a blank screen and the app crashes. Reboot didn't help, but shows the initial start screen before crashed again

**Comment by alex-signal** [comment]
Hi! That doesn't sound great. Could you upgrade to .17 and see if the issue persists?
