### ISSUE TITLE
Signal goes blank and does not work.

### ISSUE THREAD

**Issue by princeali311** [signalapp/Signal-Android#11680]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the Android app, I either get a list of my chats that are not up to date (force closing and reopening will load a few messages before it stops updating) or just a blank screen that says signal at the top and has the camera and pencil icons. You cannot at this point do anything. Can't see settings, can't open a chat (and if you can open a chat in the event the app loaded the chats as intially described, you can't see the messages), nothing. If on the off chance you've force closed and quickly got in the o settings, you'll be able to mess around there, but that's it. Oddly enough storage is shown as 0b, which is not true. The phone was working fine and then it just stopped when I went to go check my messages. Linked devices work perfectly fine. 

### Steps to reproduce
- N/A

**Actual result:** Described above.
**Expected result:** The app should load and let me see my messages.

### Screenshots
![Screenshot_20211012-231830](https://user-images.githubusercontent.com/62471390/137061408-931f810f-777c-4847-bfbd-aff0c7e33632.png)

### Device info

**Device:** Pixel 5
**Android version:**11 (RQ3A.210905.001) 
**Signal version:** 5.24.14

### Link to debug log
https://debuglogs.org/4ac7002b88aad338e5bf8f31f6cbcfe39d9da8b79e1052fe9b431c0561b174fc

**Comment by princeali311** [comment]
Edit: installing the oven over update did nothing. 

Android 11 RQ3A.211001.001

**Comment by kelseymok** [comment]
I've also had the same issue as @Totorrr and @princeali311. I also had entered my pin just before the issues started. Restarting the phone, force stopping, clearing cache, and the language workaround did not resolve the issue (back to the normal state) for me.

**Comment by Krzmbrzl** [comment]
This did happen to me yesterday. I don't know if the debug logs of today still contain usable information but here they are anyway: https://debuglogs.org/f1dc2fe11ea9beb81b1138cad4ea5d458673cd3bab3f65b1961796a55d2f9edd

For me the situation was as follows:
I tried sending a GIF which displayed a loading animation at which Signal froze. I force-stopped it and afterwards I encountered the situation described here.
Note that I had the Signal Desktop app opened in parallel.

Restarting signal and/or the phone and cleaning the cache did not resolve the issue. I finally turned my computer off and waited a bit. Then I restarted my phone again (I might have also cleared the cache again) and Signal was back working.

**Comment by ScatteredRay** [comment]
I’m getting the same issue…

It’s working on my paired iPad.

Additionally, it seems to have happened maybe after switching Sim #2 in my phone out, and back.

How do I get debug logs to post them?

**Comment by Krzmbrzl** [comment]
@ScatteredRay go to settings and then Help > Debug logs. Then submit and paste the generated link here

**Comment by Krzmbrzl** [comment]
Well given that nobody reported the bug to be fixed, I would assume it is indeed still relevant.

**Comment by Krzmbrzl** [comment]
> Well given that nobody reported the bug to be fixed, I would assume it is indeed still relevant.

**Comment by lead0r** [comment]
> I think this was resolved a while back. Please comment if you experience the issue again.

I just experienced it for the first time. I'm on 6.39.3

**Comment by lead0r** [comment]
> > I think this was resolved a while back. Please comment if you experience the issue again.
> 
> I just experienced it for the first time. I'm on 6.39.3

Aaaand update solved it

**Comment by obar** [comment]
I seem to have the same issue and I'm on the latest version of the app, having just transferred my account successfully to this phone. I can view the message contents by opening a conversation I know has content, and the badge number in the bottom left drops accordingly when that message is read. No filters or folders are in use.

![Image](https://github.com/user-attachments/assets/3bb8f6f2-d865-45a1-9953-be0871386369)

**Comment by obar** [comment]
Thanks Michelle, this is the work around I needed!

**Comment by yarninspacetime** [comment]
The same happens here with 7.70.1 and the workaround with adding folders doesn't do the trick. It happened after updating to 7.70.1. Chats still appear on my laptop, but not on my phone.

Edit: Somehow stuff is back (clearing cache, forcing hard stop, rebooting phone..) , but no new messages appear or can be sent from my phone since the update.

Edit2: After not using my phone for a bit, everything seems gone once more. How is this possible? Chat visibility vs screen activity? Really weird.
