### ISSUE TITLE
Archived Chats are not valid share targets

### ISSUE THREAD

**Issue by newhinton** [signalapp/Signal-Android#11682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing data, the signal app 'publishes' chats to the share dialog. The share dialog should provide the most recently used chats. However, it often shows irrelevant chats, but more importantly, it shows chats that are archived and therefore not a valid target for sharing. 

### Steps to reproduce
- I am not quite sure how to reproduce it besides the obvious steps of archiving a chat and then trying to share an image. The share dialog is often just hit and miss.

**Actual result:** Archived chat is proposed as target
**Expected result:** Only the last X used chats should show up

### Device info

**Device:** Samsung S9
**Android version:** 11 (LineageOS )
**Signal version:** 5.24.14

**Comment by alex-signal** [comment]
Hi! By Share Dialog, are you referring to the Android system share sheet?

**Comment by newhinton** [comment]
This is still relevant. 

@alex-signal 
it seems that https://github.com/signalapp/Signal-Android/blob/e96ff92029306ab8645ab2b6097ad84fca444508/app/src/main/java/org/thoughtcrime/securesms/util/ConversationUtil.java#L88

is not called regularly. There is a ConversationShortcutUpdateJob, but that one only adds Shortcuts, but not removes them. This could probably be fixed by adding the clearAllShortcuts() call in the run() method.

The job is in the onResume for the ConversationParentFragment, but that may not be enough. It certainly misses the cleanup though.

**Comment by newhinton** [comment]
Please see above comment, this is not stale.

**Comment by alex-signal** [comment]
The call to `setDynamicShortcuts` will replace all existing dynamic shortcuts, as per it's documentation. We do set the LongLived flag, so it's possible what we want to do here is selectively delete dynamic shortcuts that have become archived.

**Comment by newhinton** [comment]
I think i wont be able to test it before this hits the official release, but if you like i can give feedback then&close it then.

**Comment by newhinton** [comment]
It seems to be working just fine now!
