### ISSUE TITLE
Images take a long time to send on a good connection

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#11684]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images, Stickers or Link Preview Images sometimes take a long time to send on a good connection (one minute or more). Most of the time it only takes a few seconds.

### Steps to reproduce
- Send Image, Sticker or Link Preview Image
- wait

**Actual result:** It takes a long time
**Expected result:** It should not take that long

### Device info
**Device:** Asus Zenfone 6
**Android version:** 11
**Signal version:** 5.24.14

### Link to debug log
https://debuglogs.org/2ce8d7a927cb8761c0dfdf9fc5cbcdbcada03ac0c6bc60ac5e9e9cca647f18af

Sticker that took long: 23:59:39 MESZ
Link Preview image that took long: 23:21:33 MESZ

**Comment by Nisc3d** [comment]
New Debug Log with an image that took too long. This time over a minute for a picture with 22,7kB.
This issue is happening on different phones and different wifi connections. 
Link: https://debuglogs.org/13a995b9a344577cc6f848bdab402368d761634546dad8a203dc021749798dad
Image ID: 1637697617384

**Comment by Nisc3d** [comment]
Another one on a Asus Zenfone 8.
Image took over a minute to upload. It should only take seconds on this good internet connection.
https://debuglogs.org/3e3b87deca7ac5e0a3359dd6a56b58be7a84b229b15c36f53f6b5435a2db7fbf
Image ID: 1637842231765

**Comment by Nisc3d** [comment]
I think this might be something with specific german isps. If someone can confirm that they have the same Problem sometimes with Telekom or 1&1 this would be helpful.

**Comment by Nisc3d** [comment]
Can someone please look at this issue or give me tips how I can debug it?
New Debug log: https://debuglogs.org/c415d32538e1d24747af22566dbdadea4012916b9a308df635b7517fd5e46fb5

**Comment by cody-signal** [comment]
Hi there, it looks like the part that's taking a long time isn't the upload but the request to get metadata used to perform the upload. Looking at your logs, it seems like some upload jobs are taking 60s just to get that metadata, and then no time at all to send the upload. I don't know why that is happening.

Are you able to reliably reproduce it or is it just random?

**Comment by Nisc3d** [comment]
On my phone (Asus Zenfone) it happens very rarely. Like once a month. On the Motorola phone from my friend it happens 90% of the time for media uploads. If I can help more with additional debug logs let me know. This issue is one of the more annoying ones and I will help with everything that I can do if you can get it resolved.

**Comment by cody-signal** [comment]
Do you know what kind of network your friend is using it from? Is they on a VPN or other extra networking kit?

If not on a VPN, could they try one, or try the built in TLS proxy. The part that's taking so long is after we've requested the metadata and waiting for it to come back so it's hard to know what could be faltering.

**Comment by Nisc3d** [comment]
So, just by coincidence it happened to me again today.
https://debuglogs.org/d86cff4ab46410e2daa70f712faa69f136aa191408ccd10f7ec9c5689c8a7499
Message ID:
1643847843414 (I think it was this one. If not it was the one before or 2 before).

I was on Wifi with a good connection (Router in the same room) and good speeds.
After this I tried with a VPN and without a VPN again but I couldn't reproduce it. The photo was taken with the in-app Camera and also cropped.

I will test it also again with my friend but it takes some time, because we are not living in the same are.

**Comment by cody-signal** [comment]
Thanks for the extra info. I added some logging to the 5.31.x beta that just dropped. If you could install and run that, it would be helpful. It added some benchmark data around the part that's been slow for you so I can figure out exactly which of 3-4 things is actually taking so long.

**Comment by Nisc3d** [comment]
Thank you for your work. We are currently testing it and I will post a debug log when we can get a good result.

**Comment by Nisc3d** [comment]
Another Update: It just isn't happening right now. We will keep an eye on this and I will post a debug log, when it's happening again.

**Comment by cody-signal** [comment]
Can you post the debuglog from it happening? Should still have the timing data in it.

**Comment by Nisc3d** [comment]
Good News:  It happened. 
https://debuglogs.org/android/5.32.4/bd01b00267172aa95c27bd95287be280253227f3edc18a8ae6391eccb578b48c

**Comment by greyson-signal** [comment]
It looks like a lock was being held on decryption that took a good 15 seconds to get a hold of. Something is up there.

**Comment by cody-signal** [comment]
Do you know if this is happening in both 1:1 conversation and groups or just groups?

**Comment by Nisc3d** [comment]
Happened again:
https://debuglogs.org/android/5.32.7/19f27c4a0e883e87abb1171c5409a9c78b08304241142a1ff6004e0b4b3d0f1a
Message: 1645226536194 was slow to upload.
Also 1645226320396 was slow to download.

**Comment by Nisc3d** [comment]
Another Log: https://debuglogs.org/android/5.32.10/d268ec249401f3ccb719356dd62468f064576c448b9c80955db0e75ae2bf3e72
The last image took long to send.

**Comment by greyson-signal** [comment]
For future reference:

https://debuglogs.org/android/5.32.7/19f27c4a0e883e87abb1171c5409a9c78b08304241142a1ff6004e0b4b3d0f1a
`JOB::0f3848fd-4473-47d8-8f5b-0cee11b8a492` was a ResumableUploadSpecJob that took 60 seconds to run. The AttachmentUploadJob it was blocking (`JOB::8ffc6411-9fde-4f8d-9023-a2ba272ea45b`)  finished soon after.

https://debuglogs.org/android/5.32.10/d268ec249401f3ccb719356dd62468f064576c448b9c80955db0e75ae2bf3e72
`JOB::5041a4c7-359d-419e-94c3-56bb3feba5b1` was a ResumableUploadSpecJob that took 60 seconds to run. The AttachmentUploadJob it was blocking (`JOB::01d7b82f-c61c-4623-a289-12dfa4fb6217`)  finished soon after.

**Comment by Nisc3d** [comment]
Another example: https://debuglogs.org/android/5.32.14/8fa09cf7aa991de63eb2b945a935523fa8a767e2d7a5dbebde28b56b23acd588
Message ID: 1645964625181

I don't know if you have enough already.

**Comment by cody-signal** [comment]
Thanks, we have another logging change in the next beta release that'll be out soon. I'll let you know here when it drops and then a log after that would be helpful. We're still a little unsure why this is happening and where exactly the issue is, however, we hope the additional logging will show us.

**Comment by cody-signal** [comment]
@Nisc3d if you could submit a new debuglog using the latest beta, that would have the additional metrics for us to see where time is being spent.

**Comment by Nisc3d** [comment]
Okay, I will try to capture one.

**Comment by Nisc3d** [comment]
Here is a log: https://debuglogs.org/android/5.33.2/9d7e8ebaa0248bad1d7a2823c3de05351fe872e56927b6da3c55ed7587cf3f10

**Comment by cody-signal** [comment]
Thanks for the logs, I finally know where the time is being spent. It looks like it's taking 3 attempts to connect successfully. The first two take 30s each, as that's the timeout, and then finally the 3rd one connects and completes.

Sadly, there's not much we can do to make this faster as it's randomly up to the network conditions on if it'll work or not. The one thing we might do is dial back the timeout to 10s so it'll fail faster (all 3 attempts would take the same as currently the 1st one).

```
[0.000 callStart]
[0.003 dnsStart]
[0.047 dnsEnd]
[0.047 connectStart]
[30.077 connectFailed]
[30.078 connectStart]
[60.107 connectFailed]
[60.107 connectStart]
[60.159 secureConnectStart]
[60.311 secureConnectEnd]
[60.312 connectEnd]
[60.312 connectionAcquired]
[60.312 requestHeadersStart]
[60.312 requestHeadersEnd]
[60.312 requestBodyStart]
[60.312 requestBodyEnd]
[60.312 responseHeadersStart]
[60.507 responseHeadersEnd]
[60.507 responseBodyStart]
[60.507 responseBodyEnd]
[60.507 connectionReleased]
[60.508 callEnd] 
```

**Comment by Nisc3d** [comment]
I really appreciate the investigation into this issue. Sadly that confirms my worries, that it is a network issue on an otherwise fast connection. Also this happens on two different ISPs and two different city's in Germany with different routers. The ISPs are Deutsche Telekom and 1&1.

I have two questions: Can you also check and lower your timeout times for downloads a bit?
I also have the issue #11059 open which may be related. 

And can I use some network tool to troubleshoot this to report it to my ISP when it happens? If yes, can you recommend me one tool that checks the connection like the Signal App does? And the URL where I can point it to.

**Comment by Nisc3d** [comment]
Yes, we can close the issue. Thanks for helping. If you have something to add in the future feel free to comment here again.

**Comment by Nisc3d** [comment]
@cody-signal Sorry I have another thing to add, which might be related. The last message (text, not a picture) took long to send. Is this the same problem or another problem? https://debuglogs.org/android/5.33.3/3bbd66cb06d3c5c07a5873fde8eb0c15f4038d5db5ecf6f3ab98ed83cae7c243

**Comment by Nisc3d** [comment]
Another example: https://debuglogs.org/android/5.34.8/0979c55a1516842d6157623261082c78bfedfe3b2886dbcf543d4e0439c672a3
