### ISSUE TITLE
Visual Bug: Signal renders a single white pixel directly above the keyboard.

### ISSUE THREAD

**Issue by torgeros** [signalapp/Signal-Android#11695]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the keyboard is open, there are two white pixels in the bottom left corner of the chat window, directly above the _Signal message_ field. The screenshot with the keyboard shows it.

### Steps to reproduce
This is consistent across all chats, **except the one where I have set a custom chat color** for some reason.

I open the chat, tap in the message field to open up my keyboard, and then the white pixel appears. When i use the back-gesture, the keyboard closes (as expected) and the white pixels disappear.

Closing and re-opening the app does not change anything, I have also tried restarting the device.

### Screenshots

<img src="https://user-images.githubusercontent.com/67151313/137799614-60644ce2-f757-442a-bde1-bfe224d6b496.jpg" width=500 alt="screenshot with keyboard">

<img src="https://user-images.githubusercontent.com/67151313/137799372-2a64e0ae-6194-410c-be3a-4b65bf99ae29.jpg" width=500 alt="screenshot without keyboard">

### Device info

**Device:** Oneplus 6T (A6013)
**Android version:** Android 11, OxygenOS 11.1.1.1
**Signal version:** 5.24.14

### Link to debug log

https://debuglogs.org/3d476ed8a9f72c099eda11c988338319c2267704471200b8627dd2c1ccf5e2b3

**Comment by AlertSubject** [comment]
I've reported this on the forums two weeks ago but received no reaction
Obviously not the worst bug but still hoping for a fix

**Comment by torgeros** [comment]
The bug is gone for me. @AlertSubject can you confirm?

**Comment by AlertSubject** [comment]
> The bug is gone for me. @AlertSubject can you confirm?

Yes, seems to be fixed
