### ISSUE TITLE
Message history auto clean-up problem

### ISSUE THREAD

**Issue by George-TL** [signalapp/Signal-Android#11698]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
----------------------------------------
### Bug description
After setting:
Signal -> Settings -> Data and storage -> Manage storage -> Keep messages to value "30 days"
Signal only cleans old messages for active chats.
Active chat is chat which I'm using to communicate by sending messages.
Other chats (idle ones) are not maintained by automatic clean-up.

### Steps to reproduce
Set Signal as described above.
Wait few days/weeks.
Open any inactive conversation.

**Actual result:** Old messages are still there.
**Expected result:** Signal should invoke auto purge task once per day.

Re-setting clean-up period for the same value will trigger mass purge for all conversations.

### Device info

**Device:** HTC M8
**Android version:** 10 (Lineage 17.1)
**Signal version:** 5.24.17

**Comment by clauz9** [comment]
I've reproduced the issue by moving the phone's date forward, Greyson you have a log sent on the forum.

**Comment by George-TL** [comment]
> out of curiosity, @George-TL is your phones clock set to automatically sync ? or is it on manual ?

automatic

**Comment by George-TL** [comment]
Tested today - problem still present.

**Comment by 0x022b** [comment]
@greyson-signal do you still need debug logs about this issue? If you do, I can send you one.

**Comment by cody-signal** [comment]
To clarify, the issue is that inactive chats don't get trimmed but active ones do? I believe this is the expected (but likely incorrect) behavior since we trim threads on updates. Can you confirm this is in fact what you're experiencing?

**Comment by George-TL** [comment]
Signal for android v6.9.2 - looks like problem is solved and old messages are removed for inactive chats.
