### ISSUE TITLE
Messages keep unarchiving themselves without any new correspondence

### ISSUE THREAD

**Issue by kiplingw** [signalapp/Signal-Android#11690]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Previously archived messages sometimes unarchive themselves, without any new message activity in the given thread. Note that this is not the same as #11587 which dealt with messages unarchiving themselves on receipt of new messages.

This appears to occur regardless of whether I am using Signal from another device or not, but seems to be easily reproduced when I have Signal Desktop installed on multiple machines.

### Steps to reproduce
- Archive all of your messages with Signal Desktop on machine X;
- Open Signal Desktop on machine Y;

**Actual result:** Some (but not all) previously archived messages unarchive themselves.
**Expected result:** I expected archived threads to not resurrect themselves without additional correspondence.

### Device info
I am using Signal Desktop version 5.20.0 on both machines. I keep both machines' installations up-to-date.

**Comment by Genis-Sage** [comment]
hey @kiplingw 
does the unarchiving also happen on your phone, or just on your desktop computers?
if it's only on your desktop computers, it would be better to open an issue in the [Desktop Repo](https://github.com/signalapp/Signal-Desktop/issues)

**Comment by kiplingw** [comment]
Come to think of it, now that I test again, it only seems to happen on the desktop client. I have opened an [issue](https://github.com/signalapp/Signal-Desktop/issues/5587) in the desktop repository.
