### ISSUE TITLE
Message sending fails

### ISSUE THREAD

**Issue by freiheitsnetz** [signalapp/Signal-Android#11719]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In one Signal group I can not send messages. I send a message and it states that sending failed. It's just that one group. In other groups and direct messages I do not have this issue. It does not matter whether I am on WiFi or mobile data. Other people in that same group can send messages without any issue. I am admin in that group. I created that group several months ago but never sent any message within that group. So, I can not say whether it just occurred with the current Signal version or would have never worked.

### Steps to reproduce
- create message and tap send
- it tries to send but fails (red text that it failed)
- try again sending fails as well
- reboot does not help

**Actual result:** 
- sending fails

**Expected result:** 
- should send normally

### Device info
**Device:** Google Pixel 3a
**Android version:** 12 (SP1A.210812.015)
**Signal version:** 5.25.7

### Link to debug log
https://debuglogs.org/dfd5ee01d63727876ac853422a05614636b168bc3519ff1a884f64f76c9a4a39

**Comment by zamadatix** [comment]
I've run into the exact same issue. I tried forwarding images from another chat to the group chat and it hung on the first dotted circle sending. I tried deleting for everyone the failed message, being kicked and readded to the group, and removing myself and deleting the conversation to be readded fresh. In all cases I can receive messages from the group but send fails instantly. All other chats and groups work fine.

**Comment by greyson-signal** [comment]
@freiheitsnetz If you tap the failed message, what happens? If you long-press the message and tap the 'i' icon in the toolbar to go to the message details screen, what error do you see? 

The logs indicate that the send failed due to a safety number change, which is normally corrected via a prompt.

@zamadatix Can you post a log so I can see if you have the same issue? Thanks!

**Comment by freiheitsnetz** [comment]
Here is the note I get when I tap on a failed message.
<img src="https://user-images.githubusercontent.com/7985946/140048778-eb6e1340-1d87-4f84-8d35-6ee476964b25.png" width="300" />
And this one when long-pressing on 'i' icon.
<img src="https://user-images.githubusercontent.com/7985946/140049353-be64cf26-4ea2-44bd-92ed-ec36940581d9.png" width="300" />

In both cases, a resend does not help.

**Comment by freiheitsnetz** [comment]
Solved for me --> kind of workaround.
@greyson-signal your hint to the safety number change helped.

I texted all participants from that group directly and for one participant I received the prompt that the safety number has changed and whether I want to send the message despite that change. I confirmed to send the message nevertheless and after that I was able to send messages within the group as well.

I other words: The safety number change for one participant was holding back the message in the group, but within the group I got no prompt. I only got that prompt in a direct communication.

Nevertheless, I think this solution seems to be more like a workaround. In larger groups it would not be easily possible to text all group members to find out whose safety number change is holding back the message.
Thus, I would leave it to the developers whether they consider this issue as solved and I should close it or whether it should stay open.

**Comment by jeffm24** [comment]
Just wanted to add that I was having the same issue and the workaround @freiheitsnetz suggested was the solution. I had a new group chat going with two iPhone users and two Android users (myself included). One of the iPhone users (A) was newly signed up and was in the chat, but we couldn't see any of his messages. After he was added, both myself and the other Android user became unable to send any messages (the loading spinner would just go on forever). Weirdly, the other iPhone user (B) was still able to send messages in this situation (though he still couldn't see B's messages), so it may be some sort of difference in the clients there. I tested the above suggestion and found that I was unable to send B a message individually either (same infinite spinner), so I started a new chat with only the other people and everything was working again. I mentioned it to him and he reset his account, causing his security number to change in both the private and group chat. After that, everyone was able to see his messages and send messages without issue.

**Comment by arikb** [comment]
Okay, I have the same or a variant of this problem.

In the BSFS group (which I haven't participated in for a long while) I am not able to send messages anymore from the Android app. I did a few tests:

- I cannot send a regular message, I receive a failure message
- I can send a reaction to someone else's message
- I can promote and demote another member to an admin
- On the desktop I am able to send messages to the group as usual
- On the desktop I can see the messages sent by the Android device (i.e. they are synchronised to the desktop)
- Other members apparently cannot see those messages

I'm running 5.27.2 and my debug logs taken immediately after a failed message: https://debuglogs.org/f70cebc34fafc148f0c0a9c6fc20f88dabdd99871ca63dbae4c488e4cd4436f4

Images from my Android device and then from the desktop:

![image](https://user-images.githubusercontent.com/1229613/142781684-057c020b-8e5c-4f41-b55f-5ac85c418b5e.png)
![image](https://user-images.githubusercontent.com/1229613/142781697-4e8a0e9e-8221-482a-8076-639fe5d36b23.png)

**Comment by Le1b1** [comment]
Same problem here with one group:
https://debuglogs.org/2e62b2235615252fafe95c4f470786916f907a805e4c3aca117b693ad6aa680e

**Comment by Hanl0n** [comment]
I have the same problem.

I am not able to send messages from the Android app in the BSFS group

    I cannot send messages, I receive a failure indicating a network connection issue
    I can send a reaction to someone else's message
    On the desktop I am able to send messages to the group as usual
    On the desktop I can see the messages sent by the Android device (i.e. they are synchronised to the desktop)
    Other members cannot see those messages

I tried to leave and re-enter the group, I unlinked all devices an re-linked one.

desktop:
https://debuglogs.org/e5c50132ee8cf354bcd9c3464ccd5488021d711b76de95418005f3b6fdcf918b.gz

Android:
https://debuglogs.org/1fa14fbc8e01e533450e96c1d2b9df391a41222bbcff6ed9945c776bde48993a

**Comment by Hanl0n** [comment]
Short update: It's been about a month and this is not self-solving.

I didn't try any workarounds. At the end this app should work without knowledge about airplane mode.  ;-)

https://debuglogs.org/d737da91338f524a5d27f44c2b6bb92b0c980b50adfcb7ed5e3dee0d802dca43

**Comment by greyson-signal** [comment]
Please try again on 5.29.4. It's likely that 64e4bcf46aec49c1b34357c8d9ad01e56705a2f3 fixes the issue.

**Comment by Hanl0n** [comment]
This seams to be solved in 5.29.4
Thanks

**Comment by foolishgrunt** [comment]
I recently encountered a (apparently) identical issue on version 6.43.2. I an an admin of one group, and for this group only, I received repeated "Send failed" errors any time I tried to send a message, while everyone else was able to message without issue.

After perusing this thread, I decided to try removing three inactive members from the chat. After doing so, I am now able to send messages without issue.

Let me know if there is any additional information I can share to see if this is a recurrence of the same issue.

**Comment by alex-signal** [comment]
@foolishgrunt Please open a new issue and include a debug log.
