### ISSUE TITLE
[sending video attachment] Audio plays at like 0.25x speed

### ISSUE THREAD

**Issue by MomentofClarity** [signalapp/Signal-Android#11712]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
 
 - - - - - - - - - -

 #### Bug description

Audio becomes slowed down a lot when uploading video as an attachment. 

 #### Steps to reproduce

- Download YouTube video (mp4) via NewPipe
- Use ffmpeg command (on Ubuntu if that's relevant) to cut a portion of it (ffmpeg -i sbw.mp4 -ss 00:00:05.00 -t 00:00:40.00 -c copy sbw2.mp4)
- Send the video from computer to phone (it looks normal when played)
- Upload video to signal as an attachment

**Actual result:** The audio sounds like a chopped and screwed remix (either in app or after downloading the video from app). 

**Expected result:** The audio resembles the original

 #### Screenshots ((((NWFW warning kind of it's a music video and youtube-appropriate but on the obnoxious side)))

[screen recording playing on Signal via Streamable](https://streamable.com/9av8p0)

 #### Device info

 **Device:** Galaxy S21

 **Android version:** 11

 **Signal version:** 5.25.4

 #### App state

 Signal messages and calls registered, SMS disabled, passphrase enabled

 #### Link to debug log

 https://debuglogs.org/75368150252fd61eed64ff3cb4f9b1fc50da2c9d7141b1c8d77307189da57eda

 #### Other info

 I have a (semi-NSFW as before) [direct link](http://149.28.41.64/sbw2.mp4) to the source video if it helps. For some reason it starts at 0:04 seconds and doesn't have a 0:00? It plays perfectly fine on both my computer and phone in various apps, but when I click that link on a browser it lags for 4 seconds but then plays and sounds normal.  On Signal it also has the 4 second lag, but if you download the video from signal it plays immediately (but audio still messed up)

 I am not overly concerned about this just posting here in case it helps solve other video processing issues.

**Comment by ssalabura** [comment]
I've just got the same bug, so this is still relevant. Video (attached below) being sent from an Android device has audio slowed down to about 0.25x original speed. Issue doesn't exist on a desktop version of Signal.

**Device**: Samsung Galaxy A52s 5G
**Android version**: 12
**Signal version**: 5.45.6
**Link to debug log**:
https://debuglogs.org/android/5.45.6/d38dffa9768d3ff9d836bb73721f99ed487d68b31401e20e5f7c0f62507b6d6
**Link to video being sent**:
https://user-images.githubusercontent.com/56295611/185209980-b56ae22d-ac52-450a-b076-e9b52934bf37.mp4

**Comment by Zahrun** [comment]
Not stale

**Comment by Chromatros** [comment]
Not stale
