### ISSUE TITLE
SERVICE_NOT_AVAILABLE in FcmUtil when "Cloud Messaging" is disabled via MicroG

### ISSUE THREAD

**Issue by Doomsdayrs** [signalapp/Signal-Android#11724]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When using MicroG, Signal will attempt to get a token from MicroG. 

If MicroG has "Cloud Messaging" disabled, or if "Cloud Messaging" is disabled for the application, then an IOException will be thrown at line 27 of `FcmUtil.java` with the description of "SERVICE_NOT_AVAILABLE". 

### Steps to reproduce
- Use phone with MicroG
- Disable "Cloud Messaging" globally or for the app only.
- Open up Signal

**Actual result:**
No notifications due to `FcmUtil.java` constantly causing errors.

**Expected result:**
`FcmUtil.java` fails to get token, I assume Signal constantly retries to the token without properly handling.
### Device info
**Android version:** 11
**Signal version:** 5.25.7

### Correction
Patch `FcmUtil.java` to wrap the IOException
[signal-fcm-microg.txt](https://github.com/signalapp/Signal-Android/files/7455728/signal-fcm-microg.txt)

**Comment by greyson-signal** [comment]
Hi there, we don't provide support for MicroG stuff. You can see if anyone can provide any assistance on the [forum](https://community.signalusers.org/). Thanks!

(Also, thank you for the suggested patch, but the IOException would never be thrown, so I don't see it doing much)

**Comment by Doomsdayrs** [comment]
Contrary to inteli sense, IOException is thrown with MicroG. 

This doesn't do anything to non-microG users and only improves the usability of the app for more users who have more options
