### ISSUE TITLE
Camera closes completely after clicking on "back" / arrow back

### ISSUE THREAD

**Issue by FreddyRice** [signalapp/Signal-Android#11729]
Currently the following scenario happens:
1. Open a Chat
2. Open Camera
3. Take a Picture
4. Click "Back" (in my case on bottom navigation from android phone)
5. Camera shortly shown and then it automatically closes and an error message is shown:
(de) "Ein oder mehrere Elemente waren ungültig."
(en)? "One or more elements are invalid" 

Expected Result:
Keeping camera open to take another picture

I also checked with a friend and he faces the same bug.

Version: 5.25.7
Huawei P20 Lite with Android 9

Best regards,
FR

**Comment by Ynnck123** [comment]
I am also experiencing this issue on my One Plus 7 Pro with Android 11.

App Version: 5.25.7
