### ISSUE TITLE
Signal Android Breaks up Audio & Video on Wifi only - consistent Issue

### ISSUE THREAD

**Issue by gab81** [signalapp/Signal-Android#11723]
**X** I have searched open and closed issues for duplicates
**X** I am submitting a bug report for existing functionality that does not work as intended
**X** I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
**X** This isn't a feature request or a discussion topic

**Bug description**

Signal Android breaks audio and video while on wifi on Samsung S8

**This has been tested extensively on 2 Samsung S8.**

Both phones running latest version: Signal 5.25.7 (now updated to 5.25.8) **Now 5.28.10**

**Steps to Reproduce**

Do an audio or video call with any of our 2 Samung S8.

1. When phone is on mobile network only, call and video are perfect
2. _When phone has wireless switched on, audio breaks repeatedly, whether you are 10 cm or 10 meters from the router it's occurring_ - Calls saver is off, set to "never".
3. _Tested with both 2.4ghz and 5Ghz signals from router, tested various channels on both spectrums, tested also different channel widths, disabled 5ghs as crowded 2.4 ghz channel potential suspect but happened again._
4. Other voIP apps such as FB Messenger and Telegram never break up audio
5. _Tested to disable mobile network while on wifi (in order to avoid phone jumping connections), still breaking up_
6. Tested usb-c adaptor to Samsung S8 and then plug Ethernet straight to router, call is perfect
7. Tested same wireless network on Laptop with  Signal Desktop, call is perfect
8. _Tested to move router away from current location, not near tv and it still breaks up_

**Device Info**

Samsung S8
Android version: 9

The same S8 on a different connection (on a previous signal release), it never broke up so often, might have happened on a spot basis but not on regular consistent basis like now, therefore there's an issue

**Links to Debug Logs**

Here are 2 debug logs from our Samsung s8s that experienced the issue

Phone 1 https://debuglogs.org/32520e5ba68d13e2e3e0b34621b1593b848f5196440da9963d13c7d3bbec1c81
Phone 2 https://debuglogs.org/abefdd9b00a360a43d2c5311355d7c9ceb473590bd09683b0de729d92d0e4950

let me know if i can provide further troubleshooting, also provided here https://community.signalusers.org/t/phone-video-calls-jumping-on-android-wifi/38229/17

many thanks,
Gabrio

**Comment by Herohtar** [comment]
You should avoid deleting/ignoring the issue template, but in any case, you'll need to provide a debug log from when the issue was occurring in order for the devs to investigate this at all.

**Comment by gab81** [comment]
Here are 2 debug logs from our samsung s8 that experienced the issue

Phone 1 https://debuglogs.org/32520e5ba68d13e2e3e0b34621b1593b848f5196440da9963d13c7d3bbec1c81

Phone 2 https://debuglogs.org/abefdd9b00a360a43d2c5311355d7c9ceb473590bd09683b0de729d92d0e4950

Also reported via in app contact us menu.

To add this happens every day, every time recently.

Thanks,
Gabrio

**Comment by gab81** [comment]
hello - any response to these logs for these audio issues by chance? many thanks

**Comment by gab81** [comment]
> You should avoid deleting/ignoring the issue template, but in any case, you'll need to provide a debug log from when the issue was occurring in order for the devs to investigate this at all.

I've properly formatted the bug report in the requested format.

**Comment by gab81** [comment]
hello

any chances to have this picked up? just happened again with the newest release of the app as well

thank you

**Comment by gab81** [comment]
hello - i have to bump this one as there are no reactions. Does anyone have similar issues? I cannot really use Signal on my home wifi anymore which sucks. I need to disable the wireless and leave it to my Phone's mobile network.

At this point i don't know if it's the router but buying a new router just for testing this is not something i want to do and it's ridiculous, other wireless things work fine on the phone.

does anyone have the same issues?

I tested this with calling a second phone, one at home (on wireless) and one on mobile network, still cracks. then tested many many times with my phone on home wifi and calling another computer on signal desktop in Italy.

As i explained 1000 times, if i put the ethernet cable on the phone with the usb-c adapter then call is perfectly smooth.

very frustrated with this and good i have a big data package on my phone.

**Comment by gab81** [comment]
> You should avoid deleting/ignoring the issue template, but in any case, you'll need to provide a debug log from when the issue was occurring in order for the devs to investigate this at all.

is it possible to know if anyone ever have been working on this? still happening for me in 2022 now. thanks

**Comment by Tursko** [comment]
> hello - i have to bump this one as there are no reactions. Does anyone have similar issues? I cannot really use Signal on my home wifi anymore which sucks. I need to disable the wireless and leave it to my Phone's mobile network.

Have you tried a different network (like a friends house) or a different router? I feel like this is most likely a home router issue.

**Comment by gab81** [comment]
> > hello - i have to bump this one as there are no reactions. Does anyone have similar issues? I cannot really use Signal on my home wifi anymore which sucks. I need to disable the wireless and leave it to my Phone's mobile network.
> 
> Have you tried a different network (like a friends house) or a different router? I feel like this is most likely a home router issue.

no i haven't but how's possible that Signal is the only one having this issue? Whatsapp, Telegram and Voicecalls over Wifi connect fine-

**Comment by Tursko** [comment]
> > > hello - i have to bump this one as there are no reactions. Does anyone have similar issues? I cannot really use Signal on my home wifi anymore which sucks. I need to disable the wireless and leave it to my Phone's mobile network.
> > 
> > Have you tried a different network (like a friends house) or a different router? I feel like this is most likely a home router issue.
> 
> no i haven't but how's possible that Signal is the only one having this issue? Whatsapp, Telegram and Voicecalls over Wifi connect fine-

Those are different apps, it's entirely possible that it's something to do with your connection. You should definitely try a different network first.

**Comment by gab81** [comment]
How is Signal using the data connection differently? VOIP Data is data....

**Comment by Tursko** [comment]
> How is Signal using the data connection differently? VOIP Data is data....

Could be using more data or something.  It's a basic test though, won't hurt anything.
