### ISSUE TITLE
Crash when filtering users for a new group and you have animations disabled

### ISSUE THREAD

**Issue by henu** [signalapp/Signal-Android#11722]
### Bug description
If you have animations globally disabled in your Android developer settings, then Signal will crash if you try to filter users to your new group chat. Without filtering it works.

### Steps to reproduce
- Go to developer options in your Android device and disable animations (animations are just waste of time, right?)
- Open signal and start creating new group chat
- In "Select members", search some of your contacts by writing their name to text field
- Click a name in the list

**Actual result:** Usually it crashes. Try different names and different number of filtered names if you don't get crash
**Expected result:** The user should be added to the list of members

### Screenshots

![crash_1](https://user-images.githubusercontent.com/3167494/139649513-1a703c37-3999-4f27-9ca9-301d0a8c99d0.png)

![crash_2](https://user-images.githubusercontent.com/3167494/139649527-6dd7312e-c93d-40a6-ba51-d284a9c607dd.png)

### Device info

**Device:** Samsung XCover Pro
**Android version:** 11
**Signal version:** 5.25.7

**Comment by artur-borowiec** [comment]
Confirmed on OnePlus 7T (Android 11)

**Comment by anand956** [comment]
Hey, I want to work on this issue.
Please can you guide me.

**Comment by targezed** [comment]
Confirmed on Asus Zenfone 8, android 11.
![Screenshot_20220122-154356370](https://user-images.githubusercontent.com/24196152/150643264-e6efccd4-b5f1-432b-b5bb-27576a9ee06b.jpg)
