### ISSUE TITLE
Opening High Resolution image will roate 90 degrees CCW

### ISSUE THREAD

**Issue by Calabree** [signalapp/Signal-Android#11732]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening a high resolution image, the image will rotate 90 degrees CCW

### Steps to reproduce
- Open Signal
- Go to chat where someone sends you an image
- opening an image sent to you via High Resolution option

**Actual result:** Image will rotate 90 degrees counter clockwise from preview
**Expected result:** Image should open the same orientation as  it is shown in the preview 

### Screenshots

![View of Photo in preview](https://user-images.githubusercontent.com/42219730/140522751-59495838-7d1d-47f4-9471-54a66a91cfd0.png)

![View of Photo once opened](https://user-images.githubusercontent.com/42219730/140522778-f72176fd-5791-42e9-b98e-ebd0677e18a8.png)
### Device info

**Device:** Google Pixel 6 Pro
**Android version:** 12
**Signal version:** 5.25.8

### Link to debug log

https://debuglogs.org/1caf2fac2aca2c6ec37f98b33eae398629cd0bbd9c8e71e35cb252302c437516

**Comment by clauz9** [comment]
if you are receiving those images from an IPhone your issue is the same as the one here,
https://github.com/signalapp/Signal-Android/issues/11614#issuecomment-949838567

**Comment by greyson-signal** [comment]
I'm confident that this is the same issue as #11614, yeah. Unfortunately we use two different image viewers depending on the image size, and the one that handles big images doesn't respect EXIF data consistently :/
