### ISSUE TITLE
Installed version 5.25.8, but still cannot "Block and Report"

### ISSUE THREAD

**Issue by heini** [signalapp/Signal-Android#11730]
Hi,

after receiving a spam message today, I updated Signal on my Android device to 5.25.8, but I still get no option to "Block and Report", I can only "Block", just as with the previous version.

**Comment by clauz9** [comment]
Currently the option to "Report spam and block" only shows up before you accept a message request, from the person that is spamming you.

[Screenshot 1](https://user-images.githubusercontent.com/77681918/140646104-dbc64c8a-3e85-479a-9e20-57dde95e787b.png) [Screenshot 2](https://user-images.githubusercontent.com/77681918/140646111-ff260a74-ac88-45b1-a01c-49e9afa7023b.png)

Therefore this is not an actual issue with Signal, it's more a feature request, which somebody already has requested on the community forum, here 

 https://community.signalusers.org/t/report-as-spam-option-after-accepting-message-request/37321

feel free to add your input to that feature request, and maybe consider closing this issue.

**Comment by heini** [comment]
I wasn't asked to accept the message.

**Comment by heini** [comment]
Ah, maybe it wasn't a Signal message, but a simple SMS...

**Comment by clauz9** [comment]
>Ah, maybe it wasn't a Signal message, but a simple SMS...

wait, can you please confirm that it was an SMS message, it should be simple if you still have the message from the spammer, it should have an unlocked padlock at the end of it

![Screenshot](https://user-images.githubusercontent.com/77681918/140648760-30d472ca-8d81-4636-9171-210eeccd477b.png)

or you can select the message, by long tapping on it, and selecting the "i" icon from the top bar, thus entering message details, which will give you the following information 

[Screenshot](https://user-images.githubusercontent.com/77681918/140648849-17ca17bf-daaf-4850-99a4-f46e4dd9f2f4.png)

and if you have "SMS" in the  "via" field, than it was for sure an SMS.

**Comment by heini** [comment]
Yes, I can confirm it was an SMS.
