### ISSUE TITLE
Backup frequency 

### ISSUE THREAD

**Issue by L0garithmic** [signalapp/Signal-Android#11737]
Can you please consider allowing the adjustment of backup frequency. It's annoying to backup every day. My message collection is very large (4.5gb+)

Also. Would it be possible to do incrimental? And/or Encrypted Cloud backups?

**Comment by Jledesp** [comment]
Same issue, same request.

**Comment by darrellenns** [comment]
Automatic backups is definitely needed. Most users are simply not going to be frequently going into the settings and initiating a backup manually. Event just an option for an automatic backup interval a retention of the last N backups would be a big improvement.

**Comment by miklish** [comment]
Hopefully the bot can reopen this, as I came to post the same request. I was surprised not to see more backup options in the app (such as backup frequency).

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by Croydon** [comment]
For anyone else finding this issue:

-> https://community.signalusers.org/t/tune-backup-frequency-to-reduce-flash-wear/14040

-> https://community.signalusers.org/t/keep-only-one-backup-file-backup-frequency/14220/10
