### ISSUE TITLE
Group member's message not sent to one of the group members

### ISSUE THREAD

**Issue by Elektropepi** [signalapp/Signal-Android#11738]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am in a group with six members. User B sends a message and everyone including me sees it, so it's fine. A few days later User B sends another message that all members except me receive. I can receive all messages of other members. User B can see my messages. Since then, I do not receive messages of User B in the group anymore.

When I send a PM to User B, they receive it, BUT if he answers, another chat with the same phone mumber is opened. The chat, in which I've sent him a message, has the "Member of Group X" line. The chat, in which he responds, is missing that line. Both chats have the same phone and security number.

If I try to mention him in the group chat with "@", all members except User B are shown.

### Steps to reproduce
- User B sends a message in the group chat that everyone can see
- Open group chat

**Actual result:** The message of User B is missing, only for me.
**Expected result:** The message of User B is shown.

### Screenshots
![group mention missing](https://user-images.githubusercontent.com/13781376/140617780-57823c92-ea04-478a-8f55-7754a9d4e11c.jpg)
Six group members, if I enter "@", User B is missing.

![PM same number not in group](https://user-images.githubusercontent.com/13781376/140617783-59787cf3-3cc6-41e2-b5c6-656d0640fc76.jpg)
I write User B a PM. All PMs have only the single check. In this chat they are member of the group.

![PM not in group, can talk](https://user-images.githubusercontent.com/13781376/140617784-6eabc178-3791-4230-9e43-6bcbc6e7959e.jpg)
User B responds to my message in another chat. In this chat they are NOT in the group. But the phone and security numbers are the same.

### What I've tried so far
- Leave and rejoin the group
- Reinstall signal

### Device info

**Device:** Galaxy S8
**Android version:** 8.0.0
**Signal version:** 5.25.7

### Link to debug log

https://debuglogs.org/49c33540cc9a0d1824339b01467dbb2e3fa04454a8d8fb503903ba994e832c96

**Comment by greyson-signal** [comment]
Hi there, I have a hopeful fix for this in 5.26.x, which is currently in beta. Please let me know if it resolves when you get that version. Thanks!
