### ISSUE TITLE
Signal Android - More and Select Multiple disappeared

### ISSUE THREAD

**Issue by rvwilliams99** [signalapp/Signal-Android#11747]
I'm on version 28 Oct 2021.  I can no longer delete multiple messages as the More 3 lines are not present.

**Comment by Tursko** [comment]
It is now a circle with a check on the inside. This indicates 'select' mode.

**Comment by rvwilliams99** [comment]
Many thanks.  That's solved the problem.

Regards

Richard.

****************************************************
Richard Williams
email: ***@***.******@***.***>
mobile: 07981 734697
****************************************************

**Comment by Tursko** [comment]
Glad you figured it out. Please close this issue.

**Comment by rvwilliams99** [comment]
Thanks for the tip
