### ISSUE TITLE
Changed the application id,now app started to crash on contacts searching

### ISSUE THREAD

**Issue by harryfrz** [signalapp/Signal-Android#11742]
Im trying to rename the package name of the app.i tried several ways doing it,but after using the application id method the app started crashing while searching for contacts.can anyone help me to rename the package name without making the app crash.please help me guys.

**Comment by greyson-signal** [comment]
Hi there, we use Github for bugs. For development assistance, please try [the forum](https://community.signalusers.org/). Thanks!
