### ISSUE TITLE
Downloads cannot be paused 

### ISSUE THREAD

**Issue by palimmo** [signalapp/Signal-Android#11749]
[x ] I have searched open and closed issues for duplicates
    [x ] I am submitting a bug report for existing functionality that does not work as intended
    [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
    [x ] This isn't a feature request or a discussion topic

Downloads cannot be paused.
If you click on the animated circle during the download nothing happens.

This is very important, in particular for users that are on a (slow) metered data connection.

Device info

Device: Samsung J6 SM-J600FN/DS
Android version: 10
Signal version: 5.25.7

**Comment by Aeonitis** [comment]
@palimmo Could I ask you to discuss this as a feature request and not an issue?

The community is available [here](https://community.signalusers.org/c/feature-requests/android-feature-requests/18).

**Comment by palimmo** [comment]
> @palimmo Could I ask you to discuss this as a feature request and not an issue?
> 
> The community is available [here](https://community.signalusers.org/c/feature-requests/android-feature-requests/18).

Done!
