### ISSUE TITLE
Extremely high memory usage after a couple of days on device without Google Play Services. App becomes unresponsive and janky. 

### ISSUE THREAD

**Issue by davidtakac** [signalapp/Signal-Android#11741]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a couple of days of using Signal on my Google Pixel 4a 5G running CalyxOS without Google Play Services, the app becomes so unresponsive and janky that I cannot use it. The only thing that fixes it is a Force Stop, but the issue returns after a couple of days. The attached screenshot and debug log were taken at the time this issue was present. 

Could this be related to [Issue #9220](https://github.com/signalapp/Signal-Android/issues/9220) for which there has been a pull request for some time now? If so, what is stopping it from being merged? I would be happy to contribute. 

### Steps to reproduce
- Use Signal on a device without Google Play Services for a couple of days (possibly open ConversationActivity repeatedly to cause a memory leak as described in linked issue)

**Actual result:** Application becomes unresponsive and janky when opening the conversation list and individual conversations.  
**Expected result:** Application stays as responsive and smooth as the first time it was started after installation or a Force Stop. 

### Screenshots

![Screenshot_20211107-001353](https://user-images.githubusercontent.com/35954251/140639739-38a891ba-08da-4208-adef-b9e01f1578f9.png)

### Device info
**Device:** Google Pixel 4a 5G
**Android version:** 11
**Signal version:** 5.25.7
**Other info:** CalyxOS without Google Play Services

### Link to debug log
https://debuglogs.org/116e5b8e7b65938c641a5bbddad71924e35fcb4b4e8ec8f62094c61c1522966c

**Comment by greyson-signal** [comment]
Try 5.25.8, we made several memory-related fixes there.

**Comment by Tvirin** [comment]
@davidtakac Share with us if you have noticed any improvements in v5.25.8

**Comment by davidtakac** [comment]
@Tvirin After updating to 5.25.8 and using the app for 7 days, I haven't noticed the described lag and jank. The RAM usage peaked at 700 MB and settled at 500-600 MB. There's definitely been an improvement. 

@greyson-signal are these results in line with devices that have Google Play Services?
