### ISSUE TITLE
Not all text / phone number fields allow copying

### ISSUE THREAD

**Issue by jaredsburrows** [signalapp/Signal-Android#11750]
Add or allow single/long click to copy text and phone number fields. This is helpful for adding new contacts when the user does not have Signal.

**Comment by UserX404** [comment]
@jaredsburrows 

Features should be discussed in the [forum](https://community.signalusers.org/).
Github is used for bug reports only (as mentioned in the issue template)

**Comment by jaredsburrows** [comment]
@UserX404 This is not really a feature. In some views/pages of the app, you can easily copy the phone number but it is not consistent throughout the app.

**Comment by UserX404** [comment]
It's not really a bug. If you feel something should be improved - forum is the correct place to put your request.
It's just the way devs handle things here.
