### ISSUE TITLE
red app icon

### ISSUE THREAD

**Issue by duchampdev** [signalapp/Signal-Android#11758]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal app icon just turned red with the update to 5.26.4 from Google Play. I couldn't find a related commit in the repository. However, as I run Android 12, it might be related to the new color system. So is the changed icon intended to be like that?

### Device info
**Device:** Google Pixel 3a
**Android version:** 12
**Signal version:** 5.26.4

**Comment by lnwor** [comment]
It's fixed in 5.26.5

**Comment by duchampdev** [comment]
Thanks, it's now also fixed on my device!
