### ISSUE TITLE
Read/delivered/unread icon for messages in group chats is broken

### ISSUE THREAD

**Issue by Eldenroot** [signalapp/Signal-Android#11754]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Read/unread/delivered "icons" in group chats are not working properly

### Steps to reproduce
- create a group of 3 or more users
- send a message
- read the message by one user
- check the "icons" - it displays that the message was read by all, but actually when you click on details it is not... it should follow the status for all users (same as Whats app does, or what Signal app did in past).

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Huawei
**Android version:** 10
**Signal version:** latest beta from Google Play... but it happens on any version

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/141184427-56d4adf1-3f8f-42dc-af12-82110646f03a.png)

Happens on Signal app (Windows) too...

**Comment by bme13** [comment]
This is the expected behaviour. There are multiple discussions on the forum about that. See e.g. https://community.signalusers.org/t/read-receipts-using-group-chat-behaviour-is-this-expected-or-bug/1340.

**Comment by matkoniecz** [comment]
> You get the two checkmarks when the first member of the group gets the message delivered

This may be expected, but for me it is a bug in design and not helpful at all. For group chats it is important when last person has seen something, not the first.

**Comment by bme13** [comment]
You have to keep in mind that disabling of the read receipts works differently in Signal than in Whatsapp. In Whatsapp you can't disable sending read receipts for groups. If you disable read receipts in Signal they are also not send in groups.

**Comment by matkoniecz** [comment]
Still, showing full marker when only single person read it is misleading. Not showing anything or always unread (when someone disabled receipts) would be better.

FB style markers showing where each person finished reading would be the best (but that would be a feature request.

**Comment by bme13** [comment]
Yeah, it's misleading if you expect different behaviour indeed. Anyway I just pointed out that it's the current expected behaviour and these bug reports are for 'existing functionality that does not work as intended' as is part of the checks in the bug report template. Will just leave it to a developer what to do with this.

**Comment by Eldenroot** [comment]
This is so confusing... bad implementation of this feature... _(

**Comment by AlertSubject** [comment]
I prefer it the way it is right now

It's useful to see if someone has read your message when asking something.
WhatsApp does it in a way that you always have to check manually if you want to see if someone has seen your message

WhatsApps approach also has the disadvantage that it won't even display the message as "delivered" unless everyone has received it. Sometimes a users phone is offline for some time, especially in larger groups

Which means read receipts are being rendered useless until you manually check who was received / seen a message

Signals approach works better in my opinion. I can always see if the message has been delivered / seen by at least one user
Less manual checking for me

**Comment by Eldenroot** [comment]
Any planned changes for this annoying behaviour? Thx

**Comment by Eldenroot** [comment]
Still relevant. Need to be addressed
