### ISSUE TITLE
Signal crash when trying to leave Legacy Group

### ISSUE THREAD

**Issue by igor2x** [signalapp/Signal-Android#11778]
### Bug description
When I tried to leave legacy group Signal crashed.

### Steps to reproduce
- On contact list I had Legacy Group.
- I marked group and tapped on three dots at top right corner.
- I tried to leave the group but message button error appeared some error on leaving group.
- Then I upgrade Legacy Group to New Group. App closed down (crashed). PROBLEM.
- I started Signal in contact list tapped on group to open discussions.
- Group was opened. From three dots option I have selected options and then left the group.
- Now everything is fine. I could leave the group. Just experience is not the best to have crash...

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Crash at step PROBLEM.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
No crash.

### Device info
**Device:** Samsung A30s
**Android version:** 11
**Signal version:** 5.26.11

### Link to debug log
https://debuglogs.org/4d5adf49a64a2d17462961f935c6fe54d0f2d5b89246ceae05b523c4b1115ffc

**Comment by igor2x** [comment]
It is irrelevant to me now, because I don't have any Legacy Groups anymore. Also can't retest the problem for the same reason.
I am closing down a problem.

**Comment by Currrupted** [comment]
I am having similar issues, using the latest version on my Android device (6.36.5). When I attempt to update the group (so that I can leave the group) Signal crashes and restarts. When I try to leave the group, I only get "Failed to update the group". When I try to block the group (which should translate to leaving the group for good), Signal crashes without restarting.

**Comment by cody-signal** [comment]
Hi @Currrupted could you provide a debuglog after encountering one of the crashes?

**Comment by Currrupted** [comment]
> Hi @Currrupted could you provide a debuglog after encountering one of the crashes?

Sure thing! I just tried all three actions in the group settings. It should be among the most recent lines.
[Link](https://debuglogs.org/android/6.36.5/e648b99e06f5832c920f212b37fe82486ca0a77c013573fb715ba34b4cb55337) 

Thanks!
