### ISSUE TITLE
Single emoji group name appears as ellipsis in conversation view

### ISSUE THREAD

**Issue by ccurro** [signalapp/Signal-Android#11772]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If I create a group with a single emoji as the name, while in the conversation view the group name is abbreviated to `...`.

This also has happened to me with group names of three emojis in a row as well. There may a general issue with conversation names composed entirely of emojis, but I haven't diagnosed it in detail.

### Steps to reproduce
- Touch compose button
- Touch new group at top of the screen
- Add users to group (optional)
- Set group name to a single emoji e.g., :grimacing: 
- Enter conversation view for group and look at the top left of the screen for the conversation name

**Actual result:** The conversation name appears as `...`
**Expected result:** The conversation name should appear as :grimacing: 

### Screenshots
![Screenshot_20211117-191508](https://user-images.githubusercontent.com/44445/142309087-4f47827c-00b9-448f-a368-7c6a51a525e9.png)

### Device info

**Device:** Pixel 4a
**Android version:** 12 build # SP1A.211105.002.A1
**Signal version:** 5.25.8

### Link to debug log

https://debuglogs.org/621cfed3f21482b96d45999643f5f49ee81fc0b9c317b86acf4008952abd404d

**Comment by Aeonitis** [comment]
I'll try to investigate that very soon!

Please just double check one more time if there are duplicates of this issue. 

If there really isn't, this is a great catch! 😁

**Comment by ccurro** [comment]
All I've been able to find are two potentially related/relevant but certainly distinct issues: 
- #10625
- #10076
