### ISSUE TITLE
Emoji and keyboard issue 

### ISSUE THREAD

**Issue by Sajeg** [signalapp/Signal-Android#11780]
When you select a Emoji from the Signal-Emojis and you mark that, the keyboard appears. 
Maybe this is a known issue. ![20211120_194718.jpg](https://user-images.githubusercontent.com/84874195/142737813-b3b2414d-8368-49ad-8c01-a91907ddbb62.jpg)

**Device:**
Samsung Galaxy Xcover 4 (SMG390F) 
Android 9 Pie

**Comment by IronJunkie** [comment]
Can confirm does the same on multiple different phones with different OS & multiple keyboards.

**Comment by major-mayer** [comment]
This is most likely a duplicate: https://github.com/signalapp/Signal-Android/issues/11618

**Comment by major-mayer** [comment]
Yes this is still relevant and happens to me more often than I would like.
Still no response, neither on this nor in my issue.
