### ISSUE TITLE
Crash loop after marking large number of messages as 'read' on linked iPad.

### ISSUE THREAD

**Issue by wizardofid** [signalapp/Signal-Android#11788]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal keeps crashing as soon as it is unlocked. Starts normally if internet connection is cut (flight mode).

### Steps to reproduce 
- Setup: Signal Android 5.26.11, 1 linked iPad with Signal iOS 5.26.1.8, 1 linked Signal Desktop 5.23.1, 1 linked Signal Desktop 5.24.0, 1 linked Signal Desktop 5.25.0-beta2.
- A group with about 1300 unread messages.
- Open group at linked iPad and scroll down thus marking all messages as 'read', maybe in 2 or 3 steps.
- Tried deleting group in Signal Android, didn't help.
- Had to block some domains at router to get signal producing a debug log. Therefore debug logs are from about 15 h after first problem occurence.

**Actual result:** Signal Android crashes and keeps crashing at every restart. I think it marked the messages also as 'read'. No crash in flight mode. 
**Expected result:** Signal keeps running.

### Device info
**Device:** Fairphone FP3
**Android version:** Android 10, Build 8901.3.A.0132.20211027
**Signal version:** 5.26.11

### Link to debug log
https://debuglogs.org/3b476f94887bd51c8d7b65ed3ad4c300f10add495a46ca47d00016fe8ff5090f
https://debuglogs.org/6e5d4ac5aa4971ac743b72be99d0ad4be48e37375a2802be04d26b4655b40c5b

**Comment by fsck** [comment]
My device shows the same symptoms (immediate crashes when opening the app without airplane mode) and I also have a similar setup: Signal Android 5.26.11, linked iPad with Signal 5.26.1.7, linked Signal Desktop 5.4.1

Device: Samsung Galaxy S21
Android version: Android 11

Could you give me some pointers on which domains to block on the router to extract the debug log? I vaguely remember that you could copy&paste the debug log from the dialog, but this does not seem to work any more unfortunately.

**Comment by wizardofid** [comment]
> My device shows the same symptoms (immediate crashes when opening the app without airplane mode) and I also have a similar setup: Signal Android 5.26.11, linked iPad with Signal 5.26.1.7, linked Signal Desktop 5.4.1
> 
> Device: Samsung Galaxy S21 Android version: Android 11
> 
> Could you give me some pointers on which domains to block on the router to extract the debug log? I vaguely remember that you could copy&paste the debug log from the dialog, but this does not seem to work any more unfortunately.

Sure. I had the problem, that I coud produce a debug log in flight mode, but found no way to upload it then. I blocked following domains:
- thoughtcrime.org
- signal.org
- whispersystems.org

Thus Signal couldn't connect to its servers and didn't crash. Upload of debuglogs to debuglogs.org worked then.
Interesting side effect: After starting with this blocked domains, Signal ran many hours, even after enabling all domains again or switching to mobile connection.

**Comment by fsck** [comment]
Thank you. The android app was temporary working again for me too after I left the iPad in flight mode for a couple of hours. It is now back to crashing.

Here is the Link to the debug log: [https://debuglogs.org/644e35a01c943544d4e63f8f344e9ae288c400328a2b1a7db7f110f46184b7de](https://debuglogs.org/644e35a01c943544d4e63f8f344e9ae288c400328a2b1a7db7f110f46184b7de)

**Comment by KerryKrisp** [comment]
I have the same problem. It started when I updated Signal on my linked Ipad. After some hours Signal seemed to be working again on my phone (without changing anything on my Ipad, the only thing I did was opening signal on my linked laptop), but since yesterday it keeps crashing again when opening the app on my phone (after opening signal on my Ipad).
Deleted the Ipad as linked device (wasn't so easy because you need a network connection for that...) didn't work so I tried reinstalling it on my phone, but didn't work either, still keeps crashing.
When i turn off the internet connection (wlan or mobile internet) I can open the app without any problem.

Device: Google Pixel 4a, running Calyx Os 2.11.0 (Android 11) with Signal Version 5.26.11

**Comment by mpjanz** [comment]
Same Problem here,
No amount of reinstalling deleting data/cache is helping so far. only flight mode on the phone makes it possible to keep the app open. Iam using a linked desktop version an the ipad to be able to use it at all. 

6.Gen Ipad IpadOs 15.1
Fairphone 3 /e/os 0.19 (android 10) Signal version 5.26.11

**Comment by cody-signal** [comment]
Hi Folks, can you try installing 5.27.x and see if the issue resolves itself. We added a change we believe will fix the issue.

**Comment by greyson-signal** [comment]
Hey, I believe this is resolved in 5.27. Can you update and let me know?

**Comment by wizardofid** [comment]
Hi, 5.27.13 doesn't seem to change anything in my case. Maybe there's something new in the debuglog:
https://debuglogs.org/37c0ebbd6442c53ad190450fc261b7951718aa6794734ef8cf0f86dfd3aed537

**Comment by greyson-signal** [comment]
This has turned into #11818, merging this discussion into that.
