### ISSUE TITLE
much too tight character limits have been imposed on a few strings on transifex

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11784]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Dutch translation for "speaker" is "luidspreker". This is the only proper translation, used everywhere where speaker is translated. I now see that Signal imposed a limit of 8 characters for the translation of speaker. That's 1 character more than the English word. That's unreasonable. In this case it would make sense to update the UI so it can take a few more characters, rather than imposing a limit which only hurts users in other language regions and calling the matter resolved.

Furthermore we see that we already translated these before the character limit was placed, and thus we can see that longer strings actually do fit quite well, with the exeption of the word "luidspreker" for which the last letter jumps to the next line. Ideally the word would be translated as "`Luid&shy;spreker`" allowing it to word wrap properly, however:
1. Signal does not support rendering &shy; on this string
2. The character limit prevents us from editing this text string to anything longer than 8 char.

Proposed solution:
Leave this to translators discretion. Enable rendering of `&shy;` only on call button labels (performance impact, but only at a critical place in the app) and stop imposing a character limit.
This is less ideal performance wise, but allows for proper translations that make sense to users in other languages. Forcing 8 char simply doesn't cut it here, the label might as well be removed then as only the icon would still make sense.

### Screenshots

![Screenshot_20211122-212237](https://user-images.githubusercontent.com/34976212/142931149-093c6cc3-aa51-4255-bae0-086e792f329c.png)

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0.0
**Signal version:** 5.27.2

**Comment by Meteor0id** [comment]
Caracter limit is still too tight, making it impossible to maintain these translations while they are the only right translations

**Comment by Meteor0id** [comment]
Still waiting for the product team to renove the character limit on this string. the code has changesz more characters fit but transifex won't allow it yet. I just need to add a hyphen (&shy) to fix this.

@riyapenn-signal 
@cody-signal

**Comment by Sgn-32** [comment]
character limit is now 16. "Luid[SHY]spreker" with 12 character should work.

![Bildschirmfoto_2022-04-23_12-54-18](https://user-images.githubusercontent.com/49990901/164891635-052144aa-bb7b-4534-b46b-7e6798582ba3.png)

**Comment by Meteor0id** [comment]
That allows me to finally add thd &shy in Dutch which is great.

However the kimit is still 8 for WebRtcCallView__flip where Dutch is using 9
And the limit is still 8 for WebRtcCallView__end_call where Dutch is using 17

These limits should still be increased, the current translations seem to fit fine and it makes no sense to have such tight limits

**Comment by Meteor0id** [comment]
Also happening with conversation_selection__menu_message_details
I just looked it up to insert an &shy only to discover that string also has a too tight char limit

**Comment by Meteor0id** [comment]
the limit is still 8 for WebRtcCallView__flip where Dutch is using 9
And the limit is still 8 for WebRtcCallView__end_call where Dutch is using 17

Although I no longer have access to transifex as recent as a week ago this limit was still preventing edits, and it should still be removed so yranslators can do what they need to do

**Comment by Meteor0id** [comment]
@phil-signal
