### ISSUE TITLE
Singal 5.26.11: Show details of a contact not working

### ISSUE THREAD

**Issue by wheelseal** [signalapp/Signal-Android#11794]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I will see the details of a Signal-Contact, it crashed or go back to the chat-list.

### Steps to reproduce
- open signal and tab on an avatar of an single-chat in your chat-list. 
- scroll down in the opened menu and tab on "contact details". 

**Actual result:** If you tab on it, Signal crashed or jump back to your chat list.
**Expected result:** Signal openes the contact manager.

### Screenshots

![signal-2021-11-28-133849](https://user-images.githubusercontent.com/61382908/143768678-de7e4433-d113-47d4-b863-2f279f124aae.jpg)

### Device info

**Device:** Sony Xperia XA2
**Android version:** 10
**Signal version:** 5.26.11

### Link to debug log

https://debuglogs.org/8137637b14896627b508c84096fc2b826797fb6af000f567867f8a270cd0c6b4

**Comment by greyson-signal** [comment]
Apparently your device has no application that is capable of viewing contacts. We can show an error message in that case instead of crashing, but that's about it.

**Comment by Aeonitis** [comment]
I can try to take this on. Maybe "This action is not supported on your device." Is a sufficient error message?

I'll try to figure out how the device type is determined, probably just by Android OS version checking maybe...

**Comment by Tursko** [comment]
> I can try to take this on.
> 
> Maybe "This action is not supported on your device." Is a sufficient error message?
> 
> I'll try to figure out how the device type is determined, probably just by Android OS version checking maybe...

Certainly OP's phone has a contact app, or maybe they accidently removed it? They reported this bug because they expected it to open in their contact app though so I feel like that already invalidates that assumption.

**Comment by Aeonitis** [comment]
@Tursko I deleted my comment as I do agree with your point...

Hopefully we can come across a debug log of that...
