### ISSUE TITLE
Can't delete thread b/c dialog is cropped (DE / German)

### ISSUE THREAD

**Issue by tdashton** [signalapp/Signal-Android#11792]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Can't interact with any of the options when I select a conversation, delete it and am presented with the alert dialog. The title seems too long and pushes the buttons off the right hand side of the screen. Portrait mode on a Sony Xperia XZ2 Compact.

### Steps to reproduce
- try to delete any conversation

**Actual result:** AlertDialog which I cannot interact with in portrait mode.
**Expected result:** Some sort of UI element I can interact with.

### Screenshots

![Screenshot_20211126-124601](https://user-images.githubusercontent.com/820379/143577281-9b27cb23-9ea3-464d-a400-b159187a47fb.png)

### Device info

**Device:** Sony H8314
**Android version:** 8.0.0
**Signal version:** 5.26.11

### Link to debug log

n/a

**Comment by Aeonitis** [comment]
Hey,

I just had a quick look. The english and german texts seem similar in length. 

```
<plurals name="ConversationListFragment_delete_selected_conversations">
    <item quantity="one">Delete selected conversation?</item>
    <item quantity="other">Delete selected conversations?</item>
</plurals>

<plurals name="ConversationListFragment_delete_selected_conversations">
    <item quantity="one">Ausgewählte Unterhaltung löschen?</item>
    <item quantity="other">Ausgewählte Unterhaltungen löschen?</item>
</plurals>


<plurals name="ConversationListFragment_this_will_permanently_delete_all_n_selected_conversations">
    <item quantity="one">Dies wird die ausgewählte Unterhaltung unwiderruflich löschen.</item>
    <item quantity="other">Dies wird alle %1$d ausgewählten Unterhaltungen unwiderruflich löschen.</item>
</plurals>

<plurals name="ConversationListFragment_this_will_permanently_delete_all_n_selected_conversations">
    <item quantity="one">This will permanently delete the selected conversation.</item>
    <item quantity="other">This will permanently delete all %1$d selected conversations.</item>
</plurals>
```

Maybe the device is telling the app it is in portrait mode instead of landscape mode?

It makes me wonder, is the problem still there the next time you try it? 

If it is, can you try three more things?
1. Bring up the dialog starting in landscape mode
2. Bring up the dialog in landscape mode then rotate to portrait mode while the dialog comes up.
3. Bring up the dialog in portrait mode then rotate to landscape mode while the dialog comes up.

**Comment by tdashton** [comment]
hi @Aeonitis ! Thanks for the quick response! I have tested again and could not reproduce the issue, so it seems indeed temporary and likely caused by what you mentioned above. Thanks!
