### ISSUE TITLE
App link verification is failing

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#11797]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app links for Signal (signal.group, signal.art, signal.tube, signal.me) are failing verification.

On Android 12, this results in web intents for Signal not opening directly in the app by default (https://developer.android.com/about/versions/12/behavior-changes-all#web-intent-resolution)

### Steps to reproduce

Following https://developer.android.com/training/app-links/verify-site-associations#invoke-domain-verification:

```
$ adb shell pm get-app-links org.thoughtcrime.securesms
  org.thoughtcrime.securesms:
    ID: 36102c4f-9655-4fa6-b098-94cfe53e61b7
    Signatures: [29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26]
    Domain verification state:
      signal.group: legacy_failure
      signal.art: legacy_failure
      signal.tube: legacy_failure
      signal.me: legacy_failure
```

From https://signal.group/.well-known/assetlinks.json, https://signal.art/.well-known/assetlinks.json, https://signal.tube/.well-known/assetlinks.json, https://signal.me/.well-known/assetlinks.json, the JSON uses `"29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0 EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26"` as the sha256 of the signing certificate fingerprint. However, there's a space in the fingerprint; this is likely the reason why it's failing verification.

On the other hand, Apple Music has verification for most of its domains, and their assetlinks.json don't have a space in the fingerprint:

```
$ adb shell pm get-app-links com.apple.android.music
  com.apple.android.music:
    ID: 60c96c91-6463-42b0-911a-06c1e995a3fd
    Signatures: [88:BA:59:0E:C2:E1:EA:33:C4:45:8D:AF:59:48:9F:AE:E2:CE:F2:97:A9:B4:07:1E:18:CF:82:EF:53:11:00:AA]
    Invalid autoVerify domains:
      applemusic
    Domain verification state:
      music.apple.com: verified
      finance-app.itunes.apple.com: verified
      itunes.apple.com: verified
      buy.itunes.apple.com: verified
      setup.icloud.com: verified
      se2.itunes.apple.com: legacy_failure
      search.itunes.apple.com: verified
      itun.es: verified
```

### Screenshots

| ![1](https://user-images.githubusercontent.com/26474149/143981493-eb098348-e6c2-4874-bc92-0516753a9fd2.jpeg) | ![2](https://user-images.githubusercontent.com/26474149/143981497-9264c0a2-451a-45a2-9e32-9aa85218097e.jpeg) |
|---|---|

### Device info
Pixel 5, Android 12 (GrapheneOS), Signal 5.26.11

**Comment by inthewaves** [comment]
App link verification is still failing. A likely fix is to remove the space from the sha256 fingerprints at  https://signal.group/.well-known/assetlinks.json, https://signal.art/.well-known/assetlinks.json, https://signal.tube/.well-known/assetlinks.json, https://signal.me/.well-known/assetlinks.json

**Comment by huynguyennovem** [comment]
Let's try this:
- Return code 200 instead of 304. 
FYI: https://www.reddit.com/r/androiddev/comments/ni33zr/comment/hc739d5/?utm_source=share&utm_medium=web2x&context=3

**Comment by inthewaves** [comment]
still doesn't verify successfully on Android 12

**Comment by ehrenkret-signal** [comment]
```shell
adb shell pm verify-app-links --re-verify org.thoughtcrime.securesms
adb shell pm get-app-links org.thoughtcrime.securesms

  org.thoughtcrime.securesms:
    ID: 00000000-0000-0000-0000-000000000000
    Signatures: [29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26]
    Domain verification state:
      signal.group: verified
      signal.art: verified
      signal.tube: verified
      signal.me: verified
```

**Comment by ehrenkret-signal** [comment]
Thanks, this has been fixed

**Comment by mercpls** [comment]
> Thanks, this has been fixed

What was the fix?

**Comment by inthewaves** [comment]
the space in the SHA256 fingerprint string was removed from https://signal.group/.well-known/assetlinks.json, https://signal.art/.well-known/assetlinks.json, https://signal.tube/.well-known/assetlinks.json, https://signal.me/.well-known/assetlinks.json (old version: https://web.archive.org/web/20211021000502/https://signal.group/.well-known/assetlinks.json)
