### ISSUE TITLE
Dialog options are unreadable because of elipsis

### ISSUE THREAD

**Issue by gjvnq** [signalapp/Signal-Android#11793]
Language: pt-BR

Android version: 11

Signal version: 5.26.11

What happened: dialog options are not completely readable because the text is longer than the dialog width causing them to be "cropped" with elipsis (...). (See attached screenshot)

What should have happened: dialog options should either have a line break or be shorter.

![Screenshot_20211127-115412_Signal](https://user-images.githubusercontent.com/3050524/143686640-fdebf93f-2244-4de2-b284-8e97d506585f.png)

If new line breaks can't be implemented, one option is to rewrite the question as:

> What backgrounds do you want to remove?
>  * Only the default one
>  * All of them

Or in Portuguese:

> Quais papéis de parede você quer remover?
>  * Apenas o padrão
>  * Todos

**Comment by Meteor0id** [comment]
Gonna see if I can reach the Portugese translators, but honestly it would have been nice if these texts would line break instead.

**Comment by cody-signal** [comment]
There's a fix coming in 5.28 to do multiline.

**Comment by gjvnq** [comment]
Thanks!
