### ISSUE TITLE
The conversation is rendered with additional newlines

### ISSUE THREAD

**Issue by seguri** [signalapp/Signal-Android#11796]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The Android app is adding newlines to the conversation that are not part of the original message.

### Steps to reproduce
- write "23.05" in a conversation

**Actual result:** "23.0" is displayed on the first line, "5" on the second
**Expected result:** "23.05" is displayed on the same line

### Screenshots

![Screenshot_20211128-220734_Signal (1)](https://user-images.githubusercontent.com/2405157/143932015-4ccad3a5-0b46-4d6b-bcb1-78371857e537.jpg)

### Device info

**Device:** samsung SM-A528B
**Android version:** 11
**Signal version:** 5.26.11

### Link to debug log

n/a

**Comment by seguri** [comment]
Same for "No no". It's split on 2 lines

**Comment by sagarumathe** [comment]
I am experiencing the same,
I noticed this happening mostly with 5 lettered words like Hello, Bella, etc

usually with words that have a slanting letter that takes less space like i,l,1,t etc
![Screenshot](https://user-images.githubusercontent.com/43010515/144861107-8f20c942-00a1-4fc4-b210-eba7bebfa97f.jpeg)

**Comment by seguri** [comment]
Seems fixed in 5.30.6

**Comment by nicokaiser** [comment]
Not fixed in 5.30.6 on Fairphone 4.

**Comment by sagarumathe** [comment]
I'm still facing it,
I'm on the latest beta build

**Comment by rainerzufall** [comment]
updated debug log incoming: https://debuglogs.org/55cb2b0fd0d6d0a259336dbf3721110cd3a1ec99e0c1b818a323e7efa7e334cb

The following two words are 100% reproducible being split in two lines:
`Bis später`

gets send like:
`Bis`
`später`

**Comment by rainerzufall** [comment]
related issues with similar problems: 
https://github.com/signalapp/Signal-Android/issues/11688 ("Short messages displayed in multiple lines")
https://github.com/signalapp/Signal-Android/issues/10365 ("Messages that contain only a single 5 character word are display on 2 lines.")

**Comment by rainerzufall** [comment]
https://github.com/signalapp/Signal-Android/commit/9f1deda220a4fab64836d99e4af2d634a5decfea in **5.32.8** fixes the problem for me!
