### ISSUE TITLE
After Granting Permission Can't Perform Operation Directly

### ISSUE THREAD

**Issue by ketancts** [signalapp/Signal-Android#11808]
We have to select photo gallery option twice to change profile pic, after giving permission we can't redirect to select photo screen (gallery).

I want to open gallery screen directly after granting storage permission.

How can I achieve that?

**Comment by UserX404** [comment]
@ketancts
This is not a proper issue report.
Please don't delete the issue template. As mentioned in the template GH is for bug tracking and feature request should be discussed in the forum.
https://community.signalusers.org/
