### ISSUE TITLE
Signal for Android doesn't work on China ROM phones.

### ISSUE THREAD

**Issue by aswedaw** [signalapp/Signal-Android#11803]
Both versions of Signal Private Messenger for Android Google Play Store and Signal Website,
don't work on China ROM phones which  don't support Google Play Services App.
If you can publish a version like Telegram with Google Firebase in the Standalone Web Version, it will be a great help to Myanmar people. 
Whenever I tried to signin Signal Private Messenger, Google's good-for-nothing captcha is an obstacle. Even though I transfered from my old phone with my Google Play Services, to a China ROM phone, without Google Play Services app. Chinese telephone manufacturers are playing tricks on us.
Please try Telegram version of  its own website . Try on Amazon Tablet.
It perfectly works without Google Play Services.
Check it out. Learn from it. 
https://telegram.org/android

**Comment by mlsem** [comment]
Is technically we could free up form google play services ?

**Comment by aswedaw** [comment]
If we wish so, we will. If we don't wish so, we won't. But, the point I'd like to point out is
not-Ungoogled Signal Private Messenger, but, Signal Private Messenger with Google Firebase
Cloud Messaging in the Signal Private Messenger APK like Telegram Web Version APK.
We can't use Google Play Services APK on China ROM devices. Previously, we could to use Google Play Services on the same phones. But,CCP are cyberbullying Myanmar Unicode users.

**Comment by aswedaw** [comment]
We need  the ability of Signal Private Messenger
like Telegram Messenger Web Version Standalone APK,which uses Google Firebase in-app support. Signal Private Messenger insists Google Play Services app on China ROM devices, which is impossible.

**Comment by woheller69** [comment]
what about using Signal FOSS which works without the Google stuff?

     https://www.twinhelix.com/apps/signal-foss/

**Comment by ndgunebo** [comment]
> what about using Signal FOSS which works without the Google stuff?
> 
> ```
>  https://www.twinhelix.com/apps/signal-foss/
> ```

Does not work. Captcha is forced on the server side. You will not be able to register without submitting captcha.
