### ISSUE TITLE
Signal causes battery overheating

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#11804]
I still use a Pixel XL. Until last week it was running Android 7.1.2 and Signal for all those years without this issue. I did an OTA update to Android 10 last week. Since then Signal has several times caused massive battery drain to the point that the phone got so hot it woke me up out of a dead sleep in the middle of the night (I fell asleep with it in my pocket). When I open the battery usage screen it's all Signal.

Each time it happens I've noticed that it's when there are new unread messages. Signal is set to repeat notifications 10 times.

**Comment by sezanzeb** [comment]
I'm having 83% battery usage from signal alone

**Comment by jbaker6953** [comment]
I haven't posted more because it's intermittent and I can't pin down a test case. However, it has happened to me even when there aren't unread messages. It seems to happen whenever Signal has focus when the phone's screen is turned off. It's as if Signal doesn't know the screen is off and continues using resources as if the screen is on and Signal is the active app.

**Comment by jbaker6953** [comment]
Happened again last night. Signal drained my phone from 100% to 2% in 6 hours without the screen being on more than 10 minutes the entire time. The specific situation was that I was part of a group SMS conversation and there were a lot of messages flying back and forth.

**Comment by sezanzeb** [comment]
Have you tried the newest version? v5.28.8

I'm not running signal on my phone at all currently

**Comment by jbaker6953** [comment]
5.28.5 is the latest offered on Google Play for my device.

**Comment by sezanzeb** [comment]
@greyson-signal, I hope you don't mind that I'm pinging you. This issue really seems to be quite critical

**Comment by jbaker6953** [comment]
Signal won't stop with the battery drain today. When I force stop it I still receive message notifications, but as soon as I unlock Signal it starts burning battery at an incredible rate. Today it burned through 45% in 2 hours.

**Comment by OneuKdgzuR** [comment]
Hello, I come here to confirm this problem, same symptoms :
It happens when Signal has focus/is on foreground when I turn off screen. If Signal is not on foreground, no battery drain. But I forget to put Signal in background before turning off screen, so I lost a lot of battery (15% in 45 minutes this morning).
I have this problem since at minimum 2 months.

Phone : Faiphone 3+
Signal version : 5.28.10
OS : Lineageos 18.1 (in Lineageos 17 I was getting the same problem), no Micro-G or Google Play Services
Using MullvadVPN

**Comment by OneuKdgzuR** [comment]
Humm so  maybe we have same symptoms but not the same problem because for example, I set my phone on plane mode every night, like this night. I turn off my screen with Signal on foreground, and during night, it lost 70% battery, even without connection or unread messages from groups.

**Comment by jbaker6953** [comment]
Are you sure you didn't receive any group messages that day. Once the issue is triggered I cannot find a way to stop it reliably, even if no more group messages arrive.

**Comment by sezanzeb** [comment]
I'm running signal in some battery saving modes, but will only be able to receive messages when opening the app. The battery usage is not causing trouble anymore. I need to check how it behaves when disabling energy savings.
