### ISSUE TITLE
Emoji skin color distinction is ignored on message reactions 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#11802]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji reaction summaries to a message seem to ignore skin colorizations. I came across a message reacted with a neutral thumbs up and a white thumbs up and the message unfortunately showed two white thumbs up.

### Steps to reproduce
- in a group chat send a message
- have someone react to it with a neutral skin color emoji 
- have someone else react with the same emoji but with a specific skin color

**Actual result:** message shows two of the skin color emoji reacts
**Expected result:** it should show one neutral skin color reaction and another with the skin color that the other person reacted with 

### Screenshots

The message
![signal-2021-12-01-15-09-33-975.jpg](https://user-images.githubusercontent.com/22125581/144315009-4ed16d2b-28c7-4489-aaaf-03f850c60ad9.jpg)

The reactions when clicked on:
![signal-2021-12-01-15-09-33-975 (1).jpg](https://user-images.githubusercontent.com/22125581/144315081-0bf6933a-0cbc-4934-a849-3efb661476c4.jpg)

### Device info

**Signal version:** 5.26.11

**Comment by bitmold** [comment]
Yes stilllllllll happens

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by bitmold** [comment]
Yes this happenzzz

**Comment by alex-signal** [comment]
The color of the emoji in the reaction is meant to match whatever you've personally selected as your "default" skin-tone variation for that reaction. (For example, if you thumbs up using tone A, those will be collapsed to tone A on the bubble

**Comment by bitmold** [comment]
My default skin color is the generic yellow one yet in the pic above it showed a specific white skin color

**Comment by bitmold** [comment]
Not able to reproduce this someone should check if it exists

**Comment by cody-signal** [comment]
If you don't have a default tone then it'll be whatever tone other folks are sending.

**Comment by bitmold** [comment]
I didn't set a default tone. I think it's weird that a neutral and white thumbs up get set as two white thumbs up

**Comment by bitmold** [comment]
I think this is still a problem and still occurs in the latest release.e ![signal-2022-06-16-10-30-37-070.jpg](https://user-images.githubusercontent.com/22125581/174093425-cf9b0206-9a8e-4851-9370-841500e3d023.jpg)
![signal-2022-06-16-10-30-37-070-1.jpg](https://user-images.githubusercontent.com/22125581/174093445-984cfb54-f3fc-4c3d-afd0-618c82bd8f60.jpg)

**Comment by greyson-signal** [comment]
To be clear, this was a specific design choice. We cluster skin tone variations of the same emoji together, and we will simply use the most recent variation we received to represent the group. Nothing is perfect, but it was decided that this was better than showing 4 different variations of a thumbs up in the summary view.
