### ISSUE TITLE
Android 12 can't receive notifications only on mobile data, wifi works fine

### ISSUE THREAD

**Issue by heretoenhance** [signalapp/Signal-Android#11814]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a Samsung Galaxy S21 on Android 12 and I don't receive notifications while on mobile data, I followed everything on the support page but nothing works (disabling battery optimisations, etc.)

I receive notifications while on wifi with no issues at all.

### Steps to reproduce
- Wait for someone to send you a message while your app is closed and your phone is on mobile data.
- The message doesn't get delivered unless you open the app

### Device info

**Device:** Samsung Galaxy S21
**Android version:** 12
**Signal version:** 5.27.13

### Link to debug log

https://debuglogs.org/96fff477a68e64974717531bc5b878fc9cf9171e15d85aa00dcf0e0c61e9b9ec

**Comment by sallyahaj** [comment]
On Oppo 6 Android 12, there is no notification at all, whether it connected to mobile data or wifi.

**Comment by sosterauer** [comment]
I had the same happen to me. No notifications at all but the message was shown as delivered. This started after some phone update. Its an Oppo Reno 6.
Solution was to change the notification sound(s). After this the notifications immediately started to appear again.

**Comment by woheller69** [comment]
For me it works with either mobile data OR Wifi. But switching between them does not work.
Maybe the push connection needs to be renewed with every change?

**Comment by woheller69** [comment]
After a fresh reboot with mobile data on, push notifications are working.
If I switch off mobile data for a few seconds and then switch them on again, notifications are broken.
This is only fixed by a reboot. Killing and restarting Signal is not sufficient.

**Comment by greyson-signal** [comment]
@woheller69 Can you please post a log taken after this happens?

**Comment by woheller69** [comment]
[logcat.txt](https://github.com/signalapp/Signal-Android/files/8171302/logcat.txt)

Here is a logcat.
I first deleted logs. 
Then sent test message from other device -> received
Then switched mobile data off (Wifi was off before).
Wait 5s.
Mobile data on
Second test message -> not received
Create logcat

**Comment by greyson-signal** [comment]
Thank you so much for the logcat log -- is there any way you could also post a debuglogs link? Settings > Help > Debug log > Sbumit

**Comment by woheller69** [comment]
https://debuglogs.org/android/5.32.14/c13b40261026e49cdd40f97a38fdd890a6f84814077c87ebce02f6ad48574fcd

**Comment by woheller69** [comment]
In the meantime I rebooted and push works again

**Comment by woheller69** [comment]
If push stopped working with mobile data instead of a reboot it also helps to
1. switch on Wifi
2. switch off mobile data
3. switch off Wifi
4. switch on mobile data

**Comment by woheller69** [comment]
with 5.34.5 it seems to be even worse...
And my workaround does not seem to work anymore

**Comment by cody-signal** [comment]
@woheller69 can you submit another updated debuglog? We've made changes around notifications since the last one.

**Comment by woheller69** [comment]
Here is the log. Just received a delayed message...

https://debuglogs.org/android/5.39.3/4ede6aae6c395a43a94e0183c2ee2e6aab0a71fb694939d3b67f4995d2479567

**Comment by cody-signal** [comment]
Thanks, it appears you have some very large FCM delivery delays (like in the 12hr+ range). The system is reporting that the connection you are on is metered and this will often cause slow notifications. Samsung also likes to do special things to us occasionally.

**Comment by woheller69** [comment]
Don't know what you mean with metered connection. It is a normal mobile connection, usually LTE.
I have not imposed any restrictions.
Wifi is switched on only if I make larger downloads.
My IMAP emails are received immediately within seconds and are never delayed.

With TwinHelix Signal-FOSS using Websocket it works fine as well but power consumption is too high as it keeps my phone from entering deep sleep. The IMAP connection does not cause that issue with deep sleep.

**Comment by cody-signal** [comment]
> Don't know what you mean with metered connection.

At the top of your log, we put in if the OS indicates your connection is metered. It's reporting it as such.

> My IMAP emails are received immediately within seconds and are never delayed.

Interesting. Do you know if they use push notifications or something else?

> With TwinHelix Signal-FOSS using Websocket it works fine as well but power consumption is too high as it keeps my phone from entering deep sleep.

Good to know. This makes sense given the websocket bypasses the need for FCM push notifications and those are thing being massively delayed.

**Comment by woheller69** [comment]
I am using K-9 mail for email. As far as I know it uses IMAP Idle for push notifications.
https://en.m.wikipedia.org/wiki/IMAP_IDLE

Power consumption is very low. My phone needs about 1% battery per hour in total.
With the websocket it is more than 2%...
I wonder why the websocket connection needs so much more.

**Comment by woheller69** [comment]
Push connection in k-9 is renewed every 6min (can be set by user from 1min up to one hour).
But that does not mean emails are delayed up to 6 min. They are received immediately.
Is the 55s cycle for the websocket really needed?
