### ISSUE TITLE
5.27.13: Crash after startup ("Must provide a UUID for E164!")

### ISSUE THREAD

**Issue by KommX** [signalapp/Signal-Android#11818]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal app crashes directly after startup (when phone is connected to the internet). From #10951 I've learned that I can start the app, when I set the phone to airplane mode. Then, I can also *see* the debug logs, but I can't submit them, because I would need internet access for that. Connecting the phone to the internet again, directly crashes the app again.

### Steps to reproduce
- I just start the app.
- Unfortunately I have no clue what previous actions could have caused this issue.

**Actual result:** App crashes with "java.lang.IllegalArgumentException: Must provide a UUID for E164!"
**Expected result:** App should start without crash.

### Device info

**Device:** Google Pixel 6
**Android version:** 12
**Signal version:** 5.27.13

### Link to debug log
Unfortunately, I don't know how to provide the debug logs, but I can see them, so I can at least retype some things, I see there:

`java.lang.IllegalArgumentException: Must provide a UUID for E164!`
`at org.thoughtcrime.securesms.database.RecipientDatabase.getAndPossiblyMerge(RecipientDatabase.java:437)`

**Comment by albrow** [comment]
I'm experiencing this as well. Some additional context in case it helps:

- This seems to be the [line of code where the crash is occurring](https://github.com/signalapp/Signal-Android/blob/b981ac4fe440108f6b21f48facc593447fd46054/app/src/main/java/org/thoughtcrime/securesms/database/RecipientDatabase.java#L437).
- As far as I can tell, it first started happening on version 5.
- I can see the full stack trace on the "Feedback Agent" application, but unfortunately I am not able to copy/paste it. I attached a screenshot of the stack trace:
![Screenshot_20211207-144635](https://user-images.githubusercontent.com/800857/145117770-b41e8d27-6d50-4d55-9150-8ad5ca627f6d.png)
![Screenshot_20211207-144655](https://user-images.githubusercontent.com/800857/145117775-3bddba5c-56d4-4930-ad0f-300eb9e429d1.png)
![Screenshot_20211207-144644](https://user-images.githubusercontent.com/800857/145117777-2e6588a6-2623-449b-8f30-68b305210280.png)
27.13.

Let me know if there is any other information I can provide that might be helpful.

**Comment by greyson-signal** [comment]
Fixed in 5.28, which is going to beta shortly. You can join the beta here: https://play.google.com/apps/testing/org.thoughtcrime.securesms

**Comment by KommX** [comment]
I can confirm that the update to 5.28.1 fixed this crash.
Thank you!
