### ISSUE TITLE
[Android 12/Pixel 6 Pro] Audio playing through wrong speaker

### ISSUE THREAD

**Issue by shadACII** [signalapp/Signal-Android#11825]
In the current Play Store Version of the App the Audio of speech Messages plays from the bottom firing speaker when the device is Held in the war and the Screen geht's turned Off by the proximity Sensor.

**Comment by Aeonitis** [comment]
Sorry, I just want to clarify, that happens on non Pixel phones too. It also happens on voice messages on other apps too. Just a feature that allows to auto-play with ear speakers and main speakers interchanging based on Sensor.

Not sure what's the defect tbh.

**Comment by shadACII** [comment]
The issue is, that Signal plays through the wrong speaker. When held on my war it plays through the Main speaker and Not the earpiece speaker Like on the other phones i have tried. Don't know why thus happens some Times but i only observed this in the Signal App.

**Comment by Aeonitis** [comment]
Oh I see now, my main phone is the same phone as yours, a Pixel 6 Pro.

I have the latest changes (5.27.13) and it switches correctly:

If close to ear -> ear speakers play.
If away from ear -> main speakers play.

I wonder if you're on Stable version or on the Beta version right now...

**Comment by shadACII** [comment]
I'm on 5.27.13 too and today it didn't had the issue. Maybe it was a Bug in Android 12 and my Last Restart fixed it.

I guess as the Bug cannot bei reproduced thus issue should bei closed.

**Comment by Aeonitis** [comment]
Welcome back anytime you have any further issues ☺️👍
