### ISSUE TITLE
Typo in the Notification magaphone

### ISSUE THREAD

**Issue by tinyboxvk** [signalapp/Signal-Android#11823]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Typo in the Notification profiles magaphone

### Steps to reproduce
Upgrade to 5.28.0

**Actual result:** Typo in the Notification profiles magaphone

### Screenshots

![signal-2021-12-08-195142](https://user-images.githubusercontent.com/13696594/145309563-19e7cd3f-0fda-4e24-8db2-90f1da1c440b.jpeg)

### Device info
**Android version:** 11
**Signal version:** 5.28.0

**Comment by cody-signal** [comment]
Thanks this was reported already on our beta thread: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-28-release/39659

Looks like you are using the beta to get this, so feel free to report issue there.

edit: Thanks for closing already, guessing you saw the fix. :)

**Comment by tinyboxvk** [comment]
> so feel free to report other beta issues there.

Thanks for providing the link!
