### ISSUE TITLE
the selected contact is invalid

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11820]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to share a particual contact from my system contacts I get this error, however this is just a basic contact with a normal name, last name and phone number. I fon't see why it could be invalid. Editing the name did not solve it either. I made a second contact with all the sane details and that one is not invalid. Looks like a bug, but don't know how to provide the right information to debug it.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/0e46abe8ea0f81b248b17958a83bd0e178a3c7579a939b8f045eceb6d8dcec78

**Comment by Aeonitis** [comment]
I didn't understand that, your contact name has hyphens in their name? Is that what reproduces the error?

What message did you get? Did the app just crash? What did you mean by invalid?
