### ISSUE TITLE
Notifications unreliable in 5.27.13

### ISSUE THREAD

**Issue by chaoscommander** [signalapp/Signal-Android#11826]
Since the update to version 5.27.13 I frequently have the problem of not receiving message notifications until I actively open the app. I have set all the right options, turned off battery optimization etc. since forever ago and I have checked that they still are set correctly.

Log, a few minutes after the last occurrence: https://debuglogs.org/211072d3831584c0c4e14c23a431a200fed82b5e569cfb21898e798eef378bca

**Comment by mimre25** [comment]
Same here on a Samsung Galaxy S7 with Android 8.0.0, and "Samsung Experience" 9.0; Signal 5.27.13.

Only get the notifications when opening signal.

**Comment by beaini** [comment]
I was facing this issue. I was able to resolve it by changing the Notification sound. My guess is that with the upgrade (I upgraded both OS and Signal, so dunno which) the Notification sound that I had selected was unavailable. Instead of notifying without a sound, it failed to notify me completely.

**Comment by chaoscommander** [comment]
> I was facing this issue. I was able to resolve it by changing the Notification sound.

This is not the case for me.

**Comment by greyson-signal** [comment]
@chaoscommander I see a lot of evidence of your OS not giving us FCM messages. If we don't get FCM messages, we don't know when you got a new message, and we can't show notifications. I noticed that you're using Lineage -- I don't know what version of Play Services you're using, but if you're using gapps or something, it could just be a bug on their end or something.

**Comment by UserX404** [comment]
@mimre25
You can check the link posted in this [forum tread](https://community.signalusers.org/t/keep-android-apps-from-sleeping/39820).

@chaoscommander 
Unfortunately there is no OnePlus section.
Have you already checked support's [troubleshooting section](https://support.signal.org/hc/en-us/articles/360028198711#oneplus)?

**Comment by chaoscommander** [comment]
@greyson-signal Could be, but seems unlikely to me, since it always worked perfectly until I updated Signal to 5.27.13. Other apps also have no trouble giving me push notifications.

@UserX404 As I said above: I have set all the right options for battery optimization etc.

**Comment by greyson-signal** [comment]
I guess I'm trying to say that this isn't something we have any control over. Your system is effectively holding on to FCM pushes and not giving them to us until we're foregrounded. Some phones just do this in the name of battery optimization. I don't know your system well enough to know if it's a bug in Lineage or if you're missing yet-another-toggle, but the problem cannot be solved programmatically.

**Comment by chaoscommander** [comment]
Understood. Thank you for analyzing and explaining the problem, @greyson-signal.

**Comment by chaoscommander** [comment]
Did you make significant changes to the notification system in 5.30.6? The problem has suddenly gotten much worse. I do not receive any notifications anymore until I open Signal actively, even if it was only backgrounded for a few seconds before the next message arrives.

**Comment by cody-signal** [comment]
No, there were any big changes in 5.30.6. We made a few tweaks in the latest beta to how we detect networking.

You can provide a new debuglog if you'd like for us to look into.
