### ISSUE TITLE
add option to Disable proximity sensor when listening to voice messages

### ISSUE THREAD

**Issue by nanderer** [signalapp/Signal-Android#11837]
Hi,

i am right now listening to many voice messages and would like to put my phone into pocket while playback but that interrupts the playback. Also i sometimes trigger the sensor accentually. 

I know its a nice feature to hold the phone to your ear and listen to it more quietly but when i am at home i dont need that and when i am on the go ive connect a headset to my phone...

So please add an option in the setting to disable the proximity sensor handling as other apps have.

Thanks in advance and keep up the good work

**Comment by major-mayer** [comment]
I think you have to create a topic on the forums for that, as Signal uses github only for bug reports and this is a feature request.
