### ISSUE TITLE
Android went into unrecoverable crash state. Cannot recover messages from iPad.

### ISSUE THREAD

**Issue by djensen47** [signalapp/Signal-Android#11835]
First, thank you for Signal and all the hard work.

Issue: Signal crashed constantly on Android but all the data was synced to iPad. After I stupidly reinstalled on Android I cannot get the data out of my iPad.

Can I create a backup on my iPad and use it to restore to another device? If not, why not?

Question: is there some hidden feature or files to get my data (even if it cannot be used to restore)? Or is there a way to backup and restore from iPad to Android or iPhone?

**Comment by djensen47** [comment]
Wasn’t sure whether to post on Android or iOS since Android had the crash, I posted here.

**Comment by alex-signal** [comment]
Hi! Unfortunately, unless you had backups enabled, that message history is gone.
