### ISSUE TITLE
unable to send/receive messages in group chat

### ISSUE THREAD

**Issue by adamyytam** [signalapp/Signal-Android#11841]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

"I'm able send/receive message between individual user in one-to-one communication.  But in group chat, I cannot send/receive messages with anyone else in the group.  I tried to install the app on another phone using the same account.  But the same problem exists.  But when I use the same phone and register with another account, everything works just fine.  It seems to me I have problem with the account itself, not with the phone."

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/cae4e21811e6c2c3dbb6a0f2680647943f12a5c22aba8602cd1f5765fd91beab

**Comment by pcj7thirteen** [comment]
https://github.com/signalapp/Signal-Android/issues/11831#issuecomment-993939918

**Comment by greyson-signal** [comment]
We've made some significant changes to group processing in the last week or so (which is what your client was stuck processing). Let us know if the issue is still happening.
