### ISSUE TITLE
Support Feature Charges Incorrect Ammount on Upgrade

### ISSUE THREAD

**Issue by aeturnum** [signalapp/Signal-Android#11857]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you change your level of support within the month, Signal charges you for the entire amount, instead of just the difference between your previous level and the new one.

### Steps to reproduce
- Support at one level
- Choose Manage Subscription
- Select a higher level

**Actual result:** You are charged the full value of both levels.
**Expected result:** You are charged the full value of the first level, and the difference between the 1st and 2nd level.

### Screenshots
![Screenshot_20211221-180417_Google Play services](https://user-images.githubusercontent.com/2303837/147023166-13beb939-6580-4a82-96b6-0300ee38ecce.jpg)

### Device info
**Device:** Galaxy S21 5G
**Android version:** 12 (Nov 1, 2021)

**Signal version:** 5.28.5

### Link to debug log
https://debuglogs.org/71d01fe11d16beccc07a98c976ce7d9478b51ec0bcf847419ff26f92a245721e

**Comment by greyson-signal** [comment]
We use an anonymous credential system that allows users to make donations while not having any payment information tied to their account. Unfortunately this system also makes it so we can't do 'upgrade' pricing where you're only charged the difference -- we have to charge the full amount. 

I'll talk to our designers and see if there's a way we could make this more clear in the app. Thanks!

**Comment by greyson-signal** [comment]
I looked into it and it appears we *do* show a message indicating the full amount will be charged. Apologies if it was missed, but I'm going to consider this closed for now. Thanks!
![signal-2022-01-03-113839](https://user-images.githubusercontent.com/37311915/147956004-abf12341-a54a-48b9-b6a9-09403823f9b0.jpeg)
