### ISSUE TITLE
Alphanumeric PIN can't be entered

### ISSUE THREAD

**Issue by Woren** [signalapp/Signal-Android#11856]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Alphanumeric PIN can't be entered. There is one option to type it in or paste it.

### Steps to reproduce
- Wait for verify PIN dialog
- Click on Verify PIN
- Dialog appears but only with numbers to type in.

**Actual result:** Only numbers can be typed in
**Expected result:** Number and characters should be able to type in or paste

### Screenshots
See attached

### Device info
**Device:** Samsung Galaxy Note 20 Ultra
**Android version:** 11
**Signal version:** 5.28.5

Using Microsoft SwiftKey or Samsung keyboard with the same result.

Can be similar to iOS bug
https://github.com/signalapp/Signal-iOS/issues/4380

**Comment by Woren** [comment]
![Signal](https://user-images.githubusercontent.com/1436458/146955966-076e2b67-ef0a-442f-a27c-311032aacb83.jpg)

**Comment by UserX404** [comment]
I also have a numeric pin without issues. It may depend on your keyboard.
What happens when clicking on the marked areas?

<img src="https://user-images.githubusercontent.com/14954521/146979023-54797c2c-4ae8-46b7-a8b1-3285697fe80f.png" width="100" height="100"/>

**Comment by Woren** [comment]
The arrow is moving keyboard layout from right to left. I'm using "gestures" instead of typing every letter. Usually with one hand.
The keyboard icon is for choosing input method / "keyboard" (mentioned above - Samsung keyboard etc.).
This has no effect on reported issue.

**Comment by UserX404** [comment]
Ok
Just for testing - can you try an other keyboard e.g. Openboard.

**Comment by Woren** [comment]
Just workaround until this is resolved. As long as device is registered PIN can be changed in Settings - Account and then use only numeric PIN.

**Comment by feanil** [comment]
I'm seeing the same issue but would prefer to not switch away from an alphanumeric pin.

**Comment by feanil** [comment]
The issue was resolved for me by removing the pin and setting a new alphanumeric pin.  After that, the prompt allows for alphanumeric input again.

**Comment by jdchristensen** [comment]
Why was this closed as completed?  Signal still in some cases opens up a numeric keyboard when the user has an alphanumeric PIN, e.g. when transferring a Signal account from another device.

**Comment by jdchristensen** [comment]
I just tried again, and saw an option to "enter an alphanumeric PIN".  I guess I must have missed that the first time.

**Comment by pseudomonas** [comment]
I have just had this issue on moving to a new phone. When initially logging into Signal I got the  "enter an alphanumeric PIN" option. On the "We'll ask you from time to time" prompt, **no such option is present**.

**Comment by tmccombs** [comment]
This still happens for me, at least when I get the prompt to remind me of my pin. There is no option to enter an alphanumeric pin.
