### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by bitboy85** [signalapp/Signal-Android#11850]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
German dates like 24.12.2021 and ip addresses are underlined, formatted as phone number. Clicking on it allows to give this number a call.

### Steps to reproduce
Write a message like "24.12.2021" or "8.8.8.8"

**Actual result:** Input is formated like a phone number

**Expected result:** For date, there shouldn't be a formatting. For IP adress ether no formating or allow to open by browser

### Device info

**Device:** Samsung J5
**Android version:** 
**Signal version:** 5.28.5

**Comment by ShadyMedic** [comment]
Don't you normally put a space after the dots in the date? But yeah, it's a problem for IP addresses or longer decimal numbers.

**Comment by bitboy85** [comment]
No, there is no space in dates.

**Comment by greyson-signal** [comment]
Android uses the system-provided "linkifier" system, meaning that we should be using the same link-finding strategy as all of the other apps on your phone. On my device (which has a US-English locale), 24.12.2021 is not made into a link. So I'm gonna guess that it's a bug in your device's implementation, possibly specific to your locale.

(IP addresses *are* linkified for me, but they open in the browser, which I feel is expected)

**Comment by UserX404** [comment]
@greyson-signal 
I tested this on my Xperia XZ2c with LOS 18.1 by changing from de_DE to de_AT and en_US afterwards.
24.12.2021 becomes a clickable link for all this language settings.
When clicking, the system wants me to choose a caller app. (2 apps available on my phone)
As i'm correct this hasn't something to do with the used keyboard because the link is generated after sending the message and not during input stage.
