### ISSUE TITLE
Android → Android data transfer documentation issue. Portable hotspot causes transfer to fail.

### ISSUE THREAD

**Issue by JustFranz** [signalapp/Signal-Android#11858]
Official documentation https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_transfer

The instructions say to turn off VPN that might interfere with Wi-Fi Direct. It does not mention that Wi-Fi portable hotspot will interfere with Wi-Fi Direct. The transfer will just fail and Signal App does not give you a useful error message to let you know what went wrong.

Phone 1 that has data. Wi-Fi on and Bluetooth on.
Phone 2 no data, Wi-Fi on, Bluetooth on, portable hotspot on.

I do not know if phone 1 can have hotspot on and not have the transfer fail. I do not know if phone 1 being connected to hotspot of phone 2 has anything to do with it failing. I do not know if it would fail if phone 2 was connected to hotspot of phone 1.

All I know is that turning hotspot off on phone 2 fixed the issue. The app does not give a useful error. There is nothing in Signal documentation.

**Comment by greyson-signal** [comment]
Ah thank you for the info, we'll add this to our support documentation. Thanks!
