### ISSUE TITLE
Screen disabled and unresponsive after starting a call or receiving one.

### ISSUE THREAD

**Issue by dr3adl0rd** [signalapp/Signal-Android#11859]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When starting a call with a single contact or when receiving a call, the screen gets locked and disabled. None of the controls or screen functions are available until about 5 seconds after the call is established or dropped.
This is happening with Signal only, no other messanger is behaving like this. This causes some of the calls to go unanswered, and in other cases the call can't be dropped.

### Steps to reproduce
- Open signal for Android
- Select contact
- Tap call button on top
- Screen gets locked, and disabled. Power button, volume controls or screen taps are all disabled.
or
- Get somebody to call you
- Wait for a call
- As soon as the call is coming screen gets locked, and disabled. Power button, volume controls or screen taps are all disabled, there's no way to answer the call.
- On second attempt, the screen is still disabled, but the controls to anwer or decline are showing on the screen.

**Actual result:** Screen is locked and disabled and there's no way to answer the call or when calling to enable/disable mic or speaker or drop the call.
**Expected result:** Screen should be left exactly as it was when starting a call, or receiving a call. There should be no change to the phone state. The controls to answer/reject call should always be visible on the screen during a call in progress.

### Device info
**Device:** OnePlus Nord N10 5G
**Android version:** 11
**Signal version:** 5.28.5

### Link to debug log
https://debuglogs.org/ba9874798cada230071c183765d0c7532217b7aa31c4c737cf21b476406c1ff6

**Comment by cody-signal** [comment]
Hey there, definitely some weird stuff going on here. It looks like the app is restarting the screen and getting out of sync. This happens 100% of the time for both incoming and outgoing calls?

**Comment by dr3adl0rd** [comment]
Definitely 90% of the time on the first incoming call - second attempt is nearly always possible to answer. On outgoing calls, it's very random, but 8 out of 10 calls will have this issue, and the random part is not related to the contact.
