### ISSUE TITLE
Video quality mangled to unusable levels

### ISSUE THREAD

**Issue by I338** [signalapp/Signal-Android#11867]
I understand the need for image and video compression, but please at least make some option to respect the integrity of files and not modify them in any way (i.e. matching md5sum)

**Comment by Genis-Sage** [comment]
@I338 
I understand your frustration, but with the current amount of information given, it's nearly impossible for the signal to sort in your bug report
that's exactly, why they provide a bug report template

apart from that:
Signal devs want to keep the Github repo reserved for bug reports
and most probably, the behaviour you describe is currently as-designed
so a better place would be the [community forum](https://community.signalusers.org/)
(But I am not a Signal dev, just a happy Signal user, who tries to help a bit)

**Comment by greyson-signal** [comment]
Hi there, we're looking at adding some additional video compression options in the future, but we don't currently have any plans to be able to send media at original quality. Feel free to discuss in the forum. Thanks!
