### ISSUE TITLE
Sharing contact with birthday impossible

### ISSUE THREAD

**Issue by MartinX3** [signalapp/Signal-Android#11861]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm unable to share the contact birthday

### Steps to reproduce
- share the contact via the Google contacts app

**Actual result:** either a contact with name and phone number and no birthday or if I only choose the birthday the error "invalid contact" in signal.
**Expected result:** To share the birthday

### Screenshots

N/A

### Device info

**Device:** Sony Xperia XZ2
**Android version:** 11
**Signal version:** 5.28.5

### Link to debug log

N/A

**Comment by greyson-signal** [comment]
Hi there, we don't support sharing birthdays at this moment. I'd consider it a new feature, so I'll point you towards the [forum](https://community.signalusers.org/) where new features are discussed. Thanks!

**Comment by MartinX3** [comment]
Let's try.
https://community.signalusers.org/t/contact-share-doesnt-share-fields-like-birthday-or-homepage/3705/6
