### ISSUE TITLE
Reaction emojis do not scale up with font size

### ISSUE THREAD

**Issue by rgilton** [signalapp/Signal-Android#11863]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When one increases the font size, the emojis that display as 'reactions' on messages do not also scale up. This means that visually-impaired people cannot see the reaction emojis.

### Steps to reproduce

 - React to a message
 - Increase the font size

**Actual result:** Reaction emojis stay the same size
**Expected result:** Reaction emojis increase in size in proportion to the message font

### Screenshots

With "normal" font size:
![1](https://user-images.githubusercontent.com/1496/147406216-acb04266-6eac-4048-8d30-260aaccffd72.png)

With "extra large" font size:
![2](https://user-images.githubusercontent.com/1496/147406217-05ddcf99-b044-422f-b407-6acd49d5459f.png)

Note the reaction emoji is the same size in both screenshots.

**Comment by rgilton** [comment]
Yes, emojis still do not scale with font size.

**Comment by rgilton** [comment]
Yes, emojis still do not scale with font size.

**Comment by cody-signal** [comment]
Hey there, thanks for your suggestion. I've forwarded it onto our design folks.
