### ISSUE TITLE
@ Button to jump for both mentions and quotes/replies

### ISSUE THREAD

**Issue by AnisTaluqdar** [signalapp/Signal-Android#11864]
### Bug description
When we are outside in a group it is very difficult to find out who replies/quotes to us when we come back but for tags, it's counted in @ button and we can track it easily. When someone chats in a big group it's not he/she will tag every time but what they do they reply/quote each other and continue chatting. So, for trucking, the thread both should be counted in @ button.

### Steps to reproduce
- When someone tags you in the group it’s showing @ button and you can find the chat easily. But don't work with quotes/replies.

![Screenshot_2021-12-27-16-22-32-28.jpg](https://user-images.githubusercontent.com/41234183/147470478-9d0d3959-81a0-4316-82a6-f97dae1fbc8f.jpg) 

- But for telegram, it works for both quotes/replies and tags. 

![129018030-2632d512-22e6-4d74-bc96-128b3efa0360.jpg](https://user-images.githubusercontent.com/41234183/147470486-966315bc-6336-4fa0-8153-ed560fa7897d.jpg)

**Comment by Genis-Sage** [comment]
hey @AnisTaluqdar 
the Signal devs want to keep the Github repo reserved for Bug reports
when I understand your request correctly, you want a behavioral change...
so the [community forum](https://community.signalusers.org/) is the correct place to bring up feature requests
(But I am not a Signal dev, just a happy Signal user, who tries to help a bit)
