### ISSUE TITLE
When quoting a message and clicking on the selected quote doesn't redirect to the message

### ISSUE THREAD

**Issue by tiagogaspar8** [signalapp/Signal-Android#11869]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic (I believe it is not)

----------------------------------------

### Bug description
When quoting a message to reply to it, a bubble with the message selected will appear on top of the message box (1). When clicking on it (1), it should move the message list to the respective message, and highlight it (2).

### Steps to reproduce
- Select a message to reply by swiping right on top of one
- When the message is selected the keyboard should open and a bubble with chosen message appears
- Click on the bubble with the message above the keyboard
- Nothing happens

**Actual result:** 
No redirection/highlight is made on the selected message

**Expected result:** 
The message list should roll to the quoted message and highlight it.

### Screenshots
![signal-2021-12-28-12-29-35-332.jpg](https://user-images.githubusercontent.com/39808643/147566411-3a750bda-0f0b-4c94-80b5-52ae78f33bd3.jpg)

### Device info

**Device:** OnePlus 8
**Android version:** 11 (Oxygen OS 11.0.10.10.IN21BA)
**Signal version:** 5.28.8

### Link to debug log

I believe there are no logs I can't provide here, if there are please let me know!

**Comment by Genis-Sage** [comment]
hey @tiagogaspar8 
I tried out multiple other messengers, and not one of it jumped to the quoted message, while the new message is in draft state
so Signal behaves exactly as all other messengers

based on that, I assume, that the jump-to functionality is currently only implemented for sent/received messages, but not for draft messages, so Signal behaves as-designed
personally, I would go for a feature request in the [community forum](https://community.signalusers.org/)
(But I am not a Signal dev, just a happy Signal user, who tries to help a bit)

**Comment by tiagogaspar8** [comment]
Hi,

Actually in telegram this does happen, I can send a video if it is useful! 😁

Thanks.

**Comment by Genis-Sage** [comment]
@tiagogaspar8 
then it's 1 out of 6 messengers...(aside from Signal, I tested Threema, WhatsApp, Skype and FB Messenger)
I would go for a feature request in the community forum... and you can post the video there for better visualization

**Comment by greyson-signal** [comment]
My recommendation would be to continue this on the forum, thanks!

**Comment by tiagogaspar8** [comment]
Sorry for the delay in answering.
I see what you mean, I'll add this to the forums.
