### ISSUE TITLE
commercial use

### ISSUE THREAD

**Issue by Manvendra132** [signalapp/Signal-Android#11873]
i want to make a software like signal so, i wanted to modify it some places and provide the public for free, my question is can i make that closed source and just display ads on it and donot sell the software.

**Comment by iSaluki** [comment]
Signal uses the GPL3 license, which does allow commercial use. However one of the defining clauses of the GPL license is that you must disclose your source code, and it must be disclosed under the same license as the origin repository.

Please see https://github.com/signalapp/Signal-Android/blob/master/LICENSE for the full license.

I am not a lawyer, nor am I affiliated with Signal in any way. This is not legal advice.

**Comment by Manvendra132** [comment]
and if i disclose the source can i display the ads on it and there is no issue.

**Comment by mohe2015** [comment]
IANAL but I'm pretty sure you would be violating Signals https://signal.org/legal/ terms of use by displaying ads in the app. You could probably host your own server though but I assume you don't want that as you then would not be able to communicate with other users from the official app.

**Comment by Manvendra132** [comment]
> IANAL but I'm pretty sure you would be violating Signals https://signal.org/legal/ terms of use by displaying ads in the app. You could probably host your own server though but I assume you don't want that as you then would not be able to communicate with other users from the official app.

as i have said i will change some code in it and use it with my own brand name and i don't think it will be illegal if i use it's code as signal is open source and also if i display ads on it i will show it on my platform not on signal so, i don't think i am violating the terms and if i am please clear my doubts, thank you for the reply

**Comment by mohe2015** [comment]
> > IANAL but I'm pretty sure you would be violating Signals https://signal.org/legal/ terms of use by displaying ads in the app. You could probably host your own server though but I assume you don't want that as you then would not be able to communicate with other users from the official app.
> 
> as i have said i will change some code in it and use it with my own brand name and i don't think it will be illegal if i use it's code as signal is open source and also if i display ads on it i will show it on my platform not on signal so, i don't think i am violating the terms and if i am please clear my doubts, thank you for the reply

Yeah if you also change the name and use your own server I would agree. Still not a lawyer.

**Comment by Genis-Sage** [comment]
@Manvendra132 
as the Signal devs prefer to keep the Github repo for Bug reports only,
please use the community forum:
[community.signalusers.org](https://community.signalusers.org)

what is important, apart from the license questions:
You are not allowed to use the official signal servers. So you will definitely need own servers in the end.
