### ISSUE TITLE
Delete own notes for everyone - not just me

### ISSUE THREAD

**Issue by Bondarz** [signalapp/Signal-Android#11876]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, why is it not possible to delete notes for everyone in the Android version under "My notes"? With the Windows version, the notes can be deleted for everyone. When chatting with other people, I can delete the messages from Android and Windows. Problem therefore only affects own notes. I like to use these as quick storage. Thanks

### Screenshots
![Signal_Android](https://user-images.githubusercontent.com/19914015/147790668-9cd9e98b-5baa-43d7-b337-8faf374d73ca.png)
![Signal_Desktop](https://user-images.githubusercontent.com/19914015/147790669-380cee50-46cb-4aeb-8242-0acab1aa589e.png)

### Device info
**Device:** OnePlus Nord
**Android version:** 11
**Signal version:** 5.28.5
**Signal Windows:** 5.26.1

**Comment by Aeonitis** [comment]
Isn't everyone only you when making a Note to Self? There is only you, did I miss something?

Maybe you're concerned about the messages in the UI, not about missing functionality, right?

**Comment by Bondarz** [comment]
> 

Exactly. It's about the "Note to self" function.
I have now switched Signal to English for testing purposes.
I find it confusing that within the "Note to self" notes (Android) I can only delete a message with "delete for me". In the Windows app, under "Note to self", I can delete the notes with "Delete for everyone".

When I delete a note, it should be deletable from everywhere, not only with the windows version.
If I write to other users, I can also delete the texts directly from android.

**Comment by Tursko** [comment]
They just still haven't implemented it.
