### ISSUE TITLE
Dependency verification failed for configuration ':libsignal-service:protobufToolsLocator_protoc'

### ISSUE THREAD

**Issue by westonal** [signalapp/Signal-Android#11871]
With a fresh clone of 3d6ffe25f0ec00331f985b9f693e61b047f849b5, and `$./gradlew assemblePlayProdDebug` it resulted in:

```
Execution failed for task ':libsignal-service:generateProto'.
> Dependency verification failed for configuration ':libsignal-service:protobufToolsLocator_protoc'
  One artifact failed verification: protoc-3.10.0-osx-x86_64.exe (com.google.protobuf:protoc:3.10.0) from repository MavenRepo2
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.2/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  Open this report for more details: file:///Users/.../Signal-Android/build/reports/dependency-verification/at-1640806047420/dependency-verification-report.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 48s
```

Report HTML mentioned:
[at-1640806047420.zip](https://github.com/signalapp/Signal-Android/files/7790343/at-1640806047420.zip)

Which is just this:

![image](https://user-images.githubusercontent.com/6041352/147697393-00b7b8ec-a5be-48de-8479-0e0c8b225469.png)

**Comment by johanw666** [comment]
Yes, you need to add those files to gradle/verification-metadata.xml. For Windows I posted the hashes in https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-28-release/39659/243 , you seem to be using MacOS, I don't know the hashes there. To fix the build on all systems Mac en Windows hashes need to be added.

**Comment by westonal** [comment]
Two different versions of protoc as well. If they update that to be consistent, it would be good to get on to 3.18.0, as I think that will allow it to build on a M1 https://github.com/protocolbuffers/protobuf/issues/8062
