### ISSUE TITLE
APK checksum incorrect?

### ISSUE THREAD

**Issue by keith24** [signalapp/Signal-Android#11872]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The sha256 hash I get from the downloaded APK is different from the one on the website.  

### Steps to reproduce
- Download `Signal-Android-website-prod-universal-release-5.28.5.apk` by clicking the "Download" button on [https://signal.org/android/apk/](https://signal.org/android/apk/)
- `shasum -a 256 Signal-Android-website-prod-universal-release-5.28.5.apk`

**Actual result:** Downloaded version's checksum is: `b6406d136dd4b428c5c70bc1b9e58119ecad3f5a2a72f6337054055b16cbecfd`
**Expected result:** Checksum listed on the page: `29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26`

I tried downloading it again and got the same valid-looking apk with the same checksum.  Looks valid because: 

```sh
$ file Signal-Android-website-prod-universal-release-5.28.5.apk
Signal-Android-website-prod-universal-release-5.28.5.apk: Zip archive data, at least v?[0] to extract
```

So maybe the web page hasn't been updated?  Or have I been pwnd?

**Comment by westonal** [comment]
That is not the _checksum_, but the _fingerprint_. And as it relates to the signature, it does not change from build-to-build. See the link it takes you to for [verify](https://developer.android.com/studio/command-line/apksigner#usage-verify).

![image](https://user-images.githubusercontent.com/6041352/147714054-f0a257cd-2e43-4169-b843-cd2d4ae58287.png)
