### ISSUE TITLE
Voice notes don't respect SMS/MMS conversation status

### ISSUE THREAD

**Issue by ellenhp** [signalapp/Signal-Android#11880]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have a friend who likes voice notes and I'm having a lot of trouble sending them voice notes over the cellular network with Signal as my default SMS app. My friend is a signal user, so the app always sends the voice messages over signal. Normally that wouldn't be a problem but this friend does not check it so it is kind of a problem.

### Steps to reproduce
- Set Signal as your default SMS app
- Go to a conversation with a phone number that *does* have a Signal account
- Type out a message and long-press the send button and select "Insecure SMS".
- Press and hold the voice note button, say a message then release it.
**Actual result:** The voice message sends over the signal network.
**Expected result:** The voice message sends over the cellular network as an MMS.

### Device info

**Device:** Pixel 4a
**Android version:** 11 I think
**Signal version:** 5.28.5

### Notes

From what I understand the ability to send SMS/MMS messages to Signal users from within the app has been pretty controversial and I can't claim to have any insight one way or the other about whether it's correct behavior to send an insecure message containing data from the microphone with what could be an accidental tap. But what I can say with certainty is that I can't use Signal as a default SMS app anymore because of this issue which is a shame because it's really convenient to have everything inside of Signal :( It doesn't need to be convenient to send voice notes to my SMS-conversation friends but I do need the ability to do it somehow using an external voice recorder app or something.

**Comment by alex-signal** [comment]
I'm not sure what the issue here is, do you want the voice notes to *always* send over SMS? Is there a reason you can't send them via Signal, given both you and the recipient use it?

**Comment by ellenhp** [comment]
> do you want the voice notes to _always_ send over SMS?

Definitely not. I was just thinking that there would be a way to send them over SMS if the rest of the conversation is set to go over SMS, but there isn't. They always go over the signal network.

> Is there a reason you can't send them via Signal, given both you and the recipient use it?

I was really hoping I could meet this person where they are because it's kinda hard to make new friends this time of year where I live but I guess I could try and get them to check Signal more often.
