### ISSUE TITLE
Subtexts to images is not possible anymore on Android version

### ISSUE THREAD

**Issue by hunzel** [signalapp/Signal-Android#11882]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is not possible anymore to write Subtexts to specific images when sending more than one image per message. In iOS Version it still exists. Android had this somewhen in the past too, but the Button disappeared.

### Steps to reproduce
- Press blue X to open attachment menu
- go to gallery
- select several image to send to someone
- in the next screen you can enter a text for the message

**Actual result:** There is only the possibility to write one text for the message for all the selected images.
**Expected result:** There should be a button to add specific texts to single images of all the selected images to be sent.

### Device info

**Device:** Samsung Galaxy S20 FE 5G / Samsung Galaxy S7
**Android version:** 11 (security patch 2021-12-01
**Signal version:** 5.28.5 (button has been missing for a few months now!)

**Comment by westonal** [comment]
Unfortunately not a bug. It was deliberately removed.

**Comment by hunzel** [comment]
> Unfortunately not a bug. It was deliberately removed.

Why is that and what chance could there be to get it back? IOS has it, why have differences between those systems?

> They are called "Captions" by the way.

Sorry, not my first language. But thanks for the info!

**Comment by westonal** [comment]
> Why is that and what chance could there be to get it back?

Best thing would be to start a topic on the forum https://community.signalusers.org/

One reason why was certainly that it was deemed to be under used, so speaking up about it's removal on there would show that it's being missed.

> IOS has it, why have differences between those systems?

I am surprised at that, but I don't have an iOs device to verify. It's not uncommon for feature sets to vary though as it requires more effort and planning to keep them in sync.
