### ISSUE TITLE
SMS never sends on WiFi without cell service

### ISSUE THREAD

**Issue by bdm310** [signalapp/Signal-Android#11898]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS never sends on WiFi without cell service.

### Steps to reproduce
- Disconnect from mobile network or be in an area without cell service
- Connect to WiFi
- Send a regular SMS

**Actual result:** SMS spins forever.
**Expected result:** SMS should send if "WiFi Compatibility" mode is enabled.

### Device info
**Device:** Google Pixel 3
**Android version:** Lineage 18.1
**Signal version:** Versions after settings refactor 5/12/2021

### Link to debug log
https://debuglogs.org/925486088c4a32fc0f979ece9a9a06a4eb8334404be332ff525592a2ca886c8f

There was a settings framework refactor that neglected to link up the wifi compatibility setting switch. You can see the attached debug log shows the setting as disabled even though I can assure you it's enabled. Pull request inbound with a fix.

**Comment by bdm310** [comment]
The original settings refactor: https://github.com/signalapp/Signal-Android/commit/f2d5ea03919933e7c02f6d15a379e1372c9bfae6

**Comment by Tursko** [comment]
I actually recall someone making an issue earlier last year about something similar. They were on Fi and previously had no issue sending SMS message over wifi. But after an upgrade (assuming it was the settings refactor) they weren't able to do so anymore, so they switched their default SMS back to Google Messages.

**Comment by bdm310** [comment]
I believe you're referring to https://github.com/signalapp/Signal-Android/issues/10233
There's not enough info there to say if it's the same problem and no debug logs posted.

**Comment by Tursko** [comment]
> I believe you're referring to https://github.com/signalapp/Signal-Android/issues/10233
> There's not enough info there to say if it's the same problem and no debug logs posted.

It was a different one because the person was directly complaining about wifi texting on fi.
