### ISSUE TITLE
Support system claims Google Store latest version is not the latest version.

### ISSUE THREAD

**Issue by dscotese** [signalapp/Signal-Android#11895]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
support@signal.org replies to my emails with "... Hi there, This is not the latest version of Signal. ...".  The version reported by Signal on my Android (5.28.10) matches the version reported at the Google Store (5.28.10).

### Steps to reproduce
- Submit a support request from an Android using version 5.28.10 of the app by visiting Settings | Help | Contact Us.
- Note that support@signal.org replies as described above.

### Device info

**Device:** Samsung Galaxy 7
**Android version:** 8.0.0
**Signal version:** 5.28.10

### Link to debug log
[Debug log
](https://debuglogs.org/110faea2c1976fb8a52d18cb10c54184635343ca0fa8881f7a92c6bd6a72b1c8)

**Comment by cody-signal** [comment]
I've let them know. Closing this since it's unrelated to the app, but rest assured they're on it.
