### ISSUE TITLE
"Chat Color" changes the wrong bubble (Android and PC)

### ISSUE THREAD

**Issue by cavemank1** [signalapp/Signal-Android#11894]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This started sometime last year on on both Android and Desktop versions. At some point, the option to change a contact's color stopped changing the contact's message bubbles and started changing mine.  This is backwards.  I can now no longer identify my conversations by color.  I have sent several emails over the last few months trying to indicate this bug, but have not received any responses.  Maybe submitting here will get this resolved faster?

This issue has been unbelievably frustrating and just a constant pain. I really like signal, but this is getting to be a deal-killer since I am constantly having to figure out who I'm conversing with or who said what, since my brain is instantly drawn to the colored text which I assume would be the person I'm conversing with.  And far from being something I'm starting to acclimate to, it's making me more frustrated as time goes on because it seems like such an obvious oversight and a simple fix.  Obviously I don't need *my* text highlighted in a color, as I know what I just wrote. But I do need the ability to quickly see the text of the person I'm conversing with. 

### Steps to reproduce

Happens in any chat.  Seems like someone literally coded a setting for the wrong thing?  Should be easy enough to fix.   At first I thought it was just my machine, so I un-installed signal and then re-installed it.   That didn't fix the issue.  I then started encountering the issue on desktop as well (or maybe it was Desktop first, it's been so long I can't remember) and it seemed that the issue was impacting multiple platforms.  I've since done a phone wipe and a PC format and the issue persists.  I've experienced the same thing on multiple machines, so it does seem that it's an issue with the app itself. 

**Actual result:** 
My chat messaged get the color that should be for my contact

**Expected result:** Changing chat color should change my contact's messages so I can quickly identify and read them. 

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by cody-signal** [comment]
https://community.signalusers.org/t/discussion-about-the-new-color-changes/33048

**Comment by cavemank1** [comment]
Cody, Hi, it doesn't indicate when this will be resolved.  Do you guys have an ETA?

**Comment by cavemank1** [comment]
Based on that link, it seems like dozens and dozens of people are logging it as a bug.  I can see how a change like that might make sense in a brainstorming session, but when you have tons of real users logging it as a bug almost a year after implementation, I don't think it's reasonable to dismiss that with the "it's not a bug, it's a feature" cliche. 

It is quite clear from the feedback that users are just as frustrated as I am by this change which is so obviously flawed we all separately concluded it must be a bug.  It's not a matter of mere aesthetic preference; there is volumes of feedback with users articulating exactly why it is nonsensical.  The most obvious of course is that no one cares what color _their_ text is, since that's not what's important in a conversation.  The important thing is the text of the person you are communicating with, and that's what should be highlighted. 

It feels like the devs are digging their heels in here for reasons that don't make sense.  Ultimately, it's your app, you guys can do whatever you want, but to the extent that you care about feedback from your users, this seems like a silly thing to brush off.
