### ISSUE TITLE
Improvement: periodically check/re-register GCM

### ISSUE THREAD

**Issue by TheLastGimbus** [signalapp/Signal-Android#11905]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I use MicroG on my device. I had few situations where I had to re-install it, loosing all it's data and registered GCM/FCM connections. After that, Signal isn't registered for GCM and I don't receive notifications. I used to disable and re-enable "Signal messages and calls" in Settings->Privacy->Advanced ; but that doesn't do the job now :(

My friend with normal Huawei phone also had problem with notifications, and I suspect it may be the same thing - failing to register for GCM

Signal could periodically (WorkManager, randomly at startup, or whatever) check if it's properly registered with GCM, and if not, re-register again - that would be awesome, and would make it more robust.

### Steps to reproduce
- Have a de-googled phone with microG
- Install Signal properly, making sure it registered
- be happy with notifications
- clear microG's data
- No notifications, no request to register :(

**Actual result:** No re-register
**Expected result:** I mean it is expected, but *could* re-register again :)

### Screenshots
- Not needed

### Device info

**Device:** Google Pixel (sailfish)
**Android version:** 10 (LineageOS 17.1 + microG)
**Signal version:** 5.29.3

### Link to debug log

- Not needed

**Comment by TheLastGimbus** [comment]
Yes dear bot, here us 2 meet again. It is still, relevant, indeed...

**Comment by hiqua** [comment]
It registered for me again after an update.
