### ISSUE TITLE
Can't send videos, images or stickers with mobile data

### ISSUE THREAD

**Issue by Minibus93** [signalapp/Signal-Android#11902]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't send videos, images or stickers with mobile data.
it only works with wifi.
please note that mobile data works fine in every other app, only signal has this problem.

### Steps to reproduce
- turn off wifi, turn on mobile data
- try to send a sticker or a video or an image. Or try to download a video, sticker or image with mobile data
- that reproduce the bug
- 
**Expected result:** image/video/sticker would send with mobile data & 

### Screenshots

![signal-2022-01-16-114852](https://user-images.githubusercontent.com/73554423/149656897-9196e2c8-d80e-4d31-bfb2-d12d9cd24de6.jpeg)

### Device info

**Device:** Xiaomi Mi 10 (umi_eea)
**Android version:** 11 (V12.5.5.0.RJBEUXM, RKQ1.200826.002 test-keys)
**Signal version:** 5.28.10

### Link to debug log
https://debuglogs.org/a4186683dc44d0c7f8697a14d2049798afb0e7cd2985cdfdde8ed13d3ef08656

**Comment by DonPicciotto** [comment]
Pretty sure it's related to this https://github.com/signalapp/Signal-Android/issues/11839

**Comment by Minibus93** [comment]
> Pretty sure it's related to this https://github.com/signalapp/Signal-Android/issues/11839

It is.

I'm with ho. Mobile too
