### ISSUE TITLE
Build Debug Apk Error : Task :Signal-Android:compilePlayProdDebugKotlin

### ISSUE THREAD

**Issue by afDursun** [signalapp/Signal-Android#11907]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Error while outputting Debug Apk. > Task :Signal-Android:compilePlayProdDebugKotlin
I downloaded the project from github. I opened it with Android Studio. I wanted to build a Debug APK. But below errors occurred

### Screenshots
![s2](https://user-images.githubusercontent.com/17432551/150008716-a60d5bf1-c101-42f9-a404-21c6b8d4e9bb.PNG)

### Device info

**Device:** Windows 10-Android Studio 2020.3
**Android version:** Output Debug Apk
**Signal version:** master

`e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\avatar\picker\AvatarPickerFragment.kt: (54, 46): Unresolved reference: groupId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\avatar\picker\AvatarPickerFragment.kt: (56, 98): Unresolved reference: isNewGroup
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\app\AppSettingsActivity.kt: (39, 12): Unresolved reference: setStartCategoryIndex
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\app\privacy\expire\ExpireTimerSettingsFragment.kt: (135, 33): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\app\privacy\expire\ExpireTimerSettingsFragment.kt: (137, 34): Unresolved reference: initialValue
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\ConversationSettingsFragment.kt: (111, 26): Unresolved reference: groupId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\ConversationSettingsFragment.kt: (114, 28): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\ConversationSettingsFragment.kt: (168, 26): Unresolved reference: groupId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\ConversationSettingsFragment.kt: (371, 14): Unresolved reference: setInitialValue
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\ConversationSettingsFragment.kt: (375, 25): Overload resolution ambiguity: 
public open fun navigate(p0: Uri): Unit defined in androidx.navigation.NavController
public open fun navigate(p0: NavDirections): Unit defined in androidx.navigation.NavController
public open fun navigate(p0: Int): Unit defined in androidx.navigation.NavController
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\permissions\PermissionsSettingsFragment.kt: (26, 63): Unresolved reference: groupId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\components\settings\conversation\sounds\SoundsAndNotificationsSettingsFragment.kt: (28, 99): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\ChatColorSelectionFragment.kt: (20, 81): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\ChatColorSelectionFragment.kt: (102, 80): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\ChatColorSelectionFragment.kt: (103, 10): Unresolved reference: setChatColorId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\ChatColorSelectionFragment.kt: (105, 42): Overload resolution ambiguity: 
public open fun navigate(p0: Uri): Unit defined in androidx.navigation.NavController
public open fun navigate(p0: NavDirections): Unit defined in androidx.navigation.NavController
public open fun navigate(p0: Int): Unit defined in androidx.navigation.NavController
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\ChatColorSelectionFragment.kt: (117, 131): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\custom\CustomChatColorCreatorPageFragment.kt: (54, 132): Unresolved reference: recipientId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\custom\CustomChatColorCreatorPageFragment.kt: (56, 152): Unresolved reference: chatColorId
e: C:\Users\User\Desktop\Signal-Android-c\app\src\main\java\org\thoughtcrime\securesms\conversation\colors\ui\custom\CustomChatColorCreatorPageFragment.kt: (56, 171): Unresolved reference: recipientId
`

**Comment by greyson-signal** [comment]
Hi there, we only use Github for bugs. For development assistance, please use [the forum](https://community.signalusers.org/). My guess would be something with Windows and protoc though.
