### ISSUE TITLE
Reply to a disappeared message keeps the message content visible in a preview

### ISSUE THREAD

**Issue by dedozet** [signalapp/Signal-Android#11913]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Replies to a message that was set to disappear still show the disappeared message's contents in its preview

### Steps to reproduce
- set the disappearing messages timer to 30 seconds
- send user B a message
- turn disappearing messages off
- user B replies to the message
- wait for the original message to disappear

**Actual result:** the reply still shows a preview of the original message's content
**Expected result:** the reply shouldn't keep the original message visible

### Screenshots

![SmartSelect_20220121-011639_Signal](https://user-images.githubusercontent.com/93612074/150443254-e8d399c5-ff95-4a14-991f-4ece215112c7.jpg)
![SmartSelect_20220121-011705_Signal](https://user-images.githubusercontent.com/93612074/150443260-6761ab8c-d509-4ce6-953c-a860399bbb98.jpg)

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** 5.28.10

### Link to debug log
Not needed

**Comment by greyson-signal** [comment]
Hi there, this is actually intended behavior. We consider quoting to be the equivalent of copy-paste. Thanks!

**Comment by jondo** [comment]
This was not what me and my friends expected 🫤
