### ISSUE TITLE
Signal uses too much space on internal memory

### ISSUE THREAD

**Issue by lcaouen** [signalapp/Signal-Android#11919]
### Bug description
After 6 months of use, Signal takes 1 GB of space on internal memory.
A solution must be found to reduce this space otherwise Signal could only be used on expensive android phones.
Could you add an option to store the data on sd card instead of internal memory ?

### Steps to reproduce
- send messages with photos and videos

**Actual result:** 1 GB on internal memory
**Expected result:** 300 MB on internal memory

### Screenshots
![Screenshot_20220123-140818](https://user-images.githubusercontent.com/3267663/150681533-773b0146-038d-47ec-a042-341924de522b.png)

### Device info
**Device:** Xiaomi MI A1
**Android version:** 9
**Signal version:** 5.28.10

**Comment by UserX404** [comment]
Not sure what's your problem here.
All media received and sent are stored locally on your device within a encrypted database. This mainly results due to it's 'your' data and not stored in the cloud. You are capable to manage the consumption by your own.
E.g. by reduce the maximum conversation length, enable disapearing messages or by checking the storage consumtpion within the app.
https://support.signal.org/hc/en-us/articles/360049673331-Storage-Management#android

**Comment by lcaouen** [comment]
But I want to keep my messages and media. I don't want to delete them.
I want to keep an history and being able to search an old message.

**Comment by UserX404** [comment]
When you run out of memory you have to delete something or expand capacity. That's the common use case with every device.
What you are requesting (sd export) is a feature request and should be discussed in the [forum](https://community.signalusers.org/).
GH is only used as bug tracker.

**Comment by greyson-signal** [comment]
@lcaouen If you want to keep all of your media and message, they will indeed take up space. Other apps solve this by storing your messages and media on their servers, which we do not do for obvious privacy reasons.

If you'd like to make some more space, inside of Signal you can go to Settings > Data and storage > Manage storage > Review storage to sort media by size and delete large items. There's also some other tools there to limit the amount of time you keep messages and stuff. Hope that helps!
