### ISSUE TITLE
After attaching a photo to a regular SMS message, the send button is blue, indicating it’s encrypted

### ISSUE THREAD

**Issue by akilou** [signalapp/Signal-Android#11916]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After I attach an image to a regular SMS conversation, on the page where I have the opportunity to edit the image, add a caption, or send it, the send button at the bottom-right is blue which, in all other circumstances in Signal, indicates that I’m sending an encrypted Signal message (as opposed to the gray send butotn with an unlock icon when sending a regular unencrypted SMS

### Steps to reproduce
- Attach an image to an SMS(MMS) thread
-   See blue send button

**Actual result:** Button is blue (indicating a secure message)
**Expected result:** Button should be grey (indicating an insecure mms message)

### Screenshots
![b35dccc041565912e73381e16bea5985a85dcfe4_2_225x500](https://user-images.githubusercontent.com/4934676/150578732-49ea5672-f2f2-4221-abc1-987d1a507173.jpeg)

### Device info

**Device:** Google Pixel 6
**Android version:** 12
**Signal version:** 5.29.4

### Link to debug log
Not needed.

**Comment by akilou** [comment]
I'm new to Github. I'm only here because I was referred from the other message board. I'm doing my best to raise a security issue. If there's a template, I'll fill it out if it'll help. Can you point me to it?

**Comment by Tursko** [comment]
> I'm new to Github. I'm only here because I was referred from the other message board. I'm doing my best to raise a security issue. If there's a template, I'll fill it out if it'll help. Can you point me to it?

The template is displayed when you start the issue. Looks like you deleted it when you pasted your description of the issue.

**Comment by akilou** [comment]
Well then I have a bug-reporting bug to report. I was able to reproduce it.

I clicked 'new issue' when I was not signed in to Github. The sign-in dialogue popped up, I signed in, and was brought to a blank "new issue" message with an empty Title field and and empty message field. I never saw a template.

**Comment by Tursko** [comment]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I posted this to the Signal users Community and they told me to post it here. Copying verbatim.
After I attach an image to a regular SMS conversation, on the page where I have the opportunity to edit the image, add a caption, or send it, the send button at the bottom-right is blue which, in all other circumstances in Signal, indicates that I’m sending an encrypted Signal message (as opposed to the gray send button with an unlock icon when sending a regular unencrypted SMS).

### Steps to reproduce
- Attach an image to an SMS thread
- See blue send button

**Actual result:** Button is blue (indicating a secure message)
**Expected result:** Button should be grey (indicating an insecure mms message)

### Screenshots

![image](https://user-images.githubusercontent.com/18274896/150567676-9bfd192b-215d-453b-80de-f596a22dcbd3.png)


### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

**Comment by Tursko** [comment]
I have completed some of the template for you. Edit your original post and copy paste what i wrote above :)

**Comment by AllanBlanchard** [comment]
Same problem here on a Pixel 5. I don't know if it isbthe same for the OP, but sending the message also instantly fails without useful information about the failure (the application just indicates that sending the message failed).

**Comment by Tursko** [comment]
Still a valid issue.

**Comment by akilou** [comment]
yeah, this still isn't fixed. I see it every time I send a photo over SMS (MMS). Frankly it's a security issue, as it indicates that I'm sending an encrypted message when I'm not, and it seems like a relatively easy thing to fix, change the button color from blue to gray. Not sure why this hasn't been fixed yet.

And @AllanBlanchard, no my messaged do go through, I'm not having that problem. It's literally just the color of the button.

**Comment by alex-signal** [comment]
Looks like this got missed when we rewrote the media share flows late last year. We're tracking this, and you're right, it should be an easy fix.

**Comment by Tursko** [comment]
https://github.com/signalapp/Signal-Android/commit/d865b5d7b5433d78e1116cec70aa3c5aebd258ae
