### ISSUE TITLE
Background colour cannot return to default setting

### ISSUE THREAD

**Issue by ellwiii** [signalapp/Signal-Android#11915]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The default colour of a chat background is white. After changing it to dark green, later I wanted to switch it back to the default one. After clicking "reset background" nothing changed, the colour stayed the same - dark green.

### Steps to reproduce
- change default colour of a chats background to any other
- go to chat settings and click "reset background" buton
- look at the preview or go back to the chat

**Actual result:** Chat colour did not change back to the default one - it stayed green
**Expected result:** Chat colour goes back to the default one - it switched to white

### Screenshots
![InkedScreen_Recording_20220120-192002_Signal_Moment2](https://user-images.githubusercontent.com/44124878/150491416-5620b8a2-87b7-4bb1-8c7c-cdd6dc11de74.jpg)
![Screen_Recording_20220120-192002_Signal_Moment1](https://user-images.githubusercontent.com/44124878/150491437-e69f115a-8bd9-474b-b3af-73a42af43993.jpg)
![InkedScreen_Recording_20220120-192002_Signal_Moment_LI](https://user-images.githubusercontent.com/44124878/150491450-826cc4b7-8ea2-4a5c-a655-32c5bafe1903.jpg)

### Device info

**Device:** Manufacturer Samsung Galaxy S9+
**Android version:** 10
**Signal version:** 5.28.10

**Comment by greyson-signal** [comment]
There's two wallpapers: (1) the chat-specific wallpaper and (2) the global default wallpaper.

If you set the global default wallpaper to green, and you reset the chat-specific wallpaper to default, it will stay green. That's because green is considered the default.

If you'd like to reset or change the global default wallpaper, you can go to Settings > Appearance > Chat color & wallpaper > Reset wallpapers.

**Comment by ldoench** [comment]
It was possible to reset the individual chat background via the global setting, but I could not reset it in the chat specific screen, where I set it. This is an UX problem, because without finding this ticket it is not clear to the user where to reset the chat color
