### ISSUE TITLE
android 5.28.10 on 4G

### ISSUE THREAD

**Issue by cthompstone** [signalapp/Signal-Android#11912]
Hi I have 2 people with android 10 rugged phones (Oukitel)  and signal 5.28.10 and signal does not send or receive when on mobile data.
a 3rd phone (same make model) with 5.25.x works perfectly.
The 5.28.10 phones have to be on wifi, then signal will send and receive messages fine.
Anyone else had this?

Thanks
Chris

**Comment by strugee** [comment]
Hi @cthompstone, thanks for using Signal. Unfortunately, you seem to be in the wrong place - GitHub issues is not a discussion forum. Please either edit your issue so that it uses the issue template, or close this issue and post on [the forums](https://community.signalusers.org/t/) instead. Thanks!

**Comment by cthompstone** [comment]
Thank-you stale bot,
i only just find out that:
It turns out that EE (the UK mobile network operator I use) sets new accounts to a 'under 12 years' filter for data.
But more than just this, they recently added signal to the under 12 ban list.
Interestingly Whatapp is not on the under 12 blacklist / ban list.
I only discovered this by accident when I went to signal.org website on the phones with no wifi enabled and it would not load.
Thanks
Chris
