### ISSUE TITLE
Chats can't be opened without camera

### ISSUE THREAD

**Issue by werdck** [signalapp/Signal-Android#11921]
When I hardware-disable the camera of my device, signal can be still opened and I receive messages like normal, but when I try opening a chat by any means (tapping on it on Signal's overview screen or via notification), Signal hangs. It doesn't crash, but becomes unresponsive and switches to a completely black screen.

This behavior disappears after enabling the cameras again and restarting my device. I just don't want my camera to be enabled, and any other app, including the camera apps I use, can handle an inaccessible camera device.

**Comment by alex-signal** [comment]
Could you please attach a debug log? (Settings->Help->Submit Debug Log)

**Comment by werdck** [comment]
Done, it's at https://debuglogs.org/9ac10cb4c26e56047e0bd4d1d64894a8cb1fbeeb0ed988f80398511751b43409
