### ISSUE TITLE
Restore or decryp my Signal app data?

### ISSUE THREAD

**Issue by empty2k** [signalapp/Signal-Android#11924]
My Oneplus 6 unfortunately stopped booting, so I had to reset my device. 
Unfortunately, I couldn't backup Signal via the official method because I couldn't get into the OS anymore. 
However, I was able to backup the data partition via TWRP.
I tried to copy back all files from the data\data\org.thoughtcrime.securesms folder. I have set the permissions accordingly OCTAL: 0771 and the owner to the appropriate group: "10217 - u0_a217" (I assume that this group is not static)
However, when trying to restart Signal, Signal crashes.
Unfortunately, I re-enabled Signal on the newly installed Android. Before I had copied the files back.

How can I decrypt the data from app_parts\ or best integrate it back into Signal?
If more information is needed, I will be happy to supply it.
I hope someone can help me.

Info:
Device: OnePlus 6
OS: Android 11
Root via Magisk

**Comment by strugee** [comment]
Hi @empty2k, this question isn't really appropriate for the issue tracker, which is for bug reports only. I suggest posting on the forum: https://community.signalusers.org/

**Comment by empty2k** [comment]
Oh sorry! thx for the hint.
