### ISSUE TITLE
back button goes back too far on my spesific device

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11928]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
the back button on my device jumps me back out of the conversation to the conversation list, while on devices of others it mearly removes focus from the input field first.

---

For comparison:
1. Open a chat
2. Press on the input field (your keyboard opens)
3. Press the back button

On the 3rd step your keyboard closed, but the chat is still on your screen. You simply undid the action of giving ficus to the input field.

Now let’s do it again but instead if the text keyboard we open a different keyboard or picker:

1. Open a chat
2. Press on either the attachment button, or the emoji button, or the gif button or the sticker button (doesn’t matter which one). (The menu opens)
3. Press the back button

This time on my device I leave the chat and go back to the overview. This is not consistent with how the text keyboard gets dismissed.

Every step back should undo only 1 action. Opening the attachment menu or emoji keyboard is an action, and so it makes sense the back button only closes that keyboard rsther than closing the whole chat.

Why this matters:

- Doing this wrong caises unconcious frustration bevause muscle memory is hard to learn for this.
- It’s even more frustrating because you might be used to something different from other Android apps.

The back button should always first dismiss any opened menu/keyboard and not immediatly close the whole chat.

Another user (Herohtar) tried to reproduce this on a Pixel 5 and for them the nack button dismisses the emoji keyboard and/or attachement picker without closing the conversation, so the issue appears to be device spesific.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0.0
**Signal version:** 5.30.1

### Link to debug log

https://debuglogs.org/c1ac1d5a7b8af2deffbaa2293e5128276053771f8a37063f5555cb2cc08a218a

**Comment by Sesmicwastaken** [comment]
Same happens with me but not sure if it's that big of a deal as I'm kinda used to it now lol


Device: Oneplus Nord
Android: 12 (Pixel Experience Custom rom)

**Comment by AlertSubject** [comment]
Can reproduce on the oneplus 9 Pro running android 12 and the latest signal beta

**Comment by Tursko** [comment]
> Another user (Herohtar) tried to reproduce this on a Pixel 5 and for them the nack button dismisses the emoji keyboard and/or attachement picker without closing the conversation, so the issue appears to be device spesific.

My Pixel 5 does the same thing.

**Comment by aeroechelon** [comment]
![image](https://user-images.githubusercontent.com/2360095/151463698-3f016244-0ba6-4bdf-b694-0ba586b6c5ba.png)

To be clear you're referring to system Back button and not the in-app Up button when referring to the Back button correct?

**Comment by Meteor0id** [comment]
I am referring to the system back button.

**Comment by daniele-athome** [comment]
I can confirm it on Moto X4 running Android 9, Signal latest master. Normal keyboard is handled correctly (probably by the OS), other popups (emojis, media) cause the back button to immediately close the chat activity.

**Comment by alex-signal** [comment]
Yeah I think I broke something when I wrapped up ConversationActivity into a fragment. I'm going to TAL at this over the next few (business) days.

**Comment by Sesmicwastaken** [comment]
Fixed on the latest beta 
Thanks! :D

**Comment by Meteor0id** [comment]
Fixed with https://github.com/signalapp/Signal-Android/commit/4de88072976dd678db74405a01ab4615f14a0ef1
