### ISSUE TITLE
Message backups to Nextcloud External Storage fail

### ISSUE THREAD

**Issue by dustojnikhummer** [signalapp/Signal-Android#11920]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android 11
Signal uses the standard Android's file manager to select backup destination. While it can't see OneDrive, SMB etc, I noticed it can see my Nextcloud. I can select the folder, but when it tries to create the backup it fails.

### Steps to reproduce
- Select your Nextcloud folder that uses External Storage (in my case SMB) as destination for backups
- Try to create backup manually by tapping "Create backup"

**Actual result:** a .tmp file with size of 0KB gets created on the storage server. Notification of "Creating Backup" appears on the phone for a few seconds. The file isn't visible to Nextcloud, I can see it by navigating to that server over SMB (my nextcloud setup uses external SMB storage). Saving to internal Nextcloud storage works!
**Expected result:** Full backup file will be generated on the server.

### Screenshots

![Screenshot 2022-01-24 113356](https://user-images.githubusercontent.com/3268305/150767219-7921ad1d-4c77-499f-a90e-c405fdd1be01.png)

### Device info
**Device:** Xiaomi Poco X3, MIUI 12.5.4
**Android version:** 11
**Signal version:** 5.28.10

### Link to debug log
https://debuglogs.org/1cfcc3394dbc3ecdc12f8fda88946da33e94008f9c29c5e88024b27839e9b942

**Comment by UserX404** [comment]
@dustojnikhummer
Thats not a signal issue so please close this issue.
During Backup a tmp file is created an renamed after backup is complete.
It's offtopic but i would recomend another workflow:
Let signal backup to its default dir (internal mem) and configure nextcloud android app auto-upload the backup dir.

**Comment by dustojnikhummer** [comment]
> @dustojnikhummer Thats not a signal issue so please close this issue. During Backup a tmp file is created and renamed after backup is complete. It's offtopic but i would recomend another workflow: Let signal backup to its default dir (internal mem) and configure nextcloud android app auto-upload the backup dir.

I wasn't aware Netxcloud can auto backup a single folder. That is a functional workaround.

Still wish Signal had a native way to upload to a cloud storage of my choice, as GDrive and OneDrive apps don't have the functionality to autobackup a folder.
