### ISSUE TITLE
Signal synchronizing names using contact info without permission

### ISSUE THREAD

**Issue by sdyyyy** [signalapp/Signal-Android#11925]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I accidentally once gave signal permissions to all my contacts, so all the names on signal synchronized with the names in my contacts, right after that i switched off the permission and restarted signal and thought the issue was gonna go away, but it didn't change the names back. Didn't think much of it and thought after update It's gonna be resolved, but couple of updates later and it still remains the same. Also i just remembered, that when i search by their names, their phone numbers are also still there, could it be that once signal synchronized all the data, that it just keeps it forever like that even without the given permission?

### Steps to reproduce
- Give signal permissions to contacts
- Open signal and see that all the names got synchronized
- Exit signal and switch off the permisions
- Turn signal on
- see the names

**Actual result:** Names remain synchronized from contacts.
**Expected result:** Names changed back to what the users named themselves after creating signal.

### Device info

**Device:** Samsung Galaxy a5 2016
**Android version:** 7.0
**Signal version:** 5.28.10

**Comment by sellth** [comment]
Signal copies contact info locally into a separate "account". Names and phone numbers [are not](https://support.signal.org/hc/en-us/articles/360007061452-Does-Signal-send-my-number-to-my-contacts-) [synchronised](https://signal.org/blog/private-contact-discovery/) with Signal's servers at all. To delete this info from your app do this: Android Settings > Accounts > Signal > Remove Account

Reference: https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts#android_contacts_refresh

**Comment by sdyyyy** [comment]
> 

Thanks!
