### ISSUE TITLE
Can't forward SMS to number not in contacts/rercent messages

### ISSUE THREAD

**Issue by nalyDylan** [signalapp/Signal-Android#11937]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Forwarding SMS only allows you to select from contacts/numbers you've previously messaged and doesn't allow you to initiate a conversation with a forwarded SMS (in particular, I was trying to forward an unsolicited political SMS to the FCC's 7726 "SPAM" service)

### Steps to reproduce
- Select a message in Signal
- Hit forward
- Try typing a number into the search bar and realize there's no way to send

**Actual result:** No option to enter a phone # manually, only to search and select from contacts
**Expected result:** Some way to enter and send to a phone number

### Screenshots

![signal-2022-01-29-112058_001](https://user-images.githubusercontent.com/20782994/151668641-9b5e6368-fcb4-4e9f-9884-7a426143a3de.jpeg)

### Device info

**Device:** OnePlus Nord N200
**Android version:** 11
**Signal version:** 5.28.10

### Link to debug log
N/A

**Comment by Tursko** [comment]
This isn't a bug, its just functionality that hasn't been built. The work around is to add that SPAM number to your contacts. Afterwards you'll be able to forward.
