### ISSUE TITLE
Signal allows device to sleep (screen off) while playing video

### ISSUE THREAD

**Issue by DNGros** [signalapp/Signal-Android#11930]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to watch received video without user interaction. The issue came up in #6642 and was intended to be fixed in #6837. Unclear if this is regression at an unknown time after v4.10.0 or if this a device / android version specific issue.

A similar issue has been raised for audio clips in #8462 and #7954. In PR #9508 the solution was using the power wake lock api.

### Steps to reproduce
- receive video message longer than screen timeout (~30 seconds default on my device) that was recorded via built-in camera functionality
- play video without touch interaction

**Actual result:** Screen decreases in brightness (after about ~25 seconds) before eventually going to sleep (after ~30 seconds). This stops the audio/video playback. When unlocking the screen the video returns to beginning and user must manually seek to find previous point.
**Expected result:** Able to watch video without interaction by keeping screen awake. 
As an extension feature, it might be even more preferable to play using default media controls as mentioned in #8462 so can also watch listen to audio while viewing other apps (though this should likely be user configurable).

I believe this is the source attempting to enforce the keep-wake (but not completely sure if this is right video player) https://github.com/signalapp/Signal-Android/blob/2dd887cd17ab37a8814da046d8b0cb16a86abf74/app/src/main/java/org/thoughtcrime/securesms/video/VideoPlayer.java#L307-L329
[This SO post](https://stackoverflow.com/a/52110502) suggests `playerView.setKeepScreenOn(true)` might be a solution rather than the window flags. Would appreciate other thoughts.

### Device info

**Device:** Google Pixel 4a
**Android version:** 12
**Signal version:** 5.28.10

**Comment by cody-signal** [comment]
Hey there, this is fixed in our latest beta 5.30. It'll be available widely soon or you could join the beta.

**Comment by DNGros** [comment]
@cody-signal awesome! Just tried the beta release on my device and it worked. Apologies that didn't realize about the beta version fix or notice your patch in c48ea68e7.

Thanks for letting me know and for your work on Signal!
<img src="https://user-images.githubusercontent.com/5520022/151620927-012f271a-fedd-4254-9d5c-3d6b56a63c2a.png" width="100">
