### ISSUE TITLE
SMS Messages fail to send after turning off airplane mode

### ISSUE THREAD

**Issue by DjIronArm** [signalapp/Signal-Android#11933]
[x] I have searched open and closed issues for duplicates
[x] I am submitting a bug report for existing functionality that does not work as intended
[x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
[x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I put my phone in airplane mode when I go to bed. Often, when I turn off airplane mode in the morning, and try to send a message, it fails. It just hangs with the spinner.  This isn’t a new issue. I’ve noticed this for several months. So it's not related to a specific version it seems, as i've updated the app multiple times between.  If I restart the phone, then I get the error that it failed to send. I’m guessing a force stop would probably work too, but haven’t tried it. Just putting airplane mode on for a minute or 2 doesn’t seem to be a problem. But after being on for 8 hours or so, it seems to cause an issue.

### Steps to reproduce
- Turn airplane mode on
- Turn airplane mode off
- Send a message.
I'm not sure if the length of time in airplane mode is relevant.  It seems to be, since toggling it for a minute or two doesn't seem to be a problem.

**Actual result:** 
Message does not send.  It just hangs with the spinner instead of checkmarks.  It does not resolve itself if you wait.

**Expected result:** 
Send message successfully. (shows checkmarks, no error)

### Screenshots
I'll get a screenshot next time it happens.

### Device info

**Device:** LG G8X ThinQ
**Android version:** 11
**Signal version:** 5.28.10

### Link to debug log
I'll have to get this next time it happens.

**Comment by DjIronArm** [comment]
Upgraded to 5.29.7, same issue.
![signal message not sending_LI](https://user-images.githubusercontent.com/32883030/152014622-40f475a0-82ea-4a0a-82a0-6d7b5b78320b.jpg)

**Comment by cody-signal** [comment]
It looks like the OS is not notifying us that we have cell service again. If you force close and restart the app does it send? I couldn't reproduce locally.

**Comment by DjIronArm** [comment]
> It looks like the OS is not notifying us that we have cell service again. If you force close and restart the app does it send? I couldn't reproduce locally.

I will try a force stop and let you know.

**Comment by DjIronArm** [comment]
No issue with Signal messages (as expected).  The issue is only with SMS messages.

**Comment by cody-signal** [comment]
Okay, then it's definitely because the OS isn't telling us you have cell service again. The internet check is separate and appears to be working. Hrm.
