### ISSUE TITLE
Unable to use Signal voice calls

### ISSUE THREAD

**Issue by kevin-george** [signalapp/Signal-Android#11943]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I use Signal voice call to call others, they can't hear my voice when I use the microphone and hear a weird sharp noise when I use the speakerphone. 

- I've tried re-installing the signal app 
- I've made sure the app has all permissions it asks for and given it unlimited access to data. No optimizations enabled.
- I've confirmed that I'm on a strong Wi-Fi connection(Signal Desktop works fine for the same call recipient). This was working perfectly fine until yesterday and I've been using Signal for many years now.
- Regular calls via the cellphone network work fine so the microphone isn't damaged

### Steps to reproduce
- Open Signal
- Initiate voice call with contact

**Actual result:** Recipient unable to hear my voice when on regular microphone and hears a weird sharp noise when on the speakerphone
**Expected result:** Voice call works as usual

### Screenshots
None

### Device info

**Device:** Google Pixel 3
**Android version:** 12, Security Update Oct 5,2021
**Signal version:** 5.29.7

### Link to debug log
https://debuglogs.org/7708ecbcd645ef48e52e3d09f5fab08502ed02b35bf79231bc634d2aefd957cd

**Comment by EMostafaAli** [comment]
I confirm that I face the same exact issue. I believe it happens in the latest update. Voice messages works well but not voice calls. I tried to reinstall (with and without backup) but no avail.

The issue happens in my Pixel 3 as OP but I have another phone pixel 2 which works with no issue. Not sure if it is specific to Pixel 3 or all Android 12

**Comment by Edu4rdSHL** [comment]
The issue is present on Android 11 as well, Redmi Note 10 Pro. Using an earphone when making voice/video calls causes the app to not transmit the voice.

**Comment by EMostafaAli** [comment]
> The issue is present on Android 11 as well, Redmi Note 10 Pro. Using an earphone when making voice/video calls causes the app to not transmit the voice.

Just to be clear our issue happens **without** using earphone or headsets. Maybe your issue is different.

**Comment by jim-signal** [comment]
Hello, the 5.29.7 release brought a change to echo cancellation that we think is causing the issue. You won't have to reinstall, maybe just relaunch the client if it still isn't working for you. The change has been disabled via remote configuration.

If you can let us know if it is working or not, that would be great. If not, please also provide a debug log. Sorry for the inconvenience.

**Comment by EMostafaAli** [comment]
@jim-signal, I can confirm that it is working now. Many thanks.

**Comment by kevin-george** [comment]
I can confirm that everything is back to normal now. Thank for you for the prompt response!
