### ISSUE TITLE
Signal does not respect tablet orientation in call

### ISSUE THREAD

**Issue by peledzius** [signalapp/Signal-Android#11942]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've a tablet is mounted on the wall in landscape position. Whenever I receive a call or answer it, call screen(caller name, picture, controls) rotates to portrait mode.   

### Steps to reproduce
- Have a tablet positioned in landscape mode
- Receive call/answer call

**Actual result:** Tablet rotates to portrait mode
**Expected result:** Tablet keeps original orientation

### Screenshots
![Screenshot_2022-01-31_00-30-24](https://user-images.githubusercontent.com/24360494/151720684-7d18de6b-d1fe-4212-8885-9f69c67d9725.png)
When call is in Picture-in-picture, app switches to landscape(correct) position
![Screenshot_2022-01-31_00-28-56](https://user-images.githubusercontent.com/24360494/151720686-e9cea02b-fcb2-450e-98e7-1f8ca82b98a0.png)

### Device info

**Device:** Samsung Tab A7
**Android version:** 11
**Signal version:** 5.29.7

### Link to debug log

https://debuglogs.org/44d099dbfdab2b0761487ebe974f143914b173705fb9e99ef0e5429d1420315a

**Comment by cody-signal** [comment]
Hey there, we have big plans on the roadmap to support larger screens like tablet as 1st class citizens. We'll get there, just ask you be patient with us.
