### ISSUE TITLE
Conversation menu item "unmute" displayed twice when conversation with blocked recipient is muted

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#11940]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversation menu item "unmute" displayed twice when conversation with blocked recipient is muted

### Steps to reproduce
- block a recipient
- open the conversation menu
- mute the conversation
- open the conversation menu

**Actual result:** "Unmute" displayed twice
**Expected result:** "Unmute" displayed only once

### Screenshots

![Screenshot_1643478832](https://user-images.githubusercontent.com/49990901/151672030-40f64874-2355-4bd8-ad9e-be3322917df5.png)

### Device info
**Android version:** 11
**Signal version:** 5.30.3

**Comment by Meteor0id** [comment]
All media is also displayed twice but I guess you noticed that too.

**Comment by Sgn-32** [comment]
The issues #11938 and #11940 are related, but not the same.
11938 is about double "All media" when user is blocked
11940 is about double "unmute" when a conversation is muted and user is blocked.

Both could be caused on this if-condition isInMssageRequest when a user is blocked. But i couldn't test more in detail.

https://github.com/signalapp/Signal-Android/blob/62933ba887d92ada26ba56f5b416daccaf1e27e1/app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationParentFragment.java#L903

**Comment by Sgn-32** [comment]
Fixed in 5.32.0 with https://github.com/signalapp/Signal-Android/commit/d8e0baa9ee99b45639835ea014bd53d261316275
