### ISSUE TITLE
Jumbo emojis are blurry for 2s (loading)

### ISSUE THREAD

**Issue by Altonss** [signalapp/Signal-Android#11947]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The new Jumbo emojis are blurry for 2s (some kind of loading time).

### Steps to reproduce
- send a jumbo emoji

**Actual result:** The new Jumbo emojis are blurry for 2s.
**Expected result:** The new Jumbo emojis should not be blurry.

### Device info
**Device:** Samsung Galaxy Core Prime
**Android version:** 5.0.2
**Signal version:** 5.29.7

**Comment by cody-signal** [comment]
When you send/receive a jumbo emoji, we have to download the higher res version of it (to keep our APK size from being huge), it's part of sprite sheet of other jumbos. During that time we should the lower res version and swap in the higher one when we get it. Sending the same emoji should be crisp immediately as you already have it downloaded.

This is working as expected.

**Comment by Altonss** [comment]
Ok I understand but that kind of ugly from a user perspective. Is it downloading the emoji each time from the signal servers?

**Comment by Altonss** [comment]
Ok but I see 2 issues appart from the usability problem:

1. From a privacy point of view, when downloading these emojis, Signal will now what emojis I use most often, or am I wrong about this?
2. From a bandwidth perspective (in some areas with limited network access) this could be an issue, as each time I restart the app the cache is deleted, so it's downloading the same emojis again and again (without the user noticing about it!)

**Comment by cody-signal** [comment]
1. No, we download a sprite sheet, which is 64 different emojis. We don't know which one you actually want. And once you download that sprite sheet, you'll never need to download it again. For the initial emoji, and for the other 63 that just happen to be on the sheet as well.
2. We cache the sprite sheets to disk, so you don't download them again and again. The first use after a fresh app start may be delayed a bit as we load the image from disk into memory. The download is also gated by the same data restrictions as images. If the user has restricted auto-download of images based on network type, this will respect that. It won't download the jumbos and it will also not show the large version of it because we know that we won't be allowed to download it (if it's already downloaded then we'll use it)

**Comment by Altonss** [comment]
Thanks a lot for your detailed reoponse :heart: 


> 2\. We cache the sprite sheets to disk, so you don't download them again and again. The first use after a fresh app start may be delayed a bit as we load the image from disk into memory. The download is also gated by the same data restrictions as images. If the user has restricted auto-download of images based on network type, this will respect that. It won't download the jumbos and it will also not show the large version of it because we know that we won't be allowed to download it (if it's already downloaded then we'll use it)

That may be the issue on my device. Each time I restart the app,  I need to wait for the same emojis to re-download, so then this is a bug right?

**Comment by cody-signal** [comment]
Can you provide a debuglog?

**Comment by Altonss** [comment]
> Can you provide a debuglog?

https://debuglogs.org/1b08974dc7f03c45b62ea118407b8a135478780edae04d8f1a1bccd731de6b4e

**Comment by cody-signal** [comment]
Your logs show only two downloads have been made. I don't believe you are downloading them again. However, what is likely the case is still have to read them in from the disk cache which can be slow. It shouldn't be 2 seconds slow, but it's technically possible I suppose.

```
2022-01-30 14:36:56.972 GMT+01:00 I JumboEmoji              No file for emoji, downloading jumbo
2022-02-01 16:08:54.891 GMT+01:00 I JumboEmoji              No file for emoji, downloading jumbo
```

**Comment by Altonss** [comment]
But even inside a conversation, when scrolling up and down, having different jumbo emojis that for some have already been loaded in memory appear briefly blurry.
And also when sending a thumbs up that is already in memory, because I viewed it a few messages ago and it loaded, appears blurry briefly after clicking on send. This is a very short time, but still I think something could be done here! Something doesn't seem to be optimised well :)
