### ISSUE TITLE
Failed to delete account error

### ISSUE THREAD

**Issue by calzo** [signalapp/Signal-Android#11959]
I've been trying to delete my Signal account for a few hours and I'm getting the 'Failed To Delete account' error on iOS. Latest version of the Signal app. Both WiFi and mobile data are on.

**Comment by cody-signal** [comment]
Hi there, this is the issue reporting for Android not iOS. However, there is a known issue right now with part of our system that is likely the reason this isn't working right now. The server team is actively investigating it. If you continue to have issues, please open an issue under the iOS project.
