### ISSUE TITLE
Cannot create PIN on new install

### ISSUE THREAD

**Issue by YongJunLim** [signalapp/Signal-Android#11958]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Installed Signal on my new phone and was unable to create a new PIN. Also tried backing up, re-installing and restoring the backup before re-attempting. All chats were successfully transferred from the old phone. Tried both alphanumeric and numeric PINs.

There was a [similar issue](https://github.com/signalapp/Signal-Android/issues/9775) but it was not updated and is currently closed.

### Steps to reproduce
- Install Signal
- Restore backup/transfer account
- Enter PIN when prompted

**Actual result:** PIN creation failed
**Expected result:** Successful creation of PIN

### Screenshots

After entering a PIN:
![Screenshot_20220204-165824_Signal](https://user-images.githubusercontent.com/19851315/152504436-ec1c1ed2-532a-44a7-9ea8-d48098b23450.png)

Error message dialog shown:
![Screenshot_20220204-165903_Signal](https://user-images.githubusercontent.com/19851315/152504582-3f8eabf2-906c-4d13-95ea-e3875e61db52.png)

### Device info

**Device:** Samsung Galaxy S21
**Android version:** Android 12
**Signal version:** 5.30.6

### Link to debug log

https://debuglogs.org/5b83cfd86f15d591e2b28818a83e77500eba5cab0474f12f16aa94bc204db1f2

**Comment by calzo** [comment]
I'm experiencing this issue on the latest version of the iOS app. Creating a pin spins for about 50 seconds and then an error 'No Network Connection. Check your connection and try again'.

**Comment by Sai-Rithik-Lingamaneni** [comment]
I am experiencing the same issue. I changed my phone and while I set up signal in the new phone, the pin creation fails. Same error.

**Comment by cody-signal** [comment]
Hey folks, we are currently experiencing an outage with the service responsible for PINs. We are actively investigating it and hope to have a fix out soon. Sorry for the inconvenience. The server folks are on it and working as fast as possible.

**Comment by arnowelzel** [comment]
Same problem her - had to re-install the app on a new phone because the old phone does not work any longer.

I am an active support paying 5 EUR per month to Signal - but since I reinstalled on the new phone (with the same number as had before) I could not use my old PIN, cound not create a new PIN and could also not delete the account to create a new one.

**Comment by beamdee** [comment]
Was going to write something about having the same problem but server people are working on it. Thanks for all you do Signal people! Appreciate it. 

<plug>Now if we could have multiple profiles/names for different chats, that would be great ;))</plug> <3<3<3

**Comment by aravind-alpha07** [comment]
Fixed Now

**Comment by YongJunLim** [comment]
> Fixed Now

Yes, tried creating a PIN earlier today and it works. Will be closing this issue after a few days in case anyone else face problems. Thanks devs!

**Comment by cody-signal** [comment]
This was definitely a server outage that is resolved. Closing.

**Comment by json-warner** [comment]
I'm having the same issue, but this issue is several months old. Is there a method of checking the current PIN server status?

**Comment by cody-signal** [comment]
@json-warner what version are you using?

**Comment by json-warner** [comment]
Signal - 5.49.3
Device - S21+ 5G
Android - 12

**Comment by json-warner** [comment]
Not sure why it wasn't updated - but that resolved it. Cheers!

**Comment by greyson-signal** [comment]
@gityhubi Hi there, this is likely a different issue. Can you open a new  issue with a debuglog so we can see what's up? To get a debuglog during registration, you can tap on any of the text headers on any screen 8 times. Thanks!
