### ISSUE TITLE
Missing gray background for messages in one conversation

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#11960]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The gray background of messages I have received is missing in one conversation with 3 recipients (including me). In other conversations, the gray background. See screenshots.

### Steps to reproduce
Unknown, but I updated just a few days ago from 5.28.10.

### Screenshots

<details>
<summary>Missing gray background (see last messages)</summary>

![signal-2022-02-04-151143](https://user-images.githubusercontent.com/3812042/152545096-1380b286-a947-4cfe-9c09-592fad228cc0.png)

</details>

<details>
<summary>With proper gray background</summary>

![signal-2022-02-04-151217](https://user-images.githubusercontent.com/3812042/152545100-7900cf61-523d-4f08-9834-67a555458581.png)

</details>

### Device info
**Device:** Pixel 3
**Android version:** 11
**Signal version:** 5.29.7

### Link to debug log
https://debuglogs.org/78209885a384d7bd68c4aadfd3fd0df5f5f0d7bf2bf15f43e48ccccbb220f6e6

**Comment by cody-signal** [comment]
There's a known issue with restoring from backup/transferring. If you had a backup set prior, it's not part of the backup/transfer, but the setting indicating there should be one is, thus the mix up.
