### ISSUE TITLE
App Crashes when reacting to a message (Beta Version)

### ISSUE THREAD

**Issue by Ghost-Rider10** [signalapp/Signal-Android#11961]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the new update (in beta) if we long tap on any message in any chat we get a menu and also reactions and then if we want to choose from other emojis to react we click on the three dots and then all emojis appear but if we choose any other reaction from there or even if we choose none and click the back button then the app crashes.

### Steps to reproduce
- Open Android App
- Open any chat
- Long tap on any message
- After the reaction menu appears click on three dots
- Choose other Reaction from emojis or Click the back button
- App Crashes

**Actual result:** App Crashes
**Expected result:** Go Back to Chat Screen

### Screenshots

https://user-images.githubusercontent.com/45249429/152547503-ca4d32f5-f14b-47c1-8869-072b62fba613.mp4

### Device info

**Device:** Lenovo TB-8704X
**Android version:** stock Android 8.1.0
**Signal version:** 5.31.2

### Link to debug log
https://debuglogs.org/a51c3f24be6c4d1b57acb5f6849ccf21ed1b8b8ba44c20736b46f6bab79de3ec

**Comment by vojta-horanek** [comment]
+1, also affected, Motorola Moto G60

**Comment by cody-signal** [comment]
Yup, thanks for the report. This was also reported on our beta community thread and will get a fix out soon. Check it out here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-31-release/41424

I'm going to close this issue since we are still in beta and like to use the forum for tracking this stuff, but do know we'll have a fix in the next dot release.
