### ISSUE TITLE
Update 5.30.6 - Emoji Became Smaller Instead of Getting Bigger In Some Phones

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#11978]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji became smaller instead of getting bigger as mentioned in the update 5.30.6 version.

### Steps to reproduce
- Update to 5.30.6
- Test emoji
- Result being smaller than becoming larger in size

**Actual result:** Emoji got smaller in size.
**Expected result:** Emoji should get bigger in size as per the update.

### Screenshots

![IMG_022313](https://user-images.githubusercontent.com/55331939/153135417-f07b4a05-8bee-4891-84e7-dcc155951c0a.PNG)

### Device info

**Device:** Multiple Devices
**Android version:** 4-11
**Signal version:** 5.30.6

### Link to debug log

NA

**Comment by cody-signal** [comment]
Do you have download restrictions in place? The larger emojis won't be downloaded if you restrict auto-downloading images on whichever network you happen to be on. A debuglog would be helpful if that's not the case.

**Comment by desmonk** [comment]
By allowing auto download of images, the bigger emoji started working. 

Although now, the problem is another one for which I guess new case might help. Now, if a user uses more than five emoji in same message then they become too small to even read and even smaller than fonts! Another side effect is for high DPI screen and there these new big emoji, again less than six in a single message, are too big compared to the fonts.

I will open these cases on a different bug report. For this, the problem is solved.

**Comment by desmonk** [comment]
So in one of the devices the issue persists. I am opening another issue as well where by new big emoji remain inconsistent in size and many are not even bigger in size after getting the few ones working.

![IMG_001](https://user-images.githubusercontent.com/55331939/153345646-59ec29f8-5e51-4741-b788-e37f56cc64a4.png)

**Comment by alex-signal** [comment]
I'm closing this since you've opened a new more specific issue.
