### ISSUE TITLE
What is wrong with Signal Backups. Every backed up message is deleted!

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11971]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- I backed up the message at `5:05PM` yesterday before flashing my phone. At around 1`0:28PM` on `February 6 2022` I got it restored and the phone was working fine. I opened Signal. I was **shocked** to see that almost **every message was deleted** that were important to me. But selectively.  
- Chats that I'd with my mom were all cleared except those **notifications** that stated "You called", "Missed Call" notifications and etc. 
- Some chats were **completely wipedout** leaving **nothing** while some other chats were intact.
- And I was able read them all from Desktop but **couldn't** get them restored on Android.
- I now feel like switching to some other service. The app is full of **inconvenience**. There exist **no proper sync** between Signal-Desktop and Signal-Android.
- **Tell me how do I get all of my messages restored?**

### Steps to reproduce
- Backup
- Flash Phone / Uninstall and Re-Install Signal
- Restore
- Most of the chats are deleted

**Actual result:** As described, every other chat is deleted
**Expected result:** Once the backup is taken, no chat has to be deleted upon restore.

### Device info

**Device:** Nokia 6.1 Plus
**Android version:** 11.0 LineageOS 18.1
**Signal version:** 5.31.4

### Link to debug log

https://debuglogs.org/087bd361b20a5bd808530e8403b0f5569b6b0014dcdf98c60934101764d27645

**Comment by UserX404** [comment]
Do you know if the affected chats had disappearing messages set?
Afaik such messeges wheren't included in a backup.

**Comment by pixincreate** [comment]
Yes, I've had disappearing messages turned on for those chats.
> Afaik such messeges wheren't included in a backup.
I didn't know that! Finally I lost every chat that had disappearing messages turned on. Why it doesn't get backed up upon backup? 

No sync between them either restored the chat. I just cannot do anything now other than forwarding the chats from `Desktop` to `Notes to Self.` I don't think I'll keep using Signal if the same kind of inconvenience continues.

**Comment by pixincreate** [comment]
> Chats with disappearing messages are not backed up. This is to prevent them from living on in cold storage indefinitely when chat parities believe the messages will disappears with in X time. One can argue that anyone could modify Signal or have a bad actor client that doesn't respect disappearing messages, but we aren't one of those so we do our best to honor the intent.
> 
> With all that said, we have discussed changing this behavior, especially with device-to-device transfer. But as it stands now, things are behaving as they are expected.

Why not at least notify user upon backing up the data when disappearing messages are turned that they'll not be backed up? I just lost most of messages and now have to rely on pc for that.

**Comment by cody-signal** [comment]
> Why not at least notify user upon backing up the data when disappearing messages are turned that they'll not be backed up?

Very valid point, this was all built before my time so not sure what that UX wasn't included. I'll raise with the team to make them aware.

**Comment by cody-signal** [comment]
It is also the case with device transfer, backups and device transfer use the same underlying code. One just stores to disk, and the other sends over the network to the other device.

I don't disagree with you on the disappearing messages, it's also not my call. There are more folks involved than just the four of us writing code. This has come up internally from time to time, and next time I'll voice a stronger opinion for it. That's about all I can say.
