### ISSUE TITLE
Past attachments missing after moving Signal from SD card to internal storage

### ISSUE THREAD

**Issue by womanlike** [signalapp/Signal-Android#11976]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I moved Signal from the micro SD card to the phone's internal storage. With this I lost all attachments from before the switch.

### Steps to reproduce
- insert micro SD card into phone
- format it as [adoptable storage](https://source.android.com/devices/storage/adoptable)
- activate [full-disk encryption (FDE)](https://source.android.com/security/encryption/full-disk)
- install Signal (app and its data are automatically stored on the memory card)
- use it like this for years without any trouble
- in Settings -> Apps, move Signal to the internal storage

**Actual result:**
* All attachments sent/received before the switch went missing. Images, videos, files, link previews, both sent and received. In their place, I see the below icon. For images/videos the background behind the icon is a heavily blurred image/thumbnail from the original media. If I try to save such an attachment, I get “Error while saving attachment to storage!” I suspect the data is still there because the storage used by the app is still in the gigabytes.
* After the switch, someone sent me a message and it doesn’t show up on my desktop. Later I sent a message to someone else from my desktop and this message doesn’t show up on my phone. I *think* it was at this point that I got a “Chat session refreshed” entry in my Note to Self chat (but only on my phone). Since then receiving messages and syncing between the phone and the computer seems to have returned.

**Expected result:** Attachments are still available as before, no messages get dropped.

### Screenshots
![](https://user-images.githubusercontent.com/54036399/153118737-87715942-2879-440a-a2d3-bf76ff76e820.png)
![](https://user-images.githubusercontent.com/54036399/153118761-0b77ccaa-5366-488e-b089-dd0ef3a9d6ce.png)
![](https://user-images.githubusercontent.com/54036399/153118780-ec8c1f79-aae9-467b-a2d8-e4dbd7e8fc51.png)

### Device info
**Android version:** LineageOS 9.0
**Signal version:** 5.28.10 (website APK)

### Link to debug log

[Link](https://cryptpad.fr/code/#/2/code/view/JWT0EwLJ1XbyAOw-rGfDaHCwXUUX35MQJI-fUnS9AQ8/) (you can turn the preview pane off for more screen space)

The above is an `adb logcat` output in which I open Signal (it was previously forced shut down), unlock it, go into a group chat, open (the black placeholder of) a media attachment and try to save it to my phone’s storage. I apologize if the log is too heavily redacted, but this is raw adb output so I was careful. I guess the most interesting parts are in the second half, in the lines containing “W AttachmentDatabase”, “W ZoomingImageView” and “W SaveAttachmentTask”.

### Miscellaneous

Please tell me how do I fix this without losing my chat histories either on my phone or my desktop.

This bug report is a shorter, updated version of my [forum post](https://community.signalusers.org/t/all-attachments-missing-messages-dropped-after-moving-signal-from-sd-card-to-internal-storage/41605).

**Comment by womanlike** [comment]
Signal forum user _newuser_ [spotted](https://community.signalusers.org/t/all-attachments-missing-messages-dropped-after-moving-signal-from-sd-card-to-internal-storage/41605/6?u=cargo) that the app is looking for attachments in `/mnt/expand/[REDACTED]/user/0/org.thoughtcrime.securesms`, but those were moved to `/data/data/org.thoughtcrime.securesms/app_parts`. Looks like the attachment database didn't update itself after the application was moved.

**Comment by alex-signal** [comment]
Hi! We're not sure how you were able to move Signal to the external SD, as this is something we do not support.

More discussion here: https://github.com/signalapp/Signal-Android/pull/9015
