### ISSUE TITLE
Sending a long SMS makes the sending animation loop until exiting the chat

### ISSUE THREAD

**Issue by LaPeste** [signalapp/Signal-Android#11982]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a long text message (SMS) to a contact I never wrote before the "message being sent" animation gets in a loop that stops only when exiting the chat. When re-entering the chat window the message looks sent and all is fine.
More specifically, the SMS was 4 concat SMS long with no emoji. So lots of text.
Could this happen also when sending long text messages to contacts to who I wrote already, so not a new chat? I don't know and it's hard to test as I can't spam people.

### Steps to reproduce
* Go in the view to write an SMS to a contact you never wrote before 
* Write a long SMS (4 message in my case)
* Send the message

**Actual result:** The sending animation keeps looping until exiting the chat
**Expected result:** The sending animation should be run just once and the message should appear in the chat as sent.

### Device info

**Device:** Oneplus 7T
**Android version:** 11.0.0
**Signal version:** 5.30.6

### Link to debug log

[https://debuglogs.org/android/5.30.6/b2ea662ea30a8617a0cf26b83f42be2cd06ee2103f4842236feabe93dade13a7](https://debuglogs.org/android/5.30.6/b2ea662ea30a8617a0cf26b83f42be2cd06ee2103f4842236feabe93dade13a7)

**Comment by Tursko** [comment]
I've also experienced this on my Pixel 5 on 5.31.6

**Comment by LaPeste** [comment]
This should not be closed

**Comment by alex-signal** [comment]
> Could this happen also when sending long text messages to contacts to who I wrote already, so not a new chat?

I'd be surprised if it didn't? Since there's no like, endpoint verification with SMS. It's just an insecure, plaintext message.

More likely, since you're able to leave the chat and navigate back, there's an issue with the piece of code that should update a messages's status. It either isn't seeing the SMS send completion or isnt propagating them probably.

I'm going to be really annoying and ask if others can please submit debug logs (ideally on newer app versions) who are experiencing this issue, ideally right around the time it happens, so that I can see:

1. Order of operations (which activities you navigated to)
1. Any logging around the SMS Send Job

etc.

**Comment by LaPeste** [comment]
> > Could this happen also when sending long text messages to contacts to who I wrote already, so not a new chat?
> 
> I'd be surprised if it didn't? Since there's no like, endpoint verification with SMS. It's just an insecure, plaintext message.
> 
> More likely, since you're able to leave the chat and navigate back, there's an issue with the piece of code that should update a messages's status. It either isn't seeing the SMS send completion or isnt propagating them probably.
> 
> I'm going to be really annoying and ask if others can please submit debug logs (ideally on newer app versions) who are experiencing this issue, ideally right around the time it happens, so that I can see:
> 
>     1. Order of operations (which activities you navigated to)
> 
>     2. Any logging around the SMS Send Job
> 
> 
> etc.

Sorry for not having said a word for so long.
Yes yes I totally will re-add a log file if I encounter the issue again. It's just that I don't really send many SMSes.
Thank you for the attention.

**Comment by LaPeste** [comment]
Closing this issue as SMS isn't a feature supported by signal anymore.
