### ISSUE TITLE
Emojis in chat are being cut off at bottom

### ISSUE THREAD

**Issue by MirzaD** [signalapp/Signal-Android#11983]
### Bug description
Emojis in chat are being cut off at the bottom. This only happens when sending emojis without text.

### Steps to reproduce
- send message with emoji

**Actual result:** emoji is cut off at the bottom
**Expected result:** whole emoji should be displayed
### Screenshots
![Screenshot_20220210-140652](https://user-images.githubusercontent.com/5558026/153414604-dc7cb02d-db70-423c-bee3-f4f18dfd883a.jpg)

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 11
**Signal version:** 5.32

### Link to debug log
https://debuglogs.org/android/5.32.0/9b943f9a95e6592679c549b146d1bbb0739c0738b3b71daacfae1c1d2324a9c9

**Comment by cody-signal** [comment]
Hey there, I can't seem to reproduce this. Can you try the latest beta and see if it fixes it for you? Is there anything special about your display setup? Looks like maybe a custom font? Do you have adjust font scaling or display scaling?

**Comment by letmutx** [comment]
same issue on OnePlus 8T as well

**Comment by jankna** [comment]
Same on OnePlus Nord 2 with OnePlus Sans

**Comment by cloneman** [comment]
Same Issue here, Oneplus 7T. Switching away from "Oneplus Sans" font to Mr Roboto workaround works.

**Comment by MirzaD** [comment]
This is still not fixed, can we get this reopened? I can write a message here every couple of weeks to keep the boots away 😅
