### ISSUE TITLE
Account Not Deleted

### ISSUE THREAD

**Issue by ja7833** [signalapp/Signal-Android#11985]
- [x] I have searched open and closed issues for duplicates ([#10666](https://github.com/signalapp/Signal-Android/issues/10666) and [#10685](https://github.com/signalapp/Signal-Android/issues/10685))
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

**Bug description**
- Account Not Deleted
- Sever issues are the common theme in #10666 and #10685; [Signal Status](https://status.signal.org/) currently says _"Signal is up and running."_

**Steps to reproduce**
- Follow the [Delete Account](https://support.signal.org/hc/en-us/articles/360007061192-Delete-Account) instructions.
- Actual result _"There was a problem completing the deletion process. Check your network connection and try again."_
- Expected result _"This will delete your Signal account and reset the application.  The app will close after the process is complete."_

**Device info**
- Device: Google Pixel 3a
- Android version: 12 (February 2022 security update)
- Signal version: 5.31.6

**Comment by alex-signal** [comment]
Could you please include a debug log?

**Comment by ja7833** [comment]
Hello, I sent a debug log directly to support@signal.org via Help/Contact us.

**Comment by ja7833** [comment]
I didn't hear back from support@signal.org. After looking at the debug log every attempt at account deletion seemed to fail due to issues with trying to leave groups? I resolved by:

1.     Manually deleting all groups
2.     Clearing Signal cache
3.     Clearing Signal storage
4.     Rebooted phone
5.     Registered phone number with Signal again
6.     Deleted account
