### ISSUE TITLE
Forwarding messages to SMS contacts results suprisingly in MMS

### ISSUE THREAD

**Issue by Carltoffel** [signalapp/Signal-Android#11992]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I wanted to forward a Signal message containing a link (which generated a preview) to a SMS contact. This resulted in the preview image being send as a MMS. The "bug" is more likely an "unintended behavior" of the app, maybe an UI/X bug. Therefore my device info and log shouldn't matter.

### Steps to reproduce
1. Navigate to a Signal chat
2. Select a message with a link which has a preview image (to be clear: I'm not talking about an image which has a link in the description. Instead I mean a link, which generated a preview image automatically. When tapping the link preview image it follows the link (contrary to a picture which would be displayed in full screen mode)
3. Tap the forward icon
4. Select any contact from the menu which has the "SMS" label
5. Send the message

**Actual result:** Signal sends an expensive MMS (you can check this by selecting the message, tap the (i) and it will say MMS)
**Expected result:** There are some options (in order of my personal preference, first=best):
1. Signal could remove the preview image and only send the text
2. Signal could warn or inform the user that it will send an MMS in some way:
   - it could say "MMS" instead of "SMS" when selecting a contact (in step 4 of the reproduction steps)
   - before sending it could display a pop-up asking if the user wants to send plain text as SMS or include the preview as MMS

### Device info

**Device:** Fairphone 3+
**Android version:** Android 10 (/e/ OS 0.21-q-20220122158537-stable-FP3, LineageOS API-Level llama (9))
**Signal version:** 5.28.5 installed via Apps (foundation.e.apps, the default store on /e/ OS)
**Relevant Settings:** generate link preview, no SMS delivery report, no WLAN call compatibility, Signal is the default SMS-App (German phone, therefore I translated the settings from German to English)

**Comment by Tursko** [comment]
IMO it should clear the image and only send the link. No reason what so ever to send a separate mms image.

**Comment by Tursko** [comment]
https://github.com/signalapp/Signal-Android/commit/ee176cbe3d570f32e919c91461bf38a420675344

**Comment by alex-signal** [comment]
@Carltoffel If the issue is resolved in 5.33.0 beta, I believe this can be closed.

**Comment by Carltoffel** [comment]
@alex-signal thank you for fixing this! Since I'm not using Google Playstore, I cannot test the beta. But as soon as 5.33.0 stable releases for my phone via the /e/-OS Store, I'll confirm if it works!

**Comment by Carltoffel** [comment]
Sorry for the late update, Signal wasn't up-to-date in the /e/-OS store for a long time.
I can confirm that it works! I had a Signal message with link preview, I selected it and forwarded it to an SMS contact, I even added a message in the forwarding dialogue and the result were two SMSes: The first with the link, the second with my message. Everything as expected. Thank you again!
