### ISSUE TITLE
How to fix Unresolved reference: groupId

### ISSUE THREAD

**Issue by erslnenes** [signalapp/Signal-Android#11993]
![Ekran Görüntüsü (109)](https://user-images.githubusercontent.com/53295548/153768537-8475b5e7-15f3-4db2-81f0-bd76fb39a5e6.png)

I have this problem, how to fix? All sdk etc. installed.
Thank you

**Comment by hiqua** [comment]
Ask on the forum.

**Comment by greyson-signal** [comment]
Hi there, as mentioned, we only use github for bugs. Please use the [forum](https://community.signalusers.org/). Thanks!
