### ISSUE TITLE
Same media files gets saved with two different names - Chat window save V. All media save menu

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#11997]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App saves same media file with two different names when saving a file within the chat window and by using "All media" menu. If a file saved from chat window is named signal-2025-05-05-04-04-04-123.jpg then if we save the same file from "All media" menu, then it becomes different as signal-2025-05-05-04-04-04-125.jpg.

Only time the same file with incremental name is saved when we save from same method that is, if we save same file using chat window again then it becomes signal-2025-05-05-04-04-04-123-1.jpg and same goes for "All media" menu.

### Steps to reproduce
- Save a media file like a photo from chat window and save same file using "Media all" menu. 
- This same file gets saved with different names.
- Incremental save only happens if a user saves using same method again and which as mentioned earlier won't result in a completely different file name but will have the standard incrementation.

**Actual result:** Same file gets saved with different names.
**Expected result:** File should get saved with same name.

### Screenshots

NA

### Device info

**Device:** Multiple
**Android version:** 4-11
**Signal version:** 5.30.6

### Link to debug log

NA

**Comment by stevegdavis** [comment]
It seems looking at the code that the reason is that the Chat Window Save uses the date received of the photo object from MediaDatabase->getMediaMmsMessageRecord() but the All Media Save uses the date sent of the photo object ? from the attachments database and there is usually a difference in milliseconds, not sure why this is done, can anyone spread some light on this?
