### ISSUE TITLE
App crashes when long-pressing "Received call from ..." and clicking "Info"

### ISSUE THREAD

**Issue by GitMatze** [signalapp/Signal-Android#11994]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
-  Long-press a "Received call from ..." message that appears after a taken call (not sure about the exact English message text). 
- Click "Info" in the pop up window

**Actual result:** The app crashes
**Expected result:** The app shows information on the call. 

I tested multiple such messages and all of them cause a crash. 

### Device info

**Device:** Samsung S7
**Android version:** 8.0
**Signal version:** 5.32.4

### Link to debug log

https://debuglogs.org/android/5.32.4/c7ab19c8ee95624185304a9e03dd42f595a43e0b29e1ffccb5974610723755db

**Comment by greyson-signal** [comment]
This should be resolved in 5.32.5.
