### ISSUE TITLE
Send icon animation plays even when animations are disabled

### ISSUE THREAD

**Issue by octavopera** [signalapp/Signal-Android#12002]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When typing the first character of a message, or deleting the only character of a message, an animation plays affecting the buttons to the right of the message composition textarea. This animation still plays when animations are disabled in Android's Settings -> Accessibility -> Remove animations.

### Steps to reproduce
 - open a conversation or begin a new conversation
 - type the first character of a message

**Actual result:** The animation plays.
**Expected result:** The animation should not play.

### Screenshots

https://user-images.githubusercontent.com/99776432/154182905-0ec7a8ee-a2d5-4ee7-9490-e724e109c47b.mp4

### Device info
**Device:** Unihertz Titan
**Android version:** 10
**Signal version:** 5.31.6

### Link to debug log

https://debuglogs.org/android/5.31.6/b777de65a90cd94bbc0070709d2dac925116d780372780174acbd7617b2dfb0f

**Comment by octavopera** [comment]
This issue is still present as of version 5.34.10.

**Comment by greyson-signal** [comment]
Hi, I don't think we'll be addressing this.
