### ISSUE TITLE
Error message not shown when trying to attach too large media file

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#12011]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Toast "One or more items were too large" (_MediaReviewFragment__one_or_more_items_were_too_large_) is not shown when you try to attach only one too large file. However, it is shown correctly when one other, not too large file, has already been selected.
Additionally, the error message could be more precise.

### Steps to reproduce
- open a conversation
- tab "+"-button to select an attachment
- choose "Gallery"
- find one file that is too large and try to select it

**Actual result:** Nothing happens. File is not selected, no error toast is shown.
**Expected result:** Error toast "One or more items were too large" should be shown. As the error message is always shown immediately upon selecting the item, the error message could be improved to state that "this item is too large"

#### Additional steps that do work as intended
- in the gallery select one file that is not too large
- try to additionally select the too large file

**Actual result is as expected:** First file is selected. Upon selecting the too large file the above error toast in shown.

### Device info
**Device:** Google Pixel 4a
**Android version:** 12
**Signal version:** 5.32.7

**Comment by UserX404** [comment]
To help devs tracking down this issue please attach a debug log and provide more details about the choosen file. (e.g. type, size)

**Comment by Whatnoww** [comment]
Can confirm this issue is occurring on my Pixel 6 as well.

https://debuglogs.org/android/5.32.12/34ccc3d3c12c6cc0e0cdf077eebd4d13679983c02de14e74ba5c90c49837914e

Pixel 6
Android 12
5.32.12
