### ISSUE TITLE
video call on signal can't connect to Bluetooth headphone automatically when connected

### ISSUE THREAD

**Issue by Roza7790** [signalapp/Signal-Android#12013]
Hii all,
I got a bug in the video call and sometimes the voice call on signal app after upgrading to Android 12. When I make or receive a video call on signal the voice doesn't go through the Bluetooth device even though it's connected and it shows that Bluetooth connected but the voice still comes out from the phone unless i change it manully to speaker then choose bluetooth again.

**Comment by hiqua** [comment]
Debug log?

**Comment by MendelBak** [comment]
I've been having this problem for a few months now. It's been really frustrating and makes it really hard to trust Signal when making calls, especially to people who have less patience for technical issues and just expect the app to work.

I find that when performing a voice call via Signal, if my bluetooth earbuds are connected, it will almost always not send my voice through, even though I can hear the other person. If I try to switch the output from bluetooth -> speaker -> bluetooth it occasionally fixes the issue (usually not, though). 

The only way I've found to fix it, is to hang up and call back; the second call always works fine.

I'd like to include debug logs. How do I do that?

**Comment by cody-signal** [comment]
We have a big calling change coming soon, which should address some of these BT issues

**Comment by rawlife56** [comment]
Did you give nearby devices permission to signal?

**Comment by MendelBak** [comment]
> Did you give nearby devices permission to signal? That should fix it

Why would this have anything to do with the issue? The issue is one of bluetooth connectivity and as far as I understand, Bluetooh Scanning permission for Nearby Devices just improves location based services.

**Comment by cody-signal** [comment]
Nearby devices permissions includes more than just location services, and is tied also to being able to connect to bluetooth devices. However, it seems to be OEM/hardware dependent so it may help you.

**Comment by noClaps** [comment]
This issue persists in 5.42.8.

I have to switch my audio output device to speaker and then back to bluetooth for it to work properly. The feature should work without this workaround, seeing as Signal does detect when I've connected my bluetooth headset, when I've given it the Nearby Devices permission.

**Comment by cody-signal** [comment]
@noClaps can you provide an updated debuglog?

**Comment by noClaps** [comment]
@cody-signal Here you go: https://debuglogs.org/android/5.42.8/5a4922dd66c5fd3a92f72c66f4cbecb2aebd68454104a970d16bf830b1c5e39b

**Comment by cody-signal** [comment]
Looking through your logs, I see bluetooth being used for one call.  It looks like it connects, and then you switch to speaker, and then it connects again. Is this what happened or did it switch away from bluetooth on it's own?

**Comment by noClaps** [comment]
My phone connected to my bluetooth headphones, and the toggle showed the bluetooth device icon, but the call audio was still playing through the phone speakers, and not the headphones. So I switched the toggle to phone speakers, then back to bluetooth, and then the call audio started playing through my headphones.

**Comment by Tursko** [comment]
I also have this issue. In fact I can't even switch to my earbuds, it always defaults the Bluetooth connection to my galaxy watch which is frustrating.

**Comment by simlei** [comment]
I am not getting audio through my headphones connected through jack/ aux either

**Comment by cody-signal** [comment]
@simlei Do your headphones have a mic?

**Comment by simlei** [comment]
No. Koss KSC75.

**Comment by anaxonda** [comment]
I just tried and this issue has not been resolved for me. Happy to provide more logs if that helps.

**Comment by xxedgexx** [comment]
I also have this issue and have for quite some time.

**Comment by nicholas-signal** [comment]
I improved the switcher a little bit ago (there's like a popup dialog now) that should help address this, but @xxedgexx would you mind submitting a debug log? https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug

**Comment by Enzo-Matrix** [comment]
Could find a similar open case, so hoping to reopen this one. This issue is still occurring in Signal 7.62.3 on Android. When connected to bluetooth, incoming calls does not transit out going audio. This can be resolved by switch audio from bluetooth to either handset or speaker phone. Once bluetooth is re-enabled, out going audio is transmitted normally. See the crash log below for details.
https://debuglogs.org/android/7.62.3/cf424cd31f4ef83f8871f2a3e3eb077b7cb9cd90a2d3b03f5e0ac49d8330c6ac

Note, this issue also frequent occurs on Signal on iPhones, but none of my iPhone users know what "debug" is.

**Comment by Enzo-Matrix** [comment]
@cody-signal @nicholas-signal 
This issue seem to be getting worst with the recent release on Signal. Current version 7.63.3 on Android seem to occur on every call. Prior, it was bout 50% to 60% of the time.

**Comment by StripeC** [comment]
Why this still not fixed?

**Comment by wertzuz** [comment]
Maybe open a new issue to raise attention? Since closed issues seem to be ignored mostly.
