### ISSUE TITLE
Cannot copy text from signal message

### ISSUE THREAD

**Issue by sseide** [signalapp/Signal-Android#12015]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

regression error -work some versions ago but cannot say when exactly because i do not use this every day.

I received a text message with an postal address or login credentials in it. This text (no url) i want to copy to use it inside some other apps. (lets say google maps or password manager or browser login page or some other apps or ...).
Some time ago it was easily possible to copy text from received message by long pressing on the text and select the text to copy with the boundary markers. Afterwards the selected text was copied to the clipboard and could be used inside other apps.

With current versions of Signal it is not possible anymore to select text from message - it is only possible to answer/forward/copy an entire message within signal.

### Steps to reproduce

- select a message with text in it e.g. "lets meet at Osteria San Marino. We will meet Adam and Eve there too. And remember to bring all the other suff we need and blah blub yummy yadda other long text here..."
- long press on "Marino" to select text "Osteria San Marino"
- Text is not selected, only entire message can be answered and so on... This is not helpful when putting text into other apps input fields...

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Long pressing text of a message selects the entire message and action possible on full message only.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

after a long press (or some similar self-explaining action) it is possible to select single words from an long message and copy them to use in other apps.

### Device info

**Device:** Fairphone 2
**Android version:** 11 (LineageOS 18.1)
**Signal version:** 5.32.7

### Link to debug log

Not relevant

**Comment by sseide** [comment]
This now missing feature is much more relevant sending username and password via signal.
Text fields to enter password (browser/apps) do not display the text copied into it - therefor it is not possible to modify the text there and delete everything notbeeing the password.

**Comment by greyson-signal** [comment]
> Some time ago it was easily possible to copy text from received message by long pressing on the text and select the text to copy with the boundary markers.

I don't recall a time when this ever was a feature. It's possible your OS overrode some settings and allowed it? But we've never allowed individual text selection. You *can* long-press linkified text to copy it. Not sure if that's what you were thinking of.

**Comment by sseide** [comment]
Thanks - than it was not overwritten by Signal. It definitely worked before this UI change when every person in a group chat had its own color  and not every one else than me is gray. (This i do not really like as it is much harder to see which person wrote something in a group chat, but different topic). I cannot say if it worked after the color change in group chats - this is just to get some time reference, i do not say these two are connected.

And it was possible to select every "normal" text you like with a long press. Than the word you pressed was highlighted with these small icons on the beginning and end of the selected text. With these icon you could move the selection range to include more or less text. Normal Android text field behaviour. It was not tied to Urls or phone numbers.

**Comment by drws** [comment]
I'm confirming @sseide's report since I wanted to copy part of a Signal message today and found out that it doesn't work anymore. Also wanted to report it as a bug and found this.

@greyson-signal I see no reason, security or otherwise, that user would be able to copy URLs and phone numbers, but not other text. Would you please consider reopening this?

**Comment by combinatorylogic** [comment]
My 2cents: any app that overrides text selection is not worth using. It is so annoying that Signal have no alternatives. And same goes for pinch zoom not working.
