### ISSUE TITLE
Opening an image while recording an audio pauses the recording, but hides the button to send it afterwards

### ISSUE THREAD

**Issue by major-mayer** [signalapp/Signal-Android#12029]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When record a voice message, lock the recording, open an image in the chat and then go back to the chat, the button to send the paused/ stopped voice message is not visible.
Nevertheless, when you click on the location where it should be, the audio gets send anyway.

While i'm not sure if the issues are related, i would like to bring up an older bug report from me that still persists and is going in the same direction: https://github.com/signalapp/Signal-Android/issues/11579

### Steps to reproduce
- Start recording a voice message
- Lock it by swiping up
- Open an image in chat
- Go back to the chat

**Actual result:** The send button is hidden (like in the screenshot)
**Expected result:**It shouldn't be hidden

### Screenshots
![Screenshot_20220301-203106_Signal](https://user-images.githubusercontent.com/17907799/156259563-40c8ff30-d28f-4a05-8c14-0649d18287e0.png)

### Device info

**Device:** Poco F3
**Android version:** 12
**Signal version:** 5.23.14

### Link to debug log

Not relevant i guess

**Comment by Altonss** [comment]
This bug happens on 5.32.14 version and for a lot more situations than the title might mention:
The send button is hidden when one records an audio message (by locking it or not!), quitting the conversation and going back!

**Comment by greyson-signal** [comment]
Yes, this is fixed in 5.33, which will be going to beta soon. Thanks!
