### ISSUE TITLE
During Audio and Video call always shows network failed even with good network connection fix it

### ISSUE THREAD

**Issue by hari1412** [signalapp/Signal-Android#12020]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by hiqua** [comment]
Please follow the template.

**Comment by jmytch** [comment]
Same issue here as of 5th March 2022. Video call came up with "Network failed!" here in Australia. Was fine before the last 2-3 updates ago.

**Comment by n0sign4l-official** [comment]
Same issue here: https://debuglogs.org/android/5.32.14/1c77fc869fff71c451aed087b672e258e76c7fdf76bdc5be7621f6aceef82ca0 
(Issues persits with the latest version on website)
