### ISSUE TITLE
Taking Backup results in Force Close with java.lang.ArithmeticException: integer overflow

### ISSUE THREAD

**Issue by likeitlikeit** [signalapp/Signal-Android#12024]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When tapping "Create Backup", backup runs until about 20%, then the app force-closes. (The same happens when transferring conversation history to a new device.) Data and storage indicates that the overall data size is 5.8GB.

### Steps to reproduce
- Settings / Conversations / Save conversations / Create backup
- Wait for a short while

**Actual result:** The app works its way up to about 20%, then closes. 
**Expected result:** Backup is created

### Device info

**Device:** Samsung Galaxy S21 Ultra 512GB Snapdragon
**Android version:** 11
**Signal version:** 5.32.14 Beta (and other previous versions)

### Link to debug log

https://debuglogs.org/android/5.32.14/8678d8fbbfd555a24a9f1468ccb64285a66cec20537fab334c618a350c774ff2

**Comment by cody-signal** [comment]
Thanks for the report, this is a fun one. Tracking internally.

**Comment by HexPandaa** [comment]
If you need any more logs, I also have the same problem and haven't been able to take a backup for almost 6 months.

**Comment by HexPandaa** [comment]
@cody-signal I'd be willing to run such a special build if that can help solve the issue. Just to be sure, I won't loose all my messages while installing it?

**Comment by HexPandaa** [comment]
@cody-signal Any news on this custom build?

**Comment by cody-signal** [comment]
Hey there sorry. Things got a bit crazy here. Can you email me directly or DM me on the community forum?

cody at signal dot org

**Comment by cody-signal** [comment]
Hey folks, we have a "fix" coming for this in 5.46 that'll stop the crash and alert you about what went wrong and help guide you to fixing it. For the curious, the issue is an attachment/avatar/sticker being >2gb and that prevent the backup.

**Comment by HexPandaa** [comment]
Nice, thanks!

**Comment by HexPandaa** [comment]
Can be closed as solved for me.
