### ISSUE TITLE
Registration code not delivered for mtel.ba telecom provider

### ISSUE THREAD

**Issue by gasicgoran** [signalapp/Signal-Android#12022]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Registration code not delivered.
The phone number belongs to https://mtel.ba/ telecom provider.
I check all the support pages, called the provider to check if some filters are existing on that side, and also tried with another phone.

### Steps to reproduce
- open the app
- try to register
- enter the number if format [+387 65 xxx xxx]
- wait for the registration code
- try with the call

**Actual result:** Nothing happens, I just wait, and no code nor call is received so I can not finish the registration process
**Expected result:** I should receive the code and be able to finish the registration

### Device info
**Device:** Samsung S21 Ultra 5G
**Android version:** 12
**Signal version:** 5.32.7.

**Comment by cody-signal** [comment]
Hey there, thanks for this report. This is actually an issue we've been working on for sometime to get resolved. As of yesterday, we are seeing about a 90% success rate according to our support team. We like to focus GH issues on issues directly related to the android app so I'm going to close this, and if it continues to be an issue please feel free to contact support directly.
