### ISSUE TITLE
Bug: Two push notifications for every message

### ISSUE THREAD

**Issue by GitMatze** [signalapp/Signal-Android#12028]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently started getting two push notifications for each message I receive. The second notification pops up within one or two minutes. 

**Actual result:** Two message notifications, i.e., two vibration alarms etc.
**Expected result:** Just one notification

### Device info
**Device:** Samsung S10e
**Android version:** 12.0
**Signal Version:** 5.32.14

### Link to debug log
https://debuglogs.org/android/5.32.14/d364b7d22a42122d12faaac9c2a516b13e1f48c90cd862d87018656c6e7f384d

**Comment by bme13** [comment]
Hi. Based on the logfile it seems you've enabled the repeat alerts, See Settings->Notifications->Repeat alerts. If that is set to 'One time' you need to set it to Never.
