### ISSUE TITLE
Group chats need a notification cooldown

### ISSUE THREAD

**Issue by pet0ruk** [signalapp/Signal-Android#12021]
Looks like this was covered by https://github.com/signalapp/Signal-Android/issues/6759 but never addressed.

Signal is great - but in my opinion one of the few features it is missing is that busy group chats really **need** some kind of notification cooldown on them. 

WhatsApp does this, but Signal seems to have nothing at all. You can mute for time periods, but other than that it is going to send a notification for every single message in a group chat which means once a conversation kicks off I essentially need to mute notifications for 1 hour just to not have my phone go off every 15 seconds.

There really needs to be some kind of backoff with this, like notifying for the first two messages and then not again for that group chat for 5 minutes or something, and if you have not checked the chat and a new message comes in after 5 minutes then wait 5 minutes again until you look at that chat and then it all resets.

It honestly feels like a bug that this doesn't exist because it makes the app extremely annoying for any reasonably sized group chat to the point that it's one of the main things in our group that makes people want to use WhatsApp instead.

**Comment by i-segura** [comment]
Totally agree on this. I love Signal, I would say this is my the thing that annoys me the most (and the people near my phone).

**Comment by mainlt** [comment]
Also totally agree. WhatsApp has this figured out pretty nicely.
You receive a notification after a couple of seconds, and only if no other new messages arrive in the meantime. At first I was wondering why our group was so annoying since we changed to Signal, than realizing that every message instantly triggers a notification.

**Comment by cody-signal** [comment]
We are already tracking this feature request internally, and will likely get to it this quarter, but no promises.

**Comment by gessel** [comment]
Is this implemented?  Is there a UI tweak to enable the cooldown?  @pet0ruk's proposal with 5 minutes and if not checked, extended by 5 for every message arriving less than 5 from previous would be awesome.

I'd prefer, at the cost of an unwanted UI complication, a user-selectable "cooldown" period.  I'd generally set it for an hour or 4 myself.

**Comment by marksteward** [comment]
This was closed as Completed, but I can't find any way to manage a noisy chat other than entirely muting it for a fixed period. If I find time to catch up with the chat before this fixed period ends, I then need to remember to check it again or cancel the mute. Unusable if there are multiple such chats.
