### ISSUE TITLE
No results found for any emoji/reaction search

### ISSUE THREAD

**Issue by kevinoid** [signalapp/Signal-Android#12039]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Attempting to search for an emoji, for either message composition or reaction, always shows "No results found".

### Steps to reproduce

For message composition:
1. Tap the "add emoji" smiley face button to the left of the message composition text box.
2. Tap the magnifying glass in the bottom left corner.
3. Type the letter "a" (or any other letter).

For reactions:
1. Long-tap a message.
2. Tap "..."
3. Type the letter "a" (or any other letter) in the "Search emoji" box.

**Actual result:** The search results show "No results found".
**Expected result:** The search results would show emojis with names containing "a".

### Screenshots

https://user-images.githubusercontent.com/336433/156810941-f3523172-1c34-4196-abc5-6b2fdf603547.mp4

### Device info

**Device:** Google Pixel 5a (barbet)
**Android version:** 12 (Build SQ1A.220205.002)
**Signal version:** 5.32.15

### Link to debug log

https://debuglogs.org/android/5.32.15/530a0f9034786d0a626bbb944e026a6510606c9bf7f822a9006492530308277d

**Comment by greyson-signal** [comment]
Huh, strange. Your logs indicate you downloaded the search index, but maybe something went wrong. We're cutting a new index soon, so maybe that'll fix it for you.

**Comment by kevinoid** [comment]
Thanks @greyson-signal.  Let me know when I can test the new index.  (I am still able to reproduce the issue as I compose this comment.)

**Comment by greyson-signal** [comment]
There should be a new one! If you don't see it, try changing your language to something else in Settings > Appearance and then changing it back. That should force a new index download.

**Comment by kevinoid** [comment]
Works for me!  (I didn't even need to change the language.)  Thanks again @greyson-signal!
