### ISSUE TITLE
Problems using cellular connection

### ISSUE THREAD

**Issue by CallMeFlanby** [signalapp/Signal-Android#12032]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes no messages are received or sent when using cellular data. If I use a Wi-Fi connection, there is no problem at all. Sometimes if I close the app, this problem is solved, however it doesn't work always. 

This issue was opened as suggested in https://github.com/signalapp/Signal-Android/issues/11839#issuecomment-1049108873_ and is not related with issue #12026 as that user has always the problem and not sometimes. 

### Steps to reproduce
- open Signal
- send a message

**Actual result:** 
- look at the round dotted circle animation (see comment below) 

**Expected result:** 
- icon of a sent message (one/two circles with a check sign inside) 

### Screenshots
See comment below

### Device info
Device:
Samsung Galaxy Note 10 (SM-N970F/DS)

Android version:
12

Signal version:
5.32.14

### Network info
Vodafone Deutschland GmbH (Vodafone Germany) 

### Link to debug log
**As the issue happened (not working):**
https://debuglogs.org/android/5.32.14/f81c5c1b4ec63f178e909bd1adcf5ffeeb915edf5f4e5202f2c74688cc64ed54
**After closing the apps two times and reporting the issue (working):**
https://debuglogs.org/android/5.32.14/49a0b2e35cc59ad54fa3041454ee2dd7573cd6cc6de2df2d9ac2ddb582723684

**Comment by CallMeFlanby** [comment]
So, it happened again. It looks like it happens somehow randomly. I took a lot of print screens, I hope they help and sent (again) two debug logs. Sorry for the debug log spam, I hope they help you solving the problem.

### Description: 
- the pictures are in chronological order.
- from pictures 1 until picture 7 I was using cellular data. As you can see the sent messages (text and voice) weren't really sent out. 
- picture 3 and 4 show that cellular data works as WhatsApp messages are received. 
- on the upper left side you'll find the clock. 
- starting on picture 1 you see that one voice message was sent. 
- starting on picture 3 you see that one text message was also sent. 
- starting on picture 5 you see that another text message was sent
- in total I sent 2 text messages and 1 voice message. 
- all data related to the people I was talking to is covered up in blue or orange. 

### Debug logs 
Debug log after picture 7 was taken: https://debuglogs.org/android/5.32.14/7e6573d8f2c274f361f756e3becbd22073c1013b74a075b9126fd5703bf78209

Debukg log after pictures 9 was taken: https://debuglogs.org/android/5.32.14/0bb0d60774fe7a1d6610fb96b5cb6634ca0e747949614909bbac7c2b3e6b4fbc

- 1
![Screenshot_20220302-172555_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410070-991c3bd4-63b7-4874-8555-0169ad63ffd1.jpg)

- 2
![Screenshot_20220302-172703_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410096-e68b09dd-c8a4-4ae0-ba52-d879783c686b.jpg)

- 3
![Screenshot_20220302-172801_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410147-be94bb4b-672e-44ca-8d00-039df78ba4e5.jpg)

- 4
![Screenshot_20220302-172813_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410194-5003eee4-da61-40ae-b791-b6ee53945f9b.jpg)

- 5
![Screenshot_20220302-173148_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410227-706fceae-9a62-4552-a781-3831dd278906.jpg)

- 6
![Screenshot_20220302-173328_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410266-d0d834e0-2a28-4de5-af2b-110b8656e4b5.jpg)

- 7
![Screenshot_20220302-173407_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410318-e98b9b34-e33e-40f0-9afa-0a7b32c0677f.jpg)

- 8
![Screenshot_20220302-173624_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410359-e81ecca6-992f-4720-a911-fc82afba6bcc.jpg)

- 9
![Screenshot_20220302-173709_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/156410404-97953da4-2f8c-4cf7-b1eb-b29c7436a0ea.jpg)

**Comment by CallMeFlanby** [comment]
Tried to use the workaround presented in https://github.com/signalapp/Signal-Android/issues/11814#issuecomment-1061844237. Didn't work.

**Comment by CallMeFlanby** [comment]
Today also had problems with WiFi, messages weren't sent.

Debug log: https://debuglogs.org/android/5.32.15/1ff1126eef7ecfb5165a105a5a08bdc1656aea8baec7a7ce539cf5f7a292d8f2

Before:
![Screenshot_20220309-201911_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/157516618-5adff984-1585-406c-88c9-de24701a4101.jpg)

After closing the app more than three times in a row
![Screenshot_20220309-202035_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/157516661-e6b17fb5-baa1-4af2-a53b-3cd3ab8ac19e.jpg)

**Comment by woheller69** [comment]
> Tried to use the workaround presented in [#11814 (comment)](https://github.com/signalapp/Signal-Android/issues/11814#issuecomment-1061844237). Didn't work.

Just updated my workaround in #11814. It only works if it connects to a Wifi. Outdoors without a Wifi the procedure does not work for me.

**Comment by CallMeFlanby** [comment]
Update in the comment didn't help. Now sometimes I don't even get new messages on wireless. 

https://github.com/signalapp/Signal-Android/issues/12026#issuecomment-1060801144

Currently downloading 5.33.5 (beta) from the play store.

**Comment by CallMeFlanby** [comment]
Update 5.33.5 didn't help either.

Log: https://debuglogs.org/android/5.33.5/34ac50c9750f7ada334b9be231b88c02c897b3f1f845f299a3de86adbdfc8a9f

Print:![Screenshot_20220317-075802_Signal~2.jpg](https://user-images.githubusercontent.com/7440579/158754205-84b921b6-d999-456a-9d41-c0cab58dbcca.jpg)

**Comment by greyson-signal** [comment]
In your system settings, do you have any data restriction things enabled? If you go to your system settings and find the settings for signal, are there any data restriction toggles in place?

**Comment by CallMeFlanby** [comment]
> In your system settings, do you have any data restriction things enabled? If you go to your system settings and find the settings for signal, are there any data restriction toggles in place?
> 

Hi,

there was in fact a disabled option within a sub-menu. Toggled it on and will check if it works.

Signal Settings:

![Screenshot_20220322-165435_Settings.jpg](https://user-images.githubusercontent.com/7440579/159529433-a0580096-b50a-4d3b-b9ab-eb0db279bcbd.jpg)

My old config (found when I clicked in mobile data)
![Screenshot_20220322-165523_Settings.jpg](https://user-images.githubusercontent.com/7440579/159529558-8dd54148-ca5c-4a2c-ab3d-40de671f5cce.jpg)


My new config
![Screenshot_20220322-165528_Settings.jpg](https://user-images.githubusercontent.com/7440579/159529600-5de08ecd-e468-4109-8f96-18b17416cd27.jpg)

Thanks for your reply.

**Comment by woheller69** [comment]
this should only be relevant, if you are using data saver mode

**Comment by CallMeFlanby** [comment]
It looks like the problem is/was solved.

Not sure if it was because I changed the setting or if it was the update. Using version 5.34.7.

Thanks for the constant support.


@greyson-signal close the issue or rather wait?
