### ISSUE TITLE
Inconsistent archiving with Desktop when I send a message to an archived convo: should send `please unarchive` if unarchiving implicitly

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#12046]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Please see: https://github.com/signalapp/Signal-Desktop/issues/5730#issuecomment-1062658940

### Steps to reproduce

* archive a conversation
* send a message to this conversation

**Actual result:**  this conversation is now unarchived on Android but still archived on desktop
**Expected result:** the archive status should be consistent across clients

### Link to debug log
* https://debuglogs.org/android/5.32.15/261c333e26600f09642c81bfae0e9e420686d23e6f9dcfdea9d82e7b25f56d97
* https://debuglogs.org/desktop/5.35.0-beta.1/db739180f8e04393a539dbab9f93fc489c8097186654e2a9b8a4cf83e10944ad.gz

**Comment by greyson-signal** [comment]
Hi there, this sounds like a desktop bug, which you've already reported. Thanks!

**Comment by hiqua** [comment]
@greyson-signal my understanding is that both desktop and android have the same bug (inconsistency), and both will have to fix it.

Either
1. both clients should unarchive a conversation whenever a message has been sent there from the other client without getting a hint from this other client that it should be unarchived. Or:
2. both clients should, when I send a message in an archived conversation, also send a hint `please unarchive this conversation` to the other clients.

But you need one of these in each client (including Android).
