### ISSUE TITLE
Cannot send SMS from another SIM

### ISSUE THREAD

**Issue by SureshCBE** [signalapp/Signal-Android#12040]
Hi,
I have dual SIM phone and I have a conversation with one person from SIM number 1. I am changed default SIM for SMS from SIM number 1 to SIM number 2 in system settings. Then I am tried to write new SMS to the same person but new conversation is not created and SMS is still sending from SIM number 1 not from SIM number 2 in the last conversation.

**Comment by hiqua** [comment]
Did you have a look at:
* https://community.signalusers.org/t/dual-sim-sms-add-an-option/32976/4
* https://support.signal.org/hc/en-us/articles/360007319251-Dual-Sim#android_dual_sim
* ?

**Comment by SureshCBE** [comment]
Hi,

Thanks for your immediate reply now i got my answer. Before I submit a issue i am not looked at the website you shared sorry for that. Now my issue was resolved. Thanks !

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SureshCBE** [comment]
Hi,
I am refered on Signal support page and got the answer.
