### ISSUE TITLE
Typing indicator not working

### ISSUE THREAD

**Issue by M3M4Ti** [signalapp/Signal-Android#12042]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

 - - - - - - - - - -

 #### Bug description

my typing indicator is not working even though it is on

#### Steps to reproduce

- Open Signal
- Go to the main conversation list
- Start writing to any contact

**Actual result:** No one sees the typing indicator, but I can see theirs.

**Expected result:** Let them see a typing indicator

#### Device info

**Device:** Xiaomi Redmi Note 9

**Android version:** stock Android 11

**Signal version:** 5.32.15

**Comment by greyson-signal** [comment]
Hi there, the current log only shows you talking with one other person, and we *are* sending typing indicators for them. Can we get a log from the other person? Do you know what country that person is in? (some of our censorship circumvention techniques could result in lost typing indicators)

**Comment by bme13** [comment]
This also seems related to #10747. There it was solved for some by changing the time and timezone to automatically. Perhaps it's worth to check that as well.

**Comment by M3M4Ti** [comment]
> This also seems related to #10747. There it was solved for some by changing the time and timezone to automatically. Perhaps it's worth to check that as well.

yes, the problem is solved with timezone.
