### ISSUE TITLE
Signal does not check if keyboard is already open

### ISSUE THREAD

**Issue by nitrox-github** [signalapp/Signal-Android#12058]
Hi!

Since around 5.33.x +/- Signal does not check, if the keyboard is open and shows conversation in fullscreen. Keyboad is still open in the background (small down-arrow in the screenshot is from keyboard).

Somehow Signal lost its ability to check for an already open keyboard.

Pixel 5, Android 12, Signal 5.33.2 currently

regards,
nitrox
![Screenshot_20220312-140935](https://user-images.githubusercontent.com/8950340/158019501-65034582-43c2-43d1-9d98-1be20861ca6d.png)
x

**Comment by clauz9** [comment]
add a debuglog please, and try to keep to the issue template, don't just delete it.
