### ISSUE TITLE
In chat with new contact, messages progressively disappeared then later reappeared (disappearing messages NOT enabled)

### ISSUE THREAD

**Issue by patcon** [signalapp/Signal-Android#12064]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I moved a conversation from WhatsApp to Signal. This was the beginning of my chat history with this person. I sent ~20 msg between noon and 4:30pm, including a 15-minute m4a audio file (recorded in Google Recorder). At ~4:30pm, I noticed that the **messages sent from noon to 1:30pm, including the recording, were no longer visible to me**. (see screenshot) They continued to be visible to my conversation partner, though they could not play the embedded audio file on their ios device. Over the course of the next 10 minutes, **1-2 more messages disappeared** on my end. (A first log was taken, link below)

This was during a sensitive discussion, and the missing messages were quite alarming. This also confused communication as I was trying to determine what I had sent already.

It does not escape my notice that, had I used Signal to record the audio message, I wouldn't have been able to easily download nor forward the audio file to anyone else.

When I checked again today at noon, **all the messages appeared back in my history**. (Screenshots below. A second log was taken as soon as I noticed this.)

Aside: The first 15-minute m4a audio file that I was trying to send to this person (recorded in Google Recorder) was not playable by the recipient. (This may have been an issue with file format, as it's downloaded in m4a from the remote Google Recorder link, but is sent as mp3 by Signal.) The link to the hosted m4a file worked fine on iOS.

### Steps to reproduce
- no idea :(

**Actual result:** Messages from first of chat onward progressively disappeared over a few hours.
**Expected result:** Would not expect messages to disappear

### Screenshots

| Before: top | After: aligned | After: top |
|--------|------|------|
| ![WhatsApp Image 2022-03-14 at 2 00 35 AM](https://user-images.githubusercontent.com/305339/158115246-8188ae8f-2631-41af-b2c0-c81d4b37fcc1.jpeg) | ![WhatsApp Image 2022-03-14 at 2 00 35 AM (2)](https://user-images.githubusercontent.com/305339/158115345-6bc528c5-6274-4db1-a263-50f0cc5eedeb.jpeg) | ![WhatsApp Image 2022-03-14 at 2 00 34 AM](https://user-images.githubusercontent.com/305339/158115085-a3416cb5-c687-46cc-accc-9adfc1e5b18a.jpeg) | |

### Device info

**Device:** Google Pixel 3
**Android version:** 12
**Signal version:** 5.33.1

### Link to debug log

- Logs when messages were gone: https://debuglogs.org/android/5.33.1/923a2246803953f5b690fbe1a533a8f7997b930a96802850e01dee865798c362
- Logs the next day when messages were back: https://debuglogs.org/android/5.33.1/3e89eeb75acae2e429a0fa7c1f56576e7e761b184ba82bbbdae67a62662b1892

**Comment by patcon** [comment]
Can someone how me understand priority here?

To clarify, this feels quite urgent and unexplainable. No tickets match this issues. (I've been in touch with friends at Citizen Lab) The nature of my current work makes me believe this is likely active targeting, and I worry that a weakness in Signal can lead to someone being able to hide critical media messages from one end of the conversation (and potentially has somehow corrupted an audio file that was being sent via Signal)

cc: @greyson-signal @alex-signal @cody-signal  ❤️

**Comment by greyson-signal** [comment]
Hi there, there was a bug in 5.33.1 where sending/receiving a message in a chat could result in earlier messages being removed from view. They were not deleted -- rather, this was a UI bug resulting from stale state in our paging library.

This bug was fixed in 5.33.2 and never went to production users (i.e. 5.33.1 only ever went to beta users). Thank you for being a beta tester, but I also encourage users who need more stability to use the production app. Thank you!

**Comment by patcon** [comment]
Thank you, @greyson-signal  ❤️ 

The reality is that this bug caused real panic for me. Some validation of this bug would have saved me heartache through the week.

(I will admit that the day before filing this ticket, the first call from my new federal government encrypted cellphone was a 9-1-1 distress call related in part to this bug. This was all compounded by some other tech issues that unnerved me, the subject matter I was working with, and prior attacks on government coworkers.)

Anyhow, only sharing to socialize the impact it had on me 🙏 (I'll definitely get off the beta channel, I forgot I was on it tbh)

**Comment by patcon** [comment]
Suggestion for community automation to make the most human response possible:
- create a label for "beta" for all suspected beta bugs.
- create a github action workflow to recognize these beta bugs, and auto-post a message explaining how to get off beta

I'm happy to offer a contribution of this workflow, if it fits without your triage processes and would have a change of being used 🙏

**Comment by patcon** [comment]
One more humble suggestion, as I'm thinking what aggravated my situation:

_I share this next thought because I don't think I'll be the last person who starts into the beta program, and later ends up working in a sensitive context. A little bit of over-thinking this situation might go a long was in protecting future people like me, which would be greatly appreciated 🙂_ 

When I was trying to understand this, I didn't see any issues in the issue queue that resembled my own. Seeing something would have allowed me to ratchet down my concerns, because I wouldn't have felt so alone. My assumption is that this bug was detected by a team member using the beta, and silently fixed. (Which makes total sense.)

Would it be possible to create stub issues for issues like this fixed by the team, so that users find them when searching for "someone experiencing something like they are experiencing"?

I could image that this be automated. You could have a hashtag you use in commits, and it auto-generates an issue from the commit message and immediately closes it. Again, this would be no extra labour for you, just a change to your processes (which is admittedly not negligible).

Do you think something like this could help others never end up in my situation again? If so, I'd be happy to workshop the idea and submit another PR 🙏 

**Prologue:** I literally backed out of a project due to the stress (partially related to this bug), and so my output in the world went down, and I was not able to support a group doing really important on-the-ground anti-racism work (helping African nationals get out of conflict zone and dealing with racist border institutions).

**Comment by greyson-signal** [comment]
You're right, and I apologize for not responding to the bug sooner. We get a lot of github updates every day, and while we look at every issue, unfortunately we're imperfect and sometimes something gets missed. I think this was a case where a person just missed seeing the issue. We'll try to do better in the future :heart:
