### ISSUE TITLE
Reproducible build passes but apk hash check fails !

### ISSUE THREAD

**Issue by flatcloud0b3** [signalapp/Signal-Android#12063]
- [ * ] I have searched open and closed issues for duplicates
- [ * ] I am submitting a bug report for existing functionality that does not work as intended
- [ * ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ * ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

    I clone the signal-android repo from github, 
    build my own apk from the reproducible folder 
    
    from https://github.com/signalapp/Signal-Android/tree/master/reproducible-builds#introduction, 

    I then pull the existing apk, that i wish to compare to, from my mobile devise and compare them by running the Python script. 
    I also check the ABI of the google play app to avoid any confusion; it reads arm64-v8a.

    The output says "no match" when i compare the google apk with the one i built from the source code.

### Steps to reproduce

    # Clone the Signal Android source repository
    git clone https://github.com/signalapp/Signal-Android.git && cd Signal-Android

    # Check out the release tag for the version you'd like to compare
    git checkout v5.32.15

    # Build the Docker image
    cd reproducible-builds
    docker build -t signal-android .

    # Go back up to the root of the project
    cd ..

    # Build using the Docker environment
    docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease

    # Verify the APKs
    python3 apkdiff/apkdiff.py ~/Signal-Android/app/build/outputs/apk/playProd/release/Signal-Android-play-prod-arm64-v8a-release-unsigned-5.32.15.apk 
    ~/reproducible-signal/apk-from-google-play-store/Signal-5.32.15.apk

**Actual result:** 

    Manifest lengths differ!
    Sorted manifests don't match, META-INF/androidx.activity_activity-ktx.version vs META-INF/CERTIFIC.RSA
    APKs don't match!

**Expected result:** 

    Expected to see the apks match :(

### Screenshots

    APKs built from source code :
![signal_apks](https://user-images.githubusercontent.com/77271212/158073829-44bc0f25-ac9a-42b9-8020-c178257de088.jpeg)
    Python script hash check result :
![nomatch](https://user-images.githubusercontent.com/77271212/158073843-bef09a0c-ddda-44ff-8a71-0184071ae383.jpeg)

### Device info

**Device:** Pixel 4a with GrapheneOS & 64 bit System 76 "Gazelle" running Ubuntu 20.04 as build machine
**Android version:** 12
**Signal version:** 5.32.15

**Comment by flatcloud0b3** [comment]
Answered by valldrac on element chat room. Closing this issue.

**Comment by flatcloud0b3** [comment]
Reopening issue. the suggestion on element is below

![element](https://user-images.githubusercontent.com/77271212/158078353-3a400ad4-8d9e-48fe-ab64-3c74f8431135.jpeg)

I swapped the python script with the one from mollyim 
[ https://github.com/mollyim/mollyim-android/blob/master/reproducible-builds/apkdiff/apkdiff.py ]
and it shows another mismatch. I see the mollyim script ignores a few files: 

    class ApkDiff:
    IGNORE_FILES = ["META-INF/MANIFEST.MF", "META-INF/*.RSA", "META-INF/*.SF"]

the mismatch :

![mismatch](https://user-images.githubusercontent.com/77271212/158078554-1b90e1cc-997f-448c-be93-ee3d4c8275d8.jpeg)

Idea is to be able to reproducibly build and produce a APKs match result. thanks for any advise.

**Comment by chemicalstorm** [comment]
Got the same issue on v5.34.5, tried the mollyim's apkdiff without success :|

**Comment by chemicalstorm** [comment]
Finally managed to get something using https://diffoscope.org/. From what I can tell, the differences are due to the self-signed certificate or the change in `GIT_HASH` format.

**Comment by greyson-signal** [comment]
FWIW I have a script that's been running every night for about a year. It builds three copies of the app using `assembleWebsiteProdRelease` and uses our `apkdiff.py` to compare the three universal apks. All has been fine so far.

**Comment by sztadii** [comment]
@greyson-signal, what do you mean by 'three copies'? iOS, Android, and Desktop? Would you like to publish / share this script? I think it would be cool if users could validate that the GitHub version matches the deployed version.
