### ISSUE TITLE
"gif"-animations from giphy saved as .mp4, cannot be re-posted as autoplaying "gif"-animations

### ISSUE THREAD

**Issue by blaueente** [signalapp/Signal-Android#12079]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The auto-play functionality does not work for re-saved animations from giphy. 
(related issue: https://github.com/signalapp/Signal-Android/issues/4539 )
Also, this discourages caching and use of local gifs and encourages re-downloading pre-made gifs from giphy. This significantly increases mobile data usage, and unnecessarily leaks info to giphy.

### Steps to reproduce
- select and post a "gif" from giphy. 
- this will auto-play in the message view.
- save the "gif"
- it will be saved as .mp4
- re-post .mp4

**Actual result:** animated picture will show as a movie, a thumbnail without auto-play, needing a press on the play button will open in full-screen player
**Expected result:** the animated picture will show auto-playing in the message view, just as it did from giphy originally.

If the mp4 is directly from giphy, then the user should maybe have the possibility to post an mp4 similarly with auto-play?
If the .gif from giphy is converted to .mp4 upon saving, this is maybe not ideal?

### Device info

**Device:** pixel 6 pro
**Android version:** 12
**Signal version:** 5.32.15

**Comment by blaueente** [comment]
also loosely related to https://github.com/signalapp/Signal-Android/issues/12083
The solution is probably not easy, after all, it is a good thing for efficiency that "gifs" are actually encoded as mp4. 
* Maybe just autoplay every video and omit sound, only add it on click? Or 
* autoplay every video that has no sound? Or 
* let the sender select autoplay, and use some heuristic as default?

**Comment by gitrazorhub** [comment]
@blaueente   Why is it a good thing that gifs are encoded as mp4?

**Comment by blaueente** [comment]
> @blaueente Why is it a good thing that gifs are encoded as mp4?

Because it compresses much better and thus saves a lot of bandwith and storage.

**Comment by gitrazorhub** [comment]
> Because it compresses much better and thus saves a lot of bandwith and storage.

Alright, how does that apply our problem here?  Signal uses Giphy, so when I send a message with a Giphy file it's in the gif format.  When I save it to my phone/PC it becomes an mp4.  How does that save storage and bandwidth after the fact since the message was sent originally in gif format?  All future use of Giphy will continue to be sent in the gif file format, not mp4.  Where is the savings?

**Comment by blaueente** [comment]
I am not sure what exactly your point is? I did not look into the code, but my assumption is that giphy already delivers an mp4 to the signal app, that means there never was an actual .gif as far as signal is concerned. Which should not change, because of the reasons I mentioned. What should change, as part of this issue, is that non-giphy .mp4 files (including saved files from giphy) should be treated more like the files coming directly from giphy, i.e. having Autoplay without sound.

**Comment by greyson-signal** [comment]
Hi there, thank you for the detailed report, but I don't think we'll be tackling this. We have special flags and treatments for mp4's we *know* come from giphy, and we don't have an easy/reliable way to determine if the random mp4 you're attaching is from giphy.

Having a generic autoplay thing starts going into the realm of UX and design of new behavior, which we try not to discuss on Github, which we reserve for bugs. But thanks!

**Comment by gitrazorhub** [comment]
@blaueente 
My point was that saving a gif as an mp4 after the fact does nothing for the user.  If, as you stated, the file never was a gif but rather an mp4 then there never was a problem to begin with.  I suppose that getting an actual gif is the issue, not that a gif  is converted to an mp4.

**Comment by gitrazorhub** [comment]
@blaueente 
I understand now.  I was operating under the assumption that the user receives a gif from Giphy.  I also use Note To Self to forward these files from Giphy.  Thanks for the clarification.

**Comment by UserX404** [comment]
Here, the relating forum discussion:
https://community.signalusers.org/t/forwarding-a-gif-sends-it-as-a-video/42838
