### ISSUE TITLE
Why doesn't Signal Logo show up at splash screen? 

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#12076]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I somewhere heard that Signalapp has a splash screen that appears (signal logo) when opening the app. It doesn't appear to me on my phone rather than a blank splash screen upon opening.

### Steps to reproduce
- Open Signal app
- You should see the Signal Logo in the splash screen

**Actual result:** Just a blank screen appears.
**Expected result:** I should be able to see the pleasing logo upon opening the app.

### Device info

**Device:** DRG_Sprout
**Android version:** 11 (LOS 18.1)
**Signal version:** 5.34.0

**Comment by Tursko** [comment]
Only happens on Android 12.

**Comment by pixincreate** [comment]
> Only happens on Android 12 since the app uses the new SplashScreen API

I'm on A11 and some apps do show the logo at application start up but signal doesn't for me.

**Comment by greyson-signal** [comment]
We don't have a splash screen except the auto-generated android 12 one.
