### ISSUE TITLE
Screen Lock privacy setting greyed out/unavailable on Android 12 in Dual Messenger/App mode

### ISSUE THREAD

**Issue by Deenniss** [signalapp/Signal-Android#12071]
Hello,

The Screen Lock function in the Privacy settings is not available (greyed out) in Signal v5.32.15 on Android 12 in Dual Messenger (Dual App) mode.
This option is visible in dark grey color, and no action is possible to activate it, it is indeed disabled and unavailable.

This option was available and working properly on Android 11 in Dual Messenger/App mode on Samsung phones until the Android 12 upgrade which happened 2 months ago for me.

The Dual Messenger mode for Signal was enabled as follow (on Android 11, before the 12 update):
https://forum.xda-developers.com/t/add-non-messenger-apps-to-samsung-dual-messenger.3817250/

Step 1: Enable Dual Messenger for an existing app (e.g. WhatsApp).
Step 2: Enable USB Debugging and connect your device to your computer.
Step 3: Open command prompt in your adb folder.
Step 4: Type
Code:

adb shell

Step 5: Type
Code:

pm list users

Step 6: In the resulting list, find the user named "DUAL_APP" and get its number. For example, the number is 95 on my device:
Code:

UserInfo{95:DUAL_APP:20000030} running

Step 7: Type
Code:

exit

Step 8: Copy your desired apk file to your adb folder.
Step 9: Type
Code:

adb install --user 95 desired_app.apk

Remember to replace "95" with whatever number you saw in Step 6.

Wait for the process to finish. A SUCCESS message should be displayed.

The app of your choice will now be installed in Dual Messenger.

**Comment by cody-signal** [comment]
Hey there, thanks for the report. This is honestly not something we'll probably be looking into. If you want to look into it and provide a PR I'll gladly review it, but I doubt the team will spend any time on it.
