### ISSUE TITLE
Signal APK signature needs upgrade

### ISSUE THREAD

**Issue by drduh** [signalapp/Signal-Android#12073]
```
Owner: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Issuer: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Serial number: 4bfbebba
Valid from: Tue May 25 08:24:42 PDT 2010 until: Tue May 16 08:24:42 PDT 2045
Certificate fingerprints:
         SHA1: 45:98:9D:C9:AD:87:28:C2:AA:9A:82:FA:55:50:3E:34:A8:87:93:74
         SHA256: 29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 1024-bit RSA key (weak)
Version: 3
```

Please upgrade the software signing credentials to stronger cryptographic standards, such as SHA256 and 2048-bit or greater RSA public key. I understand backwards compatibility is a concern, but it's time to make a decision to stop supporting algorithms which are weak and putting the rest of the users at risk.

Previous issues https://github.com/signalapp/Signal-Android/issues/6833 and https://github.com/signalapp/Signal-Android/issues/9362 were closed due to your inactivity.

**Comment by cody-signal** [comment]
Reopened previous ticket.
