### ISSUE TITLE
MobileCoin is a bug?

### ISSUE THREAD

**Issue by xmready** [signalapp/Signal-Android#12074]
Signal has added a centralized, premined, and censorship capable payment system. This payment system called "MobileCoin" has burrowed technology from the Monero project including subaddresses and RingCT. The devs for MobileCoin claim it is based on CryptoNote even though CryptoNote does not even have those features. Any payment system that can block users based on their geographic location is not an open and permission-less distributed network. Monero and Bitcoin are permission-less.

If Monero, the only real privacy oriented payment system, is too slow for the Signal devs, they could have easily waited for Taproot, Schnorr and MAST to make Lightning Network payments a totally private and instant alternative. This shamelss cash grab is very upsetting and I hope Moxie gets his head straight.

I posted this in bugs because I have no idea how to post feature requests on SignalUsers.org without creating an account. I do wish this whole thing was bug. I'll be sending this by email as well.

**Comment by hiqua** [comment]
You can use your github account to log into https://community.signalusers.org/ where this belongs.
