### ISSUE TITLE
New EXIF metadata gets added to images - Including the ones which are stripped off of it

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#12075]
- [x] PR #7542 failed to solve #5968. 
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All images are having new metadata getting added to them. Sent or received. More concerning is the images which are already stripped from EXIF values, now have new data to them!

### Steps to reproduce
- Strip EXIF data of image completely. Tested with Phil Harvey's EXIF tool and there select option to clear all metadata.
- Send and then download and check using same program.
- You will see new data fields.

**Actual result:** New metadata getting added to images. 
**Expected result:** No metadata should get added.

### Screenshots

NA

### Device info

**Device:** Multiple
**Android version:** 4-11
**Signal version:** 5.32.15

### Link to debug log

NA

### Note
Don't use any Android apps to remove EXIF and rather use Phil Harvey's tool and remove all of them. https://www.exiftool.org

**Comment by desmonk** [comment]
_Metadata Removed_:
![IMG_901823](https://user-images.githubusercontent.com/55331939/158871753-74b982d2-2e75-455d-99db-a01fc632e3d3.png)

_New Metadata_:
![IMG_23123132](https://user-images.githubusercontent.com/55331939/158871766-d3f793f6-2a9b-409e-90e6-f59f51c7181b.PNG)

**Comment by cody-signal** [comment]
Thanks, we'll try and get this taken care of ASAP

**Comment by greyson-signal** [comment]
So the main goal of EXIF stripping was to remove location data, which still isn't there. The goal was _not_ to remove all EXIF data. Do you think any of the remaining EXIF data is identifying?

**Comment by hiqua** [comment]
I think their point is that there is *new* EXIF data (identifying or not) being added by Signal, which is unfortunate (and unnecessary).

**Comment by greyson-signal** [comment]
I agree it's not ideal, but this is the EXIF data that is added by the built-in Android image conversion tools. And unfortunately the EXIF libraries I know of don't really work on files that are encrypted on disk. Meaning in order to strip off this EXIF data, we'd have to put a lot of engineering effort into handwriting some new streaming EXIF editor/image converter so the receiver can't see the metadata revealing... the image width? Or the color profile? See what I mean?

I guess I just want to dispell the idea that "all EXIF data is bad". Most of it is just fine. We just want to make sure there's no location data or other identifying bts. As far as I can tell that still true. Please reopen if you think that there's identifying metadata being added/not-removed.

**Comment by desmonk** [comment]
Good points but the the problem is sending new/altered metadata instead of sending the original ones besides removing location. Say if you want to keep some of it, then this conversion actually changes it altogether! This defeats the idea of keeping some non intrusive data.

Problem here is even when the image is totally metadata cleaned, these new values are getting added! This is something that must not happen for obvious reasons.

We are not keeping the metadata here but rather adding new ones to images. I request you to understand how important this is and strip all the data instead as what you're keeping here are not even from original image. Meaning you're actually sending fake data! Which is again an issue.

Basically only location data is being stripped off. Rest of the data kept is not even original and rather it's altered ones. Meaning what you're keeping here is not even what was there to begin with.

In short sending completely new data and only removing location data. This is grave concern. As neither you're stripping the bits nor sending original values. Keep the original values and strip the location is still understandable.

Biggest bummer is addition of new values to stripped images here as users think they are sending a totally metadata free image.

Isn't Signal about privacy after all? BTW, Briar app strips all data. So this can be executed after all. And yes, you're adding identifying metadata here. Didn't you see the screenshot here? That is too much data! And your excuse for not doing the right thing is not using engineers for this? This is metadata we're talking about! What else is there to think twice even when it comes to privacy!

**Comment by greyson-signal** [comment]
> And yes, you're adding identifying metadata here. Didn't you see the screenshot here? That is too much data! 

Please tell me specifically what data you you feel is identifying or revealing. I included the EXIF data for an image I just sent and compressed. I don't personally see anything. In fact, nearly all of it just seem to be data you could get by just analyzing the file.

I tried to emphasize this in my earlier comment, but "metadata" is not some inherent evil. The definition is just "data about data". There are some forms of metadata that we here at Signal really do not like, and we take great care to remove it/not collect it. The color space of the image (which could be determined by just looking at the file) is not on that list.

I brought up engineering time simply to emphasize that this isn't some "quick fix" -- it would take a real amount of time and a high probability of introducing new bugs for, in my opinion, zero benefit. Again, if there's something in this information that you think is somehow revealing, please share what specific fields and why.

## JFIF
|JFIF&nbsp;Version|1.01|
|:----|:----|
|Resolution|1 pixels/None|

## File
|File&nbsp;Type|JPEG|
|:----|:----|
|File&nbsp;Type&nbsp;Extension|jpg|
|MIME&nbsp;Type|image/jpeg|
|Encoding&nbsp;Process|Baseline DCT, Huffman coding|
|Bits&nbsp;Per&nbsp;Sample|8|
|Color&nbsp;Components|3|
|File&nbsp;Size|474 kB|
|Image&nbsp;Size|1,536 × 2,048|
|Y&nbsp;Cb&nbsp;Cr&nbsp;Sub Sampling|YCbCr4:2:0 (2 2)|


## Composite
|Megapixels|3.1|
|:----|:----|

## ICC Profile
|Profile&nbsp;CMM&nbsp;Type| |
|:----|:----|
|Profile&nbsp;Version|4.3.0|
|Profile&nbsp;Class|Display Device Profile|
|Color&nbsp;Space&nbsp;Data|RGB|
|Profile&nbsp;Connection&nbsp;Space|XYZ|
|Profile&nbsp;Date&nbsp;Time|0000:00:00 00:00:00|
|Profile&nbsp;File&nbsp;Signature|acsp|
|Primary&nbsp;Platform|Unknown ()|
|CMM&nbsp;Flags|Not Embedded, Independent|
|Device&nbsp;Manufacturer| |
|Device&nbsp;Model| |
|Device&nbsp;Attributes|Reflective, Glossy, Positive, Color|
|Rendering&nbsp;Intent|Media-Relative Colorimetric|
|Connection&nbsp;Space&nbsp;Illuminant|0.9642 1 0.82491|
|Profile&nbsp;Creator| |
|Profile&nbsp;ID|0|
|**Profile&nbsp;Description**|**sRGB**|
|Red&nbsp;Matrix&nbsp;Column|0.43607 0.22249 0.01392|
|Green&nbsp;Matrix&nbsp;Column|0.38515 0.71687 0.09708|
|Blue&nbsp;Matrix&nbsp;Column|0.14307 0.06061 0.7141|
|Red&nbsp;Tone&nbsp;Reproduction&nbsp;Curve|(40 bytes binary data)|
|Green&nbsp;Tone&nbsp;Reproduction&nbsp;Curve|(40 bytes binary data)|
|Blue&nbsp;Tone&nbsp;Reproduction&nbsp;Curve|(40 bytes binary data)|
|Media&nbsp;White&nbsp;Point|0.9642 1 0.82491|
|Profile&nbsp;Copyright|Google Inc. 2016|

**Comment by Herohtar** [comment]
@desmonk What "this right here is" seems to be you not understanding what metadata is and what is a privacy risk. The only thing still attached to the image is the [ICC Profile](https://en.wikipedia.org/wiki/ICC_profile), which is necessary information for how the colors are supposed to be rendered. Without that information, your photo could end up looking entirely wrong, which would definitely be a huge negative.

**Comment by taggart** [comment]
> Without that information, your photo could end up looking entirely wrong, which would definitely be a huge negative.

I don't know if that was intended as a pun, but it's great! :)
