### ISSUE TITLE
String "MediaPreviewActivity_s_to_s" impossible to translate properly without code changes

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#12072]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The string "You" (key: ``MediaPreviewActivity_you``) is currently getting used for both of the placeholders contained in the string "%1$s to %2$s" (key: ``MediaPreviewActivity_s_to_s``).

In other words, the very same string "You" is getting used when it functions as a) a grammatical subject or b) an grammatical object. While this works in English, it doesn't work in many other languages, where the translation of "You" would be different depending on its function and location within the sentence. I've watched this issue for years now, and translators for several languages asked about it. There's zero way to solve this on the translators' side.

My suggested solution is splitting up the current string ``MediaPreviewActivity_s_to_s`` into two separate strings:

1. MediaPreviewActivity_you_to_s: “You to %1$s” (if user is sender)
2. MediaPreviewActivity_s_to_you: “%1$s to you” (if user is recipient)
3. MediaPreviewActivity_you: "You" (although I think this one can get removed completely if it's not used in other places)

As an example, the German translation of these two strings would be

1. MediaPreviewActivity_you_to_s: “Du an %1$s”
2. MediaPreviewActivity_s_to_you: “%1$s an dich"
3. MediaPreviewActivity_you: "Du"

**Comment by Sgn-32** [comment]
I see only:
- Sent by you to Alice
- Sent by you to [group name]
- Sent by Alice
- Sent by Alice to [group name]

No case with "Sent by Alice to you"
