### ISSUE TITLE
crash trying to restore backup

### ISSUE THREAD

**Issue by beerockxs** [signalapp/Signal-Android#12077]
Signal crashes when I try to restore a backup from another phone after entering the passphrase. Here's the log: https://debuglogs.org/android/5.32.15/01f95e216660162e55b7d301fc3d8e298ac168d737d5fe2fe91aa7596bd286d9

**Comment by clementblaudeau** [comment]
Same issue

**Comment by skickar** [comment]
We are all having this issue over here too: https://github.com/signalapp/Signal-Android/issues/11952

**Comment by UserX404** [comment]
This [commit](https://github.com/signalapp/Signal-Android/commit/3c0b87bbcaa503b52516ea96ed5a674f9d377e42) could probably fixes your isue.
Atm in beta phase.

**Comment by skickar** [comment]
Thank you! I just noticed there was a signal update and can confirm it fixed the Android Account Transfer feature. Didn't test the restore from backup.

**Comment by Lasteinsa** [comment]
Hello.. I have this error when I restore my backup. how to solve it?
https://bin.kv2.dev/~6245965a410e7c32e669b3a6

**Comment by alex-signal** [comment]
@Lasteinsa Please include a full debug log :) This looks like a different issue, so please also open a new ticket, including said debug log.
