### ISSUE TITLE
unable to receive and send messages [4g Vodafone portugal]

### ISSUE THREAD

**Issue by joaogilbertosilva** [signalapp/Signal-Android#12080]
WiFi works fine.
It only started a few days ago.

Debug log can be provided.

**Comment by hiqua** [comment]
> Debug log can be provided.

Please do

**Comment by jocolamarco** [comment]
> > Debug log can be provided.
> 
> Please do
[db12fcb18aabf3aeb5b0e6a54153807ef0fe9c557a29ef26b89930104c2caba5.gz](https://github.com/signalapp/Signal-Android/files/8318058/db12fcb18aabf3aeb5b0e6a54153807ef0fe9c557a29ef26b89930104c2caba5.gz)
