### ISSUE TITLE
Brief connection interruption ends call with "Network failed!" but, once connection is back, all audio and outgoing video are resumed

### ISSUE THREAD

**Issue by drebs** [signalapp/Signal-Android#12086]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

During a (video or audio) call between A and B, a brief interruption in the Internet connection of A immediately causes its Signal to act as if the call had ended by showing a "Network failed!" screen. But, if the connection is quickly restored, two-way audio is resumed and, in the case of video calls, one-way video from A to B is also resumed.

At this point, A still sees the "Network failed!" screen and thinks the call has ended, but she can actually still hear B and B can still hear (and see, in case of video calls) her. If A tries to click "Cancel" and call B once again, this just leads back to the "Network failed!" screen. The only way A can hang up the call is using the button in the call notification, which is still there.

On the other side, A's audio (and video) just froze to B and, after some seconds, the call continues just as before with B being able to hear (and see in case of video calls) A just as before.

### Steps to reproduce

- Use Wi-Fi only in both devices (turn off mobile data).
- Establish a video call from A to B.
- In A, turn the Wi-Fi off and then immediately on again.
- Wait for the connection to be re-establish, and then wait for some seconds.

**Actual result:** A can now hear B once again, and B can now both see and hear A.

**Expected result:** All audio and video should cease and the call should end for B as well.

### Device info

I reproduced in more devices, but I'm submitting debug logs for 2:

**Device:** moto g(7) plus
**Android version:** 10
**Signal version:** 5.32.15

**Device:** RealMe 6 RMX2001
**Android version:** 11
**Signal version:** 5.32.15

### Link to debug log

- https://debuglogs.org/android/5.32.15/139d307079380d48fa47327ff051a5835996b1cc9355f9545b53bb7bc506c5de
- https://debuglogs.org/android/5.32.15/d1e9dcd04e12373281945607e2c678e6dd2c1edaf8e70b5a6a010e285aa6ea24

**Comment by cody-signal** [comment]
Thanks for the detailed report, we're already tracking this one internally, and hope to have a fix out soon.

**Comment by cody-signal** [comment]
Is this still occuring @drebs ?

**Comment by drebs** [comment]
> Is this still occuring @drebs ?

Not for me, in version 5.36.3. \o/

Thank you very much, long live Signal and open source software!
