### ISSUE TITLE
sending messages hangs until network change on pixel 5

### ISSUE THREAD

**Issue by benmayne** [signalapp/Signal-Android#12081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Several times a day, sending a message will hang until i force a network change. By network change I mean, either joining or leaving a wifi network or toggling mobile data on/off. This happens naturally if I walk outside of wifi range, but seems to hang indefinitely if I don't leave the network. This started within the last week and has happened on several different wifi networks and levels of cell reception. I have not noticed connectivity issues with any other apps or with my limited sms use within signal. 

I've restarted my phone several times in this time as well as "Reset Wi-Fi, mobile, and Bluetooth" in my system settings without it stopping. 

### Steps to reproduce
This is not deterministically reproducible. It seems to impact well under 10% of my messages on a given day. 

 - send a message, see the icon spinning for pending to send
![Screenshot_20220320-091952](https://user-images.githubusercontent.com/3374110/159178783-53fe024e-35ad-49dc-bc9d-92a83b317f50.png)
 - toggle wifi or network on/off 
 - see the message send 
![Screenshot_20220320-092058](https://user-images.githubusercontent.com/3374110/159178806-e6d30357-5d8c-476a-a899-64f3c5fde0e5.png)

### Device info

**Device:** Google Pixel 5
**Android version:** 12 with Feb 5 security update (I'm planning to update android versions right after filing this to see if it helps)
**Signal version:** 5.34.0
**Network:** Google Fi

### Link to debug log

Two sets of logs: 

One time I observed this happening right after sending a message on cell which I solved by toggling cell on/off
https://debuglogs.org/android/5.34.0/2440b284f2b80f83a30eb644fa7ba982ba9ac2ebe3f77cd39040234ba3a14ff8

Later I took logs when it happened on wifi and then again after switching and getting it to send on cell 
Right after first attempt: https://debuglogs.org/android/5.34.0/96ad97d7a5b1ec6f6e8ec907b3111c2d5684618c202d01de3a67a4f40aa13268
Right after turning wifi off and the message sends: https://debuglogs.org/android/5.34.0/699630f40c7dad99c80b054a6f6378646687c55bce167f4fcf1e861fd1dcd3f6

**Comment by EVOTk** [comment]
Same issue
I'm kill apps ans relauch for resolve...
Signal 5.34.0
Android 10
Honor 20

**Comment by voroninman** [comment]
The same for me. Restarting the app or turn on/off wifi sends the message. Pixel 3a with the latest OS.

**Comment by cody-signal** [comment]
Hey folks, thanks for the report, we're looking at this right now and hope to have a fix out into the 5.34.x beta line soon.

**Comment by EVOTk** [comment]
It's resolve for me
v5.34.4
