### ISSUE TITLE
Forwarding images to non-signal users

### ISSUE THREAD

**Issue by ethnh** [signalapp/Signal-Android#12087]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to forward an image I sent to another signal user on my phone, I get a "Failed to send" message. Saving and sending manually works fine

### Steps to reproduce
- Send an image to another user on signal
- Attempt to forward it to a non-signal contact on phone
- View error

**Actual result:** Error, image not sent as noted above
**Expected result:** Image should be forwarded

### Device info
**Device:** Pixel 4a
**Android version:** Android 12 Beta - Build S3B1.220218.004
**Signal version:** 5.33.7

**Comment by greyson-signal** [comment]
HI there, I can't reproduce. Can you please post a debuglog link? Thanks!

**Comment by EthanHindmarsh** [comment]
Hello,
https://debuglogs.org/android/5.33.7/ef3c293b6e6eaf8a5b892c5357e027965f8b99d0caf5d021a9ef897313214209
If it is relevant, I get the option to delete for me / delete for everyone
after forwarding 👍

**Comment by Tursko** [comment]
I just encountered this same issue and it completely bricked my app. I think I'm gonna have to delete it and restore from a backup. 

1. Forwarded an image from a Signal chat to an MMS chat (only happened with 1 specific image). 
2. It failed to send in the MMS chat. 
3. I went to delete the message and the "delete for everyone" option showed for some reason. Not thinking anything of it I clicked delete for all and now I just have a crash loop anytime I open signal. 

I'm trying to recover my app before I nuke it. Trying hard to get a debug log.

**Comment by EthanHindmarsh** [comment]
RE: Taylor
#12129 may be related to your issue, though that issue is open as well

**Comment by EthanHindmarsh** [comment]
Also related, #12135

**Comment by greyson-signal** [comment]
We made a decent number of changes to forwarding in 5.36, and I can't repro these issues. That'll probably hit beta in a couple days, let me know if this is still an issue :+1:
