### ISSUE TITLE
Editing Image Before Sending: Single Emoji in Textfield not Applied to Image

### ISSUE THREAD

**Issue by helmut-steiner** [signalapp/Signal-Android#12091]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When editing an image before sending it to a contact a single emoji which is applied to the image in the editor will not be applied to the sent image. Application: If you want to cover up sensitive information e.g. somebody's face in an image, the image will be displayed in the chat without the emoji. This is a privacy issue. 

This issue only arises if there is a single Emoji in the text applied to the image. Emojis with text are displayed correctly. It doesn't matter if there is text sent with the image in the message or not.

### Steps to reproduce
- Take an image
- Open it inside a chat in Signal
- Edit the image before sending and apply a single emoji in a text field
- Apply changes to image
- Send the image to your contact

**Actual result:** The image doesn't contain the emoji.
**Expected result:** The image should contain the emoji on the place specified during editing.

### Screenshots

![Screenshot_20220324-142309](https://user-images.githubusercontent.com/8708898/159925771-695f605c-4939-4f2c-867e-aa6e91fe482f.jpg)
![Screenshot_20220324-142254](https://user-images.githubusercontent.com/8708898/159925782-b1dd880e-a6fe-4eed-a064-551c4c44d95f.jpg)
![Screenshot_20220324-142242](https://user-images.githubusercontent.com/8708898/159925786-1b47044e-8cc9-4cd2-933f-4723aa8ef467.jpg)
![Screenshot_20220324-142210](https://user-images.githubusercontent.com/8708898/159925794-37c80909-1c32-4d57-932f-71a643a2251b.jpg)

### Device info
**Device:** OnePlus 5
**Android version:** Oxygen OS 10.0.1
**Signal version:** 5.32.15

### Link to debug log
https://debuglogs.org/android/5.32.15/2c2a3f8913b91521ffcadf718a5eb99785f2171d9626d922272bd483e89d6cc9

**Comment by greyson-signal** [comment]
Hey there, we're gonna look into it. I think it's a device-specific or android-version-specific problem because I can't repro on my Pixel 5.

**Comment by helmut-steiner** [comment]
I tried it on another Android device and it seems this issue is indeed device or android-version specific.

**Comment by cody-signal** [comment]
@helmut-steiner can you try on a later version of the app and let us know if this is still happening?

**Comment by helmut-steiner** [comment]
I moved to a new phone. I can try with the old one at the end of next week and let you know.

**Comment by greyson-signal** [comment]
The way I "fixed" this was to disable emoji in the text view if the device didn't support rendering emojis above a certain size. Couldn't really figure out any other reliable way to address this. I did this a couple months ago though, so I'll close this.
