### ISSUE TITLE
Signal video call initiates call to US numbers

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-Android#12097]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic
- [X] I hope iOS bug regarding no notifications will be resolved in a reasonable time
----------------------------------------

### Bug description
My wife try to call me (from Macedonian to Slovenian number) but via Signal app. When she press to "camera icon" (try to initiate video call), she gets a message saying: "Your network does not support video calls" and video is off..

Then Signal starts to ring, but at the same time phone starts to call to US number in Minessota! When she tried to video call her sister (through Signal app), similar thing happened, but phone started to call to Pennsylvania. 

This is happening consistently (is repeatable) and is definitively not normal.

### Screenshots

Example of call log from Android:
![image](https://user-images.githubusercontent.com/3339198/160187336-f0ad000c-6946-4bed-9016-6884886504a8.png)

When she tried to call me with video call, Signal started calling:
![image](https://user-images.githubusercontent.com/3339198/160188668-c5565956-7ca7-4ba0-ab51-8bef9180f1c5.png)

But at the same time ordinary call was initiated:
![image](https://user-images.githubusercontent.com/3339198/160188854-0fe6afaa-1c02-41ae-bf75-43c025cc7995.png)

### Device info
**Device:** Huawei P20 Lite, model ANE-LX1 
**Android version:** 9
**Signal version:** 5.34.4

**Comment by MatejKovacic** [comment]
Additional info - the same is happening after prone reboot.

She can call me with Signal audio call, and then switch to video call. But directly video calling is not working.

**Comment by hiqua** [comment]
Debug logs?

**Comment by clauz9** [comment]
this might be of interest
![image](https://user-images.githubusercontent.com/77681918/160232097-6d399dc4-4a6c-4659-92bc-bd6df78c5f9a.png)
[source](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-33-release/42513/133?u=clauz)  

[additional information](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-33-release/42513/160?u=clauz)

They have integrated Signal calls with Android's [telecom framework](https://developer.android.com/guide/topics/connectivity/telecom) but that requires a phone number be passed from the app to the OS, and Signal being Signal is trying to not give your contact's actual phone number to the OS so they're generating a random one, that gets handed to the OS.

but it seems some phone brands are more trigger happy then others and start calling the number 😆

**Comment by MatejKovacic** [comment]
Debug log: https://debuglogs.org/android/5.34.4/0789407847c0b95a2bb25cb4a9551a4c2c5f55d2dc83f6c727e8c3e5a5a5ab74

Debug log was captured today, the weird behavior happened yesterday.

**Comment by MatejKovacic** [comment]
If you need more "fresh" debug log, let me know.

**Comment by csabu16** [comment]
I have the same issue: https://debuglogs.org/android/5.34.4/4acfae63865cceea7c9f84b2e80517f0cc18eca855b711c661c229b6cc80b232

**Comment by michelm117** [comment]
I have the same issue.
I tried to call someone 2 times. The first number it called was +11965550000. After 5 minutes a tried again. This time it called a number from California +12095550000. 

P20 pro
Model: CLT-L29
Android 10

https://debuglogs.org/android/5.34.4/ca5764adbe24399e76e973f542d5dff290bb6015160298a5b2cac19c789303d7

**Comment by clauz9** [comment]
it seams Huawei does some funky stuff too... @cody-signal  you might want to know about this

**Comment by johanw666** [comment]
Completely disabeling it for everyone is a "fix"?

**Comment by greyson-signal** [comment]
When a release goes to everyone that causes a bad issue like this, then yeah, reverting it is the fix :) We'll try again in the next release and will likely need to maintain a more extensive list of blocked manufacturers.

**Comment by moejoeward** [comment]
Update: Somewhere between the 29th or 30th of March, I was able to make calls again on my device. I no longer have the calling problem as of now.
