### ISSUE TITLE
Videos sent from Signal Android are received as black on Signal iPhone

### ISSUE THREAD

**Issue by vadi2** [signalapp/Signal-Android#12099]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending a video from an Android to an iPhone device results in the received video being all black. This happens sporadically for pre-recorded videos only; videos recorded from within the app itself are fine.

This lack of reliability in sending videos is problematic and frustrating.

### Steps to reproduce
- select and send pre-recorded video
- watch video on receiving phone - all black

### Device info

**Device:** Samsung A52s 5G
**Android version:** 12
**Signal version:** 5.34.4

**Comment by greyson-signal** [comment]
Hi there, are the videos playable on your device? Also, I know it happens sporadically, but if any of these videos are acceptable to be shared with us (or you managed to reproduce it with a test video), you can email it to greyson@signal.org, and that would be super helpful. Thanks!

(And per usual, debuglogs from the sending and receiving device will also be helpful)

**Comment by vadi2** [comment]
They are playable on my device and in my Signal conversation as well. I'll send a video over when it happens!

**Comment by vadi2** [comment]
Mail sent.

**Comment by lindemeier** [comment]
Similar problem here.
Recording videos outside the app. 
Sending the video via signal then results in black screen on iphones.

**Comment by UnreachableCode** [comment]
I just got this too for an archived meme video I downloaded from Google Photos, my iPhone friends couldn't watch it. Format is MP4 or MPEG (same thing?) Here's a screen of the video name and extension after I downloaded it back from Signal 
![Screenshot_20220530-134453__01](https://user-images.githubusercontent.com/1167553/170995592-8763a56c-94f7-4cf9-8528-0fe35be6d68b.jpg)

**Comment by cody-signal** [comment]
@UnreachableCode if the video is acceptable to share, please send it to us so we can try to reproduce.

**Comment by UnreachableCode** [comment]
It's not safe for work, if that's fine with you?

**Comment by cody-signal** [comment]
No, thanks for asking.

If you can try to send to an iOS user again and get debuglogs from your device and their device that would be helpful.

**Comment by vadi2** [comment]
I've sent a video before, have you received it?

**Comment by cody-signal** [comment]
I'll ask Greyson as he asked for it previously it appears.

**Comment by vadi2** [comment]
This is still an issue and the ball is in Signal court's devs.

**Comment by dernassesmart** [comment]
Is there a solution for this problem?

**Comment by vadi2** [comment]
It hasn't happened to me lately anymore.
