### ISSUE TITLE
IOS 15.4 App deregistered and continues to spontaneously deregister after reinstall. 

### ISSUE THREAD

**Issue by razausman** [signalapp/Signal-Android#12096]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Device: Iphone 11
Current Software version: 15.4
Problem occurred when software version was 15.3. I tried to register and it would hang. I then upgraded to 15.4 and it allows me to register but the problem persists. It lets me register but right after I send a message it deregisters. 
I have turned off my VPN and tried registration without success. It keeps getting deregistered. 
It may be a coincidence but signal started acting up when I received a suspicious audio file on Whatsapp from a friend. I have ZoneAlarm on IOS and the VPN on it may also have got disabled at the same time (both were working fine before then both were not working but i'm not sure if it happened at the exact same time) . However when I upgraded IOS the VPN started working. I talked to ZoneAlarm and they thought it was not an issue and was related to the upgrade. 

### Steps to reproduce
- register device
- send message
- It deregisters

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Signal does not send the message and says the phone is deregistered. When I go back on the chats screen the yellow deregistration message flickers repeatedly. See attached mov file. 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
It lets me chat? 

### Screenshots

https://user-images.githubusercontent.com/20649679/160136725-21cd19c9-61d9-46db-916d-01b302b0c23e.MOV

### Device info

**Device:** Apple Iphone 11
**Android version:** 0.0.0
**Signal version:** 5.33.0.25

### Link to debug log

https://debuglogs.org/ios/5.33.0/a4ebedc99953da45e4b69a0893dfea3a03c343afb9e9d4b49d3bd2445bc4d6b3.zip
BTW the debug link is in help on IOS. This is inaccurate
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by greyson-signal** [comment]
Hi there, this is the issue tracker for the Android app. Here is the tracker for the iOS app. Thank you!
https://github.com/signalapp/Signal-iOS/issues
