### ISSUE TITLE
Can't capture screenshot of TextSecure

### ISSUE THREAD

**Issue by pfctdayelise** [signalapp/Signal-Android#121]
Just wondering, has TextSecure somehow deliberately disabled screenshots?

When I attempt to take on on my Samsung Galaxy S3, it has an error "Couldn't capture screenshot: Couldn't save screenshot. Storage may be in use".

I am able to screenshot the native Messaging app and the home page and so on.

This is using the Power+Home button combination.

**Comment by williscool** [comment]
was a toggle feature ever requested? if not I will

**Comment by riyapenn** [comment]
@williscool Check out http://support.whispersystems.org/hc/en-us/articles/213191027-Can-I-take-a-screenshot-

**Comment by williscool** [comment]
@riyapenn thanks!
