### ISSUE TITLE
Insecure Call Does not Actually Call

### ISSUE THREAD

**Issue by elibroftw** [signalapp/Signal-Android#12102]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I click the call icon, Signal repeatedly tells me it won't be safe. There should be an option to disable this popup because it's super annoying combined with the next sentence. After clicking okay to the dialog, Signal only auto fills the number into the phone app but does not actually make the call. What the hell? The UX is terrible. Just call the person!

### Steps to reproduce
- open chat on signal with someone who doesn't have signal
- press call

**Actual result:** I get a popup that can't be disabled and agreeing to the popup does not call the person, only auto fills the phone app
**Expected result:** Ability to disable future popups and the actual call starting rather than requiring more user input.

### Screenshots
![Screenshot_20220328-172007__01](https://user-images.githubusercontent.com/21298211/160489815-43c4e0e6-f6cd-404d-a22f-f06d979d40d7.jpg)
![Screenshot_20220328-172112__01](https://user-images.githubusercontent.com/21298211/160489817-97946498-b122-4f3f-a359-b78cda4c93ce.jpg)

### Device info

**Device:** Oneplus 6T
**Android version:** 12
**Signal version:** Latest

**Comment by greyson-signal** [comment]
Hi there, I understand the frustration, but for now I think we'll keep this behavior as-is. Thanks!

**Comment by elibroftw** [comment]
@greyson-signal Why are you thanking me if you don't care about my opinion?

**Comment by Tursko** [comment]
I do agree that this seems like an odd design decision. The pop-up is already the confirmation. Seems like a good feature request.
