### ISSUE TITLE
Unknown Message Appearance in Notes to Self

### ISSUE THREAD

**Issue by aesrentai** [signalapp/Signal-Android#12107]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A message (which appears to contain a phishing link) appeared in my Notes to Self that I did _not_ send.  It does _not_ appear on my Signal Desktop notes since it apparently was sent via MMS.

### Steps to reproduce
- None, I didn't do anything to receive this message

**Actual result:** Foreign message appeared in my Notes to Self
**Expected result:** Only I can write notes to myself

### Screenshots
![Screenshot of the message in my notes to self](https://user-images.githubusercontent.com/48196236/161163923-d53e1814-817f-46e4-bb87-57f051095be3.jpeg)

![Unknown message info](https://user-images.githubusercontent.com/48196236/161164329-66eefcb6-b6f1-4a9b-b703-16a93c85e7c0.jpeg)

### Device info

**Device:** Pixel 4a
**Android version:** 12
**Signal version:** 5.34.5

### Link to debug log

This is one day old unfortunately, I don't think it'll be very useful

https://debuglogs.org/android/5.34.5/8f9f0fc60cb06a6e6aeb8ee4fea3a4b65a003c173f99cff3ba4e29bbe789cd4d

**Comment by UserX404** [comment]
Keep in mind it's an Sms and not a Signal message. So you would also receive it with other Sms apps.
But this has been fixed within the actual beta.
https://github.com/signalapp/Signal-Android/commit/c7a345eb0bb56026ad07fa7d66e872650b1521e6

**Comment by Sgn-32** [comment]
See also:
https://community.signalusers.org/t/received-a-spam-message-through-note-to-self/43036
