### ISSUE TITLE
Chat scrolls when new messages are received

### ISSUE THREAD

**Issue by Kitsume** [signalapp/Signal-Android#1211]
When being in a chat and messages are received the chat scrolls with them to the most recent message. So when you have received something over 100 messages (like when you are in an active group chat) you have to scroll quite some time up until you reach the part you read last.
It would be far more convenient if the chat stayed where you left it/where the new received messages start and you could then just continue reading.

**Comment by 1337sup3rh4x0r** [comment]
Are there any plans about this behaviour? 
Will there be an optional setting to have TS always open a conversation at the point where the user left it?

I'm currently trying to have my buddies drop whatsapp for TextSecure and this is really keeping everybody from switching.

**Comment by ki113r1337** [comment]
I totally agree with @generalmanager and @sagischwarz .
I would prefer that when you open the Chat again, you are where you left off. Then an arrow can appear to scroll straight to the bottom.
Also the automatic scrolling to the bottom when new messages are received is annoying.

**Comment by 1337sup3rh4x0r** [comment]
Are there any plans on this in the near future? 
Are you planning to make scrolling optional? 
Would you welcome and include a pull request that implements this optional setting?
