### ISSUE TITLE
Crash trying to add text to an image

### ISSUE THREAD

**Issue by zznidar** [signalapp/Signal-Android#12128]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I select the Add Text option when editing an image within Signal, the activity seems to crash (image is lost, conversation is closed, white screen shows for a moment, then the conversation list appears).

### Steps to reproduce
- Open a conversation (or from the conversations list)
- Take an image (or select one from gallery)
- Tap the pencil icon to edit the image
- Tap the text icon

**Actual result:** Signal crashes
**Expected result:** Text editing tool should show up

### Device info

**Device:** Poco F1
**Android version:** Android 10
**Signal version:** 5.34.5

### Link to debug log
https://debuglogs.org/android/5.34.5/bb5a71026f9aca856ce245b70a60c3922e62a2a1ee9aeecc5e2c579b3c498e94

**Comment by cody-signal** [comment]
Thanks, we fixed this on a later version, but I didn't realize this was impacting folks in 5.34.5 land. Check for an update soon or hop into the beta to get this fixed sooner. But we should be rolling it out shortly.

**Comment by clauz9** [comment]
@zznidar consider closing this please, if the issue is fixed in the most recent version

**Comment by zznidar** [comment]
I can confirm this is fixed in 5.34.10. Thanks, closing.
