### ISSUE TITLE
Audio Message Length Can Overlap with Timestamp 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#12125]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio msg length and msg timestamp will occasionally render on each other 

Might be a duplicate of #11677

### Steps to reproduce
I can't consistently reproduce it. Maybe it has to do with having multiple audio messages back to back? I find if I scroll up and down a convo fast this occurs 

### Screenshots
![signal-2022-04-05-20-31-57-829.jpg](https://user-images.githubusercontent.com/22125581/161878742-7516746d-bd5a-48c2-8e0b-e88ddf49f930.jpg)

### Device info

**Signal version:** 5.34.4

**Comment by bitmold** [comment]
Was this released ?

**Comment by UserX404** [comment]
Maybe this commit
https://github.com/signalapp/Signal-Android/commit/dabd1312225cde4ca0c84189371ea9dc3d8c9871
