### ISSUE TITLE
Wiki for Submitting-useful-bug-reports has incorrect info about where to go

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#12122]
I searched for this and didn't find it. Most of the stuff in the bug report template doesn't apply to this. Just need a quick wiki update to fix it. 

From: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports 

![image](https://user-images.githubusercontent.com/704514/161437108-7e9a8c35-b0f1-4e0c-9963-758069f92256.png)

That's incorrect. It should be `Settings -> Help -> Debug log`.

**Comment by Herohtar** [comment]
I think the Wiki is open for anyone to edit, so if you see a problem you can just correct it yourself, which is why there isn't an issue template for it. I've gone ahead and updated the step.
