### ISSUE TITLE
"Network Failed" screen covering up actual video call

### ISSUE THREAD

**Issue by givensuman** [signalapp/Signal-Android#12138]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I switched to Signal with my girlfriend and we do video calls almost nightly. I've run into a regular issue in which if I change rooms, typically to a room with slightly worse wireless signal, the call will often flash to a "Network Failed" screen, which is just my video in full-screen and a "Network Failed" button. This is fixed simply by ending the call and recalling. Notably, audio never cuts out, and my video is still transmitted to her.

In our last call, the bug happened multiple times across multiple calls, which was a little frustrating. Oddly enough, when I ended the call, it this time briefly flashed from the full screen of my face with an error message described above to her video -- not a still from when I lost connection, but a frame or two of our current call before shutting off. My phone has been sluggish since it got some water damage which is what I think allowed me to notice this.

This suggests to me that the "Network Failed" page has no way of reconnecting to a video stream, and is sort of a dead-end so to speak. It seems that there was a video connection happening behind a facade error screen.

A button to attempt to reestablish connection, or simply a process to automatically do so would be appropriate here, I think.

### Device info

**Device:** Samsung SM-J737T
**Android version:** 9
**Signal version:** 5.32.15

### Link to debug log
https://debuglogs.org/android/5.32.15/58c2668c4e1f75c54934c17c6d0c795db9946e7e6f11f13ccd582788e5e7353a

**Comment by cody-signal** [comment]
Thanks for the report, tracking internally.

**Comment by cody-signal** [comment]
Can you try on a later version of Signal, something in the 5.34.x range or later?

**Comment by cody-signal** [comment]
@cain-dev can you provide an updated debuglog as well?
