### ISSUE TITLE
SMS group broadcast not working

### ISSUE THREAD

**Issue by tcely** [signalapp/Signal-Android#12131]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to send a link to a SMS group using the broadcast distribution type. It never works for me.

### Steps to reproduce
- use a SMS group
- select broadcast instead of conversation
- try sending a message

**Actual result:**
The message is reported as not sent.

**Expected result:**

The message was sent as a SMS to each member of the group.

### Screenshots

![Screenshot_20220408-151732](https://user-images.githubusercontent.com/138864/162510370-13f3283f-a7fc-41ba-aeff-6f4b6ccf5092.png)
![Screenshot_20220408-151638](https://user-images.githubusercontent.com/138864/162510306-d32bb2cc-797f-43eb-83f8-03217c2c33b6.png)

### Device info

**Device:** Google Pixel 3a XL
**Android version:** 12 April 2022 update
**Signal version:** 5.34.10

### Link to debug log

https://debuglogs.org/android/5.34.10/b232e0d01f15b2388b22b4ede6ce085ab487def8d1c54f5bbe1bc375794ff499

**Comment by jliebers** [comment]
Maybe this is related to other broken SMS functionality such as in #11444

**Comment by tcely** [comment]
> Maybe this is related to other broken SMS functionality such as in #11444

I'd be curious to know why you think so.
