### ISSUE TITLE
Compare names screen will not open

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12132]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When two users in a group have the same profile name Signal shows a banner. Sometimes when I see this banner and tap on "compare names" (I believe in English it is called "review" but whatever), the screen won't open. I can tap it as often as I like and I see the animation of a screen immediately closing but I never reach the comparison screen.

On a side note: There should be a possibility to reach the name comparison screen even after dismissing the banner. That option is still missing in Signal.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0.0
**Signal version:** 5.35.0 (existed in some previous versions as well)

### Link to debug log

https://debuglogs.org/android/5.34.10/8807fde3f529562029b4725d620edbe2879e0807a216736af4c3506ccabf2833

**Comment by cody-signal** [comment]
Thanks for the report, tracking the not opening bug. If you leave the conversation and come back does the banner reshow?

**Comment by Meteor0id** [comment]
I think it did but I can't be sure because it's been a few day and I am not currently seeing the issue. It will happen again some time

**Comment by Kage1** [comment]
This is still an issue in the current beta version.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-6-release/50230/42?u=orclev159

**Comment by Kage1** [comment]
> Thanks for the report, tracking the not opening bug. If you leave the conversation and come back does the banner reshow?

Based on your question above, no when I go back to that contact the review link is no longer there.
