### ISSUE TITLE
Calls via the Signal (Android) app switch to hybrid mode despite WLAN

### ISSUE THREAD

**Issue by hindicc71** [signalapp/Signal-Android#12141]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
Calls via the Signal (Android) app switch to hybrid mode despite WLAN. This means that I see WLAN characters + 4G mobile network during a Signal call or video call (doesn’t matter). If I’m not mistaken, I was able to determine that mobile data volume is not deducted, but it still annoys me that something happens that should not happen. I installed several apps for testing and it was the same with none except Google Duo.

### Steps to reproduce
Start call and observe network activity

**Actual result:** It is visible on the device that it constantly switches between wifi and 4g although wifi reception is very good. To rule this out, I have also tested other apps and there this problem does not occur. E.g. Threema, WhatsApp, Telegram and so on.
**Expected result:** No switching between networks.

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 10
**Signal version:** 5.34.10

**Comment by cody-signal** [comment]
@hindicc71 can you provide an updated debuglog?
