### ISSUE TITLE
Calander variable not getting used on updated donation string

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12145]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a previous version of Signal this string mentioned the next moment on which the subsription will get renewed (exactly one month later). The string was updated to mention the new amount, but on doing so the date was removed. The variable is still there but not being used anymore. The old string also still exists in srings.xml.

https://github.com/signalapp/Signal-Android/blob/d11e8ec04b0b0a66649775e0eb84ce6e51abbb00/app/src/main/java/org/thoughtcrime/securesms/components/settings/app/subscription/subscribe/SubscribeFragment.kt#L226

In my opinion mentioning the date is useful, the string could be rewritten to include both variables. Exactly matching the text as seen on iOS is mot the most important here, it's just a confirmation popup.

This might just be an example of old code which hasn't been cleaned up yet. Not a big deal but maybe these kind of things could be aitomatically detected and cleaned up.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 5.35.0

**Comment by u32i64** [comment]
Just noticed this issue... If the resolution ends up being to remove the old string and not change the new one, I've done that in https://github.com/signalapp/Signal-Android/pull/12146.

**Comment by u32i64** [comment]
#12146 has been merged in https://github.com/signalapp/Signal-Android/commit/23939aeee30ea88acd6ca5cad6ebd4ea97283ed1, so this issue can probably be closed.
