### ISSUE TITLE
Immediate crash on backup restore

### ISSUE THREAD

**Issue by lehmanju** [signalapp/Signal-Android#12159]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Restoring a backup on a freshly installed android device leads to an immediate crash of Signal. After opening the app, choosing a backup to restore and providing a passphrase, the app immediately crashes. It doesn't matter whether it is the correct or incorrect passphrase. The backup is 1.3GB large and usually takes a few seconds to restore. It has been created by the recent stable Signal version, but judging by the exception this is not where the problem originates.

The log contains a reference to [this](https://github.com/signalapp/Signal-Android/blob/4098f77e08e1ca489f5b268d494af4b1455e41e7/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupImporter.java#L127
) line which results in an `IllegalStateException` complaining about no current transaction. I suspect Signal doesn't even begin to read the backup and fails earlier.

### Steps to reproduce
- Open a clean Signal app
- Restore backup
- Choose backup file from internal or sdcard storage
- Input passphrase or any other number combination

**Actual result:** Immediate crash
**Expected result:** Successfully restore backup or provide helpful error message.

### Device info

**Device:** Xiaomi Redmi 8T
**Android version:** 12
**Signal version:** 5.35.1

### Link to debug log

https://debuglogs.org/android/5.35.1/435afd5aaa4834348bf6732beaf8ffc9bb5a7038a4905920f3cdf0afd8c92d42

**Comment by lehmanju** [comment]
Ah, I found the error. `try{} finally{}` swallows the original exception if a new exception occurs in the `finally` block. This should probably be fixed.

Other than that, my backup files only contained 0s, no idea why.

**Comment by greyson-signal** [comment]
Yeah I think we have some ordering problems in the try-finally (we should normally be starting the transaction at the very beginning, but we were doing it after a possible IOException) which masked a different issue. I'm guessing that issue was a bad backup file or bad password.

We have longer-term plans to build a better backup validation system, sorry!
