### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by goodforever** [signalapp/Signal-Android#12156]
### Bug description

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 23s

Steps :

git clone https://github.com/signalapp/Signal-Android.git
cd Signal-Android
git checkout -f v5.35.1 -b v5.35.1
./gradlew clean assembleWebsiteRelease --exclude-task signProductionWebsiteRelease

With '--warning-mode all' logs:

./gradlew clean assembleWebsiteRelease --exclude-task signProductionWebsiteRelease --warning-mode all

enableFeaturePreview('VERSION_CATALOGS') has been deprecated. This is scheduled to be removed in Gradle 8.0. The feature flag is no longer relevant, please remove it from your settings file. See https://docs.gradle.org/7.4.1/userguide/feature_lifecycle.html#feature_preview for more details.
        at settings_djgkide1fq9g0dkqn2k9tt3mw.run(/Users/foo/Signal-Android/settings.gradle:1)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The VersionCatalogBuilder.alias(String) method has been deprecated. This is scheduled to be removed in Gradle 8.0. Use one of the more specifically named methods (library or plugin) instead Consult the upgrading guide for further information: https://docs.gradle.org/7.4.1/userguide/upgrading_version_7.html#version_catalog_deprecations
        at dependencies_adspe8nsfod6ysgzmyxcjq4zg$_run_closure1$_closure2$_closure3.doCall(/Users/foo/Signal-Android/dependencies.gradle:15)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :
The RepositoryHandler.jcenter(Action<MavenArtifactRepository>) method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral(Action<MavenArtifactRepository> instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.4.1/userguide/upgrading_version_6.html#jcenter_deprecation
        at build_dkby8vpzfj62pdhkrsfw9laz8$_run_closure1$_closure2.doCall(/Users/foo/Signal-Android/build.gradle:9)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :Signal-Android
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
WARNING:BuildType(spinner): buildConfigField 'BUILD_VARIANT_TYPE' value is being replaced.
WARNING:BuildType(perf): buildConfigField 'BUILD_VARIANT_TYPE' value is being replaced.
Using force on a dependency has been deprecated. This is scheduled to be removed in Gradle 8.0. Consider using strict version constraints instead (version { strictly ... } }). Consult the upgrading guide for further information: https://docs.gradle.org/7.4.1/userguide/upgrading_version_5.html#forced_dependencies
        at build_bt1q2aybogdsopkwzvz0ppdoy$_run_closure5$_closure66.doCall(/Users/foo/Signal-Android/app/build.gradle:536)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
WARNING:API 'BaseVariant.getApplicationIdTextResource' is obsolete and has been replaced with 'VariantProperties.applicationId'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see TBD.
To determine what is calling BaseVariant.getApplicationIdTextResource, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'signProductionWebsiteRelease' not found in root project 'Signal'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
5 actionable tasks: 5 up-to-date

**Comment by clauz9** [comment]
> ./gradlew clean assembleWebsiteRelease --exclude-task signProductionWebsiteRelease

https://github.com/signalapp/Signal-Android/blob/d401386e2d22ed9eab1d2d596c7c727507cf986b/app/build.gradle#L90-L91 

the build.gradle file does not contain "WebsiteRelease" as a build variant, so maybe try

`./gradlew clean assembleWebsiteProdRelease`

I just  tied it out, and it works, no need to exclude that task anymore. 

remember to close this issue, after you test it out, and confirm that it builds

**Comment by greyson-signal** [comment]
Hi there, we have daily jobs that ensure that signal builds with the included [docker image](https://github.com/signalapp/Signal-Android/tree/master/reproducible-builds). For development help, please use the [forum](https://community.signalusers.org/). Thanks!

**Comment by goodforever** [comment]
@clauz9 Thanks !  BUILD SUCCESSFUL in 21m 55s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 21m 55s
261 actionable tasks: 248 executed, 13 up-to-date
