### ISSUE TITLE
Speakerphone only (always)

### ISSUE THREAD

**Issue by MuhammadAzamat** [signalapp/Signal-Android#12151]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On older signal versions on Androi 12 phone after hang up video call on both devices only loudy speakerphone is ON.

### Steps to reproduce
- install older signal android version (ex. 4.66.1) on Android 12 phone
- call in video calling mode
- after successful connection hangup.
- Cal second time

**Actual result:** Speakerphon is ON Always.
**Expected result:** speakerphone off, can switch sound to speakerphon and reverse

### Device info

**Device:** Pixel 5, Pixel 5a
**Android version:** 12
**Signal version:** 4.66.1

**Comment by greyson-signal** [comment]
Hi there, we don't support old versions of the app. We have a singular line of releases. Feel free to open a new issue if it happens on the current beta/production version. Thanks!

**Comment by MuhammadAzamat** [comment]
HI there,
Can You just link in which version or commit You fixed such problem?

**Comment by greyson-signal** [comment]
The version you're running is almost 2 years old. A *lot* of changes have been made to calling. I couldn't tell you what version, apologies.

**Comment by MuhammadAzamat** [comment]
@greyson-signal Thanks, I will try find it.
