### ISSUE TITLE
feature request: schedule a message to send later

### ISSUE THREAD

**Issue by CommunistSpectator** [signalapp/Signal-Android#12160]
please add a feature to schedule messages to be sent later.

**Comment by clauz9** [comment]
you conveniently deleted the issue template, that would've had you sign that "This isn't a feature request" 
and blew past the option of opening an actual feature request 

![image](https://user-images.githubusercontent.com/77681918/163393773-3ed3d63d-97e0-48cc-90ca-c339b4768619.png)

which would've taken you to the appropriate place to open a feature request
where you can find an existing feature request for scheduling a message 

https://community.signalusers.org/t/scheduled-send-of-messages/2568

Please close this "issue"
