### ISSUE TITLE
Deleted a contact on my phone yet it still appears in Signal.

### ISSUE THREAD

**Issue by X3X3YY** [signalapp/Signal-Android#12169]
Identical to this iOS ticket:

https://github.com/signalapp/Signal-iOS/issues/4892

This means that this issue has been ignored for some quite time now. 

This is a potential privacy issue.

**Comment by X3X3YY** [comment]
The usual "remove Signal account" and then "refresh Signal contact list" workaround DOES NOT WORK.

**Comment by greyson-signal** [comment]
Closing as a duplicate of #10891. You can read my comment here: https://github.com/signalapp/Signal-Android/issues/10891#issuecomment-1079067370
