### ISSUE TITLE
One or more items were invalid after selecting and then after deselecting an image from the gallery

### ISSUE THREAD

**Issue by MedzikUser** [signalapp/Signal-Android#12163]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- go to any chat
- click +
- gallery
- select any image and then deselect it
![Screenshot_2022-04-14-20-46-34-90_4b14b257287ac0a6d1fd5fbb2487716f](https://user-images.githubusercontent.com/87065584/163459369-7175f0cd-f48d-41d0-95cd-75e206973b4f.jpg)

**Actual result:** I got the message "One or more items were invalid"
**Expected result:** it shouldn't be there

### Screenshots

![screenrecord](https://user-images.githubusercontent.com/87065584/163458770-164cf4ff-310a-4feb-825c-c1a9679b9265.gif)

### Device info

**Device:** Realme 8
**Android version:** 11 (January 5, 2022 patches) (ColorOS Official)
**Signal version:** 5.34.10

### Link to debug log

https://debuglogs.org/android/5.34.10/32ba4d919f63a0fdc2965fc90d0e9ad1e7b71bb9c51729b933abe32c3f95d0e1

**Comment by clauz9** [comment]
Can't really do much without a debuglog...

**Comment by MedzikUser** [comment]
> Can't really do much without a debuglog... you can get one, by going to Settings -> Help -> Debug log -> Submit then you can either add the link to your issue, or send it to the developers.

I thought it wouldn't be necessary.

**Comment by greyson-signal** [comment]
If you're getting that error, it means that the item you selected is not labeled by the system as an image or video. My assumption is that the system is feeding us a bad/weird contenttype, but having a log would help.

**Comment by clauz9** [comment]
> but having a log would help.

@greyson-signal you have one now.

> ### Link to debug log
> https://debuglogs.org/android/5.34.10/32ba4d919f63a0fdc2965fc90d0e9ad1e7b71bb9c51729b933abe32c3f95d0e1

**Comment by MedzikUser** [comment]
There is still

**Comment by MedzikUser** [comment]
In the new image chooser this problem does not occur
