### ISSUE TITLE
Note to Self warns that my safety number has changed

### ISSUE THREAD

**Issue by adakaleh** [signalapp/Signal-Android#12173]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
*Note to Self* warns me that my own safety number has changed. This does not occur in the desktop version of Signal, but only on my phone. Using Note to Self, I can send messages from my laptop to my phone without any warning. The safety number has not changed with any of my other contacts.

I'm not sure, but this may have been triggered by the fact that I added a new number for myself in the Android contacts app (I have not replaced my previous number, but added a new one).

Other users have also been affected:
https://community.signalusers.org/t/note-to-self-asking-me-to-verify-my-own-safety-number/43522

One of them has linked a debug log here:
https://community.signalusers.org/t/note-to-self-asking-me-to-verify-my-own-safety-number/43522/3

**Signal version:** 5.34.10

**Comment by cody-signal** [comment]
> I'm not sure, but this may have been triggered by the fact that I added a new number for myself in the Android contacts app (I have not replaced my previous number, but added a new one).

Can you elaborate what you mean by not replaced but added a new one? As in, you added a new contact to your phone with the same number that you use in Signal but it's also another used in another system contact?

**Comment by cody-signal** [comment]
If anyone else is experiencing this, reproduction steps would be greatly appreciated.

**Comment by cody-signal** [comment]
Could you post a screenshot of it? Did you see a banner at the top of screen saying "this number is no longer verified?" or something like that.

**Comment by adakaleh** [comment]
> Can you elaborate what you mean by not replaced but added a new one? As in, you added a new contact to your phone with the same number that you use in Signal but it's also another used in another system contact?

In the contacts app I have a "Me" entry, which had two numbers (mobile, home). I simply added a third (work).

> Could you post a screenshot of it? Did you see a banner at the top of screen saying "this number is no longer verified?" or something like that.

It's a banner at the top saying "Your safety number with Me has changed and is no longer verified". If I try to send a message, I get a pop-up telling me that "Me" (Note to Self) may have reinstalled or changed devices and asking me to verify the safety number to ensure privacy.

**Comment by cody-signal** [comment]
Okay, thank you for the extra details!

**Comment by cody-signal** [comment]
Do you have a linked desktop or ipad by chance?

**Comment by cody-signal** [comment]
Based on this report and what we've seen in the forum, we believe this is a bug on a linked device trying change the verified status for ourselves. The next beta will have a fix to ignore those messages and prevent this from happening. Feel free to verify yourself to get rid of the banner.

**Comment by adakaleh** [comment]
> Do you have a linked desktop or ipad by chance?

Yes, like I said, my laptop is linked.

> Based on this report and what we've seen in the forum, we believe this is a bug on a linked device trying change the verified status for ourselves.

This sentence doesn't make sense to me. Do you mind rephrasing?

> Feel free to verify yourself to get rid of the banner.

Are you *sure* a man-in-the-middle on Signal's end isn't trying to read our notes? :)
