### ISSUE TITLE
SMS/MMS export procedure

### ISSUE THREAD

**Issue by salustre** [signalapp/Signal-Android#12170]
Hi, 
Because SMS/MMS import feature has been abandoned, as described here.....  

https://github.com/signalapp/Signal-Android/issues/11653

I would like to stop using Signal as my default SMS app, please provide the procdeure to export SMS/MMS from Signal to Android database. 

Best regards

**Comment by greyson-signal** [comment]
Hi there, we use github for bug reports. For feature requests, please use the [forum](https://community.signalusers.org/).
