### ISSUE TITLE
Link previews can somewhat compromise location

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-Android#12171]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If you send a link preview of a website which is localized by virtue of its CDN, then the preview you'll see will contain local identifiers. For example "Current weather in Dallas". The question is, how far can this be taken? Can I compel you to send me a link preview of a website which encrypts your IP address and spits it out in a manner which will be echoed back to me in a link preview, so the sender is compromising his location without even knowing it? Or does this not work because the link preview is generated by Signal's own CDN, in which case the best I can do is to discover your locale, which is the locale of the nearest Signal CDN? I don't know enough to comment, but the lesser threat is readily reproducible.

### Steps to reproduce

Go to a site which serves localized content, ideally embedded in the page title or close to the top of  the page. Send a link to the site to a friend. (The home page will do. You don't need anything obvious like example.com/dallas)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Your friend will see the content localized to you, not to them.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Link previews should be independently resolved at both ends. So I see Dallas and you see Sydney.

I suppose the other option is just to give up and tell me that some degree of location compromise is unavoidable, and routing calls through Signal servers doesn't help because we're not talking about calls here. Speaking of which, I have to wonder whether those servers are also somewhat localized, so I can roughly approximate your location from the IPs stamped on the relayed packets. I don't know.

### Device info

I've tried this with a number of friends recently. The only commonality seems to be Android. It always happens as described.

**Comment by greyson-signal** [comment]
Link previews are generated by the sender's device. The sender has control over whether or not they want to attach a link preview, or whether the feature is enabled at all. In that sense, "compelling someone to send you a link preview" would require you to ask them to paste a link back into their composer and accept the link preview, which seems like a sufficiently high bar.

> Link previews should be independently resolved at both ends. So I see Dallas and you see Sydney.

This is far worse. Having a receiver generate the link preview means that senders could make the receiver contact a server with little-to-no user interaction, setting up much easier malicious scenarios.

If you have any further questions, please reach out to security@signal.org.
