### ISSUE TITLE
cannot open contact card in one-on-one conversation which I have not yet accepted

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12179]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I receive a message request I can't open the profile card. This is confusing, I want to see the options to block, and to enlarge profile image etc. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by alex-signal** [comment]
If you get a message request, your options to block should be listed at the bottom of the screen. Are these not present?

**Comment by Meteor0id** [comment]
Thosecare present but it is confusing and inconsistent that tapping the pofile does nothing. I can't enlarge their profile image to see who they are, and I am used to quickly looking at their phone number there but with a message request I have to look in the chst itself to find it. It's crom a UX perspective not right to not be able to tap this.
