### ISSUE TITLE
Transfer from Play Store APK to Website APK - cannot transfer from a newer versions of signal

### ISSUE THREAD

**Issue by aggroskater** [signalapp/Signal-Android#12180]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am attempting to transfer my Signal account from an old Blackberry KeyONE device running its stock ROM, with Signal acquired from the Play Store, to a Google Pixel 5a running GrapheneOS, with Signal acquired from the website. When I follow the instructions on the website, I ultimately run into an error: "Cannot transfer from a newer versions of Signal". There seems to be no way to manually trigger an update of the APK obtained from the signal.org website.

### Steps to reproduce
- Follow procedures documented here: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages
- Observe aforementioned error message on the device receiving the transfer.

**Actual result:** Get "Cannot transfer from a newer versions of Signal"
**Expected result:** Either that the transfer works, or else that there is a way to have the website-acquired Signal application auto-update.

### Screenshots

![Screenshot_20220420-001712](https://user-images.githubusercontent.com/943591/164155869-33f38ab2-febf-4c5a-950a-5e9dd4b390e9.png)

### Device info
**Device:** Google Pixel 5a
**Android version:** 12.0.0
**Signal version:** `5.35.3` on the older phone being transferred from, `5.34.10` on the newer device being transferred to.

**Comment by UserX404** [comment]
This is due to you were on beta. You need to wait for a stable 5.35 release.

**Comment by clauz9** [comment]
> This is due to you were on beta. You need to wait for a stable 5.35 release.

or update to 5.35.3 on the new device, if you're ok with being on the beta

**Comment by aggroskater** [comment]
>This is due to you were on beta. You need to wait for a stable 5.35 release.

Understood. I didn't think I had opted into a beta, but perhaps I did at some point?

>or update to 5.35.3 on the new device, if you're ok with being on the beta

Is there a way to do that from the APK downloaded off of the website? Or is there another spot to check for downloading beta APKs to my device? I did try manually adjusting the download URL to see if `5.35.3` was available, but that didn't work.

**Comment by clauz9** [comment]
You can search "Signal" on the play store from your new device and you will have an option to join the beta there. under the install/uninstall/open buttons

remember to leave the beta from the play store after you transfer your messages... so you will get updated to the stable version going forward.

**Comment by clauz9** [comment]
@aggroskater if you managed to transfer your conversations, and need no further help .. please remember to close this issue

**Comment by aggroskater** [comment]
>You can search "Signal" on the play store from your new device

GrapheneOS doesn't have the Google Play store, or even Google Services. Hence my need to obtain an install from the signal.org website directly. It sounds like I'll need to wait a while though (a few days? a few weeks?) for a 5.35.x release to be available at signal.org/apk/beta. In the meantime, I'll turn off automatic updates on my old device and keep it connected via WiFi. I'll update this issue once a new version is uploaded to the signal.org website.

**Comment by aggroskater** [comment]
Alrighty! Looks like [https://signal.org/android/apk/](https://signal.org/android/apk/) has version `5.35.3` now. Awesome :) I removed the old Signal APK from my GrapheneOS, and then downloaded the `5.35.3` APK from the website. Ultimately, it worked!

The process started off like this:

| ![Screenshot_20220420-160440](https://user-images.githubusercontent.com/943591/164328656-d4d448fb-7e87-4eb4-b386-fbdb79fa56ef.png) | ![Screenshot_20220420-160450](https://user-images.githubusercontent.com/943591/164329013-7df6aba1-7abd-43c8-93e0-96fb9f7973c5.png) |
|:--:|:--:| 
| Receiving Device - count of 100s of messages | Sending Device - percentage of messages |


But then it failed:

| ![Screenshot_20220420-161754](https://user-images.githubusercontent.com/943591/164329893-0d01825a-95c3-40fb-82e6-50e48ef9ff75.png) | ![Screenshot_20220420-161758](https://user-images.githubusercontent.com/943591/164329965-91599376-50fb-46e3-a786-b08bf83821e0.png) |
|:--:|:--:| 
| Receiving Device - failure | Sending Device - failure |

No worries. I had read that the process is a bit finicky and it's worth trying a couple times. So I retried the process, and on the second go 'round, it worked (I don't think it matters, but on the second go, I placed the devices on top of each-other, perpendicular to each-other):

| ![Screenshot_20220420-163750](https://user-images.githubusercontent.com/943591/164330458-db180314-9c81-4653-81b7-970209bab448.png) | ![Screenshot_20220420-163746](https://user-images.githubusercontent.com/943591/164330546-195f7c78-ce73-42ac-a3c0-8369e90fc80d.png) |
|:--:|:--:| 
| Receiving Device - Success | Sending Device - Success |

At which point I was then able to complete the configuration process on the receiving device, with the appropriate indications that Google Play Services were not available, and with configuring the device to always be on in the background:

| ![Screenshot_20220420-163826](https://user-images.githubusercontent.com/943591/164331380-55f96193-0469-458c-870b-4ed05373a2b3.png) | ![Screenshot_20220420-163836](https://user-images.githubusercontent.com/943591/164331660-fa4dab48-a7b8-4295-8061-d221f69d9150.png) |
|:--:|:--:| 
| Initial "Get Started" screen with appropriate prompt for Missing Google Play Services. I tapped "I understand" | Obtain and enter the verification code |
| ![Screenshot_20220420-163850](https://user-images.githubusercontent.com/943591/164331770-6d0b72b2-245c-443e-a44f-fa7eb1762f97.png) | ![Screenshot_20220420-163908-redacted](https://user-images.githubusercontent.com/943591/164332922-eac5264b-0a42-4a73-a1bd-95451ad73a82.png) |
| Input previously created Signal PIN | Notification about missing Google Play Services and "tap to disable system battery optimizations that prevent Signal from retrieving messages while inactive." I tapped the notification. |
| ![Screenshot_20220420-163940-redacted](https://user-images.githubusercontent.com/943591/164332991-fa6c0a5d-a04a-4b00-b409-ccc7c1b23fc9.png) |  |
| Get pop-up asking for permission. I tapped allow. | All done! |

Thanks so much to the Signal team for getting an updated APK out to the website! Feel free to use the above images as desired for documentation, as I know that this particular scenario is/was an edge case of an edge case, and I'm impressed and happy that Signal is able to ultimately handle it.

**Comment by clauz9** [comment]
Glad to hear it worked 👍
