### ISSUE TITLE
Question about message storage

### ISSUE THREAD

**Issue by dl200010** [signalapp/Signal-Android#12187]
This is just a question I have about this app. Where are the received messages stored? Are they stored in the MMSSMS.db like other SMS apps? I would like to know because I use a backup app that backs up that database using calls to the provider class. I developed this portion myself and would like to know if it would still be able to backup messages sent and received in Signal.

**Comment by Genis-Sage** [comment]
@dl200010 
Signal devs want to keep the Github issue tracker reserved for bug reports

so the right location to ask your question would be the community forum: https://community.signalusers.org/


but as your question is answered in one sentence:
no, Signal does store all messages in its own encrypted database
so if you use Signal for SMS and MMS, you don't have access to them

**Comment by dl200010** [comment]
Thanks. That is all I needed!
