### ISSUE TITLE
Tapping "show" on a message request profile picture does not show the profile picture

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12196]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- receive a message request
- do not accept nor decline
- tap "show" on the profile picture

**Actual result:** nothing happens
**Expected result:** the profile picture should load and be shown

If you leave the conversation the profile picture suddenly show, but that should have happened right away

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 5.36.2

**Comment by alex-signal** [comment]
Is this an issue with blurred profile photos? As in the photo doesn't get reloaded and is still blurry?

**Comment by Meteor0id** [comment]
That's right, If I want to unblur the image nothing seems to happen but once I leave the conversation the image suddenly unblurs. that's a little late, it should do that as soon as I tap or show some kind of loading icon to indicate my tap was effective. (But I tried waiting for a few minutes and it seemingly never loads until leaving the conversation)

**Comment by greyson-signal** [comment]
I can't reproduce in the 5.37 candidate ranch. It's instantly reactive. Please reopen if you see that it's still happening in 5.37.
