### ISSUE TITLE
Cannot block an entire group

### ISSUE THREAD

**Issue by cidetraq** [signalapp/Signal-Android#12190]
A support page led me to believe I could block a group entirely 
https://support.signal.org/hc/en-us/articles/360007060072-Block-numbers-or-groups
But I see no functionality for that on the Android app. 
![Screenshot_20220422-195827](https://user-images.githubusercontent.com/30700271/164844924-598102fe-ce77-45e6-a89c-9d0a192ec089.png)
I've also looked in settings and other places but I cannot find a way to block a group like I can in the stock Android messages app.

**Comment by Sgn-32** [comment]
The settings for "group leaving" and "group blocking" is below the "Shared media" in the group settings. At least for signal groups. This group is an MMS group. Maybe Signal has a different behavior here.

**Comment by Sgn-32** [comment]
Found this:

https://github.com/signalapp/Signal-Android/blob/efe7b3099fb67f72334d0de08f60bceb2c6f51f1/app/src/main/java/org/thoughtcrime/securesms/recipients/RecipientUtil.java#L113-L116

So MMS groups aren't blockable.
