### ISSUE TITLE
Possibility to download .apk from http://www.whispersystems.org/ or github repository

### ISSUE THREAD

**Issue by duy** [signalapp/Signal-Android#122]
It'd be great if the .apk app could be downloaded without the need to use google play or to compile the source code

**Comment by alanthehat** [comment]
One reason to avoid Play is that it still has the bug where it refuses to update or install anything, complaining about 'lack of storage' when there's lots free :-(

**Comment by alanthehat** [comment]
F-Droid is a well-known alternative app-store that works more often than Play & seems secure.

**Comment by mateoeh** [comment]
This discussion has already been hashed out, please read issue https://github.com/WhisperSystems/Signal-Android/issues/127.

**Comment by alanthehat** [comment]
@mateoeh I did. 
It seems to have taken me 3 hours. 
It didn't answer my issue. 
#127 is closed.
