### ISSUE TITLE
Signal 5.36 failed to compile on Windows

### ISSUE THREAD

**Issue by 0dvictor** [signalapp/Signal-Android#12201]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Building Signal 5.36 on Windows with Android Studio failed following error:
```
C:\path\to\Signal-Android\libsignal\service\src\main\java\org\whispersystems\signalservice\api\subscriptions\ActiveSubscription.java:255: error: unmappable character (0x9D) for encoding windows-1252
     * and may temporarily appear as “pending�? on a cardholder’s statement.
```

The failure is caused by non-ASCII quotation marks in comments of [`ActiveSubscription.java`](https://github.com/signalapp/Signal-Android/blob/efe7b3099fb67f72334d0de08f60bceb2c6f51f1/libsignal/service/src/main/java/org/whispersystems/signalservice/api/subscriptions/ActiveSubscription.java#L255).

### Steps to reproduce
- Checkout Signal 5.36.0 or 5.36.1 or 5.36.2
- Build with Android Studio on Windows

**Actual result:** Build finishes successfully without errors.
**Expected result:** Compilation failed.

### Device info

**Device:** N/A
**Android version:** N/A
**Signal version:** 5.36.0+

### Link to debug log

```
C:\path\to\Signal-Android\libsignal\service\src\main\java\org\whispersystems\signalservice\api\subscriptions\ActiveSubscription.java:255: error: unmappable character (0x9D) for encoding windows-1252
     * and may temporarily appear as “pending�? on a cardholder’s statement.
```

**Comment by gyancodes** [comment]
@0dvictor  Hey, can I work on this issue.

**Comment by 0dvictor** [comment]
> @0dvictor Hey, can I work on this issue.

Sorry that I already submitted PR #12202.

**Comment by gyancodes** [comment]
@0dvictor Thanks, No problem.

**Comment by clauz9** [comment]
@gyancodes you can work on any issue that is currently opened, in fact you can work on issues that perhaps you know about, but they are not on github. 

Just make a PR, and the devs will review it 👍 looking forward to your PR's
