### ISSUE TITLE
Crash on app startup due to ClassCastException

### ISSUE THREAD

**Issue by mgrobarek** [signalapp/Signal-Android#12207]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes immediately on startup. You can barely see the opening screen with all the conversations, then it’s gone. If you disable all Internet connections, it starts up without a crash (but obviously can’t receive/send any messages).

### Steps to reproduce
- Activate any Internet connection (Wifi or mobile data)
- Start Signal.

**Actual result:** Signal crashes (repeatedly).
**Expected result:** Signal should obviously not crash.

### Screenshots
Not fast enough to get one, but it’s only Android’s/Samsung’s crash message window. In Signal itself, there are no error messages or the like.

### Device info
**Device:** Samsung Galaxy A3 2016
**Android version:** 7.0
**Signal version:** 5.35.3

### Link to debug log
Not possible because uploading is only possible while being online, but this is when the app crashes.
But the log contains the following exception (paraphrased/abbreviated due to lack of copy/paste):

ClassCastException: String[] cannot be cast to org.conscrypt.ApplicationProtocolSelector
 at org.conscrypt.ApplicationProtocolSelectorAdaptor.<init>(ApplicationProtocolSelectorAdapter.java:45)
 at org.conscrypt.ConscryptFileDescriptorSocket.setApplicationProtocolSelector(ConscryptFileDescriptorSocket.java:1080)
 at org.conscrypt.OpenSSLSocketImpl.setAlpnProtocols(OpenSSLSocketImpl.java:155)
 …coming from okhttp3 internal classes…
 at org.thoughtcrime.securesms.net.DeviceTransferBlockingInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
 …coming from PushServiceSocket.getMessages()…

**Comment by cody-signal** [comment]
Hey there, sadly we need more to be able to see better about what's going on.  ANy chance you can screenshot it or use adb to capture more?

**Comment by mgrobarek** [comment]
I managed to stitch together screenshots from the stacktrace. If you need anything else, please tell me which part of it.
![Stacktrace](https://user-images.githubusercontent.com/70602401/165836665-e174a549-fd48-4b97-b8e3-07c038d580f8.png)
