### ISSUE TITLE
No option to delete message for all in "My notes".

### ISSUE THREAD

**Issue by TMMC** [signalapp/Signal-Android#12206]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While on desktop version you can delete message "For all" (devices in this case) in "My notes", mobile version allows you to remove it only for  the device it is installed on ("For me only"). A few versions back it was possible, but it was buggy - one could delete "For all" from Signal (Android) only the messages sent from Signal (Android) but from Signal Desktop it was possible for both messages sent from Signal (Android) and Signal Desktop - if I recall correctly. 

### Steps to reproduce
- Send message to yourself (My notes) - you can do it from Signal (Android) or Signal Desktop.
- Select and try to delete on Signal (Android) - do not delete the message, just see the options you have.
- Do the second step on Signal Desktop and see the options you have.

**Actual result:** On Signal (Android) you do not get the option to remove/delete for all.
**Expected result:** One should be able to remove "for all" in Signal (Android) the same way as in Signal Desktop.

### Device info
**Device:** Samsung A30s
**Android version:** 11
**Signal version:** 5.35.3

**Comment by olijg** [comment]
Perhaps the issue is instead a desktop issue, since there is only *one* user(me) in the Notes? What separate functionality would the delete for everyone option have in this scenario?

**Comment by cody-signal** [comment]
Hey there, it does seem like Android should be supporting this option. We think the UX should also be updated since saying "Everyone" is a bit misleading in Note to Self. We're tracking this internally and will get in when we can so we are in line with the other platforms.

**Comment by TMMC** [comment]
@cody-signal "For all", "My notes", "For me only" are only my loose translations of what I see in my default language. And yes, I agree "Everyone" can be misleading in that case, maybe "All devices" or "Everywhere".

**Comment by vadi2** [comment]
This is still an issue, could this be looked into? The 'note to self' feature should be able to delete notes for all devices.

**Comment by Tursko** [comment]
Now in beta: https://github.com/signalapp/Signal-Android/commit/f96c31b38f5849e47d7fa4fc61172f9c83cbadc1
