### ISSUE TITLE
Add new notification profile button has misaligned icon

### ISSUE THREAD

**Issue by Altonss** [signalapp/Signal-Android#12216]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Add new notification profile button is broken

### Steps to reproduce
- Open the notification profiles 3 times
- At the third time, you will see that the "plus" button to add a new profile is broken (misaligned, it's too low)

**Actual result:** New notification profile button is broken, it is misaligned
**Expected result:** The button should be aligned.

### Device info
**Device:** Samsung Galaxy Core Prime
**Android version:** 5.0.2
**Signal version:** 5.35.3

**Comment by cody-signal** [comment]
Can you provide a screenshot and debuglog, it contains screen size/density info that is typically helpful when troubleshooting UI issues.

**Comment by Altonss** [comment]
Sorry for my late reply, here are more details:
I guess that the full log might not be that usefull so here are the relevant details:
Screen: 480x480, xhdpi (240), 60.00 hz
Font Scale: 1.0
Android: 5.0.2, API 21
Emoji Version: 7 (xhdpi)
![image](https://user-images.githubusercontent.com/66519591/167267980-4c444adf-e11b-4cf4-a8fa-58a8c6c1e821.png)

**Comment by cody-signal** [comment]
I'm still unable to reproduce this, could you provide a full debuglog so I can see all of the stats? If you do not wish to share it publicly, you can send it to me directly at my email, cody at signal org

**Comment by Altonss** [comment]
At the first time opening the notification profile menu it doesn't happend, you need to try it several times (for me 2 times works: open it, close it, reopen it)!
https://debuglogs.org/android/5.35.3/8c9b1528b8a5c2495f1e6545c5d4298622c3eae4394ed7fbf704060d1043c760

**Comment by Altonss** [comment]
It also happens on 5.39.3

**Comment by Altonss** [comment]
This issue is still there!
Moreover the "down" arrows on the 2 profiles are not of the same size.

**Comment by Altonss** [comment]
Issue is not stale...

**Comment by Altonss** [comment]
I don't think the issue has been solved
