### ISSUE TITLE
"who can send to this group" permission missing

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12211]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a group some of us noticed we are admins but don't see the permission to change who can send to the group. That option is missing in the permissions menu. We do see permissions for who can edit the group and who can invite, but not for who can send. This looks like a bug.

### Device info

**Device:** Motorola Moto G7 plus
**Android version:** 10.0.0
**Signal version:** 5.36.3
I do also have Signal Desktop linked and it is up to date.

### Link to debug log

This is probably nothing new. See any of my other debug logs I guess.

**Comment by UserX404** [comment]
Isn't this beta related since 5.36.3 isn't a public release atm?
I checked settings in 5.35.3 in groups where i'm a admin and i see all three options, including 'who can send'.

**Comment by cody-signal** [comment]
For a group to become "announcement only" all members of the group must advertise the announcement group capability. What is likely happening is there's someone in the group that doesn't have an updated version of their primary or linked device and thus is reporting false. Or haven't been active and reported a new capability. Can you make a brand new group and see if the setting shows or check other groups with active members? Sadly we don't log anything right now if the UI is hidden for capability reasons.

**Comment by Meteor0id** [comment]
We figured one or more people in the group lack capability or have been inactive, but I guess the real problem here is that we don't want to have to create a new group every year to clean up old users, nor do we want to go on a witchhunt to find out who they are and remove them. The point is we need Signal to sonehow deal with inactive group members over time to prevent confusions like these from happening to any Signal users.

**Comment by cody-signal** [comment]
Yup, we made tickets for all platforms to stop checking for the capability, so you'll be able to use the permission regardless of who is in the group.

Regarding better support for dealing with inactive users, that would be a feature request for sure.

**Comment by Sgn-32** [comment]
`Remove announcement group capability checks` in 5.37.0

https://github.com/signalapp/Signal-Android/commit/9599d3a0b63c78e587298e74199f1395265254e2
