### ISSUE TITLE
No control how updates should be downloaded

### ISSUE THREAD

**Issue by Manaplayer** [signalapp/Signal-Android#12215]
I don't think this has something to do with any type of versions and devices:
As in closed issue https://github.com/signalapp/Signal-Android/issues/8714 , Signal is still automatically downloading his next update (without play store), on mobil data too.
Would it be better to make a switch to control how Signal update is working with different network connections?

Signal 5.36.3
Android 12

**Comment by cody-signal** [comment]
Hi there, please follow the template when positing GH bugs. Additionally, GH is used for bugs, not feature requests. While some may consider what you report a bug, we don't. For requests, please visit our community forum: https://community.signalusers.org/c/feature-requests/android-feature-requests/18

For context, we use Android's built in download manager for downloading the APK. I'd recommend looking to see if there are system settings for configuring it's behavior.
