### ISSUE TITLE
Unable to send SMS from Signal

### ISSUE THREAD

**Issue by ganeshkumarv10** [signalapp/Signal-Android#12214]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to send any SMS from signal on miui 

### Steps to reproduce
- Set signal as default SMS app on Xiaomi miui 13
- Try sending SMS from signal. The app will still have the button stating 'enable signal for sms'
- it makes no difference which route you take, if you try to initiate phone settings from app or go to settings, enable default messages app and come back to the app
- all permissions have been granted without any change
- this has been broken for awhile and is not a recent regression issue

**Actual result:** 
No change, unable to send SMS from signal 
**Expected result:** 
Send SMS from signal app

### Screenshots

![IMG_20220430_104117](https://user-images.githubusercontent.com/73722623/166100471-554e5486-2cf0-4578-9fa0-3c9d6959a9d4.jpg)
![IMG_20220430_104137](https://user-images.githubusercontent.com/73722623/166100472-64728ed1-5954-4ec2-a6b8-989f6dc579b2.jpg)

### Device info

**Device:** Xiaomi Mi 11
**Android version:** 12 (security update 1 Dec 21)
**Signal version:** 5.36.3

### Link to debug log

https://debuglogs.org/android/5.36.3/9032775262d7ada53091e19cf00b962c9aa449bc696814876639b620d6f40e1d

**Comment by drk002** [comment]
I had the same problem. Text messages sent from Signal were not reaching the recipients.
The problem disappeared after the last update to 5.36.3

Device: Poco X3 Pro, MIUI 13
Android version: 12
Signal version: 5.36.3

**Comment by drk002** [comment]
I am testing sending sms messages and another problem is:
- no sms delivery report despite report delivery option enabled.

**Comment by UserX404** [comment]
@drk002 
Should be fixed with 5.37.x
https://github.com/signalapp/Signal-Android/pull/12194#issuecomment-1108524388

**Comment by Sgn-32** [comment]
@ganeshkumarv10 

From your the debug log Signal isn't default SMS app.
```

======== KEY PREFERENCES ========
Screen Lock          : false
Screen Lock Timeout  : 0
Password Disabled    : true
WiFi SMS             : false
Default SMS          : false
Prefer Contact Photos: false
Call Bandwidth Mode  : HIGH_ALWAYS
Client Deprecated    : false
Push Registered      : true
Unauthorized Received: false
self.isRegistered()  : true
Thread Trimming      : Disabled
Censorship Setting   : DEFAULT
Network Reachable    : false, last checked: 0
```

Have you enabled SMS in Signal itself?
https://support.signal.org/hc/en-us/articles/360007321171-Can-I-send-SMS-MMS-with-Signal-

Signal settings > Chats > SMS and MMS > Use as default SMS app

![signal-2022-05-04-191146](https://user-images.githubusercontent.com/49990901/166742395-307e5398-f9ff-41ee-a7f4-38e623401e4a.jpeg)

**Comment by ganeshkumarv10** [comment]
That's the exact issue, I can't set signal as the default SMS app. I've
tried setting it from within signal as well with no luck.

Thanks

**Comment by Sgn-32** [comment]
Can you post some screenshots and a fresh debug log after "enabling" Signal as default SMS app?

**Comment by ganeshkumarv10** [comment]
![IMG_20220504_184255](https://user-images.githubusercontent.com/73722623/166748127-6acf553c-0dda-4a0e-b460-74f35f439d1e.jpg)
![IMG_20220504_184316](https://user-images.githubusercontent.com/73722623/166748131-5648fb4d-dd3f-48c1-90b0-faa2ce022bb0.jpg)
![IMG_20220504_184345](https://user-images.githubusercontent.com/73722623/166748132-11f48ec4-70bc-4855-8c95-0614a75d8c88.jpg)

**Comment by Sgn-32** [comment]
Most likely it is device specific. Unfortunately, I do not have a suitable device to analyze further.
Maybe another volunteer or one of the developers has a Xiaomi device.

**Comment by MrRinkana** [comment]
This should be closed now that SMS support has been removed.
