### ISSUE TITLE
Deleting a group does not leave the group and group may reappear

### ISSUE THREAD

**Issue by bublath** [signalapp/Signal-Android#12217]
- [X ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [? ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When deleting a group in the Signal App it disappears as expected. However the user does not leave the group and the group will reappear when receiving new messages. To REALLY delete a group, you first need to leave it and then delete it. This is very confusing and hopefully not intended.

### Steps to reproduce
- long press on group and choose "delete"
- Send a message from a different device to the group
- Group will reappear with message

**Comment by cody-signal** [comment]
Delete here isn't deleting the group, but deleting the current thread of messages. Just like 1:1, deleting a 1:1 conversation doesn't "delete" the person, just the conversation.

If you want to leave a group you need to go into the settings for the group. I can understand the confusion though, but it's not a bug.
