### ISSUE TITLE
disable "verify your signal PIN"

### ISSUE THREAD

**Issue by alexmo1997** [signalapp/Signal-Android#12227]
Personally, I use a password manager on android (for the signal pin, too), so this doesn't really apply to me as I don't intend to remember it... Thus I'd like to be able to disable signal from trying to get me to remember it...

**Comment by Sgn-32** [comment]
Signal settings > Account > PIN reminders

![signal-2022-05-04-190002](https://user-images.githubusercontent.com/49990901/166740193-74cf7b05-66ba-46ec-a548-ecf8b86ad0b8.jpeg)

**Comment by clauz9** [comment]
Since this is your first issue, welcome, here are a few things you might want to know. 

You should keep, and respect the issue template, don't just delete it. 

This "issue" would be a feature request, if it wasn't already available, so the place for feature requests would be here: https://community.signalusers.org/c/feature-requests/android-feature-requests/18

Now that Sgn-32 resolved your issue, you should close it.

**Comment by alexmo1997** [comment]
> https://support.signal.org/hc/en-us/articles/360007059792-Signal-PIN#pin_reminders
> 
> Signal settings > Account > PIN reminders

Oh, I really thought I searched the settings but that should have been easy to find.
Sorry to bother you!

> Since this is your first issue, welcome, here are a few things you might want to know.
> 
> You should keep, and respect the issue template, don't just delete it.
> 
> This "issue" would be a feature request, if it wasn't already available, so the place for feature requests would be here: https://community.signalusers.org/c/feature-requests/android-feature-requests/18
> 
> Now that Sgn-32 resolved your issue, you should close it.

Well I kind of saw it as a bug report as it's not really a feature I want but to disable a feature. But thinking about it, you are correct. I'm terribly sorry, I guess this must be really annoying if users don't respect your proper way of handling things. Maybe I subconsciously didn't want to think it was a feature request as I didn't want to have to create an account on yet another forum. Is there a reason you don't want feature requests here in the issue tracker?
