### ISSUE TITLE
Permanent "Checking for messages" notification after 5.37.0

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#12221]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to 5.37.0 I have a "Checking for messages" permanent notification that appears randomly, but once it appears it remains there until you force the app to quit.

### Steps to reproduce
- Update to 5.37.0
- Wait.

**Actual result:** Permanent "Checking for messages" notification.
**Expected result:** The "Checking for messages" notification should appear only for a small amount of time (1 or 2 seconds).

### Screenshots

![image](https://user-images.githubusercontent.com/32582878/166389691-dc5d8e51-1d24-4326-91d3-735a80972e94.png)

### Device info

**Device:** Redmi Note 10 Pro
**Android version:** 12
**Signal version:** 5.37.0

### Link to debug log

https://debuglogs.org/android/5.37.0/f19b5c22cd082ca789e5fd8a87df77bd50ee336cc0826c75ac1bd4e00a26d278

I think that it's somehow related to https://github.com/signalapp/Signal-Android/commit/921f7a70b3d003d5b07420074f043269f8c944fb

**Comment by bme13** [comment]
Hi, seems you're running the beta. There's a specific thread in the community forum to report beta issues. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-37-release/44124. You're specific issue was mentioned there and should be fixed in 5.37.1.
