### ISSUE TITLE
two minor cases where texts don't fit well

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12230]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
Not enough room for "partially send, tap here to ..."

![Screenshot_20220505-231255](https://user-images.githubusercontent.com/34976212/167029330-2f10c951-44df-4d3a-bc33-31ac2429c083.png)

Button to show overlaps with text saying "previously verified"
![Screenshot_20220505-231022](https://user-images.githubusercontent.com/34976212/167029332-04b91e2f-eacc-4512-bc61-a3d0d3ad9e7d.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by clauz9** [comment]
> Not enough room for "partially send, tap here to ..."

are you sure that's the text ? `ConversationItem_error_partially_not_delivered` if this is the string key, the text says
"Partially sent, tap for details"

**Comment by johanw666** [comment]
Change "Gedeeltelijk" to "Deels", that is the same in Dutch and is shorter.

**Comment by Meteor0id** [comment]
The choice of words is to avoid any and all ambiguity. But even if we do shorten it that way it probably still won't fit, and it may also not fit in other languages. I also have older screenshots of that same text in which it had two lines and did fit, appearently that was changed.
