### ISSUE TITLE
Chat doesn't update when open in background

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#12232]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a chat is open and Signal is in the background, newly received messages do not show up in the chat. You have to fully back out to the chat list, then re-open the chat before they will display.

### Steps to reproduce
1. Open a chat
2. Return to the home screen / switch to another app so that Signal is now in the background with the chat still open
3. Receive a new message in that same chat
4. Switch back to Signal

**Actual result:** The new message is not displayed in the chat, even though there is a notification showing the message contents
**Expected result:** New messages should show up in the chat

### Screenshots
N/A

### Device info
**Device:** Pixel 5
**Android version:** 12
**Signal version:** 5.36.3

### Link to debug log
https://debuglogs.org/android/5.36.3/ce0606063a689a438def942c04c9cb94a84e28fe94657c38ca55945ef581670e

**Comment by greyson-signal** [comment]
Hmm, I can't reproduce? I followed your instructions: opened a chat with Alice, switched to a different app, received a message from Alice, and whether I manually switched the app back or tapped the notification, I still saw the new message regardless.

Is the app just not scrolled to the correct position? Do you have the 'don't keep activities' debug switch on in your developer settings? If it's consistent for you, can you get me the timestamp of one of the missed messages? (message details, long-press sent timestamp to copy)

**Comment by Herohtar** [comment]
It looks like it may be intermittent or a weird one-time thing. I have had a couple of similar situations and the chat updated correctly.

The message definitely was not there in this case though; I tried scrolling up, then back down, and still wasn't able to see the new message. I haven't changed any developer settings.

I'll try to add some more details if I can get it to happen again.

**Comment by winstoncooke** [comment]
I have definitely noticed this before, although I cannot recreate it on demand.
