### ISSUE TITLE
Allow to send logs encryptedly

### ISSUE THREAD

**Issue by tzugen** [signalapp/Signal-Android#12234]
When I try to report a bug from the app it will create an Email in my email app.

There are a number of issues with this:
- The log contains identifiable data on my device, which I might not want to connect to a specific email account
- there is no possibility of sending the log encrypted. I have asked the support team for their PGP Key, but they didn't know what that is..

Suggestions:
- Provide an email address with PGP support on the website
- Create an internal API through which logs are submitted E2EE instead of using email as the transport mechanism

**Comment by greyson-signal** [comment]
Hi there, we use github for bugs, not feature requests. If you'd like to make a feature request, please use the [forum](https://community.signalusers.org/). 

Also, if it helps, all logs are scrubbed of any identifiers before uploading. But I also understand people have different thresholds.
