### ISSUE TITLE
Storage contains 1.8 GB ghost video

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12231]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For a while now it bothered me that Signal was using so much storage (according to the app itself) so I started manually deleting loads of media. However I just discovered the reported storage usuage can't actually ne credited to any file. Signal reports 1.9 GB of storage usage mostly video. But when I check all files left there are just 75 images of which the largest is a little over 500kB. How can I get rid of this ghost file or these ghost files? Are there actual files lingering?

### Screenshots

![Screenshot_20220505-235636](https://user-images.githubusercontent.com/34976212/167032467-b154d139-d4bd-4667-a6d4-4c001b846b42.png)
![Screenshot_20220505-235514](https://user-images.githubusercontent.com/34976212/167032470-8faecc65-6973-4564-b7d9-17a1019d385a.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 5.37.1
**Signal version:** 10.0.0

**Comment by Meteor0id** [comment]
Around 600 MB so ses the gohst video is a myth. The questions which remain are why Sigmal get the total size wrong and what to do about it

**Comment by Meteor0id** [comment]
I still have this bug and it still shouldn't exist

**Comment by berkaymenekse** [comment]
Is it allocates the size of not yet downloaded, pending contents? Did you check this out? @Meteor0id

**Comment by greyson-signal** [comment]
Indeed, we incorrectly include pending downloads in the size calculation. That's probably it. Will be fixed in an upcoming release.

**Comment by berkaymenekse** [comment]
I can fix it. I know where needed to be changed. I want contribute somethings for Signal ♥️
