### ISSUE TITLE
Cannot set own sound notification - no sound (silence))

### ISSUE THREAD

**Issue by Eldenroot** [signalapp/Signal-Android#12235]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I cannot anymore set custom sound notification for groups/contacts. I mean there is no way to use no sound anymore (I wanna use only vibrate and no tone). It was possible before.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

Latest beta signal, Xiaomi Redmi Note 9, Android 11

**Comment by cody-signal** [comment]
Can you updated to 5.37.2 beta and submit a debuglog after experiencing the issue and receiving a notification in that chat with no sound?

**Comment by Eldenroot** [comment]
Latest beta amd still valid. Tell me how to set "no sound" for notification in selected groups? I could do that in past, now I cannot!!! Add a switch or something if you cannot fix sound select!

**Comment by greyson-signal** [comment]
There were too many problems managing notification settings in-app, so now we simply link out to the system notification channel settings. Whatever you can change for other app's notifications, you can change for Signal.

**Comment by Eldenroot** [comment]
You misunderstood me... I do not want to mute all notifications from Signal, I wanna set my own notification for selected conversations.

**Comment by greyson-signal** [comment]
Tap the icon of the chat you want to change sounds for to go to the chat settings > Sounds & notifications > Custom notifications > Use custom notifications > Customize. That will create an Android Notification Channel for that specific chat, and take you to the system settings where you can customize it.

**Comment by Eldenroot** [comment]
Yes I know. But in past I selected "None" in the Android settings. But now (since some update) when I select none, it still plays the notification.
