### ISSUE TITLE
Inaccurate times on SMS thread

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12249]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Was texting a friend after 12AM (00:00, I have my phone on 24 hour mode). And their messages were showing "sent" at an earlier time when I know for a fact they were sending me messages after midnight. You'll notice that the thread keeps switching from today/yesterday.

Is it even possible for Signal to know the sent time of a receiving SMS message? Do carriers provide that? 

### Steps to reproduce
- use 24 hour time
- recieve SMS messages after midnight

**Actual result:** Sent time not accurate and causes the thread to look weird. 
**Expected result:** Sent time should be accurate

### Screenshots

![signal-2022-05-15-10-23-31-167.jpg](https://user-images.githubusercontent.com/18274896/168480632-cf5d5d84-8fcb-4da8-b612-89f03a29fc4b.jpg)
![signal-2022-05-15-10-24-36-582.jpg](https://user-images.githubusercontent.com/18274896/168480640-08c0ecea-db4e-4fc0-9378-10c0b10120f1.jpg)
### Device info

**Device:** Pixel 5
**Android version:** 12
**Signal version:** 5.37.4

### Link to debug log

https://debuglogs.org/android/5.37.4/900a356203abeb8cc99d234e3512487669566e8b5e8acd18ac7332bd0b7ec186

**Comment by greyson-signal** [comment]
We show the banner based on the sent time of the message. The sent time is set by the sender. It could be the sender's clock is off?

**Comment by Tursko** [comment]
That sounds possible, but the other messages from earlier in the day look accurate. And the messages I've received recently also look accurate.

**Comment by Tursko** [comment]
Still encountering this issue with any SMS message. It's really only noticeable after midnight.

**Comment by Tursko** [comment]
Seems okay right now so I'll close.
