### ISSUE TITLE
echo on receiving end with moto g7

### ISSUE THREAD

**Issue by miles969** [signalapp/Signal-Android#12243]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
duplicate of #7947 and #7635

### Steps to reproduce
- use headphones

**Actual result:** echo 
**Expected result:** no echo
### Device info

**Device (ro.product.model):** moto g(7)
**Android version:** 12
**Signal version:** 5.36.3

**Comment by rashad-signal** [comment]
Can you provide debuglogs from each device that was in the call where the echo happened? And there are a few other things that would be helpful to clarify:

1. Was the moto g7 the device that heard the echo? Or was it causing the echo?
2. Likewise, which side were the headphones being used on?
3. Which model of headphones were used to reproduce the problem?
4. Does this happen on all calls, or does it only happens sometimes?

**Comment by miles969** [comment]
i linked two known issues with this problem that contain a solution of sorts (blacklisting a certain value, afaiu).

**Comment by rashad-signal** [comment]
It does sound likely that this issue is related to the linked issues, but getting more information will help confirm that. If it is the same issue, then knowing which value to blacklist will be important. That will be clearer from debuglogs and knowing which device was experiencing the echo. If you aren't comfortable with sharing the debuglogs publicly, you can send them to me by email instead at rashad at signal dot org.

**Comment by Meteor0id** [comment]
You're using a custom ROM I guess? Moto G7 running Android 12 ... they were even hesitant to provide an upgrade to 10.

**Comment by miles969** [comment]
LineageOS 19.1 yes

> You're using a custom ROM I guess? Moto G7 running Android 12 ... they were even hesitant to provide an upgrade to 10.
