### ISSUE TITLE
Help screen not properly terminated after visiting Payments > help

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12245]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I had navigate to various menus in the Payment screen. When I navigated to Payments > Help and pressed the back button (arrow button top left of the screen) I was not send back to Payments but was instead send to the Settings overview. When I later switched languages the help menu showed up unexpectedly.

### Screenrecording
[](https://user-images.githubusercontent.com/34976212/167301193-6208e8ac-72d2-4595-8866-b32f28616cbf.mp4)

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0.0
**Signal version:** 5.38.0

**Comment by clauz9** [comment]
@Meteor0id  Isn't this fixed ? 🤔  can you close the issue if it is ? 🤔  or are you still experiencing this ? 
 https://github.com/signalapp/Signal-Android/commit/a501940909e489de13baf4f43357e19462f499b2

Can you close this, if it's fixed ?

**Comment by Meteor0id** [comment]
@clauz9 I saw the commit to fix it but I have not been able to test it. It most likely has been fixed so I'll close it and if I see it again open a new one.
