### ISSUE TITLE
Signal doesn't show pictures from internal storage

### ISSUE THREAD

**Issue by tactical-snail** [signalapp/Signal-Android#12248]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't show images from internal storage. It shows videos though. It doesn't load them in both chats and custom wallpaper selector. When you select an unloaded image and try to send it, it throws you back to the chat list.

### Steps to reproduce
- reinstall signal
- restore previously made backup
- give it contacts and storage permissions

**Actual result:** Shows empty black space
**Expected result:** Should show the pictures saved on device

### Screenshots
![Screenshot_20220515-143021_Signal](https://user-images.githubusercontent.com/96728391/168466234-32be345c-5ff5-490e-8db7-5281eb82edfc.png)
![Screenshot_20220515-143041_Signal](https://user-images.githubusercontent.com/96728391/168466236-c1de6c8d-8f5d-4766-9d9c-9e0695c31553.png)

### Device info

**Device:** Redmi S2
**Android version:** 12L
**Signal version:** 5.37.4

**Comment by alex-signal** [comment]
Could you please attach a debug log?

**Comment by tactical-snail** [comment]
Sure

https://debuglogs.org/android/5.37.4/3a64bd81157d693530db724ce27d9c8f5bb2d66a4d0ce095df720090269f3a09
