### ISSUE TITLE
Unblocking not working on Android

### ISSUE THREAD

**Issue by cjfcjfcjf** [signalapp/Signal-Android#12244]
Two people were blocked and then unblocked a few days later. It has been more than 6 months. I still cannot send or receive messages to or from either of these people. In group chats, I am able to see when someone replies to one of them, but it says "original message not found." I have uninstalled and reinstalled. I have deleted chat archives. I have never used desktop client or used signal on any other device.

**Comment by clauz9** [comment]
Interesting 🤔, but you should try to stick to the issue template, don't just delete it, each time you ignore and delete the template, the developer that put it there, sheds another tear 😢 do you really want to make the developers cry? 🤣 

Also, I tried to replicate your issue on the most recent version, 5.38.0 and I can't seem to do it, can you add a debug log please ?

**Comment by simon0356** [comment]
Hello,

Got the same issue, here is my log file : https://debuglogs.org/android/7.30.2/2828849fe01d25906ea61550fcded221745418d6325eeecbc00bb9d3643db3f0

Thanks
