### ISSUE TITLE
Sent time is equal to first attempt sending time, regardless of several attempts to send and fails

### ISSUE THREAD

**Issue by kofaysi** [signalapp/Signal-Android#12252]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Sent time is equal to first attempt sending time, regardless of several attempts to send and fails.

When mobile network is not available then sending message fails (not a Signal issue). After waiting for or searching and finding a network (E, 4G,... ), sending is attempted again and it succeeds. The sent time of the message displays the period of the first attempt. Usually, the sent time is few minutes, whereas it should be few seconds. The difference can be few hours or days, when sending previously failed messages after few hours or days. The issue can be simulated by disallowing mobile network connection on the device.

### Steps to reproduce
- disallow mobile network
- attempt to send message
- sending message fails
- wait few minutes (to allow for larger and significant time difference)
- allow mobile networks
- resend the message by tapping the red exclamation mark next to the message and `Send`

**Actual result:**
Sent time is few minutes just right after the successful sending attempt. It is probably the time of the first unsuccessful sending attempt.

**Expected result:**
Sent time shall be few seconds just right after the successful sending attempt. 

### Screenshots

Not relevant.

### Device info

**Device:** LG G5 h850
**Android version:** 10
**Signal version:** 5.37.40

**Comment by kofaysi** [comment]
The issue persist in Signal 5.42.8

**Comment by greyson-signal** [comment]
This is a deliberate design choice. Someone may send a message but have bad network, causing it to actually send an hour later. We want the recipient to see that the message was sent an hour ago. Otherwise it can cause weird social problems.

**Comment by kofaysi** [comment]
Thank you for the clarification, dear greyson-signal. Maybe we are talking about different occurrences of the display of the sent/received time.

Both information (sent & received) are available in the details/info to the particular message. I understand and I think it is socially correct to display sent time of the message just next to the message in the message list of the recipient. But the socially correct behavior would be to display the received (or actually transmitted) time next to the message in the message list of the sender. This way the social information would be complete, both are aware of the situation.
