### ISSUE TITLE
#10367 closed. Changed SIM cards. Signal App doesnt go past lock screen.

### ISSUE THREAD

**Issue by NightStalkerH** [signalapp/Signal-Android#12256]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App does not pass lock screen. 
Switched Sprint SIM Card to Tmobile SIM card. 

After lock screen prompts for passcode and provided, it continues in a loop cycle going back to lock screen. 

Issue occured only after SIM card change. Changed back to Sprint SIM and still not able to get passed lock screen. 

Changed passphrase to a pin and still not able to login. 

After error, updated Signal app via app store on 5.18.22. Did not fix issue. 

App was working fine, with passphrase, prior to SIM swap on 5.18.22

### Steps to reproduce
- Switch SIM cards .. Sprint to Tmobile
- Attempt to login to App by using same device passphrase/pin

**Actual result:**
Loops back to lock screen. 
**Expected result:** 
Log in to app and access messages

### Device info

**Device:** samsung note 8
**Android version:** 9
**Signal version:** most recent updated 5.18.22

### Link to debug log
Tried to download log and publish. Does not publish. I can see it but does not allow for link or publish.

**Comment by cody-signal** [comment]
Is SIgnal setup to be your SMS app? If so, can you try disabling that in system settings and trying to launch signal afterwards?

**Comment by NightStalkerH** [comment]
It was set as primary SMS app. Upon SIM transfer noticed that tmobile setup changed it back to standard messages app as primary. 

Signal doesnt move forward in either preference.

Just tried again based on your query. No go. Accepts pin but reloads lock screen. Still if using wrong pin ot does acknowledge a wrong pin.

**Comment by NightStalkerH** [comment]
The app will not publish the log but I could copy and paste it. Seems a bit much for this forum. 
I have lots of sensitive contacts and information in these messages and need to be able to reaccess them. 
Nuclear option is not an option. 
I have seen where it is possible that a code can be switched from false to true or vice versa. But not sure how I could do that/get access to the code. 
Would a portion of the log be helpful here ? If so, which portion?

**Comment by clauz9** [comment]
@NightStalkerH  so, just to clarify... if I understood you correctly... you have a passphrase set-up as lock screen security, for your Android device, right ? 

and you've enabled from inside the Signal app, the "Screen lock" option, from Settings -> Privacy, yes ? 

![image](https://user-images.githubusercontent.com/77681918/169374359-e12d9600-2a86-42f7-a8f5-50279be9416e.png)

And now Signal doesn't allow you to open the app, 🤔  ? but you can access, and use your Android device normally, outside of Signal yes ?

**Comment by NightStalkerH** [comment]
@clauz9 yes, I have had a passphrase setup on my device for years as both lockscreen and startup encryption. 

I have used Signal for about a year or more. I have activated the Signal security protocols to use my device passphrase to open and unlock Signal. This was activated about 6 months ago. 

There were no issues using this setup with passphrase unlock until yesterday 5.18.22 when I switched SIM cards.

When I was unable to access my SMS via Signal after SIM swap, I read the thread in issue #10367 on this site and saw where some advised changing the method of security  passphrase or PIN on device and Signal would automatically change its protocol and may and worked for some to gain access. 

Therefore, yesterday I changed from passphrase to pin. Signal did in fact change as well and changed from asking for a passphrase to a PIN. However, it accepts the PIN but reloads the lock screen. In continues in this loop pattern and never loads the messages. 

Yes, I can continue to use my device outside of Signal with no issue.

**Comment by clauz9** [comment]
> Yes, I can continue to use my device outside of Signal with no issue.

good, so you should be able to temporarily disable lock screen security, as Cody suggested, open the signal app, disable the "Screen lock" option from within signal, and then re-enable your Android lock screen security. 

also, get a debug log from Settings -> help -> debug log and add it to your issue, while you're in Signal.

**Comment by NightStalkerH** [comment]
@clauz9 : okay. So, I was successfully able to disable as you indicated. In hindsight, if I was able to change password type successfully before, logic should have told me to try a no lock sequence. 

However, given this being a secure/encrypted app, I never thought that deactivating locking sequence on device would auto deactivate on Signal ... thinking lock compromises of device. 

Anyway. It worked and allowed me to access messages with no lock. 

However, once lock was reestablished both on Signal and device, I am prompted with Signal lock screen and it runs same loop. I tried this various times in different sequences and then ran the debug log from the lock screen while in loop cycle. 

I was now able to get link for debug. 

https://debuglogs.org/android/5.37.4/1a2a08101848d7e37c2d8190cd5728b9fca4b2676a172b3bf5953a0b8e7823be

I am running Signal 5.37.4

**Comment by clauz9** [comment]
> I was now able to get link for debug.
> 
> https://debuglogs.org/android/5.37.4/1a2a08101848d7e37c2d8190cd5728b9fca4b2676a172b3bf5953a0b8e7823be
> 
> I am running Signal 5.37.4

@cody-signal  you've got a debug log

**Comment by clauz9** [comment]
> Anyway. It worked and allowed me to access messages with no lock.
> 
> However, once lock was reestablished both on Signal and device, I am prompted with Signal lock screen

while the android lock is disabled ... you can enter Signal Settings -> privacy and set the "screen lock inactivity timeout to "None" ... which will keep Signal unlocked, then go to Android settings, reenable your lock screen password, and then go back to Signal, now you should be able to get in, because it's still unlocked. 

And you should be able to go to Settings -> privacy  and disable the "screen lock" option.

**Comment by NightStalkerH** [comment]
@clauz9 correct. However I need signal to function with a lock. 
I followed steps above and yes it enters with no password/pin. However once reestablished it continues lock cycle despite my entering the correct pin. 
If my phone is unlocked, I need signal to function as it was and auto lock upon specified time lapse or screen lock. 
Despite the steps above it is not allowing me to achieve this anymore. 
If it locks, it stays locked. If I remove passphrase/pin then I have access. But the moment a lock goes back on and reactivated in Signal, I am stuck at lock screen.

**Comment by clauz9** [comment]
> @clauz9 correct. However I need signal to function with a lock.

so if this is required .. my suggestion would be to... disable Signal's screen lock option... completely, crate a Signal back-up with all your conversations (just so you know, conversations that have "disappearing messages" enabled won't be saved in the back-up)  uninstall and reinstall signal, restore your back-up... and then enable Signal's "screen lock" again.

**Comment by NightStalkerH** [comment]
@clauz9 okay. This is sound logic and given the ability to access messages with lock turned off, I can do this. 
Thank you! 
A bit of a process but hope it also helps others. Glad I am able to see and access my messages.

**Comment by clauz9** [comment]
> (just so you know, conversations that have "disappearing messages" enabled won't be saved in the back-up)

Take note of this... before you do anything.



> A bit of a process but hope it also helps others. Glad I am able to see and access my messages.

well... it's a workaround until a fix is released.... 🤷‍♂️

**Comment by NightStalkerH** [comment]
Thank you @clauz9. Saved me and my messages.
