### ISSUE TITLE
Mic not working, people cannot hear me

### ISSUE THREAD

**Issue by pmty11** [signalapp/Signal-Android#12259]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The mic is not working with Signal. If I make a call or if somebody calls me - in both cases they cannot hear me. The problem started some versions ago, I cannot really tell when. But like 2 month ago I was able to make calls and had no mic problem. The phone is not the problem as normal phone calls do work.

What I did try to solve the problem:
Reinstalled Signal
Trying to make calls via Wifi or mobile data connection
Checked the permissions - all set for the mic

### Steps to reproduce
- Starting a call / accepting a call via Signal

**Actual result:** When the call starts I can hear the other person just fine. However, that person cannot hear me.
**Expected result:** Microphone works so that the other person can hear me.

### Device info

**Device:** Xiaomi Redmi Note 8
**Android version:** 18.1 LineageOS
**Signal version:** 5.38.5

### Link to debug log
(https://debuglogs.org/android/5.38.5/af2431cdd8aaf3a08dd88a3e9b4be26cf7e5bb28e0a7d076f640f676843c082f)

**Comment by mueenulit** [comment]
Can you please check the Microphone permission?   
Go to Settings > Apps > Signal > Permissions ...

![Screenshot_20220523-112950_Permission controller](https://user-images.githubusercontent.com/88363715/169749778-7436f04b-c197-47c0-b613-e6897016d3e4.jpg)

**Comment by pmty11** [comment]
Thanks for your suggestion. As I wrote in the initial post, the microphone permissions are granted - Signal is allowed to use the microphone.

**Comment by cody-signal** [comment]
@pmty11 does recording a voice note work when using the same setup?

**Comment by cody-signal** [comment]
When you are speaking do you see your audio indicators move?

**Comment by pmty11** [comment]
@cody-signal 

1) Recording voice notes does work. If I record a voice note and send it to somebody that person can hear what I recorded.
2) No, there are no audio indicators visible.

**Comment by cody-signal** [comment]
> No, there are no audio indicators visible.

They aren't visible at all or can you see them but they aren't moving?

**Comment by PKVienna** [comment]
I have this identical issue:
Nexus 6p,  LineageOS 15.1-20200204 (yes, old, but Lineage dropped support for the Nexus :-( ).
Signal updated on 24th,  mic stopped working on Monday 30th.
The three little audio level dots do not move at all with speaking.
Voice messages arrive only as static.
Recording and talking worked fine up until yesterday.
phone reboot did not clear the problem.

**Comment by PKVienna** [comment]
Dreadful problem to debug: as of June 1, the problem "went away", and the microphone works again...
Although signal itself has not updated, the Messages app has, although Signal is my default messaging app.
I don't see a reliable debugging/reproducability route for this problem...

**Comment by pmty11** [comment]
Updated to Signal version 5.93.3. Still, the microphone is not working.
@cody-signal: Any update on that problem?

**Comment by pmty11** [comment]
It seems the problem is device-specific, and related to LineageOS 18.1. Sorry for bothering, nothing is to be done from Signal's side. Closing the ticket.
