### ISSUE TITLE
Multiple chats unarchived with no new messages

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#12255]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I had multiple archived chats randomly become unarchived without receiving new messages. Many of them were simply "[Name] is on Signal!" chats with people that I don't actively talk with, but at least one of them was a chat that *did* have some history, but was no longer active, and the last message was a safety number change message from September 2021. There were other archived chats that did *not* become unarchived, so it wasn't an "all or nothing" kind of thing. I'm not exactly sure how recently it happened because they were all further down on my chat list and I didn't notice them until I scrolled down looking for something, so I'm not sure if the log will have any useful info. I did re-archive the chats before capturing the log, so if the info is there, you might be able to see which chats were affected (not sure if that is tracked in the logs).

I found https://github.com/signalapp/Signal-Android/issues/11690, which seems similar, but was apparently only for the desktop client.

### Steps to reproduce
1. Archive chats
2. Wait
3. ???
4. Profit!

**Actual result:** Maybe your chats will become unarchived? Actually, I don't know what caused this, so I'm not really sure how to reproduce it.
**Expected result:** Chats don't become unarchived unless they receive a new message, per design.

### Screenshots
N/A

### Device info
**Device:** Pixel 5
**Android version:** 12
**Signal version:** 5.37.4

### Link to debug log
https://debuglogs.org/android/5.37.4/bf6fc6c0fcaab1f6b133706f05619e89b057d0885825de4ac31063cb50ea1d93

**Comment by Herohtar** [comment]
I do have a linked Desktop client. Those chats actually do not show up there at all, neither in the "Archived" list nor the main list. I'm not sure why, because I have not manually deleted them. Maybe that's another issue, lol.

**Comment by greyson-signal** [comment]
@newhinton Can you provide links to [logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) from both your desktop and android device after you experience the issue?

**Comment by newhinton** [comment]
I can try! Though as OP, i don't really know WHEN exactly those chats are unarchived, so my 'testing' was just poking in the dark. However, i will create logs for my observation

**Comment by greyson-signal** [comment]
Thanks! Did any spontaneous unarchives take place in these tests? If so, can you describe which platform did the archive, which platform(s) unarchive spontaneously, and in which logs?

**Comment by Herohtar** [comment]
I don't think I have seen this happen any more since the issue was created. 🤷‍♂️
