### ISSUE TITLE
Feature Request: We want to share live location

### ISSUE THREAD

**Issue by somratpro** [signalapp/Signal-Android#12253]
We need to share live location sometimes, and we can't do that in signal. then we have to go to Whatsapp again. It will be great if we can do that.

**Comment by cody-signal** [comment]
Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.

If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org
