### ISSUE TITLE
Input audio not working when using headphones in Redmi Note 10 Pro

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#12251]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting a voice or video call in my Redmi Note 10 Pro using headphones or plugging in them later makes the input audio to not work any more unless I disconnect them. The problem isn't the headphones because I have tried with others having the same result, also, voice notes can be recorded just fine, looks like a server-side problem or specific voice/video calls.

### Steps to reproduce
- Start a voice or video call in your Redmi Note 10 Pro.
- Plug in headphones.
- Input audio stop working.

**Actual result:** Input audio doesn't work unless I disconnect the headphones.
**Expected result:** Input audio continues working normally.

### Screenshots

Not needed.

### Device info

**Device:** Redmi Note 10 Pro
**Android version:** 12
**Signal version:** 5.38.3 (happens in the stable version too)

### Link to debug log

https://debuglogs.org/android/5.38.3/60803873b07d5d1ca3d884badb299b038286397a9938ee5ffd33a6e796392035

**Comment by rashad-signal** [comment]
Just wanted to get a little more information before looking into this:

1. The problem happens when the headphones are plugged in, but are these headphones that are plugged in through USB, or a headphone jack?
2. Do the headphones have a mic on them, and that's what isn't working? Or do they not have a mic, and the mic on your phone stops working?
3. If you don't mind providing it, what model of headphones were you using when this problem happened?

**Comment by Edu4rdSHL** [comment]
Hey, @rashad-signal thanks for the reply and sorry for the delay.

1. They are plugged through the headphone jack.
2. The headphones have a mic, that's what is not working.
3. Honestly I don't think that it matters too much, I have tried with several headphones (4) and they all have the same result. One is JBL, and others from Samsung.

As I said, they all work in all other apps, Signal is the only that has the problem.

**Comment by Edu4rdSHL** [comment]
It seems to have been fixed in the latest builds.

**Comment by Edu4rdSHL** [comment]
This issue has been fixed a long time ago, if you have problems please use another issue.

I'm unsubscribing from it.
