### ISSUE TITLE
Cannot send my own “gifs”. (Short videos, to be shown as looping pictures.)

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#12263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal has a “gif” sending feature. Which works fine for giphy. But giphy requires not only an account, but a special approved account. Which of course makes it completely useless for sending your own self-made ones, as it leaks all private information to that dubious third-party site.

So naturally, one wants to do the most simple, normal thing, and just send that short, (usually audioless and small) mp4 file as a “gif” directly via Signal, without going through any useless centralized privacy-selling (aka ad-based) web site.

But trying to do that always ends up sending a video. Which is not shown directly in the chat. Also, there is no way to decide whether to loop it. Despite there being a button seemingly for it, but that does something else that is literally not possibly in physics (prevent the recipient from watching it more than once).

But when I choose to save a “gif” that I received and that *is* shown right in the chat window, it ends up as a short, audioless MP4 file in my file system too!    
So it clearly is already designed to do that. The code path to do it when picking one’s own gif-like video is just currently inconsistent with the code path for giphy-originating gif-like videos.

### Steps to reproduce
- Get somebody to send you a giphy. It should just show in your chat, and animate by itself.
- Save that giphy to your file system. (E.g. your meme collection.)
- Send the MP4 that that resulted in back to that user.

**Actual result:** That user gets a video, with a play button, that opens a player. it does not animate in the chat.
**Expected result:** It should be exactly as if when you received that same file. Animating in the chat.
(Or, alternatively, giphy videos should be treated like normal videos too. The inconsistency is the issue.)

**Comment by navid-zamani** [comment]
Bugs are not bread. They don’t go “stale”. Who came up with that malicious bot?
Problems do not magically go away because they are old.
This is still a problem.

**Comment by cody-signal** [comment]
Hey there. So here's the thing, this isn't a bug. It's a feature request. It's a very good feature request and something we've talked about doing before. However, as it stands now this is behaving as expected as we don't treat mp4s differently when they don't come from the internal gif search feature. Please check out our forum for feature requests.

Also, this has made my day:
![image](https://user-images.githubusercontent.com/66265416/180797400-d1a16267-18f2-438e-a051-1745f83a8a27.png)

**Comment by navid-zamani** [comment]
Hey, hmm, as a programmer, I know that using an arbitrary file in your submit function is the normal functionality that is the most generic case and takes the least amount of effort if one implements something like that on any Unix-like platform (which Android/Linux is), since everything is a file. So only sending specific files requires somebody to add specific code on top of that, to limit the functionality.

Meaning it’s not something one needs to add, aka a feature, but something one has to fix or remove, aka a bug.
That’s why I marked it as such.

What will happen now? You did not mark this as a duplicate to any other issues. (Github allows issues to be marked as feature requests so that one can filter by them, right? So will this now be forgotten unless I go to the forums to post it there?

Happy you liked that statement and made it into a meme. :)

**Comment by cody-signal** [comment]
Signa's Dictionary defines bugs as the app not behaving as designed and intended. In this case, the app is behaving as designed and intended so it's not a bug.

I closed the ticket because by our definition of a bug and by our desired usage of GitHub issues to solely be for bugs, this shouldn't be tracked here.

**Comment by Melaron** [comment]
I understand the bug definition issue here, but it would be nice if this was automatically transitioned into a feature request or similar. It seems like users should be able to send mp4's as looping videos since the capability is clearly there. I can send .gif files and they loop just fine, but .mp4 should be an option as well.
