### ISSUE TITLE
Audio calls enable also 4G data when you are on Wifi, risking to use unwanted data

### ISSUE THREAD

**Issue by gab81** [signalapp/Signal-Android#12262]
### Bug description
I came across this situation on a recent audio call where there are both WIFI and 4G data active at the same time

### Steps to reproduce
i was on a call recently and i noticed that the 4G data sign was on while i was using Wireless - i didn’t want to use 4G data obviously and it seems it’s not (the little arrows are not moving) but still why are they showing during a call.

![image](https://user-images.githubusercontent.com/54513687/169842172-3e570994-9c41-4aa8-9ea8-b3559aba537c.png)

A community member told me that:

RingRTC (Signal’s calling library) automatically detects your network quality and switches between WiFi and mobile data to (in theory) whichever one is the best at any given moment. So if it thinks your call will have higher quality on 4G, it will switch to that. It seems to very often get it wrong, as it will insist on using data for me even when connected to my much higher bandwidth WiFi.

This is very inefficient because:

Imagine you are just outside in your garden, WIFI is a bit weak but still working, you do a video call 2 hours, phone instead takes from the DATA and it used 2GB of your data contract… not fun right?

We should have an option in Settings that allows Signal to use 4G Data while on a call yes not. simple. We should have the choice whether or not we want to suck our bandwidth on the DATA contract or not.

- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Device info
Device:** Samsung Galaxy S8
Android version 9
Signal version: 5.38.5

### Link to debug log
https://debuglogs.org/android/5.38.5/0dd13c4af87fae102ca2542f9f37efa6e2f797a8acdd0c72696d2732766d09a6

thank you

**Comment by cody-signal** [comment]
There's a new banner/haptic feedback shown in the latest beta when signal switches to cellular from wifi, so you'll at least know if it's using cellular in the app.

It's not the setting you're asking for but it's something. 🤷🏼

**Comment by Bloo-dev** [comment]
Reopen
This is still an issue, I pay by MB and don't want signal to use my data at all. For me signal calls are simply not viable until a setting exists to switch off the smart switching and limit signal to WIFI.

**Comment by Bloo-dev** [comment]
Reopen

**Comment by venomousbirds** [comment]
I recently got the message that it would automatically switch to data even when using WIFI. I'm not going through the trouble of disabling my data every time I call and going through the trouble of installing a firewall is much too complicated for me. So this is still an issue that makes it basically impossible for me to call through Signal.

**Comment by Bloo-dev** [comment]
> There's a new banner/haptic feedback shown in the latest beta when signal switches to cellular from wifi, so you'll at least know if it's using cellular in the app.
> 
> It's not the setting you're asking for but it's something. 🤷🏼

That's at least something! Thanks for adding that!

I still wish this would be added as a toggle, is there a reason why this was marked as `wontfix`, or did the bot simply do that automatically?
