### ISSUE TITLE
In chat sounds in android not working as intended

### ISSUE THREAD

**Issue by NoobieOnGitHub** [signalapp/Signal-Android#12278]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in chat sounds are enabled, whenever I'm receiving messages, I hear my system notification sound instead of the in chat sound. It doesn't matter whether I'm in the DM or not, I hear the notification. I saw this issue on my friend's and my parent's android devices. 
### Steps to reproduce
- Turn on In-chat sounds from settings
- go to a DM 
- receive a message

**Actual result:** Hearing notification sounds whenever i receive a message even though I'm in their DM
**Expected result:** In chat sounds like we normally see on apps like WhatsApp
### Device info

**Device:** Motorola G40 Fusion
**Android version:** 11
**Signal version:** 5.39.3

### Link to debug log

https://debuglogs.org/android/5.39.3/e109cd20a2611c4cf97f82d480076f88f18de172bb20338c3bdc10153a40290f

**Comment by Kuladeep1996** [comment]
@greyson-signal have similar problem.. if possible can you add different sound(Subtle sound) like WhatsApp, if user is inside chat

**Comment by NoobieOnGitHub** [comment]
> 

Yes, just like all the other messengers out there. Take WhatsApp or telegram for example. When we hold down the record button or when we sent a message, there will be certain sounds. I don't actually care much about that, but it's a nice thing to add. What annoys me is even though we are in the DM the notification sounds keeps playing. Like in WhatsApp, when we get a message in a DM or group chat there is a small low pitch sound effect which is pleasing to the ears. In signal, the app uses the default notification tune even though we are in the DM, so I had to disable 'in chat sounds' all together.
