### ISSUE TITLE
The app does not start

### ISSUE THREAD

**Issue by 0uros** [signalapp/Signal-Android#12275]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just open the app, and the app don't start.

### Steps to reproduce
- Just open the app

**Actual result:** Just make the android animation to open the app, and later the app close without see the UI of the app. After rey to open sometimes, android show the screen "the app is nota working"

### Device info

**Device:** Motorola Moto G8 Power
**Android version:** 11
**Signal version:** 5.39.3
**Custom ROM:** EvolutionX

### Link to debug log
https://paste.evolution-x.org/aBR4EU

**Comment by cody-signal** [comment]
This error occurs when the system has blown away our key credentials. Sadly, the only fix is to reinstall/re-register.

**Comment by 0uros** [comment]
Oh I see, it's not that a problem, luckily I do backups quite often, I was able to solve it by logging in again, thanks!
