### ISSUE TITLE
After some recent Signal update the sharing of content with 'note to self' stopped working - observed on android client and on linux desktop 

### ISSUE THREAD

**Issue by mniehus** [signalapp/Signal-Android#12279]
After some recent Signal update the sharing of content with 'note to self' stopped working - observed on android client and on linux desktop

**Comment by greyson-signal** [comment]
I don't fully understand. Can you provide more details and a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) that's taken after the issue occurs?

**Comment by DonChunior** [comment]
The initial situation on my Android device is that "Note To Self" is on top in Signal because I just wrote something in it.
Now, for example, I'm on a website in the Chrome browser and want to save it to "Note To Self" using the Share functionality (Share > Signal):
Then a menu opens with the latest Signal conversations, but "Note To Self" is not in the first place as I would expect (and as it was until recently)!

**Comment by DonChunior** [comment]
This issue is related to following SignalCommunity topic: [Note to Self stopped appearing in share sheet suggestions](https://community.signalusers.org/t/note-to-self-stopped-appearing-in-share-sheet-suggestions/44757).

**Comment by sammdu** [comment]
Hi, I am experiencing a similar issue. I'll provide some screenshots for reference.

It used to be when I share a file or link to Signal, "Note to Self" would be the top option if not one of the top options. 
However, after a recent update, I no longer see it in the recent list, even though I use it just as frequently.

<img height="600" src="https://user-images.githubusercontent.com/10665890/175756076-33bcd575-ee8e-4e0d-abb4-f4e826e89d1c.png"/>

I need to search for it every single time for it to appear: 
<img height="600" src="https://user-images.githubusercontent.com/10665890/175756148-a00b0223-2dfa-4568-bc97-50bcb0663099.png"/>

Hopefully this makes it clear, and it is obviously a regression in user experience. It doesn't make sense that a frequently used feature needs to be searched up every time, when it hadn't used to be like this.

**Comment by alex-signal** [comment]
Hi, this was a regression and is fixed for either 5.41 or 5.42

**Comment by mniehus** [comment]
yes, it was solved with fix 5.42.  thanks!
