### ISSUE TITLE
Transfering phonenumber-Profile to a new phone without need of SMS-confirmation - phone company turned off the number

### ISSUE THREAD

**Issue by 8zgs4gt** [signalapp/Signal-Android#12272]
I have a use-case where i need to transfer a Signal phonenumber account to a new phone because the old phone does not get any security updates any more.
In my case the phone-company have already turned off the phonenumber. If you try to call the phone number, you get the information, that the phone number does not exist. This is for me the perfect situation because i can give to the people a signal-only number and this protects me so that the people cant create unencrypted meta-data or even general data by using their phone number to send me unencrypted SMS-messages. I always told the people to NEVER make a unencrypted call (i never answered any, but call still creates meta-data). The people still used the phone number to try to make a unencrypted call over the phone company after i had told them not to do that.

After a few months of police brutality and prison in a country with broken law and jurisdiction, i was financially broke and the phone-number was shut off because of missing payments. Now i have the situation where other people can only contact me with Signal and the people are not able to contact me without encryption - and this is from the security perspective a positive thing. But how can i transfer this Signal-only phone number to a new phone?
https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages
> Your new device  can receive a SMS or call to complete registration.

No, it can not. There is no working simcard any more. The simcard with the phone number is been turned off (cant register to the phone network any more) and the old and the new phones are been used with open public wifi only.
I dont need the old conversations or anything else. The only thing i need on the new phone is the phonenumber i am using.

How can i still use this Signal-only phone number? This is a huge issue right now for me because it breaks the ability to communicate with any other people. Please help

**Comment by cody-signal** [comment]
This is more a support request, and I'd encourage you to use our community forum or reach out to support@signal.org since we use GH for bugs/crashes. However, I'll do my best to provide some support here. You just may get better instructions from those other two sources.

If your old device is still registered and active, and your new device as SIgnal installed but not registered yet, and the new device has an active phone number that can receive SMS then you can use the change number flow on the old device (you'll get the SMS code on the new device but that's fine). After you do this, you can then go to the new phone and register Signal with the new phone number and your account will have the same identifiers.

To be clear, as long as the account with the old number is still accessible on the old device, you don't need the ability to receive SMS on it anymore. Only the NEW phone number needs to be active.

**Comment by 8zgs4gt** [comment]
Thanks for the answer.
> to use our community forum
Quote from the support-subforum in https://community.signalusers.org/  "In this category you can ask other Signal users questions about the app. Note that this is unofficial support"
That is the reason why i reported the issue here. I cant find any solution for this issue and the issue is that i would loose the only option to stay in contact with other Signal users. I dont want to loose the ability to stay in contact with other Signal users.
But i have create a forum account there and wrote about the issue i reported here in https://community.signalusers.org/c/support/android-support/11 The account and the post are now waiting for approval and unlisted at the moment. 

> or reach out to [support@signal.org](mailto:support@signal.org)
I cant find any PGP key for this email address on the known public PGP servers. Where can i find the PGP public key?

> If your old device is still registered and active
Yes, it is.

> and your new device as SIgnal installed but not registered yet
Yes, because your website is telling me that i would have to receive SMS and this is impossible when the phone company have turned off the number. That is making a registration impossible.

> and the new device has an active phone number that can receive SMS
No. It does not have any phone number or simcard inside and this situation wont change in near future. I am using it with open public WiFi.

> To be clear, as long as the account with the old number is still accessible on the old device, you don't need the ability to receive SMS on it anymore. Only the NEW phone number needs to be active.
There is no new phone number

**Comment by greyson-signal** [comment]
Hi, I'm sorry, but given your situation, there just isn't a way to transfer the number. Every flow of moving the account to a new device requires receiving an SMS or Voice code to prove ownership of the number. My only suggestion would be one of the cheap ways to get a new number, like Twilio ($1 USD/month) or something similar.
