### ISSUE TITLE
Message position in list is not kept when going back

### ISSUE THREAD

**Issue by jaredsburrows** [signalapp/Signal-Android#12271]
Message position in list is not kept when going back

Version: `5.39.3`

**Comment by UserX404** [comment]
Please don't delete the issue template.
The corresponding forum topic as cross reference:
https://community.signalusers.org/t/did-chat-list-scroll-position-break/44664

**Comment by clauz9** [comment]
@jaredsburrows this has been fixed with the following commit https://github.com/signalapp/Signal-Android/commit/259a86b605763f9f6e3c114327a23dec0fbfa7a8 in version 5.40.2. 

if you are able to update to that version and confirm that it doesn't happen anymore, you should then close the issue.

**Comment by jaredsburrows** [comment]
Thanks.
