### ISSUE TITLE
When forwarding a message, the new recipients cannot tell it was forwarded

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#12285]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When forwarding a message, it looks like the messages comes from me. This is very confusing to the recipients of the forwarded message, in particular when the message contains words like "I", "me", or "we" that now just refer to the wrong person.

### Steps to reproduce
1.  Forward a message
2.  Look at the forwarded message in the receiving channel/chat

**Actual result:** The forwarded message looks exactly like a message sent by the forwarder.
**Expected result:** The forwarded message should say something like "Forwarded message from X" (like when one forwards an email).
I think this is a bug since the current implementation of 'forward' makes the feature basically impossible to use in a way that does not confuse the people the message is forwarded to.

### Device info

**Device:** Motorola G7
**Android version:** 11
**Signal version:** v5.39.3

**Comment by debojyoti452** [comment]
@alan-signal 
As far my understanding there is no specific key that defines is it forwarded message or not. I was trying to add this fix but didn't able to get the key. Any suggestions?

**Comment by greyson-signal** [comment]
We won't be adding this feature for the time being. Thanks!

**Comment by philiprenich** [comment]
Hi @greyson-signal 
Always good to get clear responses from devs, thanks for that!

Would you mind expanding a little on the reasoning?
 Won't add the feature as stated with the original sender mentioned? Won't mark a message as forwarded fullstop even if it was just a "Forwarded" tag? Technically can't due to the way the e2ee works within Signal?
