### ISSUE TITLE
Note to Self history lost after restoring from local backup

### ISSUE THREAD

**Issue by realbiz21** [signalapp/Signal-Android#12286]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After restoring from a local backup, the Note to Self history was missing.

### Steps to reproduce
- Use Signal for a long time, keeping a list of Note to Self messages
- Enable chat backups, remember the passphrase
- Get ready to lose your phone, so force a backup and transfer the backup off
- Lose your phone
- Get a new phone, transfer the Signal backup to the new phone
- Install Signal and restore from backup
- Look for Note to Self thread

**Actual result:** There is no Note to Self thread
**Expected result:** The Note to Self thread should have existed with the many notes from using Signal for a long time

If it matters, by default Disappearing messages for my account are at 4 Weeks, however I explicitly changed it for Note to Self to disable Disappearing Messages (because I know restoring from Backup makes the threads with Disappearing messages set empty).

Since I have a backup, is there a way to extract the Note to Self assuming the bug is just for restoration. Because I lost a lot of important notes but I have many local backups.

### Screenshots

N/A

### Device info

**Device:** Pixel 3A
**Android version:** GrapheneOS Android 12
**Signal version:** 5.40.4, website APK

### Link to debug log

N/A

**Comment by realbiz21** [comment]
@cody-signal Yes, the same phone number was used. I chose the backup, entered the passphrase, used the same phone number, completed the CAPTCHA, got the verification text, entered my registration lock PIN.

But there was no Note to Self thread.

If I try to search contacts and choose Note to Self, the thread is empty.

However it has a single message saying it will use 4 weeks for disappearing messages, but if I go into the conversation settings it says Disappearing messages is Off, which is expected because I explicitly turned off Disappearing messages for Note to Self.

So I wonder if the default Disappearing message of 4 weeks got applied to Note to Self or is mixed up somehow.

**Comment by cody-signal** [comment]
The will set to 4 weeks is shown when a conversation is empty, so that's expected. It's not currently applied until you send a message so that's why it's shown as off in the settings.

When you were using NTS in the previous install, did you turn off NTS timer after it was auto-turned on, or had the NTS chat been established prior to enable the default timer?

**Comment by realbiz21** [comment]
I'm pretty sure the NTS chat was established long before enabling the default timer.

**Comment by cody-signal** [comment]
There are community tools for exploring backup files. You may want to look into one of those to at least verify that the NTS data is in the backup. If you can verify that it is in there, then the next thing would be to provide a debuglog after restoring from the backup and seeing no NTS messages in the restored chat.

**Comment by realbiz21** [comment]
I tried [signalbackup-tools](https://github.com/bepaald/signalbackup-tools). Looking in the backup sqlite file, I do not see a thread in the threads table for my Note to Self. So NTS didn't even make it into the backup. That means it's lost. I kind of figured using NTS for long term notes wasn't the best approach but I learn my lesson now.

I did more testing by making a new NTS thread with dummy messages, and then creating a backup, with version 5.40.4. The NTS dummy messages are in that backup so that is good. A really old backup also did have old NTS notes in there. Maybe the specific version I used had an issue (v5.35-5.39)?

Since it seems to work with 5.40.4 I am not sure if this issue should remain open, but I am 1000% sure I didn't delete my NTS thread, because it was a year-long notepad. If there is more input needed from me let me know.

**Comment by clauz9** [comment]
> If it matters, by default Disappearing messages for my account are at 4 Weeks, however I explicitly changed it for Note to Self to disable Disappearing Messages

@realbiz21 I'm trying to replicate your issue 🤔 

can I get a bit of clarification on the timeline of the events described in the quote above ? 

1. did you first set a "Default timer for new chats" then you started a new "Note to self" conversation, went to the 3 dot menu, and turned off  "disappearing messages"  ? 
2. did you first set a "default timer..." then you started a new "note to self" conversation, sent 1 or more messages, and then went to the 3 dot menu to turn of "disappearing messages" ?  
3. did you already have an existing "note to self" conversation in your chat list, and then you set a "default timer for new chats", and went to the 3 dot menu of  "note to self" to turn off "disappearing messages" ? 

or was there a different order of events ? 🤔

**Comment by realbiz21** [comment]
@clauz9 I believe it's closer to #3 - 

I had an existing NTS conversation for about a year, then maybe 5 months ago I enabled a default disappearing timer of 4 weeks. I don't _believe_ I actively disabled disappearing messages for NTS because the chat was already established. In other words I don't think I _ever_ touched the disappearing messages setting for the NTS thread.

However, when I tried to replicate the above some days ago, everything worked as expected as far as NTS being present in the newly created backup.

**Comment by clauz9** [comment]
@realbiz21 can you tell me what version of Android you were running on the device that made the back-up and the one that you restored  the back-up on ? 

I'm asking because I managed to reproduce your bug yesterday... on an Android 8 device, and today I can't anymore ... 🤔 

and I'm wondering if it's ok to test on a newer android version...
