### ISSUE TITLE
Include user names when copying multiple messages from group chat

### ISSUE THREAD

**Issue by grthr** [signalapp/Signal-Android#12283]
In a group chat I often copy multiple messages from different user names and paste them into another app (e.g. DeepL for translation).
The text copied to the clipboard does not include the names of the messages, although the messages do come from different users.
In case of translation, it is hard to get the mapping of who wrote what.

Steps to reproduce
Open Signal
Go to a group chat
Long press a message
Click select
Mark multiple messages from different users
Click copy
Paste clipboard in another app or browser
Actual result: The pasted text does not include the user names of the messages:
[message1]
[message2]

Expected result: The pasted text is formatted like this:
[username1]: [message1]
[username2]: [message2]

**Comment by cody-signal** [comment]
Thanks for taking the time to report this. We use GH issues exclusively bugs. While I can understand why one would consider this a bug, it's more a feature request. If you look at our template you deleted you can find the link to our community forum where we accept feature requests.
