### ISSUE TITLE
Error when adding a member to a group

### ISSUE THREAD

**Issue by IvanHaentjensANB** [signalapp/Signal-Android#12295]
When I try to add a member to a group through the API, I get this error:

"error": "WARN  AccountHelper - Messages have been last received 16 days ago. The Signal protocol expects that incoming messages are regularly received.\nFailed to send message: StatusCode: 400 (GroupPatchNotAcceptedException)\n"

**Comment by greyson-signal** [comment]
Hi, sorry, we don't provide raw API support here. This is just for reporting bugs you encounter in the official Signal Android app. Feel free to discuss on the [forum](https://community.signalusers.org/). Thanks!
