### ISSUE TITLE
Unable to access group after deleting it from Chats view

### ISSUE THREAD

**Issue by rodrigovillarbello** [signalapp/Signal-Android#12298]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Any group that gets deleted from the main view of the app (that is, the Chats view) is no longer accessible until someone writes a new message and the group again shows in the Chats view.

I don't believe this bug is tied with my current Signal version since this has happened to me several times when using previous versions.

### Steps to reproduce
- Have a group.
- Long press the group in the Chats view.
- Press "Delete".
- Press again "Delete" in the "Delete selected conversation?" dialog.
- The group disappears from the main view of the app (intended) and is no longer accessible (not intended).

**Actual result:** The group is no longer accessible.
**Expected result:** The group should be accessible after searching for its name.

### Screenshots

After deleting the messages, the group is no longer searchable by its name:
<img src="https://user-images.githubusercontent.com/61924177/174479387-6fe1ec9a-c8c9-4185-94b1-a54df507b633.png" width="300">

It also doesn't show in the profile of someone I know for sure is in that group:
<img src="https://user-images.githubusercontent.com/61924177/174479394-097454b7-a410-41ac-a8f9-b0d0cc6b6b6e.png" width="300">

But I can still add people to that same group:
<img src="https://user-images.githubusercontent.com/61924177/174479397-a2651f45-d088-447f-860b-5844b947d4b3.png" width="300">

### Device info

**Signal version:** 5.40.4

**Comment by greyson-signal** [comment]
You can find the group if you click the new conversation button (the pencil in the bottom right of the chat list) and search there.

The global search only searches for threads that exist, so deleted threads will be excluded. We have some future plans for global search.

**Comment by rodrigovillarbello** [comment]
Ah, my bad, didn't check that view. Thing is the lack of groups in common with the other user and that the desktop app does have global search led me to think it was a bug.

Thank you for the quick response anyway.
