### ISSUE TITLE
Google Play Services detection broken with work profile

### ISSUE THREAD

**Issue by ryantrinkle** [signalapp/Signal-Android#12297]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Google Play Services is installed in a work profile but NOT installed in the main profile, Signal thinks that Google Play Services is "updating".  This makes it impossible to get past the registration screen.

### Steps to reproduce
- Set up a device without Google Play Services
- Use Shelter or a similar app to create a work profile
- Install Google Play Services in the work profile, but do NOT install it in the personal profile
- Install Signal in the personal profile
- Provide your phone number to begin the Signal connection process

**Actual result:** Signal fails with an error message stating that google play services is updating
**Expected result:** Signal should use its "google play services not present" workflow to register the user

### Device info

**Device:** Pixel 6 Pro
**Android version:** 12
**Signal version:** 5.40.4

**Comment by greyson-signal** [comment]
Hi, thank you for taking the time to file a report, but I don't anticipate that this is something we will be spending time on.
