### ISSUE TITLE
Contacts not showing up

### ISSUE THREAD

**Issue by PxlRift** [signalapp/Signal-Android#12293]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My phone's contacts are not showing up inside the app when creating a conversation.
Only phone numbers, not contact names show up in the message list.

### Steps to reproduce
- Resynced Contacts via account settings in android settings multiple times.
- Refreshed Signal Contact page inside the app multiple times.
- Manually added phone numbers to existing and new contacts.
- Restarted phone multiple times.
- Redownloaded Signal multiple times.
- Tried importing contacts via a vcf file directly from the first-party contacts app.
- Set as default SMS/MMS messaging app.

**Actual result:** Messages from existing contacts show up as phone number that messaged me.
**Expected result:** Messages from existing contacts show up as the name of the contact.

### Screenshots
![Screenshot_20220617-211319_Signal~2](https://user-images.githubusercontent.com/56781157/174292075-1b6b0920-8544-4c3b-bdbe-5fd6d4598ab9.jpg)

![Screenshot_20220617-211200_Signal](https://user-images.githubusercontent.com/56781157/174292062-abc87b92-8057-4e7b-88a1-ab1c17aef82e.jpg)

### Device info

**Device:** Samsung Galaxy S10
**Android version:** One UI 4.1 (Android 12)
**Signal version:** 5.40.4

### Link to debug log
https://debuglogs.org/android/5.40.4/b9ced809c7d5679a4ca9f6c6fedd509341d32663429273e734658964822b5b2e

**Comment by greyson-signal** [comment]
Hmm, I have some ideas as to what may be happening. Added a possible solution and some extra logging to 5.41.4.

**Comment by TwinMoonTerror** [comment]
I am having this issue as well. Same attempted steps, largely the same issue. 
An additional wrinkle I am having is that attempting to send group messages which involve contacts whose name is not displaying results in that contact being omitted from the text as it is sent.

**Comment by greyson-signal** [comment]
@TwinMoonTerror Please provide a debuglog, thanks!

**Comment by TwinMoonTerror** [comment]
Here is a debug log shortly after sending a message to a contact without their name showing and creating and saving a new contact for them.

https://debuglogs.org/android/5.45.6/58b19c7e2afa6267ddd750dec2367dbc2e84a464f23d7d859e209a63feb834d3

Device info
Device: OnePlus 7T
Android version: Oxygen OS 11.0.9.1.HD65AA (Android 11)
Signal version: 5.45.6
