### ISSUE TITLE
[Bug][Notifications] Signal freezes device completely when receiving a message containing media when screen is OFF

### ISSUE THREAD

**Issue by x2k13** [signalapp/Signal-Android#12306]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

**Signal version: 5.40.4.1
Android OS: Android 11/crDroid 7.19
Device: Samsung Galaxy S5 (SM-G900F)
Rooted: No**

**Bug description**
As the title says already, upon receiving a message containing media when screen is OFF leads to a full freeze of the device, without any way to unlock it other than force-reboot/removing the battery, which is pretty annoying when it happens a few times a day. The only way to prevent this is to disable notifications for Signal system-wide, but that's not how a messenger should work, right? 🙂

Thanks in advance for looking into this. ~~I would have provided a log, but when the freeze occurs, even Matlog/Logcat crashes and stops recording the log, so the useful info doesn't get recorded at all.~~

**Steps to reproduce**
See above

**Edit**: added URL to log file
https://debuglogs.org/android/5.40.4/65c687a50e08e5ed955375d7b55f6442726faa0ab3c58c72dc482c131c9b5dda

**Comment by alex-signal** [comment]
> Thanks in advance for looking into this. I would have provided a log, but when the freeze occurs, even Matlog/Logcat crashes and stops recording the log, so the useful info doesn't get recorded at all.

Signal will log into a database, so those logs aren't lost! If you can upload a debug log and add it to your description it'd be a great help.

**Comment by x2k13** [comment]
> > Thanks in advance for looking into this. I would have provided a log, but when the freeze occurs, even Matlog/Logcat crashes and stops recording the log, so the useful info doesn't get recorded at all.
> 
> Signal will log into a database, so those logs aren't lost! If you can upload a debug log and add it to your description it'd be a great help.
Added the URL to the log to the description, thanks for the hint! I hope this helps.

**Comment by cody-signal** [comment]
Are the images you are receiving large or of a specific type? Does it happen with every image? Did this start happening recently or has this been a problem for awhile? Did you recently update crDroid?

While this isn't a fix, but can get you running again, you can change the notification setting for "Show" to be just the name only and then it won't try to show image previews.

**Comment by x2k13** [comment]
> Are the images you are receiving large or of a specific type? Does it happen with every image? Did this start happening recently or has this been a problem for awhile? Did you recently update crDroid?
> 
> While this isn't a fix, but can get you running again, you can change the notification setting for "Show" to be just the name only and then it won't try to show image previews.
Yes, this has been a problem for a while, but I waited to report it, because it could have been fixed by the next updates automagically, but that didn't happen. 

I really can't say if it's acertain type or size of images, but the ones I receive are usually .jpeg and .png, but just regular 72 ppi. 

crDroid (which is a fork of LineageOS 18.1) is receiving monthly updates (monthly patch from Google), and I'm always on the latest version, for obvious reasons. But the problem existed since I installed Signal and there have been at least 3 updates since.

Addition to my OP: I found out that it's not only attached media, but links and their preview as well. I followed your advice and set the notification settings to just show names, no crashes since then. At least now I can unlock my phone and the app without a hard crash.

**Comment by cody-signal** [comment]
Thanks for the extra details. This is tough one and seems to be very OS specific. We put a fix in recently to use different ways of providing the data to the OS but it seems some don't like it.

**Comment by JohnnyMT** [comment]
A friend and I are also experiencing this issue 1-2 times a week. This started a few months back, but we also had it with screen on. 
Signal version: 5.44.5 
Android OS: 10
Device: Honor 20 YAL-L21
Rooted: No

I have an debug log one week ago, after the hard reboot:
https://debuglogs.org/android/5.43.7/af8b8f344d128a571999008cb8929d74cd83dbb1763160d13bd08345465d89d0

**Comment by cody-signal** [comment]
Thanks for the details @JohnnyMT, could you provide some of the file sizes of the media you observe this occurring with? Roughly ballpark is good enough.

**Comment by vanMacG** [comment]
For me, this happens only on some random images/media... (see #11828). I have the same device as op (Samsung Galaxy S5 (SM-G900F), but with stock LineageOS.

**Comment by JohnnyMT** [comment]
> Thanks for the details @JohnnyMT, could you provide some of the file sizes of the media you observe this occurring with? Roughly ballpark is good enough.

Just had the issue again, 523kb image. 
Debug log:
 https://debuglogs.org/android/5.45.6/4131e77733a821a86d5347fa4ed6168858232617506c6c0645449d2bd0a25ac4

**Comment by JohnnyMT** [comment]
@cody-signal and it was definitely with screen on

**Comment by vanMacG** [comment]
Last time I had the issue, was also with screen on and I observed something interesting:
I was in another app when receiving a messge with an image, got a notification popup at the top of my screen. This notification freezed but I was still able to navigate and interact with the open app. Some seconds after, a system pop-up saying "system UI" is not responding anymore, and I had to restart. So it's really "only" system UI (and signal) crashing.
PS: image size was 492,9 kB.

**Comment by cody-signal** [comment]
I have another hopeful fix coming in 5.48 that'll drop into beta later this week. Please try it out when it's available in your preferred channel (beta or prod).

**Comment by vanMacG** [comment]
> I have another hopeful fix coming in 5.48 that'll drop into beta later this week. Please try it out when it's available in your preferred channel (beta or prod).

@cody-signal Did the fix made it into 5.48? I had another crash on friday...

**Comment by vanMacG** [comment]
And yesterday once again... Image size is 363,8 kB.
Curioz fact: I had signal desktop running as well. And after some time the watched status from desktop got synced to the phone. After notification was gone, the phone was recovered and didn't need a restart.

**Comment by greyson-signal** [comment]
Can you provide a [log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) that's taken after it happens?

**Comment by vanMacG** [comment]
Sure: [log](https://debuglogs.org/android/5.50.4/1b5e52b163ee8cb1cf46ef4eee826d0fbd86cf9441743fcc794790cf77284dfb)
Message arrived at 2022-10-03 17:46

**Comment by vanMacG** [comment]
I see that one minute later, I received another message with a different person... Maybe this also helped "recover" the notification...?

**Comment by cody-signal** [comment]
@vanMacG I assume you're running a custom rom, which one?

I can't reproduce this, and this point I don't know how it could be happening with all the changes we've made.

**Comment by vanMacG** [comment]
I'm using LineageOS 18.1 (without google but microG).
Does it make sense to continue posting signal-logs when this issue occurs? Maybe system-logs would help more?
