### ISSUE TITLE
Can sometimes not send videos with Google Pixel 6 - loops and loops

### ISSUE THREAD

**Issue by googlepixelbug** [signalapp/Signal-Android#12300]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
GOOGLE PIXEL 6 user. When I try to send a video either recorded or saved locally from phone (could be a video I have saved in a chat for e.g.) it will sometimes not work. The little loading circle icon will just loop and loop until it reaches a full circle then starts over again. I can wait for minutes or hours, it will not sent successfully. So I have to longpress => delete for everyone to clear the pending transfer. Its been like this since day one on my Google Pixel 6 fresh phone and install out of the box. Is this something about the Google Pixel 6 phone and Google Android OS thats the issue?

### Steps to reproduce
- Have a Google Pixel 6
- Attach a video or record a video via camera
- "Hopefully" it will loop and get stuck. Sometimes it works, sometimes not. It could be on wifi or 4G, with or without VPN.

**Actual result:** Will loop and loop. Transfer will be pending until you cancel it. It will never be sent. Instead I transfer the video on whatsapp but I do not want to use whatsapp really.
**Expected result:** Video being sent.

### Device info

**Device:** Google Pixel 6
**Android version:** 12. It says "Android-12-9"
**Signal version:** 5.40.4

### Link to debug log

https://debuglogs.org/android/5.40.4/a8dc832740600ae46d3b22e6573e5b2f20436b00227938c291c877d04d0e4daa

Last 2-3 minutes (15:21 and cancelled video 15:24 => directly to submit bug report).

**Comment by googlepixelbug** [comment]
Maybe a format would help or re-install but not possible right now unfortunately.

**Comment by greyson-signal** [comment]
Looks like there may be something funny happening between attachment uploads and censorship circumvention. We're looking into it.
