### ISSUE TITLE
Mi band 7 Quick replies don't work with Signal

### ISSUE THREAD

**Issue by Minibus93** [signalapp/Signal-Android#12311]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you try to use any quick reply to any signal notification you receive on your Mi Band 7 the quick reply won't be sent. 
(quick replies gets send with whatsapp instead)

### Steps to reproduce
- Have a Mi Band 7
- Receive a Signal message notification on your Mi Band 7
- Click "reply" button
- Select any quick reply and try to send
- "Message could not be sent"
- That has reproduced the bug

**Actual result:** "Message could not be sent" so you can't use with replies with Signal on Mi Band 7
**Expected result:** Message should be send successfully like it happens with WhatsApp

### Device info

**Device:** Mi 10, model M2001J2G
**Android version:** 11/Miui 12.5.8.0(RJBEUXM)
**Signal version:** 5.41.9

**Comment by cody-signal** [comment]
Debuglog?

**Comment by Minibus93** [comment]
> Debuglog?

Didn't think it was needed, I'm sorry for not including it since the beginning

https://debuglogs.org/android/5.41.10/5e26995f1c7b11ac553027ca12d94af6a4013f5bc52ea7d11516750116e2d6ce

**Comment by Tiago-Seven** [comment]
Same problem here. Really wanted to use this feature with Signal :slightly_smiling_face:.

**Comment by Minibus93** [comment]
Just wanted to update that the issue persists even after firmware update on mi band 7 (1.19.1.5)

**Comment by Minibus93** [comment]
I guess this won't be addressed by anyone eh? Bit sad, this is a huge usability turndown...

**Comment by cody-signal** [comment]
Hey there, we don't have on these devices and don't know why it doesn't work. We are hoping to revamp some wearables stuff soon, but until then, this just isn't a priority. Sorry, totally understand the desire for it though.
