### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by arthurhawron** [signalapp/Signal-Android#12314]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have been using signal for a while on /e/os. It has been working fine up until recently. Now the app doesn't open, It crashes on every launch, and I don't know why.

### Steps to reproduce
- use signal on samsung galaxy s8 with /e/ os.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Samsung Galaxy S8
**Android version:** 9
**Signal version:** Latest

### Link to debug log
 Because I cannot open the app, I captured it with a debug app: [Here](https://pastebin.com/KJ43MyUB)

**Comment by UserX404** [comment]
Please don't delete and fill in the issue template!

**Comment by arthurhawron** [comment]
There, hopefully thats it.

**Comment by greyson-signal** [comment]
It looks like our entry in the Android keystore is "unrecoverable". This makes it impossible for us to decrypt our database, and unfortunately there is no way to recover from this state. It could very well be an issue with /e/ os. Is there anything else you can think of that may have been going on with the device that could have altered something? An OS update or similar system change?

**Comment by mkot-bh** [comment]
Ok. I've fixed it by a manual update from version Signal 5.44.4 to Signal 5.44.5 (apk available at https://signal.org/android/apk/). Clearing the cache beforehand did not help.

**Comment by Cjh4444** [comment]
> Ok. I've fixed it by a manual update from version Signal 5.44.4 to Signal 5.44.5 (apk available at https://signal.org/android/apk/). Clearing the cache beforehand did not help.

did this preserve your messages? I'm having a similar issue, on a Moto G Power 2021, the app randomly stopped working a couple of nights ago, and haven't been able to get it fixed, restarting and clearing the cache doesn't do anything, and I'd rather not delete the app data as it would delete my messages. I filed a support ticket but they haven't gotten back to me. Wondering if updating to Signal 5.44.6 would fix my issue (currently on 5.44.5).

**Comment by cody-signal** [comment]
@Cjh4444 can you start the app while in airplane mode?

If you can, you can now save the debuglog to disk by going to Settings -> Help -> Debuglog -> 3 dot menu and save.

Could you send that zip to me at my email cody at signal dot org?

**Comment by Cjh4444** [comment]
That worked. Thank you!
