### ISSUE TITLE
Google Map API Error(Cannot get location)

### ISSUE THREAD

**Issue by RLirri** [signalapp/Signal-Android#12313]
- All Cheked
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I want to access a location using Google Maps in Chatting functions, the application does not respond to a correct location.

### Steps to reproduce
- Open a chat session
- Click “+”
- Click Location (open Google Maps)
- Choose to check to send

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Location cannot be sent. And also can't check the location

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Can direct to a correct location and also send a correct location 

### Screenshots
<img width="461" alt="Screen Shot 2022-06-26 at 7 50 17 PM" src="https://user-images.githubusercontent.com/76832192/175812692-b0c27a7f-47a5-4b06-a3b0-378884558e33.png">
<img width="453" alt="Screen Shot 2022-06-26 at 7 50 39 PM" src="https://user-images.githubusercontent.com/76832192/175812710-f5aa6bc5-1375-44da-87c4-b0f7465f4260.png">

### Device info

**Device:** OPPO A93s 5G
**Android version:** Android 11(Pie)
**Signal version:**

**Comment by alex-signal** [comment]
Hi! Could you please include a debug log?
