### ISSUE TITLE
Search text in message/messages/conversation/conversations/chat/chats

### ISSUE THREAD

**Issue by Genis-Sage** [signalapp/Signal-Android#1232]
I would like the possibility to search , for words/phrases/numbers in chats, especially if they are old and therefore long.
For example if someone send me an address, but I can't remember the date,
it would be helpful if I can press options/search and then have a text field (and a search button).

**Comment by inetpro** [comment]
+1

**Comment by sigenc** [comment]
@moxie0 Thank you for opening this issue again.

Hello all,

i think this is one of the most wanted features for signal. Every one of my not so technical friends ask me why he can't search his messages. The Brown University has an interesting approach to handle this. Thanks to jaypatelani on the community forum, we know that there is some possibility to search in signal messages without compromising security and without doing major changes to the signal infrastructur. 

http://esl.cs.brown.edu/blog/signal/

> In this project, we set out to explore whether encrypted search could be used to add search functionality to the Signal messaging app securely and without compromising efficiency. The design we proposed incurs minimal changes to Signal's current architecture and has several advantages over the naive solutions which include using a plaintext in-memory index or using full-database encryption solutions like SQLCipher.

And my personal most anticipated feature that would come as a side effect of this:

> In the future, we plan on improving the project in two ways. First, we would like to store EDB and message encryption keys in either the Android Key Store or, depending on the device, in secure hardware. The benefit of this would be that the encrypted index would be secure even while the app is in open mode. Second, we would like to use encrypted search techniques to also hide some of the meta-data that Signal currently stores in plaintext like timestamps, sender and device ID.

**Comment by justjoeyuk** [comment]
Is it worth moving towards https://realm.io for something like this?

**Comment by wes-novack** [comment]
+1 
very surprised to see that we're still missing content search in Signal messenger on Android

**Comment by moxie0** [comment]
@wes-novack Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues  

You can use the reaction emoji in GH to express support, thanks.

**Comment by sandeepcmsm** [comment]
+1
