### ISSUE TITLE
[Android][Regression] Video recording fails when Animations are disabled

### ISSUE THREAD

**Issue by khalidelassaad** [signalapp/Signal-Android#12327]
### Bug description
THIS IS A REGRESSION. Video functionality was working as expected with Animations disabled before this update.

When trying to record a video with Animations disabled, the video does not record and instantly jumps to the "video recorded, preview before sending screen". The video has no length and is a black screen (unlike taking a picture)

### Steps to reproduce
- Disable Animations. Settings > Accessibility > Visibility Enhancements > Remove animations to ON
- Open Signal
- Select a chat
- Press the camera icon in the message box to open the camera
- Press and hold the record button at the bottom of the screen

**Actual result:** Recording button expands as if recording started, then immediately recording stops WHILE BUTTON IS STILL PRESSED. Preview shows a video that is all black, with no ability to be played.
**Expected result:** Recording should start and continue for as long as the button is pressed. Preview afterwards should show video contents and be playable

### Screenshots
![Screenshot_20220701-162609_Signal](https://user-images.githubusercontent.com/28274751/176977830-f90a5cbb-b640-4bd0-88e5-f0e2285e7792.jpg)

### Device info
**Device:** Samsung Note 9
**Android version:** 10
**Signal version:** 5.41.11

### Link to debug log
https://debuglogs.org/android/5.41.11/cea1f1bcae3ffd3e865f0fb6f204d77b2ac0b3996e8faf3e07f4f3f5658b8e26

**Comment by SNowArchitect** [comment]
Was able to recreate this issue as listed above. 
This can also be recreated if while in developer mode the animation scale is set to 0

**Device**: Samsung Note 20
**Android version**: 12
**Signal version**: 5.41.14

![Screenshot_20220706-103647_Settings](https://user-images.githubusercontent.com/45631610/177576361-18648ae8-fe24-45e1-b70d-7a17a881cbfb.jpg)
![Screenshot_20220706-103710_Settings](https://user-images.githubusercontent.com/45631610/177576363-1470839c-ed52-4297-822f-b07e16bb2424.jpg)

**Comment by khalidelassaad** [comment]
Yeah, seems like the animation scales also affect the rate at which the recording indicator circle fills up, also impacting the max duration of the video.

If set to 0.5x, I can only record a 30s video (as opposed to 1 min)

If set to 2x, I can record a 2:00 video!!

**Comment by alex-signal** [comment]
Hi! This has been resolved in 5.43 which should be hitting beta today or tomorrow.
