### ISSUE TITLE
The message sent by the IOS end to the Android end can be received, and the message sent by the Android end to the IOS end will be lost

### ISSUE THREAD

**Issue by 337077418** [signalapp/Signal-Android#12335]
https://user-images.githubusercontent.com/10607980/177721024-8c7c8b45-4f75-4537-a886-fd9d54fe7637.mp4

**Comment by alex-signal** [comment]
Hi! Could you please add debug logs? Without those, there isn't much we're able to do.

**Comment by 337077418** [comment]
Sorry, there should be a problem of not receiving messages when the IOS simulator is running
