### ISSUE TITLE
Reply Chain Text Overlapping

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12337]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For some text, the "Read More" overlaps the timestamp.

### Steps to reproduce
- Send Message
- Quote it
- Open Reply Chain View

The text I used in the message:
_Bei den Mails müsste ein Hintergrund beim Logo verwendet werden. Sonst siehts im Darkmode so aus:_

**Actual result:** Read more overlaps
**Expected result:** Read more doesnt overlap

### Screenshots
![Screenshot_2022-07-07-22-37-42-31_4b14b257287ac0a6d1fd5fbb2487716f_1.jpg](https://user-images.githubusercontent.com/62468040/177867600-ace9c93b-1fc0-4d85-a5c9-39f5d8674d9b.jpg)

### Device info

**Device:** OnePlus 8t
**Android version:** 12
**Signal version:** 5.42.7

**Comment by debojyoti452** [comment]
@MorgeMoensch 
![image](https://user-images.githubusercontent.com/20729878/184030114-625ba87b-68bc-4657-b214-0707a1cfc0b5.png)
Couldn't able to reproduce on Pixel 3XL and Oppo F9 Pro

cc: @alex-signal

**Comment by MorgeMoensch** [comment]
@debojyoti452 it's in the replied-to view, not in the normal Chat view (as you showed in your Screenshot)

**Comment by debojyoti452** [comment]
> @debojyoti452 it's in the replied-to view, not in the normal Chat view (as you showed in your Screenshot)
> 
> Did you follow the exact steps in the issue description when trying to reproduce?

@MorgeMoensch 
Can you please add exact reproduce steps?

**Comment by MorgeMoensch** [comment]
@debojyoti452 please see the section 'Steps to reproduce' in the first post

**Comment by debojyoti452** [comment]
@MorgeMoensch 
Didn't able to reproduce it. Can you add a loom video? so I can fix it for you.

**Comment by hidekido** [comment]
I [have tried](https://www.loom.com/share/545f62a94ffa470090c7d0b20c9221c2) to reproduce, but without any luck. 
Also, I've tried different font sizes(e.g. on the screenshot below the font size is "Large").
![image](https://user-images.githubusercontent.com/20519507/188152470-c2f8d48e-27bc-4e6a-8566-4fed5adb8b40.png)


Maybe something is unusual with your system font size, or I don't know.

**Comment by MorgeMoensch** [comment]
This is fixed for me now; so I'll go ahead and close this issue.
