### ISSUE TITLE
Unusual waste of space within the UI. 

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#12332]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Most of the space within the application is being wasted and it doesn't look any good or appealing to use it. I'm not talking about the color or anything but only the overall usage of space for the elements and visual looks.

This is subjective but as a designer, I mentioned what I observed. 

### Steps to reproduce
- open the app
- look into the UI and the space being used by the elements. Most of them are being wasted. 

**Actual result:** Ugly UI by wasting a ton of space. 
**Expected result:** The pixel density has to be increased and should beade a little compact so that UI look good. That doesn't mean that you've to fill it with clutter. 

### Device info

**Device:** DRG
**Android version:** 12.1
**Signal version:** 5.42.6

**Comment by fat-tire** [comment]
Another perspective:  No.

**Comment by greyson-signal** [comment]
Hi there, we use Github as an issue tracker. For suggestions or feature requests, feel free to use the [forum](https://community.signalusers.org/). Thanks!
