### ISSUE TITLE
Source code for SQLCipher

### ISSUE THREAD

**Issue by v4Zexr** [signalapp/Signal-Android#12333]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Around [October 2021](https://github.com/signalapp/Signal-Android/commit/77cb9bc174a383ed82368e0bdff79423331d5d62) Signal began using a modified version of SQLCipher. The license for which can be reviewed [here](https://www.zetetic.net/sqlcipher/license/). The source code featuring Signal's changes hasn't been released yet, it's obviously critical that changes to this library can be reviewed.

I believe the relevant licenses call for the source to be made available, but I must say my knowledge in this confusing area isn't my strength. Even if the license doesn't require the source be made available, will Signal make it available regradless, in the spirit of being an open source project?

**Comment by greyson-signal** [comment]
SQLCipher themselves are the ones who made the changes. It was a relatively large refactor of their Android layer and we started using it before it was public. I believe SQLCipher will be making the source available soon -- it's just a large change (with breaking interface changes), so they have to spend more time preparing it for use with their wider userbase.
