### ISSUE TITLE
Can't open link from incoming text

### ISSUE THREAD

**Issue by elibroftw** [signalapp/Signal-Android#12344]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I got a text from audible to install an app. A link was provided with https://

### Steps to reproduce
- get a text from someone with a link that does not start with http 

**Actual result:** 

Clicking the link (underlined) does not open a browser. 

**Expected result:** 

Opens the link in a browser. 

### Screenshots

![Screenshot_20220711-011102.jpg](https://user-images.githubusercontent.com/21298211/178193299-ca9c4207-6372-4ee6-8c6f-414974047ac2.jpg)

### Device info

**Device:** knellus 6t
**Android version:** q
**Signal version:** latest

**Comment by zecipriano** [comment]
Me and a couple of friends are having the same issue.

It seems that text after the link breaks it.

"some text google.com" <- link is underlined and clicking it opens a browser.

"google.com some text" <- link is underlined but clicking it does not open a browser.

If the link starts with https:// it always works.

I am on version 5.42.7.

**Comment by JohnFrontzos** [comment]
I tried both "google.com" or "dummy text google.com" in a conversation and they work as expected. 
Android v13
Signal app v6.2.3

**Comment by elibroftw** [comment]
Can't reproduce the bug so closing. Must've been fixed without reference.
