### ISSUE TITLE
[Feature] Possibility to remove/disable audio on sharing video

### ISSUE THREAD

**Issue by Dephrilibrium** [signalapp/Signal-Android#12346]
Heyho Signal-Coders,

sometimes I share videos of some projects and I want to share that videos without audio (e.g. audio-record is hardly overdriven so that the sound is scratchy).

Therefore a feature to "clip out" the sound would be pretty nice.

Kind regards,
Deph

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
