### ISSUE TITLE
Lock screen does not work

### ISSUE THREAD

**Issue by annalisabuffa** [signalapp/Signal-Android#12340]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by annalisabuffa** [comment]
The screen does not lock at the time out. 
This occurs with android 12 on a huawei p30 pro. At the moment the screen does not lock at all.

**Comment by annalisabuffa** [comment]
![Screenshot_20220708_201152_org thoughtcrime securesms](https://user-images.githubusercontent.com/51314407/178047590-5067d24c-283a-44e9-9ce2-170f3d08b95a.jpg)

These are the settings

**Comment by C4P4E7** [comment]
A few days ago, I opened an issue related to this check #12330

**Comment by C4P4E7** [comment]
Please create the issue properly and follow the rules. Compare your issue and mine and check what is missing. It should be detailed.

**Comment by alex-signal** [comment]
Closing as duplicate.
