### ISSUE TITLE
clicking a recognized link does not open browser. 

### ISSUE THREAD

**Issue by adiastra** [signalapp/Signal-Android#12347]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal recognizes certain strings of text as links but does not open the browser when clicking the links. A real  example of this links i get regularly from fedex. The link text format looks like this fedex.com/t/<tracking number>/en_US

Signal recognizes that fedex.com is a URL and underlines the text and makes it clickable. Clicking this URL does nothing 

This only seems to happen when signal is acting as the default SMS app and only only with links send via SMS. 

### Steps to reproduce
- Receive a link formatted as described above over SMS (signal is the default messaging app
- click the link
- ???
- profit 

**Actual result:** Clicking the link does nothing other than visually showing the link was clicked (the underline disappears momentarily) 
**Expected result:** Clicking the link should open the link in a browser window

### Device info

**Device:** Samsung S22
**Android version:** 12
**Signal version:** 5.42.8

### Link to debug log

https://debuglogs.org/android/5.42.8/baa768267d1160935f5bf2690434f1a1d9f957504cb86028da0062216f447372

**Comment by adiastra** [comment]
Yay!

**Comment by clauz9** [comment]
This should probably be closed right ?
