### ISSUE TITLE
automatically rejected (spam) group invites don't say "was automatically rejeced"

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12342]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My conversation list has been flooded by group invites from a spammer. I didn't know this was happening because I saw no notifications. When I opened Signal I saw a large nuber of groups which makes I do not recognise and appearently I rejected those group invites (so it sais). I don't recall doing that (because I didn't) yet Signal states I did. It would be helpful if Signals texts are more accurately and say "Signal automatically rejected this group onbite for you because it suspects this is spam."

### Screenshots

![Screenshot_20220710-215046](https://user-images.githubusercontent.com/34976212/178160035-55506b1c-31db-44ce-be9d-29f46efa61df.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by Meteor0id** [comment]
@alex-signal i wouldn't call this a feature request, you guy introduced automatic rejection but forgot to review what impact it has on UX and if new strings should be added. Now we have tjis situation where you open Signal and it tells you you rejected invites which you don't recall doing. That's a confusing situation resulting from a change you made.
