### ISSUE TITLE
Signal, please stop harassing me in the name of verification

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#12359]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Your spam filter daily flags me as spammer and asks for verification every time I text people with continuous 3 - 4 messages. I kid you not,, it's super annoying to Googl'e ReCaptcha!

### Steps to reproduce
- Send continuous messages in chat

**Actual result:** Google's ReCaptcha being popped every now and then just like a mushroom
**Expected result:** Stop surveillancing chat by not checking the amount of message sent..

### Screenshots

This is the screenshot of me getting caught for infinite time!
![Screenshot_20220726-230030_Gallery](https://user-images.githubusercontent.com/69745008/181073165-f76c327a-4bdc-4417-a200-f3201aef726b.png)

### Device info

**Device:** DRG
**Android version:** 12.1
**Signal version:** 5.44.1

### Link to debug log

https://debuglogs.org/android/5.44.1/a5382a791edcf4eaa5bf66e68b1aedf473fb94f12bc0298e2469585cb17b0b28

**Comment by Dyras** [comment]
How many messages do you send before this happens exactly?

**Comment by cody-signal** [comment]
Hi there, looking through your logs, it looks like you are doing a couple things that could end up increasing the odds of being asked to verify:

- You seem to be unable to get access keys for a couple recipients which means you are sending multiple non-sealed sender messages
- You aren't using FCM, we use push tokens to help auto-verify you and without FCM we can't do that so we have to fall back to captcha
- You are using a VPN which puts you into a shared IP space where someone else could be doing sus things. I'm not saying don't use a VPN, lots of folks do and fully recognize the need/desires to use a VPN.
- You are running a custom build that could be interacting with the service in odd unexpected ways or have patches that prevent expect behaviors from occurring.

These are all speculative and not saying you should stop doing any of these things, just trying to give some context on why you may be encountering this so much.

**Comment by pixincreate** [comment]
> How many messages do you send before this happens exactly?

like some 5 messages in continuous or so....

> You seem to be unable to get access keys for a couple recipients which means you are sending multiple non-sealed sender messages

Can you elaborate this a bit, in an understandable way?

> You aren't using FCM, we use push tokens to help auto-verify you and without FCM we can't do that so we have to fall back to captcha

I have no idea why its falls to socket connections. When I tried to forcefully use GCM, I was never notified when a message arrived. I've removed all the permissions for GMS and have isolated that app with `XPrivacyLua`. May be that's what is causing this..

> You are using a VPN which puts you into a shared IP space where someone else could be doing sus things. I'm not saying don't use a VPN, lots of folks do and fully recognize the need/desires to use a VPN.

I use it because, I suspect that my ISP/ carrier provider is monitoring it's users and also, there exist no data privacy laws in the country that would benefit users. 

> You are running a custom build that could be interacting with the service in odd unexpected ways or have patches that prevent expect behaviors from occurring.

but I've never seen users reporting issues like this apart from me. So, I doubt this would be the cause..

**Comment by cody-signal** [comment]
> Can you elaborate this a bit, in an understandable way?

Here's an older blog post that explains the technology: https://signal.org/blog/sealed-sender/

It usually happens when you are messaging someone new/first time and do not have their profile. This is a rare thing to happen a lot in a short period of time during "normal" Signal usage. But something that happens a lot for bad actors that are sending lots of first time messages out.
