### ISSUE TITLE
"ENABLE SIGNAL FOR SMS" instead of reply box with Signal user in the Signal app

### ISSUE THREAD

**Issue by wavecommander** [signalapp/Signal-Android#12357]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Started being unable to send a Signal message to a single, specific user in the Signal app.

Oddly, ***and likely very important to finding out the underlying issue***, I was able to send a message to this Signal user if I tapped "Reply" on the system notification that appeared when they messaged me. A small overlay would appear where I could type and send a message to them, but when opening the full app, clicking on my conversation with this single user presented me with "ENABLE SIGNAL FOR SMS" instead of a reply box.

### Steps to reproduce

No clue, sorry

**Actual result:** Unable to send a Signal message to a Signal user within the Signal app

**Expected result:** Should be able to send a Signal message to a Signal user without enabling SMS

### Device info

**Device:** Google Pixel 4a
**Android version:** 11
**Signal version:** 5.30.5

### Link to debug log

https://gist.github.com/anonymous/2f554c3c1695534c7ba17ae76c3ad973

This isn't my debug log as I did not attempt a bug report at the exact time it happened to me. This is from https://github.com/signalapp/Signal-Android/issues/6079

### Additional Information

I just wanted to be able to message my contact and get it working again so I wiped/reset my phone after making backups and reinstalled Signal and it worked as normal. I tried reinstalling the Signal app, but the problem persisted. I had my contact reinstall the Signal app, but it persisted. Only upon wiping my phone were we able to message as normal.

Sorry. This bug was very frustrating and time consuming to deal with so when I saw that the issue had been auto closed I wanted to make sure that the devs are aware that this issue is still present.

Duplicate issue of: https://github.com/signalapp/Signal-Android/issues/6079

**Comment by cody-signal** [comment]
5.30.x is a fairly old build, did you try updating before wiping?

**Comment by wavecommander** [comment]
This happened in February. I was up to date at the time.

If this issue hasn't been explicitly looked for and solved it likely still had the potential to happen. The issue I linked that describes the same bug was raised in 2017.

**Comment by wavecommander** [comment]
Bump. This bug is really infuriating

**Comment by alex-signal** [comment]
There were some bugs with the transport logic earlier in the year that were looked at. Have you tried again on the latest version of the client?

**Comment by wavecommander** [comment]
I am unable to reproduce the bug. I don't know what caused it in the first place.
I may take a look at the code myself if I have time.

Are you able to cite the commits of those bug fixes you mention?

**Comment by greyson-signal** [comment]
I think I know what this bug was, and I'm fairly certain it's been fixed. This type of thing would happen if there was a mismatch between the multiple ways a user could be detected as 'registered'. One would tell us the user was registered, and one wouldn't. And without getting too into the weeds, there was a bug in the client implementation of the one that would sometimes incorrectly tell us a user is unregistered that has since been fixed. I'm ok with closing this.
