### ISSUE TITLE
wiki/Submitting-useful-bug-reports is not available

### ISSUE THREAD

**Issue by solzard** [signalapp/Signal-Android#12351]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Issue template and [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/041bde3fd97a97d724c6c6c4c151cee4f0399d48/CONTRIBUTING.md) have links to https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports . However, the wiki page is not available anymore and redirected to the README of Signal-Android. The links should be removed.

### Steps to reproduce
- Open a new issue / [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/041bde3fd97a97d724c6c6c4c151cee4f0399d48/CONTRIBUTING.md)
- Click the link to https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

**Actual result:** Redirect to https://github.com/signalapp/Signal-Android/
**Expected result:** See a wiki page

**Comment by yjhn** [comment]
Can you check again? The page is loading just fine for me.

**Comment by solzard** [comment]
I'm not sure why, but it's obviously available now. Close this.

**Comment by cody-signal** [comment]
The wiki was removed for a period of time on our end and then restored.
