### ISSUE TITLE
switch to openstreetmap for location sharing

### ISSUE THREAD

**Issue by holequantum** [signalapp/Signal-Android#12352]
for devices with no gapps and play services there are lots of issues in signal while shareing location stuff i think it should switch to something called openstreetmap openstreetmap.org/ i really hope to see switch to a better alternative such as openstreetmap

**Comment by UserX404** [comment]
Hi
Devs use GutHub as bug tracker only.
Please close this issue and continue discussion on the forum -> https://community.signalusers.org/t/use-openstreetmap-instead-of-google-maps/5434

**Comment by holequantum** [comment]
yes i have seen that but it was in avtopic since 2019 and havenot been implemented so i make it bug report for grab the eye of core devs.
