### ISSUE TITLE
Freeze at white screen before splash screen after reinstallation from Play Store

### ISSUE THREAD

**Issue by KeefeJ** [signalapp/Signal-Android#12367]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal used to work fine on this phone (stock rom, never rooted, app from Play Store), but on Jul 30 it began failing to launch, with Android reporting that "Signal keeps stopping." I don't know if the app had recently updated. Neither clearing its cache, nor rebooting the phone helped. Launching while offline didn't make a difference. Clearing data didn't fix it.

Uninstalled and reinstalled from the Play Store. Upon launch, the phone screen just goes mostly white (top icons and back/home/apps buttons on bottom still visible, and the rest of the screen semi-transparent), no splash screen, nothing about setting up or restoring backup.

Captured a log with `adb logcat` after the steps below while online.

The primary (at launch?) error appears to be:
`E AndroidRuntime: net.zetetic.database.sqlcipher.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database`
But I also get this earlier error (at install?):
`E PackageManager: Failed to create app data for org.thoughtcrime.securesms: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /data/data/org.thoughtcrime.securesms (code 0)`
Note that the phone's storage was less than half full, and I have since installed other apps without issue.

Is there anything I should do to ensure a fresh install with no potential of lingering effects from the original app crash? I'm just assuming that uninstalling the app removes anything that could impact the reinstall.

### Steps to reproduce
- uninstall Signal app
- reboot phone
- install Signal app from Play Store
- launch Signal app

**Actual result:** Hangs with white screen before splash screen.
**Expected result:** Splash screen, then prompt to setup or restore from backup.

### Screenshots

![image](https://user-images.githubusercontent.com/845582/182537845-57912968-fad8-43e8-a451-35a8a3b09abf.png)

### Device info

**Device:** Motorola Z2
**Android version:** 9.0
**Signal version:** 5.43.7

### Link to debug log

Can't get a log from the app because of launch hang.
Log from ADB logcat, manually pruned: [signal_install.txt](https://github.com/signalapp/Signal-Android/files/9248913/signal_install.txt)

**Comment by greyson-signal** [comment]
```
07-30 20:38:25.616  1901  2055 E PackageManager: Failed to create app data for org.thoughtcrime.securesms: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /data/data/org.thoughtcrime.securesms (code 0)
```

Yeah, this is super weird. It's not giving us access to our own storage directory. And so it can't access our locally-stored database (it might have been what caused the problem on your original install). Nothing should restrict access to our own internal storage directory.

I've never seen this specific issue before, but I've seen similar things when users are running custom ROMs.
Are you running a custom ROM? Do you run any apps that could be restricting storage access?

**Comment by KeefeJ** [comment]
It's the stock rom, never rooted.

What apps could restrict storage access?

I noticed that Verizon's "Digital Secure" app (com.securityandprivacy.android.verizon.vms) is getting notified of the installation, if I'm interpreting those BroadcastQueue log entries correctly. Could that app be a problem? But that app is on most Verizon phones, with something like 100M installs, so it seems quite unlikely to be causing an issue for just me.

**Comment by KeefeJ** [comment]
I tried disabling Digital Secure, and uninstalling/reinstalling Signal. No change. I still get the "failed to create app data" error. Any other ideas?

**Comment by greyson-signal** [comment]
I'm sorry, but right now I'm coming up blank. The 'scorched earth' approach would be doing some sort of factory reset, but obviously that's pretty extreme.

**Comment by Genis-Sage** [comment]
@KeefeJ 
searching a bit for the error message

super old Signal issue #7402
for whatever reason, the issue was gone by installing Signal from a different source:
[Reinstalling Signal via Play Store did not help. But when Signal is installed by Yalp Store, it suddenly works fine.](https://github.com/signalapp/Signal-Android/issues/7402#issuecomment-367612520)

and from another app:
[PasswdSafe Bugs](https://sourceforge.net/p/passwdsafe/bugs/68/)
here, it seemed to be connected to a mal-functioning SD card


perhaps, something with the storage of your phone is wrong, and Android tries to install Signal always to the same part.... but that's really just a shot into the blue

you could try to check, if your phone did a trim of the storage
taken from [[How can I know if fstrim was run when I put my phone on charging over night?](https://androidhiro.com/source/questions/answer/213937/how-can-i-know-if-fstrim-was-run-when-i-put-my-phone-on-charging-over-night)](https://androidhiro.com/source/questions/answer/213937/how-can-i-know-if-fstrim-was-run-when-i-put-my-phone-on-charging-over-night)
check the date if the file "/data/system/last-fstrim"

**Comment by iamnathanwindsor** [comment]
How do you install Signal via Yalp?

I updated Signal via Google Play, but now I get the same white screen of death.

I can't find the right version to install either. I type in 115600 for Version: 6.0.6, and it says, "Not Available"

I downloaded the APK from signal directly, and when I try to update, it says, "App not installed." Any ideas?
