### ISSUE TITLE
(Regression) Parsing of URLs with trailing paranthesis

### ISSUE THREAD

**Issue by liqpap** [signalapp/Signal-Android#12368]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports (page not available at the moment?)
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Clicking on a URL ending with ')' results in it being cut off when handling the URL. Might be related to https://github.com/signalapp/Signal-Android/issues/9449 which seems to be the opposite problem

### Steps to reproduce
- Click on URL with trailing paranthesis, e.g. https://de.m.wikipedia.org/wiki/Red_Dawn_(2012) 

**Actual result:** browser opens https://de.m.wikipedia.org/wiki/Red_Dawn_(2012 - Error 404

**Expected result:** browser opens the correct URL

### Screenshots

![signal-2022-08-03-094651_002](https://user-images.githubusercontent.com/22499395/182557361-c2954ddf-470d-4675-987f-64b8c21491e7.jpeg)

(notice the missing underlining of the closing paranthesis)

Older signal versions (5.42.7) show the correct behaviour:

![old](https://user-images.githubusercontent.com/22499395/182558095-ee130e38-ee21-4f80-a3a0-29acf1677a9e.jpeg)

### Device info

**Device:** Google Pixel 4a 5G, multiple other devices 
**Android version:** 12 (also tested in 11)
**Signal version:** 5.44.3 (regression to 5.42.7 where it still worked correctly)

### Link to debug log
not applicable

**Comment by greyson-signal** [comment]
We rely entirely on the system linkifier. Links should be handled like they are anywhere else in Android.

It does seem that it treats a message containing

```
https://de.m.wikipedia.org/wiki/Red_Dawn_(2012)
```

Differently from a message of
```
https://de.m.wikipedia.org/wiki/Red_Dawn_(2012)

 🤔😜
```
Seems like the linkifier behaves differently if there's text after it. My guess is that since there's other text, it doesn't know if the `)` is part of the url, or if someone was putting the url itself in parens. Here's an instance where you _wouldn't_ want the paren:

```
I'm gonna go do a web search (kagi.com) and see if I get a good result.
```

Parsing links is a hard problem that I think is best left to the system to solve, even if it's not perfect.

**Comment by liqpap** [comment]
> We rely entirely on the system linkifier. Links should be handled like they are anywhere else in Android.

Is that a recent development and you used another way of parsing URLs before? As described: in Signal 5.42.7 it behaves as expected, same system 5 minutes later with updated Signal and no change to the underlying system it broke.

However checking with another application it shows the same behavior as Signal does now, with the "wrong" interpretation of the link.

**Comment by greyson-signal** [comment]
It's been the case for years, yeah. I couldn't say more without really digging into things.
