### ISSUE TITLE
Text limit with attach

### ISSUE THREAD

**Issue by dreem2001** [signalapp/Signal-Android#12369]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since update the application on march the application doesn't allow to type more than 700 characters (any language) in case there's an attachment (any size).
Once the attachment is deleted, it allows to add any number of symbols.
In case you typed more than 700 symbols and attach e.g. the text is automatically cut to 700 symbols.
Desktop or iPhone don't have such limitation. 

### Steps to reproduce
Add an any size picture, try to type of paste text large than 700 symbols. 

**Actual result:** Signal doesn't allow to type long text with attachment
**Expected result:** Signal allows send messages with attachments and text longer than 700 chars.

### Device info
**Device:** Google Pixel 4XL
**Android version:** 12.1
**Signal version:** 5.44.3

**Comment by dreem2001** [comment]
The issue appears again. Could someone help with it? Thanks!

**Comment by nicholas-signal** [comment]
> The issue appears again. Could someone help with it? Thanks!

Do you have Stories enabled?

**Comment by nicholas-signal** [comment]
If you have the Stories feature enabled, you are limited to 700 character in Stories and in Chats.

You may [Disable the Stories feature](https://support.signal.org/hc/en-us/articles/5008009166234-Stories#story_turn_off) to remove this limit.

Please let me know if Stories are disabled and you're still being limited.

**Comment by dreem2001** [comment]
@nicholas-signal  Thanks a lot, sir! It definitely helped :)
