### ISSUE TITLE
Camera Orientation

### ISSUE THREAD

**Issue by aaemon** [signalapp/Signal-Android#12362]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Camera orientation has become unstable in last few update. When we take photo we want it as it is captured. Not like oriented by any means. Also camera shutter button changes position when you want to take a photo at a different angle. In any other camera app I have never seen camera shutter button changes position. I have already discussed this in the signal reddit community and everyone facing the same irritating issue.

### Steps to reproduce
- change your phone orientation while signal in built camera in turned on
- take photo while physically changing phone orientation.

**Actual result:** Camera shutter button changes position, also sometimes the image captured is oriented. 
**Expected result:** Camera shutter button should not change position and image should be captured as it is when taking the shot, not oriented.

### Device info

**Device:** Mi A2
**Android version:** 10
**Signal version:** 5.43.7

**Comment by dreambucket13** [comment]
I cannot seem to reproduce this issue - running v5.49.0, Pixel 4a

**Comment by alex-signal** [comment]
Please take a look on a newer version. We recently updated cameraX and we locked the screen to portrait mode, so the shutter button should no longer move.

**Comment by aaemon** [comment]
newer version fixes the issue. Thanks
