### ISSUE TITLE
No way to disable emoji suggestion

### ISSUE THREAD

**Issue by slmb3** [signalapp/Signal-Android#12371]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports (was the wiki deleted? Link isn't working for me)
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji suggestion popup, such as when typing "cat", is pretty cool. But it can be very distracting so there needs to be a way to disable it. Also, I think option for disabling the vibration but keeping the suggestion popup might be useful.

### Steps to reproduce
- Type a word related to an emoji, like cat
- observe popup with emoji suggestion

**Actual result:** No obvious way to disable
**Expected result:** There should be a way to disable

### Screenshots
![Screenshot_20220804-173639](https://user-images.githubusercontent.com/80601335/182905787-e1dbcd48-a5e1-4aea-8e88-a4e3924b14a4.jpg)

### Device info
**Android version:** 11
**Signal version:** 5.45

**Comment by ChrislyBear-GH** [comment]
Same here. Couldn't find a way to disable the disruptive vibration and covering of the previous message by these unnecessary suggestion popup.

**Comment by greyson-signal** [comment]
This has already been addressed in 5.45.1, thanks!

**Comment by slmb3** [comment]
Whoops, should have checked for updates first. Thanks!
