### ISSUE TITLE
Learn more link leads to 404 page

### ISSUE THREAD

**Issue by AlertSubject** [signalapp/Signal-Android#12376]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A link in the app leads to a 404 page

### Steps to reproduce
- Open a chat
- go to the safety number section
- press learn more

**Actual result:** 
You get redirected to a 404
Most likely because the "learn more" button doesn't link to the help page directly but instead to a redirect page 
**Expected result:** 
I should be shown some lovely information on how safety numbers work

**Comment by greyson-signal** [comment]
Pretty sure this was fixed a while back
