### ISSUE TITLE
Signal crashes with AssertionError "Should never try to insert My Story"

### ISSUE THREAD

**Issue by bitwave** [signalapp/Signal-Android#12370]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening the Signal App produces a crash.

### Steps to reproduce
- Open Signal App
- Wait some seconds
- Signal app crashes

**Actual result:** 
Signal App crashes with AssertionError
**Expected result:**
Signal App works normally and does not force close itself.

### Device info

**Device:** Motorola moto G Pro
**Android version:** 11
**Signal version:** 5.44.3

### Link to debug log

Cannot gathered as Signal crashes before trying to do so. Crashlogs/Stacktraces sent via Googles crash collector.
But the crash happens here: https://github.com/signalapp/Signal-Android/blob/efb82369b6644dea10e5769cdb9eb3ba8018aef9/app/src/main/java/org/thoughtcrime/securesms/database/DistributionListDatabase.kt#L562

**Comment by reggiii** [comment]
Hi, I have the same phone and error as the previous user, so I also can't upload a crash log. I did screenshot the beginning of it though so it may or may not be helpful, sorry for the bump 
![EHMdIov](https://user-images.githubusercontent.com/110631211/182934094-ff054e47-aa2b-4e62-b059-8107b7863ab9.jpg)

**Comment by jackreid** [comment]
Same bug happening here on Signal v5.44.3 on Android 10, moto g(7). Notably this only occurs if the phone is connected to network. I can open it fine while on airplane mode. This enabled me to save a backup, uninstall the app, and restore from backup. Unfortunately the bug immediately resumed as soon as I was finished logging in.

![Screenshot_20220804-151002](https://user-images.githubusercontent.com/25727967/182941426-04385514-f3ea-4beb-a451-6279bf2fe8e7.png)
![Screenshot_20220804-151010](https://user-images.githubusercontent.com/25727967/182941429-fdf04917-669a-4d48-aa70-7acf81caf990.png)

Here is the debug log from the desktop app (which is still working fine): https://debuglogs.org/desktop/5.53.0/3933db6751ca6090f1e0fe9f7b8812954936ab52b2f028b9002b7d732818dc49.gz

**Comment by jackreid** [comment]
As an update, a second round of backing up while on airplane mode + reinstalling seems to have resolved the issue. 

Here is the debug log from after resolution in case that helps anyone track down the source of the error: https://debuglogs.org/android/5.44.3/b1c556370514fe94e517a7cb93d4ff853b26894b75f53b91baa7ce424cacaf86

**Comment by greyson-signal** [comment]
Hey folks, really sorry about this. We have a hopeful fix in the current beta (5.45.1 has some fix, 5.45.2 has another one). Fingers crossed all will work well afterwards for people that ran into this.

**Comment by reggiii** [comment]
Just got onto the beta through the play store. It's 5.45.2 and I'm still having the exact same issue. 
I'm on a moto g power and on Android 11 for reference. 

I haven't had time to try a full backup/reinstall yet, but will try that when possible. 

Appreciate the timely response

**Comment by greyson-signal** [comment]
Hi @reggiii, are you able to get us a debuglog? It'd be super-helpful and allow us to narrow down the crash. I know you likely can't get to the in-app debuglog, but you could use adb to get us a log, which you can download [here](https://developer.android.com/studio/releases/platform-tools).

You could also upload more screenshots of the debuglogs preview in the worst case.

**Comment by reggiii** [comment]
For sure, here's the log 
[signalcrashlog.txt](https://github.com/signalapp/Signal-Android/files/9269147/signalcrashlog.txt)

**Comment by dimbdr** [comment]
Hi, I'm also reporting the same behavior. When I open the app, few seconds later it crashes, whatever I do (or do nothing).
At first, it crashed on 5.44.3, then I installed the 5.45.2 right after reading this issue, but same result.
Here the logs I could gather with logcat
[signal_5.45.2_crash.txt](https://github.com/signalapp/Signal-Android/files/9269850/signal_5.45.2_crash.txt)

Android version: 11
Device: Moto g 5G plus
Signal version: 5.45.2

**Comment by DKhalil** [comment]
Same here on 5.45.2 on android 11 on a moto g9 plus

**Comment by NeMoeImya** [comment]
I appear to be having the same issue.

Messages will still show up in my notifications, but if I click on them to read them, the app begins to open, then shuts down and gives the error message “Signal keeps stopping” with an option to get App info, Close app, or Send feedback.

I am using Version 5.44.3 on a Moto G Power (2021) phone running Android version 11.

I am attaching here the screenshots of the debug logs, which I can access when I am in airplane mode. I am not sure in what order they will upload but the screenshots should show the system info, the latest error message, and then I scrolled down to take a shot of where the first FATAL ERROR message appeared today and then have two pictures of that (one scrolled over to the right so you can read more of the message).
![Screenshot (Aug 4, 2022 9_04_36 PM)](https://user-images.githubusercontent.com/110687893/183124769-06c57e05-a78d-4335-b1ef-848e42dbbd0c.png)
![Screenshot (Aug 4, 2022 9_02_26 PM)](https://user-images.githubusercontent.com/110687893/183124773-62ab4e87-8e10-4fd6-8ee8-03a5b769a619.png)
![Screenshot (Aug 4, 2022 9_00_44 PM)](https://user-images.githubusercontent.com/110687893/183124775-0c02de63-e031-4ff6-9fb9-a9f46088d8e2.png)
![Screenshot_20220804-205927-555](https://user-images.githubusercontent.com/110687893/183124776-89a7631d-c376-46b5-a8d4-026ef039e066.png)

**Comment by NotAProfessionalDeveloper** [comment]
Same here 
![Uploading Screenshot_20220805-205441.png…]()

**Comment by NotAProfessionalDeveloper** [comment]
Same here
![Screenshot_20220805-205441](https://user-images.githubusercontent.com/277893/183143549-ade98d0a-5607-4acd-a428-1a40bbf9cddd.png)

**Comment by greyson-signal** [comment]
Thank you all for the info. We just released 5.45.3 that probably doesn't fix it, but does give us more debugging info. The other helpful thing we added: the ability to save a debuglog to a zip file on your device. So you can go into airplane mode, go to the debuglog screen, tap the three-dot menu, select save, and then share that zip file :) That's been on my todo list for a while to add, but this gave me a good excuse :sweat_smile: 

(Some background: the crash results from an invalid DB state, and none of our attempts to clean it up seem to be working, so 5.45.8 is more about gathering more info in logs)

**Comment by DKhalil** [comment]
[signal-log-1659732342503.zip](https://github.com/signalapp/Signal-Android/files/9272805/signal-log-1659732342503.zip)

Here's my debug log

**Comment by greyson-signal** [comment]
Thank you for the logs! Just released 5.45.4 to beta (may take a few hours for it to show up on the Play Store) with a hopeful fix. Whether it's fixed or still broken, another log will be helpful to confirm our theories :) Thanks!

**Comment by lemondropkids2** [comment]
[signal-log-1659738850624.zip](https://github.com/signalapp/Signal-Android/files/9273888/signal-log-1659738850624.zip)

Here is another

**Comment by tiagopereira** [comment]
Same error here on version 5.44.4. As soon as signal connects to network, it crashes. Can't submit an error log because of this.

**Comment by GeoffreyCrouton** [comment]
> As an update, a second round of backing up while on airplane mode + reinstalling seems to have resolved the issue.
> 

Thank you SO much! I thought a very large group chat was gone forever, but airplane mode has allowed me to open the app on my phone and backup. Upvote this work around!

I'm on a Moto G7 power running Android 10 (there seems to be a trend with Moto users reporting this.)

**Comment by tiagopereira** [comment]
Moto G100 on Android 11 here. Two rounds of backup without internet + reinstall did not solve the issue for me, unfortunately. Still crashing as soon as it has internet.

**Comment by greyson-signal** [comment]
Hey folks, appreciate all the logs for sure, but for now I think I'm good on logs from 5.45.3.

 If I could get logs from 5.45.4 that'd be very much appreciated. Thanks!

**Comment by DKhalil** [comment]
@greyson-signal yeah, as soon as it's up on the store I'll get you a log, but so far it's still on .3

**Comment by NotAProfessionalDeveloper** [comment]
Hmm I updated to 5.44.4 but there is no three dot menu in the debug screen. 
![Screenshot_20220806-100235](https://user-images.githubusercontent.com/277893/183240378-9108348f-6d88-4f20-849d-913af8fc19ee.png)

**Comment by greyson-signal** [comment]
Sorry, I know the version names are similar, but all of these changes are in 5.45.4 (only in beta), not 5.44.4 (prod). If we can confirm a fix in 5.45.4, I'll hotfix it to prod.

**Comment by DKhalil** [comment]
@greyson-signal shouldn't the new version have been released by now? Or is it possible to take so long?

**Comment by greyson-signal** [comment]
It can, indeed, take a while. Google's review times are wildly inconsistent, and it's still under review. If you'd like, you can get the APK via Firebase App Distribution:
https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-distribution/17538

**Comment by dimbdr** [comment]
Hi,
I installed the version 5.45.4, and there's no longer a crash while being connected to a data service. It seems the fix works quite well!
Just to be sure, you can find some logs in case there woild be something fishy.
https://debuglogs.org/android/5.45.4/a7264c12cf26ddc5dc7f049452fb1c2c5317f9d29995e8ca3b7e7e9577bff19b

**Comment by lemondropkids2** [comment]
I have installed 5.45.4 and it has fixed the crashing problem for me as well. Here is the log file taken after installation of 5.45.4 and being able to get back into the app.  Hopefully it helps.

Thank you for all the work in getting this resolved.

[signal-log-1659796384300.zip](https://github.com/signalapp/Signal-Android/files/9275236/signal-log-1659796384300.zip)

**Comment by NeMoeImya** [comment]
Installed 5.45.4 and it has also fixed my issue. The Firebase App distribution method worked flawlessly and was very easy to do.

Thank you so much for this, Greyson. I never realized just how dependent on the app I am for my professional life until all of a sudden it wasn't there!

**Comment by greyson-signal** [comment]
Perfect! I'll prepare a hotfix for the production release then, thanks everyone for confirming!

The observant among you may have noticed that everyone with the problem seems to have a Moto G device... and the log confirms that this is because the Moto G appears to have a bug in it's UUID implementation that causes the `toString()` of a UUID of all zeros to be `0000-0000` instead of the proper `00000000-0000-0000-0000-000000000000`. This caused us to be unable to find something in the database that we knew was there. It's pretty wild, but the logs ya'll submitted confirmed it, and this is why it took us so long to figure it out.

Thanks again, and apologies for the inconvenience!

**Comment by NotAProfessionalDeveloper** [comment]
Let's file a bug with Motorola 😂

**Comment by aarelovich** [comment]
Hi I also have a Motorola G Phone. I also have the same issue. I managed to submit my log and I would also like to note that I'm using version 5.44.5 https://debuglogs.org/android/5.44.5/da4b6280a2591fea253bc4c2d0f3f50d538835603853973c9230ecf0d58559a2
I would really appreciate any insight to this. As I have not been able to use signal and it is the only application my boss trusts.

**Comment by NotAProfessionalDeveloper** [comment]
I can confirm the issue seems to be fixed on my phone (motorola g60s) in 5.44.5. at least it's no longer crashing on start. 🍾

**Comment by TobiasWenzel** [comment]
> I can confirm the issue seems to be fixed on my phone (motorola g60s) in 5.44.5. at least it's no longer crashing on start. 🍾

Same here. With the latest officially released version from the Google Playstore the crash is now gone. 👍 
Thanks @greyson-signal for the quick help, even on the week-end! 🚀

**Comment by bitwave** [comment]
> I can confirm the issue seems to be fixed on my phone (motorola g60s) in 5.44.5. at least it's no longer crashing on start. champagne

Same here. Big thanks @greyson-signal and contributors!

**Comment by aarelovich** [comment]
I just downloaded version 5.44.5 and very unfortunately nothing changed. The option to generate the Debug Logs is now gone, so I'm not sure how to proceed.

I also have a Motorola Phone. I tried uninstalling the application and re-installing it, however as soon as I went out of the app and then inside it started doing the same thing again.

Furthermore I've noticed that my initials AA are changed to +2 whenever I go into the app and I can no longer change them back. 

How should I proceed?

**Comment by alex-signal** [comment]
Hi @aarelovich! Looks like you've got a separate (albeit bad)  issue. I'm going to ensure we're tracking this internally, and pass it off in the meantime.

If you don't mind, could you please file a new issue with your debug log from your last message? I'll make sure that the issue is referenced in the ticket, and we'll have a better place to go if we need more information from you :)

**Comment by aarelovich** [comment]
@alex-signal Thank you very much for the interest. It's a huge issue for me as my boss does not want to use ANY other messaging app other than signal. I created a new bug as instructed https://github.com/signalapp/Signal-Android/issues/12380. If you could tell me how to generate newer logs I will. It's very very important for me to get this working ASAP and will do everythign in my power to make it so.,

**Comment by GeoffreyCrouton** [comment]
Thank you so much @greyson-signal for fixing this! Once 5.45.4 beta showed up in the Play store it fixed the problem for me and is much appreciated.

Note, for all of you running a non-beta version (i.e. 5.44.5 or something,) the only version that fixes the problem is 5.**45.4** or newer. Currently you have to be enrolled in the beta program to use this, but @greyson-signal has said he plans to push this to production soon since it is resolved on the beta side. Testing 5.**44**.5 does not accomplish anything further on this ticket.

**Comment by NotAProfessionalDeveloper** [comment]
I can't confirm that only 5.45.4 fixes it. After updating to 5.44.5 it is fine on my end.
Maybe there are several issues here.

**Comment by alex-signal** [comment]
We hotfixed this in prod and pushed out the same fix into a beta at the same time.

**Comment by aarelovich** [comment]
I am not in the Beta. Is there a way that I can try the hotfix to see If I can get my signal back?

**Comment by greyson-signal** [comment]
The fix is also in 5.44.5, which is in production. You can also get it from our [website](https://signal.org/android/apk/).

**Comment by aarelovich** [comment]
So If I already have 5.44.5 installed from 2 days ago, is it worth it to install via APK again? Because it currently does nto work for me. Thank you for your help!

**Comment by NotAProfessionalDeveloper** [comment]
@aarelovich maybe u should continue ur messages in #12380 as that seems to be ur issue

**Comment by GeoffreyCrouton** [comment]
> We hotfixed this in prod and pushed out the same fix into a beta at the same time.

Thank you for the clarification Alex, and all your hard work making this a great app.
