### ISSUE TITLE
Unable to switch between SMS and Signal text message - Pixel 2 Android 11

### ISSUE THREAD

**Issue by nmw01223** [signalapp/Signal-Android#12373]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using Signal for text message on Android Google Pixel 2, Android OS 11. With a recipient who has Signal, it always defaults to Signal message as opposed to SMS/unsecured. However if away from wifi with no mobile data, SMS is needed.

To switch between Signal and SMS, a long press on the send button is used - but with no text to send the button is not present, so text has to be written first.

If the phone is portrait, on tapping the text field, and soft keyboard appears, some text can be entered, and a long press then carried out to switch to SMS. But, if landscape (eg if in a cradle), on tapping the text field, a soft keyboard appears with a separate dialog box. Now if text is entered, the only option is to press Signal Message in the dialog - which sends it immediately. There is no long press on a send button available, so it is not possible to switch to an SMS message.

### Steps to reproduce
- Tap new text message button
- Select a text recipient from contacts who has Signal
- Have the phone in landscape orientation
- Tap text input field to bring up keyboard
- Enter at least one character

Pressing the signal message button will now send that text by Signal message, there is no way to switch to SMS message first
Ideally a long press on the Signal message button should switch mode to SMS and vice versa

A simpler alternative might well be to always have the send button there whether characters have been typed or not. Then the long press will always work to change send mode, but on a short press, no action could be taken if no text characters present, possibly putting up a short toast message to say why not sent.

### Device info
Google Pixel 2
Android 11
Signal V5.44.3

**Comment by greyson-signal** [comment]
Hi there, thanks for the detailed report. You can actually long-press on the button while it is still a '+' and it should let you switch to SMS -- no need for it to be the '>'. 

Landscape text entry in android apps is weird. We kinda just let android do it's thing, since the keyboard covers so much in that mode. I don't think we'll be changing anything there, but thanks!
