### ISSUE TITLE
Hangup on keyboard usage

### ISSUE THREAD

**Issue by CannyDuck** [signalapp/Signal-Android#12374]
After the last update, Signal is not usable for me anymore. If the keyboard is opened when I want to type a message, the app get extremely slow slow and a character input is nearly not  possible. So I have to kill the app, because to whole Android freezes. Everything was fine before the last update. Using gboard keyboard, also tried with Swiftkey,, same behave. Using Android 8.

What I tried without success:

- phone restart
- reinstall Signal
- reinstall Gboard

**Comment by greyson-signal** [comment]
Are you able to post a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) taken after the issue occurs? Thanks!

**Comment by CannyDuck** [comment]
https://debuglogs.org/android/5.44.3/4f0b1ca49ed670e5e42e6ecff7f606ce3453d68b82064d7af85471d311f8c5e5

**Comment by CannyDuck** [comment]
I reverted to 5.41.15 that works for me.
