### ISSUE TITLE
Impossible to accept an invitation

### ISSUE THREAD

**Issue by sneko** [signalapp/Signal-Android#12383]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Yesterday I created a group while inviting 4 members. Directly after clicking the "create group" button I ended with an error about a friend not being added (it was on desktop).

I was not able to see him in the group but the friend told me he was seeing the invitation but was not able to accept. Each time he clicks on "Accept" a loader appears and nothing happens **(he is on Android)**.

On my side, I checked if I was able to invite him again but:
- From the members list I can't see him
- When trying to add him a new time, I get an error "already in the group"

About my admin side, I'm unable to add him again on iOS and Desktop (I posted comments there because the behavior is not consistent for the error shown):
- https://github.com/signalapp/Signal-iOS/issues/4466#issuecomment-1210248618
- https://github.com/signalapp/Signal-Desktop/issues/4314#issuecomment-1210253416

About my friend:
- he is stuck, and not having any error toaster when the accept loader ends, which is frustrating...
- I just asked him to "remove" the invitation to see if it unlocks things. He was able to do so, so a new time I invited him, but he was still stuck to accept the new invitation
- I created another group with 2 people (him included), and same issue

It seems linked to his profile... that's so weird.

When describing the case it looks like a backend error at the end... but still, at least on Android the "accept" not working should display something.

Thank you,

### Steps to reproduce

Not able to reproduce the issue with other people, only with this user...

### Screenshots

<img width="413" alt="image" src="https://user-images.githubusercontent.com/8195958/183841710-61c49cf1-25e4-4ffe-866b-4ee63e574ce8.png">

### Device info
**Signal version:** 5.44.5 (friend version on Android)

**Comment by alex-signal** [comment]
Can you please get your friend to try joining and then grabbing a debug log from their device (Settings -> Help -> Debug Log)

**Comment by sneko** [comment]
@alex-signal here it is:
[1ad27fdc7c0ed9e12231648f38ec5b1c7ef134ef0113bc7b1dfb34614e28d83e.gz](https://github.com/signalapp/Signal-Android/files/9300098/1ad27fdc7c0ed9e12231648f38ec5b1c7ef134ef0113bc7b1dfb34614e28d83e.gz)

**Comment by sneko** [comment]
@alex-signal I posted debugs logs from my side (when inviting him) in case it can help, for both situations:
* Adding him a new time when invitation already sent but he cannot accept
* Creating a brand new group with him as member

Please find those for iOS and Desktop (I tested both because the behavior/messaging was not consistent between the two platforms):
* iOS: https://github.com/signalapp/Signal-iOS/issues/4466#issuecomment-1211980568
* Desktop: https://github.com/signalapp/Signal-Desktop/issues/4314#issuecomment-1211976548

**Comment by cody-signal** [comment]
Can you have your friend change something on their profile and try again? Like can they change their profile name to something and then they can change it right back. And then try to accept the invite?

**Comment by sneko** [comment]
@cody-signal that was it!

For no reason he had no firstname/lastname filled. Which is really weird because we were able to add him to groups in the past. And he told me he didn't change his phone or uninstalled/re-installed.

Do you know what could explain this situation? (after setting a name he was able to accept invitations)

I guess he won't be the only one:
* maybe on the client side, when trying to accept an invitation an error toaster could say "please set a name to enter conversations"
* or better... propose a button to go to settings

Thank you for the tip!

**Comment by cody-signal** [comment]
We are already working on this, this is the second report we've gotten about a profile being lost. Do you know if your friend has any linked devices?

**Comment by sneko** [comment]
@cody-signal he says he didn't

**Comment by cody-signal** [comment]
@sneko can you have your friend get us another debuglog?

**Comment by sneko** [comment]
@cody-signal I will try to have him to do it over the weekend but cannot guarantee that ^^.

What steps does he need to perform after starting the application (specific actions...)?

**Comment by cody-signal** [comment]
Same as before, Settings -> Help -> Debug Log and send us the link

**Comment by sneko** [comment]
@cody-signal here it is:
https://debuglogs.org/android/5.45.6/1c33abebd7e7999b025c74fdf535c9a87b0cacf55a724d21dbfe0e17ed434c00

**Comment by cody-signal** [comment]
Thank you! We are adding some protections to keep this from happening again. Do you mind if a close this ticket?

**Comment by sneko** [comment]
It's good for me, problem solved on our end :)
