### ISSUE TITLE
Duplicate messages with delay

### ISSUE THREAD

**Issue by CallMeFlanby** [signalapp/Signal-Android#12389]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Today I got a message from the 8th August (it is the 12th) and it is a duplicate message shown between messages from today. 

### Steps to reproduce
- don't know how it happened, just opened a conversation 

**Actual result:** 
A message from the a few days before is between the messages from today. 

**Expected result:** 
Messages ordered chronologically. 

### Screenshots
Duplicate bug
![Screenshot_20220812-164103_Signal.jpg](https://user-images.githubusercontent.com/7440579/184380040-1bf4c1e6-17b5-45fb-8bcd-205f391a6ee0.jpg)

Original message
![Screenshot_20220812-164121_Signal.jpg](https://user-images.githubusercontent.com/7440579/184379986-567a6f2c-7816-48ad-877b-34c1f87627d9.jpg)

### Device info
**Device:** Samsung Galaxy Note 10 
**Android version:** 12
**Signal version:** 5.46.1

### Link to debug log
https://debuglogs.org/android/5.46.1/d9c254840aad560ad08f3dd409f6115a30a5744dccfc8358ce570b2a65dd8fe0

**Comment by cody-signal** [comment]
Hi there, can you open the message details for the original and duplicate, long press the sent timestamp, this will copy the message id to your clipboard and could you then provide that for both the original and duplicate?

**Comment by CallMeFlanby** [comment]
> Hi there, can you open the message details for the original and duplicate, long press the sent timestamp, this will copy the message id to your clipboard and could you then provide that for both the original and duplicate?

Hello,

Of course.

Here you have:

Original: 1659991243873
![Screenshot_20220813-174950_Signal.jpg](https://user-images.githubusercontent.com/7440579/184501504-23ae487a-b0de-4fb0-9a3a-c2d33d967e39.jpg)

Duplicate: 1659991207224
![Screenshot_20220813-174930_Signal.jpg](https://user-images.githubusercontent.com/7440579/184501507-9aed517c-5191-4316-b433-be0a467198d7.jpg)

Thanks for your quick answer.

**Comment by cody-signal** [comment]
Thanks, do you happen to know what type of type the person that original sent the messages has? Would you be able to get their debuglogs as well?

Sorry for all the follow up questions. What we are seeing in the logs is really odd and nothing is really explaining what we're seeing.

**Comment by CallMeFlanby** [comment]
> Thanks, do you happen to know what type of type the person that original sent the messages has? Would you be able to get their debuglogs as well?
> 
> Sorry for all the follow up questions. What we are seeing in the logs is really odd and nothing is really explaining what we're seeing.

Hi, just saw your message, sorry for the delayed answer.

I talk to my friend and asked him if he can send me his logs.
Will also ask him, if it also happens to him and which version he uses. I only know he has an iPhone.

I will reply to your comment again as soon as I have his details.

**Comment by RyantHults** [comment]
Hi there, wanted to chime in and say I am seeing the same issue. 

The details for my latest instance of message duplication are:
original message:
`BRUH
Sent Aug 22, 2022, 12:38:56 PM CDT
Received Aug 22, 2022, 12:38:57 PM CDT
Via SMS`

duplicate message:
`BRUH
Sent Aug 22, 2022, 12:39:54 PM CDT
Received Aug 22, 2022, 12:39:56 PM CDT
Via SMS`

sender is on iphone using iMessage, I am on a Samsung S21 on android 12, August 1st 2022 security patch. 
according to sender's phone, message was sent Aug 22, 2022, 12:35 PM CDT

I have also experienced sent messages, both SMS and MMS, arriving hours later.

**Comment by greyson-signal** [comment]
@RyantHults Regarding SMS/MMS specifically, that protocol is sort of a dumpster fire. Carriers themselves will cause delays and re-deliveries of messages minutes, hours, or days later. There was a famous incident a few years ago where everyone was sent [8-month old SMS's from the previous Valentine's Day](https://www.bbc.com/news/technology-50345471).

So the TL;DR there is: can't do anything about SMS/MMS, but we _are_ interested in figuring out what happened with Signal messages :)

**Comment by CallMeFlanby** [comment]
> Thanks, do you happen to know what type of type the person that original sent the messages has? Would you be able to get their debuglogs as well?
> 
> Sorry for all the follow up questions. What we are seeing in the logs is really odd and nothing is really explaining what we're seeing.

So, here you have his debug logs: https://debuglogs.org/desktop/5.55.0/4f71fc9da7c81ef0a3a49d5e6f3c1bee83351f0b48abb9dc8c0a6e72d3de83e7.gz

This debug logs are from his MacOS version.

He also sent a screenshot from the duplicate message:
![image](https://user-images.githubusercontent.com/7440579/186167589-17ff2869-6e3a-42ae-9d52-5938ea8c0534.png)


I hope this helps.

**Comment by CallMeFlanby** [comment]
Closing the ticket due to no further feedback.
