### ISSUE TITLE
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports does not exist

### ISSUE THREAD

**Issue by rugk** [signalapp/Signal-Android#12394]
Your issue template tells me to read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports, but that does not exist or is set to private.

**Comment by cody-signal** [comment]
Thanks, this was unintentional and will be back shortly.

**Comment by rugk** [comment]
Apparently there again.
