### ISSUE TITLE
Unstable internet connection causes sealed-sender messages to be sent as unsealed-sender

### ISSUE THREAD

**Issue by stevie553** [signalapp/Signal-Android#12395]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you have an unstable internet connection, and the unidentified pipe times out. Signal falls back to the identified pipe, which sends a normal sealed-sender message as unsealed-sender.

### Steps to reproduce
I found this best to reproduce on a virtual device since you can throttle its internet easily.
- Create a new virtual device with Google Play Services installed (haven't tested without).
- Set the Network type to GPRS and the Signal strength to Poor.
- Send some text messages, you should now see that it takes longer to send and some messages are sent as unsealed-sender.
- If you don't get unsealed-sender messages the first time, try to forward 10 or 20 messages to one contact, then you'll find that some, if not all, of these messages will fall back to the identified pipe, marking the messages unsealed-sender.

**Actual result:** Falling back to the identified pipe if the unidentified pipe times out, which mistakenly marks a sealed-sender message as unsealed-sender.
**Expected result:** Maybe retry connecting to the unidentified pipe? I'm not sure how this should be fixed but falling back doesn't make much sense since both pipes are on the same server, so if you can't really reach one, you can't reach the other, I think?

### Device info

**Device:** Android Studio Pixel 3a Emulator
**Android version:** 12
**Signal version:** 5.46.3

### Link to debug log
https://debuglogs.org/android/5.46.3/c3e029732220969fece98979dc35aad60aacfb1e0554bf05bcfdb51dd85846b9

Note: I can reliably reproduce this bug, so if you want, fresh installs, fresh emulators, or an apk to test with, I'm okay with that.

**Comment by cody-signal** [comment]
Thanks I'll look into it.

**Comment by cody-signal** [comment]
Fix will be in 5.48, thanks for the detailed repro steps.
