### ISSUE TITLE
Turning off display stops voice message recording 

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#12408]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm recording a voice message by sliding the icon to the top to lock the recording mode without having to press the icon for longer.

I then begin to speak and switch off the display of the phone.

When I'm done recording, I turn on the display again only to see that the recording stopped the moment I switched off the display. The interface is is also messed up.

### Screenshots
![Screenshot_20220821-083648](https://user-images.githubusercontent.com/206281/185779029-1dad954b-f86d-4a29-b51e-b33094d28e51.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 12
**Signal version:** 5.46.3

**Comment by jnns** [comment]
> [...] we intentionally stop recording if you lock the screen or leave the chat in order to prevent people accidentally leaving the recorder on and recording stuff they didn't intend to.

Saw the comment quoted above in the linked pull request thread. 

I have difficulties imagining why this might be useful in the way it is implemented right now. If someone wants to record a conversation without others noticing they can just as well use the system's recorder app. Oftentimes I want to record a longer audio message, and the message being discarded when the display is switched off makes me have to record the message all over again. This is very annoying, especially on the long messages.

Are you open for a discussion to reconsider whether this is just "messy UI" or if the intended behavior is actually helpful for the majority of the userbase?

**Comment by greyson-signal** [comment]
The bug is just the "messy UI", and I believe that was actually fixed a few weeks ago. The risk of someone accidentally recording a bunch of stuff after they lock their screen is worse than the benefit some people may get, so we're going to be keeping the behavior the same.

**Comment by jnns** [comment]
Thanks. The UI definitely changed in the last few weeks although it the call to action button is still blank and not conveying the draft status of the message (see screenshot).

![Screenshot_20221220-163254](https://user-images.githubusercontent.com/206281/208707431-46c1bfff-4d1d-4b97-aea0-7714ead36e54.png)

It would also be great if the fact that the recording stopped would be indicated by the same sound that is played between voice messages that are played back-to-back. This would prevent people talking to the void for minutes.
