### ISSUE TITLE
Pinned SMS thread keeps unpinning itself

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12402]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have an SMS thread that is pinned, but for whatever reason it keeps unpinning itself. 

### Steps to reproduce
- Pin an SMS thread
- Ensure you have a linked device that is active

**Actual result:** The SMS thread eventually unpins itself. I am assuming its because its trying to sync with my linked device.
**Expected result:** SMS thread should stay pinned.

### Device info

**Device:** Google Pixel 5
**Android version:** 13
**Signal version:** 5.46.6

### Link to debug log

No debug log yet. I will attach once I notice it again.

**Comment by johanw666** [comment]
I have exactly the same issue. Debug log: https://debuglogs.org/android/5.47.2/79df957044ab8d2508d65578210c44f521819131924b5663c0b0b8385c3ef946

**Comment by greyson-signal** [comment]
Yeah, this is most likely because the user is unregistered, so the linked device ends up removing it. It shouldn't do that though.

**Comment by johanw666** [comment]
I had this issue in the past a few times and complained at the desktop Github but they seem to have ignored it: https://github.com/signalapp/Signal-Desktop/issues/5585

**Comment by greyson-signal** [comment]
Hi there, given our future plans to [remove SMS support](https://signal.org/blog/sms-removal-android/), I'm gonna close this. Thanks!
