### ISSUE TITLE
Change phone number numeric keyboard broken and doesn't auto-read text message

### ISSUE THREAD

**Issue by agilob** [signalapp/Signal-Android#12401]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing. Text message is delivered, but I can't read it without going back a few times. White space is a numeric keyboard, buttons are there, but none is displayed correctly. Text message with code isn't automatically filled.

### Steps to reproduce
- Attempt to change phone number

### Screenshots
![signal-2022-08-17-142157_002](https://user-images.githubusercontent.com/2544251/185117981-901c1227-4b24-4374-bcfe-c146cf368e17.png)

### Device info

**Device:** Nokia 8.3 5G
**Android version:** 12
**Signal version:** 5.45.6

**Comment by alex-signal** [comment]
Whoops! Looks like we hard-coded the text color. Will update.

**Comment by cody-signal** [comment]
The auto read is disabled in change number flow, but I'll look at enabling it.

**Comment by fobo66** [comment]
Auto-read is enabled now in 5.48.3
