### ISSUE TITLE
Android to Android transfer speed is abysmal (~100 messages per minute)

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#12418]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have recently acquired a new phone and was delighted that Signal-Android has a built-in ["transfer from smartphone in my left hand to the smartphone in my right hand"- feature](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_transfer). However, the transfer speed of messages is abysmal, the transfer has been running for half an hour and less than 3000 messages (0.4%) were transferred.

Given that speed I will be finished in a few days, which is unnacceptable for 2 Android devices in the same wifi.

### Steps to reproduce
- have an ~5gb Signal-Android installation
- start the transfer
- die of old age

**Actual result:** Less than 2 messages per second are transferred
**Expected result:** Signal-Android is transferring thousands of messages per second

### Device info
Sender:
**Device:** Redmi Note 3 Pro
**Android version:** 7.1.2
**Signal version:** 5.46.7
Receiver:
**Device:** FP3+
**Android version:** 12
**Signal version:** 5.47.3

### Link to debug log
Sending a debug log would require me to abort the procedure, and I need to have this done on Tuesday.

**Comment by alex-signal** [comment]
Hi! I'm sorry it's moving so slowly for you. I'm not sure how much help we can be on such a short timeframe. If this is taking that long via WiFi transfer, I'd recommend trying the backup route instead. (Turn on Airplane Mode, create a backup, move the backup to the new device, and then restore the backup). It's a bit more manual but should end up being a faster method of transfer for you.

**Comment by Trolldemorted** [comment]
Thanks a lot, have done that, worked like a charm!
