### ISSUE TITLE
Transfering data of Signal app from one phone to another not possible

### ISSUE THREAD

**Issue by SignalUser2022** [signalapp/Signal-Android#12411]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to use another phone to transfer the data of Signal app from my current phone to this new phone.
The two phones don't find each other and I get an error report "Conection not possible: Unexpected error has occured" even though I'm using the same Wifi, Bluetooth and Location services are activated and the Signal app has all needed permissions. 

This is quite problematic since I cannot create a backup of the Signal app on my current phone. I also created an issue on Github for this and sent a debug log [Report](https://github.com/signalapp/Signal-Android/issues/12062). So for now I cannot save any contents of this app.

### Steps to reproduce
- Start Signal app on both phones
- Activate all necessary networks and permissions
- Follow the instructions properly to transfer the data
- Get an error report on my current phone that the transfer is not possible

**Actual result:** 
The transfer of the Signal data to a new phone is not possible
**Expected result:** 
The transfer would complete so I could use the new phone

### Device info
**Device:** BQ Aquaris X
**Android version:** 12
**Signal version:** 5.46.6

### Link to debug log
I saved a debug log and can send it via E-Mail

**Comment by fillwithjoy1** [comment]
Well afaik you can backup chats and restore them **locally** in the Chat > Chat Backups. You can try to do that for now, until the devs start looking into this

**Comment by greyson-signal** [comment]
Please send your log to greyson@signal.org

**Comment by SignalUser2022** [comment]
done

**Comment by SignalUser2022** [comment]
@fillwithjoy1 like I already mentioned above, this option doesn't work for me and I already opened an issue for that.

**Comment by greyson-signal** [comment]
Thanks, got it! Cody built this and is currently on vacation, he'll take a look when he gets back.

**Comment by spagy** [comment]
hi, i think i'm running into the same issue.

with both phones in transfer mode, they don't find each other. i have followed all troubleshooting steps outlines in the support page.

eventually, i get an error modal on the old device with the title 'Error Connecting', and one of the options is to submit a debug log. here is such a debug log: https://debuglogs.org/android/5.49.3/5dc64cec23755d2fc64d40ded51ddc255f2bfb6fc46409c393ee9f26476889af

**Comment by cody-signal** [comment]
@spagy looking through the logs the WiFi direct connection just can't be establish. Please double check you've removed any known groups from the WiFi DIrect settings on your device and make sure your OS is fully up to date on both devices.

**Comment by spagy** [comment]
hi @cody-signal thanks for your reply, i don't have the set up to test this at the moment but i'll give it another go when i have. that said i'm almost certain that i had removed all known groups from wifi direct settings on both devices.

i'm not sure how up to date the devices were, but i'll make sure they're as up to date as possible when i next test.

**Comment by cody-signal** [comment]
That's a bummer. Sadly WiFi Direct is rough on Android when both devices are Android. It seems that something is fundamental broken here that's outside our control.

**Comment by spagy** [comment]
that's annoying. thanks for having a look at this!

**Comment by spagy** [comment]
that's annoying, thanks for looking into this though!
