### ISSUE TITLE
Problem to send an SMS to yourself (Note to self)

### ISSUE THREAD

**Issue by TBDwarf** [signalapp/Signal-Android#12428]
### Bug description
I have a problem to send myself an SMS when signal is the default application for receiving them.
I use an API of my phone operator (Free Mobile, France) which allows via the entry of a URL to send me an SMS (home automation use, NAS alarm etc.)

Example : 
https://smsapi.free-mobile.fr/sendmsg?user= user code &pass= password &msg= message

For some time this function did not seem to work anymore and it turns out that if I change the default application for receiving SMS (by any one), then I can again receive SMS from this API ...

The problem only exists with the SMS application of Signal, I think the problem is in the "note to self" function, after some research on the internet I found other people in my situation.

### Steps to reproduce
- send an SMS to your own number from your own number without using the signal application

### Device info
**Device:** Google Pixel 5
**Android version:** 13
**Signal version:** 5.48.3

### Link to debug log
In the debug log I can see a line: 
SmsReceiveJob : Received an SMS from ourselves! Ignoring.

**Comment by Sgn-32** [comment]
Dropping of own SMS was introduced with 5.34.7. https://github.com/signalapp/Signal-Android/commit/c7a345eb0bb56026ad07fa7d66e872650b1521e6
This was made because of SPAM/FAKE attacks with own number.

**Comment by TBDwarf** [comment]
It seems that this security implementation poses a problem to several people (reddit, Jeedom forum, user of the service of the telephone operator "Free Mobile" which counts 13.32 million customers etc.). 

I am not a specialist of this type of attack but I do not think that users often receive fake sms from their own number, especially if it appears in the note to self section.

Isn't it possible to add a bypass function to this security? Then the user is free to activate it or not?

**Comment by PHCEAC** [comment]
I confirm that this is a big problem for me. Suggest reversion, or opt-in, for this feature.

SMS APIs like the "Free Mobile" are perfect for remote monitoring.

The ignore feature seems to break the SMS system, as it is apparently entirely permissible to send SMS to one's own telephone number. This is a common method for non-Signal users to maintain lists of notes on their telephone - the "Note to self" title of the Signal app parallels this.

The use of own number as source of mobile account related messages from one's carrier is also not uncommon.  

If there is no metadata associated with SMS messages which would indicate that the origin has been spoofed, then Signal app should simply emphasise that all received SMS are "Insecure/unsecured", whatever the apparent origin. The current UI is fairly clear to me, but maybe the little "open padlock" could just be bigger.
