### ISSUE TITLE
Impossible to retrieve SMS code to change number

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#12429]
If you get a new SIM and try to change your phone number in Signal it will cause a code to be texted to your phone. There is no way to read the text message to get the code without dismissing the screen where you enter the confirmation code.

**Comment by Sgn-32** [comment]
There was a commit https://github.com/signalapp/Signal-Android/commit/c6c30f25a2bc197f5638becdc2e9d152105b9496 `Attempt automated SMS verification in change number flow. ` with 5.48.0.
The SMS verification code should be insert automatically.
Maybe post a debug log?

**Comment by alex-signal** [comment]
A debug log would be appreciated, though I'm surprised that you don't get a notification in your shade containing the code.

**Comment by jbaker6953** [comment]
When I tried it again the code was automatically populated.

The contents of messages have not appeared in my shade since a couple of versions ago. How do you enable them again?

**Comment by jbaker6953** [comment]
Nevermind. I found the settings. I suppose we can close this until I can replicate, although I'm loathe to keep switching my number back and forth.
