### ISSUE TITLE
Screen timeout cancels transfer / backup

### ISSUE THREAD

**Issue by AbandonedCart** [signalapp/Signal-Android#12423]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Transfer (and possibly manually initiated backup) fail when the device goes to sleep. Backup was absurdly slow, so I stopped it before I could test further.

### Steps to reproduce
- Open Signal
- Setup and start a transfer
- Allow device screen to time out
- Wake screen
- Read the failed message

**Actual result:** Cursing because you were an hour into a transfer and have to start over. Requesting a refund on donations. It really depends on how utterly infuriated you are that the already slow transfer didn't consider screen timeout.
**Expected result:** Someone had thought to include `FLAG_KEEP_SCREEN_ON` or `setKeepScreenOn` to prevent this, even if it were optional similarly to Samsung's Smart Switch having a "Keep Screen On" button and a transfer completes without sitting next to your device tapping the screen every few minutes or disabling the timeout entirely.

### Screenshots
N/A

### Device info
**Device:** Samsung, at least
**Android version:** Irrelevant
**Signal version:** 5.47.1

### Link to debug log
It's an oversight that likely happened from an untested situation. I had to send the device in for service and lost my chat history, along with any logs or ability to collect them. See "Expected result" for solutions.

**Comment by AbandonedCart** [comment]
Could be related to one or more of the size-based issue reports, but they all seem to infer the likelihood that the size of the transfer overloads the process, not that timeout terminates the connection.

**Comment by cody-signal** [comment]
I've tested this and have been unable to repro with the partial lock. The screen goes off and things continue to work just fine. Even if we do a full lock to keep the screen on, and someone presses that power button, that'll release the lock which is worse.

If this is something you can reproduce, then a debuglog would be helpful. I did a device transfer the other week of my multi-gb personal install to a new device and was able to just leave the phones alone and come back to it later just fine. There seems to be something specific to certain OS/vendors that act a bit differently when the screen goes off.

**Comment by AbandonedCart** [comment]
It will take some time to get enough messages together to recreate the years I lost and log the failure. In the meantime, a quick and easy solution is attached:

```
var isEnabled = false
findViewById<Button>(R.id.screen_toggle).setOnClickListener {
    isEnabled = !isEnabled
    it.keepScreenOn = isEnabled
    it.text = if (isEnabled) "Some text for disabling" else "Some text for enabling"
}
```

No services, no wake locks, no additional management. It's basically just a button that can keep the screen on.

**Comment by AbandonedCart** [comment]
I forgot this was still Java, so here is that same solution again:

```
AtomicBoolean isEnabled = new AtomicBoolean(false);
((Button) findViewById(R.id.screen_toggle)).setOnClickListener(view -> {
    boolean isButtonEnabled = !isEnabled.get();
    ((Button) view).setKeepScreenOn (isButtonEnabled);
    ((Button) view).setText(isButtonEnabled ? "Some text for disabling" : "Some text for enabling");
    isEnabled.set(isButtonEnabled);
});
```

Keep in mind the premise is being a self-contained example, so variables have been minimized and assumed local.

**Comment by AbandonedCart** [comment]
Honestly, I already explained what devices were likely to blame and why I don't have a log. I lost years of messages and that's not something I can throw together. I guess that's what I get for not testing the backup before it was too late. Thanks for responding.

**Comment by djoris** [comment]
I imagine why @AbandonedCart closed this (in frustration) but want to add to this. This issue might be rare but very scary. Edit: I have now had this issue four times.

The old phone stays on "Transferring data..." with a percentage showing, and probably acknowledges the transfer is interrupted but will be signed out from my account.
The new phone was stuck on a certain number of messages, then twice happily switched to the screen: "Set up your profile" and began receiving messages.
Uninstalling Signal on the new phone to retry brought me in limbo; the old phone would not restart transfer. It gave the "Unable to connect to service" message, likely because it was deregistered.

I worked around this issue by installing KeepOn (F/LOSS) on both devices to force the screen to stay on. This worked for me immediately the fifth attempt. For perspective, I couldn't get past 66900 messages before.
