### ISSUE TITLE
old threads not respecting global time based history limit until a new message is sent to them

### ISSUE THREAD

**Issue by benmayne** [signalapp/Signal-Android#12421]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
(edited based on discussion below)

I have a 30 day message retention set, but groups with messages older than that don't seem to clear their old messages until I send a new one. I haven't found any active threads with old messages still around, but stale ones seem to persist. 

old bug description: 
> Several times now, I've sent a message to an old group (in this case last message in April, 4 months ago). As soon as I send the message, the message history in the group is cleared. 

> This group in question did not have a message retention policy. The messages were originally sent from this phone, so haven't interacted with any backups/restores. I have, however, gone through several desktop clients in this time both removing old ones and setting up new ones. 

**Actual result:** Old messages persist until a new message is sent
**Expected result:** Messages older than my retention window should be automatically deleted

### Screenshots
Before:
![Screenshot_20220827-192835_2](https://user-images.githubusercontent.com/3374110/187055685-89916a0b-6709-44fa-a6ea-0230b36f0507.png)

After:
![Screenshot_20220827-192916_2](https://user-images.githubusercontent.com/3374110/187055695-4442764c-c699-4312-820d-41a2cad99aed.png)

### Device info

**Device:** Pixel 5
**Android version:** 13. August 5 Security Update
**Signal version:** 5.48.2

### Link to debug log

https://debuglogs.org/android/5.48.2/fa4f167ff94ecef8d589666d8404cd752ceff9748defc1a3cc45f98c4b969782

**Comment by alex-signal** [comment]
Hi! Is it possible this is related to message trimming? Are the messages gone permanently or if you back out and re enter the group do they reappear?

**Comment by alex-signal** [comment]
It seems to me that the issue is that they were not cleared out back 3 months ago. I'm not exactly sure *what* triggers the trim for a given thread. I'm tracking this issue internally though, so we'll get it sorted.

**Comment by benmayne** [comment]
sounds good. Want me to update the original bug report to indicate this?

**Comment by alex-signal** [comment]
@benmayne If you don't mind, for accuracy's sake.

**Comment by benmayne** [comment]
tested a few more versions of it: 

same behavior for groups and direct messages. It also clears the message history when I send a new message from my desktop client, not just actions initiated from android. Sending a sms with signal clears the relevant thread too even when the rest of the thread is signal messages. 

https://debuglogs.org/android/5.48.3/24ee2cfb63edeb2c780d95087e44e27927486d5e6d0c09adadf890cdadc5ef1c
