### ISSUE TITLE
Unable to unlock Signal with an alphanumerical password

### ISSUE THREAD

**Issue by Sirusdark** [signalapp/Signal-Android#12430]
- [X ] I have searched open and closed issues for duplicates:
It is not the same as: https://github.com/signalapp/Signal-Android/issues/9650
It is not the same as: https://github.com/signalapp/Signal-Android/issues/9862
The spam/funny posts about "backdoors" are kinda related though as only Fingerprint works haha
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to unlock Signal version 5.48.3 on Android 8.0.0 with an alphanumerical passwords.

### Steps to reproduce
- Close Signal and/or Lock it.
- Open Signal.
- Touch "Tap to Unlock"
- Touch "Use Password" instead of using a fingerprint (if enabled).

**Actual result:** Signal opens the phone's numpad keypad instead of the keyboard. See Screenshots below.
**Expected result:** Signal shows a keyboard.

### Screenshots
![signal_unlock_step0](https://user-images.githubusercontent.com/6478223/187966797-403e51f3-3fa8-423d-a740-e449dab5ec3c.png)
![signal_unlock_step1](https://user-images.githubusercontent.com/6478223/187966798-b2b6de11-5a80-4752-add1-028c2ed5bc5f.png)
![signal_unlock_step2](https://user-images.githubusercontent.com/6478223/187966801-f9687acf-46d6-483f-ae05-89ff0a74a59f.png)

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 5.48.3

**Comment by Sgn-32** [comment]
I don't find the string "Use a fingerprint or enter the current PIN" in the [strings.xml.](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/res/values/strings.xml). So an Android OS issue?
Maybe post a debug log?

**Comment by Sirusdark** [comment]
Sure, I wouldn't mind sending it privately. Do I have your permission to send it to you? (I have your contact info) Thanks!

**Comment by Sirusdark** [comment]
> I don't find the string "Use a fingerprint or enter the current PIN" in the [strings.xml.](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/res/values/strings.xml). So an Android OS issue? Maybe post a debug log?

Sure, I wouldn't mind sending it privately. Do I have your permission to send it to you? (I have your contact info) Thanks!

**Comment by Sgn-32** [comment]
You can send it to me. I will check.

**Comment by Sgn-32** [comment]
I've tested it with Android security screen lock:
a) "password" and "fingerprint"
b) "PIN" and "fingerprint"

Both working normal.
![Screenshot_1662068558](https://user-images.githubusercontent.com/49990901/188019430-4f6b7558-6496-4c67-9d15-b8b127a0de52.png) ![Screenshot_1662068569](https://user-images.githubusercontent.com/49990901/188019434-ea1bacce-ef06-4625-88aa-2c622d7c54d8.png)


![Screenshot_1662069221](https://user-images.githubusercontent.com/49990901/188019811-e956acb3-4258-497c-b4fa-66520fd16ff3.png) ![Screenshot_1662069225](https://user-images.githubusercontent.com/49990901/188019815-46e39990-924b-4ae3-82f9-4097526e4e3b.png)

**Comment by Sirusdark** [comment]
I sent the log via e-mail. Thanks for the clear screenshot, I can see the issue: on a Samsung Galaxy 7, the screen menu buttons are not available as this model uses hardware button, thus no keyboard icon/button is available to switch between numpad and keyboard input.
