### ISSUE TITLE
Front Camera Is Dark

### ISSUE THREAD

**Issue by samsunga50** [signalapp/Signal-Android#12437]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When taking a picture using signal with the front camera, the image becomes really dark. With back camera it works. The front camera works well on Camera App and other camera apps, so it is not a hardware issue.

### Steps to reproduce
- Open signal
-Go on a chat
-Click the camera icon on bottom right
-Use front camera

**Actual result:** Dark Image Despite Lighting being good
**Expected result:** Good Image

### Device info

**Device:** Samsung A22 4G
**Android version:** 12
**Signal version:** 5.48.3

### Link to debug log
 problem with com.samsung.adaptivebrightnessgo API Level 2

**Comment by cody-signal** [comment]
Can you provide a debuglog please?

**Comment by arncor** [comment]
I got the same issue here with both front and back camera.

Signal 5.50.4
Ulefone armor6E
Android 9
