### ISSUE TITLE
Messages displayed on lock screen after "Lock Screen -> Hide Content"

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#12432]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal messages are displayed on the lock screen when Settings -> Notifications -> Messages -> Customize -> Lock Screen is set to "Hide content."

### Steps to reproduce
- Set Settings -> Notifications -> Messages -> Customize -> Lock Screen to "Hide content."
- Set Settings -> Notifications -> Show to "Name and message"
- Receive message
- Check lock screen
- 
**Actual result:**
Name and message are displayed on the lock screen.

**Expected result:**
Message content NOT displayed on lock screen

### Device info

**Device:**
Samsung Galaxy S22 Ultra

**Android version:**
Android 12

**Signal version:**
Signal 5.48.3

**Comment by jbaker6953** [comment]
After toggling "Hide content" to "Show content" and back it now works as expected. I cannot reproduce the combination that causes my issue.

**Comment by jbaker6953** [comment]
It's happening again. I was fooled during testing because Signal is hiding messages on the lock screen that come from non-Signal users. Messages from other Signal users are not hidden on the lock screen.

**Comment by jbaker6953** [comment]
Sorry for the spam. It turns out to be due to the default custom notifications settings. If you set up custom sounds for a conversation it defaults to displaying content on the lock screen instead of honoring the global option to hide it. Seems like a bug, but maybe feature request?

Intuitively it seems like enabling custom notification options for a conversation should copy the global notification settings as a default so the user won't be making changes they didn't explicitly change.

**Comment by nicholas-signal** [comment]
> Sorry for the spam. It turns out to be due to the default custom notifications settings. If you set up custom sounds for a conversation it defaults to displaying content on the lock screen instead of honoring the global option to hide it. Seems like a bug, but maybe feature request?
> 
> Intuitively it seems like enabling custom notification options for a conversation should copy the global notification settings as a default so the user won't be making changes they didn't explicitly change.

Unfortunately those defaults are controlled by your phone manufacturer, not us application developers.

**Comment by jbaker6953** [comment]
Interesting. I was not aware you could control the phone's default settings from the Signal preference menu.

**Comment by nicholas-signal** [comment]
> Interesting. I was not aware you could control the phone's default settings from the Signal preference menu.

Yes: the system provides us the ability to link out to the phone's settings app, which [we do for this specific "Customize" menu item](https://github.com/signalapp/Signal-Android/blob/fb0aa55cbb44f03cc1834bda4d75957b77e28716/app/src/main/java/org/thoughtcrime/securesms/notifications/NotificationChannels.java#L131-L148).
