### ISSUE TITLE
Data leak: Unselected contact details are still sent

### ISSUE THREAD

**Issue by darkdragon-001** [signalapp/Signal-Android#12446]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing a contact, a menu with all available contact details appears. In this menu one can (de-)select certain properties in order to (not) include it in the sent contact. No matter what is (de-)selected there, everything it sent to the other use!

### Steps to reproduce
- Open a chat
- Tap "+" button
- Select "Contact"
- Choose a contact
- Deselect certain properties
- Check on the recipient's phone which contact details are received

**Actual result:** All contact details are transferred regardless of the selection made
**Expected result:** Only selected contact details are transferred.

### Device info
**Device:** Xiaomi Mi A1
**Android version:** 9
**Signal version:** 5.49.1

Tested messaging with a contact using Fairphone 3+ in both directions.

**Comment by greyson-signal** [comment]
Thanks for the report! This will be fixed in the upcoming 5.50 release.
