### ISSUE TITLE
Texto groups : can't edit membership and can't even delete the group

### ISSUE THREAD

**Issue by bugith** [signalapp/Signal-Android#12445]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using Signal as my default messaging application, I have many groups for the same purpose, e.g. friends that use Signal and others that don't. When a new one comes that doesn't use Signal, I can't add them to the texto group, I can't delete the group, have to recreate a new group from scratch, and when one switches to Signal, I can't remove them out of the texto group

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** SM-N7505
**Android version:** 5.1.1
**Signal version:** 5.48.3 (-FOSS)

**Comment by Sgn-32** [comment]
From the support pages:

https://support.signal.org/hc/en-us/articles/360007319331-Group-chats


    Insecure MMS group

    Communication is insecure
    Message are sent through your cellular provider
    Costs and fees are determined by your mobile plan
    Start a new group with a maximum of 10 members
    Group members can not be changed after creating
    A group name or photo is displayed on your device nly.
    Shows Unsecured MMS in the chat
    The send icon will be gray with an open lock  after you type a message
    Each message bubble will show an unlock icon

**Comment by bugith** [comment]
The worse is we can't deleted it, so it will remain polluting forever in the data
