### ISSUE TITLE
Direct share doesn't work

### ISSUE THREAD

**Issue by xIUPITERx** [signalapp/Signal-Android#12449]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't show in the direct share section of my samsung share menu.

### Device info

**Device:** Samsung Galaxy A52s 5G
**Android version:** 12.0.0
**Signal version:** 5.49.1

**Comment by xIUPITERx** [comment]
Any help?

**Comment by cody-signal** [comment]
Hi there. We can't reproduce this issue. We use direct share all the time without a problem. 

Is this all share sheets or something specific?

**Comment by xIUPITERx** [comment]
If Direct Share works, signal contacts should also appear in the red area, right?
![signal-2022-10-03-161051_002](https://user-images.githubusercontent.com/97352673/193601102-f232e943-4a22-4c26-8643-5822d862402a.png)
But only Whatsapp contacts appear for me, even if siganl is unlocked.

**Comment by greyson-signal** [comment]
Signal can provide suggestions of contacts to put there, but the system is ultimately the one that decides which show up based on their own internal rules. Do you use whatsapp more often than signal? In that case, it could just be preferring the app you use more.

**Comment by xIUPITERx** [comment]
I use signal as my main messenger and even if this were not the case, Signal should still appear in Good Lock.

**Comment by xIUPITERx** [comment]
Any news?

**Comment by alex-signal** [comment]
Hi! Unfortunately direct share is a bit of a black box for us. If you long press the Signal icon on your homescreen, does it pop up with some quick access contacts? If so, then at the very least we are publishing shortcuts.

**Comment by xIUPITERx** [comment]
No there are no quick access contacts.

**Comment by xIUPITERx** [comment]
I also checked it on other phones (Google Pixel 6, Xiaomi Mi 8), same problem there.

**Comment by xIUPITERx** [comment]
it looks like the screen lock feature breaks direct share.

**Comment by cody-signal** [comment]
Yes, in order to respect the intent of screen lock, we can't share information with the OS that we can't remove easily. Things like the share sheet are driven by shortcut info provided to the OS which includes names and avatars and are not something we can remove when Signal is locked.
