### ISSUE TITLE
Unable to share to SMS contacts from another app

### ISSUE THREAD

**Issue by odama626** [signalapp/Signal-Android#12448]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sharing from another app to signal when SMS is enabled does not show sms contacts as options

### Steps to reproduce
- use signal for sms
- share image from photos to signal app

**Actual result:** recent SMS conversations are filtered out and not included in the list of recent chats
**Expected result:** SMS conversations should be included and sorted in the correct order based on last message time with chat messages -- maybe have an unlock icon on the image to show that some are sms

### Device info

**Device:** pixel 6 p
**Android version:** 13
**Signal version:** 5.48.3

### Link to debug log

https://debuglogs.org/android/5.48.3/a018c0c4d7e88d91eee9ef30c568e2d3e0eb7a654db94077ef6d90d31f24bb59

It looks like something was fixed in the past 6 months or so that would probably be in the same section of the code base and this could be a regression of that change https://github.com/signalapp/Signal-Android/issues/12115

**Comment by greyson-signal** [comment]
Given we're removing SMS from the app, I'm gonna close this. Thanks!
