### ISSUE TITLE
Playing own audiomessages always shows "Not to myself" in the upper part.

### ISSUE THREAD

**Issue by DexterNemrod** [signalapp/Signal-Android#12441]
When I play audiomessages it always says "Notiz an mich" (german for "note to myself") even in chat with other people.

Steps to reproduce:
- record/send audiomessage
- play the message

System-Details:
- 5.49.1 (via playstore)
- Mi 10T pro 5G (M2007J2SG)
- Android 12 (LineageOS 19-20220903-NIGHTLY-apollon) also happened with previous LOS 19 versions)

![session-attachment-2022-09-08-074221](https://user-images.githubusercontent.com/98281166/189049581-504359df-97f2-4763-9e73-147b7d268f30.jpeg)
![session-attachment-2022-09-08-074222](https://user-images.githubusercontent.com/98281166/189049582-5972b9df-e2e2-42d1-95e6-27cfbec6c818.jpeg)

**Comment by EtzBetz** [comment]
Can confirm this on my Pixel 6 on the same version, Android 13.

I would actually like to contribute a fix, but I'm new to this codebase and while experienced with android stuff, never did much android programming stuff besides some small stuff for myself.

I'd guess that the issue here is that the `note_to_self` string is used instead of the own user name?
Someone more experienced may wants to give me a pointer?

**Comment by Sgn-32** [comment]
@EtzBetz 

XML view file:
https://github.com/signalapp/Signal-Android/blob/8f63b850fc30998a8119e0725d8c474d3eb17c5b/app/src/main/res/layout/voice_note_player_view.xml#L22

VoiceNotePlayerView.kt text variable:
https://github.com/signalapp/Signal-Android/blob/8f63b850fc30998a8119e0725d8c474d3eb17c5b/app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNotePlayerView.kt#L37

Setting the state of a voicenote:
https://github.com/signalapp/Signal-Android/blob/8f63b850fc30998a8119e0725d8c474d3eb17c5b/app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteMediaController.java#L88

Getting the title of voice note:
https://github.com/signalapp/Signal-Android/blob/8f63b850fc30998a8119e0725d8c474d3eb17c5b/app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteMediaItemFactory.java#L178

**Comment by Sgn-32** [comment]
Fixed in 5.50.0
Only show "Note To Self" as Voice Memo author if both sender and receiver are self. https://github.com/signalapp/Signal-Android/commit/aa268fc3ba9e6e0a97b24e8cfc3f3c970e9c1bab
