### ISSUE TITLE
Camera lag when taking photos

### ISSUE THREAD

**Issue by EVOTk** [signalapp/Signal-Android#12457]
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Camera lag when taking photos

### Steps to reproduce
Take picture from inside signal app

**Actual result:** the camera lags, and it's blurry
**Expected result:** camera not lags

### Screenshots
Signal App :
https://user-images.githubusercontent.com/45015615/190850068-c8589ea8-047d-4883-96eb-f39301a419e8.mp4

Original Camera App : 
https://user-images.githubusercontent.com/45015615/190850104-271046af-7601-4d9d-a0cc-a62895c07dcc.mp4

### Device info

**Device:** Honor 20
**Android version:** 10
**Signal version:** 5.50.1

### Link to debug log
https://debuglogs.org/android/5.50.1/d3bef4b0cee6357dbfda92274320a5420324e58146d18ca01a04ae2f4cda0158

**Comment by kissdani99** [comment]
Same problem when using the rear camera.
Front camera works as intended,

Device: P30 Pro.
OS version: EMUI 12.0.0
Signal version: 5.49.3

**Comment by LastePurustaja** [comment]
I have the same issue only its even worse when i select multiple images/videos and try to unselect random one it crashes the whole app
OS EMUI 12.0.0
App version 5.50.4

**Comment by greyson-signal** [comment]
Please let me know if this gets better on 5.51

**Comment by LastePurustaja** [comment]
> Please let me know if this gets better on 5.51

Yeah will do

**Comment by jogizy** [comment]
Same issue. Idk why! Everything was OK before an update?

**Comment by LastePurustaja** [comment]
Update 5.52.5 now its fixed
