### ISSUE TITLE
Even after refreshing, new contacts don't show up.

### ISSUE THREAD

**Issue by chisbroad** [signalapp/Signal-Android#12455]
Bug description

Once you click the pencil icon in the bottom right and refresh the contact list, it should show new contacts who have also installed Signal or its fork but it doesn't happen with me.

I have already given it the permission for contacts, microphone, camera, and phone.

Seems like it is more of a server-side problem because I tried with Signal and its available forks like Molly and Langis.

Also, thank you so much for everything you all are doing. I really appreciate it.

Android 12 (S1SR32.38-124-3)
Device

Moto G52
Link to debug log

https://debuglogs.org/android/5.48.3/84422aa1fe12dd48a7003cbb590d293f8dcbba76c4f142793fa334d784d458ac

**Comment by greyson-signal** [comment]
Hmm, I'm seeing successful directory syncs in your logs. Are you able to provide logs from an official version of Signal?

**Comment by chisbroad** [comment]
Never mind, I figured out the problem.

Due to privacy concerns, I am not using Google's phone nor contacts app but Simple Dialer and Contacts app. And saving the numbers here in phone makes it impossible for other applications to find it as Android 12 forbids that.

**Comment by ahrenswett** [comment]
CLOSE
