### ISSUE TITLE
Videos selected for posting do not open in preview screen

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#12452]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Videos selected to send on Huawei and Oppo devices have a black screen, sometimes they open and freeze on trim screens and then crash. Even if the application is killed, it remains on the white screen as seen in the video.

### Steps to reproduce
- Select gallery from the attachment menu at the bottom
- Any 2-3 video files are selected. 2-3 videos can be selected along with the photo.
- Sometimes the trim screen may freeze and crash without opening, sometimes the trim screen will open and freeze and crash
- Even if the application is killed, it remains on the white screen as seen in the video.

**Actual result:** Videos causing crashes
**Expected result:** Videos should not freeze

### Screenshots

https://user-images.githubusercontent.com/31124402/190348609-8f688789-b351-494b-b8f6-2a18b6cdad64.mp4

https://user-images.githubusercontent.com/31124402/190348106-78755fbe-06d8-4cf4-8359-bc9a6ed8e28e.mp4

### Device info

**Device:** Huawei Mate20 Pro, Oppo Reno Z, General Mobile GM 8
**Android version:** 10.0, 9.0
**Signal version:** 5.49.2

### Error log
`E/ACodec: [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
2022-09-14 10:07:45.212 28526-28798/? E/LogX: {AsyncTask #1}[VideoThumbnailsExtractor -> extractThumbnails(VideoThumbnailsExtractor$Callback arg3)] Exception! message:java.lang.InterruptedException`

### Link to debug log
https://debuglogs.org/android/5.49.2/a4f030af7faf4e1706b1254b313f391d62a5d2f64d3533cbe07352a6fdf089f6

**Comment by gelbertgel** [comment]
I have added. Please fix this issue

**Comment by greyson-signal** [comment]
Are you able to provide a link to the full log?

**Comment by gelbertgel** [comment]
I have added log and new video

**Comment by alex-signal** [comment]
Could you provide video file information? (File type, etc)

Not the video itself, just the info. How was the video recorded? I tried with a couple videos on a Huawei device and could not immediately reproduce.

**Comment by gelbertgel** [comment]
The videos were shot directly from the device camera. in mp4 format. It happens in the video file I take from every camera. It happens for some of the other video files and not for others.

**Comment by gelbertgel** [comment]
Hi, do you think any solution to this error? I would be very happy if you solve it. Thanks in advance

**Comment by gelbertgel** [comment]
Hey, my issue is not resolved but closed.
