### ISSUE TITLE
Unable to reply to non-signal messages

### ISSUE THREAD

**Issue by Viss** [signalapp/Signal-Android#12454]
- [ ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If someone who does not have their primary messenger set to signal begins a conversation in signal, then moves to unencrypted texts, still using the same phone number, any replies you send to them are sent via signal, and since they are using regular sms, those messages never reach them. There should be a way to 'switch back to regular sms' for a conversation.

### Steps to reproduce
- start with two mobile devices: One that uses signal as the default messenger app and another that does not.
- using the device where signal is not the default messenger, send a signal message to the other device
- an encrypted signal session is established
- the first device stops using signal, and moves to regular sms
- the second device recieves those sms messages, and shows a little unlocked padlock icon indicating the messages are unencrypted
- all replies to that thread from the second device are sent encrypted, to the signal account, and not "as a reply to the unencrypted messages"
- there is no way to convert the conversation "back to regular sms from an encrypted signal conversation"
- the conversation is now one-sided and orphaned, with no way to recover other than to delete the entire chat history and start from scratch

**Expected result:** it would be super handy to have an option to reply with regular text messages versus signal messages, in the event that a signal user stops being a signal user, or stop using signal for a brief period of time.

### Device info
Signal for android - all versions, this is not a new development, this is just how signal currently works

**Comment by greyson-signal** [comment]
Long press the send button to switch to SMS.

**Comment by Viss** [comment]
oh excellent - thanks! I had no idea this functionality even existed!
