### ISSUE TITLE
Nothing happens after re-registering device

### ISSUE THREAD

**Issue by Wowol** [signalapp/Signal-Android#12456]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After re-registering number on phone, there is no outcome - no exception, just nothing happens. Signal still tells me that I need to re-register. On the other hand - second device is unregistered.

### Steps to reproduce
- Register device on another phone with the same number
- Try to re-register on previous phone with the same number

**Actual result:** Nothing happens, device is still not registered.
**Expected result:** Device is registered and I can use signal.

### Device info
Device: Xiaomi Redmi Note 8 Pro
Android version: 10
Signal version: 5.49.3

### Link to debug log
I can't open settings, as explained in  #12453.

@greyson-signal - u might be interested.

**Comment by greyson-signal** [comment]
Hi there, can you access the debuglog screen if network is disabled? If so, you can save the log zip locally via the three-dot menu in the top right of the log viewer.

**Comment by Wowol** [comment]
Hi, unfortunately I get the same error with network disabled.

**Comment by Wowol** [comment]
Hi,
1. No - in fact, my goal is to move the data from old phone (either by backup or directly sending data to new phone).
2. Yes - registration on new device is working.

**Comment by alex-signal** [comment]
There are lots of things that could technically have happened, but we unfortunately can't tell for sure without a debug log. Did you wipe the app between when you initially tried to register and when you were finally able to register (wipe as in, delete data or reinstall)

If not, you may still be able to generate a debug log with some useful information now that you're registered.
