### ISSUE TITLE
InApp Camera and Flashlight not working

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#12467]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal InApp Camera (Front and Back) and the Flashlight are not working since Signal Update 5.44.5
Worked well in the past.

### Steps to reproduce
- InApp Camera not working (doesn' t take any picture)
- Screen remains black, no picture shown
- closing App and open again or restarting device same Issue

**Actual result:** remains black screen, showing no foto
**Expected result:** showing taken foto ready for editing and sending

### Device info

**Device:** Samsung Tablet SM-T805
**Android version:** 6.0
**Signal version:** 5.49.4

### Link to debug log
https://debuglogs.org/android/5.49.4/d236bb4be99288abdba4a1741994684979c1b9f0348912497ff50f3b9bcb2a37

**Comment by alex-signal** [comment]
Please include a debug log :) Is this a 4G tablet? We don't currently support large form-factors (though to be honest there's no reason your camera shouldn't be working)

**Comment by delete-77** [comment]
Hi alex-signal, i have included the debug log now and yes you're right, it's a 4G tablet with wifi.
The camera with the official camera app and other apps is working.

**Comment by alex-signal** [comment]
Thanks!
