### ISSUE TITLE
Signal sends notifications of my own messages when sent from notification or google auto

### ISSUE THREAD

**Issue by micw** [signalapp/Signal-Android#12466]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I answer a message within the notification popup, I get a notification a few seconds later, containing my own answer.

When I answer a message via google auto, I get a notification a few seconds later, containing my own answer (I guess i't related and i guess google auto uses the "notification direct answer" function for this feature).

### Steps to reproduce
- receive a message on android, with notifications enabled
- on the notification, use the "answer" button to answer "inline" within the notification

**Actual result:** The message is sent. After a few seconds, my own message is notified as incoming/new message.
**Expected result:** The message should be send but not notified back to myself.

### Device info

**Device:** OnePlus 6
**Android version:** 11
**Signal version:** 5.49.4

**Comment by alex-signal** [comment]
Hi! Could you please add a debug log? We recently did some work around the replies functionality with Android Auto in this area.

**Comment by micw** [comment]
Hello,
thank you for the fast response. Honestly, it's a few weeks ago that I used this functionality because of this bug. So the Signal version I reported may not be the correct one if there was a recent update. I did a test with Android Auto today and did not receive my own messages anymore. I will do another test with normal notification reply (without android auto) as soon as I receive another message.

I will come back with new test results and will close the issue if it's already solved.

**Comment by alex-signal** [comment]
Thanks! Could you please add a debug log? I'll ensure we're tracking this and have someone take a look

**Comment by micw** [comment]
Sure. How can I do this?

**Comment by micw** [comment]
Will the debug log contain info from start of the app/phone or a certain time range? (because i did the tests yesterday and rebootet the phone meanwhile)? Will it contain messages or other personal information?

**Comment by alex-signal** [comment]
We scrub out personal information. Debug logs generally contain the last few days worth of data, depending on how much you use the app. I think they cap out around 7 days unless we explicitly mark log lines as "long term" which last 21 days. These are of course used sparingly.

**Comment by micw** [comment]
A debug log, taken shortly after the issue (received notification of the message I answered to) happened.
https://debuglogs.org/android/5.49.4/df9034229dd7af2d70fa4090ea942f2f178c1292e0f57e65962b43d574ec1bcd

**Comment by greyson-signal** [comment]
Reading through this, I think this is just how google handles inline notification replies, which is how google auto replies are handled. I don't think there's much for us to do here, sorry!

**Comment by micw** [comment]
Are you sure about this or is this just a guess? Would it make sense to gather more information (e.g. verify if _other_ apps behave the same) rather than just closing the issue? Let me know what tests/infos you need to track it down or ensure that this is really not solvable.

Kind regards,
Michael.

**Comment by micw** [comment]
Update: I just got a brief test:

## Signal
* sent a message "Test" from other phone to my phone
* got a notification on my mi band "Test"
* Answered inline with "Ok" from my phone
* got a notification on my mi band "Test" (from myself)

## Telegram:
* sent a message "Test" from other phone to my phone
* got a notification on my mi band "Test"
* Answered inline with "Ok" from my phone
* got no notification, as it should be
