### ISSUE TITLE
Why can't I add friends or send signal messages when using proxy in Signal? I can only send SMS

### ISSUE THREAD

**Issue by 337077418** [signalapp/Signal-Android#12461]
Why use Samsung mobile phone? You can't add friends or send signal messages with proxy in Signal. You can only send SMS messages

In addition, Huawei mobile phones cannot use this function, and the connection failure is always prompted

**Comment by greyson-signal** [comment]
Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.

Regardless, can you provide a log?

**Comment by 337077418** [comment]
https://debuglogs.org/android/5.50.1/cb204986a241f2996fb4b5e64472bdce5c01fce6f6f12864c95691ada19c4ba5

**Comment by 337077418** [comment]
> https://debuglogs.org/android/5.50.1/cb204986a241f2996fb4b5e64472bdce5c01fce6f6f12864c95691ada19c4ba5

tts.soft167.com

**Comment by 337077418** [comment]
> 你能详细说明吗？我们在应用程序中有一个代理功能（设置 > 数据和存储 > 代理）。你指的是那个吗？它对我来说很好。
> 
> 无论如何，你能提供一个日志吗？

When I use a Samsung mobile phone and open the agent in signal, I cannot search for other signal members, and it will jump to the interface for sending SMS messages. When I use a Huawei mobile phone, the connection will always fail when I turn on the proxy in signal

**Comment by 337077418** [comment]
> Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.
> 
> Regardless, can you provide a log?

When I use a Samsung mobile phone and open the agent in signal, I cannot search for other signal members, and it will jump to the interface for sending SMS messages. When I use a Huawei mobile phone, the connection will always fail when I turn on the proxy in signal

**Comment by 337077418** [comment]
> > Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.
> > Regardless, can you provide a log?
> 
> When I use a Samsung mobile phone and open the agent in signal, I cannot search for other signal members, and it will jump to the interface for sending SMS messages. When I use a Huawei mobile phone, the connection will always fail when I turn on the proxy in signal

Only when other vpnapps are opened, the proxy function can be used in the signal, and the proxy can be successful. But that's funny, I don't have to go over the wall when I'm already outside the wall

**Comment by 337077418** [comment]
> https://debuglogs.org/android/5.50.1/cb204986a241f2996fb4b5e64472bdce5c01fce6f6f12864c95691ada19c4ba5



> Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.
> 
> Regardless, can you provide a log?

**Comment by 337077418** [comment]
> Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.
> 
> Regardless, can you provide a log?

https://debuglogs.org/android/5.50.1-nightly-untagged-2022-09-22-14/f3e2d174fb3b5f2519af90b7ed92970c756bbf1ff4871870f18c3c33d4459679

**Comment by 337077418** [comment]
> > Can you elaborate? We have a proxy feature inside the app (Settings > Data and Storage > Proxy). Are you referring to that? It's working fine for me.
> > Regardless, can you provide a log?
> 
> https://debuglogs.org/android/5.50.1-nightly-untagged-2022-09-22-14/f3e2d174fb3b5f2519af90b7ed92970c756bbf1ff4871870f18c3c33d4459679

Client A fails to dial client B. After the timeout hangs up, client B will have a missed voice call prompt.

**Comment by 337077418** [comment]
new question

https://user-images.githubusercontent.com/10607980/191678592-8f8d6c9c-20be-4ff9-bd31-99a11b0795b3.mp4

**Comment by 337077418** [comment]
> new question
> 
>  654e9d88e02d8eb05a2e14c6018c834a.mp4

The Samsung mobile phone in the video does not pop up the call interface, nor can it enter the call interface through the status bar

https://debuglogs.org/android/5.50.1-nightly-untagged-2022-09-22-14/e239b5dbda14f757d7b05ceb2714ba2a280d9a967ae37d2e5d60d2748ad91e0f

**Comment by greyson-signal** [comment]
While most things work with the proxy, it looks like our service that tells us if a user is registered _does not_. I'll note that you're not using any official clients. I especially don't know what's running on the Huawei device, has a weird package.

But messaging should work with people you already know are signal users.
