### ISSUE TITLE
Signal unable to differentiate between landline and mobile phone numbers when forwarding messages

### ISSUE THREAD

**Issue by tipporoll** [signalapp/Signal-Android#12465]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When forwarding a message, Signal does not seem to be able to differentiate between landline and mobile phone numbers when searching by name in the contacts list. I get three suggestions in the filtered list for one specific contact, having only one mobile number and two landline numbers, all three in international +46 format. Contact is not on Signal. All three rows in the filtered view include the text "sms", although you can't send text messages to landlines. Issue #12444 seems somewhat related. 

### Steps to reproduce
- longpress message, choose forward
- search by name in search box for a non-signal contact with both mobile and landline numbers
- ponder and guess which of the multiple rows actually correspond to a mobile phone. Forward to all (three) of them to be sure message gets through.. 

**Actual result:**
Signal lists multiple rows, all marked "sms", even though some of these numbers correspond to landlines. 

**Expected result:**
No landline results would come up in the search listing when searching by name. Alternatively, indicate also the corresponding number for each row, enabling me to not forward messages to landlines. 

### Screenshots

![20220921_124431](https://user-images.githubusercontent.com/114067878/191486437-5b2de443-4a50-42f1-b99c-d58762f7286d.jpg)

### Device info

**Device:** Samsung S7
**Android version:** 8.0.0
**Signal version:** 5.49.4

**Comment by greyson-signal** [comment]
Closing this, given we'll be removing SMS support soon.
