### ISSUE TITLE
Use consistent voice message audio encoding to lower storage usage and improve quality

### ISSUE THREAD

**Issue by Totorrr** [signalapp/Signal-Android#12475]
- [X] I have searched open and closed issues for duplicates
- [~] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [~] This isn't a feature request or a discussion topic

----------------------------------------

### Disclaimer
This is neither a new feature request, nor a bug report for something that doesn't work. 

It's kind of in the grey area that we could call "improvement", and it concerns several Signal clients types, so I hope it will be accepted here. 

### Bug description
When sending audio messages (voice mails), the codec-bitrate settings greatly vary depending on the emitting device. 

- Android phone: AAC @ 36 kbps approx.
- Apple iPhone: AAC @ 128kbps approx.
- Signal-Desktop for Linux: MP3 @ 160kbps (!)

### Steps to reproduce
- receive a voice message from each type of device
- with Signal-Desktop, download on your computer each kind of voice message
- run `ffprobe file.ext` on each audio file
- notice the codec-bitrate difference mentioned above

**Actual result:** There are very different bitrates. Some same length audio messages use a lot more storage space than others, and audio quality differs significantly between the different message sources.

**Expected result:** Every device would use the same encoding settings, typically, Opus @ 16kbps or 24 kbps (WhatsApp Android uses 16kbps apparently). This codec allows for pretty good voice and moderate music quality at such low bitrates. It would greatly reduce mobile devices storage usage (and network) when sending & receiving many voice messages. 

MP3 is from the previous century and 160kbps is largely overkill. AAC is not as open/free as Opus and 128kbps is too much for voice. Opus is low latency, versatile (no need to chose between High-Efficiency modes or so, just setup the bitrate), royalty free and CPU usage friendly. 

My phone has like 2.5 GB of audio on Signal storage, mostly received from iPhones, that mean those 2.5 GB could have been reduced to something like 315 MB! (going from 128 to 16 is a division by 8)

**My request: please switch voice message encoding to Opus @ 16 kbps (or between 16 and 24) from every device**

### Device info

**Device:** Sony Xperia
**Android version:** 9
**Signal version:** 5.50.4 (Android), 5.60.0 (Signal-Desktop)

### Related topic

There is a "General discussion" post I found [here](https://community.signalusers.org/t/opus-vorbis-audio-compression/4711) about this but the discussion has drifted away from the 1st post & original topic.  

### See also

 - The bug I created on Signal-iOS: https://github.com/signalapp/Signal-iOS/issues/5440 
 - The Signal-Desktop bug: https://github.com/signalapp/Signal-Desktop/issues/6128

**Comment by alex-signal** [comment]
Please use the community forum for feature requests (or in this case, an improvement) https://community.signalusers.org/

**Comment by Totorrr** [comment]
Hello @alex-signal,I left a message in here: 

- https://community.signalusers.org/t/unify-voice-message-format-maybe-use-opus/20529/9 

I'm a little afraid that it will stay unanswered/unconsidered over there, that is why I also submitted two extremely short PRs that just lower the bitrate. It's an easy first step towards reducing memory/network usage. I hope these will be considered/merged, before 1 year has passed :crossed_fingers: :smiling_face_with_tear:
