### ISSUE TITLE
Format is not removed after pasting

### ISSUE THREAD

**Issue by darkdragon-001** [signalapp/Signal-Android#12478]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When pasting formatted text, the format (e.g. font size) is maintained in the textbox for composing a message. It is only removed after clicking the send button. Preview should be as close as possible to the final result and in turn formatting removed directly when pasting.

### Steps to reproduce
- copy formatted text
- paste formatted text in the message composition textbox

**Actual result:** Format maintained but removed _after_ send
**Expected result:** Format removed directly when pasting

### Device info
**Device:** Xiaomi
**Android version:** 9
**Signal version:** 5.50.2

**Comment by Sgn-32** [comment]
UI: Rich Text Can be Pasted into a Signal Message https://github.com/signalapp/Signal-Android/issues/8058
