### ISSUE TITLE
Front facing camera broken in Google Pixel 2.

### ISSUE THREAD

**Issue by Xxtayce** [signalapp/Signal-Android#12470]
Okay, this has only gotten worse since I +1'd on this bug report https://github.com/signalapp/Signal-Android/issues/12424#issuecomment-1235598361

I can now no longer take any videos OR photos using forward-facing camera. Signal video call is fine. Recording short videos or taking photos only works from the back side of the camera. Audio still works on video, but my phone even tells me the camera is inaccessible.

Super frustrating. Can send logs if you don't already have a bunch.

**Comment by alex-signal** [comment]
This sounds like a separate situation, please add logs.

**Comment by Xxtayce** [comment]
Log of a front-facing video I just tried to record is here:

https://debuglogs.org/android/5.50.2/8a8f4fa3a6b506fe95651d98a1ceaffeaec7fd80e7cc5ef612bf9b6a33a428b7

**Comment by Vggh** [comment]
I have been having issues with front-facing camera on Pixel 3 for the last few versions of Signal which sound similar:

https://github.com/signalapp/Signal-Android/issues/12521

**Comment by cody-signal** [comment]
We tried to reproduce this with out pixel2s running stock and are unable to.

**Comment by cody-signal** [comment]
Please post updated debuglogs and we can re-open.
