### ISSUE TITLE
Unable to change phone number due to "cached" pin?

### ISSUE THREAD

**Issue by Laukage** [signalapp/Signal-Android#12473]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Changing the account Pin in the app doesn't syncronize immediately, i've now tried changing my pin on my signal account multiple times, and it can verify it and all.. but when changing to another phone number it will immediately deny the pin i just changed to..

I might be doing something wrong, but this should be correct according to multiple articles.

### Steps to reproduce
- Change pin under: Account -> Change your pin
- Registration lock disabled.
- Account -> Change phone number
- Verify the new phone number with the verification code
- You will then be asked to provide your pin which is incorrect.

**Actual result:** It denies the pin, even though it is correct - a password manager doesn't lie.
**Expected result:** For it to approve the phone number change.

### Device info

**Device:** Oneplus 9 pro
**Android version:** 12.1
**Signal version:** 5.49.4

**Comment by UserX404** [comment]
Hi!
After you run your steps you should grep a  [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) and add the link to your report. It will help to identify the problem.

**Comment by Laukage** [comment]
> 

What information does the debug log contain?

**Comment by UserX404** [comment]
You can check them by your own before upload but all personal informations are removed.
