### ISSUE TITLE
Missing option pen on reply picture.

### ISSUE THREAD

**Issue by emonfejm** [signalapp/Signal-Android#12472]
Andoid device 
When replying on the picture in a message missing pen to use on picture. if that has any sense.

Where do I enable that option please?

**Comment by alex-signal** [comment]
I'm sorry but I'm not sure what you mean.

**Comment by jchesterdev** [comment]
I think they mean an edit button (pen) where you can modify the photo that was sent to you and then send it back.

**Comment by cody-signal** [comment]
This is a feature request, please see the template you deleted for where to make feature requests. GH issues are for bugs only.
