### ISSUE TITLE
not be possible to remove the proxy address

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#12485]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
not be possible to remove the proxy address
similar issue as in Signal4ios reported by @u32i64 
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-5-55-release/47373/12

### Steps to reproduce
set and save a proxy adress in Signal4Android
delete the proxy adress
the save button is greyed out
leaving and entering the proxy settings again will show the latest saved proxy adress

**Actual result:** not be possible to remove the proxy address
**Expected result:** possible to remove the proxy address

**Signal version:** 5.51.4

**Comment by cody-signal** [comment]
So you want to remove the text for _reasons_? Disabling with the switch is not enough?

**Comment by Sgn-32** [comment]
So that you can deny ever having used a proxy. Currently a proxy address (valid or invalid) remains when disabled the proxy.
When the proxy is turned on again, an attempt is made to connect to the proxy directly. In case of an invalid proxy address, an error message is displayed.

Maybe in the case the proxy adress is invalid and the proxy is getting disabled, then remove the proxy adress.



![signal-2022-09-30-162348_002](https://user-images.githubusercontent.com/49990901/193292352-d299233f-2989-4273-b645-e47b4408c86e.png)


![signal-2022-09-30-162348_003](https://user-images.githubusercontent.com/49990901/193292400-84cc7cfa-8520-4450-b54a-ca251685f372.png)

**Comment by Sgn-32** [comment]
```
  private void onProxyTextChanged(@NonNull String text) {
    if (Util.isEmpty(text)) {
      saveButton.setEnabled(false);
      saveButton.setAlpha(0.5f);
      shareButton.setEnabled(false);
      shareButton.setAlpha(0.5f);
      proxyStatus.setVisibility(View.INVISIBLE);
    } else {
      saveButton.setEnabled(true);
      saveButton.setAlpha(1);
      shareButton.setEnabled(true);
      shareButton.setAlpha(1);

      String trueHost = SignalProxyUtil.convertUserEnteredAddressToHost(proxyText.getText().toString());
      if (SignalStore.proxy().isProxyEnabled() && trueHost.equals(SignalStore.proxy().getProxyHost())) {
        proxyStatus.setVisibility(View.VISIBLE);
      } else {
        proxyStatus.setVisibility(View.INVISIBLE);
      }
    }
  }
}
```

The condition `SignalStore.proxy().isProxyEnabled()` in the if-clause is always true, because the proxy adress is only changeable when the proxy is enabled.
Maybe also change it that the proxy adress is also changeable when proxy is disabled?

**Comment by Sgn-32** [comment]
https://github.com/signalapp/Signal-Android/commit/cdb7f0736827c668ed4d7ce85bece8b3a92dd819
