### ISSUE TITLE
When sending a photo, the android interface overlaps the Signal interface

### ISSUE THREAD

**Issue by EVOTk** [signalapp/Signal-Android#12487]
- [ X] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a photo from phone gallery, the android interface overlaps the Signal interface

### Steps to reproduce
- Use Signal for Send Photo from phone gallery

**Actual result:** When sending a photo, the android interface overlaps the Signal interface - The send button, for example, can only be used on a small part.
**Expected result:** That the Signal interface does not overflow

### Screenshots
![image](https://user-images.githubusercontent.com/45015615/193427245-3f51f6f6-08a6-4de5-b65b-4ac5fede74d2.png)

### Device info

**Device:** Honor 20
**Android version:** 10
**Signal version:** 5.51.5

### Link to debug log

https://debuglogs.org/android/5.51.5/9f28a5dd319f48834e55d33770ac51d805241ba85ceb21c201054f553b7ae2d2

**Comment by UserX404** [comment]
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-51-release/47498/38

Dev mentioned it should be fixed in the next release.

**Comment by EVOTk** [comment]
Oh! Thx for the link
