### ISSUE TITLE
Emoji v14 rendered differently

### ISSUE THREAD

**Issue by TheRisenPhoenix** [signalapp/Signal-Android#12484]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a few days (presumably since the last update), Signal for Android fails to render Emojis from version 14. Previously, their style was consistent to all the older emojis, but recently, they (and **only** v14) appear differently. It seems like they aren't handled by Signal anymore but dispatched to the default OS emoji renderer. This happens in the _chat itself as well as in the input field_.

### Steps to reproduce
- Send some old emojis (for example, "happyface")
- Send v14 emoji (for example, "meltingface")
- Compare both and see the difference in style

**Actual result:** 
New emojis are rendered differently

**Expected result:**
All emojis should share the same visual style (eg. "apple style")

### Screenshots
![grafik](https://user-images.githubusercontent.com/43245438/193087989-85cc8aa3-2a93-40ac-97a1-eba17cec3333.png)

I expect them to look like this: (taken from Signal Desktop, where it still works fine)
![grafik](https://user-images.githubusercontent.com/43245438/193086828-346d6c57-6fb3-40f1-a925-fc129b0b707c.png)

### Device info

**Device:** OnePlus 7 Pro (but also happening with different devices)
**Android version:** 11
**Signal version:** 5.50.4

### Link to debug log
https://debuglogs.org/android/5.50.4/30ec527a571fb7926023ba1d9243ae0630fd95ebd2cb9db23ae2a5021f0209f5

**Comment by cody-signal** [comment]
Can you confirm that Settings->Chats->Use system emoji is disabled?

**Comment by TheRisenPhoenix** [comment]
Yes, it is disabled. I also tried enabling and disabling it again, but the issue persisted

**Comment by TheRisenPhoenix** [comment]
Soo I just did some tests with friends:
It seems like this issue appears at least on Android 11 and Android 9, but apparently not on Android 12. iOS is also not affected. (at least as far as I can tell from my very limited sample size and quick asking around)

**Comment by cody-signal** [comment]
Thanks for the extra details, I've been able to reproduce on some of my devices. It's a weird one...I'll keep ya posted.

**Comment by UnderscoreX5** [comment]
Issue should be solved as of last beta.

**Comment by greyson-signal** [comment]
Fixed in 5.51.x
