### ISSUE TITLE
"Media no longer available" error when displaying recent images

### ISSUE THREAD

**Issue by jakub-sieradzki** [signalapp/Signal-Android#12483]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to open an image sent to me, the error toast "Media no longer available" appears and full screen view closes.
This error affects only recent images (sent over the past week), older ones open as expected.

### Steps to reproduce
- Open conversation view
- Go to the media gallery
- Open one of the recent images

**Actual result:** Error toast "Media no longer available" appears and full screen view closes.
**Expected result:** Image opens in full screen view.

### Screenshots
https://youtu.be/QyVbFg2H-xs

### Device info
**Device:** Lenovo k10a40
**Android version:** 6
**Signal version:** 5.50.4

### Link to debug log
https://debuglogs.org/android/5.50.4/a39f2aed43bb520451abc112c926f4d145d27b7c87877a3e4d62a0f6cd02f45f

**Comment by AplusKminus** [comment]
I can confirm this bug, but so far it only occurs in one group and not with an image that I sent. It does occur with videos in that group though.

### Device Info

**Device**: Google Pixel 5
**Android version**: 13
**Signal version**: 5.53.4

### Link to debug log
https://debuglogs.org/android/5.53.4/b6c3ebe7012cb94560bf2dfea7b264b2926f914e01966d7376c7d0422fc85278

**Comment by realwuffi** [comment]
Same Herr, not with every chat but it seems like it affects videos and animated gifs

https://debuglogs.org/android/6.1.4/180ea773274cd78a34f551c1a7d28ed864f023103f33c366bc6c6f64e9d9d0a7

**Comment by AplusKminus** [comment]
I cannot reproduce the bug anymore, not even with the videos where it originally occurred. Currently on version 6.3.0.
