### ISSUE TITLE
Incorrect contact listed in group, cannot view their messages.

### ISSUE THREAD

**Issue by viasux** [signalapp/Signal-Android#12480]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A contact who has joined a group I created appears to be 'replaced' by a different contact. The join message shows the correct user's name, but I cannot see any of their messages and they are replaced in the user listing of the group with a different contact. This bug does not affect my linked signal desktop app.

### Steps to reproduce (has not been repro'd, don't want to bug people)
- Add 3 contacts in your phone
- Message all 3 individually on signal
- Create a group chat with 2 of them
- They both join

**Actual result:** One contact will be replaced by a third, seemingly unrelated contact with a different name and phone number. The join message shows the correct user's name, but I cannot see any of their messages.
**Expected result:** I expect my contact to show normally, not as some random third contact, and I expect to be able to see their messages.

### Device info

**Device:** Pixel 4a (5G)
**Android version:** 13.0
**Signal version:** *molly version v5.48.3-1-FOSS
I first asked the molly devs about this bug, and they said since Molly is 99% signal code and they couldn't think of a way Molly's code could produce this bug, I should report here.

### Link to debug log

I am not comfortable posting a debug log publicly. I could send one privately.

**Comment by cody-signal** [comment]
Please try to reproduce this with a standard Signal install and post/send a debug log to me. <name> at signal dot org.

**Comment by viasux** [comment]
> Please try to reproduce this with a standard Signal install and post/send a debug log to me. [name] at signal dot org.

If I find the time to do this and people to bug into testing it with me, I will. What's that email supposed to be exactly?

**Comment by valldrac** [comment]
> Please try to reproduce this with a standard Signal install and post/send a debug log to me. [name] at signal dot org.

Cannot reproduce it in Molly v5.48.3-1-FOSS either. We tried several devices and accounts. @viasux and I have sent an email to you with more details.
