### ISSUE TITLE
Fatal Exception when trying to retrieve messages

### ISSUE THREAD

**Issue by camditt** [signalapp/Signal-Android#12497]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Service crash when checking messages

### Steps to reproduce
Build the app and install on Android

**![image](https://user-images.githubusercontent.com/93596459/194636070-f36b5ca9-5af8-412b-a432-40f86ca3b0e1.png)
The code 565 - PushServiceSocket.java should be updated 
From:
`try (Response response = makeServiceRequest(String.format(MESSAGE_PATH, ""), "GET", (RequestBody) null, headers, NO_HANDLER, Optional.empty())) {`

To:
`try (Response response = makeServiceRequest(String.format(MESSAGE_PATH, "", ""), "GET", (RequestBody) null, headers, NO_HANDLER, Optional.empty())) {`

### Device info

**Device:**Pixel 6 Pro
**Android version:** 13.0.0
**Signal version:** 5.52.0

**Comment by greyson-signal** [comment]
This was fixed in 5.52.1, apologies!
