### ISSUE TITLE
Media picker crashes when deselecting last item

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#12493]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you deselect all the media items in the built-in media picker, it crashes.

### Steps to reproduce
1. Open the media picker either via the path from the camera icon on the chat list or within a chat
2. Navigate to any media folder
3. Select at least one image or video
4. Deselect all selected media items by tapping them

**Actual result:** Media picker disappears (apparently crashing) and a toast appears with the message "One or more items were invalid"
**Expected result:** Media picker remains open with no items selected, as if you had just opened it and not yet selected anything

### Device info
**Device:** Pixel 5
**Android version:** 13
**Signal version:** 5.50.4

### Link to debug log
https://debuglogs.org/android/5.50.4/5c6df8dbdcfcee1f8113babc00b744939a232080b569c304a129ffb865bfeb9a

**Comment by greyson-signal** [comment]
Not a crash, but it is a bug. We'll TAL :+1:

**Comment by artur-borowiec** [comment]
I took a look at this and here's my insight (I'll describe events happening in `MediaSelectionViewModel`):

When user takes a photo, then goes back, method `removeCameraFirstCapture` calls `removeMedia` with `supressEmptyError` flag set to `true`. It was introduced as a fix to (https://github.com/signalapp/Signal-Android/issues/11729).

When user de-selects last item from gallery, the same method is invoked with the flag set to `false` and such code is executed:
```
 if (newMediaList.isEmpty() && !suppressEmptyError) {
      mediaErrors.onNext(MediaValidator.FilterError.NoItems())
    }

```
`newMediaList` is now empty, so `NoItems` error is thrown, as described in the issue.

I could've supressed the error again (empty selection doesn't seem to be an error) but then `MediaValidator.FilterError.NoItems` would be useless.
Is there a case when NoItems error should be thrown?

**Comment by Herohtar** [comment]
Still exists in 6.3.6

**Comment by Herohtar** [comment]
This issues appears to have been resolved at some point!
