### ISSUE TITLE
Front facing camera not working Pixel 3

### ISSUE THREAD

**Issue by Xhvvvvv** [signalapp/Signal-Android#12491]
----------------------------------------

### Bug description
Front facing camera not working if launched from Signal app. Camera works fine if launched from Linked Devices. Camera works fine outside of Signal. Issue persisting last few versions.

### Steps to reproduce
- open Signal chat
- press camera icon
- black camera screen
- press camera trigger
- crash popup

**Actual result:** Black screen or crash

**Expected result:** Signal camera works 

### Screenshots
![signal-2022-10-04-04-43-00-431](https://user-images.githubusercontent.com/114946117/193645279-5a5fa730-9eb1-41bf-9a5a-b0470cf1531a.jpg)

### Device info

**Device:** Pixel 3
**Android version:** SP1A.210812.016.C2.2022090700
**Signal version:** 5.50.4

### Link to debug log

https://debuglogs.org/android/5.50.4/070e857f8b604370da637b1a3b5e6ffbfcccacad3368887e5d678fd1b92d47d1
![signal-2022-10-04-04-43-29-499](https://user-images.githubusercontent.com/114946117/193645286-df3920d4-dd38-40ed-83fc-6b8cd63b5983.jpg)
![signal-2022-10-04-04-43-50-243](https://user-images.githubusercontent.com/114946117/193645307-b17f8dc1-9a60-4123-b2b8-63ca37a2a336.jpg)
![signal-2022-10-04-04-43-57-791](https://user-images.githubusercontent.com/114946117/193645324-01e4097e-abbf-427a-8aae-0ea04181d762.jpg)

**Comment by Vggh** [comment]
The official Signal apk download is still at 5.50.4:

![signal-2022-10-05-08-58-33-830](https://user-images.githubusercontent.com/115045800/193938072-90f707d2-a048-4448-9332-e33caa56c8c9.png)

**Comment by Vggh** [comment]
OK, I will have to wait to test if it resolves the camera issue as I can only install the .apk file releases

**Comment by Vggh** [comment]
I just tested the new .apk version 5.51.7 and the issue is the same. Camera works when launching Linked Devices but not when launched from chat. I noticed that there is no android 'camera in use indicator' like when when the Linked Devices is using it.

https://debuglogs.org/android/5.51.7/7fb228119bb347440619c4ddd3c10ae5f4f2c60920da7550ad2f938d5635b8c9

**Comment by Vggh** [comment]
![signal-2022-10-06-13-07-09-924](https://user-images.githubusercontent.com/115045800/194198288-6abae36f-581f-45c9-a4c7-c5b1cff444a3.jpg)

That is the indicator that I mean (I am not sure of the proper term).

**Comment by Vggh** [comment]
![signal-2022-10-06-13-07-09-924](https://user-images.githubusercontent.com/115045800/194198288-6abae36f-581f-45c9-a4c7-c5b1cff444a3.jpg)

That is the indicator that I mean (I am not sure of the proper term). 

![signal-2022-10-06-13-08-56-915](https://user-images.githubusercontent.com/115045800/194198470-9fd8355a-ea7b-4953-9be5-45ead5324123.jpg)

**Comment by Vggh** [comment]
> Can you let me know if this is resolved in 5.51?

I tested on 5.51.7 and the issue persists.
