### ISSUE TITLE
Push Notification on Google-Free Smartphones

### ISSUE THREAD

**Issue by genofire** [signalapp/Signal-Android#12490]
Google independent generic push system:
https://unifiedpush.org/

Switch to UnifiedPush with FCM embedded support:
https://unifiedpush.org/developers/embedded_fcm/

- [x] I have searched open and closed issues for duplicates
  - Closed because of mistrust on Signal would solve it  https://github.com/signalapp/Signal-Android/issues/11154
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
  - Found no official Statement https://community.signalusers.org/t/use-gcm-fcm-alternatives-for-notifications/10264/8

**Comment by genofire** [comment]
Okay, to close an issue with no text or commant from an maintainer is also a statement.

**Comment by greyson-signal** [comment]
Apologies for the lack of comment, but we don't anticipate doing this work. We reserve github for bug reports not feature requests, which is why it was closed before.

Signal *does* work without play services. What confuses people is that we do not guarantee that Signal works with _fake_ play services. When there's no play services installed at all, we will fallback to a persistent websocket connection to deliver notifications.

**Comment by genofire** [comment]
I understand that this is not direct an bug, i could formulate that as an Bug: e.g. Websocket is not (re)connected after a while.

Do you have not a default snippet for such closing?

In the End, i not feeling understand:
 - Forum has not get any official answer
 - linked Issue was not closed, because the Opener do not believe that Signal would do anything
 - this Issue close without commant
 - you call an OpenStandard as fake play service (see next part)

---

We do not talk about fake play services. There is an official standard called UnifiedPush, for Applications and ApplicationServer. So not every Application needs to create a Websocker, SSE, HTTP-Poll or any TCP connection (together with an Notification).

UnifiedPush has a library where is FCM inside, so that if the user has not installed/setup any UnifiedPush Provider. It will fallback to the Google Play Service.

So please do not call it _fake play service_, because it does not try to reimplement google - it is an open standard for push notification (which works outside of android, like Linux also).
It would be really nice, that Signal use OpenStandards for Notification and do not use propriare (Google and own Websocket implementation).

**Comment by metaphys** [comment]
I confirm what genofire is saying, this isn’t a fake gplay but an open implementation. This means also that users could then choose their notification server or even self-host it. (nextcloud for instance offer this functionnality)

**Comment by rightsaidfred99** [comment]
One wonders about open source software that still uses proprietary standards. a shame.

**Comment by uberhalit** [comment]
Proof enough that the original Signal app cannot be trusted. Use Molly instead: https://github.com/mollyim/mollyim-android

**Comment by okias** [comment]
@cody-signal

Hi. This is very much privacy related issue. This is very far from feature request **in context** of Signal.

While push notifications not leaking messages, it leaking important metadata. As Signal built (I hope it's still the case) on premises of open system, forced dependency on push notification from closed source implementation sounds like something undesirable (while ofc, people not caring about the privacy that seriously may be OK with it).

Thank you for consideration and for keeping Signal focused on privacy and openness.

**Comment by rightsaidfred99** [comment]
Just use Molly with UnifiedPush support instead, it's superior app over Signal in both battery life and privacy

**Comment by secureprivate** [comment]
bump
