### ISSUE TITLE
Unable to see messsages/people after re-joining group chat

### ISSUE THREAD

**Issue by FFMbyBicycle** [signalapp/Signal-Android#12492]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a persons leaves a group chat for a while and then re-joins the group chat later on, the person is unable to see messages from other people who joined the group during their absence. We were able to reproduce this error with multiple group chats with a lot of different people and devices. It doesn't matter if it is a fresh or already existing (older) group.

### Steps to reproduce
You need at least 4 people/devices for this test. Create a group chat with person A, B and C. All of the three are able to see each others messages and all members in the list of group members, no problems.

Now person A leaves the group chat without blocking anybody. After that person D joins the group while person A is still NOT in the group (important!). B,C and D are able to read each others messages without problems and can see each other in the list of group members.

Person A joins the group chat **again**. Person A is now unable to see (new) messages from person D (which joined the group while person A was not in the group), while messages from B and C are working fine. Person A is unable to see person D in the list of group members, too. Communication between B, C and D is working fine and D is able to see messages from A, too - but not the other way around. New messages from D will not be shown at all for A.

When B or C is citing/responding to a message from D, A will see the reply and the first two lines of the original message together with the error "Original message not found". If A tries to follow the reference of the original message, the error same error occurs (see screenshot).

**Actual result:** People who left a group chat for a period of time will be unable to see other people and their messages when they joined during the time of their absence
**Expected result:** All people in a group chat should be able to see all people and their messages, regardless if they left the chat group for a period of time

### Screenshots
![signal-error](https://user-images.githubusercontent.com/74880272/193826598-94385bc7-4e47-4f37-8bce-d4fd5778f8c1.png)

### Device info
Tested with multiple Android and Apple devices, let me know if details will help here

### Link to debug log
No debug log created, but can be supplied if required

**Comment by cody-signal** [comment]
> Person A joins the group chat again. 

In your testing, how does Person A rejoin? Invite link? Manually added by an admin?

**Comment by cody-signal** [comment]
Thanks. A debuglog from device A after this all happens would be helpful

**Comment by cody-signal** [comment]
No worries on the log. Figured out the issue.

**Comment by cody-signal** [comment]
> D is able to see messages from A

@FFMbyBicycle  Can you double check this is actually true? I just tried to reproduce this, for me, A doesn't see D's messages, and D doesn't see A's messages.

**Comment by FFMbyBicycle** [comment]
Yes, you're right. Sorry for that wrong information, just reproduced it here and got the same result. For me it is interesting that A and D don't see each other messages, but D is able to see A as a group member - but not the other way around.

And one more detail we just noticed: A, B and D got Android devices here, C got iOS. I was A and in a second step I used Signal desktop app in parallel where I can see that D is a group member and I can see all messages from D and when I send a message using the desktop app D is also able to see my (A) messages. Also replying works when the messages were sent using the Desktop app. Seems not to be a general protocol problem, but something with the mobile app(s) :-)

Let me know if you still need a debug log, hopefully I was fast enough due to some other messages arriving...

**Comment by cody-signal** [comment]
Thanks for confirming it.

The issue is isolated to the device's local state. This is why linked desktop is fine. The device isn't processing the group state properly and essentially doesn't update the local state properly to include Device D.

**Comment by bce000** [comment]
A user left Signal for a while, group and Signal.
Sent this user a group link without confirmation need
The user reconnected to Signal and the group.
I am blocked by this user.
I am the only user who sees this user in the group and on signal.
My linked devices report this user as not connected to Signal.
Other users see this user as not connected to Signal

**Comment by bce000** [comment]
Hi, Is there any way for the user to get a working signal before official version 5.52 is released?
Reinstall Signal, workaround, something else or just sit down and wait for official release 5.52?

**Comment by FFMbyBicycle** [comment]
Just tested it using Signal 5.52.5 and multiple test persons, bug seems to be fixed :+1:

Person A will receive a notice that person D now joined the group and all are able to read all message. Thanks a lot for this fast solution!
