### ISSUE TITLE
Can't enable proxy in working profile

### ISSUE THREAD

**Issue by Nonie689** [signalapp/Signal-Android#12508]
I can't connect from my working profile [where signal is installed] to my main profile

I am using netguard in the working profile and in the main profile [and there are also a socks connection enabled to my proxy]

in the netguard at the working profile are signal excluded

the proxy is on 127.0.0.1:1080

sometimes signal can connect to the proxy, but mostly it does not!

  1. I would like to insert proxys, also when the connection fails
  2. I want to insert multiple proxys
 
**Device:** Manufacturer Model Google Pixel 6
**Android version:** 13 latest [graphene-os]
**Signal version:** latest

**Comment by greyson-signal** [comment]
Hi there, we use github as a bug tracker. This looks like something complicated and specific to your networking setup. Signal uses  standard networking libraries.
