### ISSUE TITLE
Cant register number & dont get sms verification

### ISSUE THREAD

**Issue by rashidmya** [signalapp/Signal-Android#12506]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever i try to enter my phone number to register, I keep getting "youve made too many attempts to register this number". Ive been trying for like 3 days now and i never get an sms too

### Steps to reproduce
- open app
- tap continue
- enter number number & tap next

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** pixel 6a
**Android version:** android 13
**Signal version:** 5.51.7

### Link to debug log
https://debuglogs.org/android/5.51.7/5bd8e51f401b791b0cdb05b8e1c4e22cb1a57af4e7dddff31a36edd57bb97a50

**Comment by ferid-akifzade** [comment]
Me too. I think it is problem for people live in neither US nor EU country.

**Comment by greyson-signal** [comment]
@rashidmya Looks like you're running grapheneOS, and your using some FCM alternative that's throwing exceptions during registration. Signal supports phones with play services, and we support phones without them, but if you install play-services-alternatives, you're on your own. Sorry!

**Comment by scientiac** [comment]
I am using Lineage OS 20 with android 13.

Last time I used lineage was via waydroid on droidian and signal worked just fine then, but now that I've installed Lineage on my phone it's just not letting me log in.

It gives an error saying "Too many attemps to register this number, please try again later." I waited days and retried but can't log in. 

Another problem is: It gives the same error on trying any phone number not just mine.

**Comment by greyson-signal** [comment]
@scientiac I'm gonna assume you're hitting the same issue. Lineage (or something you installed in addition to lineage, idk) has an FCM shim that is throwing an IOException where it shouldn't.

**Comment by greyson-signal** [comment]
If people want more details, the specific exception is this:

```
[5.51.7] [52  ] 2022-10-09 13:17:49.890 GMT+04:00 W FcmUtil                 Failed to get the token.
[5.51.7] [52  ] 2022-10-09 13:17:49.890 GMT+04:00 W FcmUtil                 java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
```

**Comment by rashidmya** [comment]
> If people want more details, the specific exception is this:
> 
> 
> 
> ```
> 
> [5.51.7] [52  ] 2022-10-09 13:17:49.890 GMT+04:00 W FcmUtil                 Failed to get the token.
> 
> [5.51.7] [52  ] 2022-10-09 13:17:49.890 GMT+04:00 W FcmUtil                 java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
> 
> ```

will Signal stop relying on google services in the future?

**Comment by greyson-signal** [comment]
I wanna be super clear: Signal does not require play service to function. However, if play services are _present_, we expect them to work. Idk what Lineage has done, but they've put some shim in that breaks things. Signal can't be putting patches in to fix mistakes in every fork out there.

**Comment by scientiac** [comment]
Apparently when i try to log into my dads account after logging his account out from miui and then logging back in again, it gives the same error. 

testing this on MIUI - Android 13, with all google dependencies. 

P.s. It was working all along but after i logged out and tried to log back in, says "too many attempts"

I dont think its a lineage problem.

**Comment by greyson-signal** [comment]
@scientiac Can you please share a log? You could be hitting a different issue.

**Comment by endim8** [comment]
I'm also getting this issue! It would be good if signal showed an error message along the lines of "FCMUtil unable to get token". I've been trying to login for a week at this point, assuming it was a network issue as the only error message given is "failed to connect to server"


device: Pixel 6 Pro, LineageOS 20-20230303

**Comment by endim8** [comment]
LineageOS people say it's an issue with Signal's FCMUtil library:
![Screenshot from 2023-03-09 14-48-12](https://user-images.githubusercontent.com/26939824/224060997-2321cf8f-ddaf-4e2b-b261-c43f5b1731aa.png)
![Screenshot from 2023-03-09 14-48-29](https://user-images.githubusercontent.com/26939824/224060993-3a77d568-1d40-476b-b8d8-c75ab7f45102.png)

@greyson-signal can this be re-opened?

**Comment by cody-signal** [comment]
Please try on 6.14.2 when it's available to you. Just went to beta.
