### ISSUE TITLE
App crashes when sending stories

### ISSUE THREAD

**Issue by nehemiagurl** [signalapp/Signal-Android#12500]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Signal app crashes when sending stories
Updated to the latest version on the Play Store (I am a beta tester, and this is the beta version) and tried to post a story. The app crashed. After reopening, I tried resending the failed story, and it crashed again. Image and text stories both resulted in crashes, regardless of text length and regardless of text language.
After changing the privacy settings of my stories, the app stopped crashing, however, sending story updates to one of the groups I'm in still results in crashes consistently.

### Steps to reproduce
- set story privacy to "all Signal connections"
- attempt to post a story 

**result**: the app instantly crashes during the sending phase, and the story is not sent.

alternatively
- attempt to post a story to a group 

**result**: for some of the groups (but not all), the app instantly crashes during the sending phase, and the story is not sent.

### Screenshots
![Screenshot_20221007-235735_Signal](https://user-images.githubusercontent.com/109424320/194651380-4e57cc66-d0df-42ba-97ca-d72d7c028f81.jpg)

### Device info
**Device:** Samsung Galaxy A12
**Android version:** 12
**Signal version:** 5.52.3 (beta tester)

### Link to debug log
https://debuglogs.org/android/5.52.3/f3c4681954809be4315ab2d3b5afa8ac03d2646b3f215fe41f2694edd9eace09

**Comment by nehemiagurl** [comment]
Updating to 5.52.4 (which came out yesterday) still results in the same crashing behaviour under the same conditions.

Here is the updated debug log:
https://debuglogs.org/android/5.52.4/5ce83056d2871e62b9324658519eaa10aced43a519e7f6a4ebd7a7141ab4b107

**Comment by UserX404** [comment]
Due to 5.52 is actually in beta I would suggest to report beta bugs in the corresponding #beta-feedback thread in the forum.
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-52-release/47714

**Comment by nehemiagurl** [comment]
This issue seems to have been resolved in 5.53.0.
