### ISSUE TITLE
Emoji included by typing colon and emoji name (e.g. :smile) are not added to recently used emojis

### ISSUE THREAD

**Issue by AmirGamilDev** [signalapp/Signal-Android#12514]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As the title says, emojis used by typing an emoji using colon (e.g. :smile) are not added to recently used emojis list.

Given that the relatively recent functionality of emojis found via emoji search _are_ added to the recently used emojis list, this felt like a bug/inconsistent behaviour.

### Steps to reproduce
- In a chat, type an emoji that _isn't_ currently in the recent emoji list.
- Tap the emoji icon
- Open the recent emoji list

**Actual result:** The typed emoji is not showing in the recently used emoji list.
**Expected result:** The typed emoji should show in the recently used emoji list.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 5.51.7

### Link to debug log
https://debuglogs.org/android/5.51.7/4a5e7cad7f55d5bcd117a775dc85aca1fe3ddb61d13a670066bcadb2d3701eeb

**Comment by Gh0stz0x** [comment]
The problem still exists.
