### ISSUE TITLE
MMS group card shows 'insecure call' button

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12512]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the main conversation list you can click on the profile picture of an MMS group which opens a group card. In this card you have the option to 'Message' or 'insecure call'. Insecure call shouldn't be there and causes the app to crash.

### Steps to reproduce
- Open main conversation list view.
- Click on the image of an MMS group. This will open a quick card.
- See and click on the insecure call button.

**Actual result:** Insecure call button is displayed, clicking it crashes the app.
**Expected result:** Insecure call button shouldn't be displayed for MMS groups (but should still be displayed for individual SMS conversations).

### Screenshots

![signal-2022-10-11-09-45-45-234.jpg](https://user-images.githubusercontent.com/18274896/195123571-3fde152f-401a-4795-88dc-042d60302485.jpg)

### Device info

**Device:** Pixel 5
**Android version:** 13
**Signal version:** 5.51.7

**Comment by Sgn-32** [comment]
Not quite sure should be this line https://github.com/signalapp/Signal-Android/blob/c82bf826e0abfac42c6293c6a8ceffec073ffe1d/app/src/main/java/org/thoughtcrime/securesms/recipients/ui/bottomsheet/RecipientBottomSheetDialogFragment.java#L227

`/* isAudioAvailable   = */ !recipient.isBlocked() && !recipient.isSelf() && !recipient.isReleaseNotes(),`

Needs an `&& !recipient.isMmsGroup()`

But having no MMS group, i can't test a PR.

**Comment by Tursko** [comment]
> Not quite sure should be this line https://github.com/signalapp/Signal-Android/blob/c82bf826e0abfac42c6293c6a8ceffec073ffe1d/app/src/main/java/org/thoughtcrime/securesms/recipients/ui/bottomsheet/RecipientBottomSheetDialogFragment.java#L227
> 
> `/* isAudioAvailable   = */ !recipient.isBlocked() && !recipient.isSelf() && !recipient.isReleaseNotes(),`
> 
> Needs an `&& !recipient.isMmsGroup()`
> 
> But having no MMS group, i can't test a PR.

I would try to do this myself but I haven't figured out how to build and run the app in android studio yet. Maybe I'll give it another shot.

**Comment by Tursko** [comment]
Will be closing. 
https://signal.org/blog/sms-removal-android/
