### ISSUE TITLE
Transfer to new Android device stuck at 99.9% then runtime exception is thrown when retrying

### ISSUE THREAD

**Issue by nkosi23** [signalapp/Signal-Android#12511]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have just been trying to transfer Signal's data to my new Android phone. The transfer took a lot of time (there is 7gb of data to transfer) so I left the phones on a desk and went to work on something else in the meantime. When i came back, the Signal application was no longer open on the new phone (it just disappeared, probably crashed), and the transfer was stuck at 99.9% on the old phone.

I initially tried to leave the old phone stuck at 99.9% and restart the transfer on the new phone hoping that it would resume, but unfortunately the new phone was not able to find the old phone. I therefore decided to cancel the transfer on the old phone, and **something very scary happened**: after hitting the cancel button on the old phone, I was taken to the message list page and a pop up opened itself saying in essence: "All good! You now need to register Signal on your new phone, you will not be able to use Signal on this phone until you do so". And the bottom of the popup had two buttons: IIRC the first one was saying "ok" and the second one was saying something like "Cancel and continue using Signal on this phone". Of course I did hit the second button, but it really looked like I could have been left in situation where I wouldn't have been able to use Signal on any phone. I think it is totally **not normal** that this popup was displayed despite the fact that the transfer was not complete. Fortunately, there was no data corruption or things like this and I am still able to access my data on the old phone.

Based on the advice I've found on the internet, I went to the settings of both phone to hard stop Signal and restart the application to try again. But now, the old phone produces a runtime exception whenever I try to start the transfer process (a few seconds after the "looking for the other phone" stage begins). The new phone does not have the issue and just keeps waiting for the connection to be established before displaying the timeout page (the page giving tips such as: check your connectivity etc...). Here [are the debug logs](https://debuglogs.org/android/5.51.7/90ada521f9d968d1ef0421399aeb6efb1fbb212afa4587c1fcf33b977e0a53a9) of the old phone.

My old phone is dying (screen issue getting worse by the day, the screen has an increasing green shade, blinks like crazy, and starts turning itself off randomly and increasingly frequently) so I really need to get the data out asap. Unfortunately I do not have enough free internal storage left to make a file-based backup, but I will continue to think about how and if I can move in that direction in the meantime while this bug is sorted (I have a bunch of constraints making freeing space inconvenient). It is unfortunate that this feature doesn't just work.

### Steps to reproduce
- Start a transfer between two android devices

**Actual result:** The transfer is stuck at 99.9% on the old phone, and the Signal app is shut down on the new phone. From then on, everytime I retry the transfer the old phone produces a runtime exception a couple of seconds after the "looking for the other phone stage begins".
**Expected result:** The transfer completes itself, and my data is successfully transferred on the new phone.

### Device info

**Device:** Samsung Galaxy S8 (SM-G950F)
**New Device:** Xiaomi Redmi Note 11
**Android version (old phone):** 9.0.0
**Signal version:** 5.51.7 (same version on both devices)

### Link to debug log
https://debuglogs.org/android/5.51.7/90ada521f9d968d1ef0421399aeb6efb1fbb212afa4587c1fcf33b977e0a53a9

**Comment by cody-signal** [comment]
Nothing jumps out in your logs. It looks like the wifi direct connection was dropped and then couldn't re-establish. We have an internal project slated for general improvements around D2D transfer quality of life.
