### ISSUE TITLE
Add Last seen and online similar to WhatsApp

### ISSUE THREAD

**Issue by u2s1e0r3** [signalapp/Signal-Android#12516]
These missing features prevent my girlfriend from using Signal instead of WhatsApp. That's an issue.

https://faq.whatsapp.com/general/chats/about-last-seen-and-online/

Last seen and online tell you the last time your contacts used WhatsApp, or if they're online. If a contact is online, they have WhatsApp open in the foreground on their device and are connected to the Internet. However, it doesn't necessarily mean the contact has read your message. Last seen refers to the last time the contact used WhatsApp.

**Comment by yoshimo** [comment]
> That is a privacy issue.

Yes, but like the competition or the new stories, nobody forces you to use it and you can filter it down to selected people if implemented that way.

**Comment by greyson-signal** [comment]
Hi there, I appreciate the feature suggestion, but we handle feature requests in the [forum](https://community.signalusers.org/). We only use Github to track bugs. Thanks!
