### ISSUE TITLE
The alert "SMS support going away" is not localized.

### ISSUE THREAD

**Issue by ikanakova** [signalapp/Signal-Android#12528]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The alert "SMS support going away" is not localized.

### Steps to reproduce
- Open Signal.

**Actual result:** The alert "SMS support going away" is displayed in Signal in English not in my language.
**Expected result:** A warning about such an important matter should be translated before it is shown to ordinary users.

### Device info

**Device:** Nokia 6.1
**Android version:** 10
**Signal version:** 5.53.2

**Comment by greyson-signal** [comment]
Hi there, translations are often not available during beta. Rest assured we will have fully translated strings before going to production. Thanks!

**Comment by ikanakova** [comment]
@greyson-signal Sorry, I wasn't sure it was a beta version - see https://community.signalusers.org/t/show-that-it-is-a-beta-stable-version-in-help/48184/3
