### ISSUE TITLE
SMS export runs forever

### ISSUE THREAD

**Issue by rs3212** [signalapp/Signal-Android#12523]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using SMS export, the process starts but always runs beyond the total count, forever incrementing. I let it run 24 hours. The total count was 27672 but it ran beyond 280000 until I force stopped the app. 
After restarting SMS export it now shows a total of 233 and it still runs beyond the total. (this is repeated every time I force stop the app and restart SMS export)
  

### Steps to reproduce
Start SMS export

**Actual result:** It runs forever
**Expected result:** Process ends at total or it at least updates the total, and displays some kind of final summary of messages failed, successful, etc.

### Screenshots

![signal-2022-10-14-012446_002](https://user-images.githubusercontent.com/115780483/195799659-445d2358-42b1-4a74-b787-6ab7eb2a6444.png)

### Device info

**Device:** Pixel 5a
**Android version:** 13
**Signal version:** 5.53.1

10-14 01:28:01.119   520  1137 D SmsExportService: Failed to write attachment to disk.
10-14 01:28:01.119   520  1137 D SmsExportService: java.io.IOException: No stream for: AttachmentId::(604, 1596248813228)

10-14 01:28:01.119   520  1137 D SmsExportService: 	at java.lang.Thread.run(Thread.java:1012)
10-14 01:28:01.432   520  1137 D ExportMmsPartsUseCase: Checking attachment that may already be present...
10-14 01:28:01.555   520  1137 W AttachmentDatabase: null
10-14 01:28:01.555   520  1137 W AttachmentDatabase: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms

/app_parts/part7589924079002502350.mms: open failed: ENOENT (No such file or directory)

**Comment by greyson-signal** [comment]
Hi there! Any chance we could get a full debuglog link?

**Comment by rs3212** [comment]
I have inspected the entries that SMS exporter is duplicating forever (all MMS) and I think I have an idea why this is happening. Several years ago I accidentally deleted one of my large conversations. I realized what was happening and stopped the app before it could delete all the history. Consequently a large portion of the history in media shows as broken ( it shows an image icon with an exclamation).  It appears that media is stored in app_parts. Some of those files have probably been deleted before the entries in the database itself were deleted. When it tries open the file during export it throws an exception. I'm assuming there might be an issue with the iterator not taking into account entries that throw exceptions or the entries don't get flagged because of the exception.

**Comment by rs3212** [comment]
I have saved the debug log externally but how can I be sure everything is properly anonymized? There's so much information I'm not sure I'm comfortable posting it (I'm kind of paranoid) where it is publicly accessible as it is my personal phone.

**Comment by owenvoke** [comment]
I think this is probably the most similar issue to mine, but let me know if I should create a new one.

I had this issue too, the messages didn't export however (after reaching 20,000+ / 2000) it now only gives the option to remove SMS messages from Signal, even though they didn't export at all.

Is there any way to get the SMS export button back? 🤔

**Comment by cody-signal** [comment]
@rs3212 you can send me the log directly: cody at signal dot org

@owenvoke To confirm, you've opened your new SMS app and there is no chats from signal?

**Comment by owenvoke** [comment]
@cody-signal, that's correct. The default SMS app on Android doesn't show the exported SMS messages at all. Signal still shows all my SMS messages, but I can't export them anymore.
