### ISSUE TITLE
SMS Support - Another Voice

### ISSUE THREAD

**Issue by TwisX** [signalapp/Signal-Android#12537]
I know this isn't the "proper" channel and I've already posted to the forums, but for the sake of visibility I'm posting here as well.

I understand the desire to drop an insecure protocol. However, that insecure protocol isn’t going anywhere anytime soon and is still widely used. Dropping SMS isn’t going to improve security for anyone. If anything, it will degrade security for users as they switch to another app for SMS messaging that might not be maintained to the same standard as the Signal app is.

From a usability perspective, this will just frustrate existing users and will likely be offputting to potential new users. For me, Signal is the iMessage of Android. One app for all my messaging needs. If a friend is on Android, it’s not that difficult to get them to switch as Signal wouldn’t be “yet another messaging app” for them. Removing SMS support will destroy this great aspect of Signal.

I realize that Signal is a free app and the majority of users don’t contribute to development costs. However, listening to user feedback is a necessary feature of good development. It’s obvious that many, many users are upset about this decision. It’s not too late and wouldn’t be a “bad look” to backtrack on this.

I really hope that the Signal team listens and decides to keep SMS support instead of blindly pushing forward with this (in my opinion) poor decision.

Thank you.

**Comment by WSLUser** [comment]
I would second this. Whatever reasoning was used is extremely flawed.  I use this application and enjoy the fact SMS is included. I don't trust Facebook so WhatsApp isn't an option for me. I do trust Signal for encryption and appreciated the ability to send SMS when the recipient can't install Signal for whatever reason.  Dropping this support will drop a vast majority of users. Not sure where your revenue comes from but I suspect the sudden loss of millions of users will impact it in some way. I also sincerely hope somebody forks this project and keeps the fork updated from updates made here without dropping SMS support. You already made the questionable decision to remove plain-text backups and having that support just isn't worth the hassle but SMS? If a fork can have both plain text backups and SMS while staying updated, I'd jump to that fork in a heartbeat. Do everyone a favor and prevent the need for someone to fork this project in first place and bring back user facing features. Security also means availability and you are removing availability of services needed by many users. So not so secure then is it? Encryption is only part of the story. Not the only one. Know your CIA triangle, particularly the A.

**Comment by MartinX3** [comment]
I only started using signal because it replaced my SMS app...

**Comment by jcfyre** [comment]
I 100% agree, and the explanation on their website for the removal is just a spaghetti of words that sound like a very dry justification for complete SMS removal. If they really wanted they could have just made a setting where you could toggle on or off for a prompt to pop up when sending a message through normal SMS saying it will be unencrypted with a Cancel and an Okay button under it for confirmation. They could have very easily made this THE messaging app. I really hope they add that again in the future, especially the prompt idea for those who want to know when sending unencrypted messages.
