### ISSUE TITLE
Signal infinite crash loop after sending signal message to MMS group and attempting to delete it following SMS migration

### ISSUE THREAD

**Issue by coderjoe** [signalapp/Signal-Android#12534]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After trying to delete a message sent in an archived MMS group after finishing the SMS migration signal crashed.
Signal is now stuck in an infinite crash loop preventing me from loading the app or communicating to any signal contacts.

### Steps to reproduce
- Use signal for SMS/MMS
- Create a MMS group
- Send and receive a few messages
- Begin the SMS migration feature and export all your messages
- Make signal not the default SMS app
- Go back to signal
- Open the archived MMS thread and send a signal message in it
- Long press on the message and choose "delete for everyone"
- Watch the message delete
- Signal should now crash and should continue to crash every time when opened

**Actual result:** Signal crashes upon deleting and continues to immediately crash every time it is opened.
**Expected result:** Signal should open and work as expected. It probably should also display the same message in MMS groups that SMS is no longer supported prompting you to invite friends or move to your other app.

### Screenshots
Can't grab screenshots since it keeps crashing

### Device info
**Device:** Pixel 3 XL
**Android version:** Android 12 Build Number SP1A.210812.016.C2
**Signal version:** 5.53.2

### Link to debug log
I cannot capture debug log because the app immediately crashes so I cannot get to the menu.

**Comment by Techie007L** [comment]
Sadly, it seems that their planned solution to these problems is to completely eliminate SMS/MMS support in Signal.  Wait till you get the next version:

![Signal terrible foolishness3](https://user-images.githubusercontent.com/84245450/196055345-53ca1e68-94f3-486c-a2e2-fa2bcf09db0d.png)

**Comment by cody-signal** [comment]
Can you put your phone in airplane mode and try to get into the debug log that way? You can create a local zip of the log by using the 3-dot menu in the debug log viewer and either attach it here or send it to me via email. cody at signal dot org
