### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by CallMeFlanby** [signalapp/Signal-Android#12544]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

# Bug description
Backup is not working. After creating or choosing a folder, the passphrase message appears and after this pop-up is closed, nothing happens. 
Probably related with https://github.com/signalapp/Signal-Android/issues/12062, but in this case the folder created allows read and write. No pop-up message appears showing which is the problem. 

# Steps to reproduce
- try to do a backup
- choose a folder
- save passphrase and tick the box
- backup does not start

**Actual result:** 
No backup is started. 

**Expected result:** 
A backup should start

# Screenshots
![signal-2022-10-20-23-55-48-187.jpg](https://user-images.githubusercontent.com/7440579/197070969-978573a9-4d68-4ddd-874f-b1876f57dc24.jpg)

### Device info
**Device:** Poco X3 Pro
**Android version:** 12
**Signal version:** 5.52.5 (dual app mode) 

### Link to debug log
https://debuglogs.org/android/5.52.5/2b6c23eb33fdc5568f0dab24f5de72530ed217e8d16927a8a49a0de15b1914ce

**Comment by cody-signal** [comment]
We are unable to create a file in the folder. Either there isn't enough space or something is restricting us from making a file in the folder you've selected. Can you try other folders or making new one that's not in a default one?

**Comment by CallMeFlanby** [comment]
> 

Already tried other folders, removed and added permissions, nothing changed. The phone has more than 50% space free.

**Comment by cody-signal** [comment]
What is "dual app mode"?

**Comment by CallMeFlanby** [comment]
> What is "dual app mode"?

A mode that allows you to clone the app if you have a dual SIM phone and want to use an app for both numbers. There is a video from Xiaomi about it: [](https://m.youtube.com/watch?v=9U5Tnhqqn0o)
Don't know if the that may cause a problem but thought it would be nice to inform you that this problem happened with the app in dual app mode.
