### ISSUE TITLE
"Unable to discover old/new device" when trying to migrate Signal from old to new Android Smartphone

### ISSUE THREAD

**Issue by AndreasLuckert** [signalapp/Signal-Android#12542]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The phones cannot find eachother.

I assume this could be due to my old phone "Xiaomi Redmi Note 5" not having the "nearby" - function which might be required to discover the new phone?

### Steps to reproduce
- place phones physically next to eachother
- connect them to the same WiFi - network
- activate GPS and Bluetooth
- start backup transfer process from new or press "Try again" after failure
- on the new phone a message shows up like "Android_XXXXX" (Accept, Decline), but the old phone keeps trying to discover until failure. The new phone fails after "accepting" also, after a while.

**Actual result:** The phones cannot find eachother, it fails with "Unable to discover old/new device. Make sure the following permissions and services are enabled ..."

**Expected result:** The process goes successfully according to the official docs: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages

### Device info

**Old Device:** Xiaomi Redmi Note 5
**Android version:** 9 PKQ1.180904.001
**Signal version:** 5.52.5

**New Device:** Google Pixel 6
**Android version:** 13
**Signal version:** 5.52.5

**Comment by cody-signal** [comment]
Can you provide debuglogs for both devices after a failed attempt?

Make sure to clear the previous wifi direct connections from both devices by going to your wifi->wifi direct settings and removing saved groups, etc.

**Comment by greyson-signal** [comment]
Wi-Fi direct doesn't mean a direct cable: it's a direct P2P connection that can form between devices. You can read more here: [link](https://en.wikipedia.org/wiki/Wi-Fi_Direct).

Wi-Fi direct can be funny and flaky, and so one of the debugging steps would be to clear any state you have already in the system settings.

**Comment by jnns** [comment]
I experience the same problem. Here are the debug logs:

New device:
https://debuglogs.org/android/6.6.3/08cdbd9b986ca9aa756d74d57291c7c5a7169aac8bdf43786ea3e6b9872fb094

Old device:
https://debuglogs.org/android/6.6.3/7d6b9932e1b49a378a5fa621fc8bacb60dd04ada2fc89d81980f2f528421a413

**Comment by cody-signal** [comment]
@jnns thanks for the debuglogs from both devices.

Everything from our side looks correct. Both the old and new start up their services but are unable to find each other. Eventually the system starts not allowing us to do any wifi direct stuff.

I would double check your wifi direct settings and clear any previous groups or state and try again. If that still doesn't work, trying cycling wifi on/off or restarting the devices.

**Comment by jasonpolites** [comment]
I am having the same issue. New device. Both devices on latest version. Old device can't find new one. I've tried recycling wifi, tried rebooting both, checked any Wifi Direct sessions. I'm able to manually connect via wifi direct between the phones, but signal just seems to sit there with a spinner and never finds the new device

**Comment by Eiernase** [comment]
I'm having the same issue, exactly like described in the original post.
Looking at Reddit threads this seems to have been an issue for the past two years, also #11440.
I'll just work around this using a local backup and moving it between phones.

**Comment by Penguin-Guru** [comment]
I had to disable my V.P.N. Even when I set it to bypass for local network traffic, it does not.

**Comment by m000** [comment]
Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.

I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

**Comment by Aashishkebab** [comment]
Thank you devs for completely ignoring this issue.

**Comment by Penguin-Guru** [comment]
> Thank you devs for completely ignoring this issue.

It is frustrating but I assume they're under-staffed and busy, as a non-profit. It would be nice if they managed their repo issues better but at least they keep the apps and infrastructure running. The software's open-source so we could theoretically fix it ourselves if we needed to. Maybe someone outside the core team will at some point.

**Comment by chaosharmonic** [comment]
This isn't a fix, but I did just find a workaround after encountering this myself.

On opening the option to transfer accounts *out*, I was taken directly to the step to search for nearby devices. But if I scanned it with an unrelated QR code scanner, I was then taken to Signal, to start the QR-based pairing process -- at which point, after scanning it *again*, everything then worked as normal. (Including the wireless pairing, which in this flow is triggered next.)

If my understanding of the user-facing copy is correct, it's *supposed* to start with the QR scan within Signal. Meanwhile, it's equally buggy that the QR scan from outside initiates a second QR scan.

But if you're encountering this and your immediate priority is a working device migration, that should help you.

**Comment by PPsyrius** [comment]
> But if I scanned it with an unrelated QR code scanner, I was then taken to Signal, to start the QR-based pairing process -- at which point, after scanning it *again*, everything then worked as normal. (Including the wireless pairing, which in this flow is triggered next.)

Yes, this is the correct workaround - just don't initiate transfer on the old phone first or it would've been struck in the incorrect flow steps, just scan the QR transfer code displayed on the new phone with any camera app (I'm pretty sure most of them came with QR reader nowadays) and things should work perfectly again.

**Comment by chaosharmonic** [comment]
"Correct" in what sense? Is there a specific reason this is marked as won't fix? And, in particular, does that extend to outside PRs, or just Signal's internal dev team?

**Comment by wertzuz** [comment]
Won't fix is the tag added by the stale bot if there was norecent activity in the issue, that's also why it's closed. After it's closed you have to hope someone from Signal opens the issue again.

**Comment by chaosharmonic** [comment]
Got it, so it's more just an indicator about dev resources, and not necessarily intention. Good to know.

**Comment by Greenfoot5** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

Just wanted to say thanks, the worked well for me. I should also add, I turned off mobile data on both devices while also disconnecting from wifi networks.

**Comment by KLEPTOROTH** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

Thank you for this, this resolved the issue for me I have never had this previously.  I've swapped phones many times over the years and have never had to do this.

**Comment by ltpitt** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

OH MY YOU SAVED US!

IT WORKS!

**Comment by lukdz** [comment]
Recap how process should work:
1. On new device select transfer from old device to get QR code.
2. On old device scan QR code with Signal app and confirm data transfer 
    (this action over _Internet_ moves both phones to read for searching nearby devices mode)
4. Click search for nearby devices on both phones.
5. Once devices are connected via local network progress bar starts 
    (percentage on old phone, number of messages received on new phone)
7. Once transfer is completed you're no longer able to send messages from old phones.
 
Issues that I encountered:
1. With both devices connected to same WiFi and SIM card transferred to new phone, 
    process would get stuck on step 3 with devices searching for each other and new device throwing error after about a minute and showing troubleshooting steps (allow in setting Signal to find nearby devices etc.) non of which were helping. Annoying part was the fact that after each failed receive on new phone I had to reinstall app on new phone (to attempt transfer for second time, maybe logout have been enough) and reenable account on old one.
2. With WiFi enabled but not connected to any WiFi on both devices (as suggested above) and SIM card transferred to new phone,
    process would get aborted on step 2 with old phone throwing an error unable to access Internet after selecting data transfer option. Second SIM might have solved the problem...
3. With WiFi enabled but not connected to any WiFi on both devices (as suggested above), SIM card transferred to new phone and **both phones connected to the same LAN (using USB-C to ethernet adapter/laptop dock)**
    I was finally able to complete the process without any issues. Not really sure if transfer was done via WiFi or Ethernet (there was activity on adapter status LED during the transfer, but I could also see some blinking afterwards).

**Comment by KLEPTOROTH** [comment]
I love how this is labeled wontfix when this is clearly a bug.....

**Comment by Eiernase** [comment]
For me the issue turned out to be that I was connected to a VPN.
I had local network discovery turned on, but Signal still didn't like it.
Have since taken to using backup files instead though.

**Comment by LindyBalboa** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

My hero

**Comment by bigretromike** [comment]
New phone: HyperOS3 Android 16 (xiaomi) without sim
old phone: realme  with sim

1. wifi on but not connected to anything - does not help beause new phone without internet is unable to generate QR code
2. clear wifi direct (which is hidden under developer settings on hyperos) nothing (but when I connect them manualy direct connection is established)
3. scanning qr with other app and then with signal - does not help
4. VPN is off.
5. being on same wifi - does not help
6. being on different wifi - does not help

Any chance to reopen the issue so its more visible to developers @cody-signal ?

**Comment by 1337haXXor** [comment]
Well I just encountered this. It kept saying it could not discover the new Android device (doing Android to Android), both devices have WiFi and GPS on, VPN off, etc.
But the problem is now it de-registered the old Signal phone's account without transferring/activating it, and I can't re-register the old device because I no longer have access to that phone number.
Cool..

EDIT: Reopening the app on the new phone, it looks like it DID transfer the account and contacts and such, but none of the messages themselves. So it.. half transferred?

**Comment by wischi-chr** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

Thank you @m000 

I couldn't do exactly that because I only had one SIM, but it worked after I disconnected the phone with the SIM from WiFi (using mobile data). Looks like the P2P discovery completely breaks if they the phones try to connect directly to each other over WiFi but fail because the router is set up in a way (typically per default) that devices (especially mobile) don't see each other on the network.

I thinks it's pretty sad that issues like that are auto-closed by some bot because of "inactivity" :-/

**Comment by bigretromike** [comment]
I don't understand whatsapp do similar migration (don't know from backend point, but frontend looks very similar) yet, it did it without issue. And signal on same second phone did "half-transfer" (that is logout from old device, login on new device, did not transfer chats) twice.

**Comment by Taewan-P** [comment]
From my experience, turning off wifi and mobile data is the most promising way...

**Comment by bigretromike** [comment]
> From my experience, turning off wifi and mobile data is the most promising way...

sadly that did not helped in my case - just saying

**Comment by coleprogramer** [comment]
Hey guys, **I'VE FOUND THE WORKAROUND**.

So after installing the app on the new device, head to **Settings → Apps → Signal → Permissions**. Usually there will be enabled only permissions for: **_Contacts and accounts_**, **_Notifications_** and **_Phone_**. 
What you need to do is to **enable** (for some reason) all the rest of the **"Not allowed"** category below. In my case those were: **_Photos and Videos_**, **_Camera_**, **_Location_**, **_Microphone_** and **_Nearby Devices_**.  So enable all of those. 

You have to do it on both the new and the old phone. The moment you do it, the phones will "recognize and find" each other and you will get the authentication numbers on screen which must be the same. You go on and press okay if the numbers are the same (should be) and the transfer will begin.

In my case this was Xiaomi to Samsung. But I've tried Samsung to Samsung and was fine there as well. 
**You can leave the wi fi and mobile data on.** 


For some reason, **Signal might be crashing on the new phone afterwards**. Then just proceed with **uninstalling Signal and then installing it again**. This time when asked about Back up. **Select the "I don't have the old phone" and then select the "Restore from the Signal Cloud/Backup)**. I needed to insert the key, but afterwards it just loaded up and everything was fine and dandy. Signal is now working and all the data is transferred.

**Comment by bigretromike** [comment]
> For some reason, **Signal might be crashing on the new phone afterwards**. Then just proceed with **uninstalling Signal and then installing it again**. This time when asked about Back up. **Select the "I don't have the old phone" and then select the "Restore from the Signal Cloud/Backup)**. I needed to insert the key, but afterwards it just loaded up and everything was fine and dandy. Signal is now working and all the data is transferred.

So you somehow corrupted database and restore it from cloud/backup - this wouldn’t be needed if transferring from old phone work correct. Strange

**Comment by coleprogramer** [comment]
> > For some reason, **Signal might be crashing on the new phone afterwards**. Then just proceed with **uninstalling Signal and then installing it again**. This time when asked about Back up. **Select the "I don't have the old phone" and then select the "Restore from the Signal Cloud/Backup)**. I needed to insert the key, but afterwards it just loaded up and everything was fine and dandy. Signal is now working and all the data is transferred.
> 
> So you somehow corrupted database and restore it from cloud/backup - this wouldn’t be needed if transferring from old phone work correct. Strange

I agree. It would be way easier if the transfer option was flawless and was functioning properly. 
I'd say that, probably, what happened was that all the data was transferred correctly but something else interfered with the app afterwards (probably some of the permissions might bug out the app afterwards). So the data was then present on the phone, transferred successfuly. I don't know what happened exactly to the app afterwards. But here is the workaround for both the transfer of data and the possible crashes afterwards. 
That might not happen to everyone, it is just something that happened to me while transferring from the Xiaomi to Samsung.

**Comment by bigretromike** [comment]
I can't tell how its behave on phone, but as soon as you bypass windows account protection whole signal get "corrupted" maybe similar "corruptions" is happening with the "workaroud" maybe the workaround somehow hides the message while still being unable to transfer? that would make sense why It "did" transfer but end up with corrupted profile info

**Comment by krzemien77** [comment]
> Hey guys, **I'VE FOUND THE WORKAROUND**.
> 
> So after installing the app on the new device, head to **Settings → Apps → Signal → Permissions**. Usually there will be enabled only permissions for: **_Contacts and accounts_**, **_Notifications_** and **_Phone_**. What you need to do is to **enable** (for some reason) all the rest of the **"Not allowed"** category below. In my case those were: **_Photos and Videos_**, **_Camera_**, **_Location_**, **_Microphone_** and **_Nearby Devices_**. So enable all of those.
> 
> You have to do it on both the new and the old phone. The moment you do it, the phones will "recognize and find" each other and you will get the authentication numbers on screen which must be the same. You go on and press okay if the numbers are the same (should be) and the transfer will begin.

This - thank you very much Sir, much obliged.

In my case it was: SONY Xperia 5 IV -> Motorola Signature.

**Comment by imnotpoz** [comment]
> Here is the trick that made the transfer work in an instant for me: **disconnect both phones from all wifis**. I.e. wifi must be on, but you should not join any network.
> 
> I had already managed to "connect" the phones through directly going to wifi direct settings. Signal would not make the transfer though, no matter what I tried. It only worked after disconnecting both phones from the wifi.

can confirm this worked for me :3
