### ISSUE TITLE
Android Notifications not Marked as Read After Reading on Desktop App

### ISSUE THREAD

**Issue by jwildman16** [signalapp/Signal-Android#12541]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a follow-up to issue #11950. The gist: After reading a message in the desktop app, the Android application's notification remains until you open the conversation or manually mark it as read. 

Update to the previous case: 
Case #11950 comments indicated the bug occurred if a conversation had ever been bubbled before. I did not find that to be the case. I found that the bug is dependent on whether the thread is marked as a "conversation." The bug only occurs so long as the thread is a conversation. 

Example of threads shown in "Conversations" section of mobile app notifications settings: 
![image](https://user-images.githubusercontent.com/29931390/196752445-e0382d0d-64e6-48c3-bd85-56bd22c83baa.png)

If a thread has never been marked as a conversation, the mobile notification disappears as expected after the message is read on the desktop app. Additionally, removing an existing thread from the conversations section causes it to behave as desired (mobile notification disappears when message is read on desktop). You can mark a notification channel as "Not a conversation" in its settings: 
![image](https://user-images.githubusercontent.com/29931390/196752209-43b6fbd1-38c0-42b5-bc0a-532f4459032d.png)

### Steps to reproduce
- Receive a message in Signal. 
- Read the message using Signal desktop application (I am on Windows 10)
- The mobile notification remains in place after reading the message on desktop (and thereby marking it read)

**Actual result:** 
The mobile notification remains in place. 

**Expected result:** 
The mobile notification should clear once the message becomes read on the desktop. WhatsApp messages (even those marked as conversations) manage this scenario as expected (though, the mobile device usually must be unlocked before the thread updates and gets marked as read). 

### Device info
**Device:** Google Pixel 6a
**Android version:** 13 (Sep 5, 2022 security update)
**Signal version:** 5.52.5

### Link to debug log
https://debuglogs.org/android/5.52.5/377eb572b42892808d6c4ceb23e8543bea1fa72a46dded48a616a916640fd5f2
(taken while message was read on desktop, but still showing on mobile)

**Comment by mitomenai** [comment]
Notifications aren't being marked as read for me, period. I have to manually swipe them away, even after clicking on it.

Signal version 5.53.8

**Comment by cody-signal** [comment]
Are you able to do this always? I've been trying to reproduce this locally and nothing seems to work.

**Comment by jwildman16** [comment]
Yes, it seems to happen always. I just tried with another contact. I turned on custom notifications for the thread in Signal and then marked the notification channel in Android settings as priority. I then received a notification, read it on desktop, and the notification remained on my phone, including after unlocking the screen.

**Comment by cody-signal** [comment]
Looks like priority is the key, thanks

**Comment by cody-signal** [comment]
Got a potential fix in place for you for 6.2, let me know if that helps when it becomes available to your preferred update path.

**Comment by jwildman16** [comment]
I'm on 6.2.4 and just verified that the notifications are now clearing as expected! The notification even successfully cleared from the phone after reading the message on the desktop without the need for unlocking my phone's screen (it also works with the screen unlocked). Seems to be working perfectly now. 

Thank you so much for your work on this!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Me and my colleagues still have this issue on 6.18.4 jfyi

**Comment by nicholas-signal** [comment]
> Me and my colleagues still have this issue on 6.18.4 jfyi

Would you mind opening a new issue, and include a debuglog (if possible from you as well as your colleagues)?
