### ISSUE TITLE
github documentation link is an infinite loop

### ISSUE THREAD

**Issue by yardenac** [signalapp/Signal-Android#12555]
Your [README file says](https://github.com/signalapp/Signal-Android/blob/0e8a598985f00f77b0a6a4e44b80e16c4cad90ae/README.md?plain=1#L40-L43):

> Looking for documentation? Check out the wiki!
> 
> https://github.com/signalapp/Signal-Android/wiki

but the wiki is just a copy of the README. Infinite loop, no actual documentation.

**Comment by MedzikUser** [comment]
See the `Pages` menu, which is collapsed by default.

![image](https://user-images.githubusercontent.com/87065584/202293814-43971c10-c981-4ea4-993e-d330d8523c8c.png)

**Comment by alex-signal** [comment]
We're very into recursion here.
