### ISSUE TITLE
Switch to "SMS send button" possible even SMS is disabled

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#12556]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Long pressing the send button lets switch user to "SMS send button" even SMS is disabled in Signal.

### Steps to reproduce
- Disable SMS in Signal
- Long press on the Signal send button
- Button for "Unsecure SMS" appears

**Actual result:** Send button can changed to SMS even SMS is disabled
**Expected result:** Switching to SMS not possible on long pressing the send button

**Signal version:** 5.52.5+

**Comment by Tursko** [comment]
It's goes away once you click it. Pretty odd.

**Comment by cody-signal** [comment]
This is be design, you can force a chat into SMS mode. Regardless, it's being phased out with SMS removal. Right now everyone is in Phase 0 which should behave like no changes have been made. Phase 1 (will start in a few weeks) will start removing some of these types of UI elements.

**Comment by cody-signal** [comment]
There's a tweak coming in the next prod rollout starting now that'll reset everyone back to Phase 0. Some folks got a jump on Phase 1 with the last release due to a bug.
