### ISSUE TITLE
No option to migrate all messages out of Signal into standard Android SMS database.

### ISSUE THREAD

**Issue by Particpant** [signalapp/Signal-Android#12565]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There's no mechanism to export messages back to the Android SMS database, there's no way to migrate out of Signal usage without losing message history.

### Steps to reproduce
- Look for message export options

**Actual result:** No ability to fully export all conversations in Signal back to the standard Android SMS database.
**Expected result:** Full message and media history should be exportable so users can revert to non-Signal messaging without data or conversation history loss.

### Device info
**Device:** Sony Xperia 5ii
**Android version:** 12
**Signal version:** 5.53.8

I have to migrate multiple elderly relatives back to their phone's default messaging app, due to the pending removal of SMS support from Signal and there's no way to export the entire message history stored in Signal back to the Android SMS database. This means they will lose their entire Signal messaging history with their one or two extant signal contacts. For non-tech-savvy, elderly person usability reasons, it is not possible to keep Signal installed after disabling it as their default messaging app, as it will only cause confusion.

**Comment by greyson-signal** [comment]
Hi there, we provide the ability to export SMS messages out of Signal, but have no plans on writing something that would export your Signal messages into your SMS app. For feature requests, please use [the forum](https://community.signalusers.org/). Thanks!

**Comment by matthewadie** [comment]
So I start using signal because it supports SMS as well as encrypted communication, I convince a few other people to use it as well, I happily use it for years...  Then you decide to drop SMS which renders Signal useless to me and now I'm going to lose the message history sent through Signal.  

Yeah... I'm afraid that I regret ever using signal in the first place.  Moving to Element/Matrix for secure messaging is a much better option than an SMS free Signal.
