### ISSUE TITLE
Vibration keep going off when using the app if there are any unread messages

### ISSUE THREAD

**Issue by Mariusmssj** [signalapp/Signal-Android#12578]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I have any unread messages (even just one) on signal using the app keep triggering vibrations. If I enter any conversation on the app the phone vibration goes off as it if just received a message. This also happens after sending a message in any chat.

### Steps to reproduce
- Have at least one unread message in the app
- Open any conversation or reply to a message

**Actual result:** Using the app normally and messaging anyone while having a single unread message keep triggering vibration on the phone as if a new message has been received,
**Expected result:** Using the app normally should not trigger vibration (for a message that already had a notification when it was first received) when opening other messages, with an unread one being present.

### Device info
**Device:** Google Pixel 7
**Android version:** 13
**Signal version:** 6.0.6

### Link to debug log
https://debuglogs.org/android/6.0.6/595c1c6021cf5a8445fbff4a2f0864548a9677a5f80050739c732b29942f6b7e

**Comment by cody-signal** [comment]
It looks like your "other" notification channel is set to vibrate. Can you try turning that off and seeing if anything changes?

We don't do much with vibration so I'm really struggling to come up with ideas on what could be causing the problem.

**Comment by Mariusmssj** [comment]
> It looks like your "other" notification channel is set to vibrate. Can you try turning that off and seeing if anything changes?
> 
> We don't do much with vibration so I'm really struggling to come up with ideas on what could be causing the problem.

Apologies where would I find the "other" option? I tried all notification settings and also android settings as well, turning off vibration for the whole app notifications does not solve the issue.

**Comment by TheRealNox** [comment]
I have the same issue.
If I ahve an unread message, whenever I enter another chat, or I reply, the phone vibrates.
it's horribly irritating.
I'm runing Signal on the PIxel 8 Pro, Android 14, build UD1A.230803.041

**Comment by Huber1** [comment]
Could someone from the signal team please reopen this issue? The issue persists and it's really annoying.
There hasn't been any working solution yet.
Else I'd have to make a duplicate

Cheers Moritz

**Comment by nicholas-signal** [comment]
> Could someone from the signal team please reopen this issue? The issue persists and it's really annoying. There hasn't been any working solution yet. Else I'd have to make a duplicate
> 
> Cheers Moritz

Hello, please create a new issue as, after 12 months, it is likely that your issue is indeed new. Please make sure to follow the issue template.

**Comment by Mariusmssj** [comment]
My wife also is facing this issue on her pixel 6A as am I
