### ISSUE TITLE
After deleting given message with picture, the thumbnail remains until the window is closed

### ISSUE THREAD

**Issue by Vividious** [signalapp/Signal-Android#12571]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If someone sends a picture and there is direct reply to such message, picture thumbnail connected with that response remains until window is closed.

### Steps to reproduce
1. Person A sends a picture 
2. Person B replies with "answer" option (keeping the conversation window open)
3. Person A deletes the message

**Actual result:** Person B does not see the direct message however the thumbnail is still present
**Expected result:** Person B should not see either original photo or its thumbnail

### Screenshots

Screen 1/3 (receiving picture msg)
<img src="https://user-images.githubusercontent.com/34356490/199281592-3e1184d2-b240-4a03-841b-c176e5b5ce47.jpg" width="200">
Screen  2/3 (responding to it)
<img src="https://user-images.githubusercontent.com/34356490/199281597-8b07ebef-6482-4283-a1cb-f98560451a2e.jpg" width="200">
Screen  3/3 (msg is deleted, thumbnail still exists)
<img src="https://user-images.githubusercontent.com/34356490/199281603-cb088fe8-c24c-42e0-9a07-d844a953beda.jpg" width="200">

### Device info

**Device:** Samsung Galaxy S21 5G (Exynos)
**Android version:** 12
**Signal version:** 5.53.8

**Comment by Vividious** [comment]
Hey @cody-signal !
I am expecting the thumbnail to go away at the exact moment Alice deleted it.

Screen 1/3 (receiving picture msg)
<img src="https://user-images.githubusercontent.com/34356490/199281592-3e1184d2-b240-4a03-841b-c176e5b5ce47.jpg" width="200">
Screen  2/3 (responding to it)
<img src="https://user-images.githubusercontent.com/34356490/199281597-8b07ebef-6482-4283-a1cb-f98560451a2e.jpg" width="200">
Screen  3/3 (msg is deleted, thumbnail still exists)
<img src="https://user-images.githubusercontent.com/34356490/199281603-cb088fe8-c24c-42e0-9a07-d844a953beda.jpg" width="200">

**Comment by cody-signal** [comment]
Thanks for the clarification. So quotes/replies are conceptually closer to copy/paste than a direct reference to a previous message. So by quoting you are actually making a copy of Alice's message and including that in your message. What Alice then does with her original message is completely independent of yours.

The app is behaving as designed.
