### ISSUE TITLE
"Add as a contact" not functional for user without known phone number

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#12570]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal shows the option "Add as a contact" for Signal contacts whose phone number is not known.

### Steps to reproduce
- Someone added a Signal user to an existing group
- That new group member did not send any message
- I can see the new group members profile name but not their phone number

**Actual result:**
- Going to the contact's details page, Signal shows the "Add as a contact" option
- Doing that, a new contact with custom name is created, but without any phone number
- There is no connection to the Signal contact, Signal does not display the custom contact name

**Expected result:**
- Signal should not show that option

### Screenshots
![SignalAddContact](https://user-images.githubusercontent.com/3845150/199218001-17c38df0-b7f9-4ce0-bbf9-6a5400aa70dc.png)

### Device info
**Android version:** 13
**Signal version:** 6.0.6

**Comment by cascheberg** [comment]
This issue still exists in current Signal version 6.6.3

**Comment by devurandom** [comment]
6.11.7 also still has the problem.

The issue also happens outside of group chats: when a user without phone number sends a message request (writes to you first), you will see them in your conversation list, you can open the conversation to view their messages, you have "add to contacts" in the three-dots-menu (there is no such button in Signal-internal contact page, the one where you configure "disappearing messages" and "chat color", which you open by tapping their name at the top above the conversation, which usually also contains an "add to contacts" button), but if you press that button and create the contact, the name in Signal does not change and the contact in your address book shows no sign of being linked to Signal.
