### ISSUE TITLE
group chat does not disappear in overview even last message is deleted

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#12576]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Group chat doesn't disappear from overview when last message in the chat is deleted.
In the overview the group chat shows last message.

### Steps to reproduce
- delete all messages in a group chat

**Actual result:** Group chat doesn't disappear from overview when last message in the chat is deleted.
**Expected result:** Group chat disappears from overview, at least the last message shouldn't be shown in the overview

### Screenshots

![Screenshot_1667502078](https://user-images.githubusercontent.com/49990901/199812229-48498f1b-34f2-482f-9077-ceb8146abb46.png) ![Screenshot_1667502087](https://user-images.githubusercontent.com/49990901/199812234-755cdabe-16b3-41e5-aa7c-853f864d01df.png) ![Screenshot_1667502093](https://user-images.githubusercontent.com/49990901/199812238-f1d33612-a1e0-4efd-99e1-2f5d0a4bd71f.png)

![Screenshot_1667502859](https://user-images.githubusercontent.com/49990901/199813828-d687b064-044b-4b59-b478-fc4a0b0a5bf0.png) ![Screenshot_1667502863](https://user-images.githubusercontent.com/49990901/199813852-ff72a032-c7db-4c0c-ab8c-342ad49636ef.png)

### Device info

**Device:** Virtual Device
**Android version:** 12
**Signal version:** 6.1.0

### Link to debug log
https://debuglogs.org/android/6.1.0/4d006da3574312d89a9a50dd433ea2f6c856ec8bd255a6887e091fa26bd8d48e

**Comment by Sgn-32** [comment]
Tested with some other groups. Issue is only when the group as additional set a group story. (Not necessary with recent update)

![Screenshot_1667576748](https://user-images.githubusercontent.com/49990901/200018830-6d0721bc-4d5f-42ac-b5c8-ca93d1a74a3f.png) ![Screenshot_1667576763](https://user-images.githubusercontent.com/49990901/200018835-cff1b678-b775-47f7-8eb5-5fea3f5cd779.png)
![Screenshot_1667576772](https://user-images.githubusercontent.com/49990901/200018837-575d5295-4181-44a8-a9f4-4f395c0e14bf.png) ![Screenshot_1667576779](https://user-images.githubusercontent.com/49990901/200018840-2765eb16-0a52-4b01-a319-0896de0b59e0.png)

**Comment by cody-signal** [comment]
Thanks for the follow up. I can't reproduce this. I think you much have some message associated with that group that is keeping the thread from being deleted but also won't render in the chat.

I've tried a few combinations of things and I cannot reproduce this. Are you able to reproduce this with a fresh group or other groups?

**Comment by Sgn-32** [comment]
On second try, I was able to reproduce it.
1. Created a new group (with 2 members)
2. sent some messages
3. created a group story for this group
4. posted a text story
5. deleted the messages in the group chat
6. the group chat doesn't disappear in the conversation list
7. to shorten the 24 lifetime of the text story, deleted the text story for everyone
8. group chat still not disappears even group chat and group story are empty

While testing found another issue that posting to a group story isn't possible if group chat is empty.
The group story isn't displayed in the selection screen.

**Comment by cody-signal** [comment]
Ah, the remote delete story is actually key it seems. Since it's tombstoned in the db instead of being deleted it keeps the thread around as the message count > 0. Looking into it. Did you report the other story issue you found separately or just here?

**Comment by Sgn-32** [comment]
But what cached the last deleted message?
I've send "message 1" then "Message 2" and deleted it reverse "message 2", then "message 1" and returned then in the overview.
Here is see "message 1".
Since there are some feature request out there to not delete/disappear empty chat, how about to show "no message" or similar.

> Did you report the other story issue you found separately or just here?

Just here. Should i open a new issue number for it?

**Comment by cody-signal** [comment]
When you delete, we update the thread record where the snippet shown in the conversation list lives. So delete 2, will update it to show 1. And then deleted 1 won't update it because it thinks there's no message to use for the snippet. But the thread stays around because of the story associated with it.

No need, I'll pass it on to the team.

**Comment by Sgn-32** [comment]
I believe that was fixed some version ago.
