### ISSUE TITLE
Some shared links fail to send when dissapearing messages are enabled by default but not in chat

### ISSUE THREAD

**Issue by 31j** [signalapp/Signal-Android#12577]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes, when sharing some links with link preview from a Reddit client (infinity) to Signal, the links fail to send. The link must either be sent again without the link preview OR the message needs to be deleted and the app restarted before manually pasting the link with the link preview to send. This issue only effects certain links, e.g. sending a DDG link with a query attached is fine but a reddit one is not

This issue specifically occurs when the default timer for messages is set to something other than None, but the chat is set to None. This also produces some other quirks when sharing, for example after sharing the chat appears like a new chat with a new contact despite there being previous message history and only restarting the app rectifies it. 

Setting the default message timer to None OR changing the chat's timer to anything but None avoids both of these issues. The first issue can also be avoided by disabling link previews. 

### Steps to reproduce
- Enable a global default for the dissapearing messages (mine is 1 week)
- Share link from Reddit app to Signal, Select a contact that you disabled dissapearing messages with
- Wait for the link preview to appear before hitting send
- There appears to be some other issues here with having to restart the app to see their responses and past messages 

Note: I must be missing something since *sometimes* it works but usually it doesn't. There might be some other condition that I have yet to notice to recreate this. 

**Actual result:** Upon restarting the app to actually see the messages, the message is not sent. When using the resend button the message continues to fail. Copying the link and sending it as a new message with link preview also fails unless the previous message is deleted and the app restarted
**Expected result:** The message is sent 

### Screenshots

![signal-2022-11-03-193919_002](https://user-images.githubusercontent.com/32624322/199856205-72f3e45a-bbf8-4c62-acb2-22bc52d870ef.jpeg)
In the image above there should be previous message history displayed. If the chat has a message timer (even if it isn't the default) it works fine, otherwise it displays like this as if it's a message to a new contact

![signal-2022-11-03-194126_002](https://user-images.githubusercontent.com/32624322/199856209-fb6e4aad-3f1a-4fc8-bd3c-407baacaa773.jpeg)

### Device info

**Device:** Samsung Galaxy Note 9
**Android version:** 10 - 1 June 2022 Security patch
**Signal version:** 6.0.6

### Link to debug log

https://debuglogs.org/android/6.0.6/f6709f3aa3bf4131751b9a78eec2bf997de19e31cd22a0d722bf93382113060c

**Comment by cody-signal** [comment]
Thank you for the detailed and complete report. We'll take a look.
