### ISSUE TITLE
Signal sustainer payment issue

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#12572]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm located in Poland and wanted to become a Signal sustainer with a star badge, but the transaction fails repeatedly.

### Steps to reproduce

- Be located in Poland and use PLN as the default currency for transactions
- Try becoming a Signal sustainer with a star badge (pay with Google Pay)

**Actual result:** Two 1$ transactions show up as declined in Google Pay.
**Expected result:** One transaction for 12PLN (~3$) is made.

### Screenshots

N/A

### Device info
**Device:** Redmi Note 9 Pro
**Android version:** 12.0
**Signal version:** 6.0.6 (beta)

### Link to debug log

https://debuglogs.org/android/6.0.6/b94a04c9f1f5acf604882ee7829a5a6acb34cb878d58842935b106c8054a0a4d

(I tried to make a payment at 16:25)

**Comment by lanz** [comment]
You shouldn't become a sustainer anyway now that they're ignoring user feedback and dropping SMS support.

**Comment by Kwasow** [comment]
@lanz I don't think this is something that should be discussed here, and it is my own decision about what I value about the app :))

**Comment by cody-signal** [comment]
Thanks for lettings us know, passing it on to our donations guy.

**Comment by cody-signal** [comment]
Doing a quick glance through the logs, it looks like the CVC/security code is incorrect. Can you double check your card details in google pay?

**Comment by Kwasow** [comment]
I've double-checked, and it seems it was actually an error on my end. My card expired recently, and I thought I updated the details in Google Pay, but it seems that something didn't actually work correctly. I deleted the card and re-added it - now everything works fine. Thank you for your time! Maybe it would be possible to show a more useful error message in the future?
