### ISSUE TITLE
List of shared media always scrolls starting at beginning to selected image when switching images

### ISSUE THREAD

**Issue by niels-beier** [signalapp/Signal-Android#12582]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When switching between pictures on the shared media page of any contact the small previews at the bottom always start scrolling at the beginning to the selected picture instead of going only one instance to the left or right.

### Steps to reproduce
- Click on any contact (best visible when many pictures have been sent in the conversation.
- Go to the shared media page of that conversation
- Select any image
- Swipe left or right to switch between images

**Actual result:** The small preview of the pictures at the bottom always scroll from start to the selected image.
**Expected result:** The preview scrolls from the last selected image to the new selected one.

### Screenshots

https://user-images.githubusercontent.com/43962032/200132793-6c09b31a-3591-475a-af98-4a7cf0426b8c.mp4

### Device info

**Device:** Samsung Galaxy S21
**Android version:** 12.0 Security patch level 2022-10-01 (One UI 4.1, Build Number: G991BXXS5CVIF)
**Signal version:** 6.0.6

### Link to debug log

https://debuglogs.org/android/6.0.6/861e3cd04c0770f01d355aa3e6c508c2844a1389eddc18bf24713f3a5d34f36e

**Comment by cody-signal** [comment]
We made some tweaks to this in 6.1 and I think fixed it. Can you try again when that's available for you? It's currently in beta.

**Comment by niels-beier** [comment]
Still appearing on 6.1.4, so nothing changed.
