### ISSUE TITLE
Signal activates proximity sensor when playing voice messages

### ISSUE THREAD

**Issue by yukina3230** [signalapp/Signal-Android#12587]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I play a voice message, sometimes the screen goes off. I noticed it was because the proximity sensor was activated. I tried covering the sensor while playing voice messages and when the screen turned off, the volume also changed too. I think this is a bug because the proximity sensor should only be activated when calling, not when texting.

### Device info
**Device:** Xiaomi Mi 11 Lite 5G
**Android version:** 12
**Signal version:** 6.0.6

**Comment by greyson-signal** [comment]
Yes, this is intended. Specifically, the idea is that if you play a voice note, and hold the phone up to your ear, it will play through the earpiece as if you were on a call.

**Comment by venelin98** [comment]
I find this feature very annoying, as I often want to scroll or write while listening, but the screen turns off.

It would be great if it was possible to disable the proximity sensor during voice messages in the settings

**Comment by wertzuz** [comment]
Other messengers do the same it still feels smoother in other apps so I think its more like a timeout sensitivity issue so it does not activate accidently so often.
