### ISSUE TITLE
Signal asks for location permission which has already been granted (Huawai device)

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12581]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Someone I know has a Huwai device and was trying to transfer their Signal account to a new device. When following the transfer steps at some point Sinal says location permission is required. If you tap continue the Huawai setting for the Signal app are opened with at the top a slide button for "location". But that permission is already enabled. If you go back to Signal Signal still says location needs to be granted first.

The problem appears to be that Signal also wants a certain type of location permissionbehivh includes wifi. Signals text does not explain this, but if you have a good look at the hiawai settings screen for the Signal app you will see it has multiple settings and one of those has to be changed for Signal account transfer to work. (Or to promp that your device does not support wifi direct).

Signal does not clearly tell the user what it needs, leading to an experience in which Signal seems to not be wirking properly. It ask a permission it already has, but means something else.

### Screenshots

Maybe I can get a screenhot if this later

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0 maybe I can get this info later
**Signal version:** 6.0.4

### Link to debug log

Maybe I can get a debug log later

**Comment by nicholas-signal** [comment]
Please submit a debug log if you would like us to investigate this issue. Full disclosure: it is often difficult to diagnose device-specific issues, especially ones on devices that are not receiving OS updates from the manufacturer.

**Comment by aaguilera** [comment]
I had this same issue. I solved it setting up the location services in Android configuration, switching from "battery saving" mode to "accuracy" mode. After that, Signal stopped asking for location services permission and it detected my other phone.
