### ISSUE TITLE
app gets stuck when trying to open a "story" 

### ISSUE THREAD

**Issue by ggrrll** [signalapp/Signal-Android#12596]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

app gets stuck when trying to open a "story" , from the recently added 'stories' tab and I need to restart the app 

### Device info

**Device:** Xiaomi Mi A2
**Android version:** API 29
**Signal version:** 6.0.6

### Link to debug log

https://debuglogs.org/android/6.0.6/d0f904641912bd5881256db9a787a8d5d50c6537f86738d527f2c65cacb51f5a

**Comment by greyson-signal** [comment]
This is fixed in 6.1.x, which is rolling out to production.
