### ISSUE TITLE
Chat messages do not show up on bad internet

### ISSUE THREAD

**Issue by user1027** [signalapp/Signal-Android#12590]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversations in a group chat in which I'm trying to send a message when I have spotty connectivity, do not load if I try to view the group messages after I've gone to the main view.I can't reproduce the bug using airplane mode. Maybe the app behaves weirdly when it thinks it has interner but it doesn't.

#11680 is somewhat similar as in the interface loads but not the contents but I don't know

### Steps to reproduce
- Have EDGE connectivity (i.e. bad, slow and not reliable. Note that I was underground)
- Send a message to a large Signal group.
- Message doesn't get sent due to bad connectivity
- Go to the main screen where all the conversations are listed
- Press on the chat you just sent a message to.

**Actual result:** After entering the chat for the 2nd time, a blank screen with no messages is shown, even though the group name and picture can be seen in the apropriate place (the top).
**Expected result:** Old messages and messages in process of being sent are shown.

### Screenshots

Can't give any screenshots unfortunately

### Device info
**Device:** Pixel 4a
**Android version:** 13
**Signal version:** 6.0.6

### Link to debug log
https://debuglogs.org/android/6.0.6/8627c53494e12633ef104d66b6f2eae9d2cc9a71ba57e8c04a055eec17a11e1d
Note that because my internet connection was not reliable, I tried to submit the debug log several times, so there's lots of errors of that too

**Comment by greyson-signal** [comment]
This is addressed in 6.1.x, currently in beta
