### ISSUE TITLE
Default carrier for "unsecure SMS" in case of multiple SIMs

### ISSUE THREAD

**Issue by bojanlikar** [signalapp/Signal-Android#12599]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- I use Signal on Android phone with two SIM cards - one "physical" and one eSIM. For my preferred call (not relevant) and "insecure SMS" I use a carrier with eSIM.
- When I try to reply on a "insecure SMS" received on eSIM (preferred carrier) Signal app tries to send the first reply on "physical" SIM (not preferred) carrier
- When I try to send a new "insecure SMS" even to a person who's phone number is associated with the preferred carrier (based on the country code) Signal app selects "physical" SIM (not preferred) carrier
- if I long press plus sign right from the text input field I can select the preferred carrier and send the "insecure SMS" using that carrier. Everything works OK

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I just think it would be helpful if you would check "preferred" carrier in case of multiple SIMs and offer:
- preferred carrier in case new "insecure SMS" conversation is started by me
- when I receive an "insecure SMS" in a new conversation Signal should use the same carrier that "insecure SMS" was received from for sending the reply

### Device info

**Device:** Pixel 7
**Android version:** 13
**Signal version:** 6.0.6

**Comment by greyson-signal** [comment]
I'm closing this because we're going to be removing SMS support in the near future.
