### ISSUE TITLE
Transfering to new Android device fails midway 

### ISSUE THREAD

**Issue by WildPenquin** [signalapp/Signal-Android#12593]
- [X] I have searched open and closed issues for duplicates (possible duplicate(?) #12411 )
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Transferring to a new android device fails midway, after both phones have started reporting an in-progress transfer of messages.
The symptoms include the old device just exiting to the settings page midway, and the new phone waiting for the old phone indefinitely. **More crucially, I got twice a misdetected success on the old phone!** Luckily I tapped on "cancel, keep using Signal on this device" (not sure, but one might got locked out in case they tap the wrong option here)?.

The transfer in my case was from OP3T (Signal 6.0.6) to Fairphone 4 (Signal 6.0.6). Both phones have the android power saving settings at default, which was in my case the issue. The display will switch off after 30 seconds of inactivity *per default* on Android. I **presume** after a while Android puts signal on the background, since if I leave both phones in this state and re-open them after a while, I can see the transfer is in progress. But in case I'm not constantly "re-awaking" the phones, the transfer will eventually fail! The transfer will take a relatively long time (over 10 minutes) if a user has a lot of messages - in my case, ~20k (I believe).

As a workaround, I needed to set both phones automatic "turn off display" to maximum, 30 minutes, and still sit trough the whole process to make sure it does not take more than 30 minutes, to "stimulate" the phones so that they will not turn off display to save battery.

While troubleshooting this, I disabled all battery optimization settings I could find, however that did not help to work around the issue. I needed to "force" the displays of both phones to stay lit.

### Steps to reproduce
- Have an "old" and a "new" android device, the old one having a Signal account with loads of messages
- Start transfer from "old" to "new" as per application instructions

**Actual result:** The transfer fails midway. Sometimes the old phone reports "success", despite the new one does not.

**Expected result:** The transfer should succeed, as long as the user does as in the instructions; i.e. they don't close signal.

The transfer should work with stock Android settings or even with more conservative power-saving settings, including automatic display power-off. If this can not be achieved, the user should be notified, and forced to (temporarily) set the automatic display power saving to maximum setting.

The "old" device should **never** report a success in case the new one does not report a success (this happened to me twice with failed transfers, but this could also be a separate issue; there seem to be too little safeguards / too lax assumptions in the code from the "old" device POW).

**Device:** Oneplus 3T -> Fairphone 4
**Android version:** OP3T: latest OTA / FP4: Android 11 (latest OTA)
**Signal version:** 6.0.6

**Comment by greyson-signal** [comment]
Hi there, can you please provide [debuglogs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)? At least from the new device, but both devices would be helpful. Thanks!

**Comment by WildPenquin** [comment]
Hi,

Here is a log from the OP3T after  a failure. I also noticed (and forgot to mention), that Signal does not find the new device at all after a failure. Disabling an re-enabling WiFi, it can detect the device again. The log: https://debuglogs.org/android/6.0.6/79174958a4d07eeb16e7ee7d7b9ec0ea935c84db8cb78eb8e9b72a000d2c3c64

From the FP4: https://debuglogs.org/android/6.0.6/560640e87ce44d69673b62ece829e9d4a33ce47baacebfae6dd04f5261433329

**Comment by staticdev** [comment]
I am having same problem on Fairphone, it doesn't see the old phone.
