### ISSUE TITLE
Signal freeze when I touch a Story

### ISSUE THREAD

**Issue by Matzeeee** [signalapp/Signal-Android#12594]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal freeze when I touch a Story

### Steps to reproduce
- start Signal
- touch Storys
- touch my Story  or the Signal Story
- the Help screen with Gestures appears and Signal freezes and is not responding.

**Actual result:** Signal freeze. The Android Apps/Back buttons are not workking. Only the Android Home Button works. I have to kill the Signal App.
**Expected result:** show Story

### Screenshots

![image](https://user-images.githubusercontent.com/60921150/200620351-5939d460-50d1-41f5-b450-d4ba64651439.png)

### Device info

**Device:** Samsung Galaxy A51
**Android version:** 12
**Signal version:** 6.0.6
Android and all Apps are uptodate.

### Link to debug log

https://debuglogs.org/android/6.0.6/320a9fbd9f5fef7d43d05bca294c06e131f0e24d274b3b6265229283ea0b8c39

**Comment by dewtoujii** [comment]
Had the same issue. For me it was due to disabled animations in the dev options (See Screenshot). After setting them to "1x" the help screen can be closed. Animations can be disabled again after this.

![Screenshot_20221108-194820_1](https://user-images.githubusercontent.com/13303798/200650551-1b69b511-f5e0-4aa3-aad8-8fa317fada2b.png)

**Comment by Matzeeee** [comment]
Yes!
Activating the Option solves the Problem.
The helpscreen is animated now and can be closed.
Thanks.

**Comment by greyson-signal** [comment]
This is fixed in 6.1.2 (going to beta, prod shortly). Thanks!
