### ISSUE TITLE
Signal messages fail to send when Instabug is blocked by app privacy protection

### ISSUE THREAD

**Issue by lanz** [signalapp/Signal-Android#12607]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using the DuckDuckGo Privacy Browser app to block app trackers. This app prevents other apps from sending personal data to Facebook, Google, Adobe, Urban Airship, Amplitude, and other ad platforms. It also prevents data from being sent to platforms like Bugsnag and Instabug.

The DuckDuckGo Privacy Browser keeps reporting that Signal is attempting to send my data to Instabug. However, when the DuckDuckGo Privacy Browser app is enabled and blocking Instabug requests, none of my Signal messages will send. Signal will only send messages if I disable the DuckDuckGo Privacy Browser app and allow my data to be sent to Instabug.

Sending Signal messages shouldn't trigger any data to be sent to Instabug. Secondly, there should be an option in the privacy settings to prevent Signal from sending data to Instabug.

### Steps to reproduce
- Install DuckDuckGo Privacy Browser
- Enable the "App Track Protection" feature
- Attempt to send a Signal message

**Actual result:** Signal messages fail to send.
**Expected result:** Signal should still send messages even if app tracking protection is preventing Signal from sending data to Instabug.

### Screenshots
![signal-2022-11-14-174251_002](https://user-images.githubusercontent.com/56061103/201792765-d7112077-3d88-4876-9f6a-9ad644a03069.jpeg)

### Device info
**Device:** OnePlus 9 Pro
**Android version:** 12
**Signal version:** 5.53.8

**Comment by greyson-signal** [comment]
Very unclear why this would be happening, considering we most certainly _do not_ use Instabug. Signal has no analytics or reporting whatsoever. This can be verified by looking at the source, and you can verify we're shipping what's on Github via our [reproducible builds](https://github.com/signalapp/Signal-Android/tree/main/reproducible-builds).

This makes me wonder if you're unknowingly using an unofficial version (a debuglog would help us confirm that), or if DuckDuckGo is throwing false positives for some reason.

**Comment by MedzikUser** [comment]
I use App Tracking Protection and I haven't noticed it ever blocking anything from Signal app.

**Comment by MedzikUser** [comment]
btw latest Signal version is [v6.2.3](https://github.com/signalapp/Signal-Android/releases/tag/v6.2.3)
