### ISSUE TITLE
can’t record video, only photo

### ISSUE THREAD

**Issue by erik55** [signalapp/Signal-Android#12605]
On my Samsung S6 with Android 7 I can't record a video inside Signal. 

Steps: 

1. Click on camera symbol 
2. Long press on record button (which should start recording a video)

What happens: A photo is taken immediately. 

What is expected: A video recording should be started. A photo only for short taps/clicks. 

https://debuglogs.org/android/6.2.1/e310171d7e17e4acc4d934e08c246fd0edf3fa838aace031a66081505b42dff4

**Comment by bme13** [comment]
Hi, It seems video capture is only supported from API 26 onwards and memoryFileDescriptor is available. See e.g. #9117. In your logfile this is mentioned:  CameraXFragment: Video capture not supported. API: 24, MFD: false, Camera: 0, MaxDuration: 60 sec
