### ISSUE TITLE
App carsh when signing in if google play services SMS permission denied 

### ISSUE THREAD

**Issue by Waa11a** [signalapp/Signal-Android#12606]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description.
The app immediately crash after I click "OK" in the "is your phone number above correct?" Dialog if Google play services SMS permission is denied.

### Steps to reproduce
- Deny google play services SMS permission
- Download signal from google play
- open the app and allow all permission, type your phone number and click "OK"

**Actual result:** The app immediately crash
**Expected result:** the app shouldn't crash

### Device info

**Device:** Vivo V23e 5G
**Android version:** 12
**Signal version:** 6.1.4

**Comment by Waa11a** [comment]
> Can you please submit a log? You can get one during registration if you tap the header text at the top of any registration screen 8 times. Thanks!

Of curse
https://debuglogs.org/android/6.1.4/c3e8c9f575b5b8f7ea53d863e93c5327d2f836922e904afe3a0598b8b3e936c7
Hope this help

**Comment by greyson-signal** [comment]
Ah, thank you. This is fixed in 6.2.x, which is currently in beta and will be going to production within the next few days. Thanks!
