### ISSUE TITLE
Signal froze first time I opened after the story feature got enabled

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#12603]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I opened signal, clicked on the Stories button on the bottom, got presented a howto screen, and there signal froze. I could not go in any directions. Fortunately, after force closing the application correct behaviour was restored and I can use the messaging again.

Debug log: https://debuglogs.org/android/6.1.4/2da7cfb915de6349b824b4ee4b984c2a15450f4977c439a198336b433ccc7d9c

**Comment by alex-signal** [comment]
Hi! Did you have animations disabled?

**Comment by szotsaki** [comment]
Yes I did; spot on! :)
