### ISSUE TITLE
UX: Stories from (long) video

### ISSUE THREAD

**Issue by neurer** [signalapp/Signal-Android#12600]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sorting of story elements made from long videos is confusing.

### Steps to reproduce
- Post a video that is 1 minute long
- Video is split into two stories
- Edit the story and touch the first element in the list.

**Actual result:** The first element in the list is the second part of the split video.
**Expected result:** The first element in the list to be the first part of the split video.

**Current sorting**
- End of split video
- Beginning of split video

**Desired sorting**
- Beginning of split video
- End of split video

### Screenshots

![Signal_Stories_Screenshot_20221111](https://user-images.githubusercontent.com/6098965/201382096-64fbedb8-97b0-443c-a66e-dcee6d81f606.jpg)

**On a sidenote**: Videos start muted for me. An indicator would be helpful.

Other than that. Very interesting feature!

**Comment by greyson-signal** [comment]
Yeah, we split videos into 30sec chunks, that's expected.

And the "My story" list shows items from newest-oldest, so counter-intuitively the split videos will appear in reverse order, but this isn't unexpected.

Regarding videos starting muted, this is a common thing story-apps do. Audio will be enabled if you hit the volume switch. But I agree it would be good to add some indicator.

Thanks!
