### ISSUE TITLE
Message search function does not work properly

### ISSUE THREAD

**Issue by maxcom1** [signalapp/Signal-Android#12602]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to search for all messages with a given content - e.g. "x", to for example find any of the oldest messages with this content or see the total number of those messages only displays me the last 500 messages, which makes it very difficult.

### Steps to reproduce
- enter the conversation (chat)
- open message search function
- in the search field, type wanted content

**Actual result:** Only the last 500 messages are shown
**Expected result:** All messages that contain the search phrase should be shown, otherwise it's a hindrance

### Screenshots
![image](https://user-images.githubusercontent.com/46265094/201498418-e6c412c4-adbd-46ce-bfbf-13f863e21310.png)

### Device info
**Device:** Samsung Galaxy A52 [SM-A525F] (also Samsung Galaxy S20 FE, Samsung Galaxy S22, Realme 9..)
**Android version:** 12
**Signal version:** 6.2.1

**Quite importantly:** this bug occurs on more than one device and does not need special circumstances

**Comment by MedzikUser** [comment]
I think this limit is causing the issue.

![image](https://user-images.githubusercontent.com/87065584/201517616-eb05a13c-3f9a-4e53-a68b-e8e61c7c5514.png)

**Comment by greyson-signal** [comment]
Indeed, we currently limit it to 500 results for performance reasons. The thinking being that if there are more than 500 results, you probably have to make your query more specific to be useful anyway. Might be something we can look into in the future, but tbh even SQLite FTS has it's limits when it comes to perf.

**Comment by maxcom1** [comment]
> Indeed, we currently limit it to 500 results for performance reasons. The thinking being that if there are more than 500 results, you probably have to make your query more specific to be useful anyway. Might be something we can look into in the future, but tbh even SQLite FTS has it's limits when it comes to perf.

Well, how about at least increasing the limit or adding a similar option to the ability to limit the number of messages stored?
Because performance is not the reason, these 500 messages load in some very small fraction of a second, and the search function is not used all the time - only for specific purposes (which are hindered by the limit), so the impact on performance would probably be zero or very marginal, unnoticeable.
