### ISSUE TITLE
Renaming contacts in signal (or android contacts) then refreshing reverts the rename

### ISSUE THREAD

**Issue by alv53** [signalapp/Signal-Android#12621]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a contact on my android phone (the name has an emoji if that is relevant). Renaming contacts appears to be broken, as Signal keeps renaming the contact to the old name (somehow finding a non-existant contact). Steps taken to try to resolve
- Remove and re-enable contacts permission in android settings
- Restoring signal from a backup
- Clearing cache for android contacts
- Checking that the contacts are not in the SIM card (they are in the synced google account on my device)
- Re-installed signal from scratch WITHOUT backup (losing all chat history 😢. But I did restore to a backup to get that back in the meantime)

Some other notes:
- Haven’t looked at the signal source code or the debug log at all, but I’m curious if this issue stems from the old contact name having an emoji in it? I can rename other contacts that do not have emojis fine.
- Tested this with the other person’s iphone (who also has emojis for me in their contact name). This issue can not be reproed on iphone, so likely android specific.

### Steps to reproduce
When I try to rename the contact from my android contacts (synced to google account) or directly from signal (clicking on contact photo -> Contact details -> edit)
- The contact is renamed
- However, if I then refresh my contacts in signal (compose a new message, swipe down), the following happens:

**Actual result:** New contact name disappears, old contact name which is no longer in my android contacts re-appears.
**Expected result:** New contact name remains.

### Screenshots
- [Chat with old contact name “PA ND 🥑”](https://user-images.githubusercontent.com/4079116/202895001-60fbe15f-b1d8-4fdb-9b95-dccc4c661107.png)
- [Contact renamed in EITHER android contacts or via signal contact details](https://user-images.githubusercontent.com/4079116/202895039-aa10fd00-6937-4b04-be9b-b857e3440a4c.png)
- [Signal chat reflects name change](https://user-images.githubusercontent.com/4079116/202895060-24565ff6-191f-46df-8d18-9e6701948ebd.png)
- [Signal contacts list has new name](https://user-images.githubusercontent.com/4079116/202895074-aeb951a5-dce8-4737-a0f3-9c0d390e114e.png)
- [Refreshing contacts list (pulling down) deletes new name, and shows old name. This diverges from my android contacts list now.](https://user-images.githubusercontent.com/4079116/202895087-3b55a606-17c3-462a-876b-80ec2c6402b0.png)
- [Chat now displays the old contact name (no longer synced to android contacts).](https://user-images.githubusercontent.com/4079116/202895142-058f7b05-2c72-46cc-bacd-d859b21ac7db.png)
- [Contact details shows an empty contact for the old name](https://user-images.githubusercontent.com/4079116/202895168-2d8650e6-5600-451a-ab5d-312dfd854ce7.png)

### Device info

**Device:** Samsung S20
**Android version:** 12
**Signal version:** 6.2.3

### Link to debug log
https://debuglogs.org/android/6.2.3/e7a440c9d1ef3fb5e77702da8e7a5149b6c2c08602f65c175819b64f66bf6e24

**Comment by alv53** [comment]
Haven’t looked at the signal source code or the debug log at all, but I’m curious if this issue stems from the old contact name having an emoji in it? I can rename other contacts that do not have emojis fine.

**Comment by alv53** [comment]
Tested this with the other person’s iphone (who also has emojis for me in their contact name). This issue can not be reproed on iphone, so likely android specific.

**Comment by greyson-signal** [comment]
Contact data on android is pretty complicated. If we're showing the old name, that means that there _is_ an entry in the system contact database for that name attached to that contact. My guess is that for a single contact, there's actually _two_ name entries for it, and we do our best to choose the latest one, but there's no way to _guarentee_ it's the latest. 

I'd try downloading some alternate contact apps from the play store and see if the old entry is showing up anywhere. Maybe Simple Contacts or the Google Contacts app?

**Comment by alv53** [comment]
Hi @greyson-signal, thanks for the reply! Google Contacts did not help, but Simple Contacts was able to find three duplicate entries for this particular contact. The problematic one appeared to have been associated with WhatsApp. Deleting it and then refreshing contacts in signal fixed the issue.

**Comment by greyson-signal** [comment]
Great to hear!

**Comment by hemsagarelugu** [comment]
Yes , Simple contacts helped to fix this issue.

**Comment by hemsagarelugu** [comment]
> Hi @greyson-signal, thanks for the reply! Google Contacts did not help, but Simple Contacts was able to find three duplicate entries for this particular contact. The problematic one appeared to have been associated with WhatsApp. Deleting it and then refreshing contacts in signal fixed the issue.

This worked
