### ISSUE TITLE
Desktop client

### ISSUE THREAD

**Issue by jondo** [signalapp/Signal-Android#1263]
It would be great to have TextSecure desktop clients for Windows/Mac/Linux. Of course that's not a priority compared to the mobile apps - but would that be feasible at all?

**Comment by nerdoc** [comment]
Just wanted to add: the link from @generalmanager to the support forum is dead. Where can I get info about the desktop client?

**Comment by generalmanager** [comment]
I guess you could just open a new question in http://support.whispersystems.org/hc/en-us/sections/202686357-Other-Devices-and-Platforms

Am 9. November 2015 00:30:52 MEZ, schrieb "Christian González" <notifications@github.com>:

**Comment by jonathancross** [comment]
FYI:
https://github.com/WhisperSystems/Signal-Desktop
