### ISSUE TITLE
ENTER key on AOSP is overwritten by Emoji selector icon when "Use system emoji" is active

### ISSUE THREAD

**Issue by yveggie** [signalapp/Signal-Android#12639]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Related issue
https://github.com/signalapp/Signal-Android/issues/12638#issue-1466319831

### Bug description
When the option to use system emoji's is active, the ENTER key on Android Keyboard (AOSP) is replaced with emoji selector icon.

### Steps to reproduce
- To activate "Use system emoji": Signal Main Screen > Settings > Chats > section Keyboard > check "Use system emoji"
- In text input area, select Android Keyboard (AOSP)
- No ENTER key is available on the keyboard. The place where I would expect it shows - and functions as - an emoji selector.

**Actual result:** Keyboard with Emoji icon selector in the place of the ENTER key
**Expected result:** Keyboard with ENTER key in place

### Device info
** Device: Fairphone FP2, OS build 22.10.0-rel.0
** Android version: 10
** Signal version: 6.2.3

**Comment by greyson-signal** [comment]
It looks like we do add another keyboard hint when "use system emojis" is enabled, but I can't get it to actually change the keyboard behavior on any of my devices. Is the keyboard you use installable via the Play Store? Could you send us a link?

**Comment by yveggie** [comment]
It's the keyboard that comes with Android 10, I think. All other keyboards need to be installed, this one is there by default.
This is an Android tweaked to work on the Fairphone 2, which is relatively old. Perhaps that has something to do with it?
Before I knew this had something to do with the "use system emojis" option, I re-installed Gboard on my phone to get the ENTER button back...
