### ISSUE TITLE
I cannot select emoji from text input area when the keyboard is set to "Use system emoji"

### ISSUE THREAD

**Issue by yveggie** [signalapp/Signal-Android#12638]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After selecting Setting > Keyboard > Use System Emoji, the selector in the text input area changes to Label. Selecting it, I get the option to switch to GIF, but not to emoji. Previously, I could select emojis from here.

### Steps to reproduce
- In Signal main screen, go to Settings > option Chats > section Keyboard > select "Use system emoji"
- Go back to Signal main screen
- Open a chat
- In the text input area, at the left, you see either a Labels or Gif icon, but not an Emoji icon
- Pressing the icon, you can access either a Labels section or a Gif section, but not the third emoji section
- Return to Signal main screen, go to Settings > option Chats > section Keyboard > deselect "Use system emoji"
- Go back to Signal main screen
- Open a chat
- In the text input area, at the left, press the Labels or Gif icon
- In the selection area, at the top, the first of 3 icons is now an Emoji icon

**Actual result:** Labels or Gif selector
**Expected result:** Emoji or Labels or Gif selector

### Device info
**Device:** Fairphone FP2, OS build 22.10.0-rel.0
**Android version:** 10
**Signal version:** 6.2.3

**Comment by greyson-signal** [comment]
This is intended. If you switch to using system emojis, we assume you'll be accessing them from your own keyboard, rather than ours.

**Comment by yveggie** [comment]
Thanks for explaining. I'll remember never to activate that setting again. :-)
