### ISSUE TITLE
Can't recieve calls on a locked phone in Android 13

### ISSUE THREAD

**Issue by galibert** [signalapp/Signal-Android#12637]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a Samsung S22+ with Android 13, when the screen is locked and there is an incoming call (video or audio) the phone rings but, to answer you have to:
- unlock the phone
- start the signal application
- accept the call

The first two steps shouldn't exist.

### Steps to reproduce
- Recieve a call on a locked phone

**Actual result:** Ring sounds, screen stays locked, no direct way to answer
**Expected result:** Call answering screen

### Device info

**Device:** Samsung S22+
**Android version:** 13 (1 oct 2022)
**Signal version:**  6.2.4

### Link to debug log

https://debuglogs.org/android/6.2.4/35dfd1c1d17c40e238e20837035e5a825b08b249788dbafcfc70cab2d605efcf

**Comment by cody-signal** [comment]
Is the phone only locked or are you using "Lockdown" mode?

![image](https://user-images.githubusercontent.com/66265416/204617755-4968bb8b-ff6d-4cc5-9845-38dc79c4fc30.png)

**Comment by cody-signal** [comment]
Additionally, are you blocking notifications or other types of content from showing on the lock screen?

**Comment by galibert** [comment]
The Lockdown mode is not in use.  Pour les notifications seul un icone apparait.
