### ISSUE TITLE
Gifted badge not received

### ISSUE THREAD

**Issue by nehemiagurl** [signalapp/Signal-Android#12642]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Gifted a badge to a friend. The gift appears on my side to be delivered and viewed, but to the other party the message is not found

### Steps to reproduce
- gift a badge to a friend and pay with Google Pay
- the gift appears to be sent and received on your side, but is not found on the other

#### Sender side:
![Screenshot_20221129-191239_Signal](https://user-images.githubusercontent.com/109424320/204597433-67bf0d88-132b-4866-8160-1685f0ab7939.jpg)
![Screenshot_20221129-191308_Signal](https://user-images.githubusercontent.com/109424320/204597475-9ae1fba9-ee07-4c00-93a0-550b3bd3b95f.jpg)
![Screenshot_20221129-192026_Signal](https://user-images.githubusercontent.com/109424320/204598501-239eebd6-9e64-4077-8dcd-35c51fe4205f.jpg)
#### Receiving side:
![signal-2022-11-29-18-37-16-973](https://user-images.githubusercontent.com/109424320/204597570-1adfac40-5811-4b6a-a804-8e8b3b8eefb2.jpg)

#### Sender side:
**Device:** Samsung Galaxy A12 
**Android version:** 12
**Signal version:** 6.3.3
#### Receiving side:
**Device:** Xiaomi Redmi Note 7
**Signal version:** 6.2.4

#### Sender side:
https://debuglogs.org/android/6.3.3/a0334d882a37263fc84e3296610c6b3355a0ebc083f339c7a51ffed8eff70ad6
#### Receiving side:
https://debuglogs.org/android/6.2.4/005cf6f4fceecc8a6dc01fd367f718c1470348e920cc51ee6ad7c958bd852278

**Comment by cody-signal** [comment]
Hi there,

Thanks for the very detailed report. Including both logs was very helpful. It looks like there's a bug with new installs that receive a gift very early on that caused the message to be dropped and not processed. We are fixing that bug.

As for resolving the issue for you now, we're in a bit of a tough spot. Can you email me (cody@signal.org) and we can discuss there?

**Comment by nehemiagurl** [comment]
emailing you rn!

**Comment by nehemiagurl** [comment]
Other than fixing my personal badge problem, I believe this issue was fixed in genera in later released, wasn't it? @cody-signal

**Comment by greyson-signal** [comment]
Yep! All fixed.
