### ISSUE TITLE
MMS groups still showing up in search even after deletion

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I exported my SMS/MMS messages out of Signal recently and afterwards I used the option to delete all SMS/MMS threads from the database. But I still see empty MMS groups in my search history. 

### Steps to reproduce
- Export your SMS/MMS messages
- Delete all SMS/MMS messages via the delete all functionality
- Search for users that have been in MMS threads.

**Actual result:** I still find old, empty chats in search. Which clutters my results. 
**Expected result:** All SMS/MMS threads should have been deleted from the local Signal DB. 

### Screenshots

![signal-2022-12-02-20-18-54-073.jpg](https://user-images.githubusercontent.com/18274896/205417849-9f2dea11-ef74-4420-8251-a9eb3b0648b5.jpg)
![signal-2022-12-02-20-18-14-800.jpg](https://user-images.githubusercontent.com/18274896/205417855-e18cce13-96fe-46a0-b6f1-750c1a276187.jpg)

### Device info

**Device:** Pixel 7
**Android version:** 13
**Signal version:** 6.2.4

### Link to debug log

https://debuglogs.org/android/6.2.4/36cca6aefcc6219e4727bfbb502b7a493b32efe710b01abb1fad17967630882f

**Comment by cody-signal** [comment]
Hi there, are all the MMS threads that are showing up include someone that uses Signal and had a safety number change with?

**Comment by Tursko** [comment]
> Hi there, are all the MMS threads that are showing up include someone that uses Signal and had a safety number change with?

Yes those are actual MMS groups. One or two of the users in the groups are Signal users but all the others aren't.

**Comment by cody-signal** [comment]
Thanks for the reply. The safety number update messages are why the threads aren't being deleted. If you long press/delete them the threads should go away.

I'll have to think about how to address this in general, but the above will at least get you to a happy state.
