### ISSUE TITLE
UX: one failing backup turns off all backups

### ISSUE THREAD

**Issue by Ekleog** [signalapp/Signal-Android#12659]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Hey! Before the bug itself, please let me thank you for signal, it's an awesome application!

I just found a way I think the UX would deserve being improved, which is listed below :)

### Bug description
When one backup fails, signal auto-backups turn off and need to be manually re-enabled

### Steps to reproduce
- Enable backups, with a folder over the network (eg. on a nextcloud)
- Have the network turned off at the scheduled backup time
- Click the "backup failed" notification (I'm not sure whether this is required to repro)

**Actual result:** Notice that backups are now turned off, and need to be turned on with a new passphrase again
**Expected result:** It'd be great if backups stayed on, so that the passphrase does not change and need to be re-written to a safe place on every day where internet failed during the backup!

### Device info

**Device:** Samsung Galaxy S10+
**Android version:** LineageOS 19.1
**Signal version:** 6.3.6

### Link to debug log
Not applicable (unless you can't repro? But it's been consistent for me, I'm pretty sure it's "by unintended design", and it hasn't happened to me recently so I don't have one at hand. Feel free to ask if I'm wrong and you actually need one!)

Anyway, thank you so much for Signal! :)

**Comment by Ekleog** [comment]
I misclicked and created the issue while still creating it, sorry about that! It's now filled.

**Comment by Ekleog** [comment]
Somewhat scarier, as it just happened to me again: it looks like signal truncates its backup files to 0B in this situation, though AFAIR not on the first time it happens, so I guess it's just that it keeps its "backup rotation" running even though it fails the writes.

Also, I can confirm that not clicking the popup does not disable the backups, as I did get the popup 3 days in a row.

**Comment by cody-signal** [comment]
I think the only thing that makes a backup fail and then also disable is if the destination folder we are given to write the backup to has been "disappeared". Guessing something like this is happening with your cloud backup? Does the same happen to you when using local only storage?

We are unable to reproduce so a debulog would be helpful if you're still encountering this issue
