### ISSUE TITLE
Voice memo lock breaks when changing orientation

### ISSUE THREAD

**Issue by MaLiKorSlip** [signalapp/Signal-Android#12655]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug 
When creating a voice memo and using the lock function to continue recording without pressing the button, if your phone changes orientation, it will stop the recording prematurely

### Steps to reproduce
- have the phone in portrait mode
- press and hold the voice memo button in a message
- Swipe up to lock the microphone to continue recording
- move your phone so it switches to landscape orientation

**Actual result:** 
Voice memo recording will stop 
**Expected result:**
Voice memo recording continues

**Comment by MaLiKorSlip** [comment]
This is both android and iphone

**Comment by c15c** [comment]
Please fix this. Super frustrating bug.

**Comment by alex-signal** [comment]
Please add a debug log :-) I'm pretty sure we're just being bad about config changes here.

**Comment by alex-signal** [comment]
Are you on iOS or Android? This is Android github repo.

**Comment by c15c** [comment]
Yeah iOS sorry. Do I need to submit it as a separate bug?

**Comment by alex-signal** [comment]
@c15c Yes, this should be opened on the Signal-iOS repo.
