### ISSUE TITLE
Import Android SMS Database

### ISSUE THREAD

**Issue by marsianer** [signalapp/Signal-Android#1265]
Unfortunately SMS messages can't be imported, when the sender have no phone number. However, in the standard Android App are messages included, where the phone number is the name of the company. For example my bank sends SMS messages with the number "comdirect" and there are many more companies like that.

Is there any reason, why this messages can't be imported? I really want to use TextSeure, but I also don't wanna lose my existing SMS messages.

**Comment by DanHakimi** [comment]
I'm very confused as to why Signal needs to import from the SMS database -- shouldn't it keep SMS synced with the SMS database?
