### ISSUE TITLE
Not receiving replies in group chat.  Direct message still working.

### ISSUE THREAD

**Issue by Hangten10** [signalapp/Signal-Android#12660]
Everyone can read my messages but I am not receiving anything.  My colleagues are here with me so I know they are messaging and can see in their phones.  Any tips on how to fix this?

This is happening with two groups.  They are trying to get me to move to WhatsApp.  It was working this morning...  Please help.

Thanks

Edit- I am on Android but colleagues are both iOS and Android.  Direct messages are working.

Edit 2: Noticed that turning off ProtonVPN allowed group messages to be received.  Not sure where the issue lies.

**Comment by andrepd** [comment]
Having the exact same issue. 

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Group messages from others aren't delivered, but my messages to the groups are. Read receipts "x is typing" indicators also work. Direct messages work fully with no problems. 

### Steps to reproduce
- Have someone send a message to your group

**Actual result:** No message is delivered
**Expected result:** Message is delivered to my phone

### Device info
**Device:** Pixel 4a
**Android version:** 11
**Signal version:** 6.3.0

### Link to debug log
https://privatebin.net/?2e7ad283fa748739#HPoypzxCBTsABUjNXbNmF7yiL266mD3efLt2nmehX2Qz

**Comment by bharker75** [comment]
I am having this problem as well. Attempting to create a new group also fails.

**Comment by lucastx** [comment]
Apparently the same here with 3 people I'm in contact with. All Android devices, with problems specifically to receive group messages in multiple groups, starting in the same time window since the issue was opened  (Dec 6th).

I'm hoping to get the debugs log to add here

**Comment by smcclennon** [comment]
[This reddit thread](https://libreddit.de/r/signal/comments/zekpcy/not_receiving_replies_in_group_chats/)  on the issue recommends disabling ProtonVPN, which worked for me.

Feature status with ProtonVPN enabled:

|Feature|Status|
|-|-|
|Send group messages|✅|
|Receive group messages|❌|
|Receive group typing indicators|✅|
|Send direct messages|✅|
|Receive direct messages|✅|
|Receive direct typing indicators|✅|

**Comment by lucastx** [comment]
ProtonVPN team has acknowledged and reproduced the bug, and is working on a solution, according to their official Reddit account in a thread dealing with this issue:

https://www.reddit.com/r/ProtonVPN/comments/zfmeot/signal_messenger_blocked/

**Comment by smcclennon** [comment]
Comment from Proton customer services:

> The issue was on Proton VPN server side, and our teams have managed to fix it.
> 
> Please reconnect to the VPN servers and everything should work as expected with the Signal application

The issue now seems to be resolved.

**Comment by toxpal** [comment]
The same problem here with Pixel 6 and Android 13. The issue started yesterday. The strange thing is that SOME groups work, and some don't. Direct messages work fine.

**Comment by greyson-signal** [comment]
Looks like protovpn addressed this.
