### ISSUE TITLE
"New tag collected" message after sending messages in Signal.

### ISSUE THREAD

**Issue by multilectical** [signalapp/Signal-Android#12662]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since this morning, every time I send a message I see several instances of the message "New tag collected" along with a string of letters/numbers.

### Steps to reproduce
- Fill out field with message text
- Hit send
 
**Actual result:** Screen shows the error "New tag collected" along with string of letters/numbers and I hear 3 notification sounds.
**Expected result:** The App just stays on my list of messages showing no strange message or sounds.

### Screenshots

![signal_error](https://user-images.githubusercontent.com/1326270/206744934-e1d933d9-86ef-4114-b6be-d7a1bbd558aa.png)

### Device info

**Device:** Pixel 5
**Android version:** 13
**Signal version:** 6.3.6

### Link to debug log
https://debuglogs.org/android/6.3.6/b4483e18e27a80624417901be6e7d637a24c9c5aaf08d99b3af759268c2c256d

**Comment by greyson-signal** [comment]
Just wanted to make it clear that whatever you're seeing is not coming from Signal. There is no screen like that. Idk what other apps you have installed.
