### ISSUE TITLE
Get ANR when repeatedly record video and go back

### ISSUE THREAD

**Issue by Kobayashi-996** [signalapp/Signal-Android#12667]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I tried to collect videos for the Gallery, I long clicked to record a video, soon clicked back, then repeated the two steps again and the app would be ANR

### Steps to reproduce
1. Click the camera icon on the main page
2. Go to the Gallery
3. Click the camera icon at top right
4. Long click and record a video
5. Click back
6. Long click and record a video
7. Click back, and the app gets completely stuck, then get an ANR

**Actual result:** Get ANR
**Expected result:** Continue to collect videos

### ScreenRecord
https://user-images.githubusercontent.com/120108516/206853176-3c1ed767-a2d8-430f-a771-86ccba571774.mp4

### Device info
**Device:** Google Pixel 2
**Android version:** 9.0
**Signal version:** 6.4.2

### Link to debug log
https://debuglogs.org/android/6.4.2/c06b3d1639f79e2a0cfdde385f43bbaec2a9a080846c248f6da72142e1bb055a

### Logcat
ANR in org.thoughtcrime.securesms (org.thoughtcrime.securesms/.mediasend.v2.MediaSelectionActivity)
    PID: 9750
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 1.  Wait queue head age: 48377.7ms.)

**Comment by UnreachableCode** [comment]
I followed your steps on a Pixel 2 with Android 9.0 emulator. I couldn't recreate this bug on 7.28.4.
