### ISSUE TITLE
Group listing on user profiles only shows some groups

### ISSUE THREAD

**Issue by qwerty287** [signalapp/Signal-Android#12676]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

On the user profile views, you can see all groups you and the viewed user are member of. However, this doesn't work for all groups. Some groups are never shown there (not important which user), and groups that are on one profile are on all.

### Steps to reproduce
- create few groups with members
- look at member's profile (scroll down)

**Actual result:** Some groups are shown, some not.
**Expected result:** All groups (the user is member of) are shown.

### Device info

**Android version:** 12 (Android One)
**Signal version:** 6.3.6

**Comment by cody-signal** [comment]
The list is limited to a few, and then you can tap to expand to see all of them. I can't reproduce this with a few folks in my contacts with shared groups.

**Comment by greyson-signal** [comment]
If you delete the thread, then that's behaving as intended. It's the only way for people to remove groups from results. Otherwise, there is no way for people to remove them, and creating a group once would cause it to follow you forever.
