### ISSUE TITLE
Stale unread messages badge when deleting an unread chat

### ISSUE THREAD

**Issue by bkis** [signalapp/Signal-Android#12678]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When completely deleting a chat with unread messages, the badge indicating unread messages (bottom of main screen) still shows these messages as unread. There's no way to change this now, as the chat is deleted and the message cannot be "read" anymore.  
This happened when I got a spam SMS from a random number (that likely won't send any other messages in the future) that I didn't want to read and instead just deleted the chat completely (see screenshot). 

### Steps to reproduce
- get a message, don't read it
- delete the chat with the unread message

**Actual result:** The badge with the unread message count doesn't change.
**Expected result:** Although the message *was* never read, indicating it as unread forever just makes the badge useless. When deleting a chat, unread messages should be either marked as read or at least not taken into account by this counter.

### Screenshots
![photo_2022-12-15_10-29-52](https://user-images.githubusercontent.com/9215743/207826159-12f335d0-8005-47bb-a9a5-cc24d3f73297.jpg)

### Device info
**Device:** Samsung Galaxy A5 2017
**Android version:** LineageOS 17 (based on Android 10)
**Signal version:** 6.3.6

### Link to debug log
This bug already appeared one or two weeks ago. I don't think a fresh debug log will help in this case anyway (there's no error or anything, I think it's just a hickup in the implementation of this counter or the deleting of chats).

**Comment by greyson-signal** [comment]
I tried my best to reproduce this on the upcoming 6.7 branch and I've been unable to. Tried deleting pinned/unpinned, tried archiving, couldn't get it to repro. Please let me know if this is still an issue in 6.7+. Thanks!

**Comment by bkis** [comment]
Will do! Thanks for your reply!
