### ISSUE TITLE
Cannot send sms without country prefix

### ISSUE THREAD

**Issue by jbrepogmailcom** [signalapp/Signal-Android#12677]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

There are some local country numbers for SMS (Premium-SMS), that use shortened number and are only country specific, so they only work without country prefix. For example SMS sent to number 9020626 can pay for ticket. But Signal automatically adds country prefix even when the number is stored in contacts without the prefix, so in my case Signal creates recipient number as +42090202626 from contact number 9202626 ad then tries to send SMS to that number. It does not work. So signal does not allow to send premium SMS and needs to be turned off as default SMS application and other SMS application needs to be set as default in order to send premium SMS.

### Steps to reproduce
- try to send premium SMS to number without country prefix
- error that SMS cannot be sent

**Apparently there have been same problems reported before but closed without resolution as part of "GitHub Issue Cleanup: See https://github.com/signalapp/Signal-Android/issues/7598 for more information."**

**Comment by nikkehtine** [comment]
I really doubt this is going to get fixed since Signal [announced they'll be phasing out SMS support](https://signal.org/blog/sms-removal-android/)

**Comment by jbrepogmailcom** [comment]
"We have now reached the point where SMS support no longer makes sense" - well, I really wanted Signal to by my default SMS application and I think I am the only one. I will have to transfer to other Signal fork.
