### ISSUE TITLE
.mp4 videos sent from Signal-Windows can't be open in Signal-Android, displays message "Media no longer available."

### ISSUE THREAD

**Issue by kerenkxs2** [signalapp/Signal-Android#12679]
**Bug description**
Every time I send .mp4 videos from Signal-Windows to Signal-Android, the video can't be played in Signal-Android. Attempting to do so warns the message: "Media no longer available." In Signal-Windows, it can be only downloaded as there is no option to play the video.

**Steps to reproduce**
Open Signal-Windows.
Open any conversation.
Get any .mp4 video and send it through the messenger.
Try to open this .mp4 video in Signal-Windows. It can only be downloaded, not played.
Try to open this .mp4 video in Signal-Android. Message is displayed: "Media no longer available."

**Expected result**
.mp4 videos would be playable both in Signal-Windows as well as on Signal-Android, like most of the other messengers.

**Device info**
It has been tested with more than five Android devices. Same behavior.
Windows 10 and Windows 11.

Signal-Windows version: 6.1.0
Signal-Android version: 6.3.6

**Comment by cody-signal** [comment]
Can you provide a debuglog?

**Comment by kerenkxs2** [comment]
> Can you provide a debuglog?

Here:

https://debuglogs.org/android/6.3.6/73dac6201ebe86d040752e6602569cf77df92eb3ae0b2844d3cf2f16ddbdf28c

**Comment by cody-signal** [comment]
Thanks. It looks like we do have the file but we are unable to play it due to how it's encoded. Our decoder fails. Is the mp4 from a specific source?

The error message definitely incorrect and we'll fix that, but not sure we can fix Android OS unable to decode and play the video.

**Comment by kerenkxs2** [comment]
> Thanks. It looks like we do have the file but we are unable to play it due to how it's encoded. Our decoder fails. Is the mp4 from a specific source?
> 
> The error message definitely incorrect and we'll fix that, but not sure we can fix Android OS unable to decode and play the video.

The .mp4 file is generated in Bandicam. I usually take the file and post it into Signal, which generates the referred problem.

**Comment by kerenkxs2** [comment]
I played a few tests with Video and Audio codecs. Now it seems to be working.
The issue lies with the Audio Codec. I changed it from MP3 to AAC and the videos now work both in Android and Windows.

**Comment by cody-signal** [comment]
Interesting, good to know. We've update the error message for this error case and it'll be 6.6.
