### ISSUE TITLE
"Signal is unlocked" notification can be closed without locking Signal.

### ISSUE THREAD

**Issue by michaldaw** [signalapp/Signal-Android#12681]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Signal is unlocked" notification can be cleared by swiping, resulting in Signal being unlocked without the users knowledge.

### Steps to reproduce
1. Open Signal.
2. Go to Settings > Privacy.
3. Turn on Screen Lock.
4. Exit Signal.
5. Open notifications bar.
6. Swipe "Signal is unlocked" to close this notification.

**Actual result:** It's possible to close the "Signal is unlocked" notification by swiping. Signal doesn't lock immediately nor does it after locking the phone. It results in Signal being unlocked without the users knowledge. Signal locks after some time, but after unlocking it's still possible to reproduce the bug. All this happens without changing the Screen Lock setting.

**Expected result:** The "Signal is unlocked" notification should not be possible to close by swiping. Even if it would be supposed to be possible to close it this way, closing should lock signal.

### Screenshots
![Signal Bug All](https://user-images.githubusercontent.com/119760691/208266613-323dcc57-7f0b-4604-8d73-7e31fdcf8df8.png)

### Device info
**Device:** Samsung Galaxy A22 Model SM-A225F/DSN
**Android version:** 13
**Signal version:** 6.3.6

### Link to debug log
https://debuglogs.org/android/6.3.6/46a4e20b9dc9464f757622db19340229511e21a9310adf02e9059071e47a3428

**Comment by francis2054** [comment]
I seem to still have this issue, I can remove the notification, but then I have no way of locking Signal. Not even clearing from memory brings it back or locks Signal. The only way for me personally, is force stop the app or restart my phone. 
Worth a new issue opened?

Signal version 6.45.1
Android version 14
Nothing Phone 2
