### ISSUE TITLE
Bug report from within signal app creates useless email message with Proton Mail app

### ISSUE THREAD

**Issue by GuiDoSignal** [signalapp/Signal-Android#12687]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to submit a bug from within the signal app, it creates a empty message on the Proton Mail app. The message contains no recipient, content nor attachment (i.e. debug log).

### Steps to reproduce
- Click on the three dots -> Settings -> Help -> Contact
- Write the description, choose  the contact reason, pick an emoji and check the option to include the debug log
- Click "Next" and choose the Proton Mail app to contact the support

**Actual result:** An empty message is created, with no recipient, description nor attachment.
**Expected result:** A message with recipient, description and attachments should be created, so one can file a support ticket.

### Screenshots
![Screenshot_2022-12-20-16-25-33-87_c3025e5ce50ffdc2876b487a5468618d](https://user-images.githubusercontent.com/1004193/208755334-8e5c9b47-a9dc-42d0-b879-c4169f75fcd1.jpg)

### Device info

**Device:** Oneplus LE2125
**Android version:** 13
**Signal version:** 6.5.6

### Link to debug log
[]

[DEBUG LOG](https://debuglogs.org/android/6.5.6/be93bae7dd998eeee020fbeb958361997f281d84eaeb0695f4d98ae875a92a32)

**Comment by greyson-signal** [comment]
We verified that this flow is working for other email apps. My guess is that it's some bug in proton mail.
