### ISSUE TITLE
I can see strangers in my contacts

### ISSUE THREAD

**Issue by VSCPPFI** [signalapp/Signal-Android#12680]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If i am searching for a contact in the Signal Desktop application, i can see people displayed as contacts, that i do not have in my contacts and never had.

### Steps to reproduce
- Open Signal Desktop
- Search for a few names
- find someone Displayed as a Contact, that is not in your contact list.

**Actual result:** It shows me the profiles of strangers.
**Expected result:** It should only show me the profiles of my contacts.

### Screenshots

![Screenshot (15)](https://user-images.githubusercontent.com/119423378/208243392-e677182e-9c1a-4b38-b438-97f1d60f00db.jpg)
The persons 2 and 3 in the list are not in my contacts. As you can see on the right side even the profile picture and phone number is visible to me

### Device info
**Signal Desktop version:** 6.1.0

**Comment by Sgn-32** [comment]
Are the contacts also shown on your primary device (Android/iOS)?
Maybe some group members of a group you are also a member?

**Comment by VSCPPFI** [comment]
> Are the contacts also shown on your primary device (Android/iOS)? Maybe some group members of a group you are also a member?

No, it seems its only on the desktop version. No, they certainly are not members of a group i am in.

**Comment by VSCPPFI** [comment]
The people in the picture are only an example btw. I found some more people, not just the 2.
