### ISSUE TITLE
allowing other people to erase messages from my phone

### ISSUE THREAD

**Issue by jontis** [signalapp/Signal-Android#12690]
Dissappearing messages is not a feature, it's a bug. Allowing other people to at their discretion erase messages from my phone is not the way I want a messaging app to work.
I will thus prioritize other services.
Please rethink this move.
Kindly
Jonathan Anderson

**Comment by nicholas-signal** [comment]
We use GitHub to track bugs, not features. Please use the [Signal Forum](community.signalusers.org) to discuss features.
