### ISSUE TITLE
Emoji Search Terms are missing for new v14 Emoji

### ISSUE THREAD

**Issue by starhawking** [signalapp/Signal-Android#12699]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji released as part of Emoji v14 appear to be missing from search when using the builtin emoji picker. 

It appears this is likely because [signalapp/emoji-search-index](https://github.com/signalapp/emoji-search-index) does not include the new v14 emoji

### Steps to reproduce
- Open the Signal Emoji Picker
- Switch to the search tab
- Search for `salute` or `melting`

**Actual result:** The🫡or 🫠 emoji should appear in the search results
**Expected result:** `melting` displays "No results found" and `salute` only returns 🖖 (Vulcan Salute)

### Screenshots
![signal-2022-12-27-153542_002](https://user-images.githubusercontent.com/1923850/209724630-79331323-4ba2-463e-a07c-bb3d8b4cb39b.jpeg)
![signal-2022-12-27-153542_003](https://user-images.githubusercontent.com/1923850/209724632-206cd460-5c66-41c0-ab99-c864d696b19e.jpeg)

### Device info

**Device:** Samsung Galaxy S10+
**Android version:** 12
**Signal version:** 6.6.3

### Link to debug log

https://debuglogs.org/android/6.6.3/e906e7d7087a7c139714faf9aab0482fc4f01dc97d4704875e982bfcabd6f1f2

**Comment by greyson-signal** [comment]
Hi there, this is fixed in 6.7, which will go into beta early next week. Thanks!

**Comment by dagdrommer** [comment]
I have the same issues using the latest Signal version on my S23. 
The only exception is that the search always show "no results".

https://debuglogs.org/android/6.22.8/4f223c173a622724fe9c462d3e958e2cf04cf7a1e6d7736d369680fde8a0dc88
