### ISSUE TITLE
Safety Number verification feedback is confusing

### ISSUE THREAD

**Issue by devnull09** [signalapp/Signal-Android#12697]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

During the verification of the safety number, the feedback provided by the app is displayed by either a red X or a green hook which is displayed for about 1-2 seconds before it disappears. Most of the screen stays the same and it is not at all clear to a user if the verification was successful or not after the response x or hook has disappeared. The app shows a small text "UserX is verified" but it displays the unverified message in the same text as well, which is in both cases displayed in the same color and size as the rest of the text on the screen, making it very easy to overlook.

To emphasize:

When verifying the safety number, the user may be holding both phones and trying to read the QR code one phone with the camera of the other. With the attention switching between the two phones, possibly holding them at different angles as well to get the camera to capture the code, it is very easy to miss the 2 second verification feedback.

I have gone through the safety number verification process several times in the past days and despite using this process several times a year and being a signal user for years, I misinterpreted the feedback message as well when it failed and only noticed the mistake by chance. The other users who I showed the verification process to all failed to understand that the process failed as well.

Part of the problem is how the process usually works:

The user tries to capture the QR code and when it is read, the reading phone provides the 2 second feedback which is normally "successful" which makes the user hit the mark as verified button.
Even as someone who does this several times a year, I did not remember or pay attention to what color the feedback needs to be and while holding two phones, I hit the verified button as a response to the verification feedback (red X), because why read the feedback message again? After all its always been successful when there is a feedback and never failed before.
Unfortunately, one of the phones was offline and the safety number of the other contact had changed, which is why it failed in this example.

This is the first time a safety number verification failed for me and it was not at all clear to that it did.
Only when I verified the number again on the second phone did I notice the 2 second failed message by chance, checked the second phone again and noticed that I had just marked the safety code as verified even though it failed to verify.

For the average user who rarely uses this feature at all, this is even more confusing.
To the person I was showing the verification process to, it was a very bad example as well and even more confusing.

### Steps to reproduce
- Go through the safety number verification process after the safety number has changed while one of the phones was offline
- The verification will fail but the feedback message will disappear quickly and the verification screen will show no clear indicator of the result

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)
The verification will fail but the safety number screen will mostly look the same with the difference of the verification message, which is easy to overlook since it is only 1% of the screen with lots of text around that looks the same.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)

A failed verification should give a very clear user feedback, like displaying the full screen bright red and sounding a clear error message alert. After a failed safety number attempt, the feed back should very clearly display an error message instead of looking the same as always.

### Screenshots

left is unverified, right is verified.
(Please note that this is an example image and I had to manually edit the verified message since I do not have the affected phone with me to make a screenshot.)

![d](https://user-images.githubusercontent.com/111058423/209581465-8bfbc489-b69b-4da5-a255-f972c0f9337d.png)

As shown in the example (mock) screenshot, the difference between verified and unverified is easy to miss.

### Device info

**Device:** Pixel 6a
**Android version:** 13 (latest version as of yesterday, don't have the phone on me to check the full version)
**Signal version:** 6.6.3

This was tested with two phones, one of which was an IPhone

**Device:** IPhone 13
**IOS version:** [16.2](https://en.wikipedia.org/wiki/IOS_version_history#16.2)
**Signal version:** 6.6

### Link to debug log

The same issue exists on IOS
https://github.com/signalapp/Signal-iOS/issues/5512

**Comment by Meteor0id** [comment]
Design feedback belongs on the community forum, especially since this isn't about either Android or iOS but about both.
https://community.signalusers.org/
Typically the designers do not react to feedback no matter where it is posted.

**Comment by devnull09** [comment]
> Design feedback belongs on the community forum, especially since this isn't about either Android or iOS but about both. https://community.signalusers.org/ Typically the designers do not react to feedback no matter where it is posted.

This isn't just about design. Its about usability of a major security feature in signal.
If this is left to designers who will not even look at the feedback, there is no reason to report bug at all.
