### ISSUE TITLE
buttons are hidden/cut off when adding picture to story

### ISSUE THREAD

**Issue by Matzeeee** [signalapp/Signal-Android#12698]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
The buttons at bottom of screen are hidden/cut off when adding picture to story (see screenshot)

### Steps to reproduce
- goto storys
- touch camera button
- touch pictures/gallery button (bottom right)
- choose a picture and touch button ">" (bottom right)
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
the screen schows the bicture and cut off buttons
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
show full buttons

### Screenshots

![img1](https://user-images.githubusercontent.com/60921150/209692937-9a2ea96d-c766-4e1a-a7c8-61576c448d66.png)

### Device info

**Device:** Samsung Galaxy A51
**Android version:** 13
**Signal version:** 6.5.6

### Link to debug log

https://debuglogs.org/android/6.5.6/ce28497bef8c1207f89f42f71e92f18b716619a4754d60711d6abb155c6c3c67

**Comment by nicholas-signal** [comment]
Hello: I am unable to reproduce this on a Galaxy A51 running Android 12 (Android 13 is not yet available in the US yet). I tried images with aspect ratios 1:1.7, 1:2.35, and 1:2.4.

Could you please confirm this is still an issue, and exactly the dimensions of the image?

In addition, could you check your OS settings app and report back your "Screen Zoom" and "Font Size" settings?

**Comment by Matzeeee** [comment]
image:
![Garmin-2023](https://user-images.githubusercontent.com/60921150/211202981-da4a60ea-a137-4c01-9963-c9e726f1e60b.png)

**Comment by Matzeeee** [comment]
dimension: 438x413

**Comment by Matzeeee** [comment]
screenshot:
![Screenshot_20230108_154808_Signal](https://user-images.githubusercontent.com/60921150/211203119-6afbd66e-b4a3-4de8-9dee-db625e8121e1.png)

**Comment by Matzeeee** [comment]
![Screenshot_20230108_155631_Settings](https://user-images.githubusercontent.com/60921150/211203272-f7450a23-4cf1-44d4-850f-9dc82384a377.png)

**Comment by Matzeeee** [comment]
![Screenshot_20230108_155654_Settings](https://user-images.githubusercontent.com/60921150/211203301-c839c6db-231b-4db4-aeec-7338a242aad1.png)

**Comment by nicholas-signal** [comment]
Unfortunately, even with your exact image and settings, I am unable to replicate this issue. I will revisit this once Samsung ships Android 13 to the US.

![Screenshot_20230111-095820_Signal](https://user-images.githubusercontent.com/112583042/211839408-24ed46e9-d54d-4d33-89ae-b3a2f313be14.jpg)

**Comment by Matzeeee** [comment]
in your picture above you have **swipe gestures** activated in Android Settings / Display / Navigationbar (?)
if i activate this too then it seems ok:
![img2](https://user-images.githubusercontent.com/60921150/211842802-2cc42eea-213f-4b26-a460-b73bc9e4f36c.png)
if i activate **buttons** its cut:
![img1](https://user-images.githubusercontent.com/60921150/211843076-fd8eb50e-9ac5-496c-8b71-3b0fc5dafecf.png)

**Comment by nicholas-signal** [comment]
A good thought but even still I am unable to reproduce it:
![Screenshot_20230111-102014_Signal](https://user-images.githubusercontent.com/112583042/211844600-ba6b5d2f-9129-42f5-9058-f03d081caf2a.jpg)

**Comment by Matzeeee** [comment]
Ok, here is the solution:

![Screenshot_20230111_194930_Settings](https://user-images.githubusercontent.com/60921150/211894092-e8535c54-6f42-4af3-a659-46f85a36aa41.png)

I have turned off this 3 Options.
If I turn on again it works.

**Comment by Matzeeee** [comment]
P.S. there was an other issue with the same problem some time ago...

**Comment by Matzeeee** [comment]
> [alex-signal](https://github.com/alex-signal) closed this as [completed](https://github.com/signalapp/Signal-Android/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/signalapp/Signal-Android/commit/276f485b49b2ffbe2dfbe30d0829b112cb29e2d4 [on Jan 13](https://github.com/signalapp/Signal-Android/issues/12698#event-8224302066)

Hello, has this error already been fixed? I still have the same problem in the latest version.
