### ISSUE TITLE
rtmp URL schema parsing and highlight

### ISSUE THREAD

**Issue by pzhuk** [signalapp/Signal-Android#12694]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- send a message which has RTMP url  for example   rtmp://foo.bar.com/zoo
- open message with Signal mobile
- try to click on the message or copy it

**Actual result:**  the only part of link which is being parsed and used is bar.com/zoo  and link is being opened as http://bar.com/zoo
**Expected result:** full link is properly highlighted. Possible to copy full link with typical copy/paste procedure

### Screenshots
![image](https://user-images.githubusercontent.com/10362976/209446595-5ed7e1a3-d6e4-45a7-a655-e0472c8551fc.png)

### Device info
**Device:** Motorola G60
**Android version:** 12
**Signal version:** 6.5.6

**Comment by greyson-signal** [comment]
Hi there, we use the default android linkifier. I don't anticipate writing a custom one to handle this usecase.
