### ISSUE TITLE
legacy_failure bug

### ISSUE THREAD

**Issue by panzhenglian** [signalapp/Signal-Android#12700]
scheme and host have been configured for my application, but several domain names cannot take effect. The configuration and logs are as follows:
<intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="https" />
                <data android:scheme="http" />
                <data android:host="app-config.flowus.cn" />
                <data android:host="www.flowus.cn" />
                <data android:host="test.allflow.cn" />
            </intent-filter>
            
            adb shell pm get-app-links com.next.space.cflow
  com.next.space.cflow:
    ID: 7782a8e9-350f-4080-8a4e-dec398f323d3
    Signatures: [38:9F:51:5F:C5:77:C4:C2:CE:40:36:9E:51:20:2D:C0:A2:BE:CE:22:CA:68:74:FE:67:17:AA:CD:A4:1D:AD:CE]
    Domain verification state:
      app-config.flowus.cn: verified
      test.allflow.cn: legacy_failure
      www.flowus.cn: legacy_failure
      
assetlinks files on the site are normal

https://digitalassetlinks.googleapis.com/v1/statements:list?source.web.site=https://app-config.flowus.cn&relation=delegate_permission/common.handle_all_urls
https://digitalassetlinks.googleapis.com/v1/statements:list?source.web.site=https://www.flowus.cn&relation=delegate_permission/common.handle_all_urls
https://digitalassetlinks.googleapis.com/v1/statements:list?source.web.site=https://test.allflow.cn&relation=delegate_permission/common.handle_all_urls

https://app-config.flowus.cn/.well-known/assetlinks.json
https://www.flowus.cn/.well-known/assetlinks.json
https://test.allflow.cn/.well-known/assetlinks.json

**Comment by greyson-signal** [comment]
Hi there, we only use Github for bugs. For development assistance, please use [the forum](https://community.signalusers.org/). Thanks!
