### ISSUE TITLE
In-app camera doesn't take photos using volume buttons

### ISSUE THREAD

**Issue by AvidSeeker** [signalapp/Signal-Android#12704]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

In-app camera doesn't take photos using volume buttons

- Touch the camera button
- Click the volume button

**Actual result:** Camera should take picture
**Expected result:** It doesn't

**Comment by greyson-signal** [comment]
Hi there, thank you for the suggestion, but we only use github for bug reports, not feature requests. For feature requests, please use [the forum](https://community.signalusers.org/). Thanks!
