### ISSUE TITLE
Drag area is too small in multi line text

### ISSUE THREAD

**Issue by farewelltospring** [signalapp/Signal-Android#12706]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Selection outline and drag area are too small in multi line text when writing on an image

### Steps to reproduce
- Take photo in app
- Add text
- Add multiple lines of text (press enter)

**Actual result:** Drag area is smaller than the text
**Expected result:** Drag area should be the same size as the text

### Screenshots

![pic](https://user-images.githubusercontent.com/108375980/210228947-acb6d5f8-81fd-45f6-8432-f715dcb0a50b.png)

### Device info

**Device:** Pixel 3
**Android version:** 12
**Signal version:** 6.6.3

### Link to debug log

Not needed.

**Comment by farewelltospring** [comment]
Did this get fixed?

**Comment by farewelltospring** [comment]
Can someone find time to fix it? If not, then can someone give me pointers on how to debug it myself?

**Comment by alex-signal** [comment]
There should be a `MultilineTextRenderer` that may be reporting its size wrong somehow? I've not looked at the image editor in a while and it's not the easiest thing in the world to grok
