### ISSUE TITLE
Some message parts aren't included in backups

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#12702]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal backups are missing some message parts

### Steps to reproduce
- Enable backups

**Actual result:** Some MMS messages are missing their media
**Expected result:** All messages have their associated media

### Device info

**Device:** Samsung S22 Ultra
**Android version:** 13
**Signal version:** 5.59

### Link to debug log
Debug logs show nothing. However, performing a sqllite query on the decrypted database shows the problem.

```
 * Executing query: SELECT * from mms where _id = 37864
_id|thread_id|date|date_received|date_server|msg_box|read|body|part_count|ct_l|address|address_device_id|exp|m_type|m_size|st|tr_id|delivery_receipt_count|mismatched_identities|network_failures|subscription_id|expires_in|expire_started|notified|read_receipt_count|quote_id|quote_author|quote_body|quote_attachment|quote_missing|quote_mentions|shared_contacts|unidentified|previews|reveal_duration|reactions|reactions_unread|reactions_last_seen|remote_deleted|mentions_self|notified_timestamp|viewed_receipt_count|server_guid|receipt_timestamp|ranges|is_story|parent_story_id|quote_type|export_state|exported
37864|1|1670890796153|1670890804118|1670890802739|10485780|1|(NULL)|1||31|(NULL)|(NULL)|132|(NULL)|1|(NULL)|0|(NULL)|(NULL)|-1|0|0|0|0|0|(NULL)|(NULL)|-1|0|(NULL)|(NULL)|1|(NULL)|0|(NULL)|0|1670891314822|0|0|1670891234954|0|fdfb615f-4d06-42fe-badf-28b9b791f644|-1|(NULL)|0|0|0|(NULL)|0
```

In the above query we see that the mms message ID 37864 has part_count=1.

```
 * Executing query: SELECT * from part where _id = 37864
(no results)
```

Where'd it go? It's not expired, exported, remote deleted, or anything else.

**Comment by tbvdm** [comment]
You need to query for `mid`, not `_id`. Try this:

```
SELECT * FROM part WHERE mid = 37864
```

**Comment by jbaker6953** [comment]
Thanks. I do see the attachment info appearing in the part table under mid, but the actual binary attachment is not exported in a backup. There are 56 MMS in my backup that are affected this way. How can I further debug?

**Comment by jbaker6953** [comment]
It appears that these are MMS messages that contained attachments that were not downloaded. For example, when you have Signal set not to download images unless on WiFi. If you don't download that image for some time it will be wiped from the system and you will get the placeholder info in the part table, but no associated data.

**Comment by greyson-signal** [comment]
Thanks for digging into this! That makes sense then, since we don't have the image data to backup, so I'm gonna close this.

**Comment by jbaker6953** [comment]
Shouldn't there be some indication in the database that the attachment is supposed to be missing?
