### ISSUE TITLE
App crashes upon open

### ISSUE THREAD

**Issue by parzival-cmd** [signalapp/Signal-Android#12716]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal app is crashing upon opening 10/10 times.

### Steps to reproduce
- Updated to the latest version
- Just opened the app after the update
- It's just force closing itself upon each open instantly after 2seconds

**Actual result:** It's crashing whenever I open the app.
**Expected result:** It shouldn't crash/close rather I need to take backups, chats etc

### Screenshots
![Screenshot_20230107-145231_Pixel_Launcher_Extended.png](https://user-images.githubusercontent.com/55645257/211143532-457df5ad-37bf-4d66-9c59-394d252c6bb5.png)

### Device info

**Device:** Xiaomi Redmi Note 9 Pro
**Android version:** 13 December Patch
**Signal version:** Version 6.7.0

### Link to debug log
https://paste.evolution-x.org/2ndnn2

Incase if you're not able to open the log, here is the screenshot.
![IMG_20230107_145103_498.jpg](https://user-images.githubusercontent.com/55645257/211143481-c245448d-5daa-464a-94aa-af862d4e2d9c.jpg)

**Comment by nicholas-signal** [comment]
Please try version 6.7.3 and see if that fixes the startup crash for you.

**Comment by parzival-cmd** [comment]
Hi, where I can find the version 6.7.3 which you've mentioned?

I can only find 6.6.3 on the website and also in Playstore.

**Comment by Sgn-32** [comment]
@parzival-cmd 

How you updated to 6.7.0? Upating to 6.7.3 should be the same way.
6.7.X is beta.
So you should be in beta program in PlayStore, allowing updating to 6.7.1 - 6.7.3.
or you have firebase app?

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-7-release/50551
https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta

**Comment by parzival-cmd** [comment]
Hi @Sgn-32 , I have updated to 6.7.x when I was on beta but not now and hence maybe it is showing 6.6.3 and I have uninstalled signal, I'm using molly a fork of signal for now as a back-up.

**Comment by parzival-cmd** [comment]
Hi @Sgn-32 , I have updated to 6.7.x when I was in beta but not now and hence maybe it is showing 6.6.3 and I have uninstalled signal, I'm using molly a fork of signal for now as a back-up.

Ps: I've tried the latest apl from firebase and it still crashes.
https://paste.evolution-x.org/GUbutK
