### ISSUE TITLE
signal taking time to send messages

### ISSUE THREAD

**Issue by Matheus-TestUser1** [signalapp/Signal-Android#12713]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Samsung a01
**Android version:** 11
**Signal version:** Playstore version

**Comment by nicholas-signal** [comment]
Thanks for filing a bug, would you mean submitting a debug log?

**Comment by Matheus-TestUser1** [comment]
not only was this problem even though I was having the messages were taking too long to send even on normal internet

**Comment by Matheus-TestUser1** [comment]
https://debuglogs.org/android/6.6.3/6d49b49d7bff09e05eb1154de22e38998ec251a8b5e46127f7c7672248f250e5

**Comment by Matheus-TestUser1** [comment]
![Screenshot_20230105-152507_Signal](https://user-images.githubusercontent.com/99508668/210854210-ef8edcf9-260f-4abf-85df-6c5ecdf136f1.jpg)

**Comment by nicholas-signal** [comment]
> https://debuglogs.org/android/6.6.3/6d49b49d7bff09e05eb1154de22e38998ec251a8b5e46127f7c7672248f250e5

Thanks, I will share with the team.

**Comment by Matheus-TestUser1** [comment]
Obrigado, vou compartilhar com a equipe.

**Comment by Matheus-TestUser1** [comment]
Fixed
