### ISSUE TITLE
Can't delete SMS group

### ISSUE THREAD

**Issue by fresheneesz** [signalapp/Signal-Android#12718]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

There seems to be no way to delete an SMS group on android. 

### Steps to reproduce
- Create a group and add at least one SMS member.
- Search for it (since it doesn't seem to appear in the list of conversations).
- Try to delete it. Press the group and hold down.

**Actual result:** No menu pops up. Nothing happens.
**Expected result:** I expected a menu option to appear that includes deleting the group.

Note, there also are no options below the members to leave the group, and there is no way to remove group members. 

### Device info
**Device:** Pixel 5a
**Android version:** 13
**Signal version:** 6.6.3

**Comment by Tursko** [comment]
This isn't technically a bug. You just need to find the group on the main conversation list view. There's no option to delete the group from within the group or by searching for the group.

**Comment by fresheneesz** [comment]
Ah I see, you're right, if I search for other groups it also doesn't work. That seems... not ideal. You should be able to do the same thing you can do in the normal list in search. Search should just be a filter not change modes on how to interact with groups.

But in any case, my sms group isn't showing up in the main list, so the only way to find it is to search for it. I literally just created it, so it should be on the top right? Regardless, I looked through the whole list and it isn't there. So if that's the only way to delete it, I still can't delete it because its not in the main list.

**Comment by Tursko** [comment]
If you send a message in that group it should show up on your conversation list. Not ideal but it should fix it. SMS support is being phased out so I don't think they'll prioritize any of these legacy bugs.

**Comment by fresheneesz** [comment]
Ah I see. Probably for the best.
