### ISSUE TITLE
echo on receiving end with video call on asus zenfone 8

### ISSUE THREAD

**Issue by thrillfall** [signalapp/Signal-Android#12714]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Receiving end hears their own voice when being video called from Asus Zenfone 8.
This seems independent of the device of the receiving end. Happens for android and iPhone as receiver.

### Steps to reproduce
- Asus Zenfone 8 video calls another user or is being called

**Actual result:** 
receiving end hears their own voice as annoying echo only on their side
**Expected result:** receiving end hears only the voice of the caller.

### Screenshots

None

### Device info

**Device:** Asus Zenfone 8 (sake)
**Android version:** LineageOs 19.1
**Signal version:** 6.6.3

### Link to debug log

https://debuglogs.org/android/6.6.3/686ce20dc15d0f09ea43b777ff38cba9b34f442b722038969c30909520a448c4

**Comment by rashad-signal** [comment]
We made some changes to our echo cancellation configuration which should resolve this. Let us know if you're still seeing it.

**Comment by thrillfall** [comment]
Thanks @rashad-signal for picking this up. When did you make the change? I can't find anything in the recent git history.

**Comment by rashad-signal** [comment]
The change was made in January through remote configuration. So in the worst case, you may need to restart the app for the change to apply. If you've restarted and the problem is still happening, then providing new debuglogs would help in looking into it.

**Comment by thrillfall** [comment]
It is way better now. Thanks!
What is that remote configuration? How do you apply that?
