### ISSUE TITLE
App crashing at launch beta 6.7.0

### ISSUE THREAD

**Issue by homer907** [signalapp/Signal-Android#12710]
Phone model: OnePlus 8 Pro
Android version: 13
App version: 6.7.0 beta

Installed from Play Store update. App crashes upon attempt to open. Unable to provide debug log due to app crashing.

**Comment by paride** [comment]
Same happening on a Pixel 6a.

**Comment by benmayne** [comment]
Same on pixel 7

**Comment by mariachini** [comment]
Xperia 10 III also.

**Comment by PetziAt** [comment]
Same on Ulephone Note 11P, Android 11

**Comment by nxfifteen** [comment]
Same for Samsung Galaxy S22 Ultra running Android 13

Crash report sent

**Comment by AuspeXeu** [comment]
Pixel 6 Pro crash report sent

**Comment by utzer** [comment]
> Same for Samsung Galaxy S22 Ultra running Android 13

Same here. 

> Crash report sent
How can I send a crash report in this case, maybe not needed anymore, but for next time?

**Comment by nicholas-signal** [comment]
Hi everyone: if you're able, please submit a debuglog.

We are pushing out a 6.7.2 release that should address the startup crash.

**Comment by utzer** [comment]
> Hi everyone: if you're able, please submit a debuglog.
> 
> We are pushing out a 6.7.1 release that should address the startup crash.

Hope it'll be available soon, cut off from some conversations.

**Comment by mariachini** [comment]
> Hi everyone: if you're able, please submit a debuglog.
> 
> We are pushing out a 6.7.1 release that should address the startup crash.

[logcat](https://gist.githubusercontent.com/mariachini/e64a336fe7eba98ab180c67dee5321fd/raw/6b937e7719e4eac159e9b053588d47bd265a1721/gistfile1.txt)

**Comment by homer907** [comment]
> Hi everyone: if you're able, please submit a debuglog.
> 
> We are pushing out a 6.7.1 release that should address the startup crash.

Updated to 6.7.1, still crashing. Not able to grab debug.

**Comment by nxfifteen** [comment]
Confirmed 6.7.1 hasn't resolved it for me ether

**Comment by homer907** [comment]
> Can everyone give 6.7.2 a try? More context from @greyson-signal on the forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-7-release/50551/79

Updated to 6.7.2. Not encountering crashes.

**Comment by nxfifteen** [comment]
Just upgraded to 6.7.2 and the problem seems to be resolved for me now

**Comment by Delan168** [comment]
Same for me, problem solved, thank you!

**Comment by PetziAt** [comment]
Great work. Thanks.

**Comment by nicholas-signal** [comment]
Sounds like 6.7.2 fixed this issue for most people. If anyone is still experiencing startup crashes, please file a new GitHub issue.
