### ISSUE TITLE
removal of sms support will kill signal

### ISSUE THREAD

**Issue by hchaase** [signalapp/Signal-Android#12712]
or email support@signal.org

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when you remove sms support new users will dry up, I and many other will be forced to stop using the app because there will be no one to message when non tech people wont bother with the app. 

after this you might as well use whatsapp if not the standard sms app.

next action: cancel donations.

don't  do this, don't kill the app!

**Comment by nicholas-signal** [comment]
Hello,

GitHub Issues are used for tracking crashes and bugs.

Please submit all product feedback and feature requests to our community forum: https://community.signalusers.org/
