### ISSUE TITLE
Stories Broken: Text, Links, Images; Share dialog

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12724]
Using official self-updating APK.

Creating a story works, but when going the the "overview, select "all contacts", send" menu doesnt show any buttons.

No difference between Images, Links or Text.

Version 6.1.4 Android 13

**Comment by alex-signal** [comment]
Hi, I'm not sure which overview you're referring to?

**Comment by firefoxlover** [comment]
I wanted to provide a screenshot but its literally empty.

At the moment stories seem to be broken entirely on some devices. I can view my links sent, other people cant view any links at all.

The Overview is the thing where you select "share with all my contacts" and continue. But it seems to have been fixed?
