### ISSUE TITLE
Chat Session Refreshed - missed messages

### ISSUE THREAD

**Issue by xitij** [signalapp/Signal-Android#12721]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a user posts a twitter link with a preview sometimes the preview fails (I'm not sure the actual cause of this). When another user replies to the original message I receive a "chat session refreshed" message from that user and the message they sent is not there. This seems to only be a problem on Android (I have an Android phone but the replied message appears on Signal desktop).

### Steps to reproduce
- Have a user post a twitter link with a preview (not sure what link previews don't actually work). This doesn't work for all twitter links only ones where the link preview fails.
- Have any user quote that message.

**Actual result:**
- You will receive a "chat session refreshed" message from the user who quoted the message.
- You will be unable to see/read the quoted message on Android but on other platforms you be able to see it.
**Expected result:**
- You should not receive the "chat session refreshed" message.
- You will be able to view the quoted message.

### Screenshots
**Desktop view**
<img width="780" alt="Screen Shot 2023-01-10 at 23 13 19" src="https://user-images.githubusercontent.com/1811321/211717080-e62a6c73-208a-4676-a808-84d231ace11e.png">
**Android view**
Original message with link preview failure:
![Screenshot_20230110-231956](https://user-images.githubusercontent.com/1811321/211717301-6396fc51-2a71-4482-bf3e-8f488df91d5f.png)
Quoted message with missing message (you can see the message above in the desktop view)
![Screenshot_20230110-231156](https://user-images.githubusercontent.com/1811321/211717318-a83474ee-7a36-4711-b2ff-46080f3a989c.png)

### Device info
**Device:** Google Pixel 7 (also had the same problem on Google Pixel 2A).
**Android version:** 13.0.0 (build number TD1A.221105.001)
**Signal version:** 6.6.3

### Link to debug log

[signal-log-1673411825202.zip](https://github.com/signalapp/Signal-Android/files/10388909/signal-log-1673411825202.zip)

**Comment by xitij** [comment]
**Please note**
In the above screenshots the message in the desktop version with "Test" is the one I'm referring to...

**Comment by xitij** [comment]
Also sorry it's a Krassenstein twitter link, it's a bit. I do not endorse these hilarious hilarious weird twin brothers.

**Comment by greyson-signal** [comment]
Hi there, the log goes back to `2023-01-10 15:10:54.740 EST`, but I don't see any mention of a "Chat Session Refresh" event. Did it happen before then?

**Comment by xitij** [comment]
No it definitely happened after that. I actually asked my friend to resend his message so that it would be in the logs because I wasn't sure how far back they go. So I grabbed the logs after I had him repro it.

Is there anything I need to do to get it in the logs? Maybe open the DM that is generated from the friend where it says "chat session refreshed"? I also realized that I can repro this myself by just quoting the original message on my computer. I'm not able to see my own message on Android.

Please lmk how I can confirm or make sure it's in the logs.

**Comment by xitij** [comment]
Bump, would you like me to resubmit some logs?

**Comment by cody-signal** [comment]
Yes please. If you could repro it and then provide debuglogs right afterwards that would be helpful.

**Comment by xitij** [comment]
[signal-log-1674144452438.zip](https://github.com/signalapp/Signal-Android/files/10458456/signal-log-1674144452438.zip)

**Comment by xitij** [comment]
To repro this I found a message in one of my chats that was missing the link preview. I replied to it via Signal desktop, and then checked for it on my Android device. I receive a "Note to Self - Chat Session refreshed" message. I also checked the logs and I see entries from 01/19/2023 11:06 am, there do seem to be some errors in there as well.

lmk if you need anything else. Thanks.

**Comment by xitij** [comment]
Bump. Anything else needed here?
