### ISSUE TITLE
Unable to share location on Android

### ISSUE THREAD

**Issue by GitPudding** [signalapp/Signal-Android#12723]
Pixel 5
Android 13
CalyxOS 4.5.0
Signal 6.7.6

When trying to share my location, I am unable to send my location. Tapping the share location option will open the map screen, with the option to move the marker around, and a bar at the bottom of the screen with a checkmark and a loading wheel that continuously spins, but never does anything. When the checkmark is tapped, it will put a draft map location in the chat window, but there is no option to send it. 

I don't have Google maps, and use OsmAnd~ for maps.

**Comment by greyson-signal** [comment]
I've heard of people with similar setups having issues. A log would help me confirm it's the same issue, but the last time I saw a log related to this, the map implementation was throwing an exception when it shouldn't be, i.e. some bug in your device's implementation. If you provide a log, I'm happy to confirm.

**Comment by GitPudding** [comment]
https://debuglogs.org/android/6.7.6/732bf2d6ad53cb1b9b528921564ec35449c06cb60a2a6d70f980df871595e4d1

**Comment by bme13** [comment]
This seems similar to #9101. Based on your logfile you're also using microg and I see the next messages:
* GmsMap  : unimplemented Method: setBuildingsEnabled
*  GmsMap  : unimplemented Method: snapshot

Not the same as the 'GmsMap : unimplemented Method: setOnMapLoadedCallback' mentioned in the original ticket but I assume using microg is the reason.

**Comment by GitPudding** [comment]
Thanks for looking into this everyone. I appreciate the help!

**Comment by bme13** [comment]
Looking into this it seems the address returned in the PlacePickerActivity is correct. The problem likely is the missing snapshot method in microg, used in SignalMapView. I assume that's needed to know the map is rendered correctly. It appears to be on the list at microg. See https://github.com/microg/GmsCore/issues/1617

**Comment by t-m-w** [comment]
Don't close. Still impacts Signal 6.21.3. Thanks.

**Comment by fynngodau** [comment]
Even with snapshots now being implemented in microG (https://github.com/microg/GmsCore/issues/1617#issuecomment-1595810757), the correct map is still not shared. The reason is that microG does not implement `GoogleMap.OnMapLoadedCallback` correctly. See also: #13006.
