### ISSUE TITLE
Voice calls via phone speakers are too loud

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#12727]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice calls using the phone's speakers are too loud. (When I use a bluetooth headset, the volume is fine.)
Whenever I make or receive a Signal voice calls, they are way too loud -- I have to hold my phone 5-10cm away from my ear to make it bearable. I tried lowering the volume with the usual volume down button, but that volume slider is already all the way at the bottom. I expanded the volume menu to also see other volume sliders (just in case Android for some reasin would be adjusting the wrong volume) and moved them all down, which does not help.

Ironically, enabling the "speaker" mode actually makes the call a bit more quiet. It also cuts away a bunch of frequencies and it is still too loud for having the phone directly at my ear though.

(Yes, I double checked that speaker mode is "off" -- the button background is gray, not white -- before putting the phone to my ear, and experiencing the way too high volume.)

This makes it impossible to have signal voice calls in a public space without bluetooth: everyone around me would easily be able to hear the other side of the conversation, and would probably be very annoyed by that.

### Steps to reproduce
- Make a voice call with the phone's native speakers

**Actual result:** The volume of incoming audio is way too loud, and can easily be understood even when I put the phone half a meter away from my ear. That is at the lower volume that I can set.
**Expected result:** The volume should be the same as for regular phone calls: something where I can put the phone directly to my ear.

### Device info

**Device:** Motorola Moto G7 Power
**Android version:** 12
**Signal version:** 6.5.6

**Comment by RalfJung** [comment]
Yes, last time I tried this was still a problem.

Though it seems like there is little point in keeping this issue open anyway...

**Comment by greyson-signal** [comment]
Hi there, this seems like a device-specific issue that I can't reproduce on any of my devices. We defer to the system volume (i.e. the sliders you slide down) -- we can't go any lower than that, apologies.
