### ISSUE TITLE
Links in stories dont work on some devices

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12737]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Stories with Text and images work across devices.
But it seems links dont appear on many devices, Text with added links, the links are not sent.
Unsure if works with link only (no text)

### Steps to reproduce
- create a text story
- add a link
- the link shows on your device, but not on other peoples

**Actual result:**

Text shown, no link window / button.

**Expected result:**

Links working normally

### Device info

**Device:** Google Pixel 4a
**Android version:** 13 (5.1.2023)
**Signal version:** 6.1.4 official APK (doesnt self-update?)

**Comment by cody-signal** [comment]
Can you update to latest version of Signal? Should be 6.7.x or 6.8.x at this time. Also providing a screenshot and debuglog would be helpful as I'm unable to reproduce this myself.

**Comment by firefoxlover** [comment]
> Can you update to latest version of Signal? Should be 6.7.x or 6.8.x at this time. Also providing a screenshot and debuglog would be helpful as I'm unable to reproduce this myself.

I tried. I use the selfupdating apk so it should update itself??

The newest Version is 6.7.6

I tried verifying the SHA256 hashsum using Hashr but it doesnt match. Also I get an error "issue updating your package".

I dont use an unofficial version from F-Droid (firefox unofficial, Calyx or Twinhelix repo afaik), cant update it there.

**"Screenshot":**
On my phone you see text and the link button below.
On other phones (Android, iOS) you just see the text.

**Comment by cody-signal** [comment]
Looks like a fix was added in 6.9 that address some changes around links weren't rendering if someone has link previews disabled, so that could be it.

**Comment by greyson-signal** [comment]
When you talk about sending "links", are you sending a URL in a text story, or are you clicking the link button in the bottom left and attaching a link as a distinct object?

**Comment by firefoxlover** [comment]
> When you talk about sending "links", are you sending a URL in a text story, or are you clicking the link button in the bottom left and attaching a link as a distinct object?

This is a link bug caused by disabling link previews. This behavior doesnt fit the personally perceived one (just a link showing, no preview) and it is fixed with the new Update!
