### ISSUE TITLE
Keep on getting back to last chat using recent apps view after sharing link (link is also still in message box)

### ISSUE THREAD

**Issue by krwow** [signalapp/Signal-Android#12731]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After using share option in web browser (In most browsers it's similar to: Share → Signal → [some contact] → Send), I use back gesture (once), which gets me back to web browser. And if I try to open Signal from recent apps (Android gesture), I get back to chat with person I send the link to. And the link is still in the message box, despite it has already been sent, it's also as a message in chat. And if I use system back gesture again, I’m not in the chat list, I’m out of app again. If I want to get back to all chats, I need to open Signal from all apps list (launcher) or desktop shortcut.

That's a bug since a long time.

### Steps to reproduce
- open web browser of your choice
- navigate to website of your choice
- use "Share" in your web browser
- select someone from "Share" menu or select "Signal" and then someone inside app
- send link
- go back (I use gesture) to leave app (chat with someone)
- display recent apps menu and select Signal
- try to go back to all chats by going back one more time

**Actual result:** Chat with someone I sent message to is being opened again, message has been already sent, but it's also in message box, input box again
**Expected result:** Getting back to list of all chats or, in worse scenario, getting back to chat with someone I sent message to, but with empty message box and ability to quickly go back to all chats view.

### Screenshots

<img src="https://user-images.githubusercontent.com/65966603/213546265-5e01bfe3-8799-4a9d-a8a7-59af2ce5c9b6.png" width="108" height="234">

### Device info

**Device:** Google Pixel 4a
**Android version:** 13
**Signal version:** ~~6.7.6~~ 6.8.3

### Link to debug log

https://debuglogs.org/android/6.8.3/23464362223a741e0ad72f79e2efa94bafde933718dde41cc0017e4fea56137a

**Comment by clark-signal** [comment]
Hey thanks for the report! This should be fixed in 6.9.1 by 73b453b0d45b47a84e37c780dcf3a2a9d899c464

**Comment by krwow** [comment]
@greyson-signal, please make it opened again, not closed as bug is fixed in 6.9.2 only in part - there's no link in input box, but there's still no way to get back to chat list using recent apps. Or should I make another issue topic with mostly the same content?

**Comment by clark-signal** [comment]
I think that part should be fixed as well in 6.10 by d6356833037af2fa7ea25109a1a260b7e9929d65 if not, please let me know
