### ISSUE TITLE
Portal is not available for photos.

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12738]
Signal implements the file chooser portal only for files, which works very well. 

The "send" dialog solves that, but you cant change your profile picture through it, so you need to grant the App file permission.

This permission is one of the most sensitive ones, even though its not needed at all.

Avoiding the need for this permission makes Signal also immune to laws requiring client-side scanning for "child p*rn*graphy". Just not enable it, perfect.

Signal being open source does not change that, you could build it from source, avoiding the (assumed) proprietary scanning software, but nobody does that.

**Comment by greyson-signal** [comment]
Hi there, we don't intend to change our image picker for profile pictures.

**Comment by firefoxlover** [comment]
@greyson-signal yes I understand that, but an option to send images to profile picture would help. I can open a new issue.

**Comment by greyson-signal** [comment]
No need, we only use github for bug reports, not feature requests. But thanks!

**Comment by firefoxlover** [comment]
So what is the state of this? When disabling media permission on Android 14, the photo chooser is black.

I cannot edit an image if I select it through the filepicker portal.

Your photo chooser may have a different UI, but all Element Apps offer the native Android image picker portal, which looks great and doesnt require the app to have these vast permissions.

**Comment by firefoxlover** [comment]
https://community.signalusers.org/t/implement-androids-photo-picker
