### ISSUE TITLE
Official APK not updating itself

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12739]
I use the official APK downloaded from [this site](https://signal.org/android/apk/)

It is still on version

```
Version 6.1.4
org.thoughtcrime.securesms
versionCode 116005
targetSdk 31
minSdk 19
Installed: 20.11.2022
```

It doesnt show any update prompt.

Also trying to download the apk and manually updating it doesnt work, "incompatible with installed app".

**Comment by Sgn-32** [comment]
Is this issue related to yours?
_Updates are not checked via mobile data (only via Wi-Fi) for the APK-installed app._
https://github.com/signalapp/Signal-Android/issues/12711

**Comment by firefoxlover** [comment]
> Is this issue related to yours? _Updates are not checked via mobile data (only via Wi-Fi) for the APK-installed app._ #12711

No its not, I didnt get any updates anymore. I manually uninstalled and installed the new version, which works normally. Couldnt restore the backup, just crashed, 30k messages lost, luckily nothing important and I have a desktop client with notes.

**Comment by nicholas-signal** [comment]
Are you 100% sure you downloaded the original APK from our site? The message you describe sounds similar to the message that appears when trying to install an APK that has a different [signature](https://source.android.com/docs/security/features/apksigning) than the version that's currently installed. This suggests that the installed version was built and signed by a 3rd party.

For the sake of clarity: as @Sgn-32 suggested, we only support automatic non-Play-Store updates over unmetered connections such as WiFi.

Now that you have the signal.org version installed, please re-open this issue if you are not presented with future updates when connected to WiFi.

**Comment by firefoxlover** [comment]
I am sure it was an official version, there was no FDroid repo used too. Anyways, autoupdates work normally now.
