### ISSUE TITLE
Video Lag while on a call

### ISSUE THREAD

**Issue by andyxheli** [signalapp/Signal-Android#12741]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
Video call someone from Android to ios

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
Samsung S22 Ultra
**Android version:** 0.0.0
13
**Signal version:** 0.0.0
6.8.3

### Link to debug log
<!-- immediately after the bug has happened capture a debug log via Signal's settings (Help -> Debug log) and paste the link below -
->https://debuglogs.org/android/6.8.3/d2b9c94cfc170a0f3a90e0ebc96c003f509fbe39b2084c785357bad55121e451

**Comment by cody-signal** [comment]
Without a debuglog (and preferably one from the person you are calling as well) we can't do anything.

**Comment by andyxheli** [comment]
https://debuglogs.org/android/6.8.3/d2b9c94cfc170a0f3a90e0ebc96c003f509fbe39b2084c785357bad55121e451

**Comment by andyxheli** [comment]
here you go sorry. that sure why is not showing under the original post

**Comment by andyxheli** [comment]
Hi @cody-signal Any feedback on this ?
