### ISSUE TITLE
Jump to bottom of message thread button makes sound even after it has been clicked and has disappeared. 

### ISSUE THREAD

**Issue by zjs81** [signalapp/Signal-Android#12740]
- [X] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On long message threads, the down arrow will disappear visually however, if you tap on the spot where it disappeared it will still make the tapping sound. 

### Steps to reproduce

1. Send messages to a recipient until your screen is full of messages.
2. Drag the screen up to see the past conversation. 
3. The jump to the bottom arrow should appear
4. Make sure that your sound is turned all the way up on your device for system sounds.
5. Tap the arrow repeatedly
6. You will hear the tapping sound even when the arrow isn't there. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
You will hear a tapping sound even when the arrow is not on the screen. 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
It should make the sound once then you will not be able to hear anything after tapping in the same spot. 

### Device info
**Device:** Samsung S21 Ultra
**Android version:** 13
**Signal version:** 6.8.3

**Comment by cyclonejet** [comment]
For me, the tapping sound plays whenever touching anywhere, not necessarily the arrow key. It plays when I tap a message, or when I touch a blank space in a conversation.

Could you try and tap somewhere in a conversation window before the arrow appears to see if the tapping sound plays?
