### ISSUE TITLE
Receiving a call deleted recorded audio/voice memo

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12747]
When I record an audio for someone and I get a call over signal, the audio is cancelled and delted.

## Problem
Audio is deleted, not stored.

## Solution
Pause the audio, dont delete it, have it pending to be sent

## Solution 2
Just send the audio when you receive a call

Using newest self-updating APK

**Comment by greyson-signal** [comment]
This should be fixed in 6.10, going to beta this week (hopefully tomorrow). Thanks!
