### ISSUE TITLE
Interacting with stories on Signal Desktop changes Signal Android disappearing messages settings

### ISSUE THREAD

**Issue by ultr41337h4xor** [signalapp/Signal-Android#12745]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Very strange interaction when using the Signal Desktop app to react and reply to other people's stories. I have only tested this for a single group story, as it is the only place where I use stories. The bug occurs when replying/reacting, either through the dedicated reaction part on the right, or when typing an emoji as text to a friend's story (it even happened once when typing a single letter as a reply, but the former two caused it every time when the bug was occuring). What happens is that each time a reply is sent through the desktop app, the disappearing timer for the group chat changes between "1 day" and "Off" in the android app version of the group chat.

Several interesting things I've noticed:
1. I tried to reproduce it again and it didn't happen, but it was happening for like an hour before. Tried again 5 minutes later and now it's happening again, so it seems to be intermittent (or perhaps another action stops it?).

2. the android client is the only device where the change happens (no notification about settings being changed in the desktop app, nor is the actual setting in the desktop group settings changed, while it was changed in the android group settings)

3. aside from myself, two other group participants have apparently turned the setting off (after my unwittingly having turned it on through this bug), without them having actually done it themselves, both of them rarely using the desktop app and one of them even having stories turned off

4. nobody (aside from myself) can actually see the notifications about disappearing messages being turned on/off, but they could see the timer icon on my message, when the setting was turned on

5. when the setting for disappearing messages was turned on, my messages were indeed disappearing (had the timer icon), but the other group participants' weren't

6. can't see my own group story on desktop app (working as intended or another bug?)

### Steps to reproduce
- on the signal desktop app, react to another person's group chat story, or send emojis/text as a reply

**Actual result:** Setting for "Disappearing messages" is changed to "1 day" or "Off" in the android settings of the group chat (depending on what the setting was beforehand)
**Expected result:** The "Disappearing messages" settings shouldn't be changed

### Screenshots

![image](https://user-images.githubusercontent.com/86489731/213947719-c7e35f07-9523-408b-8c6c-148fd35068d2.png)
![image](https://user-images.githubusercontent.com/86489731/213947843-69c0f9aa-9e91-47b9-910e-f35cd840c2c8.png)
![image](https://user-images.githubusercontent.com/86489731/213947927-7e91437a-021f-4491-895b-7ba54d2964f6.png)
![image](https://user-images.githubusercontent.com/86489731/213947997-2659f9c9-e017-4af0-9f3d-6291553d36ce.png)
![image](https://user-images.githubusercontent.com/86489731/213948147-3c928414-4963-4219-8ee3-80c9a766f3f9.png)

### Device info

**Device:** Fairphone 3+, Lenovo Legion Y520
**Android version:** LineageOS 19.1 (Android 12)
**Desktop version:** Windows 10 Pro N
**Signal version Android:** 6.8.3
**Signal version Desktop:** 6.2.0

### Link to debug log

**Debug log android:** https://debuglogs.org/android/6.8.3/33f248f74f6694917be1177a3b6a1b1fdb98cff62d1f5a9fce26b95c5aeae034

**Debug log desktop:** https://debuglogs.org/desktop/6.2.0/d91852eb31ed65346913ea6afacd5b9b1ee7daf7e5497cef9afd7e4d1b4f8ab5.gz

**Cross post in Signal-Desktop:** #[6254](https://github.com/signalapp/Signal-Desktop/issues/6254)

**Comment by cody-signal** [comment]
Hi there, this was a double bug on desktop and android. We'll be rolling out a fix shortly. Android's is in 6.9.1 beta. But we may be hotfixing backing to .6.8.x

**Comment by greyson-signal** [comment]
This should have been fixed a while ago.
