### ISSUE TITLE
Backup fails at 99% due to 'your backup is too large to store on this volume'

### ISSUE THREAD

**Issue by lbacherle** [signalapp/Signal-Android#12742]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
-i look at the size of my signal app: 10GB
- i select a folder on my sd card for backup that has 50GB free
- li start a backup
- the backup fails at 99%  with the error message 'your backup is too large to store on this volume'

**Actual result:** the backup fails at 99%  with the error message 'your backup is too large to store on this volume'
**Expected result:** the backup works as intended

### Device info

**Device:** Redmi Note 8T
**Android version:** newest
**Signal version:** newest

**Comment by cody-signal** [comment]
Can you provide a debuglog?

**Comment by DavidMndz** [comment]
Have you checked the format of the sd card? If it is formatted with an old format type, it might be allowing files only up to 4GB.

**Comment by partofthething** [comment]
> Have you checked the format of the sd card? If it is formatted with an old format type, it might be allowing files only up to 4GB.

FWIW this was the issue for me when I had this exact error. My SD card was formatted with FAT32, which has a max file size of 4 GB. When I reformatted it as exFAT, the backup worked.
