### ISSUE TITLE
Emoji not rendered the same

### ISSUE THREAD

**Issue by ceever** [signalapp/Signal-Android#12750]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoijs look different, depending on whether they appear in the text or as notation to a chat.

### Steps to reproduce
- Send a emoji in a chat
- Add a notation to a chat using the same emoji

**Expected result:** 
Emojis should look the same within the app

### Screenshots
See comment below

### Device info
**Device:** Samsung Galaxy S8
**Android version:** 9
**Signal version:** 6.6.3

**Comment by ceever** [comment]
![20230125_134523](https://user-images.githubusercontent.com/40247591/214581620-779c2d94-743b-4c1c-88a2-2b406819a6db.jpg)

**Comment by greyson-signal** [comment]
Hi there, we don't currently support system emoji in reactions.

**Comment by MrRinkana** [comment]
> Hi there, we don't currently support system emoji in reactions.

It would be great if that could be changed.

The apple emojis **feel weird to an android user**. The noto-emojis from google are used in many linux distros, and are more similar to the windows emoji font - in other words will be **more familiar to most**.

Having **mixed emojis really gives a less polished look**.

Maybe this last point is from my own bias preferring the look of the noto emojis but the apple ones have shading that sticks out in most material-styled apps, i.e. create a dissonance with the more flat themes.
