### ISSUE TITLE
Filtered view is not dismissed when there are no more "unread" messages 

### ISSUE THREAD

**Issue by clauz9** [signalapp/Signal-Android#12753]
- [X] I have searched open and closed issues for duplicates
- [ ]  I am submitting a bug report for existing functionality that does not work as intended 🤷
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
if you use the unread message filter and open the last conversation that has an unread message, after you exit the conversation by tapping back, you still see the filtered view, instead of all your conversations.. 

### Steps to reproduce
- have some unread messages
- pull down to enable the unread message filter
- enter your last conversation that has unread messages
- exit it, by tapping back

**Expected result:** Go back to your conversations list

### Screenshots

<details>
<summary> screenshots</summary>

![image](https://user-images.githubusercontent.com/77681918/215073401-6ac624f8-ebcd-4365-8ff8-63e029cc41a4.png)

</details>

### Device info

**Device:** Nokia 3.1
**Android version:** 10
**Signal version:** 6.10.1

### Link to debug log

Sent an e-mail to support@signal.org with the debug log link and this as message body `4cb98818-a3df-4a69-be6b-95772c377e73` to make it searchable...

**Comment by finn-signal** [comment]
Thank you.

We will reach out via the ticket you submitted if we need additional information.
