### ISSUE TITLE
Cloud messaging not recognized when enabled after installation

### ISSUE THREAD

**Issue by HerrBert233** [signalapp/Signal-Android#12758]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Let's assume you have LineageOS with MicroG. Cloud messaging was disabled by default. You installed Signal. Everything worked as expected, but later Signal drained too much battery. So you decide to switch from websocket mode to fcm mode. You go to microG setting, enable could messaging, then go back to the Signal app: but surpise: fcm is still not used (according to debug log). I search every option in signal, restarted the app. Nothing. fcm is permanently disabled. Probably it was decided during installation and now it uses websocket forever.

### Steps to reproduce
- Disable could messaging.
- Install Signal.
- Enable cloud messaging.

**Actual result:** fcm is not used an no option to turn it on.
**Expected result:** Either fcm is now used, **or** there is an option to turn on fcm post installation.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 12 (LOS19)
**Signal version:** 6.9.2

### Remark
Please don't tell me "just reinstall the app" / "reinstall LineageOS" or any other infeasible solution. This will make me loose all my data and chats. It's also not technically required to do all this, it's just that there is missing a check, maybe a single line of code, maybe just change the event listener from "on_app_install" to "on_app_startup" or whatever. Implement a checkbox. Technically, this is all doable. It's just missing and that's a problem, and in my case a huge problem because battery runs low very fast now and I really need to switch to fcm to solve this, but I can't because your app doesn't let me.
It is a bug because every interface designer in the right mind would have implemented such an option. It' absence is not a matter of taste but a severe design flaw.

**Comment by sussycatgirl** [comment]
> This is currently how it works, yeah. I tried doing a thing where we'd dynamically go back and forth, but many people will intentionally disable FCM during registration and then turn it back on afterwards, but they want it to stay off in Signal forever, so this messed with them. So it'd require some new UX to allow the user to flip some switch, and I don't know when we'll get around to doing it. This is pretty niche usecase.

MicroG actually allows you to disable cloud messaging registration for specific apps, which is certainly more convenient to do than temporarily disabling cloud messaging entirely.

Signal is the only app that consistently has problems with FCM in my experience, it'd be great if registration could be handled in a better way :3

I know I can restore a backup after reinstalling the app, but at this point my chats grew over 20gb so the entire process takes over 40 minutes, during which I won't be reachable :(
