### ISSUE TITLE
"Read More" behavior is different from clients on other platforms

### ISSUE THREAD

**Issue by leftl** [signalapp/Signal-Android#12757]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Expanding long messages containing text via "Read More" is handled differently on the Android client, as compared to the iOS and desktop clients. 

Rather than expanding the text bubble within the context of a conversation, a new view is shown to the user containing only the contents of the message. To respond to the messages or otherwise interact in the conversation, you must exit this view. This makes it difficult to respond to longer messages as you must jump between contexts, one with the full message contents and another with text-input. 

The way you interact with expanded text does not match the UX of other clients, which is why I've reported it as a bug.

### Steps to reproduce
- Write a message containing more than approx. $1052$ characters.
- Click the "Read More" span on the message bubble.

**Actual result:** A new view is displayed containing only the contents of the message.
**Expected result:** The message is expanded inside the bubble within the conversation itself, as done on other clients.

**Comment by greyson-signal** [comment]
Hi there, we're aware of the difference. Thank you for the feature request, but we reserve github for bug reports. Thanks!

**Comment by leftl** [comment]
I'd argue inconsistent UX *is* a bug, but thanks for taking the time to reply.
