### ISSUE TITLE
Videocall doesn't enforce camera permission again, after camera was used.

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12754]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Android (13) only one app can access the camera. If another app accesses the camera, it may get the permission. This has to be controlled somehow, as some apps say "Camera not accessible" if another app currently uses it.

### Steps to reproduce
- start a videocall
- create a new story / open a camera appp
- The story/camera app needs camera permission and the video in the call freezes

**Actual result:** The videocall freezes, as the call doesnt request camera permission again

**Expected result:** Test if camera permissions are available, if not request it again

### Screenshots
(Frozen videocall)

### Device info
Device: any Android 
Version: Grapheneos based on Android 13
Version: 6.9.2 self-updating

**Comment by firefoxlover** [comment]
This is an important issue. Please either solve it or not ignore it.

**Comment by firefoxlover** [comment]
this is not stale. it is still an issue

**Comment by firefoxlover** [comment]
I will try

**Comment by firefoxlover** [comment]
interesting. New behavior now is, that when a videocall runs and you use your camera, the camera in the call simply gets deactivated.

The bug thereby is still not fixed, maybe this is the intended behavior now?

**Comment by nicholas-signal** [comment]
I'm not sure I follow.

Only one surface can access the camera feed at one time. So if you choose to background an ongoing video call and open the camera page, then the camera page takes precedence over the ongoing call. Therefore, we toggle off the video (so the state is reflected to the other participants in the call) and honor your intention to use the camera page.

**Comment by nicholas-signal** [comment]
> could the app remember its camera state and when it is in the foreground, enable it again?

I will raise this to our Design team and ask if they would prefer that behavior.
