### ISSUE TITLE
notify app arrived on icon does not work

### ISSUE THREAD

**Issue by KeesBleijenberg** [signalapp/Signal-Android#12765]
About 2 month ago Signal showed the number of arrived apps on the icon. It does not work any more.
The same thing works flawless on WhatsApp installed on the same phone.
Signal has version 6.9.2
I'am on Android with MIUI 12.5.7
It looks like a bug...?

Kees

**Comment by greyson-signal** [comment]
Hi there, we don't actually set the badge count. The OS usually does it based on notification count.

**Comment by LinuxOnTheDesktop** [comment]
The original reporter means 'message arrived', not 'app arrived'.

I too see no badge showing new Signal messages - but I do on my SMS program and on WhatsApp. (I am on Android 13.) That combination of affairs suggests a bug within Signal (or at least a workaround-for-a-bug that Signal is not implementing). So I submit that this issue needs re-opening.

**Comment by greyson-signal** [comment]
Different launchers do it differently. And it's possible that some launchers have specific API's that they may make available? But in general it's up to the launcher to do this, and almost universally they do it based on notification count. You usually need to give the launcher notification access to do it. I just check and Nova Launcher Prime shows the "notification dots" just fine for Signal.

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response.

I myself use Nova. Nova shows a 'dot' for signal in the status bar, but no 'badge' on the icon itself (that icon being in my 'dock').

**Comment by greyson-signal** [comment]
For Nova, you have to go to the Nova settings > Notification badges > Choose style and select Numeric Dots. You also have to make sure Nova has notification access. It's working fine for me :)

![Image](https://github.com/user-attachments/assets/ecb10930-a7f7-463a-8391-6edde1cf23a2)

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but I have those options enabled already; if I did not, I would not seen the badges - on WhatsApp and my SMS app - that I mentioned.

Toggling Nova's 'notification badges' option does not help. Changing icon set does not help. The icon, in the dock, does have a context-menu that has a 'show badge' tickbox, but when I tick it the result seems to be a kind of smudge in the bottom-right of the icon (irrespective of icon set; and I have Nova set to show badges at the _top-right_). Here's an image of that 'smudge':

![Image](https://github.com/user-attachments/assets/976f1d88-4a31-4f75-8135-23f527612a46)

Nova provides a test for, seemingly, notifications-and-notification-badges: if one creates a Nova Settings icon, then running the test should not only generate a notification but also a badge. I did create such an icon, a notification did appear, but no badge appeared. Perhaps I misunderstand the test. Yet, as I say: other apps have working badges.

**Comment by greyson-signal** [comment]
I'd honestly report a bug to Nova. If we have notifications in the tray, they should be able to read them. It obviously works for me on Nova, so might be something unique to your setup.

**Comment by LinuxOnTheDesktop** [comment]
I find that even with my phone's default launcher (which brings the default icons with it), Signal displays the badge incorrectly:

![Image](https://github.com/user-attachments/assets/309ab3e6-538d-49c9-ab8d-451bf34f57b7)

I note also that there have been several Signal bugs involving buttons, viz.: 

- #2358
- #3842
- #6245

**Comment by LinuxOnTheDesktop** [comment]
But perhaps the problem is not with Signal after all . . Inspired by [this](https://support.google.com/messages/thread/203301732/google-messages-not-showing-app-notification-badges-on-android?hl=en), I've tried toggling Nova's 'notification badges' option, with a reboot in-between. I will see if that works. (I have to await a Signal notification.) If it does not work, I discover that [there is a more nuclear option](https://old.reddit.com/r/S23/comments/188or6x/app_icon_badge_numbers_not_working/), which consists in reset Nova's data.

**Comment by greyson-signal** [comment]
>  I find that even with my phone's default launcher (which brings the default icons with it), Signal displays the badge incorrectly

I know Nova and some OEM's add the count option, but I thought the stock behavior was to only show a "dot" when notifications are present _at all_? Because the Android SDK does not actually have a mechanism to directly communicate "unread count" -- everything is calculated based on notifications and their properties, so the stock launcher plays it safe and doesn't actually show a count.

**Comment by greyson-signal** [comment]
I would report it to Nova, yeah.
