### ISSUE TITLE
Call information not properly translated on Chat overview

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12762]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the Chat overview, the info about videocalls is not properly translated.

Language:
Android: German
Signal: English

But instead of displaying 'Outgoing Videocall' it shows 'Ausgehender Videoanruf'. Interestingly, it is correctly displayed inside the chat.

This may be related to https://github.com/signalapp/Signal-Android/issues/11353, but I doubt it since the dates are correctly (= english) shown while the videocall is still on German. See the Screenshots below

### Steps to reproduce
- Enter Chat
- Start Videochat
- Go to Chat Overview

**Actual result:** Videocall-Info on Chat overview is in German
**Expected result:** Videocall-Info on Chat overview is in English, since this is the Language set in Signal

### Screenshots

Chat Overview:
![grafik](https://user-images.githubusercontent.com/62468040/215867176-2f439b51-4552-4a5d-aac4-e9113f42c618.png)

Inside Chat its correct:
![grafik](https://user-images.githubusercontent.com/62468040/215866896-691e1c04-cb4d-4ec9-8dc6-5c4fc634de34.png)

### Device info

**Device:**OnePlus 8T
**Android version:** 13
**Signal version:** 6.9.2

**Comment by Sgn-32** [comment]
Can you also check other calls (incoming/outgoing voice/video calls), 'voice messages', photos, files and videos?

Seems relevant to this in `ThreadBodyUtil.java`

`private static @NonNull ThreadBody getFormattedBodyForMms(@NonNull Context context, @NonNull MmsMessageRecord record) {`

**Comment by MorgeMoensch** [comment]
This happens also with incoming and outcoming calls, as well as photos. Didn't test the other options, but it will probably occur there as well.

**Comment by cody-signal** [comment]
@MorgeMoensch I'm unable to reproduce this on the latest versions of the app (6.11.x in beta). Could you try again when a new version of Signal becomes available to you in your preferred release channel.

**Comment by Sgn-32** [comment]
Tested with 6.11.2 beta. Issue still there. For testing set device language to german, french and dansk. Signal app to english.
Having a voice message as last message in an conversation, shows the dansk string.
Hint: the string didn't changed directly. Only after entering the conversation and going back to the conversation list.

![Screenshot_1675870663](https://user-images.githubusercontent.com/49990901/217577970-84b724fb-da78-4d02-b7e9-609a4942566e.png)

**Comment by Sgn-32** [comment]
Tested with 6.11.4 beta on virtual device. Seems it depends on the correct order.
1. change the language in Signal, e.g. espanol
2. change the device language, e.g. dansk
3. go in a conversation and than go back to the conversation list

when later the Signal language is changed to another language and repeat step 3, the string is shown correct in the new language.

**Comment by MorgeMoensch** [comment]
This still happens with Signal 6.21.3

**Comment by MorgeMoensch** [comment]
Still happens on 6.27.10

**Comment by alex-signal** [comment]
My immediate thought is that we're storing translated string content in a thread snippet in the database (which is why it self-corrects if you enter and leave a conversation). We'll have a look.

**Comment by MorgeMoensch** [comment]
You're probably relating to the the reproduction-guide by @Sgn-32, but just to to make sure you're understanding correctly: For me, inside the conversation it is always in the proper language, and never in the chat list (also not when entering a conversation and returning to the overview).

**Comment by alex-signal** [comment]
@MorgeMoensch Is it always a group calling notification causing it? It's possible there's a missing translation somewhere.

**Comment by MorgeMoensch** [comment]
@alex-signal Nope, 1:1 Calls

**Comment by MorgeMoensch** [comment]
Does no longer appear in 7.8.1
