### ISSUE TITLE
problem to create new account or backup old account could not verify or show this pop-up messages

### ISSUE THREAD

**Issue by shahariarnavil** [signalapp/Signal-Android#12766]
problem to create new account or backup old account could not verify or show this pop-up messages
i also could not get verification code also
plz help me out or fix the problem

![IMG_20230202_201027_906.jpg](https://user-images.githubusercontent.com/86552801/216347390-4ec3e6ab-b5d9-4067-a31c-dd10da3e59a5.jpg)

**Comment by shahariarnavil** [comment]
@alex-signal

**Comment by nicholas-signal** [comment]
Hello,

As the pop-up describes, you have exceeded the current rate limit. Please try again in 24 hours.

Depending on your country and carrier, it is possible that your carrier may be blocking Signal SMS codes.
