### ISSUE TITLE
UI Bug in Data and Storage Settings

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12763]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
That void space with the darker colour seems inconsistent with the other Settings-Pages. Both in Light and Dark Theme.

### Steps to reproduce
- Open Settings
- GoTo Data and Storage
- GoTo Manage Storage

**Actual result:** Background has darker "void" in between two components
**Expected result:** All background has the same colour

### Screenshots

![grafik](https://user-images.githubusercontent.com/62468040/215868300-f08f30c9-cfe0-475f-bb58-77f22f3b109b.png)

![grafik](https://user-images.githubusercontent.com/62468040/215868779-ffa848d7-7820-4b6a-baa0-6825a10afb17.png)

### Device info

**Device:** OnePlus 8T
**Android version:** 13
**Signal version:** 6.9.2

**Comment by nicholas-signal** [comment]
This is working as intended at this time.
