### ISSUE TITLE
(Video) Call Icon not properly aligned

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12761]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The icon for an outgoing call is not properly aligned. On the Chat overview as well as in the chat

### Steps to reproduce
- Start a Videocall with another person
- end the call
- (go to Chat overview)

**Actual result:** Icon isn't properly aligned on the vertical axis
**Expected result:** Icon is properly aligned (vertically centered in relation to the text)

### Screenshots
Chat Overview: 
![grafik](https://user-images.githubusercontent.com/62468040/215865615-1be1f1b4-ce1f-480a-ba09-8eec87e5d5d9.png)

Chat:
![grafik](https://user-images.githubusercontent.com/62468040/215865667-c5457d0b-b2e4-4331-ac86-adc15a5ee7bc.png)

### Device info

**Device:** OnePlus 8T
**Android version:** 13
**Signal version:** 6.9.2

**Comment by MorgeMoensch** [comment]
Still exists on 6.15.3

**Comment by cody-signal** [comment]
We are aware, it's a limitation of how we have our assets. We have new assets in the works to address it. Going to leave closed.
