### ISSUE TITLE
Wrong Notification Text when in fullscreen mode

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12767]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal "short" Notifications do double the First and Last Name. It seems like the Scheme for Group Notifications is used in 1:1 Chats.

Notification in Signal Settings are set to 'Name only'.

### Steps to reproduce
- Open a YouTube Video in Fullscreen (native App)
- receive a Notification from a 1:1 Chat

**Actual result:** First and Last Name show up twice
**Expected result:** First and Last Name only show up once

### Screenshots

That's how Signal shows up:
Firstname Lastname: Firstname Lastname New Message
![grafik](https://user-images.githubusercontent.com/62468040/216406959-c2a30f03-4e3c-49cd-871c-391cf8933771.png)

That's how it shows up with Threema:
Firstname Lastname 1 new Message
![grafik](https://user-images.githubusercontent.com/62468040/216407145-b31c58fc-30bc-40d9-b03e-2dfe7c8bf3a9.png)

### Device info

**Device:** OnePlus 8T (since Threema is able to display them correctly, this should be fixable by Signal as well)
**Android version:** 13
**Signal version:** 6.9.2

### Link to debug log

https://debuglogs.org/android/6.9.2/51c6cca73f3a7cebf13ed21e950f4ec556d6eda9cc4285dd92ae5fca7e27f703

**Comment by cody-signal** [comment]
Hrm. This is really odd. I can't reproduce your issue specifically, but can get some weird behavior with multiple notifications from different chats. It seems like this mode is pulling data oddly from our notifications to render it in the compact view.

**Comment by MorgeMoensch** [comment]
hi @cody-signal 
It seems to me as if the group-scheme is wrongly used in 1:1 Chats as well. The following screenshot shows what happens with a group message (this is fine):

![grafik](https://user-images.githubusercontent.com/62468040/217377620-ac57551f-7033-41ec-a442-ba2f894ccb6e.png)

Since it works fine with Threema it's maybe worth to have a look at their Source Code? https://github.com/threema-ch/threema-android

**Comment by MorgeMoensch** [comment]
This still occurs.

I observed that it only happens for the first notification. If the same user sends another message shortly after, the notification gets displayed correctly.
