### ISSUE TITLE
Backup restoration crash on autofill phrase

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#12769]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On backup restore when app asks for backup phrase there is no initial proposal for auto-fill but this should be offered.
On long clicking the input field android offers me to paste clipboard and a auto-fill option behind a 3-dot menu (img1).
After coosing auto-fill with Keepass2Android the app crashed with notification "_Failed to build an autofill datatset_"

### Steps to reproduce
- start a fresh Signal installation
- try restore from data file
- use auto-fill provider e.g. Keepass2Android to input backup pass phrase

**Actual result:** App crashes
**Expected result:** App should accept the provided pass phrase and restore backup file

### Screenshots

<img src="https://user-images.githubusercontent.com/14954521/216665934-f71e6e87-c76c-450b-b0b5-c877daf66c24.jpeg" width=40% height=40%>
<img src="https://user-images.githubusercontent.com/14954521/216665960-d175ebfd-59da-444e-aa93-37657469dedf.jpeg" width=40% height=40%>
<img src="https://user-images.githubusercontent.com/14954521/216665978-04f142dd-9b23-45b7-9be3-74c670269501.jpeg" width=40% height=40%>

### Device info

**Device:** Sony XZ2c
**Android version:** 12 (LOS19.1)
**Signal version:** 6.7.6

### Link to debug log

https://debuglogs.org/android/6.7.6/da9289bfa8267159e3facb0ed0b5fddb48b07cdf0a8c304e2a6c50b1a8129e16

**Comment by alex-signal** [comment]
Hi! Thanks for the bug report. Unfortunately, it appears you've hit a bug not with Signal, but with Android 12:

https://issuetracker.google.com/issues/228529893

**Comment by UserX404** [comment]
Thx for pointing this issue.
This [comment](https://issuetracker.google.com/issues/228529893#comment13) says this bug won't be fixed for Android 12 but has been already fixed for Android 13.

Due to this information it sounds it's not an issue with signal.
-> closed
