### ISSUE TITLE
WHY YOU REMOVING TRADITIONAL SMS SUPPORT!??!?!?!?!?

### ISSUE THREAD

**Issue by Yszty** [signalapp/Signal-Android#12764]
Whats the reason of this decision? BIGGEST ISSUE HERE!!!!!

**Comment by nicholas-signal** [comment]
The GitHub Issues are for bug reports. Please provide feedback on our community forum.

**Comment by Yszty** [comment]
I know what the issues are for, but I coudnt stop myself...

` It’s important that people don’t mistake SMS messages sent or received via the Signal interface as secure and private when in fact they are not.`

Well, it's a bit disapointing, but all right. Some things need to be done for the greater good.

Why signal remove SMS support:
https://www.signal.org/blog/sms-removal-android/
