### ISSUE TITLE
cannot transfer from old to new android phone

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [signalapp/Signal-Android#12779]
Old phone: Pixel 4a5G running latest updates (app+OS)
New phone: Pixel 7 running all latest updates

Logs: https://debuglogs.org/android/6.11.2/1cee0b40d3287b3439e0b9ca7a03c0132466b0908a5156092675ac3d3d896f

To reproduce:
Open signal app on both phones
Select transfer from old phone on new phone
Follow instructions on old phone
Hit allow when asked to connect
Verify codes and hit continue
Observe devices fail

**Comment by alex-signal** [comment]
Hello! Sorry to ask, but could you please upload a new debug log?

**Comment by gidoBOSSftw5731** [comment]
Weird that that didn't work, here's a log for the new and old phone (respectively)
https://debuglogs.org/android/6.11.2/2ce60a8e570f51e4bb95ddda9eb29b9fa80735df7c5b1e746d3f1556b1a6e809
https://debuglogs.org/android/6.11.2/1980ea36fe99566b49b0364b17dd2d3d1757bbb0bef29bf1e2f9e1ba2352058f

**Comment by drujd** [comment]
Same problem. Transferred from Samsung S8+ to S23 Ultra, lost all my data and history. The new phone just re-registered without loading any data from the old phone. 😭

**Comment by alex-signal** [comment]
@drujd Could you please add a debug log?

We recently released 6.11.4 which should have fixes for the bad foreign key issue folks were seeing during transfers.

**Comment by drujd** [comment]
> @drujd Could you please add a debug log?

Will a debug log not containing the process of transfer any useful? I cannot replicate that anymore, my old phone is gone. A peek in the debug log reveals that it contains just data from current run of the app.

**Comment by drujd** [comment]
https://debuglogs.org/android/6.10.9/c2c317852da3f935d8952a5205402dc1dd2a7c40b94bfdd01f14818425b0fdb3

**Comment by drujd** [comment]
The attempt to transfer data happened around 2023-02-09 21:15 (the start of the log). What I think happened is that the transfer somehow failed without explicitly letting me know that fact and I just continued in standard new registration. I did found it weird that I have to do all stuff new registration requires and even had problem with authentication SMS not arriving (had to accept the call).

**Comment by gidoBOSSftw5731** [comment]
> > @drujd Could you please add a debug log?
> 
> Will a debug log not containing the process of transfer any useful? I cannot replicate that anymore, my old phone is gone. A peek in the debug log reveals that it contains just data from current run of the app.

I'd note that a lot of people transfer their signal data over when they are getting rid of their old phone. I'm able to carry two phones, but that's not a luxury everyone has. Because of that, I'd consider this a pretty time-sensitive bug.

**Comment by drujd** [comment]
Actually I have checked the log and it seems it does contain logs from the transfer process. Hence I deleted that comment.

**Comment by gidoBOSSftw5731** [comment]
The new update fixed this issue. Closing as my specific issue is fixed. 

> @drujd Could you please add a debug log?
> 
> We recently released 6.11.4 which should have fixes for the bad foreign key issue folks were seeing during transfers.
