### ISSUE TITLE
Transferring data requires one to disable registration lock

### ISSUE THREAD

**Issue by paultheweird** [signalapp/Signal-Android#12770]
When transferring data from an old device to a newer one, the user will have to disable the registration lock on their account before being able to start using Signal with the old data on the new device. There's a few issues with this:

- The documentation on the [website](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_transfer) does not mention this 
- The app on either phone makes no mention of this
- There's no way to do this on the old phone if you've just transferred data to the new phone

The feature request is to add a warning in the app to alert the user to this fact and suggest they disable the registration lock on the old device. Adding a similar reminder on the website would help too.

**Comment by nicholas-signal** [comment]
Hello,

GitHub Issues is for filing bugs. Please submit feature requests to our [Community Forum](https://community.signalusers.org/).
