### ISSUE TITLE
Delete message prompt doesn't resize for vertical orientation

### ISSUE THREAD

**Issue by alexWhitworth** [signalapp/Signal-Android#12774]
![Screenshot_20230205-210443](https://user-images.githubusercontent.com/13594486/217163805-7a15c3a0-f30f-4453-b5d2-36dfc22a88d4.png)

Signal App v6.9.2
Google Pixel 4a (5g)

When I select a message and try to delete with phone oriented vertically, the "cancel" and "delete" buttons do not display. the popup doesn't auto-resize for screen width.

_Note: I can't reproduce today and it seems v6.9.2 came out today, so perhaps this was a 6.9.1 bug._

**Comment by alex-signal** [comment]
I'm going to close this out since you can't repro
