### ISSUE TITLE
incoming calls vibrate only once

### ISSUE THREAD

**Issue by dkwo** [signalapp/Signal-Android#12780]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When the phone's 'Ring & notification volume' is set to minimum, an incoming Signal call makes it vibrate only once (as opposed to many times).

### Steps to reproduce
- set volume as described
- receive a Signal call

**Actual result:** The phone only vibrates once.
**Expected result:** It should vibrate many times, for as long as the other end is calling me. Incidentally, this is what happens with regular phone calls as well as Whatsapp calls: the phone vibrates repeatedly, for as long as the other party is calling me.

### Device info
**Device:** pixel 6a
**Android version:** 13 (GrapheneOS)
**Signal version:** 6.10.8

**Comment by dkwo** [comment]
nothing has changed, issue still present.

**Comment by dkwo** [comment]
when thye call me, the incoming call screen appears; if the phone is on vibrate mode, it vibrates only once; if instead it's on ring mode, it rings many times, as expected.

log: https://debuglogs.org/android/6.16.2/2589d0e189ab4548b3c2af825c53be187228c25a01271cb7ab223f51cee0fd7f

**Comment by dkwo** [comment]
seems fixed now, not sure whether it's because i'm using a second esim (affecting the power saving status), or something else.

**Comment by Trustmega** [comment]
> Hi, on my phone a Galaxy A52 with most recebt updates for Android the issue/bug is present again. When the screen is locked and in vibration only mode Signal Calls vibrate just once, also the call is visually shown on the screen.
> 
> That's quite annoying cause this way you miss lots of calls because you don't realize that it's not just a messag, but a current caller.
> 
> Would really appreciate if someone could get a look on it :) Thx in advance.

Same issue for me. Galaxy a52 running Android 14 with oneui 6.

@dkwo can this be opened again?

**Comment by ostap1010** [comment]
> Hi, on my phone a Galaxy A52 with most recebt updates for Android the issue/bug is present again. When the screen is locked and in vibration only mode Signal Calls vibrate just once, also the call is visually shown on the screen.
> 
> That's quite annoying cause this way you miss lots of calls because you don't realize that it's not just a messag, but a current caller.
> 
> Would really appreciate if someone could get a look on it :) Thx in advance.

I have the same issue on Samsung Galaxy S10plus

**Comment by luc-w** [comment]
I have the same issue on my Pixel 6A running Android 14

**Comment by maximko** [comment]
Please reopen this issue. Same on android 13 and latest Signal.

**Comment by alex-signal** [comment]
Hi everyone!

If you can please upload fresh debug logs, and please let us know what your Full Screen Notification permission is set to for Signal (I don't remember whether we have this in our debug log information)

**Comment by alex-signal** [comment]
Hi folks, looks like we missed adding the proper attributes when we start vibration. Hopefully this is improved in `7.7`

**Comment by Trustmega** [comment]
> Hi folks, looks like we missed adding the proper attributes when we start vibration. Hopefully this is improved in `7.7`

Does this mean you identified the issue and that it will be fixed?

In other words, you dont need the debug log?

**Comment by alex-signal** [comment]
> Does this mean you identified the issue and that it will be fixed?

It means I *hope* it's fixed, because with Android you never really know what you're going to get with some of these APIs. So please re-test when `7.7` becomes available (I am targetting a beta for later today)

**Comment by dkwo** [comment]
Finally got 7.7.* from the playstore.
For me, incoming calls now work, but incoming video calls are still broken (registered as missed).

**Comment by Trustmega** [comment]
I still have this issue. Although only when DND is enabled. Only vibrates once. Like getting a message.
________________________________

**Comment by alex-signal** [comment]
@Trustmega Have you allowed calls to override DND settings?

**Comment by Trustmega** [comment]
That setting doesn't show in my app.

Here are screenshots from the signal settings and my DND settings. Unfortunately the latter ones are in Swedish. Ask me if something is unclear.

As you can see both signal and WhatsApp are exempt.
________________________________
