### ISSUE TITLE
Sharing images as 'View-Once' doesn't bump the converstation

### ISSUE THREAD

**Issue by cyclonejet** [signalapp/Signal-Android#12789]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I share images as 'View-Once', the conversation the people whom I sent it to don't get bumped until opened.

### Steps to reproduce
- Home Page
- Camera
- Click something
- Turn on 'View once message'
- Send it to someone who's not on top of your conversations
- Whomever you sent it to, their conversation stay where they are
- Open any conversation
- Go back
- The conversation to whom you sent the view-once message is at top now

**Actual result:** The conversation didn't get bumped after sending 'View-Once' message. It only bumped when a conversation was opened.
**Expected result:** The conversation should have been bumped to the top of the conversation list when it was sent.

### Device info

**Device:** Xiaomi Redmi Note 5 Pro
**Android version:** 11
**Signal version:** 6.10.9

### Link to debug log
https://debuglogs.org/android/6.10.9/fedda5c9f4f1cb7d251fea19921f054479a0a31950ac950192f8f6befd8f9438

**Comment by AlertSubject** [comment]
Can't reproduce
Works on my oneplus 9 pro using latest beta
But the bumping did take a second or two
