### ISSUE TITLE
App crashes when trying to share image

### ISSUE THREAD

**Issue by OliverRoss** [signalapp/Signal-Android#12787]
Looked in the issues but didn't see a similar one.

When I share an image from my gallery, Signal opens the dialogue to select the chat. 
Upon entering some combinations (e.g. "ae", "si") of letters in the search field, the App crashes immediately. Other strings work fine.

**Comment by greyson-signal** [comment]
Can you please include a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by OliverRoss** [comment]
https://debuglogs.org/android/6.10.9/e13a4929534398dba7875489decdaf12cd5e457220587db8d6b53615c4b85993

**Comment by greyson-signal** [comment]
I believe this was fixed a while back

**Comment by OliverRoss** [comment]
Yes, just tried to reproduce on the same device and at least here it's fixed.
