### ISSUE TITLE
Please disable 4 pinned tabs max

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#12784]
For people using Signal only, without the ability to build spaces, groups or anything (Like Element does), it is so restricting to just allow 4 pinned chats.

I literally have 50 open, and it is so nessecary to be able to bin the 20% of important chats, with 4 this is just not enough...

**Comment by bme13** [comment]
Hi. Please note github is only used for bug reports. Signal community is used for feature request. There's actually already a request for this. See: https://community.signalusers.org/t/allow-for-more-than-4-pinned-chats/19869.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
