### ISSUE TITLE
Couldn't schedule message as I'm shown "SMS messaging is no longer supported in Signal" on long-press, untill force stop

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-Android#12786]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I wanted to use the newly added message scheduling feature. However, when I type a message to someone (a person or group) and then long-press the send icon I'm shown this message "SMS messaging is no longer supported in Signal". I don't get any options to schedule my message.

I then force stopped the app and now I don't see the message about SMS and I am able to schedule my message. So force stopping solved the issue. This isn't a big problem, but Signal sent a special message within the app to notify users about this feature. So some people will then try the feature immediately and be confused if it doesn't work.

### Steps to reproduce
- Update app
- Type a message to someone
- Long-press the send icon

**Actual result:** I see a message saying: "SMS messaging is no longer supported in Signal"
**Expected result:** I want to see the schedule message options

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 12
**Signal version:** 6.11.6

**Comment by greyson-signal** [comment]
Thanks! We've fixed this in 6.11.7
