### ISSUE TITLE
Image compression sometimes increases image size

### ISSUE THREAD

**Issue by shvchk** [signalapp/Signal-Android#12796]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See title : )

### Steps to reproduce
1.  Send optimized PNG file, e.g. this QR code (727 bytes):
  ![sound of silence qr](https://user-images.githubusercontent.com/872945/219790668-b00d6283-98cc-4324-a092-0cd811b932ef.png)
2.  Save image from Signal back to your device

**Actual result:** "Compressed" image size is 3,4 KB (~5 times more, which is better than on desktop, but still)
**Expected result:** Compression should not increase image size

Similar issue for Signal Desktop: signalapp/Signal-Desktop#6296

### Device info
**Android version:** LineageOS 20 (Android 13)
**Signal version:** 6.11.7

**Comment by shvchk** [comment]
unstale 🪄✨

\* why `wontfix` though?

**Comment by shvchk** [comment]
:magic_wand::sparkles:

**Comment by shvchk** [comment]
🪄✨

**Comment by cody-signal** [comment]
Hi there @shvchk, while I appreciate the concern and observations here, we rely on our compression flow to do more than just decrease file sizes. As such, I don't think we'll be making any changes here and we accept that sometimes the file size will be larger for some types of images.
