### ISSUE TITLE
No notification when scheduling message with note to myelf

### ISSUE THREAD

**Issue by kamstrup** [signalapp/Signal-Android#12798]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I use the new scheduled messages feature, and sending to my "personal note" later in the day I don't get a notification. I was expecting to be able to use this as a reminder. Eg. schedule a personal note for later in the day, "remember to pick up the kids"

### Steps to reproduce
- Go into Personal Note (or what it is called in english? sorry)
- Write a private note
- Hold down the Send button and wait for scheduling options.
- Select a time later in the day

**Actual result:** The note is just silently appended at the scheduled time
**Expected result:**  A notification later in the day when the message is created

### Device info

**Device:** OnePlus 7T
**Android version:** 11
**Signal version:** 6.11.7

**Comment by cody-signal** [comment]
Yeah, we are going to do this, just not sure when.

**Comment by newhinton** [comment]
@cody-signal This is great to hear! But doesnt it make sense to not let that bot close this ticket? i was about to open a duplicate.

**Comment by kr15h** [comment]
I am experiencing the issue as well. Would be so cool to use this for reminders.
