### ISSUE TITLE
Own message before messages received earlier after getting back online

### ISSUE THREAD

**Issue by krwow** [signalapp/Signal-Android#12791]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you send a message being offline (or while there are many messages awaiting on a server and it takes a moment to download them to device) and reconnect later, messages are not in the correct order - as in the example from screenshot, at the top there's my own message sent "now" (at first it had status "sending", but after connecting to the Internet it was right away sent), then there are many messages sent 30 minutes ago to me, which I get after connecting to Internet again, but it was a few seconds later then sending my message.

It might be just a result of inconsistency in displaying date and time format - in own messages it's always a sent time, but in these coming from someone it's a receiving time.

### Steps to reproduce
- disconnect from Internet (may be airplane mode)
- send a message to someone
- wait until you're certain that this person have already sent you some message
- connect to the Internet
- go back to chat and check the messages order

**Actual result:** messages not in the correct order
**Expected result:** messages... in the correct order (maybe sorted after downloading and sending all messages after reconnection? or sent messages displayed always after received ones after reconnection?)

### Screenshots

1.
<img src="https://user-images.githubusercontent.com/65966603/219118745-3b4f6942-bced-47e1-bfa3-891b37003ffd.png" width="108" height="234">
2.
<img src="https://user-images.githubusercontent.com/65966603/219124496-7aacebfb-5f91-4b7c-b1a2-3d4be0d11c05.png" width="108" height="30">
3.
<img src="https://user-images.githubusercontent.com/65966603/219124556-bc56683c-ddf4-45a2-99d8-f0932b898cf0.png" width="108" height="30">

### Device info

**Device:** Google Pixel 4a
**Android version:** 13
**Signal version:** 6.11.7

### Link to debug log

https://debuglogs.org/android/6.11.7/360cfb5cdfb3d31ee91fa65b78a351b5c47fcd2a10079349813d22af7982655b

**Comment by greyson-signal** [comment]
Hi there, we don't ever re-sort message history. From your perspective, the messages you sent were "first"  in that you saw them first, then you saw other messages come later. Doesn't matter that those messages were technically sent "earlier".
