### ISSUE TITLE
The order of messages is not correct

### ISSUE THREAD

**Issue by giupardeb** [signalapp/Signal-Android#12799]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Yesterday (19 February 2023) I turned on the airplane mode at 3.30 pm, after about 1 hour I sent a message in a chat and after 10 minutes I turned off the airplane mode and signal sent the message.  But in meantime I received several messages (sent while I was in airplane mode). The result is a incorrect viewing of the order of messages (see the image  below).

### Steps to reproduce
- turn on the airplane mode
- send a message
- receive messages while the airplane mode is on
- turn off the airplane mode

**Actual result:** incorrect viewing of the order of messages
**Expected result:**  the correct order of messages

### Screenshots
![photo_2023-02-20_13-58-38](https://user-images.githubusercontent.com/4471950/220120558-0e36ee40-f3bf-4462-ac39-e2b4c95f8ddd.jpg)

### Device info

**Device:** Xiaomi Redmi Note 9S (lineage_miatoll)
**Android version:** 12
**Signal version:** 6.11.7

### Link to debug log
[signal-log-1676821497446.zip](https://github.com/signalapp/Signal-Android/files/10784749/signal-log-1676821497446.zip)

**Comment by greyson-signal** [comment]
Hi there, we never insert new messages into the past. They're always rendered in "received order", so this is working as intended.
