### ISSUE TITLE
SMS/MMS not working anymore

### ISSUE THREAD

**Issue by glemiere** [signalapp/Signal-Android#12800]
Okay fine, it's not a bug report.
But I want to see how many of us coding nerds would be willing to fork a version of signal that supports SMS/MMS. I really thought Signal would be the last time I'd have to tell all my family and friends to use X app for messaging, but here we are again.

Soooo, has anyone already been doing it? If so, I'd be happy to join.

**Comment by markum** [comment]
It would be so great. The mess has already started. People who are running Signal are sending unencrypted SMS again, and so conversations are split between conventional SMS and Signal. Everything was working fine until the Signal people thought this was a great idea and really necessary.
