### ISSUE TITLE
Alarm clock on lockscreen enabled when a message is scheduled

### ISSUE THREAD

**Issue by FiniH** [signalapp/Signal-Android#12806]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I scheduled a message on Monday to be sent on Thursday/yesterday at 13:37. When I locked my screen one time on Thursday, I saw that I have the symbol of a set alarm clock for 13:37. For the life of me, I searched through all alarms I maybe missed but couldn't find any. After the message was sent successfully, the symbol vanished and no alarm ringed.

### Steps to reproduce
- schedule a message for a specific time
- have no other alarms set
- look at the lockscreen on the day when the message should be sent

**Actual result:** 
I have a weird alarm symbol on my lockscreen and thought some alarm I couldn't find would ring while I'm in the train. :D

**Expected result:** 
No alarm symbol.

### Screenshots
![Screenshot_20230223-071135~2](https://user-images.githubusercontent.com/11769157/221140001-b81ed26f-cce9-479f-a1e8-3252ce5cf1ec.png)

### Device info

**Device:** Google Pixel 6
**Android version:** 13
**Signal version:** 6.12.5

**Comment by cody-signal** [comment]
Yeah, it's a side effect of the only way we've found to get reliably alerted by the Android OS at the right time.

Greyson wrote a bit about it on our forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-12-release/51511/130?u=cody-signal

**Comment by kgSignal** [comment]
I have this bug as well. On a Google Pixel 7Pro with the March Feature Drop/security patch update.

Debug log:
https://debuglogs.org/android/6.13.7/1afa76bc20efdbe8743c1462f67b89a36de3a012ca7593b2677e6f628780c35c

So reading your response @cody-signal , does that mean we're just gonna have to deal with this for the foreseeable future? 

Unfortunately when you click on the alarm icon it takes you to the alarm app vs. your chat where the scheduled message has been set. Maybe that would be an decent middle term solution that it at least takes you to the scheduled message?

I don't use the feature really much at all but if I did it would tick my OCD side of my brain just a tad :)

**Comment by cody-signal** [comment]
Thanks for the post. Yes, this is something we'll have to live with for now. That's odd it doesn't take you to our app. We specifically give the OS an intent to fire to open the conversation with the scheduled message needing the alarm.

**Comment by greyson-signal** [comment]
Copy-pasting some context from my [forum post](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-12-release/51511/130?u=cody-signal):

> We don’t want to have to schedule it as an alarm either, but using what should be the “correct” way to schedule something like this ([setExactAndAllowWhileIde 4](https://developer.android.com/reference/android/app/AlarmManager#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent))) was straight-up being ignored by a lot of phones overnight. People would schedule something for 4am, and it would run at 8am when they woke up. If it was just a few minutes late, I think we could handle that, but it basically wasn’t working at all.
