### ISSUE TITLE
Unable to send a link to a specific side, all other links are working




### ISSUE THREAD

**Issue by joergi** [signalapp/Signal-Android#12811]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I wanted to send a link to an [article](https://www.insider.com/a-lawyer-died-after-gun-discharged-mri-scanner-2023-2) but it's always not sending.   
I tried it in different chats, it's never working.   
I tried to send the same link on whatsapp, it's working...   
Sending any other link is working.   
Only this one isn't working. 

A friend tried it from his Android phone and it was working.  
I tried to forward his sent link and it's working for me to send it. 

### Steps to reproduce
- try to send https://www.insider.com/a-lawyer-died-after-gun-discharged-mri-scanner-2023-2
- also resend is not working

**Actual result:**
Still showing sending failed
**Expected result:**
 Link should be sent

### Screenshots
![Screenshot_20230226-132648.png](https://user-images.githubusercontent.com/1439809/221410768-6929c93a-f407-4fdc-87a4-ccc819bd5a10.png)

![Screenshot_20230226-132633.png](https://user-images.githubusercontent.com/1439809/221410767-1022cdcb-ffa4-41b9-b4b2-7883cc891ef3.png)

![Screenshot_20230226-133802.png](https://user-images.githubusercontent.com/1439809/221411081-8199963e-fa83-4b07-a9a1-9edbbee71e51.png)

### Device info

**Device:**
Fairphone 3+ (8901.4.A.0021.0 release-keys) 
**Android version:** 11 (see Screenshot above) 
**Signal version:** 6.12.5

### Link to debug log
https://debuglogs.org/android/6.12.5/e9f0f9c66b3129172b61989a88306819488857f62eed7770ed1ccdce67cc0a11

**Comment by cody-signal** [comment]
Hey there, looks like it was an issue with the link preview image and it being corrupted. Is this still happening? Can you try sending without the link preview?

**Comment by joergi** [comment]
hey @cody-signal 
it's working without the preview on my mobile.

but as I wrote in my original post, a friend (using the same version of Signal, as I do, could send it from his Android) including the preview.
Also I was able to send the link incl. preview via WhatsApp...
