### ISSUE TITLE
Signal does not react to ripple panic trigger

### ISSUE THREAD

**Issue by hydrargyrum** [signalapp/Signal-Android#12816]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app does not react to the ripple panic button

### Steps to reproduce
- open signal
- unlock it
- open ripple app
- trigger panic button
- go back to signal

**Actual result:** signal is:
- all data is still there
- unlocked!!!

**Expected result:**
- at the very least, signal should be locked with the device password or the signal pin
- optional: in a configurable manner, local signal data should be wiped

### Device info
**Device:** Samsung
**Android version:** 10
**Signal version:** 6.12.5

**Comment by nicholas-signal** [comment]
Hello,

We use GitHub issues exclusively to track bugs in the Signal app. The Ripple application is developed by the Guardian Project, and it is up to them what Ripple does and does not support.

If you have other feature requests that are within Signal's purview, please join the conversation on our community forum: https://community.signalusers.org/

**Comment by hydrargyrum** [comment]
@nicholas-signal the bug is in signal app, not in ripple app
