### ISSUE TITLE
Android Transfer isn't working, somehow the app version is different

### ISSUE THREAD

**Issue by ubershmekel** [signalapp/Signal-Android#12813]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to transfer Signal from my Pixel 5 to my Pixel 7. The reason seems to be that the versions are out of sync. The older Pixel 5 has Signal 6.12.5, the newer Pixel 7 has Signal 6.11.7. I see the versions by looking at the application info in Android settings.

### Steps to reproduce
- Get a new phone
- In new phone, install Signal, tap "Transfer or restore account".
- In old phone go to Signal -> settings -> account -> Transfer Account.
- Get a "Cannot transfer from a newer version of Signal" error in the new phone. Geta "Transfer failed" error in the old phone.

**Actual result:** No transfer occurs
**Expected result:** The account is transferred to the new phone.

### Device info

**Device:** Google Pixel 5, Google Pixel 7
**Android version:** 13
**Signal version:** 6.12.5 and 6.11.7

Perhaps this is related to issues found at https://github.com/signalapp/Signal-Android/issues/9590

**Comment by hmcguirk** [comment]
Same issue here. App Info in old phone's settings says its 6.12.5, and that the app was downloaded from play store, but app info in play store, at bottom of 'whats new' says version is 6.11.7. New phone has 6.11.7 everywhere. Transfer fails for same reason

**Comment by cody-signal** [comment]
Ah, yes, this is a sticky situation. 6.12.5 is in a staged rollout and it appears you updated on the old phone and then when going to install on the new phone you're no longer in the  6.12.5 bucket and get the previous version that was rolled out to 100%.

We're having some problems with the Play Store right now and getting new builds approved. If you can't wait, you can find 6.12.5 in other places that mirror apks. You can also join the firebase beta which is 6.13.3 (See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-13-release/51700?u=cody-signal) but I wouldn't recommend you stay on that version and just install it for now, and then don't install via firebase again and it'll automatically go back to play store releases.

**Comment by Stivan93** [comment]
Same exact problem here.  Can you direct us to a mirror for the APK?  Thank you

**Comment by Stivan93** [comment]
Would be better yet if signal.org would post a link to the 6.12.5 sdk for all of us in this current bind.  Thanks!

**Comment by tobiloeb** [comment]
I did a backup yesterday and removed the signal App. After reinstall via playstore the backup can't be restored cause of error:
"Data backup of newer signal versions cannot be imported"
Same Phone same Version

**Comment by Stivan93** [comment]
I found a seemingly safe place to pull the 6.12.5 APK from:
https://www.techspot.com/downloads/7363-signal-messenger.html

**Comment by Stivan93** [comment]
Worked for me, and I was able to restore from a backup I took on the older phone.

**Comment by nicholas-signal** [comment]
Hello all,

6.12.6 should be available on the Play Store shortly. It is also available immediately and directly from our official website:
https://signal.org/android/apk/

**Comment by sebastianrueckerai** [comment]
I am having the same issue: I am on 7.9.5 on my old phone but the store version I can download is older so I cant transfer. Can you point me to a way to install the newer version on my new phone? Preferably in a way so I can later switch back to the normal non-beta version of Signal?

**Comment by alex-signal** [comment]
Hi! We are in the process of rolling out `7.9.6` so if you'd like to stick with the stable store version please just hold tight, it should be available over the next couple days.

Alternatively, you could install the beta.
