### ISSUE TITLE
Open through notification - return to previous screen

### ISSUE THREAD

**Issue by francwalter** [signalapp/Signal-Android#12815]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening Signal through a notification in the Notification Bar, after hitting Back button and leaving Signal, I am on Home screen, as if I hit the Home button.

### Steps to reproduce
- I am in any app, e.g. an editor and a Signal message notification pops up.
- l hit the message's notification and Signal opens with that message
- After reading the message, I hit Back button to return to my previous app
- First Back button closes the message and shows Signal's main window.
- Next Back button is as if I hit the Home button, shows the Android "desktop".

**Actual result:** I see the Android Desktop.
**Expected result:** To be back in the previous app's screen, especially if this app gets killed by Android when in background or if that app looses its data when the Home button is tapped. 

### Device info
**Device:** Xiaomi Mi A1 (but with all devices it is the same)
**Android version:** 9.0 (but all other versions are affected too)
**Signal version:** 6.12.5 (unfixed in all previous versions)

This bug is very long present and there are a few other apps doing this wrong too (e.g. k9mail, Threema), but most apps handle the return from a notficiation to the previous app correct (WhatsApp, Telegram, FairEmail etc.).

I opened an issue (#11116) long time ago, but it was not even commented by a dev and in the end it was closed by a bot.
But this issue is still annyoing me (and surely other users) again and again.

I don't open a notification from Signal, if I am in work in another app because of this bug.
But I open them from other apps where this is working.

Please fix this!
Thanks.
frank

**Comment by nicholas-signal** [comment]
Hello,

I was unable to reproduce this on the multiple devices I have (Samsung, Pixel, HTC, etc). Here's the precise steps I followed:

1. Have phone unlocked on non-Signal app. I tested various apps, including the home screen, the web browser, and the camera.
2. Receive an incoming Signal message.
3. Tap on the incoming notification.
4. View the conversation.
5. Back out of the conversation. I tested both the OS's back button and the arrow in the action bar.

Is it possible that you have any of your Android Developer Options enabled in the device's settings? Relevant options could be "Don't keep activities" or "Background process limit", among others.

**Comment by francwalter** [comment]
After 5. Back out of the conversation... you did not mention, what happens on your phones now, but this is the crucial part.
Are you back in the app you used before?

**Comment by nicholas-signal** [comment]
Ah, I misunderstood your issue. Yes, it is the current behavior that exiting Signal returns you to your phone's home screen.

I will raise this with our Product team and update you if we choose to change the behavior.

In the meantime, I suggest using the navigation bar's recent apps functionality to return to your previous app. The exact steps can differ by device, but generally: for 3-button navigation, it's a double-tap on the square ("App Overview") icon, and for gesture navigation, swipe left/right at the very bottom of the screen.

**Comment by francwalter** [comment]
> I will raise this with our Product team and update you if we choose to change the behavior.
> 

Did you raise this to your product team?
Was it just declined?
I don't hear anything anymore and now the bot want to close this issue!
This issue is still annoying, making signal notifications a bit useless.
And your proposition to use "navigation bar's recent apps functionality to return to your previous app" is not that useful because apps can be killed in the meantime it they lose their actual state (annoying when I was going to write something).

**Comment by nicholas-signal** [comment]
> Did you raise this to your product team?

Yes, I did raise it, and I have nothing to share publicly at this time.

**Comment by francwalter** [comment]
You closed this issue, without beeing completed?
The bug is still present, nothing changed!
Why did you close it?

**Comment by nicholas-signal** [comment]
It is currently working as designed. If the design changes, then we will incorporate the new design.
