### ISSUE TITLE
Camera_ Problem with Landscape Orientation on Galaxy S23+

### ISSUE THREAD

**Issue by thn80** [signalapp/Signal-Android#12817]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using Signal 6.12.6 on Android 13 on a Samsung Galaxy S23+.
If I want to take a photo via the small camera symbol shown in conversations, everything works fine if the phone is held in portrait mode OR if Androids automatic screen rotation is tunred off.
However, if the phone is held in landscape mode (90° rotated) and in the Android settings the "Auto Screen Rotation" is turned on, Signal shows the live camera preview 90° rotated.
A similar problem is discussed in [this issue](https://github.com/signalapp/Signal-Android/issues/8611) and also a lot of other issues here on Github are marked as duplicates of this issue. However, this issue is marked as solved and the problem still appears on my phone.

My wife has a Samsung Galaxy S8, running Android 9 and Signal 6.12.6 on which the setting of the automatic screen rotation of Android has no influence on the behavior of Signal's in-built camera. In all combination it works as expected.
The Galaxy S23+ works only correctly if Androids screen rotation is configured to "Portrait" mode only OR if Android uses automatic screen rotation and the phone is held in portrait mode during the use of Signal's camera.

### Steps to reproduce
- Go into a conversation
- Hold the phone in landscape mode (90° rotated)
- Start the in-built camera via the small camera icon shown in the conversation.

**Actual result:** Signal shows the live preview camera image 90° rotated.
**Expected result:** Signal should recognize that the phone is rotated by 90° and correct the camera preview.

### Device info
**Device:** Samsung Galaxy S23+
**Android version:** 13
**Signal version:** 6.12.6

**Comment by thn80** [comment]
Any comments on this?

**Comment by nicholas-signal** [comment]
I am able to reproduce this, but device-specific camera issues specifically can be quite tricky to fix in a way that doesn't break the majority of devices.

**Comment by thn80** [comment]
Any comments on this?

> I am able to reproduce this, but device-specific camera issues specifically can be quite tricky to fix in a way that doesn't break the majority of devices.

I agree with this, but we should also consider that the Galaxy S23+ is really one of the mainstream phones and, therefore, a lot of users will be affected of this issue.

**Comment by thn80** [comment]
Is there any update on this?

**Comment by nicholas-signal** [comment]
I've investigated the issue, and the short summary is that Google's CameraX library doesn't offer an easy way to override the orientation of the preview surface for fixed-orientation screens. It looks like they're adding such an API in the upcoming 1.3.0 release: https://developer.android.com/jetpack/androidx/releases/camera#1.3.0-alpha05

While we wait for 1.3.0, rest assured that even though the preview is wonky, the photo will be taken with the correct orientation. Additionally, if you initiate the camera with the phone in portrait, the preview will function correctly.

**Comment by thn80** [comment]
Any update on this?

**Comment by greyson-signal** [comment]
Unfortunately CameraX 1.3.0, while it fixes this issue, made an API change that makes it impossible for us to use for the time being. They changed their API's to require an output File instead of a ParcelFileDescriptor, meaning we can't use our previous strategy to avoid writing unencrypted bytes to disk. I'll try to reach out and get them to add the API back.

**Comment by greyson-signal** [comment]
Apologies, I misspoke. We found the API to use the ParcelFileDescriptor. However, even after upgradign to CameraX 1.3.0, this bug is still happening :(

**Comment by thn80** [comment]
Any updates?
