### ISSUE TITLE
Restore data from backup: Backup from newer versions....

### ISSUE THREAD

**Issue by backupandforkacc** [signalapp/Signal-Android#12810]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Want to restore messages from Backup. 
Recently switched from Android 12 to Android 13
Installed signal via playstore. Also tried version from website.

### Steps to reproduce
Choose restore at first startup of app.
Choose backup file.
Put in passphrase.
There is a message popping up only for 1 sec (much too short!), says something like: Backup from newer versions cannot be restored. I do not know the version of the app from previous system (Android 12).

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Xiaomi 9T (davinci)
**Android version:** LineageOS 20 (Android 13)
**Signal version:** 6.11.7

### Link to debug log
https://debuglogs.org/android/6.11.7/a8c6f24d10b990af167825cc254c297f9a1f947dc0c361911af834475d416c06

**Comment by cody-signal** [comment]
What seems likely, is you're stuck in the previous prod build but on your previous install you were in the staged rollout bucket and allowed to update to 6.12.5. We are fighting the play store on getting builds out.

you can do like @neobrain and find a site that mirrors apks to download or join the firebase beta or wait.

**Comment by miszuni** [comment]
I have the same problem. Can you provide alternative trusted apk source?

**Comment by tobiloeb** [comment]
I have the Same problem :(

**Comment by backupandforkacc** [comment]
i downloaded the aptoide store, also have good experience with aurora store. Can be downloaded directly from their website. 
They have a newer version and with that I could restore.

**Comment by nicholas-signal** [comment]
Hello all,

6.12.6 should be available on the Play Store shortly. It is also available immediately and directly from our official website: 
 https://signal.org/android/apk/

**Comment by henryreed** [comment]
Adding this for folks stumbling in from Google: if you are using Signal Beta, and you wanted to downgrade to the regular Signal version, you cannot use local backups to restore your data because of this error. If you need your data, you can recover from the backup file using third-party tools (like bepaald's `signalbackup-tool`), but there is no way to import the data you recovered from a backup back into the Signal app.

**Comment by unusualevent** [comment]
if you wait will the beta backup eventually be readable by the stable client?
