### ISSUE TITLE
Phone number country code always reset to +1 when sign-up

### ISSUE THREAD

**Issue by ZueyEnfe** [signalapp/Signal-Android#12819]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When i try to sign-up today, the phone number country code always back to +1 after captcha. which make me unable to sign-up.

### Steps to reproduce
- open new installed app from play store
- click continue
- change the country code (in my case +62)
- enter phone number and click continue
- complete captcha

**Actual result:** the country code changed to +1 which result invalid phone number or confirmation being send to wrong number.
**Expected result:** able to sign-up.

### Screenshots

https://user-images.githubusercontent.com/99162380/222355196-31979944-852e-4d9c-820d-c1b76ba08d2d.mp4

### Device info

**Device:** Xiaomi redmi note 7
**Android version:** crDroid 9.2 (Android 13)
**Signal version:** 6.12.6(121907)

### Link to debug log

I can't get the log

edit: reuploading the video. it corrupt i think

**Comment by nicholas-signal** [comment]
This issue was fixed in https://github.com/signalapp/Signal-Android/commit/ab48aa57662f75e46145ee762b8d1b5dd5249259 and is part of the current 6.13.5 release.

**Comment by nicholas-signal** [comment]
> ok, thanks. and sorry, i culdn't find that issue before, so i make new one

No worries! Thanks for using Signal, and thank you for reporting a bug!

**Comment by Leberwurscht** [comment]
I experience exactly the same problem, on 6.13.6.
I changed the country code to +49, solved the Captcha, and got the error message "invalid number" while the phone number field displayed my phone number, but starting with +1 instead of +49.

**Comment by Leberwurscht** [comment]
[fb1451c2848fd897a94bc1f608bfce810163c42007cb3c10646681ccbdc247e9.gz](https://github.com/signalapp/Signal-Android/files/10882095/fb1451c2848fd897a94bc1f608bfce810163c42007cb3c10646681ccbdc247e9.gz)

**Comment by nicholas-signal** [comment]
> I experience exactly the same problem, on 6.13.6. 

Your debug log states that you're on 6.12.6, not 6.13.5. Google Play can take a while to distribute the latest version to everyone.

**Comment by Leberwurscht** [comment]
Sorry I missed that and thank you for the response!
I'll just wait then. The latest version available on https://signal.org/android/apk/ is also still 6.12.6.
