### ISSUE TITLE
(previews of) missing attachments should not be hidden as if they never existed

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12823]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When for whatever reason an atrachment is missing, Signal Android (and Desktop also, I have not tested iOS) hides any sign of the attachment. For example if someone has once send an image with some text, all I see now is a text message.

This  confuses the cconversation history. If we discussed an image or whatever file, there is now just text and I have to guess what might have been send if anything at all.

Signal should show a placeholder, can be a blur hash or something else. That allows me to see what file type was send, and at what moment, part of which message. Even if the filetype is unknown, a placeholder should still be shown to indicate something was there.

On Desktop (not sure about Android) you sonetimes see a download button on a blhr hash and when you click on it and the image can't he found the whole tthing just disappears. Let's not do that.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 6.13.5

**Comment by greyson-signal** [comment]
Is this a situation where an attachment fails to download? Or a situation where a user deletes the attachment on a message after receiving it? If the attachment is unreadable, I'm actually much more interested in logs around the attachment failure :)

**Comment by Meteor0id** [comment]
Still very relevant, Signal should not remove any messages from history ever unless a user does that on purpose.
If messages disappear the remaining message history could be misinterpreted.

**Comment by Meteor0id** [comment]
A tombstone for attachments is still important to have
