### ISSUE TITLE
Delayed echo when calling a Pocophone F1

### ISSUE THREAD

**Issue by breversa** [signalapp/Signal-Android#12828]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When calling one person who uses a Pocophone F1, I can hear my voice echoing with a 0,5-2s delay, which makes it VERY painful to speak.

### Steps to reproduce
- Call that person using either Signal Android or Signal Desktop
- Hear yourself with a 0,5-2s delay
- Hang up because it's impossible to talk like this, and call back using normal phone call…

**Actual result:** I hear myself with a 0,5-2s delay. The person *using* the Pocophone F1 can speak and hear just fine. No issue on their side.

**Expected result:** I don't hear myself

### Screenshots
![signal-2023-03-07-223952](https://user-images.githubusercontent.com/2071276/223561979-6ddda57e-586c-4518-9ed7-16ee48cf5671.png)

![signal-2023-03-07-224029](https://user-images.githubusercontent.com/2071276/223560838-d3723d46-ce0e-4751-ab7b-250db78cea6c.png)

### Device info
**Device:** Xiaomi Pocophone F1
**Android version:** 11
**Signal version:** 6.11.7 (current version but that bug has been existing for at least a year)

**Comment by siegbertus420** [comment]
Same here! On Oneplus 5T with Lineage OS 21.0 - 15.10.2024 withous GApps. No matte who I call, everyone hears the Echo. Even when a Headset is attached. It seems somehow the incoming sound is just sent back inside the phone!

When the Oneplus is Muted, there is no Echo. Normal phone Calls work perfectly, no Echo whatsoever.

I would absolutely appreciate if someone looked into it.

**Comment by jim-signal** [comment]
Hello @breversa and @siegbertus420, can you please provide debug logs? We can take a look at them and see if they yield any clues in regards to the echo, which isn't expected. Thanks!

[How to submit logs is here...](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports)

**Comment by siegbertus420** [comment]
That one was made right after a test call: https://debuglogs.org/android/7.19.2/efed5bee92006c736cfcb5361e265e12eba5dd032f2e070258af924f5766a166

Am 17.10.2024 um 21:52 schrieb Jim Gustafson ***@***.******@***.***>>:



Hello @breversa<https://github.com/breversa> and @siegbertus420<https://github.com/siegbertus420>, can you please provide debug logs? We can take a look at them and see if they yield any clues in regards to the echo, which isn't expected. Thanks!

How to submit logs is here...<https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports>

**Comment by breversa** [comment]
> Hello @breversa and @siegbertus420, can you please provide debug logs? We can take a look at them and see if they yield any clues in regards to the echo, which isn't expected. Thanks!
> 
> [How to submit logs is here...](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports)

Sorry, I can't help any longer as I've gotten rid of that device months ago.

**Comment by jim-signal** [comment]
@siegbertus420 we made a change in the configuration, can you try again and let us know if the experience is better, or not? Thanks.

**Comment by r0d0dendr0n** [comment]
I have a poco f1 and I also experience echo when using the phone mic and speaker (both normal and loud). How do I get the test release?

**Comment by jim-signal** [comment]
@r0d0dendr0n there is no special test release for this, there are some options we can adjust which allow us to make some device models use alternative audio settings. To do this, we would need some logs from when you were in a bad call. Also, do you hear the echo or do the other users in the call with you hear their echo? We need logs from the side that is causing the echo, which is usually not the side that hears it (unless both devices in a call are bad).

**Comment by siegbertus420** [comment]
> @siegbertus420 we made a change in the configuration, can you try again and let us know if the experience is better, or not? Thanks.

Yeeees it's fixed. Thank you sooo much! <3

**Comment by gongoscho** [comment]
Hello, I also have problems with echoes with my POCOPHONE F1 when I make calls via video or loudspeaker.

When two Pocophones F1 make a call, there is even feedback and you can't understand a word.

Which signal version fixes the echo/feedback problem?

**Comment by jim-signal** [comment]
@gongoscho there is no specific version. We can see if that device can be added to a list to use an alternative echo mechanism. To do that, a log will be really helpful that captures a bad call and the app details. [See here for how to get a link to a log file.](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports)

**Comment by gongoscho** [comment]
Oh, sorry my fault.

**Xiaomi Poco F1 LineageOS 20
Android 13** 


https://debuglogs.org/android/7.23.1/b1872f96689238aa1a7df6925c74e0be72ab44c8fe3abb86b9b79dda8f206c1b

**Comment by jim-signal** [comment]
@gongoscho since last week we've configured the "Poco F1" with LineageOS to use a different echo canceller. If you have had a Signal call, have you noticed any change?

**Comment by gongoscho** [comment]
Yes, it is fixed. I have tested with three different Poco F1.

Tank you!
