### ISSUE TITLE
signal sees no contacts on new install.

### ISSUE THREAD

**Issue by rezad1393** [signalapp/Signal-Android#12827]
I installed signal on two phones. my country is Iran so I use vpn to get the code to verify new install.
both phones (separate numbers) dont have see contacts even to invite.

### Link to debug log
(https://debuglogs.org/android/6.12.6/9264ee4290e9cd918e461dc333113634943c47001d93df4ca27fbb1925d6d6b5)

**Comment by nicholas-signal** [comment]
Are you able to send and receive messages to your contacts if you type their phone numbers in manually?

**Comment by FAD775544** [comment]
I am also getting this error on a fresh install of signal 6.16.2, I have noticed it also does not add a signal account under the android account section were previously it did.

If I type the number of a contact I am unable to initiate the conversation, but if they send me something first I can accept and send messages but its an unknown contact
