### ISSUE TITLE
Voice message is lost when it reaches 60 minutes

### ISSUE THREAD

**Issue by davidak** [signalapp/Signal-Android#12822]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

A voice message is lost when it reaches 60 minutes.

At the first time, i thought i made a gesture that deletes the message, but now it happened a second time. So this is a bug that exists for months (or years).

(People hate long voice messages, so a limit might make sense. But that's a different topic.)

### Steps to reproduce

- Record a voice message by holding down the microphone button
- Talk for 60 minutes

**Actual result:** When you reach 60 minutes, the phone vibrates once and the message is gone forever
**Expected result:** I should be able to record unlimited voice messages, or a limit should be implemented that let me send the message (like the desktop client had a 5 minute limit at some point)

### Device info

**Device:** Fairphone 2
**Android version:** 11 (LineageOS 18)
**Signal version:** 6.9.2

**Comment by nicholas-signal** [comment]
Hello, we had a fix for this released in Signal 6.10.0. Can you test with the latest Signal app and see if it still happens?
