### ISSUE TITLE
Add option to enable SMS in future versions.

### ISSUE THREAD

**Issue by Sn0whax** [signalapp/Signal-Android#12826]
I understand the choices to remove SMS by default. But couldn't we just have a toggle to enable it within the app itself?
This would ensure users that do use SMS have an idea of potential consequences/rid of the nubs. There could also be like a green/blue send button type thing similar to iMessage. Green send is SMS, blue being Signal.

Without SMS I don't see how signal provides many benefits over something like SimpleX Chat. This was supposed to be androids iMessgage killer.

**Comment by nicholas-signal** [comment]
The GitHub Issue tracker is for bugs in the existing app. All feedback regarding feature requests and SMS removal can be submitted via our community forum: https://community.signalusers.org/

**Comment by NtTestAlert** [comment]
Goodbye, Signal. Been here since TextSecure. Too bad the team decided to kill the app, and were too egoistical to reverse course from oblivion. 
A sad day for privacy and encryption. Which makes me think this was by design.
