### ISSUE TITLE
Device transfer fails with FOREIGN KEY constraint error on `threads`

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#12829]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Transfers to a new device with my database are failing with similar symptoms to #12703, except that the foreign key constraint error is thrown on the `threads` table.

I did not test restoring a backup file.

### Steps to reproduce
- on new device, select option to transfer on registration screen and go through the instructions on the old device
- wait for devices to pair
- confirm pairing code
- wait ~30 seconds

NOTE: I was affected by 61e127f, and still have at least one corrupted thread in my database from before that patch landed. I have not yet evacuated SMS/MMS out of Signal. Possibly related?

**Actual result:** "transfer failed" with a red exclamation mark triangle
**Expected result:** transfer succeeded 

### Source device info

**Device:** Pixel 3a XL
**Android version:** LineageOS build 19-20230225-NIGHTLY-bonito based on Android 13
**Signal version:** 3.13.6

### Destination device info

**Device:** Pixel 7
**Android version:** GrapheneOS build TQ1A.230205.002.2023030400 based on Android 13
**Signal version:** 3.13.6

### Link to debug log

New device: https://debuglogs.org/android/6.13.6/5b3b41f63964d8f31656fa30cc75f1b0aadf9128ea57532e48165ef3e70556f0

Old device: https://debuglogs.org/android/6.13.6/b5d17b9f06654a3e8607ab806eb0172d3bca87c1d7159cbb72885254c2720c5d

**Comment by haffenloher** [comment]
Same issue as #12857, so possibly fixed (?)

**Comment by strugee** [comment]
Confirmed fixed with 6.16.1, thank you!
