### ISSUE TITLE
Pull-Down gesture does not follow android guidelines

### ISSUE THREAD

**Issue by micw** [signalapp/Signal-Android#12821]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I do a "pull down" gesture in the signal message list, it unexpectedly toggles between read/all messages.

### Steps to reproduce

* Open signal android
* in the message list, put one finger on the screen and pull down

**Actual result:** Signal toggles between read messages and all messages
**Expected result:** The drag down gesture on android is commonly used to refresh a page or update a view. Applications should either implement that behavior or should ignore the gesture. It does not make sense that one single application implements the gesture completely different to all other android app.

The gestures is described at https://m2.material.io/design/platform-guidance/android-swipe-to-refresh.html#usage

### Device info
**Device:** OnePlus 7
**Android version:** 13
**Signal version:** 6.11.7

**Comment by nicholas-signal** [comment]
Hello,

The GitHub Issues Tracker is for bugs and crashes in the app. Please submit product and design suggestions to our community forum: https://community.signalusers.org/

Thanks.
