### ISSUE TITLE
Fatal : unable to receive verification code due to Signal erroneously changing phone number country code

### ISSUE THREAD

**Issue by didierm** [signalapp/Signal-Android#12825]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Installing Signal on a new phone fails, due to Signal automatically changing the international country code prefix +32 (Belgium) to +1 (USA), and consequentially erroring out with "Invalid number".

### Steps to reproduce
- install latest Signal v6.12.6
- start the registration process
- enter valid phone number "+32 486 123456"
- Signal enters captcha mode to verify human interaction

**Actual result:** 
After successful captcha completion, Signal immediately displays an modified phone number (automatically replacing country code +32 with +1) and errors out.

Repeating the process yields the same erroneous result.

**Expected result:**
Signal should not change the country prefix, and send the verification SMS to the supplied phone number.

### Screenshots

* step 1 : enter phone number
![Signal-01a](https://user-images.githubusercontent.com/989004/222953941-62d9fe3d-37ed-4a5f-8844-90670c59d946.png)
* step 2 : captcha
* step 3 : receive verification SMS
![Signal-02a](https://user-images.githubusercontent.com/989004/222953947-8f2ccd53-192a-4392-a580-cc362cb83786.png)

### Device info

**Device:** Poco F3
**Android version:** 12 (LineageOS 19.1 alioth 20230304)
**Signal version:** 6.12.6

### Link to debug log
- no debug log, as Signal was unable to complete the registration process
- no adb logs related to the issue (filtered on "thoughtcrime|securesms|whisper|signal")

### Additional information

- I have installed Signal many times over the past years (both clean installs and account transfers/migrations), and have never before experienced this issue.
- The issue occurs : 
  - in both a personal and a work profile (set up through Insular)
  - with 2 different SIMs (dual-sim phone)
  - with clean install (no account transfer)
  - after successful account transfer (with both variations : from backup, and through wireless account transfer)
  - with both standard Messaging app and Signal being set as default SMS app
-  Signal is registered in microG/GCM to receive push notifications
- The phone has no issue receiving SMS messages on both SIMs
- Signal worked correctly on the previous phone (dual-sim Xiaomi Mi6)

**Comment by Sgn-32** [comment]
Someone has reported it in the beta 6.13 thread.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-13-release/51700/22

_When registering up with a non +1 country code, after filling out captcha it then says “Invalid number” and shows +1 with my number. After changing it back to my proper country code it then registers properly._

**Comment by didierm** [comment]
Thanks for the follow-up.
At least with v6.12.6, changing back to the proper country code does not work, as this redirects to the captcha, and the subsequent +1 replacement.

**Comment by didierm** [comment]
I retried with (as of March 5th) the latest beta version v6.13.6 from the firebase development channel.
The issue is fixed in this version (which - thankfully - also did not lock me up in a captcha verification loop).

I leave it to the discretion of the developers to close this issue when/if they see fit.
