### ISSUE TITLE
"error connecting to service" when trying to register

### ISSUE THREAD

**Issue by OhaDerErste** [signalapp/Signal-Android#12837]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to re-register my Account on a New device I always get the error "error connecting to service"

### Steps to reproduce
- Install the Signal APK
- Enter your Phone number
- Enter the sms code

**Actual result:** I can't register my phone number
**Expected result:** I can register my phone number

### Screenshots

I cant take screenshots because Signal locked me out for 5h

### Device info

**Device:** Samsung Galaxy S9 (SM-G960F)
**Android version:** CrDroid 9.2 (No GPlay services)
**Signal version:** 6.13.6

### Link to debug log

I cant acess the logs since Signal doesnt let me log in

**Comment by OhaDerErste** [comment]
I will add logs as soon as I can register again

**Comment by albirs** [comment]
seems same error like #12835 and #12834
fixed in 6.14.2

**Comment by OhaDerErste** [comment]
where can I download that version? latest on the website is 6.13.6

**Comment by Striker789** [comment]
I currently have the exact same issue on a Samsung device.

**Comment by albirs** [comment]
6.14.2 still is beta
download on apkmirror dot com for example …
but you have to make new installation when you will change later to offical versions…

**Comment by Striker789** [comment]
I tried now, unfortunately it also didn't work...

**Comment by axl303** [comment]
6.14.2 - Doesn't work for me, also the one from Google Playstore doesn't work.
Android P30 Pro Huawei

**Comment by affengeist** [comment]
Same problem here with issue: #12839

**Comment by xxxcrow** [comment]
I have the same issue
The problem seems to be the gapps

**Comment by affengeist** [comment]
With a little skill and patience, registration works with the old Signal version 6.7.6.

**Comment by xxxcrow** [comment]
> With a little skill and patience, registration works with the old Signal version 6.7.6.

Or on a latest version of a patched signal 😁

**Comment by axl303** [comment]
Guys, the idea is to submit a report and devs to fix it, not to download older versions from shit mirrors apk websites or wasting time. First time trying to use signal - Ultra bad experience with google shit & apps. Telegram works like a charm. :)

**Comment by affengeist** [comment]
It's quite wonderful that other messaging apps work well for you @axl303 . 

Our intention with older/newer versions was that the developers could use this information to  isolate the problem (diff).

The test with older versions was possible in my case because I still had older versions stored on my disk and fortunately did not have to use an unofficial mirror.

**Comment by albirs** [comment]
> 6.14.2 still is beta download on apkmirror dot com for example … but you have to make new installation when you will change later to offical versions…

**Comment by cody-signal** [comment]
@OhaDerErste the 6.14.2 beta is now available from the Play Store Beta channel.

**Comment by axl303** [comment]
Hello, using "6.14.2" finally fixed the problem (from today). I was able to register and now using Signal without any problems.
The version I used is: "6.14.2", before 1-2 days it was not working, but today (14 March) everything is fine - Thank you devs.
Working like a charm on a: Huawei P30 Pro, Android everything updated to latest (android,google etc.)
Thank you devs. :)

**Comment by cody-signal** [comment]
We've also released 6.13.7 on our website (https://signal.org/android/apk/) that has the hopefully fixes in it. It'll be available on Play Store once approved.

**Comment by xxxcrow** [comment]
> We've also released 6.13.7 on our website (https://signal.org/android/apk/) that has the hopefully fixes in it. It'll be available on Play Store once approved.

![Screenshot_20230314-220417_Signal](https://user-images.githubusercontent.com/24483751/225044834-e678214e-5601-4db8-9adb-e48230b5f959.png)
😅?

**Comment by OhaDerErste** [comment]
> @OhaDerErste the 6.14.2 beta is now available from the Play Store Beta channel.

I'm using a degoogled phone

**Comment by OhaDerErste** [comment]
just downloaded 6.14.2. Everything works now

**Comment by cody-signal** [comment]
@xxxcrow can you provide an updated debuglog running 6.13.7 or 6.14.2?

**Comment by xxxcrow** [comment]
> @xxxcrow can you provide an updated debuglog running 6.13.7 or 6.14.2?

I hope I did everything right and this is the log you need 😄
I tried two times, first time it accidentally worked(it rarely happened on the previous versions too)
https://crypt.xnode.link/note/1uM6UNOdDCwD7LvlnR3pfSOpL8cxfffMiFByW1kaoG0m#1096d1a7101f160f99c2f5ca2eaec771c1d61e474d7f0fc36fa94f52582287fb
Let me know if the URL is broken or something else

**Comment by cody-signal** [comment]
@xxxcrow not exactly what I was hoping for. You can get a debuglog from the app by tapping any title in the registration flow 8 times or going to Settings->Help->Debuglog in the app.

**Comment by xxxcrow** [comment]
> @xxxcrow not exactly what I was hoping for. You can get a debuglog from the app by tapping any title in the registration flow 8 times or going to Settings->Help->Debuglog in the app.

😅😅😅😅😅
https://debuglogs.org/android/6.13.7/b0a59fe46d438ba1c1ffe0ba80f64a37491b2cea4508fc5675555c8791ca4d20

**Comment by cody-signal** [comment]
Whoa...your logs are...unexpected. It seems like you end up in a bad state with respect to the server. We're looking into it.

**Comment by xxxcrow** [comment]
> 

My signal app got a notification about the update 
I'm on 6.13.8, same thing

**Comment by cody-signal** [comment]
The plot thickens, got new info, chatting with our server team.

**Comment by Okechukwu88** [comment]
Not working

**Comment by lm2lm2** [comment]
Hi,

had same issue

i had a big advantage : automatics backup were setup.
So when this issue occured, i had a j0 plus a j-7 backups
i use rarely signal

i tried tons of things :
-different pin unlock attempts, but no one said "right pin" nor "wrong pin"
-upgrade to the latest version of signal

then i had the idea to take another ungoogled android device : i installed latest version of signal, and "tested" backups. The recent one did not worked. The older one (one week older) worked. just had to do same on the original device.

Then i completely wiped data of my signal app
i opened it again, took "restore" choice, and used my old backup
and then validated my number by sms

everything worked, but it's a real bad signal from a such app..
