### ISSUE TITLE
Signal froze the phone when tried to answer a call

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#12838]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
An incoming call was displayed on the mobile phone while the desktop app (Linux, 6.9.0) was also running. I plugged in my headphone into the phone and clicked on the green accept call button.

I saw the state change from "incoming call" to "answering..." (in local language) while the phone kept buzzing and the desktop Signal ringing. After some seconds I realised that Android Signal froze, so I wanted to background it, but I could not. Android was frozen, too. The best I could do was forcibly restart the phone.

In the meantime I could switch to desktop with my headphone and answer the call there. That was nice.

### Device info

**Device:** moto g100
**Android version:** 12
**Signal version:** 6.13.6

### Link to debug log
https://debuglogs.org/android/6.13.6/914dd65d1a221cce53a23791e89f92a2b5a46253afa74d94f64471e490dfb33c

**Comment by szotsaki** [comment]
I don't know how relevant is it but the logs show a deadlock:

```
[6.13.6] [40467] 2023-03-11 18:50:02.835 GMT+01:00 W warn_current_thread_is_deadlocked.cc: (line 19): Probable deadlock:

[6.13.6] [40467] 2023-03-11 18:50:02.858 GMT+01:00 W warn_current_thread_is_deadlocked.cc: (line 20): #00 pc 00303aa6 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc_rffi.so
#01 pc 00212dd2 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc_rffi.so
#02 pc 00303556 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc_rffi.so
#03 pc 0025f9de /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc_rffi.so
#04 pc 0025c1aa /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc_rffi.so
#05 pc 0021f706 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#06 pc 001517b6 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#07 pc 001e70fe /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#08 pc 001ff6f2 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#09 pc 00148d2a /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#10 pc 0010c286 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#11 pc 0025d7b2 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#12 pc 0025cefe /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#13 pc 00271426 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#14 pc 0025ca0a /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#15 pc 0026bd56 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#16 pc 0026da66 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#17 pc 0026f1d6 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#18 pc 00260a72 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#19 pc 0025a32a /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#20 pc 0029bf56 /data/app/~~nD_gEt4cwUD4RylYkGnccg==/org.thoughtcrime.securesms-YbSMr2SPy13QJBfxWbWnwQ==/lib/arm64/libringrtc.so
#21 pc 000b6976 /apex/com.android.runtime/lib64/bionic/libc.so
#22 pc 00053212 /apex/com.android.runtime/lib64/bionic/libc.so
```

**Comment by inaqui-signal** [comment]
Does this happening consistently? Did it resolve after restarting the device? Also please confirm that you allowed permission to use the microphone.

**Comment by szotsaki** [comment]
* It happened only once, I could not reproduce it.
* Yes, it was resolved after the device restart
* I double checked, and interestingly, microphone access is forbidden for Signal
  * However, it says the last time I used it was earlier today (when I called someone)
  * Speaking over microphone does work normally when I call someone (and Signal doesn't ask for permission either)

**Comment by cody-signal** [comment]
We've passed this onto our calling team and they're looking into it.
