### ISSUE TITLE
Scheduled Message in Group of >40 people get sent, but shows in details "Not Sent"

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#12833]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I schedule some daily information to a signal (admin only) group. The messages get sent at the right time and the seen indicator appears, but within the message details, the status "not sent" is shown.
Checking the same message on desktop shows correct details with read and delivered information.

### Steps to reproduce
- schedule a message within a (admin only) group >40 people
- wait the message to get sent 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
check the message details and see the status "not sent" even if read indicator is shown next to the message

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Get the correct sent, delivered, read informations to all the recipients in message details.

### Device info
**Android version:** 12
**Signal version:** 6.14.1 (but already appeared in 6.13.X)

**Comment by clark-signal** [comment]
Hey thanks for reporting. Do you happen to have a screenshot (please blur out anything you need to)? We do show a "Not sent" section in the message details screen, which will show up if there are users that the message was not sent to, is this what you're seeing?

**Comment by mawed** [comment]
Here the Screenshots from Android (sending device)

![Android2](https://user-images.githubusercontent.com/11197868/225137748-e97c76ba-e4c6-4127-92bc-9faa55fa56fd.jpeg)
It shows "Not Sent" for all group members, but the messages were sent (as far as the people I asked for it)
On Desktop it shows the right details:
![Desktop](https://user-images.githubusercontent.com/11197868/225137925-4692f2ae-be93-4b00-bc5d-33ef08ecd192.jpg)

In the last days, the messages do show the right message details on Android too.

**Comment by clark-signal** [comment]
Thank you for the screenshots! It sounds like it is now working properly?

**Comment by mawed** [comment]
The last few days, the problem did not appear again.
But it did appear for 4-5 days.

**Comment by mawed** [comment]
It did not happen again, shall I close this ticket @clark-signal ?

**Comment by greyson-signal** [comment]
I'll close this issue, but concerning the "long scheduled message" question: you should be able to see the content of long scheduled messages. In the bottom sheet, the message should have a "read more" link at the end, allowing you to read everything. If that's not the case, please open a new issue. Thanks!
