### ISSUE TITLE
Stuck in registration loop

### ISSUE THREAD

**Issue by Fade9947** [signalapp/Signal-Android#12835]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Registration doesn't go through on a new phone. The procedure ends with a "You have made to many attempts to register..." with varying time-outs before for re-try is allowed.

I first tried the transfer from my old to the new phone, which wasn't successful then proceeded to restore a signal-backup.
Once the restore was completed the registration process starts but cannot be completed. On some attempts the verification SMS is received and after entering the code the process still ends with the attempts exceeded notification, on other attempts for registration that step isn't reached.
Signal on my old phone now also shows me as "Device no longer registered...", and trying to re-register there also ends up in "You have made to many attempts....". The application has been running on the old device for several months up until the moment i wanted to transfer to the new device.

(Re-)Registration on on both devices has been tried from different wireless networks as well as on mobile data connection.
On the new device Signal was uninstalled several times after running into the registration issue, successive installs were done via direct apk-download from signal web-site and install via aurora store.

### Steps to reproduce
on new device (after fresh Signal install via aurora store + allowing all permissions select-able in app-settings):
- tap "Transfer or restore account"
- select restore from backup
- tap choose back-up
- select back-up
- tap restore backup
- enter back-up passphrase (once the back-up is restored providing a location for future backups is requested which was done)
- enter phone-number
- confirm verification notification for phone-number
-  confirm Missing Google Play Store-notification
- solve capture
- confirm verification notification for phone-number again
- confirm Missing Google Play Store-notification again
=> Ends with "You have made to many attempts....."

on Old device running e.foundation e/OS:
- open Signal
- tap "Device no longer registered"-notification
- select country-prefix
- enter phone-number and continue
- confirm "Verification code will be sent"-message
- enter pin
- confirm "Verification code will be sent"-message again
- solve capture
- confirm "Verification code will be sent"-message again
=> Ends with "You have made to many attempts....."

**Actual result:** Registration ends with "You have made too many attempts"
**Expected result:** Successful registration

### Device info
New device:
**Device:** OnePlus A6003
**Android version:** 13 (LineageOS 20)
**Signal version:** 6.13.6

Old device
**Device:** Moto G4
**Android version:** 7.1.2 (e.foundation e/OS)
**Signal version:** 6.13.6

### Link to debug log
Log from Old Device
https://debuglogs.org/android/6.13.6/5fddd472dc66263da42197e65dd76aced96cc77b12a2f89a406df0edb5e2227f

**Comment by albirs** [comment]
almost the same Probplem here #12834

**Comment by Fade9947** [comment]
> almost the same Probplem here #12834

Agree to the almost part, i did find similar issues reported prior to filing.
However i find it quite odd that the issue also shows on my old device where Signal has been working nicely.
There were no major changes to this device and after waiting for the re-register time-out to count down registration should go through.

**Comment by albirs** [comment]
the problem seems more frequent:
https://community.signalusers.org/t/signal-media-coverage-articles-news/1458/2051

**Comment by florisdipt** [comment]
I am facing the same issue, my old device is no longer signed in and i recieved a timeout of 5 hours trying to register.
Other than timeouts I would also get an error that it could not communicate with services on the rare occasion it actually asked me for a verification pin.
Tried the same process as user above.

I've not been able to communicate all day. 

My process:
1. Tried transfering from in app(wifi-direct) but did not succeed
2. Tried restoring a backup and proceeding to activate via sms from there
3. Tried restoring withouth backup. to no avail.
4. Recieved a timeout for 5 hours(ouch)
5. Tried installing google play services
6. Tried activating on a secondary number that was not timed out (yet) but got a prompt google play services wanted sms access and did not feel comfortable granting it so cancelled that. And recieved a timeout again.

Also maybe notable. The A2 has microG


Now going to try with a earlier version of signal android will try to place another reply.

Device info
New device:
Device: Pixel 6A
Android version: 13 (GrapheneOS)
Signal version: 6.13.6

Old device:
Device: Xioami MI A2
Android version:  11 [CalyxOS 2.14.0](https://en.wikipedia.org/wiki/CalyxOS)
Signal version: 6.13.6

**Comment by albirs** [comment]
thank you @florisdipt ! sadly i dont have an other phone number. but i'm on Signal 6.12.6 and hope that some time my number gets unblocked. I hope it doesn't take 7 days. I only use Signal and currently have hardly any communication and everyone is wondering why I "left" Signal... :-(

**Comment by Tsi-Napah** [comment]
Same issue here on sony xperia xa2.
I tried singal app 6.14.1, 6.12.4 and 6.13.6 
I tried on lineageOS 18 with microG, lineageOS 19 with and without microG
I checked permissions, sms limit and trust configuration.
I can register with sms on other apps (banking, vpn...)
I dont know what else to do...

**Comment by albirs** [comment]
may this commit is targeting the problem
https://github.com/signalapp/Signal-Android/commit/6fb31671577e0b6335f04f553efeff49fa32b2b2
"Don't reset session on return from captcha."

**Comment by pixincreate** [comment]
> may this commit is targeting the problem [6fb3167](https://github.com/signalapp/Signal-Android/commit/6fb31671577e0b6335f04f553efeff49fa32b2b2) "Don't reset session on return from captcha."

That didn't fix the issue, at least for me. 
P.S: I tested it on my builds

**Comment by Lurkars** [comment]
Same issue here.

**Comment by Tsi-Napah** [comment]
From https://github.com/signalapp/Signal-Android/issues/12834, try with Signal version 6.14.2 (available on apk mirror)

**Comment by Lurkars** [comment]
> I blocked two phone numbers with time out but was able to activate on my third one with Signal version 6.12.6 (121907) withouth Google play or microG. So i can confirm the problem did not occur on that version. 

Can confirm. Luckily, I found an older APK download and didn't had to trust APKMirror, but using an older version, activate account and then update did work for me!

**Comment by Tsi-Napah** [comment]
> > I blocked two phone numbers with time out but was able to activate on my third one with Signal version 6.12.6 (121907) withouth Google play or microG. So i can confirm the problem did not occur on that version.
> 
> Can confirm. Luckily, I found an older APK download and didn't had to trust APKMirror, but using an older version, activate account and then update did work for me!

Which version did you use?

**Comment by Lurkars** [comment]
> > > I blocked two phone numbers with time out but was able to activate on my third one with Signal version 6.12.6 (121907) withouth Google play or microG. So i can confirm the problem did not occur on that version.
> > 
> > Can confirm. Luckily, I found an older APK download and didn't had to trust APKMirror, but using an older version, activate account and then update did work for me!
> 
> Which version did you use?

The one mentioned: 6.12.6

**Comment by albirs** [comment]
with the APKMirror version 6.14.2 finaly did works for me!!

**Comment by Tsi-Napah** [comment]
Wonderfull now with better coveragem it worked.

Thank you very much Signal dev team!!

**Comment by Fade9947** [comment]
@florisdipt: Managed to re-register on version 6.12.6 as well, thanks for the tip to this workaround.

**Comment by florisdipt** [comment]
> @florisdipt: Managed to re-register on version 6.12.6 as well, thanks for the tip to this workaround.

No problem. 

Just so you know the devs will probably re-open this issue until they've fixed and rolled out the bug.

**Comment by albirs** [comment]
@florisdipt @Fade9947 
Strangely, 6.12.6 did not work for me, although I have exactly the setup as described above:
Device: OnePlus A6003
Android version: 13 (LineageOS 20) without Google
... only with 6.14.2 i had success
