### ISSUE TITLE
Unexpected message: "SMS messaging is no longer suported in Signal."

### ISSUE THREAD

**Issue by jgilmore** [signalapp/Signal-Android#12849]
I knew it was coming, and of course I, like any sensible person would, disabled updates to signal.

My wife did not, and upgraded to signal 6.13.7. I don't know what process she's gone through, but she's no longer able to send SMS messages, and conversations which are with SMS only contacts now display that message.

So was support removed? If so when? I don't see it in the changelogs anywhere that I can find.

I need to know when exactly it was removed so I can downgrade her version of signal to one that actually F*K'N works. If it's NOT actually removed in version 6.13.7, how to I enable it again? If it was auto-magically forced off as part of the "exporting SMS messages" process, never to turn on again, what version do I have to rollback to that doesn't have this misfeature?

While I understand and agree with your decision to no longer support SMS, That's solely due to google not releasing the API for their latest SMS interface. I very much disagree with the way you're forcing that change on people. It's on my phone, it works, leave it alone. I realize that it's not working for everyone, but that's their problem. I see removing it's availability for people for who it's working as a deliberate crippling of functional software, which is against the open-source philosophy of "it's running on my hardware, and I can do what I want with it. This includes fixing bugs, disabling "misfeatures", and in general it is and *should be* under my sole control."

I have long said, and I maintain, that if you remove support for existing working installations, the only sensible action is to 1. stop updates, and 2. fork the project if needed to fix existing bugs/add new features. We'll call it "nonsignal private messenger" or some such, I'm sure. Just like iceweasel in debian.

I also notice that this github repository is several versions behind the play store. What did you add in the more recent updates that you don't want us to know about? Or where is the source for the latest version?

**Comment by Max-Stirner-Signal** [comment]
Signal is removing SMS/MMS support from Android. This means that it will no longer be possible to send unsecure SMS/MMS messages with Signal. Only Signal to Signal messages will be possible.

You can learn more on why we are doing this in the support page:
https://support.signal.org/hc/articles/360007321171#android_sms

For more information on how to export your existing SMS messages to another SMS app, please visit this guide:
https://support.signal.org/hc/articles/360007321171#android_sms_removal_steps

**Comment by bme13** [comment]
I don't think it's related to a specific version. See https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-very-soon/47954/1801. 
It seems to differ for everyone depending on there usage.
>I also notice that this github repository is several versions behind the play store. What did you add in the more recent updates that you don't want us to know about? Or where is the source for the latest version?

Not sure to what version you're referring. I think the playstore version is 6.13.7 (or .8?) while the latest github version is 6.14.4.

**Comment by cody-signal** [comment]
Sometimes we have to do things called "hotfixes" where we have to fix a bug in an earlier version after we've already publish newer ones. When we do that, we have to make a new branch for that hotfix version. Typically all these are, are short branches with cherry-picked fixes from the main branch.

We tag every release so it's easy to find: https://github.com/signalapp/Signal-Android/tags

**Comment by jgilmore** [comment]
Yeah, having examined this I can only reach one realistic conclusion:

Signal got too big and too popular, and so somebody decided to limit it, and bribed or threatened the devs to destroy it, coming up with a very effective strategy of removing existing functional features to make it unusable by the majority of non-technical users.

It's also possible they took over the project, hiring bad actors to contribute until they controlled, and again sabotaged it from the inside.

Either way, it it my opinion that "An enemy has done this" is the most reasonable explanation for the high-handed and implacable destruction of the signal private messenger we all knew and loved.

Any volunteers to compile and post a non-crippled version? At this point it's just a matter of spoofing the "do we force the removal of SMS for this person" checks.

We can re-brand and distribute a "Lets Go Signal" version after the hotfix is out. Because Fuck them.

**Comment by JerryK13** [comment]
All the harsh wording aside, you can find such a fork in my repo. This is however a temporary measure. Once they start removing sms code and mess with the db, the fork will become harder to maintain.

**Comment by WSLUser** [comment]
@JerryK13 I am really glad to see your fork exists (along with the fork you actually forked from as it supports both my complaints with Signal proper - plaintext backup and SMS support being dropped). I have question of if I'm able to install your apk and be seen as an "update" to my existing Signal installation? I was a beta user but dropped that and stopped updating but lost SMS support anyways. If answer is yes, then I won't be concerned about my existing backups. If the answer is no, then I would ask if importing my existing backup would work with functionality still intact for SMS support

**Comment by Starztash22** [comment]
Hi

**Comment by JerryK13** [comment]
@WSLUser as my apk signature is different you must first make a backup within the original build, then you uninstall the original apk and restore from your backup at the installation of my fork.
If you later decide to go back to the original build, you make a normal signal backup within my build, uninstall my build and restore from that backup at the installation of the original build.

**Comment by TheGrave** [comment]
> [@WSLUser](https://github.com/WSLUser) as my apk signature is different you must first make a backup within the original build, then you uninstall the original apk and restore from your backup at the installation of my fork. If you later decide to go back to the original build, you make a normal signal backup within my build, uninstall my build and restore from that backup at the installation of the original build.

Latest release in your repo tells me: "Unable to connect to service"?
