### ISSUE TITLE
Scheduled messages are shown as alarms on the status bar

### ISSUE THREAD

**Issue by martino2002** [signalapp/Signal-Android#12848]
I know this isn't a bug and it's probably intended, but that doesn't make it less stupid (I didn't have any other option apart from bug report in the New Issue page).
I simply want to understand why it was chosen to treat scheduled messages like alarms.

**Comment by danielsparing** [comment]
Yeah I hope this wasn't intended, as it gives the user the impression of an alarm coming up.

Besides the Alarm notification tile it also comes up on the lock screen.

**Comment by greyson-signal** [comment]
Closing as a duplicate of #12806
