### ISSUE TITLE
picture zoom in not work on android

### ISSUE THREAD

**Issue by emonfejm** [signalapp/Signal-Android#12845]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening picture, it can not be zoomed in using two fingers.

### Steps to reproduce
click on te picture in the message

**Actual result:**
It is happening nothing.
**Expected result:**
The picture will be bigger

### Screenshots
n/a

### Device info
**Device:* one plus 7t
**Android version:** Oxygen OS 11.0.9.1.HD65AA
**Signal version:** 6.14.2

### Link to debug log
n/a

**Comment by cody-signal** [comment]
Could you provide a debug log? I'm unable to reproduce this. Additional do you happen to be using conversation bubbles or just normal?
