### ISSUE TITLE
Video call display corruption

### ISSUE THREAD

**Issue by xcelente** [signalapp/Signal-Android#12840]
During video calls, sometimes my image on the other side becomes garbled / corrupt and requires me to restart the call. My side of the video looks fine. I suppose this could be a GrapheneOS problem but I haven't seen the same problem within Element.

**Comment by inaqui-signal** [comment]
If possible please provide a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) so we can take a closer look.
