### ISSUE TITLE
Send later doesn't work when sending to multiple chats at once

### ISSUE THREAD

**Issue by AmirGamilDev** [signalapp/Signal-Android#12842]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a message to multiple chats at once, send later doesn't work

### Steps to reproduce
- Share an image from outside Signal
- Select more than one chat to send to
- Long tap send button
- Select time to send message

**Actual result:** 
Message is not sent and I am returned back to the chat selection screen

**Expected result:**
Message should send to multiple chats at time specified

### Device info

**Device:** Samsung Galaxy A52sb5G
**Android version:** 13
**Signal version:** 6.13.6 (verified as also occurring on 6.13.7 but debug log is from 6.13.6)

### Link to debug log
https://debuglogs.org/android/6.13.6/b98a7d565c07abf3d516f467bad62afcb456886cf9023e103f9d52bb4a86b86d

**Comment by cody-signal** [comment]
This is fixed and will be in 6.15

**Comment by AmirGamilDev** [comment]
Just tried this on 6.18.4. Nothing happens when long press send in this scenario.

**Comment by greyson-signal** [comment]
I think the "fix" was that we shouldn't have provided the option to do scheduled sends from that screen. Right now we don't support multi-target scheduled messages. Maybe in the future!
