### ISSUE TITLE
Crash while opening chat after restoring from backup

### ISSUE THREAD

**Issue by pkar70** [signalapp/Signal-Android#12855]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 I just moved Signal to new device (from Nugat to Pie). Installed Signal, and used procedure from
https://www.reddit.com/r/signal/comments/lism5g/cannot_restore_backup_on_new_phone/
to restore backup on new device.
When I start Signal, everything looks OK (list of chats). But after tapping on chat, chat only flashes, than return to list of chats.
Restarting device doesn't solve problem.

### Steps to reproduce
- restore backup
- try to enter any chat

**Actual result:** returns to chat list
**Expected result:** shows chat, and allows to write any message

### Device info

**Device:** Bluestack 5 emulator
**Android version:** Pie
**Signal version:** 6.13.8

### Link to debug log
https://debuglogs.org/android/6.13.8/79280bb9cfd12ecc7fe212c229f0d16cd57a50b8f60155c0bf1df0cff54f0574

**Comment by greyson-signal** [comment]
Hi there, it looks like the database is partially corrupted after restoring the backup. This is something we've got a few reports about and have been trying to figure out. 6.15 (currently in beta) has some extra logging, so hopefully that'll give us a better idea of what's happening. 

In the meantime, if you still have your backup, we've found that "trying again" (reinstalling and restoring from backup again) often fixes it.

**Comment by hmumm** [comment]
I'm having the same issue I believe, here are the steps I took:

- download signal on new phone
- choose restore, transfer from another device
- go through all steps on new and old phone
- says transfer failed, no further error is given

Next I tried copying over a backup and restoring. This just caused signal to crash.

Reinstalling did nothing, same issue. Tried both multiple times. 

Let me know if any other info will help you.

**Comment by pkar70** [comment]
I just workaround problem, but I don't know if this is acceptable for you.
* in source Signal, make current backup
* remove all media (~260 MB)
* make another backup
* copy signal backup files to desktop
* use https://github.com/xeals/signal-back to extract all media files from first backup (extracting messages doesn't work for me, I got empty file)
* copy smaller backup file to new device, to Downloads folder
* reinstall Signal on new device, select "transfer" and "from backup"
* now, messages are restored and Signal doesn't crash on entering chat

**Comment by greyson-signal** [comment]
@pkar70 Ah, I'm sorry you had to go through all that. If you ever hit the issue again, you could install 6.15.2 (not in the play store yet, but [here's a link](https://updates.signal.org/android/temp/Signal-Android-play-prod-universal-release-6.15.2.apk) to the APK) and see if you could get logs afterwards.

@hmumm Can you share a log after you hit the crash? To get a log during registration you can tap on the header text on one of the registration screens 8 times.

**Comment by hmumm** [comment]
https://debuglogs.org/android/6.13.8/0acfb85c16d400b4a7352cf1ff074773a5d6bb4b557863075ad81c1e5e04c563

**Comment by hmumm** [comment]
Here are logs for the transfer process. From the new phone: https://debuglogs.org/android/6.13.8/6cbbb14d13b9feee6485e09dfcbca6d4c688fb0e0da6f7178d9124582445bfd7
From the old phone:
https://debuglogs.org/android/6.13.8/0bab33d5dbec9eeca0398d67980443d7cedb786290ad218f274cdd8cc11aed1a

**Comment by nicholas-signal** [comment]
marking as completed because #12857 is completed
