### ISSUE TITLE
Message notification sound doesn't play

### ISSUE THREAD

**Issue by MiracoleWorker** [signalapp/Signal-Android#12851]
OnePlus 5
LineageOS + microG 20.1
Signal version 6.13.7

Signal stopped playing the selected tone when receiving a message. I tried selecting other tones, uninstalling and reinstalling Signal, and force quitting and clearing the cache. The message tone never played. Incoming calls do trigger the appropriate tone. 

Expected behavior: Signal receives a message and plays the selected notification tone.

Actual behavior: Signal receives a message, vibrates, but does not play any tone.

**Comment by cody-signal** [comment]
A debuglog would be helpful.

**Comment by cody-signal** [comment]
Sorry for the delay, is this for all messages or a custom channel for a specific contact? Nothing jumps out from your logs as unexpected. And to confirm, you are getting notifications, just not hearing any sound?

**Comment by MiracoleWorker** [comment]
It's for all Signal messages, yeah. And I do get notified; it pops up locked or unlocked and vibrates. It's just quiet. I've tried different tones and the same thing happens.

**Comment by cody-signal** [comment]
> It's just quiet.

As in the vibration is or there is a sound playing but the volume is low?

**Comment by MiracoleWorker** [comment]
Every notification is just a vibration, no sound.

**Comment by cody-signal** [comment]
Sometimes we have a bug where the sound is routed incorrectly and using media volume or something like that. Just confirming that you've tried this will all the volume bars maxed (media/ring/notifications/etc)

**Comment by MiracoleWorker** [comment]
I've made sure my media, alarm, and notification volumes are all up, if that's what you mean?

**Comment by cody-signal** [comment]
Yes, I figured you had, but...gotta ask. Thanks for being responsive, sorry we don't have much to show for it.

Which Lineage version are you on and I can try to repro with one of mine.

**Comment by MiracoleWorker** [comment]
That's okay; I understand it might take time. My LOS version is 20-20230307-microG-cheeseburger. 

For added context, I've been using Signal on LOS + microG for years without issue. It's always possible that a recent change might've broken something, but generally it's worked just fine.

**Comment by cody-signal** [comment]
I installed the `lineage-20.0-20230313-microG-walleye` build on my pixel 2, enabled the various microg push stuff, and then install the latest signal and couldn't reproduce. :(

**Comment by MiracoleWorker** [comment]
Damn, that's disappointing. I just tried turning different notification settings on and off (signal and general), updating my OS (20-20230409-microG-cheeseburger), trying different tones, general troubleshooting from the signal site, and still no luck. I'm at a real loss :/

**Comment by cody-signal** [comment]
Sorry boss. Don't know what else to try at this point. Without being able to repro it or having others report similar issue to try and derive a common thread, there's not much more I can do.

**Comment by MiracoleWorker** [comment]
That's fair, thanks for your efforts.
