### ISSUE TITLE
Rotate screen icon doesn't show up during calls

### ISSUE THREAD

**Issue by ShaqibK** [signalapp/Signal-Android#12853]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During a signal call the Rotate screen icon, one that appers on bottom left of the screen, wont show up when device is rotated. On app it works fine, only on calling screen this issue occours. Everytime going to settings to toggle autorotate on then turning it off after call is not feasible when there is a good option available. 

The icon looks like this
![Screenshot_20230320-233000_Brave](https://user-images.githubusercontent.com/86542526/226429306-1aeaf75c-0d1c-46c4-b1e5-4c93e80ac016.png)

### Steps to reproduce
- open signal app,
- rotate the phone 90°, the rotate screen icon shows up on bottom left corner,
- Start/join a call,
- rotate the phone 90°, the rotate screen icon wont show up.

**Actual result:** The rotate screen icon wont show up when screen is rotated during calls.
**Expected result:** The rotate screen icon should show up when screen is rotated during calls also.

### Device info

**Device:** mi 11 lite ne 5g
**Android version:** 13
**Signal version:** 6.13.7

### Link to debug log
https://debuglogs.org/android/6.13.7/d945148c8b00a6d181e84f8ec92e9b289d97773111611e96198f991f66c03225

The call happened at 22:22 IST on 20/03/2023.

**Comment by Slin-nilS** [comment]
Is this Issue still existing? Because I had a similarly but not the same issue. See [14142](https://github.com/signalapp/Signal-Android/issues/14142)
