### ISSUE TITLE
Can not donate to Signal using Mobilecoin

### ISSUE THREAD

**Issue by vitamins** [signalapp/Signal-Android#12859]
Mobilecoin is a failure and should be removed from the App's menus as it gives Signal a bad reputation.

The fact that we can not donate to Signal using Mobilecoin, gives the impression that Signal organization does not believe in the future of Mobilecoin.

Furthermore, the media has reported on possible financial profiteering by the signal developers through Mobilecoin. You can now clear up such doubts about your motives by removing Mobilecoin.

**Comment by greyson-signal** [comment]
Hi there, we use Github for bug reports. For discussions, you can use [the forum](https://community.signalusers.org/).
