### ISSUE TITLE
No longer receiving any notifications whatsoever

### ISSUE THREAD

**Issue by yarsiemanym** [signalapp/Signal-Android#12854]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have used Signal on this phone (Google Pixel 5a with GrapheneOS and sandboxed Google Play Services) for about a year and everything worked fine. Then a few weeks ago, I suddenly stopped receiving any notifications. If I open the app I immediately get notified of all messages I have received since I last opened the app.

I have set Google Play Services, Google Services Framework, and Signal to all have unrestricted battery and data access.

### Steps to reproduce
- Close the Signal app
- Have a contact message me
- No notification received
- Open the Signal app
- Receive a notification and also see the new message in the list

**Actual result:** Notifications aren't received until I open the app.
**Expected result:** Push notifications are received in the background so I don't have to constantly check the app for new messages.

### Screenshots
None

### Device info
**Device:** Google Pixel 5a
**Android version:** 13 (GrapheneOS with sandboxed Google Play Services)
**Signal version:** 6.13.8

### Link to debug log
https://debuglogs.org/android/6.13.8/2f4975dc30678e509467f25cc8e824b7f061f02ac748a1e01708f688937a6887

**Comment by greyson-signal** [comment]
Hi there, unfortunately your log is showing that we're not getting any FCM messages. It's likely the case that either your OS isn't delivering them, or for some reason google stopped forwarding them to your device (maybe it got flagged or something by some Google system, I couldn't say). But I don't think there's anything that the app can do :(

**Comment by yarsiemanym** [comment]
Thanks for the response. I'm not surprised. While I haven't gotten _any_ notifications from Signal, WhatsApp has also been spotty. I occasionally don't get notifications from it either. I'll go pester the GrapheneOS team about it.

**Comment by wertzuz** [comment]
Hey main thread for all issues seems to be #8692
