### ISSUE TITLE
Old progress dialog style when deleting chat

### ISSUE THREAD

**Issue by cyb3rko** [signalapp/Signal-Android#12852]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When deleting a chat the confirmation dialog is fine (using the M3 dialog styling), but the progress dialog that is shown after confirming the deletion still uses the old dialog style.

### Steps to reproduce
- select a chat
- select Delete
- confirm deletion
- progress dialog appears

**Actual result:** The progress dialog uses the old dialog style.
**Expected result:** Usage of the M3 dialog styling to fit every other dialog in the app.

### Screenshots

The confirmation dialog uses the new M3 dialog style:

<img src="https://user-images.githubusercontent.com/46033730/226422914-1379f702-a4ae-4e92-8007-bca804026599.jpg" width="400">

---

The progress dialog afterwards uses the old dialog style:

<img src="https://user-images.githubusercontent.com/46033730/226423047-e1228082-8b56-47e7-8c5c-36b724069ec7.jpg" width="400">

### Device info

**Device:** Google Pixel 7 Pro
**Android version:** 13 (33)
**Signal version:** 6.13.7 / Update: Still relevant in 6.24.4 + 6.38.2

### Link to debug log
Not needed I suppose

**Comment by cyb3rko** [comment]
Still relevant

**Comment by cyb3rko** [comment]
Still relevant

**Comment by nicholas-signal** [comment]
Thank you for reporting the issue. The ProgressDialog [(ours is based on the system-provided one)](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/components/SignalProgressDialog.kt#L5) is not part of Material Design 3. Therefore we are going to have to design and implement our own. I've raised this with the Design team and will update this GH issue with developments if/when they occur.

**Comment by cyb3rko** [comment]
Still relevant

**Comment by cyb3rko** [comment]
Seems to be implemented now
