### ISSUE TITLE
Foreign key constraint violation during backup import

### ISSUE THREAD

**Issue by greyson-signal** [signalapp/Signal-Android#12857]
Migrating over from #12855

> - download signal on new phone
> - choose restore, transfer from another device
> - go through all steps on new and old phone
> - says transfer failed, no further error is given
> 
> Next I tried copying over a backup and restoring. This just caused signal to crash.
> 
> Reinstalling did nothing, same issue. Tried both multiple times. 
> 
> Let me know if any other info will help you.
> 
_Originally posted by @hmumm in https://github.com/signalapp/Signal-Android/issues/12855#issuecomment-1481325745_
            

Some extra logs
> https://debuglogs.org/android/6.13.8/0acfb85c16d400b4a7352cf1ff074773a5d6bb4b557863075ad81c1e5e04c563
> 
> Here are logs for the transfer process. From the new phone: > https://debuglogs.org/android/6.13.8/6cbbb14d13b9feee6485e09dfcbca6d4c688fb0e0da6f7178d9124582445bfd7
> From the old phone:
> https://debuglogs.org/android/6.13.8/0bab33d5dbec9eeca0398d67980443d7cedb786290ad218f274cdd8cc11aed1a

**Comment by greyson-signal** [comment]
Looks like a foreign key constraint violation, which the exporter is designed to avoid, but clearly something is going wrong.

I've added new logging to the current beta (6.15.3) which should tell us more about the order it's exporting tables in to see if the problem is in the exporter or if somehow bad data got stuck in the thread table.

**Comment by hmumm** [comment]
I signed up for the beta in Google play. It says I'm on 6.15.3 hopefully that's correct and can help you find the issue. Anyway here's the logs: https://debuglogs.org/android/6.15.3/1fe3d786e3b47debeb28daffcdee90df9695615503767d58a997f2363daf6771

**Comment by greyson-signal** [comment]
I'm sorry I didn't specify this earlier, but the new logging is added to the exporter. Do you still have access to the phone that created the backup? Could you have it create another and take a log?

**Comment by greyson-signal** [comment]
I'm sorry I didn't specify this earlier, but the new logging is added to the exporter. Do you still have access to the phone that created the backup? Could you have it create another and take a log?

**Comment by hmumm** [comment]
Here is when using the transfer on the old phone: https://debuglogs.org/android/6.15.3/a80be8c03cae749f3e654dad6dceb7c58c40dd507c25bcf1218fab1ddfd391b8

And here's after creating a backup on the old phone: https://debuglogs.org/android/6.15.3/57ceb5b5b998c44d4902cdd32f8d82304463641fbc3b2ffd5b77344f2fc09e33

**Comment by greyson-signal** [comment]
Thank you! It looks like the export is happening correctly, but somehow there's a thread_id with a dangling recipient. I'll attempt to fix this in the next release.

**Comment by hmumm** [comment]
Is there any update on this? I have not been able to use Signal at all because of this.

**Comment by nicholas-signal** [comment]
Yes: @greyson-signal added a fix for this issue (de0a37d356b0d74e1cc2cf9768a3e245abf03e33) that is currently in our beta releases. You can participate in our beta program by joining us in our community forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-16-release/52460/30

Or you can wait until the production release, which should be in less than a week.

**Comment by greyson-signal** [comment]
Worth noting that you have to create a new backup. It won't fix existing backups.

**Comment by hmumm** [comment]
Awesome, I was able to download the beta and the transfer went smoothly (I used the transfer option vs creating a backup). Thanks for the help I appreciate it.
