### ISSUE TITLE
Unability to access personnalized notification sounds on custom Rom

### ISSUE THREAD

**Issue by albatdawn** [signalapp/Signal-Android#12869]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After activating personalized notifications, when trying to change the notification sound, nothing happens.

### Steps to reproduce
- Select any conversation
- Click to access the conversation settings
- Click on Sounds and notification
- Click on personalized notification
- Tick "use personalized notification"
- click on "change sound and vibration"

**Actual result:** Nothing happens except sometime for a sort of black flash as if the sound selection menu had opened very briefly and closed immediately after.

**Expected result:** The Android menu for setting notification should open so that you could setup the sounds and vibration.

For information, it does work on the same device with e/os 1.7 (Android 11). This one does comes with MicroG, so maybe it could be related to that, don't know.

Also, I have access to the general application notification, when going to Signal's overall settings.

Let me know if I can help with that.

### Device info
**Device:** Fairphone FP3
**Android version:** Divest/Lineage OS 19.1 ( AOSP 12.1) without MicroG
**Signal version:** 6.14.5

### Link to debug log
https://debuglogs.org/android/6.14.5/9566e5599b97a8727c614b87dda5a1dd39200ab29eb23644dd111adca5b12b49

**Comment by nicholas-signal** [comment]
I see this error line in your logs:
```
java.lang.SecurityException: Permission Denial: reading com.infomaniak.drive.data.documentprovider.CloudStorageProvider uri content://com.infomaniak.drive.documents/document/794101%2FSalvatio%40146580%2F68944 from pid=10284, uid=10136 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```

Does ringtone selection work if you manually enable the `ACTION_OPEN_DOCUMENT` permission for Signal?

**Comment by albatdawn** [comment]
Hello,
Thanks for your reply.

I'm not sure how to give that permission, since it's not in the one requested from what I see.

I don't know if this is equivalent, but currently Signal has the permission to access multimedia files
It actually has all the requested permissions.

I should have said in the description that I'm able to select ringtone for the calls. Don't know if that helps.

I assume the error you see came from another action: when trying to share a file from Kdrive.

**Comment by albatdawn** [comment]
Good morning,

Just for other who might face the same problem, I'm giving the information that after an upgrade from Divest/Lineage OS 19.1 (AOSP 12.1) to 20 (AOSP 13) the issue does not occur anymore and I can set up custom notification as the menu is launched when clicking.
Same as [here](https://github.com/signalapp/Signal-Android/issues/12893)

Thanks.
