### ISSUE TITLE
QR Code Scanning - does this new install screen theme work on Android?

### ISSUE THREAD

**Issue by timjamello** [signalapp/Signal-Android#12865]
https://github.com/signalapp/Signal-Desktop/issues/6348#issuecomment-1487829646_
          
Over on Signal-Desktop, I wrote a PR that adapts the install screen to dark mode. @josh-signal noted that the QR code scanning library Signal uses on Android may not be able to scan a QR code without significant white padding around it.

Can someone with an Android device confirm whether or not the QR code is scannable in this screenshot?

![](https://user-images.githubusercontent.com/42359096/228386617-96a0947f-d918-4bdc-b8a7-5f4c1ebc565f.png)

Thank you.

_edit: I don't actually need anyone to click "Link" after scanning the code; this is a defunct QR code that would fail to link anyways._

**Comment by timjamello** [comment]
If requests like these are better suited to the community forum, please let me know.

**Comment by nicholas-signal** [comment]
The Signal Android client is able to read it fine!

Thank you for contributing to Signal.
