### ISSUE TITLE
scheduled messages - long messages no preview possible

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#12862]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Scheduling really long messages, there is now way to get a preview. You have to copy the scheduled message and insert somewhere to check the message content.

### Steps to reproduce
- schedule a long message
- show your scheduled messages

**Actual result:** 
No way to preview

**Expected result:**
Show a preview button to long scheduled messages.
(If you're on it, from a UX point of view, the next scheduled message is shown in a really short preview as all the others are shown with a long preview. As soon as this message is sent, the next message to be sent is also shown shorter.)

### Screenshots
![signal-2023-03-22-21-45-23-556](https://user-images.githubusercontent.com/11197868/227885003-4dc5c8d2-97c1-47eb-97d5-b5fd621759b6.jpg)

### Device info
**Signal version:** 6.15.3

**Comment by mawed** [comment]
This is only shown, when the message is really long within a group or an individual chat.

Did you try this with a message of 100 words and schedule it 2 or 3 times?

**Comment by haffenloher** [comment]
Can reproduce: if scheduled message is *really* long, I also get "Pending" instead of "Read more". One or two lorem ipsums weren't enough, here's the message I had to use: https://gist.github.com/haffenloher/09b68d9f314ecf3ca9bf755452dbeafa

**Comment by mawed** [comment]
@greyson-signal 
Is it reproducible with this information?
Or do you need a log?

**Comment by mawed** [comment]
@greyson-signal 

Still reproducible with 6.23.1

**Comment by mawed** [comment]
@greyson-signal @clark-signal 

Should this be solved by https://github.com/signalapp/Signal-Android/commit/9d33690f3436a439e60421b9ad42b569a4aa8e85?

**Comment by greyson-signal** [comment]
@mawed I think so
