### ISSUE TITLE
Delayed notifications on Android due to Desktop Client

### ISSUE THREAD

**Issue by RaXorX** [signalapp/Signal-Android#12867]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With Signal Desktop open/running in background notifications on Signal android are delayed or just do not appear at all. I get notified on my desktop but on app the notification isn't there. Moreover, the message doesn't even get synced to the android app and I have to open it, and let the messages sync to the phone.

### Steps to reproduce
- Install Signal Desktop
- Sync Signal Desktop with Phone app
- Keep android app running in background.
- Desktop can be running in background or actively open.
- Have someone send messages to you.

**Actual result:** Messages get delivered to desktop, sync to desktop properly and on time and I receive a notification instantly on desktop. Whereas on phone, the messages aren't even there when I open the phone. They take time to sync and since there's no active message received till it syncs up, I do not get any notifications at all on the phone.
**Expected result:** Since Signal Desktop is a "linked" device and not an active standalone client, messages should get received to the phone first triggering the notification on phone (this will happen automatically as long as messages get received on phone first) and then get synced with Desktop Client.

I can't recall the version but this issue started with recent betas only. A week or so ago Signal worked totally fine, I would get messages on phone first and then on Desktop (well, I'd get them at the same time even if they were running in background)

### Device info

**Device:** Xiaomi Mi 11X
**Android version:** 13.0
**Signal version:** 6.15.3

### Link to debug log

[signal-log-1680148102020.zip](https://github.com/signalapp/Signal-Android/files/11107542/signal-log-1680148102020.zip)

(At the time of posting it is about 9:20 am IST, the last message I received was about 40 minutes earlier, aka, about 8:40 am IST. My app was running in background and desktop was as well. Desktop had a notification at 8:40 am perfectly, the message was there as well. I waited 20 minutes or so but never received any notifications on android. I read the message in Desktop Client about 9:00 am and then opened my phone's app. The message wasn't there and it took it a couple seconds for it to appear on phone - so the message on phone was received about 9:02 am IST)

**Comment by RaXorX** [comment]
Apparently, it might be that signal is not able to detect play services. I just downgraded to 6.14.5 and it said something like this device does not support Play services. And to let Signal's background connection service run in the background... My device has play services just fine...

**Comment by greyson-signal** [comment]
Your log for 6.15 just didn't have any FCM notifications in it. Sometimes OEMs just don't give us notifications, and it's a black box, so these things can be next to impossible to diagnose.

> Since Signal Desktop is a "linked" device and not an active standalone client, messages should get received to the phone first triggering the notification on phone

Linked desktops actually function as their own client. The primary device does not need to be on or functioning for the linked device to receive messages.

As for 6.14, I believe 6.14 may have had a bug where we sometimes incorrectly thought a user didn't have play services, so I wouldn't recommend that release.

**Comment by RaXorX** [comment]
Well when I was on 6.14 it just gave me a notification that play services are missing and to use a constant service notification to receive notifications. Which is what I'm using. But 6.15 never gave me that option.
