### ISSUE TITLE
Some icons in Settings look broken on Android 6

### ISSUE THREAD

**Issue by DirkPitt1** [signalapp/Signal-Android#12868]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some icons in the app's Settings look broken on Android 6. I'm not sure if this is a new bug or something longstanding because I'm using the device very rarely these days. I don't see broken icons on Android 11 nor GrapheneOS.

### Steps to reproduce
- Open the app on a device with Android 6.
- Open Settings.

**Actual result:**
Some icons look broken.
**Expected result:**
All icons look right.

### Screenshots

![signal-2023-03-30-152049](https://user-images.githubusercontent.com/28538453/228851737-1ed44fc3-2d49-4995-9269-75252e10239f.jpg)

### Device info

**Device:** LG G4
**Android version:** 6.0
**Signal version:** 5.15.3

### Link to debug log

https://debuglogs.org/android/6.15.3/bef3b74bb6b9b46c8bfd992365581bb95f8cbb3e115a9b62d166ff15ecbf2136

**Comment by CryYxx** [comment]
I confirm this, on my Cubot echo with Android 6 icons in the menu look the same, and on the white theme too. This problem started a few versions ago when new icons were introduced.
Also in the status bar notification, the reply icon looks corrupted.
![1](https://user-images.githubusercontent.com/129492114/229061102-d588a329-5b84-4ae5-9b28-ccdbe5834b62.png)
![2](https://user-images.githubusercontent.com/129492114/229061110-94d0bc00-7923-4bd9-8ba6-f6dbed021b20.png)
![3](https://user-images.githubusercontent.com/129492114/229064395-68ea3f81-69d9-4435-a43a-3a397f487f35.png)

**Comment by DeadSecTr** [comment]
Android 6....really?

**Comment by clark-signal** [comment]
Hi thanks for reporting! This should be fixed in 6.17
