### ISSUE TITLE
Request to donate to signal is blocking my view of the app

### ISSUE THREAD

**Issue by vitamins** [signalapp/Signal-Android#12864]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by nicholas-signal** [comment]
Hello @vitamins,

Please fill out the issue template, and include a screenshot if possible.

Thank you.

**Comment by vitamins** [comment]
I haven't done any of these things, the headline should be fairly obvious, i don't participate in needless bureaucracy

**Comment by vitamins** [comment]
I can not provide a screenshot as the window asking for donations does not appear again after i dismissed it. I had to dismiss it as i can not donate using Mobilecoin (the best currency 😂)

**Comment by nicholas-signal** [comment]
On my Samsung A51, I am able to view the app even with the request to donate. 

If you would like a further investigation, please review our bug submission guidelines and submit a new issue: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
