### ISSUE TITLE
Creation of Backup not possible at all

### ISSUE THREAD

**Issue by SignalUser2022** [signalapp/Signal-Android#12877]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I go to the settings of the Signal App and try to create a backup. The file manager opens, telling me I should create a new folder where I can save the backup. I create a new folder and click on the area "Use this folder". After that I get kicked right back to Signal and the automatic backups are still disabled.

I had the same problem using another phone a while ago and opened an issue. 
https://github.com/signalapp/Signal-Android/issues/12062
My old phone broke down and I lost therefore all the content on Signal since I couldn't create a backup. Now I'm using a new phone and the same problem appears again.....
Any help appreciated.

### Steps to reproduce
- Open Signal
- Go to settings
- Enable creation of backups
- File manager opens
- Create new folder
- Click on the button to use this folder as storage for the backup

**Actual result:** No backup is created
**Expected result:** A backup is created

### Device info

**Device:** Samsung Galaxy A52
**Android version:** 12
**Signal version:** 6.15.3

### Link to debug log
I can send that via e-mail, don't want to post it publicly

**Comment by alex-signal** [comment]
Hi, you can send an email straight to support through the app. Please include the github issue number in your email.

**Comment by SignalUser2022** [comment]
I tried to do that, but I cannot add the issue number somehow within the app. I was able to save the log though. Can I send it via e-mail?
Thanks

**Comment by alex-signal** [comment]
@SignalUser2022 Yeah, you can email it to support at signal dot org and include this ticket number :-)

**Comment by SignalUser2022** [comment]
Done :-)

**Comment by greyson-signal** [comment]
Thanks, we got it and will take a look :+1:

**Comment by cody-signal** [comment]
Hi @SignalUser2022 were you also running a flavor of Lineage on your other device? 

I'm adding some additional logging that may help with this in the next beta (6.18.x). When that's available to you, could you install it and try to enable backups again? You can then email the debuglog to me cody@signal.org

**Comment by SignalUser2022** [comment]
Dear Cody,
I'm running a non-modified version of LineageOS on my device, as downloadable from the Lineage website.
How can I get a beta version, since I only get update notifications in the Signal app for stable updates?
Thank you :-)

**Comment by greyson-signal** [comment]
Hi, if you're using the version from our website, you won't be able to get beta updates (maybe one day, but not currently :sweat_smile:). 6.18 will likely be available to you in ~2 weeks.

**Comment by cody-signal** [comment]
@SignalUser2022 this is now available via the website.

**Comment by viddha** [comment]
I recently shifted to a Google Pixel 6 phone and started facing the same issue. Earlier, I used a Oppo F9 phone, and the backups worked absolutely fine. However, now every time I try to select the folder to backup the chats, I get reverted back to the previous screen, backup menu, where the button still reads 'Turn On' (Chat Backups). I went through this issue thread, and I would like to point out that Google Pixel phones have Files by Google as the default file manager app. Furthermore, I was able to save a copy of the debug log onto my phone, which means that there is no issue in supporting the writing of data.

My debug log - https://debuglogs.org/android/6.19.9/83fb2daa96529e5b5b5e32f94c274ef3d4b043b62278881bceaeb3bcb55d671b

Please help. Backing up signal is absolutely important for me.

**Comment by SignalUser2022** [comment]
Wow
I think I found a solution:
@cody-signal After you mentioned the developer option in issue #12062 I disabled the option "Don't keep activities" and now I can save backups in the internal storage
I'm beyond words. Thank you so much for solving the issue 🥇

**Comment by viddha** [comment]
Yes! It worked for me as well! Thank You @cody-signal ! I was super worried about losing my chats.
Appreciate the time and the effort🤟🏼
