### ISSUE TITLE
Microphone remains in-use even when muted in call

### ISSUE THREAD

**Issue by ZLima12** [signalapp/Signal-Android#12870]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a call, pressing the mute button does not cause the microphone in-use indicator to disappear. This is unlike the equivalent behavior for turning video on and off, which correctly releases camera access when video is turned off.

Given Signal's emphasis on privacy, only using the microphone when enabled by the user should be the default behavior.

### Steps to reproduce
- Start a call
- Mute the microphone

**Actual result:** The microphone is still in-use by Signal, as shown in the status bar.
**Expected result:** The microphone icon disappears from the status bar, indicating that Signal is not currently accessing the microphone.

### Device info

**Device:** Google Pixel 7
**Android version:** Android 13
**Signal version:** 6.15.3

**Comment by howdyAnkit** [comment]
Can I get assigned for this ? Would like to check and contribute

**Comment by nicholas-signal** [comment]
We directly use the Android's mute functionality: https://github.com/signalapp/Signal-Android/blob/36a8c4d8ba9fdb62905ecb9a20e3eeba4d2f9022/app/src/main/java/org/thoughtcrime/securesms/webrtc/audio/AudioManagerCompat.java

It is Google's decision to display or not display the indicator when the mic is connected but muted.
