### ISSUE TITLE
[RTL] Conversation panel does not show conversation name

### ISSUE THREAD

**Issue by riastradh** [signalapp/Signal-Android#12874]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the Android system language is set to a right-to-left script, the name of the person or group in a conversation is not shown in the conversation screen.

### Steps to reproduce
- Set Android system language to a right-to-left script, such as Arabic or Hebrew, or, in _Settings -> Developer options_, enable _Force RTL layout direction_.
- Open a conversation in Signal.
- Look at the top of the screen.

**Actual result:** The name of the person or group in the conversation is missing.
**Expected result:** The name of the person or group in the conversation should be displayed.

### Screenshots

Left-to-right English displays the conversation name just fine:

![en](https://user-images.githubusercontent.com/3687362/229873399-8e793ff7-f6d5-4d55-8f5d-3fc58a6c4455.png)

In Arabic the name is missing:

![ar](https://user-images.githubusercontent.com/3687362/229873483-638e305a-ba58-471d-a7e0-d70fa51a53ee.png)

In Hebrew the name is missing too:

![he](https://user-images.githubusercontent.com/3687362/229873555-c84456c2-1aba-49d3-a491-5c2aef7c62de.png)

### Device info

**Device:** Fairphone 3
**Android version:** 11
**Signal version:** 6.15.3

**Comment by alex-signal** [comment]
Hi! this should be fixed in `6.16.2`
