### ISSUE TITLE
Automatic backups get disabled after every update of Signal

### ISSUE THREAD

**Issue by FFDA** [signalapp/Signal-Android#12871]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After every (at least it looks like it, I can't be sure) Signal app update automatic backups get disabled. I keep keys for the backups in password manager and I'll just share the old ones with the dates when they were generated by the app:

> Senas 2020-10-27: 38779 85022 02211 74730 54386 56474
> Senas 2023-02-09: 70958 95098 17718 50847 98657 76262
> Senas 2023-02-10: 75154 52945 99299 69670 32339 94024
> Senas 2023-03-17: 53255 72037 04340 46737 72849 04824
> Senas 2023-03-21: 54198 25518 49927 10027 36907 68562
> Senas 2023-03-26: 47523 05932 73110 98605 38747 35251

I noticed the error in the logs at the time when the app tries to make a backup:
```
04-02 02:00:02.946  3791  3849 E ActivityThread: Failed to find provider info for com.android.externalstorage.documents
04-02 02:00:02.948  3791  3849 E ActivityThread: Failed to find provider info for com.android.externalstorage.documents
```

### Steps to reproduce
- Enabled backups
- Wait for next app update
- Wait for next backup that is done during the night
- Find notification in the morning that backups were disabled

**Actual result:** No backup is made
**Expected result:** A backup created in the middle of the night

### Device info
**Device:** Redmi Note 9 Pro
**Android version:** 12 (xiaomi.eu Rom)
**Signal version:** 6.15.3

### Link to debug log
https://debuglogs.org/android/6.15.3/556c6b3be422ecdf625a87b562fb2632ad947b3f2c59808c487ed24b1446b4bc

**Comment by cody-signal** [comment]
It seems like after every app update the OS does not allow us access to the backup location.

Error on first job after the update:
`java.io.IOException: Cannot write to backup directory location.`

I'm not sure what we can do here, without access we can't write, and we have to prompt UI to request access again hence the notification to help you notice it.

I think the only thing we could do is try to reuse the same backup password if you disable/enable again but that's not a great move either.

**Comment by FFDA** [comment]
So most likely it's a problem with my phone/OS. I think at least one another app has the same problem. It just gets less often updated so it's less noticeable. And I only need reselect the same folder without saving password every time. I guess this issue can be closed without a solution.

**Comment by cody-signal** [comment]
You'll need to save the password each time until/if we make a fix to reuse the old one in this specific situation. Until then, you'll need to record it each time you re-enable backups.

**Comment by ztNFny** [comment]
It seems the SAF access to the backup folder is getting lost on update. I have the same issue here (with multiple but not all apps), after installing an update SAF access is lost and has to be re-granted.
Using OnePlus Android 12.

**Comment by FFDA** [comment]
> It seems the SAF access to the backup folder is getting lost on update. I have the same issue here (with multiple but not all apps), after installing an update SAF access is lost and has to be re-granted.
> Using OnePlus Android 12.

Do you use a custom rom? I think that mine has a bug in it. And that's why it is happening, otherwise a lot more people would complain about this.

**Comment by FFDA** [comment]
I install a new ROM. This time I used LineageOS and the issue disappeared. I guess one of the updates of xiaomi.eu (or even stock Xiaomi ROM that it was based off) introduced it.

Closing the issue.
