### ISSUE TITLE
FEATURE REQUEST: Upload manually on cell/restricted internet

### ISSUE THREAD

**Issue by trytomakeyouprivate** [signalapp/Signal-Android#12889]
Internet saving features for download are awesome.

But similar to the "send later" feature, you might want to send images, but only when you are on Wifi again.

Adding an opt-in feature to handle uploads for all the media types exactly like downloads (one switch could be enough) would be really helpful.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
