### ISSUE TITLE
Emoji domains shows up as normal text instead of links

### ISSUE THREAD

**Issue by OlofHaglund** [signalapp/Signal-Android#12885]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji domains do not show up as a click able link. 

### Steps to reproduce
- Open up a chat in Signal.
- Send an link where the domain contains an emoji.
- Try to click the link.

**Actual result:** The link is display and behaves as normal text.
**Expected result:** The link displays and behaves as a link.

### Device info

**Device:** Nokia 8.3
**Android version:** 12
**Signal version:** 6.15.3

**Comment by alex-signal** [comment]
Could you give an example  of an emoji domain?

**Comment by maurerle** [comment]
Hi @alex-signal, this is still the case for any Internationalized Domain Name (IDN).

Any hyperlink to a domain containing special characters, like  `http://türkiye.com` does not get rendered as link in signal android. The domain gets punnycoded to `http://xn--trkiye-3ya.com/`.
On Android and iOS, it works to then send a clickable link to the punnycode variant

However, the folks at signal-desktop decided to not render the DNI/Punnycode domain:
https://github.com/signalapp/Signal-Desktop/issues/3966#issuecomment-928192521

So if you want to link to a IDN domain, you have to use punnycode variant for mobile and the actual link on desktop.
This is quite a bad current situation.

I would prefer if the mobile clients behave as on the desktop or supports both variants.

Can you reopen this issue please?
