### ISSUE TITLE
whitespaces at the end of a full line should not get compressed, they are too hard to spot

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12882]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Type a whitespace at the end of a full line and wonder if you missed it, if it did not register. Backspace a written text and get confused when the line jumps back too early while the whitespace appears to be gone but if you look closely is still there. It's confusing, would be better to jump the whole word to the next line and print the whitespace properly.

### Screenshots
![Screenshot_20230407-185754](https://user-images.githubusercontent.com/34976212/230649356-0f29faa5-65ab-408c-bc8c-eae313cdf4ec.png)
Compressed whitespace

![Screenshot_20230407-185702](https://user-images.githubusercontent.com/34976212/230649358-e85b130b-fbbf-4842-b7b8-8aaf607caf98.png)
No whitespace

![Screenshot_20230407-185842](https://user-images.githubusercontent.com/34976212/230649351-3e75af0a-d6fe-4313-ae69-6d1ca366e362.png)
Normal whitespace

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 6.17.1

**Comment by alex-signal** [comment]
This appears to be a limitation with `EditText`. The same thing happens in say, Google Messages.

**Comment by Meteor0id** [comment]
It is still an issue, still makes reading difficult, still worth keeping open, still hoping someone will forward it to the right developer
