### ISSUE TITLE
Missing received image and the same shared further

### ISSUE THREAD

**Issue by krwow** [signalapp/Signal-Android#12884]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have received a message from person A, it was an image and some text in the same message. I replied just the image to person B. I had been able to see images in both chats for some time both on Android and Windows app. After some thumbnail of image changed to gallery icon with warning icon in my chat with person A and person B on Android device. And opening image results in seeing black image with some Signal options. I cannot it share it (after trying it just gets back to chat screen with this image) neither reply to it (after sending reply nothing new appears in chat). What's more, I can still view it on PC and it is visible on person A device, but it's also not visible on person B device.

### Steps to reproduce
It's hard to say that there's a known way to reproduce that...
- Get message with image and text on Android.
- Have Windows app connected.
- Wait for some time and see that every occurence of this image is missing in Android app.

**Actual result:** Thumbnail is a gallery icon with warning icon, image after opening is just black.
**Expected result:** Seeing proper thumbnail in chat and proper image after opening it.

### Screenshots

Received message:
<img src="https://user-images.githubusercontent.com/65966603/230725888-d692728e-cbd5-4193-a962-c96083fc649f.png" width="300" height="170">

Shared further message:
<img src="https://user-images.githubusercontent.com/65966603/230725903-f606274e-e438-44a1-9d69-b6acd8623c6a.png" width="300" height="85">

### Device info

**Android version:** 13
**Signal version:** 6.16.2 (log is from that version, but bug was found in older one)

**Comment by alex-signal** [comment]
Hi! I don't see anything obvious in the logs further than the image can't be loaded. It appears that the underlying file got deleted at some point but I can't see if it was during the period your logs were for. Did this pop up after the shared message was sent? Or was it a while after that? I'm wondering if we somehow messed something up during the copy pipeline that would've resulted in deletion somehow...

**Comment by alex-signal** [comment]
Try deleting the failed messages off your android device and then send it from the PC again. It's likely seeing it as a duplicate and refusing to write it to disk.

**Comment by krwow** [comment]
Thanks, that worked. I might have checked that by removing image from just one chat on mobile, but I removed it every occurrence on mobile, send it from PC as new message and now it is visible on Android device as well.

So having linked device helped this time.
