### ISSUE TITLE
Cannot send one particular gif to anyone (just in this app) 

### ISSUE THREAD

**Issue by krwow** [signalapp/Signal-Android#12886]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to send one particular gif using Signal on Android, but I cannot send it no matter what recepient is, no matter the way I'm trying to send it. I suspect it might be its size - it's 1680 x 980 pixels, 30 fps and it is 1 minute 16 seconds long, weighting 3.66 MB. I always get, translating it roughly, "Message could not have been sent. Check connection with Internet and try again" (pop-up window or after taping on status of message in chat) or "It wasn't possible to deliver the message - Delivering message wasn't successful" (as notification with red warning triangle). I can preview gif in chat on my device, but there's an exclamation mark next to message status and "Sending wasn't successful" instead of time of sending message and I cannot open it fullscreen. I have already checked out many possibilies - choosing gif from last images, from "Gallery" icon, sharing from Google Photos, using various options - full size, default size or one-time mode. It's always the same. I can still remove gif in everyone's chat or just myself. Exclamation mark is visible in chat list when this gif is last message. Choosing "Retry" to send it again doesn't help either.

I tried sending it by other apps - in Messenger by Meta (E2EE chat) autoplaying thumbnail in loop causes app stuttering and chat with this gif is lagging, that's why I assume the reason of all this is its size (partial success), but in Session it works just well, maybe it is compressed in different way.

### Steps to reproduce
Again not so easy to reproduce...
- take the biggest gif (filesize, gif length, size in pixels) you have
- send it to someone
- hope there will be bug and it won't be sent 

**Actual result:** Gif not sent.
**Expected result:** Gif sent.

### Screenshots

<img src="https://user-images.githubusercontent.com/65966603/230729427-15fff5b4-0b08-4397-93f1-e3368687f7c7.png" width="300" height="55">

### Device info

**Android version:** 13
**Signal version:** 6.16.2 (it was present in previous versions as well)

**Comment by alex-signal** [comment]
"org.thoughtcrime.securesms.transport.UndeliverableMessageException: Size constraints could not be met!"

It looks maybe like the gif you're trying to send is too large, yeah. That is a giant gif. In *my* ideal world we'd  transcode it into an MP4 but here we are.

I'll bring this up with the team.

**Comment by alex-signal** [comment]
We use JPG to compress images. The same compression won't work for GIFs. GIF is a really awful file format. We'll take a look at what we can do here.
