### ISSUE TITLE
show ellipsis on status if it does not fit

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12895]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20230413-142641](https://user-images.githubusercontent.com/34976212/231757849-5fee0745-09b8-44e1-a459-080a9f7b5ce8.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Sgn-32** [comment]
android:ellipsize="end" is already set in the xml-file

https://github.com/signalapp/Signal-Android/blob/e33a68b203dc8bdfb576ca35d02119a4fd45ce1c/app/src/main/res/layout/bio_preference_item.xml#L58-L59

Changed this to
```
 android:ellipsize="marquee"
 android:singleLine="true"
```

and it works.

![Screenshot_1681634571](https://user-images.githubusercontent.com/49990901/232287622-d9e18d49-0361-460f-bf72-2633d18abe00.png)
