### ISSUE TITLE
Switching app durring the restore backup dialog triggers confusing behaviour

### ISSUE THREAD

**Issue by cwammerl** [signalapp/Signal-Android#12891]
-  I have searched open and closed issues for duplicates
-  I am submitting a bug report for existing functionality that does not work as intended
-  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
-  This isn't a feature request or a discussion topic

**Bug description**
During the process of restoring a backup.
When switching to another app during the dialog to enter the passphrase of the backup

**Steps to reproduce**
Open a clean Signal
Press the button to restore you previously created backup 
Select the backup and press restore
With the dialog up change into another app, E.g. your bitwarden app that holds the passphrase.
Switch back into the Signal app

Actual result: Signal will imideatly greet you with a "backup successully restored" dialog without even entering the key or procesisng anything

Expected result: The dialog to enter the passphrase should still be up and allow me to procced with the restoring process.

Device info
Device: Pixel 4a - Clean install

Android version: Android 13

Signal version: 6.16.2

**Comment by nicholas-signal** [comment]
I am not able to reproduce this issue.

https://github.com/signalapp/Signal-Android/assets/112583042/93bfdbba-fe23-48b7-b5af-c45ab016ad17

Did I follow the repro steps properly?

**Comment by cwammerl** [comment]
Yes, looks good. I guess it was a one off then on my device.
Thanks for checking
