### ISSUE TITLE
Smartwatch still shows up as a bluetooth option

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12899]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This commit was supposed to prevent smart watches from being an option when selecting an audio source. https://github.com/signalapp/Signal-Android/commit/ed67e7ac04e76f0a9c07ef65a65d31ddd9fc5faa

But it doesn't seem to work at all times. 

### Steps to reproduce
- start a call with both your ear buds and smart watch connected. The ear buds will be the only choice.
- during the call put your headphones back in the case, which will disconnect them. 

**Actual result:** The Bluetooth source will switch to your smart watch, even though it wasn't originally on the list.
**Expected result:** After disconnecting it should switch back to your speaker. 

### Screenshots

![image](https://user-images.githubusercontent.com/18274896/231918325-ae371171-fdf1-4836-a68e-811285a00c9c.jpeg)

### Device info

**Device:** Pixel 7
**Android version:** 13
**Signal version:** 6.17.3

### Link to debug log

https://debuglogs.org/android/6.17.3/844e3b95dbaa3d2b42ffc1f79f93a760a09d2b6ab9ce3d52d8291e4904a4b1e2

**Comment by nicholas-signal** [comment]
Hello,

The way this works is Signal asks the operating system for a list of the "available communication devices" inputs/outputs: https://github.com/signalapp/Signal-Android/blob/e2ade166ece367dda0002957c5af5e4d36b4ec25/app/src/main/java/org/thoughtcrime/securesms/webrtc/audio/FullSignalAudioManagerApi31.kt#L168

The operating system will only surface the "main" connected Bluetooth device into this list. In my experience, it usually does a pretty good job of determining which device is actually desired: earbuds over watch, for example. It seems like it prioritizes the devices well for you, too!

If you want the system to never present the watch as an option for calls, you can disable it in the operating system settings. Here's how it looks on my Galaxy A51:

https://user-images.githubusercontent.com/112583042/233704111-a81bdd19-e7d3-4a9b-be71-096222168743.mp4

Now, why don't we do this automatically? I've searched and searched for a good way, post-SDK 31, to reliably determine if a Bluetooth device is or is not a smartwatch without requiring the `android.permission.BLUETOOTH_CONNECT` but have come up empty-handed.

Please let me know if disabling the watch for calls in your system settings solves your issue!

**Comment by Tursko** [comment]
Im fine with it presenting the watch as an option, but it's odd that when I disconnect my headphones it switches to my watch. I would expect it to switch to my speaker and stay that way until I choose another Bluetooth device. 

I've seen this same experience with normal phone calls though and I'm not sure if y'all have any control over it.

**Comment by nicholas-signal** [comment]
> I've seen this same experience with normal phone calls though and I'm not sure if y'all have any control over it.

Exactly: the operating system chooses which single connected Bluetooth device to present to apps as an audio input/output. I'm afraid you're at your OS's mercy when it comes to choosing that one device among your multiple connected Bluetooth devices.

I'm going to close this issue, given that the ball is your OEM's court. (Google, in your case)

**Comment by Tursko** [comment]
Thanks for all the info! Hopefully Google can improve their device switching process.
