### ISSUE TITLE
Unable to change custom message notification after setting it for the first time

### ISSUE THREAD

**Issue by grendello** [signalapp/Signal-Android#12893]
This happens on Android 12

The issue is similar to [this one](https://github.com/signalapp/Signal-Android/issues/12869), in external behavior, but not in the internal cause of it.
In my case, after restoring Signal backup on a new phone, I was able to select a custom message notification sound for a conversation (user), but (despite
the sound file being available and still accessible when e.g. changing the default message notification sound for the device), the Signal conversation
falls back to the default device tone, and I can no longer modify the conversation tone.  Looking at the logcat output, each time I try to change the message
notification tone, I see this:

```
W MediaProvider: Trouble resolving content://media/external/audio/media/806; falling back to search: java.io.FileNotFoundException: No item at content://media/external/audio/media/806
W MediaProvider: Trouble resolving content://media/external/audio/media/806; falling back to search: java.io.FileNotFoundException: No item at content://media/external/audio/media/806
W MediaProvider: Trouble resolving content://media/external/audio/media/806; falling back to search: java.io.FileNotFoundException: No item at content://media/external/audio/media/806
```

The only messages logged by Signal itself (or related to its PID) around that time are

```
D NotificationChannels: ensureCustomChannelConsistency()
D NuPlayerDriver: NuPlayerDriver(0xf2d00470) created, clientPid(8294)
D Ringtone: Successfully created local player
D NuPlayerDriver: NuPlayerDriver(0xf2d01d70) created, clientPid(8294)
D Ringtone: Successfully created local player
```

I **suspect** it's an Android/MediaProvider bug, since it was what initially provided that URL to Signal, but I found no way to reset the notification for that conversation.  Even attempting to clear it from the phone
Settings app (via Notifications -> App Settings -> Signal -> [My Conversation]) results in the same error.

Is there a way to reset the stored notification URL so that I can set a new tone for the conversation?

**Comment by clark-signal** [comment]
Hello, from what I understand you're taken to the system settings to configure the notification for a conversation with a user? I believe on API 30+ we let the system handle the notification settings via the settings per channel.

Do you know what device you're using?

**Comment by grendello** [comment]
Hey @clark-signal, yes, when it works I'm taken to the system settings to configure the notification channel.  I had it fail on a Pixel 3XL (Calyx OS 4.9.0), Motorola G71 5g (Android 12) and Nokia G60 5G (Android 12 as well). The Nokia recently got an update to Android 13 and since then I haven't seen the issue there.

**Comment by clark-signal** [comment]
Thanks for the additional context! I'll try to see what we can do, but given that the OS update fixed it for your Nokia and that we let the system handle the customization, I suspect it's an Android bug as well :/
