### ISSUE TITLE
app crashes when switching away from call

### ISSUE THREAD

**Issue by jthall** [signalapp/Signal-Android#12896]
I have searched all open and closed issues for duplicates.
I am submitting a bug report for existing functionality that does not work as intended.
I have read submitting useful bug reports.
This isn't a feature request or discussion topic.

bug description:
When using Signal 6.17.3 and earlier, when on the call screen of an active audio or video call, switching away from the active call to do something else, like pressing the home button, causes the app to crash. The call continues until you select restart app. A log showing this is here:

https://debuglogs.org/android/6.17.3/a7203e5b66a755cdfe5c67c43f94301a6c551a61644ce6de8ab18191cb8a4b8a

When using 6.18.0, simply attempting to start a call yields a crash--the two may be related. The call does not have ringing sound but will connect if the other person answers.

https://debuglogs.org/android/6.18.0/f99d8c9bde5f55784a0c2b273b91044667e8b9991b4ff4684bfce24e17b7fd9f

How to reproduce:

1: Open the signal app and make an audio or video call.

2: Press home button either while it is ringing or when the person has answered.

actual results:
The app crashes.

expected results:
The app does not crash

device info: Samsung S7 Active (ATT) 8.0.0

**Comment by Max-Stirner-Signal** [comment]
Thanks for also writing into support@. We'll get back to you via that channel.
