### ISSUE TITLE
Backups run immediately on phone start, regardless of charging state

### ISSUE THREAD

**Issue by creideiki** [signalapp/Signal-Android#12907]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Until a week or two ago, scheduled backups only ran when I connected my phone to a charger. Since then, backups start immediately when the phone starts, regardless of charging state.

This is annoying because it means the phone is unusably slow for the first half hour after turning on, when I turned it on because I wanted to use it right then.

### Steps to reproduce
- Activate scheduled backups.
- Disconnect any charger and turn the phone off.
- Let the phone sit powered down overnight.
- Turn the phone on without connecting any charger.

**Actual result:** Scheduled backup starts immediately.
**Expected result:** Scheduled backup should not start until I connect a charger.

### Device info

**Device:** Motorola Moto G5 Plus (XT1685)
**Android version:** LineageOS 18.1 (Android 11)
**Signal version:** 6.17.3

### Link to debug log

https://debuglogs.org/android/6.17.3/593380f5812bc810524adff02837afbe982f19c2f7fefebb4786fa26f437c226

**Comment by cody-signal** [comment]
Having two conditions is tough to reconcile in a predictable way, so we dropped the charging constraint for scheduling.

What is your expectation for reconciling the two? If you have a schedule for say 2am, but the charger isn't connected. Should it run then? If it waits until the charger, then it's not really scheduled anymore.

If your use case is to turn your phone off at night, in the short term, I'd recommend setting a different schedule if you know the phone will be off.

**Comment by creideiki** [comment]
I had not noticed that the charger constraint had been dropped, or that I could change backup times manually now. It was set to 0200, but I changed it to the evening instead, which suits my use better.

Otherwise, I would have expected the backup to run when both time and charger conditions were fulfilled simultaneously. EITHER (at least 24h have passed since the last backup AND the charger is plugged in) OR (skip this run and wait until the next scheduled time AND then check if the charger is plugged in). The first of these was the impression I had gotten from the previous behaviour. The current behaviour accepts a delay of several hours because the clock stopped while the device was powered down, but not a delay of several hours because the charger wasn't plugged in, which seems inconsistent in my mental model.

In general, I would prefer as little as possible to happen right after boot. That time is already filled with a cacophony of alerts and errors, e.g. Signal messages already read on a desktop client (#8445), errors from ill-behaved synchronization apps which are unable to wait for the VPN to come up and thus complain about not being able to reach their servers, and media player apps wanting to scan their libraries in case they have changed. Starting a long-running backup process which saturates I/O to the SD card at the same time does not improve the situation.
