### ISSUE TITLE
"CANCEL" not working on Registration Lock

### ISSUE THREAD

**Issue by glasszay** [signalapp/Signal-Android#12909]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Registration Lock `CANCEL` button not working on confirmation. 

### Steps to reproduce

- Go to Settings>Account>Registration Lock
- Toggle on/off Registration Lock
- Tap `CANCEL`

**Actual result:** Toggles on/off even though action was cancelled.
**Expected result:** Registration Lock's `true/false` value stays the same when user clicks `CANCEL`.

### Screenshots

![Signal](https://user-images.githubusercontent.com/76571965/233173610-aceee26a-6db9-41bf-8476-55dc3019cce3.jpeg)

### Device info

**Android version:** 10
**Signal version:** 6.18.3

**Comment by cody-signal** [comment]
This looks like a UI state problem. If you cancel and then leave the screen and return does the switch show the correct state? For me, the UI always changes when I tap, but the actual enable/disable of reglock doesn't.

**Comment by cody-signal** [comment]
@siva-subramaniam-v appreciate the request, but we'll take this one and fix it today.

**Comment by siva-subramaniam-v** [comment]
@cody-signal  Alright. Can you point me to issues you guys need help with? I mean issues you guys at Signal wouldn't prioritize to work with, but still need a fix.

**Comment by glasszay** [comment]
I'm no longer experiencing this issue, didn't see any commit on this issue, can I close it?

**Comment by nicholas-signal** [comment]
> I'm no longer experiencing this issue, didn't see any commit on this issue, can I close it?

Glad to hear the issue is fixed for you! Don't worry, I got it.
