### ISSUE TITLE
USB-C headphones not getting recognized on calls and the call audio is coming though the phone front speaker

### ISSUE THREAD

**Issue by Adi-Shuji** [signalapp/Signal-Android#12906]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As the title says on calls the audio is not coming though the usb-c headphones when connected inside it still comes form the front speaker of the phone. There is no problem with the usb-headphones as it works in all other apps. The audio comes correctly if I switch to a bluetooth headset.

### Steps to reproduce
- Call someone or get a call on Signal
- connect usb-c earphones 
- answer the call

**Actual result:** Call audio comes from the front speaker of the phone instead of the usb-c headphones.
**Expected result:** When usb-c earphones are connected it should get recognized and automatically the call audio should get switched over to the headphones. 

### Device info

**Device:** samsung SM-G986W
**Android version:** 13
**Signal version:** 6.17.3

### Link to debug log

https://debuglogs.org/android/6.17.3/9d7262a90b7f9fb8d1de5b19704c8e917cf8d15a873cdc96b0c8241d55228c5e

**Comment by cody-signal** [comment]
Hi @Adi-Shuji are you able to switch to them manually or do they not work at all?

Auto-switching and flat not switch-to-ablle are two separate problems so it would be helpful to know which you encounter.

**Comment by ellisonch** [comment]
This just started happening to me today as well, but I'm using normal wired 3.5mm-jack headphones.  When I call, or receive a call, on signal, the other person's voice defaults to coming out of my speakers.  I have to select the button and change it to come out of my headphones.  I'm on signal 6.17.3 on android 12.  I can't figure out how make this change stick either.  I have to set it back for every call.

Other programs are play audio into my headphones.  Signal is the only one that isn't.

**Comment by cody-signal** [comment]
Thanks for the details @ellisonch, that helps confirm the fix we put out in 6.18.3 (just started prod rollout today) will likely fix this issue for you.

**Comment by HaseebAhmed-2624** [comment]
I'm getting this issue in my mobile with following specifications any updates on the resolution then please let me know
Device : Samsung A06
One UI version : 7
Android version : 15
Already tried enabling and disabling disable usb audio routing about
The audio is working fine with apps other than VOIP
Let me know if there is anyother method of resolution
