### ISSUE TITLE
search broken post-transfer

### ISSUE THREAD

**Issue by antgeth** [signalapp/Signal-Android#12902]
- [x] I have searched open and closed issues for duplicates _`(Well, I tried. Searching for "search" is tricky as every bug report has this checklist in it.)`_
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After account transfer to new device, chat history, while present, is not searchable. Kind of a big problem as my mobile device is the only complete repository of my messaging history.

### Steps to reproduce
- Transfer signal account from old phone to new phone.
- Attempt to search messages for any term that you know will turn up a result (as verified by searching on an instance of Signal Desktop).

**Actual result:** No results dating to before the transfer.
**Expected result:** All the times you said the word "delectable".

### Device info
**Device:** Moto Z4
**Android version:** 10 [QPFS30.130-15-11-23]
**Signal version:** 6.17.3

### Link to debug log
https://debuglogs.org/android/6.17.3/f79a8b68de1e90e2963e07f69c5d3dddb68b201beba4b6d9cc4eae40fd2db58d

**Comment by antgeth** [comment]
so, is this fixed? if i update will i be able to search my messages again?

**Comment by cody-signal** [comment]
Appears the fix is in 6.18.2 which is in beta and should start a prod roll out today.

**Comment by antgeth** [comment]
just updated to 6.18.4 and search works again. thank you!
