### ISSUE TITLE
Signal backup not working

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#12915]
### Bug description
Since I installed signal it keeps saying that backup could not be created and verified

### Steps to reproduce
settings>chats>backup>create backup+ backup could not be created or verified.

### Screenshots
![Screenshot_20230422_204650_Bromite](https://user-images.githubusercontent.com/131549493/233801883-2c625ebc-1e2f-4355-bc15-7180fba7cd6a.jpg)

### Device info

**Device:** Samsung s20 FE
**Android version:** Android 13
**Signal version:** 6.18.4

### Link to debug log
->https://debuglogs.org/android/6.18.4/bd780b00de569198fbcafc4bd4f36d138744610dc8e1ad4f9a2dc43e5cc321d4

**Comment by cody-signal** [comment]
The OS is reporting that the backup file we created cannot be read for security reasons (as if we don't have permission to access the location).

Have you selected the Downloads folder or some other default folder?

**Comment by user1234579** [comment]
I have created a folder called "signal"

**Comment by DaveSaah** [comment]
Having a similar issue 👍

**Comment by cody-signal** [comment]
@DaveSaah  Could you provide a debuglog?

**Comment by DaveSaah** [comment]
https://gist.github.com/DaveSaah/e09db2c247de1ad0b8adb269c456234f

**Comment by DaveSaah** [comment]
> @DaveSaah Could you provide a debuglog?

https://gist.github.com/DaveSaah/e09db2c247de1ad0b8adb269c456234f

**Comment by cody-signal** [comment]
Thanks. I was hoping for one of our debuglogs from the app:

Settings->Help->Debuglog->Submit :)

**Comment by DaveSaah** [comment]
> Thanks. I was hoping for one of our debuglogs from the app:
> 
> Settings->Help->Debuglog->Submit :)

Sorry, my bad 🥲. 
https://debuglogs.org/android/6.19.8/4859f2aa93027adfde1761659d010aa3fa5ee55a03bf0aaa39c7af39b5e98acd

**Comment by dereksnow** [comment]
Same issue.
Samsung S20+
Android 13

Any updates on this issue?

https://debuglogs.org/android/6.21.3/c200740ddb4215a97c04dbd2d69c7eca728028449572da8637d3fb35d3fc9e82

**Comment by dereksnow** [comment]
I haven't manually disabled any permissions for Signal and when I go to the app permissions under "Not allowed" it reads "No permissions denied"... But it also doesn't explicitly list being able to write to storage under "Allowed". I'm unsure how to give storage permissions to Signal. It seems Samsung may have changed how this is performed. I will see what disabling and re-enabling backups does and selecting a different location.

**Comment by dereksnow** [comment]
I'm still having the same issue after disabling and re-enabling backups. I just used the Signal folder that I created this time /storage/emulated/0/Signal

How would I go about giving com.android.externalstorage the permissions it needs? It seems this would be done/verified by Signal when backups are initially enabled.

**Comment by Paulchen232** [comment]
It now Backup possible?

**Comment by dereksnow** [comment]
Yes, backup was successful. 👍

**Comment by Paulchen232** [comment]
My Mother have an Samsung have a SAMSUNG Galaxy A53 with the same Error. But it Work Not.

**Comment by Paulchen232** [comment]
Signal 6.21.3

**Comment by Paulchen232** [comment]
Have you a external Storage in.

**Comment by Paulchen232** [comment]
@DaveSaah 
`Update: I had "External Storage" disabled for All file access. I will test again.`
Have you then neu Enabled the Chat Backups? Use than Signal in App-Info the internal storage?
Exist an external storage in your phone?

**Comment by dereksnow** [comment]
> @dereksnow Have you a external Storage in.

I'm not using any external storage. You should post a debug log and see if someone can help.

**Comment by DaveSaah** [comment]
> 

I do not have an external storage.

**Comment by Paulchen232** [comment]
@dereksnow 
Thank you for your ansers. What for Cellphone have you,? The Cellphone my Mother ist Samsung A53.

**Comment by Paulchen232** [comment]
@dereksnow 
You have Samsung S20+, I have now see it. 🙂

**Comment by Paulchen232** [comment]
Search:
Unable to find backup file, attempt:

**Comment by Paulchen232** [comment]
Kann you @alex-signal or you @cody-signal help my.

**Comment by Paulchen232** [comment]
@DaveSaah 
Did you wipe the cache partition before?

**Comment by Paulchen232** [comment]
@DaveSaah
I would like to know if you use the  /storage/emulated/0/Signal folder?

**Comment by greyson-signal** [comment]
@Paulchen232 Looks like you're hitting a similar error:

```
 java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000005586
```

Are you writing to an external sd card? Can you write to internal phone storage instead?

**Comment by DaveSaah** [comment]
> @DaveSaah I would like to know if you use the /storage/emulated/0/Signal folder?

Yes

**Comment by DaveSaah** [comment]
> @DaveSaah Did you wipe the cache partition before?

I wipe my cache most of the time 🙂

**Comment by clauz9** [comment]
> Update: I had "External Storage" disabled for All file access. I will test again. https://github.com/signalapp/Signal-Android/issues/12915#issuecomment-1576984806


So @dereksnow  is referring to the  "All files access" special access permission...

that you can find by going to  `Settings -> Apps -> 3 dot menu ( in the top right) -> special access -> all files access` 

then you should find in that list of apps, `External Storage` and see if the toggle is enabled.

I just unchecked it, and it made Signal back-ups fail... @Paulchen232 can you verify that you have that toggled on ? 

 <details> 

<summary>Screenshot</summary> 

![image](https://github.com/signalapp/Signal-Android/assets/77681918/a6cfb38c-0205-4348-baf5-cff305d4bd6f)

</details>



Signal is currently not in that list of apps, they probably should be, I've seen apps, ask you for that specific permission and open the `All files access` list of apps, and highlight themselves so you know what to toggle on... 

Unless there's a better approach... 🤔 🤷‍♂️

**Comment by MartinX3** [comment]
I disabled and enabled the backup feature for my custom backup folder on my sdcard

The first backup worked.
But then I get the same error again.

https://debuglogs.org/android/6.24.4/d2ee7b361d4c7a029287a32bc8f6383917721f7dde67d87f57ad6a73cff5629b

**Comment by Paulchen232** [comment]
@MartinX3 
Are you from Germany?

**Comment by MartinX3** [comment]
@Paulchen232
But that shouldn't case the issue.

**Comment by Paulchen232** [comment]
Is not the same error. In my issue it was the External Storage in the All files access list that was off.

**Comment by MartinX3** [comment]
That's a deprecated feature.
Nowadays Signal asks for permission for a specific folder which also works.
So it is normal if Signal is not in the app permission list of external full storage access permissions.

**Comment by MartinX3** [comment]
If you need this then your Android is too old.
My Android 13 doesn't need it for the backup feature.

**Comment by Paulchen232** [comment]
My mother have Android 13 (Samsung A53) and for shy must it on have.

**Comment by MartinX3** [comment]
Then she doesn't need it either.
Except samsung broke its "custom rom".

**Comment by Paulchen232** [comment]
Is that: Settings -> Apps -> 3 dot menu (in the top right) -> special access -> all files access
the same way with you? 
If Englisch: "External Storage" off for you?

**Comment by MartinX3** [comment]
It's `Settings -> Apps -> Special App-Access -> Access to all files` here.
And of course Signal is not listed for me, because it recognized that my android version supports the scoped storage feature.
So it asked for the folder permission inside the signal app while choosing the backup folder.

**Comment by clauz9** [comment]
> Ah, sorry.
> I thought you mean the external storage permission of signal.
> Yes, the system app `External storage` already has allowed access by default.

Yeah Signal also needs to have the "External Storage" permission.. 

check "app info"

**Comment by MartinX3** [comment]
> > Ah, sorry.
> > I thought you mean the external storage permission of signal.
> > Yes, the system app `External storage` already has allowed access by default.
> 
> Yeah Signal also needs to have the "External Storage" permission.. 
> 
> check "app info" 
> 
> <details>
> 
> <summary> Screenshot </summary> 
> 
> ![image](https://github.com/signalapp/Signal-Android/assets/77681918/5d48fd66-1f60-464d-baea-aa2c28fc22f6)
> 
> </details> 
> 
> 

No, it doesn't.
I already explained why...

![Screenshot_20230711-121648_Berechtigungssteuerung.png](https://github.com/signalapp/Signal-Android/assets/4518092/e75e1ea3-350f-4ba3-b434-97ca4b46382f)

![Screenshot_20230711-121655_Berechtigungssteuerung.png](https://github.com/signalapp/Signal-Android/assets/4518092/05c8ac9f-0072-4877-96a8-cc29713de1a7)

**Comment by clauz9** [comment]
> check "app info"

Sorry, it's `app info -> storage` 

see the screenshot.

**Comment by MartinX3** [comment]
> 
> > check "app info"
> 
> Sorry, it's `app info -> storage` 
> 
> see the screenshot. 
> 
> 

There is only the scoped storage permission i explained earlier.
Signal doesn't want a permission for the entire external storage in newer android versions.

![Screenshot_20230711-122643_Einstellungen.png](https://github.com/signalapp/Signal-Android/assets/4518092/531e5f22-28d3-40c5-bf0c-0b980baa4eca)

**Comment by clauz9** [comment]
hmm... that's strange 🤔  

> I suspect some kind of media attachment is causing this issue.

you're probably right about this 🤔  the question is, can we determine what attachment that is from the id we got there 🤔

**Comment by MartinX3** [comment]
> hmm... that's strange thinking
> 
> > I suspect some kind of media attachment is causing this issue.
> 
> you're probably right about this thinking the question is, can we determine what attachment that is from the id we got there thinking

xD

Yes, luckily.
The `id` is a unix timestamp.
The `len` is the size in bytes.

As a normal user you can list all the media in Signal and delete the "broken" entries.

But I wonder why they are broken if I can open these file and watch their contents just fine.

Or maybe the backup service should ask me if I want to delete them (and show me which ones would get deleted).

**Comment by clauz9** [comment]
The strange part, there's no insert point for that Attachment ID in the log... 

https://github.com/signalapp/Signal-Android/blob/5fbf0a98b9896960bf6e7859ca498b91c0c542ca/app/src/main/java/org/thoughtcrime/securesms/database/AttachmentTable.java#L822

So I'm thinking the attachment might not even exist...

**Comment by MartinX3** [comment]
You can convert the id to a human readable format here:
https://www.unixtimestamp.com/

**Comment by clauz9** [comment]
> Each backup try shows a different attachment id and length.
Can you remember if the verification process fails immediatetly, or does it fail after some progress ?

**Comment by MartinX3** [comment]
> > Each backup try shows a different attachment id and length.
> 
> 
> Can you remember if the verification process fails immediatetly, or does it fail after some progress ? 
> 
> Also can you walk me thru what you did, step by step ? maybe I can reproduce the issue on my end, and attach a debugger...

Yes, between 70-80% if i remember correctly.

I just activate the backup or it automatically runs.

You would need my chat history including media between different people.
(Photos, videos, gifs, website previews)

**Comment by clauz9** [comment]
If you are on the beta version of signal, try version 6.26.0 and see If that fixez your back-up issues, there are quite a few changes to the back-up proces in this version...

**Comment by MartinX3** [comment]
> If you are on the beta version of signal, try version 6.26.0 and see If that fixez your back-up issues, there are quite a few changes to the back-up proces in this version...

Using the Beta 6.26.2 and the backup file verification process still aborts at around ~74%.

But it is weird to that always the first backup works if I generate a new backup password.

https://debuglogs.org/android/6.26.2/ecb249c7c992757934b40144b5835b655212ee7e6bbd048d3c0165bf252e6414

**Comment by Leo84-leo** [comment]
I have the same issue. Backup cannot be created and verified:

https://debuglogs.org/android/6.28.6/9ba230b477b79ae63ced140a3727e08fee87c3e9ba2f65af006b859b64a01f5a

**Comment by cody-signal** [comment]
@MartinX3 - Can you confirm you have enough free storage space on your device? And determine if your backup is larger than 4gb and you are running a fat-based storage format?

@Leo84-leo - Yours looks permission related, we write the backup and then when we ask the system to read it to rename/verify the system denies us. Can you pick a new location to store the backup?

**Comment by MartinX3** [comment]
@cody-signal Thank you.
The sd-card was almost full.

It would be nice if signal would give me a "storage full" error message.

Also get old backups automatically deleted?
I manually removed old backup files.

**Comment by Leo84-leo** [comment]
@cody-signal that worked - thanks!!!

**Comment by cody-signal** [comment]
@MartinX3  I wish we could too, but as you can see, it's not something that's obvious in the error message and Android really doesn't like giving out system information with request bonkers permissions. But I agree, we could do better here and I'll make a ticket.

@Leo84-leo 🎉
