### ISSUE TITLE
Signal not showing phone number or safety number

### ISSUE THREAD

**Issue by gitkodada** [signalapp/Signal-Android#12910]
- [ Yes] I have searched open and closed issues for duplicates
- [ Yes] I am submitting a bug report for existing functionality that does not work as intended
- [ Yes] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ Yes] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All the recent contact that have been adding me  signal doesn't appear to display their phone number. We do exchange messages and calls normally, but no phone number is shown for each contact, the name of the contact shows but no number. Its like i am typing with a ghost :DD 
When i try to verify the contact safety numbers it says "You must first exchange messages in order to view the safety number", which i already have (both call and message)
I am not sure if the two issues are related.

### Steps to reproduce
I try to save a new contact's number or verify the safety numbers.

**Actual result:** No number is shown under the name of the contact, and safety numbers cannot be verified since Signal thinks no messages have been exchanged, but actually there have been messages and phone calls exchanged.

### Device info

**Device:** Google Pixel 7
**Android version:** newest
**Signal version:** 0.0.0

**Comment by gitkodada** [comment]
> Can you share a debuglog please?

https://debuglogs.org/android/6.17.3/333098fbe96e4fe290e56ffe6c18ef70f5f0aec21a03b912de788bdf2aa58a8d

**Comment by gitkodada** [comment]
> You have exchanged messages on Signal and this still occurs? This should happen if you try to view their safety number prior to responding to their initial message, but should resolve after sending them your first message. You responding is the trigger for establishing everything long term.

Yes. The contact adds me, we start exchanging messages, we even talk via voice call. I hang up and still there are no safety numbers to verify or phone number to see. Anytime i want to write back at her i find her in my contact list, but there is no phone number below the name in the signal contact list. I think this upgrades to using signal without phone number, a feature many clients would love 😂😂

**Comment by cody-signal** [comment]
Hi, debuglogs would be helpful to try and figure out what is going on. Thanks!

**Comment by greyson-signal** [comment]
Hi there, this should have been fixed a while back.

**Comment by gomker** [comment]
This same scenario just happened this morning to me.

Device: OnePlus8 / IN2015
Android 13
App Version 6.29.2

**Comment by beedell-roke** [comment]
@gomker, [`signal-cli/discussions/1414#discussioncomment-8117716`](https://github.com/AsamK/signal-cli/discussions/1414#discussioncomment-8117716) may be of use. [^1]

[^1]: [`reddit.com/r/signal/comments/12y2qvk/comment/jhlxkdw`][1]

[1]: https://www.reddit.com/r/signal/comments/12y2qvk/comment/jhlxkdw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
