### ISSUE TITLE
restoring a backup constantly crashes the app

### ISSUE THREAD

**Issue by jthall** [signalapp/Signal-Android#12917]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Signal crashes when trying to restore a backup
### Steps to reproduce
- Open app and select transfer -> restore from backup.
- Select a backup and enter 30-digit passphrase
- Signal claims it cannot find itself in recipient table but messages are in message table

**Actual result:** Signal logs it is unable to find the entry for its own phone number either via ACI or E164 lookup. When import of the messages happens, assertion because it does not believe it has found its local entry in recipient table. The entry exists in the backup and the phone attribute looks like +17xxxxxxxxx where xxxxxxxxx are actual numbers. I can't figure out how to make the logs display the actual sql lookup for the e164 lookup, but a query like
select _id,phone from recipient where phone="+17xxxxxxxxx"; yields _id is 2 and that is the correct lookup in the backup.
**Expected result:** Signal should not crash and instead proceed to the reregistration screen

### Device info

**Device:** Manufacturer Samsung S7 Active
**Android version:** 8.0.0
**Signal version:** 6.19.1

**Comment by jthall** [comment]
I can try, the problem is that the first time you run, the crash hasn't happened yet, and then if you try to relaunch, the app crashes almost immediately. The app does not stay alive more than a second or two.
This is my first exposure to Java, and I'm trying to understand this syntax:
val selfId: RecipientId? = getSelfId(db)
This looks vaguely like the c ? : construct, where if RecipientId, presumably some  global variable not referenced in this function, is assigned to selfId if RecipientId contains something (or is not 0) and if it is 0 or evaluates to False, then getSelfId(db) runs.
I see a normal val declaration below that makes sense.

Then val idByE164 is similarly created. Would this be valid?
db.rawQuery("SELECT _id FROM recipient WHERE phone LIKE %?%", SqlUtil.buildArgs(e164))

I'd like to get a string representation of e164 so I can know what it is trying to look up. Presumably SqlUtils.buildArgs(e164) would do the trick, but the ? before the let is throwing me a little.

Sorry for that elementary question.

**Comment by jthall** [comment]
ok so getLocalE164(ApplicationDependencies.getApplication()) returns null. What in the database will feed the E164 object?

**Comment by jthall** [comment]
Looking at the changes from yesterday, it looks like the SQL lookup to determine if there are any messages was modified with a filter where type & 0x1F matches one of the following values:
2, 11, 21, 22, 23, 24, 25, and 26.
In my database, all show 0 except for 
23: 545
11: 5
2: 207
So presumably when you add all that up, 757 does not = 0 and that still throws the assert. While the type field does not exactly match these numbers, presumably this is a bitmask and you want to know if $type&0x1F == one of these.
So what do these types mean, i.e. where is a description of the bitmask that goes into the type field? Just for fun, I can remove the offensive types from the listOf here and see if it will let me restore the backup and register, but before I do that, I want to know what the types are and what this particular ascert is trying to protect against.

**Comment by KiralyCraft** [comment]
I can confirm this is also happening for 6.19.4. The logcat exception looks like this:

```
05-02 08:34:53.258 16813 16886 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16813
05-02 08:34:53.258 16813 16886 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Could not find ourselves in the recipient table, but messages exist in the message table!
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.migration.V185_MessageRecipientsAndEditMessageMigration.migrate(V185_MessageRecipientsAndEditMessageMigration.kt:50)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:201)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:166)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:279)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:278)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:278)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:294)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
05-02 08:34:53.258 16813 16886 E AndroidRuntime: 	... 4 more
```

It's rather difficult to get a debuglog from the app itself, given that after restoring the backup it crahes when it's opened. I'm on LineageOS 20

**Comment by KiralyCraft** [comment]
What I find interesting is that I've created backups automatically on a previous LOS install, specifically LOS16, where Signal was usually kept up to date. It seems the backups created were "broken" like this from the beginning since I have versions of them at least as old as February. 

They all crash the newer Signal versions, yet they still work on 6.18.4. Quite strange indeed

**Comment by jthall** [comment]
I don't think this is resolved.

**Comment by clark-signal** [comment]
Are you still reproducing? If so do you happen to have debuglogs and/or logcat logs?

**Comment by sugguy** [comment]
Same issue on : 
**Android 13 
MIUI 14.0.3
Signal version : 6.28.6 
Backup file size : 1.35 GB**

App crashes the moment I tap restore after entering the passphrase : 

`java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at An error occurred while executing doInBackground().(:0)
Caused by: java.lang.NegativeArraySizeException: -1073487864
	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
`

**Comment by CStafford-14** [comment]
I'd also like to report this. I'm on Signal 6.39.1 on a Pixel 7a running Android 14. I made a backup this morning as I had to reset my phone, so the versions should be the same. For some reason, Signal crashes when trying to recover with a backup.

**Comment by cody-signal** [comment]
Can you provide a debuglog after crashing during the backup restore process? You can tap any title in the registration/restore flow 8 times to get a debuglog.

**Comment by CStafford-14** [comment]
> Can you provide a debuglog after crashing during the backup restore process? You can tap any title in the registration/restore flow 8 times to get a debuglog.

I can't, actually. It crashes immediately after I select the archive, so I'm back to square one after that without logs.
I was able to import a previous backup, though. Maybe the archive was corrupted?

You could probably reproduce the issue by corrupting the archive and seeing what happens. Although it might not be possible to recover a corrupted archive, a crash can still be prevented.
