### ISSUE TITLE
Signal is constantly crashing when I try to register

### ISSUE THREAD

**Issue by tutak-kat** [signalapp/Signal-Android#12916]
Hi,
I want to use Signal for years?????? but I'am constantly unable to receive verification code - I got warning that google play service is missing I pressed I understand and I always got message "Signal has stopped".
I downloaded always Signal from official site.
Then I tried Molly and got the same result.
Phone is Samsung S9+ with android 8.
Google play is disabled as well as other Google and Samsung applications, phone is not rooted.
On my wife S8 Signal is working.
How to resolve the problem
Thanks

**Comment by cody-signal** [comment]
can you provide a debuglog? If you tap any screen title 8 times in the registration flow it'll open the submit debug log screen.

**Comment by tutak-kat** [comment]
Here is my debug log
https://debuglogs.org/android/6.17.3/8b33025d886bbedafc3c20767b86cb08bdc773b90b20f8322b8c1da38aece534

**Comment by cody-signal** [comment]
Thanks for the logs. It shows a webview exception. I noticed you're also building your own version?

Please make sure there's some webview implementation available from the OS. Signal is likely trying to inflate a webview so it can show a captcha.

**Comment by tutak-kat** [comment]
No i don't build my own version. It is beyond my capabilities.
Something is wrong. Can you check more, please?
I'am trying to use or official Signal app from signal site (without google) or molly-FOSS, but both have the same problem, actually I was not able to use them like ever since they are always crashing.


-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Apr 24, 2023, 13:55 by ***@***.***:

**Comment by tutak-kat** [comment]
I solved a problem.
When you mentioned webview I checked and found that it was disabled on my phone.
When I enabled it - Signal is working.
Thanks.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Apr 24, 2023, 13:55 by ***@***.***:
