### ISSUE TITLE
No notification on new member requests for groups

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#12926]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As the admin of  a group that I created, I set it so I have to accept their request to join.
But when somebody does that, I do not get any system notification. It only shows up on the top of the group itself, when I open the group.
Since the group is small, this often results in people waiting way too long or giving up, before I see it.

I have verified that all notifications are enabled in Android, that other notifications generally work for Signal, and that the group itself has notifications enabled too inside Signal. Messages by people in that group result in normal system notifications.

### Steps to reproduce
- Create a new group.
- Configure the group to only allow you (the admin) to add members or change group settings.
- Use another Signal account, to join that group via the group link sharing feature.

**Actual result:** Nothing happens. But entering the group as the admin, a small notification is displayed *inside* Signal.
**Expected result:** I should get a system notification even when not opening Signal. With a sound and everything. Ideally even easier to notice than a normal message one since it is more important.

### Screenshots
[Not possible, for privacy reasons]

### Device info

**Device:** Huawei Mate 10 Pro
**Android version:** EMUI 12.0.0.226 (Android Q 2023-04-01)
**Signal version:** 6.18.4

### Link to debug log
[Protocol contains sensitive information. Sharing it as-is is antithetic to the purpose of using Signal. As it is a *lot* of work to anonymize this, please request which of that information specifically you need when you need it.]

**Comment by UnderscoreX5** [comment]
Bug reports are always appreciated but without a full debug log, troubleshooting the issue becomes pretty hard. Debug logs contain low level app information and do not reveal any of your message contents. Since we do not collect data on you, we appreciate your help in identifying the issue and working with us to get this resolved.

**Comment by navid-zamani** [comment]
Hey,

what prevents you from following the steps to reproduce?

Or did you follow them and came to different results?

Given that I verified that it’s not caused by the OS, I would be surprised if your results differed from what happened here. The logs ate clearly not necessary to reproduce the situation, and contains mostly unrelated data anyway.
In any case, the bug would be resolved pretty quickly.

Please understand that, given the current workflow and UI, sharing that log stands in stark contrast to the reason why people use Signal. If you truly sanitized those (unreasonably huge) logs, presenting things differently in the UI and here … say offering verifiably reliable true anonymization  … would remove this contrast and not lead to this.
(Note that in any case, what is shared here, will be part of any data sent e.g. to the law enforcement of hostile governments or their corporations. So anonymization would have to include even fingerprintability above a certain number of fingerprint bits.)

I now read as much of the log as I could and will share it here. But if I die as a result, that’s on you.
https://debuglogs.org/android/6.19.6/77cfa0649c7545da2a9da4908bf777cf6b49df0583319398d65a69ae4334cb04

**Comment by antonengelhardt** [comment]
+1 on this!

I get the reason why this is not working, but i often forget to admit people, because i am not notified about it.

**Comment by tesujimath** [comment]
Well I would say it's possible, and as users are pointing out, highly desirable. 

If slow polling is the only current solution, then that is better than what we have at the moment. Checking each group state every three hours, say, would be so much better than what we have currently. Or even once every 24 hours.

Why do you imply slow polling is not possible?

Please reconsider!
