### ISSUE TITLE
Signal Crashes during voice calls

### ISSUE THREAD

**Issue by jthall** [signalapp/Signal-Android#12924]
#

- [X] I have searched open and closed issues for duplicates. (Nicholas requested new issue instead of #10892 )
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when making an audio or video call, or when switching away from the call screen to do something else on the phone because it expects the phone to support Picture-in-Picture. If Talkback is operating, the PIcture-in-Picture function is disabled because Talkback needs the overlay.
### Steps to reproduce
- open Signal when Talkback is running
- Select a contact and click signal call or video call.
- Signal sends the invite for the call, then crashes when trying to open the call screen.

**Actual result:** The app crashes because of an uncaught exception when PiP is not supported.
**Expected result:** The app should function normally when PiP is not in use.
### Screenshots

N/A

### Device info

**Device:** Samsung S7 Active (g891A)
**Android version:** 8.0.0
**Signal version:** 6.19.3

### Link to debug log

https://debuglogs.org/android/6.19.3/9707e5ba5b301573eedaf116ab532e15118dbfad46e480baf1745b288622fd52

**Comment by jthall** [comment]
I've been looking at this, specifically in WebRtcCallActivity.java in isSystemPipEnabledAndAvailable. Apparently, Picture In Picture is an allowed permission, android SDK is >= 26, and package manager says the feature picture in picture is available, however actually attempting it results in an exception because it is not in fact available. The only solution I can think of is you keep a state variable in the class that starts out true, then a try / catch when you go to initialize PiP if that fails you set it to false so that future calls to this function will return false. As a demonstration I forced this function to return false all the time and now I can at least make calls and switch away from them without crashing the app. It's not ideal but I need to be able to communicate with some of my people again.
Do you think my idea is sound? to initialize a state variable as true until proven otherwise?

**Comment by alex-signal** [comment]
I think we should just catch the exception, print a warning and move on.

**Comment by jthall** [comment]
As long as the functionality works--currently if it thinks PiP is available, whenever you try to transition the call screen the app crashes. I don't know enough about rendering to know what the impact would be if the app thinkgs PiP is enabled but it in fact isn't. You'd have to wrap all of the PiP calls and handle the exception separately, no?
That's why I was thinking a state variable would be doable, that way it would only need to be utilized in that one function instead of this function returning true when in fact the answer is false. When the init function fails, the catch could set the variable to false, then the top of the isPipEnabledAndAvailable or whatever it is would check for the presence of that variable being true and if it is not, return false; thus the app would function correctly and understand that PiP is in fact not available, which is the whole point of this function.

I really don't care what the final solution is as long as the app works as intended. It was amazing to be able to switch away from the call screen without a crash yesterday.
