### ISSUE TITLE
SIgnal fails during the account tranfer to a new device

### ISSUE THREAD

**Issue by reza-naq** [signalapp/Signal-Android#12925]
Hi there,

The process to transfer a Signal account from a device to a new one failed for me.
Here are the detals:

- Old device: Sumsung A7, running Android 10
- New device: Pixel 5a, running Android 13
- Signal version; the latest on both; 6.18.4

I follow the steps recommended in the Signal documentation.

- WIFI, Localisation & Bluetooth are active on both devices
- On both devices I grant all the permissions I’m asked for
- On the old device I activate ‘account transfer to a new device’
- On the new one I select “transfer from an Android device”

While the old device waits forever the new one fails offering to submit the error message.
When I submit I get the following link to share in case of error reporting:

https://debuglogs.org/android/6.18.4/1ad478a7217ce40f439db235d3f2f4a3f33c9191402a9ab2f0a61cd250a5e68b

Therefor I can’t transfer the chats from one device to another.
Any idea?

Thanks in advance

**Comment by nicholas-signal** [comment]
I see in your debuglog `add local service failure_reason: 2`, which [maps to a `BUSY` signal](https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pManager#BUSY). Is it possible you're using WiFi Direct in another app or something while trying to initiate your device transfer?
