### ISSUE TITLE
Progress wheel glitch when sending any media

### ISSUE THREAD

**Issue by Daydemon7** [signalapp/Signal-Android#12932]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending any picture or video regardless of size, it will begin to send as normal with the progress wheel starting to fill and then the wheel will begin jumping around to almost full then almost empty and eventually will fail to send after several minutes of this glitch on loop. Occasionally it will end successfully with double checkmarks but the recipient is unable to load the media. I cross verified with multiple recipients so I think the issue is on my side.

The issue seems to have arisen after the latest update although I am not 100% sure on the exact date. 

I am connected to a fast, stable wifi connection with no VPN, no app restrictions. 

***I did notice after connecting to my VPN (PIA) the issue has seemed to temporarily resolve and media sends normally as long as I'm connected to the VPN when initiating the message.***

### Steps to reproduce
- take picture or video
- Send picture or video
- bug immediately occurs

**Actual result:** Media begins to send as normal then the progress within the progress wheel begins to jump around forward and backward until it fails to send or sends successfully with the recipient unable to load the media
**Expected result:** Progress wheel should run smooth until media is sent successfully as normal

### Device info

**Device:** Samsung Galaxy S22 Ultra
**Android version:** 13
**Signal version:** 6.19.6

### Link to debug log
https://debuglogs.org/android/6.19.6/df2fa7b74c4f30dea3c0fc9962d269ee856fbcec3a57f6087d031c7630a12de2

**Comment by cody-signal** [comment]
Your logs have a larger than normal number of networking errors. Are you able to try on a different WiFi or cellular network and see if the issue persists?

I recognize this isn't a long term solution but helpful in troubleshooting the cause.
