### ISSUE TITLE
App crashes instantaneously when opened

### ISSUE THREAD

**Issue by conartist6** [signalapp/Signal-Android#12939]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Immediately when I open the app it closes itself. This began happening after I opened an old unread spam SMS message. I had formerly used signal for SMS before being forced to use a different app. Signal encouraged me to open the spam SMS showing a red unread messages counter until I had read all unread messages. Immediately upon opening the spam message Signal crashed, and then crashed on every subsequent attempt to open it.

I cleared cache data, but it did not help. I am unwilling to clear personal data as then I would lose my personal data!!

### Steps to reproduce
Open the evil text message, then try to open Signal ever again

### Screenshots
Nothing to see...

### Device info

**Device:** Google Pixel 4
**Android version:** 13
**Signal version:** 6.19.8

### Link to debug log
The app crashes before I can capture a log. I don't know how to use adb for debugging.

**Comment by nmalthouse** [comment]
Do you have any guesses as to what part of the spam message causes the crash? I am having the same issue with a verification sms from my school and would like to notify them.

**Comment by cattenbb** [comment]
Same issue here

**Comment by yip924** [comment]
Same issue. Mine started crashing right after I changed my phone number from a Hong Kong one (+852) to a UK one (+44).

**Comment by cody-signal** [comment]
@cattenbb @yip924 what version of the app are you running?

**Comment by cattenbb** [comment]
I uninstalled the beta version, then installed the regular one, then back to the beta and it seems to be working now. Thank you!
