### ISSUE TITLE
Connectivity detection doesn't work with reverse tethering (gnirehtet)

### ISSUE THREAD

**Issue by titibandit** [signalapp/Signal-Android#12941]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the gnirehtet USB reverse tethering app (https://github.com/Genymobile/gnirehtet), Signal's communications are not getting through, as if connectivity was absent. It is a somewhat known problem, since apps commonly verify connectivity by checking wifi and mobile data presence. This issue has been fixed for the Conversations XMPP client apparently (https://github.com/iNPUTmice/Conversations/pull/4050)

### Steps to reproduce
- Install gnirehtet reverse tethering as per the instructions
- Connect the phone to computer and activate reverse tethering

**Actual result:** Open signal and observe messages not coming in nor going out.
**Expected result:** Signal having normal internet connectivity

(Funnily, uploading the debug log seems to work)

### Device info

**Device:** Samsung Galaxy 7 SM-G930F
**Android version:** 11
**Signal version:** 6.19.8

### Link to debug log

https://debuglogs.org/android/6.19.8/c6ab054ee559fac1d9f0555055a34fa9951d91a8131c8a55a1128c30db778159

**Comment by nicholas-signal** [comment]
> This has been fixed and then reverted as mentioned in #12953. Any reason why this has been reverted?

https://github.com/signalapp/Signal-Android/pull/12953#issuecomment-1691811376
