### ISSUE TITLE
Deleted message still visible if answering during deletion of the message

### ISSUE THREAD

**Issue by 0xW00dy** [signalapp/Signal-Android#12946]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a user deletes a message while another user is answering the message, the message will still show as a preview above the message sent by the second user. 

### Steps to reproduce
- User A sends a message
- User B answers the message by sliding it
- User A deletes his message
- User B send a response to the deleted message
- Initial message will still be show as a preview

**Actual result:** The content of the deleted message is shown in the preview
**Expected result:** The preview should look like "Message deleted"

### Screenshots
![Screenshot_20230516-1449352](https://github.com/signalapp/Signal-Android/assets/74475627/00d48780-4e47-423f-aa97-f7595f9b7cda)

### Device info

**Device:** Nothing Phone (1)
**Android version:** 13
**Signal version:** 6.19.9

**Comment by greyson-signal** [comment]
Hi there, the mental model we have for quotes is that they're equivalent to copy-paste. So this is working as intended. But thank you!
