### ISSUE TITLE
Sent video have several problems (0.25x audio speed, stuck on frame but audio goes on etc etc)

### ISSUE THREAD

**Issue by Minibus93** [signalapp/Signal-Android#12945]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When videos are sent, they are often (not always) sent with some kind of sheaningans, like their  audio speed reduced to 0.25x, or them stucking on a frame while audio still goes on ecc...

### Steps to reproduce
I don't know, send a video and hope for the bug to appear? Sorry, I don't have a specific step by step indication

**Actual result:** The video is sent (video file was fine and not corrupted), the sent video is, in this case, playing the audio at an atrociously low speed, making it unservable.
**Expected result:** The video should play exactly as it is before sending it

### Screenshots

(happens on PC as well)

https://github.com/signalapp/Signal-Android/assets/73554423/9e2ea662-db0a-4faf-9248-48f6ca5a3d7e

### Device info

**Device:** Xiaomi Mi 10
**Android version:** 12 
**Signal version:** 06.20.3

### Link to debug log

Can't provide the debug log right after the bug because this bug happened some time ago and I only had the time to produce the documentation and write the report now. 
I'm sorry.

**Comment by Minibus93** [comment]
It did it again.

This time, I managed to grab debug log right after the video was sent uncorrectly (audio slowed down by terrible amount)
[signal-log-1684352478202.zip](https://github.com/signalapp/Signal-Android/files/11508636/signal-log-1684352478202.zip)

Here it is!

Please fix this bug asap because this really impacts Signal usability!

**Comment by Anti-ctrl** [comment]
Friend of mine has the same problem on his Asus Rog Phone. He sent me the same video twice and both times it broke the sound. Its heavily distorted like its at 0,25x speed.

He send the video and immediately captured a debug log. I hope that helps.

[signal-log-1685906383762.zip](https://github.com/signalapp/Signal-Android/files/11646476/signal-log-1685906383762.zip)

To add a bit more Info: Its not every video that has these issues. My guess is, that it might be something with the converting of the Video and the codecs in these Videos. I will add the broken video:

https://github.com/signalapp/Signal-Android/assets/68434734/209437f9-9ccc-4e3b-bfd5-a4cbfe2552bc

And just to make it complete, here is a working video, also send from him:


https://github.com/signalapp/Signal-Android/assets/68434734/cf554153-327a-4c5e-ad3c-e80ba2b78bdf

**Comment by mathsen** [comment]
That sounds like the same bug as described [here](https://github.com/signalapp/Signal-Android/issues/12674). I also have one phone with this problem - extremely annoying.

**Comment by Minibus93** [comment]
Has any signal dev aknowledged this issue in this or any other bug report?

The bug is still present and definitely impact daily usage with friends and family.

**Comment by primelionzard** [comment]
I am having the same issue, and usually it is when I download a vid from instagram to send in Signal. I have a Pixel 6 Pro.

[Debug Logs](https://debuglogs.org/android/6.28.4/98e94f9af7dd111906f82095ef72db5b7bceaebfe0e77d53b00145ee212e389d)

**Comment by Scary-Guy** [comment]
I just had this issue as well.  I sent the thread to my friend who sent the video.  It's an .mp4 formatted file and that's all I'm seeing in this and similar issues such as #12674.

Is it reencoding the video when sending it?  I would hope it just sent it straight to preserve fidelity.  If it's to reduce Signal's network overhead though by compressing it I can understand that I suppose.  Maybe marking friends as verified should allow for DCC transfers?  Maybe also mark the media on the end with M for modified and O for original 1:1 (as inputted anyway.) Sorry just thinking out loud.

**Comment by Na-Cly** [comment]
Same issue here. Steps to reproduce are send a video.

**Comment by Scary-Guy** [comment]
> Same issue here. Steps to reproduce are send a video.

I mean not exactly since it only happens to the videos some of the time.  I've been chatting with a friend and most of their videos have been working except for a few of them.  We both have androids so the ones from the new phone (Galaxy Fold) work fine, but ones taken on their previous phone seem to be slow.  I'm not sure what their previous phone was but I will ask.

If it happens with every video you send though @Na-Cly then you might want to mention your phone make/model/OS and submit a log.

**Comment by Na-Cly** [comment]
@Scary-Guy it happens to every video I send.

**Comment by Scary-Guy** [comment]
> @Scary-Guy it happens to every video I send.

Survivorship bias, (or whatever the inverse if that is.) It happens to every video that you send yes, but it doesn't happen to every video that I receive.  This tells us that it's not necessarily a fault of Signal alone but that it is contingent on certain conditions that must be met.

You saying that it happens to every video is good, but they need to know what kind of phone you have (and ideally some logs to analyze) in order to track down the exact cause.  The few videos that I have taken and then sent out on my Oneplus 7t did not have issues as far as I could tell.

**Comment by SamCyanide** [comment]
I am also having this issue. It only occurs with videos I downloaded from the Internet, primarily Instagram. 

Signal version is 6.40.4 for Android.

Here's some info on the video file:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sdcard/Movies/Instagram/VID_52220421_183257_304.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:13.65, start: 0.000000, bitrate: 4868 kb/s
  Stream #0:0[0x1](und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 58 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (hvc1 / 0x31637668), yuv420p(tv, bt470bg/bt470bg/smpte170m), 1080x1920, 4808 kb/s, 30.15 fps, 30 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (hevc (native) -> h264 (libx264))
  Stream #0:0 -> #0:1 (aac (native) -> aac (native))
```

**Comment by Zahrun** [comment]
not stale

**Comment by cody-signal** [comment]
Please provide new reports at this earlier thread: https://github.com/signalapp/Signal-Android/issues/12674

The two are linked, and I'll also link on our tracking side.

**Comment by Weedalf** [comment]
I have the same problem.
every video I edit with google photos app has these sound issues.
I have a google pixel 7 pro.
