### ISSUE TITLE
signal  for Android has serious perrformance issues - frequent interruptions and missing cat parts

### ISSUE THREAD

**Issue by bhlevca** [signalapp/Signal-Android#12944]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

The audio and video chats  have degraded in quality in the past 2-3 months. There are frequent interruptions and conversation is often impossible to do, most likely  due to lost packets.

### Steps to reproduce
Just try to have a conversation audio or video for more than 5 minutes. Sometimes even 2 minutes are enough to shoe the problem
Both sides are on good WiFi -connection.  In fact whether on WiFi or on mobile connection the results do not seem differ, leading to the conclusion that it is not a bandwidth at either end problem.

**Actual result:** 
Patchy, studded, missing parts of the conversation

**Expected result:** 
uninterrupted  flow of bits to support a normal conversation

### Screenshots

N/A

### Device info

**Device:** Google Pixel 6 Pro
**Android version:** 13 API 33
**Signal version:** 6.20.3

### Link to debug log

https://debuglogs.org/android/6.20.3/a4622581a4732316ddc9fac3151f597444b8e98b2375cf4f7577e7ad6afcb4f0

**Comment by bhlevca** [comment]
Can't get those, sorry

**Comment by bhlevca** [comment]
Hello, I finally managed to have another bad chat (audio only). Please find the link to the logs attached, hope that it helps

Mine: https://debuglogs.org/android/6.21.0/0e73abfa241cd44920e80ff558654fe029cb8b0a8def3b1c65eb2b78c84861d7
The other side: https://debuglogs.org/android/6.19.9/cc4fac51391c802c3f639b118e3d5add9834bc249bca4da0cb5a96e23f94df6f

**Comment by bhlevca** [comment]
Just a thought, could our ISPs throttle Signal chats?  Is the protocol identifiable by the ISP?

**Comment by bhlevca** [comment]
I did not do the WIFI test yet but here is a log for a mobile connection
audio chat/videochat that was good

https://debuglogs.org/android/6.21.2/2b109ddd43d4a9537560b6247a49017be241bd0e416d51a76f5c555b707538d9

it appears that the WiFi connection has a problem and I am wondering if it
has something to do to ISPs throttling the Signal connections

Below is a quotation from a thread on the Signal forum that blames the bad
quality on being at home Wifi or mobile. This looks very suspicious as I am
beginning to see the same. I'll try a Wfi chat that goes through your
servers.

Thanks



*"Same issue with me except turning on video tends to negate the audio
quality issues if I remember correctly.*


* None of this was a problem until I upgraded phones and went from Android
10 to Android 13.*



* Now the only way I can reliably use Signal audio calling is by turning on
a VPN connection first (any commercial VPN will do) then all lag and
choppiness is gone.*




* I also notice the choppiness/lagginess seems to mostly occur when I'm on
my home WIFI or the cellular tower serving my home. If I leave and get on a
different wifi network or different tower the issues subside quite a bit.
No idea what to make of it all. Would really really like to get Signal
calling working reliably again.*"

**Comment by bhlevca** [comment]
The following are logs with the relay on:

Mine: https://debuglogs.org/android/6.21.3/b40b17535d5387cbb7e6d08a095828750d8b872b2de5dab2feeaa7737dd9d894

The other side:  https://debuglogs.org/android/6.21.3/4b0b5c0de8478614dcb9cd6a9511cfcad2d6c00b584c5705fd624126530b9b80

Also before observing a glitch:
Mine: https://debuglogs.org/android/6.21.3/ace5081fc53b9ab72bb03b0287a3d4fc3010f2b48da43be44b2b8bede2aa4f70

The other side: https://debuglogs.org/android/6.21.3/c3a5ea10a247c19422bc12fe225901a54ed3c9bdc128838369b374ed04d7b27e

In general, the quality was better.  I noticed only one short lag 

Both were on Wifi.

**Comment by rashad-signal** [comment]
That's great to hear. Based on the logs, there might have been a few more cases where parts of the audio were missing, but they might not have been noticeable. And it definitely was a lot less than before.

There's another change we made to how Signal sends audio that's in the beta version of the app (6.22.1), and we'd like to get feedback to see if it helps fix this problem. Looking at the versions of the app you've sent logs from, it looks like you're enrolled in the beta already? If so, could you try one more thing: make a call on WiFi on 6.22.1 (or newer) without the "Always relay calls" option enabled. I think we should be able to see the effects from the logs if you can provide both sides, even if the person on the other side isn't using a beta version of the app.

**Comment by bhlevca** [comment]
Mine Wifi 6.22.1 https://debuglogs.org/android/6.22.1/d332cbc9661fa04d4e97995571b0ab3b1223e55da20ecab633e3adffd0f2e34d

Remote Mobile 6.21.3 : https://debuglogs.org/android/6.21.3/0087a786d2386c31c10560d6d7c57ad1b550f62a5fbfc25f1d3dc625b1286fe0

The reconnection still occurred a few  times, short but still there, you can probably see that in the logs.

**Comment by rashad-signal** [comment]
Thanks for trying it out again. It's good that the changes in the latest beta aren't making anything worse. But it's still unclear whether it makes things as good (or better) as when the "Always relay calls" setting is on. For the call in the logs, a relay server still happened to be used, so we might have to wait until more people are on the beta or until it's released to production to get more feedback on it.

**Comment by bhlevca** [comment]
I had a perfect audio chat today for 30 minutes. We both were on mobile data. 
I only have problems on wifi. If there is nothing inyour code that creates these loses in connection, then I suspect some foul play an throttling by those who can

**Comment by bhlevca** [comment]
https://debuglogs.org/android/6.23.5/3f2ca7fb99adeb02f48cbb4c32fa1828cda38c15e1a7dcb55cd8e25b81aa29fd

This is the latest log. Things got worse. I am going to try on mobile data.

I suspect more and more that's throttling. How can we tell if such things happen. What ports and protocol is Signal using. Thanks

**Comment by rmacklin** [comment]
I've been having this issue, too - for months, at this point. (I generally have to ask the other party to switch to a different calling platform since the choppiness makes the audio effectively unusable.) Currently running version 6.23.5 on Android 13. I'm always on WiFi, and have not had the "Always relay calls" setting enabled. I'll try enabling that setting to see if it gets better. But just wanted to add another data point. (I also found a [reddit thread](https://www.reddit.com/r/signal/comments/yehtpz/audio_cuts_out_during_audio_or_video_calls/) where others seemed to be having the same issues.)

**Comment by rashad-signal** [comment]
@bhlevca There still isn't anything in your logs that would suggest that throttling is happening. Your device is still receiving the audio, but in bursts. If you think there's throttling (as in reducing the amount of bandwidth available) happening, you can try making an audio-only call which will use significantly less bandwidth than a video call. I think you already tried this previously though, so you'll probably see the same thing.

Take a look at [this](https://support.signal.org/hc/en-us/articles/360007320291-Firewall-and-Internet-settings) for ports and protocols used in calls.

---

@rmacklin could you provide debug logs taken after having a bad call so that I can check whether you're experiencing the same problem?

**Comment by bhlevca** [comment]
I understand.  Port 443 is always open as it is for the HTTPS protocol the other ports are UDP and thye go through the firewall. If it is not throttling then what causes the busts and interruptions? Why on data this doesn't happen?

**Comment by bhlevca** [comment]
In a similar thread, someone said that version 6.24.3 does not show this problem, but he had multiple changes done to his system including an upgrade to a different phone/OS version.

I am cautious and I want to test thoroughly before declaring victory.

**Comment by bhlevca** [comment]
The latest version 6.24.4 seems to be much better. Still has the occasional interruptions but they are fewer and shorter. A short conversation may not experience any, but in longer conversations, the issues will be still there.  A good step forward!

**Comment by bhlevca** [comment]
Unfortunately the joy was short lived. The performance issues are still present.
A lot of information was added to a closed too soon similar bug:
https://github.com/signalapp/Signal-Android/issues/11789

**Comment by rashad-signal** [comment]
@bhlevca Could you try out version 6.26 of the app, which was recently released to beta? 6.26.0 or anything newer would be fine. It has some changes which we think will reduce the impact of the bug. The change applies to the receiving end of the audio, so even if the person you're talking to isn't on beta, the hope is that you'll still be able to hear the difference. And as always, logs will help in understanding what's going on.

**Comment by bhlevca** [comment]
I had a very good video chat today. The version I  had installed at the time was 6.26.0. However, my location was outside Canada so I cannot conclude that it is better because of the new version or the ISP here in Europe is not throttling the communication
