### ISSUE TITLE
Infinite loading after entering PIN code during registration

### ISSUE THREAD

**Issue by 0-Il** [signalapp/Signal-Android#12948]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I once created a backup > reinstalled the app > tried importing the backup > got this error: "Backup contains malformed data". I have a debug log of that error (the exact error from the debug log is a `Failed due to foreign key constraint violations.`), and I have a hypothesis about why my backup got malformed data in the first place, but it's a whole other story for which I would have to create a separate issue. 
I've successfully fixed the backup via this tool https://github.com/bepaald/signalbackup-tools, its developer guided me how to fix it. Now, when I try to import my backup upon registering an account, the app imports the backup successfully, I register my phone number successfully, however, after entering my account's PIN code, the loading circle appears and gets stuck, loading infinitely. The app is stuck and doesn't proceed to the chat screen. I suppose that the infinite loading after entering PIN is due to loading my account / backup in the background. Now, if I close the app and wait a little, I then open the app, and the app's theme changes to dark, which is the theme I use: welcome screen now has a dark theme, which means that despite I haven't even got to the chat screen, my account and backup are already loaded into the app. (The debug log has a string which indicates that the theme changed to dark (`DynamicTheme: Setting to always night`) and other strings indicating that the account / backup were loaded into the app.) And now, if I try to import the backup again, it just skips loading the backup (as it is already loaded) and goes right to the phone number registering screen. I register my number, enter my PIN, and this time the app proceeds to the chat screen and I can use the app. From now on, I could just let it go and continue to use the app, but I'm not satisfied with it, as I want to register my account in a clean way, without any bugs and errors, so they, in turn, wouldn't cause me any other new bugs in the future.

### Steps to reproduce
- Open the app
- "Transfer account"
- "Restore from backup"
- [backup selected, passphrase entered, ... backup restored]
- Register the number
- Enter PIN code

**Actual result:** After entering the PIN code, a circling loading icon appears and the app gets infinitely stuck at "loading": there's nothing but the circling loading icon, the app doesn't proceed to the chat screen.

**Expected result:** After entering the PIN code, the app should proceed to the chat screen.

### Device info

**Device:** Huawei Honor 6A DLI-TL20
**Android version:** 7.0
**Signal version:** 6.19.9

### Link to debug log

https://debuglogs.org/android/6.19.9/87f1a339f069ccf70a05374c35fbfe8f1877f4bbec5cce7fad9d225469958e51 

If your editor displays line numbers, the infinite loading error starts at line 1908. And here's the exact string for manual searching: 
`[6.19.9] [1031 ] 2023-05-16 23:54:31.094 GMT+03:00 W DeadlockDetector: Found a long block! Blocked for at least 5000 ms.`

**Comment by greyson-signal** [comment]
I see in the log that we're taking a long time to do a migration. You said it was loading "indefinitely" -- how long did you wait? Can you wait for several minutes? You have an older device and if you have a large database, running all of these migrations could take a while.

**Comment by clark-signal** [comment]
Thanks for the update and reporting. Looks like there's a bug in our db migration and restore from backup flow. We'll take a look.

**Comment by greyson-signal** [comment]
This should have been fixed in 6.21.1
