### ISSUE TITLE
"Hide this card?" and other payments dialogs are not MD3

### ISSUE THREAD

**Issue by Wojtaz0w** [signalapp/Signal-Android#12949]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- Go to settings > Payments (beta) 
- Click on three dots next to any card with info about cryptocurrency (like arrow on the screenshot) 
- Old style dialog "Hide this card?" appears 

**Actual result:** Dialog is Material Design 2
**Expected result:** Dialog is Material Design 3

### Screenshots
![Screenshot_20230516-234414_Signal.png](https://github.com/signalapp/Signal-Android/assets/104674625/9f021c8a-cde7-48fd-99fc-f5cbf4a0b3d8)

### Device info
**Device:** Redmi 9
**Android version:** 13 (crdroid) 
**Signal version:** 6.20.4

### Link to debug log
Not necessary

**Comment by Wojtaz0w** [comment]
Also this dialog about recovery phase is MD2 while it shouldn't. Checked on Signal v6.21.0 ![Screenshot_20230518-205955_Signal.png](https://github.com/signalapp/Signal-Android/assets/104674625/b50f868b-3724-497c-81c4-92562994e947)

it pops up when mobilecoin recovery passkey is incorrect (one from random worda)

**Comment by Wojtaz0w** [comment]
> Hi, i would like to work on this, if you don't mind. 

Sure, go ahead 😀

**Comment by Wojtaz0w** [comment]
> Hi, i would like to work on this, if you don't mind. 

Sure, go ahead 😀

**Comment by Wojtaz0w** [comment]
Fixed in 6.23.0
Installed 6.23.1 today, issue fixed 🙂❤️

**Comment by cyb3rko** [comment]
Unfortunately it's still relevant for other dialogs, see #12852 .
App version: 6.24.4
