### ISSUE TITLE
Date picker looks outdated (MD2)

### ISSUE THREAD

**Issue by Wojtaz0w** [signalapp/Signal-Android#12958]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The date picker (schedule message) looks outdated. 

### Steps to reproduce
- Try to change date when the message will be sent
- Outdated MD2 date picker pops up

**Actual result:** Date picker is using Material Design 2
**Expected result:** It uses MD3 (**https://m3.material.io/components/date-pickers/specs**) 

### Screenshots
![Screenshot_20230520-074613_Signal.png](https://github.com/signalapp/Signal-Android/assets/104674625/8c4d1353-1918-462c-9090-94c88aa05a33)
How it should be:
![Screenshot_20230520-075554_Mull.png](https://github.com/signalapp/Signal-Android/assets/104674625/7aa9a727-e7d7-47f1-b349-bec831fcafb9)

### Device info

**Device:** Redmi 9 with custom rom crdroid
**Android version:** 13
**Signal version:** 6.21.2

### Link to debug log
Not required

**Comment by Oshanik22** [comment]
Hi I would like to pick this up :)
Is that alright?

**Comment by Wojtaz0w** [comment]
I'm not sure i understand... English isn't my native language. What do you mean by picking up? @Oshanik22

**Comment by Oshanik22** [comment]
I mean that i want to work on this

**Comment by Wojtaz0w** [comment]
Okay, sure 🙂

**Comment by Oshanik22** [comment]
thanks 🙃

**Comment by Oshanik22** [comment]
Hi, after a bit of research, these are my findings - 

Currently, we are using the MaterialDatePicker from the [MDC 1.8.0 library](https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md), which is considered part of Material Design 3. This means that our datepicker aligns with the Material Design 3 guidelines. It closely resembles the MaterialDatePicker showcased in the [MDC material 3 datepicker documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md).
 
<img width="702" alt="MD3 datepicker" src="https://github.com/signalapp/Signal-Android/assets/64382839/2a55649f-3bf5-45af-b49c-c155ef5e3b0f">


To provide a clearer picture, here is an example of a Material Design 2 datepicker: [Material Design 2 Datepicker](https://m2.material.io/components/date-pickers).

<img width="341" alt="Screenshot 2023-05-22 at 11 40 05 AM" src="https://github.com/signalapp/Signal-Android/assets/64382839/3126397f-3b11-4cc8-aa86-da71781b2357">



However, it's important to note that the visually appealing datepicker shown in the [link you provided](https://m3.material.io/components/date-pickers/specs), which belongs to the Material Design 3 specification, is currently part of the Jetpack Compose library and has not been officially released.

Considering the situation, we have a few options:

1. We can customize the appearance of our current datepicker to make it visually more appealing.
2. We can wait for the official release of the Jetpack Compose datepicker and adopt that once it becomes available.
3. Alternatively, we can explore using the datepicker provided by this library: [Library for alternative datepicker](https://github.com/maxkeppeler/sheets-compose-dialogs).

Please let me know how you would like to proceed.

**Comment by Wojtaz0w** [comment]
I belive option 1 is the best. Maybe also bumping MDC lib to 1.9.0 would change it. Thanks a lot for working on it 😀

**Comment by greyson-signal** [comment]
Hey folks, thank you for the interest, we're just gonna keep using the datepicker that google has provided. When it gets updated, we'll use it (I tested 1.9.0 and it didn't seem to change anything).
