### ISSUE TITLE
org.json.JSONException: Value null at data_size of type org.json.JSONObject$1 cannot be converted to long

### ISSUE THREAD

**Issue by 0xmatthias** [signalapp/Signal-Android#12952]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After my phone died I tried to import a signal backup from 2022 which failed due to a foreign key contrains crash. So I looked into the issues and found out a lot of people have this problem. Unfortunately [signalbackup-tools](https://github.com/bepaald/signalbackup-tools) did not resolve the problem. So I created an empty backup and used signalbackup-tools to import all conversations from my signal desktop into that empty backup. I could import the newly created backup into the signal app, which contained all attachments and conversation from my signal desktop. My guess is, that this backup also included some broken attachments.
So today I received an image from a friend. When I try to open the Image, then signal app crashes. On my PC I have no Problems to open the Image with signal-desktop. I have no problem to open other pictures in other chats.

### Steps to reproduce
I don't know. Maybe try to import a backup from signal desktop with [signalbackup-tools](https://github.com/bepaald/signalbackup-tools) and look into the sql database in the parts table if there are any empty data_size rows.

**Actual result:** Signal crashes, when I try to open the image. I can see it for like 1 second
**Expected result:** Signal shows the image like signal-desktop does

### Device info

**Device:** One plus 10 pro
**Android version:** 13.0
**Signal version:** 6.20.6

### Link to debug log
relevant logcat output:

```
05-17 19:19:14.917 23067 24699 E AndroidRuntime: FATAL EXCEPTION: signal-io-bounded-7
05-17 19:19:14.917 23067 24699 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 23067
05-17 19:19:14.917 23067 24699 E AndroidRuntime: org.json.JSONException: Value null at data_size of type org.json.JSONObject$1 cannot be converted to long
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.json.JSON.typeMismatch(JSON.java:101)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.json.JSONObject.getLong(JSONObject.java:526)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.JsonUtils$SaneJSONObject.getLong(JsonUtils.java:65)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachments(AttachmentTable.java:1268)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getMediaMmsMessageRecord(MessageTable.kt:5181)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getCurrent(MessageTable.kt:5040)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getNext(MessageTable.kt:5030)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5334)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5328)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository.getAttachments$lambda$4(MediaPreviewRepository.kt:1620)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository.$r8$lambda$jItvT5bjeQY5LM-YvP77dU7HmP8(Unknown Source:0)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository$$ExternalSyntheticLambda0.call(Unknown Source:10)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
05-17 19:19:14.917 23067 24699 E AndroidRuntime: 	at Value null at data_size of type org.json.JSONObject$1 cannot be converted to long.(:0)
```

**Comment by gangulwar** [comment]
Could you kindly provide more details about the steps you followed when the crash occurred? Any specific actions or sequence of events that led to the crash would be helpful in reproducing the issue on my end.

**Comment by 0xmatthias** [comment]
I used [signalbackup-tools](https://github.com/bepaald/signalbackup-tools) to import all conversations and attachments from my signal desktop, because my signal backup from 2022 lead to a foreign key contrain crash and thus I could not import my original signal backup 2022. I suspect, that it created a faulty SQL database. I have a question regarding the parts table. Is it possible, that the table can contain entry with a data_size of NULL? 
Because my signal SQL Database obviously contains such entries. If the answer is no, then I could just delete the entries. Also can I check signal backups with the signal android app without re-register my phone number?

**Comment by gangulwar** [comment]
It is not intended to contain entries with a NULL data_size value. If such entries are present, it indicates a potential issue within the database. Might be possible to delete the entries with NULL data_size values, although caution is advised.

If you are willing and able to do so, I kindly request your assistance in providing me with the JSON file containing the backup data. Having access to the actual backup file would be immensely helpful in examining.

As for your query about accessing the contents of a backup without re-registering your phone number, I am uncertain.
