### ISSUE TITLE
Fatal Exception when restoring backup

### ISSUE THREAD

**Issue by Skipp1** [signalapp/Signal-Android#12965]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is crashing on restore/registration.

### Steps to reproduce
- Open fresh Signal install
- Press restore from backup 
- Register phone number
- Enter verification code
- *Crash*

**Actual result:** Signal crashes
**Expected result:** Signal restores the backup.

### Screenshots

[video.mp4](https://github.com/signalapp/Signal-Android/assets/32483567/8a85866a-04d1-4cf1-af29-154cd5922944) ( Phone number removed )

### Device info

**Device:** Oneplus 5
**Android version:** 11 ( lineage_cheeseburger-userdebug 11 RQ3A.211001.001 )
**Signal version:** Signal-Android-website-prod-universal-release-6.20.5.apk

### Link to debug log

[logcat.log](https://github.com/signalapp/Signal-Android/files/11547706/logcat.log)

**Comment by cody-signal** [comment]
Can you try updating to 6.21.x and making a new backup and new restore?

**Comment by AN4364364** [comment]
I have a very similar situation. After restoring the database backup and going to the next page with phone number confirmation, Signal crashes after several seconds. If I click through really fast, I can get the SMS confirmation sent to me, but I can't type it in fast enough. If I reopen Signal, I get back to the same home screen page shown in 0:01 of the video, but it crashes again after several seconds. It becomes impossible to keep the app open for more than a few seconds to do anything with. It's almost like it's on a timer. Uninstalling and reinstalling allows me to restart from square one, but the outcome is the same each time.

I can't click fast enough to get a debug log. It just crashes.

I'm on a Samsung Galaxy 10+, latest Android version of Signal as of this post, plenty of space on the phone.

**Comment by cody-signal** [comment]
What version did you create the backup file in? Could you try using logcat or pidcat to capture the crash details?
