### ISSUE TITLE
Can't transfer data to new phone due to version mismatch

### ISSUE THREAD

**Issue by sebathomas** [signalapp/Signal-Android#12962]
Hi, I realize this might be a Play Store issue and not a Signal issue but it's blocking data transfer for me so I thought I'd ask here.

I'm trying to transfer my app data from my old phone (Pixel 4a) to my new phone (Pixel 7a) but for some reason the Play Store won't allow me to install the most recent version. On the new phone I'm stuck on version 6.19.9, while the old phone has version 6.20.6. Signal on the new phone won't let me install backups created in the old phone because of the version mismatch, and the location-based update fails every time without an error message.

I already tried reinstalling Signal via Play Store and clearing the Play Store user data and cache but I always get the old version. Any idea what might be the reason? Should I download the apk from the website instead? I'd normally like to avoid that.

**Comment by nicholas-signal** [comment]
The Play Store gradually rolls out new versions to different users. In cases like these, you can force download the latest version at https://signal.org/android/apk/
