### ISSUE TITLE
Signal story: incorrect views being displayed on story

### ISSUE THREAD

**Issue by njmulsqb** [signalapp/Signal-Android#12964]
**Device:** Huawei Y7 Prime
**Android version:** 8.0.0
**Signal version:** 6.20.6

### Link to debug log

https://debuglogs.org/android/6.20.6/88b00c63c610253eea6a350db4d558fa49ebdf99b6a3025b52fd5ae7e3871089

**Comment by njmulsqb** [comment]
When I post a story, it shows N views for example it shows 5 views but when I click on views to see those 5 viewers I can only see 2 viewers, so the views count is incorrect

**Comment by greyson-signal** [comment]
I think this should be resolved in the latest version.
