### ISSUE TITLE
Leaving app after two, not just one back gesture

### ISSUE THREAD

**Issue by krwow** [signalapp/Signal-Android#12973]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes after opening app (I think it doesn't matter if it's from multitask view or launcher) using back gesture doesn't result in leaving app and getting back to Android desktop, I can see the gesture animation, but Signal all chats view is being opened one more time. I have to use back gesture again to get to the Android desktop. It doesn't happen every time, but every few attempts.

### Steps to reproduce (not every time it works)
- open Signal from multitask view, desktop or launcher's list of apps
- stay at list of chats view
- use back gesture in attempt to leave the app (but after animation it is still on the same place, the same view)
- use back gesture one more time to leave the app successfully

**Actual result:** Staying at all chats view after using back gesture
**Expected result:** Leaving app after using back gesture

**Comment by krwow** [comment]
No, I have been experiencing this issue for some time, it was even before this app icon change feature added.

**Comment by cody-signal** [comment]
Thanks for the quick response. Can you think of anything unique about your OS install? Custom ROM or non-default launcher like Nova or other? Some set of developer settings enabled that usually aren't?

If you can find consistent repro steps where the issue occurs every time that would be very helpful.

**Comment by krwow** [comment]
It's default stock Android 13, nothing special, the same thing with developer settings. But I use Olauncher instead of default one. There's no such issues with other apps, but thanks for a hint, I might give default launcher a try, maybe that's the cause of problems. And I'll try to find some consistent way to reproduce bug,
