### ISSUE TITLE
Cannot send messages in some chats

### ISSUE THREAD

**Issue by Gugu7264** [signalapp/Signal-Android#12976]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are 2 chats (1 group and 1 contact) in which I am unable to send messages. I am correctly receiving them, almost instantaneously, but every message I try to send is stuck (rotating dotted circle).
I have no VPN enabled, rebooted my phone twice, forced the app to stop, but nothing worked.

### Steps to reproduce
(hard to reproduce since it's very specific)

- Go to one of the 2 bugged chats
- Try to send a message

**Actual result:** The message is stuck and not sending at all (rotating dotted circle)
**Expected result:** The message should be sent correctly (and the receivers should receive it)

### Screenshots
*Imagine a message with a rotating dotted circle, literally*

### Device info

**Device:** Google Pixel 6a
**Android version:** UpsideDownCake (UPB2.230407.019)
**Signal version:** 6.22.4 (beta)

### Link to debug log

https://debuglogs.org/android/6.22.4/f60b75a4f482f44da070c9f8c5ffcefa46da24e97b86b468bae77fc583f2ef75

**Comment by cody-signal** [comment]
Hi @Gugu7264 are you still encountering this issue? If so, could you please update to latest version of Signal available to you and see if that addresses the issue?

**Comment by Gugu7264** [comment]
Hi, the issue resolved itself after a few days, no idea what was it related to...
