### ISSUE TITLE
Limitation in the number of allowed notification customization + cant free slots when conversation are deleted

### ISSUE THREAD

**Issue by JohnXLivingston** [signalapp/Signal-Android#12974]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

There seems to be a limit for the number of custom notifications we can create.
Let me explain (sorry, screenshots are in french).

When I try to add a custom sound for message, by:
- going to group properties / sound and notifications / custom notifications
-  clicking on «personnaliser» ("customize" in english):

![image](https://github.com/signalapp/Signal-Android/assets/38844060/ac933c79-8d83-436f-b06c-b0fefcf5a045)

Nothing happens.

If I open Android settings, go to notifications/applications, and select signal, here is what i got:
![image](https://github.com/signalapp/Signal-Android/assets/38844060/36d8b89f-1101-401a-856c-b5a092308d04)

It seems that signal adds an entry for each conversation with custom notifications.

And at the end of the screen, i got this:
![image](https://github.com/signalapp/Signal-Android/assets/38844060/8b3175b5-e3c4-401a-84c6-b470a2f0e5b7)

There is a label saying «16 catégories supprimées». French for "16 deleted categories".
And each time i try to customize notifications for a new group, this count is incremented!

So, it seems there is a limit to the number of conversation that can be customized.

And there is more... My signal is setup to prune message after some time. So, some groups are no longer displayed in my signal app... So i can't disable custom notification in old and deprecated groups. I did not find a way to list all groups that i belong to, so i can uncheck custom notification in these groups. I'm totally stuck. 

### Steps to reproduce
- customize notifications for 20 or 30 groups

**Actual result:** Can't select sound for messages.
**Expected result:** To be able to select custom sound for messages, even when there are a lot of customized groups. Or at least, a way to disable custom notifications on groups that are no more listed in signal.

### Screenshots
See above.

### Device info

**Device:** Fairphone 3+
**Android version:** /e/ OS, version 1.11
**Signal version:** 6.21.3

**Comment by alex-signal** [comment]
Whenever you create a new notification, you're essentially constructing a new NotificationChannel and deleting the old one. That's just how android works.

> So, some groups are no longer displayed in my signal app... So i can't disable custom notification in old and deprecated groups.

You should be able to press the pencil in the bottom right of the chat list screen and search by name for the groups in question.

**Comment by JohnXLivingston** [comment]
> Whenever you create a new notification, you're essentially constructing a new NotificationChannel and deleting the old one. That's just how android works.

And is there any way to display an error message in signal that tells why we can't add custom notifications?
I was searching for hours to try to understand why this feature did not work (although it worked before).

> You should be able to press the pencil in the bottom right of the chat list screen and search by name for the groups in question.

I can indeed find some groups using this method. But not all. There are groups i can't find. Maybe groups i lefted long time ago?

I cleaned all groups that I can. There are only 7 groups still shown in my android settings (the ones i can't find in signal, and 2 for which i want to keep custom notifications).
But i still can't add new custom sounds. And the count of «deleted categories» goes up to 22 now :'(

Any clue for how i can solve this issue? Is there a way to delete all custom notification in android, so i can start from scratch?

Anyway, thanks for your response.
