### ISSUE TITLE
Opening notifications settings causes app to hang 

### ISSUE THREAD

**Issue by githubuser6000** [signalapp/Signal-Android#12970]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Open settings
- Open notification settings
- observe app hangs 

**Actual result:** notification settings should open up (it does open, but after the "app is not responsive" popup shows up 3 times)
**Expected result:** I should be able to open notification settings, and change settings, without app hanging multiple times for each setting that I change 

### Device info
**Device:** Pixel 6
**Android version:** 13
**Signal version:** 6.22.2 (Beta, from playstore)

### Link to debug log

[Logs](https://debuglogs.org/android/6.22.2/cf32862d7e6fa9278213359c975f621c2797e65e98f1c3436948c1c18bd25783)

**Comment by cody-signal** [comment]
Hi there, this is kind of wild.

Does this happen every time you try to open notifications? Is it only notifications settings or does this happen randomly while using the app?

Nothing jumps as to a cause in the logs unfortunately, but I do see evidence of the main thread hanging for sure, just don't know what's causing it.

**Comment by githubuser6000** [comment]
Okay so I managed to reinstall android and it's gone, for some reason :/
Thank you for your time!
