### ISSUE TITLE
Linking new device resets safety number verification status of contacts

### ISSUE THREAD

**Issue by sellth** [signalapp/Signal-Android#12977]
### Bug description
Regularly I need to re-link one of my lesser used devices because it hits the 1 month limit. While this used to work without noticeable problems, recently the act of re-linking **de-verifies** the safety numbers with most of my contacts. I get a status message along these lines: *You have marked your safety number with X as not verified from another device.*

This has happened twice after the 1 month grace period ran out, ~~but I cannot reproduce it when manually unlinking the device.~~ First time most of my contacts de-verified, 2nd time one remaining contact de-verified + another contact which I re-verified in the meantime.

Edit: I can now reliably reproduced this when manually unlinking the device while the respective client is closed.

### Steps to reproduce
- Have Signal Desktop linked to Signal Android.
- Verify contact safety numbers.
- Close Signal Desktop.
- Unlink Desktop client from the Android app.
- Open Signal Desktop, follow instructions to re-establish the linking.
- On Signal Desktop, open the conversation of the verified contact(s).

**Actual result:** Verified contact safety numbers are marked as not verified.
**Expected result:** Contact verification status does not change.

### Device info
**Device:** Google Pixel 4a
**Linked Signal client:** Signal desktop for Linux
**Android version:** 13
**Signal version:** 6.21.3

First encounter was April 9th, probably Signal 6.17.

### Link to debug log
Issue occurred today (June 1st) roughly at 12:30 GMT.

Android: https://debuglogs.org/android/6.21.3/f2b357078e0a7db3e2bac6a0ac886e5e92d05a129d966456d7efd60e8282f192
Desktop: https://debuglogs.org/desktop/6.19.0/0482e33dd0183dd41fc587ff50b97d10a23893c8cc8a285125d52c5c171109d8.gz

**Comment by otakup0pe** [comment]
Confirming this with mobile android and windows 10 desktop being linked. The desktop had previously been linked but I hadn't used it in months.

**Comment by sellth** [comment]
I cannot reproduce this any more. Appears to be fixed.

**Comment by nicholas-signal** [comment]
Hello all, I believe this issue was fixed by https://github.com/signalapp/Signal-Desktop/commit/90f0f8e2558c06838b9bf3c8d54e5fb563b59296
