### ISSUE TITLE
My Signal Android is not sending anything & Signal Desktop is showing the wrong checkmarks

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12984]
https://github.com/signalapp/Signal-Desktop/issues/6468

**Comment by clark-signal** [comment]
Hi, sorry you're experiencing issues. Do you happen to have logs from the Android device?

**Comment by Meteor0id** [comment]
No need to apologize, you didn't create this situation.

Uploading the log keeps failing so I upload it here manually 

[signal-log-1686170950309.zip](https://github.com/signalapp/Signal-Android/files/11681858/signal-log-1686170950309.zip)

**Comment by Meteor0id** [comment]
I now found out my Android app is also not sending messages to anyone. So in fact the Android app is almost completely not working. What IS working still is that when I send something to someone it shows up on signal Desktop as well (so messages I am sending to others do still get synchronized to Desktop.

Signal Desktop shows two check-marks (which I think is untrue! I think the message is not actually being delivered! Signal Desktop is misleading me by showing it was delivered but not read)

**Comment by clark-signal** [comment]
Thank you for the logs! This should be fixed in 6.22.7 and should be fixed in 6.23.1 (it is present in 6.23.0 if you have that)

**Comment by cody-signal** [comment]
The fix is in 6.22.7 but was missed in 6.23.0. The fix will also now be in 6.23.1.
