### ISSUE TITLE
Forget passphrase 

### ISSUE THREAD

**Issue by kavinkarthiik** [signalapp/Signal-Android#12982]
I need to know my passphrase

**Comment by jackmurray** [comment]
>And if you mean a passphrase for your chat backup file, then there's no way to recover it.

Is there a way to reset it, so that newly-created backups use a new passphrase? Does disabling backups and re-enabling them generate a new passphrase? If so, the UI does not make that clear.

**Comment by greyson-signal** [comment]
For backups, disabling and re-enabling will reset the passphrase, yes. 

For your PIN, the documentation already posted here is correct.
