### ISSUE TITLE
Unable to find backup file, attempt

### ISSUE THREAD

**Issue by Paulchen232** [signalapp/Signal-Android#12986]
Debuglog:
https://debuglogs.org/android/6.21.3/01177a09899b85a8e75fd79b7194592f0f3adbcfef9b98ae995db6e8b7552c31
My mother's backup still doesn't work. Signal also attempts to write to non-existent external storage.
Perhaps anywhere can Help my.

_Originally posted by @Paulchen232 in https://github.com/signalapp/Signal-Android/issues/12915#issuecomment-1580315829_

`Backup failed`
Cellphone: Samsung A53
Android: 12,13
Signal 6.21.3
I do not understand why Signal do this.
So it is not correctly recognized that no external memory is available and with external memory it works too not.

**Comment by Paulchen232** [comment]
My mother can`t send the neu debuglog as http.
[Debuglog ](http://paulchen.w4f.eu/signal-log-1686384722426.zip)

**Comment by Paulchen232** [comment]
in the debug log he does not find so many stickers.

**Comment by Paulchen232** [comment]
First of all I transferred the account to a Nokia G22. The backup then worked there. There were some illegibility in the backup which I corrected with signalbackup-tools. I was able to export the chats as html. But back on the Samsung A53, the backup still didn't work.

**Comment by Paulchen232** [comment]
Oh, I guess I didn't fix anything. Since the backup works on the Nokia G22, I couldn't fix anything with the "signal backup-tools". The inbound and outbound backups were the same. On Wednesday I will transfer the account again from the Samsung A53 to my Nokia G22 and then uninstall and install Signal on the Samsung A53. I don't think I've done that before. I'm curious if the backup on the Samsung works again when I transfer the account back.

**Comment by Paulchen232** [comment]
Backup on Samsung A53 futurmore not work. 
@clark-signal  What android.calling.telecomModelBlockList in the debuglog means.

**Comment by Paulchen232** [comment]
Yes I did that but it didn't help.

> android.calling.telecomModelBlockList is completely unrelated and is about calling.
Ok,

**Comment by Paulchen232** [comment]
I was thinking it might have something to do with the problem as the phone model is so similar.

**Comment by Paulchen232** [comment]
The close was an error. The backup works not.

**Comment by clauz9** [comment]
Can you open "App info" for signal and let me know what permissions you have allowed for the app, and also check in the "storage" section to see if you have "External storage" permitted

**Comment by Paulchen232** [comment]
I have also du this:
:\Program Files (x86)\Minimal ADB and Fastboot>adb shell appops get org.thoughtcrime.securesms
Uid mode: COARSE_LOCATION: foreground
FINE_LOCATION: foreground
READ_CALENDAR: ignore
WRITE_CALENDAR: ignore
CALL_PHONE: ignore
READ_SMS: ignore
RECEIVE_SMS: ignore
RECEIVE_MMS: ignore
SEND_SMS: ignore
CAMERA: ignore
RECORD_AUDIO: ignore
READ_EXTERNAL_STORAGE: ignore
GET_ACCOUNTS: ignore
READ_MEDIA_AUDIO: ignore
READ_MEDIA_VIDEO: ignore
READ_MEDIA_IMAGES: ignore
LEGACY_STORAGE: ignore
COARSE_LOCATION: allow; rejectTime=+10m2s798ms ago
FINE_LOCATION: allow; time=+22m28s686ms ago; rejectTime=+10m2s798ms ago
READ_CONTACTS: allow; time=+1h21m59s999ms ago
WRITE_CONTACTS: allow; time=+1d4h51m54s635ms ago
WRITE_SMS: ignore; rejectTime=+1d5h0m6s660ms ago
SYSTEM_ALERT_WINDOW: default; rejectTime=+4h32m51s116ms ago
WRITE_CLIPBOARD: allow; time=+1d4h49m47s475ms ago
WAKE_LOCK: allow; time=+10m2s174ms ago; duration=+395ms
READ_PHONE_NUMBERS: allow; time=+1d5h0m6s660ms ago
RUN_ANY_IN_BACKGROUND: allow
START_FOREGROUND: allow; time=+7m35s714ms ago (running)
ACCESS_RESTRICTED_SETTINGS: allow; time=+1d3h43m7s68ms ago

And I do READ_EXTERNAL_STORAGE to allow.
I think the problem Comes from a Huawei P9 Lite with internal memory on SD card. It was adopted with the Smart Switch app.
On 29./30. I dry more: account to another Cellphone, new install Signal, backup test with neu account.

**Comment by clauz9** [comment]
Well here's what I have... 

```

Uid mode: COARSE_LOCATION: foreground
FINE_LOCATION: foreground
READ_CALENDAR: ignore
WRITE_CALENDAR: ignore
CALL_PHONE: ignore
READ_SMS: ignore
RECEIVE_SMS: ignore
RECEIVE_MMS: ignore
SEND_SMS: ignore
CAMERA: ignore
RECORD_AUDIO: ignore
READ_EXTERNAL_STORAGE: ignore
GET_ACCOUNTS: ignore
READ_MEDIA_AUDIO: ignore
READ_MEDIA_VIDEO: ignore
READ_MEDIA_IMAGES: ignore
LEGACY_STORAGE: ignore
COARSE_LOCATION: allow
FINE_LOCATION: allow; time=+5m47s16ms ago; rejectTime=+9m23s883ms ago
READ_CONTACTS: allow; time=+3m33s515ms ago
WRITE_SMS: ignore; rejectTime=+6m13s161ms ago
SYSTEM_ALERT_WINDOW: default; rejectTime=+6m18s391ms ago
CAMERA: allow; time=+1d0h59m59s740ms ago; duration=+1s747ms
READ_CLIPBOARD: allow; time=+3h58m59s832ms ago
WRITE_CLIPBOARD: allow; time=+4d0h21m9s511ms ago
WAKE_LOCK: allow; time=+2m59s620ms ago; duration=+2s676ms
GET_USAGE_STATS: default; rejectTime=+11s886ms ago
READ_PHONE_NUMBERS: allow; time=+6m13s161ms ago
START_FOREGROUND: allow; time=+17s664ms ago (running)
WRITE_MEDIA_AUDIO: deny; rejectTime=+1d0h36m40s88ms ago
MANAGE_EXTERNAL_STORAGE: default; rejectTime=+1d0h36m40s89ms ago
ACCESS_RESTRICTED_SETTINGS: allow; time=+11m56s360ms ago
```

The only thing that I can see that might make a difference is the `MANAGE_EXTERNAL_STORAGE` permission.. 

so since you seem comfortable using ADB, can you try 

`adb shell appops set --uid org.thoughtcrime.securesms MANAGE_EXTERNAL_STORAGE allow` 

And see if that fixes anything 🤔  

When you run the ADB command make sure, there's only one phone connected to the PC, otherwise you need to specify which device to run the command on.

**Comment by Paulchen232** [comment]
Ok, I dry this later. I say If anything fixes.

**Comment by Paulchen232** [comment]
I have let MANAGE_EXTERNAL_STORAGE set to allow. That probably means all files access.
Backup not working.
I'll try again something on the 29th/30th.

**Comment by clauz9** [comment]
Read this 

https://github.com/signalapp/Signal-Android/issues/12915#issuecomment-1624078250

**Comment by Paulchen232** [comment]
One more thing: I've seen that in the diagnostic log this often occurs with different stickers:
`java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_stickers/sticker...` Do you know how this is possible?

With another mobile phone where everything works, it is not in the "All files access" list either.

**Comment by clauz9** [comment]
Signal is not there, but "external storage" should be, have you looked at the screenshot ?

**Comment by Paulchen232** [comment]
Very very nice, now I have anderstand what to do. I see external storage with System-Apps. External storage call in German: externer Speicher. It is now on and the Backup work! I have explane it my mother with Telegram because shy must do it. 

Many thanks!

**Comment by Paulchen232** [comment]
The message of success came from my mother! 🙂
