### ISSUE TITLE
Signal crashes when trying to generate a link preview for https://…

### ISSUE THREAD

**Issue by l3u** [signalapp/Signal-Android#12998]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Short story: I typed "I just registered some-domain.de, this may take a while until it's through the DNS. As soon as it points to my server, I'll register a Let's encrypt cert so that https://… will work".

Signal tried to create a link preview for "https://…" (with an ellipsis char, not three dots) and crashed. I worked around this by disabling link previews and editing the draft.

### Steps to reproduce
Type "https://…" (with an ellipsis char, not three dots) and see Signal crash trying to create a link preview

### Device info
**Device:** Motorola moto g42
**Android version:** 12
**Signal version:** 6.12.3

**Comment by l3u** [comment]
Uploading did not work, so here we are:
[signal-log-1686559927126.zip](https://github.com/signalapp/Signal-Android/files/11720760/signal-log-1686559927126.zip)
I opened it just now, but it contains the crash.

**Comment by l3u** [comment]
Thanks for the quick reply and for fixing this!

**Comment by nicholas-signal** [comment]
For those curious: this has to do with how OkHttp detects hostnames in their IP address detection method (like "8.8.8.8") and how it gets confused by a bunch of dots in a row.
