### ISSUE TITLE
message body ends up unredacted in Signal log when sqllitedatabase error occurs

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12991]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just noticed that some logs actually contain message text. That's not ok! That's obviously private. It happens whwn SQLlite throws an error, it will also throw body=

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Redact the entire body, prevent it from ending up in the log

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by cody-signal** [comment]
This bug with SQLCipher exceptions in debug logs has been fixed (https://github.com/signalapp/sqlcipher-android/commit/247c46de5898b7922140cac49b3d8ce0a57a474e). Thanks for letting us know.

Out of an abundance of caution, all legacy Android debug logs have been fully cleared, and submitting new debug logs from old Signal Android versions is no longer possible.
