### ISSUE TITLE
Chat backup feature doesn't work in Waydroid, Windows Subsystem for Linux and in Android emulators

### ISSUE THREAD

**Issue by xXRealXxx** [signalapp/Signal-Android#12995]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to restore chat backups via the .backup file, my chats do not get restored. Only two group chats get restored, which didn't have any messages exchanged in to begin with (and don't have any messages in them after the restoration). However, I have chats with 11 people (13 if we count Notes to Self and Signal's official messages). These chats, which I actually care about, don't get restored. It's strange that those two groups get restored, because I specifically deleted them from my Signal app on my phone so that they don't get restored (yes, I tried restoring multiple times). Here's what I was doing:
- I've installed the Signal apk from Signal's official website in Waydroid that's running on Linux Mint 21.1 with the GNOME Desktop Enviroment.
- I've generated a chat backup from my Poco X3 Pro phone running MIUI 13.0.1 (that's Android 12). The generated backup is recent, it was generated immediately before the restoration attempt in Waydroid.  
- I tried to restore the generated .backup file on the newly installed Signal in Waydroid.
- It asked for my numeric passphrase. I typed it in, but it said that it's incorrect, even though I typed it in correctly.
- I pasted in the numeric passphrase, but it still said that the passphrase is incorrect (but it is correct, I checked the passphrase on the Signal app that's installed on my phone, and it said it is correct). 
- I pressed the home button on the navigation bar, and when I came back to Signal, it said that restoration was complete.
- Then it asked for my phone number, then to complete hcaptcha, then my phone number AGAIN, then the SMS verification code, and after that my registration PIN. 
- After registering was successful, only two (deleted before the backup file generation) group chats were restored, but not my other chats.
I've noticed that after this "restoration", Signal's app data on Waydroid takes up only ~150 MB, but the actual backup file is 21.1 GB. 

### Steps to reproduce
- Generate the chat backup file from the device you want to migrate from.
- Try restoring the chat backup file on Waydroid.
- See the failure for yourself.

**Actual result:** Chats don't get restored, except for two chat groups.
**Expected result:** ALL chats get restored.

### Device info
**Device:** Xiaomi Poco X3 Pro, Dell Inspiron 3542 (Linux Mint 21.1 with GNOME DE, Waydroid) 
**Android version:** 12 (11 on Waydroid)
**Signal version:** 6.21.3 (same version on both my phone and Waydroid)

### Link to debug log
https://drive.google.com/file/d/1I2gYSdrYxel4z47q_DxGahBqghoZVYz_/view?usp=sharing
(google drive link because the submit button didn't work in Waydroid)

**Comment by xXRealXxx** [comment]
Tried this on Windows Subsystem for Android, I get the same issue as described above on Waydroid.
Here's the debug log: https://debuglogs.org/android/6.22.8/32f89156c6dc21155db7b96fb73b9e6981b90a7ac5e56a1d2b98397a3473a7ba

**Comment by xXRealXxx** [comment]
> Do you happen to know if these chats are expiring chats? I believe the way backup works, expiring messages get dropped.

No, they are not expiring chats.

**Comment by xXRealXxx** [comment]
bump

**Comment by greyson-signal** [comment]
I don't think we can commit to supporting Waydroid, apologies.
