### ISSUE TITLE
Crash when committing data from transfer to new phone ("Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress")

### ISSUE THREAD

**Issue by Crazywater** [signalapp/Signal-Android#12992]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When transferring data to a new Phone, Signal crashes after the transfer completes. Reopening Signal on the new phone looks like a fresh install, but after going through the regular setup flow with a phone number and PIN the messages do appear.

The exception seems to be the following:
```
06-09 18:53:54.598 29507 29627 E AndroidRuntime: FATAL EXCEPTION: Thread-2
06-09 18:53:54.598 29507 29627 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 29507
06-09 18:53:54.598 29507 29627 E AndroidRuntime: java.lang.IllegalStateException: Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress.  Finish all transactions and release all active database connections first.
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.reconfigure(SQLiteConnectionPool.java:291)
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.setForeignKeyConstraintsEnabled(SQLiteDatabase.java:2177)
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:300)
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at org.thoughtcrime.securesms.devicetransfer.newdevice.NewDeviceServerTask.run(NewDeviceServerTask.java:52)
06-09 18:53:54.598 29507 29627 E AndroidRuntime: 	at org.signal.devicetransfer.NetworkServerThread.run(NetworkServerThread.java:97)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: java.lang.IllegalStateException: Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress.  Finish all transactions and release all active database connections first.
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.reconfigure(SQLiteConnectionPool.java:291)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.setForeignKeyConstraintsEnabled(SQLiteDatabase.java:2177)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:300)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at org.thoughtcrime.securesms.devicetransfer.newdevice.NewDeviceServerTask.run(NewDeviceServerTask.java:52)
06-09 18:53:54.599 29507 29627 E SignalUncaughtException: 	at org.signal.devicetransfer.NetworkServerThread.run(NetworkServerThread.java:97)
```

### Steps to reproduce
- Open a fresh Signal install on the new phone
- Go through the import flow on both phones
- Wait for copy to complete to 100% (>130k messages in my case)

**Actual result:** Copy completes but then Signal crashes immediately on the new phone
**Expected result:** Signal does not crash and data is successfully imported.

### Screenshots
N/A

### Device info
**Device:** Transferring from Moto G10 to Pixel 6a
**Android version:** Transferring from 11 to 13
**Signal version:** 6.21.3 on both devices

### Link to debug log
Grabbed via ADB, attached as txt file:
[logcat.txt](https://github.com/signalapp/Signal-Android/files/11708568/logcat.txt)

**Comment by Crazywater** [comment]
Update: Going through the regular setup flow after restarting Signal (confirming via SMS code and entering PIN) works, the messages seem to have been copied successfully.

**Comment by derMart** [comment]
As @GraphiteSprite is pointing out there are several instances when foreign key constraints can't be disabled.
OP has it in `SignalDatabase.runPostBackupRestoreTasks` while @GraphiteSprite has it in `FullBackupImporter.importFile`. This also looks like a hard to tackle problem to me, as it seems to happen only non deterministically...
