### ISSUE TITLE
Videcall rotation issue. makes my phone screen fizzy just like as it would develop a hardware issue.

### ISSUE THREAD

**Issue by Assimilator-X** [signalapp/Signal-Android#13009]
Video call screen rotation totally ignores global android settings. most annoying is this, The sensitivity is way way too high and vhen i  all someone when i am.driving, every single bump sets it off. I habe factory reseted my pho e because it was looked exactly the same as my device developed a hw fault. And i have been told that is nothing wrong with it. I wi stop using signal at this point thank you.As i have see that is a long ongoing issue by now. I dont know why this idoot settings needs to ig ore the system settings at all.

**Comment by cody-signal** [comment]
We respect the system setting on auto rotate being enabled/disabled and will only rotate if it's enabled.
