### ISSUE TITLE
Front camera is too dark

### ISSUE THREAD

**Issue by pippi1otta** [signalapp/Signal-Android#13005]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When taking a photo or video in-app, with the front/selfie camera, the image is too dark.
Both during the preview, and in the final result.
When using the back camera the brightness is normal (like in the built-in camera app).

### Steps to reproduce
- open a chat with someone
- tap the camera icon at the right end of the message input field
- make sure the front/selfie camera is active
- tap (or hold) the shutter button to take a photo (or video)

**Actual result:** The image is way too dark. Both during preview and in the final result.
**Expected result:** The brightness should be the same as in the built-in camera app.

### Device info

**Device:** Samsung Galaxy A13
**Android version:** 12
**Signal version:** 6.22.8

### Link to debug log

https://debuglogs.org/android/6.22.8/713b7f31a16203b42d7b5fc389cf305ac50f88b0e3ccf24b974f9b691b4c68ae

**Comment by nicholas-signal** [comment]
We use Google's [CameraX](https://developer.android.com/training/camerax) library to handle device-specific camera compatibilities. We recently updated to the 1.3.0 version; would you mind retesting? Thanks!

**Comment by pippi1otta** [comment]
@nicholas-signal It doesn't happen anymore.

Thank you!
