### ISSUE TITLE
Receiving or making a Signal call while global microphone access is denied should ask user for microphone access

### ISSUE THREAD

**Issue by hecd** [signalapp/Signal-Android#13019]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Receiving or making a Signal call while global microphone permissions (introduced in Android 12) does not prompt the user to grant global microphone access. This happens when recording a Signal audio message with the popup message "Unlock device microphone? This unblocks access for all apps and services allowed to use your microphone"). Note: the bug appears even if microphone permission has been granted to the Signal app. The problem occurs when microphone access is globally turned off. See https://community.signalusers.org/t/silent-voice-message-is-recorded-without-a-warning-when-microphone-access-is-blocked/51566/6 for similar resolved issue when recording a voice message.

### Steps to reproduce
- disable microphone access using Quick settings. See https://www.howtogeek.com/733911/how-to-disable-the-mic-and-camera-from-androids-quick-settings/
- receive or make a Signal call

**Actual result:**  the microphone is not recording and the other call participant will not hear you since the microphone access is denied without any visual indication - not user experience intuitive). See screenshot 1 for visual presentation of global microphone tile when microphone access is blocked globally.
**Expected result:** a popup asking if the user wants to allow microphone access should appear in the same way as if recording an audio message and the microphone . After granting global microphone access microphone access tile should look like screenshot 2 and microphone will be used in the Signal call.

### Screenshots
1. 
![hold-and-drag-camera-and-mic-tiles](https://github.com/signalapp/Signal-Android/assets/25802566/eff54859-28a1-4901-b3ae-00c5dd283678)
2.
![quick-settings-access-tiles](https://github.com/signalapp/Signal-Android/assets/25802566/7313abfc-a75a-4a67-9271-784b9779e4a5)

 

### Device info

**Device:** Pixel 7
**Android version:** 13
**Signal version:** 6.23.5

**Comment by nicholas-signal** [comment]
Google specifically blocks apps from detecting if the mic/camera has been disabled via the Quick Toggle, a policy you can read more about here: https://developer.android.com/training/permissions/explaining-access#toggles

Google's intended behavior is that the OS prompts the user to re-enable the toggle, behavior which I have verified works for Signal on my Pixel 6a:

![Screenshot_20230829_145219](https://github.com/signalapp/Signal-Android/assets/112583042/73d294f7-8b9c-43de-94ad-07c3f8187128)

**Comment by SivaG3161Optisol** [comment]
Hi @nicholas-signal 
I am just in need of some clarification on this statement : "Google's intended behavior is that the OS prompts the user to re-enable the toggle, behavior which I have verified works for Signal on my Pixel 6a:"

what if the user denies, the microphone permission , when it is globally disabled. is there any way to get the state of microphone access toggle so that i can re-request the permission or else restrict the user to get access to functionalities related to microphone.
