### ISSUE TITLE
Can't talk over each other during a video call

### ISSUE THREAD

**Issue by leg7** [signalapp/Signal-Android#13013]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If me and the person I'm video calling start talking over each their audio will stop coming through and I won't be able to hear them. 

### Steps to reproduce
- Video call someone
- Start talking at the same time as them

**Actual result:** Can't hear them
**Expected result:** I should be able to hear what the person is saying

### Device info
**Device:** Google Pixel 6
**Android version:** 13 (grapheneOS)
**Signal version:** 6.23.5

### Link to debug log
I don't have one sorry

**Comment by rashad-signal** [comment]
I tried to reproduce this, also on a video call on a Pixel 6 with Graphene OS (using Android 13 as well), and things worked fine for me, so I was wondering if you could provide more info?

Debug logs from both devices in the call would be ideal if you could try again and are willing to provide them (if you don't want to post them here, you can email them to me at rashad@signal.org). Other things that would be useful to know are:
1. What mic / speaker were used for the call? The built-in ones, or something external?
2. What device was the other person using?
3. Do you know if the other person also couldn't hear you when you were both talking?

**Comment by leg7** [comment]
I just saw your response and have not tried to get debug logs since but it happened again yesterday. We are both using the built in microphones of our phones and this happened when the other person uses an android phone or an iphone 8. The other person tells me they can hear me and this bug does not affect them. I don't know if they are being accurate though since they are not very tech savy and it's possible they haven't noticed the issue.

I don't think it happens all the time when talking over each other but if you are in a video call long enough and talk over each other you will notice it a couple times.
