### ISSUE TITLE
Links including accented characters in URL are not working

### ISSUE THREAD

**Issue by tvass** [signalapp/Signal-Android#13011]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Links that include an accent (eg: with the char "é") are not clickable. 

### Steps to reproduce
- Send a message with a url that include é  (eg: https://xn--multipli-i1a.fr/en/)

### Screenshots
![Capture d’écran, le 2023-06-19 à 13 04 36](https://github.com/signalapp/Signal-Android/assets/1489618/7b21f0ea-d873-4a71-ae5e-4dcfac16c15c)

### Device info
**Device:** Samsung S23
**Android version:** 13
**Signal version:** 6.22.8

### Link to debug log
[log](https://debuglogs.org/android/6.22.8/e9597844e7e099bd26694b7c6cdb2f47bb31261aa8c94625549e0f0a7ebda7f9
)

**Comment by fwinn** [comment]
Same problem with ä ö ü characters, although there are valid URLs with these characters, see for example https://bayerische-bierkönigin.de/
