### ISSUE TITLE
Camera is on even when I "Answer without video"

### ISSUE THREAD

**Issue by pippi1otta** [signalapp/Signal-Android#13010]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When answering a video call with the "without video" button, the camera is on, while it should be off. This happens always.

### Steps to reproduce
- lock your screen
- have someone video call you
- press the "Answer without video" button in the middle

**Actual result:** the camera is on
**Expected result:** the camera should be off

### Device info

**Device:** Xiaomi Redmi Note 11 Pro
**Android version:** 13
**Signal version:** 6.24.0

### Link to debug log

https://debuglogs.org/android/6.24.0/d502381d004db87230fe443cd0ffaad1694600605d74f1fc10b1609328c624ec

**Comment by pippi1otta** [comment]
Thank you very much, too!

**Comment by nicholas-signal** [comment]
I believe this was addressed by 1bdc77affed5fe1770efc706c2a51a1b7fb2705f

Can you confirm this is fixed on your end?

**Comment by pippi1otta** [comment]
@nicholas-signal Yes, it works now.

Thanks for the fix!
