### ISSUE TITLE
App crasing after an update

### ISSUE THREAD

**Issue by kakxow** [signalapp/Signal-Android#13018]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app crashes after the latest update on my old phone.
I have no backups, so I did not try to reinstall.

### Steps to reproduce
- Launch an old version (from around October 2022).
- Update to the latest version.
- Update google play services.
- Launch an app.

**Actual result:** The crash occurs after a few seconds of black screen when launching an app.
**Expected result:** App working as normal.

### Screenshots

No meaningful screenshots available.

### Device info

**Device:** Xiaomi mi A1
**Android version:** 9
**Signal version:** 6.20.5

### Link to debug log
log from adb logcat, I hope I've pasted everything relevant there
https://pastebin.com/WDib5y9s

**Comment by codeonblocks** [comment]
The last update is a buggy mess. I'm having all sorts of bugs with it as well.

**Comment by greyson-signal** [comment]
I believe the specific crash instance you hit was addressed a while back. If it wasn't feel free to post another debuglog. Thanks!
