### ISSUE TITLE
Voice Message High Bitrate. Android 12.

### ISSUE THREAD

**Issue by piratOLD** [signalapp/Signal-Android#13025]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice messages too high bitrate. I communicate in a signal with voice messages and I can't understand why the bitrate of voice messages depends on the android version. On android version 9 voice messages are low bitrate and take up little space, but voice messages on android 12 take up five times as much space. 41 seconds takes up 988 kilobytes on android 12. 46 seconds takes 196 kilobytes on android 9. I am very frustrated that different android versions for some reason have different bitrates of voice recordings and correspondingly different sizes and the backup will take up to five times more space than it could if the voice messages were with the same bitrate on all android versions. Please fix this.

### Device info
**Device:** Xiaomi Redmi Note 9
**Android version:** 12
**Signal version:** 6.23.5 Play Store and Apk install (Stable), 6.24.x Play Store (Beta)

**Comment by greyson-signal** [comment]
I don't know why the file sizes are different, but we always use the same sample rate and bitrate independent of OS version.

**Comment by piratOLD** [comment]
If I send you the log, will it help you figure out what's wrong?

**Comment by piratOLD** [comment]
> I don't know why the file sizes are different, but we always use the same sample rate and bitrate independent of OS version.

If I send you the log, will it help you figure out what's wrong?

**Comment by greyson-signal** [comment]
Couldn't hurt, we can see if there's anything interesting

**Comment by piratOLD** [comment]
> Couldn't hurt, we can see if there's anything interesting

https://debuglogs.org/android/6.23.5/cd7db1c22981a0b38388c695f7be81481e2288bcb2ec1fb0ac5625f777773ff1

**Comment by piratOLD** [comment]
> Couldn't hurt, we can see if there's anything interesting

In general, asked to send a voice message from another phone with android 12 and there everything was correct. The bitrate is low. The phones are from the same company, but the thing is that the chips in them are different. Where the voice messages are five times bigger in the phone (redmi note 9) the chip is from Mediatek and where everything is fine the chip is from Qualcomm (poco x3 nfc). Maybe it depends on the chip. Somehow wrong android processes or something else. Please check voice messages on chips from Mediatek if there is such a possibility.

**Comment by nicholas-signal** [comment]
Hello! According to some back-of-the-napkin math, the Qualcomm phone is putting out a file with a bitrate of ~34,000 bits/s, which is reasonably close to the 32,000 bit/s that Signal requests of the phone: https://github.com/signalapp/Signal-Android/blob/e7f8d3619960dac1cf5262099729f202cd22953b/app/src/main/java/org/thoughtcrime/securesms/audio/MediaRecorderWrapper.java#L21

The MediaTek chip seems to be outputting ~192,000 bit/s, which is way over what our app is specifying.

I believe you are correct: this is a bug in the MediaTek phone.

**Comment by piratOLD** [comment]
> Hello! According to some back-of-the-napkin math, the Qualcomm phone is putting out a file with a bitrate of ~34,000 bits/s, which is reasonably close to the 32,000 bit/s that Signal requests of the phone:
> 
> https://github.com/signalapp/Signal-Android/blob/e7f8d3619960dac1cf5262099729f202cd22953b/app/src/main/java/org/thoughtcrime/securesms/audio/MediaRecorderWrapper.java#L21
> 
> The MediaTek chip seems to be outputting ~192,000 bit/s, which is way over what our app is specifying.
> 
> I believe you are correct: this is a bug in the MediaTek phone.

Can you fix this in the app so voice messages don't take up so much space with the Mediatek chip?

**Comment by nicholas-signal** [comment]
Unfortunately that is up to Mediatek. As just an app on the phone, Signal cannot override the chip's behavior.

**Comment by piratOLD** [comment]
> Unfortunately that is up to Mediatek. As just an app on the phone, Signal cannot override the chip's behavior.

I'm just wondering how other messengers solve these problems? Other messengers don't have such problems with unification of voice recordings. The Session app (a fork of Signal) uses aac in voice messages and there is no problem with different bitrates. The bitrate is the same on Qualcomm and Mediatek.

https://github.com/oxen-io/session-android

**Comment by nicholas-signal** [comment]
Session never merged the work we did to use the supported MediaRecorder API on Android 8.0+ devices: https://github.com/signalapp/Signal-Android/commit/b04ae3a8b3e0a4e7f015cf3a29a925fd076876ec

This was to use the [MediaRecorder API](https://developer.android.com/guide/topics/media/mediarecorder) because on Android 8.0+, we need to be using this API to encrypt the data **before** it is saved to the phone's storage.

In your particular case, it would appear the older API is not bugged on your MediaTek device, and the new one is.

**Comment by piratOLD** [comment]
> Session never merged the work we did to use the supported MediaRecorder API on Android 8.0+ devices: [b04ae3a](https://github.com/signalapp/Signal-Android/commit/b04ae3a8b3e0a4e7f015cf3a29a925fd076876ec)
> 
> This was to use the [MediaRecorder API](https://developer.android.com/guide/topics/media/mediarecorder) because on Android 8.0+, we need to be using this API to encrypt the data **before** it is saved to the phone's storage.
> 
> In your particular case, it would appear the older API is not bugged on your MediaTek device, and the new one is.

Thanks for the explanation.

**Comment by piratOLD** [comment]
> Session never merged the work we did to use the supported MediaRecorder API on Android 8.0+ devices: [b04ae3a](https://github.com/signalapp/Signal-Android/commit/b04ae3a8b3e0a4e7f015cf3a29a925fd076876ec)
> 
> This was to use the [MediaRecorder API](https://developer.android.com/guide/topics/media/mediarecorder) because on Android 8.0+, we need to be using this API to encrypt the data **before** it is saved to the phone's storage.
> 
> In your particular case, it would appear the older API is not bugged on your MediaTek device, and the new one is.

May I ask why you chose the aac codec for voice messages instead of ogg?
With the ogg codec there is no problem between soc in bitrate. It's not very convenient when there are different file sizes and there is no unification of voice messages.

**Comment by nicholas-signal** [comment]
AAC is more compatible with other platforms, especially Apple devices.
