### ISSUE TITLE
Unable to connect to server when registering phone number

### ISSUE THREAD

**Issue by adriandelgg** [signalapp/Signal-Android#13027]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I try to sign in using my phone number it doesn't work and it pops up an error message saying:
"Unable to connect to service. Please check network connection and try again."

### Steps to reproduce
- Download Signal
- Enable permissions
- Put phone number in and click "Continue"

**Actual result:** Pop up saying "Unable to connect to service. Please check network connection and try again."
**Expected result:** Should take me to the next page to verify my number.

### Device info

**Device:** Google Pixel 6
**Android version:** 13
**Signal version:** 6.23.5

**Comment by greyson-signal** [comment]
Can you please share a debuglog? During registration, you can tap the header text on any screen 8 times and it should prompt you to submit a debuglog.
