### ISSUE TITLE
Misleading text about clearing message history

### ISSUE THREAD

**Issue by Pikari0** [signalapp/Signal-Android#13022]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was cleaning my phone, I've done a Signal backup and I tough it was time to delete my message history.
After passing the pop-up saying it will delete "all message history" I end up on a screen with no conversation at all. 
I wasn't expecting this, I was thinking I will end up with all my conversations on Signal conversations list but empty.
All the pop-up texts talk about "message history" and not about removing the conversations themselves.
Now the only way to have my group chat back is waiting for someone to post a message in it or load my backup.

### Steps to reproduce
- go into the settings
- go into "Data and storage"
- Tab on "Manage storage"
- Tab on "Clear message history"
- Pass the pop-ups
- Now your conversation list is empty

**Actual result:** No conversations in the conversations list
**Expected result:** All my previous conversations in the conversations list but all of them empty

### Screenshots
![image](https://github.com/signalapp/Signal-Android/assets/36168520/d4d85dd9-165e-4032-bcac-5e572a0c225d)
![image](https://github.com/signalapp/Signal-Android/assets/36168520/30db1cf3-e148-4c15-af2d-af72c241d425)
![image](https://github.com/signalapp/Signal-Android/assets/36168520/d17dbe1d-9954-4c53-9b63-cdacce56fe1b)

**Comment by UserX404** [comment]
Your chats has been emptied and so they aren't shown in the overview till they have new content.
You should be able to find your contacts and groups by clicking the pencil button and search for them.

**Comment by Meteor0id** [comment]
This is a long standing issue. Groups of which you are a member should never be cleared from your chat kist, but unfortunately Signal has not yet learned that lesson.

**Comment by greyson-signal** [comment]
Different users will have different expectations of this screen. Many people use this as a way to have a "clean slate" -- they don't want a single trace of past conversations showing up in the chat list. I'll see if we can improve clarity here at all.

**Comment by Meteor0id** [comment]
@greyson-signal people who want a clean slate do not want random groups from the past to suddenly show up again because they unknowingly were still a member and a new message has been send to the group.

Currently:
Group chats disappear from rhe chat list but you are still a member

Expected either one if these two:
1. You automatically leave groups when you clear them out of the chat list
2. You stay in the group and the group still shown in your chat list (even if there are no messages in it). You can still archive, mute, leave or block the group, or manage the group if you are the admin.

**Comment by Meteor0id** [comment]
Still a relevant issue

**Comment by Pikari0** [comment]
Maybe for now if the behavior is not changed, the text can ?
Before : "This will permanently delete all message history and media from your device."
After : "This will permanently delete all message history and media from your device. Your conversation list will be empty until someone send you a new message."

**Comment by gabefair** [comment]
> @greyson-signal people who want a clean slate do not want random groups from the past to suddenly show up again because they unknowingly were still a member and a new message has been send to the group.

See https://community.signalusers.org/t/list-oneselfs-group-memberships/59739
