### ISSUE TITLE
Chat bubbles instantly dismiss when opened 

### ISSUE THREAD

**Issue by Zarozz** [signalapp/Signal-Android#13032]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive a signal message I get a notification and the chat bubble pops up, the bubble works normally and I can see part of the message when the bubble pops up. 
When I click the chat bubble, the conversation opens for a split second then dismisses, the signal chat bubble menu stays open but the chat is gone. 

### Steps to reproduce
- receive a signal message with chat bubbles enabled
- click the chat bubble ( see screenshot 1)

**Actual result:** 
- bubble opens and I can see the chat, then immediately closes
- empty bubble window remains ( see screenshot 2)
**Expected result:** 
The bubble opens and I can see and reply to messages, the bubble does not close until I dismiss it or click away

### Screenshots

![Screenshot_20230626_224059_Chrome](https://github.com/signalapp/Signal-Android/assets/5660235/455842a3-fb0e-4dad-a449-45b54350ee9a)

![Screenshot_20230626_224107_Chrome](https://github.com/signalapp/Signal-Android/assets/5660235/0f1cb66c-2708-41de-b63b-c40d162fa2e1)

### Device info

**Device:** Samsung Galaxy S10
**Android version:** Android 12
**Signal version:** 6.24.3

### Link to debug log

https://debuglogs.org/android/6.24.3/7776715f42272f7bcbc8dde821fec2fc7288688fcbe134e54fce22db1dd5c17c

**Comment by Nahhoppla** [comment]
I have a similar bug since the new chat Format update my chat bubble instandly closes after opening and the chat got read automatically. Restarting the phone didn't helped and i cant even deactivate the bubble cause it closes too fast

Device: Redmi Note 8 Pro 
Android version 11 
Signal Version 6.24.4

**Comment by Sev455** [comment]
I have the same issue.
One plus GM1917
Android 12
Signal 6.24.4

**Comment by nicholas-signal** [comment]
Hello everyone,

I reverted a change I made for the Bubble logic, and it is currently in testing in the 6.25 beta.

You can participate in the beta program on our community forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-25-release/54207/17

Let me know if it helps!

**Comment by Nahhoppla** [comment]
I downloaded the apk via firebase, (after seeing google has with beta on no update available) and now it works again! Thanks for your help!

**Comment by Brandieee** [comment]
On 6.24.4

My observation has been that my four previously pinned chats bubble correctly and have the option to create bubbles from the three-dots interface of the conversation.

All other conversations experience the above behaviour, pinning new conversations does not help and unpinning previously pinned and working conversations doesn't break bubbling either.

**Comment by Zarozz** [comment]
> Hello everyone,
> 
> I reverted a change I made for the Bubble logic, and it is currently in testing in the 6.25 beta.
> 
> You can participate in the beta program on our community forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-25-release/54207/17
> 
> Let me know if it helps!

Just got the new version and it's working now. Thanks so much!

**Comment by Sev455** [comment]
> Hello everyone,
> 
> I reverted a change I made for the Bubble logic, and it is currently in testing in the 6.25 beta.
> 
> You can participate in the beta program on our community forum: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-25-release/54207/17
> 
> Let me know if it helps!

The new version is working for me also.
Thank you!

**Comment by nicholas-signal** [comment]
Sounds like we have enough confirmation that this is fixed in the 6.25 beta release. Therefore I'm closing this GitHub issue.
