### ISSUE TITLE
Backup confirmation not working on Qin F21 Pro

### ISSUE THREAD

**Issue by monstermichl** [signalapp/Signal-Android#13033]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently wanted to setup a new backup of my Qin F21 Pro, but there is no checkbox to confirm that I understood the conditions. I know that it worked seemlessly in the past but now it seems to be broken. **FYI: This phone does not have Google services installed**

### Steps to reproduce
- Open Signal
- Go to Settings
- Go to Chats
- Chat Backups
- Click "Turn on"
- Select a folder for the backup

**Actual result:** No confirmation checkbox gets shown.
**Expected result:** A confirmation checkbox should be shown.

### Screenshots
![Screenshot_20230625-014131](https://github.com/signalapp/Signal-Android/assets/17982894/ada1e98a-9d49-4844-b77b-098caea78441)
![Screenshot_20230625-014149](https://github.com/signalapp/Signal-Android/assets/17982894/883619dc-7e6b-46fd-ae3a-c74bbf10cf36)

### Device info

**Device:** Qin F21 Pro
**Android version:**
![Screenshot_20230626-200929](https://github.com/signalapp/Signal-Android/assets/17982894/3f58d73a-c1ff-4050-8f6c-60832004782f)
![Screenshot_20230626-201532](https://github.com/signalapp/Signal-Android/assets/17982894/6097f38d-795a-4778-ba5d-cbb5118f597c)
**Signal version:** 6.23.5

### Link to debug log
I'm not sure if a debug log would help here. But if, I going to provide it privately.

**Comment by Sgn-32** [comment]
Seems that the text isn't scrollable. I've set the android text size and display size to high and don't see the full popup.
You can try it to set the text size and display size to a lower level.

![Screenshot_1687884294](https://github.com/signalapp/Signal-Android/assets/49990901/0d1b287b-d2ce-4557-94c4-6f44f16f50ae) ![Screenshot_1687884352](https://github.com/signalapp/Signal-Android/assets/49990901/d030bc3a-629e-4f42-ae21-de92192ecfee)

**Comment by monstermichl** [comment]
Thanks for the hint. Unfortunately, the font size on the lowest setting is still to big. Did you try it on the actual phone or an emulator? I don't think I can set the display size on that device.

![Screenshot_20230628-162015](https://github.com/signalapp/Signal-Android/assets/17982894/68c9ada1-c538-4063-b101-128f4b015467)
![Screenshot_20230628-162037](https://github.com/signalapp/Signal-Android/assets/17982894/1f7ee183-38eb-40ab-8a6d-ee223c99b702)

**Comment by Sgn-32** [comment]
In 6.25.0 beta the devs have a commit for the backup enable dialog for smaller screens. If you are not on beta, you have to wait that 6.25.x is released.
