### ISSUE TITLE
Proxy setting is broken

### ISSUE THREAD

**Issue by RedSteel-1** [signalapp/Signal-Android#13045]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Proxy setting is broken and doesn't work.
Not being able to route a messenger to Tor/VPN running on localhost - is a critical issue, especially for a private and secure messenger like Signal.
Please fix this.

### Steps to reproduce
Open Signal, open settings -> data and storage -> proxy,
enter the address where the proxy is running (for example 127.0.0.1:9050),
press Save

**Actual result:** "Failed to connect".
**Expected result:** Connected, and all traffic is routed through it.

### Device info

**Device:** Any
**Android version:** 11-13
**Signal version:** 6.24.4, or any

**Comment by alex-signal** [comment]
Hello, I've confirmed that proxies are working. Can you confirm you're utilizing the correct address? From your steps it appears you're entering localhost. Are you actually running the proxy on the same device you're running Signal on?

**Comment by alex-signal** [comment]
And the proxy running at 127.0.0.1:9050 is set up according to https://signal.org/blog/run-a-proxy/ ?

**Comment by alex-signal** [comment]
That's not how the Signal proxy works :-) You can direct traffic on your device through tor (probably via VPN settings in your devices network config?) but the Proxy setting in Signal is only for connecting to Signal proxies.

**Comment by aspensmonster** [comment]
Note for posterity: The motivation for wanting to have the Signal app only ever attempt connection over a proxy is because Orbot's VPN functionality can break, especially during high memory loads on devices (even if the Always-On option is specified in the Android VPN settings for the Orbot app). This then may cause Signal traffic to instead route over the normal internet, rather than through the VPN that is now offline.
