### ISSUE TITLE
Search for URLs is broken

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#13047]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Searching for portions of an URL or even the whole URL verbatim doesn't yield the expected results. 

When reducing the search token to only a subset of the URL in question (say, just a folder, i.e. the part between slashes), all occurrences in the history are found properly.

### Screenshots

![Image_16123~2](https://github.com/signalapp/Signal-Android/assets/206281/593d5997-911e-4ca4-a50e-9837a9cf860b)

![Project 2~2](https://github.com/signalapp/Signal-Android/assets/206281/af0f0a7b-3edc-4b9e-8f11-8f3c91511ea2)

(Please note that the added space character you see in the second screenshot is not the problem). 

### Device info

**Device:** Google Pixel 4a
**Android version:** 13
**Signal version:** 6.25.2

**Comment by RohanNavlakhe2** [comment]
@alex-signal Should we work on this?
or this is expected behavior?

**Comment by jnns** [comment]
Today I also noticed that searching for email addresses is broken as well:

Given a message only consisting of an email like this
> abcdef@gmx.de

That message is found by the query strings up until `abcdef@gmx.`. The query `abcdef@gmx.d` will not retrieve the message anymore. The same goes for the complete email address as search string.
