### ISSUE TITLE
The contents of a deleted message are displayed in replies despite its deletion.

### ISSUE THREAD

**Issue by M3DZIK** [signalapp/Signal-Android#13046]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The content of the deleted message is shown.

### Steps to reproduce

Let someone send a message and delete it in a while, and you reply as stated below (the same thing happens as you turn off the internet and send before you turn on, etc).

**Actual result:** The content of the deleted message is shown.
**Expected result:** The content should not show up.

### Screenshots

my pov:

https://github.com/signalapp/Signal-Android/assets/87065584/09cff98d-d4d8-4806-b583-d1aff4a5fc06

@gostrdr1337 pov:

https://github.com/signalapp/Signal-Android/assets/87065584/107e56c9-8a05-4cc7-bfc1-ba1ed32e82bd

### Device info
**Android version:** 13
**Signal version:** 6.25.2

**Comment by greyson-signal** [comment]
Hi there, we consider quoted replies to be the equivalent of copy-pasting a message, so this is working as intended.
