### ISSUE TITLE
Text is cut off on transfer confirmation

### ISSUE THREAD

**Issue by TheBicPen** [signalapp/Signal-Android#13040]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- transfer account from device A to device B
- open signal on device A

**Actual result:** text is cut off on popup
**Expected result:** text is not cut off

### Screenshots

![20230701_171044.jpg](https://github.com/signalapp/Signal-Android/assets/23622288/a87882fb-3e86-4c5f-a015-dbbf279af300)

### Device info

**Device:** Samsung Galaxy A8
**Android version:** 9
**Signal version:** 6.23.5

**Comment by MrMak21** [comment]
Hello. I made an investigation and i managed to solve the problem
