### ISSUE TITLE
Very long GC waits, app freezes very often for a minute or so

### ISSUE THREAD

**Issue by awalgarg** [signalapp/Signal-Android#13048]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

All the following tasks take on the order of a minute to complete almost consistently. During this time the signal app is frozen, and sometimes the whole system freezes with it:

- Opening signal
- Opening a chat in signal
- Sending a message

Notes:

1. Relevant section from `adb logcat` shows it spends most of the time waiting for GC (see log below).
2. I have very few chats in Signal, and yet it takes 1.5GB ram, the highest in all the apps I use by a large margin. WhatsApp, with many many more chats and much more usage takes less than 80MB ram (see screenshot below).
3. Signal desktop (on linux) synced to the same account, while slower to start, is actually much more snappy with message sending and image loading being virtually instantaneous.
4. This behavior is not new/version-specific. It's been like this since the beginning, and has gradually worsened over time, presumably as the chat messages have piled up.
5. "Force Stop"-ing the app and restarting helps for a bit, but it soon becomes very slow again.
6. Other apps do not exhibit this behavior. While my phone is a bit slow overall, it's reasonably snappy.

<details>
<summary><code>adb logcat</code></summary>
<pre>
07-07 17:44:09.595 28670 24361 D ConversationViewModel: Starting at position: 0 || jumpToPosition: -1, lastSeenPosition: 0, lastScrolledPosition: 0
07-07 17:44:09.595 28670 28697 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:09.595 28670 28697 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:09.595 28670 28670 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:09.596 28670 24383 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:09.597 28670 28717 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:09.607 28670 18193 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:09.661   632   632 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
07-07 17:44:09.662   632   632 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
07-07 17:44:10.153 28670 28699 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:10.302 28670 28716 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:10.527   803   826 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
07-07 17:44:10.581 28670 28750 I crime.securesm: Waiting for a blocking GC Alloc
07-07 17:44:10.781   788   873 E SDM     : HWCDisplay::GetHWCLayer: [0] GetLayer(32811) failed: no such layer
07-07 17:44:10.781   632   632 W HwcComposer: command 0x3000000 generated error 3
07-07 17:44:10.864   632   632 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
07-07 17:44:13.551  1360  1360 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@f9bd78e
07-07 17:44:10.865   632   632 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
07-07 17:44:13.771 28670 28697 I crime.securesm: Clamp target GC heap from 517MB to 512MB
07-07 17:44:13.771 28670 28697 I crime.securesm: Alloc concurrent copying GC freed 179450(14MB) AllocSpace objects, 8(2MB) LOS objects, 3% free, 493MB/512MB, paused 1.024ms total 4.175s
07-07 17:44:13.771 28670 28670 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 4.175s
07-07 17:44:13.771 28670 28670 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.774 28670 24383 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 4.177s
07-07 17:44:13.774 28670 24383 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.775 28670 24383 D ConversationDataSource: [size(), thread 1] 0 ms
07-07 17:44:13.775 28670 28717 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 4.178s
07-07 17:44:13.775 28670 28717 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.775 28670 18193 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 4.168s
07-07 17:44:13.775 28670 18193 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.778 28670 28699 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 3.624s
07-07 17:44:13.778 28670 28699 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.778 28670 28716 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 3.475s
07-07 17:44:13.778 28670 28716 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.778 28670 28750 I crime.securesm: WaitForGcToComplete blocked Alloc on ProfileSaver for 3.196s
07-07 17:44:13.778 28670 28750 I crime.securesm: Starting a blocking GC Alloc
07-07 17:44:13.832 28670 20767 D ConversationListDataSou: [size(), UnarchivedConversationListDataSource, OFF] 5 ms
07-07 17:44:13.836  1360  1770 I InputDispatcher: Window 'Window{b8fb57b u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}' spent 3310.1ms processing the last input event: MotionEvent
07-07 17:44:13.836  1360  1770 I InputDispatcher: Window 'Window{b8fb57b u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}' spent 3293.4ms processing the last input event: MotionEvent
07-07 17:44:13.836  1360  1770 I InputDispatcher: Window 'Window{b8fb57b u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}' spent 3286.0ms processing the last input event: MotionEvent
07-07 17:44:13.836  1360  1770 I InputDispatcher: Window 'Window{b8fb57b u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}' spent 3277.6ms processing the last input event: MotionEvent
07-07 17:44:13.836 28670 28670 I Choreographer: Skipped 254 frames!  The application may be doing too much work on its main thread.
07-07 17:44:13.837 28670 28670 W FrameRateTracker: Bad frame! Took 4250 ms (255 dropped frames, or 0.24 FPS)
07-07 17:44:13.847 28670 28755 I OpenGLRenderer: Davey! duration=4259ms; Flags=0, IntendedVsync=245121029103364, Vsync=245125262436528, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=245125277766177, AnimationStart=245125277778104, PerformTraversalsStart=245125278148312, DrawStart=245125280410083, SyncQueued=245125281269667, SyncStart=245125281318000, IssueDrawCommandsStart=245125281660240, SwapBuffers=245125285745917, FrameCompleted=245125288589720, DequeueBufferDuration=244000, QueueBufferDuration=414000,
</pre>
</details>

<details>
<summary>Android memory use</summary>
<img src="https://github.com/signalapp/Signal-Android/assets/9100409/2743f8dc-4166-48a9-b891-78b9b3d81e3f">
</details>

### Device info

**Device:** Motorola Payton
**Android version:** 9.0.0 (LineageOS 16)
**Signal version:** 6.23.5

### Link to debug log

Debug log screen takes forever to load, was unable to generate link.

**Comment by awalgarg** [comment]
I'm still facing this issue, even after keeping up with the updates.

**Comment by nicholas-signal** [comment]
> @nicholas-signal Could you help me with how to profile the memory usage of my device?

Our public builds are not built as debuggable, so you would have to download Android Studio and [use the profiler to capture a heap dump](https://developer.android.com/studio/profile/memory-profiler). You could then send the heap dump to us, or dig into it yourself.

I totally understand if this is outside your comfort zone. I also noticed I failed to ask you for a debug log. We should start there: are you able to submit a debug log and paste the URL in this GitHub issue? https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug

Debug logs are, by design, scrubbed of all personally identifiable information before uploading.

**Comment by awalgarg** [comment]
My apologies for the late response, @nicholas-signal. I briefly attempted going the manual debugging route, but yeah that seems to be quite messy, but I'll keep trying.

Here is a debug log: https://debuglogs.org/android/6.40.4/cf8ca7affbf83bd07e509aad9e98ac151374c2b57fc6c10275aaf18ed0402043.
