### ISSUE TITLE
Signal closes immediately after opening chat bubble

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#13055]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have conversation bubbles enabled for Signal on my phone. When a new message arrives, the bubble appears for that chat and I see the message preview, but when I tap the bubble to open the conversation, Signal appears briefly, then immediately closes and the bubble disappears entirely. This gives me the impression that the activity is crashing.

### Steps to reproduce
1. Enable conversation bubbles
2. Get new message
3. Bubble appears
4. Tap bubble

**Actual result:** The bubble "opens" and Signal appears for a few milliseconds, then "crashes" -- the bubble with Signal completely closes and disappears.
**Expected result:** Chat bubble opens and I am able to use Signal normally.

### Screenshots
N/A

### Device info

**Device:** Pixel 7 Pro
**Android version:** 13
**Signal version:** 6.24.4

### Link to debug log
Logs from two separate occurrences of the issue:
https://debuglogs.org/android/6.24.4/e7ca80062492f49899ae5337a02aaefefef9cd75f1b29b972ff5e3c3469d4254
https://debuglogs.org/android/6.24.4/869601a298f9d694006fb169f09117d11435c237fdec8fad462c2638d1b1aead

**Comment by ovdeathiam** [comment]
I've just installed 6.25.5 and it fixed the issue for me. Previously I had the same issue.

**Comment by Herohtar** [comment]
Can confirm it is fixed in 6.25.5
