### ISSUE TITLE
You can't read comments in a story if it is marked as a spoiler.

### ISSUE THREAD

**Issue by M3DZIK** [signalapp/Signal-Android#13052]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can't read the comment when you click and it's like a blank message.

### Steps to reproduce
- make a story
- write a comment and make it as spoiler

### Screenshots

https://github.com/signalapp/Signal-Android/assets/87065584/c84c55d7-a80b-46a8-a3b4-432415a2993b

### Device info
**Android version:** 13
**Signal version:** 6.25.2

**Comment by Asudox** [comment]
> A fix was pushed for this in 6.26, can you try to repro with an updated version when it's available to see if the problem goes away.

I can confirm that indeed this problem is now fixed.

**Comment by M3DZIK** [comment]
Yes, it has been fixed
