### ISSUE TITLE
Link previews display incorrect characters for certain websites

### ISSUE THREAD

**Issue by razieli** [signalapp/Signal-Android#13050]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When entering a URL of certain pages into the message edit field, the link preview text would use an incorrect charset and become unreadable.

This occurs when the page has the charset declared only in the HTML head and is not UTF-8, while the charset in the HTTP response is not explicitly declared.

For example, the website https://rotter.net/ does not have an explicitly declared charset in the HTTP response, but specifies the charset as windows-1255 in the HTML head.

Unlike Signal Desktop (and all major browsers), Signal-Android fails to identify the correct charset and displays the text incorrectly.

### Steps to reproduce
- Enter a URL of a page where the charset is declared only in the HTML head and is not UTF-8 (e.g. https://rotter.net) into the message edit field.
- Wait for link preview to load.

**Actual result:** The non-Latin characters are not encoded correctly, resulting in unreadable text.
**Expected result:** The charset is identified correctly, all the characters are encoded correctly, and the text is readable.

### Screenshots

![image](https://github.com/signalapp/Signal-Android/assets/7279173/b73338da-0036-4cb3-a731-787773439370)

### Device info

**Device:** Samsung S22 Ultra
**Android version:** 13
**Signal version:** 6.24.4

### Link to debug log

https://debuglogs.org/android/6.24.4/0b22eadb7861c8364917dc3feb2a207f36456700a1f7dc090b9acb20c3f643c1

**Comment by nicholas-signal** [comment]
This was fixed thanks to a community contribution. Thanks @razieli!
