### ISSUE TITLE
Non-displayable character at end of messages received from iOS

### ISSUE THREAD

**Issue by chaoscommander** [signalapp/Signal-Android#13066]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every message received from a Signal user on iOS ends with a broken Unicode character (or similar). The remote user doesn't see it.

### Steps to reproduce
- iOS user sends Signal message to Android user, both with most recent version from their respective app stores

**Actual result:** Every message has an additional broken symbol at its end when received
**Expected result:** Only the text that was actually entered and sent is displayed

### Screenshots

![Screenshot_20230718-101146~2](https://github.com/signalapp/Signal-Android/assets/6382352/c37bb530-d155-4b7c-8d72-273e8250e873)

### Device info

**Device:** Fairphone 4
**Android version:** 12 (FP4.SP29.B.069.20230510) 
**Signal version:** 6.25.5

### Link to debug log

Didn't think to capture one when it happened, sorry, will add at next occurrence

**Comment by nicholas-signal** [comment]
Do you know exactly which character it is?

The most likely explanation is it's a new Unicode emoji that was added to iOS.

**Comment by chaoscommander** [comment]
It is not an emoji. My conversation partner showed me that he didn't type anything beyond the actual text. It seems to be the Object Replacement Character: ￼

**Comment by TateWalker** [comment]
Users on Reddit think it might be due to Voice to Text features on iOS. When it happened to me, the sender was driving so could've been using Voice to Text.

**Comment by chaoscommander** [comment]
> Users on Reddit think it might be due to Voice to Text features on iOS. When it happened to me, the sender was driving so could've been using Voice to Text.

Thanks, that was it. We tested, and the extra character appears only when using Speech-to-Text (always at the end of a string spoken in one go).

**Comment by nicholas-signal** [comment]
This should be addressed in the upcoming iOS client release.
