### ISSUE TITLE
Animation Bug unread filter

### ISSUE THREAD

**Issue by Silther** [signalapp/Signal-Android#13073]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The UI for the unread filter has a laggy Animation.
If you swipe fast or sometimes even slow you need to swipe 2 times an the animation "jumps".

### Steps to reproduce
- mark chats as unread
- swipe down (to apply the unread filter)
- swipe down fast to see the buggy animation

**Actual result:**  leaving the unread filter is laggy and needs two swipes

**Expected result:** animation shuoldn't be buggy and you should only need one swipe down to leave the filter

### Screenshots
https://github.com/signalapp/Signal-Android/assets/97352673/2713a386-9741-4e41-bdec-e7180b4fc36f

### Device info

**Device:** Samsung A52s 5G
**Android version:** 13
**Signal version:** 6.26.2

**Comment by nicholas-signal** [comment]
Hi, in looking at your video, it looks like the animation is running but the second swipe just speeds it along. Can you show a video of what happens if you let the "laggy" animation plan out? I want to see the state where it needs two swipes but you only give it one.
