### ISSUE TITLE
Adding members to a group chat adds a different contact if you click on someone who is already in the chat

### ISSUE THREAD

**Issue by devotaaabel** [signalapp/Signal-Android#13070]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you go to add members to a group chat, the contacts that are already in the group chat show in the list, and if you click them, it'll add a different contact. I did this because it's hard to tell the difference between already added members, especially because there's not much contrast in the colors in dark mode, and there's no visual cue other than the toggle button. Also in my case, there was some confusion because members that are invited but haven't joined yet don't show in the group chat, but they do show in the add member screen. I can reproduce this currently on any group chat. Sometimes it happens on the second or third try, but it's consistently reproducible on my end if I keep trying. To be clear, the contact isn't actually added to the group chat when this bug occurs, but they would be if the user clicks done. 

### Steps to reproduce
- open signal
- open a group chat
- click on the overflow to go to group settings
- scroll down and click `Add members`
- click on a member who is already in the group chat. if that doesn't work, click on another contact that is already in the group chat, until you see a little box at the top, adding a different contact than you clicked on.

**Actual result:** A different contact is added to the group chat
**Expected result:** No contact is added, because you clicked on a contact that is already in the group chat

### Screenshots
I'd prefer not to add screenshots of my contacts/group chats. I think the steps above are self explanatory, but please let me know if anything isn't clear.

### Device info

**Device:** Pixel 7
**Android version:** 13.0.0
**Signal version:** 6.24.4, and after updating to 6.25.5 it's still reproducible

### Link to debug log
https://debuglogs.org/android/6.24.4/19602945721314d73a212f876dc6e6f62d0d0d0fb3a7998e1bcdd0d8e422bf6d

**Comment by bhaskarraksahb** [comment]
Can you please confirm that it happens only when there is a contact below already selected one. For example if you have two contacts A and B and A is already in the group. When you try to add A again B gets selected. If there is only one contact within the group(Only one contact with A firstName), the behaviour is expected.

**Comment by devotaaabel** [comment]
Hi @bhaskarraksahb, are you asking if it always adds the next contact after the selected one? If so, the answer is no- if I have contacts A, B, C, D, E, F, G, H, I, J, K, and A and D are already in the group. Clicking on D adds H to the group, and clicking on A adds K (it's seemingly random to me)

**Comment by nicholas-signal** [comment]
I have been able to reproduce this issue, and added it to our bug tracker. Thank you for the report, and we'll post any updates on this GitHub issue!
