### ISSUE TITLE
Voice Message stutters

### ISSUE THREAD

**Issue by MisterIsmed** [signalapp/Signal-Android#13078]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The playback of a voice message that was recorded using signal cannot be understood. Voice is understandable in alternation for a second and then again not. It stutters or was referred to as sound like a robot. Overall not usable for communication. *EDIT:* All other Apps can use the microphone without any problems and record voice messages or use for phone calls.

### Steps to reproduce
- Initiate recording of a voice message
- Speak for any amount of time you want to
- Send message
- Playback message on receiving end

**Actual result:** Voice stutters, sound robotic, cannot be understood what was said.
**Expected result:** Voice message is recorded correctly so it can be understood on the receiving end.

### Device info

**Device:** Asus Zenfone 8
**Android version:** 13
**Signal version:** 6.26.3

### Link to debug log
https://debuglogs.org/android/6.26.3/54715501750a5944a4e2ed12eaec62de90e068b3c7eddff643842a64693fc5db

**Comment by nicholas-signal** [comment]
Please attach a debuglog. Among other things, that will help us see if the phone's operating system displays errors with the audio encoding.

**Comment by MisterIsmed** [comment]
Updated original Post with Info and Link to debuglog.

**Comment by nicholas-signal** [comment]
Hello,

I recently [rewrote the Voice Note Playback code](https://github.com/signalapp/Signal-Android/commit/11cfe5ee824495703b54b74a89ab2b0c76e19afb). Would you mind retesting? If the issue is still present, a new debug log will be helpful.
