### ISSUE TITLE
App crash when trying to access camera on Google Pixel 7a (Android 13)

### ISSUE THREAD

**Issue by mlowdi** [signalapp/Signal-Android#13071]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some kind of app crash happens when I try to access the camera from within the Signal app. I've experimented with removing and adding permissions, etc., to no avail. The logs hint at a "window manager" problem.

### Steps to reproduce
- Open a conversation
- Tap the camera button in the message field

Alternatively

- Open Signal
- Tap the camera icon in the bottom right of the screen

**Actual result:** Conversation closes and I'm back at the conversation list (or in the other case, the app closes)
**Expected result:** Camera UI opens

### Device info

**Device:** Google Pixel 7a
**Android version:** 13 (TQ3A.230705.001)
**Signal version:** 6.26.2

### Link to debug log
https://debuglogs.org/android/6.26.2/b251216783c9720b04fdc0758f29e42b9941c730222f025ce040af24f27e49e2

**Comment by nicholas-signal** [comment]
This crash is fixed in 6.26.3.
