### ISSUE TITLE
App crash on opening a chat

### ISSUE THREAD

**Issue by pushkar-anand** [signalapp/Signal-Android#13079]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Open signal
- Open a specific chat(is a long chat), other chats are working fine
- app crashes

**Actual result:** App Crashes
**Expected result:** Chat screen should open

### Device info

**Device:** Google Pixel 7 (panther)
**Android version:** 13
**Signal version:** 6.27.4

### Link to debug log

https://debuglogs.org/android/6.27.4/597919b02e32bac8b560eb4d591b1573101b64e1ca0122a4e522bd4f6888c6a5

**Comment by cody-signal** [comment]
Fixed in .5, please try updating when you can. Thanks!
