### ISSUE TITLE
Time displayed incorrectly

### ISSUE THREAD

**Issue by snooppr** [signalapp/Signal-Android#13088]
![2023-08-01](https://github.com/signalapp/Signal-Android/assets/61022210/cc90b40c-ff88-4d44-b68c-604a7a5f4367)

![2023-08-01-](https://github.com/signalapp/Signal-Android/assets/61022210/b328899f-f0fe-4c35-939c-51093b5c892f)
Sent at 21.59, read at 21.01.

**Comment by greyson-signal** [comment]
We use the user's local clock to get the time, so things like this can happen. You can see that your clock and your friend's clock are not aligned, since their messages are send after yours but have an earlier timestamp.
