### ISSUE TITLE
Signal Stories fail to send

### ISSUE THREAD

**Issue by deanbigbee** [signalapp/Signal-Android#13085]
### Bug description
When attempting to send Signal Stories, I receive a SEND FAILED error. Tapping to retry does not fix it. Deleting and trying again does not fix it. Have tried with multiple images with no results.

### Steps to reproduce
- Enter Signal Stories tab
- Choose a photo from Library
- Click Send

**Actual result:** SEND FAILED error
**Expected result:** Send Success

### Screenshots
![Screenshot_20230728-104326](https://github.com/signalapp/Signal-Android/assets/42777229/514020a6-3045-48ef-9cae-a842bcee3410)

### Device info

**Device:** Google Pixel 7
**Android version:** Android 13 up to date as of July 27
**Signal version:** 6.26.4

### Link to debug log
[signal-log-1690555553396.zip](https://github.com/signalapp/Signal-Android/files/12195606/signal-log-1690555553396.zip)

**Comment by cody-signal** [comment]
Hi there, thanks for reporting. We found the issue and will be fixing it shortly. In the meantime, you should be able to go into the failed story, tap on it to get additional information on why it failed (looks like a safety number change) and then can resolve that to send again.

**Comment by deanbigbee** [comment]
Thanks Cody. I don't have that option when I click on the failed story, nor by going into the options menu and selecting Info. But glad to hear it will be fixed soon! 
![Screenshot_20230728-155750](https://github.com/signalapp/Signal-Android/assets/42777229/193e2402-03f6-49ef-958c-0191ab521890)

**Comment by cody-signal** [comment]
Huh, that's not right. So guess we have another bug to fix.

This should be working again, the server team pushed out a change that should allow you to send again.

**Comment by Jens14L** [comment]
Signal 6.28.6 crashes on Android 13 (Samsung SM-G988B/DS) when I retry to send my story (e. g. picture or picture + text).

Deleting the story works at first but after an app restart the failed story is back again.

**Comment by cody-signal** [comment]
@Jens14L can you provide a debuglog? Settings->Help->Debuglog

**Comment by Jens14L** [comment]
@cody-signal Yes, here it is: [Debug Log](https://debuglogs.org/android/6.28.6/23b69f835e67bb668b4f2af18e44de6bece6e9174d1da366141926fa88551fd5). Thank you! 🙃

**Comment by Jens14L** [comment]
@cody-signal Story-sending fail and crash fixed for me by v30.4; I had the same problem with beta v30.2.

**Comment by Jens14L** [comment]
What was the issue respectively what’s the fix/commit?

**Comment by muchubatactics** [comment]
I have the same exact issue on a pixel 6, android 13.

**Comment by Jens14L** [comment]
I was wrong. The issue persists. Tested again for my story (all contacts) with v6.31.1.

**Comment by Jens14L** [comment]
Seems to be fixed for me by v6.38.1 or previous versions on Android 13. 👍
