### ISSUE TITLE
Missing Context Menu Options on Text Selection

### ISSUE THREAD

**Issue by ElvenSpellmaker** [signalapp/Signal-Android#13081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Ever since the feature to format text (which is a good feature!) the Select All (and Select) feature of Android has gone missing in the context menus making it hard to select all text.

In fact all, default and app added shortcuts are missing, like a 3rd party app added context menu option or built-ins like "Share"

### Steps to reproduce
- Type some text
- Click on a word to select the word and bring up the context menu
- Try to "Select All" the text

**Actual result:** The "Select All" option of Android is missing.
**Expected result:** "Select All" should be available for selecting all the text.

### Screenshots
![IMG_20230726_155604](https://github.com/signalapp/Signal-Android/assets/2286713/54674ec3-57b0-4131-a1c2-44cb58e3881e)
![IMG_20230726_155619](https://github.com/signalapp/Signal-Android/assets/2286713/9e614d72-48d1-4379-b334-d5188909241b)

### Device info

**Device:** OnePlus 11
**Android version:** OxygenOS 13.1, Android 13
**Signal version:** 6.26.4

### Link to debug log
N/A?

**Comment by ElvenSpellmaker** [comment]
> I'm unable to reproduce. If you have already selected all of the text it doesn't show. Based on your screenshots that's what is happening. If you only select part of the text, the select all is there for me.

Hey, thanks for the response, I did wonder if that'd be raised and I should have posted images with more than one word.

It does this for me regardless of how many words there are or how many I have selected:

![Screenshot_2023-07-26-17-01-54-27_4b14b257287ac0a6d1fd5fbb2487716f](https://github.com/signalapp/Signal-Android/assets/2286713/4083cf69-d468-4b06-b9e6-37d340493fa5)
![IMG_20230726_170241](https://github.com/signalapp/Signal-Android/assets/2286713/c4eda13b-6ebe-4e65-9a1b-be0a534c1ec0)

**Comment by cody-signal** [comment]
Interesting, thanks for the clarification. We don't remove anything from the list the OS generates. We only add to it, so I'm not sure how it would disappear. I'm tempted to chock this up to OxygenOS oddities, but if someone can repro on a stock Android rom we can take a deeper look.

**Comment by ElvenSpellmaker** [comment]
Select and Select All only appear when nothing is selected, this is still an issue Mr stalebot.

**Comment by ElvenSpellmaker** [comment]
But it's still an issue?

**Comment by cody-signal** [comment]
Hi again @ElvenSpellmaker, we are still unable to reproduce and as I said before, we don't remove anything in the code, we only add, so I don't know how this could a Signal specific problem. Perhaps worth bring it up with the OxygenOS  folks?
