### ISSUE TITLE
Add Motorola One Power to AEC Blacklist

### ISSUE THREAD

**Issue by spring-trees-ufo** [signalapp/Signal-Android#13086]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Other person on call hears an echo when I use speaker on my device

### Steps to reproduce
- Initiate a Signal audio call
- Put myself on Speaker

**Actual result:** The other person on the call can hear an echo of their voice.
**Expected result:** The other person shouldn't be hearing an echo.

### Device info

**Device:** Motorola One Power
**Android version:** 10
**Signal version:** 6.26.5

### Link to debug log
https://debuglogs.org/android/6.26.5/876f14d2dda230bbd63c3a011005c79053e1986404ab0ad5a0d522f1cf86c213
Latest call initiated at 09:31 on July 29th, 2023.

**Comment by cody-signal** [comment]
We updated the block list. You should get new values in a couple hours, please let us know if this fixes the issues.

**Comment by spring-trees-ufo** [comment]
Fixed, appreciate it.
