### ISSUE TITLE
Registration via Audio call broken

### ISSUE THREAD

**Issue by prettySongbird** [signalapp/Signal-Android#13093]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

During the registration process, Signal offers SMS and Call verification to confirm the used phone number.
However, it seems that Call verification does not currently work while SMS verification is still functional.

I have tested several different numbers from different providers (all based in Germany) and reproduced the issue with all of them

As a result, phone numbers that cannot receive SMS cannot be used with Signal at the moment.

### Steps to reproduce
- register a new phone number 
- after entering the phone number (and automatically triggering the SMS verification), wait 60 seconds until the call option becomes available
- select the call option to receive the verification code via call

**Actual result:** While confirmation SMS have been received (on  numbers/devices that support them), no voice call has been triggered 
**Expected result:** Audio Call verification should work to support number/devices without SMS support

### Screenshots
Nothing to show

### Device info (Test system 1)

**Device:** Pixel 6a
**Android version:** 13
**Signal version:** Signal 6.27.10

### Device info (Test system 2)

**Device:** VM - Android x86 (for testing/reproduction)
**Android version:** 9
**Signal version:** Signal 6.27.10

### Link to debug log
The debug log is not available before the registration process is completed

**Comment by prettySongbird** [comment]
Update:

Calls to regular numbers seem to work again, but softphones still seem to have issues.
This is most likely related to the softphone providers instead.

**Comment by geno327** [comment]
We seem to have a similar issue at work, where we use softphone numbers. The provider said that Signal needs to whitelist new blocks of phone numbers and that we should reach out to Signal to get them whitelisted.
Is there a formal process to follow as end users?
