### ISSUE TITLE
Adding a person to the address book exposes badges

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#13097]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When adding a person to the address book and refreshing the 'new message'-List, I get the notification that a contact has joined Signal. So far so good. But it shows the new contact's badge as well. The other person hasn't stored my phone number. I think this exposes information that shouldn't be accessible by anyone who simply enters the phonenumber of someone else. So I'd rate it as a privacy issue.

### Steps to reproduce
- Add new contact to address book
- refresh on the 'new message' screen
- go back to the Chats-tab
- you can now see the Badge of the other person (of course they must have purchased one)

**Actual result:** Badge is shown without having exchanged messages or me being stored in the other persons address book
**Expected result:** Badge is not shown

### Screenshots

![grafik](https://github.com/signalapp/Signal-Android/assets/62468040/9e04bbf1-f7a2-41ca-b56f-9ebc0a6184a7)

### Device info

**Device:** OnePlus 8T
**Android version:** 13
**Signal version:** 6.27.10

### Link to debug log

https://debuglogs.org/android/6.27.10/1fe6eb05636caef90d0a60886aa2fce5bd1156742a32297dc844b2dc9d090984

**Comment by nicholas-signal** [comment]
This is working as intended.
