### ISSUE TITLE
Can not capture and / or send and receive high quality pictures (on ColorOS 13.1  (Android 13))

### ISSUE THREAD

**Issue by specs32** [signalapp/Signal-Android#13095]
- [oh boy ]  have I searched open and closed issues for duplicates (also the internet for probable cause and solution)
- [ indeed ] I am submitting a bug report for existing functionality that does not work as intended
- [yes] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [no] This isn't a feature request or a discussion topic

### Bug description
I can not send high quality pictures with Signal (at least on my particular phone). Even if I choose "send file" and select a photo from my gallery via filemanager with the size of for example 5 MB it gets compressed down to 300KB of sheer garbage. YES I selected High quality both in settings and in send picture mode. It makes no difference how I try to send the picture, it always gets compressed down to 300-400 KB of pixely mash no matter what I do.

### Steps to reproduce
- take a picture (with phone camera app or signal camera - doesn't matter)
- send it in HQ
- save the picture on PC
- compare size and quality of sent and received picture

This is also true the other way around !!! If I choose a photo on my PC and send it in Signal (up to date Arch linux - Signal version 6.27.1-1) with HQ  settings to any chat (usually note to self) on my phone it gets awfully compressed down.  (7 MB finest zoomable sunset in jpeg format file sent - 400KB minecraft screenshot received) 

I expect pictures being sent (and of course received) at the quality I shot them. At least (!!) when I choose to send them as file (like for example telegram does) OR if I set High Quality mode in Signal and have for example a 9 MB file it shall not be compressed further down than your chosen image transfer limit.

I do have a 64MP camera in that phone .. what good is it to me if I can send only 0.5 MP compressed "garbage" ? (xcuesme)  The only way I could transmit that photo is by compressing it into a different file format (zip or tgz or something) and that's kind of :roll_eyes: 

### Device info
**Device:** Oppo Find X3 Lite
**Android version:** 13 (ColorOS 13.1) (stock !)
**Signal version:** 6.27.10 (play store latest update)

Thank you though for all that flawlessly works on that brilliant app !!!

**Comment by alex-signal** [comment]
Hello! Would you be able to try your steps to reproduce and submit a debug log? (Settings -> Help -> Debug Log)

**Comment by specs32** [comment]
[signal-log-1691552992595.zip](https://github.com/signalapp/Signal-Android/files/12298033/signal-log-1691552992595.zip)

from latest backwards ...
I sent the debug log
I sent 2 pictures from PC to Signal (note to self)
I sent 2 Pictures from Signal to PC (note to self)
I took a photo in Signal and sent it (note to self)


![IMG20230809054608](https://github.com/signalapp/Signal-Android/assets/15709095/5764c1fd-d2b7-4646-83cd-4084e07f4af7)

This is one of the original photos I took with the camera in HD settings and sent via Signal. (Select Picture from Gallery)

![signal-2023-08-09-054640_002](https://github.com/signalapp/Signal-Android/assets/15709095/58b70a65-2003-4b49-b282-eb01af8ebfc7)

This is what I got with Signal in both directions to and from PC  (note to self) I sent the high resolution one via Telegram as file from phone to PC so I could send it back in original size via Signal.

I want to mention that the resolution on the photos (prior attempts) is indeed 4K , but the quality is severely reduced.. maybe this is intended behaviour ?

**Comment by greyson-signal** [comment]
Hi there, I understand your frustration. However, this behavior is intended. We call it "high quality" rather than "original quality" because we don't really ever send original-quality photos. We do not yet have a feature to send an image as a file attachment without modifications.

**Comment by specs32** [comment]
Thank you for taking the time clarifying this, and thank you for your understanding. And sorry for the bias.. I tired and tried and thought it should be possible and couldn't figure it out... I hope you will implement this feature in the future.. That would be great.
