### ISSUE TITLE
Pin creation failed

### ISSUE THREAD

**Issue by omarkhallill** [signalapp/Signal-Android#13104]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When i try to create a pin in signal in Samsung android , it says Pin creation failed , without any errors codes or something.

### Device info

**Device:** samsung SM-A325F
**Android version:** 13.0.0
**Signal version:** 6.28.6

### Link to debug log

![signal-log-1691827469651.zip](https://github.com/signalapp/Signal-Android/files/12326883/signal-log-1691827469651.zip)

**Comment by theking2** [comment]
Same here. On a Punkt mp-02

**Comment by cody-signal** [comment]
Sorry for the delay, @omarkhallill you issue should've been resolved in early September if you update to the latest version of Signal.

@theking2 without a debuglog I don't know what your issue could be related to, but if the same, then try updating to at least 6.32.+

**Comment by strigona** [comment]
I'm trying to migrate phones, after the data copies over I am unable to create a PIN. I'm on 6.40.5

**Comment by nicholas-signal** [comment]
> I'm trying to migrate phones, after the data copies over I am unable to create a PIN. I'm on 6.40.5

Please try this again, as there was an intermittent SVR2 issue at that time that have since been resolved. If it works for you, please close this GitHub issue. We're tracking this issue broadly here: #13277

**Comment by strigona** [comment]
Thanks, I meant to come back and provide an update. I re-transferred my account and I was able to register without getting permanently stuck on the PIN stuff. A few hours later I successfully created the PIN through the settings.
