### ISSUE TITLE
Signal Emojis

### ISSUE THREAD

**Issue by elendil7** [signalapp/Signal-Android#13106]
Hello,
Are Signal's emojis open source and/or free to download and use as one wishes?

Kind regards

**Comment by FrodoBaggins74524** [comment]
Yes, Signal's emojis are open source and free to download and use as you wish. You can find the emoji set in Signal's GitHub repository, and they are available under open source licenses. This means you can use, modify, and distribute them according to the terms of the license.

**Comment by Jens14L** [comment]
For comfort access: [Path to the emoji tables/matrices for Signal Android](https://github.com/signalapp/Signal-Android/tree/main/app/src/main/assets/emoji)

**Comment by greyson-signal** [comment]
Hi there, you can direct any inquiries around emojis to https://github.com/iamcal/emoji-data. Thanks!
