### ISSUE TITLE
Stop spamming users with Captchas

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#13114]
Still happening on 6.32.5

This is really insane. A messenger that needs a phone number, has no really FOSS mobile client also spamming people sending messages with Captcha requests???

How? What bot would spam Signal? Can't you just save the devices ID and see if it succeeded a Captcha once its NOT a bot and stop spamming users with Captchas?

I have to do 6 a week or so, its insane. Please save that state. Either captchas dont work, and robots can solve them, or once a Captcha is solved the device is secure.

**Comment by cody-signal** [comment]
Can you provide a debuglog so we can see why you are encountering so many?

**Comment by firefoxlover** [comment]
It happened on my phone again. Solved the captcha, didnt react, again, 5 times.

before solving the captcha(s):

https://debuglogs.org/android/6.30.4/351ed80a5e2bc32ac3176ff55d80a141c75b3e503c63531af218a8a9cc70dcb8

after solving the captchas:

https://debuglogs.org/android/6.30.4/3b3a4ad4563b55d134477a52349544b0f6ac0f68ec509c3b468fd8a8d7834542

My Proposal: use a captcha ONCE after login. From then on, annoying users that send a lot is simply harassment.

**Comment by firefoxlover** [comment]
Another debug log, when ignoring the captcha popup, so right when... again... I need to solve it.

https://debuglogs.org/android/6.32.5/c3d3538dc461c80fa5c4d64c757a44e2e5a9b4460155bbaad6fcec5dd018919a

**Comment by firefoxlover** [comment]
Today I had to solve a captcha again... the last one was 3 days ago

**Comment by firefoxlover** [comment]
Today I had to solve a captcha again... the last one was 3 days ago.

Edit today: again another captcha

**Comment by firefoxlover** [comment]
aaaand had to solve a Captcha again, today on Signal Desktop, packages as Flatpak (I think the .deb is the origin here), using Electron.

**Comment by firefoxlover** [comment]
Aaaand today I had to solve another Captcha. Please guys, whats the purpose?
