### ISSUE TITLE
Restore last conversation

### ISSUE THREAD

**Issue by aylen384** [signalapp/Signal-Android#1311]
1. Open a conversation in Textsecure
2. Press the HOME button
3. Open the textsecure app using the app icon

Current result: The conversation list is shown

Expected  result: The last active screen (conversation or conversation list) is shown

**Comment by rhodey** [comment]
related to #2331

**Comment by rhodey** [comment]
@mcginty any reason we're still tagging a bunch of activities as `android:launchMode="singleTask"`? I think if we just removed that from our XML declaration of `ConversationListActivity` this issue could be resolved-- also I prefer the UX requested by this issue.

**Comment by wp9015362** [comment]
@rhodey :

Any update on this issue?

It would be much appreciated if you could fix it.

Regards

**Comment by moxie0** [comment]
@wp9015362 You have been warned several times not to "bump" issues like this.  You're as close as you can be to getting banned.
