### ISSUE TITLE
catastrophic issue - signal (recent version) crashes EVERY time a call is attempted. Relay settings don't help. Reinstall no help.

### ISSUE THREAD

**Issue by nad0vs** [signalapp/Signal-Android#13116]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After most recent update, every time android signal tries to connect a call it crashes.
Messages work fine
Enabling "use less data" or "relay calls" does nothing to help

### Steps to reproduce
- call someone OR have someone call you (via signal of course)
- pick up the call or wait till other party does 
- instant crash!

**Actual result:** As said above, a crash

**Expected result:** a call (the way signal behaved before)

### Device info

**Device:** Pixel 5
**Android version:**Android 13
**Signal version:** 6.29.2
### Link to debug log

I hope I caught it right 
[signal-log-1692261606374.zip](https://github.com/signalapp/Signal-Android/files/12367651/signal-log-1692261606374.zip)

**Comment by nad0vs** [comment]
Here's one after making a fresh call after erasing all data and re-registering 

https://debuglogs.org/android/6.29.2/f6b54e91ff9406a12a9fab5615216f2922c6d819bff0c05d9c12c665bba3b6d1

**Comment by cody-signal** [comment]
Sorry you're encountering this @nad0vs, looking into right away.

**Comment by alex-signal** [comment]
Hi! It's non-optimal but for the time being you can go into app info, notifications, and disable Call and Call Status and ideally that should let you make calls again? Though you won't receive call notifications when they come in. I'm looking into how the heck this crash is happening (since we have the grantUriPermissions flag set and access enabled for the systemui process) but I'm still digging into whether it's an issue with us or with Calyxos

**Comment by nad0vs** [comment]
@alex-signal could the fact that I'm running it as user secondary have something to do with it?

P.S.: it was running fine before I installed the most recent update. I'll try uninstalling signal then re-installing it from Aurora and seeing how that goes

**Comment by nad0vs** [comment]
Problem persists.

Installing from fdroid also does not help anything 

Would greatly appreciate any pointers to how to work around this.

**Comment by nad0vs** [comment]
FWIW I tried installing Molly (well, it's a fork so I can install side-by-side) and it has exactly same crash

Maybe something about my phone is broken, but like, all other apps are making calls and otherwise working fine.....

**Comment by cody-signal** [comment]
When it's available to you, can you try on the current beta 6.30.1+, will likely start coming to prod next week.

**Comment by anatolms** [comment]
I want to contribute as well, if that might be any useful.

I have almost exact same issue (as you will see from logs), except I managed to fix outgoing calls by (supposedly) disabling notification called call status. Incoming calls didn't get fixed no matter what.

And I also happen to not even see a call popup (both with call status enabled and disabled, so I only hear like one second of ringtone and then error message appears (sometimes it doesn't) and app crashes. After starting signal again there is a message in a corresponding dialogue that reads "... declined call... "

https://debuglogs.org/android/6.31.2/287fa7893a8fc9cd9cbbed1e5d009d1e7f51efb3b5e2ec1ac2b60d54e99d6284

I installed beta version, as you can see, but it didn't change nothing, compared to current release

**Comment by anatolms** [comment]
Issue is still present even after updates.
