### ISSUE TITLE
Not connection 

### ISSUE THREAD

**Issue by homammm** [signalapp/Signal-Android#13125]
When I register a new number in the application, it gives me the following message: (It is not possible to connect to the service. Please make sure that you are connected to the network and try again.)

Knowing the proper connection!

### Device info

**Device:** Galaxy A51
**Android version:** 13
**Signal version:** 6.28.6

**Comment by cody-signal** [comment]
Can you provide a debuglog after experiencing the issue? Tapping any title in the registration flow 8 times will prompt it.

**Comment by homammm** [comment]
> Can you provide a debuglog after experiencing the issue? Tapping any title in the registration flow 8 times will prompt it.

https://debuglogs.org/android/6.29.2/879c18369a15e45e9c6604b89186bb36c94e113d87c6b80760124707054093fc

**Comment by homammm** [comment]
@cody-signal 

![Screenshot_20230824_200751_Signal.jpg](https://github.com/signalapp/Signal-Android/assets/121060312/95724e23-8893-41fa-b2a9-1ec5205dbfab)

**Comment by cody-signal** [comment]
Thanks, looking into it.

**Comment by homammm** [comment]
> Thanks, looking into it.

?

**Comment by greyson-signal** [comment]
Our best guess is that you are in a region where we're experiencing a high level of fraud. These things are dynamic, and you may be successful if you try again at a later date. Apologies!
