### ISSUE TITLE
Phone randomly restarts during signal voice calls

### ISSUE THREAD

**Issue by Wurzelkoch** [signalapp/Signal-Android#13126]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While on a voice call, the phone randomly restarts. With one caveat: It does not ask for the encryption passphrase but restarts from after decryption. To date, this kind of restarting has only occured during signal voice calls, that's why it seems to me as a signal bug.

### Steps to reproduce
- start a signal voice call

**Actual result:** After some time (about half to one and a half minute) the phone may randomly restart from after decryption. It does not happen always, though.
**Expected result:** I should be able to finish the phone call without the phone interfering
### Screenshots
I wouldn't know how to screenshot the splash screen of the phone restarting…

### Device info

**Device:** Samsung Galaxy S5, SM-G901F
**Android version:** lineage_klte-userdebug 10
**Signal version:** 6.28.6

### Link to debug log
Will add as soon as the bug happens again. In the mean time, here is one from a couple of minutes after the latest occurence: https://debuglogs.org/android/6.28.6/142b38278eee202f18d8069a91966f7db525c562118f64c8cca1459e36decd1f

**Comment by cody-signal** [comment]
Looking through your logs, we think this should be fixed on later version of Signal. Please update and if it still happens you can reopen this ticket with a fresh debuglog. Thanks for your initial report!
