### ISSUE TITLE
Occasional blank screen when opening a chat

### ISSUE THREAD

**Issue by nehemiagurl** [signalapp/Signal-Android#13123]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Occasionally (multiple times a day) when opening a chat, the screen goes wholly blank and no messages or info can be seen. This only stops when going back to the chat list and entering again.

### Steps to reproduce
- open a chat from the chat list/from search results

**Actual result:** the screen goes blank
**Expected result:** the opened chat is displayed as expected

### Screenshots
![signal-2023-08-19-184318](https://github.com/signalapp/Signal-Android/assets/109424320/70187043-9384-4668-bba8-2315ef0452ec)

### Device info

**Device:** Samsung Galaxy S23+
**Android version:** 13
**Signal version:** 6.28.6

### Link to debug log
https://debuglogs.org/android/6.28.6/d7ea67e233dae76f91fcbf2ffc7b659bafeb6fcdf2f22127d487fb4043920c0f

**Comment by cody-signal** [comment]
Hi there, can you try this on a later version? At least 6.29.1 or later when it becomes available to you?
