### ISSUE TITLE
Sending more than 3 images fail

### ISSUE THREAD

**Issue by cyclonejet** [signalapp/Signal-Android#13129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending more than 3 images fail

### Steps to reproduce
- Send more than 3 images

**Actual result:** Sending fails
**Expected result:** Sending should succeed

### Device info

**Device:** Xiaomi Redmi Note 5 Pro
**Android version:** 11
**Signal version:** 6.28.6

### Link to debug log
https://debuglogs.org/android/6.28.6/7e11b8d5e2c8302fea6dfd7f94bd4b79a9109cf811c14b175097657d1ff81961

**Comment by cyclonejet** [comment]
Updated to 6.30.4

Now the upper limit is 8, i.e. sending more than 8 images fail.

Logs when sending 8 pictures succeed: https://debuglogs.org/android/6.30.4/f0c249a6f142ece49593f4b81bc51501d3837435b73a1077e985b08d8380cb56  
  
Logs when sending 9 pictures fail: https://debuglogs.org/android/6.30.4/3658c38dc629ec7eb1c380f4c8f70ad47333b30e8dd7ab51b7539ac827e735fc  
  
  
After I installed new version, I started by sending 9 pictures at first, it failed. And any number of pictures being sent less than 9 succeeds.

**Comment by nicholas-signal** [comment]
I looked at your logs and I see that[ Glide, our image parsing library,](https://github.com/bumptech/glide) fails on loading some images. Are you able to narrow the issue down to a specific image file, or is it any combination of any 9+ images?

I've also added additional logging in the upcoming 6.31.3 release to include more information in the debug logs about why Glide cannot load an image.
