### ISSUE TITLE
No Audio button for a group call

### ISSUE THREAD

**Issue by gwdevelgit** [signalapp/Signal-Android#13137]
### Bug description
Signal is missing the Audio button for a group call. The feature is there for a direct (one-to-one) call but it's missing from the group call. Because of this, we have to always start the group call using the Video button and then explicitly/manually disable the camera in order to start an audio-only group call.

### Steps to reproduce
- create a group call in Signal
- try to start an audio call (you can't ... only the Video button is there)

**Actual result:**
- to initiate an audio-only group call, one has to initiate the call with the Video button and then remember to disable the camera before starting the group call

**Expected result:**
- a separate Audio button should be available for a group call similar to the UI used for a direct (one-to-one) call

### Device info
**Device:** Google Pixel 6a
**Android version:** 13
**Signal version:** .6.30.4

**Comment by nicholas-signal** [comment]
Hello,

Thanks for using Signal, but GitHub issues are for bugs and crashes. This is working as designed. We welcome feature requests on our community forum: https://community.signalusers.org/

Thanks!
