### ISSUE TITLE
Voice message indicator sounds are reversed in Android and Desktop

### ISSUE THREAD

**Issue by sellth** [signalapp/Signal-Android#13131]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When listening to multiple voice messages, sound notifications are played in between messages and after the last message ends. These go *ding* *ding* either in ascending or descending tone. Unfortunately, usage of these sounds is reversed between Signal Desktop and Signal Android.

- **Signal Desktop** uses ascending sounds to break between messages and descending dings to indicate end of the last message. This makes total sense, as it fits with how a lowering of pitch usually indicates the end of a sentence in speech.
- **Signal Android** however uses descending sounds between messages and ascending dings at the end. This is obviously wrong and should be corrected. :-)

### Steps to reproduce
- record multiple voice messages
- listen to them on Android and Desktop
- observe how the Desktop dings make much more sense

### Relevant code
- https://github.com/signalapp/Signal-Android/blob/f9d9af4fe91e0883f22ee08e0a60368d323c80a1/app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteMediaItemFactory.java#L41-L42
- https://github.com/signalapp/Signal-Desktop/blob/d455f62e5f99b6254b83bbb7c7ec114197f4fb76/ts/util/Sound.ts#L126-L132

**Comment by cody-signal** [comment]
Thanks, reached out to desktop and the team to figure out the spec'd behavior so we can align.
