### ISSUE TITLE
Backups may be exported with incorrect CREATE TABLE definitions

### ISSUE THREAD

**Issue by SnakingSappyGoat** [signalapp/Signal-Android#13135]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Backups may be exported with incorrect `CREATE TABLE` definitions. 

While working on a backup tool I discovered that sometimes there is a mismatch between the data type that is specified in the `CREATE TABLE` statements and actual data inserted in the columns.

An example that I found in one of the backups I was working with: the `identities` table creates the column `address` with the `INTEGER` type, while this should be `TEXT` type. 

For some reason sqlite happily processes the INSERTs and actually puts data with `TEXT` type in the columns, and I can browse the table with tools like DataGrip, but when I try to read the field with the .NET sqlite driver I get an error.

Some research seems to indicate that the way the `CREATE TABLE` statements are generated during export - reading from the `sqlite_master` table - is not a reliable way to fetch the current structure of a table ([source](https://www.sqlite.org/schematab.html): `The text is usually a copy of the original statement used to create the object`).

Either I missed the bit where `CREATE TABLE` statements are ignored during import, or this accidentally (still) works. My best guess is that most sqlite drivers are rather forgiving with misconfigured types, so this may not immediately cause issues for users who imported backups. But I suspect it may at some point become an issue when database migrations happen on unexpected table structures.

**Comment by cody-signal** [comment]
Hi @SnakingSappyGoat this is something we are still tracking but not something we've looked into just yet. And will eventually be eclipsed by the new v2 backup format that's being developed, but until then it's in our backlog to check out.
