### ISSUE TITLE
Signal-Android Crashes when send or recieve media on signal Desktop

### ISSUE THREAD

**Issue by muhammad-ans** [signalapp/Signal-Android#13138]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send or recieve media on signal desktop and then I try to open signal on mobile it crashes and force me to clear data.

### Steps to reproduce
- Send an image to someone on signal desktop
- Open signal android
- it crashes.

**Actual result:** 
Signal crashes and force me to clear data.

**Expected result:** Signal should work fine on mobile.

### Device info

**Device:** Oppo F3
**Android version:** 6.0
**Signal version:** 6.30.4

### Link to debug log

This is the log obtained through adb logcat
"
08-29 21:34:30.318 17976 17976 W linker  : /data/app/org.thoughtcrime.securesms-1/lib/arm64/libringrtc_rffi.so: unused DT entry: type 0x70000001 arg 0x0
08-29 21:34:30.442 17976 18023 D libc-netbsd: [getaddrinfo]:  hostname=chat.signal.org;  servname=(null);  app_pid=17976;  app_uid=10165;  ai_flags=1024;  ai_family=0; ai_socktype=1 from prox result 0
08-29 21:34:30.687 17976 18028 E WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
08-29 21:34:30.688 17976 18028 E APEExtractor: getAPEInfo not ape 5001
08-29 21:34:30.724 17976 18028 E         : unknown object: 44a4fbff-0-0-0000000000000000, 0 bytes
08-29 21:34:30.724 17976 18028 E         : asf_parse_header:error 2
08-29 21:34:30.724 17976 18028 E         : error parsing header: -8
08-29 21:34:30.735   477  1191 E MtkOmxAudioDecBase: GetParameter unsupported nParamIndex
08-29 21:34:30.735   477  1191 E OMXNodeInstance: getParameter(76:MTK.DECODER.MP3, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
08-29 21:34:30.743 17976 18035 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 18035 (TableOfContentT)
08-29 21:34:30.797 18036 18036 I AEE/AED : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-29 21:34:30.797 18036 18036 I AEE/AED : Build fingerprint: 'OPPO/CPH1609/CPH1609:6.0/MRA58K/1528121160:user/release-keys'
08-29 21:34:30.797 18036 18036 I AEE/AED : Revision: '0'
08-29 21:34:30.797 18036 18036 I AEE/AED : ABI: 'arm64'
08-29 21:34:30.797 18036 18036 I AEE/AED : pid: 17976, tid: 18035, name: TableOfContentT  >>> org.thoughtcrime.securesms <<<
08-29 21:34:30.798 18036 18036 I AEE/AED : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
08-29 21:34:30.814 18036 18036 I AEE/AED :     x0   0000000000000000  x1   000000000010055a  x2   0000007f7b6ae488  x3   0000007f7a3bf110
08-29 21:34:30.814 18036 18036 I AEE/AED :     x4   0000007f7a3bf200  x5   0000007f7a3bf1d0  x6   ffffff80ffffffd8  x7   0000007f7a3bf4f0
08-29 21:34:30.814 18036 18036 I AEE/AED :     x8   0000007f7a3bf200  x9   0000007f7a3bf1d0  x10  00000000ffffffd8  x11  00000000ffffff80
08-29 21:34:30.814 18036 18036 I AEE/AED :     x12  00000000000000a0  x13  0000000000023280  x14  0000007fab859198  x15  0000000000000001
08-29 21:34:30.814 18036 18036 I AEE/AED :     x16  0000007fa9639470  x17  0000007fad2b9080  x18  000000000000003c  x19  0000007f7ae373a0
08-29 21:34:30.814 18036 18036 I AEE/AED :     x20  0000000000000800  x21  0000000000000000  x22  0000000000000960  x23  0000007f7ae373c0
08-29 21:34:30.814 18036 18036 I AEE/AED :     x24  ffffffffffffffff  x25  0000000000000800  x26  0000000000000000  x27  fffffffffffffc10
08-29 21:34:30.814 18036 18036 I AEE/AED :     x28  0000000000001000  x29  0000007f7a3bf100  x30  0000007f96766434
08-29 21:34:30.814 18036 18036 I AEE/AED :     sp   0000007f7a3bf100  pc   0000007f967663ac  pstate 0000000080000000
08-29 21:34:30.821 18036 18036 I AEE/AED : 
08-29 21:34:30.821 18036 18036 I AEE/AED : backtrace:
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 00 pc 000000000002e3ac  /system/lib64/libmedia_jni.so
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 01 pc 000000000002e430  /system/lib64/libmedia_jni.so (_ZN7android16JMediaDataSource6readAtElm+112)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 02 pc 00000000000f1c88  /system/lib64/libstagefright.so (_ZN7android18CallbackDataSource6readAtElPvm+100)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 03 pc 00000000000f1eb8  /system/lib64/libstagefright.so (_ZN7android15TinyCacheSource6readAtElPvm+224)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 04 pc 00000000000ffb8c  /system/lib64/libstagefright.so (_ZN7android9MP3Source15getNextFramePosEPlS1_S1_+72)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 05 pc 000000000017a280  /system/lib64/libstagefright.so (_ZN7android20TableOfContentThread14useAFrameToTOCEv+60)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 06 pc 000000000017a194  /system/lib64/libstagefright.so (_ZN7android20TableOfContentThread11threadEntryEv+116)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 07 pc 000000000017a10c  /system/lib64/libstagefright.so (_ZN7android20TableOfContentThread13threadWrapperEPv+100)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 08 pc 00000000000675c4  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
08-29 21:34:30.821 18036 18036 I AEE/AED :     # 09 pc 000000000001edf0  /system/lib64/libc.so (__start_thread+16)
08-29 21:34:31.256 18036 18036 I AEE/AED : 
08-29 21:34:31.256 18036 18036 I AEE/AED : Tombstone written to: /data/tombstones/tombstone_08
08-29 21:34:31.256 18036 18036 E AEE/AED : AM write failed: Broken pipe
08-29 21:34:31.256 18036 18036 E AEE/AED : request.action: 0
08-29 21:34:31.346   477  9295 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...

"

**Comment by nicholas-signal** [comment]
Does this occur with all image formats?

**Comment by muhammad-ans** [comment]
The bug used to occur when i send the the png  from desktop Now i tried it did not crash but it always crashes when i get a voice note from one specific contact.
When i receive the voice note it crashes when downloading of voice note is completed.
Then i have to clear data and log in again.

**Comment by nicholas-signal** [comment]
Do you know what device that contact is using to send the problematic voice notes?

**Comment by muhammad-ans** [comment]
He used signal desktop when it crashed, Recently He changed the number on that account now it does not.

**Comment by nicholas-signal** [comment]
Interesting. Well, glad to hear it's no longer crashing. I will close this issue for now, feel free to re-open it if it reoccurs.
