### ISSUE TITLE
Signal crashes when importing backup file due to NegativeArraySizeException

### ISSUE THREAD

**Issue by Hedreon** [signalapp/Signal-Android#13146]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Every time I try to import my backup file(s), Signal crashes with the `NegativeArraySizeException` error.

From my understanding of Java and reading the debug log, what happened was that as soon as I clicked "Restore", Signal crashed with a `NegativeArraySizeException` error pointing out the source of the error which is [line 164 of the `BackupRecordInputStream.java` class.](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/backup/BackupRecordInputStream.java#L164) From reading the line and a bit of the class, you we're creating a new byte array called `frame` with a value of a byte array of an integer called `frameLength`. Usually it's supposed to be positive and not a negative, but for some reason it returned a negative. I'm guessing the `BackupRecordInputStream.java` class is used to decode some part of the backup file for Signal to use?

### Additional details

This still happens even if the backup file is not password-protected.

I could make a pull request that fixes this and study the code structure of this project but I can't because not only will studying the code structure take a significant amount of my free time, but also because I have school.

There are no issues or pull requests that have the exact same error. Though, after some more searching, I've only found multiple comments (in issues) of people reporting the same issue.

I don't think I can upload the entire signal debug log since this is a crash, and I don't think it's possible for Signal's debug logger to still be running if the entire app crashed, so that's why I only used a small chunk of what was being recorded using `adb logcat`.

Details may be subject to change.

### Steps to reproduce

- Make sure you're using Signal v6.30.4 or even above

- Open the app

- Click "Transfer or restore account"

- Click "Restore from backup"

- Click "Choose backup"

- Choose your backup file

- Click "Restore backup"

- Enter the password for the backup file

- Click "Restore"

- Crashed.

**Expected result:** Signal correctly imports the backup file without a problem.
**Actual result:** After you import your backup file, signal crashes with the `NegativeArraySizeException` error.

### Screenshots

https://github.com/signalapp/Signal-Android/assets/39467046/67cc7722-d0c7-4073-b73b-118cb7894715

### Device info

**Device:** Xiaomi POCO F3 (alioth)
**Android version:** 13 (Modded - LineageOS 20.1)
**Signal version:** 6.30.4

### Debug log

```
09-04 00:28:43.727 28538  2291 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
09-04 00:28:43.727 28538  2291 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 28538
09-04 00:28:43.727 28538  2291 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:269)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
09-04 00:28:43.727 28538  2291 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -80411097
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-04 00:28:43.727 28538  2291 E AndroidRuntime:        ... 4 more
09-04 00:28:43.727 28538  2291 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at android.os.AsyncTask$4.done(AsyncTask.java:415)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:269)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.lang.Thread.run(Thread.java:1012)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException: Caused by: java.lang.NegativeArraySizeException: -80411097
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-04 00:28:43.727 28538  2291 E SignalUncaughtException:       ... 4 more
09-04 00:28:43.738 28538  2291 I JobManager: Successfully flushed.
```

**Comment by greyson-signal** [comment]
This usually means something got corrupted with the backup file. We do run a verification on the file after creating the backup, so we're either missing something in our verification, or the file got corrupted afterwards. Did you copy the file from one phone to another? If so, can you try re-copying it?

**Comment by Hedreon** [comment]
> This usually means something got corrupted with the backup file. We do run a verification on the file after creating the backup, so we're either missing something in our verification, or the file got corrupted afterwards. Did you copy the file from one phone to another? If so, can you try re-copying it?

It happens with every backup I had. Before I had to "fix" (not going into the specifics; but I will say it involved formatting) my phone, I copied my backups folder to my PC, and once "fixed", I put it back into the phone.

**Comment by Hedreon** [comment]
Update: I read inside the backups before copying them again and their contents doesn't seem to be corrupted, since I think of corrupted binary files as being full of NUL unicode characters.

**Comment by mjwritesstuff** [comment]
Same error code : 

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at An error occurred while executing doInBackground().(:0)
Caused by: java.lang.NegativeArraySizeException: -1073487864
	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


```

**Comment by ryders** [comment]
@cody-signal curious to get your input;

**Summary;** I am not able to restore any backups created via Graphene OS;

**Details;**
1. I took a backup of my Signal messages using the built-in backups mechanism on a Pixel 7 Google Android phone
2. I wiped the phone and flashed Graphene OS
3. I restored the backup without a problem
4. 2 days later, I took another backup of my Signal messages using the same method, but on a now Graphene OS phone 
5. I wiped the phone and re-flashed fresh Graphene OS
7. Trying to restore the backup from #4, I get the same error (attached below) when restoring the backup from #4, `NegativeArraySizeException`

Interesting bits;
a) both backups were 'verified' by the built-in backup utility after being taken
b) both backups will show a correct 'wrong passphrase' if I willingly enter a wrong digit
c) both backups were taken and saved on the phone, then moved to a usb key. I have tried restoring from the usb key AND from the phone storage, to no avail.

**Further Details;**
8. Assuming backup from #4 is corrupted, after successfully restoring the first backup from #1 I proceeded to created a fresh new backup
9. trying to restore backup from #8 I get the same error, `NegativeArraySizeException`
10. tried restoring #1 again, and it's still works fine at this stage
11. Installed the Google Play Services (in case the restore needs those?) to no avail

All 3 backups above taken using the same / latest Signal 7.6.2 and successfully verified.

Bottomline is I'm not fussed about 2 days of messages that can't be restored for whatever reason. However, It appears it's not possible to restore any backup created via Graphene OS moving forward and THAT is more of a problem..

--

As mentioned in other threads the there's some difficulty in (reliably) backing up and restoring / transferring messages and this is a pain point when we're forcing contacts to ditch other applications.

I understand that privacy trumps convenience here and I'm ok with the inconvenience of manually having to transfer data. That said, the process needs to be reliable. Anything I can do/test to help?



--- Support Info ---
Filter: Signal Android Debug Log Submission - Crash
Device info: Google Pixel 7 (panther)
Android version: 14 (2024052100, 2024052100)
Signal version: 7.6.2
Signal package: org.thoughtcrime.securesms (doDiFGKPO1r)
Registration lock: true
Locale: en_AU

Debug Log: https://debuglogs.org/android/7.6.2/5a37f6ebccf63224f21a451498e2360e4dc3c0dd3b71ea190aaa58b2d16ce580
