### ISSUE TITLE
Crashes directly after starting due to RuntimeException caused by IllegalStateException

### ISSUE THREAD

**Issue by j0057** [signalapp/Signal-Android#13140]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal crashes directly after starting, it started doing this a few days ago. Cleaning cache or Signal's data didn't solve the issue. The phone (Zenfone 8) did get a Android security update days ago, I'm not sure if this was already happening before this update.

### Steps to reproduce

Start the app

**Actual result:** Crash
**Expected result:** No crash

### Screenshots

Sorry, I have no ADB ready to go for this, but here are some screenshots from the 'report a problem' dialog that appears after failing to start the app a few times:

![Screenshot_20230830-180440329](https://github.com/signalapp/Signal-Android/assets/452835/a8bf9694-0ac5-427a-ab3a-0388041fe8f7)

![Screenshot_20230830-180453328](https://github.com/signalapp/Signal-Android/assets/452835/9c145386-06b8-49fa-b2ee-08e55c37771d)

![Screenshot_20230830-180524024](https://github.com/signalapp/Signal-Android/assets/452835/2d500722-0346-4b5a-8798-a646c96985e7)

![Screenshot_20230830-180550487](https://github.com/signalapp/Signal-Android/assets/452835/ad710169-fa50-4023-9ad7-1087ae7a91ca)

### Device info

**Device:** Asus Zenfone 8
**Android version:** 13
**Signal version:** 6.30.4

### Link to debug log

Not available

**Comment by BeHappy2021** [comment]
I have the same issue on version 6.30.4 with my Asus Zenfone 8 Flip. There is another user with version 6.26.5 on a Samsung S20 who doesn't have the issue so I've told them not to update.

**Comment by j0057** [comment]
Is there anything I can do to help this issue along? I'm 100% unable to use Signal at the moment.

**Comment by greyson-signal** [comment]
It seems this was a bug specific to the Zenphone 8. We have a fix in 6.32.0, which is going to beta shortly.

**Comment by BeHappy2021** [comment]
I have installed beta 6.32.0 and can confirm that this issue is now fixed for me.

**Comment by j0057** [comment]
Beta worked for me too, lost all my chats in the process, and a re-install of the non-beta version did not restore them.

Thanks for the bugfix though!
