### ISSUE TITLE
Galaxy watch sound issue

### ISSUE THREAD

**Issue by thanasistrisp** [signalapp/Signal-Android#13141]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I answer or begin calls with phone connected, the default device is galaxy watch 5. If they call me and switch device to phone speakers, they can not hear me. If I call them first from phone and switch (as default is even there galaxy watch), it is ok.
Though, in other apps I have checked, it works as expected. Always default device when answering from phone is the phone itself (e.g. Viber, Messenger, Whatsup).
Also, a weird behavior only in Signal is that I cannot answer voip calls from watch. The answer screen in watch flashes between answering and declining state, and I cannot from there neither decline nor answer. I have to do this only from phone. In the above apps, I also cannot answer from watch, but I can decline as expected.

### Device info

**Device:** Samsung Galaxy A70
**Android version:** LineageOS 20 _with Samsung stock audio_, Android 13
**Signal version:** 6.31.2 with Google services

**Comment by thanasistrisp** [comment]
@nicholas-signal just tested latest version from playstore. It is not showing call notification at all but it is a nice workaround for now till Signal fully supports wearos like What'sUp e.g. where you can answer or decline calls and they completely sync with phone.

**Comment by LSeelig** [comment]
> @nicholas-signal just tested latest version from playstore (6.32.0). It is not showing call notification at all but it is a nice workaround for now till Signal fully supports wearos like What'sUp e.g. where you can answer or decline calls and they completely sync with phone.

@nicholas-signal is this why I dont get call notifications on my watch? This is a major issue as I dont know I received the call until I miss it!

**Comment by LSeelig** [comment]
I don't have the know-how or storage on my computer to test-build this. Is anyone in this thread with a smartwatch able to try reverting this commit and testing?
https://github.com/TwoLeaves/Signal-antisocial/commit/8b3ac39148974cf8e595bb1c0329850878b0b9f3
