### ISSUE TITLE
Unable to share 4 photos or more from third party app through Signal

### ISSUE THREAD

**Issue by mrxx0** [signalapp/Signal-Android#13143]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to send pictures from a third party app through Signal, photos are loaded but the message is not sent.

### Steps to reproduce
- Open Google Photos
- Select 4 photos
- Send them through Signal with the share icon
- Signal opens and load the photos in the message
- Send the message

**Actual result:** Message is not sent, an error icon appeared
**Expected result:** Message is sent without error

### Device info

**Device:** Google Pixel 6
**Android version:** 13 (running GrapheneOS)
**Signal version:** 6.30.4

### Link to debug log

https://debuglogs.org/android/6.30.4/ee0ee3b4a74a3143342bacb710b547c0155c2993c6c5075a85fca1082cfabe7d

**Comment by nicholas-signal** [comment]
Signal is having trouble loading the images off the disk and transcoding them for sending.

I've added additional logging to try to diagnose this issue in the upcoming 6.32 Signal release, which will be hitting beta shortly. If you are willing to enroll in the beta and submit a new debuglog, that would be much appreciated! Otherwise, I'll check back in when 6.32 rolls out to globally.

**Comment by mrxx0** [comment]
I enrolled in the beta and tried multiple times with 6.32.0 to reproduce the issue I had with 6.30.4 stable and I couldn't.
Can you reproduce it ?

**Comment by nicholas-signal** [comment]
> I enrolled in the beta and tried multiple times with 6.32.0 to reproduce the issue I had with 6.30.4 stable and I couldn't. Can you reproduce it ?

Glad to hear it's no longer happening for you!

No, we can't reproduce it. We've gotten occasional reports of this issue over time and we keep adding additional logging around Glide to get an accurate picture, but the root cause continues to elude us.
