### ISSUE TITLE
Idea: Split up backup in multiple chunks

### ISSUE THREAD

**Issue by Cameo007** [signalapp/Signal-Android#13147]
My signal backup is getting bigger and bigger (~4GB). So it would be nice to have the option to segment the backup in multiple chunks because I upload the backup in the cloud and then only new chunks would need to be uploaded.

This would be only an opt-in option.

**Comment by greyson-signal** [comment]
Hi there, thanks for the suggestion! But we only use Github for bug reports. Feel free to discuss feature request in the [forum](https://community.signalusers.org/). Thanks!
