### ISSUE TITLE
crashes when playing back voice message

### ISSUE THREAD

**Issue by overtinkering** [signalapp/Signal-Android#13148]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal 6.30.4 crashes when playing back voice message

### Steps to reproduce
- press play on voice message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- the sound starts playing
- display is not refreshed, no playhead appears(or moves)
- after ~5 seconds, android crash dialog appears
- voice message keeps playing till the end as long as we don't "accept" the crash dialog.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- sound plays
- display updates, playhead moves and can be repositioned
- Signal remains running without android reporting crash

### Device info

**Device:** Samsung Galaxy S5
**Android version:**6.0.1
**Signal version:** 6.30.4

### Link to debug log

https://debuglogs.org/android/6.30.4/4a65d0d4ab8e826d0f5facd476e4a5048cbd1ecdaa90ee625fc5e19b3ea7b1f8

**Comment by Kufat** [comment]
I am having a similar(?) problem with Signal 6.32.0 on a OnePlus 11 running Android 13. Instead of a crash, the voice message play button reacts briefly but never toggles to "pause", and the sound doesn't actually play at all.

**Comment by nicholas-signal** [comment]
Hello,

I've improved the voice note queueing/loading in 6.32.1, which is currently in beta. Please let me know if this issue is fixed once you get a chance to try 6.32.1+, whether as part of the beta program or as it rolls out to the stable channel.

**Comment by Kufat** [comment]
Thanks; I'll update to 6.32.1 and report back as soon as it becomes available for me. (I am in the beta program but currently only see 6.32.0.)
