### ISSUE TITLE
Messages read by linked iPadOS device are not always marked as read

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-Android#13153]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages read by linked iPadOS device are not always marked as read.

### Steps to reproduce
- link and iPadOS device with primary android device
- wait for messages (1-1 or group messages, does not seem to make any difference)
- open message(s) received in previous step on the linked device

**Actual result:** Unread count of the conversation on question is not (always) zeroed on the primary Android device
**Expected result:** If the Android device is connected to Signal backend and receiving read syncs (as seen to be the case by attached log, look for E.g. message with timestamp 1693978736821), unread count is zeroed

Dual of this issue on the iOS repository: https://github.com/signalapp/Signal-Android/issues/13168

### Device info

**Device:** Samsung Galaxy A32
**Android version:** 13.
**Signal version:** 6.30.4

### Link to debug log
https://debuglogs.org/android/6.30.4/80b6df76cebc3cec0125be0685778d28b647db4fc73f280d9fbf5d378f7d01c2

**Comment by firefoxlover** [comment]
Imagine needing to support ipadOS as an open source project...

Also this bug is not stale anymore.
