### ISSUE TITLE
Mute does not mute, loud notfication sound

### ISSUE THREAD

**Issue by timpoiko** [signalapp/Signal-Android#13155]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Mute does not mute

### Steps to reproduce
- Have a Linux laptop and an Android phone with signal, devices linked.
- Put the phone to a nightstand and use laptop. Mute a active chat for next 8 hours.
- Receive a new message from this chat.

**Actual result:** 
Message received with a loud notification sound. Sound came from phone. My wife, who was next to me, woke up.
**Expected result:** 
Silent chat.
After I hear the notification sound, I checked from the phone and from the laptop that chat in question is really muted.

Muting works as expected before recently happened forced updates.

Loud message received 2023-09-05 23:39

### Device info

**Device:** Planet Computers, Cosmo Communicator
**Android version:** 9
**Signal version:** 6.24.4

**Device:** Lenovo E14
**Linux version:** Debian 11
**Signal version:** 6.30.0-beta.2

### Link to debug log
https://debuglogs.org/android/6.24.4/6771d9456f4642b805396b977deff1f2191d2be20292e0ba61f124ecf919d9e4

**Comment by Sgn-32** [comment]
Your version of Signal is some days old. Have you tried it with the newest 6.31.2?

**Comment by cody-signal** [comment]
Hey there, I tried to reproduce this but couldn't. I can see in your logs where the mute status should've been sync'd around 22:51:11 so not sure what happened here. Unfortunately, I don't have to insight into which threads were muted and which made notification noises. Can you try to repro on latest desktop/android versions?

**Comment by timpoiko** [comment]
I reproduced this with the newest android and desktop versions. Of course I can slightly longer delay after muting.
