### ISSUE TITLE
Crash when opening a conversation: Unsupported icon type: only the bitmap and resource types are supported

### ISSUE THREAD

**Issue by robin-thoni** [signalapp/Signal-Android#13157]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal app crashes each time I open a conversation (group, or 1:1). Seems to happen since this morning beta update. Signal is completely unusable at this point.

### Steps to reproduce
- Open any conversation with the latest Play Store beta

**Actual result:**

Signal crashes.

**Expected result:**

The conversation activity opens and displays the chat history.

### Screenshots

![Screenshot_20230907-103739_Market Feedback Agent](https://github.com/signalapp/Signal-Android/assets/9640353/2496973e-6000-4ba2-826c-c69499f1d5bb)
 Sorry, the crash report app won't let me copy the stacktrace

### Device info

**Device:** Samsung Galaxy S9
**Android version:** 10.0
**Signal version:** 6.32.0

### Link to debug log

https://debuglogs.org/android/6.32.0/b56048c0970f821762304cb9ee1cb223e94bbb5cf643f869fb6afebd888818a5

**Comment by MarkusWagner** [comment]
I have the same problem on my OnePlus 5 since the update to 6.32.0 .

**Comment by simodev** [comment]
Same problem

**Device info**
Device: HUAWEI P30 Lite
EMUI version: 12.0
Signal version: 6.32.0

**Comment by 627426p** [comment]
Same Problem here, maybe another debug log helps: 

https://debuglogs.org/android/6.32.0/7a3eba95871d87679a318994d5880b4f8120b6421b49bb419638fc9eccadbb70

**Comment by egallesio** [comment]
I have the same problem on a Redmi Note 7 running Android 10. 
My log: https://debuglogs.org/android/6.32.0/e5a9750da827cb7d354afe9c0c5b08dda2287fabb6815be771924cb572993237

**Comment by CodingTarik** [comment]
Same problem on Xiaomi MI 9T.

**Comment by joshdev8** [comment]
Same on Pixel 7, android 14 beta.

**Comment by nicholas-signal** [comment]
This has been fixed in 6.32.1.

**Comment by ddshore** [comment]
Thanks for the fix, do you know when this will be pushed to the play store?

**Comment by robin-thoni** [comment]
They said on Reddit it was pushed already, so... between now and 24 hours. Thank you Play Store :)

**Comment by egallesio** [comment]
It's already on the Play store, and ... it works. Thanks a lot.

**Comment by robin-thoni** [comment]
> It's already on the Play store

Mostly depends where you are on the planet, for the first few hours. It's not necessarily available everywhere at the same time, unfortunately. Or at least it was like that when I used to push stuff to the Store, maybe it has changed since?

Anyway, got the fix too, can also confirm it fixes the issue. Thanks @alex-signal for the quick fix!

**Comment by robin-thoni** [comment]
@alex-signal @nicholas-signal  The notification icons still seem broken:
![signal-2023-09-08-081225_002](https://github.com/signalapp/Signal-Android/assets/9640353/6c6ff2d8-b2a7-4474-bb46-02b8f6875d9d)

**Comment by nicholas-signal** [comment]
> @alex-signal @nicholas-signal The notification icons still seem broken: ![signal-2023-09-08-081225_002](https://user-images.githubusercontent.com/9640353/266518289-6c6ff2d8-b2a7-4474-bb46-02b8f6875d9d.jpeg)

This is still on the Galaxy S9 w/ Android 10, right? Would you mind submitting an updated debuglog so we can see if/when the imageloading fails?

**Comment by robin-thoni** [comment]
Yes, same device. Here are the logs, taken seconds after the notification popped: https://debuglogs.org/android/6.32.1/14a141edc8868fb064c8c11b7754ba0c765dc160858f377a2462d2d766442d84

**Comment by nicholas-signal** [comment]
> Yes, same device. Here are the logs, taken seconds after the notification popped: https://debuglogs.org/android/6.32.1/14a141edc8868fb064c8c11b7754ba0c765dc160858f377a2462d2d766442d84

Thanks, we're taking a look.
