### ISSUE TITLE
Cannot create pin-signal

### ISSUE THREAD

**Issue by gityhubi** [signalapp/Signal-Android#13151]
----------------------------------------

### Device info
**Android version:** 12
**Signal version:** 6.30.4

The third day I can't create a PIN code:

**PIN creation failed
Your PIN was not saved. We'll prompt you to create a PIN later.**

**Comment by nicholas-signal** [comment]
Are you able to get into the app? Either way, please submit a debug log (instructions here: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) so we can diagnose what is causing the PIN creation to fail.
