### ISSUE TITLE
Signal-Android images not loading bug

### ISSUE THREAD

**Issue by Babe-n** [signalapp/Signal-Android#13159]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Updated my Android to latest version and now I can't send images in Signal anymore. I've checked the app settings and upgraded Signal to latest version. Got a message stating Signal does not support latest version of Android.

### Steps to reproduce
Sending any image just sits and loads and loads and doesn't get sent.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

Samsung S22 Ultra
**Android version:** UI one 5.1
**Signal version:** 6.31.2

**Comment by nicholas-signal** [comment]
Would you mind submitting a debug log? This will (hopefully) tell us where in the code the failure is occurring.

**Comment by Babe-n** [comment]
Hi guys

About an hour ago all the images suddenly went through so it seems as if
the problem resolved itself somehow.

Thank you very much for the reply!

Regards
Liesl

**Comment by Babe-n** [comment]
Resolved itself somehow after 16 hours. Not sure why. But working now.

**Comment by Babe-n** [comment]
Hi guys
Closed this too soon it seems. It's happening again but strangely only in one chat. Images just hang and load and load but don't go through. But definitely work on a different chat. Help please ;)

**Comment by nicholas-signal** [comment]
> Hi guys Closed this too soon it seems. It's happening again but strangely only in one chat. Images just hang and load and load but don't go through. But definitely work on a different chat. Help please ;)

Sure thing, we just need a debug log so we can begin to dig into the issue: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug

Additionally, if you long-press on the problematic message, you should be able to select `Info` from the pop-up menu which should take you to the Message Details screen. On the message details screen, if you long-press the `Sent` timestamp, it should copy the message ID to your phone's clipboard.

Please include one or more of these message IDs as well so we can match them up with the lines in your debug log.

**Comment by Babe-n** [comment]
Hi again

Ok I submitted the debug log and a image message ID from one of the images
that was "stuck" for about 12hours and 20min, online following the link you
sent me. The other, older images send had failed with an error message this
afternoon already.

Let me know what else I can send you.

Thank you

**Comment by UserX404** [comment]
@Babe-n
You have to post the Url of the log toyourpost here

**Comment by Babe-n** [comment]
No problem

Debug log:
https://debuglogs.org/android/6.31.2/e58109cb4113f7ba4489d8d071f2262c5e0a409feb12158c4fc9ba493fe19f59
Message ID: 1694402398658 (was send at 05:19 and received just over 12
hours later)

Thank you

**Comment by Babe-n** [comment]
Awesome, thank you!
