### ISSUE TITLE
Issues with registering phone number fresh install

### ISSUE THREAD

**Issue by Anduril97** [signalapp/Signal-Android#13165]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal had been lagging a lot lately with sending messages, oddly enough this seemed to be more of an issue with group chats than with single person messaging. I decided to back up and do a full uninstall reinstall. After I reinstalled I am now unable to register my phone number on signal, even if I choose transfer account or press continue (and ignore my backup); after entering the phone number either way, pressing continue causes the loading circle to spin forever and eventually signal crashes.

### Steps to reproduce
- install signal, Grant necessary permissions
- either press continue or transfer account (I have tried both ways and the exact same result happens)
- move along steps until enter phone number, press continue

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Loading bar spins forever, eventually a pop-up comes up saying is this number correct? I press OK, after a couple of minutes of loading signal crashes
**Expected result:**
Should be able to receive a text message to register my phone number on signal.

### Device info

**Device:** Samsung Galaxy S22
**Android version:** 13
**Signal version:** 6.31.2

### Link to debug log

https://debuglogs.org/android/6.31.2/6ee335ed579b45826b90c441a33d82d3bd07a0c81c1ea84b5788ce4d672c9692

Here's another debug log that I took just after it crashed now:
https://debuglogs.org/android/6.31.2/116c986edda6437e8fb2b53c40d445b33514c0b293f14f8130b0f2697e369f01

**Comment by nicholas-signal** [comment]
Interesting... Does it ask you to re-enter your PIN?

**Comment by Anduril97** [comment]
@nicholas-signal No I have never been asked to re-enter my PIN, maybe I never got that far? When I tried doing transfer account it does ask for the backup code and all that, which seems to go successfully. The issue I run into is when I enter my phone number it just loads forever without going anywhere

**Comment by teddi2727** [comment]
Unable to connect to server.. that’s the message I receive when trying to register. I’ve granted permissions, made sure VPN was turned off, and done everything else suggested.  As a 77 year old grandmother, most of your language is gobbledygook to me, so lead me gently to a solution.

Also, an extra space appears between last two numbers of phone number.

**Comment by nicholas-signal** [comment]
Hello @Anduril97,

According to your debug logs, the next step you should have seen was a prompt for you to enter your old PIN, which would have let you proceed. I've added more logging in v6.38 to try to pinpoint exactly what's happening here, since as best I can tell, your device simply isn't presenting you with the screen you're supposed to be seeing.

@teddi2727 your issue sounds related but distinct. If you don't mind, would you be able to file a new GitHub issue, including a debug log? That will let us narrow down what is causing your "Unable to connect to server".

Here's the instructions for taking a debug log: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug

**Comment by Anduril97** [comment]
I was able to log in eventually after a few days. Really not sure what happened.
