### ISSUE TITLE
Signal needlessly degrades PNG images

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-Android#13164]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Sending a PNG causes it to be converted to a lower image quality, as it's though it's being internally converted to a JPG, at least insofar as viewing it within the app is concerned. I fully understand that Signal might want to (1) remove the JFIF header from JPGs due to its identifying information such as GPS and camera specs, (2) remove the same from PNGs if applicable, (3) remove the same from videos if applicable, and (4) recompress videos to lower quality in order to relieve datacenter load. However, degrading the quality of an image format whose use purpose is overwhelmingly for the sake of maximizing resolution seems excessive.

A compromise solution would be to have a setting that allows us to "Send PNGs verbatim" or something like that. It would be nice to have the same option for videos, but I get why that might never happen.

### Steps to reproduce

Just make a PNG image, ideally with sharp features so the high quality is obvious, such as a graphic design element for a presentation. Send it to someone.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

At least within Signal itself, the received image is degraded in quality. You might need to zoom up to notice.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The image should be identical to what was sent.

### Device info

**Device:** Android 12
**Android version:** 12
**Signal version:** Latest

**Comment by nicholas-signal** [comment]
Currently, Signal Android transcodes all images to JPEG for bandwidth, security, and compatibility reasons.
