### ISSUE TITLE
Group links in chats are not working

### ISSUE THREAD

**Issue by realmazharhussain** [signalapp/Signal-Android#13166]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Only hostname part of the link (https://signal.group/) is recognized as a link.

For example, <https://signal.group/#abcdefghi> is recognized as <https://signal.group/>#abcdefghi.

### Steps to reproduce
- Open Signal
- Send yourself a group link

**Actual result:** Cannot click on the link to join the group 
**Expected result:** Clicking on the link should give the option to join the group

### Screenshots
![Screenshot_20230910-101232](https://github.com/signalapp/Signal-Android/assets/67191572/b8328878-5acd-4e22-8584-dde2189249c0)

### Device info
**Device:** Infinix Smart 4 (X653)
**Android version:** 9 (XOS v5.5.2)
**Signal version:** 6.31.2

### Link to debug log
Not Applicable

**Comment by realmazharhussain** [comment]
No.

**Comment by cody-signal** [comment]
I'm unable to reproduce this, I wonder if it's something specific about your group link, maybe the `-` in it?

**Comment by realmazharhussain** [comment]
More probably it is the # right after https://signal.group/ that is causing it.

**Comment by cody-signal** [comment]
No, that linkifies fine for me. Actually manually typing in a similar link to yours linkifies fine as well. We use the system linkification api, so I wonder if XOS is doing something incorrectly.

![image](https://github.com/signalapp/Signal-Android/assets/66265416/b6ecd10d-693d-432b-b149-2d4b28b9e015)

**Comment by realmazharhussain** [comment]
That's probably it.
