### ISSUE TITLE
It's possible to call a contact who doesn't have Signal installed anymore

### ISSUE THREAD

**Issue by magical-heyrovsky** [signalapp/Signal-Android#13160]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It's possible to call a contact who doesn't have Signal installed anymore. So let's say I have a friend called Bob who used to have Signal installed but uninstalled it a while ago. I am still able to see Bob in the Signal contact list and even call him. Signal does not tell me that this person does not have Signal installed anymore, but instead tries to call him. I hear a ringtone for about 20–30 seconds. Then the call will be cancelled automatically.

### Steps to reproduce
- Call someone who does not have Signal installed anymore via Signal
- It will ring for a while (~20-30 seconds) before cancelling the call automatically
- Signal will display **Unanswered voice call** in the chat.

**Actual result:** See **Steps to reproduce**
**Expected result:** 
- It should not be possible to call a contact who doesn't have Signal installed via the Signal app
- The fact that Signal displays contacts that don't have Signal installed anymore is of course another problem that deserves a separate GitHub Issue. If a contact does not have Signal installed then that contact should not be displayed in the Signal app.

### Device info

**Device:** Google Pixel 6a
**Android version:** 13
**Signal version:** 6.31.2

**Comment by nicholas-signal** [comment]
The Signal service does not know whether the client is installed or not. The service only knows the last time they connected, and every day we look for accounts that are 180+ days old and delete them (https://github.com/signalapp/Signal-Server/blob/ecd6b0174a32f17bf4a24fd291af438f49ed5edc/service/src/main/java/org/whispersystems/textsecuregcm/storage/AccountCleaner.java#L72-L74).

We don't allow calls to deleted accounts, but if the account exists, we don't know if they've uninstalled or if their phone is just off.
