### ISSUE TITLE
Signal crashing when Twin Apps is enabled

### ISSUE THREAD

**Issue by cabrenn** [signalapp/Signal-Android#13162]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Once I enable Signal in Twin Apps and login to both main Signal app and it's twin, both of them crash immediately after opening.
**This started to happen once I updated my app. I am not sure what was the version prior to update.**

### Steps to reproduce
- download signal
- login to newly installed signal
- enable signal in Twin Apps
- login to Signal twin with account different to original Signal
- once PIN is entered to open twin account the app crashes
- opening either original or twin app will close Signal immediately

**Actual result:** Both Signal and it's twin are immediately force closing when opened.
**Expected result:** Both Signal and it's twin should not force close and open.

### Screenshots
-

### Device info
**Device:** Asus Zenfone 9 (AI2202)
**Android version:** 13 (security patch July 5, 2023)
**Signal version:** 6.31.2

### Link to debug log
https://pastebin.com/vjzjtGQD

**Comment by nicholas-signal** [comment]
Your log indicates you're actually running into a ZenFone-specific bug that I tried to address here: bfc8b199b63c789a477640cf022e161e612076ce

This fix is in 6.32, which is currently in beta.

**Comment by zigg8321** [comment]
This issue has resurfaced and has been persistent for the last 30-ish days, only falling back to version 7.13.4 is the only solution I have found to avoid losing access to my second #.
