### ISSUE TITLE
Poor audio quality on Fairphone 4

### ISSUE THREAD

**Issue by Kyle0** [signalapp/Signal-Android#13161]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio quality is very poor when using video calling. This is always the case, regardless of whether I use mobile data or wifi. This appears to be due to a lack of background noise cancellation when video is on.

### Steps to reproduce
- Open signal
- Start audio call to a contact
- Ask contact if they can hear you
- Turn on video
- Check audio quality with contact again

**Actual result:** Poor/indecipherable audio
**Expected result:** Good quality audio with no background noise

### Device info
**Device:** Fairphone 4
**Android version:** CalyxOS 4.12.1
**Signal version:** 6.31.2

### Link to debug log
https://debuglogs.org/android/6.31.2/b5f302065532811e1da4e256104d8cf2a1bf53b3f46a4442117fdece5fa9c98b

### Fresh Debug Log
https://debuglogs.org/android/6.33.3/e51a10cc0d1afbd6bd0bfa98509019ff24114c5ec80aa214a4cbab9aeef6a81a

**Comment by nicholas-signal** [comment]
We have experienced similar issues in the past with the Fairphone 2, and the resolution was not relying on the hardware's automatic echo cancelation.

I've gone ahead and added the Fairphone 3 & 4 to the list, which should take effect globally in 6-12 hours. Let me know if that helps!

**Comment by Kyle0** [comment]
That was a quicker response than I expected! I just tried a video call, didn't notice much improvement, tbh. Was an update required? I haven't seen an update listed on F-Droid.

**Comment by nicholas-signal** [comment]
It should have taken effect when the app refreshes its configuration., which usually takes place every 6-12 hours.

**Comment by Kyle0** [comment]
Oh, I see. Not really familiar with the inner workings of Android. I made one or two more calls since, they seemed to have better quality audio. But I want to leave this issue open a bit longer, just in case.

**Comment by nicholas-signal** [comment]
I see in your new logs that automatic echo cancellation is indeed disabled, but clearly that has not resolved the issue. We'll see if we can source a Fairphone 4 here in the USA.

**Comment by Kyle0** [comment]
Just keeping this issue alive, as not solved.

**Comment by Kyle0** [comment]
I wondered if it might have something to do with latency of the network connection. I have a VPN on by default, which I usually forget about. I have tried calling with the VPN off and with a different VPN connection optimised for P2P. Both had much lower latency (<20 ms as opposed to 200-400 ms), and the call quality on my end was much better, no audio feedback. Is there some more definitive test I could do on my device to help pin down the issue? Since I already have a Fairphone, would save someone having to get one just for testing purposes.

**Comment by pjaap** [comment]
The Problem still contantly appears in all video calls when a stock rom Fairphone 4 is included. The problem does not exist on FP4 with current LineageOS though.

**Comment by fazlefahimrohan** [comment]
![Screenshot_20250328_165328_DuckDuckGo.jpg](https://github.com/user-attachments/assets/c6eb26a9-7c1e-450f-ba23-0cd43cca0898)

I see a automatic error or is was stoped loading. An unexpected end
