### ISSUE TITLE
Click on verification info in the chat opens a verify view with the wrong (own) identifier

### ISSUE THREAD

**Issue by easyMaxi** [signalapp/Signal-Android#13171]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
@tiefenau notices this with me.
The text within a chat that links directly to the verification view opens the "wrong" view. It links to the view to verify yourself. The button there verifies only you. You can check that by clicking it and looking at your notes chat.

### Steps to reproduce
- Mark a person as verified through the settings
- Go to the chat. There should be a "you marked ... as verified" text (Pay attention to the name of the contact in the text)
- Click on this text
- The verification screen opens up again. But now for yourself. (You can notice this by looking at the text under the security numbers. This now mentions your name.)
- We checked this in the code and found that two different IDs are provided to the activity (VerifyDisplayFragment) depending on where it is called.
- We tried to figure out how the code works, and to the best of our effort, we think it is related to the following line that contains the call to the activity and gives your own ID and not the one from the chat contact: https://github.com/signalapp/Signal-Android/blob/61654f815d09138ac7bcb32822a5849ebd9f8b05/app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationUpdateItem.java#L715

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
I can verify myself but not the chat partner by opening the verification screen through the ("you marked ..." text in the chat). 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
I would expect to verify the conversation partner or be able to mark them as not verified anymore.

### Screenshots

[Screen_recording_20230914_145846.webm](https://github.com/signalapp/Signal-Android/assets/965733/a46d2d14-a8a4-4ef8-a4e9-c0ee4990593d)

### Device info

**Device:** Emulated Pixel XL API 30 (but we tried it also on a Galaxy A14 and a Galaxy A53
**Android version:** 11 and 13
**Signal version:** 6.31.2

**Comment by greyson-signal** [comment]
This was fixed a while back.
