### ISSUE TITLE
Transfer account not working due to missing location permission

### ISSUE THREAD

**Issue by grote** [signalapp/Signal-Android#13173]
Try to transfer an account on Android 13 while both apps not having location permission. Signal doesn't ask to get this permission and just shows a progress bar on both phones (without any text). 

Logcat had:

```
Wifi Direct unavailable: REQUIRED_PERMISSION_NOT_GRANTED
```

This gave me the right hint, so I granted location permission in settings for both apps and tried again. This time text showed up immediately next to the progress bar.

Expected behavior: at least complain about missing permission and guide user to settings screen, if the app can't ask for the permission. Alternatively, discovering nearby devices shouldn't require location perm anymore, maybe something like `neverForLocation` needs to be adapted.

**Comment by turmoni** [comment]
+1ing this - having looked at the source and seen that it *looks* like this permission should be being requested I was wondering if I had just got myself into some weird obscure situation, but if two of us have had the issue (and you on multiple devices) that seems unlikely, plus there seem to have been some recent changes in the area ( https://github.com/signalapp/Signal-Android/commits/main/device-transfer/lib/src/main/java/org/signal/devicetransfer/WifiDirect.java ).

**Comment by alex-signal** [comment]
Hi! Yes, some work was done around this to support Google's new requirement of targetting API33+.
