### ISSUE TITLE
Signal 6.32.4 crashing: IllegalStateException: No session for...

### ISSUE THREAD

**Issue by Diapolo** [signalapp/Signal-Android#13170]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is constantly crashing and draining my battery really fast. Sometimes it's while accessing a chat, sometimes it's before being able to enter my pin and sometimes even before being able to generate a log file.

### Steps to reproduce
Not reproducible every time also different cases when crash occurs!
- open Signal app
- try to generate a log file before entering my pin

**Actual result:** Crash, app closes.
**Expected result:** No crash, app running fine since yesterday.

### Device info
**Device:** Fairphone 4
**Android version:** 13
**CalyxOS version:** 4.13.1 (security express branch)
**Signal version:** 6.32.4 (website version, no GAPPS or Play Store)

### Link to debug log
Currently none... I submitted it via webform.

### Error
```
09-13 18:29:51.309  3502  4101 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
09-13 18:29:51.309  3502  4101 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3502
09-13 18:29:51.309  3502  4101 E AndroidRuntime: java.lang.IllegalStateException: No session for (********-****-****-****-*********ad3.1)!
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.signal.libsignal.protocol.SessionCipher.getRemoteRegistrationId(SessionCipher.java:166)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.signal.libsignal.metadata.SealedSessionCipher.getRemoteRegistrationId(SealedSessionCipher.java:209)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalSealedSessionCipher.getRemoteRegistrationId(SignalSealedSessionCipher.java:69)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.EnvelopeContent$Encrypted.processSealedSender(EnvelopeContent.java:92)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:121)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2425)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2382)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1988)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.resendContent(SignalServiceMessageSender.java:542)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.ResendMessageJob.onRun(ResendMessageJob.java:177)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
09-13 18:29:51.309  3502  4101 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by Diapolo** [comment]
I reinstalled the app (was using the website distribution version for Websocket support) and restored a backup. Because microG was running Signal asked to register for push notifications (GCM AFAIK) and I allowed that. Well it seems that "solved" the problems (by switching the message delivery mechanism).

Didn't get a response from support after sending my log, lets see if something happens with the issue...

**Comment by nicholas-signal** [comment]
hi @patcon, would you mind attaching the debug log URL here? Thanks! (feel free to just create a new one)

**Comment by patcon** [comment]
Sure! https://debuglogs.org/android/6.34.5/adc7ddbd7cd5fa0519d1ca68d156c6b120cd678767365f3b186103eee79c9286

Left the worst-offending group and force stopped an hour ago, but this is the log immediately after opening it back up

Thanks again

**Comment by patcon** [comment]
New logs that def have a record: https://debuglogs.org/android/6.34.5/5b556e6555984a593511720de7185969d35d55a20a86c19f20925a2913bbc737

**Comment by thgoebel** [comment]
I have the same issue, and it's crashing *a lot*. To the point where Signal is annoying to use because it crashes away under me.

Signal 6.37.2, Android 13/LineageOS 20. The phone has no GApps, and I installed Signal from Aurora Store (i.e. Play Store) and not from the Signal website.

https://debuglogs.org/android/6.37.2/855615cba062c6e25026ec765190c7a44cc100d10ec12e787f40357f57654606

**Comment by nbelavic** [comment]
Also hit this yesterday. 
Signal 6.40.5 from play store, Android 13/MIUI14.0.14.0.TKDEUXM


`java.lang.IllegalStateException: No session for (XXXXXXXX-XXXX-XXXXX-XXXX-XXXXXXXXXXXXX.1)!
        at org.signal.libsignal.protocol.SessionCipher.getRemoteRegistrationId(SessionCipher.java:166)
        at org.signal.libsignal.metadata.SealedSessionCipher.getRemoteRegistrationId(SealedSessionCipher.java:209)
        at org.whispersystems.signalservice.api.crypto.SignalSealedSessionCipher.getRemoteRegistrationId(SignalSealedSessionCipher.java:69)
        at org.whispersystems.signalservice.api.crypto.EnvelopeContent$Encrypted.processSealedSender(EnvelopeContent.java:92)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:120)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2456)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2413)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:2019)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.resendContent(SignalServiceMessageSender.java:541)
        at org.thoughtcrime.securesms.jobs.ResendMessageJob.onRun(ResendMessageJob.java:177)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
        at [[ ↑↑ Original Trace ↑↑ ]].(:0)
        at [[ ↓↓ Exception Message ↓↓ ]].(:0)
        at No session for (********-****-****-****-*********b8b.1)!.(:0)
`


https://debuglogs.org/android/6.40.5/1c00042b225b4b63254d570d0b1d9a04d45904b6376ca5f2aa008f7fd465e648

**Comment by maximiliankaul** [comment]
Unfortunately, I'm experiencing the same problem. A contact of mine got a new phone (Fairphone 4). Since then
 - my phone (Pixel 7 stock) crashes (same exception as described here)
- the contact can successfully send messages to me
- contact doesn't receive messages from old (before phone change) chat buddies
- Signal works as expected between the contact and previously unknown chat buddies
