### ISSUE TITLE
Bubbles are not showing and crashing SystemUI

### ISSUE THREAD

**Issue by gooomis** [signalapp/Signal-Android#13177]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The bubbles are not showing after receiving the notification, and when tapping on "Create bubble" the only thing happening is creating an empty notification, which crashes the SystemUI after tapping on it.
Signal is allowed to create bubbles, the conversations did not appear as conversations up until creating "Custom notifications" for the contacts. After that, the issue persists. It has been also apparent on previous beta versions of Signal.

### Steps to reproduce
- Open a conversation
- Tap on three-dot menu
- Select "Create bubble"
- An empty notification with just a contact name shows up, but not a bubble
- Swiping the notification panel and tapping on the newly created notification 
- SystemUI crashing

**Actual result:** After tapping "Create bubble" the bubble should appear and be working as intended
**Expected result:** SystemUI crashes, bubble does not appear

### Screenshots
https://github.com/signalapp/Signal-Android/assets/16692462/46d0f746-33bc-4d7c-bece-ecb1b5f88a2c

*The video ends in the moment of SystemUI crashing*

### Device info
**Device:** Samsung Galaxy S23 Ultra
**Android version:** 14
**Signal version:** 6.33.1

### Link to debug log

https://debuglogs.org/android/6.33.1/d023f002563e3310285f0e6c92c884a61f5114aca08172d74aaa42505c922965

<details><summary>ADB logs at the SystemUI crash point:</summary>
    <pre>
09-18 00:32:23.459 25362 25362 E AndroidRuntime: FATAL EXCEPTION: main
09-18 00:32:23.459 25362 25362 E AndroidRuntime: Process: com.android.systemui, PID: 25362
09-18 00:32:23.459 25362 25362 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.UserHandle android.app.PendingIntent.getCreatorUserHandle()' on a null object reference
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter$$ExternalSyntheticLambda2.run(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:75)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter$1.onDismiss(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:95)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.ActivityStarterImpl$ActivityStarterInternal.dismissKeyguardThenExecute(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:98)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.ActivityStarterImpl.dismissKeyguardThenExecute(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:2)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter.onNotificationClicked(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:301)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.NotificationClicker.onClick(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:290)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.view.View.performClick(View.java:8043)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.performClick(qb/70860432 88936b875f4207cdfa8adefca1678cec715368d819a88530b55a740162fd893b:4)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8020)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:31834)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8875)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
09-18 00:32:23.459 25362 25362 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
</pre>
   </details>

**Comment by PanchumarthiAbhinav** [comment]
@jim-signal I would like to look into this issue. I am new to this codebase, So it would be great if you could provide any guidance.

**Comment by alex-signal** [comment]
@PanchumarthiAbhinav Notifications stuff is kept in the `org.thoughtcrime.securesms.notifications.v2` package. This is likely a bug due to Android 14, either something new with PendingIntents or Notifications we need to add, or an actual bug in whatever beta build the user is on (because as far as I'm aware, A14 doesn't officially release on Pixel devices until October 4th, let alone however long Samsung will make users wait)

**Comment by gooomis** [comment]
Hi Team,
With the release of stable Android 14 for S23 series and this bug still existing (at least for me) could we investigate?
If there is anything that you'd need me to do/provide/log let me know.
