### ISSUE TITLE
Signal messenger - no access to gallery media

### ISSUE THREAD

**Issue by FireRobW** [signalapp/Signal-Android#13179]
Signal  messenger version 6.33.3
Device used: Galaxy Xcover 5 SM-G525F/DS
System version: Android 13, OneUI 5.1
 
I like to access gallery media to import them into Signal messenger. But the gallery page at Signal seems to be empty. But it isn't empty...
 
Screen shot for reference:
https://justpaste.it/img/287bdeb8f91bf1ea921186ae37ebf621.png
 
I de- and re-installed Signal several times and in different versions. But no success in this matter. Any needed acces permissions in Signal should be ok. Because when installing Signal it asks automatically to confirm them anyway.
 
Did I overseen anything...?

**Comment by alex-signal** [comment]
@FireRobW Some permission changes happened when we upgraded our target API to 33. Could you please post a debug log? (Settings -> Help -> Debug Log)

**Comment by FireRobW** [comment]
Please find the log file attached for reference.
[log.txt](https://github.com/signalapp/Signal-Android/files/12701522/log.txt)

**Comment by alex-signal** [comment]
@FireRobW Could you try denying the permissions for media access in the Signal permissions section of App Info (Long press signal icon, and hit app info)

There were some permissions changes here related to API33 and while it looks like you should have the MEDIA_IMAGES permission, you don't have the MEDIA_VIDEOS permission so I'm wondering if perhaps something is getting stuck.

**Comment by unickorn** [comment]
Experiencing the same issue, I had just installed the app a couple minutes ago.

I denied images and video permissions in app info and it did prompt me again with the permission request, but still did not fix the issue.

**Comment by FireRobW** [comment]
@alex-signal
 
I denied images and video permissions in app info. The app requesting me again to confirm the permissions. So the issue is still not fixed.

**Comment by alex-signal** [comment]
@unickorn @FireRobW Could you both share new debug logs? It lets me see the permissions the app thinks it has and might help me diagnose the issue.

**Comment by unickorn** [comment]
Here it is;

![signal-log-1695842922106.zip](https://github.com/signalapp/Signal-Android/files/12742608/signal-log-1695842922106.zip)

**Comment by alex-signal** [comment]
That is very strange. When the dialog pops up, does it say "Allow signal to access photos *and videos* on this device?"
It still has READ_MEDIA_VIDEO marked as false.

**Comment by unickorn** [comment]
I am accessing it by trying to change my profile picture. This is the prompt, sorry that it's German but you can clearly see it is indeed asking for Video as well :)

![SmartSelect_20230927_230311_Permission controller.jpg](https://github.com/signalapp/Signal-Android/assets/29836508/7b88e898-5aae-40b8-9d84-d19352e1e35c)

**Comment by unickorn** [comment]
Hmm I just tried to send a story using the camera, and interestingly enough, after asking for Camera permission the issue now seems to be fixed.

**Comment by FireRobW** [comment]
@unickorn
 
Thank you for giving this hint. It really works. But I think that not really many new users trying it. They fast go away again from Signal and do not like to contact the support straight afterb first installing the app. Sad.
 
@alex-signal
 
Following attacht two ZIP files - containing the log data BEFORE and AFTER I tried the hint of @unickorn.
 
Perhaps you can find any usefull difference of data helping you to find the reason of that bug.
Good luck. ;-)

**Comment by alex-signal** [comment]
Hi folks, this issue should be resolved in version `6.35.x` which is currently in beta.

**Comment by FireRobW** [comment]
That's great. Thank you for your work. :-)

**Comment by Psypher1** [comment]
This is an issue once again
