### ISSUE TITLE
JSON fails to import yet disables accounts in the process

### ISSUE THREAD

**Issue by Mailaender** [signalapp/Signal-Android#13184]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to migrate my phone manually after the account transfer failed. https://github.com/signalapp/Signal-Android/issues/13185

### Steps to reproduce
- I exported my account as JSON on my old phone.
- Imported the JSON on my new phone

**Actual result:** Failed to import. Added an empty account on the new phone. Disabled my account on the old phone.

**Expected result:** It should have imported the complete profile.

### Device info
**Device:** ASUS Zenfone 10
**Android version:** 33.0220.0220.52
**Signal version:** 6.33.3

### Link to debug log
Shows a forever loading screen. Probably another bug.

**Comment by alex-signal** [comment]
Hi, by JSON do you mean the normal chat backup option in settings?

**Comment by Mailaender** [comment]
Yes, the one which lets you choose between TXT or JSON.

**Comment by cody-signal** [comment]
Hi @Mailaender, sorry for the confusion but that file is a report generated by Signal for your own personal records. It is not something to be imported or used to transfer an account to another device. There is no import flow for this record file.

You want to use Settings->Chats->Backup if you want a physical file backup of your install or the Device Transfer screen.

**Comment by Mailaender** [comment]
Sadly, that options is greyed out after I did the wrong import.
