### ISSUE TITLE
Using Signal in split screen or pop up views no longer works on Android

### ISSUE THREAD

**Issue by sahaskatta** [signalapp/Signal-Android#13182]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No longer able to use Signal "open in split screen view" or "open in pop-up view" on Android 13.

### Steps to reproduce
- Open Signal app
- Swipe up from bottom to see open apps
- Click Signal icon at the top

**Actual result:** The context menu that appears is missing "open in split screen view" and "open in popup view".
**Expected result:** Until a very recent update, the context menu permitted "open in split screen view" and "open in popup view".

### Screenshots
https://github.com/signalapp/Signal-Android/assets/221064/3f193a1e-e0ed-49bf-b880-5a0136139619

### Device info

**Device:** Samsung Galazy Z Fold4
**Android version:** 13
**Signal version:** 6.33.3

**Comment by mickonep** [comment]
I have signal version `6.36.5` and unfortunately split view do not work

**Comment by nicholas-signal** [comment]
> I have signal version `6.36.5` and unfortunately split view do not work

Are you able to share a debug log?
