### ISSUE TITLE
Message synchronization takes enormously long time so normal use of the application is not possible

### ISSUE THREAD

**Issue by mtzea** [signalapp/Signal-Android#13188]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I turn on the phone with Signal Android app (or the phone doesn't have internet connection and it is regained, the same behaviour) after using the Signal Desktop app when the phone was turned off the messages take an enormously long time to synchronize on the Android app, to the point that for an extended period of time (depending of the number of messages exchanged, however, the time can generally be counted in tens of minutes minimum) it is not possible to use the app normally (try to exchange messages with someone without seeing the latest messages because even the older ones haven't been synced yet, good luck). It also happens that the Android application can no longer keep up with the synchronization of messages exchanged via the desktop application even when the device is turned on and it has the stable internet connection.

As I was digging into the adb logs I've noticed two unusual things:

```
09-25 20:43:35.910  6812  6977 W MessageFetchJob: null

09-25 20:43:35.910  6812  6977 W MessageFetchJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: Failed to pull messages.

09-25 20:43:35.910  6812  6977 W MessageFetchJob: 	at org.thoughtcrime.securesms.jobs.MessageFetchJob.onRun(MessageFetchJob.java:75)

09-25 20:43:35.910  6812  6977 W MessageFetchJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)

09-25 20:43:35.910  6812  6977 W MessageFetchJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)

09-25 20:43:35.910  6812  6977 W MessageFetchJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

09-25 20:43:35.910  6812  6977 I BaseJob : [JOB::571d70bd-b304-440f-989c-b87aae964e5f][MessageFetchJob] Encountered a retryable exception. (Time Since Submission: 61547 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __notification_received)

09-25 20:43:35.910  6812  6977 I BaseJob : org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: Failed to pull messages.

09-25 20:43:35.910  6812  6977 I BaseJob : 	at org.thoughtcrime.securesms.jobs.MessageFetchJob.onRun(MessageFetchJob.java:75)

09-25 20:43:35.910  6812  6977 I BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)

09-25 20:43:35.910  6812  6977 I BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)

09-25 20:43:35.910  6812  6977 I BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```
It appears from time to time in my logs (it may have Run Attempt: 2/3 and 3/3) but I don't see if it has the connection with my issue.

And another thing from DeadlockDetector:
```
09-25 20:45:17.955  6812  8509 W DeadlockDetector: Found a long block! Blocked for at least 5000 ms.

09-25 20:45:17.955  6812  8509 W DeadlockDetector: -- [563] signal-JobRunner-2 | WAITING

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.lang.Object.wait(Native Method)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.lang.Thread.parkFor$(Thread.java:1220)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: sun.misc.Unsafe.park(Unsafe.java:299)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:843)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1172)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:181)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:257)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.thoughtcrime.securesms.crypto.ReentrantSessionLock.acquire(ReentrantSessionLock.java:18)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.crypto.SignalSealedSessionCipher.encrypt(SignalSealedSessionCipher.java:42)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.crypto.EnvelopeContent$Encrypted.processSealedSender(EnvelopeContent.java:90)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:121)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2421)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2378)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1984)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:232)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:125)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

09-25 20:45:17.955  6812  8509 W DeadlockDetector: 

09-25 20:45:17.955  6812  8509 W DeadlockDetector: 
```
And these locks appears in period of time between two messages are synched. So maybe my issue is an effect of a deadlock?

I don't know if it is somehow related to each other but I also experience the behaviour described in issue #13134 

### Steps to reproduce
- use the Signal Desktop app when the phone with Signal Android app isn't able to sync the messages (turned off or without internet connection)
- make the Signal Android app able to sync messages

**Signal version:** 6.33.2

**Comment by cody-signal** [comment]
If you are weilling to share your full debuglogs from within Settings->Help we can take a deeper look.

**Comment by mtzea** [comment]
Sure, here you are @cody-signal https://debuglogs.org/android/6.33.3/3e16abada50f828fac433ff32545868336296adb1d3730803887c6f98c204804

I've also noticed that in time when this issue occurs the org.thoughtcrime.securesms uses a lot of my CPU, far more than the other apps I use.

If there is anything I can help with to solve this issue, I will gladly help.

**Comment by cody-signal** [comment]
Thanks! Appreciate the full log. We'll look into it.

**Comment by mtzea** [comment]
Update from me, maybe this will help you somehow in resolving this issue. It's getting worse as time goes on, messages are loading longer and longer with the passage of time since I face this issue.

**Comment by mtzea** [comment]
Another update from me. I've just checked that I am unable to make and receive calls via Signal when the app is "desynced".

**Comment by mtzea** [comment]
@cody-signal any progress in investigating the issue? Now I am completely unable to use Signal on my phone because of it.
I've updated to 6.35.3, nothing have changed.
