### ISSUE TITLE
Account transfer takes forever

### ISSUE THREAD

**Issue by Mailaender** [signalapp/Signal-Android#13185]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to migrate my account to another phone.

### Steps to reproduce
https://support.signal.org/hc/de/articles/360007059752#android_restore

**Actual result:** Loading screen without progress indication. Both phones turn dark.

**Expected result:** It should have imported the profile or at least tell me what went wrong.

### Device info
**Device:** Pixel 5
**Android version:** TQ3A.230805.001
**Signal version:** 6.32.4

### Link to debug log
https://debuglogs.org/android/6.32.4/1141955578c11ed674e1e408fafa0b7195f0841021e97e9c39bd9e34f8435f8f

**Comment by Genis-Sage** [comment]
@Mailaender 
according to your log, your Signal Installation has no permission for location, which is needed for the transwer via Wifi Direct

can you allow location access, and try it again?

side note:
#13173 is about the fact, that Signal does not request the permissions at that point - this is fixed in the current beta release

**Comment by Mailaender** [comment]
I can't repeat it. The account transfer is greyed out due to https://github.com/signalapp/Signal-Android/issues/13184.

**Comment by Mulugruntz** [comment]
I'm facing the same issue.

To avoid opening a new one, here's my debug logs
https://debuglogs.org/android/6.40.4/5fea388875568a0eaf2c3425844e1487186110f5762315a9bb1ee80a1da0dde9
