### ISSUE TITLE
Huge privacy concern

### ISSUE THREAD

**Issue by ViktorKahu** [signalapp/Signal-Android#13196]
.

**Comment by Herohtar** [comment]
No, that is not the case. Contacts are not synced to new registrations unless they are able to provide the Signal PIN that was associated with the previous account.

The new owner will have a completely new account and their profile will not be shared with any of your contacts nor will they be able to see any of your contacts.

The only possible issue would be if your contacts were not aware that you were no longer using the old number and decided to message you *and also ignored the safety number change warning* that indicates that they may no longer be talking to the same person.
