### ISSUE TITLE
hcaptcha loop on motorola moto g42

### ISSUE THREAD

**Issue by Carpspb** [signalapp/Signal-Android#13192]
Dear experts,
just insalled the one and only signal app on my new motorola moto g42 phone (6GB, Android 12) yesterday. Today afer actualising my contacts in signal it accurs a loop in hcaptcha verification process. Three times four times, then I gave up trying to complete the verification. Unfortunately I now can not send any messages because signal says that only after completing the messages could be sent.
Please, it whould be nice if you could fix it. Thanks in advance

**Comment by cody-signal** [comment]
Sorry you're hitting this, can you provide a debuglog so we can try and see what's happening? You can get a link from going to Settings->Help->Debuglog, submitting it, and posting the link here.
