### ISSUE TITLE
When receiving registration code via phonecall, Signal jumps out of code entering view back to enter phone number view.

### ISSUE THREAD

**Issue by pjylkka** [signalapp/Signal-Android#13190]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
At least in here Finland you may have your old wired phone numbers as a mobile number;
When trying to register this number on Signal, it says there's an error on sending registration code by SMS. (Well at least in Finland SMS works just fine on these numbers, but that's not really the problem I describe here.)

### Now what happends / steps to reproduce
=> Signal suggest for having a phone call for receiving the code, I admit this.
=> Signal changes to the code entering view, and phone rings.
=> I take the call and bot gives me registration code.
=> I hang up and jump (android square button), back to Signal;
=> Signal jumps out of the code entering view, back to the view it asks for the phone number.

For the half second I even saw that Signal is still on code entering view (if that view didn't come from android cache), but never have a change to enter the code. After that everything starts from begin; can't receive SMS, so I take a phone call, get back to code entering view, signal jumps out of the view back to the enter phone view.  After couple of tries Signal starts to delay tries.

### Suggestion
Remove code that forces signal change back to the phone number entering view, and/or add "I have registration code" button on the view.

### Screenshots
Not required, problem is self explanatory

### Device info
**UPDATED INFO**: Signal is running as a Cloned app due of Dual SIM
**Device:** Nothing Phone 2
**Android version:** Android 13 with Nothing OS 2.0.3 GUI
**Signal version:** 6.33.3

### Link to debug log
Can't get on log as at this point only option behind three-dot-menu is "Use proxy"

**Comment by cody-signal** [comment]
If you tap on any title in the registration flow 8 times you can get a debuglog.

Do you happen to have "don't keep activities" enabled in the developer settings? If so, try disabling that and trying again.

**Comment by pjylkka** [comment]
> Do you happen to have "don't keep activities" enabled in the developer settings? If so, try disabling that and trying again.
Developer settings are at their defaults. I checked this anyway and "don't keep activities" was disabled.

Weirdest thing is, I've I tried this like on four times before and every time was the same. But today, it did not do it anymore. I thought if Signal has updated, but version is still 6.33.3.

When I hang up the, phone entered back to the Signal code entering view.
I tried to make sure if the problem was me changing manually back to Signal;
=> Cancelled code enter, and wiped app out of the memory and started again.
=> Received phone call, got code
=> Changed view manually back to signal.
=> Code entering view remained on the screen.

> If you tap on any title in the registration flow 8 times you can get a debuglog.
Oh this is nice to know, thank you. Now I can enter to debug log but pressing Submit says  "Failed to submit logs"
Tried with wifi, tried with mobile data as well. I confirm - internet is working.
There's no any third party firewall apps of anything of any sort.

### Things that were different at this try
- I changed phone language to english to find "don't keep activities" setting via search.

### Forgot to mention when opening issue (Updated in op):
- I have dual sim, and this Signal is working as cloned app

Let me know if you want to investigate this case any further, I'll be happy to remove/recreate clone for bughunt, or should I close the case?

**Comment by cody-signal** [comment]
Thanks for the follow up. If you can come up with consistent repro steps we can take a look again. But for now, we can close this.
