### ISSUE TITLE
Problem with my posts in the Signal community / MuerteRoja

### ISSUE THREAD

**Issue by MuerteRoja** [signalapp/Signal-Android#13205]
Hello, good afternoon, yesterday I created an account in the Signal community, my name is MuerteRoja and the email that I have associated with my account is facundomultimediafocan@skiff.com in the “Request Features” section I have created a new topic where I suggested implementing usernames in the Signal application as in the Telegram application, however, I do not see any records about this post that I created, it does not appear in my profile, the last thing I saw was a poster where it said that my post had to be approved by a community administrator, I have seen that there have been people creating new posts and, however, mine does not appear

**Comment by Herohtar** [comment]
Please don't post on the GitHub repository about forum issues. This is not a bug.
