### ISSUE TITLE
Use the image picker Element X uses, get rid of file permissions

### ISSUE THREAD

**Issue by firefoxlover** [signalapp/Signal-Android#13201]
I didnt know this existed, but then I saw it in Element X. 

Android has a really awesome image filepicker portal, which is en par with the Signal one. 

Using it could make Signal work with less trouble, decrease attack surface and increase privacy.

[Here is the Element X repo](https://github.com/vector-im/element-x-android)

**Comment by nicholas-signal** [comment]
Hello,

Please share feature requests on our community forum, as we reserve the GitHub issue page for bugs & crashes.

Join us here: https://community.signalusers.org/c/feature-requests/android-feature-requests/18

Thanks!
