### ISSUE TITLE
UX Issues on Screen Lock timeout menu

### ISSUE THREAD

**Issue by EnronEvolved** [signalapp/Signal-Android#13202]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to set up a screen lock for Signal, but the timeout menu is not very intuitive or functional. There isn't a button for inputting zero, or an obvious way to delete numbers, so the timeout is currently stuck at 1h11m with no way of modifying it.

(Unrelated, but I was able to set a passphrase for the app itself up until very recently, when I switched to a new phone, has that feature been removed? If so, I am disappointed, as I liked being able to put separate security measures in place. What happened to manually locking the app, too?)

### Steps to reproduce
- Turn on screen lock
- Attempt to set timeout

**Actual result:** Resulting menu cannot be used to configure the timeout appropriately (for reasons described above).
**Expected result:** A usable timeout menu

### Device info

**Device:** Sony Xperia Z5 Compact
**Android version:** 7.1.1
**Signal version:** 6.33.3

**Comment by nicholas-signal** [comment]
Just to confirm:

You're referring to this screen, right?

https://github.com/signalapp/Signal-Android/assets/112583042/8a65c615-c91c-45c4-b674-b1c332e8ceac

**Comment by EnronEvolved** [comment]
That is correct, the bottom row of buttons is missing.

**Comment by nicholas-signal** [comment]
Ah, you're saying that the dialog is not formatted properly on the Z5 Compact?
