### ISSUE TITLE
Heavily distorted audio when making Signal calls through Bluetooth headunit

### ISSUE THREAD

**Issue by 0xunusedusername** [signalapp/Signal-Android#13207]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When making or receiving a call via Bluetooth through the car head-unit, the audio quality is garbled and robotic; even the dialing tone is distorted. The other call also hears my voice but unrecognizably distorted. Updated head-unit firmware and it's still not working.

Works fine over Bluetooth earbuds.

Other Bluetooth audio outputs work: other phone calls, Signal voice messages, music, navigation, browser.

### Steps to reproduce
- Connect to car Bluetooth
- Make or receive a Signal voice call

**Actual result:** Unusable audio ensues.
**Expected result:** Normal, clear, Signal call audio. It was previously working.

### Screenshots
Not needed

### Device info
**Device:** Google Pixel 7
GrapheneOS Version: 2023100300
**Signal version:** 6.35.3

**Comment by nicholas-signal** [comment]
We do not have any special handling for head units vs. other headsets; perhaps an issue between your phone and your head unit with negotiating a Bluetooth SBC link? If you add a debug log, we can see if the phone's Bluetooth stack prints any errors it encounters.

**Comment by mshxd** [comment]
@nicholas-signal here's the log: https://debuglogs.org/android/6.35.3/53a2cb0caafdf29be1d04961ceb53902bfec3cb6d3123572c8a9badf8920ea23

is it possible to have it purged after reading?

Tried repairing, changing audio codec. Everything else is still working, including VoIP. Not sure why this issue is specific to Signal calls.

**Comment by mshxd** [comment]
Any thoughts on this @nicholas-signal ?

**Comment by nicholas-signal** [comment]
I see in the logs that the phone is able to successfully connect to Bluetooth devices without error, except on one occasion where it looks like the selected Bluetooth device was unavailable (could be caused by something as innocuous as the device being out of range).

For some context: on Android 12+, we simply just ask the OS to change the audio device for us, and do not manage the connection or codec ourselves. See the API call here: https://github.com/signalapp/Signal-Android/blob/3d94122abc1ac2685230faad7322d405cb631013/app/src/main/java/org/thoughtcrime/securesms/webrtc/audio/AudioManagerCompat.java#L138

I know you mentioned updating your head unit firmware already, but have you tried updating your phone's firmware?

**Comment by mshxd** [comment]
@nicholas-signal Hi Nicholas, my phone is running the latest firmware. I guess a factory reset is the only thing that would help at this point?

**Comment by nicholas-signal** [comment]
I can't promise that a factory reset will fix it; all I can say is that wherever the problem lies, it's caused by something in a layer beneath the Signal application.

**Comment by mshxd** [comment]
@nicholas-signal Alright, thanks for looking. I'll look into getting a test device to see if I can isolate it.

Is it possible to get my log purged for privacy?

Thank you

**Comment by mshxd** [comment]
@nicholas-signal factory reset the head unit and tried another Android device; issue still persists.

**Comment by nicholas-signal** [comment]
> Is it possible to get my log purged for privacy?

Feel free to edit out the URL from your comment so it's un-indexable, and our log retention rules will take care of the rest.

> factory reset the head unit and tried another Android device; issue still persists.

Unfortunately, without access to your specific head unit, it's going to be practically impossible to figure out what's going wrong. Feel free to share the specific SKU you're having trouble with, but I want to set expectations properly that we cannot realistically support device-specific bugs in the over 1,000 different Android Auto head units out there.

**Comment by mshxd** [comment]
Sony XAV-AX6000

> > Is it possible to get my log purged for privacy?
> 
> Feel free to edit out the URL from your comment so it's un-indexable, and our log retention rules will take care of the rest.
> 
> > factory reset the head unit and tried another Android device; issue still persists.
> 
> Unfortunately, without access to your specific head unit, it's going to be practically impossible to figure out what's going wrong. Feel free to share the specific SKU you're having trouble with, but I want to set expectations properly that we cannot realistically support device-specific bugs in the over 1,000 different Android Auto head units out there.

I understand, just doing what I can at least.

Sony XAV-AX6000

**Comment by 0xunusedusername** [comment]
Solved after a deep investigation.

In the event anyone else stumbles on this and is having a similar issue:

This is an issue with the Bluetooth hardware in certain Sony head units. The problem arises if the system Bluetooth call volume is above the minimum value. If it is, it will overload the BT receiver in the head unit and distort the audio. 

Set the system BT call volume to minimum, only control the call volume from the head unit, and it will work as expected.

**Comment by CapricanDRJ** [comment]
I have this problem without other hardware. It has happened off and on to friends and myself for the last 3 years. There is another issue that was closed without solution and appears to be duplicate https://github.com/signalapp/Signal-Android/issues/7253

While I don't use bluetooth devices, I have found that connecting and disconnecting a bluetooth device seems to reinitialize the mic. Restarting also tends to work. I would assume that another app had changed something and signal doesn't properly re-initialize it until a device is connected/disconnected. If it was the windows 3.11 days, the issue sounds like the wrong bitrate on a sound card.

**Comment by 0xunusedusername** [comment]
> I have this problem without other hardware. It has happened off and on to friends and myself for the last 3 years. There is another issue that was closed without solution and appears to be duplicate #7253
> 
> While I don't use bluetooth devices, I have found that connecting and disconnecting a bluetooth device seems to reinitialize the mic. Restarting also tends to work. I would assume that another app had changed something and signal doesn't properly re-initialize it until a device is connected/disconnected. If it was the windows 3.11 days, the issue sounds like the wrong bitrate on a sound card.

Yeah, it's pretty disappointing.

If I want to make a Signal call over the BT unit I have to call, immediately end it, then call again to get the mic to work. Signal is the only app that has this issue for me.
