### ISSUE TITLE
Messages received when switching devices are silently lost

### ISSUE THREAD

**Issue by Keisial** [signalapp/Signal-Android#13211]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as expected
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Scenario:

0. Alice, Bob and Charlie are in a group chat
1. A backup is made from Alice app
2. Alice device is shattered into pieces
3. Bob sends "＠Alice, will you marry me?"
4. Alice installs Signal on a new device, restoring the backup from (1) and correctly providing the Signal PIN

### State:
* Alice sees the chat history but not the message (3)
* Bob and Charlie see the full chat, including the message (3)

From their point of view, Bob proposed to Alice, and Alice ignored it, choosing not to answer. In fact, Alice didn't get that message and doesn't know she missed anything.

Bob and Charlie might see a notification at (5) that the safety number of Alice has changed, but that would give no information on what data (if any) was not seen by Alice (not even that is happening here, since Alice is restoring from a backup, there's no change of safety numbers).
Bob will even see a double check on his message, since _Charlie_ did receive and read it. He could see that the message was never delivered to Alice in the 'Message details' window, but that would require actively checking.

For comparison, WhatsApp would have shown a placeholder while awaiting for Bob to come online, and then get that message, reencrypted by Bob's device. Not resending automatically old messages to a new device is a feature for Signal. But *silently* dropping them, unbeknownst to both sender and receiver, is a bug.

This has been been previously discussed on issue #11373 and https://community.signalusers.org/t/what-happen-to-those-undelivered-messages-when-a-recepient-reinstalls-signal/6758 where it is found that the server clears the ephemeral queue, dropping those in-flight messages.

Some options would be:
* Do not clear the ephemeral queue, but send the (unreadable) message to the new device (or a simplification of that), so that it shows on those chats that there were missing messages (this assumes that it could still be tied to a chat, that may not be possible)
* Return those messages to the sender, so that the sender is alerted they were not delivered (may need some changes to the format)
* When receiving a safety number change from Alice, make Bob client check in reverse order the messages it sent until the first one acknowledged by old-Alice (or old-Alice joining the chat), and add a note to the safety number change message that Alice didn't receive the last N messages he sent (if N > 0). (easier, as it can be done client-only, although that verifification might be a bit expensive if there are a lot of unacknowledged messages, there could be a limit after which it is shown as 'more than N')

**Comment by Rorschach1010** [comment]
I second this and I find it strange and concerning, that this was never addressed by neither devs nor more than a handful of users. You just have to loose your phone or get the OS wrecked by an OEM update (which depending on the manufacturer, can happen) and everyone who sends you a message during that time, till you reinstalled it, will never arrive and just vanish.
Not every user uses Signal for trivial messages to family members. Some messages are very important.
