### ISSUE TITLE
Signal APK flagged as malicious by Google PlayProtect and Virustotal

### ISSUE THREAD

**Issue by ILoveFOSS** [signalapp/Signal-Android#13219]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------
Hi and sorry for using the issues page, but I do not want to open an account on the community forum.

I am using the Signal Website APK version (https://signal.org/android/apk/) which I usually update immediately when an update notification is shown. Today, the update notification was prompted and offered to install version 6.35.4. During installation, Google Play Protect warned that Signal is stealing contacts and information and tried blocking the update process. Because of the warning, I downloaded the APK directly from your website and let Virustotal check it. The scan result is that TrendMicro House Call flags it as a trojan.
![image](https://github.com/signalapp/Signal-Android/assets/81854757/b23897f2-ccfc-49b4-91a8-666a6d545752)

EDIT: Here the link to the scan result https://www.virustotal.com/gui/file/47a6512b19327932b14350128a95a03159e4a317b5d2893cdffec6ffc9e06a3b?nocache=1

After researching, I ignored Google PlayProtect's warning and updated. When opening Signal I am now greeted by this notification:
![image](https://github.com/signalapp/Signal-Android/assets/81854757/af34fce9-0a59-4456-a7d6-ebedf3f26fd4)
(The warning basically has the same content as in the screenshot in comment 2)

Not sure what exactly is going wrong, but you might want to contact google and trend micro about this.

Thank you for this great app nonetheless!

**Comment by thm-unix** [comment]
Confirm, has this issue too.

**Comment by thm-unix** [comment]
![image](https://github.com/signalapp/Signal-Android/assets/84270488/26397283-721b-43e3-b798-1ce2f6fdc33a)

Should this URL be here? This list is part of VirusTotal's behavior report

**Comment by ILoveFOSS** [comment]
As an addition to previous comments: 
![image](https://github.com/signalapp/Signal-Android/assets/81854757/c00ced2c-f144-4968-9053-61e7ad8fad0f)

Seems like a bundled file could trigger the issue as it is also flagged as malicious (but looks like that result is based on heuristic checks instead of binaries)

**Comment by thm-unix** [comment]
Some new info on this topic. Downloaded an old APK file of Signal (6.13.7) via Wayback Machine, tried to test it on VirusTotal and got quite a bit different result (2 vendors believe it's malicious).
https://www.virustotal.com/gui/file/40f33f3db8cc5716e51eddb407b0d679ee5cb9712066f0917b2fa1a4093487c2/detection

**Comment by thm-unix** [comment]
By checking old versions one-by-one found out the first version that was flagged as malicious. That's 5.19.4 from August, 6th, 2021. Since then every Signal version is shown as malicious by TrendMicro-HouseCall

https://www.virustotal.com/gui/file/d5bf11a1af4c847ee990e84904b2ec0811f7a44a2aa5d17a4987163984e4dd74?nocache=1

**Comment by TheCapsLock** [comment]
I, it seems it has been introduced arround 6.35.0 : 

- 6.35.0 : https://www.virustotal.com/gui/file/2ed0011728693de1a03bf5d7c3fa1d412497b188d25d68900331b0cfbf0a1d6c?nocache=1
- 6.34.4 : https://www.virustotal.com/gui/file/c173e729d9ccee1efecd35d6901594c232a545b2cb929e40ecb0f8110e5050d0?nocache=1

**Comment by cody-signal** [comment]
Hi,

Thanks for reporting this.

This warning was shown in error due to a bug specific to Google Play. This message was not related to Signal.

Google has resolved the issue. You should now be able to download and install Signal without further problems.

If you need additional help, please let us know.

**Comment by harut420** [comment]
Hi, i see  this and not really understagin why it happens, i use download from APK version 6.36.5 .
i have done a netwwork capture and wireshark show this :  connection to 35.207.91.29  port 80 and packets are those following TCP flow  :
....!..Bx6hqkAOc0mSv...........@!..Bx6hqkAOc0mSv.	......Unauthorized....07b88d3d3854efb1...
signal.org...(....<
....!..Bx6hqkAOc0mSv...........@!..Bx6hqkAOc0mSv.	......Unauthorized....07b88d3d3854efb1...
signal.org...(....<
...\!..BCCONKNpUz+n/............1698500649:532985821...
signal.org......07b88d3d3854efb1........c.|...a....5}<.....@!..BCCONKNpUz+n/..........._. .......ef..
.....X....Q..2...L.........\. .(...._{...`!..BrRlpPP75moyu.......5..B.....1698500649:532985821...
signal.org......07b88d3d3854efb1....EG'.o.n.\.ET+.#.
.V.... !..BrRlpPP75moyu.....~Hq.	...$S.)!..n.]j.(..0......x!..B......N..iS....`...L!..B1g9EnseHhRPj...	OIjv:PeuA....W.....
.)...4.xe....$..n~!..........Ofm?z....|.P..g.(..-..N.......5..B..(.........p!..B6ul4jcUy5GqY.......5..B....`...L!..B0RvzOkflayYH...	PeuA:OIjv....W.....
.*..a....K.j.$..n| ........0......
w.fY...k..(....3X...P!..BVkfX/os4iMKZ.......5..B....@...,!..B1g9EnseHhRPj. .....5..B.......M.u.*em.x.$.[..CM..(....."...X!..B.R1mgk.....v...@...,!..B0RvzOkflayYH. ........._....p\.#...x...4..up.aD..(...d{........5..B..(..&..I...`!..BsetZpeC8vohP..........B.....1698500649:532985821...
signal.org......07b88d3d3854efb1......Ex..
_......	F...d...`!..B9yw8kAlgPyhw..........B.....1698500649:532985821...
signal.org......07b88d3d3854efb1....SWP....\.x..`.*x'o.T... !..BsetZpeC8vohP....f.
F
k.?.|0.{.'.:3\D.(..._.,... !..B9yw8kAlgPyhw....M8..rx.k.UE".RR.U.y'.(.........x!..Bu8!............`...L!..B0F3UjP42geW1...	OIjv:PeuA....W.....
.)...4.xe....$..n~!.......4...wN.I...!..,.Y..(..f{.0.......5..B..(.....D...x!..B..c.F.iH..M....`...L!..B7BYtffiOC8mE...	OIjv:PeuA....W.....
.)...4.xe....$..n~!..........f..d}O...*^.S...(.............5..B..(...s.w...P!..Bwd8fWTRxcsYM.......5..B....@...,!..B0F3UjP42geW1. .....5..B......v!.}.F....8.,.L..~5.(.........P!..BYDCNgY2jGOv7.......5..B....@...,!..B7BYtffiOC8mE. .....5..B.....p'	..~r..$.....	.....(....o....\!..B0m6HcU0LvUEK.
..........1698500649:532985821...
signal.org......07b88d3d3854efb1....r$....-...?M\.n....h...(!..B0m6HcU0LvUEK.
.............z.j...:|.....P~...(......

would be nice to understand what it is.
