### ISSUE TITLE
Signal 3.36.1 showed a blank screen after upgrading to Android 14

### ISSUE THREAD

**Issue by hborders** [signalapp/Signal-Android#13221]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I upgraded my Pixel 7 Pro to Android 14, and Signal is now showing a blank screen. All of my conversations are gone. I sometimes get a `Checking for messages...` foreground notification and then a `You may have new messages` notification. I didn’t see a place on the official site to report bugs, so I opened a 

### Steps to reproduce
- Open Signal
- Start an Android 14 upgrade
- Switch back to Signal
- Restart your device when the Android 14 upgrade completes

**Actual result:**
A `Checking for messages...` foreground notification shows every minute or so. A `You may have new messages` notification shows after.
Tapping the `You may have new messages` notification or opening the app from the launcher shows a blank screen with the `Chats` and `Calls` buttons on the bottom. I can swipe down to filter by unread, but nothing changes because no conversations are available.
**Expected result:**
My conversations show as expected.

**Workaround**
I force-quit the app to capture a log and everything recovered `:lolsob:`

### Screenshots
I can't capture a screenshot anymore because the issue resolved itself after I force-quit the app to capture a log.

### Device info

**Device:** Pixel 7 Pro
**Android version:** 14
**Signal version:** 3.36.1

### Link to debug log
https://debuglogs.org/android/6.36.1/ed9d944d54bfa66b4e686f90589b259ec9eebf4ededfec88927fb7babb6d6441

**Comment by marcogabriel** [comment]
Experienced the same problem, fixed it by force quit the application and restarted Signal. (Thanks @hborders)

**Comment by alex-signal** [comment]
Hi! I believe you've hit a bug here around a race condition with our job manager initialisation. I believe we've got a working approach for a fix for this to ensure it doesn't happen to others, but I'm glad you were able to get Signal working via an app restart.
