### ISSUE TITLE
Attachment download fails with RangeException, InvalidMacException, PushNetworkException, starting at 20231011

### ISSUE THREAD

**Issue by smigniot** [signalapp/Signal-Android#13222]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting at 20231011, image and video download stopped working. I have reinstalled (twice) since then and reproduced the bug : my contact (has worked flawlessly the last 5 years) sends an image or a video, a notification appears on my side and clicking on the Image or Video download icon fails. I did nothing obvious or unusual as an end user.

The application log (logcat) shows a PushNetworkException (did some IP stopped responding on signal servers side ?) an InvalidMacException (a consequence ?) and a RangeException (interesting, seems to happen at the *end* of the download, as if trying to download *more* than the actual data length).

Interestingly, other contacts do not have the problem, as Alice, if I'm part of a group with Bob and Carol, then Bob sends a picture, Carol sees it (but I still fail to "download the attachment" from Alice, in the same group). Please find joined both a video capture (redacted) and the debug log

### Steps to reproduce
- Contact Bob sends a picture
- As Alice I receive a notification
- As Alice I'm puzzled that the picture did not download automatically
- As Alice I click on "Image" which is supposed to download the picture
- The progress ui component .. progresses, and at the end no picture is displayed
- Reproduce ad libidum : Clicking several times does not end up in a success

**Actual result:** The image/attachment is not downloaded
**Expected result:** The image/attachment should be downloaded, and displayed

### Screenshots

https://github.com/signalapp/Signal-Android/assets/19796901/c9ab81ca-805c-442b-a5d9-3cddd803f9ce

### Device info

**Device:** HUAWEI NEM-L51
**Android version:** 6.0, API 23
**Signal version:** 6.28.6
Available in the debug log of course

### Link to debug log

https://debuglogs.org/android/6.28.6/9d6c8b39453e1941126eb970952fb86cf8eddeba0a363cb7ebb4a060fbbbaef4
Can reproduce reliably and produce more logs if needed

Additional information : This is a rooted device, and a self-compiled Signal-Android.apk ! **but** I (always, been 5 years already) compile the original source code found on github, with a single modification : PlayServicesStatus getPlayServicesStatus(..) always return PlayServicesStatus.MISSING

**Comment by smigniot** [comment]
Proposal to : CLOSE

Reason : Recompiled from github version 6.35.3 (with libwebp 1.3.2).
Attachment download now works. Problem resolved from the end-user side
1. So the problem disappeared, I have absolutely no clue of the root cause
2. Reinstallation was not the issue (done several times) and upgrade solved it

**Comment by alex-signal** [comment]
This was caused by a sender-side bug around incremental MACs. It's been resolved in the latest production version.
