### ISSUE TITLE
Transfer to new device => Disappearing messages lost?

### ISSUE THREAD

**Issue by LMSSonos** [signalapp/Signal-Android#13229]
I transferred signal to a new device. I was quite surprised to find out, that disappearing messages are not copied over. I know they are excluded in the backups and understand that, but I did not expect this when transferring to a new device.

In case this is wanted, just close this. issue.

If wanted, maybe add a message showing that these messages will be lost.

**Comment by cody-signal** [comment]
Yeah, this is behaving as implemented. We are working through some backup changes this quarter so this may change eventually.

**Comment by Machion** [comment]
I was also very surprised about that. 
Would be nice, if one can decide during backup what to include > [Feature request] :)
