### ISSUE TITLE
Some received images aren't loaded and can't be downloaded

### ISSUE THREAD

**Issue by ralf401** [signalapp/Signal-Android#13225]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since ~1  day, some images aren't loaded and can't be downloaded. I noticed it from 2 contacts of me (1 direct chat, from one contact in a group chat). If I press the loading icon, the animation for loading the image is shown for 1-2 seconds but nothing happens. I checked the desktop-app (Fedora, 6.33) where I can see and download the images without any problem.  So far the problem only occurs from the 2 contacts of me. Otherwise it works as expected.

Note: I'm running of GrapheneOS (Android 14). They made some updates in the last days. However, I could not see any reports regarding this problem and assume, that it could be somewhere on Signal side (because for most of the contacts, it works fine).

### Steps to reproduce
- I'm sorry but I can't tell you how to reproduce it. Receive pictures and hope that the error occurs ;-)

**Actual result:** I see that images are sent but can't see or download them.
**Expected result:** I expect that it works (to be able to see and download the images for all of the contacts"

### Screenshots

![signal-2023-10-14-213905](https://github.com/signalapp/Signal-Android/assets/60067527/e36f589e-23f6-4f65-a658-ad13a58de956)
![signal-2023-10-14-214700](https://github.com/signalapp/Signal-Android/assets/60067527/b905cb44-b4c6-4288-9f70-5be3c3361ca2)

### Device info

**Device:** Google Pixel 6 Pro
**Android version:** 14 (GrapheneOS, installed Play Store/ Play services, Signal App installed via Play store)
**Signal version:** 6.29.2

### Link to debug log

https://debuglogs.org/android/6.29.2/282255ef9da470ebd06783605c7249191488d1a7282e01a6cb183259218874e3

Please let me know if I can provide further information!

**Comment by tintin10q** [comment]
I have the same issue on my galaxy flip 3 with android 13

**Comment by alex-signal** [comment]
This was a sending side bug and should be resolved in the latest available production version of Signal.

**Comment by Brigithubert** [comment]
I am the sending side. How can I check whether the bug is resolved?

**Comment by jlsnt** [comment]
Hello,

As a **recipient**, I noticed this behaviour appeared a few days ago. In my case, it happens exclusively when **many images are attached** to a message. It's fine if the message contains a single image.

Thanks.

**Comment by Brigithubert** [comment]
Doesn't work with single images either. I tried to be smart and work around using a story with only the one contact reporting this issue: Worked once and the stopped working. :(

Has anyone tried to clear the cache? Will this remove all messages -- and help?

**Comment by cody-signal** [comment]
@Brigithubert if you are running the latest version the bug should be fixed. If you are still encountering a sending issue, please provide a debuglog so we can look into what might be happening.

**Comment by cody-signal** [comment]
🙏🏼
