### ISSUE TITLE
Recorded voice messages are only static on Pixel 7 after Android 14 upgrade

### ISSUE THREAD

**Issue by smoke007** [signalapp/Signal-Android#13231]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Recorded voice messages are only static on Pixel 7 after Android 14 upgrade. I've rebooted my phone and even backed up my data, then uninstalled and reinstalled Signal to confirm the issue still exists.  I'm on the newest Android and Signal app version.

I can use Signal to make a voice call and the mic works fine there.  Also, I can play other people’s messages to me just fine.

- Update - I tried to use Google Assistant and it couldn't hear me.  I took my phone out of the case, checked it over, and put it back in.  The mic started working again and now works in Signal too.  Very odd since I tested the mic in phone calls, Signal calls, and video recording with audio, but those could have been using a different mic on the phone.  Maybe something came loose in my phone or is faulty; so perhaps this issue was only with my phone.  If this issue doesn't come back or no one else with a Pixel 7 on Android 14 can duplicate the issue, I'll close this.  Thanks

### Steps to reproduce
- Record a voice message to someone or using "Note to self" and play it back.  I only hear a level volume of static.
- Using Google Buds Pro yields the same results, so may not be related to specific mic or mic isn't being correctly set even for Bluetooth?

### Device info

**Device:** Google Pixel 7 128GB
**Android version:** Android 14, Oct 5 2023, build UP1A.231005.007
**Signal version:** 6.36.5

### Link to debug log

https://debuglogs.org/android/6.36.5/60335313be3b3e10fce03b3cf260bb4be41420bb6ec5871febe93cd771739c5f

**Comment by smoke007** [comment]
Update - I tried to use Google Assistant and it couldn’t hear me. I took my phone out of the case, checked it over, and put it back in. The mic started working again and now works in Signal too. Very odd since I tested the mic in phone calls, Signal calls, and video recording with audio, but those could have been using a different mic on the phone. Maybe something came loose in my phone or is faulty; so perhaps this issue was only with my phone. The issue has not returned since; closing ticket.  Thanks

**Comment by Maxiiiik** [comment]
I have the same bug and it was caused by the update (I'm sure of this because before the last update I decided to try the beta of the future version and then gave feedback about it and returned to the stable version at that time, October somewhere, but after the update in December, this squeak while recording voice messages or voice recorder returned)
