### ISSUE TITLE
Signal crashes when connected to internet

### ISSUE THREAD

**Issue by PatrickDaG** [signalapp/Signal-Android#13230]
I have tried using signal on linux with wayland today. After that immediately crashed it seems to have corrupted something as now my android app crashes immediately after opening when connected to network.

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Signal crashes immediately on startup when connecting the internet

### Steps to reproduce

- Open the App
- wait a second 
- App crashes to Main screen

**Actual result:** 
Crashes
**Expected result:**
Signal working normally 

### Device info
**Device:** Samsung Z Flip 4
**Android version:** 13
**Signal version:** 6.36.5

### Link to debug log
[signal-log-1697576116736.zip](https://github.com/signalapp/Signal-Android/files/12961842/signal-log-1697576116736.zip)

**Comment by cody-signal** [comment]
Thanks for the report and sorry you're hitting this issue. There's a fix for this already in the code for the next beta 6.37 that will ship later today. Please update when it's available to you

**Comment by PatrickDaG** [comment]
Just got the update. It's fixed now. Thx a lot.
