### ISSUE TITLE
Scheduling messages beyond Daylight Savings Time are ambiguous.

### ISSUE THREAD

**Issue by gnrfzui** [signalapp/Signal-Android#13232]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While the time zone is set to DST, scheduling a message for beyond DST (eg in November) will result in the message being scheduled an hour early. I presume this is due to the scheduled time being saved correctly, but afterwards interpreted as the time zone active in November, without DST.

### Steps to reproduce
- make sure your device time zone is somewhere where DST is active, eg CEST
- schedule a message for 5pm and confirm
- see that the message is scheduled for 4pm

bonus:
- reschedule the message, and directly save without any changes
- see that the message is now scheduled for 3pm

**Actual result:** scheduling a message for 5pm results in the message scheduled for 4pm
**Expected result:** scheduling a message for 5pm results in the message scheduled for 5pm, even if DST has ended by that time.

### Device info

**Android version:** LineageOS based on Android 11
**Signal version:** 6.36.5 website build

**Comment by Keisial** [comment]
The "Schedule message" states your timezone: "All times in (GMT+02:00) Central European Summer Time".

I think it is behaving as expected.

You are scheduling a message at 17:00 (GMT+02:00), it just happens that later you are at a different timezone, and thus it becomes 16:00 (GMT+01:00). I expect the same to happen if you schedule a message for 17:00 in France, then travel to England. It will be sent at 16:00 in London (17:00 in France).

An alternative would be not to schedule based on a fixed timezone, but in a IANA timezone, such as scheduling it at 17:00 on Europe/Berlin. However, how should it behave in that case if I scheduled a message on 2023-10-29 at 2 am? That hour happens twice that day. Should it be sent at 00:00 UTC (02:00 CEST), 00:01 UTC (02:00 CET), both...?

**Comment by gnrfzui** [comment]
Now that you mention it, scheduling with respect to Europe/Berlin (and alike) is the behaviour I expected. Though, I see your point that this results in ambiguity for one hour per year (and impossibilities for another hour per year).

Considering the "bonus issue" described above, do you also consider that intended behaviour?
- schedule a message for 5pm (at a date beyond DST change)
- see that it is scheduled for 4pm
- hit reschedule on the message: now 4pm gets interpreted as time *before* DST change
- save the sending scheduling without making changes
- see that it is now scheduled for 3pm

If I do not change anything but directly confirm, I expect no changes to happen. This is not the case here.
