### ISSUE TITLE
Aviator hack signal

### ISSUE THREAD

**Issue by imrankha34** [signalapp/Signal-Android#13247]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by imrankha34** [comment]
Aviator signal

**Comment by major-mayer** [comment]
What are you trying to say to us with this bug report? It doesn't contain any information about your problem.
Please either update it with precise information or close it.

**Comment by 2026moraa** [comment]
****

**Comment by 2026moraa** [comment]
Hi

**Comment by 2026moraa** [comment]
Joy moraa

**Comment by cocuk52** [comment]
jıjıjıj

**Comment by Abhijeetkumarsin** [comment]
Hack website aviator

**Comment by khansar** [comment]
03407098

**Comment by Vickyvckl** [comment]
Avitor Hack
