### ISSUE TITLE
Custom wallpaper takes ~1s to load when opening conversation on first start of application

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#13240]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This started to happen a few versions ago. When opening a conversation the initial messages are displayed on a white background. After approximately 1s the correct background wallpaper becomes visible. This only seems to happen if the application was not used for a while or when I remove it from the list of recently used apps. After the initial delay everything works fine until closing the app and remove it from the list of recently used apps. In the attached logfile this was noticed 11-03 at 15:24.

### Steps to reproduce
- Remove Signal from recently used list
- Open Signal
- Open a conversation

**Actual result:** Delay in loading wallpaper
**Expected result:** wallpaper is displayed directly when opening chat

### Device info

**Device:** Samsung S9
**Android version:** 10 (/e)
**Signal version:** 6.39.1 (but also on a few previous versions)

### Link to debug log

https://debuglogs.org/android/6.39.1/1e0fe70f5be6af77b64554caf8fe8df819e5dc55297176337768aca64093e189

**Comment by Keisial** [comment]
How big is the wallpaper image you are using?

**Comment by bme13** [comment]
Hmm, quite large actually. ~0.97 MB. Reduced it's size to ~90 KB by sending it in Note to Self. That seems to improve things but it still happens occasionally. See e.g. https://debuglogs.org/android/6.40.4/9ffd70ab0d9083f05ece0aeb4e7006a56ec39a44be9cd7325f865174450637f1 at 20:51 (11-12). Also please note that this behaviour started to happen after a Signal update while I didn't change the background.
