### ISSUE TITLE
App crashes during the call quite often

### ISSUE THREAD

**Issue by DominikM60** [signalapp/Signal-Android#13242]
Hello Everyone!

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal started to crash quite often during the call. The issue affects me and two of my relatives. Just a moment ago it happened 3 times in a row within 1 minute. Sometimes crashes happen more often, sometimes less, I don't see any pattern. Before the update to Android 13 everything was working fine. I am adding the device info of my phone but theother two affected are Samsung and Motorola.

### Steps to reproduce
- open Signal
- call someone
- wait a minute, 5 or 30 minutes, who knows when it happens

**Actual result:** Suddenly whole app closes
**Expected result:** Call keeps going as expected

### Device info

**Device:** Realme 8 Pro 8/128
**Android version:** 13
**Signal version:** 6.37.2

### Link to debug log
[]()
https://debuglogs.org/android/6.37.2/a8fe9af7fc910093d349cd781602441f8b79f3880715614d802a15d4fc073477

**Comment by greyson-signal** [comment]
I'm unfortunately not seeing any crashes in the log :(

**Comment by DominikM60** [comment]
Fair enough, let's keep the issue open, gonna try again next time it happens and once it does I will be quicker

**Comment by DominikM60** [comment]
Happened again, this time it was copied immediately
https://debuglogs.org/android/6.39.1/b09d0dc702cb6c842981b0c318ac2d97d4237fbde156480ccf681003ba7308d1

**Comment by greyson-signal** [comment]
I totally believe that it's crashing, but unfortunately there's nothing in the logs :( This happens sometimes on some devices, idk why. It sometimes means a native crash. I _do_ see an out of memory error on 11/10 (logcat sometimes caches old crashes), but I'm guessing that's not what you just hit. Thank_ you so much for the report, but at the moment I'm not sure what the issue is :(

**Comment by DominikM60** [comment]
I can try to provide logs from Samsung as well but I have no idea if its worth anything
