### ISSUE TITLE
Android 14 - Touching the notification has a 2 second delay 

### ISSUE THREAD

**Issue by Wowol** [signalapp/Signal-Android#13254]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Android <13: immediately after touching the message notification, signal was opening showing the conversation.
After upgrading to Android 14: After touching the message notification, there is ~2 seconds delay before the conversation is opened.

It seems I'm not the only one: https://www.reddit.com/r/signal/comments/170rxvo/comment/k4mcm6i/?utm_source=share&utm_medium=web2x&context=3

### Steps to reproduce
- Be on homescreen (can be unlocked)
- Get a message
- Click on the notification

**Actual result:** There is ~2 seconds delay before the conversation is opened.
**Expected result:** Conversation loads immediately.

### Device info

**Device:** Google Pixel 6
**Android version:** 14
**Signal version:** 6.39.3

### Link to debug log
https://debuglogs.org/android/6.39.3/f6ab3fea8a505761088ecabc992a33ef248f7836184f4c82a4b844146a285686
(taken immediately after the issue arised)

**Comment by SamLeatherdale** [comment]
I'm on a Galaxy S23 running One UI 6 (Android 14) and the app doesn't open at all after touching a notification, not even after a 2 second delay. App version 6.39.3

**Comment by ElegyD** [comment]
Could be an Android/Framework issue, because the same problem occurs in other apps (I've seen it myself in Google Opinion Rewards for example):
https://issuetracker.google.com/issues/293122865

**Comment by SamLeatherdale** [comment]
Ok, I have an update, for me it's only happening for contacts I have enabled Bubbles for. As soon as I turned off Bubbles, clicking the notification started working again. Maybe I should raise a separate issue for Bubbles? 🤔

**Comment by Wowol** [comment]
@SamLeatherdale I have all Bubbles disabled, but it still doesn't work for me properly, so I am not sure if they are the issue here.

**Comment by micaelvaleri** [comment]
In my case clicking the notification open Signal on the message itself, only thing is the notification pane stays in the foreground and I have to close it manually otherwise I can't see the message behind.
I confirm it happens on Android 14, not 13. I am on CalyxOS 5.2.0

**Comment by ElegyD** [comment]
Apparently it has been fixed by some with the December Android patch, can anyone confirm this?

But I've got a Pixel 5 which last update was November and does not get updates anymore.
I created a new issue on Google's Issue Tracker because all others were closed. Starring it if you are still affected could eventually help:
https://issuetracker.google.com/issues/319053151
