### ISSUE TITLE
Make it possible to restart the account setup

### ISSUE THREAD

**Issue by davidhedlund** [signalapp/Signal-Android#13257]
# Initial prompt

When Signal is started for the first time:

![image](https://github.com/signalapp/Signal-Android/assets/6416073/7731de7d-d015-48c8-a2a9-2e2d08146734)

Regardless what you choose, after you have finished the account setup, there's no way to restart the process later.

![image](https://github.com/signalapp/Signal-Android/assets/6416073/05177bde-fed1-4e78-92c6-4ff2d54ab113)

# Request
Make it possible to restart the account setup later:

![image](https://github.com/signalapp/Signal-Android/assets/6416073/7731de7d-d015-48c8-a2a9-2e2d08146734)

* If you created a new account by pressing "Continue" in the first screenshot by mistake, you cannot restore backups to it later.
* If you restored a chat backup file, you cannot restore other chat backup files later (for example if you realized that you restored an old backup file later, and you want to restore a newer backup file).
* If you created an account, you cannot register a new account later.

There is no signal directory (for example in Android/data/) that can be deleted to restart the process either. To my knowledge, the only option you have is to reinstall Android (reset the phone, or install a third party Android OS). Or have I missed something?

**Comment by greyson-signal** [comment]
Hi there, we only use Github for bug reports, not feature requests.

That being said, the app doesn't support restoring from backups after you've registered for various reasons, and we don't plan to. If you don't want to install, you can always click the "Clear Data" button in your system settings for Signal. Different OEMs name it different things, but there will be something like that. It basically resets the app state.

**Comment by davidhedlund** [comment]
> If you don't want to install, you can always click the "Clear Data" button in your system settings for Signal. Different OEMs name it different things, but there will be something like that. It basically resets the app state.

Excellent, can you not just mention "Clear Data" here?:
![image](https://github.com/signalapp/Signal-Android/assets/6416073/59ad1e38-994d-48b2-8bb4-94fba0d9eaff)
