### ISSUE TITLE
Send Failed for Long Video Files Below Attachment Size Limit

### ISSUE THREAD

**Issue by lhhel9l3** [signalapp/Signal-Android#13258]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Android will always try to re-encode video files. In the case of long duration videos, it could be under the 100MB limit, but when you try to send it, Signal will still attempt to transcode the video. If the video cannot be transcoded due to its length (debug log suggests memory limit error), Signal will fail to send the video.

If that same video file is sent from Signal Desktop, it will work, since it is under the 100MB limit.

### Steps to reproduce
- Try to send video file under 100MB limit

**Actual result:** Signal shows "send failed" without any explanation why.
**Expected result:** Signal will send the video file since it's under the attachment size limit

### Device info

**Device:** Pixel 6a
**Android version:** 14
**Signal version:** 6.40.0

### Link to debug log
https://debuglogs.org/android/6.40.4/213f1d45b07639624d806f11fd52c4087f6af5cbe4935674e51ea7a54d8118d7

**Comment by adamk1211** [comment]
According to [alan-signal,](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-45-release/8707/5) 

> The rules are it recodes every video to 720p at 2Mbps + 192Kbps audio unless the video is already at a low enough total bitrate and contains no location information.
> 
> The output file is a maximum of 50MB (30MB if sending device is a low memory class device). At the bit rate of 2.192 Mbps, this is roughly enough for a 3 minute video.
> 
> When a video has a longer duration, the bitrate will start to be reduced to fit in the 50MB (or 30MB), down to a minimum of 480p 500 Kbps + 192 Kbps audio. However, in practice this will be unlikely on android as you will likely not have an original 3 min video that is under 200MB.

In my mind, the video size and/or length is almost irrelevant. The app should continue to reduce the bitrate to fit in the max file size.

**Comment by adamk1211** [comment]
Sorry. I was emphasizing what should happen. This has been a bug in signal for a while. Since 2020, if the app complains about a video, I send it to myself in WhatsApp. This recodes the video and allows Signal to send it 100% of the time.

**Comment by cody-signal** [comment]
We are actively working on improved video and attachment send support.

**Comment by cody-signal** [comment]
Have you been able to try on 7.1.3+?

**Comment by TJMac93** [comment]
Hi @cody-signal, this is the first result when googling "Signal can't send video". Is there any update on this issue? I can't send any videos at all, they don't even appear in my gallery as a option to send when I select to add media.

**Comment by greyson-signal** [comment]
@TJMac93 please include a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports), thanks!

**Comment by TJMac93** [comment]
@greyson-signal solved, I think? Thanks for getting me on the right path 😅  Sharing for other users with the same issue

In the debuglog I found a line `android.permission.READ_MEDIA_VIDEO: NO` which I'm guessing was the root cause. I couldn't see any denied permissions in my OS settings however. Removing all camera and media permissions and re-enabling them fixed the issue. New debuglog and that line is now set to YES, and a pending video sent successfully.
