### ISSUE TITLE
Signal leaks message content

### ISSUE THREAD

**Issue by d4f5409d** [signalapp/Signal-Android#13264]
Signal leaks the content of the messages (it displays on the screen) even if it is set to do not display message content only names.

Signal version: 6.40.4
Device: OnePlus 8, Android 13
Please be aware there are many many issues / bugs with Signal recently on OnePlus 8 stock OxygenOS. 

https://community.signalusers.org/t/signal-still-shows-message-content-in-notifications-when-set-not-to/57089

After a little bit of time, I can ensure this happens with images afaik and not with text messages. Text messages do work correctly.

**Comment by yan32323** [comment]
Have the same problem:

Had this problem before and after updating to android 14 with latest signal play store version still ongoing. When messages are first recieved they are locked it's only after unlocking and relocking them that the problem occurs.

Bug description :

The app doesn't lock pictures on the notification once shown

Conditions :

Screen lock has to be enabled

Recieve a picture that shows in notifications

Steps to reproduce :

- recieve a picture on a notification enabled chat
- unlock signal without opening chat
- relock signal either manually or with screen lock inactivity timeout

Actual result : notification prompt locks text but shows pictures
Expected result : notification prompt locks everything including pictures

Screenshots :

![Screenshot_20231201-173919.png](https://github.com/signalapp/Signal-Android/assets/82976692/d4afe696-64ee-4d0c-a756-a11a2ab57c91)

![Screenshot_20231204-185906.png](https://github.com/signalapp/Signal-Android/assets/82976692/183405b6-84a6-42e9-aa11-b50d1a1572e1)



Device info :

Device : pixel 6 pro
Android : 13 and 14
Signal : 6.40.5

Debug log :

https://debuglogs.org/android/6.40.5/42de3a6821eaa4798b645698167055a88e397d89ba7b9adcb8c895a00e112c35

**Comment by cody-signal** [comment]
The thumbnail issue has been resolved in 6.41.3 that is pending Play Store approval.

**Comment by yan32323** [comment]
> The thumbnail issue has been resolved in 6.41.3 that is pending Play Store approval.

Thank you so much for the info ! (Close the issue then ? Sorry not really familiar with how issue management works)
