### ISSUE TITLE
Unexpected package name displayed after updating Signal (Website Distribution Build) via APK

### ISSUE THREAD

**Issue by antarctic3431** [signalapp/Signal-Android#13263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have the Signal Website Distribution Build installed (no Google services) on my device, originally obtained from https://signal.org/android/apk/. Recently, when an update rolls out and I am prompted to install, an unexpected package name appears at the `App Installed` stage. This is occurring with the APK obtained directly from the Signal website, and per my screenshots below, occurred when updating from 6.39.1 to 6.40.4.

The unexpected package name is: `org.thoughtcrime.securesms.ApplicationContext`

### Steps to reproduce
- Download the latest Signal Website Distribution Build APK from Signal at https://signal.org/android/apk/.
- Save the APK to the Downloads folder.
- Launch the APK.
- Prompted with: `Do you want to update this app?` The Signal app icon and "Signal" app name are displayed. (Screenshot 1)
- Update process runs. (Screenshot 2)
- Update completes, prompted with `App Installed`. The Signal app icon has been replaced with a generic Android icon, and the package name `org.thoughtcrime.securesms.ApplicationContext` appears instead of "Signal". (Screenshot 3)
- In the list of installed apps (Settings > Apps), the Signal app name appears as otherwise expected (including correct icon), and is installed as `org.thoughtcrime.securesms`. Version number also increased to latest version.

**Actual result:** Downloading the APK directly from the Signal website and updating shows unexpected package name of `org.thoughtcrime.securesms.ApplicationContext` at the App Installed stage.
**Expected result:** On conclusion of previous app updates, the Signal app icon and "Signal" app name were displayed with App Updated on conclusion of update.

### Screenshots
Screenshot 1
![Screenshot 1](https://github.com/signalapp/Signal-Android/assets/124637546/a3966531-6f86-42f2-a7c1-9bea9d095255)

Screenshot 2
![Screenshot 2](https://github.com/signalapp/Signal-Android/assets/124637546/e8dfcd8b-a317-43fe-9d59-6aef8d75ceab)

Screenshot 3
![Screenshot 3](https://github.com/signalapp/Signal-Android/assets/124637546/977cb533-8c1c-40b1-8ccd-408513b3c073)

### Device info
**Device:** Google Pixel 7
**Android version:** 14 (GrapheneOS)
**Signal version:** 6.39.1 updating to 6.40.4

**Comment by clark-signal** [comment]
Hi thanks for the report, AFAIK this is a system dialog, so would be an issue on the OS's end.
