### ISSUE TITLE
Image gallery picker doesn't allow selection of .JPEG extensions 

### ISSUE THREAD

**Issue by eeik** [signalapp/Signal-Android#13265]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When saving images on Android, for some reason Chrome is saving some JPEG images with .jpeg extension rather than .jpg. Signal's attach image feature gallery picker isn't showing these images for me.

### Steps to reproduce
- save JPEG image onto device as .jpeg extension
- within Signal conversation thread, attach image
- find the folder where JPEG image is located

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
observe that image is not rendered in preview and thereby not available to attach 

Workaround is to alter .jpeg to .jpg within file system editing app. Once image has.jpg extension, signal attach works as expected 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
regardless of image file extension, a simple image (i.e. JPEG, JPG, PNG, GIF) should all be viable to select and send 

### Device info
**Device:** Moto 5G 2023
**Android version:** 13 (T1TPNS33.58-42-2)
**Signal version:** 6.40.4

**Comment by greyson-signal** [comment]
Unfortunately I don't think this is within our control. We're simply asking the system to give us all of the images it has. We're not filtering by extension. Any filtering would be done by your OS.
