### ISSUE TITLE
F-Droid request

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#13268]
Hi!

Can you please publish your app on F-Droid officially? Or at least make your own F-Droid repo [like Tor did (link)](https://guardianproject.info/fdroid/repo/)?

F-Droid allows custom keys [(more info)](https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html)

**Comment by dave0003** [comment]
Just a note;  as long as Signal includes auto-update code, as the version on the Signal website does, it wouldn't be acceptable to F-Droid.  Wireguard was removed from F-Droid recently for that reason.

**Comment by Ychchcgf** [comment]
@dave0003 
> wouldn't be acceptable to F-Droid

They can [self host F-Droid repo (link)](https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/)

**Comment by greyson-signal** [comment]
Hi there, we don't have any immediate plans to host an f-droid repo. Thanks!
