### ISSUE TITLE
Cannot transfer/register: Expected HTTP 101 response but was '404 Not Found'

### ISSUE THREAD

**Issue by zaventh** [signalapp/Signal-Android#13275]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Entering the account PIN during a device transfer results in a general toast message "Error connecting to service". As a result, the registration process cannot be completed.

### Steps to reproduce

- Have an account PIN
- Initiate a transfer from one device to a new device
- Proceed until asked for a the account PIN
- Enter any PIN, including incorrect ones

**Actual result:** An error is received. Debug logs indicate a 404 network error.
**Expected result:** Registration should complete successfully upon entering a correct PIN.

### Screenshots

![Screenshot_20231121-152800](https://github.com/signalapp/Signal-Android/assets/669283/312cfa00-3292-4f23-b47a-ec2970f2fd8e)

### Device info

**Device:** Pixel 8
**Android version:** 14
**Signal version:** 6.41.2

### Link to debug log

[signal_transfer_bug.txt](https://github.com/signalapp/Signal-Android/files/13431990/signal_transfer_bug.txt)
[signal_transfer_bug2.txt](https://github.com/signalapp/Signal-Android/files/13432031/signal_transfer_bug2.txt)

**Comment by nicholas-signal** [comment]
Thakn you for your reports! Please try this again, as there was an intermittent SVR2 issue at that time that have since been resolved. If it works for you, please close this GitHub issue.

**Comment by zaventh** [comment]
It appears to be working now. Thanks.
