### ISSUE TITLE
Cannot change PIN: PIN creation failed

### ISSUE THREAD

**Issue by zaventh** [signalapp/Signal-Android#13277]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When attempting to change my PIN, I received a message "PIN creation failed". Debug logs reveal network level errors.

Note this is very similar to #13275 which happens during a registration/transfer.

### Steps to reproduce

- Open Account settings
- Select Change your PIN
- Select any PIN

**Actual result:** An error is displayed
**Expected result:** The PIN should be changed

### Screenshots

![Screenshot_20231121-160309](https://github.com/signalapp/Signal-Android/assets/669283/6f9f6537-6dd2-4fd6-aa16-4460552993ff)

### Device info

**Device:** Pixel 7
**Android version:** 14
**Signal version:** 6.41.2

### Link to debug log

https://debuglogs.org/android/6.41.2/0d7d8c61e873ba9acc2f7889fe1d668a60c72c4d27ca675c9197b72d69a7de6d

**Comment by nicholas-signal** [comment]
Thank you for your reports! Please try this again, as there was an intermittent SVR2 issue at that time that have since been resolved. If it works for you, please close this GitHub issue.

**Comment by zaventh** [comment]
This appears to be resolved now. Thanks.
