### ISSUE TITLE
Upload progress circle shows incorrect amount of progress

### ISSUE THREAD

**Issue by zestyping** [signalapp/Signal-Android#13272]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The graphical circular progress indicator for a video file upload shows the incorrect fraction of progress.

### Steps to reproduce
- Upload a video file of at least 10 MB.
- Observe the circular progress indicator.

**Actual result:** The upload is less than 10% done, but the circle is 3/4 filled.

**Expected result:** When the upload is 10% done, the circle should be 10% filled.  When the upload is half done, the circle should be half filled.

### Screenshots
<img width="394" alt="image" src="https://github.com/signalapp/Signal-Android/assets/236086/088f9681-0cfd-49c3-bec2-4875b779d3ef">

### Device info
**Device:** LG Q6
**Android version:** 8.1.0
**Signal version:** 6.36.5

### Link to debug log
https://debuglogs.org/android/6.36.5/7394344ba77d4f838784266915e85bb32816902dfcfb64d129805488d2a251f9

**Comment by nicholas-signal** [comment]
This is working as intended. The first 75% of the progress indicator is for video transcoding, the last 25% is the network upload. So what you're seeing is that it's 10% uploaded, which results in (10% * 25%) + 75% = 77.5% filled.
