### ISSUE TITLE
Black text in audio output switcher menu even in dark mode

### ISSUE THREAD

**Issue by adarsh1001** [signalapp/Signal-Android#13278]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The audio output switcher menu during calls has black text even in dark mode.

### Steps to reproduce
- Set the app theme to Dark.
- Initiate a signal call.
- Open the audio output switcher menu.

**Actual result:** The text in the menu will be in black color.
**Expected result:** Text should be white since the background is dark.

### Screenshots
![Screenshot_20231121-235820_1.png](https://github.com/signalapp/Signal-Android/assets/8820038/376b9fc9-cd4b-43c3-b1ed-66cdb81ca039)

### Device info

**Device:** Nothing Phone (2)
**Android version:** 13
**Signal version:** 6.40.5

### Link to debug log

N/A

**Comment by nicholas-signal** [comment]
This should be fixed in the 6.41 release, currently in beta: https://github.com/signalapp/Signal-Android/commit/2d835581a50797fe6f958b8ba0c685ac856f5ba2
