### ISSUE TITLE
Ditch google evil corp maps, use OSM

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#13289]
Hi!

When sending a location I noticed that Google Maps was used for selecting locations.

Isn’t it true that Google tracks behaviour like searching/selecting locations?

Let’s suppose you want to secretly meet up with someone, Signal will provide the privacy for that. However, if you select it though Google Maps, Google knows you selected that location. Plus, if the other person clicks that same link, Google might figure out that you will be meeting with that person at that location.

Besides, Signal using a service of the most privacy-invasive companies out there doesn’t sound like a good match.

I suggest using OSM for selecting locations.

Google is not private. Google is not secure. Google is about surveillance.

Using google map integration is gross, because you will share your location in **UNENCRYPTED** form with the mod evil corporation in the world.

For example [Molly (link to open source)](https://github.com/mollyim/mollyim-android) switched to Open Street Maps. And everything workes perfectly fine.

**Comment by gbucar** [comment]
Google maps is not available on phones that do not have play services so this wold be improved too.

**Comment by Goldmaster** [comment]
Maybe there should be an option that would allow users to select osm or Google maps. If play services are not installed then only osm would be used.

**Comment by Yvihihuguv** [comment]
Any updates?

**Comment by greyson-signal** [comment]
We don't have any immediate plans here

**Comment by nach0** [comment]
Please give the users who don't have Google Play Services and no Google Maps an alternative.

Currently Signal freezes when I try to share my location, that is clearly a bug.

Let us choose between using Google Maps or OSM to share our location. Sharing location works fine in WhatsApp without Google Play Services
