### ISSUE TITLE
Do not process media while sending it as file 

### ISSUE THREAD

**Issue by kik-btaski** [signalapp/Signal-Android#13295]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While sending video/photo as file, it processes it and then sends it. Because of that, file hash is not the same. The app should assume that user wants no processing while sending it as file 

### Steps to reproduce 
- open any chat and tap `+` icon
- select file and choose one video/photo 
- send it and save it to check its hash

**Actual result:** File hash is not the same
**Expected result:** File hash should be same

### Device info
**Android version:** 11
**Signal version:** 6.40.5

**Comment by greyson-signal** [comment]
Hi, this is currently working as intended, although we may make this a feature in the future.
