### ISSUE TITLE
Allow “delete for everyone” in Note To Self, with no time limit or tombstone

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#13291]
One of the uses for Note To Self is securely sending data from one device to another (phone to desktop, or vice versa, desktop to desktop, etc). However, once you have used the data on the other end, it is often times no longer needed and can be deleted from the conversation for tidiness and security. Unfortunately, there is only the option to “delete for me”, which will only delete the message from the one device that you are using. If you have a large number of linked devices, you now have to log in to every single one and delete the message there.

This can partially be mitigated by using disappearing messages, but you have to be sure to set a long timer since the countdown starts immediately on all devices, and you may want to delete the message sooner than whatever timer you set. You also may not want the message to expire at a specific time, but instead stay around indefinitely until you specifically delete it manually.

Note To Self should allow “delete for everyone”, maybe with a slight rewording – “delete from all devices”. Since Note To Self is only for yourself, there is also no reason to impose the 3 hour time limit, and instead it should allow messages to be deleted at any time. It also seems reasonable that the deletion tombstone would not be necessary here as well.

As a side note, “delete for me” in Note To Self should be changed to “delete from this device”, as “delete for me” in Note To Self implies the behavior I am requesting here already exists (which it does not).

**Comment by Yvihihuguv** [comment]
Any updates?

**Comment by greyson-signal** [comment]
We did this a while back
