### ISSUE TITLE
No telephony and video call

### ISSUE THREAD

**Issue by paulsommer** [signalapp/Signal-Android#13294]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Telephony and video calls stopped working on my phone. Still working on connected PCs

### Steps to reproduce
- Install Signal on your phone
- Try to call someone on Signal (works)
- Reboot the phone
- Try again to call someone on Signal, and it doesn't work.

**Actual result:** The target of the call gets a silent notification  "Verbindung wird hergestellt" ("Connection being established") but no ring. The caller (me) hears the normal ringing sound.
The same result if someone tries to call me.
After the connection try the called person gets a "missed call" message.

It only works after a fresh install until I reboot the phone.

**Expected result:** Telephony should work as it did for years (even on my phones with Lineage-OS) 

### Device info
**Device:** OnePlus 8
**Android version:** 13 (LineageOS 20-20231121-Nightly-instantnoodle)
**Signal version:** 6.40.5

### Link to debug log

https://debuglogs.org/android/6.40.5/626ba1135468f0d8bb126a58d31833c45c2f898f41545ece348c19869f5dcaae

**Comment by Ansalpandey** [comment]
I tested out this issue, but I am not getting this error.

**Comment by paulsommer** [comment]
Signal also worked for me for years; but not anymore.
I haven't made any changes to the device other than the regular updates.

**Comment by russell** [comment]
I have the same issue.  I was able to reproduce the behavior.  It works after first install and then it doesn't after rebooting.  It's been happening to me for about a month I would say.  It started happening after I upgraded to Android 13, which was around the same time.

When I call a signal phone, that phone shows a connecting notification, but never shows me calling. If I try to call from the phone that is receiving the call, a dialog is shown that allows a user to accept the call, but doing this results in nothing.  The common experience is that the user is unaware I'm calling and they just receive a missed call notification.

Interestingly all other messages work, I can message, see typing notifications, everything other than calling or receiving call's works.

My device has MicroG,  so I assumed that was the problem, and I tried installing with MicroG disabled to allow Signal to use the direct connection.  But this didn't work either.

@paulsommer are you using the official google play services?

### Device Info
**Device:** Fairphone 5
**Android Version:** 13 (e/OS 1.17-t-20231109350751-stable-FP5)
**Signal Version:** 6.41.3

### Link to debug log
https://debuglogs.org/android/6.41.3/995878419d964020fa76dd017dadc077c53a46db8aed43966c81f3ebab70ee0b

**Comment by paulsommer** [comment]
My phone (Oneplus8 with LineageOS) runs Android 13 too. I don't know how long this error exists, because i rarely use telephony with signal.

**Comment by russell** [comment]
@paulsommer I was looking through your logs and found that you have a VPN connected.  I also use a VPN, the VPN I'm using is Tailscale.

When I disable my VPN, then calling works again. Can you confirm if you are using a VPN and if disabling it fixes calling?

**Comment by paulsommer** [comment]
@russel It's exactly that. Thanks a lot for the hint. I'm using personalDNSfilter for blocking ads.
In the link you added.

In the last message of the thread you posted, the guy suspects the MTU size is too small. 

I'm not qualified to judge that. Anyone else?

**Comment by mrkspflr** [comment]
https://github.com/tailscale/tailscale/issues/8888#issuecomment-1859235907

**Comment by russell** [comment]
I just tried turning of magic DNS, it has no effect, I don't even have exit nodes configured, I only route to some services on the tailnet, so the signal traffic should be going direct.

**Comment by mrkspflr** [comment]
do you use any tailscale acl configurations? can confirm that if tailscale vpn is just connected ('use exit node'=off) it works for me, in my case it's not dns related.

**Comment by russell** [comment]
I have no ACL configured and I have no exit nodes configured.
