### ISSUE TITLE
User (Reciver) can take a screenshot of view once image

### ISSUE THREAD

**Issue by surendar75** [signalapp/Signal-Android#13300]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I received a view once image but i took a screen shot after opening. unexpectedly the app is allowing to take a screen shot of a view once image. This bug completely made ruin of view once feature in the signal.

### Device info
**Device:**  Google Pixel 7
**Android version:** 14
**Signal version:** 6.40.5

**Comment by surendar75** [comment]
> You could disable screenshots within settings -> privacy. But keep in mind it affects the whole app.

Yeah, i know that but, it is not intended. If  the  receiver can take  screen shot then what is the use of view once feature. This is not possible in whatsapp(as i asked whatsapp user).

**Comment by UserX404** [comment]
The 'view once feature' is handled as a kind of memory-saving feature and has never ment to be a security feature.
Due to it's working as designed feel free to attend the [forum discussion](https://community.signalusers.org/t/screenshot-of-view-once-photo/44344).

**Comment by surendar75** [comment]
> The 'view once feature' is handled as a kind of memory-saving feature and has never ment to be a security feature. Due to it's working as designed please close the ticket and feel free to attend the [forum discussion](https://community.signalusers.org/t/screenshot-of-view-once-photo/44344).
 Ok, So it is not a bug. Closing the issue.
