### ISSUE TITLE
Echo during call

### ISSUE THREAD

**Issue by DidierLmn** [signalapp/Signal-Android#13304]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When making an audio call via Signal, I can hear an echo of my own voice coming back to me.
The call is NOT made while on speaker phone. Neither side has speaker phone activated.
The person on the other end says they don't have any audio issues, no echo or anything.
When performing a normal phone call (not via Signal) between the same devices, there is no problem. It seems limited to Signal calls.

### Steps to reproduce
- Start Signal audio call

**Actual result:** Hear an echo of myself coming from the other end
**Expected result:** No echo

### Device info 
(device where I hear the echo)

**Device:** Samsung Galaxy A53 
**Android version:** 14 (also present while on 13)
**Signal version:** 6.41.2

### Device info 2
(Other device that seems to send back the echo, but doesn't have/hear any audio issues itself)

**Device:** Xiaomi Mi8
**Android version:** 13 (LineageOS)
**Signal version:** 6.41.2

### Link to debug log
https://debuglogs.org/android/6.41.2/76098f9c1038823bd75288422ea9c8ec86bbe9a27782bcef9d0a800bd22e0feb
(Offending call was started around 2023-12-05 20:20 GMT)

**Comment by cody-signal** [comment]
Do you hear an echo if you call people that don't have a Xiaomi Mi8?

**Comment by klefan** [comment]
I have the same issue. People I call experience an echo of themselves. I don't hear an echo of myself.
Whatsapp works without echo in both sides.
Persons I`m calling use Samsung Galaxy J7, Samsung A3.

My phone:
Device: LG V20
Android version: 13 (LineageOS 20)
Signal version: 6.41.3

There are some old topics:
https://github.com/signalapp/Signal-Android/issues/6241#issuecomment-315890310
https://gitlab.com/LineageOS/issues/android/-/issues/6513

**Comment by DidierLmn** [comment]
I got some logs from the Xiaomi device right after a phone call 
https://debuglogs.org/android/6.41.3/bb55d58b7f66aa74b78711058a2db149f856754570368a487241765fa5898061

I can't say if the issue also exists with other devic as I don't have any other contacts to call.
