### ISSUE TITLE
Permissions for SMS are still present on the Signal Android app, though SMS has been deprecated in the app.

### ISSUE THREAD

**Issue by rollsicecream** [signalapp/Signal-Android#13315]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
In the Signal Android app, the old permissions for sending/receiving/modify SMS messages are **still** present in the app, but SMS **has been deprecated** on Signal some time ago.

### Steps to reproduce
- Go to the Google Play Store page of Signal
- Click on 'about this app'
- Drag down to 'Permissions' and click on 'view details'
- And as you can see, the permissions for SMS are displayed.

**Actual result:** Signal gets the old SMS permissions **automatically**.
**Expected result:** After the deprecation of SMS support on the app, the permissions **should be removed.**

### Screenshots
![signal_permissions](https://github.com/signalapp/Signal-Android/assets/153316540/018218e1-f426-42d5-801a-e3a4b9d356b0)

### Device info

**Device:**  No need for it.
**Android version:** No need for it.
**Signal version:** 6.40.5

### Link to debug log
No need for it.

**Comment by rollsicecream** [comment]
Okay, should we close the issue or not?

**Comment by Goldmaster** [comment]
Will we at some point have sms import readded? Maybe enhanced with support for importing from WhatsApp and telegram.

**Comment by rollsicecream** [comment]
> WhatsApp and telegram

Well, in the case of WhatsApp and Telegram, it could be possible with things like ZIP files, that's what Telegram does AFAIK : https://www.reddit.com/r/Telegram/comments/mx8upw/i_can_export_telegram_chats_but_can_i_import/

> sms import

Do you mean SMS export? Because SMS imports are now useless with the disappearance of SMS support in Signal.

**Comment by codethief** [comment]
> Because SMS imports are now useless with the disappearance of SMS support in Signal.

No, they're not. There is a difference between being able to correspond with someone through Signal and being able to read a past conversation with them in the Signal app, e.g. to keep all your conversations with that person in the same place (that's backed up, secure, has a nice UI, et cetera). If I understand @Goldmaster correctly, their request is about the latter.

**Comment by locuturus** [comment]
> The permissions are still there to allow SMS export to work. However, we're seeing reports of that not working that we're looking into. Believe us, we want these removed as soon as soon as possible and will do so when we can/plan.

Yes, I found this while looking for reports on that. I stopped using Signal for a couple years after using it for many years. After going back to it recently I was excited to try the SMS export feature but it gets stuck on the step to set Signal as the default SMS app

**Comment by Goldmaster** [comment]
> If I understand @Goldmaster correctly, their request is about the latter.

Yes, it's about being able to import sms, whatsapp and telegram messages into signal to chat with someone who now uses signal

**Comment by cody-signal** [comment]
The permission should drop in the next release.

**Comment by cyb3rko** [comment]
It was removed, current release does not include SMS permissions anymore
