### ISSUE TITLE
APKs on GitHub, F-Droid repo

### ISSUE THREAD

**Issue by zsoltsandor** [signalapp/Signal-Android#13318]
I enjoy using Signal, but I am planning on de-Googling my life (without switching to Apple in the process). Having libre APKs on GitHub would be a good move towards this. Optionally an F-Droid repo could also be beneficial.

**Comment by bigboipete** [comment]
Do you know this APK source?

https://signal.org/android/apk/

Works like a charm on my degoogled device. As far as I recall F-Droid is not an option for some technical reasons.

**Comment by rollsicecream** [comment]
[Obtainium](https://github.com/ImranR98/Obtainium) does support installing Signal from the website, so... this is something!

**Comment by Nomarian** [comment]
It seems the guardian project offers a repository. Given they're the ones doing tor, why isn't it possible?

**Comment by greyson-signal** [comment]
We started putting APK's on github, which works great with obtainium (instructions [here](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-obtainium/65274)). Hopefully that's sufficient for the time being.
