### ISSUE TITLE
Clarify standalone APK release strategy (Cannot transfer account from standalone APK to version downloaded from Google Play due to the latter being behind)

### ISSUE THREAD

**Issue by codethief** [signalapp/Signal-Android#13317]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am trying to transfer my Signal account from my old phone (Pixel 5) to my new phone (Pixel 8). My old phone is running the standalone APK while on the new phone I wanted to use the version from Google Play.

The transfer has turned out to be impossible because my old phone is running a newer version of Signal (6.41.3) which is not yet available on the Play Store.

While understandable that the transfer itself doesn't work I would like to use this ticket to ask: Why is the version on Google Play one minor version and several patch versions behind the standalone APK? Is this just pure coincidence and I happened to run into it or is this a systematic thing?

For instance, I noticed that the [beta feedback thread for v6.41](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-41-release/57060/114) was closed only two days ago. Does this mean the standalone APK is actually the beta version? If so, I'd at least expect this to be communicated on https://signal.org/android/apk/ .

### Steps to reproduce
Follow the steps [here](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_transfer_steps) until "Confirm the 7-digit code matches on both phones and select Continue on each phone." Upon doing so, my new phone reports that my old phone is running a newer version of Signal.

### Device info
**Old phone:** Google Pixel 5
**New phone:** Google Pixel 8
**Android version on new phone:** An older version of GrapheneOS (based on Android 13)
**Android version on new phone:** Latest version of GrapheneOS (based on Android 14)
**Signal version on old phone (standalone APK):** 6.41.3
**Signal version on new phone (latest available version from Google Play Store):** 6.40.5 ("last updated on 27 November 2023", according to Google Play Store)

**Comment by UserX404** [comment]
As you mentioned its not possible to transfer is not possible to an older version. Signal pushed 6.41.3 a few days ago but it stucks into Google's approval process. For this particular case you need to wait until 6.41.3 being pushed by Google.

**Comment by cody-signal** [comment]
Our usual flow is to have Play Store update first and then have the standalone website apk get updated so they are in sync. However, many folks were experiencing self-update issues specific to the website apk that we wanted to fix sooner rather than later without having to wait for Google. We did not think it would be stuck in review this long though and thus be out of sync this long, sorry. The update should hopefully be available soon.
