### ISSUE TITLE
No Error message about root cause of a transfert error

### ISSUE THREAD

**Issue by Hierosme** [signalapp/Signal-Android#13310]
My music Band use Signal to share guitare show. 

Unfortunlly Signal look to have a file size limitation and no error message speack about it.
No parametter permit to deal with it.

Signal start the transfert and stop with a "Transfert Error"message.

Why start the transfert if the size is too big ?
Why no inform user about a size file transfert before strat the transfert ?
Why the error message do not help the user ?

Now we have identify our trouble is cause by the video size, but Signal application have totaly let use determine the trouble.
Actually our video exchange are limited to 2 minutes and 30 secondes.

**Comment by cody-signal** [comment]
Hi @Hierosme, sorry you are encountering this issue. There is messaging in the app when videos/files are too large that should be showing when you encounter the issue.

Can you provide a debuglog? 

https://support.signal.org/hc/articles/360007318591-Debug-Logs-and-Crash-Reports
