### ISSUE TITLE
Keepig the voice message button pressed is difficult 

### ISSUE THREAD

**Issue by janwo** [signalapp/Signal-Android#13322]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The voice message button gets unpressed easily although the finger is still on it. This results in many 2 second long voice messages.

### Steps to reproduce
Open a chat and keep the button pressed on an Google Pixel 7a. You will notice that the button is deactivated very easily.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Google Pixel 7a
**Android version:** 14
**Signal version:** 6.41.3

### Link to debug log

https://debuglogs.org/android/6.41.3/b8d770e61f8adb28ad5073322ba84ce5a04b2b7de4b14e8324ee062d2534e2b6

**Comment by greyson-signal** [comment]
I can't reproduce any issue. FWIW you can also drag the voice note button up to lock it so that you don't have to hold it.

**Comment by janwo** [comment]
Also the locking fails sometimes, as the button deactivates right before being in locked state. Is it a device specific thing? In other messaging apps I don't have this issue.Am 14.12.2023 21:18 schrieb Greyson Parrelli ***@***.***>:
I can't reproduce any issue. FWIW you can also drag the voice note button up to lock it so that you don't have to hold it.

**Comment by nicholas-signal** [comment]
Would you be willing to record a video of the behavior? And would you mind including the "show taps" so we can see the touch event handling as its happening?

https://www.androidpolice.com/android-13-dp2-show-touches-screen-recorder/
