### ISSUE TITLE
Wish: font-size for the input-field 

### ISSUE THREAD

**Issue by Spielmops** [signalapp/Signal-Android#13336]
As an older person with diminished eyesight I wish, the settings/fontsize would also apply to the edit-field ....

Spielmops

**Comment by greyson-signal** [comment]
Our in-app font settings only apply to message bubbles. However, your system-wide font size should apply to the compose box. Does that work for you?

**Comment by Spielmops** [comment]
Sadly no! If I choose a bigger system-font-size, the everything else is to big. So why not apply that font-setting to the compose-box? Space enought ...

Spielmops
