### ISSUE TITLE
Disable annoyances permanently

### ISSUE THREAD

**Issue by Lemm99** [signalapp/Signal-Android#13330]
It would be great if one could permanently disable the annoying donation message. I'm trying to convince more family members to use Signal but the more annoying crap you put in the app, the more difficult my job becomes. I already had a handful of friends and family members remove the app a while back because of the incredibly annoying PIN crap you forced on users. Thankfully you fixed that but the damage is done. Stop annoying users. Also remove the cryptocurrency BS please. Merry Christmas!

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by samuraiijaack** [comment]
Can we please reopen this issue? I understand that Signal is a non profit but it feels out right annoying getting asked for a donation every time I open the app. Can you think of any other creative ways to generate revenue other than asking your users every time they use the app? Maybe offer additional features like Discord Nitro? I bet you would have more donors.

**Comment by Syphist** [comment]
> Can we please reopen this issue? I understand that Signal is a non profit but it feels out right annoying getting asked for a donation every time I open the app. Can you think of any other creative ways to generate revenue other than asking your users every time they use the app? Maybe offer additional features like Discord Nitro? I bet you would have more donors.

Yes, can we please re-open this? I get signal needs funding but I cannot afford to donate the way they want me to and I would like an option to disable the ask for it that I get on a weekly basis. I wouldn't mind if it was once a year, heck even once every 3-4 months. Every week is excessive. Other projects that ask for donations like this, such as KDE, only ask once or once a year.

**Comment by gh10ltz** [comment]
these devs are morons

**Comment by wertzuz** [comment]
It's only happening on every release which os really not every day. Also don't throw insults around just because you disagree with a decision!

**Comment by greyson-signal** [comment]
Signal is a non-profit and subsists entirely on donations. We run a donation campaign once per quarter, so that's once every 3 months. If you tap "not now", we'll dismiss the request for 5 days, if you press it again we'll dismiss it for 7 days, and if you press it again we won't ask until the next quarter. That means there should be gaps of ~2.5 months where you don't see donations.

I'm sorry if people find this annoying, but this is how Signal continues to exist and offer free services for all users.
