### ISSUE TITLE
emoji search index (flags)

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#13343]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Emoji search index needs some more love and improvement.
There is no way to find out about search parameters of specific emoji's, which could be improved by showing search keys when long click on a specific emoji.
I messed arround to find a way to insert a specific flag, what was hard to determine which search phrases could be used. The search keys also differs with the desktop implementation.

### Steps to reproduce
- set local language to german
- flags could not be found like on desktop eg: `:flag-hu`, `:flag-hungary` but with `:ungarn` (german localization for hungary)
- there is no way to find the austrian flag using therms like `:österreich` , `:oesterreich` or `:austria`.

**Actual result:**
There is no way to determine search keys. It's also not possible to search for austrian flag with the correct localized term `:österreich`. This could maybe comes from the leading character [Ö](https://www.compart.com/de/unicode/U+00D6) or [ö](https://www.compart.com/de/unicode/U+00F6)
Whereas the search of `:flag` provides a suggestion of all country flags.
**Expected result:** 
1) provide a possibility to determine the possibe search terms for `:`-search
2) enable search also for none standard characters (umlauts) to get e.g. austria flag 🇦🇹

### Screenshots

![grafik](https://github.com/signalapp/Signal-Android/assets/14954521/f5972c94-ff07-4ed0-87b8-fa75f99dd417)
![grafik](https://github.com/signalapp/Signal-Android/assets/14954521/585f0bf7-4303-4609-becb-3398d23ed106)

### Device info

**Device:** Sony XZ2c (tama)
**Android version:** 11 (LOS 19)
**Signal version:** 6.41.3

### Link to debug log

https://debuglogs.org/android/6.41.3/81c8719803a20d62dca0cf2c71ba27d1b91a0fb7714b7d6072964794c2f4642d

**Comment by UserX404** [comment]
Figured out the correct flag gets shown then starting with :Ös (terreich) but dont show up when typing :österreich (lower case).
Did a cross check with germany. Despite Austrian flag the german one are shown with capital :Deu (tschland) AND with lower case :deu

Looks like the search index need some posish to be case insensitive.

**Comment by major-mayer** [comment]
@greyson-signal @cody-signal could you please re-open this issue? I am still having the same problems as reported by @UserX404
