### ISSUE TITLE
Sticker preview not closing on Back button

### ISSUE THREAD

**Issue by pippi1otta** [signalapp/Signal-Android#13351]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The sticker preview screen is not closed when Back button is pressed, and any subsequent previews are drawn on top of it. The only way to get rid of such a preview screen is to close the chat.

### Steps to reproduce
- enter a chat
- tap the keyboard/emoji/sticker icon to the left of the input field
- make sure the sticker tab is selected
- long-press on a sticker, to see its enlarged preview and associated emoji
- press the Back button of your phone

**Actual result:** The enlarged sticker disappears, but the semi-transparent screen and the emoji are still there.
**Expected result:** The whole preview disappears.

### Screenshots

https://github.com/signalapp/Signal-Android/assets/136894633/43e11d96-f961-4580-b3e8-c94af44b8f31

### Device info
**Device:** Xiaomi Redmi Note 11 Pro
**Android version:** 13
**Signal version:** 6.42.3

**Comment by pippi1otta** [comment]
The sticker previews also ignore "Screen security", in case this helps finding the main issue:

https://github.com/signalapp/Signal-Android/assets/136894633/a3b50a7a-f72e-43da-a651-78ea8b92d82c

**Comment by Ansalpandey** [comment]
@pippi1otta Can you provide more context for this issue? I have successfully reproduced it on my Emulator and Physical Device as well.

**Comment by cody-signal** [comment]
I'm unable to reproduce the issue on my test devices. As soon as I release my long press or even if I keeping pressing and then tap back the preview immediately dismisses.

**Comment by pippi1otta** [comment]
> As soon as I release my long press or [...] the preview immediately dismisses. @cody-signal 

Yes, but only if your long press has at least a little bit of swipe in it. I guess it's designed this way so one can preview several stickers with a gliding motion.

If I keep my finger steady and release exactly where I pressed, the preview goes into a "CapsLock state", and only another tap anywhere on the screen hides it.

I expected a Back button press to dismiss it too, as it is idiomatic to do so.

**Comment by cody-signal** [comment]
I don't disagree that the behavior you see is incorrect, but I can't reproduce it which makes fixing the right problem difficult.

Using a mouse and being completely still or a finger and going crazy, I'm unable to reproduce the issue, as soon as I tap elsewhere or release the press the preview goes away.

Anything else you can think of that could be contributing?

**Comment by pippi1otta** [comment]
> Anything else you can think of that could be contributing? @cody-signal 

Nothing, really. But I checked my wife's phone, a Samsung Galaxy A13, with a completely different set of apps, and I could still reproduce the issue every time.

**Comment by pippi1otta** [comment]
not fixed as of 7.1

**Comment by cody-signal** [comment]
Hi again, I just tried to reproduce this and still couldn't get the sticker picker to stay up after I release my finger from the screen. Without a repro, it's pretty tough for us to be able to fix this. :(

**Comment by pippi1otta** [comment]
Note fixed as of 7.6.2

**Comment by pippi1otta** [comment]
Fixed in 7.9.5. Thanks a lot, @El-Ahmed and @cody-signal!
