### ISSUE TITLE
Signal Crash when try to share Image video and file using android share and signal has screenlock enabled.

### ISSUE THREAD

**Issue by AmolAcharya** [signalapp/Signal-Android#13353]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When we try to share anything from gallery or from any other app like whatsapp it gets crash only when signal has screenlock enabled.

### Steps to reproduce
- Enable screenLock in signal app.
- got to the gallery select image and share it
- it redirects to the lockscreen to unlock but after unlocking it gets crash.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Samsung A73 5G
**Android version:**13
**Signal version:** using beta version but it is also present in production version.

**Comment by Max-Stirner-Signal** [comment]
Please write in from within the app so we can better understand what the issue is. You can reference the term "crash" and this GitHub issue number.

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.
