### ISSUE TITLE
NullPointerException when trying to send Signal stories

### ISSUE THREAD

**Issue by rugk** [signalapp/Signal-Android#13364]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when sending a Signal story.

### Steps to reproduce
- Send a New signal story (image)

I have configured quite a lot of contacts. This is sent to most of them.

I send it to only a part and initially it also failed, but apparently for sent later.

**Actual result:** crash
**Expected result:** not crash and sens story

### Screenshots

![Screenshot_20240115-184937_1_1](https://github.com/signalapp/Signal-Android/assets/11966684/16671381-2554-425d-92bf-43fc620cfd3d)

### Device info

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.15.0  
**Build-ID:** `TQ3A.230901.001.23415000`
**Signal version:** 6.43.2

### Link to debug log

https://debuglogs.org/android/6.43.2/5d3f3f3ee99256ba1effd39f3a84e77270e690e7019450c1769e38e54d084170

**Comment by cody-signal** [comment]
Please try when 6.43.3 or 6.44.2 are available to you, it has the fix.
