### ISSUE TITLE
Former Signal user's profile still shown

### ISSUE THREAD

**Issue by julianfairfax** [signalapp/Signal-Android#13361]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a contact leaves Signal, their profile information is still shown in sections such as the blocking contact interface. It should be deleted from your device when a user leaves Signal.

### Steps to reproduce
- Add a Signal user to your device and Signal contacts
- The user must leave Signal
- Go to the blocking contacts interface

**Actual result:** You can still see their profile info (such as photo)
**Expected result:** They should have no info, like all the other contacts in your device

### Device info

**Device:** Google Pixel 6a
**Android version:** 14
**Signal version:** 6.43.2

([this is an old issue](#11553))

**Comment by greyson-signal** [comment]
We keep the last-known name we have for the user, so you can see it in your existing chats that you may have with that person before they become unregistered. This is working as intended.
