### ISSUE TITLE
New AboutSheet - no string "1 group in common"

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#13362]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The text "1 groups in common" in the new aboutSheet is wrong.
At least in german the translated string "1 gemeinsame Gruppen" is wrong.
It should be "1 gemeinsame Gruppe".

https://github.com/signalapp/Signal-Android/blob/c725a2fabb76f88d555c9f8b3c4f1cbdde4d4593/app/src/main/res/values/strings.xml#L1899-L1900

See also this string:
https://github.com/signalapp/Signal-Android/blob/c725a2fabb76f88d555c9f8b3c4f1cbdde4d4593/app/src/main/res/values/strings.xml#L1033-L1038

### Device info
**Signal version:** 6 .43+

**Comment by cody-signal** [comment]
Fixed in an upcoming release (6.45)
