### ISSUE TITLE
signal backup restore fail

### ISSUE THREAD

**Issue by ThaChillera** [signalapp/Signal-Android#13376]
- [ ] I have searched open and closed issues for duplicates (commented in closed issue #12990 )
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes during the backup restore process

### Steps to reproduce
- latest version of signal
- backup db version 210
- restore, almost done, signal crashes
- see comment in linked issue for stack trace

**Actual result:** crash
**Expected result:** restore done, everything works

### Device info

**Device:** Samasung Galaxy S10
**Android version:** 13
**Signal version:** 6.43.3

### Link to debug log
No debug log capabilities during setup, see https://github.com/signalapp/Signal-Android/issues/12990#issuecomment-1902192294 for stacktrace

**Comment by cody-signal** [comment]
After a failed attempt, can you relaunch and then tap any screen title 8 times and that should generate a full debuglog for us.

**Comment by ThaChillera** [comment]
When trying again the restore worked as expected, so  ¯\\_(ツ)_/¯. For anyone else experiencing this: just keep wiping signal app storage and trying I guess, I didn't do anything expect try again 48 hours later, same signal app same backup file.
