### ISSUE TITLE
Error in Signal: java.lang.IllegalStateException: Check failed

### ISSUE THREAD

**Issue by aronmal** [signalapp/Signal-Android#13397]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't really open Signal anymore, it crashes after 1-3 seconds continuously. Also when being in other apps, I get an android warning about the crash of Signal also many times.

This happens since today evening, I also noticed a weird bug today before lunch, in one recent chat there was an empty message, just a time and unread checkmarks,  it I was flat (looked kinda bugged) and I didn't send it. I don't know if this is related.

My main concern at the moment is, is there a way to rescue my chats to hopefully restore them? Or if the chats are also corrupted, to fix them to restore a fixed backup?

### Steps to reproduce
- I don't know

**Actual result:**  I don't know
**Expected result:** To not have a crashing Signal

### Error info from android when the pop up occoured
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002.B2/2024010700:user/release-keys
package: org.thoughtcrime.securesms:137702
process: org.thoughtcrime.securesms
processUptime: 2598 + 486 ms
installer: com.aurora.store

java.lang.IllegalStateException: Check failed.
at org.thoughtcrime.securesms.database.RecipientTable.splitForStorageSync(RecipientTable.kt:2238)
at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:106)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:410)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
at [[ ↑↑ Original Trace ↑↑ ]].(:0)
at [[ ↓↓ Exception Message ↓↓ ]].(:0)
at Check failed..(:0)

```

### Device info
**Device:** Google Pixel 4 XL
**Android version:** 13 (graphene os)
**Signal version:** 6.44.3

### Link to debug log
Not possible to access the app long enough to make a backup nor get a debug log.

**Comment by aronmal** [comment]
OMG, the App just did crashed instantly, I wanted to make a backup, but when I switched apps to save the backup passphrase Signal crashed again when entering. But this gave me hope. I got it again to not instantly crash when going into the settings. I was able to make a backup and also afterwards create a debug log.

The link:

https://debuglogs.org/android/6.44.3/c26d3999cdedd4dd8360ea7d43705f81c39ee98dc8fb9f0bfe9675d10b2047b6

**Comment by aronmal** [comment]
I also noticed, when I left the settings and tried to send a message, it was just spinning and not really sending. After going to the home screen and opening signal again I saw the message was being send (spinning, first checkmark, two checkmarks, followed by a crash) and the app crashed again right after.

**Comment by aronmal** [comment]
I know why I could open Signal, I am currently in a Bus and have a bad internet connection. I noticed, when I disable Network, Signal does not crash. So I was a bit lucky I stumbled across this when I had a weak mobile signal.

I will try to restore my backup on a second phone to check if my chats have corrupted data maybe triggering this crash. I hope not, but otherwise I wonder what the cause of the crash is.

**Comment by aronmal** [comment]
I just tried my old phone where I had Molly installed as a linked device from when I migrated to my new phone. I noticed it is also crashing now.

I will later try if I am able to restore the backup on the signal app on my old phone with a land line number as account. I am not too optimistic and am expecting it to also crash. I will let keep you posted.

**Comment by aronmal** [comment]
I now restored the backup in my current phone in Molly, it did worked as well as the registration. Then I tried to re-register my account in the signal app and it worked and had no crashes since. I noticed the messages being send slower, but this may be because I am still on the road.

**Comment by nicholas-signal** [comment]
This should be addressed by the v6.45.2 release.

**Comment by aronmal** [comment]
Did you know what the problem was?

**Comment by nicholas-signal** [comment]
> Did you know what the problem was?

You may see the relevant fix here: https://github.com/signalapp/Signal-Android/commit/9d1514308a2e7dedfb16b8dc3467d122f8a5260d
