### ISSUE TITLE
Signal crashes after opening, when in airplane mode does not crashes 

### ISSUE THREAD

**Issue by WimTh** [signalapp/Signal-Android#13393]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening signal on my pixel 8pro it crashes . When i put the phone in airplane mode it stays open.
The strange thing is that when i am in settings in airplane mode and then turn off airplane mode it closes settings and then closes signal.

### Steps to reproduce
- start signal, auto minimize

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
crashes signal
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
keeps running

### Device info

Pixel 8Pro 
14 build UQ1A.240105.004
6.44.3

### Link to debug log

https://debuglogs.org/android/6.44.3/1d106d3612a476c5f961aaabff14c1d2fb4d92a130a517d59dca10de5ea2ec38

**Comment by WimTh** [comment]
I have tried to restore from a backup but signal keeps crashing

**Comment by nicholas-signal** [comment]
This should be addressed by the v6.45.2 release.
