### ISSUE TITLE
Truncated Videos (1-second)

### ISSUE THREAD

**Issue by stevenwalton** [signalapp/Signal-Android#13406]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When uploading a video, the video gets truncated to 1 sec long. In the preview, video will show correct metadata (such as 0:59 . 16.3MB) but when clicking send the processing part takes awhile and then suddenly jumps to the end and says 0.3MB or 0.6MB (I've seen no other values and 0.3MB was only first observed today. Usually 0.6MB). When I download the video I get a different quality and information (via Google Photos)

Uploaded:
8.3 MP . 3840 x 2160
On device (355 MB)

Downloaded:
0.9 MP . 1280 x 720
On device (327 kB)

Pictures are unaffect. E.g. 
Upload
12.5 MP . 4080 x 3072 . Ultra HDR
On device (2.7MB)
(Signal says 0.8 MB while uploading)

Download
12.5 MP . 4080 x 3072 . Ultra HDR
On device (871 kB)

Settings > Data and storage > Media quality > Sent media quality > High

### Steps to reproduce
- Take Video
- Upload Video

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
[edit removed media]

### Device info

Device: Pixel 6 Pro
Android version: 14
Signal version: 6.46.3

### Link to debug log
Can produce upon request, prefer not publicly sharing

**Comment by nicholas-signal** [comment]
This issue was fixed in 6.46.4, please update and try again. If the problem persists, a debug log would be extremely helpful.

**Comment by stevenwalton** [comment]
Confirmed working on my end, so I'll close the issue. Version: 6.46.5

RE debug logs, these would be more readily given were they not public. While I'm sure there are no identifying information in the logs it is thousands of lines and... well... Signal is a privacy app and aint no one got time to verify. So I think it is reasonable to assume people are going to provide minimal amount of information necessary.  Especially considering how what may not be identifying at one point of time may become identifying at a later date and we don't want to just be leaving fingerprints everywhere. Looks like we can save it too, so maybe higher compliance if we're asked what to grep for? Maybe there could also be some clarity in generation and these could autodelete or have user control?

**Comment by nicholas-signal** [comment]
> Maybe there could also be some clarity in generation and these could autodelete or have user control?

As you would expect, we take privacy extremely seriously. Debug logs are scrubbed of all personally identifying information, including all phone numbers, encryption keys, and so on before being uploaded. As far as how they're generated, it's quite simply a bit of diagnostic information (very easy to glance at the top) followed by the `logcat` output of only the Signal app. Again, any PII in this output is obfuscated. We include all of it because you can never know what will be relevant to a bug.

Uploaded debuglogs are expired and purged automatically.
