### ISSUE TITLE
App Crashes while processing backup 

### ISSUE THREAD

**Issue by benediktrauch** [signalapp/Signal-Android#13401]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since last update (6.46.1) the app keeps crashing after some seconds. It's probably related to an backup running in background. App diagnostics are showing a lot uncaught exceptions in FullBackupExporter:

SignalUncaughtException: at org.thoughtcrime.securesms.backup.FullBackupExporter.isNonExpiringMessage (FullBackupExporter. java:595)
SignalUncaughtException: at org.thoughtcrime.securesms.backup.FullBackupExporter.isForNonExpiringMessage (FullBackupExporter. java :613)

After disabling the backup it seems to be stable and not crashing.

### Steps to reproduce
Nothing special, maybe just some expiring messages and backups enabled.

### Device info

**Device:** Google Pixel 6 Pro
**Android version:** 14 Build UQ1A.240105.002
**Signal version:** 6.46.1 (beta user on Google Play)

### Link to debug log
https://debuglogs.org/android/6.46.1/54514ac9c7f6661da619811b46cf84f6d574598f4549fc03549051df97235a43

**Comment by bwskin** [comment]
I also encounter same this issue. I noticed that I can rename backup directory and app starts showing notification about backup dir removal, but no crash - temporary workaround. Re-enabling backups to new dir causes crashes again.

**Comment by giseledute** [comment]
I also have the same problem

**Comment by Mati312** [comment]
Same problem here since today - Backup stops at 10.5% and then the app crashes. Backups can not be completed.

**Comment by IHadAThoth** [comment]
Same issue. App crashes creating the backup, using significant battery in the process, and there is no "skip" or abort option (without turning off backups entirely)

**Comment by ElCruncharino** [comment]
I can also confirm this issue.

**Device info**
Device: Google Pixel 6
Android version: 14 Build UQ1A.240105.002
Signal version: 6.46.1 (beta user on Google Play)

**Comment by lukebarone** [comment]
Same here, Samsung Galaxy s 20

**Comment by jlsnt** [comment]
Likewise.
Pixel 6, GOS, Android 14, Signal 6.46.1.

**Comment by nicholas-signal** [comment]
Hello everyone,

We have submitted 6.46.3 to [Firebase App Distribution](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538) and the Google Play Store which should fix this crash. It should be immediately available via Firebase, and hopefully the Play Store should be distributing it asap.

**Comment by giseledute** [comment]
> 
It worked! Thank you very much!

**Comment by benediktrauch** [comment]
> Hello everyone,
> 
> We have submitted 6.46.3 to [Firebase App Distribution](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538) and the Google Play Store which should fix this crash. It should be immediately available via Firebase, and hopefully the Play Store should be distributing it asap.

Got the update from Google Play, backup went through. I think we can consider it as fixed and close this issue. 

Thanks a lot for that quick fix 👍
