### ISSUE TITLE
Unable to register Signal with new phone. "Unable to connect to service."

### ISSUE THREAD

**Issue by gravidThoughts** [signalapp/Signal-Android#13414]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is unable to send an SMS with a code for registration. After searching the issues, this was a problem in Spring 2023 that appeared to be resolved with 6.14. Also research showed that the call verification had been reintroduced in Fall 2023, but I am not being provided this option.

I have been trying for the last few days, and the logs clearly show that my provider Mobifone is rejecting the SMS. I am concluding this is not something that is intermittent. I am able to receive SMS messages.

### Steps to reproduce
Clean installation of Signal with a never registered phone number. After completing the captcha successfully and verifying the phone number receive a message starting with "Unable to connect to service."

**Actual result: Unable to register new Signal installation via SMS. I am **not** prompted to verify via call instead. 
**Expected result Able to register via SMS, or if unable, provided the option to complete verification by call.

### Device info

**Device:** Samsung Galaxy Tab A7 Lite
**Android version:** 14
**Security Patch Level:** Dec 1 2023
**Signal version:** 6.46.7
**Mobile Provider:** Mobifone (Vietnam)

### Link to debug log

https://debuglogs.org/android/6.46.7/baf4492fe14cd8bddb40a26d07b0b40e19a1219eaa98dbd2217fa39b54b659a3

**Comment by 0x4649** [comment]
I'm having a similar problem trying to re-register Signal on a new phone and getting "Unable to connect to service.", as described in this issue: https://github.com/signalapp/Signal-Android/issues/12839

now unable to register either old or new phone with Signal and stuck in a loop of "you've made too many attempts to register", as in this comment https://github.com/signalapp/Signal-Android/issues/12839#issuecomment-1467519805

Using Graphene OS without Google services, Signal 7.7.2 APK downloaded from signal.org

Devices: Pixel 6a and 8a
Android version: 14
Signal Version: 7.7.2

**Comment by RasheedAZ** [comment]
I'm having a similar problem but not getting any "Unable to connect to service" message. It just keeps giving me the hcaptcha over and over again even though I fill it correctly and then after repeated attempts, it bans me for 4 hours.

This happens whether I try to re-register Signal on the same phone, register a new number on the same phone or registering a new number on a phone on which Signal was never installed.

Devices: Pixel 5 | Nokia 2.1
Android version: 14 | 10
Signal Version: 7.7.2

Pixel is using MicroG on CalyxOS and Nokia is Google Play services with stock Android.

I have confirmed that I can send and receive SMS messages.

My country code is 64.

**Comment by cody-signal** [comment]
@RasheedAZ can you post a debuglog after failed attempts? You can tap the title of any screen during registration 8 times to get a debuglog link. Thanks!

**Comment by 0x4649** [comment]
> Hi,
> 
> If you can upload your debug logs, I can see exactly which error is occurring.

Thank you, now trying with 7.8.1 from signal.org

https://debuglogs.org/android/7.8.1/831b58ae33e6e0fe8e426d33e0d32351d254277110ad37868439dadbd06fd976

**Comment by cody-signal** [comment]
@0x4649 it looks like you are having a lot of connectivity problems reaching our servers. Is it possible to try without a VPN?

**Comment by 0x4649** [comment]
> @0x4649 it looks like you are having a lot of connectivity problems reaching our servers. Is it possible to try without a VPN?

Thanks, same result I'm afraid but will try again later. 

Are you saying VPNs are being blocked or throttled server side?

**Comment by cody-signal** [comment]
We aren't doing anything on our server side. Something between your client and our servers is timing out and preventing you from connecting to us. I noticed you had a VPN and sometimes VPNs can do that depending on the quality of the vendor, so we always ask folks that have evidence of network connectivity problems to try without VPN to see if anything changes.

**Comment by 0x4649** [comment]
> We aren't doing anything on our server side. Something between your client and our servers is timing out and preventing you from connecting to us. I noticed you had a VPN and sometimes VPNs can do that depending on the quality of the vendor, so we always ask folks that have evidence of network connectivity problems to try without VPN to see if anything changes.

Thank you for confirming! Is there an easier way for me to verify network connectivity than going through the registration process?

**Comment by 0x4649** [comment]
@cody-signal tried cycling VPN connections, connecting to different servers, disconnecting from the VPN, etc.

When retrying from the Signal PIN code screen it seemed like the connection was failing immediately so wasn't sure changes were being taken into account.

That made the process a bit painful because, when transferring data from an old phone, if Signal is closed on the new device you have to re-register the old device and start again from the beginning.

Eventually uninstalled the VPN app (https://f-droid.org/packages/de.blinkt.openvpn/) from the new device and made the (same) VPN connection from the WAP the phone connected to instead to get it working.

**Comment by pbryant0915-sketch** [comment]
Im Having the same issue right now at the same time i cant produce QR code on the app itself in my laptop its just keeps spinning and still no QR hoping you Could help me @cody-signal @nicholas-signal 

<img width="809" height="528" alt="Image" src="https://github.com/user-attachments/assets/ecb644e7-84c8-45a5-ad6b-07a0bfc4104f" />

**Comment by pbryant0915-sketch** [comment]
also on my phone it said signal couldn't send an sms code because of issues with the sms provider, i cant receive Code or any call

**Comment by pbryant0915-sketch** [comment]
I tried to email SIgnal Troubleshoot already for a month now still no response on isse

**Comment by Cornelius1124** [comment]
Android 15
SM-16 
Signal version 7.69.2 

I still cant connect even i used vpn it still wont working
