### ISSUE TITLE
App crash when opening replies to group story

### ISSUE THREAD

**Issue by fwinn** [signalapp/Signal-Android#13415]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to open the replies to another person's group story, the app crashes - even if there are no replies yet.

### Steps to reproduce
- another person posts a group story
- view that story
- Click "Reply to group"

**Actual result:** The app crashes
**Expected result:** Possibility to reply to the group story

### Device info
**Device:** Google Pixel 6
**Android version:** 14
**Signal version:** 6.46.7

### Link to debug log
[Link to logs](https://debuglogs.org/android/6.46.7/7fe87bbc15575209d823fb3f4f4ba6cecf40eceacfc354292e0b970617d3eb45)

**Comment by fwinn** [comment]
Fixed in version 6.47.4

**Comment by fwinn** [comment]
It happens again in v 7.6.2, this time also when it's my own group story. But it just seems to happen when there's already at least one reply.

**Comment by alex-signal** [comment]
@fwinn Could you please add a debug log?

**Comment by fwinn** [comment]
Yes, [here you go](https://debuglogs.org/android/7.6.2/73a54befb644cf855d050bf8b189c006355d895501ecabb88aae463e00c6b818)

**Comment by fwinn** [comment]
Fixed in version 7.7.2 👍
