### ISSUE TITLE
warn about max 10 edits BEFORE editing NOT AFTER

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#13428]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

If you edit a message for the 11th time (I do that with my todo pist wich is a note to self message) Signal android lets you write 5 paragraphs if you like only to tell you more than 10 edits are not allowed when you try to press submit. Could and should have warned you when you started editing rather than after.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Arthur-GYT** [comment]
I've opened a PR for this issue. Now we just have to wait ^^.
