### ISSUE TITLE
key_value constant value not consistently used in KeyValueDatabase.java

### ISSUE THREAD

**Issue by epachamo** [signalapp/Signal-Android#13422]
- [ x] I have searched open and closed issues for duplicates
- [n/a ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the file Signal-Android/app/java/org/thoughtcrime/securesms/database/KeyValueDatabase.java the final String for TABLE_NAME is created on line 37.

  private static final String TABLE_NAME = "key_value";

In the code it is inconsistently used. To prevent future error when code is changed, the string "key_value" should only appear in this variable declaration. Instances of its use on lines 81, 82, 99, 100, and 101 should be updated with the TABLE_NAME string variable.

### Steps to reproduce
N/A

### Screenshots
N/A

### Device info
N/A

### Link to debug log
N/A

**Comment by Adityaupadhye** [comment]
Opened a PR to resolve this issue. #13426

**Comment by cody-signal** [comment]
As stated in the PR, these are migration methods and must be hard coded to match the names used at the time of migration.
