### ISSUE TITLE
AttachmentCipherTest not working properly 

### ISSUE THREAD

**Issue by Abdullah-mb** [signalapp/Signal-Android#13436]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In AttachmentCipherTest class the following function (attachment_encryptDecryptEmpty, sticker_encryptDecryptEmpty) always throw InvalidMessageException.
why do we use assertArrayEquals without using try and catch block.

### Steps to reproduce
- open signal project
- go to libsignal-service
- run unit test for AttachmentCipherTest

**Actual result:** function throws invalidMessageException and test failed
**Expected result:** A function that catch invalidMessageException and test success 

### Screenshots

![Screenshot from 2024-02-20 13-29-20](https://github.com/signalapp/Signal-Android/assets/47639120/f8dba2f4-da96-4352-9d02-7401d4fcf3b2)

### Device info

**Device:** Pixel 3a
**Android version:** 10
**Signal version:** 7.0

**Comment by cody-signal** [comment]
All tests pass. Are you on a mac?

**Comment by satvik2131** [comment]
all tests passed in Linux-Ubuntu as well 
![Screenshot from 2024-02-27 14-24-15](https://github.com/signalapp/Signal-Android/assets/59243339/7b77f875-73c1-4d78-97e1-456337e95291)
