### ISSUE TITLE
Updating Verification-Metadata.xml file fails with ktlint Code style violations

### ISSUE THREAD

**Issue by clauz9** [signalapp/Signal-Android#13448]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Running `./gradlew --write-verification-metadata sha256 qa --rerun-tasks` fails because of code style violations from `ktlint` in auto generated files 

`Signal-Android\libsignal-service\build\generated\source\wire\...`
`Signal-Android\build-logic\plugins\build\generated-sources\...`

### Steps to reproduce
- run `./gradlew --write-verification-metadata sha256 qa --rerun-tasks` on a fresh checkout of Signal-Android

**Actual result:**  The command fails
**Expected result:** The dependencies checksums should be updated 

### Screenshots
<details>
<summary>Screenshot</summary>

![image](https://github.com/signalapp/Signal-Android/assets/77681918/4b9afa51-4366-4a39-99f4-fbb19bcc09cd)

![image](https://github.com/signalapp/Signal-Android/assets/77681918/0645dfb5-f281-4757-93f1-342aa7051a2f)

</details>

### Device info

**Device:** N/A
**Android version:** N/A
**Signal version:** N/A

### Link to debug log
N/A

**Comment by cody-signal** [comment]
Hi there, we use github solely for bug reports. For help with development tasks, check out our forum: https://community.signalusers.org/c/development/6
