### ISSUE TITLE
Crash when opening story reply menu

### ISSUE THREAD

**Issue by p0wl90** [signalapp/Signal-Android#13442]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal always crashes when opening story answer/reaction menu. Bug exists since a few updates (approx. 1-2 months)

### Steps to reproduce
- open a story sent by other persons
- tap "reply to group"

**Actual result:** Menu bottom sheet starts to open but has a weird gap between some emojis. But opening animation immediately stops and the app goes back to main menu. Sometimes, Android crash info dialog is displayed.

**Expected result:** The reply menu opens and can be used

### Screenshots

<img src="https://github.com/signalapp/Signal-Android/assets/6959020/d1368064-c1ed-4112-8350-4a080ec7e557" height="400">

### Device info
**Device:** Google Pixel 8
**Android version:** 14
**Signal version:** 6.46.7

### Link to debug log
[Link to log](https://debuglogs.org/android/6.46.7/00969ccbccca336ca4e27029c1692242f644c427c7ef44bfe6d637fa9bc699fc)

**Comment by greyson-signal** [comment]
I believe this is fixed in 6.47+, which is in the process of rolling out
