### ISSUE TITLE
voice note crashes/reboot my phone

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#13441]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice note msg crashes my phone and it reboots.
Msg: 1708714168408
Reproducable reboot at 0:30 to the end

### Steps to reproduce
- listen to rceived voice note
- downcountin timer runs to ~0:30 a short loud 'click' sound and phone reboots

**Actual result:** 
Phone reboots at specific time if a specific voice note.
**Expected result:** 
Fully played
### Device info

**Device:** Sony XZ2c, LOS 20
**Android version:** 13
**Signal version:** 6.47.4

### Link to debug log

https://debuglogs.org/android/6.47.4/6a327e812ac87967fb7fe07d694f6e70c2aedef888d4c990cedac7f99baea6fd

Senders log:
https://debuglogs.org/android/6.47.4/00b5feaba8cc559250406ba08da006112ee443f65334af7e5ee5e583fe695569

**Comment by greyson-signal** [comment]
Hmm, unfortunately the logs don't capture the crash. This can happen with system crashes. Media playback defers to the systems built-in decoders, and my guess is that there's likely an OEM-specific bug. I'm closing this just because I don't think there's much we could do here.
