### ISSUE TITLE
Missing username setting

### ISSUE THREAD

**Issue by zoot** [signalapp/Signal-Android#13459]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Earlier today, while using my phone, I was prompted to add a username, I think ... or I found the option via the settings. I can't recall, because I was multi-tasking! I managed on Signal Desktop, but can't find the appropriate page on Signal App on Android.

### Steps to reproduce

- Open Signal App
- Tap on my profile icon, top left
- Tap on the enlarged profile icon, next to phone number
- Only Name, About and Badges shows

**Actual result:**

No username selection option.

**Expected result:**

Option to add/edit username, as per Signal Desktop, via the sequence above.

### Device info

**Device:** Google Pixel 6
**Android version:** 14
**Signal version:** 6.47.5

**Comment by nicholas-signal** [comment]
This issue should be resolve in 7.0.2, which is currently rolling out.

**Comment by zoot** [comment]
Thanks @nicholas-signal - I installed the update a few moments ago and the username settings now show on the profile page 👍🏼
