### ISSUE TITLE
emoticon in the app are incorrect

### ISSUE THREAD

**Issue by mealejan** [signalapp/Signal-Android#13456]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The emoticons that I select are not the ones being transmitted. On both test devices the option use system-emoticons was turned off. Enabling the option to use  system emojis results in the actual emoticons that are received to be displayed on the sender. This bug is not related to the appearance or design of the emoticons, it is about the actual emoticon, the screenshot shows that the emoticons don't match. Not all emojis are affected.

### Steps to reproduce 
Procedure A:
1. Open a chat with a contact
2. Select an emoticon through signal
3. Send emoticon
Procedure B:
1. Open a chat with a contact
2. Select an emoticon from gboard
3. A different emoticon is inserted into chat field
4. Send the message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Different emoticon is transmitted of the one selected
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
A: Selected emoticon is being transmitted 
B: Selected emoticon is added to the chat field

### Screenshots
![bug_signal](https://github.com/signalapp/Signal-Android/assets/29132948/e6808e3d-2701-4582-a8b6-3edd8957c02f)

### Device info
**Device:** Pixel 8
**Android version:** 14 
**Signal version:** 6.47.5

### Link to debug log
[]https://debuglogs.org/android/6.47.5/7e2648c5804ad2250e53285f4bedf859e93df10ff32fa8efdda4cf16862550f0

**Comment by greyson-signal** [comment]
Hi there! Unfortunately it looks like there's a bug with the emoji set we compile into the app. Normally a device would download the higher-res versions after they install, which is why I'm guessing this is the first report we've gotten of this.

Did you just install the app? Could you share a debuglog? That could tell us why you haven't downloaded the new version. 

Obviously the built-in mapping being wrong is bad and is already fixed in 7.1, but for you specifically, we could hopefully fix your situation so that you can get the remote copy of the emoji index.

**Comment by mealejan** [comment]
I have the app installed since November 2023. Debuglog was posted but hidden in the original bug report, it is un-hidden now.

**Comment by davidtorcivia** [comment]
I also have this problem with the most recent beta install. First noticed it with reactions: 👍 is now 🫵, 😮 is 🙁, 🤖 is 👽, etc. 

Android 14. 

[signal-log-1709664193944.zip](https://github.com/signalapp/Signal-Android/files/14500010/signal-log-1709664193944.zip)

Debug log: https://debuglogs.org/android/7.0.2/791659659370cda688823c3cf15062557f1fc802542dadd4c2bb2a5b9959b9c0

**Comment by fireflames** [comment]
I have the same issue for a while, but I have the app installed for a long time. When I noticed I was still using version 6.x, I then updated and are now running 7.0.2. 7.1  is not available in the play store for me at the moment.

It also happens with a lot more smileys as documented here.

Also, is there an option to force update the smiley index?

https://debuglogs.org/android/7.0.2/c631824b8d58ef98c8ce52705e8607fbad4f18b388277540aac8bd2168ca55f5

**Comment by mealejan** [comment]
I am not experiencing this bug anymore with 7.0.2.

**Comment by fireflames** [comment]
Without any Updates it fixed itself at some point

**Comment by greyson-signal** [comment]
Yes, it should "fix itself" once the higher-quality emoji are downloaded, replacing the low-res versions we package in the app. The bug is fully resolved in 7.1.x, so closing.
