### ISSUE TITLE
No emoji reactions and no context menu for URL / link only messages

### ISSUE THREAD

**Issue by ThomasMeschke** [signalapp/Signal-Android#13457]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving messages, one can open the reactions and the context menu to these by holding them pressed, so the overlay opens up. 
When receiving messages containing nothing more than a valid URL with no preview, holding it pressed copies the URL to the clipboard. 
This results in not being able to e.g. emoji-react to messages containing nothing more than a valid URL with no preview. 

### Steps to reproduce
- receive a message containing nothing more than a valid URL with no preview
- open the chat
- try to emoji-react to the received URL message

**Actual result:** little toast at the bottom stating the URL has been copied
**Expected result:** same option dialog like on every other message, enabling emoji-reactions and showing a context menu for replying, forwarding and so on, since this already offers an option "copy" which would also simply work for URLs.

### Screenshots
- none -

### Device info
**Device:** Nokia 6.1 (2018)
**Android version:** 10
**Signal version:** 6.46.7

### Link to debug log
https://debuglogs.org/android/6.46.7/5421057d2ce224e88d04000168cc7eccf00d88ed55d4fe81a1d7890fedba1b93

**Comment by nicholas-signal** [comment]
You may invoke the context menu on URL-only messages by carefully long-pressing anywhere other than the URL, such as the message bubble itself, or the text of the link preview.

**Comment by ThomasMeschke** [comment]
Pretty inconvenient in my opinion. Not quite user friendly...
