### ISSUE TITLE
Keyboard greyed out for PIN verification

### ISSUE THREAD

**Issue by Kyle0** [signalapp/Signal-Android#13460]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to verify PIN as Signal Android periodically requests, the keyboard to enter the PIN is greyed out and unresponsive.

### Steps to reproduce
- After "Verify your Signal PIN" message appears, tap on verify PIN
- Try to use keyboard to enter PIN into the PIN input field

**Actual result:** Keyboard for verify PIN modal does not function or respond
**Expected result:** Screen keyboard inputs typed characters into PIN input field

### Screenshots

![Screenshot_20240305-094021](https://github.com/signalapp/Signal-Android/assets/3329946/ac47bc77-530a-4b01-b07f-a66885a1001a)

### Device info

**Device:** Fairphone 4
**Android version:** CalyxOS 5.4.0 (Android 14)
**Signal version:** 6.47.5

### Link to debug log

https://debuglogs.org/android/6.47.5/3982c0a8fb93e2368c860c1378f948652228c7ffccb86fc865dfc8aa6caea0f2

**Comment by Kyle0** [comment]
After a few hours, this bug seems to have gone away on my device. If no one else is able to replicate it, feel free to close this issue.

**Comment by alex-signal** [comment]
Given that the keyboard here is completely controlled by the OS, I'm going to chalk it up to an issue with CalyxOS.

**Comment by estan** [comment]
Just to add as a note here: I had this problem yesterday, but today it's magically gone just like for @Kyle0.

I'm on Fairphone 5 with Android 14.
