### ISSUE TITLE
Signal phone number as a login flaw

### ISSUE THREAD

**Issue by Pantyhose-X** [signalapp/Signal-Android#13478]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Signal requires a cell phone number as a login flaw
1. The SIM operator can block text messages from its own Signal. 
2. The SIM operator and FBI can use your mobile phone number to log in. unless you set up TOTP
3. If the operator deletes your mobile phone number, your Signal will not be logged in if it is scrapped. .

### The best solution.
* phone number + login password
* No SMS messages, including verification codes, will be sent to the cell phone number.
* Signal login does not require SMS verification code.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by greyson-signal** [comment]
HI there, we use Github exclusively for bug reports. For discussions, please use the [forum](https://community.signalusers.org/). Thanks!
