### ISSUE TITLE
Deleting a username not freeing it to be reserved by another account

### ISSUE THREAD

**Issue by 0xunusedusername** [signalapp/Signal-Android#13475]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Deleting a username does not free it to be reserved by another account

### Steps to reproduce
- delete username reserved on one account
- attempt to claim from a different account

**Actual result:** username says it's still unavailable
**Expected result:** username is available to reserve from the other account

### Device info

**Device:** Google Pixel 8 Pro
**Android version:** 14.0.0_r29
**Signal version:** 7.0.2

The log says UsernameRepository: [deleteUsername] Successfully deleted username

But it's still not available

**Comment by 0xunusedusername** [comment]
`INFO  2024-03-15T18:22:19.993Z PUT (REST) https://chat.signal.org/v1/accounts/username_hash/reserve
INFO  2024-03-15T18:22:20.148Z createHTTPSAgent.createConnection(chat.signal.org): connected to IPv4 addr after 145ms (attempts v4=1 v6=0)
ERROR 2024-03-15T18:22:20.242Z PUT (REST) https://chat.signal.org/v1/accounts/username_hash/reserve 409 Error
INFO  2024-03-15T18:22:27.416Z handleOutsideClick: ProfileEditorModal handled click
INFO  2024-03-15T18:22:29.441Z handleOutsideClick: ConfirmationDialog.EditUsernameModalBody.confirmChange handled click
ERROR 2024-03-15T18:22:29.442Z assert failure: Error: This should not happen
    at assertDev ([REDACTED]/Resources/app.asar/preload.bundle.js:21:278)
    at [REDACTED]/Resources/app.asar/preload.bundle.js:96:215791
    at [REDACTED]/Resources/app.asar/preload.bundle.js:136:214
    at [REDACTED]/Resources/app.asar/preload.bundle.js:126:267695
    at n.<computed> ([REDACTED]/Resources/app.asar/preload.bundle.js:82:47333)
    at Object.action ([REDACTED]/Resources/app.asar/preload.bundle.js:123:32784)
    at onClick ([REDACTED]/Resources/app.asar/preload.bundle.js:86:316953)
    at Object.Rb ([REDACTED]/Resources/app.asar/preload.bundle.js:68:9858)
    at Xb ([REDACTED]/Resources/app.asar/preload.bundle.js:68:10032)
    at Yb ([REDACTED]/Resources/app.asar/preload.bundle.js:68:10104)`

response when attempting to reserve the deleted username

**Comment by 0xunusedusername** [comment]
Deleting the account entirely does not appear to free it either

**Comment by greyson-signal** [comment]
I forget the exact period of time (maybe 3 days?) but usernames are, in fact, unreservable by others for a period of time after removing it. This is intended to prevent usernames getting taken from someone before they've had a chance to let people know they've changed their username.
