### ISSUE TITLE
Incognito keyboard not applied on search in message

### ISSUE THREAD

**Issue by LoHub** [signalapp/Signal-Android#13484]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When incognito keyboard is switch on, my keyboard is in incognito mode when I type messages but not when I use search in message.

### Steps to reproduce

- Enable incognito keyboard in settings
- Go in any conversation
- Press tree dot menu
- Select `Search`

**Actual result:** Keyboard appear in normal mode
**Expected result:** Keyboard appear in normal mode in incognito mode if supported

### Device info

**Device:** Pixel 8
**Android version:** Android 14
**Signal version:** 7.0.2
**Keyboard:** Swiftkey 9.10.31.21

**Comment by alex-signal** [comment]
Hi! Thanks for your bug report. I've fixed this for version `7.9.0`
