### ISSUE TITLE
No missed call notifications since a recent update

### ISSUE THREAD

**Issue by dandoor** [signalapp/Signal-Android#13496]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Missed calls don't invoke a notification since one of the recent updates (I am not sure which, but it was in the last few weeks).

### Steps to reproduce
- Get a call.
- Don't answer.

**Actual result:** No notification for the missed call.
**Expected result:** A notification should show.

### Device info
**Android version:** 14
**Signal version:** 7.1.3

**Comment by nicholas-signal** [comment]
Hello, please provide a debug log, as well as a date and time of the missed call, so we can attempt to diagnose the issue.

**Comment by dandoor** [comment]
Is there an email address or something to send the relevant log entries? I don't want to post it publicly

**Comment by greyson-signal** [comment]
You can email support@signal.org, tell them the issue number, and let them know to tell the android team. Thank you!

**Comment by dandoor** [comment]
Sent.

**Comment by ibeleliev** [comment]
The same happens to me with Signal v7.2.4 and Android 14. I will send the debug log to the provided email too now.

**Comment by toxpal** [comment]
Someone got it working? I have the same problem with both of my Android 14 phones (Pixel 6 and Nothing Phone) after specified Signal update. Can't get it working for weeks...

**Comment by mtvec** [comment]
This also happens to me (and everyone I regularly call with). Here's a [debug log](https://debuglogs.org/android/7.4.2/ccae2bd0e0b0223783f31adcd2251283da51ff8d5ce80497a6904457c50f49c1) of the most recent occurrence.

I would consider this a rather high priority issue as I often don't notice having missed a call until after quite some time. Please let me know if there's anything I can do to help debug this.

**Comment by cody-signal** [comment]
This was unintended and will be fixed in 7.6 coming to beta soon.

**Comment by Izzet-Beltir** [comment]
Same issue on Signal 7.4.2, Android 14, Pixel 8

**Comment by dandoor** [comment]
Solved
