### ISSUE TITLE
All conversations lost

### ISSUE THREAD

**Issue by bugith** [signalapp/Signal-Android#13494]
- [v] I have searched open and closed issues for duplicates
- [v] I am submitting a bug report for existing functionality that does not work as intended
- [v] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [v] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I didn't want to disturb at security@signal.org
My friends received a message stating their security number with me changed... After taping "Learn more" <-translated, they read I **probably** changed my phone or reinstalled Signal. Although I did none of these.
So the message let think this is an an eavesdrop.
### Steps to reproduce
- I can't say. I just can add that we changed DST this night (jump from 2AM to 3AM).
- Also when I looked at Signal this morning I was asked my phone number then the conversation list was empty.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Huawei Model ALE-L21
**Android version:** 6.0.0
**Signal version:** 7.1.3

**Comment by nicholas-signal** [comment]
Hello, please submit a debug log. We can use that determine what, if anything, caused the database to be wiped.

**Comment by bugith** [comment]
Can't repro/log unavailable
