### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by pippi1otta** [signalapp/Signal-Android#13499]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The conversation bottom sheet now calls "phone contact" what is known in other places in the UI as "system contact".

**Actual result:** Multiple names are used throughout the app for the same thing.
**Expected result:** Use one name everywhere, whatever it is. (just don't call it "story", please)

### Screenshots

![IMG_20240403_062714](https://github.com/signalapp/Signal-Android/assets/136894633/05b2693f-7866-4475-b6c1-3549a7ba4414)
![IMG_20240403_062733](https://github.com/signalapp/Signal-Android/assets/136894633/fc2061d1-c93f-49b6-b10c-1ebe8a76aa33)

### Device info
**Signal version:** 7.2.3

**Comment by Prab-27** [comment]
hey, @alex-signal please assign this issue I want to contribute and I am a beginner.

**Comment by pippi1otta** [comment]
@Prab-27 They have corrected the strings already - b50eab23.
Thanks, @greyson-signal and @alex-signal!
