### ISSUE TITLE
Cannot delete Signal contact from mobile contacts or from Signal itself

### ISSUE THREAD

**Issue by petrenkonikita112263** [signalapp/Signal-Android#13510]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Firstl of all you need at least one chat in your Signal at denied access to your contacts via the Signal app. In the end, Signal will create/add contact on your phone that you no longer can't remove.

### Steps to reproduce
- Open Signal, tap 🖊, and grant access to your local contacts (it will bring Compose to view your Signal contact list).
- Check one of your chat with person
- Try to delete phone number contact from Signal
- Then try to follow-up the info message and delete contact from your local contacts phone

**Actual result:** From Signal you'll receive message that you can't delete this account only from your phone contacts. But trying to delete from there will print you a message that you can only hide this contact.
**Expected result:** The contact was deleted without any issue

### Screenshots
No, I can't provide them

### Device info

**Device:** Blackview BV4900Pro
**Android version:** 10
**Signal version:** 7.2.4

**Comment by satvik2131** [comment]
I am not experiencing this issue , can you make a video recording of it and also the debug log .

**Comment by petrenkonikita112263** [comment]
Video, not sure. Regarding logs, I'll send them to the mail.

**Comment by satvik2131** [comment]
actually you can mention the logs here as well

**Comment by alex-signal** [comment]
Some people aren't comfortable posting debug logs in a public place. The support email is sufficient, please ensure to describe your problem or mention the github issue number.

**Comment by petrenkonikita112263** [comment]
Closing this issue, I can't understand why I'm getting a zip archive with logs, but after unzipping - there's no file, despite the fact I have the option to display hidden files.
