### ISSUE TITLE
Dealing with very quietly recorded voice messages

### ISSUE THREAD

**Issue by copyvar** [signalapp/Signal-Android#13519]
_This is not a feature request, as I see this behaviour as a bug._

When listening to multiple voice messages recorded very quietly, you would need to turn up the volume very high to actually be able to listen to it. The voice message ending sound is VERY LOUD then.

Please, add an option to disable voice message ending sound or just disable it in general (I do not even see a point, why it was added). Please also make it possible to only listen to the other persons' voice messages and not your own.

**Comment by clark-signal** [comment]
Hi, feature requests should be posted to the forum: https://community.signalusers.org/c/feature-requests/17

Although you may view it as a bug, the ending sound is working as intended.
