### ISSUE TITLE
Add capitalization to First and Last name in profile

### ISSUE THREAD

**Issue by pippi1otta** [signalapp/Signal-Android#13528]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The First and Last name in the profile do not have automatic capitalization set.

After adding capitalization to the Nickname activity in abfd9f8, I think the same should be done to the Your name activity under Profile, for symmetry.

### Device info
**Android version:** 13.0
**Signal version:** 7.4.2

**Comment by BenjaminMuslic** [comment]
I will try this. Contributing to open source for school project

**Comment by BenjaminMuslic** [comment]
I will work on this. Contributing to open source for school project.

**Comment by pippi1otta** [comment]
@BenjaminMuslic probably these:

- [EditProfileNameFragment.java](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/profiles/manage/EditProfileNameFragment.java)
- [edit_profile_name_fragment.xml](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/res/layout/edit_profile_name_fragment.xml)

**Comment by Eqerem-Hena** [comment]
@BenjaminMuslic Did you work on this, or could I take it on?

**Comment by BenjaminMuslic** [comment]
You can work on it

**Comment by pippi1otta** [comment]
Not fixed as of 7.11.4
