### ISSUE TITLE
Web preview identifies as "WhatsApp/2" as User Agent..

### ISSUE THREAD

**Issue by ThorstenSauer** [signalapp/Signal-Android#13522]
<!-- This is a bug report template. By following the instructions below and filling out the sections with your information, you will help the developers get all the necessary data to fix your issue.
You can also preview your report before submitting it. You may remove sections that aren't relevant to your particular case.

### Bug description
Web preview identifies as "WhatsApp/2" as User Agent..

### Steps to reproduce
- type "https://myserver.domain/signaltesturl/" as a message
- grep signaltesturl in the access logs of myserver.domain "grep signaltesturl /var/log/apache2/access.log"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Log Line shows:
/var/log/apache2/access.log:x.x.x.x - - [19/Apr/2024:09:40:05 +0200] "GET /signaltesturl/ HTTP/1.1" 404 819 "-" "WhatsApp/2"

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Log Line should show something like "SignalPreview" as user agent
/var/log/apache2/access.log:x.x.x.x - - [19/Apr/2024:09:40:05 +0200] "GET /signaltesturl/ HTTP/1.1" 404 819 "-" "SignalPreview"

**Comment by clark-signal** [comment]
We use this user agent so that websites generate proper previews.
