### ISSUE TITLE
Build failed. Is perhaps kotlinOptions javatarget missing in build-logic/tools?

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#13523]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I used to build Signal on Android Studio Flamingo but changed laptop and installed Iguana. Compiling failed with a mismatch between java and kotlin. After adding the kotlinOptions jvmTarget = signalKotlinJvmTarget to build-logic/tools/build.gradle.kts things start rolling. Is that option missing there or am I missing something?

### Steps to reproduce
- Try building a fresh checkout in Android studio Iguana.

**Actual result:** Build fails
**Expected result:** Build successfull

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by nicholas-signal** [comment]
Are you still unable to build the app? Have you tried "Invalidate Caches and Restart"?

**Comment by bme13** [comment]
Hi. Thanks for responding. Since this ticket was stale I didn't close it but due to the failure I kept using the Flamingo version on the old laptop. Recently Signal updated gradle and since that wasn't supported in Flamingo I've updated that to Koala. Building that worked fine. I haven't tried it with a fresh install though and struggle with other issues (nothing to do with Signal) on that laptop so can't easily try. Sorry for not closing this issue earlier but for now I'm able to build Signal.

**Comment by bme13** [comment]
Closing
