### ISSUE TITLE
Android: messages received, but the chat appears to be empty when accessed. Linked device works. Video attached.

### ISSUE THREAD

**Issue by Moggel1** [signalapp/Signal-Android#13531]
After using Signal for a long time, all of a sudden the chat does not open anymore. Signal receives the messages in the chat (the preview of the last message is shown), but as soon as the chat is opened, it's blank. This is a large chat, more than 10 Gigabytes.
We created a "group" chat, with only us two persons, and that is still working. However, our main chat cannot be accessed anymore.
I wasn't able to find this issue reported previously.

The affected person uses Signal on this phone as primary device, and is also using Signal Desktop (Windows 11) as linked device. There, on Signal Desktop, everything works fine, the chat can be used normally.

The chat partner uses an iPad and Signal Desktop, for him everything is normal.

A video of the issue is attached.
https://github.com/signalapp/Signal-Android/assets/127660551/75317236-fb97-4f69-a46a-c0eb9f09d37e

Debug log:
https://debuglogs.org/android/7.4.2/5dd4cf0acd124ffecd29faf5763375a6d2028ffe3d5c20045f8d8751849bd24e

Device: Oppo reno 6 lite
Signal version: 7.4.2
Android version: 13

**Comment by Raychani1** [comment]
I'm experiencing the same issue in one of my group chats. I thought it happened because I was messing with the system time. In the main menu I can see if somebody sends a message but once I open the chat it jumps back to an old message. Devices is linked to multiple desktops including Windows and Linux, and messaging just works fine.

Device: Google Pixel 7
Signal version: 7.4.2
Android version: 14

**Comment by cody-signal** [comment]
A debuglog from a device encountering the issue would be extremely helpful in this situation. (Settings->Help->Debug log)

**Comment by Moggel1** [comment]
I've updated the issue with the version numbers:
Signal version: 7.4.2
Android version: 13

I hope that I get the debug log soon, I'll update it here then. Thank you in advance!

**Comment by Moggel1** [comment]
> A debuglog from a device encountering the issue would be extremely helpful in this situation. (Settings->Help->Debug log)

I've updated the issue.
Here's the debug log:
https://debuglogs.org/android/7.4.2/5dd4cf0acd124ffecd29faf5763375a6d2028ffe3d5c20045f8d8751849bd24e

**Comment by Moggel1** [comment]
As I wrote above, we created a group chat for us two. This worked, but the issue began to occur there too. The chat can be opened and read, but always after a few seconds the chat closes itself automatically and returns to the chat overview. 
It can hardly be used, because it happens that the chat is closed during typing the message :(
The app itself doesn't seem to crash. It's "just" the chat that's always being closed.
@cody-signal

**Comment by cody-signal** [comment]
@Raychani1 Unfortunately, nothing is jumping out in your logs. Can you take one right after experiencing the problem and provide the full link to it or email the file to me cody at signal.org

@Moggel1 Your logs point a different picture and show potential database corruption which is concerning. I would encourage you to try creating a backup file in case things break further. We're looking into it.

**Comment by Moggel1** [comment]
Hello @cody-signal , oh my god, this doesn‘t sound good… corrupted database, how could this happen…
I hope that it‘s somehow possible to access the data…
Because now, it‘s also already no longer possible to access that 1:1 group we created :((
(we try to create a backup)

**Comment by Moggel1** [comment]
Please, @cody-signal, if you could provide me a perspective, it would be great.
- I assume that the Signal database on that affected phone is corrupted, and cannot be restored. The chats are lost. Right? Or do you think that a future update could fix it?
- If the data is lost on the phone, it is bad, but there's still the connected Signal desktop. Here my question: if I remove Signal from the phone (it's the primary device), and install it again, will it connect again to Signal deskop? I mean, will all the old chats still continue to exist there? It would be very tragic if the Signal desktop database is also lost, since it isn't possible to export the messages. I ask for advice how to proceed.

Thank you very much in advance.

**Comment by alex-signal** [comment]
@Moggel1 As long as you don't clear the data on the desktop instance, it should retain the messages, even if you re-link. I am 99.9% sure, because I've done so several times.

If your database has become corrupted, then there's unfortunately nothing we can do to restore it. You *can* get partial message recovery via a local backup if you had that feature enabled.

**Comment by Moggel1** [comment]
Thank you very much, @alex-signal . I'll try.
For me it was important to know that I don't have to wait for an update that might fix the broken database. 
I can go on with this. I close this issue. @Raychani1 please create a new issue for yours, as it seems to be different from my corrupted database issue.

**Comment by ttmx** [comment]
Hey! I'm having an issue that looks exactly the same as the repro video from this issue's OP. Sometimes the conversation manages to open but most of the time it does not and just stays blank, even though the last message preview seems available.
I can send the debug log over email, I would very much like to keep my chats.

Thx!
