### ISSUE TITLE
Received video: Unable to play media

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#13530]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Received a video in a groupchat but when trying to play it a toast message 'Unable to play media' pops up.

### Steps to reproduce
- See description

**Actual result:** Unable to play received video.
**Expected result:** Play received video.

### Device info

**Device:** Samsung S20 and S9
**Android version:** 13 and 11
**Signal version:** 7.5.0 and 7.4.2

### Link to debug log

https://debuglogs.org/android/7.5.0/bdfcd91023d85e6cf7ee4a3404e9725861b1a09bccfa4c9a49ffcfcc9c95b80f
https://debuglogs.org/android/7.4.2/55234e19060d929428b9266f2aec42270cf5edbfb1a40eba87716b4a04c575d4

**Comment by nicholas-signal** [comment]
Which one sent the video? Are you able to provide a messageID?

**Comment by bme13** [comment]
Long pressing the sent info in the message details gives 1713806691918.

**Comment by nicholas-signal** [comment]
It appears that the video you're trying to play is in a format that neither of your devices support. Are you able to download and play it in the Samsung Gallery app? If you're comfortable, it would help if you could submit the video to [support@signal.org](https://support.signal.org/hc/en-us/requests/new) and mention this GitHub issue (#13530), or simply upload it here.

**Comment by bme13** [comment]
I've tried to download it previously but it didn't show up in my gallery so thought that failed. That's why I couldn't provide a file type. Downloaded a different gallery app and now it is displayed. Turns out to be a wmv file. Still wasn't able to play but after installing vlc it played. I guess this is mainly related to my phone configuration than and I'm sorry for your time.

**Comment by nicholas-signal** [comment]
No worries! I'm just glad we uncovered the root cause.
