### ISSUE TITLE
Email Support System Incorrectly Judges Application Version

### ISSUE THREAD

**Issue by HugoCortell** [signalapp/Signal-Android#13533]
> If you are looking for support, please visit our support center:
> https://support.signal.org/
> or email support@signal.org

I tried that, and this issue has been created in response to that not working.

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The email support system rejects any support request I make, claiming that my app is out of date, in spite of the app being up-to-date, or as far up-to-date as the palystore will allow it to be. Here is that email:
![image](https://github.com/signalapp/Signal-Android/assets/59887727/0034010c-55a4-48ac-9e00-b90c9599a716)

I have tried through both the app (twice) and the website.
![image](https://github.com/signalapp/Signal-Android/assets/59887727/994f4327-ac23-49e8-a4a3-e0ca95864edb)

Here is a picture of the playstore page. Notice how there is no update button.
![image](https://github.com/signalapp/Signal-Android/assets/59887727/504c7e27-1668-405e-b07f-7bb7cf7a54fb)

Here is a picture of the playstore's "apps that have updates" page. Notice how signal is not there.
![image](https://github.com/signalapp/Signal-Android/assets/59887727/24c4fcb5-8549-405e-a2a4-4893df4cbe9a)

I don't know what is causing this, but it is a serious issue which prevents users from reaching out, and Signal from being notified of bugs. Hopefully the issue is exclusive to me and other bug reports aren't being sent back.

If you try to reply to the automated rejection email (usually with support emails of this kind, you can reply to the machine as a "I want to talk to a human any way, the provided documentation did not help), you are met with the following reply, which is greatly disheartening. 
![image](https://github.com/signalapp/Signal-Android/assets/59887727/0ccb1fd9-f75b-4873-8604-d96698c3e662)

### Steps to reproduce
- I don't know. I'm just an end user who wishes they could have reported this via email support.

**Comment by UserX404** [comment]
Please also add a debug log to the ticket do allow devs to cross-check version, flags etc.

**Comment by cody-signal** [comment]
I let our team know and they found the issue, you were getting incorrectly filtered. Thanks for letting us know so we can fix.
