### ISSUE TITLE
Signal crashes when trying to view replies on Signal Stories

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#13556]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal crashes when trying to view replies on Signal Stories.

### Steps to reproduce

- Add media to a Signal Story
- Receive a reply
- Tap to view replies

**Actual result:** Crash
**Expected result:** No crash

### Device info

**Device:** Google Pixel 7
**Android version:** GrapheneOS [2024050700](https://grapheneos.org/releases#2024050700)
**Signal version:** 7.6.2

### Link to debug log

https://debuglogs.org/android/7.6.2/585e1872abb871b8f5b5d3fd8da29bbc1fd25484bfffa547a9049a68da88795c

**Comment by alex-signal** [comment]
Fixed in 7.7.x which is currently in beta.

**Comment by Jaymay552** [comment]
What is this app for my roomate literally forces me to use it why and how tf did I even get to this webpage lol
