### ISSUE TITLE
Link to Instructions to verify Signal APK Signing Cert outdated

### ISSUE THREAD

**Issue by gabefair** [signalapp/Signal-Android#13553]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the APK download [site](https://signal.org/android/apk/) a link is provided to the documentation on how to verify the APK signing cert. 
This is the link: https://developer.android.com/studio/command-line/apksigner#usage-verify
It provides this command to use: `apksigner verify [options] app-name.apk`
However in issue #13270 it is reveled that additional parameters are needed to see hash to verify the download.
`apksigner verify --verbose --print-certs-pem --min-sdk-version 24 app-name.apk`

**Comment by gabefair** [comment]
This is a simple documentation fix.

**Comment by greyson-signal** [comment]
Hi there, the documentation has been updated
