### ISSUE TITLE
TextSecure keeps launching its unlock activity, interrupting other applications

### ISSUE THREAD

**Issue by darrikmazey** [signalapp/Signal-Android#1355]
I posted this to the whispersystems mailing list, and was directed here.

TextSecure keeps arbitrarily (not related to receiving any sms) launching it's unlock activity.  This will completely interrupt a running application.  Also, sometimes when I unlock my phone, the TextSecure unlock activity is showing, despite not having been active when I locked it.

I captured a debug log immediately after this happened. 

http://hastebin.com/qetemaveyi

Of note: I am running TextSecure 2.0.7 on Android 4.4.2 on a Samsung Galaxy Note3 on TMobile.

Hope this helps.  If there is anything I can do to help debug this issue further, please feel free to contact me.

Cheers,
Darrik

**Comment by gabrielbauman** [comment]
This is still happening. See #2239

**Comment by gabrielbauman** [comment]
Just happened again: https://gist.github.com/anonymous/0cff7221933d2134fc17

**Comment by gabrielbauman** [comment]
https://gist.github.com/anonymous/b5f68da0eff07af6261e
