### ISSUE TITLE
Username removed on its own

### ISSUE THREAD

**Issue by ikonyx** [signalapp/Signal-Android#13568]
- [x] I have searched open and closed issues for duplicates
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I set a username two months ago as soon as the usernames functionality rolled out in BETA. Recently after I opened the app, I noticed a popup box mentioning that there was something wrong with my username and that it was removed and now I can "set the same username or change it" (no screenshot available). My phone number privacy settings were also changed since the username got removed on its own.

### Device info

**Device:** Redmi Note 10 Pro
**Android version:** 13
**Signal version:** 7.7.1

### Link to debug log

https://debuglogs.org/android/7.7.1/c0024bcf717f2567a3894c70d465d2b01b470bda6fadef9cff8158cccafafbbf (I noticed the issue on May 18th)

**Comment by cody-signal** [comment]
Hi there, sorry for the delay. Did you happen to add/remove/update any linked devices like desktop around the time you lost the username?

**Comment by RameshBabu300997** [comment]
Hi, Can you please assign this issue to me

**Comment by ikonyx** [comment]
> Hi there, sorry for the delay. Did you happen to add/remove/update any linked devices like desktop around the time you lost the username?

Hi. Yes I linked my desktop.

**Comment by cody-signal** [comment]
Thanks @ikonyx for confirming. This was likely a desktop bug that I found while troubleshooting your report. It should be fixed for others going forward. Thank you for helping make Signal better.

**Comment by ikonyx** [comment]
You're most welcome @cody-signal

**Comment by biscober** [comment]
Ahh, so that's what happened to my username.  Back around May I setup a username and linked my desktop and then didn't use Signal for a couple weeks.  When I next opened the app, I had this error and couldn't get my name back - someone else had sniped it.  I thought I somehow got hacked.  Only managed to find this post now, which seems to explain how I lost my username - a bug.  I guess that's at least some closure for me.
