### ISSUE TITLE
Messages are in wrong order

### ISSUE THREAD

**Issue by iamjustmewhoia** [signalapp/Signal-Android#13563]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Messages are displayed in the wrong order. When my friend sent me message yesterday and I turn my phone off before recivin

### Steps to reproduce
- Friend sends message but has poor network and the message is not sent
- The date changes and you write
- Friend connects online and the message they sented yesterday is being sent along with message from them today
- 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The message that could not be send yesterday is being sent and the app says "Today" (I write) "Yesterday" (the message they could not send and "Today" (with the message they sented today.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The expected result would be that the message that was sent yesterday should be displayed under yesterday and not first day today yesterday today.

### Screenshots

![Screenshot_20240516-132603~3](https://github.com/signalapp/Signal-Android/assets/153007801/b8a129a6-010d-48ce-8425-b19aedb13f13)

### Device info

**Device:** Motorola Moto G20
**Android version:** 11
**Signal version:** 7.7.1

### Link to debug log
https://debuglogs.org/android/7.7.1/9dfd56c35be3e6aedfaacce64c3315e83f3d1e0a9fa89f3206c80a34bf8c8728

**Comment by nicholas-signal** [comment]
Unfortunately, under these conditions, this is the expected behavior.
