### ISSUE TITLE
Unable to Create new PIN/skip on new/old phone.

### ISSUE THREAD

**Issue by kernelphr34k** [signalapp/Signal-Android#13582]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to Create new PIN, login to existing signal with old phone or new phone.

### Steps to reproduce
- Open Signal
- Click on "Re-register Signal" button in any message, or the top banner
- Enter phone number used to sign up with, confirm number.
- Enter your PIN screen, choose skip PIN.
- Enter / verify phone number for additional verification
- Signal asks for my PIN again.

**Expected result:** 
- I get a prompt on my original phone to reset PIN, set PIN, SMS confirms it's me and I'm logged back in and can send and receive messages via Signal.

**Actual result:** 
- Signal asks for PIN again after SMS verification.

### Screenshots
![Screenshot_20240529_101534_Signal](https://github.com/signalapp/Signal-Android/assets/10677081/3760e384-17dd-4d7f-abd8-12c842439639)
![Screenshot_20240529_110127_Signal](https://github.com/signalapp/Signal-Android/assets/10677081/d9eb9d0f-a431-4ef8-95a3-5914798fac18)
![Screenshot_20240529_163450_Signal](https://github.com/signalapp/Signal-Android/assets/10677081/72961fec-6be2-434a-ad8e-3b26661b3f33)

### Additional Info:
- New phone is a Samsung S24 (Android 14, OneUI 6.1, all updates applied) 
- Old phone is the Samsung A51, detailed provided below.
- Unable to access signal or send messages on either phone due to PIN not being reset on either phone or not being able to skip.
- I still have access to Signal on my old phone, but it has the "Re-register banner" and button on the bottom of every chat.
- I've been trying for 2 days now to get this working, whereas WhatsApp just worked.
- Looking at your Signal PIN help doc "What if I forget my PIN" section. I do not see anything to create a new PIN on either device.
- - I don't know if I enabled "registration lock" but I more than likely had it disabled as I do not like the PIN feature. https://support.signal.org/hc/en-us/articles/360007059792-Signal-PIN#pin_forgot
- I'm sorry I have harassed 'support@signal.org' but I'm out of country and really need Signal to be working.
- I have a screen recording (ask, can send privately) from both phones of me doing the SMS verification, and then it auto populates the SMS numbers, then asks for PIN again. AFAIK, it should not be asking for the the PIN again as I just did the SMS verification.

### Device info
--- Support Info ---
Filter: Signal Android Support Request - Something's Not Working
Device info: samsung SM-A515F (a51nnxx)
Android version: 13 (A515FXXU8HWK1, TP1A.220624.014.A515FXXU8HWK1)
Signal version: 7.6.2
Signal package: org.thoughtcrime.securesms (doDiFGKPO1r)
Registration lock: true
Locale: en

### Link to debug log 

(this is from S24)
https://debuglogs.org/android/7.6.2/2bf964c8dca3b7751de040b826e055b7d20ea2f28c1f1540b444a0ec7181c6a2

(this is from A51)
https://debuglogs.org/android/7.6.2/b9444b304a91ff64af97064969ce1e39e81f5420480a82bf3a5186a7eecc4a7f

**Comment by kernelphr34k** [comment]
Hello,

I was able to get back into my signal app after waiting ~7 days. 

Steps I did to resolve:

- Opened Signal app and started the re-register process on the A51.
- Skipped the pin, did SMS confirmation.
- Set new pin, confirmed new pin. (Did not have this option previously)
- Conformation of SMS, asked for PIN again, skipped
- Signal is registered on A51 again.
- Removed SIM from A51, installed into S24
- Started transfer account process from A51 to S24
- Transfer completed successfully.

Notes/comments:

- I tried the only PINs I would have set, but did none worked.
- I believe I would have had the registration lock disabled. 
- I was always able to confirm SMS verification.
- The wait time of hours for an incorrect PIN, and a 7 day wait is egregious. The user should set the time period, or have other options.
- I understand security, but I have physical access to both phones and this was a mistake on my part not using the transfer account feature initially. In this use case, another option to backup/transfer to a new phone would be great.

**Comment by nicholas-signal** [comment]
As best I can tell, this is Registration Lock working as intended. I see registration lock is enabled in the screenshots. Registration lock prevents registration unless the correct PIN is provided within the first 10 guesses. Otherwise, the lock will expire after 7 days, at which point one can register with SMS again.
