### ISSUE TITLE
Videos sent to iOS phone do not play back

### ISSUE THREAD

**Issue by hebu** [signalapp/Signal-Android#13585]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using Signal on an Android phone. It maybe started around the beginning of 2024 that iOS users can not play back anymore the videos I sent to them. Usually, the app just does not react when trying to start the playback. One user reported, that the app simply disappeared. Another one reported that he could not even save the videos to the gallery and the file ending would be something cryptical instead of a proper video file format ending.

(I also reported this bug to the iOS repository as I do not know which side of the messaging chain is buggy: https://github.com/signalapp/Signal-iOS/issues/5816)

### Steps to reproduce
- Sender uses Signal 7.7.2 on Android 8.0.0 (Huawei P10 Lite)
- Recipients use Signal on iOS
- Sender either sends a message containing a video from the gallery, records a video in the app or sends a video in a story
- Recipient receives the video
- Recipient tries to play back the video

**Actual result:** Recpient's app does not react or disappears/closes.

**Expected result:** Recipient is able to play back the video.

### Device info

**Sender's device**: Huawei P10 Lite

**Sender's android version**: 8.0.0

**Sender's Signal version:** 7.7.2

**Recipients:** Various iOS devices and versions. Sorry that I did not ask everyone, but I might add this info later.

**Comment by hebu** [comment]
Hi there, I uploaded debug logs of both sides this evening:

Android: https://debuglogs.org/android/7.7.2/c876e9498b985b9b8b6b264eebf09347b174c2c2cf182768689b69d004781135

iOS: https://debuglogs.org/ios/7.11.0/c8b25ae9eb10e26005c05215b1a4a167b47edc5e2d7314249d5ec4d07dd14e70.zip

**Comment by nicholas-signal** [comment]
Are non-iOS clients able to play the videos? Would you be comfortable having one of the recipients upload the resulting video to our [Support Portal](https://support.signal.org/hc/en-us/requests/new) so I can see if the video file is malformed in some way? Thanks.

**Comment by hebu** [comment]
Yes, Android-clients are able to play the videos. How can the video be uploaded to the support portal on iOS? Long-pressing the video does not offer a "Save" option in the context-menu.

**Comment by hebu** [comment]
Here's an update: 
- The user who offered the debug logs told me today, he was now able to play my videos and all he did was updating to iOS 17.5.1
- I hoped this was the solution and asked others for their iOS version and they were also running 17.5.1 and still could *not* play my videos. 
- So I asked another user to provide a received video file as suggested by @nicholas-signal

**Comment by hebu** [comment]
Hi @nicholas-signal - the test recipient I asked to help uploaded the video to the support portal. He said, the video would'nt play when opened from the gallery. But if he saved the video via share -> Save to file, it would play. So he uploaded the one from the gallery.

Another user who could not play my videos on May 30th is now able to play my video. He is using iOS 17.5.1, he said he did not change anything on his phone. My Signal app was updated to 7.8.1 on June 6th on my Android phone. Sadly he did not tell me his Signal app version.

Still not sure, what causes the problem or helps to fix it. Does not seem to be the iOS update to 17.5.1 neither my Signal update to 7.8.1 as there still are users who cannot play my videos.

**Comment by hebu** [comment]
Hey @nicholas-signal – did you get the uploaded video file?

**Comment by hebu** [comment]
Meanwhile, every test person on iOS 17.5.1 reported to me, that they could play back videos again. There's only one tester on iOS 15.8.2 who's app is crashing on video playback.

So I'd consider this issue as done.
