### ISSUE TITLE
Links in Signal Stories buggy/no longer functional in current Android

### ISSUE THREAD

**Issue by mfuhrmann** [signalapp/Signal-Android#13589]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Spawned out of https://community.signalusers.org/t/links-in-signal-stories-buggy-no-longer-functional-in-current-android-version-7-7-2/

### Steps to reproduce

- create story with an URL link
- share it
- try to click the link in the story

**Actual result:** The link does not open. The story just closes.
**Expected result:** The link should get opened.

### Screenshots

Don't have some. But easy to reproduce.

### Device info

**Device:** Google Pixel 7 Pro, Pixel 8 Pro
**Android version:** 14
**Signal version:** 7.8.1, 7.7.2,

**Comment by greyson-signal** [comment]
I'm fairly confident this was resolved in an earlier version
