### ISSUE TITLE
Donation fiat only

### ISSUE THREAD

**Issue by schubba** [signalapp/Signal-Android#13586]
Signal Donation does not accept Crypto 
At Least MOB Coins should be accepted.

**Comment by Ashbeel111** [comment]
Can you share some more information related to this issue. So, we can guide you properly and also give you a better solution for future aspects. [educonnect normandie](https://educonnectnormandie.online/)

**Comment by cody-signal** [comment]
@schubba You can use crypto via our web donation portal: https://signal.org/donate/

The apps do not support it nor plan to at the moment, but thanks for the feedback.
