### ISSUE TITLE
Microphone in speakerphone mode unusable due to background noises on Pixel4a

### ISSUE THREAD

**Issue by tve** [signalapp/Signal-Android#13595]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

On a pixel4a when turning on speakerphone during a call the microphone picks up ambient noises like crazy and makes it very uncomfortable for the remote party. This started a couple of months ago (have used Signal for many years). Previously the speakerphone microphone was perfect and did not pick-up ambient noises (basically normal).

I am using CalyxOS (Android 14 AOSP-based) and have done some testing:
- regular phone calls (AOSP dialer) have the speakerphone microphone working perfectly: clear audio, no ambient sounds, etc.
- it also works fine with the last (Android 13) stock google image
- speakerphone microphone unusable in the last Android 13 CalyxOS build (dec '23 or jan '24, I'm not sure), same for an august '23 CalyxOS build (the speakerphone microphone feature worked fine at that time)
- exactly the same issue with the latest LineageOS 21.0
- I also reverted to the oldest version of Signal that currently still works (7.1.3) and the issue persists

### Steps to reproduce
- install clean OS
- install signal
- set-up signal account
- make signal call and test voice quality
- turn on speaker and have the other party report sound quality, they should hear a change where the voice becomes softer and ambient noises get picked up and amplified, for example computer fan or just about anything else
- hang up, make a regular phone call to the same party, turn on speaker and observe that it sounds great

**Actual result:** speakerphone microphone picks up and amplifies ambient noises driving other party crazy
**Expected result:** speakerphone microphone sounds normal and is usable

### Device info

**Device:** Google Pixel4a
**Android version:** 13 and 14
**Signal version:** 7.4.2 (tried back to 7.1.3, can't test previous ones as they won't connect to servers)

### Link to debug log
https://debuglogs.org/android/7.4.2/2259a6b61f4e6960b1deab5c253ff581b272077f4e1d8292ce47e91ee95467a3

**Comment by Ashbeel111** [comment]
To improve the microphone performance in speakerphone mode on a Pixel 4a and reduce background noise, follow these steps:

**1. Enable Noise Suppression:**
   - Go to **Settings > Sound > Advanced > Noise cancellation** and turn it on.

**2. Update Software:**
   - Ensure your device is running the latest software. Go to Settings > System > System update** to check for updates.

**3. Clear Microphone Area:**
   - Make sure the microphone openings are clean and unobstructed.

**4. Adjust Environment:**
   - Move to a quieter location to reduce background noise.

**5. Third-Party Apps:**
   - Use third-party noise-cancelling apps like Krisp [ent](https://educonnectnormandie.online/ent/) for better noise management during calls.

**6. Factory Reset (if other steps fail):**
   - Back up your data and perform a factory reset. Go to **Settings > System > Advanced > Reset options > Erase all data (factory reset).

These steps should help improve the microphone quality during speakerphone calls.

**Comment by tve** [comment]
Thanks for the suggestions. However, during regular phone calls the speakerphone mic works perfectly. This is a software issue, not a hardware or system configuration issue.

> **1. Enable Noise Suppression:**
> 
>     * Go to **Settings > Sound > Advanced > Noise cancellation** and turn it on.

This setting does not exist in AOSP-based builds as far as I can tell.

> **2. Update Software:**
> 
>     * Ensure your device is running the latest software. Go to Settings > System > System update** to check for updates.

I am running the latest version of  CalyxOS (may 2024), I also tried the latest version of LineageOS.

> **3. Clear Microphone Area:**
> 
>     * Make sure the microphone openings are clean and unobstructed.

I did that several times. Also, it works great during regular phone calls.

> **5. Third-Party Apps:**
> 
>     * Use third-party noise-cancelling apps like Krisp [ent](https://educonnectnormandie.online/ent/) for better noise management during calls.

I will try this app, but the problem is that somehow Signal does not use the microphone the same way that the AOSP dialer does, since the latter works great.

> **6. Factory Reset (if other steps fail):**
> 
>     * Back up your data and perform a factory reset. Go to **Settings > System > Advanced > Reset options > Erase all data (factory reset).

I did that several times and installed LineageOS as well to verify.

> These steps should help improve the microphone quality during speakerphone calls.

They don't. The speakerphone calls work great using the AOSP dialer during regular calls, but with Signal it's unusable.

**Comment by Ashbeel111** [comment]
need more help.[ytmp3](https://ytmp3.ing/)

**Comment by tifriis208** [comment]
Hi. For information, I got the same issue with my Pixel 3 with also CalyxOS. But I don't have this issue with my Pixel 4a (also with CalyxOS), last build. Let's hope we find the issue :)

**Comment by tve** [comment]
I can confirm that this issue is fixed! yay& thanks!
details: the pixel 4a i reported the issue for sadly died but i had the exact same issue with the 8a that replaced it. with the recent upgrade it now works as expected, i.e. no more pick up of background noise.

**Comment by jim-signal** [comment]
@tifriis208 Sorry to hear about your Pixel 3, I hope you can eventually recover it.
