### ISSUE TITLE
repeaded crashing "my story does not exist"

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#13602]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
after reinstalling the app and resorting from backup file the app now keeps crashing.

### Device info

**Device:** Motorola Moto G7plus
**Android version:** 10
**Signal version:** 7.9.6

### Link to debug log

https://debuglogs.org/android/7.9.6/626b96168ecf1ee8ae1a3894c2b8de82748623bf921c128fdaa96e6e930de03f

**Comment by nicholas-signal** [comment]
Does this crash still occur?

**Comment by Meteor0id** [comment]
Nope, turns out I had tested a backup which had been modified with a thrid party tool. I mixed them up and thought for a moment thus was a Signal bug. Nothing here, closing.
