### ISSUE TITLE
Group Connection Error

### ISSUE THREAD

**Issue by kapalko** [signalapp/Signal-Android#13604]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some groups on the app have kicked me out, with the "You are no longer in the group." message. However, my friends can still see me in the group settings as an active member. I am still a part of the group and can receive messages on the MacOS desktop version as well.

This did not happen to all of my groups, only a subset. The three other members in one of these groups are all iOS users, I am the only Android. I cannot determine if other Android users are affected in other groups.

### Steps to reproduce
- open Signal
- select group
- realize you've been removed

### Screenshots
![image](https://github.com/signalapp/Signal-Android/assets/11836366/69e39be3-9bbe-4f24-8e73-b4456497cc80)
Here is what I see in the group including me trying to send a message.

![image](https://github.com/signalapp/Signal-Android/assets/11836366/4399fd18-e7c1-4a2c-ac2a-b8469e771058)
Group settings on Android

![image](https://github.com/signalapp/Signal-Android/assets/11836366/37b805f6-9354-415d-9acb-d31224213003)
Behavior is normal on the desktop app

![image](https://github.com/signalapp/Signal-Android/assets/11836366/d08b279f-0aed-4acf-a226-5afb8ce6377a)
Group settings on desktop also confirm

### Device info
**Device:** Google Pixel 7
**Android version:** 14
**Signal version:** 7.10.0

### Link to debug log
https://debuglogs.org/android/7.10.0/14444352adf6cc85b31a16850a6e0c92b1829dd56e6e7690fcc1e795cb1432de

**Comment by nicholas-signal** [comment]
This is a bug in the beta version, 7.10.0. It is fixed in a66857a7ccbc12e0c1a7f734e65f7d3d704c73fb

**Comment by kapalko** [comment]
Thanks @nicholas-signal. I've updated to 7.10.1 but the database still resolves as having left the groups. Should I reinstall completely?

**Comment by nicholas-signal** [comment]
You may need one of the remaining group members to add you back into the group.

**Comment by kapalko** [comment]
@nicholas-signal we tried that but they cannot as their devices registered me as still being in the group. Workaround is to have someone remove me and re-add to the group. 

All set now, thanks!

**Comment by cody-signal** [comment]
For anyone that finds this later, any group state change will fix this. For example, changing the group title will resolve the local db state.
