### ISSUE TITLE
Removed from group after failed image upload

### ISSUE THREAD

**Issue by leo-unglaub** [signalapp/Signal-Android#13606]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am in a group that existed for a very long time. It contains 7 members. Last night i was on a train with a weak mobile data connection and i posted a picture into the group. Because the mobile internet connection broke for around 2 minutes the pic did not upload completly, it got stuck and signal was trying to re-send it automatically. Right after the upload worked, i got automatically removed from that goup, but only on the mobile device. On the connected desktop client i am still able to chat with the group. 

My first thought is, that for some reason the app trying to re-upload the image multiple times somehow triggered some anti-flooding/antispam routines that removed that client? But thats just a guess at this point, i did not look at the code.

### Steps to reproduce
Unable to reproduce

### Screenshots
![image](https://github.com/signalapp/Signal-Android/assets/734684/84b8bbd5-672f-4b57-a86f-4ebafa27c50f)

### Device info
**Device:** Fairphone 5
**Android version:** 13
**Signal version:** 7.10.0

### Link to debug log
https://debuglogs.org/android/7.10.0/bf4fa4c8d836392c765f2bf9b1d8520f923e258b7b336ec83b1ac0c0f4b1c649

**Comment by nicholas-signal** [comment]
This is a bug in the beta version, 7.10.0. It is fixed in https://github.com/signalapp/Signal-Android/commit/a66857a7ccbc12e0c1a7f734e65f7d3d704c73fb

After upgrading to 7.10.1, you may need another remaining group member to remove and re-add you to the group.

**Comment by cody-signal** [comment]
To elaborate on Nicholas' comment for anyone that finds this in the future: Any group state change made by you or someone else will resolve this after updating to 7.10.1. For example, changing the title/description, changing disappearing messages, etc.

**Comment by leo-unglaub** [comment]
Thank you so much for fixing this! I can confirm that it works after upgrading to `7.10.1`. Igot re-added to the group and its fine again. Big thanks :)
