### ISSUE TITLE
Android PIN Screen Only Allows Numeric PINs (Again?)

### ISSUE THREAD

**Issue by thegranddesign** [signalapp/Signal-Android#13605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have searched the issue tracker for this and, despite numerous issues stating that this was an issue, the issue was closed with some people stating it was "fixed".  I'm not certain if there is some other PIN screen somewhere that was fixed, but on my device with the latest Signal, this is happening.

### Steps to reproduce

1. Generate an alphanumeric PIN of 60 characters
2. Go to Settings -> Account -> Change Your PIN
3. Tap "Create alphanumeric PIN"
4. Paste the new PIN into the field
5. Confirm by re-pasting in the confirmation field
6. Go to Settings -> Privacy -> Screen Lock
7. Toggle the switch to "on"
8. Go to Android settings and force quit Signal
9. Re-open Signal and get presented with the option to use your fingerprint
10. Instead of using fingerprint, tap "Use PIN" in the lower left

**Actual result:**

The PIN entry screen is of the "numeric" variety only.  The keypad only contains digits.

**Expected result:**

Either the app should know that I have an alphanumeric PIN and default to a standard keyboard (preferable) or a similar "Use alphanumeric PIN" text should be shown to switch the PIN type (like what happens on the "Create a PIN" screen.

Also, if it matters, the alphanumeric PIN field should allow pasting and not lose state if the app is switched away from and then back to.

### Screenshots

N/A

### Device info

**Device:** N/A
**Android version:** 14.x
**Signal version:** 7.9.6

### Link to debug log

N/A

**Comment by nicholas-signal** [comment]
The Screen Lock feature relies on the operating system-provided [biometric authentication dialog](https://developer.android.com/identity/sign-in/biometric-auth). As part of the operating system, the biometric authentication dialog uses the device's system PIN, rather than the Signal PIN. You may validate this yourself by changing your device's screen lock to a pattern and repeating these steps.

**Comment by darshanbidkar** [comment]
> The Screen Lock feature relies on the operating system-provided [biometric authentication dialog](https://developer.android.com/identity/sign-in/biometric-auth). As part of the operating system, the biometric authentication dialog uses the device's system PIN, rather than the Signal PIN. You may validate this yourself by changing your device's screen lock to a pattern and repeating these steps.

+1, we can close this issue.

**Comment by thegranddesign** [comment]
You're kidding. That is absolutely unclear. I think that the text should be changed to "Use Device PIN" instead.

**Comment by thegranddesign** [comment]
It's unclear that I was switching from a Signal dialog to a system dialog. Apologies.
