### ISSUE TITLE
[Bug] Chat Backup can't detect the system file manager

### ISSUE THREAD

**Issue by ZakMorphas** [signalapp/Signal-Android#13611]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app depends on a specific file picker and it's a problem. App Name: "Files", Package Name: "com.google.android.documentsui". I've removed some of my phone's bloatware using Universal Android Debloater yesterday. Google Files was one of them. Today I was trying to backup my chat manually, then it gave me an error saying: "No file picker available". After I restored Google Files, it started working again. But I already have 2 other File Managers, Fossify File Manager & Material Files. The app detected none.

### Steps to reproduce
- Uninstall com.google.android.documentsui.
- Go to App Settings > Chats > Chat Backups > Choose a Folder

**Actual result:** Error: No file picker available
**Expected result:** Open the available File Manager (in my case, Fossify File Manager/ Material Files)

### Screenshots
![Signal_Error](https://github.com/signalapp/Signal-Android/assets/117139065/aed17b18-3f20-477b-9407-9fe9f454e216)

### Device info
**Device:** Realme C25s, Model: RMX3195
**Android version:** 13, Realme UI 4.0
**Signal version:** 7.9.6

**Comment by jebbgrenham** [comment]
Similar issues - on android 9. The backup folder location is just non-selectable but must be related.

**Comment by greyson-signal** [comment]
We're doing a pretty standard request for [Intent#ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE). My guess is that whatever file picker you have installed doesn't support it.
