### ISSUE TITLE
The recipient of "view only once" aka. one time media can take screenshots of it and record it

### ISSUE THREAD

**Issue by Uneccessary** [signalapp/Signal-Android#13610]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When somebody send a one-time image or video, the recipients can take a screenshot of it.

### Steps to reproduce
- Some person send you a picture or video which can be only viewed once
- Open the picture or video
- Take a screenshot of it

**Actual result:** You can screenshot the picture / video when it's beeing send as a one-time-media and screen protection is disabled
**Expected result:** You shouldn't be able to screenshot such media for security and privacy reasons, also WhatsApp and other messengers does block this.

### Device info

**Device:** Samsung Galaxy A33 5G
**Android version:** Android 14
**Signal version:** 7.10.3

**Comment by greyson-signal** [comment]
It was an explicit decision to not block screenshots. The idea is that it provides a false sense of security, and not only can different android OS's override our request to make it unscreenshottable, but users could also just take a picture with another phone.

**Comment by Uneccessary** [comment]
I still think some security measures, are still better than none because of "the user could get a false sense of security". Pretty much every- and anything about Signal could do that, even the fact that it advertises itself as an private and secure messenger.

Still, thank you for your reply. I will take this then to the feature suggestions.
