### ISSUE TITLE
Verification code not handling error message properly

### ISSUE THREAD

**Issue by Fison01** [signalapp/Signal-Android#13623]
### Bug description
During account registration(phone number registration), user not be get the following error as it was implemented on old versions

### Steps to reproduce
- Uninstall signal if it was already installed
-  When you reach to Verification code screen
- Enter wrong code: no error message show up

**Actual result:** No thing happen
**Expected result:** should see error message popup

### Device info
**Device:** Pixel 6
**Android version:** 14
**Signal version:** 7.11.3

**Comment by jklawiter** [comment]
I have no idea if it is related issue but also:

- There is no information about SMS lock time
- Something is cancelling/killing process while checking for the SMS code, and it is not working than so even if you have correct code it's not processed, and time counter to „get another code” does not appear.

I'm trying to reregister my account after factory reset 2 days ago it was working with older versions now it's not. :(

**Comment by StarGazer202424** [comment]
I have a Samsnung Flip 6.  Either I just don't get sent the code or I get like 1 code. For instance, if I request a verification code  I will get it within a few seconds of requesting, but if I request another one nothing happens unless I wait like 30 minutes.

Even when I get the code and type the 6 digits into the box it will just spin for a few seconds and nothing happens. 

I then have to wait to till the 1 minute countdown happens to try to resend the code by text or to call. If I hit these buttons nothing happens.

**Comment by jklawiter** [comment]
> I then have to wait to till the 1 minute countdown happens to try to resend the code by text or to call. If I hit these buttons nothing happens.
Upgrade to testing version 7.12!

**Comment by jklawiter** [comment]
> I just went to the google play store to download it how do I upgrade to testing version 7.12?

You have to apply to beta test program, and than wait few minutes.
Maybe it is not important but after upgrade I've wiped all memory storage of Signal, and than registered my number without any troubles.

**Comment by StarGazer202424** [comment]
> > I just went to the google play store to download it how do I upgrade to testing version 7.12?
> 
> You have to apply to beta test program, and than wait few minutes. Maybe it is not important but after upgrade I've wiped all memory storage of Signal, and than registered my number without any troubles.

Okay I signed up for the beta. It told me I had too many attempts so I had to wait an hour. Now when I request I get

"Unable to connect to service. Please check network connection and try again"

I am connected to wifi and that is all working great.

**Comment by StarGazer202424** [comment]
Okay now suddenly it worked. It even added my backup (though it did not ask me to put my passphrase in)

**Comment by ms2245-eng** [comment]
Trying to reinstall... gets to the confirm phone number page, but never sends an SMS. Is this a 7.11.3 thing as well?
Worked fine a few days ago before I deleted it

**Comment by StarGazer202424** [comment]
> Trying to reinstall... gets to the confirm phone number page, but never sends an SMS. Is this a 7.11.3 thing as well? Worked fine a few days ago before I deleted it. Are there issues with the verification?

No clue the weird thing is my wife did it on the exact same phone and she had no problem. She did it like an hour after I first tried.

**Comment by ms2245-eng** [comment]
> > Trying to reinstall... gets to the confirm phone number page, but never sends an SMS. Is this a 7.11.3 thing as well? Worked fine a few days ago before I deleted it. Are there issues with the verification?
> 
> No clue the weird thing is my wife did it on the exact same phone and she had no problem. She did it like an hour after I first tried.

Did you solve this by going to the beta 7.12?

**Comment by greyson-signal** [comment]
Resolved in 7.11.4 + 7.12.0

**Comment by Fison01** [comment]
@greyson-signal can 7.12.0 version work with server version v12.36.0( released 3 months ago)?
