### ISSUE TITLE
https://signal.org/android/apk/ gives fingerprint for public key instead of signing certificate (1024-bit)

### ISSUE THREAD

**Issue by sandwm** [signalapp/Signal-Android#13625]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On https://signal.org/android/apk/, a note regarding older apksigner versions and the 1024-bit key certificate was recently added. (See also #13617.) However, while it says to give the "SHA-256 fingerprint for the 1024-bit **signing certificate**", it gives the fingerprint of the public key, beginning with "75:33:...". (Both are output by `apksigner verify ...`.)

The main text above the note correctly gives the "SHA-256 fingerprint for the 4096-bit signing certificate".

### Steps to reproduce
- go to https://signal.org/android/apk/
- read the text beginning with "Note:"
- run the apksigner command given on the page: `apksigner verify -v --print-certs --min-sdk-version 24 Signal*.apk`
- compare apksigner output and the fingerprints given on the web page

**Actual result:** The note gives the public key fingerprint.
**Expected result:** The note should give the certificate fingerprint.

### apksigner verify output
SHA-256 related output from `/opt/android-sdk/build-tools/34.0.0/apksigner verify -v --print-certs --min-sdk-version 24 Signal*.apk`:

```
Signer (minSdkVersion=33, maxSdkVersion=2147483647) certificate SHA-256 digest: 4be4f6cd5be844083e900279dc822af65a547fecc26aba7ff1f5203a45518cd8
Signer (minSdkVersion=33, maxSdkVersion=2147483647) public key SHA-256 digest: 40763a247a68565e9950825c9ddac73ddcccd34f63c4b65759b66cb6d2844b43
Signer (minSdkVersion=24, maxSdkVersion=32) certificate SHA-256 digest: 29f34e5f27f211b424bc5bf9d67162c0eafba2da35af35c16416fc446276ba26
Signer (minSdkVersion=24, maxSdkVersion=32) public key SHA-256 digest: 75336a3cc9edb64202cd77cd4caa6396a9b5fc3c78c58660313c7098ea248a55
```

### Device info

**Signal version:** 7.11.3

**Comment by greyson-signal** [comment]
This was fixed a couple days ago, thanks!
