### ISSUE TITLE
Reaction Emoji-bar is misplaced sometimes.

### ISSUE THREAD

**Issue by vdTwer** [signalapp/Signal-Android#13633]
# Reproduce
- Open a normal- or groupchat.
- Tap and hold a message, containing an image or reply to another message (I think that the actual key factor is the height of the message, but since I don't have text-messages that long, I only noticed it on images)
- The bar, displaying the emojis you can use to react is misaligned. 

(Tested on Google Pixel 8 Pro, Android 14-11, Signal Version 7.11.4)

# Example
![image](https://github.com/user-attachments/assets/ed842323-5cc7-4722-8832-86971b16683e)

**Comment by alex-signal** [comment]
hi! how much space is available above the message? I believe we use some rules around how much space is above the message and below the bottom of the action bar to determine how to place the reactions scrubber. I understand it's not ideal but it helps ensure it's always visible and useable.

**Comment by alex-signal** [comment]
Thanks a lot for the detailed images! I'll make sure this is tracked and see if design has opinions here.

**Comment by greyson-signal** [comment]
I think this is working as intended. One of our heuristics is that we don't want the reaction bar to appear too far from your finger, and I think that's the limit you're running into.
