### ISSUE TITLE
System theme changes not reflected in chats without screen reload

### ISSUE THREAD

**Issue by neunzehnachtneun** [signalapp/Signal-Android#13654]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a UI glitch introduced in 7.12.3 showing up in chats. The change of the dark mode switch is not recognized anymore in group and single chats, while it seems working in overview and settings.

### Steps to reproduce
- Set Signal theme to the "System default"
- Open a chat
- Go to Android's settings and switch the theme to dark mode
- Back to Signal and see if the chat screen updates to match

**Actual result:** Chat view stays light.
**Expected result:** Chat view should change to dark mode

### Device info

**Device:** Pixel 6a
**Android version:** 14
**Signal version:** 7.12.3 + 7.13.4

### Link to debug log

https://debuglogs.org/android/7.12.3/f7cecbcc452a408a0afd39c7ba96bff7b4f67f95f56cec986ca4011d9f4e056f

**Comment by henkkasoft** [comment]
I changed to new Android device and experienced something similar.

I had dark mode in my previous device's Signal application. I used **set up my device** solution to get all my data and installed apps to new device.
Signal had the dark mode set by default but it did not take effect until I switch it to light mode and then back to dark mode.
My new phone settings does not have dark mode set, only Signal app have.

Environment:
Device: moto g84 5G
Android version: 14
Signal version: 7.14.2

**Comment by neunzehnachtneun** [comment]
The issue continues to occur. Using version 7.17.4.

**Comment by neunzehnachtneun** [comment]
Unfortunenately still present under 7.21.5 using Android 15.

**Comment by neunzehnachtneun** [comment]
Thanks for solving, devs!
