### ISSUE TITLE
Android startup crash, sql error `no such table: message_fts`

### ISSUE THREAD

**Issue by antonpiatek** [signalapp/Signal-Android#13659]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android crash on startup

### Steps to reproduce
- Launch app after automatic update today at 02:00

**Actual result:** App briefly shows chat list, then crashes
**Expected result:** App opens normally

### Device info
**Device:** Huawei P30Pro
**Android version:** 12.0.0.219 emui?
**Signal version:** 7.14.1

### Link to debug log
Signal logs unavailable as app crashes within the second. Android log: [adb.log](https://github.com/user-attachments/files/16696346/adb.log)

One part jumps out, assuming this isn't a caught exception and handled in the app elsewhere:

```
08-21 19:05:46.986 11762 11864 E SignalUncaughtException: org.thoughtcrime.securesms.migrations.MigrationJob$FailedMigrationError: android.database.sqlite.SQLiteException: FullCode: 1 | ErrorCode: 1 | ExtendedErrorCode: 0 | Message: no such table: message_fts | ExtraMessage: , while compiling: INSERT INTO message_fts (rowid, body) 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:             SELECT 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:               _id, 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:               body
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:             FROM 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:               message 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:             WHERE 
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:               _id >= 1 AND
08-21 19:05:46.986 11762 11864 E SignalUncaughtException:               _id < 10001
```

**Comment by mtang-signal** [comment]
Thanks for reporting and providing the log, we're actively looking it and should hopefully have something soon.

**Comment by nicholas-signal** [comment]
Signal v7.15.4 is now available on Google Play as well as [our website](https://signal.org/android/apk/). Please let us know if the crash is resolved.

**Comment by antonpiatek** [comment]
Thanks, I had reinstalled the app a while ago.
