### ISSUE TITLE
Signal Call Audio (mic) cuts out when Signal is in the background/viewing other apps

### ISSUE THREAD

**Issue by ChanoSan** [signalapp/Signal-Android#13656]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When making a Signal audio call, the microphone stops working both when viewing other apps (i.e. when Signal is running in the background) and when the screen is off. This only affects microphone (sending audio), and speakers (receiving audio) continue to function as expected. Bringing Signal back into the foreground, with the screen on restores microphone functionality. Additionally, enabling Picture-in-Picture mode with the call screen hovering over other apps allows the microphone to work normally.

Essentially, in order for a Signal call to work as expected, Signal must always be in the foreground and the screen must always be on, or Picture-in-Picture mode must be enabled. Tabbing into other apps without Picture-in-Picture or turning off the screen disrupts this.

### Steps to reproduce
- Make a Signal audio call
- Switch to other app / Turn off the screen during the call (without Picture-in-Picture)

**Actual result:** Microphone stops sending audio
**Expected result:** Microphone should continue to function with others apps in foreground, or with screen off.

### Device info

**Device:** Motorola Moto G Pure (XT2163DL)
**Android version:** 12 (Build No. S3RHS32.20-42-13-3-12-4)
**Signal version:** 7.14.1

### Link to debug log

[signal-log-1724208290714.zip](https://github.com/user-attachments/files/16685427/signal-log-1724208290714.zip)

**Comment by ChanoSan** [comment]
Updated Signal on the device to 7.14.2, the same issue still persists.

**Comment by ellisonch** [comment]
I'm affected by this as well.  It is a serious problem, as it basically means I can no longer use signal to talk to people while I walk around.

I use a Moto G Power 2022, with Android 12.  My Android build is S3RQS32.20-42-10-12-5-7, and my Signal version is 7.14.1.

**Comment by SJP58** [comment]
This is happening to me, too.
Device: Galaxy S20 FE 5G
Model: SM-G781W
One UI version: 5.1
Android version: 13
Build: TP1A.220624.014.G781WVLSFHXF1
My Signal version: 7.14.2

**Comment by kbarylyuk** [comment]
Same here: when I lock my phone during voice calls the person on the other end no longer hears me after a few seconds, but I can hear them. 
Device: Samsung Galaxy S20FE 5G
Model: SM-G781B/DS
OneUI v5.1
Android v13
Build: TP1A.220624.014.G781BXXSDHXH1
Signal v7.14.2

**Comment by ChanoSan** [comment]
> i check in redmi note 8
> Android 11
> i cant reproduce this problem

Every affected device so far appears to be:
- Android 12 or higher
- either a Motorola or Samsung device

**Comment by umesh8412** [comment]
**either a Motorola or Samsung device**
 Is You are using a physical device? 

Is there any way to reproduce that problem in emulator as installing the same hardware as mention? 

I check in internet it just show you can get skin of that samsung mobile but the hardware still be android os

Anyhow to reproduce in emulator?

**Comment by ChanoSan** [comment]
> Is You are using a physical device?
> 
> Is there any way to reproduce that problem in emulator as installing the same hardware as mention?

I am an end-user, so I'm reporting an issue with the physical device I'm using, as are the other users reporting in this issue. 

I have no experience with Android emulators so I have no idea how to test anything with them. All I can do is recognize patterns: Every report so far is Android 12 or higher and using Motorola or Samsung hardware, probably on vendor version Android builds.

**Comment by Fisshy86** [comment]
I'm having the same issue;

Phone info:
Make: OnePlus 8 Pro
Model: IN2023
Android version: 13

Signal info:
Currently running on version 7.15.4,   but I did an update to it to see if it solved my issue and it didn't. I don't know what version I was on before


I have localized it to be Signal, as I've tried other apps and they keep microphone "on" while screen is locked.  I've only tried it with locked screen

**Comment by nicholas-signal** [comment]
Hello everyone,

A fix for this issue should be rolling out now, and should reach everyone within the day.
