### ISSUE TITLE
Blocking a user still allows the user to see profile pic and new name

### ISSUE THREAD

**Issue by Jienniers** [signalapp/Signal-Android#13651]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Blocking a user still allows the blocked user to see my new profile pic and my new name, Please fix this I don't want the blocked user to see what profile pics i'm adding or what name i'm changing to. or make it so that it shows a random profile pic to them after you block them like in whatsapp, and for the name make it like "Signal User" or make the name same as when you blocked them even after you change it.

### Steps to reproduce
- Block the user
- Change Name/Profile pic
- See from other user account

**Actual result:** The blocked user is still able to see my new profile pic and new name
**Expected result:** The blocked user shouldn't be able to see what Profile pic i change to, or what name I change to

### Device info

**Device:** Huawei
**Android version:** 10
**Signal version:** v7.14.1

**Comment by cody-signal** [comment]
Thanks for this report, we'll look into it right away. In the meantime, do you know if you are in any groups with the blocked person?

**Comment by Jienniers** [comment]
> Thanks for this report, we'll look into it right away. In the meantime, do you know if you are in any groups with the blocked person?

Oh yeah, i'm in a group with them

**Comment by Jienniers** [comment]
But even if the person is in the group he shouldn't be able to see the profile change

**Comment by cody-signal** [comment]
> Oh yeah, i'm in a group with them

That is how they are learning of your changes. Unfortunately, with how groups currently work, anyone you share a group with will learn about your profile changes. In a perfect world, this wouldn't be the case, but it is how Signal Groups work today. The recommendation would be to leave or block the group if possible.

In response to your questions though, we did update our [documentation](https://support.signal.org/hc/articles/360007060072-Block-numbers-usernames-or-groups) to more explicitly state this to help others in the future.

**Comment by Jienniers** [comment]
> > Oh yeah, i'm in a group with them
> 
> That is how they are learning of your changes. Unfortunately, with how groups currently work, anyone you share a group with will learn about your profile changes. In a perfect world, this wouldn't be the case, but it is how Signal Groups work today. The recommendation would be to leave or block the group if possible.
> 
> In response to your questions though, we did update our [documentation](https://support.signal.org/hc/articles/360007060072-Block-numbers-usernames-or-groups) to more explicitly state this to help others in the future.

Okay
