### ISSUE TITLE
Signal Android App recently broken? Couldn't send/receive messages.

### ISSUE THREAD

**Issue by wischi-chr** [signalapp/Signal-Android#13669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
About 1-2 days ago my Android app stopped receiving messages. It still worked fine on a linked Desktop PC (could receive and send messages there - but they never showed up on android). First I thought it's a my issue but after contacting some people (via phone calls or RCS) they told me that Signal also stopped working for them. My guess is that the impact - at least with my contacts it's probably a bit more than 50% I asked.

### Steps to reproduce
No idea - it just stopped working roughly 30h ago.
There are often notifications with "you may have new messages" but there never are any. My guess is that the app actually gets the message but fails to decrypt it?

### Device info
Currently Android Beta (joined after it stopped working) not sure about the contacts but android could be the common denominator.

### Workaround
Some contacts reinstalled Signal (without Backup) and it started working again. I just made a local backup, uninstalled and reinstalled the android app - restored from backup and it looks like it works again - at least with other contacts that also reinstalled Signal.

It would be great if this issue could somehow be fixed without me calling hundred people and explaining to them how to backup, reinstall and restore Signal.

**Comment by wischi-chr** [comment]
Also of that somehow matters (because nobody on Twitter or down detector seems to complain) most of my contacts with issues are from Austria, some of them from Germany.

**Comment by wischi-chr** [comment]
_(sorry pressed the wrong button on mobile)_

**Comment by wischi-chr** [comment]
What I also just noticed. A lot of people that "broke" seem to have signal installed for years. Maybe there was something on the local database that got migrated and migrated and recently broke?

**Comment by mtang-signal** [comment]
Hi, would you be able to submit a debug log to help us look into this (Settings > Help > Debug log)?

**Comment by wischi-chr** [comment]
Sadly that was a bit stupid of me, because I only focused on fixing the people around me (we mainly communicate via Signal) and the fix involved reinstalling, so the setups (I know of) that had that bug, are gone. I now know that the "impact" was far lower than I initial thought, because it seems to have only impacted family and close friends.

My current guess is, that it had nothing to do with the migrations, but that some message in a group Chat messed up all members of that chat (except one contact - maybe that persons app sent some malformed message?). All people I later contacted who are not part of that group chat were not effected.

So it looks like this issue is certainly low priority and if we fail to reproduce it we can close that issue.
