### ISSUE TITLE
Signal 7.14.2 Crashing Upon Startup

### ISSUE THREAD

**Issue by kaswarh** [signalapp/Signal-Android#13662]
- [+] I have searched open and closed issues for duplicates
- [+] I am submitting a bug report for existing functionality that does not work as intended
- [+] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [+] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Signal app crashes immediately upon startup and disappears from view. This began happening after being auto updated to 7.14.2 today.

### Steps to reproduce
- Open the Signal app

**Actual result:** The app disappears from view without any error info. Or show Android window: "Signal app crashed again. Close."
**Expected result:** The app should remain visible and continue to function

### Screenshots and Video
![Снимок экрана от 2024-08-22 21-59-57](https://github.com/user-attachments/assets/ccfa1bb9-1e70-4876-9dab-9dd527c89c65)

https://github.com/user-attachments/assets/c0580e82-abec-4dc2-9c43-48e772c32475

### Device info

**Device:** Google Pixel 7 Pro
**Android version:** 14, Security Update 05-08-2024
**Signal version:** 7.14.2

### Link to debug log

I can't give logs because the application doesn't open

addition to the above: **after** reinstallation the application **works successfully,** but after some time (**from 1 to 2 hours**) it stops working again. This problem is observed only on **Android 14**. On Android **12** and **13** - there is **no** problem.

**Comment by mtang-signal** [comment]
This is likely the same bug as 7.14.1 that we're still trying to fix. There are some [other ways to get logs](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#advanced-capturing) if you are able to provide them.

**Comment by LexaChe** [comment]
The same problem (((

**Comment by ktau221** [comment]
Remedy: long press "Signal" icon and select "group messag" to open the app. :(

**Comment by kaswarh** [comment]
The problem started after transferring data to another phone. Developers: you can reproduce the error like this: transfer data from Android 12 to Android 14 and try working on Android 14.

**Comment by ShymkoGleb** [comment]
Same problem. And the same way to reproduce. After transfering from iPhone to new Nothing Phone (2a). Signal works less then two days and crash with same message. After reinstalling it work again around two days. Trying to reset pin code. But nothing is help.

**Comment by kaswarh** [comment]
Update to Beta 7.15.4 via Google Play solves the problem

**Comment by ckraasch** [comment]
Hello all, I have the same problem since a few days and have been following all the relevant issues. 

Unfortunately, installing the beta version mentioned above did not solve the problem for me.

**Comment by nicholas-signal** [comment]
Signal v7.15.4 is now available on Google Play as well as [our website](https://signal.org/android/apk/). Please let us know if the crash is resolved.

**Comment by ktau221** [comment]
> Signal v7.15.4 is now available on Google Play as well as [our website](https://signal.org/android/apk/). Please let us know if the crash is resolved.

😔 Not solved 😔

**Comment by nicholas-signal** [comment]
@ktau221 are you able to get ADB logs so we can see what's happening for your device 7.15.4?

**Comment by ktau221** [comment]
> @ktau221 are you able to get ADB logs so we can see what's happening for your device 7.15.4?
sorry, i can't get ADB, and i deleted all msg on Signal (without backup) :(,
it's a few time crashing, and it's become stable on 7.15.4...

that's two hints i hope can help,
1) remedy, long press and select group message, then , signal will not crashing
2) after few crashing, it's become stable.. it's related to some files are updated by timing?

**Comment by nicholas-signal** [comment]
> it's become stable.. it's related to some files are updated by timing?

That's great to hear! If you could still upload a debug log, it would still be very helpful!

**Comment by ktau221** [comment]
> > it's become stable.. it's related to some files are updated by timing?
> 
> That's great to hear! If you could still upload a debug log, it would still be very helpful!

https://debuglogs.org/android/7.15.4/da9503699f9060ac6b927a03f0b41617fa0443e1c12cc79982efd22effc3b0f7

**Comment by wiregrasscoder** [comment]
I'm have this problem on 7.16.4, Android 14, Samsung S21, app downloaded from Play Store, backup file is around 18GB. The app crashes between 1-3 seconds and I cannot get logs, unfortunately. Is there a way to get logs when the app crashes immediately? I'm willing to help troubleshoot this any way I can.

**Comment by jalso** [comment]
I'm also have this problem on 7.16.5, Android 13, Samsung S20FE. The app crashes between 1-3 sec after start.

**Comment by greyson-signal** [comment]
Hi there, please update to 7.17.4. It's currently rolling out to production, or you can download it from [our website](https://signal.org/android/apk)
