### ISSUE TITLE
 Uploading several videos to Stories consumes all available storage space

### ISSUE THREAD

**Issue by kaosmaja** [signalapp/Signal-Android#13667]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Uploading several minute-long videos stored on an SD card at once onto Stories freezes the application and hogs all primary storage space until system restart.

### Steps to reproduce
- Have 2 GB storage left on primary device
- Saved on an SD card, have some pictures and several minute-long videos you want uploaded in the same story update
- Try to upload all of these in one update (without splitting the videos up first, this will make Signal attempt to split the videos and take even more space from the primary drive)

**Actual result:** A picture or two might get uploaded, but the upload process ends up hogging all primary storage space and Signal hangs, with the situation only being resolved upon restarting the device.
**Expected result:** Signal tries to process uploads in a storage-efficient manner, not hanging the app and not hogging up primary storage space. 

### Screenshots

N/A: Cannot do screenshots when there isn't space on the primary drive.

### Device info
Device: XQ-AS52
Android version: 12
Signal version: 7.13.4

### Link to debug log
N/A: Signal app is hanging, cannot access debug log

**Comment by greyson-signal** [comment]
We copy videos into private storage as part of transcoding them. I don't anticipate us changing this behavior for now. Apologies!

**Comment by kaosmaja** [comment]
@greyson-signal so doing it one at a time is not possible? Or checking if there is enough memory in the first place?
