### ISSUE TITLE
Notification sound plays even when chat is open

### ISSUE THREAD

**Issue by snprajwal** [signalapp/Signal-Android#13677]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When a chat is open in the Signal app, the notification sound is played for every message that is received, even though the chat is already active and the messages are being read.

### Steps to reproduce

- Open a chat in the Signal app
- Get the person to message you while it is open on your phone

**Actual result:** You will persistently hear the notification sound
**Expected result:** You shouldn't hear the sound for a chat that's already open

### Device info

**Device:** Xiaomi 11i Lite NE 5G
**Android version:** 14 UKQ1.231108.001
**Signal version:** 7.14.2

### Link to debug log

https://debuglogs.org/android/7.14.2/315959e6b2918da3104919df4088558b34ec4368ece5d9cc670871ed4bfeb9ab

**Comment by bme13** [comment]
Hi. This is a setting. Check settings->Notifications->In-chat sounds

**Comment by snprajwal** [comment]
Ah, my bad. Thank you!
