### ISSUE TITLE
JobManager potential bug: jobs retry indefinitely

### ISSUE THREAD

**Issue by valldrac** [signalapp/Signal-Android#13679]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed that might be an issue in the JobManager, which seems to have started with commit [973dc72](https://github.com/signalapp/Signal-Android/commit/973dc72cfa5abbd1f5db6f37e7e736a6e6dd6241) in v7.13.0. It appears that the `runAttempt` counter might not be incrementing after each job retry in the job cache (`jobSpecCache`) in `FastJobStorage` class, leading to jobs retrying indefinitely until the app is restarted.
 
### Steps to reproduce
- Trigger a job failure that should lead to a job retry.
- Observe that the retry attempt count doesn’t increase and the job keeps retrying indefinitely, never reaching the max attempts limit.
- Restart the app.
- Notice that the job spec updates correctly from disk after the restart. 

### Device info

**Device:** Any
**Android version:** Any
**Signal version:** v7.16.2

### Analysis

Relevant code: [FastJobStorage.kt lines 203-209](https://github.com/signalapp/Signal-Android/blob/676be03ffcab2dd420ed8dcb165d55fda8208b93/app/src/main/java/org/thoughtcrime/securesms/jobs/FastJobStorage.kt#L203-L209)

To help identify this issue in the test suite, the `updateJobAfterRetry - state updated` test should use consistent values for `serializedData` between calls, and test incrementing `runAttempt` (the initial value is 1).

```patch
--- a/app/src/test/java/org/thoughtcrime/securesms/jobs/FastJobStorageTest.kt
+++ b/app/src/test/java/org/thoughtcrime/securesms/jobs/FastJobStorageTest.kt
@@ -298,7 +298,7 @@ class FastJobStorageTest {
 
   @Test
   fun `updateJobAfterRetry - state updated`() {
-    val fullSpec = FullSpec(jobSpec(id = "1", factoryKey = "f1", isRunning = true), emptyList(), emptyList())
+    val fullSpec = FullSpec(jobSpec(id = "1", factoryKey = "f1", isRunning = true, serializedData = "a".toByteArray()), emptyList(), emptyList())
 
     val subject = FastJobStorage(mockDatabase(listOf(fullSpec)))
     subject.init()
@@ -306,7 +306,7 @@ class FastJobStorageTest {
     subject.updateJobAfterRetry(
       id = "1",
       currentTime = 3,
-      runAttempt = 1,
+      runAttempt = 2,
       nextBackoffInterval = 10,
       serializedData = "a".toByteArray()
     )
@@ -315,7 +315,7 @@ class FastJobStorageTest {
     check(job != null)
     job.isRunning assertIs false
     job.lastRunAttemptTime assertIs 3
-    job.runAttempt assertIs 1
+    job.runAttempt assertIs 2
     job.nextBackoffInterval assertIs 10
     job.serializedData!!.toString(Charset.defaultCharset()) assertIs "a"
   }
```

I haven’t had the chance to prepare a PR for this, but I hope my analysis is accurate and helpful.

**Comment by greyson-signal** [comment]
You're totally right, thank you very much for discovering this! I really appreciate it. There will be a fix in 7.17 :heart:
