### ISSUE TITLE
Successful transfer to new Android device but cannot use PIN or create a new PIN

### ISSUE THREAD

**Issue by ZiggsZiggs** [signalapp/Signal-Android#13684]
- [x] I have searched open and closed issues for duplicates : [13609](https://github.com/signalapp/Signal-Android/issues/13609), [4468](https://github.com/signalapp/Signal-iOS/issues/4468), [11958](https://github.com/signalapp/Signal-Android/issues/11958), all closed without documented resolution option 
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am migrating from an old Android device (OnePlus 8T v14.0.0.602) to a new Android device (OnePlus 12 v14.0.0.840). I was able to transfer messages/contacts from the old to the new device. The old device is now unliked. During the PIN verification on the new device, I get an error "Error connecting to service." If I skip and try to create a new PIN, I get an error "Your PIN was not saved. We'll prompt you to create a PIN later."
I am now stuck in a PIN creation loop. 

### Steps to reproduce
- transfer Signal history from old to new device
- try to re-use existing PIN in the new device
- try to create a new PIN in the new device

**Actual result:** Re-using the old PIN fails with the error message "Error connecting to service." Creating a new PIN fails with the error message "Your PIN was not saved. We'll prompt you to create a PIN later." Signal is unuseable on either device (old is de-registered, new is not registered).
**Expected result:** The old/the new PIN is accepted and Signal is activated on the new device.

### Troubleshooting steps taken
- Restarted Android device
- Restarted Signal app
- Tried over DATA plan connection
- Tried over WiFi connection
- Tried creating a brand new PIN (different than the old one)

### Screenshots
![PIN creation failed](https://github.com/user-attachments/assets/920339f1-41ed-4449-9d66-6834cd1c3489)

### Device info

**Device:** OnePlus 12
**Android version:** 14.0.0.840
**Signal version:** [latest from Play Store]

### Link to debug log
I do not have access to Signal's settings (Help -> Debug log) because I'm stuck in the "Create a PIN" loop.

**Comment by liuzzi** [comment]
having same issue

**Comment by doffryn** [comment]
Same issue here today.

**Comment by Saik0Shinigami** [comment]
Sorry guys. I bought a new phone and went to restore Signal this morning. Clearly I broke it.

**Comment by valderman** [comment]
I had the exact same thing happen to me just now. It was also not possible to change the pin on the old device.

Removing the PIN entirely does work however, so I managed to migrate to a new device by re-registering the old device (which did not require the PIN), removing the registration lock, removing the PIN, and then redoing the account transfer.

**Comment by ZiggsZiggs** [comment]
> I had the exact same thing happen to me just now. It was also not possible to change the pin on the old device.
> 
> Removing the PIN entirely does work however, so I managed to migrate to a new device by re-registering the old device (which did not require the PIN), removing the registration lock, removing the PIN, and then redoing the account transfer.

Thanks for the tip @valderman . Did this transition allow you to keep/transfer conversation history?

**Comment by doffryn** [comment]
> I had the exact same thing happen to me just now. It was also not possible to change the pin on the old device.
> 
> Removing the PIN entirely does work however, so I managed to migrate to a new device by re-registering the old device (which did not require the PIN), removing the registration lock, removing the PIN, and then redoing the account transfer.

Thanks for this. I went back and disabled the old pin and this worked. As my transfer of the account data and messages was already completed, I did not lose any data as a result. I have not been able to set a new pin yet on the new phone, but do have all my messages and media.

**Comment by cody-signal** [comment]
Hey folks, one of our service providers had a pretty big hiccup (impacted lots of "The Internet"), and we are still recovering from it. Our team is actively looking into right now and we hope it'll resolve shortly. You can keep trying and it should eventually start working again once things iron out.

**Comment by BuxtonWater** [comment]
> Hey folks, one of our service providers had a pretty big hiccup (impacted lots of "The Internet"), and we are still recovering from it. Our team is actively looking into right now and we hope it'll resolve shortly. You can keep trying and it should eventually (hopefully minutes but maybe a couple hours) start working again once things iron out.

Thank you for the update!

**Comment by lizoron** [comment]
still not working as I'm experiencing the same problem right now, new phone setup.

**Comment by valderman** [comment]
> > I had the exact same thing happen to me just now. It was also not possible to change the pin on the old device.
> > Removing the PIN entirely does work however, so I managed to migrate to a new device by re-registering the old device (which did not require the PIN), removing the registration lock, removing the PIN, and then redoing the account transfer.
> 
> Thanks for the tip @valderman . Did this transition allow you to keep/transfer conversation history?

It did.

**Comment by lizoron** [comment]
I was able to register using the details above, but no I do not have my conversation history. Not sure if there's some additional step I missed to do that.

**Comment by rodney-b** [comment]
> Unfortunately things still aren't back yet on our end. Just got an update from the server team.

Thanks for being on top of it and the quick responses

**Comment by rodney-b** [comment]
PIN creation is working for me now 👍

**Comment by doffryn** [comment]
Same, all working and PIN registered.

**Comment by ZiggsZiggs** [comment]
I tried again today 13/09 and this time it went through. The PIN is now set in the new device, and the import from another device also worked.

Thanks everyone for your feedback.
Thanks Signal team for the updates.

**Comment by cody-signal** [comment]
Thanks for confirming! Things should be working normally now. Appreciate the patience and civility ❤️

**Comment by ARehmanMahi** [comment]
Same issue, Yeah. I'm having mixed feelings about this.
Oct 2024, I can't create pin.

Plus it doesn't find acounts by phone number.
I just installed on my 2 phones.

Im on mobile data.
Not sure if its the fucking firewall thing my countey imported from china.

But then where's the benifit of an encrypted app.
I tried vpn, ai tried the censorship setting, nothing works.
