### ISSUE TITLE
Message notification was received 50 minutes too late

### ISSUE THREAD

**Issue by Bethbryan** [signalapp/Signal-Android#13695]
### Steps to reproduce
- Used Signal like normal

**Actual result:** Notification was received about 50 minutes after the actual message was sent.
**Expected result:** Notification received with no delay.

**Signal version:** 7.16.4
Battery optimization: unrestricted
Stable internet connection

Message was send at 15:05:53 MESZ

### Link to debug log
https://debuglogs.org/android/7.16.4/a1913be9c3c48045a7b95e3224be79e7850c00767a945c4b104e2017e7335c37

**Comment by rmolson** [comment]
I'm having this issue as well.
Android version 14
CalyxOS versio: 5.11.0

**Comment by lucasmz-dev** [comment]
Are you using FCM or WebSockets ?
Two of my friends have notification troubles with FCM

**Comment by greyson-signal** [comment]
Unfortunately, best I can tell, this is a case of the OS just not providing us FCM notifications. You have a few in your logs that are extremely delayed, despite being high-priority notifications. Unforuntately there's only so much we can do.

**Comment by lucasmz-dev** [comment]
Is there anything a user can do? e.g. reinstalling Signal may help? @greyson-signal

**Comment by greyson-signal** [comment]
You can check out here:
https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

or here:
https://dontkillmyapp.com/

**Comment by soulmist7** [comment]
I am having this issue as well: GrapheneOS on Pixel 8 Pro - everything up to date
