### ISSUE TITLE
Building from source fails due to missing POST_NOTIFICATIONS permission and other errors

### ISSUE THREAD

**Issue by homedirectory** [signalapp/Signal-Android#13692]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Unable to build from source due to build-time errors.

### Steps to reproduce
- Clone this repository and `cd` into it.
- Execute the build with `ANDROID_HOME=~/data/android/sdk ./gradlew build`.
- Receive an error (E1).
- Address the error by adding the following line to `image-editor/app/src/main/AndroidManifest.xml
  ```
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
  ```
- Receive an error (E2).

E1:

```
/home/lambda/data/android/signal/signal-build/Signal-Android/image-editor/app/src/main/AndroidManifest.xml: Error: When targeting Android 13 or higher, posting a permission requires holding the POST_NOTIFICATIONS permission (usage from com.bumptech.glide.request.target.NotificationTarget) [NotificationPermission]

   Explanation for issues of type "NotificationPermission":
   When targeting Android 13 and higher, posting permissions requires holding
   the runtime permission android.permission.POST_NOTIFICATIONS.
```

E2:
```
Some problems were found with the configuration of task ':libsignal-service:sourcesJar' (type 'Jar').
  - Gradle detected a problem with the following location: '/home/lambda/data/android/signal/signal-build/Signal-Android/libsignal-service/build/wire/proto-sources'.

    Reason: Task ':libsignal-service:sourcesJar' uses this output of task ':libsignal-service:generateMainProtos' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':libsignal-service:generateMainProtos' as an input of ':libsignal-service:sourcesJar'.
      2. Declare an explicit dependency on ':libsignal-service:generateMainProtos' from ':libsignal-service:sourcesJar' using Task#dependsOn.
      3. Declare an explicit dependency on ':libsignal-service:generateMainProtos' from ':libsignal-service:sourcesJar' using Task#mustRunAfter.
```

### Notes

Errors E1 and E2 occur for versions 7.15.4 and 7.17.1.

I had previously successfully built 7.9.4 on another computer. Then I tried building that version on this one (where I'm receiving errors) and received just E2, which suggests that something could be off in my second machine's environment. Both machines run Arch Linux.

The `$ANDROID_HOME` variable mentioned above points to an sdk installed via Android Studio, which is Android 14.0 (API level 34).

**Actual result:** Build fails due to unexpected errors.
**Expected result:** The project is built successfully by following the [instructions](https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources).

**Comment by cody-signal** [comment]
The app currently builds fine for us from source. There could be something off with your configuration. We use GH exclusively for bugs, for help with development please checkout our forum: https://community.signalusers.org/c/development/6

**Comment by homedirectory** [comment]
Sorry for posting in the wrong place. I had the wrong impression that this was the right place to post after seeing existing issues related to reproducible builds and building from source.

In my environment, I am definitely using Java 17 JDK.
