### ISSUE TITLE
Sharing a picture without connection at the time of sending is stuck at recipient choosing, whereas sharing text is not

### ISSUE THREAD

**Issue by Chepycou** [signalapp/Signal-Android#13705]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a picture (or message) from the Signal app, even if your connection is laggy or off, the message is committed locally and will be sent once the network connection is back. Sharing a picture without connection stops after choosing the recipient, whereas sending text works all the way through.

### Steps to reproduce
- disable your network connection
- select a text and share it to a contact
- select a picture/video and share it to a contact

**Actual result:** Sharing the text works normally (the message will be sent ASAP) but when sharing the image/video, the app holds on the recipient picker page (where you get to check the recipients you wish to send the picture to)
**Expected result:** The app should proceed to the next step (add text/edit the image) and commit to message to be sent ASAP

### Device info
**Device:** Fairphone 5
**Android version:** 13
**Signal version:**7.17.5

Don't have an easy way to transfer stuff from my phone right now. If needed, tell me, I will send the relevant stuff when I can.

**Comment by greyson-signal** [comment]
Hi there, I can't seem to reproduce this. I've turned on airplane mode, went to my system gallery app, and shared a photo into signal. It created the pending message in the chat as-expected, wasn't blocked at all. Also tried picking media inside the app and it also worked. Is there anything else you can share? A log would definitely be helpful.

**Comment by Chepycou** [comment]
Truly weird,
Just tried to reproduce it again and it does not seem to happen. I was connected to a faulty Wi-Fi network at the moment of the error (rather than airplane mode), so this may be it ?
Also, I rebooted the phone several times since, which may have solved the issue ? 

If it ever happens again, I'll remember to generate the log !

**Comment by Chepycou** [comment]
Happened again here is a debug log :
<https://debuglogs.org/android/7.17.6/dd65d7a8dc8bf88096fb1aeed931816839f24f62974dd3560ff75fcfeb845e48>
I was in airplane mode and once I switched to data connection it worked.
R.LACROIX
--
Sent with K-9 Mail a Free and Open Source Mobile Mail Client.
Please excuse the brevity, spelling and punctuation.

**Comment by greyson-signal** [comment]
Hmmm, can you tell me more about where the data is being shared from? When we receive a share into the app, the first thing we do is copy the data into private app storage (so that we can send it). Are you maybe sharing from someplace where the data is remote and the app sharing the data would need to download it first? I'm not sure here, the log isn't showing any network activity during the share flows.

**Comment by Chepycou** [comment]
It's being shared from either my file manager or my photo app (Aves Libre). I tried from both when I had the airplane mode on, and it lead to the app stopping at the same place. Maybe it's just me missing something obvious though
