### ISSUE TITLE
Rate limit exceptions should be handled better

### ISSUE THREAD

**Issue by tinloaf** [signalapp/Signal-Android#1370]
I ran into a situation today where TS told me that "SMS is not available" constantly. Looking into the logs revealed that it was in fact a rate limit exception.
- This should be communicated to the user. Some message like "you're sending messages too fast" would be nice.
- TS should not try to resend those messages immediately, but rather wait
- Ideally, the TS server should present the client with a captcha that clears the timeout

**Comment by williscool** [comment]
+1. Had an important message to send. A friend and had to switch to the stock messaging app to send.

Shortly after I figured out you could disable secure textting altogether to get things to work.

but the trying to end the session in the thread didnt work either.

This bug was really weird for me because I had never sent a text secure message so I dont know how I could have hit the rate limit.

**Comment by williscool** [comment]
I'm new to TextSecure and I tried re signing up for the secure messaging and still got an error on thr debug log. This time it was "no attachments present" i was just trying to send text. Switching to all insecure for now. Need to be able to text this person. Also I could recieve his messages but not send

My device info:

```
Device  : LGE LGLS990 (g3_spr_us)
Android : 5.0.1 (150221743942c, LRX21Y)
Memory  : 43M (0.20% used, 256M max)
Memclass: 256
OS Host : LGEARND13B8
App     : TextSecure 2.23.3
```

**Comment by moxie0** [comment]
@williscool You would need to attach the debug log for us to be able to help you.

**Comment by williscool** [comment]
Debug log from settings :
https://gist.github.com/anonymous/18d91508863379324719

Catlog dump:
https://www.dropbox.com/s/v60mewzy4ssd4a6/textsexure-debug-log-2015-08-05-12-27-02.txt?dl=0

**Comment by moxie0** [comment]
There's nothing in this log. You have to capture it immediately after whatever problem you experience.

**Comment by williscool** [comment]
Search for "TextSecureMessageSender" in the lpg from that dropbox link.

The debug log capture either I was too slow or nothing showed in it

**Comment by moxie0** [comment]
@williscool It looks like your friend is using "whisperpush" on Cyanogen, is registered with their servers, and they're responding with the 413.  I'd recommend asking your friend to switch to TextSecure.

**Comment by williscool** [comment]
Ah! Interesting

**Comment by williscool** [comment]
But it would be nice to see a better error in the ui

**Comment by williscool** [comment]
Also Is there a way to only not secure message that one contact? Now I have to deal with that annoying overlay on the main message threads screen and ask my friend to change the app but I can't know for sure is going to happen in order to be able to send him a message
