### ISSUE TITLE
Enable vibration for In-thread notifications

### ISSUE THREAD

**Issue by generalmanager** [signalapp/Signal-Android#1371]
A friend of mine found a bug in [MessageNotifier.java](https://github.com/WhisperSystems/TextSecure/blob/339193af12fc81946eda4baba1877e5eace80262/src/org/thoughtcrime/securesms/notifications/MessageNotifier.java#L242):

If the options "In-thread notifications" and "Vibrate" are activated the phone vibrates and rings just fine unless you are in the thread that has a new message. In that case only the ringtone is played, but the phone doesn't vibrate.

**Comment by TWfromSWD** [comment]
Is this really the same as https://github.com/WhisperSystems/TextSecure/issues/1965? I totally understand that there is no vibration if you're already in the thread that gets the message, but in my case, the phone was locked, the screen was off and there was no notification at all. No Sound and no Vibration.

**Comment by mcginty** [comment]
Closed too quickly, you're right. Reopening and thanks for checking @TWfromSWD!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
