### ISSUE TITLE
Unhiding a hidden story crashes the app with `kotlin.NotImplementedError`

### ISSUE THREAD

**Issue by maximumultraist** [signalapp/Signal-Android#13710]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When unhiding a previously hidden Story, the app crashes with a `kotlin.NotImplementedError` exception. In addition to the Signal debug log, I have also attached the precise stack trace of the exception.
[Story unhide exception stack trace.txt](https://github.com/user-attachments/files/17123206/Story.unhide.exception.stack.trace.txt)

### Steps to reproduce
- hide a Story from a user
- view the hidden Story, and attempt to unhide it

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The app crashes with the aforementioned exception.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The app does not crash and unhides the story.

### Device info

**Device:** Google Pixel 9 Pro
**Android version:** GrapheneOS (based on Android 14 QPR3)
**Signal version:** 7.17.6

### Link to debug log
https://debuglogs.org/android/7.17.6/d3ea8d3d0ae62e8a7ba7a2c06c10a756e0308bb4582aab63f048106eeafc1958

**Comment by greyson-signal** [comment]
Fixed in upcoming 7.19 release.
