### ISSUE TITLE
No Flip Video Button in Group Calls

### ISSUE THREAD

**Issue by spagy** [signalapp/Signal-Android#13717]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is no button to switch/flip the camera in group video calls.

### Steps to reproduce
- Join group video call
- Tap screen to show buttons
- See that there is no flip video button

**Actual result:** There is no flip video button
**Expected result:** As described in the (Calling options support page)[https://support.signal.org/hc/en-us/articles/5369785769370-Calling-options-Switch-camera-microphone-or-view], there should be a flip video button

### Screenshots
![group-call-buttons](https://github.com/user-attachments/assets/12fab18b-b58c-4209-b886-b66d52fd3d92)

There is no flip video button. Tapping the ellipsis button doesn't show a flip video button either.

### Device info
**Device:** Google Pixel 8
**Android version:** 14
**Signal version:** 7.17.6

### Link to debug log
https://debuglogs.org/android/7.17.6/b49949a1be53f0a36cc77ba8e835ecdfe329d92fcc855d12aae42be63fb63fe4

**Comment by greyson-signal** [comment]
In a video call, the flip video button is on your little self-camera view. Before the call starts, it should be in the bottom right corner of your camera view.

**Comment by githubuser6000** [comment]
That just seems to make the self-view slightly larger. It does not make self-view the big-screen and remote-view the small screen

**Comment by spagy** [comment]
> In a video call, the flip video button is on your little self-camera view. Before the call starts, it should be in the bottom right corner of your camera view.

ah thank you. i'll try that next time!
