### ISSUE TITLE
Outgoing traffic 'blocked', incoming traffic works fine

### ISSUE THREAD

**Issue by vacuuuu** [signalapp/Signal-Android#13726]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

**Solved: Everything started working again!**

Sending messages not possible (spinning circle), receiving messages works fine after installing the recent update. After receiving and reading a message, the sender doesn't get a delivered or read confirmation (just one check mark). Looks like incoming traffic working just fine, but all of outgoing traffic being 'blocked' at some point.

I'm in the Android beta program. 

Everything worked fine yesterday. The issue occured today. In the meantime, there was an update this morning.

I've tried connections via mobile networks, Wifi networks, being connected to nordvpn and using no vpn.

### Device

Pixel 7 pro

### Android version

14

### Signal version

7.19

### Link to debug log

https://debuglogs.org/android/7.19.0/4b16db5b02d5e606278b8900b1609bd2a0d5e55c092bacf96b55648a768737df

**Comment by nuggex** [comment]
I am experiencing the same thing with the addition that I am unable to create a current backup to be able to reinstall. 

I get a log entry W JobCotnroll LocalBackupJobApi29 Job Failed with nothing to indicate why it failed.

**Comment by GlitchCat** [comment]
Same issue here, has been an issue for me since yesterday evening.
Same beta version also.

**Comment by abraarakhter** [comment]
I am seeing the same issue. Same phone and Signal version. 

https://debuglogs.org/android/7.19.0/213fabf7b23fafe42495d9c9a011cb1a685224dd97595828c30ab0f40cb24b6d

**Comment by leonnis12** [comment]
I have the exact same issue on the latest version from the beta program. In the logs, the backup job fails with Job failed, just as described above. This happens on the S24+.

**Comment by icynstant** [comment]
im having issues with 7.19.2

**Comment by Chromatros** [comment]
The most funny stuff is that on the same devices it works with molly.im

**Comment by nerozero** [comment]
Same here

**Comment by greyson-signal** [comment]
@melnikovsky Looks like you're seeing a separate issue entirely from what OP was experiencing. And it's not an issue with the receiver, but with the sender. I'd recommend opening a new issue and, if possible, attempting to get logs from the sender. Thank you!

**Comment by greyson-signal** [comment]
(Sorry, should have mentioned I'm closing this because OP and the first couple comments were for an issue that is duplicated here #13724)
