### ISSUE TITLE
Crash when editing notification profile from home screen

### ISSUE THREAD

**Issue by cyb3rko** [signalapp/Signal-Android#13741]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

When trying to edit the notification profile from the "home screen" the app just closes.

Editing it from within the settings (Settings -> Notifications -> Profile) works as expected.

### Screenshots

<IMG src="https://i.imgur.com/SzfJX0W.jpeg" width="300"/>

### Device

Google Pixel 7 Pro

### Android version

15 (35)

### Signal version

7.19.2

### Link to debug log

https://debuglogs.org/android/7.19.2/42251bd70ed1e3ec923e76d15ef478fb1c179ab48399bacdb1d6094c38d6379d

**Comment by greyson-signal** [comment]
I believe this has been fixed on newer versions.

**Comment by cyb3rko** [comment]
Sorry, you are right.
The newest version fixed it for me
