### ISSUE TITLE
Crash when scrolling to top of chat

### ISSUE THREAD

**Issue by iamjustmeithink** [signalapp/Signal-Android#13751]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

Whenever I open a specific group chat and scroll to the top, the app crashes consistently. This issue doesn't occur in other group chats or one-on-one conversations.

I've tried both the stable and beta versions of the app, but unfortunately, the problem persists in both.

It's worth mentioning that I imported a backup from my old phone about two weeks ago. However, I hadn't encountered this issue before, as I hadn't needed to view the earlier messages in that group until now.

### Device

Samsung S23 fe

### Android version

14

### Signal version

7.22.1

### Link to debug log

https://debuglogs.org/android/7.22.1/3b822badf340d3f4359c35e5b49b950f7b690e4d8c5b60aeefb85cca5c4e05d4

**Comment by iamjustmeithink** [comment]
I have reviewed the log and believe this is the issue:

```
[7.22.1] [main] 2024-10-27 22:28:07.841 GMT+01:00 W AppStartup              Too many end events! onCriticalRenderEventStart/End was mismanaged.
[7.22.1] [main] 2024-10-27 22:28:07.841 GMT+01:00 D ConversationListFragmen [startup] data-set: 1477, first-render: 10, total: 1487
[7.22.1] [main] 2024-10-27 22:28:07.841 GMT+01:00 W VoiceNoteMediaControlle Could not finish postponed media controller creation! (RoutingActivity})
```

Could you provide guidance on how to resolve this? Any steps or suggestions you can offer would be greatly appreciated.

Thank you!

**Comment by greyson-signal** [comment]
Huh, it looks like you have some person in the group that has no ACI/PNI, which are identifiers that are required of any group member. Does this happen to be a very old group with some very old history?

**Comment by iamjustmeithink** [comment]
Yes, it is a quite old group, with messages dating back to around 2022. With many messages daily.

Is there any way to fix this issue? Since I can see the messages in a split second before it crashes and closes.

Also; thank you so much for your fast response! Signal is my #1 place to be with my friends and family.

**Comment by greyson-signal** [comment]
I'm not sure if there's anything you can personally do at this moment, but I can add a check in 7.23 (which will go to beta later this week). Definitely a weird state though, and I'm not sure how you got into it. Even with the check I added to address this specific crash, it's quite possible it could crash somewhere later down the line, but I guess we'll see!

**Comment by iamjustmeithink** [comment]
Ok, thank you so much!

Well, I have no clue either, but everything else works, just not that particular group with the first messages. Indeed very odd.

I will look for the update and let you know if the behavior stands, or if it gets fixed!

Thank you for your time to adress my issue!

**Comment by iamjustmeithink** [comment]
It is working now! Thank you so much for taking the time to look into this and resolve the issue - I really appreciate it!

**Comment by greyson-signal** [comment]
Great to hear!
