### ISSUE TITLE
Chat added via username links local phone number

### ISSUE THREAD

**Issue by newhinton** [signalapp/Signal-Android#13755]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

I was setting up a secondary number via landline, and added that number as a chat. I then deleted the chat again, and re-added it via usernames. Signal then links the username back to the local number that is stored in my contacts.

I would expect that a chat that is added via username will not be tried to be linked to a local account.

If the number is not known, it is working as intended, the number is hidden.

### Device

Pixel 7

### Android version

15

### Signal version

7.20.2

**Comment by newhinton** [comment]
It seems after setting a nickname, signal removes the link from the local contact.

**Comment by greyson-signal** [comment]
There's a difference between "phone number visibility" and "phone number discoverability". The default is for visibility to be off, but discovery is on. Discovery being on means that  other people who have you in their system contacts can still find you by phone number. So  you'll still get linked to user's contacts. 

If you turn discoverability off, then other users _cannot_ link you to their contacts. 

You can read more about this here. Thanks!
https://support.signal.org/hc/en-us/articles/6712070553754-Phone-Number-Privacy-and-Usernames
