### ISSUE TITLE
Wrong screen after leaving Folder settings or Chat folders

### ISSUE THREAD

**Issue by TwoF1nger** [signalapp/Signal-Android#13761]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

1. either
    1. long-press a folder title in the conversation tab and select Edit folder from the context menu
    2. press the Folder settings button in the center of an empty folder (easiest with Unread)
1. then, press Back to leave the screen
1. instead of going back to the conversations tab, you are in Settings.

### Device

Redmi Note 11 Pro

### Android version

13

### Signal version

7.22.2

**Comment by greyson-signal** [comment]
This is fixed in 7.23, thanks!
