### ISSUE TITLE
Unable to send voice messages

### ISSUE THREAD

**Issue by modemrunner** [signalapp/Signal-Android#13778]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

I’m unable to send voice messages. The feedback is “The message cannot be sent. Please check your connection and try again” and Signal suddenly returns to screen lock. 
It’s ok to send other files or text messages.

### Device

Pixel 3a

### Android version

Android 12

### Signal version

7.24.0

### Link to debug log

[https://debuglogs.org/android/7.24.0/2800d2c0784d3ff74abeef3b2f5ddefeeab348fb7b04394bfd129a089d1ba31d](url)

**Comment by PhillyMay** [comment]
I ran into the same Problem after the latest Signal update (Signal Beta 7.24.0, Android 14, Samsung Galaxy S23)

**Comment by ronnybruechner** [comment]
Also here. Pixel 5 and Pixel 8 Pro, Signal 7.24.0.

Not matter, if its my own recorded voice message, or a extracted forwarded from Telegram. Also not matter, if I send it as *.ogg or *.mp3.

Same voice message, to the same receiver, is been delivered in seconds, when it was transfered with Signal 7.32 on Win11 Pro.

Friendly regards.

**Comment by rafirafirafi** [comment]
Same here galaxy S23
Cannot send voice messages, resending it crash signal

**Comment by PhillyMay** [comment]
Update: I just downloaded the available beta Update from the play store, which bumped my Signal Version to 7.24.2.

This update seems to have fixed the issue for me

**Comment by rafirafirafi** [comment]
Update fixed it. Thank you
