### ISSUE TITLE
Total unread (OS displayed value) doesn't respect folder unreads

### ISSUE THREAD

**Issue by matthewdavis** [signalapp/Signal-Android#13774]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

I have 1 folder.  A chat in that folder has 3 unread. Inside the app it correctly only shows 3. But the OS icon claims 6 unread.

### Device

Google Pixel 9 Pro

### Android version

Android 15

### Signal version

7.23.1

### Link to debug log

https://debuglogs.org/android/7.23.1/5092fad90ce66f4b2f769fdd8e100954e7afbb6548f295ef1ef31f300e1b614d

**Comment by bhanuj10** [comment]
Is it randomly occuring?
Or it's a common thing on ur device?

**Comment by greyson-signal** [comment]
We don't control the OS icon. The OS is determining "unread count" by counting notifications in the notification tray.
