### ISSUE TITLE
No media is sending plus signal crashes upon resend

### ISSUE THREAD

**Issue by marwanj** [signalapp/Signal-Android#13777]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

All media sent through my phone not being sent.
When I press on resend on the information menu, it leads to the app crashing.
This happens on the beta version of the app

### Device

Pixel 6

### Android version

15

### Signal version

7.24

### Link to debug log

[Uploading signal-log-1731112203110.zip…]()

**Comment by greyson-signal** [comment]
This was fixed in 7.24.2
