### ISSUE TITLE
[Data/Transfer] Signal on iOS and Android data transfer

### ISSUE THREAD

**Issue by LunarN0v4** [signalapp/Signal-Android#13773]
On both Signal iOS and Android, you should be able to transfer your data between both versions, no questions asked.  
This has been asked from Signal multiple times for a couple years now and this is still a problem even when it shouldn't be.  
SimpleX, WhatsApp, Session, and other encrypted messengers have a way to do this, yet Signal continues to lag behind in such a basic feature.  
Even in newer competitors, this simple feature is available.  
Not to mention, Signal iOS doesn't allow backing up and restoring data at all, while you can do so easily on Android.  
To make sure all developers of both mobile versions of Signal have this clear, I've duped this issue on both [signalapp/Signal-iOS](https://github.com/signalapp/Signal-iOS) and [signalapp/Signal-Android](https://github.com/signalapp/Signal-Android).  
This issue is only going to worsen as you add more features, since you'll need to account for more at once, so if you finish this now rather than later, this will be easier to continue in the future.

**Comment by greyson-signal** [comment]
Hi there, as noted in our issue template, we only use Github for bugs, not feature requests. That said, you'll be happy to know we're actively working on a cross-platform backup format.

**Comment by afeld** [comment]
[Feature Request](https://community.signalusers.org/t/switching-from-android-to-iphone-or-vice-versa-path-to-transfer-backups/15529?u=afeld)

**Comment by wreshi** [comment]
@greyson-signal Is there any timeline or anything? I literally have like 2 years of chats that I don't wanna lose. This is why I've not gotten an iPhone yet cause I can't transfer my Android Signal Chats to it.

**Comment by wreshi** [comment]
I think perhaps they just don't want to build it.

**Comment by greyson-signal** [comment]
@LunarN0v4 
> the feature request was made four years ago man, there is no way it has taken that long for your two teams to figure it out

Believe it or not, we were building _other_ things for the last four years ;) But we're actively building the format now, and while we don't commit to public timelines, we are doing our first test of the format with desktop history syncing, which you can read about here: https://community.signalusers.org/t/help-us-test-desktop-history-syncing/65452/73
