### ISSUE TITLE
Signal makes the extraordinary request of entering the device password without giving a strong reason

### ISSUE THREAD

**Issue by mlncn** [signalapp/Signal-Android#13780]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

When linking a new device, Signal on Android says "Tap continue and enter your phone's lock to confirm. Do not enter your Signal PIN." and the next screen is within Signal which seems… really wrong.  Opening something in Android for the password would be less concerning, if that is possible.

And either the prompt or the documentation should explain why the Signal PIN is not requested here.

The documentation does not mention this: https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices

### Device

Blackview BV9100

### Android version

9

### Signal version

7.23.1

**Comment by greyson-signal** [comment]
> and the next screen is within Signal which seems… really wrong

If the concern is that we have some custom UI built by us to receive your password, that is not correct. We do, in fact, call out to the system to prompt for the device password. The styling can vary wildly between OEM's and Android versions. Many OEMs will implement it as a dialog that could make it _look_ like it's part of Signal, but it is not.

> And either the prompt or the documentation should explain why the Signal PIN is not requested here.

One can technically opt-out of PINs, so we only use it for restoring data during registration if people haven't opted out.

Asking for the device lock has become standard practice among messaging apps when linking a new device. It helps prevent the scenario where you lend your phone to someone and they link their laptop to your phone while you aren't looking.

iOS is still building this feature, I believe, and the documentation on our support site will be updated when they're finished. Thanks!
