### ISSUE TITLE
Long press on app icon behaves differently from all other apps (doesn't sow "App info")

### ISSUE THREAD

**Issue by leoheitmannruiz** [signalapp/Signal-Android#13793]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

When I long press on apps I get a pop up that says "App info". It's got a little "i" in a circle icon. When I click this icon I am shown the "App info" screen for that app in my system settings.

This is the case for every app on my phone, except for Signal.

When I long press on Signal, I get a similar pop up. However, it doesn't say "App info". It does show the same icon. I can only get to the system settings screen by clicking on the icon, not where I expect text to be. Also, when long pressing on the icon, a little pop up is shown that says "App info". This is not the case for any other app.

### Screenshots

![normal](https://github.com/user-attachments/assets/0137bdb9-f469-472d-9ca5-7fcd61cbe8c3)
![bug](https://github.com/user-attachments/assets/a67d0e29-dd4b-4752-805d-9ca555187a3a)

### Device

Google Pixel 6a

### Android version

15

### Signal version

7.23.1

**Comment by greyson-signal** [comment]
My understanding is that this is the responsibility of the launcher, and this is likely a weird bug with the launcher you're using.
