### ISSUE TITLE
uptime.signal.org resolves to 127.0.0.1 -- blocked as DNS rebind attack

### ISSUE THREAD

**Issue by timkgh** [signalapp/Signal-Android#13800]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

```
> dig +short uptime.signal.org @8.8.8.8
127.0.0.1
```

How is that useful? It is identified as a DNS rebind attack.

**Comment by greyson-signal** [comment]
This is a mechanism we have in place to check if the signal service is down, so we can alert users. We flip the domain that url points to and check it if we ever have difficulty contacting the service.

https://github.com/signalapp/Signal-Android/blob/9b36c62ba3d0b63600a874f3b94f8ed2ccf6093b/app/src/main/java/org/thoughtcrime/securesms/jobs/ServiceOutageDetectionJob.java#L60

**Comment by timkgh** [comment]
Thanks for the explanation. Perhaps you could reconsider how it works and what it resolves to, it does not feel reliable with DNS providers that will just flag the domain as a [DNS Rebind Attack](https://en.wikipedia.org/wiki/DNS_rebinding).

**Comment by CodeSapiens** [comment]
I agree that this needs to be revisited. The URL gets blocked as DNS Rebinding by my upstream DNS resolvers, which I assume will render Signal's check useless. I could add a rule to always allow uptime.signal.org, but that feels like a hack.
