### ISSUE TITLE
Default Notification contains "Name & Message" rather than just "New signal message"

### ISSUE THREAD

**Issue by jameshfischer** [signalapp/Signal-Android#13821]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

For a new user, one perhaps unfamiliar with the setup options, the default behavior of the app seems to frustrate the goal of security, as notifications are cleartext, can be sent by default to smartwatches, and remain even after the message itself has been deleted.  

"Notification History" should not expose Signal communications or correspondent identities, by default.

It is not 100% clear, but this choice of default behaviors may be the reason why signal communications were compromised in this case:  https://www.startribune.com/court-filing-describes-chaotic-messaging-around-attempted-120000-bribe-in-feeding-our-future-trial/601182903

### Device

Irrelevant, but Pixel 9 Pro

### Android version

Irrelevant, but Android 15  (11/5/2024 security update)

### Signal version

7.25.2

**Comment by greyson-signal** [comment]
Signal strives to be a useful messenger by default, and that means showing message content in notifications by default. I don't anticipate changing this default anytime soon.

**Comment by james-lawrence** [comment]
[translation](https://www.404media.co/fbi-extracts-suspects-deleted-signal-messages-saved-in-iphone-notification-database-2/): signal puts its users security at risk by default. dropping it down to the name only is a reasonable (and sane) compromise.
