### ISSUE TITLE
No spacing for "kiss" emojis put next to each other

### ISSUE THREAD

**Issue by looowizz** [signalapp/Signal-Android#13840]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

When sending any two of the "kiss" emoji combinations (e.g. 🧑🏾‍❤️‍💋‍🧑🏼🧑🏾‍❤️‍💋‍🧑🏼 or 👩🏾‍❤️‍💋‍👩🏾👩🏽‍❤️‍💋‍👩🏾), they have no spacing so look like they are directly next to each other, which i think is not supposed to happen?

### Screenshots

**
![signal-emoji-issue](https://github.com/user-attachments/assets/bb1defd1-e976-47cf-b7d4-f08a5dd85929)
**

### Device

Google Pixel 4a (5G)

### Android version

14

### Signal version

7.26.1

**Comment by poojasngh432** [comment]
<img width="344" alt="Screenshot 2024-12-16 at 7 07 20 PM" src="https://github.com/user-attachments/assets/1159431c-c8e1-46bd-91bd-c5f4ed4d82f7" />
This applies to all emojis that have a straight edge on the sides. Adding space most likely is a business decision and doesn't seem like a bug/issue.

**Comment by greyson-signal** [comment]
Yeah, I think I may leave it as-is for now. But thanks!
