### ISSUE TITLE
Signal silently falls back to "unsealed sender" messages if server returns 401 when trying to send "sealed sender" messages

### ISSUE THREAD

**Issue by pixelschubsi-gh** [signalapp/Signal-Android#13842]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

Reviewing the source code, I noticed the following:
https://github.com/signalapp/Signal-Android/blob/542374aee0e9da8bf957255d8512d63e30ccfee5/libsignal-service/src/main/java/org/whispersystems/signalservice/api/SignalWebSocket.java#L194-L224
If a message with `SealedSenderAccess` is sent, it uses the unidentified web socket (as expected). If the server returns status `401`, the client will attempt to send the message again using the `SealedSenderAccess` returned by `SealedSenderAccess.switchToFallback()`.

For a chat with an individual that you don't share a group with, there is no fallback: https://github.com/signalapp/Signal-Android/blob/542374aee0e9da8bf957255d8512d63e30ccfee5/libsignal-service/src/main/java/org/whispersystems/signalservice/api/crypto/SealedSenderAccess.kt#L154-L157

For other chats there may be one or multiple fallbacks in place. In any case, once there is no fallback left, it will return the `null` fallback:
https://github.com/signalapp/Signal-Android/blob/542374aee0e9da8bf957255d8512d63e30ccfee5/libsignal-service/src/main/java/org/whispersystems/signalservice/api/crypto/SealedSenderAccess.kt#L66-L74

If the `null` fallback is returned, `request` is invoked using `null` as a `SealedSenderAccess`, which results in it redirecting the message to the sending flow on the authenticated web socket without sealed sender access.

This effectively allows the server - if turned malicious - to turn off sealed sender selectively by returning a 401 for a given message they receive from a sender (by IP) or for a recipient.

**Comment by FrankThe** [comment]
Feature > Bug

**Comment by greyson-signal** [comment]
Yes, the server is the one who validates that you have the correct token to message the other user in an unauthed fashion. This validation is an important step to help cut down on the different types of abuse that could happen if you allow unauthed connections to send messages to anyone.

That also means that the server could prevent you from sending sealed sender. That's a trade-off we're ok with. Sealed sender is not a guarantee, but rather a best-effort sort of thing. There are many legitimate reasons that you may have an out-of-date token that causes the server to return a 401, and those reasons are not a cause for alarm. It's not at all comparable to a safety number change, where we stop the send and notify the user, and I don't think notifying the user of a unsealed send fallback is necessary.

For people who are concerned about this sort of thing, you can enable sealed sender indicators in the settings.

**Comment by nehemiagurl** [comment]
@greyson-signal i think the concern was more about the server being able to create a mapping between sender and receiver, no?

**Comment by greyson-signal** [comment]
Yes, one day the server could decide to no longer support sealed sender, and sends would go back to be unsealed, and the server would know who the sender is. There's not a great way to prevent that with the current design. There's legitimate reasons that you might get a 401 (i.e. the receiver blocked you, changing their profile key, causing you to be unable to send sealed sender to them), and those are indistinguishable from the server just returning a 401. This system was intended to be best-effort (and we do, indeed, do everything we can to bias ourselves towards sending sealed sender messages), but there's no guarantee. 

Users can turn on the sealed sender indicators in the settings if this is something that they're concerned about.

**Comment by nehemiagurl** [comment]
@greyson-signal i'd argue that maybe there should be a way on the client end of blocking messages not being sent via Sealed Sender. immediately finding out about an attack from the server essentially rules out most attacks, but i think it's probably better to have the option for it not to be there in the first place (i know y'all really don't like toggles but i'd argue it's not too different to the existing Sealed Sender toggles)

**Comment by Whatnoww** [comment]
> Yes, one day the server could decide to no longer support sealed sender, and sends would go back to be unsealed, and the server would know who the sender is. There's not a great way to prevent that with the current design. There's legitimate reasons that you might get a 401 (i.e. the receiver blocked you, changing their profile key, causing you to be unable to send sealed sender to them), and those are indistinguishable from the server just returning a 401. This system was intended to be best-effort (and we do, indeed, do everything we can to bias ourselves towards sending sealed sender messages), but there's no guarantee.
> 
> Users can turn on the sealed sender indicators in the settings if this is something that they're concerned about.

AFAIK this is not representative of current behavior? Right now if someone blocks you, you will continue to send sealed sender, but messages just don't deliver. After a while the client then starts falling back on non sealed sender. It's never immediate, and message delivery just stops at first.

**Comment by pixelschubsi-gh** [comment]
Can you list all the legitimate reasons for the server to return 401?

I believe for many of them (like the user changing their profile key), one could have the 401 reply include a proof of legitimacy (e.g. some sort of signature from the recipient's client that proves that they authored a profile key change).

If the server can't provide a verifiable proof that the 401 is for good reason, the client should not automatically switch to non-sealed sender messages and issue a warning to the user instead.

**Comment by nehemiagurl** [comment]
this @soatok blogpost seems to imply the attack described in this issue will fully bork groups for the android client, making it extremely noticable. and as mentioned, the server can't selectively 401, they'd have to do it for everyone. am i understanding this correctly?
https://soatok.blog/signal-crypto-review-2025-part-4/

**Comment by pixelschubsi-gh** [comment]
At the time the server decides to send a 401, it knows the intended recipient of the message and the IP address of the sender. It thus can selectively return 401 to do harm.

Hypothetically, assuming a malicious server wants to know all active contacts of a user, they could return 401 for all messages that are sent to that user and then, from the not sealed sender message sent instead learn the sender/recipient pair. Alternatively they could determine the IP address used by a user to receive messages and return 401 for all sealed sender requests coming from that IP address (thus if multiple users share an IP address, they can clearly see which messages have been sent by which user).
