### ISSUE TITLE
textsecure not an option when "sharing" an address book contact

### ISSUE THREAD

**Issue by deadpoint** [signalapp/Signal-Android#1407]
TextSecure is not an option when attempting to share a contact from the address book, in Android 4.4.2 when i select "messaging" it tells me "messaging" is not the default sms app. This would be a nice feature to have added to the app.

**Comment by Mihahn** [comment]
I'd like to bump this as it's a feature that I'd love to see. I think I'd be very useful to share contacts securely using TS (if TS would handle them properly and let you import them in your "Contacts" app/phonebook)! :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
