### ISSUE TITLE
New Thread Contact Search + Not Reducing Contacts Correctly

### ISSUE THREAD

**Issue by landry314** [signalapp/Signal-Android#1414]
I don't know if anyone else is having this issue but when I click on the + to start a new thread and start to type then certain letters do not work properly and results appear that do not contain these characters.

For example... I am looking for a girl named "Mio". I type "m". I get "AJ", "Alex"... no 'm's in that... when I type the whole name it does not eliminate anyone, like it hates the 'm' key... She is in the list but much lower below a bunch of people who should not be showing up.

I type "a" and "Britt" is in the list. I type "m" again and I am left with "Amy, Britt, Jodi" so only the first result is correct. I type "m" again... eliminates all contacts but when I type a "y" it successfully reduces to "Amy"... how does this make sense?

Why does it work for Amy but not Mio?

When I type "gwenyth" it reduces fine but "Emma" pops up after first character then disappears after second...

"Anna" comes up for "d" ???

I am using a google address book on a Motorola Cliq 2 running Android 2.3.7 with no data plan and push turned off and TS set to receive all SMS.

Searching works fine directly from the Contacts app.

**Comment by volcano99** [comment]
I have weird problems with the search field too. Searching for a set of letters like "ad" brings up all sorts of contacts except for the only one with an "ad" in it. This is extremely confusing

**Comment by rhodey** [comment]
issue #2378 has some useful context for this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
