### ISSUE TITLE
Allow turning off sound notifications

### ISSUE THREAD

**Issue by virtualritz** [signalapp/Signal-Android#1423]
When `Notifications` are switched `on`, a user can select a `LED blink pattern` of `None` and/or can set `Vibrate` to `off`.
But they can't switch off `Sound`. The only way to switch off sound is to have a sound file that contains no sound at all.

Rename the current Sound widget to `Sound file`. 
Add a `Sound` checkbox above and use it to gray/ungray the `Sound file` widget.

Aka:

```
Sound        [ x ]
Sound File
```

**Comment by KonomiKitten** [comment]
@virtualritz Hey I know this bug is extremely old by now but I found a possible solution to your issue and documented it over in this bug report https://github.com/signalapp/Signal-Android/issues/8478#issuecomment-449248946
