### ISSUE TITLE
Push Messaging Failure

### ISSUE THREAD

**Issue by charlieamadeus** [signalapp/Signal-Android#1447]
Despite having push messaging capability with nearly all of my contacts who use TS, one seems to default to SMS. Oddly, this contact can send me push messages with no problem. Issue arose after the contact's phone entered Android Safe Mode. I've tried new keys, but haven't reinstalled. Any suggestions? Thanks for all of your hard work.

**Comment by naconner** [comment]
I've experienced this issue numerous times on prior and latest Signal for Android and Desktop. When an Android contact's phone is placed into power saving mode, my client thereafter believes his number to be unregistered.

I can receive messages from him, but my Android client wants to send replies over SMS instead, and my desktop client throws the error `Number is not registered`. This persists after contact reinstalls Signal and also after reverifying keys. [We switch to another platform until such time as Signal recognizes him as being registered again, but what event triggers this is unknown to me.]

Excerpted debug logs from my desktop client:

```
2016-06-04T19:55:25.452Z sorting conversation +[REDACTED]323
2016-06-04T19:55:25.522Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]323
2016-06-04T19:55:26.717Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]323 404 Error
2016-06-04T19:55:26.729Z UnregisteredUserError: Number is not registered.
2016-06-04T19:55:26.736Z Failed to create or send message Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:112:39
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:123:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:39360:3
```

Full logs: https://gist.github.com/naconner/0c80caf8a7e7426490ab356825b0ffe7#file-gistfile1-txt-L979-L1009

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
