### ISSUE TITLE
Not all contacts of a group chat receive same messages

### ISSUE THREAD

**Issue by monreal** [signalapp/Signal-Android#1453]
We found this while trying to recreate some other issues this morning. In a group chat of three contacts A, B, C:
- A sends a group message
- B does not see the group message
- C sees the message and replies
- A does not see group reply
- B does see the group reply

After that more test messages were exchanged and this time all participants got the message. This is probably hard to reproduce but it looks like the message delivery in TextSecure (at least with groups) is not reliable at this point.

**Comment by rhodey** [comment]
hi @monreal, are you still having this issue? can you remember if this was an MMS group or a TextSecure push messaging group (as in every member has TS installed)?

**Comment by monreal** [comment]
Well, this was using push as I have never ever used MMS in my life. As for the "am I still having the problem": it's hard to tell because most people have since stopped using TextSecure unfortunately because it was too unreliable. However I have seen the bug multiple times after I originally filed it.

**Comment by rhodey** [comment]
thanks for the update @monreal, I'll leave this open for now.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
