### ISSUE TITLE
[Proposal for a registration improvement] When registering a tablet w/o SMS functions and using temporarily a second SMS enabled device: allow to manually enter the six-digit code during step 2

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#1467]
_With reference to #1397 and after  a discussion with @generalmanager I like to propose this small UX change during the registration step 2 (when the silent sms is used to register the device's number)._
- Current situation:

During Step 2, the registration currently waits for 2 minutes to receive the (first) registration SMS. This registration obviously fails in the case that the device (e.g. a tablet without SMS/MMS functions) is unable to receive SMS. If the user has a different device e.g. a smartphone with their SIM card and SMS/MMS enabled, they receive the first code on this device.

After the timeout the first code is not valid any longer. The user can manually trigger the TS server to send a second six-digit-code via the Code-by-Voice-call function, and then enter the second code to finish the registration on their tablet.
- My suggestion (TOFU-compliant):

In oder to comply with the trust-on-first-use (TOFU) principle and to avoid the abvove mentioned second registration cycle by voice (in the case of a tablet without SMS/MMS function) I suggest a **code change to allow the entering of the six-digit-code already during the first cycle**. 

I mean this: 
- already during registration step 2 - while the device waits for 2 minutes to receive the first verification code in a silent SMS
- users should be _able_ to enter the (first) code manually in case they are in possession of it because they received it on their other, SMS/MMS-enabled phone device.

In my view this appears to be possible, and does not break the workflow, or introduces security threats.
- Advantages
1. Less registration codes need to be sent, lowering the number of "registration failures during step 2" (when the device cannot receive SMS, but the SMS was sent to another device of the user)
2. much easier and quicker registration for tablet users, because the timeout does not matter any more: user cann immediately enter the code in the first cycle (TOFU)

**Comment by unsignedzero** [comment]
Any update on this as the current app I'm using still has this bug.
