### ISSUE TITLE
Contact shortcut/widget

### ISSUE THREAD

**Issue by effem** [signalapp/Signal-Android#1484]
Hi,

it would be nice to be able to create shortcuts to contacts from my contact list.
The new icon on the home screen would directy jump into the converstion with the selected user.
The icon could be the users profile picture on the phone.

**Comment by blokeley** [comment]
This would be great.  The default android widget for "Contacts > Direct message 1 x 1" can open Signal in a specific SMS chat. 

However, it can't open a Signal (encrypted) chat.  

WhatsApp has the widget "WhatsApp > WhatsApp Chat 1 x 1" which does open a specific IM chat. Please could the same be done for Signal?

**Comment by Hanzei** [comment]
@blokeley  On Android 7.1 a "Contacts > Direct message 1 x 1"  widget can open the chat directly. But its not possible to link to a groupchat.
If someone wants to develop this feature, https://developer.android.com/guide/topics/appwidgets/index.html would be a good startingpoint

**Comment by blokeley** [comment]
@Hanzei the direct message widget works perfectly. Thanks

**Comment by dcormier** [comment]
The direct message widget workaround does not work. It opens the default SMS client, not Signal. I do not use Signal as an SMS client at all.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
