### ISSUE TITLE
text search messages

### ISSUE THREAD

**Issue by asaladin** [signalapp/Signal-Android#1488]
I would love to see a text search feature to dig through old messages

**Comment by JohnnyCalavera** [comment]
Since #1232 is locked I can only comment on this issue. Are we gonna get any response after over 2 years of waiting for a search feature, please?

**Comment by nrizzio** [comment]
@JohnnyCalavera It was locked because bumping issues accomplishes nothing except clog up contributor's notifications. If the issue is open, then the feature will be accepted if someone contributes it. If you want to discuss a feature, please do it at whispersystems.discoursehosting.net. Thanks.

**Comment by erik55** [comment]
Search is working since mid 2018, see https://www.reddit.com/r/signal/comments/8repb9/signal_for_android_now_has_full_text_search/
