### ISSUE TITLE
Notification Color for Individual Contacts or Groups

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#1504]
~~how about we edit this one too?  or just delete it.....~~ :see_no_evil:

**Comment by Sysy1** [comment]
it would be great if you do that for the notification bar and the led!

**Comment by rhodey** [comment]
related #354

**Comment by Fmstrat** [comment]
Would definitely appreciate this a well. Once I handle CSRF in ownNote, I may fork off this and see if I can help you guys out with a pull. I didn't see this in the CONTRIBUTION file, but I did see this:

"**The answer is not more options.** If you feel compelled to add a preference that's exposed to the user, it's very possible you've made a wrong turn somewhere."

Is this LED feature something you don't want external developers focusing on until all the kinks are worked out?

Thanks!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
