### ISSUE TITLE
Plain text export silently creates invalid XML if any message contains Unicode Emojis

### ISSUE THREAD

**Issue by raphinesse** [signalapp/Signal-Android#1546]
The plain text export suffers from a bug in Android's `org.kxml2.io.KXmlSerializer.writeEscaped` where [UTF-16 surrogate pairs](http://en.wikipedia.org/wiki/UTF-16#Code_points_U.2B10000_to_U.2B10FFFF) are erroneously rejected as invalid characters.

This is particularly problematic with a message export since it is likely that messages will contain those characters, and a single occurrence in any message will render the whole file useless without manual correction.

See the [corresponding android issue](https://code.google.com/p/android/issues/detail?id=64108) for more details, including a fix written for another android application.

**Comment by 360path** [comment]
I've exported Messages from Version 3.25.4 but the export is still corrupted (contains invalid characters such as "&#55357;" or "&#56856;") when there is an emoji in the message.

**Comment by hrehfeld** [comment]
Same here. Please reopen.

**Comment by hrehfeld** [comment]
Here's an example from current playstore version:

    <sms protocol="0" address="xxxx" date="xxxx" type="1" subject="null" body="hey &#55357;&#56841; &#55356;&#57226;&#55356;&#57220; " toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />

These are mostly emojis: https://raw.githubusercontent.com/wooorm/emoji-emotion/master/support.md

But sometimes there are also linefeeds:

    body="Anruf-Info: +xxx hat versucht Sie anzurufen (xxx)&#10; * Dieser Dienst ist fuer Sie kostenlos"

    body="Hey!&#10;&#10;Wie gehts?&#10;&#10;Viele Grüße!"

**Comment by eliask** [comment]
Stumbled on this bug as well. 

For better search engine visibility, libexpat throws XML_ERROR_BAD_CHAR_REF or "reference to invalid character number".

One would think there is some standard way to escape/transform any messages for use in XML but maybe not?

Anyway, since I wanted to get something useful out of the exported XML file, I replaced the invalid characters as follows:
```
sed 's/&\(#[2-9A-Fa-f][0-9a-fA-F]\{4,\};\)/ (\1) /g' \
SignalPlaintextBackup.xml > SignalPlaintextBackup.xml.cleaned
```

More comprehensively (seems to match the XML spec 1:1):
```
sed 's/&#\([^9AD]\|1[0-9A-F]\|D[89A-F][0-9A-F][0-9A-F]\|FFF[EF]\|1[1-9A-F][0-9A-F]\{4,\}\|[2-9A-F][0-9A-F]\{4,\}\);/ (#\1;) /gi' \
SignalPlaintextBackup.xml > SignalPlaintextBackup.xml.cleaned
```

Aside: since XML was a pain to deal with, I wrote a quick tool for converting it to a similar JSON structure and got nicer to process messages with `jq`:
```
./xml2json.py SignalPlaintextBackup.xml.cleaned  | jq -c '.smses."@children"[].sms'

{"protocol":"0","address":"+123456","date":"1493000000000","type":"1","subject":"null","body":"testing Ӓ","toa":"null","sc_toa":"null","service_center":"null","read":"1","status":"-1","locked":"0"}
{"protocol":"0","address":"+6544321","date":"1494000000000","type":"1","subject":"null","body":"äöå","toa":"null","sc_toa":"null","service_center":"null","read":"1","status":"-1","locked":"0"}
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
