### ISSUE TITLE
Make password input field swipe friendly

### ISSUE THREAD

**Issue by generalmanager** [signalapp/Signal-Android#1651]
There aren't too many simple ways to create a secure and easy-to-remember password.
One of the better strategies are Diceword passphrases ([you can learn more about them here](http://arstechnica.com/information-technology/2014/03/diceware-passwords-now-need-six-random-words-to-thwart-hackers/))
Diceware makes it easy to create memorable passphrases with over 80 bits of entophy, but with Androids textPassword field every letter has to be entered manually.

If it were possible to swipe (with the AOSP keyboard), many words could be entered within seconds, improving the usablility of complex passwords.

I don't use any non-FOSS keyboards (like the Swype, SwiftKey, the google keyboard and so on) so I wasn't able to test their behaviour. If you use a third-party keyboard, please test the behaviour of the keyboard on the textsecure unlock screen and let us know if swiping is possible.

Maybe there is no way around it, but I'd still like to discuss possible workarounds, as this is a seemingly minor change which may still improve the average password strength a fair bit.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
