### ISSUE TITLE
Bad encrypted message...

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-Android#1668]
Hi, every now and then (perhaps once a month, but then again I don't text like crazy) I receive a "bad encrypted message" from a TS contact.

This one was received recently and I captured logs immediately. I don't have (and am unlikely to get) logs from the sender.

Logs: http://hastebin.com/zepunizevi

We have since exchanged 5-6 messages (some of them just a few minutes after the "bad message") with no issue - so I can't reproduce this... Hope the logs have some useful information. if not, it would be great to know what I should do next time this happens - other than (presumably) requesting the sender capture logs as well.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
