### ISSUE TITLE
Editing contacts impossible

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#1672]
Hi, I have a problem.
Since I installed TextSecure, I can't edit my contacts any more.
Let me explain. If I use the phone's default app to edit the name/surname of a contact (which I save on my sim card), and then reboot the phone, all the edits are gone. This started happening after I installed TextSecure, for some reason.
It's obviously very annoying and it's kind of driving me crazy. Please fix it.
Thank you

**Comment by Myutouuhh** [comment]
You can edit contacts on android phone easily ! But if you want to edit Android phone contacts on computer. With the help of contacts editor ,you need to connect android phone with USB cable on computer .
http://www.how-to-print-text-messages.com/resources/android-contacts-editor.html
