### ISSUE TITLE
Add Android Wear support

### ISSUE THREAD

**Issue by cypressious** [signalapp/Signal-Android#1699]
Hangouts has the possibility to answer with predefined answers or voice. Something similar would be awesome for TextSecure. Since all this works over notifications, this should be reasonably easy to intergrate.

**Comment by kristovatlas** [comment]
Wear support would be unbelievably cool...

**Comment by vinilox** [comment]
I agree, Android wear support would definitely be cool !

**Comment by espeed** [comment]
+1

**Comment by midi** [comment]
This was merged a while back: https://github.com/WhisperSystems/TextSecure/commit/424a463b21869b9afa674430709a4dc3e03be31c

But sadly has no option to reply.
Please consider adding that, as it's super useful.

**Comment by joeykrim** [comment]
Should this be closed, as https://github.com/WhisperSystems/Signal-Android/pull/3244 was merged allowing replies from Android Wear?

**Comment by lightmaster** [comment]
This Feature Request is several years old now, are there any plans to add a native Android Wear app? I would really like to see an app where you can view your messages, reply to a chat that's not in your notifications, start a new chat, etc. It's very annoying how, currently, you can reply to a notification on Android Wear, but if you want to send a second message, you have to either open up Signal on your phone, or wait until they reply back.

**Comment by darkpixel** [comment]
I'm a bit late to the Android Wear game, but I'd love to see support too.  I occasionally get messages while out for a walk or run and would love to tape on my watch and send a voice reply.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
