### ISSUE TITLE
Type SMS without selecting recipient first

### ISSUE THREAD

**Issue by ludovicaelbrecht** [signalapp/Signal-Android#1700]
Hi all,

When creating a new SMS message, a user is forced to select a recipient before being able to type a message. It's not uncommon for users to prefer to type the message first, than select the recipient(s). Advantage: if the user presses 'send' accidentally, an incorrect/incomplete message is not sent by accident.

One way some SMS apps implement this, is to have a recipient selection screen show up, like TextSecure does, but which also contains a button "Skip" or "Next". Pressing this button brings the user to the next screen, where the message can be typed. The top bar of the screen than doesn't display the recipient, but instead shows something like "Add recipient" or another visual cue of where to press to select a recipient.

Thanks for considering this,
Ludovic

Nexus 5, stock Android 4.4.4, TextSecure 2.0.8.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
