### ISSUE TITLE
Bring back the encrypted backup!

### ISSUE THREAD

**Issue by schmitmd** [signalapp/Signal-Android#1705]
I loved the fact that I could export an encrypted backup of my texts. Version 2.1.0 took this functionality away, please put it back ASAP or make a disclaimer on why it's gone.

**Comment by landry314** [comment]
i dont care about my texts but my keys i would like a clean and secure way to migrate to a new phone when i upgrade. does the export plaintext option export private keys in plaintext? i would be shocked. does it have anything to do with the keys or just the texts? should i just move the files in /data/data manually to export my keys?

**Comment by phipolis** [comment]
I agree with @landry314 that exporting the private keys would be an excellent stopgap until encrypted backups can be restored. Only power users are going to use 3rd-party apps to backup their TS configuration. For everyone else, a new phone means a new key. This really bothers me, it blows the TOFU model out of the water. Users get used to clicking through key change alerts accompanied by "it's fine, I got a new phone" messages. Uh-huh.

IMO it's bad enough that users have to know about and remember to use the export function in settings to keep key continuity. Having no option there and needing to use (and know about) 3rd-party apps is even worse. As @agrajaghh's #2154 suggests, Flock is perfectly positioned to provide seamless device-independent backups of the key material. Backups that don't require the user to remember, nor even to have a concept of key continuity. This to me seems to align best with the OWS imperative of simplicity.

**Comment by landry314** [comment]
absolutely, i got a new phone today and had to text everyone to end their sessions and start a new one to make new key exchanges... which was unnecessary work.

also, at any time today a man in the middle attack could have occurred and now any key verification i have done in the past is null and void because i have all new keys.

all private/public key encryption apps should have a clean export private keys option for migration or reflashing of phones.

right? :-)

**Comment by 2-4601** [comment]
In https://github.com/WhisperSystems/Signal-Android/issues/5931#issuecomment-265300716 moxie wrote:
> We do not use GitHub for discussion or Q&A.  Please do not open issues here just to ask questions or bump topics.  If an issue is locked, it's generally because there has been too much discussion or people have been too verbose.
> 
> For this issue, the work to be done is very straightforward:
> 
> 1) Make plaintext backup complete. It should export media, groups, preferences, block lists, etc... in addition to just text messages. All in a format compatible with SMS Backup & Restore.
> 
> 2) Wrap the now complete plaintext backup in an encrypted stream.
> 
> 3) Include the identity key in the encrypted stream.
> 
> I wish I had enough time to discuss at length why this is the only approach that will work for us, but sadly I don't have the time to do that for every issue.  I also wish I had enough time to do this work, along with all of the other open issues here, but I have to make choices.  If this is an issue that's important to you, **I think step 1 would make a great PR.**  Please see the mailing list or the online forums for further discussion, thanks.

**Comment by 2-4601** [comment]
24e573e537639f6f8ff40fd774cf9ff079bbacce
