### ISSUE TITLE
Disable secure messaging doesn't work

### ISSUE THREAD

**Issue by LikeHoo** [signalapp/Signal-Android#1709]
With the latest version 2.1.0 I noticed that disabling the secure messaging function from the padlock menu, doesn't have an effect. The message confirming that secure messaging is disabled is displayed both for me and the recipient, but the send button as well as the text bubbles still has the closen padlock icon.

**Comment by Chris-YBS** [comment]
I have a contact who has stopped using signal. Is there a way to revert conversations with this contact to SMS? I know I can select it for each message, but can I make it the default?
