### ISSUE TITLE
Reading "Encrypted" Messages without Password

### ISSUE THREAD

**Issue by Dedal0** [signalapp/Signal-Android#1716]
Since the last update of TextSecure (2.1.1) I noticed something "extrage" but I thought was an optical illusion at first but I confirmed this.

In the notification bar, you can see the message whithout encryption, in older versions the message was "Encrypted Message" now it showed the message in plain text.

![screenshot_2014-07-20-10-36-05](https://cloud.githubusercontent.com/assets/5331187/3637969/aee95298-102c-11e4-9924-3db2d86a97be.png)

I erased the content of the message but as you see is a long message, is not encrypted and was shown in plain text in the notification bar but when I clicked the message...

![screenshot_2014-07-20-10-36-31](https://cloud.githubusercontent.com/assets/5331187/3637963/0a3cffa6-102c-11e4-9f92-56dcd5fb5139.png)

It's suppose to be blocked by password... Hope you could fix this issue...

**Comment by EONEP77** [comment]
Encrypted text PIN / Password PIN / Password FTYPMP42ISOMMP42 MDATQ decrypt text taqkv0drh2zy0l0rm3rmhrguqf7a0izw89obsbpwpyzoec_e6bnzhlzvn_aok1b'kaarsf6hrzfbb vueyhjiktdo04cpirwdt5zzzzhwg5ouffsnakg2d4iqlehmvbusxcsa1gxundtizmxojv7h8kd dhsp1ldordco- 8UAKXBG8OYMGZ8KIMVUKSCJ0WC4W0P_6AH7 VBOKZOK4LXREHDZAI2-UXG2MFL NQJG2PI3GWZSOFELDRHIRAF2DCCDIHQM2DAWZ6MJAJQBGE7CBOQ9KSD4CQ4YIwNL5F-W3JZWMW alq8ejrnf_k3xdsguthic66sbawaqb1x0o9stoweucy-os2x7m_c16vhxe hdzvkf3b6sgd95gc_g FYC9ETNAM0SICKUJ2EUSADIHDCH8K 0KZVC3OQJI6CJIJKAPQW1DKLBRLUT5XEUSKQ25Q6VWGPMG4 pyjulg2dxo77cgjrhfli24oiartdr59dgde8fhpv4rqmjb6fn3s7nxnw0vuzviqqaie7l6ghd5go pxythnegfcnkudancecvvvygwvofxygygwizsdoe av7lk_dx2md3rnbeto_tkzkafe6pmjxqbfo 7aty91_n CLUTU3MVKKVDE2SEUZ9MXGKYXJ154QIH3FBE1BRSWZ2RV7JPILL9V8KJNPQ3NBYTRDPP0 F6i- LB4F0YOKMRKTQA2QRZMIFSP6WQFUNUJI5JMDD3ER4TFRTSGJKTJKL5L0O_TXU9XUYHQMDIT- A3E_USLQHMB5HO2JVMZZXRBYEOHHV6LPJ9KNSUVAHUCHTANTDC6-2YYZNVR 5AYHHA-9ZSFQ JMPS3NURCLJMDEW0WEV0TE6TGCQ0JRJA_94HOWYRC5J643NNUUPYLLXVUYEYSFWYII-VPIQXMO HQUSWBSGUGX_JZW_6DETJW_RWZ_X056IKL-DRK8ZX4YHIVUCU6NBXWULSZRS6NOFQRLTRWAOG6ZIU exf4yonzvmsgjewtcze0_alhqless2zscxlm-tr62d 1arwi3kzgvn6719animilzd4smedklejoa y- SID3HG8A3MIKHL0QCU-JSQJGVE5M5TT1DPWSBLX20EYIIOR07RL2-LFTAYSIGZ0H2OQAIR- GVQJXTBGIGDQLQLVTHQ-HZKCS891BZWSXNE-HD2QKVXSYV2KBYJO 88-ITMV4CANUY9USCHRM23Q1 mmpmzf1nmfzqkajok6gut zcc5rzloxywvht92asvrml7epo8xga9jtvgykuuhd-wgjsercbsvayu k- BF_KFVW9YLR6SFMUKQD5WJMAIEL5FBKGZ6C_QPPAKVANI9OOFBL9TJROHRBQUI2OSFZ51MUJN2 2h6ipeVhplQci7uzegnqg8nxt7alb45Qbja 6JTX7F15T6UHQYFYOSSTB0LCVEZOJEBLEBLE G9MKMRNKXKKIRWTNQAM6DROEHG1GKP38XB7FZAPPPPPPPE86D7FHGYIZ4MYX2SH7RM7U668TLJIIFWF 8YWKWNC9YIIDPGNX8YMVA2FGLHMVNH-NX-CNAH7UU2BDIY91GXOH8WT18AZLHXAMZDNNN2_M-Q 3RezyPS8XNQ NCJZMK-G2HQVYCOYHXBDBX-JGQ0YTLS6_VGUAUPLYU7R ICQUBLXA1LWPGQ_KL5_E T1GQE4VSPOGRXFAI1H19XJKPCD9MIVZLRXKBREGRIGJJTYCUQUE_QGHK5RHFGYSTLOBSG_COBOR4IE 6WOSLOXTBOKUTJMADXKRNJKGCZ783H5DPQB2QGRDU93YI9W23BVVJBJHLXM4XHNK7GAVAXHTAA DVSU1EGPMD108PMN57JBEIGYA0MVFVQWRX ILU8JFZ_MUQAD1MUH0M7ZGUSIJTKTV4YASW_CCVOC ZWAXXAN2V -JuiblsRofsw6Q-GJLJHLIL-2BQJUNUDG0GBEY2WLB9GIXITQJOQB1EZLK0JLMATAC AKZ7FUNCL- 2RQ154RCUFDD12A0_JR_8TARA817V3E_45-01TU0ASF2D4J2YGWQLA34AF9OEBRABB 4EFO3W_RBXMRW c3kipn52PE48Xhhmizmips_R2QYCJPAC284LJNWJ1HXO3Ozazuac9fgtej5ikx IMA4QAEDID_SHRNOSO64JWSJMWFGAMIM7PEBBOAD1LFJF7WM6WFP9J10VLTJIIFZVWKOHUN3F_WG Y7YC9WSIVPPTHZQR1UZ0YBAHD3MIFLHGAGIMAS_WTTKHGJJ_KSJOPS60FB3X1R_Y4NP KQ805XM r3tjwubj_sxnagwxakxh7tjljxkjssecymnruxoizihgbjg9_uwl4w94v26_gx68vugj1gy4gqm3 LCOBBIHAKZWCYFBV6ILEOBFOTENTYQSG2Y-Z5GNZVI_-IASGR-4WG7_YR -__ LKKRVH2C8G5D ZBRJB vlmgowhtjezndooyrdxfzbgf_rxfpnuauvt1j7r_ubm3weo6 pfjgawgj-ahplnanl_d2vtq4ymf7 BuA2S6GXHX1OPABRBK2MLM9SEHRXUPDYXWF6E_QG8-UPHMTPTFR2VHMWUBDECRVR_3REWAPPUV ZSZ3CC3TLXCBO7LOJE5SYC8ATHDHMPVTTMZE_12JKTL98EEKBB_QRWZT4RHP8K8HCTTIONBCGYU 6FBWXLFVZJLCEI0WBZ9iWTCFYB 1x8J7BSNK5X_RWUCHMAACJ7V1-HD9NGYJKEJVOBJTXBYXPVB6 IC6TCQSO1UCLYNQDCNGBKC3GMM_ESQ8OL7LQTAPIQLRNppNGSnthjkpKxJ0_DHSFGSGVPMDKC2QI iaonck4veu4o7ejjxzwfdfdauzo-8ipbburvzuyk3vwq5xiezr22 m0h8auwsou-oo7x1-9cc3zak jrb3rh ZFN1RG0UWIGMUGI9PEKLRB0M8RVMW4_LH-AN_PGLK2O138S0MSW2HEMYO4HOPQRYOQUUS qbcgtbljfgvvhn_n4j5i5tmh5flwhejrnr_3fjec2ws0-iaaw3- yfwljxm5sfpdoy2li9y2_sxng vxc0xtye9wmqb omyomjqqb1fqu8evjqf2z18_hlapey3eq6nj7e7swy0v3bz szoggezoef9k_gl MF5QX5WZWBFGZNUH6ZN2_4X0GT0V3ISPDXI9CVEIIN6PEG9GNN1S3443FP-NXMTOSV8QBHPIZDWV G6UQ0CA9LAQL9_RGNEBWO8POOFIJYDJAXMR1VPLZ5EPJKOTDW9FVGJ_EP2FXLMP_COAOPCFYPSE T_1DTY- BNBQHPR_FS3G7WYE3-X6CQPILFA3NNL8 =
