### ISSUE TITLE
Custom label value not showing up in list of TextSecure users

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#1732]
Setup:
1. Create a contact that has two mobile numbers (Mr. & Mrs. A for instance)
2. For each mobile number choose "Custom" and set the labels as Mr. for one and the other as Mrs.
3. Make sure at least one is a TextSecure user (both would apply here though too)
Steps to reproduce:
1. Create new conversation by tapping the "+" in the top right corner of TextSecure.
2. The TextSecure users are listed first and it doesn't show the Custom label value of Mr or Mrs.  Regular users work properly and show the custom label value.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
