### ISSUE TITLE
Asking for passphrase when unlocked

### ISSUE THREAD

**Issue by goshuar** [signalapp/Signal-Android#1755]
Lately, it seems that almost every time I open TextSecure, it asks me for my passphrase, even though the ongoing notification that it is unlocked is displaying, it is configured to never time out, and the phone has not been switched off nor the process manually killed.

Debug Log: http://hastebin.com/opatoyaruh

(Samsung Galaxy S3 Mini GT-I8190N running latest firmware from Vodafone, Android 4.1.2)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
