### ISSUE TITLE
TextSecure nuking encrypted SMS? WTF?!

### ISSUE THREAD

**Issue by SecUpwN** [signalapp/Signal-Android#1762]
Dear @moxie0, the first thing I do before having breakfast is having a coffee and reading the current security news. Today, this [article on Heise Security](http://heise.de/-2269353) was the worst news of the day: Are you honestly thinking that SMS are going to be replaced by data connections in the future and are thus thinking that nuking the **offline** SMS encryption feature (as discussed in #1737) is necessesary? Are you **FUCKING** serious? Excuse my cursing, but I simply cannot believe you seriously decided that!

Up until this point I've been a huge fan of the Whisper Systems products - be it RedPhone, TextSecure or anything else. I've been recommending TextSecure to all of my friends, recommended them to full erase WhatsApp, explained how to connect through TextSecure, even fiddled with their phones until it worked - and now you are blatantly coming along saying that it's "too much work and confusion" connecting people through exchanging keys? I really hope that mentioned article is wrong and all this is not true.

**Please rethink your decision.** If TextSecure will nuke offline SMS encryption (which always was the reason why people like me and my friends used it), I'm going to fully eliminate TextSecure and replace it with a smarter choice. And I will not only do that for my own phone, but for every phone if brought TextSecure to. To be honest, even thinking about it hurts! But deep within myself I simply cannot support a Project who eliminates its upmost important feature! Have you ever thought of the fact that there are countries out there who lack data connections due to poverty or war (and probably will continue to do so for the next few decades)? What about the people living in supressed countries with supressing governments?

I very much loved TextSecure, and while writing this, I still do. In the name of all security-enthusiasts and people ou there wondering how to continue or which App to switch to, I am asking you to **NOT** just close this Issue, but rather have a grown-up discussion here, which hopefully leads you  to the conclusion that offline SMS encryption is really important to keep.

**THANK YOU** for listening to the community and not just what the "trends" are going to be.

**Comment by E3V3A** [comment]
Very informative discussion. Thanks!

**Comment by SecUpwN** [comment]
@mejo- and @smarek, it appears that with yesterdays update TextSecure finally has no encryption any longer. Here is their [official statement](https://whispersystems.org/blog/goodbye-encrypted-sms/). This leaves all people without GooglePlay Services vulnerable since TextSecure is virtually useless for them. I filed a last attemnpt to complain with #2723, but it was closed quickly. Question: Which App do you use now?

**Comment by moxie0** [comment]
And here I was hoping that your "last attempt to complain" would actually be your last attempt.
