### ISSUE TITLE
Unified key verification

### ISSUE THREAD

**Issue by ncruces** [signalapp/Signal-Android#1818]
This is just an idea for your plans to merge RedPhone and TextSecure into Signal.

The way SAS and key continuity are used to verify identities in ZRTP are much more user friendly than identity verification in TextSecure (QR codes, etc).

By folding both apps together, as it seems to be your plan, maybe you could reuse identity verification from "RedPhone" for "TextSecure"?

**Comment by strugee** [comment]
@moxie0 is this still the plan? Glad I found this instead of filing a dupe :)
