### ISSUE TITLE
please add option to hear message tone while on a call 

### ISSUE THREAD

**Issue by Dennisl123** [signalapp/Signal-Android#1830]
hi, please add a option to hear message tone while on a call.  I can not get the vibrate to work and I'm blind so I can't see the notification in the status bar this would be useful.  Your app is extremely accessible to the blind and with Google's screen reader talk back.  I would be willing to donate if you add this option thank you.

**Comment by the-kyle** [comment]
I also need the ability to hear a message indicator while I'm talking on the phone. At this point, if I'm on the phone and I receive a text message, nothing is happening at all. I end up having to open TextSecure once I'm off the phone in order to know whether I received a message while I was talking. Most messaging applications, even if they don't play the set notification tone for a message while a phone call is active, do play some sort of beep or other indicator. This is the feature that is needed in TextSecure. Thanks much.

**Comment by Dennisl123** [comment]
I agree please allow for the playing of the message tone in the next 
version.  Thank you very much.

**Comment by rhodey** [comment]
just verified that this is still and issue, assigning to myself with the intent of determining steps to resolve and then maybe I'll open a pull or pass it off to whoever.

**Comment by Dennisl123** [comment]
I would really appreciate this not getting passed back and forth.  I 
would truly like to see it in the next version.  I would also like to 
have the ability to hide the contense of the message and the message 
sender in the notification bar.

**Comment by rhodey** [comment]
I figured out that you can reliably play notification sounds layered on top of a call in progress with the following code:

```java
Uri ringtone = Uri.parse(TextSecurePreferences.getNotificationRingtone(context));
Ringtone tone = RingtoneManager.getRingtone(context, ringtone);
tone.setStreamType(AudioManager.STREAM_VOICE_CALL);
tone.play();
```

note that `setStreamType()` was deprecated in API 21 but I found no alternatives that come anywhere near our `minSdkVersion 9`. we can use `TelephonyManager` to determine the call state and do this conditionally:

```java
TelephonyManager telephonyManager = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
if (telephonyManager.getCallState() != TelephonyManager.CALL_STATE_IDLE) {
  // whateva
}
```

the notification sound is layered on top of the audio so no pause or skip or anything like that but I'm still not sure if this should be enabled by default. @Dennisl123 is there any reason why a message tone is better than a vibrate while in call? my thought is that a vibrate would do less to interrupt the call in progress but your feedback on this would be great.

**Comment by agrajaghh** [comment]
just one thought: you might not be able to feel the vibration if the phone is on speaker

**Comment by Dennisl123** [comment]
then give me the option to turn notification while on a call on.  also 
please give me the option to hide message sender and message contense in 
the notification bar.  thank you for doing this I look forward to it in 
the next version.  I am willing to test builds prior to release.

**Comment by Dennisl123** [comment]
I can here the message tone I may not feel the phone vibrate.  I am 
blind I can't see the light flash so I really need the tone.

**Comment by Dennisl123** [comment]
here is a real simple solution have it enable message tone while on a 
call you check it it is on vibrate while on a call you as the user can 
have one or both of them checked and it will do what the user wants.

**Comment by rhodey** [comment]
thanks for the feedback @agrajaghh & @Dennisl123. @mcginty and I just tested this on Google Hangouts and WhatsApp, interestingly neither of them vibrate or play a message tone for new messages received while in call. kinda surprised me.

using the hardware volume buttons on my device I can turn the volume all the way town to vibrate only, in this setting the in call notification is silenced just like I would expect it to be while outside of a call. so that's good.

personally, I also would like to hear message tones (or vibrate) while in call but I think to be consistent we should also vibrate in call if TextSecure is set to vibrate out of call. anyone super opposed to this before I open a PR?

**Comment by agrajaghh** [comment]
Just one more thought: If you are on the phone and some guys start sending a lot of group messages it could be really annoying

**Comment by Dennisl123** [comment]
no I think it should as well.  will this be in the next version?  what 
about hiding message sender and   the  contents of the message in the 
notification bar?

**Comment by agrajaghh** [comment]
@Dennisl123 pls don't mix up different issues here

**Comment by mcginty** [comment]
@Dennisl123 this probably won't be in the next version, but we're interested in implementing it to help accessibility. There's a separate issue open about notification privacy settings.

**Comment by rhodey** [comment]
#1858 for notification privacy settings

**Comment by Dennisl123** [comment]
I would appreciate it as soon as you can.  this would help 
accessibility.  I also noticed some unlabeled buttons with talk back. 
Not having the privacy setting and the notification while on a call is 
preventing me from using it full time.  I hope this done soon.

**Comment by Dennisl123** [comment]
yes I would like to see the option to  not display the message sender or 
the message  contents in the notification bar.

**Comment by rhodey** [comment]
something else to note for anyone looking into this in the future, [NotificationCompat.Builder.setSound()](http://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setSound(android.net.Uri, int)) doesn't work with stream type `AudioManager.STREAM_VOICE_CALL`

**Comment by mcginty** [comment]
@Dennisl123 please open a new issue for the unlabeled buttons with a description of how to reproduce. Thanks.

**Comment by moxie0** [comment]
based on my experience with redphone, fucking with stream_voice_call will open up a world of pain

**Comment by rhodey** [comment]
ok, well I found no other ways of doing this and can't imagine a solution that wouldn't involve `AudioManager.STREAM_VOICE_CALL` so removing my assignment.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
