### ISSUE TITLE
all incoming sms being duplicated twice

### ISSUE THREAD

**Issue by wuftymerguftyguff** [signalapp/Signal-Android#1835]
Not sure what else to add.

never used to happen now happens for all recipients.

MOTO Razr MAXX CM11

**Comment by merkste** [comment]
I am experiencing the sms duplication behavior as well. Next time it happens, I'll past a debug log.

**Comment by merkste** [comment]
Here we go: https://gist.github.com/6058fd99eba800d73b33

**Comment by mantono** [comment]
I got the same (or very simiar) issue in 3.9.1
https://gist.github.com/anonymous/1196a00e1f95e4a15c36
I have been able to confirm this problem with multiple contacts, of which none are Signal users. I thought that upgrading to 3.9.1 would eliminate this issue (had it before as well), as #3525 was fixed, but that seems to be an unrelated issue.

Sorry I had to remove so much of the content from the screen shots (the second one has a password in it), but all the important data is still there. Some of the duplicates report the same sent time, but most of them don't.

![media-20160115t_cens](https://cloud.githubusercontent.com/assets/7093365/12368158/269a3a32-bbe9-11e5-9f28-da5594d2e8c8.png)
![media-20160115_cens](https://cloud.githubusercontent.com/assets/7093365/12368159/29f2d7a2-bbe9-11e5-9021-8f9aaea5bf02.png)

**Comment by McLoo** [comment]
Just received a duplicate signal message 
Same time stamp sent 
Same time stamp received 

Can't get the sender's log. Possible he's got bad signal (3g)

https://gist.github.com/b839b75c4939c71d53c5

**Comment by mantono** [comment]
**Signal 3.20.4**
https://gist.github.com/14ba54a6b47a8a61449b3ee0a01a1a7f

Sent time is the exact same one. Received time differs with 59 seconds, I had already read the first one when the second one came in.

Had this happen again more recently but did not save the log for that particular instance. All occurrences of this problem have been with SMS.

I know that this debug log is not from the most recent version, but as far as I can see, nothing in the most recent commits addresses this issue anyway.
