### ISSUE TITLE
Trapped in push message activation activity on failure

### ISSUE THREAD

**Issue by phipolis** [signalapp/Signal-Android#1855]
In the course of having difficulty getting push messages activated, I've uncovered some roughness with the error handling of the push message activation screen. When the "Verifying Number" screen displays the "Connectivity error" message, the back button does not work. The user must either click the edit button to try (and fail) again, or use the home button and open the App again to return to the main of TextSecure.

TextSecure 2.1.5 on Nexus 5 / CyanogenMod 11 / Android 4.4.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
