### ISSUE TITLE
Constantly detecting contact data changed, forcing refresh

### ISSUE THREAD

**Issue by m-r-h** [signalapp/Signal-Android#1859]
Strange little issue with the latest release, on Android 4.4.4

Looking at inbox it goes through a phase of constant refreshing for a minute or two - removing and re-adding contact info on received texts.  This happens fast enough that if I didn't know the contact names I'd probably not have time to read them. Then it'll be fine for a while, but come back in a few hours later to send a text and it will frequently start again.

Log is full of many
W/ConversationListActivity(13072): detected android contact data changed, refreshing cache

No changes to my apps, aside from auto-updates, no changes to contacts in weeks.

http://hastebin.com/sojeqatatu

**Comment by cmdavis4** [comment]
I know this is three years old at this point, but I continue to have this issue and it makes the app essentially unusable. Any fix in the works?

**Comment by moxie0** [comment]
@cmdavis4 Can you post a debug log?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
