### ISSUE TITLE
Feature Request: Option to strip unicode characters

### ISSUE THREAD

**Issue by merdox** [signalapp/Signal-Android#1864]
Recently I stopped using the stock CyanogenMod SMS app in favor of TextSecure. One thing that bothered me and continues to do so is that there is no option to strip all unicode characters. It would be really usefull to have this option for alphabets that use non-standard characters ( e.g Cyrillic, Greek ). This basically means swapping any non-standard character for its closest counterpart in the default GSM alphabet ( e.g. 'á' => 'a' ) allowing the use of 160 characters per SMS instead of 70. I consider it an essential feature especially if you are not online, as the same text in unicode might charge you more than double than it would on the default GSM alphabet.

I hope you implement this feature. Thanks and keep up the great work! :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
