### ISSUE TITLE
Import backup: Please tell me how old the backup is I am going to import

### ISSUE THREAD

**Issue by hacklschorsch** [signalapp/Signal-Android#1875]
I would like the 'import backup' screen, that asks me whether I want to continue ("... will completely replace your existing keys, preferences, and messages"), to tell me the date of the backup I am going to import.

(I mistakenly thought TS would automatically, regularly, create encrypted backups (like it should be, IMHO) and imported a backup from February -- half a year of messages and photos gone. Didn't know about #1631)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
