### ISSUE TITLE
Auto delete messages 

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-Android#1894]
Auto delete messages

I'd like to request that feature again because many people already requested it in some issues, but there were some privacy concerns and it could be interesting to talk about them and maybe, after finding a good solution, to implement the feature! ;)

So the idea is that messages automatically get deleted from the phones somehow. The  suggestion that someone could delete the message from all phones remotely let some privacy concerns come up as you should have full control about which messages get deleted from your phone and which do not...

Another idea (what I do appreciate) is the option to disable history like it's possible on hangouts (messages get deleted after some time automatically). For example messages get automatically deleted 24 hours after you read them. This could be an option in the conversation itself and you get the message "history turned off". Every participant should have the option to turn it off/on and it applies for all the participants. Like that there's no confusion and all people in the conversation should be happy with this solution and can turn it on/off like they want to do. The messages should of course have another color if history is turned off ;)

I do like this feature, the only privacy concern could be that you can still capture screenshots of it, but maybe taking screenshots could generally be disabled in the app or you get a notification that someone took a screenshot (what should be possible somehow because it works on snapchat e.g., too, right?). Do you think this would be possible or do you have some other concerns? Is such a function too hard to implement or would you even like that feature? :)

**Comment by BItim** [comment]
Is there any option to verify that the other user using the unmodified official version of Signal? By digital signature/checksum or something else?
