### ISSUE TITLE
Remove separating characters during scan to remove dupes in the contact list

### ISSUE THREAD

**Issue by oholika** [signalapp/Signal-Android#1946]
My adressbook is quite messed up and for a lot of contacs I have the same numer two or three times stored. TextSecure does a scan and shows each number only once as long as they are identical, in case they contain " " or "-" they will be displayed as dupes. I am recommending to ignore those characters in the scan.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
