### ISSUE TITLE
Feature Request: "Template" message list

### ISSUE THREAD

**Issue by NiccoloDeiConti** [signalapp/Signal-Android#195]
Would it be possible to add a list of pre-composed messages (called "templates" or "quick-text" in other clients) that could be filled with frequently-used replies?  Things like "I'm driving," "In a meeting," or custom replies that can be sent with just a couple of taps would greatly enhance (well, for me, at least) TS's suitability to take over as my sole SMS client.

**Comment by generalmanager** [comment]
Now that the quick reply functionality has been implemented, this could provide even more value, if it's accessible from the quick reply pulldown.

**Comment by freiheitner** [comment]
Removing myself from this discussion as I no longer have an Android device.

**Comment by micressor** [comment]
+1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
