### ISSUE TITLE
implement lock screen notification on really old devices

### ISSUE THREAD

**Issue by gumbost** [signalapp/Signal-Android#198]
Platform: 
Samsung s3 running stock 4.1.2

Request:
It would be very useful to have a notification on the locked screen. The stock messaging app puts a message icon on the lock screen that can be swiped. Swiping it send you to the unlock screen and after a successful login it takes you to the app/message. This type of notification is standard for the text app and phone. There may be other similar notifications but I don't use them to know.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
