### ISSUE TITLE
Plaintext export does not export protocol push/sms

### ISSUE THREAD

**Issue by grandchild** [signalapp/Signal-Android#1980]
Is this by design? Because I seem to remember that the export _did_ once carry that information, now the XMLBackupItem constructor is just fed a 0 for protocol.

I'd fix this, if I knew it wasn't removed by design. I couldn't readily find a commit that introduces/changes this.

If this is an attempt to abstract away from the whole protocol push/sms switcheroo, then I'd argue this is the wrong place to enforce it, since you're just throwing away data without any actual gain (it's saving the protocol='0' field anyway).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
