### ISSUE TITLE
Push receive issue after clearing Play Services Data. Other GCM dependent apps recover

### ISSUE THREAD

**Issue by anemes** [signalapp/Signal-Android#1987]
After a problem with localisation issues with google play, I followed some instructions by google to clear data on Google Play related services . 

After that point I stopped receiving push notifications from textsecure. I could still send however! 

I didn't make the connection for a bit, because other GCM reliant services continued to notify me. After uninstalling and reinstalling the app, everything worked as expected (with a new key).

[0] http://android.stackexchange.com/questions/42347/how-do-i-change-the-google-play-country

**Comment by midi** [comment]
@moxie
Any update?
No ability to backup and restore conversations is quite a deal breaker and makes it really hard to pitch it to friends and peers, who are used to having their conversations "in the cloud".

The silent failing is quite disastrous. I've run into this after changing devices, google accounts...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
