### ISSUE TITLE
Inability to receive mTAN SMS

### ISSUE THREAD

**Issue by boolean-is-null** [signalapp/Signal-Android#1996]
I am completely unable to receive mTAN SMS by my bank. TextSecure shows no error message nor a notification.
When I set the default messaging app to receive/send messages, then re-request my mTAN I receive it immediately. 

I'm willing to deliver debugging/additional information as good as I can, so I will recreate the scenario later and attach the debug log in this ticket.
My device - GalaxyS3; Android 4.4.4 Cyanogenmod11

**Comment by rhodey** [comment]
something tells me this might be related to #105, banks sometimes use the weird "flash" sms thing.

**Comment by philippelatulippe** [comment]
I had the same problem with an activation code from Deutsche Bank, using the Meine Karte app. The Sender was "DBMobile". Signal doesn't generate any log lines when it is received.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
