### ISSUE TITLE
use delivery receipts to show message received time for outgoing messages

### ISSUE THREAD

**Issue by exploide** [signalapp/Signal-Android#2055]
After long pressing on a message and selecting the info button, the message details are shown. This includes the sent and received times for incoming messages. For outgoing messages, in contrast, only one Sent/Received time is displayed, probably containing sent time.

Now that delivery receipts are implemented, it would be possible to display the received time for outgoing messages (by taking the sent time from the receipt). Or to make it more precise, let the receipt message piggybag the real received time.

This would make the user interface more consistent.

When this is rejected for some reasons, I suggest renaming the "Sent/Received" label for outgoing messages to "Sent" because this is what it really is about.

**Comment by mayerflash** [comment]
+1

**Comment by 4ntone** [comment]
+1   It would be very useful to know the time a person received a message. This is really missing in this great app.

**Comment by GfEW** [comment]
+1

**Comment by heyimgay** [comment]
Please don't comment if you don't have any new information.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
