### ISSUE TITLE
MMS messages do not display the Subject

### ISSUE THREAD

**Issue by pyther** [signalapp/Signal-Android#2089]
I don't believe this issue is provider specific. However some information about my device.
Network: ATT Prepaid/Gophone
Phone: Moto X GSM Unlocked (carrier)

Problem:
send an email message, with a subject, to 555XXXYYYY@mms.att.net

Actual Results:
textsecure displays the body of the email message, but does not display the subject

Expected Results:
textsecure should display the subject and body of the message

The stock messaging app solves this problem by adding a subject line.

Example

Email:

```
To: 555XXXYYYY@mms.att.net
Subject: A Test Message
Content Line 1
Content Line 2
Content Line 3
```

The stock messaging app would display

```
<Subject: A Test Message> -
Content Line 1
Content Line 2
Content Line 3
```

TextSecure Displays

```
Content Line 1
Content Line 2
Content Line 3
```

**Comment by mwsasser** [comment]
I've got the same problem with the subject not appearing.  However I use a Samsung Note 5 on Verizon.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
