### ISSUE TITLE
Problems with plaintext import

### ISSUE THREAD

**Issue by gusandrews** [signalapp/Signal-Android#2099]
I just moved to a new phone, and in doing the following steps found the errors mentioned and starred:

Make plaintext backup on old device (HTC Evo shift), to SD card
Copy to new device SD card (Kyocera Rise) using Mac desktop
Disconnect phone from Mac
Start TextSecure for the first time
Verify number
Import SMS already in Kyocera Rise’s native SMS system
Finish first-time setup
Import plaintext backup from SD card
*\* Got “Error importing backup!”
*\* Yet it seems to have imported everything anyway
*\* All timestamps in list view seem to be from moment of import, but in messages, they are from the original date of conversation.
*\* Because I did not realize it had imported, I imported it twice, and now all messages are duplicated
Tried to submit debug log
*\* Got “Could not grab logs from your device. You can still use ADB to submit debug logs instead.” 
*\* This was not enough information; I don’t know what ADB is.
Because of all duplicates, deleted TextSecure and started over.
*\* On importing this time, first import did not appear to import the plaintext file, but it also did not give me an error message. 
Second import did import it. 
Messages not duplicated this time.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
