### ISSUE TITLE
[UX] [security] Notification if plaintext message is received in encrypted conversation

### ISSUE THREAD

**Issue by generalmanager** [signalapp/Signal-Android#2114]
When somebody receives an unencrypted SMS from a contact with whom s/he previously communicated securely, this can have several reasons:
- The contact currently doesn't have internet connectivity/access to their phone for whatever reason
- The contact stopped using TextSecure permanently for whatever reason
- An attacker is trying to coerce an unencrypted response (requires user interaction), provoke metadata leakage, explain the error message of a following MITM attack, pretend the contact is still alive/free or similar.

In the first and second cases the recipient probably doesn't notice that the received message was unencrypted (which hints at the "no connectivity" of "no TS" scenarios) and will probably reply with an encrypted push message. This leads to the sender wondering why s/he doesn't get a response and the recipient thinking s/he already did respond. Which s/he did, but accidentally via the wrong channel.

In the third case the user should be warned about the general possibility of faked messages.

While explaining everything in extreme detail would be way too much, a short explanation should suffice.

What do you think about: 

> You received a plaintext SMS in an encrypted conversation. This could mean that $contact currently doesn't have access to their smartphone, has stopped using TextSecure or is beeing impersonated. 
> Do you want to answer via plaintext SMS?
> [  ] Don't show again for this contact _<-- checkbox_
> **[YES]** **[NO]** _<-- those are supposed to be buttons_

The checkbox to disable the warning lessens security but is probably neccessary to not put users off who regularly have mixed channel conversations.

**Comment by nrizzio** [comment]
This issue is obsolete and can be closed (encrypted SMS isn't something that's supported anymore).

**Comment by 2-4601** [comment]
Hmm... it doesn't seem that this would be dependent on the deprecated encrypted SMS feature. More like a feature request to get an explicit warning for receiving unencrypted SMS?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
