### ISSUE TITLE
Share multiple photos (files)

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2159]
Hi,
I love TextSecure but there's one thing that I find rather annoying. It often happens that I want to share some pics with someone (more than just one pic), and I have to select them one at a time instead of selecting them all and sending them all at once.
It would be cool if I could pick them from the gallery and then click "share" and send them without going through the procedure n times. I don't think this should be hard to implement and it would save so much time and improve usability greatly.
Thank you

**Comment by manhole11** [comment]
With 2.4.1 I can select more than one photo, but it just sends the first one I selected.....

**Comment by fajabird** [comment]
Many Miss this feature. Meanwhile I looked at different implementation:

- telegram seems to implement an own picker Dialog
- threema uses the same picker textsecure does but still allows to select more that one picture

I think textsecure should go the threema way.

**Comment by aurisnoctis** [comment]
At the moment (version 2.14.5), I cannot find a way to attach more than one picture in one go, for either of the two options:

1. `Gallery > <select image(s)> > Share` (TextSecure only shows up as sharing option if 1 image is selected, starting with two, the TextSecure sharing option disappears, only WhatsApp and a couple of others available)

2. `TextSecure > <some conversation> > Add attachment > Picture` (short or long press on a picture just attaches that picture instantly. No other pictures can be selected directly without going to the TextSecure menu again.)

Sorry if I still overlooked another option (?)

**Comment by cassy12** [comment]
I also miss this feature very much. Is it planed to implement this?

**Comment by mcginty** [comment]
On the roadmap

**Comment by piratenpanda** [comment]
Roadmap for which release? Would be really good to have and a missing feature compated to all other messengers

**Comment by damiencourousse** [comment]
+1 for this feature request.  

Thank you for this great app! :)

**Comment by sigenc** [comment]
pls don't bump

**Comment by Trolldemorted** [comment]
we might want to change the title to "change multiple files", though.

**Comment by chodid** [comment]
Just started a bounty on this. Join in and pledge! :)
https://www.bountysource.com/issues/6632903-share-multiple-photos-files

**Comment by p0ll3** [comment]
2 Years later, still one of the most wanted features.

**Comment by moxie0** [comment]
@p0ll3 Please read the contributing guidelines before posting again.

**Comment by gabrielsimoes** [comment]
I'm planning on tackle this issue. My idea is to send multiple URIs to the SlideDeck, instead of only one. And make an horizontal ListView or something.

**Comment by gabrielsimoes** [comment]
I plan on implementing two overlaping layouts: the RecyclerView for images, files and videos, and a SinalMapView for the map attachment. I decided to do this after having some problems with map image precaching.

**Comment by gabrielsimoes** [comment]
Alright, I have finished implementing it. I'll just wait for a maintainer to review the PR.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/share-multiple-photos-files/2544).
