### ISSUE TITLE
Allow setting status message for yourself and group chats.

### ISSUE THREAD

**Issue by entonjackson** [signalapp/Signal-Android#2197]
I have searched through all issues and was wondering i couldn't find this issue neither open nor closed.

The idea is to have a status message with text and/or emojis for yourself and group chats.
The problem for this ER is to display the message, because at the moment there's no space for it.
If we look at e.g.: Whatsapp, you can see the status in the

chat overview and in a
contacts view

Currently you can see the last message in the chat overview. I would rather like to see the status message of a user there instead. So I think it would be a smaller problem to achieve this.

To have a status message in the contacts view is a tougher job, because there is no contacts view yet. What we have now is the stock android contacts view you get, after clicking on the contacts avatar in the overview.
So this would be an entirely new view. Maybe this should be a new issue also... An own contacts view would be a nice improvement, because we could add other little informations there.

I think this little nice improvement would make it more fun to use TS.

**Comment by Evi1M4chine** [comment]
I suggested a rather different approach to `status` in a new issue:  #4766
It avoids the privacy concerns by doing it *right*. It also doesn’t force anyone to use it.
So it’s a zero compromise solution that has only advantages.
