### ISSUE TITLE
dark theme flashes white on screen changes

### ISSUE THREAD

**Issue by grrrrr** [signalapp/Signal-Android#220]
Nexus S running 4.1

What happens

Open TextSecure or change screens with dark mode theme enabled and at each screen the default white theme displays for a split second before the black theme loads.

What should happen

Users should only see dark theme when using TextSecure.

**Comment by heyimgay** [comment]
This is still the case after you change the theme to dark and then go from the preferences to the conversationlist but as far as i could find that is the only place that happens and the reverse does not happen (black flash when theme is set to light)
