### ISSUE TITLE
Delivery receipts not working for MMS to non-TextSecure users

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#2207]
I send MMS to some friends that do not use TextSecure.  They receive the picture fine but I never get a delivery receipt.

**Comment by McLoo** [comment]
Still happening. Message received, but no receipt. 
Didn't check code, but the setting for SMS report used on MMS too?

**Comment by smarek** [comment]
Also other way around it does not work either. No delivery report is generated for MMS when received on Signal (as default SMS app) from non-Signal sender. #5177

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
