### ISSUE TITLE
Intermittent Error Downloading Attachments

### ISSUE THREAD

**Issue by icyfyer** [signalapp/Signal-Android#2213]
First, the details:
Samsung SGH-M919 (JGEDLTEUE)
Cyanogenmod 11-20141112-SNAPSHOT-M12-JFLTE
TextSecure Version 2.3.3

Log: https://gist.github.com/29fc12c3b52e4358f76c

Problem: Sometimes when I someone sends me a photo attachment, it will not download. I am presented with a message notification, and there is a message bubble in the thread with a download button in it. If I tap the button, the bubble changes to "Connecting to MMS Server" stays for a few seconds, then changes back to a download button. There is no way to retrieve it. I have tried tapping it over and over again, restarting the phone, force-closing the app. Nothing works. 

The problem happens sporadically, and happens with both encrypted and unencrypted messages, sent from TS and other messengers, over push and SMS (MMS).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
