### ISSUE TITLE
MMS Download Failure (non-AT&T)

### ISSUE THREAD

**Issue by dawsome** [signalapp/Signal-Android#2220]
Whenever I receive a multimedia message, attempting to download results in displaying "Connecting to MMS server..." for a few seconds, then reverting back to the "Download" button. In other words, I can't download multimedia. When connected to Wi-Fi, the "Connecting to MMS server..." message stays on-screen for over a minute; with Wi-Fi off it only lasts ~10s. I've tried restarting the phone, enabling manual MMS, even uninstalling and reinstalling the app--no dice.

Device info: Motorola Droid Mini, stock Android 4.4.4, TextSecure 2.3.3

App state: Push registered, MMS preferences automatic (or manual: MMSC URL http://mms.vtext.com/servlets/mms), incoming and outgoing SMS fully enabled

Debug log: https://gist.github.com/aaf18938b646e5326500

I realize that there have been a couple threads about this in the past, but none of them match my issue exactly, and none of the proposed solutions have helped. Would really appreciate it if someone could take a look!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
