### ISSUE TITLE
Unable to sent anything. 

### ISSUE THREAD

**Issue by Dronte** [signalapp/Signal-Android#2261]
I've just installed TextSecure. It recieves all the messages - both secure and sms.
But sent messages are displayed as sent, but don't reach the addressee. 

Android 4.2 

I'm ready to provide additional information in a week or smth.

**Comment by kjeldsen-rasmus** [comment]
All of a sudden I cannot send or receive texts via TextSecure, the standard texting app works fine though.

I have tried disconneting from Orbot, and reinstalling TextSecure (and re-registering) but nothing seems to work.

Device : Sony Xperia Z1 Compact (D5503)
Android: cm_amami-userdebug 4.4.4 KTU84P b391725b68 test-keys
OS Host: cyanogenmod
App : TextSecure 2.3.3

https://gist.github.com/816dbcad71ad3b362d48

Kind regards,
Rasmus

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
