### ISSUE TITLE
[bug] Duplicate message preview shows ciphertext

### ISSUE THREAD

**Issue by generalmanager** [signalapp/Signal-Android#2269]
If the last received message was a "duplicate message" the message preview in the pulldown notification shows the ciphertext. 

What exactly is the reason of showing those messages at all? Do they occur when a message is transmitted by GCM over an unreliable connection? Why not silently drop them?

TS-Version: 2.3.3.

As this probably isn't device specific I won't add any further information. If those are needed, I'll gladly provide them tough.

**Comment by manhole11** [comment]
I'm getting a lot of duplicate messages lately, and what I've found out is that they are **NOT** duplicate at all. They are just like all the other messages, but for some reason are not shown. I'm missing several messages for this reason.
Debug log here: https://gist.github.com/anonymous/6f74127e0d78748ad35e

**Comment by KommX** [comment]
A friend of mine also has this problem sometimes with messages I was sending him.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
