### ISSUE TITLE
Desktop client

### ISSUE THREAD

**Issue by joebandenburg** [signalapp/Signal-Android#2275]
I know this is a huge feature request and my intention is to begin the discussion.

I've just started using TextSecure as a secure replacement for Google Hangouts. I use Hangouts both on my Android phone and on the desktop, so that I can switch to a full size keyboard when I am at home or work. This is a great feature that I'd love to see implemented by a secure messaging system.

My suspicion is that multiple clients acting as the same identity (and hence all being able to read the same chat history and send messages) is either impossible or very difficult to achieve in a client-side encryption model. Is this true?

Do you have any intention to support such a feature in the short or long term?

**Comment by partik1** [comment]
I wonder if there's any alternative true client (for linux) and not a shitty chrome-app (of all browsers..). Not even firefox..

If there's anyone making a linux client, please let me know.
