### ISSUE TITLE
Passphrase keeps timing out randomly

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2328]
~~edited... no point in contributing to this project... waste of time~~ :see_no_evil: 

passphrase randomly times out earlier than expected.

**Comment by zmanian** [comment]
I've been seeing something like this on my Lollipop Nexus 5.

Set a long passphrase duration like 3-4 hours.

Passphrase will need to be re-entered after less than an hour.

My working hypothesis has been the [memory leak](https://code.google.com/p/android/issues/detail?id=79729) in Lollipop is causing the persistent notification to be killed early and wiping the passphrase from memory.... It is interesting that you are seeing this on Android 4.4.2 which does not have have the memory leak issue as far as I know.

**Comment by mcginty** [comment]
If you see this happening, try gathering a logcat and see if we can work out whether Android is killing the service for memory reasons, etc. Lollipop also has some better memory diagnostics so we may be able to look at how much contention there is during the times when you have to enter your passphrase early as well.

**Comment by nwdev** [comment]
@mcginty So I should submit the debug log right after I notice it happens? It happened to my this morning, would submitting a log now still be useful? If so, here it is. https://gist.github.com/anonymous/873033900f3ea96d179a

**Comment by kcconlin9319** [comment]
This just started happening to me today with version 2.4.1 (Nexus 5, Lollipop 5.0.1, rooted).  I originally didn't have timeout enabled, but this morning after the 2.4.1 update the app was timing out every 10-15 minutes or so anyway.  Since then I've turned on timeouts and set the interval to 599 minutes, and I haven't had a timeout since.  If it happens again I'll submit a debug log.

**Comment by zmanian** [comment]
I've been able to reproduce this twice today. Nexus 5 , Lollipop, unrooted.

After the phone have been on for about 48 hrs, the persistent notifications start dying randomly and taking their app processes with them.

Here is the TS log immediately after the starting the app up again.
https://gist.github.com/anonymous/79c88b9bc342f20009f3

**Comment by nwdev** [comment]
Happened to me twice this morning within 20 minutes or so. Here is the debug log.
https://gist.github.com/73f078778f54e8e2ea7e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
