### ISSUE TITLE
Hyperlink is not clickable

### ISSUE THREAD

**Issue by peskykid** [signalapp/Signal-Android#2352]
Tried sending the new "invite" message.. The link is not clickable.

**Comment by moxie0** [comment]
In the compose text or the sent message view?

**Comment by McLoo** [comment]
Sent message bubble. Address isn't linkifyable. Not enough www or .com

**Comment by peskykid** [comment]
links can not be clicked on senders or recipients device.. Compose & sent view both have issue

Tested with Gs4 & Gs3

**Comment by GAS85** [comment]
I believe this is an old one issue or similar to #1482

**Comment by JavaJens** [comment]
I have the same issue, but I believe it to be an issue of ".link" and autoLink as other TLDs like ".com" work just fine.
I have a KitKat device, so it might be worth considering another TLD, as most devices <=KitKat (what about iOS?) will have the same problem.

**Comment by 2-4601** [comment]
Just tested with an ICS device and Signal 3.7.2.
`.link` TLD is not linkified.
`.com` on the other hand works.

**Comment by heyimgay** [comment]
#4206 might provide insight.

**Comment by dolanor** [comment]
I still have that problem (Samsung Galaxy S5, KitKat)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
