### ISSUE TITLE
message ends up in wrong thread

### ISSUE THREAD

**Issue by pinkwerther** [signalapp/Signal-Android#2354]
I was writing texts to in different threads, switching to the other thread while one message was sent (possibly because I received a message there) and the message ended up in the wrong thread. It was not sent to that person, but I don't knew yet whether it was sent to the right person either.

**Comment by pinkwerther** [comment]
Setup: sms message writing to one person. Send. Switch to thread of another person. Receive a message there. On my device the first message appears in the thread of the second person. Don't know if I can reproduce this yet.

**Comment by rhodey** [comment]
@pinkwerther I think the behavior you experienced can be described by #2262. if you disagree and are able to provide further information or a debug log I'll reopen this and look into it, thanks!

**Comment by pinkwerther** [comment]
@rhodey if you say so... i never delete any threads though... also i just had another look, after several reboots and that kind in the meantime the message appears still in the wrong thread only. on that day i used to communicate with both contacts frequently. i'm not sure i understand how you might reuse threads in a way that would show the described behaviour here. however the issue has not occured again, but then again i don't text often or much.

**Comment by rhodey** [comment]
@pinkwerther if you never delete threads then my hypothesis may be incorrect, I'll reopen. can you long click on this weird message, tap the message details icon (the 'i' thing), and let us know what it says? is the recipient who you expect?

**Comment by pinkwerther** [comment]
@rhodey not sure what to expect... the recipient (from the 'i' thing) is the person the message was intended for. in this sense it is who i expected to send the message to. but since it's in the thread of another person it's not really what one might expect when looking at the message details.

**Comment by McLoo** [comment]
@pinkwerther have you used the import and export functions (some time) before that iddue occurred the first time?

**Comment by pinkwerther** [comment]
@McLoo it's occured only once so far. And yes, I've used the import export functions, but more likely middle of December (at least it was there that I last used the other texting program), while the issue was middle of January.

**Comment by legatek** [comment]
I've encountered a similar problem. There's a non-contact thread, labeled '1', where received MMS's sometimes go. It hasn't happened in a while so I haven't been able to pull a debug log.

**Comment by Davioli** [comment]
I can confirm this.
About two months ago, I replied to a friend's message, and it ended up in a group conversation I viewed after - bit of an embarassing moment.
First I thought, it was simply my mistake, but now it happened to a friend as well.
They wanted to send a message to me, but had a bad phone signal.
Then they continued another conversation, and the message ended up there.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
