### ISSUE TITLE
Double login screens

### ISSUE THREAD

**Issue by plaguedemons** [signalapp/Signal-Android#2360]
I get double login requests from text Secure every time. I am using v 2.4.2 on a Galexy Note 3

**Comment by mindlessroman** [comment]
Happened to me just this evening. https://gist.github.com/anonymous/73173a0dcf89b624cc56

**Comment by gabrielbauman** [comment]
Happens twice a day. I find that if I sign in to the first login screen, I can press Back at the second one and the app is unlocked. 

Also the Textsecure login will pop up while I am doing something else in another app seemingly at random.

https://gist.github.com/anonymous/0cff7221933d2134fc17

**Comment by gabrielbauman** [comment]
This should be reopened. It happens in the current version of the app.

**Comment by gabrielbauman** [comment]
Another one just now. Turned screen on to a double unlock screen:

https://gist.github.com/dad5f0a54e9e40cb80ed

**Comment by McLoo** [comment]
Just had this. When I opened TS first time this morning. Log is similar to @gabrielbauman's.
Also on CM12.
Wasn't able to force this.

**Comment by shaaati** [comment]
Additional notice: For me, this does **not** happen everytime when I unlock TS. So far I cannot determine any regularity. It seems to happen quite randomly.

**Comment by gabrielbauman** [comment]
@moxie0 Both bugs that deal with this ongoing issue are closed. Could you please reopen one of them?

**Comment by mcginty** [comment]
This issue is open...

**Comment by gabrielbauman** [comment]
Still an issue in 2.6.4 from the Play Store. 

With the app locked, launch TextSecure. A login screen appears. Press the back button. A second login screen appears. Press the back button again and you are back to the Android Launcher. 

Entering a password on the first login screen unlocks the app, but then the second login appears even though the app is actually unlocked. Pressing the back button on the second screen after entering the password on the first takes you to your messages. 

It's like the app is pushing two login activities onto the history stack and you have to deal with both of them before you get to see your messages. 

Also, after the lock timeout occurs the login activity pops up and interrupts whatever I am doing on the phone. Every time.

**Comment by mcginty** [comment]
We're aware of the issue, we'll close it when it's resolved and any related PRs will mention this. Thanks.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
