### ISSUE TITLE
Make "unread badge" optional

### ISSUE THREAD

**Issue by IBBoard** [signalapp/Signal-Android#2366]
Having recently updated TextSecure and just received my first SMS for a while, I noticed that TextSecure has taken to putting an "unread count" badge on the icon.

Having read the ticket then I understand that some people want it, but I don't have an unread count on any of my other icons, and it looks ugly and out of place. Besides which, my phone already beeps when I get a message, and I have the notification on my lock screen (with info hidden), and the TextSecure icon is already in the top bar once I unlock and have a new message (the same as I have for emails and other messages/notifications from other apps).

Can the "unread badge" be made optional?

**Comment by manhole11** [comment]
I like the idea of having a badge counting the unread messages, but I agree with you, it is ugly. I'd like to hide it too because it's just too hideous to sit on my home screen.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
