### ISSUE TITLE
Messages get stuck as "Decrypting, please wait..."

### ISSUE THREAD

**Issue by Bujiraso** [signalapp/Signal-Android#240]
Hi, I have noticed an issue where a message is received and it says "Decrypting, please wait..."and it doesn't decrypt until you lock and unlock the database.

This occurred for me when I first turned on the phone (mine is a SGS2, i9100m) and the database was locked but I received new messages. The TextSecure app was also updating (either in progress, or just finished, I didn't notice which) if that's relevant.

Maybe a feature to individually re-decrypt messages that are stuck would help?
Thanks

**Comment by patcon** [comment]
This seems to only affect SMS/MMS when they are candidates for encryption, which [is deprecated](https://whispersystems.org/blog/goodbye-encrypted-sms/).

This can probably be closed.

**Comment by itys** [comment]
Issue persists, request this not be closed as TextSecure is the default SMS app for most TextSecure / Signal users. While SMS encryption may be deprecated, TS still needs to be able to properly handle unencrypted SMS.

**Scenario**
* Phone on airplane mode
* Normal, non TextSecure SMS' sent and cached by the network
* SMS' received when phone set out of airplane mode
* Several "Decrypting, please wait..." messages unable to be read

**Troubleshooting steps taken**
* Lock TextSecure and unlock
* Reboot device
* Run updates to ensure latest version of TextSecure

Debug log [submitted](https://gist.github.com/19c5338483a72ced2ebe)

**Comment by rhodey** [comment]
@itys you're saying that before the airplane mode changes you had no `Decrypting, please wait...` messages, and then after disabling airplane mode you received SMS messages and had multiple `Decrypting, please wait...` messages? Are there one per message? Is this is one or multiple conversations?

that would be super surprising as we've heard of nothing like this months, possibly years.

**Comment by itys** [comment]
@rhodey Multiple per message and multiple conversations as shown in the debug log. I appreciate your cautious doubt and surprise - however, yes, this has happened a couple times over the past month.

**Comment by arleslie** [comment]
Just had this happen on v3.18.3.
I opened the app as the notification appeared even though the message was sent minutes before.
Locking and unlocking the app fixed it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
