### ISSUE TITLE
UX: Font Weight Header

### ISSUE THREAD

**Issue by smonsays** [signalapp/Signal-Android#2440]
Is there anyone else who thinks the header would look cleaner with normal font weight?

**Comment by jeremymasters** [comment]
When you say "header" I'm not exactly sure what you mean.

**Comment by smonsays** [comment]
Sorry, TextSecure is supressing screenshots by default and I don't have a computer with adb at my disposal right now:
I mean the letters saying "TextSecure" on the top in the conversation overview.

**Comment by jeremymasters** [comment]
Was just looking at this again.  I have been using the dark theme which doesn't have those letters stand out as much to me as when I switch to the light theme.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
