### ISSUE TITLE
Auto retrieve mms

### ISSUE THREAD

**Issue by huxys** [signalapp/Signal-Android#2449]
Hi,

I've notice that if my mobile data is turned off and I receive a MMS, textsecure wont turn the data on to receive the mms like the other apps e.g. hangouts, textra, etc...

If I've mobile data off but wi-fi on, textsecure will turn the mobille data on to receive the MMS.

Is it possible to make that possible, since it already works in the situation above?

Thanks

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
