### ISSUE TITLE
UI: Header hides text input on small displays / invisible text input

### ISSUE THREAD

**Issue by grandchild** [signalapp/Signal-Android#2491]
(I am not sure if this is a dupe, seemed like it would've been reported already. I couldn't readily find an issue about this though...)

The new UI with the header appearing in landscape mode as well hides the text input on smaller phones.
![textsecure-2015-02-17-192623](https://cloud.githubusercontent.com/assets/770029/6234962/15c96a26-b6df-11e4-99e0-e0b39578fed6.png)
Maybe Textsecure has to go back to the old landscape text input mode, or conditionally check for screen height and decide...

**Comment by mcginty** [comment]
Thanks for the issue and screenshot, @grandchild! Yeah sounds like we should either fallback to the old input mode or hide the ActionBar if there's limited screen space.

**Comment by Txtscr** [comment]
When will this issue be closed. I had this problem on my 3 inch phone but another 3.7 inch phone the same problem occurs.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
