### ISSUE TITLE
TS crashes right after password input

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#2518]
The app crashes after hitting in unlock - both, keyboard and arrow button. Crash log is here:
https://gist.github.com/ad01528f64cf2522cba1
I basically cannot access any messages anymore, which is pretty bad. I'd be happy to get help how to a) rescue my messages and b) get TS working again.

**Comment by moxie0** [comment]
Hmm, looks like a bad attachment.  Shouldn't crash, but here's a quick
workaround for you:

1) Put your device into airplane mode (both wifi and mobile disabled).

2) Open TS.  At this point it shouldn't crash.

3) Delete the offending attachment (should show as an incoming message
that's downloading).



On 02/23/2015 12:21 PM, merkste wrote:
> The app crashes after hitting in unlock - both, keyboard and arrow
> button. Crash log is here:
> https://gist.github.com/ad01528f64cf2522cba1
> I basically cannot access any messages anymore, which is pretty bad. I'd
> be happy to get help how to a) rescue my messages and b) get TS working
> again.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2518>.
> 

-- 
http://www.thoughtcrime.org

**Comment by merkste** [comment]
Thanks, that worked partly. TS starts but I dont see any incoming message/attachment. Any chance to figure out which one causes the trouble? TS crashes again as soon as I turn off airplane mode.
However, I got an attachment earlier this day that never loaded. I deleted the message after a while and the other guy sent it again successfully. I don't know whether this is related.

**Comment by merkste** [comment]
So far I was able to create a PlainText-Backup. But is there a way to preserve attached images as well?
Or asking the other way around, will this issue be resolved with a dot release soon?

**Comment by agrajaghh** [comment]
AFAIK, the backup is currently just exporting the messages without attachments

**Comment by merkste** [comment]
@agrajaghh Is there any hope for another solution/fix? I checked all my threads so far but found no pending images for the last days. Do you think it is related to the message with the pending image I've deleted?
OT: This is another case where encrypted SMS come in handy. They still work.

**Comment by agrajaghh** [comment]
@merkste you could fiddle around with the sqlite database manually, but that could make things worse as well... 

I guess the core developers will fix this crash, but I can't (and they probably cant either :wink:) tell you when this will be..

**Comment by moxie0** [comment]
@merkste If you delete the offending message (it has to be a recent message from a textsecure user), this crash will resolve itself.

We can put in a fix for the crash bug, but you won't get that until the next release (2.6.0), which still has a little ways to go (you can watch the milestones here if you like).

**Comment by merkste** [comment]
W/InputEventReceiver(22905): Attempted to finish an input event but the input event receiver has already been disposed.
W/KeyCachingService(22905): Decrementing activity count...
W/KeyCachingService(22905): Incrementing activity count...
W/KeyCachingService(22905): Decrementing activity count...


Am 25. Februar 2015 00:08:39 MEZ, schrieb Moxie Marlinspike <notifications@github.com>:

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
