### ISSUE TITLE
Missing vibration in Android Wear

### ISSUE THREAD

**Issue by maxauvy** [signalapp/Signal-Android#2524]
When I receive a message in TS, the phone pushes the notification to the smartwatch, whici will vibrate and show the message.

This feature works fine with unencrypted messages. But if a contact also uses TS to send encrypted messages, the notification will still be pushed to the watch, but without vibration and so on.

Maybe just a few things to add to te code base ?

If you need some testing or other informations, please ask! :)

**Comment by JavaJens** [comment]
IIRC none of the developers has a smart watch, so I think support for that is a little ways done the line.

**Comment by jeremymasters** [comment]
I'm sure they would take smart watch donations. ;)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
