### ISSUE TITLE
1 card per message in Android Wear

### ISSUE THREAD

**Issue by maxauvy** [signalapp/Signal-Android#2525]
When I receive a message in TS, a notification is sent to the smartwatch, with the content of the message.

If I receive another SMS from the same contact, the content of the second message is added to the first one, so that's OK.

But if I receive another message from a different contact, TS shows something like "X messages", with only the name of each contact. So I can't read the content on the watch, I have to take out my phone and open TS.

Is it possible to add a feature with something like 1 notification / card per contact ?

If I can help, don't hesitate :)

**Comment by makubi** [comment]
Hi,

@dr03lf and I are currently working on this.

**Comment by z0l2k** [comment]
Is this still being worked on? Its the main bug preventing me from using Signal as my main sms app.

**Comment by agrajaghh** [comment]
@z0l2k Unfortunately bumping or +1's don't help fixing this issue (they just create extra email notifications for the devs). Please only post if you have new information that will help to solve the issue. Thanks

**Comment by lolstarz** [comment]
I'm happy to take this up, since it affects me too :). I propose a notification preference to disable the "summary notification" -- does that sound acceptable?

**Comment by 2-4601** [comment]
@lolstarz Thanks for your let's fix this attitude :)
You might want to check out #4488 and see why that's on hold.
Also https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md has some info on contributions.

**Comment by lolstarz** [comment]
Thanks for the link, I have been searching through issues for dupilicates/related tickets but not having much success. I see and appreciate the "don't add more options" strategy in the contrib.md. I will use the code from that PR for now on my device and see if in anything changes wrt strategy to fix the issue.

**Comment by jpph** [comment]
Please notice the smssecure which is forked from TextSecure doesn't have this issue. You might want to check how they fixed this. For now I have replaced ts with smssecure as default sms app. Works very well with my pebble

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
