### ISSUE TITLE
 Feature: send schedule

### ISSUE THREAD

**Issue by DaveQB** [signalapp/Signal-Android#253]
The default SMS app on Samsung at least show you to set a time the SMS is to be sent. I use this feature a lot, so need to revert back to the default app to send these messages. Would be great to have this feature added.

Thanks.

**Comment by AltJ** [comment]
+1
This is one feature that is preventing me from using textsecure as my default messaging app.

**Comment by alextpedro** [comment]
I'm interested in this feature as well.

**Comment by williscool** [comment]
+1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
