### ISSUE TITLE
MMS are from "unknown"

### ISSUE THREAD

**Issue by maxauvy** [signalapp/Signal-Android#2532]
When I receive some MMS from my contacts, either encrypted or not, they appear in the good conversation thread, but without the contact picture. Moreover, the notification indicates a message from "Unknown". SMS are OK, though.

Is there a way to fix this, as it's quite annoying ?

TextSecure 2.5.3 / LG G3 (d855) / CyanogenMod 12
App state: Push registered, incoming SMS enabled (default app), outgoing SMS enabled

**Comment by rhodey** [comment]
@maxauvy can you post a debug log from a time span where you receive an MMS like this and experience this behavior?

I'm interested to see if this logging statement shows up https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/recipients/RecipientFactory.java#L87

**Comment by maxauvy** [comment]
@rhodey of course. The "thing" just happened, so here is a debug log : 
http://p.open-freax.fr/ac3e63

If I can do anything else to help, please let me know :)

**Comment by rhodey** [comment]
this may be related to #2874, see [my comment for context](https://github.com/WhisperSystems/TextSecure/issues/2874#issuecomment-94598217)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
