### ISSUE TITLE
Feature Request - Block Texts

### ISSUE THREAD

**Issue by SirGrant** [signalapp/Signal-Android#26]
It would be a nice feature to be able to block texts.  This could be because someone is sending you spam SMS or maybe you have a person who is bothering you.  I think you should be able to instruct the program to reject texts from certain numbers.

**Comment by ulysseoriol** [comment]
Would it be possible to re-open this feature request, I can't find the source but I think as of Android 5.0 text messages can only be blocked through the main text messaging app.

**Comment by Zebrazilla** [comment]
I feel this would be a very useful features as well and would +1 such an initiative of reopening this.

**Comment by mcr** [comment]
three spam sms today...

**Comment by haffenloher** [comment]
@mcr blocking a number is done through the conversation settings (has been supported for a while, see #3378)
