### ISSUE TITLE
Minor theme inconsistency

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2625]
When changing the theme to 'Dark' before registering a phone number, and then going into settings and pressing 'Push messages' (the first option), a window with the heading 'Connect With TextSecure' opens which appears to use the default light theme, which appears to be inconsistent with the rest of the app.

This also appears to be an issue for the 'Change passphrase' window found under Settings / App protection / Enable Passphrase and the 'Submit debug logs' window under advanced settings.

Saumsung SGH-T399
Android 4.2.2
Textsecure 2.6.1

**Comment by Jens14L** [comment]
The TextSecure logo should be also blue and the background could be also black. I’m using TextSecure 2.5.3 and the dark theme.

![textsecure_login](https://cloud.githubusercontent.com/assets/11010835/6548067/6a35fb98-c5ed-11e4-9925-22990da23cf6.png)

**Comment by mcginty** [comment]
@Jens14L that's an outdated TextSecure, please update.

**Comment by Jens14L** [comment]
2.5.3 is the current PlayStore version which Google displays to me. Is it a staged rollout?

**Comment by mcginty** [comment]
Gotcha, yeah wait for the upcoming update. The watermark is now blue.

**Comment by shaaati** [comment]
Another theming issue in version 2.6.2: The redesigned message detail dialog always uses the light theme instead of adapting to the user setting.

**Comment by agrajaghh** [comment]
PR to fix the message detail activity: #2640 and the passphrase prompt: #2627

**Comment by rhodey** [comment]
partially resolved by 257660200aad91b9696aba45b20f67b2d769f8ed

**Comment by riyapenn** [comment]
#3281 has updated details for dark theme improvement

**Comment by FeuRenard** [comment]
This issue more precisely:
Make `LogSubmitActivity` and the registration process (`RegistrationActivity` and `RegistrationProgress`) adapt to dark theme.

**Comment by FeuRenard** [comment]
I am working on this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
