### ISSUE TITLE
Message Details may show wrong recipients

### ISSUE THREAD

**Issue by agrajaghh** [signalapp/Signal-Android#2642]
If you add someone to a group the message details view is showing the new group member as a recipient for past messages

**Comment by mcginty** [comment]
Yes, unfortunately we don't store per-message group contexts as of now. This is probably a database change we would want to consider for the future, though, alongside a list of recipients that gave back delivery receipts rather than just a count.

**Comment by agrajaghh** [comment]
yeah, I thought so. What do you think about not showing the recipients for group messages at all (ofc just until these db changes are in)? I think showing false information is worse than not showing this at all. It would be still possible to see the group members anyway...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
