### ISSUE TITLE
ic_send asset is imprecise

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#2656]
The edge of the arrow above the lock could be improved.

![img_medium_8343925](https://cloud.githubusercontent.com/assets/984047/6630952/330613e6-c8f5-11e4-9199-e20f9ec6c0e5.png)

**Comment by mcginty** [comment]
Do you mean the whitespace isn't perfectly rounded?

**Comment by justin-** [comment]
Yeah. Not exactly a showstopper, I know!

**Comment by mcginty** [comment]
A valid issue nonetheless. Can tackle this when I make the icon more circular too :P.

**Comment by michalmsk9** [comment]
I think this issue should be now resolved. In my pull request, I included 'fixed' icon files for each size class. I also included the original size file, which you can use for any other purpose.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
