### ISSUE TITLE
Feature Request - Google Voice text messaging integration

### ISSUE THREAD

**Issue by epowell** [signalapp/Signal-Android#27]
I occasionally use Google Voice (GV) for texts, or texts are sent to my GV number. Those texts are received by the GV app directly. It would be nice to be able to encrypt/decrypt messages sent through GV. Local storage should be encrypted, but most of the messages would be stored (encrypted) in GV instead.

(This is likely a large undertaking. If I have the time, I may try to tackle this on my fork.)

**Comment by patcon** [comment]
For anyone further who comes across this, "wifi calling" setting allows TextSecure to work reliably with the Voice+ (voiceplus) app that come with CM11. (See #2698 for context)

**Comment by chughes87** [comment]
Is this any more possible these days? Is there any intention to make this happen anytime soon? I keep wanting this feature

**Comment by Fuzion24** [comment]
Signal no longer falls back to sending encrypted messages over SMS.  You can, however, still register Signal using your Google voice phone number.  The SMS gateway they use doesn't seem to like GV numbers, but if you wait it out and receive a call for number verification, you're golden.

**Comment by justingoldberg** [comment]
What about using the Google voice feature that forwards sms to your real number? This would help those using the new Haven app with signal on a non activated or wifi only device.

Edit: ok, I just answered my own question. The non activated device would not get those messages.
