### ISSUE TITLE
Audio mp4 file needs to be added as video

### ISSUE THREAD

**Issue by oholika** [signalapp/Signal-Android#2716]
I created a audio file and wanted to add it to my conversation, but I could not browse it. After checking the file type (mp4) I tried to add it as video and it worked. IMO a seperation between Video and Audio is not really needed at all... 
btw, are you planning in app shortcuts for audio recording or photos like you do for the barcode scanner?

**Comment by agrajaghh** [comment]
see #520 for the second part

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
