### ISSUE TITLE
Saving Attachments - where do they go?

### ISSUE THREAD

**Issue by coofercat** [signalapp/Signal-Android#276]
This is hopefully a daft question, but I can't find the answer anywhere.

I've received a nice picture via MMS into TextSecure 0.9.9.7. It looks okay in the message thread, and clicking it gives me the warning about needing to decrypt it, but then it loads perfectly into my image viewer. If I tap+hold the image, I'm then warned about needing to decrypt it to put it on the external SD card, it then takes maybe half a second while it says "Saving attachment...", and then "Success" flashes up. Despite all of this, I can't find the attachment anywhere on my phone :-( (I've used ES File Explorer to search for various filenames, but to no avail).

I had a look in the source code; it looks like it's saving to Environment.getExternalStorageDirectory(), but none of the obvious locations seem to have the picture in them.

Any idea where attachments end up?

(If it matters, I'm using a Samsung Galaxy S2 GT-I9100 running Jellybean 4.1.2).

**Comment by thebeezle** [comment]
Uh, I recorded an audio file via the Signal app and saved it .... can't figure out for the live of me where it went or which folder it was saved in.  Thanks for the Microsoft style app.

**Comment by thebeezle** [comment]
Recorded an audio MMS via signal and sent to an iphone. they couldn't play it.   What is the point?
