### ISSUE TITLE
Make disabling passphrase password protected

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2761]
Textsecure 2.7.1

Currently, changing the passphrase requires entering the old passphrase. This is presumably to prevent a third party from changing the passphrase when the app is unlocked. However, nothing stops someone from just disabling the passphrase first (which is not passphrase protected), and then creating a new passphrase. Requiring the user to enter their passphrase to change the passphrase doesn't seem to add any security. 

I'd suggest requiring the user to enter their passphrase to remove the passphrase to fix this vulnerability.

**Comment by nwdev** [comment]
+1

**Comment by Valodim** [comment]
I just stumbled upon this and it really seems weird. Maybe don't ask for the passphrase to change it, instead? It can only be done in the unlocked state anyways, and it's not like *changing* the passphrase is an attack scenario for anything other than trolling the user :)

**Comment by dkg** [comment]
I prefer the original proposal (requiring the passphrase to remove it) over the one proposed by @Valodim.  I prefer it for three reasons:

 * removing the app lock can be done in seconds (e.g. while someone has stepped away from their phone briefly), and can be the starting point for a larger future attack.
 * removing the app lock is hard to notice -- it'll only be noticed when the user restarts the app if they are deliberately expecting a passphrase prompt to show up.  If the app just starts, how many users will see that as a change?
 *  If the user's device's data is being backed up regularly, removal of the app lock might result in full cleartext backup, exposing everything to the backup provider.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
