### ISSUE TITLE
Font size in message input box is larger than font size in messages

### ISSUE THREAD

**Issue by wp9015362** [signalapp/Signal-Android#2769]
Hello,

in TextSecure-Android, the font size in the message input box is different than the font size used for messages.

Could you please make the message input box font size be equal to the message font size?

IMHO the font size for what I am typing (message input box) should not differ from what I am reading (messages).

Regards

**Comment by jeremymasters** [comment]
For the record, mine looks like the same size in both messages and the input box....galaxy s4, stock 4.4.2 using swiftkey.

**Comment by wp9015362** [comment]
On LG G2 with stock KitKat 4.4.2 ROM for example, the message input box font size always is larger than the message font size. Regardless of the keyboard and regardless of the system font size setting.

**Comment by wp9015362** [comment]
@mcginty :

I see you closed a pull request which was about to fix this issue a few months ago:

https://github.com/WhisperSystems/TextSecure/issues/2969

Since you have fixed https://github.com/WhisperSystems/TextSecure/issues/3317 now (thanks for that), could you now also please have a look at this issue?

I still think the font size in the message input box should not be larger than the font size in the messages. The font size should be equal for both.

When the font size in the message input box is larger than the font size in the messages, then the eyes always have to re-adjust between writing a message and reading a message.

And I also noticed something else:

When the message input box is empty, then there is a text in there in light gray which says "Send TextSecure message".

The font size of this text also is different.

Could you please fix that and make the message input box always have the same font size as the messages?

It would be much appreciated.

Regards

**Comment by andrewsawczyn** [comment]
Should this not be an easy fix?  Still unresolved 2 years later. Problem still exists with 3.29.6 and Android 7.1.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
