### ISSUE TITLE
Export backups to a sub-folder.

### ISSUE THREAD

**Issue by Wicked0ne** [signalapp/Signal-Android#2791]
Right now on my phone TextSecure exports the backup to the main folder on my sdcard. It would be nice if it was exported to a sub-folder, something like /sdcard/TextSecure/backup.xml or even have a setting to allow users to select the folder.

The reason behind this request is that most "backup" apps don't allow backing up a single file. Such apps as BtSync or the open source competitor to BtSync called SyncThing. They act kinda as dropbox but you host the servers and folders they backup to. I update my rom somewhat frequently and like to save my text messages.

**Comment by mcginty** [comment]
Yeah, we should probably organize all our sdcard files in a folder.

**Comment by agrajaghh** [comment]
Saving the attachments in a TextSecure folder on the sdcard might be better as well (like Whatsapp, Threema, Telegram)

**Comment by Wicked0ne** [comment]
I'm going to attempt fixing this. It's been a long time since I've written java. Will submit a pull request if I get it working.

**Comment by TWfromSWD** [comment]
Same as https://github.com/WhisperSystems/TextSecure/issues/1901

**Comment by SergejKern** [comment]
Is this still open?

**Comment by McLoo** [comment]
That tells you the green field under the title, saying: "Open"

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
