### ISSUE TITLE
Verified message shows wrong details (verify again)

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#2796]
as mentioned in #2784

If you receive a message, that needs verification and you verify, the message is shown just fine. But the detail dialog still offers the verify button which should not be tapped :)

Despite my former statement, details for that message show "verify" until you did.

**Comment by mspl13** [comment]
Also, an indicator for verified contacts would be nice to see. It would make it easier to differentiate between those 2 groups (verified/unverified).

**Comment by heyimgay** [comment]
Maybe a signal blue circle around the photo?

**Comment by FeuRenard** [comment]
I did not see this effect while investigating #5604. Does this still happen for anyone?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
