### ISSUE TITLE
[Feature request] Add ability to delete image in image view

### ISSUE THREAD

**Issue by BT80** [signalapp/Signal-Android#2798]
Currently the only way to delete an image is by long-tapping the image and selecting the delete icon.

If you short-tap the image it is displayed in full screen mode. There is already a save icon in that view. My suggestion is to also add a delete icon in that view.

**Comment by moxie0** [comment]
Thanks, but I don't think we're going to do this.

**Comment by BT80** [comment]
That's sad! I thought it would be of benefit. My use case was as follows:
When selecting "All images" in the menu there is no posibility to delete an image from the past. The only way to delete it would be by scrolling up the chat history until you reach that specific image, long-tap it and then select the delete icon. Scrolling up on large chats can be very tedious.

**Comment by 2-4601** [comment]
I can imagine @BT80 use case becoming more and more common as the user base grows. Deleting one image out of hundreds is currently not very user friendly.
Please consider reopening this.

**Comment by mcginty** [comment]
I think this could be useful, especially now that we have a message details page where that action could also exist. Reopening with the caveat that we will likely want to add the "caption" text underneath the image so they know they're deleting the whole message and not just the media.

**Comment by Don42** [comment]
I think it would also be useful and in line with android ux guidelines, to be able to longpress select images in the "all images"-View. This would allow it to save or delete multiple images at once. This would make the view behave more like the native gallery.

**Comment by 2-4601** [comment]
Deleting multiple images should then have a dialog which tells explicitly that you are also deleting associated messages at the same time. As mcginty noted above deleting images in TS is not as trivial as it may first seem.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
