### ISSUE TITLE
TextSecure displays some "national" numbers as US numbers

### ISSUE THREAD

**Issue by rrthomas** [signalapp/Signal-Android#2804]
I'm in the UK, but I have a Fairphone FP1U, which only has one (US) English locale, so it's understandable why TextSecure chooses this format for my numbers.

However, Hangouts and the built-in Messages app both display the numbers as they are entered in my Contacts.

I've read other (closed) issues about deduping numbers & other display issues. I guess the problem may arise because after deduping the number is reformatted? Would it make more sense simply to pick one of the original forms of the number (arbitrarily, if necessary)?

**Comment by moxie0** [comment]
You'll have to give us steps to reproduce.

**Comment by yzrmn** [comment]
Maybe I can help with this, I'm in germany and I set language to English (United States).

These are typical formats for german mobile numbers:

![screenshot_2015-03-27-19-24-48](https://cloud.githubusercontent.com/assets/11163354/6874462/b3223636-d4b7-11e4-90cc-63d6d8e3e2eb.png)

However, locally formatted numbers are displayed as US numbers in TextSecure:

![untitled](https://cloud.githubusercontent.com/assets/11163354/6874466/bcda6784-d4b7-11e4-8bc6-1bab8efaf812.png)

I saved all my contacts with +49 to circumvent the "wrong" formatting.

**Comment by rrthomas** [comment]
I get pretty much the same result as @yzrmn, except that, contrary to my initial report, only some of my "local-style" numbers are formatted in the US style. I cannot yet see what precisely causes the reformatting: some numbers in the format "07xxx xxxxxx" are reformatted, while others are not.

**Comment by moxie0** [comment]
Wait, so the formatting you're talking about is the addition of the dashes?

**Comment by rrthomas** [comment]
That's right: the space is removed, and dashes are added.

**Comment by moxie0** [comment]
But everything still works right? You're saying that it's just displayed weird?

**Comment by rrthomas** [comment]
That's right.

**Comment by yzrmn** [comment]
I think I found it in the code...

https://github.com/WhisperSystems/TextSecure/blob/28232fc2a5f8ac8ba11283ca9992f1052467d28b/src/org/thoughtcrime/securesms/ConversationActivity.java#L554-L560

My suggestion is, the phone number is displayed unformated (like in contact selection for non push contacts)

It also looks like formatNumber is deprecated: http://developer.android.com/reference/android/telephony/PhoneNumberUtils.html#formatNumber%28java.lang.String%29

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
