### ISSUE TITLE
Feature Request: Lock Messages (to prevent auto deletion)

### ISSUE THREAD

**Issue by nickma82** [signalapp/Signal-Android#283]
Long press (right click) on a message should give the Ability to "Lock/Unlock Message" to prevent it from being automatically (and or accidentally) deleted.

Prevent deletion in case of:
- "Conversation length limit" bail out
- Retentation exceeded (see also: https://github.com/WhisperSystems/TextSecure/issues/176)
- Delete Threads (should bring up at least another Pop-Up)

**Comment by tatwater** [comment]
+1

**Comment by Pa9an** [comment]
+2 (me and my wife) :)
This request is more than two years old, will we ever see it completed? :)

**Comment by micressor** [comment]
+1

**Comment by bungabunga** [comment]
hey, @micressor, although i am with you on this, please know that people from OWS really hate +1s. it's a very small team of devs and bumping issues only distracts them from coding.
