### ISSUE TITLE
conversation snippet gross on group update

### ISSUE THREAD

**Issue by rhodey** [signalapp/Signal-Android#2834]
1. create a group with some friends
2. send some messages between friends
3. notice the "conversation snippet" text in the conversation list view is the last message sent
4. update the group name
5. notice the snippet now reads `<phone #>, <phone #>, etc joined the gr...`

I think it would be better to keep the conversation snippet to message content only, ie: don't update snippet on group update.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
