### ISSUE TITLE
Conversation doesn't always scroll to bottom on sending 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#2856]
- when the last message was a (**edit: n outgoing**)  media message 
- and new message ist text only 
- and keyboard is open when sending 

Second text message scrolls down correctly.

This drove me nuts for quite a while  😲
Feature  introduced in #1216

**Comment by rhodey** [comment]
some related discussion in #1211

**Comment by McLoo** [comment]
Hm, no it was the text I sent after an incoming (old)  message. Just in case it gives any clue,  the log right after sending: https://gist.github.com/db66dffd258643b60ca5

**Comment by McLoo** [comment]
Nearly fixed :grimacing: 

There were 2 existing image bubbles before I wrote the "Do"  message 
![_20151119_210853](https://cloud.githubusercontent.com/assets/5326916/11282897/107a5dcc-8f02-11e5-8108-2ec2e60c1061.JPG)

**Comment by dcherian** [comment]
Still have this on 3.7.2. I think it happens when the last message in the conversation is an image.

**Comment by dcherian** [comment]
Just happened again. I sent one message that had a URL link. That scrolled fine. When I sent the next message (text only), Signal didn't scroll all the way.

**Comment by mkae** [comment]
Still seeing this on 3.20.4 at times when sending messages.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
