### ISSUE TITLE
Text to Email / SMS Gateway sent as MMS not SMS

### ISSUE THREAD

**Issue by Ferinex** [signalapp/Signal-Android#293]
If you send a text message to an email address, it will be sent as an MMS even if no image is attached. This means, for the recipient, that the content of the message is attached to the email as a .txt file instead of being inside the body of the email. It also means the return address will be the MMS gateway instead of the SMS gateway, so any reply sent will be an MMS unnecessarily.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
