### ISSUE TITLE
ConversationActivity has incorrect ActionBar size and font size after orientation change

### ISSUE THREAD

**Issue by turtlekiosk** [signalapp/Signal-Android#2930]
The actionbar size and font size of the text in the actionbar are incorrect if you enter the ConversationActivity and then rotate the device (specifically it retains the correct sizes for the opposite orientation).

Entering from portrait:
![portrait_correct](https://cloud.githubusercontent.com/assets/1096636/7078767/5981b344-deea-11e4-836c-3f5405b75b9e.png)

Entering from landscape and rotating to portrait:
![portrait_incorrect](https://cloud.githubusercontent.com/assets/1096636/7078775/6759ded8-deea-11e4-9259-1b47164823d8.png)

Entering from landscape:
![landscape_correct](https://cloud.githubusercontent.com/assets/1096636/7078786/7ec9fc88-deea-11e4-8508-d06077ffad63.png)

Entering from portrait and rotating to landscape:
![landscape_incorrect](https://cloud.githubusercontent.com/assets/1096636/7078797/9ad7c3c4-deea-11e4-9e0f-6400ec8bf0ac.png)

Device info: Moto X 2013, Android 4.4.4, TextSecure 2.10.2

**Comment by turtlekiosk** [comment]
I think the views are not being redrawn because the the orientation config change is ignored for ConversationActivity in the AndroidManifest.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by turtlekiosk** [comment]
Yep, still an issue as of 2.28.1

**Comment by merkste** [comment]
It still persist in 3.6.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
