### ISSUE TITLE
TextSecure uses full-fledged notification sounds for in-thread notifications. Should use short dedicated sounds instead.

### ISSUE THREAD

**Issue by wp9015362** [signalapp/Signal-Android#2951]
Hello,

TextSecure uses full-fledged notification sounds for in-thread notifications and does not allow to configure the in-thread notification sounds, it simply uses the main full-fledged notification sound.

The sound for main notifications can be configured in TextSecure though.

In comparison:

Telegram for Android is using short dedicated sounds for in-thread notifications and it also has a sound for outgoing messages, not just for incoming messages.

It's using the following sound for outgoing messages:

https://github.com/DrKLO/Telegram/blob/dev/TMessagesProj/src/main/res/raw/sound_out.wav

And it's using the following sound for incoming messages:

https://github.com/DrKLO/Telegram/blob/dev/TMessagesProj/src/main/res/raw/sound_in.wav

Could you please also use short dedicated sounds for the TextSecure in-thread (notification) sounds, similar to how Telegram for Android is doing it for it's in-thread (notification) sounds?

AFAIK WhatsApp is doing it like that as well by the way.

Regards

**Comment by 2-4601** [comment]
Counter example: _Google Hangouts_ uses only one notification sound.

**Comment by wp9015362** [comment]
> @2-4601 wrote:
> 
> Counter example: Google Hangouts uses only one notification sound.

And does it have a short dedicated sound for in-thread notifications? Or does it use the normal main notification sound for in-thread notifications?

Well, ideally I would like to be able to configure the in-thread notification sound myself, just like I can do for normal notifications in TextSecure. But I didn't ask for it because I guess @moxie0 would probably answer:

"[The answer is not more options.](https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md)"

...

Anyway, using short dedicated sounds for in-thread notifications by default (with the option to disable in-thread notification sounds, which already is available, of course) would probably make sense, wouldn't it?

Regards

**Comment by 2-4601** [comment]
_Hangouts_ does not have in-thread notification sounds. Just a general one. It is customizable.

I don't have anything against adding in-thread notification sounds to TextSecure but it might get a ∞ milestone :)

**Comment by volcano99** [comment]
I don't really care about having a different sound for in-thread notifications, but I like the idea of a sound for outgoing messages. Though right now there are way bigger issues. Even visually, sending messages doesn't feel as smooth as on telegram. It takes forever for a message to turn blue and sometimes I receive the delivery receipt before it even marks the message as sent. So sounds will definitely get a ∞ milestone

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
