### ISSUE TITLE
multimedia messages not downloading 

### ISSUE THREAD

**Issue by Arilkahn** [signalapp/Signal-Android#2976]
Images & videos do not download.

**Comment by agrajaghh** [comment]
we need a little bit more info...

**Comment by moxie0** [comment]
https://github.com/WhisperSystems/TextSecure/wiki/Submitting-useful-bug-reports

**Comment by mrtompa** [comment]
I have the same problem.
Device info: HTC One m7, Android 5.02, TextSecure 2.10.2.
Message is:
Multimedia message
MMS download failed!

Debug log: https://gist.github.com/deac71c19c807d13eb66

**Comment by hamr1984** [comment]
I can neither receive nor send MMS. Instead of just showing the received MMS, it has a download button and includes message size (in bytes) & an expiration date. Instead of sending the MMS, it says not delivered tap for details, with a red exclamation mark to the left of the message. When I tap for details all it tells me is message failed to send. When I press the resend button, the same thing continues to happen.

**Comment by hamr1984** [comment]
My device is a Samsung Galaxy S5, operating with Android version 4.4.2. I just did a factory reset on my phone prior to having this problem.

**Comment by agrajaghh** [comment]
@hamr1984 please post a debug log after trying to send a MMS

**Comment by hamr1984** [comment]
Nevermind, my Mobile Data was turned off. I guess I can only get MMS on Mobile data and not WifI also.

**Comment by w1res** [comment]
I'm having this issue on a Moto X running Android 4.4.4. I'm on Verizon.

To make it work, I have to disconnect from WiFi, receive the MMS, and then connect to WiFi again. Now that I have a VPN it is even worse, because I have to disconnect from WiFi, disconnect my VPN, download the MMS, and then re-enable both.

I know that I had this problem a while back. Then I seem to recall it working at some point (not 100% sure on that). I don't know when it happened, but it is not working for me again.

**Comment by Arilkahn** [comment]
I just relized that yes this is only happening while I'm on Wi-Fi when I'm
on 4G it downloads images just fine.

**Comment by choate2626** [comment]
Same issue. Fails to send or receive MMS, but mine is not affected by WIFI like others. 

Phone- LG G3
Android- 5.0.1
TextSecure- 2.11.1
Receiving gives MMS Download failed
sending gives Failed to Send. 
WIFI on or off, same message.
SMS sends with no issue

Debug log:
https://gist.github.com/5cb41999a9f163afd681

**Comment by ximex** [comment]
I think i have the same problem.

Nexus 4
Android 4.4.4 (CM 11 Nightly)
TextSecure 2.11.1
WIFI on or off -> same problem

Debug log:
https://gist.github.com/928113e9fc0d68880449

**Comment by hamr1984** [comment]
What fixes mine was my Mobile Data was turned off in my phone settings.

**Comment by mcginty** [comment]
@choate2626 I don't see any MMS stuff in your debug log. Can you make sure you send/receive a message, it fails, and then post the log? Thanks!

**Comment by choate2626** [comment]
https://gist.github.com/d34753ba9c9b058f769f

**Comment by choate2626** [comment]
And sending

https://gist.github.com/c19d752eb70205d8dd9d

**Comment by aibaraiduas** [comment]
I have the same problem as well (TextSecure 2.14.5; Nexus 5; Android 5.1; T-Mobile): "Multimedia message MMS download failed." It was a picture sent to multiple recipients despite TextSecure only showing the sender, not the other recipients. There was a follow up (just text) that simply did not show up.

My phone did receive the messages because I checked another texting app (Textra) after TextSecured failed. Note that Textra was not running at the time though (I only opened it afterwards, and autostart is turned off via App Ops). 

Log:
https://gist.github.com/anonymous/8cd1b64b7aeb4c4ef8f8

**Comment by riyapenn** [comment]
Sony Z3 6603
stock android 5.1.1
TextSecure 2.28.1

https://gist.github.com/anonymous/76c8dab7fbb41e7a7e2a

MMS download failed, worked prior to update to 2.28.1

**Comment by TriPold** [comment]
Hello!

I have the same problem with my Samsung Galaxy S4, running Cyanogenmod 13.0-..., android version: 6.0.1.

I don't use mms messages alot so unfortunately I can't tell when this has occured me before. Maybe an year ago. Yesterday I suddenly got one mms from my Mom.
I tried to open it with Signal but as I tapped it suddenly a sign of connection interuption appeared on top of the 4G network icon.

The only way to reestablish the connection was to turn mobile data off and back on.

Because of the sudden connection interruption that happens every time I try to open the mms message, signal won't get a change to connect with the mms server and gives the same red warning sign beside the mms message as has already been mentioned on many post's before this.

I just can't figure out why this is happening only when I'm trying to open an mms message.
I tried updating the ROM and even got my self a new sim card. Non of this seemed to be helpfull in any way.

Log below:

https://gist.github.com/96abd74ba24da8e0b788

**Comment by moxie0** [comment]
@TriPold The system is returning the error "http failure." Looks to me like your system APN settings are probably incorrect.

**Comment by TriPold** [comment]
@moxie0 My APN settings are correct. I've tripple checked them to ensure they match with the APN settings provided by my operator.

**Comment by moxie0** [comment]
@TriPold Don't know what to tell you.  The logs are pretty clear, we try to retrieve the MMS using our own code, and when that fails we try to have the system do it instead:

```
2-17 11:33:07.104  7060  7079 W IncomingLegacyMmsConnection: Downloading in MMS mode with proxy...
02-17 11:33:07.104  7060  7079 W LegacyMmsConnection: Checking route to address: 213.161.41.57, 213.161.41.57
02-17 11:33:07.106  7060  7079 W LegacyMmsConnection: requestRouteToHostAddress(/213.161.41.57) -> false
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: java.io.IOException: Connection manager could not obtain route to host.
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:114)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:85)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:59)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:97)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-17 11:33:07.106  7060  7079 W IncomingLegacyMmsConnection: Downloading in MMS mode without proxy...
02-17 11:33:07.106  7060  7079 W LegacyMmsConnection: Checking route to address: 213.161.41.10, 213.161.41.10
02-17 11:33:07.110  7060  7079 W LegacyMmsConnection: requestRouteToHostAddress(/213.161.41.10) -> false
02-17 11:33:07.111  7060  7079 W MmsRadio: MMS Radio Disconnect Called...
02-17 11:33:07.111  7060  7079 W MmsRadio: Reference count: 0
02-17 11:33:07.111  7060  7079 W MmsRadio: Turning off MMS radio...
02-17 11:33:07.115  7060  7079 D ConnectivityManager: stopUsingNetworkFeature for 0, enableMMS
02-17 11:33:07.115  7060  7079 W MmsRadio: Unregistering receiver...
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: java.io.IOException: Connection manager could not obtain route to host.
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:114)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:92)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:59)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:97)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-17 11:33:07.116  7060  7079 W CompatMmsConnection: Falling back to try receiving via Lollipop API
02-17 11:33:07.120  7060  7079 W IncomingLollipopMmsConnection: downloading multimedia from http://213.161.41.10:80/servlets/mms?id=m9YOlZKIc01 to content://org.thoughtcrime.provider.securesms.mms/mms/1455701587120
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: javax.net.ssl.SSLException: Read error: ssl=0xb4cec780: I/O error during system call, Connection timed out
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at okio.Okio$2.read(Okio.java:136)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:130)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readUntilNonControlFrame(WebSocketReader.java:119)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:94)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: 	at java.lang.Thread.run(Thread.java:818)
02-17 11:33:07.138  7060  7202 W WebSocketConnection: onClose()...
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: Calling disconnect()...
02-17 11:33:07.138  7060  7202 W WebSocketConnection: WSC connect()...
02-17 11:33:07.138  7060  7202 W OkHttpClientWrapper: Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
02-17 11:33:22.215  7060  7060 W LollipopMmsConnection: onReceive()
02-17 11:33:22.216  7060  7060 W IncomingLollipopMmsConnection: HTTP status: -1
02-17 11:33:22.216  7060  7060 W IncomingLollipopMmsConnection: code: 4, result string: null
```

**Comment by TriPold** [comment]
@moxie0 Okay. Thank you very much for the info. I'll be in touch with my operator.

Back to testing.

**Comment by TriPold** [comment]
Yeiii! I've solved the issue.

I went to Signal settings. Then into Chats and media and from there under Media auto-download, I checked all: Images, Audio and Video when using mobile data.

That seemed to have fixed the problem.

**Comment by moxie0** [comment]
@TriPold I'm pretty sure that's a coincidence.

**Comment by jonsafari** [comment]
For me, I solved this problem by re-enabling trusting the Baltimore CyberTrust root (Settings -> Security -> Trusted credentials).

**Comment by agh1467** [comment]
I'm on LineageOS 14.1 (xt987) and experiencing a strange issue. It seems that it will intermittently download MMS messages successfully. Looking at the logcat I found the following which I think may be important.

Here is a snip from when it successfully downloads an MMS:
```
10-01 17:36:50.154  3853  4489 D MmsServiceBroker: downloadMessage() by org.thoughtcrime.securesms
10-01 17:36:50.160  4355  4517 D MmsService: downloadMessage: http://sobmms.plspictures.com[57]
10-01 17:36:50.164  4355  4517 D MmsService: Current running=0, current subId=-1, pending=0
10-01 17:36:50.164  4355  4517 D MmsService: Add request to running queue for subId 1
10-01 17:36:50.167  4355  5917 I MmsService: [DownloadRequest@8fcd2d8] Executing...
10-01 17:36:50.167  4355  5917 I MmsService: mms config for sub 1: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=6, enableSMSDeliveryReports=false, maxMessageTextSize=-1, supportMmsContentDisposition=false, enabledTransID=false, aliasEnabled=false, supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=40, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true, maxSubjectLength=80, httpParams=X-MDN: ##LINE1##|Proxy-Authorization: Basic ##NAI##, enableGroupMms=true, emailGatewayNumber=6245, maxMessageSize=1048576, naiSuffix=:pcs, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false, enableMultipartSMS=true}]
10-01 17:36:50.167  4355  5917 D MmsService: [DownloadRequest@8fcd2d8] MmsNetworkManager: start new network request
```

Here is a snip from when it fails to download the MMS:
```
10-01 17:38:17.510  3853  4905 D MmsServiceBroker: downloadMessage() by org.thoughtcrime.securesms
10-01 17:38:17.521  5376  5376 W MessageRetrievalService: Active Count: 0
10-01 17:38:17.523  4355  4517 D MmsService: downloadMessage: http://rstnmms.plspictures.com[66]
10-01 17:38:17.530  4355  4517 D MmsService: Current running=0, current subId=-1, pending=0
10-01 17:38:17.530  4355  4517 D MmsService: Add request to running queue for subId 2
10-01 17:38:17.553  4355  6037 I MmsService: [DownloadRequest@6427d7b] Executing...
10-01 17:38:17.553  4355  6037 I MmsService: mms config for sub 2: null
10-01 17:38:17.553  4355  6037 E MmsService: [DownloadRequest@6427d7b] mms config is not loaded yet
```

I noticed three things here:
1. The download URLs change (sobmms.plspictures.com -> rstnmms.plspictures.com)
2. The subscription ID changes from 1 to 2 for an unknown reason.
3. The mms config on Subscription 2 isn't populated thus returns null.

After this there will be an exception referencing a connection time out.

I found the following regarding the subscription change as well:
```
10-01 18:08:34.853  4547  7561 D CellBroadcastConfigService: Enable CellBroadcast on sub 2
10-01 18:08:34.890  7364  7477 D IccSmsInterfaceManager: [IccSmsInterfaceManager] Added cdma broadcast subscription for MID range 4096 to 4096 from client com.android.cellbroadcastreceiver
10-01 18:08:34.890  7364  7477 D IccSmsInterfaceManager: [IccSmsInterfaceManager] Calling setCdmaBroadcastActivation(true)
10-01 18:08:35.070  4547  4547 D CellBroadcastReceiver: onReceive Intent { act=android.intent.action.ACTION_DEFAULT_SMS_SUBSCRIPTION_CHANGED flg=0x20000010 cmp=com.android.cellbroadcastreceiver/.CellBroadcastReceiver (has extras) }
10-01 18:08:35.070  4547  4547 D CellBroadcastReceiver: Start Cell Broadcast configuration.
10-01 18:08:35.173  4133  4133 E SignalClusterView: Unexpected subscription 2
10-01 18:08:35.173  4133  4133 E SignalClusterView: Unexpected subscription 2
10-01 18:08:35.922  3853  3879 D MmsServiceBroker: getCarrierConfigValues() by com.android.messaging
10-01 18:08:35.922  7364  7403 D MmsService: getCarrierConfigValues
10-01 18:08:35.922  7364  7403 I MmsService: mms config for sub 2: null
10-01 18:08:36.233  7364  7364 D TelephonyProvider: subIdString = 2 subId = 2
```

I'm not sure if this is a system problem (LineageOS) or a Signal problem.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
