### ISSUE TITLE
TextSecure removed delivery check marks

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3014]
Something weird just happened to me, but I remembered this is not the first time (and luckily I have the debug log!)
I had a conversation open:
- I sent three messages. One got delivered immediately, but the screen turned off while the other two were being sent/delivered
- My friend wrote me a message
- I unlocked my phone (the conversation of textsecure was already open as I unlocked it)
- I could see for a very brief instant that all three messages had the delivery check mark, which disappeared almost instantaneously. The messages are still there, but the first is the only one to be marked as delivered.
  I am sure my friend got all the messages, as they replied to them. I tried closing and reopening the conversation, but the check marks don't seem to come back.
  Here's the debug log https://gist.github.com/f50b4f35b2c3aee21199

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
