### ISSUE TITLE
Incoming message bubbles not resized on small screens

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3027]
This is not a huge bug, just somehting that annoys me. The grey bubbles for incoming messages "touch the border of the screen" (I don't know how else to describe it). Basically, they are too large.
Here is a screenshot that will show you the problem
![media-20150421](https://cloud.githubusercontent.com/assets/11767388/7256071/6f72b88a-e84d-11e4-9ccc-31fe78a8ff0b.png)
My phone's screen is not really big so I guess that's the problem

**Comment by mcginty** [comment]
good point, thanks for the issue @volcano99

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
