### ISSUE TITLE
Signal has disappeared from the recent apps view

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3038]
I updated my Nexus 4 stock Android from 5.0.1 to 5.1 and just noticed that TextSecure does not show up anymore in the _overview/recent apps/recent screens/app switcher/card view_ (whichever is the correct term).

If I have only TextSecure open I see the message 'Your recent screens appear here' as if I had no apps open.
If I have TextSecure and other apps open I see every other app except TextSecure there.

TS 2.12.0

**Comment by rhodey** [comment]
@2-4601 I've been running TS 2.12.0 on Android 5.1 for the past ~week and have yet to experience this. Have you restarted your phone since the initial update? *crosses fingers that it will magically go away*

even if this did magically stop happening it is strange that TextSecure is the *only* app for which this happens.

**Comment by 2-4601** [comment]
Yes, this is a pretty useless bug report as it is. I submitted just before going to sleep. Should have slept over it and tested more. Restart solved it. But I have some ideas how to reproduce it.

**Comment by rhodey** [comment]
`Now all I can say is that it did actually happen`

lol, **I believe you**, @2-4601 :church:

**Comment by 2-4601** [comment]
Happened again just now. I wasn't doing anything special. Just browsing old messages and inwardly crying why nobody answers me. Then when I switched to another app I saw that TS was missing from the list.
https://gist.github.com/a1417e558d09fd188e43

Will keep this closed until I can reproduce.

**Comment by 2-4601** [comment]
And again. Sent messages to a group and individual people. Then switched to another app and TS is no longer in the recent apps list.
https://gist.github.com/539fbd43af2afe447fd2

Both logs have `FileNotFoundException` but not sure if it's related to this.
Cannot reproduce. This has not happened with other apps so far.

**Comment by rhodey** [comment]
with all these logs and context I think it's definitely helpful to reopen this issue even without steps to reproduce, someone else experiencing the same is probably more likely to notice it open

**Comment by 2-4601** [comment]
This time no accompanying strange behavior. I just opened a conversation¹, tapped _Overview_ and boom.
https://gist.github.com/e50487c398534e6071d1

Those `FileNotFoundException`s have probably nothing to do with this since they seem to be in every log I have viewed.

Note to self: next time lock the screen when in TS and unlock to see if it goes to Home Screen or back to TS (¹:soccer:)

**Comment by 2-4601** [comment]
Uh-oh, this happened now with my 4.0.4 device (Huawei U8800) and TS 2.16.1. No debug log because the feature does not seem to work with this device. The log is always empty except for device info.

**Comment by 2-4601** [comment]
@oholika can you reproduce this?

**Comment by oholika** [comment]
yes with TS 2.14.5 on Nexus4 (occam) with Android 5.1 (LMY470)

**Comment by 2-4601** [comment]
I mean does it happen only occasionally or are there some steps that always cause it to happen?

**Comment by oholika** [comment]
it happens every time

**Comment by 2-4601** [comment]
Even after you reboot your Nexus?

**Comment by oholika** [comment]
just checked, after reboot everything works fine!

**Comment by 2-4601** [comment]
Thanks for the confirmation :smiley: 

I only get this issue randomly and so far I have been unable to say what exactly causes it.
If you can find out the steps that trigger this please post them here.

**Comment by jeremymasters** [comment]
fwiw, I have never had this on my Galaxy s4 with android 5.0.1.  I HAVE seen it happen on my wife's Galaxy S6 with Android 5.0.2.

**Comment by 2-4601** [comment]
Happened just now with Huawei U8800, 4.0.4, TS 2.23.1

**Comment by Rambo-Zambo** [comment]
I've managed to reproduce this. It seems to occur when sending a link from the YouTube app to TextSecure using the YouTube app's built-in sharing function. As described above, it persists until restart and I've managed to reproduce it 3 out of 3 times. Tested on Nexus 5 / Android 5.1.1 with the latest versions of both YouTube and TextSecure.

**Comment by McLoo** [comment]
Can reproduce with @Rambo-Zambo info - BUT I have to go through the lock screen to make this happen. Reminds me of the weird #3740

Force close TS brings it back to recents after 1st opening
Log after shared, switch to other app, and opened TS again from launcher (with update)

**Comment by thvasilo** [comment]
Can confirm that after disappearing from recents, force stop and open again brings it back.

**Comment by 2-4601** [comment]
Copypasting @eosrei's report from #5180 here:
>I can only get to Signal by opening from my home screen favorite/shortcut menu. It is never available in the Recent Apps list.

>Reproduce:
>1. Close all recent apps
>2. Open Chrome
>3. Press *Home*
>4. Open Signal
>5. Press *Recent Apps*
>6. Recent Apps list appears with Chrome. Signal scales/resizes down to fit, but then disappears.

>If I close all apps and open just Signal, when I press *Recent Apps* my app list is empty.

>*This may be related to #1037 and is probably related to #3172. Neither describe this exact issue. Could be an unintended result of a workaround for #3172?*

>System: CyanogenMod 12 - Android 5.0.2

>Opening Signal with Favorite Menu
```
02-04 18:34:05.195 1321-1321/com.cyanogenmod.trebuchet I/Timeline: Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:6910395
02-04 18:34:05.197 731-1209/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=org.thoughtcrime.securesms cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[437,1035][571,1195] (has extras)} from uid 10017 on display 0
02-04 18:34:05.201 731-789/system_process W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1321, uid=10017) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
02-04 18:34:05.202 731-789/system_process W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10017)
02-04 18:34:05.202 731-789/system_process W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1321, uid=10017) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.icingsync.ApplicationLaunchReceiver
02-04 18:34:05.202 731-789/system_process W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.icingsync.ApplicationLaunchReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10017)
02-04 18:34:05.254 23261-23261/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
02-04 18:34:05.418 23261-23261/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-04 18:34:05.418 23261-23261/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
02-04 18:34:05.433 23261-23261/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
02-04 18:34:05.523 23261-23261/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e50521f time:6910723
02-04 18:34:06.012 731-800/system_process I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1f1da3d9 u0 org.thoughtcrime.securesms/.RoutingActivity t10029} time:6911212
```
>Pressing *Recent Apps*
```
02-04 18:34:08.179 1024-1024/com.android.systemui W/ResourceType: No package identifier when getting value for resource number 0x00000000
02-04 18:34:08.179 1024-1024/com.android.systemui W/PackageManager: Failure retrieving resources for org.thoughtcrime.securesms: Resource ID #0x0
02-04 18:34:08.184 731-884/system_process I/ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity (has extras)} from uid 10009 on display 0
02-04 18:34:08.188 265-4766/? W/SurfaceFlinger: FB is protected: PERMISSION_DENIED
02-04 18:34:08.188 731-884/system_process W/WindowManager: Screenshot failure taking screenshot for (720x1280) to layer 21035
02-04 18:34:08.188 731-884/system_process E/ActivityManager: Invalid thumbnail dimensions: 384x384
02-04 18:34:08.191 23261-23261/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
02-04 18:34:08.224 23261-23261/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-04 18:34:08.224 23261-23261/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
02-04 18:34:08.225 23261-23261/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
02-04 18:34:08.246 731-999/system_process D/TaskPersister: removeObsoleteFile: deleting file=10029_task.xml
02-04 18:34:08.409 1024-1024/com.android.systemui I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3aa7e22d time:6913609
02-04 18:34:08.727 731-800/system_process I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{c75a29e u0 com.android.systemui/.recents.RecentsActivity t10022} time:6913927
```

>The primary difference between this logcat and that of #3172 is the:
```
731-884/system_process E/ActivityManager: Invalid thumbnail dimensions: 384x384
```

I can't reproduce with those steps though. And can't reproduce with the YouTube sharing steps either (see previous comments). And I can't remember the last time I experienced this. So maybe it's some weird ROM issue in some Android versions.
Tested with Nexus 4, stock 5.1.1, Signal 3.10.0

**Comment by svelle** [comment]
Just wanted to let you know that two years later this still is a thing. 
I have had this happen on two different devices. Sony Xperia Z1 Compact running Cyanogenmod 13 and now the Nexus 5X running stock 7.1.2.

Log is here:
https://gist.github.com/anonymous/944dc0831d1c1bd835837c1e8aa9c917

I don't really know from when to post this so I just dumped the whole log from today.

**Comment by riyapenn** [comment]
Adding Log: https://gist.github.com/33fe791fc9d402106d02bd9db50a3bb2
Device: Huawei Nexus 6P
OS: 7.1.2 
Signal version: 4.5.3

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
