### ISSUE TITLE
Chat Heads

### ISSUE THREAD

**Issue by Mosrite** [signalapp/Signal-Android#3039]
I find the floating bubbles which are for instance featured by Facebook Messenger very convenient. It makes it way easier to have several conversations at a time or to work with another app while answering incoming messages from time to time. Maybe this could be implemented for TextSecure in the future, too?

**Comment by volcano99** [comment]
If by floating bubbles you mean the "heads", I'm not sure that would be a good idea. It slows down phones pretty badly. To solve the problem of having several conversations at a time, textsecure could use a tab-like UI, sort of like surespot did. For example, swiping right could take you to the next conversation in the list, and swiping left could take you to the previous one. I think that would be much easier to implement and wouldn't even slow down the app that much.
What do you think?

**Comment by Mosrite** [comment]
Yeah, exactly, I mean the heads. Maybe this could be implemented as an option? Just like Facebook does it? People with faster phones could enable it, while all others would leave it disabled. 
A tab-like UI would improve parallel conversations but wouldn't help for switching between a conversation an another app. Furthermore, I think tabs might be used in the future to distinguish calls from text messages when RedPhone and TextSecure will be merged.

**Comment by yoasif** [comment]
Additional info: https://www.facebook.com/help/android-app/101495056700254?rdrhc

And end users commenting at how much they love FB messenger: https://www.reddit.com/r/Android/comments/4oa7iy/discussion_facebook_has_finally_given_me_the/

**Comment by JustPassingByHere** [comment]
Is there any particular reason why there's so little discussion on this? It seems this was a requested feature since 2015. 

I can understand if it's due to difficulties in implementing this or having focus on the core user experience with Signal as is but there's no official word on this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
