### ISSUE TITLE
delete old messages after certain time

### ISSUE THREAD

**Issue by ilf** [signalapp/Signal-Android#3047]
Currently, the auto-deletion of old messages only works for a conversation length limit: the number of messages per contact.
I'd love to also auto-delete old messages after a certain time. Options should be weeks, months, or years.
I propose a default of six months.

**Comment by agrajaghh** [comment]
I think this is even more usefull than the deleting after a number of messages. But it should definitely be turned off by default. Users don't expect messages to be deleted automatically and won't be happy...

**Comment by volcano99** [comment]
I don't think it's more useful than what we have now (I actually like the current option better), so it's just a matter of personal tastes. I'm not sure how well this will do with the "no more option" philosophy

**Comment by ilf** [comment]
The options "message count" and "time" are not exclusive, but complementary. I don't know much about the "no more option" philosophy, but this could just be one tiny new option and off by default.

**Comment by ilf** [comment]
Thanks for implementing [disappearing messages](https://whispersystems.org/blog/disappearing-messages/)!

I would really like to enable this globally though, without having to manually set this in every conversation and group.

This could be added to settings -> chats and media -> delete old messages.

**Comment by asavageiv** [comment]
I would also like to set a default value for disappearing messages instead of having to set it on a conversation by conversation basis.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
