### ISSUE TITLE
Improve search experience for when there’s no existing conversation with the searched person

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#3063]
I often search for people whom I messaged with to find the conversation. Now sometimes I don’t actually have an existing conversation with that person or I just forgot if I have one. In that case no result shows up.

As a nice fallback, it would be good if below the search results there would be a section like »Other contacts«. Similar to the »New message« people list, that would show the other contacts in the address book which match that search term.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
