### ISSUE TITLE
MMS error / helloMobile APN

### ISSUE THREAD

**Issue by m0rix** [signalapp/Signal-Android#3117]
**Problem**: sending and receiving MMS via default app works, but I cannot send/receive MMS via TextSecure.
##### My APN-settings for MMS (german provider is HelloMobil):

**Name**: O2 MMS
**APN**:  internet.telco _or_ internet.victorvox
**Username**: _none_
**Password**: _none_
**MMSC**: http://10.81.0.7:8002
**MMS-Proxy**: 82.113.100.5
**MMS-Port**: 8080
**Authentification**: PAP
**APN-Type**: mms

**error-log**: https://gist.github.com/346059a8725facc735c4

**Comment by mcginty** [comment]
Hey @m0rix, thanks for the issue submission! I don't see any MMS activity in your error log. Can you please try to send/receive an MMS and then immediately submit an error log? I'm guessing it got pushed out of the buffer.

**Comment by spoon532** [comment]
I am also having this issue on 2.13.0. Carrier is AT&T. I was able to receive, but not send the same photo back (nor any other photos).

https://gist.github.com/anonymous/145f11f41ae655b3956a

**Comment by m0rix** [comment]
@mcginty Sorry for the late reply. It is impossible for me to send/receive an MMS. I'm getting a dialogue "Configure MMS Settings" and checked the "manual settings" several times...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
