### ISSUE TITLE
mms issue: receiving same message over and over again

### ISSUE THREAD

**Issue by fabianbmnn** [signalapp/Signal-Android#3149]
Every time I receive a multimedia message text secure sends it again every day (at the same time) . That means that i end up having the same message 7 times.

Log:https://gist.github.com/90c8cb71076adc8df5a1

**Comment by benoitne** [comment]
I confirm I got the same issue
It is like TextSecure is not ACK it received the MMS and the provider keeps try to send it after multiple tries I receive a sms from my provider invited me to connect to a web site to see the MMS online

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
