### ISSUE TITLE
Feature request: Allow sharing Android calendar events via TextSecure

### ISSUE THREAD

**Issue by dang357** [signalapp/Signal-Android#316]
Originally a bug, which should have been titled "Shared calendar events are not actually attached." The fix in #1025 removed TS from the "share with" list of calendar events, so no longer a bug, but would like to be able to share calendar events via TS, same as can be done with default Android text app.

Original (bug) text: Android default Calendar app lets you send a calendar entry. TextSecure is one of the apps that comes up as an option to use for sending. Choosing it, you get to TextSecure, but there is no attachment, just an empty message. (If you choose the regular default Android Text Messaging app, the calendar entry does get properly attached, which is why I suspect the issue is with TextSecure.) Only tried doing this from Calendar, don't know if it's an issue sending via TextSecure from other apps.

**Comment by kalaspuffar** [comment]
@dang357: Looked at this issue a bit to see how hard an implementation of a sending of calendar event would be. And if you just want to read an event and send it to someone so they could have a similar event in their calendar that shouldn't be hard, might need to invent a lean format. But if you add them to it as a attendee for instance and use the regular Google Calendar then you already have this calendar in the cloud and most of the invitation messaging is done by Google so I'm not sure what the use case is for this feature. When you add a calendar event to your Google calendar it's already sent over the wire none encrypted.

Another thing is that this feature will add a requirement to the permissions so you can read the calendar. And perhaps this could be a bad for some users. "Why does this messaging app need to access my calendar?" someone might ask.

Then again I think it's up to moderators to decide if this is a feature worth looking into. @moxie0 @mcginty @agrajaghh @rhodey

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
