### ISSUE TITLE
Image view in fullscreen

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#3192]
Remove the action bar in the view where you can inspect a received picture to enlarge the image.

**Comment by rhodey** [comment]
I like the action bar being optional because of the "save" menu item, lots of apps are doing the pattern where you tap the image once to disappear the action bar and tap again to return it, hangouts defaults to hiding the action bar and then bringing it back in on tap. I'm up for either of those.

**Comment by sedrubal** [comment]
:+1:

**Comment by FeuRenard** [comment]
I am working on this issue.

**Comment by FeuRenard** [comment]
Feature is fully implemented here:
https://github.com/FeuRenard/Signal-Android/tree/mpa-fullscreen_support

I am going to delay opening a PR until I implemented #5934 on top. By this I want to make sure that I don't introduce changes that have to be reverted by myself later.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
