### ISSUE TITLE
Feature request for TextSecure: Unread count on icon

### ISSUE THREAD

**Issue by Falkvinge** [signalapp/Signal-Android#321]
When I'm pushing TextSecure onto friends and family to spread adoption of encrypted communications, the showstopper is the lack of an unread messages count on the icon, like all other messaging apps have today.

When I send text messages to my mother, she will never read them, because when she turns her phone on, TextSecure won't show on her home screen as "1 unread message" with a little red circled "1" on the TextSecure icon. Drawing from UX from all other messaging apps today, the lack of such a number will instead indicate "nothing unread". 

I understand such an indicator is a privacy leak, but it's also an adoption showstopper to take TextSecure beyond the hardcore carers for cryptography, and by extension, even the ability for people like ourselves to communicate securely with friends and family (since they won't use TextSecure).

Cheers,
Rick

**Comment by patcon** [comment]
This library might be helpful.
https://github.com/arturogutierrez/Badges

> Small library to show badges in app icons for unread messages on most common manufacturers: LG, Sony, Samsung and HTC.

(Only Apex Launcher *Pro* has badges. It is paid, so I couldn't confirm bugs/behaviour.)

**Comment by agrajaghh** [comment]
@patcon a similar library is already included in TS: https://github.com/leolin310148/ShortcutBadger

**Comment by patcon** [comment]
:+1:

(got my issues mixed up and didn't mean to comment on closed one :)

**Comment by Brenhoist** [comment]
Wow this request is so old and still we have nothing. I am exactly in the same situation, people who I encouraged to install textsecure don't see any indication of icon on missed, unread count.

**Comment by wizardofid** [comment]
@Brenhoist "... and still we have nothing..." What do you mean? This issue is closed. As mentioned by agrajaghh ShortcutBadger is included. 
The number of missed calls and messages is in fact shown on the icon at my Samsung S3. Therefore i think it is correct that this issue is closed.
Maybe your problem is device-dependend. Then it might be best to open a separate issue for this.

**Comment by McLoo** [comment]
@Brenhoist you'll need a launcher that supports the badging. (e.g. stock android launchers like Samsung, Sony, ... or 3rd Party launchers. For details see https://github.com/leolin310148/ShortcutBadger)

Android's or CM's default launcher do not support that. (Without manipulating the icons themselves, which is not allowed)
