### ISSUE TITLE
crash on receipt of VCard from iOS

### ISSUE THREAD

**Issue by Jmachet** [signalapp/Signal-Android#3256]
After receiving an SMS containing a Vcard, my TextSecure app won't open. It allows me to enter my pin but after that it crashes. I have reported the crash dump to the developer. I would really like to delete the message and continue using TextSecure without reinstalling it and losing all the data.

Thanks in advance for any help you can provide.

**Comment by moxie0** [comment]
Please post a debug log here.

**Comment by Jmachet** [comment]
Hi Moxie,

Here is a debug log https://gist.github.com/660916bfb42ff9b16173

Cheers

**Comment by moxie0** [comment]
there's nothing in this log. you need to capture it immediately after the crash

**Comment by Jmachet** [comment]
I have reported it when the crush dump popup appears. My crash description
mentioned the vcard. If it makes it easier for me to send this to you,
please can you let me know of a way I can copy the crash log.

Thanks for the prompt response.

**Comment by moxie0** [comment]
1. Cause the crash to happen.
2. Immediately open TS
3. From the lock screen, immediately generate a debug log
4. Post the gist here.

**Comment by Jmachet** [comment]
The actual happenings of the crash aren't recorded in the log generator
because it's a hard crash. (The app closes and all processes stop)

**Comment by Jmachet** [comment]
Hi Moxie,

Please note I have found a workaround to fix my issue. I tried sharing
something to a contact that sent me the vCard (that crashed my app) and
then could remove the message and now my app opens again.

Thanks for the help. A future idea may be that the actual content of
messages don't fully load until you open the message up. Funnily enough
today, this was in the news:
http://arstechnica.com/security/2015/05/beware-of-the-text-message-that-crashes-iphones/

**Comment by rhodey** [comment]
damn, we've had problems with VCards for awhile. tagging for reference #499, #2252, #2504, #2332.

@Jmachet any idea if this VCard contained a picture? or if it came from an Android, iOS, Windows Phone, or other device?

**Comment by Jmachet** [comment]
It was from an iOS device. I couldn't tell you what was inside as it seemed
to be a whole random lot of hex after it had <START Vcard 3.0>.

To get it working again I used the loophole above to delete it so I don't
have it anymore.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
