### ISSUE TITLE
MMS download failed - HTC One M8, Android 5.0.1

### ISSUE THREAD

**Issue by dalethestirling** [signalapp/Signal-Android#3270]
Using Textsecure Beta on HTC One  M8 and still getting Message failed while receiving MMS from another handset.

Debul log attached.

https://gist.github.com/83a5c33c3bffb800ea65

**Comment by 5boro** [comment]
Could you try with this settings : https://devicehelp.optus.com.au/web/htc-one-m8/messaging/setting-up-my-mobile-phone-for-mms/

Your device seems to be trying trying to use 202.139.83.152:8070 as a proxy but it's [refusing connections](https://gist.github.com/anonymous/83a5c33c3bffb800ea65#file-cat-log-L14)

**Comment by puredistortion** [comment]
@5boro thanks for the help. 

I have deleted the APN from the phone and created a new one as per the instructions on the devicehelp page from Optus. The connection error is now gone. 


However I am receiving a Timeout issue, I have tried re-installing the app but still receive the following:

W/IncomingLollipopMmsConnection(30540): java.util.concurrent.TimeoutException: timeout when waiting for MMS

I do not believe this to be an issue with Optus, as when switching back to the defult Messages app on the HTC One, I am able to send and recieve MMS content. 

I am yet to import my old messages to the re-installed copy of the app. 

I have attached the Gist, this is taken from after the reinstall. 

https://gist.github.com/anonymous/4073511dfc7a4e126a38

**Comment by bk10287** [comment]
Having mms download issues on the HTC One M8 as well.  Debug logs:
https://gist.github.com/184f09ffd27ed4088f2b

**Comment by 5boro** [comment]
You're getting HTTP 302 errors, a quick search brought up this : #1267

Could you try without WIFI ?

**Comment by bk10287** [comment]
It actually happened while off WiFi, but I do have t-mobile so maybe it is a carrier issue.

**Comment by 5boro** [comment]
There's a 'WIFI calling' setting you may want to try out, and definitely check your APN settings.

**Comment by bk10287** [comment]
Thanks yea I found that and set it on.  It was working from prior updates, so I get the impression my APN settings should be fine, but I'll double check everything first.

**Comment by puredistortion** [comment]
@5boro I have tried to recieve and send an MMS without wifi on and it still failed. 

here is the gist:

https://gist.github.com/anonymous/7baf98da2800e4445994

**Comment by 5boro** [comment]
TextSecure fetches it's APN settings from CyanogenMod and Google's Hangout app, @puredistortion is it working using Hangouts?

If it is we may just need to update [apnlists](https://github.com/WhisperSystems/TextSecure/tree/master/apntool/apnlists)

**Comment by puredistortion** [comment]
@5boro I have done this and MMS does indeed work in Google Hangouts os the APN setting that they are using would be the correct ones. 

I have done some digging through all of the [APN data](https://github.com/WhisperSystems/TextSecure/tree/master/apntool/apnlists) that TextSecure appears to be using. If I get this wrong apologies as still getting my head round it. 

It appears that apns.db in master was generated from [hangouts.xml](https://github.com/WhisperSystems/TextSecure/blob/master/apntool/apnlists/hangouts.xml) as it now contains the data from hangouts.xml. Also I was unable to find the IP of [202.139.83.152](https://gist.github.com/anonymous/83a5c33c3bffb800ea65#file-cat-log-L14) which was a refused connection earlier in the issue I was having. This IP only exists in [cyanogenmod.xml](https://github.com/WhisperSystems/TextSecure/blob/master/apntool/apnlists/cyanogenmod.xml). 

Another interesting thing that I have found is that there is 3 entries for the APN name Optus MMS which is the defined APN name in the Optus [devicehelp page](https://devicehelp.optus.com.au/web/htc-one-m8/messaging/setting-up-my-mobile-phone-for-mms/):
```
1118,5052,505,2,"Optus MMS",mms,http://mmsc.optus.com.au:8002/,,mms,,,,,61.88.190.10,8070,,,,0,,,
1119,50502,505,02,"Optus MMS",mms,http://mmsc.optus.com.au:8002/,,mms,,,,,61.88.190.10,8070,,,,,,,
...
1126,50590,505,90,"Optus MMS",mms,http://mmsc.optus.com.au:8002/,,mms,,,,,61.88.190.10,8070,,,,,,,
```
What I am not clear on is how does TextSecure use this data? It could be as simple as adding the correct auth value for the row ```ID 1119```. Though at this point I am speculating.

**Comment by 5boro** [comment]
@puredistortion No, I think you're getting it right.

I see you've already opened the database and all, so maybe you could try and build TS from android studio, with the [modifications to the row](https://github.com/WhisperSystems/TextSecure/blob/master/apntool/apnlists/hangouts.xml#L1862)?

**Comment by TJC** [comment]
I'm struggling with MMS on Optus and Signal as well -- I commented in another thread, but then saw this one. I didn't realise that Signal is (I think?) using an independent APN list rather than the system settings.

Just regarding the Auth Type being PAP -- I don't think that's it.. I had Auth=none in my global APN and MMS used to work fine in other apps.

**Comment by Spm2011** [comment]
I'm having the same issue using Signal with my Sprint HTC One M8 on Android 6.0. I can send MMS but I can't receive them anymore. 

Here's my debug log:
https://gist.github.com/ce052c234e0fcb347769

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
