### ISSUE TITLE
Feature request: Sending dummy short messages

### ISSUE THREAD

**Issue by stefanb** [signalapp/Signal-Android#328]
TextSecure could mask meaningful communication between people by occasionally sending dummy random messages to random recipients at random times:
- Recipients would be chosen randomly between contacts that knowingly use TextSecure, so it could be recognized as such after decryption and automatically discarded by recipient.
- "Randomness" should be tweaked to level-out the legitimate messages, spoiling the traffic analysis of traffic retention data, preventing to weigh connections in the deducted social network graph or guessing sleeping/activity patterns.

People often have many unused messages in their monthly quota, so those could easily be used with no extra cost, or they value their privacy more than some money. Sender would need to enable this feature (opt-in) and define desired quantity (eg max 100 dummy messages per month, 2 dummy messages for every legitimate one, max 500 messages total counting legitimate and dummy ones...). The feature would need to be aware of roaming (disabled by default, optionally enable) and battery level (do not send if bellow eg. 30%).

http://en.wikipedia.org/wiki/Traffic_analysis#Countermeasures

Possible extensions: 
- Recipients could be able to let their peers know, that they do not want to participate in this and do not want to receive messages for whatever reason (opt-out).
- Recipients could also be chosen randomly between other contacts (those not using TextSecure yet) to promote its use (default message) or a custom explanation by sender. Those messages would be in clear text. As this might be annoying it should be very limited (eg max 1 message to a single recipient per month, only during daytime...) to not be too intrusive spam.
- Dummy messages could contain other peer's phone numbers (random selection from those participating in dummy messaging, not just their contacts), never to be shown to user, just to send dummy messages to, to further mask the real social network. It would be tricky to opt-out later on once your number starts circulating, so opt-outs would need to be spread this way as well and by direct reply dummy message or by defining a [TTL](http://en.wikipedia.org/wiki/Time_to_live) of each such number.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
