### ISSUE TITLE
lock action should close app instead of returning to lock screen

### ISSUE THREAD

**Issue by donjoe0** [signalapp/Signal-Android#3291]
https://github.com/WhisperSystems/TextSecure/issues/985 was closed by mistake, the issue is still not solved: the Lock action still takes me to the passphrase screen instead of taking me "out" of the app completely, even after the latest update.

**Comment by rhodey** [comment]
aha, thanks for the clarification @donjoe0-- looks like I didn't completely understand the behavior being requested.

**Comment by pR0Ps** [comment]
Personally, the way that the app currently behaves seems optimal to me.

After hitting the "Lock" button the user is switched to the passphrase screen. This allows them to verify that the app is actually locked before navigating to the home screen or another app. If the app just closed instead I could see users pulling down the notification shade or reopening the app to check that they actually need to enter the passphrase to use the app again.

**Comment by donjoe0** [comment]
So because some users will not trust the app to do what they just told it to do by tapping "Lock" and will voluntarily take a redundant extra step just to make sure, you think it's natural to force _all_ users to _always_ take that redundant extra step? And this when there's already a notification mechanism that lets you know when you have TextSecure closed but still unlocked?

"Optimal", yeah...

**Comment by ChaoticMind** [comment]
I also had the same reasoning as @pR0Ps when I saw the previous issue. So I'm voicing my agreement and think the current behaviour is better.

**Comment by jeremymasters** [comment]
There could always be a toast message with the message "TextSecure is now locked!"...That seems like a happy medium.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
