### ISSUE TITLE
Group chats from iPhone messaging show up as undownloadable MMS

### ISSUE THREAD

**Issue by alex** [signalapp/Signal-Android#3293]
https://gist.github.com/anonymous/2bbd21f790fedba16dd9 is the log

**Comment by alex** [comment]
Same error occurring with the latest textsecure: https://gist.github.com/anonymous/ff8571bb081d509afdb0

**Comment by riyapenn** [comment]
Still an issue?

**Comment by alex** [comment]
Haven't seen it in a while, honestly not sure if that's because my friends have all been trained to avoid putting me in an iphone group message, or because it's fixed :-/

**Comment by alex** [comment]
Still occuring, latest log: https://gist.github.com/anonymous/de351c04c14591894a57f7b63f85fde6

**Comment by 2-4601** [comment]
Operator seems to be [Cingular](https://github.com/WhisperSystems/Signal-Android/issues?q=is%3Aissue+cingular)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
