### ISSUE TITLE
Every group update creates a new avatar image to 'All images'

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3380]
1. Create a new group and add a group avatar to it
2. Open _All images_
3. Witness your shiny group avatar in the gallery
4. Update the group _n_ times (no need to change anything - just tapping the check mark is enough)
5. Open _All images_
6. Witness _n + 1_ shiny group avatars in the gallery
   ![immortan joe](https://cloud.githubusercontent.com/assets/174176/8064614/a8b71f2e-0ee4-11e5-9500-d5d8a74e0e6b.gif)

And if you actually change the group avatar all the old ones are still visible in the _All images_ view and they cannot be deleted.
- TS 2.17.0
  - Nexus 4, stock Android 5.1.1
  - Huawei **V8**800, Android 4.0.4

:fire::guitar::truck:

**Comment by cascheberg** [comment]
I just noticed that group images are only shown in "All images" for the person that updated the group,

**Comment by 2-4601** [comment]
That's tracked at #3045.

**Comment by cascheberg** [comment]
I have a fix, but a quick test showed that it requires a change to Signal on iOS as well, see #5395.
I even think that it is not possible to do it in a simple different way, see https://github.com/WhisperSystems/Signal-Android/issues/3045#issuecomment-202915569

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
