### ISSUE TITLE
This one weird trick, the devs don't want you to know, crashes recipients' TS

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3388]
(Couldn't resist with the title :( ·)

There seems to be no size checking on group name.
1. Update a group's name with _A Modest Proposal_ by _Jonathan Swift_ (Try the _Plain Text UTF-8_ option from [Project Gutenberg](https://www.gutenberg.org/ebooks/1080). Direct links don't work.)
2. After tapping the checkmark to broadcast the update **the other group members' TS will crash**

If you strip the Gutenberg metadata (introduction, license etc.) and just paste the actual text it won't crash. So the sweet spot is somewhere between 20-40KB.

In any case it's still a big wall of text that shouldn't be.
![a modest proposal-jonathan swift](https://cloud.githubusercontent.com/assets/174176/8141636/b5a2ce1e-1172-11e5-8f6a-1e2e6ae356c1.png)
- TS 2.17.0
  - Nexus 4, stock Android 5.1.1
  - Huawei U8800, Android 4.0.4

Debug log: https://gist.github.com/152ae1566c6c3d245ab0

```
E/AndroidRuntime( 4560): FATAL EXCEPTION: Thread-530
E/AndroidRuntime( 4560): Process: org.thoughtcrime.securesms, PID: 4560
E/AndroidRuntime( 4560): java.lang.IllegalArgumentException: byteCount < 0: -26331
E/AndroidRuntime( 4560):    at okio.RealBufferedSource.read(RealBufferedSource.java:46)
E/AndroidRuntime( 4560):    at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:249)
E/AndroidRuntime( 4560):    at okio.Buffer.writeAll(Buffer.java:705)
E/AndroidRuntime( 4560):    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
E/AndroidRuntime( 4560):    at org.whispersystems.textsecure.internal.websocket.OkHttpClientWrapper.onMessage(OkHttpClientWrapper.java:102)
E/AndroidRuntime( 4560):    at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:110)
E/AndroidRuntime( 4560):    at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
E/AndroidRuntime( 4560):    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/AndroidRuntime( 4560):    at java.lang.Thread.run(Thread.java:818)
```

**Comment by mcginty** [comment]
abridged version: effective. Power لُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ 冗

**Comment by jeremymasters** [comment]
@mcginty I wonder how many people had github notifications for this thread crashing their iPhones for that note! :)

**Comment by 2-4601** [comment]
Rough estimate >9000

**Comment by 2-4601** [comment]
I'm curious. Has anyone tried this with Signal contacts? I don't have any iOS devices to test with or Signal friends that I hate :)

**Comment by McLoo** [comment]
@FredericJacobs might wan't to try this :question:

**Comment by cascheberg** [comment]
This looks similar to https://github.com/square/okhttp/issues/1071 which was fixed in their 2.4.0 release.

**Comment by McLoo** [comment]
guess this can be closed, as ~~fixed~~ worked around with 038f24f

**Comment by 2-4601** [comment]
Or wait for a complete fix?
rhodey [wrote](https://github.com/WhisperSystems/Signal-Android/pull/3438#issuecomment-113238663)
> ... we'll have to take note of this in #3388 and make sure to keep it open until the 2nd half is also complete.

**Comment by FeuRenard** [comment]
038f24f / #3438 only shows effect when you use the system emojis.

The `android:maxLength` attribute [sets](https://developer.android.com/reference/android/widget/TextView.html#attr_android:maxLength) an `InputFilter` for the `EditText` object. This filter is [overwritten](https://developer.android.com/reference/android/widget/TextView.html#setFilters(android.text.InputFilter[])) in [EmojiEditText](https://github.com/WhisperSystems/Signal-Android/blob/ec63f7014e5e67993ac0793cc94de092d2b7eca6/src/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java#L29) when you use Signal's built-in emojis.

You can easily verify this by trying to reproduce this issue with the steps provided in the initial post. Do it one time with system emojis and another time with the built-in emojis.

**Comment by FeuRenard** [comment]
Current state:

- What is done: we prevent Signal users from setting too large group names.
- Has to be done ([according to @rhodey](https://github.com/WhisperSystems/Signal-Android/pull/3438#issuecomment-112996218)): Prevent Signal from crashing when it receives a too large group name.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
