### ISSUE TITLE
No contact names pictures appearing

### ISSUE THREAD

**Issue by jwalantsoneji** [signalapp/Signal-Android#3432]
It seems with more and more messages getting added to TextSecure, it has stopped showing contact names and pictures.
Randomly renders some contact names while scrolling but that's not permanent too.
Can it be solved with more caching?

**Comment by Mihahn** [comment]
Please add a debug log and information on your device (like model, Android version, TextSecure version, ...)! Otherwise it's nearly impossible to solve the problem...

**Comment by jwalantsoneji** [comment]
Debug log submitted: https://gist.github.com/78db79bf6e34bac71909

Model: Huawei Honor 6
Android version: 4.4.2
TextSecure version: 2.17.0

**Comment by Mihahn** [comment]
Thanks! I already guessed it and I think it is related to the issues #3275 and #3376. Please check if you have the built in permission manager and if yes, check the permissions for TextSecure (don't restrict anything) and try disabling the battery saver...

**Comment by jwalantsoneji** [comment]
Ohk.. did some liberation in terms of battery saving through killing apps..
Keeping it under observation, it's 10pm here. Will check again tomorrow morning to see when phone stabilizes.

**Comment by jwalantsoneji** [comment]
No luck with getting contact names, pics on the TextSecure yet.

**Comment by 5boro** [comment]
Could you find the permissions manager?

**Comment by jwalantsoneji** [comment]
There are couple of I could find.
One restricts notification area items, the other kills apps when phone locks.
Both are disabled now.

**Comment by 5boro** [comment]
What EMUI version are you on?

**Comment by jwalantsoneji** [comment]
Its the latest available by the provider: EMUI 2.3
The full version number is: H60-L04V100R001C00B109SP01

**Comment by 2-4601** [comment]
@jwalantsoneji Have you experienced this after disabling those EMUI restrictions?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
