### ISSUE TITLE
No "unavailable" toast for quick response, when TS is locked

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#3464]
Tested with CM 12.1

If TS is locked I don't get the toast "Quick response unavailable when TextSecure is locked!" though the code gets executed.
Instead system(?) is toasting "Message sent to Number"

**Comment by rhodey** [comment]
confirmed on N5 stock Android 5.1.1, TS 2.21.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
