### ISSUE TITLE
long mms group messages don't send

### ISSUE THREAD

**Issue by greenbrier** [signalapp/Signal-Android#3465]
When I send group messages over a certain length, the send fails.  If I break the same message up into multiple shorter messages to the same group, the messages send.  I'm not sure exactly what the threshold is, but it seems to be somewhere around the character limit for a single SMS text.  This only happens with insecure group MMS messages.  If I send the same message to a group of TextSecure users, the TextSecure chat message delivers without a hitch.

Device info: Samsung Galaxy Avant SM-G386T, stock Android 4.4.2, TextSecure 2.19.1, also have XPrivacy installed, which I mention because sometimes I've seen it break functionality in other apps
App state: not sure what's useful here -- it's registered to send and receive SMS and MMS as well as chat
Debug logs: https://gist.github.com/anonymous/7e3983e8b5425812c2f2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
