### ISSUE TITLE
MMS reception crashes data connection

### ISSUE THREAD

**Issue by jellium** [signalapp/Signal-Android#3484]
Hi, everytime I recieve a MMS through TextSecure (when using TextSecure also for SMS/MMS for the sake of uniformity despite I know it's not encrypted), first the MMS is not downloaded, secondly my data connection crashes (3G or LTE I believe). I need to delete the MMS and restart the data connection. If I restart the data connection before deleting the faulty MMS, the data connection will stop when trying to download the MMS.

I have now separated SMS/MMS from TextSecure encrypted-push now in order to avoid this, but I believe this should be fixed.

Thanks for all your amazing work.
- Device info: Samsung Galaxy Note 3, CyanogenMod 12.1-20150531-NIGHTLY-hlte (Android 5.1.1), TextSecure 2.19.1
- Debug logs generated by TextSecure while the data connection was lost after the reception of the MMS push notification: https://gist.github.com/jellium/83210298af4844970082#file-mmsissue

**Comment by mcginty** [comment]
Hmm, yeah it looks like the file created to receive the MMS body in the cache was deleted. Possible you were in a low-storage situation or cleared your cache. I should just create those temporary files in another location to avoid the issue.

**Comment by jellium** [comment]
Anything I can do to prevent this problem to occur albeit I don't use TextSecure for MMS anymore?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
