### ISSUE TITLE
Input box does not clear properly after quick reply, expand & send

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3494]
1. Receive a message notification
2. Tap quick reply
3. Write something
4. Tap the top right corner icon to expand and open TS
5. Tap send
6. Go to conversation list and notice your message is correctly snipped (but there's no "Draft :" as there shouldn't)
7. Come back to the conversation
8. Notice that your text has reappeared in the input box

![dune time](https://cloud.githubusercontent.com/assets/174176/8418216/50ace904-1eba-11e5-92e1-2fcabb7c6345.gif)

TextSecure 2.20.0
Nexus 4, stock Android 5.1.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
