### ISSUE TITLE
Quick response sending sms instead of data on galaxy you note 2

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#3512]
My brother and I have been using Textsecure since it's infancy. We tried the quick response to phone calls and it works fine for when he calls me and I reject him but sends regular sms when he rejects my calls. I'm using a galaxy s4 with Android 5.0.1,he is using a note 2 with Android 4.4.2.
Log here:https://gist.github.com/af4ef023402ad5cbc68e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
