### ISSUE TITLE
emoji drawer doesn't vibrate like standard keyboard

### ISSUE THREAD

**Issue by turtlekiosk** [signalapp/Signal-Android#3527]
Kind of weird when I switch from my normal keyboard to the emoji drawer because the keyboard vibrates on keystrokes unlike the emoji drawer.

**Comment by mcginty** [comment]
I don't know that there's a way to get the vibration preferences for the active keyboard.

I have vibration turned off on my keyboard, for example, so having it on in all cases would be equally weird for me in the other direction.

**Comment by johanw666** [comment]
Would simulating a keypress (and discarding the key) not let the keyboard vibrate depending on its default? Like the solution in http://stackoverflow.com/questions/8696489/android-simulate-key-press

**Comment by turtlekiosk** [comment]
The backspace button on the emoji drawer vibrates though.

**Comment by eosrei** [comment]
My friend's phone: Samsung S3 Mini (4.1.2)

Vibrate is disabled system-wide, but the backspace button vibrates in the emoji drawer. Not the emojis, just the backspace. Debug log available, but I doubt it's needed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
