### ISSUE TITLE
RFE: Option to change phone number and update your number with contacts

### ISSUE THREAD

**Issue by Hooloovoo** [signalapp/Signal-Android#3558]
At the moment, the guide for changing a phone number is very unintuitive:
http://support.whispersystems.org/customer/portal/articles/1468975-what-happens-when-i-change-my-phone-number-
with no actual guidance from the app to help you through the process.

Compare this to Telegram:
https://telegram.org/faq#q-how-do-i-change-my-phone-number
where there is a "Change Number" option in settings and the app will update your number in any mutual contacts' phones.

WhatsApp also seems to have a Change Number wizard (though only those currently in chats with you are notified):
http://www.whatsapp.com/faq/en/android/27585377

**Comment by generalmanager** [comment]
Great idea, a wizard and/or mass notification function of either all contacts or all TS-compatible contacts would help a lot. Especially because the current advice is probably not found by a huge part of the userbase.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
