### ISSUE TITLE
Direct video capture

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#3564]
Similar to how we do direct photo capture, maybe letting users hold the shutter for video.

Spawned from https://github.com/WhisperSystems/TextSecure/issues/520.

**Comment by cdonc** [comment]
Any news or milestones for this feature?

**Comment by moxie0** [comment]
@cdonc Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by zero77** [comment]
Duplicate of #6279

**Comment by nrizzio** [comment]
@zero77 This is not a duplicate of #6279. #6279 is about being about to switch to the front facing camera within a video call. This issue is about being able to record a video to send to someone without ever having to leave the app.

**Comment by zero77** [comment]
yes, sorry you are right

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
