### ISSUE TITLE
Support flash in direct capture mode

### ISSUE THREAD

**Issue by agrajaghh** [signalapp/Signal-Android#3590]
Would be good to have a button to set the flash during direct capture to enabled/disabled/auto

**Comment by bkchr** [comment]
Hi, I would like to implement this feature. You got any ideas how the visual implementation could be done? 
I created two mockups in the ide, but maybe the new button would be too much?
Horizontal version:
![horizontal]
(https://photos-6.dropbox.com/t/2/AABORBJpuQ1XpOGTEma1ydtXqQNd9X9XkiESgst7UTgpDg/12/3714191/png/1024x768/3/1438448400/0/2/horizontal.png/CI_Z4gEgASACIAMgBCAFIAYgBygBKAIoAygH/denfXzyoQgL5nnb6Wo2ctXRRqxoq86yoR_z3nWYaI4Y) 
Vertical version:
![vertical] (https://photos-3.dropbox.com/t/2/AABPYbD5qs2q5Lf7gsD746ghJ6-DqqLJiDoR38cYNmm8kw/12/3714191/png/1024x768/3/1438448400/0/2/vertical.png/CI_Z4gEgASACIAMgBCAFIAYgBygBKAIoAygH/CWeh04V0hDirOYsr4JW8W_qlRuG14el-cIUZf0jPHRg)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
