### ISSUE TITLE
"Send TextSecure message" should be renamed to something like "Type TextSecure message" and should have a lighter gray

### ISSUE THREAD

**Issue by wp9015362** [signalapp/Signal-Android#3609]
Hello,

when the message input box is empty, then there is a text in there in gray which says "Send TextSecure message".

Wouldn't it make more sense to rename this to "Type TextSecure message"?

For comparison:

In WhatsApp for Android it says "Type a message". And in Telegram for Android it simply says "Message".

Also:

In both WhatsApp for Android as well as in Telegram for Android, this text has a lighter gray color compared to TextSecure.

In TextSecure the text almost is as dark as the text that is actually typed into the message input box.

It would be nice if you could give the text a lighter gray as well to differentiate it more from the text that is actually being typed into the message input box.

And, as already mentioned in https://github.com/WhisperSystems/TextSecure/issues/2769, it would also be nice if you could adjust it's font size to match that of the messages in the bubbles.

Regards

**Comment by 2-4601** [comment]
More comparisons:

**kik:**
_Type a new message_

**Viber:**
_Type to compose_

**Facebook Messenger:**
_Write a new message_

**Snapchat:**
_Send a chat_

**Stock 4.0 SMS app**
_Type message_

**Google Messenger SMS app:**
_Send message_

**Hangouts:**
_Send Hangouts message_

**Signal iOS** ![1f610](https://cloud.githubusercontent.com/assets/174176/8633602/ea35538c-27d8-11e5-9ba7-3ce3f3ddffe7.png)
_New message_

**Comment by McLoo** [comment]
And in landscape mode the button text then would be 'type TextSecure message' 😀

**Comment by wp9015362** [comment]
> @McLoo wrote:
> 
> And in landscape mode the button text then would be 'type TextSecure message' :grinning:

What do you mean? What does it have to do with landscape mode?

**Comment by McLoo** [comment]
![screenshot_2015-07-11-14-43-29](https://cloud.githubusercontent.com/assets/5326916/8634348/b325722e-27f5-11e5-95ba-e73b44c92a40.png)

**Comment by wp9015362** [comment]
@McLoo :

You seem to be using an ancient version of TextSecure or something seems to be wrong with your TextSecure installation.

TextSecure 2.21.0 is using material design and does not have a button which says "Send TextSecure message".

TextSecure 2.21.0 has a round button with blue color and with a logo inside it, not with a text.

What version of TextSecure are you using?

**Comment by dkasak** [comment]
@wp9015362 The latest TextSecure version does this too. TextSecure forces portrait mode but if you force it to appear in landscape mode (probably when you access TextSecure from another application that is forcing landscape mode), you will see this. I've had it happen a few times.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
