### ISSUE TITLE
When emoji keyboard is open, long-press transport switcher popup opens down rather than up.

### ISSUE THREAD

**Issue by moxie0** [signalapp/Signal-Android#3622]

**Comment by 2-4601** [comment]
Milestone typo? Should be in 2.22.1?

**Comment by mcginty** [comment]
does not appear to be an easy way to fix this in ListPopupWindow without passing through the KeyboardAwareLinearLayout container to know when to specify a manual vertical offset to push it up.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
