### ISSUE TITLE
Visual Tracking of Favorite Threads

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#3660]
I think it'd be helpful to have a way to keep easy visual focus on favorite threads.  One reason that comes to mind for this is that I may have a favorite contact or three that I want to always make sure I can see the last message.  I want to be certain to respond to them and it would jog my memory easily if they are "at the top".  This could be accomplished in a few ways.  Some that come to mind are:
1. A system like currently used when searching for contacts where certain threads stay on top of the entire thread list.
2. An icon that would change the UI to show only favorited threads but when toggled would change back to all threads.  In addition, using the android back button would return to full thread list too.
3. Swiping the thread list (left or right?) would show only favorited threads; swiping back would of course return to normal view. In addition, using the android back button would return to full thread list too.

Perhaps a star icon could be used to indicate "favorite" where that's needed.  Also, "favoriting" a contact could be done by long-press options and/or when tapping the contact's name at the top of the thread and indicated by one of those lollipop-looking switches like the mute conversation one.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
