### ISSUE TITLE
Can't open MMS attached file (Free Mobile - Illiad Free.fr)

### ISSUE THREAD

**Issue by Nemotaku** [signalapp/Signal-Android#3667]
Hello, 

Same issue as described in closed #1990 

I use MMS Monster to check, the result is here : https://gist.github.com/bfd18e12302faa6223c5 

My Wifi is off and I have no message error, only "Connect to MMS server..;" then nothing happened and the "Download" button come back. 

Emmanuel

**Comment by 5boro** [comment]
Salut, 
From the [Free Mobile support page](https://mobile.free.fr/assistance/65.html) : 
 ```MMSC : http://mms.free.fr (sur les périphériques Samsung il est préférable d’indiquer http://212.27.40.225 en cas de problème) ```

You should try with this settings

**Comment by Nemotaku** [comment]
I tried. Nothing changed.

**Comment by vser1** [comment]
I got it working by overriding the MMSC URL in Signal settings (letting the APN to the default Free MMS).
 Settings > SMS and MMS > Manual MMS settings > MMSC URL > [Using custom] http://212.27.40.225
And I could retrieve MMS. I can't confirm it works for sending nor that it works with all possible MMS but at least I could fetch 2 of them.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
