### ISSUE TITLE
Push registration service fail on the phone running Android 2.3.6

### ISSUE THREAD

**Issue by kiral6** [signalapp/Signal-Android#3673]
I have received the sms verification,   But registration takes some time and then fail.
I get this exception information on my debug log :

> RegistrationService(6251):  java.io.IOException: SERVICE_NOT_AVAILABLE
> RegistrationService(6251):  at com.google.android.gms.gcm.GoogleCloudMessaging.register()
> RegistrationService(6251):  at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:246)

GCM works fine on my moto ( Android 4.1.2 ), but always received a SERVICE_NOT_AVAILABLE on Samsung Galaxy, android 2.3.6.

This is the same solution, please?
http://stackoverflow.com/questions/17618982/gcm-service-not-available-on-android-2-2/17721385#17721385

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
