### ISSUE TITLE
SMS failed to send because of phone number format

### ISSUE THREAD

**Issue by ewmalmbe** [signalapp/Signal-Android#3683]
Contact #1 phone number formatted "+1 (XXX) XXX-XXXX"  which was done due to a early version of iOS Signal. I switched the conversation from TextSecure to Insecure SMS using the above phone number format but received "Not delivered", "Failed to send". I texted contact #2 who's SMS phone formatted XXX-XXX-XXXX and the message sent. I changed contact #1 to the same format as contact #2 and the message was sent/received. 

Not a big problem but wanted to raise awareness that maybe a little regex could be applied to the SMS send function.

Android v2.21.0

Edit... Upon further investigation it may be the country code preventing the message to be sent. Anyone else having this issue or just me?

**Comment by valerie-roske** [comment]
Hey, I was having this issue too. I hadn't been able to send messages to certain people and I thought it might be because they didn't have smartphones, but realized the country code was the issue as it started working once I edited the contact.

**Comment by mcginty** [comment]
If you try "(XXX) XXX-XXXX" does it succeed? So it's just the prepending of "+1" that was causing a failure?

**Comment by valerie-roske** [comment]
I think using the "(XXX) XXX-XXXX" format (without the country code) also didn't work, but I can test that again. I also believe that I tried "X-XXX-XXX-XXXX" without success.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
