### ISSUE TITLE
direct capture preview should obtain orientation from accelerometer (otherwise breaks when forced portrait)

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#3693]
TextSecure doesn't recognize the orientation when taking photos in full screen mode, so photos that should have landscape orientation are presented as portrait in conversation.

Stock 4.4.4 on Sony Xperia Z3C

BTW - the UX and design of new features in TS are fantastic!

**Comment by 2-4601** [comment]
I can only reproduce this with the following steps:
1. Hold phone in portrait
2. Tap quick capture
3. Tap full screen
4. Turn phone landscape
5. Take a shot
6. Photo orientation is portrait

But if my phone is already in landscape before I tap quick capture then the orientation will be correct.

Nexus 4, stock 5.1.1, TS 2.23.0

**Comment by bungabunga** [comment]
with me in full screen mode the picture is always sent as a portrait.

On July 18, 2015 10:11:34 AM CEST, 2-4601 <notifications@github.com> wrote:
>I can only reproduce this with the following steps:
>1. Hold phone in portrait
>2. Tap quick capture
>3. Tap full screen
>4. Turn phone landscape
>5. Take a shot
>6. Photo orientation is portrait
>
>But if my phone is already in landscape before I tap quick capture then
>the orientation will be correct.
>
>Nexus 4, stock 5.1.1, TS 2.23.0
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/TextSecure/issues/3693#issuecomment-122510976


- 359

**Comment by 2-4601** [comment]
Just removed my previous comment as it turns out I actually **cannot reproduce this**. I thought I could but it was just because I took the photo too fast, i.e. without waiting for the orientation change.

Nexus 4, stock 5.1.1, TS 2.23.0

**Comment by mcginty** [comment]
Z3C here (albeit 5.0.2), can't reproduce either unfortunately

**Comment by bungabunga** [comment]
@mcginty would this help:
https://gist.github.com/bungabunga/4e83b0cad3bcd5e4fe27

**Comment by McLoo** [comment]
@bungabunga you commented before the image was fully uploaded

**Comment by 2-4601** [comment]
@bungabunga 
Stupid question: do you have force portrait on?

**Comment by bungabunga** [comment]
@2-4601: not stupid at all!! in fact you solved the mistery! yes, i have auto-rotate set to off most of the time because it irritates me if the screen turnes around when i lay in bad watching my phone (i lay in bed a lot;)

@mcginty: photos taken with phone's default camera always show the orientation right, even if auto-rotate is set to off. could you make the same to TS's camera?

@McLoo: i don't have a computer near me and i post from my phone, which is a pain...

**Comment by mderazon** [comment]
I am wondering what's the status of this issue.
I also don't like to have auto rotate enabled and Signal's built in image capture doesn't use the accelerometer data like the OP mentioned.
I think that Signal built in image capture is great feature. Very handy to quickly capture and share images. But I think that using the device orientation is not a great choice.

WhatsApp for example has this set to use the device accelerometer (I guess that that is how it's done, maybe I'm wrong?)

**Comment by b0urb0n** [comment]
Currently using 4.11.5 on Android 6.0 (yeah, I know) and this issue still exists.  Any updates?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
