### ISSUE TITLE
TS not displaying contact name

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3711]
- Receive an sms by an unknown number
- Save the number to your contacts
- TS should now display the name of the contact, but it doesn't

Speaking of contacts.. what is the point of syncing contacts with textsecure? (It's an honest question, I don't know what that feature is there for). Also because, the contacts that appear synced using textsecure don't have a name, just a phone number...

**Comment by 2-4601** [comment]
Tried this but not sure if I could reproduce:
1. Receive SMS from unknown number (TS as my default SMS app)
2. Open the SMS from notification
3. In the conversation tap the avatar to open system contacts app view/card
4. Create a new contact within the system app view
5. Return to TS conversation
6. TS still displays # in the avatar
7. Return to conversation list
8. Now TS displays the name I gave

Is the step 6 what you meant? If so I think the current situation is good enough. It will display the name after it has queried the system contacts.
TS 2.23.0, Nexus 4, stock 5.1.1

> what is the point of syncing contacts with textsecure?

Contact info, such as name and profile picture, are pulled from the system contact app/provider. If TS cannot access them it can only show the number. Some ROMs, permission apps, etc. can prevent apps from accessing the contacts.

**Comment by oaim** [comment]
> Is the step 6 what you meant?

No, in step 7 I still don't see the name of the contact

**Comment by moxie0** [comment]
@oaim are you running a non-stock rom?

**Comment by oaim** [comment]
No, all is normal

**Comment by oaim** [comment]
Not sure if this helps, but here is what I get when I tap to edit:
![media-20150721](https://cloud.githubusercontent.com/assets/12774519/8806855/05aa2b76-2fd9-11e5-9f20-59b5af83673b.png)

**Comment by heyimgay** [comment]
Is this still an issue after #4259

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
