### ISSUE TITLE
Avatar color in group message notification is wrong

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3714]
When someone writes in a group chat and you pull down the notification bar, the contact's profile picture is wrong (assuming they have a default "letter+color" avatar). The correct letter is shown but the background is gray.

**Comment by 2-4601** [comment]
Confirmed with TS 2.23.0, Nexus 4, stock 5.1.1.

Group notifications do not use the color of the contact in the initial avatar.

**Private message notification:**
![private](https://cloud.githubusercontent.com/assets/174176/8765775/96ad716e-2e26-11e5-8d73-5b2705e3c203.png)

----------
**Group message notification:**
![group](https://cloud.githubusercontent.com/assets/174176/8765776/9c23b41e-2e26-11e5-89e2-63a5c1151eea.png)

**Comment by oaim** [comment]
Maybe this is intentional to tell group notifications from individual notifications, but I think it should be handled differently

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
