### ISSUE TITLE
Cannot add member to group mms

### ISSUE THREAD

**Issue by thoraxe** [signalapp/Signal-Android#3716]
I totally understand that certain group features are not available on mms. However, when creating a group message of non textsecure users (which then defaults to mms)  it does not appear possible to add a member to the group after the first message. 

Is this a byproduct the of the mms protocol? 

Device  : samsung SM-G900T (kltetmo)
Android : 5.1.1 (G900TUVU1FOF6, LMY47X.G900TUVU1FOF6)
Memory  : 32M (0.10% used, 128M max)
Memclass: 128
OS Host : SWHC3813
App     : TextSecure 2.22.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
