### ISSUE TITLE
Delayed MMS meesages

### ISSUE THREAD

**Issue by littleTrex** [signalapp/Signal-Android#3736]
I am getting an issue where received MMS messages get delayed from both group conversations and from 1-on-1 conversations.

https://gist.github.com/anonymous/d887f38ffe34624975ac

Here's also some an Imgur album of both my current APN settings and a snapshot of the delayed MMS. (It's suppose to be a message from a group conversation, but apparently it's treated as a 1-on-1 as it's trying to download the MMS.)

https://imgur.com/a/jtu97

**Comment by littleTrex** [comment]
Been doing some tinkering.
I wiped all APNs from the apns-conf.xml file under /system/etc/ . I then manually input my carrier's APN (AT&T), and I'm still getting the same issue.

I made another debug log though and noticed something:
https://gist.github.com/anonymous/f2c879b17650d7f2cb2c

Line 22:
W/ApnDatabase( 2573): Returning preferred APN LegacyMmsConnection$Apn{ mmsc: "http://mmsc.cingular.com", proxy: "wireless.cingular.com", port: 80, user: none, pass: none }

Why would it be trying to use Cingular?

**Comment by Lockyc** [comment]
Could it be because AT&T used to be cingular?
From Wiki:

> AT&T Mobility, formerly known as Cingular Wireless, is a wholly owned
> subsidiary of AT&T that provides wireless services to 121.8 million
> subscribers in the United States


--
Lachlan Collins

**Comment by littleTrex** [comment]
Yeah, you're right. They were Cingular before. Don't know I didn't think of that. That would explain why it's trying to use the Cingular address.

Is there anyway to manually tell TextSecure to use different MMS APN settings then? I can't seem to find an option to do so in the app settings.

**Comment by f41c0r** [comment]
I know you were messing with /etc/, but did you try looking under 

Wireless & Networks -> Mobile Networks -> Access Point Names 

In the general settings? I would think editing it /etc/ would cause it to stick, but maybe not?

**Comment by littleTrex** [comment]
Yeah, I tried modifying my APNs under those settings as well. Here are my current APNs:

http://imgur.com/a/GKer4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
