### ISSUE TITLE
All images, group creation and name updates using old emoji set

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3751]
Seems like 13578bb8c0897735b6e7562654ecbd893982d141 solved only 1/3 of #3676:lock:
TS 2.23.1

**All images:**
![screenshot_2015-07-17-15-29-49](https://cloud.githubusercontent.com/assets/174176/8747125/c364ab1c-2c98-11e5-9563-5a972a1ecbc6.png)

---

**Group name edit:**
![screenshot_2015-07-17-15-25-28](https://cloud.githubusercontent.com/assets/174176/8747084/4d197b9a-2c98-11e5-9190-eac946027c41.png)

**Comment by 2-4601** [comment]
Found one more. When the someone else changes the group's name the `Title is now` status string uses old emojis:
![screenshot_2015-07-22-12-12-09](https://cloud.githubusercontent.com/assets/174176/8822105/b1261914-306b-11e5-8dac-07001438ad7c.png)

**Comment by mcginty** [comment]
this will require us using custom views for all of our actionbar titles, nontrivial, taking out of 2.27

**Comment by p4nci** [comment]
@2-4601 is this still relevant?

**Comment by 2-4601** [comment]
Group name edit does not have the issue anymore, the rest are not resolved.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
