### ISSUE TITLE
Drafts' order not maintained on SMS import

### ISSUE THREAD

**Issue by ChaoticMind** [signalapp/Signal-Android#3795]
1. Have an SMS conversation in TextSecure with contact A
2. Have an SMS or data conversation in TextSecure with contact B
3. Send an SMS to contact A using the default SMS app ("Messaging") (receiving also works)
4. Send or receive a message to/from contact B
5. Write a draft to contact A. We now have the draft with contact A as the top-most conversation (latest)
6. "Import system SMS database" into TextSecure. This properly imports the old SMS into the TextSecure conversation with contact A.
7. The draft with contact A is no longer the top-most conversation. Instead, the conversation with contact B is now the top-most conversation. (i.e. it returns to the state at point4)

Expected behavior: 
The draft with contact A should remain the top-most conversation as it contains the latest interaction (draft)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
