### ISSUE TITLE
Support SMS URIs with no number?

### ISSUE THREAD

**Issue by jpsingleton** [signalapp/Signal-Android#3828]
I previously commented on a closed issue https://github.com/WhisperSystems/TextSecure/issues/2578 and pull request https://github.com/WhisperSystems/TextSecure/pull/3030 but I'm not sure these will get noticed.

Would it be possible to extend support for SMS URIs to handle links with body text but no number (aka no `path` or `data` variables set in the code)? e.g. `sms:?body=Hi%20there`.

The use case is you have a message but want to choose who to send it to. Like you can with [`mailto:?subject=Hi%20there&body=Hello%20there`](mailto:?subject=Hi%20there&body=Hello%20there) and `whatsapp://send?text=xxx`. Other SMS apps already support this behaviour.

I'm not sure if it's just as simple as not throwing the `URISyntaxException` in `Rfc5724Uri.java` and returning an empty path.

I'm happy to have a go at doing this if it's something people want and has a chance of getting merged.

**Comment by mcginty** [comment]
Yeah, looks like we should let people choose via ShareActivity. That sounds like a reasonable PR idea to me!

**Comment by jpsingleton** [comment]
@mcginty OK, I've got this working and it's a very small change. It's tested on device and all looking good. However, I've been struggling for ages to get the unit tests to run. I think it might be related to issue https://github.com/WhisperSystems/TextSecure/issues/3474. I don't want to check in broken tests but I can't verify they work. Any ideas?

**Comment by pgaubatz** [comment]
Hey @jpsingleton!

Are you planning on submitting a PR on this issue?
I am asking, because I've just stumbled upon this bug... 

Cheers,
Patrick

**Comment by jpsingleton** [comment]
That's the plan but I need pointing to some better documentation on how to run the unit tests so I can be sure I haven't broken anything. Also I need to merge from upstream which is non-trivial as the folder structure has changed with the rename to Signal.

**Comment by jpsingleton** [comment]
@pgaubatz I was going to have another go at applying my changes to a fresh fork but it looks like you've beaten me to it! Good work. It's probably worth asking someone like @mcginty or @moxie0 to get this merged. I'd like to see this in the stable version on play. It's the only thing currently stopping me from recommending Signal over WhatsApp. Perhaps a quick code review would help.

I had success simply removing the `|| parts[1].isEmpty()` so I'm not sure if the other changes are required. Are these additional bugs in the implementation of [RFC5724](https://tools.ietf.org/html/rfc5724)? Does `body` have to exist if `path` is empty? I can't find anything specific in the [code style guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines) but if the style is to return early to avoid nesting then I'd try and preserve that.

The tests look pretty similar to mine but when using TDD I couldn't get them to fail before applying the change. That's why I was keen to keep the change as small as possible but if you have them running and are happy with the coverage then it should be fine. There doesn't appear to be any CI on this repository but I hope they get run as part of the final build process.

**Comment by pgaubatz** [comment]
Hey @jpsingleton!

The thing is: What is Signal supposed to do with a URI like this `sms:?foo=bar`? Neither the recipient number(s) nur the body could be prefilled... So I figured it makes sense to reject such URIs...

Regarding the tests: The test suite successfully completes and I've tested the .apk on a real device to verify that it works correctly. So I am pretty confident that I haven't broken something else...

Do you think that simply submitting the PR is not "enough"? I am not sure how I am supposed to ask @mcginty or @moxie0 ... :) 

Cheers,
Patrick

**Comment by jpsingleton** [comment]
OK, all sounds good to me. Less tests need changing this way.

I'd wait and see what happens with the PR now. If there are no comments or a merge after a while then poke someone.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
