### ISSUE TITLE
Not all messages unblocked in notifications when app is unlocked

### ISSUE THREAD

**Issue by heartsucker** [signalapp/Signal-Android#3832]
TS: 2.23.3
Phone: Moto G 2014
OS: CM 12.1-20150725-NIGHTLY-titan
Android: 5.1.1

I've had trouble reproducing this one, but on one instance it was
1. Lock phone
2. Receive multiple messages (in a single conversation)
3. Open app, unlock
4. Before clicking conversation, look at notifications in the notification center while app is open
5. The first shows the unblocked text, the rest show "Gesperrte Nachricht..." or whatever the English string is.
6. Opening and closing the notification center does not change the state

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
