### ISSUE TITLE
Notification avatar color not theme aware (properly)

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#3866]
- receive single thread message
- have light theme avatar color in notification
- open TS or have it already open
- enter any thread Edit: except for the one notified of course
- check notification and have a dark theme avatar now

(dark theme scenario this is :new_moon_with_face: )

![screenshot_2015-08-01-23-10-22](https://cloud.githubusercontent.com/assets/5326916/9023609/922c1a14-38a3-11e5-8b4c-ba7b2b0a2048.jpg)

**Comment by moxie0** [comment]
I think it is theme aware, notifications are always light right?

**Comment by McLoo** [comment]
But then it should not change color... 

Besides that,  even this 'light' difference looks weird if you got used to the colors.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
