### ISSUE TITLE
TextSecure still slow / bad performance

### ISSUE THREAD

**Issue by SlappyHours** [signalapp/Signal-Android#3868]
Even though the performace of TextSecure has been improved, it is still worse compared to other messengers:

In a pretty long conversation I experience the following issues (on a Moto X 1st gen):
- When sending a message there is a short delay before the message is visible in the text view. Then it takes quite some time ("Now...") before the message is marked as sent. Sometimes the "..." animation stops for a moment
- When receiving a message I sometimes hear the notification sound but the message pops up seconds later
- It is especially worse when sending and receiving (multiple) messages at the same time. Sometimes the keyboard is lagging (not responding while typing) and the symptoms described above are worse

I still like textsecure, but it just does not feel really smooth - I am always suprised when switching to a different messenger how smooth it is.

**Comment by Dyras** [comment]
Are you by any chance not using the stock keyboard?

**Comment by SlappyHours** [comment]
Keyboard is "Android Keyboard (AOSP)" - the default one.

**Comment by oaim** [comment]
Related (and kind of duplicate) https://github.com/WhisperSystems/TextSecure/issues/3651

**Comment by Dyras** [comment]
This has started affecting me as well. Weeee!
https://gist.github.com/anonymous/73009b060e2c99287e06
https://gist.github.com/anonymous/e2d5afca753252eed868
https://gist.github.com/anonymous/99ea8143d8f4098957dc

**Comment by mcginty** [comment]
significant improvements on the way. thanks for the logs and traces, @oaim @Dyras  and @SlappyHours!

**Comment by Dyras** [comment]
@mcginty I'm still experiencing a delay before sent messages "jump" up to the chat log. It's really snappy on both Wickr and Telegram. Is this related to the encryption or something similar? Or is it not supposed to be like this?

Galaxy Nexus Kitkat 4.4.4.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
