### ISSUE TITLE
More space for MessageNotifier_mark_read in notifications

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3870]
Message notifications have two buttons: one for marking the message as read and the other for quick reply.

The language translations for `MessageNotifier_mark_read` have an average character length of 14.
For `MessageNotifier_reply` the average is 6.52 characters.

Yet they both have the same amount of space in the notification. This causes the `MessageNotifier_mark_read` to be truncated in nearly all of the languages.
![chew bubble gum](https://cloud.githubusercontent.com/assets/174176/9113878/84eb9194-3c5f-11e5-801b-539fd9c9cbd4.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
