### ISSUE TITLE
Soft keyboard covers emoji keyboard when readjusting input cursor position

### ISSUE THREAD

**Issue by turtlekiosk** [signalapp/Signal-Android#3874]
If I'm typing with the emoji drawer open and I press a different part of the TextView, the system soft keyboard will pop up and if I want to continue typing emoji, I have to reopen the emoji drawer.

![emojibug](https://cloud.githubusercontent.com/assets/1096636/9037648/6414e494-39bb-11e5-9aba-f1660c4fc194.gif)

**Comment by mcginty** [comment]
no other messenger does this - i'd be worried about accidentally preventing the softkey from opening. will look into it at some point though!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
