### ISSUE TITLE
My own messages are shown as unread

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#3877]
Hi. My own messages are sometimes shown as unread. At first I thought I was crazy, but it turns out that the app on occasion shows my own messages as unread, which makes no sense.

Galaxy Nexus
Kitkat 4.4.4
Paranoid Android
Has happened for the last 3 betas now. 2.24.1 included.

Typically this is how it happens:
1. I send something to someone
2. I press back twice on my Galaxy Nexus to close the app
3. When I start the app again I can see that my own message is unread

Sometimes I only press back once, and I can still see my message as unread.
![2015-08-04 10 58 50](https://cloud.githubusercontent.com/assets/12563436/9070492/3639d166-3af0-11e5-8904-8988a08f48ab.png)

If there is anything I can do to help, feel free writing instructions.

**Comment by Dyras** [comment]
https://gist.github.com/anonymous/5f3474d73240e0a954b8
If that helps.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
