### ISSUE TITLE
Recent update broke MMS settings, changed SMS-to-many

### ISSUE THREAD

**Issue by owenblacker** [signalapp/Signal-Android#388]
Before the recent update, sending an SMS to multiple recipients correctly queued an SMS to each recipient independently.

Now it converts it to an MMS group conversation, which is not the desired behaviour, for me. Is it possible for this to be a configurable option?

Separately, this MMS conversation required me to look up the settings and re-enter them into Text Secure. I would be more than happy to grant access for Text Secure to read my device's MMS settings, were I prompted to do so.

I'm using a Nexus 4, running Android 4.3, build JWR66Y. Text Secure doesn't have an About page with a version number (which would be useful) but the Play Store (in en-GB) shows the date 21 Oct 2013 for the app, with the description talking about Changes in 1.0.2

**Comment by MatejKovacic** [comment]
I have TextSecure 2.11.1 (the latest version) on HTC One Mini. I have received MMS in TextSecure, but cannot open it. TextSecure is connecting to MMS server, but after a while it times out. I am using Simobil (MCC: 293, MNC: 40).

My settings are:
URL MMSC: http://mmc
Proxy server for MMS: 80.95.224.46
Proxy server port for MMS: 9201
MMSC username: simobil
MMSC password: internet
MMS proxy: (without)

Any idea?

**Comment by bungabunga** [comment]
@MatejKovacic if you have a VPN active, shut it down and TextSecure will be able to retrieve your MMS.

**Comment by MatejKovacic** [comment]
VPN is not active. Actually, I have disconnected my device from wifi network and was only connected via Simobil 3G/LTE...

**Comment by nimdajitam** [comment]
I'm experiencing the same issue as Matej described here after updating TexTesecure (from 2 versions back) without changing MMS settings in any way. I've tried with Andorid defaults (TextSecure defaults) and manual settings ... Sending MMS works fine!

I've discovered something interesting. When I get MMS notification message expiration time (for downloading MMS content) displayed in TextSecure is same as time when notification was received. What means that it's a priori expired!

Downloading MMS content on default Android app works fine too.

**Comment by mcginty** [comment]
Hey @MatejKovacic and @nimdajitam, I'm going to need debug logs after TextSecure fails to send/receive an MMS to make more progress in diagnosing your issues. Can you also please create a new issue? This one is closed and very old, and doesn't make sense to reopen.

**Comment by nimdajitam** [comment]
Sure, I'm going to open new one right now.
