### ISSUE TITLE
List of contacts incomplete for compose or group creation

### ISSUE THREAD

**Issue by tdoerges** [signalapp/Signal-Android#3891]
# Description

When I hit the button for composing a new message or the add member button when creating a group, I get a list of contacts that's way too short.

The contact list ends with a number that begins with a GSM code (e.g. *31# to display the phone number on the receiving end). Maybe that's the culprit?

Debugging is a bit hard because I can't delete the alleged culprit (I guess that's #682).

I think #3099 and #1516 might be related, but they only talk about NBSP or parentheses and not about GSM codes.

Manually entering a phone number for a contact works.
# Expectation

Always get the complete list of contacts.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
