### ISSUE TITLE
Avatar for 'neither' content notification is an unxpected #-sign

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#3897]
For the new setting to show neither name nor message content the notification avatar has a #-sign.
I'd expected 
- the TS logo 
- or maybe some mysterious agents' hat (chrome private window) 
- or a carnivals mask (firefox)
- or alike

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
