### ISSUE TITLE
Can't easily close emoji drawer in quick reply

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#3898]
2.25.0 at https://github.com/WhisperSystems/TextSecure/commit/5fe1a289547fb4cf36b256ded6b1badbc330e0f5

Though it's pretty cool that keyboard and emoji are shown at the same time in quick reply, there should be a way to close the emoji drawer as it cover quite some space.
From the last message only the time stamp is visible. When scrolling merely one line of text is visible.

![_20150806_105402](https://cloud.githubusercontent.com/assets/5326916/9107695/adac7ba6-3c29-11e5-9b29-d8bdba90ce17.JPG)

**Comment by mcginty** [comment]
you can close it by closing the keyboard and hitting back, but I agree that's not very intuitive or simple.

**Comment by mcginty** [comment]
cutting out of milestone as it's not high priority

**Comment by McLoo** [comment]
:scream_cat:

**Comment by mcginty** [comment]
:see_no_evil:

**Comment by mammuth** [comment]
Note: As of 3.26 Signal uses Android's own direct reply instead of the custom quick reply (for devices >= Android 7)
https://github.com/WhisperSystems/Signal-Android/commit/373a0f952708996c584f92e4e000d270cb22af01

So this only affects users with Android 6 and below.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
