### ISSUE TITLE
Forgot my passphrase

### ISSUE THREAD

**Issue by Pffalk** [signalapp/Signal-Android#391]
I forgot my passphrase because I haven’t used this in a while & I’m not seeing any way to get in.

**Comment by klutt** [comment]
I'm struggling with the passphrase. AFIK I have never set the passphrase, so I have no clue what it is. I have just downloaded the apk package to the phone in genymotion so I have no idea what to do. I have tried uninstalling and reinstalling, but it still asks me for this passphrase.

**Comment by u32i64** [comment]
@klutt This is a very old issue which very likely isn't related to your problem. Also the [community forum](https://community.signalusers.org) should be used for questions.

> have tried uninstalling and reinstalling, but it still asks me for this passphrase.

I see two potential "passphrases" you might be facing during registration then; you should be able to tell in which situation you are by looking at what exactly the app is asking you about:

- [Backup passphrase](https://support.signal.org/hc/en-us/articles/360007059752). This was generated by Signal and shown to you when you enabled backups. If you don't intend to restore a backup, you can skip this step by pressing the *Skip* button under *Restore backup*.
- [Signal PIN](https://support.signal.org/hc/en-us/articles/360007059792). In some cases you can skip it too and create a new one, see the linked support article for details.

**Comment by klutt** [comment]
Oh sorry about that.

I know about pin. That's a thing I have set and remember. But I may have missed the backup thing. But nevertheless, I have gone into settings->apps and uninstalled it. And then I reinstalled Signal from the install file that I had downloaded and copied via shared folders in VirtualBox. But it keeps asking me for this and it's driving me nuts.
