### ISSUE TITLE
No way to unset recipient notification sound

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#3913]
can set to system default, but not TS default

unless I totally missed sth.

**Comment by RiseT** [comment]
Imho, the recipient default should use TextSecure's default rather than the system's default.

**Comment by samlanning** [comment]
On further inspection, it looks like choosing what seems to be the system default will actually set the TS default? It just previews the system default sound when you press it.

On a related note, if you select a non-default ringtone, and then default, if you go to change the ringtone again before closing the activity, then the previous non-default ringtone is selected in the popup (the default is correctly saved however).

**Comment by samlanning** [comment]
If we wanted to solve this completely and fully, we would probably have to make `AdvancedRingtonePreference` subclass `ListPreference` instead of `RingtonePreference`, which would involve a great deal more code.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
