### ISSUE TITLE
Messages sent with limited mobile data enabled won't send on app reopening

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#3919]
Yeah I know, the subject makes no sense. I blame the heat, okay?

Something I noticed today when I was out walking is that if I have TextSecure set to "Limited mobile data" so that TextSecure can't use the internet in the background, the messages sometimes won't send when I open the app again. Typically, this is how it happens:
1. I open the app and I write a message to someone. Any messages the person has written of course arrives meanwhile.
2. I "send" the message and I back out of the app, but the message isn't sent in time.
3. I open Puffin or whatever, and a minute later I open TextSecure again. The message is still "sending".
4. Here's where the problem shows. I sit there, waiting for the message to send. Half a minute passes, yet nothing.
5. I send another message, now both messages send without any problems whatsoever.

What should happen when I open the app is pretty obvious. The message should send, without me having to send another message.

Log while it's "sending" to no avail:
https://gist.github.com/anonymous/2901e20eb9799c2bb182

Now I realize this might be confused with https://github.com/WhisperSystems/TextSecure/issues/3068 but it's not the same issue. The message never actually fails for me when I do the above. It simply keeps "sending" yet nothing happens.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
