### ISSUE TITLE
MMS group message sends to myself 

### ISSUE THREAD

**Issue by europrobe** [signalapp/Signal-Android#3936]
When I receive an mms group message initiated by someone else,  and then reply to it, the reply gets sent to myself also. The conversation then includes both my outgoing mms, and then (after a few seconds) the same mms addressed to me.

I use TS 2.25.3.

**Comment by riyapenn** [comment]
Workaround may be to add yourself as a contact in your contacts list.  You can send an email to support@whispersystems.org to work through this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
