### ISSUE TITLE
Feature Request- Galaxy S6 Edge Compatibility

### ISSUE THREAD

**Issue by mjap** [signalapp/Signal-Android#3937]
Have the app recognize the top 5 contact colors for the GS6 Edge and have them light up accordingly as in the native messaging app.

**Comment by moxie0** [comment]
We don't have a GS6 Edge on hand, and don't know what this means.  You'll have to be more specific, screenshots would help.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
