### ISSUE TITLE
Not receiving notifications via bluetooth

### ISSUE THREAD

**Issue by cbrune** [signalapp/Signal-Android#3944]
Hi - not sure this is supposed to work or not.

My system:
Phone: Nexus 5
Android: 5.1.1
TextSecure: 2.22.2

Before I started using TextSecure, my phone would send a bluetooth notification to my car while I was driving.  From the car's UI I could see the message sender and play it (text to speech).

With TextSecure installed (and while unlocked) that no longer works.  I do not get text messages via bluetooth in the car anymore.  That was kind of handy...

**Comment by rustyrussell** [comment]
Me too; Pebble watch doesn't get TS notifications.  Really annoying; gets everything else...

**Comment by chr1shaefn3r** [comment]
@rustyrussell I'm using the original Pebble and receive all the TS notifications. Which Pebble are you using?

@cbrune First thing I would do is update TextSecure, current Version in the PlayStore is imho 2.28.2

**Comment by jeremymasters** [comment]
newest TS in the play store is 2.28.1

**Comment by rustyrussell** [comment]
Christoph Häfner <notifications@github.com> writes:
> @rustyrussell I'm using the original Pebble and receive all the TS notifications. Which Pebble are you using?

It's a Pebble Steel.

Perhaps there's a difference between secure and insecure messages?  I
hardly get any of the latter, so maybe they work?

Cheers,
Rusty.

**Comment by rustyrussell** [comment]
Confirmed.  Normal (insecure) SMS notifications occur.  Encrypted do not.

Passphrase off, screed security on.  Version 2.28.1.

**Comment by cbrune** [comment]
I'm running version 2.28.1 and still see the problem.

**Comment by mariuszs** [comment]
Standard messaging application for Android supports Bluetooth MAP.

https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=215400

Can we add support for this bluetooth profile?

**Comment by vladimiroff** [comment]
Bump. This two years old issue doesn't seem to be receiving a lot of attention.

**Comment by hakova** [comment]
Voting for this issue as a feature request. I use Signal as a default handler app for SMS messages. Neither SMS messages nor encrypted Signal messages are forwarded to my car's bluetooth when received. Quick fix will be appreciated.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
