### ISSUE TITLE
Incoming group MMS from previous thread arriving from "+abc", not downloading.

### ISSUE THREAD

**Issue by Quantum-cross** [signalapp/Signal-Android#3959]
This morning I received some important messages over group MMS (I still can't convert people to text secure). They arrived under a new thread from "+abc" and failed to download. Retrying download does not help.

I'm on T-Mobile using a Moto X 2nd gen running TextSecure 2.25.3.

Here is the [debug log](https://gist.github.com/anonymous/ef237eeb5f04dc171f4c) and a [screenshot](https://img.bi/#/qdm6viC!_vmdoAB4CrFASAPWBAQ5mmagGUedPwwzc_rQqO9r).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
