### ISSUE TITLE
Message Delivery Failed to non-textsecure user  - 2.25.3

### ISSUE THREAD

**Issue by johnwaldo** [signalapp/Signal-Android#3976]
My text secure messenger consistently fails to deliver messages to this particular number. No other numbers in my contacts list have had issues. Switching over to Google's "Messenger" allows the message to go through. For what its worth, the receiver's device is an iphone and oth sender and receiver are on CDMA (different networks).

Attached is a log captured immediately after sending the failed message.

https://gist.github.com/anonymous/15c723075e3d9dfbe8ff

Thanks in advance!
If you

**Comment by riyapenn** [comment]
Related to https://github.com/WhisperSystems/TextSecure/issues/3096?

**Comment by ryancdotorg** [comment]
I had the same issue, only started recently. It seems to depend on the message text in my case. I noticed  that at least one failed message had a trailing space - could that be an issue?

**Comment by johnwaldo** [comment]
This remains an ongoing issue for me. Same user on ios. I'm using Signal
3.1.1

**Comment by moxie0** [comment]
From the log it looks like we're delivering everything to Android alright, and Android is rejecting the message.  @johnwaldo does this happen for messages that are < 160 chars, or only for messages that get split?

**Comment by moxie0** [comment]
Oh, I bet your failing contact has "(" or ")" in the number stored in your address book? For some strange reason, some devices reject numbers formatted that way, so we started stripping them out.  That change is in the 3.3.x release, which we'll hopefully get out of the beta channel and into production soon.

**Comment by ryancdotorg** [comment]
@moxie0 This person wasn't in my address book, and was not being displayed with any characters other than digits and a leading +.

**Comment by ryancdotorg** [comment]
I don't have logcat set up, but if this happens again i can try to get a log.

**Comment by moxie0** [comment]
@ryancdotorg You might have a separate issue. You can get a log from Signal Settings -> Advanced -> Submit debug log.

**Comment by ryancdotorg** [comment]
@moxie0 I would prefer not to submit everything in the debug log publicly, but I looked at it and I do see this:

    W/MmsSmsDatabase( 4099): Type: sms
    W/MessageDetailsActivity( 4099): Recipient is not a group, resolving members immediately.
    W/SmsSendJob( 4099): Sending message: 6387
    W/SmsSendJob( 4099): org.thoughtcrime.securesms.transport.UndeliverableMessageException: Trying to send a secure SMS?
    W/SmsSendJob( 4099): at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:86)
    W/SmsSendJob( 4099): at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:55)
    W/SmsSendJob( 4099): at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
    W/SmsSendJob( 4099): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
    W/SmsSendJob( 4099): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/SmsSendJob( 4099): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

**Comment by mderazon** [comment]
same problem. occasionally I am getting red exclamation "Not delivered". When I tap for details and hit "Resend" I get the same results immediately.
Only happens with SMS. Also, sending through other apps is fine.

I can give you the number to try and send it to if you think it can help, tell me.

Here's the debug log
https://gist.github.com/anonymous/973ed665e7fdd8cbd17c

**Comment by ryancdotorg** [comment]
Just had this happen again recently.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
