### ISSUE TITLE
Title sometimes shows wrong user name

### ISSUE THREAD

**Issue by n0-1** [signalapp/Signal-Android#3993]
Hi,

When opening a new message, sometimes the title bar shows the wrong contact name. I haven't found out yet what this depends on, but it happens quite often.

This happens with version 2.25.3.

Cheers, Phil

**Comment by 2-4601** [comment]
What device are you using? Android version?
Debug log could also be helpful. After your issue happens immediately go to Settings -> Advanced -> Submit Debug Log and paste the link here

**Comment by n0-1** [comment]
This happens with a Sony Ericsson Xperia Mini Pro (SK17i) with Cyanogen Mod installed (CM10, basically Android 4.1.2).

It seems to happen every time I receive an SMS and reply to it. Interesting aspect I just noticed: the screen turned off due to timeout and I hit the home button to turn it on again - and suddenly the title bar showed the correct user. Is this some sort of caching issue? Please note that not only the name is wrong, but the color as well.

Log URL: https://gist.github.com/a4f8ba188e5638e8302a

**Comment by riyapenn** [comment]
Possibly related to #4066

**Comment by n0-1** [comment]
Yes, #4066 is pretty sure a duplicate of this one.

**Comment by riyapenn** [comment]
Also related to https://github.com/WhisperSystems/TextSecure/issues/2354

**Comment by kpuljek** [comment]
Also happens on LG G4, stock, with android 5.1
Screenshot: http://i.imgur.com/8fbw4pK.jpg

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
