### ISSUE TITLE
emoji selector doesn't work with physical keyboards

### ISSUE THREAD

**Issue by n0-1** [signalapp/Signal-Android#3994]
Hi,

When typing a message and I click on the grey smiley to the left of the text field, the emoticon selector opens from below. Once it's open, I can't close it anymore using the grey keyboard symbol to the left of the text field. The only way to close it is to type the 'back' button of the phone.

This happens with version 2.25.3.

Cheers, Phil

**Comment by 2-4601** [comment]
What device are you using? Android version? Which keyboard? Does this happen every time?
Debug log could also be helpful (Settings -> Advanced -> Submit Debug Log and paste the link here).

**Comment by n0-1** [comment]
This happens on a Sony Ericsson Xperia Mini Pro (SK17i). The question for the keyboard hit the bull's eye: It happens only if using the phone's physical keyboard. If I leave it slit in, the button works as expected, switching between emoticons and on-screen keyboard.

Debug Log: https://gist.github.com/9d17c4f87bb57677d768

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
