### ISSUE TITLE
Cancel download according to auto download settings 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4030]
When leaving the auto download zone (eg WiFi)
While downloading a (large) attachment,
The download should be stopped according the new download zone (eg mobile data)

Or at least notify about the zone change and let the user abort the download.

**Comment by mcginty** [comment]
Yeah, had thought about doing this in the initial release but thought it might also be weird for a download to show it's beginning and suddenly cancel itself. Will keep it open as a feature request.

**Comment by Dyras** [comment]
A sudden cancellation followed by a message declaring why it stopped would be the best option if you ask me. Anything is better than burning all of my internet on my phone.

**Comment by McLoo** [comment]
Guess we can't pause and resume downloads?

**Comment by mcginty** [comment]
Well, I think the "cancel" would make more sense as a pause, but right now we also have no sense of download resumption even if the network cuts out and becomes available again. It would just fail and you'd have to start over again.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
