### ISSUE TITLE
Cancel media download 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4031]
Add option to cancel running media downloads
Once we go large media this is really needed

**Comment by Mihahn** [comment]
I'd add an option to cancel running media transmission, too :wink:

**Comment by jodson** [comment]
I can create this issue. What i need to do to help in this project?

**Comment by mcginty** [comment]
@jodson i'd recommend starting off with something smaller to get used to the codebase. check out the "easy" tagged issues.

**Comment by jodson** [comment]
Ok. Is it just start coding and then commit? Or need some discussion about that "easy" tagged issues?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
