### ISSUE TITLE
notification should always show content of the message,not "most recent from xxx"

### ISSUE THREAD

**Issue by jpph** [signalapp/Signal-Android#4038]
Hi, I am using textsecure with pebble and it is working fine except when receiving message from different persons. On the second messahe, the notification is "Most recent from xxx" without the content of the message. I have then to reach my phone, unlock and go into textsecure to read it... I would like to be able to read directly the message on the watch (that is the purpose of the smartwatch).
Would it be possible to have an option to force the notification of the content of the message on every message ? thank you

**Comment by riyapenn** [comment]
Different 3rd party software, but similar issue in https://github.com/WhisperSystems/TextSecure/issues/2525

**Comment by chr1shaefn3r** [comment]
A quick workaround you could do to prevent these "Most recent from xxx" notifications is to always mark incoming TS messages as read.

**Comment by jpph** [comment]
Hi, as I was annoyed by this bug for the last 4 month, I replace with SMSsecure for sms parts.
In SMSsecure, I do not have this issue, every message arrive on its own. 
If it can help.... (I know that SMSsecure is forked from Textsecure).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
