### ISSUE TITLE
LG G2 receives texts on 1-1 texting, but not in group texts

### ISSUE THREAD

**Issue by rbernas** [signalapp/Signal-Android#4045]
Hello,
I am sending texts from a LG G2 phone and the text receiver also uses a LG G2 phone on the Sprint network. Between the two LG G2 phones, texts are successfully received for 1-1 text, but not for group texts of 2 or more people. Note that the single user of TextSecure is the sender of the SMS. None of the other users are using TextSecure. 

The TextSecure user encounters no issues with receiving text messages from other users on 1-1 or group texts.

Other phone manufacturers on the same group texts (Samsung, Apple phones), however, do receive the texts for both 1-1 and group texts from the sender using TextSecure. Again, none of these SMS receivers are using TextSecure.

No problems encountered for 1-1 or group texts when using the default messaging app on phone.

Have you encountered similar issues between LG G2 phones on the Sprint network?

Best,
Rick

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
