### ISSUE TITLE
Message recipients retroactively change after sending

### ISSUE THREAD

**Issue by cosmc** [signalapp/Signal-Android#4048]
I've only encountered this issue once and have not been able to reproduce it, but it looked really dangerous.  The order of events was, as best I can remember, like this:
- I sent a message in an ongoing conversation with Person A.
- I started a new conversation and sent one message to Person B.
- Person A replied, and when I switched back to the first conversation, the message that I'd sent to Person B appeared to have moved to the conversation with Person A.
- When I went back to the screen with the list of recent conversations, the _entire_ conversation with Person B suddenly had Person A's name on it instead.  A moment later, before my eyes, it changed back to Person B's name.  One message that I'd sent to Person A (and which I confirmed that he received) is still shown in my conversation with Person B.

That was a little convoluted, but the end result is that both Person A and Person B have potentially received messages that were intended for the other, and there's no way for me to know who got which messages without checking with both of them.

**Comment by riyapenn** [comment]
Possibly related to #4066, #3993, https://github.com/WhisperSystems/TextSecure/issues/2354

**Comment by acbilimoria** [comment]
I've seen this as well but it went away after updating last week.

**Comment by cosmc** [comment]
I saw this issue again, while my phone was in Battery Saver mode.  Here's one hypothesis, which is total guesswork: there may be a race condition between the view switching to show a new conversation, and fetching the data to populate the view (interlocutor's name, conversation contents, etc.).  So when you switch to a new convo, you sometimes see the old value of $name_of_person_you're_talking_to before the new value can be displayed.  It may be that fetching the data is usually faster than switching the view, so the behavior isn't normally visible, but with reduced power the relative speeds of those two operations might change.  This is, again, strictly conjecture. And @riyapenn, it does look similar to those issues.

**Comment by acbilimoria** [comment]
Just saw it again today:  I received a message from person x and opened it to see messages from person x in the body and the name and number of person y in the header.  I clicked back and at the top of the index it showed the message from x but that it was from person z.

**Comment by jeremymasters** [comment]
@acbilimoria if you see it happen again, it would be helpful to immediately grab a debug log and post here for the devs

**Comment by acbilimoria** [comment]
Oh yeah I meant to include that on the last message:
https://gist.github.com/0ea88d18dbe129aa977f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
