### ISSUE TITLE
Notification repeat starts over 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4054]
once the repeat count is reached there  is silence 
until ~~you reopen TS~~ (no need to change apps) 
 and  enter  any conversation  (but the notified of course) 
Then the notification is repeated 'repeat count' times. Again. 

Log has a NPE along with a "YOu must call this method on a background thread" 

2.62.2
https://gist.github.com/62dfaa7367c375dd34a8

Edit: Plain text SMS is notified in this case

**Comment by moxie0** [comment]
You sure you don't have any staged/local changes?  Those stack traces don't line up.

**Comment by McLoo** [comment]
clean play release - haven't had a custom build on that registration/phone for ages

maybe of use: it's a **self send** SMS. In that convo still 3 attachments have the download arrow and another one the eternal loading circle (due to some older issues)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
