### ISSUE TITLE
contact name doesn't update after adding contact 

### ISSUE THREAD

**Issue by heyimgay** [signalapp/Signal-Android#4074]
it requires that you manually exit the conversion and reenter

**Comment by heyimgay** [comment]
probably related to #3711 but it's not system, I have that disabled

**Comment by XertroV** [comment]
I can confirm this is occuring on my G4. I have SMS on. It is triggered regularly.

When I receive a message and open via the notification the conversation has a name mismatch. The heading contains the name of the previous recipient, but the user-icon in the chat accompanying each message reflects the current recipient.

**Comment by heyimgay** [comment]
Thought it was fixed but still happened on 3.7.2

**Comment by agrajaghh** [comment]
Its fixed for me when using "Add to contacts" from the menu, but its not fixed if you add the contact via the avatar (only way in group conversations)

before and after adding to contacts:
![dbc77d64-a9ad-11e5-9380-43574d7a208c](https://cloud.githubusercontent.com/assets/5296073/11984164/4ab9d2fc-a9b9-11e5-9b5d-7b19c066c0be.png)

**Comment by McLoo** [comment]
@agrajaghh "(only way in group conversations)" besides the member list? But I guess it behaves equally...

**Comment by agrajaghh** [comment]
@McLoo wow didn't know you can tap the contacts in the memberlist :grin: This "thing" needs a redesign I guess. Maybe I'll try it during the holidays...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
