### ISSUE TITLE
Pictures taken by Camera not always displayed for sending

### ISSUE THREAD

**Issue by He-Ro** [signalapp/Signal-Android#4076]
On a friends phone the attachment of photos taken by the camera does not work all the time, while the quick capture seems to work just fine.

What I did:
- Open the conversation
- Click "Add attachment"
- Click "Camera"
- Take a photo (I experienced that it worked, if I took the photo as fast as possible, so I took the photo directly after the camera started up)
- Notice that the photo gets displayed in the conversation
- Dismiss the photo
- Click "Add attachment" again
- Click "Camera"
- Wait a little longer
- Take the Photo
- Notice that there is no photo available in the conversation.

![anim](https://cloud.githubusercontent.com/assets/3579374/9901746/da3aa8f4-5c69-11e5-8e2c-294e4ebe9943.gif)

Here is the log taken in TextSecure:
https://gist.github.com/anonymous/845ad0bd39050f88a5ef

Here is a log taken with adb:
[cat.log.bz2](http://sprunge.us/fSSA)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
