### ISSUE TITLE
Can't Receive MMS

### ISSUE THREAD

**Issue by capdot** [signalapp/Signal-Android#4080]
I was sent an MMS and prompted with a dialog to tap and configure MMS settings to continue download. I've since set the MMS settings and am able to receive MMS now but if I try to get the original MMS it seems Text Secure is still looking up the broken default MMS settings( I don't know where these original settings came from) Is there anyway I can get it to apply the new settings to the old MMS. Getting the person to resend the original MMS is not possible, unfortunately.

**Comment by mcginty** [comment]
please try to download it, have it fail, then post a debug log

**Comment by capdot** [comment]
Here is the debug log https://gist.github.com/anonymous/acf803e3e8372fcda7af

**Comment by capdot** [comment]
Just to give you an idea what's happening in the debug.

I tap configure to download and it appears like TS tries the old broken MMS defaults below

 W/ApnDatabase(  855): Returning preferred APN LegacyMmsConnection$Apn{ mmsc: "http://mms.virginvibe.com.au:8002", proxy: "202.139.83.152", port: 8070, user: none, pass: none }

When this fails I get the you need to configure this screen. I click ok and go the the MMS settings screen where the correct settings are already entered but there is no way to make TS apply them to the current MMS download. From here all i can do is go back and I end up at the same tap to download/configure screen.

**Comment by Happy8-8** [comment]
Same issues as the OP.
Using T-mobile US

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
