### ISSUE TITLE
Duplicate contacts in list on Android < 5.0

### ISSUE THREAD

**Issue by lifebarier** [signalapp/Signal-Android#4087]
When same contacts are saved on SIM and PHONE TextSecure shows them both. Default dialer lets user choose which contacts to show but that doesn't transfer to TS and there seems to not be any option in TS to choose.
Android 5

**Comment by mbausdorf** [comment]
I am experiencing the same issue. Would appreciate a fix!

**Comment by oaim** [comment]
Don't know if your issue was fixed when #4072 got merged, but it's still present on my phone. Android 4.1.2, TS 2.28

**Comment by mcginty** [comment]
@oaim that fix only works on Android 5.0 and up.

**Comment by oaim** [comment]
Yes I know, I just said it to avoid this being closed ;)

**Comment by mcginty** [comment]
updated to the title to make it less likely to get accidentally closed :)

**Comment by bartz1** [comment]
Update: in 3.5 this is the situation:
- no duplicate contacts in the "Signal users" section
- in the "All users" section, only the not-Signal users are displayed twice. This was not the case until I think 3.4.2, as all users used to be displayed twice (in this section)

**Comment by sweeper3000** [comment]
I believe I'm having this issue. They show in the new conversation section of Signal. I think this has to do with linked contacts. For all my Signal contacts, Signal writes 2 linked contacts to the same contact when it should be one. I'm on Android 7.0

#### Debug
﻿**Android:** https://gist.github.com/anonymous/2f848d74431c0d07ac05f72637eb279e

The same thing happened in the Desktop version, but press of the `Import Now` button & a relaunch cleared it up. If a desktop log is of any use, here it is, captured before I ran through the above steps.
**Desktop:** https://gist.github.com/anonymous/c36977b65319b041c92ed7d51804ba0c

#### Picture of New Conversation View
![debug-final](https://cloud.githubusercontent.com/assets/13157680/18853517/9064bb48-8413-11e6-9b48-f224b249d913.jpeg)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
