### ISSUE TITLE
[KitKat] Attempt to retreive MMS causes TextSecure to crash

### ISSUE THREAD

**Issue by bassworq** [signalapp/Signal-Android#410]
If you open a thread containing an MMS that is yet to be retrieved from the carrier (T-Mobile USA, in my case), TextSecure crashes. Stack trace using Nexus 5 on KitKat:

```
E/DatabaseUtils(  989): Writing exception to parcel
E/DatabaseUtils(  989): java.lang.SecurityException: No permission to write APN settings: Neither user 10102 nor current process has android.permission.WRITE_APN_SETTINGS.
E/DatabaseUtils(  989):     at android.app.ContextImpl.enforce(ContextImpl.java:1685)
E/DatabaseUtils(  989):     at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1714)
E/DatabaseUtils(  989):     at com.android.providers.telephony.TelephonyProvider.checkPermission(TelephonyProvider.java:735)
E/DatabaseUtils(  989):     at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:462)
E/DatabaseUtils(  989):     at android.content.ContentProvider.query(ContentProvider.java:855)
E/DatabaseUtils(  989):     at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
E/DatabaseUtils(  989):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
E/DatabaseUtils(  989):     at android.os.Binder.execTransact(Binder.java:404)
E/DatabaseUtils(  989):     at dalvik.system.NativeStart.run(Native Method)
W/MmsCommunication(13159): java.lang.SecurityException: No permission to write APN settings: Neither user 10102 nor current process has android.permission.WRITE_APN_SETTINGS.
W/MmsCommunication(13159):  at android.os.Parcel.readException(Parcel.java:1461)
W/MmsCommunication(13159):  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
W/MmsCommunication(13159):  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
W/MmsCommunication(13159):  at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
W/MmsCommunication(13159):  at android.content.ContentResolver.query(ContentResolver.java:461)
W/MmsCommunication(13159):  at android.content.ContentResolver.query(ContentResolver.java:404)
W/MmsCommunication(13159):  at org.thoughtcrime.securesms.database.MmsDatabase.getCarrierMmsInformation(MmsDatabase.java:598)
W/MmsCommunication(13159):  at org.thoughtcrime.securesms.mms.MmsCommunication.getMmsConnectionParameters(MmsCommunication.java:95)
W/MmsCommunication(13159):  at org.thoughtcrime.securesms.mms.MmsSendHelper.hasNecessaryApnDetails(MmsSendHelper.java:119)
W/MmsCommunication(13159):  at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:591)
W/MmsCommunication(13159):  at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:588)
W/MmsCommunication(13159):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/MmsCommunication(13159):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/MmsCommunication(13159):  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/MmsCommunication(13159):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/MmsCommunication(13159):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/MmsCommunication(13159):  at java.lang.Thread.run(Thread.java:841)
```

I sometimes see the same exception and stack trace on logcat on my Nexus 4 (stock Android 4.3), but it doesn't cause TextSecure to crash.

I checked the manifest and the WRITE_APN_SETTINGS permission isn't there. Perhaps it just needs to be added?

**Comment by seiyaa** [comment]
@wsot i have the same problem in system_server on Android system
where can i find the test app to debug my problem?
pid: 1782, tid: 2529, name: Binder_C  >>> system_server <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'heap corruption detected by dlmalloc'
    r0 00000000  r1 000009e1  r2 00000006  r3 00000000
    r4 00000006  r5 00000002  r6 000009e1  r7 0000010c
    r8 7628fb60  r9 401ed338  sl 7893ad48  fp 7a213984
    ip 00000006  sp 7a213868  lr 4008926d  pc 40098384  cpsr 00010010
    d0  636f6c6c616d6c64  d1  206e6f6974707572
    d2  0000000000000000  d3  0000000000000000
    d4  70615f6465726168  d5  703d657079742070
    d6  5f6d726f6674616c  d7  400000003f800000
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 4000000000000000  d17 00000006ffffffff
    d18 0000000000000000  d19 0000000000000000
    d20 0000000000000000  d21 0002000200020002
    d22 0010001000100010  d23 0000000000000000
    d24 0003000000030000  d25 0003000000030000
    d26 0707070703030303  d27 000000300000002f
    d28 0001000000010000  d29 0001000000010000
    d30 00b6800000b38000  d31 00bc800000b98000
    scr 80000010

backtrace:
    #00  pc 00022384  /system/lib/libc.so (tgkill+12)
    #01  pc 00013269  /system/lib/libc.so (pthread_kill+48)
    #02  pc 0001347d  /system/lib/libc.so (raise+10)
    #03  pc 000121b3  /system/lib/libc.so
    #04  pc 00021c38  /system/lib/libc.so (abort+4)
    #05  pc 00012c99  /system/lib/libc.so
    #06  pc 0000f3a5  /system/lib/libc.so
    #07  pc 000102b1  /system/lib/libc.so (dlmalloc+604)
    #08  pc 0000de7f  /system/lib/libc.so (malloc+10)
    #09  pc 0000091b  /system/lib/libstdc++.so (operator new(unsigned int)+2)
    #10  pc 0007260b  /system/lib/libandroid_runtime.so (android::ibinderForJavaObject(_JNIEnv*, _jobject*)+98)
    #11  pc 0006bdc7  /system/lib/libandroid_runtime.so
    #12  pc 0001dd4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
    #13  pc 0004e3a7  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
    #14  pc 00027160  /system/lib/libdvm.so
    #15  pc 0002e120  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
    #16  pc 0002b7b8  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
    #17  pc 00060801  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
    #18  pc 0004d10d  /system/lib/libdvm.so
    #19  pc 0006da6f  /system/lib/libandroid_runtime.so
    #20  pc 000727ab  /system/lib/libandroid_runtime.so
    #21  pc 00019225  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+60)
    #22  pc 0001d799  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+508)
    #23  pc 0001db17  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+38)
    #24  pc 0001db8d  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
    #25  pc 000219f5  /system/lib/libbinder.so
    #26  pc 0000ea5d  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+216)
    #27  pc 0004debd  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+68)
    #28  pc 0000e58f  /system/lib/libutils.so
    #29  pc 0000d3f8  /system/lib/libc.so (__thread_entry+72)
    #30  pc 0000d590  /system/lib/libc.so (pthread_create+240)
