### ISSUE TITLE
Sending large videos has an awkward pause

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#4112]
1. Attach a large video file (tens of MBs)
2. Notice that the thumbnail icon appears almost instantly after selecting the video
3. Tap send
4. Notice that the thumbnail icon vanishes
5. For several seconds there's no indication of what's happening (it looks like the video disappeared)
6. After the awkward pause the message appears again with the upload progress animation

With a 58 MB video file the awkward pause was 12 seconds for my Nexus 4. For my low-end device (Huawei U8800) it was more than 4 **minutes**.

TS 2.27.0, 2.27.1
Nexus 4, stock 5.1.1
Huawei U8800, 4.0.4

**Comment by mcginty** [comment]
Yeahhhhhh. We copy the entire contents of the media over to an encrypted file in TextSecure's app data before showing anything. We should not do that.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
