### ISSUE TITLE
Lock screen with PIN entry not using FLAG_SECURE

### ISSUE THREAD

**Issue by yakovsh** [signalapp/Signal-Android#4132]
And therefore it is vulnerable to screen capture on Android 5.0 with MediaProjection API. Sample video shot with Telecine is attached.
![video](https://cloud.githubusercontent.com/assets/667009/10120952/9c8d5410-64a3-11e5-8029-dc2e81016d72.gif)

**Comment by jodson** [comment]
I think that commit solve this problem 

https://github.com/jodson/TextSecure/commit/c0c39c05828a3dd18840af8ae345dd505474cd06

**Comment by yakovsh** [comment]
There is also a second related issue involving the virtual keyboard as well:

https://code.google.com/p/android/issues/detail?id=129285

**Comment by jodson** [comment]
Oh, i don't knew about this. Thank you for show this. So, to create a mechanism to solve that second problem, it's just not show the native keyboard. The password to unlock the screen can be a finger swipe.

What do you think?

**Comment by yakovsh** [comment]
That could be one approach. Another approach I have seen that Google Wallet uses, is that they have a custom PIN entry screen that does not use the keyboard, and that PIN entry screen can be hidden with FLAG_SECURE.

**Comment by jodson** [comment]
I thought in that approach. I am waiting my pull request be accepted. If that happen, I will try implement that custom PIN.

**Comment by yakovsh** [comment]
Thanks!
