### ISSUE TITLE
Recipient notification settings ignored for calls

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4164]
Yes, they were for messages, but now at least 'ringtone' looks like it's for calls.
- Not muting
- Always default ringtone (which now really could be the one from Signal IOS).
- No vibration

**Comment by moxie0** [comment]
I changed it to 'Notification ringtone' for now, eventually we'll add separate sections

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
