### ISSUE TITLE
hanging up on a call before the recipient answered doesn't stop the ringing on their side

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#4172]
A calls B
A immediately hangs up on B
B still sees ringing

**Comment by real-or-random** [comment]
In the position of A, I can still hear the ringing in the background after hanging up (while seeing the normal conversation again).

No idea if B can still answer. If yes, then this would be a different bug actually, because in the above description, B cannot answer.

**Comment by scienmind** [comment]
"B" can answer the call, and then it'll display "connecting" status (for B) for quite a long time, or until B presses the red "hang up" button.

**Comment by Esokrates** [comment]
I have still experienced that issue lately. When pressing the button by accident and aborting instantly it rings forever on the other side!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
