### ISSUE TITLE
No update in conversation thread when starting new conversation(no history exists) with secure contact

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#4175]
No message history w/ A 
1. Tap compose message icon from conversation list
2. Select secure contact A
3. Initiate secure call
4. Cancel secure call 
5. BUG: No update in conversation thread
6. Go back to conversation thread
7. View message thread with A
8. Conversation thread indicates 'Called A'

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
