### ISSUE TITLE
calling in airplane mode sometimes hangs on call screen missing end button

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#4186]
Sometimes calling in airplane mode will cause a "server failed" error to be shown and the call will end, but other times it just hangs in a blank-ish screen.

**Comment by kaladivo** [comment]
Is it possible to reproduce it somehow? I am unable to do it...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
