### ISSUE TITLE
(Some) strings for SMS/MMS encryption still present

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#4195]
It seems like various strings for encrypted SMS/MMS are still present in the code.

Keys:
- SmsMessageRecord_[...]
- MmsMessageRecord_[...]

**Comment by unrulygnu** [comment]
While I cursed their seemingly useless presence when translating a while back, I realized that downstream projects may enjoy the benefit.  That turned my frown upside down. :smiley:

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
