### ISSUE TITLE
"Missed call" log displays wrong time if offline

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#4197]
1. Turn on air plane mode
2. Ask someone to call you with Signal
3. Wait for five minutes
4. Turn off air plane mode
5. The call log message says: _"Missed call from someone: **Now**"_

_**Now**_ should be _**5 min**_

Note that messages that were sent to you while you were in air plane mode show correct time.

Signal 3.0.1
Nexus 4, stock 5.1.1
Huaweui U8800, 4.0.4

**Comment by cascheberg** [comment]
I'd like to offer support in fixing this, but it seems to require server-side changes. Is that server code even publicly available (on GitHub)?

**Comment by mantono** [comment]
@cascheberg I think this is the repo you're looking for: [WhisperSystems/TextSecure-Server](https://github.com/WhisperSystems/TextSecure-Server).

**Comment by cascheberg** [comment]
TextSecure uses a `TextSecureProtos` protobuf class from [WhisperSystems/libtextsecure-java](https://github.com/WhisperSystems/libtextsecure-java).
RedPhone uses a `CompressedInitiateSignalProtocol` protobuf class, but I could not find the `.proto` files.

**Comment by findkiko** [comment]
I had a look at this bug.
I think I've chased down where the date is getting set but I'm not 100% sure if missed call entities even have a "DateSent" attribute. I'd appreciate if somebody could take a look at https://github.com/findkiko/Signal-Android/commit/6397fbd198e40a470fceaea69c4d493cccab98fb 
Am I on the right path? I'm not sure even where to begin compiling a new app and putting it on a phone to test this, or whether it's necessary for a patch like this.
Thanks

**Comment by cascheberg** [comment]
@findkiko It's not that simple.

You can follow the code from `RedPhoneService.notifyCallStale()` and also `GcmBroadcastReceiver.handleReceivedCall(...)`.

I think the relevant code is not available, so currently @moxie0 would have to fix it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
