### ISSUE TITLE
problem with pull-to-refresh

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-Android#4204]
There are some "problems" with updating the database using pull-to-refresh...
1. Open your Signal contact list
2. pull to refresh
3. after a few seconds (try it < 5s and > 5s) press the back button 
4. open Signal contact list immediately
5. do steps 1-4 until you're tired :see_no_evil: 

You'll notice that sometimes 
1. every contact appears twice
2. only some appear twice
3. everything's fine again 
Everytime I try it, I get result 1,2 and 3 randomly....

Nexus 4, Android 5.1.1, Signal 3.0.1
https://gist.github.com/anonymous/683e5942592876263c87

**Comment by johanw666** [comment]
No problems here. However, one other thing: the pull down only works on JB or higher. I removed that restriction, and it works OK on my ICS device as well. So perhaps it is an idea to change the code for that?

**Comment by eternaltyro** [comment]
I have this same issue on Motorola Moto E 2nd generation. However, results are consistent. I always have some contacts listed twice and others not. Btw, do you have a dual SIM phone? Are contacts saved in the SIM and the Phone at the same time?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
