### ISSUE TITLE
Linkify geo-schemed uris

### ISSUE THREAD

**Issue by Hooloovoo** [signalapp/Signal-Android#4206]
I'm using Signal 3.0.1 beta on Android on a Nexus 5. Debug log (though I doubt you'll want it) is https://gist.github.com/526f0bbf1de80801e008

It would be great if geo: uris in messages that I receive turned into hyperlinks that, when clicked, gave the choice of opening the geo: link in whatever applications the user has installed that deal with them.

geo: uris are a way of encoding location information in a universal way, instead of doing so in a mapping-application specific way. See:
http://geouri.org/
https://en.wikipedia.org/wiki/Geo_URI_scheme
https://developer.android.com/guide/components/intents-common.html#Maps

The geo intent appears to be supported on Android (if I click on a geo link in Chrome, it asks me which of my various mapping applications I would like to open it with), but geo: uris within messages in Signal do not turn into hyperlinks and cannot be clicked to load up the location on a map. I commonly see this with OSMAnd links, which generate a geo: uri by default when one uses it to send a location. I believe that GeoSMS also sends geo: links to other people via SMS.

To a degree this is a privacy issue. A key reason I use OSMAnd is because it does offline mapping and geo: uris allow you to send and resolve locations without sending them to a remote webserver (like Google Maps). 

I'm not an Android developer, but it looks to me like the 7-odd lines of example code in the developer.android.com link above should go a long way to making these geo: uris work.

**Comment by mcginty** [comment]
It's 7-odd lines to launch an open intent for geo-schemed URIs, but the main issue is that Android's Linkify class doesn't understand geo URIs. We'd need to write our own Linkifier for them, which is a less small change.

**Comment by rmueller83** [comment]
I nearly got it to work. I got a RegEx from https://codecov.io/github/zxing/zxing/core/src/main/java/com/google/zxing/client/result/GeoResultParser.java which I use for Linkify. I also followed the advice to disable the autolink mask here: http://www.indelible.org/ink/android-linkify/
The linking basically works, but there is one problem: you have to call the Linkify methods after each TextView.setText(...) call. In ConversationItem the linkification is dependent on (batchSelected.isEmpty()) as we do not want to have clickable links on batch selection. No problem to linkify here.
But there is another TextView.setText(...) call from EmojiTextView.onLayout(...) where I do not have the batchSelected information to make the linkification dependent on batch selection. I uploaded a patch file of my progress, anyone can feel free to use it: https://gist.github.com/rmueller83/a3ce5254ae557bed2015
Perhaps @mcginty has some advice where to put the Linkify code and how to access the batchSelected state...

**Comment by twzkxkan** [comment]
Can the [ChatSecure](https://github.com/eighthave/ChatSecureAndroid/blob/eb76c4672191fa99900ea2ac39735653dc153c94/src/info/guardianproject/otr/app/im/app/ChatView.java#L1880) [implementation](https://github.com/eighthave/ChatSecureAndroid/blob/eb76c4672191fa99900ea2ac39735653dc153c94/src/info/guardianproject/util/LinkifyHelper.java#L12) be of help?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
