### ISSUE TITLE
Entire Message History Disappeared

### ISSUE THREAD

**Issue by sbgold** [signalapp/Signal-Android#423]
I picked up my phone and noticed that my entire message history has disappeared! I've rebooted the phone twice with no effect. I have a Samsung Stratosphere running Android 2.3.6, TextSecure 1.0.2 and the 'Delete Old Messages' setting is NOT active.

I recently changed my MMS preferences to enable Manual MMS. My carrier is Verizon. Is it possible the carrier has message storage limits I'm unaware of? 

I have no backups to export. 

Please advise.

**Comment by jfrederickson** [comment]
I just experienced this on my own device, though stupidly I didn't capture a debug log. :( I rebooted my device thinking it was just a display issue (since the empty thread list looks like just a blank pane.)

If I experience this again I'll send logs.

**Comment by pilgrimish** [comment]
@mcginty just happened to me. HTC M9 was low on battery, but not out. Phone shut off without warning.  Once I got it charged a bit and back on, all Signal messages were gone along with all phone contacts. Have not been able to retrieve either. Where do I take a debug log? Is it too late? Probably happened around 4pm EST today.

**Comment by mcginty** [comment]
@pilgrimish https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#how-to-capture-debug-log

It's probably gone, but you can still give it a shot and see if your device logs are luckstruck.

**Comment by gimbi** [comment]
@mcginty @pilgrimish @moxie0 

Same thing just happened to me. HTC M8 shut off due to low battery but the last thing I heard was a text message notification. Maybe the shutdown while writing corrupted the database. Everything is gone, including archived messages.

Wondering if it's possible to extract the database and try to manually hack at it? The log doesn't go back far enough to be useful. 

Might be a good idea to store archived messages in a different database, mitigating such loss.

**Comment by sigenc** [comment]
This is why we need the possibility to do an encrypted backup.

**Comment by kso512** [comment]
This issue is still occurring, on my friend's system.  Debug log: https://debuglogs.org/5eac62107a1794c018fc91635cb0c7c514358359b6a0db8e5da9716ff7f72a33

**Comment by attd** [comment]
Didn't save log but this happened for the first time today for me on OnePlus6.  Deleted 2 of the most recent conversations and it somehow deleted every single one.  Battery wasn't low or anything and nothing else happened that I could tell.

**Comment by alternativesurfer** [comment]
Yep, just happened to me. 

Pixel 1, Android 10
I had closed the app about 20 minutes ago, reopened it and everything was gone. 

App info showed the storage utilization for the full DB but no amount of rebooting made it come back. Had to restore from this mornings backup.

**Comment by gtmadev** [comment]
Just happened to my device. One moment, was in there replying to someone. Next thing I know, the entire app is blank with no conversations. I do have a backup, so I will restore. But wow.. really strange for it to be doing that.
