### ISSUE TITLE
Auto-split oversized texts

### ISSUE THREAD

**Issue by Norbert80** [signalapp/Signal-Android#4230]
Feature Request:
Auto-split oversized texts over multiple messages. At the moment they will be truncated.

(Telegram messenger auto-splits oversized texts into multiple messages.)

**Comment by jeremymasters** [comment]
To be clear, are you talking about SMS/MMS or TextSecure messages?

**Comment by Norbert80** [comment]
TextSecure

**Comment by RyanRiddle** [comment]
Do you mean messages your receive or send?

**Comment by Norbert80** [comment]
Send. Splitting received messages would not make sense.

**Comment by TWfromSWD** [comment]
Out of interest: At what length do the messages get truncated?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
