### ISSUE TITLE
Last message from blocked contacts should be blocked

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4237]
So after being bombarded by a total idiot, I decided to block the creep. Said and done, no more messages. However, I still see the last message written by her on the "front page" of Signal.

The purpose of blocking someone is to make sure that you can't see their messages, so why not block the last message as well? I think Telegram does this, and I love it. Removing the chat completely isn't an option for me.

**Comment by effigies** [comment]
Why not just remove the last message manually?

**Comment by Dyras** [comment]
Yes, I asked myself that too while writing it. But I'm a saver. I want to save everything "just in case".

**Comment by effigies** [comment]
So you want the message removed for you, but don't want to remove the message? Or you want the thread pushed down so that it's not among the first things you see?

**Comment by McLoo** [comment]
Ublock 
Draft or send sth
Block 
Done

**Comment by Dyras** [comment]
That's exactly what I want effigies. I want "BLOCKED" to be shown as an actual message under the person's name, thus not showing me the last message.

McLoo Yeah I'm fully aware of that. The reason I'm requesting this isn't because I'm brain dead or lazy, it's just that I think it would be a neat feature.

**Comment by McLoo** [comment]
Ahh now I got it. Sry. 
Totally makes sense to me. Should be tagged EASY.

**Comment by mcginty** [comment]
This might be solved when archiving functionality is added? If we want to specifically change the update to be "Blocked" it'd only really make sense to me if we added a "You blocked Total Idiot" meta-message into the conversation to be consistent.

**Comment by samlanning** [comment]
How about rather than displaying a message like "Blocked" or "You blocked Total Idiot", what if we just display no text when blocked?

**Comment by Dyras** [comment]
@samlanning As long as I know the user is blocked and I don't have to read their last message I really don't mind. But yeah, sounds good!

**Comment by dmevdy123** [comment]
If I block someone on signal will the messages still appear on the other persons app/phone?

**Comment by Dyras** [comment]
@dmevdy123 What messages? Something you've sent? Absolutely, because their device has already received the message.

**Comment by dmevdy123** [comment]
@Dyras thank you

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
