### ISSUE TITLE
Backing up SMS in TextSecure

### ISSUE THREAD

**Issue by docanonymous** [signalapp/Signal-Android#424]
Hello,
I have a problem with TextSecure. I want to export my messages to the SD Card in order to have a backup of my data. I want to export the messages in plaintext, but unfortunately I have no idea where to find it on the SD-Card or how to open it. I could’t find any plaintext data in /storage/sdcard0/TextSecure Export. I hope you can help me with this problem.
Greetings,

**Comment by hpk42** [comment]
For what it's worth, i just exported the data on my nexus 5 (Which doesn't have an SDcard) and although the export claims to be successful, i can't find "TextSecurePlaintextBackup.xml" anywhere.  Is this supposed to work?
