### ISSUE TITLE
small UX suggestions regarding TextSecure account in Android sys settings

### ISSUE THREAD

**Issue by spaghettifreek** [signalapp/Signal-Android#4258]
Friends have asked me where TextSecure syncs its contacts to, "in which cloud they end up", and I had to assure them that TextSecure stores its contacts only locally on the device, populating them automatically by sourcing other Android contacts providers (like local address book or Google account or Exchange account or CardDAV or ...).

The confusion might be avoided by adding a privacy section with a short explanation next to the TextSecure system account like this:
![screenshot](https://cloud.githubusercontent.com/assets/15157050/10541311/32f59630-7410-11e5-8576-2039601e0b10.png)
The only drawback: It might give the impression that you can have multiple TextSecure accounts per Android user or device.

Related: Tapping "Add account" in the Android system settings and selecting TextSecure, I get stuck. OpenKeychain handles this situation quite nicely and tells me "You can not create OpenKeychain accounts manually" in a pop up and drops me back to the sys accounts screen.

PS: Loving everything you do and how you do it. Keep going!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
