### ISSUE TITLE
Reinstalled phone, now one user can't message me

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4275]
Hi. I reinstalled my Galaxy Nexus today, but before doing that I deactivated data messages for Signal. Now whenever my mom tries to send me a message it automatically fails. At first it seemed the problem was caused because she had to "verify" my new identity, but after doing so... Same problem.
https://gist.github.com/anonymous/b018a5608a3ba2debce2

I've tried updating the contact lists on both phones about ten times, and my Galaxy Nexus just won't detect my mom's phone number as a Signal number.

**Comment by moxie0** [comment]
Hey @Dyras the best place for support questions is support@whispersystems.org or the support center.  Thanks.

**Comment by Dyras** [comment]
@moxie0 I didn't intend for this to be a support question, I intended it to be an issue report. I think it's pretty obvious that what happened for me isn't supposed to happen. I got it working, but I figured there could be a way of preventing this from happening, since 9/10 people will just sigh and uninstall TextSecure if this happens for them.

But yeah, if you say so...

**Comment by mcginty** [comment]
@dyras any chance you have been using the browser extension

**Comment by Dyras** [comment]
@mcginty I don't even know how to install it, so no. Never used it ever.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
