### ISSUE TITLE
Messaging one specific signal user "poisons" all subsequent messages, requiring reinstall

### ISSUE THREAD

**Issue by patcon** [signalapp/Signal-Android#4277]
Specifically, this is just one contact that has been using textsecure for perhaps a year, using two different number. When I send them a secure message, the message gets stuck in pending status. From that point on, all other secure messages sent to anyone else also get stuck in pending status. The only way I've found to fix things is to uninstall and reinstall the app.

I first noticed this in August 2015, when I sent a message to my contact's old number, for which I later discovered he didn't have access anymore. Reinstalling was the only way to fix things, and I messaged him twice (ie. two reinstalls) before realizing the root of the bug.

I thought it was specific to that old number he'd registered, but now his new number has done the same thing, and it looks like I'll need to reinstall.

Here the log from a subsequent failing message, but I unfortunately don't have the log from when I first messaged the poison friend, after which the problem resurfaced:
https://gist.github.com/anonymous/e3a9af2dd3a39de5d1f1

My contact's device is Samsung 6 edge

**Comment by moxie0** [comment]
There is no message send attempt in this log, can't do anything without a log.

**Comment by patcon** [comment]
Odd. Thanks. I'll reinstall and try to get logs for the whole flow

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
