### ISSUE TITLE
Outgoing SMS occasionally hangs

### ISSUE THREAD

**Issue by glamrock** [signalapp/Signal-Android#4281]
https://gist.github.com/2c8a2d5af9d77332289bb

I promised @mcginty I'd post a log when this happened, but this time it was plain SMS, so I suspect this is just TS not knowing it was sent.

**Comment by glamrock** [comment]
(Incidentally, getting a new phone fixed most other issues I was having)

**Comment by mcginty** [comment]
404!

**Comment by glamrock** [comment]
Fixed: https://gist.github.com/anonymous/2c8a2d5af9d77332289b 

Perils of filing a bug via mobile! ;)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
