### ISSUE TITLE
Messages with or without country code gets split in list

### ISSUE THREAD

**Issue by lukebarone** [signalapp/Signal-Android#4282]
My contacts are usually stored as the area code and phone number in my phone. When I text them, they appear in their own conversation. When they reply, my telco puts the country code on the SMS automatically, so they appear to be in a different conversation.

I suggest merging them together - if I have a contact that is 234-555-1234 in my address book, they should be merged with messages coming from +1-234-555-1234 automatically.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
