### ISSUE TITLE
[Feature Request] Save encrypted media to SD-Card

### ISSUE THREAD

**Issue by Wasseranomalie** [signalapp/Signal-Android#4297]
I have a phone with very limited internal memory for Apps. With the great feature of large attachment support my limited memory space gets overwhelmed so I have to store these media files decrypted and delete them.

It would be great if TextSecure would save received media files on the SD-Card like WhatsApp does.

Maybe related: #4065

**Comment by Dyras** [comment]
Sounds wonderful to me. My 32 gig SD-card is really empty at the moment, while my phone is really full.

**Comment by piratenpanda** [comment]
Threema also does this

**Comment by LoveIsGrief** [comment]
I wasn't aware that WhatsApp did this (at least I haven't found out how). But cheap phones on the market still don't have a lot of storage and all of the google stuff is taking up lots of space. Offloading the data to an SD card would be highly appreciated.

**Comment by GnafGnaf** [comment]
Yes, please do this! Signal quickly becomes the biggest app on my phone since I use it a lot and then I have to decide if i keep the messages or delete other apps.

**Comment by breznak** [comment]
Can the devs comment on this "problem"? I totally agree, using Signal actively (photos, vids), the data storage accumulates 4GB easily. It would be no problem if the data could be stored on SD card instead of phone root memory.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
