### ISSUE TITLE
Receiving messages while showing "All Pictures" lets  TS jump to last picture

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#4303]
I did not find anything about this issue:

When showing all pictures in a conversation and receiving a message in this conversation, TS jumps to the last pictures.

I think this behaviur is not intended.

**Comment by 2-4601** [comment]
Cannot reproduce any more with 3.6.0.
(I was able to reproduce this with whatever the version was on 26 Oct.)

**Comment by mawed** [comment]
3.6.0
I reproduced it right now.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
