### ISSUE TITLE
Notifications during calls

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#4318]
It is really annoying to have the phone vibrate while on a _Signal_ call. I had the same problem with Redphone too.

Currently on Signal 3.1.0, rooted Moto G 4.4.4 with Xposed.

I now remember that I've had this trouble with TS vibrating when I'm on other calls (Skype) as well.

**Comment by dcherian** [comment]
Related: #79, #3321, this commit: https://github.com/rhodey/TextSecure/commit/77fa36efdcb4810d0b24c45fe6db64d2cb67d66e

**Comment by hrehfeld** [comment]
I also get this on Motorola Moto G with 5.x, and also on Xiaomi Redmi Note 4 with LineageOS (current)

It's very disruptive, to the point where I rather don't use the feature to call with signal and instead rely on normal calls.

**Comment by deutrino** [comment]
My ear was quite unpleasantly surprised to find that this is still a problem in Signal 4.16.5 on LineageOS 14 (Android 7.1.2).

**Comment by cjk28** [comment]
Very annoying, especially on nexus 5x which has obscenely violent vibrate. Was hoping that this might be one thing that signal might do better over telegram. the google phone app: https://play.google.com/store/apps/details?id=com.google.android.dialer&hl=en_GB just plays a quiet beep and surpresses vibration when you get a notification mid-call which is perfect.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
