### ISSUE TITLE
Localisation errors in Google Play store text

### ISSUE THREAD

**Issue by barrystaes** [signalapp/Signal-Android#4348]
This concerns localisation of the Google Play store listing for "Signal Private Messaging".

The top sentence in my devices language seems to be auto-translated. It also translates the product name (Signal) and introduces translation errors.

NL / dutch:
`Signaal maakt privacy eenvoudig. Stuur tekst, foto's, en de groep boodschappen gratis!`
better would be
`Signal maakt privacy eenvoudig. Stuur tekst, foto's, en groepsberichten gratis!`

I suppose more language have this problem. 
No PR because i could not find the store texts in the repository.

**Comment by SARG04** [comment]
In the Google Play translation it is still called "TextSecure Privater Messenger" (as name and in the text).
And the translation of the (outdated) res/values/google-playstore-strings.xml is not on Transifex. Where the App translation is handled.

**Comment by RiseT** [comment]
@SARG04 Correct. Always been wondering where the (German) Play Store strings are translated (or rather *not* translated...)

**Comment by vinilox** [comment]
In French, the Google Play translation is also outdated it's "TextSecure, Messagerie Privée" instead of"Signal..."

**Comment by barrystaes** [comment]
FWIW; the text in question appears in the Play Store app (positioned between the main text and the screenshots) but is not shown in the Play Store website.

**Comment by RiseT** [comment]
Take a look at #4408. At this point in time, each language's translation team has to send @moxie0 the updated translation (outside of Transifex)...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
