### ISSUE TITLE
W/PropertyValuesHolder(15081): Method setScaleX()

### ISSUE THREAD

**Issue by Safari77** [signalapp/Signal-Android#4349]
logcat started showing 15 if these per second after calling with Signal 3.1.1, Android 5.0.2

```
11-03 15:26:00.515 W/PropertyValuesHolder(15081): Method setScaleX() with type float not found on target class class org.thoughtcrime.redphone.util.multiwaveview.TargetDrawable
```

**Comment by mcginty** [comment]
Unless there are UI bugs caused by that, it's probably benign.

**Comment by Safari77** [comment]
Do you mean this is a feature not getting fixed?
It's not benign to spam 15 lines a second till next reboot or killing of Signal.

**Comment by mcginty** [comment]
It wasn't clear in your description that it was spamming for the rest of the process lifecycle.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
