### ISSUE TITLE
Secure call on Huawei Nexus 6P uses rear mic

### ISSUE THREAD

**Issue by oscillik** [signalapp/Signal-Android#4360]
Issue is exactly as it says in the title - when making a secure call with Signal, the mic being used is the wrong one - the Nexus 6P has three mics (two front, one rear) and Signal is defaulting to using the rear mic, with no way to choose which mic is used.

Huawei Nexus 6P, running Android 6.0

Debug log as below
https://gist.github.com/anonymous/e7fc8c82979d01600a12

**Comment by tribut** [comment]
Same thing appears to happen on the Moto X Play.

**Comment by 2-4601** [comment]
@oscillik Is this still an issue with >3.31?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
