### ISSUE TITLE
Ugly loading animation on updating group

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#4377]
On updating groups an old and ugly loading animation appears.

Device info: `*`, Signal `3.1.1`

![tmp_5749-_20151104_172601-1054093989](https://cloud.githubusercontent.com/assets/5571650/10944810/2dd8a420-831b-11e5-87e4-67d05334b3ad.JPG)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
