### ISSUE TITLE
Other users cannot see me as a Signal user

### ISSUE THREAD

**Issue by Pesebrero** [signalapp/Signal-Android#4378]
Sometimes when other user installs Textsecure and tries to send me a message, he doesn't see me as a Textsecure user. So the only way he can message me is through SMS instead of using Textsecure network. The latter is better because SMS may or may not have associated costs, but data is rather cheap or even "free".

Needless to say, I'm failing to convince people to use Textsecure because of this. My device is a Samsung Galaxy S7273t. 

I'm from Argentina, and I've found another issue which may be related, but is less specific (and I'm trying to avoid to use SMS):
https://github.com/WhisperSystems/Signal-Android/issues/1511

Sorry about my english, thanks in advance.

**Comment by jeremymasters** [comment]
This is probably more of a support question. (http://support.whispersystems.org) Have they tried the pull to refresh in the contacts list in Signal (was Textsecure)?

**Comment by Pesebrero** [comment]
Thanks for your answer jeremymasters.

I thought user detection was automatic. I will use my mother's phone as gunea pig for testing this issue. I've already tried several reinstalls with it.

By searching "pull to refresh", I have found this issue: https://github.com/WhisperSystems/Signal-Android/issues/3949

**Comment by moxie0** [comment]
My guess is that there are multiple ways to format mobile numbers in argentina or something like that.

**Comment by Pesebrero** [comment]
Yes, that's my guess too, all those "+5411", "+54911", "005411" "1115", etc. could be causing trouble. They are explained in detail in #1511.

**Comment by Pesebrero** [comment]
This is still happening with the latest version.

Is there a way to escalate for a quicker solution? Signal is essentially not working in Argentina because of this.

**Comment by tandiljuan** [comment]
@moxie0 I've documented my tests in the ticket #1511 . Also I've described a logic that could be used to solve this kind of issues.

**Comment by Pesebrero** [comment]
Still an issue with version 4.11.5.

Signal is still unable to recognize the traditional "15XXXXXXXX" format, however it seems to recognize the "11XXXXXXXX" format with local area code at the beginning (in this case, "11", used in the Buenos Aires metropolitan area). So it's clearly recognizing local numbers without the country code.

The random issue with or without the "9" is also present. Just verified from the same device with two different contacts, both with the same carrier (Claro). Both were on my contact list with full number including country code. One it only appeared on my contact list with the "9" (+54911XXXXXXXX)  and the other without it (+5411XXXXXXXX). I had to manually edit the numbers in order for them to appear, otherwise they are not reachable by Signal. As you can see, this is really a major issue.

@moxie0 How we can give this more priority?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
