### ISSUE TITLE
Unable to download MMS messages with Swisscom

### ISSUE THREAD

**Issue by FreeMinded** [signalapp/Signal-Android#4387]
I just updated to Signal 3.1.1 and I'm still unable to download MMS messages.
I get a message and when I click on download it tries to connect to the server but fails (with no error message). All MMS settings are on standard. And the settings were just updated by setup message from Swisscom (using M-Budget-Mobile). I can receive MMS messages with the standard app.

This issue is related with #349. As suggest by @moxie0 i open a new issue as it's not fixed for me.

**Comment by moxie0** [comment]
Can't do anything without a debug log.

**Comment by FreeMinded** [comment]
Here you go: https://gist.github.com/41179d69addd5780706f

**Comment by moxie0** [comment]
You have to capture the debug log immediately after whatever behavior you're trying to diagnose fails. There's no attempt to retrieve an MMS message in this log.

**Comment by FreeMinded** [comment]
Sorry for my ignorance...
This one should be better https://gist.github.com/9fd8b4959a5f6166dbe3
And thanks a lot for looking into it!

**Comment by moxie0** [comment]
The MMS server is returning "not found," meaning the media content is no longer on their servers.  This usually happens if you have another SMS/MMS app installed that is misconfigured to retrieve MMS even when it's not the default MMS app and it beats Signal to retrieving the content.

**Comment by FreeMinded** [comment]
I tried to figure out what could be interfering and disabled the pre-installed SMS/MMS app. But it didn't change anything. So I'm back using Signal for SMS and the built in app for MMS (which a receive very rarely anyway)
Thanks @moxie0 for trouble shooting!

**Comment by FreeMinded** [comment]
closing issue...

**Comment by m-kuhn** [comment]
Same provider, same issue, same response (404).
The strange thing is, that I get a reminder every day for a week, so either the app is doing that or my provider sends it.
If it's the provider who sends it, why would he do it if the message has already been downloaded and is no longer on the server?

**Comment by FreeMinded** [comment]
@m-kuhn I guess it's the provider sending it as I experienced the same in my case. After reverting to the standard app for receiving MMS I got the messages a day later on the standard app.
So the messages are definitely still on the server an the issue is somewhere else.
I reopen this issue in the hope we'll find the reason and a fix someday.

@moxie0 If there is any tests I could do to help troubleshoot let me know.

**Comment by m-kuhn** [comment]
Yesterday I was able to download an MMS by clicking on the error message (this did not work previously, the provider or the app must have changed something). @FreeMinded can you confirm?
However, I just received the *reminder message* for the old message again, so there's still something strange about it.

**Comment by FreeMinded** [comment]
@m-kuhn Unfortunately nothing changed on my side. Still unable to download messages.

**Comment by m-kuhn** [comment]
I can't really tell when it works and when not.

I receive a reminder (no picture), I can click it and after one or two retries it works (on WLAN, not sure if it matters). Then I still get 6 (estimated) daily messages  mostly with pictures but sometimes just a reminder again.

**Comment by FreeMinded** [comment]
I got a new phone (Sony Xperia Z3 compact, Android 5.1.1) and now I receive MMS messages correctly. But I get the messages (incl. picture) again and again until the message is expired on the server.

**Comment by agrajaghh** [comment]
@FreeMinded please post a debug log

**Comment by m-kuhn** [comment]
Captured after a click on a reminder

http://pastebin.com/fipKLDhd

I removed some of the noise, but there is still a lot left, sorry

**Comment by FreeMinded** [comment]
Here is my log file capture just after having received the same image for the 4th time.
https://gist.github.com/anonymous/70783ff9fa342d5fe4bd

**Comment by FreeMinded** [comment]
Mhh, my problem is still not solved. I received a message which fails to download. The error log is here https://gist.github.com/anonymous/8b94aaf94289887e17b3
Interesting is that I'm able receive some messages (see above) but others not. I will post more information if I can find a pattern (I don't receive many MMS messages).

**Comment by m-kuhn** [comment]
@FreeMinded try clicking the message a couple of times. Suddenly it works.

**Comment by FreeMinded** [comment]
@m-kuhn Thanks for the hint! It actually worked. In case that heplps, attached the log captured after the download succeeded https://gist.github.com/anonymous/191e9e38961ff8fa4757

**Comment by jonathanernst** [comment]
Same provider here (Swisscom).

MMS download works fine here (@FeeMinded and @m-kuhn did you enable image, audio and video downloading with mobile data in the settings ?)

However every time I receive a MMS, Signal receives it every day at the same time of day for seven days (I guess until it expires), just like m-kuhn.

**Comment by FreeMinded** [comment]
@jonathanernst I have only enabled images over mobile data. But that shouldn't be the problem as I never got any audio or video so far.
I have the same behavior as you with the repeated reception of the message till it expires on the server. See my log file posted above for more details...

**Comment by agrajaghh** [comment]
quoting @Prosouth from #5177:
> When I receive a MMS, I open it to read it and the next day, I receive the same MMS during one week. There is no issues with the content of the MMS, it's correctly downloaded.
> 
> I suspect that the MMS is downloaded correctly but not marked as read for my network operator(Swisscom).
> 
> Operator: Swisscom (Switzerland)
> Device : samsung SM-G925F (zeroltexx)
> Android : 5.1.1 (G925FXXU3QOKN, LMY47X.G925FXXU3QOKN)
> Memory : 52M (22.86% free, 256M max)
> Memclass: 256
> OS Host : SWDD5010
> App : Signal 3.10.0
> 
> Here's the log : https://gist.github.com/anonymous/7c85725947a676ea0479

**Comment by nja** [comment]
I can't download MMS. Switching to other message apps it works. Switching back to Signal I get the same problem again.

https://gist.github.com/anonymous/bd0c8cda48e4a8798060

**Comment by moxie0** [comment]
@nja From the log it looks like you need to configure your APN information.

**Comment by nja** [comment]
My APN settings are the defaults. As I said, they allow other messaging apps to download MMS fine. Here they are if it's of any help:

> Name: Telia Internet
> APN: online.telia.se
> Proxy: Not set
> Port: Not set
> Username: Not set
> Password: Not set
> Server: Not set
> MMSC: Not set
> MMS-proxy: Not set
> MMS-port: Not set
> MMS-protocol: WAP 2.0
> MCC: 240
> MNC: 01
> Authentication type: Not set
> APN-type: default,hipri,dun,supl
> Bearer: Unspecified
> 
> Name: Telia MMS
> APN: mms.telia.se
> Proxy: Not set
> Port: Not set
> Username: Not set
> Password: Not set
> Server: Not set
> MMSC: http://mmss/
> MMS-proxy: 193.209.134.132
> MMS-port: 80
> MMS-protocol: WAP 2.0
> MCC: 240
> MNC: 01
> Authentication type: Not set
> APN-type: mms
> Bearer: Unspecified

**Comment by jandrieu** [comment]
I also have this issue. I can't download group texts, with error "MMS failed to download"  it's been this way for a while.

here's a debug log https://gist.github.com/b0a0261d6d396e026d5323e2d4cc8f1f

**Comment by riyapenn** [comment]
@jandrieu did you contact support@whispersystems.org and/or adjust APN settings according to the support page http://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do-?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
