### ISSUE TITLE
Make contact sort configurable

### ISSUE THREAD

**Issue by g0hl1n** [signalapp/Signal-Android#4391]
I'd love to see some settings to configure the sort of my contacts.
Currently all contacts are sorted descending by their first name.
At least a setting to sort the contacts by their last name would be really great!

A similar feature request was posted in #741, but there was no response on that.

Thank you!

kind regards,
g0hl1n

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
