### ISSUE TITLE
ApplicationPreferencesActivity_on and ApplicationPreferencesActivity_off are shared between different functionalities

### ISSUE THREAD

**Issue by amire80** [signalapp/Signal-Android#4418]
By translation and reading the Java code, I noticed that the translatable strings ApplicationPreferencesActivity_on and ApplicationPreferencesActivity_off are used for telling whether passphrase, SMS and MMS are on or off.

The words for "on" and "off" are the same in English for describing everything, but in other languages they may be different for different things.

As far as I can see the code, it's best not to use such messages at all, and instead to have messages such as "Passphrase on", "Passphrase off", "SMS on", "SMS off", etc., instead of sticking messages together in runtime.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
