### ISSUE TITLE
Feature Request: Show total sum of sent texts / reset monthly

### ISSUE THREAD

**Issue by kerlerm** [signalapp/Signal-Android#442]
Hi devs!

I really like your texting app, but I'm missing a key feature: 

My mobile contracts allows to send 200 texts/month for free. More texting costs extra money. Could TextSecure show the total of all texts sent und issue a warning, when the limit has been reached?

The counters/quota should be reset once a month or by user-defined date.

Would be cool to get that onto the next release!
Thanks a lot!

**Comment by beatstick** [comment]
I' d like to see this feature as well.

**Comment by moxie0** [comment]
@beatstick Please don't bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md
