### ISSUE TITLE
playing audio should hold a wake lock

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#4424]
if you play audio that's longer than the screen timeout on your phone, it abruptly stops because onPause happens.

**Comment by psyfx** [comment]
Bug is still present in 3.11.1
Audio stops immediately after the screen goes dark. (a few seconds)

**Comment by moxie0** [comment]
@psyfx Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
