### ISSUE TITLE
T-Mobile can't download MMS

### ISSUE THREAD

**Issue by ThaWeatherman** [signalapp/Signal-Android#4443]
Currently not working on WiFi or 4G. Samsung Galaxy S4, CM 11 nightly. Fails with VPN off and on. Using default carrier settings.

**Comment by agrajaghh** [comment]
please post a debug log (right after the download failed)

**Comment by ThaWeatherman** [comment]
I see a button to submit one, but how do I export it?

**Comment by merkste** [comment]
Push the button, long press the shown irk This should copy the URL you want to post here.

**Comment by merkste** [comment]
Does it work with 3G or on another phone? T-mobile wanted to disabled MMS after the stage fright vulnerabilities at least until the fixes are deployed. But that info might be outdated already.

**Comment by ThaWeatherman** [comment]
https://gist.github.com/f2b08a8e3033d029c2e4

I can get MMS with the normal messaging app.

**Comment by xHazardx8** [comment]
I have the same problem, cannot download mms on wifi (wifi calling compatibility enabled).
Another thing I noticed is the default APN shows MetroPCS, I changed it to TMobile.

https://gist.github.com/anonymous/f83b9377999001a94e62

**Comment by JSkier21** [comment]
This is related to testing for connectivity with both CM and TMO rom. With TMO, wifi calling being both enabled and active, MMS won't work. If you change to cellular preferred or wifi calling is not active, MMS works just fine. Not sure what to do on CM, but Signal is failing to verify connectivity in either case. 

This was previously discussed regard TMO wifi calling, although I think this should be left open and worked on for both stock TMO and root CM roms. I'm available to test TMO rom and wifi calling. 

Previous mention: https://github.com/WhisperSystems/Signal-Android/issues/2160

**Comment by ThaWeatherman** [comment]
Thanks for the response. So at least for now, if I disable wifi calling in CM then I won't have this issue?

**Comment by JSkier21** [comment]
I don't use CM, is there a ROM with wifi calling on it? I would just try to turn off wifi calling or go to preferred cellular, this works for the TMO factory ROM.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
