### ISSUE TITLE
scroll wheel no longer works in conversations

### ISSUE THREAD

**Issue by 2011** [signalapp/Signal-Android#4445]
This may very well get slammed, but I am going to complain anyway. :)

Yes, I am using a mouse with android, and it worked perfectly with TextSecure from the beginning of time (or whenever I started using TextSecure) through 2.27.2.

As of 2.28.1 (and also Signal 3.1.1), the scroll wheel no longer works in the conversation window (ie. to scroll up to see older messages). Now I have to press and hold the mouse button (and drag) to scroll up and down. The scroll wheel still works fine in other parts of the app (the message compose box and the contact list), but not in the conversation window.

Would like this fixed if you can figure out what happened. :) Thanks.

**Comment by johanw666** [comment]
My guess would be that https://github.com/WhisperSystems/Signal-Android/commit/99d3374d35b5027850fdc31c8a2620fb5f83fbf7 is responsible. I have no idea how to fix this though.

**Comment by McLoo** [comment]
quick lookup: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#onGenericMotionEvent%28android.view.MotionEvent%29

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
