### ISSUE TITLE
signal contact not present in signal contact list

### ISSUE THREAD

**Issue by bartz1** [signalapp/Signal-Android#4447]
(I'm using the latest beta on android 4.1)
1. a friend of mine created a group with me and X
2. I added X's phone number, as I didn't have it
3. after several "problems" with signal not displaying the name of the contact, I managed to save the contact AND have his name displayed correctly in the group chat
4. when i go to the contacts list, he's not present among the signal contacts, but he is present in "all contacts". However I am able to send him signal messages in a private chat with him just fine (and not problem within the group either). I did update the contact directory several times but nothing changed.

**Comment by McLoo** [comment]
did you pull-to-refresh your contact list?

**Comment by bartz1** [comment]
" I did update the contact directory several times but nothing changed."

**Comment by obifur** [comment]
I had a similar problem.. #4338. At the end I had to reinstall. Unfortunately the backup function still can't handle groups :(

**Comment by bartz1** [comment]
Reinstalling is not an option for me. If I uninstall Signal, I don't think I'll reinstall it again. Too many issues/Not worth the trouble.
I tried deleting and recreating the contact several times, saving it both on sim and phone. Rebooting doesn't help.

**Comment by ambux** [comment]
I deleted signal contact details of one friend in the contacts app, the contact details in the carddav-account still exist. 

This lead Signal to crash whenever I pull-refresh the contact list within Signal or when I sync the Signal-account from the accounts list. 

See the log of a crash here: <script src="https://gist.github.com/anonymous/a5436a033d830f12c180.js"></script>

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
