### ISSUE TITLE
Thread view

### ISSUE THREAD

**Issue by mp081280** [signalapp/Signal-Android#4455]
First - I did not notice that issue on Galaxy Note 3 but I cannot confirm if problem does not occur on that device.

Currently I face this issue on OnePlus Two. OS version is Android 5.1.1 with modifications called Oxygen OS 2.1.1. System is not rooted.

Problem description: Message box is empty (no messages). I create new message to person X - a thread is created. When person X replies to my message second thread is being created (which means that the message is not added to previously created thread).
This is annoying because for each person for which I create first sms, two threads will be created as soon as the person will replay to my message.
I've discovered a workaround: write first sms, person replies, further communication is done withing second thread, first sms should be deleted.

Let me know in case further details would be needed.
Cheers!

**Comment by moxie0** [comment]
@mp081280 Are you in a country where the same number can be formatted differently? For instance Mexico, where numbers can either be +52 or +521?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
