### ISSUE TITLE
Notification sound et led color

### ISSUE THREAD

**Issue by SWGAKamui** [signalapp/Signal-Android#4475]
Hello, I've noticed that the notification sound and the led color isn't separate from the telephone sound and led.
When you change the led, it change all notification led color (example an email will be the same color as the application).
For the sound, the sound won't change if the telephone notification doesn't change, which is quite frustrating since. Now everything have the same sound.

Thanks for the application !

**Comment by 2-4601** [comment]
I have never experienced this (Nexus 4, stock 5.1.1)

Which device, ROM and Signal version are you using?

**Comment by SWGAKamui** [comment]
Sony Xperia S
Android 4.1.2
Signal version 3.1.1

**Comment by SWGAKamui** [comment]
I tried to look at the code if I could found the bug, but I couldn't, sorry.
Maybe is it from the library "Notification" which change all notification color and not just the signal app notification.

As for the sound, it seems that it doesn't save the sound notification choice. When I choose it, go back and look which sound was choose, my choice isn't save.

I hope it will help you !

I will try to look at it this week-end.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
