### ISSUE TITLE
No MMS on HTC One + T-Mobile

### ISSUE THREAD

**Issue by judecalvillo** [signalapp/Signal-Android#4476]
Ever since updating to your latest version, I can no longer receive or send MMS messages through the environment mentioned above. Hopefully you can fix this soon, because I otherwise like your app. Thx.
- Jude

**Comment by agrajaghh** [comment]
please post a debug log (right after the MSS failed)

**Comment by judecalvillo** [comment]
Oh, I'm not an Android developer, nor am I really interested in installing + learning the Android SDK right now. This is simply where your Google Play listing says to report bugs. On that note, all the app says is that it 'Failed to send' (in the case of sending) and that "some issues need my attention," which only expands to sent/received time-stamps. Hope that helps.

**Comment by judecalvillo** [comment]
Btw, I *am* able to send/receive MMS from my standard 'Messages' app for now. I would just prefer to use 'Signal.'

**Comment by 2-4601** [comment]
Posting a debug log does not need Android dev tools.
You can do it within Signal: **Settings -> Advanced -> Submit debug log**
And paste the link here.

**Comment by judecalvillo** [comment]
Oh, ok. I'll send myself an MMS message now and send you a report shortly, assuming it doesn't publicize my private phone number.

**Comment by 2-4601** [comment]
The logs might contain the last to digits of the phone numbers. At least for push messages. Don't know about MMS. In any case full numbers are not in the logs in either case.

**Comment by judecalvillo** [comment]
Ok, thanks. Here goes... https://gist.github.com/99a134438f0653e8cadd

**Comment by judecalvillo** [comment]
Hi. I haven't heard any update on this, even though you've marked the issue "closed." Unfortunately, I've updated the app, and I'm still experiencing the issue (I cannot receive MMS messages on my HTC One M7). I look forward to hearing from you.

**Comment by heyimgay** [comment]
This issue is still marked open

**Comment by judecalvillo** [comment]
I just installed the latest version of Signal, and it appears I'm still encountering this problem. It's been 5 months since I first reported this issue, and I'd love to use Signal, but it seems I have to return to the default messaging app for now. I hope to see this resolved soon!

**Comment by joshmoore** [comment]
Same for Fairphone 1 + T-Mobile (Germany)

**Comment by moxie0** [comment]
Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
