### ISSUE TITLE
Silent SMS detection

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-Android#448]
Silent SMS's are usually used for locating GSM user (when user receives SMS, location data are stored in data retention database) identifying his IMSI/TMSI number, etc. More about it here: http://matej.owca.info/predavanja/GSM_security_2012.pdf, page 39.

Silent SMS are usually used together with IMSI catchers, more info here: 
http://secupwn.github.io/Android-IMSI-Catcher-Detector/

The problem is, that silent SMS are - well, silent. User cannot see whether he or she has got that kind of SMS.

It would be great if TextSecure would have an option to detect silent SMS'es and show them.

BTW, silent SMS'es could be detected with Osmocom paltform. There is an application for Osmocom called Catcher catcher, which also detects silent SMS's, more info here: https://opensource.srlabs.de/projects/catcher/wiki

However, Osmocom is highly "hacking" platform, it is not usable for everyday use.

Does this idea sounds interesting?

**Comment by Dastgsm** [comment]
what should i do for example for having tmsi of someone that i know his tmsi ???
