### ISSUE TITLE
ALLCAPS shouldn't be used for emphasis in user interface strings

### ISSUE THREAD

**Issue by amire80** [signalapp/Signal-Android#4496]
ALLCAPS is used in some UI strings for emphasis. This is a localization anti-pattern, because many languages don't have capital letters - Arabic, Persian, Hindi, Georgian, Thai, Chinese, and many others.

Emphasis should be done by actual styling and design.

**Comment by Dyras** [comment]
Personally I don't really see the problem. It works well for 98% of all available languages, and I'm sure not having capital letters isn't going to affect the app negatively.

**Comment by mcginty** [comment]
This was done for compatibility reasons (the all-caps attribute in Android's TextViews are only available from API 14). Maybe @moxie0 has a stronger opinion on this, but we could move to doing this programmatically if it's a pain for translators.

**Comment by amire80** [comment]
Not resolving this means that in languages that don't have capital letters, there won't be any emphasis at all, and there are quite a lot of such languages (much more than 2%).

**Comment by amire80** [comment]
... And if it isn't clear, ALLCAPS as such shouldn't be used at all, anywhere. If emphasis is needed, it should be defined as *emphasis* - it might be implemented as ALLCAPS in some languages, as a bold font in others, etc.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
