### ISSUE TITLE
Add size of attachement to message info

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#4554]
I think it'd be helpful to see how big a data attachment is in the message info.
1. long-press received data (image, video, audio, whatever)
2. tap the circle-i
3. Would like to see how big the data is that was sent for that particular message.  Then I could go through and delete large attachments that were sent to reduce the size of data stored inside Signal.
4. Not sure how much it applies to pure text "signals" but it would look symmetrical.

**Comment by 2-4601** [comment]
Related #863

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
