### ISSUE TITLE
Sending picture with text doesn't display text on HTC One

### ISSUE THREAD

**Issue by kyrofa** [signalapp/Signal-Android#4561]
I'm trying to convince my wife to use Signal with me (baby steps). However, while I was trying to show her how it wouldn't change her life at all, I sent her a picture message with some text, and this is how it showed up on her phone (an HTC One M7, with the default texting app):

![screenshot_2015-11-16-16-01-29](https://cloud.githubusercontent.com/assets/946674/11194760/edf2ff12-8c7b-11e5-8109-e4a743aecf3a.png)

It looks like a slide show, with two items. And when opening the slide show, there's only a single item (the picture). The text is nowhere to be found:

![screenshot_2015-11-16-16-01-48](https://cloud.githubusercontent.com/assets/946674/11194785/18252724-8c7c-11e5-86eb-0e343e40f8d0.png)

Sending her a picture message with text from Textra (the texting app I was previously using) looks perfectly fine:

![screenshot_2015-11-16-16-03-45](https://cloud.githubusercontent.com/assets/946674/11194803/328b46b6-8c7c-11e5-8fdc-a96d38106976.png)

End result: my wife refuses to use Signal if it "screws up the pictures I send to my mom." I can't really blame her, but I'd sure like it to work for her. Anyone have any idea what's going on?

**Comment by kyrofa** [comment]
No thoughts on this?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
