### ISSUE TITLE
Audio Attachment with .3gpp-file is first shown as audio, then video

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#4576]
When sharing a .3gpp- Audio file directly via filemanager, Signal directly shows the video image. 

When attaching it via 
attachment drawer -> Audio -> filemanager, 

it first get shown as a audio (with play button and playable) as draft, but sent it is shown as video (not directly playable).

Signal 3.3.3

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
