### ISSUE TITLE
Receiving constant notifications that "XXX is on Signal, say hey!" where XXX is myself

### ISSUE THREAD

**Issue by fredronnv** [signalapp/Signal-Android#4604]
I'm receiving constant notifications that XXX is on Signal, however it seems to be myself. I've got two phone numbers on Signal, in different countries, I don't use one anymore and that particular SIM hasn't been online for around two months. No other contacts seem to have this problem. Issue #4406 sounds similar and is probably related but I'm using a later version of Signal (3.4.2).

[Debug Log](https://gist.github.com/anonymous/f14ad6ad761a64b47838)

![s51116-095343](https://cloud.githubusercontent.com/assets/5538536/11275517/4bcdd436-8ede-11e5-9560-1e43ce278f43.jpg)

**Comment by jeremymasters** [comment]
Try this for the number you don't use:
http://support.whispersystems.org/hc/en-us/articles/213132377-How-do-I-unregister-Why-is-my-message-undelivered-
https://whispersystems.org/textsecure/unregister/

**Comment by moxie0** [comment]
It doesn't look like anything is in that log, did you capture it immediately after getting a notification?

**Comment by fredronnv** [comment]
Another [debug log](https://gist.github.com/anonymous/07351551eb8d3ca9a4f6)

I've captured this right after a notification arrived. I have myself as two distinct signal conversations with two different phone numbers and they exhibit the same issue. They have different country codes.

I am unable to unregister the other number as I am unable to find my SIM at the moment, however I believe I can do so within a few days and report back.

**Comment by mawed** [comment]
Maybe blocking this number works as a short time solution.

**Comment by fredronnv** [comment]
I've actually tried blocking both numbers, but that doesn't stop these notifications. Also tried deleting the threads but no luck.

I have noticed, however, that the notifications have now stopped (3 hours ago since the last one), has something perhaps been changed server-side?

**Comment by fredronnv** [comment]
Actually, that was probably too optimistic, the notification(s) have started arriving again.

[debug log](https://gist.github.com/anonymous/8bf5d7f97d6b9bc62aca)

If there is anything else I can do to provide more information please do let me know.

In the meantime I'm blocking notifications from Signal, that kind of helps, with the downside that I have to check for messages every now and then, but I'm not too bothered by that.

**Comment by 2-4601** [comment]
Blocking just the single number does not work as @mawed suggested? (Conversation settings -> block)

How about if you temporarily remove the number from your systems contact app?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
