### ISSUE TITLE
MMS fails to everyone not on signal.

### ISSUE THREAD

**Issue by infowire** [signalapp/Signal-Android#4644]
ATT is my provider. HTC M8
https://gist.github.com/4b49ca535dfc40114c41

**Comment by infowire** [comment]
Any ideas ???

**Comment by mcginty** [comment]
Your log doesn't have any MMS activity in it. Please try sending an MMS and then immediately upload the log after the failure.

**Comment by infowire** [comment]
https://gist.github.com/b3b12b01b460a760621b

**Comment by infowire** [comment]
It failed then I did the log.

**Comment by riyapenn** [comment]
Also check out http://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do-

**Comment by infowire** [comment]
If someone can give me the info for the. APN for Android on att

**Comment by KevinMK** [comment]
I just had Signal fail to send MMS to someone not on Signal. I took a debug log immediately after this occurred.
https://gist.github.com/anonymous/79cd06ed3221d2916a32

I am on an AT&T Samsung galaxy note 4, running Android 5.1.1, with signal version 3.6.1.

I sent my first mms hours before that log. One difference from that first time and the log is the first image was taken with the camera inside the Signal app, while the log was generated after an image failed to send that had been taken and saved outside if the Signal app. Also, there was text along with the image in that first one. None of it was sent. However, there was no error message, or failure to send message.

Once I found out that the first image didn't send, I tried to replicate it by sending a another image. This time. I did get a message saying it failed to send the message. I then tried sending a picture taken through my camera app and saved on my device. This also failed to send. I then turned off my Wi-Fi and tried sending the image over 4g, and this time it had a spinning circle for 5+ minutes until I turned Wi-Fi back on and received another failure to send message. After that, I tried taking the image in a smaller resolution, but it still failed to send. Finally, I restarted the app and tried sending that smaller image again, and it failed yet again. Then I generated the log and posted this.

If you need more information, let me know. I'd love to continue using the app and become a supporter as well! My experience with it in the very short time I have used it is very positive except for the MMS issue. Thanks for the great app!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
