### ISSUE TITLE
Tell the user how to actually link devices

### ISSUE THREAD

**Issue by bartz1** [signalapp/Signal-Android#4649]
Assume that:
1. the user has no idea there's a Signal browser extension
2. the user opens the "device" section
What would they think? I think that instead of displaying "No devices linked.." you should display something like "[...] you can download our Chrome extension to add new devices! <link>". Though I get it, right now there's no official link to get the chrome extension - but I assume there will be a way soon, or you wouldn't have set this menu entry as visible? Anyway, consider this as a note for the future.

**Comment by raumzeit77** [comment]
+1

**Comment by moxie0** [comment]
@raumzeit77 Please do not post in issues unless you have material information to add.

**Comment by uberlaggydarwin** [comment]
I've submitted a pull request for this. Please don't merge it yet though.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
