### ISSUE TITLE
The translatable string preferences__input_settings doesn't seem to be used anywhere in the code

### ISSUE THREAD

**Issue by amire80** [signalapp/Signal-Android#4650]
There are several ways to translate the string preferences__input_settings, and I tried to figure out what is the right one. I couldn't find it anywhere in the app's interface, and when I grep the repository, I can only find in strings.xml file, but not in actual code. If it's not actually used, then it should be removed to avoid wasting translators' time.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
