### ISSUE TITLE
Audio download arrow icon misses the line below 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4663]
See Screenshots 

![picshop-fb2acdd4bf12478f22e153d2f060561f](https://cloud.githubusercontent.com/assets/5326916/11322933/bd7e2e26-9101-11e5-9ddd-125b33954c55.png)

![picshop-309fcf46a692e0fee6f43f55da13ae71](https://cloud.githubusercontent.com/assets/5326916/11322935/bd8429c0-9101-11e5-9db7-9a16e178bc96.png)

![picshop-0ea948c5600924fb018f1432f5c3d512](https://cloud.githubusercontent.com/assets/5326916/11322934/bd7f0828-9101-11e5-92c9-68e747deec61.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
