### ISSUE TITLE
Shared media draft disappears after reboot, orphaned PersistentBlobProvider file

### ISSUE THREAD

**Issue by unrulygnu** [signalapp/Signal-Android#4665]
While working on another issue, I found a handful of orphaned files in `app_captures`, at a time when I had no draft media messages pending. I narrowed down these steps to reproduce consistently, yet there may be other ways to reproduce the issue. 

**Steps to reproduce** (UPDATED)
1. `adb shell ls -la /data/data/org.thoughtcrime.securesms/app_captures/` to verify contents
2. Select a photo or video in Gallery/Photos
3. Share the media with Signal
4. Select a contact and note the time
5. Observe the draft media message in the Conversation
6. Tap `Back` (this saves the draft media message)
7. Tap on the Conversation to open it again
8. OPTIONAL: Tap `Home` (calls `onPause()`, but not `onDestroy()`)
9. `adb reboot`, install a new build, or other `Activity`-killing action that does not call `onDestroy()`
10. Open Signal
11. Observe the draft media message in the Conversation List
12. Tap the Conversation
13. Behold the disappearance of the draft media message
14. `adb shell ls -la /data/data/org.thoughtcrime.securesms/app_captures/`
15. Behold the orphaned, a-bit-too-persistent blob file

Device info: Nexus 5, stock Android 6.0 MRA58K, Signal 3.5.0 (d21fe51), 3.5.1 (6a18824)

App state: Signal registered, SMS enabled, default SMS app

**Comment by unrulygnu** [comment]
I can't reproduce this with #4689.  But as soon as I return to d21fe51, the existing video draft disappears like school in summertime.

**Comment by mcginty** [comment]
I've noticed this pre-3.5.0. I think this should go to 3.6.0 to speed up the .1 release.

**Comment by mcginty** [comment]
this sounds like a DraftDatabase issue?

**Comment by unrulygnu** [comment]
**DRAFT EXISTS**

* File in `/data/data/org.thoughtcrime.securesms/app_captures/` 
* Record in `drafts` table
* On opening the conversation:

        D/ConversationActivity: initializeDraftFromDatabase(), doInBackground(), threadId= 4
        D/DatabaseFactory: getDraftDatabase(context)
        D/DraftDatabase: getDrafts(4), results: [org.thoughtcrime.securesms.database.DraftDatabase$Draft@2ef9e02]
        D/DraftDatabase: clearDrafts(4)

**DRAFT GONE**

* File in `/data/data/org.thoughtcrime.securesms/app_captures/` 
* NO RECORD in `drafts` table
* On opening the conversation:

        D/ConversationActivity: initializeDraftFromDatabase(), doInBackground(), threadId= 4
        D/DatabaseFactory: getDraftDatabase(context)
        D/DraftDatabase: getDrafts(4), results: []
        D/DraftDatabase: clearDrafts(4)
* No calls to `draftDatabase.reset()`, `DraftDatabase#clearDrafts`, `ThreadDatabase#delete*` etc.

**Comment by unrulygnu** [comment]
From `ConversationActivity.java`

      @Override
      protected void onDestroy() {
        saveDraft();

From [Activity | Android Developers] (https://developer.android.com/reference/android/app/Activity.html#onDestroy%28%29):

> protected void onDestroy ()
> \<snip>
> *Note: do not count on this method being called as a place for saving data! For example, if an activity is editing data in a content provider, those edits should be committed in either [onPause()](https://developer.android.com/reference/android/app/Activity.html#onPause()) or [onSaveInstanceState(Bundle)](https://developer.android.com/reference/android/app/Activity.html#onSaveInstanceState(android.os.Bundle)), not here.*

**Comment by unrulygnu** [comment]
Updated all three diagnostic posts above on this issue.

**Comment by agrajaghh** [comment]
If the conversation is open and you restart the phone, will `onPause()` be called?

**Comment by unrulygnu** [comment]
@agrajaghh :
> If the conversation is open and you restart the phone, will `onPause()` be called?

* `adb reboot`: No

        E/(): Device disconnected
* Power button: Yes, but not `onDestroy()`

        D/ShutdownThread: Notifying thread to start shutdown longPressBehavior=1
        I/ShutdownThread: Sending shutdown broadcast...
        D/ShutDownListener: ACTION_SHUTDOWN Received, waiting for oemhook readiness callback
        I/ShutdownThread: Shutting down activity manager...
        W/PassphraseRequiredActionBarActivity: onPause()
        D/ConversationActivity: onPause()
        W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
        W/KeyCachingService: Decrementing activity count...
        D/ConversationActivity: onStop()
* Lightning strikes, other acts of God:  I assume not :stuck_out_tongue_winking_eye: 

And for the sake of thoroughness:

* Installing a new build: No

        I/ActivityManager: Force stopping org.thoughtcrime.securesms appid=XXX user=-1: uninstall pkg
        I/ActivityManager: Killing XXX:org.thoughtcrime.securesms/XXX (adj 0): stop org.thoughtcrime.securesms
        I/WindowState: WIN DEATH: Window{XXX u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}

**Comment by agrajaghh** [comment]
> adb reboot: No

> Lightning strikes, other acts of God: I assume not

thats okay I guess...

> Installing a new build: No

Android is so weird sometimes... :grimacing:

**Comment by unrulygnu** [comment]
> thats okay I guess...

I'm testing moving `saveDraft()` to `onPause()`.  Will try to create any other scenarios which normal users may encounter and see if it breaks.  If it's good to go, I'll submit a PR.

Thanks for the feedback!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
