### ISSUE TITLE
Contact/number duplicates after phone wipe (entries can't be edited or deleted)

### ISSUE THREAD

**Issue by darryl-grennan** [signalapp/Signal-Android#4669]
My friend had to wipe her phone.
She used Signal previous to the wipe and had several contacts.
After the phone was wiped she had all her contacts reloaded.
Upon installing Signal 3.4.2 all of her previous Signal contacts had duplicate entries in her contact list with only the phone number showing on said duplicates.
The duplicates were all linked/associated to Signal and couldn't be edited or deleted.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
