### ISSUE TITLE
Texts not sent/received - data issue?

### ISSUE THREAD

**Issue by kdbug** [signalapp/Signal-Android#4675]
I've been using signal on an Android phone for the past two weeks or so. Sometimes I will not receive messages for up to 18 hours after someone has sent them. Outgoing messages also have some delay, but seems to be less. I think this may be a data-related issue because I often get a few rapid messages when I turn on data or connect to a wifi source.

**Comment by RiseT** [comment]
*"or connect to a wifi source"*

I've been experiencing this lately on Marshmallow. But this is not limited to Signal. I'm having the same issue with e. g. the Gmail app. It almost seems like Marshmallow (sometimes) deactivates data & wifi as long as the display is turned off. As soon as I turn the display on, it seems to connect and I get a bunch of messages and emails. I haven't experienced this very often, though, but will keep an eye on it when it happens next time (if it is an Android issue - would sending a Signal log be of any help?)

**Comment by riyapenn** [comment]
Check out 6 & 8 specifically on http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
