### ISSUE TITLE
Improve UX when adding users to a group

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#4691]
There are two different options to add contacts to a group in the edit group view:
1. tap the "Add member" text input and start typing a name
2. tap the small "+" icon to see a full view contacts list
## 

Using the first option you will see a list popping up.
The problem with this list is that in contrast to the other list:
- it also shows non-Signal contacts and contact numbers, although I did not select Signal as default SMS app
- it does not highlight numbers registered with Signal
- the list is rather small and difficult to use
## 

Apart from that, I only noticed by chance that tapping the "+" icon gives me a perfectly nice and searchable contacts list, thinking that it was just a random design element.

Shame on me, but I did not discover that second option earlier because I always tapped the "Add member" text input since it is the largest and most visible item for that purpose. Then, when the keyboard shows up, I naturally start typing a name and then choose from the small list shown.
## 

I suggest to remove the text input field and always link to the full view list immediately.
Or make tapping the input field show the full view list, but with the keyboard already visible.

**Comment by bbinoy** [comment]
Additionally it would be very good for the user friendliness, if adding members/removing yourself (now in settings menu of the conversation) can be integrated in the members list (top right icon).

**Comment by paul-schulze** [comment]
On Android if you add a new member to group the chat history only says "Updated group". Would be much better to say " User XY added User YZ".

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
