### ISSUE TITLE
Fail invalid provisioning QR codes earlier

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#4699]
9b3457f0b2d733770433dbaf3715485445102343 handled the crash of scanning arbitrary QR codes but Signal still goes through all the steps before telling the user that the QR code was an invalid provision string.

![autobiography of a yogi](https://cloud.githubusercontent.com/assets/174176/11354625/c12fcae8-9255-11e5-9a77-cff7100be4e2.gif)

Would it be possible to make it fail as soon as the QR code is scanned?
For example returning straight to _Manage linked devices_ view with the error toast.

3.5.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
