### ISSUE TITLE
relocate toggle to show/hide password

### ISSUE THREAD

**Issue by scienmind** [signalapp/Signal-Android#4711]
The new pass-phrase visibility toggle introduced in [#3776](https://github.com/WhisperSystems/Signal-Android/pull/3776) is in very close proximity to the "unlock" arrow button. 
This way it is makes it too easy to accidentally "Show" your password by mistake, instead of submitting it. 
Especially on devices with smaller screen sizes, owned by people with big hands.

While not a big issue, it does introduce additional unnecessary usability friction for the "cautious user".

This can be effectively avoided by relocating the show/hide toggle to the left part of the input field.
(or at least by increasing the spacing between the toggle and the arrow button.)

**Comment by m0jo** [comment]
Where would you like the icon to be?

**Comment by scienmind** [comment]
I think this can be a good option:
![edit 2](https://cloud.githubusercontent.com/assets/11633330/11671102/900ab3fa-9e0e-11e5-83c9-ce314db01919.png)
It's nice and symmetric, and prevents accidental taps well.

also possible:
![edit 1](https://cloud.githubusercontent.com/assets/11633330/11671106/97c5cd5a-9e0e-11e5-9446-b7c50545a5e8.png)
However, the second one is not visually symmetric, and hence, I think less preferable.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
