### ISSUE TITLE
Quick capture preview with front camera doesn't match the actual taken picture

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4715]
https://gist.github.com/anonymous/deefe8b9d464c50f21cb
Whenever I try to take a picture directly in the latest Signal build, the picture preview of what the picture will look like doesn't match with the "result" of taking a picture at that given moment. The actual picture is higher up than the preview.

Using the back camera, I can't see any difference at all.

Basically, if I take a picture where my entire face is visible, the actual picture only shows my eyes. God am I bad at describing things...

Hopefully these pictures can explain it better.

![2015-11-25 21 07 26](https://cloud.githubusercontent.com/assets/12563436/11408488/bef5d53c-93b9-11e5-8fa3-d73ceac29a52.png)
![2015-11-25 21 07 33](https://cloud.githubusercontent.com/assets/12563436/11408491/c08e903c-93b9-11e5-9a0d-b76e1c83e1ef.png)

**Comment by moxie0** [comment]
...that's just the thumbnail, though, right? Like if you view the full photo it's correct?

**Comment by Dyras** [comment]
@moxie0 If I send the picture and click it, the picture is still cropped. It's cropped for the receiving person too.

A much better example: https://mega.nz/#!2AoTwQhB!Ok914XyR8jqI0v2T1NXOspCSZ3zXRIfbfix2bN3qJwg
My entire face was visible in that picture during the "preview" and the picture you see above is what the app gave me. You can barely see my face which is clearly a bug. You can see my hair though, so I guess that's something?

I thought the exact same thing as you the first time I sent a picture, but sadly the thumbnail is exactly what the picture ends up looking like.

**Comment by Dyras** [comment]
@mcginty Do you need any more info? I'm switching to a new phone soon because the mic in my Galaxy Nexus has stopped working, and I'll be reinstalling my Gnexus in the process.

**Comment by mcginty** [comment]
I think the weirdness is coming from the fact that the rotation is reported to be 270 instead of 90 (the normal value for portrait mode).
```
W/CameraView(21136): starting preview with size 1280x720
W/CameraView(21136): previewSize: 1280x720
W/CameraView(21136): data bytes: 1382400
W/CameraView(21136): previewFormat: 17
W/CameraView(21136): croppingRect: Rect(0, 381 - 720, 899)
W/CameraView(21136): rotation: 270
```

**Comment by Dyras** [comment]
@mcginty Ah right, do you need more logs or something to figure out what's causing it?

**Comment by mcginty** [comment]
@Dyras I don't think more logs are required, we'd just need to work out *how* this was happening, which means either reproducing it on this device or giving you builds with even more diagnostic info in them.

**Comment by Dyras** [comment]
@mcginty Uuuuuuuh what? I'm totally running stock. This problem only started happening since 3.4.0 or so.
Device  : samsung Galaxy Nexus (yakju)
Android : 4.3 (776638, JWR66Y)
What
https://developers.google.com/android/nexus/images
JWR66Y is listed as a stock rom. Where exactly does it say it's not stock?

**Comment by mcginty** [comment]
Oh that's really weird - my phone didn't update to that release. Well, let me push it to it and see if I can repro with 4.3 then.

**Comment by Dyras** [comment]
If you can't repro, feel free mailing me a debug build. I'll install it tomorrow and get back to you.

**Comment by mcginty** [comment]
hahaha, well I think I wasn't wrong about this being a ROM bug. I just updated to your ROM and can reproduce.

**Comment by mcginty** [comment]
Further research: Looks like the SurfaceView refuses to move for the front-facing camera, so our app misjudges what portion of the screen is visible to crop the picture correctly.

**Comment by steko** [comment]
I have a Jiayu G4S with a non-stock 4.4 ROM and I'm seeing the same.

**Comment by Dyras** [comment]
@steko If you post a log it would be easier for them

**Comment by steko** [comment]
https://gist.github.com/7f3f702e67a6138ce1f5

**Comment by 2-4601** [comment]
Reopening because still an issue on some devices.

**Comment by agrajaghh** [comment]
same for me on a Nexus4 with 5.1.1

**Comment by agrajaghh** [comment]
weird thing is that the screenshot you take is not diplaying what really is on the screen:

screenshot / (bad) photo of the device: (without moving the device ofc)
![screen_photo](https://cloud.githubusercontent.com/assets/5296073/12019656/611cfa98-ad73-11e5-8ee8-836ab4fedb9d.jpg)

draft:
![draft](https://cloud.githubusercontent.com/assets/5296073/12019657/6b419416-ad73-11e5-9a66-3083c0d3f18a.png)

sent picture:
![picture](https://cloud.githubusercontent.com/assets/5296073/12019662/7e896b34-ad73-11e5-9b42-7a736132b38d.png)

**Comment by billie80** [comment]
Looks like this happens for other devices too. I'll post the information from #4972 here as well.

When taking a picture with the front camera using direct capture in collapsed state the resulting image is different compared to the preview.
The preview shows the lower portion from a full screen capture, while the resulting image is from the middle portion of a full screen capture.

I will try to explain the issue with an image series.

The first one is an image of the phone with the camera preview. Note the detail marked with the red circle in the upper right corner.

![tmp_29552-ca024246-ac85-11e5-98fe-50abfaf9af49-2100758390](https://cloud.githubusercontent.com/assets/9938306/12043771/a2d01e8c-ae88-11e5-9bb9-62b21ca7890c.jpg)

The next one is the preview of the taken picture. Note the detail mentioned before is now in the lower left corner.

![tmp_29552-c5080ffe-ac86-11e5-8997-d03cb10290c6161829820](https://cloud.githubusercontent.com/assets/9938306/12043778/b0904ea2-ae88-11e5-99a5-11f7b753af7a.jpg)

I wanted to take a screenshot from the camera preview but strangely the screenshot shows the view like for the taken picture. This is why the first pictures a not screenshots. See the third picture.

![tmp_29552-db73deb2-ac86-11e5-9780-cfb9c32cc4f952159806](https://cloud.githubusercontent.com/assets/9938306/12043784/bd467586-ae88-11e5-9ed7-d60a4e87f8a3.png)

The last image is a full screen capture of the same scene. I suppose the region in the camera preview is different to the final region applied.

![tmp_29552-e8b3729a-ac86-11e5-934c-bf7e4787f0ea-1308311471](https://cloud.githubusercontent.com/assets/9938306/12043789/c9c71afe-ae88-11e5-818c-b6c7245f72f5.png)

This happens only with the front camera using direct capture in collapsed state. The back camera works as expected.

Device info: Samsung Galaxy S5 Mini, Stock Android 4.4.2, Signal 3.8.1

Debug log: https://gist.github.com/anonymous/b3bc25fd68eb6fc8bec2

**Comment by billie80** [comment]
@agrajaghh: I noticed the same. A screenshot of the preview is different to what is displayed on the screen.

**Comment by sysfu** [comment]
I'm having an issue which might be related, when the front facing camera is selected, the shutter button does not respond at all. Shutter button snaps pictures as expected with rear facing camera. Device is Samsung Galaxy S3 with Android 4.4.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
