### ISSUE TITLE
Tilting the phone during quick capture freezes the picture

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4716]
https://gist.github.com/anonymous/ad1ed270aee6a207d455
Here's how I do it
1. Enter a conv
2. Press the quick capture button
3. Tilt the phone to the left/right 90º
4. The picture is forever stuck like this
![2015-11-23 18 10 58](https://cloud.githubusercontent.com/assets/12563436/11408572/58664580-93ba-11e5-865c-97ff8e2750fb.png)
![2015-11-23 17 15 31](https://cloud.githubusercontent.com/assets/12563436/11408577/5c666af2-93ba-11e5-9cb5-c56c91582d9b.png)

Gonna try with my moms phone to see if the same thing happens for her.
Update: Doesn't happen on her Xperia S.

**Comment by Dyras** [comment]
I just saw this https://github.com/WhisperSystems/Signal-Android/pull/4635 and I think that's exactly what my problem is. I'll reopen this if it still happens with the next major version.

**Comment by Dyras** [comment]
This is still happening for me, even with 3.6.0. @mcginty you have the same phone as I, is this still happening for you on the abomination known as Galaxy Nexus?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
