### ISSUE TITLE
Notifications should be dark in the dark theme

### ISSUE THREAD

**Issue by vzsze** [signalapp/Signal-Android#4725]
Android5 supports background colour in notifications. Would it be possible, to have dark notifications in the dark theme? This would make them look so much better. 

![screenshot_2015-11-26-16-19-24](https://cloud.githubusercontent.com/assets/541560/11426121/049e1112-945a-11e5-921a-7618f5bb68cc.png)

**Comment by claenn** [comment]
Don't agree. I would leave those ui statusbar experience to the rom based theme engine, as in CM.

Regards

**Comment by kurtisnelson** [comment]
That would be against Android UI design guidelines, notifications should be allowed to be themed by the OS unless there is a good reason not to.

**Comment by rejhgadellaa** [comment]
Disagree. Colored notifications is only for media playback. Imagine all apps using their own color. It would become a total mess.

**Comment by opticron** [comment]
Maybe a separate switch for theming the notifications, then? OS theming of notifications is not always global and I know at least with Substratum, app-by-app is the preferred method.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
