### ISSUE TITLE
Limited message bubble size when with media 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4734]
This just doesn't look right
1st message without media 
2nd bubble  should be equally wide IMO 

(did  I complain on that before? Couldn't find such an issue) 
![screenshot_2015-11-27-11-17-01](https://cloud.githubusercontent.com/assets/5326916/11438956/9e72dbda-94f8-11e5-8dc0-9d1ade283498.png)

**Comment by Dyras** [comment]
I thought about this about a week ago. I'm with you, it just doesn't look right.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
