### ISSUE TITLE
Opening Signal the very moment a message is delivered screws with the notification

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4756]
I got a message the very moment I opened Signal. The notification only showed a number, and no actual name. Not sure if anything can be done about this, or if it even matters, but I'm pointing it out anyway since I'm willing to say 9/10 people don't know their friends's numbers by heart.

https://gist.github.com/anonymous/02f6441fac2349602f53

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
