### ISSUE TITLE
i hear myself during a call, my contact does not hear me

### ISSUE THREAD

**Issue by nizariOne** [signalapp/Signal-Android#4757]
In a voice call, i can hear myself (repeated with a delay) and what my contact is saying, but he cannot hear me. He can hear other contacts however.

Here's the log: https://gist.github.com/e6d88fd184629d7f5992

The speaker toggle trick does not work. Pls help :)

I'm running Android 4.1.2 on a ZTE Blade V

**Comment by eternaltyro** [comment]
This issue persists in 3.8.1: https://gist.github.com/anonymous/e31c228270dd22f8f5b6
It's been there since 3.6.x

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
