### ISSUE TITLE
Prompted to "Invite to Signal" a contact who already uses Signal

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-Android#4763]
This is somewhat similar to issue #4584 but without any loss of functionality. I can call/IM my friend just fine via Signal, but I got a random "Invite to Signal" popup for this friend today. Strange, as she has been using TextSecure for more than a year, and she hasn't changed her phone/number recently. 

She _did_ send me an SMS today because her broadband was down. Could this have confused the app into thinking this user is not on Signal?

**Comment by scienmind** [comment]
I can conform this. Just received a invite prompt for a long time signal user.

Notification arrived in the middle of Signal-encrypted messaging, without SMSs involved.
(The conversation does have SMSs in it, but from a long tome ago.)

Debug log: https://gist.github.com/f4555d2ca229c20b2c93

**Comment by dcherian** [comment]
Same here. Just happened on 3.6.1. Tapped notification for Signal message from contact. Was prompted to invite even though the latest message was an encrypted message.

Log here: https://gist.github.com/anonymous/74a5c97057b5e0c57a9b but I'm not sure if there's anything useful in it.

**Comment by moxie0** [comment]
When this happened, was the send button blue or gray?

**Comment by dcherian** [comment]
I replied with an encrypted message. Didn't have to change it, so the button must've been blue.

**Comment by scienmind** [comment]
Same in my case, the invite prompt appeared while exchanging encrypted (blue button) messages.

**Comment by i7u** [comment]
Same here (blue button), and I have the screenshot to prove it :-)

**Comment by McLoo** [comment]
Here for my long time signal contact. 
Just got it when opening from notification. 
Texted that contact (push) a hour ago 

https://gist.github.com/53c33ff20485ed56e924

**Comment by pdf** [comment]
Can we please just have a preference to turn the massive invite banner off entirely per #4471?  It's really nothing but an annoyance for users.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
