### ISSUE TITLE
Mass notification to "say hey" to already existent contacts after update to 3.6.1

### ISSUE THREAD

**Issue by mad-de** [signalapp/Signal-Android#4774]
Directly after Update to 3.6.1 I received a notification for every single one of my already existing Signal contacts "xxx is now on Signal, say hey". That made 30 notifications in total in less then a second.
Android 4.4 (Kitkat) CM11 Model: FP1 
Sorry, no debug log as phone crashed after (probably unrelated). If necessary I could probably provoke this behavior by downgrading to a self-compiled version and updating again.

**Comment by mad-de** [comment]
Nope - apart from the system crash, which only happened one time afterwards and probably wasn't linked to the apps behaviour, everything worked and works alright.

**Comment by wizardofid** [comment]
I had similar experiences on 3.5.0 and 3.5.2. Also FP1 but with original Android (4.2.2). 
System crash and restart --> All contacts lost their information about the Signal-registration. When a refresh happened all previously known contacts were announced with 'Say hey...'.
First time i triggered a refresh in the contacts list, second time i waited for the timed refresh. Made no difference (as expected). 
I just tried restarting the phone while Signal is open --> same effect.
Thought it was a very rare effect and therefore ignored it...
Maybe Fairphone's 'People'-App is the culprit?

**Comment by johanw666** [comment]
I don't think Fairphone software hasanything to do with it because I had the same on one of my devices, a Sony Xperia Z1 Compact running Android 4.4.4. When I upgraded to some 3.5 version and pressed the new message button, I saw no contacts. When I refreshed, I got a lot of contacts with this effect, all of which I had previously messaged with.

BTW, thi message can't be deleted from the thread, just as the voice call messages. At least not without manually deleting records in the database.

**Comment by mad-de** [comment]
Hi - i had no crash beforehand. The app mass notfied me directly after updating to 3.6.1

**Comment by wizardofid** [comment]
I tried several times to make it also happen on my old S3 with Android 4.4.4. No success - everything's running smoothly after a forced restart.

**Comment by unrepentantgeek** [comment]
I received a single notification of this type.  I then dismissed it only to have it come back for the same phone number a few hours later.  Rinse, repeat, etc.  Why does this useless and annoying notification even exist?  App uninstalled until it's removed entirely.

**Comment by i7u** [comment]
Just moved Signal to a new device with stock Android 5.1.1, maintaining my phone number. Moved over my phone contacts, then registered Signal on the new phone, moved over the Signal plaintext backup, then used Signal for 6-8 hours without a glitch. Noticed that for every conversation I would enter, I would get a "so-and-so is on Signal, say hey!", which is a reasonable thing to do.

8hrs later at approx 00:15 (is there a timer somewhere, or coincidence?) I got ~70  "so-and-so is on Signal, say hey!" notifications. Thankfully I can mark them all as "read" with one tap.

Debug log: https://gist.github.com/1361b85498e51f8f5f57

**Comment by mr-gosh** [comment]
i get this notification for my 120 signal contacts all 1 or 2 days. very anoying...
I am using cm13 nightly build - but i have not restricted any permissions from signal.

**Comment by McLoo** [comment]
Theory:
 the affected devices do a full sync of the contacts DB by deleting local and repulling completely from server. 
By deleting and recreating the Signal contacts we notify. 
Plausible? 
Maybe someone is willing to deactivate contact sync (not signal)  for some days...

**Comment by Teldix** [comment]
Hey community, i also got these mass messages. It happened twice today and I would guess more than three times the last week. My phone uses CM12.1 (Motorola moto G peregrine).
Please feel free to have a look into my log: https://gist.github.com/a16de9c3b31403da4eaf

**Comment by riyapenn** [comment]
Recurring for another CM user: https://gist.github.com/da0e140d965f42a4a6ea5c779daf3c17

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
