### ISSUE TITLE
Regression: Message disappears on "send" when media has been "shared" to Signal

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-Android#4791]
This behaviour is not reliably reproducible on my phone (Samsung GT-I9300, stock Android 4.3).

I've been using TextSecure/Signal with this phone way before the feature to attach pictures was introduced (many thanks by the way!) and never had this issue, I therefore feel it's reasonable to flag this as a regression. I have observed this buggy behaviour 3-4 times recently, after TextSecure was rebranded as Signal. I may have sent 50 pictures in recent weeks, so this gives you an idea of the occurrence of the failure. It's low but far from negligible.

Creating a media message with the following workflow sometimes results in the message disappearing before it's sent:

Gallery -> Share via -> Signal -> Share with... <contact> -> Image draft is shown as expected with red "X" on top right -> Add some text -> Hit Send.

Normal behaviour: The message disappears for less than a second, then re-appears with the upload progress indicator spinning/completing. The message is sent successfully, is received on the other end, I get the delivery receipt and the world is a better place.

Buggy behaviour: The message disappears, never to be seen again. Nothing is received on the other end. My uninformed guess is that something fails as the media message is packaged up in the encrypted blob to be transmitted to the server and the draft is just trashed, leaving some sort of invisible garbage behind.

When this bug occurs, repeating the workflow (Gallery -> Share via...) reliably repeats the bug. I have found that the easiest way to get out of this buggy loop is to use Signal's native "Attach -> Image" buttons to select the image from gallery. This makes everything work as expected.

I realize this is a difficult bug report to work with. Intermittent failure and no hard data to go on. Next time this happens I will capture the log, if there are any other tricks I can use to show you what happens (e.g. some sort of time-lapse-snapshot recording software that will show you a "video" of the phone's behaviour), please shout.

**Comment by 2-4601** [comment]
Maybe #4665?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
