### ISSUE TITLE
Signal Android not finding device contacts

### ISSUE THREAD

**Issue by thoraxe** [signalapp/Signal-Android#4803]
Signal 3.6.1
Samsung Galaxy S5 SM-G900T
Android 5.1.1
Baseband G900TUVS1FOJ4

I've noticed that a contact that is only in my device contacts is never found when I go to send a new text message.

The interesting thing is that I have an existing conversation with this individual that is properly identified with contact information, but trying to send a new text and typing their name they never come up in the list of contacts.

Is there something I'm missing on device contacts showing up in Signal's search list?

**Comment by 2-4601** [comment]
Is this contact a Signal user? Have you made Signal the default SMS app?
If I understood your issue correctly this sounds a bit like a support issue which are supposed to be handled by support@whispersystems.org
This issue tracker is mainly for bugs.

**Comment by thoraxe** [comment]
@2-4601 this seems like a bug to me.

I ask these questions honestly:

* why does it matter if the contact is a Signal user or not? When attempting to send a new text all contacts available to the OS should be searched/listed. It appears that device contacts (as opposed to contacts from Google, etc) are not searched.

* Signal is the default SMS app. Why would the default-ness of Signal as the SMS app affect which contacts within Android are searched when attempting to send a new message?

**Comment by 2-4601** [comment]
Is the contact saved in SIM? There have been some issues with that.

**Comment by thoraxe** [comment]
I'll have to check. I don't believe so as it contains other info besides data (eg: picture). Is there a quick way to see what's saved to SIM?

**Comment by scienmind** [comment]
I have the same issue on on of the devices (Samsung I-9305):

Signal is not used there as a default SMS client, just for signal messages. 
When composing a new message, a list of signal-registered contacts only is shown, but one contact is always missing. Same with the "add members" dialogs in groups.
The "missing" contact is a long time signal user, and i have an active conversation with him present. But he never appear in signal's in-app contact lists. He only can be added there by typing his number manually.

The "missing" contact is saved on the device (not SIM). I tried to delete him -> reboot -> sync Signal -> reboot -> add contact -> sync Signal. Unfortunately, no change.
The number formatted in a standard way, and is appearing just fine in Signal's lists on other devices.

Its tricky and weird, maybe related to this samsung's ROM (which they seem not to care updating anymore)...

**Comment by thoraxe** [comment]
So, I think I may have found the "problem" for me in particular.

This contact, while being listed as a "device contact" isn't actually on my device! I think that Facebook is doing something bizarre and showing the contact as being in my phone ("device"), but, when looking at contacts in Android and selecting "show device contacts" this individual does not appear.

So, I am happy to close this issue as I don't think it's explicitly Signal related -- I think it's the nature of these particular types of contacts and how Facebook represents them / makes them accessible to other apps.

**Comment by scienmind** [comment]
@thoraxe I doubt that the issue should be closed, as I stated above - I experience the same issue with a contact missing from Signal's internal lists. 
This contact originally was added manually to the standard device's phone book (and stored "on device"), no 3rd party involved in any way with the contact in question.

**Comment by peterpanondrugs** [comment]
Same here. Changed the numbers on a contact. But now signal doesn't recognize then anymore. Restart only showed the new names but still not listed as signal contacts. 1 is Android 1 is iOS

https://gist.github.com/e3d981f57c3bd0990c25

**Comment by Mikaela** [comment]
I am on Jolla Phone and am using it's Android Support and have Google Play Store & Services installed.

When I open Signal, I am shown that no one uses Signal, but I can send SMSes to everyone. When I opened discussion with my other number and tocuhed the "Refresh secret discussion" or whatever the button was, my other number became visible Signal user.

Both phones have the same contacts and only Samsung Galaxy S3 (GT-i9305) running Android 5.1.1 shows all contacts who are Signal users as Signal users.

**Comment by 2-4601** [comment]
@peterpanondrugs 
See https://github.com/WhisperSystems/Signal-Android/issues/4338#issuecomment-198157982 and the comments below that:
In short:
Go to **Android Settings > Accounts > Signal > Menu > Remove Account** (at this point Android might say: _"Removing this account will delete all of its messages, contacts, and other data from the phone"_, but that is not accurate, all your Signal messages will remain untouched) then open Signal, tap the blue pen to get to the contact list and refresh it by pulling down or via the menu

@Mikaela 
Unfortunately Sailfish OS (+Android Support layer) is not supported.

**Comment by Mikaela** [comment]
> Unfortunately Sailfish OS (+Android Support layer) is not supported.

Is there any specific reason for this or how does it differ from normal Android? And if this is the case, why Signal doesn't tell this to me when I install it?

From what I understood this issue is also happening to some people using native Android and I don't understand what prevents the conctacts from appearing until I refresh private conversation with them.

**Comment by 2-4601** [comment]
@Mikaela Only Android is supported. If Sailfish OS happens to work, that's a plus, but if it doesn't OWS doesn't have the resources to look into it. You said in your previous comment that it works on your Android 5.1.1 device but not on Jolla, so it sounds like a Sailfish problem.

**Comment by Mikaela** [comment]
@2-4601 Unless I am entirely misunderstanding, @thoraxe and @scienmind and @peterpanondrugs are experiencing this same issue on Android natively, and I think fixing it on Android would also fix it on Aliendalvik.

**Comment by Mikaela** [comment]
Interesting discovery: Signal Desktop shows all the contacts who use Signal even if the app doesn't on Jolla. Is it the same for people having this issue on Android?

**Comment by nsrosenqvist** [comment]
I can't find any phone contacts by searching, neither the conversation I've imported from the SMS app. I can send messages if I open an existing conversation but I can't start new ones without entering the phone number manually.

**Comment by cipri-tom** [comment]
This seems to be a problem with the android app. I have one contact for which I saved 2 numbers. One of them is definitely on Signal, since I securely chat with him from my iPhone. However, it doesn't appear to be in Signal in my android phone. Even when I manually write his number, Signal only offers to send an SMS, rather than an encrypted chat. 
I repeat, I'm chatting securely with the same number from my iPhone.

**Comment by DreamFlasher** [comment]
I can confirm this bug.

**Comment by riyapenn** [comment]
This is likely a result of how phone numbers are formatted on your phone. Aside from [feedback](https://github.com/WhisperSystems/Signal-Android/issues/4803#issuecomment-199345423) from earlier in the thread, contact support@whispersystems.org and provide information on what steps on the [support page](https://support.whispersystems.org/hc/en-us/articles/216595418) you've gone through.

**Comment by waseltzer** [comment]
Same bug for me. Only some of my Contacts show up in Signal.

**Comment by BlurryFlurry** [comment]
same problem

**Comment by Nutomic** [comment]
I have the same problem, running LineageOS 14.1 and using DAVdroid for contacts.

**Comment by ariddell** [comment]
Same issue. LineageOS 14.1 local contacts. Tried doing the account deletion/resync trick. No effect. What's very weird is that I can receive messages from the people who are not showing up in my contact list but I can't send messages to them (prompted to use SMS).

**Comment by nwios** [comment]
Same issue on iOS, it isn't listed on app but I have already checked on request that outing from iOS app but the response back with 0 elements, however the server side admin tells me the request is correct and never gets any exception about that.

Any help?

**Comment by michaelkirk** [comment]
@nwios 

I don't fully understand your report, but this is the Signal-Android issue tracker. If you are having an issue with the Signal-iOS client could you open an issue over at: https://github.com/WhisperSystems/Signal-iOS/issues/new

If you do open an issue there please record the actions you are taking, what you see, and what you expect to see.

**Comment by jetole** [comment]
I use signal as my primary SMS and have been and it works fine. I'm using a Galaxy S6. A friend of mine on a Galaxy S5 has just installed signal and I'm looking at his phone now. He doesn't use it as his primary SMS and it only shows signal contacts. He's on a Galaxy S5 neo. My name was not on his contract list. After I sent him a message my name appeared on his contact list but he says it will be gone tomorrow. He has a short message history and we use disappearing messages. I don't know if that's related but I'm just giving full disclosure in case it is. My name keeps disappearing from his signal list.

**Comment by D-Nice** [comment]
For Lineage OS, if you have privacy guard active, disable it for Signal, and then pull/refresh contact list after clicking the pen icon in Signal.

**Comment by cipri-tom** [comment]
@D-Nice what is privacy guard ? I can't find it

**Comment by D-Nice** [comment]
@cipri-tom Here's an older article about it, assuming you're using one of the CM/Lineage custom ROMs https://www.guidingtech.com/42045/cyanogenmod-privacy-guard/

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
