### ISSUE TITLE
Crash after QR scan to verify identity

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#4810]
1. Phone A: Tap  'verify identity' through the contact header 
2. Phone A: Choose 'Scan their key to compare' 
3. Phone B: Tap 'verify identity' and Choose 'Get your key scanned' 
4. Place Phone A over Phone B to scan code 
5. App looks like it scans it but it when it goes to load signal again the app crashes.

https://gist.github.com/074447ecc61bd1bcf3f6

Device  : LGE Nexus 5X (bullhead)
Android : 6.0 (2343525, MDB08L)
App     : Signal 3.6.1

**Comment by jeremymasters** [comment]
Should this be on 3.7.1 instead?

**Comment by moxie0** [comment]
hmm, can't reproduce this

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
