### ISSUE TITLE
Sudden switch to one-way unencrypted conversation

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#4812]
Suddenly, I was unable to send encrypted messages to a specific contact. Though, messages I received were encrypted. Additionally, the contact was no longer listed as Signal user. Since another friend of mine had exactly the same issue with this contact, I presume the problem being not at my side. It was not possible for the contact to de- and re-register in the app - nothing happend. The only way out of this mess was to deregister via the web form.

Logs from the suspicious contact:
https://gist.github.com/anonymous/eb2b9b80212e04b168da
https://gist.github.com/anonymous/f2e25dbcc5ca704e55e8
My log:
https://gist.github.com/9757360f322d618461fd

**Comment by varanasib** [comment]
I can confirm this.  It happens when the contact uninstalls signal on the cellphone.  Suddenly, without warning, messages sent to the user, even in response to messages sent in signal, are received by that user unencrypted.  This is a huge problem.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
