### ISSUE TITLE
Proximity sensor disabled in horizontal orientation during signal calls

### ISSUE THREAD

**Issue by scienmind** [signalapp/Signal-Android#4813]
During signal call, if the phone is placed horizontally on it's back (i.e. flat on the desk with screen facing up), then the proximity sensor will not turn off the screen.

If the screen was already off before reaching this position, it'll remain off, and will be turned on while sensor clears, but if covered again, screen will not turn off.

This causes accidental clicks if you call while laying on the couch for example.
Original android dialer listens to the proximity sensor in all orientations, and I think this is the correct behavior to implement.

Tested with several devices, Signal 3.6.1.

This may be one of the reasons for: #4434 ,if you prefer, I can close this and add this info there.
(also may be relevant: #4519 and it's PR: #4522)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
