### ISSUE TITLE
Incorrect emoji displayed when typing in landscape

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#4816]
Nexus 5X, Android 6.0
"Use system emoji" unchecked

When composing a message, if the orientation is landscape and the software keyboard is on screen, the system emoji are displayed in the input text field.

**Comment by McLoo** [comment]
@justin- that's because you see the keyboards(?) input field, that's used for landscape orientation (to prevent all kinds of orientation quirks) 

WhatsApp is acting the same way. 
Telegram *seems* able to handle the quirks as they use their text field in landscape too😰

**Comment by FeuRenard** [comment]
This issue seems related to #3620 . According to this, your suggestion is right: you see the keyboard's input field and not the one of Signal. And this seems to be intended.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
