### ISSUE TITLE
Home screen icon shows unread messages in error

### ISSUE THREAD

**Issue by parris** [signalapp/Signal-Android#4818]
My Signal app icon indicates I have 7 unread messages currently. When I go into the app I can't find them. I've also tried to mark all of them as read, but the indicator still doesn't disappear.

**Comment by McLoo** [comment]
Did you just import the messages from the stock app?

**Comment by parris** [comment]
I imported from hangouts which previously imported from the stock app.

**Comment by McLoo** [comment]
Then I guess you hit #3842 and the unreads keep hanging out
Someone should create a fix for that :)

**Comment by parris** [comment]
Oh interesting. I'm using the aviate launcher too. Ha

**Comment by andoks** [comment]
I have the same bug, using Nova launcher prime. I'm unsure if I imported from hangouts though.

Is there any known work-arounds? Preferably not including deleting all the imported messages

**Comment by mreppen** [comment]
Affects me too. I did not import from Hangouts since it was installed on a fresh phone.

**Comment by McLoo** [comment]
@mreppen what device are you using? Maybe you could push a debug log after receiving a message?

**Comment by mreppen** [comment]
@McLoo 
A Oneplus 2 with Nova/TeslaUnread.

The unread badge should make sure I remember to do it. To late to receive anything now.

Do I submit it before or after reading the message?

**Comment by mreppen** [comment]
So I happened to get one anyway. Bug report from after reading: https://gist.github.com/anonymous/5f39458252cd56d9ae20

**Comment by mreppen** [comment]
Did some testing:

When I have 0 unread messages, it shows 1.
When 1, shows 1.
When more unread all correct.

**Comment by EarMaster** [comment]
I have the same issue on a OnePlus One with Nova Launcher / Tesla Unread. Mark as read, doesn't work for me. As a workaround you can disable Signal in the TeslaUnread settings. This doesn't show the correct number, but it doesn't show a wrong number either.

**Comment by parris** [comment]
Workaround: Go into your original messages app and mark all of the messages
as read manually. Notice the signal app counter decreases as you read
messages from your old app.

You can't mark messages read that don't exist in Signal. Does Signal use a
global unread count from the phone or something? Does anyone have an idea
about the appropriate way to resolve this? Should Signal only care about
the messages in Signal?

**Comment by EarMaster** [comment]
The latest update of Signal (I think) seems to have solved this issue for me. I'm no longer getting the false Unread notification

**Comment by andoks** [comment]
Same here, the unread label now works as expected. (Nexus 6)

**Comment by riyapenn** [comment]
Is this still an issue? 
If yes, does archiving all messages (swipe right on each conversation thread) help? 
(visual for archiving available at: http://support.whispersystems.org/hc/en-us/articles/214582088-How-can-I-archive-chats-or-conversations-)

**Comment by cyberpyrate** [comment]
Solved mine indirectly thanks to parris' suggestion to go into the stock ap. I found the verification message from Signal's install unread in the stock ap's repository. When Signal sees it it deletes it from the repository automatically, but it wasn't deleted from the stock ap, thus showing I had a message unread when I couldn't find one. Thanks for the tip parris!

**Comment by eprodgers22** [comment]
Not sure if this is the case with others. The app icon for Signal can now be long pressed (Galaxy S7) and "clear badge" option is available. I just was able to clear the 1 from showing on the app. I will post again if the issue comes back and I have to clear the badge again.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
