### ISSUE TITLE
Can't send MMS on Project Fi

### ISSUE THREAD

**Issue by mpcsh** [signalapp/Signal-Android#4820]
Hey! I just switched from T-Mobile to Project Fi on my Neuxs 5X. I can send SMS just fine, but MMS won't go through - neither picture messages nor group chats with non-Signal users. I've tried both WiFi Calling Compatibility Mode on and off to no avail. Debug log [here](https://gist.github.com/anonymous/0be310f4d4c97bc14f47).

**Comment by 2-4601** [comment]
#3644

**Comment by ThurnisH41ey** [comment]
#3644 was resolved by using Fi Spy to switch to T-Mobile. Mine doesn't work on either.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
