### ISSUE TITLE
Manual read receipts

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#4821]
I am aware of your view on (automatic) read receipts from #2667. That's what e.g. WhatsApp does with its blue checkmarks.
However I would like to use "manual read receipts" in the manner Threema has implemented them (they call it "acknowledge"):
1) Long-press a received message
2) Select "acknowledge message" (I guess so, I use the german translation)
3) Then the "received" (or "seen") indicator is replaced by an indicator for acknowledgement of the message

I choose this to say that I read something over writing "Ok." because it doesn't annoy my conversation partner. Most of the time it's sufficient that the partner gets this information the next time he opens Signal and not immediately.

**Comment by AlexanderKayumov** [comment]
I believe read receipts (as done e.g. in WhatsApp) are a great feature that a lot of users find they need.

Of course, it should be an opt-in feature, otherwise it wouldn't be consistent with the privacy philosophy of Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
