### ISSUE TITLE
Feature Request: Sync messages between devices

### ISSUE THREAD

**Issue by MaralAfris** [signalapp/Signal-Android#4830]
Hi,

It would be great that the mobile and desktop version contain the same messages, so that we can seemlessly go from one to another, for example that when we add a desktop client, it would ask to sync messages available on the mobile version.
Also when both are connected at the same time that they could share a kind of "message status" so that they could keep in sync.

**Comment by Dyras** [comment]
This is what I was expecting and I was surprised to see this feature missing.

**Comment by RiseT** [comment]
I guess it's pretty difficult to implement full synching in a privacy focused app. For the kind of synching you're thinking of, it would be necessary to permanently store all messages, media, etc. on Signal's server, which is a privacy risk.

The only way I could imagine doing this without storing the data on the server is a direct device-to-device sync when two or more linked devices are online simultaneously.

Dropbox has a feature called 'LAN Sync' which does exactly that, although the underlying motive there is transmission speed and not privacy:
https://www.dropbox.com/help/137
https://blogs.dropbox.com/tech/2015/10/inside-lan-sync/

**Comment by mawed** [comment]
If this is implemented it should be optional and with possibility to abort as it could be really intense for the (mobile) network

**Comment by MaralAfris** [comment]
Couldn't we actuallty require both devices to be connected at the same time and that they simply share a checksum of the messages stored on each devices.
If one of the see that the checksum differs then they can ask the user to use a sync mode where they share the message history ?

This way you can have control of it and use P2P sharing which would reduce the privacy problem :D

**Comment by Dyras** [comment]
I definitely think directly sending the message from one device to the other is the way to go. Since every message sent/received after linking the device is delivered to both devices I don't see this as a big issue. I would very much prefer if they put their gunpowder into use for something else. I wish we had more themes, for example.

**Comment by lorenzhs** [comment]
At the risk of being slightly off topic, I think core functionality like working synchronization should be a much higher priority than adding more themes.

Also I must confess that I'm not quite sure what your intent is in this issue. Sync of new messages (i.e. from the time you link the devices) is supposed to work. If it doesn't, that's a bug (like mine in #4859). Or are you referring to syncing *old* messages, i.e. those sent and received *before* the Desktop client was linked? Then you should say so clearly.

If that is indeed what you mean, then this issue will probably go away within a couple of weeks as your history is populated with more recent chats. How often do you really go back to older chats?

**Comment by Dyras** [comment]
Sorry for being unclear, I've had a crap day today. I mean old messages, not new messages after linking the desktop client.

**Comment by lorenzhs** [comment]
Ah, good. Then let me attempt to rephrase the issue statement, maybe @MaralAfris can adopt it for the first post:

it would be great if Signal could sync the entire message history to a new device being linked. It's a bit unclear what would be the best way to facilitate this, but probably opening websockets to the server and having the server pass through the data without ever storing it would be most reliable.

**Comment by RiseT** [comment]
Now I'm the one being confused. If this is only for old messages prior to linking, I wonder how the syncing of new messages after linking technically works.

Let's say I've got Signal on my mobile phone, which is online all the time, and I've got some notebook with an **already linked** Signal Desktop. Let's further say that I don't switch that notebook on for a couple of months. One day, I switch that notebook on and start the already installed & linked Signal Desktop. So where does Signal Desktop get all of those messages from that arrived on my phone in the time period between linking (couple of months ago) and the current day? From the server?

**Comment by lorenzhs** [comment]
I don't know how this is implemented cryptographically, but yes, the messages are stored fully encrypted on the server and downloaded once you connect. This is the same as what happened previously if you switched off your phone for a month -- the messages would still arrive, and they'd still be secure. Since this isn't really related to the issue at hand, I don't think this is the right place to discuss this really.

**Comment by heyimgay** [comment]
From the phone if it's still in your history.

A new message type saying "this is the checksum of the last message I received" and is timestamped so we know which messages to send.

**Comment by RiseT** [comment]
@lorenzhs Thanks, but I'd say it's crucial to understand this for discussing the topic/issue at hand.

**Comment by scienmind** [comment]
Syncronization may be done after linking the devices using the regular method, which is just using Signal Messages.
(As Moxie mentioned, all communication between the linked devices is done by Signal messages.)

The issue with backlog syncing is the size of course. But backlog syncing can be done at least for the textual contents (as done in plain-text backups). It would be better than nothing, and in such case size should not be a problem. 
Judging from this PR a while ago: https://github.com/WhisperSystems/Signal-Android/pull/4019, signal should handle 100MB message just fine.


(Off topic: @RiseT, as far as file syncing tools go, you should have a look at this free, opensource project: https://syncthing.net/. Great tool, no storage on 3rd party servers)

**Comment by madLyfe** [comment]
i think this would be awesome as well. the messages shouldnt need to be stored on signals servers.

**Comment by lorenzhs** [comment]
There is a matching Signal-Desktop issue, https://github.com/WhisperSystems/Signal-Desktop/issues/444 - not sure if I should close that one?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
