### ISSUE TITLE
Request: Allow QR code to link devices to be scanned from front-facing camera

### ISSUE THREAD

**Issue by bacirella** [signalapp/Signal-Android#4839]
Back-facing camera can't focus, but the front camera works fine.

**Comment by srivs** [comment]
Same problem for me. Will appreciate an update.

**Comment by agrajaghh** [comment]
@bacirella @srivs are your back-facing cameras broken? or is it a signal specific issue?

**Comment by srivs** [comment]
Not a Signal issue. It's a broken back-camera in my case.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
