### ISSUE TITLE
Message shown in Notification while only name selected in options

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#4841]
Received messages get displayed in the notification bar when receiving.
When swiping down the notification bar only the "New message" info is displayed.

As I just linked a chrome app before noticing this, this could be connected (or since the update to 3.7.1 yesterday)

**Edit:**
not reproducable right now

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
