### ISSUE TITLE
Self-sent messages get synced from Desktop to Android but not the other way

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#4844]
Using the Signal App it is possible to send messages to the phone, but messages from the phone do not get sent, as they appear in-app as received directly.

**Comment by 2-4601** [comment]
Also with groups.
- on Android create a group with your cat
- your cat leaves the group
- on Android send a message to the group (you are the only member)
- Desktop does not receive the message

**Comment by mawed** [comment]
Group behaviour also described in #3090

**Comment by moxie0** [comment]
whoops

**Comment by gulp21** [comment]
I only did a quick test, but removing the ``!forceSms && isSelfSend`` case in ``sendMediaMessage`` and ``sendTextMessage`` seems to fix this issue (ie. messages I send from Android to myself appear in the Desktop app). I’m not sure, though, whether it has some bad implications which I don’t see.

[Possible use cases for this feature: forward messages which contain important information to myself to make them easier to find; send notes to myself such that they are available on all synced devices]

**Comment by simplestuf** [comment]
PS: As I don't have a smartphone, my wife and I were hoping to use this 'feature' to communicate with each other using her phone and my desktop.

**Comment by Trolldemorted** [comment]
@simplestuf you can use [signal-cli](https://github.com/AsamK/signal-cli) as your root device and link signal-desktop instances to it. I did the same since i do not own a smartphone too.

But this issue looks easily solved, maybe @gulp21 can create a pull request?

**Comment by simplestuf** [comment]
@Trolldemorted Thanks: signal-cli seems to be working for us.

**Comment by Trolldemorted** [comment]
I created PR #5816 after having tested @gulp21's proposal for several days.

It would be great to get this fixed at last.

**Comment by FeuRenard** [comment]
Related #4147

**Comment by 2-4601** [comment]
>Related #4147

I believe the view regarding self-sending in #4147 has changed, see https://github.com/WhisperSystems/Signal-Android/issues/3090#issuecomment-163483522

**Comment by MavrikD** [comment]
Is the reverse feature being worked on? (mobile to desktop)

**Comment by Trolldemorted** [comment]
I am currently not actively working on it, but these two PRs are awaiting review:

https://github.com/WhisperSystems/Signal-Android/pull/6209
https://github.com/WhisperSystems/Signal-Desktop/pull/959

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
