### ISSUE TITLE
Signal is randomly dropping incoming sms

### ISSUE THREAD

**Issue by jarlelin** [signalapp/Signal-Android#4851]
Whenever I have Signal as the active SMS app it randomly drops about half of the sms I receive. It might be related to only one contact as I dont use sms that much with others.

If I set the default sms app "messages" as the primary, then I receive all sms as I expect.
If I set Signal as the default sms app then I randomly receive only about half of the messages received.

The only other sms enabled app I have installed is hangout and it is set to "sms disabled".

Phone: Samsung s6 edge. Android 5.1.1. Signal version 3.6.1.

**Comment by davepwsmith** [comment]
I have also had problems with receiving SMS messages recently, although I can't really tell how many messages I haven't received!

**Comment by davepwsmith** [comment]
Other users with similar problems: #4784

**Comment by moxie0** [comment]
If it's reproducible, please post a debug log from immediately after a "dropped" sms.

**Comment by davepwsmith** [comment]
What kind of debug log are you after? Just a plain `adb logcat`, or something more specific?

Obviously I will have to wait until I can get hold of somebody else's phone to test this, so it might not be in the immediate future.

**Comment by moxie0** [comment]
Sure, logcat is great, or you can do Signal Settings -> Advanced -> Debug log.

**Comment by davepwsmith** [comment]
https://gist.github.com/anonymous/a608afa6a8a540379814

**Comment by moxie0** [comment]
@davepwsmith Are you capable of building and running your own APK? I think we'd need to add more debug logging.

**Comment by davepwsmith** [comment]
That depends on what I need. I use a mac and have the basics installed. Capable of running `git clone && ./configure && make && make install`, then sure. If I'd have to download shedloads of android SDKs and libraries and configure all kinds of nonsense then I suppose I could but it would be a real pain. I'm more than happy to install a debugging-enabled apk if you will provide it for me.

**Comment by davepwsmith** [comment]
Just had a look at the building instructions. I'll attempt to do this tonight, let me know what the flags are for enabling debugging.

**Comment by moxie0** [comment]
No flags, just let me know when you get your environment setup and I'll push a branch for you to try

**Comment by davepwsmith** [comment]
OK great, it'll be around 19.00 GMT!

On 10 December 2015 14:32:55 GMT+00:00, Moxie Marlinspike <notifications@github.com> wrote:
>No flags, just let me know when you get your environment setup and I'll
>push a branch for you to try
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/4851#issuecomment-163636619

-- 
Sent from my phone. 
Please excuse my brevity.

**Comment by davepwsmith** [comment]
Another debug log just in case. 
https://gist.github.com/anonymous/1c38840e5b4daf107468

Just downloading the SDK now, but the internet is kinda slow here! I should be set up within the next half-hour

**Comment by moxie0** [comment]
You can run the moxie/sms_logging branch whenever you're ready, thanks!

**Comment by davepwsmith** [comment]
OK, I should be able to get working this weekend. Do you need me to specifically test whether a message is dropped and then collect logs, or can I just use it for a few days and collect logs. (i.e. do you know what you're looking for)

**Comment by moxie0** [comment]
specific test please, i don't know what i'm looking for

**Comment by jarlelin** [comment]
Dropped an sms 30 minutes before this log. 
Should have gotten 2x sms but only got the second one. 

https://gist.github.com/c2d3bb164a78b9e316b1

**Comment by moxie0** [comment]
@davepwsmith The 3.8.0 release is blocking on this, let me know if you won't have time to do this so I can release without it.  Thanks!

**Comment by davepwsmith** [comment]
I'm looking into this today.

**Comment by davepwsmith** [comment]
Won't build I'm afraid:
````
Note: Recompile with -Xlint:unchecked for details.
14 warnings
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease SKIPPED
:proguardRelease
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [httpclient-android-4.3.5.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [jackson-databind-2.5.0.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/NOTICE] (Duplicate zip entry [jackson-databind-2.5.0.jar:META-INF/NOTICE])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [jackson-core-2.5.0.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/NOTICE] (Duplicate zip entry [jackson-core-2.5.0.jar:META-INF/NOTICE])
:dexRelease
:packageRelease
:assembleRelease
:assemble
:compileLint
:lint SKIPPED
:preCompileDebugUnitTestJava
:preDebugUnitTestBuild UP-TO-DATE
:prepareDebugUnitTestDependencies
:processDebugUnitTestJavaRes UP-TO-DATE
:compileDebugUnitTestJava
/Users/davidsmith/signal-android/Signal-Android/test/unitTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java:11: error: cannot find symbol
public class PhoneNumberFormatterTest extends TextSecureTestCase {
                                              ^
  symbol: class TextSecureTestCase
1 error
:compileDebugUnitTestJava FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugUnitTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 45.584 secs
````

**Comment by davepwsmith** [comment]
I'm sure you've already looked at these, but since this bug was introduced with recent updates, I presume it has something to do with these commits:

https://github.com/WhisperSystems/Signal-Android/commit/b41364c709dc1c076a7057179eb4e5654a63fa6a
https://github.com/WhisperSystems/Signal-Android/commit/e5cd3e4fd10622f5bcde5d177d629dfa242f6aec

**Comment by davepwsmith** [comment]
Signal-Android/test/unitTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java

is missing 

`import org.thoughtcrime.securesms.TextSecureTestCase;`

**Comment by davepwsmith** [comment]
Anyway, I'm out for a few hours now (to go and look at awesome LEGO sculptures, which unfortunately trumps debugging code which I don't understand). I'll be back home later, and will continue, it's up to you what you want to do with the release, it's your app!

**Comment by moxie0** [comment]
You don't need the tests, just delete them if they're not compiling for you.

**Comment by davepwsmith** [comment]
https://github.com/WhisperSystems/Signal-Android/pull/4873

**Comment by moxie0** [comment]
Or build straight from Android Studio, should be fine.

**Comment by davepwsmith** [comment]
Gists from 'Signal-Android-debug.apk' built in android studio after two consecutive dropped text messages:
1: https://gist.github.com/anonymous/ddd735cfda77c22b8604
2: https://gist.github.com/anonymous/d6afa8cc75bb125bff22

**Comment by moxie0** [comment]
Thanks! It looks like it's not even making it out of the SMSListener.  I pushed a commit to the branch with some more logging there, could you run that and see what we get?  Thanks again.

**Comment by davepwsmith** [comment]
Hi, I've not been able to replicate this with that update to the branch. I'm aware that there's no reason for that and it makes no sense! I'll keep the debugging branch installed, and if I think that I have a dropped text I'll send you a log, but this is so intermittent that it might be a long job.

**Comment by moxie0** [comment]
@davepwsmith Very strange.  If you jump one commit back does it reproduce again?

**Comment by davepwsmith** [comment]
I'm afraid I'm back in a place with very slow internet now, and in all honesty, the enormous inconvenience which is caused by having to do multiple un/reinstalls when there is no way to back up my keys (inconvenience, I should add, not only to me but to everyone that I exchange messages with!) means that I'm hesitant to get further embroiled in this. The problem seems to have gone away, although there is clearly no reason for it to have done so. I'll continue to collect bug reports if and when messages seem to be dropped. Sorry I can't be of further help!

**Comment by moxie0** [comment]
hmm switching between versions you build shouldn't require you to reinstall.  That's fine, but I can't fix what I can't diagnose, so I'll just leave this open until someone who can reproduce this bug wants to run some debug builds.  Thanks for your help!

**Comment by davepwsmith** [comment]
OK, I will have a little more time around Christmas when work has calmed down. I will endeavour to look into this some more then. If, as you say, "it's not even making it out of the SMSListener", does that imply a problem with the Android messaging back-end rather than Signal itself? Some problem with play store services? Let me know if you have any inspiration over the next few weeks, and I'll keep running the debugging version and see what turns up.

Many thanks for your attention and help, keep up the good work!

D

**Comment by craigem** [comment]
I''m +1 on this report. Across multiple handsets, models, manufacturers and versions of Signal. It's happening a lot but it's not easily reproducible, as it usually isn't every message, only some, or most etc.

I've been experiencing this for over a year.

**Comment by mantono** [comment]
I have this problem to (3.16.1), but I cannot tell for sure whether the problem actually is caused by Signal or the other persons handset/software. It's not reproducible anyway, so it usually takes quite a while before you realise a message has been dropped/missing, hence any debug log is of very little help after an hour or so (I guess?).

**Comment by asmith999** [comment]
3.18.3 and I have this problem too. One contact I cannot send to at all, another I am not recieving on and off. Been going on for ~half a year now? I like my privacy but going for other options for the time being.

**Comment by jeremymasters** [comment]
This was on milestone 3.8.0...maybe it just needs to be moved so it gets noticed again. @moxie mentioned if someone was willing to run debug builds he'd be better able to ascertain what's going on.  For the record, version 3.19.1 is out as well now but I'm not sure that addresses your issue.

**Comment by TimmyCarbone** [comment]
+1. Happening to me too. Cannot receive sms from certain contacts. I'm on 3.21.3

**Comment by GitHorst** [comment]
maybe for some of you [this](https://github.com/WhisperSystems/Signal-Android/issues/5253#issuecomment-272040752) is helpful? (from a similar report)

**Comment by kylebarbour** [comment]
+1, also having occasionally dropped SMSes. Seems random - it's not happening with every contact or in every message. Also happens with group messages. The only way I know I didn't get the messages is that people call me later asking why I didn't respond. Doesn't ever happen with Signal messages, just SMS. [Here's the debug log](https://gist.github.com/anonymous/3db5bc46e2025e67e317f28df953e4b3).

My Signal version is 3.28.4, I'm on Android 6.0.1 on a Motorola Droid Turbo 2. I don't believe that I have any other SMS app that could be capturing the SMSes; I never actually even set up the native Messaging app.

**Comment by jarlelin** [comment]
I tried to reinstall Signal and can verify I still randomly drop messages
with no clue as to why. Only ever had it happen with one contact, but
that's because I mostly only use SMS with that one contact.

**Comment by moxie0** [comment]
To look into this I'll need someone who can pretty reliably reproduce this behavior to run a debug build that I give them with additional logging.

**Comment by rebeccaroisin** [comment]
One possible way to reliably reproduce might be to request SMS authentication codes (gmail login from an private browsing window for example) -- if I'm using Signal as the default SMS messenger, I often have to request 2 as the first one doesn't arrive.

**Comment by kordek** [comment]
@moxie0 I've experienced this issue several times, recently Signal has been dropping all of my SMS. If you can give me the mentioned build I could spend some time reproducing this bug.

**Comment by RobertLHarris** [comment]
I'm in a group conversation with my wife and 2 friends.  One of the friends ( not using signal ) sends 5 messages.  I got #1,2 and 5.  My wife ( not using signal ) got all 5.

**Comment by balajiramanathan** [comment]
I am also having this issue.  Person sends me a message, I don't receive it.  I call them and tell them I didn't receive the message (I was expecting a shopping list from my significant other).  The other person then copied the message text, pasted it into a new SMS and hit send, and I received the second message.  Now, they have 2 sent messages, but I have only one received message, not sure what happened to the first message.  This has happened twice so far - and every time, the second identical message is delivered, but the first one is never delivered.

**Comment by jeremymasters** [comment]
@balajiramanathan if you could include a log file, that could help the development team figure this out more easily.

**Comment by balajiramanathan** [comment]
I re-enabled signal as my default sms app and asked my wife to send me a message.  After half an hour, I still hadn't received it.  This is the debug log from before I got that message:
https://gist.github.com/f475ea5e2ba1bfbfee7f602d61dc23f3

Then, she resent the message (identical text, copied and pasted from the previous unreceived messaged to a new one), and I received it immediately. Here is the debug log from after I got the message:
https://gist.github.com/92f84af18d26765e3700c891c979be35

The actual message text was longer than 140 characters.  Not sure if that has any relevance or significance to the issue.

**Comment by gladstonedigital** [comment]
I had this problem probably 4 or 5 times yesterday. I'm going to quit using signal, it's messing up my friendships since my friends think I'm ignoring them

**Comment by moxie0** [comment]
@gladstonedigital If it's reproducible, please submit a debug log after you miss a message so that we can have the information we need to fix it. Alternately, you can use Signal only for Signal communication and use another app for SMS.

**Comment by gladstonedigital** [comment]
None of my other SMS apps are receiving SMS either. I can send and receive
MMS, i can even send SMS, but i can't receive any SMS at all anymore. The
last few weeks I've been receiving them intermittently but now i don't
receive any at all. I switched to using the app "Pulse" but that's not
working either

**Comment by moxie0** [comment]
@gladstonedigital Hmm, if no SMS apps are working on your phone for any incoming SMS, it's unlikely that it's a problem with Signal. But could you capture a log immediately after a "missed" SMS just the same?

**Comment by gladstonedigital** [comment]
Sure, I'll let you know if i get a chance to. It's hard tho since I'm
trying so many different troubleshooting ideas but if I'm able to i will

**Comment by sethcim** [comment]
Signal started silently dropping about 2/3 of unencrypted sms about 2 months ago. Several damaged friendships and lost job opportunities later... The messages have been delivered and stored in my phone (other messaging apps can see them) but signal never registered their arrival.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
