### ISSUE TITLE
Don't sync close session messages?

### ISSUE THREAD

**Issue by liliakai** [signalapp/Signal-Android#4868]
Currently, Android syncs close session messages to Desktop, but sessions are a device-level thing, so maybe they shouldn't be synced?

Alternatively, keep syncing them (if only for the sake of consistent message history across multiple devices), but also display synced close session messages correctly. Currently, instead of _Secure session reset_, outgoing close session messages received via SyncMessages display the message body ("TERMINATE").

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
