### ISSUE TITLE
[UX] Enable direct camera capture for changing group image

### ISSUE THREAD

**Issue by jnachtigall** [signalapp/Signal-Android#4880]
To change a group's image I have to use an an already taken image. Would be nice if the camera could be used directly. 

Maybe related to https://github.com/WhisperSystems/Signal-Android/issues/520 where direct image capture was implemented for messages itself. This should be extented to group images.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
