### ISSUE TITLE
PhoneNumberFormatterTest  build failed

### ISSUE THREAD

**Issue by praveenkathari** [signalapp/Signal-Android#4881]
/test/unitTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java:11: error: cannot find symbol
public class PhoneNumberFormatterTest extends TextSecureTestCase

Build failed

**Comment by davepwsmith** [comment]
I'm pretty sure that PhoneNumberFormatterTest.java is just missing

`import org.thoughtcrime.securesms.TextSecureTestCase;`

**Comment by McLoo** [comment]
Uh. Mea culpa! 

Slipped in with #4603 
Ran the test a couple of months ago the last time 
Should be enough to remove `extends TextSecureTestCase` to have the sme behavior before.

**Comment by praveenkathari** [comment]
Thanks ,

i was unable to set the config file : error

Failed to parse configuration at: twilio; Can not instantiate value of 
type [simple type, class 
org.whispersystems.textsecuregcm.configuration.TwilioConfiguration] from 
String value ('accountId:ACe84380546xxxxxxxx 
accountToken:db38ee0e0fxxxxxxxxx number:18885xxxxx 
localDomain:192.xx.xx.xx'); no single-String constructor/factory method

On 12/14/15 11:53 PM, David Smith wrote:
>
> I'm pretty sure that PhoneNumberFormatterTest.java is just missing
>
> |import org.thoughtcrime.securesms.TextSecureTestCase;|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WhisperSystems/Signal-Android/issues/4881#issuecomment-164517003>.
>

-- 
Regards,
Praveen Kathari
ct: +91 9866781816
www.intoweb.in

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
