### ISSUE TITLE
Check while Installation for old Backups

### ISSUE THREAD

**Issue by Alexandero89** [signalapp/Signal-Android#4892]
Ok my old Issue https://github.com/WhisperSystems/Signal-Android/issues/4883 was closed, so i would suggest to add a feature to prevent the problems i had in the future.

1)While installation Signal could check if there is allready a org.thoughtcrime.securesms directory available and take this one instead of deleting/creating a new/empty one.
2)Or maybe the other way around: Add an Import-Function not only for encrypted Backups taken before but also of a given directory to take what it needs to replace the database and keys

I hope that is no big deal to implement, because it could prevent dataloss in future in different situations.

thx

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
