### ISSUE TITLE
Time information too fuzzy

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#4895]
I got an image at 22:59, now it is 0:48. When I tab on the photo I can read "1 hour ago" which might be too fuzzy...

**Comment by heyimgay** [comment]
How fine grained do you suggest it be?

**Comment by sedrubal** [comment]
mh, I don't know :D I'd say `1 and a halve hour` or even `2 hours`...

**Comment by 2-4601** [comment]
It should behave similar to the conversation list, i.e. change to _2 hours_ at 00:59. If not then perhaps you've been hit by #3525?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
