### ISSUE TITLE
Wrong number with double country code gets added while adding new member to a group

### ISSUE THREAD

**Issue by scattenlaeufer** [signalapp/Signal-Android#4897]
When a new member is added to a Signal group, there is also a second number added, which is the number of someone already part of the group, but the country code is screwed up. Instead of +49 (for Germany) the number is added with +4949. This happens seemingly at random and not on all devices in the group, but most of the time only on one of them.

After being blessed with this extra number, all messages I send get an error and are reported as "not delivered". In the message details it states that "some issues need your attention", but I cannot resend the message. Also all participants in the group do receive the message.

**Comment by 2-4601** [comment]
What version of Signal are you using? Has this been always like this or a recent change?
Not sure if it will show in the logs but it might help if you could post a debug log here immediately after the issue happens (**Settings -> Advanced -> Submit debug log**) and paste the link here

**Comment by scattenlaeufer** [comment]
There is a log: https://gist.github.com/anonymous/dee51c126b1c8011dfdb

It's not a problem of the most recent update, but we started to notice it about a month ago parallel to an update, but I am not sure to which version it was. The current version I am working with is 3.7.2 as stated in the log.

**Comment by scattenlaeufer** [comment]
Now we witnessed seemingly the same error, but in a group without the any numbers with double country code. Here is a log: https://gist.github.com/824f07760022875f8b2a

**Comment by scattenlaeufer** [comment]
Here is another log with the problem: https://gist.github.com/anonymous/eddd98e7ae7f57c16ab8

In this case there again were numbers with double country code

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
