### ISSUE TITLE
MultiDeviceContactUpdate fails when linking second desktop device

### ISSUE THREAD

**Issue by liliakai** [signalapp/Signal-Android#4901]
https://gist.github.com/anonymous/51543b8bb4afdcbeb718

See also https://github.com/WhisperSystems/Signal-Desktop/issues/514

**Comment by moxie0** [comment]
What is this log supposed to show? Looks like it's sending fine.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
