### ISSUE TITLE
No sound notifications after upgrades

### ISSUE THREAD

**Issue by jpsingleton** [signalapp/Signal-Android#4902]
This has happened a few times now but I'm not certain that it happens every time Signal is upgraded via the play store. It happened with the latest update (3.7.2) so I thought I'd report it.

When Signal is upgraded no notification sound is played for incoming messages, although the notification LED still flashes. To fix it I have to go into the notification settings and select the sound I use again (Hangouts Message default SMS sound). Before changing the sound back to the previous value it appears unset. The value before entering the selection modal is a short (5 digit) number. The radio button list modal has nothing selected.

If it happens again then I'll try to remember to take some screenshots or a debug log while relevant info is still there.

**Comment by jpsingleton** [comment]
This didn't happen with the latest upgrade so I'll close this.

**Comment by jpsingleton** [comment]
This happened again. I got logs this time so I'll add detail.

**Comment by jpsingleton** [comment]
This is the log output:
```
02-05 18:10:01.350 28911 28911 W MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No entry for content://media/external/audio/media/28886
02-05 18:10:01.355 28911 28911 E MediaPlayer: Unable to create media player
02-05 18:10:01.355 28911 28911 D Ringtone: Problem opening; delegating to remote player
```
Looks like it can't find the file. `28886` is the number it mentioned originally.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
