### ISSUE TITLE
Enable SMS delivery reports by default

### ISSUE THREAD

**Issue by JoEiner** [signalapp/Signal-Android#4908]
Signal does not enable the "SMS delivery reports" flag by default in the App's settings. As providers that charge for SMS delivery reports seem to be a margin phenomenon (according to my own research only very few providers in very few countries), I suggest enabling this setting by default. 

Disabling it is contrary to the expectations to most users who know there is typically a delivery receipt for SMS messages - not even knowing that there is an option to disable that.

Moreover, the Signal UI does not show that one tick is all there will ever be for SMS messages with SMS delivery reports disabled. Users might therefore falsely assume that their messages have not been delivered.

In case "tricking" some very few users into paying 1p for delivery reports is not a viable option for you, I suggest prompting the user if he wants delivery reports enabled the first time he sends a SMS using Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
