### ISSUE TITLE
Failure to download MMS

### ISSUE THREAD

**Issue by jmw16** [signalapp/Signal-Android#4913]
Signal is not downloading MMS messages for me. It's also flagging unsecured SMS messages as failing to deliver but they are, in fact, going through. Any suggestions? 
https://gist.github.com/27fb9d877c2572d67ab9

Thanks

**Comment by 2-4601** [comment]
> Any suggestions?

Have you checked if any of the existing issues of MMS downloads failing are related to your case?
https://github.com/WhisperSystems/Signal-Android/issues?q=is%3Aissue+mms+download

**Comment by jmw16** [comment]
Not as far as I can tell but I'm not very tech savvy.

**Comment by FeuRenard** [comment]
I can't spot anything MMS download related in this log.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
