### ISSUE TITLE
[UX] Button to send image attachment is misplaced

### ISSUE THREAD

**Issue by jnachtigall** [signalapp/Signal-Android#4914]
I selected an image to be send and then waited:

![screenshot_2015-12-17-22-11-50](https://cloud.githubusercontent.com/assets/3307404/11882296/e518efd4-a50b-11e5-8b98-821cd27acd7b.png)

I thought that this screen meant that the image is being sent. After waiting half a minute I learnt that this impression is wrong ;)

Apparently I stll have to sent the bluish button (2.). However, the button is next to the text input field (1.) which makes it unclear that pressing this button (2.) means that the image _above_ is going to be send.

A solution might be 
a) to move the sent button a bit above (nearer to the image) in this case
b) In case I can send also some text (1.) together (simultaneously) with the previously selected image, then just make it clearer that the send button is also associated with the image. For example by having no gap between image and text input. Maybe have it both in a blueish background (like send button).

**Comment by Jiehong** [comment]
Indeed, the send button should always be at the same position, aka  top right of what is about to be sent.

The X button to cancel should be changed, and can directly be put in the middle of the image with a text "cancel" instead.

This would be a lot clearer.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
