### ISSUE TITLE
MMS issues with AT&T

### ISSUE THREAD

**Issue by lndshrk** [signalapp/Signal-Android#494]
First, let me describe the phones...

N4 - A Nexus 4 on stock Android 4.3 running TextSecure 1.0.6

N5 - A Nexus 5 on stock Android 4.4.2 running TextSecure 1.0.6 and alternatively 8sms  1.16

iPhone - iPhone 4S on stock iOS 7.0.4 running the stock messaging app.

All 3 phones on AT&T and on the same plan actually.

APN - I am using the following:

MMSC http://mmsc.mobile.att.net
Proxy proxy.mobile.att.net
Port 80

These settings work fine in 8sms.

Using the N5 on 8sms, the N4 on the stock messaging app, and the iPhone, MMS images can be traded all day long.

When either the N4 or N5 attempts to send an MMS image using TextSecure to the iPhone or either the N4 or N5 NOT on TextSecure, you get the "MMS adaptation" message.  I could quote it verbatim, but I'm sure you know what I'm talking about - some part of this message - blah blah - deleted.

When either the N4 or N5 attempt to send an encrypted MMS to the other phone, you get "bad encrypted".

Summary

Stock to Stock Android or iPhone - works happily
TS to Stock - MMS adaptation message
TS to TS - bad encrypted

In essence - for me - TextSecure doesn't work for MMS images - AT ALL.

**Comment by darkSkies** [comment]
My wife and I just tested this again. TextSecure is my default messenging app... 

She took a photo with her iPhone and sent it to me from the stock iOS messaging app.  I received a message that said "downloading MMS" & after a few seconds that message changes to "MMS download failed". 

Please let me know if I can help you fox this. I have a couple of iDevices and my Android device to work with; I'm having problems getting this to work with either system.

Debug log:  

https://gist.github.com/4e6fe25ff906955d967a

**Comment by Rossmairm** [comment]
Yeah same here, sending photos via latest release on nexus 6p to a Samsung s5 on ATT
