### ISSUE TITLE
Tilting during direct capture makes everything black

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4944]
If I press the direct capture button in a conversation and then tilt the phone 90º, the camera isn't showing anything but black. And no, I'm not holding my finger over the camera lins.

https://gist.github.com/anonymous/4a2c2210e071a30efc93
https://gist.github.com/anonymous/152bfb9182f27d896f04
This has been around for some time now.

**Comment by FeuRenard** [comment]
I don't have this issue. Maybe it's dependend on the device or OS?
Sony Xperia U, Cyanogenmod 11, Signal 3.8.1.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
