### ISSUE TITLE
Group Update Failures are Unrecoverable

### ISSUE THREAD

**Issue by samlanning** [signalapp/Signal-Android#4974]
When updating a group chat, if an update fails to send to one of the members of the group for whatever reason (for example unverified key, deregistered user etc...) then the thread shows up as having an error. but there is no way to resent to users that have not received it, and it does not even show in the conversation view that it was the group update that failed to send.

**Comment by FeuRenard** [comment]
d7e4928 makes the selection of group update messages possible. This allows resending the group update in case of failure.
### Screenshot
![screenshot_2016-09-04-17-57-26](https://cloud.githubusercontent.com/assets/16167751/18232259/464e1750-72cc-11e6-996c-75bfea934269.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
