### ISSUE TITLE
Signal (iOS) contact does not appear in contact list

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#4976]
A friend of mine registered via iOS signal app (meanwhile twice). It is in a group conversation I am too. But he does not appear in my signals contact list.

**Device Info:** Nexus 5, Omnirom 5.5.1, Signal 3.8.1 (Btw. (again): why is this tag not present on github?)

**App state:** Push registered, SMS/MMS disabled, Privacy off

**Comment by johanw666** [comment]
Try refreshing the contact list by pulling down in themain screen, or in Android settings - accounts - sync contacts when you're on ICS or lower.

**Comment by sedrubal** [comment]
I tried this several times. Nothing changed... And I waited several hours...

**Comment by thomasbilk** [comment]
I have the same problem from Android (5.0.2) with a friend who has the iPhone version. We do not see each other though we are both in the others address book.

**Comment by michaelkirk** [comment]
@thomasbilk/@sedrubal has the latest Signal-iOS update had any change in this behavior?

**Comment by sedrubal** [comment]
I can't say, because now he appeared in my list...

**Comment by thomasbilk** [comment]
Same here. All people I expect to see are available. When the problem arises again I will comment.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
