### ISSUE TITLE
Recurring "say hey" messages for all contacts

### ISSUE THREAD

**Issue by benboggart** [signalapp/Signal-Android#4977]
About once every week I receive "say hey" messages for all my contacts. This is extremely annoying (and in German even more so, stating "it's time to say hello").
As these messages occur in the dialogues, I have to check every single one of them - whether there arrived an actual message from my contact or just this "say hey".
I assume the recurrence is is a bug. 
But I also suggest to
- either avoid this message altogether 
- or handle it outside the dialogues, so mistaking them for actual messages is avoided

Currently, this message is for me the single reason to recommend Signal only very tentatively. Two points to consider:
- The large fraction of friends whose major concern is not decryption, but the patronizing nature of commercial alternatives, would be just as annoyed as I am about Signal spamming "it's time to say hello".
- Any additional contact using Signal would only add to my weekly share of "say hey" messages.

Thanks a lot for your work!

_Signal 3.7.2, Android 4.2.2 standard. May be related to #4774._
[Protocol](https://gist.github.com/1516b726a4144ef64567)

**Comment by moxie0** [comment]
Thanks but we can't do anything without a debug log from immediately after this happens

**Comment by benboggart** [comment]
Is the provided Protocol not the debug log you're looking for, or is it just not sufficiently close to when the above happened? Please let me know what to provide and/or what "immediately" means.

**Comment by jopek** [comment]
I get this too, every day or every second day. here is my log, although it is 5 minutes old. I first had to find out how to submit a debug log.. 

my device is a samsung galaxy s4, android version 4.4.2. buch do check the debug log yourself. all details are listed there.
[debug log](https://gist.github.com/anonymous/3280e906d3d371707f3c)

hope this helps!

**Comment by moxie0** [comment]
@jopek In your log the Signal 'account' had been deleted.  This is the Android-level account that should be visible under Android Settings -> Accounts.  Know anything about that?

**Comment by jopek** [comment]
strange... signal has an account listed

**Comment by jopek** [comment]
i have just updated the android signal app. maybe that solves the problem. I'll keep you posted.

**Comment by benboggart** [comment]
Hi moxie, could you please reply to my last question? Not sure what you guys need. Thanks!

**Comment by 2-4601** [comment]
@benboggart Maybe he missed your log. It's linked with the name _Protocol_ which might be confusing. Also the link was invalid before (I guess you fixed it since it works now). For quick access here it is: https://gist.github.com/1516b726a4144ef64567

**Or** its just that you captured the log too late and the important information was already lost.
You should submit the log immediately after you receive the "say hey" messages for all of your contacts.

**Comment by mimi89999** [comment]
I'm even receiving this messages from myself...

**Comment by moxie0** [comment]
the log needs to be captured immediately after this occurs

**Comment by mimi89999** [comment]
It happens every week around 23h UTC.

**Comment by benboggart** [comment]
Thanks 2-4601. I didn't touch the original link, it was working for me all the time. What I provided is called (translated) "diagnosis protocol" in the German version of Signal. 
Hence the question @moxie0. I'd very much like to know whether this protocol 
* is the required log and contains the required information (and was just overlooked)
* is the required log but wasn't captured fast enough
* is not the required log - then how do I get what you need

moxie0, please talk to me ;)

**Comment by moxie0** [comment]
Again, the debug log needs to have been captured immediately after the behavior to debug.  The log you posted wasn't.

**Comment by mimi89999** [comment]
@moxie0 Are you restarting/rebooting the TextSecure server every week around 23h UTC?

**Comment by mimi89999** [comment]
@benboggart Do you remember what time it was when you received the "say hey" messages?

**Comment by benboggart** [comment]
@moxie0 Thanks, now I know that Protocol = Log. That was the question all along. I'll be ready next time.

@mimi89999 Yes! I opened this issue about an hour after it occurred. So Sunday 23:00 sounds about right. The previous two times were between Dec 13th 12:21 and Dec 14th 11:16, and between Dec 19th 12:39 and Dec 20th 08:50.

**Comment by jopek** [comment]
it happened again...   https://gist.github.com/73e23479eea85e56e5f2

**Comment by jopek** [comment]
@moxie0,  about the android signal account: It turns out that it is linked to my previous telephone number but I am using a new sim card with a new number. 
is there a way to transfer the account / link new number?

**Comment by jopek** [comment]
happy new year to all of you! <3

**Comment by mimi89999** [comment]
@jopek Export your data (conversation history), un-install the app, install i again, register your new phone number, and import your data. You can't have two phone numbers registered with Signal on one device.

**Comment by cascheberg** [comment]
@jopek your question is off topic. But there is no need to uninstall the app, see http://support.whispersystems.org/hc/en-us/articles/212535818-What-do-I-do-if-I-get-a-new-number-What-if-I-am-switching-to-a-new-phone-

**Comment by jopek** [comment]
@cascheberg and @moxie0: thank you very much for your quick  response regarding the switching to a new phone / sim. I tried @cascheberg's suggestion and it worked well. 

anyway, back to the original topic:
now using properly registered new number and a new version of signal, yet I still get the signal suggestion to say hey. I acted like Flash Gordon, blazingly fast! here you go...  

https://gist.github.com/69f5fbc931aa46936089

**Comment by jopek** [comment]
it occurred to me that maybe, since it is a "new" registration, it is a the first notification of this sort, despite the contact chats already being full of "say hey" messages.

**Comment by benboggart** [comment]
no such messages this weekend ...

**Comment by iamal** [comment]
Same problem here. It happened just a few minutes ago (~23:50 Japanese time)

https://gist.github.com/anonymous/2bec27ee3b25ce24a67f

**Comment by moxie0** [comment]
@iamal From your log, it also appears that your system-level Signal "account" had been deleted.

**Comment by iamal** [comment]
@moxie0 So does that mean it's a problem on the operating system level, not this app? Is there anything one can do about that?

**Comment by jopek** [comment]
@iamal check what number your signal is associated with. click the three dots, advanced, first entry "signal messages and calls". for me it was once the old number.

just now while writing this, I received again a lot of these. 

https://gist.github.com/e8be04cd9ab7432d5c98

**Comment by iamal** [comment]
@jopek Thanks! It is the correct number, though.

**Comment by benboggart** [comment]
No "say hey" messages for me on this weekend either. 
(Only deviating circumstance I see from previous weeks with "say hey" spamming: No new contacts were established since the last occurance. Don't know if that could trigger something.)

**Comment by moxie0** [comment]
@iamal It seems the Signal account under System Settings -> Accounts is disappearing somehow.  If you're not manually deleting it, then there's something else strange happening.

**Comment by cascheberg** [comment]
Signal 3.9.1 added a preference to disable these messages, see #4926. Not a fix for this bug, but kind of a workaround.

**Comment by jopek** [comment]
I noticed that my android-signal-account is missing when these messages come. at a later point in time the account is there again.

**Comment by iamal** [comment]
@cascheberg Thanks for the hint, I tried it out, hope it works.

@moxie0 I don't delete it manually. Some more information that might or might not be related: I have disabled a few system apps: Android Keyboard, com.google.android.voicesearch, face unlock, google text-to-speech, google contact sync, google+, iFixit (pre-installed on fairphone), picasa uploader, talkback, on-screen tips.
I also run into low-memory problems occasionally, so that I can't update some apps. Signal is up to date.

**Comment by yan-** [comment]
I have experienced the same problems on different devices lately. The next time it happens, I will try to post a debug log.

**Comment by benboggart** [comment]
@cascheberg Thanks for the info. The new setting is great!
I just checked my Signal version, apparently I updated in the process of switching forth and back between phones. I do have 3.9.1 now - that may also explain why these messages did not re-occur since opening this thread.

**Comment by jopek** [comment]
I still get these annoying notifications... 

https://gist.github.com/anonymous/657cab033d2306165e401210636bb92e

**Comment by geminiimatt** [comment]
i am a trainer and have just seen this in the wild a few times now.
two recommendations to you @jopek 
soon as you get the "say hey"
1) send a message back, for example just a period. "."
- OR -
2) reset the secure session. (from inside the chat thread click the upper right 3 dots -> Reset Secure Session)

see if you get them again. also am interested which, if either of these worked for you.

**Comment by mcginty** [comment]
Just got a cheap dual-sim phone ("BLU Advance 5") and it's happening every day-ish:
https://gist.github.com/mcginty/b9a49067bbe1862284f6624ea6dca3a2

**Comment by benboggart** [comment]
Still happening to me as well. (By the way, contributing to the conversation - e.g. by sending the suggested period - seems to work. Can't say anything about the 2nd suggestion yet.)
Log: [https://gist.github.com/anonymous/f557892b53590b36d9c682b5c66ca08f](url)

**Comment by moxie0** [comment]
@benboggart That log link doesn't seem to work

**Comment by p4nci** [comment]
@moxie0 copying the link text works 😃 
https://gist.github.com/anonymous/f557892b53590b36d9c682b5c66ca08f

**Comment by moxie0** [comment]
I'll be interested to see if this is still an issue for you on 3.26.x

**Comment by benboggart** [comment]
Sorry for the broken link. Now I've updated to 3.26.x. Also, after posting the above, I did the "reset secure session" as suggested. I will post a log if it occurs again.

Btw, the "say hey" happens much less frequently than at the time of my first post and also for very few contacts only (all of which I've never had a conversation with). Can't figure out a pattern other than that. It could not have something to do with _them_ having an outdated version, right?

**Comment by yan-** [comment]
Just to let you know: I had this problem before, but for at least some months it hasn't occurred. I'm using 3.27.1.

**Comment by riyapenn** [comment]
Surfacing on 4.6.1 https://gist.github.com/113f831844b0344ddecac7be00a4f6f9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
