### ISSUE TITLE
Update Wiki to reflect new newbie build instructions

### ISSUE THREAD

**Issue by Jesse-V** [signalapp/Signal-Android#4985]
https://github.com/WhisperSystems/Signal-Android/wiki/How-to-build-Signal-from-the-sources#build-signal-detailed-for-newbies describes to newbies how to build Signal from source. However, these instructions are confusing and slightly out of date. For example, it suggest TextSecure.git rather than Signal-Android.git, and it's not clear how to install the Build Tools, SDK API 22, and the other dependencies. I would like to present improved newbie build instructions, which successfully work out of the box in a headless Ubuntu 15.10 VM. I hope that a ticket is the appropriate place to present this, otherwise I can repeat this in a more appropriate venue.

> 1) **Install the dependencies**. You need, the Java Development Kit (JDK) version 7 or higher, the Android Software Development Kit (SDK) Build Tools, SDK API 22, the Android Support Repository, and the Google Repository. These can be set up via the Android Studio GUI, or through the command line via **sudo apt-get --no-install-recommends install default-jdk default-jre-headless** If you already have these installed, skip to step 2.
> 
> > A. Install the SDK. See http://developer.android.com/sdk/index.html for different methods to install the SDK. From the command line, **wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz** then extract with **tar zxvf android-sdk_r24.4.1-linux.tgz**
> > B. Install the libraries. Navigate to the SDK folder, then execute **./android update sdk -a -u -t 7,27,147,155** You will need to confirm the license agreement. As of December 2015, this installs Build Tools revision 22.0.1, SDK API level 22, Android Support Repository revision 25, and Google Repository revision 24.
> 
> 2) Obtain the Signal sources.
> 
> > A. **git clone --depth 100 https://github.com/WhisperSystems/Signal-Android.git** Then navigate into the Signal-Android directory via **cd Signal-Android**
> > B. Switch to the latest release. Run **git tag** to list the current tags, then checkout the latest tag. For example, **git checkout tags/v3.9.0**
> 
> 3) Prepare the environment. You can either define the environmental variable ANDROID_HOME that points to the SDK directory, or define a file local.properties in the Signal-Android directory that points to the SDK. This can be done by writing _sdk.dir=/path/to/sdk_ to local.properties, for example. Finally, if you are building on a 64-bit host, you will need to install lib32stdc++6 and lib32z1 to allow the execution of 32-bit programs.
> 
> 4) Build Signal. From inside the Signal-Android directory, execute **./gradlew build** which is a script that will set up Gradle and the build Signal, which will take several minutes. If your build is successful, the Signal APK is located at _build/outputs/apk/Signal-Android-release-unsigned.apk_ You can then clean the build with **./gradlew clean**
> 
> 5) Sign the build. If you wish to install the release build, it needs to be signed. See https://developer.android.com/tools/publishing/app-signing.html for more information. The quick and dirty method is **keytool -genkey -v -keystore myKeystore -alias Me -keyalg RSA -keysize 4096** and then **jarsigner -verbose -keystore myKeystore Signal-Android-release-unsigned.apk Me** You can then rename it to reflect that it's now signed.
> 
> 6) Signal should now be ready for use. Push it to your device with **adb install Signal-Android.apk**.
> 
> Troubleshooting: Gradle build fails should produce informative error messages. If you see _SDK location not found._ then Gradle cannot find your SDK, which can be corrected by defining the environmental variable or local.properties file described in step 3. If you see messages similar to _Could not resolve all dependencies for configuration: Could not find com.android.support:support-v7:22.2.1_ then you have the wrong Build Tools installed. Messages regarding Google Play apps indicates that you did not install the Google Repository. In both cases, see step 1B on how to install the dependencies.

**Comment by johanw666** [comment]
Don't forget about the Google api key if you want location messages to work: https://github.com/WhisperSystems/Signal-Android/issues/4949

**Comment by Stefan-Code** [comment]
+1 for this, I just built from source and with the new instructions this would have been quite a bit easier.

**Comment by Jesse-V** [comment]
@johanw666 Good catch. Personally, I'm not interested in sharing locations like that, but it's good to know that you need the API to do so.

@Stefan-Code Thanks for the support. I build a snapshot of my VM and tested these instructions a couple of times over, so I'm confident that this guide works and doesn't install any more prerequisits than necessary. Step 3 is the most difficult to explain and could be improved, but it's not to hard to figure out. I'm a big fan of up-to-date guides. :)

**Comment by johanw666** [comment]
Now that I read them more thouroyugh, these instructions are Linux only and commandline only. AFAIK the recommended build method is by installing Android Studio. Using Android Studio, I could build from sources from an unpacked zipfile as well, I didn't need to clone the repository (which can leave out rthe installation of a git environment if you don't plan to submit pull requests). Building signed apk's from Android Studio is just a menu option.

**Comment by sophici** [comment]
Dear all, I am new to android studio and try to build signal from source. However, I cannot build it successfully. First time, I set multidex and fail in unittest such as org.thoughtcrime.securesms.jobs.CleanPreKeysJobTest > testSignedPreKeyEviction. Second time I remove multiDex and get UnsupportedOperationException. Can anyone help me pass the dilemma? sincerely yours.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
