### ISSUE TITLE
Plaintext Export sets wrong "status" attribute in XML

### ISSUE THREAD

**Issue by milux** [signalapp/Signal-Android#503]
When using the plaintext export and import the XML with "SMS Backup And Restore", all restored messages in the "SMS/MMS" app have the green tick icon which says that the receiver got the message (even the ones sent by oneself).
This happens always, even if no delivery report has ever been requested for a particular SMS.
This occurs because the exporter sets the attribute "status" to "0" instead of "-1", which seems to be the right one here.

[System: CyanogenMod 10.2.0 stable on I9505]

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
