### ISSUE TITLE
Problem downloading MMS message

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#5055]
I received an MMS message from a contact.
The 'balloon' states:
Multimedia message
and a DOWNLOAD button.

When I select the DOWNLOAD button, this message is displayed:
Connecting to MMS server ...

But the multimedia message is never downloaded. It can very well be that my MMS settings are incorrect. But the logs show some stack traces:
https://gist.github.com/d59d0424109fededf211
https://gist.github.com/anonymous/24ea4891f21f8d60cfb5

**Comment by janvlug** [comment]
Fixing the MMS server and proxy solved the download issue.
Still the feedback on incorrect settings could maybe be improved (in the UI and the log).
Feel free to close this bug if in your opinion no improvement on the feedback is needed.

**Comment by ClubWDW** [comment]
Which settings are you referring to? Would love to know.

**Comment by janvlug** [comment]
Settings|SMS and MMS|Manual MMS settings
MMS Proxy Host
MMS Proxy Port

During the download problem, both the "MMS Proxy Host" and the "MMS Proxy Port" settings were wrong.

**Comment by ClubWDW** [comment]
Do you have at&t? If so, what settings did you use? Would love to be able
to use the websockets version.

On Sun, Jan 17, 2016 at 6:11 PM, janvlug <notifications@github.com> wrote:

> Settings|SMS and MMS|Manual MMS settings
> MMS Proxy Host
> MMS Proxy Port
>
> During the download problem, both the "MMS Proxy Host" and the "MMS Proxy
> Port" settings were wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/5055#issuecomment-172398272>
> .
>



-- 

Bryan Belt


I prefer to use encrypted email. My public key fingerprint is 8DB3 1568
E467 F703 2C63 E444 821C 645D EBDC 9F9A. Learn why your privacy matters by
watching this video - https://youtu.be/pcSlowAhvUk and then learn how to
protect and encrypt your email by watching this video -
https://youtu.be/Ro3MSBS9w-A

**Comment by janvlug** [comment]
@ClubWDW no, I'm in the Netherlands, I looked up the settings at the website of my provider.

**Comment by nwbt** [comment]
With US AT&T I had the same issue with an Moto X (1st gen) Android 5.1.

Settings > Cellular Networks > Access Point Names > Reset to Default ... Fixed the issue for the time being.

There was another APN which handled MMS listed before I selected Reset to Default. After "Reset to Default" was selected the second APN for AT&T was removed and now MMS pictures download with no problem.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
