### ISSUE TITLE
OTP message not received

### ISSUE THREAD

**Issue by Linuxine** [signalapp/Signal-Android#5062]
Hi, 

I have a bug issue with Signal 3.9.1 on Android 5.0.2 : OTP messages from my bank and Google, for example, are blocked or lost. 

At first I though the GSM signal was not good, or it was my bank's fault. I had to try to validate a purchase twice or three times to get the OTP. Then, I started to have to ask several time the OTP for my Google account. Today (maybe after my last update of Signal ?) I waited the entire morning trying to receive the OTP from Google. Just to be sure, I switched back to the default SMS application on my phone... and I got the OTP immediately. I could not find any option to allow those OTP messages, is there a parameter blocking them in Signal ? It is quite annoying ...
Thanks for your help !

**Comment by agrajaghh** [comment]
we need a debug log to see whats happening

Maybe like that: open Signal, request a OTP, wait 5min (don't do anything in Signal) and afterwards generate the debug log.

**Comment by Linuxine** [comment]
Ok, will do for my next OTP !

**Comment by davepwsmith** [comment]
Just to confirm this bug on the latest version.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
