### ISSUE TITLE
Strange behavior try sending SMS over and over again, incomming call sound 

### ISSUE THREAD

**Issue by harchaoui** [signalapp/Signal-Android#5068]
Hi Signal-Android dev. 
I have the Signal app on a galaxy s5 not rooted, the problem began last week with the last Signal update 3.9.1  ( I guess), Strange behavior come to the surface : 
• The app send one single SMS over and over again to the recipient, and that causes me extra credit.
• When I open the Signal It behave like someone call me and activate the call sound on the phone just sound of incoming call
• I sent a debug log.

**Comment by McLoo** [comment]
You need to post the link of the debug log. 
And the log should be taken right after that happened.

**Comment by harchaoui** [comment]
Yeah ok i will perfom this task soon.

**Comment by doncarton** [comment]
>When I open the Signal It behave like someone call me and activate the call sound on the phone just >sound of incoming call

Experienced same trouble in beta.

**Comment by harchaoui** [comment]
@McLoo i captured the debug log ... i want this debug to be anonymous not link to my actual account.

**Comment by harchaoui** [comment]
@doncarton  yeah this is the same event that i experienced. what kind of task that fire this in your case?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
