### ISSUE TITLE
Contacts list empty, expecting known Signal contacts

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#5079]
The contacts list doesn’t work on android when you click on the blue pencil it takes you to a blank page and nothing happens so you have to copy their number across manually. Unlike SMS Secure where the contacts list opens up and you can just select the contact and just send a message.

**Comment by agrajaghh** [comment]
please post a debug log

**Comment by zero77** [comment]
Ok thanks I will see what I can do.

**Comment by zero77** [comment]
Is this what you wanted

Device  : LGE LG-D855 (g3_global_com)
Android : 5.0 (1445306351, LRX21R.A1445306351)
Memory  : 58M (0.18% used, 256M max)
Memclass: 256
OS Host : LGEARND12B2
App     : Signal 3.9.1

--------- beginning of main
W/PartProvider( 8747): onCreate()
D/LgDataFeature( 8747): LgDataFeature() Constructor: none
D/LgDataFeature( 8747): LgDataFeature() Constructor Done, null
D/ContextHelper( 8747): convertTheme. context->name=org.thoughtcrime.securesms themeResourceId=2131427593
W/PassphraseRequiredActionBarActivity( 8747): onCreate(null)
D/ContextHelper( 8747): convertTheme. context->name=org.thoughtcrime.securesms themeResourceId=2131427584
W/ExperienceUpgradeActivity( 8747): getExperienceUpgrade(179)
W/PassphraseRequiredActionBarActivity( 8747): routeApplicationState(), state: 0
I/PhoneWindow( 8747): [generateLayout] setColorNavigationBar => color=0x ff000001
D/PhoneWindowEx( 8747): [LMJ][PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
I/PhoneWindow( 8747): [setNavigationBarColor2] color=0x ff000000
W/PassphraseRequiredActionBarActivity( 8747): initializeClearKeyReceiver()
W/DirectoryRefreshListener( 8747): Scheduling for: 1452961400236
W/PassphraseRequiredActionBarActivity( 8747): onResume()
D/OpenGLRenderer( 8747): Render dirty regions requested: true
I/Adreno-EGL( 8747): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL( 8747): OpenGL ES Shader Compiler Version: E031.25.03.00
I/Adreno-EGL( 8747): Build Date: 12/12/14 금
I/Adreno-EGL( 8747): Local Branch: LA.BF.1.1_RB1.05.00.00.002.031_20141212_01821442
I/Adreno-EGL( 8747): Remote Branch:
I/Adreno-EGL( 8747): Local Patches:
I/Adreno-EGL( 8747): Reconstruct Branch:
I/OpenGLRenderer( 8747): Initialized EGL, version 1.4
D/OpenGLRenderer( 8747): Enabling debug mode 0
--------- beginning of system
W/ResourcesManager( 8747): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
D/Atlas   ( 8747): Validating map...
W/KeyCachingService( 8747): onCreate()
W/service ( 8747): Broadcasting new secret...
W/KeyCachingService( 8747): onStartCommand, null
W/KeyCachingService( 8747): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 8747): Incrementing activity count...
W/MmsSmsDatabase( 8747): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/MessageRetrievalService( 8747): Active Count: 1
W/MessageRetrievalService( 8747): Waiting for websocket state change....
W/MessageRetrievalService( 8747): Network requirement: false, active activities: 1, push pending: 0
W/RecipientPreferenceDatabase( 8747): Muted until: 0
I/CliptrayUtils( 8747): CliptrayUtils created!! mTextView = android.support.v7.widget.SearchView$SearchAutoComplete{2d9d5212 VFED..C. ......I. 0,0-0,0 #7f100075 app:id/search_src_text}
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
I/CliptrayUtils( 8747): CliptrayUtils created!! mTextView = android.support.v7.widget.SearchView$SearchAutoComplete{666180d VFED..C. ......I. 0,0-0,0 #7f100075 app:id/search_src_text}
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
I/Timeline( 8747): Timeline: Activity_idle id: android.os.BinderProxy@2422aa1d time:527521280
W/RecipientPreferenceDatabase( 8747): Muted until: 0
W/RecipientPreferenceDatabase( 8747): Muted until: 0
W/RecipientPreferenceDatabase( 8747): Muted until: 0
W/RecipientPreferenceDatabase( 8747): Muted until: 0
W/RecipientPreferenceDatabase( 8747): Muted until: 0
I/ViewRootImpl( 8747): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl( 8747): ViewRoot's Touch Event : ACTION_UP
I/Timeline( 8747): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:527524545
W/PassphraseRequiredActionBarActivity( 8747): onPause()
W/KeyCachingService( 8747): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 8747): Decrementing activity count...
W/MessageRetrievalService( 8747): Active Count: 0
W/MessageRetrievalService( 8747): Network requirement: false, active activities: 0, push pending: 0
D/ContextHelper( 8747): convertTheme. context->name=org.thoughtcrime.securesms themeResourceId=2131427592
W/PassphraseRequiredActionBarActivity( 8747): onCreate(null)
D/ContextHelper( 8747): convertTheme. context->name=org.thoughtcrime.securesms themeResourceId=2131427583
W/ExperienceUpgradeActivity( 8747): getExperienceUpgrade(179)
W/PassphraseRequiredActionBarActivity( 8747): routeApplicationState(), state: 0
I/PhoneWindow( 8747): [generateLayout] setColorNavigationBar => color=0x ff000001
D/PhoneWindowEx( 8747): [LMJ][PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
I/PhoneWindow( 8747): [setNavigationBarColor2] color=0x ff000000
W/PassphraseRequiredActionBarActivity( 8747): initializeClearKeyReceiver()
I/CliptrayUtils( 8747): CliptrayUtils created!! mTextView = android.support.v7.widget.AppCompatEditText{3bdaa9b3 VFED..C. ......I. 0,0-0,0 #7f1000a4 app:id/search_view}
W/PassphraseRequiredActionBarActivity( 8747): onResume()
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
W/KeyCachingService( 8747): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 8747): Incrementing activity count...
W/MessageRetrievalService( 8747): Active Count: 1
W/MessageRetrievalService( 8747): Network requirement: false, active activities: 1, push pending: 0
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/CliptrayUtils( 8747): setInputTypeforClipTray(): 0
V/TelephonyAutoProfiling( 8747): [loadFeatureFromXml] *** start feature loading from xml
D/TelephonyAutoProfiling( 8747): [parse] Load xml
V/TelephonyAutoProfiling( 8747): [getMatchedProfile] selected file : /cust/OPEN_EU/config/featureset.xml
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : handle8bit, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : ConcatMTCheckTimestamp, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : allow_sending_empty_sms, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : retry_to_enable_cb, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : copy_submit_to_uicc, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : spam, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : MANUAL_SELECTION_WITH_RAT, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : SUPPORT_LOG_RF_INFO, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : seperate_processing_sms_uicc, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : KRWapPushWithSpam, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : GLOBALspam, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : support_emoji_in_concat_message, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : KSC5601Decoding, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : KR_Modem_Item, value : true
D/TelephonyAutoProfiling( 8747): [profileToMap] add - key : OperatorMessage, value : true
V/TelephonyAutoProfiling( 8747): [loadFeatureFromXml] load feature from xml complete : {handle8bit=true, ConcatMTCheckTimestamp=true, retry_to_enable_cb=true, allow_sending_empty_sms=true, copy_submit_to_uicc=true, spam=true, MANUAL_SELECTION_WITH_RAT=true, seperate_processing_sms_uicc=true, SUPPORT_LOG_RF_INFO=true, KRWapPushWithSpam=true, GLOBALspam=true, KSC5601Decoding=true, support_emoji_in_concat_message=true, KR_Modem_Item=true, OperatorMessage=true}
W/PhoneNumberFormatter( 8747): Got local CC: GB
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
I/Timeline( 8747): Timeline: Activity_idle id: android.os.BinderProxy@1b91e534 time:527525273
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
I/ViewRootImpl( 8747): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=527527054, downTime=527527054, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{24eaebeb V.E..... R....... 0,0-1440,2560}
D/BubblePopupHelper( 8747): isShowingBubblePopup : false
I/ViewRootImpl( 8747): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=527527138, downTime=527527054, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{24eaebeb V.E..... R....... 0,0-1440,2560}
D/Bu

**Comment by agrajaghh** [comment]
@zero77 the log seems to be cut off. Please just post the link and make sure you created the debug log right after you open the contact list

**Comment by zero77** [comment]
https://gist.github.com/anonymous/3906ffccf6369bc416ef

**Comment by 2-4601** [comment]
Do you have any Signal contacts? Is Signal set as your default SMS app?
If the answer is no to both questions then the current behaviour is that you will see no contacts.

**Comment by zero77** [comment]
I have some Signal contacts but it is not my default SMS app as I have some contacts that don’t use it. In SMS Secure it just opens up all my contacts automatically and I select the one I want to send a message to but this doesn’t happen with Signal.

**Comment by agrajaghh** [comment]
is your phone rooted? do you have any apps like xprivacy installed?

**Comment by zero77** [comment]
No it is not rooted and i dont have xprivacy

**Comment by zero77** [comment]
It seams to work fine with apps like SMSSecure and others but for some reason not Signal and I am not restricting the app in any way.

**Comment by CarlosCastaneda** [comment]
Debug Log Url is:
https://gist.github.com/57631eed16aa9dac04f2

**Comment by riyapenn** [comment]
"Re-installed Signal 
- In Settings > SMS and MMS, disabled "Receive all SMS" and "Receive all SMS"; 
- Enabled password;
- Checked the contact list, and it was right, i.e. all contacts on Signal; 
- Refreshed the list, and it was still right; 
- Restarted the phone and waited until the 3G connection was established; 
- Opened the app and went straight to the contact list, which was actually empty; 
- Refreshed the contact list, but nothing happened; 
- Captured Debug log: https://gist.github.com/18d84e7b2d24a576f403"

**Comment by kaiburmeister** [comment]
Masha Kolenkina asked me to post this here:

1. Installed Signal on Nexus 6 with Android 6 via Play Store, Contacts synced with Google Account; Contact List in Signal filled with contacts
2. Turned Off Contact Sync with Google Account
3. Deleted all Contacts in Android Standard Contact App
4. Turned On Contact Sync with DAVdroid; all Contacts showed again in Android Standard Contact App with correctly formatted phone number
5. Turned Phone off and on again
6. Started Signal, got straight to Contact list, Refreshed Contact List; Contact list was empty
7. Captured Debug Log:
https://gist.github.com/fcb14d24b5900e245d3d

After that debug log three more of my friends joined Signal. They are now shown in my contact list. The others who joined before I moved from Google to DAVdroid still are not shown.

**Comment by p4nci** [comment]
I can confirm this (or similar???). You don't need to re-install Signal:
1. DELETE any (Signal)Contact from the (Android) contact app
2. Check contact list in Signal if deleted contact disappears
3. ADD the same deleted contact in the contact app
4. Refresh contact list in Signal: Contact won't show. To send a Signal message you MUST either enter the phoneno. or from conversation list if available.

Maybe there is a trigger in Signal-DB that’s prevent Signal from "refreshing" (updating) contact in the standard android contact app (???)

**Comment by ashjas** [comment]
I got a new device Mi A1. No customisations, stock OS
Installed signal from playstore.
registered with previous working phone number.
Signal could not send sms, or i could not recieve sms.
Verified using call.
Successfully registered.
But none of my signal contacts show up, the main screen of signal app is empty. Searching does not bring any contacts, and if i select a number which i know is a valid signal registered user, i only get an option to send "unsecured sms".
[link to debug log](https://gist.github.com/anonymous/6cb0b787eedb9b0de80b05e9e35c9fd7)

**Comment by p4nci** [comment]
@ashjas you can try
a) refresh the contact list: tap pencil in the conversations list => refresh the contact list i.e. pull-to-refresh
b) delete signal account and then repeat a) (see https://github.com/WhisperSystems/Signal-Android/issues/4338#issuecomment-198157982)

also helpful: [Support: How do I edit or update contacts on Signal Android?](https://support.signal.org/hc/en-us/articles/115005104688-How-do-I-edit-or-update-contacts-on-Signal-Android-)

Please read also: https://github.com/WhisperSystems/Signal-Android/issues/6957

**Comment by ashjas** [comment]
@p4nci yes, it does show the contacts upon refresh. Thanks.

**Comment by schiessle** [comment]
I have the same problem. I'm using the latest version directly downloaded from here as I don't have any Google Services installed https://signal.org/android/apk/

I can message everyone who is already in the chat list but I can't start a new chat as the contact list is empty. I use Signal for Signal only (no SMS).

I wanted to try this:

> b) delete signal account and then repeat a) (see WhisperSystems#4338 (comment))

but there is no Signal account at all listed in my Android settings. Android version is 7.1.2

**Comment by schiessle** [comment]
Today I tried to remove Signal completely and install it again. The problem is the same. The contacts list is empty. Even worse, after importing my old chat history I see now only phone numbers, no names and no avatars. Which somehow makes sense if Signal can't read the contacts (permissions are granted). This is the signal log, maybe it contains some useful information: https://wolke.schiessle.org/s/5k2PAkzSTZcjrPF

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
