### ISSUE TITLE
Decrypting too long (until an unrelated crashed kill signal) 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#5080]
Knowing I would receive an OTP via SMS I unlocked Signal. 
Milliseconds after that the sms notification showed up saying "decrypting" 
Same was for the convo list: stayed in decrypting. 
Went in and out the convo: still always "decrypting" 
Tryed sending a debug log, then signal crashed. 

Don't mind the first crash in the log 😊
https://gist.github.com/anonymous/d72641ad375fe6919c09

**Comment by McLoo** [comment]
Forget about the crash. Should be fixed with latest libpastelog?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
