### ISSUE TITLE
Fresh install needs work

### ISSUE THREAD

**Issue by gillisig** [signalapp/Signal-Android#5081]
Hi guys, 

After a fresh install I am greeted by a big empty screen with no clear clue where to start like you can see below:
![signal-empty-state](https://cloud.githubusercontent.com/assets/5390864/12372955/cf69757a-bc60-11e5-97fe-04993a0ce31c.png)

I think it would improve the user experience greatly if you would add some guidance on how to get started on this screen. Here is a good place for inspiration: http://emptystat.es/

There are also many things unclear at this stage for a new user. Like what happens if I send a message to someone who doesn't have Signal? Whats the easiest way to get them using Signal? Will sending them a message include a message for them to start using Signal? There is only one contact that appears in the list when I compose a new message, does that mean he is the only one who has signal? Does that mean I can only send a message to him?

These are just some of the things that pop up in my head right away. Let me know if I can be of any more assistance.

**Comment by johanw666** [comment]
How about something like https://github.com/SMSSecure/SMSSecure/pull/260 ?

**Comment by agrajaghh** [comment]
I'm not a big fan of these *wizards*, they can be pretty annoying to users who just want to get started. I guess a background image/text saying something like "You don't have any messages yet, tap the blue pencil to write a new message or use the menu to create a group chat" might be a better idea.
Although I don't think any user wouldn't find the pencil alone, its pretty obvious and standard android behaviour...

**Comment by RiseT** [comment]
@agrajaghh *"Although I don't think any user wouldn't find the pencil alone, its pretty obvious and standard android behaviour..."*

I've seen someone complaining "Why the heck do I have to tap on a pencil icon when I just want to open my contact list", though. And I have to say that's a valid point...

**Comment by johanw666** [comment]
"I've seen someone complaining "Why the heck do I have to tap on a pencil icon when I just want to open my contact list"

Because using another row to make a tabbed form, like WhatsApp does, wastes screen space?

**Comment by RiseT** [comment]
@johanw666 I guess the main point of that comment wasn't about tapping on an icon but an icon with a pencil on it. The pencil implies writing. (Solely) opening the contact list isn't writing. If anything, I would expect a pencil icon for the conversation view.

Aside from that, I prefer a tabbed form. But that's just my personal opinion.

**Comment by heyimgay** [comment]
The contact refresh feature is notoriously hard to find for new users.

**Comment by vanitasvitae** [comment]
A little introduction for new users would indeed be a good feature.
Maybe a little popup message that appears at the first start, that offers a little tour?
The popup could have two buttons, one to dismiss the popup (for experienced users) and one, that starts the tour. 
The tour could be "AOSP-first-boot"-style with blue rings and popups that say "press here to..." and so on.

**Comment by mwaclawek** [comment]
There should definitely be a centered text in the background describing the first steps, like [this](http://emptystat.es/image/133336148454).

This has become a de facto standard in (mobile) interfaces.

An introductory wizard like [this](https://github.com/SMSSecure/SMSSecure/pull/260) may be a good idea as well, but is not really related to this issue.

**Comment by cascheberg** [comment]
I also think that this would be a great improvement regarding the first impression that a user gets.
Maybe one could do something similar for the contacts list:
> Not many contacts here yet? Tell them about Signal! It's free and private...
Hint to the "Invite Friends" feature etc.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
