### ISSUE TITLE
System doesn't Support multiple mobile Devices (non Desktop)

### ISSUE THREAD

**Issue by bamberdd** [signalapp/Signal-Android#5102]
I can't use Signal on two mobile Devices at the same time because Signal-App does not allow me to  link the devices via Settings->Devices ...QR-Code scan. 
If the requested feature is realized it would be very useful to give the user the possibility to assign each conntected device with a priority für message delivery.

**Comment by kaueraal** [comment]
I suppose this would be an important feature for later tablet support, as most users of a tablets also own a mobile phone.

**Comment by x12x** [comment]
The qr code you're trying to scan is not for linking the device, but for verifying the other user's identity. It's not your fault if you misunderstood, just poor design choices

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
