### ISSUE TITLE
Unable to send SMS

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#5105]
I noticed that sending SMS on someone's phone with Signal does not work.
See log file:
https://gist.github.com/anonymous/576689062ed206fc9123

Interestingly enough the registration to the Signal server did work (for which I suppose SMS verification is required).

Sending SMS's with the phone when using the regular messaging app works fine.
One thing that I noticed that I on my phone where SMS with Signal is working fine, have more detailed MMS settings than on the phone with the problem sending SMS, but this may be related to the fact that I have an older Android version.

**Comment by moxie0** [comment]
Hmm, not really much we can do. From the log we hand the SMS to the OS, and the OS returns "Error SMS Generic Failure."  Have you looked at the phone number format?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
