### ISSUE TITLE
Often times when getting new group messages from iOS users the keyboard will lock

### ISSUE THREAD

**Issue by kaloudis** [signalapp/Signal-Android#5117]
and I'm unable to reply unless I make a new group myself. Has happened to me three or four times now. I think it has to do with how the group names are set in iOS

**Comment by 2-4601** [comment]
Next time this happens immediately capture a debug log by going to Settings -> Advanced -> Submit debug log
and paste the link here

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
