### ISSUE TITLE
Recipients encountering video playback problems

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#5118]
When I send a video recorded with the Android system camera app (3.1.021 (2428808-40)) from a Nexus 5X (Android 6.0.1, MMB29P) to another Signal-Android user the video does not display although they can hear the audio. They have a Samsung Trend (GT-S7580) running Android 4.2.2 and Signal 3.9.1.

See also https://github.com/WhisperSystems/Signal-iOS/issues/1010

This is a different video file than the one mentioned in the issue linked above although in both cases they were recorded with the same device at 1920x1080 resolution.

**Comment by 2-4601** [comment]
Can you get a debug log from the Samsung Trend device. It should be captured right after you try to play it.
Settings -> Advanced -> Submit debug log
paste link here

**Comment by justin-** [comment]
https://gist.github.com/f1b5621a8715eb0544c7

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
