### ISSUE TITLE
Can't place calls between Android phones

### ISSUE THREAD

**Issue by mastersilv3r** [signalapp/Signal-Android#5126]
From Phone 1 to Phone 2. Call came but no voice exchanged.

Phone 2 to Phone 1. Can't place the call.

**Comment by agrajaghh** [comment]
We need a debug log from both phones (right after the call failed) to see whats happening

Settings -> Advanced -> Submit debug log

**Comment by mastersilv3r** [comment]
https://gist.github.com/2b2b119589f123e8ae72

**Comment by agrajaghh** [comment]
from what phone is this debug log? What issue exactly did you experience?

**Comment by cascheberg** [comment]
```
W/dalvikvm( 2777): WARNING: exception class 'Lorg/thoughtcrime/redphone/audio/NativeAudioException;' missing constructor (msg='Failed to start native audio' kind=0)
```
Same in #5233.

_(There seems to be a problem with correctly throwing `NativeAudioException` in `CallAudioManager.cpp`)_

**Comment by 2-4601** [comment]
@cascheberg is this issue and #5233 still relevant with webrtc?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
