### ISSUE TITLE
Blank screen when calling, call fails

### ISSUE THREAD

**Issue by steko** [signalapp/Signal-Android#5132]
The upper part of the screen shows the call info, but the 80% lower part of the screen is blank white and there is no error message, nor audio from the phone, and no way to hang the call.

Logs here https://gist.github.com/b442f6347f0fa82f3b5b

**Comment by agrajaghh** [comment]
could you please provide a screenshot?

**Comment by steko** [comment]
I would, but when I tried the problem was gone. I'll try to recreate what it looked like from a working screen shot.

Il 27 gennaio 2016 09:32:54 CET, agrajaghh <notifications@github.com> ha scritto:
>could you please provide a screenshot?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5132#issuecomment-175479409

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by edo0** [comment]
I didn't take a screenshot, but here's the debug I took right after I had this kind of issue
https://gist.github.com/2ed1a0f36705dec2b7d1

**Comment by steko** [comment]
Logs from a similarly failed call https://gist.github.com/88e1f64280bf9063ba43

**Comment by steko** [comment]
Screenshot (pardon the volume control)

  ![screenshot_2016-02-05-07-48-52](https://cloud.githubusercontent.com/assets/40545/12839901/fef32bf6-cbdd-11e5-91c4-d814d116f3d8.png)

**Comment by cascheberg** [comment]
Redphone has some race conditions, see #5005. But I don't know if that PR helps...

**Comment by cascheberg** [comment]
Blank call screen has also been reported in #4186 and #4835

**Comment by peperunas** [comment]
+1 happens to me as well.

**Comment by tdb-alcorn** [comment]
+1

Me: LG Nexus 5X, Android 7.0, Signal 3.28.4
Friend: iPhone 7, iOS 10.0, Signal 2.6.5

**Comment by cgsrvc** [comment]
+1
Device: Samsung Galaxy S7
Android version: 7.0
Signal version: 3.29.6
Logs link: https://gist.github.com/bff94033671a3eb4048aab337f1a1e36

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
