### ISSUE TITLE
Quick answer in landscape mode fails transition to portrait

### ISSUE THREAD

**Issue by edo0** [signalapp/Signal-Android#5135]
When I receive a message and open the "Answer" dialogue while my phone is in landscape mode, everything goes fine. But if at a certain point I rotate it to portrait the dialogue won't fit itself to the screen, and I won't have the "send" button (since is outside the screen) unless I rotate it again to Landscape mode.
https://gist.github.com/8076b676ccbec434d82d

**Comment by 2-4601** [comment]
Related #3666.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
