### ISSUE TITLE
When auto-delete limit is reached, outgoing messages are no longer shown

### ISSUE THREAD

**Issue by TheRealCuran** [signalapp/Signal-Android#5148]
I've configured Signal to only keep the last 200 messages per conversation. But when I reach that limit and send another message, the new outgoing message isn't shown (but gets apparently sent, since the contact replied to it) in the conversation screen. Incoming messages work normally and get appended (while probably deleting the oldest message, haven't checked that).

Workaround: delete the conversation/the oldest n messages. Only the first option is a real workaround though, otherwise you can keep deleting constantly.

**Comment by 2-4601** [comment]
I cannot reproduce this. I used the automatic trimming with 5 last messages.
Huawei U8800, Android, 4.0.4, Signal 3.9.1

@TheRealCuran What is your device, ROM, Signal version?
Could you post a debug log immediately after the issue happens? Settings -> Advanced -> Submit debug log
and paste the link here

**Comment by TheRealCuran** [comment]
The Phone is a Fairphone 1U (FP1U), Android 4.2.2 (latest Fairphone ROM version: Koala Nut 1.8.7), Signal 3.9.1

I cannot reproduce this with a limit of 5 messages either, but I had it with the far longer conversation, where this happened. Obviously I can't reproduce it there at the moment, since I just deleted the old stuff there entirely.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
