### ISSUE TITLE
Pictures not displayed

### ISSUE THREAD

**Issue by Jens14L** [signalapp/Signal-Android#5156]
When I open a picture which I have received, it is not displayed in portrait mode (but in landscape mode) and the screen stays blank (see screenshot). If it was opened and displayed in landscape mode before, it is also displayed in portrait mode.

Signal 3.9.1
Android 6.0.1
LG Google Nexus 5
Log: https://gist.github.com/8bcd925896ca3a19d779

![signal_open picture](https://cloud.githubusercontent.com/assets/11010835/12698594/0cbe5ac6-c7a1-11e5-86a2-f13bf46393aa.png)

**Comment by 2-4601** [comment]
Is the issue just with this one picture or with all pictures?

**Comment by Jens14L** [comment]
I have examined the problem more precisely. The issue affects definitely some pictures, however only in one little group with 3 members. Different behaviours occur in this group (sometimes one picture is previewed and displayed normally):
*  The picture is not displayed in portrait mode;
*  The picture is not previewed;
*  It is opened a different picture as previewed.

Could it be a database error?
Should I delete the stored group contents and test if it has solved the problem? …

New log (Signal 3.10.0): https://gist.github.com/4d42721e889538d37add

**Comment by agrajaghh** [comment]
related to #4732?

**Comment by 2-4601** [comment]
Most likely the same cause as in that issue but I guess only @mcginty can know for sure.

**Comment by Jens14L** [comment]
The problem recurs with new images in this one group after deleting the old contents. If I open a picture which is not displayed, then a different picture that is displayed and after that the first one, the other one was displayed (only 2 picture in the group).
I added a group picture which is not displayed sometimes in the group settings.

**Comment by 2-4601** [comment]
Does the issue persist if you "kill" signal from the app switcher or reboot your device?

**Comment by Jens14L** [comment]
Yes, the issues persist after killing or rebooting. I reinstalled Signal and recreated the affected group. I will observe the behaviour in future.

**Comment by generalmanager** [comment]
I've got the same issue, but only with pictures from one person/device. Will post a debug log if needed.

**Comment by agrajaghh** [comment]
@generalmanager is it reproducable for you? Is it happening everytime this one person is sending you a picture?

**Comment by generalmanager** [comment]
@agrajaghh Yup, every single image they send to this group. The images I received from the same device in a private chat don't show this problem. The preview always looks good btw.

**Comment by Jens14L** [comment]
Recreating the group solved the issue for me.

**Comment by Jens14L** [comment]
After some time, the issue reoccurs in the new group with the same both persons.

**Comment by mopsie** [comment]
Same here. Pictures dont open and/or are mishmashed, exactly as Jens14 describes. Thanks for the landscape hint btw. Turning the phone prior to maximising the picture works.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
