### ISSUE TITLE
Add per conversation message trimming (delete old messages)

### ISSUE THREAD

**Issue by bhabba** [signalapp/Signal-Android#5176]
Right now we only have the option to set a global maximum of messages per conversation (_Settings_ -> _Chats and media_ -> _Message trimming_).

I would love to have a **per conversation option** for this as well, i.e. being able to **set the maximum number of messages for every conversation independently**.
- So under _Conversation settings_ of each conversation there should be an option for _Message trimming_ similar to the global option, i.e. a slider for <ins>_Delete old messages_</ins>, an option <ins>_Conversation length limit_</ins> and a button <ins>_Trim all conversations now_</ins>.
- The _Conversation length_ limit should offer any discrete value between 0 and say 10'000 (right now the global option doesn't allow 0; but being able to set 0 in the per conversation option would be beneficial, see 2. under "Advantages" below).
- **The global option** should be changed (and accordingly renamed) to work **as the default value** for the individual per conversation message trimming but shouldn't restrict it.
- Same as the "global message trimming" the "per conversation message trimming" should be disabled by default.
### Advantages
1. Since Signal is more or less designed as a WhatsApp replacement, i.e. meant to be used with all of your contacts with a phone number, you may conduct conversations of different sensitivity simultaneously. On one hand you may want to keep all of the messages exchanged with your regular friends and family on your phone but also want to immediately (or with a little delay) delete the messages exchanged with certain political activists, information sources and other vulnerable people.
   Right now you either have to manually delete every message you don't want to keep on your phone while being able to keep the rest **OR** you have to accept the automatic deletion of **ALL** old messages automatically **INDEPENDENT** of the conversational partner(s).
   
   "Per conversation message trimming" would allow the best of both worlds at the same time.
2. Signal acts as a (ideally the default) SMS/MMS app, too. Besides the actual conversations with real people you may also regularly receive mTAN's, roaming notification/welcome messages and other kinds of messages you don't want to keep. Therefore essentially the same problem as described in 1. occures – but this time the problem isn't that much about unwillingly keeping sensitive information but more about having to do inconvenient janitorial exercises. Either you automatically delete **ALL** messages **INDEPENDENT** of sender/receivers **OR** you have to do the tedious task of **MANUALLY** delete every message and/or conversation you don't want to keep.
   
   "Per conversation message trimming" would solve this problem in an elegant way. For every sender of mTAN, roaming, etc. messages you could set the per conversation <ins>_Conversation length limit_</ins> to 0. Then the message should be deleted automatically as soon as you have read it (properly opened and left the conversation). Maybe there should be a suitable info shown about this behaviour when entering the value 0 into the per conversation <ins>_Conversation length limit_</ins>.

I hope I could convince you of the utility of such a feature :)

https://github.com/WhisperSystems/Signal-Android/issues/3047 might be connected to this issue (implementation-wise), https://github.com/WhisperSystems/Signal-Android/issues/4242#issuecomment-179899174 as well.

**Comment by francwalter** [comment]
Exactly this! Thanks for requesting it!
:+1:

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
