### ISSUE TITLE
wrong transition direction if a conversation is opend by an external Intent

### ISSUE THREAD

**Issue by signalguest** [signalapp/Signal-Android#5210]
When you close a chat opened by a contact widget the transition is still to the right.
That makes the transition unnatural and probably violate the material design guidelines.
Trust me the feeling will never get away.

**Comment by haffenloher** [comment]
Not totally sure what this is about, but it may have been fixed with #4893 in version 3.11?

**Comment by moxie0** [comment]
Please see https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I don't think anyone understands what you're asking for.

**Comment by signalguest** [comment]
Steps to reproduce:
1. Add a direct message contact widget to your screen
2. Tap the the widget -> Signal will be spawned extending from it, that's cool
3. Tap back as you want to close -> Signal will disappear with a transition going to the right
That's a wrong way to exit in that scenario. It's usually ok because from the left come in the contact list, but when you start a chat from a widget you're not going back to contact list but to your home screen.

**Comment by agrajaghh** [comment]
how do you add that widget? I don't have any signal widgets... Is it a SMS widget from the phone?

**Comment by signalguest** [comment]
Exactly, is under Contacts widgets, is Android built in.

**Comment by agrajaghh** [comment]
I guess it's not possible to know if Signal was launched from the widget or contact app. Possible solution would be to transition to the buttom if the activity got launed from an external intent. I'm not sure though, how easy that is and if it's worth it...

**Comment by signalguest** [comment]
Transition to the buttom would be natural.
Or at last go back to contact list, like that is just random.

**Comment by moxie0** [comment]
as of 3.11 this will be going back to the contact list, so should be resolved

**Comment by cascheberg** [comment]
@moxie0 actually that is not true, that fix was for Signal notifications only.

I just noticed that Signal behaves slightly different, even wrong, when opened through the widget, depending on the state that Signal was previously in.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
