### ISSUE TITLE
[Feature request] Support for Samsung Smart Cover display mode

### ISSUE THREAD

**Issue by weirdnik** [signalapp/Signal-Android#5223]
Samsung's Smart Cover for Galxy series phones has features that allow for message management and answering and making calls while the cover is closed (for covers with transparent window). Signal currently acts as if the phone screen is disabled when the cover is closed, and thus to read a message or answer the calls the cover must be opened. This is a feature request to support the windowed covers display mode so calls can be answered and messages read (if Signal is unlocked) using the cover's window display mode.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
