### ISSUE TITLE
No sound when call as securely made

### ISSUE THREAD

**Issue by ajay340** [signalapp/Signal-Android#5225]
For some reason when both my iPhone and Android performed the handshake the ring was made, no sound could be heard when talking on both ends.

**Comment by agrajaghh** [comment]
please post debug log

**Comment by riyapenn** [comment]
Also make sure both devices have microphone permissions enabled.

**Comment by strugee** [comment]
Seems like this should be closed since we've been waiting for a debug log for a year and a half?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
