### ISSUE TITLE
Pebble Watch Doesn't Get Notifications If Set to Name Only

### ISSUE THREAD

**Issue by glassresistor** [signalapp/Signal-Android#5231]
So Signal has a great feature to select what is shown on a notification.  For security reasons I prefer to have my watch only show who texted me and not what they said.
This worked great until afew weeks ago(unclear exactly when) but now I no longer get notifications.  If i change the settings to name and message it starts working again but changing it back to name only stops me from getting notifications again.
I'm running the newest version of Pebble Time and Signal currently available in the play store

**Comment by glassresistor** [comment]
I have a feeling that maybe the pebble app has changed and is failing because it no longer has a message attached for an SMS application.
A shotterm fix might be just adding an empty string or a space(' ') if notifications are off and see if that works.

**Comment by 2-4601** [comment]
related #4264?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
