### ISSUE TITLE
"Client failed" when trying to call other users

### ISSUE THREAD

**Issue by Argafal** [signalapp/Signal-Android#5233]
I have tried with different devices, different versions of android, different users calling different other users. Also iOS, same wifi, different wifis, 3g, 4g ... In none of these constellations I managed to get a call between two users working: It rings, and when the other person picks up I see the handshake words, immediately followed by "client failed". Please advice.

**Comment by agrajaghh** [comment]
Please post a debug log:
Settings -> Advanced -> Submit debug log

**Comment by Argafal** [comment]
https://gist.github.com/anonymous/a36cac3d90fb66c34a91

**Comment by hal88** [comment]
Same issue, another debug log...
https://gist.github.com/03ceec677007d35f2aa5

**Comment by haffenloher** [comment]
@hal88 There's no trace of a Signal call in that log. Did you capture it immediately after the problem occurred?

**Comment by hal88** [comment]
https://gist.github.com/e794e505d02f6d7cea53
Any better? That time signal crashed which it normally doesn't.
Let me know if there's something you want me to test out try.
Cheers.

**Comment by cascheberg** [comment]
Regarding @hal88's log:
```
E/InitiatingCallManager(27949): Died with unhandled exception!
W/InitiatingCallManager(27949): java.lang.IllegalArgumentException: Invalid point
W/InitiatingCallManager(27949): 	at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
W/InitiatingCallManager(27949): 	at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
W/InitiatingCallManager(27949): 	at org.spongycastle.crypto.generators.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:73)
W/InitiatingCallManager(27949): 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.generateKeyPair(KeyPairGeneratorSpi.java:155)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:253)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.<init>(ZRTPSocket.java:106)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPInitiatorSocket.<init>(ZRTPInitiatorSocket.java:56)
W/InitiatingCallManager(27949): at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:88)
```
That has also been reported in #5064.

The crash is the same cause as in #5353.

**Comment by cascheberg** [comment]
@agrajaghh I wouldn't say that #5064 is a duplicate, since it's not clear what is being tracked here.

@Argafal's log is quite different:
```
W/CallAudioManager(12599): AudioPlayer::start() returned -1!
W/dalvikvm(12599): WARNING: exception class 'Lorg/thoughtcrime/redphone/audio/NativeAudioException;' missing constructor (msg='Failed to start native audio' kind=0)
E/InitiatingCallManager(12599): Died with unhandled exception!
W/InitiatingCallManager(12599): java.lang.RuntimeException: re-throw on exception class missing constructor
W/InitiatingCallManager(12599): 	at org.thoughtcrime.redphone.audio.CallAudioManager.start(Native Method)
W/InitiatingCallManager(12599): 	at org.thoughtcrime.redphone.audio.CallAudioManager.start(CallAudioManager.java:54)
W/InitiatingCallManager(12599): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.runAudio(InitiatingCallManager.java:130)
W/InitiatingCallManager(12599): 	at org.thoughtcrime.redphone.call.CallManager.run(CallManager.java:103)
W/InitiatingCallManager(12599): at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:94)
```

There are different exceptions that lead to the same observable behavior. Maybe issue titles should be updated accordingly?

**Comment by agrajaghh** [comment]
@cascheberg you're right, I just had a look at @hal88 log which looks like the one in #5064

**Comment by qguv** [comment]
Same issue here.

**Comment by jeremymasters** [comment]
@qguv what about a log file?  Should probably be able to repro this and get the log file.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
