### ISSUE TITLE
Straight Talk, recurring request for MMS Settings

### ISSUE THREAD

**Issue by nlourenco** [signalapp/Signal-Android#5235]
In place of receiving an MMS message from a contact, I get the following:

> _Multimedia message_
> Tap and configure MMS settings to continue download.

I go in and input the following information per my carrier:

> Name: straight talk
> APN: wap.tracfone
> Port: 8080
> MMSC: http://mms.tracfone.com
> MMS Proxy:  Leave blank
> MMS Port: Leave blank

After I do so, there is only a back button to go back to my text messages, but my MMS message fails to materialize ie. nothing happens. 

> Samsung Galaxy S3
> Android 4.1.2
> Straight Talk (Verizon network)
> Signal 3.10.0
> [debug log](https://gist.github.com/78010851ba2f1d048f42)

**Comment by jjohns71** [comment]
From what I've found it looks like the MMSC should be http://mms3.tracfone.com
MMS Port 80

Is this link relevant - http://forums.androidcentral.com/google-nexus-5/350688-mms-straight-talk-issue-correct-apn-settings.html

**Comment by nlourenco** [comment]
I have learned that the Samsung Galaxy S3 on Straight Talk (Verizon network) does not have an option to edit APN settings in the system. Is it possible to route all MMS messages to default text messaging app instead of Signal?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
