### ISSUE TITLE
Receive encrypted messages on secondary SIM

### ISSUE THREAD

**Issue by mach-o** [signalapp/Signal-Android#5267]
On my dual-SIM phone, I can only receive encrypted messages on my primary SIM. The secondary SIM receives SMS only.

**Comment by strugee** [comment]
So we're clear: you mean on the second SIM's _number_, right?

**Comment by mach-o** [comment]
I guess? Can you explain the distinction/potential misunderstanding?

**Comment by strugee** [comment]
Plaintext texts go over the cell network using your SIM card. Encrypted Signal messages go over the data connection, which could be the cell network's data connection but could also be WiFi, etc. They use your number to identify you, but they don't use the SIM card or the number's carrier account in the same way plaintext SMSs do. In other words, you could pull out your SIM card and still receive Signal messages, but not SMS messages.

**Comment by John-Kenney** [comment]
It seems it's only possible to register one number with Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
