### ISSUE TITLE
Google Play Store: "Package File is invalid" (Android 2.3.6)

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#5269]
Related to https://github.com/WhisperSystems/Signal-Android/issues/5254, https://github.com/WhisperSystems/Signal-Android/issues/2753, https://github.com/WhisperSystems/Signal-Android/issues/2881

I've had this problem with signal/textsecure updates intermittently over the years.
I've had this problem just with signal/textsecure, never with any other app.
I've tried this procedure multiple times (http://support.whispersystems.org/hc/en-us/articles/217293017-What-do-I-do-if-i-see-Package-file-is-invalid-) with no success.
I've also removed Google Play Store updates and reinstalled them without success.
A couple of times I've also done a full wipe/factory reset of the device, and I still had the same problem. 
This problem has always been fixed eventually by an update of signal/textsecure (sometimes I had to skip multiple updates).
The last version I've been able to install on my device is 3.8.1.
My device is a samsung galaxy s advance GT-I9070, android 2.3.6 stock non rooted.

Debug log: https://gist.github.com/fvmrc/c0f131599f8aa8f8adb3

See this: https://github.com/WhisperSystems/Signal-Android/issues/2753#issuecomment-84731860

**Comment by johanw666** [comment]
Signal 3.9 introduced location messages and upgraded the version of Google Play Services it required to at least 8.1. Does yur device run Play Services >= 8.1?

If so, try the apk from apkmirror.com to check if itis a playstore related issue or if it has to do with the cobination of the apk and your device. If you are able to sideload it the playstore might have an issue.

**Comment by fvmrc** [comment]
I'm running Goole Play Services 8.4.89 (2428711-034).

**Comment by johanw666** [comment]
BTW, the dexopt error you get seems identical to #5254

**Comment by johanw666** [comment]
When I google on `DexOpt: couldn't find static field` I get a lot of old discussions, seems to be something later Android versions have solved. Perhaps the discussion in https://code.google.com/p/android/issues/detail?id=2422 is relevant to this?

**Comment by agrajaghh** [comment]
```
02-19 19:25:54.900 E/dalvikvm( 5724): LinearAlloc exceeded capacity (5242880), last=416
02-19 19:25:54.900 E/dalvikvm( 5724): VM aborting
```
I just tried this gradle plugin: https://github.com/KeepSafe/dexcount-gradle-plugin

> Total methods in TextSecure-debug.apk: 59672 (91,05% used)
> Total fields in TextSecure-debug.apk:  27925 (42,61% used)
> Methods remaining in TextSecure-debug.apk: 5863
> Fields remaining in TextSecure-debug.apk:  37610

so its not the 65K limit. But iirc there were some devices with an even lower limit, no? Damn google...

**Comment by fvmrc** [comment]
```
02-19 19:25:54.900 E/dalvikvm( 5724): LinearAlloc exceeded capacity (5242880), last=416
02-19 19:25:54.900 E/dalvikvm( 5724): VM aborting

```
Maybe some of this information is relevant?
https://bugzilla.mozilla.org/show_bug.cgi?id=1100361
http://stackoverflow.com/questions/8413898/linearalloc-exceeded-capacity-5242880-last-1092-error-while-instaling-on-my-s
https://code.google.com/p/android/issues/detail?id=22586
https://www.facebook.com/notes/facebook-engineering/under-the-hood-dalvik-patch-for-facebook-for-android/10151345597798920

**Comment by baitisj** [comment]
I experience this bug on the Motorola XT557, and have attempted manually installing 3.13.1 from apkmirror. Both result in failure. Cleaned cache and data for all Google products did not fix the issue.

Android version 2.3.7
Google Play Services version 8.4.89 (2428711-034)
Google Play Store version 5.8.8

**Comment by The-42** [comment]
Same situation for me as @fvmrc has, cannot get past Signal 3.8.1. Tried every version apkmirror had and that Google Play Services workaround, no success on a rather exotic Ace 2 with stock Android 2.3.6.

Google Play Services 8.7.03 (2645110-034)
Google Play Store 5.8.8
Samsung Galaxy Ace 2 (GT-I8160P)

I wouldn't mind keeping 3.8.1 if it wouldn't keep telling me it's expiring in a week :/

Any chance for a fix or will I really have to root the device after all to get a bit more recent version of Android?

**Comment by moxie0** [comment]
I'm hoping that's enough

**Comment by The-42** [comment]
It is indeed, update via apkmirror to 3.14.0 went well & no more "in 4 days I will die" message :)

Too bad this got reverted in e0f6a92to fix #5337, so the problem is likely to return from 3.14.1 on...

**Comment by agrajaghh** [comment]
@The-42 @moxie0 3.14.1 is working for me on 2.3.7

**Comment by baitisj** [comment]
Same here. 3.14.1 is working fine on Gingerbread Android version 2.3.7 / XT557.

**Comment by The-42** [comment]
Huh. 3.14.1 is also installing & working fine on 2.3.6. Not sure why, still better than the other way around though. Thanks :)

**Comment by johanw666** [comment]
On 15-03-2016 12:46, Bert van Hall wrote:

> Huh. 3.14.1 is also installing & working fine on 2.3.6. Not sure why,
> still better than the other way around though. Thanks :)

Because the last patch from 3.14.0 to 3.14.1 did not just reverse the
removal from some packages from proguard but made the inclusions more
specific:

removed in 3.14.0 (note the two *):
keep class org.spongycastle.jcajce.provider.asymmetric.** {*;}

added in 3.14.1:
keep class org.spongycastle.jcajce.provider.asymmetric.* {*;}
keep class org.spongycastle.jcajce.provider.asymmetric.util.* {*;}
keep class org.spongycastle.jcajce.provider.asymmetric.dh.* {*;}
keep class org.spongycastle.jcajce.provider.asymmetric.ec.* {*;}

the other classes in org.spongycastle.jcajce.provider.asymmetric are
still removed, but because those are not used it doesn't matter.

-- 
Met vriendelijke groet,

Johan Wevers

**Comment by fvmrc** [comment]
I have successfully installed signal 3.14.2 on the device.
However, upon installing version 3.15.2 this problem reappears again.
Debug log: https://gist.github.com/fvmrc/cf2fd82d5b1d0e61a11f956fd10c75c2

**Comment by agrajaghh** [comment]
@fvmrc what device are you using?

its working for me on a HTC Desire with 2.3.7

**Comment by fvmrc** [comment]
@agrajaghh The one in the original post: samsung galaxy s advance GT-I9070, android 2.3.6 stock non rooted.

**Comment by The-42** [comment]
Same for me on my GT-I8160P with Android 2.3.6, I'm afraid...

btw thanks @johanw666 for the explanation :)

**Comment by The-42** [comment]
Not really unexpected, still bad news for us phone-whose-crappy-vendors-won't-update users...

Oh well, thanks for the effort so far, I hope Signal 3.14.2 won't expire too soon ;)

**Comment by johanw666** [comment]
It expires 90 days after build. However, you can of course build your own version from the 3.14.2 sources and remove that limitation.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
