### ISSUE TITLE
Multiple calls in a row should be stacked

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#5271]
Hi, a friend of mine wants me to call and wake her up which is fine and all, but calling 20 times in a row creates some serious spam in the chat. There's no way that I could find to delete these messages either.

My suggestion is thus: Multiple calls in a row should be stacked. 
With that I mean that instead of:
Hi wake up!
You called
You called
You called
You called
You called
You called
You called
You called
You called
You called
Sleepy bird!

You get:
Hi wake up!
You called x10
Sleepy bird!

When you click the called message you get the full list.

**Comment by 2-4601** [comment]
Hmmm... I've a feeling this could be a dupe but couldn't find it :)
Related #4190

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
