### ISSUE TITLE
signal message not delivering for random contacts

### ISSUE THREAD

**Issue by slio** [signalapp/Signal-Android#5279]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

I am using signal only for signal messages and calling. Today randomly inbetween conversation with a contact the messages never went to my friend( it's still on loading screen) 
I have tried resetting secure connection, it is also finishing to load animation. The messages sent by my friend can be received by my device.

Meanwhile i am able to send recieve messages with other contacts. One contact also notified me suddenly he can't signal message me though mine are delivering to him.
### Device info

 **Model:** ONEPLUS ONE

 **Android version:** 4.4 CM 11S

 **Signal version:** 3.12.0
### Link to debug log

https://gist.github.com/f2974198974560761241

**Comment by signalguest** [comment]
#5273 
Same here.

**Comment by signalguest** [comment]
Not able to edit my comment on Android so i add a new one

New log, same issue
https://gist.github.com/5abfb15efab569571b6b

**Comment by riyapenn** [comment]
contact support@whispersystems.org also check out http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-

**Comment by slio** [comment]
Device info

Model: ONEPLUS ONE

Android version: 4.4 CM 11S

Signal version: 3.16

Tried the support options given. Anythings else i could try?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
