### ISSUE TITLE
SMS inbox hickup - received SMS marked as undeliverd outgoing

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#5287]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Steps to reproduce
- wish I knew how, maybe I'll by something else via PayPal :stuck_out_tongue_closed_eyes: 
- last PP SMS came in properly about 15 hours ago
- self sent test SMS works fine 
- received the security code SMS from PP
- opened Signal from notification, with unlocking it
- (I think I noticed some flickering at the new message bubble, but not sure about that)
- then I got my fully working PP codeas undelivered outgoing message
### Screenshots

![unbenannt](https://cloud.githubusercontent.com/assets/5326916/13287523/cd46720a-db07-11e5-91d5-c5ed11ff69aa.png)

### Device info

Device  : Sony D5503 (D5503)
Android : 5.1.1 (3760228123, 14.6.A.1.216)
Memory  : 19M (6.17% free, 192M max)
Memclass: 187
OS Host : BuildHost
App     : Signal 3.12.0
### Link to debug log

This log seems to be useless, despite the fact, that I sent it immediately after screenshooting the PP convo
https://gist.github.com/f6bedf3a54e7ee5bf1bf

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
