### ISSUE TITLE
Jump/go to time/date in conversation

### ISSUE THREAD

**Issue by weak2** [signalapp/Signal-Android#5290]
Hi all,

thank you for Signal I use it for quite some time now! Which in turn brings me to the following feature request:
Please add a "**jump to time**" functionality!
I have several chats where there is a lot of conversation. Just to go to a specific date takes a lot of scrolling and often even a press of "show full conversation".

I imagine a press on the menu button inside a conversation that shows a new menu item "jump to". After pressing it I could then choose from predefined choices like "Yesterday", "One week ago", "One month ago", or, additionally, enter a specific date I want to jump to. 
Perhaps, there could also be a time field to jump to specify the landing point more closely (I am unsure whether this is really necessary but it might be for some people.). For even more user friendliness, the date could be chosen from a pop-up calendar but just a plain vanilla "jump to date" functionality would already help a lot.

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
