### ISSUE TITLE
Phone number change results in bad encrypted messages

### ISSUE THREAD

**Issue by sashw** [signalapp/Signal-Android#5296]
When a user changes the phone number (following the corresponding [support](http://support.whispersystems.org/hc/en-us/articles/212535818-What-do-I-do-if-I-get-a-new-number-What-if-I-am-switching-to-a-new-phone-) description) the 'old' encryption keys for already existing sessions are still used. Sent messages therefore can't be read by recipients. [Reset of the keys](http://support.whispersystems.org/hc/en-us/articles/215238178-What-do-I-do-if-I-have-a-bad-encrypted-message-) solves this issue. 

At least this was what happened when a friend from my contact list got a new phone number. All messages he first sent couldn't be decrypted, other contacts had the same problem. Maybe the reset of (existing) session keys could be triggered by the app once a phone number gets registered in order to avoid this problem.

Android version: CM12.1
Signal version: 3.9.1 (Outdated, I know, but I haven't seen a commit since then which might affect this issue)

**Comment by freelibertas** [comment]
The trigger can't be automatic or you wouldn't be able to tell if someone is impersonating your friend. An automatic reset of encryption keys would make all the magicrypto useless. The developer of Signal said elsewhere that they want to make the message that comes with the key mismatch more user friendly, but it will never completely disappear. Unfortunately there's a price to pay for encryption and it's usability.

**Comment by sashw** [comment]
Yes, that's right. I totally agree with that. I guess I haven't expressed myself clear enough what I meant with triggering a key reset.
Let's say you already use Signal and have chat sessions with encryption keys. Then you get a new phone number. To register Signal with this number, you have to first unregister the old number. Therefore you go to the advanced settings and disable Signal messages by toggling the first option. This could be used as the trigger I meant. Because if you disable Signal messages, a reset of the existing session keys shouldn't harm the security. Especially if you yourself initiate this.
Once you register it again with the new number, new session keys are used in existing chat sessions. Since you are using a new phone number, messages to other contacts appear in a new chat session. No bad encrypted messages which might irritate users. At least if I did not forget something important.

**Comment by 2-4601** [comment]
What was the exact error you got when your contact changed to new number?
1) **"Bad encrypted message..."**
or
2) **"Received message with unknown identity key. Tap to process and display."**

If 1) then it sounds like something weird happened
If 2) then that's the expected behaviour

**Comment by sashw** [comment]
Sorry, I haven't posted the exact error message. I got the error
"**Message encrypted for non-existing session...**"
so neither 1) nor 2). Seems I skipped a line or two in strings.xml when I checked what the english message is, it wasn't bad encrypted message... But still it seems to not be the expected behaviour. I was not able to view the message at all.

**Comment by 2-4601** [comment]
Thanks, it would be helpful if you could describe what happened step by step with as much detail as you can remember. Now you mostly concentrated on interpreting what happened instead of describing what actually happened :smile:

**Comment by moxie0** [comment]
It's cool, this is a known problem. I don't think I need any more info to fix this.

**Comment by texttheater** [comment]
This is really bad especially if you are in a group with many people. Your messages to the group will appear as bad *individual* messages to each member.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
