### ISSUE TITLE
Camera sensor usage

### ISSUE THREAD

**Issue by takhlaq** [signalapp/Signal-Android#5301]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

abnormal camera usage when idle? see screenshot (camera sensor usage)
### Steps to reproduce
- i realise this isn't very helpful, but i don't really have any detailed steps to reproduce or any other info other than signal was running in background when i noticed (wasn't even using the camera in-app)
### Screenshots

![screenshot_2016-02-28-15-32-44](https://cloud.githubusercontent.com/assets/6381451/13390001/60953550-dec3-11e5-8825-bba442a1df2d.jpg)
### Device info

 **Model:** ASUS Zenfone 2 (ZE551ML)

 **Android version:** 5.0.0

 **Signal version:** 3.12.0

**Comment by sadmansk** [comment]
I came across this bug earlier today as well, also using ASUS Zenfone 2. Is it possible that it's an issue with the x86-processor?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
