### ISSUE TITLE
"Select All" option in Batch selection mode does not work as expected when there is an unread message

### ISSUE THREAD

**Issue by jsoberg** [signalapp/Signal-Android#5327]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

When the "Select All" menu item is selected while _Batch selection mode_ action mode is up in the conversations list **and** there is at least one unread message, not all conversations are selected.
### Steps to reproduce
- Open Signal app.
- **Make sure** that there is an unread message in the conversation list.
- Long press on a conversation to bring up the "Batch selection" action mode.
- Tap "Select All" option from the action mode.
- Scroll up/down through conversations while they are selected.
#### What happened:

Some conversations in the list were not highlighted.

For example, I had 30 conversations in my list. When the "Select All" menu item was tapped, the action mode subtitle displayed "30 selected". However, when scrolling down the list, there were 8 conversations which were not highlighted. When one of these un-highlighted conversations was tapped, the action mode subtitle would subtract one (e.g, "29 selected"). When the conversation was tapped again, it was highlighted (as expected) and the action mode subtitle was incremented by one (e.g "30 selected").
### Device info

 **Model:** Motorola Moto X (2nd Generation), AT&T

 **Android version:** 5.1

 **Signal version:** 3.13.1
### Debug log

Logcat displayed no relevant log information when the issue was reproduced.

**Comment by 2-4601** [comment]
Thanks for the well written bug report.

I can reproduce this with Nexus 4, stock 5.1.1, Signal 3.13.1

Seems to be only a visual glitch.

**Comment by jsoberg** [comment]
I suspect that this may have something in particular to do with the views in the list being recycled; Scrolling up and down on the list quickly seems to increase the number of un-highlighted items in the list, along with changing which items are highlighted and which are not.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
