### ISSUE TITLE
Malformed picture in MMS crashes Signal.

### ISSUE THREAD

**Issue by Aldarone** [signalapp/Signal-Android#5349]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

Signal crashes since I received a spam MMS. By looking at logcat it seems that the embedded image is malformed and Signal cannot make the thumbnail : `java.util.concurrent.ExecutionException: org.thoughtcrime.securesms.util.BitmapDecodingException: Failed to decode image dimensions: -1, -1`
### Device info

 **Model:** Asus Zenfone 2 ZE551ML

 **Android version:** 5.1.1

 **Signal version:** 3.14.2
### Link to debug log

https://gist.github.com/Aldarone/d547edcd915f9dfc572d

**Comment by Trolldemorted** [comment]
could you upload an example image?
