### ISSUE TITLE
Receiving the same message twice in group-chat

### ISSUE THREAD

**Issue by Wasseranomalie** [signalapp/Signal-Android#5355]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

In a group of three people I sometimes receive the same textmessage from one person twice directly behind each other, although he only sends it once. The third person receives it correctly just one time. It does not always happen.
### Device info

 **Model:** LG Nexus 5X

 **Android version:** 6.0.1

 **Signal version:** 3.14.2
### Link to debug log

https://gist.github.com/anonymous/464864b7a2b22601c587
I am not sure if it is in there, because it is only few seconds long..

https://gist.github.com/anonymous/7a3308bae1eab06ddc74
That´s the debug log from the desktop-app (v0.3.2).

**Comment by 2-4601** [comment]
> receive the same **textmessage**

By **textmessage** you mean Signal message?


Sounds like #2639 except this part:
> The third person receives it correctly just one time

It would help to get a debug log from the sender's device. And ask if the sender was in a poor network condition during the sending.

**Comment by EmilVogt** [comment]
I was about to open a bug report, too, because this happens to me sometimes as well.

Group with 3 members:
A (me): Sony Z3 Compact, Android: 5.1.1, Signal: 3.13.1
B: Sony Z3 Compact, Android: 5.1.1, Signal: 3.13.1
C: Sony Z1 Compact, Android: 5.1.1, Signal: 3.13.1

So B is sending a signal message without any errors (in opposition to #2639) and C is receiving this message normally (once). I'm the only one recieving this message twice. The messages I recieve show these times:
1. sent 13:48:31
    received 13:45:59
2. sent 13:48:31
    received 13:46:00
Note, that the times show a strange behavior (received before sent).

A log from A (me):
[https://gist.github.com/c93b148354cecd2f884d](url)

Unfortunately, I can't provide a log from the sender's device.

**Comment by Wasseranomalie** [comment]
Yes, i meant Signal messages.

I´ll ask about a log and the network-conditions the next time it occurs.

My messages didn´t come from the future:
1. sent 18:53:54
received 18:54:00
2. sent 18:53:54
received 18:54:03

**Comment by caioiglesias** [comment]
I've caused it before. My messages kept failing and I kept clicking resend while flooding everyone in the group.

**Comment by nicdumz** [comment]
I've just hit a similar issue, and *I know* I happened to be in bad network conditions.

Specifically, the wifi router had a misconfigured / slow DNS server. Me (sender) first had a "delivery failed" error from the Android app. I retried once, messages eventually went through.


My receivers received messages 6 times. This was a group chat, 4 members including me.

Realized too late to grab a relevant debug log.

Versions looks like this on sender:
```
Device  : LGE Nexus 5X (bullhead)
Android : 6.0.1 (2705526, MHC19Q)
Memory  : 31M (2.23% free, 192M max)
Memclass: 192
OS Host : <redacted>
App     : Signal 3.15.2
```

One of the receivers:
```
Device  : LGE Nexus 5X (bullhead)
Android : 6.0.1 (2741998, MHC19T)
Memory  : 43M (19.45% free, 192M max)
Memclass: 192
OS Host : <redacted>
App     : Signal 3.15.2
```

**Comment by 2-4601** [comment]
@caioiglesias & @nicdumz What you are describing is definitely #2639.
The other reports here sound like something different.

**Comment by nicdumz** [comment]
@2-4601 thanks, after asking for more details, you are correct. Each participant of this N participant received the message (N-1) times. Updated my original comment to reflect this.

Thanks for the quick update.

**Comment by dball** [comment]
Two of my correspondents is seeing this in a 3-way group chat. We can replicate it apparently easily and could provide debug logs from all devices. Is this known to still be a problem? Would our debug logs be useful or superfluous?

**Comment by Trolldemorted** [comment]
@dball how do you replicate it? and can you replicate that in non-group chats as well?

I am having this issue every now and then with non-group chats.

**Comment by riyapenn** [comment]
17-person group chat, message "duplicates" received 7 times. Unsure of sender had any alerts. If that's the case then these logs (if useful) should be posted on #2639 
Sender: https://gist.github.com/5cf13232b52fec422985ba5e74f6a6f0
Receiver: https://gist.github.com/61d903cb2a118b65a7285c1b230f70e0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
