### ISSUE TITLE
Enhancement: Append timestamp to export filename

### ISSUE THREAD

**Issue by Fmstrat** [signalapp/Signal-Android#5364]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Enhancement description

Right now, if you run a Plain Text Export, it exports to a file named `SignalPlaintextBackup.xml`

Since every time you backup, it uses the same filename, a user has to rename the file if they archive them off in a folder. It also makes it easy to accidentally overwrite an old backup when testing.

This request is to append a formatted timestamp to the filename, thus `SignalPlaintextBackup-YYYYMMDDHHSSmm.xml`, or `SignalPlaintextBackup-EPOCH.xml` or any other combination that would ensure unique filenames.

Suggest to include this with feature request: https://github.com/WhisperSystems/Signal-Android/issues/2791

Would likely require alterations here: https://github.com/WhisperSystems/Signal-Android/blob/3d651ef29a2b270ac291946ba6f0eda3db43fc6e/src/org/thoughtcrime/securesms/database/PlaintextBackupExporter.java#L15

And alterations to import code to select a file.
### Steps to reproduce

Just a plain text backup.

 **Signal version:** 3.14.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
