### ISSUE TITLE
Crash using recycled bitmap

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#5368]
I have:
- :cat: searched open and closed issues for duplicates
- :cat: read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

Seems like there's something happening where recycled bitmaps are thrown back into the pool. Very likely related to #4732, but opening separate issue since it's an actual crash and not totally certain.
### Steps to reproduce

(unknown besides have lots of images and use the app frequently)
### Device info

 **Model:** LG Nexus 5

 **Android version:** 6.0.1

 **Signal version:** 3.14.2
### Link to debug log

https://gist.github.com/anonymous/d91b41ac22235d3f943f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
