### ISSUE TITLE
download of Video files is broken

### ISSUE THREAD

**Issue by ulu** [signalapp/Signal-Android#5377]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I have a group containing 3 members including me. One member has an iPhone. The two others have an Android device. Sending/receiving/saving Pictures are no problem for all devices. But we are unable to share movies between devices with different OS.

On Android the movies from iPhone cannot be played from Signal nor can they be stored to phone internal/SD-Card storage. There is a message which vanishes to fast to be readable followed by another one saying "file was successfully saved" but the movies are always files of 0 bytes. On an Android device recorded and send *.3gpp files can be saved on the other Android device.

The iPhone user is unable to save the movies from Android phones to local iPhone memory.
### Steps to reproduce

Scenario 1:
- generate a short movie with iPhone (*.mp4)
- send it to the group
- try to download the file on Android device (it does not matter if over WiFi or mobile network)
- check /media/sdcard/Movies (depends on device and attached SD-Card) and you will find a file signal-[Timestamp].mp4 of size 0 bytes

Scenario 2:
- generate a short movie with iPhone (*.mp4)
- send it to the group
- try to play the file on Android device by touching the picture (it does not matter if over WiFi or mobile network)
- chose a movie player (i tried vlc, google galery, mx player, BSPlayer, TotalCmd)
- only TotalCmd says (on Ulefone):
  ![screenshot_2016-03-25-14-13-10](https://cloud.githubusercontent.com/assets/809609/14044718/ef4f5b66-f293-11e5-9793-468bf2ad50cf.png)

Scenario 3:
- generate a short movie with Android phone (*.3gpp)
- send it to the group
- try to download the file on iPhone device - which is not possible at all (That's what I got from the person with iPhone. I am currently not able to check what happens without physical access.)

**Actual result:**
Downloaded Signal-[Timestamp].mp4 has size of 0 Bytes

**Expected result:**
Either I would expect an unambiguous error message showing the reason for the failure or I expect the file properly stored to the phone/SD-C flash memory.
### Screenshots

see attached file
### Device info

**Device:** Ulefone Power
**Android version:** 5.1
**Signal version:** 3.14.2
The Ulefone has a local VPN installed and uses Signal as default SMS/MMS App.

**Device:** Samsung Galaxy S3 (intl)
**Android version:** Cyanogenmod 13.0-20160312-NIGHTLY-i9300
**Signal version:** 3.14.2
The device does not use Signal as default SMS/MMS App.

**Device:** Apple iPhone 6
**iOS version:** 9.3
**Signal version:** 2.2
### Link to debug log

https://gist.github.com/anonymous/f6d48b7fd0e3d1e10724

**Comment by 2-4601** [comment]
Related: #5118, https://github.com/WhisperSystems/Signal-iOS/issues/1010

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
