### ISSUE TITLE
Emoji at end of line is shown twice

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5385]
### Bug description

This bug occurs to me in WhatsApp, Threema and Signal. But I did not find something with Google until now. I don't know if it can be solved by Signal developers.
### Steps to reproduce
- Open a conversation.
- Type roughly one line of text in the input field.
- Add one emoji (built-in/Apple-iOS, not system-emoji) directly behind the text.
- Add one of the following symbols directly behind the emoji: ) " ' : ; ! ? , / . } ]
- Place the text cursor in the text and play around with adding/deleting some (different sized) letters.

**Actual result:** The emoji is shown twice – one time at the end of the first line and another time at the beginning of the second line. That is especially the case, when the symbol after the emoji does not fit into the line and a line break has to be done behind the emoji.
**Expected result:** The emoji shows only up once.
### Device info 1, reproducible

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.14.2
### Device info 2, reproducible

**Device:** Samsung Galaxy S5
**Android version:** 5.0
~~**Signal version:**~~ tested with WhatsApp
### Device info 3, **not** reproducible

**Device:** Sony Xperia U
**Android version:** 4.4 (CyanogenMod 11)
**Signal version:** 3.15.1

**Comment by 2-4601** [comment]
Reproducible on Nexus 4, stock 5.1.1, Signal 3.15.2.
![cold sweat duplication](https://cloud.githubusercontent.com/assets/174176/14062962/75d4f15e-f3bc-11e5-9b68-2f109b9f309b.gif)

**Comment by qasimchadhar** [comment]
Two emojis are never bad

**Comment by FeuRenard** [comment]
This also happens inside the bubbles.
![screenshot_2016-08-06-16-02-02](https://cloud.githubusercontent.com/assets/16167751/17457175/38794bd8-5bf0-11e6-8289-d4a13278fe5d.png)

**Comment by FeuRenard** [comment]
This issue is not reproducible on Android 6.0.1 with Signal 4.14.9. It probably never was with Android 6.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
