### ISSUE TITLE
Import/export action bar title inconsistent

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5389]
### Bug description

The action bar title in the import/export-view doesn't match the menu entry tapped on, to get to this view. That's inconsistent with the other entries in the conversation list's menu.
### Steps to reproduce
- Open signal.
- Click on the three dots in the top right corner.
- Choose "Import / export".

**Actual result:** The action bar title is "Signal".
**Expected result:** The action bar title matches the chosen menu entry label - "Import / export" here.
### Comment

I appreciate that "Import / export" in the action bar and "import"/"export" on the tabs would be redundant. I suggest renaming the menu entry to "backup" or "data backup" and putting the same label in the action bar.
I would be happy to make a PR to get used to working with the code and contributing. Just let me know your opinion.
### Device info

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.14.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
