### ISSUE TITLE
Trim all conversations now does not trim Archived messages

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#5400]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Message trimming does not apply to archived conversations. Unarchiving conversation does not trigger a message trim. A new message in the thread will cause message trimming to work. This
### Steps to reproduce
- Have more than one message in a conversation thread
- Have some message threads archived
- Enable "Delete old messages"
- Set Conversation length limit to 1
- Choose 'Trim all conversations now'
- Archived conversations remain unchanged.
- Unarchive a conversation, remains unchanged.
- Receive or send a message in an 'archived' thread (even if it has been moved back to unarchived) and messages are trimmed

**Actual result:** All unarchived conversations (inclusive of media) are deleted up to conversation length limit. All archived conversations remain unchanged
**Expected result:** All unarchived and archived conversations are trimmed. Other option is to rename Chats and Media setting to "Trim unarchived conversations now" and change wording in pop up to "Delete unarchived messages now"
### Screenshots

n/a
### Device info

**Device:** Motorola XT1097
**Android version:** 5.1 
**Signal version:** 3.14.2
### Link to debug log

1. https://gist.github.com/anonymous/3ece5f60b247bbdd5fa9181de23531cf
2. https://gist.github.com/anonymous/1a57fa35fb38871aea9e7aa92ecfa769

Related as a quick work around to request in https://github.com/WhisperSystems/Signal-Android/issues/5176

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
