### ISSUE TITLE
Implement group chat @user "highlight" notification feature

### ISSUE THREAD

**Issue by lightraven24** [signalapp/Signal-Android#5401]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Telegram implements a neat feature when a person can be in a group chat, and mute all notifications for that chat, but messages that have a @persons_name in them.

This is useful for noisy group chats where a person doesn't want to be notified every time something happens in the chat.

**Comment by sedrubal** [comment]
Whatsapp has implemented this, too:

![mention](https://cloud.githubusercontent.com/assets/5571650/18687361/07838620-7f80-11e6-95a3-db24481a6824.png)

**Comment by THPubs** [comment]
Any updates guys?

**Comment by haffenloher** [comment]
@THPubs please read the [Contributing Guidelines](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues) before posting here again.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
