### ISSUE TITLE
InviteActivity does not adapt to dark theme

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5407]
### Bug description

The view where you can invite friends to Signal is not responsive to the selected theme. Especially the view to select contacts to invite looks out of place in dark theme.
### Steps to reproduce
- Open Signal (dark theme selected)
- Tap the three dots in the top right corner
- Choose "Invite friends"
- Tap on "Send SMS"

**Actual result:** The ActionBar is blue and the entering contact selection is definitely light themed.
**Expected result:** The ActionBar is black and the entering contact selection is dark themed.
### Device info

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.15.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
