### ISSUE TITLE
8704daa breaks building on windows

### ISSUE THREAD

**Issue by bottiger** [signalapp/Signal-Android#5418]
Most windows users will not have git in their environmental path variable due to the way most git is installed, and used, on windows. Furthermore the git executable is called "git.exe" and not just "git"

8704daa tries to integrate a timestamp from git into the build process. I've looked into integrating information from git into the build process for my own app, but I just don't think there is a nice clean way to do it in a cross platform friendly way.

In order to build Signal-Android on windows I modified the build.gradle file like this:

```
    def build_timestamp = System.currentTimeMillis();
    if (!org.gradle.internal.os.OperatingSystem.current().windows) {
        build_timestamp = getLastCommitTimestamp();
    }
    buildConfigField "long", "BUILD_TIMESTAMP", build_timestamp + "L"
```

It would be nice if you also could do something similar.

EDIT: I've made a pull request here: https://github.com/WhisperSystems/Signal-Android/pull/5419

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
