### ISSUE TITLE
Conversation view search will not return SMS-only conversations with no corresponding contact

### ISSUE THREAD

**Issue by robryk** [signalapp/Signal-Android#5428]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I have some conversations with phone numbers that are not in my contacts (e.g. phone number 444 or phone number SWISSCOM, or +14252766197). They have a "#" sign as the contact icon in the conversation view. When I search in the conversation view they never appear. E.g. if I search for "+", I get all conversations with my contacts and only them. If I search for 444, I get nothing.
### Steps to reproduce
- cause an SMS message to be sent to you from an unknown phone number (one that is not in your contacts),
- wait for the message to arrive
- search for the phone number of the originator of that message in conversation view
- notice empty search results

**Actual result:** The message you just received does not appear in search results.
**Expected result:** The message you just received should appear in search results.
### Screenshots

Please request screenshots if you want them (blacking out personal information is time consuming and I don't want to play with it needlessly).
### Device info

**Device:** LGE Nexus 5X (bullhead)
**Android version:** 6.0.1 (2595691, MHC19J)
**Signal version:** Signal 3.15.2
### Link to debug log

https://gist.github.com/d6a6beca2240eaac69fd1821aece3c85

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
