### ISSUE TITLE
Screen Security not working - Lenovo Vibe A7010

### ISSUE THREAD

**Issue by enzolovesbacon** [signalapp/Signal-Android#5441]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

The feature "Screen Security", which prevents screenshots within the app or recents list, doesn't work (screenshot _is_ taken) when the app switcher is triggered for the Android offered by Lenovo on the Vibe A7010 phone (which is slightly customized).

Although, the shortcut for a screenshot will get me correct behaviour ("Couldn't capture screenshot").

Unfortunately, I think they only offer this model in Brazil and another few selected countries (it's a lower end model).

http://shop.lenovo.com/br/pt/smartphones/a-series/a7010/
### Steps to reproduce
- Open Signal
- Tap the app switcher button

**Actual result:** Displays app content (conversations, contact names)
**Expected result:** A blank space in the Signal app window
### Device info

**Device:** Lenovo Vibe A7010
**Android version:** 5.1
**Signal version:** 3.15.2
### Link to debug log

https://gist.github.com/b1877496d5d37713d050552f040fe447

**Comment by 2-4601** [comment]
Could you check out #3172 and confirm that this is a different issue?

**Comment by enzolovesbacon** [comment]
@2-4601 Although it's a very similar issue, his very first paragraph discards my report as a duplicate.

Every time I try to switch context, the contents of my Signal screen is shown in the switcher drawer, whether I locked the screen or not. The only exception is when I try to perform a screenshot manually (Power button + Vol down on my phone), which then gets blocked.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
