### ISSUE TITLE
Please support sending stickers

### ISSUE THREAD

**Issue by rbalint** [signalapp/Signal-Android#5445]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Users can't send stickers to each other using Signal. This is a deal breaker for some users preventing switching to Signal from other messenger apps such as Viber.

Adding a sticker store may also help funding the project.
### Screenshots

![screen-shot-2013-04-16-at-10 57 46-am1](https://cloud.githubusercontent.com/assets/1520835/14586175/55a420be-0490-11e6-915c-d7844febe1de.png)
Ths screenshots are copied from here:
http://www.adweek.com/socialtimes/facebook-updates-iphone-app-with-stickers-and-chat-heads-ipad-gets-new-design/292460

**Comment by rhetr** [comment]
some open source discussions about stickers:

https://wiki.tox.chat/developers/feature_ideas/stickers
https://github.com/qTox/qTox/issues/402
https://github.com/irungentoo/toxcore/issues/1106
https://github.com/Gargron/xmpp-web/issues/3
https://www.stickerstelegram.com/
http://telegramhub.net/

**Comment by Fnatte79** [comment]
I agree, it is a deal breaker for many.
For time being I use both Telegram and Signal but still have a few friends who not seems to wanna change to Signal just because it doesn't support stickers.

**Comment by hermannsblum** [comment]
*push*
I find this THE dealbraker when trying to convince people to switch from telegram to signal.

**Comment by nrizzio** [comment]
This has been implemented in 69d0242574cc68b068afe3a00861e574b176f08b (Giphy support).

**Comment by 2-4601** [comment]
Is the Stickers tab in the Giphy browser the same as the sticker feature requested in this issue? I have really no idea... :thinking:

**Comment by rbalint** [comment]
Thanks for improving Signal, Giphy support is indeed a related addition.
I think to claim this case resolved Signal needs a more user friendly method of sending ''stickers' and on the receiver side the sticker should not be in a bounding box rectangle because it is less nice than Viber's solution.
I also tried sending PNG-s with alpha background and only a black box is shown in the conversation.

**Comment by nrizzio** [comment]
Fixed by 1b44bdc (for sure!)

**Comment by 2-4601** [comment]
I think the original feature request is about adding a drawer for stickers (like the emojis have) and then attaching them directly to the conversation as messages (without the message bubble around them). This is different from the scribble mode where you can add stickers on existing image attachments. But at least there are sticker resources now :)

**Comment by rbalint** [comment]
When I opened the bug I meant making Signal able to send and receive stickers and creating a user experience on par with Messenger/Viber regarding this feature.
I have not tried 1b44bdc yet, thus I can't tell if both parts are done.
I'm OK with closing this bug even if it is only possible but not user friendly to send stickers, I can open a new one for making it easy.

**Comment by rbalint** [comment]
Thank you for working on this feature BTW!

**Comment by 2-4601** [comment]
@rbalint 1b44bdc is in 3.25.3 which is available in the Google Play release.

**Comment by rbalint** [comment]
@2-4601 @nrizzio I have tried 3.25.4 and yes, I the thing implemented is different from what I asked and provided screenshots for.
I suggest reopening this issue but thank you for the implemented scribble mode, this can be useful for some people, too.

**Comment by Tajnymag** [comment]
Awesome feature would be to create your own packs. That way Whisper Systems wouldn't have to come up with their own unique stickers packs. I'm pretty sure there would be enough users crowdsourcing stickers 😄

**Comment by rocurley** [comment]
Not the op, but IMO the [spec for Tox](https://wiki.tox.chat/developers/feature_ideas/stickers) would likely do it. Telegram has a pretty thriving ecosystem of stickers based on this model.

**Comment by FaizKhan5** [comment]
Any updates ?

**Comment by deutrino** [comment]
@rocurley or anyone - are there links to creative commons / open source / libre sticker packs using that or any standard spec?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by alan-signal** [comment]
https://signal.org/blog/make-privacy-stick/
