### ISSUE TITLE
Show size of attachment (before downloading)

### ISSUE THREAD

**Issue by El-Cerdo** [signalapp/Signal-Android#5449]
When you have set the option to download photos and videos manually, you should be able to see the size of an attachment _before_ you decide if you want to download it or not.

In addition the file size could be shown in the file info dialog.

**Comment by ghsrcgh** [comment]
Video size is not written on "download" icon. So you cannot decide do you able to download it by modem or need to wait Wi-Fi. For example, Telegram showing video size on video icon, so it easy to decide (you see the size: is it 1mb or 150mb).

Please fix this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
