### ISSUE TITLE
Problem With Notifications

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#5453]
### Bug description

I am having problems with call and message notifications.

I do not get any notifications when I receive a call.

I only know that I had a call and miss the call if I open the actual chat then there is a message within the chat but no notification of any kind

When I receive messages the only notification I get is the phone vibrates the screen doesn’t light up and the LED lights don’t flash.

This only seems to be happening since I upgraded to android 6.0 and I have checked all of the system notification settings nothing seems to make a difference other messaging apps work correctly.
### Steps to reproduce

It happens whenever I receive a message from anyone.

It also happens when I receive a call.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour) 

I do not receive any notification of a missed call except for if I open up the chat or if the Internet was off and then when it is turned back on then I get a notification.

The only notification I receive for a message is that the phone vibrates and when I unlock the screen I can see a notification.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The phone screen should light up and the phone should vibrate and show the incoming call.

If I get a message the screen should light up and show a notification as well as the LEDs should flash.
### Device info

**Device:**LG G3
**Android version:**6.0
**Signal version:** currently 3.15.2 but it regularly updated
### Link to debug log

https://gist.github.com/dca632146bae573f0a43bdb62197bc28

**Comment by riyapenn** [comment]
Contact support@whispersystems.org and indicate if you are using any third party notifications apps i.e. Light Flow or firewall.

**Comment by mfuhrmann** [comment]
I can confirm an similar issue like that. In my case Signal doesn't bring any notification (vibration, led, sound, push notification). So I always have to open Signal to notice that I have got some messages.

**Comment by 2-4601** [comment]
@mfuhrmann Check out http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by carlhopf** [comment]
This fixed it for me in Cyanogen 13: https://github.com/WhisperSystems/Signal-Android/issues/2703#issuecomment-180308001

**Comment by zero77** [comment]
@carlhopf Thanks, but I've already tried that and it didn't seem to make a difference.
Although I only done this with signal is there another service or app signal uses that I need to do it to as well.

**Comment by slinnky** [comment]
I'm having this issue on my Nexus 6p Android 7.1.1. My phone does not vibrate or make a sound when a call comes though. I only know a call is coming in if I'm looking at my phone and see the screen light up asking me to answer the call. I've looked through the notification settings both within Signal and in the operating system settings and everything is enabled as it should be.

**Comment by jeremymasters** [comment]
@slinnky  The devs need a debug log from right after issues occur to help troubleshoot issues.

**Comment by skymoo** [comment]
I've started seeing this as well, Android O DP4 on a Pixel:
https://gist.github.com/869bc1f76a1d69c15bd9a39229a854c8

**Comment by oittaa** [comment]
I've had the missing notification sound every now and then in the final Android O on a Nexus 5X.

**Comment by roipoussiere** [comment]
Same problem on my Xiamomi Redmi Note 3. I need tout open the app to see thé notifications.

**Comment by dkurzaj** [comment]
Most of the time I get notifications when I receive a new message, but sometimes I don't. I have no idea on which conditions it happens.
My phone is an HTC Desire 530 and a friend of mine has the exact same problem, but with a BLUBOO Picasso.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
