### ISSUE TITLE
Unregistered phone number gets added to group again after re-registering and getting added to group with a new number

### ISSUE THREAD

**Issue by x2k13** [signalapp/Signal-Android#5455]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When a user leaves a group and unregisters his phone number with Signal and re-registers with a new number and gets re-added to the group using the new phone number, the old number will be added again to the group as well if a member of the group still has their old phone number in their contact list (probably merged as one contact) .
### Steps to reproduce
- leave a group
- unregister phone number from Signal via menu
- register a new phone number in Signal
- make someone re-add you and update the group

**Actual result:** 
The new phone number gets added correctly, showing name and number in member list.
The old, unregistered phone number gets added to the group again, just with no name.
Shows as "+1234567890 joined the group", looking up the members of the group, everyone has a name and phone number except the old number, which just has a blank name field.

**Expected result:** 
If someone leaves a group and unregisters a phone number in Signal, even if someone else has the old number and the new number in his contact list (probably merged as one contact) never assign that old, unregistered phone number with the group again, just the new phone number, which is registered.
### Screenshots

none, can't be taken on Android 5.1.1 due to security limitations.
### Device info

Seen on various Android 5.1.1 and iOS 9.3.1 devices
**Signal version:** 3.15.2
### Link to debug log

n/a

**Comment by 2-4601** [comment]
Unable to reproduce with Nexus 4, stock 5.1.1, Signal 13.5.2

1. Mr. T. leaves the group
1. Mr. T. unregisters from Signal
1. Mr. T register a new phone number for Signal
1. I add Mr. T's new number to my existing contact of Mr. T. (the contact has now Mr. T's old and new numbers)
1. I try add Mr. T to the group
 * oops, I can't find Mr. T. from the list of contacts to add (both old and new numbers are missing)
 * I try to manually add Mr. T's old number: Signal says that number is not a Signal user
 * I try to manually add Mr. T's new number: Signal crashes¹ 
1. I refresh my contact list
1. I see Mr. T's new number as a Signal contact
1. I add Mr. T to the group
1. Everything works as expected

- - - - - - - - - -

¹ ) https://gist.github.com/anonymous/01700d15808e39f6e4086141437d6dc3
```
--------- beginning of crash
E/AndroidRuntime( 3990): FATAL EXCEPTION: main
E/AndroidRuntime( 3990): Process: org.thoughtcrime.securesms, PID: 3990
E/AndroidRuntime( 3990): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { cmp=org.thoughtcrime.securesms/.PushContactSelectionActivity (has extras) }} to activity {org.thoughtcrime.securesms/org.thoughtcrime.securesms.GroupCreateActivity}: java.lang.IllegalArgumentException: YOu must call this method on a background thread
E/AndroidRuntime( 3990): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
E/AndroidRuntime( 3990): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
E/AndroidRuntime( 3990): 	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
E/AndroidRuntime( 3990): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
E/AndroidRuntime( 3990): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3990): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3990): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 3990): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3990): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3990): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 3990): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 3990): Caused by: java.lang.IllegalArgumentException: YOu must call this method on a background thread
E/AndroidRuntime( 3990): 	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:144)
E/AndroidRuntime( 3990): 	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:169)
E/AndroidRuntime( 3990): 	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.contacts.avatars.ContactPhotoFactory.getContactPhoto(ContactPhotoFactory.java:55)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.contacts.avatars.ContactPhotoFactory.getContactPhoto(ContactPhotoFactory.java:42)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getIndividualRecipientDetails(RecipientProvider.java:143)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipientDetailsSync(RecipientProvider.java:129)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipient(RecipientProvider.java:82)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipients(RecipientProvider.java:96)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientFactory.getRecipientsForIds(RecipientFactory.java:106)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.recipients.RecipientFactory.getRecipientsFromString(RecipientFactory.java:81)
E/AndroidRuntime( 3990): 	at org.thoughtcrime.securesms.GroupCreateActivity.onActivityResult(GroupCreateActivity.java:313)
E/AndroidRuntime( 3990): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
E/AndroidRuntime( 3990): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
E/AndroidRuntime( 3990): 	... 10 more
I/Process ( 3990): Sending signal. PID: 3990 SIG: 9
```

**Comment by x2k13** [comment]
Looks like this issue is more or less iOS related, then. Apparently someone in that specific group is using iOS 9.3.1 and has the contact merged like described. It's actually sort of weird, the person definately left the group, then un-registered from Signal. In addition, Signal was completely uninstalled on that specific device and the device shutdown, number wasn't reused at all, basically it's offline now. 

So how come the number gets re-added to the group?

Anyway, it would be nice to be able to just delete members from the member's list, which we can't at the moment.

**Comment by 2-4601** [comment]
Deleting members from a group is basically #828.
If iOS can add unregistered contacts to groups, could you open an issue for that at the [iOS tracker](https://github.com/WhisperSystems/Signal-iOS/issues)?

**Comment by tx3eh8IUD1** [comment]
The problem occurred for me as well (see #2408 ). 

However, for me **the user has not left the group before de-registering / uinstalling**.

**Comment by Trolldemorted** [comment]
@2-4601 do you know which way is the easiest to reproduce the crash? Or does the calling of getContactPhoto on the wrong thread occur only in this specific scenario?

**Comment by 2-4601** [comment]
@Trolldemorted Can't remember anything about it :)
The crash seems to have been just collateral damage while trying to reproduce the original issue (which is not a crash)

**Comment by jamiexy** [comment]
Just ran into this issue on Android 7.0.

I left the group, unlinked Signal desktop, and unregistered my phone number from Signal. I then registered a new number and requested to be added back to the group. Before being added to the group, I could see that the old number was still listed as a member of the group. When I am added, the old number is still listed as a member, just without a name. The old number cannot be removed or deleted.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
