### ISSUE TITLE
Sending a sms to a special number like 9990033612345678 failed

### ISSUE THREAD

**Issue by kewix** [signalapp/Signal-Android#5456]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Signal is not able to send a text message (SMS) to a special phone number like 9990033612345678. 

This is a special prefix number used by French operator Bouygues Telecom with option B.Duo. 
B.Duo allow you to have a second line (virtual line) on the same sim card but you have to use prefix 999 to use the second number. When Sending a message with a prefix 999 it will actually send it with your regular number to your operator but the receiver will see the virtual number from your second line (this is also working for calls).
I don't know if this system exists in others countries, but this is very useful when you use ad service (like craiglist) and don't want to display your original number. 
More info here : https://www.services.bouyguestelecom.fr/communication/b-duo
### Steps to reproduce
- receive a sms or send to a number like 9990033612345678
- enter text
- send message

**Actual result:** Message failed because prefix is prefixed again with country prefix (+33 in my case), it creates a number like +339990033612345678 completely nonsense for the operator
**Expected result:** Message success with no autoprefix before the 999
### Device info

**Device:** One Plus One
**Android version:** 5.1.1
**Signal version:** 3.15.2
### Link to debug log

https://gist.github.com/anonymous/e37c46c101f9d365d5f7800887be12f6

Thanks for your help, love using Signal :)

**Comment by olemd** [comment]
Same with long special numbers in Norway. But apparently Signal prepends +47 on the incomming message but only uses 47 (with no +) when replying. The correct behaviour would be not to prepend +47/47 - relevant numbers include 05123xxxxx, 08321xxxx, and 2252xxxx

I suspect prepending the country-code to "weirdly long" numbers are always wrong and should only be done on "normal" numbers. Dedicated short numbers, for instance 2115 does not exhibit this problem.

Unfortunately I don't have a relevant debug-log available.

**Comment by Ensnared** [comment]
Can confirm this issue, special long numbers that are mostly used for automatically sent messages that required you to reply with a code for confirmation (e.g. to confirm a bid when bidding on a house or property) can not be sent to using Signal.

**Comment by hernil** [comment]
I have the same issue with my five digit phone number of my Norwegian bank.

**Comment by pwlbc** [comment]
I am not able to send a SMS to 19872 in Poland.
Signal automatically changes the number to +4819872 which result in failure to send SMS.
The number has to be 19872 without country code.
Please fix this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
