### ISSUE TITLE
Sending attachments sometimes fails without explanation

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#5463]
One in ten times sending a message with an attachment silently fails. I add the video, all is fine and dandy and when I press send nothing ever happens, and no file is ever sent. Same thing sometimes happens for voice clips.

https://gist.github.com/anonymous/1335db821f0300b4a8da278d581e234a
Also, out of curiosity, what does
"04-26 01:40:06.963 10490 10528 W RecipientPreferenceDatabase: Muted until: 0"
mean?

I would post more logs but for whatever reason I get a 404 page not found whenever I create a log and I click the link to it in the app. Oh well...

**Comment by 2-4601** [comment]
Do you mean using the same attachment or with different attachments?
For example:
If you attach `i.snort.coke.mp4` ten times, it will fail once.
or
If you attach ten different videos, it always fails with a specific video?

How did you capture the attachments? Did you share them to Signal from an external app?

**Comment by Dyras** [comment]
Different attachments.

I've found no correlation between how I send the attachments to my Signal contact and whether or not it appears in the chat after I send it. I send voice clips by sharing it from Easy Voice Recorder and I add videos from inside of Signal. I've had problems with both.

**Comment by jgardner04** [comment]
I simply get an error that says documents has failed.  It happens for me every time I try to attache an image or video.

**Comment by riyapenn** [comment]
@jgardner04 please share your attachment file type and steps with support@whispersystems.org

**Comment by jgardner04** [comment]
@riyapenn I don't even get that far.  When it tries to open the document library I get an error saying, "Unfortunately Documents has stopped"  I captured a log file and uploaded it [here](https://gist.github.com/anonymous/8d52fdeceb697763ff72d6409cef301d).  I have also signed up for the Beta to see if the issue is present there but have yet to receive the download.  I am unable to capture a screenshot as it will not capture it.  It only allows me to grab the screen underneath.

**Comment by Dyras** [comment]
@jgardner04 I don't think you and I have the same problem

**Comment by jgardner04** [comment]
@Dyras, sorry I did not mean to hijack the thread, I will work on a different issue.  Thanks for letting me know.

**Comment by peterpanondrugs** [comment]
Same: hope this helps.

When i send from Quickpic app out of my gallery to 


W/PushReceivedJob( 5115): Received receipt: (XXXXX, 1463739734918)
W/MmsSmsDatabase( 5115): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 46) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 46) ORDER BY date_received DESC LIMIT 1)
W/EarlyReceiptCache( 5115): org.thoughtcrime.securesms.database.EarlyReceiptCache@36c8b5cb
W/EarlyReceiptCache( 5115): Early receipt: 1463739734918,+***********36
W/MessageRetrievalService( 5115): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService( 5115): Reading message...
W/WebSocketConnection( 5115): Sending keep alive...
W/OkHttpClientWrapper( 5115): onMessage: BINARY
W/WebSocketConnection( 5115): WSC onMessage()
W/WebSocketConnection( 5115): Message Type: 2
W/MessageRetrievalService( 5115): Application level read timeout...
W/MessageRetrievalService( 5115): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService( 5115): Reading message...
W/InputEventReceiver( 5115): Attempted to finish an input event but the input event receiver has already been disposed.
W/KeyboardAwareLinearLayout( 5115): onKeyboardClose()
W/ThumbnailView( 5115): Not re-loading slide content://org.thoughtcrime.securesms/part/1463739147940/1205
W/ThumbnailView( 5115): loading part with id content://org.thoughtcrime.securesms/part/1463738703552/1204, progress 0
W/ConversationActivity( 5115): onBackPressed()
W/PassphraseRequiredActionBarActivity( 5115): onPause()
W/KeyCachingService( 5115): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 5115): Decrementing activity count...
W/MessageRetrievalService( 5115): Active Count: 0
W/PassphraseRequiredActionBarActivity( 5115): onResume()
W/KeyCachingService( 5115): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 5115): Incrementing activity count...
W/MessageRetrievalService( 5115): Active Count: 1
W/AttachmentDatabase( 5115): getThumbnailStream((row id: 1206, unique ID: 1463739164164))
I/Timeline( 5115): Timeline: Activity_idle id: android.os.BinderProxy@2f368cab time:51687519
W/PassphraseRequiredActionBarActivity( 5115): onDestroy()
W/MmsSmsDatabase( 5115): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 58) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 58) ORDER BY date_received DESC LIMIT 1)
I/Timeline( 5115): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:51691945
W/PassphraseRequiredActionBarActivity( 5115): onPause()
W/KeyCachingService( 5115): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 5115): Decrementing activity count...
W/MessageRetrievalService( 5115): Active Count: 0
W/PassphraseRequiredActionBarActivity( 5115): onCreate(null)
W/ExperienceUpgradeActivity( 5115): getExperienceUpgrade(179)
W/PassphraseRequiredActionBarActivity( 5115): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 5115): initializeClearKeyReceiver()
W/PassphraseRequiredActionBarActivity( 5115): onResume()
W/KeyCachingService( 5115): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 5115): Incrementing activity count...
W/MessageRetrievalService( 5115): Active Count: 1
I/Timeline( 5115): Timeline: Activity_idle id: android.os.BinderProxy@391e3ebe time:51692777
I/Timeline( 5115): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:51695312
W/PassphraseRequiredActionBarActivity( 5115): onPause()
W/KeyCachingService( 5115): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 5115): Decrementing activity count...
W/MessageRetrievalService( 5115): Active Count: 0
I/Choreographer( 5115): Skipped 33 frames!  The application may be doing too much work on its main thread.

**Comment by Dyras** [comment]
Two more logs
https://gist.github.com/anonymous/158359ebae21895a51b5b6207bcb4ec7
https://gist.github.com/anonymous/9a38ef90290e06099d9a8a0bf4a9c8cd

**Comment by peterpanondrugs** [comment]
Sending attachment kinda always fails for videos when I try to send it from quickpick gallery. 
Images mostly work.
Person gets then sometimes empty bubbles with double check mark.

https://gist.github.com/anonymous/0f3cfeaeaed76c78d7d6184afc8b43ed

**Comment by Dyras** [comment]
https://gist.github.com/anonymous/07868eedd503eff8c18f189d47a719ed
Still happening for me

**Comment by galopeian1** [comment]
I have run into this issue sending attachments to non-signal users via MMS.

**Comment by gordon-morehouse** [comment]
I also use Quickpic and it's likely a problem with the videos or something else, not Quickpic. So far I believe it's related to size and/or codec. I've never had problems with Quickpic sending short or small videos which are H264/AAC, but if a H264/AAC video is large enough, it doesn't work. I haven't systematically tried other codecs yet but so far I suspect that can also be an issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
