### ISSUE TITLE
Non-black dark theme

### ISSUE THREAD

**Issue by Deedasmi** [signalapp/Signal-Android#5470]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---

Very interested in this application, but have a bit of concern with the themes. My eyes are horrible, and light themes wear my eyes out. However, white text on black screens is pretty much proven to be worse for the eyes than light themes. Better to use one of the following:
- Solarized: http://ethanschoonover.com/solarized
- Dark on light on dark: https://imgur.com/mW8EDxr

**Comment by RiseT** [comment]
Agreed. It's all about contrast, e. g. text color vs. background color. If it's too low (e. g. dark gray on black), it's hard to decipher the text, if it's to high (e. g. white on black), your eyes will tire very quickly.
The present dark theme is not optimal in that regard.

**Comment by FeuRenard** [comment]
Black is ideal in regard of power consumption with OLED displays.

**Comment by Deedasmi** [comment]
I think eye health is worth a couple minutes off an 8+ hour battery life.

**Comment by RiseT** [comment]
Take a look at the images of [this](https://www.quora.com/Are-dark-themes-for-IDEs-and-code-editors-good-for-the-eyes) link for direct comparison between high contrast dark & light themes and a low contrast one.

**Comment by vdcbb** [comment]
I'm very much in support of Deedasmi's proposal. I hate all these light themes everywhere. And white on block is equally as bad in a different way. GNOME Shell's dark theme is very nice.

**Comment by smichel17** [comment]
I believe that a light yellow on blue-green is the best on the eyes. Here's lorem ipsum in my terminal:

![screenshot from 2016-11-25 12-47-11](https://cloud.githubusercontent.com/assets/6563664/20632677/55fc5b5e-b30d-11e6-8adb-496f297df4b5.png)

That said, it's ugly as heck until you get used to it.

IMO, the best option would be to offer 3 themes: Light, Dark, and Black (OLED).

Light and Black (OLED) would be the current themes, and Dark would be a dark theme with lower contrast.

'Night' is an alternative name to 'Black'.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
