### ISSUE TITLE
SMS messages before "See full conversation" are not exported

### ISSUE THREAD

**Issue by Anonymous0112358** [signalapp/Signal-Android#5473]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In the very big conversation, all sms are not charged, when you scroll up in the conversation, "See Full Conversation" apparead and load all sms's conversation. But you exporting SMS, this SMS not charged is not exporting in the XML.
### Steps to reproduce

-Export SMS
-Check XML or restore backup 
-Only new sms are present in the XML, not older sms.
### Screenshots

This SMS: 2 fevr. 2014 19:54 is present in XML
![2016-05-01_23 31 45 1](https://cloud.githubusercontent.com/assets/6732385/14944516/d86c56cc-0ff5-11e6-92c0-58a1081c6312.jpg)
But this SMS: 2 fevr. 2014 19:53 is not present in XML
![2016-05-01_23 34 42 1](https://cloud.githubusercontent.com/assets/6732385/14944529/531b9fe0-0ff6-11e6-99f6-70b3ff8bd380.jpg)
### Device info

Samsung Galaxy Note 4 
Android 5.1.1
Signal 3.15.2

**Comment by Anonymous0112358** [comment]
Hello , how to know if this bug is fixed ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
