### ISSUE TITLE
I can't message one contact. The messages just keep loading

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#5490]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Sending messages to ONE contact simply isn't possible. It just keeps loading and loading and loading and....
### Steps to reproduce

I have absolutely no idea to be honest. However, yesterday I experienced WiFi problems at home which caused Signal to stop working. This was the case on both my phone and my mom's phone. However, the internet problem is fixed now and we can write to each other, but there's one contact I can't write to.

**Actual result:** 
The message is forever stuck with "..." beneath it. This never changes. It's as if the phone thinks there's no internet whatsoever. Interestingly enough I can still receive messages from this contact, I just can't respond.
**Expected result:** 
The message should send, of course.
### Device info

Device  : motorola MotoG3 (osprey_reteu)
Android : 6.0.1 (33, MPI24.107-55)
Memory  : 37M (1.96% free, 96M max)
Memclass: 96, low-mem device
OS Host : ilclbld28
App     : Signal 3.15.2
### Link to debug log

https://gist.github.com/anonymous/c7d07534ca38c905ce41f47ad3ac4543

Things I've tried so far:
Remove the conversation with the bugged contact - didn't work
Restart the phone - didn't work
Leave the phone on for hours - didn't work
Weep silently in the dark - didn't work

Related: https://github.com/WhisperSystems/Signal-Android/issues/5484

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
