### ISSUE TITLE
Display Group icons large when touching on it

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#5496]
### Bug/Feature Request description

In WhatsApp one can view the group logo in full screen after one has touched it. Then you're able to share or save it. It'd be nice if one can do the same in Signal in some way...
### Screenshots

![WhatsApp Example](https://cloud.githubusercontent.com/assets/5571650/15270605/dcb8ce60-1a25-11e6-83cb-8eb06533f435.gif)

**Comment by 2-4601** [comment]
You can view it in _All images_. Though only for the sender because #3045.

**Comment by sedrubal** [comment]
Ah ok. Is it possible to add a "shortcut" that allows touching the group icon in conversations list and in groups detail view to get to the group image detail view?

**Comment by FeuRenard** [comment]
When the icon is displayed in large, there should be a possibility to export/save it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
