### ISSUE TITLE
Sending a picture through MMS causes com.android.phone to crash

### ISSUE THREAD

**Issue by Lennylord** [signalapp/Signal-Android#5499]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Every time I send a picture through MMS, Signal _seems_ to have crashed the process com.android.phone
### Steps to reproduce
- Open Signal
- Send party a picture over MMS with established connection (does not require mobile data to be on, but needs a connection)

Issue did not resolve after clearing Signal's cache and restarting and hard restarting the phone

**Actual result:** A dialog stating "Unfortunately, the process com.android.phone has stopped." pops up and phone un-detects SIM card

**Expected result:** Picture should send through and other person should see the image.
### Screenshots

![2016_05_17_18 38 57](https://cloud.githubusercontent.com/assets/19417931/15342505/95cdd6d6-1c63-11e6-926e-71ef9d68e92f.png)
### Device info

**Device:** Samsung SM-G930D
**Android version:** 6.0.1
**Signal version:** 3.15.2
### Link to debug log

https://gist.github.com/anonymous/a283c5400a8a8189b4375036880abd91

**Comment by tyndallm** [comment]
I am still experiencing this issue on the latest Signal, also using a Samsung device, my info:

**Device**: Samsung SM-G920F
**Android version**: 6.0.1
**Signal version**: 3.25.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
