### ISSUE TITLE
Reinstall after Software-Upgrade - SMS/Call verification failed

### ISSUE THREAD

**Issue by lukesky333** [signalapp/Signal-Android#5500]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Reinstall after Software-Upgrade - SMS/Call verification failed
### Steps to reproduce
- installed a new ROM on my phone (CM13 on Samsung Galaxy S5)
- installed Signal
- started Signal and inserted my phone number
- trying the SMS verification -> failed
- trying the call verification -> failed

**Actual result:** I tried everything to reinstall Signal after ROM-Upgrade, but the verification failed everytime
**Expected result:** Signal should be up and running...
### Device info

**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** 3.15.2

**Comment by 2-4601** [comment]
Which country (phone number)?
Which format did you use when you entered your number? +12345678?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
