### ISSUE TITLE
Group MMS timestamp delayed by locked signal app

### ISSUE THREAD

**Issue by nikipound** [signalapp/Signal-Android#5502]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When I get a group text message in MMS form while signal is locked, it waits to download until signal is unlocked, then appears with a timestamp for time MMS was downloaded, not time sent. 
### Steps to reproduce
- set signal to lock with passphrase
- let it lock
- receive MMS messages in group text
- wait for minutes to hours before unlocking signal

**Actual result:** Text messages are received first in individual conversations, then downloaded, then relocate to the group text. Time stamp reads "now" instead of actual time received. 

**Expected result:** Messages load in group text conversation with the timestamp matching the time sent. 
### Screenshots

Sorry, no screenshot as of now. 
### Device info

**Device:** Droid Turbo
**Android version:** 5.1
**Signal version:** 3.15.2
### Link to debug log

https://gist.github.com/5193599eb710422e3ed8c4581d0e3b3c

Related: #1277 (closed 1 year ago, no solution listed)

**Comment by nikipound** [comment]
In description, I mean timestamp corresponds to time at which MMS was downloaded (after unlocking app), not time at which my phone received notification that an MMS was available.

**Comment by nikipound** [comment]
Can't seem to get a screenshot, and I suspect it's being denied by Signal itself.

**Comment by nikipound** [comment]
Other note: Sometimes individual conversations will be highlighted as having unread messages after the message was downloaded and moved to the group text.

**Comment by johanw666** [comment]
If you want to make a screenshot you can (temporary if you wish) enable screenshots in Settings - Privacy - Screen security.

**Comment by nikipound** [comment]
Just wanted to put in an update on this: The issue still persists, although I haven't seen messages appear out of order in a while, which is nice. I've got a couple screenshots as well. 

## Device Info
**Device:** Droid Turbo
**Android Version:** 6.0.1
**Signal Version:** 4.14.9

![signal-mms](https://user-images.githubusercontent.com/12263574/34445884-763a1f54-ec9c-11e7-82a5-c8543dd2dcae.jpg)
![signal-moreinfo-1](https://user-images.githubusercontent.com/12263574/34445886-76784b80-ec9c-11e7-8145-b9a1fa23744c.jpg)
![signal-moreinfo-2](https://user-images.githubusercontent.com/12263574/34445885-7659bb3e-ec9c-11e7-8951-1a8ce21089c1.jpg)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
