### ISSUE TITLE
Priority mode for starred contacts ignored for calls

### ISSUE THREAD

**Issue by kwlg** [signalapp/Signal-Android#5503]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

The priority mode in Marshmallow for starred contacts works as expected for messages but is ignored for calls. Thus, if I have priority mode enabled and a starred contact sends me a message, my notification signal is played and the phone vibrates as expected. However, if the same contact calls me via Signal, no sound is played and there is no vibration.
### Steps to reproduce
- Mark a contact as starred in the Contacts app.
- Change the behaviour of priority mode so that only starred contacts get through. In the settings of Android:
  - Settings -> Sound & notification -> Do not disturb -> Priority only allows.
  - Change "Messages" and "Calls" to _From starred contacts only_
- Enable priority mode
- Have the starred contact call you and message you via Signal

**Actual result:**
- For messages
  - Notification signal is played and vibration is felt when the starred contact sends a message via Signal
- For calls
  - Ringtone is **not** played and vibration is **not** felt when the starred contact calls via Signal

**Expected result:**
- For messages
  - Notification signal is played and vibration is felt when the starred contact sends a message via Signal
- For calls
  - Ringtone is played and vibration is felt when the starred contact calls via Signal
### Device info

**Device:** Google Nexus 5X
**Android version:** 6.0.1 (Google's official build)
**Signal version:** 3.15.2
### App state
- All app permissions allowed in Marshmallow's permissions settings
- Signal messages and calls registered
- SMS enabled

**Comment by cascheberg** [comment]
I think this is an Android limitation. Signal uses a regular `MediaPlayer` to play the sound, which is muted automatically. Notifications instead are handled by the Android system. Also, the Android API for priority mode is almost nonexistent.

**Comment by luisvd** [comment]
I have a similar problem and it is related to the same issue.

The contact has a custom ringtone. **The default sound for calls is vibrate.**

If the contact calls on regular line the ringtone will work, **if the contact uses signal for a call the phone will vibrate using the default settings.**

_Apparently signal does not follow the contact ringtone settings therefore the do not disturb settings will not work._

Possible solutions:

- Incorporate the call/messages notifications with the native android
- **A possible workaround would be selecting custom ringtones per contact just like notifications.**

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
