### ISSUE TITLE
Send Message to Network

### ISSUE THREAD

**Issue by ghost1372** [signalapp/Signal-Android#5508]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In our network carrier (MTN Irancell) when SIM card charging is over,Messages will be delivered to the contact but A message will be sent to the contact from network (MTN Irancell) , contact to see the message from user  must respond to a message from Network (By sending numbers to network message for allowing Deductible expenses )

but when i replay to network message and send numbers signal give me error and message not send.
my friend number is : **+98937XXXXXXX**
when he send me message and his charge is over MTN send me message and say to me you have a message from your friend but his charge is over do you want pay her message cost? if yes please replay 5 to this message.
MTN number that send me message is : 7040**9371239874**
but when i replay 5 ,message not send
when i use a classic phone (Nokia 1100 and other classic) this feature work perfect.
please fix this bug or add this feature. i love signal and its better.
### Device info

**Device:** Galaxy s6 G920P
**Android version:** 5.1.1
**Signal version:** 3.15.2

**Comment by 2-4601** [comment]
How does Signal display the number for the MTN number `70409371239874`?
I mean if you open that conversation, what does the number in the top bar look like?

Related #5456, #4853, etc.

**Comment by Dyras** [comment]
Could you show some pictures?

**Comment by ghost1372** [comment]
![photo_2016-05-24_14-37-21](https://cloud.githubusercontent.com/assets/9213496/15500251/2d803ce0-21bd-11e6-8158-218114f2e0a7.jpg)

**Comment by Dyras** [comment]
Could you try sending him a text in an SMS app that isn't Signal?

**Comment by ghost1372** [comment]
its work perfect on Samsung Stock SMS app.
![photo_2016-05-24_14-54-55](https://cloud.githubusercontent.com/assets/9213496/15500793/9a93da6a-21bf-11e6-990a-10d7828ce6d5.jpg)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
