### ISSUE TITLE
Signal does not decrypt message with unknown key

### ISSUE THREAD

**Issue by mittwinter** [signalapp/Signal-Android#5512]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Apparently, Signal received a message with an unknown identity key here. Instead of the actual message, it shows this message instead, with a key icon on the right side of it:

```
Received message with unknown identity key. Tap to process and display.
```

However, tapping that message has no effect. Also long-tapping the message and selecting "Message details" and then tapping the message has no effect.

As a side effect, the user details at that time showed no key for the user. Resetting the secure session seemed to work but had no effect. Only after sending a first message to the contact, the key was shown in the details again.

Exchanging messages works now, but the one affected message above can still not be decrypted.

I also tried restarting signal, rebooting the device, which also included re-entering the Signal passphrase.
### Steps to reproduce
- see description above, not reproducible with new messages at the moment

**Actual result:** Message cannot be decrypted, even after tapping the message as stated
**Expected result:** Should be able to decrypt the message
### Screenshots

The cited message above is shown. I can provide screenshots if needed.
### Device info

**Device:** Sony Xperia Z3 Compact
**Android version:** 5.1.1
**Signal version:** 3.15.2
### Link to debug log

I also can provide the debug log if requested, however I'm currently not sure if it would be helpful to provide it directly after, e. g. the tapping of the message does not work. Let me know if the log would help here.

**Comment by johanw666** [comment]
I'm not sure what exactly happened (maybe the user had just registered and sent the message before your phone had updated the contacts?) but I doubt this can be restored at this point. I doubt the decryption key exists anymore. Since it works now, I think the only option is to ask the sender to resend the message.

**Comment by mittwinter** [comment]
Thanks for the reply!

I think that I am able to share some more information now, but I'm not sure about the technical background. However, maybe it helps somehow: So the message was about 6 weeks old but somehow my Signal received it just yesterday. So it may very well be, that the other user switched keys in between. However, he is not sure if he did.
The other interesting thing is that I also use Signal Desktop paired with my Signal on Android (of course), and there I could click at the message details, accept the new key and the message could be successfully decrypted.

At last, it might even be helpful for future instances of this behaviour to communicate in Signal on Android that a message might no longer be decrypted, e. g. because the decryption key is no longer existing as you said - instead of showing the kind of misleading message I reported in my first post.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
