### ISSUE TITLE
MMS not working in Signal, working in stock app, APN correctly configured, Flyme OS

### ISSUE THREAD

**Issue by oscarascal** [signalapp/Signal-Android#5516]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I can't receive or send MMS through Signal
### Steps to reproduce
- Just take a photo and send it to someone, it will fail

**Actual result:** I get an error notification, and no matter how much I try it will fail
**Expected result:** The MMS should just go and my friend is supposed to receive it (or me to be able to receive it)
**What I have tried:** I've reentered my APN dozens of times, didn't work. I've tried restarting the phone, didn't work. I've tried with the **stock app : MMS worked**. I've tried enabling/disabling Wi-Fi and data, didn't work. I've activated media auto-download while roaming on every connection, didn't work. I've followed each step of http://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do- , didn't work.
### Screenshots

Funny thing, the Signal app is the only app in which I can't take a screenshot. Does this need a new bug report ?
Anyway, it's just a "Some issues need your attention" dialog, with the image, the recipient, "Failed to send" and a resend button.
### Device info

**Device:** Meizu M2 Note
**Android version:** 5.1 (1449657555, Flyme OS 4.5.4.2I)
**Signal version:** Signal 3.16.0
### Link to debug log

https://gist.github.com/anonymous/e932d01d3cb6ccd74cca1c7f21872d92

**Comment by peterpanondrugs** [comment]
Just FYI. Go to settings / privacy and disable "screen security" to take a screenshot.

**Comment by KarolTrzeszczkowski** [comment]
I couldn't reproduce on Meizu m2 note with flyme OS 5.1.6.0IN, Signal 3.16.0 
I updated Flyme yesterday. Earlyer i've had Flyme 4.5.4.2I and i dont remember any errors.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
