### ISSUE TITLE
Android app stopped working 3 days after porting my phone number, desktop still working fine

### ISSUE THREAD

**Issue by dysinger** [signalapp/Signal-Android#5518]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I ported my AT&T wireless number to a VoIP provider (flowroute).  I expected Signal to keep working over the internet.  What I experienced is that 3 full days after my number was ported, Signal messages stopped coming to my Android phone. I also get the wiggling dots when I send someone a message (meaning it's not going to show up). My linked Desktop account continues to work just fine. (?!)
### Steps to reproduce
- use my android phone & fail
- use my desktop chrome application & win

**Actual result:**
Can't send or receive messages to contacts that I have sent/received messages to in the past from this phone.
**Expected result:** 
That I can send & receive messages over wifi.
### Screenshots

Can't take a screenshot of my Android app (won't let me).
### Device info

**Device:** Nexus 5 Android Phone
**Android version:** 6 (latest)
**Signal version:** latest

**Comment by dysinger** [comment]
Happy to provide any other information needed.  I miss having my Android Signal working!

**Comment by moxie0** [comment]
can't do anything without a debug log

**Comment by dysinger** [comment]
Ah sorry

I would think this was because I dropped my wireless provider in favor of a VoIP provider (I ported the number & it's still active & used on my phone).  But then again it stopped working on May 30th (my number was ported on the May 26th.)

Also I disabled my Android Phone & Messaging apps because I wasn't using them. That may have caused a hiccup with Signal. I didn't think that it would.  It doesn't matter if I disable it or enable it. Signal still isn't working.

https://gist.github.com/ce64bdb17757297256e0a6fffd95ce5b

**Comment by dysinger** [comment]
I tired "resetting secure connection" but not being able to send or receive at all to anyone from my phone persists.  Every outgoing message has the 3 dots on indicating it's not sent & every incoming message says "decrypting..." forever.

**Comment by moxie0** [comment]
What is a "voip provider?" If your device reports that there is no network access / service, then Signal won't attempt to make a network connections and will just queue the message (pending state with the bouncing dots) until your device reports that the network is available.

**Comment by dysinger** [comment]
I ported my number to Flowroute.com - they are a carrier that provides SIP trunking.  Android even has built in support for SIP accounts.

It worked for multiple days over wifi without having AT&T in the mix. My guess would be that the number port isn't the issue. I was just listing all the changes that have happened in the last week to 10 days

**Comment by dysinger** [comment]
I've tried every single combination of enable SMS/MMS, disable SMS/MMS, enable/disable Android Phone/Messanger, that I can toggle. Nothing fixes this.  I see every single message that I sent from my desktop as "Decrypting, please wait..." and every single message I send from the phone shows the dribbling dots.

**Comment by dysinger** [comment]
I also tried unchecking/checking mobile data & roaming data checkboxes (so only wifi is left).  Nothing helps.

**Comment by dysinger** [comment]
Interesting: my phone says my desktop linked chromium app was last active on May 29 but I have been using it exclusively since my phone stopped working (up to & including today, June 6th).  I still see all the messages that I send with my desktop on my phone as "Decrypting, please wait"

**Comment by dysinger** [comment]
Is it the case that, even though my phone number didn't change, if I don't have a SIM card inserted with a data plan that Signal Android is just not going to work at all (even on wifi) anymore?

**Comment by nrizzio** [comment]
Signal needs internet access (either data or WiFi) to work. Can you open a Web browser and type in the address https://textsecure-service.whispersystems.org from the phone, and after ignoring the certificate error, get a 404 file not found message from the webpage?

**Comment by dysinger** [comment]
I still have wifi on the device. This never stopped working. I still receive new messages on Signal too. They are just stuck and wont decrypt.  New messages I try to send dribble dots forever.

I was thinking about this more. My son went to hawaii a few days after we dropped our LTE plan. His Signal (on iPhone) continues to work fine. I don't think its a number port or network access issue.

I can, in fact, navigate to that address on my phone. I can bypass the warning and get a 404.

**Comment by dysinger** [comment]
I'm just going to have to dive into the source myself I guess. I'm really trying hard to not uninstall/reinstall as I'd probably lose everything (my chats & my keys)

**Comment by haffenloher** [comment]
>  Every outgoing message has the 3 dots on indicating it's not sent & every incoming message says "decrypting..." forever.

hey @dysinger! Sounds like an annoying problem :( Somehow your log covers only 90 seconds, did you capture it immediately after you sent or received a message? A log of an incoming message that gets stuck "decrypting..." would be interesting.

**Comment by dysinger** [comment]
https://gist.github.com/e1df68458deccd3a73be813d9ae0d78f @haffenloher @nrizzio @moxie0 I captured another debug log while I was receiving messages that I can read on my linked desktop but appear as "decrypting..." forever on my phone (phone connected via wifi)

**Comment by dysinger** [comment]
3 weeks without Signal

**Comment by dysinger** [comment]
I finally uninstalled Signal & lost all my chat history & keys

**Comment by dysinger** [comment]
I uninstalled, reinstalled, verified my phone number by phone call, reverified keys with all my peoples & then it stopped working again after a couple weeks.

**Comment by dysinger** [comment]
I don't want to be super salty because I know lots of hard work went into this & parts of it are open source.  I'm just dismayed at the effort I put into pushing my whole family & all my friends to use it & now I can't keep it working

**Comment by dysinger** [comment]
I'm not the only one who's seen this problem
https://twitter.com/owenblacker/status/765179474753232896

**Comment by dysinger** [comment]
https://twitter.com/AaronToponce/status/768841885171392512

**Comment by dysinger** [comment]
https://twitter.com/Balaa_eish/status/732198004493561856

**Comment by dysinger** [comment]
https://twitter.com/EdVoncken/status/528516215279747072

**Comment by umudkip** [comment]
Pointing out the problem is not constructive. Could you provide new
instances of debug logs or otherwise informative logging?

**Comment by dysinger** [comment]
That didn't help at all last time but sure.

**Comment by dysinger** [comment]
https://gist.github.com/anonymous/ae8476368c2e711a12aa46c011d69e11

**Comment by dysinger** [comment]
If there was a way to reverify the phone number or even export/import my key, I'd be happy. Imagine if your GPG key ring just stopped working at random & the only way to make it work again was revoking your keys & having another key signing party. 1 time that might be workable. 2 times in the last couple months? no

**Comment by dysinger** [comment]
#5553 is very similar

**Comment by dysinger** [comment]
somehow I am stuck in a loop on https://github.com/WhisperSystems/Signal-Android/blob/ec63f7014e5e67993ac0793cc94de092d2b7eca6/src/org/thoughtcrime/securesms/database/MmsSmsColumns.java#L205

**Comment by dysinger** [comment]
I don't see anything in the logs that would help me debug this. If I had access to the sql database I could get further by reading code. Without knowing what data signal is looking at I'm at a loss to move forward with these debug logs.

**Comment by dysinger** [comment]
I have a development environment up & running now. I'll be able to reproduce this apart from my phone if my hunch is correct.

**Comment by dysinger** [comment]
As an experiment I added a sim card to my phone & everything immediately works again.  So even though you can sign up for Signal without text messaging enabled, it assumes that you do & the first time you try to text someone (on accident) everything stops working permanently.

**Comment by dysinger** [comment]
My suggestion would be to remove the voice confirmation if it's just going to lead to a broken app

**Comment by dysinger** [comment]
I could reproduce this by 

1. firing up signal in Android SDK
2. confirming my VoIP number via voice (grab an account with flowroute or similar PSTN gateway services)
3. messaging people securely on Signal
4. messaging a person not on Signal 
5. witness the app in a permanent loop "decrypting..." loop forever

**Comment by haffenloher** [comment]
wow, congrats on finding this... will try to reproduce once I find the time.

Just to be sure:

> messaging a person not on Signal 1 time

What's with that message sent to a non-Signal user? Is it stuck in pending state? Deleting it doesn't help?

**Comment by dysinger** [comment]
I will double check everything a couple times to make sure at some point this week using android sdk & ephemeral numbers at flowroute

**Comment by dysinger** [comment]
Yes, a message to a non-signal user seems to be what triggers it

**Comment by dysinger** [comment]
IMHO it should give an error when you SMS someone & there's no sim card in the phone
OR it shouldn't allow you to sign up by voice

**Comment by dysinger** [comment]
I wanted to try Signal without the possibility of IMEI trackers (wifi only). Seems like it's not possible currently. You can take a regular Android phone, remove the GSM antenna, install Signal, verify by voice & message people for a little bit before it stops working (pretty close though)

**Comment by dysinger** [comment]
Confirmed: you can reproduce this on your own phone easily.

Step 1) have a working phone with Signal
Step 2) take out your sim card
Step 3) send & receive texts & calls on Signal as long as you like over wifi
Step 4) send 1 SMS message to a person who is not on Signal
Step 5) watch as signal is broken for all uses until you put the sim card back in

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
