### ISSUE TITLE
Read state sometimes doesn't get synced from desktop app to Android app

### ISSUE THREAD

**Issue by tge-linee** [signalapp/Signal-Android#5519]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

After I receive a message in Signal and read it in the desktop app sometimes the Android app still shows it as unread.
### Steps to reproduce
- receive a message in Signal
- read the message in the desktop app
- look at phone

**Actual result:** The Android app still shows the message as unread
**Expected result:** The app should show the message as read
### Device info

**Device:** Samsung Galaxy S3
**Android version:** 4.1.2
**Signal version:** 3.16.0
**Signal Desktop version:** 0.13.0
### Link to debug log

Desktop: https://gist.github.com/anonymous/985fad27e92bede48278da43e8de1988
Android: https://gist.github.com/anonymous/3c8bd125c7c9a34fbc6ab95a1644942f

**Comment by deper29** [comment]
AFAIK Signal doesn't have read receipts.

**Comment by nrizzio** [comment]
@deper29 It does, but only for your own devices. Message read state should sync across all linked devices.

**Comment by skulumani** [comment]
I believe Signal Desktop already incorporates something like this

https://github.com/WhisperSystems/Signal-Desktop/commit/e07616e2ef01006077af86377f577226d28f49d0

I'm also pretty sure this exists on Android as well as I have noticed notifications disappearing from Android after reading on the Desktop.

https://github.com/WhisperSystems/Signal-Android/commit/08e2221dc0ce4cff5cff78b3b28a42059ecf934c

**Comment by Trolldemorted** [comment]
@skulumani how is this relevant? the complaint was that the android client sometimes either fails to receive or to handle receipts from signal-desktop.

i am experiencing this issue as well, and i think it happens more likely if signal-desktop has to send receipts for many messages at once. but even with regular conversations, i notice this every other day.

**Comment by luzgabriel** [comment]
I am experiencing this issue as well. It is quite annoying. If I am using the desktop app and I keep reading the messages on the desktop app my phone will not show notifications (that is expected!). However, if I do not read the message on the desktop app or open the app on my phone my phones starts to load every message, one by one thus receiving a lot of notifications, it is pretty annoying. I have to silence my phone for about 3~4 minutes until the app loads all the messages that I have sent and read on the desktop app. I don't know if it is the exact issue you guys are experiencing as well. If not I will open another issue.

Device info
Device: Nexus 5x
Android version: 7.1.1
Signal version: 3.25.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
