### ISSUE TITLE
Group message user can't see texts

### ISSUE THREAD

**Issue by mlam0413** [signalapp/Signal-Android#5520]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---

While texting in group messages, there is one member who cannot see my text messages.  When I text them individually, I don't have this problem. The members who cannot see my messages describe that they are blank bubbles where the contents of the text should be displayed.

My device info is as follows:
**Device:** Samsung Galaxy 4
**Android version:** 5.0.1
**Signal version:** 3.15.2

Link to debug log: https://gist.github.com/749a520b312d7b0553378f8b0a91e621

**Comment by Dyras** [comment]
What device/Android version/Signal version is your buddy using?

**Comment by mlam0413** [comment]
There's actually multiple group messages that is experiencing this issue. One is using a Moto X Pure with Android 6.0, and one is a Moto X (not sure what Android version they're using). Neither is using signal, just their native texting app.

**Comment by jeremydk** [comment]
I'm also having this issue if another repro is necessary. First started on M, and persisted through upgrade to N dev preview 3 on a Nexus6p.

**Comment by jeremydk** [comment]
The broken client is using a Moto X (2014) with the stock SMS app.  I had him try installing Textra and all the messages are now visible.   It looks like the common thread here is the Moto client.

**Comment by mlam0413** [comment]
Is there any update on this issue?

**Comment by mgla** [comment]
Same issue here: 

* Signal 3.29.6
* Android 6.0.1
* Samsung Galaxy s7

**Comment by rocrandall** [comment]
Same issue here on samsung galaxy, it will sometimes also try downloading the group broadcast msg as an individual text, but that always fails too. Really odd behavior

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
