### ISSUE TITLE
Race condition situation at the end of downloading an image in TextSecure of Signal

### ISSUE THREAD

**Issue by mfalmousa** [signalapp/Signal-Android#5522]
### Bug description

This bug happens in Android version of TextSecure(signal) when downloading an image. It makes the ProgressWheel in the TransferControlView to be always spinning even after completing the job of downloading, which disables the user from showing the image.
It seems that the attachment's statetransfer property, in the attachment database, changed to TRANSFER_PROGRESS_STARTED after being TRANSFER_PROGRESS_DONE (race condition situation).
### Steps to reproduce

When the user receives a push attachment (image), it is downloaded automatically in the background.
The bug happens when the user click to download the image after changing the state of the attachment to 'done' by the AttachmentDownloadJob and before acknowledging the user that the image has been downloaded.

**Actual result: the progressWheel will be always spinning, and the user cannot show the image directly from the conversation thread. However, the user can see the image from the 'all images' option in the menu.

**Expected result: The spinningWheel supposed to stop spinning after downloading the image, and the final state in the database should be TRANSFER_PROGRESS_DONE but not TRANSFER_PROGRESS_STARTED.

**Comment by FeuRenard** [comment]
I don't get how to reproduce this issue. I am in a conversation and do the following:

- receive push attachment
- see that it automatically starts to download (spinning wheel)
- _when do I have to hit something to reproduce this?_

If I hit the spinning wheel repeatedly, nothing weird will happen. Download successfully finishes and the thumbnail is shown. And by hitting the bubble after the spinning wheel disappeared I enter the media preview. At which point did I miss the described glitch?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
