### ISSUE TITLE
Sending empty video file crashes Signal

### ISSUE THREAD

**Issue by Entepotenz** [signalapp/Signal-Android#5523]
### Bug description

Signal crashes immediately after launching
### Steps to reproduce
- get a video file with size of 0
- try to send video into group chat

**Actual result:** 
Signal crashes and it is not possible to access the app.
Reboot doesn't help
**Expected result:** 
Warning that the video is empty
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.16.0

**Comment by haffenloher** [comment]
Try to open the app in flight mode as a workaround. That may allow you to delete the problematic message. If that works, could you please capture a debug log of the crash and post it here?

**Comment by Entepotenz** [comment]
I activated flight mode and deleted the video.

Tanks :-)

**Link to the debug log**
[https://gist.github.com/anonymous/94f6ec77f3f1d6348121d534853dcce3](url)

**Comment by 2-4601** [comment]
Related #5331.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
