### ISSUE TITLE
Incoming SMS was registered as an outgoing signal message

### ISSUE THREAD

**Issue by awnumar** [signalapp/Signal-Android#5524]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

An incoming SMS showed up on the screen as an outgoing signal message, which obviously failed to send and so prompted to fall back to SMS.
### Steps to reproduce

I'm not quite sure how to reproduce. It just happened. I'll attach a screenshot and a debug log.
### Screenshots

![img-20160606-wa0006](https://cloud.githubusercontent.com/assets/8942495/15826809/e3e5d718-2c00-11e6-83c5-8fba3001bc57.jpg)
### Device info

**Device:** samsung GT-I9305 (m3xx)
**Android version:**  4.4.4 (I9305XXUFOC1, KTU84P.I9305XXUFOC1)
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/anonymous/7d41a83d7a831628bccfae00bc0f4933

**Comment by 2-4601** [comment]
Related #5287

**Comment by libeclipse** [comment]
It seems in the related issue the message was displayed as an outgoing SMS while in this one it was displayed as an outgoing signal message.

**Comment by libeclipse** [comment]
Another thing to note is that in both cases, the texts came from automated systems.

**Comment by Killerwichtl** [comment]
The same bug also appears in group conversations. But i don't know how to reproduce yet. Only difference is that Signal tries to send back the message and the initially sender receives a weird string as private message. The other ones in the group don't receive anything. Signal Version was also 3.16.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
