### ISSUE TITLE
Signal  fails on IPv6-only networks

### ISSUE THREAD

**Issue by Spindel** [signalapp/Signal-Android#5528]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

textsecure-service.whispersystems.org seems to not have an ipv6 address, this makes signal fail miserably on ipv6-only networks
### Steps to reproduce
- Set up ipv6-only network on our public wifi
- connect phone to ipv6-only network and join the 21st century
- fail to send signal messages

**Actual result:** 
Instant failure on Signal

**Expected result:** 
Messages routed like normal
### Screenshots

None, debug log has been transmitted
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/anonymous/d205e48fdb8e90272cc2181ba8f953f5

**Comment by rmueller83** [comment]
IPv6 should now be possible: https://aws.amazon.com/de/blogs/aws/now-available-ipv6-support-for-amazon-s3/
The Java library was updated to 1.11.26 a few minutes ago and released on GitHub. It should also be available in Maven pretty soon, including dual stack capabilities: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/DualstackEndpointBuilder.java

**Comment by rmueller83** [comment]
It is on Maven Central now.
https://aws.amazon.com/releasenotes/9387767230430923
https://docs.aws.amazon.com/AmazonS3/latest/dev/ipv6-access.html
There seem to be some restrictions when using EC2, perhaps @moxie0 could tell if this would work.

**Comment by derNarr** [comment]
As my internet provider regularly has ipv4 outages, solving this issue would increase the connectivity of signal for me. ipv6 works much more stable at my internet provider.

Keep up the good work. Thanks!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
