### ISSUE TITLE
Muted Conversations showing on lock screen when phone is off

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#5537]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Describe here the issue that you are experiencing.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by AdamG620** [comment]
If I receive a message in a conversation that has been muted, I will still receive a lock screen notification when the phone lock screen is on.  I do not receive notifications for the muted conversation if the phone is on/unlocked.

**Comment by 2-4601** [comment]
Unable to reproduce on Nexus 4, Android 6.0.1, Signal 3.16.0.

Please read through https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
It's difficult to try to fix a bug when there's not enough information.

**Comment by AdamG620** [comment]
Sorry about that. I'm also on 6.0.1 on a Galaxy S7. Signal 3.16.0.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
