### ISSUE TITLE
InputPanel does not retain cursor position when rotating

### ISSUE THREAD

**Issue by lorenzhs** [signalapp/Signal-Android#5539]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When rotating the device while composing a message, the cursor (caret) position is lost. Signal always places the cursor at the beginning of the message after rotation. This requires scrolling back to the previous position (usually the end), which is cumbersome.
### Steps to reproduce
- write a message in a conversation, but don't send it yet
- rotate device

**Actual result:** Text is retained, but cursor is at the beginning
**Expected result:** Cursor position should be restored after rotation

If you can point me in the right direction, I can attempt to fix this myself if you want.
### Device info

**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 3.16.0

**Comment by 2-4601** [comment]
Hmm... unable to reproduce on Nexus 4, Android 6.0.1, Signal 3.16.0 and Google keyboard

However, in my Huawei 4.0.4 device with stock keyboard the cursor always moves to the end of the **word** after rotation. 

Sounds like this could be a keyboard issue. Which keyboard are you using?

**Comment by lorenzhs** [comment]
Hu. I'm using Swiftkey, but I can reproduce just the same with the AOSP keyboard and the Google keyboard. That's weird.

**Comment by lorenzhs** [comment]
Screencast: https://4z2.de/signal-android_bug_5539.mp4

**Comment by FeuRenard** [comment]
I cannot reproduce this with Android 5.1 AOSP keyboard, Signal 3.16.0. The text cursor position doesn't change during rotation.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
