### ISSUE TITLE
Can't send messages anymore (Authorization failed)

### ISSUE THREAD

**Issue by BlackLotus** [signalapp/Signal-Android#5551]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When trying to send a message over Signal I always get a "Not delivered". Resending doesn't help, resetting the session doesn't work and I got network connectivity. Trying to list the linked devices results in a "Network connection failed..."
### Steps to reproduce
- click on a signal contact
- Try to send a message

**Actual result:** I get a "Not delivered" message.
**Expected result:** The message should be delivered.
### Device info

**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 3.16.0
### Additional Info

I use Signal-Desktop from git and before it stopped working I tried to link the official Signal-Desktop version with the phone. The official Signal-Desktop works, but syncing contacts didn't.
Signal-Desktop works correctly.
### Link to debug log

https://gist.github.com/86ee03f8e090df52ba0b2f4140696460

**Comment by northwestbased** [comment]
You might want to try contacting whisper system support at support@whispersystems.org. In as much as there hasn't been a new Signal release on the play store for a month, if things stopped working recently, it could potentially be a problem with your phone.

**Comment by rprimus** [comment]
Mon Feb 20 15:17:42 GMT 2017

Am having the same symptoms as OP.  

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.1 N4F260
**Signal version:** 3.29.6

### Additional Info
```
02-20 14:56:01.688 29804 29828 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
02-20 14:56:01.689 29804 29828 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/gcm/
02-20 14:56:02.251 29804 29828 W JobConsumer: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
02-20 14:56:02.251 29804 29828 W JobConsumer: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:536)
02-20 14:56:02.251 29804 29828 W JobConsumer: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerGcmId(PushServiceSocket.java:190)
02-20 14:56:02.251 29804 29828 W JobConsumer: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.setGcmId(SignalServiceAccountManager.java:79)
02-20 14:56:02.251 29804 29828 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-20 14:56:02.251 29804 29828 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```
=======================================================================
## Solution:

The above appears to occur when a user's keys keys get corrupted.

**Steps I took to solve issue:**

1. Export Plaintext backup
2. Delete App data and Cache
3. RE-register with Signal
4. Import backup (from step 1.)
5. Review App settings
6. (Optionally)  Link devices

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
