### ISSUE TITLE
Changing group icon does not work (out of memory exception)

### ISSUE THREAD

**Issue by SlappyHours** [signalapp/Signal-Android#5554]
- Capture an image with smartphone camera
- Start signal
- Edit a group
- Click on group icon
- Chose camera image
- Crop image using crop dialog
- Save

Expected: Chosen cropped image is now the new group icon
Observed: Icon is still the old icon (nothing changed)

Log shows "out of memory" exception. Resizing image with other apps works fine. So I do not think this is really "out of memory".

Workaround: Edit camera image, resize to smaller resolution and save as png.

Android 4.4.4 / Moto X

---

D/dalvikvm(11070): GC_CONCURRENT freed 155K, 25% free 71304K/94596K, paused 6ms+9ms, total 101ms
W/OkHttpClientWrapper(11070): onClose(1000, OK)
W/WebSocketConnection(11070): onClose()...
D/dalvikvm(11070): GC_EXPLICIT freed 123K, 25% free 71360K/94596K, paused 4ms+8ms, total 94ms
D/dalvikvm(11070): GC_EXPLICIT freed 190K, 25% free 71170K/94596K, paused 4ms+8ms, total 89ms
D/dalvikvm(11070): GC_FOR_ALLOC freed 16K, 25% free 71173K/94596K, paused 71ms, total 71ms
I/dalvikvm-heap(11070): Forcing collection of SoftReferences for 19713616-byte allocation
D/dalvikvm(11070): GC_BEFORE_OOM freed <1K, 25% free 71173K/94596K, paused 77ms, total 77ms
E/dalvikvm-heap(11070): Out of memory on a 19713616-byte allocation.
I/dalvikvm(11070): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm(11070):   | group="main" sCount=0 dsCount=0 obj=0x416dee40 self=0x41601520
I/dalvikvm(11070):   | sysTid=11070 nice=-6 sched=0/0 cgrp=apps handle=1074520404
I/dalvikvm(11070):   | state=R schedstat=( 0 0 0 ) utm=460894 stm=73908 core=1
I/dalvikvm(11070):   at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
I/dalvikvm(11070):   at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
I/dalvikvm(11070):   at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:352)
I/dalvikvm(11070):   at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
I/dalvikvm(11070):   at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:46)
I/dalvikvm(11070):   at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:107)
I/dalvikvm(11070):   at android.view.View.performClick(View.java:4456)
I/dalvikvm(11070):   at android.view.View$PerformClick.run(View.java:18462)
I/dalvikvm(11070):   at android.os.Handler.handleCallback(Handler.java:733)
I/dalvikvm(11070):   at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm(11070):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm(11070):   at android.app.ActivityThread.main(ActivityThread.java:5086)
I/dalvikvm(11070):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(11070):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(11070):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
I/dalvikvm(11070):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
I/dalvikvm(11070):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(11070): 
E/GraphicsJNI(11070): **\* Uncaught exception returned from Java call!
W/System.err(11070): java.lang.OutOfMemoryError
W/System.err(11070):    at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
W/System.err(11070):    at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
W/System.err(11070):    at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:352)
W/System.err(11070):    at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
W/System.err(11070):    at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:46)
W/System.err(11070):    at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:107)
W/System.err(11070):    at android.view.View.performClick(View.java:4456)
W/System.err(11070):    at android.view.View$PerformClick.run(View.java:18462)
W/System.err(11070):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(11070):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(11070):    at android.os.Looper.loop(Looper.java:136)
W/System.err(11070):    at android.app.ActivityThread.main(ActivityThread.java:5086)
W/System.err(11070):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(11070):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(11070):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err(11070):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err(11070):    at dalvik.system.NativeStart.main(Native Method)
E/android-crop(11070): OOM cropping image: null
E/android-crop(11070): java.lang.OutOfMemoryError
E/android-crop(11070):  at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
E/android-crop(11070):  at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
E/android-crop(11070):  at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:352)
E/android-crop(11070):  at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
E/android-crop(11070):  at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:46)
E/android-crop(11070):  at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:107)
E/android-crop(11070):  at android.view.View.performClick(View.java:4456)
E/android-crop(11070):  at android.view.View$PerformClick.run(View.java:18462)
E/android-crop(11070):  at android.os.Handler.handleCallback(Handler.java:733)
E/android-crop(11070):  at android.os.Handler.dispatchMessage(Handler.java:95)
E/android-crop(11070):  at android.os.Looper.loop(Looper.java:136)
E/android-crop(11070):  at android.app.ActivityThread.main(ActivityThread.java:5086)
E/android-crop(11070):  at java.lang.reflect.Method.invokeNative(Native Method)
E/android-crop(11070):  at java.lang.reflect.Method.invoke(Method.java:515)
E/android-crop(11070):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/android-crop(11070):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/android-crop(11070):  at dalvik.system.NativeStart.main(Native Method)
I/Choreographer(11070): Skipped 32 frames!  The application may be doing too much work on its main thread.
W/PassphraseRequiredActionBarActivity(11070): onResume()
W/KeyCachingService(11070): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(11070): Incrementing activity count...
W/MessageRetrievalService(11070): Active Count: 1
W/MessageRetrievalService(11070): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(11070): Making websocket connection....
W/WebSocketConnection(11070): WSC connect()...
W/OkHttpClientWrapper(11070): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
W/MessageRetrievalService(11070): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(11070): Reading message...
W/WebSocketConnection(11070): onConnected()
W/PassphraseRequiredActionBarActivity(11070): onPause()
W/KeyCachingService(11070): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(11070): Decrementing activity count...
W/MessageRetrievalService(11070): Active Count: 0
W/ConversationActivity(11070): onActivityResult called: 5, 0 , null
W/PassphraseRequiredActionBarActivity(11070): onResume()
....

**Comment by 2-4601** [comment]
Related  #3084.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
