### ISSUE TITLE
Partial message copying feature request

### ISSUE THREAD

**Issue by jalkjaer** [signalapp/Signal-Android#5555]
Copying partial text from a message would be nice. I.e. when receiving long validation tokens/one-time passwords to be entered in some web form.

See #2845

**Comment by BilliAlpha** [comment]
I agree that this would be an awesome feature.

**Comment by MiKhan1** [comment]
It is nice Signal allows to take an action on a phone number (if it is recognised, though), but copying part of the message would still be great.

**Comment by joelbarker2011** [comment]
This is the single biggest draw AWAY from Signal for me. Someone texts me an address or email, and I can't easily copy it? Irritating.

**Comment by moxie0** [comment]
@joelbarker2011 Do you have an example of an app that you feel does this well? Hangouts, Messenger, and WhatsApp all work the same way as far as I can see. Is there are UX interaction that I'm missing?

**Comment by joelbarker2011** [comment]
I just checked my old text messaging app (Android default) and Google
Voice: neither allows partial message copying (to my great surprise). Both
(like Signal) allow tapping a phone number/email address/web address to
call/email/browse.

This would still be a neat feature, but I withdraw my implied criticism.
(Thanks for calling me out.)

Joel

Via phone

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
