### ISSUE TITLE
Plaintext backup import deletes the plaintext backup after import

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#5556]
### Bug description

Upon import of a plaintext backup the backup gets deleted.
### Steps to reproduce
1. I exported a backup.
2. Reformatted phone, and imported backup.
3. Waited a day; reformatted with an update; the backup was gone.

**Actual result:**
The backup of the export is deleted.

**Expected result:**
The backup should not be deleted after import.
### Device info

**Device:** Oneplus X
**Android version:** 6.0 (CM13 nightly)
**Signal version:** 3.16.0

**Comment by LoveIsGrief** [comment]
It might be prudent to ask before deleting.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
