### ISSUE TITLE
Can't retry download MMS

### ISSUE THREAD

**Issue by n76** [signalapp/Signal-Android#5562]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When MMS download fails I am unable to retry.
### Steps to reproduce
- Create a condition where receiving an MMS will fail. In my case it is when I am connected to a WiFi (WLAN) Access Point.
- Have an MMS sent to phone.
- Will get a message "MMS download failed!"
- Correct MMS receive condition (in my case disable WiFi).
- No obvious way to request Signal to retry downloading MMS.

**Actual result:** Should be able to request another MMS download attempt.
**Expected result:** No obvious way in app or in WhisperSystem FAQs, etc. to have app retry to download MMS.
### Device info

**Device:** Galaxy Nexus (Maguro)
**Android version:** AOSP 6.0.1
**Signal version:** 3.16.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
