### ISSUE TITLE
Message notification icon does not always clear after reply when inactivity timeout enabled

### ISSUE THREAD

**Issue by AboveMyPaygrade** [signalapp/Signal-Android#5567]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Message notification icon does not always clear after reply when inactivity timeout enabled.
### Steps to reproduce
- enable inactivity timeout within the privacy settings
- allow Signal to lock due to an inactivity timeout
- receive a message from someone
- unlock your phone
- see that you have the notification icon that normally appears after a new message has arrived
- pull down the notification bar: it should show the contact, along with "locked message"
- touch the notification, which should take you to the screen to unlock Signal
- unlock Signal
- reply to the message
- press your home button

**Actual result:** Message reply goes through, as expected, but the notification icon in the status bar does not clear.  Notification icon will only clear if you either go into Signal and go to the aforementioned conversation thread, or if you pull down your notification bar again and tap on the message notification a second time (you could also manually clear the notification from the notification bar).

**Expected result:** Notification icon should clear after either unlocking Signal after tapping the notification the first time, or after the reply to the message.
### Screenshots

N/A
### Device info

**Device:** Huawei Nexus 6P
**Android version:** 6.0.1, Stock, Rooted, Build no. MTC19V
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/4cc3188c15eaf968a158d700e91ca6de

https://gist.github.com/8282873282725aa673e17f9f1ca26b96

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
