### ISSUE TITLE
Bug report leaks authentication secrets

### ISSUE THREAD

**Issue by janschejbal** [signalapp/Signal-Android#5570]
I just took a system-level bug report, and in the "VM TRACES JUST NOW" section under:

```
----- pid 19934 at 2016-07-10 16:14:17 -----
Cmd line: org.thoughtcrime.securesms
```

I saw this:

```
"WebSocketReader https://textsecure-service.whispersystems.org/v1/websocket/?login=+[redacted]&password=[redacted]" prio=5 tid=45 Native
```

The login was my phone number, and the password was 24 base64-looking characters.

I'm not sure if this can be prevented (maybe by moving the password out of the GET parameters?), but this doesn't look like a good thing.

**Comment by bobberb** [comment]
Run a winpcap or wireshark on this if you are curious.   HTTPS wraps arou everything after the .com.

**Comment by 2-4601** [comment]
This doesn't happen in the debug logs that are captured within Signal.
But I can reproduce this on a **non-rooted** Android 6.0.1 by taking the bug report from the Developer Options. However before you capture that log Android gives you an explicit warning that says that private information might be visible in the report.

The CrashBrowser logs seem to have that information too but they are redacted, see #3734 (or Moxie redacted them manually).

**Comment by sigenc** [comment]
So basically even with an password for my database, a simple system level bug report will show the number with wich i registered signal? i was under the impression that with locked signal even forensics couldn't find out my number. Why is it necessary to upload login and hashed pass to https://textsecure-service.whispersystems.org/? And how could this be prevented? If it is used as a indentifier for signal can't we generate some id with doesn't let anybody filter out the number with a debug log? My concern is per example. If i message a friend and he didn't safe my number with a name it only shows up as a number in his contact list. an adversary who jailed us both will have the evidence that i messaged him, when for example my friends phone got seized before the database locks automatically. The adversary now can see his messages and contacts. If he believes that one of this numbers is mine he could compere it to the logs of my device and there it is the evedence.

Or am I totally wrong about this?

**Comment by sigenc** [comment]
#6172

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
