### ISSUE TITLE
Messages not delivered until signal is opened since upgrade to Android 6.01

### ISSUE THREAD

**Issue by leo-b** [signalapp/Signal-Android#5578]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Since I upgraded to Android 6.01, incoming messages are only delivered when the app is opened.
I think I am suffering from the same problem as @sesse [commented here](https://github.com/WhisperSystems/Signal-Android/issues/5548#issuecomment-232490696)

I did already try all steps suggested in http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-.
- GCM ist working, the Play services monitor shows successful pings
- Is doesn't matter if the phone is connected via Wifi or mobile data.
- A reboot doesn't help
- reinstalling Signal (with re-registering and reimporting data) doesn't help
- other GCM push services like Whatsapp, Facebook or Hangouts work fine
- clearing the cache and data of Google Play Services and Google Services Framework doesn't help
### Device info

**Device:** Samsung Galaxy S5 (rooted)
**Android version:** 6.0.1
**Signal version:** 3.16.0

**Comment by gjallarhorn** [comment]
You did not write anything about battery optimizing features (which is usually the reason behind these problems). So have you: 
1. White listed Signal in Doze (part of Android 6). See this link:
http://www.cnet.com/how-to/stop-specific-apps-from-using-doze-on-android-6-0-marshmallow/
2. Samsung have something called "power save" which I think should only be enabled when you really need to save all the battery you can. White listing Signal in this does not help, so I recommend you to disable it instead.

**Comment by leo-b** [comment]
> Whitelisted Signal in Doze (part of Android 6).
> Samsung have something called "power save"

Did that. (Power saving mode is disabled, Ultra power saving mode is disabled, Signal ist whitelisted as app.) Just re-checked.

**Comment by sesse** [comment]
Here's something strange: Today, Signal got updated to 3.16.1, and it seems like the problem has disappeared; my phone now receives Signal messages while it's in my pocket with no issues at all. But there are no code changes from 3.16.0 to 3.16.1…?

**Comment by n76** [comment]
If you look at the commit history you will see that a number of changes have been made along the way, just never released. When the version was bumped, and a new build released, those changes were, in effect, released.

**Comment by sesse** [comment]
I looked at the commit history, and couldn't find any changes. Neither does “git diff v3.16.0..v3.16.1”. What git-fu am I missing?

**Comment by n76** [comment]
Sorry, I was wrong. . . I was going by noticing the last check-in date as shown on the GitHub website occasionally changing. But when I actually do a "git diff" between 3.16.0 and 3.16.1 the only change appears to be the version code and version name in the manifest.

**Comment by Trolldemorted** [comment]
my nexus 4 (CM13, Android 6.1) is affected too, but not always.

@leo-b does this always happen? i have the impression that disabling wifi or something like that is triggering this.

**Comment by tecufanujacu** [comment]
Me too sometime I have the same problem.

@sesse some months ago I received the messages only opening Signal, I simply uninstalled and reinstalled it to partially solve the problem, now only sometime I don't receive some message until I don't open Signal.

**Comment by 2-4601** [comment]
I had these a couple of times a month or two ago on 6.0.1. Haven't had since. Sounds like intermittent GCM issues.

**Comment by d4l3k** [comment]
I've been having this occur pretty regularly on Android 7.0 preview 5.

**Comment by Hedaja** [comment]
Same problem here. 
Honor 6 H60-L04
Emui 4.0
Andorid 6.0

All permissions are given. It's whitelisted from power saving. Notifications and everything is activated....

**Comment by Hedaja** [comment]
Forgot to mention that I had quite a few apps (also certain Google apps disabled)  in an older issue someone reported that activating them solved the problem. So I'm trying that right now.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
