### ISSUE TITLE
Incorrect Photo Preview in Group Chat

### ISSUE THREAD

**Issue by phrag** [signalapp/Signal-Android#5584]
### Bug description

Sent photo to group A, different photo to group B.
Group A photo preview displays Group B's photo. When clicking on the preview, correct photo is then displayed.
### Steps to reproduce

Only seen this once and i use signal everyday.
### Device info

**Device:** OnePlus3
**Android version:** 6.0.1
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/anonymous/0eed8e9bfcfb4f8de2ff6bdcdedfa65c

**Comment by 2-4601** [comment]
Sounds like #5071, #4732.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
