### ISSUE TITLE
unregistering and group membership

### ISSUE THREAD

**Issue by 2011** [signalapp/Signal-Android#5594]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Describe here the issue that you are experiencing.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0
### Link to debug log

I guess this is more of a feature request (after reading other issues).

I recently had to change my number, and forgot to leave my groups before unregistering. I no longer have access to the old number, which will eventually be reassigned to someone else. It seems that all of my groups (some reasonably large) will have to be re-created (ugh).

Two thoughts for improvements.
1. Automatic purging of group memberships when someone unregisters a number.
2. Prompt the user ("would you like to leave groups you are a member of?") when someone unregisters a number.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
