### ISSUE TITLE
Several contacts get "Daniel Nagy stopped using Signal" message whereas in fact I did not.

### ISSUE THREAD

**Issue by nagydani** [signalapp/Signal-Android#5595]
I have:
- [y] searched open and closed issues for duplicates
- [y] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Several contacts get "Daniel Nagy stopped using Signal" message whereas in fact I did not. When I send them Signal messages, they receive them, but I do not get confirmation (second check mark). Also, my desktop and mobile clients are out of sync: messages sent from one do not appear in the other. I do not receive any Signal messages from those contacts (only unencrypted SMS over Signal).
### Steps to reproduce
- Send Signal message to any of such contacts

**Actual result:** I get a single checkmark after a second or so, but never the second one confirming that they have received it.
**Expected result:** Get a single checkmark after a second or so and a second checkmark after a similarly short period of time.
### Screenshots

Not relevant.
### Device info

**Device:** Samsung Galaxy S3 (GT-I9300)
**Android version:** 4.3
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/anonymous/25e3e981c0b3ce21849c0c3e8af4a869

**Comment by GabrielSturtevant** [comment]
This may be a silly question, but have you tried selecting the "Reset secure connection" option in the conversation with each of these contacts?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
