### ISSUE TITLE
Setting large group image fails

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5596]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I tried to add a large group image (>3MB) and it failed in two ways depending on the device.
### Steps to reproduce
- update group
- tap on the group avatar
- select a large image ~~(now crash on old device)~~
- tap the checkmark to update the group
- tap the group title and see that the group image is black

**Actual result:** ~~Crash on old device.~~ Black group image on new device.
**Expected result:** Group image should be set to the selected image.

~~### Device info (old device)
**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 3.16.0~~
### Device info (new device)

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.16.0

~~### logcat (old device)
only output, that seemed relevant.
https://gist.github.com/FeuRenard/7a84e8c7f4785b83ec1212c3ed92598f~~
### Debug log (new device)

https://gist.github.com/anonymous/adfa7aabc2f684f8ca420c078a0bf338

**Comment by FeuRenard** [comment]
Half of this issue is tracked in #5554. I edit the initial post accordingly.

**Comment by schmeat** [comment]
Experiencing this right now. 

- https://gist.github.com/36e13919d233145667ce9f727cc2433a

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
