### ISSUE TITLE
This requires Google Play

### ISSUE THREAD

**Issue by mid-kid** [signalapp/Signal-Android#560]
I don't know why this app requires play, but I don't have / want to have google play installed on my cyanogenmod.

If it's possible, please remove the requirement, otherwise, please elaborate on why it's needed.
Thanks.

**Comment by jomo** [comment]
Can this please be reconsidered?

It's already hard enough to install TextSecure without Google Play (i.e. on CM), but requiring it for (non-sms) chats is really, really bad for a **privacy** focused app IMHO.

I would love to use TextSecure, but I don't want to install Google Apps (that probably track me everywhere I go).

I'm sure it's possible to find another way for push messages.
