### ISSUE TITLE
Quiet Time

### ISSUE THREAD

**Issue by unhammer** [signalapp/Signal-Android#5625]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Sometimes, I get lots of messages while I'm at work, which could bother my co-workers. I'd like to make Signal be quiet about the messages (just blink the led, no vibration or sound), but without silencing my phone completely (if someone calls, I'd like to hear it). I can turn off message sounds/vibration, but then I have to remember to turn it on again later before I put my phone in my jacket. Could we have a time-based quiet mode, where I can say "no message sound/vibration 8-4 on weekdays"?
### Steps to reproduce
- try to work
- receive 30 messages at once, opening desktop app in desperation

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- get embarrassed and turn off phone sound
- forget to turn on again sound after work
- receive very important message on way back from work and not notice

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- enable Quiet Time
- phone starts beeping after work, stops beeping when starting work next day

**Alternative solution:** 
- when the Desktop app is started, let there be a 10-second delay before messages reach phone. If the reply field of the relevant conversation has received any input/mouseover, the message is marked read, and sent to the phone as a previously read message which doesn't need notification.

**Comment by FeuRenard** [comment]
That's maybe a task of your OS. And e.g. in Android 5.1 such a feature already exists.

**Comment by libeclipse** [comment]
If thirty messages come in, you should only get a loud notification for the first one.

**Comment by FeuRenard** [comment]
That issue is tracked in #3165.

**Comment by Calefornia** [comment]
iMessage forwarding from Mac to iPhone uses a slight delay before notifying phone, and FB messenger allows muting conversations. Sounds like both features would be useful. Cheers.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
