### ISSUE TITLE
MMS Fails to Send or Download.

### ISSUE THREAD

**Issue by SyberHexen** [signalapp/Signal-Android#5629]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description
- MMS to non-Signal users do not send or download but if I enable the system default messaging app i can send them from there with no trouble. 
- Used to work in older versions (Aprox. 1 Year or longer ago, Don't remember exact ver. figured it would work itself out.)
  ###Steps to solve 
- Formatted my device
- Toggled Wifi off
- Switched between 2g, 3g, LTE
- Adjusted through all available apn setting for my carrier with many variations inside and outside the manual mms settings area.
- Had a New Sim Re-provisioned to my device.
- Did reset APNs and rebooted device 
### Reset APNS to default and rebooted twice after these steps.
- Wrote new apns-conf.xml file with my Unlisted APN added.
- Wrote new apns-conf.xml file with all other APNS for my carrier removed.
- Wrote new apns-conf.xml with just my carrier's provisioned APN in file.
### APN provieded by  'NET10 Wireless' for bring your own device customers  (which isn't in cyanogenmod APN or Signal APN databases

Name: Reseller
APN: Reseller
Proxy: (blank)
Port: (blank)
Username: (blank)
Password: (blank)
MMSC: http://mmsc.mobile.att.net
MMS Proxy: proxy.mobile.att.net
MMS Port: 80
MCC: 310
MNC: 410
Authentication Type: (None)
APN Type: default,mms,supl
APN Protocol: IPv4
Bearer: Unspecified
### Steps to reproduce
- Send MMS to Non-Signal User
- Recieve MMS from Non-Signal User

**Actual result:** Sending Box Spins for a short while then says fails to send.
**Expected result:** Sending Box Spins and MMS Sends
### Device info

**Device:** Unbranded LGE Nexus 5 (hammerhead)
**Android version:** 4.4.4 (Cyanogenmod 11)
**Signal version:** Signal 3.16.1
### Link to debug log

First debug before getting Re-provisioned Simcard
https://gist.github.com/24bc7cbad80c4f6ab2946b93906d7f8f
Second after re-provisioned Sim
https://gist.github.com/anonymous/f11e6879fece15e7e81e543e71ced6b6

**Comment by jjohns71** [comment]
This seems to be causing the issue based on the second gist you posted.

> W/LegacyMmsConnection( 6662): connecting to http://mmsc.mobile.att.net/
> **W/LegacyMmsConnection( 6662): * response code: HTTP/1.1 403 Invalid MSISDN number received.**

**Comment by SyberHexen** [comment]
Yea that's been the only persistent error that jumps out to me.  Seemed present regardless which working apn I had used.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
