### ISSUE TITLE
Cannot take in-app photo with Note 4 on CM 12.1

### ISSUE THREAD

**Issue by co50** [signalapp/Signal-Android#5643]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In the Signal app, attempting to take a photo results in nothing. The camera's take-photo on screen graphic blinks when you touch it like normal but doesn't take a photo. 
### Steps to reproduce
- Open Signal on a Note 4 with latest CM 12.1 nightly (same issue with last month's worth of nightlies)
- Tap photo icon
- Attempt to snap photo

**Actual result:** Nothing. Circular "take photo" graphic blinks as it should when you touch it, but doesn't take photo. Tapping it repeatedly does nothing, just blinks each time. 
**Expected result:** Normally, like before I installed CM 12.1, it would take the photo just fine.
### Screenshots

Screenshot wouldn't help here. Nothing appears out of the ordinary.
### Device info

**Device:** Samsung Galaxy Note 4 (T-Mobile version)
**Android version:** 5.1.1
**Signal version:** 3.17.0
### Link to debug log

https://gist.github.com/27e84147eb45738e4d22a639249ea89e

**Comment by FeuRenard** [comment]
The logged exception is similar to that in #4899.

**Comment by co50** [comment]
I read that thread, but the "solution" to the issue on that phone was installing CM 13.0. However, CM 13.0 does not exist for the Note 4. Any better solutions?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
