### ISSUE TITLE
Replace 'TextSecure' string in Contacts app with 'Signal'

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-Android#5644]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

The word 'TextSecure' is still used for Signal contacts in Android's Contacts app.
### Steps to reproduce
- open Android's `Contacts` app
- select a contact who uses Signal
- click on the `Edit` button (the pencil in the upper-right corner)
- click on `Linked contacts (x)`

**Actual result:** The linked contacts of the contact are shown and the Signal contact shows `Signal` with `TextSecure` as subtitle.
**Expected result:** `TextSecure` should be replaced with `Signal`. A quick look in the source code gave me the impression that this should be changed [in this line](https://github.com/WhisperSystems/Signal-Android/blob/a307ff350c4f2ef0c778b1e2fd4656cb6ac086e6/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java#L210).
### Screenshots

![signal_contact](https://cloud.githubusercontent.com/assets/696839/18057981/928a26ea-6e12-11e6-96c7-9a2cd13acead.png)
### Device info

Device: Nexus 5
Android version: 6.0.1
Signal version: 3.17.0
### Link to debug log

n/a

**Comment by nrizzio** [comment]
I can't reproduce this on Android 5.1. Have you had Signal installed from when it was TextSecure?

**Comment by siccovansas** [comment]
Yes that is the case indeed. Not sure if this is a problem anymore then or if it can be easily fixed? My main concern was that new users who don't know TextSecure might be confused by this issue, but this is less of a problem if it only occurs for old TextSecure users. Still I guess it would be nice to have the text replaced if it is easily fixed.

**Comment by johanw666** [comment]
I can reproduce this (or at least something similar because the GUI differs) on aSony Xperia Z1 compact running Android 4.4.4.

**Comment by FeuRenard** [comment]
If the TextSecure string is only shown on "old" installations, I would say: it's not a bug, it's a feature :wink:
The user originally installed TextSecure and maybe this hint helps him recognize the app. But it's also ok to eliminate the TextSecure string.

**Comment by johanw666** [comment]
I checked it on a new phone, the account name there is shown as Signal. Apparently it's an Android thing where the existing account is not renamed.

**Comment by riyapenn** [comment]
This should resolve with a [resync of your contacts](http://support.whispersystems.org/hc/en-us/articles/216595418-How-can-I-see-the-names-of-my-contacts-in-my-contact-list-I-am-only-seeing-numbers-)

1. Go to Android Settings
2. Choose Accounts
3. Choose Signal
4. Tap on the Menu
5. Choose Remove Account (the alert of clearing data is incorrect, your messages will not be deleted)
6. Open Signal
7. Tap on the pencil icon in the blue circle
8. Choose the Menu
9. Tap Refresh

**Comment by siccovansas** [comment]
@riyapenn I can confirm that these steps indeed fix the 'problem' (a side effect was that I received a notification, effectively the second time, of the people who are Signal which I haven't chatted with). The remaining question is if this procedure can be automated and forced on 'old' TextSecure users (preferably without the above side effect) or if this is too minor of an issue and that people who want to fix it should use the procedure listed in the previous post.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
