### ISSUE TITLE
Messages to numbers without ()s fail silently

### ISSUE THREAD

**Issue by nojunkforme** [signalapp/Signal-Android#5645]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Messages to numbers formatted like 123-456-7890 fail silently. The message never arrives to the recipient. There is no indication the message wasn't sent. The same message sent to (123) 456-7890 succeed.
### Steps to reproduce
- Use a known good contact's phone number, Ten digit, US format. e.g. (123) 456-7890
- send a message 
- Verify the message was received.
- edit the phone number so that it is has no parentheses, ()s.  e.g. 123-456-7890
- send a message
- this message will not be delivered, nor will there be any error message shown. 

**Actual result:** 
- This message will not be delivered, nor will there be any error message shown. 
  **Expected result:** 
- This phone number format should be acceptable. Messages using it should be sent and received.
### Screenshots

none needed.
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.17.0
### Link to debug log

make one yourself.  It if showed an error message when the problem happened submitting a debug log would be much easier. Since it fails silently there's no indication of an error.

**Comment by johanw666** [comment]
A number not starting with a 0? What country is that? Can you send a sms to the number formatted in that way? I need to use the entire number, for a US number I believe that would be something like  +11234567890.

**Comment by moxie0** [comment]
Can't reproduce. Are you running some weird ROM?

**Comment by nojunkforme** [comment]
No.  Nothing but a stock Nexus 5 running the latest Android 6.0.1.
Granted this is a weird problem and possibly not described correctly. Still there are contacts on my phone who can send me texts, but when I reply they get nothing. This happens only with Signal. When I use the built in Google Messenger they get delivered as expected. Some contacts work fine. Some fail silently. I can only confirm the failures by communicating via email.  If there were a texting test bed I could send messages to I would try out a variety of contact formats.

**Comment by johanw666** [comment]
AFAIK is "texting" an Americanism for "sending sms messages". Are you talking about sms messages or Signal messages via the internet?

**Comment by n76** [comment]
"Texting" in the US may be SMS or MMS and the person saying "texting" probably does not know which technology is being automatically selected for them. Or even that two different technologies exist for sending messages via a mobile carrier.

**Comment by nojunkforme** [comment]
The field on the bottom of the Signal app screen says either "Send unsecured SMS" or "Send Signal message". The failures I've seen appear more often (always?) with the Send Signal message option. One of these recipients was on an iPhone, the other on Nexus 5 running a possibly out of date version of Android.

**Comment by johnwblue** [comment]
> AFAIK is "texting" an Americanism for "sending sms messages".

(•_•) ( •_•)>⌐■-■ (⌐■_■)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
