### ISSUE TITLE
Display pictures of contacts in group member list view

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#5647]
### Bug description

The list of group members should display the peoples picture left to their names.
### Steps to reproduce
- tab the group members icon in the top bar in a group conversation

**Actual result:** 
A list of names appear
**Expected result:**
a list of names with the contacts picture from address book should appear
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1 MOB30Y
**Signal version:** 3.17.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
