### ISSUE TITLE
mms receive fails for group message

### ISSUE THREAD

**Issue by jperkyns** [signalapp/Signal-Android#5655]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When messages (whether just text, or also pictures etc.) are sent to a group and I am one of the recipients, (either from a non-signal user or a signal user) there is an error which says:
Multimedia message
MMS download failed!
with a red exclamation point.
Attempting to download again gives the same result.

Messages which are sent to a single user (just me) arrive correctly (just text or pictures etc all good).
If I switch to the default app the group messages arrive correctly.
Two other members of my family who just upgraded their phones as I did have exactly the same problem.
### Steps to reproduce
- Have anyone send a group message when I am one of the recipients.

**Actual result:** 
I get the error message as described above.
**Expected result:**
Group message should download correctly.
### Screenshots

The error message is too simple for this.
### Device info

**Device:** Samsung J7 (SM-J700P)
**Android version:** 6.0.1
**Signal version:** 3.17.0
**Carrier** virgin mobile usa (sprint)
I have searched the settings for the phone but none of the paths that are supposed to be there to find APN information exist.
### Link to debug log

This was done immediately after attempting to re-download the mms message
https://gist.github.com/9059b630c323443b05023790024f61e2

**Comment by mlindsay** [comment]
I have been getting this as well, but I think I just figured this one out! I disabled wifi and retried and all of the failed messages worked, so possibly trying to do MMS over wifi does the wrong thing? Maybe an Android specific weirdness?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
