### ISSUE TITLE
Resiliency against restricted networks

### ISSUE THREAD

**Issue by devurandom** [signalapp/Signal-Android#5679]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In restrictive networks, Signal cannot connect to the server and gives no indication of this issue.
### Steps to reproduce
- Travel to a country or use a network operator that blocks Signal
- Open the Signal app and go to Settings > Linked Devices, or try to send a message
- Notice that messages fail to send after ultra long timeouts and no linked devices are ever listed
- Try to find an indication why this happened
- Find none

**Actual result:** Messages fail to send and devices fail to be enumerated, but Signal gives no indication that it was blocked
**Expected result:** Signal somehow routes messages into even the most restrictive networks, or at least indicates when there is no connectivity with the server
### Screenshots

Not easily possible to show this in a screenshot.
### Device info

**Device:** Samsung Galaxy S4 Mini LTE
**Android version:** 6.0.1 / CM 13 ZNH5Y
**Signal version:** 3.18.3
### Link to debug log

https://gist.github.com/anonymous/c8dbe3ab71e716ea8b92afdc64663313
### Additional information

Using a regular computer in the same network, I was able to gather this information in addition:

```
# curl https://textsecure-service-ca.whispersystems.org:80
curl: (28) Operation timed out after 300xxx milliseconds with 0 out of 0 bytes received
```

The same happens for ports 4433, 8443, 443.

The TCP connection can be established, though:

```
# telnet textsecure-service-ca.whispersystems.org 4433
Trying 54.172.187.107...
Connected to textsecure-service-ca.whispersystems.org.
```

It is only afterwards that any information traveling through it is being blocked.

**Comment by johanw666** [comment]
Which network is this?

To fix real blocking I think some p2p mechanism is required, but that contradicts with Moxies centralism philosophy so I doubt that will be implemented. This discussion has been had before.

**Comment by Dyras** [comment]
https://github.com/WhisperSystems/Signal-Android/issues/1187
That combined with Orbot could be a possible solution to this.

**Comment by devurandom** [comment]
@sweeper3000 I tried that, but could not get it to work at all. It seems after starting up that app nothing can connect to "the internet" anymore, including the Android "does the network connection work" tester (exclamation mark next to the WiFi icon).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
