### ISSUE TITLE
Sorting favorite smilies by absolute occurrence

### ISSUE THREAD

**Issue by fbruetting** [signalapp/Signal-Android#5685]
The favorite smilies at the moment are sorted by "last use". This isn't really good, because they change their position almost every time one uses a smilie – and so everyone has to search the position of the smilie he/she wants to use every time.

I'd like to propose sorting them by absolute occurrency, so that they don't alter their position as often as they do now. It would be much easier, finding the right smilie, because everyone after some time then knows the position, where the smilie should be.

// And 10 times the same smilie in one message should count just as one use, otherwise mass-smilies would alter the ranking a lot.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
