### ISSUE TITLE
Cannot cancel sending of an SMS message.

### ISSUE THREAD

**Issue by awnumar** [signalapp/Signal-Android#5689]
When sending an SMS message, if the message is deleted before it's sent, signal still continues attempting to send it until it either silently succeeds, or fails with a notification.

https://gist.github.com/anonymous/cfab20affdbabeda52d50d6e302986fc

Note that the debug log also also contains the log of an incoming message being shown as a failed outgoing message.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
