### ISSUE TITLE
Selecting status messages with phone numbers is difficult

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#5691]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Selecting group updates, session resets and possibly timer messages (disappearing messages) does not work properly if the message contains a raw (linkefied) phone number and you select by tapping over the text. Selecting outside the text works.
### Steps to reproduce
- make an unnamed Signal contact do a status message
- try to select the status message by tapping on the text

**Actual result:** the status message does not get selected
**Expected result:** the status message gets selected
### Screenshots

![screenshot_20160916-213049](https://cloud.githubusercontent.com/assets/174176/18597797/500b9430-7c58-11e6-8224-b0e90e5f252e.png)
![pokecircus](https://cloud.githubusercontent.com/assets/174176/18597798/518a05a8-7c58-11e6-9336-849e0ad14572.png)
### Device info

**Device:** Nexus 5X
**Android version:** 7.0
**Signal version:** 3.19.0

Related in the past: #2333

**Comment by ByteHamster** [comment]
It's hard even without phone numbers. At least on my device, running 3.20.0, I can only delete disappearing message notices when tapping on the icon. When tapping on the text, the event is ignored.

**Comment by ByteHamster** [comment]
Sorry for the noise. The disappearing message notices contain a "phone numer" - the time.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
