### ISSUE TITLE
MMS only fails from one person to the group

### ISSUE THREAD

**Issue by chiraag-nataraj** [signalapp/Signal-Android#5698]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Group MMS fails to download only from one specific person in the group. Individual MMSs to and from that person work just fine.
### Steps to reproduce
- Ask person to send me an image through MMS
- Works fine
- Then ask same person to send the group a text
- Refuses to download
- Then ask another person in the group to send the group a text
- Works fine

**Actual result:** Can't receive group MMS from one specific member of the group.
**Expected result:** I receive group MMSs from all members of the group without any problems.
### Device info

**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 3.19.0
### Link to debug log

https://gist.github.com/anonymous/5573dd20b72704aa10e67d063da0b829

**Comment by amorshc** [comment]
@chiraag-nataraj  - is the other end of the operator in the group on an iOS device?

**Comment by chiraag-nataraj** [comment]
Nope. They're on Android as well.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
