### ISSUE TITLE
Failure on playback and saving audio attachment

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#5700]
### Bug description

I sent an audio attachment (via Signal Desktop). Neither playback nor saving the attachment works on Signal Android.
### Steps to reproduce
- send audio attachment (via Signal Desktop), including some text
- open conversation on Signal Android
- try to play or save the attachment

**Actual result:** A message is shown that tells that an error occurred during playback/saving.
**Expected result:** The audio file should be played and saved.
### Device info

**Device:** Motorola Moto G 3rd Gen
**Android version:** 6.0
**Signal version:** 3.18.3
### Link to debug log

https://gist.github.com/anonymous/8a05f0d880d4d6c7e140b589124e89cb

**Comment by 2-4601** [comment]
Does this happen with all audio attachments or just with this one?

Tried to reproduce with an mp3 file that I sent from Signal Desktop. Didn't encounter any issues. I tried both with text and without text. (3.18.3, Android 4.0.4)

**Comment by merkste** [comment]
Unfortunately, I cannot reproduce the issue again. It disappeared after  
switching between cellular and wifi network back and forth. All the  
attachments in question are playing fine now. Could it be just some  
connectivity issue in conjunction with an error message too vague?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
