### ISSUE TITLE
Not enough horizontal space for 'Enter name or number' & uniformity issues

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#5703]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Description

The screen space for the string `contact_selection_activity__enter_name_or_number` in the contact list got rather small in width because of the subsequently added dial pad and menu dots. That's a problem for some translations (e. g. the German one).

![screenshot_20160918-233701_cr](https://cloud.githubusercontent.com/assets/12624674/18619369/acd2f26e-7dfa-11e6-8cd2-09fbb7379a45.png)

Thus, I suggest using the same font size, font attributes (and font color) as `ConversationListActivity_search` in the conversations list. I guess this comes down to just removing the attribute for bold text (which should free slightly more space) and adjusting the text color. This would have the additional benefit of a more coherent look.

![screenshot_20160918-233643_cr](https://cloud.githubusercontent.com/assets/12624674/18619374/be0fe37a-7dfa-11e6-962e-eac6a8679e7b.png)

Note also that these two strings don't start at the same horizontal position. Not sure if this should be changed, as the positioning of `ConversationListActivity_search` seems to be aligned with the conversations.  On the other hand, e. g. the string "Signal" is positioned more to the left, so all 3 strings currently have a different horizontal position:

![screenshot_20160919-000739_cr](https://cloud.githubusercontent.com/assets/12624674/18619472/91bd3612-7dfd-11e6-984b-832a1157f9d4.png)

**_Summarized, probably it would be best to align them all (and similiar ones in other activities) while a) leaving the most space for the search fields and b) at the same time, leaving enough room between "back" buttons and the search fields, so they don't interfere with each other.**_
### Device info

**Device:** Google Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.19.0

**Comment by FeuRenard** [comment]
I already played around with the font size of the contact search hint in #5412. Keep in mind that the screenshots there are taken from a 3.5 inch screen device.

**Comment by RiseT** [comment]
Thanks for the info! So what do you think about adding the following two changes to #5412 :

- Removing the bold attribute for `contact_selection_activity__enter_name_or_number` (the search hint is bold, no? Or does it just look like it because of the font size?)
- Adjusting the text color so it's in line with `ConversationListActivity_search`

The horizontal alignment could be done in a different PR - if wanted.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
