### ISSUE TITLE
Add blank sheet to scribble mode

### ISSUE THREAD

**Issue by peterpanondrugs** [signalapp/Signal-Android#5711]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Steps to reproduce
- sending a picture allowing you to add :  own painting/drawing/ink to a picture / blank sheet 
### References
- google allo, wire,...

![01](https://cloud.githubusercontent.com/assets/8776733/18756256/8c0181d4-80ef-11e6-9393-663076e74c1f.gif)

**Comment by 2-4601** [comment]
1b44bdcd3cafee26f08327f4ba6d9462d5713875 added everything else in this feature request except the ability to draw on a blank sheet.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
