### ISSUE TITLE
Sync deleted messages

### ISSUE THREAD

**Issue by Patrick010** [signalapp/Signal-Android#5713]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Since I dint find any discussion forum so I'm posting here;

I have both the Android app and Windows client installed and messages sent are being synched between the two. Thing is, deleted messages are left on the other synched device, which I find a serious security issue. Is this by design or a flaw?
### Steps to reproduce

=Have both the Android App and Windows client installed
- Send a message on either Android or Windows
- Find the sent message replicated on the other device
- Delete the message on either device
- Check the other device and find the message you just deleted still here!

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- If I delete a message, on whatever device, I expect it to be gone on all devices. Should be obvious as sending messages are replicated, so why not deleting??
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by 2-4601** [comment]
https://github.com/WhisperSystems/Signal-Desktop/issues/643

**Comment by Orbixx** [comment]
At the very least Signal Desktop should also be able to delete messages without any sync. You can't do that either.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
