### ISSUE TITLE
 Incorrectly called buildLayer on View

### ISSUE THREAD

**Issue by dschrempf** [signalapp/Signal-Android#5715]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In the Application Manager, when killing Signal, I get the following warning in `logcat` and the Application Manager closes.

```
09-23 11:109-23 11:12:25.876  1330  1474 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-23 11:12:25.876  1330  1474 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

This only happens with Signal.

I am using CM13 with Android 6.0.1
### Steps to reproduce
- Open Signal
- Open Application Manager
- Kill Signal

**Actual result:**
- The Application Manager closes.

**Expected result:**
- The Application Manager should not close and I should be able to kill the next application.
### Screenshots

None.
### Device info

**Device:** Samsung S4 Mini LTE
**Android version:** 6.0.1
**Signal version:** 3.19.0
### Link to debug log

No debug log available because Signal get killed.  See logcat from above, please tell me if I can provide further logs.

**Comment by johanw666** [comment]
This is done for a reason: in https://github.com/WhisperSystems/Signal-Android/issues/1037 Moxie wrote:

> This is the consequence of a workaround for an Android OS bug that was causing TextSecure to miss incoming messages after swiping from the recent tasks list. I agree it's unfortunate, but it's better than the alternative, and I don't think there's anything we can do until Android fixes their bug.

**Comment by sedrubal** [comment]
I can't imagine that there is such a huge bugs for more than 3 years in all android versions without a working workaround. Why doesn't OpenWhispersystems take this issues important? There are so many github issues complaining about this behavior. It looks like people dislike this behavior.

**Comment by nrizzio** [comment]
@sedrubal Please don't bump issues. Closing the app switcher *is* the workaround to a different but worse problem (not receiving messages at all when the app is closed), and your insinuation that OWS doesn't care is quite rude and condescending especially considering that they have only one Android app developer who can only do so much in one day. The bug isn't even in code that OWS has control over (it's Google's). I encourage you to read the contribution guidelines, specifically the part about how bumping issues doesn't help anybody and where *discussion* of issues can go (which for the most part is at whispersystems.discoursehosting.net).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
