### ISSUE TITLE
Message send / receive error between Android iOS

### ISSUE THREAD

**Issue by towlie** [signalapp/Signal-Android#5722]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I was in the middle of a conversation until I noticed my messages didn't get ticks (so it looked like there aren't send to the server) I had to delete them to send messages again.

The other side was using the iOS version of signal and got an endless vibrating phone and the message
that it received faulty messages (my unsend messages?). He had to kill the app to make it stop. After that he send me messages about that incident which are shown as delivered but I never received them.

The only thing I could observe in that conversation was that one message got only 1 tick but messages after that message already had 2.
### Device info

**Device:** Xiaomi Redmi Note 3
**Android version:** 6.0.1
**Signal version:** 3.19.1
### Link to debug log

This was done after a restart of the app. While it was still trying to send those faulty messages.

https://gist.github.com/anonymous/7ee5012a7e3faf4e2dda8868651755c8

**Comment by towlie** [comment]
Some small addition. We both got broken encryption messages after that and had the Restart encryption.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
