### ISSUE TITLE
Hyperlink previews

### ISSUE THREAD

**Issue by rotojp** [signalapp/Signal-Android#5724]
I have:
- [x]  searched open and closed issues for duplicates
- [x]  read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
## Bug description

When sending hyperlinks, Signal currently displays no previews. 
This may be a feature lowering adaptation of Signal, as with #5445.
## Screenshots

_Google Allo_

![google-allo](https://cloud.githubusercontent.com/assets/8006669/18869210/9b81b72c-84ab-11e6-9970-a7dbf468ac62.jpg)

_Telegram_

![download](https://cloud.githubusercontent.com/assets/8006669/18869457/b827f0d4-84ac-11e6-927f-c960da539a28.jpeg)

**Comment by TimesEnemy** [comment]
Greets.

I would rather a feature like this be optional and off by default.  It will just generate more traffic and create unnecessary potential security holes.  Perhaps when a link is created or detected by Signal, Signal could offer a checkbox or option to include a hyperlink preview into the mix.

**Comment by kmindi** [comment]
I agree with @TimesEnemy that this is at least a privacy issue and can also be a security issue concerning automatic loading of content from literally any source.

**Comment by 2-4601** [comment]
WhatsApp does this on the client-side and only for the sender. When the sender types a link in the compose box WA detects it and fetches a preview.

**Comment by altring** [comment]
Desktop version also needs this :)

**Comment by Trolldemorted** [comment]
Having the sender generate the preview is reasonable, i guess. A checkbox (that remembers the previous choice) would be great, as i'd propably never want to use this feature.

**Comment by E3V3A** [comment]
Preview is a horrible privacy killer. Why even bother to use Signal if you want this? Just use Fb messenger or WhatsApp.

**Comment by rmueller83** [comment]
At least in iMessage this feature sucks ;-) [http://rsmck.co.uk/blog/imessage-preview/](url)

**Comment by oittaa** [comment]
@E3V3A what's wrong with the approach proposed in this thread?

1. Make the feature optional.
2. Sender device (which obviously trusts the the link more or less) fetches a preview and packs it in the message.

To me that looks like a zero privacy issue for the recipient. The current model sucks from usability perspective.

1. Take a screenshot from a webpage.
2. Attach the screenshot to a message.
3. Add the correct URL to the message.

Only the last step should be needed in a modern messenger.

**Comment by l0rn** [comment]
i like the proposal of @oittaa . Eleminate the privacy issue by only letting the sender device download stuff and put the result in a message. I'd like to see that feature for random cat content gif urls I paste in the text field. Like Telegram does, but with only let my device download it.

**Comment by mderazon** [comment]
This is one of my favorite features in other IMs. I see some comments about security / privacy issues but they are not giving any examples. I can't think of any issue with that and i'm interested to know.

Actually, I find myself often not needing to open the link because I already know what the link is about so if anything, it's a 👍 for privacy / security :-)

Anyway, it's a huge plus for usability IMO.

**Comment by snaggen** [comment]
There is a library for fetching the preview information like this
https://github.com/LeonardoCardoso/Android-Link-Preview/

So when someone pastes/type in/shares a link, it shouldn't be that hard to use this to fetch the preview information. Then this could be sent as some kind of attachment with the link.

**Comment by Hooloovoo** [comment]
I would also love to see this.

Like others, I cannot see a privacy/security issue -- if I am sharing the link then I have visited it on my phone and there is no additional privacy risk by loading those links again through Signal (though Tor browsing would have to be managed).

As somebody else said, there is much more risk in me clicking an unexplained YouTube link that, in hindsight, I would rather not have viewed on work WiFi etc.

**Comment by FeuRenard** [comment]
This feature in WhatsApp got some attention here:
https://twitter.com/mulander/status/874370124932943874

The WhatsApp app seems to attempt fetching a preview while you are typing a URL, like:

- `https://github.com/W`
- `https://github.com/Wh`
- `https://github.com/Whi`
- ...
- `https://github.com/WhisperSystems`

Fetching is done on the sender's phone as suggested in this thread but the user agent seems to be exposed under certain conditions. If the user types the URL manually or pastes it from somewhere (not a browser) he/she didn't necessarily visit the URL (at least from the device he/she is using at the moment). If we decide to implement this, we should be careful.

**Comment by rdesimone** [comment]
IMO this feature is needed especially for users willing to switch from WhatsApp.

**Comment by Meteor0id** [comment]
Additional idea:
When sharing a weblink, Twitter for example generates an image preview of the webpage, which automatically focuses on a cetlrtain place of the webpage. This place is usually the header text of the article or blogpost.

For signal I would propose to do a simulair thing, but with one addition: allow to user to edit the scroll position of the preview.

More in detail:
- when a weblink is placed in a message, genarate a screenshot of the entire page.
- look for the position of the header. To do this pharse the webpage for elements such as <main> <div id='main'> <div class="main"> <header> <article> <h1> and microdata attributes.
- cut the preview at the position which appears to be most relevant, and add this cut preview to the concept message
- add an edit button to this concept preview. The user may click this button, and the full page preview will be shown to him. He can than manually select on which area of the page he wishes the preview to be focussed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
