### ISSUE TITLE
Signal loses contact names on owncloud account remove and readd

### ISSUE THREAD

**Issue by mehlis** [signalapp/Signal-Android#5730]
### Bug description

when deleting the only andoid account (in my case nextcloud) and readd it via davdroid, Signal app loses connections between Numbers and Names
### Steps to reproduce
- have contacts via davdroid
- delete davdroid account from phone
- readd account via davdroid

**Actual result:** All contacts in signal list are only the phone numbers, no names
**Expected result:** Signal matches numbers with names, and displays names
### Device info

**Device:** Google Nexus 5X
**Android version:** 7
**Signal version:** 3.91.1

**Comment by art1fa** [comment]
Had the same issue some months ago, needed to manually rematch all the Signal contacts. I'm not sure though if this can be fixed on the SIgnal side or if the Android system or DavDroid / Contacts app is responsible.

**Comment by haffenloher** [comment]
> when deleting the only andoid account (in my case nextcloud)

That's strange, there should have been a Signal account as well.
What happens if you open Signal, tap the blue pencil icon and pull down the contact list to refresh it? Does that fix your problem? Does it (re)create a Signal account on your Android system?

**Comment by mueller-ma** [comment]
You could try https://github.com/WhisperSystems/Signal-Android/issues/5737#issuecomment-251777516

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
