### ISSUE TITLE
Setting Signal's language to 'default' sets the language active when last closing Signal (Android 7.0 only)

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#5738]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Setting Signal's language to 'default' after changing it to something else sets Signal's language to the one that was set at the last time Signal was closed - not (necessarily) Android's system language.

When set to 'default', Signal definitely use the language active when it was last closed. I've tried a couple of combinations when changing the language, and that has been the common denominator.

I'm experiencing this issue on Android 7.0 only. This used to work properly in prior Android versions.
### Steps to reproduce
- Open Signal
- Change language to some language that is not your Android's system language
- Close Signal by tapping Android's Back button a couple of times
- Open Signal again
- Change language to 'default'

**Actual result:** The language used in Signal is now the one that was active when Signal was closed
**Expected result:** The language used in Signal should be the one set as system language in Android
### Device info

**Device:** LG Nexus 5X
**Android version:** 7.0.0
**Signal version:** 3.19.1

**Comment by RiseT** [comment]
There's definitely a bug, but slightly different than initially described. Have to clarify the steps to reproduce. Closing for now and re-opening again soon.

**Comment by 2-4601** [comment]
On my brief exposure to Android N and Nexus 5X (what a horrible device:) I think I encountered something like this bug.
I had system language set to English (US). I set Signal language to non-English. Then I set Signal language back to default but it didn't change to English (US) but stayed on the non-English language.

**Comment by RiseT** [comment]
@2-4601 I'm definitely interested in your experiences regarding the Nexus 5X as I purchased one myself a couple of days ago but have to send it back for a new one because of some serious issues. Don't know where to discuss this, though.

**Comment by RiseT** [comment]
Regarding the bug it seems like this is not bound to English. One has to do  a certain sequence of steps that include exiting Signal completely and opening it again that lead to Signal staying at its priorly set language although it's set to to the default language.

**Comment by RiseT** [comment]
Pretty long title, but don't know how to describe this in a shorter way...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
