### ISSUE TITLE
Too many permissions

### ISSUE THREAD

**Issue by daald** [signalapp/Signal-Android#574]
deleted

**Comment by ogai** [comment]
![screenshot_2015-07-24-15-52-14](https://cloud.githubusercontent.com/assets/753094/8875925/9d395346-321c-11e5-902b-c0ea84aca5e5.png)

**Comment by daald** [comment]
Seriously: There is no need to load Photos for a Messaging application. Nor does it need to do phone calls. What I mean with my report: Googles permission tool is quite intransparent (both the new and the old version). But a serious application could write: "We need phone permission because we want wo call home." - "We need Location because we offer that data to our ad partners" - or more seriously: "We need contacts because we want to offer you your address book in our application".
But for me it doesn't matter anymore. I chose to not use this application.

**Comment by moxie0** [comment]
@daald ok then why are you still posting here?
