### ISSUE TITLE
crash with IllegalStateException after connecting signal desktop

### ISSUE THREAD

**Issue by mutax** [signalapp/Signal-Android#5744]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Signal on android crashes directly after start or as soon as network connectivity ist established.
It startet after I installed signal desktop in chrome and clicked on 'sync contacts with phone'.
It seems as if a network request to retrieve the data crashes the app on the phone.
Groups are synced to chrome, individual contacts are not.
### Steps to reproduce
- install signal desktop in chrome
- connect android phone via scanning of QR code
- request contact sync to chrome

**Actual result:** 
crash as soon as I enable wifi or if I start the application on android with enabled network. 

**Expected result:** 
Android app not crashing without user interaction
### Device info

**Device:** HUAWEI HUAWEI Y360-U61 (Y360-U61)
**Android:** 4.4.2 (C577B111, Y360-U61V100R001C577B111)
**Memory :** 17M (31.42% free, 128M max)
**Memclass:** 128, low-mem device
**OS Host :** ubuntu
**App:**     : Signal 3.19.1

```
--------- beginning of /dev/log/system
E/AndroidRuntime( 5993): FATAL EXCEPTION: JobConsumer-2
E/AndroidRuntime( 5993): Process: org.thoughtcrime.securesms, PID: 5993
E/AndroidRuntime( 5993): java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime( 5993):    at android.os.Parcel.readException(Parcel.java:1480)
E/AndroidRuntime( 5993):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
E/AndroidRuntime( 5993):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
E/AndroidRuntime( 5993):    at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
E/AndroidRuntime( 5993):    at android.content.ContentResolver.query(ContentResolver.java:462)
E/AndroidRuntime( 5993):    at android.content.ContentResolver.query(ContentResolver.java:405)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientProvider.getIndividualRecipientDetails(RecipientProvider.java:136)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipientDetailsSync(RecipientProvider.java:129)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipient(RecipientProvider.java:82)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipients(RecipientProvider.java:96)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientFactory.getRecipientsForIds(RecipientFactory.java:109)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.recipients.RecipientFactory.getRecipientsFromString(RecipientFactory.java:84)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.getColor(MultiDeviceContactUpdateJob.java:144)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.generateFullContactUpdate(MultiDeviceContactUpdateJob.java:113)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.onRun(MultiDeviceContactUpdateJob.java:72)
E/AndroidRuntime( 5993):    at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 5993):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 5993):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

```

**Comment by moxie0** [comment]
Weird thing about this is that it's a crash in the android code, not ours.

**Comment by mutax** [comment]
For me it looks like a database query is made to get the users and the cursor in the sqlite is not setup correctly, e.g. the code tries to get more entries from the query although the query is not yet setup correctly.

**Comment by moxie0** [comment]
yeah we're making the query to the system's contact provider, and the crash is happening over in the provider

**Comment by mutax** [comment]
bump? would _really_ be nice so see at least a try catch around that so I can finally use it again...

**Comment by Trolldemorted** [comment]
@mutax does this still happen?

Would you install a self-compiled version of Android (or attach a debugger) and tell us the value of uri?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
