### ISSUE TITLE
Messages do not show up on the phone unless marked read in the desktop app

### ISSUE THREAD

**Issue by rochelmeyer** [signalapp/Signal-Android#5745]
Bug description

Describe here the issue that you are experiencing.

My phone was online all the time today, but did not receive messages. At home i started the desktop app and saw a message that had been sent "5 hours ago". Answering this message caused the message to appear on the phone. It had not been there until then.
Steps to reproduce

```
using hyphens as bullet points
list the steps
that reproduce the bug
```

Actual result: Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Messages only show up when the phone is in the same network as a desktop / laptop with Signal App up and running.

Expected result: Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Phone should receive and show messages immediately and independent from the desktop app.
Screenshots
Platform info

Operating System: My Operating System A

Kubuntu Linux 16.04.1 LTS, (all updates up to date)

Browser: My Browser X.Y.Z

Chromium from the ubuntu repositories
Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Signal version: Z.Y.Y

Signal Version 3.19.01, Android M (Cyanogenmod 13)
Link to debug log

https://gist.github.com/anonymous/4d76a1221e21b816a44a258ae1f1a2c9

**Comment by 2-4601** [comment]
If you can consistently reproduce this, could you also post a debug log from your Android client?

**Comment by rochelmeyer** [comment]
I must admit, that I'm a user, not a developer. I have no idea where to
find that log and how to post it. Can you give me a hint?

**Comment by rainerzufall** [comment]
@rochelmeyer 
You can find the guidance on "How do I send a debug log?" at their support page: http://support.whispersystems.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-

**Comment by rochelmeyer** [comment]
Thankd, that was really easy. Here it is:

https://gist.github.com/anonymous/2a7e3c9b23c4ffa14a9578a8d99bf398

Device: Samsung Galaxy S3 (GT-i9300)

Android Version 6.0.1

CyanogenMod Version 13.0-20161001-NIGHTLY-I9300

Baseband Version I9300XXUGNAB

Kernel Version 3.0.101-CM-g43c083e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
