### ISSUE TITLE
Inconsistency | remove save button for disappearing picture messages

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#5757]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

There seems to be a feature inconsistency: If one sends a disappearing picture message, there's still the save button for the picture. This somewhat contradicts the idea of the message being temporary.
### Steps to reproduce
- Set the message disappearing timer to 10 seconds
- send picture
- as the receiver, click the picture while the count-down is running. Press the save button

**Actual result:** The picture gets saved
**Expected result:** There should not be a save button if there's a timer set for the message.
### Device info

**Device:** Nexus 4
**Android version:** 6.0.1
**Signal version:** 3.20.0

**Comment by sweeper3000** [comment]
Only problem with this is one can easily take a screenshot of the picture. It would give a false sense of security.

**Comment by johanw666** [comment]
Disappearing messages is a protection against sloppy operational security of the receiver, not a protection against deliberate actions of the receiver. That is a battle you cannot win, see Snapchat for an example of someone loosing the arms race.

**Comment by motatuc** [comment]
@sweeper3000: true, a screenshot is most likely possible. But this applies to the messages itself as well.

@johanw666: Right, disappearing is also because of the sloppyness. But this sloppyness also applies for pictures. So removing the save button seems to be a supportive move in this direction.

**Comment by FeuRenard** [comment]
How about a compromise between removing the button and leaving everything as is?
There is already a warning when you attempt to save an image to the device storage. We could extend this warning addressing this inconsistency.

**Comment by motatuc** [comment]
@FeuRenard: I agree with you on the messge text copying - this should not be changed in my opinion.
About the save button, let me ask the other way around: Why keeping the save button for disappearing picture messages?

**Comment by FeuRenard** [comment]
I would not want to make keeping an image more difficult for the user. He will succeed in keeping it anyway if he wants to (screenshot).

Privacywise the screenshot even has the disadvantage, that it possibly leaks the conversation partner as the `MediaPreviewActivity` shows it in the action bar.
Saving an image currently doesn't show information about the sender or recipient. So we have another argument for saving: In the device storage the saved image will be out of context. It will be decoupled from the conversation after disappearing in Signal.

**Comment by nrizzio** [comment]
A simple warning would probably be the best way to go:

> This message is set to expire in %time%.
Are you sure you want to continue?

**Comment by user7743** [comment]
I agree with the OP - I would like a way to prevent the picture being saved if the chat is using disappearing messages. Whilst I agree there will be ways to circumvent such controls, I feel its better to make it harder for less security savvy users to make such compromises in operational security. Maybe the compromise should be an option in the definition of the chat - to be able to save or not.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
