### ISSUE TITLE
Audio attachment disappears when sent

### ISSUE THREAD

**Issue by rrthomas** [signalapp/Signal-Android#5773]
I have:
- [x ] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When I attach an audio clip to a message, it disappears when I hit send.
### Steps to reproduce
- Touch the attachment button
- In my case, I use Sound Recorder. Record and save some audio.
- The audio appears in the message window. I can play it back. The attachment has a red X button, I guess so I can delete it if I decide not to send it.
- Type some text for the message (or not, doesn't matter).
- Hit Send.

**Actual result:** The message is sent. Any text appears as normal. The message is described in the chat summary screen as "Media message" if there is no text. However, the audio attachment has disappeared. The recipient cannot see it either. The speed with which the message is sent suggests the audio was not sent (it is very fast, unlike if, for example, I attach a photo).
**Expected result:** The audio attachment should appear after sending, both on my phone and the recipient's phone.
### Screenshots

Doesn't seem to be useful in this case.
### Device info

**Device:** Fairphone FP1U
**Android version:** 4.2.2
**Signal version:** 3.19.1
### Link to debug log

https://gist.github.com/9abedceec16e680c7b1a5e5a6240fcdf

**Comment by 2-4601** [comment]
Can you consistently reproduce this or was this a one time thing? What's the file and codec type of the audio?

**Comment by rrthomas** [comment]
It happens 100% of the time. The file type is Ogg, whatever Sound Recorder outputs by default, I guess.

**Comment by 2-4601** [comment]
Tried to reproduce but I can't even select an ogg file as an audio attachment? And if I try to share it from a file manager it doesn't appear in Signal.

Tested on ~~potato~~ ZTE Open C, CM13 (6.0.1)

**Comment by rrthomas** [comment]
I just used stock Sound Recorder, and recorded a new file. As I said in my original report, it shows up fine in the message thread, and I can play it there, so Signal seems to have no problem with it at that stage. It's only when I try to send it that it disappears.

**Comment by haffenloher** [comment]
Can reproduce with the exact same steps. Here's my log containing a `SocketTimeoutException`:

https://gist.github.com/anonymous/48f2b7623f94ff6aa06095d5745eff7f

**Comment by i7u** [comment]
Potentially related to https://github.com/WhisperSystems/Signal-Android/issues/4665 ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
