### ISSUE TITLE
Check if bitmap is not null on BitmapTransformation.transform()

### ISSUE THREAD

**Issue by fischli** [signalapp/Signal-Android#5776]
### Bug description

I'm not able to start Signal anymore. It always crashes on start by a NullPointerException caused by a BitmapTransformation. This bug is not related, but similar to #5193
### Steps to reproduce

Not able to reproduce the crash on another device because I can't locate the involved attachment which causes the fatal crash.
### Device info

**Device:** Motorola E Surnia
**Android version:** 6.0.1 (CM13.0)
**Signal version:** 3.19.1
### Link to debug log

I missed it to get a full log but I got the relevant stacktrace
https://gist.github.com/fischli/4af54fec0bb7457843f908ee46d2e9d0
### Proposal to fix it

Worked for me.
https://gist.github.com/fischli/237faafe00edfd1aa0b566bbfe673930

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
