### ISSUE TITLE
Signal sends very underspecified SMS during registration

### ISSUE THREAD

**Issue by instagibbs** [signalapp/Signal-Android#5778]
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

The SMS sent during registration has the text "Your TextSecure verification code: <number>\"

This is very generic looking and during usage I was socially-engineered accidentally.

My recommendation is that the text's message be much more specific in what data that is. Perhaps call it "private registration" code or something which tells people never to share the data? Usually upon registration the message is immediately digested by the Signal app if on the same device, which led to my unfamiliarity.
### Steps to reproduce
- User B wants to add user A to their contact list
- B is a bit confused, hadn't actually registered yet
- B asks for my phone number, receives it, punches it in
- Signal servers now text the above text to user A
- User A thinks it's slightly weird that he has to read back a code to add himself to B's address book, but unfamilarity with iOS platform makes it semi-plausible.
- User A reads off the code in person

**Actual result:** B has control of A's keys(?) A little hard to say actually what the net effect was other than I had to reinstall the app and register/generate a new keypair.
**Expected result:** A adds B into address book
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
