### ISSUE TITLE
Disappearing messages sometimes don't disappear

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#5790]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Some disappearing messages are still visible after their expiration time has passed. They only disappear after force-closing Signal and reopening it.
### Steps to reproduce

I've observed this happening twice but no clear way on how to to reproduce
- receive/send disappearing messages
- wait until the messages have passed their expiry
- open the conversation with the expired disappearing messages

**Actual result:** The messages are sometimes still present
**Expected result:** The messages should have disappeared
### Screenshots

I opened the message when it was received at 8:04pm, the message I had sent a few hours earlier was gone (as expected). The received message was still present when I opened the conversation again at 11:21pm (over 3 hours later). Disappearing time was 30 minutes and the timer had expired (the hourglass is empty, the message details say "Disappears 1 second").

![screenshot_20161019-232110](https://cloud.githubusercontent.com/assets/106307/19516272/bee3711a-95ea-11e6-9d46-0649858eb4b9.png)
### Device info

**Device:** BlackBerry PRIV
**Android version:** 6.0.1
**Signal version:** 3.20.4
### Link to debug log

https://gist.github.com/anonymous/0e3155fbb68a7ca2039be761bf1bfc7f

**Comment by Dyras** [comment]
I've noticed the exact same thing. I've set Signal to use a password, if that could be why.
https://gist.github.com/anonymous/8fc9bea189c74f458bec8d5e37dd66c8

**Comment by petcap** [comment]
I can confirm this behaviour on Android as well, a very small number of messages never disappears. I do not use a password for Signal. Currently on stock Android 7.0 with October 5:th security patches.

**Comment by imarkskinner** [comment]
Can also confirm on android 7.1.1 Signal version 3.21.3 october patches installed

**Comment by riyapenn** [comment]
Samsung Galaxy Note 7 Edge, running Android 6.0.1 on Verizon. Android version of Signal is 3.25.4
https://gist.github.com/anonymous/d876044f91deb9b560dc5d9035f7afe4 (this log does not go back far in time when the messages actually were meant to disappear as user expected it to disappear "3 hours ago" from the time of sharing the log)

**Comment by Enekk** [comment]
This has been open for quite some time, so I just wanted to throw my hat into the 'me too' ring.  Android 7.1.1 on a Nexus 6p.  I am running Signal 4.0.0.

**Comment by cwaldren** [comment]
Confirmed. Was able to trigger disappearing after I sent a new message in the conversation. 

Moto G 3rd gen, Android 6.0, running Signal 4.01.

**Comment by jeremymasters** [comment]
@Enekk @cwaldren Debug logs are really what's needed here.  I know the devs don't like the "me too" posts.  You can get the same effect of the "me too" by using the emoticon reaction for ones you have but don't have extra data or logs.

**Comment by Enekk** [comment]
Here are the debug logs captured at the moment where this was happening to me.  https://gist.github.com/anonymous/ca571f2a3e6bd763956b4530be274053  I believe the message was at around 20 minutes old even though it should have been culled after 5.

**Comment by jeremymasters** [comment]
Running into this too intermittently. Almost seems like the timer starts over.

https://gist.github.com/c95d614776dbc45e9969634a5113d000

**Comment by micressor** [comment]
I also confirm this on android 7.1.2 (patch level 5. Dez 17) with Signal version 4.13.7.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
