### ISSUE TITLE
Please support SVG (or fix mobile/desktop inconsistency)

### ISSUE THREAD

**Issue by btittelbach** [signalapp/Signal-Android#5791]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

mobile Signal does not support displaying SVG while desktop Signal does.

This was originally mentioned in [Bug 5046](https://github.com/WhisperSystems/Signal-Android/issues/5046) but only the crash was fixed and the bug closed afterwards so this is an explicit feature request.
### Steps to reproduce (some drama added)
- Send a SVG image to someone from desktop client
- See the SVG image render perfectly in the desktop client
- wonder why other person is confused
- check your phone
- see that SVG image is neither displayed nor viewable on mobile

**Expected result:** render SVG on mobile client

**Unless:** If adding SVG support is a security risk that might allow an attacker to gain access to the chat history, disable SVG support on desktop client instead.
### Screenshots

svg on desktop client:
![svg_desktop](https://cloud.githubusercontent.com/assets/635660/19519086/91d5b4ce-960a-11e6-8d99-16ad67717d7f.png)

svg on mobile client:
![svg_mobile](https://cloud.githubusercontent.com/assets/635660/19519085/91d1fa50-960a-11e6-96db-3f5620910192.png)
### Device info

**Device:** Sony Xperia Z1 C6903
**Android version:** 5.1.1
**Signal version:** 3.20.4

For the curious: Image is a proposed open source experiment of realraum

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
