### ISSUE TITLE
Support ad hoc groups

### ISSUE THREAD

**Issue by nemequ** [signalapp/Signal-Android#5792]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---

@gerdneuman already described this well in https://github.com/WhisperSystems/Signal-Android/issues/3301#issuecomment-169859856 (which I came across while searching for this issue):

> What I would like to have is an easy quick way to send a message to a small "instant" group, mostly just 2 people. E-mail has the perfect UX for this: Just press a :heavy_plus_sign: button and add another recipient. Recipient can then reply to all and see who has been informed.
> 
> In Signal we have single messages (resembles single mails) and group messages (resembles mailing lists).
> 
> But there is no easy way to sent a "Hi, we meet at five" to 2 people spontaneously without setting a up a static group before – and also allowing one of the 2 recipients to answer "No, let's meet at six" and all get the message and all know about it. I do not see how broadcast list could fulfill this user story.

This isn't really the same thing as #3301, so I'm creating a separate issue.

**Comment by Coldfirex** [comment]
This would be very helpful.  It is a pain to have to create static groups when I need to send something out quick.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
