### ISSUE TITLE
SMS Messages sent with Google Assistant do not show up in Signal

### ISSUE THREAD

**Issue by Flat** [signalapp/Signal-Android#5803]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When a text is sent through Google Assistant the sent message is not shown in Signal/Updated into signal's SMS database.
### Steps to reproduce
- send text through Google Assitant
- open signal
- read messages
- notice sent text isn't there.

**Actual result:** Sent text not in text log
**Expected result:** Sent text should be shown in signal message logs
### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.20.4

**Comment by FeuRenard** [comment]
Related to #218 and #4037.

**Comment by videogmike** [comment]
I've seen a few of these posts that suggest this isn't an important feature or hard to implement. Instead of being automatic it could be a button in settings to merge any new messages in the SMS database into the Signal database. Rather than reimporting the whole thing. 
I want to use Signal as my primary SMS app but if I'm driving and use Google to send an SMS to my wife hands free, it would be great if that showed up in signal.

**Comment by ikeahloe** [comment]
This is holding me back from using signal as main messenger. 

( Also I don't like that it doesn't use default emoji, but that's    a small thing )

**Comment by videogmike** [comment]
That's a setting you can tell it to use default emoji

**Comment by ikeahloe** [comment]
Thanks. Didn't meant to derail comments about the original issue.

**Comment by Terafloppy** [comment]
This is a serious issue for me as well.  I need to be able to send and reply to messages hands free while driving.

I'm using Android Auto and can not initiate a Signal message.  However, I can reply to one.  Please help!  If this can't be fixed.  I won't be able to us Signal as my replacement SMS app.

**Comment by nagaboto** [comment]
This is an important issue to me.  Using new Pixel XL phone.

**Comment by AMP3D** [comment]
The Nissan Rogue sends an auto-reply ("I'm driving.") for incoming texts when paired with a phone via BlueTooth. This auto-reply does not work using Signal Messenger and a Samsung Galaxy S5 (Android Marshmallow). I can see this being a potentially major safety issue.

**Comment by jeffjonez** [comment]
Would love to see this working. I've disabled the Google sms app, and still Google voice command finds a way to bypass signal. :/

**Comment by joeykrim** [comment]
I'm having the same experience on the Pixel XL phone and added some more details in a related issue:
https://github.com/WhisperSystems/Signal-Android/issues/218#issuecomment-299106117

> The last question seems to be whether it's possible to have voice interactions exposed to an application without Google's explicit support.
> On a Google Pixel XL (Android 7.1.1), the voice command "Send a text message" defaults to the Android Messenger application and ignores Signal, even when Signal is marked as the default application. In addition, "Sent a text message with WhatsApp" works, but "Sent a text message with Signal" results in a web search.
> 
> Google has listed some voice interactions that are available, but they don't explicitly list sending a text message/SMS, as a possible voice interaction: https://developers.google.com/voice-actions/system/.
> 
> After quickly going through their Codelab tutorial (http://io2015codelabs.appspot.com/codelabs/voice-interaction#1), I don't see how to bind to the initial and specific voice command "Send a text message". The codelab example does show how to handle the intent(responding via voice and confirming action completed) after Google passes the intent to the application from the voice command.

**Comment by jcollum** [comment]
LG G5, Android 7, Signal 4.16.9

### Bug description
Messages sent via Google Now voice assist do not show up in signal but are sent

### Steps to reproduce
- start Google Now by long pressing on the Home button
- say "Send text message to Alice" 
- dictate and confirm sending message 
- open Signal

**Actual result:** Message does not show in list of messages sent to Alice in Signal. Message does show in messages sent to Alice in default messaging app. 

**Expected result:** All text messages are in the same place.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
