### ISSUE TITLE
Do not truncate animated GIFs (GIPHY)

### ISSUE THREAD

**Issue by Norbert80** [signalapp/Signal-Android#5809]
Signal 3.21.0 displays truncated thumbnail previews of GIF animations. So the user always has to open them in full screen to watch the complete thing.

Animated GIFs in conversations are only fun if they can be watched completely inline.

**Comment by 2-4601** [comment]
The square clipped thumbnails are expected behavior according to this https://github.com/WhisperSystems/Signal-Android/issues/3579#issuecomment-120036493
> I believe this is the intended behavior. The aspect ratio should be correct, but the actual bounds are set so that thumbnail previews are always square.

**Comment by rezadu** [comment]
+1 for this. Still happens in 3.28.4.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
