### ISSUE TITLE
Self-sent messages do not appear as unread

### ISSUE THREAD

**Issue by brinerustle** [signalapp/Signal-Android#5821]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

when sending a message to one's own account, it does not appear as unread in one's inbox
### Steps to reproduce
- make a contact with your own number
- send yourself a message

**Actual result:** 
When you return to your inbox, you see that you have already read the message you intended to send yourself.

**Expected result:** 
You should be able to send yourself a message as a reminder, as one can do in email platforms, etc, and by showing the message as read, this is not possible.
### Device info

**Device:** Huawei P8 Lite
**Android version:** 6.0
**Signal version:** 3.20.4

**Comment by FeuRenard** [comment]
Related #3877

**Comment by 2-4601** [comment]
I don't see how this would work? When you send a message to yourself you are already in the conversation when you "receive" it and thus see it immediately. Same happens when you are in a conversation with someone else and they send you a message – it gets read right away.

**Comment by FeuRenard** [comment]
We would need #685 implemented.

**Comment by brinerustle** [comment]
@2-4601 To understand how this might work, it helps to think of cases in which you would send yourself a message, and why you would want a notification:

1) Send data to another device with the same signal account: You probably want a notification, so when you get to the other device later, you remember that you sent it. 

2) Someone has your other device, and you want to message that person from your own account. If it's immediately marked as read, the person will not see it as a notification on your other device, making a conversation difficult.

3) Writing a draft. Sometimes a message might be hard to write in a single sitting, and by sending yourself a half-written message, you get the chance to use your "solo thread" as a draft folder without worrying about losing that data if your terminal powers off. When you get back to power, a reminder that there's a message there would be useful.

4) Writing a draft: Sometimes you have data in another android app that you want to use in signal. Not all data gets formatted as we would expect between apps when we choose the share button. By sending it to yourself in signal, you get to see if the data is sent in the correct format and avoid sending garbled content. 

In any case, when you write a message to yourself, you are not usually waiting for a response, but sending yourself a reminder or putting something in a place to more easily find it again. In email programs like gmail, when you send yourself a message, you still get a notification even if the thread is open and you are seeing it at the time.

**Comment by brinerustle** [comment]
@FeuRenard : a solution to #685 would be great - but I can think of a simpler solution for this special case: 
1) Upon opening a conversation with ourself, note that.
2) Upon sending, check to see if it's a conversation with self, and if so, close the "conversation" with ourself and return to the inbox, before "reading" what we have just written. Then we could still get a notification....

This would make things easier in the case of a conversation between two people on two devices associated with a single signal account. Having to mark the conversation as unread each time a message is sent would be quite cumbersome. The alternative suggested here - which would require opening the thread each time you want to write in it - would be no more difficult to deal with than when two other signal users are messaging you simultaneously and you are jumping from one response to the next..

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
