### ISSUE TITLE
Add 'auto resend' possibility if delivery failed.

### ISSUE THREAD

**Issue by UncleGoogle** [signalapp/Signal-Android#5823]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---

Similar to #4808 feature request
My device suffer from frequent delivery failure (sms). About 1/3 of all messages don't want be send totally randomly. Sometimes also in case of poor covarage/reception.

**Now**: I need tap 'more info' and 'resend' button.
**Expected**: try to resend once automatically in case of failure (feature to set in settings) 
**Expected at least**: button for resend it with one tap (no two) - like #4808
### Device info

**Device:** LG Optimus 4X HD P880
**Android version:** 4.0.3
**Signal version:** 3.20.4

**Comment by 2-4601** [comment]
There's already auto resend logic. One reason it fails could be your Android version, see #3068.

**Comment by Trolldemorted** [comment]
it fails for me too sometimes (android 6, nexus4), so this is no android 4 only issue.

and it duplicates messages every now and then, even in non-group chats.

**Comment by UncleGoogle** [comment]
@2-4601 Oh, that sad.
@Trolldemorted : not sure if you understood my problem correctly: problem with my frequent delivery failure concerns my **device**. It occurce even in 'naitive' sms app.

**Comment by 2-4601** [comment]
Oops... I also missed that your report is only about SMS :)
In that case (AFAIK) Signal relies heavily on Android to send the SMS.

**Comment by UncleGoogle** [comment]
Hmm, I see that my report is not precise. It sometimes work as expected but not when immediately fail by my 'device problem'. I will do more tests and make debug reports or close issue within 2 weeks.

**Comment by UncleGoogle** [comment]
Ah I forgot: there is a chance for **Expected At least** ? In my naitive app, I had to press button only once to resend, but now, I have to click "touch to see details", and than "resend". Separate button for resend just below the message would be helpful.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
