### ISSUE TITLE
Giphy: Scroll to the top of the list when changing search keyword 

### ISSUE THREAD

**Issue by ByteHamster** [signalapp/Signal-Android#5824]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Steps to reproduce
- Enter keyword in giphy
- Scroll down a lot
- Enter new keyword
- Results update but scroll position is still down 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Start list from the beginning if the keyword changes

**Signal version:** 3.21.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
