### ISSUE TITLE
White background shown in editor's landscape orientation despite dark theme set

### ISSUE THREAD

**Issue by mkae** [signalapp/Signal-Android#5827]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
White background gets suddenly shown in Signal's editor's landscape orientation despite a dark theme being set

### Steps to reproduce
- edit message with a dark theme enabled
- observe dark background in portrait orientation
- turn mobile into landscape orientation

**Actual result:** Background changes from dark to white

**Expected result:** Background should stay dark

### Device info

**Device:** One Plus X
**Android version:** 6.0.1 - CM13
**Signal version:** 3.20.4

**Comment by FeuRenard** [comment]
Related: #3620 #4816

**Comment by sigmarelax** [comment]
I am also seeing this issue

**Comment by d33rforce** [comment]
also seeing white background on landscape.
OnePlus 3t, Android 7.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
