### ISSUE TITLE
Giphy browser crashes

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5831]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While scrolling down the GIF list, after ≈ 10 pages Signal crashes. But you have to wait for all GIFs to load completely.

### Steps to reproduce
- open conversation
- go to GIPHY browser
- select the two column GIF view in the top right corner
- wait until all GIFs loaded (then all of them are animated)
- scroll down ≈1 page
- wait until all GIFs loaded
- scroll down ≈1 page
- ...

**Actual result:** Signal crashes. Sometimes with Android alert dialog that Signal crashed, sometimes without it.
**Expected result:** Signal doesn't crash.

### Device info
**Device:** Fairphone 2 (2GB RAM)
**Android version:** 5.1.1
**Signal version:** 3.21.3

### Link to debug log
https://gist.github.com/anonymous/3d7e7d0e928153575b443a8d8514b8d2

**Comment by 2-4601** [comment]
In my 1 GB RAM device it crashes on the third page.

**Comment by moxie0** [comment]
hmm anyone want to spend some time with the android device monitor and see where all the memory is going? either the recycler view isn't recycling, or our glide interactions are fucked up somehow.

**Comment by FeuRenard** [comment]
I can't promise it, but I will try to find some time over the course of the weekend.

**Comment by FeuRenard** [comment]
I can't promise it, but I will try to find some time over the course of the weekend.

**Comment by FeuRenard** [comment]
With my AVDs the crash is not reproducible. I tested it with 

- AVD Nexus 5X, 5.1
- AVD Nexus 5X, 6.0

RAM usage of Signal during tests ranges between 95 and 150 MB. It is significantly lower when using the one column Giphy browsing (60-90 MB) and sharply decreases when changing from the two column view.
I don't actually see a leak here, as the memory usage doesn't increase boundlessly.

The crash on my real device happens because the maximum size of memory for Signal is 128MB. For the AVD it is 384MB. And 128MB obviously collides with the up to 150MB needs of the Giphy browser sometimes.

**Comment by moxie0** [comment]
@FeuRenard I think the question is still where the 150MB of memory consumption is coming from. Can you use the android device monitor to see?

**Comment by FeuRenard** [comment]
I will try now. But I have to admit, that I haven't worked with this tool yet.

**Comment by FeuRenard** [comment]
Looking at the Java Heap over time promises to be interesting, I learned until now. That's what you meant? I will go on tomorrow.

**Comment by moxie0** [comment]
Yes iirc you should be able to see where the allocations are going

**Comment by FeuRenard** [comment]
Sadly I can still reproduce this. But it takes longer (more "pages") until the crash takes place, though.

### Device info
**Device:** Fairphone 2 (2GB RAM, memclass 128)
**Android version:** 5.1.1
**Signal version:** 3.22.0

**Comment by moxie0** [comment]
@FeuRenard Can you check and see where the memory is going?

**Comment by FeuRenard** [comment]
I fear I can't do this with my daily device because I actually don't want to run a self-compiled Signal there. Android Device Monitor doesn't display any applications/processes to track with the device connected and Play store version running (however I can see the logcat output).

But I guess that Glide's pool (mentioned here https://github.com/WhisperSystems/Signal-Android/pull/5841#issuecomment-259007596) is the problem.

**Comment by sjjh** [comment]
Just in case that another logcat is of any help here: https://gist.github.com/8d94475e84866e9287d3f7b9e5233158

I'm no Android expert. But in case that you can tell me how to check where the memory goes using ADB or a FOSS debugging app on the phone (I saw an option to specify a debugging app in the developer options of Android), I'm willing to see if I can get further information to help.

Device: Fairphone 2
OS: Fairphone Open 16.10 (Android 5.1)
Signal: 3.22.2

**Comment by FeuRenard** [comment]
I cannot reproduce this issue any longer. I just scrolled down 50 "pages" as described above and Signal didn't crash. How about you @sjjh?

**Comment by nrizzio** [comment]
I also can't reproduce this on my device anymore. I suspect it's because `android:largeheap` was enabled in the manifest a couple of updates ago.

**Comment by sjjh** [comment]
For the time being I cannot reproduce it either (but currently my internet connection is rather slow).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
