### ISSUE TITLE
Stop huge traffic consumption of GIFs by previewing

### ISSUE THREAD

**Issue by devdan** [signalapp/Signal-Android#5843]
I have:
- [x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Using the new giphy feature consumes a lot of traffic. By playing around with the feature, more than half of my monthly traffic was used within a few days. Please only show a traffic friendly preview of the GIF, preferable a still image.

**Comment by FeuRenard** [comment]
For automatic media downloads in conversations there are two settings. One for mobile data and another for wifi. We could add an additional checkbox here, named "GIF preview".

![screenshot_2016-11-07-16-29-13](https://cloud.githubusercontent.com/assets/16167751/20063531/d0a98b9c-a507-11e6-9c4b-b720d5a1adeb.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
