### ISSUE TITLE
"Mute notifications" doesn't completely(?) mark new messages as read.

### ISSUE THREAD

**Issue by donjoe0** [signalapp/Signal-Android#5846]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Muted conversations still sometimes affect notifications: having new muted messages and receiving a new message from a non-muted contact will generate a "cumulative" notification showing the total unread messages _including_ the ones from muted contacts.

### Steps to reproduce
- Mute someone you got an SMS from in the past.
- Get a new SMS from them. (Don't open the conversation.)
- Later, get an SMS from a non-muted contact.

**Actual result:**
Signal creates a combined notification mentioning both new messages from the muted and the non-muted contacts as being unread.

**Expected result:**
Only messages from non-muted conversations should be mentioned in any kind of notifications whatsoever, including the "cumulative" unread messages notifications.

### Device info
**Device:** Xiaomi Redmi 3
**Android version:** 5.1.1
**Signal version:** 3.21.3

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
