### ISSUE TITLE
Cannot call the other party, when the other party is calling me

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-Android#5847]
Hi,

I have noticed that if someone is calling me, and before I got a call from him, I try to call him also, I get busy signal.

So:
1. I have a conversation with a person Alice.
2. For whatever reason connection drops.
3. Alice try to call me back.
4. At the same time I am trying to call Alice back.
5. I get busy signal, Alice gets busy signal to.

It is quite logical, you cannot call someone who is busy. But the question is: since we are calling each other, will be possible to "detect" this and join all two calls together?

**Comment by dcherian** [comment]
Here, I get a missed call notification from the other party while I'm calling them. Two times now, I have been unable to connect a call with the same contact after this has happened.

Log 1: https://gist.github.com/anonymous/e6266b013206549ccd683cca4f71bb86 
Log 2: https://gist.github.com/anonymous/84c62c3d2ba95249be5f23337c8bcdf8

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
