### ISSUE TITLE
Giphy: have keyboard up for search right away

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#5849]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When tapping the attachment icon, then selecting GIF the search box comes up but the keyboard is not available until I tap the search box

### Steps to reproduce
- tap attachment icon
- choose "GIF"

**Actual result:** Giphy comes up with blinking icon in the search bar but no keyboard to type
**Expected result:** Giphy comes up with blinking icon in the search bar and keyboard launches so I can start typing instead of having to tap the search box for the keyboard to come up.

### Device info
**Device:** Verizon Galaxy Note 5
**Android version:** 6.0.1 (stock)
**Signal version:** 3.21.3

**Comment by moxie0** [comment]
That was kind of an intentional decision, since it's showing the trending gifs.

**Comment by jeremymasters** [comment]
I'll buy that direction, but it's not very often I use anything trending so it might be worth ruminating over.  You can close this if you feel strongly against changing it.

**Comment by grantbey** [comment]
I support the keyboard popping up. In my n=1 experience, when I move to insert a gif I usually have a search term in mind. Very seldom do I intend to send a random trending gif to someone.

**Comment by jeremymasters** [comment]
After using for awhile, my experience follows @grantbey closely.  The trending ones seem to be a bunch of stuff from last night's sitcoms.  Not sure if the API has a way to define "trending" where it could be the trending from the last week or two, but that might be more representative of what's _really_ trending.  This could also quickly be turning into a bike shed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
