### ISSUE TITLE
Failed to send while roaming.

### ISSUE THREAD

**Issue by RaceMouse-of-Denmark** [signalapp/Signal-Android#5852]
### Bug description
SMS fails to send while roaming.

### Steps to reproduce
- travel to other country 😀
- enable WiFi due to insane data roaming charges.
- unsecured SMS no longer gets sent.

**Actual result:**
"Some issues need your attention" is displayed.
**Expected result:**
Plain text SMS should have been sent.

### Device info
**Device:** Samsung Galaxy S4
**Android version:** 6.0.1
**Signal version:** 3.21.3

### Link to debug log
https://gist.github.com/59d6401425e27ef29be6daa12449f552

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
