### ISSUE TITLE
Camera preview physical rotation on S6 edge results in black screen

### ISSUE THREAD

**Issue by AaronMulgrew** [signalapp/Signal-Android#5855]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On the app, if you click the camera icon, the preview loads all well and good. But if you rotate the phone (physically) the screen rotates and you get the full screen capture preview, but the screen doesn't connect to the physical camera properly resulting in a black screen. If you rotate back to portrait then it initialises properly.

### Steps to reproduce
- Click the camera icon inside a chat
- rotate the phone

**Actual result:** Black screen
**Expected result:** View of camera 

### Device info
**Device:** samsung SM-G925F
**Android version:** 6.0.1
**Signal version:** 3.21.3

### Link to debug log
[debug log](https://gist.githubusercontent.com/AaronMulgrew/4bf76fd7d72c5fe77845084ae41d8fa4/raw/231b6ebdeb981531874faed1e3041bab79cce96d/Signallog)

**Comment by haffenloher** [comment]
Can confirm, the same thing has been happening for me on a Mediatek phone with Android 4.2.

**Comment by 2-4601** [comment]
Possibly related #4843

**Comment by NamingException** [comment]
Can confirm, the same thing happens on pixel xl

**Comment by riyapenn** [comment]
Adding logs for this issue of a black Screen from rotation of device from portrait/landscape while using direct capture:
Signal 4.14.10, Pixel 2XL, Stock 8.1: https://gist.github.com/16f97b10789245b96bd803e3bb00f72d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
