### ISSUE TITLE
Registered user appears unregistered to other Signal users but can still send Signal messages

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-Android#5859]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
From both mine and my wife's phone we observe that a family member (let's call him Bob) with whom we've been exchanging Signal messages is all of a sudden appearing as not registered with Signal. At the same time, Bob can send messages to a pre-existing Signal group we all participate in, or direct messages to us and these messages are received by us as expected.

I understand these to be two contradictory states. One is either registered (and should be able to use the service) or not.
 
I've looked at https://github.com/WhisperSystems/Signal-Android/issues/5482 - but my contact's number does start with a "+". Re-registering as per http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way- seems to have fixed this schizophrenic state after considerable confusion (as he people involved are non-geeks) so I would like to take this opportunity to understand how Bob ended up in this messy state - hoping to stop this happening to others.

### Steps to reproduce
- Attempt to send a direct Signal message to Bob. Observe that only "Send unsecured SMS" is an option.
- Refresh the directory of registered users
- Quit the Signal app and re-start it
- Send a message to the Signal group containing Bob. He does not receive the message, while other group members do.
- Notice that Bob can send messages to Signal groups and individuals as any legitimate Signal user can - with a padlock icon and everything!

**Actual result:** Multiple people (I would suspect "all" - but hard to test) can't send Bob a Signal message, while Bob can send Signal messages to individuals and groups.
**Expected result:** Everyone should be able to send Bob a Signal message.

### Screenshots
Chrome app showing that Bob is not registered with Signal:
![not registered](https://cloud.githubusercontent.com/assets/2001138/20287480/b2089260-aac4-11e6-91d4-58c4e7e0fde0.jpeg)

Screenshot of Android app showing that Bob was receiving SMS messages but responding with Signal messages:
![signal](https://cloud.githubusercontent.com/assets/2001138/20287946/a610029c-aac7-11e6-845b-4381ed60f4fb.jpeg)

The only option offered by two Signal apps on two Android phones (with two different phone numbers) at that time was to send Bob an unsecured SMS message.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 3.21.3

Bob also has an Android phone, but it's hard to collect device info (he's far away, not technical and already bewildered enough by this experience)

### Link to debug log
This debug log is from my phone right after I noticed I can't send Bob a Signal message.
https://gist.github.com/0b0cbec7c0a40a09c70c6e5d4dc593c6

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
