### ISSUE TITLE
Signal was unable to connect to the server

### ISSUE THREAD

**Issue by keefe007** [signalapp/Signal-Android#5864]
Hello,

I have a brand new Pixel XL and Signal is failing at the last step of the verification process.

I always get the error: "Signal was unable to connect to the server"

My google account and wifi/mobile network are working fine.  I have tried a factory reset and it does the same thing.

Verizon Pixel XL running android 7.1

**Comment by moxie0** [comment]
Hey @keefe007 are you able to use tools like 'adb' in order to get a log? I think there might be some stuff going on with the GCM service based on some behavior I just saw, have you opened the "Play" app recently on your device? If not, can you try opening the app, then going back to Signal and registering?

**Comment by opethfan** [comment]
I'm experiencing the identical issue, on an LG G3 with a custom Nougat (7.1) ROM. All Play services seem okay save for the registration in Signal. Here is the relevant parts of the log:

`11-15 18:29:10.204 W/GCM-GMS (2187): Failed to get registration: java.io.IOException: SERVICE_NOT_AVAILABLE
11-15 18:29:10.212 W/ContentTaskController(1847): Invalid newTask was provided to startTracking.
11-15 18:29:10.543 W/PushServiceSocket(2662): Push service URL: https://textsecure-service.whispersystems.org
11-15 18:29:10.543 W/PushServiceSocket(2662): Opening URL: https://textsecure-service.whispersystems.org/v2/keys/
11-15 18:29:10.895 I/NuPlayerDecoder(288): [audio] saw output EOS
11-15 18:29:11.095 I/Icing   (2187): Indexing 846AC92848F0443D3226A6CAD66ABDE674E85CA7 from com.google.android.gms
11-15 18:29:11.148 W/RegistrationService(2662): 
11-15 18:29:11.148 W/RegistrationService(2662): java.io.IOException: SERVICE_NOT_AVAILABLE
11-15 18:29:11.148 W/RegistrationService(2662): 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
11-15 18:29:11.148 W/RegistrationService(2662): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
11-15 18:29:11.148 W/RegistrationService(2662): 	at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)
11-15 18:29:11.148 W/RegistrationService(2662): 	at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:208)
11-15 18:29:11.148 W/RegistrationService(2662): 	at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)
11-15 18:29:11.148 W/RegistrationService(2662): 	at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)
11-15 18:29:11.148 W/RegistrationService(2662): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-15 18:29:11.148 W/RegistrationService(2662): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-15 18:29:11.148 W/RegistrationService(2662): 	at java.lang.Thread.run(Thread.java:761)
11-15 18:29:11.203 I/Icing   (2187): Indexing done 846AC92848F0443D3226A6CAD66ABDE674E85CA7
11-15 18:29:11.403 I/MediaFocusControl(851):  AudioFocus  abandonAudioFocus() from uid/pid 10036/1114 clientId=android.media.AudioManager@ae87347
11-15 18:29:12.110 E/ThermalEngine(276): [GPU_MON] 6 percent. Current Sampling Time is 1 sec
11-15 18:29:14.987 I/Icing   (2187): Usage reports 0 indexed 0 rejected 0 imm upload false
11-15 18:29:15.983 I/ActivityManager(851): Setting hasTopUi=false for pid=1114
11-15 18:29:16.023 I/Icing   (2187): Indexing 846AC92848F0443D3226A6CAD66ABDE674E85CA7 from com.google.android.gms
11-15 18:29:16.107 I/Icing   (2187): Indexing done 846AC92848F0443D3226A6CAD66ABDE674E85CA7
11-15 18:29:24.050 I/ActivityManager(851): START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10036 on display 0
11-15 18:29:24.068 W/SurfaceFlinger(272): FB is protected: PERMISSION_DENIED
11-15 18:29:24.068 W/WindowManager(851): Screenshot failure taking screenshot for (1440x2560) to layer 21020
11-15 18:29:24.197 I/art     (851): Background partial concurrent mark sweep GC freed 31960(1822KB) AllocSpace objects, 4(80KB) LOS objects, 33% free, 17MB/26MB, paused 1.184ms total 148.553ms
11-15 18:29:24.335 I/WindowManager(851): Destroying surface Surface(name=org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationProgressActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.AppWindowToken.destroySurfaces:417 com.android.server.wm.AppWindowToken.destroySurfaces:382 com.android.server.wm.WindowStateAnimator.finishExit:568 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:180 `

The service was okay earlier today when being used from 6.0, although admittedly I did not try to register.

**Comment by moxie0** [comment]
@opethfan Yeah it looks like it can't connect to GCM for some reason. Did you try opening the Play app and then going back to Signal to register?

**Comment by keefe007** [comment]
Even with play store app open it still can't connect to the server.

**Comment by moxie0** [comment]
I'm pretty sure this is an issue with Google's GCM servers. I've tried updating the version of the gcm library we use, the newer (but still deprecated) version of the api, etc.. and have the same results. I'll keep investigating, I think this is currently affecting all android registrations.

**Comment by opethfan** [comment]
Registration just completed successfully over LTE around 8:35PM Pacific time.

**Comment by moxie0** [comment]
Looks like it's working here too. @keefe007 what about you?

**Comment by merge** [comment]
I have exactly this issue now after installing android 7.1

**Comment by merge** [comment]
hm. a few minutes after starting the play store app, registration succeeded. I hope I can still remove my google account now.

**Comment by coventry** [comment]
I'm having this problem with a friend's Sprint Android 5.0.1 Galaxy S4.  Is that version/model supported by Signal?

I believe this is the corresponding excerpt from the debug log.

```
E/SMD     (11571): smd Interface open failed errno is 2 -1
W/RegistrationService( 6013): java.io.IOException: SERVICE_NOT_AVAILABLE
W/RegistrationService( 6013):   at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
W/RegistrationService( 6013):   at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
W/RegistrationService( 6013):   at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:252)
W/RegistrationService( 6013):   at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:212)
W/RegistrationService( 6013):   at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:59)
W/RegistrationService( 6013):   at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:96)
W/RegistrationService( 6013):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/RegistrationService( 6013):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/RegistrationService( 6013):   at java.lang.Thread.run(Thread.java:818)
E/SMD     (11571): smd Interface open failed errno is 2 -1
```

**Comment by moxie0** [comment]
@coventry Looks like a problem with your Android device communicating with GCM. Last time this happened it was a GCM outage. This looks specific to your device, anything weird going on with Play Services on that phone?

**Comment by coventry** [comment]
Thanks, @moxie0. What should I look for regarding Play Services? FWIW, Play's behavior seemed completely normal when I used it to try reinstalling Signal, and AFAICT it's a stock install.

**Comment by coventry** [comment]
Oh, also, this problem has persisted since yesterday, so it'd be surprising if it was caused by a service outage.

**Comment by coventry** [comment]
I can access `https://gcm-http.googleapis.com/gcm/send` (referenced in #6237) from the phone, but it redirects to `https://developers.google.com/cloud-messaging/http-server-ref`.

**Comment by moxie0** [comment]
@coventry I know this sounds stupid, but have you tried rebooting the phone?

**Comment by coventry** [comment]
Yes, tried that.

**Comment by p13rrot** [comment]
Having this issue as well.  No restrictive firewall, wifi and data work fine.  Just tried installing yesterday, but no matter what would get stuck on step 4 with "connectivity error".  Tried rebooting, updating gogle play things, no effect.
Am not a dev but tell me what you need and I'll do my best to send info.
Verizon Moto E 2015 xt1528.  Android 5.1, Google play store is 7.9.30

**Comment by vkleibel** [comment]
I've got the same issue on my brothers phone, its a HTC One M8. have tried it multiple times over the last weeks on different networks, downgraded and reinstalled updates for google play services... here is a part of the debug log i got from that device:

```06-18 14:43:22.435 29861 29956 W InstanceID/Rpc: Found 10011
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: getSharedPreferences
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1341)
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.loadFromDiskLocked(SharedPreferencesImpl.java:120)
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:52)
06-18 14:43:22.464  2532 30122 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:91)
06-18 14:43:22.467  2532 28105 E GCM     : GCM failed to read backup checkin config, checkin may have failed
06-18 14:43:22.470  1058 30123 D HtcWifiDataStallTracker: mIsWifiConnected true mIsDhcpActive false supplicantStateCOMPLETED mOldWifiDisplayStatus 0mIsRoutingComplete true
06-18 14:43:22.473  2532 28105 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
06-18 14:43:22.491 29861 29956 W RegistrationService: java.io.IOException: AUTHENTICATION_FAILED
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:252)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:212)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:59)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:96)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-18 14:43:22.491 29861 29956 W RegistrationService: 	at java.lang.Thread.run(Thread.java:818)
06-18 14:43:22.816  1058  1319 W SensorService: D/Accel(x, y, z, t) = (  0.9,   9.2,   2.1, 107048542ms), calendar = 1497789802, sys_time = 107048553ms
06-18 14:43:23.121  1058  1076 I ActivityManager: Waited long enough for: ServiceRecord{2dfa2a2 u0 org.thoughtcrime.securesms/.service.KeyCachingService}
06-18 14:43:23.321 20165 20165 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
06-18 14:43:23.325 20165 20165 I wpa_supplicant: environment dirty rate=6 [29][2][0]
06-18 14:43:23.325  1058  1333 D WifiStateMachine: fetchRssiLinkSpeedAndFrequencyNative abnormalRssiCnt = 0
06-18 14:43:23.325  1058  1333 D WifiStateMachine: fetchRssiLinkSpeedAndFrequencyNative rssi=-28 linkspeed=72 freq=2462
06-18 14:43:23.325  1058  1333 E HtcWifiRssiMonitor: newrssi =-28 , oldRssi= -40
06-18 14:43:24.375  1575  1575 D NetworkController.WifiSignalController: Change in state from: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-36,lastModified=06-18 02:43:19,ssid="***"
06-18 14:43:24.375  1575  1575 D NetworkController.WifiSignalController: 	to: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=false,activityOut=false,rssi=-36,lastModified=06-18 02:43:19,ssid="***"
```

**Comment by X4mp** [comment]
I have the same issue on my new bought Xiaomi Mi 6. I'll try a few things and come back later if it doesn't work.

**Comment by wisemonkey** [comment]
I had exact same issue, and I was under impression that signal doesn't rely on GCM anymore.
I use microG with f droid. I had to enable GCM through microG settings to finish registration otherwise registration was failing with unable to connect to server.
I hope this helps with identification/resolution of issue.

**Comment by naman** [comment]
Nudging again since the last comment was a few months old. 

Hey, facing the same issue *without* google play services (disabled through microg settings). Isn't there a way to register without a GCM token/Google Play services? I thought signal-without-google-play-services was rolled out [long ago](https://github.com/signalapp/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b)

**Comment by haffenloher** [comment]
@naman sounds like a separate issue. You should probably either enable GCM or not have microG / Play Services installed during registration.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
