### ISSUE TITLE
Trouble sending group messages

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#5867]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A friend of mine has trouble sending messages in a group. He can send a few, then suddenly sending doesn't work. The message bubble shows the animated dots but the message never goes through.

Has no trouble receiving messages in the same group.
Has no trouble sending/receiving messages in one-on-one chats.

Those unsent messages finally get delivered an hour later. He has been sending messages in on-on-one chats all through that time with no issues, so it's not a network problem.

Once the delivery happens, he has no trouble sending messages to that group. To calrify, others have been messaging that group in the meantime with no issues

### Steps to reproduce
- send messages

**Actual result:** Sending doesn't work after some time
**Expected result:** Sending should always work.

### Device info

**Device:** OnePlus Two
**Android version:** 6.0.1
**Signal version:** 3.21.3

### Link to debug log
After sending a message:  https://gist.github.com/anonymous/4d5f2584e8964d17d07809cceb1c7799

Before sending second message: https://gist.github.com/anonymous/455055e9bbdc217740691e7962a13894

After sending second message: https://gist.github.com/anonymous/214614a1443d17ee6732ecaa17e468d7

**Comment by mkesper** [comment]
Several friends of mine were already facing that problem, now I can reproduce it too with my new mobile (S7, Android 6). All people I know with this problem are on Android 5 or greater.

**Comment by moxie0** [comment]
signal group or mms group?

**Comment by dcherian** [comment]
Signal group.

**Comment by dcherian** [comment]
All of the unsent group messages eventually delivered once he switched to home WiFi, but again one-on-one chats were not affected earlier.

**Comment by moxie0** [comment]
@mkesper It sounds like you can reproduce this, can you provide the steps to reproduce?

**Comment by NaKroTeK** [comment]
Did you try the following : someone else from your group discussion update the group from the mobile app ?

**Comment by mkesper** [comment]
@NaKroTeK This usually works but is not very user friendly.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
