### ISSUE TITLE
Group MMS unable to be read - Android/iPhone

### ISSUE THREAD

**Issue by amorshc** [signalapp/Signal-Android#5868]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Issue when sending a message in group to Android/iPhone users;  Happens whether I create group message, or other contact has created group message.

If I send a message to the group, only iPhone users are able to see the messages. Android users report not being able to view the message - it comes in as a timestamp, and blank. (See attached picture)

Internal testing was done on my phone between my phone using Signal, default settings to group message, resetting APN, having carrier reset APN, resetting Signal permissions and rebooting phone. iPhone users report being able to see messages - android users are unable to see the message.

Further testing was done by switching SMS message apps to the stock messenger app, as well as Allo (Google), and Textra. No issues with group MMS/SMS reported when switching messenger app, and all users are able to view messages in group.

### Steps to reproduce:

- Use iPhone of any type below (iPhone 7 and below) - and use mixed Android devices.
- create group message or have "other contact" create group message.
- send message from Android device to group created.

iPhone's tested: 6s + iOS 10.1.1 and iPhone 6S 10.1.1 = able to see messages
Android's Tested: Galaxy s5 6.0.1, Galaxy s4 5.1.1, LG V5.

**Actual result:** 
See attached screenshot.
Message appears - but has timestamp and name only.

**Expected result:**
Picture (MMS) or regular text (SMS) to be shown in group message.

### Screenshots
![1479307094739](https://cloud.githubusercontent.com/assets/23526787/20394759/459d1a72-aca6-11e6-8e32-0cbc44050c32.jpg)

### Device info
Device  : samsung SAMSUNG-SM-G900A (klteuc)
Android : 6.0.1 (G900AUCS4DPH4, MMB29M.G900AUCS4DPH4)
App     : Signal 3.22.2

### Link to debug log
https://gist.github.com/25b6901d0f3dd92af2eca4cf47d43a73

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
