### ISSUE TITLE
Quick Reply and Non-Standard DPI...

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#5870]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using a custom DPI (lower than 420), using the quick reply function from the notification bar causes Signal to send the message, and then load the entire message window.

### Steps to reproduce
- Set device DPI to 380.
- Receive Signal or SMS message and select "Reply" , either from heads-up, or notification shade.
- Send message from the quick reply box.

**Actual result:** The entire Signal app is then brought back to focus.
**Expected result:** Quick reply modal should disappear after message is sent, Signal should not be brought in to focus.
### Screenshots

N/A

### Device info

**Device:** N/A - have tested numerous devices.
**Android version:** 6.0.1 (CyanogenMod 13, and stock AOSP Android 6.0.1)
**Signal version:** 3.22.2

**Comment by nullpointer17** [comment]
Working correctly here, Lenovo P2, Android 6.0.1. I'm using 400 dpi instead of 480 which is the default.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
