### ISSUE TITLE
Crash on startup - BitmapDecodingException: java.io.FileNotFoundException: PartAuthority couldn't load Uri resource.

### ISSUE THREAD

**Issue by dapphp** [signalapp/Signal-Android#5871]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After entering my passphrase to unlock Signal, it abruptly terminates without any message or notifications.  This may have been caused by the phone crashing while receiving an MMS.

** The problem was resolved by having someone send me a regular SMS.  Even though the corrupted image was still there, it seems to have been fixed as it was no longer the most recent message.  Posting this here so others can find it. **

This can be closed - except for maybe adding code to handle these exceptions gracefully and prevent a crash.

Once I got a new text and was able to get back in the app, the previously received message was an MMS and the image appeared broken.  When opening it, it just appeared black.

### Keywords

DecryptingPartInputStream: java.io.FileNotFoundException: Part shorter than crypto overhead!
AttachmentDatabase: java.io.FileNotFoundException: IOException while reading IV!
DecryptableStreamLocalUriFetcher: Caused by: org.thoughtcrime.securesms.util.BitmapDecodingException: java.io.FileNotFoundException: PartAuthority couldn't load Uri resource.

### Steps to reproduce
- Create passphrase to have encrypted local database
- Receive partial/corrupt MMS image?
- Open Signal & enter passphrase
- Crash

### Device info
**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** 3.22.2 (and previous version - upgrade did not help)

### Link to debug log
https://gist.github.com/dapphp/742c050fbd2d3b9c214c740af89ced1d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
