### ISSUE TITLE
Allow saving multiple images in a conversation

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5874]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
There was #5088 asking for multi-selecting images in "All images" and then saving them. It was closed without actually having multi-select & save implemented.
I am asking for multi-select images in a conversation and then save them.

### Steps to reproduce
- go to a conversation
- long press a picture message
- tap a second/third/... picture message

**Actual result:** No save button is shown.
**Expected result:** A save button should be shown and allow to save the selected images.

**Comment by nysander** [comment]
when this feature will be deployed?

**Comment by FeuRenard** [comment]
Please [don't bump issues](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues)! To vote for an issue, feature or PR you can add a positive reaction (e.g. :+1:) to the initial comment.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
