### ISSUE TITLE
Expand text entry field height when input exceeds 4 lines

### ISSUE THREAD

**Issue by blokeley** [signalapp/Signal-Android#5885]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

The height of the text entry field for writing messages is limited to 4 lines.

I write long signal and SMS messages and would like the text entry field to expand in height as I write so I can still see my full message.  This would be great.

Even if this can't be done, a customisable fixed height setting would suffice.

Thanks in advance for any help.

**Comment by 2-4601** [comment]
It used to expand to the whole screen (#2899). More than four lines could make sense now since most of the phones currently have very large screens. For comparison WhatsApp has max 6 lines. Don't know if it can be dynamically adjusted based on the screen size but a user preference for this sounds like an [unlikely option](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology).

**Comment by blokeley** [comment]
How about default to the largest that won't break, maybe 6 like WhatsApp's, and add a setting to allow users to increase it?

**Comment by Lokesh-Krishna** [comment]
Defaulting to 6 without any setting to increase sounds like the more reasonable solution as the setting to increase or decrease would mean making sure the options in it don't break the app.

**Comment by jbonnafo** [comment]
Hello,
Could it be possible to have the "expanding to whole screen" feature ?
Some people i know find that 4 lines limit quite annoying.
Thanks,

**Comment by bill-mcgonigle** [comment]
Typing into a small box on a small screen can be a usability problem for anybody,  but the low-vision users are especially hard hit as "a line" contains many fewer words with a large font size. #accessibility 

There's an inherent tradeoff between input area size and the ability to see the conversation history, but some  reasonable default (maybe 60% of vertical screen size, up to a dozen lines' height) would be a good start without getting into complex zoomable-interface semantics.

Beyond that, adding a draggable-resize border on the top of the input box would let anybody adjust the input to the needs of a particular conversation.

**Comment by bill-mcgonigle** [comment]
* available vertical screensize (exclusive of screen keyboard).  Sorry, can't edit previous comment on mobile.

**Comment by mad99** [comment]
Yeah, would be nice to have the option to expand and re-reduce the height of the text-area, maybe with a simple button for «expand»<#1> and reset-to default <#2> on top-left empty-space: See attachment
![signal-bigger-editor-area](https://user-images.githubusercontent.com/6169308/31779417-56d98450-b4f3-11e7-8871-d41ef477acf1.jpg)

**Comment by moxie0** [comment]
@mad99 Interesting. Nice idea!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
