### ISSUE TITLE
One friend is unable to see messages from second friend, but third friend can see messages from both.

### ISSUE THREAD

**Issue by joshuap** [signalapp/Signal-Android#5886]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I found issues #5868 and #5867 which seem like they could be related but do not describe the behavior we are seeing exactly.

----------------------------------------

### Bug description
I am using Signal with 2 friends: Ben and Trent (device info below). I am able to communicate with both Ben and Trent individually and in a 3-person group message, however Trent cannot see any of Ben's messages in either a direct message or in the group. I can see both of their messages in the group, but Trent can see only mine; to him it appears as if Ben is totally silent (no indication that he has replied). Trent reports the same behavior in a direct message to Ben: he can locate Ben in the contact list and send him a message; Ben receives the message and replies, but Trent receives no indication of the reply.

### Steps to reproduce

- I am unable to reproduce this because I don't have access to the phones. My first step would be to try sending messages between two Android devices running the same software versions to see if they are delivered.

**Actual result:** Trent is unable to see Ben's messages.
**Expected result:** Trent should see Ben's messages.

### Device info
- Ben: Samsung/Galaxy Core Prime, Android 5.1.1, Signal 3.22.2
- Trent: Samsung/Galaxy Note 5, Android 6.0.1, Signal 3.22.2
- Me: Apple/iPhone 6+, iOS 10.1.1, Signal 2.6.5

### Link to debug log

From Trent's phone (not 100% sure if this is directly after Ben has sent a message to Trent which is not displayed, but it doesn't seem to contain much):

```
Device  : samsung SM-N920V (nobleltevzw)
Android : 6.0.1 (N920VVRS3BPI1, MMB29K.N920VVRS3BPI1)
Memory  : 40M (1.40% free, 256M max)
Memclass: 256
OS Host : SWDD6723
App     : Signal 3.22.2

--------- beginning of main
11-23 17:34:04.690 20887 20887 W GcmBroadcastReceiver: GCM message...
11-23 17:34:04.720 20887 20901 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
11-23 17:34:04.720 20887 20901 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/
11-23 17:34:05.300 20887 20901 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
11-23 17:34:05.300 20887 20901 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+*********56/1479951243588
11-23 17:34:05.370 20887 20903 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'M
```

**Comment by moxie0** [comment]
Those are the *entire* contents of Trent's log? Looks cut off.

**Comment by joshuap** [comment]
It may be incomplete. I'll ask him to produce another one tomorrow and post it for you.

**Comment by joshuap** [comment]
@moxie0 Trent says he submitted the logs via the android app. Not sure if you can identify him easily. His phone number ends in 6325. I'm afraid that's the best I can do for now... If I can get more out of those guys I will.

**Comment by moxie0** [comment]
@joshuap That just generates a gist. We don't have access to it until the link is posted here.

**Comment by joshuap** [comment]
@moxie0 ah, sorry. Here's the gist Trent generated after all three of us replied to the group:

https://gist.github.com/anonymous/fcd99449886fc396379a9c97deedb5da

I don't see any reference to Ben's #, which ends in *59. I am *56 and Trent is *25.

Here is a debug log from the Signal Chrome app (captured just now from my account) where I see messages from both of them (but Trent can still not see Ben):

https://gist.github.com/joshuap/d1a41f1c0b0c1997ab95498a842ea8ef

**Comment by moxie0** [comment]
Huh, everything in the logs looks fine. Just to make sure I understand, you're saying that:

1) Ben sends Trent a direct non-group Signal message.  When Ben hits "send" the send button is colored blue.
2) Ben sees a delivery receipt (double check) for that outgoing message.
3) Trent never sees anything.  No notification, no message, no thread creation, nothing.

Is this true?

**Comment by joshuap** [comment]
@moxie0 we finally discovered the issue. I confirmed that Ben would message Trent but would only see a single check for the outgoing message (instead of double). As far as I know he was replying to a message that Trent had sent him. I asked him to try to send Trent a new message; when he tried, he realized that Trent was not in his Signal contacts. I had him check his Android contacts and he realized that he had not entered the area code for Trent's phone number, since they are both local. Once he added the area code everything was fine.

Is it possible to default to the local area code when a contact's phone number doesn't specify one?

**Comment by moxie0** [comment]
Hmm, what country are you guys in? How was Trent's number formatted in Ben's phone?

**Comment by joshuap** [comment]
We are in the US (CA). Ben said the number was formatted like "123-4567".

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
