### ISSUE TITLE
Some voice notes are saved with .attach extension

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#5899]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some voice notes are saved without an audio extension (".attach"). This happens for all voice notes with my Android 4.4.4 device, but only happened once with my Android 5.1 device.

### Steps to reproduce
- Open a conversation with a voice note.
- Long-press a voice note
- Save it
- Open a file manager app
- Navigate to the music directory

**Actual result:** Voice note is saved with ".attach" file extension.
**Expected result:** Voice note is saved with the according audio file extension.

### Device info (reproducible)
**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 3.23.0

### Device info (not reproducible)
**Device:** Fairphone 2
**Android version:** 5.1
**Signal version:** 3.23.0

**Comment by 2-4601** [comment]
Hmmm... Wasn't this `.attach` thing an issue also before? Long discussion on #4536.

**Comment by Dyras** [comment]
Saves as an .aac file for me. Moto G4 with Marshmallow.
On an unrelated note, I think Signal should be more specific about where the file is being saved to.

**Comment by LoRDxRaVeN** [comment]
I have the same problem on my Xperia SP with stock Android 4.3 (a couple of apps uninstalled). Also i can't play back the voice notes in Signal (Error message: "Fehler bei der Audiowiedergabe", german for something like "audio playback error". If i rename the exported audio file, the playback works, so the file itself is fine. 
And i can tell, that the playback works on my girlfriend's Xperia SP with Cyanogenmod 13 inside Signal, so maybe it's Jelly Bean/Kit-Kat related.

Device: Sony Xperia XP
Android version: 4.3
Signal version: 3.23.0

**Comment by philips77** [comment]
My mp4 got saved as .attach. I renamed the extension to mp4 and video is working now as expected.

**Comment by thrdroom** [comment]
We got the same problem with a family device over here.
Samsung galaxy s7
Android Nougat 7
Signal 4.9.9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
