### ISSUE TITLE
Fully delay notification creation during active desktop conversations

### ISSUE THREAD

**Issue by adarazs** [signalapp/Signal-Android#5902]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In release 3.23.0 the "squelching" of notification sound was introduced while using the desktop client. The solution follows the #4905 enhancement request closely, by only delaying the *sound* of the notification, not the whole notification.

Most wearable devices are vibrating based on the appearance of a phone notification, so this still results in constant extra notifications for anybody using a wearable that can receive them.

### Steps to reproduce
- have any wearable that receives notification from the phone
- receive messages while actively using Signal Desktop

**Actual result:** the user gets notification/buzzing on the wearable even when the notification sound doesn't fire on the phone itself due to the notification sound squelching.
**Expected result:** the full notification creation should be delayed during an active conversation, not just the sound.

### Device info
**Device:** LG G4 + Pebble 2 HR (problem also exists using a Xiaomi Mi Band 1A)
**Android version:** 6.0
**Signal version:** 3.23.0

**Comment by hopeseekr** [comment]
Expedite this!

What happens now is that there is about a 30 second pause between SIgnal Desktop and Android sync, EVEN ON MEssAGES marked ot disappear after 30 seconds...

After 3 hours of chatting tonight, for instance, it is 00:49 IST yet the android client is still beeping continuously tho my chats ended 20 minutes ago :O The Android client is now on messages from 22:49 IST, fully 2 hours behind!!!!

What's worse, these are messages marked for deletion in 1 minutes.

**So does Signal keep these messages???? Are they NOT deleted???**

So many problems with this!!!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
