### ISSUE TITLE
archived/blocked flags are not part of xml backup

### ISSUE THREAD

**Issue by jmayday** [signalapp/Signal-Android#5904]
After importing messages from _.xml_ backup, previously archived messages are all placed in main folder. 
Also 'blocked' flag is gone. 

I'm talking about only those messages that were part of the backup (probably already received messages and their flags are intact).

I was expecting that 'archive' and 'blocked' flags are part of _.xml_ backup. 

This is part of my backup (entries from one thread). For sure I've moved all messages from this number to archive and blocked the conversation. 
```
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="2" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="2" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="2" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
 <sms protocol="0" address="<cut>" date="<cut>" type="1" subject="null" body="<cut>" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
```

**Comment by johanw666** [comment]
The plaintext backup is compatible with https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore . Does that program support such tags? I doubt it since it isn't Android default functionality.

**Comment by haffenloher** [comment]
@johanw666 the goal would probably be to include this info in such a way that it gets ignored by SMS Backup & Restore

**Comment by jmayday** [comment]
@johanw666 let's distinguish two things: 'a format' and 'a format compatible with'. In my opinion it's nothing wrong with extending the format and exporting some extra properties.
@haffenloher I believe SMS Backup & Restore should just ignore unknown properties out-of-the-box.

**Comment by johanw666** [comment]
OK, I tested it with sms backup and restorte: restoring this test file into the system sms database worked:
``
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<smses count="1">
 <sms protocol="0" address="+31612345678" date="1385315600000" type="1" subject="null" body="Test mesasge" toa="null" sc_toa="null" service_center="null" read="1" status="0" locked="0" archive="1" blocked="1"/>
</smses>
``
I added extra fields archive and blocked to the message, they seem to get ignored as they should.

**Comment by jmayday** [comment]
@johanw666 thx for implementing this. When can we expect Signal update in Google play?

**Comment by jmayday** [comment]
@johanw666 just to keep consistency - wouldn't it be better to have 'archived' and 'blocked' rather than 'archive' and 'blocked'?

**Comment by johanw666** [comment]
@jmayday I did not implement this in Signal, I just created an xml test file by hand to see if sms backup and restore would not break on it. And I'm not the one pushing Signal updates so if and when it will be in Signal I have no idea. Personally I prefer a full backup without those xml files and I don't care about the system sms database, but that pull request was rejected yesterday.

**Comment by jmayday** [comment]
Ahh OK. But I don't get instruction @moxie0 gave. 
linking PR if anyone interested: https://github.com/WhisperSystems/Signal-Android/pull/5907

**Comment by johanw666** [comment]
Probably because it's not idiot proof enough: if you restore a newer version of the database on a device with an old Signal it might crash on startup, and if you have received messages after the backup was made you need to reset the secure session(s). The later can be done automatically as well but I didn't implement that. Same issues as when you use a Titanium Backup.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
