### ISSUE TITLE
BUILDING.md needs warnings/instructions regarding data loss when reinstalling app

### ISSUE THREAD

**Issue by sparr** [signalapp/Signal-Android#5913]
(skipped the template as this isn't a code bug)

After following the instructions to get set up with Android Studio, I built the app and installed it on my phone. Little did I know that switching from the already-installed release build of the app to the build I had just made would result in losing configuration, keys, and the message database.

The instructions should probably have a warning about this, and perhaps instructions for backing up what can be backed up (I understand keys aren't currently available for backup without root and third party tools?) and restoring after the reinstall.

**Comment by 2-4601** [comment]
How did you install it? Android should refuse to install the same app with a different certificate.

**Comment by sparr** [comment]
Phone attached to computer via USB. I pressed the default Run/Play button in Android Studio. It asked me which device to run on, I chose my phone. Android Studio asked if it could [can't remember the exact wording] to replace the installed app with my newly built app, and I said yes. That was apparently my big mistake.

**Comment by Trolldemorted** [comment]
yes, replacing includes purging the old installation's directories.

**Comment by sparr** [comment]
@Trolldemorted I can uninstall and reinstall plenty of other apps without losing their data, because they store that data somewhere other than in their installation directory. Narrowing the field to just messaging apps, I am not aware of any other messaging app on Android where this would be the case.

I'm not suggesting this behavior be changed, just that it be noted in the docs so others don't succumb to it as naively as I did.

**Comment by 2-4601** [comment]
Submit a PR to add the warning. I've only installed via adb and on the device manually and updating with a different cert does not work. No idea how it goes in Android Studio

**Comment by sparr** [comment]
I'm not sure how it should be worded. This is my first exposure to Android development. I hope someone else here has more insight into which situations and install methods can lead to this problem.

**Comment by moxie0** [comment]
The Android studio dialog you clicked through says "WARNING" in all caps, and says that all your application data will be lost. Feel free to submit a PR if you think including additional information in BUILDING would be useful, though.

**Comment by johanw666** [comment]
Next time you try that and don't want to loose your data, you can use Lucky Patcher to disable the Android signature check and install the apk directly (i.e. not from Android Studio). This requires rootand the Xposed framework..

I'm not sure if Titanium Backup would barf over different signatures.

**Comment by Trolldemorted** [comment]
@johanw666 it is a shame that android/cm does not support that on its own. Do you know if there is a way to make it forget a signature and trust the next first use again?

**Comment by johanw666** [comment]
It's a security measure, but since it also works against modded pirated software I doubt that Google will allow users to switch it off. The Lucky Patcher way does require some knowledge. What you want (change the signature once) will require you to switch this option on in Lucky Patcher, change the apk with the different signature and then switch the option off again.

**Comment by Trolldemorted** [comment]
i am *very* reluctant to install apps that mess with my system.

can't i change the certificate key in `/data/system/packages.xml` and be done with it?

**Comment by johanw666** [comment]
I don't know, if you find a way to serialize a key in the format that is used in that file, please test it (I would suggest to test it with an open source app you don't currently use so no data is lost if it doesn't work) and let us know.

**Comment by Trolldemorted** [comment]
Serializing is easy: sign something, deploy, goto packages.xml and there is your key.

I just need someone with a rooted android and vanilla signal to test it, i guess.

**Comment by nikwen** [comment]
Thanks a lot for this warning. I'd be willing to add something to BUILDING.md if you're not planning on doing that yourself. Just let me know.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
