### ISSUE TITLE
Reduce/mute music volume when recording voice message

### ISSUE THREAD

**Issue by WolfgangAndreas** [signalapp/Signal-Android#5914]
When recording a voice note and music is played via Spotify / Google Play / another player in the background this also is recorded to the note. It would be nice, if other players get muted or reduced in volume, when recording a voice note.

**Signal version:** 3.23.0

Thank you for your great work!!! Keep on going!
- Wolfgang -

**Comment by nrizzio** [comment]
[These](https://developer.android.com/training/managing-audio/audio-focus.html) are the relevant Android API docs.

**Comment by jcollum** [comment]
### Bug description
When recording voice audio media playback (audio e.g. podcast) should stop. It's very hard to listen and talk at the same time. **Telegram manages to do this, Signal should as well.** 

### Steps to reproduce
- start audio playing, like a podcast or music
- send a voice message to yourself (or anyone else) via Signal

**Actual result:** recorded voice message will have music in the background


**Expected result:** recorded voice message has no music in the background

### Screenshots
Can provide if needed, but I don't know how I'd capture it without doing a screen recording. 

### Device info 
**Device:** LG G5
**Android version:** 7
**Signal version:** Signal 4.16.9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
