### ISSUE TITLE
Typing on keyboard doesn't show anywhere when receiving new message

### ISSUE THREAD

**Issue by agaon** [signalapp/Signal-Android#5915]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I get a new message (Signal is locked) and I open the app from the Notification panel, a keyboard automatically appears in the conversations. typing on the keyboard doesn't show the text anywhere. 

### Steps to reproduce
- get a message from an existing contact that already has an existing conversation (signal is locked) 
- unlock Signal from the notification bar 
- the app opens up in the conversation with the keyboard already drawn (open) 
- type in keyboard - nothing is displayed in the text box 
- (step needed to make the text appear) click on the text box, now type in keyboard, text is displayed on the text box

**Actual result:** Text that is typed on the keyboard isn't displayed 
**Expected result:** Text that is typed on the keyboard is displayed in the "text box"

### Device info
**Device:** Huawei Nexus 6P (angler)
**Android version:** 7.0 (3318877, NBD91K)
**Signal version:** 3.23.0

### Link to debug log

Getting a message and keyboard not filling the text box -
https://gist.github.com/anonymous/5f437873148af5a6f40811251391e8df
Getting a message and keyboard not filling the text box, clicking on the text box and it works -
https://gist.github.com/anonymous/143c92a1a8325c6417aa895b1fbbff8c

**Comment by Lokesh-Krishna** [comment]
I thought there was something wrong with my keyboard. Glad to know it's not because the keyboard would never have got a fix.

**Comment by thomascrepain** [comment]
Issue als appears on a Motorola G4, Android 6.0.1 (3.10.84-g061c37c). 
Signal version 3.27.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
