### ISSUE TITLE
Add notification when delivery fails and device is muted

### ISSUE THREAD

**Issue by UncleGoogle** [signalapp/Signal-Android#5918]
Related to #5823 

### Bug description
When I send SMS, and delivery fails just after send attempt -> there is no notification. 
Often I wrote message, place phone next to me and have no idea that sth went wrong.  When phone is not muted, there *is* a notification sound (the same like for incoming sms what is a bit strange, but ok), but when is muted, there is no vibration. IMO it should vibrate. Error never, ever should goes silently.

Please, check firstly if this issue is related with application or my device/android ver.

### Steps to reproduce
- (have old android version)*
- mute phone (I mean go to vibration mode)
- call delivery fail notification (red circle) somehow (when screen is still not blank)*
(...)* not sure if is needed.

**Actual result:** Notification goes silently (I mean - there is displayed  red circle and information, but it doesn't 'shout'.
**Expected result:** It should vibrate for a short time to catch my attention.

### Device info
**Device:** LG Optimus 4X HD P880
**Android version:** 4.0.3
**Signal version:** 3.20.4

### Link to debug log
https://gist.github.com/anonymous/186d90931301c906ab9c4c8676f78481
or
https://gist.github.com/anonymous/78e670b11a58545b3940a727976dbc34

**Comment by haffenloher** [comment]
> mute phone (I mean go to vibration mode)

If in vibration mode, your phone should still vibrate on delivery failures - unless you're still viewing the relevant thread and `Settings > Notifications > In-conversation notifications` is disabled?

**Comment by UncleGoogle** [comment]
`In-conversation notification` is enabled in my case.

**Comment by haffenloher** [comment]
And you're still viewing the thread or not? Sorry but it's impossible to tell from your repro steps.

**Comment by UncleGoogle** [comment]
How can I help with this issue?

I think someone else should:

1\) 
- set phone to vibration mode
- enable `Settings > Notifications > In-conversation notifications`
- call delivery fail notification (red circle appear) somehow (for example by lack of connection) when still viewing the relevant thread 

if there is everything ok (there is vibration signal):
2) check the same for android 4.0.3 (or just 4.xxx)

if there is everything ok:
3) close the issue unless more people have this problems.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
