### ISSUE TITLE
Cannot read message from Signal user if they reply to group of Signal and non-Signal users

### ISSUE THREAD

**Issue by msh345** [signalapp/Signal-Android#5920]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For group messages, if one person has Signal and the others don't, then their message to me (via the group chat) says, "MMS download failed! Message size: 1 KB". Tapping on the message doesn't download the message. I can read messages from all other group members (non-Signal users). 

The undelivered message only happens if I use Signal as default app. Going back to stock messaging app, future messages can be read.

The Signal user is also using a Samsung (Galaxy S7).

Direct messages from the Signal user to me only are readable.

EDIT: They are using the default messaging app to send messages to the group. When they send messages directly to me through the default messaging app, I can read them on Signal.

EDIT 2: When the Signal user sends a message to the group, it arrives as an unreadable MMS directly to me, not to the group.

### Device Info
Device  : samsung SAMSUNG-SM-N920A (noblelteuc)
Android : 6.0.1 (N920AUCS4CPK1, MMB29K.N920AUCS4CPK1)
App : Signal 3.23.0

### Link to Debug Log
https://gist.github.com/anonymous/473e3866575baa40a2c18c78fbb07040

**Comment by haffenloher** [comment]
Could you please add a link to a debug log captured after you received / tried to download one of these failing messages?

**Comment by msh345** [comment]
Updated. Also, note the EDIT

**Comment by Trolldemorted** [comment]
I suppose you can read their messages if they use signal because they send signal messages instead of mms in that case.

Another thing: i think your your debug log contains several phone numbers, you might want to check.

What happens if you send a group message via signal? Does the other person with signal receive it properly?

**Comment by msh345** [comment]
Unfortunately, no. They're sending the group plain text, and I receive it as an MMS.

Is there any way to delete the Gist?

If I send a message via Signal, the other Signal user receives the message in their default messaging app.

**Comment by sweeper3000** [comment]
@msh345 If you sent the gist through your GitHub account, yes. If sent through the app, no.

**Comment by michaelkirk** [comment]
> Is there any way to delete the Gist?

https://help.github.com/articles/deleting-an-anonymous-gist/

**Comment by riyapenn** [comment]
What steps from the [support page](https://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do-) have you tried? Editing APN settings and/or checking Chats and media settings may resolve this.

**Comment by msh345** [comment]
Yes, I pretty much did everything on that page, except the "reprovision" part (replace?).  And instead of deleting the APN, AT&T told me to use the "reset to default" option, but that didn't work. I asked if I could edit the APN settings, but they discouraged me from doing so.

**Comment by riyapenn** [comment]
Based on your debug log and [possibly related MMS info](https://developer.android.com/reference/android/telephony/SmsManager.html#MMS_ERROR_CONFIGURATION_ERROR)
`12-05 15:16:38.591 12144 12174 W CompatMmsConnection: Falling back to try receiving via Lollipop API
12-05 15:16:38.591 12144 12174 W IncomingLollipopMmsConnection: downloading multimedia from http://166.216.166.67:8015/Y/1205183731600038000110000 to content://org.thoughtcrime.provider.securesms.mms/mms/1480972598600
12-05 15:16:38.681 12144 12144 W LollipopMmsConnection: onReceive()
12-05 15:16:38.681 12144 12144 W IncomingLollipopMmsConnection: HTTP status: -1
12-05 15:16:38.681 12144 12144 W IncomingLollipopMmsConnection: code: 7, result string: null`

I think it's worth asking AT&T to re-provision your device.

**Comment by msh345** [comment]
I appreciate your help, but I don't want to go through the trouble of getting another phone and then find out Signal also doesn't work on that. I'm afraid I'll have to find another app.

**Comment by riyapenn** [comment]
Re-provisioning is not getting another phone but resetting information.  AT&T has done it before based on user information in some forums [here](https://forums.att.com/t5/Apple/No-service-suddenly/td-p/4172419) and [here](http://forums.androidcentral.com/t-galaxy-note-2/246857-mms-send-receive-problems.html).  If you choose to no longer use Signal, make sure to [unregister](https://support.whispersystems.org/hc/en-us/articles/213190627-How-do-I-unregister-) your number or you can switch to another app for insecure messaging and keep using Signal for private messaging.

**Comment by msh345** [comment]
Got it. I called AT&T again, and they asked me to check my APN settings against the first table [here](https://www.att.com/esupport/article.html?_escaped_fragment_=/wireless/KM1062162). Everything was the same. I asked the tech to look at the Signal debug log, and they noticed that, apparently, the app is expecting Lollipop, but the Android version on my phone is Marshmallow. Could that be the problem?

**Comment by meowsus** [comment]
I have the same problem. Once a week 2 friends and I start a group message. Myself and another friend have Signal, and the other doesn't. Apparently, when I reply, no one can read my messages.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
