### ISSUE TITLE
double-tap trashcan to delete

### ISSUE THREAD

**Issue by titaniumbones** [signalapp/Signal-Android#5925]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### UI Change Request description
To delete messages, it is currently necessary to long-press the message, click the trashcan, then click the confirm button.

Textra uses a different UI that still requires active confirmation, but is somewhat quicker.  The process is as follows:
- select one or more messages
- tap the trashcan. *The trashcan animates "open"*
- tap the trashcan *again*. Messages are now deleted.  

The double tap is still a confirmation, but is much smoother and quicker than the dialog. I have never deleted texts by accident, but the deletion process is fluid and easy.  

### Steps to reproduce
- select one or more messages 
- tap trash can
- tap confirm button

**Actual result:** 
Message is deleted, but with some effort
**Expected result:** 
Message is still deleted, but faster and more fluidly.  

### Device info

**Device:** Honor 5x
**Android version:** CyanogenMod 13.1
**Signal version:** 3.23.0

### Textra Feature
[very short description in their help pages](https://textra.uservoice.com/knowledgebase/articles/422303-trash-can-deleting-messages)

**Comment by haffenloher** [comment]
Offering an "Undo" option instead of requiring confirmation would be even better: #3066

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
