### ISSUE TITLE
Enable image viewing in immersive mode

### ISSUE THREAD

**Issue by nikwen** [signalapp/Signal-Android#5934]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
It would be nice to be able to view images in immersive mode, i.e. with the the app bar, the status bar and the navigation bar being hidden.

Documentation on immersive mode: https://developer.android.com/training/system-ui/immersive.html

**Comment by FeuRenard** [comment]
#3192 is related. But it only asks for the removal of the action bar, not of status bar and navigation bar.

**Comment by FeuRenard** [comment]
I am working on this issue. Looks actually quite nice :)

My plan is to first implement #3192. It will work with all supported Android versions. Immersive mode will later be available for KitKat and above.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
