### ISSUE TITLE
Pressing back button after opening a picture from the gallery brings you back to the conversation instead of the gallery

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#5940]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With the newly introduced feature to go to the gallery ("all pictures") when opening a picture from the conversation view, one can search through all the pictures of this conversation. After opening another picture and pressing then the back button of my phone, I expect to be back in the gallery. Instead I'm back in the conversation.

### Steps to reproduce
- go to a conversation
- open a picture in the conversation by tapping on it. You view the picture in full screen now.
- press the gallery button ("all pictures"). You see all pictures of the conversation now.
- open another picture by tapping on it.
- press the back button.

**Actual result:** I'm back in the conversation.
**Expected result:** I'm back in the gallery.

### Device info

**Signal version:** 3.24.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
