### ISSUE TITLE
Initial SMS import only contains received SMS not sent

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#5960]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
ON "initial import of sms messages, the other user's responses were imported but not my own"

### Steps to reproduce
- First install of Signal
- Register
- Import SMS

**Actual result:** Received SMS imports, but is one sided and does not contain sent SMS
**Expected result:** All SMS imports

### Device info

**Device:** Samsung Galaxy S7 Edge AT&T
**Android version:** 6.0.1
**Signal version:** 3.24.1

### Link to debug log
 Log captured after asking user to re-import:
https://gist.github.com/b1a54267d272c4264c9a285f73835118

**Comment by riyapenn** [comment]
Device: Samsung Galaxy S7 Edge AT&T
Android version: 7.0.0
Signal version: 4.9.9
Log: https://gist.github.com/2b0bdbf8b93a067fe2ffc446733f1341

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
