### ISSUE TITLE
App deletes all of my contacts

### ISSUE THREAD

**Issue by linuxcentre** [signalapp/Signal-Android#5964]
I have installed the app from the google play store 1 week ago and on one of my phones running it completely wiped the contacts.

On another phone (same model and OS) I just updated the app this morning from installation last week and it too deleted all of my contacts.

I have the app on a 3rd phone (same OS and model) and it has not yet happened.

Strangely on this updated phone I could not add any more contacts as every time I added one manually in android it would say 'contact deleted'. Also the android contacts app just said something like 'Contacts Updating'. (It was as if the signal app had locked the contacts DB?)  

I tried:
* Hard reboot -> still no contacts.
* Removing the Signal app + reboot -> still no contacts.
* I even copied an old contacts2.db + profile.db from an older system backup and set perms/ownership/SELinux labels in recovery mode -> still no contacts.
* Restoring conatcts from vcf -> still no contacts.
* Restoring conatcts from superbackup app -> still no contacts.

The only way was to clear the storage on the 'contacts storage' system app and re-import all contacts from backups.

This seems to happen *sometimes* after I refresh the contacts in Signal after update or installation.

Device: Motorola Moto G 3rd Gen
Android version: Cyanogenmod 13.0 (marshmallow)
Signal version: 3.24.1(and the version on play store 1 week ago)

Possibly slightly related to this but a more serious problem
https://github.com/WhisperSystems/Signal-Android/issues/5808

**Comment by linuxcentre** [comment]
Just happened again. This time I did not refresh the contacts or update the app.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
