### ISSUE TITLE
Meizu deletes signal as malware

### ISSUE THREAD

**Issue by tgrrr** [signalapp/Signal-Android#5970]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Meizu MX5 deletes signal as Malware on phone updates. It also runs a security check detailing signal as "Malicious App".

I understand this is likely because of the Chinese government.

This _may_ be related to the unresolved problem of application crash on contacts load:
[Application Crash at Contact Search #5308](https://github.com/WhisperSystems/Signal-Android/issues/5308#issuecomment-246050370
)

### Steps to reproduce
- Install Signal on Meizu MX5
- Upgrade to Flyme 5.1.11.1A
- Flyme > Security > antivirus > lists Signal as Malicious App
- Signal APK is no longer on phone

OR

- Install Signal on Meizu MX5
- Flyme > Security > antivirus > lists Signal as Malicious App
- Antivirus is automatically run
- Signal APK is no longer on phone

**Actual result:** 

Signal APK isn't deleted

**Expected result:** 

Signal APK is deleted

### Screenshots

![meizumaliciousapps](https://cloud.githubusercontent.com/assets/4689707/21291485/450adf98-c535-11e6-972c-e3151a8d940a.jpg)

### Device info
**Device:** Meizu MX5
**Android version:** 5.1.11.1A
**Signal version:** 3.24.1

### Link to debug log

Not available, as signal is deleted.

**Comment by sweeper3000** [comment]
> I understand this is likely because of the Chinese government.

The phone is made by a Chinese company (for clarity). Although normally, this sort of thing shouldn't happen outside China (see WeChat inside China vs outside China.

Correct me if I'm wrong, but the most one can do is report that Signal is not a malicious app; not much the developers can do on their end.

**Comment by tgrrr** [comment]
Thanks for the quick reply.

I've reported it to Meizu.

This is posted as an open issue to see if others are having the same issue, 

To see if it's to do with APK signing, etc.

Cheers, P

**Comment by johanw666** [comment]
Are you sure you're not better of by deleting this "security" software from your phone?

**Comment by Dyras** [comment]
So is this Flyme included with the phone or is it something you manually installed?

**Comment by sweeper3000** [comment]
@Dyras Flyme is the modified Android OS installed on the phone

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
