### ISSUE TITLE
AT&T users unable to receive MMS pictures sent from Signal

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#5971]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sending pictures to AT&T users via MMS results in the recipient receiving the following message instead of the picture:

>One or more of the message components have been deleted by MMS Adaptation. Either the message was too large or the components were unsuitable for your handset.

I have encountered this problem when:
- sending to both Android and iPhone users.
- sending from Google Project Fi and T-Mobile US.

An AT&T employee [said in 2015](https://forums.att.com/t5/3G-MicroCell/MicroCell-not-sending-MMS-pix-too-large/m-p/4187723/highlight/true#M16992) that their MMS size limit was 1MB but I have had this problem occur when sending images smaller than that.

I am not sure if this issue is reproducible 100% of the time.

This error message has also been mentioned in issues #380 #494 #511 #920 #1204

### Steps to reproduce
- Send a picture to an AT&T user via MMS

**Actual result:** The recipient receives an error message
**Expected result:** The recipient should receive the picture

### Device info

**Device:** Nexus 5X
**Android version:** 7.0 (N5D91L)
**Signal version:** 3.24.1

### App state
**SMS delivery reports:** On
**'WiFi Calling' compatibility mode:** Off

**Comment by graboskyc** [comment]
I'm having the same issue. Signal installed on a Nexus 5x and Nexus 6P (project fi). Sending MMS picture from Signal on these devices to AT&T (iPhone 6, iPhone 6S, Galaxy S7) reveals that message to the recipient. I can receive MMS images from them. Sending that same MMS picture to a Verizon iPhone 6 works successfully.

**Comment by Emu-latte** [comment]
I'm having the same issue. Signal installed on OnePlus One, Cyanogen OS 13.1.2, android 6.0.1, AT&T network. I can't download MMS from my brother. He is a Signal user & sends from his iPhone. Here's my debug log: https://gist.github.com/ccb97077f207abef4324004e1c86edd4

**Comment by riyapenn** [comment]
@Emu-latte What you described is not the same issue as the title. This issue is for **SENDING** messages.  You can check out the [support page for RECEIVING MMS](https://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do-). 

@graboskyc and @justin- You may want to attach debug logs. And also test w/ WiFi compatibility mode on.

**Comment by Emu-latte** [comment]
@riyapenn OK, my bad, I figured AT&T and MMS fail was maybe the same issue. I checked the SUPPORT PAGE FOR RECEIVING MMS thank you anyway, none of that fixes anything.

**Comment by Emu-latte** [comment]
Actually, the issue is about RECEIVING mms. SEE OP TITLE THX

**Comment by riyapenn** [comment]
The issue title and OP describes a Signal user sending MMS to non-Signal user where the non-Signal user (receiver) does not see the MMS.  So here the only Signal user is the sender.  You described you (Signal user) having issues receiving MMS.  contact support@whispersystems.org or make sure you edit your APN settings / ask your provider to reprovision your device.

**Comment by graboskyc** [comment]
@riyapenn I uploaded the logs. Link is: 

https://gist.github.com/48d52032424cf4ad74f2d77d42854c95

After I enabled Wifi compatibility mode, it worked for one phone number and not another. Both AT&T iPhone 6. Toggling the Wifi setting off again and resending the same photo again yielded the error message on the AT&T handset.

**Comment by notMyUsername** [comment]
Same problem and phone/Carrier/OS version/Signal version as the OP.  Although it happens a lot, it isn't always reproducible - but it happens enough that it is a really serious problem for me.  Sometimes resending the exact same picture will result in its being successfully received.  I've not noticed any pattern as to why it works sometimes and other times it doesn't.

**Comment by dolatron** [comment]
Having same issue with both Nexus 5x and 6p on Google Fi. When sending MMS to users on AT&T they see an error message that the attachment is not suitable. I can receive MMS messages from them and MMS messages sent to VZW & T-Mobile users are received successfully.

- This occurs both when WiFi compatibility is enabled or disabled. 
- This occurs consistently when Google Fi is using T-Mobile as service provider. 

However, I've found that:
- This does not occur when Google Fi is using Sprint as a service provider.
- This does not occur when cellular data is disabled. 

Signal v 3.25.3
Android 7.1.1 
Logs - https://gist.github.com/anonymous/b2011978193ebd05871db854ea6829a8

**Comment by rmeyer100** [comment]
Same problem on Google Pixel running on Google Fi. Images sent from Signal to non-Signal AT&T user results in the OP's error message, both on WiFi and on a cellular connection. Tough bug to deal with, especially since I don't always know which network the recipient is on before I send an image.

Google Pixel
Android 7.1.1
Signal 3.30.4
'WiFi Calling' compatibility mode enabled

Can upload logs later if helpful.

**Comment by drawks** [comment]
I'm also able to replicate this issue when sending an image via mms from signal on t-mobile to another signal user on at&t. Super frustrating...

**Comment by jtsylve** [comment]
I'm seeing this as well with Project-Fi.  T-Mobile has a 1 MB limit, but I'm not sure if that's the issue here.  https://support.t-mobile.com/docs/DOC-5354

**Comment by nomiaed** [comment]
I have the same issue as OP.

Using a Pixel on Project Fi - sending to an iPhone user on AT&T.

**Comment by moxie0** [comment]
I'm hoping 51d61445915e0a607742a46c60332e015f9559b6 helps with this. @drawks nice chart by the way!

**Comment by rmeyer100** [comment]
I'm very happy to report that this appears to be fixed for me with the 4.6.0 update! (Google Pixel, Android 7.1.2, Signal 4.6.0, Google Fi (both cell and WiFi sending).)

Many thanks!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
