### ISSUE TITLE
It is possible to create multiple accounts with the same phone number

### ISSUE THREAD

**Issue by miguelmarco** [signalapp/Signal-Android#5981]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It is possible to create several accounts from the same phone number.

### Steps to reproduce
- Create an account using a real (country code + 9 digits) phone number, plus some extra digits at the end
- Request verification by phone call

**Actual result:** Receive a phone call at the (country code + 9 digits) phone call that gives a verification code for the (country code + 9 digits + extra digits) account
**Expected result:**  The system would detect that the phone number that is receiving the call is not the same as the one trying to get registered, and show an error message.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
