### ISSUE TITLE
Dialing only successful after Signal text message

### ISSUE THREAD

**Issue by s0riak** [signalapp/Signal-Android#5983]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Dailing fails if a contact wasn't receiving a message recently. After sending a text message with random content which is received by the other party without issues, the next attempt for dialing this contact succeeds.
My speculation is:
That the message is send via a websocket connection which is open but the dialling relies on long-polling with the intervals getting too long after a long time of inactivity. The message would activate the receiver, making the dialing afterwards possible. I have not had a look at the source or any documentation but guess from experience in other projects.

### Steps to reproduce

1. Contact B should not use signal for some hours but has not network interruption etc.
2. Contact A tries to call contact B which should fail (dialing indefinitely)
3. Contact A sends a signal text message to contact B which is received immediately
4. Contact A tries to call contact B which succeeds 

**Actual result:** The call in step 2 fails even though contact B can be reached directly afterwards after sending a text message
**Expected result:** The call in step 2 should succeed (No signal text message should be needed to make the dialing of an available contact work immediately)

### Screenshots
not relevant

### Device info
Device of contact A:
**Device:** https://www.bq.com/en/aquaris-m5
**Android version:** 6.0.1
**Signal version:** 3.24.1

Device of contact B:
**Device:** Samsung GT-I9100G
**Android version:** 4.1.2
**Signal version:** 3.21.3

### Link to debug log
not available

**Comment by haffenloher** [comment]
In step 3, does A send an SMS or a Signal message?

How exactly does calling "fail" in step 2? Does it just dial indefinitely?

**Comment by s0riak** [comment]
@haffenloher thanks for the questions. I updated my description to rule out the ambiguity.

**Comment by riyapenn** [comment]
You AND your contact will both have to be connected to the internet for your call to be placed and connect. Signal will continue ringing in your side for a couple of minutes or until your contact answers or rejects your call.  

If the call does not complete, it is likely that your contact is not on an internet connection at the time you placed the call, has settings on their device where Signal can not access the internet,  or you both need to [check your firewall settings](https://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-).

**Comment by s0riak** [comment]
@riyapenn it doesn't seem to be the case, that contact B has no internet connection. The signal text message arrived more or less instantly as expected and the dialing afterwards is successful as well. As this has happened multiple times for me and contact B, I doubt that contact B is offline at the first dialing attempt and just comes online in the very moment the text message send right after is delivered, as there are 5 seconds in between.

**Comment by nullpointer17** [comment]
Same behaviour here... and you saved my day... I was thinking calls wasn't working at all... instead sending a message before the call "solves" the problem. :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
