### ISSUE TITLE
No video thumbnails

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#5993]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since version 3.25.0 (commit a4c17e5325827f4c44e29148adcaf10862dff33d) video thumbnails are supposed to be generated. With version 3.25.3 this does not work. Is it possible that this is due to reverting the update of the support libraries in commit 71f8e9eb31d798051567ac021ef8c9b2dc840139?

### Steps to reproduce
- Attach video
- No thumbnail in draft
- Send video
- No thumbnail for sent video

**Actual result:** No video thumbnails are generated.
**Expected result:** Video thumbnails should be generated.

### Screenshots

![tmp_18505-2016-12-26 23 21 49-396728326](https://cloud.githubusercontent.com/assets/9938306/21487143/f3528eaa-cbc2-11e6-8ec2-7557fa88816d.png)

### Device info

**Device:** Samsung SM-G800F (kminiltexx)
**Android version:** 5.1.1
**Signal version:** 3.25.3

### Link to debug log

https://gist.github.com/billie80/bb7e9dbcb55161f195fe2f886ca48924

**Comment by moxie0** [comment]
Hey sorry, only works on M+. Looks like you're still on L.

**Comment by billie80** [comment]
Thanks for clarifying this. Looking forward to the update to Marshmallow for the S5 mini then.

**Comment by billie80** [comment]
Got the update to Marshmallow (6.0.1) a few days ago. I checked again and there are still no video thumbnails. The following log should contain two trials with two different contacts and two different videos. Signal version is now 4.1.0.
https://gist.github.com/4233bcdb43ff3697fe1dcf813440bc86

**Comment by moxie0** [comment]
I don't see any messages sent or received in this log. The code won't retroactively create thumbnails for previous videos, only for new videos sent/received. Is that what you're trying?

**Comment by billie80** [comment]
Yes I only checked for thumbnails of existing videos. I did not yet send a video but will try this as soon as possible.
I only created a draft containing video. So there are no thumbnails for drafts either?

**Comment by moxie0** [comment]
It's true, there are no thumbnails for drafts. Thanks, let us know if it's not working as it should be.

**Comment by billie80** [comment]
Okay I downloaded a small mp4 test video from http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5. Still no thumbnail!
Here the new log: https://gist.github.com/b37bf51f5fa5bd5ef7f5d0796bb0cbc1

**Comment by billie80** [comment]
The receiver with the same device and Android version also doesn't see the thumbnail.

**Comment by billie80** [comment]
Relevant lines from the log:

AttachmentDatabase: insertParts(1) 03-29 00:06:26.995 9302 10377 W AttachmentDatabase: Inserting attachment for mms id: 678 03-29 00:06:27.085 9302 9302 W ClipboardExManager: hasData : 2, -1, null 03-29 00:06:27.125 9302 9302 W ClipboardExManager: hasData : 2, -1, null 03-29 00:06:27.145 9302 10377 W AttachmentDatabase: Wrote part to file: /data/user/0/org.thoughtcrime.securesms/app_parts/part1682315403.mms 03-29 00:06:27.150 9302 10377 W AttachmentDatabase: Submitting thumbnail generation job... 03-29 00:06:27.150 9302 10377 W AttachmentDatabase: Inserted attachment at ID: (row id: 275, unique ID: 1490738786997) 03-29  00:06:27.160 9302 9320 W AttachmentDatabase: Executing thumbnail job... 03-29 00:06:27.160 9302 9302 W ClipboardExManager: hasData : 2, -1, null 03-29 00:06:27.200 9302 10377 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id,  expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 8) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 8) ORDER BY date_received DESC LIMIT 1) 03-29 00:06:27.220 9302 10377 W CanonicalAddressDatabase: Hitting DB on query [ID]. 03-29 00:06:27.255 9302 9302 W IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection 03-29 00:06:27.290 9302 10447 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 8) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id = (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 8) ORDER BY date_received DESC LIMIT 500) 03-29 00:06:27.300 9302 9320 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer 03-29 00:06:27.300 9302 9320 W AttachmentDatabase: Generated video thumbnail...

Although the log says "generated video thumbnail" the previous message says otherwise.  

Bitmap bitmap = retriever.getFrameAtTime(1000);
from
src/org/thoughtcrime/securesms/database/AttachmentDatabase.java
says "videoFrame is a null pointer". So somehow retrieving an image from the video at I guess 1000 milliseconds fails.

**Comment by billie80** [comment]
I thought there might be something wrong with the video, so I tried again with a recording from the phones camera but the thumbnail generation also failed.

Here again the log file although there is probably nothing new which is of interest:
https://gist.github.com/f5d9722318434da5a74b73e7e29df66f

**Comment by peterpanondrugs** [comment]
Same issue here. https://gist.github.com/a4a6ac0d964836a7c0a59a4fcfa96f49

**Comment by peterpanondrugs** [comment]
- Sharing out of Signal : working thumbnail
- Sharing from another app : not working

**Comment by bme13** [comment]
Tested this with a Samsung S5 running android 6.01 a Samsung J5 Android 6.01 and a Acer running Android 6.0. On both Samsung's no thumbnails are shown however on the Acer this works as expected. Since the final call in MediaMetadataRetriever.java is:
private native Bitmap _getFrameAtTime(long timeUs, int option); 
I assume the problem is somewhere in the Samsung environment however I don't have any android or java experience.

**Comment by bme13** [comment]
I was doing some more tests to get additional information about this and noticed that logcat seems to provide some additional useful information about this.                           
Here is a comparison of a snippet from the Signal log and the output of logcat.

Signal output:
```
10-11 17:08:44.061 29361 29377 W NotificationState: Added thread: 26
10-11 17:08:44.061 29361 29377 W NotificationState: getAndroidAutoHeardIntent Added thread: 26
10-11 17:08:44.071 29361 29379 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
10-11 17:08:44.071 29361 29379 W AttachmentDatabase: Generated video thumbnail...
10-11 17:08:44.081 29361 29377 E ActivityThread: Failed to find provider info for com.teslacoilsw.notifier
```
Logcat output:
```
10-11 17:08:44.051 32326 32326 V MediaPlayerService: Create new media retriever from pid 29361
10-11 17:08:44.061 29361 29377 W NotificationState: Added thread: 26
10-11 17:08:44.061 29361 29377 W NotificationState: getAndroidAutoHeardIntent Added thread: 26
10-11 17:08:44.071 32326 32472 E SavsMetadataRetriever: getFrameAtTime - source is null
10-11 17:08:44.071 32326 32472 E MetadataRetrieverClient: failed to capture a video frame
10-11 17:08:44.071 29361 29379 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
10-11 17:08:44.071 29361 29379 W AttachmentDatabase: Generated video thumbnail...
10-11 17:08:44.071  3407  4269 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = org.thoughtcrime.securesms,userId = 0
10-11 17:08:44.071  3407  3407 D SensorService: SensorEventConnection::SocketBufferSize, SystemSocketBufferSize - 102400, 2097152
```
Specifically the line `SavsMetadataRetriever: getFrameAtTime - source is null` is not in the Signal log.
Now as a test a wrote a small program (just a small variant on the myfirstapp development example :smile:) to see if I could reproduce things and here's what I found.
If I call the setDataSource for the MediaMetadataRetriever with the same arguments as in the Signal source, so using a own MediaDataSource, I get the same errors as happens in Signal however if I call setDataSource with a fileDescriptor argument the thumbnail generation works fine. Apparently the setdatasource with a MediaDataSource argument fails on a Samsung device??
Currently I'm not sure how to continue with this however I thought this might be useful to share.

**Comment by moxie0** [comment]
@bme13 Great investigation. Sadly we have to use MediaDataSource because the file is encrypted on disk, so we can't just pass a FD to the decoder.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
