### ISSUE TITLE
SMS message attempts to send many times

### ISSUE THREAD

**Issue by robotmay** [signalapp/Signal-Android#5997]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal is currently failing to send SMS messages on my Nexus 5X. As part of this, it can actually attempt to send the same message about 20 times in rapid succession, causing Android to prompt whether to block it. I believe this is tied to very bad/flakey mobile reception, as where I am currently it dips in and out. Sometimes it works, sometimes it fails to send for a few minutes, then the Android prompt for SMS sending permissions pops up, and sometimes I get a rapid spree of error sounds and the permission window pops up immediately. The permission window is black, and clicking Allow doesn't actually do anything. 

Sorry if this is a duplicate, I've tried searching but I'm just on my phone and it's pretty annoying to search on!

### Steps to reproduce
- have poor/no signal
- send an SMS

### Screenshots
Haven't managed to get a screenshot of the permission prompt, as it's hard to reproduce.

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/918e602ce8359c9e0779707fdcc05fd5

**Comment by 2-4601** [comment]
Related #4296

**Comment by stifnils** [comment]
I am experiencing the same issue.
When the reception is bad Signal is sending SMS multiple times to the reciver. Many or all of the SMS are getting to the reciver and they are getting spammed with the same SMS.

My log 

https://gist.github.com/c373d528e6f6c922cd179493fd8da050

**Comment by stifnils** [comment]
New log same issue
https://gist.github.com/7f8b6109c0c74e71a4eb7edf8c79d929

**Comment by stifnils** [comment]
Same episode later log
https://gist.github.com/anonymous/7be1095a3892402291d498638cc0137c

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
