### ISSUE TITLE
did not serve GSM Codes

### ISSUE THREAD

**Issue by SnoopDEvelops** [signalapp/Signal-Android#5998]
### Bug description
# =>1v2: Signal doesn't serve GSM Codes,

like:
*T#
*T#Testmessage
*N#Testmessage
to recieve a delivery-protocol as soon the phone is logged in. 

*LATER 01#
to send message time shifted 

and so on...

# =>2v2: Signal lost Groups
It isn't possible to search a Group name.

New Message->Search Contact->Groupname doesn't exist.
its only list real contacts (single)

### Device info

**Device:** Samsung S5
**Android version:** 5.1.1
**Signal version:** 3.25.3 / Signal-Desktop/0.27.0

**Comment by 2-4601** [comment]
Is this like two bug reports in one? The second one sounds like #2378.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
