### ISSUE TITLE
Dual SIM: trouble with default card selection when one SIM is turned off

### ISSUE THREAD

**Issue by souris81-7021** [signalapp/Signal-Android#6005]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal ignores SIM status (enabled/disabled) in dual SIM phones for sending unsecured messages.

### Steps to reproduce
- in a dual sim phone, turn off one of the SIM cards via system settings
- open Signal app
- try to send unsecured message

**Actual result:** Signal tries to send an unsecured message via the last used SIM card
**Expected result:** 
1. Signal respects the availability of the SIM cards, and sends an unsecured message with the active (available) SIM card. 
1. Sending unsecured messages with only one active SIM card does not change last saved SIM card for this conversation (e.g. if both SIM cards are active again, Signal will default to the last used SIM card in dual-SIM mode, ignoring messages sent in single-SIM mode)

### Device info
**Device:** Xiaomi Redmi 3 Pro 3/32
**Android version:** 5.1.1 / MIUI 8.2 by xiaomi.eu 6.12.1
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/anonymous/ca35fb40f5d4778301250713a0039464

**Comment by muellert** [comment]
I have a similar problem. I am having a OnePlus 3 with two different SIM cards, and I have installed LineageOS on this phone. In the settings, I need to set a default SIM for sending texts, which I choose according to which country I am in, or whom I want to text - most of my conversational partners are actually using plain texts, no encrypted messages, btw. My Signal account is registered to one of the SIMs, but it is currently unfeasible to use this card as the default card for sending texts, so I selected the other card for sending texts. However, Signal tries to send texts via the non-default card, which then do not get delivered. Only once the other side has texted me on the number of the non-default card, Signal starts to also send texts to this party via the non-default card. But the upshot is that I cannot send a text to anyone whom I've not yet received a text from on the non-default card.

**Comment by haffenloher** [comment]
@muellert that sounds more like a support issue (you can long-press the send button to choose the other SIM). If you need more help with troubleshooting, you're welcome to open a thread at our [community forums](https://whispersystems.discoursehosting.net/)!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
