### ISSUE TITLE
Feature Request: Disappearing Message Time of 15 Minutes

### ISSUE THREAD

**Issue by Enekk** [signalapp/Signal-Android#6013]
The disappearing message function is something that I make heavy use of, but there seems to be a gap in the options.
When thinking about how long some conversations go, 5 minutes seems too quick, but 30 minutes is too long.
I'd love for there to be a 15 minute option.

Given some of the feature requests I saw while looking to see if someone else asked for 15 minutes, it might be smart to support a custom time option somewhere.

**Comment by pprucia** [comment]
I think it would be better to have 10 minutes instead of 15. This would match seconds values - 5s, 10s, 30s.

**Comment by narzb** [comment]
Why not add a manual selector to choose the desired time ?

**Comment by mawed** [comment]
I personally would like 1 month much more as an option as 1 week is not that long time for a history of a conservation.

I don't think a manual selector will be integrated as this does not fit OWS mentality. (For example: choosing conservation color wasn't integrated to be choosen completely manually.

**Comment by narzb** [comment]
I think a selector with weeks / days / hour / minutes would suffice and keep the mind "KISS".

This is not complicated to use, does not add complexity to the program and it covers all needs.

And to truly not confuse the user, we could add the option "manually select" in the list of predefined choices.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
