### ISSUE TITLE
Replying to a specific message and have the message quoted

### ISSUE THREAD

**Issue by gabridome** [signalapp/Signal-Android#6017]
- [] I have searched open and closed issues for duplicates

I have open the same ticket in Signal-iOS https://github.com/WhisperSystems/Signal-iOS/issues/1557 being a request for the two platform.

----------------------------------------

### Bug description (in reality is a feature request)

Especially in group chat but also in individual ones Telegram and (now) whatsapp allow to quote a previous message by tapping it and choose "reply". This action create the new message with on top the summary of the message you are referring to. In Telegram (desktop version) there's also the possibility to quote specific parts (selection) of a previous message. In this case the selection apears in the new message quoted with the ">" sign.

In group chat this is almost mandatory because you cannot follow easily the threads that normally form in the chat.

I miss this a lot in signal. I have searched and I didn't find a similar feature request.

Thank you for the wonderful job you are doing.

**Comment by tdemin** [comment]
This functionality is also available in WhatsApp, and it's great, yeah. Would love to see it available in Signal as we have to quote the messages by hand.

I've attached a screenshot showing how does it look like in WhatsApp Desktop.
![2017-02-03 18_30_36-whatsapp](https://cloud.githubusercontent.com/assets/25529819/22593156/09fe59dc-ea3f-11e6-943d-4479af838a8f.png)

**Comment by mcagl** [comment]
I'm trying to use Signal more and more as time passes (I don't use Whatsapp but I'm a heavy Telegram user (from f-droid)), and I find this a really useful feature, in groups but also in 1:1 chats.

Please add support for message replying and quoting to Signal.

thanks in advance!

**Comment by gabrielfranco89** [comment]
This should be a great feature. Many friends of mine don't move to signal because of this feature in WhatsApp. 

It could be simpler than the wtspp feature: I imagine the following procedure:

1) user hold the message he wants to reply
2) user choose the button reply
3) app simply quote the selected message below the text box
4) user replies quoting the message right below his answer. 

This procedure don't have to manage past messages since it just quote a current conversation. It's more like a automatic copy and paste. What do you guys think?

I don't have android or iOS developer abilities to test this, but I think it is a nice start.

**Comment by albalitz** [comment]
I think a nice way to approach this is how Conversations does it (which is similar to what @gabridome suggested in the original description of this issue and similar to what @gabrielfranco89 suggested in their comment).
Conversations offers to quote text in a long press menu and then copies the quoted text, prepending a '>', making it a markdown quote. "Quote lines" are rendered like quotes here on GitHub.
This does not only allow quoting messages from the conversation itself, but anything the user wants to quote by simply starting the line with '>'. Markdown-like display would probably make this related to #5534.

**Comment by danblank000** [comment]
I too want to throw my hat in and say that this is the only feature I feel is lacking in am otherwise awesome but of software!

**Comment by ruppalsingh** [comment]
@danblank000 Please use the thumbs up emoji on existing posts to express your support for an idea, if you have nothing new/constructive to add.

**Comment by FWCologne** [comment]
To add to this request: At least Telegram (can't say anything about Whatsapp as I don't use it) allows you to jump to the quoted message if you tap on the quote, which is imo very useful to view the quoted message in context. Threema allows to quote, but doesn't have this specific "jump" feature.

**Comment by kolaente** [comment]
> To add to this request: At least Telegram (can't say anything about Whatsapp as I don't use it) allows you to jump to the quoted message if you tap on the quote, which is imo very useful to view the quoted message in context. Threema allows to quote, but doesn't have this specific "jump" feature.

Same goes for whatsapp

**Comment by wjh** [comment]
Out of interest, what would need to be done to support this?

**Comment by Meteor0id** [comment]
It might be important to note that this quotation option could later be extended to quoting web-pages. For those familliar with whatsapp of twitter, web-sites (most notably blogs and news-sites) have share buttons, which lead to an automatic quotation in a social media post. By adding meta data on the web-page, the social media application can show a preview image and a header of the shared article.

The reason I bring this up here is that the citation system would best we written with this future feature also in mind.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
