### ISSUE TITLE
Re encode video files before sending to lower video size

### ISSUE THREAD

**Issue by mderazon** [signalapp/Signal-Android#6020]
This is a feature request.
I couldn't find any mention to this in any of the issues, except maybe [this](https://github.com/WhisperSystems/Signal-Android/issues/672#issuecomment-251770633) comment by Moxie.

I know images are being changed and resolution is being lowered before being sent. I think that something similar should be done for videos. Videos from phone cameras these days can be huge (4K resolutions) and sending this over the wire just so it'll be viewed on a small screen is a waste.
I am talking about **lossy** comression / re-encoding.

I'm assuming this is not an easy feature because of the plethora of different codecs and containers formats and cross compatibility issues between ios-android and probably more issues I haven't thought of. Nevertheless, I think it can improve the app significantly.

I use Whatsapp a lot and I think that video takes a big chunk of my media messages, I would say almost 50/50 with images. If Signal was as convenient for sending videos as it is to send images, people would send many more videos.

**Comment by rmueller83** [comment]
Currently, if you send a webm video from Signal-Android to Signal-iOS, the video cannot displayed on iOS due to lack of webm support. Re-encoding could fix this, too.

**Comment by gordon-morehouse** [comment]
It would be further good to clarify, in documentation AND error messages, what the size limits are, until this feature request is implemented or closed.

The error messages are not helpful. "Can't play this video" and/or "Sorry, there was an error setting your attachment" provide no useful information as to WHY.

**Comment by waz452** [comment]
I personally think there should be an option to re-encode to different % levels.  

Sometimes you want to send a high quality photo, and from what I've found, its not possible. (Anyone know how to send high quality images through Signal?)

Would something like the following work?  (Sorry if I haven't explained it properly)
1) Using normal Signal encryption patterns - file is encrypted and uploaded to Google drive
2) Link is then shared to receiving party
3) When receiving party clicks the link, it downloads encrypted file 
4) As file is encrypted like a normal Signal message, that user is able to view the file
However, if the link is just given to another person, they won't be able to view the file as its encrypted using secure Signal encryption
Likewise if Google / whoever want to access the files, they will be unable to open the file either as it didn't pass through Signal that would "decode" the encryption so basically you have a invalid file that can't be accessed

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
