### ISSUE TITLE
Countries where registration does not work

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#6027]
If Signal registration does not work with your country and telco, please add that as a comment on this issue, and it will be updated on the tables below and looked into.

# :x: User reported countries where registration has issues

Country | Telco | Country prefix |  Telco prefix | Example number | Comments
------- | ----- | -------------- | ------------- | -------------- | --------
Bosnia and Herzegovina | [m:tel](http://www.mtel.ba/) | +387 | 065, 066 | **+387**655639xx | https://github.com/WhisperSystems/Signal-Android/issues/5384#issuecomment-263814431: SMS verification does not arrive or is delayed
Bosnia and Herzegovina |  | +387 | 33 | **+387**33123456 | landline
Albania | vodafone | +355 | 66 | **+355**661234567 | works successfully on Telekom Albania (T-Mobile)
Andorra |  | +376 |  | **+376**812345 | 
Czech Republic |  | +420 |  | **+420**512345678 | 
Malaysia | Maxis | +60 | 012, 017, 014-2, 011-2 | | User says he tried registering on both Wi-Fi and data, and that he can't open the OWS homepage on a browser. https://redd.it/6tdemt
Turkey|Avea|+90|‭0554|‭00 90 554 123 45 67|Could not register via both, wifi and mobile
Vanuatu |  | +678 |  |  | https://github.com/WhisperSystems/Signal-Android/issues/5850#issuecomment-264768879 Server says "Bad response: 400 Bad Request" for 6 digit numbers
Greenland |  | +299 |  | **+299**(6moredigits) | 
 Netherlands VoIP| |+31 97 |  | +31 97 12345678 | cell phone numbers of +31 6 12345678 currently work
 Finland | DNA/Radiolinja  | +358  | | +358 123456 | ~2k 6 digit numbers exist, 7 digit numbers from Finland have no issue
Belarus | Velcom, MTS | +375 | 29, 33 or 44 | **+375**291234567 | example number in internal format 80291234567
Macedonia | Telekom (T-Mobile) | +389 | | **+389**70xxxxxx, **+389**75xxxxxx | "It used to work perfectly on my older iPhone's Signal app, but now I'm not receiving SMS confirmation codes. Calls as well."
 |  |  |  |  | 

# :x: Other countries where registration would not work

Country | Telco | Country prefix |  Telco prefix | Example number | Comments
------- | ----- | -------------- | ------------- | -------------- | --------
Niue |  | +683 |  | +683(4digitnumber) | 
Tokelau |  | +690 |  | +690(4digitnumber) | 
Ascension Island |  | +247 |  | +247(4digitnumber) | 
Chad |  | +235 |  | +235250(4digitnumber) | 
Solomon Islands |  | +677 |  | +677(5digitnumber) | landline
Cook Islands Format |  | +682 |  | +682(5digitnumber) | 
St. Helena and Tristan da Cunha |  | +290 |  | +290(4/5digitnumber) | 4 digits according to wiki, but twillio has it with 5 digits
Samoa |  | +685 |  | +685(5digitnumber) | 
Suriname |  | +597 |  | +597(6digitnumber) | 
 Sweden | Telnor SE | +46  | aaa | +46 aaa 0xx yyy zzzz | not a valid [Twilio](https://www.twilio.com/lookup) format, but supported by Telnor
 |  |  |  |  | 
 |  |  |  |  | 

***

# :white_check_mark: Fixed so far

Fixed by | Country | Telco | Country prefix |  Telco prefix | Example number | Comments
-------- | ------- | ----- | -------------- | ------------- | -------------- | --------
https://github.com/WhisperSystems/Signal-Android/issues/6027#issuecomment-292476935 | Bosnia and Herzegovina | [BH Telecom](https://www.bhtelecom.ba/) | +387 | 060, 061, 062 |   | https://github.com/WhisperSystems/Signal-Android/issues/6027#issuecomment-282892525
https://github.com/WhisperSystems/Signal-Android/issues/6027#issuecomment-292386068 | United Arab Emirates |  | +971 |  | **+971**41234567, **+971**551234567 | #5988: [Censorship](https://github.com/WhisperSystems/Signal-Android/commit/541718fd114a6f2336222a571869e1056cd122dd)? SMS verification doesn't come through, call verification works
https://github.com/WhisperSystems/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e | Faroe Islands |  | +298 |  | **+298**123456 | #5291: Server says "Bad response: 400 Bad Request" for 6 digit numbers
https://github.com/WhisperSystems/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e | Equatorial Guinea |  | +240 |  | +24007(4digitnumber) | 
https://github.com/WhisperSystems/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e | New Caledonia |  | +687 |  | **+687**123456 | #5850: Server says "Bad response: 400 Bad Request" for 6 digit numbers
https://github.com/WhisperSystems/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e | French Polynesia |  | +689 |  | +68922(4digitnumber) |

**Comment by laurentdinclaux** [comment]
I don't know what telco is but please add New Caledonia (+687) to the list of non working countries.

**Comment by 2-4601** [comment]
@laurentdinclaux It already is there, as is Vanuatu which you mentioned in your issue (#5850)

**Comment by moxie0** [comment]
Shouldn't new caledonia, andora, etc work as of https://github.com/WhisperSystems/libsignal-service-java/commit/df5be03e6fc7b06dc2547069ccb5fc717a89581e?

Also let's not tell people to add a zero to their number, that seems like it's bound to cause endless pain in the future.

**Comment by laurentdinclaux** [comment]
@moxie0 the issue is server side

And yes I didn't go further using the 0 "workaround", just noticed that I could activate my account this way, end of the story.

**Comment by moxie0** [comment]
Alright maybe this chart (thanks for making it @2-4601!) should include what the issue is.  Seems like there's a problem with SMS/Voice delivery in some cases, or client/server not considering it a "valid" number for registration in others.

**Comment by 2-4601** [comment]
:+1: I'll remove the 0 workarounds. The comments have references to issues which have more details but I'll add the short version to the comment field.
Some of those table rows are just added from @riyapenn's list so I don't know the exact cause of those issues, I assume she got the info through the support system?

**Comment by Trolldemorted** [comment]
you maybe should add UAE: #5988

**Comment by laurentdinclaux** [comment]
@moxie0 it is simple to test, visit https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+687888888 you'll get a HTTP 400 Bad Request, add a zero, no error (but the sms won't get sent, my work around implies waiting for the call alternative wich work with the added 0)

**Comment by 2-4601** [comment]
@Trolldemorted I was intending not to include countries in the list where registration does not work due to censorship. I think that's kind of a separate issue and the cause in those cases is clear. These are mostly some weird number issues, telcos unintentionally doing something odd, Twilio not supporting some countries, or some issue with the Signal registration infrastructure or client bugs. But I guess in some cases it's not clear if the issue is about [malice or stupidity](https://en.wikipedia.org/wiki/Hanlon's_razor).

**Comment by Trolldemorted** [comment]
@2-4601 in UAE's case, i think it is not yet clear whether it is censorship or a twilio hickup.

I mean, who would censor the sms but allow the calls to go through?

**Comment by johanw666** [comment]
These call and sms systems are used for a lot of things so blocking them completely has side effects they may not like, but the contents of the sms are easy to filter on. Filtering the call realtime on a content-base is much more difficult.

**Comment by LaMpiR** [comment]
Hi. For Bosnia +387 33 is a landline number. Don't see how one can use Signal on the landline phone?
Mtel with +387 65/66 has problems.

**Comment by 2-4601** [comment]
> Don't see how one can use Signal on the landline phone?

You can use any number with Signal that can receive SMS or **call** verification from Twilio.

> Mtel with +387 65/66 has problems.

Could you provide an example number? (Mainly interested in the prefixes, formatting and number of digits in the phone number)

**Comment by LaMpiR** [comment]
All numbers in Bosnia and H. go with 3 prefix numbers and 6 numbers after that.
So, for example +387 country code, 33(code for the landline in city Sarajevo) 333-222(for the number).
Mobile phones use following prefixes:

060	happy
061, 062 , 060	BH Telecom
063	HT ERONET
064	haloo
065, 066,	m:tel
067	izi mobil

So an mtel number which I used would be +387 65 563 9xx.
I've tested on three +387 65(mtel mobile provider) numbers. 

A bigger list here, but it is more for landlines since every city has its own prefix. Sarajevo is 033, Banja Luka is 051 and so on.

If you need more help, happy to provide it since I would very much like to use signal.

**Comment by moxie0** [comment]
https://github.com/WhisperSystems/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e

+298, +240, +687, and +689 should be good now as far as Signal server filtering

**Comment by laurentdinclaux** [comment]
I can confirm that +687 works properly now. Thank you for the fix.

**Comment by LaMpiR** [comment]
Do we have any news on the reason it's not working with sms verification? I would really much like to use it and would help in any way I can with this.

**Comment by 2-4601** [comment]
@LaMpiR In #5384 some users from your country reported that registering had worked before, then stopped working and then started to work again. Moxie said that during that time nothing specific was done on OWS end so it must have been either Twilio or the mobile carrier.
If you could test registering on another telco than m:tel it might help to rule out the culprit.

**Comment by LaMpiR** [comment]
#Bosnia

So, I called a friend of mine, who is on Eronet and he managed from the first try. Called my father, tried and from the second time managed.

But today, I sent him few messages and he didn't get them and the I was seeing that the messages are delivered and likewise but none of us received messages. I've restarted the encryption process and it worked but still haven't received previous messages.

**Comment by HamzaAdilovic** [comment]
#Bosnia

**Comment by jonalmeida** [comment]
I can confirm that Signal works in UAE currently. The telecom providers haven't blocked registration or voice calls (yet?).

**Comment by HamzaAdilovic** [comment]
#Bosnia I can confirm that BH Telecom numbers (061/062/060) are working now.

**Comment by belag** [comment]
+381 (Serbia), Telenor network also NOT working. Neither SMS or call comes through. 069, 063 area code..

**Comment by bpdkaufman** [comment]
+236 (Central African Republic) on Orange and Telecel not working. Neither SMS or call come through. Works if i register a Google Voice number in the country, but not my SIM card number.

**Comment by NinebitX** [comment]
@2-4601 @riyapenn: Here's a new one: 

Country | Telco | Country prefix | Telco prefix | Example number | Comments
-- | -- | -- | -- | -- | --
Malaysia | Maxis | +60 | 012, 017, 014-2, 011-2 | | User says he tried registering on both Wi-Fi and data, and that he can't open the OWS homepage on a browser. https://redd.it/6tdemt

**Comment by dziaineka** [comment]
Neither SMS nor call registration works in Belarus.
Samsung S7 Android 7.0

**Comment by AykutCevik** [comment]
Another new one:

|Country|Telco|Country prefix|Telco prefix|Example number| Comments|
| ------------- | ------------- |------------- |------------- |------------- |------------- |
|Turkey|Avea|+90|‭0554|‭00 90 554 123 45 67|Could not register via both, wifi and mobile|

**Comment by dkim1958** [comment]
registration does not work in Belarus (+375), GSM provider is Velcom (29 or 44), example number are +375 29 1234567 (international format) or 8029 1234567  (internal format). No SMS, no call...

**Comment by OoTheNigerian** [comment]
Nigeria. (+234)

My network is 9 Mobile (formerly Etisalat) I ported my number from GLO to it.

**Comment by stavreski** [comment]
I'm reporting a verification problem here in Macedonia. I'm using Telekom, T-Mobile network: +389-70xxxxxx, +389-75xxxxxx. It used to work perfectly on my older iPhone's Signal app, but now I'm not receiving SMS confirmation codes. Calls as well. :(

Help!

**Comment by Arny2018** [comment]
registration does not work in Belarus (+375), GSM provider is MTS (29 or 33), example number are +375 33 1234567 (international format) or 8033 1234567 (internal format). No SMS, no call...
Help!!!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
