### ISSUE TITLE
Recent photos thumbnails not updated after opening conversation

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#6028]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The "recent photos thumbnails" shown above the attachment selector does not update itself after opening a conversation.

### Steps to reproduce
- Open conversation. Open attachment drawer and note thumbnails shown.
- Switch to some other app & save image.
- Come back to conversation, open attachment drawer and you'll see that the new photo is not shown in the thumbnail list.
- Leave the conversation and select a conversation from the main screen. Now try to add attachment and you'll see that the thumbnails have updated.

**Actual result:** 
Thumbnail list is not updated.

**Expected result:** 
It'd be nice if the thumbnail list updated itself at least every time the attachment drawer is opened, if not periodically while the attachment drawer is open.

### Device info

**Device:** Moto G 2013 (falcon)
**Android version:** CM 13.1
**Signal version:** 3.26.2

### Link to debug log
Not useful here.

**Comment by moxie0** [comment]
Good catch, seems like we need a content observer to invalidate that cursor loader

**Comment by brianpgrissom** [comment]
I've noticed that those thumbnails don't include videos - could that be related? Or does the thumbnail mechanism only specify photo-media?

**Comment by dcherian** [comment]
@brianpgrissom That sounds like a different bug. Perhaps it only lists photos; probably open another feature request issue asking for videos to be presented.

**Comment by piratenpanda** [comment]
This is still in 4.7.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
