### ISSUE TITLE
 Group chat are lost(!) if disappearing messages are enabled and cannot be recovered

### ISSUE THREAD

**Issue by Rolf558** [signalapp/Signal-Android#6038]
Hi,

In build 3.26.2 the complete chat/group is deleted after deleting all its messenges. This is extremely annoying for groups. I lost a group after deleting it's messages and I also wondered why chats have vanished. The reason was that the self destruction timer has deleted the last remaining message.

**Comment by Rolf558** [comment]
@moxie0 build 3.27.0 is still affected by this regression bug. Please let me know if the description is unclear and you need further information.

**Comment by 2-4601** [comment]
Is this really a regression? I remember it has always been that if there are no more messages in a conversation it is not shown in the conversation list anymore.

**Comment by ocram** [comment]
> Is this really a regression? I remember it has always been ...

Thought so, too. But ...

> The reason was that the self destruction timer has deleted the last remaining message.

A group really shouldn't disappear for that reason.

**Comment by Rolf558** [comment]
I am using TextSecure/Signal since several years. I noticed this behavior with build 3.26.2 the first time. However I am not really sure if it is a regression or not.

Nevertheless we seem to agree that this bug has to be fixed.

I also agree that the loosing of groups is the biggest issue cause by this bug. However since chats and goups should behave the same and it is common also for other popular messaging apps to keep chats and groups although if they contain no message (until it is explicitly deleted by the user) thi bug should be fixes for both chats and groups equally.

**Comment by wizardofid** [comment]
Problem is that you can't find (and use) a group any longer when it has vanished (#6053). You have to wait until someone else posts something into the group... I'd see this not as a problem if a fix for #6053 allows to find and use my groups even if they contain no messages at this moment.

**Comment by moxie0** [comment]
Yeah I think threads with no messages should disappear from the thread list, but that groups should appear in the contact list when you tap the FAB from the conversation list.

**Comment by Rolf558** [comment]
(@2-4601 You seem to be right. Chats are also vanishing in Silence app which is is based on Signal code. So it is very unlikely that it is a regression.)

**Comment by Rolf558** [comment]
Would it be possible to define a milestone? I lost my groups again. :-(

**Comment by Rolf558** [comment]
No update? Message timer cannot be used for groups until this bug is fixed.

**Comment by rossPatton** [comment]
Can this issue get fixed please? It's extremely annoying and a huge detriment to recommending Signal for group messaging

At the very least, one should be able to find the group after it's been 'deleted'

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
