### ISSUE TITLE
performance degradation

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#6039]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
thanks to git bisect, i noticed that 1b44bdcd3cafee26f08327f4ba6d9462d5713875 increased the initial startup time. On my nexus4 it takes at least 2x as long to start compared to 3.24.1.

### Steps to reproduce
- close all apps
- wait some seconds
- start signal

**Actual result:** Signal should startup as fast as before the commit, or faster
**Expected result:** it does not

### Device info

**Device:** Nexus 4
**Android version:** 7.1

**Comment by nrizzio** [comment]
@Trolldemorted are we sure the performance degradation isn't a byproduct of *MultiDex*? Scribbles were introduced a little while ago, while MultiDex was fairly recent. This is just an anecdote but I feel that the introduction of sluggishness is more recent than scribbles.

**Comment by moxie0** [comment]
Huh, that's weird, nothing in that commit should affect initializing the application context, or the conversation list. Can you quantify how much slower this commit is, and where the *additional* time is going?

**Comment by Trolldemorted** [comment]
@nrizzio Note that this issue is describing the *startup* delay only. I did not yet try to trace down the overall sluggishness, as this was easier to test. And yep, i tested several times, 3.24.1 starts faster than the following commit.

@moxie0 Maybe i can try to measure it tomorrow, but i think on the nexus4 we are talking about a difference of 1-2 seconds.

Maybe this is related to throtteling? On my redmi note3 signal starts instantly when pokemon go is running, but when no apps are running i have two wait 1-2 seconds (signal just displays a white screen).

**Comment by Trolldemorted** [comment]
unfortunately i have not found a way of measuring that did not interfere with the result. 1-2s is pretty accurate though, i think.

**Comment by Stuie** [comment]
I'm not seeing slow startup on my Nexus 4.

I added [Hugo](https://github.com/JakeWharton/hugo) annotations to the `ApplicationContext` and `ConversationListActivity` startup methods. I've attached some timings at the bottom of this comment.

I've also run the profiler on startup (again, debug apk), and I don't see anything bad in there, but I'm also not experiencing the symptom.

I have created [a gist](https://gist.github.com/Stuie/d3a3971cda79fa394df9c8121debb0ae) to provide you with a patch. If you're able to apply it and report back the figures you see in logcat then we may have more luck diagnosing the root cause.

You can apply it by entering the top-level directory of the project and running this `git apply /path/to/signal-hugo.diff` (although if you're using git-bisect then I'm sure you can apply a diff. :)

# ApplicationContext
```
|              Method              | First Launch | Second Launch | Third Launch |
|----------------------------------|--------------|---------------|--------------|
| ApplicationContext.onCreate      | 129ms        | 130ms         | 122ms        |
| initializeDeveloperBuild         | 0ms          | 0ms           | 0ms          |
| initializeRandomNumberFix        | 3ms          | 2ms           | 2ms          |
| initializeLogging                | 7ms          | 1ms           | 1ms          |
| initializeDependencyInjection    | 26ms         | 25ms          | 28ms         |
| initializeJobManager             | 19ms         | 20ms          | 23ms         |
| initializeExpiringMessageManager | 44ms         | 43ms          | 41ms         |
| initializeGcmCheck               | 10ms         | 10ms          | 8ms          |
| initializeSignedPreKeyCheck      | 0ms          | 0ms           | 0ms          |
| initializePeriodicTasks          | 10ms         | 14ms          | 8ms          |
| initializeCircumvention          | 1ms          | 1ms           | 1ms          |
```

# ConversationListActivity
```
|              Method              | First Launch | Second Launch | Third Launch |
|----------------------------------|--------------|---------------|--------------|
| onPreCreate                      | 1ms          | 0ms           | 0ms          |
| onCreate                         | 178ms        | 187ms         | 202ms        |
| initializeContactUpdatesReceiver | 5ms          | 2ms           | 4ms          |
| showRatingDialogIfNecessary      | 0ms          | 0ms           | 1ms          |
| onResume                         | 8ms          | 6ms           | 6ms          |
```

[Tables created on here](https://ozh.github.io/ascii-tables/)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
