### ISSUE TITLE
Add a mute action from notification/wearable

### ISSUE THREAD

**Issue by dmchurch** [signalapp/Signal-Android#6040]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
It would be nice to allow quick access to the conversation mute feature from the message notification, especially for group conversations, like the "Mark as read" action. It should have a predefined time that it will mute the conversation for, perhaps 1 hour, perhaps 2 hours, perhaps user-configurable in app settings. This would be useful, for example, when a conversation starts up in a group channel that you don't need to be a part of, or if you're active on a linked device and don't need to get notifications to the phone.

### Steps to reproduce
- Message arrives in a conversation
- Check what actions are available from the phone notification
- Check what actions are available from the wearable notification

**Actual result:** The only actions available are "Mark read" and "Reply"
**Desired result:** "Mute" is an additional single-click action, like "Mark read"

### Screenshots
(screenshots of notifications showing "Mark read" and "Reply" actions on both phone and wearable)

![image](https://cloud.githubusercontent.com/assets/605817/21897545/e64cdaba-d8b7-11e6-8dcb-74b2c85b2551.png)
![image](https://cloud.githubusercontent.com/assets/605817/21897138/b2cb4c4a-d8b6-11e6-8c4a-414409f8ed91.png)

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 3.26.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
