### ISSUE TITLE
Disappearing message timer starts before media download completes

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6041]
I have:
- [X] searched open and closed issues for duplicates Related: https://github.com/WhisperSystems/Signal-Android/pull/5628#issuecomment-244275261
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Timer starts when read as opposed to when read after fully downloaded

### Steps to reproduce
1. Connect to this specific WiFi network where network speed can be down to even few kb/s.
2. Set timer
3. Receive message

**Actual result:** 
No timer: photo downloads and appears as normal. 
10s: photo downloads for ~3 seconds and then appeared, photo displayed for 7 seconds
5s: photo downloads for ~4 seconds and then appeared, photo displayed for 1 second
**Expected result:** 
Timer starts after message downloaded

### Screenshots

N/A

### Device info

**Device:** OnePlus 3
**Android version:** 6.0.1
**Signal version:** 3.26.2

### Link to debug log

https://gist.github.com/02e8d7aa0a619a29bc04e509b681de88

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
