### ISSUE TITLE
signal-android thinks a user is unregistered, signal-desktop does not

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#6049]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
title says it all, i think.

I know Signal-Server sometimes just forgets users, that messages in groups with unregistered users aren't synced to siblings on android, but i think we do not yet have an issue where Signal-Android and Signal-Desktop have different opinions on who is unregistered.

### Steps to reproduce
- have a group
- notice messages aren't synced
- check the debug log: a user appears to be unregistered
- check signal-desktop, says its messages are delivered to all group members

### Device info

**Android version:** 6
**Signal version:** 3.26.2

### Link to debug log
https://gist.github.com/anonymous/f11e806c6081866b8e177a1c60fae42c

**Comment by yhager** [comment]
I'm seeing a similar issue - can't send/receive anything on the mobile, but desktop happily sends/receives messages. This happened after a phone wipe + reinstall. I connected the desktop, but they don't seem to agree on registry info..

https://gist.github.com/anonymous/dae7e76b04be052e9da5d034512e21c5

**Comment by grinapo** [comment]
and #5531 may be also related.

**Comment by Trolldemorted** [comment]
@moxie is this fixed by https://github.com/WhisperSystems/libsignal-service-java/commit/089b7f11239eaa475a78ae064c6df22b5b88b74f?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
