### ISSUE TITLE
Add support for carrying out conversations within the notification on Android N

### ISSUE THREAD

**Issue by lokesh-krishna** [signalapp/Signal-Android#6050]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
Signal now supports Android N's Direct Reply feature but doesn't make use of MessagingStyle to let you carry out conversations within the notification.
Adding support for this would make the implementation more complete.

Implementation of this has been documented: https://android-developers.googleblog.com/2016/06/notifications-in-android-n.html#messagingstyle

**Actual result:** Currently, replying to a message from within the notification makes the notification go away and a fresh notification is created for the reply to your message.
**Expected result:** Replying to a message from within a notification would append your reply to the notification and the notification will persist until the user swipes it off, with further replies from either side being added to the current notification.

### Screenshots
![messagingstyle](https://cloud.githubusercontent.com/assets/20235646/21952081/fdaa201e-da38-11e6-9e6f-2d737f8a812c.png)

**Comment by LaughingCabbage** [comment]
I would like to look at implementing this feature. Is anyone familiar with the notification system that can outline the challenge of this addition. Why this is still an open feature after #6693?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
