### ISSUE TITLE
Possibility to rotate and crop images (in scribble mode)

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#6051]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request description
When shooting or selecting an image, it get's put into the scribble-mode where it is possible to edit the picture with doodles, notes etc.
I think it would be great if there was a possibility to rotate and/or crop the image before sending.
(This could be done also with more image-editing functions as filters, contrast, brightness....)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
