### ISSUE TITLE
Phone number formats in contact list don't follow changes in Android's address book

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#6060]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The character grouping of phone numbers displayed in Signal's contact list doesn't change according to the one used in Android's address book.

I wonder if this is related to #4191

#### Potentially related or additional issue
Furthermore - I don't know if this is really related or rather a separate issue (but for me, it happened within the same couple of minutes) I've had the rather strange experience that after changing the phone number format of contact A in Android's address book, suddenly contact A completely disappeared from Signal's contact list and was replaced by another contact (contact B), displayed as using Signal (without any "hey" message, though). While contact B has always been a member of my address book, I'm absolutely sure that contact B doesn't use Signal. After updating Signal's contact list another time, that "ghost Signal user" disappeared again (or rather was displayed correctly as a non-Signal user) and contact A was back. I've saved a log for this, but am unsure if this is of help for this case.

Edit: The second/additional issue could have been a case of https://github.com/WhisperSystems/Signal-Android/issues/6488

### Steps to reproduce
1. Add a Signal-using contact to Android's address book using the phone number format ```+491231234567```
2. Open Signal, update contacts, get "xyz is on Signal, say hey!"
3. Check phone number format displayed in a) Signal's contact list and b) conversation activity. Both show the format/character grouping used in Android's address book.
4. Go to Android's address book and change the phone number's format to ```+49 123 1234567```.
5. Open Signal, update contacts.
6. Again, check phone number format displayed in a) Signal's contact list and b) conversation activity.
7. Note that while in the conversation activity, the phone number's character grouping has changed to the new one used in Android's address book, the character grouping in the contact list hasn't changed (i. e. is still the initial one).

**Actual result:** Phone number format in Signal's contact list doesn't change.
**Expected result:** Phone number in Signal's contact list should change according to the one used in Android's address book.

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.27.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
