### ISSUE TITLE
Connecting devices is not possible on smart watch due to menu being out of display.

### ISSUE THREAD

**Issue by lawilog** [signalapp/Signal-Android#6062]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I want to connect a device (on desktop), but the menu to do that is not displayed on a small smart watch display. I assume the control buttons are below, out of display.

### Steps to reproduce
- open settings
- open Connected devices ("Verknüpfte Geräte" in German)
- click "+" to add (shown on the left in screenshot below)
- scan QR code on computer screen
- be frustrated at menu (shown on the right in screenshot below)

**Actual result:** Disfunctional menu. Can only go back.
**Expected result:** Be able to connect device (or may answer no). I would like to be able scroll down, or zoom out, ... or say "yes", or have a clickable button on top.

Maybe remove the icon on top.

### Screenshots
![too_small_for_smartwatch](https://cloud.githubusercontent.com/assets/1273913/21996953/f0a56b3a-dc2c-11e6-8cd4-f2354e115c4a.jpg)

### Device info
**Device:** enox Wrist-Smart-Phone WSP88 Version 2
**Android version:** 4.4.2
**Signal version:** 3.25.4
240 x 240 pixel display

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
