### ISSUE TITLE
Don't let twitchy fingers open RecipientPreferenceActivity twice

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#6065]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
You can open RecipientPreferenceActivity twice (on top of each other)

### Steps to reproduce
- open a conversation
- rapidly tap the contact name
- watch the contact name animation happen twice and RecipientPreferenceActivity open (twice)
- tap the back arrow on top left

**Actual result:** RecipientPreferenceActivity is still open
**Expected result:** You get back to the conversation

### Screenshots
![twitchy recipientpreferencesactivity](https://cloud.githubusercontent.com/assets/174176/22028455/ea4db810-dcdf-11e6-973f-099c40a821c3.gif)

### Device info
**Device:** Moto G4 Play
**Android version:** 6.0.1
**Signal version:** 3.27.0

I had one other device lying around with Signal 3.25.3 and this happens on that build too.

### Link to debug log
https://gist.github.com/anonymous/9e1a93688339bacf8b16b1967c21afec

**Comment by 2-4601** [comment]
Also happens on 3.24.1

**Comment by McLoo** [comment]
Confirmed by Twitchy Fingers himself  😉
With 3.26.2

Also notice,  that the contact name vanishes if both RecipientPreferenceActivity get closed

**Comment by grantbey** [comment]
Same for me on 3.27.0 on a Pixel 7.1.1.

**Comment by jkdf2** [comment]
This happens in a lot of places. For example, go into Signal's notification settings and hit "Sound" twice rapidly. The sound selector will show up twice.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by alan-signal** [comment]
Still a reproducible issue.

**Comment by five-c-d** [comment]
When I try to reproduce this in 4.42.3 what I do is hammer about six taps in rapid succession onto the name of the contact in the titlebar of my 1-on-1 chat... as described above, I see two transition-animations of their avatar-pic opening up the activity twice.  However, after hitting the back-button a couple of times to return to the chat-history of the 1-on-1, sometimes -- not sure if it is always? -- 

the small circular avatar-picture in the titlebar is gone... there is a blank area with the background-color of the titlebar where the tiny-circular-avatar-pic used to be... as if hammering on it made it disappear  :-)   It stays gone, until you back up to the conversation-list, and then re-open the conversation-list item in question, as which point the titlebar once again has the avatar-pic in it as expected.

**Comment by alex-signal** [comment]
Unable to reproduce on `4.71.x`
