### ISSUE TITLE
Message input screen doesn't close after sending in horizontal mode

### ISSUE THREAD

**Issue by jtarvainen** [signalapp/Signal-Android#6070]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When the phone is in horizontal mode, the message input screen doesn't close after clicking the "Send Signal message" button.

### Steps to reproduce
- Open Signal
- Rotate the phone to horizontal mode
- Enter a chat
- Write a message and click "Send Signal message"

**Actual result:** The message is sent and disappears from the input screen, but the blank input screen doesn't close.
**Expected result:** The message input screen closes.

### Device info

**Device:** Google Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.26.2

### Link to debug log
https://gist.github.com/anonymous/a41de0512a78d17cd5ddb7f879654fc2

**Comment by 2-4601** [comment]
Not sure what's the expected behavior. If you are in portrait mode, the IME also does not get dismissed after tapping send.

**Comment by jtarvainen** [comment]
In portrait mode, there is no separate input screen, just the single-row 
input field at the bottom of the chat screen. Naturally, this field is 
always visible. However, in horizontal mode, the input screen, along with 
the keyboard, occupies the entire display, thus obscuring the chat view. 
After clicking "send", the (now empty) input screen should close and the 
chat view be displayed.

Regards
Jussi

**Comment by jtarvainen** [comment]
Is this being worked on? There have been a few updates since This should be an easy enough issue to address since it doesn't involve message transmission, just the UI. Please fix it!

**Comment by 2-4601** [comment]
Would you like to fix this? There are quite a many issues and the fastest way to get this fixed would probably be to contribute a PR.

**Comment by jtarvainen** [comment]
Unfortunately I don't have the necessary coding skills.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
