### ISSUE TITLE
Uninvited 'ghost' user appears in group chat....very weird issue

### ISSUE THREAD

**Issue by Japhys** [signalapp/Signal-Android#6071]
One of the group members reinstalled signal. After one of the other members updated the group, the main window of the reinstalled user showed a bunch a group users that were added to the group in question. There was one unfamiliar username (!!) added to the group! The name did not ring a bell to any of the other group members (and also not to the reinstalled user). Furthermore the other group members didn't get a message this user was added. Tried to update group several times. When clicking on the group members icon in the top right corner the name of the ghost member is not being listed not even in the app of the reinstalled user. This is very weird and kind of worrying. I do have screenshots but don't want to post them here for privacy reasons...obviously. I could send them privately if desired   

### Device info
**Device:** Nexus 6P
**Android version:** 7.0 (NBD91P)
**Signal version: 3.26.2

**Comment by sweeper3000** [comment]
Could this be because the contact the reinstalled Signal did not leave the group(s) he/she is a member of?

**Comment by Japhys** [comment]
I am not sure if he left the group, probably not. But the thing is he got notified of all members in the group when re-entering and one of the user names is not a group member, not one of his phone contacts, not a contact of any other group member, nor does anyone know anybody with that name. Nobody else got notified of this user entering or being a member of the group and the username is not being shown when clicking the members icon in the right top corner (the re-entered person doesn't have this user in the contact list either!).

**Comment by 2-4601** [comment]
The names of the contacts in Signal come from your Android device's contact app. If there is no name in your Android contacts, Signal will show just the number. So if there's an unfamiliar name in the group, there must also be an unfamiliar name in your system contacts :)

Also could you post a debug log? If you don't have any logs from when this happened, send a message to the group and then post a log (See section 4 https://support.whispersystems.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-)

**Comment by Japhys** [comment]
I know...but I am afraid it's not that simple. In that case ALL group user would have to see this number. And no one does. I double checked the phone of the person in question, he does not have a contact in his phone with this name, nor does anyone else :) I will asked him for a debug log

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
