### ISSUE TITLE
Option to disable/enable direct share feature

### ISSUE THREAD

**Issue by AykutCevik** [signalapp/Signal-Android#6073]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With the latest version of Signal you introduced direct share. There is no option to disable this functionality which I think is important.
Now I'm seeing all my chats in a share window which gets overloaded and slower in opening - and which reveals all my chats to any person next to me looking on it.

### Steps to reproduce
- Out of any app; click the share button
- See Signal chats appearing
- look for an option to disable this

**Actual result:** 
"Direct Share" setting is not available in settings activity.
**Expected result:** 
"Direct Share" setting is available in settings activity where it can be enabled/disabled.

### Device info
**Device:** Samsung Galaxy S6 Edge
**Android version:** 6.0.1
**Signal version:** 3.27.1

**Comment by 2-4601** [comment]
If you use a passphrase to lock Signal, direct share will not show any Signal conversations

**Comment by sigenc** [comment]
I'm against more Options too. But here i think AykutCevik is right. We need the possibility to disable that. 
Damn i know moxie is really not into putting more Options into Signal. But i think there are some usefull stuff. What about a hidden menu that you can only enter if you tap 5 times somewhere on the Screen or what ever. Like when you wan't to enter development Options in android?

**Comment by AykutCevik** [comment]
Using a workaround like setting a passphrase is not a solution for this case. We need this option since messengers like Telegram and Threema also have them and the user will not be overwhelmed with this option.

Signal already has a section with "advanced settings" where it could be placed e.g.

**Comment by nikwen** [comment]
I think this belongs into the privacy settings where we already have the anti-screenshot toggle. Afaik the Android N shortcuts PR will add a toggle for disabling the disclosure of chats to the launcher application and I think that this is the way to go here as well.

**Comment by nikwen** [comment]
There is a related Diskussion at https://github.com/WhisperSystems/Signal-Android/pull/6035.

**Comment by jeremymasters** [comment]
I think it'd be good to change the title on this issue.  Direct Share has already been added.  It looks like what you really want is "Add Ability to Limit Direct Share" or something like that.

**Comment by AykutCevik** [comment]
@jeremymasters You are right, I edited the title :)

**Comment by nikwen** [comment]
@AykutCevik Moxie voted against a similar toggle for the Android N shortcuts. Besides that, no progress.

**Comment by AykutCevik** [comment]
@nikwen thank you for your comment. I think this is a little bit different. Since Android N shortcuts are triggerd wittingly while long-pressing on the launcher icon, the direct share list is always showing up, no matter I want it or not, which require an option in my opinion.
Would be great to hear the arguments against this option so I can also relate :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
