### ISSUE TITLE
Wishlist: Group (video and voice) calls

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#6075]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### description
I would like to use group (video) calls as this is a great feature for different situations.
Are group (video) calls on the list, that will come at some future time?
As webrtc is in development at the moment, will this be a step in this direction or is it totally uncorelated.

(one-to-one video calls are in  #4497)

EDIT: to make it clear, I mean video AND voice group calls. (title changed)

**Comment by lukehutch** [comment]
+1. (And/or voice calls.) I have had to switch to Hangouts for some security-sensitive calls because Signal doesn't support more than two parties.

**Comment by nrizzio** [comment]
@lukehutch Please [do not bump issues](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues). If you want a feature, please use the reactions button to +1.

**Comment by mawed** [comment]
There was an statement by OWS:
It's on the roadmap. 
:+1:

https://mobile.twitter.com/whispersystems/status/911011419297947648?p=v

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
