### ISSUE TITLE
"Empty message" snackbar appears when clicking twice at the send button

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#6076]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I write a message and double tab on the send button twice, I get a snackbar with "ConversationActivity_message_is_empty_exclamation".

### Steps to reproduce
- Write a text
- click on send twice very fast

**Actual result:** message is sent and I get a snackbar with "ConversationActivity_message_is_empty_exclamation".
**Expected result:** message is sent and the attachment menu is opend

### Device info

**Device:** Oneplus X
**Android version:** 6.0.1
**Signal version:** 3.27.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
