### ISSUE TITLE
Group names keep disappearing (Unnamed group)

### ISSUE THREAD

**Issue by TurkeyMan** [signalapp/Signal-Android#6078]
### Bug description
When participants in groups get new phones (not me), we have to authorise their new key before they can post which is expected, but after that, my phone changes the group name to "Unnamed group" for all groups that user is included in. I can no longer distinguish between the groups in the active conversations list, since I now have many groups called "Unnamed group".

This may or may not be related to use of the desktop client... I use the desktop client about 90% of the time, and I find that I have to accept new keys on both the desktop and my phone client separately. The phone client seems to be 'primary' somehow, and I can only perform group management with the phone client.

### Steps to reproduce

Your test device is an Android device. Also attach a desktop client to your test device (may be unrelated, but is in my repro scenario)
Create a group with 3 occupants and name it something.
Have one of the OTHER users switch to a new phone (update their keys?).
On the desktop client: notice the keys have been updated, and accept the new key.
[In my experience now, at this time, the user who changed phone can no longer post to groups; they can't activate the text entry field]
Now authorise the new user again on the Android device.
[The user who changed phones can now post again]
Notice that the group name is now "Unknown group" on your Android device, but the group name is still correct on the desktop client.

**Expected result:** Group names are not lost. Also, I don't think I should have to authorise the key change on all my attached clients. Authorising the key change on any one of them should be enough and update my other alias clients.

### Device info

**Device:** OneplusOne
**Android version:** 7.1
**Signal version:** 3.27.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
