### ISSUE TITLE
"ENABLE SIGNAL FOR SMS" with contact who has signal installed

### ISSUE THREAD

**Issue by s0riak** [signalapp/Signal-Android#6079]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After experiencing #6061 I can't send any Signal message or make a Signal call to the contact, I was sending a file to which made Signal crash. Instead of the normal input for a message only a button "ENABLE SIGNAL FOR SMS" is shown, even though the contact still has signal installed an I can receive messages from the contact. The other contacts not involved in #6061 are working as usual.

### Steps to reproduce
- (Get the app/service in a weird state by executing the STR of #6061)
- Delete all data of the app
- Reinitialize the app
- Open the contact which caused the crash in #6061 

**Actual result:** A button "ENABLE SIGNAL FOR SMS" is shown instead of the normal input
**Expected result:** The input (input field, attachment selection, "send"-button) is shown.

### Screenshots
not available

### Device info
Device: Aquaris M5
Android version: 6.0.1
Signal version: 3.27.1

### Link to debug log
https://gist.github.com/2f554c3c1695534c7ba17ae76c3ad973 (can't see anything helping to understand why the contact is not recognized as a signal contact)

**Comment by rollermy** [comment]
I had to add a +1 before my friend's number. (try that or what ever the country code should be)

**Comment by s0riak** [comment]
Thanks for the replies. I tried to refresh the contacts right after the issue occured and it didn't have any effect. I tried it again (with unchanged contact number) some days ago and it worked again.
@2-4601 I'm unsure if one should close the issues as it would be best to check if the contact is on signal before displaying it is not. Which in my opinion not the root cause of the issue as the contact was in the contact list before.

**Comment by lekanwang** [comment]
I'm also experiencing this. A contact, who's number has not changed, and from whom I'm still receiving messages sent from Signal, now no longer appears in my Signal contacts, and I am not able to send messages to the contact. I tried adding a +1 to the phone number, and refreshing.

**Comment by s0riak** [comment]
The same contact disappeared again (showing "ENABLE SMS..."). Didn't change anything I would consider relevant. I followed the instructions in https://support.whispersystems.org/hc/en-us/articles/216595418-Where-are-my-Signal-contacts-How-can-I-see-the-names-of-my-Signal-contacts- which didn't help anything.

**Comment by jeremymasters** [comment]
@TestingEGWBQ23 you should get logs when this happens.

**Comment by TestingEGWBQ23** [comment]
@jeremymasters from one or both phones? What do I do with the logs?

**Comment by TestingEGWBQ23** [comment]
Any updates on this? Do the maintainers have any idea what is happening? Any workarounds or fixes to try? Thanks.

**Comment by jeremymasters** [comment]
@JoeTvx if this is happening to you, it would be great to have a log right after you notice it

**Comment by rettichschnidi** [comment]
This happened to me too!

Timeline
=======
- 2018-03-09, 17:42: Received first message from my communication partner (+**********80)
- 2018-03-09, 18:36: I answered, but message did not get received till the next morning (had just one tick)
- 2018-03-09, 19:58: Partner sent me another message. Received quickly by me. Partner did not yet receive the messages sent by me at 18:36.
- 2018-03-09, 20:00, 20:01, 21:17: Messages sent by me. Also not received by my partner till the next day around 7:50.
- 2018-03-10: Messaging seems to work okay-ish
- 2018-03-11, before 13:19: Messaging seems to work
- 2018-03-11, 13:19: Sent another message to my partner. Received by server, but not by partner (one tick).  (see screenshot from 14:03)
- 2018-03-11, 13:45: Message still not received. "ENABLE SIGNAL FOR SMS" appeared, I did not enable it. Could no longer write anything to my partner. (see screenshot)
- 2018-03-11, 13:46: Got a new message from my partner. My last message was still not received by him. (see screenshot)
- 2018-03-11, after 14:12: Partner tries to call my using the in-app functionality. All I get are "missed call" 
- 2018-03-11, 14:35: Call from my partner to me actually worked.
- 2018-03-11, somewhen later: "ENABLE SIGNAL FOR SMS" vanished.

Files
====
- [In-App Log](https://files.reto-schneider.ch/diesunddas/2018-03-12-signal-bug/2018-03-11_14-02-in-app-log.txt) - Logcat dumped, but not here for privacy reasons. If helpful, please let me know what to look for and I will upload the relevant parts.
- [Screenshot](https://files.reto-schneider.ch/diesunddas/2018-03-12-signal-bug/2018-03-11_14-03-screenshot-censored.png) from 14:03

If anything is missing, please let me know.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
