### ISSUE TITLE
Recovery of Deleted SMS Possible in Android

### ISSUE THREAD

**Issue by TheMachineWhisperer** [signalapp/Signal-Android#6091]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With physical access to the phone it is possible to recover the text of SMS messages deleted from the signal client in android. Not necessarily a bug but a flaw perhaps. 

### Background
I had a requirement to recover SMS sent in signal android which had been deleted, although I was not expecting to have any success I did actually manage to achieve it, at least partially. I ran a standard SQLite recovery on the messages.db from /data/data/org.thoughtcrime.securesms/databases using the tool provided by https://github.com/mdegrazia/SQLite-Deleted-Records-Parser.

This did require root to access the messages.db database but actually recovered quite a lot of data from the free and unallocated blocks, roughly 28 out of 31 texts I knew had been exchanged with the particular contact and deleted at least a week ago.

Obviously the "body" data of the entries in the sms table are encrypted or encoded, I haven't looked too deeply into how this is achieved and what keys are used etc. I should note that the android app on this particular phone is not passphrase protected.

The issue here is that whatever method is used to encode/encrypt the body text appears to be static, so having data recoverable means with access to the phone I was still able to read the messages by replaying them back into the database.

I used the DB Browser for SQLite from http://sqlitebrowser.org, edited the SMS table, duplicating a row for an existing message and then replacing the body string for that duplicated row with the one extracted from the recovered data. Copying the modified database back to the phone then allows the messages to be decrypted and read.

### Comments
I have not tested this with the signal database passphrase enabled and it obviously does require physical access to the unlocked phone.

Could one militate against this problem by removing the free/unallocated blocks through database maintenance, vacuum etc, and prevent injecting of old messages back into the database by regularly cycling whatever key is used to encrypt the body strings, re-encrypting the existing messages on-the-fly or perhaps even using a per-thread key.

### Steps to reproduce
- Root the phone
- Obtain the messages.db database, I used adb shell "cp /data/data/org.thoughtcrime.securesms/databases/messages.db /sdcard/
- Copy from local storage to PC.
- Run the  mdegrazia/SQLite-Deleted-Records-Parser on the database and export to a RAW file
- View the file and extract the strings for the desired contact numbers, it is fairly obvious where the strings begin and end.
- Open the messages.db in SQLite browser, modify the sms table, duplicate a row for the same contact then replace the 'body' string of the duplicated row with that extracted from the recovery data
- Save the changes and copy the modified messages.db back to the phone storage
- Copy the new database over the top of the existing one "cp /sdcard/messages.db /data/data/org.thoughtcrime.securesms/databases/
- Use application manager to kill Signal then re-launch.
- Open the thread for the desired contact, if the string was incomplete "Error decrypting message" is displayed, otherwise message text is displayed.

**Actual result:** Previously deleted messages are now visible on the phone, although timestamp information is lost.
**Expected result:** Messages not to be recoverable from free and unallocated blocks of the SQLite database. Should not be possible to replay encrypted body strings back into the database.

### Device info

**Device:** Sony Xperia Z3 Compact D5803
**Android version:** 6.0.1
**Signal version:** 3.27.1

**Comment by jasdaller** [comment]
You can use software to recover you data back. But do remember act fast over it and don't try writing something more over it otherwise the chances of getting your things back will decrease. The data recovery program to scan your phone and restore lost data from it.
Only a  few steps you can get back your lost data from your phone.

**Comment by thereproducter** [comment]
Nobody comments ? Holy shit !! Great job in finding this, shame that this ticket is open. Any idea if any changes have been made ?

**Comment by sigenc** [comment]
Hi there,

i don't see any problem here. This would not be possible if the app was passphrase locked. Only some metadata would be available.

**Comment by thereproducter** [comment]
You don't see a problem? If a LEO has your handset and JTAG or chip off it's available for review!! Tell me I'm wrong.

**Comment by sigenc** [comment]
Just use a password. For me the bigger problem, is the metadata that is available when using a pass. They can extract the id, Sender id and time

**Comment by pgerber** [comment]
I agree that being able to read messages from the DB, if there is no passphrase, is to be expected. If that wasn't the case, there would be no need for a passphrase in the first place.

However, in my opinion, making it harder to recover deleted messages, from encrypted and unencrypted, databases does make sense. At least as long as this can be done cleanly and in a timely manner.  Perhaps the [secure delete](https://sqlite.org/pragma.html#pragma_secure_delete) functionality offered by Sqlite could be used. I'm well aware that this doesn't guarantee that the data is actually overwritten on the storage but it would certainly make it harder to recover any deleted messages.

**Comment by moxie0** [comment]
Please do not use the issue tracker for discussion. If you would like to discuss something, please visit the forums.
