### ISSUE TITLE
Calendrical fast scrolling for conversation view

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#6095]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With the introduction of (sticky) date headers, it would make sense to add fast scrolling to the conversation view (like the alphabetical fast scrolling in Signal's contact list, but with dates instead of alphabetical characters).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
