### ISSUE TITLE
Adhere to Material Design grid specs

### ISSUE THREAD

**Issue by rejhgadellaa** [signalapp/Signal-Android#6114]
Hi,

I'm new to Signal, love how easy it is to use, but I did find a few (Material Design) related issues that cause twitching of the eyes and other OCD-y things. Pretty much all of it has to do with alignment of elements, spacing between them, etc.

I realize that I may sound like I'm an a**hole but a) english it not my native tongue so finding the right words is sometimes difficult and b) I actually care and think these issues shouldn't be too hard to fix and it really does make sense to adhere to Android's design specs, if only for consistency between apps.

Anyway, on to the issues at hand.

I used the app Keyline Pushing (available in Play Store) to overlay Material Design grids and, from the looks of it, I think Signal uses a metric grid system (10) instead of 8x8.

See this page for basic Material Design metrics and keylines:
https://material.io/guidelines/layout/metrics-keylines.html

### Conversations overview 

* The app title (in the action-/appbar) should be at 72px from left edge (weirdly, in other screens it is)
* Horizontal spacing from edge to content is not 16px (or 24px on tablets)
* Avatars are not 40x40
* I'm guessing the list items are not 72px in height either

Here are the specs for lists:
https://material.io/guidelines/components/lists.html#lists-actions

Here is a screenshot with keylines + grid overlay and a rough sketch of how it should be layed out.

![sig-conv-list](https://cloud.githubusercontent.com/assets/4703109/22379933/c3f8edf4-e4bb-11e6-98ef-ad8bab7bd727.jpg)

### Settings

The issues here are not super obvious until you draw a line from the title (in the action-/appbar) down and notice that the items in the content area don't match up with it. This is also covered under the MD > Components > Lists section:
https://material.io/guidelines/components/lists.html#lists-actions

![sig-sett](https://cloud.githubusercontent.com/assets/4703109/22380321/5e34489a-e4bd-11e6-807f-12109ad44fe4.png)

### Conversation

I'm guessing that the chat 'bubbles' and avatar have to be looked at but my biggest gripe is the text input box at the bottom. Nothing seems to line up properly:

![sig-message-box](https://cloud.githubusercontent.com/assets/4703109/22380078/5c8940c8-e4bc-11e6-8104-4101fea09a1b.jpg)

Also, the "Send Signal Message" placeholder text's vertical alignment is way off. This is probably an easy fix; just make it the same size as the normal text (when a user inputs something) because it's a different size and does line up.

### Device info

**Device:** Motorola Moto X 2nd gen (2014)
**Android version:** 6.0.0
**Signal version:** 3.27.1

**Comment by rejhgadellaa** [comment]
PS: I'm happy to help make some mockups and maybe even build some layouts in Android Studio if that helps. Also open to discussion and such :D

**Comment by 2-4601** [comment]
Related to the last point #4903

**Comment by moxie0** [comment]
@rejhgadellaa Making the changes to the layouts in a PR would definitely be helpful. I'd prefer one PR per activity section, rather than a single PR which covers everything.

**Comment by rejhgadellaa** [comment]
@moxie0 ok just checked out the project and going through the layout files now. I'm getting a bunch of render errors from the layout previewer in Android Studio so I hope I'll be able to solve those or this is going to be a tedious job :P Can you point me in the right direction by any chance?

Here's an example: (conversation_activity.xml)

> The following classes could not be instantiated:
> - org.thoughtcrime.securesms.components.camera.QuickAttachmentDrawer (Open Class, Show Exception, Clear Cache)
> - org.thoughtcrime.securesms.components.SendButton (Open Class, Show Exception, Clear Cache)
> - org.thoughtcrime.securesms.components.camera.CameraView (Open Class, Show Exception, Clear Cache)

**Comment by rejhgadellaa** [comment]
Making some progress here but I'm starting to see that I'm not familiar with all the elements in the layouts, especially the ones that aren't visible all the time. 

For example, I have a `org.thoughtcrime.securesms.components.AlertView` element with id `indicators_parent` that I had to resize but since it's just an empty box in the preview I have no clue what issues I may cause by doing this. Are there any design docs, mockups, etc available for Signal?

I'm just trying out some stuff for now so it's not immediately a problem but by the time I really start doing the serious work it would be nice to have some reference/docs so my PR's will actually be worth something and not just a waste of your and my time :)

**Comment by rejhgadellaa** [comment]
Just a small update. Like I said earlier, I've been playing with the layouts a bit. Here is what I've been able to do so far..

### Conversation list

(Before and after)

![signal-wip](https://cloud.githubusercontent.com/assets/4703109/22399804/a3620acc-e5a5-11e6-820d-1f0f8e13ab9d.jpg)

### Conversation

(Don't have the 'before')

![screenshot_20170128-215944-blur](https://cloud.githubusercontent.com/assets/4703109/22399805/a96c94b4-e5a5-11e6-9d4e-49d618360c2d.png)

There are plenty of issues and questions I have, I'll come back to that tomorrow..

**Comment by rejhgadellaa** [comment]
The preference activity has 8dp spacing on the left and right of the list and I can't figure out what causes it (or how to solve it)

I've not been able to find a [style](https://github.com/WhisperSystems/Signal-Android/blob/master/res/values/styles.xml) or [theme](https://github.com/WhisperSystems/Signal-Android/blob/master/res/values/themes.xml) rule that causes it and from what I found it doesn't wrap the preference list in a layout.

I also tried debugging the layout using Hierarchy Viewer in Android Studio but since I haven't really used that before I'm not sure where to look. I was able to confirm that the items do have the spacing but I'm not sure if it's margin or padding and which element might have that.

Does anybody have a clue?

![screenshot_20170129-110107-8dp](https://cloud.githubusercontent.com/assets/4703109/22403364/fe96164e-e614-11e6-8938-a82faeaa7ae5.jpg)

**Comment by Lokesh-Krishna** [comment]
Very impressed with all the work you're doing here.
Since you already are looking into the UI, could you see if #6008 can be incorporated into your work because it would directly impact what you're doing. Wouldn't it be better if it were taken into account from the beginning instead of necessitating changes later?

**Comment by Cormak** [comment]
This is definitely an improvement. Since I started using Signal recently, I noticed there was something "off" about the layout and I'm glad others picked up on this.

**Comment by rejhgadellaa** [comment]
@Lokesh-Krishna I think that I would break things if I would just remove then from the UI. But I did make them a little bit smaller (32px i stead of 40). Anyway, I think I'd rather have it as an option and just hide the avatar through code (on creation)..? But I can take something like that into account

**Comment by Lokesh-Krishna** [comment]
[QKSMS](https://github.com/moezbhatti/qksms) (an open source SMS app) does give you the option to enable or disable the conversation avatars so maybe its repository could be of some help to you? 

However Signal likes to keep options to a minimum so it would be a better idea to decide whether it should continue to exist or not and go all in with one of them. If they have to stay then making them smaller is a good idea.

**Comment by Cormak** [comment]
Please keep options to a minimum and just have 100% adherence to the latest Material Design standards. I don't think there's any room for customization here. We should be 100% objective about this. Anybody who doesn't like it can criticize Google.

**Comment by rejhgadellaa** [comment]
@Cormak hmm MD spec doesn't really say anything about having avatars in chat conversations so it's something "we" have to decide for ourselves. I prefer to have them (but bundled like Hangouts and others do). I do think that having the avatar AND (in group chats) a name with EVERY message is overdoing it and a waste of space. But that is for another issue :)

**Comment by Cormak** [comment]
@rejhgadellaa Yes, well if MD doesn't say anything then obviously it will be up to our decision as to what is best for Signal and I think you're right, wasting space with overuse of avatars ruins information density and looks bad. Avatars should be kept to a minimum and Hangouts is indeed a good model.

**Comment by Lokesh-Krishna** [comment]
> But that is for another issue :)  
Which would be #964 :P But the problem seems to be that bundling message bubbles the way Hangouts does would require changes to the database which would take a lot of time to implement.

I think that doing away with the avatars in at least individual conversations, where they serve no purpose at all and are overkill in the current quantity is a practical and immediately implementable solution.

**Comment by moxie0** [comment]
Thanks everyone, but please resist the urge to comment on design aspects unrelated to this immediate issue.

**Comment by Lokesh-Krishna** [comment]
I'm sorry. I didn't mean to distract from the issue at hand but I do think that is one decision that does impact what is being done here.
It would be nice to have your opinion on this matter, either here or on #6008 regarding this.

**Comment by Lokesh-Krishna** [comment]
@rejhgadellaa Could it be possible to look into the new export/import cards' vertical alignment and the Signal icon on the action bar as well?

What do the Material Design guidelines say about app icons on the action bar? Not all apps seem to have an icon in their action bar.

**Comment by moxie0** [comment]
@rejhgadellaa I think it'd be great if we could get started looking at a PR for any of the components you've done so far.

**Comment by rejhgadellaa** [comment]
@moxie0 Sry for not returning to this issue for some time. I did some experimenting back when I started this issue but made some beginners mistakes when it comes to git. Short story: I have to redo all of my work. The good news is that I have some rough idea of that needs to happen. I'll start working on it this week and see if I can get one or two activities finished by the end of it.

**Comment by rejhgadellaa** [comment]
@moxie0 so I started working on the conversation list, I think I have it ready for a PR. But then I read your comment on #6562 regarding the size of the avatars.. so I guess you're not going to do the PR I'm about to do :( 

I would like to make the argument that following the guidelines has some benefits, like the title in the appbar lining up with the text in the conversation list. It may not show in the main conversation list (because the Signal title is not in the right place, I'll have a look at that in due time :)) but if you have a look at archived conversations you should see what I mean. The title sits at 72dp from the left, as does the text in the conversation_list_item.

So my point is consistency. Not just with the rest of the OS and some major apps, also between elements in the app. It's just a LOT nicer to look at things when they line up. Following the guidelines makes sure that all of it does.

**Comment by rejhgadellaa** [comment]
First PR is ready, tackles the conversation list: #6672. It's my first contrib here so hope it's okay :)

**Comment by rejhgadellaa** [comment]
@Lokesh-Krishna yep I did look at those (import/export and app-/toolbar icons). I'll see what I can do :)

**Comment by rejhgadellaa** [comment]
Just a quick Q: is there any way I can test Signal on an emulator? Because it doesn't have a sim so I can't get past the registration... I'm pushing the app to my daily driver now and it's kind of a hassle.

**Comment by rejhgadellaa** [comment]
Just two quick screenshots of what I've done so far.

The PR for the conversation list is available.

For the conversation item sent/received:
- Smaller avatar (32dp)
- New 9 patch (background graphic) for chat bubble. I had to ditch the shadow so it doesn't include whitespace in the 9 patch itself, not sure if this is desired.. I could add it back in.
- Tweaked all the margins and paddings to fit in 8x8 grid
- Moved name of person to bottom of bubble and aligned it with the status text inside the bubble. I think it looks nicer this way because it's closer to the avatar.

Conversation input:
- Pushed everything into a 8x8dp grid.
![screenshot_20170525-100837](https://cloud.githubusercontent.com/assets/4703109/26442152/97279a44-4133-11e7-9d78-28d5aac4e174.png)
![screenshot_20170525-100829](https://cloud.githubusercontent.com/assets/4703109/26442153/972c8b9e-4133-11e7-937b-fe1c75e0acf7.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
