### ISSUE TITLE
Call fails, white band / blank screen and can't receive phone calls afterwards

### ISSUE THREAD

**Issue by peperunas** [signalapp/Signal-Android#6116]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Once a call is hung up, the callee and the caller can't phone through Signal again. If a call is attempted a screen with a white strip on the bottom appears and nothing happens afterwards. The phone then is unable to receive "standard" calls.

### Steps to reproduce
- Alice calls Bob
- Bob accepts the call
- Bob hung up the phone

**Actual result:** 
- Alice can't phone through Signal and can't receive phone calls (white strip screen)
- If Bob tries to call Alice, Bob has no signs of the bug happening: the call doesn't succeed though.

**Expected result:**
Alice and Bob can call each other without issues.

### Screenshots
![photo_2017-01-28_18-23-55](https://cloud.githubusercontent.com/assets/6033387/22398357/fab5e59c-e586-11e6-9f8f-bc2bb12da908.jpg)

### Alice Device info
**Device:** Oneplus 3T
**Android version:** 7.0
**Signal version:** 3.27.1

### Bob Device info
**Device:** Xiaomi Mi5
**Android version:** 7.1.1
**Signal version:** 3.27.1

### Link to debug log
Alice debug log: [here](https://gist.github.com/anonymous/ba304549d3a29daf35a724f21bef3a25)
Bob debug log: [here](https://gist.github.com/94c2fdfa86c80271fe46cbe97c7523c5)

Similar issue in #5132

**Comment by 2-4601** [comment]
Thanks for the detailed report. You mention #5132 as similar issue. Is there something specific in this case that differs from #5132 or could they be duplicates?

In any case, the upcoming webrtc change hopefully handles this and similar Redphone related issues.

**Comment by peperunas** [comment]
@2-4601 Signal drains battery due to RedPhone and you can't receive "standard" calls afterwards.

**Comment by 2-4601** [comment]
Last part related to #4703.

**Comment by peperunas** [comment]
Yes. I've uninstalled Signal right now since I couldn't receive phone calls. It's a serious bug which prevents me (and my friends) from using Signal right now.

**Comment by naftulikay** [comment]
I am affected by this as well. 

My debug info is [here](https://gist.github.com/anonymous/e5b6ba74c5c29c2218775d1d3f5f05b3). I'm on a Pixel running the absolute latest Signal and latest Android and this bug has been present for for a while now. My exact problem is that I can receive/place one call on Signal, and then all future calls yield me a blank screen very similar to the one above.

The only workaround that I have is to force kill Signal, which is extremely annoying.

**Comment by peperunas** [comment]
I confirm everything @naftulikay said.

**Comment by motatuc** [comment]
I suffer the same problem with Signal 3.28.1 on Android 7.1.1 Could be Android version related.

**Comment by illyas3** [comment]
Same issue, device Xiaomi MI5 running LineageOS and Signal 3.27.1. Started happening today.

**Comment by moxie0** [comment]
Sorry about this Android N problem. If you're on the beta channel, you could try out the calling stack that will be replacing this soon by toggling Settings -> Advanced -> Video calling beta in the 3.29.0 release.  

I'm guessing this might resolve things for you all, although it will only work with contacts who are also running the beta and have enabled this setting (for now).

**Comment by naftulikay** [comment]
@moxie0 an updated debug log showing the exception: https://gist.github.com/anonymous/3e240580452a372d4a0750221de02c16

**Comment by peperunas** [comment]
@moxie0, the bug is still happening. A can call B how many times he/she desires but B can't call back. B screen's stuck in "Composing...".
Now:
The call quality is very low though: we experienced massive lag and voice loss. We also tried the videochat: we could see each other but the audio was screeching all the time. I think these issues have to be filed in another thread though.

**Comment by friend7** [comment]
@moxie0:
have same problem, only nexus 5x restart helps.

Also i notice it works when calling users which use Video calling beta.. So it is problem with "classic" old call system.

**Comment by riyapenn** [comment]
User states this is not resolved with new calling. Log: https://gist.github.com/e4016150440c437287f6a6a6e847708c

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
