### ISSUE TITLE
Group vanishes, changes to weird number and is an MMS contact after that... reappers after sending message via Desktop, but history on phone is empty

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#6117]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Ok this is a strange one. Last week I was traveling from Austria to Munich via Bus. They have WiFi on board which is fed by LTE Routers. I was sending some messages to a Group with 3 members while beeing on that WiFi. 

### Steps to reproduce
- never happened before. never happened again. 
- wasn't able to reproduce this. sorry

**Actual result:** Suddenly the popup appears that the contact is not running Signal anymore. And therefore the message will be downgraded to MMS. Noteworthy that it says "**the** contact". And not "**one** of your contacts". I would suspect this phrasing more in a direct one-to-one conversation. Not in group. 
After dismissing the warning popup and not resending the message, the group name changed to this weird number. 
+84785552757794605149254 
+84 is Vietnam. I wasn't able to find anything related to it. Also it doesn't seem like any of my phone numbers or even parts of it are related to this one. 

So my group vanished and was replaced with this weird new contact. I did not send any new messages. 
Later that day when I got home, I tried sending something via Desktop which worked without any problems. Surprisingly on my phone my previously vanished group reappears, but with an empty message history. 
**Expected result:** none of that above ;)

### Screenshots

![01](https://cloud.githubusercontent.com/assets/18451020/22403204/456b422c-e608-11e6-8a22-c6155c39153d.png)
![02](https://cloud.githubusercontent.com/assets/18451020/22403205/4b028704-e608-11e6-9431-9fa2c34e960d.png)
![03](https://cloud.githubusercontent.com/assets/18451020/22403209/5317c648-e608-11e6-8682-6932dcba9583.png)
![04](https://cloud.githubusercontent.com/assets/18451020/22403210/5626fd4a-e608-11e6-8a7f-cffb059211e0.png)

### Device info

See Debug Log

### Link to debug log

https://gist.github.com/anonymous/cbad753736e389b2dd529e5605085f63

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
