### ISSUE TITLE
Duplicate date header

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#6120]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Duplicate date header when receiving messages from different days in the past on the same day, see screenshot.

_Edit: I noticed that this is a duplicate of #6101, but which has been closed. cc @haffenloher_

### Steps to reproduce
- Turn off device A
- Day 1: send message from device B to A
- Day 2: send message from device B to A
- Day 3: turn on device A to receive messages

**Actual result:** Duplicate date header shown, shows received date
**Expected result:** I had expected it to show the sent date

### Screenshots
![signal](https://cloud.githubusercontent.com/assets/3845150/22440355/6dd557da-e733-11e6-92d3-8e4952113ef3.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
