### ISSUE TITLE
Received message shown as not sent

### ISSUE THREAD

**Issue by Zeriuno** [signalapp/Signal-Android#6127]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A Signal message sent to me is now shown as a message that Signal wasn't able to deliver.

### Steps to reproduce
Not sure it can be reproduced, it might depend on the network conditions: this happened while my phone card was in roaming, Signal was able to send and receive encrypted messages, but SMS weren't going through.
- Sent several SMS (three)
- SMS were not listed as sent, but as in progress (i.e. moving dots)
- ongoing Signal conversation
- Simultaneously, the SMS status changed to "sent", while one of the messages I received in the Signal conversation changed to "not delivered"
- I can't find out if the SMS were really sent and delivered as shown.

**Actual result:** The very same message in the conversation changed background color (it was the contact's one, now it is white); has a red warning side next to it; "not delivered" is written at the bottom of the message, next to the padlock. If I click to get more informations about it, I have the option to resend the message.

**Expected result:** SMS status switched to "sent" or "not sent", accordingly.

### Device info
**Device:** Alcatel One Touch 997D
**Android version:** 4.1.1
**Signal version:** 3.27.1

### Link to debug log
The bug appeared two days ago and I didn't think to capture the debug log right away.

**Comment by Zeriuno** [comment]
I have to add on what already reported:
* I have updated to 3.28.3
* no SMS is being sent, at all (system default app still does though)

I do not know if the SMS not being sent is related to the Signal message bug or not.
Here my debug log: https://gist.github.com/anonymous/866143e50c3061f7b2929de27301930c

**Comment by 2-4601** [comment]
Sounds a lot like #5287

**Comment by Zeriuno** [comment]
Yes, indeed. So probably the Signal message appearing as undelivered outgoing message isn't related to Signal being unable to send SMS?

**Comment by 2-4601** [comment]
I have no idea :)
But let's close this as duplicate

**Comment by Zeriuno** [comment]
So I would open a new issue for the SMS not being sent and reference that one in the duplicate issue telling that the two have been observed together. What do you think of that?

**Comment by 2-4601** [comment]
So if I have understood these issues correctly:

- in #5287 an incoming SMS was changed to an outgoing (and undelivered) SMS
- in #5524 an incoming SMS was changed to an outgoing (and undelivered) Signal message
- in this issue an incoming Signal message was changed to an outgoing (and undelivered) Signal message

Probably same cause in all of them but who knows, I guess we can track them separately.

**Comment by Zeriuno** [comment]
Issues correctly summed up, for as far as I am concerned, only:

* in this one (#6127) the incoming Signal message was changed to an outgoing and undelivered Signal message **while** Signal was trying and failing to send several SMS (and as of now Signal still can't send SMS on my phone).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
