### ISSUE TITLE
Crash after sending image

### ISSUE THREAD

**Issue by t3io** [signalapp/Signal-Android#6129]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal crashed while sending an image attachment. When I reopened the app I realised that the attachment had been sent successfully. 

### Steps to reproduce
Not sure this is reproducible. All I did was attach an image from the preview gallery that appears on top of new messages when tapping the "attach" blue icon. I then added some text in the message by typing, and hit the blue "send" icon. 

**Actual result:** app crashed
**Expected result:** app does not crash

### Device info

**Device**: Samsung Galaxy S5 neo
**Android version**: 6.0.1
**Signal version:** 3.27.1

### Link to debug log
https://gist.github.com/anonymous/b109688bb07670b8f4bdb956ea06ead6

**Comment by Trolldemorted** [comment]
well, does it crash if you send the same image again?

**Comment by t3io** [comment]
No, it did not. The reason I said I don't expect it to be reproducible is that I send images all the time with this exact setup and never have issues.

**Comment by moxie0** [comment]
hmm, out of memory error. was this image super large, panoramic, or anything like that?

**Comment by t3io** [comment]
No :-(

This image is as standard as it gets, captured via this phone's camera app with my usual (default) settings. No fanciness. Just checked image properties, original is 6.8MB, bog standard for this phone.

**Comment by moxie0** [comment]
@t3io Thanks, could you also check the original image dimensions?

**Comment by t3io** [comment]
Resolution: 4608 X 3456
