### ISSUE TITLE
Wrong date header "Today", preceeding "Yesterday"

### ISSUE THREAD

**Issue by Zeriuno** [signalapp/Signal-Android#6131]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Scrolling a Signal conversation, I get, from bottom to top, the following date headers: Today, Yesterday, Today (it was actually yesterday), Yesterday, (then goes on as expected).

### Steps to reproduce
Do not know the repro steps.
What I can say is that the Signal message was sent from a GMT 0 location to a GMT +1.
Message details are as follows:

- Sent jan 31, 2017 0001:50 CET
- Received jan 30 , 2017 23:55:09 CET

The following (mine) was sent at jan 30, 2017, 23:59:29 CET

**Actual result:** See screenshot
**Expected result:** From bottom to top, these date header should be displayed: Today, Yesterday, Sunday…

### Screenshots

![192 168 1 65](https://cloud.githubusercontent.com/assets/1645004/22475062/1e5db084-e7de-11e6-8757-f508a98ee137.png)

### Device info
**Device:** Alcatel OneTouch 997D
**Android version:** 4.1.1
**Signal version:** 3.28.3

### Link to debug log
Debug log doesn't show relevat informations.

**Comment by 2-4601** [comment]
#6101, #6120

**Comment by Zeriuno** [comment]
Thanks for those cross-references @2-4601, didn't see those when searching!

It looks to me though, like this one is another problem than those.

And considering what @moxie0 wrote:

> How did you generate these screenshots? Keep in mind that the headers are generated by the message "receive" time rather than the "send" time.

It seems to me that the middle message, "Today" ("Oggi" in the screenshot) isn't following the rule: it was received on 2017-01-30, yet the date header is using 2017-01-31 (when it was sent, yes, it was sent **after** being delivered).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
