### ISSUE TITLE
Disable video support on ancient devices without enough VRAM

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#6139]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
No established (video) beta call when calling each other.
Once tried with video button active(Case 1). Once tried with video button inactive (case 2).

### Steps to reproduce (Case 1)
- Call from device 1 to 2 with video button active
- accept call on device 2 and activate video button
- no call is established but I still get a notification the call is waiting to be established

### Steps to reproduce (Case 2)
- call from devide 2 to 1 with video button inactive
- accapt call on device 1 with video button inactive
- no call established even if there is a sound.

### Device info
**Device 1:** HTC Desire HD
**Android version:** 4.2.1
**Signal version:** 3.29.1

**Device 2:** FP 1
**Android version:** 4.2.2
**Signal version:** 3.29.1

### Link to debug log
device 1 
https://gist.github.com/970d1d14ca230810492e0ddb8a023bf2
device 2
https://gist.github.com/a47cead94293bf077935e3800c92dabf

EDIT: Device 1 has no self-portrait camera, could this be a problem? Moxie stated here, the other camera is not yet supported (https://whispersystems.discoursehosting.net/t/voice-video-beta/760/3)

**Comment by moxie0** [comment]
@mawed Are these logs from case 1 or case 2?

**Comment by mawed** [comment]
@moxie0 
Ddebug from device 1 should contain both.
Ddebug from device 2 should contain at least the second case as I took on debug log after the first try and I'm not sure if the old data gets deleted then? (Debug 1 for device 2; https://gist.github.com/c58ac84bbe4524c126449fedd518cf5b)

Today I got one call where voice only worked for 1-2 seconds... The only and longest on till now.

**Comment by moxie0** [comment]
@mawed I think device 1 is the problem:

```
W/Adreno200-ES20( 3349): <map_texture_attachment:1236>: GL_OUT_OF_MEMORY
D/dalvikvm( 3349): WAIT_FOR_CONCURRENT_GC blocked 390ms
I/org.webrtc.Logging( 3349): EglRenderer: Dropping frame - No surface
I/org.webrtc.Logging( 3349): EglRenderer: Dropping frame - No surface
W/System.err( 3349): java.lang.RuntimeException: java.lang.RuntimeException: glBindFramebuffer: GLES20 error: 1285
```

For some reason it doesn't have enough memory for a 1x1 GL texture.

**Comment by mawed** [comment]
@moxie0 this could be the problem.
The device is really old (from 2010) and I just use it as workaround to sync messages from my device to signal desktop as I really enjoy this feature.

If I can help with this device somehow to test really old and weak devices, just tell me.
As I do not know anyone else in beta I can't check to try the beta calling with my main device.

**Comment by moxie0** [comment]
@mawed Could you do me a favor and try this APK between these two devices:
https://mega.nz/#!YtVUwACL!1sIjpZAsmYAnn8nN0wGvIAVURzUZpcmW7hi9QPEZG5I 

It's a little webrtc test APK, not related to Signal, so you can install it alongside.

**Comment by mawed** [comment]
@moxie0 device 1 cancels the call without any information.

**Comment by moxie0** [comment]
@mawed Thanks any way you can post the output of adb logcat from device 1 with this test apk?

**Comment by mawed** [comment]
@moxie0 I will try, never did this, but already downloading Android Studio.

**Comment by piratenpanda** [comment]
@mawed there are also apps like matlog to make this easier

**Comment by mawed** [comment]
@piratenpanda thanks for the hint

@moxie0 
[log.txt](https://github.com/WhisperSystems/Signal-Android/files/750157/log.txt)

**Comment by moxie0** [comment]
@mawed Thanks for this, looks like this device just doesn't have the vram to support video:

```
02-03 11:06:13.801 W/System.err(9540): Caused by: java.lang.RuntimeException: glBindFramebuffer: GLES20 error: 1285
02-03 11:06:13.811 W/System.err(9540): 	at org.webrtc.GlUtil.checkNoGLES2Error(GlUtil.java:29)
02-03 11:06:13.811 W/System.err(9540): 	at org.webrtc.YuvConverter.convert(YuvConverter.java:191)
02-03 11:06:13.811 I/CameraStatistics(9540): CameraStatistics: Camera fps: 7.
02-03 11:06:13.811 W/System.err(9540): 	at org.webrtc.SurfaceTextureHelper$7.run(SurfaceTextureHelper.java:234)
02-03 11:06:13.811 W/System.err(9540): 	at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:208)
02-03 11:06:13.811 W/System.err(9540): 	at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:205)
02-03 11:06:13.821 W/System.err(9540): 	at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:182)
02-03 11:06:13.821 W/System.err(9540): 	at android.os.Handler.handleCallback(Handler.java:725)
02-03 11:06:13.821 W/System.err(9540): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-03 11:06:13.821 W/System.err(9540): 	at android.os.Looper.loop(Looper.java:137)
02-03 11:06:13.821 W/System.err(9540): 	at android.os.HandlerThread.run(HandlerThread.java:60)
02-03 11:06:13.821 E/rtc     (9540): 
```

It'd be great if I could detect that and disable it, but that doesn't look straightforward.

**Comment by mawed** [comment]
@moxie0
Maybe at least inform the user about the reason of the error/not working (video) call? This would decrease the frustration of the user.

**Comment by moxie0** [comment]
As it stands, this condition is undetectable. I'd like to be able to disable just the video functionality, inform the user, etc, but at the moment I can't see how.

**Comment by mawed** [comment]
I tried again and now the video connection from device 2 to 1 worked without a crash.
(when calling in this "direction"). When calling from device 1 not even the voice call alone worked.
But when the app crashes, it still shows a notification in the notification bar, even the call has been aborted.
On device 2 the call is not even ended.

Is it possible to detect a crash and "stop" the call on device 2 and delete the notification on device 1 about an outgoing call?

**Comment by moxie0** [comment]
@mawed No I can't do anything here, the crash and everything about it is outside of my control. The only hope I have is to somehow be able to detect devices which aren't video capable before anything goes wrong, but it doesn't look like that's very possible.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
