### ISSUE TITLE
Tablets not supported

### ISSUE THREAD

**Issue by jonasvp** [signalapp/Signal-Android#614]
I tried installing from the [Play store](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en) but it says "not compatible with your device". My Nexus 7 (with 3G) can send and receive SMS. Any way to install TextSecure anyway?

**Comment by hadiasghari** [comment]
Hi, is there any update on this? I am trying to install it on my Samsung Galaxy Tab that is running official Android firmware and has SIM card support. 
I would suggest that it is not blocked on such devices.

**Comment by ph0o** [comment]
+1, we need an alternative for threema pls!!

**Comment by foss-** [comment]
+1 no news on this?

**Comment by Mangoes** [comment]
+1
Samsung Galaxy Tab 3 10.1 Wifi (Intel cpu) and it says Signal is not compatible with this device.

Telegram, WhatsApp, Viber, hangouts, Linphone, etc... they all work fine.

So, what's the problem with Signal?

Thanks.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
