### ISSUE TITLE
Video call stops showing own camera after pressing home button (Android 4.2)

### ISSUE THREAD

**Issue by haffenloher** [signalapp/Signal-Android#6144]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Steps to reproduce
- start a video call
- have both (!) parties enable video (necessary to trigger the bug)
- press home button
- return to Signal through notification or app switcher

**Actual result:** Camera still works (image is received on the other end), but the little preview of one's own image is gone and cannot be brought back by switching the camera off and on.
**Expected result:** Own camera preview is still there.

### Device info

**Device:** Fairphone 1
**Android version:** 4.2.2
**Signal version:** 3.29.1

**Note:** This was *not* reproducible using an API 25 emulator. Do any other Android 4 users see this?

### Link to debug log
https://gist.github.com/anonymous/1a0a12af7ed33210d76013ebfd4299f9

**Comment by moxie0** [comment]
hopefully that should do it!

**Comment by haffenloher** [comment]
Still seeing this. New log: https://gist.github.com/anonymous/3d16b9f3452271d86be84316e417dde6

**Comment by 2-4601** [comment]
Also reproducable on Android 4.0.4
https://gist.github.com/bc93847979767914688375758dcb0d8d

**Comment by Shenkaa** [comment]
I've tried it on an Android 4.4.4 device with Signal 3.29.2 and couldn't reproduce this problem.

**Comment by haffenloher** [comment]
I think this got closed by mistake, this is still happening with 3.29.3 / Android 4.2.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
