### ISSUE TITLE
Exporting pictures crashes after a part of the images

### ISSUE THREAD

**Issue by white-gecko** [signalapp/Signal-Android#6145]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The export of pictures crashes after some images.

### Steps to reproduce
(this only happens on some threads, with many pictures)
- Go to a thread
- Open the menu
- select "all pictures"
- click on the top right icon with two floppies
- select "yes"

**Actual result:** I get an error message, that something went wrong with storring the images on the device, when I look into the "Pictures" folder I find only a part of the pictures (starting from the most recent picture)
**Expected result:** I would expect to have all images of that thread exported

### Device info
**Device:** Motorola Moto G 4G
**Android version:** 5.1
**Signal version:** 3.28.4
Not rooted

### Link to debug log
I have retrieved the following log with `adb logcat "*:W"`

```
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483900240733/973, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483900230648/972, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483900228221/971, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483900226371/970, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483898059694/969, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483825464885/965, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483825464458/964, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483700960574/962, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483642963362/956, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483465329294/951, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483300184953/948, progress 0
W/ThumbnailView(15833): loading part with id content://org.thoughtcrime.securesms/part/1483233749695/947, progress 0
W/SaveAttachmentTask(15833): mkdirs() returned false, attempting to continue
W/InputMethodManagerService(  873): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@223bbc01 attribute=null, token = android.os.BinderProxy@3dc6a7a5
W/SaveAttachmentTask(15833): mkdirs() returned false, attempting to continue
    (The above line was repeated 36×)
W/AttachmentDatabase(15833): java.io.FileNotFoundException: /data/data/org.thoughtcrime.securesms/app_parts/part-1895628768.mms: open failed: ENOENT (No such file or directory)
W/AttachmentDatabase(15833): 	at libcore.io.IoBridge.open(IoBridge.java:456)
W/AttachmentDatabase(15833): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.crypto.DecryptingPartInputStream.<init>(DecryptingPartInputStream.java:62)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getDataStream(AttachmentDatabase.java:365)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getAttachmentStream(AttachmentDatabase.java:119)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:49)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:86)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:71)
W/AttachmentDatabase(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:27)
W/AttachmentDatabase(15833): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/AttachmentDatabase(15833): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/AttachmentDatabase(15833): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/AttachmentDatabase(15833): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/AttachmentDatabase(15833): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/AttachmentDatabase(15833): 	at java.lang.Thread.run(Thread.java:818)
W/AttachmentDatabase(15833): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/AttachmentDatabase(15833): 	at libcore.io.Posix.open(Native Method)
W/AttachmentDatabase(15833): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/AttachmentDatabase(15833): 	at libcore.io.IoBridge.open(IoBridge.java:442)
W/AttachmentDatabase(15833): 	... 14 more
W/SaveAttachmentTask(15833): java.io.IOException: No stream for: (row id: 707, unique ID: 1471623718595)
W/SaveAttachmentTask(15833): 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getAttachmentStream(AttachmentDatabase.java:121)
W/SaveAttachmentTask(15833): 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:49)
W/SaveAttachmentTask(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:86)
W/SaveAttachmentTask(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:71)
W/SaveAttachmentTask(15833): 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:27)
W/SaveAttachmentTask(15833): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/SaveAttachmentTask(15833): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/SaveAttachmentTask(15833): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/SaveAttachmentTask(15833): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/SaveAttachmentTask(15833): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/SaveAttachmentTask(15833): 	at java.lang.Thread.run(Thread.java:818)
W/InputMethodManagerService(  873): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@185d026 attribute=null, token = android.os.BinderProxy@3dc6a7a5
W/MessageRetrievalService(15833): Application level read timeout...
W/MessageRetrievalService(15833): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(15833): Reading message...
```

**Comment by dschrempf** [comment]
I have the same issue.  The relevant logcat:

    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: java.io.IOException: File too short
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.crypto.DecryptingPartInputStream.createFor(DecryptingPartInputStream.java:52)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getDataStream(AttachmentDatabase.java:389)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getAttachmentStream(AttachmentDatabase.java:125)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:49)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:32)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:16)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at java.lang.Thread.run(Thread.java:761)
    05-02 17:30:30.963  8589  8641 W AttachmentDatabase: 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: java.io.IOException: No stream for: (row id: 171, unique ID: 1492461973631)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getAttachmentStream(AttachmentDatabase.java:127)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:49)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:32)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:16)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at java.lang.Thread.run(Thread.java:761)
    05-02 17:30:30.970  8589  8641 W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

It seems that the file is actually missing.  I observe that I cannot view files prior to a specific date.  I did not delete anything and do not think that my card is corrupted.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
