### ISSUE TITLE
Scroll to bottom button has the same color in bright and dark theme

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#6155]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The scroll to bottom button has a white background in the dark theme

### Steps to reproduce
- Switch to dark theme
- open a chat and scroll a bit upwards
- the button appears

**Actual result:** The button has a white background
**Expected result:** The button should have a dark background and white arrows

### Screenshots

not available

### Device info

**Device:** Oneplus X
**Android version:** 6.0.1
**Signal version:** 3.28.4

### Link to debug log

not available

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
