### ISSUE TITLE
Sometimes receiving "missed call" alerts even when Android phone was available

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6157]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Inconsistently get missed call alerts on Android (iOS sees Busy) when placing webrtc call

### Steps to reproduce
- Receive webrtc call to Android from iOS

**Actual result:** Only see "missed call" notification (after iOS screen shows busy)
**Expected result:** See full screen info of call

### Device info

**Device:** Moto X
**Android version:** 5.1
**Signal version:** 3.29.1

### Link to debug log

Most recent call was successful, the three prior to that only showed missed call alerts: https://gist.github.com/8a6ce8a198cd4507dba6fe697b859f5d

iOS log: https://gist.github.com/55af1201eb82ef82e25c5deb895a5c1f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
