### ISSUE TITLE
Display "x has left the group" instead of "Left the group" in conversation overview. 

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#6161]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

When a group member leaves a group the summary window displays *Left the group* although *`x` has left the group* would avoid confusion about whether I was the one leaving the group or another person.

### Steps to reproduce
- Open a group with other members
- Have one of the other members leave the group
- Open Signal's the conversation overview (where a list of conversations is seen, along with the latest message in each conversation)

**Actual result:** The latest message for the group in question is *Left the group* (`ThreadRecord_left_the_group`) which in most translations means that the user (you) left the group. 
**Expected result:** *x has left the group* (`ConversationItem_group_action_left`) should be displayed instead. 

**Signal version:** 3.25.x – 3.29.1

**Comment by nonlinear** [comment]
A nice to have: conversations authored by member that quit group appear differently: either faded out, or in italics.

**Comment by ianmcderp** [comment]
From the code I can tell that the used String resource has been adapted to provide the requested:
```xml
<string name="ConversationItem_group_action_left">%1$s has left the group.</string>
```
Also I cannot reproduce it on Android 7.0, Signal 4.16.9. When a user is leaving a group, the name of the left user is applied to the conversation item template.

**Comment by FeuRenard** [comment]
This issue is about the conversation list, not in-conversation.
![screenshot_20180313-205241](https://user-images.githubusercontent.com/16167751/37366521-ef31747c-2700-11e8-843c-ed9995b5e4c4.png)

Issue still present in 4.17.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
