### ISSUE TITLE
Tell user were exported file was saved

### ISSUE THREAD

**Issue by RaGaPlanet** [signalapp/Signal-Android#6164]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
After the export of Signal data or all images of a user were saved the only feedback given is that the operation was successful. However the user is not told where the files were stored. If you don't know the export directories it is very frustrating searching for the target folder in the Android file system.

Related language strings:
- ExportFragment_export_successful
- ConversationFragment_files_saved_successfully

### Steps to reproduce
- export all signal data
OR
- save all images of a user in a conversation

**Expected result (feature request):** Tell the user in which folder the files were saved/exported to. (internal oder external sdcard + folder / path)

### Device info
**Signal version:** 3.28.4

**Comment by FeuRenard** [comment]
I can imagine that a snackbar popping up would be even better. It says that saving/exporting was successful and offers the action to go to the directory by file manager or open the gallery at the right place.

**Comment by RaGaPlanet** [comment]
There is just the string notification, which fades away after approx. 1-2 seconds. No action options are displayed.

**Comment by FeuRenard** [comment]
f67eb5f9f3efc688cec1d1690bd379d18e5001b0 introduced the snackbar with the action to open the directory. I tested it on 4.4 and 5.1 and a tap on "Open directory" showed no effect. Is it working for anyone?

**Comment by FeuRenard** [comment]
Works with [ES File Explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop), doesn't work with [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager) (https://github.com/arpitkh96/AmazeFileManager/issues/419). So if a file manager is installed which supports "resource/folder" intents, "Open directory" will work.

Issue fixed :)

**Comment by vishal0071** [comment]
Should work with Amaze File Manager [now](https://github.com/TeamAmaze/AmazeFileManager/commit/2c14ba516b1e0eb845476ef3a8f930049e250b76).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
