### ISSUE TITLE
No way to retransmit "Leave the group" message on key change

### ISSUE THREAD

**Issue by alex** [signalapp/Signal-Android#6177]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

You're in a group with someone, you try to leave, but their key has changed since the last time you sent them a message. Your "leave the group" message will fail to go through, and there's no way to accept the key change on it.

### Steps to reproduce

- Be in a group with some people
- One participants key changes
- Leave group

**Actual result:** That person never sees your "left group" protocol message, so they keep sending you messages.
**Expected result:** You have the opportunity to accept the key change and re-send that message.

### Device info
**Device:** Nexus 5
**Android version:** 7.1.1
**Signal version:** 3.28.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
