### ISSUE TITLE
Create a group by selecting multiple recipients

### ISSUE THREAD

**Issue by jerome-tgl** [signalapp/Signal-Android#6181]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description

Support the creation of a new group by selecting multiple recipients in the 'new message' screen.

### Steps to reproduce
- click the floating action button to start a new conversation
- select a contact

**Actual result:** a conversation with the contact is instantly selected/created, with no option to add other recipient or to turn the conversation into a group.
**Expected result:** when creating a new conversation, a long-press on a contact would select it and allow more contact to be added (thus creating a group).

Also, a new option could be added to the 1:1 conversation menu to create a group with the current contact.

This UI would make groups more accessible, easier to discover, and more consistent with other messaging apps (e.g Whatsapp, Google's Messenger).

### Device info
**Signal version:** 3.29.2

**Comment by 2-4601** [comment]
#2989, #3083

**Comment by nonlinear** [comment]
Instead of long press, some other chat systems have a "add more users" option on menu under one-on-one conversation.

That could prompt group editing feature, with current user (from one on one conversation) selected by default.

Default title is usually member names, but easy to overwrite.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
