### ISSUE TITLE
4.1.0 WebRTC calls cannot utilize Bluetooth headset microphone

### ISSUE THREAD

**Issue by mmirg** [signalapp/Signal-Android#6184]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Call audio routing only works with speakerphone when making a WebRTC call with a Bluetooth headset connected.  Without the headset, I am able to toggle between the phone's earpiece and speakerphone.  When I connect a Bluetooth headset, I see options to toggle call audio between speakerphone, phone earpiece and the Bluetooth headset but I am unable to receive audio through either the phone earpiece or the Bluetooth headset.  Speakerphone continues to work as expected.  The call recipient indicated that they could hear me irrespective of which audio device I selected in the Signal interface.

### Steps to reproduce
- Connect Bluetooth headset
- Place WebRTC call
- Toggle audio between headset, speakerphone and earpiece to verify audio output.

**Actual result:** No audio can be heard through either the earpiece or headset.
**Expected result:** Audio should be routed to the correct sink when selected in the user interface.

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.29.6

### Link to debug log

https://gist.github.com/aa3e7cba4ee992d441d1567f03360360

**Comment by moxie0** [comment]
Strange, looks like a pretty modern device but I can't reproduce.

**Comment by mmirg** [comment]
I'm sorry for the relative paucity of useful information on this bug report, but upon further testing, I still have this issue but it seems to alternate between my Bluetooth headset either working properly to receive audio or to transmit audio.  If one function works the other does not.  I tried calling a Nexus 5X on the same network and was able to place several WebRTC calls that connected and was able to hear the audio transmitted from the other device but they could not hear anything from my end.  I verified that the same headset works without a problem with the old RedPhone style calls with Signal, regular PSTN calls and calls via WhatsApp.

Is there a more rigorous testing protocol that I could follow to produce useful information and/or collect something else from my device that might help with this?

**Comment by mmirg** [comment]
I've tried testing this more and have noticed a few things.  Audio is briefly routed to the headset audio when the audio output is changed via the UI toggle between "headset" and "speakerphone".  This happens in both directions, both when switching to speakerphone and to headset.  The change itself takes roughly five seconds (timed and based on intuition), so when I start the call on headset (as is the default) I will hear the connection audio and ringing through the headset.  When the call connects, I no longer hear audio but the recipient can hear my voice through the microphone on the headset.  When I switch to speakerphone, I will hear call sound through the earphone for a split second before the audio is re-routed to the speakerphone.  Likewise, when I toggle from speakerphone to headset again I will hear audio from the headset for a split second before the audio stops completely.

My headset, the Noble BTS, also contains a toggle button labeled "phone" which switches the headset between it's audio profile and headset profile.  When I press the mode switch button in the middle of a call, the UI will adjust itself to indicate that the available outputs are the phone earpiece and speakerphone but I will then hear audio routed to my headset (operating as an a2dp earphone) but the input source is the phone microphone instead of the Blueooth microphone (as expected.)

**Comment by moxie0** [comment]
Both Android and webrtc do not make this easy, but I've made some changes in 3.31.0 that I hope should make things work more consistently. Outgoing calls should be seamless. For incoming calls, I unfortunately can't seem to play the ringtone through the BT headset, but I can auto-connect once the call is answered. Hopefully this is an improvement. Please reopen if problems persist w/ that branch.

**Comment by mmirg** [comment]
I'm afraid I'm now experiencing an inverted version of this issue with 3.31.0.  Same Bluetooth headset (still working with RedPhone calls, WhatsApp, regular PSTN calls).  Placing an outgoing call routes the incoming audio to my Bluetooth headset but the microphone on the headset is not used for outgoing audio.  The handset microphone is not used either, rendering the call effectively one way.  I was not able to rectify this by toggling the new Bluetooth symbol button to disable the headset mid-call.

**Comment by mmirg** [comment]
The webrtc refactoring code, which I believe is included in the 4.0.0 release, still results in my the microphone of my Bluetooth headset not working.  Incoming audio plays correctly through the headset earpieces in one of the headset modes (there is no obvious feedback as to whether the headset is in "phone audio" or "media audio" mode) and both the microphone and earpieces are silent in the other mode.  Call recipients cannot hear my through my microphone irrespective of how I toggle the headset.  It continues to work properly with other telephony both with PSTN calls as well as through VOIP calls in applications like WhatsApp.

**Comment by mmirg** [comment]
I have done a few more tests to confirm this bug (at least on my particular device).  I have purchased a different Bluetooth headset adapter with similar, but not identical, functions to the first one and this device (the Avantree Clipper Pro) exhibits the exact same problem as the other Bluetooth transceiver.  I am able to make PSTN calls and VOIP calls using WhatsApp but Signal is unable to utilize the microphone on the headset.  I can hear the other person's voice through the earpieces.

I tried limiting the profile for the headset to "phone audio" only and disabled "media audio" in the Android Bluetooth settings but to no avail.  I also tried updating my Nexus 6P's OS to the latest 7.1.2 beta (build NPG47I) and experienced no change in symptoms.

**Comment by jeffbl** [comment]
I am having this exact problem with a Moto Hint (second generation) bluetooth headset. I call someone and can hear them fine through the headset, but they cannot hear me at all. Also tried turning off media audio for the headset (leaving only phone audio enabled) and makes no difference.

Running Signal 4.3.2, Nexus 6p stock 7.1.2

**Comment by JustMeOk** [comment]
Me too, on a multitude of devices.  Car, Plantronics, Sena.  It has rendered Signal unusable for calls for months now.

Signal 4.3.2, Nexus 5X, stock 6.0.1

**Comment by jeffbl** [comment]
Just tried it again, and my Moto Hint microphone successfully worked for an incoming call, as well as an outgoing call. This is great news.
Signal 4.6.0, Nexus 6p stock 7.1.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
