### ISSUE TITLE
Gboard GIF not importing

### ISSUE THREAD

**Issue by rezadu** [signalapp/Signal-Android#6187]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using Gboard keyboard, I am unable to attach GIFs from the keyboard. Error: "Attachment exceeds size limits for the type of message you're sending". GIFs from within the app work fine, however they are not the smoothest which is why I am trying Gboard GIFs.

### Steps to reproduce
- use Gboard as default keyboard
- open and choose any GIF within the keyboard

**Actual result:** GIF does not get selected to be sent with error: Error: "Attachment exceeds size limits for the type of message you're sending".
**Expected result:** GIF should be selected and able to be sent with no error.

### Screenshots

![signal error](https://cloud.githubusercontent.com/assets/16312571/22724288/cd8ed158-ed8a-11e6-856c-6eb3409a3e0e.png)

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.28.4

### Link to debug log

https://gist.github.com/anonymous/3199ba4a3a4b1b03e659d8a0e4871733

**Comment by 2-4601** [comment]
Related #5958

**Comment by Epopplew** [comment]
Try disabling the setting in developer options 
"Do not keep activities"

**Comment by moxie0** [comment]
@Epopplew I don't think it's very common for anyone to have that setting enabled. You would have had to enable developer options first (tapping 10 times or whatever on the device info) and then selected that?

**Comment by Epopplew** [comment]
It was enabled when I got this phone

**Comment by michaeljensen** [comment]
Mine is unchecked on my LG G4 and I'm unable to send any gifs.  It works fine for messages to signal users, but not over SMS.

**Comment by michaeljensen** [comment]
Looking through the debug log, I see a lot of this message, which appears to be related:
`BItmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!"`

**Comment by zee0** [comment]
there is another potential issue here, in that the error message simply isn't true. signal has a limit for SMS/MMS that isn't accurate for my network. using the standard messaging app that came with my phone, i've never seen this message when attaching a file or gif, but in signal it appears that 95% are too large.

**Comment by michaeljensen** [comment]
@zee0 I think you hit the nail on the head.  That appears to fit exactly what I'm seeing.  A quick search revealed to me that people can send 2MB files over MMS with my provider. (maybe even more)

**Comment by mftruso** [comment]
T-Mobile has a 1MB limit for MMS attachments
https://support.t-mobile.com/docs/DOC-5354

**Comment by michaeljensen** [comment]
I think a possible solution to this would be to allow the user to override the default limit of (what I've read to be) 300kb.  In 'Settings' under 'Chats and media'  seems like the perfect place for this setting.

**Comment by michaeljensen** [comment]
I'm not sure if this is related or not, but yesterday I sent a screenshot over SMS through Signal and it resized it to an unreadable 180x320 image (14.78KB) before sending.  The original image size was 1440x2560.  If it's related to the file size limit, I'll leave this here.  If it's unrelated, I'll open up another issue for it.

**Comment by gkubed** [comment]
@michaeljensen I've come to the same conclusion as far as placement goes. "Media Auto-Download" could be renamed "Media" and it could be dropped under there. 

Or, better yet, it could somehow auto-detect the carrier limit.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
