### ISSUE TITLE
Unencrypted Groups: "Me" is missing from the group members list

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6190]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
An unencrypted group's members list doesn't include "Me" like the encrypted groups do

### Steps to reproduce
- Open unencrypted MMS group conversation
- Tap the little picture of people to see the group members

**Actual result:** List includes all people _except_ for "Me"
**Expected result:** List includes all people _including_ "Me" to match encrypted groups

### Device info
**Device:** Samsung Galaxy Note 5
**Android version:** 6.0.1 (Stock Verizon)
**Signal version:** 3.29.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
