### ISSUE TITLE
Encrypted Groups do not contain group member count at the top like unecrypted groups

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6191]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In an encrypted group at the top under the name, there is no group member count.

### Steps to reproduce
- Open encrypted group conversation
- at the top, under the name, there is no member count

**Actual result:** No member count under the group name inside the conversation
**Expected result:** Under the name, there would be a member count, just like unencrypted group conversations do.

### Device info
**Device:** Samsung Galaxy Note 5
**Android version:** 6.0.1
**Signal version:** 3.29.2 but not really tied to this version

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
