### ISSUE TITLE
Feature Idea: Channels like BBM and Telegram using Tumblr blogs.

### ISSUE THREAD

**Issue by jaypatelani** [signalapp/Signal-Android#6196]
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
This is rather just and idea to have an integrated channel page or section like we have giphy we might get channels using tumblr. 

Thanks.
### BBM channel screenshots : 
![channels_all](https://cloud.githubusercontent.com/assets/17174485/22986628/2f0edf5c-f3d2-11e6-9c0c-3d9aced922dc.png)
### Telegram Channel list screenshot: 
![telegram](https://cloud.githubusercontent.com/assets/17174485/22986893/0073c094-f3d3-11e6-8931-97592c1aa347.png)

### Device info

**Device:** BlackBerry Dtek50
**Android version:** 6.0.1
**Signal version:** 3.28.4

**Comment by strugee** [comment]
@jaypatelani can you provide a more detailed description of what you're looking for? And can you edit your description so it doesn't include a bunch of useless issue template text?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
