### ISSUE TITLE
Importing SMS fails in Android 7.0

### ISSUE THREAD

**Issue by icanos** [signalapp/Signal-Android#6198]
### Bug description
When selecting Import / Export and choosing Import SMS the application reports that the SMS has successfully been imported, but when returned to the list of conversations, there's nothing there.

### Steps to reproduce
- Install a clean Signal
- Set Signal as default SMS application
- Click Import SMS

**Actual result:** No conversations imported
**Expected result:** Should have imported all my conversations to Signal and display them in the app

### Device info
**Device:** Huawei Honor 8
**Android version:** 7.0
**Signal version:** 3.28.4

### Link to debug log
Extracted info from debug log 'adb logcat':

02-09 12:00:32.896  2378  2662 E DatabaseUtils: Writing exception to parcel
02-09 12:00:32.896  2378  2662 E DatabaseUtils: android.database.sqlite.SQLiteException: no such column: group_all (Sqlite code 1): , while compiling: SELECT _id, address, person, thread_id FROM (SELECT thread_id AS tid, date * 1000 AS normalized_date, NULL AS time_body, text_only, NULL AS group_id, ct_t, msg_box, v, retr_txt_cs, ct_cls, NULL AS type, st, NULL AS address, NULL AS person, tr_id, read, m_id, NULL AS body, NULL AS addr_body, m_type, network_type, locked, resp_txt, retr_st, NULL AS error_code, NULL AS group_all, NULL AS reply_path_present, sub, NULL AS risk_url_body, rr, ct_l, NULL AS status, NULL AS subject, _id, m_size, exp, sub_cs, NULL AS group_fail, sub_id, resp_st, date, date_sent, pri, NULL AS group_sent, thread_id, read_status, d_rpt, rpt_a, NULL AS is_secret, m_cls, NULL AS service_center FROM pdu_restricted WHERE (read=0 AND thread_id!=0 AND (msg_box=1 OR type=1) AND (msg_box != 3 AND (m_type = 128 OR m_type = 132 OR m_type = 130))) GROUP BY thread_id HAVING date = MAX(date) UNION SELECT thread_id AS tid, date * 1 AS normalized_date, time_body, NULL AS text_only, group_id, NULL AS ct_t, NULL AS msg_box, NULL AS v, NULL AS retr_txt_cs, NULL AS ct_cls, type, NULL AS st, address, person, NULL AS tr_id, read, NULL AS m_id, body, addr_body, NULL AS m_type, network_type, locked, NULL AS resp_txt, NULL AS retr_st, error_code, group_all, reply_path_present, NULL AS sub, risk_url_body, NULL AS rr, NULL AS ct_l, status, subject, _id, NULL AS m_size, NULL AS exp, NULL AS sub_cs, group_fail, sub_id, NULL AS resp_st, date, date_sent, NULL AS pri, group_sent, thread_id, NULL AS read_status, NULL AS d_rpt, NULL AS rpt_a, is_secret, NULL AS m_cls, service_center FROM sms_secret WHERE (read=0 AND thread_id!=0 AND (msg_box=1 OR type=1) AND (type != 3)) GROUP BY thread_id HAVING date = MAX(date)) GROUP BY tid HAVING normalized_date = MAX(normalized_date), (OS error - 2:No such file or directory)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:899)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:510)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1397)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1331)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at com.android.providers.telephony.MmsSmsProvider.getConversations(MmsSmsProvider.java:1541)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at com.android.providers.telephony.MmsSmsProvider.query(MmsSmsProvider.java:992)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1020)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
02-09 12:00:32.896  2378  2662 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:565)

**Comment by 2-4601** [comment]
Are the messages you try to import MMS? (#4095)

Does this affect only Android 7.0 (per your title) or did you test on other versions too?

**Comment by icanos** [comment]
The messages I try to import is both SMS and MMS, around 30+ conversations with a few thousand messages.

I've only tested it on Android 7.0 as I only have 7.0 to test with. Maybe the title should be changed but I cannot help with verifying other version unfortunately.

**Comment by elvisk208** [comment]
Does the same for me on the same phone. SMS messages fail to import. 

I had to use SMS Backup to import them.

**Comment by mannp** [comment]
I too was about to report the same problem on an Honor 8 phone running Android 7.0

The message reports success but no messages are imported.

@elvisk208 How did you use SMS Backup to import them when Signal uses its own message db? Doesn't SMS Backup only work with the android text db? Thanks.

Issue still the same on the latest release beta version.

Thanks in advance.

**Comment by amirghm** [comment]
its because for android 7.0 huawei uri changes, for example `content://mms-sms/conversations?simple=true` is removed and have no replace for it

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
