### ISSUE TITLE
Feature - Ability to customize default Invitation message

### ISSUE THREAD

**Issue by dakuzen** [signalapp/Signal-Android#6206]
When communicating with someone via SMS the "Invite to Signal" banner when pressed places 

```
Let's use this to chat:
https://sgnl.link/1234
```

It would be nice if I could customize that first line to make it more personal, without having to modify it each time.

**Comment by micressor** [comment]
+1

**Comment by mateoeh** [comment]
@micressor Please don't +1 issues

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
