### ISSUE TITLE
Pictures sent by text not displayed in conversation 

### ISSUE THREAD

**Issue by stumpylog** [signalapp/Signal-Android#6207]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send a picture via unsecured MMS to a contact, the picture is not displayed correctly in my conversation view.  Instead of the picture, I see an empty box with the send time/date displayed.  The receiver reports no issues viewing the image, so it does appear to send.

### Steps to reproduce
- Open Signal, open conversation with contact
- Press the attachment icon
- Select a picture to send
- Hit send
- Possible other step: Leave phone alone for a bit?

**Actual result:** The image is sent, but appears as an empty box, instead of a thumbnail of the image
**Expected result:** The image should be sent, and displayed in a thumbnail form

### Screenshots
Contact 1
![screen](https://cloud.githubusercontent.com/assets/797416/22836458/48ccc478-ef71-11e6-8835-8a0d849c7101.png)
Contact 2
![screenshot_20170210-095934](https://cloud.githubusercontent.com/assets/797416/22838008/eaf74312-ef77-11e6-8f2e-c56bdcbb765c.png)

### Device info

**Device:** Samsung S7 on Verizon (G930V)
**Android version:** 6.0.1
**Signal version:** 3.28.4
Sending over WiFi, WiFi calling compatibility disabled, SMS delivery turned on, screen security on

### Link to debug log

It took a few tries this morning
https://gist.github.com/anonymous/b487c5914313dc75daf8fa692d695865

**Comment by piwacet** [comment]
Just verifying I have the same issue. Developed in the last few weeks with one of the updates. Motorola Droid Turbo running stock. Android version is 6.0.1 (I assume motorola made some tweaks to this software.)
Thanks for this great messaging app!

**Comment by Asphahyre** [comment]
Same issue on my OnePlus 3.
Please note than the full image appears when I touch the supposed frame of the thumbnail.

**Comment by collin-o** [comment]
Same issue/behaviour Samsung S6 Edge Plus.  Send image, after finished sending blank placeholder appears in thread where image should be.  Tap placeholder and image will appear.  Has been like this for weeks now... used to work fine but an update whacked it out.  Does not occur with any other messaging app.

**Comment by stumpylog** [comment]
I'm wondering if this could be related to change from 183f874.  The timeline would be about right from my perspective and from @piwacet "in the last few weeks"

Also, based on the log, [line 643](https://gist.github.com/anonymous/b487c5914313dc75daf8fa692d695865#file-cat-log-L643) starts an outgoing MMS connection, followed shortly by ThumbnailView deciding to not reload at [line 644](https://gist.github.com/anonymous/b487c5914313dc75daf8fa692d695865#file-cat-log-L664), it may be realated any way.  I'll keep poking around, it's rather fun

**Comment by moxie0** [comment]
@stumpylog yeah one of those commits around there is probably the culprit. thanks for the screenshots everyone

**Comment by mantono** [comment]
Same here!
_Fairphone 2
Android 5.1_

**Comment by jkdf2** [comment]
Can confirm this on my Nexus 6P running the latest Signal-Android `master` branch on Android 6.0.1. Sender is on a Nexus 6P on Android 7.x. Not sure which Signal version.

There's one specific picture that causes it in my conversations.

[Debug log when message arrives](https://gist.github.com/jkdf2/a69548a1a14d634b9677e3bf3655ac41)

[Debug log when opening the blank thumbnail](https://gist.github.com/jkdf2/829e451f672b7af9b1419c59bc6c7197)

The `D/skia: --- decoder->decode returned false` line seems telling; I don't get this in my log for the pictures that do work. 

Note that unlike the other people in this thread, the image does **not** show up when I click the thumbnail. The full-screen view is also a blank image.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
