### ISSUE TITLE
Video playback is sometimes broken for the sender

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#6214]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When viewing a video in a conversation the video fails to play for the device that sent the video. The recipient is able to view the video without issue. This issue has happened to me with multiple videos and it may be related to file size because I sent a very short video as a test to replicate this and the issue was not present. All videos in question were recorded with the device's camera using the default Android camera app at 1920x1080 and 60fps.

### Steps to reproduce
- Send a video to someone
- After the video has been sent, tap the preview thumbnail to begin playback

**Actual result:** The playback screen opens but it only shows a black frame and the video does not play
**Expected result:** The video should play

### Screenshots
![screenshot_20170211-191826](https://cloud.githubusercontent.com/assets/984047/22858562/3f94582a-f08f-11e6-8223-d1789377c84e.png)

### Device info
**Device:** Google Pixel
**Android version:** 7.1.1
**Signal version:** 3.28.4

### Link to debug log
https://gist.github.com/42c90d1b77837e33c8af219e1f2f4889

**Comment by haffenloher** [comment]
Do these longer video files play if you wait a bit after tapping the thumbnail, like 15-20 seconds?

**Comment by justin-** [comment]
Yes, after 30 seconds or so it begins playing but it halts before reaching the end of the video. The video in question is around 50 megabytes.

**Comment by paride** [comment]
@haffenloher @junitas Same here, more or less, but:
- I'm the recipient, not the sender;
- The video does not autoplay even if I wait up to two minutes after tapping the thumbnail;
- The video plays if I move the video progress bar, but halts before reaching the end.

Nexus 6, stock Android 7.1.1, Signal 3.31.4.
The video is 26 seconds long.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
