### ISSUE TITLE
Contact numbers display briefly as app opens

### ISSUE THREAD

**Issue by elvisk208** [signalapp/Signal-Android#6215]
Hiya,

Every time I open Signal, when the app has been closed down only, I briefly get displayed a list of my message threads. But instead of names for contacts, the app shows me their phone numbers before it quickly writes over with contact names. 

Odd behaviour to add - the top thread always displays correctly with name not number. 

It's not a massive bug but just looks annoying and unpolished.

**Comment by elvisk208** [comment]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As above, opening app from closed state briefly displays contact numbers not names. Names are quickly filled in. 

### Steps to reproduce
- Close app, reopen

**Actual result:** App opens and displays numbers before quick redraw. 
**Expected result:** should show names. 




### Device info

**Device:** Honor 8
**Android version:** 7.0.0
**Signal version:** 3.29.3

**Comment by scienmind** [comment]
On weak/old devices it takes even longer, I witnessed it up to 30 seconds...
I thought on faster devices it would be unnoticeable

Some other phone/contacts apps have this behavior as well, so it's not "only signal" that stores the number and retrieves its details upon the first launch after boot. Due to Signal's encrypted storage, it's just more noticeable there than in other apps.

Maybe temporary storing the details within the application, and re-scanning in the background would make it look "more polished".

**Comment by elvisk208** [comment]
Interesting. Textra doesn't do that on my Honor 8, nor WhatsApp. But some other third party text apps do. 

Same behaviour on my old Moto X. 

It doesn't look very slick at all.

**Comment by Asphahyre** [comment]
I have this problem too.
I don't know if it's due to the same thing, but I also had a problem with other Signal contacts. Signal only showed their number instead of the contact name registered in my phone.

This bug doesn't appear since I reinstalled Signal due to another bug yesterday.

**Comment by johanw666** [comment]
I would not call it a bug, just a glitch. I see it too on a Z3 compact, which has a fairly fast SD 801 soc but it didn't bother me. That it disappears after reinstall is probably due to it not having to load any message data then. Storing the names and re-scanning them in the background seems overly complicated to me to solve a minor gui issue.

**Comment by elvisk208** [comment]
Glitch good description. 

But it does bother me. Reinstall doesn't work. Suggest a splash screen while it does the work to scan contacts? Cover over the problem?

**Comment by ocram** [comment]
The priority here may be showing initial content to the user as fast as possible.

If you want to delay showing the content until you have resolved all contact numbers, it may introduce a small but noticeable delay (e.g. 150ms).

**Comment by elvisk208** [comment]
Would prefer delay, personally. 

I'd add the iOS version doesn't exhibit this behaviour.

**Comment by Trolldemorted** [comment]
@ocram why does loading the contacts' names take longer than loading the contacts' numbers? Genuine question, did not yet take a look where the contacts are stored.

**Comment by anselhazen** [comment]
I have seen this bug now with at least the last 3 versions of Signal.  More disturbing is that when this does it Signal is also not password protecting messages. Everything can be seen.

**Comment by elvisk208** [comment]
If so, should this whole issue be reclassified as a bug, not a UX issue?

**Comment by 2-4601** [comment]
>  More disturbing is that when this does it Signal is also not password protecting messages. Everything can be seen.

Could you please clarify what this means?
How to reproduce?

**Comment by anselhazen** [comment]
What I experience is if my phone has been "sleeping". I swipe to open it. I tap signal to open it and at times it will not ask for the password that I have set to lock signal. I only see this happen when I have not used the phone for awhile. Contacts will only have numbers not names and every contact is grey. Once signal assigns the colors and names to the numbers and I close then reopen it is password protected like it should.

Another issue is if you go to signal via the icon that puts you on the screen with all the recent apps that have been used. If it was the last used and on "top" contacts and the most recent message is showing. Again, should have been password protected.

**Comment by 2-4601** [comment]
> What I experience is if my phone has been "sleeping". I swipe to open it. I tap signal to open it and at times it will not ask for the password that I have set to lock signal. I only see this happen when I have not used the phone for awhile. Contacts will only have numbers not names and every contact is grey. Once signal assigns the colors and names to the numbers and I close then reopen it is password protected like it should.

Could you post a [debug log](https://support.whispersystems.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-) after this happens?

> Another issue is if you go to signal via the icon that puts you on the screen with all the recent apps that have been used. If it was the last used and on "top" contacts and the most recent message is showing. Again, should have been password protected.

Sounds like #3172.

**Comment by elvisk208** [comment]
Is there any update on this possibly being fixed. It looks awful as the app opens. While i admit it isn't a severe issue, I wonder if it is putting some off using the app.

**Comment by janvlug** [comment]
@elvisk208 I understand that you are interested in progress on this issue, or that you might be worried that the issue is forgotten. I myself am quite often tempted to ask for status updates in issues as well. However doing so consumes costly time of the limited number of developers. This issue tracker is really for reporting issues or adding new information to already reported issues that might help solving them.
You can always discuss issues and ask for status updates in the community forum at: https://whispersystems.discoursehosting.net/

**Comment by elvisk208** [comment]
Erm ok. That's not clear anywhere. Just an average punter asking for updates...

**Comment by strugee** [comment]
@elvisk208 https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues, though admittedly that's only linked to when you file issues.

**Comment by elvisk208** [comment]
It seems in the latest beta builds the issue with contacts displaying initially as numbers has been resolved. But now, contacts pictures are exhibiting a similar behaviour. At first they are blank and slowly appear from the bottom up.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
