### ISSUE TITLE
"Remind me later" for safety number changes

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#6226]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

It'd be nice if, when a contact's safety number changes, Signal would provide me an option to remind me later about verifying the change. This would be useful because, while I usually want to verify these changes, it's not always practical in the moment.

I'm on Signal 3.29.6.

**Comment by cascheberg** [comment]
Related / Duplicate: #910

**Comment by strugee** [comment]
@cascheberg yeah, I saw that. But it's pre-safety numbers and even if it weren't I don't think it'd be a duplicate.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
