### ISSUE TITLE
Unable to initiate video call, but can receive video call

### ISSUE THREAD

**Issue by t3io** [signalapp/Signal-Android#6228]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My friend is able to video-call me and I can see her video feed as expected. Clicking the camera icon to activate my video does nothing. If I call my friend, I can only initiate a voice call. 

### Steps to reproduce
- Receive Signal video call (yay!)
- Notice I'm receiving video, but not sending any video. 
- click on the video camera icon to activate it
- notice this doesn't change anything
- hang up
- call my friend
- notice this is a traditional voice call with no video options

**Actual result:** I can't send a video feed
**Expected result:** I can initiate my video feed, as well as initiate video calls in which the other party can activate their video feed 

### Device info
**Device:** Samsung Galaxy S5 Neo
**Android version:** 6.0.1
**Signal version:** 3.29.6

### Link to debug log
https://gist.github.com/7e611bbe594b9e4af916078905f1234c

**Comment by Natanji** [comment]
Have you tried disabling and re-enabling the Video Calling Beta and subsequently re-starting the Signal app? It seems like your instance of Signal hasn't yet noticed that your friend has enabled Video Calling Beta and is thus falling back to the old Voice Calling.

**Comment by riyapenn** [comment]
Also make sure you've enabled permissions for Signal. 

Specifically for Marshmallow OS: Go to Android Phone Settings > Apps > Signal > App Permissions > Enable all permissions. Even if this is enabled, please re-toggle the setting (turn it off and back on) and restart your phone.

**Comment by t3io** [comment]
All permissions were enabled, but I disabled, re-enabled, restarted the phone. Now works as expected. Thank you for this killer feature!

**Comment by t3io** [comment]
Unfortunately I spoke too soon. This bug is still present, with at least two contacts of mine using Signal on Android. When I call them, I usually only get the old-style voice only call, even though we have had successful video calls in both directions.

**Comment by t3io** [comment]
Log of me receiving video call from my friend:https://gist.github.com/anonymous/904efdfe2af2a31bfbb4bf5aeba8dfc9

Log of me calling my friend and getting an old style voice only call: https://gist.github.com/anonymous/e27c9d7338195ee258a36d975c84f47a

These happened within 10' of each other. I can't initiate a video call to my friend 90% of the time. My friend can video call me 100% of the time.

Please let me know if there is anything else I can do to help you debug this. I've restarted my phone, to no effect. I can always initiate video calls to my most common Signal-iOS contact.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
