### ISSUE TITLE
Update to 3.29.6 triggered re-registration/cleared app data

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6233]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Updating to 3.29.6 cleared app data and triggered reregistration; Could be device specific issue as user had similar issue with another app (Slack)

### Steps to reproduce
- User has auto-update set and is always on the latest version of Signal
- Updated to Signal 3.29.6

**Actual result:** Opening app shows registration screen, conversation history and app data are cleared
**Expected result:** Opens app and continue without any change to conversation history

### Screenshots

N/A

### Device info

**Device:** LGE Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.29.6

### Link to debug log
 https://gist.github.com/8b85cca4b307f621e4154752fccbfcef Log was captured much later than when issue occurred.  

Please close/I'll close if this log is useless and no one else reports this.

**Comment by brucejackson** [comment]
I experienced a similar incident, though not identical, with version 3.30.0.

Differences from the previous post:
### Steps to reproduce

- User has auto-update set and is always on the latest version of Signal (beta)
- Updated to Signal 3.30.0
- Opened  3.30.0 and Signal appear as expected.
- On a subsequent opening (within a few hours), registration screen appeared.

**Actual result:** Opening app shows registration screen, conversation history and app data are cleared
**Expected result**: Opens app and continue without any change to conversation history

### Device info

**Device:** LGE Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.30.0

### Debug Log
Sorry did not capture one any time close to incident.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
