### ISSUE TITLE
Flood of "Bad encrypted message"s on phone when desktop read queued messages

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#6243]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

When I started my desktop with Signal, Signal desktop started updating. It seemed that for each received  message, my phone (Android) received a "Bad encrypted message". Resulting in a flood of these messages.

Debug log from the phone:
https://gist.github.com/603ce003b45c6c2af42a3002c5b2b0c7

**Comment by Trolldemorted** [comment]
was your desktop offline for a longer period?

**Comment by janvlug** [comment]
I guess for less than a day. My desktop has been offline for way longer periods without issues.

**Comment by moxie0** [comment]
@janvlug for clarification, is the issue ongoing? or was it limited to this one burst of read notifications?

**Comment by janvlug** [comment]
It was a one time burst. At the moment the last message from the queue was processed on Signal on the desktop, the burst on the phone stopped.

**Comment by Trolldemorted** [comment]
@janvlug so subsequent messages sent from desktop to android are decrypted fine?

**Comment by janvlug** [comment]
This issue happened only once. So it was limited to a specific burst of updates that I received on the desktop. At the moment everything is working normal again, even when the desktop has been offline for a while and is reading the queued messages. Maybe the issue should be closed because it is not reproducible.

**Comment by nrizzio** [comment]
I don't think this should be closed. I've definitely had this happen to me in the past few months, albeit without any debug logs, but it has happened to me more than once.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
