### ISSUE TITLE
Screen won't stay dim after depressing lock button -- not sure if bug or if by design.

### ISSUE THREAD

**Issue by daemhan** [signalapp/Signal-Android#6258]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I don't know if this is an actual bug or not, and I hunted around the issues and couldn't see anything else, but, during a Signal call, the screen is always on -- even when I lock it. During calls with the standard dialer and other VoIP apps, I can hold down the lock button on the phone for a second or so, and it deactivates the screen. Depending on what I do, I can either lock the screen or just have it shut off during the call. With Signal, I get unexpected behaviour.

### Steps to reproduce
Unexpected Behaviour #1:
- Hold lock button down during call to deactivate active screen [make it go black until I want it active again/the call ends.]
- Screen goes dark as expected, but it only does so for several seconds, and then Signal turns the screen on again. It will not stay dimmed.

Unexpected behaviour #2:
- Tap out of Signal during active call. 
- Call status shows in status bar at top of phone screen, as it does with other apps.
- Hold lock button down to deactivate screen.
- Screen locks and goes black for several seconds, and then lights up again, as though I've got a new notification rather than something existing going on, and it will not dim again unless I hold the lock button down to manually dim it. Several seconds later, it lights back up again.

Expected behaviour:
In both scenarios, I expect the screen to stay dark until the call ends, I get a new notification from something else/new Signal message notification, or I actively unlock it again to start doing things on the phone while still in the call. This is the behaviour I am used to with other calling apps, and I like it for two reasons: conserves battery, since the screen isn't always on, and I minimise the chance of accidentally disconnecting or muting the call by tapping when I don't mean to.

### Device info
**Device:** HTC One M9
**Android version:** 6.0
**Signal version:** 3.29.6 -- has been doing this since I installed Signal for the first time at the beginning of November 2016, which was at least a couple of versions ago, so it's not new.
**Not sure if relevant, but I have told Android to use Signal as the default messaging app instead of using HTC's messaging app.

### Link to debug log
**Do not have debug log for this, since not sure if actual bug yet or if Signal is deliberately designed to behave in the above described manner.

**Comment by 2-4601** [comment]
I think it's the proximity sensor. Even if you explicitly lock the screen via the power button, the screen will still turn on if you move your hand over the proximity sensor. I would also expect Signal to respect the explicit locking of the screen.

**Comment by daemhan** [comment]
I'm not sure if it's that. I'm frequently lounging or laying down after having attempted to lock the screen without any movements near the phone [headset, phone above head or off to the side and not moving], and like clockwork after a few seconds, it just lights back up again. Even if I just use the lock button to dim the screen instead of explicitly locking it, it still comes back up.

But who knows, it could be that and Signal is just not working with it properly like the other apps seem to. I'll attempt to get a debug log the next time I'm on a Signal call. It won't be difficult to cause the behaviour to happen, since it happens every time.

**Comment by daemhan** [comment]
Here is the link to the debug log: https://gist.github.com/e9374e2f273e452d87cbf98e72e2a60b

I dimmed the screen once, and that lasted all of 1 second. Then I tried explicitly locking and dimming the lock screen, and that brightened again once I put the phone down.

**Comment by riyapenn** [comment]
Same as the first example in OP ~ Locking by pressing the power button and the screen just powers on after a couple of secs on its own and stays with the backlight on.  

Device: Samsung Galaxy S7
Android version: 7.0
Signal version: 4.10.12
Log: https://gist.github.com/anonymous/f1d7e88c9a8c5e4be6d62f534be9f471

**Comment by dpapavas** [comment]
This does indeed seem to be related to the proximity sensor.  When a call is established, Signal acquires a proximity wake lock, which turns the screen on and off, based on the proximity sensor, disregarding any manual user actions, such as turning the screen off via the power button.

It looks like it can be fixed, by turning the proximity wake lock into a partial wake lock when the user turns the screen off manually and back into a proximity lock, when the user turns the screen back on manually.

A sample implementation, can be found in commit dpapavas/Signal-Android@778a8574d6c69041ebf3de11e5cfe8e215158f66.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
