### ISSUE TITLE
Cannot initiate beta audio/video call to some contacts

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#6261]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I cannot initiate beta audio/video calls to some contacts. Instead, a classic "redphone" voice call is started. However, if they call me, audio/video calls work just fine. Meanwhile other contacts are unaffected. I've tried disabling and re-enabling the feature and restarting the phone as suggested in #6228. Additionally, I refreshed the contact list manually. But the problem persists.

### Device info
**Device:** Motorola Moto G 3rd Gen
**Android version:** 6.0.1
**Signal version:** 3.29.6

### Link to debug log
https://gist.github.com/anonymous/cf6f319050b052805e3c580f4043b41e

**Comment by michaelkirk** [comment]
Problem could be on the other end too. Could you have them toggle in/out of the calling beta?

**Comment by roberthesele** [comment]
same issue here no call & viedeocall to my contacts

phone: Moto G⁴ android 6.0.1,

signal. 3.29.6 beta

cheers Robert

Michael Kirk <notifications@github.com> schrieb am Di., 21. Feb. 2017,
00:04:

**Comment by roberthesele** [comment]
https://gist.github.com/28c180e37f32e21a4443739b4637e803

debug log!

i hope it's helpful, standard browser Firefox
plugins: webRTC globally disabled, H264 on.
have webRTC enabled, same results!

thanks for your great work!

Robert Hesele <r.hesele@gmail.com> schrieb am Di., 21. Feb. 2017, 02:15:

**Comment by merkste** [comment]
@michaelkirk I tried to turning it off and on again a couple of times on the other side for two contacts. Unfortunately, it didn't seem to have the desired effect besides testing their patience.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
