### ISSUE TITLE
Different layout on 2 screens with the same size

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#6267]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I run Signal on 2 different devices with the same screen size in pixels (720x1184): a Sony Xperia Z1 compact with Android 4.4.4 and a Sony Xperia Z3 compact with Android 6.0.1. The later has much more indentation, making it necessary to scroll the settings screen while the former has space to spare. Is this intended behaviour or a UX issue?

Z1C:
![signal_advanced_settings_z1c](https://cloud.githubusercontent.com/assets/8427572/23174238/0693734c-f85c-11e6-810f-b05336ec2b97.jpg)

Z3C:
![signal_advanced_settings_z3c](https://cloud.githubusercontent.com/assets/8427572/23174245/0d376802-f85c-11e6-9de1-915ece5a8d74.jpg)

Edit: forgot to edit out phone numbers.

**Comment by piratenpanda** [comment]
Looks like a theme issue. Clock also has a different font

**Comment by johanw666** [comment]
That's Android 4 vs. Anxdroid 6. Both phones are running stock.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
