### ISSUE TITLE
new message notifications won't go away after importing SMS database

### ISSUE THREAD

**Issue by Be-ing** [signalapp/Signal-Android#6270]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I installed Signal and was annoyed by notifications for new messages that would not go away after importing my SMS database. I searched for the phone numbers that Signal was saying I had new messages from, but they did not show up in my contacts or conversation history. I realized there were two phone numbers contributing to this. They both were phone numbers I had previous SMS conversations with before installing Signal but had not added to my device's contacts and who were registered with the Signal server.

### Steps to reproduce
- have SMS conversation with a phone number registered with the Signal server but not added to your device's contacts
- install Signal
- import SMS database

**Actual result:** Signal displays a new message notification until all phone numbers registered with Signal are added to device's contacts or those conversations are deleted. Notification is displayed in notification drawer and keeps device's notification LED blinking.
**Expected result:** no notification is displayed

### Device info
**Device:** Samsung Galaxy S5 Mini SM-G800H
**Android version:** [Cyanogenmod 12.1-20151208-UNOFFICIAL-kmini3g](https://forum.xda-developers.com/galaxy-s5-mini/orig-development/rom-cyanogenmod-12-1-s5-mini-t3105617) (based on Android 5.1.1)
**Signal version:** 3.30.0

I fixed the issue before being able to take screenshots or a debug log. I cannot reproduce it by deleting a contact who has Signal installed. I don't want to reimport my SMS database to try to reproduce the issue because Signal warns that will result in duplicate messages.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
