### ISSUE TITLE
Call information is labeled as unread messages

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#6275]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Screenshots
![screenshot_20170222-002457](https://cloud.githubusercontent.com/assets/174176/23188309/e670beb8-f896-11e6-9ed9-f8de294a87ac.png)

Dunno what to do with these. I guess this applies to other status messages too. It feels weird to refer to them as unread **messages**.

**Comment by cascheberg** [comment]
I'd say that's ok. But even outgoing calls are marked as unread, which does not make sense.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
