### ISSUE TITLE
UI for starting video calls is difficult to figure out

### ISSUE THREAD

**Issue by Be-ing** [signalapp/Signal-Android#6278]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After instructing the user I was communicating with how to enable the beta video calling in his preferences, we still had difficulty figuring out how to start a video call. He called me and I saw him on video, but he could only hear me without seeing video from me. After a minute of confusion, he told me to press the video camera icon on my phone while in the call, which initiated me sending video.

### Steps to reproduce
- Have WebRTC voice/video calls enabled on both devices
- View conversation

**Actual result:** There is no indication of any way to initiate a video call, or that Signal supports video calling.
**Expected result:** A video camera or other clear icon would be next to the phone icon at the top of the conversation to initiate a video call

**Comment by motatuc** [comment]
Well, I personally dislike the idea of having the call initiated with video enabled by default.
It's good to have audio only by default. And if someone wants video - it can be enabled on demand.

Coming to that point: How much more easy should it be to start the video? All that one has to do it pressing the video button. It might be hard to make it more simple :)

**Comment by snaggen** [comment]
The original request seems to be for an additional call button for Video calls, next to the regular call button. And only the Video call button would initiate video by default. 
I think this is a great way to make video calls easier, and still keep the regular audio only calls.

**Comment by Cormak** [comment]
>  All that one has to do is pressing the video button. It might be hard to make it more simple :)

This is some weird doublethink language here. The point is that pressing 2 buttons is a not as simple as pressing one. It's silly to force the user to start an audio call in order to get to a video call, and the video call button is next to the speaker and mute buttons, which is confusing since those buttons have completely different functions. Two of the buttons affect the call in progress and one of them starts a new kind of call, yet they are the same size and are right next to each other.

I agree with Snaggen and the OP that there should be a video call button next to the audio call button. However, I would like to add one thing: the receiver should be explicitly shown what kind of call they are getting. It should say "Audio Call" or Video Call" according to what the caller presses so the receiver can reject a video call if they are not ready or not willing to appear on video or reject an audio call if they prefer a video call.

**Comment by snaggen** [comment]
@motatuc Well, yes it might not sound very difficult to press two buttons... but if I intend to start a video call with you. I then start with making an audio call, then I have to upgrade my side of the call to Video and then tell you to do the same...  Ok, I agree that it is not really difficult to click the actual buttons, but the whole procedure is not very streamlined (well, if I call my dad, getting him to press the correct button might actually be difficult... ). Wouldn't it be easier if I just clicked the "video call" button, then you see an incoming video call and answer?

**Comment by motatuc** [comment]
I got your point and they convinced me. A two button solution would be not too bad. With an indication about what call is going to be established like @Cormak suggested.

**Comment by wizardofid** [comment]
I prefer the possibility to upgrade an audio call to a video call when necessary or possible. So each side cut decide if its OK for him to enable video. Maybe i just want to show my partner something. Then i might enable video for a moment without needing him to switch over to video or us both to end the audio call and start a new one in video mode. I like the interface as it is.

**Comment by snaggen** [comment]
@motatuc Yes, knowing what type of call you are answering is important. And for Video Calls it might also be good to have a way to answer with no video... but it might be confusing to have a second answer button... 
@wizardofid But an extra video call button doesn't prevent you from calling audio only and upgrade your side. We are not talking about having the video button inside the call to behave differently, only to have an additional video call button you may use if you intend the call to be a two-side video call.

**Comment by Cormak** [comment]
@wizardofid We are simply talking about initiating a call. Nothing more. The video button in the chat makes things obvious to people. 

During the call, we can have a more distinct looking button that changes to video and vice versa, of course with a notice asking the other caller to confirm the change with a tap.

**Comment by Be-ing** [comment]
@snaggen:
> And for Video Calls it might also be good to have a way to answer with no video... but it might be confusing to have a second answer button...

I thought about this, but I don't think it would be a great idea. The UI for answering should be an extremely simple binary choice. There will be situations when the receiver can't or won't want to think about whether to answer as a full video or as an audio call, for example in a stressful situation or when the receiver is distracted. Also, many people will accidentally answer a request for a video call with an audio call, then get confused why it isn't a video call and struggle to actually have a video call as I did initially. If they don't want a video call, but do want an audio call, they can refuse the video call and call back with an audio call.

**Comment by UNIcodeX** [comment]
I like it the way it is now. Take the call, then decide whether to initiate / accept / decline video. Not hard IMO.

**Comment by justin-sleep** [comment]
I also prefer the UI as it is.  It's not what people are used to, but it feels more natural than segregating audio and video calls.  I agree that it's not how people would initially think video calls are started, because of how other applications isolate video calls into their own thing, but after you tell them "hit the button that looks like a camera to turn on your camera" they instantly understand in my experience.  I've had video calls with people who generally give up when they run into a technical or UX obstacle, and this isn't one of them.

+1 for just keeping a unified "Call" option.

**Comment by Be-ing** [comment]
If the UI has to be explained, it is a failure.

**Comment by Be-ing** [comment]
> I prefer the possibility to upgrade an audio call to a video call when necessary or possible. So each side could decide if it is OK for him to enable video. Maybe i just want to show my partner something. Then i might enable video for a moment without needing him to switch over to video or us both to end the audio call and start a new one in video mode. I like the interface as it is.

To clarify, I am not suggesting that the ability to toggle video on/off from a call that start as audio-only be removed (or that a video call can't be switched to an audio call during the call). That is indeed a useful feature. But it should be more obvious how to start a video call.

**Comment by nonlinear** [comment]
Maybe a caller can choose to initiate either audio or video... And receiver can pick up, cancel (as usual) and asecodwry funcionou (smaller area) offering switch ("answer as audio" if video or "answer as video" if audio).

This way it empowers both users, allowing receiver to refine initial option.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
