### ISSUE TITLE
feature request: switching to back camera for video calls

### ISSUE THREAD

**Issue by Be-ing** [signalapp/Signal-Android#6279]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

It is difficult to point the camera at something other than oneself during a video call using the front camera because it is hard to get oneself out of the way while seeing the screen. It would be helpful to be able to switch between the front and back camera in the call to make it easier to show one's surroundings.

**Comment by sigenc** [comment]
This is a really important request. At the Moment it is not possible to Show anything with webrtc.

**Comment by smidm** [comment]
+1

**Comment by p4nci** [comment]
@smidm please read [Contributing to Signal Android: dont-bump-issues](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues)
Please use reaction emojis as I did for your comment 😉

**Comment by zero77** [comment]
@sigenc 
Is this still the case.

**Comment by trymeouteh** [comment]
This would be handy especially when the video calls get laggy.

**Comment by nrizzio** [comment]
@trymeouteh Please [read the contributing guidelines and cease bumping issues.](https://github.com/WhisperSystems/Signal-Android/blob/f53d64ab7a77d4d79723729bfc4fba9685703c61/CONTRIBUTING.md#dont-bump-issues)

**Comment by alanina** [comment]
How can this feature request still be open in this day and age when the majority of the messaging apps have it enabled?

**Comment by Be-ing** [comment]
@alanina the Signal developers have their own priorities. Complaining with an entitled tone does not change that. Asking nicely might. If this feature is so important to you, you can program it yourself and open a pull request. Signal has [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) in this Git repository.

**Comment by alanina** [comment]
@Be-ing to be honest my tone was more surprised than entitled but how complicated could be to extend the current code that defaults to the front-face camera and use the exiting Android Camera 2 API as shown in one of the Google samples....
https://github.com/googlesamples/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java

....
 // We don't use a front facing camera in this sample.
                Integer facing = characteristics.get(CameraCharacteristics.LENS_FACING);
                if (facing != null && facing == CameraCharacteristics.LENS_FACING_FRONT) {
                    continue;
                }
....

**Comment by nh2** [comment]
I agree that this is an important feature, and it's a reason why many of my contacts have recommended not to use Signal (so I can understand @alanina's stance).

I've taken a couple hours of my free time today to implement this feature, adding a button to switch between front and rear camera: https://github.com/signalapp/Signal-Android/pull/7559

**Please test it if you can, and tell me if it works for you.**

Here's an built APK in case you don't want to build it yourself:

[Signal-play-debug-4.17.5-webrtc-camera-flipping.apk.zip](https://github.com/signalapp/Signal-Android/files/1843562/Signal-play-debug-4.17.5.apk.zip)

**Comment by alanina** [comment]
Niklas thank you for the effort. I will try out your debug build in a
couple days and let you know if it works as expected on my phone.

Many thanks!
Alex

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by greyson-signal** [comment]
FYI this was implemented in #7735. Thanks!
