### ISSUE TITLE
Using mobile data and wireless lan at the same time with webrtc call

### ISSUE THREAD

**Issue by sigenc** [signalapp/Signal-Android#6281]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When i call a friend, or he calls me. Everytime you can see that it displays on his phone the H+ while he is connected to his home wifi. We are not sure if this is intended behavoir or a bug. Didn't really pay attention to it in previous releases.

### Steps to reproduce
- initiate a webrtc call
- observe phone

**Actual result:** using wifi and mobile data at the same time
**Expected result:** use only wifi if connected
### Device info

**Device:** Samsung S6
**Android version:** Stock / newest version
**Signal version:** 3.29.6

Sorry no debug log. Could not convince him to share it, due to of privacy issues.

**Comment by tsdmgz** [comment]
Noticed it, but looks like it's intended behavior to speed up reconnection when wifi drops.

**Comment by merkste** [comment]
I have noticed this behavior as well. I argue that if wifi is available, an application should only use mobile data if the user gave its explicit permission. Otherwise costs may arise at a surprise during a normally free call.

However, is it a bug or a feature?

**Comment by irassek** [comment]
I have noticed this behavior while making a call and the audio was terrible. After a few retries i decided to switch off the mobile data manually and the audio quality improved just through wifi.
Smart Network Switch + Download Booster not active.
I hope this is not a feature, because it's decreasing audio quality! 
It would be nice to hear some explanation to this behavior. 
Maybe its an Samsung only behavior/bug/feature.

Samsung Galaxy 7 G930F Android 7.0

**Comment by rponline** [comment]
Hi!

I just used up a lot of data because of this behaviour.
A setting to prevent using data for calls would be nice.

**Comment by tsdmgz** [comment]
I would add that in areas where cell reception is significantly bad and the phone can't get a proper mobile data connection, it delays ringing or sometimes outright fails to set up the call.

**Comment by riyapenn** [comment]
According to one user this issue with Mobile data/wifi is happening with Google Hangouts. So it sounds like an OS issue. 

Device: Samsung Galaxy S7 Edge
Android version: 7.0
Signal version: 4.9.9
Signal debug log: https://gist.github.com/a012c3f96b9a0ecaa0910b9e833dbab9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
