### ISSUE TITLE
Error too many files  open 

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6284]
Signal crashed out of nowhere 
https://gist.github.com/39027f24964cf0c8e58db3a96f2853ff
#################################################################
02-22 05:56:01.309 17204 17239 E AndroidRuntime: Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	(unable to open database file (code 2062))
02-22 05:56:01.309 17204 17239 E AndroidRuntime: #################################################################
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:980)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getMessageCountForThread(SmsDatabase.java:170)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MmsSmsDatabase.getConversationCount(MmsSmsDatabase.java:126)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase.update(ThreadDatabase.java:525)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.incrementDeliveryReceiptCount(SmsDatabase.java:298)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MmsSmsDatabase.incrementDeliveryReceiptCount(MmsSmsDatabase.java:133)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handleReceipt(PushReceivedJob.java:69)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handle(PushReceivedJob.java:41)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob$1.onMessage(PushNotificationReceiveJob.java:39)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:134)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:36)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-22 05:56:01.309 17204 17239 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-22 05:56:03.509 17204 17239 I Process : Sending signal. PID: 17204 SIG: 9

**Comment by Trolldemorted** [comment]
sounds like https://github.com/WhisperSystems/libsignal-service-java/pull/26

**Comment by moxie0** [comment]
@Trolldemorted very unlikely, and try with resources is not supported on android at our minsdk

**Comment by Trolldemorted** [comment]
we can close the streams manually, if that is the only problem!

are you really sure that using deleteOnExit & not closing streams does not leak FDs? I suspected this could also be a cause of #5515

**Comment by moxie0** [comment]
he would have had to receive a *lot* of attachments in a short period of time to trigger a FD exception before the finalizer runs

**Comment by Trolldemorted** [comment]
or just enough attachments in a single message - or is there an enforced limit? An adversary could easily fit 1024 files into one message, if i understand it correctly

**Comment by jeremymasters** [comment]
I actually received zero attachments

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
