### ISSUE TITLE
feature request: intelligent temporary muting for active conversations

### ISSUE THREAD

**Issue by Be-ing** [signalapp/Signal-Android#6288]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

The muting feature is already decent, but it could be better. I don't want to mute a conversation then forget I had muted it and miss messages in the future. I want to be notified of new messages, but not be annoyed by torrents of new message notifications coming in quickly.

I think this could be possible with a relatively simple feature that I'll call "intelligent muting" for now, unless someone comes up with a better name. When enabled, conversations would automatically be muted for a short, configurable amount of time (like 5 minutes) upon receipt of a new message. New messages would not trigger a new notification until that amount of time elapsed without receiving a new message. Thus, I could be notified that there is new activity, but not have my notification sound go off 5 times within a few minutes. This would be especially helpful for large group conversations.

**Comment by cascheberg** [comment]
Related commit: 3787551878473c703a21210aa24d39080ad57ad4 "limit audible notifications to once every 2 seconds" (does not have a preference or so)

**Comment by Be-ing** [comment]
That's a good feature to have and does not need any configuration. But it addresses a different issue. The issue I am concerned with is active conversations that have new messages coming in not necessarily within a few seconds of each other, but within the amount of time it takes someone to read and respond to a new message.

**Comment by GSPP** [comment]
Reposting a relevant comment here:

I think the delay strategy needs to be configurable. With most friends I'd be OK with receiving messages only after quite some time. When my boss writes me I want my phone to buzz immediately and possibly for every message also.

**Comment by deutrino** [comment]
Very closely related to #5945

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
