### ISSUE TITLE
Two parties simultaneously calling each other results in endless ringing

### ISSUE THREAD

**Issue by haffenloher** [signalapp/Signal-Android#6289]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Two parties simultaneously calling each other results in (almost) endless ringing, plus missed call notifications on both ends. This can happen when a call drops unexpectedly and both parties want to re-establish it.

### Steps to reproduce
- Start webrtc call from device A to device B
- Quickly start webrtc call from device B to device A

**Actual result:** Call status never progresses past "Ringing..."; missed call notifications on both ends; call simply ends after a long wait
**Expected result:** Call gets established

### Device info
**Android version:** 7.1.1 / 4.2.2
**Signal version:** 3.30.0 / 3.30.1

### Link to debug log
I guess it's unnecessary, but including them anyway:
https://gist.github.com/baf5df2e328c64574eac570ded5334f1
https://gist.github.com/97070be9a1c69052bf96f51838a323ad

**Comment by Shenkaa** [comment]
The same happened to me two hours ago with a Samsung Galaxy S7 (6.0.1) and an OnePlus One (6.0.1).

**Comment by alterechtschreibung** [comment]
Yes, this is annoying.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
