### ISSUE TITLE
[UI] No easy way to access messages during a call

### ISSUE THREAD

**Issue by pgera** [signalapp/Signal-Android#6291]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
During a call, there is no way to go back to Signal from the call screen. You can't send a text easily during a call, for instance. You can go through a couple of additional steps by swiping the call screen away, and opening signal from the launcher again to get to the main signal screen though.

### Steps to reproduce
- Start a call
- Try to message either the recipient or a different person while on the call

**Actual result:** No back or text button on the call screen
**Expected result:** Some hook to go back to main signal app

### Device info

**Device:** Pixel Sailfish
**Android version:** 7.1.1
**Signal version:** 3.29.6

### Link to debug log

N/A

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
