### ISSUE TITLE
Error updating group

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#6295]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I tried to update a Signal group (very active, many members, lots of messages), because the messages of some members arrived multiple times, and other messages seemed to be missing.

I got an error updating the Signal group:

In the notification area:
Message Delivery failed
Failed to deliver message

In Signal contacts/groups overview:
Red exclamation mark, <contact name 1>, <part of contact name 2> <rest invisible>

Debug log:
https://gist.github.com/6303f6db23e699366785f48339774707

**Comment by janvlug** [comment]
Some more info:
* It appeared that the identities of one of the group members were out of sync between my phone and desktop. The new identity was known on the desktop, not on the phone.
* The group name did change on the phone, but not on the desktop.
* Another group member got a notification of the group name change,
* The person that saw the group name change sent me a few messages. These messages only arrived at the phone, not the desktop. I think (but am not fully sure) that I did not get a notification of these messages.
* I saw that the last contacts import on the desktop was more that two weeks old. I did another import. No errors we shown, but the group name did not update.

**Comment by janvlug** [comment]
Update:
I noticed that the person whose messages did not arrive at the desktop actually sent SMS text messages. Not Signal messages. He cannot send me Signal messages, but I can send messages to him, that he receives fine. I have the same issue with at least one other contact that I am aware of. See https://github.com/WhisperSystems/Signal-iOS/issues/1807 One of the contacts has an iPhone, the other one an Android 6.0.1.

**Comment by janvlug** [comment]
After that I did another import of contacts today on the desktop, the name of the group on the desktop has been updated.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
