### ISSUE TITLE
Treat hotspots like mobile data for auto-download

### ISSUE THREAD

**Issue by patcon** [signalapp/Signal-Android#6297]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

-----

Hi all! Hopefully all is going well! Appreciative of Signal as it stands, but just wanted to file this feature request :)

## Observed behaviour

When a user tells Android OS that a certain wifi network is metered:

    Settings > Data usage > more > Network restrictions

and sets Signal config _not_ to auto-download media on mobile networks:

    Settings > Chats and media > Media auto-download > When using mobile data

but allows Signal to download everything on wifi:

    Settings > Chats and media > Media auto-download > When using Wi-Fi

Signal downloads as if it were a regular, unmetered wifi network.

## Expected behaviour

Android does some cleverness to recognize and auto-tag wifi hotspots as metered. I would expect an app to treat metered wifi as if it were data, and use those settings.

## Suggested improvements

Would be rad if Signal used [`isActiveNetworkMetered()`](https://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered()) to check on this. `grep` doesn't seem to show this being used in codebase.

Many apps seem to neglect this, which is unfortunate, as it's _high_ penalty on the off time someone decides to share a whole bunch of photos and videos. haha oy. Given this, it would also be nice to tip the user that you're aware of the common oversight by changing the config string from "When using Wi-Fi" to "When using Unmetered Wi-Fi". This let's people with hotspots know they don't need to bend over to confirm they won't get drilled with overage charges :)

In closing, thanks again for everything! <3

**Comment by nrizzio** [comment]
@dmo580  Please don't [bump issues.](https://github.com/WhisperSystems/Signal-Android/tree/master/CONTRIBUTING.md#dont-bump-issues)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
