### ISSUE TITLE
Group member who has blocked you doesn't get your messages in group

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#6299]
I have:
[x] searched open and closed issues for duplicates
[x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Group member who has blocked you doesn't get your messages.

### Steps to reproduce
- create group with user A and B
- user A blocks user B
- B writes something in group

**Actual result:** A doesn't get group messages from B. 
**Expected result:** A should still get group messages from B.

### Device info
**Android version:** 7.1.1 / 7.1.1
**Signal version:** 3.29.6 / 3.30.3

### Screenshots
![image_b](https://cloud.githubusercontent.com/assets/26023321/23331434/f7c1819c-fb5d-11e6-863a-24e170a66ee0.png)
![image_a](https://cloud.githubusercontent.com/assets/26023321/23331437/fdb81a8e-fb5d-11e6-82c3-3ed76e5626e7.png)

**Comment by Trolldemorted** [comment]
Isn't that the very point of blocking?

**Comment by asdf38** [comment]
I think everyone should get all messages in a group, I believe WhatsApp handles it this way, but I'm not quite sure.

**Comment by brianpgrissom** [comment]
If someone blocks you, you should be blocked, group or not.

**Comment by haffenloher** [comment]
Adding to what the others already said: This would make it trivial to circumvent blocks. Every time someone blocks you, you could just create a two-person group and continue messaging them.

**Comment by asdf38** [comment]
I think it's weird if someone responses to nothing...
@haffenloher That's true, but wouldn't it be possible to check if one has blocked you before adding one to a group? If not, there has to be another way of preventing that case.

**Comment by TheSpeedyBlur** [comment]
I think the correct way of handling this is like Facebook's Messenger. It shows a warning dialog that someone you blocked is in this group, and you can choose whether you'd like to see the messages in the group or leave the group.

**Comment by brianpgrissom** [comment]
I disagree. Blocking should be private. If they know you blocked them then they may try and find ways around it

**Comment by TheSpeedyBlur** [comment]
I was talking about this scenario: When A blocks B, and anyone creates a group including the two of them, a warning message is shown ONLY to A. B can write freely to the group.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
