### ISSUE TITLE
Send again doesn't show spinning element after pressing

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#6307]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If a message fails to send, the red exclamation mark takes one to the details view where the send again button is located. In earlier Signal versions the button disappeared after pressing it and some spinning element or dancing dots appeared, signalling that something is happening. Since a few versions now nothing happens visually after pressing even though Signal is trying to resend the message. This is confusing and leads to pressing the button again and again because nothing seems to be happening.

### Steps to reproduce
- Send a message that fails to send for whatever reason
- click for details
- press resend button

**Actual result:** 

Nothing signals the user that something is happening, button stays active all the time

**Expected result:**

Deactivate the button and signal that something is happening

### Device info
**Device:** Huawei Nexus 6p
**Android version:** 7.1.1
**Signal version:** 3.29.6

**Comment by piratenpanda** [comment]
It still shows the resend button again when leaving the details view and entering it again before the message gets resent/another warning is shown

**Comment by iafisher** [comment]
This is still an issue for me on 4.53.6. After a message fails to send and I press "Resend", there is no indication either in the conversation view or the detail view that Signal is attempting to resend the message, and the "Resend" button is still visible. As piratenpanda noted, this can lead users to hitting "Resend" multiple times.

Could this issue be reopened?

**Comment by cody-signal** [comment]
This should be fixed by this commit https://github.com/signalapp/Signal-Android/commit/fb600e98291951efbab37ee6033624db67ffa78b. Please test again and let us know.
