### ISSUE TITLE
Group texts come in as MMS that can't download on WiFi

### ISSUE THREAD

**Issue by dbolton** [signalapp/Signal-Android#6311]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In group text messages I often get the following error message: "Error downloading MMS message, tap to retry." The message appears to come from the individual person rather that appearing in the group. If I tap to retry the download, it fails every time while on WiFi calling. If I leave WiFi and get cell service, the text downloads without errors and moves back to the group rather than appearing to be from a single person. 

In the Signal settings I have WiFi calling compatibility turned on. Individual texts come through on WiFi. So far I've only experienced the problem within the context of a group text that includes a mix of Android and iPhone users. 

Others have reported issues with group texts (listed below) but the WiFi calling aspect seemed to warrant its own issue report
* https://github.com/WhisperSystems/Signal-Android/issues/5868 
* https://github.com/WhisperSystems/Signal-Android/issues/5868
* https://github.com/WhisperSystems/Signal-Android/issues/5867

### Steps to reproduce
- connect to WiFi
- turn on WiFi calling on phone 
- turn on WiFi calling compatibility within Signal settings
- join a group text message that include non signal users on android and iphone
- wait for texts from all members of the group. 

**Actual result:** messages from some users fail to download and appear as individual texts. 

**Expected result:** all texts should download and appear in the context of the group

### Device info

**Device:** LG G5
**Android version:** 7.0
**Signal version:** 3.29.6

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
