### ISSUE TITLE
[Feature request]: Grey out or disable contacts you aren't talking to to avoid sending info to wrong contact

### ISSUE THREAD

**Issue by ailanthus8** [signalapp/Signal-Android#6319]
### Bug description

It is easy to send sensitive information to the **wrong** **contact** on Signal desktop or mobile. This is especially easy to do if you use Signal continuously throughout the day and alternate between conversations. People who use Signal may be sharing very sensitive information. Misfires can be disastrous. 

### Feature request

Provide a user option that greys out or (better) disables every contact except the one being actively used. 
Example of the need: A friend accidentally shared sensitive personal information with a reporter today, and he told her he had done the exact same thing earlier in the day. My friend did this when she moved from Signal IoS to Signal desktop, which had a different contact's window open than on IoS. Yes, she is an idiot, but there are a lot of idiots with sensitive information who are using Signal.

For many Signal users, this would be a very important feature. Finding ways to reduce user error makes Signal safer to use.

### Device info

**Device:** Iphone 5c
**IoS version:** 10.2.1
**Signal version:** 2.7.1

Desktop: MacBookAir
OSX Sierra 10.12.3 
Signal version: "About Signal" is greyed out

**Comment by 2-4601** [comment]
This is the Android client's repository, seems like you are talking about Signal iOS?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
