### ISSUE TITLE
UI glitch when opening Settings -> SMS and MMS section

### ISSUE THREAD

**Issue by scienmind** [signalapp/Signal-Android#6321]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Visual glitch when opening SMS and MMS settings - wrong menu shown temporary

### Steps to reproduce
- Open Signal
- Open Settings
- Click "SMS and MMS"

**Actual result:** for a fraction of a second a messed up "SMS and MMS" section shown:

* SMS Enabled
* SMS delivery reports
* WiFi Calling compatibility...
* SMS delivery reports (duplicate)
* WiFi Calling compatibility... (duplicate)
* Manual MMS settings
 --- followed by the correct "SMS and MMS" section: ---
* SMS Enabled
* SMS delivery reports
* WiFi Calling compatibility...

**Expected result:** correct "SMS and MMS" section shows up straight away

* SMS Enabled
* SMS delivery reports
* WiFi Calling compatibility...

### Device info
**Device:** Samsung S4 Mini
**Android version:** 6.0.1 (CM 13.0)
**Signal version:** 3.30.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
