### ISSUE TITLE
Received image shows up blank

### ISSUE THREAD

**Issue by jkdf2** [signalapp/Signal-Android#6323]
Nexus 6P running the latest Signal-Android `master` branch on Android 6.0.1. Sender is on a Nexus 6P on Android 7.x. Not sure which Signal version.

Conversation is a Signal <-> Signal conversation.

There's one specific picture that causes it in my conversations.

[Debug log when message arrives](https://gist.github.com/jkdf2/a69548a1a14d634b9677e3bf3655ac41)

[Debug log when opening the blank thumbnail](https://gist.github.com/jkdf2/829e451f672b7af9b1419c59bc6c7197)

The `D/skia: --- decoder->decode returned false` line seems telling; I don't get this in my log for the pictures that do work. 

The image does **not** show up when I click the thumbnail. The full-screen view is also a blank image.

Interestingly the image shows up perfectly on Signal-Desktop.

This seems somewhat related to #6207 but this is on the receiving end instead of the sending end.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
