### ISSUE TITLE
New in and outgoing sounds while in-conversation view

### ISSUE THREAD

**Issue by qauff** [signalapp/Signal-Android#6325]
I think if we had different and subtle sounds upon receive and sending of messages while you're in the conversation, it'd make the app feel much more polished.

**Comment by moxie0** [comment]
Have a sound in mind?

**Comment by qauff** [comment]
I'm sure they're not GPL friendly, but I extracted these two files from an "Android Messages" apk:

Receive sound: https://drive.google.com/open?id=0B52VJwf78X5WekVYcTdPLTZGNFE
Sent sound: https://drive.google.com/open?id=0B52VJwf78X5WRzRHcng2TkY0ZFk

I'm noticing more Messengers has little sounds like these and it really makes the app feel more polished, in my opinion at least.  If this is something you agree with, I'll keep looking for some GPL friendly sounds :)

**Comment by moxie0** [comment]
I'm definitely not opposed to the idea of having send/receive sounds, but yeah we probably can't just take them out of an APK =)

Let us know if you find something good that we can license

**Comment by qauff** [comment]
How about these?

Receive: 
http://soundbible.com/2067-Blop.html
http://soundbible.com/2044-Tick.html

Send: 
http://soundbible.com/2068-Woosh.html

**Comment by qauff** [comment]
@moxie0 any opinions on the sounds I linked? I can keep looking if you're not happy with them :smile:

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
