### ISSUE TITLE
Clear conversation, deleting only the content

### ISSUE THREAD

**Issue by PanderMusubi** [signalapp/Signal-Android#6328]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As is found in other popular instant messaging software, offer clearing a conversation by deleting the messages (in bulk) inside, but keep the conversation available even though it is empty. Now it is deleted, but when it remains, it can be used quickly for writing new messages without having to search for a contact first.

### Steps to reproduce
- have a conversation
- delete all the messages
- the conversation disappears by deletin the last message in it

**Actual result:** The conversation disappears
**Expected result:** The conversation remains, although empty. This clearing action should be available with longpress on a conversation or from the menu within a conversation. In the app and in the web gui. For groups, probably some small variation is needed, but the same functionality is requested for that too.

PS I have searched the open and closed issues for something similar but could any on exactly this.

### Device info

**Device:** n/a
**Android version:** n/a
**Signal version:** n/a

**Comment by 2-4601** [comment]
Related #6038.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
