### ISSUE TITLE
MMS doesn't fully notify until app opened

### ISSUE THREAD

**Issue by onehalfMVsquared** [signalapp/Signal-Android#6332]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
MMS messaging does not download or fully notify until after app opened. Upon receiving a MMS message, LED and notification icon both appear but notification sound/vibration does not occur and message does not download. Messages can then go unnoticed until phone checked for other reasons. After opening signal or opening and unlocking signal, MMS messages promptly download as expected and only then does sound/vibrate occur. In the case of group messages they show as numerous new texts from individual users but then download sequentially and are placed in a single group automatically (time stamps indicate actual download time regardless of send time or how long they have been in limbo). Wi-fi connection does not seem to make a difference. After opening, MMS response time seems improved for short period and messages will download as expected. SMS and signal messages consistently alert with the notification as expect as soon as message arrives in all cases. 

MMS set to auto fetch all types in all situations in Signal settings
Signal "doze" turned off, background data unrestricted
pnf - no root app doesn't seem to help either
Issue is not new and has been occurring for some time which and has led to use of alternative messaging apps from time to time however built in and all other 3rd party apps work as expected

### Steps to reproduce
- allow signal to be idle for period
- receive MMS message
- failure of notification
- open signal to receive message and notification

**Actual result:** SMS and signal messages notify with sound/vibrate/LED and icon as soon as they arrive. MMS messages arrive but only result in icon and LED flash. Once signal opened, MMS downloads and sound/vibrate occur
**Expected result:** MMS message arrives and notification alerts per phone settings just as with a SMS or signal message regardless if recently opened

### Device info

**Device:** Samsung Note 5 - Verizon (SM-N920V)
**Android version:** 6.0.1
**Signal version:** 3.30.4

### Link to debug log
https://gist.github.com/7a8fc709485afbc2c9ae96ed530c716d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
