### ISSUE TITLE
Message Notifications disappear when also using Signal Desktop App

### ISSUE THREAD

**Issue by SwartzCr** [signalapp/Signal-Android#6338]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Message notifications get marked as read immediately, and sometimes don't cause the phone to vibrate. The result is that all incoming messages are marked as read, and I have to manually go into signal to see if I've received any messages.

### Steps to reproduce
- Have Signal open on a phone and on the desktop client
- get a message (while the computer is asleep)
- watch as the notification appears on the lock screen and then immediately disappears.

**Actual result:** messages get marked as read immediately removing the notification
**Expected result:** The message notification should stay on my lock screen and the message should be marked as unread.

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.30.4

**Comment by 2-4601** [comment]
Strange. Just tested this by suspending my laptop and could not reproduce.

**Comment by haffenloher** [comment]
@2-4601 I think this only happens when your desktop is running, Signal Desktop is focused and the conversation in which you're receiving messages is open

**Comment by 2-4601** [comment]
I guess I was confused by this step:

> - get a message (while the computer is asleep)

I assumed it meant that the computer is suspended (asleep).

Because otherwise it seems like the expected behavior to me: if Signal Desktop is active on a conversation, it should mark messages received to that conversation as read and reflect it on Signal Android.

**Comment by SwartzCr** [comment]
So computer was suspended, I had signal open, and watched a bunch of messages get loaded into the android app and then get marked as read. It happened to be the window that I had open on my computer, but the computer was closed.
here's the debug log: https://gist.github.com/anonymous/0d6a6ddf09605ab04fcf415d7b895f9b

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
