### ISSUE TITLE
Message switching sender and weird base64

### ISSUE THREAD

**Issue by remram44** [signalapp/Signal-Android#6342]
### Bug description
I (Remi) was on the desktop client (Chrome, MacOS) texting with Vicky (@VickySteeves, on Android).
In the middle of the chat, Remi gets a weird base64-looking message that is dated an hour back.
Suddenly, Vicky sees the last message Remi sent before that appears to have been sent by her.

### Screenshots
Remi on desktop:
![Remi on desktop](https://cloud.githubusercontent.com/assets/426784/23717142/a58268be-0400-11e7-88d2-c8707bf7df5a.png)

Vicky on Android:
![Vicky on Android](https://cloud.githubusercontent.com/assets/426784/23717524/2aebaeec-0402-11e7-928a-aedbcd33304a.png)

Remi on Android:
![Remi on Android](https://cloud.githubusercontent.com/assets/426784/23717530/34971a9e-0402-11e7-97ae-77f12ded3368.png)

Copied message content:
```
AHppBQOIp+geafFCFhvtfWMS+8HN3Bq5jlwkNPuk9m6a9uMUX/XvlQ6wXs/pm3H+HXnv0iVBJ6rg+w1jI2j+4y+ZqinwYK/sjVv6GneBMLGylrU1kjDaYypVAGXZ/Ne2GILGhtJPrzo=
```

#### Remi's Mac
**Device:** Macbook 2012
**MacOS version:** 10.12.3
**Chrome version:** 56.0.2924.87
**Signal version:** 0.32.1
**Signal log:** https://gist.github.com/remram44/261a25feb5ec703c91e7151defdcedf3

#### Remi's Android
**Device:** Google Pixel
**Android version:** 7.1.1
**Chrome version:** 56.0.2924.87
**Signal version:** 3.30.4

#### Vicky's Android
**Device:** LG G5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
