### ISSUE TITLE
Some media messages have a white preview thumbnail

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6346]
I have:
- [X] searched open and closed issues for duplicates using various phrases 
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some images have a white preview thumbnail when a caption is added

### Steps to reproduce
- Forward Image to another Signal conversation
- Add caption (caption removed in image)
- Send message

**Actual result:** Image thumbnail is white/blank
**Expected result:** Image thumbnail is displayed as it is done w/o a caption

### Screenshots

![screen shot 2017-03-08 at 1 47 56 pm](https://cloud.githubusercontent.com/assets/4898366/23725845/ff7bd85e-0406-11e7-952b-59e43fde5dcf.png)

### Device info

**Device:** Samsung Galaxy S Advance GT-i9070P
**Android version:** 4.1.2
**Signal version:** 3.30.4

### Link to debug log
 https://gist.github.com/34403e4fb79162045d07cc20d112176d

EDIT:
Adding log for user who experiences this w or without a caption for images from the attachment drawer: https://gist.github.com/287018f9e198fba3bbde7435df14c049

**Comment by waz452** [comment]
I've had similiar issues as well ...
Also noticed this via Facebook Messenger which uses the Signal backend

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
