### ISSUE TITLE
Location sharing doesn't work

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6351]
I'm running 3.31 without gapps. When I tap on the location sharing button, nothing happens. Is this expected?

Other apps, for example maps.me, are able to get the location even without gapps.
As maps.me is Apache licenses maybe it's possible to take something useful from there.

**Comment by rmueller83** [comment]
I think this is due to the dependency on Google Maps services in https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/components/location/SignalMapView.java which you are missing. In my opinion using standardized GEO URIs would be the best approach here, but my PR for displaying them was closed in favor of Google Maps https://github.com/WhisperSystems/Signal-Android/pull/4790

**Comment by vvug** [comment]
@rmueller83 but if I understand your PR correctly, that would mostly affect the receiver side of the location sharing, which would be able to easily open a `geo:` uri. As it is done now at least it is possible to open the google maps link in the browser.

The main problem in my opinion is on the "sharing" side, where there is no way to share the location without gapps. The only way is to open an external app and "share" the location to Signal.

**Comment by Be-ing** [comment]
This would require implementing an alternative location picker that does not rely on Google Maps. Refer to #5042

**Comment by Be-ing** [comment]
As a quick hack, the button for opening the location picker could be hidden if Google Maps is not installed. I think that would be a better user experience than showing a button that confusingly does not do anything.

**Comment by merge** [comment]
Signal 4.6.0 is still affected. Is there any plan to provide location sharing for users without google services?

**Comment by moxie0** [comment]
@merge Please try not to bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

If an issue is open it's open. If you want to express support for something that's already been said or documented, please use the "reactions." Thanks.

**Comment by belidzs** [comment]
I have Google Maps installed on my Xiaomi Redmi 4A, yet when I try to share my location, nothing happens for a second or two, then it looks like something is opening, but then it returns to the chat window.

[https://gist.github.com/anonymous/77c90a7c2a6cdf37960d0e52e03cddf3](url)

**Comment by Be-ing** [comment]
@belidzs: If you have Google Maps installed that is not the same issue. Open a new issue for that.

**Comment by belidzs** [comment]
@Be-ing just did that, thanks

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
