### ISSUE TITLE
Wrong message/warning order on safety number change

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6357]
When I receive a message from a contact that just reinstalled the app, I get the "safety number changed" warning, as expected. Once I accept it the order of what I see in the conversation in wrong: first I see the message I just received with the new safety number, then the "Your safety number with xxx has changed". It should be the other way around, to respect the chronological order of things:

1. Show the warning: Your safety number with xxx has changed;
2. Show the message: The message sent with the new safety number.

Running Signal 3.31.1 from the Play Store.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
