### ISSUE TITLE
Show an inline map instead of a Google Maps link

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#6361]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

It'd be nice if, instead of showing a Google Maps link, Signal displayed a map inline. This would improve the UX for location "attachments" quite a bit, IMO.

**Comment by piratenpanda** [comment]
OpenStreetMap would be an ideal match for most locations

**Comment by Be-ing** [comment]
Related: #5042

**Comment by haffenloher** [comment]
> It'd be nice if, instead of showing a Google Maps link, Signal displayed a map inline.

I'm sorry if I don't understand your request correctly, but doesn't Signal already do both (i.e. send a link together with a map)?

**Comment by strugee** [comment]
@haffenloher no, I'm pretty sure it doesn't - that's the point of this issue. I'll double-check though.

**Comment by strugee** [comment]
Huh, looks like I was wrong. For some reason I thought this didn't work.

**Comment by strugee** [comment]
Though on second thought, this seems to just be an image. It'd be nice if the map was actually interactive and let you open a map view by tapping on it, without actually leaving the app.

**Comment by paride** [comment]
@strugee There is a strong privacy reason for sending an image. Sending an "interactive map" means sending a location and having Signal (or an external library) query a server to load the map, leaking the exchanged location.

You could think of a "load location" button that prevents the map to auto-load, but this is basically how it works now, where the static image is the button.

**Comment by strugee** [comment]
@paride oh, that's a great point. So I see two alternatives here:

1. Keep the existing behavior
2. Use offline OpenStreetMap tiles, if available

I'll let Moxie or one of the other developers make the final call, but I'm betting on option 1.

**Comment by FeuRenard** [comment]
This was the commit message of the commit which introduced location sharing:
> Start with encoding as a simple image thumbnail for compatibility with MMS and iOS.

Source: bcf95e50aa38cae2dfe640ea1a1e26cbaa3a84b7
So I would say there's something on the roadmap.

**Comment by jeremymasters** [comment]
I think the idea is to sync up Android and iOS's attachment capability and then add more to both.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
