### ISSUE TITLE
Visual display for how many contacts are on Signal

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#6362]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

It'd be nice if Signal had a screen that would show e.g. a pie chart that indicated how many of my contacts were on Signal. Or how many of the messages I send are encrypted. Tapping an element of the pie chart would then show a list of people in that category - this would be a nice way to get an overview of contacts I still need to convince to convert.

There's probably also room for some gamification in here - the app could display something like e.g. "Almost there! :tada:" when most, but not all, of my contacts were using Signal.

**Comment by moxie0** [comment]
It'd be great if someone made a mockup for how this should look

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
