### ISSUE TITLE
First message as re-registration not marked as delivered

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6370]
### Bug description
After unregistering and re-registering, the first message I send to a contact gets delivered but not marked as such (the second "tick" does not appear).

### Steps to reproduce
- Register to Signal, send some messages to a contact;
- Unregister from Signal (do not uninstall the app, just unregister);
- Register again;
- Send a message to the same contact.
- Actual (buggy) result: Only one "tick" appears.
- Expected result: two ticks, as the message is actually 

From the second message everything works as expected (two ticks appear).

Runnig Signal 3.31.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
