### ISSUE TITLE
latency in video/audio calls

### ISSUE THREAD

**Issue by arunhappiest** [signalapp/Signal-Android#6378]
### Bug description
If I ring a mobile it takes 30 seconds to ring the recepient mobile, what is it doing for 30 seconds? where in in whatsapp it is just 1 second which i tested with same devices. voice also has 2 second latency.

### Steps to reproduce
call any mobile near by.

### Device info

**Device:** samsung
**Android version:**4.4 
**Signal version:** latest

**Comment by soloclub** [comment]
:+1:

**Comment by p4nci** [comment]
@soloclub wrong 👍

@arunhappiest actually, the newest changes ("peer-to-peer" connection for WebRTC calls) should reduce the call latency (see also https://whispersystems.org/blog/signal-video-calls/).
Do you have enabled a setting which will relay all calls through the Signal service?

**Comment by 2-4601** [comment]
Related #6176 (if I understood the description of this issue correctly)

**Comment by peter-sc** [comment]
My understanding is not the in-call latency, where you hear the other party 30s later and which should be much better with peer-to-peer WebRTC, but rather the "signalling latency".
I have the same issue, the second phone starts ringing after 30s of call initation. The first phone has 30s ringing tone. This way you thing the other party is not near the phone and you cancel the call.

**Comment by haroldfinch1984** [comment]
Hi,
yes. Signalling takes more than 30 seconds to ring the recipient mobile!!!!!
I made several test with different (phone-android 6.1). UMTS or LTE  network is the uninfluential , Network operator is the same uninfluential. Routing takes too long. After achieving connection...voice quality is very good. Relay calls through the Signal service is not enabled.  As Peter-sc said is " signalling latency" problem. Maybe is Related to #6176.

**Comment by haroldfinch1984** [comment]
Moxie said:
Might be slightly faster in 3.29.2, but this is largely the result of the ICE handshake and webrtc's infinite wisdom to use DTLS. We could make the device "ring" sooner, but then if you answered immediately there'd be a delay before you could talk (and there might be problems that prevent the ICE handshake from completing at all).
---
https://webrtc-security.github.io/
we have no hope for the future???

**Comment by haroldfinch1984** [comment]
Moxie said:
Might be slightly faster in 3.29.2, but this is largely the result of the ICE handshake and webrtc's infinite wisdom to use DTLS. We could make the device "ring" sooner, but then if you answered immediately there'd be a delay before you could talk (and there might be problems that prevent the ICE handshake from completing at all).
--------------------------
more on this....
https://webrtc-security.github.io/

we have no hope for the future????
 I am wondering how "other" app does!!!!!

**Comment by haroldfinch1984** [comment]
Moxie said:
Might be slightly faster in 3.29.2, but this is largely the result of the ICE handshake and webrtc's infinite wisdom to use DTLS. We could make the device "ring" sooner, but then if you answered immediately there'd be a delay before you could talk (and there might be problems that prevent the ICE handshake from completing at all).

more on this....
https://webrtc-security.github.io/

we have no hope for the future????
I am wondering how "other" app does!!!!!

**Comment by halb9** [comment]
> Related #6176 (if I understood the description of this issue correctly)

YES!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
