### ISSUE TITLE
Video calls should not continue transmitting video when call screen is not foreground view.

### ISSUE THREAD

**Issue by joshproehl** [signalapp/Signal-Android#6380]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When in a video call, if I tab out of the application, transmission of video should stop and the user I am talking to should see their contact image of me.

### Steps to reproduce
- Use latest android app.
- Call someone who is using latest iOS app.
- During video call go to the home screen, or task-switch to another app

**Actual result:** The iOS user I am speaking to should *NOT* continue to see what my camera is seeing.
**Expected result:** The iOS user I am speaking to is able to continue to see live video feed from my camera while I am in another application.

When the behavior is reversed, and the iOS user switches apps, the live video stops and I see their user icon, so this appears to be the correct expected behavior.

It's possible that it would be useful to continue transmitting video while switched to another application, *especially* if #6279 is implemented, however this should be something that must be user-enabled each time. (other video chat apps have set the standard that video transmission pauses once the app is backgrounded.)

### Device info

**Device:** Moto X Pure 2015
**Android version:** 6.0
**Signal version:** 3.31.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
