### ISSUE TITLE
Can't open signal: Failed to open database

### ISSUE THREAD

**Issue by JulienPalard** [signalapp/Signal-Android#6382]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Can't open signal due to a "Failed to open database"

### Steps to reproduce

Seriously I don't know, signal was working fine, now it crash while starting.

### Device info

**Device:** Nexus 6P
**Android version:** 7.1.2
**Signal version:** 3.31.4

### Link to debug log

https://paste.debian.net/hidden/33db2b18/

**Comment by JulienPalard** [comment]
I tried to erase cache and data from the android preferences → application → signal → storage and a force close, it did _not_ fix the issue.

I tried uninstall / reinstall, it fixed the issue although it's the exact same version.

**Comment by jeremymasters** [comment]
What version did you upgrade from?

**Comment by JulienPalard** [comment]
From 3.31.4 to 3.31.4 when I uninstalled / reinstalled.

Previous version unknown (If it's an upgrade that caused the issue, which is probable) but my Android is auto-upgrading apps on Wi-Fi and I'm almost always on Wi-Fi, so probably just the latest published version on the Android Play Store.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
