### ISSUE TITLE
Missed "leave group" event will eventually get member re-added to groups

### ISSUE THREAD

**Issue by dnesting** [signalapp/Signal-Android#6394]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This is somewhat of an extension of #6177 with additional consequences.  I changed phone numbers and devices, added my new number and removed my old number from a few large groups.  A small fraction of group members didn't receive the update (maybe due to key changes, but I don't know).  Some weeks later, these group members have updated the group to add new members or change the group name, and this had the practical effect of propagating their device's view of the member list to everyone else in the group, resurrecting my membership and exposing the new owner of my old phone number to group messages.

#6177 mostly describes a nuisance of continuing to receive messages from people that didn't get your "leave group" event.  My issue feels more like a security concern, since my old group membership gets re-propagated to everyone in the group even if I don't have control of the original device or number anymore.

### Steps to reproduce
- join a large group
- have a member of the group change their key and don't accept the change
- leave the group
- observe that most members no longer see you're a member
- cancel your phone service and recycle your phone
- have the member that didn't get your "leave group" event make a change to the group

**Actual result:** The previously-left number is re-added to the group
**Expected result:** The previously-left number should get propagated somehow to the group member that didn't get the memo and the old number should not be re-added to the group.

### Device info
**Device:** Google Pixel XL  
**Android version:** 7.1.1  
**Signal version:** 3.31.4

**Comment by bisam** [comment]
could this somehow be connected to #4520 ?

**Comment by travisthomas** [comment]
#4520 sounds likely to be connected, although that report does not state that a key change occurred, which is the crux of this bug. 

I can see a few possible fixes: 

1) Mark the conversation/group as "dead" and any new messages in that thread, discard. This only affects the local device and only occurs after user deliberately leaves the group.
2) Always accept unsubscribe messages even if the security keys aren't user-accepted. This would keep group membership lists more accurate and prevent the sending of unwanted messages. It is somewhat tidier, but probably presents a greater security risk.
3) Some sort of consensus implementation for group membership.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
