### ISSUE TITLE
Libc segfault when initiating video calls (not BETA)

### ISSUE THREAD

**Issue by SamClarke2012** [signalapp/Signal-Android#6396]
I have:
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
Crash (libc **segfault**) on video call (not beta).
### Steps to reproduce
- Attempt to initiate a video call between two freshly updated apps

**Actual result:** Fatal error. Log points to;
`F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 10767 (Thread-6)`

**Expected result:** Call should be placed using allocated memory.

### Device info

**Device:** LGE Nexus 5X (bullhead)
**Android version:** 7.1.1 
**Signal version:** 3.31.4

### Link to debug log

https://gist.github.com/anonymous/ab20402476965a511a08c36cd325e64f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
