### ISSUE TITLE
Feature request: display contact nickname instead of full name

### ISSUE THREAD

**Issue by clarcharr** [signalapp/Signal-Android#6401]
It would be nice to be able to have conversations show a nickname, e.g. "Mom" instead of "Jane Smith." This also provides a security benefit because people looking over your shoulder won't see people's full names if it's enabled.

**Comment by 2-4601** [comment]
Related #6211, https://github.com/WhisperSystems/Signal-Android/pull/6260#issuecomment-287212708, #5717.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
