### ISSUE TITLE
It is not possible to set a group avatar

### ISSUE THREAD

**Issue by Deccoy** [signalapp/Signal-Android#641]
Hello,

thanks for your great work.

On my CM11 phone it is not possible to set a group avatar. Clicking on the empty group avatar wil open the "image selecting form", but whatever i choose, the group avatar stays empty after selection.

Bedt regards,
Deccoy

**Comment by richardwonka** [comment]
I’m seeing the same behaviour on iOS18.3.1

**Comment by greyson-signal** [comment]
Hi there, this is the Android repository. You can report issues for the iOS app here: https://github.com/signalapp/Signal-iOS/issues
