### ISSUE TITLE
Manual MMS Settings Missing

### ISSUE THREAD

**Issue by interfect** [signalapp/Signal-Android#6417]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The underlying problem is that my MMS messages are not being sent correctly in a group chat. My contact says that "I can see some of your message until I open it up. Then the phone converts it to a MMS & I can no longer see what you said.".

I am using Sprint, and on some other issues I saw that on Sprint it may be necessary to go into Signal's manual MMS settings and set a different MMS server from whatever it defaults to.

However, the manual MMS settings are missing on my copy of Signal. Under Settings -> SMS and MMS, I have only three options: "SMS Enabled", "SMS delivery reports", and "'WiFi Calling' comparability mode". There also does not appear to be any relevant option in the "Advanced" section if the settings.

Searching the source code for "Manual MMS Settings" reveals a bunch of hits, so I assume the settings have not been removed, and that they are just not appearing on my device.

How do I make the manual MMS settings appear so I can apply the Sprint MMS workaround?

### Steps to reproduce
- Have a Sprint LG G2
- Open Signal's SMS and MMS Settings

**Actual result:** No Manual MMS Settings option appears
**Expected result:** A Manual MMS Settings option should appear

### Screenshots

http://m.imgur.com/QmuD83z
### Device info
**Device:** LG G2
**Android version:** 5.0.2
**Signal version:** 3.31.4

### Link to debug log

https://gist.github.com/660f15e53aa9639df0d16afd6fed2465

**Comment by haffenloher** [comment]
This means that Signal is using Android's new API for sending MMS. You can simply use the phone's settings and set the correct APN details there.
For further assistance check out https://support.whispersystems.org, support@whispersystems.org or visit the [unofficial forums](https://whispersystems.discoursehosting.net/).

**Comment by interfect** [comment]
The settings app on this particular phone does not expose the APN settings. It's not under "Roaming" or "More" -> "Mobile Networks".

**Comment by interfect** [comment]
The underlying issue I am trying to solve looks to be #2143.

**Comment by FeuRenard** [comment]
#2143 seems to be fixed for others. So is this for you @interfect , too?

**Comment by interfect** [comment]
I haven't been using group MMS recently. I've also ditched the offending
phone without APN settings. But if it can, Signal probably should expose
APN settings when the phone doesn't.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
