### ISSUE TITLE
New group member resets the disappearing messages timer

### ISSUE THREAD

**Issue by paride** [signalapp/Signal-Android#6421]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a new user is added to a group for which a disappearing messages timer has been set, the first message the new users sends also resets the timer ("NewUser set disappearing messages time to Off").

### Steps to reproduce
- Create a group with a couple of users;
- Set a disappearing messages timer and test it;
- Add a new user to the group, *note that the new user doesn't see the timer as set*;
- Have the new user send a message to the group *before any other user*.
- This message disables the timer for everybody.

**Expected result:** The new user sees the timer immediately after being added to the group.

This doesn't happen if the new user receives a message before sending anything. In this case s/he gets the timer information.

Edit: the same problem occurs when linking a desktop client and sending a message to a group from it. In this case it seems that receiving a message is not enough for getting the right timer information: the first message sent from the desktop client still resets the timer.

### Device info

**Device:** Nexus 6
**Android version:** Stock Android 7.1.1
**Signal version:** 4.0.0-play

**Comment by mfc** [comment]
I can confirm this bug -- in the cases I have seen, it happens even without the new user sending the first new message.

It resets as soon as the new user was added, and from the group it is communicated that the user who added the new user has reset the counter (even though they did not).

It requires a lot of vigilance for this not to result sensitive messages that can never be deleted from being shared to the group.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
