### ISSUE TITLE
Improve search for non-contacts

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-Android#6424]
We recently made some improvements in Signal-iOS around searching for non-contacts by phone number.  I suggest we have parity on Android.

* https://github.com/WhisperSystems/SignalServiceKit/pull/130
* https://github.com/WhisperSystems/SignalServiceKit/pull/139

Let's say user has a US phone number like +12045002827.  They should be able to search for another US phone number like +17043264096 by entering any of:

* +17043264096
* 17043264096
* 7043264096 

They should also be able to search for a non-US phone number like +441733530267 by entering any of:

* +441733530267
* 441733530267

IMO we should try prepending the calling code for the current user's phone number ___and___ the calling code that corresponds to the default region for the current device.  I'm not sure how this works on Android, but on iOS users specify their language and region preferences as a system setting.  So for a user living in the US (With a US phone number) but who is Scottish and like seeing dates and times, etc. formatted in UK way and thus uses the UK region, we should try both US and UK calling codes since they are likely to look up users in both places.

**Comment by charlesmchen** [comment]
Specifically Riya recently couldn't find my UK device +441733530267 on her android device with a US phone number.

https://gist.github.com/anonymous/5b868ca9386c3b0c593ecc6e4fd0d81d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
