### ISSUE TITLE
"SomeUser updated the group" message still confusing

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6425]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Sometimes in group conversations I get the message "SomeUser updated the group". This is quite confusing: what was actually done? My guess is that nothing is actually done, otherwise I'd see a more specific message, like: "group name changed", "new user added". The group settings has just been refreshed. I see two possibilities for improving this:

- Change the wording to something like: "SomeUser refreshed the group properties"
- If nothing actually changed on the side of the user receiving the "group update", just suppress the message, otherwise specify what has been updated. Of course this would be the best option.

### Device info

**Signal version:** 4.0.0

**Comment by Trolldemorted** [comment]
I don't think the latter is the best option - if a user sends a "refreshing" group update and looks on a member's device, he will expect to see something there, otherwise he could (i would) consider the message as not successfully sent.

**Comment by vvug** [comment]
@Trolldemorted I understand, but if you didn't change anything, why expecting to see anything?

Another way is removing the possibility to send "update group" messages if nothing was changed at all. But I think that's still useful, as sometimes groups are out of sync.

I also noticed that when the group icon (avatar? whatever) is changed the vague "group updated" message is shown. A more precise message ("User X changed the group icon") should be shown instead.

**Comment by Trolldemorted** [comment]
I'd expect that there is a message telling me that the device has received an update, but the update did not cause any changes, just as you have described in your first option.

:+1: for avatar change text references

**Comment by vvug** [comment]
And ￼:+1: for showing the "update received, nothing changed" message. I now agree it's the best option.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
