### ISSUE TITLE
Fatal exception attaching / sending image.

### ISSUE THREAD

**Issue by SamClarke2012** [signalapp/Signal-Android#6426]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A fatal exception was triggered whilst attaching an image, brake-pad reports an attempt to invoke a virtual method on a null obj. App log reports skipping image preview due to a zero width preview size, followed by a (remote) file not found error with **MessageSender**.

### Steps to reproduce
- Take image with native camera app
- Crop image with native camera app - Final size is 902x1218 @ 257KB
- Use attachment drawer to attach image from system storage, noting that the pre-send preview is working
- Enter text to caption the image, hit send and note that **no** image / message content is rendered (no apparent relation to existing gray box issues)

**Actual result:** No message is sent 
**Expected result:** Message is sent

### Device info

**Device:** LGE Nexus 5 (hammerhead)
**Android version:**  6.0.1 (3437181, M4B30Z)
**Signal version:** 3.31.4

### Link to debug log

https://gist.github.com/anonymous/43e68ca1823543f69545a12555df6e9b

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
