### ISSUE TITLE
Group avatars: pinch-to-zoom / taking pictures / easy identification

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6429]
A missing feature: taking a picture to set the group avatar, and the ability to pinch-to-zoom when selecting which part of an existing image use as an avatar.

I also think it should be easier to identify groups in the conversations list, for example by superimposing the "two human figures" icon to the group avatar.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
