### ISSUE TITLE
contact flashing, kyboard blinkink

### ISSUE THREAD

**Issue by fikaficho** [signalapp/Signal-Android#6433]
Device  : HUAWEI HUAWEI P6-U06 (P6-U06)
Android : 4.4.2 (C00B520, P6-U06V100R001C00B520)
Memory  : 22M (20.25% free, 256M max)
Memclass: 192
OS Host : localhost#1
App     : Signal 4.0.0

contact flashing, alyernately flashes betwen the name and the contact number
kyboard blinkink between uppercase and lowercase letters, 
omits characters when writing, 
no transmission parameters for MMS messages from default andrid app

unfortunately, it does not work well

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
