### ISSUE TITLE
Speech bubble color in conversation overview too dark

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#6438]
Sorry for the nitpicking. I like the new icons, except for the one in the conversation overview. It is too dark and uses a color which nowhere else can be found. I think it would be better if it uses the same color as the string "Signal" next to it (so white) or the same color as the logo/icon. This would look "friendlier".

![signal icon](https://cloud.githubusercontent.com/assets/17936066/24322277/5ded3c14-1160-11e7-87e1-414188e8f938.png)

I'm not interested in a discussion, so feel free to close this if you disagree.

**Comment by FeuRenard** [comment]
This issue occurs due to the transparency of `actionbar_icon_holo_dark`. The bubble itself should definitely be solid white, The color/transparency of the fringe could be both, I am undecided.

cc @iadmir

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
