### ISSUE TITLE
External app sending SMS created a new thread instead of using existing

### ISSUE THREAD

**Issue by snaggen** [signalapp/Signal-Android#6446]
### Bug description
Strava have a feature called "beacon", where it sends a sms with a link so someone can follow my ride. When I sent such a beacon to my wife, I got to choose which SMS-app to use (it is not using any general share mechanism, it seems to be trying to send a SMS). I then selected Signal, and got a new secure conversation to my wife where I sent the message. It seems that she received the message, so that part worked. However, the strange part is that I already have a secure conversation thread with my wife, so I would have expected that thread to be used for this message also instead of creating a separate thread. 

### Steps to reproduce
- Setup Strava to send a beacon
- Start recording a strava session, then click send beacon
- Select Signal to send the beacon

**Actual result:** A new conversation thread is created
**Expected result:** Signal should open existing conversation thread for the user. 

### Device info
**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.1.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
