### ISSUE TITLE
duplicate groups

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#6448]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
User sent image to group with poor connection. Group member responded. Thread list looked like this afterwards:

![signal-2017-03-27-095226](https://cloud.githubusercontent.com/assets/10261186/24354110/f37f58f2-12f0-11e7-8b3f-10f992bdd720.png)

As you can see, the group is listed twice. New incoming messages arrive in the new one (but old messages are only in the old group), new outgoing messages arrive in both.

After a reboot the old group appears with a new name ("+X" where X is a set of numbers) and the group avatar is gone. The old group can no longer be used to send signal messages, it displays the "enable signal for sms" button.

### Device info

**Device:** Xiaomi HM 1SW (armani)
**Android version:** 7.1.1
**Signal version:** Signal 4.0.0

### Link to debug log

https://gist.github.com/anonymous/0833749e245fe91bfda6ca7712f5a7a1
Since the debug log contains only **four** minutes, it contains no useful info as the incident happened before.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
