### ISSUE TITLE
Improve voice messaging

### ISSUE THREAD

**Issue by Lesik** [signalapp/Signal-Android#6455]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Several things should be improved (imho) to make voice messaging as enjoyable as with similar popular messaging services:

- The voice messages' lengths should be displayed next to the them. I always listen to short voice messages even if I don't have much time because I see it won't take long. With longer voice messages, I usually dedicate some time in my day to listen to them later. But one has to know how long the message is going to be before playing it back. Another argument is that when receiving more voice messages than fit on the screen, and listening to them one-by-one, it's easy to loose your current position in the messages if they can't be distinguished from each other. Currently, it's only the timestamp that distinguishes them, often displaying the same time for multiple messages (because they were sent in the same minute) or a very similar time with only a minute difference, which makes it easy to loose your current position. A competing messenger [solves the issue of indistinguishable voice messages with sound graphs](https://telegram.org/file/811140355/1/WIZMMGf4N0o/42aafb28995492f57c).
- Rotation should be locked when recording starts. Currently, accidentally tilting your phone while recording rotates the screen and stops the recording. This is especially annoying since voice messaging is mostly used in situations where one can't type well, e.g. when walking on the street, eyes on the road instead of looking at the phone. In this position one doesn't pay much attention to how one is holding the phone because one is concentrating on the surroundings, resulting in accidental tilting that aborts the recording.
- Recording voice messages without an active internet connection is a pain, for example on train rides or on vacation. Once a voice message is recorded, it can't be played back until it has been delivered to the server. Re-listening to what one has just said (to avoid repeating oneself) is impossible until the internet connection is reestablished. Instead of replacing the play button with a Spinner (I mean the Android View) to indicate the message is being sent, thus making it unplayable, just display a "..." animation like with text messages.
- I am unsure if this is already implemented and just doesn't work for me, but holding your phone to your ear or otherwise blocking the proximity sensor doesn't switch audio playback to the earpiece. It works with competing messengers though.

To conclude, a word of compliment: It seems like when sending multiple voice messages with no internet connection, then reconnecting again, sends the messages in the order they were recorded. Some competing messengers do not care to save the order, usually resulting in the smallest/shortest voice message being sent first, and so on, resulting in a weird order that confuses the receiver.

**Comment by sedroar** [comment]
I'm having the same issue when holding the phone on my ear. Message is not played.

**Comment by primeapple** [comment]
@Schweineschwarte, I think this bug is described in #6097

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
