### ISSUE TITLE
Use single button to open attachment window.

### ISSUE THREAD

**Issue by wayloncovil** [signalapp/Signal-Android#6457]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In the conversation window, there are 3 ways to open/close the attachment window.

### Steps to reproduce
The paperclip will open and close the attachment window.
The green down arrow (that is visible in the attachment window) will close the attachment window.
The ellipses in the upper right of the conversation window have an option to open the attachment window.

**Actual result:**
As described above.
**Expected result:**
From a usability and attractiveness perspective, there should be only a single way to open and close the attachment window.

### Screenshots
See the [thread on Discourse Hosting](https://whispersystems.discoursehosting.net/t/conversation-window-ui-tweak/895) for screenshots and discussion of alternatives.

### Device info
**Device:** Moto X Pure Edition
**Android version:** 6.0.0
**Signal version:** 4.1.0

**Comment by mftruso** [comment]
Thanks @wayloncovil It is confusing when you start typing a message and the paperclip icon goes away. Until reading this issue I didn't know there was another way to add an attachment from the upper-right ellipsis.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
