### ISSUE TITLE
Feature Request: Use Share Intent Subject When Sharing to Signal

### ISSUE THREAD

**Issue by fbis251** [signalapp/Signal-Android#6459]
At the moment, sending a share Intent to Signal will include the `EXTRA_TEXT` portion of the Intent but not the `EXTRA_SUBJECT`

For example, using this code from another app
``` java
Intent sendIntent = new Intent();
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_SUBJECT, "This is the intent title");
sendIntent.putExtra(Intent.EXTRA_TEXT, "This is the intent body");
sendIntent.setType("text/plain");
startActivity(Intent.createChooser(sendIntent, getResources().getText(R.string.send_to)));
```

Signal will only use the body: `"This is the intent body"` but not use the subject: `"This is the intent title"` 

This would make it easier to get page titles and other subjects shared from browsers and other apps that set the share Intent's EXTRA_SUBJECT

**Comment by PiCob** [comment]
Related: #5959 regarding (dis)advantages of using EXTRA_SUBJECT

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
