### ISSUE TITLE
International (Vanuatu) phone number coerced to same country

### ISSUE THREAD

**Issue by stephzylstra** [signalapp/Signal-Android#6460]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I was sent a link to a Vanuatu phone number in +678<number> format (where 678 is the country code). Clicking on that link to message the number opened a conversation to +61678<number> - i.e. despite the + at the beginning of the number, the number was coerced to an (invalid) Australian number.

Saving the number as a contact allowed me to start a Signal conversation with the correct number.

### Steps to reproduce
- have Signal as default SMS app
- Receive a Vanuatu phone number
- click on the phone number link and choose the SMS option
- Notice that the number has been coerced to different number

**Actual result:** The number was treated as a +61 (Australia) number instead of a +678 (Vanuatu) number
**Expected result:** The phone number would be the same as the one clicked on, i.e. a +678 (Vanuatu) number

### Screenshots
1. Link shows the number in +678 format
![screenshot_20170330-090747](https://cloud.githubusercontent.com/assets/735413/24500212/d76f47e6-1587-11e7-914b-4e6267abb3ca.png)

2. Conversation opened by clicking that link shows the number as a +61 number
![screenshot_20170330-090817](https://cloud.githubusercontent.com/assets/735413/24500224/e4d00650-1587-11e7-8dff-5879558d15b2.png)

### Device info

**Device:** Google Pixel
**Android version:** 7.1.1
**Signal version:** 4.1.0

### Link to debug log
(I was at work at the time so this was taken later - sorry!)
https://gist.github.com/6091eb4e268a625c04a4b5869451385a

**Comment by stephzylstra** [comment]
I am aware Vanuatu is listed as one of the countries where registration doesn't work (https://github.com/WhisperSystems/Signal-Android/issues/6027) but I'm just trying to use it for SMS, not Signal registration

**Comment by kepish** [comment]
I have also experienced this issue. I was sent a message containing a Finnish phone number via Signal, and it was coerced to a U.S. number in the same manner as described above (had a "1" prepended to the number, so it was +1358 instead of +358). My Signal account was registered with a U.S. phone number, and the phone was purchased in the U.S., but I am currently using a Finnish SIM card.

**Device:** Google Pixel
**Android version:** 7.1.2
**Signal version:** 4.8.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
