### ISSUE TITLE
Failed to send message 

### ISSUE THREAD

**Issue by jstoner** [signalapp/Signal-Android#6461]
I have:
- [ X ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Trying to send a message, I get a 'failed to send' message when I click for details when it fails, and it fails reproducably. 

Recently I had an interruption in my cell service (stolen credit card, had to change the number, provider shut off recurring billing, service expired, no SMS). That got resolved yesterday. I don't know if that has anything to do with the current failure,but this use case is very straightforward, so it should work. 

### Steps to reproduce

- type message to person 
- hit send

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

There is an exclamation point to the right and a not delivered message and a tap for details message in the lower right. I tap and see 'failed to send.'  
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The message sent. 
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://gist.github.com/511954b54edfd41f83a29a58ec9dc61e

**Comment by moxie0** [comment]
The client isn't able to negotiate a secure TLS connection with the server because it looks like some middleware is trying to redirect the connection. I assume it's a captive portal or something, are you sure you have an active data connection?

**Comment by jstoner** [comment]
Yup, that wasn't a problem. As I recall I googled my error message soon after. I also submitted the log so that much did work.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
