### ISSUE TITLE
 Message appears multiple times (Group, 3 members, 2 Signal, 1 SMS)

### ISSUE THREAD

**Issue by wem** [signalapp/Signal-Android#6462]
### Bug description
In a group with 2 members they are using Signal and a non Signal user. A Signal user sent a message (non-Signal message type explicitly chosen), the other Signal member got the message multiple times ... the non Singal user just once. Neither, deletion of the group, peer2peer chat / re-installation of Signal on producers device, or the deletion of peer2peer chat on the Signal receiver device solved the problem ... The message still appears from time to time.

### Steps to reproduce
- Create a group with 2 Signal members and a non Signal member
- Send a non-Signal message from a Signal device

**Actual result:** Message appears multiple times (over several days) on the second Signal device within the group.
**Expected result:** Message get sent to each device only once.

### Device info "Message producer"
**Device:** Samsung S4
**Android version:** 5.0.1
**Signal version:** 4.1.0

### Device info "Signal receiver"
**Device:** Samsung S7
**Android version:** 7
**Signal version:** 4.1.0

### Link to debug log
Sorry, group, peer2peer chat already deleted.

**Comment by siragi** [comment]
Same problem here. Non-signals sending images to signal ends up in resending the images multiple times from the csp.

**Comment by deValmont** [comment]
Same problem here

Carrier: Swisscom/Switzerland and Orange/France
Phone: Huawei Mate 9
Signal: 4.6.1.

**Comment by deValmont** [comment]
Still no solution ? This bug is very annoying, I keep on getting the same MMS again and again. This only happens when sent by people not using Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
