### ISSUE TITLE
Video Call - video is green tint on other person phone

### ISSUE THREAD

**Issue by rainfarmer** [signalapp/Signal-Android#6463]
### Bug description
When making a video call, my video has a green tint on the other person's phone.
On my screen the video looks normal.
Recording with same camera in different app has no green tint.

### Steps to reproduce
Any video call, initiated or received.
Only tested with calls between an android and iphone.

**Actual result:** My video has green tint on other user's phone.
**Expected result:** Video should look similar to how it looks on my phone, no green tint.

### Device info

**Device:** HTC One X
**Android version:** 4.0.3
**Signal version:** 4.1.0

**Comment by nrizzio** [comment]
@rainfarmer please capture a log after performing a video call and reply with a link here

**Comment by rainfarmer** [comment]
https://gist.github.com/182872f12dc7e2d8b2cb7eae526de6cf

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
