### ISSUE TITLE
Iran Censored Signal Again!

### ISSUE THREAD

**Issue by GameO7er** [signalapp/Signal-Android#6468]
Hi AFAIK In This Issue #5992 Iran Censored Signal and It Seems Problem Solved Here #6006
As We Can See In This Link :
https://github.com/elliptic1/Signal-Android/commit/af0ff7d7618425d8aa63da98ab474ccd47dae387
But I Installed v 4.1.0 From Google Play Recently And When Try To Enter My Phone Number and Receive Message The App Shows Me "Signal Was Unable To Connect To The Server".
The Problem Solved When I Used L2PT VPN USA Country.
This Mean Unfortunately Iran Censored Signal Again So Please Solve This Issue Again.
Thanks In Advance

**Comment by johanw666** [comment]
From what I understood from the discussion then, Google blocks the domain fronting functionality from Iranian IP's.

**Comment by GameO7er** [comment]
@johanw666 
How About Other Websites That Provide Domain Fronting?
I Searched Recently and It Seems Other Sites Also Provide This Service Like Akamai , Amazon and etc.
Of course Amazon is Already Censored In Iran! Anyway Iranian People Need This Messenger Specially The President Election Is Near About 1-2 Months .BTW Must be a Solution! For This Issue!
Thanks In Advance
Regard

**Comment by johanw666** [comment]
AFAIK OWS  would have to make an agreement with one of the other services that offer domain fronting, and then code it in the app. I don't know how fast the first issue can be completed (putting it in the app is then trivial).

**Comment by aliforever** [comment]
Same issue.

**Comment by mrphs** [comment]
It's not about making agreements. OWS could switch to other providers like Amazon or Azure and that would fix this issue for millions of Iranians trying to get online.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
