### ISSUE TITLE
Neither SMS nor call registration works

### ISSUE THREAD

**Issue by rysiekpl** [signalapp/Signal-Android#6469]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unable to register -- SMS is not intercepted by Signal (and hence not used); `CALL ME` button does not seem to have any effect ("Requesting call" message pops up, but no incoming call is ever received).

I recognize Jolla is not supported, but previous versions (3.16.x for example) of (Libre)Signal used to work well. Registration via a call was possible.

A simple fix would be to allow manually typing the code received via the SMS (perhaps after clearly informing the user about the problems with this approach). The code does not currently seem to work with Voice Verification.

### Steps to reproduce
- install Signal on Jolla (using either Signal Website Release, f-droid, or LibreSignal)
- enter phone number when prompted
- receive SMS; SMS verification timeouts anyway
- tap `CALL ME`, expect a call with the code

**Actual result:** No call is ever received; tapping `CALL ME` multiple times ends in the "Too many requests!" message
**Expected result:** Incoming call with the code is received, registration can go through.

### Device info

**Device:** Jolla
**Android version:** 4.1.2 (alien dalvik)
**Signal version:** Website Release 4.1.0

### Link to debug log

No access to the debug log, since this happens before registration.

**Comment by GuiltyPixel** [comment]
Confirmed on LineageOS 14.1 nightly on d2tmo (Android 7.1.1) using a Google Voice number. This is really frustrating, why can't I type the code...

**Comment by moxie0** [comment]
Can't reproduce, what country is this in?

**Comment by rysiekpl** [comment]
Poland, and Bosnia and Hercegovina here. Tried with both Polish and Bosnian numbers, physically both in Poland and in BiH (so, 4 combinations).

**Comment by moxie0** [comment]
@rysiekpl Have you tried with a polish number recently?

**Comment by rysiekpl** [comment]
I have just tried with a Polish number, albeit while roaming in Bosnia. I finally got the call, it worked.

When I tried a few weeks ago there was no incoming call.

**Comment by 2-4601** [comment]
Bosnia and Herzegovina has been reported before #6027

**Comment by GuiltyPixel** [comment]
United States here.

**Comment by dziaineka** [comment]
Also neither SMS nor call registration works in Belarus.
Samsung S7 Android 7.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
