### ISSUE TITLE
Incoming calls over VPN take extremely long to "connect" (85-250s). (the VPN in question works well with other VoIP, i.e. plaintext calls with Groundwire + callcentric)

### ISSUE THREAD

**Issue by BurnySnek** [signalapp/Signal-Android#6485]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

If VPN is connected, Signal takes forever to connect an incoming call (up to 250 seconds, that 's long...)

The VPN is shadowsocks-based, tested for general VoIP compatibility via Groundwire client and callcentric's VoIP service, with very good results, under 5s from call initiation to call connection, good quality.

The issue was also replicated on Mullvad VPN with usual android OpenVPN client (exactly same behavior)

So it is not an issue specific to a particular VPN implementation or server/client config.

Also, it's not a push issue groundwire uses push too
Also, to further verify it's no a GCM/push issue, PNF Root app was installed and yet another incoming call via Signal was attempted.
With other person trying to Signal-call the phone behind VPN, phone showed  no signs of being called for 149 seconds, while, during all this time, the GCM log courtesy of PNF Root app showed numerous push messages from whispersystems/Signal

NB: Signal text messages are not affected and are delivered instantly

### Steps to reproduce
- Install an android VPN (any Shadowsocks or OpenVPN one seems to do)
- connect it
- test that signal works by exchanging text messages
- try to call the phone behind VPN

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The incoming call takes unreasonably long to connect

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Somewhat more reasonable time between "other party initiated call" and phone actually ringing. Maybe like, 5 - 15 seconds

### Device info

**Device:** Tested and reproduced on Samsung Galaxy S6 edge, Xiaomi Redmi Pro, Elephone P7000
**Android version:** Different android versions, Android 6 on Samsung Galaxy S6 edge, various Android 5 (vendor ROMs) on Xiaomi Redmi Pro, Elephone P7000
**Signal version:** 4.1.0

**Comment by BurnySnek** [comment]
I will also capture a "clean after reboot" device log on a Xiaomi (Android 5.0) device closer to Friday.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
