### ISSUE TITLE
Non existing phone numbers in group

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#6491]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I have a group that contains invalid phone numbers (contacts). These numbers are valid numbers prefixed with the country code of the country where the person that added the contacts resides.
I do not know exactly how to reproduce this issue.
The erroneous numbers end with: 567 and 699, see the debug log:
https://gist.github.com/25cceef1447bd60944e6dfb62944a4d4
(note that the same numbers in their correct form are also part of the group)

Maybe it might be an option to automatically remove incorrect numbers from groups, especially because there is no way to remove contacts (numbers) from a group (#3365).

**Comment by janvlug** [comment]
The phone numbers where the extra country code was added did not have the + sign in the stored number for the contacts. So probably therefore the extra country code was added.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
