### ISSUE TITLE
"Powered by Twilio" badge cut off in registration activity

### ISSUE THREAD

**Issue by nrizzio** [signalapp/Signal-Android#6492]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The "powered by twilio" badge at the bottom of the registration activity is cut off when "more information" is tapped or the phone is held sideways.

### Steps to reproduce
- open a new Signal client
- tap on "More Information" or hold the phone landscape
- scroll down as far as possible

**Actual result:** The "powered by twilio" badge is cut off
**Expected result:** The "powered by twilio" badge is not cut off

### Screenshots

![screenshot_1491351263](https://cloud.githubusercontent.com/assets/13669330/24684353/55d8f296-1973-11e7-8d47-d2d0464304c2.png)

![screenshot_1491351274](https://cloud.githubusercontent.com/assets/13669330/24684358/5c1849a4-1973-11e7-87fb-2ef360fb7749.png)

### Device info

**Device:** Nexus 5 (Virtual device)
**Android version:** 6.0.1
**Signal version:** 4.2.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
