### ISSUE TITLE
"Say hello to secure video calls" notification after every update

### ISSUE THREAD

**Issue by slintes** [signalapp/Signal-Android#6493]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After every update there is a Android notification which says "Say hello to secure video calls" (exact text might differ, I translated the German text to English). I understand that this is a new feature which you want to promote, but this way it gets annoying. Seeing it once should be enough.

### Steps to reproduce
- install a version with that new feature and notification
- swipe that notification away
- wait for a new version and install it

**Actual result:**
notification reappears

**Expected result:**
no new notification

### Device info
**Device:** Nexus 5x
**Android version:** 7.1.2
**Signal version:** latest available on Play Store

**Comment by FaizKhan5** [comment]
May be you are reinstalling app so get that notification but in every update i am not getting any notifications

**Comment by slintes** [comment]
no, updates

**Comment by FaizKhan5** [comment]
Post a debug log immediately after next update.

**Comment by haffenloher** [comment]
I guess the key element here is step 2, "swipe that notification away" (instead of tapping on it).

**Comment by slintes** [comment]
yes, I think I didn't open Signal at all between updates (unfortunately nobody of my friends uses it actively :/ )

**Comment by moxie0** [comment]
I don't think we considered the case where Signal isn't opened between updates

**Comment by slintes** [comment]
At least in this case very few people like me are affected ;) Probably not worth doing something about this then. I will just tap on the notification next time. Thanks for your answers. Feel free to close this if also think it's not worth any action :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
