### ISSUE TITLE
real time (streaming) push to talk or PTT

### ISSUE THREAD

**Issue by travisfw** [signalapp/Signal-Android#6497]
I have:
- [x] searched open and closed issues for duplicates (#3563)
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
[From Wikipedia](https://en.wikipedia.org/w/index.php?title=Push-to-talk&oldid=765635499 ) 

> Push-to-talk (PTT), also known as press-to-transmit, is a method of having conversations or talking on half-duplex communication lines, including two-way radio, using a momentary button to switch from voice reception mode to transmit mode.

The term push-to-talk appears in #3563 but that issue seems to be about sending voice messages, and the way this feature is currently implemented is not the way the term PTT is commonly used. For PTT, voice should be streamed in real time.

PTT conversations could be left open for days or months, and at any given time no data is necessarily being transferred unless someone has their thumb on the PTT button.

### Why

PTT is a love-it or hate-it kind of feature. For me, it would be a major selling point that I could use to get a few more people onto Signal. For couples, families, hands-free driving, and teams who might otherwise use walkie talkies, this method of communication can be a far superior experience than extensive SMS, group calls, or frequent short phone calls.

### How

Having the phone suddenly blurt out a friend's voice is the main anti-feature. For this reason people need to be able to manage the state of being in a PTT conversation or not. Here's a draft sketch for how I imagine this working:

In order to be able to be heard live, the caller needs to first initiate a conversation through the menu in the SMS thread. When off, the interface would look and work exactly as it does currently, except for the new menu option to start a PTT conversation. The callee would accept the conversation either through a notification or an indicator in the SMS thread.

When a PTT conversation is active, the microphone icon would change to indicate that holding it will stream audio live, and a menu item for muting the conversation would be enabled. The three PTT conversation states would be **active**, **muted**, and **off**, with the only shared state being whether the conversation is active or not. When the user mutes a conversation, no indication is sent to the other party.

So long as the conversation is active, all incoming audio would be saved as audio messages the same way they currently appear in the SMS thread. When muted, the audio would not play until the user specifically listens to it. When unmuted, it would play live through the speaker phone. Details:

events ⇩ | states ⇨| - | - |
-|-|-|-
_ | PTT Active | PTT Off | PTT Muted
press and talk | stream audio to everyone in conversation | record audio and send as a file when finger lifted | same as PTT Off
receive stream | play audio live and also save as message | save audio as unread message, as if it was not streamed | same as PTT Off
receive audio message | same as PTT Off | same as existing behavior | same as PTT Off
user begins PTT | N/A | send PTT invitation, change state to PTT Active | N/A
user receives PTT invitation | ignore event | notification of PTT invitation | same as PTT Active
user accepts PTT invitation | N/A | state changes to PTT Active | N/A
user declines PTT invitation | N/A | send PTT hang-up to all members | N/A
user ends PTT | send PTT hang-up, state changes to PTT Off | N/A | same as PTT Active
PTT hang-up received | change state to PTT Off | drop pending invitation | same as PTT Active
PTT muted | change state to PTT Muted | N/A | N/A

There are multiple ways that the shared state of being in a PTT conversion can get out of sync, but with the event handling described in the above table, such issues will default to as if PTT is not active, and can quickly be resolved by ending and beginning the PTT conversation.

To me, the above seems like a minimal way to add this functionality on top of the existing interface without moving anything around, without forcing anyone to adopt, and without disrupting existing patterns of usage, and staying in-line with familiar patterns.

### Conclusion /TL;DR

Signal is uniquely positioned to offer secure walkie talkie style conversations to groups, teams, and families with the need for real-time communication in short bursts. The feature can be implemented with minimal UI changes and no disruption of existing usage patterns.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
