### ISSUE TITLE
Search should remove diacritics from search string

### ISSUE THREAD

**Issue by jmayday** [signalapp/Signal-Android#6499]
### Steps to reproduce
- open Signal and tap on pencil icon
- type your (Polish/Spanish/Hungarian) friend name using only English alphabet 

**Actual result:** As your Polish/Spanish/Hungarian name contains language-specific signs, Signal won't show contacts as diacritics are not ignored while searching.
**Expected result:** Signal should suggest contacts and don't strictly compare diacritics (should ignore diacritics. May map them to letters from English alphabet). Eg. if you type "agnes" Signal should suggest you "AGNÈS" if it exists in your contact list. 

https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringUtils.html#stripAccents-java.lang.String-

### Device info

**Device:** Samsung Galaxy S4 I9506
**Android version:** 7.1.1
**Signal version:** 2.4.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
