### ISSUE TITLE
app screen is aways blank; app is responsive;

### ISSUE THREAD

**Issue by shula** [signalapp/Signal-Android#6500]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

 - I installed Signal, but when I run the app, the app's screen is black / blank / empty.
 - also after a reboot - the app screen is not usable at all.
 - Android's top "fast-access" line is visible and working.
 - If I press at random locations on the screen, I sometimes see a country-list; After selecting a country, the screen returns to be blank. MEANING: the app works; just the screen is blank.
 - I have many other apps - they all work normally. It's just Signal.

### Steps to reproduce
- install the app
- run the app

**Actual result:** 
same as bug description

**Expected result:** 
the app screen of course.

### Screenshots
 - just... black ... with android's pull-down menu on top (time, battery, status, etc). 
 - Not even the wallpaper.

### Device info
**Device:** ZTE Grand S II
**Android version:** 5.1.1
**Signal version:** installed on 2017-04-06

### Link to debug log
 - can't get into settings or logs - because the screen is blank.

### related issues? ###
 - https://github.com/WhisperSystems/Signal-Android/issues/59  (sometimes blank)

it's not my screen exactly, but you get the point
![image](https://cloud.githubusercontent.com/assets/124651/24804156/d01319e2-1bad-11e7-8200-6dea7454776b.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
