### ISSUE TITLE
Hitting "Open directory" after saving media has no effect

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6503]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Hitting "Open directory" after saving media will have no effect if none of the installed file managers can handle a "resource/folder" intent. (see also #6164)

### Steps to reproduce
- Open conversation
- Scroll to an image/video/audio message
- Long-press this media message
- Choose "Save" from the context menu.
- A snackbar will pop up and offer an "Open Directory" action. Hit "Open Directory".

**Actual result:** Nothing will happen (if none of the installed file managers can handle a "resource/folder" intent)
**Expected result:** Don't offer "Open directory", if there's no app to perform this action.

### Tested file manager apps
Works as expected:

- ES File Explorer

Doesn't work:

- Amaze File Manager
- Built-in 7.1.1 file manager (Settings -> Storage -> Internal Shared Storage -> Explore)

**Comment by moxie0** [comment]
Do you know if there is an intent that would work with Amaze and the built-in file manager?

**Comment by FeuRenard** [comment]
Not yet 😏

**Comment by FeuRenard** [comment]
Folks here have the same problem:
https://github.com/syncthing/syncthing-android/issues/838

They complain about Android more and more hiding the file system from the users. I think, that this is not bad. A file manager is no app a user should have to use. iOS hides the file system completely: foolproof. Why don't we offer "Open file" instead? Then a gallery app would open for a saved image/video and a music player for a saved audio file and an appropriate app for a file of arbitrary type.
If there is no app to handle the file we could try to open a file manager like we do now.
If there is no appropriate file manager installed we could display the path.

**Comment by FeuRenard** [comment]
The snackbar was removed with f315b1db80f41089e3b8e492a765be305479c0e1.
