### ISSUE TITLE
Sharing a video from Photos shows an empty share screen

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#6506]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
1. Open the Photo app
2. Choose a video
3. Try to share it to Signal
4. This is as far as you can get: https://nup.pw/BjZPdv.png

**Actual result:** You can't choose a contact to share the video with
**Expected result:** Sharing pictures work, and so should videos.

### Screenshots
https://nup.pw/BjZPdv.png

### Device info
Device  : motorola Moto G (4) (athene)
Android : 7.0 (16, NPJ25.93-14)
Memory  : 55M (9.35% free, 384M max)
Memclass: 192
OS Host : ilclbld26
App     : Signal 4.2.4

### Link to debug log
https://gist.github.com/anonymous/47411aeb23d379e89b6a3680ffbaad64

**Comment by moxie0** [comment]
What happens when you tap the plus?

**Comment by Dyras** [comment]
@moxie0 A list of my contacts appear, when I press a contact the chat opens as if I've opened it from the "homescreen". No sign of the video whatsoever.

**Comment by Dyras** [comment]
@moxie0 When I attempt this exact thing now, Signal crashes every time. I still get to the share screen, but when I press back to get out of sharing the app crashes.
https://gist.github.com/anonymous/8b9cfc39987e1f790013b58f45f1603a

**Comment by Dyras** [comment]
Still happening, still super annoying.
https://gist.github.com/anonymous/706abfae5444d915c53841025cc0cec8

**Comment by Dyras** [comment]
Fixed now with the changes to the attachments 🎉

**Comment by Dyras** [comment]
Apparently not fixed, happened yesterday. Craaaap!

https://gist.github.com/anonymous/c4b0bb418e486b82c8e142cf0b5245fd

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
