### ISSUE TITLE
Percent-encoded SMS URLs are handled improperly.

### ISSUE THREAD

**Issue by praxiq** [signalapp/Signal-Android#6509]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When Signal attempts to open an sms: url in which the initial `+` sign is encoded as `%2B`, the way it interprets the URL is not in keeping with other SMS apps.

### Steps to reproduce
- Open the URL `sms:%2B18005551212` in signal.

**Actual result:** Signal creates a new message to +1218005551212. (Signal strips the % and B, then prepends +1 to the resulting number.)
**Expected result:** Signal creates a new message to +18005551212.

### Device info
OnePlus 3T running latest LineageOS

### Notes:
- Google's SMS app (com.google.android.apps.messaging) handles this url as described in "Expected Behavior" above.
- The sms: urls described in RFC 5724 use an actual + sign, rather than url-encoding the plus sign as %2B. As such, it's not clear whether my example URL should be valid or not. However, it is obvious how this URL is intended to be parsed, and some developers do create SMS urls this way.
- The Lyft android app is an example of an app that generates sms: urls with %2B in place of the plus sign. As such, this app works with the built-in SMS app, but breaks with Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
