### ISSUE TITLE
Forwarded audio or video files and voice notes can't be played on Desktop and iPhone

### ISSUE THREAD

**Issue by liliakai** [signalapp/Signal-Android#6510]
Summary: Forwarding a voice note changes its content type from 'audio/aac' to 'audio/*'

1. Send a voice note to Alice.
2. Forward that voice note to Bob.
3. Open Alice's thread on Desktop.
4. Open Bob's thread on Desktop

Expected result:
Both threads contain playable audio messages.

Actual result:
Only Alice's thread contains the playable audio message. Bob's thread contains an empty message.

Debugging on the desktop side reveals that the content type on the original was `"audio/aac"`, but on the forwarded message was `"audio/*"`. This applies both to the message forwarded to Bob's client, and the message synced to Alice's Desktop client under Bob's thread, both will get `"audio/*"` content types. I manually changed the content type on Desktop to `"audio/aac"` and was then able to play the message.

**Comment by liliakai** [comment]
Looks like this applies to videos too: #6617.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
