### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by yvan-sraka** [signalapp/Signal-Android#6511]
Hello,

What do you think about using the new [Adaptive Icons](https://developer.android.com/preview/features/adaptive-icons.html) feature of Android O?

It would be really nice to see them implemented in Signal! Can I help :wink:?

Thank you very much,

**Comment by moxie0** [comment]
Go for it!

**Comment by yvan-sraka** [comment]
Yes, I can definitely do the technical implementation, but I lack designer skills to edit the current icon to the new format, can anyone help me?

Thank you very much,

**Comment by Stanzilla** [comment]
I am on 4.14. 6 and adaptive icons are not working. @moxie0 reopen?

**Comment by winterer** [comment]
Same on 4.14.8. I took a short look at the sources; everything looks find at first glance. No idea, why it's not working.

**Comment by Stanzilla** [comment]
It's a new file, maybe it was skipped during compilation?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
