### ISSUE TITLE
send and receive contacts (vCard) properly

### ISSUE THREAD

**Issue by Ricain** [signalapp/Signal-Android#6520]
I have:
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] searched open and closed issues for duplicates

----------------------------------------

Hi :smile: 

This is a fresh feature request for #535 and #1407.

|Signal|Android Message|Android Message detailed|
|-----|--------|--------|
|![screenshot_20170411-143016](https://cloud.githubusercontent.com/assets/4070933/24909498/69b92262-1ec4-11e7-8b42-9f66ac8ea3bd.png)|![screenshot_20170411-142238](https://cloud.githubusercontent.com/assets/4070933/24909503/73a02884-1ec4-11e7-9a21-a67a8a5363bb.png)|![screenshot_20170411-142251](https://cloud.githubusercontent.com/assets/4070933/24909799/c4c50eb8-1ec5-11e7-88b9-31c361565416.png)|

Sharing contacts with Signal will extract only phone number and not any other information such as emails, dates, or contact picture. Worse, it won't do anything if a contact does not contain any phone numbers.

**Can you add the ability to share contacts in vCard format with an easy way to import/export them from Signal app?**

A good example of how it could work is Android Message (see screenshots).

Things worth mentioning:

- Looking at privacy, it would be really nice to be able to share sensitive contacts this way with all metadata included.
- vCard format is not something easy: https://tools.ietf.org/html/rfc6350
- Some implementations exist: https://github.com/mangstadt/ez-vcard
- Most SMS/MMS applications support this: Signal is late.
- Opening a text editor and copying or making your own `vcf` file is not a solution.
- This has been requested many times: #535, #1407, #922, #2504, #3808, #4205, #5075, #5612, #499, #2306...

**Comment by ByteHamster** [comment]
You already provide a list of issues that your issue is a duplicate of. Why do you even create a new one then?

**Comment by VikOlliver** [comment]
Just ran into this one myself, while trying to show someone how wonderful Signal is and why they should use it. They decided not to. There's your problem.

**Comment by travisfw** [comment]
I message with an iphone user often, and I can't even copy the message into a text file to make it work. I can import other vcf files, for instance, when sent by email. Don't know why it doesn't work coming through Signal.

This is what comes out of signal and fails to import as a vcf file (anonymized):

    ﻿BEGIN:VCARD
    VERSION:3.0
    PRODID:-//Apple Inc.//iPhone OS 10.3.2//EN N:Doe;Dr. John;;;
    FN: Dr. John  Doe 
    ORG:Doctor;
    TEL;type=pref:19995551234
    item1.ADR;type=HOME;type=pref:;;00 S. X Dr. \nSuite 0;X City;CA;;United States
    item1.X-ABADR:us
    END:VCARD

**Comment by travisfw** [comment]
I message with an iphone user often, and I can't even copy the message into a text file to make it work. I can import other vcf files, for instance, when sent by email. Don't know why it doesn't work coming through Signal.

This is what comes out of signal and fails to import as a vcf file (anonymized):

    ﻿BEGIN:VCARD
    VERSION:3.0
    PRODID:-//Apple Inc.//iPhone OS 10.3.2//EN N:Doe;Dr. John;;;
    FN: Dr. John  Doe 
    ORG:Doctor;
    TEL;type=pref:19995551234
    item1.ADR;type=HOME;type=pref:;;00 S. X Dr. \nSuite 0;X City;CA;;United States
    item1.X-ABADR:us
    END:VCARD

**Comment by zanedb** [comment]
Came here to report this, found this issue. I could possible make a PR about this but I don't know if I'll have time. It should definitely be added. @moxie0

**Comment by agottschling** [comment]
I've got the same problem as @travisfw. People send me contacts and I can't import them.

**Comment by jimreesman** [comment]
+1

**Comment by veeyah** [comment]
+1, I get vcards often and every other SMS app I've used handles it natively.  I don't think I can continue using the app without this feature.

**Comment by nimbius** [comment]
+1 i believe we need to handle vcards.  the actual raw output in the chat window is alarming as users arent expecting to see vcard code, and may interpret it as malicious/dangerous activity in their secured chat application.

**Comment by zanedb** [comment]
Perhaps we could use a library such as [this](https://github.com/mangstadt/ez-vcard). [This](https://stackoverflow.com/questions/17955097/importing-vcard-in-android-via-code) may also be useful. It is interesting that this has received pretty much no input from the Whisper Systems dev team. I could try to setup a PR.
________________________________

**Comment by damccull** [comment]
I also need vcard imports on a regular basis. This could be easily solved with not much work at all and without requiring any extra permissions than what signal already wants. Saving a recognized vcard as a vcf file in a temporary location (that gets cleaned up automatically) and then sending an intent for the phone's contacts app to open that file would suffice. The contact apps support vcards already, so no need to manually parse the card, just recognize it and hand off to another app.

**Comment by VikOlliver** [comment]
May I ask what to? Vcards are a relatively minor deal for me, at least compared to the single-point-of-failure vulnerability that SIgnal suffers from - and demonstrated in the last day or so. Nevertheless, if you've found a workaround I'd like to hear it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
