### ISSUE TITLE
Does not import all SMS messages

### ISSUE THREAD

**Issue by xenotropic** [signalapp/Signal-Android#6525]
### Bug description

I convinced my wife to install signal. When she imported her prior SMS messages into signal, it only imported a random selection. Some contacts' conversations are missing entirely; for many only inbound messages were imported, not the sent messages, so it ends up showing a one sided conversation. 

### Steps to reproduce
1) send messages on Samsung phone using default app
2) install signal
3) use import messages feature within signal

### Device info
**Device:** Galaxy S5 mini
**Android version:** 5.1.1
**Signal version:** 4.2.4

**Comment by 2-4601** [comment]
Maybe those messages that were not imported were MMS messages? See #4095.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
