### ISSUE TITLE
Support new Aspect Ratios

### ISSUE THREAD

**Issue by sweeper3000** [signalapp/Signal-Android#6529]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Due to new devices such as the Galaxy S8 with a larger aspect ratio, Android is recommending developers update their app's max aspect ratio. See the blog post for more info:

https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html?m=1

If there's no update to the max aspect ratio, the app will default to 16:9 and on these larger devices, there will be back bars on what could have been space used by the app.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
