### ISSUE TITLE
Video calls don't show full thumbnail of myself

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#6530]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

When I video call someone over Signal, the little preview of myself in the lower left-hand corner is square. However, talking with the person calls me reveals that they (shockingly) do not see a square - the thumbnail preview thing is obscuring parts of the video that they see. This is unfortunate.

### Device info

**Device:** Nexus 6P
**Android version:** CyanogenMod 13.0-20161220-SNAPSHOT-ZNH5YAO3XH-angler based on Android 6.0.1
**Signal version:** 4.2.4 (I'm on the Google Play beta channel but I don't think this is a beta)

**Comment by FaizKhan5** [comment]
I'm also seeing that thumbnail on left top side in video call when my cam is off and another person cam is on

**Comment by strugee** [comment]
@FaizKhan5 you should file a separate issue. Make sure to read the wiki page on how to file good bug reports.

**Comment by RiseT** [comment]
> the thumbnail preview thing is obscuring parts of the video that they see. 

One just shouldn't do video calls while naked 😁 Sorry, couldn't resist. But I agree on the issue's point.

**Comment by strugee** [comment]
😑😒

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
