### ISSUE TITLE
Movable thumbnail preview (video call)

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#6533]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In a video call, I should be able to move around the thumbnail showing my camera's video. Sometimes this covers up what I want to see from the other person's camera.

### Device info

**Device:** Moto G4
**Android version:** 7.0.1
**Signal version:** 4.3.5

**Comment by RiseT** [comment]
Wouldn't be the ability to toggle the thumbnail on and off a much simpler solution for the stated purpose...? Just a thought.

**Comment by dcherian** [comment]
Yes that would be a good start. But in general I think you would want to make sure that your camera is pointed in the right spot

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
