### ISSUE TITLE
[4.3.0] Signal takes minutes to display video thumbnails

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6542]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When sending a video the thumbnail takes minutes to be shown.

### Steps to reproduce
- Share a video to a contact
- Notice how the generic "video" icon is shown in the conversations, both when previewing the message (before hitting send), and after the video has been fully uploaded.
- Wait several minutes
- The video thumbnail shows up.

**Expected result:** The video thumbnail shows up immediately, even before actually sending the message. 

### Device info

**Device:** Nexus 6
**Android version:** Stock 7.1.1
**Signal version:** 4.3.0

### Link to debug log

https://gist.github.com/anonymous/27d2c0bf5a1034c232d698ce88ce2b32

**Comment by haffenloher** [comment]
Related: #5993 (probably the same issue)

**Comment by FeuRenard** [comment]
I noticed a similar problem, maybe not exactly the same:

### Steps to reproduce

- attach a video somehow (sharing from outside, forwarding inside etc.) -> no thumbnail
- hit send
- wait for end of upload

**Actual result:** thumbnail placeholder is shown with play overlay (suspicious, overlay should only appear with the thumbnail, not the placeholder). But: when you quit the conversation, the conversation list entry shows the correct thumbnail. On reentering the conversation the correct video thumbnail is shown.
**Expected result:** thumbnail is shown

### Device info
**Device:** AVD Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.10.6

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
