### ISSUE TITLE
Ringing didn't stop after call connected

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#6547]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Happened once. I initiated the call. Other person answers. I can hear them but they can't hear me. I can also hear the "ringing" sound, display says "ringing" not "connected" while this is happening

### Device info
**Device:** Moto G4
**Android version:** 7.0.0
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/anonymous/51ccb97e7d74b97f6e9c683e8dad8a38

**Comment by dcherian** [comment]
This happened again just now on 4.12.2 https://gist.github.com/079b8bd3b22377fbb43823f17b1e8127

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
