### ISSUE TITLE
Button to discard message

### ISSUE THREAD

**Issue by dschrempf** [signalapp/Signal-Android#6548]
I sometimes end up writing a long message but then getting a call which clarifies matters.  Then I have to manually delete the whole message either by repeatedly pressing backspace or by double click -> select all -> backspace.  A "discard message" button would be nice.

**Comment by Wikinaut** [comment]
:+1:

**Comment by Currrupted** [comment]
I really like the idea! The question would be where to put such a button, as the interface is already relatively "full". Maybe next to the message field?

**Comment by Wikinaut** [comment]
@Currrupted This can be done in the following way:

Perhaps you have noticed, that the additional (I admit space-consuming) gadget-icons for Camera and Microphone direct media messages become hidden *as* *soon* *as* at least one character is typed (or pasted) into the input line.

This now leaves then enough space for a new single "X" symbol at the right end of the input line which - when clicked - could open a user prompt "Press a second time to clear the input".

**Comment by Wikinaut** [comment]
Try a online test with your browser for example here https://mediathekviewweb.de/ . Type one character and notice the "X" symbol for clearing the input.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
