### ISSUE TITLE
Feature - re-invite contacts that uninstalled Signal without de-registering

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#6549]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

Signal contacts that I do not frequently exchange messages with tend to forget to install Signal when they switch to a new phone (probably because I'm the only person they were using Signal with). When I send them a Signal message, I see that the message reaches the server (one check mark) but is never delivered to their device. I would like to be able to send a new invitation with the link to the Signal app to them to ask them to re-install Signal. Currently this is not possible from the menu because the user is already registered, and therefore the invite option is missing.

**Comment by Be-ing** [comment]
The sender can't assume that the recipient does not have Signal installed anymore. It is also possible that the recipient has their device turned off or is not connected to a network for an extended period. It would be helpful if Signal displayed a notice to the sender if message does not reach the recipient after a specified amount of time. I think the server will queue undelivered messages for two days (can't recall where I read that). Whatever that time limit is, it would be helpful to notify the sender after that time.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
