### ISSUE TITLE
Incoming call drops playing media to speaker

### ISSUE THREAD

**Issue by sulaweyo** [signalapp/Signal-Android#6550]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When i listen to Musik via Bluetooth headset when a call comes in via Signal the Audio stream is offloaded to the speakers. Not that awesome when you sit in public transport and suddenly your music drops to the phone speakers at max volume.

### Steps to reproduce
- Play music on bluetooth headset
- Receive a call

**Actual result:** Music is offloaded to speakers
**Expected result:** Music should pause as it does on phone or hangout calls (for those two i know that it works correctly)

### Device info
**Device:** OnePlus 3T
**Android version:** 7.1.1
**Signal version:** 4.2.5
**Headphones** Parrot Zik
**Music player** Poweramp

### Link to debug log
https://gist.github.com/anonymous/88ba0c6e3490d603f6638846c7e4272f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
