### ISSUE TITLE
Group chat, some messages missing on one user's device

### ISSUE THREAD

**Issue by amitkot** [signalapp/Signal-Android#6554]
### Bug description
I have a group with 5 more participants.
Some of us wrote each other this afternoon.
Looking at another user's device, I noticed there are some messages they received in the chat, that I did not.

### Device info
Device  : OnePlus A0001 (bacon)
Android : 6.0.1 (2b5f277d1c, MHC19Q)
Memory  : 72M (8.34% free, 512M max)
Memclass: 192
OS Host : cyanogen
App     : Signal 4.3.1

### Link to debug log
https://gist.github.com/anonymous/765a99cab323c98017b36b9d68772594

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
