### ISSUE TITLE
No sound after some time and not possible to establish calls

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-Android#6572]
I have:
- [ X] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
In some cases I can hear the other party, but he cannot hear me (the other party can hear just some gibberish). This happens when I am on 4G network and driving with a car. I have full 4G signal, at the beginning Signal calls are just fine, but after some time communication is not possible. I live in Europe, Slovenia.

Anyway, right now, I have serious problems establishing Signal calls at all. Calls do not establish at all, but eve if they do, I or other party can hear just gibberish (but the person who does not hear gibberish, can hear the other person just fine).

I am also using Biocoded app, which is using Signal protocol, and it is working without any problems. So I assume it is not mobile network problem...

Anyway, I remember there were some problems with Signal servers a few months ago, and after Moxie resolved them, Signal calls started working. Maybe there is similar problem?

### Steps to reproduce
- start Signal call
- after some time connection is not possible anymore
or right now:
- start Signal call
- just pulse sound is heard

**Actual result:** The other party cannot hear me or the call is not established at all.
**Expected result:** Call should work.

### Device info
**Device:** LG Nexus 5
**Android version:** CM13
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/f793698a73ccc839818fffd1b42bc97b

**Comment by MatejKovacic** [comment]
This was a bug about European servers error: #5976

**Comment by moxie0** [comment]
There aren't any service problems at the moment, but there have been some ROM bugs reported from people running CM/LineageOS. Do you have a stock Android device you could try with?

**Comment by MatejKovacic** [comment]
Well, in fact me and my friends tried with other devices too (even iPhone), but it is the same. Are there any plans to use alternate codecs to even reduce required bandwith?

**Comment by cegg1** [comment]
Is this problem the same as #6432 ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
