### ISSUE TITLE
Notifications aren't being marked read after viewing SMS

### ISSUE THREAD

**Issue by mattsigal** [signalapp/Signal-Android#6576]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Ever since installing Signal and making it my default SMS application, when I receive a text message and open it in signal, the system notification does not see that the message is read. This results in the "new text" notification light remaining on. I've found a work around to clear the notification using the Lightflow widget (pictured below).

### Steps to reproduce
- Have Lightflow installed.
- Receive text message.
- Read the text message via Signal.

**Actual result:** Notification light comes on and vibration occurs signalling new text message has arrived. After reading, light continues blinking.
**Expected result:** System UI should see that the text has been read, and notification light should stop blinking.

### Screenshots
![2017-04-24 20 32 33](https://cloud.githubusercontent.com/assets/1421758/25357406/a9a5f034-290b-11e7-9b32-e4d4b6beb345.png)
(this widget is from Lightflow, and shows that sms notification is still on - despite having no unread messages)

### Device info
**Device:** LG Nexus 4
**Android version:** 5.1.1
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/anonymous/4dafc89cd719d1a776dd172098043a94

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
