### ISSUE TITLE
A better dark theme

### ISSUE THREAD

**Issue by jult** [signalapp/Signal-Android#6577]
Yes, I want to commit this the official way, but I'm missing directions for this. I'd like to submit a -in my view- much better dark color theme, but it's not clear where it needs to go in the Signal code-tree. For now I would rather just submit the range of colors for it, so someone with clear access can add it as an extra optional theme.

- We all have 24 bit color screens on our Android systems. The current Signal themes, aside from them not offering a lot of visual appeal, are not even all that legible: White on light red, white text on tan brown, really? I can't imagine Moxie would have signed for that to be the main dark theme, or did he?

- Here's a theme I once created for Squirrelmail, which I still use a lot because of its simplicity, and because this theme is so easy on the eyes, with good contrast and reminiscing of being in nature, think dark forest, fireflies, [Twin Peaks](https://www.youtube.com/channel/UCJFCmrB4hr_mBMwzg3vGrsQ/videos). I would imagine the several mildly differing dark greens could function as the backgrounds for the message bubbles, and the yellow-green-ish color[8] should be perfect for the text on them. Lots better than what it is now. In fact, some in my surroundings have simply stopped using Signal because of its dark theme, while the same people are still using this dark theme on my webmail-servers;
```
$color[0]   = '#092003'; // TitleBar
$color[1]   = '#DDFEAB'; // Quote in mail
$color[2]   = '#FECF10'; // Warning/Error Messages
$color[3]   = '#041001'; // Left Bar Background
$color[4]   = '#030900'; // Normal Background
$color[5]   = '#102903'; // Table Headers
$color[6]   = '#C3CEAC'; // Text on left bar (user created folders/Purge etc.)
$color[7]   = '#CEEFAC'; // Links (also email-addresses)
$color[8]   = '#EFFEDE'; // Normal text
$color[9]   = '#091902'; // Darker version of #0
$color[10]  = '#081800'; // Darker version of #9
$color[11]  = '#CCDDC0'; // Special Folders color
$color[12]  = '#182907'; // Alternate color for message list
$color[13]  = '#DEFDAF'; // Color for quoted text -- > 1 quote
$color[14]  = '#BDEFA1'; // Color for quoted text -- >> 2 or more
$color[15]  = '#163011'; // Unselectable folders
$color[16]  = '#F0CD09'; // Highlight color
```

- Please be somewhat respectful of the chosen colors here, be aware that these selections and combinations are not slammed together in a couple of hours; It evolved into these exact color picks during the last 17(!) years of use on some webmail servers I still maintain, and it versioned into this from friends' and relatives' user input and my own taste and views etc.

- I know you're going to kill this as a non-Issue, for not following guidelines, but it *is* an issue. I don't want to work on signal code, I just want to add a GUI color theme. Here's me hoping someone will pick it up as such.

**Comment by Dyras** [comment]
Can you post a picture of what this theme in Signal would actually look like?

**Comment by FaizKhan5** [comment]
@jult Post a screenshot or close this issue please :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
