### ISSUE TITLE
TextSecure crashes when "Registering with server"

### ISSUE THREAD

**Issue by Vinnl** [signalapp/Signal-Android#658]
Every time I try TextSecure v2 and I try to enable Push messages, TextSecure crashes. It gets through the SMS verification and key generation, but crashes at the "Registering with Server..." step, after which it says "Unfortunately, TextSecure has stopped." The attachment shows how far it gets.
![yrypwlb](https://f.cloud.github.com/assets/4251/2255742/3ce3b0a6-9dfb-11e3-9629-04c08951202c.png)

This is on regular Android 4.2 on the Fairphone. I have Xprivacy installed but set it to allow everything TextSecure asks for, and AFWall+ but also configured it to allow TextSecure. RedPhone can register with the server just fine. It doesn't matter whether TextSecure is on the Internal or Phone Storage.

If there's any othe relevant information I can provide or things I should try, please let me know here. Thanks.

**Comment by pde** [comment]
I saw this bug occurring on CyanogenMod 12.  It seems that either PrivacyGuard, or the system's default PermissionsManager, was silently unhappy about TextSecure having been installed before the user could be asked what permissions to give it.  Relevant logcat entries:

```
W/PackageManager(  750): Not granting permission android.permission.BROADCAST_WAP_PUSH to package org.thoughtcrime.securesms (protectionLevel=2 flags=0x8be44)
W/PackageManager(  750): Not granting permission com.google.android.c2dm.permission.RECEIVE to package org.thoughtcrime.securesms because it was previously installed without
W/PackageManager(  750): Unknown permission com.android.launcher.permission.READ_SETTINGS in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.android.launcher.permission.WRITE_SETTINGS in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.sec.android.provider.badge.permission.READ in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.sec.android.provider.badge.permission.WRITE in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.htc.launcher.permission.READ_SETTINGS in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package org.thoughtcrime.securesms
W/PackageManager(  750): Unknown permission com.anddoes.launcher.permission.UPDATE_COUNT in package org.thoughtcrime.securesms
```
Using TitaniumBackup for a data preserving uninstall / reinstall of TextSecure fixed this problem.  Will try to file a bug against CM for this behaviour...
