### ISSUE TITLE
Android Auto only reading most recent Signal message does not see previous unread messages

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6582]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal is o longer reporting how many messages are waiting, and will only read the last message sent from a user. Debug log is for three messages from a Signal contact where only the last message was read, no unread message count was shown on the android auto screen

### Steps to reproduce
- Connect to Android Auto
- Receive multiple Signal messages
- Read new messages

**Actual result:** Most recent messages is read
**Expected result:** All unread messages are displayed/read

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.4.0 Beta
Latest Android Auto update: 3/29/17 version 2.2.710804

### Link to debug log
https://gist.github.com/058f77fe591c0485d398ae93d8835c79

**Comment by 2-4601** [comment]
@snaggen

**Comment by snaggen** [comment]
I don't have an Android Auto car anymore. And on top of that, I will be
without development possiblies for the coming months.
So the earliest time for me to look at this would be the end of August, and
then only using the emulator.
However, the code is quite simple and contained, so I should not be to hard
for anyone else to dig into this.

Den lör 29 apr. 2017 19:132-4601 <notifications@github.com> skrev:

**Comment by ddomains** [comment]
Maybe related: Signal no longer shows quantity of unread messages (#) on the Android Lock screen (Android 7.x)

**Comment by bdmayes** [comment]
@snaggen If you can point me in the right direction in the code base, I can try taking a look at this. I have zero Android experience but I do have a willingness to help and access to Android Auto in my vehicle. I'm actually looking to (potentially) fix another issue I'm having with Auto/Signal integration. While searching open issues I stumbled across this one.

Additionally, it is possible to download the Android Auto app from the play store and launch it directly on the phone. Having the in-dash system in your car is not necessarily a requirement.

**Comment by snaggen** [comment]
If I were you, I would go back and look at the initial Android Auto commit too see how it works

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
