### ISSUE TITLE
Signal android app is getting crashed

### ISSUE THREAD

**Issue by info2shashi** [signalapp/Signal-Android#6583]
Signal android app is getting crashed while starting up WebRtcCallService at following line

`this.peerConnectionFactory = new PeerConnectionFactory(new PeerConnectionFactoryOptions());`

Here is logs
```
04-26 12:00:52.571 E/chromium: [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
04-26 12:00:52.616 E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
04-26 12:00:53.805 E/NativeCrypto: ssl=0x9b8fd200 cert_verify_callback x509_store_ctx=0x9b7ff4e0 arg=0x0
04-26 12:00:53.805 E/NativeCrypto: ssl=0x9b8fd200 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
04-26 12:00:53.812 E/NativeCrypto: ssl=0x9b903800 cert_verify_callback x509_store_ctx=0x9dece360 arg=0x0
04-26 12:00:53.812 E/NativeCrypto: ssl=0x9b903800 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
04-26 12:00:53.812 E/NativeCrypto: ssl=0xa16cbe00 cert_verify_callback x509_store_ctx=0x9e0dc360 arg=0x0
04-26 12:00:53.812 E/NativeCrypto: ssl=0xa16cbe00 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
```
It seems, something wrong with webrtc library OR am I missing something? Thanks

**Comment by haffenloher** [comment]
There's no crash in that log snippet. Please fill out the issue template and include reproduction steps and a full debug log.

**Comment by herbsmn** [comment]
my app also crashes when trying to initiate a call. i'll try to get you logs soon. i'm using the Replicant ROM on a galaxy s3.

**Comment by miketv-s** [comment]
I seem to have the same issue as herbsmn. 

## Bug description
When trying to place a Signal call, Signal crashes with message "Unfortunately, Signal has stopped"

## Steps to reproduce
Open Signal
Tap a Signal capable contact.
When in contact conversation screen, press the locked telephone icon in the upper right to place call.

## Expected result:
Call screen opens, makes funky calling noise and shows text like "Calling" and "Establishing Signal call"

## Actual result: 
Signal stops, with message "Unfortunately, Signal has stopped" from the OS

## Device info:
### Device: 
Samsung Galaxy S3 (i9300)

### Android version: 
Replicant 6.0

### Signal version: 
4.5.3 (from https://whispersystems.org/android/apk/), 4.6.0 (from http://fdroid.eutopia.cz/)

### App state:
Signal messages and calls registered, handles system SMS, passphrase disabled. Bug triggers both when reregistered to operate without GCM and reregistered with GCM enabled through microG.

### Debug log:
[signallog-crashedcall.453-submit.txt](https://github.com/WhisperSystems/Signal-Android/files/1069493/signallog-crashedcall.453-submit.txt)

## Additional information:
[A reply in the Replicant forum](https://redmine.replicant.us/boards/9/topics/14272?r=14273) suggests the effect may be related to Signal trying to use video capabilities also for pure voice calls. Replicant has not been able to support video yet.

**Comment by moxie0** [comment]
@miketv-s Looks like you have a different issue than what this one is about. From your log:

`````
06-08 20:14:08.655  4189  4189 E AndroidRuntime: java.lang.RuntimeException: Unable to find any matching EGL config
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.webrtc.EglBase14.getEglConfig(EglBase14.java:236)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.webrtc.EglBase14.<init>(EglBase14.java:57)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.webrtc.EglBase.create(EglBase.java:86)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.webrtc.EglBase.create(EglBase.java:93)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService$7.run(WebRtcCallService.java:835)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.Util$2.run(Util.java:397)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-08 20:14:08.655  4189  4189 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`````

That looks like a ROM issue to me, that function call shouldn't fail. I don't know much about Replicant, but it looks like this is something that wouldn't pass CTS? We can't really support Android ROMs that don't meet the Android compatibility standards. Feel free to open a separate issue if you want to track it here, but it seems like this should be something you open with Replicant instead.

**Comment by herbsmn** [comment]
Thanks @moxie0 

I just opened a ticket related to this with Replicant: https://redmine.replicant.us/issues/1810

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
