### ISSUE TITLE
Don't scale down images attached as "files"

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6589]
Sometimes there is the need for sending an image as-is, without further compression/scaling. As now Signal supports big and arbitrary attachment, please leave images alone when sending them as "Files" and not from the "Gallery".

The workaround now is renaming the file, but it's rather clunky on Android

**Comment by LoveIsGrief** [comment]
I'm interested, is this done in the app itself?

**Comment by FeuRenard** [comment]
It's done around here in-app:
https://github.com/WhisperSystems/Signal-Android/blob/e96bf2bdc7a9cb7497eec696362c29a764d292d7/src/org/thoughtcrime/securesms/jobs/SendJob.java#L52

Media only leave your device encrypted (for Signal messages). I cannot imagine that there is a method which resizes encrypted media (e.g. on the server).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
