### ISSUE TITLE
PDF file misinterpreted as media file

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6591]
### Steps to reproduce
- Send a PDF file as an attachment
- See how the sent file appears as a "media bubble". The video player opens when tapping on it (and it doesn't work, of course).

**Expected result:** A "file" bubble appears.

### Device info

**Device:** Nexus 6
**Android version:** Stock 7.1.1
**Signal version:** 4.5.0

**Comment by moxie0** [comment]
Can't reproduce this, you'll have to provide a sample file that causes this behavior for you.

**Comment by vvug** [comment]
You're right, it isn't always reproducible. I can reproduce it with this file:

[a.pdf](https://github.com/WhisperSystems/Signal-Android/files/962277/a.pdf)

It's a valid PDF 1.7 generated by pdfLaTeX.

**Comment by p4nci** [comment]
@vvug can't reproduce this with provided a.pdf (sender Signal v4.5.0 - receiver Signal v4.3.2)

**Comment by vvug** [comment]
@p4nci I trust you, but I can always reproduce it with that file...

**Comment by Trolldemorted** [comment]
cannot reproduce on Android 7.1.2 (lineageos), Signal 4.5.0.

**Comment by ForGorNorPor** [comment]
Could not reproduce on Android 4.4.4 CyanogenMod, Signal 4.11.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
