### ISSUE TITLE
[Feature] Add a private PDF previewer

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6592]
It would be very useful to be able to view PDF documents without saving them unencrypted and with a viewer that is guaranteed not to connect to the Internet or do other nasty things.

I understand there's the danger of bloating Signal, but I think this possibility should at least be considered.

**Comment by paride** [comment]
CopperheadOS has a pdf viewer which uses pdf.js in a WebView sandbox, see:

https://copperhead.co/android/docs/technical_overview#pdf-viewer

The latest Apache licensed version of the app is cloned here:

https://github.com/paride/CopperPDF

**Comment by sigenc** [comment]
@paride this was exactly my idea. Nice one

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
