### ISSUE TITLE
Signal Messages behaving oddly with shift key and long press on keyboard.

### ISSUE THREAD

**Issue by BitterLies** [signalapp/Signal-Android#6598]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While typing in the Signal App on Android 7.0, the Shift button will activate and deactivate.  This interrupts typing, breaks autocorrect, and prevents things like long press to get a symbol (Holding the 'A' key to get the '!').  In addition to the keyboard showing inputs that aren't happening, the number at the top of the screen changes format.  Instead of showing the number below the contact name, it will randomly switch to +xxxxxxxxxx below the contact name instead of xxxxxxxxxx.  Once this happens once, it will continue to randomly Shift throughout the app being open.  No other app on the phone does this when typing.

### Steps to reproduce
- Open messenger on Android 7.0.  
- Open an SMS message or a Group message (Happens in both)
- Type a word, then punctuate the word with "!" by holding the "A" key.

**Actual result:** 
Keyboard shifts randomly, with the Shift key becoming illuminated or not.  Typing becomes very tedious, as the quick changing of the Shift key seems to interrupt typing.  Number at the top of the screen 'flickers' between two different formats ("xxxxxxxxxx" and "+xxxxxxxxxx").  App must be closed down and reopened to type properly.  Typing may or may not trigger this again before restarting the App.
**Expected result:** The message should simply type as I input the proper keys.

### Screenshots
Due to the issue, I'm unable to get a screenshot of it in it's different states, since it happens very rapidly.

### Device info

**Device:** Samsung Galaxy S6
**Android version:** 7.0.0
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/anonymous/b7ab2376d7b38b75bc07086e1893bd4f

**Comment by moxie0** [comment]
You running an aftermarket rom or anything like that? I don't know why, but from the log it looks as if your sync adapter is running over and over again non-stop. Not sure why that would affect the keyboard, but seems suspicious.

**Comment by BitterLies** [comment]
Forgive my ignorance, but how can I check if I have a rom like that?  I'm not sure what it is.

**Comment by haffenloher** [comment]
> how can I check if I have a rom like that? 

@BitterLies did you install a rom which came from a third party, not from your phone's manufacturer?

**Comment by BitterLies** [comment]
Like an operating system?  No, I've only ever installed Apps from the Google Play Store.

**Comment by 2-4601** [comment]
#6433 has similarities in the description

**Comment by venatiodecorus** [comment]
I've run into this issue as well, although I wasn't long pressing anything. Occasionally when I open the app, the keyboard will be freaking out as if the shift key is being toggled rapidly. Makes it impossible to type. I kill the app and reopen and it will still be happening. Eventually it stops. Strange.

**Comment by arccgi** [comment]
Samsung galaxy S7 on verizon network.
Signal becomes impossible to use, constantly interrupts chat and reformats contact's phone number.  Causes missed characters during texting, and only happens inside of signal app.
Was using signal exclusively as default messenger app for months, then this started happening.
Disabled autocorrect and system emoji option, using video calls, issue persists.
Removed signal app from phone and restarted, installed again.  left standard messenger app to android default and signal app still has same issues.
What additional info can i provide to assist resolution?

**Comment by moxie0** [comment]
@arccgi I think somehow you have a sync adapter that's running constantly in the background, continually updating the contacts database every few milliseconds or so. I'll look into how to reduce the effects of this within Signal, but every time we get a notification that a contact has been updated, we attempt to redisplay the contact information. So every time that sync adapter writes to the contacts db, we essentially "redraw" signal.

**Comment by cmdavis4** [comment]
I also had the same issue in which the contact number reformatted every few seconds, blocking input; the reformatting has stopped in the last ~week, but the issue persists. It now happens as the underline beneath the word I'm currently typing flashing twice, during which time keyboard input is ignored. The contact number does not reformat when this happens. The two flashes happen in a fraction of a second but it still makes it essentially impossible to type in the app. I've tried different keyboards and the issue is reproduced in all of them. I'm on a Galaxy S6 on Verizon.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
