### ISSUE TITLE
Flyme OS - Meizu m5s - cannot pickup the call.

### ISSUE THREAD

**Issue by notsofast123** [signalapp/Signal-Android#6599]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Call drops on the receiving phone when you are trying to pick up incoming call. From the lock screen or the app, does not matter.  4.4.0 or 4.5.0, Flyme 6 or 5, result is the same. Different notification settings, lock screen password or not - result is the same. If you callback - it goes through as it should.

### Steps to reproduce
Start Signal
Call the phone
Phone rings
Pickup
Call drops

### Device info
Device  : Meizu M5s (meizu_M5s)
Android : 6.0 (1492776309, Flyme 6.7.4.25 beta)
Memory  : 17M (0.00% free, 512M max)
Memclass: 256
OS Host : mz-builder-5
App     : Signal 4.4.0

### Link to debug log
https://gist.github.com/anonymous/55b9bef459f63d9ec546fa37ac7920aa
https://gist.github.com/anonymous/f61c0dda251c5820e5c56f225e3967e3

**Comment by moxie0** [comment]
What is FlymeOS? You've got some weird things going on in your logs, looks like you tried downgrading the app after schema changes had already been applied, is this a rooted device?

There's also this crash:

`````
04-28 20:06:09.326 12210 12400 E AndroidRuntime: java.lang.RuntimeException: Camera is being used after Camera.release() was called
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at android.hardware.Camera.setPreviewTexture(Native Method)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at org.webrtc.Camera1Session.create(Camera1Session.java:73)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at org.webrtc.Camera1Capturer.createCameraSession(Camera1Capturer.java:34)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:285)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:815)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
04-28 20:06:09.326 12210 12400 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
`````

**Comment by notsofast123** [comment]
It's Chinese version of Android made by Meizu, very popular because relatively cheap. Although I have global phone, but it should matter.
http://www.flymeos.com/

I have tried downgrading after trying everything, but might have not done it clean, that's what you see in the logs. Doesn't work either.
It's not rooted.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
