### ISSUE TITLE
Strange short vibration and no notification sound when recieving messages

### ISSUE THREAD

**Issue by kwlg** [signalapp/Signal-Android#6600]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Quite often when I receive messages, I get only one short vibration and no vibration pattern. When this happens, I don't get a notification sound either. The fact that I get only one short vibration and no sound leads to me missing the fact that I have received a message. This happens even though all sounds in the system, as well as the vibration, are turned on.

If I get another message a few seconds later, the behaviour is often the way it should be with the usual pattern and a notification sound.

The bug appears as follow:
- A message is received.
- If the normal vibration pattern of Signal is assumed to be approximately (250 ms vibration, 250 ms without vibration, 250 ms vibration), the vibration I get is more like 50 ms vibration and then nothing more. Thus, I get ONE very short vibration and not a pattern like I usually do, and there is no notification sound.

### Steps to reproduce
- Unknown, although I have tried to find out how to reproduce this during the past few months.
- I most often experience the problem when the phone is lying on a table. It is possible it happens with the phone in a pocket as well. The vibration is so short I'm not sure I would feel it if the phone is in a pocket.
- The screen appears to have to be turned off, usually for a while.

**Actual result:** A message is received and I only get ONE short vibration instead of a vibration pattern. I get no notification sound.
**Expected result:** A message is received and I get the usual vibration pattern (250 ms vibration, 250 ms without vibration, 250 ms vibration) and a notification sound.

### Device info
**Device:** Google Nexus 5X
**Android version:** 7.1.2 (stock, unrooted) but had the problems on 7.1.1 as well
**Signal version:** 4.3.2

### Link to debug log
Update: https://gist.github.com/ecd9eceea928b11d171beb4beba05dac
Happend with the screen on while holding the phone in my hand

**Comment by moxie0** [comment]
Do you have a linked desktop client?

**Comment by kwlg** [comment]
No, I only use Signal on Android

**Comment by kwlg** [comment]
Here is the log: https://gist.github.com/ecd9eceea928b11d171beb4beba05dac

This time, it happens with the screen on while holding it my hand

**Comment by kwlg** [comment]
Here is another one: https://gist.github.com/a113dca9e5bdff44ca1e72ee120fc340
From what it seems to me, this log might be more helpful than the previous one.

The screen was on and I was holding the phone in my hand when the message was received.

**Comment by njregenwether** [comment]
@kwlg 
Not certain that this is the issue, but on looking into this in the top line of your log file https://gist.github.com/ecd9eceea928b11d171beb4beba05dac 
we see 
ActivityThread: Failed to find provider info for com.teslacoilsw.notifier

On searching around about this, I see that com.teslacoilsw.notifier is a part of the nova notifier. The error associated with that appears to be pretty well described here. 
http://stackoverflow.com/questions/18463767/failed-to-find-provider-info-for-custom-provider

It appears to be security/packaging issue related to nova's notifier. I'm not sure this is the issue but it might be worth looking into. Hopefully this helps.

**Comment by kwlg** [comment]
I can now confirm this problem on another Nexus 5X too. It uses the same version of Android (7.1.2) and is currently running Signal 4.6.1. Maybe it is a device specific problem?

@njregenwether Thanks for the suggestion! However, the other user with the same problem uses no apps from that developer so I believe the problem is not related to that.

**Comment by JasMan78** [comment]
Same error here on two other Nexus 5X from a friend of my and me. 
Happens mostly when SMS or Signal message arrives when phone is in deep sleep mode (Signal is excepted from that deep sleep mode). 
Happened a few minutes ago (21:59 o'clock), see logs: 

https://gist.github.com/c55debe0c5db97b207af9998be75150b

**Comment by kwlg** [comment]
> Same error here on two other Nexus 5X from a friend of mine and me.
> Happens mostly when SMS or Signal message arrives when phone is in deep sleep mode (Signal is excepted from that deep sleep mode).
> Happened a few minutes ago (21:59 o'clock), see logs:
> 
> https://gist.github.com/c55debe0c5db97b207af9998be75150b

Perhaps this only happens for Nexus 5X?

I have noticed that this happens much less frequently since updating to Android 8.0. Since the update (or some Signal update?), at least the vibration appears to behave the way it should. It still happens from time to time that I hear no notification, however.

**Comment by JasMan78** [comment]
I noticed that this also happens on Twitter notifications. So I think it's not a Signal problem. Must have to do with the Nexus 5X. But I can't find any related topics in Internet.

**Comment by JasMan78** [comment]
@kwlg Do you use Tasker on your Nexus 5X? I've disabled Tasker for a while (2-3 hours), and the notification sound was fine in this time. Not represantive, because sometimes it works also fine with Tasker enabled. But maybe a hint.....

**Comment by JasMan78** [comment]
Just as information: I've upgraded my Nexus 5X to Oreo and now the notification sound is always fine.

**Comment by digit83** [comment]
Ive the same problem on my Galaxy s8+, Android 7.0, SE 8.1. I just noticed the notification sometimes work normal when i turn up volume in Android settings

BTW I dont use tasker

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
