### ISSUE TITLE
Cannot receive phone calls or SMSs during a Signal call when on the Three UK network and connected to 4G or Wifi

### ISSUE THREAD

**Issue by cegg1** [signalapp/Signal-Android#6602]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

### Bug description
Cannot receive phone calls or SMSs during a Signal call when on the Three UK network and connected to 4G or Wifi.  

Three UK has the "Three inTouch" app that handles voice calls and SMSs when the phone is connected to 4G or Wifi (com.hutchison3g.threeintouch). In practice this app is some kind of VoLTE/VoWiFi replacement for non-VoLTE/VoWiFi-enabled devices that prevents 3G fallback for incoming calls and also enables calls over WiFi. It doesn't do anything when the phone is connected to 3G. 

If a Signal call is started while the phone is connected to 4G or WiFi (and thus the regular calls are being handled by InTouch), InTouch de-registers from the network for the whole duration of the Signal call and no calls or SMSs can be received or sent until the Signal call finishes. The phone appears to be out of mobile coverage to someone trying to call from a traditional network. When the Signal call ends, InTouch re-registers with the network and the phone starts receiving calls / SMSs normally again.

  -This bug does not happen when calling using any other apps, including Whatsapp, Skype, Hangouts and Duo. Calls and SMSs can be received while on a Whatsapp/Skype/Hangouts/Duo call regardless of being connected to 3G, 4G or Wifi, and InTouch does not de-register from the network during these calls. 
  -This bug did not happen with the old RedPhone calls either, it only started happening with the new WebRTC calls. 
  -This bug does not happen if the phone is connected to 3G.

In a nutshell, it looks like Signal WebRTC calls are breaking Three InTouch. 

Incidentally, a very similar issue happened with the early versions of Google Duo, but it was fixed soon after being reported. The only difference was that in that case, InTouch was not just being broken during a Duo call, but every time Duo was on the foreground, regardless of whether a Duo call was in progress or not. Link:  
https://productforums.google.com/forum/#!topic/Duo/yX0e4cjT2hI

### Steps to reproduce
- Be on the Three UK network, connected to 4G or Wifi, and using the Three InTouch app (being connected to 3G does not trigger the bug). 
- Initiate a Signal (WebRTC) voice call (old RedPhone calls did not trigger this bug). 

**Actual result:** Incoming phone calls / SMSs cannot be received during the Signal call. Calling the phone from a traditional network while on a Signal call results in an "out of coverage" message. The Three InTouch app de-registers the phone from the network as soon as a Signal call is initiated. 

**Expected result:** It should be possible to receive incoming phone calls / SMSs while on a Signal call. Calling the phone from a traditional network while on a Signal call should work. The Three InTouch app should stay registered on the network during a Signal call. 

### Screenshots
![01](https://cloud.githubusercontent.com/assets/28192843/25558454/116aa32e-2d1f-11e7-825c-702abf350fdd.jpg)
![02](https://cloud.githubusercontent.com/assets/28192843/25558457/1fbcd960-2d1f-11e7-961c-057cc9d6ea75.jpg)
![03](https://cloud.githubusercontent.com/assets/28192843/25558458/2322fef4-2d1f-11e7-8488-e95f3af75733.jpg)
![04](https://cloud.githubusercontent.com/assets/28192843/25558459/26f6b52a-2d1f-11e7-80fa-f9cf4e3cf7da.jpg)

### Device info
**Device:** Nexus 5 D821
**Android version:** Stock 6.0.1 M4B30Z
**Signal version:** 4.5.2 (but this bug happens with every Signal version since WebRTC was introduced)

### Link to debug log
Debug log of successful Signal call while on 4G: no regular phone calls or SMSs can be received until the Signal call has ended.
https://gist.github.com/ee60c98e50a43a404f0e63f809da425a

**Comment by johanw666** [comment]
I'd say this is a feature, not a bug. It is already troublesome enough that "normal" calls can interrupt a Signal call, please don't allow other voip apps to do the same.

**Comment by cegg1** [comment]
I see your point about VoIP apps not interfering each other, it's a good point. 
I'd say in this case it's a bit different because Signal is precluding "normal" calls and text messages from going through while a Signal call is active. The phone is reported as being *out of network coverage* to someone that tries to make a "normal" call while the phone is on a Signal call. If anything, it should be reported as busy, not out of coverage.

**Comment by johanw666** [comment]
> To a person that tries to make a "normal" call to the phone while it is on a Signal call, the phone is reported as out of network coverage. If anything, it should be reported as busy, not out of coverage.

I agree on that, but I doubt that's something Signal can solve. How does this work for other voip apps like WhatsApp, Viber and BBM?

**Comment by cegg1** [comment]
There are no problems at all with WhatsApp, Skype, Hangouts or Duo calls. And there were no problems either with the old RedPhone calls. The issue can be narrowed down to Signal's new WebRTC calls only.

Now, a similar issue did happen with the first-ever release version of Duo, but it was fixed by Duo in the following version, soon after being reported in their forum:
https://productforums.google.com/forum/#!topic/Duo/yX0e4cjT2hI

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
