### ISSUE TITLE
Registration crash after entering voice code

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6603]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The registration crashes after entering the voice verification code. No Google Play Services installed.

### Steps to reproduce
- Install Signal
- Enter phone number for registration
- Press Register button
- Wait for 2min timeout (AVD cannot receive SMS)
- Trigger voice call
- Answer call, enter code
- Press Verify

**Actual result:** The registration progress is shown (the window with the four steps) but then Signal closes. The registration process starts again after opening Signal.
**Expected result:** The registration progress is shown and finishes successfully, showing the conversation list afterwards.

### Device info

**Device:** AVD Galaxy Nexus
**Android version:** 4.0.3 (without Google Play Services)
**Signal version:** 4.5.2~x (da6a00c4dca734d4d15be13aa4225081646e39a2 + own commits far away from registration stuff)~

### Link to debug log
These are full device logs. I did not manage to capture Signal's output only.
https://gist.github.com/FeuRenard/e7cc4eb065dcb96128350bcec9ef2233
https://gist.github.com/FeuRenard/106fb3507f050d6ff4ef2f76ed0bae6f
Signal-only log:
https://gist.github.com/FeuRenard/9cdacb7d84cd4ce60d5b47d6a3c03653

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
