### ISSUE TITLE
Message sent on Desktop does not get synced to Android (after SafetyNumber Change on Desktop)

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#6609]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Text sending to a group on Signal-Desktop does not get synced to Signal-Android

### Steps to reproduce
I am not sure if this is reproducible. But here is what happened. 
I wrote a message to a group in Signal-Desktop. Signal-Desktop informs me about a changed safetynumber. These messages do not get synced to my phone. 

**Actual result:** See the screenshots 
**Expected result:** Message(s) should get synced to my phone. 
### Screenshots

![signal-desktop](https://cloud.githubusercontent.com/assets/18451020/25636822/1c899e9a-2f72-11e7-9d0a-b6ca49e8b0da.png)
![signal-android](https://cloud.githubusercontent.com/assets/18451020/25636836/27a6efbc-2f72-11e7-9a05-b07d43c5977c.png)

### Link to debug log

Desktop: https://gist.github.com/anonymous/fd5996887d49f542593afee276606469
Android: https://gist.github.com/anonymous/ac96d8d1737f8b4b2fdd011ad5f7c807

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
