### ISSUE TITLE
video from iPhone cannot be forwarded correctly from Android

### ISSUE THREAD

**Issue by unhammer** [signalapp/Signal-Android#6617]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I receive a video from an iPhone (never got one from an Android yet), and then try to forward it, other iPhone's can't open it. But the video plays fine on the Android (and original iPhone).

### Steps to reproduce
- receive video from iPhone onto Android
- long-click, click `…`-menu and "Forward" to another iPhone

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- my Android plays the video I received just fine
- the second iPhone owner, who I sent to, gives me a reply saying "what's this 7mb file, it doesn't open"
- my Signal Desktop shows a working video preview in the conversation where I received the video
- my Signal Desktop shows the filename `signal-2017-05-08-182819.*` (with tooltip `Unsupported attachment type. Click to save`) instead of the Video/preview in the second conversation (where I forwarded the message). Saving this file, I can use `/usr/bin/file` on it, which gives: `/tmp/signal-2017-05-08-182819.*: ISO Media, MP4 v2 [ISO 14496-14]`

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- Desktop and the second iPhone should be able to play the forwarded video

### Device info

**Device:** Sony Xperia LT25i
**Android version:** 4.3
**Signal version:** 4.5.3

### Link to debug log
https://gist.githubusercontent.com/anonymous/2bf8f99d16ae854c404cd9a5d14674db/raw/6505f9155112b9a0a82ac76ebbd42fcf0c660ff3/cat.log

**Comment by odeke-em** [comment]
The description of this bug looks overly similar to https://github.com/WhisperSystems/Signal-Desktop/issues/1174 in which the video won't play on Desktop but will play on Android, on Desktop Signal version: 0.39.0.

**Comment by liliakai** [comment]
dupe #6510 ?

**Comment by unhammer** [comment]
Looks like it! (Though might want to mention that it affects iPhone in the summary too?)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
