### ISSUE TITLE
No Signal data loads after power cycle (all messages lost/deleted/wiped)

### ISSUE THREAD

**Issue by gimbi** [signalapp/Signal-Android#6618]
I have:
- [x] searched open and closed issues for duplicates
Potentially related issues:
https://github.com/WhisperSystems/Signal-Android/issues/423 (I commented on this one)
https://github.com/WhisperSystems/Signal-Android/issues/4772
https://github.com/WhisperSystems/Signal-Android/issues/6441
https://github.com/WhisperSystems/Signal-Android/issues/6472
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Device shut off due to low battery. I heard the Signal message notification as it shut down. Once rebooted, Signal failed to load any data, including archived messages. Signal is able to send and receive texts and I confirmed that no new key was generated with a friend (fig 1).

Android reports Signal is consuming 115 MB of data and 30 MB cache (fig 2), leaving me hopeful that the data might be recovered with some elbow grease. Open to any suggestions - my thoughts:
- I'm guessing Signal is unable to open the old database and made a new one. Is it somehow possible to force it to open the old database?
- If not, might there be a way to recover the message DB and decrypt all or some of the data out of band? I know my passcode and the keys appear to be intact.

### Screenshots
Fig 1
![screenshot_20170508-223114](https://cloud.githubusercontent.com/assets/954607/25833925/ad1a22d4-3442-11e7-8319-701cfa97750e.png)

Fig 2
![screenshot_20170508-222228](https://cloud.githubusercontent.com/assets/954607/25833928/b447aa86-3442-11e7-8c73-b73f09cb91db.png)

### Device info
**Device:** HTC M8, hw version 5
**Android version:** 6.20.654.3
**Signal version:** 4.1.0

### Link to debug log
https://gist.github.com/anonymous/32706bddc8b09c4db21520bca8a5a513 [taken ~10 minutes and a reboot after the incident]

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
