### ISSUE TITLE
Re-registering with a different number confuses other devices

### ISSUE THREAD

**Issue by paride** [signalapp/Signal-Android#6619]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

When a device unregisters from Signal (without uninstalling) and then re-register with a different telephone number, contacts with previously active conversations see the new messages come from the old number. The messages do arrive, but the number is not recognized as a Signal user (the "Invite to Signal" banner appears).

### Steps to reproduce
- Register a device and start a conversation with a contact;
- Unregister the device from the "advanced preferences" page (do not uninstall Signal);
- Register again with a different phone number
- Send a message in the conversation initiated with the previous number.

**Actual result:** The other user sees these messages coming from the old number. The "Invite to Signal" banner appears, and it is not possible to reply.
**Expected result:** The messages are shown as coming from the new number, that correctly appears as a Signal user.

### Device info

**Device:** Nexus 6
**Android version:** 7.1.1 (stock)
**Signal version:** 4.5.3 on both sides
### Link to debug log

https://gist.github.com/anonymous/fb0cdbc65da69369131d9c001119c61c

**Comment by 2-4601** [comment]
Related #5057

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
