### ISSUE TITLE
Feature - set disappearing timer by default

### ISSUE THREAD

**Issue by alecbl** [signalapp/Signal-Android#6622]
I think it would be useful that one could optionally choose to have disappearing messages set, to some timer, by default.
The reasoning is that I tend to view it as being an hint that I wish to exercise sane log keeping. Having the ability to set it on my end is valuable for that purpose, because it forces other parties to deliberately circumvent it.
It does grow a bit tiresome to have to remember to set it on every new chat that does not yet has it on.

**Comment by merge** [comment]
If anything I'd set a default maximum number of locally saved old messages. One can already opt-in to such a limit too though.

While it makes _very_ much sense not to log indefinitely, especially with Signal, especially with questionable security state of enduser's devices, I guess it's hard to force people to do so. Having all logs is what most people expect I think.

It's an important topic imo. From a stable UX point of view the ship has sailed here though :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
