### ISSUE TITLE
Timeframe server deletes inactive accounts

### ISSUE THREAD

**Issue by sigenc** [signalapp/Signal-Android#6623]
Right now the server logs 2 things. Registration day/month/year and last login day/month/year. This is used to determine unactive accounts and delete them if they are not used longer than a year. My question is, is it possible to reduce this logging to month/year? So the day don't get logged. 

EDIT: Or even better what @bowensong recommends.  `current_year - last_login_year > 1 `

**Comment by bowensong** [comment]
Or even further more, it only keeps the year, so it deletes the user if `current_year - last_login_year > 1`

**Comment by paride** [comment]
Inactive accounts are not deleted, just marked as inactive, they remain in the database "forever". The server doesn't even have a way to delete accounts at the moment, it's one of the things I'd like to see implemented in #6620.

**Comment by sigenc** [comment]
@paride Yes paride. I noticed the issues you opened. Let's see what moxie has to say about this.

**Comment by sigenc** [comment]
@bowensong This would mean that if youjoin on 29 dec and don't login till 1 jan i till deactivate your account.

**Comment by bowensong** [comment]
@sigenc That's not true. Because `2017 - 2016 == 1`, not greater than 1

**Comment by sigenc** [comment]
@bowensong Hmm True. So it means when i register on 29.12.2017 and don't Login till 01.01.2019 it will delete the account? This is an awesome idea. Even better. Good Job.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
