### ISSUE TITLE
Support drag-dismiss gesture in media preview

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6625]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Feature Request
Add support for a drag-dismiss gesture in `MediaPreviewActivity`, which will close the activity.
This would allow swiping up or down instead of using a back button (in navigation or action bar) for closing the activity. You can see this feature in action with the official Twitter app when you view an image in fullscreen. (EDIT 2017-10-04: WhatsApp's media preview also supports this in the most recent stable Android release)

I see the following advantages in this feature:

- If we decide to hide action bar and navigation bar in the future (#5934), this feature will allow the user to go back without bringing the bars onscreen before.
- When using a touch screen, the middle of the screen should be the easiest accessible region for touch actions. With this feature we don't have to move our finger to the corner of the display to leave the activity.

This feature was first proposed in a [community forum thread](https://whispersystems.discoursehosting.net/t/support-android-drag-dismiss-activity/896).

This [extended FrameLayout](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/ElasticDragDismissFrameLayout.java) could be useful for implementing this feature.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/support-android-drag-dismiss-activity/896).
