### ISSUE TITLE
Feature request: emoji reactions

### ISSUE THREAD

**Issue by vr2262** [signalapp/Signal-Android#6630]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request
One of my contacts wished they could add emoji reactions to specific messages in our chat. The two main features would be the ability to add reactions to messages and the ability to view which users responded with which emoji.

Other applications that have this feature:
Slack: https://get.slack.help/hc/en-us/articles/206870317-Emoji-reactions
Facebook Messenger: https://newsroom.fb.com/news/2017/03/introducing-message-reactions-and-mentions-for-messenger/
GitHub: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by pspeter3** [comment]
This would be really cool! I assume this would need to be implemented across all of the platforms though.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
