### ISSUE TITLE
Label "unread messeges" is confusing (and sometimes just wrong)

### ISSUE THREAD

**Issue by dreng** [signalapp/Signal-Android#6631]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If a new message arrives while the conversation list is active, a label "1 unread message" is added to the conversation (which can be seen after opening the appropriate conversation of course). If one opens that conversation and a second message arrives, the label changes to "2 unread messages", which is actually not true. In fact the conversation view is not able to know if someone read a message or not. That's only known by the reader himself. I mean, I'm staring at the screen reading the new messages and Signal is telling me that I haven't read the messages!?

The truth is that I did not answer the 2 messages mentioned before, that's why the label stays where it is. But: why should it be useful to see a label right under my last answer telling me that I did not write anything since then? That's just logical.

In conclusion this label is just useless in my opinion. More than that it is confusing because one might think of a bug if that label does not disappear.

### Steps to reproduce
- Go to conversation list
- Receive a message
- Change to conversation view
- Receive another message

**Actual result:** Label "x unread message(s)" stays until something has been sent
**Expected result:** No label should be shown at all

### Screenshots
![screenshot_2017-05-10-14-15-54](https://cloud.githubusercontent.com/assets/20901110/26000612/f0794f0c-3729-11e7-81ca-c1e6c904b82d.png)

![screenshot_2017-05-12-16-34-01](https://cloud.githubusercontent.com/assets/20901110/26002928/7e8ae4fc-3731-11e7-8795-2f94de6e35f9.png)

### Device info

**Device:** Samsung S5 mini (SM-G800F)
**Android version:** 6.0.1 (also 4.4.4)
**Signal version:** 2.5.3

**Comment by Dyras** [comment]
Personally I think "New messages" would be more appropriate.

**Comment by dreng** [comment]
@Dyras 
I agree that "New messages" would be more appropriate. On the other hand one could leave the conversation open for hours while just reading incoming messages. That's why "New messages" or any other phrase is not ideal either.

Let me ask that question again:  Why should it be useful to see a label right under my last answer telling me that I did not write anything since then? It makes no difference if I scroll up until I see a label or if I scroll up until I see my last post. I don't get the point.

**Comment by merge** [comment]
I think it's not necessarily _your_ last post where that label is. _unread_ is really often wrong and _new_ would be better indeed.

**Comment by dreng** [comment]
@merge 
Thank you for your contribution. Can you give an example where it's not supposed to be _your_ last post? I did some testing but can't figure it out.

**Comment by anoadragon453** [comment]
Got a complaint today about this from an older friend using Signal. Along with changing the text to read 'New Messages', I suggest talking a look at what [Riot.I'm](https://riot.I'm/app) in that a simple bar is displayed above new messages before disappearing gracefully once it's been scrolled into view.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
