### ISSUE TITLE
Feature Request: Playback speed control

### ISSUE THREAD

**Issue by DoS007** [signalapp/Signal-Android#6643]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

**Long voice messages can be tedious to hear**. Hearing people speaking in a speed that is much slower than one's own comprehension time, that's why **e.g. youtube's speed control** is very nice. There you can easily set the speed to e.g. 1.5x of normal speed. **So you can hear people, saying good structured, nice things in an appropriate speed.**

This playback achieves:
- Less boredom
- More time for other things

Implementation:
The speed choice control could blend-in when one starts playing the voice message in signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
