### ISSUE TITLE
SMS do not get forwarded to hands free device.  

### ISSUE THREAD

**Issue by TimBritton** [signalapp/Signal-Android#6648]
Sms do not get forwarded to my car system via Bluetooth when received.  Let me know if I need to provide more information!

**Comment by nrizzio** [comment]
@TimBritton can you fill out the issue template and either amend your original post or add it as a comment?

**Comment by TimBritton** [comment]
It looks like this may be related to Issue #3944.  Did you want me to close this?  I was on the train earlier when I was searching.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
