### ISSUE TITLE
android: incoming call: notification title

### ISSUE THREAD

**Issue by bogorad** [signalapp/Signal-Android#6651]
Since there is no support for Android wear I keep missing incoming calls - they don't show on my watch (Huawei v1), only 'missed call' notification. I worked around this problem (incoming calls using a non-wear-supporting VOIP app like Zoiper and WhatsApp) by using tasker: 

- intercept notifications from specified app (AutoNotification plugin for Tasker)
- check notification title
- if it's something like 'incoming call' - send the text field to android wear (AutoWear plugin for Tasker)

However this method doesn't work with Signal because its notification about an incoming call is untitled.

Could this be fixed?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
