### ISSUE TITLE
Bluetooth audio connection is not terminated after calling

### ISSUE THREAD

**Issue by micressor** [signalapp/Signal-Android#6658]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Bluetooth audio connection is not terminated after calling. I have tested this with a headset and a hands-free kit in the car. In the car, I see in the display that the connection has not yet been disconnected.

### Steps to reproduce
1. Connect the bluetooth headset
2.  Call another singal user
3.  End the call.

**Actual result:** Audio connection to the headset is still open.

**Expected result:** The audio connection to the headset should be terminated.

### Device info
**Device:** Fairphone 2
**Android version:** 5.1
**Signal version:** 4.5.3

### Link to debug log
The caller has terminated the call. The receiver pressed the hangup button on the headset a little later:
https://gist.github.com/anonymous/b2ed8e8eb42bce611424f87e653bb489

**Comment by micressor** [comment]
Added debug log: https://gist.github.com/anonymous/b2ed8e8eb42bce611424f87e653bb489

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
