### ISSUE TITLE
Signal sends lots of SMS with dual SIM

### ISSUE THREAD

**Issue by konstantin-schekotihin** [signalapp/Signal-Android#6664]
### Bug description
If SMS is send over deactivated SIM card on a dual SIM phone, Signal tries to resend the message continuously (kind of infinite loop).

### Steps to reproduce
- switch off a SIM card on a dual SIM phone
- select it to send an SMS in Signal
- send something

### Device info

**Device:** Motorola G4 (dual sim)

**Comment by adamhassel** [comment]
This is still an issue. Signal doesn't seem to respect the disabled state of SIMs in a multiple-SIM phone. I think that a trivial solution to this issue would be to simply not allow sending from a disabled SIM card.

As it is now, this will result in an infinite retry (as sending through a disabled SIM obviously fails), resulting in Android OS complaining that Signal is sending too many SMS'es, rendering the app/phone nigh unusable.

Device: Huawei P9 Plus Dual-SIM

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
