### ISSUE TITLE
Ogg Vorbis files not selectable in "Attach audio"

### ISSUE THREAD

**Issue by h-2** [signalapp/Signal-Android#6666]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

When selecting audio files to send to a conversation partner, one cannot select ogg vorbis files. MP3s on the other hand work fine.
It is possible to attach ogg vorbis files, via the regular file attach so it is not a huge issue. I expect, however, that usually there are also embedded media controls?

In any case, it might just be some hardcoded regex that just doesn't include `.ogg`? Because system-wide ogg is fully recognized as a valid audio format...

### Steps to reproduce
- press the attach button
- select audio
- look for a `.ogg` file, see it grayed out

**Actual result:** the file is grayed out
**Expected result:** the file should not be grayed out and selectable

### Screenshots

Not relevant I think.

### Device info

**Device:** OnePlus One
**Android version:** 6.0.1 (CM13.0)
**Signal version:** 4.5.3

### Link to debug log

Not relevant I think.

**Comment by junitas** [comment]
I reproduced this using a sample file of type `audio/x-vorbis+ogg`. When opening the Audio attachments menu, `selectMediaType(Activity activity, @NonNull String type, @Nullable String[] extraMimeType, int requestCode)` sets the acceptable mimeTypes for the Intent to be `"audio/*`, which should ungray the .ogg file when the attachments drawer is opened, but for whatever reason it doesn't.

**Comment by derede** [comment]
THIS IS NOT A WANDTED FEATURE!
I would call it "bug" or please rename "Audio" to "only mp3" or something. It does not work as expected. Even attaching as a file or sharing over the music app doesn't work as expected, there are always I/O errors.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
