### ISSUE TITLE
"Error downloading MMS message, tap to retry" on Signal 4.6.0

### ISSUE THREAD

**Issue by mrogaski** [signalapp/Signal-Android#6670]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
"Error downloading MMS message, tap to retry" on Signal 4.6.0

### Steps to reproduce
When receiving an MMS message from non-signal user, I receive the message "Error downloading MMS message, tap to retry". 
Tapping on the icon usually has no visible effect, however it sometimes cause the dowload icon to disappear.  When it does appear to retry, the failure occurs again.  

**Actual result:** "Error downloading MMS message, tap to retry"
**Expected result:** MMS message is successfully downloaded.

### Device info
**Device:** Motorola Droid Mini
**Android version:** 4.4.4
**Signal version:** 4.6.0

**Comment by mrogaski** [comment]
[b219681c998aa531d287a7e12df0d575-cc7c92ecc0ed6350e23d2debf8dd14b852106373.zip](https://github.com/WhisperSystems/Signal-Android/files/1020573/b219681c998aa531d287a7e12df0d575-cc7c92ecc0ed6350e23d2debf8dd14b852106373.zip)

**Comment by riyapenn** [comment]
@mrogaski I may have created https://github.com/WhisperSystems/Signal-Android/issues/6668 around the same time as you opened this issue.

**Comment by cwknox** [comment]
Same issue, Signal 4.10.11.  It may be an Android v. Apple issue as I get it receiving messages from iPhone users, and see the same behavior with three stock messaging app.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
