### ISSUE TITLE
Voice message stops playing when holding phone to ear

### ISSUE THREAD

**Issue by MasterOfBytes** [signalapp/Signal-Android#6673]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When playing an audio voice and holding the phone to the ear, the phone gets dark (which is ok) but stops playing the voice message

### Steps to reproduce
- receive an voice message
- push the play button
- hold phone to the ear

**Actual result:** Voice message stops playing
**Expected result:** Voice message plays to the ear speaker

### Device info
**Device:** Samsung Galaxy S7 Edge
**Android version:** 7.0
**Signal version:** 4.6.0

### Link to debug log
https://gist.github.com/9335f4ce2b0a0b6475948d8371a40a71

The Bug is also mentioned here, but not declared as a bug: https://github.com/WhisperSystems/Signal-Android/issues/6455

**Comment by sedroar** [comment]
I have the same issue on Samsung Galaxy S7. 
But, if you listen to the audio message from the info view (tapping in the i icon after selecting the message) you can listen to it, and if you turn the phone close to your ear, the message will be played in the earpice (so, this feature works well in the Info page).

**Comment by thrdroom** [comment]
I can confirm my sister has the same problem with the following device:

### Device info

**Device:** Samsung Galaxy S7
**Android** version: 7.0
**Signal version:** 4.9.9

**Comment by drws** [comment]
Confirming for:

Device: Samsung Galaxy S7 G930F
Android version: 7.0
Signal version: 4.10.12

**Comment by MasterOfBytes** [comment]
Still an issue 👎

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
