### ISSUE TITLE
Signal 4.6.1: Can't retrieve MMS messages T-Mobile

### ISSUE THREAD

**Issue by eonsend1** [signalapp/Signal-Android#6682]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

MMS messages from non-Signal users display error 'Error downloading MMS message, tap to retry'.  All retries similarly fail.  Restarting device doesn't help.  Wifi on/off doesn't help.  Wifi Calling Compatibility on/off doesn't help.  Neither default T-Mobile APN settings or modified ones fix the issue.

### Steps to reproduce
- Receive MMS message from non-Signal user.
- message fails to download
- tap 'retry' icon
- message attempts to download, mobile network icon appearing/disappearing multiple times over the course of the download
- message fails to download after ~10 seconds

Actual Result: MMS message fails to download

Expected Result: MMS successfully downloads on first try.

### Device info

**Device:** LG G4
**Android version:** 6.0
**Signal version:** 4.6.1

### Link to debug log

https://gist.github.com/anonymous/9383bd457f16d7176f0d265bd0c3578b

**Comment by moxie0** [comment]
That log is strangely truncated so it's hard to see what's going on. Can you capture another full log?

**Comment by eonsend1** [comment]
All the logs that I've tried to capture are similarly truncated.  Is there a setting to insure they are longer?

**Comment by moxie0** [comment]
@eonsend1 In all the logs you capture, there's only one second of data available? You might have to use adb logcat with a USB cable connected to your desktop device to get a proper log.

**Comment by eonsend1** [comment]
Logcat posted here: https://gist.github.com/anonymous/f3965626f7a380057d851df35480e0ec

**Comment by moxie0** [comment]
@eonsend1 Something is very strange, many log lines are missing. Is this a custom ROM or anything strange? Also you're not running a VPN or anything like that right?

**Comment by eonsend1** [comment]
hmm, i checked and it looks like the log level was set to debug (I captured the log through Android Studio), could that be the issue?  I will set the log level to verbose and recapture. Im not running a VPN, and I am using the stock ROM.  

Verbose logcat capture here: https://gist.github.com/anonymous/a28a941e860435f414d980546c88c799

**Comment by moxie0** [comment]
@eonsend1 Can you try running "adb logcat" from the commandline instead of using android studio?

**Comment by eonsend1** [comment]
[cmd_logcat_adb.txt](https://github.com/WhisperSystems/Signal-Android/files/1030094/cmd_logcat_adb.txt)

**Comment by moxie0** [comment]
@eonsend1 Do you have multiple SIM cards?

**Comment by eonsend1** [comment]
No this is not dual SIM. It's a standard LG G4 (LG-H811 purchased from a T Mobile store which, as far as I'm aware, only has 1 SIM slot.

**Comment by riyapenn** [comment]
Also an issue on 

Sprint
Device: HTC One M8
Android version: 6.0
Signal version: 4.6.1
Debug log: https://gist.github.com/anonymous/303b74af763015b2c96427d2f7e80e35
Notes: Sending MMS works after enabling Wi-Fi calling compatibility mode; Receiving MMS does not; this had worked previously

**Comment by moxie0** [comment]
@riyapenn This is an issue for tmobile, let's keep sprint stuff separate

**Comment by EvanK** [comment]
Have seen a similar issue on T-Mobile (Nexus 4 running CyanogenMod), when receiving a _group_ MMS

**Comment by eonsend1** [comment]
Are there any updates on this?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
