### ISSUE TITLE
NPE Crash after tapping notification 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#6685]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashed after tapping the notification for a signal message (with image) that just a arrived. There was only that one new message. 

Signal was locked per 20 minute setting.  Not sure what the last activity was I hat open. 

Also sent the crash report. 

### Steps to reproduce
- ? 

**Actual result:** crash 
**Expected result:** !crash

### Device info

Device  : Sony E5823 (E5823)
Android : 6.0.1 (2701308494, 32.2.A.0.253)
Memory  : 11M (18.04% free, 512M max)
Memclass: 192
OS Host : BuildHost
App     : Signal 4.6.1

### Link to debug log

https://gist.github.com/c78b8b83ca4e51ea6644d661780796c2

*Filling out the issue template on the phone is a PITA :-\ Always need several attempts to bring me to fill it out.*

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
