### ISSUE TITLE
Pictures sent from linked desktop client do not show on android

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-Android#6686]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Pictures sent from linked desktop client do not show on android. Only a placeholder and caption are shown, see screenshots.

### Steps to reproduce
- link android client with desktop client
- send picture using the linked desktop client

**Actual result:** Picture is not shown on android client
**Expected result:** Picture is shown on android client

### Screenshots
![desktop](https://cloud.githubusercontent.com/assets/4365731/26553297/ad4466dc-4493-11e7-9ffd-78f997b7e2cb.png)
![android](https://cloud.githubusercontent.com/assets/4365731/26553304/b282d822-4493-11e7-9407-760be5f4868c.png)

### Device info

**Device:** motorola MotoG3
**Android version:** 6.0.1
**Signal version:** 4.6.1 (android), 0.40.0 (desktop)

### Link to debug log

https://gist.github.com/anonymous/8601eb1568e9cef06b2ef2e9d753bd39

**Comment by FeuRenard** [comment]
I cannot reproduce this, Android 6.0.1, Signal 4.6.1, Desktop 0.40.0.

Can you tap on the empty picture message and see anything? Do you see this issue for every picture (.png, .jpg)?

**Comment by NFM-8** [comment]
I am able to reproduce with at least png, jpeg and pdf attachments. Selecting attachmenet message and pushing the save button results in error "Error while saving attachment to storage!". Receiving android client can access attachments just fine.

With two desktop clients attached to the android client, the other desktop client can also see attachments 
sent from the other desktop client just fine.

Tried with and without passcode, reboot android but the problem persists.

**Comment by Dyras** [comment]
You have to enable the self destruct timer in order to trigger this bug
Happens for every picture on G4 and G3 for me

**Comment by FeuRenard** [comment]
There is no timer enabled on @NFM-8's screenshots. And I cannot reproduce with set timer either.

**Comment by Dyras** [comment]
Well here's what happens for me
When I send a picture/video from Signal-Desktop to a contact, the picture/video actually appears on my phone momentarily. The reset timer is set to 1 day and the picture/video disappears in less than a minute.

Here's a log from Signal-Android: https://gist.github.com/anonymous/9d146d8e9619cbab67787947cd5a7412
Will try disabling reset timer now to check if pictures still disappear, I'm pretty sure they don't (at least for me) but I could be wrong

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
