### ISSUE TITLE
Signal 4.6.1 Received MMS download fails (provider: Sprint)

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6691]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Received MMS on Signal 4.6.1 fails with the provider Sprint. Sending MMS works after enabling Wi-Fi calling compatibility mode; Receiving MMS does not; this had worked previously

### Steps to reproduce
- Receive MMS
- Open Signal
- Tap to download

**Actual result:** MMS fails to download
**Expected result:** MMS downloads and displays

### Device info

Device: HTC One M8
Android version: 6.0
Signal version: 4.6.1
Provider: Sprint

### Link to debug log
 https://gist.github.com/anonymous/303b74af763015b2c96427d2f7e80e35

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
