### ISSUE TITLE
Contact name update in Signal on BBOS10

### ISSUE THREAD

**Issue by Recte** [signalapp/Signal-Android#6694]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Again this might just be a Android Runtime thing on Blackberry, and no serious issue for me personally. But just to make sure it is no issue on Android, I'd like to report it. So, if this works fine on Android, it is fine with me. Better safe than sorry.

When I update a contact name in my contacts, the name is not updated in Signal. It looks like it only reads the name in the initial install or when a contact starts using Signal and not afterwards. 

### Steps to reproduce
1. Edit contacts in the native device "contacts app"
2. Check contacts in Signal where nothing is changed
3. Tap on the pen to open contacts in Signal
4. Swipe down to refresh/update contacts
5. Nothing changed
6. Delete conversation, repeat step 3 and 4 and get result of step 5

**Actual result:**
Nothing happens in relation to the contact name
**Expected result:**
Name of contact updated to the contact in the address book/contacts.

### Device info

**Device:** Blackberry Q10 SR10.3.3.1463
**Android version:** Android Runtime with [Android Jelly Bean support](https://developer.blackberry.com/android/apisupport/unsupported_api_jellybean_appfeatures.html) 
**Signal version:** 3.3.0 to 4.6.1 (all versions I ran so far)

### Link to debug log

Not Applicable I guess, but if it is useful I'd like to read the preferred actions.
When looking at the debug log the only relevant thing I see after step 4 is:

```
W/PushServiceSocket(593825851): Push service URL: https://textsecure-service.whispersystems.org
W/PushServiceSocket(593825851): Opening URL: https://textsecure-service.whispersystems.org/v1/directory/tokens
W/Directory(593825851): Adding active token: +*********--, --------------, video: true
```
The dashes are the replacement of the last two digits and the secure string.
So it does refresh but does not look at the my address book. There are no errors are shown either, so that made me think if it was just the absence of the functionality.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
