### ISSUE TITLE
Feature: Auto-Expiring Groups

### ISSUE THREAD

**Issue by privong** [signalapp/Signal-Android#6702]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

## Summary

In similar vein to the "disappearing message" setting in Signal for set deletion of messages after a given time, I request a "disappearing group" setting. Such a setting would cause all members to leave a group a set period of time after the group's creation or after the most recent message and remove the group. This has at least one potential advantage / use case:

_Automated reduction of attack-surface for recovery of communications metadata_. Even if the auto-expiring messages feature is enabled, the discussion group's existence potentially remains on devices of involved parties. Compromise of any device involved in the conversation could reveal at least the contact information for people involved in the group, even if no actual communication information is risked.

## Relevant Issues / Feature Requests Previously Opened

I did search the issues to try and ensure similar requests were not already considered. I did find a couple items, that are related but not the same:

* #1764 "Enable sender to delete own messages from all parties in the conversation". I agree that this was rightfully declined for the reasons mentioned in the thread. My feature request is not to create a single-user ability to remove a group from many devices, but to enable an feature analogous to "disappearing messages" that the entire group would see and be able to re-negotiate.

* #2412 'Is there a way to create an "incognito thread"?' This discusses automated log-cleaning of individual conversations. It was declined according to discussion #1764 regarding deletion of messages from remote parties. I would argue my feature request is more akin to the "disappearing messages" feature, but extended to groups to further protect group membership from after-the-fact discovery by 3rd parties.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
