### ISSUE TITLE
UX: Misleading menu item text '*Leave group*'

### ISSUE THREAD

**Issue by wizardofid** [signalapp/Signal-Android#6705]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes people accidentally leave a group. They misinterpret the menu item '*Leave group*' as '*Leave current group chat back to chat overview pane*'.
I see several possible enhancements:
- Change menu text to '*[End | Cancel | Terminate] my group membership*'. This was an easy change which should clarify the purpose of this menu item.
- Enhance confirmation dialogue like it is in Signal / iOS. Add a clarifying sentence, what it means to leave the group.
- Add a menu item '*Back to chats overview*' for people who are looking for this functionality.
- Move '*Leave group*' menu item to the '*Edit group*' submenu. Maybe you should be able to remove yourself from the group at the same place where you can add people to the group. 

I'd prefer the combination of moving this item to the '*Edit group*' submenu and enhancing the confirmation dialogue like it is in Signal / iOS. But this might be (to) much work for a minor issue...

### Steps to reproduce
- Give unexperienced user a device with Signal
- Ask him to open an existing group chat
- Ask him to leave this chat back to chats overview

**Actual result:** People sometimes open 3dot-menu and choose '*Leave group*' and ignore or misunderstand confirmation dialogue.
**Expected result:** People always understand purpose of '*Leave group*' item and never accidentally leave the group.

### Screenshots
None.  I don't think screenshots are helpful here and i'm lazy ;-)

### Device info
not reasonable, device-independent issue.

### Link to debug log
not reasonable as it works like it is designed.

**Comment by paride** [comment]
Suggestion: "Unsubscribe from group".

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
