### ISSUE TITLE
Feature: display artist & title if present in common audio tag format(s)

### ISSUE THREAD

**Issue by deutrino** [signalapp/Signal-Android#6707]
I would love it if, when I attach an audio file, the title and artist are displayed if they are set in a couple of common tag formats - for example, MP3 id3 tags (v1 and v2), and the most common tag type used in .m4a and .ogg containers. That should cover 90+% of cases.

This is a total wishlist item given the resources available, but it's the type of subtle fit and finish that makes apps a joy to use.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
