### ISSUE TITLE
No LED Notification After Android 7.0 Upgrade

### ISSUE THREAD

**Issue by pinesol93** [signalapp/Signal-Android#6709]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After I upgraded to Android 7.0, I no longer receive notifications through the LED light on my phone.

### Steps to reproduce
- upgrade to Android 7.0
-ask someone to send me a text 
*text is sent*
-no notification seen
*wait for text*
-press button to wake screen and see text
-LED does not change 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
-when a new text is received, the LED does not light up.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Have the LED flash when I receive a text message

### Device info

**Device:** SM-G920V
**Android version:** 7.0
**Signal version:** Signal 4.6.1

### Link to debug log

https://gist.github.com/anonymous/a491db68de4439be3e66bf10a4ac0231#file-cat-log

**Comment by haffenloher** [comment]
Do you use a non-stock rom? Does the LED work when vibrate mode or notification sounds are enabled?

**Comment by pinesol93** [comment]
Thanks for looking into this.

This is stock rom. Also, when I turn on vibrate it does work. I usually keep vibrate off, though. Prior to updating, I had vibrate turned off and it still worked.

Maybe a setting I've missed?

Jonny Pine


-------- Original message --------

**Comment by pinesol93** [comment]
This is stock rom. Also, when I turn on vibrate it does work. I usually keep vibrate off, though. Prior to updating, I had vibrate turned off and it still worked. 


Maybe a setting I've missed?

**Comment by pinesol93** [comment]
Sorry, I didn't think the comment from the email would show up.

**Comment by p4nci** [comment]
@pinesol93 check if LED is activated:
Android settings -> Notifications -> Gear (right top corner) and check LED settings

**Comment by pinesol93** [comment]
Signal notifications is set to "Allow notifications". Also, the LED indicator setting is on as well.

The LED works with Snapchat and my email when vibrate is turned off for example, but when vibrate is off for signal, no LED.



Jonny Pine


-------- Original message --------

**Comment by p4nci** [comment]
just to be clear, I'm talking about a global settings (Android settings -> Notifications -> Gear at right top corner) and NOT per app settings

**Comment by pinesol93** [comment]
Correct. Android Settings->notifications and from that menu you are able to choose either allow all all notifications or specific app notifications. Signal notifications are allowed.

Unless there are separate notifications, but both the setting app and the gear in the top right corner of the pull down screen go to the same settings menu



Jonny Pine


-------- Original message --------

**Comment by p4nci** [comment]
here my settings:
![screenshot_1](https://user-images.githubusercontent.com/16047081/27056232-90f47406-4fc7-11e7-865b-fa779fce8e95.png)
![screenshot_2](https://user-images.githubusercontent.com/16047081/27056250-9b63b03c-4fc7-11e7-9f7e-481d2f9b631f.png)
![screenshot_3](https://user-images.githubusercontent.com/16047081/27056257-a257c144-4fc7-11e7-8093-b570e41cc787.png)

**Comment by pinesol93** [comment]
Thanks for the screenshots. Unfortunately, it seems as though mine are different. See mine below:

Full path: (gear)->notifications->find Signal-> tap Signal App.

[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20170612-181703_png_1497305868089]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20170612-181713_png_1497305883219]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20170612-181728_png_1497305887481]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20170612-181732_png_1497305891888]


Let me know if calling would help and I can provide my phone number.


Jonny Pine


-------- Original message --------

**Comment by p4nci** [comment]
@pinesol93 please check also "LED indicator" under Settings -> Display
:confused:

**Comment by pinesol93** [comment]
Fortunately or unfortunately, the LED Indicator is on:
![screenshot_20170613-213539](https://user-images.githubusercontent.com/29242271/27111778-70b6d0ee-5080-11e7-9211-d436aa0e0a4c.png)

I also tried enabling vibrate notifications through signal (settings>notifications>vibrate) and then I turned vibrate off for an individual conversation and the LED did not work. I turned vibrate back on for the conversation and the LED immediately worked.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
