### ISSUE TITLE
Signal 4.6.1 crash in the middle of an SMS conversation "java.lang.IndexOutOfBoundsException"

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6710]
I have:
- [X] searched open and closed issues for duplicates, most similar to https://github.com/WhisperSystems/Signal-Android/issues/6553 and https://github.com/WhisperSystems/Signal-Android/issues/6661 (in terms of user wording and not debug logs) possibly solved by https://github.com/WhisperSystems/Signal-Android/commit/e9ae439b70ed8e807df090d97c2cd798c612e09e?
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash in the middle of an insecure conversation with a contact.  Crashes subsequently after opening Signal. 

### Steps to reproduce
- No clear steps to repro

**Actual result:** Crash
**Expected result:** Not crash

### Screenshots
N/A

### Device info

**Device:** LG G6
**Android version:** 7.0
**Signal version:** 4.6.1

### Link to debug log
 https://gist.github.com/99b37908d30431ff16cc7e0b97545104

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
