### ISSUE TITLE
Use volume rocker to click pictures

### ISSUE THREAD

**Issue by jonalmeida** [signalapp/Signal-Android#6711]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When taking a picture you can take one by pressing the on-screen button, however most camera apps by default support clicking a picture by using either volume keys. I recommend following this practice as well.

### Steps to reproduce
- Open a conversation in Signal.
- Click on the camera icon in the input field.
- Observe the camera viewfinder open up with the on-screen button to click a photo.
- Attempt to take a photo by clicking on either volume key.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
No action takes place when the volume keys are pressed when the camera viewfinder is active.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
A picture should be taken.

### Screenshots

N/A

### Device info

**Device:** LGE Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.6.1

### Link to debug log

N/A

**Comment by The-Drake** [comment]
Same behavior on LG G3, G4 and Nexus 5.
Still open issue on 4.10.12.
Makes selfies sticks click buttons useless too.

Every other similar apps works ok. Please fix it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
