### ISSUE TITLE
Use shared elements transition for media preview

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6719]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
We could use a [shared element transition](https://developer.android.com/training/material/animations.html#Transitions) when we are starting/finishing [`MediaPreviewActivity`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/MediaPreviewActivity.java) from/to both [`ConversationActivity`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/ConversationActivity.java) and [`MediaOverviewActivity`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/MediaOverviewActivity.java).

You can see an example on [YouTube](https://www.youtube.com/watch?v=Qbf-uaybG6A), in the[ Android documentation (figure 1)](https://developer.android.com/training/material/animations.html#Transitions) or in Signal when you switch between a conversation and its recipient preferences.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
