### ISSUE TITLE
"All media" does not show audio files

### ISSUE THREAD

**Issue by DoS007** [signalapp/Signal-Android#6729]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Beeing in a chat with a person, one can click on the options button and click on "all media" (or similar, in the german translation it's "Alle Medieninhalte") to show the media. One gets a list with all pictures and videos.  
Audio files and recordings are not in this list, although it's media as well. Please add that :). (This would be very helpful, as one could save them then as well to the normal storage for a backup.)

**Comment by mueller-ma** [comment]
Can you change th title to "All media does not show voice messages"?

**Comment by finnoleary** [comment]
Bumping to state that I've started work on a PR for this. AFAIK it looks to be a simple one-line change[0], but getting a test environment set up is going to take a while right now.

[0]: The queries used seem to disinclude audio files from the "documents" view but does not include them from the "gallery" view: https://github.com/WhisperSystems/Signal-Android/blob/e7a9893e94659779680cedcfc3398a664e12abad/src/org/thoughtcrime/securesms/database/MediaDatabase.java#L44

**Comment by finnoleary** [comment]
Ok, I had a ""working" example back in January, but there's no interface to show the audio media files correctly and there's no documentation (and the code is literal fucking spaghetti) with respect to how things are displayed that I can't write one. The change is conceptually simple, but trying to write supporting code for the change is doing my head in. I might pick it up sooner or later, but I have other things that I would like to dedicate my time to in the meantime, I'm sorry.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
