### ISSUE TITLE
Signal crashed after opening(IllegalArgumentException: Unknown type class org.thoughtcrime.securesms.mms.DecryptableStreamUriLoader)

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#6733]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After opening Signal it crashed. 

### Steps to reproduce
Unable to reproduce.

**Actual result:** A message "signal is gestopt" (Dutch) appears.
**Expected result:** Signal app starts.

### Device info

**Device:** samsung SM-G900F (kltexx)
**Android version:** 6.0.1
**Signal version:** 4.6.1

### Link to debug log

https://gist.github.com/anonymous/67bb53a2697e6655c8df0f4bf37e8aba

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
