### ISSUE TITLE
can't see others in signal 4.7.0 during the video call

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#6742]
I can't see the other guy in the video call, even I told him to click the video button. I can see myself in the small box, but the background is black.

**Comment by nrizzio** [comment]
Please fill out the [issue template](https://raw.githubusercontent.com/WhisperSystems/Signal-Android/master/.github/ISSUE_TEMPLATE.md) in order for us to help you.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
