### ISSUE TITLE
De-sync with contacts form the phone

### ISSUE THREAD

**Issue by DonDon-9097** [signalapp/Signal-Android#6753]
Every now and then Signal disconnetcs a conversation with it's contact, so for example if you have a conversation with John Smith, your conversation will be stripped of his name and surname, and there will be only his number left: 
John Smith >>> +11 111 111 111
And you can no longer get his contat through signal, even though it's still in your contact list.

I think it mostly happens while you get a new message.

### Device info

**Device:** Honor 6 (Huwawei) H60-L04
**Android version:** 6.0
**Signal version:** same problem since I've started using it i all the versions, currently 4.6.1

### Link to debug log
https://gist.github.com/79c7861c8962e77b35276ecbf8bb7032

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
