### ISSUE TITLE
Heart emojis don't get made jumbo

### ISSUE THREAD

**Issue by stephzylstra** [signalapp/Signal-Android#6758]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Heart emojis, or sequences of emojis containing a heart, are always at normal size rather than being jumbo sized, even if there is no other text in the message. Other emojis do go jumbo sized.

### Steps to reproduce
- Send message containing only (non-heart) emojis. Confirm that these are jumbo sized.
- Send message containing only emojis, including at least one heart. Confirm that this is regular size.
- Send message containing only a heart emoji. Confirm that this is regular size.

**Actual result:** Any emoji sequence containing a heart is regular size. Any emoji sequence not containing a heart is jumbo sized.
**Expected result:** Any emoji sequence, including with a heart, should appear as jumbo sized.

### Screenshots
![screenshot_20170623-094003](https://user-images.githubusercontent.com/735413/27460894-25a57f70-57fa-11e7-8034-3405aff6a1f5.png)
![screenshot_20170623-094010](https://user-images.githubusercontent.com/735413/27460891-259f06ae-57fa-11e7-9937-907b5d8ef6e8.png)
![screenshot_20170623-094031](https://user-images.githubusercontent.com/735413/27460892-259fa5aa-57fa-11e7-9f0b-4c716e50332a.png)
![screenshot_20170623-094053](https://user-images.githubusercontent.com/735413/27460893-25a06a3a-57fa-11e7-91c6-ce5fdbd1ba2a.png)

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.6.1

### Link to debug log
Note: Most of the screenshots are from earlier, but I replicated the issue again with a single heart right before I grabbed the debug logs.
https://gist.github.com/7769fff88e3e39b07033881f87aadaad

**Comment by p4nci** [comment]
@stephzylstra  :confused: almost the same environment:
Nexus 5X,
Signal v4.6.1 and
Android 7.1.2 (=LineageOS 14.1)
Works as expected with both emojis: system and Signal's built-in

P.S. I'm talking about :heart:

**Comment by stephzylstra** [comment]
I just got a jumbo sized heart by using the emoji keyboard next to the input text field. Using the emoji drawer on the standard Google keyboard is consistently normal sized regardless of whether I have system or Signal emojis turned on.

**Comment by p4nci** [comment]
well, I don't know if this is signal or keyboard issue :thinking:

**Comment by emdantrim** [comment]
Also, perhaps it's important to note that there are technically two heart emojis -- one of them is heart, as in love, and one of them is hearts, as in cards. (❤️ ♥️) However, neither of them are jumbo'd in Signal (and while we're at it, none of the other playing cards suits ♠️ ♦️ ♣️ are jumbo'd.)

This also happens for a lot of the newer emoji that I assume have not gotten put into whatever emoji index that Signal uses to decide what gets jumbo'd.

I am curious if there is an index of emoji that are recognized by Signal, or perhaps some logic that determines what is or is not an emoji, and I would be happy to try and fill it out more myself if someone could point me in the correct direction. :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
