### ISSUE TITLE
Throttle notifications

### ISSUE THREAD

**Issue by GSPP** [signalapp/Signal-Android#6759]
Notifications for incoming messages are not throttled at the moment. This means that the phone makes a sound or vibration for each and every incoming message, even if they are just seconds apart. I feel like a slave to the phone because it grabs my attention constantly when I'm in the middle of something else. It breaks my concentration.

At the same time, I do want to receive notifications. Just not so many.

I propose:

1. Notify the user at most once every X minutes (default: 15 minutes?) after the last notification or after the last time the user opened Signal. There is no point in telling the user many times that messages are available.
2. Notify about an incoming message not immediately but after 1 minute delay. That way multiple incoming messages can be read in one go instead of being constantly forced to either monitor the chat or be distracted by the notifications. I think this feature must be default off because it adds a delay that users might not expect. I'm not sure.

The delay constants should be configurable to adapt the app to users diverse needs. I hope this feature request makes sense for the product. I'm using Google Android 7.1 and Windows 7 with Signal Desktop.

**Comment by p4nci** [comment]
related to https://github.com/WhisperSystems/Signal-Android/issues/3165, https://github.com/WhisperSystems/Signal-Android/issues/5625, https://github.com/WhisperSystems/Signal-Android/issues/5945

**Comment by Be-ing** [comment]
My idea for dealing with this: #6288

**Comment by GSPP** [comment]
I'm in a Signal Desktop chat right now. Literally, every few seconds my phone buzzes *immediately* when Desktop receives a message. It also buzzes for each and every message. I basically want to be notified by new messages meaning I can't just disable notifications. I have no mitigation against my phone constantly buzzing.

@Signal Team: Can you prioritize this? You have built a very fine messenger, and it's free, but this notification spam is quite a problem.

**Comment by nrizzio** [comment]
@GSPP Please don't bump issues. If the issue is open it's tracked.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
