### ISSUE TITLE
Option to play recorded voice message while it is still uploading

### ISSUE THREAD

**Issue by drws** [signalapp/Signal-Android#6769]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

Current behaviour after the voice message is recorded is that an upload is indicated by the rotating arrow in the message icon and only after the upload is finished, the user can listen to the voice message that was sent. Upload can take some time (especially on 2G) and there is no reason that the voice message cannot be listened right after the capture, while it is still uploading. It's an obvious improvement that does not change any other functionality.

**Comment by FeuRenard** [comment]
Mentioned in #6455, but that should be split up anyway.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
