### ISSUE TITLE
Option to pause voice message recording

### ISSUE THREAD

**Issue by drws** [signalapp/Signal-Android#6770]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

Currently the voice message button records the message while it is pressed down and it has the ability to cancel the recording by swiping to the left side (over the message input field). It would be an useful addition to be able to pause the recording while the swipe is halfway to the left. So that the user presses the button to record, if the need arises (for example to quickly ask another person something) swipes a bit to the left and pauses the recording with that and if the swipe is extended, message recording is canceled.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
