### ISSUE TITLE
Marked verified status still updates groups sometimes

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#6775]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Marking a contact as verified/unverified still sometimes automatically updates all groups the contact is in. The groups jump to the top of the conversation list without any group interaction. The problem was already discussed in #6744.

### Steps to reproduce
I managed to reproduce the problem using two Android virtual devices running a fresh Android 7.1.1.

* install Signal 4.7.4 on both devices
* add phone numbers to each others contact books, as well as another contact
* A sends message to B
* A creates two groups with B
* A sends message to another contact (for reference)
  * see screenshot 1
* try to reproduce the issue by verifying B: no problems
  * see screenshot 2
* A links a desktop device
  * then power off desktop device
* try to reproduce the issue by verifying B: problem shows up (sometimes)
  * see screenshot 3
* put device B into airplane mode
* try to reproduce the issue by verifying B: no problems
* switch off airplane mode on device B: problem shows up without interaction on device A
  * sometimes there are two check marks next to the status message
* unlink desktop device: issue not reproducible anymore

### Screenshots
![pic1](https://user-images.githubusercontent.com/3845150/27649445-16d65082-5c32-11e7-9196-df949563004f.png)
**Screenshot 1: before contact verification**

![pic2](https://user-images.githubusercontent.com/3845150/27649463-24836238-5c32-11e7-8e20-67f2178952e8.png)
**Screenshot 2: contact verification works as expected**

![pic3](https://user-images.githubusercontent.com/3845150/27649526-58d0fe2e-5c32-11e7-9d29-29846173e653.png)
**Screenshot 3: contact verification updates all groups**

### Device info
**Device:** Android virtual device
**Android version:** 7.1.1
**Signal version:** 4.7.4

**Comment by cascheberg** [comment]
I did some more research:
* verify contact B on device A
* A calls `MultiDeviceVerifiedUpdate.onRun` which somehow sends a message to B every time
  * message is not received by B if I comment out that part
* B receives that message in `MessageRetrievalThread`
  * ends up as "unrecognized message"
  * somehow still triggers a read receipt on device A
* read receipt is received by A which calls `incrementDeliveryReceiptCount`, which updates threads
  * issue does not occur when I comment out that call

Some output of my additional logging:
**device A**
```
SmsDatabase.insertMessageOutbox
MultiDeviceVerifiedUpdate.onRun
SmsDatabase.insertMessageOutbox
SmsDatabase.insertMessageOutbox

MessageRetrievalThread
PushContentReceiveJob 1
PushReceivedJob.handle
PushReceivedJob.handle receipt
MmsSmsDatabase.incrementDeliveryReceiptCount
```

**device B**
```
MessageRetrievalThread
PushContentReceiveJob 1
PushReceivedJob.handleMessage false
PushDecryptJob.handle.onRun
PushDecryptJob.handleMessage unrecognized
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
