### ISSUE TITLE
Problems with multiple safety number errors in group message

### ISSUE THREAD

**Issue by scottnonnenberg** [signalapp/Signal-Android#6777]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I only partially addressed the outgoing identity key errors in a partially-sent group message, the error notification went away in the conversation view. But not all recipients had received the message. Also, the verification decision I made for a user didn't show up in the conversation view or on my linked desktop install.

### Steps to reproduce
  - In a group with four participants, all are verified
  - Keeping the conversation open, two participants reregister
  - Attempt to send a message
  - Get an error in the conversation, and you can tap the message for more information. You see two errors, with view buttons.
  - Tap the first 'view' button, and see a dialog explaining the situation. Tap Accept. First error is now gone.
  - Tap the second 'view' button, see the dialog, tap the text to take you to the safety number screen. Then back out of all that - tapping cancel on the dialog, then back to the conversation view.

### Actual/expected
1. The conversation view no longer shows an error. Expected the message to still have the red icon. One recipient never got the message, but the conversation view shows no error.
2. The decision I made about that first user's new identity key was not added to the conversation view. This was also not sync'd to the linked desktop, so a message sent from desktop ran into the two identity key errors even though a verification decision had happened on Android.

### Device info
**Device:** Moto G5 Plus
**Android version:** Android 7.0
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/anonymous/183b9ff4e8104a092b18eec0a95624b1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
