### ISSUE TITLE
Phone number wrongly associated to contact

### ISSUE THREAD

**Issue by lemeda** [signalapp/Signal-Android#6782]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When trying to send message to - or receiving message from - a phone number which only differs by one or two specific digits compared to a number in one's directory, the conversation which opens is the one corresponding to the number in the directory.

I have made some tests, only on French mobile phone numbers, which are in the format +33 (0)6 xx xx xx xx or +33 (0)7 xx xx xx xx,  and here is what I have observed:
- what I have described above applies when the digit right after the leading 6 or 7 changes;
- it also applies when you replace the leading 6 by a 7 or the leading 7 by a 6;
- it also applies if both conditions above are met;
- it seems not to apply when it is another digit which is modified;
- it applies both for numbers written with an international dialling code (+33 6 xx xx xx xx) and for numbers written without it (06 xx xx xx xx);
- it applies both for signal contacts and non-signal ones;
- actually, if the second number is also in the directory and a previous conversation with the first number already exists within Signal, when one tries to start a conversation with the second number, the conversation with the first number opens.

### Steps to reproduce
- Pick up any number in your directory. Let's say it is 06 12 34 57 89, and that the number is the one of  Robert Dupont.
- Try to write a message to a number  where the 6 or the 1 (or both) is changed, for instance 07 12 34 57 89 or 06 92 34 57 89, or 07 82 34 57 89.
- Alternative to step 2: find a way to receive a message from one number such as the ones mentioned in step 2.

**Actual result:** The conversation which opens is your conversation with Robert Dupont, who has the number  06 12 34 57 89. If you send the message, it is sent to that number. 
**Expected result:** The conversation window which opens should correspond to the number you actually typed (or received a message from), and the message should be sent to that same number.

### Screenshots
So, if I type any of the following numbers:
![screenshot_typing_number_1](https://user-images.githubusercontent.com/19377750/27769722-96513d26-5f30-11e7-9c6e-837fc11e24b5.png)
![screenshot_typing_number_2](https://user-images.githubusercontent.com/19377750/27769725-a26c3aac-5f30-11e7-9eef-f34cf2589c1f.png)
![screenshot_typing_number_3](https://user-images.githubusercontent.com/19377750/27769727-abdb6f04-5f30-11e7-9faa-0a5016929f34.png)

When I press "New message to...", the conversation window which opens is:
![screenshot_result](https://user-images.githubusercontent.com/19377750/27769728-b0c7c51c-5f30-11e7-95c8-5483de31c60a.png)
(with the contact "Contact" owning the number +33612345789 previously added in my directory)

### Device info
**Device:** HUAWEI G740-L00
**Android version:** 4.1.2
**Signal version:** 4.6.1

### Link to debug log
https://gist.github.com/efed29ecd96d3ec8728c894903a43e3d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
