### ISSUE TITLE
Signal freezing when trying to send SMS

### ISSUE THREAD

**Issue by fyrstyk** [signalapp/Signal-Android#6784]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When composing an insecure SMS the app freezes and stops responding. Keyboard becomes laggy, and gets stuck on the screen. If in secure mode this does not happen.

### Steps to reproduce
Open signal, select inseure text message, type.

**Actual result:** Keyboard stops responding, phone runs slowly
**Expected result:** Keyboard responds normally, can type an insecure SMS

### Screenshots
![img_20170703_114158 2](https://user-images.githubusercontent.com/28437420/27787504-3b77e228-5fe5-11e7-86fa-fa4ed589cab3.jpg)

### Device info

**Device:** One Plus 3T A3003
**Android version:** 7.1.1
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/49e5447bc4964304280b5976b2ba9609

**Comment by moxie0** [comment]
I can't reproduce this and there's nothing in the debug log. Only difference I could think of would be the character counter.

**Comment by msimonpietri** [comment]
Hi fyrstyk,

I have exactly the same issue ... I try to uninstall/install Signal, switch to another SMS messenger and revert to Signal, replace keyboard from SwiftKey to Swype ... remain the issue ! I'm stuck for sending SMS ...

Have find a workaround on your side ?

Monty

**Comment by fyrstyk** [comment]
Hi

I found the issue on my phone after much twiddling. It is a dual sim phone and the issue also happened in the default SMS client and the one downloaded from Google Play, except the Google app came up with an error..... No default sms message centre. In Settings, then SIM & network set a default SIM for messaging.

Fixed.

I would suggest that a check for this is implemented in Signal, as this is an issue for Dual SIM phones.

Hope that helps.

**Comment by msimonpietri** [comment]
Thank you fyrstyk !!! Yes I'm in dual sim mode ... and I had this parameter set to "always ask" ... now this is fixed !

Thank you again ! And I agree, there must be a check in Signal to avoid this ...

Monty

**Comment by fyrstyk** [comment]
Excellent!

I was set to always ask as well. It seems to affect all SMS platforms even the original one+ platform. Not sure if it is specific to the handset, or an android issue. 

If one of the SMS apps was able to tell me the error instead of freezing up or force closing then I suspect that Signal can be made to check.

Glad you got it sorted, I was seconds away from doing a full wipe on the phone!

**Comment by ccuq** [comment]
I just switched from a OnePlus 3 to a OnePlus 3T and I have the exact same issue. I didn't have it on the OP3 with the exact same configuration (no default SMS provider when using 2 Sims). Seems to be a OP3T issue.

**Comment by compiaffe** [comment]
I can confirm the issue with Signal on a OnePlus 3, as well as the work around to fix it. However, I didn't have any issues in the standard 'Messaging' app.

This bug seems to have been introduced within the last month, as before about 2 weeks ago I had no issues with Signal.

**Comment by drmartinsweden** [comment]
I have this problem on the OnePlus 5, but I already have the default SMS set to SIM1, so the workaround doesn't work for me. 👎

**Comment by Arvoreen75** [comment]
@drmartinsweden one the OnePlus3 I had exact the same problem although It was set to SIM1, what helped was changing the settings and setting them back to SIM1. (Perhaps some bug when they are on default and not really set ?!)

**Comment by denialo** [comment]
I have this problem with OnePlus 3 after it returned from RMA.
Same firmware version.
In signal the back button does not work and the keyboard freezes, so unable to type anything, either secure or insecure message. Tried Gboard and Swift keyboards, same.
Thanks for looking into this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
