### ISSUE TITLE
Emoji icon not visible on LineageOS

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#6785]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using Lineageos on oneplus x with system emojis enabled, the icon for the emoji drawer is not available

### Steps to reproduce
- On lineageos disable signal emojis
- Go to a chat and see that the emoji icon is gone
- Emojis written when signal emojis were active are displayed as system ones (testet with the macbook user and the default smile)

**Actual result:** Go to a chat and see that the emoji icon is gone
**Expected result:** Go to a chat and see the normal emoji icon

### Screenshots
![screenshot_20170703-200541](https://user-images.githubusercontent.com/22525368/27803900-336ff042-602c-11e7-9023-e389ece7bac0.png)

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2
**LineageOS version** 14.1-20170629
**Signal version:** 4.7.4

**Comment by mateoeh** [comment]
This is intended behavior. Use the system keyboard's emoji drawer if you're using system emojis

**Comment by mueller-ma** [comment]
Ok.
Can we increase the padding on the left side of "Signal-Nachricht"?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
