### ISSUE TITLE
Location Link Broken

### ISSUE THREAD

**Issue by mikecardwell** [signalapp/Signal-Android#6786]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using the "Location" function in signal to send somebody your location, the Google Maps link is broken. Clicking it excludes the longitude. Signal seems to detect the comma that separates the latitude and longitude in the query string as the end of the URL. Perhaps it needs encoding as `%2C`.

### Steps to reproduce
- Send somebody your location
- Look at the link which was generated

**Actual result:** Expected link not generated
**Expected result:** Expected link generated

### Screenshots
![screenshot_20170625-135226](https://user-images.githubusercontent.com/330908/27804468-fbc3a6ca-6026-11e7-9917-6e3b147c849a.png)

### Device info
**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 4.7.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
