### ISSUE TITLE
Error downloading MMS message, tap to retry

### ISSUE THREAD

**Issue by jbshirk** [signalapp/Signal-Android#6787]
I have:
- [x ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Error downloading MMS message, tap to retry

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

- receive MMS

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Endlessly fetches same mms without success, no way to stop other than mute/block/delete contact

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Receive mms, or at least terminate loop silently

### Screenshots

Not on Android phones you can't, nope.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://gist.github.com/anonymous/2928697e7acbe6bb20815dbfe5536608

**Comment by jbshirk** [comment]
Many things asked for in template are inappropriate for android phone. 

Ex. Error log dump has to be done on phone and url copied to clipboard. But how to search issues on mobile? It seems impossible.

**Comment by dkogias** [comment]
I'm seeing this __when the phone is on VPN, using [OpenVPN for Android](https://github.com/schwabe/ics-openvpn)__, and only for carrier-delivered multimedia content that is __not__ from my Signal contacts.

MMS content will not download when the VPN is active, but will download without delay if I disconnect the VPN.

Other applications don't seem to have any issues connecting over the VPN (G-apps, Firefox, etc) and I can see their traffic if I `tshark`-snoop on the `tun` device from the VPN server.  However, when I try to download a non-Signal contact's MMS content I see no traffic at all.

**Comment by dcherian** [comment]
@dkogias can the stock SMS app download MMSes when you are on VPN?

**Comment by dkogias** [comment]
@dcherian no, upon further testing, stock SMS app (Messages) has the same behavior.  I also tried excepting Signal from the VPN traffic (VPN app allows that), but I assume MMS up/download is delegated to an Android service that actually handles the traffic, and that doesn't want to play with VPN.

Sorry about the spam, I'll open an issue on the VPN repo.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
