### ISSUE TITLE
Verification over SMS or Call

### ISSUE THREAD

**Issue by TarkanY** [signalapp/Signal-Android#6789]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to register a new second smartphone device for the signal messenger, the first device will be deleted.

### Steps to reproduce
- install on a smartphone device with number verification
- Install on another second smartphone

**Actual result:** the first device will be kicked off without any information for the user
**Expected result:** the user of the first device should get an acknowledge that a second device is logged in. Actually it is not a bug, but for me it is not enough, Signal Protocol is probably the best end to end encryption, but who cares about it, if someone could log in as a second device or else. There should be a better logging situation. I would suggest a small thing, that would change a lot. The security code, which is send over SMS or Call should be just shown in the App. If Alice adds her second smartphone, the verification number should be send inside the signal app. That could give the user a better feeling of authentication and prevents also eavesdropper (like ss7 hacks etc.). But if we wanna go further, signal developer should implement two-step verification. Thank you!

### Device info

**Device:** ZTE Blade v8 and Wiko Robby
**Android version:** 7.0 and 6.0
**Signal version:** 4.7.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
