### ISSUE TITLE
Unable to message as phone number format switches between +1 123-456-7890 and 1234567890 repeatedly

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6790]
I have:
- [X] searched open and closed issues for duplicates.  May be related to https://github.com/WhisperSystems/Signal-Android/issues/6060
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unable to write a message while the phone number re-formats. 

### Steps to reproduce
- Open Signal
- Type a message

**Actual result:** - As a message is being typed, the phone number format changes between +1 123-456-7890 and 1234567890 repeatedly and keyboard inputs are not seen in the message compose field 
**Expected result:** To be able to message. 

### Device info

**Device:** Samsung Galaxy S7 Edge
**Android version:** 7.0
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/1d9358a4190df3bc15481dce22835177

### Temporary troubleshooting solution 
1. Enable All the permissions for Signal
Go to Android Phone Settings > Apps > Signal > App Permissions > Enable all permissions. Even if this is enabled, please re-toggle the setting (turn it off and back on) and restart your phone.
Go to Android Settings.
2. Resync contact accounts
Go to Android Phone Settings >  Accounts > Signal > Menu > Remove Account. The alert of clearing data is incorrect, your messages will not be deleted. > Open Signal > Menu > Refresh / Pull down on the contacts list to refresh
3. If the above steps don't resolve, edit the phone number format and repeat step 2.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
