### ISSUE TITLE
Attachments sent from own desktop cannot be opened.

### ISSUE THREAD

**Issue by He-Ro** [signalapp/Signal-Android#6791]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Attachments other than pictures or videos, for example PDF files cannot be opened if they are sent from my own Desctop client.
### Steps to reproduce
- Use the Desktop to send someone a PDF file
- Open that conversation in the Android client
- Click on the PDF attachment of your own message

**Actual result:**
The PDF does not get opened
**Expected result:**
The PDF gets opened

### Device info

**Device:** Sony Xperia Z5
**Android version:** 7.0
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/a06c8d5a08dd300782cce99d365ab1bc

**Comment by moxie0** [comment]
Is there a PDF viewer on the device? What does it mean to "not get opened?"

**Comment by He-Ro** [comment]
Yes, there is a Viewer installed.
If I send a PDF to myself, then (as with all self sent messages on Android) the message appear twice once as incoming and once as outgoing.
When I click on the outgoing attachment nothing happens.
On the other hand, when I click on the incoming attachment it gets opened in the viewer as expected.

**Comment by Trolldemorted** [comment]
@moxie0 you can easily reproduce this by sending a pdf to yourself from Signal-Desktop: You will able to interact with the direct message, but not the sync message.

**Comment by chiraag-nataraj** [comment]
I can confirm I just encountered this same bug. If you send an attachment to yourself, you will see both messages in the chat, but attempting to save the sent attachment to the device results in "Error while saving attachment to storage", while the received attachment works just fine.

**Comment by He-Ro** [comment]
Please note, that it does not only affect messages sent to yourself. IMHO the more severe case is, when you send an attachment to someone else from your Desktop. Then you cannot open it on your Phone, because you only see the outgoing message. Just had this same case on 4.9.9 again.

**Comment by Trolldemorted** [comment]
@He-Ro this does not affect messages sent to yourself, only synced sent messages.

**Comment by merkste** [comment]
I do experience this problem. However, the file in question is a video file. Is the the same or a seperate issue?
Signal Version 4.10.12
Log File: https://gist.github.com/anonymous/6901a6838a3a2579d42d0d2638d4bb76

**Comment by mpas97** [comment]
I just sent a pdf to a contact, then I wanted to have a look on my phone but the file couldn't be opened nor saved. I think this issue should have a higher priority, it has been opened in july.. version 4.11.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
