### ISSUE TITLE
Location sharing doesn't work even when Google Maps is installed

### ISSUE THREAD

**Issue by belidzs** [signalapp/Signal-Android#6796]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have Google Maps installed on my Xiaomi Redmi 4A, yet when I try to share my location, nothing happens for a second or two, then it looks like something is opening for a moment, but then it returns to the main window (instead of the chat window) without any location provided. 

This is not a duplicate of #6351 as I have Google maps installed.

### Steps to reproduce
- Open chat with a Signal contant
- Click on paperclip/location

**Actual result:** Nothing happens for a second or two, then it looks like something is opening for a moment, but then it returns to the main window (instead of the chat window) without any location provided. 
**Expected result:** My current location should be in the chat window ready to send

### Device info

**Device:** Xiaomi Redmi 4A
**Android version:** 6.0.1 (MIUI v8.5.1)
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/anonymous/77c90a7c2a6cdf37960d0e52e03cddf3

**Comment by johanw666** [comment]
Are you building your own version? If so, this happens if you don't use your own Google Maps api key. You can request this key from Google, connect it with your apk signing key and replace the one in the manifest file with toyr own.

**Comment by belidzs** [comment]
@johanw666 no, I'm using prebuilt Signal from Play Store

**Comment by johanw666** [comment]
I can't see anyting wrong in the logs, but I see Xprivacy mentioned in the logs. Does it perhaps prevent Signal access to location?

**Comment by belidzs** [comment]
@johanw666 good idea, but XPrivacy would normally give Signal a fake location. I have checked, and there was no restriction applied on location. I have now whitelisted Signal completely, but unfortunately I'm still unable to share my location

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
