### ISSUE TITLE
Default group icon too small in share menu

### ISSUE THREAD

**Issue by He-Ro** [signalapp/Signal-Android#6804]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The default icon for groups is very small in the share menu on recent Android versions.

### Steps to reproduce
- Make sure that a group with the default icon is at the top of your last conversations in Signal. (For me four contacts/groups were shown)
- Go into an app, from where you can share stuff (such as an image) in the gallery app.
- Share the picture.
- Let the share window pop up (see screenshot).
**Actual result:**
The default icon for a group is very small.
**Expected result:**
The icon should be normal size.

### Further Info
When clicking on the Signal Icon in the share window then the list of the contacts/groups appears and there all icons have the correct size.
This issue only appears for the default group icon.
Custom group icons, custom contact icons and default contact icons (the letters) all appear normal sized.
Screen size: 720 x 1280 pixel. 4.6 inches.

### Screenshots
![screenshot-blured](https://user-images.githubusercontent.com/3579374/28012325-b4509264-6565-11e7-8b18-74ae28516207.png)

### Device info

**Device:** Sony Xperia Z5 Compact
**Android version:** 7.0
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/9f6788629fe390b37913724f2feaaba1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
