### ISSUE TITLE
[Feature] Introduce "important messages" for better innovative async communication

### ISSUE THREAD

**Issue by DoS007** [signalapp/Signal-Android#6805]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

# Motivation
When people communicate face-to-face they use many concepts without noting it. Due to technologic development in the last decades it got possible to communicate *wherever* the communication partners are and do it *whenever* they want to communicate asynchronously (in some forms this concepts were already present in the past by e.g. writing a letter). But in the digital age this whereever, whenever communication is heavily used and thus is optimized by integrating components that are natural in a face-to-face communication (which is due to evoluation development of humans the natural way ). 

**One such very important integration were smilies/emoticons** which integrate the communication of mood/sentiment/feeling on the level of text based communication. Look how heavily these are used today! How many emoticons/smilies *did you* use the last 3 days, hmm? That was innovation for text based messaging and they got *indispensable for today text communication*.
**Now are you ready for the next innovation??** (I hope you can't wait for it *drum roll please*):  
*Important messages.* I know, I know at the first view this look really boring, but just think about it. When we talk face-to-face we can communicate emotions. By async text messaging we integrated that by introducing emotions/smilies. When we talk face-to-face we can just switch and talk in the present moment about, what is most important to us. By **async messaging we can not do that .... yet**. The "problem" with async messaging is, that we always have a form of mailbox where many messages await us. But what if we don't have time to see all messages? We just want to read the most important messages, but what is important, we can only determine after reading. The contact partner himself has no way to show, that one message is really important (in the face-to-face communication he could just simply speak about the important thing, **but in async communication this competes with his earlier communication**).

So, just one **question for you**: Did you ever have the problem, that someone had open messages from you and you couldn't communicate important messages (and calling would be inappropriate)? 

One of many examples would be, that you want to remind someone of a credit transfer which should be done on the next day (or a meeting, or [...]). You don't want to interrupt your communication partner by calling him (busy person) and just want that when he looks the next time on the phone (in some short free period) he sees and looks at the important message (wihout needing to read and answer to an discussion about another topic you had earlier).

I belief that this feature would have quite an impact, especially for persons who don't always read all messages right away. A question about a cinema visit today eventing would be read in time.
Important messages:  Like emoticons **at first inconspicuous but later indispensable**. 
What do you think? :)

# Realisation example
On the sender: Equip the context menu of the "send button" with a third element (additionally to unsecure sms and signal), called e.g. "Signal - urgent" or something. After writing and sending such a message, signal would switch automatically back in the normal mode. 
On the reciever: He gets the special message with a special notification (e.g. the notification get's a slightly red color and the important messages get a red icon) .

What do you think? :)

**Comment by 464247853** [comment]
It sounds like a great idea I would love to have but it's probably a lot of work to develop it?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
