### ISSUE TITLE
Many copies of same message recieved

### ISSUE THREAD

**Issue by BobCollins42** [signalapp/Signal-Android#6808]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A four person group, with two non-Signal users (therefore a non-Signal group).
Two days ago, I received a picture image (from one of the non-Signal users) about 6 hours after my wife, who is also a signal user, received it.
Today, I have received four more copies of the image (and an unrelated text message from the same person in the group) at about 30 minute intervals.

### Device info
Device: Google Nexus 5X
Android version: 7.1.2
Signal version: 4.7.4

### Link to debug log
https://gist.github.com/ed8846175bcfa289092539ca0a98c4e8

**Comment by johanw666** [comment]
This is a known issue: it uses mms in this case, and sometimes the communication between Signal and the carrier to notify the later that the mms is received fails. Often the message is resent in such a case.

**Comment by mgla** [comment]
@johanw666  Could you maybe link to the primary issue? I would like to track that one.

**Comment by johanw666** [comment]
I was talking about this: https://github.com/SilenceIM/Silence/issues/321, also mentioned here: https://github.com/WhisperSystems/Signal-Android/issues/5396

**Comment by mgla** [comment]
Thanks, maybe also https://github.com/WhisperSystems/Signal-Android/issues/5355 ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
