### ISSUE TITLE
Feature request: Google Photos to pull from photos/video selection

### ISSUE THREAD

**Issue by Carm01** [signalapp/Signal-Android#6810]
Can we have a choice of an application such as **Google Photos** for example to choose from pictures/video as we do not have that choice and there are quite a bit of applications out there that support this?

Thank You

**Comment by moxie0** [comment]
I think we just fire the selection intent, and if an application like Google Photos supports that intent filter then it should be an option. Are you sure that you didn't select "always use this application" for something other than Google Photos?

**Comment by Carm01** [comment]
That option was never asked for to begin with when I installed signal. The second time was after a factory reset. Furthermore, I reset the app preferences for all apps as well. It was never there to begin with. I am attaching two screenshots. One from my Textra app that the other from signal. I never had to fool with anything in Textra to get Google Photo's to show up. It just works. 
Telegram has the option, Allo, Android Messages, Gmail, Hangouts, Tritter, and Textra all have the option to select Google Photos.

![screenshot_signal](https://user-images.githubusercontent.com/6567665/28394306-05ae79a4-6cba-11e7-81a9-a1352180b69c.png)
![screenshot_textra](https://user-images.githubusercontent.com/6567665/28394307-05c01b78-6cba-11e7-857c-2660cac29ec3.png)

**Comment by Dyras** [comment]
I tried this myself and Google Photos in fact does not appear when I try adding a picture, and it never has appeared. My Moto G4 only has Google Photos, it doesn't have any other picture viewing app. I see exactly what the OP is seeing in his 2 pictures. Well, Google Drive aside.

**Comment by Carm01** [comment]
@Dyras 

Thank You for taking the time to post, test and confirm my finding.

**Comment by dcormier** [comment]
I have this same issue. Google Photos is not in the list of options to pick a photo from. This often makes it unnecessarily difficult for me to find an older photo to send.

**Comment by ChrisG683** [comment]
I also have this issue, this would be a massive improvement when it comes to sending photos.   A lot of Android users use Google Photos and their cloud storage to keep photos off of our device to save disk space.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/attach-photos-from-google-photos/2378).
