### ISSUE TITLE
Repeat alerts: per contact setting, allow interval, and maybe add "repeat until confirmed"

### ISSUE THREAD

**Issue by rck** [signalapp/Signal-Android#6813]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
My use case is getting an alert message triggered by a ticketing system via SMS, but every use case in which you really do not want to miss a message would do. If that happens, which can be during the night, I want all bells and whistles go on. I think I could do that with a nasty notification sound, a small interval (e.g., 15s) and a high repeat factor. Obviously I only want that for that particular contact.

A further extensions could be repeating until I move a slider from left to right (like in fire alert 2). But for me that is of minor importance. A high repeat factor with a small interval in a *per contact* setting should do.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
