### ISSUE TITLE
Save Giphy Display Setting

### ISSUE THREAD

**Issue by brianpgrissom** [signalapp/Signal-Android#6815]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Save display setting for giphy (list vs grid). This is NOT A BUG it would be a FEATURE I believe -- Giphy can take a while to load sometimes- so it'd be nice if it would save a preference for the display style- between list and grid.

### Steps to reproduce
- open conversation
- click attachment button
- choose gif
- giphy screen will default to list mode

**Actual result:** giphy defaults to list mode
**Expected result:** giphy should save display prefernce

### Device info
**Device:** Pixel XL
**Android version:** 7.2.1
**Signal version:** 4.8.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
