### ISSUE TITLE
Incoming call stops to ring or doesn't ring on phone with flip shell

### ISSUE THREAD

**Issue by lantsem** [signalapp/Signal-Android#6817]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Phone is used with original flip shell, which comes with magnet to wake screen when open. The lock screen is turned off. On incoming call in closed state phone often doesn't ring or stops to ring after 1s of playing ringtone. Sometimes it plays ringtone completely. This phone started to use Signal with version around 4.0 and never played ringtone in closed state (even for 1s) before 4.8.1. So with 4.8.1 it's better now, but still not as it should be.

### Steps to reproduce
- Close flip case
- Receive a call

**Actual result:** Phone often doesn't ring or ring only for 1 second
**Expected result:** Phone should ring

### Device info

**Device:** Motorola Moto G3
**Android version:** 6.0.1
**Signal version:** 4.8.1

### Link to debug log

https://gist.github.com/anonymous/1dcf449f6326380dfcb769c2c583193a

**Comment by lantsem** [comment]
Tested 4.15.5 version. Still the same problem - ~75% of incoming calls doesn't ring.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
