### ISSUE TITLE
Feature request: Settings for media quality

### ISSUE THREAD

**Issue by PaulXiCao** [signalapp/Signal-Android#6818]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Need an option for media qualities

### Steps to reproduce
- send image taken form within the signal app 
- add image from your album

**Actual result:** Different image qualities are sent to the recipient.
**Expected result:** The app should send images of the same quality or at least ask the user should be able to specify the qualities somewhere in the options

### Screenshots

![picture added from my album app](https://user-images.githubusercontent.com/25491255/28490397-7339fb08-6ed9-11e7-9358-f65b352d8882.jpeg)
![picture taken from within the signal app](https://user-images.githubusercontent.com/25491255/28490396-7338933a-6ed9-11e7-8ac7-f5356aff89b5.jpeg)

### Device info

**Device:** Sony E2303
**Android version:** 6.0.1
**Signal version:** 4.8.1

### Further explanations
The quality of media sent varies with the chosen method (e.g. attach an image file from your album app, take picture within the app).
There should be options in the settings menu that specify the default media quailty and maybe one can even specify qualities on the fly like so: this specific image should be in a lower quality (saving data volume) or this one should be 100%.
Same goes for video and audio..

**Comment by FeuRenard** [comment]
If I understand you correctly, you complain about the quality of images taken directly in-app (camera button in the input panel). It's kind of a feature, that the quality is worse but the image can be taken faster.

There is a forum discussion on dropping in-app image capture in favor of using the camera app:
https://whispersystems.discoursehosting.net/t/does-anyone-like-the-quick-camera-functionality-on-android/791

**Comment by PaulXiCao** [comment]
It's not only about the quality of the in-app camera but media quality in general. Say, you took an image with your phone's camera app in super hi-res (>=5MB?) and you want to send it via signal. Then there is no option to lower the quality in favor for lower bandwidth usage.

**Comment by bitug** [comment]
Yes, an option to reduce all pictures shared with signal to for example 1920x1920px would be very nice!

May be the developers can copy a bit of code from conversations app that has 3 options called [reduce picture quality](https://github.com/siacs/Conversations/search?utf8=%E2%9C%93&q=pref_picture_compression&type=): Never, automatic, always.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
