### ISSUE TITLE
MMS not automatic download on other phone after send.

### ISSUE THREAD

**Issue by deverlex** [signalapp/Signal-Android#6819]
Hi, I using Signal send a MMS over Viettel Telecome to other phone. Other phone need download MMS before view its. But I using Messenger default app, I send a MMS, other phone automatic download and I can view without download action.

I suggest Signal that can automatic download MMS, thanks.

### Device info
**Device:** Sony Xperia M2
**Android version:** 5.1.0
**Signal version:** 4.8.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
