### ISSUE TITLE
Broadcast MMS sends as Group MMS

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6824]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Broadcast MMS sends as a Group MMS (Verizon)

### Steps to reproduce
- Create New group 
- Select contacts where at least one is a non-Signal contact
- In Group view, select the double arrows and choose Broadcast
- Send message

**Actual result:** A group MMS is sent that includes each recipient
**Expected result:** An individual MMS is sent to each recipient

### Screenshots
 N/A

### Device info

**Device:** Pixel XL
**Provider:** Verizon
**Android version:** 7.1.2
**Signal version:** 4.8.1

### Link to debug log
https://gist.github.com/7f7a982555ea0c133f57f7fe78ec12e6

**Comment by Carm01** [comment]
Maybe an option like below in my screenshots of the options in the Textra could be implemented in signal ?

I had this problem in Textra and informed the Dev, and fixed fairly quick resulting in those granular controls. Hopefully we can have that here too :)

I am thinking what happens is any mms is assumed a group messages and all replies go back to the group which is bad.

Android messages I think does this thing too without options for granular control. Google is not to smart alot of the times making common sense decisions i have noticed.

![screenshot_20170801-195119](https://user-images.githubusercontent.com/6567665/28851898-8a24853c-76f3-11e7-9463-9e78648f04b7.png)
![screenshot_20170801-195135](https://user-images.githubusercontent.com/6567665/28851903-913d7cb6-76f3-11e7-895f-9083c449d739.png)

**Comment by parergon** [comment]
I've come across the same or a very similar problem a few times now. There can be very little visual difference between an SMS and an MMS if it only contains text. Some contacts use MMS to send messages to many of their contacts and replying without changing message type (very easy to do) will send your reply to everyone on the original senders recipient list. If the group is of sufficient size, it invariably ends up with a mess of "Who are you" messages.

Implementing a warning and choice of changing message type on reply would be very useful. My SO actually stopped using Signal after encountering the same problem several times (one of her contacts frequently use MMS groups).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
