### ISSUE TITLE
Crash on startup after contact got a new key

### ISSUE THREAD

**Issue by karyon** [signalapp/Signal-Android#6825]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A contact got a new phone. on the next message she sent me, i got that confirmation dialog where it says "or maybe they just reinstalled signal", where i confirmed. directly afterwards, signal crashed ("unfortunately, signal has stopped.") whenever i open signal, it instantly crashes again, although i can at least see the contact list behind the crash notification. a few seconds later after confirming the first crash, i get another, second "unfortunately, signal has stopped.".

apart from a fix, any help on what i can do to use signal again would be appreciated as well :)

### Device info

**Device:** Galaxy Nexus
**Android version:** 6.0.1 (Cyanogenmod 13)
**Signal version:** i got the message and the first crashes with 4.6.1, then while troubleshooting, upgraded to 4.8.1 with the same result. the sender of the message installed signal from the app store three days ago, so should have 4.8.1

### Link to debug log
this is the logcat when i first got the message plus a few attempts to open the app
[logcat_first.txt](https://github.com/WhisperSystems/Signal-Android/files/1179218/logcat_first.txt)

possibly cleaner logcat of a single attempt to open the app
[logcat_short.txt](https://github.com/WhisperSystems/Signal-Android/files/1179210/logcat_short.txt)

**Comment by karyon** [comment]
unresolved duplicate here: https://github.com/WhisperSystems/Signal-Android/issues/6312

**Comment by karyon** [comment]
i worked around this by renaming messages.db and its journal, starting signal, deleting the newly-created files, renaming back the old messages.db (not its journal though), and then signal started properly again. it kept crashing. debug log: https://gist.github.com/anonymous/6fce071b4c870e6ed78d6b6bfcd95860 (upper half of this, lower half is #6836)

**Comment by moxie0** [comment]
@karyon Both this and #6836 have the same root cause of data corruption. Could be a bug, could also be something that happened with your device.

**Comment by karyon** [comment]
okay.... if there is anything i can do to find out more, let me know.

**Comment by osbugs** [comment]
Any chance of fixing this data corruption without having root access? As far as I can tell, I do not have access to messages.db without being root, right? I have set Signal as my default SMS app, and I do not want to lose old messages/photos by having to clean all data just to be able to get in contact with people again. Any chance that Signal will sanitize its database automatically in such cases?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
