### ISSUE TITLE
When I initiate a voice call, the other end cannot hear me

### ISSUE THREAD

**Issue by righy** [signalapp/Signal-Android#6827]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I initiate a voice call to any of my contacts, they can never hear me while I can hear them. However, when I receive a voice call, we both can hear each other and it works fine.

### Steps to reproduce
- Open Signal
- Call any contact
- Wait for them to pick up

**Actual result:** The contact cannot hear me.
**Expected result:** The contact should be able to hear me.

### Device info

**Device:** HTC Desire (htc_bravo)
**Android version:** 4.0.4 (eng.k900.20120624.010557, IMM76I)
**Signal version:** 4.6.1

### Link to debug log
Output of `adb logcat` (anonymized) just after reproducing the bug after a fresh reboot: https://gist.github.com/righy/39fb39c8e2bf2d10031fde7aab2d748c

**Comment by RoboticEarthling** [comment]
I am having this issue as well. I have only tried calling one other person (using an iPhone), and when I initiate the call neither of us can hear anything, but if they initiate the call it works fine.

Here is my log after initiating and receiving a few calls:
https://gist.github.com/anonymous/c657c018a574a4cd0e6a74520cc397a2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
