### ISSUE TITLE
Check if updating user is in group

### ISSUE THREAD

**Issue by pajowu** [signalapp/Signal-Android#6828]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Groups can be compromised if group id and one member is known, as [documented here (page 8 and following)](https://eprint.iacr.org/2017/713.pdf)

### Steps to reproduce
See link from Bug description

### Possible fix

This should be fixed by checking whether a user is part of a group before updating it.

**Comment by FeuRenard** [comment]
Page 18:
> Open WhisperSystems is currently developing a new group management system with advanced administrative features so that **they decided not apply our fix**.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
