### ISSUE TITLE
Conversation update messages convert to normal message on export/import

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6829]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Conversation update messages are rendered as normal messages after import from a plaintext backup.

### Steps to reproduce
- call a contact
- export plaintext
- reinstall Signal
- import plaintext

**Actual result:** In the conversation is now a usual conversation item saying "Called \<contact>"
**Expected result:** There is a `ConversationUpdateItem` like before reinstalling Signal.

### Screenshots
![device-2017-07-28-205428](https://user-images.githubusercontent.com/16167751/28732268-8d769122-73d7-11e7-8733-9747d7332e57.png)

### Device info

**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 4.8.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
