### ISSUE TITLE
Group MMS usually sends twice - Verizon, Signal 4.8.1 

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6835]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Verizon group MMS sent messages are duplicated/sent repeatedly (2x)

### Steps to reproduce
- Be connected to Wifi & the Mobile network
- Send a group MMS

**Actual result:** Contacts in the MMS group usually receive the MMS twice
**Expected result:** MMS is sent once/received by contacts once

### Device info

**Device:** Samsung Galaxy S6 (samsung SM-G920V)
**Android version:** 7.0
**Signal version:** 4.8.1

### Link to debug log
https://gist.github.com/39a19d577fe8674f3c5515420d330de3

The recipients are on Verizon and T-Mobile

Time stamps for the last know multiple receipts: 
July 29th 2017 12:28:04 
July 29th 2017 12:31:51 
Juky 29th 2017 12:51:42

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
