### ISSUE TITLE
Crash on linking desktop app

### ISSUE THREAD

**Issue by karyon** [signalapp/Signal-Android#6836]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After scanning the QR code of the desktop app, while the desktop app showed "syncing contacts", the android app crashed. it instantly crashes on every subsequent start. i fixed it by removing messages.db and importing an older plaintext backup.

### Device info

Device  : samsung Galaxy Nexus (yakju)
Android : 6.0.1 (cb9d8bbe53, lineage_maguro-userdebug 6.0.1 MOB31T cb9d8bbe53)
Memory  : 32M (29.01% free, 256M max)
Memclass: 96
OS Host : iktinos.acc.umu.se
App : Signal 4.8.1

### Link to debug log
https://gist.github.com/anonymous/6fce071b4c870e6ed78d6b6bfcd95860 (the upper crashes are #6825, search for the first occurrence of `Non-successful response`, that's where this issue here starts

**Comment by karyon** [comment]
one addition: while playing around, i managed to link the desktop app but the android crashed when i sent a message with the desktop app. after multiple rounds of reinstalling the chrome app and removing messages.db and importing plaintext backups, everything seems to be working. i can't say what actually fixed it, though.

**Comment by skorokithakis** [comment]
My application is also crashing on startup after the latest update, and a friend mentioned that he got crashes when using the desktop app as well. I'm not sure if my issue is linked to the one here, but it seems it might.

**Comment by moxie0** [comment]
@skorokithakis It sounds like you're a beta tester running the beta, this issue is for 4.8.1.

**Comment by skorokithakis** [comment]
@moxie0 Ah, I had forgotten about that. Indeed, I am running 4.9.0, sorry.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
