### ISSUE TITLE
Add ability to mark messages as unread

### ISSUE THREAD

**Issue by pwd-github** [signalapp/Signal-Android#685]
That's something that's available in the AOSP Text Messaging app but is missing from TSM for Android.

**Comment by jonathancross** [comment]
Hi All, any progress on this?  It's been almost a year. ;-)
Enthusiastically waiting for this feature.

**Comment by moxie0** [comment]
I'm skeptical that we want to do this. I think this use case should be covered by inbox/archive when we do that instead.

**Comment by jeremymasters** [comment]
Seems like a "reminder" capability is the real desire here and the inbox idea lends itself easily to that.

**Comment by svrnwnsch** [comment]
Maybe it is just me, but I don't use the archive function at all.

My usecase for unread messages would be the same as I use it for emails. I read the message but don't have time to answer immediately so I would like to mark the Thread/Message (I don't care which) as unread to later answer it.

I hope this will be added to Signal as for me it is a fundamental feature which is still missing.

**Comment by colans** [comment]
This isn't implemented in [Riot](https://riot.im/) either: https://github.com/vector-im/riot-web/issues/4406

**Comment by tmanaud** [comment]
I would love to see this "Mark as unread" feature, either thread or individual message.
As this is the way I manage my emails too.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
