### ISSUE TITLE
Feature Request: Disable Voice

### ISSUE THREAD

**Issue by Ingineerix** [signalapp/Signal-Android#6855]
There is no apparent way to disable incoming voice calls or stop them from ringing.  (Big annoyance in the middle of the night.)  I would like the ability to refuse all voice calls if I so choose or at least mute the ringtone and make it vibrate only.

**Comment by FeuRenard** [comment]
This is basically a duplicate of #6411.

**Comment by Ingineerix** [comment]
Except it would also be nice to have the option to disable calls entirely.  Many times I find myself on high-latency networks when travelling and VoIP will just not work.   This can also be a concern for metered data.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
