### ISSUE TITLE
Feature Request: App Shortcuts

### ISSUE THREAD

**Issue by lokesh-krishna** [signalapp/Signal-Android#6856]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
Support for app shortucts in Android 7.1 and above.  

Here is the relevant documentation: [App Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html)

**Comment by FeuRenard** [comment]
#6099 was an attempt to implement this.

**Comment by OriginalFannibal** [comment]
Ah...
Guess I'll wait for it to be reopened someday then. The issue can stay though, right? It might even get someone to reopen the PR.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
