### ISSUE TITLE
[Feature Request] Don't allow saving or forwarding attachment

### ISSUE THREAD

**Issue by obifur** [signalapp/Signal-Android#6857]
When sending attachments I cannot be sure that they will stay private. E.g. when sending a photo of myself I don't want it to be forwarded to another person..

**Comment by Trolldemorted** [comment]
You can never be sure, no one is stopping your contacts from building Signal-Android themselves, and removing such a restriction.

**Comment by FeuRenard** [comment]
Similar discussion in #5757.

**Comment by obifur** [comment]
Yes, I understand and totally agree that it will never be 100% secure and it will be possible to save the attachment in some way. However as long as you keep this in mind (maybe add a hint) it would be fine in my opinion. It should just be more difficult to do so..

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
