### ISSUE TITLE
Dark Theme: Keyboard suggestions unreadable with black on black text

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6864]
I have:
- [X] searched open and closed issues for duplicates. This is most related to https://github.com/WhisperSystems/Signal-Android/issues/615
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Regardless of the OS light/dark theme, keyboard suggestions in Signal appear as black on black text. 

### Steps to reproduce
- Set Signal to Dark theme
- Open Signal, mistype a word
- Check keyboard spelling suggestions

**Actual result:** Suggestions appear as black on black text
**Expected result:** Spelling suggestions to have a lighter colored text

### Screenshots
OS Dark theme + Signal Dark theme: 
<img width="222" alt="screen shot 2017-08-08 at 3 55 44 pm" src="https://user-images.githubusercontent.com/4898366/29098053-13dfb824-7c52-11e7-924c-fde296758100.png">

OS Light theme + Signal Dark theme: 
<img width="220" alt="screen shot 2017-08-08 at 3 56 17 pm" src="https://user-images.githubusercontent.com/4898366/29098093-45d22312-7c52-11e7-81fa-33c8d7c80a9e.png">

### Device info

**Device:** Samsung Galaxy Note 5
**Android version:** 7.0
**Signal version:** 4.8.1

### Link to debug log
 
OS Dark theme + Signal Dark theme: https://gist.github.com/9f2b4be42692d5ecf87ff72ea0c122e7
OS Light theme + Signal Dark theme: https://gist.github.com/44c3a0863689a714081674369adb110f

**Comment by moxie0** [comment]
I kind of doubt we have any control over that, but maybe someone can check

**Comment by nribeka** [comment]
I think this is probably vendor specific as they might have their own specific keyboard implementation. This screenshot is from Moto X using gboard. You can check your keyboard setting by long pressing the , (comma) button when the keyboard is on the screen.

![motox-gboard](https://user-images.githubusercontent.com/1143145/35515503-5c74f528-04d7-11e8-8bd0-7abe48526c68.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
