### ISSUE TITLE
Exclude disappearing messages from backup

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6865]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Disappearing messages should be excluded from backup, because they are by definition not meant to persist.

### Steps to reproduce
- Send or receive a disappearing text message
- export a plaintext backup
- search for the message body of above message in the exported file

**Actual result:** The message is included in the backup.
**Expected result:** The message should not be included in the backup (even if it were encrypted) as the message cannot disappear there later.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
