### ISSUE TITLE
Possibility to check the connection status to the signal server

### ISSUE THREAD

**Issue by micressor** [signalapp/Signal-Android#6869]
I have:
- [ X] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Enhancement description
I would like to have the possibility to check the connection status between the signal app and the signal server.

**Actual result:** There is no way to check the connection status to the signal server. A similar possibility already exists in the iOS version of the Singal app.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
