### ISSUE TITLE
Some emojis are not visible in dark theme

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#6870]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The emoji https://unicode-table.com/de/1F463/ and probably other are complete black and therefore not visible on a dark background.

### Steps to reproduce
- Switch to dark theme
- Open emoji drawer

**Actual result:** On the faces page between the nose and the single eye seems to be no emoji
**Expected result:** On the faces page between the nose and the single eye I can cleary see the footprints icon.

### Screenshots
![screenshot_20170812-105544](https://user-images.githubusercontent.com/22525368/29239384-d6551a54-7f4d-11e7-89e1-0acee5d05387.png)

### Device info
**Device:** Oneplus X
**Android version:** 7.1.2 Lineageos 14.1
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment]
This issue has to exist for a long time! Either nobody uses dark theme or dark theme users don't use emoji 😆 
The emojis below are bareley recognizable on the phone's screen.
![signal-2017-08-12-155755](https://user-images.githubusercontent.com/16167751/29241309-4b7928f6-7f77-11e7-9793-ac6b2387069f.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
