### ISSUE TITLE
New group: no way to see if contact has Signal account

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#6871]
---

I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----

### Bug description
In the "New group" view there is no way to see if a contact uses Signal or not. You have to try and if not you see the message

> You have selected a contact that doesn't support Signal groups, so this group will be MMS.

~~and there is no way to undo this (remove the bad contact) and you have to close the view and try again (and enter the group name again and select the group icon again).~~

### Steps to reproduce
- tab on "New group"
- try to create a Signal only group
- add a contact without Signal account

**Actual result:** There is no difference between contacts with and without Signal account
**Expected result:** Users with Signal account should be marked as Signal users (maybe by adding a label). Btw. if you decide to replace/fix this view you should also display the contact avatars in the suggestion list.

### Screenshots

![screenshot_20170813-145021](https://user-images.githubusercontent.com/5571650/29249820-3622c38e-8037-11e7-9381-385d9662c571.png)
![screenshot_20170813-145027](https://user-images.githubusercontent.com/5571650/29249821-36255bbc-8037-11e7-82bd-8ef2baad344c.png)

### Device info

**Device:** LG Nexus 5
**Android version:** 7.1.2
**Signal version:** 4.9.6

**Comment by dcherian** [comment]
Related #4035

**Comment by nrizzio** [comment]
> there is no way to undo this (remove the bad contact)
You actually can. There is an X to the far right of each contact, it's even in your screenshot, but it's very faint. Perhaps it could be colored a little brighter.

**Comment by sedrubal** [comment]
Ah thanks, I didn't see this. I created a new issue for that.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
