### ISSUE TITLE
New group: x to remove contacts is not visible on dark theme

### ISSUE THREAD

**Issue by sedrubal** [signalapp/Signal-Android#6872]
---

I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----

### Bug description
When you create a new group and want to remove a member you just added you have to tab on the <kbd>:x:</kbd>. But on dark theme it is not really visible

### Steps to reproduce
- use dark theme
- tab on "New group"
- add a contact

**Actual result:** there is a <kbd>:x:</kbd> for each contact but it is dark gray on black background
**Expected result:** The <kbd>:x:</kbd> should be light gray / white / red or any lighter color on black background

### Screenshots
![screenshot_20170813-145027](https://user-images.githubusercontent.com/5571650/29249821-36255bbc-8037-11e7-82bd-8ef2baad344c.png)

### Device info
**Device:** LG Nexus 5
**Android version:** 7.1.2
**Signal version:** 4.9.6

This issue is separated from #6871.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
