### ISSUE TITLE
Feature request: Show letter instead of hash (#) in circle for SMS with automatic name

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#6874]
Sometimes I receive SMS messages from organizations that have somehow automatically a name with them associated (for example from Google), but no number.

These messages appear in the Signal message history with a hash (#) in the circle in front of them, instead of the first letter of the automatically provided name.

I would prefer to see the first letter of the automatically provided name instead of the #.

Android: 4.2.2
Phone model: bq Aquaris 3.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
