### ISSUE TITLE
Inconsistent display of date labels (landscape - portrait switching)

### ISSUE THREAD

**Issue by He-Ro** [signalapp/Signal-Android#6875]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The date separation labels are not centered, when switching from landscape to portrait and the other way around.

### Steps to reproduce
- Open a conversation while in landscape mode. See Picture 1.
- Scroll to a date label.
- Switch from landscape to portrait mode by turning your phone. See Picture 2.

**Actual result:** The date label "today" is shifted to the right. Note that the other label is centered correctly. It was not in the view while in landscape.
**Expected result:** The date label is centered.

### Screenshots
Picture 1:
<img src="https://user-images.githubusercontent.com/3579374/29272179-404f0fe8-80ff-11e7-95fc-2abe81bcf0d2.png" width=400/>

Picture 2:
<img src="https://user-images.githubusercontent.com/3579374/29272187-49021676-80ff-11e7-9ece-1b2127fbfa54.png" width=400/>

### Device info

**Device:** Sony Xperia Z5 compact
**Android version:** 7.1.1
**Signal version:** 4.8.1

### Link to debug log
I do not think, that this is necessary. But if you think otherwise, then I can post a debug log.

Additional info:
I think that this is linked to #2930, where the incorrect action bar height and font size is tracked. This might be a new symptom to the same root cause. I think, that this has to do with `configChanges="orientation"` being set in the `AndroidManifest.xml`. As a user already stated in that other issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
