### ISSUE TITLE
disappearing messages does not cover call logs

### ISSUE THREAD

**Issue by ilf** [signalapp/Signal-Android#6879]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The awesome "disappearing messages" feature does not cover call notifications (`MessageRecord_called_s` and `MessageRecord_s_called_you`). IMHO they should disappear the same way other messages do. For one, these kinds of metadata records can be sensitive information, too. And from a user perspective, "messages" should cover *all* message types.

### Steps to reproduce
- set "disappearing messages" to any value
- make or receive call
- wait until time for disappearing messages has passed

**Actual result:** call notification does not disappear
**Expected result:** call notification disappears

### Device info
**Device:** any
**Android version:** 7.1.2
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment]
Some thoughts about this are noted in #5628

**Comment by RiseT** [comment]
My I add that from a visual perspective, it looks quite messy if some message records remain while most others have disappeared.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/disappearing-messages-for-calls/2110).
