### ISSUE TITLE
[Issue] SMS messaging part in Signal slows down and becomes unusable

### ISSUE THREAD

**Issue by rtcw13** [signalapp/Signal-Android#6883]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to open SMS conversation in Signal. It slows down and becomes unusable. Scrolling through the texts becomes laggy.

Bringing up a keyboard takes a few seconds and if keyed in, will not input a character due to extreme lag.

### Steps to reproduce
Note: this may not be reproducible bug but here's what I did:

Wiped the phone and reinstalled a select few apps including Signal.

Set up Signal as normal and used plaintext import option to keep my messages.

Signal ran normally.

Removed SIM 1 (Three) then moved SIM 2 to slot 1 (EE). Added new SIM to slot 2.

Signal started to run slowly when viewing SMS conversations. Other Android Google app (Message) also had the same issue.

Wiping conversations and other data as well as reinstalling the app did not work.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
N/A

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
It shouldnt slow down.

### Screenshots
N/A

### Device info

**Device:** Oneplus 3
**Android version:** 7.1.1
**Signal version:** 4.9.8

### Link to debug log

https://gist.github.com/44d802059305d74dbf56de6c27f29110

**Comment by aahalai** [comment]
Have you set the default sim setting for SMS to "always ask"? That seems to have been causing issues as per this thread: https://github.com/WhisperSystems/Signal-Android/issues/6784

Setting a default sim for messaging fixed the issue for me. I'm also on a Oneplus 3.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
