### ISSUE TITLE
MMS Thread from wrong user: "1".  Further: replying to thread goes to a unrelated signal user

### ISSUE THREAD

**Issue by Philippe23** [signalapp/Signal-Android#6885]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My wife received a few MMS (image) messages from a non-signal (iOS) user whom she normally exchanges MMS/SMS messages with.  These messages ended up in a thread attributed to "1" as opposed to the non-signal user.  She responded to this thread, but instead of the replies going to the other user in the thread (or erroring out), they went to me!?  (I am a signal user.  We both have Android phones.)

More info:

The "1" thread actually appeared  Apr. 6th with a completely different MMS (image) non-signal (iOS) user.  My wife said she deleted the thread.  It's since re-appeared with this other non-signal (iOS) user, who sent 2-3 messages that appeared this way over two days.  She's never tried replying before.

### Steps to reproduce

Have not tried to reproduce.

**Actual result:** Message went to the wrong user.
**Expected result:** Messages should go to the other contacts in the thread, not to an unrelated contact.

### Device info

**Device:** Moto G4
**Android version:** 7.0
**Signal version:** 4.8.1

### Link to debug log

[device_log_issue6885.txt](https://github.com/WhisperSystems/Signal-Android/files/1272938/device_log_issue6885.txt)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
