### ISSUE TITLE
MMS not working

### ISSUE THREAD

**Issue by rrkitlo** [signalapp/Signal-Android#6890]
### Bug description
Signal works fine apart MMS. I can make calls, sens SMS but when MMS comes in the content/picture does not download. It says: Error during download, touch to try again. It happens both on Wifi and 3G internet access.

### Steps to reproduce
difficult to say, Maybe see my log report

**Actual result: MMS is not showing picture like in native Android SMS app
**Expected result:** MMS should download picture and show it.

### Device info
**Device:**Huawei p8 ALE-L21
**Android version:** 6.0
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/bfb420ffe14e81825be4082d4e909331

**Comment by bristow** [comment]
Same thing with my phone : Meizu Pro 5 without Gapps (Android 5.1)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
