### ISSUE TITLE
crash when opening the same contacts message history - org.whispersystems.libsignal.InvalidKeyException: Bad key type: 1

### ISSUE THREAD

**Issue by ggaavv** [signalapp/Signal-Android#6896]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unable to open 1/50 contact's message history (same contact every time). Every other contact's message history readable. can reply to a message from quick reply in notification.
Every time I click on contact's message history the app crashes and closes.
logcat error "org.whispersystems.libsignal.InvalidKeyException: Bad key type: 1"
full log link attached at bottom.

### Steps to reproduce
Click on the same contact every time causes the crash.

### Link to debug log
https://gist.githubusercontent.com/anonymous/cbc6e51e5d43edaae8b9c1eb872d6ce1/raw/52a5f15ba848413e450ca697a32c95c793f459b6/cat.log

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
