### ISSUE TITLE
Signal Crashes when engaging video

### ISSUE THREAD

**Issue by pintopwnie** [signalapp/Signal-Android#6904]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when turning video on.

### Steps to reproduce
- Make phone call
- talk for a bit
- hit video and then Signal crashes

**Actual result:** Signal crashes and closes
**Expected result:** Start video conversation and display video

### Device info

**Device:** Nexus 5X running CopperheadOS
**Android version:** 7.1.2
**Signal version:** 4.9.8

### Link to debug log
https://gist.github.com/anonymous/ce750ff82097bf2080440613eb4a1272
Already reviewed #6852 which was related to Chromium being disabled. I have it enabled.

**Comment by moxie0** [comment]
There is no crash in this log, can you capture a debug log after the crash?

**Comment by pintopwnie** [comment]
Moxie, thanks for the quick reply. Please see line 95 & 96 & 188 and let me know if I'm missing something. Thanks.

**Comment by pintopwnie** [comment]
92  08-27 19:02:16.410  5250  8721 I chatty  : uid=10066(org.thoughtcrime.securesms) expire 2 lines
93  08-27 19:02:16.468  5250  8723 I chatty  : uid=10066(org.thoughtcrime.securesms) expire 9 lines
94  08-27 19:02:18.259  5250 15013 I chatty  : uid=10066(org.thoughtcrime.securesms) expire 1 line
95  --------- beginning of crash
96  08-27 19:02:18.263  5250 15013 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffffd0 in tid 15013 (Thread-35)
97  08-27 19:02:23.530  8745  8745 I chatty  : uid=10066(org.thoughtcrime.securesms) expire 159 lines
98  08-27 19:02:24.715 8745 8818 I chatty : uid=10066(org.thoughtcrime.securesms) expire 3 lines

**Comment by nrizzio** [comment]
The issue with your debug log is that the relevant crash information was occluded by the logcat rate limits (chatty). Can you capture another debug log, this time with the crash visible?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
