### ISSUE TITLE
Android 4.2.2 contact search results take 20-30 sec

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6906]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Searching for a contact in Signal takes 20-30seconds before displaying results.

### Steps to reproduce
- Open Signal
- Tap on message compose
- Search for non-Signal contact

**Actual result:** Wait 20-30 seconds to see the entire search result
**Expected result:** faster search results

### Screenshots
N/A

### Device info

**Device:** WIKO RAINBOW
**Android version:** 4.4.2 stock
**Signal version:** 4.9.9

### Link to debug log
 https://gist.github.com/9dcaa7fc8219038b22d3227a4ca78cc9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
