### ISSUE TITLE
Pictures send from Signal desktop are not visible on master android device

### ISSUE THREAD

**Issue by mlsxlist** [signalapp/Signal-Android#6908]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send a picture from Signal desktop to someone, the picture is sent successfully to the recipient  but on the Android Master device I only see an empty white frame.

### Steps to reproduce
- send picture from Signal desktop to a friend
- check if she received the picture
- check on your Android master device if the message has been synced

**Actual result:*The picture is successfully sent to friend but on the Android Master device the picture is not visible
**Expected result:** The picture send from Signal Desktop should be received by the friend and the message should be synced to the master device.

### Screenshots
![signal-2017-08-29-203727](https://user-images.githubusercontent.com/6071818/29843107-660b7198-8cfa-11e7-8386-0ebc7a3f1082.png)

### Device info
**Device:** samsung SM-N910F
**Android version:** 5.1.1
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/a5e559d18f6b4d96a70b9d56e6f25492

**Comment by mlsxlist** [comment]
Just noticed that this happens only, when I have set on my Android

Media auto-download 

When Roaming
None

Once I set the Option
 
When Roaming
Images

the image is downloaded and visible.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
