### ISSUE TITLE
notification reply button doesn't always work for groups

### ISSUE THREAD

**Issue by timotree3** [signalapp/Signal-Android#6910]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I receive a notification for a signal message I see buttons to:
- Mark read
- Reply

When using the aforementioned reply button to send a message to a group, sometimes only one of the group members gets my reply.

### Steps to reproduce
- create a new group which contains insecure users.
- send a message so the group is saved
- leave the group screen so you can get notifications about it
- wait to receive a message from the group
- when a message arrives, reply directly to the notification (see above description)

**Actual result:** only one of the members in the group receives a direct message containing your reply.
**Expected result:** all of the members receive a group message containing your reply.

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.9.9

### Link to debug log

Can't provide one now. Will try to if anyone asks me to.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
