### ISSUE TITLE
Signal using too much data

### ISSUE THREAD

**Issue by batiste93** [signalapp/Signal-Android#6914]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The Signal app seems to be consuming an exorbitant amount of data.

### Steps to reproduce
- Use the app normally on Android

**Actual result:**  Almost a gig of data usage.
**Expected result:** Less than 10mb of usage

### Screenshots
![screenshot_20170902-130740](https://user-images.githubusercontent.com/1128614/29997436-123a08f6-8fe1-11e7-85c2-6ab03de4b03a.png)
![screenshot_20170902-131246](https://user-images.githubusercontent.com/1128614/29997441-1f77e3c6-8fe1-11e7-955f-c49854481630.png)

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/anonymous/dc049b40543097f0efafc84b07129965

**Comment by FeuRenard** [comment]
Do you receive many large files?
Is media auto-download enabled?
Do you use the GIF search often? (#5843)
Do you use video calls often?

Text messages should not produce such large traffic consumption and voice notes either.

**Comment by Trolldemorted** [comment]
did you change the media download settings recently?

**Comment by batiste93** [comment]
@FeuRenard 

- Not really, like 5 files  *  1MB.
- Never touched default settings.
- I did use the GIF search two or three times recently-- that's probably it.
- Always on WIFI.

**Comment by skorokithakis** [comment]
I got the same this month. 11 MB in the foreground, 1 GB in the background. Signal ate up my entire data plan, and I rarely use it, and almost never receive any files over it, let alone big ones. I also never video call.

**Comment by skorokithakis** [comment]
I believe this might be related to Signal desktop, which I do use. I never use it while the phone is on mobile data, though.

**Comment by moxie0** [comment]
Any time you send/receive a message using Signal Desktop, you're sending/receiving it via Signal Android. If you don't have the phone on while that's happening, it will "catch up" as soon as you turn your phone on. You can configure Signal Android not to download media on certain networks if you wish.

Also, if you're using Signal without Play Services installed, it will use a lot of data.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
