### ISSUE TITLE
Signal keeps a lock on the earpiece speaker after ending call

### ISSUE THREAD

**Issue by msxmine** [signalapp/Signal-Android#6915]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My phone (HTC 10) uses the earpiece (calling) speaker along with the bottom-firing speaker for media playback, HTC calls this "BoomSound Hi-Fi" and it noticably enchances audio quality.
Unfortunaly, after performing a voice call using Signal, this speaker seems to be locked, and is not used for media playback system-wide, untill Signal is killed from Android settings (just swiping it away in multitasking view does not help)

### Steps to reproduce
- Open Signal and select a contact also using signal
- Perform a voice call (any length)
- Exit Signal to home screen
- Open any app with media playback (youtube).

**Actual result:** No sound comes from the earpiece speaker untill Signal is killed
**Expected result:** Signal has no effect on audio setup system-wide after ending the call

### Device info
**Device:** HTC 10
**Android version:** 7.0 NRD90M stock
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/anonymous/014984344c90627acfad261269f7c695

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
