### ISSUE TITLE
Messages not delivered

### ISSUE THREAD

**Issue by carmenaa** [signalapp/Signal-Android#6916]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Hello, I would report a bug and hope that this can help improve this cool software. Yesterday a friend of mine sent me some message but the program says that they are not been delivered (with a red exclamation point). His internet was good and also mine, maybe there was a temporary interruption of your servers as has happened a few months ago. Now he tried sent me again these messages but I am able only to receive new messages from him, so these messages are still pending and not delivered.

I would suggest to introduce a function that can automatically send these messages without the need to do that manually or that delete "pending" messages after a reasonable amount of time from your servers and from client for security reasons.

### Steps to reproduce

**Actual result:** there is no function that tries to automatically send not delivered messages which remain pending forever. 
**Expected result:** 
- introduce a function that can automatically send these messages without the need to do that manually 
- delete not delivered messages after a reasonable amount of time from your servers and from client for security reasons, especially who choised to use the disappear message option.

### Device info

**Device:** all
**Android version:** all
**Signal version:** 4.9

**Comment by FeuRenard** [comment]
The red exclamation mark symbol indicates problems in the sending process. So in case it appears, the message did not reach the server yet.

Reasons for sending problems can be problems with the server or the sending phone's internet connection. The latter will be more probable if nobody else on the internet reports sending problems. Further information here: https://support.signal.org/hc/en-us/articles/212535538-How-do-I-know-if-a-message-has-been-delivered-

**Comment by carmenaa** [comment]
Hi FeuRenard and thanks for your reply. 
Update!
My friend was able to send the messages that came with two checkmark, but I did not receive them, I'm only able to receive new messages from him. We both activated the option disappear messages after a week, but it may not have been that they were deleted before reading them because the messages were written yesterday. What may have happened? My fear is that someone might intercept what he writes or that the server keeps a copy of these messages permanently, so there remains a trace that day we wrote.

So I think my request is legitimate, delete after a reasonable period of time these "lost" messages or not delivered messages. It has no meaning to keep messages that have not been delivered for years, no? Thanks.

**Comment by knaudult** [comment]
---Reporting---

There is currently no official statement about the management of non-delivered messages in the long run. These messages should automatically destroyed after a reasonable period of time (like an year) or this could be a security issue.

**Comment by alkanet88** [comment]
I reproduced this problem today unintentionally. I installed signal on phone, then wanted to see what would happen if I installed it on a second phone with the same number. the message from my first phone could no longer send. but mine just stayed "fail to send" forever, and I had to reset signal on the first phone to fix it.

**Comment by knaudult** [comment]
https://whispersystems.discoursehosting.net/t/what-happens-exactly-to-messages-that-are-not-received/1265

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
