### ISSUE TITLE
Proximity sensor not used on HTC devices

### ISSUE THREAD

**Issue by msxmine** [signalapp/Signal-Android#6917]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The proximity sensor does not turn the display off during (voice) calls.
In the stock phone app, this functionality works perfectly.
This seems to affect only HTC devices, as evidenced by comments on bug 4434, and the fact that it works fine on my Samsung Galaxy S6E+

### Steps to reproduce
- Make a signal call
- Put the phone next to your ear (vertical position)
- Look at the screen

**Actual result:** The screen stays on unless you press the power button. You propably pressed something on the screen
**Expected result:** The screen turns off

### Device info

**Device:** HTC 10
**Android version:** 7.0 stock
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/anonymous/06e40e8deefcd098bef5263ac0e2418d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
