### ISSUE TITLE
Use speakerphone settings for videocall audio when a headset with no mic is plugged in

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#6918]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

tl;dr: Signal doesn't have good handling of no-microphone headphones during video calls.

Happy to capture a debug log if necessary, but this seems pretty straightforward so I didn't bother.

### STR:

1. Plug in headphones that do not have a built-in microphone
2. Make a Signal videocall
3. Speak normally, holding the phone in front of you
4. Other person says something to the effect of "you're really quiet"
5. Turn on speakerphone
6. Other person says "oh you fixed it" but now audio is coming out of the phone speakers

### Device info

**Device:** Nexus 6P
**Android version:** CyanogenMod 13.0-20161220-SNAPSHOT-ZNH5YAO3XH-angler based on Android 6.0.1
**Signal version:** 4.9.9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
