### ISSUE TITLE
Group MMS broken on ASUS Zenfone AR

### ISSUE THREAD

**Issue by Skylead** [signalapp/Signal-Android#6922]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Texts, calls and media messages work as expected, group texts result in individual threaded MMS Error downloading, tap to retry (never downloads)

### Steps to reproduce
- Set Signal as default messenger
- Have someone include you in a group text
- Fail to get messages

***NOTE*** - Moved call log history from old Nexus 5X (if relevant)

**Actual result:** individually threaded errors: MMS Error downloading, tap to retry
**Expected result:** Group messages

### Device info

**Device:** ASUS Zenfone AR (VZW_ASUS_A002A)
**Android version:** 7.0
**Signal version:** 4.9.9

**Comment by Dstrator** [comment]
I am also seeing this issue coming from a 5X.  I have the same ASUS A002A, non Verizon edition.
This issue extends to the non-Signal MMS senders.  Those MMSs are not downloadable via WiFi nor Cellular.  
Feedback from Signal would be helpful.

Bug description

Texts, calls, MMS texts result in individual threaded MMS Error downloading, tap to retry (never downloads)
Steps to reproduce

    Set Signal as default messenger
    Have someone without Signal send an MMS
    Select to 'Download' MMS
    Failed to Download Message indefinitely 

NOTE - Moved call log history from old Nexus 5X (if relevant)

Actual result: individually threaded errors: MMS Error downloading, tap to retry
Expected result: Group messages
Screenshots
Device info

Device: ASUS Zenfone AR (ASUS_A002A)
Android version: 7.0
Signal version: 4.11.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
