### ISSUE TITLE
Missing I18N for avatar image cropping view

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#6934]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The buttons "Cancel" and "Done" of the avatar image cropping view are not translatable.

Aside from this, I'd suggest some explanatory "what to do" type text (or at least a title text) for that view. Some users might get lost there.

### Steps to reproduce
None

### Screenshots

None

### Device info

**Device:** Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.10.3

### Link to debug log

None

**Comment by moxie0** [comment]
I don't think that's our code, so we can't really localize it. We'd have to write our own image cropper.

**Comment by RiseT** [comment]
@moxie0 Closed by https://github.com/WhisperSystems/Signal-Android/commit/962fb60ffbf039d3813bd1ef9f23e377f4529e0e ("Don't synchronize MMS groups to sibling devices")...? I guess that's accidental?

**Comment by PiCob** [comment]
It should be #6935

**Comment by moxie0** [comment]
whoops

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
