### ISSUE TITLE
Profiles are not showing up

### ISSUE THREAD

**Issue by schmeat** [signalapp/Signal-Android#6937]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My friend and I have upgraded to profile pic beta version. We have both created profiles, however we are unable to see each other's profiles. 

### Steps to reproduce
- create profile (friend as well)
- share profile to group
- view that profiles do not show up
- create group with just me and contact
- profiles still do not show up
- restarting phone and client does not change anything

**Actual result:** Contact name and picture showing up from saved contact info
**Expected result:** Profile pictures/name should show 

### Device info
Device  : LGE LG-H873 (lucye_global_ca)
Android : 7.0 (17206141157cd, NRD90U)
OS Host : LGEACI8R13
App : Signal 4.10.3

### Link to debug log
https://gist.github.com/anonymous/bb8dcb5cd85b80886ebc4b52bd0a9c84

**Comment by moxie0** [comment]
You've sent each-other messages?

**Comment by FeuRenard** [comment]
Sounds like intended behaviour. Profile info is only shown when no contact info is present on your phone.

**Comment by johanw666** [comment]
@FeuRenard yes, that baffled me too when I first tested it until I read that existing data overrides the profile data. In most other messengers I use (WhatsApp, Viber, Skype, BBM) this works the other way around (profile data preceeds over contact info) so some explaination might be usefull if only to prevent a lot of reactions like this.

**Comment by p4nci** [comment]
how about an option (in profile settings) for overriding contact info i.e. you can switch between "contact info" and "profile info"?
Yes, I know about "no more options" Development Ideology :thinking:

**Comment by schmeat** [comment]
That's strange if that's intended behaviour. The wording says it's automatically shared to people in your contacts, which seems fairly pointless because when won't you have that info for them?   

If profiles are for only people your don't have on your list then I wouldn't ever be able go use it. Lol.

**Comment by p4nci** [comment]
@schmeat 

> The wording says it's automatically shared to people in your contacts

and that's true
> If profiles are for only people your don't have on your list

I think you misunderstood this point. Please read a [blog post about Profiles](https://signal.org/blog/signal-profiles-beta/)

**Comment by bme13** [comment]
Not sure if a ticket is the correct place to discuss this specific behavior however I do agree with @p4ci that it would be nice have an option available for overriding the contact info. If I understand correctly in the current situation one must remove the contact info (picture) in order to be able to see the signal profile information for a specific contact. This contact info however is used by other apps as well e.g. phone app so one can not use the signal profile for a specific contact together with a picture in the address book that's used by other apps.

**Comment by FaizKhan5** [comment]
If you save a number of your friend with his name so signal profile name is not show to you and if you set a picture on your friend's contact in address book so you can't see his signal profile picture.

Clear ?

**Comment by hlorenz** [comment]
> how about an option (in profile settings) for overriding contact info i.e. you can switch between "contact info" and "profile info"?
Yes, I know about "no more options" Development Ideology 🤔

Is there already an issue for this feature? I really like the idea because when using Signal I want to see Signal images, not my own ones. I know there are people who don't like this, so why not let us choose?

**Comment by entonjackson** [comment]
There should be an option to allow overriding local profile picture with the profile picture set through signal.

**Comment by SlappyHours** [comment]
Same problem here. My contacts and I were excited about the profile feature, but noone is seeing the profile name and picture.

I do not want to delete the name and picture of my contacts as there are other apps using this info.

There should be an option to override this.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
