### ISSUE TITLE
Same contact: two signal numbers but only one now shows in signal section of contact list

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6941]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a contact that uses two different phones, each with its own number.  In Signal 4.9.9 I could look at my contact list in Signal and see the same user listed twice, each entry having a unique number which looks and works correctly.  In 4.10.3 (need to download 4.10.5 yet), Only one of the user's numbers is listed in the Signal contacts section.  The other number is listed in the non-signal contacts, but upon selecting that, it does allow sending signal messages.

### Steps to reproduce
- Have one contact with two separate Signal #'s
- Tap the pencil icon to write a test message

**Actual result:** In the Signal contacts section, note that you only see one entry/number for said contact.
**Expected result:** Either two rows of the same contact, each with a different number, or some way to directly message either number if I want to from this list of users.

### Device info
**Device:** Samsung Galaxy S8
**Android version:** 7.0
**Signal version:** 4.10.5

Note: The desktop app syncs things over correctly to show two separate contacts with whom I can message, so this must just be a display bug.

**Comment by jeremymasters** [comment]
This user should have both entries as signal numbers as this person has two phones/numbers, each with signal. 
![20171116_150241](https://user-images.githubusercontent.com/4967949/32918367-72bfdc8a-cadf-11e7-89f4-424a32dff60c.png)

**Comment by jeremymasters** [comment]
I installed signal fresh on another phone and both numbers/entries show up for this contact, but my main phone still has this issue of only showing one number even though the user has two signal contact numbers.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
