### ISSUE TITLE
Video thumbnail not shown after sending

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#6944]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After sending a video, the thumbnail placeholder is shown with play overlay above. The actual thumbnail is shown not until going to the conversation list and also on reentering the conversation.

I already played with this. This issue is solved, as soon as I delete [this if-block](https://github.com/WhisperSystems/Signal-Android/blob/5ffee53faa17eaceefe51efaa6d4c87ab29bd357/src/org/thoughtcrime/securesms/components/ThumbnailView.java#L123). But that's not what was originally intended. This block exists for a reason, I assume.
So it seems the thumbnail generation finishes at a time that the video message is still displayed in preflight mode and slides are not reloaded in preflight mode. However we could make it reload, if the slide changed.

### Steps to reproduce
- attach a video somehow (sharing from outside, forwarding inside etc.)
- hit send
- wait for end of upload

**Actual result:** thumbnail placeholder is shown with play overlay (suspicious, overlay should only appear with the thumbnail, not the placeholder). But: when you quit the conversation, the conversation list entry shows the correct thumbnail. On reentering the conversation the correct video thumbnail is shown.
**Expected result:** thumbnail is shown

### Screenshots
![screenshot_20170909-005250](https://user-images.githubusercontent.com/16167751/30234005-d6a31e22-94f9-11e7-8fe7-9d01c2623e1d.png)

### Device info 1
**Device:** Fairphone 2
**Android version:** 6.0
**Signal version:** 4.10.5

### Device info 2
**Device:** AVD Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.10.6

### Link to logcat output
https://gist.github.com/FeuRenard/66a724963366f88249f5fec6ca1fbc28

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
