### ISSUE TITLE
Wrong message order after sync from Signal Deskto to Signal Android

### ISSUE THREAD

**Issue by tandiljuan** [signalapp/Signal-Android#6946]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

The messages order is wrong after the synchronization finish in Signal Android from messages written in Signal Desktop. Similar to these issues:

- https://github.com/WhisperSystems/Signal-Desktop/issues/1043
- https://github.com/WhisperSystems/Signal-iOS/issues/1398

### Steps to reproduce

- Disconnect Android (Signal Android) from Internet
- Chat on Signal Desktop (it's needed send and receive messages)
- Connect Android (Signal Android) to Internet
- Let Signal Android synchronize the messages.

**Actual result:** After the messages synchronization, you'll see first all your messages and then all the other person messages.
**Expected result:** The messages must be in the order they went sent and received.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.9.9
**Signal Desktop:** 0.43.3 (`3a733ea`)

**Comment by ArmeF97** [comment]
Same

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
