### ISSUE TITLE
Missing privacy option: hide last message from conversations list

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6956]
Sometimes I open Signal to show something to another person (e.g., recall a detail of a conversation we had on Signal). In this situation I don't like the other person to be able to see the last message I exchanged with all my other Signal contacts. I would like to have a privacy option like: "Hide last message from conversations list" (or "show last message", selected by default, to maintain a positive phrasing).

A message like "**3 unread messages**" is shown if there are unread messages.

This is similar to what is already done with notifications.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
