### ISSUE TITLE
Feature Request: Button to Abort Upload

### ISSUE THREAD

**Issue by ax3l** [signalapp/Signal-Android#6958]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request description

While sending large images or videos on a bad connection, allowing to abort the process would be really useful which otherwise blocks the already low bandwidth fully.

### Steps to reproduce

- select a large video
- start sending on a slow network
- try to abort the sending to send an other file (since you might have accidentally selected the wrong one)

**Actual result:** have to wait for the first send to finish.
**Expected result:** Allow me to abort the send.

### Screenshots

Can't screenshot since it's disabled. But just imagine the small circle going from 0 to 360 degrees *very, very slowly* on your GSM connection.

### Device info

**Device:** all?
**Android version:** 7.1.1
**Signal version:** 4.9.9, 4.10.12

**Comment by hpaantee** [comment]
Agreed, the only way seems to delete the message, but this is not really user-friendly, especially if you added a text message as well.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
