### ISSUE TITLE
[Bug] deleting own profile it's not possible

### ISSUE THREAD

**Issue by p4nci** [signalapp/Signal-Android#6960]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
~~This is a feature request~~ Deleting picture and name (i.e. deleting profile) it's not possible

### Steps to reproduce
- go to Settings -> profile settings -> try to delete picture and name

**Actual result:** Once you have set a profile there is no possibility to delete this. Deleting picture and name doesn't work. 
**Expected result:** a possibility to delete own profile e.g. setting a profile without picture and name or there should be a button "Delete this profile"

### Device info

**Signal version:** beta v4.10.8

**Comment by nrizzio** [comment]
When you say there is no possibility, do you mean that the "finish" button is physically disabled, or that you get an error message after you press it?

**Comment by p4nci** [comment]
@nrizzio nope, "Finish" button works, but you can't delete both: picture and name. There is an error message. It seems like you can't set a profile without name :thinking:

**Comment by cascheberg** [comment]
Partially fixed by 893cf9c01dd8c9c0aa4cb6c4493fbd3474b6f538.

@moxie0 Deleting ones avatar is somehow not possible. The server never returns an empty string.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
