### ISSUE TITLE
4.9.9 repeatedly crashing, cannot enter passphrase

### ISSUE THREAD

**Issue by 1000plus-signal** [signalapp/Signal-Android#6961]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to open Signal, it flashes the "Enter passphrase" screen and then crashes, and I get the "Unfortunately, Signal has stopped" Android error.

This behavior started before Burning Man, but I didn't have time to troubleshoot it then, and I had my phone off that week & Labor Day weekend anyway. I was hoping it was a transient issue that would somehow work itself out when I came back to cell signal, but no such luck.  I didn't get a chance to poke at it until this weekend, when I went to the Play Store to see if there was any update to the Signal app.  Updating to 4.9.9 gave me the ability to enter my passphrase once, and I could see my conversation list for a moment, but then an "updating database" screen came up, stayed for about 60 seconds, and then Signal crashed again. After it stopped during the "updating database" it's back to the same behavior (crash at the "enter passphrase" screen) as before the update.

Restart / wait / try again did not resolve - I waited about five minutes.  I'm using Signal from the Play Store. Airplane mode doesn't change the behavior. 

I looked at issue #6948 but this doesn't appear to be a duplicate (different platform, different logcat errors)

### Steps to reproduce
This happens every time I try to open Signal.

**Actual result:**
When I tap the Signal icon, it flashes the "Enter passphrase" screen and then crashes, and I get the "Unfortunately, Signal has stopped" Android error.

**Expected result:**
When I tap the Signal icon, it allows me to enter my passphrase and access my messages.

### Device info

**Device:** LG G3 LGLS990
**Android version:** 4.4.2
**Signal version:** 4.9.9

My phone is rooted.

### Link to debug log
I can't capture a debug log because it won't run, but attached is the adb logcat. 
[signal crash - adb logcat.txt](https://github.com/WhisperSystems/Signal-Android/files/1297849/signal.crash.-.adb.logcat.txt)

**Comment by moxie0** [comment]
Looks like data corruption. A value that got serialized into the database is malformed when it's being read back out. That value is needed to process a pending message, and so an assertion is failing every time Signal tries to process it. If you have root on the device we can fix it up manually.

**Comment by 1000plus-signal** [comment]
I do have root, and I'd love to get it working again! Please let me know what is needed.

Thanks,
Lisa

**Comment by moxie0** [comment]
@1000plus-signal I don't think manual intervention is necessary after all. Here's a custom APK that should resolve the issue.

Steps:

1) Install from here: https://mega.nz/#!N8chUDhD!aIHNaXbDyeFL5_D8E6gFzRcp13_f6b1lVckUm5CZFPM

2) Run the app. It will crash.

3) After the crash, capture an adb logcat. This time, the log will include the "malformed" value that's causing the problem, which I want to see in order to make sure I understand what's happening.

4) Run the app again. It should not crash this time.

**Comment by 1000plus-signal** [comment]
Thank you! I'm traveling tonight, just downloaded the APK and will try to do this in the morning...

**Comment by 1000plus-signal** [comment]
Had some travel challenges, just got a chance to do this.  It worked!  Thank you very much!! Attached is the logcat output.

Is there any way to migrate my Signal message database onto a new phone, or export it into a format that I can read on another system, without losing data?  I'm concerned that this data corruption is a harbinger that my phone (which is quite old) is nearing the end of its usable, and I don't want my current text message store (which I've been rolling forward for several years, since it contains conversations with many loved ones) to be stranded on this phone.   To be honest, the main reason I'm still on this old phone is because I don't see any way to migrate off it without losing my Signal messages!

I've tried previously to backup Signal on this phone (with My Backup Root or Titanium Backup) & restore it onto a potential replacement, but without success.  I couldn't find any way to get Signal to access the message database on a new phone.  Message export only gets SMS (not MMS) so I lose all my group texts and texts with images...  which are the majority of conversations with family & friends. I'd really appreciate any suggestions on how I can preserve this information...
[signal-debug-apk-logcat.txt](https://github.com/WhisperSystems/Signal-Android/files/1307699/signal-debug-apk-logcat.txt)

**Comment by 1000plus-signal** [comment]
(I can open that question as a separate issue if you prefer! It's just top of mind because this issue - and getting it working again, yay! - made me realize how hosed I would have been if the error hadn't been fixable...)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
