### ISSUE TITLE
Profiles: cannot share profile without adding to contacts after having replied

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#6964]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In a new conversation with an unknown contact, users can't go back to choose "Don't add, but make my profile visible" after replying once.

#### Note
It's also not obvious that "add to contacts" will make one's profile visible, unless you know the details of the implementation. One extra line of text at the top could fix that.

### Steps to reproduce
- receive a message from someone not in your contacts
- reply to conversation

**Actual result:** `UnknownSenderView` will disappear. Now the only option left to share one's profile is to save that contact to phone contacts, which is not obvious.
**Expected result:** There should be an option in conversation settings to make one's user profile visible.

### Device info
**Signal version:** 4.10.9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
