### ISSUE TITLE
Android app may be syncing wrong phone number from a contact with two phone numbers

### ISSUE THREAD

**Issue by divergentdave** [signalapp/Signal-Android#6971]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm opening this [as requested](https://github.com/WhisperSystems/Signal-Desktop/issues/1406#issuecomment-327647980) to follow up on a problem I experienced in the desktop client.

As background, there's a contact in my address book on my Android phone that has two cell phone numbers. Both are labeled as "Mobile" in the Android Contacts UI. The first number, ending in 199, doesn't have Signal installed, but the second number, ending in 060, does.

In a group message that contains this contact, when I send a message from my Android phone, everything works fine, but when I send a message to the same group from the desktop app, I see "some recipients failed", with an error message of "number is not registered" for that contact. If I view the group members, either on Android or on desktop, I see the wrong phone number (ending in 199, without Signal installed) for this contact. (even though on Android I can send messages without error)

### Device info
**Device:** LG Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.9.9

### Link to debug log
Desktop debug log posted at https://gist.github.com/6f0eca3e20d21ac9c265658b6ad36488

(cc @scottnonnenberg)

**Comment by haffenloher** [comment]
Did you verify that when you open "Edit group" on Android, the number ending in 060 is in the list of members and the one ending in 199 isn't?

**Comment by divergentdave** [comment]
No, in the edit group menu, I see the 199 number.

**Comment by haffenloher** [comment]
Yes, sorry, I overlooked that info in your original post. See my edit above.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
