### ISSUE TITLE
profiles: the "share profile banner" takes so much space that the quick reply function does not even display the first unread message

### ISSUE THREAD

**Issue by rainerzufall** [signalapp/Signal-Android#6973]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

### Bug description
In a group where you don't want to share your profile, the "share profile banner" (in conjunction with the unread message count) take so much space that the quick reply function does not even display the first of the unread messages [see screenshot]. This issue is related to https://github.com/WhisperSystems/Signal-Android/issues/6927 ( and also https://github.com/WhisperSystems/Signal-Android/issues/6966). When these aforementioned issues are adressed - this issue will also be fixed. 

### Steps to reproduce
- get new messages
- hit the quick reply button
- see that you don't even see the first message you just received because of the profile share banner (in conjunction with the unread message count) [see screenshot]

### Screenshot
![screenshot_20170917-164805](https://user-images.githubusercontent.com/12666598/30521960-fe4ccb28-9bc8-11e7-9308-9a8ad3855b04.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.10.10

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
