### ISSUE TITLE
First bulk SMS invite does not send, after sending a 1:1 invite SMS the second bulk invite SMS succeeds

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#6974]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The first attempt at sending a bulk SMS invite does not succeed. After individually sending an SMS to a contact, the bulk invite (to one contact) succeeds in sending. Signal is not set as the default SMS app.  

### Steps to reproduce
1. invited a friend via main menu
2. See grey alert 'invitation sent'
3. Sms did not go through
4. invite the same friend from 1:1 chat
5. See grey alert 'sms successfully sent'
6. Sms succeeds. 
7. Repeat steps 1&2, and SMS succes

**Actual result:** Invite SMS from Signal's main view does not succeed the first time.
**Expected result:** Sends Invite SMS the first time

### Screenshots

N/A

### Device info

**Device:** ZTE BLADE L110
**Android version:** 5.1
**Signal version:** 4.9.9

### Link to debug log

https://gist.github.com/d7fecb5a86d4f16d199d3da7a89d53c7

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
