### ISSUE TITLE
An alert about the links

### ISSUE THREAD

**Issue by knaudult** [signalapp/Signal-Android#6976]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
60/5000
Hello, maybe some of you know well this scenario... Someone sent to us a unwanted link and we visit it by error just with one click upon it (damn touchscreen!). I think before open link with just one click, a possible solution to this could be that Signal ask us something like "do you want visit this website and open in your browser? Click yes or no" with the possible reminder of the answer to save time. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** there is no notice system as described above and with just one click, maybe even by mistake, you visit a unwanted website.
**Expected result:** Improving link management, a solution might be the one described above.

### Device info

**Device:** all
**Android version:** all
**Signal version:** 4.9.9

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
