### ISSUE TITLE
MMS: sent mms to two non-signal users. Response went to individual thread of one user

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6979]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sent mms to two users. One replied and it went to a 1:1 thread I already had with that one user. 

### Steps to reproduce
-send mms to two non-signal users
-one of them replies

**Actual result:** message goes into 1:1 that with that one user
**Expected result:** message goes into group mms conversatio

### Device info
**Device:** Samsung galaxy s8
**Android version:** 7.0
**Signal version:** 4.10.11

### Link to debug log
https://gist.github.com/anonymous/4fcd795ff00d4a7aeebe702d70644d2a

**Comment by moxie0** [comment]
Does the non-signal user who replied see a "group" conversation or a 1:1 conversation with you?

**Comment by jeremymasters** [comment]
It came to them as a group. These are the two users that when I send individual sms, I always get an undelivered message but it actually went through but when u send mms it's fine. Weird.

**Comment by jeremymasters** [comment]
They are on signal now so it is currently mitigated.  They are novice users so not sure if I can do testing on them. Might be able to test on others sporadically.

**Comment by moxie0** [comment]
@jeremymasters Did the response message that ended up in a 1:1 conversation with you get received by the other non-signal user as well?

**Comment by jeremymasters** [comment]
@moxie0 I haven't asked them yet and I'm a little hesitant to at this point due to the fact that they are on the fence about using it and are non-tech at all.  I'd be glad to test this though in any other way really.  If I knew how to pm on github I could give more details.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
