### ISSUE TITLE
Constant prompt to "Invite to Signal" on each new message from a contact

### ISSUE THREAD

**Issue by Neurogami** [signalapp/Signal-Android#6982]
I have:
- [X ] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

A new text message sent from Amazon creates a prompt "Invite to Signal".

I click the X to close the notification.

The next new text message from Amazon again prompts me to "Invite to Signal". Again I close the prompt.  This happens with every new message I get from Amazon.

### Steps to reproduce
- Get a new text message from Amazon (though I don't know what would be special about them, just the only instance I've seen)
- You get a prompt "Invite to Signal" 
- Close that prompt

**Actual result:** 

- Next message from that contact (here, Amazon) generates yet another "Invite to Signal" prompt.

**Expected result:**  

Should never see that "Invite" prompt for a contact after I've declined it.

### Screenshots
None.

### Device info

**Device:** LG Stylo LG-H631
**Android version:** 6.0
**Signal version:** 4.10.11

**Comment by johncf** [comment]
Related #4471

Please create a "Never ask me again" checkbox. I'm quite annoyed by this. I'll invite them personally if I think Signal is that great, without the app constantly bothering me to do so.

**Comment by thenktor** [comment]
@johncf Thanks for pointing me to the settings. I searched, but could not find it. I also think this is very annoying!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
