### ISSUE TITLE
Crashed doing nothing incredible

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#6989]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
App was in the background and when I started it, I had to enter my password.

### Steps to reproduce
- simply had a couple MMS conversations of about 12 people

**Actual result:** Had to enter password after seeing  something about the app needing to close or wait
**Expected result:** app opens with no password needed because I already entered it earlier 

### Device info
**Device:** galaxy s8
**Android version:** 7.0
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/48a243037e04ba477edf49ef5c6e8736

**Comment by moxie0** [comment]
There's no crash in this log. Your password can fall out of memory at any time, or you could have gotten an app update. If the app crashes, you will see "Signal has unexpectedly stopped." Is that what you saw?

**Comment by jeremymasters** [comment]
I didn't see "Signal has unexpectedly stopped", but the phone screen was off.  I have everything set to leave Signal alone about power-save, etc.  There was no app-update because it had happened earlier in the day.  I'll close this out if there's no issue seen in the log and re-open if I experience it again.

**Comment by jeremymasters** [comment]
https://gist.github.com/48a243037e04ba477edf49ef5c6e8736

**Comment by jeremymasters** [comment]
I should add that from time to time I was receiving/sending with a non-signal MMS group that had around 12 people.  The UI began to slow response to taps on users, options, etc and then finally after some time ceased all response to touch...then finally I received the dialog that signal wasn't responding and if I should close or wait.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
