### ISSUE TITLE
Alice cannot call Bob, Bob gets "missed call" notification

### ISSUE THREAD

**Issue by czaviar** [signalapp/Signal-Android#6990]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Alice is trying to call Bob,without any success. When Alice terminates the calling, then Bob gets a "missed call" notification.

### Steps to reproduce
- Alice starts to call Bob, she sees "Calling" screen
- Bob can't see any notification
- When Alice stops calling, then  Bob gets only "missed call" notification

### Device info

**Alice Device:** Xiaomi Redmi Note 4
***Bob Device: LG G3
**Android version:** 6.0
**Signal version:** 4.9.9

### Link to debug log
Alice log: https://gist.github.com/czaviar/31f4f6d89c868f6f3040be097bf16f6f
Bob log: https://gist.github.com/czaviar/c9bbf249d84f87b9dc67b44a6598485d

**Comment by moxie0** [comment]
Bob's log is strangely filtered and cut off. Hard to tell from that, but it looks like something on the network is preventing a successful ICE handshake. Are Alice and Bob's clocks both accurate?

**Comment by czaviar** [comment]
Yes,  they both have the same time from the cell provider.

**Comment by paulohefagundes** [comment]
I had the same issue, then I realized that it was only my phone that wasn't making / receiving calls. I ended up finding out that the problem was that my phone had an adblocker [DNS66](https://f-droid.org/packages/org.jak_linux.dns66/) running. Once I disabled [DNS66](https://f-droid.org/packages/org.jak_linux.dns66/), I was able to make and receive calls

**Comment by billie80** [comment]
You can exclude specific Apps under the Apps tab instead of disabling DNS66 completely. If you just want the domain excluded using the hosts tab maybe you find the blocked host in the logcat output. It should also be hidden somewhere in the signal source code ;-)

**Comment by czaviar** [comment]
I do not have any adblocker installed.

**Comment by riyapenn** [comment]
Unsure of who Alice and Bob in this scenario are, but here are two logs from 4.10.12 for this issue:
Xiaomi Redmi Note 2 / Android 5.0.2: https://gist.github.com/a689695be31333c2ac4d78cb732e36b6
Huawei Y3 II Dual-SIM / Android 5.1: https://gist.github.com/2b098a591141d06f892b22737983d8be

**Comment by moxie0** [comment]
@riyapenn are their clocks synchronized?

**Comment by jmayday** [comment]
@czaviar I had exactly same issue. In my case problem was caused by Blokada app (http://blokada.org/). Just after turning it off Signal calls started working again.

**Comment by czaviar** [comment]
@jmayday Thanks, but I do not have any adblocker installed.

**Comment by alexanderadam** [comment]
@czaviar do you use a VPN? Or the people you want to call?

**Comment by czaviar** [comment]
No I don't.  But once I switch on the VPN on both devices the problem
dissappears.

01.11.2017 8:42 AM "Alexander Adam" <notifications@github.com> napisał(a):

**Comment by alexanderadam** [comment]
My guess: if it works when you are using the VPN it seems that your "native" network is blocking (and the VPN isn't).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
