### ISSUE TITLE
Groups: Gap between name and message-content too big

### ISSUE THREAD

**Issue by Wasseranomalie** [signalapp/Signal-Android#6995]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The gap between one sender and his message is too big (since 4.10.x).

### Steps to reproduce
- Open group
- Wait for someone to write a message

**Actual result:** Big gap between name and message of sender
**Expected result:** Smaller gap between name and message of sender

### Screenshots

![gap](https://user-images.githubusercontent.com/6809794/30916115-db4cdfdc-a398-11e7-97de-36c226cb749e.png)

### Device info

**Device:** Nokia 6 / Nexus 5X
**Android version:** 7.1.1 / 8.0.0
**Signal version:** 4.10.12

**Comment by nrizzio** [comment]
I'm pretty sure that the gap is intentional. It helps the user distinguish between message content and the sender name.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
