### ISSUE TITLE
Aesthetic and UX improvements on first run (pre-filled phone number; registering aborts on bad connection)

### ISSUE THREAD

**Issue by Lesik** [signalapp/Signal-Android#7007]
Hey,

I assume that this part of the app (first run) receives the least testing, as the user is only exposed to it for a short time.

After getting several friends to try Signal, I have went through the registering process several times, and I noticed two UX annoyances:

- On first run, the phone number is pre-filled with a weird, invalid phone number (something like +49 176 0000 0000). It doesn't look good and confuses the user. If this is supposed to help the user understand what should be put into the field, please use `android:hint` instead.

- If during registration internet connection is lost, even if only for a few seconds, registration is aborted (understandably), but the app prompts you to start again by editing your phone number. There is no need to adjust the phone number, as at this step the phone number has already been confirmed, the confirmation code was received, the only thing that's missing now is to register online. A simple "retry" button would be nice, as there is no reason to re-confirm the phone number by re-receiving the confirmation code.

Thank you for your time.

**Comment by moxie0** [comment]
> On first run, the phone number is pre-filled with a weird, invalid phone number (something like +49 176 0000 0000)

Unfortunately, I think this is what the SIM card reports is the phone number. In the US, it's typically the complete phone number, so the field is prepopulated and the user only has to tap "register."  But perhaps it doesn't return accurate information in other places.

**Comment by Lesik** [comment]
@moxie0 I see. I have several ideas:

- try to filter this single mistake only (just +49 176 0000 0000)
- try to filter by carrier, this bug always occurred to me on ALDI TALK (MEDION Mobile)
- try to filter out weird looking numbers, e.g. if SIM card reports a number that contains four zeroes, that is most likely a mistake. in case of a false positive (somebody actually has a number with four zeroes), I think these occurrences are so rare that it's OK to make these few people type in their number manually.
- a ⌫ button at the end of the EditText field, so that the phone number can be cleared in an instant

Do you have any thoughts on my second suggestion, splitting the registering process into separate parts that can be retried separately, without the need to confirm the phone number again just because there was a connection error during a later step of the registration?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
