### ISSUE TITLE
Exif orientation tag is not respected for profile pictures

### ISSUE THREAD

**Issue by exploide** [signalapp/Signal-Android#7010]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When selecting an image as a profile picture, the Exif orientation tag is not respected. This is also true for group pictures.

### Steps to reproduce
- take a picture in portrait mode (using your dedicated camera app, not any in-Signal functionality)
- select the image as your profile picture

**Actual result:** the picture's orientation is wrong
**Expected result:** the picture is properly rotated, according to the Exif orientation tag

### Device info

**Device:** Sony Xperia X Compact
**Android version:** 7.1.1
**Signal version:** 4.10.12

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
