### ISSUE TITLE
4.10.12 occasionally failing to send SMS, MMS

### ISSUE THREAD

**Issue by mrgtreeskier** [signalapp/Signal-Android#7011]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal has occasionally sent a message failed error immediately after trying to send an SMS or MMS. Signal then will not try to resend after pressing the message for more information and you have to copy, paste, and resend the message again. This happens about 5-10% of the time.

Investigated if it was a cellular issue, but Android Messenger had no problems. 

### Steps to reproduce
- Open up a thread (group or individual)
- Write something, press send

**Actual result:** 
Signal alerts user of a failure to send. Resend buttons do not work.

**Expected result:** 
Messages transmit.

### Device info
**Device:** Google Pixel XL
**Android version:** 8.0.0
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/d3e65812db9e3d15ae487821c79c436b

**Comment by moxie0** [comment]
The log is for a failed MMS. This is using the system MMS API, and from the log we hand the OS the MMS and it returns an error code saying it couldn't send it. We don't really have any control over anything beyond that, unfortunately.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
