### ISSUE TITLE
4.10.12 Contact names don't show for contacts stored in phone without country code 

### ISSUE THREAD

**Issue by kb100** [signalapp/Signal-Android#7013]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since the profiles upgrade, names do not show up for some Signal users whose numbers are stored in my phone without a country code (as in 555-555-5555 instead of +1-555-555-5555). Instead their phone number shows up. Adding the +1 to their stored contact info and refreshing the contact list by tapping the new message button and dragging down fixes the issue on a per contact basis.

### Steps to reproduce
- Upgrade to 4.10.12
- Look in either message list or contact list for composing a message
- Notice that Signal users whose numbers are saved in your phone do not show their name in your phone, instead only the phone number
- Edit their contact information by adding the country code
- Refresh contact list
- Notice that their name now appears.

**Actual result:** Phone numbers are displayed instead of contact info
**Expected result:** Contact info should be displayed instead of phone number

### Device info
**Device:** Samsung Galaxy S6
**Android version:** 7.0
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/498d14bfcd7cbe9d70bc3824ac7b8a4e

**Comment by Fmstrat** [comment]
I'm not sure why, but doing this for the contact at the top of my message list made names show up for everyone on the list.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
