### ISSUE TITLE
Time span of messages uses incorrect grammar in Polish

### ISSUE THREAD

**Issue by pbacz** [signalapp/Signal-Android#7032]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Time label of messages (`DateUtils_minutes_ago`) uses incorrect grammar in Polish (and possibly in other languages that uses some strange grammar rules).

Numerals in Polish are complicated. Below is the correct grammar:
- 1 minuta
- 2 minuty
- 3 minuty
- 4 minuty
- 5 minut
- 6 minut
- 7 minut, etc...

I understand that this cannot be done simply by changing the translation file. `DateUtils` does not support 'advanced' grammar rules like this. This would be done programatically.

I could prepare a pull request to fix this critical issue, but before I start any work I would like to hear your opinion whether this change would be considered as something useful. 😄 

### Steps to reproduce
- Write a message while using Polish locale.
- Observe time span.

**Actual result:** - It will show: Teraz, 2 minuta, ... , 8 minuta.  (English: Now, 2 minutes, ... , 8 minutes)
**Expected result:** - It should show: Teraz, 2 minuty, ... , 8 minut.

### Screenshots
![scr](https://user-images.githubusercontent.com/32469996/31151702-f75ebe8e-a898-11e7-811c-855cc5d1cafd.png)

### Device info
**Device:** Motorola Moto G4
**Android version:** Stock 7.0
**Signal version:** 4.10.12

**Comment by cascheberg** [comment]
The solution is to basically revert #3320, or change the polish translation to use units. I wanted to fix this in #4815, so there is some discussion there, see the "outdated diff" comment sections.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
