### ISSUE TITLE
Message draft not shown in chat list if number not saved in address book

### ISSUE THREAD

**Issue by Lesik** [signalapp/Signal-Android#7035]
Hey,

when writing to an unknown number not saved in the address book, by clicking the pen FAB then entering the number manually, a message draft is not shown in the chat list when you click the ← button.

**Comment by wesinator** [comment]
drafts aren't shown in the chat list at all - #7179

**Comment by FeuRenard** [comment]
I agree with @wesinator, this issue is a special case of #7179.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
