### ISSUE TITLE
When tapping on myself in the conversations list, my profile image is not shown

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#7049]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

I have a "conversation" with myself that I use to quickly take notes. I wanted to tap on it to see how other see my profile image, but the profile page that opens has just my big initial there, instead of the image. If I tap on a group that has an image, I correctly see it. 

### Device info

**Device:** Nexus 5
**Android version:** 7
**Signal version:** 4.11.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
