### ISSUE TITLE
Replying to a group MMS via the notification pull sends the message as SMS instead

### ISSUE THREAD

**Issue by bikeseat** [signalapp/Signal-Android#7053]
Let's begin with a checklist: replace the empty checkboxes [ ] below with checked ones [x] accordingly -->

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When replying to a group text (mms) via the notification pulldown, the message is sent as an sms and goes only to one individual in the group.

### Steps to reproduce
- Receive group text (mms)
- Pulldown notification, tap reply, enter message, hit send.
- From the thread in the Signal app, long press on your sent message, tap "i" for message info, notice it was sent as an sms

- Should be sent as an mms and go to the whole group

**Device:** Huawei Honor 5x
**Android version:** Lineage OS 7.1.2
**Signal version:** 4.10.12

**Comment by timotree3** [comment]
I had the same issue in #6910

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
