### ISSUE TITLE
User Experience Suggestions

### ISSUE THREAD

**Issue by JustPassingByHere** [signalapp/Signal-Android#7058]
I love this app but after sharing this with friends and family I see a few things that made their transition a little difficult or just revert back to whatever messaging app they used previously.

Here's a few things I've noticed:
- The initial period of finding another contact and sending them an encrypted message isn't very obvious. There's nothing saying the app is syncing with the server to find other contacts that also have Signal so users are left confused trying to send each other an encrypted message but the box still says "Unencrypted SMS". An optional tour may be best here to walk new users through Signal.

- On first use, users are left with a big box at the top that asks them to make Signal their default messaging app. It seems to confuse everyone. I suggest that this option should come up after users have had a chance to use the app for a few days rather than prematurely asking them to switch immediately when new users are still exploring it.

- New users tend to switch back to the default messaging app since all the conversations are already on the default messaging app (i.e. the built-in SMS app) so asking the users to import their existing messages into Signal on first run would be more appropriate. I know this conflicts with the above point but these two points are up for discussion.

I will add more observations here as I continue to listen for difficulties with Signal from others.

**Comment by p0ll3** [comment]
Imo that Signal sells as an alternative SMS App is the problem. If I recommend Signal, I insist on not installing the sms integration, which most of the time still fails, because no normal user reads anything. In the End I get confused question about how to send stuff with signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
