### ISSUE TITLE
Contacts do not appear in Signal's contact list until country code is removed

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#7061]
I have:
- [X] searched open and closed issues for duplicates. This issue is the opposite of https://github.com/WhisperSystems/Signal-Android/issues/7013
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Contacts appear in Signal's contact list (Signal > Message compose) after removing the country code from the number that is saved.  When looking at the contact entry in the phone's contact list, only a Google account is shown. Resync-ing contacts (Android Settings > Accounts > Removing Signal > Open Signal > Message compose) causes no change.

### Steps to reproduce
- Have contact's phone number stored WITH the country code
- Open Signal
- Tap Message compose
- Scroll or search for a contact

**Actual result:** Contact is not listed
**Expected result:** Contact is listed

### Screenshots
 N/A

### Device info

**Device:** Samsung Galaxy J7
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log

Contact saved WITHOUT the country code and is listed in Signal's contact list: https://gist.github.com/c2bb17fa187b17804ad40213244a3165
Contact saved WITH the country code and is NOT listed in Signal's contact list: https://gist.github.com/d43a61309c362c41796c9e2518368e3d

**Comment by johanw666** [comment]
I just checked that with 4.11.2 and I could not reproduce it. I store all contacts with country code, the ones on Signal have all +31 (The Netherlkands).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
