### ISSUE TITLE
Crash recording audio message if microphone permission is disabled

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7062]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Trying to record an audio message causes crash if microphone permission is denied.

### Steps to reproduce
- Deny Signal microphone permission
- Hit the mic button on composing a message

**Actual result:** Vibration and toast notification, then app crashes
"Unfortunately, Signal has stopped."
**Expected result:** Dialog asking user to enable microphone permission, cancel should show a message that user needs to enable mic permission to record a message.

This may also be an issue with the camera but I haven't tested that.

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.10.12

**Comment by nrizzio** [comment]
Please submit a debug log and paste the link in a comment right after Signal crashes. You can find it in advanced settings.

**Comment by wesdawg** [comment]
https://gist.github.com/a0564a0da7dff59ce21ba1c151fef5e9

**Comment by wesinator** [comment]
No longer an issue since selective permissions
