### ISSUE TITLE
Add photos in signal database to attachment drawer photo rail

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7063]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request

Looks like the attachment drawer only shows photos saved unencrypted on disk.

It'd be nice if the attachment drawer photo rail also showed photos saved in the Signal database.

**Comment by FaizKhan5** [comment]
Not a good feature :(

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
