### ISSUE TITLE
Sporadic layout issues in recipient preferences

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#7067]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The layout of the Recipient Preferences > Privacy block looks messed up some of the time (see vertical string placement & separator lines). It seems like when opening that view the first time after opeing Signal, it's displayed correctly. The issue only arises after that.

### Steps to reproduce
- Open Signal
- Go to recipient preferences of new (empty) Signal conversation (probably looks normal)
- Tap the phone's "Back" button once
- Go to recipient preferences again (issue most likely there)

### Screenshots (English & German)

![wg1cmv6s](https://user-images.githubusercontent.com/12624674/31311628-892b71f8-abb0-11e7-88e1-474faa40d055.gif)

### Device info

**Device:** Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.11.2

**Device:** Nexus 4
**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.11.2

**Comment by FeuRenard** [comment]
I can not reproduce on Android 6.0.1

**Comment by RiseT** [comment]
@FeuRenard Black theme only (just noticed)

**Comment by RiseT** [comment]
Wait. I've just managed to get this with the light theme. But it doesn't "work" eacht time...

**Comment by RiseT** [comment]
So far it looks to me like it's fine the very first time after opening Signal, after that the issue arises in almost all cases. If I then close Signal and re-open it, it again works for one time.

**Comment by RiseT** [comment]
Able to reproduce on a Nexus 4 with Android 7.1.2 (LineageOS).

**Comment by Dyras** [comment]
![screenshot_20171007-233809](https://user-images.githubusercontent.com/12563436/31312016-56e751fe-abb9-11e7-87b6-a2e28b599f0d.png)
![screenshot_20171007-233633](https://user-images.githubusercontent.com/12563436/31312017-5952649c-abb9-11e7-8846-9ae68e5ec6f6.png)
The message under "View safety number" isn't even showing for me.

**Comment by RiseT** [comment]
> The message under "View safety number" isn't even showing for me.

That message is only displayed for new conversations, i. e. no message has been sent or received.

**Comment by Dyras** [comment]
@RiseT Is the layout weird even in an old Signal conversation?

**Comment by RiseT** [comment]
@Dyras No. Everything looking as expected in that case. I guess it's that descriptionary text (when the identity key isn't exchanged yet) that messes it up.

**Comment by moxie0** [comment]
Looks like this is another CoordinatorLayout bug. The quality of Android is getting worse and worse, only thing I can do is hope they fix it in a future release.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
