### ISSUE TITLE
Crash when opening MP3 file

### ISSUE THREAD

**Issue by Sjlver** [signalapp/Signal-Android#7070]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I've sent an MP3 file via Signal Desktop. It plays there alright. When playing the same file in Signal Android, the app crashes. There's also a toast saying "Error playing audio!" or similar.

### Steps to reproduce
- Open Signal Desktop
- Send some MP3 file to somebody
- Open the same conversation in Signal Android
- Click the round play button for the MP3 file

**Actual result:** Unfortunately, Signal has stopped. Plus a toast message.
**Expected result:** Well, it should... play the audio file.

### Link to debug log
https://gist.github.com/anonymous/41a5ec32e3c002f230099cd0079ad949

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
