### ISSUE TITLE
Can't send message to verified contact after she reregistered

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#7071]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If a verified contact reinstalls signal, messages can't be sent any longer.

### Steps to reproduce
- your friend registers with Signal
- you verify the safety number
- your friend reinstalls Signal
- you try to send a message, it fails because of the changed safety number
- you click on the failed message
- you see a warning that the safety number changed and press the button next to it
- you're asked if you want to accept the new safety number, you do
- try to resent the message or send a different message, either one fails

Only once I received a message, I could send messages again.

**Actual result:** It is not possible to send messages after accepting the new safety number.
**Expected result:** After accepting the new safety numbers, you should be able to send messages again.

### Device info

**Device:** Blackphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.2

### Link to debug log
[log](https://gist.github.com/anonymous/db3ea6a5df4fbe63bfda04033e19f90c)

**Comment by moxie0** [comment]
The log you've included doesn't seem to cover the period of time that corresponds to the steps in your issue.

My guess is that if you did all of this from start to finish in short succession, the failures are a result of exceeding the key rate limits. You wouldn't trip over those in a more realistic scenario, but we should still improve the UX in that case.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
