### ISSUE TITLE
2 sim cards...

### ISSUE THREAD

**Issue by TurkeyMan** [signalapp/Signal-Android#7080]
I have 2 SIM cards, which means I have 2 phone numbers. I live between Australia and the US... and my contacts each use my respective national phone number.

So, what do I do? I feel like I should have 2 signal accounts; one for each number, and I should be able to 'sign in' with both of my numbers at the same time.
If a contract recognises both of my signal accounts, long-press on the send button should allow me to choose which one to send messages with, the same as selecting which sim to send normal sms when there are 2 SIM cards.

Right now, signal is still only using my Australian number, even though I live in the us, and my us contacts can't easily use signal with me.

**Comment by scienmind** [comment]
Yes, currently Signal supports a single account per device, so you can only register one of the numbers.
Once registered, you can use another SIM card and you will continue receiving signal messages sent to the registered number (until you unregister, or re-register with original SIM on another device).
It is often handy when traveling and using local SIM cards for data connectivity.

I do think however, that it is a valid request - to be able to register both SIM cards, effectively having 2 signal accounts on the same device. Your use case is the exact example on why it is useful.

**Comment by Invictaz** [comment]
You might need to clone the app first as otherwise I wouldn't know how to have two instances of Signal running on the same phone. Or you would need to use the secret folder on Samsung's which allow another copy of an app.

**Comment by cegg1** [comment]
@scienmind @Invictaz It's possible to have more than one instance of Signal on the same device registered under different phone numbers. Android allows you to set up two or more different users on a given device. Therefore, each "user" can have it's own separate Signal account, all on the same phone. Now, because the SIM card(s) is (are) the same to all users, you'd still receive regular phone calls regardless of what user (and therefore Signal account) is active at any given time.

**Comment by TurkeyMan** [comment]
I'm not really interested what's 'possible', I'm just saying I think this is a thing that needs to 'just work'™.
Signal could easily detect I have 2 sim cards and then offer to register both numbers for use.

**Comment by cegg1** [comment]
> So, what do I do? I feel like I should have 2 signal accounts; one for each number

Sorry, that must have been a rhetorical question then...

**Comment by TurkeyMan** [comment]
Yeah it kinda was. Sorry :)

**Comment by Invictaz** [comment]
@cegg1 only on stock Android. Have not seen this on Samsung.

**Comment by xyzzyxw** [comment]
Unfortunately using two Android accounts is quite inconvient, e.g. because notifications are only shown for the active account and you somehow have to copy your contacts.
It would be nicer if Signal would support multiple accounts. By the way, Telegram does that now.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
