### ISSUE TITLE
Avatar not accepted 

### ISSUE THREAD

**Issue by Invictaz** [signalapp/Signal-Android#7081]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal does not accept all avatar images even if within file size limit

### Steps to reproduce
- Select 23.53 kb image as avatar
- resize the raster (also happens if you don't resize it)
- press done
- nothing happens, it works with other images fine

### Screenshots

![screenshot_20171003-223006](https://user-images.githubusercontent.com/20338545/31418824-8ac35582-ae38-11e7-98f4-51526ec255ca.png)

### Device info

**Device:** Samsung A320FL
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log

https://gist.github.com/anonymous/2956101d1385169b6a18a3ac61960d3d

**Comment by Invictaz** [comment]
Suggested image is here:

![22228634_1602116859847136_5922994304018764487_n](https://user-images.githubusercontent.com/20338545/31418859-b5edd746-ae38-11e7-89cf-d78d4aa13a7d.jpg)

**Comment by Invictaz** [comment]
Seems that the JPEG decoder has an error

10-11 03:54:51.101 27685 27685 E android-crop: Error cropping image: Image failed to decode using JPEG decoder
10-11 03:54:51.101 27685 27685 E android-crop: java.io.IOException: Image failed to decode using JPEG decoder

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
