### ISSUE TITLE
Contact name / group title isn’t bold for unread messages anymore

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#7084]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The contact name / group title is not bolded anymore on unread messages. Still happens for the message text in the second line and for the timestamp so I assume it’s a bug.

### Steps to reproduce
- get a new message
- look at the conversation list

**Actual result:** Contact name / group title isn’t bold
**Expected result:** Contact name / group title should be bold for unread messages, just like with the second line and timestamp.

### Screenshots
![screenshot_20171011-234754](https://user-images.githubusercontent.com/925062/31468897-0e1a2f8a-aee0-11e7-82c3-4c906f622575.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/e7cfc91a3f551cbc94ba86c8d368d74e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
