### ISSUE TITLE
Timestamp is not properly vertically aligned

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#7085]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The timestamp baseline in the conversation list is a bit higher than the baseline of the contact name / group name. This looks a bit dirty typographically / alignment-wise.

### Steps to reproduce
- have some conversations in the list and look at the timestamp
- especially noticeable for long group names where they almost touch the timestamp text

**Actual result:** Timestamp line is a bit higher than the baseline of the contact name / group name.
**Expected result:** Timestamp line is properly aligned on the same line as the contact name / group name.

### Screenshots
![screenshot_20171011-234754](https://user-images.githubusercontent.com/925062/31468897-0e1a2f8a-aee0-11e7-82c3-4c906f622575.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/e7cfc91a3f551cbc94ba86c8d368d74e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
