### ISSUE TITLE
Text has varying alignment, looks strange design-wise

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#7086]
I have:
- [x] searched open and closed issues for duplicates. Adhere to Material Design grid specs #6114 Is similar but different in that it just speaks about aligning of elements to grid, not about changing the text alignment.
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Text in the header and content is differently aligned, making the app feel a bit jumbled at times. A proposal would be to align them to a common line on the left.

### Steps to reproduce
- open the app, look at the list view and the conversation view

**Actual result:** Lots of different text alignment lines.
**Expected result:** Text is properly aligned on the left at a common line.

### Screenshots
Current, for list view and conversation view:
![signal alignment current](https://user-images.githubusercontent.com/925062/31470073-a074d4d0-aee4-11e7-880a-f5e24a2cc89e.png)

Proposal: please note that I’m not 100% happy with this, especially with the movement of the »Signal message« part and the resulting whitespace around the emoji icon.
- move »Signal« title to right to align with content (maybe icon too. Also, the icon could be white?)
- move »Search« text a bit to right to align with content (maybe also the back arrow)
- move conversation title in heading slightly to the left to align with content
- _maybe_ move the »Signal message« input box placeholder. This looks strange though.
![signal alignment fixed](https://user-images.githubusercontent.com/925062/31470072-a0362bae-aee4-11e7-98b6-4981739506e3.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/e7cfc91a3f551cbc94ba86c8d368d74e

**Comment by p4nci** [comment]
@jancborchardt if you are in beta channel, could you check if Signal v4.13.0 fixes this?
see also commits: https://github.com/WhisperSystems/Signal-Android/commit/bb878f8a67895b0c83869dfe2d68ea3c6ea5baed, https://github.com/WhisperSystems/Signal-Android/commit/405ee3b741d0ff06473fc9a6f9a56b2809145c91, https://github.com/WhisperSystems/Signal-Android/commit/534dec282f8f9326f5ccae378ec04940129d310c (3rd point)

**Comment by jancborchardt** [comment]
@p4nci cool! I’m not in the beta channel, when would this version land in the normal release? :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
