### ISSUE TITLE
No voice recording in document area

### ISSUE THREAD

**Issue by FaizKhan5** [signalapp/Signal-Android#7088]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Bug description
Voice message record within signal app not found in document area in shared items. 

Steps to reproduce 
Record voice message within signal app 
Send a voice message 
Then i check it in shared items document area no voice message found. 

Actual result: no voice message in document area in signal
Expected result: voice message show in document area

Screenshots

Device info
Device: Qmobile Noir i6 Metal One
Android version: 6.0
Signal version: 4.11.3

 Link to debug log

**Comment by FeuRenard** [comment]
I think this is intended.
Related #7029

**Comment by FaizKhan5** [comment]
How this is intended i think voice note shows in document area

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
