### ISSUE TITLE
Replying from the heads up notification in a phone with two active SIMs labels the encrypted message with the SIM card's name

### ISSUE THREAD

**Issue by athanasio** [signalapp/Signal-Android#7093]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Replying from the heads up notification when two SIMs are active in a dual-sim phone, the message is labelled as sent like an SMS, with the name of the SIM card on the message bubble. The message is however properly sent via the encrypted channel.

### Steps to reproduce
- open a heads up notification from Signal
- reply in the provided text box and send the message
- open conversation in the Signal app and check the message you've just sent, 

**Actual result:** Although it is an encrypted message, it is labelled as sent via a SIM card, but not with an unlocked padlock.
**Expected result:** Not having the SIM card name as a label

### Screenshots

[screenshot](https://user-images.githubusercontent.com/12595662/31552676-d7bca29e-b040-11e7-8c3d-fa402b4d0469.png)

### Device info

**Device:** Honor 8
**Android version:** 7.0 (C432B394)
**Signal version:** 4.11.3

### Link to debug log

Can be provided upon request.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
