### ISSUE TITLE
Missing option to notify of unread status of thread not on each incoming message

### ISSUE THREAD

**Issue by GeneKar** [signalapp/Signal-Android#7095]
Reproduction Steps:
1) Alice and Bob have an ongoing conversation/thread
2) Bob sends message to Alice
3) Alices phone vibrates and notifies her of new unread message
4) Bob sends another message

Expected:
Phone does not vibrate or ding for each incremental message unless the whole thread is marked as 
'read'

Observed:
MD vibrates for each incoming message

Note: In my observation, this issue is causing people to mute group threads and therefore to engage less with Signal

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
