### ISSUE TITLE
Cannot export media anymore

### ISSUE THREAD

**Issue by fdw** [signalapp/Signal-Android#7097]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since  the latest update, I cannot export all media of a converstaion anymore. In earlier versions, this was possible, but now I would have to save each and every photo and video by hand.
Since the plaintext export also does not contain media (#1619), I cannot comfortably back them up.

### Steps to reproduce
- Open a conversation in signal
- in the dot menu, choose "all media"

**Actual result:** There is no button "Save all"
**Expected result:** There should be a button "Save all" that saves all photos, videos etc to disk.

### Device info
**Android version:** 7.1.2
**Signal version:** 4.11.3

**Comment by finnoleary** [comment]
I have the same problem. Version 4.11.5.

**Comment by d4l3k** [comment]
This is a serious issue for me. I've got tons of photos in signal and for security reasons I need to reinstall the OS. Not being able to export puts me in the awkward position of either deleting all the photos or going without security updates.

**Comment by jeremymasters** [comment]
@d4l3k Can you just save the files? Too many to do so?

**Comment by d4l3k** [comment]
@jeremymasters There's hundreds of files.

**Comment by fdw** [comment]
@jeremymasters I too would also rather have to click two buttons to save all media instead of saving hundreds of pictures and videos manually. (Ideally, it would be part of the unencrypted export.)

**Comment by wngr** [comment]
What was the rationale behind removing this feature? Imho there should be a way to reliably backup all media and messages from Signal.

**Comment by VTCop** [comment]
OMG! Please return the "Save All" button in next update. Saving one by one is a nightmare

**Comment by breznak** [comment]
@fdw do you recall a justification/discussion for removing the feature? Is there a PR which we can try to revert to bring it back?

**Comment by fdw** [comment]
@breznak No, sorry, I just noticed that it was gone.

**Comment by FeuRenard** [comment]
Just for reference: https://github.com/WhisperSystems/Signal-Android/commit/8ce914a344ee6edced169d74fe5bae1b81ed7b4a#diff-978497c8da0623480ac14da5b105d5fbL124
This is the commit which removes the code for this functionality.

**Comment by char32** [comment]
@moxie0 is this planned to come back in future?

**Comment by sebastianschauenburg** [comment]
It is not possible to "default" save media to the device (global, per group or per contact), so it can be accessed by the normal file browser. The 'Save all' was the only quick/efficient way to get all media exported from a conversation. Chat (text) can be exported via the global export feature. Please re-enable "Save all" since saving (exporting) every piece media one by one is suboptimal.

**Comment by breznak** [comment]
...can somebody please make (any working) fork, PR with this feature available? I'll soon be switching phones, and this is a showstopper :/

**Comment by jaimet** [comment]
FWIW, downgrading (via "adb install -r -d oldVersion.apk") as a workaround does *not* help: v4.11.0 has the problem, whereas v4.10.12 fails to run due to a "database downgrade" that fails:

AndroidRuntime: android.database.sqlite.SQLiteException: Can't downgrade database from version 45 to 43

Happy happy joy joy...

**Comment by Oisins** [comment]
Still not back. This was a very useful feature! Without it there is no way to backup my media

**Comment by dschrempf** [comment]
I have to agree, I am trying to migrate pictures and was astonished to see that it is not possible anymore to export all media from one conversation. For months now I am expecting a move forward (export all media from all conversations) but instead we seem to move backwards here? Sorry for being so harsh, otherwise I am a big, big fan!

**Comment by crbble** [comment]
Same same for 4.12.3.

**Comment by breznak** [comment]
actually, given this lock-in situation, I'm considering moving to Matrix app, once I resolve the migration issue somehow.

**Comment by janvlug** [comment]
@crbble @breznak @Oisins @dschrempf I fully understand your wish to express that you really miss this feature. But I think it is more constructive to express your wishes and opinions at the community forum. For example at this topic: [What is your most-missed-feature-ranking](https://whispersystems.discoursehosting.net/t/whats-your-most-missed-feature-ranking/1286). But please, [do not bump issues](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues).

**Comment by janvlug** [comment]
Should this issue really be closed? I still would like to be able to export media to _regular files in a directory_, as was previously possible. See my [use case on the discussion boards](https://community.signalusers.org/t/whats-your-most-missed-feature-ranking/1286/83?u=janvlug).

**Comment by finnoleary** [comment]
FYI: To get the encryped backup to work I had to clobber my chat history down to 4000 messages. Before doing this I saved 10,182 images by hand, I was glad to have done so. This functionality should exist alongside the encryped backup functionality in my honest opinion.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
