### ISSUE TITLE
Media overview "today" actually means "last 24 hours"

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7099]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A photo I received yesterday, but within last 24 hours is labeled with "today" in media overview.

### Steps to reproduce
- Receive/send photo
- wait until next day but less than 24 hours
- open according media overview

**Actual result:** Photo is labeled with "today".
**Expected result:** Photo is labeled "yesterday" or "last 24 hours".

**Comment by RiseT** [comment]
Question is what is preferable - an adjustment of the label or of the calculation...?

**Comment by scienmind** [comment]
I think setting the calculation to mark stuff happened "after 0:00 AM phone local time" as "today" and in 24h before 0:00 AM as "yesterday" would be the most intuitive from users' perspective.

(media overview labeling and "sticky dates" in conversation view should be consistent as well)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
