### ISSUE TITLE
Viewed/Read Received SMS Remains Bold Unread

### ISSUE THREAD

**Issue by TimesEnemy** [signalapp/Signal-Android#7104]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I received a message from someone else.  I first saw the notification. I touched the notification, and the Signal application was called/opened.  Signal opened to the specific message, and I read the message.  I touched the onscreen back button, and noticed the message I had just read was still bold, implying it was unread.  I touched the message again, and confirmed that I was in the complete message thread, then went back out of the thread, and the message remained marked as unread.  I danced with this for a brief moment, then the message eventually was marked as read after the 3rd or 4th time viewing the message.

### Steps to reproduce
- This has happened to me only one time.  I do not know how to reproduce it.

**Actual result:** My description covers this fairly well.
**Expected result:** I expect the message to be marked read automatically, once that message has been viewed.  By "viewed," I mean the primary screen is displaying the specific messages entire message thread, at the screen where I would respond to the message.

### Screenshots
No screenshot(s) to share at this time.

### Device info
**Device:** Google Pixel XL (1st gen ... not 2017 model)
**Android version:** 8.0.0
**Signal version:** 4.11.4

### Link to debug log
https://gist.github.com/anonymous/609405771a79f2d85be9e61413260d59

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
