### ISSUE TITLE
Can't send Signal messages in UAE. Receives them (very) late

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7107]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A contact of mine who registered with Signal while in the US, cannot send Signal messages while in the UAE. Presumable domain fronting seems to work based on the registered number...

Dupe of #6037 and #5986 but they were closed without discussion. To the user, this looks like a bug.

**Expected Result** 
1. Automatically detect if Signal is being censored and use domain fronting if option is available.
2. Throw an error, warning the user about censorship; if domain fronting is not possible/configured.

**Comment by johanw666** [comment]
> Presumable domain fronting seems to work based on the registered number...

It does, this is one of the things that should get better designed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
