### ISSUE TITLE
[Feature Request] Please add option to hide mobile number from conversation and call screens

### ISSUE THREAD

**Issue by las2mile** [signalapp/Signal-Android#7110]
I want to use signal in public without worrying of other eyes on my screen. Please allow to hide mobile number from conversation and call screens and also if possible add a camouflage background for the conversation screen.

**Comment by RiseT** [comment]
This has already been refused: https://github.com/WhisperSystems/Signal-Android/issues/5277

**Comment by ArmeF97** [comment]
Can someone please tell us why it's been refused?

**Comment by nrizzio** [comment]
@ArmeF97 please read the contributing guidelines and ask further questions on the community forum at https://whispersystems.discoursehosting.net

**Comment by ArmeF97** [comment]
@nrizzio  i read it, found a topic about it, but there was no logic explaination why this feature is being rejected

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
