### ISSUE TITLE
Read receipt icon change is hard to see

### ISSUE THREAD

**Issue by JamesHarrison** [signalapp/Signal-Android#7112]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On the dark theme, read receipt icon changes are too low contrast to be easily seen. In the light theme, the difference between the two ticks delivered and blue ticks read states are very hard to see, and likely problematic for colourblind users. 

A fundamentally changed icon replacing or appearing next to the delivery ticks with same colour as the ticks would be clearer, and eliminate issues for colourblind individuals.

### Device info

**Device:** Seen on both Samsung A5 and S7E by users with mostly functional eyesight and Mk. 1 eyeballs.

**Comment by PiCob** [comment]
I agree. There's a topic on the discussion platform as well: https://whispersystems.discoursehosting.net/t/am-i-the-only-one-who-thinks-that-the-message-status-checkmarks-are-hard-to-distinguish/1314

**Comment by landry314** [comment]
How about using red instead of blue in the dark theme? Red goes well with dark colors!

**Comment by jeremymasters** [comment]
@landry314 Red will make people think there is some sort of error, typically.

I think if the blue matched the blue of the encrypted send message icon, it'd be perfect.

**Comment by kourbou** [comment]
Or gray when for the original sent ticks, and white for the read.

**Comment by JamesHarrison** [comment]
Personally, I'd suggest green ticks or a fundamentally different icon. Blue is already "taken" as an action colour (encrypted vs non-encrypted button difference, though this is also backed up with an icon change) and green is nice and unambiguous.

**Comment by paride** [comment]
If a change has to be made to the read receipt icon, I think it should solve another issue: when the two black ticks are shown it is not possible to know if the message is unread, or if the other user has disabled the read receipts. I propose the following:

- When delivery receipts are disabled, everything behaves as before RR were implemented;
- If a message has been delivered, not read, and RR are enabled, then what is shown are two black ticks and the outline of a third tick (or a light gray third tick);
- Message read, RR enabled: three ticks are shown (optionally colored).

**Comment by mvc1095** [comment]
Colourblind user here. Displaying the read receipt only via a colour change is problematic as an accessibility issue. I would suggest showing a third checkmark, or some other icon.

**Comment by Rolf558** [comment]
I can hardly see the blue color. Maybe it is caused by my Red–green color blindness. That is why I am voting for a darker blue (or different color) or better a third checkmark.

**Comment by simhnna** [comment]
@moxie0 I am not colorblind and also find it hard to distinguish. You closed the pull request, because you'd rather stick to blue. Do you have any comments on the discussion here? If you say what you'd approve, I can try doing it.

**Comment by RiseT** [comment]
As already [stated](https://whispersystems.discoursehosting.net/t/am-i-the-only-one-who-thinks-that-the-message-status-checkmarks-are-hard-to-distinguish/1314) on the community platform, I'm very much in favor of forgetting about colors but using completely different icons for each state instead. As an example I've pointed to the way [Threema](https://threema.ch/en/faq/status_expl) handles this.

Completely different icons fix every problem stated here. Bad sight, bad light conditions, smallish phone displays, colorblindness, etc.

**Comment by Carm01** [comment]
I would agree that a different icon should be used. 
The check marks a too 'fine', need to be thicker in nature and also even though I can tell they are blue they are not very visible other that being like the background in dark theme. 

A further comment got my attention 

"I'd like to stick with blue for now, but thanks" was quoted [here](https://github.com/WhisperSystems/Signal-Android/pull/7137). There is no business reason given for this decision leaving this with people having issues clearly. A simple sent, received, and read should be simple enough. A personal opinion from a person without a full business explanation for the reasoning it is being left that way not taking into account disabilities such as being color blind or difficult to see" is really not professional.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
