### ISSUE TITLE
[Feature Request] Dedupe messages

### ISSUE THREAD

**Issue by am385** [signalapp/Signal-Android#7114]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While known and advised before import, offer and option to dedupe the afterwards. Or event when occasionally a text is sent multiple times with network issues. It would appear that once everything is imported, inside of the signal database, and decryption is not in the way, the messages could be simply hashed on Time Stamp, To, From, and Message to dedupe them.

### Steps to reproduce
- Import sms from database or text

**Actual result:** The messages are duplicated
**Expected result:** After import prompt for a dedupe

### Device info
**Device:** Samsung Galaxy S6
**Android version:** 7.0
**Signal version:** 4.11.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
