### ISSUE TITLE
Per thread notification sound can not be set to None / "None" is not remembered

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#7115]
I have:
- [X] searched open and closed issues (not PR's) for duplicates and could be mistaken. 
 https://github.com/WhisperSystems/Signal-Android/issues/4109 looks to be for global settings (Signal > Settings > Notifications > Sound), not per conversation (Conversation Settings > Notification sound). Also related to https://github.com/WhisperSystems/Signal-Android/issues/5090? 
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Per thread notification sound settings of None (i.e. Silent) does not stay but changes to the default tone

### Steps to reproduce
- Open a conversation thread
- Navigate to conversation settings
- Select Notification Sound
- Select None > OK

**Actual result:** Notification Sound is "Default"
**Expected result:** Notification Sound is "None"

### Screenshots
N/A

### Device info 1

**Device:** Samsung Galaxy S4
**Android version:** 5.0.1
**Signal version:** 4.11.5
**Debug Log:** https://gist.github.com/459782169aa56b714eaecbb2c80a077c

### Device info 2

**Device:** Motorola Droid turbo 2
**Android version:** 7.0
**Signal version:** 4.11.5
**Debug Log:** https://gist.github.com/anonymous/99df8e03c4ea9152a69670d370695551

### Device info 3
**Device:** ZTE five 2
**Android version:** 6.0.1
**Signal version:** 4.11.5
**Debug Log:** https://gist.github.com/876716e264392869fb43a829e0573715

**Comment by schmeat** [comment]
I am getting this too!!


**Device:** Samsung Galaxy S8+
**Android version:** 7.0.0
**Signal version:** 4.11.5
**Debug Log:** https://gist.github.com/23ff7ff5c335cb4d4370b6d6fb806162

**Comment by schmeat** [comment]
Any word on this being merged? I've been forced to mute conversations because if it.

**Comment by schmeat** [comment]
Hi @moxie0 , any chance of having a look at this? There is currently a pull request for it: #7140  . This bug is really killing my usability because I'm forced to mute certain contacts and groups, which means if I forget to check the app I miss messages.

Cheers

**Comment by p4nci** [comment]
@schmeat if you really want to help, you should at least post the right link to mentioned PR (#7141) and not to another issue.

**Comment by schmeat** [comment]
@p4nci please forgive me for making a mistake

**Comment by riyapenn** [comment]
Reappearing for a couple of users on 4.14.7

**Device:** LGE Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.14.7
**Debug Log:** https://gist.github.com/b1cb70ee1e3efb96cf2eed5af4ad0b30

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
