### ISSUE TITLE
Deleting Message doesn't delete Notification

### ISSUE THREAD

**Issue by QantumEntangled** [signalapp/Signal-Android#7117]
### Bug description
When receiving a message while the Signal app is open a notification is still generated (which is awesome) but when I switch to that conversation and delete the message that currently has an open notification, the notification remains active after the message has been deleted.

### Steps to reproduce
- Have Signal App open
- Receive Message (I only tested with Signal users)
- Open the conversation
- Delete the message that is currently in the notification

**Actual result:** Notification persists after message is deleted.
**Expected result:** Deleting a message also removes any active notification(s) corresponding to the message.

### Device info
**Device:** Google Pixel XL
**Android version:** 8.0.0
**Signal version:** 4.11.5

**Comment by QantumEntangled** [comment]
I believe this issue could be resolved by checking for active notifications when deleting, OR by closing the notification when the conversation is opened (regardless of whether it's reached via the notification or the Signal app itself).

**Comment by moxie0** [comment]
@QantumEntangled The latter should be true. Can you include a debug log?

**Comment by QantumEntangled** [comment]
Here's my current [debug log](https://gist.github.com/anonymous/1f2e235f6efa1486162945806ccb0cb6). Although I was unable to reproduce the problem today. Not sure if I was doing something special when it happened or something.

**Comment by micressor** [comment]
I confirm this on Signal 4.15.5. It happens only for Signal messages. SMS are not affected. MMS not tested.

**Comment by micressor** [comment]
It happens only for Signal messages. SMS are not affected. MMS not tested.

### Device Info
* Fairphone 2 (FP2)
* Android 7.2.1 (LineageOS 14.1)
* Signal 4.15.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
