### ISSUE TITLE
Selfie Camera is Backwards

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#7122]
Signal 4.11.5 on Android 7.1

When I select the camera icon in a Signal conversation and switch it to the front camera the resulting pictures are backwards as if looking into a mirror. Images should be as they appear in the real world.

**Comment by grandchild** [comment]
Every app I know does it the "mirror" way. My camera app does, whatsapp does, and I assume every other app does too. Signal shouldn't do something different in this particular aspect.

**Comment by jbaker6953** [comment]
I've been using phone cameras since the 1990's and I've only seen one phone that leaves the image backwards - the iPhone. Every other sane phone takes a picture the way a camera would. Leaving it as a mirror image serves no purpose other than aesthetics for iPhone users, and it frustrates people that need pictures with things like text.

**Comment by grandchild** [comment]
Hm on second thought I guess it's just as well to do it the other way around. And I have to concede that my camera app actually also does turn it around eventually, when saving. No preference here.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
