### ISSUE TITLE
Minor Audio issue: Caller does not hear "ringing" but hears sonar ping & after the call is answered, hears the other party.

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#7123]
I have:
- [X] searched open and closed issues for duplicates but it sounds familiar and this may be dupe or a symptom listed in a comment of another issue.
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
"Ringing" doesn't appear to the Caller

### Steps to reproduce
1. Alice calls Bob
2. Alice hears the Sonar Ping
3. Alice sees "ringing" on her call screen but does not HEAR the ringing.
4. Bob Answers
5. Alice and Bob can hear each other without issue

**Actual result:** Alice does not hear ringing in step 3 listed above
**Expected result:** Alice to hear ringing in step 3 listed above

### Screenshots
 N/A

### Device info

**Device:** Google Pixel 2
**Android version:** 8.0.0
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/4f094d1e4aa6ba690b248f0b86bbf51d

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
