### ISSUE TITLE
[Feature Request] Allow third-party apps to "poll" for messages

### ISSUE THREAD

**Issue by jwir3** [signalapp/Signal-Android#7124]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
This might be related to #3944, but I'm not sure.  Basically, it doesn't appear that there's any way I can specify an application is "trusted" to receive decrypted text messages from Signal. This is probably against the general principle of end-to-end encryption, but it might be worth it so I can use Signal in conjunction with other apps.

Basically, what I'm requesting is a way to indicate to Signal that other apps on the phone (e.g. Google Assistant, Garrulo (an app I wrote - https://play.google.com/store/apps/details?id=com.glasstowerstudios.garrulo&hl=en), etc... can "read" text messages (in clear text) from Signal. This is useful, because, when I'm driving, right now, when I ask Google Assistant to read my new SMS messages, it can't see anything inside of Signal. 

### Steps to reproduce
- Start Signal on Android, make it the default application for SMS receipt
- On another device, send an SMS message (or a Signal message) to the phone in question
- Using a hands-free device (or just by talking to your phone), say "Ok Google. Read text message" when the new message is received.

**Actual result:** Google will not read clear-text (SMS) messages or encrypted (Signal) messages received within Signal. The last message it will read is the one that verifies my participation in Signal.

**Expected result:** Google assistant will read my newest text message.

I expect that, in order for this to work, I would have to whitelist the application somehow. In that sense, what I'm asking for as a feature here is for Google to be able to "poll for new messages" to Signal, once whitelisted.

### Device info
**Device:** LG Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.11.5

**Comment by hakova** [comment]
I second this issue. I use Signal as a default handler app for SMS messages. Neither unencrypted SMS messages nor encrypted Signal messages are forwarded to my car's bluetooth when received. Quick fix will be appreciated.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
