### ISSUE TITLE
Issues with MMS after MMS was working correctly

### ISSUE THREAD

**Issue by ahoward1024** [signalapp/Signal-Android#7127]
MMS was working just fine for me for the past year or so. I decided to download a different SMS app to try something else, but went back to Signal as I have found nothing better. Now all MMS messages come up with an "error downloading... tap to retry."

I am on Project Fi and, yes, _I have set my default SMS app to Signal_.

Anyone have any clues on how to fix this?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
