### ISSUE TITLE
Option to Display Local Address Book or User Defined Profile Picture

### ISSUE THREAD

**Issue by landry314** [signalapp/Signal-Android#7132]
Currently, if I have a photo set locally in my Contacts, it overrides the profile photo set by the other user. I can't even see the personalized photo in "Conversations settings".

I would like to see it somehow and even have to option which one to display.

I currently use identiconizer and its icons are not as good as the personalized ones of other users, I'd like to see the personalized ones rather than local ones if both are present or at least be able to override it on a per user basis.

**Comment by no-username42** [comment]
Now that we are on the profile pic topic: I don´t want to use or see any pictures/avatars and would like to disable them. The old dots with a letter were fine.
Currently I constantly see the message if I want to publish my profile name and profile picture to this group. No, I really don´t want to. But there is no way to dismiss this message.
You probably can round up this issue together with landry314´s.

**Comment by landry314** [comment]
@no-username42, you are referring to issue #6927 which has been solved.

Also, you can not round issues together which are semi-related. My issue is a different issue.

I can NOT see a user defined profile picture is I have one set in my local address book. It just isn't possible. This should be, as well as the ability to choose which gets displayed in my conversation list.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
