### ISSUE TITLE
4.11.5: crash overnight

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7133]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crashed overnight
Additional info:
1. Phone was in do not disturb
2. Received message from non-signal user

### Steps to reproduce
- have signal running
- go to sleep

**Actual result:** have to enter password in the morning
**Expected result:** can just read messages, no password since already entered

### Screenshots
N/a

### Device info
**Device:** galaxy s8
**Android version:** 7.0 stock
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/a5f084232a1f6c221f7631b67cc83fdf

**Comment by jeremymasters** [comment]
Again, it out the blue I had to enter my password:
https://gist.github.com/28f0d2eec4d549950d6463b890cc7aaf
Signal is in the list of apps to ignore for power saving

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
