### ISSUE TITLE
Message text-size scaling (for emphasis)

### ISSUE THREAD

**Issue by hupsing** [signalapp/Signal-Android#7138]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------
### Feature request
What about implementing a feature for "message text scaling" for better emphasis?
I have seen this feature in Google Allo below and I think it is useful.
Long press send-button activates up/down slider for text scale.

![image](https://user-images.githubusercontent.com/33217529/32162682-187cdb2a-bd5a-11e7-965f-2afb00686b51.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
