### ISSUE TITLE
failure of immediate notification of receiving the new messages

### ISSUE THREAD

**Issue by JinsikKimSKT** [signalapp/Signal-Android#7145]
![rtt_push_server_depends_on_lte_state](https://user-images.githubusercontent.com/33244147/32209077-b8f23272-be49-11e7-89c5-89b390f3b117.png)

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Hello, Sirs.
I am Jinsik, a manager of SK Telecom, a telecommunication company in South Korea.

Rececntly I found that your "Signal Private Messenger(android)" has a bug action.

When someone send a message to other's Signal App,
the receiver's Signal App doesn't show the notification of receiving a new message.
At that time, the receiver has to start  "Signal Private Messenger" manually for receiving the new messages.

So I tested my phone with Signal Private Messenger, and found the some points of improvement
for pushing the notification from your push server.

< Testing Phone's Packet Analysis >
1. When the LTE device staying in the state of RRC_CONNECT,  
    the latency of the international network to your push server(2404:6800:4008:c06::bc) 
     is good between the handset and your phone.  ( RTT : about 100 msec )

2. But, while the LTE device' state changes from RRC_IDLE to RRC_CONNECT,
   the latency to your push server(2404:6800:4008:c06::bc, port:5228) 
    is too big between the handset and your server as the attachment.( RTT : about 400~1000 msec )
   And sometimes the TCP latency causes the TCP retransmission of push packets from your
   push server to our phones.

< Check point >
1. Please check that the TCP latency including LTE device state's change may cause
   the big network latency and TCP retransmission of push packets.
   and it may cause the failure of immediate receiving the notification of a new message arrival.

2. For improving the success rate of receiving the new message notification, 
    Please consider that your app and push-sever extend the internal TCP or SOCKET timer for
    tranporting  push packet and waiting ACK packet for the new message notifiction.
      
Best Regards,
Jinsik

### Steps to reproduce
- install Signal Private Messenger into Android phone in South Korea
- Send a new message to it.
- Sometimes, app doesn't receive the new messages immediately.
- At that time, after restarting app, it can receive the new message. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

attachment file can show the international latency for push packets.
and screenshot of app is no notificatino of receiving the new messages.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 7.0.1
**Signal version:** 4. 11. 5

### Link to debug log

 Sometimes, app doesn't receive the new messages immediately.
 At that time, after restarting app, it can receive the new message.

**Comment by moxie0** [comment]
Hey @JinsikKimSKT, interesting investigation, but it looks like your measuring against Google's GCM service. We have no control over that, it's built into Android. Have you considered getting in touch with Google about this?

**Comment by Cromefire** [comment]
Also experienced this kind of issue (I'm living in Germany). 
It only gives me notifications, if I open the app, especially after reboot. 
WhatsApp doesn't have this issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
