### ISSUE TITLE
Message bubble spacing eats lots of screen space

### ISSUE THREAD

**Issue by tdemin** [signalapp/Signal-Android#7147]
Well, the title is self-describing. The vertical spacing between the bubbles is almost 1/3 as high as the bubble.

This means every 3 messages a portion of screen space that's worth 1 message is eaten. Please reduce the vertical spacing, it's really big.

**Comment by tdemin** [comment]
Signal version 4.11.5.

**Comment by Dyras** [comment]
Can you show a picture?

**Comment by schmeat** [comment]
The spacing for group chats seems like a big waste of space too. User name being beside the time stamp would free up a lot of space.

**Comment by unitrek** [comment]
![image](https://user-images.githubusercontent.com/33198294/32343472-36d152e0-c00c-11e7-96d7-a2837a5043d5.png)

**Comment by unitrek** [comment]
![image](https://user-images.githubusercontent.com/33198294/32349131-c2a9518e-c01e-11e7-9e01-2fac1ae301c4.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
