### ISSUE TITLE
Signal crash after leaving Giphy browser

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#7153]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In a conversation I've opened the Giphy browser and typed a search term. Switched to the stickers and selected the tile view. I decided not to use the sticker so I left the Giphy browser with the back button. Shortly after the conversation view returns the message shows up: Signal is gestopt ( Dutch for Signal stopped)

### Steps to reproduce
Note that I cannot reproduce this every time and if the steps below are really needed, however at least  with this steps it happened multiple times.
- open Giphy browser
- enter search term
- switch to stickers
- select tile view
- exit Giphy browser without selecting a gif

**Actual result:** Signal stops
**Expected result:** Signal does not stop.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.12.0

### Link to debug log

https://gist.github.com/anonymous/23277e594e920d32dac978a67a3a9e2f

**Comment by FeuRenard** [comment]
I can reproduce this crash, not everytime too:

- open Giphy browser
- switch to stickers
- select tile view
- scroll down some pages and quickly...
- ... hit the back button.

**Comment by vangorra** [comment]
While I could not reproduce the problem. It looks like this is a bug in the GifFrameLoader 4.3.0. A bug has already been filed with the glide project:
https://github.com/bumptech/glide/issues/2555

**Comment by rmueller83** [comment]
I also got a crash on my SM-G900F today. Same device but other OS (Lineage 7.1.2): https://gist.github.com/anonymous/29f0042602e1eac78f43a0ce2111c9af

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
