### ISSUE TITLE
Quick camera preview icons washed out in bright backgrounds

### ISSUE THREAD

**Issue by ahtmatrix** [signalapp/Signal-Android#7156]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Quick camera icons are washed out in bright backgrounds
When using quick camera in a bright background, the switch camera, shutter, and  will not be visible because they are white with no drop shadow or black outline.

### Steps to reproduce
- press the quick camera button in the text entry box of a conversation
- point camera towards a bright background
- icons are not visible

### Potential solutions
- add a dark outline to quick camera icons

### Device info
**Device:** Nexus 6P
**Android version:** 8.0
**Signal version:** 4.10.12

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
