### ISSUE TITLE
Easy mixup of personal and group conversations: Change the styling of a group conversation

### ISSUE THREAD

**Issue by novoid** [signalapp/Signal-Android#7158]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Underlying usability issue

There is a common **usability bug** of Signal. Lets say you are getting a Signal message on your mobile. You select the notification message, switching to your Signal app, opening the conversation. You now see the last part of the conversation dialogue between you and this single person. You now answer the message of that person, writing things that are meant to be read only by that single person. Just after sending the message (or never?) you realize that you just sent this message to a group chat of many people whose conversation happens to be filled with messages of you and the other person  as long as your screen view/history is showing. 

Therefore, you **accidentally sent a personal message to a group conversation**.

You _assumed_, that you wrote your message in a private conversation because you have seen only one person's answers. Other people did not write for a longer period of time to that group conversation. You could have read the header information where you could have seen that this is not a person-to-person conversation. However, you concentrate on the bottom of the screen, where the received message could be seen and answer right below it. Therefore, it is easy to overlook the group chat header when answering a message in Signal. There is no other distinction between group and personal conversations.

The ability to change/overwrite the background color of group chats to an alarming red one for example could give the user a hint that this is not a personal conversation but a group chat. However, there is still the issue that Signal might give away "red" for an arbitrary personal conversation but this only leads to you looking more closely to the header, realizing that it is save to write personal stuff in this conversation.

_There might be other solutions to this usability issue_ (all group chats look different that any other given person-to-person conversation somehow) but my proposed feature here is a quickfix that might work for many users.

### Proposed Quickfix

I would like to be able to **set (or overwrite) the background color of a group conversation** just like it is possible for person-to-person conversations.

### Steps to reproduce
- switch to a person-to-person conversation
- hamburger menu > "Conversation settings"
- "Color" may be changed/overwritten
- switch to a group conversation
- hamburger menu > "Conversation settings"
- no "Color" option is shown

**Expected result:** I want to have the "Color" option for group conversations as well.

### Device info

**Device**: OnePlus 5
**iOS version**: Android 7.1.1
**Signal version:** 4.11.5

**Comment by NinebitX** [comment]
If I have understood this correctly, there are people who never look up at conversation headers? In that case, there must be a better way to fix the issue. Doesn't the area where you type a message currently say "Signal message" in both person-to-person and group conversations? Would it be possible to change that to say "Signal group message" in group conversations?

**Comment by novoid** [comment]
I mixed up group and personal conversations in the past and I assume that less caring people do mix up conversation types regularly.

As I mentioned, there are many possible ways to fix this issue. A distinct background color is one which seemed to be a low-hanging fruit in terms of quickfix.

Changing the "Signal message" default text would be another possibility although in my opinion, this is too subtle. I don't think that users do read this default text any more. Things like that is likely to be ignored just like banner ads are being ignored easily despite their prominent use of color or animation.

I do think that changing the send-button to something like **a send button that graphically includes multiple smaller send buttons or multiple of those paper-plane-symbols** would be a very good distinction. IMHO this would be easy to notice and easy to explain: multiple paper-plane symbols reflect multiple messages that are sent out to multiple Signal clients.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
