### ISSUE TITLE
No contacts shown

### ISSUE THREAD

**Issue by osilvab** [signalapp/Signal-Android#7160]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
There is any contact show in my list. when I try to write to a contact that I know uses Signal I only have the option to send sms. the only contact shown is myself.

### Steps to reproduce
-open signal
-try to fid any contact

**Actual result:**  non shown
**Expected result:** show contacts

### Device info

**Device:** Fairphone 2
**Android version:** 7.1.2 LineageOS 20171031
**Signal version:** 4.11.5

P.S. Using microG with GCM enabled (otherwise Signal doesnt register) and Device registration enabled.

**Comment by nrizzio** [comment]
Have you disabled the contacts permission? Please also post a link to your [debug log](https://support.signal.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-from-Signal-Android-).

**Comment by osilvab** [comment]
Contacts permision are enabled. 

[https://gist.github.com/ec1128fcaa5295d55ee68627adbb9ac3](url)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
