### ISSUE TITLE
MMS Group Message Thread Issue 

### ISSUE THREAD

**Issue by Ste4thOverride** [signalapp/Signal-Android#7161]
I have:
- [x ] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I create a group thread and add non Signal users and send a message to the group all of the replies come in as a new thread and not in the existing thread that I created. It appears that I am not added to the list of members when I look at the group members for the thread.

### Steps to reproduce
Open Signal create group thread send message when recipients reply messages show up in a new thread.

**Actual result: Not added as a Group Member to threads I created
**Expected result: All Replies should show up in the existing thread I created

### Screenshots
![screenshot1](https://user-images.githubusercontent.com/9127985/32418486-22efb8f2-c228-11e7-97ec-d4598a4d6b0e.png)

![screenshot 2](https://user-images.githubusercontent.com/9127985/32418516-d9779fa4-c228-11e7-85a4-0de7722ad3ad.png)

### Device info
**Device:Pixel XL
**Android version:8.0
**Signal version:4.11.5

### Link to debug log
https://gist.github.com/41733f2a0f309fafed5be8a4a88e3f25

**Comment by FeuRenard** [comment]
Related to #7091? In this case 4.12.x will fix this issue.

**Comment by Ste4thOverride** [comment]
Not exactly the same issue I never created a separate thread and the message order is the same. It is the same issue as @wesdawg mentioned on that thread however. 

I enrolled in the beta to receive the current version which is 4.12.2. Now half of the replies I sent have been added to the new thread that was created and all of the other messages are in one thread by themselves with no other messages.

I have deleted all of my group messaging threads which is a pain because they are not backed up by the export option. I will test and see if the issue is still on going after I recreate my group threads but it looks like it is not resolved entirely. 

I wonder if it is related to the fact that Signal is not displaying my contacts phone numbers correctly. I have all of my contacts phone numbers stored in the format of Country code + Area Code + Phone Number.  All with the hyphen between the phone number and area code but Signal displays some correctly and others without the hyphen.

**Comment by losingkeys** [comment]
I have this issue too. I've noticed this common occurrence:

1. I text some of my family (they have iPhones w/o Signal at the moment)
1. They text me back
1. It comes in a group message with them _and_ another number (mine w/the country code). Rather than saying "Me" in the list, it says "+1MYNUMBER" instead. Seems like Signal needs to recognize MYNUMBER as the same thing as +1MYNUMBER

**Comment by Ste4thOverride** [comment]
Still not resolved in 4.12.3. I created a new thread and the message replies when I got them came back in a new thread. If this was in Broadcast mode this behavior would be expected but not in conversation mode. Updated Bug Report Below. 


https://gist.github.com/8557c3714dec7b0a0fccf048f6b32baa

**Comment by ONUHWT** [comment]
I am also having this problem on my Google Pixel.  
Android 8.0.0. 
Signal 4.12.3

Let me know if I can provide any more information to help with debugging this issue.

**Comment by KatamariSanChan** [comment]
Also seeing this issue.  MMS replies come back with "Me" added to the group, so they're separated from the initial message.  I don't see a reason to see myself in the group list.

**Comment by jeremymasters** [comment]
@ONUHWT @KatamariSanChan typically the devs ask that we don't add "me too" comments to the issues unless we have new information or a log file or something like that to add.  If you want to "me too" something, you can add the reaction (thumbs up/down, smile/frown, etc).  Otherwise this emails hundreds of people.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
