### ISSUE TITLE
Own avatar not shown

### ISSUE THREAD

**Issue by paride** [signalapp/Signal-Android#7162]
### Bug description

I often write message to myself, for a number of reasons. I noticed that in the conversations I have with myself, my avatar is now shown, while it is correctly shown on my other contacts' phones.

The Electron Signal-Desktop client does show the avatar.

### Steps to reproduce
- Have a soliloquy
- Check the conversations list
- that reproduce the bug

**Actual result:** No avatar is shown, just the initial letter of the contact that has my own phone number
**Expected result:** My own avatar is shown

### Device info

**Device:** Google Nexus 6
**Android version:** stock 7.1.1
**Signal version:** 4.12.2

### Link to debug log

I think it's not relevant in this specific case.

**Comment by nrizzio** [comment]
I have the inverse problem: my Avatar is shown, but my chosen profile name is not. My phone, however, doesn't have a contact for itself.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
