### ISSUE TITLE
[Feature Request] Removing notification sound in-chat.

### ISSUE THREAD

**Issue by Julian2000nl** [signalapp/Signal-Android#7163]
A lot of chat apps replace the new message notification sound with a really basic Pop when in the chat. For users that have longer notification tones it could get annoying to hear the sound every time they receive a message, whilst having the chat open.

<b>Request:</b>
Replace the standard notification tone with a short basic Pop whilst the chat window is open.

<b>Why:</b>
It gets annoying to hear the notification jingle every time a message is received whilst the chat window is open.

**Comment by jeremymasters** [comment]
@Julian2000nl There is an option to turn off notifications while in the chat.  "Settings->Notifications->In-chat sounds" and just turn that off.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
