### ISSUE TITLE
Verified-number checkmark is sometimes not shown

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7165]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I open Signal and select a conversation with someone whose key I have verified, I see this header: with a check mark before the number:

![with_check](https://user-images.githubusercontent.com/8427572/32518782-eeef55be-c40a-11e7-9570-b1f237211837.jpg)

However, sometimes after some open-close of the conversation I see the number without the checkmark:

![without_check](https://user-images.githubusercontent.com/8427572/32518894-472845e2-c40b-11e7-80b3-7c49f64965d6.jpg)

**Device:** Sony Z3 Compact D5803
**Android version:** 6.0.1
**Signal version:** 4.12.3

### Link to debug log
https://gist.github.com/anonymous/2717351ba239a6d5312678b01bdb559b

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
