### ISSUE TITLE
[Feature Request] Copy messages with a emtpy string between them and inserting nicknames in a copy buffer

### ISSUE THREAD

**Issue by ghsrcgh** [signalapp/Signal-Android#7166]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

It is a feature request. Please make a copying few messages like a Telegram-style copy.
Or just insert empty strings between messages.

1) The first annoying thing is not adding empty string between two different messages.
For example, here is a chat:

```
John: Hello!
Could you copy that?
 
Alex: Hi!
Yep, I will try
 
John: Thank you.
Please paste here.
``` 

What will be if you will select all these message and copy/paste them somewhere?
You will see the following:

```
Hello!
Could you copy that?
Hi!
Yep, I will try
Thank you.
Please paste here.
```

Absolutely garbage of text, no any splits, you are unable to understand even by splitter - what message was written by who.

So, the first what is very wanted - is to add "enter" (empty string) after every inserted to a clipboard buffer message, except the last one. So, in this case you will have:

```
Hello!
Could you copy that?

Hi!
Yep, I will try

Thank you.
Please paste here.
```
It is not ideal, but it really much better than current behavior.

2) The best result you will get if you also will add (insert) nicknames before every new message from other guy (except a few messages from the same guy), like in Telegram.

So, you will have:
```
John:
Hello!
Could you copy that?

Alex:
Hi!
Yep, I will try

John:
Thank you.
Please paste here.
```

**Comment by vikaslraut** [comment]
How about adding timestamps like
```
John: [20 Nov]
[1.14 PM] Hello!
[1.15 PM] Could you copy that?

Alex: [20 Nov]
[1.16 PM] Hi!
[1.16 PM] Yep, I will try

John: [20 Nov]
[1.16 PM] Thank you.
[1.17 PM] Please paste here.
```
Or
```
John:
[20/11, 1.14 PM] Hello!
[20/11, 1.15 PM] Could you copy that?

Alex:
[20/11, 1.16 PM] Hi!
[20/11, 1.16 PM] Yep, I will try

John:
[20/11, 1.16 PM] Thank you.
[20/11, 1.17 PM] Please paste here.
```
Which formatting should be picked? 
I made initial changes need to pick formatting style.

**Comment by FeuRenard** [comment]
Please note that you would reveal local contact names you personally chose for recipients. Taking the identifier (mobile number) might not be better. Either way you might reveal data you did not intend to.

**Comment by vikaslraut** [comment]
Yes, this need to be addressed as personal names chosen for recipients should not be revealed.
One way to deal with this is to use **profile name** instead of contact name, but profile name is not always set by users and hence we need to use the number when there is no profile name.
What should be done then? please suggest, because in most of the cases sender's number is going to be there (if not profile name) while copying.

**Comment by ghsrcgh** [comment]
> Which formatting should be picked?

For me is better when:
```
John: [20 Nov 2017]
13:14 Hello!
13:15 Could you copy that?

Alex: [20 Nov 2017]
13:16 Hi!
13:16 Yep, I will try

John: [20 Nov 2017]
13:16 Thank you.
13:17 Please paste here.
```
(Time and date format may be get from Android's regional settings)

But maybe made like I wrote in a ticket body (like in Telegram) - where no date and no time stamps in copy/paste. Because if you copying 1-2-3 messages (just a few) - dates and time is not required usually.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
