### ISSUE TITLE
On phones with 2 SIM cards, signal ignore settings of default SIM card selected to send SMS

### ISSUE THREAD

**Issue by mirek967** [signalapp/Signal-Android#7167]
On the phone with 2 SIM cards, signal always send SMS using first SIM card. 
It ignore android settings. So even is android is set to use SIM card 2 to send SMS, signal use card no 1.
This is wrong, and there is no way to change it except exchange of SIM cards. But this can be problematic if person use SIM cards from 2 countries, and travel frequently between them.

**Comment by equaeghe** [comment]
There is no need to swap sim cards, you can deal with this from within Signal on a message-by-message basis: Long press on send button brings up a choice between sim cards (and secure Signal message).

Related: https://github.com/WhisperSystems/Signal-Android/issues/6862

If this solves your issue, you can close it.

**Comment by mirek967** [comment]
Thank you for the answer.
This solve the problem partially.
In most cases I just forget to do long press when I want to send the message. So anyway it uses the first SIM card. It would be really great when Signal would detect default settings of android, or when it would have its own option to select default SIM card for SMS sending.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
