### ISSUE TITLE
Word 'message' is prepended to outgoing messages when using Android Auto

### ISSUE THREAD

**Issue by eastsidegeek** [signalapp/Signal-Android#7168]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When you respond to a Signal message using voice prompts in Android Auto, the outgoing message has the string "Message " prepended to it.

### Steps to reproduce
- Plug in your Android device to a sync'd car with Android Auto (I am using a 2017 Chevy Bolt EV - have not tested on other vehicles)
- Receive a Signal message
- Click to have it read
- Choose to respond and send - issue will occur ~50% of the time

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- The message "Foo bar" will go out as "Message foo bar"
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- The message "Foo bar" will go out as "Foo bar"

### Device info
**Device:** Samsung Galaxy S7 (aka SAMSUNG-SM-G930A) paired with 2017 Chevy Bolt EV
**Android version:** 7.0
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/1a46db6e62f43df5dee2cbc751e95c31

### Extra thought
This may not be an issue with Signal at all, but rather with Android Auto. The last word in the voice prompt to record a message is "message". It seems reasonable that the recording may be picking up the end of the voice prompt.

**Comment by rbclark** [comment]
Have you been seeing this in other messaging platforms as well? I agree this could very well be a bug with Android Auto since on my car I use Signal with Android Auto all the time and I have only had it prepend the full "Whats the Message?" prompt once on me. One of the Signal devs can correct me if I'm wrong but I believe applications working with Android Auto don't really do much more than simply receive the message after it has been converted to text by Android Auto.

**Comment by eastsidegeek** [comment]
Have not tried other messaging apps but I can give it a shot later today.

**Comment by schmeat** [comment]
Are you saying "message" ? I have been using android auto with a GM car and have not had this issue.

**Comment by eastsidegeek** [comment]
Nope, not saying message. Just saying my message and it gets prepended.

Have not had an opportunity to switch default messengers to test outside of
Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
