### ISSUE TITLE
Black flash after exiting video player

### ISSUE THREAD

**Issue by Wasseranomalie** [signalapp/Signal-Android#7170]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After exiting the video-player a part of the view flashes black. As far as I noticed this hasn't happened in previous versions.

### Steps to reproduce
- Open video in a conversation
- Press return-button

**Actual result:** Black flash
**Expected result:** No black flash

### Screenshots

![ezgif-5-4ec779ec58](https://user-images.githubusercontent.com/6809794/32624397-7b26e298-c589-11e7-97d1-62a6877f145d.gif)

### Device info

**Device:** Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.12.3

### Link to debug log

https://gist.github.com/anonymous/f875437de2ad6f757d600bac0e87fdea
(If there is something useful in the log, it is after 11-09 20:07:12.664)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
