### ISSUE TITLE
[Feature Request] Add new contact to Signal only, not to Google contacts

### ISSUE THREAD

**Issue by Patrick010** [signalapp/Signal-Android#7172]
To improve security and privacy It'd be nice if it were possible to add a contact to Signal only. Now it is only possible to add contacts to Google contacts and have Signal sync them. This is far from private or secure! 
I prefer to add my contacts to Signal only and keep them separate from Google contacts, or have the option to make the choice to either add a contact to Signal only, or to Google contacts.
Can't imagine this to be a very hard thing to code.

Thanks
Patrick

**Comment by pgerber** [comment]
IIt's possible to store Android contact locally. At least on my phone (Android 6). Click **More Fields**, once you have done so you can pick to store the contact in the **Local phone account**. Is this what you wanted?

![screenshot_20171110-182757](https://user-images.githubusercontent.com/11895833/32673973-213aa380-c649-11e7-95f8-0c1f019249c1.png)

![screenshot_20171110-182805](https://user-images.githubusercontent.com/11895833/32674062-945bac2e-c649-11e7-957e-5e82b3123c60.png)

**Comment by Patrick010** [comment]
Doing so would still add the contact to the Android contact list, to which Google and others query this list have access. In my opinion it really should be a contact list native to Signal.

**Comment by ghsrcgh** [comment]
I think the same as @Patrick010, if we are talking about security and privacy.

**Comment by issueseverywhere** [comment]
I agree with @patrick010 on security and privacy. Also, I use Signal for international calls and messages, and mixing local and international contacts in the android app makes it messy and unproductive.

**Comment by lustigdev** [comment]
I agree with @Patrick010's recommendation.

I am correct in assuming that currently the only way to begin a conversation in Signal is to sync your entire contact book and then either invite or select a contact that's already on the platform?

Is there no concept of a public key or username?

Would be awesome if I am incorrect in this assumption or if this feature was in the works!

**Comment by moxie0** [comment]
@lustigdev @issueseverywhere  @ghsrcgh Please read the contributing guidelines before posting here again. If you agree with Patrick010's recommendation, you can use the emoji reactions to indicate your support. If you have additional questions or discussion topics, please see the community forums.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
