### ISSUE TITLE
Signal does not ring when the phone is locked

### ISSUE THREAD

**Issue by SwanKnight** [signalapp/Signal-Android#7173]
I have:
- [*] searched open and closed issues for duplicates
- [*] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After the recent update Signal no longer rings when the phone is locked. This is happening to me and several people I know. It didn't happen before the update at all. I did email the support but I got no response whatsoever.

### Steps to reproduce
- Make sure that Signal is not in the foreground.
- Lock the phone.

**Actual result:** Signal does not ring when a voice call is received and the display doesn't turn on, or turns on very briefly.

**Expected result:** Signal should ring and I should be able to answer.

### Device info

**Device:** OnePlus 3T
**Android version:** 7.1.2
**Signal version:** 4.11.5

### Link to debug log

https://gist.github.com/anonymous/41eccc4f3fabba64b7d6d22a7e8fb2de

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
