### ISSUE TITLE
[Feature Request] Swipe left to call contact

### ISSUE THREAD

**Issue by froman753** [signalapp/Signal-Android#7177]
It seems like most other texting apps allow you to swipe left or right on a conversation from your list in order to call that contact. Why hasn't Signal implemented this as well? Swiping right archives the conversation; would it be that difficult to make swiping left call that contact?

**Comment by trymeouteh** [comment]
I like this idea. If Signal Devs do not want to have a Call Menu and a Messaging Menu like in WhatsApp this is a great alternative!

**Comment by Oisins** [comment]
I don't like this idea. You can already just click the contact's icon and then press the call button.

**Comment by tdemin** [comment]
> It seems like most other texting apps allow you to swipe left or right on a conversation from your list in order to call that contact

\*opens WhatsApp\*
\*swipes left on contacts\*
\*nothing happens\*
\*same with Telegram\*

What are those "most other texting apps"?

**Comment by froman753** [comment]
Those are messaging apps. I guess it's just texting apps that do this, such as Textra and most stock text messaging apps.

I wasn't aware of the ability to click on the contact icon to pull up the contact details, but it's still not as quick as simply swiping left on a conversation.

**Comment by froman753** [comment]
Those are messaging apps. I guess it's just texting apps that do this, such as Textra and most stock text messaging apps. 
I wasn't aware of the ability to click on the contact icon to pull up the contact details, but it's still not as quick as simply swiping left on a conversation. 
 

    On Thursday, November 16, 2017, 11:25:43 AM CST, Timur Demin <notifications@github.com> wrote:  
 
 

It seems like most other texting apps allow you to swipe left or right on a conversation from your list in order to call that contact


*opens WhatsApp*
*swipes left on contacts*
*nothing happens*
*same with Telegram*

What are those "most other texting apps"?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
