### ISSUE TITLE
[Feature request] Save scroll position in current chat window for each one contact

### ISSUE THREAD

**Issue by ghsrcgh** [signalapp/Signal-Android#7178]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

Both feature requests are on the same topic, so in the one ticket:

1) Please save scroll position in current chat window for each one contact (like it doing Telegram, for example). I.e. if you had moved scroll position upper, to some date, and then "exited" from the contact to a contact list, the back - position must be saved. And do this for all contacts please (each location/position saved for each one contact).

2) Please STAY on the same position of window if some event were added by you (for example, you had sent a message to this contact). Do NOT scroll the screen immediately down to the end of chat (to the last message, after sending it)! Just stay on the same position, where send button was taped. (Do like it done Telegram, for example - stay on the same location).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
