### ISSUE TITLE
Drafts are not displayed in message list

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7179]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
MMS drafts under a new group are not displayed in the messages list even though the draft is saved.

### Steps to reproduce
- Start new MMS group
- Compose message
- Go back to message list

**Actual result:** The draft is not displayed in the message list, but if you re-enter the group you can access the draft.
**Expected result:** The draft message should be shown in the messages list.

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.12.3

**Comment by wesdawg** [comment]
Update: Experiencing the same issue starting a new conversation with existing contacts, both Signal and SMS.

**Signal version:** 4.14.10

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
