### ISSUE TITLE
Can't add additional contacts to a new MMS group

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7180]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Once starting a new MMS group, there is no apparent way to add additional contacts to the group.

### Steps to reproduce
- Start new MMS group
- Compose draft message
- Try to add more contacts to the group

**Actual result:** There is no apparent way to add additional contacts to the newly created group.
**Expected result:** A plus button somewhere to add additional contacts to the new group after a draft message thread has already been started.

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.12.3

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
