### ISSUE TITLE
[Feature request] Emoji Search

### ISSUE THREAD

**Issue by trymeouteh** [signalapp/Signal-Android#7183]
This would be a harder one but if you could add a search box in the emoji keyboard so you can find emojis quicker that would be cool. A way to achieve this maybe is to add a feature to allow users to give tags to emojis and have that data sent to Signal and be evaluated and then and make those tags permanent with the emojis in a future update. This way the Signal community can tag the emojis and the Signal Devs can focus on other parts of the app.

**Comment by piratenpanda** [comment]
you could use gboard, it has emoji search

**Comment by trymeouteh** [comment]
@piratenpanda true but me and I am sure many others would like to stay away from Google due to privacy so gboard is not an option. That is why I like to use signal instead of WhatsApp which has more features.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
