### ISSUE TITLE
[Feature request] Image URL Displays

### ISSUE THREAD

**Issue by trymeouteh** [signalapp/Signal-Android#7185]
A minor feature request would be if a link ends with .jpg, .png, .gif, .bmp instead of showing just the link the image will load in Signal itself making it visible. This way when you are in a browser and you want to share a image you can do so easily and have it displayed in the app for others to see.

**Comment by PiCob** [comment]
I guess it's covered by #5724 or at least related...

**Comment by Meteor0id** [comment]
Is not an exact duplicate of #5724 as it adds the idea of recognising image sorces and loading the full image instead of a preview. Good idea.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
