### ISSUE TITLE
 Auto-updating APK works only sporadically

### ISSUE THREAD

**Issue by micressor** [signalapp/Signal-Android#7189]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
* I have 4 phones where I notice that the update works only sporadically.
* It seems that the update is enforced via wifi?
* A similar already closed ticket: [Can't update Signal standalone APK #6740](https://github.com/WhisperSystems/Signal-Android/issues/6740) 

### Steps to reproduce
- Check [latest.json](https://updates.signal.org/android/latest.json) to be sure, that is a newer version available.
- Wait for maximal 24 hours to be prompted for the update.

**Actual result:** On some phones the update is offered and sometimes not.
**Expected result:**

* The update is always offered.
* The ability to trigger the update (also via mobile data) manually.

### Device info

**Device:** Fairphone 2 (FP2)
**Android version:** 7.1.2 (LineageOS without any extensions)
**Signal version:** 4.11.5

### Link to debug log
* Acording to 9b8719e2d56a098502475bb5b2295c7a376d4caa, the auto-update is triggered every 6 hours.
* How can I enforce the trigger, that I can provide a logcat?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
