### ISSUE TITLE
Emojis Are Not Clear And Look Rough 

### ISSUE THREAD

**Issue by FaizKhan5** [signalapp/Signal-Android#7203]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
Bug description
Emojis Are Looking Rough After 4.12.3 Update Please Fix It

Actual result: Looks Rough Not Clear And Sharpe
Expected result: Looks Clear And Sharpe 

Screenshots
![img_20171117_063728_434](https://user-images.githubusercontent.com/26612909/32958627-da35f7ee-cbe0-11e7-88cf-980e23a4d7fa.JPG)
![img_20171117_063755_139](https://user-images.githubusercontent.com/26612909/32958632-e11f751c-cbe0-11e7-9915-6012b1995c29.JPG)
![img_20171117_063814_712](https://user-images.githubusercontent.com/26612909/32958651-eb5bd156-cbe0-11e7-9edc-4fca40b6f324.JPG)
![img_20171117_063840_332](https://user-images.githubusercontent.com/26612909/32958657-f3f269b0-cbe0-11e7-82e8-d9925e25d998.JPG)

Device info
Device: Qmobile Noir i6 Metal One
Android version: 6.0
Signal version: 4.13.1

Link to debug log
https://gist.github.com/35c66058838b9a864c9c5b05f7354002

**Comment by Evanito** [comment]
Not experiencing on Samsung GS7.

**Comment by FaizKhan5** [comment]
@Evanito Because your device is high-end. The problem is on low quality display 480p Screens.

**Comment by AndrewPy** [comment]
I also noticed that (with Signal version 4.13.4). 

On a Samsung A3 (SM-A300F) with 540 x 960 pixels, the emojis look like they were rendered in the wrong resolution. 

On a Wiko Pulp with 720x1280 pixels everything looks all right (as with the previous Signal version 4.12.3).

**Comment by FaizKhan5** [comment]
@AndrewPy Please post debug log for help thanks

**Comment by CFPrulez** [comment]
I can confirm this on my 480p screen. Unfortunately I don't see anything interesting in the logs.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
