### ISSUE TITLE
Stuttering while zooming and scrolling large images

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#7208]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

(Lazy copy pasting this from https://whispersystems.discoursehosting.net/t/stuttering-while-zooming-large-images/1591/1)

### Bug description

I'm experiencing stuttering when pinch-zooming large pictures in Signal.

Some examples when I zoom an image of size:

* 4032 x 3024 2.6 MB: stutters a lot
* 3840 x 2160 1.8 MB: stutters
* 2752 x 1548 0.9 MB: no stuttering, smooth zoom

I can't recall having this issue before. Maybe started experiencing this a few weeks ago? Currently running 4.13.1 and now 4.13.2
There's no stuttering in the Photos app with the same images.

It was speculated [here](https://whispersystems.discoursehosting.net/t/stuttering-while-zooming-large-images/1591/3) that the recent Glide update could have something to do with this

### Steps to reproduce
- Open a large image
- Try to zoom

**Actual result:** Zooming is slow and stutters
**Expected result:** Zooming should be butter smooth

### Device info

**Device:** Moto G4 Play
**Android version:** 6.0.1
**Signal version:** 4.13.1, 4.13.2

### Link to debug log
https://gist.github.com/952b9bdad590e3c1e7df9f5d93f20c57

I zoomed and scrolled a 4032 x 3024 (2.6 MB) image and then captured the log

**Comment by 2-4601** [comment]
I am **NOT** experiencing this on my Nvidia K1 with the same picture:
```
Device  : NVIDIA SHIELD Tablet K1 (sb_na_wf)
Android : 7.0 (1928188_904.2811, NRD90M.1928188_904.2811)
Memory  : 86M (1.05% free, 512M max)
Memclass: 192
OS Host : mobile-u64-831
App     : Signal 4.13.2
```

Could it be an issue with lower memory class with the Motorola?

Is it safe to downgrade from 4.13.2 to 4.11.5 to see if it's the Glide update?

**Comment by moxie0** [comment]
@2-4601 I don't think you can while maintaining the database, there have been migrations.

**Comment by fncnt** [comment]
Can reproduce on another Motorola:

```
Device  : motorola MotoE2(4G-LTE) (surnia_retde)
Android : 6.0 (3, MPI24.65-39-4)
Memory  : 64M (21.36% free, 128M max)
Memclass: 96
OS Host : ilclbld86
App     : Signal 4.13.6
```
So, low memclass seems plausible? But it used to work a few versions earlier. Not sure which versions, though.

**Comment by 2-4601** [comment]
I experience stuttering again in 4.17.5 with the same device.

- have a 90° rotated version of the example image at #7516 ([here you go](https://user-images.githubusercontent.com/174176/38143384-ecb6a2e4-3448-11e8-8529-783618e51271.jpeg))
- open the galler view and try to zoom
- behold the stuttering.

**Comment by greyson-signal** [comment]
@2-4601 Can you please post another debug log? Thanks!

**Comment by 2-4601** [comment]
https://debuglogs.org/033adb34ed2e107b49b7f9c40d279fc84f433013fb8dcd02b7c90d6d99b851bd

Scrolling of said image starts after 03-30 19:23:00 (there's probably some stuttering before that but the formatting in debuglogs.org gave me a headache so I didn't clean it up)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by szotsaki** [comment]
I can reproduce it with Signal 4.37.2. I don't know the actual size of the pictures Signal sent but in my Gallery they are around 6,91 MB big with dimensions of 5520×4140 px.

It heavily stutters when pinch-zooming or when changing to the next picture inside a "group picture" message.

Android: 8.0.0
Logs: https://debuglogs.org/78b6ae0b986cd48fbbfab6404c2f64a50dd42a138b1e576f94e4cb7ec4439946

**Comment by NotSoImportant** [comment]
Can reproduce on a Moto G4 Plus with Signal 5.3.12 and previous versions since years. 
Always hoped it would be fixed at some point :-/

Same lagging is by the way observed in "com.simplemobiletools.gallery.pro"
but *works without lagging* in "com.android.gallery3d", "com.ghostsq.commander"

**Comment by NotSoImportant** [comment]
This issue seems fixed and can be closed - if nobody insists
