### ISSUE TITLE
[Feature Request] Ability to delete safety numbers

### ISSUE THREAD

**Issue by nicholasfoden** [signalapp/Signal-Android#7210]
When another signal user has a temporary phone, or decides to delete signal, there is no option to purge keys for that user and return to Insecure SMS as default. 

It would be great if there was a remove keys, or reset user function in the menu to clean their key from your device.

**Comment by scienmind** [comment]
You can unregister (Settings -> Advanced -> Signal messages and calls). So unless I'm missing something, seems to me that the feature is already there.

**Comment by nicholasfoden** [comment]
Lets say my friend deletes the signal app and now only uses SMS.
I use signal for SMS + Signal Messages. 
How can I remove his keys from the signal app so i can SMS him without having to choose Insecure SMS for every message ?

**Comment by scienmind** [comment]
Oh, I see. 

There was an issue submitted (can't find it now...) requesting a "persistent SMS toggle per conversation", so that user can force SMS-default for a curtain contact. Seems like it might be a solution for this request as well.

**Comment by nicholasfoden** [comment]
Yes, sorry. My initial post maybe wasn't very clear.
 This is the same issue.

**Comment by nicholasfoden** [comment]
#4932 #7209 Are the relevant Issues to check, sorry for the duplication.

**Comment by nicholasfoden** [comment]
Okay since the other issues have been closed, I am going to re-open this one as it is probably a more relevant suggestion. 

Instead of changing any default behaviour or persistence. It would be great to have an option to delete a signal contact from your device, effectively reverting them back to a pre-signal sign up state, and therefore only allowing SMS messaging. 

If the user re-authenticates with signal, you would recieve new safety numbers and communication would be secure again.

**Comment by cornfeedhobo** [comment]
@nicholasfoden @scienmind I think #4678 is also related. It would be great to address this finally.

**Comment by nicholasfoden** [comment]
I understand the need for less options, not more, however this is a PITA for a lot of users. 

Perhaps reversion to pre signal key exchange state for a contact could be included in the delete conversation option, so deleting a conversation with another signal user will their safety numbers from the device and reset the conversation to SMS only. ( this may not be technically how it works, but the concept is there)

**Comment by anubiann00b** [comment]
I've has this problem recently with a contact losing their phone and getting a burner flip phone with the same number. I kept accidentally sending them signal messages instead of SMS messages because I'd forget to toggle to insecure messaging.

**Comment by cornfeedhobo** [comment]
> I'd forget to toggle insecure messaging.

@anubiann00b Where are you able to do that?

**Comment by scienmind** [comment]
@cornfeedhobo long-press the send button

**Comment by cornfeedhobo** [comment]
Wow. Just wow. Where did you find documentation for this and why is this not better known?

**Comment by Trolldemorted** [comment]
https://support.signal.org/hc/en-us/articles/212535548-How-do-I-send-an-insecure-SMS-

**Comment by cornfeedhobo** [comment]
Well, I still want to be able to trash safety numbers for peers that ditch signal without cleaning up properly, but that solves my immediate problem. I'll show myself the door :-D

**Comment by devurandom** [comment]
> long-press the send button

The trouble with that is, that it is only temporary, for one message.

Having a toggle in "Conversation settings" to change from "default to Signal messages" to "default to SMS" would be a huge improvement.

**Comment by nicholasfoden** [comment]
I think one of the major issues is that it is not clear to the user that they are receiving an insecure sms.

I am completely agreed with moxie the app should default to secure whenever possible. So having an insecure option persist is not a good choice.

Some workaround has to be made to this issue at some point though. 
I made a pull request where the insecure icon was changed to red #7367, but it was denied.

**Comment by nicholasfoden** [comment]
If you accidentally send private information through a sms because you forgot it was sticky, the situation would be different. having a secure default is necessary. Having the ability to remove safety numbers from your device is the other option, however the way the protocol works does not make that possible afaik. 

changing the UI to show a red icon would make it more prominent that the message you received was an sms and the user therefore could select the appropriate reply type. you could even make the sms send button red ( or any other color for that matter) to tie the two together.

**Comment by rubo77** [comment]
We could open a popup warning:

    Last time, you selected SMS as default. Do you want to send the messages in this session today again unencrypted?

saying "Yes" will set the blue button to grey SMS for this session again, so you cannot forget it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
