### ISSUE TITLE
4.10, 4.11 WebRTC calls cannot utilize wired headset microphone

### ISSUE THREAD

**Issue by zahnpasta12** [signalapp/Signal-Android#7215]
I have:
- [x] searched open and closed issues for duplicates
- []x read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Called contact can`t hear me. Headset works fine in other apps.

### Steps to reproduce
- Connect wired headset
- place a call
- Called contacts  can`t hear me, neither through headset- or internal mic (internal mic works fine when just  simple headphones are connected)

Headset worked fine with older Signal versions (3.x?)
### Device info

**Device:** Sony Xperia T
**Android version:7.1.1
**Signal version:4.10, 4.11

**Comment by moxie0** [comment]
I'm unable to reproduce this.

**Comment by zahnpasta12** [comment]
dmesg while placing a call with headset:
`[ 2127.672241] setting pm_qos in msm_pcm_playback_copy with 1000
[ 2127.672363] done setting pm_qos in msm_pcm_playback_copy
[ 2134.192247] adm_callback: Unknown Cmd: 0x10304
[ 2135.189378] adm_open ADM open failed for port 16385`

I don`t know if the failed open port is app- OS-related.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
