### ISSUE TITLE
When on Signal call, other calls aren't giving me a beep/notif that another call is coming in

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7216]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I'm on a signal call, and someone else calls me on a normal call, I don't hear a tone in the background to know about it.

### Steps to reproduce
- get in signal call
- have someone call you normally

**Actual result:** no discernable tone to let me know call coming in
**Expected result:** let tone come in

### Device info

**Device:** Galaxy Note 8
**Android version:** 7.1.1 stock
**Signal version:** 4.12.3

### Link to debug log
https://gist.github.com/f9085652f40aad191b255bd676748f02

**Comment by marwendoukh** [comment]
I have the same issue on Android 7.1.1 (Moto G5S).

I have been on a Signal call , and someone called me (phone call) . The call was automatically rejected and the other party sees "line busy".

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
