### ISSUE TITLE
Signal became unresponsive

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#7222]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While using Signal it became unresponsive. 
I was not able to select specific conversations and while I could select settings I could not select advanced (to create a log) After a while  Signal became responsive again and I've created the logfile. 

### Steps to reproduce
- so far unable to reproduce

**Actual result:** -
**Expected result:** - 

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.13.5

### Link to debug log

https://gist.github.com/anonymous/266800cbae389f1d36d3c108f3d95c94

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
