### ISSUE TITLE
Don't convert audio files automatically to mp3

### ISSUE THREAD

**Issue by DreamFlasher** [signalapp/Signal-Android#7223]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Audio attachments on Android are automatically converted to mp3 and thus not playable on the iOS app. 

### Steps to reproduce
- send a m4a audio file via "send audio"

**Actual result:** 
The file is playable on the Android, but not in the iOS app. 
**Expected result:** 
It should also play on iOS. 

### More info
If I use the same audio file and send it as a general file (not audio file) both Android and iOS clients can play the file inline. When saving the file in a folder in both ways, I found out that in the first case ("send as audio") it turns out the file was converted to mp3, while in the latter case the file remained untouched. 

### Device info

**Device:** Blackberry Priv
**Android version:** 6.0.1
**Signal version:** 4.12.3

**Comment by michaelkirk** [comment]
iOS should have no problem playing MP3’s.

Can you share an example file that fails to be playable on Signal-iOS when sent from Signal-Android?

**Comment by DreamFlasher** [comment]
http://techslides.com/demos/samples/sample.m4a

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
