### ISSUE TITLE
Changing group avatar results in strange behavior. 

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7226]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This is a follow up to https://github.com/WhisperSystems/Signal-Android/issues/7225. While https://github.com/WhisperSystems/Signal-Android/commit/a350106f7d73182934babf019e24f61b6e7de8e6 did fix the crash. It did not fix issue with the group avatar. 

### Steps to reproduce
The avatar you see in this image below is in fact the old avatar. I already replaced it with the new one (Buddy Jesus). However it is not displayed. 
![signal-2017-11-27-220005](https://user-images.githubusercontent.com/18451020/33289781-8ecf54fa-d3b8-11e7-8c6d-f83c7426dbca.png)

In the group view the old avatar is still shown as well. Although a recent change is recognized. 
![signal-2017-11-27-220009](https://user-images.githubusercontent.com/18451020/33289865-d00ca1a2-d3b8-11e7-8c5a-13fff2583535.png)

The recent chat overview shows an even older avatar. Restart of phone doesn't help. 
![signal-2017-11-27-220012](https://user-images.githubusercontent.com/18451020/33289951-0f6e6a10-d3b9-11e7-80ba-79c90c86a7ad.png)

However if I go to the settings again, there is Buddy Jesus in full glory. 
![signal-2017-11-27-220710](https://user-images.githubusercontent.com/18451020/33290093-87cca7ce-d3b9-11e7-9dd8-e1fd61d7fca1.png)

**Actual result:** Avatar setting is mixed up. This is not limited to the phone that changes the avatar. It applies to the receiving phone(s) as well. 
**Expected result:** None of the above

### Device info

**Device:** see log
**Android version:** see log
**Signal version:** see log

### Link to debug log

https://gist.github.com/9a6a03113c7322da2315803e3108abc3

**Comment by moxie0** [comment]
Could you provide steps to reproduce?

**Comment by halb9** [comment]
- Create a new group. Add two more people to it. No Avatar yet. 
- Add avatar1 to the group. avatar1 will be 'synced' to the other group members. Nothing strange yet. 
- Change avatar1 to avatar2. The new set avatar2 will be correctly displayed in the group edit menu. However if you go back to the chat avatar1 is displayed. In the recent chat list as well. 

Taking a look at one of the phones that was added passively to the group. 
After avatar1 was set it works fine. Everything is displayed correctly. 
After the change from avatar1 to avatar2 in the recent chat list avatar1 is displayed. In the chat avatar2 is displayed. And in the group edit menu avatar2 is displayed as well. 

https://gist.github.com/bba4f36634f550d2fb22ffb102aebd44

I hope this helps. If not I will do a complete screenshot work through.

**Comment by halb9** [comment]
With the 4.14.0 release this seems to be fixed. I was unable to reproduce after all three participants updated their version to 4.14.0.

**Comment by halb9** [comment]
sorry this is not 100% accurate. This is fixed for groups when they are freshly generated. 
In old groups I still have avatar1 in the edit menu. And avatar2 in the group chat. 

However this is easily fixed by just adding the same picture again and therefore refreshing the group. 

It seems like this bug only applies to you if you happened to change the avatar of a group while at the same time be on the beta channel of the app. I don't know how likely this is. 
But I'll reopen this since it is not completely resolved and please @moxie0 close it again if you are fine with it. 
Thanks anyways!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
