### ISSUE TITLE
Incoming messages are only received after sending a message

### ISSUE THREAD

**Issue by sam-jaques** [signalapp/Signal-Android#7227]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When encrypted text messages come from a verified contact, sometimes I do not receive them until I send another message back. 
Other similar bugs mentioned that power saving may be an issue. Via the "Security" app in the MIUI I set battery saver to "Off", and under "App Battery Saver", Signal has a custom setting  of "No Restrictions".

### Steps to reproduce
I cannot consistently reproduce the bug. Steps that have caused it in the past:
- Signal is open in the background (i.e., I have recently used it, have not closed it via the task manager, but have used other apps since opening it)
- Contact sends a text message to me
- I open the signal app
- I send a message back to the contact

**Actual result:** The message they sent appears only after I have sent another message back to them
**Expected result:** The message from the contact should be received as soon as it is sent

### Screenshots
In the screenshot you can see that the final message shown was from 39 minutes ago, yet was delivered after the message I sent 22 minutes ago. This was because the final message was only delivered after I sent the second-last message.
This means that in the debug log, it will be around 16:49 when the message was finally displayed, thought it may have been received any time after 16:32. Line 532 is right around the time this would have happened.
![screen shot 2017-11-27 at 5 13 38 pm](https://user-images.githubusercontent.com/8398540/33292220-74303d66-d396-11e7-8779-636f62f75e63.png)

### Device info
Device  : Xiaomi Redmi Note 4 (mido)
Android : 7.0 (V9.0.3.0.NCFMIEI, AL1512-mido-build-20171028011511)
Memory  : 34M (24.05% free, 512M max)
Memclass: 192
OS Host : mi-server
App     : Signal 4.12.3

### Link to debug log
https://gist.github.com/anonymous/6848cc7789aefa05008659a5c4f3caa1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
