### ISSUE TITLE
Feature Request: Option to auto-save received images/video to gallery

### ISSUE THREAD

**Issue by p0ll3** [signalapp/Signal-Android#7231]
An option to enable auto-save of received images would be neat. Every Person that I try to convert of Whatsapp to Signal, beefed about that feature.

**Comment by bowensong** [comment]
I would call this a security risk, not really a nice feature to have. If developers do decide to add this, I would suggest hide this option deep inside a menu, and put a warning on every single image saved when this options is turned on.

**Comment by altring** [comment]
I think it's going against Signal's philosophy. If you want to make smth public do this manually every time and accept a risk everytime...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
