### ISSUE TITLE
Inconsistent behavior in chatting with myself

### ISSUE THREAD

**Issue by JossMarley** [signalapp/Signal-Android#7247]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I often send messages to myself in order to remember things. I noticed that on Signal Desktop I can see my profile picture and I can send messages to myself. Those messages are correctly received also on my phone. On my phone, instead, I cannot see my profile picture, I can send messages to myself and see messages sent from Signal Desktop, but when I send a new message, I cannot see it on Signal Desktop.

### Steps to reproduce
- send a message to yourself
- open Signal Desktop and check if you receive the message

- check your profile picture when chatting with yourself

**Actual result:** I cannot see my profile picture when chatting with myself. Signal Desktop doesn't receive messages sent to myself from phone application
**Expected result:** I can see my profile picture when chatting with myself. Signal Desktop will receive messages sent to myself from phone application

### Device info

**Device:** Huawei P10 Lite
**Android version:** Lineage OS 14.1
**Signal version:** 4.13.6

**Comment by GuardianMajor** [comment]
I have experienced the same issue, I had originally posted mine on the Desktop repository as I wasn't sure what was causing it, but it was marked as being an Android issue, so I am going to link it here to keep the issue tidy and add more support for this issue.

https://github.com/WhisperSystems/Signal-Desktop/issues/1852

**Comment by altring** [comment]
4.14.10 - have exactly the same issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
