### ISSUE TITLE
Verification number not displayed correctly, when using a larger font

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#7251]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Verification number not displayed correctly, when using a larger font.

### Steps to reproduce
- Android Settings => Accessibility
- Set font size and display size to large
- Go to signal and display verification number.

**Actual result:** The most left and right numbers are cut, QR code is ok
**Expected result:** Scalled correctly

### Screenshots
![signal-2017-12-06-172349](https://user-images.githubusercontent.com/22525368/33673052-0e445646-daac-11e7-8b8d-e75bd0c77e79.png)

### Device info

**Device:** Moto G4
**Android version:** 7.1.2
**Signal version:** 4.13.7

**Comment by FaizKhan5** [comment]
I think verified button show after verified label not before

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
