### ISSUE TITLE
Distorted audio on voice/video call

### ISSUE THREAD

**Issue by stephensrmmartin** [signalapp/Signal-Android#7253]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I call my wife's phone via voice or video calling within the app.
I can hear her perfectly.
She hears an unintelligible voice from me; distorted, sorta chipmunky. Can't tell what I am saying.

She can hear me fine through google duo, standard calling, google hangouts.

### Steps to reproduce
- Engage a voice or video chat through signal.
- Listen on her phone for my voice

### Device info

**Device:** My device: Samsung Galaxy S4; Her device: Moto G5 Plus
**Android version:** 5.0.1
**Signal version:** 4.13.6

### Link to debug log
https://gist.github.com/anonymous/21d3013f7898ff6aea101da383a6c922

**Comment by dschrempf** [comment]
I can confirm this issue. Devices: Moto G5 or Galaxy S4 (have good sound) connected with LG G6 (which has distorted sound). Also, when activating the loudspeakers, there is heavy backcoupling. Sounds like a drumset being played.

**Comment by boromil** [comment]
I have the same kind of problems when doing a/v calls. Devices: Xiaomi MI 5/6.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
