### ISSUE TITLE
I Can't Produce Debug Log 

### ISSUE THREAD

**Issue by FaizKhan5** [signalapp/Signal-Android#7260]
#I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can't produce debug log only shows mobile model, android version, signal version, memory only no crash info. 

**Actual result:** Not showing crash info or anything in debug log only shows mobile info like i already told.
**Expected result:** Produce debug log with full crash report

### Device info
**Device:** Huawei Mate 10 lite
**Android version:** 7.0
**Signal version:** 4.14.4

**Comment by GuardianMajor** [comment]
Question, do you have 'developer mode' enabled on your device by any chance?

**Comment by Trolldemorted** [comment]
Could you upload logcat's output?

**Comment by GuardianMajor** [comment]
@Trolldemorted if you read the issue, they said they can't produce logs, I had this exact same issue; hence why I asked the question and waiting for a reply to help them generate it like I did.

**Comment by Trolldemorted** [comment]
I wasn't asking for Signal's debug log, I was asking for logcat's output.

**Comment by GuardianMajor** [comment]
I understand what you were asking for, but if it can't be generated inside the Signal app, the reason is potentially system wide, it was for me, and there is a reason for that, which if it ends up being the case, can easily be fixed. I tried to use ADB to generate and capture it too but it wasn't there either. So let's let them get back to us and try to help them generate the logs so we can figure out what might be wrong.

**Comment by Trolldemorted** [comment]
Logcat should at least log loaded activities and other debug info if signal doesn't crash immediately, and this issue does not mention that.

**Comment by GuardianMajor** [comment]
Agreed, and true, it does and should. However, I found their value in debugging app specific events to be extremely limited, and in my case provided nothing useful to aid the problem we were facing. But the changes I made to the system logging which I also outlined in a wiki page here, ended up producing useful app specific logs that were eventually submitted.

**Comment by FaizKhan5** [comment]
No developer option is disabled in device settings.

**Comment by GuardianMajor** [comment]
@FaizKhan5 Sorry, in that case unfortunately I don't think my workaround would help you. But just in case, take a look at [here](https://github.com/WhisperSystems/Signal-Android/wiki/Things-to-Check-if-Debug-Log-is-Empty) to make sure. Alternatively if you are familiar with ADB, you can try and send your main log - assuming you can capture it, or alternatively you can look on the Play Store for a Cat Log app and export it that way. I personally use aLogcat (but that is not an endorsement and requires root anyway) but there are many options out there if all else fails. Good luck, sorry couldn't help you with this.

**Comment by FaizKhan5** [comment]
I follow these steps but it doesn't produce any log but thanks for sharing.

**Comment by FaizKhan5** [comment]
@moxie0 why i can't produce ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
