### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7262]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I started Signal, 2 messages were unread (a report that a user in my contacts had joined Signal, twice for the same contact may also be an issue). When I started Signal, it crashed after typing in my password. After restart everything worked OK.

The relevant line in the debug log is

```
java.lang.AssertionError: Migration didn't happen! /data/user/0/org.thoughtcrime.securesms/files/signed_prekeys/13787880, 1
```

### Device info

**Device:** Sony Z3 compact
**Android version:** 6.0.1
**Signal version:** 4.14.4 (self built)

### Link to debug log
https://gist.github.com/anonymous/e19d0b5e8c180c4f439db67169656d96

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
