### ISSUE TITLE
Entering message from notification ocassionally causes message text input failure

### ISSUE THREAD

**Issue by jessebett** [signalapp/Signal-Android#7268]
Before we begin, please note that this tracker is only for issues, not questions or comments.

I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Occasionally entering a message directly from notification dropdown causes the input field to not record my text input. I have a keyboard, which I can type into, but no text is recorded and pressing send does not result in any sent text.

### Steps to reproduce
- Open message from notification dropdown (or lockscreen) 
- Type into the message input field

**Actual result:**  Occasionally typing doesn't fill the input field. To 'fix' I usually back out into the contact list and go back into the message, in which case typing into the input field works again.
**Expected result:** Typing into input field results in message text inputed.

### Screenshots
Will try to update with screenshot if I can catch it.

### Device info

**Device:** Nexus 6P
**Android version:**  8.0.0
**Signal version:** 4.13.6

### Link to debug log
Will update with device log after catching the bug next

**Comment by jessebett** [comment]
Possibly a duplicate of  #7039.

Though in my case the typed text is not only not visible, but also not inputted, i.e. sending the message doesn't result in previously invisible text sent as a message because no text wasn't recorded. Unclear if this is also observed in linked issue.

**Comment by jmatth** [comment]
A couple of friends and I also have this issue. [Here's a debug log I captured](https://gist.github.com/anonymous/d2410043add6633a5ff78fd6ed8f5b87) following one incident. Not sure what to make of it but I think all the `...on inactive InputConnection` messages are from the time I couldn't input text. One person reported that turning screen security off in settings fixed the issue but we haven't figured out how to reliably reproduce the issue so can't be sure. Running stock android with gboard as my input method in case it matters.

**Comment by jnns** [comment]
Just noticed it again on my device (Android 8.0.0, Signal 4.14.10). [Here's the debug log](https://gist.github.com/anonymous/466298dd434c2b08249d7abe702775a9).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
