### ISSUE TITLE
[Feature Request] Cooldown time mode for locking group chats temporarily

### ISSUE THREAD

**Issue by HongPong** [signalapp/Signal-Android#7269]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request description

Sometimes things are not good on a group message and when everyone is riled up I would request a way to get a cooldown for 1 minutes, 2 minutes or 5 minutes that would disable the sending of messages for that time period. (akin to temporarily locking a thread or page in other contexts). 

Perhaps this whole system could be tucked into a app preference and not displayed by default. There could be a second preference "respect cooldowns" which would be enabled by default.

It could be set up such that: one person initiates the cooldown and a second person concurs. This could be presented as a text bubble like, "XYZ requests a cooldown locking the chat for two minutes" and a "Accept" or "Decline" buttons are presented. The second person who approves could then send out a blocking message with the time limit on it. 

Then the other clients can disable their send buttons, and a mellow SVG animation with some kind of hourglass or similar would appear, or maybe an abacus subtracting numbers to zero. (like a bigger hourglass than the disappearing messages one, across the whole viewport). 

When the cooldown is completed the timer message disappears and the send buttons are enabled again.

I think this could in fact help the user experience significantly by giving a way to let a overall emotional moment blow over for a few minutes and then resume again. Thanks for the consideration here!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
