### ISSUE TITLE
Add separate notification settings for messages and calls

### ISSUE THREAD

**Issue by blipp** [signalapp/Signal-Android#7270]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I would like to configure _call_ notifications differently than _message_ notifications. To be more specific, in my use case I have messages only make the LED blink, but no vibration, no sound, because I consider messages being asynchronous and non-immediate communication requests. In contrast I consider calls being synchronous and immediate, that's why I want them to make my phone vibrate or use a sound.

Adding separate sections in the notification settings was mentioned by @moxie0 in another, two year's old bug: “eventually we'll add separate sections”, see https://github.com/WhisperSystems/Signal-Android/issues/4164#issuecomment-144825913. The title of this other bug doesn't really make one think of this feature request in my opinion, that's why I created this one. Maybe the other one can be closed then. Or merged and title changed.

### Device info

**Device:** Samsung Galaxy S5 Mini
**Android version:** 5.1.1
**Signal version:** 4.14.4

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
