### ISSUE TITLE
Cannot send Signal messages with attachment when using local mall's public Wi-Fi hotspot

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#7273]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I've recently connected to a local mall's public Wi-Fi network and noticed that Signal wasn't able to send any messages, while the other messenger I have installed (Threema) & the web browser had no problems.

Can you spot anything suspicious in the debug log?

Edit: I've tested this again and noticed that this only happens when the message has attachments (in my case a photo, haven't tested other attachment types). Messages without attachtments are getting sent instantly.
Additionally, I've noticed that the same happens with Threema. Message without attachment = successful, messages with attachtment = failed.
Also, I've done a second debug log which I'll add below.

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.0.0 / 8.1.0
**Signal version:** 4.14.2 / 4.14.7

### Link to debug log

https://gist.github.com/RiseT/b83f578b298154a9442db721c62c6ebd
https://gist.github.com/RiseT/2bf662172ab9b8661710ae584be34df3

**Comment by jeremymasters** [comment]
Where I have noticed this was at a Kohl's store where you had to hit a web browser to accept the connection, but their android already had a hold on my wifi.

**Comment by RiseT** [comment]
> where you had to hit a web browser to accept the connection

I had already done that (confirmed their term & conditions via a captive portal) when trying to send a Signal message.

**Comment by johanw666** [comment]
I see some references to websocket in those logs, are you using websocket or Google notification? Could it be that those sockets are hampered by that wifi setup (I never use those, I always have strange issues with those wifi access points).

**Comment by RiseT** [comment]
> are you using websocket or Google notification?

No websocket. Google notification.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
