### ISSUE TITLE
Searching by contact nickname is inconsistent

### ISSUE THREAD

**Issue by b0urb0n** [signalapp/Signal-Android#7276]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Searching for contacts by "Nickname" is inconsistent.

### Steps to reproduce
- create a conversation or search
- enter a contact's nickname

**Actual result:** Searching for some nicknames doesn't produce the contact
**Expected result:** Searching for a nickname should produce the contact with that nickname

### Screenshots
![contact_gator](https://user-images.githubusercontent.com/23001262/33976514-65f6724a-e063-11e7-8566-e5c6ae430c7c.jpg)
![contact_moose](https://user-images.githubusercontent.com/23001262/33976515-66013c98-e063-11e7-8d57-3b6ea4aa397d.jpg)
![search_gator](https://user-images.githubusercontent.com/23001262/33976516-660bea3a-e063-11e7-83f8-e6a8a8b76e4d.jpg)
![search_moost](https://user-images.githubusercontent.com/23001262/33976517-6616d67a-e063-11e7-9b09-3a48608c3965.png)

### Device info
**Device:** Google (LG) Pixel 2 XL
**Android version:** 8.0.1
**Signal version:** 4.14.5

### Link to debug log
N/A - Contact search issue

**Comment by FeuRenard** [comment]
Difference between gator and moose: moose is Signal user, gator not.

**Comment by b0urb0n** [comment]
@FeuRenard, that's correct.  I forgot to mention that.  I'm guessing this is because the Signal [ContactsDatabase](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java) doesn't store nickname.  Searching for a non-Signal contact is handled by Android and therefor picks up on the nickname.  

Just a guess from a non-Android-developer

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
