### ISSUE TITLE
"Signal is unlocked" Notification not low priority on Android 8.1

### ISSUE THREAD

**Issue by RichJeanes** [signalapp/Signal-Android#7278]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since I got the update to Android 8.1, the "Signal is unlocked" notification cannot be set as low priority, leaving the "unlocked" icon in my notification bar permanently.

### Steps to reproduce
- Set a password on Signal on a device running Android 8.1

**Actual result:** Signal's "Signal is unlocked" notification priority cannot be modified, leaving it permanently in the notification bar.
**Expected result:** Signal should (at minimum) be able to make the persistent notification low priority. Preferably, Signal should support notification channels: one for messages, one for calls, one for the persistent "unlocked" notification, etc.

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 8.1.0 (Build OPM1.171019.011)
**Signal version:** 4.14.7

**Comment by moxie0** [comment]
The notification is set to low priority, but I assume Android 8.1 has made the decision to display any foreground service notification as normal priority.

**Comment by RichJeanes** [comment]
It appears that without any notification categories, it isn't even possible to manually set the priority for any/all of the app's notifications. I can only set global notification settings for Signal.
![screenshot_20171215-154316](https://user-images.githubusercontent.com/6753081/34063502-bae0f8fa-e1af-11e7-9c98-33dbf7fdc32f.png)

**Comment by scienmind** [comment]
Separate notification channels should be defined for "unlocked" and "new message/call" notifications to allow setting different priorities for each.

(probably "connected" notification on gapps-free devices should have it's own channel as well)

FYI:
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels

**Comment by m3adow** [comment]
I noticed this annoyance on my OnePlus 3T after the December Update of Oxygen OS. This is still Android 8.0, so it's not exclusive to 8.1.

**Comment by RichJeanes** [comment]
It's interesting that this is an issue because according to that documentation
>If you don't target Android 8.0 (API level 26) but your app is used on devices running Android 8.0 (API level 26), your app behaves the same as it would on devices running Android 7.1 (API level 25) or lower.

Since [Signal targets level API 25](https://github.com/WhisperSystems/Signal-Android/blob/master/build.gradle#L243), shouldn't the "Unlocked" notification be behaving the same as before?

**Comment by eaon** [comment]
> I noticed this annoyance on my OnePlus 3T after the December Update of Oxygen OS. This is still Android 8.0, so it's not exclusive to 8.1.

There seem to be issues with Oxygen OS and notifications, I had the same issue but when I logged in and out of a different user the notification became low priority upon unlocking the Signal db

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by jlund-signal** [comment]
Support for notification channels is included in Signal version 4.25 which will be rolling out to beta users soon. The following channels and default priority levels are included on Android 8.0 or higher:

* Messages (High)
* Failures (High)
* Backups (Low)
* Locked status (Low)
* App updates (High - For users on the website distribution build)
* Other (Low)
