### ISSUE TITLE
Searching should search names of contacts in groups

### ISSUE THREAD

**Issue by Hooloovoo** [signalapp/Signal-Android#7283]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
If I search in the main screen for "Jonathan", it shows contacts named "Jonathan", but does not show the group Jonathan is a member of named "Awesome People"

### Steps to reproduce
- Type "Jonathan" in the search box

**Actual result:** Contacts or groups named "Jonathan" (or including "Jonathan") are displayed, but not groups that do not include this string (but have the displayed contacts as member).
**Expected result:** All groups containing contacts returned by the search should be displayed.

### Device info
**Device:** OnePlus 3T
**Android version:** 8.0.0
**Signal version:** 4.14.7

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
