### ISSUE TITLE
Crash when call starts ringing

### ISSUE THREAD

**Issue by smarek** [signalapp/Signal-Android#7284]
### Bug description
Signal will crash on call receive and outgoing, not immediately, but right after the ring-tone changes (indicating the other end of call starts ringing audibly)

### Steps to reproduce
Just call or let anyone call you

### Device info
**Device:** LG Nexus 5X
**Android version:** 8.1.0  (build OPM1.171019.011, non-rooted, stock version)
**Signal version:** 4.14.8

### Link to debug log
https://gist.github.com/anonymous/f4672fecd5981c6c54f268b4d52e323d

**Comment by MaxXor** [comment]
I can reproduce the problem on my Nexus 5X using latest Signal version 4.14.10. Signal crashes when calling or receiving a call from someone.

**Comment by smarek** [comment]
@MaxXor can you please provide debug log for us to compare, if your problem is equal? thanks

**Comment by TheGuad** [comment]
I uninstalled and reinstalled signal.  All is good now.

**Comment by smarek** [comment]
Ok, so some kind of data/executable/libra/aries corruption occurs, which Signal does not check for? Would be great to have a file snapshot (obviously without user data) of /data/data/org.thoughtcrime.securesms folder to check, if the files are corrupted, or if it is data-flow/call-stack-exec issue type we are looking at.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
