### ISSUE TITLE
Notification sound not settable via global settings

### ISSUE THREAD

**Issue by smontanaro** [signalapp/Signal-Android#7285]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
The notification sound is settable via settings within the running application, but not when you start fromthe global settings/apps & notifications.

### Steps to reproduce
- From the main screen, pull down and open settings.
- Select Apps & notifications
- Navigate to Signal and select
- Select App notifications
- Note that there is no item for setting the notification sound
- Back up to Apps & notifications
- Navigate to Gmail and select
- Select App notifications
- Select Mail under your account
- Note the Sound item and select
- See the list of available sounds

**Actual result:** There appears to be no way to set app sounds via the global settings route
**Expected result:** Given that most/all other applications I've tried allow you to do this, I expected Signal would as well.

### Device info
**Device:** Google Pixel
**Android version:** 8.1.0
**Signal version:** 4.14.8

### Link to debug log
https://gist.github.com/anonymous/45fd53ea9747f5f74614938a4b2162f1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
