### ISSUE TITLE
Signal Crashes if you swipe to dismiss "Inbox Zeeerrro"

### ISSUE THREAD

**Issue by tjharman** [signalapp/Signal-Android#7287]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When everything is archived and the (rather stupid IMHO but that's unrelated) "Inbox zeeerrro" message is showing, you can swipe right to dismiss it.  This causes a "Signal has stopped" message.

### Steps to reproduce
- Swipe to archive all messages on front screen.
- View the "Inbox zeeerrro" message and say to yourself "Gawd that's silly, I'll swipe right to dismiss THAT"
- Swipe right to dismiss it.
- Signal Crashes

**Actual result:** Signal Crashes
**Expected result:** "Inbox zeeerrro" message goes away, or unable to swipe away "Inbox zeeerrro" message.

### Screenshots
There is nothing worthwhile to take a screenshot of.  It's either the "Inbox zeeerrro" message or the "Signal has stopped" message.

### Device info

**Device:** Pixel OG
**Android version:** 8.1.0 Dec Security Patch
**Signal version:** 4.14.9

### Link to debug log
Unable to capture, Signal crashes and exits.

### Other
I have clicked the "Send Feedback" button a number of times, I don't know if you or Google get that feedback info.

**Comment by nrizzio** [comment]
Here is a debug log showing the crash:

https://gist.github.com/16096c1d4b9e7476dd6e32d8bfc93f6b

**Comment by Dyras** [comment]
@tjharman If you make it crash and then open the app again you can upload a debug log and it will contain info from the crash. Or is it crashing when you try to save a debug log?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
