### ISSUE TITLE
New emoji need multiple backspace taps for deletion

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7288]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Using emojis there are two types of backspace buttons you can use for removing them: the one from the emoji drawer and the one from your keyboard.

Using new emoji like 🧜 (basically [Emoji 5.0](https://emojipedia.org/emoji-5.0/), I think) shows different behaviours of the backspace buttons. I have to press the backspace button of my keyboard four times to make the emoji disappear. With the backspace button from the emoji drawer it disappears after one tap (expected behaviour).

This issue may be related to #6676. Threema shows the exact same behaviour, WhatsApp needs three taps for deletion.

### Steps to reproduce
- open a conversation
- open emoji drawer
- enter a emoji from the Emoji 5.0 set in the input field
- open keyboard
- press backspace button (repeat until emoji disappears)

**Actual result:** I have to press the backspace button four times.
**Expected result:** Emoji disappears after one backspace tap.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.14.9

**Comment by Dyras** [comment]
Moto G4 here with 7.0.1. Can't reproduce, the genies disappear in 1 backspace no matter where I use the backspace (on the keyboard, in the drawer)

**Comment by FaizKhan5** [comment]
Same Problem

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
