### ISSUE TITLE
Can not start a new conversation thread. Screen flashes after selecting Signal contact to message

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#7291]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Can not start a new conversation thread. Debug log contains some crash information. 

### Steps to reproduce
- Tap the message compose icon
- Select any of 3 Signal contacts that are shown

**Actual result:** Screen flashes and returns to inbox view/ conversation thread list
**Expected result:** Start a new conversation thread

### Screenshots

N/A

### Device info

**Device:** Samsung Galaxy 8+S
**Android version:** 7.0
**Signal version:** 4.14.10

### Link to debug log
 https://gist.github.com/f6b12d0f2585221f32d70735812c7c36

**Comment by moxie0** [comment]
there's no crash in this log, i would need a log of a crash or steps to reproduce

**Comment by riyapenn-signal** [comment]
Closing for incomplete information and no update from user.
