### ISSUE TITLE
Signal crashes sometimes when taking HDR pictures with google camera

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#7294]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When taking images with google camera, I don't know if it happens with other camera apps as well Signal sometimes crashes and I need to enter the passphrase again to open it. This happened on several 7.1.2 roms and on 8.1. stock now as well. 

### Steps to reproduce
- Take pictures with google camera
- open signal to share pictures

**Actual result:** Signal crashes and needs to be restarted
**Expected result:** Signal should not crash of course ;)

### Device info
**Device:** Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.14.10

### Link to debug log
https://gist.github.com/anonymous/1b6568be81fedb75b37f42dbc9d435a0

**Comment by piratenpanda** [comment]
It happens to other apps too, so I wonder if the apps need to be fixed or if this is an Android isssue at least on the 5x

**Comment by kaizoor** [comment]
I think it is an issue which is cause by the google camera.
It happens also when you take a HDR picture and want to view it before it is ready.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
