### ISSUE TITLE
Signal does not send to non-Signal users

### ISSUE THREAD

**Issue by staplepen** [signalapp/Signal-Android#7297]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I updated Signal to 4.14.10 yesterday and immediately stopped being able to send messages to non-Signal users.

### Steps to reproduce
- updated to Signal 4.14.10 after notification that my version of Signal was expiring
-immediately stopped being able to send messages
-eventually figured out that I could send messages to Signal users and not to nonSignal users
-can receive messages from both Signal and nonSignal users
-did not change any other software

**Actual result:** Not delivered Some issues need your attention Failed to send  = notifications
**Expected result:** message would send

### Device info
**Device: Moto G4
**Android version: 7.0
**Signal version: 4.14.10

### Link to debug log https://gist.github.com/fb60105bd98fea37e3105234b63b8c87

**Comment by moxie0** [comment]
Looks like you've disabled SMS permission for Signal

**Comment by staplepen** [comment]
Signal says that SMS is enabled. Here's the odd bit. I went through Signal in the order below. It says SMS is enabled.  When I got to "Touch to change your default SMS app" it yielded the Wireless and networks menu from Android Settings.

Signal
Menu (three vertical dots)
Settings
SMS and MMS On
SMS Enabled Touch to change your default SMS app
Wireless and networks
 Airplane mode
 Tethering and portable hotspot
  VPN
  Cellular networks

**Comment by staplepen** [comment]
Here is another debug log

https://gist.github.com/7a15dc837aa8288d450397f6ac22e01c

**Comment by staplepen** [comment]
Here's the sequence where I verified Signal has SMS Permission:

Android
swipe down
gear cog
Apps
Signal 
Permissions 
Contacts, Phone, SMS, and Storage
toggled SMS off and on again

**Comment by pintopwnie** [comment]
Having exact same issue however I've narrowed my problem down. My specific issue is when sending pictures to iPhones that do not have Signal installed. 
I cannot receive or send pictures to iPhones that do not have Signal installed.
I receive the following error when receiving picture from iPhone: "Error downloading MMS message, tap to retry."
I receive the following error when sending picture to iPhone: "Not delivered. Tap for details."

Staplepen, can you please confirm this is the case with your issue?

**Comment by staplepen** [comment]
No I am getting a different pattern. I can send photos to both iPhone and Android non-Signal users. I can not send plain messages to both iPhone and Android non-Signal users.

Here is the debug log from a failed text to an iPhone non-Signal user https://gist.github.com/ca8f5c623ee6945457532c8c231a4114

**Comment by staplepen** [comment]
Oops ignore debug log above because I'm unsure I ID'd it correctly.

This is the debug log for successfully sending a photo to an iPhone non-Signal user:

https://gist.github.com/anonymous/d6b64da2d5326f27cdbd92074984f227

**Comment by staplepen** [comment]
This is the debug log for successfully sending a photo to an Android non-Signal user:

https://gist.github.com/1e9f2d8dc38ff46fb5b2718b65e5f2c0

**Comment by staplepen** [comment]
This is a debug log for successfully sending a photo to an iPhone non-Signal user: https://gist.github.com/13fc79c1c471262c9b680d6cb2201118

**Comment by staplepen** [comment]
Here is the debug log from successfully replying to a Group message. Group has one Signal user and most people use iPhones.

https://gist.github.com/99634a91bc0a135261b625f50f8c6538

**Comment by staplepen** [comment]
Is it worth deleting Signal and reinstalling in the chance that a file got corrupted during download or installation?

**Comment by haffenloher** [comment]
You shouldn't have to reinstall. Did you deny any permission to Signal? `READ_PHONE_STATE` seems to belong to the "Phone" permission.

**Comment by staplepen** [comment]
This is weird. I had permissions enabled for Contacts, Phone, SMS and Storage. I just enabled all permissions IE enabled Calendar, Camera, Location and Microphone. A message to a non-Signal user failed. I disabled all permissions and then renabled Contacts, Phone, SMS and Storage. A message to a non-Signal user just went through. 

Why would this work?

**Comment by moxie0** [comment]
Probably your phone is fucked up, the Moto G4 seems to have a lot of device specific problems. The method that's throwing the SecurityException isn't even documented to require READ_PHONE_STATE: https://developer.android.com/reference/android/telephony/SmsManager.html#sendTextMessage(java.lang.String, java.lang.String, java.lang.String, android.app.PendingIntent, android.app.PendingIntent)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
