### ISSUE TITLE
4.14.10: Seemingly random crash while scrolling up in a conversation

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#7307]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
### Bug description
I decided to scroll up in a conversation to look at old pictures and when I was close to the top, Signal crashed on me.

### Steps to reproduce
Scrolling up again isn't causing a crash so I'm afraid I don't know how to reproduce it..

**Actual result:** During some unknown circumstances, Signal crashes while scrolling up in a conversation
**Expected result:** Signal should never crash while scrolling up

### Device info
Device  : motorola Moto G (4) (athene)
Android : 7.0 (10, NPJS25.93-14-10)
Memory  : 12M (4.94% free, 384M max)
Memclass: 192
OS Host : ilclbld26
App     : Signal 4.14.10

### Link to debug log
https://gist.github.com/anonymous/67aa1a7a47989fae250c051a6ca7872f

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
