### ISSUE TITLE
Back button in ShareActivity doesn't route back to 3rd party sharing source

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7312]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I share something from a 3rd party app to Signal. If I then use the back arrow in `ShareActivity` I will be forwarded to the activity I used the last time in Signal. But I would expect to be forwarded to the 3rd party app I shared from.

### Steps to reproduce
- open a Signal activity (a conversation, a settings page, an image, anything...)
- leave Signal via home button
- share something from another app to Signal
- press the back arrow in the action bar of Signal's "Share with" activity

**Actual result:** You see the activity you opened in the first step.
**Expected result:** You see the app from which you wanted to share something via Signal.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.14.10

**Comment by nribeka** [comment]
Adding ```android:taskAffinity=""``` seems to be fixing this. The physical back button and the back button on top left of the share activity will stop the share activity task and bring back the calling app.
