### ISSUE TITLE
LG G6 use wrong camera to scan QR Code for Signal-Desktop

### ISSUE THREAD

**Issue by kaizoor** [signalapp/Signal-Android#7313]
When I want to scan a QR code to connect signal desktop it will use the selfie camera instead the camera on the backsite

**Device:** LG G6 Europe (h870)
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 4.14.10

Debug Log:

Device  : LGE LG-h870 (lucye_global_com)
Android : 7.1.2 (f911d7b9e7, lineage_h870-userdebug 7.1.2 NJH47F f911d7b9e7)
Memory  : 47M (20.66% free, 1024M max)
Memclass: 384
OS Host : iktinos.acc.umu.se
App     : Signal 4.14.10

--------- beginning of main
01-03 13:42:17.974 18722 18722 W GcmBroadcastReceiver: GCM message...
01-03 13:42:17.992 18722 18742 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:17.993 18722 18742 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/
01-03 13:42:18.021 18722 18722 W GcmBroadcastReceiver: GCM message...
01-03 13:42:18.464 18722 18742 W PushReceivedJob: Received receipt: (XXXXX, 1514983336860)
01-03 13:42:18.467 18722 18742 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@d3039b4
01-03 13:42:18.467 18722 18742 W EarlyReceiptCache: Early receipt: (1514983336860, +***********71)
01-03 13:42:18.469 18722 18742 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@b0051b5
01-03 13:42:18.470 18722 18742 W EarlyReceiptCache: Early receipt: (1514983336860, +***********71)
01-03 13:42:18.473 18722 18742 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:18.473 18722 18742 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+***********71/1514983336860
01-03 13:42:18.500 18722 18722 W GcmBroadcastReceiver: GCM message...
01-03 13:42:18.597 18722 18742 W PushReceivedJob: Received receipt: (XXXXX, 1514983336860)
01-03 13:42:18.600 18722 18742 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@d3039b4
01-03 13:42:18.600 18722 18742 W EarlyReceiptCache: Early receipt: (1514983336860, +***********71)
01-03 13:42:18.602 18722 18742 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@b0051b5
01-03 13:42:18.602 18722 18742 W EarlyReceiptCache: Early receipt: (1514983336860, +***********71)
01-03 13:42:18.603 18722 18742 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:18.604 18722 18742 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+***********71/1514983336860
01-03 13:42:18.738 18722 18742 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:18.740 18722 18742 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+***********71/1514983337393
01-03 13:42:18.785 18722 18743 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@d3039b4
01-03 13:42:18.786 18722 18743 W EarlyReceiptCache: Checking early receipts (1514983336860): 1
01-03 13:42:18.786 18722 18743 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@45599dd
01-03 13:42:18.786 18722 18743 W EarlyReceiptCache: Checking early receipts (1514983336860): 0
01-03 13:42:18.806 18722 18743 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS file_name, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS fast_preflight_id, NULL AS voice_note, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 11) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 11) ORDER BY date_received DESC LIMIT 1)
01-03 13:42:18.843 18722 18743 W MessageDatabase: Updating ID: 61 to base type: 10485783
01-03 13:42:18.862 18722 18743 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS file_name, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS fast_preflight_id, NULL AS voice_note, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 11) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 11) ORDER BY date_received DESC LIMIT 1)
01-03 13:42:18.895 18722 18743 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS file_name, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS fast_preflight_id, NULL AS voice_note, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0 AND notified = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0 AND notified = 0) ORDER BY date_received ASC)
01-03 13:42:19.052 18722 18742 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:19.052 18722 18742 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/
01-03 13:42:19.173 18722 18743 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
01-03 13:42:19.174 18722 18743 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/
01-03 13:51:20.663 18722 18722 W PassphraseRequiredActionBarActivity: onCreate(null)
01-03 13:51:20.666 18722 18722 W ExperienceUpgradeActivity: getExperienceUpgrade(327)
01-03 13:51:20.666 18722 18722 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
01-03 13:51:20.667 18722 18722 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
01-03 13:51:20.747 18722 18722 W PassphraseRequiredActionBarActivity: onResume()
01-03 13:51:20.769 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-03 13:51:20.769 18722 18722 W KeyCachingService: Incrementing activity count...
01-03 13:51:20.770 18722 18722 W MessageRetrievalService: Active Count: 1
01-03 13:51:20.771 18722 18750 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0, gcm disabled: false
01-03 13:51:20.772 18722 18750 W MessageRetrievalService: Making websocket connection....
01-03 13:51:20.772 18722 18750 W WebSocketConnection: WSC connect()...
01-03 13:51:20.784 18722 18750 W SignalCommunicationModule: onConnecting()
01-03 13:51:20.790 18722 18750 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0, gcm disabled: false
01-03 13:51:20.791 18722 18750 W MessageRetrievalService: Reading message...
01-03 13:51:20.905 18722 14310 W org.thoughtcrime.securesms.components.emoji.parsing.EmojiPageBitmap: loading page emoji/People.png
01-03 13:51:21.071 18722 18733 I art     : Background partial concurrent mark sweep GC freed 121872(6MB) AllocSpace objects, 41(9MB) LOS objects, 39% free, 28MB/47MB, paused 1.666ms total 103.582ms
01-03 13:51:21.184 18722 14310 W org.thoughtcrime.securesms.components.emoji.parsing.EmojiPageBitmap: onPageLoaded(emoji/People.png)
01-03 13:51:21.276 18722 14308 W WebSocketConnection: onConnected()
01-03 13:51:21.276 18722 14308 W SignalCommunicationModule: onConnected()
01-03 13:51:21.278 18722 14308 W WebSocketConnection: WSC onMessage()
01-03 13:51:21.278 18722 14308 W WebSocketConnection: Message Type: 1
01-03 13:51:22.674 18722 18722 W PassphraseRequiredActionBarActivity: onPause()
01-03 13:51:22.707 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-03 13:51:22.707 18722 18722 W KeyCachingService: Decrementing activity count...
01-03 13:51:22.707 18722 18722 W MessageRetrievalService: Active Count: 0
01-03 13:51:22.722 18722 18722 W PassphraseRequiredActionBarActivity: onCreate(null)
01-03 13:51:22.726 18722 18722 W ExperienceUpgradeActivity: getExperienceUpgrade(327)
01-03 13:51:22.726 18722 18722 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
01-03 13:51:22.729 18722 18722 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
01-03 13:51:22.774 18722 18722 W PassphraseRequiredActionBarActivity: onResume()
01-03 13:51:22.938 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-03 13:51:22.939 18722 18722 W KeyCachingService: Incrementing activity count...
01-03 13:51:22.939 18722 18722 W MessageRetrievalService: Active Count: 1
01-03 13:51:22.999 18722 28454 D OpenGLRenderer: endAllActiveAnimators on 0x84a10580 (MenuPopupWindow$MenuDropDownListView) with handle 0x8804fed0
01-03 13:51:23.594 18722 18722 W PassphraseRequiredActionBarActivity: onPause()
01-03 13:51:23.605 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-03 13:51:23.605 18722 18722 W KeyCachingService: Decrementing activity count...
01-03 13:51:23.606 18722 18722 W MessageRetrievalService: Active Count: 0
01-03 13:51:23.613 18722 18722 W PassphraseRequiredActionBarActivity: onResume()
01-03 13:51:23.700 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-03 13:51:23.700 18722 18722 W KeyCachingService: Incrementing activity count...
01-03 13:51:23.701 18722 18722 W MessageRetrievalService: Active Count: 1
01-03 13:51:24.014 18722 18722 W PassphraseRequiredActionBarActivity: onDestroy()
01-03 13:51:25.424 18722 18722 W PassphraseRequiredActionBarActivity: onPause()
01-03 13:51:25.454 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-03 13:51:25.455 18722 18722 W KeyCachingService: Decrementing activity count...
01-03 13:51:25.455 18722 18722 W MessageRetrievalService: Active Count: 0
01-03 13:51:25.770 18722 28454 D OpenGLRenderer: endAllActiveAnimators on 0x935f5100 (MenuPopupWindow$MenuDropDownListView) with handle 0x88050650
01-03 13:51:27.539 18722 18722 W PassphraseRequiredActionBarActivity: onResume()
01-03 13:51:27.597 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-03 13:51:27.597 18722 18722 W KeyCachingService: Incrementing activity count...
01-03 13:51:27.598 18722 18722 W MessageRetrievalService: Active Count: 1
01-03 13:51:28.556 18722 18722 W PassphraseRequiredActionBarActivity: onPause()
01-03 13:51:28.576 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-03 13:51:28.576 18722 18722 W KeyCachingService: Decrementing activity count...
01-03 13:51:28.577 18722 18722 W MessageRetrievalService: Active Count: 0
01-03 13:51:28.584 18722 18722 W PassphraseRequiredActionBarActivity: onCreate(null)
01-03 13:51:28.588 18722 18722 W ExperienceUpgradeActivity: getExperienceUpgrade(327)
01-03 13:51:28.588 18722 18722 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
01-03 13:51:28.590 18722 18722 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
01-03 13:51:28.635 18722 18722 W PassphraseRequiredActionBarActivity: onResume()
01-03 13:51:28.757 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
01-03 13:51:28.757 18722 18722 W KeyCachingService: Incrementing activity count...
01-03 13:51:28.758 18722 18722 W MessageRetrievalService: Active Count: 1
01-03 13:51:28.857 18722 28454 D OpenGLRenderer: endAllActiveAnimators on 0x93755200 (MenuPopupWindow$MenuDropDownListView) with handle 0x8804fc40
01-03 13:51:36.184 18722 18722 W PassphraseRequiredActionBarActivity: onPause()
01-03 13:51:36.206 18722 18722 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
01-03 13:51:36.206 18722 18722 W KeyCachingService: Decrementing activity count...
01-03 13:51:36.207 18722 18722 W MessageRetrievalService: Active Count: 0

**Comment by 2-4601** [comment]
Related #4637

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
