### ISSUE TITLE
[Feature Request] Add ability to directly pull internal storage files to signal database.

### ISSUE THREAD

**Issue by las2mile** [signalapp/Signal-Android#7316]
For additional security of private content on storage, I think it would be great to have an option to directly pull internal storage contents to signal database.

**Comment by FeuRenard** [comment]
Would sending a message to yourself (phone number you registered with) work for you? You could attach any file in the same way you can when sending messages to your friends. You could then delete the files from your phone's storage.

In the future self messaging may be relabeled to "Notes" (see #5905) which would make this possibility more convenient and easier to discover.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
