### ISSUE TITLE
[Feature Request] Video attachment compression

### ISSUE THREAD

**Issue by dusscloud** [signalapp/Signal-Android#7320]
Hi,

As nowadays mobile phone have 1080p resolution, even a few couple seconds film can be quite difficult to sent depending on cellular/wifi coverage. Changing video resolution / compression would help, as it is today implemented when sending a picture.
Video attachment compression seem to be implemented in some other messaging app (Whatsapp for instance), it would be useful in Signal too.

**Comment by FeuRenard** [comment]
This is a duplicate of #6020
