### ISSUE TITLE
Google Pixel 2 notification dot no longer appears after re-enabling Signal as the default messenger

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-Android#7322]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Missing the notification dot for Google Pixel phones

### Steps to reproduce
- Have Signal set as the default SMS/MMS app
- Receive SMS or Signal messages
- See the notification dot on Signal's app icon
- Remove Signal as the default SMS/MMS app
- Receive a Signal message
- See a notification dot on Signal's app icon
- Receive SMS
- See a notification dot on the default SMS app
- Re-enable Signal as the default SMS/MMS app
- Receive SMS or Signal messages
- No notification dot visible
- Restart phone
- Receive SMS and/or Signal messages

**Actual result:** Do not see a dot on the Signal app icon
**Expected result:** See a notification dot on Signal's app icon

### Device info

**Device:** Google Pixel 2
**Android version:** 8.1.0
**Signal version:** 4.14.10

### Link to debug log

Log shared after trying to restart as a troubleshooting step: https://gist.github.com/b8ccabadf31a5115c95f49d0a27d6039

Log shared from separate user 2 (same phone, OS, Signal version) after receiving notifications: https://gist.github.com/riyapenn/b96629b8422b20b2b1f9ecb45709341e

Log from user 2 after a factory reset to capture the issue: https://gist.github.com/riyapenn/beea16bfb939c43463ed2cc746cb0902

**Comment by tallison63** [comment]
I have similar experiences on a Pixel 2 phone.
I've witnessed it on a Galaxy S8 but am not able to provide more details.

For me: I experienced the "no dot" after uninstalling and reinstalling the app.  I had previously attempted the steps cited above of adding and removing SMS messages before I noticed that dot was actually missing.
I have submitted a bug report: https://hastebin.com/mozifixugi

**Comment by jeremymasters** [comment]
I have a similar experience on my S8 (stock verizon rom).  The dot comes and goes.  Still trying to get a feel for steps to repro.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
