### ISSUE TITLE
add option to customize call ringtones (next to message ringtones)

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#7323]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have carefully looked everywhere, but I was suprised to find no way to modify the ringtone for incoming calls. There are only options to modify the ringtone for incoming messages, or the option is not in a place where a user would expect to find it.

### Device info
**Device:** noticed on multiple devices including Moto G line and Huawai P9
**Android version:** 7.0
**Signal version:** 4.14.10

### Link to debug log
holds no relevance

**Comment by Meteor0id** [comment]
Huge chance someone will reply telling me I didn't look hard enough or this ticket is a duplicate, but I honestly couldn't find a ticket making a clear destinction between messages and calls.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
