### ISSUE TITLE
Feature Request : Please Add Iconic Signal Ringtone

### ISSUE THREAD

**Issue by FaizKhan5** [signalapp/Signal-Android#7325]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Description
Please add iconic ringtone like Skype, WhatsApp etc app and also for notifications so it becomes more popular listening to special tone by people around you.

**Comment by Dyras** [comment]
And for the love of The Flying Spaghetti Monster, don't use the ringtone that you currently use on Signal-Desktop. That shit is agony to the ears.

**Comment by 2-4601** [comment]
The iOS version has it's own ringtone if I'm I recall correctly.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
