### ISSUE TITLE
Image sent from Signal-Desktop is black on Android

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#7326]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I sent an image from my Macbook and half an hour later I tried to look at the image on my phone. It's completely black and saving the image doesn't work at all. It's like the image isn't there.

### Steps to reproduce
Send a message and pray to the Nine Divines that this issue happens, I guess. I was at school so the trigger could be a shitty Wi-Fi connection.

**Actual result:** Images sent from Desktop are sometimes not there on Android.
**Expected result:** Received images are always there, ready to be viewed in their full glory

### Device info
Device  : motorola Moto G (4) (athene)
Android : 7.0 (10, NPJS25.93-14-10)
Memory  : 37M (9.93% free, 384M max)
Memclass: 192
OS Host : ilclbld26
App     : Signal 4.14.10
So damn sick of this phone 😞 

### Link to debug log
https://gist.github.com/anonymous/3fa6f9f41adc7be96cce533edd4c174b

**Comment by deepdad** [comment]
Same here with PDF, from OSX to Android mobile.

**Comment by Dyras** [comment]
@moxie0 I sent an image message from my phone last night and it was completely dark for the receiver. Do you want that as a separate issue?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
