### ISSUE TITLE
Sending messages is more reliable with WhatsApp compared to Signal on same network conditions

### ISSUE THREAD

**Issue by hzulla** [signalapp/Signal-Android#7327]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

My wife and I are both using Android 6 devices. We both have WhatsApp and Signal installed. When using the two apps on the same devices, we often observe that Signal fails to send a message to the other user while WhatsApp is able to send a message under the same network conditions.

The cause for this is unknown to me. However, a guess is that it seems to be related to DNS. Often, while being on the road using mobile internet, my cell phone provider gives me internet connectivity but DNS doesn't respond properly for a while. The phone tells me that it has internet, but the web browser complains about not being able to resolve URL addresses.

When this happens, WhatsApp still works, but Signal does not.

A guess would be that WhatsApp may have a hard coded list of server IP addresses or that it remembers those it had resolved previously when DNS was still working. But these are just guesses and it may be a different cause.

### Steps to reproduce
- try to send a message via Signal
- Signal complains that it cannot
- copy message text, go to Whatsapp
- send same message to same user, works this time

**Actual result:** Works with WhatsApp, Doesn't work with Signal
**Expected result:** If WhatsApp manages to send messages, Signal should too

### Device info
**Device:** Blackberry DTEK50
**Android version:** 6.0.1
**Signal version:** 4.14.10

Both devices using the same cheap cellphone provider with spotty mobile internet service.

### Link to debug log

I don't have a debug log. Will try to provide one once the bug happens the next time.

**Comment by hzulla** [comment]
By the way, this issue comes in two flavours:

1) Signal fails to send the message at all and requires a manual resend action by the user

2) Signal shows one checkmark for a successful send, but not a second for a successful reception.

In both cases, it can happen that WhatsApp messaging to the same recipient at the same time successfully transmits the message and gets a receipt confirmation, showing two checkmarks.

Sometimes, Signal receives an affected incoming message only when a major network change has occured. E.g., my wife sent me a message while one of us was on the road, but only when we are both at home using our WiFi hours later, the message is received and the recipient gets a notification on the phone.

**Comment by mlsxlist** [comment]
Noticed the same some times ago when we were skiing on a hut. The internet connection there was pretty flaky. Sending messages via Whatsapp was much more reliable than with Signal.

**Comment by xyzzyxw** [comment]
I think WhatsApp keeps trying to resend the message while signal gives up quite quickly, requiring the manual resend. Annoying.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
