### ISSUE TITLE
Group MMS messages not sending

### ISSUE THREAD

**Issue by jasom** [signalapp/Signal-Android#7333]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unable to send MMS Group messages

### Steps to reproduce
- create a group with at least one non-signal phone number
- send a message

**Actual result:** After about 30s a red exclamation mark appears, along with a "Not delivered" tag on the message.  Tapping for details shows a list of the group members with the message "Failed to send" below each member's name
**Expected result:** The message is sent.

### Device info

**Device:** Lenovo Moto G5 Plus
**Android version:** 7.0
**Signal version:** 4.4.10
**Network:** Ting (MVNO for T-Mobile)

### App state
- SMS Enabled
- SMS delivery reports off
- I have tried with 'WiFi Calling' Compatibility mode both on and off
- I have tried with WiFi on and WiFi of (i.e. cell data only)
- This worked on 2017-12-21 but does not work as of 2017-12-28.  I don't believe I did a system update since then, but various apps on my phone would have auto-updated in that time frame.

### Link to debug log

This log was captured with WiFi connected, but WiFi Calling compatibility mode disabled (which was how the settings were previously when things were working).  If logs with other setting combinations would be useful let me know, but all 4 combinations of those two settings show identical symptoms from a UI point of view.

https://gist.github.com/3f172ac23adc3342954ccd6225009ba5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
