### ISSUE TITLE
No MMS Notification When Data is Off

### ISSUE THREAD

**Issue by patrickmollohan** [signalapp/Signal-Android#7353]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When data is off, there are no notifications for MMS-based messages. I keep data off unless needed to help conserve battery and to block unwanted communications. This results in me missing MMS texts for many hours, if not days, when using Signal as the default messenger app.

### Steps to reproduce
- Turn off data
- Send MMS via another phone or email
- No notification

**Actual result:** There are no notifications for MMS messages when data is off. 
**Expected result:** If I enter the conversation, I can see Signal knows there is a MMS message waiting. It cannot retrieve it, which is fine, but I would expect that since Signal knows about the message, it could notify users who have their data turned off. Something like "Hey, dingdong! You have a message waiting. Turn on data to retrieve." This is how all other messaging apps handle the situation. I don't need it to automatically turn on data and retrieve (although that would be cool, too), but I do need something better than "just turn data on" (which I'm sure will be the hack that someone would recommend; I don't want, need, or desire data to always be on).

### Device info

**Device:** Asus ZenFone 2
**Android version:** 7.1.2
**Signal version:** 4.14.10

**Comment by jeremymasters** [comment]
I believe data is required to receive mms... Not to be confused with sms

**Comment by patrickmollohan** [comment]
To receive MMS, aye. I am not asking for it to receive the MMS, however. I am asking for a notification that tells me I have a MMS message waiting to download (which would then require data). For instance, here is a screenshot of the notification I receive from the stock Messaging app on Android:
![Screenshot of Received MMS Notification](https://image.ibb.co/jefTib/Screenshot_20180121_090352.png)
Notice data is off, as shown by the "x" next to the signal bar icon, yet it gives a standard notification just like any other message. In Signal, however, there is no such notification when data is off. As a matter of fact, if the conversation doesn't already exist, Signal doesn't show that there is a message waiting to be downloaded. However, if you are in the middle of a conversation and receive a MMS from that contact while data is off, Signal does know the message exists and where it came from, it just doesn't send a notification.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
