### ISSUE TITLE
Disappearing timer not started for two messages

### ISSUE THREAD

**Issue by cdenyar** [signalapp/Signal-Android#7356]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Two messages out of hundreds from the day before did not expire when I checked the conversation the following morning, tapping for info on the message there is now a new count down showing the message will expire however *many messages received after this one expired without issue*.

### Steps to reproduce
- Send a contact several hundred messages with a disappearing timer of 12 hours

**Actual result:** Some messages remain the next day >12 hours later
**Expected result:** All read messages have disappeared.

### Screenshots

![image](https://user-images.githubusercontent.com/6653063/35284872-e33b3c1e-0029-11e8-8080-47ee7e4d96c2.png)

![image](https://user-images.githubusercontent.com/6653063/35284891-eeda4678-0029-11e8-93b8-c951bd6770a5.png)

### Device info
**Device:** Pixel 2 XL
**Android version:** 8.1.0
**Signal version:** 4.14.10

### Link to debug log
https://gist.github.com/e23b39faef7f206c4fa2d6be861606bf

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
