### ISSUE TITLE
Display message count when "Hide sensitive notification content" on lock screen is chosen

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7358]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
In Android 6 there is a setting "Notifications -> When device is locked" which can be set to "Hide sensitive notification content" (or "Show all notification content" or "Don't show notifications at all"). This seems to be available from Android 5 on. I chose exactly this option with Android 6. Currently when I receive a Signal message and I look at the lock screen, I see a notification with the blue Signal icon, "Signal" as title and "_Contents hidden_" as subtitle. WhatsApp instead shows the current message count "7 new messages in 3 conversations". I would like Signal to also display the message count on the lock screen when "Hide sensitive notification content" is chosen.

### Developer resource
https://developer.android.com/about/versions/android-5.0.html#LockscreenNotifications

### Screenshots
Lock screen notifications with "Hide sensitive notification content"
![screenshot_20180124-210414](https://user-images.githubusercontent.com/16167751/35358417-de965134-0156-11e8-8ab9-6645e7f96d5a.png)
Android 6 notification settings
![screenshot_20180124-142747](https://user-images.githubusercontent.com/16167751/35336248-0454c052-0118-11e8-93fb-c88fa8150fdc.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
