### ISSUE TITLE
Sending multiple images at once problem

### ISSUE THREAD

**Issue by Flyerone** [signalapp/Signal-Android#736]
Hi,
When I send two or more images in the one MMS  message, only one image is visible in the chat window. So I am not sure if both are being sent until I ask if two pictures where received.

**Comment by frauzufall** [comment]
Hey, I just noticed this issue, hadn't updated for a while. Did the update now and was wondering if there is a way to get the missing images of already received MMS? I was just told that I am missing quite a few images.

**Comment by ryannathans** [comment]
### Bug description
When receiving MMS containing multiple images from non-signal contact, only first image is shown. 

### Steps to reproduce
- Make new MMS on another phone containing multiple images
- Send to signal phone


**Actual result:** Signal only shows image 1
**Expected result:** Signal shows all images in MMS message

### Device info

**Device:** Samsung Note 3
**Android version:** 5.0.0
**Signal version:** 3.16.0

### Link to debug log
https://gist.github.com/anonymous/a8814012a48c9031cc736bf3e4d44e8d
