### ISSUE TITLE
Use the Android call blocking content provider

### ISSUE THREAD

**Issue by shalzz** [signalapp/Signal-Android#7360]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Currently the signal Android app uses it's own call blocking list. Resulting in signal not respecting numbers blocked via the Android phone app and vice a versa. Leading to maintaining double block lists.
Also this results in the block list being lost between phone changes/factory resets.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
