### ISSUE TITLE
After update to android 5.1, outgoing calls don't work

### ISSUE THREAD

**Issue by jferrara77** [signalapp/Signal-Android#7361]
OK, so my issue is that I update my ageing moto g to android 5.1 and now when I pace a call it will either (1) endlessly try to connect without actually ringing, (2) day that the line is busy when it isn't or (3) most usually, eventually ring, be answered, but no sound is received on either end.

I have tried clearing cache of apps based on other posts, reinstalled signal, relinked with desktop but still have a problem here. 

Sending messages works fine as does recording calls.

Debug log is here immediately after both a busy response and soundless connection: https://gist.github.com/anonymous/0daee8544c16b496dd2381abbac767b1

**Comment by jferrara77** [comment]
And my thanks for looking at this. Last message sent prematurely...

**Comment by kgbm3** [comment]
Looking at _what_, exactly, though..:) Your update: was it a stock ROM, the correct one? Does the phone have a factory bootloader, is it rooted?.. 

Can you Factory Data Reset it?

**Comment by jferrara77** [comment]
I did give a link to the log and an accurate description of the predictable failure I think..

It is all stock, no rooting. 

I didn't try the factory reset because I've seen that advice in several places and it doesn't seem worth the time. If though there is some indication in the log that this is actually the source of the problem, I would consider it but otherwise it isn't worth the hassle right now.

Thanks again.

**Comment by moxie0** [comment]
Hey sorry there's nothing in the log. That phone is notoriously bad with many OEM bugs, you might at least try restarting it.

**Comment by kgbm3** [comment]
^^ Apologies for a somewhat crass reply previously, btw.

`https://support.google.com/android/answer/6088915?hl=en`

... It's not a choice, to Factory Reset after an upgrade; actually, it _must_ be done. In fact, there's a much better chance in being successful - running a reset, **both**, before and after a ROM upgrade.

(Thought this would've been common knowledge. :))
