### ISSUE TITLE
Back-Button doesn't return to previous app, when Signal is opened through a notification

### ISSUE THREAD

**Issue by francwalter** [signalapp/Signal-Android#7362]
### Bug description
I am in any app and I get a new message in Signal. I get an entry in my NotificationBar then. If I open the NotificationBar (drag it down) and tap the new Signal message, Signal opens directly the new message. Now I read it and maybe answer it, then I tap the Back-Button to go back to my previous app. But now the Back-Button goes back in the Signal hierarchy up to the main Signal screen and another Back-Tap gets me to my home screen and not to my previous opened screen of my previous opened app. This app is maybe closed now by Android.
This is often quite annoying, I would much prefer, that Signal behaves like e.g. WhatsApp or many other Apps in this context.

### Device info
**Device:** Cubot Note Plus
**Android version:** 7.0.0
**Signal version:** 4.15.5

### Further remarks 
I have this unexpected behaviour also [in k9mail](https://github.com/k9mail/k-9/issues/963) and Threema. k9mail's developer says it is by intention, see [Navigation with Back and Up](https://developer.android.com/design/patterns/navigation.html#into-your-app). But I think this is a misinterpretation of that design pattern, as there it is not described exact the same thing. It is described to navigate into your app, but not from one app into your app (through a notification from the NotificationBar).
I would understand if the Back Button would at least in the end (in the main screen of Signal) lead to the previously opened app, where the user started, but this is not the case, Back goes to the Home Screen, closing just Signal, ignoring where the user was.
This makes it not so nice to quickly open a notification through the NotificationBar if I am using another app.
Only WhatsApp does this in my eyes correct and consistent.

**Comment by FeuRenard** [comment]
Related to #7312

**Comment by nribeka** [comment]
@francwalter + @FeuRenard,
I think this can be closed since #7371 is merged.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
