### ISSUE TITLE
OGG-file support

### ISSUE THREAD

**Issue by derede** [signalapp/Signal-Android#7365]
Please make it possible to send ogg-files, I can't find out how. No, this is not a "feature request", ogg can be an audio format. Even sending as a file or sharing over music app doesn't work.

This really drives me crazy, most of my music collection is ogg. And, yeah, sometimes I want to share. And yeah, sometimes I would like to use signal for this. And, no, I really don't understand why ogg is not supported.

**Comment by p4nci** [comment]
@derede please don't open (new) duplicate issues. You have already commented under https://github.com/signalapp/Signal-Android/issues/6666 so please close this one
