### ISSUE TITLE
Tap for unsecure fallback prompt after switching phones and keeping number

### ISSUE THREAD

**Issue by higgsch** [signalapp/Signal-Android#7366]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After getting a new phone and keeping the phone number, messages always prompt "Tap for unsecure fallback" along with the message that the other user is no longer a Signal user. My contact is still a registered user and has made NO changes in settings since prior to the change in my phone. Received messages seem to be encrypted still but all sent messages are accompanied by the unlocked lock in the lower-right corner of message.

### Steps to reproduce
- Install Signal on device A (mobile)
- Register device A with a secondary number (such as Google Voice), which is forwarded to device A
- Install on desktop machine and link to device A
- Send and receive messages from contacts as usual
- Re-direct secondary number to device B (mobile)
- Install Signal on device B
- Register device B with the secondary number, which is now forwarded to device B
- Unlink desktop machine from device A
- Link desktop machine to device B

**Actual result:** All messages sent to existing contacts (synced through the desktop machine) indicate that the other user is no longer a signal user
**Expected result:** A prompt indicating that your safety numbers have changed and need to be re-linked with all contacts or automatic re-linking with all existing contacts

### Additional notes
This seems like it might be related to the following bugs (although different in the steps to reproduce):
#4812 and #6734  

### Device info
**Device:** Motorola Moto G5 Plus (potter)
**Android version:** 7.0
**Signal version:** 4.14.10

### Link to debug log
Immediately after sending the message and receiving the prompt:
  https://gist.github.com/d1e639bb189c2b2f66db55b120f75f03
Immediately after sending the unsecure message from the prompt:
  https://gist.github.com/99cd795d1baaf48d2fb2e09c2f1cb0e0

**Comment by jeremymasters** [comment]
@higgsch if you want to try to mitigate this, you might try choosing "reset secure session" in the conversation settings with that user.

**Comment by higgsch** [comment]
I forgot to mention that the "reset secure session" function had no effect on the situation. 
 
  On Fri, Jan 26, 2018 at 15:10, jeremymasters<notifications@github.com> wrote:   
@higgsch if you want to try to mitigate this, you might try choosing "reset secure session" in the conversation settings with that user.

**Comment by moxie0** [comment]
Hmm, what you're basically saying is that you've done a fresh install of Signal on a normal unrooted device, registered it with a number that was used elsewhere on a different device, and it doesn't work. There has to be something more to it than that, since I do that like 100x a day.

Looking at the log, it seems that your device somehow has an incorrect/distorted view of its own phone number.

**Comment by xyzzyxw** [comment]
Do you store your contacts in the phone memory? At some point, signal didn't work with them anymore, so I had to copy them to the Google account.

**Comment by higgsch** [comment]
@moxie0 Yes, basically. 

Signal was registered with an alternate phone number for both devices; that is, Device A had phone number A, Device B had phone number B, phone number C is a Google Voice number that was never attached to either device via sim but was registered on both devices with Signal. To be precise, Device A had no sim card (thus the original use of the alternate number).

**Comment by higgsch** [comment]
@xyzzyxw After I installed Signal on the new phone, I linked the desktop installation and that automatically imported my Signal contacts. So to be perfectly honest, I don't know where my Signal contacts are stored.

**Comment by higgsch** [comment]
Update: After discussing the issue with a contact, we noticed some further unusual behavior.
-After I received the prompt, if I choose to send the message using unsecure fallback, he would receive the message twice; once in Signal and once in his normal SMS app.
-If I choose to not send the message using unsecure fallback, he would receive the message in only Signal AND Signal would indicate to me that the message was not sent.
-If I ignore the prompt, he would also receive the message in only Signal.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
