### ISSUE TITLE
Signal No Longer Recognizes Android Contacts

### ISSUE THREAD

**Issue by ovi-vansid** [signalapp/Signal-Android#7368]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The Signal application (version 4.14.x and higher) no longer recognizes any Android contacts on Sailfish devices that employ Alien Dalvik.  All previous versions worked fine.  All Signal messages and basic conversation features work, but there is no visible association with contacts, so no names or pictures appear.

### Steps to reproduce
- Install Android support on Sailfish device (Sailfish version 2.1.3.7)
- Install Signal Android application (tested with 4.14.10 and 4.15.5)
- Open application and notice that all current conversations have "#" as contact image, as well as no names. 

**Actual result:** All current conversations have "#" as contact image, as well as no names.  Also, the new message screen is unable to display any available contacts.  If an attempt is made to add a Contact from an existing conversation, the following message appears: "There is no app available to handle this link on your device."
**Expected result:** The Signal application should be able to interrogate the Android subsystem to automatically import contacts.  At the very least, starting a new message conversation and selecting the "..." -> "Refresh" menu should import contacts and associate them with existing conversations.  

This unexpected behavior is not present with version 4.12.3 (downgrading solves the issue).  However, the older version will "expire" and is therefore not tenable as a long-term solution.

### Device info

**Device:** Sony Xperia X
**Android version:** 4.4.4
**Signal version:** 4.15.5

### Link to debug log
https://gist.github.com/29fa6a5dde054e02826ecab128e16534

I understand from reading several other bug reports that @moxie0 is not interested in supporting Sailfish or other non-pure Android environments.  I also have read several of his comments lamenting the current "broken state" of PC security (and security overall).  Many of his laudable efforts have improved security greatly for many people around the world.  However, I propose that not supporting Sailfish (and/or Alien Dalvik) while claiming to champion privacy and security are two opposing positions that do not comport.  Having an alternative platform, free from corporate spying and other unsavory anti-privacy features, are essential to those wishing for improved privacy and security.  The Sailfish platform, while imperfect, provides a "third way" for the security conscious.  I understand that a great deal of resources cannot be committed to this tiny - *perhaps* *insignificant* - subset of devices in a sea of Android devices awash with greatly diverse hardware and versions, but I ask that serious consideration be given to ensuring that basic Signal functionality is possible on the Sailfish platform.

Thanks

**Comment by moxie0** [comment]
> However, I propose that not supporting Sailfish (and/or Alien Dalvik) while claiming to champion privacy and security are two opposing positions that do not comport. 

Sorry, but there are only 24hrs in the day. It sounds like this is really important to you, though, so hopefully you can take it on instead.

**Comment by gregoa** [comment]
FWIW, this seems to be fixed with 4.15.5.

(Except for one contact whose name is shown in the contacts list but not in the chat history. But well, it works for the rest.)
