### ISSUE TITLE
feature: multiple profiles! for example but not exclusive to dual sim.

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#7369]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

not following rest of template as this is a global feature request not a device specific bug report
----------------------------------------
In short:
Suggestion to allow for multiple seperate (user) profiles within Signal Priavate Messenger. Either one for each SIM for dual Sim phones, **or** any number of user defined profiles to which a conversation can assigned.

This is a suggestion for a feature which other messenging apps seem to not have put any effort in yet. Therefore, implementing this might also give signal an edge and some publicity.
But besides that its just something some of us expected would be standard in 2018. Need to have.

I for one have a dual sim phone. In my case one sim for private use, anothe for business. **The business sim I may take out of my phone once or twice a year to hand over to a buisness partner.**

**The issue:**
In messaging apps including signal, all conversations are part of one account. They are all mixed together. On top of that (issue 2) my buisness partners can see the same profile as my family. This is rather restricting. My mother can see what my girlfriend can see and what my clients can also see. Just take a minute to imagine that. Yea that sucks right?

**Suggestion:**
Multiple (user) profiles in signal.
Its a rather drastic step, I know. But think about it. Its human nature to uphold different identities. And this is also what privacy is about. **I for one would love to keep those identities seperate.**
**The solution could be to have one identify for each sim card, or the solution could be to allow users to make infinite profiles and group contacts in them.**

I know this would be a massive undertaking, all I ask is that we think about this. Could this be something we want?

Addition:
**Both solutions are also relevant to single SIM phones!**
- In case of coupling a profile to a certain SIM instead of a certain phone, a user can switch his SIM for another one and also assume a different identity to use with it.
- in case of user defined profiles coupled to certain conversations, it obviously doesnt matter how many SIMs are in the phone, it will also be of use to single SIM phones.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
