### ISSUE TITLE
Signal icon does not obey the icon shape setting in Android 8.1 - icon is always circular

### ISSUE THREAD

**Issue by cegg1** [signalapp/Signal-Android#7373]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In Android 8.1 the shape of adaptive icons can be set to circle, square, rounded square, "squircle" or teardrop. 
Signal, however, does not obey the icon shape setting and always shows a circle-shaped icon. 

### Steps to reproduce
- long press on the launcher background
- tap on home settings
- change icon shape to any shape other than circle (default)

**Actual result:** The Signal icon remains circular in shape. Other icons do change shape. 
**Expected result:** The Signal icon changes shape together with the other icons. 

### Screenshots
**Available settings**
![icon-shape-setting](https://user-images.githubusercontent.com/28192843/35642212-53166504-06ba-11e8-9324-106d98c5d000.png)

**Results**
Circle (default)
![circle](https://user-images.githubusercontent.com/28192843/35642142-16bff26e-06ba-11e8-849a-8e2a94b5e78e.jpg)

Square
![square](https://user-images.githubusercontent.com/28192843/35642165-26e687ac-06ba-11e8-8d60-72b3c184766e.png)

Teardrop
![teardrop](https://user-images.githubusercontent.com/28192843/35642175-3156daca-06ba-11e8-86d4-7559fb95a5c1.png)

Rounded square
![rounded-square](https://user-images.githubusercontent.com/28192843/35642191-3b7e7472-06ba-11e8-97cd-b3c722bb310c.jpg)

Squircle
![squircle](https://user-images.githubusercontent.com/28192843/35642198-40ff9912-06ba-11e8-8eff-d2b7e80063dc.jpg)

### Device info
**Device:** Google Pixel 2
**Android version:** Stock Android 8.1.0 - OPM1.171019.013
**Signal version:** 4.15.5

### Link to debug log
- I suppose a debug log is not needed. I'm happy to provide one if necessary.

**Comment by Stanzilla** [comment]
That is https://github.com/signalapp/Signal-Android/issues/6511 that should be reopened. @moxie0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
