### ISSUE TITLE
Pressing the button on a Bluetooth headset does not pick up or end a Signal call

### ISSUE THREAD

**Issue by cegg1** [signalapp/Signal-Android#7376]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When an incoming Signal call rings and a bluetooth headset is paired and connected, pressing the multifunction button does not answer the call. However, if the call is answered manually on the screen, the bluetooth set engages automatically and works.

Even more surprisingly, pressing the multifunction button while a Signal call is in progress (and the BT set in use) has the effect of disengaging the BT headset - and handing the call over to the regular speaker- rather than ending the call.  

The same issue occurs on Pixel 2 (stock) and on Nexus 5 (LineageOS). 

### Steps to reproduce
- receive a Signal call, having a bluetooth headset paired and connected
- try to answer the call from the bluetooth headset 

**Actual result:** The call keeps ringing. It can be picked up from the screen but not from the bluetooth button. When the call is answered manually, however, the bluetooth set works fine. 
**Expected result:** Pressing the bluetooth button while a Signal call is ringing answers the Signal call, similar to how pressing it while a regular phone call is ringing answers the call. 

- while on a Signal call and speaking through a bluetooth headset 
- try to hang up by pressing the button on the headset 

**Actual result:** The call does not end, but the bluetooth toggle gets disengaged and the call is transfered to the regular speaker.  
**Expected result:** Pressing the bluetooth button while on a Signal call ends the call, just as it hangs up in a regular phone call. 

### Screenshots
Not relevant

### Device info
**Bluetooth headset:** Aukey EP-B40 Bluetooth 4.1
**Device 1:** Google Pixel 2
**Android version:** Stock Android 8.1.0 - OPM1.171019.013
**Signal version:** 4.15.5
**Device 2:** Google Nexus 5
**Android version:** LineageOS 14.1.2 - NJH47F (no root)
**Signal version:** 4.15.5

### Link to debug log

Trying to pick up a Signal call by pressing the bluetooth button (nothing happens)
https://gist.github.com/1dc59631a8efd0bc26ea9a98808c039f

Trying to end a Signal call by pressing the bluetooth button (Bluetooth disengages, but call continues on speaker)
https://gist.github.com/b2cc2ed5bc3a97e443f1179a62e45fe0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
