### ISSUE TITLE
Please support ChromeOS

### ISSUE THREAD

**Issue by rothgar** [signalapp/Signal-Android#7377]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Cannot install the Android app on a Chromebook now that the chrome extension is going to be deprecated it would be nice to have an alternative for ChromeOS. See signalapp/signal-desktop#871

### Steps to reproduce
- Buy a Chromebook that supports Android apps
- Try to install signal from the [play store](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en&rdid=org.thoughtcrime.securesms)

### Screenshots

![image](https://user-images.githubusercontent.com/371796/35662394-c07313b0-06cc-11e8-94bf-9bd64c68a31c.png)

### Device info

**Device:** Google Pixelbook
**Android version:** none
**Signal version:** any

I looked in the manifest to make sure touchscreen wasn't required (it isn't) but I'm not sure why else the app shows it's not compatible.
https://developer.android.com/topic/arc/index.html#update-manifest

**Comment by AluminiumTech** [comment]
@rothgar Probably the android SDK being used to target it. ChromeOS Android Apps use Android 7 afaik and the Signal app doesn't use Android 7 as a target version.

Note: Minimum SDK version and target SDK version are two different things.

**Comment by ADepic** [comment]
Why would you use signal which respects your privacy on a Chromebook... Which violates privacy as much as possible?

**Comment by haffenloher** [comment]
@ADepic please read at the [Contributing guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs) before posting here again. If you're looking for a discussion forum, join us over at https://whispersystems.discoursehosting.net/. Thanks!

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
