### ISSUE TITLE
Repeated crash on startup

### ISSUE THREAD

**Issue by gsstark** [signalapp/Signal-Android#7378]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes on startup. I can't get any further, it keeps crashing on every startup

### Steps to reproduce
- ?

### Device info

** Device:** Nokia 5
**Android version:** 7.1.2
**Signal version:** 4.14.10

### Link to debug log

01-31 20:01:46.663  5937  5958 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-4
01-31 20:01:46.663  5937  5958 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5937
01-31 20:01:46.663  5937  5958 E AndroidRuntime: java.lang.AssertionError: Session didn't get migrated: (0,+353863296037:1)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:70)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSession(SignalProtocolStoreImpl.java:76)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:179)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:159)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:129)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:159)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:138)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
01-31 20:01:46.663  5937  5958 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
01-31 20:02:16.990  7722  7758 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-2
01-31 20:02:16.990  7722  7758 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7722
01-31 20:02:16.990  7722  7758 E AndroidRuntime: java.lang.AssertionError: Session didn't get migrated: (0,+353863296037:1)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:70)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSession(SignalProtocolStoreImpl.java:76)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:179)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:159)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:129)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:159)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:138)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
01-31 20:02:16.990  7722  7758 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
01-31 20:02:39.578  9002  9043 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-1
01-31 20:02:39.578  9002  9043 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9002
01-31 20:02:39.578  9002  9043 E AndroidRuntime: java.lang.AssertionError: Session didn't get migrated: (0,+353863296037:1)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:70)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSession(SignalProtocolStoreImpl.java:76)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:179)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:159)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:129)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:159)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:138)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
01-31 20:02:39.578  9002  9043 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
