### ISSUE TITLE
Signal crashes in the background

### ISSUE THREAD

**Issue by nicolasmueller** [signalapp/Signal-Android#7381]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes in the background. As far as I can understand from the debug log, Signal was trying to access a previously downloaded update.
I am using Signal without Google Play, so Signal downloads the updates by itself.

### Steps to reproduce
- I do not know, since the crashes happened in the background (multiple during the same day times)

**Actual result:** Signal crashes in the background. I am prompted with the Android message that Signal has stopped working.
**Expected result:** The crashes should not happen.

### Device info

**Device:** LG G6 (H870)
**Android version:** Lineageos 14.1 / Android 7.1.2
**Signal version:** 4.14.10

### Link to debug log
I captured the log after two different crashes:
https://gist.github.com/anonymous/cfa2247bbdbcd5dbc1e3a0fccfca0342
https://gist.github.com/anonymous/22ef688b55e6486cc3c1a5488e737673
Please note that even though the debug logs are identical in the beginning, they differ further down and were captured after distinct crashes.

**Comment by primeapple** [comment]
Had the same issue today, using:

LineageOS 14.1, Oneplus2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
