### ISSUE TITLE
New contact name is not populated to existing conversation

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7382]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Adding a new contact from an existing SMS conversation that was previously imported from the default SMS app, the conversation does not get updated with the newly added contact name.

### Steps to reproduce
- Open imported, archived SMS conversation with number that doesn't exist as a contact.
- "Add to contacts", Create contact (Google)

**Actual result:** Conversation still shows only the phone number even when app is closed and reopened.
**Expected result:** Conversation should populate with the newly added contact name.

### Device info

Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.15.5

**Comment by FeuRenard** [comment]
Maybe refreshing your contacts could resolve this issue for you:

1. Open Signal
2. Tap the pencil button at the bottom right.
3. pull down the contact list to perform the refresh

**Comment by wesdawg** [comment]
@FeuRenard thanks, that seemed to work.

**Comment by RiseT** [comment]
I wonder how often Signal refreshes the contact list without manual intervention. Does it at all?

**Comment by FeuRenard** [comment]
Every 12 hours
https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/service/DirectoryRefreshListener.java#L15

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
