### ISSUE TITLE
Wrong MediaPreview title when entering via media item at position 0

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7385]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
[`initializeActionBar`](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/MediaPreviewActivity.java#L127) is generally only called in [`onPageSelected(int position)`](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/MediaPreviewActivity.java#L329). But this listener method won't be called if the first position of the ViewPager is 0.

### Steps to reproduce 1
- open a conversation
- go to "All media"
- tap the media item at the very top

### Steps to reproduce 2
- open a conversation
- scroll to the oldest media item (at the top)
- tap this media item

### Steps to reproduce 3
- open a conversation
- attach an image or video (don't send)
- tap this media item

**Actual result:** "Media Preview" (`@string/AndroidManifest__media_preview`) is displayed in the action bar.
**Expected result:** Sender name and date/"Draft" are displayed in the action bar. These information will be displayed after swiping to another media item and then returning to the initial one.

### Screenshots
directly after entering MediaPreview
![screenshot_20180203-124610](https://user-images.githubusercontent.com/16167751/35766907-299f6fa8-08e1-11e8-854e-1a356bc8f48b.png)
after swiping sideways and back
![screenshot_20180203-124617](https://user-images.githubusercontent.com/16167751/35766908-2c93ca10-08e1-11e8-943f-bfd4343bb614.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.15.5

**Comment by FeuRenard** [comment]
While investigating this, I found another issue with the same root cause:

### Bug description
If you enter `MediaPreviewActivity` with a video and this video is at position 0 (at top of conversation or first entry in media overview) and you swipe away from it, it won't be stopped (in addition to the bug described in the comment above). The reason for this also is, that `onPageSelected(0)` is never called. In consequence when later `onPageSelected(1)` is called it won't call `onPageUnselected(0)`.

### Steps to reproduce
- open a conversation
- send a video
- open "All media"
- select the video you just sent (should be at position 1)
- observe that video is playing (expected behaviour)
- swipe to the next media item

**Actual result:** The video doesn't stop playing.
**Expected result:** The video stops playing.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
