### ISSUE TITLE
How to decode the SMS field of the message.db database

### ISSUE THREAD

**Issue by yota-code** [signalapp/Signal-Android#7389]
Hello,

I need to change my android phone. But I had some deep conversation with my friends about funny cats and other very important topics, and used MMS a lot...
I did a backup of all the pictures manually, one by one, but I missed the stupid comments associated to them. So I entered my phone and made a backup of the database found in `/data/data/org.thoughtcrime.securesms`. 
The `message.db` was easily opened with `sqlitebrowser` and I found that the SMS are encoded or encrypted. 

`IuLAHHO16mm2yqT3bfX1dXyyDu/TLGLmSIv1qmO2mt+fygOV+jH/BhJJBF/bue5cJl8mOq==`

It looks like some base64 ? or something else... Could you point me to the algorithms used to encode/decode this ? a clue ? or something ?

thank you :)

(I don't know how to add the label Help Wanted)

**Comment by PiCob** [comment]
Unfortunately, it seems you didn't read the bug report template at all (and even removed it intentionally)... Among other things, it states that this tracker is only for issues, not questions or comments.

If you are looking for support, please see our support center instead:
https://support.whispersystems.org/
or email support@whispersystems.org

**Comment by yota-code** [comment]
thx for the aid!

**Comment by homlett** [comment]
There is not solution yet, but let's talk about it here: https://whispersystems.discoursehosting.net/t/reading-messages-from-messages-db/514
