### ISSUE TITLE
starting video while call reboots phone

### ISSUE THREAD

**Issue by voxspox** [signalapp/Signal-Android#7392]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---

### Bug description
Starting video transmission while a signal phone call reboots phone. For an S7 this happens immediately. For another phone (Xcover3) the video is transmitted for maybe 3 seconds, then freeze some seconds then reboot.

### Steps to reproduce
- accept incoming call
- tap video icon
- phone reboots

### Device info 1
**Device:** Samsung S7
**Android version:** LineageOS 14.1-20180131
**Signal version:** 4.15.5

### Device info 2
**Device:** Samsung Xcover3
**Android version:** Android 5.1.1
**Signal version:** 4.14.10

### Link to debug log
How can I gather useful information which survive the reboot?

**Comment by FeuRenard** [comment]
> How can I gather useful information which survive the reboot?

You can connect your phone to a computer via USB and use `adb logcat` for retrieving logs. Here are instructions for the command line tool:
https://developer.android.com/studio/command-line/logcat.html
If you are uncomfortable with the command line you could alternatively use Android Studio for running logcat:
https://developer.android.com/studio/debug/am-logcat.html

**Comment by voxspox** [comment]
ok. I created 2 logs for the S7. The log starts directly before the video icon is touched (during call is already established)

[signal1.log](https://github.com/signalapp/Signal-Android/files/1692916/signal1.log)
[signal2.log](https://github.com/signalapp/Signal-Android/files/1692917/signal2.log)

**Comment by moxie0** [comment]
Looks like you're running a custom ROM? If the device is rebooting then it's a ROM bug, there should be nothing that any app can do to make that happen.

**Comment by voxspox** [comment]
agree, the S7 runs LineageOS 14.1.
The Xcover3 has the shipped Android. I will check the logs there.

**Comment by p4nci** [comment]
I can confirm this issue: Samsung S7 reboots immediately when during an audio call the video button is pressed (Device A).
Tested with
Device A: Samsung S7 (LineageOS 14.1)
Device B: Nexus 5x (also LineageOS 14.1)

Triggering a video call from Device B works as accepted i.e. there is no reboot.

BTW: it's well-known that Samsung S7 has many camera problems with LineageOS, so imo this is definitely a ROM bug 😞

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
