### ISSUE TITLE
Voice call volume issue

### ISSUE THREAD

**Issue by RobertTEG** [signalapp/Signal-Android#7395]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In a voice call, the volume of the interlocutor is lower than usual, and increasing it from the system won't help. This may affect the standard call's volume too (in my case).

### Steps to reproduce
- Call someone
- The interlocutor voice will be heard lower than usual
- Increase the volume from the system

**Actual result:**
Even after increasing the volume, the interlocutor is heard quiet.
**Expected result:**
The person you're talking to should be heard louder and clear.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.15.5

### Link to debug log
https://gist.github.com/f7aa9b3834cecd8eefbc628a506554cc

**Comment by halb9** [comment]
There are a couple of issues already for this topic. 
https://github.com/signalapp/Signal-Android/issues?q=is%3Aissue+low+volume+is%3Aclosed 

I face the exact problem (although with an S5 not an S7). 
There is a bug report in the LineageOS Tracker as well. 
https://jira.lineageos.org/browse/BUGBASH-275

It seems this is something which has nothing to do with Signal in particular. And for LineageOS it is really hard to fix.

**Comment by RobertTEG** [comment]
Well, I think it happened after I installed the version 4.15.5 on my device. Before that, everything was fine... I tried to uninstall it and reinstall, but nothing worked.
