### ISSUE TITLE
Creating debug log fails and seems to make Signal unresponsive

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#7401]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After I received a message I've noticed that message took ~20min to be delivered. Since this seems to happen occasionally I've tried to create a debug log hoping to provide some information about this delay. 
When I tried to create a debug log this failed and it only keeps showing the message: "Loading logs..." When I tried to go back to the conversations overview Signal also seems to be unresponsive. Since I could not create a log I've tried to get some information with logcat. See logcat file below. 
 I've noticed the screen was flooted with 
`
02-06 21:53:16.596 28914  2477 E RenderScript: rsAssert failed: ret == bytes || mShutdown, in frameworks/rs/rsFifoSocket.cpp at 83
`
messages. In addition to logcat I've also created a traces file by executing ps -3 signalpid(28914). Not sure if it's useful though. I was only able to stop the messages described above by forcing Signal to stop. After I've opened Signal again things seem to work normal again and I was also able to create debug logs.

### Steps to reproduce
- Was unable to reproduce. See description.

**Actual result:** Debuglog keeps showing "Loading logs.."
**Expected result:** Logfile is created.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.16.4

### Link to debug log

[logcat_20180206.txt](https://github.com/signalapp/Signal-Android/files/1702642/logcat_20180206.txt)
[traces_signal.txt](https://github.com/signalapp/Signal-Android/files/1702622/traces_signal.txt)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
