### ISSUE TITLE
Signal crashes on startup after clean install

### ISSUE THREAD

**Issue by Mitmischer** [signalapp/Signal-Android#7402]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes on startup.

### Steps to reproduce
- Wipe Signal data.
- Uninstall Signal.
- Install Signal.
- Start Signal.

**Actual result:** Signal crashes. 
**Expected result:** Signal does not crash.

### Screenshots
-- none --

### Device info

**Device:** Samsung Galaxy S4 Active
**Android version:** 7.1.2 (LineageOS)
**Signal version:** the newest one

### Link to debug log
I obviously cannot use Signal's debug log. I captured the following log with `adb logcat | grep -i thoughtcrime`: https://gist.github.com/Mitmischer/d483be1f08b5ba5ca189ce0a45565eb4
I restarted my phone at 10:30. Signal was still installed. I then (around 10:37?) started Signal and it crashed. I wiped Signal's data, reinstalled it and started it. This is where the logcat ends.
It's not hard to see that is error is somewhere here, or earlier: `02-08 10:39:47.451 7687 7712 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/messages.db'.` I wonder if that's an installation issue?

**Comment by moxie0** [comment]
The "newest one" isn't terribly specific. The alpha channel, the beta channel, production, building from HEAD?

From your log it looks like Signal doesn't have access to the filesystem:

`````
02-08 10:39:47.410  7687  7703 W ContextImpl: Failed to ensure /data/user/0/org.thoughtcrime.securesms/databases: mkdir failed: ENOENT (No such file or directory)
02-08 10:39:47.423  7687  7703 E SQLiteLog: (14) os_unix.c:32460: (2) open(/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs) - 
02-08 10:39:47.425  7687  7703 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs'.
02-08 10:39:47.426  7687  7703 W ContextImpl: Failed to ensure /data/user/0/org.thoughtcrime.securesms/databases: mkdir failed: ENOENT (No such file or directory)
02-08 10:39:47.427  7687  7703 E SQLiteLog: (14) os_unix.c:32460: (2) open(/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs) - 
02-08 10:39:47.428  7687  7703 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs'.
02-08 10:39:47.435  7687  7703 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7687
02-08 10:39:47.446  1353  1885 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-08 10:39:47.448  7687  7712 W ContextImpl: Failed to ensure /data/user/0/org.thoughtcrime.securesms/databases: mkdir failed: ENOENT (No such file or directory)
02-08 10:39:47.449  7687  7712 E SQLiteLog: (14) os_unix.c:32460: (2) open(/data/user/0/org.thoughtcrime.securesms/databases/messages.db) - 
02-08 10:39:47.449  7687  7687 W ContextImpl: Failed to ensure /data/user/0/org.thoughtcrime.securesms/shared_prefs: mkdir failed: ENOENT (No such file or directory)
02-08 10:39:47.451  7687  7712 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/messages.db'.
02-08 10:39:47.451  7687  7712 E SQLiteDatabase: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:669)
02-08 10:39:47.451  7687  7712 E SQLiteDatabase: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
02-08 10:39:47.453  7687  7712 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:669)
02-08 10:39:47.453  7687  7712 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
02-08 10:39:47.453  7687  7712 W ContextImpl: Failed to ensure /data/user/0/org.thoughtcrime.securesms/databases: mkdir failed: ENOENT (No such file or directory)
02-08 10:39:47.454  7687  7712 E SQLiteLog: (14) os_unix.c:32460: (2) open(/data/user/0/org.thoughtcrime.securesms/databases/messages.db) - 
02-08 10:39:47.455  7687  7712 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/messages.db'.
02-08 10:39:47.455  7687  7712 E SQLiteDatabase: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:669)
02-08 10:39:47.455  7687  7712 E SQLiteDatabase: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
02-08 10:39:47.621  1353  1885 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-08 10:39:47.621  1353  1885 W ActivityManager: Duplicate finish request for ActivityRecord{10bcd38 u0 org.thoughtcrime.securesms/.RoutingActivity t2053 f}
02-08 10:39:47.640  1353  6600 I ActivityManager: Process org.thoughtcrime.securesms (pid 7687) has died
`````

It looks like you're running a custom ROM, so I'm guessing a ROM bug or something fucked up like Xposed etc.

**Comment by Mitmischer** [comment]
Hello,
thank you for your fast response and sorry for my late one!
I was using the latest Signal version from Play store.
Your explanation looks reasonable to me. I explicitly granted Signal storage accces and rebooted my phone, however the error persists. You can the log of this attempt here: https://gist.github.com/Mitmischer/011c85a1a564041821cafe42ffddd61d . What bugs me are the following lines:
```
02-13 14:20:14.576 1318 1514 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package org.thoughtcrime.securesms because it was previously installed without
```
```
02-13 14:20:30.283   335   335 E cutils  : Not a directory: /data/data/org.thoughtcrime.securesms
02-13 14:20:30.283   335   335 E installd: Failed to prepare /data/data/org.thoughtcrime.securesms: Success
02-13 14:20:30.283  1318  1384 E PackageManager: Failed to create app data for org.thoughtcrime.securesms: com.android.internal.os.InstallerConnection$InstallerException: Failed to execute create_app_data [null, org.thoughtcrime.securesms, 0, 2, 10125, default, 25]: -1
02-13 14:20:30.283 335 335 W installd: Failed to stat /data/data/org.thoughtcrime.securesms: No such file or directory
```
I checked the `/data`-folder from my phone and it appears empty. If I however try to create a `data`-folder, it says that the folder already exists. If a choose another name, I cannot create a folder due to insufficient permissions. Very weird.. I could also imagine that the previous removal of Signal was not complete. Is there any way I can list the content of `/data/data`? Should Signal actually try to access `/sdcard/data`? At least, that folder is writable..
I would go with a ROM bug, too, I guess - but why is Signal the only app affected :| ?

**Comment by Mitmischer** [comment]
Reinstalling Signal via Play Store did not help. But when Signal is installed by Yalp Store, it suddenly works fine. Well, very weird to say the least, but it's working now. Sorry for the noise. I'm closing this issue as it's solved for me (yet..) . If you want to investigate further and you need logs or anything, feel free to reopen.
