### ISSUE TITLE
SMS sent via KDE Connect do not appear

### ISSUE THREAD

**Issue by steelstring94** [signalapp/Signal-Android#7403]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using the KDE Connect app with Linux Fedora 27 KDE, messages sent via the desktop in reply to unencrypted SMS do not appear in the conversation in the actual phone app.  In other words, I see only the received texts and not the sent ones.  This problem does not exist with Android Messages.

### Steps to reproduce
- Install KDE connect app on phone
- Use Linux Fedora 27 KDE and activate KDE Connect on this desktop computer
- Connect the phone to the computer as per the usual procedure with this app
- Receive a text message on the connected phone while using Signal as the default SMS app
- Reply to the text message by clicking the reply button in the notification popup that appears on the KDE desktop upon receipt of the SMS
- Open the Signal app on the phone
- See that your reply does not appear in the conversation, although your interlocutor will have received it
- Open Android Messages and see that your replies sent via the reply window provided by the KDE Connect desktop notification do, in fact, appear there (therefore it is, in principle, possible to capture these replies, so sent via the desktop app, in a phone app).

**Actual result:** Messages sent by the KDE Connect desktop app do not appear in the conversation in the Signal app on the phone
**Expected result:** Messages sent by the KDE Connect desktop app do appear in the conversation in the Signal app on the phone

### Device info

**Device:** Motorola Moto E4 Plus
**Android version:** 7.1.1
**Signal version:** 4.15.5

### Link to debug log

https://gist.github.com/anonymous/5bea9021873b6b4132c661a237c53d86

**Comment by FeuRenard** [comment]
I assume this is a duplicate of #218, #5803, #6089 and probably some others.

**Comment by steelstring94** [comment]
Update:  When you get a notification in KDE Connect that a text message has arrived, you actually get two:  One that seems to be from the KDE Connect app, and one that is from Signal.  Both have a reply option.  If you reply via the KDE Connect notification, the bug described in my original post occurs, but if you reply via Signal, you can see the sent message.

Since Signal does in fact seem to be sending the messages, it seems any problem, if there is one at all, is with KDE Connect, and so I am closing this issue.
