### ISSUE TITLE
Databae update to SQLCipher does not clean up old databases

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7406]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
When a Signal 4.16.x versionis installed over an older version, it updates the database to a SQLCipher database named `signal.db`. However, several old databases like `messages.db` and its journal file (I'm not sure if the others like `whisper_directpry.db` and `canonical_address.db` are still used) remain in the applications databases directory. If the goal is to increase security by storing the key in hardware storage on Android >= 6 it would be better to delete these no longer used files after the upgrade process was succesfull.

### Steps to reproduce
- Install 4.16.x over an older version

**Actual result:** messages.db and messages.db-journal are still there.
**Expected result:** Only `signal.db` is there to store the messages.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.16.4

### Link to debug log
Not required.

**Comment by moxie0** [comment]
This is intentional, they'll get cleaned up later once it's clear all migrations are successful.
