### ISSUE TITLE
Improvement: Don't do sound Notification when active

### ISSUE THREAD

**Issue by baso10** [signalapp/Signal-Android#7408]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I am actively talking to other person I get sound notifications.

### Steps to reproduce
- send multiple messages to other guy while he has conversation open

**Actual result:** I get sound notification for each meassage
**Expected result:** Don't hear anythink

### Device info
**Device:** Samsung
**Android version:** 7
**Signal version:** 4.15.5

**Comment by jeremymasters** [comment]
You can turn these off in the settings area.

**Comment by baso10** [comment]
Yes, but then there is also no sound notification when I am not using the app

**Comment by jeremymasters** [comment]
No.   "in-chat sounds" is what you want to turn off.
