### ISSUE TITLE
Group call feature 

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#7414]
Add group call feature. But I don’t have to be obliged to have created a group I would like to simply call someone and once I am in the call add other people to this call

**Comment by FeuRenard** [comment]
This is a duplicate of #6075.

**Comment by alerque** [comment]
The supposed duplicate of this issue got auto-closed and locked. Can we get one issue that's open tracking progress on this feature?

**Comment by haffenloher** [comment]
Hey @alerque, feature requests are now being tracked in the forums. The thread for group calls is https://community.signalusers.org/t/conference-calls/870.
