### ISSUE TITLE
Network connection seems to get stuck (without Google services)

### ISSUE THREAD

**Issue by Socob** [signalapp/Signal-Android#7420]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
First of all, I apologize if this is the same issue as #6644 or #6880, but it is difficult for me to tell whether the root cause is the same. I am using the official Signal APK from https://signal.org/android/apk/, so **not** Noise or anything like that.

For months now, Signal on Android’s network connection seems to “freeze” sporadically (once or twice per day), leaving it unable to send or receive any messages (even things like read confirmations) for long periods of time. During this time, messages can be sent and received from the Signal desktop client normally and without any delay, but none of these messages show up in the Android client. It does not make a difference whether the Android client is open or any conversations are opened – nothing happens.

It seems that Signal can be made “un-stuck” by resetting the phone’s network connection (e. g. disabling WiFi so that the phone switches to cellular data) or using “force stop” to kill and restart the Signal Android client completely. Upon one of these events, all of the messages from the intervening time period will appear in the Android client all at once.

### Steps to reproduce
Unfortunately, since this seems to happen erratically, concrete steps to reproduce are a bit difficult to determine.
- Use the phone normally (not sure if longer periods of inactivity are required).
- Have someone else send you a message and/or send messages yourself from the Signal desktop client.

**Actual result:** No new messages (sent or received) are displayed in the Signal Android app, even if it is open. This occurs when the phone and the desktop are on the same WiFi network, so the issue is not due to poor connectivity.
**Expected result:** Messages should appear immediately in the Signal Android client.

### Device info
**Device:** OnePlus One
**Android version:** 7.1.2 (LineageOS 14.1). I have never had Google Play services installed and Android Doze is disabled (“Battery optimization: Not optimized”) for Signal.
**Signal version:** 4.15.5 (but I’ve been having this issue for months now, so includes many earlier versions)

### Link to debug log
https://gist.github.com/anonymous/b1f29ef755a08091528fefff299057d9

At 15:25, my phone switched to cellular data (because I went out of WiFi range). At that point, all the messages from the last hour or so appeared all at once.

**Comment by timotk** [comment]
Based on your description it seems to be the same as #6447, #6644 and #6880.

A proposed fix is https://github.com/signalapp/libsignal-service-java/pull/49, but this does not appear to work for everyone, see https://github.com/signalapp/Signal-Android/issues/6732#issuecomment-363451778

**Comment by razzor1984** [comment]
In my case its basicaly the same(Signal 4.15.5 - Linage14.1//7.1.2 - Doze is disabled for Signal) but worse.
I get my messages hours later, the only workaround ist to switch to airplane mode and then turn it off.
So im able to get my messages.

**Comment by Nesaijn** [comment]
I have the same problem, but I would say that Signal, at least in my case, seems to have no internet connection. In case of sending and receiving messages I don't have any problems outside of my home network. With mobile data or another WiFi connection I have no problems. I also tried to reinstall it and also checked app permissions.

Signal 4.16.9
Android-Version 5.1.1
Medion S5004

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
