### ISSUE TITLE
Wrong app opening/closing after sharing a file or message

### ISSUE THREAD

**Issue by RobertTEG** [signalapp/Signal-Android#7424]
### Bug description
After sharing a file or message with a contact inside the app and closing it, it closes from the recent list and returns to the home screen. When reopening it and going back, it gets to the main menu and back to the last conversation where the file was sent.

### Steps to reproduce
- share a file or message with a contact
- go back
- reopen Signal
- try go back

**Actual result:** First, it shouldn't autoremove from the recents and should redirect to the last app opened. Second, Signal will redirect to the last conversation where the file was shared with when reopened.
**Expected result:** After sending the file, it should return to the last app and not autoremove from the recents list. And when reopening Signal and going back to home screen it shouldn't show your last conversation where the file was sent.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.16.5

### Link to debug log
https://gist.github.com/a1f8d377cce47400ec4923f9991ddae0

**Comment by FeuRenard** [comment]
Sounds related to #7312
