### ISSUE TITLE
Other party cannot see my video when I call them. When they call me, everything works fine.

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7425]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Very frequently (80-85% of the time), when I make a video call the other person cannot see my video (I can see their video). Whenever they call me, video works perfectly.

### Steps to reproduce
- make call

**Actual result:** they cannot see my video
**Expected result:** they should see my video

### Device info

**Device:** Moto G4 Plus
**Android version:** 7.0.0
**Signal version:** 4.16.5

### Link to debug log
https://gist.github.com/anonymous/465239779849914eefce4be6bb204743
In this log, there should be 3 calls:
1. Contact calls me: everything was fine and I hang up.
2. I call them back: they can't see my video. I can see their video. I can also see my video in the thumbnail thing. I hang up.
3. Contact calls me: everything works perfectly

**Comment by PiCob** [comment]
Do you think you could also get and provide the log from the other party's device? That information might be useful (if not even necessary). Moreover, the other party's device, Android/iOS version and Signal version could help analyzing the problem.

**Comment by dcherian** [comment]
Contact is on iOS. I've asked them to submit a debug log via email and refer to this issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
