### ISSUE TITLE
Sent images are downsized beyond legibility, but the recipient sees the full resolution

### ISSUE THREAD

**Issue by leafcutterant** [signalapp/Signal-Android#7426]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- take photo with phone camera
- send it to recipient (doesn't matter if it's via the Gallery or File mode)
- check after sending if the image looks right: from the default chat view, it looks okay and sharp for me, I can even read some of the text in it
- I open it freak out because it's been downsized beyond the text being legible (if I save the image, both the X and Y pixel sizes are the 1/10ths of the original image's size)
- recipient tells me it looks fine for them, only my Signal is unable to show the proper image

**Actual result:** I see a vastly inferior,  almost unusable picture if I open the image
**Expected result:** It should have the same size pixel-wise

### Device info
**Android version:** 5.1.1
**Signal version:** 4.15.5

**Recipient's phone:** iPhone iOS, n/a version
**Recipient's Signal version:** n/a (presumably up-to-date at the time of writing)

**Comment by Dyras** [comment]
Any chance you could check side by side with someone to see if it's not just your definition of "small" that differs with his/hers?

**Comment by leafcutterant** [comment]
It's not that much of a subjective definition. The sent photo was ~ 1700 * 3100 px, while the version that's displayed when I click on the message or save the image from Signal is ~ 220 * 380 px. That's small, to say the least.

**Comment by 2-4601** [comment]
Related #672

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
