### ISSUE TITLE
Missing Messages in Group Chat

### ISSUE THREAD

**Issue by p0wl90** [signalapp/Signal-Android#7429]
Hey!
I was asked to open this bug by @scottnonnenberg here: https://github.com/signalapp/Signal-Desktop/issues/1913#issuecomment-367084599
While using the desktop client, messages of a friend (in a group chat) were not displayed on my phone but only on the desktop.
I realized this because he told me, all messages me and some others wrote today were only visible on his phone but not in the desktop client.
I run Android 8.1.0 with the Februar 5 security patch on a Nexus 5X.
If you need any additional information, just tell me. I'm afraid I can't really tell you the steps to reproduce.
Logs and Screens below:

Desktop Log: https://gist.github.com/anonymous/0f0e1f838b9c959bdf6bf4b2ece34b09
Android Log: https://gist.github.com/p0wl90/3542fa031df85094a25c1a9aaaf71ed2

Screenshots have the timestamps paintskilled into them: 
![1](https://user-images.githubusercontent.com/6959020/36495165-b55c999c-1734-11e8-85e7-d9bff73ec647.PNG)
![2](https://user-images.githubusercontent.com/6959020/36495166-b57fc1ec-1734-11e8-955e-857e49db2f4d.png)

**Comment by chynric** [comment]
Hey,
also for me some messages in a group conversation were received by Signal Desktop only. I am using two different unrelated Signal accounts (each with different phone numbers). Both accounts participate in the same group. 
One account is linked with Signal Desktop and is used only by that (phone client currently not in use). This account received all messages.
The second account is not linked with any Desktop client (phone only) and missed 9 messages.
The sender of the messages could confirm, that the never received messages to the second account only got one check mark.

Signale Desktop: v1.3.0 -  received all messages
Signale Android: 4.16.6 Beta - missed 9 messages

Timestamps of missed messages (taken from Signal Desktop):

- Sent 22. Februar 2018 20:33
Rece 23. Februar 2018 14:50
- Sent 22. Februar 2018 20:34
Rece 23. Februar 2018 14:50
- Sent 22. Februar 2018 20:34
Rece 23. Februar 2018 14:50
- Sent  22. Februar 2018 20:34
Rece  23. Februar 2018 14:50
- Sent 22. Februar 2018 20:34
Rece 23. Februar 2018 14:50
- Sent 22. Februar 2018 20:35
Rece 23. Februar 2018 14:50
- Sent 22. Februar 2018 20:35
Rece 23. Februar 2018 14:50
- Sent 22. Februar 2018 20:35
Rece 23. Februar 2018 14:50

**Comment by chynric** [comment]
## Bug description - Update
It happened a second time that some group messages were not received from one group member (see previouse post: second account). All affected messages were sent by the same participant.
Though there are messages sent before and after the incident which were delivered completly.  

### Timestamps (GMT+8)
Timestamps of missed messages (taken from Signal Desktop):

- Sent 24. Februar 2018 03:19
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:20
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:54
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:54
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:55
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:55
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:55
Rece 26. Februar 2018 15:02
- Sent 24. Februar 2018 03:56
Rece 26. Februar 2018 15:02

### Steps to reproduce
- seems to happen randomly 

**Actual result:** Some group messages not received from one groupe member/android app
**Expected result:** All messages delviered and received reliable by all group memebers

## Device info
**Device:** HTC U11 Life
**Android version:** 8.0
**Signal version:** 4.16.7

## Link to debug log
Unfortunately the log is not dating back long enough to cover the time of last missing messages.
https://hastebin.com/ideqududaz

**Comment by chynric** [comment]
## Provisional fix
The bug could be narrowed down to one specific Signal Desktop instance. Messages from this account were normaly received if sending with Signal Android app, but always got undelivered to one of the groups member if sending with it's Desktop counterpart.
Following steps resolved to problem so far:
- affected group member left the group and was readded
- the sending Signal Desktop instance was updated from Version 1.3 to 1.5 

However the real cause of the bug could not be determined.

### Debug log 
Following the log just after some messages were not received:

- **Sending** Signal Desktop (1.3)
https://hastebin.com/vaguberoha
- **Not receiving** Signal Android
https://hastebin.com/ezunureted

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
