### ISSUE TITLE
Allow for the citation of web-pages, blog posts, and on-line articles.

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#7432]
This ticket is early, as it depents on the implementation of two other features. Never the less, this is a valid feature request and by starting it now it is clear which discussion belongs where.

Dependand on:
- Implementation of a custom URL sceme, #7310
- Implementation of a quotation system, as quoating webpages will partly depent on the same code used to implement quotation of previous messages. #6017
- Implementation of a weblink preview #5724

For those familliar with whatsapp of twitter, web-sites (most notably blogs and news-sites) have share buttons, which lead to an automatic quotation in a social media post or message. By adding meta data on the web-page, the social media application can show a preview image and a header of the shared article. It can in some cases also reference persons, places, or moments in time.

**The proposed feature:**
Add functionality to cite webpages, on-line articles, or blog posts.

Once it is possible open urls with signal (7310) and display citations (6017);
1. a.   Allow for messages to contain a preview image of the cited article or webpage, based on meta-data provided on that web-page.
    b.  Allow for preview images to be clickable, bringing the user to the referenced URL.
    c.  If the message contains multiple URL's, it must be visually clear which one the preview belongs to.
2. Allow for messages to contain a header/title of the referenced article, based on metadata.
3. a.  Allow for messages to contain an URL to the cited webpage.
    b.  Due to the importance of privacy, preferably do not shorten the URL, like some other apps do. Instead allow the user to see where the link takes him before cliking it.
5. Locations or moments in time may be useful to a calander function. This is currently of no use in Signal Private messenger, but should be kept in mind if future versions do have use for such meta-data.
6. Provide documentation for web-developers on the desired file-size, aspect-ratio and minimum resolution of preview images, the acceptable length of header or titels, and the manner in which meta-data must be provided. Signal does not need to be as strickt on this as a platform such as Twitter is, but it is best practice to be clear on this right from the start,, as Signal may be used in a professional environment in the future. Especially with meta-data, the rules and recommandations should be clear from day one.

I have deliberatly split these out so each detail can be easily discussed. It wouldn't be practical to split them all into seperate tickets as they are details to the same functionality.

Fetching information from web locations will obviously need to be done very carefully, as it brings in numerous privacy concerns.
Where a privacy friendly solution cannot be found, certain features could be optional, with a clear warning that it cannot be used without privacy concerns. Hopefull we can find solutions and wont have to make anything optional or leave anything out.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
