### ISSUE TITLE
Ability to include video fragments in messages

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#7434]
For a distant future, it will likely be a useful/wanted feature for a messaging app to be able to play videos directly in the messages. Much like twitter does on its timeline. The video may be limited to a certain length, say, 30 seconds, if this is required to overcome technical limitations.

The key difference which file sharing, is that video's will have a preview in the message, and are directly playable within the conversation.

Including the ability to pause, mute, or select a time index.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
