### ISSUE TITLE
Optional ability to confirm "have read"

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#7435]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

not following rest of template as this is a global feature request not a device specific bug report
----------------------------------------
Whatsapp has a tick system. One tick means the message has not yet been received. Two ticks means it has been received. Two blue ticks means the message was also displayed on screen (and likely read).

For obvious reasons, Signal Private Messenger does not have the blue ticks.
However, I think it should have, and it wont have to violate privacy.

I message my father on signal sometimes. But he falls asleep on the couch rather often. So when I text him that I will be at the station and need a lift at 00:24 in the night, the fact that he received the message doesn't really help me. I need to ask him to confirm he read it.

**The proposed feature:**
So there is a missing feature. Lets add it.
However, to preserve the privacy aware nature of Signal Private Messenger, it will have to work as follows:
- A user has to manually and deliberatly turn on the confirmations. (via a slider in the settings of the conversation "send have read confirmations")
- By default, confirmations are off.
- It is not nessessary for both sides to turn on the confirmations, but only the side which did turn them on, will send them.
- The sender will also see a visual cue on his own messages, reminding him he is sending out confirmations.
- The other side can receive the confirmations regardless of his own setting. There is no peer pressure.
- For each conversation (with a group or a person) the setting has to be toggled individually.
- There is deliberatly no global setting, as we don't want new conversations to have this setting on by default.

**Comment by p4nci** [comment]
@Meteor0id please don't delete the template when opening new issues.
 The read receipts are implemented since Signal v4.11.x (see https://github.com/signalapp/Signal-Android/commit/cb9bc9659b5926ea6777524fd7fd0fbd67f57b8e and [Signal blog](https://signal.org/blog/read-receipts/))
From Signal blog:

> Our implementation of read receipts is simple. There is only one setting. Both sides must have the feature enabled in order to see each other’s receipts.

> ... They will be enabled when users install Signal, but the feature is disabled by default for existing installations.

please check if both of you have read receipts enabled, otherwise it's probably a bug and you should provide a debug log for this.

**Comment by Meteor0id** [comment]
My apologies, I have missed the changelog and issue report when this feature was added. There is likely no reason to call this a bug. However, **I would like to keep this ticket open as a suggestion to change the feature, on the following counts:**

- For each conversation (with a group or a person) the setting CAN to be toggled individually. This could be a three state slider. 1. On for this conversation, 2. inherit from global setting, 3. off for this conversation.
- It is not nessessary for both sides to turn on the confirmations, but only the side which did turn them on, will send them.
-The other side can receive the confirmations regardless of his own setting. There is no peer pressure.

The reason I suggest these changes is because they are more faithful to the free and open nature of Signal Private Messenger in my opinion.
**The key here is having the freedom to treat my contacts in different manners**, however I chose. I might want to give receipts to my girlfriend, letting her know I read the grosseries list, but I dont want to also do that with my buisness partner, who tends to continue work conversations after buisness hours. (I made that up, I love working after buisness hours ;) )

I could reopen this as a seperate feature request if you prefer.

**Comment by Meteor0id** [comment]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by FeuRenard** [comment]
Related to #7047.

**Comment by Meteor0id** [comment]
I ksee this is in fact a duplicate of #7047, it was phrased differently (overwrite) which caused my to miss it when looking for existing tickets. Continuing these ideas at #7047 .
