### ISSUE TITLE
Read receipts not working for both parties of one conversation

### ISSUE THREAD

**Issue by cdenyar** [signalapp/Signal-Android#7436]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Read receipts not working for both parties of one conversation

### Steps to reproduce
- Confirm both devices have read receipts enabled
- send message from android client to affected user who is also on android
- Delivery receipt comes in, never turns blue

**Actual result:** Double gray/white delivery check mark doesn't turn blue after being read
**Expected result:** After reading a message, the check marks should turn blue

### Screenshots
![image](https://user-images.githubusercontent.com/6653063/36600104-6413b68c-187f-11e8-8991-efa105ea6afa.png)

### Device info
**Device:** Pixel 2 XL
**Android version:** 8.1.0
**Signal version:** 4.16.5

### Link to debug log
Device A: https://gist.github.com/d86f0d61f8a10eaf723766ebe605f62b
Device B: https://gist.github.com/anonymous/c299513b8665928cece96561aba0f997

**Comment by cdenyar** [comment]
This may be related to the desktop client.  Both parties are using the desktop client on OSX and had no issues with read receipts over the weekend but they're not working again today while we're both in the office and signed in with the desktop client.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
