### ISSUE TITLE
Latest beta: Signal can no longer play (most) video attachments

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#7438]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On my Moto G4, I can no longer play most video attachments. I can click them and the media player appears but nothing happens from there.

Ordinarily I would blame this piece of shit phone, but my friend has a Nexus 6P and she has the same issue.

### Steps to reproduce
1. Send a video that is .mp4, .webm or .mpeg from Signal-Android or Signal-Desktop, it doesn't make a difference. Here are three videos you can try it with: https://u.teknik.io/IIrt3.zip
The video with the cat in the box was sent to me as a .mpeg but I changed it to .mp4, but it doesn't make a difference.
**I can't even watch videos recorded on my own phone!** However, the thumbnail still shows in the chat so... That's something?
2. Wait for the video to download onto Signal-Android or wait for it to send
3. Click the video
4. The video is forever black.

**Actual result:** Most, but not all videos, fail to play
**Expected result:** Almost every video should play flawlessly, I first noticed the issue just now after it came back from repairs (took 2 weeks) but my Nexus buddy says it's longer than that.

### Device info
Moto G4 with 7.0.1, Signal 4.16.6.
Nexus 6P with 8.1.0, Signal 4.16.6.

### Link to debug log
Nexus 6P: https://gist.github.com/anonymous/d465bd4c2e57a2491229be1b100a3a02
Moto G4: https://gist.github.com/anonymous/27d5a88b4c488ee54e48d6a0212871d1

**Comment by moxie0** [comment]
Bengal!
