### ISSUE TITLE
Better contrast encrypted vs. unencrypted messaging

### ISSUE THREAD

**Issue by GammaSQ** [signalapp/Signal-Android#7439]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Problem Description
I used Conversations and Silence before, both having an obvious visual cue weather messages are encrypted or not: Both use a lock at the upper right corner, locked or unlocked, to show weather the next message will be encrypted.
Furthermore, Conversations colors every previous plaintext message red. I've noticed Signal colors messages from non-signal-users grey. However, they get colored once they join Signal. The lock at the message bottom isn't visually obvious enough in my personal opinion.

Although Signal displays "Noise message" or "Unsecured SMS", that note vanishes the moment a message is typed, which removes any easy visual cue weather the message will be sent encrypted or plaintext.

### Feature Request
- A persistent visual cue weather the next message will be encrypted (e.g. open or closed lock symbol)
- I suggest a better visual cue weather a previous message was encrypted (e.g. highlighting the existing lock-symbol in red)

**Comment by haffenloher** [comment]
> A persistent visual cue weather the next message will be encrypted (e.g. open or closed lock symbol)

The send button changes in color and displays an open or closed lock depending on whether you're about to send an SMS or a Signal message.

**Comment by Dyras** [comment]
In the dark theme, the lock is barely visible for me if that's what the OP is using

**Comment by moxie0** [comment]
I don't know what a "Noise message" is. It sounds like you're running a different application.

**Comment by Dyras** [comment]
@moxie0 I think he's using the CopperheadOS fork of Signal, Noise.

**Comment by GammaSQ** [comment]
To my embarrassment, I have to admit to simply have overlooked the changing send-icon.
Yes, I am using Signal on CopperheadOS, where it's called Noise because ... I guess licensing issues, but it definitely is just Signal repackaged.

This issue can be closed, though I would still leave the recommendation to handle the highlighting differently. I opened this issue only after finding others having similar problems:
https://github.com/signalapp/Signal-Android/issues/4390
