### ISSUE TITLE
There is a new logo propose for your project

### ISSUE THREAD

**Issue by jackingpanda** [signalapp/Signal-Android#7440]
Hello, I've been making logo for open source project since 2017. This is my logo proposal for your project, the making of this logo are funded and supported by [Utopian.io](https://utopian.io/) by using blockchain system. Feel free to use it, thanks!
https://utopian.io/utopian-io/@dimensco/new-logo-propose-for-signal-private-messenger

![1](https://user-images.githubusercontent.com/20648882/36652509-b04f106e-1ae1-11e8-8c63-ec980d6aa3a5.png)

**Comment by moxie0** [comment]
Thanks @jackingpanda but we try not to use GH issues for discussion, please check out the forums if you'd like to discuss or propose things. Thanks!
