### ISSUE TITLE
Notifications Not Received Until Signal Unlocked

### ISSUE THREAD

**Issue by whispy** [signalapp/Signal-Android#7444]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a message is received, notifications (audio, visual, or vibratory) are not fired until Signal is opened and manually unlocked. There is no way for one to know if one has received a new message until one unlocks the database.

Notifications are displayed _incorrectly_ in 4.16.8 (and, I think, 4.16.7). They are shown _correctly_ in 4.15.5.

### Steps to reproduce
- Be on at least 4.16.8 (think it also happens on 4.16.7)
- Lock database
- Receive a message

**Actual result:** 
No notification is received.

**Expected result:**
Notification would be received and displayed encrypted, without having to unlock database.

### Device info

**Device:** Pixel XL
**Android version:** 8.1.0
**Signal version:** See above.

### Link to debug log
https://hastebin.com/ecokuhijij

**Comment by tracerTres** [comment]
I am also experiencing this on version 4.16.8.
Device: samsung SM-j5
Android: 6.0.1

**Comment by minnmann** [comment]
I am unable to reproduce this issue. Notifications (audio, visual and vibratory) are fired correctly for me.

**Device:** Motorola Moto G5
**Android version:** 7.0
**Signal version:** 4.16.8

**Comment by jeremymasters** [comment]
I have a friend with an S8 that is experiencing this repeatedly.  Doesn't use it as his default SMS messenger.

**Comment by lanarchy** [comment]
Same issue here.
4.16.8 as well as 4.16.7

**Comment by moxie0** [comment]
TIL people use the signal screen lock

**Comment by whispy** [comment]
Isn't that the intended behavior in order to encrypt the database when not in use?

**Comment by RichJeanes** [comment]
@moxie0 Perhaps this realization means that we can get a proper patch for #3990 instead of just the workaround provided by #5805?

**Comment by wnhre2ur8cxx8** [comment]
> TIL people use the signal screen lock

The screen lock actually helped people I know of protecting their data from police searches. The police arrested them in public transport right after they saw that the phone was unlocked. They really waited for this exact moment before doing so. So another unlock for signal was a well enough protection in this scenario. Just wanted you to know @moxie0

I know you are upset and annoyed with the "open source guys" - And I can relate to that. But please dont shame and belittle the need for safety features of the politically persecuted :/
