### ISSUE TITLE
Unable to restore new encrypted backup  (4.17 branch)

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7446]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I built 4.17 from source, installed it on a device as an upgrade of 4.16.7 and made an encrypted backup. Then, I tested 2 scenarios:

1. Go to settings, Apps, Signal and remove all data
2. Remove Signal en reinstall it (I did this to be sure the Android keystore was wiped too to test this).

After both I selected restore backup on the homescreen but in both scenarios I get an invalid password error:

**Actual result:** I get an invalid password error and get asked again to register or restore a backup
**Expected result:** It should restore the backup and show either a enter password screen or a conversation list (I don't know if it saves my app password, hev to check the source more thorough).

### Screenshots
The password I was given:
![password](https://user-images.githubusercontent.com/8427572/36796616-d9560ee6-1c9d-11e8-8440-99e7f5f2ee03.JPG)
Input of the password (first screen, pwd is longer than my screenwidth):
![enter_password1](https://user-images.githubusercontent.com/8427572/36796619-dbb5a1ec-1c9d-11e8-91ad-652ffc629e2e.jpg)
Second part:
![enter_password2](https://user-images.githubusercontent.com/8427572/36796622-dde0c5dc-1c9d-11e8-95fd-815b0f5cd5e5.jpg)
Error:
![incorrect_password](https://user-images.githubusercontent.com/8427572/36796629-dfdff4fc-1c9d-11e8-8263-6fd728c694f5.jpg)

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.17.0 (at commit https://github.com/signalapp/Signal-Android/commit/332ccbb4eb480221c93baf259a1d307560390747).

### Link to debug log
I could not enter the app so I made a logcat output. I think this is the relevant part, if you need more please tell:
```
02-28 16:28:16.829 W/RegistrationActivity(17793): java.io.IOException: Bad MAC
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:225)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:167)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:63)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:352)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:344)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-28 16:28:16.829 W/RegistrationActivity(17793): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by moxie0** [comment]
I can't reproduce this. Looks to me like the password doesn't match, are you sure you're trying to restore a backup that corresponds to that password, and not a previously generated one?

**Comment by johanw666** [comment]
I set it up (restore a TB 4.15 backup and let that one go through a database upgrade), when 4.17 starts I do a backup, make the screenshot from the password, remove the data and try to restore it. I'll do some more testing tomorrow and if I still don't get it to work I'll add some extra logging.

Anyway, entering the password from left to right, top to bottom is the correct way (just to make sure)?

**Comment by moxie0** [comment]
Yeah left to right top to bottom

**Comment by p4nci** [comment]
> entering the password from left to right, top to bottom is the correct way (just to make sure)?

I was first also confused, although `left to right top to bottom` is common

@moxie0 why not "helping" users with hyphens similar to registration screen:

![signal-reg -screen](https://user-images.githubusercontent.com/16047081/36895039-b5b0fe9e-1e0d-11e8-8120-c1ab899daecf.png)

imo, this is clearer and should not confuse users how to read/enter (which direction) the passphrase

**Comment by johanw666** [comment]
I've added some logging to Signal and it gives an exception on this line in FullBackupImporter.java, in function importfile():
```java
while (!(frame = inputStream.readFrame()).getEnd()) {
```
I've added this logging:
```java
  public static void importFile(@NonNull Context context, @NonNull AttachmentSecret attachmentSecret,
                                @NonNull SQLiteDatabase db, @NonNull File file, @NonNull String passphrase)
      throws IOException
  {
    Log.i(TAG, "importFile: passphrase = " + passphrase);
    byte[]                  key         = getBackupKey(passphrase);
    BackupRecordInputStream inputStream = new BackupRecordInputStream(file, key);
    int                     count       = 0;

    try {
      db.beginTransaction();

      BackupFrame frame;

      Log.i(TAG, "importFile: reading frames");
      while (!(frame = inputStream.readFrame()).getEnd()) {
        Log.i(TAG, "importFile: reading new frame");
        if (count++ % 100 == 0) EventBus.getDefault().post(new BackupEvent(BackupEvent.Type.PROGRESS, count));

        if      (frame.hasVersion())    { processVersion(db, frame.getVersion()); Log.i(TAG, "importFile: Frame has version"); }
        else if (frame.hasStatement())  { processStatement(db, frame.getStatement()); Log.i(TAG, "importFile: Frame has statement"); }
        else if (frame.hasPreference()) { processPreference(context, frame.getPreference()); Log.i(TAG, "importFile: Frame has preference"); }
        else if (frame.hasAttachment()) { processAttachment(context, attachmentSecret, db, frame.getAttachment(), inputStream); Log.i(TAG, "importFile: Frame has attachment"); }
      }
      Log.i(TAG, "importFile: finished processing frames");
      db.setTransactionSuccessful();
    } finally {
      db.endTransaction();
    }
    Log.i(TAG, "importFile: finished");
    EventBus.getDefault().post(new BackupEvent(BackupEvent.Type.FINISHED, count));
  }
```
And I see this output in the system log (another key as above because I've made a new backup in the meantime).
```
03-02 18:37:13.092 I/RegistrationActivity(4625): doInBackground: Restore password entered: 356179817818336692720166534001
03-02 18:37:13.098 D/audio_hw_extn(591): audio_extn_get_anc_enabled: anc_enabled:0
03-02 18:37:13.108 I/HK/LatinKbdBaseView(5121): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{dd32751 V.ED..... ......I. 0,0-720,412 #7f07000a app:id/LatinkeyboardBaseView}
03-02 18:37:13.110 I/FullBackupImporter(4625): importFile: passphrase = 356179817818336692720166534001
03-02 18:37:13.110 I/FullBackupBase(4625):  getBackupKey: passphrase = 356179817818336692720166534001
03-02 18:37:13.114 I/HK/LatinKbdBaseView(5121): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{dd32751 V.ED..... ......ID 0,0-720,412 #7f07000a app:id/LatinkeyboardBaseView}
03-02 18:37:13.120 I/HK/LatinKbdBaseView(5121): onMeasure width=720
03-02 18:37:13.120 I/HK/LatinKbdBaseView(5121): onMeasure width=720
03-02 18:37:13.121 I/Keyboard(5121): setKeyboardWidth newWidth=720, mTotalWidth=720
03-02 18:37:15.748 I/Gobi    (657): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
03-02 18:37:15.748 I/Gobi    (657): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1550: Failed to get TransState, rc 9
03-02 18:37:15.748 I/Gobi    (657): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
03-02 18:37:15.748 I/Gobi    (657): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
03-02 18:37:16.243 D/audio_hw_primary(591): out_standby: enter: stream (0xb5b77380) usecase(1: low-latency-playback)
03-02 18:37:16.244 D/hardware_info(591): hw_info_append_hw_type : device_name = speaker
03-02 18:37:16.357 W/audio_hw_primary(591): disable_snd_device: device ref cnt is already 0
03-02 18:37:16.357 D/audio_hw_extn(591): audio_extn_get_anc_enabled: anc_enabled:0
03-02 18:37:16.458 I/art     (4625): Background sticky concurrent mark sweep GC freed 56379(4MB) AllocSpace objects, 0(0B) LOS objects, 21% free, 14MB/17MB, paused 1.798ms total 110.567ms
03-02 18:37:17.528 I/tad     (198): MiscTA Unit 66670: 
03-02 18:37:17.528 I/tad     (198): NOT WRITTEN (Identical)
03-02 18:37:17.528 I/tad     (198): MiscTA: Write of unit 66670 completed - OK
03-02 18:37:20.848 W/System.err(6831): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.concurrent.atomic.AtomicInteger.get()' on a null object reference
03-02 18:37:20.850 W/System.err(6831): 	at com.mobpower.a.g.a.a.a(:262)
03-02 18:37:20.850 W/System.err(6831): 	at com.mobpower.probe.e.a(:68)
03-02 18:37:20.850 W/System.err(6831): 	at com.mobpower.probe.PowerService.a(:1059)
03-02 18:37:20.850 W/System.err(6831): 	at com.mobpower.probe.PowerService$1.handleMessage(:83)
03-02 18:37:20.850 W/System.err(6831): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-02 18:37:20.850 W/System.err(6831): 	at android.os.Looper.loop(Looper.java:234)
03-02 18:37:20.850 W/System.err(6831): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
03-02 18:37:20.850 W/System.err(6831): 	at java.lang.reflect.Method.invoke(Native Method)
03-02 18:37:20.850 W/System.err(6831): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-02 18:37:20.850 W/System.err(6831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-02 18:37:20.850 W/System.err(6831): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
03-02 18:37:20.851 D/MobPowerReceiverDelegate(6831): onReceive() called with: com.mobpower.sdk.probe
03-02 18:37:21.892 W/FullBackupBase(4625): Generated: 8746
03-02 18:37:21.928 I/FullBackupImporter(4625): importFile: reading frames
03-02 18:37:21.933 W/RegistrationActivity(4625): java.io.IOException: Bad MAC
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:229)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:171)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:66)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:354)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:345)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-02 18:37:21.933 W/RegistrationActivity(4625): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by johanw666** [comment]
I can try to make a minimal backup without any sensitive messages and mail it to you together with the used key if you like.

**Comment by shikka** [comment]
Maybe it helps: 
https://github.com/signalapp/Signal-Android/commit/332ccbb4eb480221c93baf259a1d307560390747#r27893524

**Comment by johanw666** [comment]
I tried with the new official 4.17.0 but got the same result:

- Uninstall existing Signal
- Remove existing old backups
- Install Signal 4.17.0 (official Playstore apk)
- Restore TB with 4.15.5 backup
- Start Signal 4.17, it converts the data. Conversations look OK.
- Create new backup format
- Remove all Signal data from settings - apps
- Start Signal, it asks to import a backup
- Enter password
- Get incorrect passphrase toast

I made a minimal backup file and screenshot and put them online here: https://mega.nz/#F!xUxCVDoR!5vlELGHLqBSfxqM0WRp8zA

**Comment by moxie0** [comment]
@johanw666 According to your log, the password you're entering is incorrect for the backup you're trying to restore. It's hard for me to work with these logs, though, since you're running a custom build with custom changes, and have used TB. I can't reproduce, and am waiting to see if it comes up for anyone running stock.

**Comment by johanw666** [comment]
The test backup I placed on Mega was made by the apk you uploaded to Google, I wanted to make sure it was not an issue with my build environment but the official apk behaves the same.

**Comment by moxie0** [comment]
Did you use TiBackup or some other weird rooted shit with it, or install it on a stock device fresh?

**Comment by johanw666** [comment]
I restored the backup with Titanium Backup so the device was rooted. That was a backup of a 4.15.5 database, which was then converted by Signal to 4.17 format. That all went OK.

**Comment by p4nci** [comment]
@johanw666 

> Install Signal 4.17.0 (official Playstore apk)
Restore TB with 4.15.5 backup
Start Signal 4.17, it converts the data. Conversations look OK.

you can try this:
a) installing Signal v4.15.5
b) Restore backup (v4.15.5) with TB
c) Start Signal v4.15.5 with all inconveniences (de-register, re-register, ...)
d) testing with send/receive a massage AND THEN
e) update to Signal v4.17.x
....

**Comment by johanw666** [comment]
I might prepare for that. Currently my test device was always in offline mode to prevent messing up my existing installations. But now I have to switch phones anyway, my main device has a broken GPS and fixing costs more than the same device does refurbished. Fortunately my own export / import routines still work.

**Comment by ErikBAndersen** [comment]
I see the same thing.  I installed the new 4.17.1 beta on my old phone and on my new phone.

On my old phone, I used the new 4.17.1 beta to create a backup, saving the password as as a note.  I then copied the backup to my google drive.

Switching to my new phone, I downloaded the backup file and placed it under storage/Signal/Backups/ so signal could find it.  I did a "Clear Data", then started signal.  It found the backup and offered to restore it.  I entered the password, after which signal crashed.

**Comment by johanw666** [comment]
@ErikBAndersen That seems to be a different issue than mine, I didn't have any crash but Signal didn't accept the password (it just keeps saying bad password).

I'll get a new simcard today for testing and try to backup / restore a completely fresh setup. If that works at least I know it is some history isue again.

**Comment by johanw666** [comment]
OK, I got a new simcard and made a clean setup (device is the same Sony Z3 Compact I described above):

1. Uninstall Signal from phone.
2. Install official Play Store apk 4.17.1
3. Register Signal
4. Start Signal and exchange a few testmessages with another Signal setup.
5. Make Signal backup, store screenshot of key
6. Go to Settings, apps, Signal and remove all data from Signal OR uninstall Signal
7. Either reinstall Signal if removed, or start Signal, import backup
8 Get the same Bad MAC error. I placed the entire logfile, backup and a screenshot of the password at https://mega.nz/#F!xUxCVDoR!5vlELGHLqBSfxqM0WRp8zA . I only edited out 2 phonenumbers in the logfiles, replaced the contents with xxxx.
```
03-11 16:42:16.945 W/RegistrationActivity(8985): java.io.IOException: Bad MAC
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:226)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:167)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:63)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:360)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-11 16:42:16.945 W/RegistrationActivity(8985): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ErikBAndersen** [comment]
I installed the new 4.17.3 beta on my phones, and I was able to get the export/import process to work and I now have all the messages and pictures from my old phone on my new phone.  So as far as I can tell, this now works as expected.

**Comment by kaimast** [comment]
I have encountered the same problem when moving from a Phone running Android 6 to one that uses Android 8.
Not sure what the root of the problem could be but I'm willing to debug it.

**Comment by haffenloher** [comment]
@kaimast are you sure it's the same problem? Do you have a log of the issue?

**Comment by srchulo** [comment]
I am unable to even get into the restore flow. I'm on 4.17.5.

**Comment by haffenloher** [comment]
@srchulo That sounds unrelated & is probably a support issue. To see the restore flow before registration, the backup file has to be in the Signal/Backups folder. If you need help, don't hesitate to contact support or check out the [forums](https://whispersystems.discoursehosting.net/).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
