### ISSUE TITLE
Some contact names do not display, some do

### ISSUE THREAD

**Issue by fallenpegasus** [signalapp/Signal-Android#7452]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some of my Signal contacts now only display as their phone number.

Most still display correctly as their name and picture.   I have checked their Google Contact entry and Android contact entry, their phone numbers are in correct +countrycode format.  They used to work.  I've followed the steps about removing contacts without names, and doing "Refresh" in Signal.

However, they do show up with their names in the Signal Desktop Chrome app.

Other bugs about "contacts dont display" seem to be about ALL contacts not displaying.  This is only some.

### Steps to reproduce
- look at existing conversation with known contact
- see number, not name
- search for that number in Google contacts on web, find the entry
- search for that number in Google contacts on Android, find the entry
- go into the Signal conversation, tap on the bar on the top with the contacts phone number
- see it expand to unset user icon, shared media, and chat settings
- tap around, does not go to Android contacts app

**Actual result:  I should see the contacts name and picture from the contacts database.

**Expected result:** No name, no picture

### Device info

**Device:** Nexus 6
**Android version:** 7.0
**Signal version:** 4.16.9

**Comment by p4nci** [comment]
As workaround you can try this:
[WhisperSystems#4338 (comment)](https://github.com/signalapp/Signal-Android/issues/4338#issuecomment-198157982)

**Comment by fallenpegasus** [comment]
I tried that, it doesn't work

**Comment by p4nci** [comment]
@fallenpegasus could you please check if you are from [this bug](https://github.com/signalapp/Signal-Android/issues/7394) affected i.e. you have contacts with really long display names or a lot of (Signal) contacts.
Anyway, providing debug logs is always helpful.

**Comment by moxie0** [comment]
I'm unable to reproduce this issue. In order to fix it, I would need some information on how to create the issue you're experiencing, or access to some data about your issue. Please reopen if you can provide steps to reproduce from a clean install, thanks!

**Comment by PatrickHonorez** [comment]
I have the same issue: many contacts that appear in the contacts list and in the default SMS app (Messages on Pixel 3) do NOT appear in Signal. It seems that only numbers starting with **+** and containing no special characters like **(**,  **)** or **-**  appear in Signal.
For these contacts I can still open them in the phone app or contact app and press SMS button. Bit no way from Signal.

**Comment by greyson-signal** [comment]
@PatrickHonorez Can you do the following?

1. If these are non-Signal contacts, verify that SMS is enabled: `Home screen > three-dot menu > Settings > SMS and MMS`
1. Click the 'new conversation' button (the pencil in the bottom right of the home screen)
2. Pull-to-refresh
3. If you contacts aren't appearing, go to `Home screen > three-dot menu > Settings > Advanced > Submit debug log` and post the link you get here. Thanks!

**Comment by PatrickHonorez** [comment]
Thanks. Here is the report:

https://debuglogs.org/6d0824b1897b45435ad74b67e5eedbcc96065126330629688ea493457cab4b85

Patrick

**Comment by aaroecker** [comment]
This same issue is happening on my wife's phone.  I've tried refreshing contacts with in the signal app and removing and reading the account within the Android settings; nothing has resolved the issue.  Here's the report.  https://debuglogs.org/9f9455186ec2327d51fd000f077220787fb2accb8da26bf4c7ef58d9e7f4d1d4

**Comment by PatrickHonorez** [comment]
I made a simple test, creating a dummy user with the same phone number but
3 different formats. I think the issue is linked to the phone number
formatting.

For the following user, I see only the second number (professional) in
Signal.
[image: image.png]

Patrick

**Comment by aaroecker** [comment]
Any update on this?

**Comment by greyson-signal** [comment]
@PatrickHonorez 

> For the following 3 numbers, I see only the second number in Signal.
+352 691 676 66
691 676 666
00 352 69167666

I just want to clarify: it appears that the second number is actually different form the other two in that it has an extra 6, i.e. it ends with four 6's instead of three like the others. Is this a a typo, a different number format, or something else?

**Comment by PatrickHonorez** [comment]
@greyson-signal 
Sorry, it was a typo. The numbers were supposed to be equals, identical, except for the prefix. But I just tried recreating that example and Google contacts seems to recognize that the numbers have identical meaning, and to merge the 3 numbers. 
Anyway after searching a bit I still find some numbers that are perfectly OK, that do not appear in Signal while they DO appear using Android Messages. 
If it helps, one such number is +33 6 98 24 99 50 (this is one of my contacts real number).
That person is not a Signal user, but it's a valid SMS number.
Another contact with number +352 621 555 382 is in the same situation.
This makes Signal unusable as the default SMS app.

**Comment by LeeBinder** [comment]
same issue here. Any working solution?

**Comment by PatrickHonorez** [comment]
It's a type. All 3 numbers are like the 2d one, except for spacing and
country prefix.
Patrick

**Comment by LeeBinder** [comment]
@PatrickHonorez : wondering why you're re-hashing this since that's already been clarified..

**Comment by LeeBinder** [comment]
possible solution see [my post here](https://github.com/signalapp/Signal-Android/issues/9861#issuecomment-664689160) (worked for me).
