### ISSUE TITLE
Signal crashes at startup after LineageOS update

### ISSUE THREAD

**Issue by peter-michaelson1** [signalapp/Signal-Android#7453]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After updating LineageOS on my Oneplus One to version xxx Signal crashes every time when I try to start it.
I can use Signal using PC application and see all the message history properly.
I tried downgrading LineageOS back to ~month old versions, but the problem with Signal persist.
Also updated Signal beta to the newest version from Google Play with no help.

Not sure if this bug is related to LineageOS or Signal, but I'm looking for advice.

### Steps to reproduce
-Start Signal

**Actual result:** Signal crashes without asking for a password.
**Expected result:** Signal should ask for password and start normally.

### Device info

**Device:** Oneplus One
**Android version:** 7.1.2 (LineageOS 14.1-20180228-NIGHTLY-bacon)
**Signal version:** Newest beta from Google Play

### Link to debug log
03-02 13:22:54.904  9954  9954 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9954
03-02 13:22:54.904  9954  9954 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:121)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:60)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:75)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:153)
03-02 13:22:54.904  9954  9954 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:87)
03-02 13:22:54.906  5659  7241 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity

**Comment by moxie0** [comment]
Looks to me like the custom rom update nuked your entire android keystore. There's no way to recover from that, you'll have to reinstall. Might want to file a bug with the lineageos people.

**Comment by peter-michaelson1** [comment]
Thanks for a quick and accurate reply.
I know that this is caused by a LineageOS problem (which isn't the scope here), but I'm humbly asking for help:
I tried reinstalling Signal and restoring TitaniumBackup backup of Signal, but the crashing problem returned. 
Is there any way to restore my message log from a TitaniumBackup made of Signal with data and have it working?
Obviously the backup tries to use the information from nuked keystore. Is there anything I could try to restore the backup so that the new keystore would be used?

(Sorry for any errors in my explanation, I'm not that savvy regarding what's going on under the hood of Android.)

**Comment by haffenloher** [comment]
@peter-michaelson1 The problem is that your messages are encrypted with a key that's no longer there because the old keystore is gone :(

**Comment by moxie0** [comment]
Exactly, the key was stored in hardware, inaccessible to TI backup. Your TI restore gives you a bunch of ciphertext, and the key used to decrypt that ciphertext was apparently destroyed. I don't think there's a way to recover from your situation other than a fresh install.

**Comment by peter-michaelson1** [comment]
Thanks for the advices @moxie0 and @haffenloher, now I understand a bit more of the keystore and will study more out of curiosity.

I did a fresh install and Signal works as smooth as before.

I'd like to express my gratitude to the people who make Signal possible. It's a great piece of software and a fine example what profound effect properly done open source software (the Signal encryption protocol) can have. Keep up the good work.

**Comment by ale5000-git** [comment]
Just for reference the problem is discussed [here](https://jira.lineageos.org/browse/BUGBASH-590) and [here](https://review.lineageos.org/#/c/208870/).
