### ISSUE TITLE
Mobile number verify modal continue button hides when switch from landscape mode to portrait mode.

### ISSUE THREAD

**Issue by iamank1t** [signalapp/Signal-Android#7455]
#### Expected behavior
When user using app in landscape mode and then switch the app to portrait mode, then app needs to manage the layout according to device size. No button needs to be break out of the screen on changing device orientation.

#### Actual behavior
If you change device orientation from landscape to portrait, modal fails to resize it's size according to device screen size and 'continue button' hides.

#### How to reproduce
To reproduce the bug follow the following steps :-
- Download app from playstore and open it. You need to do verify your mobile number step to reproduce the bug.
- Now first change device orientation to landscape and the enter your mobile number. 
- After entering mobile number click on 'Register' button. After clicking, a modal will appear.
- Now without clicking on modal button change your device orientation to portrait and you see 'continue' button of modal goes out of the device screen.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v4.16.9
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=C2rewOsYh2k

**Comment by 2-4601** [comment]
Related #6492

**Comment by greyson-signal** [comment]
This should be resolved.
