### ISSUE TITLE
Cannot build latest version (v4.16.9)

### ISSUE THREAD

**Issue by TheCapsLock** [signalapp/Signal-Android#7458]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Following instructions from https://github.com/signalapp/Signal-Android/blob/master/BUILDING.md it is not possible to get a successful build. The following error occurs:

```
> Task :compilePlayDebugUnitTestJavaWithJavac
/Signal-Android/test/unitTest/java/org/thoughtcrime/securesms/crypto/MasterCipherTest.java:17: error: cannot find symbol
    masterCipher = new MasterCipher(masterSecret);
                                    ^
  symbol:   variable masterSecret
  location: class MasterCipherTest
/Signal-Android/test/unitTest/java/org/thoughtcrime/securesms/jobs/AttachmentDownloadJobTest.java:29: error: cannot find symbol
    job.createAttachmentPointer(masterSecret, attachment);
                                ^
  symbol:   variable masterSecret
  location: class AttachmentDownloadJobTest
/Signal-Android/test/unitTest/java/org/thoughtcrime/securesms/jobs/AttachmentDownloadJobTest.java:38: error: cannot find symbol
    job.createAttachmentPointer(masterSecret, attachment);
                                ^
  symbol:   variable masterSecret
  location: class AttachmentDownloadJobTest
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

```

### Steps to reproduce
- follow
- run gradlew build  # you should get the error here

**Actual result:** build fails
**Expected result:** build succeeds

### Link to debug log

(tested against 35a6ec707f4053966dbe70ffeffe097874de2af4):

https://framadrop.org/r/KiwiQYYqcS#JA8wt6Sg03fYdmGfKfHg0QwGPLCpva/HJ5h8UXmEumA=

**Comment by johanw666** [comment]
These errors seem to be in the unit tests, and because the 4.16 branch removed a lot of the mastersecret code I would not be surprised if some of the unit tests were not updated. I have no problems building from Android Studio.

**Comment by motatuc** [comment]
Builds fine for me as well.

Try these steps:

git reset --hard
git pull
./gradlew clean
./gradlew assemblerelease

Should work.

**Comment by bitfehler** [comment]
I had the same (I think) problem, updating my Android SDK solved it for me...

**Comment by nh2** [comment]
I have this problem now, and that is from a clean `master` clone.

@bitfehler which update / version might have brought the fix for you? Can you show your versions?

**Comment by nh2** [comment]
Also, I don't get how an update would help here. In the first mentioned file, a variable `masterSecret` is quite clearly not in scope.

Does Signal-Android have Continuous Integration? Where can I find it?

**Comment by lalunamel** [comment]
Looks like the failure to compile the tests that you're seeing is the result of this [More MasterSecret cleanup commit](3633d805c85f8e32a6fd326af553f3f23f369e3e) which happened Feb 1 2018.
I suspect the people in this thread that can build successfully are reporting that they can build _the app_ successfully, not the tests.

**Comment by lalunamel** [comment]
Hey @moxie0, I realize you're a busy person, but it's very frustrating to have done work to investigate an issue, create a PR, then have that work disregarded and the issue closed without comment. This has happened to me more than once.

Next time, I would appreciate a little nod towards the contribution I've attempted to make.
