### ISSUE TITLE
Add server status on homepage

### ISSUE THREAD

**Issue by natrius** [signalapp/Signal-Android#7461]
Please add the server status on the homepage somehow visible. If you have just one server because you don't want a federated network, fine, but manage it.

This is the exact reason why people are arguing for the federated network and not for a centralized server.

And no information anywhere from "official" is also really, really bad.

**Comment by ruicruzpt** [comment]
I agree with you, however this is not the right place to ask for it. 

But, still, I agree with you. ;)

**Comment by natrius** [comment]
As there is no github for the homepage itself, i wrote it here. Signal-server maybe?

**Comment by Cerberus0** [comment]
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/3835

**Comment by moxie0** [comment]
Please do not use GH issues for discussion, and please do not delete the issue template.
