### ISSUE TITLE
[Feature Request] Picture-in-Picture mode for video calls in Android 8.0

### ISSUE THREAD

**Issue by Cerberus0** [signalapp/Signal-Android#7462]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request

Android 8.0 (API level 26) allows activities to launch in picture-in-picture (PIP) mode. It would be neat if Signal Android could one day take advantage of this feature for video calls.

### Link to relevant documentation

https://developer.android.com/about/versions/oreo/android-8.0.html#opip

### Link to community forum discussion

https://community.signalusers.org/t/feature-request-picture-in-picture-mode-for-video-calls-in-android-8-0/1238

**Comment by jlund-signal** [comment]
Thanks for the suggestion. We use GitHub to track bugs, but I moved your forum topic to the new [Feature Requests](https://community.signalusers.org/c/feature-requests) section on the forums.
