### ISSUE TITLE
Group Chat: Impossible to find contact's number

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#7463]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal offers no way to see contact's number in group chats

### Steps to reproduce
Open any group chat in Signal and try to figure out a way to see the actual phone number of a contact.

**Actual result:** You can't
**Expected result:** You can. This is a really annoying problem in my use case because many of our employees have two cell phones: 1 work phone and 1 personal. I discovered this issue when an employee lost his work cell and started using his personal cell for everything. Every time someone started a work group chat it was impossible to tell whether they were using the right number for that employee.

### Device info

**Device:** Google Pixel XL
**Android version:** 7.1.2
**Signal version:** 4.15.5

**Comment by moxie0** [comment]
in 4.19.0
