### ISSUE TITLE
[i18n] Localizing singulars & plurals (Transifex)

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#7470]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm just pasting an issue found in the comments section of Transifex here, i. e. I am not affected personally nor do I know much about singulars & plurals in other languages.

**Example string:**
One: "SEND SMS TO 1 FRIEND"
Other: "SEND SMS TO FRIENDS"

**Translator's comment:**
All plural strings have issues. PLEASE use variable in original english string instead of fixed number 1. Or at least allow us to replace fixed number 1 with variable %d. In croatian, other slavic languages (and probably others around world) plural type "one" as defined in android is used for numbers 1, 21, 31, 41, 51, etc. So I can't just use 1, when same string will be used also for 21.
You can find more info on Mozilla localization site: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals
Islandic, all slavic languages (Russian, Ukraine, Belarus...), almost all Celtic languages etc., all those use plural rule ONE for more then just number 1.

**Comment by FeuRenard** [comment]
Here are the according developer resources:
https://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by johanw666** [comment]
Yesterday I translated 65 new strings in Dutch and found no such issues with them. Or is this a general remark?

**Comment by RiseT** [comment]
@johanw666 Depends on the language. In your case, I don't know if this is an issue in Dutch.

**Comment by FeuRenard** [comment]
This issue only affects [quantity strings](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) in languages, that reuse the quantity 1 string for other quantities such as 21,31,... Dutch is not affected according to the nice Mozilla documentation linked above.
