### ISSUE TITLE
Signal 4.17.0 - Export feature completely missing

### ISSUE THREAD

**Issue by nextgen-networks** [signalapp/Signal-Android#7473]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
- Plaintext export feature is missing.
- New export content feature (with db-keys) advertised in a couple of bug reports seems missing also.

### Steps to reproduce
- update from 4.1x.x to 4.17.0

**Actual result:** export feature seems to be missing entirely
**Expected result:** Signal content should be exportable to local store (i.e. to reset device and continue to work with signal or to move to another device)

Because of crypted database Signal data could not be restored with TWRP recovery or any external 3rd party app (I use MyBackupPro) in 4.16.x.

This leads now to an situation that one of the most popular secure messenger has no backup option!
... data security is meant a different way I thought ...

### Device info

**Device:** Xiaomi Mi Mix 2
**Android version:** 8.0.0
**Signal version:** 4.17.0

**Comment by moxie0** [comment]
Signal Settings -> Chats -> Backups

**Comment by nextgen-networks** [comment]
Hey @moxie0 

thanks for the fast response!
Good to kno feature is there - would be perfect to have this mentioned in final release notes

Thanks for your hard work!
