### ISSUE TITLE
[4.17.0] No fingerprint option for screen lock

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#7474]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I enable the screen lock option I can only use the password. There is no fingerprint option. Occasionally I briefly see a fingerprint screen after I've unlocked with the password.

### Steps to reproduce
- Enable screen lock

**Actual result:** See description.
**Expected result:** Option to either use a password or fingerprint for screen unlock.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.17.0

### Link to debug log

https://debuglogs.org/8ac0ea554e8c85378bc6834858f498aa26771474ad65ab423d64a6b6917fbd64

**Comment by moxie0** [comment]
Can you be more specific? What do you mean by "the password," and what are the steps to reproduce? Thanks.

**Comment by bme13** [comment]
Well, perhaps I don't understand the functionality. Based on the description in the playstore and the description at the screen lock option in Signal I would expect that the Signal screen lock could now be unlocked with the fingerprint sensor. So here's what I did.
* enable screen lock
* set the screen lock timeout to 1 minute (that appears to be the minimum)
* exit Signal
* wait more than 1 minute
* open Signal again
* at that point I get a screen that asks to provide a password. Now based on the description I did expect an option to use the fingerprint sensor of my device. I've tried the fingerprint sensor at that point but it didn't work.

**Comment by moxie-signal** [comment]
Can you include a screenshot? What password is it that you're being prompted for? Your Android device password?

**Comment by moxie0** [comment]
Can you include a screenshot? What password is it that you're being prompted for? Your Android device password?

**Comment by bme13** [comment]
![screenshot_2018-03-08-23-19-28](https://user-images.githubusercontent.com/25846829/37179886-866f0044-2327-11e8-8345-667eba595f31.png)

Yes the password is the Android device password. I've also notices that although I've set the language to English in Signal the message is displayed in Dutch. It translates to "Provide a back-up password"

**Comment by moxie0** [comment]
I see, that's the Android screen. It looks like the OS is telling Signal that there are no enrolled fingerprints, and displaying the system auth screen instead.

**Comment by bme13** [comment]
Ok, that seems strange to me since I use the fingerprint sensor to unlock the Android device. Do I need to enable this for specific applications in Android or is there something else I'm missing?

**Comment by moxie0** [comment]
No idea really. A lot of this stuff is device specific, can you enable fingerprint auth for any other apps?

**Comment by bme13** [comment]
Searched a bit and if I understand [this post](https://stackoverflow.com/questions/37764937/fingerprint-api-ishardwaredetected-always-returns-false) correctly I guess I'm out of luck for this feature on the Samsung S5. Thanks for the support.

**Comment by mlsxlist** [comment]
I experience the same issue with a Huawei Mate 9. I use the fingerprint sensor to unlock Android and various apps. Only signal seems to have a problem and asks for a password. Here is a debug log:
https://debuglogs.org/aac13b8c6d48b3707e5fbff5076a36b926cdf438fedbac17bbc833261a0821dd

**Comment by neteler** [comment]
Same issue on my Huawei P10: I would expect that the Signal screen lock can now be unlocked with the fingerprint sensor while only PIN is supported other than described in the play store.
Opening of a "concurrent" chat app works fine with the fingerprint sensor.
