### ISSUE TITLE
[4.17.0] Password screen is displayed when leaving Signal

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#7475]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When the screen lock is enabled the screen lock screen is also displayed when leaving Signal by using the back button. I think this only occurs when the password was requested during opening of Signal. Pressing back 2 more times does leave Signal though.

### Steps to reproduce
- Enable screen lock
- Leave Signal
- Wait until timeout expires
- Open Signal
- Leave Signal by pressing back button.

**Actual result:** Screen lock is displayed
**Expected result:** No Screen lock should be displayed on exit.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.17.0
### Link to debug log

https://debuglogs.org/8ac0ea554e8c85378bc6834858f498aa26771474ad65ab423d64a6b6917fbd64

**Comment by junitas** [comment]
I can reproduce this. When accessing the conversation list after a fresh unlock using the new "screen unlock" within the Signal app, pressing the back button will bring the user back to the pattern unlock screen. It doesn't actually re-lock Signal, however. 

If you press back again, or press home and then re-enter Signal, the pattern unlock screen is not present and you are taken to your conversation list as expected. If you re-enter your screen unlock pattern while the errant unlock screen is displayed, you are taken to the Android home screen.

I am also seeing some screwy behavior where if you press "home" on the initial pattern unlock screen within the Signal app, a subsequent touch on the Signal app launcher icon does nothing and you must press it twice to re-enter Signal.
