### ISSUE TITLE
Signal profile avatar out of frame (cropped) when viewing profile details

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7476]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The signal profile avatar is out of frame when viewing the profile details. 
This is kinda hard to explain. And since a picture is worth a thousand words here are three pictures instead of threethousand words. 

![01-signal-avatar](https://user-images.githubusercontent.com/18451020/37177891-bb7d0808-2318-11e8-8926-dc6d428d7941.png) 
Head is in the centre of avatar bubble. 

![02-signal-avatar](https://user-images.githubusercontent.com/18451020/37178034-2fdc9a60-2319-11e8-95af-38a754a5d295.png) 
Head is still in the middle. 

![03-signal-avatar](https://user-images.githubusercontent.com/18451020/37178062-45f1bf92-2319-11e8-8c2e-785960ee1edc.png) 
Head is cropped and goes out of frame. 

__________

I'm not sure if this is a Signal or Android Issue. But as far as I can tell this happens to all avatars who are Signal profiles. When I set a picture for a contact the old fashioned way in my phone contactlist it does not get cropped. 

### Device info

**Device:** Samsung Galaxy S5 klte
**Android version:** lineage-14.1-20180302-nightly-klte
**Signal version:** 4.17.0

### Link to debug log

n/a

Thanks! Let me know if this is unclear or you need anything.

**Comment by moxie0** [comment]
I'm not sure if there's another way to display the existing data. If we have a profile avatar that is a square, displaying it as a circle is straightforward (round the corners). However, the details pane needs to display a rectangle. This is done using CENTER_CROP, which essentially zooms until both edges meet the dimensions, and crops what doesn't. Moving from square to rectangle, it makes sense that some vertical pixels are lost.
