### ISSUE TITLE
[4.17.0] Signal Pattern Unlock Screen Issues

### ISSUE THREAD

**Issue by junitas** [signalapp/Signal-Android#7480]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Related to #7475 and #7474

The Signal pattern unlock screen is displaying on top of the Android pattern unlock screen. Under certain screen timeout conditions described below, on waking an Android device the Signal unlock screen will display instead of the Android unlock screen and will sometimes remain displayed after inputting correct unlock pattern. If you then input your pattern into the Signal unlock screen, the Android unlock screen will display. After then unlocking your Android as usual, the Signal app will still require you to input the unlock pattern to unlock Signal.

### Steps to reproduce
- Set the Signal lock pattern timeout to be 1 minute
- Set your Android lock pattern and set display timeout to 1 minute
- Open Signal to the conversation list. Let sit for 1 minute to allow Android to lock, and then an additional minute for the Signal timeout to occur.
- Press power button to attempt to unlock phone via pattern. Observe that Signal unlock screen is displayed.
- After entering Signal unlock pattern, and then entering Android unlock pattern, observe that Signal is still locked.

**Actual result:** Signal unlock screen is displayed before the Android unlock screen. Entering pattern does not immediately unlock Signal.
**Expected result:** Android lock screen is displayed and Signal unlock screen is only displayed when you enter Signal.

### Screenshots

None as of now because android studio is a resource hog.

### Device info

**Device:** Nexus 6
**Android version:** 7.0.0
**Signal version:** 4.17.0

### Link to debug log
https://debuglogs.org/774c5c5af6648b2e279f7f884813d348d27a00817c05a7485b9ef42fcbfa20f7

**Comment by johanw666** [comment]
Then what do you do on a device without a fingerprint scanner (or one where it is not configured)? Revert to the old password, that disappears from the settings once you choose a pattern unlock?

**Comment by Dyras** [comment]
I'm using Moto G4 with Nougat 7.0.1 and I'm experiencing this as well. The Signal lock screen is sometimes on top of the Android lock screen, which for some reason means that I have to unlock the Signal lock screen, then the Android lock screen, then the Signal lock screen again.

Here's how to reproduce:
1. Enable the Android lock screen with graphical pattern
2. Enable the Signal lock screen with a 2 min timer
3. "Close" the app by swiping it. Hell just press close everything.
4. Lock your phone
5. Sit down and play Borderlands for 2 hours without giving a care in the world for your friends that ask you if you're still alive
6. Start the screen on your phone by tapping the power on button (....) and then double click the Signal message
7. Now in some rare cases the Signal lock screen will appear on top of the Android lock screen. Not all the time, just sometimes. 

Will hook you up with a debug log next time it happens!

**Comment by moxie0** [comment]
It doesn't seem that there's any further action I can take here, please reopen if anyone sees a workaround.

**Comment by junitas** [comment]
This particular issue with the Signal lock screen seems to have been resolved and I can no longer reproduce.

**Comment by behrmann** [comment]
I still experience the problem.

**Comment by Dyras** [comment]
I haven't experienced it for quite some time, but sadly there doesn't seem to be anything Moxie can do about it. Perhaps one day, Google will get their asses out of their civilian monitoring stations and release a way to fix this.

**Comment by behrmann** [comment]
Well, without this wanting to sound confrontational and conceding that Google's lockscreen API is at fault here, this still is a regression in Signal, since this only apperead after the old lock screen disappeared.
