### ISSUE TITLE
[4.17.0] Signal sporadically asks about registration lock PIN

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#7484]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have experienced 2 different occasions where Signal asked for the registration lock PIN that make no sense to me and might be related to each other.

**First case**
In the first case, in order to test the registration lock functionality, I did a clean install of Signal after enabling a registration lock PIN. Unsurprisingly, I got asked for the PIN during the registration process (if I remember this correctly, containing the string *RegistrationActivity_this_phone_number_has_registration_lock_enabled_please_enter_the_registration_lock_pin* ). After entering the correct PIN, the registration process completed. But then I got a second, slightly different looking view that again asked for the registration lock PIN (if I remember this correctly, containing the string *RegistrationLockDialog_registration_lock_helps_protect_your_phone_number_from_unauthorized_registration_attempts* ). I again entered the PIN and got to the conversation list.

**Second case**
Here, I got asked for the registration lock PIN several hours after completing the registration process, i. e. directly after unlocking Signal via fingerprint. The debug log below is taken directly after entering the PIN.

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.17.0

### Link to debug log

https://debuglogs.org/fa09e2581c6308f3259eb69c2d8f0df02fbbd965980e1f01044ca0f5cb49615f

**Comment by FeuRenard** [comment]
This might be a feature. Signal wants to make sure you remember the PIN. You have to keep in mind that regular users (not us, Signal-Android-Github fanboys) re-register very rarely.

The frequency of how often users will be asked for the PIN might decrease with time. At least that's what I observed with WhatsApp.

**Comment by RiseT** [comment]
@FeuRenard Mh. That's possible. I don't know about this feature in WA, as I've stopped using WA some time ago.

I still think it makes no sense to enter the PIN two times within a time period of a couple of seconds as in example 1, though.

**Comment by Dyras** [comment]
If this is a feature to make sure you remember it, it would be great to put that in the box. "Do you remember your PIN? Check if you do here:" or something
