### ISSUE TITLE
[Request] Screen Sharing

### ISSUE THREAD

**Issue by rakismelange** [signalapp/Signal-Android#7486]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Request description

Allow users to share screen during video call.

**Comment by jlund-signal** [comment]
Thanks for the suggestion. We use GitHub to track bugs, but you can discuss this idea in the [Feature Requests](https://community.signalusers.org/c/feature-requests) section of the community forums.

**Comment by tbertels** [comment]
For the record, here's the actual feature request about screen sharing: https://community.signalusers.org/t/screen-sharing-on-all-platforms/15826/52

**Comment by AdnanHodzic** [comment]
Top bad this issue is closed, because 6+ years later and we're still not able share screen on video call with Signal on Android (smartphone).

**Comment by SenjuSama2012** [comment]
Is there any way to revive this Issue??? I just switched over a bunch of my family members to Signal but a stopping point for some of them is the missing feature (although working for the Desktop version) is the Screen Sharing for Android users.
