### ISSUE TITLE
[Feature] Allow user to disable "swipe right to archive chat"

### ISSUE THREAD

**Issue by VincentEngel** [signalapp/Signal-Android#7487]
Quite often i want to open a chat, but swipe a bit to the right while doing it, therefore triggering the "swipe to archive chat".
Since chats can be archived holding down for some seconds on a chat and using the archive button appearing in the top right corner, i would really appreciate an option to disable the swipe right to archive a conversation function.

This option could be in Settings > Chats and Media > Chats
It could be called "Enable swipe right to archive".
It could be enabled by default, therefore not changing any behaviour.

**Comment by moxie0** [comment]
Thanks but we're not going to do this, see "development ideology." Please try not to delete the issue template in the future, thanks!

**Comment by csmacomber** [comment]
This is disappointing.  I like Signal except I accidentally "archive" conversations all the time.  I really wish I could turn that "feature" off (as it is not a valuable feature to me, or others apparently)
