### ISSUE TITLE
[4.17.0] Lock screen is sometimes completely black

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#7489]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes for no apparent reason the Signal lock screen is black after you start the app by double tapping a notification when the phone is locked

### Steps to reproduce
1. Have your phone locked
2. Get a new message
3. Tap the message twice on the phone lock screen
4. Unlock Android
5. Pray this happens

**Actual result:** In very rare cases the Signal lock screen is black. Well more like dark gray but you get the point.
**Expected result:** The lock screen shows 100% of the time

### Screenshots
![signal-2018-03-09-230242](https://user-images.githubusercontent.com/12563436/37232234-73a363ca-23ee-11e8-8028-29c28f27c88e.png)

### Device info
**Device:** Motorola Moto G4
**Android version:** 7.0
**Signal version:** 4.17.0

### Link to debug log
https://debuglogs.org/15d81b6098534662d2645bba3709e4f9d45c494dcbaaf1b2dc163cd5629373e4
https://debuglogs.org/743ec3787775e161fc4ae35e71e4f12f1a31abe896b154137b439ac32c45ee4a
The log looks really weird, is it really supposed to look like that?

**Comment by sorryusernameisalreadytaken** [comment]
I had the same issue with my OnePlus One running with LineageOS 14.1 based on Android 7.1.2. I dont find a way to reproduce it yet :/

Next time it appears I will try to get a log.
