### ISSUE TITLE
missed messages

### ISSUE THREAD

**Issue by Da0012** [signalapp/Signal-Android#7499]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I sent 4 continuous messages but it didn't reach to friend's smart phone or my desktop application.
Signal shows one check on my smartphone

messages sent at 
21:42:05
21:42:15
21:42:22
21:43:22

### Steps to reproduce
i can't do it.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** motorola Moto G (lineage_falcon)
**Android version:** 7.1.2
**Signal version:** 4.16.9
  
### Link to debug log

https://hastebin.com/gowovivojo.hs

**Comment by leonardoporpora** [comment]
Yeah I can confirm that once it happened to me too. But I have no idea of how I can reproduce it.

**Comment by moxie0** [comment]
I'm unable to reproduce this, and there's no useful information in the debug log. Please reopen if you can provide steps to reproduce from a clean install, or a debug log that covers the relevant period.

**Comment by Da0012** [comment]
Some messages sent and received do not appear on the receiver's devices.
The messages were sent from desktop and android.
First it happened on signal, After that I noticed that wire too.

This is bidirectional.


https://debuglogs.org/be41131edc2725abe80640d9ca06d2862587206d4ec54d01ae22de4f603931fd

https://debuglogs.org/9831f717564f3e1e473c0220ee6b47f29a5a4e0f1b0865016bae87061f67e07c
