### ISSUE TITLE
Include Signal in F-Droid

### ISSUE THREAD

**Issue by nimbius** [signalapp/Signal-Android#7505]
This may be flogging a dead horse.  Moxie himself closed several of these issues with what i suspect was a growing sense of aggravation.  I once again request that Signal be added to F-Droid.

I also feel reopening the dialogue a year later has real value.

- Moxie is correct in stating that a download from play is easier than the harrowing process of enabling third party repos in Android.  This request is for more security minded users and establishes a "post google" path forward.  

- #127 Moxie outlined a very reasonable list of requests for F-Droid and his 2013 sentiments on the security of the platform were well founded.  F-Droid now allows to distribute a developer-signed version of the app, if the build is reproducable by their build server, and F-Droid now allows installation of apps without enabling third-party support.  

- FDroid allows opt-in bug reporting.

- F-Droid receives annual security audits from neutral partners and publishes the results.
https://www.f-droid.org/en/2018/01/20/upcoming-security-audit.html

- Moxie was kind enough to provide https://signal.org/android/apk/ in 2017 but as the "Danger Zone" implies, this is textbook sub-optimal distribution no better than Google Play.  

Why we need Signal in FDroid
- Google has been a member of the PRISM program for 9 years.  The fact that it joined the program at all is more than enough reason to reassess it as the sole provider of Signal.
- Arab Spring events have proven the big 3 (google, facebook, twitter) all go predictably dark.  By relying solely on Google, Signal cannot be quickly deployed in such emergencies where it would do the most good.

**Comment by moxie0** [comment]
Please do not intentionally open duplicate issues, delete the issue template, or post discussion topics on GH. If you're interested in discussion, please see the forums.

**Comment by Jowat97** [comment]
> Please do not intentionally open duplicate issues, delete the issue template, or post discussion topics on GH. If you're interested in discussion, please see the forums.

He is not CEO anymore.  @Meredith-Signal is the president of the Signal Foundation and also a great contributor to open source community. May she has a different view on it, so that it could be published on F-Droid?

**Comment by jason88fr** [comment]
Any update on this or will things stay the way they are due to some of the libraries being proprietary?
