### ISSUE TITLE
Adapt theme to light conditions

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#751]
Under low light conditions the light design is too bright and puts a strain on the eyes. Thus, a nice thing to have would be an option to switch between light and dark theme automagically using the light sensor.

| Theme |  |
| :-- | :-: |
| light theme | ( ) |
| dark theme | ( ) |
| depending on light condition | (o) |

**Comment by NorthwestBased** [comment]
IMO, the problem of screens being too bright isn't a problem with textsecure, but a problem with phones in general, and shouldn't be fixed locally, but globally for a whole phone. Maybe something like this?

https://play.google.com/store/people/details?id=110556507151732274846

@tx3eh8IUD1 Android 4.2.2 (and I'd assume more recent versions) has a font size setting to globally increase the size of text. Maybe the font in the situation you bring up is too small, but I'm not sure that we should reinvent the wheel when Android has built-in fixes for those who have these problems. I don't believe that textsecure is the only app to use small text.

**Comment by manhole11** [comment]
Yes please! This would be so useful, I currently keep swapping between light and dark theme

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
