### ISSUE TITLE
Passphrase on Virtual Device

### ISSUE THREAD

**Issue by EnesSoyaker** [signalapp/Signal-Android#7512]
Hi.

On Android Studio 3.0.1, Signal shuts down at the first opening right after the installation. From then on, when opened manually, it asks for a passphrase.

I tried removing passphrase from the code but every class is tied with another, which makes it too complicated. Is there an easy way to remove the passphrase from the code? I can not access the app.

Thank you.

**Comment by moxie0** [comment]
Please don't delete the issue template. If you have a question about Android development, please see the online forums.

**Comment by EnesSoyaker** [comment]
Thank you. That was way very help-full!

2018-03-13 19:41 GMT+03:00 Moxie Marlinspike <notifications@github.com>:
