### ISSUE TITLE
[4.17.2] Registration Lock PIN ist randomly requiered

### ISSUE THREAD

**Issue by Le1b1** [signalapp/Signal-Android#7513]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Registration Lock PIN ist randomly required.
If I press 'back', the prompt is gone and everything is fine, sometimes Signal crashes.

### Steps to reproduce
1. Enable Registration Lock PIN
2. Use other apps / wait some time (can't reproduce reliable)
3. Open Signal direct or via notification

**Actual result:** It happens
**Expected result:** I should see that prompt only after a recent installation (?) 

### Device info
**Device:** Google Pixel 2
**Android version:** 8.1.0
**Signal version:** 4.17.2 beta

### Link to debug log
https://debuglogs.org/34c05732bb5e5e865fef9edf7cfd76ed48de367b9393e4038d1d4c4f9676ae9e

**Comment by FeuRenard** [comment]
> **Expected result:** I should see that prompt only after a recent installation (?)

I think it's very useful that Signal asks regularly for this PIN, because otherwise I would forget the PIN as I don't register as Signal user very often. And there is no other use for this PIN which could help me memorize it.

That is how the dialog which requires the PIN explains itself:

> Reminder: Registration Lock is enabled for your phone number. To help you memorize your Registration Lock PIN, Signal will periodically ask you to confirm it. I forgot my PIN.

**Comment by Le1b1** [comment]
>That is how the dialog which requires the PIN explains itself:

>>    Reminder: Registration Lock is enabled for your phone number. To help you memorize your 
>>    Registration Lock PIN, Signal will periodically ask you to confirm it. I forgot my PIN.

Ah, ok. I'm using a password-safe for that. :-) 

So asking that PIN several times a day is a feature?

I get the 'memorize' point, but why not only ask for it if one registers a existing account on a new device?

**Comment by FeuRenard** [comment]
"several times a day" sounds like too often for me. Let's look at the intended values for the reminder interval:
https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/lock/RegistrationLockReminders.java#L17.

- 6 hours, then
- 12 hours, then
- 1 day, then
- 3 days, then
- 7 days

So Signal works as designed by the developers when it asks two times for the PIN within 24 hours after activation (after 6 hours and after 18 hours). So this only affects the first day and I think that's ok.

> why not only ask for it if one registers a existing account on a new device?

You mean every two years when the average user gets a new phone? In the meantime I see no reason to register my phone number on a new device. That's too long, isn't it?
If you mean Signal-Desktop: afaik the acitvation of a Signal-Desktop instance doesn't require this PIN. You have to be inside the app on your phone to activate such an instance and that's already past the registration lock PIN barrier.

**Comment by Le1b1** [comment]
> So Signal works as designed by the developers when it asks two times for the PIN within 24 hours after activation (after 6 hours and after 18 hours). So this only affects the first day and I think that's ok.

Maybe my problem was, that I didn't always enter the PIN and pressed 'back' instead. :-|

> You mean every two years when the average user gets a new phone?

Yes, but 7 days shouldn't kill me either. :-) 
Doesn't seem to be a feature for the average user. 
I would be fine to save that code somewhere and only use it if really required, just like the passphrase for the backup.

Anyways, the occasional crash when I dismiss the prompt is still a bug.
