### ISSUE TITLE
Sending SMS to multiple recipients

### ISSUE THREAD

**Issue by Jojo-A** [signalapp/Signal-Android#7514]
Hi,
obviously it is (still) not not possible to send SMS to multiple recipients at once.

Of course there have been several issues about this, which are referenced in this context:

- #232 Closed. Obviously this is about MMS, which is in real life not an alternative to "old school" SMS, so it has not much to do with plain SMS
- #347 Closed due to cross-reference (not due to a solution)
- #365 Closed because @moxie0 pointed to complications with the Android subsystem
- #413 Open but locked. Here is where it gets interesting: @mcginty told that they won't invest time into a "legacy protocol". The fact, that it has been requested be many users could indicate, that it is not as "legacy" as one might think. In fact, what's making an application successful is, that it fulfills the users needs/requests. So IMHO something can not be "legacy", if it is used be much more than just a hand full of people. Additionally @mcginty says that this feature is not on the short-term road map - which has been three years ago (-> long-term)!
- #1395 Closed due to cross-reference to #270 or #1499
- #1499 Closed for no real reason

No offense at all, I know that many developers are working in their free time!
I just ask, because I don't understand the philosophy.
- People ask for a feature (which is crucial for some of them), and get told, that it is old and legacy
- one issue after another about this topic pops up and get closed again
- people get told, that they are free to develop this feature, which is kind of "arrogant", because not everyone is able to do that. A question to developers may not be rejected with the message "Develop it yourself".

From my point of view, this feature is important, too, because I like to use Signal as my only messaging app, but I can't because of this. How should I argument, if friends tell me "I don't use Signal, because it does not support this and that."?!
And from my point of view, this would be a much more useful feature, than 50 new emojis...

Greetings

**Comment by FeuRenard** [comment]
Please use the [community forum](https://community.signalusers.org/) for discussion and don't intentionally open duplicate issues (see #413).

See https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum

> Please do **not** use this issue tracker as a discussion forum. Discussion related to the bug in question should of course go to the issue itself. However other discussion should take place at the community forum. You can use that forum to discuss any Signal related topics or to just hang out with your fellow users.

**Comment by Jojo-A** [comment]
@FeuRenard Ok, understood. Sorry that it seems not clear enough, but I did not open up this issue to "discuss". It was more meant to be a feature request.
I just wrote a little bit more so show, that I am aware of the other more or less related issues. I just wanted to avoid, that my feature request gets closed or locked by "Duplicate of issue #xxx." or "Please develop and make a PR.".
@mcginty demanded to hold back "+1" posts. This is generally understandable. But what should users do, when they've feel to share the same problem, but don't get heard?

Again, I understand that we should not "discuss" here, so I won't continue. I am just one of those guys who would like to see this feature.

**Comment by RichJeanes** [comment]
@Jojo-A The "Thumbs Up" reaction emoji seems to have taken on the roll of the "+1" on GitHub. It shows that there are people interested or watching a topic but does not generate email notifications for those involved in the thread or on the collaborators team.

**Comment by Jojo-A** [comment]
@RichJeanes Yep, thats true. But in this case, there is no emoji button (at least for me) for the other references issues. I guess because they are locked or closed.
So in which way I am allowed to show, that I am interested in such a feature?
- "Thumbs up" not working
- Opening issues not wanted because of already existing cross references
- ?
I checked the forum. One guy already asked for that [just recently](https://whispersystems.discoursehosting.net/t/how-to-post-sms-to-multiple-users-in-one-go/2096/2). The reaction was, that he got looped back to the already existing issues here on GitHub.

**Comment by haffenloher** [comment]
> So in which way I am allowed to show, that I am interested in such a feature?

Feel free to e.g. reply to that forum thread, use the GitHub reaction buttons when available, etc. Signal staff regularly visit the forum and prioritize new features based on community feedback.

But please respect that we try to use the GitHub issue tracker only for tracking issues, not for discussions such as this one. If an issue like #413 is open, it's tracked. If it's locked, it's to avoid spam and because there's simply no need for more comments. There's no piece of information missing for #413 to be implemented, someone just has to do it. Creating additional issues and comments about it just creates more [email notifications](https://github.com/signalapp/Signal-Android/pull/6886#issuecomment-370990920) for everyone including Signal staff, which means they'll have a little less time to work on this and other issues. So: please close this issue and let's continue the discussion in the community forum :)

**Comment by Jojo-A** [comment]
@haffenloher Agreed. Thanks
