### ISSUE TITLE
Wish: possibility to not accept signal calls and audio messages

### ISSUE THREAD

**Issue by markum** [signalapp/Signal-Android#7520]
For different reasons I do not want to receive calls and audio messages via Signal. Unfortunately there does not seem to be a setting for that. Having to tell every new contact this is annoying. I would find it better to solve this on a technical level, so that the user can select in the app that he does not want to receive audio calls (basically like a flight mode) and audio messages (like having the mailbox turned off). The user on the other side should then not find a call or record button when he attempts to make a signal call to this person or record audio. Would be great if this could be implemented.

**Comment by FeuRenard** [comment]
Related to #6855

**Comment by moxie0** [comment]
Thanks but we're not going to do this for now. Please try not to delete the issue template in the future.

**Comment by bungabunga** [comment]
@markum
1. you effectively disable calls if you route Signal through Tor (via Orbot app)
2. you can also disable dowloading audio/video attachments in Signal settings

**Comment by markum** [comment]
@bungabunga 
Thanks for that info. Disabling downloads is not a real solution, because people just expect you listen to them and that is really annoying.
