### ISSUE TITLE
Backups stored in internal memory despite SD card

### ISSUE THREAD

**Issue by nrizzio** [signalapp/Signal-Android#7521]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a removable SD card in my phone. When I enable backups, they are stored within *internal* memory. This often plows right through my storage and defeats the purpose of having an SD card.

### Steps to reproduce
- insert SD card, encrypt it
- enable backups
- wait for the first backup to finish

**Actual result:** The backup is stored within internal memory, chewing up scarce storage space
**Expected result:** The backup is stored on the SD card, allowing me to save valuable space

### Device info

**Device:** Samsung Galaxy Grand Prime
**Android version:** 5.1.1
**Signal version:** 4.17.3

### Link to debug log

https://debuglogs.org/03539ef784b5b00aa608880dee112ea4f4fc98f830f74acd9876c0fec62095cb

### Note

I submitted this on mobile (my computer is rather broken at the moment). I apologize in advance if I have missed details or made formatting mistakes.

**Comment by johanw666** [comment]
Your misunderstanding comes from the ambiguous terminology: "external memory" in Android was in the beginning (Android 1 - 2) usually the removable memory card, but now it confusingly means the internal memory. And when unified memory is used in Android 6 or higher it can be both.

See http://www.riptutorial.com/android/example/17144/android--internal-and-external-storage---terminology-clarification for ore details.

If you want to automatically map the internal sd card to the removable one, there is an Xposed module to do that: XinternalSD. It only works for apps who use the official api's to find the location because it hooks that api call but Signal does that.

**Comment by RiseT** [comment]
So - according to that link - the correct (i. e. Google's) terminology for a SD card would be "Secondary External Storage"...? Jeez...

Back to topic, imho it should be possible to store Signal backups on a SD card without having to use a tool like Xposed.

**Comment by moxie0** [comment]
I don't think there's a way to get the path you want. We ask Android for the external storage directory, and use the path it gives us.

**Comment by cdysthe** [comment]
I'm having the same issue on my Moto G5+ with Android 7. Backups are stored on internal storage, not the SD card.

**Comment by RiseT** [comment]
For what it's worth, here's what I've found:

> You are welcome to use the **getExternalFilesDirs()**, **getExternalCacheDirs()**, and **getExternalMediaDirs()** methods on Context. Note the plural method names. **If those methods return 2+ entries, the second and subsequent ones are locations on removable storage that you can read from and write to, no permissions required.** However, you cannot access all of removable storage this way, just a location specific for your app.
> 
> You are also welcome to use the **Storage Access Framework, allowing the user to pick where the content goes, including placing it on removable storage**. However, you are no longer working with files and paths, but with content and Uri values.
> 
> The N Developer Preview offers another option for **"Scoped Directory Access", which supports removable storage**. However, this is still part of a developer preview at the present time (March 2016). 

Source:
https://stackoverflow.com/questions/35947286/android-dev-accessing-external-sd-card-directly-on-samsung-devices-with-extsdc

**Comment by Natanji** [comment]
@moxie0 An easy solution to this would be a an option to pick the directory where the backup should be saved. There's no reason for Signal to force a specific directory and only rely on what Android is telling you; with the diversity in the devices and how they implement external storage, it's bound to fail on some devices.

**Comment by moxie0** [comment]
I've reviewed the API, and it doesn't seem like there's any defined way to access "removable storage," and that even the undefined ways are limited to scoped access for music, video, etc. Please reopen if anyone can determine a way to reliably access removable storage.

**Comment by Natanji** [comment]
@moxie0 It might be worth looking at the Code for OsmAnd for this. In OsmAnd users can choose between internal memory, external memory 1 (which is as @johanw666 pointed out usually the Android "emulated" internal memory, so ends up being the same location) and external memory 2, which is the actual SD card.

Their way to (reliably, as far as I can tell) get the SD card is to check whether the file path contains the string "emulated" (which means internal memory) among all the dirs returned by getExternalFilesDirs(). It might seem hacky but works reliably as far as I can tell, see [here](https://github.com/osmandapp/Osmand/blob/e0cd250e63b129c398fdc8af41ff08052be249a3/OsmAnd/src/net/osmand/plus/OsmandSettings.java#L1614) for how Osmand implements this.
