### ISSUE TITLE
Contact got new phone. First message seemed to crash my Android

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7525]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Contact got a new phone, re-registered, and didn't specifically disconnect desktop app (two devices links) 
Re-linked one device, messaged me. My Android app crashed but not sure if coincidentally or causally. Don't really want to go through the hassle of unregistering etc to test but the log is below.

### Steps to reproduce
- 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
N/A

### Device info

**Device:** Samsung galaxy s8
**Android version:** 7.0
**Signal version:** 4.16.9

### Link to debug log
https://hastebin.com/jegihovuge

**Comment by moxie0** [comment]
Looks like an Android bug:

`````
03-14 19:34:18.075 10614 10675 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-2
03-14 19:34:18.075 10614 10675 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10614
03-14 19:34:18.075 10614 10675 E AndroidRuntime: java.lang.SecurityException: Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }: Unable to launch app com.google.android.gms/10026 for service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }: process is bad
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1455)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1404)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:673)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zzai(Unknown Source)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.GcmRefreshJob.onRun(GcmRefreshJob.java:71)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
03-14 19:34:18.075 10614 10675 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
`````

Is your phone rooted or anything weird like that? Looks like play services is messed up.

**Comment by jeremymasters** [comment]
No root, just plain stock s8 verizon 7.0

**Comment by moxie0** [comment]
This looks like an Android bug, so I'm closing for now. No action I can take.
