### ISSUE TITLE
Signal crashes on startup after update from lineage-14.1-20180309 to 20180316

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7534]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm running LineageOS on a Galaxy S5 klte. I updated to the latest LineageOS weekly release about six hours ago (v. 20180309 to v. 20180316). https://download.lineageos.org/klte
Update finished without any problems. But since the update my Signal is crashing on startup. 
I signed up for the beta and my Signal Version is 4.17.3. Due to the crash I am unable to provide a debug log. I did however captured an adb log from the OS. The crash only happens to Signal. Other apps seem to be fine. 
This might be related to #7412

### Steps to reproduce
I have a second phone (Galaxy S4 jfltexx) where exactly the same happened. Update to latest LineageOS release. Signal crashed on startup. 

### Screenshots

n/a

### Device info

**Device:** Samsung Galaxy S5 klte
**Android version:** 7.1.2 (lineage-14.1-20180316)
**Signal version:** 4.17.3

### Link to debug log

[logcatcrash.txt](https://github.com/signalapp/Signal-Android/files/1821445/logcatcrash.txt)

**Comment by motatuc** [comment]
Have the same problem here. Moxie is assuming that the keystore got deleted during ROM-update. Only way to get your messages back I guess is a backup.

**Comment by halb9** [comment]
oh ok. Will close this for now and reopen if necessary. Thanks!

**Comment by moxie0** [comment]
This is a pretty severe LineageOS bug. You might want to file an issue with them, they appear to be destroying the OS KeyStore on each OS update. Until they fix it, this will happen every time you update LineageOS. I haven't seen this happen with any other ROM yet.

**Comment by motatuc** [comment]
They are aware but do not seem to know how to solve this atm.

https://review.lineageos.org/#/c/208870/
https://jira.lineageos.org/browse/BUGBASH-590

**Comment by cegg1** [comment]
@moxie0 Apparently the keystore does not really get destroyed, it only becomes inaccessible from the new ROM and it appears to be recoverable by downgrading to the previous ROM. Also, it does not happen on every single OS update, it only occurs when the value of PLATFORM_SECURITY_PATCH is changed. 

I'll try to summarize what is known so far from the Gerrit and Jira links above: 

1) Keystore is not really destroyed on ROM update, it only becomes inaccessible from the new ROM.
2) Downgrading the ROM to the previous version immediately recovers keystore functionality.
3) Loss of access to keystore is triggered by the change in the value of PLATFORM_SECURITY_PATCH alone.
4) None of the actual security patches break access to the keystore if the value of PLATFORM_SECURITY_PATCH is kept unchanged.

**Comment by rmueller83** [comment]
For me the ROM downgrade did not work.

**Comment by halb9** [comment]
Guys, 
I'm pretty sure I want this to be resolved as much as you do. 
But as moxie requested many times, this github repository should be for issues only. 
And as this is clearly not a Signal issue there is no point in posting here anymore. That is why I closed this issue in the first place. If you want to help please look at the LineageOS Tracker. 
Thanks. Have a nice day.

**Comment by Diapolo** [comment]
https://review.lineageos.org/#/c/LineageOS/android_system_security/+/210422/ and https://review.lineageos.org/#/c/LineageOS/android_system_security/+/210421/ have been merged in the LineageOS repo. Is anyone able to do a LOS build and see if Signal does recover with these applied?
