### ISSUE TITLE
Read receipts stops working when reconnecting desktop client

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#7535]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I unlink and then relink a desktop client, the desktop client no longer receives read receipts. Other linked desktop clients continue to get the blue mark, but the newly linked doesn't.

If I toggle the read receipts off and then back on again on my phone, it starts working again across all desktop clients.

The read receipts status probably needs to be synced when a desktop client is bootstrapped.

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.16.9
**Signal Desktop version:** 1.6.1

**Comment by nrizzio** [comment]
Please always include a debug log in issue reports.

**Comment by petcap** [comment]
Sorry, here are the debug logs from both the phone and desktop client:
[debug-android.txt](https://github.com/signalapp/Signal-Android/files/1822486/debug-android.txt)
[debug-desktop.txt](https://github.com/signalapp/Signal-Android/files/1822487/debug-desktop.txt)

They were produced by by doing this:

1. Force close Signal on Android
2. Start Signal on Android
3. Unlink previously linked desktop client from phone
4. Close desktop client and relaunch it
5. Re-link the same desktop client
6. Send a message from the phone to a third device
7. Send a message from the desktop client to a third device
8. Read both of these messages on the third device

After doing this, I got a blue check mark on my phone for both messages, but not on the newly linked desktop client. My laptop, which remained linked the entire time, also got the blue check marks for both messages.

The third device, which messages were sent to, is running iOS. I have however observed the same behavior when I send messages to people running Android.

**Comment by dmzpkts** [comment]
I also have this exact same issue.

**Comment by moxie0** [comment]
I've check with the desktop folks, and this is a bug on their end. They've got it on their list, should be fixed soon. Thanks!
