### ISSUE TITLE
Signal does not show SMS'es sent with other applications

### ISSUE THREAD

**Issue by pietervdvn** [signalapp/Signal-Android#7536]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

When another application sends an SMS (e.g. in an automated way), Signal does not pick those up and does not show them in the thread.

### Steps to reproduce
- Use an app to automatically send an SMS (e.g. as answer on a location query)
- Message does not show up

**Actual result:** SMS does not show up
**Expected result:** SMS should show up

### Device info

**Device:** Samsung Galaxy S5 - LineageOS 15
**Android version:** 7.1.2
**Signal version:** 4.17.0

PS: thanks for making Signal!

**Comment by PiCob** [comment]
Could you provide a log file immediately after reproducing this issue? That might need helpful.

**Comment by FeuRenard** [comment]
Duplicate of #4037 and #5803.
