### ISSUE TITLE
Unregistered

### ISSUE THREAD

**Issue by bivol** [signalapp/Signal-Android#7545]
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Today suddenly Signal deregistered me on my phone. I had to register again and to resync with the desktop app. 

### Device info

**Device:** Samsung Note 8
**Android version:** 7.1.1
**Signal version:** 4.16.9

**Comment by riyapenn-signal** [comment]
Support@signal.org has emailed you with a follow up.  Just so you are aware, [only one mobile device can be registered to Signal at a time](https://support.signal.org/hc/en-us/articles/213913358). If you've registered another device or phone with the same number, then that device will be available for Signal messaging and calling. In the future, make sure to fill out the issue template and provide a debug log.
