### ISSUE TITLE
Change the registered number/migrate to another number

### ISSUE THREAD

**Issue by rHohith** [signalapp/Signal-Android#7548]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by piratenpanda** [comment]
Would be nice if you would not just post an empty bug template. Also what stops you from unregistering and registering (last menu entry in the settings) with a different number on the same phone?
