### ISSUE TITLE
Signal crashes when trying to zoom/pan large image

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#7549]
I have:
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
After sending a large jpg file from my DSLR and zooming in it crashes signal. Zooming and panning is really really slow also.

### Steps to reproduce
- Send large image
- click on it
- zoom or try moving it around

**Actual result:**

Signal crashes. Seems related to:
java.lang.RuntimeException: Canvas: trying to draw too large(106614168bytes) bitmap.

**Expected result:** 

Scrolling and zooming should be smooth, signal should not crash

### Device info
**Device:** Google nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.16.9

### Link to debug log
https://hastebin.com/henobamiqo

**Comment by 2-4601** [comment]
The stuttering is most likely duplicate of #7208. However I never experienced a crash. In any case the slowness should be fixed in 4.17.x.

**Comment by piratenpanda** [comment]
Hastebin seems to be down

**Comment by piratenpanda** [comment]
Seems to be fixed with 4.17.5
