### ISSUE TITLE
4.17.4 crash when returning to vertical orientation 

### ISSUE THREAD

**Issue by riyapenn-signal** [signalapp/Signal-Android#7550]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when changing orientation from vertical > horizontal > veritcal

### Steps to reproduce
- open Signal with it in a vertical/page orientation
- rotate the phone to horizontal/landscape
- rotate back to vertical

**Actual result:** Crash
**Expected result:** No Crash

### Screenshots
N/A

### Device info

**Device:** LG Stylo 3 PLUS
**Android version:** 7.0
**Signal version:** 4.17.4

### Link to debug log
 https://debuglogs.org/51cd848db87006346c7d6fd168011461576647df1f6aafac4cf08544150093fd

**Comment by moxie0** [comment]
I'm unable to reproduce this. Please reopen with steps to reproduce from fresh install.
