### ISSUE TITLE
Signal crashes when trying to migrate database

### ISSUE THREAD

**Issue by mikebroome** [signalapp/Signal-Android#7551]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal 4.16.9 crashes while trying to update / migrate my database.

This has some similarities to issue #7386, but I assume it's different since 4.16.9 should include 0bbe83f.

### Steps to reproduce
- Installed latest Signal (4.16.9) from Google Play store.
  - unsure what version I was running before that
  - had been getting the banner telling me I needed to upgrade or Signal would stop working
- When launching Signal, get prompted for passphrase.
- Signal app starts migrating database, showing screen saying "Updating database..."
- Completion indicator gets to about 1/3 of the way across.
- Get system dialog saying "Unfortunately, Signal has Stopped."

### Device info

**Device:** LG G3
**Android version:** 4.4.2
**Signal version:** 4.16.9

### Link to debug log

https://gist.github.com/mikebroome/f7c66e6bf28be98c0f81004acfc14301

**Debug log notes:**
* log captured with `abd logcat`
* trimmed down to only the `org.thoughtcrime.securesms` and Signal PID lines

**Comment by mikebroome** [comment]
I was able to downgrade to Signal 4.15.5 (found at https://signal.org/android/apk/) which is working. That buys me some time.

**Comment by moxie-signal** [comment]
You running a custom ROM or rooted device or something? From the stack trace, it looks like your DB schema is somehow incorrect. There looks to be a row in the 'thread' table with a NULL value for the snippet_type column, which shouldn't be possible.

**Comment by ryannathans** [comment]
@moxie-signal Excuse my off-topic reply, but I couldn't help but notice you're on a brand new github account, with signal in your username, one commit, and have a username extremely similar to moxie0. Care to quench my curiosity?

**Comment by mikebroome** [comment]
Custom ROM: no.
Rooted device: yes.

**Comment by whitslack** [comment]
I have the same problem with 4.16.9, and I worked around it in the same way (by downgrading to 4.15.5 from the web site). I submitted this stack trace by email to support@whispersystems.org on 6 Mar but never heard anything back.

```
03-06 16:50:23.926  5993 17680 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
03-06 16:50:23.926  5993 17680 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5993
03-06 16:50:23.926  5993 17680 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherMigrationHelper.lambda$migrateCiphertext$3$SQLCipherMigrationHelper(SQLCipherMigrationHelper.java:139)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherMigrationHelper$$Lambda$3.apply(Unknown Source:14)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherMigrationHelper.copyTable(SQLCipherMigrationHelper.java:208)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherMigrationHelper.migrateCiphertext(SQLCipherMigrationHelper.java:137)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.onApplicationLevelUpgrade(DatabaseFactory.java:157)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.DatabaseUpgradeActivity$DatabaseUpgradeTask.doInBackground(DatabaseUpgradeActivity.java:188)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at org.thoughtcrime.securesms.DatabaseUpgradeActivity$DatabaseUpgradeTask.doInBackground(DatabaseUpgradeActivity.java:169)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-06 16:50:23.926  5993 17680 E AndroidRuntime: 	... 3 more
```

I've had the same database since the days of TextSecure. Is it possible that a schema migration was overlooked at some point, such that my schema does not match the expected schema?

**Comment by moxie0** [comment]
Wow I'm impressed, that's a suuuuuuper old database.
