### ISSUE TITLE
[Feature Request] Expose Read Receipt Time in message details

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7555]
It'd be pretty spiffy for read receipts to expose their time in the message details.

**Comment by RiseT** [comment]
While I can see many cases where read receipts are legitimate and useful (and argued correspondingly prior to their introduction), I'm not that sure about the precise reading time. It's just that I currently cannot imagine any practical use case for this that isn't related to some form of snooping. I might be wrong, though.

**Comment by jeremymasters** [comment]
Sent and received are already logged, so this seems like a natural progression, but if it isn't desired I will remain content. :)

**Comment by jlund-signal** [comment]
Thanks for the suggestion. This is working as designed, but you can continue discussing this on the [community forums](https://community.signalusers.org/) if you have any other ideas. We use GitHub to track bugs.
