### ISSUE TITLE
Signal required unlock in the morning for some reason

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7557]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal was locked after not using phone all night

### Steps to reproduce
- have fingerprint enabled
- let phone sit all night
- get group MMS in the night
- wake up in the morning
- turn on screen

**Actual result:** open signal, need to enter fingerprint, more signal downloading mms
**Expected result:** open signal, see message was delivered in the night

### Screenshots
None

### Device info
**Device:** galaxy s8
**Android version:** 8.0
**Signal version:** 4.17.5

### Link to debug log
https://debuglogs.org/e95b8d917bf04aa21503e984ed786be42eb1763c948ac4a3618add663be85241

**Comment by moxie0** [comment]
This is not unexpected behavior. Signal can only remain "unlocked" as long as the process is running. Android can (and will) kill the process at any time.
