### ISSUE TITLE
Large Encrypted Backup crashes Signal

### ISSUE THREAD

**Issue by danry25** [signalapp/Signal-Android#7560]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Importing a large Signal database (2.5GB, somewhere north of 132,000 messages) seems to consistently crash Signal. The last message # I see being imported is 132301 before Signal crashes.

### Steps to reproduce
- Export an encrypted backup with more than 132,000 messages
- Delete Signal & reinstall
- Import backup

**Actual result:** Signal crashes and prompts user to send a debug log to developer
**Expected result:** Messages and keypair should be imported (seems to work with smaller exports, eg: 500MB encrypted backup with 60k messages)

### Device info
**Device:** LG V30 H932
**Android version:** 7.1.2
**Signal version:** 4.17.5 (beta)

### Link to debug log
https://gist.github.com/danry25/9386f36686e0b03737eeb6d6da522355

**Comment by piratenpanda** [comment]
My file is 3.5GB and worked just fine

**Comment by danry25** [comment]
How many messages did your 3.5GB contain? I'm guessing based on the speed of backing up that the first 120k messages I have are plain text (as they backed up rapidly), while everything thereafter took overnight to archive as it was larger in size (whether that be pictures or files).

**Comment by piratenpanda** [comment]
Over 130k and it took like 30mins on my Nexus 5x

**Comment by danry25** [comment]
Did a fresh backup (took ~2 hours), tried to restore it on a spare Android I have (device info below), seems with this backup the crash occurs after processing message 132701. Will try restoring this backup on my LG V30 later today to see if its consistent.

Any tips on how to get more useful logs? My initial logcat was done by only displaying logs from the Signal process ID. Figure there has to be a better way, seeing the logs in other bug reports...

### Device info
**Device:** Samsung Galaxy S5 (Sprint) SM-G900P
**Android version:** 6.0.1 - Stock
**Signal version:** 4.17.5 (beta)

**Comment by moxie0** [comment]
Your backup file is corrupted, but I can't say how it happened. The restore process is crashing because it goes to read a frame size and gets back a negative number. It could be a bug in the export process or FS corruption. The fact that it's taking 2 hours to create the backup makes me think that something is very wrong, either in the code or on your device. I don't think it should take 2 hours to copy 2.5GB on disk.

**Comment by danry25** [comment]
Hmm, I wouldn't be terribly surprised if the filesystem were corrupt (or the NAND had some dead cells). Is there anything I can do to remove the damaged data from the backup? Its not the end of the world for me to lose some messages, but I'd like to keep my Signal keys & as many messages as I can get away with.

**Comment by moxie0** [comment]
It is possible, but you'd have to manually edit the file to remove the corrupt sections.

**Comment by moxie0** [comment]
@danry25 How "old" roughly would you say that the DB you're backing up / restoring is? That is to say, roughly how long have you been carrying forward the same signal install?

**Comment by danry25** [comment]
The DB has messages going back to at least February 2013, which'd mean I migrated across 3 different phones with the same DB. Pretty sure I did an encrypted export in 2014 (or sometime before #1705), and then in 2016 (approximately) I unregistered signal on my old phone, copied the app and data, and re-registered, preserving my data & keys. Not sure if the deregister & copy method works anymore...

On another note, will b9f99f99410562516ae17dbe6e58a0b94127a904 make it into Signal's Beta channel soonish? I'd love to try it!

**Comment by danry25** [comment]
@moxie0 Successfully migrated my database this morning after updating to the latest beta, really appreciate your patching of this bug!

On a sidenote, it seems in some groups with disappearing messages enabled there is a condition where after restoring the backup you'll automatically attach the media content that was sent your way during the backup.
