### ISSUE TITLE
[REQUEST] Own clipboard sharing PC<->mobile phone

### ISSUE THREAD

**Issue by Hexaae** [signalapp/Signal-Android#7561]
Please can you add a personal Clipboard sharing feature?
The idea is to send there all links, images, files for **personal** usage to easily open them from another of my devices with a Signal app installed (PC, Android, iPhone etc.). A personal clipboard to remove the need of installing other apps for sharing.
Typical usage: I've found an interesting link browsing on my mobile phone and I want to continue on my desktop/laptop PC, where I have a Signal app installed....
Would be very handy IMHO and a smart feature missing from other messaging systems.

**Comment by 2-4601** [comment]
Thanks for the suggestion. This feature has been in the works for a while and @Trolldemorted has spent time on it but I don't know the current status. In any case, it's coming some day...

**Comment by FeuRenard** [comment]
You can find more information about the feature suggestion here: https://github.com/signalapp/Signal-Android/pull/5905#issuecomment-264593896
