### ISSUE TITLE
Whole coversation timer leads to possible problems with simultaneity

### ISSUE THREAD

**Issue by kai-dj** [signalapp/Signal-Android#7562]
### Bug description
If person 1 sets the timer for messages to "off", it might be, that a message send simultaneously (or almost simultaneously) by person 2 ends up not disappearing (but person 2 assumes it would at the time).
 
### Steps to reproduce
- set timer to any value not "off"
- coversation partner would assume all messages disappear
- turn timer off right before partner sends a message

**Actual result:** 
- coversation partner doesn't realize timer is turned off fast enough - message is not disappearing

**possible solution:** 
- timer settings individual for each person
- feature for deleting messages on both devices (or set timer for messages already send)

### Device info
**Signal version:4.16.9**

**Comment by kai-dj** [comment]
…this is of cource also the case for iOS- or desktop-app.
Is there maybe a better place to file this issue. If so, can the thread be moved there?

**Comment by 2-4601** [comment]
The disappearing messages feature is not intended to handle cases such as the one you described:

https://signal.org/blog/disappearing-messages/
>Disappearing messages are a way for you and your friends to keep your message history tidy. They are a collaborative feature for conversations where all participants want to automate minimalist data hygiene, **not for situations where your contact is your adversary** — after all, if someone who receives a disappearing message really wants a record of it, they can always use another camera to take a photo of the screen before the message disappears.

If you want to discuss more https://community.signalusers.org/ is a good place to continue

**Comment by kai-dj** [comment]
…but the solution would be fairly simple. 
It would be a technical solution for a problem I otherwise would have to ask my conversation partner, to delete the message. I don't see why this flaw should stay then…

**Comment by kai-dj** [comment]
Also this might be an actual security issue. Maybe the disappearing messages feature is not intended to handle cases such as the one I described is a bad idea?

**Comment by kai-dj** [comment]
…opened thread at https://community.signalusers.org/

**Comment by kai-dj** [comment]
…sorry missclicked the thumb-down emoji ^^
