### ISSUE TITLE
Request to promote your project to over 10,000 people

### ISSUE THREAD

**Issue by yhaulez** [signalapp/Signal-Android#7564]
Hello
I am by name Nsikakabasi Charles
My steemit user is @yhaulez
I have been using your project and it's really amazing
And I would love to promote your project to over 10,000 people via facebook by running a promotion ads. I am here to request your permission to do so.

**Comment by 2-4601** [comment]
Hello,
This is a [bug tracker](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs) for the Signal Android client.
Not an advertisement platform or market place.
