### ISSUE TITLE
[Feature Request] SMS/Signal Notifications profile

### ISSUE THREAD

**Issue by xJMV** [signalapp/Signal-Android#7567]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When making Signal as default SMS manager, there is no way to have default SMS notification (Android settings) to be enforced and having the Signal notification settings just for Signal message/call only. 

### Steps to reproduce
- Install Signal and enable SMS support.

**Actual result:** The same 
**Expected result:** Use Android notification profile for regular SMS/MMS and use Signal settings for secure messages / call. I use Signal with a limited number of people and I wish to know the difference between regular SMS or secured one by the ringtone (secure messages are mostly more urgent than other SMS).

### Screenshots
 None

### Device info

**Device:** BlackBerry Motion
**Android version:** 7.1.2
**Signal version:** 4.16.9

### Link to debug log
None

**Comment by RichJeanes** [comment]
This could be accomplished by using Android's Notification Channels, at least in newer versions of Android.

The current option would be to use the custom, per-person ringtone in the Conversation Settings to distinguish your Signal conversations from your SMS ones. Though this solution doesn't really scale at all, it shouldn't be too much of a hassle with a small number of contacts.

**Comment by xJMV** [comment]
Actually I returned SMS to Android's native app... that fixes it for now in a simple way.

But I feel that many users may like to be able to set a sound for SMS, Signal and Signal voice call to be able to distinguish them... Anyway, this is just an idea, let's see if this can bring something good...

**Comment by jlund-signal** [comment]
Thanks for the suggestion. We use GitHub to track bugs, but you can discuss this idea in the [Feature Requests](https://community.signalusers.org/c/feature-requests) section of the community forums.
