### ISSUE TITLE
[Bug (?)] Group Received Check Marks Status for Quickest Message, not Slowest

### ISSUE THREAD

**Issue by mpsdskd** [signalapp/Signal-Android#7570]
Is this an issue for Signal-Android or is this a protocol-thing, as this also occurs in Signal-Desktop?

### Bug description
When sending group messages the Received Check marks go blue, if only one group member read the message. I find it more logical, if they only become blue, once EVERY group member read the messages.

### Steps to reproduce
- Send message in group
- look at received/read check marks

**Actual result:** check marks show status for the "quickest" message
**Expected result:** Should only become eg. blue, once EVERY group member read the messages.

My gf says Whatsapp behaves as stated in my expected results, so that's perhaps a reason to behave this way as well.

### Device info
Android and Linux

- [x] searched open and closed issues for duplicates

**Comment by jeremymasters** [comment]
Works as designed.  I call it "optimistic read receipts".  It actually is nice to know, "hey, at least 1 person read this message already" by looking at the check marks.  With Whatsapp, you don't know if anyone at all has read it until all have read it based on the check marks.

**Comment by FeuRenard** [comment]
#2373 requested the same.

**Comment by mpsdskd** [comment]
Damn, did not find that one. (I must say I did not go back to 2015-01)

So sounds like this behavior is intended.
I for one find it unintuitive and would rather make sure at a glance, that everyone got the message (especially in small groups of 3-5 Persons -> family).
