### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#7571]
Write on signal.org some documents were you say how Signal protect messages and infos on the phone. There are a lot of info on how signal protect messages during the transit on the internet but there is nothing on how you protect on phones :)

**Comment by jlund-signal** [comment]
This is an issue tracker for bugs in the Android application. It would be helpful if you didn't delete the issue template in the future. If you feel like you're unable to make an idea fit within the confines of the template, that might be a sign that you are about to submit something here that isn't a bug. :)

The community forum is a better place for this type of discussion. Thanks!
