### ISSUE TITLE
Camera permission required for audio call

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7573]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Camera permission is required even for a basic audio call.

### Steps to reproduce
- Disable camera permission
- Hit call button to a signal user

**Actual result:** "To call, Signal needs access to your microphone and camera."
**Expected result:** Signal should not need the Camera permission to make a basic audio call. If the user hits the video button while already in a call, it can then ask for camera permission if not already enabled.

### Device info

**Device:** Samsung
**Android version:** 6.0.1
**Signal version:** 4.16.9

**Comment by moxie0** [comment]
Sorry but there's no other way to do it with webrtc
