### ISSUE TITLE
[FEATURE REQUEST] Set chat preference where no users can screenshot chat

### ISSUE THREAD

**Issue by AccountNameHere** [signalapp/Signal-Android#7582]
Please make it so the other user is not able to screenshot the chat or at least have a snapchat style notification when someone does screenshot the chat.

**Comment by leonardoporpora** [comment]
Use the community to speak about this. https://whispersystems.discoursehosting.net
Ps. The other user could always make a photo with another phone

**Comment by FeuRenard** [comment]
Information about screenshot is tracked in  #5483

**Comment by johanw666** [comment]
That's a hacking contest you cannot win: http://repo.xposed.info/module/fi.veetipaananen.android.disableflagsecure

**Comment by AccountNameHere** [comment]
Yes, I know it's not foolproof... But for the "average" user.  Disabling the ability or setting the chat room to no screenshots is enough to mitigate the risks.  Or at least have a notification like snapchat that someone took the screenshot.

**Comment by jlund-signal** [comment]
This is an issue tracker for bugs in the Android application. It is not for questions, comments, or feature requests. The community forum has several existing posts that discuss screenshot protection, and you're welcome to continue the conversation there. Thanks!
