### ISSUE TITLE
Latest version of signal is not available for me but can be downloaded through YALP.

### ISSUE THREAD

**Issue by YiiKuoChong** [signalapp/Signal-Android#7583]
The latest version available for me on Play Store is version 4.16.9, but when I download from YALP store it shows an update for version 4.17.5 . This new update includes new features such as the registration lock.

Signal Version Available for Google Play : 4.16.9

Signal Version downloaded from YALP store : 4.17.5

Additional information :

Country : Malaysia
OS : Stock Android 7.0 (Lenovo P2)
Sample size : 1

Why is the latest update not available for me? Region?

I will include image when I am on a computer.

**Comment by RichJeanes** [comment]
I'm pretty sure that the only official distribution points for Signal are the Signal website and the Google Play Store (the preferred method). It's possible that it's some third party building from the GitHub repository and uploading to YALP.

If you do not have access to the Google Play Store, your best options are to either build from the GitHub repo directly (which means no auto update mechanism, risk of your own signing keys being compromised, etc.) or to install from the Signal website (which is apparently not kept up with the Google Play build version...) (See [this comment](https://github.com/signalapp/Signal-Android/issues/127#issuecomment-286223680) on #127).

**Comment by YiiKuoChong** [comment]
@RichJeanes Please read more about what YALP Store is. 

Basically, its an alternative client for Google Play. All the data loaded are from Google servers. Therefore there should not be any difference in version number, unless Google or the developer is delaying updates for certain regions. 

YALP uses built in credentials for all users, so that people can use Google Play without logging in to Google Play.
I use my own account which is only used in Malaysia while the public YALP account is used by people all over the world. What I want to say is that the updates are not available to users in certain region. 

The only not google connection YALP do is to obtain login tokens (afaik)!.

**Comment by RichJeanes** [comment]
The reason I say that it seems like it might be unofficial is that the current stable release on the US Play Store is 4.16.9. I assume that 4.17.5 is the current version on the Play Store beta channel since that is the latest on the GitHub repository, but I can't say since I'm not on the Play Store beta channel.

I suppose another possible explanation is that whatever Play Store crawler that YALP uses does not recognize the difference between stable and beta channels. That would explain the difference if 4.17.5 is currently on the beta channel of the Play Store.

**Comment by jlund-signal** [comment]
Signal uses [a staged rollout process](https://support.google.com/googleplay/android-developer/answer/6346149) for production releases through Google Play.

**Comment by YiiKuoChong** [comment]
@RichJeanes 

Ah that clears it up. You made it sounds like YALP is a totally diffrent store. I thought signal is updated in Google Play.
