### ISSUE TITLE
Signal Desktop and Android app are not updating read messages that were read on phone

### ISSUE THREAD

**Issue by osrambilux** [signalapp/Signal-Android#7585]
I have:
- [ X] searched open and closed issues for duplicates
- [ X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce

- Receive message on phone.
- Read message on phone in Signal app.
- See phone notification for new message still in pull down notification area after reading.
- Open Signal Desktop.
- See unread message indicator for messages you read on phone.
- Problem started with Signal Desktop after transition to stand alone application.

**Actual result:**
After messages are read on phone they will continue to be shown as unread in Android pull-down notification area and Signal Desktop.

**Expected result:** 
When messages are read on phone they should no longer be shown as unread in notification area or Signal Desktop.

### Device info

**Device:** 
Nexus 5X

**Android version:** 
7.1.2

**Signal version:** 
Signal phone 4.16.9
Signal Desktop 1.6.1

**Operating System**
Ubuntu Mate 16.04.4 LTS 64-bit

### Link to debug log
Signal App -- https://hastebin.com/kavedapidi
Signal Desktop -- https://debuglogs.org/cdd840fb85227b06f214b04ec6438ba20ece54671abc9c0f3b10597d505a8d91

**Comment by moxie0** [comment]
The fact that the notification is still visible after opening the conversation suggests that something is very wrong on the Android side. However, this debug log does not cover any conversation open actions, and I can't reproduce this, so there is no action I can take. Please reopen if you can provide a debug log that covers the relevant action. Thanks!

**Comment by osrambilux** [comment]
I've saved four debug logs.  One from Signal Desktop and Signal Android immediately after opening each respective app and one from each after reading messages on Android app.  I hope this provides what you need.  

Signal Android before and after:

https://debuglogs.org/1f1130e62899c632411052daa3db8692504bcd26d07b2e560c6f219f8bba1623

https://debuglogs.org/6fbb2b4c0b9171993eca4487a4fef2993312d52d2feb4b55254e991838352d98

Signal Desktop before and after:

https://debuglogs.org/c7fd20084294d8d8b4cf5e75aa1116b61199840a844db18a7050513280c2e371

https://debuglogs.org/ddd548f540398bdce2929a95f6fbaf77eb3e39db54e82c2cd057ea42c1a382a2
