### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [signalapp/Signal-Android#7588]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by leonardoporpora** [comment]
Hey @jbeguna04 :+1: this is not a forum. For this type of discussion you should open a discussion here https://whispersystems.discoursehosting.net
