### ISSUE TITLE
(Some?) jpeg images do not render in Media preview

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#7595]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
jpeg images are not correctly displayed in the 'Media preview' screen. The screen is black. I'm not sure whether this is the case for all jpeg images, some images show up correctly.

### Steps to reproduce
- Select a conversation that contains jpeg images
- Select 'All Media'
- Select one of the previewed jpeg images

**Actual result:** A black screen with the title 'Media preview' appears.
**Expected result:** The image should be previewed in the 'Media preview' screen

### Link to debug log
This debug log contains sqlcipher related stacktraces and jpeg related messages:
https://debuglogs.org/6cb687b3448a2f19da0ee527c49ce85f95294e22458dd3ffaa396bfc9b54df04

**Comment by Hormesis** [comment]
I have this problem as well, but only in group conversations, and only on inbound images. Images that I've added to the conversation display fine.

This problem has existed for many versions and I've reproduced it across 5+ different devices.

**Comment by Hormesis** [comment]
Steps to reproduce: create a group, have one of your friends post an image. Go to the conversation menu, click All Media, click on the image and it's blank.

**Comment by janvlug** [comment]
For all media that I checked I can confirm @Hormesis' statement that this happens only for inbound images in group conversations.

**Comment by FeuRenard** [comment]
Could you please make sure you don't experience #7384 or #7385, which both are not jpeg related?

**Comment by janvlug** [comment]
Although I'm not completely sure, indeed, I expect this to be a duplicate of #7384.
I leave it up to the devs to decide whether they want to close this bug as a duplicate, or to leave it open until we're sure it is fixed with #7387.

**Comment by motatuc** [comment]
I experience the same. Seems to be a dup of #7384 but #7384 is closed. So I think it might be good to leave this bug open and fix it of course.

**Comment by FeuRenard** [comment]
I opened #7609 which is intended to supersede #7384. So this issue can be closed in favor of #7609.

**Comment by janvlug** [comment]
Closed as duplicate of #7609, as suggested by @FeuRenard.
