### ISSUE TITLE
Signal crashes after importing Backup: Couldn't open signal.db for writing

### ISSUE THREAD

**Issue by ckujau** [signalapp/Signal-Android#7596]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I had Signal Beta running for over a year on a Nexus 5X. That phone died a few days ago and I have now a Sony Xperia XZs with Android 8.0.0. Installed Signal and set it up with my phone number, but then realized that there is no "import" function to import the backups from the newly commited backups function (commit 24e573e537639f6f8ff40fd774cf9ff079bbacce ("Support for full backup/restore to sdcard"), I assume).

After copying the Signal backups into `/mnt/sdcard/Signal/Backups` I went to `App Info` and `Clear Data` on Signal. Started Signal and now Signal was able to import the ~1 GB encrypted backup file and Signal appeared to work. Linked a Signal v1.7.0-beta.2 desktop (Linux) instance to it and both Signal on Android and on the Desktop continued to work for a few hours. But then the "Signal has stopped" screens kept popping up (even though I wasn't even using Signal actively). Now I cannot start Signal on Android anymore, every attempt to start it gives another "Signal has stopped" screen (which goes away very quickly and one has to be very quick to hit the "Send feedback" button.

### Steps to reproduce

1. Start Signal
2. `Signal has stopped` window appears.

### Device info
**Device:** Sony Xperia XZs Dual-SIM (G8232)
**Android version:** 8.0.0
**Signal version:** 4.18.0

### Link to debug log
[adb logcat](https://paste.fedoraproject.org/paste/-H4CVqxe~MODryQqScmJgw). The important part may be:

```
E SQLiteOpenHelper: Couldn't open signal.db for writing (will try read-only):
E SQLiteOpenHelper: net.sqlcipher.database.SQLiteException: duplicate column name: width: ALTER TABLE part ADD COLUMN width INTEGER DEFAULT 0
E SQLiteOpenHelper:     at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
E SQLiteOpenHelper:     at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
E SQLiteOpenHelper:     at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.onUpgrade(SQLCipherOpenHelper.java:166)
E SQLiteOpenHelper:     at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:173)
E SQLiteOpenHelper:     at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:227)
E SQLiteOpenHelper:     at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
E SQLiteOpenHelper:     at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:181)
E SQLiteOpenHelper:     at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:668)
E SQLiteOpenHelper:     at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
E SQLiteOpenHelper:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E SQLiteOpenHelper:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E SQLiteOpenHelper:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by moxie0** [comment]
ah bummer, I think I see what happened. If you start that process over with 2c82b3610d2f942ae483b360f7facb7da15ad5ed I think it should work. Thanks for being a beta tester!

**Comment by ckujau** [comment]
Did that just now with v4.18.0 (thanks for the frequent releases!), imported the backups, sent and received a few messages, no crashes so far! \o/  Thanks so much!
