### ISSUE TITLE
Linking devices fails if Signal cannot utilize mobile device's camera

### ISSUE THREAD

**Issue by sampablokuper** [signalapp/Signal-Android#7601]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The issue is as summarised in the title of this bug report, and is already described in detail [here](https://github.com/signalapp/Signal-Android/issues/5153#issuecomment-230594440).

(Essentially, this bug report is a duplicate of #5153, as - irritatingly - required by #7598.)

### Steps to reproduce
- See [here](https://github.com/signalapp/Signal-Android/issues/5153#issuecomment-230594440).

**Actual result:**

Signal cannot link Android device to PC.

**Expected result:**

Signal can link Android device to PC.

### Device info

AFAICT, this affects all versions of Signal for Android since the linking feature was introduced, irrespective of the device and Android version.

### Link to debug log

N/A.

**Comment by robfuscator** [comment]
I was looking at #5153 and it looked promising when the re-opening happened but then it got closed and again.
I don't have cameras in my phone and I think it's big con for a privacy focused messaging app to require the user to possess a camera in his*her phone in order to be able to link the desktop app. I suggest adding a text-based linking option.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
