### ISSUE TITLE
Groups: No way to hide the "make your profile name and photo visible to the group" nag message

### ISSUE THREAD

**Issue by Natanji** [signalapp/Signal-Android#7605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Re-opening of #6927 after the spring cleaning since the issue still exists. In a group conversation, the top 8th of the screen will be taken up by a message with white text and blue background with the question "Make your profile name and photo visible to the group?". Tapping on the message will bring up a dialogue asking "Do you want to make your profile name and photo visible to all current and future members of this group?". There are two options presented: "Cancel" and "Make visible". As expected, the "Make visible" makes the own profile visible to all users; but the "Cancel" button is non-functional and does not remove the message. There is also no other way to remove it outside of this dialogue.

### Steps to reproduce
- Open a new group conversation
- Tap on the message on top
- Press "Cancel"

**Actual result:** The profile is not shared to the group and the message keeps the top part of the conversation occupied at all times with no way to remove it.
**Expected result:** The profile is not shared to the group and the message is dismissed.

### Device info
**Device:** Oneplus 3
**Android version:** 8.0.0
**Signal version:** 4.17.5

### Link to debug log
Not relevant

**Comment by moxie0** [comment]
Thanks but this issue tracker is only for existing functionality that does not work as intended. Bugs. If there is existing functionality that works, but you would like it to work differently, please use the discussion forums for that. Thanks!

**Comment by Natanji** [comment]
Okay, there was no way for me to understand that this was intentional behaviour. I would expect "Cancel" to mean that the user doesn't want to share the profile, but apparently you intentionally want it to leave the message.
