### ISSUE TITLE
Adaptive icons do not work.

### ISSUE THREAD

**Issue by Stanzilla** [signalapp/Signal-Android#7607]
Tested on a Pixel XL with Android 8.1

https://github.com/signalapp/Signal-Android/issues/6511 should be reopened.

**Comment by cascheberg** [comment]
#7373 has some more information regarding this issue, including some relevant steps on how to fix it.

**Comment by moxie0** [comment]
It looks like this will only work for targetSdk 26+, which is not going to happen for a while. We can revisit once we're at that API level, but feel free to reopen if I've missed something and there's a way to do this at our current targetSdk. Thanks!

**Comment by Stanzilla** [comment]
@moxie0 this could become a problem, Google is requiring apps to target at least 26 starting November. See https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by MariusVolkhart** [comment]
Hi @moxie0,

An application does not have to set `targetSdk` to `26`, however, it must be compiled with at least SDK 26 (which Signal is 🎉 ). In fact, Google Developer Advocate Ian Lake summarizes this in a [blog post](https://medium.com/@ianhlake/vectordrawable-adaptive-icons-3fed3d3205b5)

> Note: you do not need to target API 26 to provide an adaptive icon — only compile against it. Users will benefit from your work even as you work through other behavior changes.

I triaged this issue today and it comes down to several things.

1. Devices that specify the build flag declaring that they want circular icons (emulators, Pixel, etc.), will always load the value from `android:roundIcon` in `AndroidManifest.xml`. Signal defines an `adaptive-icon` (`icon.xml`) for `android:icon`, but not for `android:roundIcon`; it is always the round image (`icon_circle.png`), so even devices that are API 26 will only be able to load the round image. This can be solved easily with a resource alias for API 26 and higher.
1. The `icon.xml` is currently in `drawable-v26` but _must be_ in `drawable-anydpi*` in order for it to be chosen over the device-specific density modifier (`xhdpi`, etc). 
1. The current launcher icons are not sized in a way that meets the adaptive icon requirements. This leads to rendering problems, as seen in these screenshots.
<img width="60" alt="screen shot 2018-04-21 at 17 28 20" src="https://user-images.githubusercontent.com/1709517/39089293-8e7fa282-4589-11e8-9d2f-688930ec6f9e.png">
<img width="62" alt="screen shot 2018-04-21 at 17 28 13" src="https://user-images.githubusercontent.com/1709517/39089294-8e919ece-4589-11e8-8df3-5a8e608ff976.png">
<img width="58" alt="screen shot 2018-04-21 at 17 27 56" src="https://user-images.githubusercontent.com/1709517/39089295-8ea1252e-4589-11e8-9a26-47b67cf7105b.png">
<img width="62" alt="screen shot 2018-04-21 at 17 27 46" src="https://user-images.githubusercontent.com/1709517/39089296-8eaf1b3e-4589-11e8-8824-462aafe50a3b.png">

I was able to get adaptive icons to render nicely by making changes 1 & 2, and adding a new vector drawable as the foreground layer.
<img width="114" alt="screen shot 2018-04-21 at 16 28 41" src="https://user-images.githubusercontent.com/1709517/39089315-c03ba9c4-4589-11e8-85d5-42fb60102e9e.png">
<img width="112" alt="screen shot 2018-04-21 at 16 28 18" src="https://user-images.githubusercontent.com/1709517/39089316-c052901c-4589-11e8-9331-6f17b86aafc1.png">
<img width="116" alt="screen shot 2018-04-21 at 16 28 01" src="https://user-images.githubusercontent.com/1709517/39089317-c0632fe4-4589-11e8-9d9b-549e26321580.png">
<img width="120" alt="screen shot 2018-04-21 at 16 27 31" src="https://user-images.githubusercontent.com/1709517/39089318-c075e738-4589-11e8-8c15-5d8438bf27f2.png">

However, this is the [wrong icon](https://github.com/signalapp/Signal-Design/tree/master/android/icons/app_icon)! Notice for example that the shadows are missing. I do not know where to find a vectorized original of the current logo. Additionally, I do not have any image editing tools beyond simple SVG editors. From reading through #5936 I see that @liliakai and @iadmir were heavily involved in the logo design, and the in #6189 the new `png`s were added, but I did not see a vectorized copy of the current logo anywhere.

I would like to pursue fixing this, but without the ability to create appropriately sized images, it is rather impractical for me to do so.

Related issues:
#6511 was recently closed as part of the issue cleanup, but had previously been reopened by @moxie0. It contains discussion on the original implementation and some reports of it working incorrectly.

**Comment by michaelkirk** [comment]
Is this helpful?  https://github.com/signalapp/Signal-Design/tree/master/android/icons/app_icon

**Comment by MariusVolkhart** [comment]
Thanks @michaelkirk! I only looked at the raw file, not the material design file 🤦‍♂️ I think that's all I need

**Comment by Stanzilla** [comment]
Fixed by https://github.com/signalapp/Signal-Android/pull/7867 which is in release 4.21 which is currently in beta. Not sure how you guys handle that, do you keep issues open until a release version with the fix is shipped? @moxie0 @greyson-signal

**Comment by greyson-signal** [comment]
We can close it, thanks for the reminder!
