### ISSUE TITLE
Incoming group image/video not displayed when selected in "All media"

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7609]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Incoming images or videos in groups are not displayed in media preview when they are selected in "All media".

### Steps to reproduce
- Receive an image or video in a group.
- Open "All media" for this group.
- Tap on a received/incoming image or video.

**Actual result:** Black screen with generic title is shown. No swiping is possible.
**Expected result:** Selected media item is shown with correct title. I can swipe to reach other images/videos.

### Screenshots
opening media from "all media"
![screenshot_20180403-112631](https://user-images.githubusercontent.com/16167751/38241472-9eaab5bc-3732-11e8-8c69-5ba8eb611128.png)
opening media from conversation
![screenshot_20180403-112622](https://user-images.githubusercontent.com/16167751/38241476-a198fe1e-3732-11e8-8dd2-46fef82a7398.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.18.0

### Link to debug log
I intentionally omit a debug log because this issue is easily and reliably reproducible.

### References

- legacy issue: #7384
- Fix: #7387

**Comment by Hormesis** [comment]
If anyone needs more information on this, I'm happy to help. I've reproduced it across 5+ devices.

**Comment by FeuRenard** [comment]
I think I figured out the underlying issue and proposed a fix in #7387. If you had the ability to test the PR I would highly appreciate your help :slightly_smiling_face:. Otherwise I can test it myself tomorrow.

**Comment by Hormesis** [comment]
I don't know how to compile my own build, otherwise I would gladly test.
