### ISSUE TITLE
Gendered emoji need multiple backspace taps for deletion

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7611]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using emojis there are two types of backspace buttons you can use for removing them: the one from the emoji drawer and the one from your keyboard.

Using gendered (male/female) emoji like 🧜 shows different behaviours of the backspace buttons. I have to press the backspace button of my keyboard four times to make the emoji disappear. With the backspace button from the emoji drawer it disappears after one tap (expected behaviour).

This issue may be related to #6676. Threema shows the exact same behaviour, WhatsApp needs three taps for deletion.

### Steps to reproduce
- open a conversation
- open emoji drawer
- enter an emoji with male/female version in the input field

**Actual result:** I have to press the backspace button four times.
**Expected result:** Emoji disappears after one backspace tap.

### Screenshots
No meaningful screenshot possible. And I cannot record a video of my screen at the moment.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.18.0

### Link to debug log
I intentionally omit a debug log because this issue is easily and reliably reproducible.

### References
Legacy issue: #7288

**Comment by greyson-signal** [comment]
Can't repro this on 4.31.x.
