### ISSUE TITLE
InviteActivity does not adapt to dark theme

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7614]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The view where you can invite friends to Signal does not adapt to dark theme. Especially the view to select contacts to invite looks out of place in dark theme.

Legacy issue: #5407

### Steps to reproduce
- use dark theme
- open Signal
- choose "Invite friends" from the actionbar popup menu
- tap "Choose contacts" button

**Actual result:** The contact list is shown in light theme.
**Expected result:** The contact list is shown in dark theme and the rest of the activity is maybe colored accordingly.

### Screenshots
`InviteActivity` with dark theme, looks exactly like with light theme.
![screenshot_20180403-141034](https://user-images.githubusercontent.com/16167751/38249047-a46185d6-374a-11e8-9647-0f7797565c0c.png)
![screenshot_20180403-141054](https://user-images.githubusercontent.com/16167751/38249137-fdac80d2-374a-11e8-9757-63af5cdff15e.png)

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.18.0

### Link to debug log
I intentionally omit the debug log because the issue is easily and reliably reproducible.

**Comment by moxie0** [comment]
in 4.19.0

**Comment by Herohtar** [comment]
I just came here to report this issue in v4.48.17 and found this when checking for existing issues. It seems there was a regression at some point.

@greyson-signal
