### ISSUE TITLE
Cannot delete Signal contact

### ISSUE THREAD

**Issue by cornfeedhobo** [signalapp/Signal-Android#7615]
### Bug description
I encourage people to use Signal a lot, and run into a situation where someone has uninstalled the app without [unregistering](https://whispersystems.org/textsecure/unregister/) causing everyone else still using signal to be sending into, effectively, a black hole. This a bug because it is terrible UX.

### Steps to reproduce
- register phone A
- register phone B
- send "hello world" from B to A
- uninstall Signal on B
- wait N hours (really doesn't matter, but I bring it up because there should be a time based expiration or something)
- send "hello world" from A to B

### Desired result
B should receive the message in cleartext.

### Actual result
No reply "hello world" is received on B.

### Failed Solutions
This issue has been discussed before (#7210 and #4678). The following replies are really insufficient answers:
- Manually select SMS on every message
  - The argument is that defaulting to secure is imperative, but this is onerous beyond being used once or twice
- Guide your peer through [unregistering](https://whispersystems.org/textsecure/unregister/)
  - This is a tall order

### Purposed Solutions
The previous suggestion was to default to the last message type used (e.g. sms), and while this would alleviate the pain of the immediate issue, it still leaves the question "how do you know your peer no longer uses signal?".

Instead, because this issue can also lead to false security, attempting to send someone sensitive or urgent messages only to have them sent to an unknown black hole, I suggest that signal spend time solving that remaining question, how can you identify if someone has removed themselves from the ecosystem, and gracefully degrade their account.

**Comment by moxie0** [comment]
There is no way to determine when an app is uninstalled. This is the exact same experience you will find on any other messenger or service. The only thing we can do is garbage collect accounts more aggressively after inactivity, but then you run the risk of deleting accounts for infrequent users.

Since the existing functionality is working as intended, I'm going to close this here, but please open a discussion on the forums if you'd like to talk about ways to improve things. Thanks!

**Comment by cornfeedhobo** [comment]
@moxie0 I am not sure this would need a more aggressive garbage collection timetable, rather maybe just some simple engagement? After all, you have the user's phone number and could text them after 3 months of inactivity. In the most egregious case I dealt with, the intended recipient hadn't had signal on their phone for a year and had moved on to another phone entirely (albeit with the same phone number). I'd be happy to open a discussion on the forums, but I think that will just devolve into user rants, when it sounds like the issue is simply not being given the weight it's impact deserves.
