### ISSUE TITLE
Selecting status message with phone number is difficult

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7616]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Selecting group updates, session resets, timer messages (disappearing messages) or call logs does not work properly if the message contains a raw (linkified) phone number and you select by tapping over the text. Selecting outside the text works. Additionally it's possible to accidentally tap the phone number which opens the dialer of the phone app. Long-tapping the number - without already being in selection mode - doesn't enter the selection mode but opens the phone app, too.

### Steps to reproduce
- open a conversation with a Signal user, who is not a phone contact
- call the contact
- see the log with the contact's phone number
- long-tap another message
- tap the text of the status message

**Actual result:** Phone app is opened when you hit the number or the message is not selected.
**Expected result:** The status message gets selected. The number should not be linkified in selection mode, which is already done for normal messages.

### Screenshots
Tapping "Called" doesn't select the status message. Tapping the linkified number opens the phone app.
![screenshot_20180403-140438](https://user-images.githubusercontent.com/16167751/38249539-43814808-374c-11e8-9ac1-5b6ffdc31b7d.png)

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.18.0

### Link to debug log
I intentionally omit a debug log because this issue is reliably reproducible.

### References
- Legacy issue: #5691
- Fix: #5786

**Comment by FeuRenard** [comment]
This issue is still present in 4.24.1 for safety number change messages:
![screenshot_20180720-200730](https://user-images.githubusercontent.com/16167751/43018202-269747a8-8c59-11e8-993c-9069753860ec.png)

**Comment by greyson-signal** [comment]
I think UX changes have nullified this issue.
