### ISSUE TITLE
Change to system locale after device rotation

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7619]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Legacy issue:  #2815

When you rotate your device the locale Signal uses changes in some places to the system set language.

### Steps to reproduce
- Set a different locale than the one in system settings.
- Enable screen rotation in Android settings.
- Open Signal
- Open popup menu from the actionbar and see the entries use the Signal set language.
- Rotate your device.
- Open popup menu from the actionbar.

**Actual result:** Popup menu entries use the system language.
**Expected result:** Popup menu entries still use Signal's language.

### Screenshots
System locale: german, Signal locale: arabic
This is directly after opening Signal
![screenshot_20180403-154334](https://user-images.githubusercontent.com/16167751/38254130-bf01a6ce-3758-11e8-876e-85e7f3eb0ad1.png)
This is after rotation
![screenshot_20180403-154406](https://user-images.githubusercontent.com/16167751/38254137-c1b07ada-3758-11e8-8ec4-2e7d1b9c968d.png)
Note that the message time directly beneath the popup menu is in german while the other timestamps are in arabic. The timestamp locale changed to german after I scrolled the item out of view and back into view. But my conversation list was not long enough to change all visible timestamps.

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.18.0

### Link to debug log
I intentionally omit a debug log because this issue is easily and reliably reproducible. However there are logs in the legacy issue #2815.

**Comment by RiseT** [comment]
Potentially related: https://github.com/signalapp/Signal-Android/issues/5738
