### ISSUE TITLE
Cant send Media meddages over WiFi. Other phones running the same version of android over the same network do work. 

### ISSUE THREAD

**Issue by murdakah** [signalapp/Signal-Android#7622]
Hi Guys, 

So I'm having the exact same issue as in this post: 
https://github.com/signalapp/Signal-Android/issues/6188

But I can't visit the textsecure address at all, there is nothing returned from the server. This is a stock rom with no modifications, even after a factory reset the problem persists. Is it possible that I should be a tinfoil hat?

**Comment by moxie0** [comment]
Hey @murdakah, please do not delete the issue template when submitting issues here. If you have a question, please see the forums. If you would like to file a bug, please follow the template, and always include a debug log.  Thanks!

**Comment by murdakah** [comment]
Sorry but what is the point of submitting an issue? The previous guy's issue was resolved. I'll post the debug log if I can access it. And besides, everything was the same as with the other guy's post. Only the device changed.
