### ISSUE TITLE
Long conversations are difficult to use (search)

### ISSUE THREAD

**Issue by kofalt** [signalapp/Signal-Android#7626]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversations in Signal can go on for a long time - IIRC, the default is to retain the last 2000 messages which is quite a lot. Frequently I will need to recall some information from a week or months in the past, and in active threads (especially group chats) this basically leads to me giving up and asking the information again. It would be great to improve this.

This issue is a replacement for #1232 that follows the issue template as per the instructions in #7598.

From the original comment:

> For example if someone send me an address, but I can't remember the date, it would be helpful if I can press options/search and then have a text field (and a search button).

### Steps to reproduce
- Use signal for a long period
- Try to remember details of a past conversation more than ~30 messages ago

**Actual result:** App requires a lot of scrolling, potentially resetting to the bottom on new message (!)
**Expected result:** App could help me find relevant information 

### Screenshots
n/a

### Device info
**Device:** Any
**Android version:** 7.1.2
**Signal version:** 4.16.9

**Comment by PiCob** [comment]
I'd also love to see this, but still it's definitely a feature request (exactly like the original issue).
And the issue template clearly says "GitHub issues should only be used to track existing bugs in Signal".

**Comment by kofalt** [comment]
Yeah, I wasn't sure of the best path forward here since it's definitely a little column A / column B. The original ticket was open for 4 years, so presumably it was fine tracking it here, and after reading #7598 it seemed better to put in a few minutes to fill out the template rather than just dropping it on the floor. If the maintainers have a different view on things that's fine!

**Comment by Natanji** [comment]
You write "the default is to retain 2000 messages". Doesn't Signal retain all messages? I don't think that by default, anything is ever deleted, is there?

I agree though that this is a huge feature request and should be closed. The way I understand the Signal developers, they'd rather have users not store all messages forever but instead only keep the newest 500 messages or so - which isn't a lot, but realistically scrollable.

I think this is a design decision. If you want searchable conversations, WhatsApp offers this.

**Comment by lalunamel** [comment]
@kofalt This conversation, per https://github.com/signalapp/Signal-Android/issues/7598 as you linked, should probably exist in the [discussion forums](https://whispersystems.discoursehosting.net/). 

So, I'd say, create a thread in there and close this GitHub issue here. jlund has created a `Feature Request` category which you can use to label the discussion you create.

**Comment by sampablokuper** [comment]
@Natanji wrote:
> If you want searchable conversations, WhatsApp offers this.

Srsly?

One of the reasons Signal exists is so that people would have a more private and secure alternative to WhatsApp. Users shouldn't have to choose between privacy and security, versus being able to search within their own conversations.

**Comment by 2-4601** [comment]
Feature requests are supposed to go to the forum and there's a [thread for the search feature](https://community.signalusers.org/t/search-within-message-threads/93). It's a planned feature for sure.
