### ISSUE TITLE
Contact deleted from contacts and added later won't reappear in Signal (and explicit sync won't help)

### ISSUE THREAD

**Issue by hiviah** [signalapp/Signal-Android#7628]
- [x] I have searched open and closed issues for duplicates and also tried looking it up throught Google
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you already had a contact, deleted it from Contacts app, and added again, it won't reappear in Signal. My reason to do that was that I had 2 telephone numbers for a contact and while Telephone app chose one, Signal chose the other one. So I decided to delete contact and add just one phone number.

Explicit sync (via *Settings - Users and accounts - Account sync - three dots menu in right upper corner - Sync now*) won't add the contact. 

The contact won't be added even if you wait 3 days.

Adding the contact's phone number under a different name won't help either.

Killing Signal and starting it again, explicit sync inbetween, does not fix it either

### Steps to reproduce
- Have or add contant that was recognized by Signal. It might be necessary to have two or more phone numbers for contact like in my case.
- Delete the contact from Contacts application.
- Add the contact with one of the phone numbers that were used before.
- Note that if you have an existing conversation with the contact, the existing display name will be updated in conversation list under the new name you used when adding the contact again in Contacts app.
- However, when you tap the compose button (the pen icon lower right), you can't find the contact (neither searching nor scrolling through list).
- Explicit sync via *Settings - Users and contacts* like mentioned above doesn't help

**Actual result:** Contact can't be found either by search or scrolling through the contact list.

**Expected result:** Contact should reappear either after some time (scheduled sync) or explicit sync (via *Users and accounts - ... - Sync now*)

**Workaround:** let the contact send you message and keep it in among your existing conversations.

### Device info
**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.17.5

### Link to debug log

Apparently the application tries to sync, but only updates the display name, which is updated in the conversation list, but the contact is not added when searching for it or scrolling throught contacts. Relevant part of `adb logcat`:

    04-04 02:42:26.516 24988  1517 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
    04-04 02:42:26.516 24988  1517 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/directory/tokens
    04-04 02:42:29.659 24988  1517 W ContactsDatabase: Updating display name: +4207xxxxxxx1
    04-04 02:42:29.663 24988  1517 W ContactsDatabase: Updating display name: +4207xxxxxxx2

**Comment by Natanji** [comment]
Have you tried rebooting the phone and clearing cache (not data!) in the Signal app?

**Comment by FeuRenard** [comment]
Did you try resyncing your contacts with the following steps: https://support.signal.org/hc/en-us/articles/115005104688-How-do-I-edit-or-update-contacts-on-Signal-Android- ?

**Comment by p4nci** [comment]
this is an "old" issue (see [my comment](https://github.com/signalapp/Signal-Android/issues/5079#issuecomment-191702933)).
As workaround I use always this:
a) delete signal account (see [WhisperSystems#4338 (comment)](https://github.com/signalapp/Signal-Android/issues/4338#issuecomment-198157982)) and
b) refresh the contact list: tap pencil in the conversations list => refresh the contact list i.e. pull-to-refresh

**Comment by moxie0** [comment]
I think this should be fixed in 4.19.0, thanks for the well written bug report
