### ISSUE TITLE
Bad encrypted message recieved

### ISSUE THREAD

**Issue by shenki** [signalapp/Signal-Android#763]
Successfully exchanged a few push messages with a TextSecure 2 user. However, then messages stopped being correctly received by my client. They say "Bad encrypted message...". The same is happening on their end; my messages are being received but showing the same error message.

I'm on Nexus 5 running Android 4.4.2, with TextSecure 2.0.1 and now TextSecure 2.0.2. The bad encrypted message was seen with both version of TS.

A pastebin that includes at most one bad transfer is at http://hastebin.com/mobiqikegi

**Comment by fiesh** [comment]
For a TextSecure conversation of mine, this just started happening.  My peer can still read my messages, but all the messages she sends are just shown as *Bad encrypted message* for me.

The debug log is under https://gist.github.com/58bb3a19b59c291c6c33

**Comment by moxie0** [comment]
@fiesh Did one of you use titanium backup?

**Comment by voidzero** [comment]
@fiesh you can try to end the session on both ends (click the lock button, at the top right). That fixed it for me a good while ago.

**Comment by fiesh** [comment]
@moxie0 No, I don't even know what that is.
@voidzero Thank you, I'll try as soon as I get the chance!

**Comment by aetherfaerber** [comment]
Experiencing this issue on Signal 4.25.10 after restoring from a backup (oandbackup).
Strangely, I can communicate just fine with some contacts but with most I and them only get the “bad encrypted message” error.

**Comment by haffenloher** [comment]
@aetherfaerber let's not use the issue tracker for support questions. We'll be happy to help you over at the [community forum](https://community.signalusers.org/). No need to register, you can use your GitHub account to login. (Also, don't use oandbackup! Signal has its own backup functionality under Settings > Chats and media > Backups)
