### ISSUE TITLE
Hardware echo cancellation does not work on many devices

### ISSUE THREAD

**Issue by equaeghe** [signalapp/Signal-Android#7635]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
This is a revival of issue #6241. The posts there contain valuable information that cannot concisely be copied here. To deal with this issue, a whitelist was in place initially, which worked in the sense that only known ‘good’ devices would use built-in echo cancellation. Afterwards a switch was made to a blacklist, which was however not updated, leaving many people with non-usable call functionality.

*I suggest others experiencing this issue to wait with commenting until the developers have indicated what info they need. The material in issue #6241 should give them a good starting point.*

### Bug description
Echo cancellation does not work on multiple devices and for various Android versions.
For example, my Samsung GT-I9192 Galaxy S4 Mini Duos (serranodsxx) on Android 7.1.2 (LineageOS) is affected.

### Steps to reproduce
- call someone with Signal, using with affected device/OS (other party's device/OS seems irrelevant)
- have conversation

**Actual result:** Other party hears disturbing echo
**Expected result:** Other party does not hear disturbing echo

Depending on the device, the results vary when using headphones or not. On my device, the echo becomes *worse* when using headphones, so in a situation where the echo cannot be caused by sound being captured by my microphone. (My guess is that the echo cancellation functionality actually *adds* the echo.) For others, the echo disappears in this situation.

Suggested potential workarounds until the root cause can be addressed are to update the blacklist, to include an ‘advanced’ option that switches hardware echo cancellation on or off, or to disable echo cancellation when using headphones. A workaround is needed to avoid chasing users to Skype or so. (I managed to convince my family to switch to Signal and then the whitelist-to-blacklist move forced us back to Skype.)

### Device info

**Device:** Samsung GT-I9192 Galaxy S4 Mini Duos (serranodsxx)
**Android version:** 7.1.2
**Signal version:** 4.17.5

### Link to debug log

Not applicable.

**Comment by moxie0** [comment]
I'm happy to add devices to the blacklist, but only if we can confirm that they are a problem with stock Android.

**Comment by moxie0** [comment]
@sluger We'll need the ro.product.model string for that.

**Comment by sluger** [comment]
hi @moxie0, the ro.product.model is  `Moto G (5S) Plus`

**Comment by ADepic** [comment]
This effects Oneplus 2 running lineage os too.

This is a deal breaker and needs to be sorted out

**Comment by skrwt** [comment]
@moxie0 Please add the Moto G4 (running stock) to the blacklist as well. I've had several people complain that they hear an echo during signal calls. Using headphones fixes this problem.

The ro.product.model string is "Moto G4".
Thanks!

**Comment by breversa** [comment]
Echo happens too on the Samsung Galaxy S III : `ro.product.model=GT-I9300`

**Comment by 2-4601** [comment]
@breversa Which ROM are you running on that Samsung Galaxy S III?

**Comment by breversa** [comment]
The ROM is _LineageOS for MicroG_, taken from here : https://lineage.microg.org/

ROM download link :
https://download.lineage.microg.org/i9300/lineage-14.1-20180517-microG-i9300.zip

**Comment by ADepic** [comment]
I'm running that too - but I've had this problem since lineage plain version 14.1

**Comment by 2-4601** [comment]
You should confirm that it's also an issue with stock Android, otherwise it won't be blacklisted as said in https://github.com/signalapp/Signal-Android/issues/7635#issuecomment-378906186.

**Comment by abooij** [comment]
I think there are many people not running stock Android. Personally, I'm not willing to delete my entire Android installation merely because one app is not functioning as desired. In #6241, there was a proposal to add a setting to the configuration screen. Is this something that can be considered as a remedy for such situations?

**Comment by breversa** [comment]
I agree with @abooij : I'd love to confirm the bug, but I have no practical way to do it, as I'm no longer running stock on any device.
Is there any other was to test that ?

**Comment by equaeghe** [comment]
@breversa @abooij I have asked on an xda forum for my device whether someone with stock could test it. So far without response. But that is one thing you can try. Adding a setting would be ideal for me as well, but I understand that this goes against the design ideas of the developers (setting explosion).

**Comment by breversa** [comment]
What about a "testing" build, then, to allow volunteers like us to test the behaviour with and without AEC, report here, then blacklist or not in the "consumer" build ?

**Comment by b0m0x** [comment]
The Xiaomi Mi A1 is also affected by non-working echo cancellation on stock.
`ro.product.model=Mi A1`

**Comment by loxK** [comment]
I have the issue on Samsung Galaxy S7. I have a strong echo in each call, very difficult to use is these conditions 

SM-G630F
Android 8.0.0

**Comment by Riotous** [comment]
@moxie0 @greyson-signal Would it be possible to include an ‘advanced’ option that switches hardware echo cancellation on or off? That would help everybody instead of creating a blacklist entry for every major device out there. There's also countless numbers of lesser-used devices that might be affected but may never be reported because the likelihood of one of their users reporting the issue is much smaller.

**Comment by holdit** [comment]
As a custom ROM user, an option to disable this would be useful. I have this issue, but can't add my phone to the blacklist because it works well with the (very) outdated stock ROM.

**Comment by greyson-signal** [comment]
I don't anticipate adding any custom settings for hardware noise cancellation. We have a blacklist that we can add to as problem devices are confirmed.

**Comment by tootbrute** [comment]
This echo is an issue on Xiaomi Redmi Note 5 too.

My wife and I have extreme echo, audio feedback, screeching sound issues when talking to each other. We both use the same exact phone.
I am using Signal 4.33.5

Maybe the model number is this?
ro.product.model=Redmi Note 5
model name is: M1803E7SH
android: 8.1.0 (OPM1.171019.011)

This is my first post on GitHub. I am taking lots of flak for making my wife switch to signal so if you could help i'd be so grateful. 

what other information do you need?

**Comment by greyson-signal** [comment]
@tootbrute I'll add that model to the blacklist for 4.34.x. Thanks!

**Comment by mbellitti** [comment]
I also have that phone but my call quality is good. Is there some test I can run to help you?

**Comment by davidar** [comment]
The echo is also an issue with the `HUAWEI ATU-L22`

**Comment by Riotous** [comment]
> We have a blacklist that we can add to as problem devices are confirmed.

See, that's the thing @greyson-signal , not all problem devices will be confirmed. There's so many Android devices out there that you're only going to get the popular ones. Many people are using lower-cost devices due to the ridiculous prices new flagships are going for and there's new competitive low-cost models being rolled out by major OEMs every month. There's also a growing number of people who are importing Chinese phones or buying them from small retailers. Not to mention, there will be people who will be using countless burner phones, prepaid phones, and unlocked Android phones for privacy reasons. 

With so many Android phones out there, having an advanced setting to turn off hardware echo cancellation and adding an FAQ entry to show people how to fix the "echo, screeching, or feedback" ensures everybody can fix the problem on their own.

**Comment by letkan** [comment]
Please add `Mi A2 Lite` to the blacklist, I just tested the echo issue by replacing ro.product.model with `Mi A1` and there was no more echo, finally I can use Signal for calls on this phone.

**Comment by 3RMD** [comment]
Same thing with Xiaomi Mi A2. Tested on stock rom and various custom roms (conversation partner using iPhone).
Please add to blacklist.
Thanks in advance.

**Comment by JoaquimCSantos** [comment]
Xiaomi Mi A2 echo cancellation was resolved in the previous version. But with this last update it came back. Please add again to blacklist.
Thanks!

**Comment by fklrx345** [comment]
@greyson-signal Please also add ro.product.model = "Moto G4 Plus" to the HARDWARE_AEC_BLACKLIST. The "Moto G4" is on the list but the Moto G4 Plus is also affected with echos. Thank you!

**Comment by szabolcs-cs** [comment]
I have this problem with the Galaxy S4 (I9505) on Lineage OS. Could we get an option in Settings to switch to software echo cancellation manually?

**Comment by zjapske** [comment]
I have an galaxy s6 sm-920f, I tried multiple lineage os versions (14.1 16.0 and 17.1) all persons on the other side complained about hearing their own voice back with a small delay. I flashed my phone back to the stock rom call the echo is gone.

**Comment by Genis-Sage** [comment]
When I'm talking to my mom, I also hear my voice as an echo

my mother's phone: BQ Aquaris U Lite, stock android 7

**Comment by Salokyn** [comment]
Hi,

I get an echo (I ear my own voice) on a Oneplus 5 (ONEPLUS A5010, Oxygen OS 9.0.10) when calling a Oneplus 3 (ONEPLUS A3003, Oxygen OS 9.0.6).

It's fine on both sides when Oneplus 3 calls Oneplus 5.

**Comment by Lusofreak** [comment]
LG G7 THINQ ...

It's not a device issue if many devices are affected... it's a software issue, better coding/solution required...

**Comment by billie80** [comment]
Is it possible to add another device to the HARDWARE_AEC_BLACKLIST?
ro.product.model = SHIFT6mq

It is the newest device from a German manufacturer. They currently have problems with Hardware AEC. It would be great if it could be added to the list. Thank you very much in advance!

**Comment by Caerbannog** [comment]
> [...] not all problem devices will be confirmed. [...]
> With so many Android phones out there, having an advanced setting to turn off hardware echo cancellation and adding an FAQ entry  [...] 

Another solution could be to help inexperienced users to diagnose such issues and submit them.
Most VOIP solutions show a screen at random after calls for this purpose.

Something like a question "How was your call", with a thumb-up and a thumb-down buttons.
When the thumb-down is clicked, other questions can appear:
> What was the problem?
> - [ ] my correspondent heard an echo
> - [ ] other
>
> Click here to submit a report with your phone model

**Comment by jemaltz** [comment]
I believe that I am experiencing this issue with my Samsung s10e
ro.product.model: SM-G970F

The issue occurs when I am on speakerphone, and is generally triggered if an object/finger comes in close proximity to the noise cancelling microphone hole on the top of the phone

The issue remains until I switch speakerphone off

Thanks!

**Comment by JP2-S** [comment]
Echo from Samsung tab s5e SM-T720
