### ISSUE TITLE
After update, conversation list was shown empty for a while

### ISSUE THREAD

**Issue by Natanji** [signalapp/Signal-Android#7642]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to 4.18.1, Signal started with a completely empty Conversation list, which I found quite alarming and my first impulse was to think that all my messages and groups were borked by the update. I remember that for a fraction of a second, "Updating database" was shown before I saw that empty list.

When nothing was shown for a while, I asked a friend to send me a message on Signal. Upon returning to the phone, the conversation list was fully populated again. I don't know if the received message triggered this, or if just waiting for a while would have also done the trick. Perhaps a background operation was still running before it could be shown?

### Steps to reproduce
I cannot reproduce this since I already updated, and after receiving a single message, the conversations were shown again. But it happened directly after the update.

**Actual result:** After the update from 4.17.5, the conversation list was empty for a while, presumably until the first Signal message was received from a contact
**Expected result:** After the update, when the conversation list shows up it should not be empty, but should be populated like before the update.

### Device info
**Device:** Oneplus 3
**Android version:** 8.0.0
**Signal version:** 2.18.1

### Link to debug log
From immediately after the update when conversation list was empty:
https://debuglogs.org/c23ca4f42f7cc34ae069d223c07ff3ae6859ddf6131e3cb80e6d15d8ca6929bf
From a few minutes after the conversations were shown again:
https://debuglogs.org/2acf6dad2bdb690f60cf28fb0be00d104dc9635289d8feb5c586ff04410914bf

**Comment by moxie0** [comment]
I'm unable to reproduce this, so there's no action I can take. It looks like maybe things were just running slowly because a backup was in progress.

**Comment by haffenloher** [comment]
I can confirm this happened on my and on someone else's phone while a backup was in progress.

**Comment by Natanji** [comment]
There was definitely no backup in progress at the time, I checked that option immediately to see from which date my latest backup was and there was no such process running. It would be nice to display a loading animation instead of an empty list when things are just going slow.
