### ISSUE TITLE
Some emojis are not visible in dark theme

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#7644]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The emoji https://unicode-table.com/de/1F463/ and probably other are complete black and therefore not visible on a dark background.
See #6870

### Steps to reproduce
- Make sure you use Signal's emojis
- Switch to dark theme
- Open emoji drawer

**Actual result:** On the faces page between the nose and the single eye seems to be no emoji
**Expected result:** On the faces page between the nose and the single eye I can cleary see the footprints icon.

### Screenshots
![](https://user-images.githubusercontent.com/22525368/29239384-d6551a54-7f4d-11e7-89e1-0acee5d05387.png)

### Device info
**Device:** Oneplus X
**Android version:** 7.1.2 Lineageos 14.1
**Signal version:** 4.17.5

### Link to debug log
Haven't got an answer so far if I need to attach a debug log for pure UI bugs: https://github.com/signalapp/Signal-Android/issues/7598#issuecomment-378207453
Since this issue appears on all devices using Signal's dark theme, I don't think you need a log.

**Comment by mueller-ma** [comment]
The foot prints emoji seems to be fixed, but I found two other ones that are hard to recognize:
![screenshot_20180406-194237](https://user-images.githubusercontent.com/22525368/38435736-ed481bea-39d2-11e8-8409-3add5c03f41d.png)

**Comment by moxie0** [comment]
Ok thanks, I'm going to close this then. Those are some pretty obscure emoji, they're still visible, and the only solution is to make the dark theme something other than black, which knowing the dark theme folks, will cause ire. Thanks!

**Comment by mueller-ma** [comment]
@moxie0 Where do you pull the emojis? I will ask them if they could make both ones grey.

**Comment by moxie0** [comment]
Hah, well, you can certainly try asking Apple, but I wouldn't hold my breath =)
