### ISSUE TITLE
No video thumbnails

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#7645]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a revival of issue #5993.

No thumbnails are generated for messages including videos.

This time the receiving device was a Fairphone 2 which also is not affected by this issue.

According to the original issue this also affects Samsungs Galaxy S5, Galaxy J5 and Galaxy S7 edge but not a not otherwise specified Acer device.
I suspect this is only an issue with some Samsung devices but still hope for a solution or workaround.

### Steps to reproduce
- Send a message containing a video

**Actual result:** No video thumbnail generated.
**Expected result:** Video thumbnails should be available.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/9938306/38380490-2f02082c-3904-11e8-90a3-34ff494a10c3.png)

### Device info

**Device:** Samsung SM-G800F (kminiltexx)
**Android version:** 6.0.1
**Signal version:** 4.17.5

### Link to debug log

https://debuglogs.org/c68a0287ad17962297ae23199452699a59b55041f975315715c7e4a108be792e

**Comment by erik55** [comment]
I can not reproduce this with my phone.
Android 8.0.0
Signal 4.20.8
Phone Samsung Galaxy S7 SM-G930F

The only maybe connected problem I have is that videos lose file extension when forwarded from one chat to another #7783.

**Comment by greyson-signal** [comment]
I believe this has been resolved.
