### ISSUE TITLE
SMS reports failed, but message actually succeeds

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7646]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS is sent, then indicates failure. Receiving contact responds to SMS,indicating it succeeded.
There was an old incident about this but it contained a lot of dross, was cross-linked into insanity , so I created this.

### Steps to reproduce
- send message to contact (just certain ones) verizon, AT&T, iPhone,  Android, doesn't matter. No idea what about the contract triggers some contacts to have this. Makes me crazy!
- failed message with red indicator appears

**Actual result:** Contacts responds to SMS indicating it succeeded
**Expected result:** No failed indicator if SMS succeeds.

### Screenshots
![20180405_123303](https://user-images.githubusercontent.com/4967949/38384905-9c666b6a-38cd-11e8-848a-7dc7e99507b5.jpg)

### Device Info
**Device:** Samsung galaxy s8 (note 5, s7 also)
**Android version:** 6.0, 7.0, and now 8.0
**Signal version:** from 3.x until now

### Link to debug log
https://debuglogs.org/68cac3774e6305aebb67f4e27f1349957ae4dfa7ad22f6b8377b4e105f112b1d

**Comment by moxie0** [comment]
Who is your cell provider?

**Comment by jeremymasters** [comment]
Verizon

**Comment by moxie0** [comment]
Fixed in 4.19.0
