### ISSUE TITLE
Old backups not deleted when new backups are created

### ISSUE THREAD

**Issue by daivat15** [signalapp/Signal-Android#7650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Old backups not deleted when new backups are created.

### Steps to reproduce
- Enable local backups on the device.
- Let signal function normally for a few days to weeks.
- Go to the location where backups are being saved.

**Actual result:** All the backups done over the past few days to weeks are present.
**Expected result:** Only the most recent backup should be present. After creating a fresh backup, the old file should be deleted.

### Device info

**Device:** Redmi Note 4
**Android version:** 7.0.0
**Signal version:** 4.17.5

### Link to debug log

I am unsure when exactly Signal schedules backing up its messages. If someone could help me figure that out, I will post the debug log as soon as the backup is performed.

**Comment by moxie0** [comment]
It's designed to retain the latest 5 backups, but I've changed it to retain the latest 2 in 4.19.0
