### ISSUE TITLE
Resend button should resend to every group member

### ISSUE THREAD

**Issue by real-or-random** [signalapp/Signal-Android#7651]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a UX bug related to #2639 from 2015 but not identical. (There is a working PR #3383 from 2015  specifically for #2639, last rebased a year ago).

### Steps to reproduce
- Try to send message to group and make sure sending fails.
- Tap the message to enter what I call resend view.
- Tap the "send again" button for a few group members.

**Actual result:**
- As far as I can verify, the message is resent only to the group members for which the button is tapped. (This what makes it different from #2639. Back then the message was resent the the whole group every time a  resend button is tapped.)
-  Since the messages is marked successful after the first resend, after leaving the resend view, I cannot enter the view again.

**Expected result:** 
 - There should be a button "send again to whole group", which just does the right thing, i.e., send to members for which the message failed. Currently it's possible to resend only to specific members, but this is not an intended feature.
 - Moreover, the message should not be marked successful, as soon as it is resent successfully to only one member.

### Device info
**Device:** HTC 10
**Android version:** 7.0
**Signal version:** 4.18.1

### Link to debug log
I refuse. This would bother my friends in the group further.

**Comment by Tobi042** [comment]
On iOS, we have only one button for this:

![signal-2018-04-06-125054](https://user-images.githubusercontent.com/1289180/38417880-563bf45c-399a-11e8-9c20-a03b3a4f64c1.jpeg)

**Comment by greyson-signal** [comment]
This should be fixed as of 4.30.x.
