### ISSUE TITLE
Search in Signal history

### ISSUE THREAD

**Issue by michal-ruzicka** [signalapp/Signal-Android#7653]
The feature I am terribly missing on both desktop and Android Signal client (I do not know the iOS client) is the search functionality. I would really appreciate the feature of search in the history of signal (and SMS) messages saved on the client. Would be possible to add this feature? Thank you.

**Comment by nrizzio** [comment]
Hi @michal-ruzicka,

We don't use the issue tracker for bugs. This feature has been requested many times before and it is on the roadmap of the developers.

Please don't delete the issue template and don't ignore the contributing guidelines. If you want to talk about features, please see the [community forum](https://community.signalusers.org).

Thanks!

**Comment by michal-ruzicka** [comment]
Hi, @nrizzio, thank you for the clarification. I am sorry for the mess I made in the issue tracker.
