### ISSUE TITLE
Manual lock ability missing

### ISSUE THREAD

**Issue by TheBozzer** [signalapp/Signal-Android#7655]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing

Before the update to fingerprint lock, in the dropdown menu there was the option to lock signal manually.
Now there is only the ability to either wait for the minimum 1min timeout for signal to lock, or to use the notification area pulldown to relock, but this is only visible if you have notifications enabled.
This leaves signal open and not very secure....

### Steps to reproduce
- none....missing previous item in menu.

### Screenshots
None

### Device info

Samsung galaxy s7
**Android version:** 7.0
**Signal version:** 4.17.5

### Link to debug log
Not a logged bug

**Comment by greyson-signal** [comment]
The manual lock option is still there. Depending on your Android version, they may hide the extra action buttons. Swipe down on the notification with 2 fingers and you should see it.
