### ISSUE TITLE
Lock notification not shown after enabling screen lock

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#7659]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Enabling the screen lock should immediately show the lock notification. Currently, the lock notification is only visible after killing and restarting Signal. Until then there is no way to lock Signal manually.
Similarly, the lock notification should disappear immediately after disabling screen lock.

### Steps to reproduce, case 1
- **enable** screen lock from the menu
- check notifications

**Actual result:** no screen lock notification, need to kill and restart Signal
**Expected result:** screen lock notification should be shown

### Steps to reproduce, case 2
- **disable** screen lock from the menu
- check notifications

**Actual result:** screen lock notification still visible, need to kill and restart Signal
**Expected result:** screen lock notification should not be shown

### Device info

**Devices:** Android Virtual Device & Moto G5S
**Android version:** 7.1.1
**Signal version:** 4.18.1

### Link to debug log
I assume a debug log is not required, because this is consistently and easily reproducible on an Android Virtual Device

**Comment by lalunamel** [comment]
I'll look into this!

**Comment by lalunamel** [comment]
This behavior appears to be the result of `KeyCachingService` dropping intents with `CLEAR_KEY_EVENT` on the floor.  https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/service/KeyCachingService.java#L128
