### ISSUE TITLE
Minor issues regarding groups in contact search UI

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#7660]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The UI for searching contacts has some small issues when it comes to displaying groups, as can be seen in the screenshot.

### Steps to reproduce
- tap the pencil button to search contacts & groups

**Actual results:**
- the first group result is missing the character icon (only when contacts are shown in the result as well)
- group results are apparently ordered by group creation timestamp

**Expected result:**
- first group result should always have the character icon
- group results should be ordered alphabetically

### Screenshots
![signalgroupsearch](https://user-images.githubusercontent.com/3845150/38467125-632138a8-3b34-11e8-8efa-a89adcc8bfda.png)

### Device info
**Devices:** Android Virtual Device & Moto G5S
**Android version:** 7.1.1
**Signal version:** 4.18.1

### Link to debug log
I assume a debug log is not required, because this is consistently and easily reproducible on an Android Virtual Device

**Comment by greyson-signal** [comment]
This should be fixed.
