### ISSUE TITLE
Signal Desktop and Android app are not updating read messages that were read on phone

### ISSUE THREAD

**Issue by osrambilux** [signalapp/Signal-Android#7661]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Desktop and Android app are not updating read messages that were read on phone

### Steps to reproduce
-Receive message on phone.
-Read message on phone in Signal app.
-See phone notification for new message still in pull down notification area after reading.
-Open Signal Desktop.
-See unread message indicator for messages you read on phone.
-Problem started with Signal Desktop after transition to stand alone application.

**Actual result:**
After messages are read on phone they will continue to be shown as unread in Android pull-down notification area and Signal Desktop.

**Expected result:** 
When messages are read on phone they should no longer be shown as unread in notification area or Signal Desktop.

### Screenshots

-Device info-
Device:
Nexus 5X
Android version:
7.1.2
Signal version:
Signal phone 4.16.9
Signal Desktop 1.6.1
Operating System:
Ubuntu Mate 16.04.4 LTS 64-bit

### Link to debug log

Signal Android before and after:
https://debuglogs.org/1f1130e62899c632411052daa3db8692504bcd26d07b2e560c6f219f8bba1623

https://debuglogs.org/6fbb2b4c0b9171993eca4487a4fef2993312d52d2feb4b55254e991838352d98

Signal Desktop before and after:
https://debuglogs.org/c7fd20084294d8d8b4cf5e75aa1116b61199840a844db18a7050513280c2e371

https://debuglogs.org/ddd548f540398bdce2929a95f6fbaf77eb3e39db54e82c2cd057ea42c1a382a2

**Comment by a9e78rauijasdf** [comment]
Same thing here - on OP 5T with android 8 - and ubuntu 17.10 and ubuntu 18.04 - newest apps available used.

**Comment by gillesdutilh** [comment]
Same here on Android 6.0.1;:
1) Tap on message notification to read message in the app, 2) close app, 3) "unread" notification still there. After again going through 1 and 2, "unread" notification is gone.

**Comment by greyson-signal** [comment]
I can't reproduce this.
