### ISSUE TITLE
New contact from group not detected after saving it

### ISSUE THREAD

**Issue by elthanor** [signalapp/Signal-Android#7662]
### Bug description
When you have a group and somebody adds a new contact that you dont have then if you try to add this contact it will never appear as a "signal" contact. Meaning that the name wont appear but only the number in the group members list and when trying to send a new message it also wont appear on the top like the other signal contacts. The group and private chats work fine.

### Steps to reproduce
- Create group
- Someone from the group adds a contact you dont have
- Save this contact

**Actual result:** The contact appears as a non "signal" contact and you get the option of adding this new contact as if this phone number was never saved on the phone at all. Chatting works fine in all cases though
**Expected result:** Have the contact displayed as a signal contact and see 

### Device info

**Device:** Xiaomi Redmi Note 2
**Android version:** 5.0.2
**Signal version:** 4.17.5

### Link to debug log
https://debuglogs.org/bdacb23a8ada1a59ee70a31b89ff004fcdb61e18f6d5b826a7c9e6dad41ddffb

**Comment by moxie0** [comment]
Usually takes a second for Android to notify us of a contact db change event. What happens if you manually "refresh" in the compose screen?

**Comment by elthanor** [comment]
Hello @moxie0. Thanks for your reply. 
What do you mean refresh in the compose screen?

**Comment by haffenloher** [comment]
@elthanor 

1. open Signal
2. press the pencil button on the down right
3. pull down the contact list to refresh (or select "Refresh" from the menu)

**Comment by elthanor** [comment]
it works thanks. i am closing this issue
