### ISSUE TITLE
UI: Screen lock state is not updated in settings

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#7663]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a minor UI bug. If the Screen lock for screenshot is set to "on" it still shows "off" in the settings menu. I did not test if it applies to other options as well.

### Steps to reproduce
- Set Screen shot lock to "on"
- Leave Signal and Open Signal
- Go to settings
-> Screen lock off when it's actually on

**Actual result:** The settings show Screen lock off
**Expected result:** The settings should show Screen lock on

### Screenshots
![screenlock](https://user-images.githubusercontent.com/15171154/38512232-01237e34-3c2b-11e8-8c2b-9b46732877ba.jpg)

### Device info
**Signal version:** 4.18.2

**Comment by haffenloher** [comment]
"Screen lock off" in the summary isn't about the "Screen security" setting, but about the "Screen lock" setting ("Lock Signal access with Android screen lock or fingerprint").

**Comment by motatuc** [comment]
@haffenloher Thanks. I misinterpreted it.
