### ISSUE TITLE
Signal Lies About Message Received Time

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#7665]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal lies about message received time. Last night someone sent me a message at 0:33. I heard the notification on my phone at 03:23. When I checked the message details Signal reported that the message was received at 0:33.

### Steps to reproduce
Wait until you don't receive a message until several hours after sender sent it. Open message information and read received time. 

**Actual result:** Received time will show a couple of seconds after sent time, not the time your device actually received the message.

**Expected result:** Sent and received times should reflect the time the receiving device actually receives the message, and the actual time the sending device sent the message.

### Device info

**Device:** Google Pixel XL
**Android version:** 7.1.2
**Signal version:** 4.17.5

**Comment by micressor** [comment]
It would be great if it was possible to see the transmission time and the reception time.

**Comment by moxie0** [comment]
This is the intended functionality. We display Signal message timestamps as sent time. You can long press for details to see both sent and received time.

**Comment by jbaker6953** [comment]
It is the long-press times that are incorrect.

**Comment by jbaker6953** [comment]
To clarify, the received time on long-press reports that the message was received at 0:33 (three seconds after the sent time) when the actual received time was 03:23.

**Comment by moxie0** [comment]
That is the time the message was inserted into the local DB, as generated by the DB's NOW(). If the notification didn't appear until later, it's because either:

a) Android is throttling the notifications as some kind of doze-related thing.
b) Android killed the Signal process before the notification appeared.

**Comment by jbaker6953** [comment]
It's definitely not (b) because I don't have to enter a password to unlock Signal after getting the delayed notification. How can I debug (a) to verify this is what's happening? I've never seen this issue with other apps that pop notifications, like email, calendar appointments, Waze's scheduled drives, etc.

**Comment by jbaker6953** [comment]
There is something more going on. Yesterday, I was in a place with poor cell reception and a friend and I were sending messages back and forth with Signal. One message from him to me was delayed by 8 minutes, but the long-press received time showed 2 seconds after the sent time. The phone was in my hand with the screen on the whole time and battery optimization turned off. Not sure where to start to track this down. Sometimes it's a real issue when I miss important messages until hours later.

**Comment by jbaker6953** [comment]
This issue happened again the other night. My wife sent me a message and the message did not appear for almost 7 minutes. When it did appear it reported that it was received 6 minutes before it was actually received. My phone was on and active during that whole time, so it's not a sleep issue. I saved the debug log, which is visible at https://debuglogs.org/811c6ed80586d59696881f767438aa040bead5c28506099b8f4b79052a7d2c5f, but I don't know how to make heads or tails of it.
