### ISSUE TITLE
disappearing messages does not cover call logs

### ISSUE THREAD

**Issue by p4nci** [signalapp/Signal-Android#7667]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
legacy issue: #6879 related: #5628 
### Bug description

from legacy issue:
The awesome "disappearing messages" feature does not cover call notifications (`MessageRecord_called_s` and `MessageRecord_s_called_you`). IMHO they should disappear the same way other messages do. For one, these kinds of metadata records can be sensitive information, too. And from a user perspective, "messages" should cover all message types.

Please see also:
https://community.signalusers.org/t/catalan-referendum-coordinated-with-signal/1609
and/or
[La Guardia Civil revienta el chat secreto en Signal de los 'arquitectos' digitales del 1-O](https://www.elconfidencial.com/espana/2017-11-22/independencia-cataluna-guardia-civil-revienta-chat-secreto-signal-arquitectos-digitales-referendum_1481632/)

### Steps to reproduce
- set "disappearing messages" to any value
- make or receive call(s)
- wait until time for disappearing messages has passed

**Actual result:** call notification does not disappear
**Expected result:** call notification disappears

### Screenshots
see video: https://vod.elconfidencial.com/834/d17/834d17b54baa9876bc8fc0700ef40508_26.mp4

### Device info
**Device:** any
**Android version:** any
**Signal version:** Signal v4.17.5

### Link to debug log
imo, not relevant

**Comment by moxie0** [comment]
This is the intended functionality. It's possible that we should revisit what is intended, but please use the forum for that. Thanks!

**Comment by haffenloher** [comment]
For reference, this is the corresponding feature request in the forums:

https://community.signalusers.org/t/disappearing-messages-for-calls/2110
