### ISSUE TITLE
Signal does not recognize Argentina's celphone number due a special 9 in prefix

### ISSUE THREAD

**Issue by ArgiesDario** [signalapp/Signal-Android#7668]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------
### Bug description
I've installed the app with a few friends, but found out that contacts were not sync, we cannot see each others, but using other apps like WhatsApp, we can see each other.

We found out that numbers from Argentina (we live in Buenos Aires) have an special number "9" to all cellphones. So numbers can be added like: 
+54 9 11 XXX XXXX (This is the way WhatsApp saves unknown numbers, and default for the country)
OR
+54 11 XXX XXXX (This way, without the 9, we can see each other on Signal)

So this special character is blocking us. We figured out a work around, to sabe both kind of numbers in the same contact so we can see each other on both apps, but its not a pretty one

### Steps to reproduce
- Add a celphone number from argentina with the format: +54 9 11 XXX XXXX
- Reload contacts to be sync

**Actual result:** Contacts won't sync
**Expected result:** You should see the others contacts using the app

### Screenshots
- None

### Device info
- This bug is not related to the devices

**Comment by 2-4601** [comment]
Related #5363, #5270

**Comment by danieldjewell** [comment]
FWIW #1511 has some interesting discussion, too. 

It seems as though Argentina is not in full compliance with some of the 3GPP/ITU specs on phone numbers (e..g E.164). The whole idea being that a telephone number (of any kind) is unique and the same. (e.g. +12125551212 should work to dial a number in Manhattan regardless of where you are.)

Can Argentinian mobile phones dial each other using the full E.164 number in-country? e.g. +54 9 11 XXX XXXX? (there might be other ways, but does this way *always* work? for SMS and voice?) 

If that works, it seems smart to change the number on registration to the full E.164 number... for everyone. Also, transparently transpose/prepend the prefix onto every number in the "mobile" field (and/or recommend that everyone in Argentina always uses the +54 9 E.164 number...) 

Actually, it wouldn't be a bad idea to harmonize everyone's number throughout the world and only register/store the E.164 number (with country code) at all times. Then, if people have contacts in their local contacts without the full E.164 number, maybe try to make the assumption that those contacts are from the same region as the SIM in the device and apply the same transposition to them as upon registration. (e.g. in the UK 07123 123456 would be transposed at registration to +44 7123 123456 ... and then if there are contacts that are 07123 654321, they would also be transposed to +44 7123 654321 before searching for them. Then, take the local international prefix (based on the locale of the SIM card) and just transpose that to + -- e.g. for a UK SIM ... 00 becomes +, for a US, 011 becomes +). 

This whole thing would probably not be an issue if everyone always just used E.164 full numbers at all times. One can dream!

**Comment by greyson-signal** [comment]
I feel like this was addressed? If not, feel free to re-open.
