### ISSUE TITLE
Incoming call rings only for 1 second on phone with flip shell

### ISSUE THREAD

**Issue by lantsem** [signalapp/Signal-Android#7669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Phone is used with original flip shell, which comes with magnet to wake screen when open. The lock screen is turned off. On incoming call in closed state Signal starts ringing and stops after 1 second. If you open screen, then you can see the incoming call, but without sound for ringtone.
Legacy issue #6817.

### Steps to reproduce
- Close flip case
- Receive a call

**Actual result:** Phone rings only for 1 second
**Expected result:** Phone must ring the entire time of the incoming call

### Device info

**Device:** Motorola Moto G3
**Android version:** 6.0.1
**Signal version:** 4.17.5

### Link to debug log

https://debuglogs.org/6ddf671dc0ebbe43ffc2ae39422d5fdb2da55bb999b4e39a81ccbf50d621a2bb

**Comment by lantsem** [comment]
Still relevant with version 4.47.6.

WhatsApp also has this problem, Viber does not.

**Comment by huaracheguarache** [comment]
I'm also experiencing this issue on my Samsung S20 FE 4G with the OEM flip cover. The phone is running Android 11 and the Signal version is 5.3.7.1. Here's a debug log (relevant part around 2021-02-03T17:09): https://debuglogs.org/4e571388f54f71dbd9a4ae101ccc65ffbc0823ed2aff549b7d4c0657a6bc422e

**Comment by AsamK** [comment]
Looks like Signal stops the ringing on purpose, when the screen is turned off. Makes sense if the user actively turns the screen off, but not if the device turns the screen off automatically ...
```
02-03 17:09:12.537 24480 24480 I WebRtcCallService: onStartCommand... action: SCREEN_OFF
02-03 17:09:12.538 24480 11320 D WebRtcCallService: action: SCREEN_OFF action handler: IncomingCallActionProce
02-03 17:09:12.538 24480 11320 I IncomingCallActionProce: Silencing incoming ringer...
02-03 17:09:12.539 24480 11320 I IncomingRinger: Stopping ringer
02-03 17:09:12.544 24480 11320 I IncomingRinger: Cancelling vibrator
```

**Comment by huaracheguarache** [comment]
For what it's worth, Viber displays the same behaviour as Signal.
