### ISSUE TITLE
Images shared to Signal sometimes don't have EXIF rotation detected.

### ISSUE THREAD

**Issue by greyson-signal** [signalapp/Signal-Android#7671]
### Bug description
When sharing via an external share sheet, Android's ExifInterface doesn't seem to be reading the EXIF data properly. It doesn't find anything. The funny thing is that if you load the same image from the media rail, it can read the EXIF data just fine. The stream from the external share is a CipherInputStream, while the stream from the media rail is a ParcelInputStream, so maybe something is going on with one of the streams with how the ExifInterface works.

### Steps to reproduce
- Open the attached image in a photo view
- Share to Signal

**Actual result:** Image is rendered in the correct orientation, but with the wrong dimensions.
**Expected result:** Image should be rendered with correct orientation and dimensions.
### Screenshots
![problem-01](https://user-images.githubusercontent.com/37311915/38717457-e05f67da-3e9b-11e8-92da-d2eb33a12f6d.jpg)
![exif-share-bug](https://user-images.githubusercontent.com/37311915/38717525-45124a44-3e9c-11e8-802d-41f90eb4b0e8.png)

### Device info

**Device:** Pixel 2
**Android version:** 8.1.0
**Signal version:** 4.18

**Comment by johanw666** [comment]
That could be an unintended side effect of https://github.com/signalapp/Signal-Android/commit/7e1e666172e0c8d0582d28a817affae91a02a598
