### ISSUE TITLE
Signal (Noise) stops receiving and/or sending messages ~ once yearly, gives no error messages.

### ISSUE THREAD

**Issue by gethob1** [signalapp/Signal-Android#7672]
### Bug description
About once a year Signal messages either stop being received on either my end, the other end, or both.  Without indication I stop getting messages or someone else stops getting mine, or both, and is later discovered by texting the person in plain text.

### Steps to reproduce
- There are either no steps to reproduce or at least no identifiable steps that can I link with the problem
- I'm not using any features or doing anything fancy or special, just picking contacts, sending messages to them, and waiting to receive messages from contacts.

**Actual result:**
It just stops working with no indication or particular reason or time.  When it's down I don't might not receive messages and/or when trying to send them it will say 'sent' with the double check marks but that user will may or may not get the messages.  There are no errors or warnings.

**Expected result:**
I expect messages to always send and be received to/by both ends without fail regardless of how I use the app.

### Screenshots
Nothing to see; the display is identical to when functioning properly except for the absense of messages I'm supposed to receive.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** Noise 4.15.5-0 (github bug report for Noise links to Signal github bug report)

### Link to debug log
I didn't know I'd need a debug log or that one even existed.  I've re-installed it and the problem doesn't seem to occur now and the log doesn't date back to the previous installation.

**Comment by moxie0** [comment]
Hey @gethob1, we're not able to support other people's software here. You'll have to look to the Noise maintainers for support, thanks!
