### ISSUE TITLE
Signal (Noise) deletes a random number of contacts after installation most of the time

### ISSUE THREAD

**Issue by gethob1** [signalapp/Signal-Android#7673]
### Bug description
For no apparent reason, Signal (Noise) deletes any number of contacts (usually not more than 1/3 to 1/2) following its installation.

### Steps to reproduce
- Install Signal (Noise) from F-Droid
- Complete the verification
- Allow it to scan/modify contacts

**Actual result:**
Certain contacts disappear and I can ascertain no pattern (across every time this has happened) as to why it deletes some and not others.  However, in the latest erasure, it was mainly the most recently added contacts with only a few of the older ones that were subsequently missing after installation.  (Strangely, just before installing it I backed up my contacts to .vcf (using 'Export Contacts' app in F-Droid) in hopes of restoring them if deleted, and after installation I found the same contacts were also deleted from the .vcf backup; normally this backup procedure works.)

**Expected result:**
I expect Signal to leave my contacts alone.  If it creates new ones, well that is not preferable but at least it's not deleting them.  Just don't ever delete any of my contacts, please.  It consistently does this almost every time I install; sometimes it does not.

### Screenshots
Nothing to see.  Just missing contacts.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** Noise 4.15.5-0

### Link to debug log
Unable to access

**Comment by UserX404** [comment]
I didn't address Signal for this but i also noticed disappeared contacts in the past.

Device: HTC One Mini 2 (memul)
OS: 7.1.2 (LOS14)
Signal: 4.17.5

**Comment by moxie0** [comment]
We're not able to support other people's software here. You'll have to contact the Noise maintainers for support, thanks!
