### ISSUE TITLE
Messages are quickly displayed on screen after expiration

### ISSUE THREAD

**Issue by Gu1nness** [signalapp/Signal-Android#7674]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If a message is set with an expiration time, and it has not been read during this time,
when clinking on the notification for this message, it is quickly displayed on the screen before being deleted.

This is a security and privacy problem : 
 - It means that memory is not completely freed after the expiration
 - It discloses information that should have disappeared.

### Steps to reproduce
- Have the application unlocked
- Receive a message with an expiration time.
- Wait for the expiration time to be over
- Touch the notification

**Actual result:**

The message appears on screen and then disappears very quickly.

**Expected result:** 

The message should not appear on screen.

### Device info

**Device:** Wileyfox Swift 2 Plus
**Android version:** Android 7.1.2
**Signal version:** Signal 4.18.2

**Comment by FeuRenard** [comment]
https://support.signal.org/hc/en-us/articles/213134237-Does-Signal-have-disappearing-messages-

How it should work is, that the timer starts after the received message is read (see support article).

**Comment by moxie0** [comment]
Sounds like this is the intended behavior
