### ISSUE TITLE
Unable to rename MMS or SMS group name

### ISSUE THREAD

**Issue by drohack** [signalapp/Signal-Android#7675]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving or after starting a MMS or SMS group message you are unable to find the "update conversation" button in the message menu to be able to rename the message.

### Steps to reproduce
- Start new MMS group message with users that do not use Signal
- Send a message
- In the message click the 3 dot menu button
- No "Update message" button is available

**Actual result:** No "Update message" button is available
**Expected result:** Have the button to Update the message to be able to rename the message.

### Device info
**Device:** Google Pixel XL
**Android version:** 8.1.0
**Signal version:** 4.17.5

**Comment by moxie0** [comment]
This is currently the intended behavior. It's possible that we should revisit naming MMS groups (only visible locally), but we use the forums to discuss feature requests. Please post there to discuss, thanks!
