### ISSUE TITLE
Can't verify number on version 4.17.5 for android without google play services

### ISSUE THREAD

**Issue by janemba** [signalapp/Signal-Android#7680]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm using an Android (version 6.0.1) but without Google Play Services (Lets say no GAPPS). So I downloaded the signal APK (version 4.17.5) on the official website. But finally, I can't "verify my number". I have an error saying "Unable to connect to service. Check your network connection and try again".

So I checked with ADB and I got the following log :

04-15 14:13:35.429  7429 19939 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)

### Steps to reproduce
- (Without GAPPS and google play services installed)
- Download official signal APK
- Install it
- Type your phone number

**Actual result:**

Got this error :

Unable to connect to service. Please check your network connection and try again.

**Expected result:** 

Receive an SMS

### Screenshots
04-15 14:13:35.429  7429 19939 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:13:35.429  7429 19939 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:15:05.497  7429  7465 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 502 
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:745)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAccount(PushServiceSocket.java:131)
04-15 14:15:18.439  7429  7632 W RegistrationActivity: 												at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:112)

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.17.5

### Link to debug log

No debug from Signal

**Comment by GAPPSRefusenik** [comment]
Do you want to use Signal with GCM or WebSockets?

If you want to use it with GCM you need to enable GCM in MicroG settings and register Signal in MicroG GCM settings (Not signal sign up). After that register your number with Signal, should work.

Please note that if you later disable GCM in microG after signing up to signal using this method you will be unable to recieve encrypted messages as the server doesnt revert to WebSockets for the sender.

If you want to use Signal with WebSockets you need to disable microG in the settings (Phone settings -> Apps -> MicroG Settings -> Disable service), reboot your phone and register your phone number in Signal. A warning will appear that notifies you about non-existent GCM/Play Services. After you've signed up you can enable MicroG again and reboot your phone.

source: [reddit](https://www.reddit.com/r/signal/comments/7cg80r/just_the_usual_signal_doesnt_work_with_my_microg/dpt0g1n)

I myself am using Signal with the latest microG preview build and have had no issues thus far.

**Comment by jlund-signal** [comment]
Thanks for the explanation, @GAPPSRefusenik. Your username is very contextually appropriate.

**Comment by janemba** [comment]
@GAPPSRefusenik 

Thank you. So, I try the second method. Without MicroG enabled. And I got exactly the same issue with the same symptoms.

Also, with the first method I can't see anything related to GCM (except for enabling it) about registering an application. I'm using the latest version of MicroG on F-DROID repository.

**Comment by janemba** [comment]
@moxie0 

Thanks I will try your solution this instead (well, I remember I installed signal when I was in another country).

**Comment by kabo** [comment]
Sorry for bringing an old thread to life, but @GAPPSRefusenik, how does one "Disable service" in the microG settings?

![screenshot_microg_services_core_20180618-203633](https://user-images.githubusercontent.com/357601/41527137-53799592-733a-11e8-8f3f-7dbdf951439a.png)

**Comment by kabo** [comment]
Ah, I figured it out. Settings > Apps & notifications > microG Services Core
Click "Disable", then "Force Stop". Then it works :)

**Comment by DouglasRay** [comment]
is it still possible to use WebSockets in v 4.34.8 or 4.34.9?
I have the "Google Play Services" permissions diagnostic when trying
to register my phone number.

platform is android 6.0.1 from Samsung - i don't see any "microG" system apps.
i tried 4.34.9 on playstore and 4.34.8 apk from signal.org.
