### ISSUE TITLE
Signal 4.17.5 crashes when importing recent plaintext backup

### ISSUE THREAD

**Issue by atomspring** [signalapp/Signal-Android#7682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, thanks for creating this wonderful system. I keep getting an ANR when restoring my plaintext backup from pre-4.17.5 into 4.17.5.

### Steps to reproduce
- Place SignalPlaintextBackup.xml into Internal storage root using MTP
- Enable Backups in Signal, recording backup password etc
- Go to overflow > import > import plaintext backup

**Actual result:** After clicking "Import plaintext backup", I get an "Application not responding message"
**Expected result:** My backup ought to be imported

### Device info

**Device:** Motorola G5
**Android version:** 8.1
**Signal version:** 4.17.5

### Link to debug log
https://tinyurl.com/y9xx2suu

The important bit is: https://paste.linux.community/view/7c92ecaf

**Comment by GAPPSRefusenik** [comment]
I had the same problem when I tried migrating today. Downgrading to 4.15.5 and doing the plaintext import there solved it for me.

**Comment by risole** [comment]
Me too.

**Comment by greyson-signal** [comment]
Plaintext backup import has been removed.
