### ISSUE TITLE
New MMS group created for responses to a group created through signal

### ISSUE THREAD

**Issue by benmayne** [signalapp/Signal-Android#7683]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I create a MMS group through signal, replies from other members create a new thread. The original group does not list me as a member, but the new group does. 

(defauly sms app, wifi calling compatibility mode off, project fi network)

### Steps to reproduce
- create a mms group
- send a message
- wait for someone to reply

**Actual result:** the reply creates a new thread/group
**Expected result:** replies go to the same thread/group

### Screenshots

First group
![2018-04-15 09 33 50](https://user-images.githubusercontent.com/3374110/38780981-74705a58-4093-11e8-965d-1e00ad22d7e3.png)
![2018-04-15 09 56 12](https://user-images.githubusercontent.com/3374110/38780983-7927930e-4093-11e8-8124-8f3100be7f3a.png)

After replies: 
![2018-04-15 09 33 41](https://user-images.githubusercontent.com/3374110/38780988-8ca3f83c-4093-11e8-8cc3-e91e37dcb793.png)
![2018-04-15 09 33 45](https://user-images.githubusercontent.com/3374110/38780993-9583eea8-4093-11e8-9907-f28159804e48.png)

### Device info

**Device:** Pixel
**Android version:** 8.1.0
**Signal version:** 4.18.3

### Link to debug log

https://debuglogs.org/cfed3ebb12a7ba60f98ccce30677996f5fc46c55b899e1e4d9a92638a4d9cbfe

This is a re-submission of https://github.com/signalapp/Signal-Android/issues/7161 which was closed during the cleanup (https://github.com/signalapp/Signal-Android/issues/7598)

**Comment by dcherian** [comment]
Happens to me always. I'm on Sprint

**Comment by hunleyd** [comment]
Happens to me as well, Project Fi. And if you try to be clever and add yourself to the original group when creating it, it says you're already a member.

**Comment by dcherian** [comment]
Just happened today: https://debuglogs.org/4774c97924b4246cd72cfce370e6ab1f303d8b6693385be9deaf109473f92ff5

The original group lists my name first while the new group lists my name last

**Comment by shanep2300** [comment]
Same issue, TMobile.

**Comment by taschrant** [comment]
Same issue, Project Fi.

**Comment by strugee** [comment]
Please don't comment "same issue". It's well-established now that this is a bug. What this issue needs now is not more people confirming it, but for someone to actually fix it.

**Comment by wesinator** [comment]
Looks like the issue is around https://github.com/signalapp/Signal-Android/blob/d9ba6962c792033ea99f8e24fb4482ac1020f8bd/src/org/thoughtcrime/securesms/groups/GroupManager.java#L51

The code appears to add the current local user to the new group, but it obviously doesn't.

**Comment by slicknic** [comment]
It seems like it's adding the local user. If I create a new group but attempt to add myself as well it tells me "you are already in the group".

**Comment by mfsch** [comment]
I have observed a similar issue on my dual SIM phone. In one-on-one conversations using my non-Signal SIM I can successfully send MMS images and they end up in the correct conversation, but when I receive MMS images from the other person Signal creates a new group with the other person, my non-Signal number any my Signal number. 

I think this could be regarded as the same issue since in both cases incoming MMS messages are not attributed to the correct conversation. Looking at the pull request #8296 I’m not sure though that this solution also works with dual SIM phones and with one-on-one conversations. It would be great if the original issue and mine could be solved in one go, so if someone more familiar with the Signal code could check this, that would be cool! Otherwise I might try finding some time to figure out the problem with my dual SIM MMS messages and come up with a separate issue or pull request.

**Comment by fleapower** [comment]
This issue is two years old, and other threads state it had been fixed. However, it is persisting on my Samsung A51 on T-Mobile. Is it being tracked in another thread?

**Comment by strugee** [comment]
@fleapower you are likely encountering a different bug. Please report a new issue, and make sure to follow the proper procedure - in particular, please search to see if the bug you're encountering has already been reported.

**Comment by benmayne** [comment]
Looks like there's an open version of it already here: https://github.com/signalapp/Signal-Android/issues/9213

(I'm about to add new logs to that one since it's back for me as well)
