### ISSUE TITLE
Two days not able to send/receive messages/calls

### ISSUE THREAD

**Issue by Lithiumion** [signalapp/Signal-Android#7684]
I have not been able to send/receive messages or calls for two days now. I'm using Signal 4.17.5 on Android 8.1.0. Everything else works fine and I have great 4G and WiFi coverage.

I even tried to deregister the app many times and I always got a "Error connecting to server" message

Funny thing is.. I was able to send messages from my desktop app while the phone version was, and still is, unable to communicate with my contacts.

----------------------------------------

### Device info
Pixel 5"
Android version: 8.1.0
Signal version: 4.17.5

### Link to debug log
https://debuglogs.org/9c8ea33258d846817337b0a594dfe8f42b8fa1322608eb898527d22d77747638

**Comment by moxie0** [comment]
Unfortunately you're in a country where Signal is censored, and we've been using Google as a domain front to circumvent that censorship. Now Google has stopped supporting domain fronting, so connections are failing. This should be fixed in 4.18.x which is rolling out through the play store.

**Comment by Lithiumion** [comment]
Thank you Moxie for the explanation. 

Actually I'm currently in Europe and this issue is recurring. I guess it is because my initial registration happened back in that country and I have to stick with it because it is how I communicate with my contacts. Is there away to inform Signal app on my phone to stop using domain fronting or do I just have to wait for the 4.18.x update?

Cheers
