### ISSUE TITLE
Blurry images when received from MMS

### ISSUE THREAD

**Issue by Sollybird** [signalapp/Signal-Android#7685]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I receive images from a non-Signal user, the images are heavily compressed, often beyond legibility (if they contain text). The issue is strange, as it appears to be somewhat localized - someone else, whom I've personally referred to Signal, doesn't have this issue at all when receiving the same image from the same sender. Similarly, whenever the other Signal user sends me a message (using the Signal protocol), the image quality is perfectly fine. Images received from various senders (using MMS) all result in the same blurry image quality, making the app unusable for receiving pictures of notes or any text, really.

### Steps to reproduce
- Receive MMS message from a non-Signal user
- Attempt to view MMS messages

**Actual result:** The image is displayed but blurry, and much lower quality than the original image.
**Expected result:** The image would be received and displayed at the original image quality.

## Album
======
https://imgur.com/a/ri5Ny

## The original picture that I sent
=====================================
https://i.imgur.com/dYGtSck.jpg

## The same picture, downloaded and sent back to me
=================================================
(Note: It is perfectly legible and not blurry on his end
https://i.imgur.com/q3mFVa1.jpg

### Device info

**Device:** Samsung Galaxy S4 Model SCH-I545PP
**Android version:** 5.0.1
**Signal version:** 4.17.5 (although the issue has persisted for more than a year, when using both the Beta and the standard version from the Play Store)

### Link to debug log

https://pastebin.com/GJubpsD3

### Similar threads
https://github.com/signalapp/Signal-Android/issues/6607
https://github.com/signalapp/Signal-Android/issues/672

**Comment by moxie0** [comment]
We don't do any compression of received images. If you switch to the standard SMS/MMS app on your device, and have the same sender send you the same image, does it appear differently?

**Comment by rainmaker** [comment]
I'm also having this issue, text is impossible to read in Signal, but the image sent was high quality.

**Comment by pebuls** [comment]
I'm also having this issue. When I sent picture it's ok for some time, maybe 10 min? and then a got a blurry one and the person who I sent also get the same. 

Device: LG Q6
Android version: 8.1.0
Signal version: 4.30.8

**Comment by patpilus** [comment]
I'm facing the same issue for a long time. 

For instance the screenshot from my phone with the original resolution of 1080x1575px (size 1.65 MB) is resized to 270x393px (60.37 **KB**). I don't get why the compression was set to be so high...

Device: Xiaomi Mi 6
Andorid version: 9.0.0 (custom ROM) 
Signal version: 4.33.5

**Comment by greyson-signal** [comment]
Same as #8590, but that one seems to have more discussion.

**Comment by Sollybird** [comment]
This is not the same issue as #8590.  #8590 pertains to the compression of images sent by the user, while this thread has to do with images sent to the user.

**Comment by patpilus** [comment]
@Sollybird actually it seems to be the same. You can see in description of #8590, that the image quality is degraded on both sides:

> Clicking on the thumbnail shows how degregated it is, and is actually what the other person sees. This is for non-signal users.

**Comment by KonPaw** [comment]
Just to clarify @patpilus if you quote a little bigger part of Juush comment:

> run the app and **send** a picture (either from my gallery) or from the in-app camera and send it off to someone. Clicking on the thumbnail shows how degregated it is, and is actually what the other person sees. This is for non-signal users. 

plus Juush second comment:

> I can receive images just fine, it's just the sending. 

So it does seem that this two issues are different ones, but it's a little blurry as @Sollybird tested it by sending to himself MMS, which could be related to #8590... (unless did by a different phone not using signal, but he didn't clarify it).

**Comment by scottdonaldau** [comment]
Experiencing this on a Samsung Note 9 - makes it a pain the arse to send someone without Signal any screenshots or photos as I have to switch back to the Samsung Messaging app (which requires me to make it the default just to use the bloody thing). Be great if this could be fixed.

**Comment by dallenwilson** [comment]
I am also experiencing the problem nearly exactly as described by @Sollybird, intermittently and with different contacts at different times. I've done a bit of troubleshooting, and my best guess as to what is happening is that Signal is receiving the image, but only allowing access to the size-reduced thumbnail that is displayed in the conversation.

I was sent a 'screenshot' (A phone-camera photo of a computer screen, from an iPhone) with text in it, and it was more or less unreadable in the thumbnail, as I would expect. Tapping the image to bring up the fullscreen display showed the same pixelated text. I saved the full image to device's SD card, and when viewing it in the usual gallery app, was able to zoom out quite a bit more than I expected. The details button reported the image was 180x240, which by my rough eyeball guess is about the size of the thumbnail in the conversation. The image sent was much, much bigger than that, but if it was just the locally generated thumbnail that got displayed and saved... well, that would explain the problem.

Device: Samsung Galaxy S5
Andorid version: 9.0.0 (LineageOS 16.0)
Signal version: 4.49.14
