### ISSUE TITLE
Not able to register the Signal APP using the Android phone

### ISSUE THREAD

**Issue by Mathew4321** [signalapp/Signal-Android#7686]
Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

----------------------------------------

### Bug description
I am not able to register to Signal App using my Android phone, I have tried in couple of phones in my office all are giving the same error “ Unable to contact the service”.
I have tried with different WIFI network and Phone data still I am getting the same error.
But the signal App works fine with  IOS(iphone)
I

### Steps to reproduce
- After installing the Signal APP
- Tried to register the APP but it failed and gave an error " Unable to contact the service"
- Carried out the Testing in couple of mobiles with Android they all failed with the same error.
-Tried in different WIFI network and with Mobile data still the same error.

**Actual result:** It will not register and error pops up with " Unable to contact the service".

**Expected result:** should be able to register the Phone

**Comment by Mathew4321** [comment]
We are not able to register to Signal App using the Android phone.

**Comment by jmiroslav** [comment]
I'm also having an issue to register two android phones with Signal. I did have two cases:

- Connectivity error. Signal was unable to connect to the server
- No SMS or call is not cumming to register the service

This is in Macedonia, +389, the provider is Makedonski Telekom 70-xxx-xxx. The phones have unrestricted internet and all other applications are working properly.

**Comment by Mathew4321** [comment]
I have tried around four android phones all are giving the Connectivity error. "Signal was unable to connect to the server".

I am from from UAE, +971 the service provider is DU and Etisalat.

**Comment by p4nci** [comment]
@Mathew4321 please provide all required (template) info e.g. Signal version, device, debug log, ...
Since you are in UAE, Signal may be censored (again???, see also https://github.com/signalapp/Signal-Android/issues/6027). Please try again with Signal v4.18.x (see also Moxie's comment https://github.com/signalapp/Signal-Android/issues/7680#issuecomment-381491729)
 
@jmiroslav imo, your issue it's different issue. Probably you are affected by this: [6027#comment](https://github.com/signalapp/Signal-Android/issues/6027#issuecomment-371116062)

@jlund-signal you may revisit the decision to reopen/unlock https://github.com/signalapp/Signal-Android/issues/6027

**Comment by Mathew4321** [comment]
How can i get older version of Signal App from play store, the version i installed was latest version.
I have tried in other android phones as well are giving the same error so its not my phone issue(i think so)

**Comment by Mathew4321** [comment]
I have tried with the old version of Signal still it gives the same error "cannot contact the service"

**Comment by p4nci** [comment]
@Mathew4321 
for additional info see also
https://community.signalusers.org/t/android-users-in-the-uae-are-reporting-that-signal-has-stopped-working/2556

**Comment by moxie0** [comment]
Hey sorry but I'm not able to provide support without a debug log. It seems like you're likely in a country where Signal has been censored, in which case the 4.18.x update should resolve things for you.
