### ISSUE TITLE
Contacts' self-set profile pictures aren't shown after fresh install (w/o importing backup)

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [signalapp/Signal-Android#7689]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a fresh install - even without importing a backup - none of my contacts' self-set profile pictures/avatars, i.e. the profiles _they_ set themselves, are shown. Instead Signal shows the usual colored circle with the respective contact's initials in these cases. (Still holds 25 minutes after the install and after texting with one such contact.)

(As a side note: The app does show pictures which I set myself in the phone's contacts app. But there's no intersection betw the two sets of contacts.)

_Edited for clarity after @p4nci 's comment below._

### Steps to reproduce
- install Signal, don't import a backup

**Actual result:** Signal doesn't depict contacts' avatars which they set themselves. Instead it shows the regular colored circles with initials.
**Expected result:** After a reasonable amount of time, self-set pictures should be shown.

### Device info

**Device:** Motorola Moto G4 Play
**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.18.3

### Link to debug log
[Here's one](https://debuglogs.org/f3164394c8d1df602e41521f4a71698986f101772327b008b404778cb2926df0), taken two minutes after installing the app.

**Comment by p4nci** [comment]
> The app does show pictures which I set myself in the phone's contacts app.

imo, this is intended functionality. From [signal blog](https://signal.org/blog/signal-profiles-beta/):
`..., but the contact information that is stored on your device will always take precedence.`

I know there is an issue about this, since I have suggested an option to enable/disable the priority of the displayed profile info (self stored within device vs. contacts profile info)

**Comment by moxie0** [comment]
What version was the backup created on?

**Comment by AlfonsoMuskedunder** [comment]
I'm a bit confused - I did _not_ import a backup during install.

**Comment by moxie0** [comment]
I'm sorry, I read that wrong. So you've received a message from a contact with a profile pic, but still don't see their photo? Are you sure that you're in their contacts, and do you know what platform they're on?

**Comment by AlfonsoMuskedunder** [comment]
Now that my friend's responses are coming in, their profile pics return. Sorry for the clutter.

I guess I was inclined to come to the above conclusion because I'm still "suffering" from a broken (wrt avatars) backed up database. Against this background, I kind of expected that avatars should appear automatically within an hour or so after a fresh install.
