### ISSUE TITLE
Error Playing Audio

### ISSUE THREAD

**Issue by nocluetoo** [signalapp/Signal-Android#7690]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I receive my voicemail as audio MMS.  When attempting to play the audio, I always receive 

### Steps to reproduce
- receive an Audio MMS
- download MMS (if necessary)
- hit play

**Actual result:** "Error Playing Audio"
**Expected result:** Hear the audio file.

NOTE: if you save the file, the .AMR is playable by VLC or other players.
Reproduced entirely in 4.18.3 on April 16th.

### Device info
**Device:** SM-A520W
**Android version:** 7.0
**Signal version:** 4.18.3

### Link to debug log
https://debuglogs.org/6ac76730b55eca1c14d46ece5b5792f00cd8f9183bc49c6a24675f2ad3807088

Sample audio file:
[AudioFile.zip](https://github.com/signalapp/Signal-Android/files/1917270/AudioFile.zip)

**Comment by greyson-signal** [comment]
This is likely the same problem as #7748.
