### ISSUE TITLE
encrypted backup does not get created (4.18.3)

### ISSUE THREAD

**Issue by nextgen-networks** [signalapp/Signal-Android#7691]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal encrypted backup does not work as expected. No backup is beeng created after counting messages.

### Steps to reproduce
- select "Sicherung erstellen" (create backup) from within Signal
- messages will be counted
- after counting the last successful backup date/time is displayed again (in my case sunday 11.39 p.m.)
- when inspecting file storage in /internalStorage/Signal/Backups only older backups are shown

**Actual result:**
Backup not possible

**Expected result:**
Backup possible / backup file in expected folder and last backup state refreshed within Signal app

### Device info

**Device:** Xiaomi Mi MIX 2
**Firmware & ROM:** xiaomi.eu_8.4.12
**Android version:** 8.0.0
**Signal version:** 4.18.3

### Link to debug log

https://debuglogs.org/4fae034f5adfb3ee991d8a5df75a11e5ea7074f0811ff8564c1d79e4f0b7217a

**Comment by AlfonsoMuskedunder** [comment]
May I ask whether you inspected the backup folder via your phone's browser or via a desktop computer? In the latter case you may just have to reboot your phone to see the current, actual file list.

**Comment by nextgen-networks** [comment]
Hey @AlfonsoMuskedunder 
Thanks for your hint. But indexing/reindexing of files and their apperance as mtp device is not the source of the problem here.
The file is not shown on the device itself (via file browser app and via twrp file manager).
As you ca see in linked log the fresh created backup file is beeing deleted by signal itself.

**Comment by nextgen-networks** [comment]
ok weird - it seems to be some kind of enum/counting bug

**Full story (and possible reason for problems):**

I had played with different ROMs last weekend.
Had to restore Signal from encrypted-backup because keystore seemed to be deleted/not restored the right way from within TWRP.
No problem at all - restore from within signal went perfectly good.

To restore I copied some older encrypted backups from pc to smartphone.
I've chosen 5 files - the latest one, and 4 older files.
These selected files are not in line of all the backups I made with the device!
The latest backup restored well I therefore left all other backups in place on the device.

This situation leads to the bug report you read by now ;-)

Workaround to backup again:
I've deleted the 2 of 5 oldest backups and voilá: Backups are possible again!

Afterwards I created 3 more backups. One of the old backups has been deleted automaticly.

Assumption:
Backups placed in Singal backup folder that have been created before Signal 4.18.3 release and that are not in line with some kind of internal counter could not be deleted automatically if new backup is created.

**Comment by haffenloher** [comment]
> Assumption:
Backups placed in Singal backup folder that have been created before Signal 4.18.3 release and that are not in line with some kind of internal counter could not be deleted automatically if new backup is created.

They're sorted by the timestamp in their filename and the two newest ones are kept (or should be).

**Comment by moxie0** [comment]
I'm not sure that I understand the description. Is there still a bug report? Did you rename the files you restored?

**Comment by nextgen-networks** [comment]
Hi @moxie0 
I've not renamed any backup files.

I've collected a set of more than 10 backups from my mobile on pc.
When restoring Signal I copied 5 of them from pc back to my mobile and restored the latest one.
Afterwards i was not able to create new backups nor they were created automaticly.

I had to manually delete at least one of the older backup file from mobile to have the backup function working again.

**Comment by nextgen-networks** [comment]
@moxie0 
As i can see in one of the latest commits (https://github.com/signalapp/Signal-Android/commit/d8a6fcf979357d411a20c154d004f64705dffe46) the order of backups that have to be deleted is beieng calculated from file timestamp not from filename.

Is it possible that an very old file date leads to an situation i faced?

**Assumtion:**
- Signal Backup files have been copied from pc to mobile via TWRP recovery.
- TWRP recovery was initialized without valid date/time (e.g. because device was complete reset/wiped).
- Typically this leads to (signal backup) file dates like 1970-01-01.
- This file date is out of range for java date/time calculation and therefore invalid if  device is bootet later on.
- By having an invalid date this old backup is beieng retained instead of the new backup file. The new file is supposed to be older than the X existing backup files that have to be kept.
So the new backup file is beieng deleted instead of one of the old ones (also see debug log that directs to that assumtion).

Could this be happen this way?


**Possible solution**
Use a date/time timestamp within the backup file as calculation base of what file has to be deleted or retained.

**Comment by artur-g** [comment]
Same problem with version 4.19.1
https://debuglogs.org/e9f85cdbaaaa098b5b6a724b72f9f727968698af365ae345447ca06fb5b96270
My backup was created and then copied with SolidExlorer to sdcard/_Backups folder. Next I formated whole phone, installed Signal and tried to create almost empty backup (to naturally create folders where they supposed to be). It counts something (I have only 1 or 2 smses) and does not create anything. I'm on cheepo Chinese phone with 1gb ram, root and xposed.

**Comment by artur-g** [comment]
Sorry, errata.
My problem is different.
When I click backup, my "Last created backup" is "never".
Looks like permission problem, but I granted all and double checked permissions in Settings. Maybe it tries to write in sdcard and can't because its different kind of permission, but it never asked me for it.

**Comment by srchulo** [comment]
I'm experiencing the same thing as @artur-g. Last created backup is never. I think I started experiencing this once I put an SD card in my device.I believe it is a separate permission for SD Cards, so maybe that's why this is happening. I see a Signal/Backups folder on my SD card, but it's empty.

**Comment by srchulo** [comment]
Just tested it. When I take out my SD card and backup, the backup says "Just now" and the file is on my device in Signal/Backups on the internal storage. Probably an SD card permission issue?

**Comment by srchulo** [comment]
After putting the SD card in, it goes back to saying the last backup was never, I assume because it's trying to read from the SD card storage which actually has no backups (and maybe because it can't even read there at all).

**Comment by moxie0** [comment]
Everyone with an sd card, your issue is #7692 rather than this.

@nextgen-networks I'm unable to reproduce your issue. The timestamp is calculated based on the file names, not the FS timestamp. So unless you've been messing with your clock, it shouldn't be deleting the "newer" file. Can you give me steps to reproduce? Otherwise there's no action I can take. Thanks!

**Comment by nextgen-networks** [comment]
Hey @moxie0,

Thanks for your information and hard work on this great messenger & protocol implementation.

I will close this issue now.
I never faced any backup/restore problems in comparable situations after the occurrence described in initial post.
