### ISSUE TITLE
Messages are not ordered the way they were sent

### ISSUE THREAD

**Issue by codewing** [signalapp/Signal-Android#7693]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
The messages are not displayed in the same order as they were sent (see screenshots). 

### Steps to reproduce
- Requires a scenario where messages get sent but arrive in a different order

Maybe this could work:
- Send from smartphone with very little bandwidth
- Send from computer few seconds later

**Actual result:** Messages are ordered by their arrival time
**Expected result:** Messages are ordered by the time they were sent

### Screenshots

![ordering](https://user-images.githubusercontent.com/12066466/38870334-cbda6c00-424d-11e8-979c-da1fbd36b75c.jpg)

The marked messages should have been ordered in the following way:
First one is the last one. Second is the first one (as you can see from the timestamp). And last is the second one.
When looking at the message detail view the timestamps seem to be correct.

### Device info

**Device:** OnePlus One
**Android version:** 7.1.2
**Signal version:** 4.18.3

**Comment by 2-4601** [comment]
The current way of sorting is actually the intended behavior so let's move this discussion to the [forums](https://community.signalusers.org/t/message-ordering/2581).
