### ISSUE TITLE
Accept Calls: Swipe in Opposite Direction

### ISSUE THREAD

**Issue by ax3l** [signalapp/Signal-Android#7698]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When accepting/rejecting Signal encrypted calls on Android, the swipe (up/down) is *exactly opposite* to the system (stock) call swipe direction.

It would be cool if that could be configured or figured out by default somehow since it makes its usage highly counter-intuitive. One will accidentally reject calls all the time if they come in via Signal.

### Steps to reproduce
Get a signal call.
Swipe for accept or reject.

Get a regular call.
Swipe for accept or reject (it's opposite on some? Androids).

### Screenshots

how? it's blocked.

### Device info

**Device:** Oneplus 3T (A3003)
**Android version:** 8.0.0 (OxygenOS 5.0.1)
**Signal version:** 4.17.5
**Stock "Phone" app version:** 2.0.0.171201120207.00b4b38

### Link to debug log
N/A

**Comment by daveloyall** [comment]
![image](https://user-images.githubusercontent.com/1524866/38957040-1289d812-431f-11e8-9ac5-2ea860c75279.png)

@ax3l, the github web interface seems to allow PNG attachments/embedded images.  (Sorry for the side-chatter, everyone else.  Let's leave this as the only comment on this screenshot topic, please!)

**Comment by daveloyall** [comment]
@ax3l, regarding screen shots being blocked, that's a configurable setting.  Check Signal > ⋮ > Settings > Privacy > Screen Security.

**Comment by AlfonsoMuskedunder** [comment]
I think it's pretty obvious this is not a bug (swiping works as intended, you just find its direction counterintuitive), but a "feature request or a discussion topic". For such issues there's Signal's [discussion forum](https://community.signalusers.org/).

**Comment by moxie0** [comment]
Android by default is swipe up to accept, down to decline. I guess OxygenOS does something different. Maybe we should have a feature to support that, but hit up the forum to discuss.
