### ISSUE TITLE
Chat partner is unable to receive/display my quoted message

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7703]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Recipient does not see the message I quoted. 
In the past new features were implemented in phases. First the ability to receive (lets say voicenotes). Then the ability to send them. It seems here beta testers are able to send quoted replies, but non-beta testers are unable to receive quoted replies. Or at least display them correctly. 
Is this intended behavior?

### Steps to reproduce
- Chat partner writes something to me
- I quote the message
- He receives my message

**Actual result:** I see a quote on my end. He doesn't see a quote on his end.
**Expected result:** Quotes should work on both ends

### Screenshots

![signal-2018-04-19-075717](https://user-images.githubusercontent.com/18451020/38984217-a230e8d4-43b5-11e8-99eb-f3f530c3a9ba.png)

![signal-2018-04-19-075548](https://user-images.githubusercontent.com/18451020/38984228-a94d4266-43b5-11e8-82bd-f6f782292474.png)

### My Device info

**Device:** Samsung Galaxy S5 klte
**Android version:** lineage-14.1-20180411-nightly-klte-signed
**Signal version:** 4.19.1

### Other Device info

**Device:** unknown
**Android version:** unknown
**Signal version:** 4.17.5

### Link to debug log

should not be needed

**Comment by p4nci** [comment]
@halb9 imo, that's fine. Both devices needs at least Signal v4.19.1+

**Comment by Dyras** [comment]
If he waits a week for the update to get out of beta, it will start working

**Comment by moxie0** [comment]
Yeah this is the intended behavior, thanks for checking though
