### ISSUE TITLE
icon for sports category emoji is confusion

### ISSUE THREAD

**Issue by frozen-sky** [signalapp/Signal-Android#7709]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the emoji overview, the sports category has a bike/bicycle as icon. However, there is no emoji resembling a bike or bicycle in this category. All emojis respresting such a vehicle, are under the transport category. 

### Steps to reproduce
- start compose a new message
- select the 'emoji' icon, to start adding an emoji to you message
- assume you want to add an emoji of a bicycle
- one would intuitive select the group/category which has a person on a bicyle as icon
- search through this group, you won't find a bicyle

**Actual result:** You do not find an emoji with a bicyle or bike in this group
**Expected result:** Two options:
- You expected to find a bicycle in this group
- You expected a different icon for the sports category, then it is more logical to find the bicyle emojis in the transport category

### Device info
**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.15.5

**Comment by 2-4601** [comment]
https://community.signalusers.org/t/making-sense-of-emoji-categories/2672
