### ISSUE TITLE
Wrong notification when messages are unread

### ISSUE THREAD

**Issue by bauxi** [signalapp/Signal-Android#7710]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When there is an unread message of e.g. contact A in my messages and I get a new message from contact B in the meantime, the notification for the message of contact A is shown (including the time I received it).
I enabled the setting where only the contact name, not the message is shown in the notification (if this is important, idk).

### Steps to reproduce
- Receive message from person A (with correct notification)
- Open Signal, but do not read message
- Receive message from contact B
- Notification for the first received message is shown

**Actual result:** Notification for an old unread message is shown when a new message is received
**Expected result:** The correct notification for an inconing message should be shown

### Device info

**Device:** OnePlus 5
**Android version:** 8.1.0 (also on Android 8)
**Signal version:** 4.19.1 (also on 4.18.x)

### Link to debug log

https://debuglogs.org/e18318390fbe5e4b799370d85302fbd19bb8cf58719ac632f1f8d9e2ca9473c8

**Comment by seancmonahan** [comment]
I have had this issue for a long, long time with Signal, not just the latest versions. I'm on Pixel 2 with latest Android 8.1.0, but I am pretty sure I also experienced this bug on my old Nexus 5 (running LineageOS 14.1, i.e. Android 7.1).

> I enabled the setting where only the contact name, not the message is shown in the notification (if this is important, idk).

I can confirm that this bug also occurs with notifications set to show the message contents too.

**Comment by SamClayton** [comment]
Same issue on both Nexus 6P and Pixel XL over several versions of Android, up to and including 8.1.0, with message contents configured to display in notification. 
Signal version: 4.19.3 and earlier

**Comment by brian-mcnamara** [comment]
I too am seeing this. I am working on a fix. I believe I have found the issue but need to run more testing and see if I can repo this in tests.

**Comment by brian-mcnamara** [comment]
Got it working :smiley: Check latest linked commit for code changes. Going to play with it a bit longer before creating PR. Also wanted to create a test for it but seems like Id be the first one to create an instrumentation test so not sure how much functionality it would add.

**Comment by AriasAEnima** [comment]
Same bug in telegram !

**Comment by vertigo220** [comment]
Any update on this? Just came to post about this same issue (Moto Z Play 8.0.0) and it's been a year since this was apparently fixed (thanks @brian-mcnamara!) but hasn't been implemented yet.
