### ISSUE TITLE
Do not save photos taken within Signal in plain text

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#7711]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When taking a photo directly inside Signal, an unencrypted JPEG is stored to the file system available for all other apps in /sdcard/Android/data/org.thoughtcrime.securesms/cache. A user might be under the impression (especially if using expiring messages) that these messages are wiped from the device if they are deleted from the conversation within Signal.

Since this is stored on the (emulated) SD card, all apps on the phone can read these photos.

### Steps to reproduce
- Press the Attach/clip button
- Select "Camera"
- Take a photo and send it
- Delete the message in Signal or let it expire
- The photos still persist in the file system

**Expected result:** Do not save photos to the file system unless explicitly choosing to do so by pressing the photo and select the save icon.

### Screenshots
![signal](https://user-images.githubusercontent.com/8736529/39053897-7dcb599c-44b0-11e8-9a82-66d4b569f62a.png)

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.18.3

### Link to debug log

[debug.txt](https://github.com/signalapp/Signal-Android/files/1932286/debug.txt)

**Comment by moxie0** [comment]
This is the intended functionality. What you're using is not the "built in camera" functionality, but the OS system camera. There's no way to make that encrypted, but if you use the little camera icon in the input field, we have control over that.

**Comment by p4nci** [comment]
for tthe sake of completeness, the differences between "built in camera" (little camera icon in the input field=quick camera) and "OS system camera":
https://community.signalusers.org/t/does-anyone-like-the-quick-camera-functionality-on-android/791
