### ISSUE TITLE
Onboarding Flow makes it easy to get trapped in a consent loop

### ISSUE THREAD

**Issue by colemickens** [signalapp/Signal-Android#7713]
When setting up an account, this happens when asking for permission to read SMSes for the verification process.

The app pops it's own dialog saying "We're going to ask for permissions." If you press "Continue", Android then asks for permissions whereupon you can "Deny". Signal then properly falls back to manual code verification.

However, I didn't even want to press "Continue". "Not Now" or "No" or whatever the option is should have just fallen into the same flow as if I Deny through Android. Instead, I was just stuck, unable to proceed.

To be honest, for the first 5 minutes I was losing hope and worrying that Signal was another app that wanted to aggressively skim data from my phone. I don't think that now, of course, but it was jarring.

**Comment by moxie0** [comment]
Thanks, this is fixed in 4.20. Please try not to delete the issue template next time.
