### ISSUE TITLE
Signal switches on data during calls when in Wi-Fi

### ISSUE THREAD

**Issue by soulstenance** [signalapp/Signal-Android#7717]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I am in a call with both Wi-Fi and data enabled, data will automatically switch on (like when you receive or send an MMS). This seems to use unnecessary amounts of data data instead of the available Wi-Fi although I haven't verified whether the usage is counted by my carrier or if it's an erroneous calculation by my phone.

### Steps to reproduce
- enable both data and Wi-Fi
- Make a call via Signal

**Actual result:** Both Wi-Fi and data are on simultaneously.
**Expected result:** Only Wi-Fi should be on, if it's available.

### Screenshots
https://www.dropbox.com/s/jq6x1oubr4louf7/20180421_162535.jpg?dl=0

### Device info
**Device:** Samsung Galaxy S9+
**Android version:** 8.0
**Signal version:** 4.18.3

### Link to debug log
https://debuglogs.org/8517dac9c3343b2ce9fd7d1eaae7c58fbf3371665f08501649adb0983fce8e19

**Comment by porjo** [comment]
I've encountered a similar problem. In my case, I've set Signal to only use mobile data for images yet my data usage screen shows Signal suddenly consuming gigs of data in the last 24hrs.
<img width=150 src='https://user-images.githubusercontent.com/1296987/39096130-0cef9c7c-464c-11e8-93aa-1d36ddc8e25a.png'><img width=150 src='https://user-images.githubusercontent.com/1296987/39096131-0d0b8360-464c-11e8-9c41-b9a77148d273.png'>

**Comment by moxie0** [comment]
@soulstenance This is currently the intended behavior. webrtc will attempt to establish connectivity on all of the available interfaces and route data using the mechanism that's working the most reliably. I think they try to weight wifi heavily, but if you have a bad signal (or walk away from the network), it'll switch to data. I'm not sure we could change it if we wanted to, but you can discuss on the forum if you think that would be possible or preferable.

**Comment by soulstenance** [comment]
@moxie0 I thought that was the case, but losing Wi-Fi causes the call to drop anyways, so it's intended purpose doesn't even work in that case. It would make more sense to give 100% priority to Wi-Fi and 0% to cellular, since some of us have limited data plans. Or at least a setting so the user can choose.

@johanw666 At least on Samsung Android there's a setting to switch on data if Wi-Fi is weak,so I have no problem there. What bugs me is when Wi-Fi is fine but it uses data anyways. Only happens with Signal.

**Comment by quaqo** [comment]
Same here, only happens with Signal. I have a 1 Gbps fiber connection both at home and work, but calling throu Signal always switch on data (4G/LTE, which is fast, but not as fast as my fiber optic connection).

Since 4G mobile data is pricey I'd like to use WiFi obviously. I restorted to use Duo, but I made Signal my first choice for messaging and made a lot of friends/relative switch from WhatsApp/Duo/Skype for Mobile... This "issue" that consumes data is making it a little awkard.

**Comment by JsBergbau** [comment]
Is there anything new about this issue? Its really annoying that signal uses mobile data. 
My Wifi
![grafik](https://user-images.githubusercontent.com/37013344/105404754-a0239380-5c2a-11eb-850c-54386e725c7a.png)

Despite this good network signal uses mobile data and that even when creating the call, not phoning yet

![grafik](https://user-images.githubusercontent.com/37013344/105404887-c812f700-5c2a-11eb-82fb-f0556cfc46c9.png)

**Comment by JsBergbau** [comment]
Next to the Wifi AP

![grafik](https://user-images.githubusercontent.com/37013344/105405343-5ab39600-5c2b-11eb-9136-dea0fb63d6ee.png)

However Signal still uses mobile data even when call is not even established

![grafik](https://user-images.githubusercontent.com/37013344/105405569-93536f80-5c2b-11eb-9ac9-74aebd1814dd.png)

**Comment by soulstenance** [comment]
> Is there anything new about this issue? Its really annoying that signal uses mobile data.
> My Wifi
> ![grafik](https://user-images.githubusercontent.com/37013344/105404754-a0239380-5c2a-11eb-850c-54386e725c7a.png)
> 
> Despite this good network signal uses mobile data and that even when creating the call, not phoning yet
> 
> ![grafik](https://user-images.githubusercontent.com/37013344/105404887-c812f700-5c2a-11eb-82fb-f0556cfc46c9.png)

I haven't noticed any issues with data being consumed while on WiFi. If it is indeed an issue for you your best bet is to toggle off data during such a call until the bug is fixed. I'd also check your data usage for that particular day with your cell carrier as the data usage that your phone shows may not be accurate.

**Comment by JsBergbau** [comment]
A lot of carriers bill you in chunks. So it could happen that even only 1 Byte is transmitted you're billed using 1 MB. So if you try to call somebody 5 times,  MB of data is charged. So this behaviour should be fixed quite soon. A lot of people are currently moving from Whatsapp to Signal. If they notice, that Signal costs then a lot of data despite having Wifi, they soon will leave. That should be avoided by all means.

**Comment by soulstenance** [comment]
> A lot of carriers bill you in chunks. So it could happen that even only 1 Byte is transmitted you're billed using 1 MB. So if you try to call somebody 5 times, MB of data is charged. So this behaviour should be fixed quite soon. A lot of people are currently moving from Whatsapp to Signal. If they notice, that Signal costs then a lot of data despite having Wifi, they soon will leave. That should be avoided by all means.

To be fair if individual MB of data is a concern to you or if you're on a pay per use plan it'd probably be smart to just always have data off unless you specifically need it, Signal notwithstanding. Problem solved. I did this back when I had a very small data plan.

**Comment by JsBergbau** [comment]
I have 2 GB included in my dataplan, but happening this 5 times a day is 150 MB / month or 7,5 % of my dataplan for nothing. To be honest, I don't know in what chunks my provider bills. 
I just try to keep that users in mind that go back to whatsapp because of such issues. 
Whatsapp for example has even very good call quality when using a limited bandwith of 32 kBit/s. With signal sadly the voice is so delayed or interrupted that there is no real call possible.

**Comment by soulstenance** [comment]
Hmm well then your best bet would be to just double check that data is indeed being used. If so, then maybe open a new ticket targeting your specific issue of data being used while on WiFi.

**Comment by soulstenance** [comment]
@JsBergbau Here's a screenshot of my data usage in the last hour after about a 5 minute video call. As you can see Signal exclusively used WiFi in spite of both data and WiFi being on. So your issue may either be phone related or you're on an unstable WiFi network.

I do believe this feature is pointless though as there is no evidence to suggest that having both on will prevent a call drop when leaving WiFi. For me it drops every time in spite of this. So if that is indeed its purpose the whole idea should be scrapped. In any case it takes like 2 seconds to call a person back and if you know you're leaving WiFi you should assume it's going to drop. The same happens with cellular calls when using WiFi calling.
![signal-2021-01-23-180058](https://user-images.githubusercontent.com/37247491/105616623-67102e00-5da6-11eb-94d5-dacd273fce76.jpeg)
