### ISSUE TITLE
Disappearing messages - not vanishing for sender

### ISSUE THREAD

**Issue by chynric** [signalapp/Signal-Android#7719]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In one specific signal group disappearing messages are not vanishing after the setting any time. The sender only is affected. The received message is disappearing for the recipients though.
There is only one specific group affected so far, which was created more than half year ago. In other groups disappearing messages is working as intended.

### Steps to reproduce
- Setting timer for disappearing messages to 10 sec
- sending a message in one specific group

**Actual result:** the message is not disappearing after 10 sec for the sender, for all other group members the message disappears after 10 sec as expected; the hourglass for the sender remains full, no timer for disappearing of the message is displayed in the message details
**Expected result:** the message disappears for all groupe members, including the sender

### Screenshots

![signal-2018](https://user-images.githubusercontent.com/36757003/39094240-09590f4a-465f-11e8-8ae7-f1e0f9be71f5.png)

### Device info

**Device:** HTC U11 life
**Android version:** 8.0.0
**Signal version:** 4.19.1

### Link to debug log
https://debuglogs.org/2da9e20c0f920b4eff4343bb4d57efda3b2b9586fddd29c25dd0337f6fb87eee

**Comment by moxie0** [comment]
Thanks! fixed in 4.20

**Comment by chynric** [comment]
Many thanks Moxie :)
