### ISSUE TITLE
Notifications for messages while locked are not cleared when app is unlocked and messages are read

### ISSUE THREAD

**Issue by burntcookie90** [signalapp/Signal-Android#7724]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you receive a message while the application is locked (via fingerprint in this case), you receive a notification saying "locked message". If you open the application, unlock and read the message, the notification does not go away.

### Steps to reproduce
- Lock signal (with fingerprint for this specific scenario)
- Receive Signal message
- Open notification shade, see "Locked message" notification
- Open Signal
- Unlock Signal via fingerprint
- Read message
- Open notification shade
- Message notification, now unlocked, still exists in notification shade

**Actual result:** Shows notification for read message
**Expected result:** Should remove notification for read message

### Device info
**Device:** Google Pixel 2XL
**Android version:** 8.1.0
**Signal version:** 4.19.1

**Comment by moxie0** [comment]
I'm unable to reproduce this. Can you check your steps to reproduce?

**Comment by burntcookie90** [comment]
Hey @moxie0 , I was able to reproduce by selecting the notification from the lock screen this time. It seems like it reposts the notification after the unlock or something. I might dive into the code tonight to see if I can find the issue.

**Comment by breversa** [comment]
I have the same issue with :
**Device**: LG G4 H815
**Android version**: 6.0.1/LineageOS 13
**Signal version**: 4.23.4

**Comment by neilstephens** [comment]
Still getting this. Android 8.1, nexus 5x.
