### ISSUE TITLE
Archived conversations 

### ISSUE THREAD

**Issue by reno-a** [signalapp/Signal-Android#7736]
Signal 4.18.3

How to access archived messages?
Archived conversations are available at the end of conversations.
It's not user friendly. Maybe a upcoming release will also add a menu entry?

**Comment by 2-4601** [comment]
Thanks for the suggestion, we use the [community forums](https://community.signalusers.org/) (it has a GitHub login) for feature requests and this issue tracker only for bugs. Check out the issue template for more info.
