### ISSUE TITLE
MMS containing multiple images shows no indication of it in conversation

### ISSUE THREAD

**Issue by chekovma** [signalapp/Signal-Android#7738]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ depends on your point of view ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving an MMS that contains more than one picture attachment the conversation only shows the first attachment and gives no indication that more than one is present.

### Steps to reproduce
- receive mms message with more than one picture

**Actual result:** 
first picture is shown in conversation.  only way to view other pictures is to check in "all media" or to click on picture and swipe.  no indication that more than one picture exists is given, even after being clicked on.

**Expected result:** 
All included images are displayed side by side inline in the conversation.  At the very list an icon showing multiple attachments should be displayed.  Once picture is clicked indication should be given that more items exist to be swiped to (arrows?)

### Device info
**Device:** Samsung Galaxy S5
**Android version:** Lineage 7.1
**Signal version:** 4.18.3

**Comment by FeuRenard** [comment]
Just for reference: #1300 (original issue)

**Comment by moxie0** [comment]
This is the intended functionality. It's possible that we should support messages with multiple attachments, perhaps even of multiple types, but please use the forums to discuss new functionality. Thanks!
