### ISSUE TITLE
Random authentication requests in iOS app

### ISSUE THREAD

**Issue by rmathus4** [signalapp/Signal-Android#7739]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal asks for fingerprint authentication randomly when typing or in a call.

### Steps to reproduce
- Ensure that the fingerprint authentication is turned on
- Start a call/video call.
- Chat for 30 minutes or more.

**Actual result:** 
Randomly, the fingerprint notification will appear in the call.  This typically happens after 30 minutes or so but it's completely random when it does.  I'm not switching networks or moving around so not sure what actually triggers it.  I do know this was not present in the previous version of the iOS app if that helps at all.

**Expected result:** 
Don't ask for authentication unless I close the app or do something else.

### Device info
**Device:** iPhone 6s
**Signal version:** 2.23.4

### Link to debug log
Will attempt to get one when this occurs again.

**Comment by mawed** [comment]
@rmathus4 
Please post your iOS-issue into the iOS-repository (https://github.com/signalapp/Signal-iOS) and close this issue.

**Comment by rmathus4** [comment]
My fault.  Didn't realize I was under Android.  Sorry!
