### ISSUE TITLE
 Building Signal 4.19.3 fails: testGetItemIdEquals FAILED

### ISSUE THREAD

**Issue by cplk2** [signalapp/Signal-Android#7742]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Build fails on Signal 4.19.1 and 4.19.3 with following error:

```
org.thoughtcrime.securesms.ConversationAdapterTest > testGetItemIdEquals FAILED
    java.lang.NullPointerException at ConversationAdapterTest.java:29

27 tests completed, 1 failed
:testPlayDebugUnitTest FAILED
:assembleWebsiteDescriptor

FAILURE: Build failed with an exception.
```

The build was successful on 4.16.4 using the exact same build toolchain (the build uses gradle : ./gradlew build assembleWebsiteRelease assembleWebsiteDebug)

### Steps to reproduce

You can find all the steps used to reproduce this on my .gitlab-ci.yml at https://git.legeox.net/capslock/signal-gcm-less/blob/master/.gitlab-ci.yml. (all the commands are run on a debian:latest docker image)

**Actual result:** Build fails
**Expected result:** Build succeeds

### Link to debug log

https://git.legeox.net/capslock/signal-gcm-less/-/jobs/65/raw

**Comment by 2-4601** [comment]
4.19.3 fails for me too when I run: 
```
./gradlew build assembleWebsiteRelease assembleWebsiteDebug
```

Related #6652

**Comment by motatuc** [comment]
`./gradlew assemblerelease` should work.

**Comment by moxie0** [comment]
remove 'build' from that command

**Comment by cplk2** [comment]
Thanks a lot, removing "build" from command line did the trick
