### ISSUE TITLE
Cannot run a new server ( got an error for messegeCache )

### ISSUE THREAD

**Issue by kuala-lumpur1** [signalapp/Signal-Android#7743]
Hi,

I'm facing some difficulties to run signal-server and there's no an issue section on Signal-Server page so i thought to write it here.

I'm trying to run the new server after the modification made for messageCache but i got an error while running the file.

messageCache may not be null

![confignull](https://user-images.githubusercontent.com/35842753/39353726-355465da-4a11-11e8-84db-2560a208ea96.JPG)

is there a new configuration need to be added for messageCache on the sample.yml file ?

thank you .

**Comment by 2-4601** [comment]
Hi, this issue tracker is only for the bugs of the Android client. Please go to the forums: https://community.signalusers.org/c/development/server-development

**Comment by 2-4601** [comment]
The tracker was closed because the server is not officially supported. You can ask help from other users on the forums.
