### ISSUE TITLE
EmojiTextView regression

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#7744]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Message texts shown in the conversation list show part of an emoji when there is an emoji in the truncated text, see screenshots.

### Steps to reproduce
- send or receive a somewhat longer messages with an emoji at the end
- check the conversation list

**Actual result:** emoji partially visible after the ellipsis
**Expected result:** emoji should not be visible

This is a regression caused by 6fbbc9d078b1d3edfa3c738fec82e44b36febeae.

### Screenshots
The full message is four times 0-9 and an emoji at the end.
![previewbad](https://user-images.githubusercontent.com/3845150/39396531-07885d52-4af0-11e8-94c4-19b46cb28c00.png)
**bug: emoji partially visible after the ellipsis**

![previewgood](https://user-images.githubusercontent.com/3845150/39396532-0a6b4da4-4af0-11e8-81f3-335db490e6dc.png)
**correct: no emoji visible**

### Device info
**Device:** Moto G5S & Virtual Device (Pixel)
**Android version:** 7.1.1 (both)
**Signal version:** 4.19.3

**Comment by cascheberg** [comment]
@greyson-signal The issue with the emojis is resolved in 4.20.4, but now for some messages the ellipsis are not shown although they should be.

**Comment by greyson-signal** [comment]
@cascheberg I believe that issue was pre-existing and not a result of 07e8ae716c3233f62de59b409d0c2f017f9ebb16. I'm looking into it!

**Comment by 2-4601** [comment]
I remember the ellipsization has been a PITA before:
See #3266, #3765, #3718, #3812, e145b8171d81d38939633ffe90c4e61168dae595

**Comment by cascheberg** [comment]
The issues with the ellipsis and also my performance issu that I mentioned in #7839 were gone after I enabled system emoji. I am still running 4.20.4, so I did not test your latest changes yet.
