### ISSUE TITLE
Signal mostly blocked in Russia

### ISSUE THREAD

**Issue by leedoyle** [signalapp/Signal-Android#7745]
Due to Roskomnadzor action against Amazon and Google networks used by Telegram to circumvent its ban in Russia (method previously used by Signal in other countries), most of Signal's functionality is blocked, at least for large ISPs. 
Currently, only **basic text messaging is possible** - without voice messaging, video or photo sharing(photo and video sharing may still work for some ISPs) . 
Signal calls also don't work anymore for many (perhaps for most) Russian  ISPs. 

Please consider handling this issue, e.g. by directing Russian Signal traffic through the servers that are  not affected (maybe the ones who successfully handle text messaging at the time of writing?).
Hopefully, the freedom of speech will survive in Russia - along with its acolyte, Signal messenger.

**Comment by moxie0** [comment]
Thanks @leedoyle, but please try not to delete the issue template in the future. We're aware of these issues, feel free to start a discussion on the forums if you'd like.

**Comment by leedoyle** [comment]
@moxie0 @moxie-signal Signal voice calling is working very unreliable in Russia, like in 1 success out of 7 attempts.
