### ISSUE TITLE
Empty conversation list when backup is initiated at app's startup

### ISSUE THREAD

**Issue by scienmind** [signalapp/Signal-Android#7747]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversation list is empty if full backup triggered on app startup

### Steps to reproduce
- Enable backups on a phone with large database (~3.5GB)
- Often the backup alarm will be skipped, and couple-days of delay will be present since the last backup
- Reboot the phone, and open Signal after the boot
- Auto backup will be triggered

**Actual result:** Opening Signal results in empty conversation list until the backup is finished, and with large DB it can take up to 30min. During that time it looks like all the conversations are disappeared.
**Expected result:** Conversation list is visible during backup, allowing normal user operation during backup.

Happened several times so far, always after the scenario described above

### Screenshots
![screenshot_20180430-084734](https://user-images.githubusercontent.com/11633330/39426741-ad8cf466-4c89-11e8-8c1e-540a0e93f9b4.jpg)

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0
**Signal version:** 4.19.3

### Link to debug log
https://privatebin.net/?8db1f726abb33049#MVdcdz2zGgNlZzey93o8GOnz2F0NxcCJ675IyuR7Fbk=

**Comment by eb053049** [comment]
This same issue affects Nexus 5x running Android 8.0 and Signal 4.19.3. I have not been able to complete any backups since the new encrypted backups came out, and the plaintext export option is gone.

**Comment by velosol** [comment]
eb053049 posted another debug log under #7813 (https://debuglogs.org/76984822f8a24bc7332d582d4edf49915680ed4ece4ecf5193ff99cdb065ded3 ) for this issue.

@scienmind Do the backups successfully complete when you experience this bug?  You can check by looking under the backup menu item and it will say "Last Backup: [Date]" instead of "Last Backup: Never"?

**Comment by strugee** [comment]
@velosol I'm not experiencing this bug right at this second, for obvious reasons, but IIRC from when I HAVE experienced it the backup has completed, at least some of the time. Once it gets to the point where it says "x/y messages" or something the interface goes back to normal. It's just "preparing backup..." that causes the interface to be blank.

**Comment by scienmind** [comment]
@velosol The backups complete successfully for me despite the bug (although, I haven't tested the actual restore on a new device with them). 
The issue I'm facing is that the conversation list isn't visually accessible for quite a while if backup starts right after reboot, before I have a chance to open the app and preload the conversation list into a working state.
