### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Hintsmth** [signalapp/Signal-Android#7750]
Hello! I'm from Crimea. Google Play is blocked in my country. Where can I find a direct download of Signal?

**Comment by CompSciMaj13** [comment]
Heres the link: https://signal.org/android/apk/

#### But by the way: 
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

**Comment by Hintsmth** [comment]
I'm terribly sorry! Thanks for your quick response. :)
