### ISSUE TITLE
Enable to use front camera for scanning QR codes

### ISSUE THREAD

**Issue by denisgolius** [signalapp/Signal-Android#7752]
Enable to use front camera for scanning QR codes.

Many smartphones have 2 cameras, but after some times main camera may break and than no chances to scan QR code from Desktop client on phone. I think will be good feature to enable using front camera as it done in Viber client for smartphones. 

PS: this problem I got on last week...

**Comment by muller** [comment]
here is the link to the request https://whispersystems.discoursehosting.net/t/enable-to-use-front-camera-for-scanning-qr-code/2781
