### ISSUE TITLE
Force SMS for Specific User?

### ISSUE THREAD

**Issue by damiong28** [signalapp/Signal-Android#7753]
A friend of mine has stopped using signal without deregistering. Unfortunately that means every time I attempt to send them a message, I have to remember to manually move from "Signal" to "Insecure SMS" messaging for them to get my messages at all. Is there a way that I can override this setting for that number specifically?

**Comment by PiCob** [comment]
Seriously..., did you even bother to read the issue template you deleted? Apparently you didn't (so don't expect an answer here), this is not a support forum. By the way: Your question has been addressed a plethora of times.

**Comment by moxie0** [comment]
@damiong28 For Q&A or support, please use the support center or the forums. Thanks!
