### ISSUE TITLE
Crash when tapping on quoted reply

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7756]
Posting from mobile...

Signal crashes when I tap repeatedly on a quote reply. Doing so selects the message above the reply for some reason, then hitting the back arrow makes signal crash.

There should be 3-4 crashes in this log

https://debuglogs.org/5b8077ae06735a9135679a47958f81addb037dcc34f4b2a0ee21c0a007a14ca3

Signal 4.19.3
Android 7
Moto G4 play

**Comment by greyson-signal** [comment]
Crash, for posterity:
```
05-02 20:16:37.025 23383 23383 E AndroidRuntime: FATAL EXCEPTION: main
05-02 20:16:37.025 23383 23383 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 23383
05-02 20:16:37.025 23383 23383 E AndroidRuntime: java.lang.IllegalStateException: Fragment ConversationFragment{8659ca0} not attached to Activity
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.support.v4.app.Fragment.getResources(Fragment.java:608)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationFragment$ConversationFragmentItemClickListener$1.onPostExecute(ConversationFragment.java:633)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationFragment$ConversationFragmentItemClickListener$1.onPostExecute(ConversationFragment.java:620)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:660)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
05-02 20:16:37.025 23383 23383 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
``

**Comment by greyson-signal** [comment]
@dcherian Just wanted to verify something. When you click a quote bubble, the intent is that it should highlight the message that is being quoted.

When you say "Doing so selects the message above the reply for some reason"  -- is it highlighting the wrong message? Or were you just confused about the intent of the highlight in general? Just want to know if there's a bug in addition to the crash :)

**Comment by greyson-signal** [comment]
Crash fixed in 4.20.

**Comment by dcherian** [comment]
I had no expectations. I was playing twitchy fingers 😂. It shouldn't do anything since multiple clicks on a normal message don't do anything. I was surprised it selected the message above the reply

**Comment by dcherian** [comment]
Oh.... Tapping on the reply takes me to the message that was quoted. That makes sense. I was quoting the most recent message, that's why it was picking that repeatedly.

**Comment by greyson-signal** [comment]
@dcherian Ah good to hear - thank you for finding this crash! And yeah, the idea is that tapping on a quote bubble brings you to the message that was quoted, forming something like a little message thread. I hope that this newfound discovery of quoted-reply behavior enriches your messaging experience :smile:
