### ISSUE TITLE
Import encrypted backups after registering Signal

### ISSUE THREAD

**Issue by DarthSpock** [signalapp/Signal-Android#7757]
-  [x] I have searched open and closed issues for duplicates
-  [x] I am submitting a bug report for existing functionality that does not work as intended
-  [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
-  [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

There is no option to import encrypted backups once Signal is registered. The currently existing restore process is broken, See #7637. An option to restore encrypted backups should exist after registering if Signal fails to prompt for a passphrase to restore messages. I consider this a bug because there is no other method of restoring encrypted backups in the current version of Signal.

Backup Signal messages on device (Metro LG Stylo 2 in my case) after removing SD card. (removal necessary to due another existing bug.)
Reinstall SD Card. 
Copy backup to SD Card
Remove SD Card
Install SD card on new device. (For me, Sprint LG G6)
Copy or Move backup from SD card into System folder directly as expected in previous versions of Signal
Install Signal from Google Play Store
Open Signal
Expect passphrase to appear (none does) per [instructions](https://support.signal.org/hc/en-us/articles/212535818-What-do-I-do-if-I-have-a-new-phone-or-change-my-number-)
Complete Registration
Open Import 
See that encrypted backups can't be restored but plain text can.

**Actual result:** No option exists after registering to import encrypted backups without generating a new passphrase
**Expected result:** Have an option to import encrypted backups after registering

**Device:** LG Stylo 2 to LG G6
**Android version:** 7.0.0
**Signal version:** 4.19.3 (Both phones)

### Link to debug log
No debug log because no information to pass into debug log as option is unavailable

**Comment by moxie0** [comment]
This is the intended functionality. If you have feature requests, please post those to the forum. GH is only for intended functionality that is not working as expected. For instance, if we had *intended* for there to be a way to restore backups to an existing install, but it just wasn't showing up for some reason, that would be a bug. If there isn't existing functionality, but you'd like it, that's a feature request. Thanks!

**Comment by darmbrust** [comment]
Well, you are ignoring that the suggested instructions don't work.  
I have the same issue as this poster... the backup / restore functionality of Signal is quite crap now.
I'm trying to migrate from one phone to another.  Made the backup.  Moved the file.  Placed it into the same Signal / Backups folder path.
Installed Signal.... and nothing.
It never prompts me to restore my backup.

**Comment by darmbrust** [comment]
As an FYI, for anyone else encountering this issue with this terrible backup / restore design.

If you put your backup file on the phone storage under Signal/Backups/ - it won't find it.  Cause why would it think to look in the place where you copied it from.  (facepalm 1)
If you put your backup file on a SD Card, under Signal/Backups/ - it won't find it.  Cause hey, why look there?  (facepalm 2)

And god forbid we be able to tell it where the backup file is by browsing....

HOWEVER.  If you put your backup under Signal/Backups/ on your SD Card, and then UNMOUNT your SD Card - and kill Signal, and restart it (prior to registering) - now, magically, it will find your backup file.

This tip thanks to frustrated folks over on reddit: https://www.reddit.com/r/signal/comments/8hxbww/signal_doesnt_find_backup_to_restore/

No idea how on earth this is supposed to work for someone without an SD card slot.

**Comment by nekromoff** [comment]
+1 for resolving this tragic functionality

**Comment by nekromoff** [comment]
https://github.com/xeals/signal-back

**Comment by moxie0** [comment]
@nekromoff Please read the contributing guidelines before posting in the issue tracker again. Thanks!
