### ISSUE TITLE
Unable to create plain text backups

### ISSUE THREAD

**Issue by DarthSpock** [signalapp/Signal-Android#7758]
- [x]  I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
There was an option to create plain text backups in 4.16.9 and below and no longer exists in 4.17.5 and above. Due to issues with encrypted backups, see #7637 and #7757, an option to create a plain-text backups should exist as it used to. Since this capability used to exist, this should be considered a bug and NOT be designated by-design. (Users should have the power of choice).

### Steps to reproduce
- using hyphens as bullet points 
- list the steps
- that reproduce the bug
 
Open Signal
Open Settings
Open Chats and Media
Enable Chat Backup
Write down passphrase
Create backup

**Actual result:** I have no prompt to choose between plain text backup and encrypted backup
**Expected result:** I should have the option to choose to create a plain text backup or an encrypted backup using the generated passphrase

### Device info

**Device:** All devices affected but has personally impacted me with LG Stylo 2 and LG G6
**Android version:** 7.0.0
**Signal version:** 4.19.3 (all devices)

### Link to debug log

No debug log due to no ability to capture information for a previously existing capability that is no longer there.

**Comment by moxie0** [comment]
This is the intended functionality. If there is intended functionality that is working as intended, but you want it to be different, please use the forums for that. Thanks!
