### ISSUE TITLE
Don't receive notifcation sometimes

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#7759]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I don't receive the notification of messages in Signal if the app is not opened. with open i mean that im chatting with someone if its closed or in background i dont receive messages. I have got 2 phones so you will see 2 debug logs. In the Device info you will see 1- and 2 - this means first phone and second phone

### Steps to reproduce
I don't really know 

**Actual result:** Don't receive the notifications when i get messages
**Expected result:** Should receive the notification

### Device info

**Device:** 1 - LG-H850 and 2 - HUAWEI VNS-L31
**Android version:** 1-  Android : 6.0.1 and 2 - Android : 7.0
**Signal version:** 1 - 4.19.3 and  2 - Signal  4.18.3

### Link to debug log
https://debuglogs.org/e875321a38fcd85581661530955619c07b521dbab846702d6f6481a4272b835d
 another debug log
https://debuglogs.org/03aa6a30a05e8e8ef594597580643d1179396aee66e06c188ddefb79fb437127

**Comment by leonardoporpora** [comment]
Done but still Have the same problem

**Comment by deutrino** [comment]
Are you running Signal Desktop as well?

**Comment by bme13** [comment]
Did you add Signal to the list of protected apps and restarted the phone? I noticed it is mentioned briefly in the Huawei specific setting, but could easily be missed.

**Comment by leonardoporpora** [comment]
I’m not running desktop app and yeah is in protected apps. I noticed that signal works perfectly after I make a debug log for 1/2 weeks than notification in background and if the app is closed don’t work

**Comment by leonardoporpora** [comment]
Any update? Let me know if there are other steps that I have to do

**Comment by a9e78rauijasdf** [comment]
I have the same issue on my OP 5T. On android 8. Sometimes the desktop app doesnt receive a message that i send - making them out of sync :/

**Comment by matijaGP** [comment]
Hi, I have the same issue on my OnePlus 3T. When phone is restarted, I get no notifications until signal is started manually. Android 8.0.0. OxygenOS 5.0.3. Signal 4.19.3. This phone doesn't have any type of startup manager exposed. Battery optimization options are same for all apps.

Seems like startup is broken. Two friends report having the very same issue, no notifications until Signal started, they have other phones tough, some Nokia and Huawei.

**Comment by matijaGP** [comment]
Hi @bme13 , thanks, but those arent applicable. I have doze turned off, and startup related things seem to be removed from user control lately. BTW, my other messanger apps are behaving from this point of view, they seem to be started with the system. I remember a long time ago google inbox behaving the same - notifications coming only after manual startup. I know that wont help, I'm just implying that startup seems to be having some issues :)

**Comment by 2-4601** [comment]
I've heard about issues with notifications on a Nokia 5 with Android Oreo. Trying out the suggestions in the support article didn't fix it. It is occasional. (Not my device so can't debug more.)
