### ISSUE TITLE
Mega.nz Integration for Live Backup

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-Android#7761]
Not a huge fan of Telegram Messenger, but one of its greatest features is its instant cloud integration.
Since such a feature in spite of being very functional compromises privacy, cloud services such as Mega with encryption in place could be a reliable alternative.

@moxie0

**Comment by jlund-signal** [comment]
There's an [existing thread on the community forum about this topic](https://community.signalusers.org/t/cloud-backup-option-to-google-drive-mega-etc/2798).

This issue tracker is for bugs, not feature requests. Please don't delete the template in the future. Thanks for the suggestion!
