### ISSUE TITLE
disturbing profile name question banner in group chat

### ISSUE THREAD

**Issue by bjacke** [signalapp/Signal-Android#7762]
ever since the user profile feature was added, in group chats there is a huge banner on top, which covers 1/3 of the chat screen, asking me if I want to make my profile name visible to the group. It could be "fixed" by making the profile name visible but I don't want to do that and I don't want to have 1/3 of the screen wasted with that question all the time.

I would expect that such a question could be clicked away by giving the option to say "no, thanks" once and then no longer see that huge question banner. Can this be fixed in a similar way?

**Comment by 2-4601** [comment]
Please try to follow the issue template when filing bugs. This feature request is being discussed here: https://community.signalusers.org/t/request-add-an-option-to-remove-the-nagging-make-your-profile-name-and-photo-visible-to-the-group-message/2311
