### ISSUE TITLE
Cannot restore previous chat databases onto current phone

### ISSUE THREAD

**Issue by risole** [signalapp/Signal-Android#7764]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot restore signal text threads (chat databases) from previous signal installations on two other phones into my current third phone.

### Steps to reproduce
- use Signal version 4.15.5 on phone A (OnePlus One) running Android Nougat for awhile, long enough to generate a 1.7MB file named SignalPlaintextBackup.xml when doing a backup of the chats
- Switch phones to phone B running Android Oreo 8.1.0 (A second OnePlus One running [custom firmware by Agent_fabulous](https://forum.xda-developers.com/oneplus-one/orig-development/rom-aosp-oreo-oneplus-one-t3666741))
- Install Signal 4.15.5 onto phone B
- attempt to restore 1.7MB file SignalPlaintextBackup.xml onto phone B (which fails as documented in issue #7430).
- continue to use Signal version 4.15.5 while waiting for an update that fixes issue #7430, thereby generating an additional collection of chats on phone B.
- leave the default setting for auto-update in the Google Play app enabled, so that Signal automatically gets updated while you are sleeping to version 4.18.3
- Switch phones to a third new phone (phone C: Moto X4 Android One) running Android Oreo 8.0.0 (stock firmware)
- Install Signal version 4.18.3 onto phone C.
- Attempt to restore 1.7MB file SignalPlaintextBackup.xml onto phone C (which fails because Signal version 4.18.3 now seems to lack the ability to import any Plaintext Backup file
- Continue to use Signal on phone C, thus generating a third collection of chats on phone C.
- You will now have 3 independent and mutually exclusive chat databases (generated from phones A, B, and C).

**Actual result:** Cannot restore previous chat databases onto your phone C (no functionality for this in version 4.18.3).
**Expected result:** Should be able to restore previous chat databases onto your phone C, thus merging 3 independent and mutually exclusive chat databases into a single chat database on your current phone (phone C).

### Device info

**Device:** Moto X4 Android One
**Android version:** 8.0.0
**Signal version:** 4.18.3

This may seem like a support request (it originated as a support request on 4/26/18) or a feature request, but I posted it here in spite of the guidance I found at https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md because after more than a week has passed since following that guidance ("Please do not ask support questions at the issue tracker. We want to help you using Signal and we have created our support system just for that. You can reach support by sending email to support@whispersystems.org"), I've received no reply nor even an automated acknowledgment of my message.

In my opinion, discarding previous functionality during version transitions from 4.15.5 to 4.18.3 where that functionality was purportedly available before (but was actually broken) is a bug, not a feature request or a support request, but I know there may be differing opinions on this.

**Comment by moxie0** [comment]
The plaintext import functionality has not been removed, although it probably will be in the future
