### ISSUE TITLE
[THANKS] For the hard work!

### ISSUE THREAD

**Issue by kepler2** [signalapp/Signal-Android#7767]
You can close the "issue" :)

Just wanted to say thanks for all your work. :1st_place_medal: 

1. **Send message** - check
2. **Send voice message** - check
3. **Send photo** - check
4. **Best encryption** - check
5. **Open-source** - check
6. **Works on older devices** - check
7. **Disappearing messages** - GREAT - check

Really appreciate your work guys. Have a nice weekend!

**Comment by Dyras** [comment]
I'm sure they appreciate the thanks, but they will probably appreciate it more if you post this at the forum 😃 
https://whispersystems.discoursehosting.net

**Comment by jlund-signal** [comment]
Thanks for the positive feedback!
