### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [signalapp/Signal-Android#7768]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by FeuRenard** [comment]
Related: #7755, #7588, #7440

**Comment by 2-4601** [comment]
As mentioned in the linked issues please use the forum for these kind of proposals: https://community.signalusers.org
