### ISSUE TITLE
Certain messages are not displayed in the inbox

### ISSUE THREAD

**Issue by sikand** [signalapp/Signal-Android#7769]
If I use Google Assistant to send a text, I never see the message in the signal inbox. Same with sending messages from the phone app, like I'm busy, please call back

ATT Samsung S9±

**Comment by jlund-signal** [comment]
Thanks for the submission, but please don't delete the issue template in the future.

This is also a duplicate of #7627, and there isn't anything that Signal can do to properly support this right now because Google Assistant does not provide the necessary APIs.

**Comment by anoxi** [comment]
Is there any hope to get an API from Google Assistant that these SMS messages get to the Signal App? Otherwise, I understand the only alternative is to switch SMS handling back to the native SMS app.
