### ISSUE TITLE
Signal 4.19.3 crashed on startup after trying to restore the data

### ISSUE THREAD

**Issue by DBGT-87** [signalapp/Signal-Android#7772]
### Bug description
Signal keep crashing on startup after restoring the database.

### Steps to reproduce
- I did a backup of Signal 4.19.3 through Titanium and Mybackup.
- When I tried to made a backup through Signal the backup always stops when the messages reaches 36000 or so, I have the phaseshare btw, but not the backup.
- I did a clean installation for my device Galaxy Note 4 N910C, stock ROM 6.0.1.
- After that I am unable to to restore my messages.
- Signal just keeps crashing on startup after restoring the "data only" or data+app".
- I tried to use Signal cleanup 4.15 then restoring the database only but nothing changed, the opening never changed: "Hello World" and there is no option to do.

**Actual result:** crashed on startup
**Expected result:** should starts normally

### Device info

**Device:** Samsung Galaxy Note 4 N910C
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by moxie0** [comment]
Can't do anything without a debug log, but it looks like you're trying to restore through tibackup? That's not supported, and Signal will crash if you try.
