### ISSUE TITLE
Signal crashing after restoring backup

### ISSUE THREAD

**Issue by DBGT-87** [signalapp/Signal-Android#7773]
Bug description
Signal keep crashing on startup after restoring the database.

Steps to reproduce
- I did a backup of Signal 4.19.3 through Titanium and Mybackup.
- When I tried to made a backup through Signal the backup always stops when the messages reaches 36000 or so, I have the passphrase btw, but not the backup.
- I did a clean installation for my device Galaxy Note 4 N910C, stock ROM 6.0.1.
- After that I am unable to to restore my messages.
- Signal just keeps crashing on startup after restoring the "data only" or data+app".
I tried to use Signal cleanup 4.15 then restoring the database only but nothing changed, the opening never changed: "Hello World" and there is no option to do.

Actual result: crashed on startup
Expected result: should starts normally

Device info
Device: Samsung Galaxy Note 4 N910C
Android version: 6.0.1
Signal version: 4.19.3

Link to the debug log:
https://debuglogs.org/1eb2e8825d047d7f1c2b0fc5d3ea60c89fad98e12b2a1450a9c9612ceb6bd236

**Comment by moxie0** [comment]
There is no crash in this debug log, please reopen if you get a valid debug log. But again, titanium backup is not supported. attempting to restore with tibackup will destroy your signal install.

**Comment by DBGT-87** [comment]
so my 40k+ messages are gone for good and there is no other way to get them back?

**Comment by PiCob** [comment]
@DBGT-87: Please have a look at the forum mentioned in the issue template. Chances are, that you find a way to restore them.
