### ISSUE TITLE
New feature request: support for flip phones

### ISSUE THREAD

**Issue by TopView** [signalapp/Signal-Android#7774]
`signal-cli `supports signal Register / Verify via txt or voice messages, rather than by the 2d bar code / smart phone combo.  For details please see [https://github.com/AsamK/signal-cli](https://github.com/AsamK/signal-cli) (scroll down under Usage).

For reasons of security and cost I don't keep a smart phone, but do have a simple flip phone.

Please, if you will, consider adding a method of registering and verifying that does not use the 2d bar code, but rather uses a simple method such as the one signal-cli uses, .. so that more people can use Signal.  

Thanks.

**Comment by haffenloher** [comment]
Please read the Contributing guidelines before posting and don't delete the issue template when opening an issue. Feature requests for Signal-Android are tracked in the community forum, not on GitHub.

**Comment by TopView** [comment]
Sorry, will move my request there.
