### ISSUE TITLE
Self chat to save messages, notes for personal use

### ISSUE THREAD

**Issue by mat-ale** [signalapp/Signal-Android#7776]
Hi all,

I'd like to propose a feature:
simply a Telegram-like feature to save messages in the cloud (encrypted of course) maybe in a self personal chat (as Telegram does).
Here is the Telegram feature I'm talking about: https://telegram.org/blog/albums-saved-messages#saved-messages

Best regards

**Comment by 2-4601** [comment]
Please don't remove the issue template when reporting bugs. Feature requests are discussed in the community forums, for this request please join this thread: https://community.signalusers.org/t/sync-messages-to-self-between-devices/2643
