### ISSUE TITLE
The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019

### ISSUE THREAD

**Issue by oittaa** [signalapp/Signal-Android#7778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019.

There was an earlier bug report (#6848) about moving to FCM, but Google hadn't deprecated GCM at the time. Maybe now is the time to make the transition. I feel like it shouldn't be left at the last minute as it isn't a huge code change, but the functionality is quite critical.

**Comment by moxie0** [comment]
We don't need an issue to track this, but thanks
