### ISSUE TITLE
disappearing messages persist as quotes

### ISSUE THREAD

**Issue by bellja** [signalapp/Signal-Android#7779]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
disappearing messages can persist after they have expired if they are quoted in another message.

### Steps to reproduce

-turn on disappearing messages in one of your conversations, preferably for more than 30 seconds, and with someone who is willing to test with you
-have your contact send you a message
-turn disappearing messages off
-before that messages disappears quote it and reply

**Actual result:** the original message disappears but will persist as a quote in a message that is not disappearing.
**Expected result:** messages that are meant to disappear should not be able to be preserved indefinitely as a quote
Possible solutions:

-When a disappearing message is quoted make that message inherit the disappearing status and expiration timer even if disappearing messages is currently set to off.
-Make disappearing messages not quotable

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.1.0 Security patch level May 5th 2018
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/886bb701c79b1fdbc11d57753fce8639009887beee76f80868be730a86c776d4

**Comment by moxie0** [comment]
This is the intended behavior. It's the same as if someone copied and pasted your disappearing message into a new message, took a photograph of your disappearing message and put it in a new message, paraphrased your disappearing message and put it into a new message, etc.
