### ISSUE TITLE
no password option for lock screen

### ISSUE THREAD

**Issue by eX00r** [signalapp/Signal-Android#7781]
Since I reinstalled signal in my lineage OS 14.1 phone there is no Option to set a lock screen password. The only options are "lock with Android lock screen" or "fingerprint". I want to set a password as it was possible before. What is this a bug or an update?

Thank you for your help.

**Comment by johanw666** [comment]
That is, unfortunately, intentional. And as with all other cases where functionality was removed that didn't show up in the changelogs.

**Comment by moxie0** [comment]
Please don't delete the issue template when filing issues, and try to stick to the forums or support center for Q&A, thanks!
