### ISSUE TITLE
Video losing file extension when forwarded from one chat to another

### ISSUE THREAD

**Issue by TopTenTiger** [signalapp/Signal-Android#7783]
Steps to reproduce
- Share a mp4 video with a contact
- Long press to select the video and tap the forward icon at the top
- Paste into another chat

**Actual result:** 
The video will be unplayable in the desktop client because the file extension goes missing (reportedly also in the ios client).

![capture1](https://user-images.githubusercontent.com/1303537/39889036-010b21ac-5497-11e8-8a11-895b1dc2eda9.png)

Filename before forwarding: signal-2018-05-10-191631.mp4
Filename after forwarding: signal-2018-05-10-191916.-

**Expected result:**
The video should retain the file extension and be playable in the client.

### Device info
**Device:** Sony Xperia XZ2 Compact
**Android version:** 8.0.0
**Signal version:** 4.19.3

**Comment by erik55** [comment]
I can confirm this. That happened to me yesterday.
Android 8.0.0
Signal 4.20.8
Phone Samsung Galaxy S7 SM-G930F

**Comment by greyson-signal** [comment]
The core issue here was fixed in 4.25, but there's a lingering issue where forwarded videos will lose their thumbnail. Created #8103 to track it.
