### ISSUE TITLE
[Feature Request] Send Individual Dissapearing Messages

### ISSUE THREAD

**Issue by trymeouteh** [signalapp/Signal-Android#7785]
It would be neat to be able to have the conversation dissapearing messages off or set to time X but be able to choose when you send a message to have it dissapear even if the  conversation dissapearing messages off or set to a different time.

**Comment by PiCob** [comment]
It would also be neat (and respectful) if you didn't delete the template.
This issue tracker is for **bugs, not feature requests** (like the template clearly says).

**Comment by jlund-signal** [comment]
Feel free to discuss this on the [community forum](https://community.signalusers.org).
