### ISSUE TITLE
Unable to create a conversation backup

### ISSUE THREAD

**Issue by korkosson** [signalapp/Signal-Android#7786]
### Bug description
When a conversation backup is initiated there is no backup created. It seems that the backup process is running (counting messages) but when the process is finished, it says "Last backup: Never" and no backup is created.
Note: Contacts are managed via CardDAV account. Tried with 2 different phones (same type) with the same results.

### Steps to reproduce
- Turn backup feature on.
- Initiate conversations backup.

**Actual result:** No backup created. GUI says "Last backup: Never", storage does not contain any Signal backup.
**Expected result:** Backup is created.

### Device info
**Device:** Motorola Moto G (5) (cedric)
**Android version:** 7.0.10
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/ca5b89147bc1ea35e41ea11faf30d0598e4f8d08a8d50cdf67691a8552e67fbe

**Comment by minnmann** [comment]
I think the relevant part is 
> java.io.IOException: Renaming temporary backup file failed!

If you have an SD card, that means this is probably a known bug and a duplicate of #7770, #7692. It should be fixed in 4.20.

Until 4.20 is released, the workaround is to eject the SD card (e.g. via the menu) and run the backup. I used this on a phone yesterday and it worked.

**Comment by korkosson** [comment]
Thanks for the advice, it's working as you've described. Looking forward to version 4.20 then.

I have searched in opened issues only, sorry for the duplicate bug report.

**Comment by jlund-signal** [comment]
No problem!

**Comment by yknip** [comment]
The suggested workaround fails for me on beta 4.19.3. Any idea when 4.20 will be released?

**Comment by korkosson** [comment]
It is still not working for me (Signal 4.20.9, Moto G5).

**Comment by minnmann** [comment]
It seems to be working for me - I also have a Moto G5, but running Signal 4.21.2. The phone is equipped with a SD card formatted as internal memory.

**Comment by korkosson** [comment]
Mine is formatted as external. Maybe there is some issue with SD cards mounted as external storage?

**Comment by haffenloher** [comment]
@korkosson Please post a debug log captured right after a backup fails so the developers can investigate.
