### ISSUE TITLE
Unable to create backup file

### ISSUE THREAD

**Issue by bjohas** [signalapp/Signal-Android#7789]
### Bug description

This is a bug report for 
> JobConsumer: java.io.IOException: Renaming temporary backup file failed!

The bug is already reported in comments on thread https://github.com/signalapp/Signal-Android/issues/7637, but the thread is about the ability to restore, rather than create, backups. Hence filing this as separate bug.

@johanw666 describes the bug in https://github.com/signalapp/Signal-Android/issues/7637:

> I tested again with 4.19.3, but now I can't make any backups at all with the official backup code:
> 
> 05-06 01:31:40.057 18198 18223 W JobConsumer: java.io.IOException: Renaming temporary backup file failed! 
> 05-06 01:31:40.057 18198 18223 W JobConsumer: at org.thoughtcrime.securesms.jobs.LocalBackupJob.onRun(LocalBackupJob.java:78) 
> 05-06 01:31:40.057 18198 18223 W JobConsumer: at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76) 
> 05-06 01:31:40.057 18198 18223 W JobConsumer: at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46) 
> 05-06 01:31:42.722 18198 18198 W PassphraseRequiredActionBarActivity: onPause() 
> Full log at https://debuglogs.org/bd90f10bfde12ca9778c1ecb82b37a0182f2db1acd8750d691ccc588312fe2a9 , what's the matter with that new log provider? Seems unable to process EOL's.

### Device info
**Android version:** 7.1.1.
**Signal version:** 4.19.3

Phone has external sd card present.

**Comment by haffenloher** [comment]
This is a dupe of #7786 and others, fixed in 4.20. Until then, the workaround seems to be to eject the SD card.

**Comment by bjohas** [comment]
Ah yes, so it is. I had searched for the log error message and only found the other thread. Thanks!
