### ISSUE TITLE
gradle wrapper does not work with Java 9, 10

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#7790]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal fails to build (`./gradlew build`) when using Java 9 or Java 10, like it is the default e.g. in Debian testing.

### Steps to reproduce
- On debian testing, install `default-jdk`
- Check out signal v4.19.3
- Run `./gradlew build`

**Actual result:** Gradle prints
```
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.
```
**Expected result:** The build should succeed.

**Comment by johanw666** [comment]
Which part of these lines in `build.gradle` is unclear:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by RalfJung** [comment]
Did you expect me to go read the entire source code before trying to compile Signal using a current version of Java?

The error message isn't very helpful, either.

**Comment by johanw666** [comment]
No, I expected you might read the relevant lines before opening an issue. And because some [censored deregatory word] at Oracle decided that backwards compatibility is something of the past Java 9 and 10 are likely to give a lot more iussues.

**Comment by haffenloher** [comment]
See also: https://stackoverflow.com/questions/49663507/how-to-fix-gradle-not-recognizing-java-10-on-linux

**Comment by igor2x** [comment]
In my humble opinion, this issue is not a bug, because Signal was designed to work with Java 8.

May I kindly suggest this issue to be closed down as bug report and invite you to continue discussion on [community forum](https://community.signalusers.org). There is a whole category dedicated to [Android-Development](https://community.signalusers.org/c/development/android-development).

**Comment by RalfJung** [comment]
@igor2x Thanks! The reason I reported it as a bug is that it wasn't at all clear that this is due to the Java version being too high. I mean, it complained about `10.0.1` not being a Java version at all. If it had said "Java 10 is too new, please use Java 8", I would not have opened an issue.

It seems that updating Gradle (but not otherwise supporting new Java version) should fix this as it means Gradle at least knows that 10 is a version of Java that exists.

**Comment by ahelwer** [comment]
@johanw666 your first response was incredibly condescending. Be better.

**Comment by johanw666** [comment]
Yes, sorry about that.

**Comment by moxie0** [comment]
Thanks, we're on Java 8 right now, so we're not yet supporting 9 or 10. I've updated the build instructions
