### ISSUE TITLE
Store media to SD card to reduce internal storage usage

### ISSUE THREAD

**Issue by breznak** [signalapp/Signal-Android#7792]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

This is a "duplicate" of the pruned https://github.com/signalapp/Signal-Android/issues/4297 
Signal is #1 consumer of my limited internal memory, now ~4GB. 

### Steps to reproduce
**Expected result:** store media to SD card (if available), as does Spotify, WhatsApp etc. 

### Device info
**Android version:** 6.x
**Signal version:** 4.19.3

**Comment by nrizzio** [comment]
This is a feature request and feature requests are no longer accepted on the issue tracker.
