### ISSUE TITLE
In-app camera does not focus, pictures are not sharp

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7794]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
#5276 , #3575, #3767
Using the built-in camera, the focus appears to be lacking compared to the camera app. Also, the camera view appears more zoomed in than the regular camera app.

### Steps to reproduce
- Go to compose message
- Touch camera to take a picture

**Actual result:** Pictures are blurry and don't seem to focus
**Expected result:** Camera uses auto-focus and view equivalent to default camera app

### Device info
**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by moxie0** [comment]
The in-app camera app is meant to be "quick" by just using the preview data, but we should probably get rid of it and use the full system camera instead.
