### ISSUE TITLE
Deduplicate messages

### ISSUE THREAD

**Issue by devurandom** [signalapp/Signal-Android#780]
Currently TextSecure (2.0.1) can only import messages from the default Android SMS application once. Afterwards doing the same again results in duplicate messages. It would be nice to be able to deduplicate them.

I assume that going through the list of messages and comparing from, to, time and text would be sufficient. Then just delete everything except the first occurance.

Please excuse me, if this is a duplicate of another issue. It was hard to find good search terms, since "duplicate" occurs extremely often as "duplicate of issue #...".

**Comment by riyapenn** [comment]
Related user action: "I clicked the import button and while waiting I then clicked on the notification progress bar and it imported again. I assumed the notification bar would bring me to a different screen not kick off a load."

https://gist.github.com/1fd6592e5848fb3a4e76163ee0e4da3a (though looks like this log may have been captured too late)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
