### ISSUE TITLE
Missing documentation for plaintext import functionality

### ISSUE THREAD

**Issue by risole** [signalapp/Signal-Android#7804]
Issue #7764 described "Cannot restore previous chat databases onto current phone", and @moxie0 replied with "The plaintext import functionality has not been removed, although it probably will be in the future" and closed issue #7764.

I'm unable to find instructions for importing a plaintext file in existing documentation, so perhaps the issue is a problem not so much with the Signal-Android code base as it is with the documentation for same?

At https://support.signal.org/hc/en-us/articles/212535828-How-do-I-import-or-export-messages-on-Signal-Android- I see the following:

> Where is the option to import or export?
> For Signal Android version 4.16.9 and earlier, follow the steps below. For Signal Android version 4.17.5 and later, follow the [steps on the support page for backups](https://support.signal.org/hc/en-us/articles/360001890291).
> 

And at the referenced URL, I see only:

> What version of Signal has this option?
> This feature is available on Signal Android 4.17.5 and later.
> 
> How do I enable a backup? 
> 
> Open Signal.
> Tap on your menu.
> Select Settings.
> Select Chats and media.
> Tap Chat backups.
> Copy the 30-digit passphrase from left to right, top to bottom. You will need this passphrase in order to restore a backup.
> Confirm that you have written down the passphrase.
> Select Enable backups. 
> You can confirm whether or not your backup completed succesfully by checking the time of the Last backup.
> How do I restore from a backup? 
> You will only be able to restore your chat history on a new install of Signal. Signal will automatically detect your messages and media from a local backup and ask you to input the 30-digit passphrase prior to registration.
> ...

So I see nothing here about how to import a plaintext file. If such instructions exist, please feel free to close this issue and post a link to those instructions. But I'm unable to find them, so if they don't exist, please share such instructions with me and tell me where I can post a diff file for including such instructions in existing documentation. I'd be glad to help document it if I knew how to accomplish the plaintext import.

Thanks for all your hard work everyone! Signal is wonderful software!

**Comment by jlund-signal** [comment]
We don't use GitHub for support issues, but the Support Center documentation [has been updated](https://support.signal.org/hc/en-us/articles/360001890291). Look for "How do I restore from a legacy plaintext backup?" on the bottom of the page. Thanks for using Signal!
