### ISSUE TITLE
Pass Phrrase

### ISSUE THREAD

**Issue by Etweyede** [signalapp/Signal-Android#7807]
I am from a non developed country so I dont have problem with CIA or those people.

I use my phone with my 2 children since my wife die. They use the normal google message app and whatsapp and am the only one who use signal. I liked it because it have a pass phrase or password for message. I dont want my children to know the things i go through just to keep them alive.

I won best farmer award my price is a new phone but yesterday the whole family was happy but i am sad becouse now the pass phase is not showing. i cant allow my children to see that i have to sleep with another man just to get money to feed them, cloth them and put roof over their head. 

PLEASE I BEG YOU WITH THE LIGHT OF GOD SHOW ME HOW TO PUT THE PASS PHASE BACK SO I CAN HAVE  hPPY FAMILY. 

Sometimes you can build something but you will never know how it help other people. I am sorry that i am telling you all my life history but i need help. Thank you and God Bless

**Comment by 2-4601** [comment]
Sorry to hear about your situation. Feature requests are currently handled in the forum. I see you have already posted there so I'll close this in favor of that one.
