### ISSUE TITLE
Plaintext import functionality still broken in version 4.19.3

### ISSUE THREAD

**Issue by risole** [signalapp/Signal-Android#7814]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Plaintext import functionality still broken in version 4.19.3

When I attempt to import a SignalPlaintextBackup.xml file created in an earlier version of Signal, the Signal app crashes and I'm unable to determine whether or not the import operation completed importing all messages. I first attempted this operation in version 4.15.5, then again in a version between 4.15.5 and 4.19.3 (4.18.x?), and now most recently (today: May 17) again in 4.19.3. Signal has crashed in the same manner in all three attempts. As best I can recall, 4.18.x did not even have an option present in the menu for importing a plaintext backup file.

### Steps to reproduce
- launch Signal
- follow the steps in the documentation under "[How do I restore from a legacy plaintext backup?](https://support.signal.org/hc/en-us/articles/360001890291)"
- Signal crashes

**Actual result:** Signal crashes (Android Oreo 8.1.0 reports: Signal stopped responding)
**Expected result:** No crash. Some kind of message reporting: plaintext import completed successfully; 1859 messages imported in 100 threads (or something like that).

### Device info

**Device:** Moto X4 Android One
**Android version:** 8.1.0
**Signal version:** 4.19.3

### Link to debug log

[Signaldebuglog01.txt](https://github.com/signalapp/Signal-Android/files/2014968/Signaldebuglog01.txt)

**Comment by bme13** [comment]
Hi,

I've never used a plaintext backup so perhaps I'm wrong however your description confuses me. In your initial description you write you want to import a SignalPlaintextBackup.xml file. Which seems to be the name of a plaintext backup(xml). However in your second description you refer to that file as signal-XX-XX-XX-XX.backup which is to my knowledge an encrypted backup file. Aren't you trying to import an encrypted file as a plain text? This would also explain why you can't read the file. When you created that backup file, were you asked to provide a password?

**Comment by CryptoSentinal** [comment]
Yeah I did get and write down a code to decrypt the backup. I don't see an option in 4.19.3 to create a plaintext.xml backup file. Or do I have to go digging into my phones file structure to find it?
