### ISSUE TITLE
Keeps asking to be default sms despite me approving it every time

### ISSUE THREAD

**Issue by nikpage** [signalapp/Signal-Android#7817]
- [ ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Frequent requests to he default sms on Redmi phone with Android 7 and Miui 9

### Steps to reproduce
1 Open sigbal
2 approve request to be default sms app
3 some time later use signal again. 
4 get same request again
5 and again... And... Until I give up on signal completely. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by 2-4601** [comment]
Could you check that Signal is available as an SMS app in your phone's system settings? See http://en.miui.com/thread-1794471-1-1.html

**Comment by moxie0** [comment]
Closing for now, please reopen if you're able to provide the requested information

**Comment by nikpage** [comment]
Hi

Sorry - I missed this.

Yes, Signal has sms selected. I can't find the default sms app in the
permissions list to deselect there. Might that be the problem?
