### ISSUE TITLE
Add support for Signal registration in Greenland

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#7820]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Mobile phone numbers as used in Greenland are not supported by the registration process.

### Steps to reproduce
- Try to register Signal in Greenland

**Actual result:** You do not receive the registration message.
**Expected result:** You receive the registration message, and are able to start using Signal.

### Device info
**Signal version:** 4.19.3

Probably a fix [similar to this](https://github.com/signalapp/Signal-Server/commit/c2d8c9a66203f25b421b716b0b59cdd0b755444e) is needed that will add support for:
Greenland with country code: +299
where subscriber number consist of 6 digits

For more details about phone numbers in Greenland see [this document](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000560002PDFE.pdf).

See also [this thread](https://community.signalusers.org/t/does-signal-work-in-greenland/2967) on the Signal support forum.

**Comment by tuxayo** [comment]
@janvlug Any more details? (see previous comment)

**Comment by janvlug** [comment]
@tuxayo, unfortunately, no. I asked the original reporter on Twitter, but did not get an answer. I just asked again: https://twitter.com/janvlug/status/1005887293478113280.

**Comment by janvlug** [comment]
According to the reporter: "Everything works, they just don’t get the SMS."
See: https://twitter.com/FrejaWedenborg/status/1005929900811997185.

**Comment by moxie0** [comment]
I see, nothing we can do in the app then. Sounds like our SMS provider just isn't delivering to Greenland, typically the voice call will work if that's the case.
