### ISSUE TITLE
Full-text search does not find emojis

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#7822]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot find emojis with search

### Steps to reproduce
- Send someone a message which has a 🍐
- Try to search for messages which has a 🍐

**Actual result:** _No results found for '🍐'_
**Expected result:** Message should be found

### Screenshots
![screenshot_2018-05-22-14-15-05](https://user-images.githubusercontent.com/174176/40359933-0b5cbf14-5dcd-11e8-8dc8-d8c06a69f478.png)
![screenshot_2018-05-22-14-15-24](https://user-images.githubusercontent.com/174176/40359935-0e0f3b24-5dcd-11e8-9abe-80a22f9f52b4.png)

### Device info

**Device:** bq Aquaris E4.5
**Android version:** 5.0
**Signal version:** 4.20.1

### Link to debug log
https://debuglogs.org/f7dcf5b2388f4788d51e409ed32a4f1c71e4b92be10aa5e9a3c399b6a1b58c8d

**Comment by FWCologne** [comment]
On my phone, it works at least for 🙄, but not for the other emojis I tried

**Comment by believeInJha** [comment]
Hi, I'm new to opensource. Can I start working on this issues?

**Comment by believeInJha** [comment]
All kind of old human emoji-like  🙂 &👍 are searchable, others don't work. This problem is even there in WhatsApp, so I guess the problem is with the Android framework. Can I start working on this issue?

**Comment by charlag** [comment]
For any future archeologists: it was fixes here:
https://github.com/signalapp/Signal-Android/commit/2c11a27897d8aafa2659b9723b366c82fe953030
I was surprised because it seems like on Android you can search for emoji but CJK is not correctly tokenized and vice versa on desktop
