### ISSUE TITLE
Mute functionality does not persist when switching screens

### ISSUE THREAD

**Issue by MAkcanca** [signalapp/Signal-Android#7827]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------
Possible duplicate of : https://github.com/signalapp/Signal-Android/issues/6859
### Bug description
Whenever I mute on speaker mode, switch to something else and get back to signal, mute button looks unselected. Not sure if audio still gets muted but that's problematic.

### Steps to reproduce
- Start a call
- Put it on speaker mode (not sure if it affects the other way too)
- Mute the call
- Put the app in background
- Get back to the call
- Check the mute button status

**Actual result:** Unselected mute button
**Expected result:** Mute button should be still active status. I wasn't able to test the audio functionality so It would be nice if somebody else can.

**Comment by jeremymasters** [comment]
I think there are some issues with all the buttons and retaining their state through transitions.  Speakerphone has some odd state retention or lack thereof as well through different sorts of transitions.

**Comment by mueller-ma** [comment]
Possible duplicates: #8221 and #8420
