### ISSUE TITLE
Notification volume goes to max on Android 8 (Oreo)

### ISSUE THREAD

**Issue by arjenlentz** [signalapp/Signal-Android#7832]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgrading phones to Android 8 (Oreo), the notification volume ends up on maximum.  This is because Notification Volume (and related settings) are now under application control, and no longer has an Android global volume setting for this (IMHO a dreadful design decision), but rather a "Notification Channels" feature which needs to be supported by the application.
See https://ting.com/blog/notification-channels-android-oreo/ for what things might look like if Signal supported this.

### Steps to reproduce
- install Signal on Android 8.x
- receive SMS
- note that volume cannot be changed from maximum.

### Device info

**Device:** Nokia 5, Nokia 6
**Android version:** 8.1 (Oreo)
**Signal version:** 4.19.3

**Comment by greyson-signal** [comment]
We're using notification channels now. But in general, you just want to make sure that you're changing your ringer volume and not your media volume.
