### ISSUE TITLE
Position sharing without Gservices

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#7835]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a phone that doesn't have Google Services, I can't share my location. When I press the "Position" button the flap goes down without an error message.

### Steps to reproduce
- Open any conversation
- Try to share your position
- You can't !

**Actual result:** The application does not generate a message
**Expected result:** The application should generate a message with a Google Maps showing my location.

### Screenshots
No screenshots because no error message appears.

### Device info
**Device:** Xiaomi Mi Note 2
**Android version:** 8.1.0
**Signal version:** 4.20.4

### Link to debug log
https://cloud.hugoleroux.ovh/index.php/s/jrRYNrzFRjBmgD9

**Comment by sigenc** [comment]
This will be tagged with help wanted. So the people who believe in free Software can contribute

**Comment by erik55** [comment]
Yes, please make it to use Osmand or Mapsme. Or just generally only use the coordinates. Or why not OpenStreetMap.org?

**Comment by harishvishwakarma** [comment]
@sigenc Why is this not closed?

**Comment by onny** [comment]
@harishvishwakarma it's not yet fixed or implemented

**Comment by trmendes** [comment]
I came here to report that same issue. The issue exists since 2018 :O.

Still! I have the same issue. I can select a location, it appears on the message box, but the send button is not enabled (only a + button). When I type a message the send button appears (while the location is still there) but when I tap the send button only the message is sent. Not the location.

**Comment by machiav3lli** [comment]
Just wanted to report that this issue still exists. It'll be helpful if some pointers to where the issue may lay get provided, so the community can contribute to its solution.

**Comment by fwicht** [comment]
Yes, as far as I'm concerned, it's still relevant! The issue hasn't been fixed. I'd be happy to help if I'm pointed to where the issue lies.

**Comment by te2dy** [comment]
Yes it is!

On /e/OS, I can choose a location; then, here is what is displayed – no map nor send button:

![Screenshot](https://i.ibb.co/pLT3HVT/signal-2022-02-02-190133-001.png)

**Comment by SkypLabs** [comment]
I would really like to see this feature being implemented, and I think many people think the same.

**Comment by machiav3lli** [comment]
I do second that, that's an essential issue that's being ignored now for almost four years. Is there any suggestion how we could push for a fix or a start point to work on?

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by fwicht** [comment]
It's not a feature, it's a bug. Please consider reopening this issue.

**Comment by Socob** [comment]
Yeah, I don’t see how a report about an existing feature being broken is a feature request.

**Comment by cody-signal** [comment]
Hey there, appreciate the concern, but this isn't likely something we'll focus on. However, if someone wants to make a PR, please and do tag me on it and I'll review it and pull it in if it's valid.
