### ISSUE TITLE
Highlighting and copying individual text, rather than entire message copy?

### ISSUE THREAD

**Issue by MajorWoooolf** [signalapp/Signal-Android#7840]
There seems no function to highlight and copy individual text within a message? only copy entire message? (and then delete all inappropriate text,,, which is a laborious way to go about things.. )
I have been using Signal from the beginning (was it called Text Secure? cant remember!) and love the way the app has developed, it really is a professional and fully functioning oem message app replacement, and gets the thumbs up from everyone i recommend it too.
Good Job Devs, just don't understand why you still cannot highlight individual text ..

**Comment by 2-4601** [comment]
Thanks for the suggestion, feature requests are handled in the forum. Could you please open a topic at https://community.signalusers.org/c/feature-requests/android-feature-requests (you can sign up/login with your GitHub account).
