### ISSUE TITLE
Disable calls for < KK

### ISSUE THREAD

**Issue by righy** [signalapp/Signal-Android#7841]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive an audio call, Signal restarts right after picking it up. It looks like I can hear the other end for about half a second before it stops. I am then brought to the Signal "enter passphrase" prompt screen.

### Steps to reproduce
- Open Signal
- Enter the passphrase to unlock Signal
- Wait until I receive an audio call
- Pick up the call

**Actual result:** Signal restarts and I am unable to talk with the correspondent.
**Expected result:** I can talk with the correspondent.

### Device info

**Device:** HTC Desire (codename bravo)
**Android version:** 4.0.4 (eng.k900.20120624.010557, IMM76I)
**Signal version:** 4.19.3

### Link to debug log
Output of adb logcat (anonymized) just after Signal restarted:
https://gist.github.com/righy/97566347ad1e4c75ed78e9d70b942c8c

**Comment by moxie0** [comment]
Looks like webrtc's minsdk is greater than your version of Android. We should disable calling for < KitKat to prevent it from crashing.

**Comment by haffenloher** [comment]
Calls still work fine on Android 4.2. Looks like the missing AcousticEchoCanceler class got added with 4.1 / Jelly Bean: https://developer.android.com/reference/android/media/audiofx/AcousticEchoCanceler

**Comment by alan-signal** [comment]
We're now >= KK.
