### ISSUE TITLE
GIF search display setting not remembered

### ISSUE THREAD

**Issue by S74HK9hV** [signalapp/Signal-Android#7843]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

Bug previously reported here, but got closed by an automated clean up: https://github.com/signalapp/Signal-Android/issues/6815

### Bug description
List/Grid view setting in the GIF search is not persistent. It keeps reverting back to the default view (large preview tiles that span the entire screen width). When view is switch to Grid view (smaller preview tiles) this setting does not remain the next time GIF search is openened

### Steps to reproduce
- open GIF search
- switch the view using the setting button on the top right corner
- exit GIF search
- return to GIF search. The view setting is not remembered by the app

**Actual result:** GIF tiles view returns to default
**Expected result:** Should remember last setting

### Device info

**Device:** SONY Xperia X Compact
**Android version:** 8.0.0
**Signal version:** 4.19.3

**Comment by ianmcderp** [comment]
> Expected result: Should remember last setting

Would this require its own `Database` or are Android's [Shared Preferences](https://developer.android.com/training/data-storage/shared-preferences) sufficient as well?

**Comment by ianmcderp** [comment]
Why did this PR get closed?
