### ISSUE TITLE
Typing in Signal is very slow and Messges arrives some hours later sometimes

### ISSUE THREAD

**Issue by Rockee79** [signalapp/Signal-Android#7847]
* [ ] I have searched open and closed issues for duplicates
  

---

### Bug description
at the Moment i have the Beta V4.20.4 installed
- on my Android Huawei Mate 10pro typing is very slow and laggy; i have this problem since the new beta is installed (Beta V4.20.4) no prob. before! (i made a restart and nothing changes)
- Sometimes Messages have a big delay and arrives hours later (on various Smartphones Android and iPhones; with and without Signal installed. This problem exists a long time with various Versions of Signal.

Feature Request: 
A new way of encrypted Backup and syncroniseable methode. It would be very nice to have all messages on all PCs (2 Laptops, 1 PC) and the smartphone.
make it possible that we can import all messages from Signal on the Android to the PC Version.
I dont want to loose some messages, if i have to maka a clean install on my Laptop/PC. 
It 

### Steps to reproduce

1.  step one
2.  step two
3.  step three

Actual result:

Expected result:

Fast typing.
### Screenshots
there are no screenshots 

### Platform info

Signal version:
Beta V4.20.4

Operating System:
HUAWEI EMUI 8.0.0

Linked device version:
BLA-L29 8.0.0.137(C432)

### Link to debug log
https://debuglogs.org/cc4f7e010375b9bc0072b8bd3773836fafdca38710d689b25478f169959e46a2

**Comment by Vallant** [comment]
Might be the same as #7839

**Comment by 2-4601** [comment]
>- on my Android Huawei Mate 10pro typing is very slow and laggy; i have this problem since the new beta is installed (Beta V4.20.4) no prob. before! (i made a restart and nothing changes)

This sounds like #7839

>- Sometimes Messages have a big delay and arrives hours later (on various Smartphones Android and iPhones; with and without Signal installed. This problem exists a long time with various Versions of Signal.

Please check [this support article](https://support.signal.org/hc/en-us/articles/115005547088-Why-do-I-only-see-new-messages-when-I-open-Signal-Android-). Huawei phones are known for their aggressive power saving mode.

>Feature Request: 
>A new way of encrypted Backup and syncroniseable methode. It would be very nice to have all messages on all PCs (2 Laptops, 1 PC) and the smartphone. make it possible that we can import all messages from Signal on the Android to the PC Version. I dont want to loose some messages, if i have to maka a clean install on my Laptop/PC. 

Feature requests are handled in the forum. For backups there's a thread here https://community.signalusers.org/t/lets-talk-about-backups/2237/
