### ISSUE TITLE
Feature Request: Add Wikipedia link to invitation SMS

### ISSUE THREAD

**Issue by renne** [signalapp/Signal-Android#7848]
When I send Signal invitation SMSes a lot of people ask what Signal is and why they should install it. To simplify this and increase the roll out speed of Signal I suggest to add a link to the Wikipedia article of Signal to the invitations SMS.

**Comment by Cerberus0** [comment]
Hi @renne!

I'm another Signal user like you and I appreciate your suggestion. However, this project handles feature requests in the forum. Please open a new topic at https://community.signalusers.org/c/feature-requests/android-feature-requests (you can sign up/login with your GitHub account).

As mentioned in the project's [contributing guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues), the purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. If you decide to stick around and report bugs, please read and fill out [the bug report template](https://raw.githubusercontent.com/signalapp/Signal-Android/a8cf5b8efa924b480de4271e4ba07e564aea7ca1/.github/ISSUE_TEMPLATE.md) when you submit new issues.

Cheers!
