### ISSUE TITLE
'Quoted message not found' for messages quoted from beyond See full conversation

### ISSUE THREAD

**Issue by houghtrans** [signalapp/Signal-Android#7850]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When old messages (which can be accessed only after scrolling all the way up and then clicking 'See Full Conversation') is quoted, then that quoted message when clicked, doesn't scrolls up to that particular message. Instead it returns 'Quoted message not found'

### Steps to reproduce
-Scroll all the way up beyond 'See Full Conversation' and select a message to quote
-Quote the message 
-Click this newly quoted message

**Actual result:** Clicking this quoted message returns 'Quoted message not found'.

**Expected result:** Clicking this quoted message should take you to that particular message.

Note:- Quote Message works perfectly fine for messages that are recent. It doesn't work only for messages that are present beyond 'See Full Conversation' option.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by Edu4rdSHL** [comment]
Able to reproduce here too, debug log https://debuglogs.org/22c62fa2ecb4e17aa9d75b0a97caee30a19759488d9d228195bb5b1bcaa8081c
