### ISSUE TITLE
@get better

### ISSUE THREAD

**Issue by Capta0081** [signalapp/Signal-Android#7853]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Capta0081** [comment]
Search, search, search

Before submitting a new issue please search if someone has already opened
an issue about the same topic. Don't forget to search for both open and
closed issues as GitHub only searches for open issues by default. (You may
also wish to check out GitHub's help article about search
<https://help.github.com/articles/searching-issues/> to get more accurate
results.)
<https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#come-up-with-a-concise-and-descriptive-title>Come
up with a concise and descriptive title

A good title sums the issue in a few words and makes it easily searchable.
There's no need to use tags such as *"[Feature]"* in the titles. Speaking
of search: did you try searching duplicate issues by using your title as
search keywords?
<https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#try-to-reproduce-the-bug>Try
to reproduce the bug

To fix an issue the developers need to see the bug themselves. Try to find
the exact conditions and steps that make the bug happen and then write them
down on your issue report. Following your steps the developers can
hopefully recreate the bug on their own device and fix it.
<https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log>Capture
a debug log

Debug log is like a history which tells what Signal was doing while it was
running. If you capture a debug log immediately after the bug has happened
the developers can use the log to see exactly what was going on in your
installation of Signal. Even in the case where you know the exact steps
that cause the bug it doesn't guarantee that the same steps cause the bug
on the developer's device. Thus it is always helpful to add a debug log to
your issue report.
<https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#how-to-capture-debug-log>How
to capture debug log

   1.

**Comment by 2-4601** [comment]
You've pasted the guide on how to report bugs here but did you read it?
