### ISSUE TITLE
Signal Crash even after uninstall

### ISSUE THREAD

**Issue by mr-lanholmes** [signalapp/Signal-Android#7856]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi all, after uninstall the Signal application, I still get the crash issue on daily basis. Please kindly advise.

Thanks

![screenshot_20180603-115454](https://user-images.githubusercontent.com/2654430/40883847-201f2412-6739-11e8-9291-63a24a976e7c.jpg)

### Steps to reproduce
- Uninstall the app
- Get a SMS while using your phone

### Device info

**Device:** Android Note 5
**Android version:** 7.0

**Comment by Trolldemorted** [comment]
What exactly is crashing?

**Comment by mr-lanholmes** [comment]
Hi @Trolldemorted I will take a screenshot if I encounter again, as normal app crash message "Unfortunately, Signal has stopped". Very strange since I already uninstalled the app.

**Comment by Trolldemorted** [comment]
Well if it crashes it obviously is not really uninstalled, but that sounds like a severe android bug. Are you using a third party rom?

**Comment by jeremymasters** [comment]
Did you just remove the shortcut?

**Comment by mr-lanholmes** [comment]
Nope i did clean uninstall from the menu

**Comment by mr-lanholmes** [comment]
Hi all. I managed to recreate the bug, it is when i receive an SMS when using my phone.

**Comment by 2-4601** [comment]
Try to see what is the default application for SMS in your phone's settings and set it to the Samsung default text app.
https://www.verizonwireless.com/support/knowledge-base-176021/
https://i2.wp.com/www.gottabemobile.com/wp-content/uploads/2015/08/Note-5-text.jpg

**Comment by mr-lanholmes** [comment]
Thanks @2-4601 . Seems like I found the issue, the app was uninstalled for normal Samsung UI, but was not removed from Samsung Knox (it still has permission to read SMS). Its solved now! Thanks!
