### ISSUE TITLE
Error when manually updating the Playstore version to a compiled apk from master branch

### ISSUE THREAD

**Issue by patrikhuber** [signalapp/Signal-Android#7861]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Hi!

Apologies that this is not strictly an "issue" - but it is also neither a feature request or suggestion that would fit in the community forums, nor a support request for the app for which I would go to https://support.signal.org.
I do think this will be interesting for other developers too:

I'm blocked by #7831, I need to backup my chats, but can't wait for the next official Signal release (which will be who-knows when).

So I successfully built the latest master branch from source and signed the created `*-website-*` and ``*-play-*`` apk's. When installing that apk on the phone, it asks "Do you want to install an update to this existing application? Your existing data will not be lost.". However it doesn't finish installing, there's an error after a couple of seconds, "The package conflicts with an existing package by the same name.".
This happens with both the play and website apks (both signed), as well as the debug apks.
I've also tried renaming `<string name="app_name">` in `strings.xml` but that didn't help either.

I suppose this might happen because I originally installed Signal from the Playstore?
Is there any way to go from the currently installed Playstore version to a version built from the latest master branch, so that I can backup my chats?
I'm afraid to uninstall the Signal version installed from the Playstore, because I am afraid that it will remove all the chats with it.

**Comment by greyson-signal** [comment]
Unfortunately you'll never be able to upgrade from a release build to a debug build (or vice-versa) because both of these builds have the same package name, but different signing keys.

As you suspected, uninstalling the app without backing up your chats will delete your chats. So don't do that just yet :)

If you want the most recent version of Signal, I'd recommend opting into the beta program, which can be done through Signal's Play Store page (the option is near the bottom of the page, I believe). Of course the beta is slightly less stable, so keep that in mind.

**Comment by patrikhuber** [comment]
@greyson-signal Thank you very much for the reply! :-)
I'm not mixing release and debug builds though. I've used the self-built release apk's, and signed them as well.

But I guess what you are saying is that even that doesn't work - upgrading only works if the signing key were the same?

Thank you for confirming that uninstalling would delete the chats! :-)

I'm already in the beta program. But I need a fix from master to be able to backup my messages (see the link I've posted). Basically the export is broken, so I (and probably loads of other people) can't uninstall, or reinstall my phone, until Signal pushes an update to the Playstore beta channel :-(

**Comment by Trolldemorted** [comment]
@patrikhuber if your phone is rooted and you don't mind messing with android, there should be ways [around that problem](https://www.xda-developers.com/application-signature-verification-how-it-works-how-to-disable-it-with-xposed-and-why-you-shouldnt/).
