### ISSUE TITLE
Per user disappearing messages proposal

### ISSUE THREAD

**Issue by codebam** [signalapp/Signal-Android#7864]
An issue I've come across is that anyone in a chat can change the disappearing message timeout.

This becomes an issue in group chats because if two people disagree on disappearing messages but the other does not one party has to compromise.

My proposal is to let users choose the disappearing message timeout for their own messages, and not let other users change this value. This respects each user because they can choose the value for the messages they send, and no one can force them to give up privacy.

**Comment by jlund-signal** [comment]
Hi, @codebam. As outlined in the [contributing guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) (and the issue template that was deleted) this tracker is only used for bugs in existing functionality that is not working as expected. There's a [Feature Requests category](https://community.signalusers.org/c/feature-requests) on the community forum that is designed for this type of valuable user feedback. Thanks!

**Comment by codebam** [comment]
Sorry about that, I posted in the appropriate section in the community forum. Thanks!
