### ISSUE TITLE
MMS image messages from different numbers (sometimes) placed in wrong conversation thread

### ISSUE THREAD

**Issue by jsoberg** [signalapp/Signal-Android#7870]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On two separate occasions and from two separate numbers, I have received an MMS message of a single image (with me being the only intended recipient of the message), and instead of being placed in the expected conversation thread between me and the sender, it is placed in another conversation thread entitled '1'. I have no explanation as to why this might have happened, as other MMS image messages received from the same numbers at other times were placed into the correct conversation threads.

### Steps to reproduce
Unfortunately, this issue is not reliably reproducible to my knowledge. The issue was observed when receiving MMS messages (images) from two separate numbers; however, other MMS messages from the same numbers at other times were placed in the correct conversation thread.

### Screenshots
![signalwrongconvthreadmms_05-31-2018](https://user-images.githubusercontent.com/1057406/40813947-738c7ca6-650b-11e8-942c-cb8fb3a6abec.png)

### Device info
**Device:** Huawei Nexus 6P
**Android version:** 8.1.0
**Signal version:** 4.19.3, installed from Google Play

### Link to debug log
The following log shows opening Signal and then opening the '1' conversation thread.
https://debuglogs.org/a12112e255e77c670f1ba655e31089a86c675fa39a30aff004ffbdcf4f62b16b

**Comment by Gabrahammer** [comment]
Look forward to St Louis
Lpp

**Comment by Trav1sty** [comment]
I'm seeing the same issue as well. So far I've been able to reproduce it when someone on T-Mobile sends a photo to me. I also am on T-Mobile.


Device: LG V30
Android 8.0.0
Signal Version: 4.30.1 (Beta from Play Store)

**Comment by jeremymasters** [comment]
@Trav1sty can you attach a debug log?  The "me too" is only helpful if the log comes with it.

**Comment by Trav1sty** [comment]
Here's the link to the debug log. https://debuglogs.org/4924a001fc50f5ed02e172b004bd0b1b10794e2479754e1188e6bedc6e6db166

**Comment by jsoberg** [comment]
I stopped using Signal years ago because of this persistent issue, so I can't report on whether it still exists or not. I'd like to know if anyone is experiencing the issue, or was experiencing the same issue and has since seen it be resolved

**Comment by UserX404** [comment]
@jsoberg
Sometimes i also have to use mms due to missing signal availability of some recipients.
I don't had this issue in the past.
For me this happens only if a dual sim user forget to switch his 'used' sim profile.
