### ISSUE TITLE
Timeframe server deactivates inactive accounts

### ISSUE THREAD

**Issue by Kamkata** [signalapp/Signal-Android#7874]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Right now the server logs 2 things. Registration day/month/year and last login day/month/year. This is used to determine unactive accounts and deactivate them if they are not used longer than a year.

### Steps to reproduce
- create account 
- run into Problems with law enforcement
- wait till ows get's an subpoena 

**Actual result:** OWS will share DAY / Month / Year
**Expected result:** Use only the Year for determining active accounts. **_current_year - last_login_year > 1_**
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Kamkata** [comment]
I really don't understand the thumbs down. This is metadata than can be reduced without having any Impact on the infrastructure. The accounts aren't deleted at the moment. They just get deactivated. We can use greater than 1 year for deactivation. No need for day and month. I consider this as a bug when i can only have one thing logged instead of three.

I'm suprised you haffenloher downvoted this.

**Comment by johanw666** [comment]
Why would the expected result be only the year? Not that I disagree that this would be a better solution, the less metadata the better and lew enforcement might draw conclusions from the date ("He started using Signal just after he insulted the supreme leader, he must be preparing a revolution!").

**Comment by 2-4601** [comment]
I think @johanw666 is right, a more suitable place to discuss this would be in the community forum.
