### ISSUE TITLE
Inconsistent rendering of Jumbomojis if system emojis are enabled

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#7875]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When system emojis are selected, emoji-only messages don't alwas show jumbomojis.

### Steps to reproduce
- Set preference to "Use system emoji"
- Send (or receive) a message containing only emojis

**Actual result:** Sometimes, e.g. during sending (see first screenshot), the emoji is correctly shown as jumbomoji. Directly afterwards, it is shown as normal (small) emoji (second screenshot). Closing the conversation and opening again sometimes fixes it, sometimes it doesn't.
If I don't use system emoji, the jumbomojis are shown correctly.

**Expected result:** The emoji-only message should always show a jumbomoji.

Since this bug only occurs for system emojis and I think I had some Google updates recently, maybe this bug is not produced by Signal (but I don't have another app that uses system jumbomojis). 
In this case, feel free to close this issue.

### Screenshots
Jumbomoji during send (flight mode was only enabled to have sufficient time for a screenshot):
![screenshot_20180604-220714_resize](https://user-images.githubusercontent.com/23025712/40985923-599e4ea4-68e5-11e8-8e2f-ebf689c6d63e.png)

Regular emoji after send:
![screenshot_20180604-220731_resize](https://user-images.githubusercontent.com/23025712/40985975-7323d56a-68e5-11e8-8e21-6b571991d693.png)

Opening the conversation later on (inconsistent size):
![screenshot_20180605-173106_resized](https://user-images.githubusercontent.com/23025712/40986621-f7e1c73e-68e6-11e8-8d19-77f1c5bb0828.png)

Correct display for integrated emojis:
![screenshot_20180605-173400_resized](https://user-images.githubusercontent.com/23025712/40986630-fe8eded2-68e6-11e8-9c62-136f3102f0bb.png)

### Device info

**Device:** Motorola Moto G5
**Android version:** 7.0
**Signal version:** 4.20.5

### Link to debug log
If necessary, I will upload a debug log

**Comment by 2-4601** [comment]
Can be easily reproduced by selecting a message. This will make the system emojis on the screen turn small.

**Comment by member-1** [comment]
This was caused by ceafb0d130910a9742ba510defa1afe2be095f8c. I've already fixed it in my [fork](https://github.com/member-1/Signal-Android/commits/).
