### ISSUE TITLE
Signal message option not removable when contacts delete app

### ISSUE THREAD

**Issue by Gibil** [signalapp/Signal-Android#7878]
- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a contact removes Signal, the option to send signal messages instead of SMS is always default and cannot be removed. Messages sent reach server and hang indefinitely with no recourse.

### Steps to reproduce
- add signal contact
- have the contact delete Signal app
- send further messages

**Actual result:** Any new messages will be signal messages and require long press option to change to SMS indefinitely

**Expected result:** I would expect that Signal unregister a contact during the uninstall process, since it is only tied to phone number.

### Device info

**Device:** Nexus 6p
**Android version:** 8.0
**Signal version:** 4.20.5

**Comment by nrizzio** [comment]
There is no way of detecting an uninstalled app from the server. There is an unregistration page that you can send to your contact: https://signal.org/signal/unregister

**Comment by 2-4601** [comment]
Yes, unfortunately the uninstall process in Android does not allow the app in question to do anything before it gets removed. Best you can do is what nrizzio said above.

Relevant threads in the forum:
https://community.signalusers.org/t/remove-inactive-users-from-the-server/122
https://community.signalusers.org/t/unregistering-users-server-side-after-a-timeout/1236
https://community.signalusers.org/t/remember-the-current-message-mode-sms-or-mms-for-each-contact/2382

**Comment by tnixeu** [comment]
I also came across this issue today. I was looking for an option to delete a number on Signal, because a friend stopped using signal. I didn't notice it just replied to the normal non Signal text message on Signal.

I think it should be possible to delete or blacklist a number for signal. Otherwise I probably have to stop using signal for text messages.

It also would be nice to be informed when I reply via signal to a normal text message or be warned that a message was not still not received after x amount of time.

**Comment by denics** [comment]
Hi 2-4601, I think it is premature to close this ticket. Here we have a real problem.
I think that a possible solution could be to have an option to "send normal SMS" in the contact options.
