### ISSUE TITLE
Restore fails on 4.20.6

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7880]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

This is a duplicte of https://github.com/signalapp/Signal-Android/issues/7446 but since that issue is closed I am opening it at request of @greyson-signal 

### Bug description
Signal gives an "invalif passphrase" error when restoring an full backup.

### Steps to reproduce
- Create full backup and store it somewhere.
- Wipe all Signal data
- Copy backup back to device (because I'm using an external sd card the wipe deletes the existing backup).
- Start Signal and import backup
- Get always an invalid passphrase error.

**Actual result:** Invalid passphrase error.
**Expected result:** Importing the backup and restore of the data

### Screenshots
See https://github.com/signalapp/Signal-Android/issues/7446 , they are the same.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.20.6

### Link to debug log
```
06-08 01:06:02.718 W/RegistrationActivity(21262): java.io.IOException: Bad MAC
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:284)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:216)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:73)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:372)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-08 01:06:02.718 W/RegistrationActivity(21262): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by greyson-signal** [comment]
Hi @johanw666, in the ticket you linked to, part of the problem may have been the use of TB and other unsupported backup utilities. With this issue, is everything you're using stock?

**Comment by johanw666** [comment]
It does have nothing to do with TB, restoring the "official" backup is the problem. I'm using Sony stock ROM, no Lineage or another custom ROM.

**Comment by haffenloher** [comment]
Isn't this identical to #7637?

**Comment by greyson-signal** [comment]
@haffenloher Thanks, this does appear to be a dupe. The original issue also has more of a history, so I'll close this on in favor of #7637.

**Comment by holmboe** [comment]
@greyson-signal the OP is using a stock ROM, no mention of Xposed as was the identified issue in #7637 that this ticket was marked a dupe. I am running a stock Oneplus 6T and I am unable to restore as well. There seems to be a secondary bug here that is yet to be solved.

**Comment by haffenloher** [comment]
@holmboe As it turned out in #7637, the OP was indeed using Xposed. If you aren't, you're experiencing a different problem. Please open a new issue and provide a debug log.
