### ISSUE TITLE
Export Function Missing from Options

### ISSUE THREAD

**Issue by markizano** [signalapp/Signal-Android#7882]
### Bug description
I am unable to export text messages to plaintext backup as in version 4.16 and lower.

### Steps to reproduce
- Goto app home page.
- Select the three dots drop-down Settings button.
- Note the missing "Export" from the "Import" options.

**Actual result:** Export function is missing entirely.
**Expected result:** When selecting "Import / Export", I should be presented with options to export to a plaintext backup.

### Screenshots
<img src="https://user-images.githubusercontent.com/360451/41171094-e9980942-6b14-11e8-80c1-d8a42c776b5c.png" width="300" alt="screenshot_2018-05-08-16-36-30-1" />

### Device info

**Device:** LG G2 / LG G4 (VS986) / Moto Z
**Android version:** 6.0 / 7.1.1
**Signal version:** 4.19.3

**Comment by 2-4601** [comment]
That feature has been removed. #7597 is a duplicate issue.
