### ISSUE TITLE
Signal crashes entire phone when making phone call

### ISSUE THREAD

**Issue by bgcarlisle** [signalapp/Signal-Android#7885]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes entire phone when making video call

### Steps to reproduce
- make a video call

**Actual result:** Entire phone crashes and restarts
**Expected result:** A video call
### Screenshots
n/a

### Device info

**Device:** Samsung S7
**Android version:** 7.1.2; LineageOS 14.1
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/350e4752617620e7119d2e673afaf8a5923974db0d93c914e2f570054fb82446

**Comment by moxie0** [comment]
Unfortunately there's nothing in this debug log to indicate a problem, but if the entire phone is crashing then it's unlikely that anything would be logged. There's obviously nothing any app should be able to do to crash the phone, even if it tried, so it's unlikely that this is an issue we can address within Signal. Looks like you're running LineageOS, so it's likely this is a custom ROM thing. I'd recommend reporting this to them. Please reopen if you identify any action we can take, thanks!
