### ISSUE TITLE
Don't convert audio files automatically to mp3

### ISSUE THREAD

**Issue by DreamFlasher** [signalapp/Signal-Android#7889]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio attachments on Android are automatically converted to mp3 and thus not playable on the iOS app.

### Steps to reproduce
- send a m4a audio file via "send audio", for example: http://techslides.com/demos/samples/sample.m4a

**Actual result:** The file is playable in the Android app, but not in the iOS app.
**Expected result:** It should also play on iOS.

### Device info

**Device:** Blackberry Priv
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by michaelkirk-signal** [comment]
Signal-iOS shouldn't have any problems playing well formed mp3 audio. 

Do you have an example file you could provide which exhibits this behavior?

**Comment by DreamFlasher** [comment]
I agree that it shouldn't have these issues. Moreover I think it shouldn't be converted, because m4a is a well suitable format. Please have a look at the "steps to reproduce" section for an example file.

**Comment by greyson-signal** [comment]
I wonder if this is related to our more general audio playback issues, like in #7748?

**Comment by DreamFlasher** [comment]
The issue is on iOS though -- the playback works nicely on Android and Desktop. So I guess I should have created a ticket in the iOS github, but I thought the issue is the converting which should not happen imho. Cause iOS can playback m4a right?

**Comment by michaelkirk-signal** [comment]
@DreamFlasher - no need to create a separate issue for now. We're tracking it down.

**Comment by moxie0** [comment]
Closing this as an iOS issue

**Comment by DreamFlasher** [comment]
@moxie0 Could you please comment about the automatic conversion? I think if I send an mp4 file I should have the chance to send it without conversion. If I encoded the mp4 exactly as I want, the conversion to mp3 can only make it worse, so I think this should not automatically happen.

**Comment by michaelkirk-signal** [comment]
I believe what’s happening is that it is indeed being sent as an m4a, but Signal iOS is confusing the mime type (audio/mpeg) as mp3. Feel free to file an issue on the iOS tracker if you’d like to be updated when we fix this. (Link back to this issue if you do)
