### ISSUE TITLE
Full text search results - weird view layout behavior after rotating phone

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7890]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------
First of. Sorry if the title is not as clear as it could be! I honestly did not know how to describe it better. Feel free to change. 

### Bug description
The layout of the grey tiles in the view is kinda messed up. See screenshots. 

### Steps to reproduce
- Search for something in portrait mode. 
- open that conversation
- rotate phone to landscape mode
- go back to search results

It just happens from time to time. Not everytime. Don't know yet why exactly. Hopefully the log will help. Otherwise I'll try and dig a bit deeper. 

**Actual result:** see 1st screenshot
**Expected result:** see 2nd screenshot

### Screenshots

![signal-attachment-2018-06-11-140828](https://user-images.githubusercontent.com/18451020/41250236-dc0382a0-6da5-11e8-9661-eb2c9bdfaee3.png)

![signal-attachment-2018-06-11-144012](https://user-images.githubusercontent.com/18451020/41250249-e512aa92-6da5-11e8-8b10-4fe1e8a0dbf4.png)

### Device info

**Device:** Samsung Galaxy S5 klte
**Android version:** 7.1.2 (lineage-14.1-20180608-nightly-klte)
**Signal version:** 4.20.6

### Link to debug log

https://debuglogs.org/bfa4b8df382eaeea56be119eaa5bcd4e6b3155272ff32b0cb0d395fce0249e4e

**Comment by halb9** [comment]
With 4.20.8 the grey tiles seem to be fixed. Thanks for that. 
But the X in the search bar is still in the middle. Is this intentional? Shouldn't it be on the right?

**Comment by greyson-signal** [comment]
@halb9 The x should be on the right IMO, but I believe that it's always been that way, even before the new full-text search changes. I'll get to it though :)

**Comment by halb9** [comment]
JUST FYI. The X is still in the middle. Doesn't really hurt. But I thought you might want to know.
