### ISSUE TITLE
Blank confirmation dialog pops up when sending SMS to short codes 

### ISSUE THREAD

**Issue by akwala** [signalapp/Signal-Android#7891]
Scenario: Automated SMS messages from pharmacies, doctors' offices, etc. that come from short codes ask for a reply, e.g., YES/NO.

When sending the reply, a blank dialog pops up with the options CANCEL and SEND. Tapping the respective options has the expected effect but the purpose of the dialog is unknown since nothing besides two icons, coins and checkbox, is visible above the options. The dialog looks the same in the light and dark themes. 

Moto G5 Plus;
Android 8

Debug log: https://debuglogs.org/2e2ecff3e048223ca035afb0399e3b7087a4c58f2078d2a244916ddf544c7f07
 
![screenshot_signal_20180611-142026](https://user-images.githubusercontent.com/1786/41251920-817acc56-6d89-11e8-843f-7e2eb78cf122.png)

**Comment by 2-4601** [comment]
That's the system dialog which informs that sending that SMS will cost you money.
Can you confirm with another SMS app whether the dialog is blank there or not?

**Comment by akwala** [comment]
Yes, the same, blank dialog pops up when I try to send an SMS message to a short code from Android Messages by Google.

Since this is a system dialog, it's not an issue in Signal's Android app. I am going to close this.
