### ISSUE TITLE
Message Size setting not being respected

### ISSUE THREAD

**Issue by kristophercrawford** [signalapp/Signal-Android#7897]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Signal version 4.19.3 for Android 8.0.0 on my Motorolla Z2 Force, when setting the message font size, no change is reflected inside of Signal Messages or unsecure SMS messages.
### Steps to reproduce
- Change chat message font size from normal to small or large
- Note no actual change to the font size in chats
- Stop/start app and reboot of phone yielded no change

**Actual result:** The font size remains normal size. 

**Expected result:** The font size should reflect the user setting.

### Device info

**Device**: Motorolla Z2 Force

**OS version**: Android 8.0.0

**Signal version:** 4.19.3

**Comment by greyson-signal** [comment]
Hmm, I'm unable to repro this in 4.24.x. It's currently in beta. If you're in the beta, can you confirm if this has been fixed? Otherwise, I'm going to revisit this after 4.24.x goes to production.

**Comment by kristophercrawford** [comment]
The issue also went away for me with no changes.  This issue can be resolved.
