### ISSUE TITLE
Double man facepalm emoji

### ISSUE THREAD

**Issue by maxxer** [signalapp/Signal-Android#7899]
### Screenshots

![screenshot_2018-06-14-18-35-27](https://user-images.githubusercontent.com/240201/41452057-4b64a300-7070-11e8-8f65-e8bd7d0e28a3.png)

### Device info
**Device:** LG G6
**Android version:** 8.0.0
**Signal version:** 4.20.8

**Comment by volv0x** [comment]
#7749 this bug report is a duplicate.

**Comment by maxxer** [comment]
shame on me and my poor searches 🤦‍♂️
