### ISSUE TITLE
Full-text-search does not seem to find words in some cases

### ISSUE THREAD

**Issue by uspoma** [signalapp/Signal-Android#7900]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not sure if the search function is supposed to work like I expect it here. It seems that searching for parts of a word does not work. Is this the way it is supposed to be?

### Steps to reproduce
- send a message with one word: Heinestraße
- a) search for Heinestraße
- b) search for Heine
- c) search for straße

**Actual result:** a and b return the correct result, my message is shown. However c does not show my sent message as a search result.

**Expected result:** Variant c should return my sent message(s) as a search result.

### Device info
**Android version:** 7.1.2
**Signal version:** 4.20.8

Please tell me if debug messages or screen shots are needed but I guess you can reproduce that behavior quite easily.

**Comment by greyson-signal** [comment]
Unfortunately [sqlite full-text search](https://www.sqlite.org/fts5.html) only supports prefix queries, so it can't match substrings that start in the middle :( Maybe in the future!
