### ISSUE TITLE
Feature Request - Mutual Screenshot Blocking Setting option for users on both sides of chat.

### ISSUE THREAD

**Issue by Crowned-Eagle** [signalapp/Signal-Android#7902]
A feature request: 

As Signal set the same disspearing msg setting for both users, introduce similar setting for Screenshot Blocking Setting so that users can not take screenshot of conversation without consent of use on other side. 

OR atleast users would be aware of that users on other side haven't Disabled Screenshot taking. And this setting once enabled this blocking should remain enabled at least for time equal to greater than Dissapearing Message timeout, so that users can not quickly disable setting take screenshot and again enable it.

_Sent from my OnePlus5T using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by 2-4601** [comment]
Hi, feature requests are tracked in the [forums](https://community.signalusers.org/).

**Comment by Crowned-Eagle** [comment]
Okk..
