### ISSUE TITLE
Can't leave group chat the second time (but can type)

### ISSUE THREAD

**Issue by stites** [signalapp/Signal-Android#7903]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Basically the same thing as #723, but this time the keyboard pops up. I don't have enough participants to simulate the following steps, from the perspective of Person B, the next section shows what I would expect (mostly c/p'd from #723).

### Steps to reproduce

- Person A creates new group, invites persons B and C and sends message.
- B leaves group after sending a message and deletes group thread.
- A adds B again to group.
- B now gets new group messages, but can't leave again.

**Actual result:** Group chat drop-down has the options: Add attachment, All media, Conversation settings, Mute notifications.

**Expected result:** Group chat drop-down has the options (in order, take from another group): Edit Group, Leave group, Add attachment, All media, Conversation settings, Mute notifications. Clicking on "Leave group" allows me to stop receiving group messages.

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 8.1.0
**Signal version:**  4.19.3

I use Signal for the management of SMS (for other global state information)

### Link to debug log

There is no crash log to send.

**Comment by anastasia** [comment]
Please help, I'm stuck in a horrible limbo state where I'm forced to look at inane messages from people I don't know. 
**Device**: Google Pixel 2
**Android version**: 8.1.0
**Signal version**: 4.19.3 
**Signal desktop version**: 1.12.1

**Comment by stites** [comment]
I've also noticed that group creators can't remove members and that the original code from #723 is still in the code base. Is this just a caching issue, then? Is it possible to delete signal's cache without losing all messages (as a workaround)?

**Comment by stites** [comment]
More updates: It seems like I am only getting messages from one person when there are multiple people in this group chat. At first, I thought it was just one person spamming a group chat, but it's pretty clear that there are other people in the conversation.

I've also cleared my Signal data -- it didn't fix anything. I think this is a backend caching bug that the Android client doesn't know how to handle.

I'll probably keep periodically updating this issue, much like how my Signal continues to send me notifications I don't want to receive.

**Comment by stites** [comment]
Just a heads-up. This issue was fixed in some weird fashion which was dependent on a group-update. Steps that occurred:

1. uninstall signal
2. install signal
3. resync device to your account
4. continue to get spammed because you are still in the same situation as before.
5. Some other group member updates group name
6. magically, you can now leave the group.

Without removing signal and/or clearing your data you won't get this fix even if another member updates the group.

**Comment by greyson-signal** [comment]
If anyone hits any weirdness with getting stuck in groups again, there's a 'block' option in the group conversation settings.
