### ISSUE TITLE
LED notification (with no sound/vibration) does not work when receiving messages

### ISSUE THREAD

**Issue by whaco1** [signalapp/Signal-Android#7904]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is essentially the re-entering of former ticket #1036 / #5189.
When I receive a signal message, the LED does not blink, but it should although neither sound nor vibration is on.
I have my notification setting set to:
- no sound (silent)
- led on
- vibration off

### Steps to reproduce

- do nothing and wait for a message to arrive

**Actual result:** Although signal message is received no LED notification occurs
**Expected result:** The LED light should blink so that I know I have received a message even if my screen is off.
**Workaround** Now I have created a very short sound file that essentially plays silence. It is set as the notification sound. Then the LED light appears.

### Device info

**Device:** Samsung S7
**Android version:** 8.0.0
**Signal version:** 4.19.3

**Comment by greyson-signal** [comment]
I imagine this should be fixed now that we use notification channels in 4.25.x. Please re-open if it's still a problem. Thanks!
