### ISSUE TITLE
Notifications - Wasted Space

### ISSUE THREAD

**Issue by californicated** [signalapp/Signal-Android#7905]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications have some wasted space below message content. 

### Steps to reproduce
Happens for any incoming message.

### Screenshots
Mentioned space marked in red, also shows another app notification with same content and usual heigth.

![screenshot_20180617-003526](https://user-images.githubusercontent.com/11815773/41507488-7a11baf2-7233-11e8-98bd-94ae1de18f14.png)

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 9.0 DP3 (same on 8.1 stable)
**Signal version:** 4.19.3

### Link to debug log
Not needed in this case.

**Comment by greyson-signal** [comment]
Fixed in 4.25. Thanks!
