### ISSUE TITLE
Self destructing messages do not delete on time Android 8.1 OG Pixel

### ISSUE THREAD

**Issue by Carm01** [signalapp/Signal-Android#7906]
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When A user or myself using signal set self destructing messages to lets 1 hour. The messages linger around for close to 3 hours before deleting. 

### Steps to reproduce
- set self destructing messages to a time
- wait and see 

**Actual result:** sometimes ( most of the time ) messages do not delete at the desired time like in the screenshot above most of the time for me

**Expected result:** Should delete within a minute or so of the time you set.

**Screen shot:** 

![screenshot_20180618-165041](https://user-images.githubusercontent.com/6567665/41566567-1af38b7a-732a-11e8-9527-33378c6b0226.png)

### Device info

**Device:** Google Pixel 128 5" 2016 version
**Android version:** 8.1.0 June security patch
**Signal version:** 4.21.0

### Link to debug log

https://debuglogs.org/a05b3fc4588c25812cf58f0b982774c194dcd42b623c0697d595e0e084664726

**Comment by greyson-signal** [comment]
@Carm01 Hi there, I'm looking into this. In the meantime, can you update to the most recent beta (4.21.2) and let me know if it's still happening? Thanks!

**Comment by Carm01** [comment]
I will check it out, thank you

**Comment by greyson-signal** [comment]
@Carm01 The bug exists in 4.21.2 as well, but should be fixed in eb4e606. Thanks for finding this!
