### ISSUE TITLE
Contact sync does not show full list of contacts

### ISSUE THREAD

**Issue by ChemWater** [signalapp/Signal-Android#7910]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal does not populate full contact list after permission to access contacts.

### Steps to reproduce
1. Allow Signal to access contacts
2. Allow Signal to make and manage phone calls
3. Allow Signal to access photos, media, and files
4. Click create message floating button

**Actual result:** Only see 5 of my 100+ contacts
**Expected result:** See my other contacts to write messages to and from.

### Screenshots
![signalscreenshog](https://user-images.githubusercontent.com/30610858/41614052-6685517c-73c5-11e8-92d5-566579489aac.png)

### Device info

**Device:** Samsung ZTE Max XL
**Android version:** 6.0.1
**Signal version:** 4.19.1

**Comment by moxie0** [comment]
Are the 100+ contacts you don't see all Signal users? You can only send a Signal message to a Signal user. If you would like to use Signal for SMS, you can enable it as the default SMS app.

**Comment by ChemWater** [comment]
I was able to see my other contacts when I made it my default app just as you said. Thanks a lot.
