### ISSUE TITLE
Disappearing message timer updates are sent after Backup restore

### ISSUE THREAD

**Issue by fsck** [signalapp/Signal-Android#7911]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When restoring a Signal-Backup, Signal-Android automatically sends disappearing message timer updates without user interaction.

### Steps to reproduce
- Restore a Signal-Backup

**Actual result:** Disappearing message timer updates are sent in every group which had a disappearing message timer set at time of the backup.
**Expected result:** No disappearing message timer update is send

### Screenshots

![screenshot_20180619-201151](https://user-images.githubusercontent.com/17763262/41616277-e64dc15e-73fd-11e8-8233-f4e9e8a24e75.png)
Screenshot from receiving group member.

### Device info
**Device:** Motorola Moto G6+
**Android version:** 8.0.0
**Signal version:** 4.20.8

### Link to debug log
https://debuglogs.org/7c27e3f93e79c6bb41d1bc71feb1225105e941de8dba6f8296f18ddaad2497ac

**Comment by moxie0** [comment]
Did you also link a Desktop instance after restoring? There's an open desktop bug that causes the behavior you're seeing on link.

**Comment by fsck** [comment]
Yes, that might be the issue.

**Comment by flyby325** [comment]
خالد
