### ISSUE TITLE
[Feature Request] Different notification sound in-chat.

### ISSUE THREAD

**Issue by EndosK** [signalapp/Signal-Android#7915]
In another topic (https://github.com/signalapp/Signal-Android/issues/7163), there was the following feature request:

> A lot of chat apps replace the new message notification sound with a really basic Pop when in the chat. For users that have longer notification tones it could get annoying to hear the sound every time they receive a message, whilst having the chat open.
> 
> **Request:
> Replace the standard notification tone with a short basic Pop whilst the chat window is open.**
> 
> Why:
> It gets annoying to hear the notification jingle every time a message is received whilst the chat window is open.
 
 
The only answer to this request was the following:

> **There is an option to turn off notifications while in the chat.** "Settings->Notifications->In-chat sounds" and just turn that off.
 
 
I think the main problem of this solution is, that when turning off the sounds completely while in chat, you have to look at the screen continuously.

A lot of peopleI am trying to convince to use Signal (me included) have the following Problem:

While writing with someone, they have their screen on and are in-chat but not looking at the screen all the time. So they often miss new answer so 1-2 minutes and the conversation gets stuck.

**So, again the same request:
Fully silencing the notification sound while in the chat doesn't fix the problem adequate. Replacing the standard notification tone with a short basic Pop whilst the chat window is open should solve the problem.**

**Comment by moxie0** [comment]
Please don't delete the issue template. From the template: https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests
