### ISSUE TITLE
Some images not downloading

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7917]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some images to group do not download.  Phone was on WiFi but may have been snoozing, although I have signal set to NOT be optimized.

### Steps to reproduce
- be a member of a group
- someone sends an image to the group
- image downloads fine on signal desktop, but not on Android phone

**Actual result:** image may not download automatically and needs to be tapped, despite settings that say it will be downloaded automatically (this was on wifi anyway) 
**Expected result:** images download like normal

### Screenshots
Lost it

### Device info

**Device:** galaxy s9
**Android version:** 8.0 stock
**Signal version:** 4.21.2

### Link to debug log
https://debuglogs.org/c6e7b41ecf5e6ead56e4cce2e45f9e02624e5ef5de9af20dc3ed6edbd5a37b54

**Comment by moxie0** [comment]
I'm guessing the sender in the group is not in your contacts?

**Comment by kpuljek** [comment]
I've had it happen twice when I sent a picture through the desktop application and it just showed as blank on my phone. So it was my picture not showing to me. It's not in the media library either. A lot of messages went through since then, I'll get a debug log next time!

**Comment by greyson-signal** [comment]
@kpuljek Can you confirm what you mean by "showed as blank"? Did you have the ability tap-to-download?

**Comment by kpuljek** [comment]
@greyson-signal no tap to download, when I long press the blank message and select save, it says "Error while saving attachment to storage".

**Comment by greyson-signal** [comment]
@kpuljek Ok that sounds like a separate issue then from the original ticket. If it happens to you again, can you open another issue with a debug log? Thanks!

**Comment by greyson-signal** [comment]
@jeremymasters  Can you tell me:

1) If other people in the group send images, do they auto-download?
2) In one-on-one conversations with the sender, do images auto-download?
3) Does this bug still happen in the same group for this sender? Or was it just happening for a short time?
4) It looks like the logs cover about 2.5 minutes. Do you think you received the "problem message" more than 2.5 minutes before you submitted the log?

Thanks!

**Comment by jeremymasters** [comment]
@greyson-signal 
1. Two people in the group sent and I had the only issue. Works fine now
2. One on one is fine
3. No 
4. I was in a meeting and came back to see this, then tapped to download. One did, one did not.

**Comment by greyson-signal** [comment]
@jeremymasters Sounds like it may have been a transient contact sync issue. Something happened, we thought someone wasn't in your contacts, but then it corrected itself. It's hard to debug without more relevant logs. Let me know if this happens again!
