### ISSUE TITLE
Old safety number changed message gets today's timestamp

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-Android#7922]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open a chat which contains a 'safety number changed' message, this message is given today's timestamp (and with hour:minute:second at 00:00:00 I think). You don't really notice this when you receive a 'safety number changed' message today as it will simply show up at the top of today's chats. If you received such a message days ago though and you haven't opened the chat in the meantime then it is weird to see the 'safety number changed' message with today's date.

### Steps to reproduce
- Someone you chat with reinstalls Signal
- Wait till next day to open the chat

**Actual result:** The 'safety number changed' message is shown to be from today
**Expected result:** The 'safety number changed' message should be listed on the day it was changed

### Device info
**Device:** Google Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.20.9

### Link to debug log
https://debuglogs.org/0c5780c8795dad45e14e4a0c06b793ef497642fc2a134f29774864c00f9364d1

**Comment by MarionaDSR** [comment]
Hello @siccovansas ,

I can see your issue is quite old. May you check if it stills happens?
Thank you!

**Comment by siccovansas** [comment]
Hi @MarionaDSR,

I checked and the problem no longer occurs! Case closed :)
