### ISSUE TITLE
Feature request: No way for group creator to remove members

### ISSUE THREAD

**Issue by rileymcgowen** [signalapp/Signal-Android#7925]
### Cannot remove members from group

I think a great feature for groups on Signal would be for the option to remove members from the group. It doesn't even need to be any specific permission, if anyone can add members, anyone should be able to also remove members.

We use this app for communication at our company, and this is a limitation when employees are no longer working for us.

**Comment by moxie0** [comment]
Please do not delete the issue template when filing issues, thanks. https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests

**Comment by aberlin** [comment]
For anyone who is researching this topic: I guess [this](https://community.signalusers.org/t/improving-signal-group-chats/979/6) is the current state of this feature. HtH.
 If someone has the correct link to where the current state of Discussion/development of this is documented/tracked, pls add
