### ISSUE TITLE
Messages can be quoted into another conversation

### ISSUE THREAD

**Issue by zznidar** [signalapp/Signal-Android#7935]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A message can be quoted into another conversation and original sender's phone number is revealed.

### Steps to reproduce
- Hold over a message in a conversation and select _Reply_
- Hold over another message in the same conversation and select _Forward_
- Select a different conversation from the list

**Actual result:** The selected message from the first conversation is quoted into the second conversation with the phone number of the original sender. 
**Expected result:** Messages should not be quoted into different conversations.

### Screenshots

![signal-attachment-2018-06-24-115208](https://user-images.githubusercontent.com/20877556/41817951-2893bd84-77a5-11e8-9b7b-cd47937a5703.jpeg)

### Device info

**Device:** Meizu m1 metal
**Android version:** 5.1
**Signal version:** 4.20.9

### Link to debug log
/

**Comment by Trolldemorted** [comment]
Why is this a bug? Is it any different from forwarding a message and then commenting it?

**Comment by zznidar** [comment]
It is not an intended feature as a trick has to be used in order to achieve this.
It reveals the phone number of the original sender. If you forward it, you only get the message content (without its author). Additionally, it looks more authentic than forwarding a message.

**Comment by Trolldemorted** [comment]
The ux could indeed be smoother, but you also reveal the phone number if you screenshot a conversation and send the screenshot to someone.

**Comment by FeuRenard** [comment]
I think this is a bug. The quoted message is part of the input panel. When I select another message from the conversation I would not expect to carry over contents from the input panel to another conversation.

I suppose around [here](https://github.com/signalapp/Signal-Android/blob/bb7a33ed8e136f4c8db20654234e345a916ebf55/src/org/thoughtcrime/securesms/ConversationActivity.java#L314) `inputPanel.clearQuote()` should be called.
