### ISSUE TITLE
Contacts that have labels attached to them are unsearchable in the Signal UI.

### ISSUE THREAD

**Issue by wincohi** [signalapp/Signal-Android#7940]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a few contacts that have been assigned labels in the stock Contacts app. However, I am unable to initiate an SMS or Signal text conversation with them through the Signal UI—I must instead open the Contacts app and choose to message them from there. All unlabeled contacts are searchable without an issue.

### Steps to reproduce
- Open the Android stock Contacts app
- Create a label at the menu on the top-left
- Add a contact (or multiple) to the label
- Open Signal
- Press the button in the bottom-right to initiate a conversation
- Attempt to find the contact(s) in the list

**Actual result:** The contact(s) is absent from the list, and will not show up even if you search them by name.
**Expected result:** The contact(s) should appear in the list as usual.

### Screenshots
Screenshots | &nbsp; | &nbsp;
-------- | ------- | --------
![screenshot](https://user-images.githubusercontent.com/14862440/41882187-7b3495ca-78b5-11e8-8ba1-9aee304af1ac.png) | ![screenshot](https://user-images.githubusercontent.com/14862440/41882402-b3a2e384-78b6-11e8-8b3a-b6120557fe63.png) | ![screenshot](https://user-images.githubusercontent.com/14862440/41882428-cc2b98ba-78b6-11e8-9960-0cabeffa5a7e.png)
*Searching for contact in Signal* | *Searching for contact in Contacts app* | *Contact has special label*

### Device info

**Device:** Google Pixel 2 (non-XL)
**Android version:** 9.0.0 DP2
**Signal version:** 4.21.6

### Link to debug log

https://debuglogs.org/47c241b592d6d187ef20189b4eb187363f292ad9e7451297b083750385258797

**Comment by tl0gic** [comment]
I have the same issue. However, I noticed that also some of my contacts without labels have the same problem.

I'm also using a Pixel 2 (non-XL) version 9. Signal version 4.31.8.

**Comment by TeknoCepni** [comment]
Excuse me, I didn't reproduce this bug. Is there this issue still ?
