### ISSUE TITLE
Contacts and message sync not working on Windows 10 aka "MultiDeviceContactUpdateJob: Not multi device, aborting..."

### ISSUE THREAD

**Issue by SeppPenner** [signalapp/Signal-Android#7941]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Contacts and message sync not working.

### Steps to reproduce
- Install signal app on Android
- Install signal app on Windows
- Connect both devices to network using Wifi

**Actual result:**
- No sync done

**Expected result:**
-Sync of the contacts and messages

### Screenshots

![grafik](https://user-images.githubusercontent.com/9639361/41665542-7e1a3b20-74a8-11e8-86cb-35f178add74b.png)

### Device info
**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** 4.21.6 on Android and 1.13.0 on Windows.

### Link to debug log
https://gist.github.com/SeppPenner/2e3b9b20ed70079f8ab1fbfb67ed4a76

**Comment by greyson-signal** [comment]
Looks like somehow internally we don't think that you have a linked device. Can you try unlinking and re-linking your desktop? Note: Unlinking and re-linking will result in you losing your message history on desktop (mobile history will be untouched).

**Comment by SeppPenner** [comment]
Hi @greyson-signal I will try that and check if it works.

**Comment by SeppPenner** [comment]
@greyson-signal @Trolldemorted: It works now :D
