### ISSUE TITLE
Crash attempting to forward errored message

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7951]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Attempting to forward a message thread that has a message retrieval error results in a fatal crash.

### Steps to reproduce
- On error downloading mms message (not sure how to reproduce)
- Hold the message to get options, tap forward icon

**Actual result:** Signal crashes
**Expected result:** Error toast or forward is disabled for message errors.

### Screenshots
![signal_error_fwd](https://user-images.githubusercontent.com/5124946/42121015-694b24e6-7bf3-11e8-8bfd-f144494c9f00.png)
![signal_crash](https://user-images.githubusercontent.com/5124946/42121010-564bd05c-7bf3-11e8-9af5-20bbd31c9de7.png)

### Device info
**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.21.6

### Link to debug log

https://debuglogs.org/739f42a284b0dca41b8b36e9d713fbc388b55701629c3b46efe26d1f46ac078c

**Comment by cascheberg** [comment]
From your debuglog:
> FATAL EXCEPTION: main
E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 21355
E AndroidRuntime: java.lang.ClassCastException: org.thoughtcrime.securesms.database.model.NotificationMmsMessageRecord cannot be cast to org.thoughtcrime.securesms.database.model.MediaMmsMessageRecord
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationFragment.handleForwardMessage(ConversationFragment.java:402)

Looks like this commit fixed a similar issue: fd6d947df39ec68036f7ba3af6bb8d538b2284b4
There are some more similar casts in other places, but I can't really tell which of them are save.

**Comment by greyson-signal** [comment]
Thank you for the report! Merged into 4.23. c7066c07969080d666a947766708fbdd96459402
