### ISSUE TITLE
App crash when importing sms database

### ISSUE THREAD

**Issue by alternativesurfer** [signalapp/Signal-Android#7953]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Android app crashes upon initial "import system SMS database" execution. 
Approximately 10% into the import the app crashes. 

### Steps to reproduce
- Install app
- Initial configuration
- Import
- Import system SMS database
(Import begins)
- makes it 10% then app crashes. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Google Pixel 1
**Android version:** 8.1.0
**Signal version:** 4.21.6

### Link to debug log

https://debuglogs.org/70db2b37a36fada090443d9959c4c269c50ca75d65951765e6586483568cb78e

**Comment by alternativesurfer** [comment]
Ran the test again, same results. 
https://debuglogs.org/5f3ffafe2615f682ddd4e68cc00a6230d595bdba5fbd17bc49bdf3d092c84162

**Comment by pshem** [comment]
Same result when importing an encrypted backup created by Signal on the previous phone. Sorry, no debug log.

Device: Samsung Galaxy J5
Android 7.1.1
Signal: 4.22.4

**Comment by alternativesurfer** [comment]
Was this capability removed?
I don't even see Import anymore

**Comment by alternativesurfer** [comment]
Tested again, still occurring. 
Logs: https://debuglogs.org/08bd13c3ede1890947aa9811ec272275267682402446fc4d5c72671cc405e658

**Comment by dfeinzeig** [comment]
Still an issue. Pretty big barrier to usage. Any updates?

**Comment by jlund-signal** [comment]
Version 4.39 should (hopefully) resolve this issue. You can join the public beta [here](https://play.google.com/apps/testing/org.thoughtcrime.securesms) if you would like to test it now.
