### ISSUE TITLE
Voice messages stop playing when the screen goes off

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#7954]
- [x] I have searched open and closed issues for duplicates -> see #7419 and #6993
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice messages stop playing when the screen goes off

### Steps to reproduce
- Receive a longer audio message than it takes more time than your cell phone's screen to turn off
- Play the message
- Wait to screen off

**Actual result:** Voice messages stop playing when screen turns off
**Expected result:** Voice messages continue playing even if the screen goes off

### Screenshots
Not necessary

### Device info

**Device:** Samsung SM-G610M
**Android version:** 7.0
**Signal version:** 4.22.4

### Link to debug log
Not necessary

I'm not sure if it's a feature request, but as #7419 said, I don't want to be holding my phone or have the screen on (to conserve battery) that whole time and it's a bit annoying to keep touching the screen every time.

**Comment by Dyras** [comment]
Yup I've noticed the same thing. The audio disappears the nanosecond the screen turns black automatically. Super annoying since it's automatic and I don't want to increase the timer because that would eat more battery :(

**Comment by UserX404** [comment]
still persist in 4.30.8
[Log](https://debuglogs.org/c4e76fde261666740ee280891dffa1b00eae43b9d8927c0a31cc3559a1235db4)

**Comment by thsowers** [comment]
This looks like it was fixed back in 0095e00 , but I am still able to reproduce, device specs below:

Device: Samsung G7 ThinQ
Android version: 9.0
Signal version: 4.47.6

 Is there anything in particular that I could start looking into to help out with this?

**Comment by wavexx** [comment]
Same here on android 7.1.2 (lineage), signal 4.47.7 (and all previous versions so far)

**Comment by dankerthrone** [comment]
Still a problem. Quite annoying.

**Comment by Edu4rdSHL** [comment]
Please can you take a look to it again, @greyson-signal ? It's a bit annoying that you need to keep the screen on during playing voice message. 

Will be go if:

1. The screen is on while playing the message. 
2. The message continues playing still with the screen off (better).

Thanks.

**Comment by thsowers** [comment]
I was able to fix the problem by going into settings -> Battery -> Power Saving Exclusions and adding Signal to this list

**Comment by dankerthrone** [comment]
> 
> 
> I was able to fix the problem by going into settings -> Battery -> Power Saving Exclusions and adding Signal to this list

Didn't work unfortunately. Still having this issue on Android 9 / Signal 4.58.5

**Comment by ant0nwax** [comment]
I also have the issue on Samsung Note 8 on Android 9...
I have an Idea for workaround... before recording starts you could LOCK TILT and after recording finished the TILT can be UNLOCKED.
The issue is that when you touch the recording microphone and phone screen tilts, your thumb or index finger does not touch that button anymore

**Comment by Edu4rdSHL** [comment]
The problem is playing audio, not recording.

**Comment by Totorrr** [comment]
@fumiakiy above apparently implemented audio playing as a service, which would be great having for this issue. Would you have a look to consider a merge @greyson-signal? 
Thanks

**Comment by greyson-signal** [comment]
@Totorrr We have work in progress to do this ourselves :)

**Comment by ant0nwax** [comment]
interesting to see that two teams develop the same functions instead of
working together

**Comment by Edu4rdSHL** [comment]
This was fixed in 4.74.0.

**Comment by ant0nwax** [comment]
oh i could maybe reinstall signal and test

**Comment by Edu4rdSHL** [comment]
Just join the beta or wait until the feature is released in the stable version.

**Comment by VadioGitazy** [comment]
> This was fixed in 4.74.0.

Unfortunately, not until today. Me and everyone around on Android device experiencing still this issue. Listening longer voice message, screen goes off and after some time the sound stops but when you turn on the screen you can see the progress line and time going on. So, we must close the app, open it again and play the voice message from the point it stops again. This is annoying.

**Comment by ant0nwax** [comment]
still signal is uninstalled, until fixed

Kind Regards From Phoneland

**Comment by VadioGitazy** [comment]
The owner of this thread closed it, so I made a new one active: 
https://github.com/signalapp/Signal-Android/issues/11471
Let's see if they fix it. This issue is there since I installed Signal.

**Comment by smoke007** [comment]
The issue is resolved for me using beta version 5.23.7.  Seems the new exoplayer update fixes the issue.  See notes in https://github.com/signalapp/Signal-Android/issues/11471
