### ISSUE TITLE
Group avatar copied to Signal's internal group media gallery multiple times

### ISSUE THREAD

**Issue by Rolf558** [signalapp/Signal-Android#7955]
Hi,

I did (roughly) the following steps:

- I made a new group with 3 participants total (including myself)

- I did a group update to set a group avatar picture and change group name

- Set self-destruct timer to 1 week

- [Some messages have been written in the meanwhile]

- I did a group update to add one more participant and change group name (in one the same group update)

Result:
I found 4 copies of the same group avatar in the group's Signal-internal media gallery.

Expected Result:
There should be zero copies of the group avatar in the group's Signal-internal media gallery.

Signal Android build: 4.22.4

**Comment by Rolf558** [comment]
Additional info:
Each group update creates a new copy of the avatar.

**Comment by cascheberg** [comment]
For reference: this has previously been reported (and then mass-closed) as #3380

**Comment by erik55** [comment]
I can confirm that bug. I am not sure how that happened, but I also have that effect in a group, with four times the group avatar in the media gallery. Some contacts have been added by at least two different participants of the group. It seams so, as if some form of update to the group adds the group avatar.
