### ISSUE TITLE
Missing timer setting for one month, 3 months and one year

### ISSUE THREAD

**Issue by Rolf558** [signalapp/Signal-Android#7958]
Hi there,

I'm missing timer settings for more than 4 weeks. Often Information should be kept longer than 4 weeks but can/should be deleted in the longterm.

I think with adding one month, 3 months and one year everyone should be happy. Btw. Wire just has added one month.

**Comment by greyson-signal** [comment]
For feature request, please visit [the forum](https://community.signalusers.org/). Thanks!
