### ISSUE TITLE
make use of notifications channels

### ISSUE THREAD

**Issue by CircleCode** [signalapp/Signal-Android#7961]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications are not splitted accross different channels and cannot be managed separately

### Steps to reproduce
- use signal without google services
- signal runs in background
- it adds a notifications saying it is running in background

**Actual result:**
this notification cannot be disabled while keeping other notifications

**Expected result:**
Notifications settings for signal offers (at least) 2 channels:
- background service
- messages
- (eventually) *service* notifications

### Device info

**Device:** OP3T
**Android version:** 8.1.0
**Signal version:** 4.22.4

**Comment by moxie0** [comment]
Please use the forums for feature requests, thanks!
