### ISSUE TITLE
Screen locking does not work an Android 4.3

### ISSUE THREAD

**Issue by mancsik** [signalapp/Signal-Android#7962]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The phones screen is protected with a pattern (lock after 5min)
Signal Setting for autolock is 1min (can not be Shorter)
There is a "Lock Signal" function visible when pulling down message Center (when "lock Signal" is tapped the message disappers)

### Steps to reproduce
- set a Display lock
- set Signals autolock to 1min
- lock Signal from the message Center or wait longer than 1 min

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Signal opens without requesting the unlock pattern
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
I expected Signal requesting the unlock pattern

### Device info

**Device:** Sony C5303 (XPERIA SP)
**Android version:** 4.3 
**Signal version:** 4.21.6

### Link to debug log
https://debuglogs.org/d46bf9a3a949b0ffedb141bc8d60291ef6d3ad0735d01b85b460631a2d819807

**Comment by mancsik** [comment]
Hi - you can close the case





Mit freundlichen Grüßen
Manfred Csikós


Ing. Manfred Csikós
Dammstraße 4a/5/9
2460 Bruckneudorf

***@***.***

gesendet von meinem XPERIA™-Smartphone +436767046866

stale[bot] ***@***.***> schrieb am Fr., 28. Jän. 2022, 17:54:

**Comment by kaktusztea** [comment]
Hi @mancsik, you opened the ticket, you also can close it.
