### ISSUE TITLE
Can't scan QR code to pair desktop

### ISSUE THREAD

**Issue by ouillepouille** [signalapp/Signal-Android#7967]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't scan QR code to pair device (Debian based desktop)
This is not a focus issue. The camera view is just pitch black. 
Other barcode apps work ; camera works flawlessly.

### Steps to reproduce
Get to pair screen with cam scanner view.

**Actual result:** total black screen
**Expected result:** camera view 

### Device info

**Device:** Moto G 1st gen
**Android version:** 5.1
**Signal version:** latest android

### Link to debug log
https://debuglogs.org/7b534ef3547d1334b3a2d8da10af47afb47226710ac822db94de8c52cab2c3c8

**Comment by FeuRenard** [comment]
Just for reference: #4843 (legacy issue)

**Comment by greyson-signal** [comment]
@ouillepouille Can you tell me if the quick-capture preview is working? That's the little camera button in the compose box when you're in a conversation. It should show a little half-screen camera. I'm curious if all camera stuff isn't working, or if it's just a specific thing we're doing with QR code capture. Thanks!

**Comment by ouillepouille** [comment]
Somehow, I reinstalled the app and it worked.

So I can't test the bug :-/
I can tell you all camera functions were A-OK (I checked in other apps)

2018-07-16 11:08 GMT-04:00 Greyson Parrelli <notifications@github.com>:

**Comment by MartinX3** [comment]
It would be nice, if we can get a second way to pair this app with the desktop.
Sometimes there is no camera preview you can use.

In my case I use a Sony Phone where the bootloader unlocking killed the camera preview (just black) + green photos if I use signal to take a photo.

While with the stock camera app and the open source app opencamera the preview is black too, but I can still take pictures.

**Comment by jnm2** [comment]
My phone camera broke. I'm getting a new one in a week or two, since the camera isn't something I usually care about, but it means there's no way to pair devices till then. I would have expected a fallback option for sure, such as entering the code manually.

**Comment by AO-LocLab** [comment]
I had the same issue that ouillepouille described as a bug, also on a Moto 1st gen. I killed the app, emptied the cache and restarted the app. I was then able to scan a QR Code.

**Comment by DuaelFr** [comment]
My phone camera can't focus anymore. I'll have to change the camera or the phone to make it work again. Is there another way to pair devices? Would it be possible to reverse the binding process and make the computer app read a QR code on the mobile?

**Comment by thomasesr** [comment]
My phone has a broken camera and I don't have enough money to buy a new phone and I cannot buy a spare camera online (if some one knows where I can find a Rear Camera for a Vernee X1 Pro). The front facing camera still works but I find it annoying that I can't pair my laptop because the only way to do it is via QR Code. There should be another method of pairing.

**Comment by smichea** [comment]
I experienced the same problems.
The pb is that the signal android app still doesnt have permission to use the cam. 
The  fix is easy and come for what greyson said earlier : go in a conversation and click the little cam on the bottom right like if you were sending a pic to your contact. Signal will then ask you permission to access your cam.
Allow it then rescan your Qr code.

**Comment by aizelauna** [comment]
Same issue here, I am unable to scan the QR code because of a broken camera glass, the QR code seen by the phone is blurry and has low contrast whereas the QR code is displayed in full screen mode in my laptop and the screen contrast is at its maximum.
Having a manual method to pair desktop app with the device would be great to manage all these corner cases.

Unfortunately, this issue is not new:
https://github.com/signalapp/Signal-Android/issues/5153
https://github.com/signalapp/Signal-Android/issues/4637

**Comment by jtourille** [comment]
Similar issue here, the QR code scan remains black. I am able to take pictures and send them. All the permissions are granted. It would be great to be able to enter some kind of code manually to pair new devices.

**Comment by Bombardier-C-Kram** [comment]
I am able to scan the qr code using any other qr code scanner app on my phone, however when I try to scan it using the signal app, it does not work. I have tried clicking on the link included in the qr code, however that just takes me to the scanner within signal.

Please add a manual pair method.

**Comment by eloeffler-fhnw** [comment]
I am using Signal on Waydroid on the pinephone. As the camera isn't accessible to Waydroid at this time, I cannot scan any QR codes. This is one of several [good reasons](https://github.com/signalapp/Signal-Android/issues/5153#issuecomment-230594440) why it would be important to have a manual entry option for the code.

**Comment by Wannabooo** [comment]
Using Signal on a Galaxy S21. Signal refuses to scan a QR to link desktop. Have tried all the brightness settings, zooming in, printing it out, etc with no success. The Samsung Camera and various other apps from the app store have no problem scanning QR codes, I can provide screencaps if needed.

**Comment by MartinX3** [comment]
J

**Comment by Delan168** [comment]
Same issue on Fairphone 4: QR code can be read just fine with any app (including the one provided for linking device), but Signal doesn't want to hear anything. Tried zooming in, screenshots, other screens --> impossible to pair device :/

**Comment by stheid** [comment]
> Same issue on Fairphone 4: QR code can be read just fine with any app (including the one provided for linking device), but Signal doesn't want to hear anything. Tried zooming in, screenshots, other screens --> impossible to pair device :/

Which Signal version do you have installed and via which app-store.

I faced the same issue [today](https://community.iode.tech/t/signal-cant-link-devices-a-camera-issue/552/5) but i figured out it does not happen with the [5.39.3](https://signal.org/android/apk/), but it happens with 5.40.0. various sources distribute different versions.

Since the google-play store seems to distribute some version before 5.40 its not yet a widely known problem.

**Comment by Delan168** [comment]
Version 5.40.0 from the Play Store (beta tester program). Is there any easy way to downgrade to 5.39.* for testing purpose and/or to notify developers?
Side note: Camera on the Fairphone 4 is not the best in the market and autofocus can be picky, but I managed to read a link with another QR code app, therefore I excluded a hardware problem or an issue on the new device.

**Comment by stheid** [comment]
Its not related to the hardware. It reads the QR code in a fraction of a second with on 5.39.3. That can be clearly ruled out as the culprit.

**Comment by Wannabooo** [comment]
For me the issue turned out to be the tilt/angle of the phone. Signal is detrimentally more particular about the angle of the phone to read the QR code than any other app. Holding the phone normally with the camera angled ever so slightly towards the floor caused specifically Signal to not read the QR code. Signal seems to need the angle to be very specifically over 90 degrees, pointing the camera more up and tilting the screen slightly towards the body.

**Comment by cody-signal** [comment]
We reworked the camera apis in 5.40 for QR scanning. It sounds like the Fairphone does not like it very much. How well does the camera work for taking photos/videos/calling?

**Comment by Delan168** [comment]
All three camera (two back and one front) work fine in most of the circumstances. As mentioned [before](https://github.com/signalapp/Signal-Android/issues/7967#issuecomment-1140328252) the Signal pairing QR code is immediately recognized by [another app](https://play.google.com/store/apps/details?id=com.kaspersky.qrscanner).
I tried several time, under different lighting conditions (day/night), different tilts ([as suggested by Wannabooo](https://github.com/signalapp/Signal-Android/issues/7967#issuecomment-1140476770)), different screens (the one from the laptop and the 4K modern screen linked to it), and tried screenshooting the link and zooming in/out. Signal doesn't want to know anything and it failed every time.

**Comment by cody-signal** [comment]
@Delan168 can you provide a debuglog?

**Comment by lukect** [comment]
QR code isn't recognized anymore in latest beta version 5.40.1 from Play Store on OnePlus 7T Pro.
https://debuglogs.org/android/5.40.1/8217626615918a25fce66e543d888dd790a0874e668fe14901db2dc76c027ab0

It worked before in version 5.39.

**Comment by greyson-signal** [comment]
Merging into https://github.com/signalapp/Signal-Android/issues/12009, which is where most of the chatter seems to be.
