### ISSUE TITLE
Message sent status out of sync for message info dialogue

### ISSUE THREAD

**Issue by Rolf558** [signalapp/Signal-Android#7969]
Hi there,

I fond the following issue while doing the following steps:

- I tried to send a a message into a group with 4 participants total while I was connected to a WIFI while locked in the captive portal

- I received a failure notice in Signal

- I unlocked the captive portal within a browser

- I switched back to signal and triggered a resent from the group message view

- The message has been sent (got 2 check marks in the group message view)

- I selected the message

- I tapped Info

- In the message info dialogue the message still has been marked as failed for all three participants.

It looks like the info dialogue was out of sync.

(In addition I was wondering why I have seen separate resent buttons for each participants. I thought I have seen in recent betas that a common resent button has been introduced a short time ago. But Maybe I am wrong in this point.)

In addition I cannot say at the moment if really the message has been sent twice since I have tapped resent in group message view and message info dialogue.

I also don't know if a similar bug exists for non-group message.

Found with Signal Android build 4.23.1.

**Comment by Rolf558** [comment]
According to a participants feedback on my question if there has been a duplicate message, the message has only been sent once.

It looks like the resent from the message info dialogue had no effect. (Or the resent from the group message view.)

**Comment by moxie0** [comment]
Thanks but please do not delete the issue template, we can't manage issues without it.

**Comment by Rolf558** [comment]
@moxie0 sorry. But this issue seems to have resolved. I cannot reproduce it any more at the moment.
