### ISSUE TITLE
Blocked users don't leave groups on the blocker's phone

### ISSUE THREAD

**Issue by Virepri** [signalapp/Signal-Android#7970]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a user is blocked, they cannot actually leave the group on the blocker's phone-- the message straight up doesn't make it through. Thus, the blocked user will continue to receive all messages from the blocker(s) within the group despite leaving.

### Steps to reproduce
- Add a user to a group
- Block the user
- Blocked user leaves the group
- Send messages in the group

### Steps to fix the issue on a per-group basis
- Unblock the user
- Add them to the group again
- Have them leave again

**Actual result:** Blocked user continues to receive messages despite being removed from the group; but only from the blocker(s)
**Expected result:** Blocked user should not receive messages as they have left the group.

### Screenshots

This image is from the blocked device, as it is the affected device.
![image](https://user-images.githubusercontent.com/13892402/42337274-1a883190-803b-11e8-8540-dfa491cb2c32.png)

### Device info

Blocker device:
**Device:** Google Pixel 2 XL (taimen)
**Android version:** 8.1.0
**Signal version:** 4.22.4
I have no info on the blocked device.

### Link to debug log

I doubt the logs will contain much of anything for this particular issue, but here you go.
[Blocker device](https://debuglogs.org/0b4b3b83997b1f44819fad0215af966b55a14c9c856778b176b4ae379a111fd2)
I have no info on the blocked device.

**Comment by 2-4601** [comment]
Related #3400

**Comment by Trolldemorted** [comment]
Also, if you are in a group with a blocked user and the blocked user adds a new nember, the views on the group are diverged: You and any member you add afterwards won't know about the new member, but the rest of the group does.
