### ISSUE TITLE
Signal crashing many times when trying to submit log

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7976]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When typing on the desktop client, then picking up my android device, the android device goes through notifications for messages I've been receiving on my desktop already.  After this flurry of activity is done, if I try to check the debug log, signal will crash every time until I restart my phone.

### Steps to reproduce
- have a linked desktop client
- text people with said desktop client
- open your android app on the phone
- watch the other party's messages you've already read flood in
- check your signal log

**Actual result:** Signal goes down in flames and system asks if you want to restart the app
**Expected result:** I open the log and send to greyson for him to decipher

### Screenshots
N/A

### Device info

**Device:** Samsung Galaxy s9
**Android version:** 8.0 stock verizon
**Signal version:** 4.23.4

### Link to debug log
Can't get them!

**Comment by moxie0** [comment]
Sorry but unfortunately there is no way for us to understand a crash without a debug log. If in-app capture doesn't work, you'll have to use adb logcat.

**Comment by jeremymasters** [comment]
Understandable. I will update as possible.

**Comment by jeremymasters** [comment]
For the record, this was not happening yesterday and I was on 4.32.3.  I did see some server changes but didn't know if those had been realized on the production instance yet or not.

**Comment by jeremymasters** [comment]
I removed a second desktop instance and haven't seen the problem since.  Closing since I really can't provide tangible data.  Will re-open if I can.

**Comment by jeremymasters** [comment]
Happening again, but this time right after I tap the link for the debug log.
https://debuglogs.org/2abeabd59e704a7e651b7adb3f9d001fcd087ee79a75cdd2dc5a8910f6cdcdc2

**Comment by moxie0** [comment]
`````
08-02 09:43:09.375 16935 16935 V InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@49eb75c nm : org.thoughtcrime.securesms ic=com.android.internal.widget.EditableInputConnection@9a4a65
08-02 09:43:09.375 16935 16935 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
08-02 09:43:09.912 16935 16935 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 873172)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: Got RemoteException calling setExtractedText
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: android.os.TransactionTooLargeException: data parcel size 873172 bytes
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at android.os.BinderProxy.transactNative(Native Method)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at android.os.BinderProxy.transact(Binder.java:761)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at com.android.internal.view.IInputContextCallback$Stub$Proxy.setExtractedText(IInputContextCallback.java:220)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:326)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at android.os.Looper.loop(Looper.java:164)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-02 09:43:09.916 16935 16935 W IInputConnectionWrapper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`````

**Comment by greyson-signal** [comment]
I believe I made some changes a while back that should have resolved this.
