### ISSUE TITLE
Quoted an image, now cannot open the app at all!

### ISSUE THREAD

**Issue by taimoor406** [signalapp/Signal-Android#7983]
The app crashes immediately on start. I can receive messages but that's all. Even quickreply through notifications does not work.

How it happened:
- Received a Signal message with text accompanied with an image
- Quoted said text with an emote (smiley face angel) and replied
- App crashed
- Now every time I open the app it crashes after one second

Signal Version: 4.23.4
Device: OnePlus 6
OS: OxygenOS 5.1.8 (Android 8.1.0)

**Comment by haffenloher** [comment]
This is just a guess, but does Signal still crash if you put your phone in airplane mode / disable all network connections? If not, you could collect a crash report from the settings and then delete the problematic message.

**Comment by taimoor406** [comment]
https://gist.github.com/taimoor406/9635b4a1bc198764ad0a8d62cdee97e4
^ My logs

The app does work if I disable wifi + data! But as soon as I turn it on it crashes.
Deleting the message worked for me. Here's a screenshot of the conversation:

https://i.imgur.com/htslUzQ.jpg
