### ISSUE TITLE
General Feedback on Signal Features

### ISSUE THREAD

**Issue by coffeewithfriend** [signalapp/Signal-Android#7989]
Hi Signal Developer, 

First of all we would like to thank you for develop this communication platform. It helps us a lot with better and safer communication amongst activists in our country, Indonesia.
But we do find some issues and want to share it with the devs for better protecting the privacy of the users.

**Expected behavior:**
1. We can choose to use phone number or screen name for registration
2. Invite/ Approve contacts
3. To be able to remove someone from a group chat (ex: if one of the members lost their mobile)

**Current Behavior:**
1. Still using mobile number for registration. 
2. Address book synchronization; so everyone that have your phone number even if they’re not in your address book can chat and call you.
3. Can’t kick someone from group chat

About us: We are 2 digital security trainers from Indonesia doing a UX workshop with 10 digital security tools users to look at some tools and collect feedback on user experience.

**Comment by duchampdev** [comment]
Especially the last one seems to be an absolutely valid point to me. But please respect the Signal developer's decision, that GitHub should just be used for bugs/issues in behaviour, not discussing features in general. They are a small team and like this, it's easier to handle things for them.
Discussions are meant to take place in the forum: https://whispersystems.discoursehosting.net

**Comment by greyson-signal** [comment]
Thank you for the feedback! In the future, as @duchampdev pointed out, please start discussions like this on the forum. Github is just for bugs.
