### ISSUE TITLE
[Feature request] Mute incoming call

### ISSUE THREAD

**Issue by leafcutterant** [signalapp/Signal-Android#7991]
From time to time I get a call that I don't want to answer, but neither do I want to reject it ( = let the person on the other end know that I'm there and I rejected it). Most phones have an option for this displayed on screen to mute the call and let it "ring" without the ringtone being played. I haven't found such an option in Signal 4.23.3, so I propose adding it.

**Comment by duchampdev** [comment]
Good idea, but please respect the Signal developer's decision, that GitHub should just be used for bugs/issues in behaviour, not discussing features in general. They are a small team and like this, it's easier to handle things for them.
Discussions are meant to take place in the forum: https://whispersystems.discoursehosting.net

**Comment by moxie0** [comment]
Also if you tap the power button it should mute.
