### ISSUE TITLE
Blue filled checkmarks for read receipts not working

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8001]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Blue double checks doesnt work after updated to 4.24.1

### Steps to reproduce
- write a message with the "read receipts" option on
- wait to the another user read the message. 
- see for the old blue checks

**Actual result:** You only can see the news "read receipts" checkmarks filled with the actual color theme.
**Expected result:** I can see the checkmark with the old blue color.

### Screenshots

Not needed.

### Device info

** Device Info:** Samsung Galaxy J7 Prime
**Android version:** 7.0
**Signal version:** 4.24.1

### Link to debug log

Not needed

**Comment by duchampdev** [comment]
This seems more like a personal opinion than a bug to me. It's the developers' design preference, how they indicate the message was read. Blue marks are just one way out of many.

**Comment by greyson-signal** [comment]
We've removed the blue color from the checkmarks in favor of filling the checkmarks in to indicate that a message was read. Not using blue gives us a little more wiggle room to play with bubble colors in the future. 

The line you referenced with the blue tint should be removed, thanks! I appreciate the research :)
