### ISSUE TITLE
Self-sends with disappearing messages are buggy.

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#8002]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See comments above screenshots.

### Screenshots

When setting disappearing message time, the corresponding bubble is too small:
(sidenote: does the icon in front of "1 HOUR" or "6 HOURS" have a somewhat different shade of gray than the font?)

Edit: As pointed out by @rainerzufall, the bubble is not just too small - it shouldn't exist in the first place.

![screenshot_20180719-093556_cr](https://user-images.githubusercontent.com/12624674/42932812-987b9dcc-8b43-11e8-8ae4-3cd92564f290.png)

Back button in dark theme should be white/gray (or whatever exact color you're normally using) here:

![screenshot_20180719-093621](https://user-images.githubusercontent.com/12624674/42931590-64f65abc-8b40-11e8-873a-a6f023d5cb06.png)

The icon colors for a) the disappearing message timer and b) the delivery status are not the same (at least in the dark theme). Since the delivery status icon imho should have a lighter color anyway, I suggest adjusting the color of the delivery status icon to the color of the disappearing message timer icon:

![screenshot_20180719-093733_cr](https://user-images.githubusercontent.com/12624674/42931554-48b2334e-8b40-11e8-94c1-2579f80675ce.png)

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.24.0

**Comment by rainerzufall** [comment]
@RiseT Your first screenshot is actually not just a message bubble, which is too small, but it is rather a bug concerning activating und deactivating disappearing messages:
Apparently, as of 4.24.1, the activation dialogue ("You set the disappearing message timer to X seconds") is considered to be a "message itself"; it appears with a small bubble (as you described), but also disappears when the timer runs out. That is in contrast what moxie said was intended when introducing disappearing messages.

**Comment by RiseT** [comment]
@rainerzufall Thanks for hint! You're right.

**Comment by greyson-signal** [comment]
@RiseT The extra bubble is throwing me for a loop. I can't seem to repro it. We haven't changed how timer updates are handled at all. 

@rainerzufall Are time text updates actually disappearing for you? I can't repro that either.

Regarding the shade of the message icons (disappearing, read, etc), they should all be the same shade. I'm also a fan of brightening them up a bit as well. Same with the update time icon. We'll discuss that, thanks!

**Comment by RiseT** [comment]
> The extra bubble is throwing me for a loop. I can't seem to repro it. We haven't changed how timer updates are handled at all.
@greyson-signal An extra hint: I've just tested this. It seems like I'm only getting the extra bubble when opening a conversation with myself (i. e. my own phone number) and then change the timer interval.

**Comment by ForestGu** [comment]
The new UI looks awesome! Thank you for this amazing work!
I am able to reproduce the extra bubble in the chat with myself as well. the outgoing timer is displayed correctly, whereas the incoming timer is not. I think this might be related to incoming messages being labeled as received via MMS in the message info in this chat with myself.
BTW I noticed one more UI Glitch: When using dark theme, sharing a contact, and editing the name, a blue action bar is shown (consistent would be dark).

**Comment by greyson-signal** [comment]
@RiseT  Ahhh ok I can repro now. Looks like self-send disappearing messages are pretty broken in general. Thank you for that!

**Comment by greyson-signal** [comment]
@ForestGu Glad you like it! And yes, I see what you're saying, that specific activity has a mis-colored action bar. I'll address that as well, thank you!

**Comment by RiseT** [comment]
@greyson-signal While we're at it: I've noticed you've modified some strings for disappearing messages in these latest commits. Could you please split each of these strings into 2 separate strings for "off" and for a time limit as described in https://github.com/signalapp/Signal-Android/issues/7501? There's a PR already but it looks like that got clobbered by the latest changes.

**Comment by greyson-signal** [comment]
@RiseT I'll take a look :)

**Comment by pedzed** [comment]
> The new UI looks awesome! Thank you for this amazing work!

The (light) theme looks really bad in my personal subjective opinion. What's a good place to give feedback?

**Comment by greyson-signal** [comment]
@pedzed Sorry to hear that -- feel free to give details in this [forum post](https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532/7). Thanks!

**Comment by greyson-signal** [comment]
I've addressed a lot of the small bugs here. Turns out the big one -- the interaction between self-sending and disappearing messages -- is an outstanding issue. Same problems occur pre-4.24.x. I'll still try to get the fix into 4.24.x, but it might not make it into 4.24.2.

**Comment by RiseT** [comment]
No hurry. Take the time necessary to find a longer-term solution.

**Comment by greyson-signal** [comment]
I believe this all got fixed during the note-to-self changes. (Note that at the time of writing there's currently a desktop bug with sending disappearing messages to yourself, but a fix for that should be rolling out).
