### ISSUE TITLE
[4.24.1] Missing translation for disappearing message notification.

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8003]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Thanks for the new fresh look Signal devs. Think it looks good. Just one minor thing I've noticed is that the translation for the disappearing message notification is missing. As can be seen in the screenshot the time indication itself is translated correctly e.g. 1 minute or off is translated however the leading string is not. 

### Steps to reproduce
- Set disappearing message.
- Check the notification message.

**Actual result:** Leading string for disappearing message is always in English.
**Expected result:** Leading string for disappearing message is in the selected language. 

### Screenshots

![screenshot](https://user-images.githubusercontent.com/25846829/42938023-32a262fc-8b51-11e8-88c0-ca863eb36b2b.png)

### Device info

**Device:** Samsung S5
**Android version:** 6.0.1
**Signal version:** 4.24.1

### Link to debug log

n.a.

**Comment by RiseT** [comment]
That's not a bug. It's just that this string hadn't been translated by the translators of that language (Dutch?) at the time the devs pulled the translations from Transifex.

**Comment by greyson-signal** [comment]
Yep, we changed the strings here, so there will be delay until we get them, but we should have more coverage before this hits production. I'll also be pulling in strings regularly as we make adjustments throughout the beta. Thanks!
