### ISSUE TITLE
[4.24.1] If your reply to a message, you can't dismiss the preview

### ISSUE THREAD

**Issue by rainerzufall** [signalapp/Signal-Android#8006]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If your reply to a message, you can't dismiss the preview

### Steps to reproduce
- select a message
- press reply button

**Actual result:** If your reply to a message, you can't dismiss the preview
**Expected result:** If your reply to a message, you should be able to dismiss the preview

### Screenshots
![screenshot_20180719-184327](https://user-images.githubusercontent.com/12666598/42958342-9a00e1b0-8b85-11e8-8721-d95f4b664e5e.png)

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.24.1

### Link to debug log
not relevant

**Comment by greyson-signal** [comment]
Ah yes I noticed this myself. I'll get this fixed soon, thanks!
