### ISSUE TITLE
[Feature Request] Display the Local Time for the people being messaged to

### ISSUE THREAD

**Issue by WNYmathGuy** [signalapp/Signal-Android#8007]
I'm very appreciative of the app and what it represents.

While using it to talk with my children who are in various time zones, I rarely think first about what time it is for them. I just begin writing whatever I think is important. Maybe it could wait till they wake up but I don't think they're sleeping because I'm not.

I know this is a difficult feature to do right because there are so many ways to do it. I have peoples location in my contacts list that the app pulls from, but that would mean Signal would have to do a lookup on the person by the city, state, zip each time it opens the conversation. That would be wrong if they were traveling. I can't ask my app to ask their app what time it is there (at least I don't think it can). If the person does use Signal, the app could just always look at the time zone the person is in and display it on the other app's messages whenever they're in different timezones, unless a conversant is trying to hide that information from others. 

If you could pull it off, there are so many cool ways to display that piece of info. A simple am/pm clock, a red background during typical sleeping hours, a sun to moon icon representing the angle of the sun for the other person. 

A catchy item like this may get my iPhone addicted daughter to try Signal instead of whatever crap she's using now.

**Comment by greyson-signal** [comment]
Thank you for the suggestion, but as specified in [our guidelines]( https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports) (and bug template), we don't take feature requests via github. Please check out the [forum](https://community.signalusers.org/c/feature-requests/android-feature-requests) for that. Thanks!
