### ISSUE TITLE
Quoting a picture will add another instance of it in shared media

### ISSUE THREAD

**Issue by schmeat** [signalapp/Signal-Android#8009]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time a picture is quoted, a new instance of that picture is created in the shared media section

### Steps to reproduce
- Send a picture
- quote it x amount of times
- click on conversation profile page, and observe the picture appear x + 1 times.

**Actual result:** Shared media adds a new instance of the picture every time it is quoted
**Expected result:** picture should only appear once

### Screenshots

![screenshot_20180719-193728](https://user-images.githubusercontent.com/1139817/42975794-39ce12fc-8b8c-11e8-8218-d28b65941fd4.jpg)
![screenshot_20180719-193752](https://user-images.githubusercontent.com/1139817/42975920-eb7d175a-8b8c-11e8-957e-288715e02cfd.jpg)

### Device info
Device : OnePlus ONEPLUS A6003 (OnePlus6) 
Android : 8.1.0 (1807130046, ONEPLUS A6003_22_180713) 
Memory : 21M (14.91% free, 512M max)
 Memclass: 256 OS 
Host : ubuntu-120 
App : Signal 4.24.1

### Link to debug log
https://debuglogs.org/d1ec73d0fd54b4848bcc838d262f0f1cfe1377317819adabe31229e32a855e66

**Comment by amitkot** [comment]
Reproduces for me as well:

Device  : OnePlus ONEPLUS A6003 (OnePlus6)
Android : 9 (1810252315, ONEPLUS A6003_22_181026)
Memory  : 45M (41.19% free, 512M max)
Memclass: 256
OS Host : ubuntu-14
App     : Signal 4.30.8
