### ISSUE TITLE
Sticker crashed Signal and deleted all messages

### ISSUE THREAD

**Issue by circledot** [signalapp/Signal-Android#8012]
Am not impressed. I went to send a "Happy Birthday" sticker and Signal instantly bombed out. The sticker was not received by the recipient, presumably Signal crashed before it could send. A bug report dialog came up, which I sent (without info).

ALL messages, including SMS were deleted. After a few hours my list of Signal contacts was re-populated but still no messages. And no pure sms messages, presumably they are all stored in the same file(s).

Backup was not enabled because, a) my microsd card isn't working, and b) I wanted backups to go to internal storage, which doesn't seem an option.

**Comment by johanw666** [comment]
For the record, with Signal 4.23.0 and later backups ONLY go to the internal memory. That this is called "sd card" is historical from the days from Android 1 and 2 when many devices didn't even have internal memory besiddes the system partition and a card was the only option. Now we have to live with the confusing terms "internal sd card" and "externa; sd card".

**Comment by greyson-signal** [comment]
@circledot This sounds bizarre and rather catastrophic. There's no code path where we would delete all of your messages and all of your contacts. 

Can I ask:

- Were you prompted to re-register after this crash?
- What version of Signal are you running?
- What device and OS are you running?
- Are you rooted, and if so, are you running any interesting rooted tools? (like Xposed)

**Comment by circledot** [comment]
@greyson-signal 

I was not prompted to re-register, it simply came up with an empty list of contacts. When my list of contacts re-appeared, all the messages for those contacts were gone.

I am running version 4.23.4 on android kitkat. Not rooted, therefore not Xposed.

**Comment by circledot** [comment]
My sms non-Signal contacts, they are not showing at all.

**Comment by circledot** [comment]
Btw, messaging my usual contacts comes up with "Bad encrypted message", until I message them, upon which normal conversations continue.

**Comment by Dyras** [comment]
Is your SD card by any chance like really full? So full that the message maybe didn't fit on the card at all?

**Comment by circledot** [comment]
I never used my sd card for a very long time because it's no longer working

**Comment by circledot** [comment]
also, one of my contacts messaged me before my contact list was re-populated.. when my contact list was re-populated, I had two entries for that person in my list

**Comment by jalan** [comment]
This just happened to me. I sent a message to a Signal group and ended up back on the start screen with all conversations, including SMS, deleted. My contacts list was gone too but momentarily repopulated.

 - I was not prompted to re-register
 - Signal 4.23.4
 - stock Pixel with Android 8.1.0
 - plenty of free storage, about 16 GB

**Comment by jalan** [comment]
[debug log](https://debuglogs.org/338ea095fb45bb33e2b16d4b614dff88b8390f80f08767e2f6691a45e33c4113)

I'm not sure, but I think the first timestamp in that log is from after the issue occurred. If so, is there a way to see previous logs?

**Comment by greyson-signal** [comment]
Not really sure what to do with this. Already investigated if there were any code paths that could cause this and came up empty. Without a debug log that captures the crash, I can only guess it's some odd SqlCipher corruption issue. Thankfully we haven't received any other reports. I'm going to close this for now, but please re-open it if it ever happens again. A change has since been merged that keeps longer logs, so we'll have a better chance of catching it. Thanks!
