### ISSUE TITLE
[4.24.1] The new feature "contact sharing" does not work correctly: the contact's name is not copied to the new contact name field

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#8016]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing a "contact" (name and number), the info is sent but at the recipient's side when clicking only the number is setup in the contact app. In other words: the name is missing!

### Steps to reproduce
At sender's side:
- select a recipient contact A to sent Signal message to
- click attachment
- select a contact B from your local contact list (via your contact app, which opens)
- sent the contact share to contact A

At recipients's A side:
- the signal message comes with the name and phone number (= contact share B)
- when clicking to add this to your contacts, only the number is copied, not the name.

**Actual result:**
- when clicking to add this to your contacts, only the number is copied, not the name.

**Expected result:**
-  when clicking to add this to your contacts, only the number is copied, not the name.

### Device info

**Signal version:** 4.24.1
between these three devices:
* HUAWEI Y6 2018 (Android 8.0.0)
* HUAWEI P8 LITE 2017 (Android 7.0)
* HUAWEI P8 LITE 2015 (Android 7.0)

**Comment by RiseT** [comment]
"Picked what we thought was the lesser of two evils here. If we give a name to the system, and the user picks “New Contact”, then it’ll populate the name. However, if they choose an existing contact, it’ll replace the name. We figured a lot of people might not notice that, and thought it’d be better to not set it at all rather than accidentally replace a name."

https://community.signalusers.org/t/sharing-contacts-potential-bugs/3462

**Comment by Wikinaut** [comment]
@RiseT Uh, say what? This is a super show stopper.

**Comment by Wikinaut** [comment]
@RiseT pls. reopen, if you want to keep that.
