### ISSUE TITLE
Re-sending SMS via different SIM causes endless permission dialog pop-ups

### ISSUE THREAD

**Issue by quixotique** [signalapp/Signal-Android#8017]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Re-sending an SMS message via different carrier (dual SIM phone) produces endless loop of "Sending SMS messages" permission pop-up dialogs.  The conversation thread had already been conducted via both SIMs at various times (ie, from two different self phone numbers) with no problems.

### Steps to reproduce
- receive a SMS message from other party (international) via SIM 1
- reply to the received message (unsecured SMS)
- message fails to send (eg, because carrier 1 account is down to zero balance)
- Signal displays the subtitle "Not delivered from <carrier 1 name>" "Tap for details"
- switch the phone to use SIM 2, which does have international SMS service
- tap on the failed message to bring up the "Message details" screen
- press the blue "RESEND" button
- up pops the "Sending SMS messages" permission dialog: "Signal is sending a large number of SMS messages.  Do you want to allow this app to continue sending messages?"
- press ALLOW, dialog disappears and pops up again
- repeat previous step ad infinitum
- press DENY and message remains in "Resending..." mode, eventually times out with send failure

**Actual result:** Message cannot be sent
**Expected result:** Message should be re-sent successfully

### Screenshots

![screenshot_20180721-135924](https://user-images.githubusercontent.com/1477470/43032350-9d7d17ae-8cf3-11e8-9015-0cd055c5b907.png)

### Device info

**Device:** Lenovo Moto Z2 Play (XT1710-09) (N.b. relatively modern dual-SIM device)
**Android version:** 8.0.0 (OPSS27.76-12-25-3)
**Signal version:** 4.23.4

### Link to debug log

https://debuglogs.org/c1608e2deef275424a9c3e96b485126874f15ebe504c879970d27cba6b02a8a8

**Comment by quixotique** [comment]
More information.  This bug does not have anything to do with international calls.  It only relates to dual SIM Android phones.  In a conversation that has been conducted insecurely (SMS only) on SIM 1, if an SMS message is ever sent using SIM 2 (because SIM 1 is disabled), then switching back to SIM 1 (by enabling it and disabling SIM 2) causes this endless cycle of pop-ups.  So it means that from that point forward, the conversation can only be conducted using SIM 2.

**Comment by cunio** [comment]
I have seen this today on Xiaomi MI 5 with MIUI 10 (8.7.19)..

**Comment by haffenloher** [comment]
> So it means that from that point forward, the conversation can only be conducted using SIM 2.

Is that still the case if you try to explicitly send a message from SIM 1 by long-pressing Signal's send button?
