### ISSUE TITLE
[BUG or FEATURE] Enter key/ Emoji button

### ISSUE THREAD

**Issue by Woodzrul** [signalapp/Signal-Android#8019]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Enter/ emoji button on keyboard not consistent throughout Signal app.

### Steps to reproduce
Settings -> Chats and media -> 
Use system emoji = Disabled

The enter key is shown on the keyboard when composing a text message. 

Settings -> Chats and media -> 
Use system emoji = Enabled

The emoji key is shown on the keyboard when composing a text message

**Actual result:** As mentioned above.

**Expected result:** The enter key should be the primary. Others SMS apps have this process in place.

### Device info
**Device:** OnePlus 2
**Android version:** 7.1.2 (AOSP Keyboard)
**Signal version:** 4.24.2

**Comment by greyson-signal** [comment]
Hmm, interesting. This doesn't seem to be consistent across the various keyboards. I don't get this behavior when using Gboard, for example. I'm guessing it's just a flag we have to set somewhere though. Open to PR's.

**Comment by Woodzrul** [comment]
Do you require anything from myself to help troubleshoot?

ROM: LineageOS 14.1
Version:  7.1.2
Keyboard:  com.android.input method.latin

Would be really cool if this can be resolved.

Thanks

**Comment by greyson-signal** [comment]
@Woodzrul Looks like that information would be all someone would need. Thanks!

**Comment by Woodzrul** [comment]
@greyson-signal I managed to resolve the issue for myself by removing the below code from ComposeText.java.

    if (useSystemEmoji) {
      inputType = (inputType & ~InputType.TYPE_MASK_VARIATION) | InputType.TYPE_TEXT_VARIATION_SHORT_MESSAGE;
    }

Not sure if this is correct, but thought I'd pass it by you.

**Comment by roberth** [comment]
Possibly related: when pressing the `Enter` key on an external keyboard (USB OTG or probably also bluetooth), the message is not sent

**Comment by Mhowser** [comment]
I still have this problem. The enter key doesn't show up. I'm using OpenBoard from F-droid.

**Comment by UserX404** [comment]
![](https://i.imgur.com/pv4FXX1.png)![](https://i.imgur.com/5HRPXPA.png)

Just installed openboard but it works as expected. Just toggle the switch within signals conversation settings.

**Comment by Mhowser** [comment]
That worked, thanks.
