### ISSUE TITLE
Feature Request: import and export keys to file, Bluetooth, QR, and NFC

### ISSUE THREAD

**Issue by GIJack** [signalapp/Signal-Android#802]
more specificly I'd like to be able to import and export the private key, and public keys to files.

I'd also like to be able to import and export public keys via bluetooth, NFC, and QR code. Something like this:
https://play.google.com/store/apps/details?id=org.sufficientlysecure.keychain

The do key management pretty well, for GPG. (sadly no one writes apps that use their wonderful app, but seriously, best key management app there is.) its also open source, I wonder if you could steal some code from them, and use their key management interface.

Reasons I need this
1. new phone, I need to securely wipe the old key, export the old key to a file, and then re-import it.
2. Lost phone, in case I loose my phone, I can reuse the same gpg key.
3. Device immaterial - once I have a back up file of the private key, I can store that on an encrypted parition, or container, and bounce that around as I see fit between devices, PCs, internet storage, etc.. I can then bring it back when I need it. I can also switch between phones at will.

For public keys.
1. in addition to reasons 1-3, having a good back up of my friend's public keys, I can easily re-import them, and share them with other people as needed, to make the fewest amounts of key exchanges needed.
2. I can set up phones for people with all the public keys they need. just load them up, and go.

This would just make an already good app fucking awesome.

**Comment by landry314** [comment]
does the export plaintext option export private keys in plaintext? i would be shocked. does it have anything to do with the keys or just the texts? should i just move the files in /data/data manually to export my keys?

**Comment by sedrubal** [comment]
@landry314 no the key will not be exported in plaintext on plaintext backup.

:+1: For the feature to export and import the private key and public keys

**Comment by micressor** [comment]
+1 with this!

**Comment by moxie0** [comment]
@micressor Please be mindful of the contributing guidelines: 

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

You can use the built-in reaction emoji if you'd like to signal support for something.

**Comment by micressor** [comment]
@moxie0 I am sorry for the e-mail spam. I have now read the [CONTRIBUTING.md](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues) and donated via Bithub. From now on, I use emoji to support a feature. Thanks for the friendly note.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
