### ISSUE TITLE
Map old conversation colors to similar new color

### ISSUE THREAD

**Issue by elya5** [signalapp/Signal-Android#8021]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The current beta version has the new message design (which is great) but it also changed the colors of the messages. I think it would be great if the old color for a contact would be mapped to a new one which is similar. That way, contacts don't suddenly lose their "color identity". It's especially noticeable in group conversations.

### Device info
**Android version:** 8.0.0
**Signal version:** 4.24.2

**Comment by greyson-signal** [comment]
Yeah, so the intended behavior is that we move to a similar color, but it's worth noting that we don't always have a similar color to map to when going from the old to new palette. That being said, I'm worried that there may be a bug in that behavior as well, so I'm going to take a look into this.
