### ISSUE TITLE
Photo drawing moves when switchen between portrait and lanscape mode

### ISSUE THREAD

**Issue by elya5** [signalapp/Signal-Android#8022]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I take picture and draw on it in landscape, the drawing moves its position when the phone is turned back into portrait mode.

### Steps to reproduce
- take a picture with signals built-in camera
- click the edit button
- turn your phone into landscape
- start to draw
- turn back into portrait

**Actual result:** Drawing moves (a part is even outside of the visible area)
**Expected result:** Drawing should stay at the same position

### Device info

**Device:** Motorola Moto G6
**Android version:** 8.0.0
**Signal version:** 4.24.2

**Comment by greyson-signal** [comment]
Yeah, unfortunately a known long-standing issue :( Thanks for the report!

**Comment by greyson-signal** [comment]
Fixed this during the multi-send changes.
