### ISSUE TITLE
Tapping chat bubble from conversation settings opens blank conversation

### ISSUE THREAD

**Issue by sweeper3000** [signalapp/Signal-Android#8026]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I go to a contact's `Conversation Settings`, scroll to the `About` section and tap the chat bubble, it opens a completely blank conversation, but if I exit the conversation and re-enter it, the messages show as normal.

### Steps to reproduce
- Open a conversation
- Go to `Conversation Settings` (3 dots > Conversation Settings)
- Scroll to the `About` section
- Tap the chat bubble
- See blank screen with no messages

**Actual result:** I see a blank screen with no messages.
**Expected result:** I should see my messages as normal.
### Screenshots

![blankmessages](https://user-images.githubusercontent.com/13157680/43050857-ba7eae22-8ddd-11e8-8f1d-43ab08585e92.jpg)

### Device info

**Device:** Google Pixel
**Android version:** 8.1.0
**Signal version:** 4.23.4

### Link to debug log

https://debuglogs.org/c54e285f8b9fcf4943c747e3edbbc2bc4e545781a634147bed0de66e8e9753a0

**Comment by minnmann** [comment]
Can confirm behaviour for 
**Device:** Motorola Moto G5
**Android version**: 7.0
**Signal version**: 4.24.2
