### ISSUE TITLE
PRs Awaiting Review

### ISSUE THREAD

**Issue by GustavMarwin** [signalapp/Signal-Android#8030]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When possible, could we get a team-member to review the following issues:

https://github.com/signalapp/Signal-Android/issues/6644
https://github.com/signalapp/Signal-Android/issues/6732

Those have been closed without being solved, yet a PR that would fix them is awaiting review.

Thank you,

**Comment by Socob** [comment]
Related: #7638

**Comment by greyson-signal** [comment]
I appreciate that you want to get certain PR's merged, but opening a new issue is not the way to do that. Please read our [bug reporting guidelines](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports). If there's a PR you really want reviewed, please comment on it directly.

**Comment by GustavMarwin** [comment]
Hi Greyson - You'll notice that multiple people have tried that approach, and it has been ignored for months, although a fix has been created. Would you happen to know why that is? Thank you.

**Comment by greyson-signal** [comment]
@GustavMarwin I don't know what PR's you're referring to. I looked at the issues, and there are some PR's referenced, but there's also comments saying that those fixes aren't reliable, or the PR's have been closed by Moxie for valid reasons. Feel free to link the PR here I guess.

**Comment by GustavMarwin** [comment]
@greyson-signal : maybe this will help clarify?
https://github.com/signalapp/libsignal-service-java/pull/53#issuecomment-404507178

**Comment by greyson-signal** [comment]
@GustavMarwin It looks to me as if the PR's linked there have already been reviewed, and valid reasons have been provided for their rejection.

**Comment by Socob** [comment]
@greyson-signal This is not about the PRs linked in that comment, but about the linked PR itself (signalapp/libsignal-service-java#53) as well as an independent, mostly-identical one (signalapp/libsignal-service-java#54). Both of these are still open, there has been no indication that they were rejected and nobody seems to know why they are not simply accepted. Both have been tested for a long time now without any issues.
