### ISSUE TITLE
[4.24.2] - All Messages showing as Bold even after they are viewed

### ISSUE THREAD

**Issue by MattR658** [signalapp/Signal-Android#8033]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the 4.24.2 BETA, all messages are showing as **BOLD** so I cannot tell which messages have been read or not quickly. This behavior is new to 4.24.2

### Steps to reproduce
- Open Signal
- View all messages
- Open individual message
- Go back to view all messages

**Actual result:** The message that has been read is still in **BOLD**
**Expected result:** After reading the message, it should no longer be **BOLD** when going back and looking at all messages.

### Device info

**Device:** OnePlus ONEPLUS A3000
**Android version:** 8.0.0
**Signal version:** 4.24.2

### Link to debug log

https://debuglogs.org/0b173bc696af7c29b1e1b2b079f2644316831cacdd296d3f6e5b53bbd17ebfb4

**Comment by greyson-signal** [comment]
Screenshots could help a lot here. If you're referring to the contact name, it's always bold now, regardless of read status. We have the unread indicator and stuff to indicate unread messages. Also, I just pushed 6a1fd8b1c6811ff1ecf0d84ac0ae70336cf27c19 which will, in fact, bold some more text so it's even more clear which conversations are unread. Please re-open if I've misinterpreted your report. Thanks!
