### ISSUE TITLE
Intermittent delay when sending SMS messages

### ISSUE THREAD

**Issue by cwillhelm** [signalapp/Signal-Android#8037]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a SMS message, the ellipses (...) display the animation for much longer than regular Signal messages. On top of that, it seems the actual SMS message is delayed in sending, rather than Signal just displaying a sending animation. I don't think this is a network error because I have tested other messaging (including SMS) apps and they send instantly. 

Additionally, the error seems to happen irrespective of my device location.

### Steps to reproduce
Generally, the extended animation can last up to 3 minutes, and seems to happen intermittently. This seems to happen more frequently when I stay within a single conversation window, sending and receiving multiple SMS messages within the same window over a few minutes (without turning the screen off).

This never happens with Signal messages to other Signal users.

I am on the Bell Canada network, but I do not believe this is the issue.

**Actual result:** Intermittent delay when sending SMS.
**Expected result:** Animation should display the check mark near instantly after sending, as opposed to being delayed up to 3 minutes. 

### Device info

**Device:** Motorola Z2 Play 
**Android version:** 7.1.1
**Signal version:** 4.23.4

**Comment by 2-4601** [comment]
Could you try to [capture a debug log](https://support.signal.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-from-Signal-Android-) next time this happens?

**Comment by greyson-signal** [comment]
+1 to providing a log.

Also, just to be clear, it's not just the the pending animation is sitting around for too long -- the actual message isn't being sent out, yes?

**Comment by cwillhelm** [comment]
It appears the actual message isn't sending, I can't tell if it's delay on either end (I.e me or the recipient). I can confirm this doesn't happen with other SMS apps though. 


https://debuglogs.org/c19768c2e55cdfe1edb0599590093d4794bdae3b332f33d3d523377ab4650c7f

**Comment by ad-m** [comment]
I suppose that I have the same issue. In the case of sending a message, the message flag of the message is still indicating the sending of messages. Sometimes it hangs up and then some random text messages are marked as send sucesfully. I'm not sure if messages are always sent, but I am sure that sometime messages was marked as pending, but it was delivered.

Deleting application data and restoring messages from copies does not solve the problem.

I have huge amounts of messages on my phone. Only SMSs. 30,000 +.

https://debuglogs.org/349800957db1c563186bd9c93706e13f22aee098e45e0d6af4605b652968a66b

**Comment by cwillhelm** [comment]
I have additional debug logs to provide if this helps the cause. This was from 4 separate instances of this happening over the past couple days.

https://debuglogs.org/11826bf685ae9a2f464836d658a4b430ed7f67e26e993a9ca182381f278374aa

https://debuglogs.org/340f4e5da25c7e0e154a3219b6ec727bd6c64ffc236daffb90f6cc15c3f7bb60

https://debuglogs.org/8693a2cbf2e30b593d4245dd8c97e054d91efb7c90a2c5286d423d30db32c1f3

https://debuglogs.org/477b152aaed0d4abb30dba99c7016699b055c3e02de4e6d29fc9927d65145e94

**Comment by ad-m** [comment]
I would like to point out that I use only SMS, I do not use Signal messages at all. That  bug occurs only for SMS for me.
