### ISSUE TITLE
missing icon badge notification and status bar notification  

### ISSUE THREAD

**Issue by cunio** [signalapp/Signal-Android#8038]
### Bug description
I'm not getting icon badge notification and status bar notification  

### Steps to reproduce
- install Signal on Xiaomi Mi5 with MIUI 10 (8.7.19)
- set all the settings described in https://support.signal.org/hc/en-us/articles/115005547088-Why-do-I-only-see-new-messages-when-I-open-Signal-Android-
- receive some Signal or SMS message

**Actual result:** 
No Signal icon badge notification (number of received messages),
No status bar notification Signal icon.
_Sometimes_ I get diode notification and sound/vibration when receiving Signal/SMS message.
 
**Expected result:** 
When new Signal/SMS/MMS message arrives:
LED is blinking using colour set in Signal settings,
Sound/vibration notification is working,
Signal icon badge is used to give informatoin about number of unread messages
Signal icon appears in status bar etc. 
  

### Device info

**Device:**  Xiaomi Mi5 
**Android version:** 8.0, MIUI 10 (8.7.19)
**Signal version:** 4.23.4

### Link to debug log
https://debuglogs.org/be106c281d6f6ee4cc6f264407e21331e75ff54c6ed90c2b1e2f577bfc0de5c4

**Comment by Castiel91** [comment]
I've got the same problem for a while now.
Sometimes I get the notification badges (using Smart Launcher), but that's unlikely. Notifications in status bar never works, vibration is to low to recognize (can't change that).

Device info:
Umidigi S2 Pro
Android 7.0
Signal Version 4.24.5

Debug log:
https://debuglogs.org/dfe325390fb11b72ca6139419e1a067036c7e6e79863e294679321bd66c71476

**Comment by levjoy** [comment]
Same problem for me. Notifications were working until yesterday they stopped. I do hear notification sounds, but no visual notifications in the status bar or on the app icon. 

Device info: 
Pixel 2 XL
Android 9.0
Signal version 4.25.6

**Comment by greyson-signal** [comment]
@levjoy What do Signal's system notification settings look like?You can find them by going to:

System Settings > Apps & notifications > Signal > Notifications

Sounds like the priority of the relevant message channel may be too low?

**Comment by levjoy** [comment]
Thanks, I think it may have had something to do with Do Not Disturb, which was blocking visual notifications but not audio notifications!

**Comment by greyson-signal** [comment]
I think a lot of these problems should be solved now that we're using notification channels in Android 8.0+ in Signal 4.25.x. Please re-open if there's still problems.

**Comment by LinuxOnTheDesktop** [comment]
Please re-open. For, on Android 13 and Signal 7.28.4 - and using 'Nova Launcher' - WhatsApp shows 'badges' (number of unread messages) but Signal does not (even though, so far as I can tell, I have enabled every requisite setting).
