### ISSUE TITLE
Signal crashes on many different views

### ISSUE THREAD

**Issue by zanedb** [signalapp/Signal-Android#8044]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Occasionally, Signal will simply crash when opening messages. Most recently, a group chat I'm in crashes on open, so I cannot view any messages.

### Steps to reproduce
- Open Signal
- Open a message view
- Crash (on certain conversations)

**Actual result:** 
It crashes, and should not
**Expected result:** 
It should not crash

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.24.4

### Link to debug log

I'm unable to capture a debug log, as the app crashes there too:
![error](https://www.dropbox.com/s/zmw6gxcdaf3mk8t/20180727_135620.jpg?dl=1)
https://www.dropbox.com/s/zmw6gxcdaf3mk8t/20180727_135620.jpg?dl=1

I'm sorry I can't provide more information here, but please ask me with any questions. This is a critical bug.

**Comment by johanw666** [comment]
Often this is caused by an incorrect state of the database. The standard trick to try is opening the screen in airplane mode and see if that works.

**Comment by zanedb** [comment]
Yup, that fixed it. Still seems to be a critical issue (that the app should hopefully resolve itself).
