### ISSUE TITLE
Reference counted images

### ISSUE THREAD

**Issue by kiplingw** [signalapp/Signal-Android#8045]
I'm not sure if this is implemented already, but this is a useful optimization tip. It's not unusual for a sender to send the same image to multiple recipients. In that situation if Signal stores multiple copies of the image in each distinct message thread, it wastes a lot of space. The way around this would be to store images once and have them reference counted. Each time an image in a message thread is deleted, its unreferenced. When it hits zero its actually deleted from storage.

**Comment by moxie0** [comment]
Thanks for the suggestion @kiplingw, but we ask that folks posting here include the issue template and stick to the contributing guidelines. These types of feature requests and suggestions are super valuable, but we prefer that people post them to the forums. Thanks!
