### ISSUE TITLE
Receiving group Messages initialized by another signal user causes constant MMS failure messages

### ISSUE THREAD

**Issue by jtylers** [signalapp/Signal-Android#8051]
----------------------------------------

### Bug description
Receiving group Messages initialized by another signal user (with mixed signal/non-signal users) causes constant repeated MMS failure messages
### Steps to reproduce
- Initialize a group message with a group mixed with signal/non-signal users
- Non-signal and signal users respond to the group message

**Actual result:** 
Some of the signal users will receive an Error every 5-10 seconds in the person to chat (not the group chat): "Error downloading MMS message, tap to retry"

**Expected result:** 
Group messages should send and receive normally without spamming hundreds of error messages

### Device info

**Device:** LG G5 ls9927zf
**Android version:** 7.0
**Signal version:** 4.24.5

### Link to debug log
https://debuglogs.org/cb5ba1ea38e293972bf2594a0d6884b008fa3e860781a50b011a6a9f96c39405

**Comment by UserX404** [comment]
Hi
I noticed this behavior when a MMS comes in and i'm connected with wifi and the mobile connection is turned off.
After switching on the mobile internet the message comes in when pushing retry.

**Comment by SparroHawc** [comment]
This issue has been a problem for a long time now.  Any group conversation with non-Signal users that is any significant length has missing messages because of this bug.
