### ISSUE TITLE
The spinner is still displayed after registration failure

### ISSUE THREAD

**Issue by masonlouchart** [signalapp/Signal-Android#8052]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The spinner is still displayed when the registration failed (because of network connection error).

### Steps to reproduce
- try to register on an Android phone

**Actual result:** We're not registered and the spinner/loader is still displayed.
**Expected result:** We're not registered and the spinner/loader is not displayed anymore.

### Screenshots
![signal_registration](https://user-images.githubusercontent.com/2325091/43388018-54b9a5cc-93e8-11e8-9b16-e0c47fe90179.png)

### Device info
**Device:** LG Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.23.4

### Link to debug log
I can't produce logs because I can't even enter into the app. The registration fails.

I guess turn the `setIndeterminateProgressMode ` on the button to `false` in the _catch_ statement (L490) could do the job.

https://github.com/signalapp/Signal-Android/blob/7237e919bee3f439a21c49281b7cf7fb387314a8/src/org/thoughtcrime/securesms/RegistrationActivity.java#L463-L504

**Comment by audebruin** [comment]
I have the same problem after unsuccessfully register due to receiving multiple 5-digit verification codes in stead of a 6-digit.

Device: TA-1053 Nokia 5
Android version: 8.1.0
Signal version: 4.23.4
Country: NL

**Comment by masonlouchart** [comment]
The button is still clickable. It's simply a UI issue.

**Comment by greyson-signal** [comment]
Fixed in 4.25. Thank you @masonlouchart!
