### ISSUE TITLE
facepalm emoji decoded as facepalm + mars-symbol

### ISSUE THREAD

**Issue by deeglaze** [signalapp/Signal-Android#8055]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A message sent from the iPhone with a facepalm emoji rendered in signal as facepalm mars-symbol. I had initially seen it as a venus symbol and it led to a very tense situation of me thinking this salesperson was being misogynistic to my lender or me (both women) because faxes are unreliable.

### Steps to reproduce
- Send the text displayed in the screenshotted screenshot from an iPhone to an Android phone with signal.
- View the text from the Pixel to see that the facepalm emoji gets expanded to facepalm + mars-symbol.

**Expected result:** The message in signal should only display a facepalm, not a facepalm + mars-symbol

I don't have the hardware to try to reproduce this myself. I can only show an instance of it happening with my screenshot.

Weirder, I copied the text of his message with facepalm + mars-symbol and sent it back to him, and his chat app still just showed facepalm.

### Screenshots
https://github.com/deeglaze/bug-report-assets/blob/default/signal_emoji_screenshot.png?raw=true

Please forgive the incorrect reading of the mars symbol as "female emoji". I redacted an email address from the screenshot.

### Device info
**Device:** Pixel XL
**Android version:** 9, build number PPP4.180612.004 (I'm in the Android P beta, if this is relevant)
**Signal version:** 4.23.4

### Link to debug log
https://debuglogs.org/5922ca76d8c597079e157dc653eb09a6221d00ea6d4d8565a63d807dc836114d

**Comment by greyson-signal** [comment]
Ok, so apparently this is a larger issue where our emoji set is just out of date. Specifically, we don't have any of the emoji for the different skin tones (see #3556). The "man facepalming" that was sent to you wasn't using the "default yellow" skintone, so when we received it, we split it apart into it's various points.

Updating our emoji set is a non-trivial task. One that needs to be done for sure, but not something that'll happen in the next release. In the meantime, if you're having emoji issues, you can always switch to your system default emoji in Settings >Chats and media > Use system emoji. Sorry about that!

**Comment by deeglaze** [comment]
Confirmed that when I switched to system emoji that the problem message renders as I expect. Good hunting :)

**Comment by greyson-signal** [comment]
We did a pretty major update to our emoji set a few months ago, so this should be resolved.
