### ISSUE TITLE
Provides an alternative to QR code to pair devices

### ISSUE THREAD

**Issue by alexgarel** [signalapp/Signal-Android#8056]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

This is a shameless revival of #5153 gone due to spring cleanup.

I have a phone where the camera is broken (auto-focus lost forever) but  I keep this phone because of ecology concerns. As I want to use the linux desktop client, the only way I can pair with my phone is through a QR that I have no mean to scan (camera won't focus).

### Steps to reproduce

- have a phone with broken camera (or emulate with tape on camera)

**Actual result:** no way to pair the device
**Expected result:** an alternative should be provided like a verification code (even if it's a long code, the case is rare enough to have a painful procedure).

### Device info

On the desktop side:

ubuntu 18.04
flatpak 0.99.3
Signal desktop 1.14.4 (via flathub)

On the phone side:

**Device:** Samsung SM-G350
**Android version:** 4.2.2
**Signal version:** 4.23.4

**Comment by greyson-signal** [comment]
Similar enough to #7967
