### ISSUE TITLE
Signal probably crashed

### ISSUE THREAD

**Issue by publicmoneypubliccode** [signalapp/Signal-Android#8060]
Hey, sry for not using the issue draft, I cant see it while I'm on mobile.

I just called somebody via Signal Audio, and I think that Signal crashed afterwards. The call ended after pressing the end button, but then there was a window which appears after an application crash. I clicked on the display the same moment so I couldnt see the applications name.

I attached a log. If there is nothing in there: I'm sorry.

Im using a Galaxy S7 Herolte with lineage OS 15, no GAPPS.

https://debuglogs.org/5d8f8018ebc88bd79ab3bd956cccd310a5ac4eba8659782296b4ca7751334d25

Thank you for your help

**Comment by greyson-signal** [comment]
Ah yes there was a crash, thank you for the report!

**Comment by elimisteve** [comment]
Was this fixed? Thanks.

**Comment by elimisteve** [comment]
Okay thanks.
