### ISSUE TITLE
Flipped image when scrolling out really fast

### ISSUE THREAD

**Issue by He-Ro** [signalapp/Signal-Android#8061]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
So this is a weird issue.
Some information: There are several ways to scroll an image in the image viewer, one can use two fingers and do the pinch zoom, but you can also do a tap and hold on the image and then slide your finger up and down. Sliding your finger up zooms out and sliding it down zooms in.

Using this tap and hold style zoom sometimes leads to the image being "inverted", it is actually a point reflection. For this I need to fling my finger up quite fast, please have a look at the video.

### Steps to reproduce
- send or receive an image
- click on the image
- tap and hold on the image and fling your finger up really fast (this does not work every time, sometimes you are not fast enough, so try this a couple of times)

**Actual result:** The image is point reflected
**Expected result:** The image should not be point reflected and zoomed out maximally.
### Screenshots

**VIDEO:** https://ptpb.pw/ZGjw.mp4

### Device info

**Device:** Sony Xperia Z5 Compact (E5823)
**Android version:** 7.1.1
**Signal version:** 4.23.4
 (also happens on Redmi 4, Android version 6.0.1, same Signal version)
### Link to debug log
https://debuglogs.org/5174ee67b7a4723a93a56a6571b92370f30820511b1d93930043416af2597afd

**Comment by greyson-signal** [comment]
Ahhh yeah that's kind of funny. Also, just for clarification, I believe the "one finger zoom" mode is activated after a double-tap, not a long-press.

**Comment by He-Ro** [comment]
Yeah, a double tap, but the second tap is really a long press.

**Comment by FeuRenard** [comment]
This seems to be a known issue with `PhotoView` or the Android framework.
https://github.com/chrisbanes/PhotoView/issues/434
https://github.com/chrisbanes/PhotoView/issues/526

**Comment by xd720p** [comment]
@He-Ro @greyson-signal @FeuRenard here is the [pull request](https://github.com/chrisbanes/PhotoView/pull/667) with the solution
