### ISSUE TITLE
Fingerprint access still enabled after deleting fingerprints from phone

### ISSUE THREAD

**Issue by avastar** [signalapp/Signal-Android#8066]
### Bug description
Unable to choose method to decrypt signal database. Fingerprint is set permanently if fingerprints are enabled on phone even if fingerprints are deleted from phone

### Steps to reproduce
- enable fingerprints
- decrypt signal database with fingerprint
- lock database
- delete fingerprints
- decrypt database

**Actual result:**
Database will only decrypt using fingerprints

**Expected result:**
Should be able to choose alternate method to decrypt database allowing for unique credentials for database

### Device info
**Android version:** 8.0.0
**Signal version:** 4.23.4

**Comment by johanw666** [comment]
Use a pattern or code to unlock the phone instead of a fingerprint scanner.

**Comment by tcely** [comment]
@johanw666 Unlocking the phone is not the issue. Unlocking the signal application should not depend on fingerprints exclusively.

It's freaking annoying to not be able to open signal when I have gloves on. I can work the keyboard just fine, but obviously I can't scan fingerprints through gloves.
