### ISSUE TITLE
Conversation color palette reduced to fewer colors

### ISSUE THREAD

**Issue by aibaraiduas** [signalapp/Signal-Android#8070]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal for Android 4.24 reduced the number of available conversation colors from 15 to 9 (compared to version 4.23.4).

I'm not sure if this is a bug or intentional (seems like an odd bug to have been introduced accidentally, but I can't see why you'd want to reduce the palette, especially with such similar colors). Either way, the color selection is now much too limiting, and should be restored. I should also add that two colors are *extremely* similar to another two, making the options effectively more limited: red and slightly-orangish-red; and teal and, uh, teal no. 2.

In individual conversations the color selection doesn't matter too much, but in group conversations it is really helpful to have different colors to quickly tell the members apart (especially if people's circle icons have both the same letter!). Now several conversations of mine have two or more people in it with the same color. 

### Steps to reproduce
- Go to conversation settings and then the color option

**Actual result:** 
Note there are only 9 options (of which two are very similar to another two).

**Expected result:**
15 color options being presented to choose from.

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.24.7

**Comment by giodamelio** [comment]
Looking back at the commit log, it looks like this happened during the recent "visual improvements" update, but [the commit](https://github.com/signalapp/Signal-Android/commit/24b062d8dde3d2bbcebc110400c95c9ffb649dc5#diff-70fdeba3134c79de10c4f05be0480cf2) gives no context other then "improve the look of message bubbles". I would argue that reducing the colors available does anything but.

I would really appreciate if we could have the old colors back, or even better allow us specify an arbitrary RGV hex code for a contact.

**Comment by greyson-signal** [comment]
This was an intentional choice, so not a bug, but feel free to start a discussion on [the forum](https://community.signalusers.org/). Color is definitely something we're thinking about. Thank you!

**Comment by jpleclerc** [comment]
My girlfriend uninstalled Signal from her phone because of that.

**Comment by Wolle980** [comment]
@jpleclerc : I was thinking about un-installation of SIGNAL too. It's annoying to be  helplessly at the mercy of developers, who have only sense for technical issues, but have no sense of visual impression :-(
But my work arround was to download Signal 4.23.4. APK, easy to find in internet. After perfoming a local backup of my conversations, uninstall of pale Signal and re-installing former version, it looks fine for me again. Now I keep an eye on further discussion.

**Comment by unsignedzero** [comment]
I don't understand how this is an improvement at all. The **worst** part about this is what we are users are **not** told of these losses and only find out when we are forced to install a new version. Coupled with the lack of import of older xml logs, I'll happily sit on an older version. 

Thank you for making this more insecure by forcing people to downgrade since you're clearing removing features without either telling users or providing a mitigation/recovery option.
