### ISSUE TITLE
Caller  stuck on dialing while the called person gets a missed call.

### ISSUE THREAD

**Issue by gpeddev** [signalapp/Signal-Android#8072]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When people call me through signal the caller doesn't hear the ring sound when its calling but keeps hearing the dialing sound.
My phone shows immediately a missed call.

ps1.I can call other people without problem
ps2. I guess this bug is different from this https://github.com/signalapp/Signal-Android/issues/7603
since the callers phone doesnt ring at all. It simple dials for ever
ps3. And its different from this https://github.com/signalapp/Signal-Android/issues/7090 since it shows the missed call immediately when the caller calls you. Doesnt wait for the caller to end it.
ps4.I updated through app store signal and it shows me 4.23.4. It doesnt show me the update to 4.24.7 while the latest version and the version of the caller is 4.24.7. 

### Steps to reproduce
- Somebody calls me.
- The caller keep hearing the dialing tone and i get a missed called

**Actual result:** The caller is stuck hearing the dialing sound and nothing happens. The receiver of the call sees a missed call
**Expected result:** Transist from dialing to ringing tone and if the call is answered start a conversation

### Device info

**Device:** Samsung Galaxy A3 (2016)
**Android version:** 7
**Signal version:** 4.23.4

### Link to debug log
This is the debug log that receive the call
https://debuglogs.org/e12f1cf21218eb59eeeaf657712feb9da3a57786e7888f372e11cd62882ac40b
This is the debug log of the caller
https://debuglogs.org/4ce610732adaa8c68ca8c7e30b393df0329237a6f9345b7d6de5b5f8132f65cc

**Comment by haffenloher** [comment]
> This is the debug log that receive the call
https://debuglogs.org/e12f1cf21218eb59eeeaf657712feb9da3a57786e7888f372e11cd62882ac40b
This is the debug log of the caller
https://debuglogs.org/4ce610732adaa8c68ca8c7e30b393df0329237a6f9345b7d6de5b5f8132f65cc

One of those logs ends at 21:00 while the other one starts at 22:02. Is it possible that one or both of the devices' clocks are off? Can you verify that both the time and the timezone are being set automatically on both devices?

**Comment by gpeddev** [comment]
@haffenloher yes time on both phones is set automatically. The phones are on different timezone so the clocks are fine.

**Comment by gpeddev** [comment]
1 month and 4 days and the problem still isnt solved. Is anyone working on it?

**Comment by greyson-signal** [comment]
If you're still experiencing the problem, please submit new debug logs for each device.

**Comment by dorakas** [comment]
same here. calls don't get established. it pings on the one phone and show notification on the other but never rings. if you click the notification it shows call screen but the call doesn't make it.

Pixel 3 log = https://debuglogs.org/d1a1312b64f6bed40d9da0fa5708409d67de1b3249a99c656df2273930acf05a

Nexus 6p log = https://debuglogs.org/0a87f3d14abb82052e7e312af2ee81aa97c1593dc029687c59ec1433b9c01ac8

**Comment by attila-lendvai** [comment]
i'm seeing this also, but the reason i'm writing is that it was very-very useful when Signal had a separate sound for "dialing" and "ringing". since a few months they have been merged into a general ringing sound, and i need to stare at the phone to see whether the called phone is actually ringing, or Signal is still trying to establish a connection.

please bring back the separate sound for the two states, and/or let me know whether i should open a new issue for this (i didn't find anything specifically about this).

**Comment by FedericoCeratto** [comment]
I'm seeing the same. It shows "dialing" never succeeds.

**Comment by mxr2-a11y** [comment]
Same situation here. Signal works fine when calling from A to B, but doesn't work properly when B tries to call A. It looks like Android version specific thing. Other phones working in the same network can dial each other numbers without any problems. 

**Caller A details**
HTC
Android 7
Latest signal

**Caller B details**
Android 9
Latest Signal
Xiaomi

**Comment by greyson-signal** [comment]
There's been a lot of technical changes over the past several months. Please include debuglogs if you experience this issue. Preferably from both phones, if possible. Thanks!

**Comment by attila-lendvai** [comment]
i'm still experiencing it, and i'm still badly missing the auditory differentiation between searching for the peer, and ringing the peer's phone, because the delay is regularly so long that the difference is relevant.

**Comment by alex-signal** [comment]
@attila-lendvai I'm sorry to ask but if this happens again and you can grab fresh logs from both your device and the callee's device I can forward them over to our callling team!

**Comment by cody-signal** [comment]
Try on 5.33 where we've integrated with the Android telecom system, and made some changes to how we ring. Please post an updated debuglog if you try with that version and still encounter problems.

**Comment by attila-lendvai** [comment]
i'm still wasting my time regularly to explain to my peers that my side only starts ringing when their side changes from "connecting" to "ringing", and that **there's no auditory feedback about this**, therefore they need to stare at the screen until it happens.

removing the submarine sound still baffles me. i can't even come up with a model of reality that justifies the decision.

and not switching to 'ringing' for 10+ seconds is a regular event.

**Comment by cody-signal** [comment]
@attila-lendvai can you provide an updated debuglog for you and the caller (if possible)?

I don't recall there being a searching sound, how long ago was this removed?

**Comment by attila-lendvai** [comment]
> @attila-lendvai can you provide an updated debuglog for you and the caller (if possible)?

i'll see what i can do. but all that is needed is a somewhat unstable network connection on the callee side, e.g. phone at the wifi boundary. the caller will hear immediately the ringing feedback sound, while the callee's phone is dead quiet.

> I don't recall there being a searching sound, how long ago was this removed?

apparently it was removed in 2019: https://github.com/signalapp/Signal-Android/issues/8633

the search keyword is `submarine`.

**Comment by attila-lendvai** [comment]
here i am years later, still baffled, and still wasting way too much of my time explaining to my non-geek peers WTF is going on, and that i'm not an asshole who regularly ignores their calls...

time for another round of evaluating alternatives.
