### ISSUE TITLE
Import SMS message is missing

### ISSUE THREAD

**Issue by dikiaap** [signalapp/Signal-Android#8075]
I'm using Signal v4.24.7.

Where is import message option? My ISP spamed me with a lot of promotion messages and I have collected many list of Alphabet numbers and manually to block them.  

I hope you bring back this feature and If anyone knows which version has this feature, I would downgrade to the old version.

**Comment by greyson-signal** [comment]
Are you referring to the "Import" option in the conversation list three-dot menu? If so, that option has been removed in favor of our encrypted backups that we offer. Encrypted backups can be enabled in Settings > Chats and media. We will not be bringing back the plaintext import option. 

Also, it's worth noting that if you do create an encrypted backup, we only offer the ability to import during registration. So if you wanted to restore from a backup, you'd have to either clear Signal's data in your system settings or do an uninstall/reinstall.

If you're referring to something else, then apologies for the confusion, and please re-open the ticket. Thank you!

**Comment by dikiaap** [comment]
Yes, it's plain text backup and that was in the three-dot menu.

Unfortunately, I don't have encrypted backup. I just have list like:

File: SignalPlaintextBackup.xml
```
<sms protocol="0" address="ISP Promo" date="1514739601000" body="Test" read="1" locked="0" />
<sms protocol="0" address="ISP Discount" date="1514739601000" body="Test" read="1" locked="0" />
...
```

**Comment by greyson-signal** [comment]
@dikiaap Yes, that option has been removed. Plaintext exports have been disabled for a few months now, so we felt it was safe to finally disable plaintext imports. Feel free to install an older version of signal via the method of your choosing to restore your plaintext backup, and after you do your import, I recommend switching to using our encrypted backups.

**Comment by tribut** [comment]
What is a way to install such an old version? It seems the old .apks are not available from updates.signal.org.

**Comment by dikiaap** [comment]
@tribut I download it from updates.signal.org. I have use v4.15.5 and its works great. https://updates.signal.org/android/Signal-website-release-4.15.5.apk

**Comment by CapnPants** [comment]
I can't convince my dad to use signal because it won't import his SMS history and he doesn't want ANOTHER messaging app that won't handle fully SMS's.

**Comment by strugee** [comment]
@CapnPants this issue is about plaintext backup import; see https://github.com/signalapp/Signal-Android/issues/8075#issuecomment-410731349.

**Comment by axeloz** [comment]
> @tribut I download it from updates.signal.org. I have use v4.15.5 and its works great. https://updates.signal.org/android/Signal-website-release-4.15.5.apk

FYI I tried this solution. I uninstalled my version of Signal and installed the 4.15.5. I was able to import SMS messages. By safety I did a plain-text backup.
Unfortunately after upgrading Signal keeps crashing. I had to reinstall it. After reinstall, I tried to restore from the backup but Signal doesn't support this plain backup.

**Comment by hiswillpower** [comment]
> @tribut I download it from updates.signal.org. I have use v4.15.5 and its works great. https://updates.signal.org/android/Signal-website-release-4.15.5.apk

This is close but the solution I found to work to import your SMS messages and plain text backups is the following:
1. Update to https://updates.signal.org/android/Signal-website-release-4.15.5.apk
2. Import your text messages and save a copy as plaintext
3. Update to https://updates.signal.org/android/Signal-website-release-4.17.5.apk
4. Start app let it upgrade the db
5. Update to latest version of Signal (let it run for 60 seconds then close app and restart)
6. Enjoy!

**Comment by Akuukis** [comment]
It did not work for me - my phone says that installation is corrupted for both versions. 

What worked for me:
- use SMS Backup & Restore app to import XML into my new fresh phone Android SMS storage
- download Signal v5.0.8 (https://updates.signal.org/android/Signal-Android-website-prod-universal-release-5.0.8.apk)
- import messages from Android SMS storage
- upgrade Signal to the newest version
