### ISSUE TITLE
Backup restore passphrase

### ISSUE THREAD

**Issue by iGeekFace** [signalapp/Signal-Android#8077]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When restoring a backup, it does not accept the passphrase, at least when using the APK from the website instead of the Google Play version.

### Steps to reproduce
- Enable the backup option
- Copy and paste the backup passphrase somewhere safe. I chose my password manager.
- Uninstall Signal
- Reinstall Signal
- When prompted to enter the backup passphrase, paste in the passphrase you copied.

**Actual result:** An "incorrect passphrase" prompt appears.
**Expected result:** Successful backup restore

### Device info

**Device:** OnePlus 5T
**Android version:** 8.1.0
**Signal version:** 4.24.8 (website release)

**Comment by moxie0** [comment]
Do you have xposed or any shit like that running?

**Comment by iGeekFace** [comment]
It seems that was it. Thanks!

Any idea why oandbackup would restore an unusable version of Signal? It's currently the only chance I have of accessing my old data, and when I launch the restored version, it crashes.

**Comment by moxie0** [comment]
Probably because it's backing up an encrypted database file, but not the key (stored in the android hardware keystore). Try hitting up the forums if you have more questions, thanks.
