### ISSUE TITLE
Signal crashed

### ISSUE THREAD

**Issue by bala-signal** [signalapp/Signal-Android#8080]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashed unfortunately when setting profile name and return back.

### Steps to reproduce
- Go to settings -> profile name activity.
- Tap "Finish" and press back.
- Signal unfortunately stops.

**Actual result:** When i tap back, it should stop all the process. 
**Expected result:** When i tap back, it gets crashed.

### Screenshots
Attached the video link here, please look at it. 
https://s3.us-east-2.amazonaws.com/signalapp/Bug+videos/IMG_4866.MOV

### Device info

**Device:** Samsung SM-J700F
**Android version:** 6.0.1
**Signal version:** 4.24.7

### Link to debug log

https://debuglogs.org/1e727d05e3d343a15ad9408661713ba2b27e80d5c4da436333e572810e83706b

**Comment by greyson-signal** [comment]
Can't repro, and unfortunately the logs are no longer available.
