### ISSUE TITLE
Checkboxes in contact share dialog not full line

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the contact share dialog the hitbox of the checkboxes are only the checkboxes themself, not the entire line like usually, e.g. in the Play Store: `Settings` => `Add icon to Home screen`.

### Steps to reproduce
- Open Chat
- Open share menu
- Select "Contact"
- Select a contact
- Click on the phone number

**Actual result:** Nothing happens
**Expected result:** The checkbox should be toggled

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.23.4

**Comment by sdew021** [comment]
Can I pick up this bug?

**Comment by mueller-ma** [comment]
The Signal team probably won't answer you, but feel free to open a PR and propose a fix.

**Comment by alex-signal** [comment]
This will be resolved in 5.25
