### ISSUE TITLE
Some messages do not appear

### ISSUE THREAD

**Issue by Da0012** [signalapp/Signal-Android#8085]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Some messages has tag sent, received and read but they does not appear on the receiver's devices.
The messages were sent from desktop and android.
First it happened on signal, After that I noticed that wire too.

This is bidirectional.

i am using a new smartphone,both installations are recent.
both signal version are 4.24.8

### Steps to reproduce
- I don't know how to reproduce it.

**Actual result:** I sent messages and they don't show up on receiver device.
**Expected result:** That the messages appear and the delivered tag works correctly. 

### Device info

**Device:** Asus Zenfone 4 max and Samsung J2 prime
**Android version:** 7.1.1 and 6
**Signal version:** 4.24.8

### Link to debug log

https://debuglogs.org/be41131edc2725abe80640d9ca06d2862587206d4ec54d01ae22de4f603931fd

https://debuglogs.org/9831f717564f3e1e473c0220ee6b47f29a5a4e0f1b0865016bae87061f67e07c

**Comment by Da0012** [comment]
#7499 is mine, but i can't reopen.

**Comment by eivisand** [comment]
I'm also missing some messages, and I have no idea how to reproduce, other it happening sometimes.
This morning at 08:31 I received a message in a group, that I don't have on my desktop signal.

**Comment by eivisand** [comment]
I'm also missing some messages, and I have no idea how to reproduce, other it happening sometimes.
This morning at 08:31 I received a message in a group, that I don't have on my desktop signal.
[Debug log desktop](https://debuglogs.org/f9394419db6fa931480cbdfa4ec9ccc0b571c54bd0ba28158cd8d347e9d1926b)
[Debug log phone](https://debuglogs.org/6d451087721d5049810c50b505946547c227bbb228d3e00584b6325d2cb79932)
**About the desktop**
OS version: Windows 10 Enterprise, Version 1803, OS build: 17134.165
Signal for windows: v1.15.4

**Comment by joannalange** [comment]
I'm having the same issue in a group chat, happens to all chat members (both android and ios devices), but usually a certain message is not missing for all people - seems to be random who can/cannot see it

**Comment by greyson-signal** [comment]
I'm unable to reproduce this, and the logs are expired. If this happens again, can you open a new ticket with more details? Logs in 4.25.x should be longer and more useful. Thanks!
