### ISSUE TITLE
Please, reenable more colors to choose from for contacts for colorblind users

### ISSUE THREAD

**Issue by watchmoretv** [signalapp/Signal-Android#8086]
Dear developers,
after an update to Signal version 4.24.8 on Android some "beautiful colors like orange" for contacts disapeared and now i can choose from only nine colors i can hardly distinguish, because i am suffering of deuteranopia (https://www.color-blindness.com/deuteranopia-red-green-color-blindness/ )
It would be great if you can reenable more colors to choose from.

Another problem is that my wired headset on my Sony L25i is still muted only with Signal, maybe due to echo cancelation...

**Comment by Dyras** [comment]
Can you give some examples of colors you want to get added? More greens? More blue colors?

**Comment by xdPh03nix** [comment]
Can we add a feature where you can give every chat a custom color?
Maybe in the form of a simple RGB slider where you can input a value?

Also, is it possible to change the text color of incoming messages to black instead of the white?

**Comment by tpoliaw** [comment]
Another vote for custom RGB colours (or just a greater selection) but even a list of 9 different colours would be good. At the moment I have four colours. Three are red, two blue and three green. I'm not colour blind and without seeing them next to each other I wouldn't be able to distinguish them. I have groups with more than four people in.

**Comment by Wunsch42** [comment]
Even just going back to the selection of colours available in the previous version would be significantly better.  It wasn't great, but it was enough to be useful.  The current choices are not enough to be useful.

**Comment by greyson-signal** [comment]
Hi there, colors are something we're looking to improve. However, as specified by our [reporting guidelines](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports), Github is for bugs, not discussion topics. So I'm going to close this, but feel free to start a discussion on [the forum](https://community.signalusers.org/). Thanks!
