### ISSUE TITLE
Empty message date tooltip is shown in new message thread

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#8089]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A new message has an empty date tooltip shown when swiped.

### Steps to reproduce
- Start new message thread
- swipe down on the screen

**Actual result:** tooltip that normally shows message dates is displayed, empty
**Expected result:** Tooltip is not displayed if there are no messages.

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.24.8

**Comment by rforrizwan55** [comment]
I am not able to reproduce this on oneplus 6. Is this still broken?
