### ISSUE TITLE
Crash when calling after upgrade to 4.24.8

### ISSUE THREAD

**Issue by pshephard** [signalapp/Signal-Android#8090]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgrading to the latest and greatest Signal app (4.24.8), the calling functionality crashes (though it only crashes the "Signal Call <phone>" portion; the normal text messaging portion still operates just fine).

Calls worked well up until I upgraded to 4.24.8 today. Not sure exactly which version I was running before, but based on the repo's release history it was likely 4.24.{0-2}.

When the crash happens, examining the chat history for that contact afterwards says "You called" for each attempt that crashed, however the contact never saw the missed call. When my contact calls me, Signal crashes, and when I open Signal again afterwards it says "Missed call".

Text messages back and forth over the Signal protocol work just fine.

My contact is running an older version of the Signal app on Android (not sure which exactly), however my expectation is that an older app version shouldn't crash my newer one. The contact is unable to upgrade to the latest version due to low free space.

I also tried calling a contact who is known to have their phone offline, and that crashed similarly.

### Steps to reproduce
- Open or create a conversation with a Signal contact
- Click the call button
- Window displays "Signal call +<phone number>" with "Dialing"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- Call window crashes after a few seconds and displays "Unfortunately, Signal has stopped."
- Conversation window displays behind the "Unfortunately, Signal has stopped" alert and returns after I click "ok"

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- Wonderful, private conversation

### Device info

**Device:** Motorola XT1528
**Android version:** 5.1
**Signal version:** 4.24.8

### Link to debug log
https://debuglogs.org/5286de5a56a51e900d0e6e45a44f0b7c409dddbdccf75528edd2ebb5ecaa3859

**Comment by c904370** [comment]
Hi,

The same behaviour is observed by me, but only when using a VPN (OpenVPN for Android or the official ProtonVPN client). When the VPN is disconnected - I can make a call.
(I am not sure if the OP uses a VPN or not)

If somebody else tries to call me, my Signal app crashes w/o ringing.

The problem is present in 4.24.7 and 4.24.8.

Link to debug log:
https://debuglogs.org/9ba8b40c850d53d9c226cb1472b065830cf9a546da55209b064ba2b83926e54c

**Comment by pshephard** [comment]
I've confirmed that the crash only happens for me when running a VPN (in my case, [NetGuard](https://www.netguard.me/), a sort-of personal firewall which I find necessary to keep random apps from leaking information on me).

If I disable NetGuard, I can successfully make outgoing calls.

**Comment by pshephard** [comment]
FYI - crash still happens after installing 4.25.0

**Comment by bloodwood** [comment]
I use PIA VPN, and same problem.  FWIW, the PIA Support desk says: "Signal appears to need ports 80, 4433 and 8443. PIA has port 80 open, but ports 4433 and 8443 are both closed on our servers. To use this app you will need to disconnect from PIA.”

Link to debug log:
https://debuglogs.org/9ef40ef3c242fdfd4ed0ba0aaf7c013466d030bdc6aa4a6fd53d5a6859302220

Device: Samsung Galaxy Note 3 (SM-N9005)
OS: Android 5.0
Signal: Version 4.24.8
PIA: Version 1.6.0.2 (386)

**Comment by pshephard** [comment]
@greyson-signal @moxie0 Is there any additional info we could provide that would help in debugging?

**Comment by greyson-signal** [comment]
@pshephard Can you get me a log from the 4.25.x beta? More logging has been added in that build. The other logs don't have a lot of info right now.

From the sound of it, your VPN is blocking ports we need. But we should still be failing gracefully.

**Comment by e5575177** [comment]
Hi,
The issue persist also with version 4.26.2.

Link to debug log:
https://debuglogs.org/b2460daa03c3632a7b09f7465b60ad8834f56ef884fca793fff8a16ecd036336

I cannot try the beta, but perhaps you can try to simulate it with free ProtonVPN account or with NetGuard, or just with a simple OpenVPN?

**Comment by e5575177** [comment]
@greyson-signal @moxie0 was the debug log above helpful enough to show the cause of the problem?

**Comment by e5575177** [comment]
@greyson-signal @moxie0 
The issue persists with version 4.29.7

Link to debug logs:
https://debuglogs.org/a3ebcbc69493ef376e70864b47d68c0804ed1d0705803a67611abc9e747ec0aa

**Comment by e5575177** [comment]
I also can confirm that the issue persist when using Blokada (https://blokada.org/), as it also behave like a VPN. It can be used to reproduce the problem.

**Comment by e5575177** [comment]
The issue persist with version 4.30.7 also.

Debug logs: https://debuglogs.org/6009bd9d1df5b9acd49b24130b6454cf9ab7ce3cf31c99516345d66e58414dab

**Comment by e5575177** [comment]
It seems that the issue is not present on Android 8 and 9.
Unfortunately - it is still present on Android 5..
