### ISSUE TITLE
Allow users to use the old u.i and bring back the option for more colors

### ISSUE THREAD

**Issue by BlackRabbit22** [signalapp/Signal-Android#8093]
For those who dislike the new u.i, please add an option for people to use the old one.

Also please bring back the old color scheme. There used to be more than 9 colors.

**Comment by Riotous** [comment]
I have a feeling the devs just want to have Signal look like iMessage and Android Messages, respectively, but I think every messenger app should take a lesson from Textra on how to do a customizable UI.

**Comment by Grammost** [comment]
> I have a feeling the devs just want to have Signal look like iMessage and Android Messages [...]
>
Yeah, seems like it. But I'm not a big fan of it. Signal's design needed some improvements, but this overhaul based on the respective messengers is not at all what I would have liked. 
Also, I think people will more likely switch from WhatsApp to Signal, so, I think, it makes more sense to keep it closer to that design, although in the end Signal should also have a destinct design.

(I know this probably belongs on the forum, but I still wanted to mention it.)

> [...]  I think every messenger app should take a lesson from Textra on how to do a customizable UI.
>
Definitely something the devs should look into.

**Comment by Hormesis** [comment]
> For those who dislike the new u.i, please add an option for people to use the old one.

So, you know they're never going to do that, right? 

Perhaps it would be valuable to provide specific suggestions for the new version on the forum where they've been requesting feedback for the past month.

**Comment by BlackRabbit22** [comment]
@Hormesis what forum? I didn't get any information about that.

**Comment by greyson-signal** [comment]
@BlackRabbit22 Whenever you create a new issue, it's pre-populated with a template. Part of that template says:

> If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org

We use Github exclusively for bug reports. So I'm going to close this issue for that reason, but please feel free to start a discussion on the forum. There's also a [forum post](https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532/115) we created to collect feedback on the design changes.

Thanks!
