### ISSUE TITLE
Multiple SMS sent with two sim cards available

### ISSUE THREAD

**Issue by hennr** [signalapp/Signal-Android#8094]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending an SMS via sim card one (offline) and sim card two online leads to multiple SMS sent after going online with sim card one.

### Steps to reproduce
- find a device with two sim cards available
- go offline with sim card one
- go online with sim card two
- send an SMS with sim card one
- go online with sim card one

**Actual result:** 
- multiple SMS sent to receiver (83 in my case)

**Expected result:**
- user gets notified that sending SMS is not possible while offline
- one SMS will be send to receiver when going online again

### Device info
**Device:** Samsung galaxy S9 DUOS (sm-g960f)
**Android version:** 8.0.0
**Signal version:** 4.23.4

### Link to debug log
Sorry, no log as this has happened some days ago

**Comment by alan-signal** [comment]
This was fixed by the fix for this #8426 as you cannot now select SIMs that are not ready.
