### ISSUE TITLE
Max disappearing messages delay too low; with usecase

### ISSUE THREAD

**Issue by leo-bogert** [signalapp/Signal-Android#8096]
- [x] I have searched open and closed issues for duplicates

### Bug description

I'm trying to use Signal to coordinate development of open source software.  
As OSS is usually developed by volunteers the contributors mostly only have time to process messages on the weekend.
Also as weekends are for recreation, they won't want to contribute each one of them.

This means that the current maximal disappearing message delay of 1 week is very stressful when using Signal as a developer chat tool.

I would propose adding 1 month and 3 months as delay options.

**Notice before closing**: I do fully admit that this is a usecase which does not affect the average human.  
However Signal being open source itself means that this issue may affect its own developers.
And if a software isn't suitable for being used by its own developers then something is wrong :)

**Comment by johanw666** [comment]
Why do you use disappearig messages at all in this use case? It might be usefull to read something back from some time ago.

**Comment by moxie0** [comment]
Thanks for writing @leo-bogert, but we don't use GitHub for feature requests, only for tracking bugs (existing functionality that does not work as intended). Please head over to the forums for discussions like these, feedback there is really helpful in development. Also, it's very difficult for us to manage issues when you delete the issue template, so please try not to delete that in the future. Thanks!

**Comment by leo-bogert** [comment]
@moxie0 
> Thanks for writing @leo-bogert, but we don't use GitHub for feature requests, only for tracking bugs 

I am aware of that, however I don't see how adding two entries to an enum is a new feature?
I would also consider the usability of this as broken, hence it is a bug IMHO.

Besides, my experience of other projects is that developers only work from the bugtracker and the forums serve as a graveyard for stuff which won't be implemented. If I were to contribute I wouldn't  either get the idea that the forum is the place to search for part of the issues of the project.
Does any of the Signal employees actively search the forums for highly upvoted stuff regularly or is this solely a place where users dwell?

> Also, it's very difficult for us to manage issues when you delete the issue template, so please try not to delete that in the future. Thanks!

I *had* filled in those parts of the template which seemed relevant and only deleted the ones which seemed irrelevant. If you hint me at which of those are also relevant I can edit them in.

Thanks for your feedback!

**Comment by moxie0** [comment]
> I would also consider the usability of this as broken, hence it is a bug IMHO.

We only use GitHub is only for existing functionality that does not work as intended. For instance, we intended the disappearing message timeout values to be the values that they are. If the value for 1 day actually timed out after 10 seconds, that would be appropriate to file here, because it would be existing functionality that did not work as intended.

If you want the functionality to be different, then GitHub is not the place where we track that

> Does any of the Signal employees actively search the forums for highly upvoted stuff regularly or is this solely a place where users dwell?

Yes, we read every single post.
