### ISSUE TITLE
Google Required To Register - Needed To Uninstall FakeStore

### ISSUE THREAD

**Issue by 0pLuS0** [signalapp/Signal-Android#8097]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

This is really frustrating needing to register Signal with Google, which I thought needing the Google Play Services to register was done away with?

I don't use Gapps on the phone, my custom rom is almost all stripped of Google, I use F-Droid instead.

Can Open Whisper please kill off this Google dependancy for registration.

Using custom roms with microg, I have noticed you can't register if you have FakeStore installed, you need to remove it, at least running the ```Stable``` versions of microg.

I have noticed if I use the latest Preview versions of microg, and I add a Google/Gmail account to the device, I can register ok, maybe the account works ok on the stable version of microg, I didn't test it.

I don't want a Gmail account, and it seems like the only way around this I have found out, unless you uninstall FakeStore. End-Users shouldn't be forced into needing a Google/Gmail account to register Signal when running custom roms and microg.

### Steps to reproduce
- Installed custom rom
- Installed microg
- Installed Xposed
- Installed FakeGapps
- Everything checked in microG except ```Location Backends & Network-based location```

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

If I try to register it asks me to update Google Play Services.

### Screenshots

![signal](https://user-images.githubusercontent.com/36190223/43989042-1b91ecd4-9d32-11e8-9f20-19801d0c27cd.jpg)

This is a screen shot now showing a message with FakeStore uninstalled.

![fakestore](https://user-images.githubusercontent.com/36190223/43989204-c3a60b38-9d34-11e8-80bd-b7f57ac4ffbf.jpg)

Now the issue also becomes, will there be ```reliability``` and ```performance``` issues?

### Device info

**Device:** Xiaomi Mi A1
**Android version:** 8.1.0
**Signal version:** Signal-website-release-4.24.8
**Services Core - com.google.android.gms-9258259.apk
** Services Framework Proxy - com.google.android.gsf-8.apk
** Store (FakeStore release) - com.android.vending-16.apk
** DroidGuard Helper - org.microg.gms.droidguard-4.apk - stable

**Comment by 0pLuS0** [comment]
I apologize, when using all the stable versions of microg, this is the problem you run into.

I went back and wiped my phone and reinstalled all over, this time installing these two ```Latest Preview``` versions of microg;

Services Core - com.google.android.gms-12221403.apk
DroidGuard Helper - org.microg.gms.droidguard-14.apk

It appears that updating to the latest Services Core works without the need to have a Google Account, and there's no more message about needing to update the Google Play Services.

If the Signal Team is not aware of this, it might be good to keep note of this issue for others using microg.

Even one of the developers of F-Droid, thought he needed a Google account to accomplish this...

**Comment by greyson-signal** [comment]
Yeah, it's pretty much impossible for us to track every combination of rooted tools that mimic/alter core system services. Thank you for posting how you solved this specific problem! Hopefully it'll serve as a good reference for others that run into similar situations.

**Comment by 0pLuS0** [comment]
Well glad to be of some help, hope it serves others well.

Here are some screen shots showing the ROM with only a Signal Account and the microg settings.

I don't have any ```Location``` Back ends configured!

![accounts](https://user-images.githubusercontent.com/36190223/43996870-e8a85c60-9dbb-11e8-92ac-b271d1587dcf.jpg)


![microg_1](https://user-images.githubusercontent.com/36190223/43996871-f15da018-9dbb-11e8-9443-aa9727a38bc8.jpg)


![microg_2](https://user-images.githubusercontent.com/36190223/43996872-f514c1be-9dbb-11e8-97f8-4c39828405f3.jpg)


![microg_3](https://user-images.githubusercontent.com/36190223/43996874-f879a752-9dbb-11e8-80a9-214c220b0c30.jpg)


![microg_4](https://user-images.githubusercontent.com/36190223/43996875-fb5b01a0-9dbb-11e8-8bbf-3c587e8dd253.jpg)

**Comment by 0pLuS0** [comment]
Well glad to be of some help, hope it serves others well.

Here are some screen shots showing the ROM with only a Signal Account and the microg settings.

I don't have any ```Location``` Back ends configured!


![accounts](https://user-images.githubusercontent.com/36190223/43996894-a0a0634e-9dbc-11e8-9b18-24cecdb4f9fb.jpg)


![microg_1](https://user-images.githubusercontent.com/36190223/43996895-a426ee0c-9dbc-11e8-96c3-827a295ec5a9.jpg)


![microg_2](https://user-images.githubusercontent.com/36190223/43996897-a716ef54-9dbc-11e8-8433-076a747739d9.jpg)


![microg_3](https://user-images.githubusercontent.com/36190223/43996898-aa0d82b8-9dbc-11e8-9b2e-01e42aeef05f.jpg)


![microg_4](https://user-images.githubusercontent.com/36190223/43996899-accf562a-9dbc-11e8-83d5-9fd4456a831b.jpg)
