### ISSUE TITLE
Signal Users Are Taken Out Of Alphabetical Order

### ISSUE THREAD

**Issue by 0pLuS0** [signalapp/Signal-Android#8100]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When opening Signal and clicking the pencil/pen and then seeing the Contacts, Signal users are placed at the top of Contacts, breaking ```Alphabetical Order```

I'm calling this a Bug, which I'm assuming this is the way it's designed, but this is really a flawed idea, for people that have a lot of contacts, and then get them shuffled like this. I really hate this, and with a lot of contacts this is going to be crazy looking at the contacts like this.

PLEASE figure something else out so that the ```Alphabetical Order``` is not messed with. Please don't even add blue color fonts, or bold fonts, because I also noticed the name was now in bold color. Maybe a ```lock icon``` can be added somewhere in the contacts is all?

```Please don't take me the wrong way, I truly appreciate all the work everyone is doing on such a great app, but this really needs to change, I can't stand this. I understand this is only seen like this inside Signal, that the actual Contacts app is not changed, but it would be great if the contacts were still left looking orignal in Signal.```

### Steps to reproduce
- Open Signal
- Click pencil/pen
- Now you'll see Signal users at the top of the Contacts list.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Contacts are not in ```Alphabetical Order```. The correct behaviour should not be to change the contacts order like this, it looks sloppy. The correct behaviour should be to just add a ```lock icon``` somwhere to the contacts is all.

### Screenshots

```In the screen shot you will now see my one contact, while I am testing this as a Letter E is being placed now at the very top above all the A contacts.```

![contacts](https://user-images.githubusercontent.com/36190223/43999777-a00cd69c-9e02-11e8-8ec8-84795eeb6f51.jpg)

### Device info

**Device:** Xiaomi Mi A1
**Android version:** 8.1.0
**Signal version:** Signal-website-release-4.24.8

**Comment by nrizzio** [comment]
The contact selection menu is in alphabetical order. Signal users are grouped separately from SMS-only contacts, but the two groups are both put into alphabetical order. The Signal contact group is above the SMS contract group.

This issue doesn't qualify as a bug under the contributing guidelines and should be posted on the forum instead.

**Comment by moxie0** [comment]
As you've noted, this is the intended functionality. GitHub is only used to track existing functionality that does not work as intended. If you have ideas about features, thoughts about how you think things should work, etc please visit the forums. Thanks!

**Comment by 0pLuS0** [comment]
I don't have a forum account, so if this can be noted here, it would be greatly appreciated!

Please make an option in Signal so the end-users have a choice of having the ```Signal Grouping``` or ```Default Grouping```.

Default Grouping of course meaning, don't change anything...

Thanks for your consideration, I hope you will do this.

**Comment by minnmann** [comment]
> I don't have a forum account, so if this can be noted here, it would be greatly appreciated!

I think, you could just sign in at the forum with your GitHub account - at least this is what I do.

**Comment by 0pLuS0** [comment]
This? --> https://whispersystems.discoursehosting.net/

**Comment by 0pLuS0** [comment]
This? --> https://whispersystems.discoursehosting.net/

I tried logging in with my GitHub account, it just sits there saying ```Authenticating``` and doesn't do anything else...

**Comment by 0pLuS0** [comment]
@minnmann not sure if you saw my edited post above? It's working now, but now I'm getting it needs to be authorized by  ```riyapenn```, which doesn't tell the end-user anything about this. 

If the system could be changed, this should say to allow ```Signal``` to authorize, not some name of someone no one knows anything about... :-1:

**Comment by 0pLuS0** [comment]
@minnmann not sure if you saw my edited post above? It's working now, but now I'm getting it needs to be authorized by  ```riyapenn```, which doesn't tell the end-user anything about this. 

If the system could be changed, this should say to allow ```Signal``` to authorize, not some name of someone no one knows anything about... :-1: 

Signal is a company about ```Security``` and then we're suppose to Authorize the name of a person, instead of the name of a Company? Am I like the only getting this? sheesh :(

**Comment by minnmann** [comment]
My understanding is that the forum is not owned by Signal itself (see https://community.signalusers.org/t/help-us-test-the-new-community-domain/1998/3). 
However, the team reads the posts, interacts with the community and also moderates the forums.

You can find a list of moderators (including riyapenn) here: https://community.signalusers.org/groups/moderators

In any case, I guess we should shut down the discussion here, since it's getting very off-topic. I think you can share your feedback directly at the forum.
