### ISSUE TITLE
GCM notification received but only receive message notification on opening Signal

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8104]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Phone led was blinking and after unlocking the phone I noticed there was one new Signal message. On opening Signal I instantly received a number of new notifications. After checking the logfile it seems that the GCM notifications are received however they're not processed. Based on the logfile I guess that something went wrong while handling the first notification and that prevents handling the later received notifications however that's just my guess. Below are the message details of the related notifications. 
Note that I could not link the GCMBroadcastReceiver message from 09:39:22.117 to a specific message. 
I'm not sure if it's related but I should mention that the initial message was the first Signal message I've received from that contact.

message contact 1. This was the initial notification.
send 13 aug. 2018 07:53:12 CEST
received 13 aug. 2018 07:53:16 CEST

These are the message details of the notifications I got when opening Signal.
send 13 aug. 2018 08:00:38 CEST
received 13 aug. 2018 09:52:32 CEST

send 13 aug. 2018 08:02:56 CEST
received 13 aug. 2018 09:52:33 CEST

send 13 aug. 2018 09:21:04 CEST
received 13 aug. 2018 09:52:33 CEST

### Steps to reproduce
Unable to reproduce.

**Actual result:** Notification for only the first message was shown and the receive timestamps for later received messages was not correct.
**Expected result:** Notification shows the number of received messages and the receive timestamp for messages is correct. 

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.24.8

### Link to debug log

https://debuglogs.org/276d12cfec2d9114b8d1c4b5ab1680bf4f61ce4f7f26bb4f86c09a566be4c680

**Comment by bme13** [comment]
Yesterday I opened Signal and instantly received a notification of a message that was send approximately 25 minutes ago.   
Message details show:

send: 29 sep. 2018 19:24:28 CEST
received: 29 sep. 2018 19:50:52 CEST

After checking the debug log there were 2 messages around that time:
`2018-09-29 19:24:29.423 CEST I GcmBroadcastReceiver: GCM message...`
`2018-09-29 19:29:29.858 CEST I GcmBroadcastReceiver: GCM message...`

To me it seems that this is perhaps the same situation as before. e.g. GCM notification was received but not processed. I've changed the title accordingly since it seems it has nothing to do with previously received messages. 

log: https://debuglogs.org/fb86faeebcecc82013db24bf86a6709c8954f31a8649fb434a1f1a9d997fd1a5

**Comment by moxgeek** [comment]
@bme13  i'am facing the same issus right now , any solution yet ?

**Comment by bme13** [comment]
Hi @moxgeek. A lot of things have been changed since I've seen this behavior. In version 4.27 Signal switched to using Workmanager and in version 4.28 there seem to be a change to prevent this to happen (with the new Workmanager) See commit https://github.com/signalapp/Signal-Android/commit/1b736e9e0409d7a0926246bc0fbb11a2db4946e1. I assumed that these changes might have solved this and haven't seen the issue since. However if you run a Signal version above 4.28 and still see this perhaps you can add a debug log.

**Comment by moxgeek** [comment]
i'am still using the 4.28 

the log on the server is : 

```
ERROR [2018-11-07 16:48:40,352] org.whispersystems.textsecuregcm.storage.MessagesCache$MessagePersister: Exception while persisting:
! java.lang.NullPointerException: Executor was null.
! at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
! at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:658)
! at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:107)
! at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
! at org.whispersystems.textsecuregcm.push.GCMSender.sendMessage(GCMSender.java:74)
! at org.whispersystems.textsecuregcm.push.PushSender.sendGcmNotification(PushSender.java:110)
! at org.whispersystems.textsecuregcm.push.PushSender.sendQueuedNotification(PushSender.java:82)
! at org.whispersystems.textsecuregcm.storage.MessagesCache$MessagePersister.notifyClients(MessagesCache.java:485)
! at org.whispersystems.textsecuregcm.storage.MessagesCache$MessagePersister.run(MessagesCache.java:396)

```


the server don't crach , just display the error and continue working 
when the reciver open the app he recive  the message even if the server throw this exception
