### ISSUE TITLE
[Bug] No Incoming Call Notification When Screen Is Locked

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#8105]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some times when the screen is locked there is no incoming call notification, where the screen lights up and displays the contact who's calling and the answer, decline buttons.

Instead you just get a missed call notification straight away although, other times it works correctly. 

### Steps to reproduce
- Do nothing and receive incoming call.
- See notification not for call but for a message. 
- Call contact back.

**Actual result:** 
As stated in bug description

**Expected result:** 
Normally you should see the screen light up and display the contact who's calling and the answer, decline buttons.

### Device info
**Device:** Samsung SM-G955F
**Android version:** 8.0.0 > 9
**Signal version:** 4.24.8 > 5.2.2

### Link to debug log
https://pastebin.com/gSkHE3dH

**Comment by nunoperalta** [comment]
One thing that I tried and seems to have helped is by going to:

Settings -> Apps -> Signal -> Battery -> Power Saving Exclusions

And mark Signal as excluded.
This seems to make the Answer/Decline + Photo appear while the phone is locked.


However, sometimes I continue not to get the call at all on the phone while it's locked, unless I wake up the screen by myself (and then the Sound + Answer/Decline happen straight away).

Signal is also excluded from the Background Restrictions list.

**Comment by TechStyle93** [comment]
Same Problem with:
- Huawei P20
- Huawei P20 Pro
- Huawei P30

We already tried every hint from singal notification and call support page.

**Comment by em-pi-three** [comment]
Same issue with Xiaomi Poco X5 Pro
