### ISSUE TITLE
New "Add attachment" icon still visible with attachment present

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#8108]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The new add attachment button ('+' in input field) is still visible when there already is an attachment present. This is confusing because a '+' implies an additional attachment is added. Instead the existing attachment is replaced.

### Steps to reproduce
- open conversation
- add attachment

**Actual result:** '+' icon in input field for adding a new attachment
**Expected result:** No '+' icon in input field, because Signal currently only supports one attachment per message.

### Screenshots
sorry, not enough time...

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.25.1

### Link to debug log
not useful

**Comment by igor2x** [comment]
I can confirm this problem on Android 8.1.
This is 4.25 specific problem.

![attachment_button](https://user-images.githubusercontent.com/10895030/44149425-5bef5b1e-a09c-11e8-8b96-c278590170c9.png)

**Comment by greyson-signal** [comment]
This is a fair criticism. I had initially left the button there intentionally, but I can see how this would cause confusion and make people think we support multiple attachments. Hiding it :)

**Comment by greyson-signal** [comment]
Whoops, forgot to link the issue in my commit. Fixed in 3c6b8bcf9b7e196060d760da257ecd658dc6afc4.
