### ISSUE TITLE
[Question] Auto Update

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [signalapp/Signal-Android#8114]
A few weeks after installing the apk I downloaded from Signal's website, the app notified me about an update. I updated. Is this normal? I use a phone that's running a custom ROM with no Google Play Service.

**Comment by haffenloher** [comment]
Hey @iknownothingaboutcomputers, please don't delete the issue template when filing an issue. We use GitHub as a bug tracker only, not as a discussion forum. If you want to ask questions, take a look at the [community forum](https://community.signalusers.org/). You can use your GitHub account to log in.

**Comment by jlund-signal** [comment]
Yes, this is intended functionality.

**Comment by iknownothingaboutcomputers** [comment]
@haffenloher Didn't know. Thanks for the info. And sorry for the late reply.
