### ISSUE TITLE
[4.25.2] Custom notification sound no longer working

### ISSUE THREAD

**Issue by astronaut-wannabe** [signalapp/Signal-Android#8117]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Prior to the latest beta version of signal, I have had certain contacts set to different notification sounds (specifically the "Hey!" sound)

After the update to 4.25.X now all notification sounds play the default system notification sound  **unless** I actually have the signal app open with the conversation with that contact open (the list view of all chats can be open and still play the default sound)

### Steps to reproduce
- Have a contact notification sound set to a non-system-default sound
- receive message when in conversation, hear custom sound
- receive message when signal in background, hear default android system sound

**Actual result:** When I get a message from the contact I the default notification sound when I used to hear "hey!"

#### notification sound set to hey
<img src="https://user-images.githubusercontent.com/13190980/44238940-a369e980-a16b-11e8-8ef0-35211f8a4d83.jpeg" alt="settings" width="50%">

#### I hear default sound when signal in background OR on this screen
<img src="https://user-images.githubusercontent.com/13190980/44239500-85ea4f00-a16e-11e8-9bff-89fd487fefca.jpg" alt="index" width="50%">

#### I only hear custom set sound when on this screen
<img src="https://user-images.githubusercontent.com/13190980/44239521-98fd1f00-a16e-11e8-9de5-f3e989b5249b.jpeg" alt="detail" width="50%">

### Device info

**Device:** Pixel XL
**Android version:** Stock Android version 9
**Signal version:** 4.25.2

### Link to debug log
https://debuglogs.org/890189eb7e6c3679b3b22e4a2641d3ee69790b7dcfa454db86188835b81ba31c

**Comment by schmeat** [comment]
Appears to be the same issue I'm having #8112

**Comment by astronaut-wannabe** [comment]
@schmeat shoot, you're right. looks like the same root cause.

This issue can probably be closed as a dupe

**Comment by astronaut-wannabe** [comment]
closing in favor of #8112
