### ISSUE TITLE
Notifications not turning on LED

### ISSUE THREAD

**Issue by h4waii** [signalapp/Signal-Android#8119]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notification LED is no longer triggered. Have tested all other applications and LED shows fine, have removed and re-added the "custom app" LED for Signal, and the issue persists. This is not an issue with the Android system, only Signal.

### Steps to reproduce
- Configure LED notifications from within Android settings
- Configure LED notifications from within Signal app
- Receive message while screen is either OFF or ON

**Actual result:** Notification LED does NOT turn on.
**Expected result:** Notification LED should turn on, according to the configurations set in the above steps.

### Device info

**Device:** Xiaomi Redmi Note 4
**Android version:** 8.1.0
**Signal version:** 4.25.2

**Comment by greyson-signal** [comment]
Yeah, unfortunately this was an unintended side-effect of adding notification channels. We'll have a fix ready soon :+1:
