### ISSUE TITLE
Scanning safety number QR code does not set conversation to "Verified"

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#8120]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Scanning the recipient's safety number QR code displays a check mark briefly, but does not set the conversation to "Verified." It is difficult to tell whether the brief check mark means the safety number matches, that the code was scanned successfully, or something else.

### Steps to reproduce
- Scan the safety number QR code on a recipient's phone

**Actual result:** QR code scans and a check mark briefly appears
**Expected result:** If the safety numbers match, the conversation is marked "Verified"

### Device info

**Device:** Google Pixel XL
**Android version:** 7.2.1
**Signal version:** 4.24.8

**Comment by FeuRenard** [comment]
This was a deliberate decision:
https://github.com/signalapp/Signal-Android/pull/6731#issuecomment-308311855
