### ISSUE TITLE
Starting today, the notification dot is shown even with no new messages if Signal is unlocked

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8121]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting this morning, I've noticed that the Android notification dot on the Launcher shortcut is **always** shown, as long as Signal is unlocked. Previously, it only appeared if you had a new message.

### Steps to reproduce
1. Unlock Signal.
2. A notification dot appears on the Signal shortcut on your Launcher.
3. if you lock Signal, the dot goes away.

**Actual result:** The dot appears even if there are no messages
**Expected result:** The dot appears if you have new messages, and not otherwise. **I'm 99% certain this is how it used to be before today, but I could be wrong**

### Screenshots
![image](https://user-images.githubusercontent.com/12563436/44289256-b4058700-a273-11e8-9d0b-490875553f20.png)

### Device info
Device : Google Pixel XL (marlin) 
Android : 9 (4898911, PPR1.180610.009) 
Memory : 151M (0.00% free, 512M max) 
Memclass: 256 
OS Host : wprf1.hot.corp.google.com 
App : Signal 4.25.2 

### Link to debug log
https://debuglogs.org/40d2f5bef57e3017c1d5e4ddbf7f0ae0352e57594dc83eb86fe3415088e25e64
(Is it just me or does it take forever to upload these logs now?)

**Comment by greyson-signal** [comment]
This was an unintended side effect of our notification channel configuration. You could fix it yourself by going to the Signal's app info page and unchecking "Show notification dot" in the "Lock status" channel, but that setting will be off by default in the next release. Thanks!
