### ISSUE TITLE
Custom notification sounds for individual contacts are ignored

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8122]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting today, my custom notification sounds are ignored on Android 9.0. I now only hear the default Pixel notification PLING instead of the guitar sound I used to use :(
At first I thought an update had reset it to the default, but nope. It's still set to my guitar sound, which was included with my Pixel phone if that matters.

**This happens when Signal is locked, but also when it's unlocked.**

### Steps to reproduce
1. Set a custom notification sound to a contact
2. Receive a message
3. It should be the default PLING

**Actual result:** Custom notification sounds are ignored
**Expected result:** The custom notification sounds should be played! #justicefortheguitar

### Device info
Device : Google Pixel XL (marlin)
Android : 9 (4898911, PPR1.180610.009)
Memory : 151M (0.00% free, 512M max)
Memclass: 256
OS Host : wprf1.hot.corp.google.com
App : Signal 4.25.2

### Link to debug log
https://debuglogs.org/40d2f5bef57e3017c1d5e4ddbf7f0ae0352e57594dc83eb86fe3415088e25e64
^ The phone number ending with 23 is the number I'm talking about

**Comment by greyson-signal** [comment]
This was an unintended side-effect of adding notification channel support. I'll be fixing this shortly. Thank you!
