### ISSUE TITLE
Scroll to bottom button has a white background in the dark theme

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8127]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The scroll to bottom button has a white background in the dark theme

### Steps to reproduce
- Switch to dark theme
- open a chat and scroll a bit upwards
- the button appears

**Actual result:** The button has a white background
**Expected result:**  The button has a dark background and white arrows

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.24.8

Legacy issue: #6155

**Comment by greyson-signal** [comment]
Fixed in 040e1fe8f68d0f71360a86a27b340d64ab563196
