### ISSUE TITLE
[BUG] Camera preview includes status bar

### ISSUE THREAD

**Issue by Woodzrul** [signalapp/Signal-Android#8129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Camera preview when in Signal shows a coloured status bar.

### Steps to reproduce
- Launch Signal
- New or existing conversation
- Tap the camera icon in the area where you enter text
- Tap full screen button (bottom right)
- Coloured status bar is shown

**Actual result:** Whilst the camera works a coloured status bar shows at the top. Having the status bar does not show the complete view.
**Expected result:** Within multiple camera and other messaging apps the status bar would normally disappear (changes to expanded desktop mode).

### Screenshots
See attached. One image from the default camera where the status bar disappears off screen. Other image from Signal.
![camera](https://user-images.githubusercontent.com/23718359/44336603-debc2f00-a46f-11e8-9e95-690b751b09e2.png)
![signal](https://user-images.githubusercontent.com/23718359/44336605-debc2f00-a46f-11e8-8404-0f17bb5c1ef9.png)

### Device info
**Device: OnePlus 2
**Android version: 7.1.2
**Signal version: 4.25.2

**Comment by greyson-signal** [comment]
This is resolved in the new camera.
