### ISSUE TITLE
Group messages encountering a weak or broken connection fail instead of retrying

### ISSUE THREAD

**Issue by wizardofid** [signalapp/Signal-Android#8133]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

Despite b02dda405cbaf501a4ef7f3a61d8fb51374e7868 group messages fail when the connection is weak or broken.
### Steps to reproduce
- Find a place with a really weak (or missing) cellular signal and no WiFi
- Try to post a message into a group chat

**Actual result:** Group message fails after roughly a minute.
**Expected result:** Group message should retry for 24 h like one-to-one messages do.

### Screenshots
Sorry, none.

### Device info
**Device:** Fairphone FP2
**Android version:** 6.0.1
**Signal version:** 4.24.8

### Link to debug log
https://debuglogs.org/47452d90cdf7ac5e7d314b5de3b6863d71891d7bde0c8c8308f70d2ababf9103

**Comment by xyzzyxw** [comment]
I can confirm this bug. Easier way to reproduce:
- disable mobile data
- have bad connection to WLAN
- try sending a message to a group
The message may even be sent to some group members and fail for others.

**Comment by greyson-signal** [comment]
All of the retry logic for groups should match how individual messages are sent (i.e. retry for 24hrs) as of 4.30.x.
