### ISSUE TITLE
[4.25.4] Duplication of Sound entries in Android notifications

### ISSUE THREAD

**Issue by igor2x** [signalapp/Signal-Android#8134]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is duplication of settings in Android notifications for Signal app.

### Steps to reproduce
- Opening **Android | Settings | Apps & notifications | Signal | App notifications.**
-  In **Messages** section there is duplication of **Default** option and in **Other** section there is duplication of **Calls** option. THE PROBLEM.
- Note: Tapping either of **Default** options it opens the same **Signal . Messages** window. The same, tapping on **Calls** opens the same **Calls Signal** window. If opening the same window then in my humble opinion there is window redundancy.

I upgraded Signal from 4.24.8 to 4.25.2 and then 4.25.4.

**Actual result:** Opening Android notification settings in section *Messages* there are duplicate *Default* options. The same problem for *Other* section there are duplicate of *Calls*.
**Expected result:** There should be only single setting for *Messages* section | *Default* and *Other* section | _Calls_.

### Screenshots
![android_notifications](https://user-images.githubusercontent.com/10895030/44509297-a7d55b80-a6b1-11e8-98da-75a9de43bcd3.png)

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.25.4

### Link to debug log

Not applicable, because it is UI problem.

**Comment by igor2x** [comment]
I also tried:
1. Create a Signal backup.
2. Leave beta program.
3. Uninstalled Signal 4.25.4.
4. Installed Signal 4.24.8.
5. Restore database. Signal works fine. There are no Android notification channel for Signal app, as expected. So far no problem.
6. I deleted backups (big mistake).
7. Joined Signal beta program.
8. Installed Signal 4.25.4 and immediately when pressing Signal icon, Signal crashes. Now Signal crashes every time I tap on icon to start it with split second window opened "Signal keeps crashing".
9. I did Android | Settings | Apps & notifications | Signal | Storage. I selected _Clear cache_ and then _Clear data_.
10. Now Signal starts up successfully. But I have no data in Signal. Everything has gone (and me stupid deleting backups in step 6).
11. Now looking into _Android | Settings | Apps & notifications | Signal | App notifications_ and now in _Messages_ section there is single entry _Default_ and in _Other_ there is also single _Calls_ section.
13. I created a debug log if it helps.

**Debug log:**
https://debuglogs.org/e90601a871d84927519031b18eb242d514f82807d9c7c730d778aa159aef0567

**Comment by greyson-signal** [comment]
@igor2x Ok, so I think I know why you had all of those crashes. You created a backup on a newer version and restored it on an older version. Then, when you upgraded it again, it tried to do database migrations that already existed, leading to the crash. Right now we don't really support restoring newer backups on older versions, so we can table that for now as a separate discussion.

I'm more interested in how you got to a place where you have duplicates of some channels. Some questions:

- Did you have custom notifications for any conversations?
- Do you remember any non-default notification settings you had set in the app? Custom sounds, mutes, etc.
- Did you alter or disable the notification channels in the system settings in between upgrading from 4.25.2 to 4.25.4?
- Did you disable custom notifications for anyone before taking the screenshot? 

Some things that seem odd to me off the bat:
- One of the "Calls" channels is set to "Make Sound", but Signal never should have created a Calls channel like that.
- One of the "Default" messages channels is set to "No Sound", but signal never should have created a Default channel like that.

If you made any modifications to the channels, it'd also be awesome if you could tell me when the modifications were made (i.e. what Signal version). That might clear up some of those oddities I mentioned. 

Sorry, I know this is a lot of information to ask for. If it wasn't clear already, managing all of the notification channels is rather complicated :) And given that this looks to be a sort of migration issue, the more information I have, the better.

Thanks!

**Comment by igor2x** [comment]
> Did you have custom notifications for any conversations?

No.

> Do you remember any non-default notification settings you had set in the app? Custom sounds, mutes, etc.

Message notification sound to None.

> Did you alter or disable the notification channels in the system settings in between upgrading from 4.25.2 to 4.25.4?

Maybe, I don't know. I was playing with notifications heavily. If I remember correctly double notifications problem appeared after migrating from 4.25.2 to 4.25.4. It was working fine with 4.25.2.

> Did you disable custom notifications for anyone before taking the screenshot?

No, I don't remember I would.

> One of the "Calls" channels is set to "Make Sound", but Signal never should have created a Calls channel like that.

Maybe there is something related to "Priority only" pure Android setting. I was on meeting when Signal 4.25.2 was installed and on Android I pulled top-down and turned "Do not disturb" (turned off by default) to "Priority only", to not be disturbed by ordinary phone calls during meeting, but then I forgot to turn this off. I am pretty sure I have been testing Signal after this "Priority only" was turned on and I am pretty sure I migrated to 4.25.4 during "Priority only" selection was in effect. Don't know if this affects notification channels.

> One of the "Default" messages channels is set to "No Sound", but signal never should have created a Default channel like that.

When I am at work, I like to disable messages to not be disturbed by personal messages during my day job, so I like to turn messages channels to "No Sound", but I like to have LED light turned on. When I have time I look at the phone and see if LED light is on. That is why "No sound" is for messages channel.

> If you made any modifications to the channels, it'd also be awesome if you could tell me when the modifications were made (i.e. what Signal version). That might clear up some of those oddities I mentioned.

Most probably after upgrade from 4.25.2 to 4.25.4.

**Comment by greyson-signal** [comment]
Try as I might, I'm unable to reproduce this. I even have a 5X running Android 8.1. I've tried every combination of upgrade paths I can think of, including using different "Do not disturb" settings. It could be some weird system bug, I don't know. If you didn't disable any custom notifications, then "5 channels deleted" is exactly what should be there, but for some reason the "Calls" channel is still there twice, which is the most odd.

If someone is able to repro this and provide more information, please re-open this ticket. Thank you!

**Comment by haffenloher** [comment]
> when you upgraded it again, it tried to do database migrations that already existed, leading to the crash. Right now we don't really support restoring newer backups on older versions, so we can table that for now as a separate discussion.

@greyson-signal hasn't this been fixed already? I believe Moxie wrote somewhere that he'd added code that prevents restore of a backup with a DB version that is too high. Can't find it right now so maybe I'm imagining things.

**Comment by 2-4601** [comment]
I have this original issue with 4.32.8.

I currently have three duplicate notification channels for a certain contact.

I used to have just two but when I tried to fix it by removing the contact from my address book I ended up having three duplicates. Or one of the duplicates is labeled with the contact's phone number. The other duplicates have contact's name.

**Comment by 2-4601** [comment]
I'm on 4.33.0 now and it seems like [hardening](https://www.youtube.com/watch?v=unkIVvjZc9Y) the notification channels (e3b22dabcea044b5a7b8e3c5636bebdfa2e25a32) fixed this :tada:

**Comment by greyson-signal** [comment]
@2-4601 Ahh I had this issue in mind when I made that fix, but couldn't remember the issue number. Glad to hear it's fixed!
