### ISSUE TITLE
Video shared into Signal incorrectly identified as a .wav

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#8136]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The receivers cannot open my video. They see it as .wav

### Steps to reproduce
- make a video from the camera
- share it through signal
- receivers cannot open it

**Actual result:** they cannot see the video
**Expected result:** they should be able to see it

### Device info

**Device:** pixel 2 xl
**Android version:** 9
**Signal version:** 4.28.8

### Link to debug log

I will send it if it's necessary

**Comment by greyson-signal** [comment]
Hi there, if this happens consistently with videos you take with your camera, can you share a test video that's confirmed to have this bug?

Some starter questions:
- Are you using the default android camera app, or something else?
- What's the expected file extension of your video?
- How do you attach your video? Do you start in Signal, or do you click the "share" button in your camera app?
- When you attach a video, is it shown with the right file extension, or as a .wav?
- When you say the receivers cannot see the video, do you mean it shows up as a regular file attachment for them?

**Comment by leonardoporpora** [comment]
Yes it happens constantly.

. I'm using the default app of camera
. The expected file extension is .MP4
. I click share button in the camera
. Wrong extension .wav instead of .MP4
. Yes they see it as a regular file .wav they do not see the video

**Comment by greyson-signal** [comment]
Hmm, I have a Pixel 2 running Android 9, and I can't repro this. Could be an XL-specific issue, not sure. 

- Are you using any special camera settings? 
- If you share the same video to another app, does it get recognized properly?
- Does attaching the video work if you start in Signal and click the attachment button?

**Comment by leonardoporpora** [comment]
I have not modified the camera settings so they are the default one. 
From  telegram I don't reproduce this problem.
Attaching the video directly from signal I do not reproduce this issue

**Comment by Dyras** [comment]
Can you show me a pic of where you are pressing "Share" in the Camera App?

**Comment by greyson-signal** [comment]
I'm completely unable to repro this. Feel free to open if you can provide more details. For instance, we have a longer debug log history in 4.25.x. Thanks!
