### ISSUE TITLE
Own avatar not shown

### ISSUE THREAD

**Issue by LAfricain** [signalapp/Signal-Android#8137]
- [*] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [*] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [*] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I noticed that in the conversations my avatar qnd my name are not shown 
Relatede [issue](#7162)

**Actual result:** My own name and avatar is not shown
**Expected result:** My own name and avatar is shown

### Device info

**Device:** Wiko goa
**Android version:** 4.4.2
**Signal version:** 4.24.8

**Comment by moxie0** [comment]
Thanks @LAfricain, this is the intended behavior. For feature requests or discussion about existing behavior, please see the forums. Thanks!
