### ISSUE TITLE
After a couple of calls ok, when making or answering call, the other party does not hear me

### ISSUE THREAD

**Issue by vbspam** [signalapp/Signal-Android#8140]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes, after a couple of calls ok, when making or answering call, the other party does not hear me.
I need to restart the phone to fix this. Restarting just application does not help.

### Steps to reproduce
- Restart the phone
- Make couple of calls, answer couple of calls
- Answer or call one more call

**Actual result:** The call looks ok like any other call except the other party does not hear me. The cell/gsm call works ok, voice recording after this happens also properly records my voice.

**Expected result:** The Signal application should work properly all the time and not only sometimes.

### Screenshots
Not applicable

### Device info

**Device:** Samsung GT-S7582
**Android version:** 7.1.2 (LineageOS 14.1 - same version all the time I use Signal, no updates)
**Signal version:** 4.24.8 (installed from APK)

### Link to debug log
https://debuglogs.org/014f1beab4763a1c3f7fb4875a4a7205c4d8bdf8bd99b7b7c2a4c33b93907b33

### Observations
- this bug appeared approx on the beginning of 2018, it just started to drive me crazy when I started to use Signal more frequently as more my friends started to use it
- the first attempt of sending of debug log failed with message about failed network
- the network was however pretty ok that time (other apps ok, whole family run on it without complains)
- the call before the broken one has been interrupted by unknown source (happened only in one occasion)
- after restart, Signal works ok, the call to the other party is ok

**Comment by 211217613** [comment]
I've experienced something similar. When answering calls I can hear the other caller but the person I'm calling can't hear me. I've seen it happen with a headset and toggling speaker phone on then off helps.

**Comment by vbspam** [comment]
Updated my original report with debug log taken while the buggy call.

Observation:
- the first attempt of sending of debug log failed with message about failed network - the network was however pretty ok that time (other apps ok, whole family run on it without complains)
- the call before the broken one has been interrupted by unknown source
- after restart, Signal works ok, the call to the other party is ok

**Comment by Wikinaut** [comment]
@vbspam Pro-Tip: you can re-edit, i.e. correct, also the issue title, which currently has a typo in it.

**Comment by haffenloher** [comment]
> the call before the broken one has been interrupted by unknown source

What does that mean exactly? Did the call just disconnect and Signal returned to the conversation screen? Could you maybe capture a debug log right after one of these interruptions that cause problems with subsequent calls?

**Comment by vbspam** [comment]
> What does that mean exactly? 
The call stopped.

> Did the call just disconnect and Signal returned to the conversation screen? 
Yes

This is just behavior I noticed once. The issue occurs also without any previous signs of unexpected behavior.

**Comment by vbspam** [comment]
Issue appeared aggain  https://debuglogs.org/60a007838fe8f6e2d2976dabbd20dba1167f9c1fadc4b951c9700d169b841c20
V

**Comment by azuredusk10** [comment]
I'm experiencing a similar problem. 
When I answer a voice call, the other person can't hear me until I toggle speakerphone on then off. 
It's happened 3 times now.

**Comment by Wikinaut** [comment]
Works for me.
