### ISSUE TITLE
Call screen layout sometimes broken

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8141]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every now and then, the layout of the Signal call scren is broken. Most importantly, there is no "end call" button anymore. Sometimes the layout gets restored correctly after e.g. entering the homescreen and getting back to the call screen again.
Unfortunately, I am note able to reproduce this issue on purpose, but it happened about 10 times during the last months.

### Steps to reproduce
- Do a regular signal call (phone to ear; no speaker, no video)
- After some time, look at the phone
- Most of the times, everything is ok, but sometimes it isn't.

**Actual result:** Broken layout, i.e. no contact name, no phone number, most importantly no "end call" button. The contact image is still shown (black area in screenshot), but with some white surrounding area.
**Expected result:** Correct call screen layout.

### Screenshots
![broken_layout](https://user-images.githubusercontent.com/23025712/44633850-4f1df100-a945-11e8-89b3-42417709955a.png)

### Device info

**Device:** Motorola Moto G5
**Android version:** 7.0
**Signal version:** 4.25.5

### Link to debug log
https://debuglogs.org/ea6c66cd958e645e74e7ed782fd14a894c1afe5ca7fad21e004402afe55a69ed

**Comment by 211217613** [comment]
Gonna go ahead and throw this one in the mix. Missing answer call button and animation. 

![image](https://user-images.githubusercontent.com/7006850/45906051-8eeec180-bda7-11e8-8053-50070f3d5987.png)

**Comment by RiseT** [comment]
For an additional log see above ("Answer/Deny Call button not present").

**Comment by Sgn-32** [comment]
Should be solved with the new calling UI from 4.60.

**Comment by minnmann** [comment]
I guess so, too. Closing.
