### ISSUE TITLE
cannot upload videos

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#8142]
Hi I have a Pixel 2 XL and with that phone is impossible for me to share videos because if they are longer than 40 seconds due to they size ... May you increase it?

**Comment by greyson-signal** [comment]
We don't have any plans to increase the attachment upload size. Also, we reserve Github for bug reports, not feature requests. If you want to discuss features, please use [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). 

In the future, please use the template that is pre-populated when you create a new issue. Thanks!
