### ISSUE TITLE
Signal crashes when opening the external camera

### ISSUE THREAD

**Issue by aleb2000** [signalapp/Signal-Android#8144]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening external camera doesn't work.

### Steps to reproduce
- Open Signal
- Go to any chat
- tap on the "+" button
- tap on the camera button

**Actual result:** A blank screen appears for a few seconds, then the app crashes and I'm back to the conversation list
**Expected result:** The external camera opens, allowing me to take pictures.

### Device info

**Device:** Huawei P8 Lite (2017)
**Android version:** 8.0.0
**Signal version:** 4.25.6

### Link to debug log
https://debuglogs.org/a0493230b6c8cea3b524e285234465822e322af036f0545d11be623829a79743

### Other info

I have came to the conclusion that the problem is caused by the device setting of using the external SD drive as default storage, mainly because when switching back to the device's internal memory the feature works as expected. I also believe this issue is correlated with this (https://github.com/signalapp/Signal-Android/issues/7726) and this (https://github.com/signalapp/Signal-Android/issues/8118) issue: the reason being that I too cannot change my profile picture, however when switching to the internal memory I was able to do that too. As such the problem is probably caused by how Signal access the device's storage.

**Comment by aleb2000** [comment]
After opening the issue I cloned the repository and tried debugging it myself, I've found out that the issue (as well as the issues I linked in the "Other info" section) are solvable by adding to the file "res/xml/file_provider_paths.xml" the line `<external-path name="external_path" path="."/>`

**Comment by greyson-signal** [comment]
@aleb2000 Thanks for digging into this! I've confirmed the problem on my Huawei Mate 10 Lite, and I've confirmed this solves the issue. `PersistentBlobProvider` ends up creating files in the root of our private storage on the external SD card, but was missing this rule to allow it to generate a URI for said file.

Thanks again!

**Comment by greyson-signal** [comment]
This will be fixed in 4.26.
