### ISSUE TITLE
Custom notification sound setting no exist

### ISSUE THREAD

**Issue by msiweka** [signalapp/Signal-Android#8147]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Custom notification sound setting no exist. 
In my phone I don't have notification channels setting, so now I have same sound as system notification.

### Device info
**Device:** EML-L29 (Huawei P20)
**Android version:** 8.1.0
**Signal version:** 4.25.6

**Comment by greyson-signal** [comment]
Hi there! So I don't have an Android 8 Huawei device. Do you mind sending screenshots of the system notification settings page for Signal? On my Huawei Mate 10 Lite running Android 7, I can get to that via:

Settings App > Apps > Signal > Notifications.

Obviously Android 7 doesn't have notification channel stuff there, but if you could send me what you see that'd be super helpful.

Also, can you send me a debug log taken after you enable custom notifications for a conversation? And when you try to navigate to the system settings? Basically after clicking these two things:

![signal-attachment-2018-08-29-091409](https://user-images.githubusercontent.com/37311915/44800719-f3817c80-ab6b-11e8-8678-9de4ff62f7c2.jpeg)

If Huawei has actually stripped notification channels from their version of Android 8, then hopefully there's something in the log that we can use to detect that scenario.

Thanks!

**Comment by greyson-signal** [comment]
@snaggen 
> Huawei have notification channels if you go to Settings App > Apps > Signal > Notifications

Ok that's good to hear!

> If you click on the System Notification Setting in signal you seem to get to the standard channel setting.

There's two places you can click a button labeled "System notification settings" in Signal, so lemme just say what should happen and you can confirm if it's working as intended.

If you go to the global notification settings via:

Conversation List > Three-dot menu > Settings > Notifications

Then when you click "System notification settings" you should go to a channel called "Default" that describes the default message notification settings.

If you go to a conversation-specific setting via:

Conversation > Three-dot menu > Conversation settings

And enable "Custom notifications" and then click "System notification settings" you should go to a channel that has the same name as your conversation recipient.

Let me know if that's working as intended. If not, please take and post a debug log. Thanks!

**Comment by greyson-signal** [comment]
@msiweka  @snaggen Can I get an update on this? I don't have a Huawei 8+ phone, so I just need some confirmation. It's a pretty serious issue if some devices have removed notification channels.

**Comment by greyson-signal** [comment]
Shoot, ok, I think I understand now. Through other research I've confirmed that Huawei does have notification channel support, but it appears there may not have a "notification sound" option in the channel settings.

This puts us in an interesting spot. Let me think about what the best way to address this would be.

**Comment by greyson-signal** [comment]
So basically I migrated the sound + vibrate setting back into the app like it was before, instead of linking out to the system to change those settings. It's more work to keep the two settings in sync, but this should allow everyone to be able to set custom sounds. Try it out in the next beta (4.25.7). Thanks!
