### ISSUE TITLE
Prefs file security

### ISSUE THREAD

**Issue by elflng** [signalapp/Signal-Android#8149]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
The registration pin and backup password are stored unencrypted in the prefs file.

### Steps to reproduce
- open org.thoughtcrime.securesms_preferences.xml
- read all sensitive information
- defeat the purpose of registration locks and backup passwords
- profit

**Actual result:** Read everything that shouldn't be readable.
**Expected result:** At the very least, obfuscate slightly, or store encrypted in a db.

### Device info

**Device:** Sony Xperia Z3+ 
**Android version:** 7.1.2 (LineageOS 14.1/nightly)
**Signal version:** 4.25.6

**Comment by johanw666** [comment]
You can read that file on someone else's phone outside the app only when you have root access on their phone. If you have root access, you can do all kind of other nasty trics which are much more dangerous like intercepting keyboard input or making hidden screenshots.

If you have root and read it on your own device, I don't see the problem. I can already access my own messages.

**Comment by greyson-signal** [comment]
@johanw666 thank you for responding, all of that is accurate. It's also worth pointing out that on Android M+, we use the [Android keystore system[(https://developer.android.com/training/articles/keystore) to generate keys to encrypt certain critical data before storing it in shared prefs.

**Comment by elflng** [comment]
@greyson-signal So why aren't the backup pw and notification pin considered critical?
