### ISSUE TITLE
Misleading wording when changing profile picture or name

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8150]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The skip/cancel button in the profile create activity is always ["Set later"](https://github.com/signalapp/Signal-Android/blob/master/res/layout/profile_create_activity.xml#L108). This is ok during the initial setup, but when a user goes to the settings and opens this activity, it should be "Cancel". The user might think, that "Set later" removes the current name and picture and he can set them later again.

### Steps to reproduce
- Open settings
- Open profile create activity

### Screenshots
Not needed

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2
**Signal version:** 4.25.6

### Link to debug log
Not needed

**Comment by greyson-signal** [comment]
I think "set later" is an acceptable label still.
