### ISSUE TITLE
Documents name not readable in dark theme

### ISSUE THREAD

**Issue by Dafnik** [signalapp/Signal-Android#8151]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the documents tab in a contact the document name text isn't visible (Black on black)

### Steps to reproduce
- Switch to dark theme
- Go into a chat
- Tab on the name of the person
- Tab on Shared media
- Tab on DOCUMENTS

**Actual result:** You just see the icons and the time stamp
**Expected result:** You should also see the name

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/16242839/44845283-631b6880-ac4d-11e8-95ee-bb47d334e40d.png)

### Device info

**Device:** Oneplus 3
**Android version:** 8.1.0
**Signal version:** 4.25.6

**Comment by aleb2000** [comment]
In `res/layout/media_overview_document_item.xml` there aren't these 2 lines inside org.thoughtcrime.securesms.components.DocumentView:
`app:doc_titleColor="?conversation_item_received_text_primary_color"
 app:doc_captionColor="?conversation_item_received_text_secondary_color"`
On the other hand they are present in `res/layout/conversation_item_received_document.xml`, `res/layout/conversation_item_sent_document.xml` and `res/layout/conversation_activity_attachment_editor_stub.xml`.

**Comment by greyson-signal** [comment]
Fixed in 4.26
