### ISSUE TITLE
Cannot Close Signal App

### ISSUE THREAD

**Issue by trymeouteh** [signalapp/Signal-Android#8152]
Lately I am unable to close the app. I have a Samsung Galaxy S8 an when I press the windows button (Bottom Left) and then swipe the Signal app window to close it or tap the X on the Signal app window it will close the app and reopen it again.

It only does this half the time and I have had this issue for a few months. It is a minor bug so no rush when looking into it.

**Comment by greyson-signal** [comment]
We don't have any control over the system's task switcher. Sounds like a bug on their end.
