### ISSUE TITLE
Typography: Arabic Font Used for Persian/Farsi

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8153]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Although this issue is not specific to Android (it's the same on iOS and Desktop), I understand the change must begin from here.
The current font used is not Farsi/Persian, it's Arabic. I have previously suggested some alternative fonts on this issue in the [Signal Community](https://community.signalusers.org/t/more-sophisticated-farsi-persian-font/) and [Signal-Desktop's Github](https://github.com/signalapp/Signal-Desktop/issues/2648).
This font is not used at all in contemporary Persian Media, Books etc.

### Steps to reproduce
- Type in with a Persian/Farsi Keyboard

**Actual result:** Here's how currently Persian looks in Signal:

![image](https://user-images.githubusercontent.com/34171942/43855773-ec4dbd7c-9b5b-11e8-94a5-1397bce5200b.png)

**Expected result:** As alternatives I suggest the current font used by Twitter (“Segoe UI”, Arial, sans-serif):

![image](https://user-images.githubusercontent.com/34171942/43855880-311d6b8c-9b5c-11e8-865f-d29d2d497ee2.png)

### Device info

**Device:** Nokia 3
**Android version:** 8.0.0
**Signal version:** 4.25.5

**Comment by khashyarkh** [comment]
@mrphs
I would love to hear your suggestions.

**Comment by Xashyar** [comment]
This issue only exists in Signal-Desktop.
