### ISSUE TITLE
Allow different kinds of identifiers for registration 

### ISSUE THREAD

**Issue by unbranched** [signalapp/Signal-Android#8157]
This is a reference to the closed issue #1085 , please reopen it and take it in serious consideration if you want your app to be the reference of secure IM. Otherwise you'll forever be a off-limits app for many people.

**Comment by greyson-signal** [comment]
As stated in the issue template, we reserve github for bugs. I encourage you to discuss this on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
