### ISSUE TITLE
[BUG] Quick reply from Phone app

### ISSUE THREAD

**Issue by Woodzrul** [signalapp/Signal-Android#8158]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When given the option to quick respond to a telephone call via SMS, message does not appear within Signal. Seems to store in the local Messaging database.

### Steps to reproduce
- You receive a telephone call
- You cannot answer right now so send a predefined quick response SMS from within the Phone app. E.g. Can't talk right now.
- Message sends perfectly fine
- Message does not appear within Signal
- Install an SMS app (QKSMS, Messaging)
- Quick response message shows even though the SMS app is not set as default

**Actual result:** SMS appears to save into the local Android SMS database and not Signal.
**Expected result:** Despite sending an SMS from the Phone app, it should appear within Signal.

### Device info
**Device:** OnePlus 2
**Android version:** 8.1.0 (LineageOS & AOSP)
**Signal version:** 4.25.6

**Comment by jlund-signal** [comment]
This is related to #7634 and #7627. Sadly, we're not aware of any API that would allow for this type of interaction with the system SMS database to occur in a reliable way.
