### ISSUE TITLE
[Bug] Backup fails with no visible error during specific storage conditions

### ISSUE THREAD

**Issue by davidsuart** [signalapp/Signal-Android#8159]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Per: https://github.com/signalapp/Signal-Android/issues/8054 .. This appears to be the same symptoms (Signal is unable to create a backup and no visible error is presented to the user) but with a documentable solution:

### Steps to reproduce
- Settings > Enable the backup feature
- Follow the tool-tip steps (Save security numbers)
- Manually invoke "Create Backup"
- An icon momentarily flashes in the notification bar and instantly disappears
- Signal displays no error to the application user

**Actual result:** Nothing happens
**Expected result:** A backup should be created or an error displayed

### Link to debug log
adb logcat:
```
[..] I ChatsPreferenceFragment: Queing backup...
[..] I LocalBackupJob: Executing backup job...
[..] W JobConsumer: null
[..] W JobConsumer: org.thoughtcrime.securesms.database.NoExternalStorageException
[..] W JobConsumer: 	at org.thoughtcrime.securesms.util.StorageUtil.getBackupDirectory(StorageUtil.java:21)
[..] W JobConsumer: 	at org.thoughtcrime.securesms.jobs.LocalBackupJob.onRun(LocalBackupJob.java:57)
[..] W JobConsumer: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.runJob(JobConsumer.java:74)
[..] W JobConsumer: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.run(JobConsumer.java:47)
```

### Environment
Android 7.0, "Internal Storage", no Signal folder (AKA: `/sdcard/Signal`) was already present and Signal was unable to create one.

### Supplementary info

**Cause**: Even though Signal messenger is assigned the correct android "storage" permission (Which subsequently passes the [`Manifest.permission.WRITE_EXTERNAL_STORAGE`](https://github.com/signalapp/Signal-Android/blob/f9adb4e4554a44fd65b77320e34bf4bccf7924ce/src/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L47) check in `jobs.LocalBackupJob.onRun()`), for some reason it cannot read or write to the storage, and it seems that when `onRun()` encounters an error it is falling back to the default `NoExternalStorageException`.

**User solution**: Force closing Signal messenger > go to Android app settings > Signal > Permissions > Disable storage > Exit and re-open settings > Re-enable Signal storage permission > Re-open Signal messenger > Run backup > Success

**Application solution**: Extending the error handling seems to have been considered in: https://github.com/signalapp/Signal-Android/issues/8054#issuecomment-409293924
 ... To further that idea, perhaps wrapping [File tempFile = File.createTempFile("backup", "tmp", StorageUtil.getBackupCacheDirectory(context));](https://github.com/signalapp/Signal-Android/blob/f9adb4e4554a44fd65b77320e34bf4bccf7924ce/src/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L70) in it's own if/try condition would help isolate this behaviour from the more generic `NoExternalStorageException`.

**Comment by greyson-signal** [comment]
For whatever reason, it looks like `Environment.getExternalStorageDirectory()` is considered non-writable.

> To further that idea, perhaps wrapping File tempFile = File.createTempFile("backup", "tmp", StorageUtil.getBackupCacheDirectory(context)); in it's own if/try condition would help isolate this behaviour from the more generic NoExternalStorageException.

That's not what's throwing the exception here. To quote your logs:

```java
W JobConsumer: org.thoughtcrime.securesms.database.NoExternalStorageException
W JobConsumer: 	at org.thoughtcrime.securesms.util.StorageUtil.getBackupDirectory(StorageUtil.java:21)
```

This is happening when trying to create our backup directory on external storage. So I don't think we need to restructure our exception handling or anything.

I do agree that we need better user-visible errors during backup.

Also, do you mind sharing what device and OS you're running? We usually only see this kind of storage permission stuff with rooted phones. Just want to make sure that's still the case. Thanks!

**Comment by davidsuart** [comment]
Yes, agreed, I see that `StorageUtil.getBackupCacheDirectory(context))` isn't throwing the exception, yet given the fix was to disable and re-enable the storage access permission of the Signal Messenger app in Android (Not making any modifications to the storage contents), it seemed plausible(?) that any attempt to write to storage could be likely to trigger an exception (As neither call is wrapped in a condition it would be the generic fallback exception), so if you are going to modify one of these calls already, perhaps both the calls to `getBackupCacheDirectory` _*and*_ `getBackupDirectory` could be wrapped in if/try conditions to be thorough?

"Thorough" seems an advisable approach because the earlier [if (!Permissions.hasAll(context, Manifest.permission.WRITE_EXTERNAL_STORAGE))](https://github.com/signalapp/Signal-Android/blob/f9adb4e4554a44fd65b77320e34bf4bccf7924ce/src/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L47) doesn't appear to be catching this problem on it's own, hence the unresolved #8054  and also this report #8159

The device was Samsung S7, Android 7.0, not rooted but by no means a "clean" test environment.

I no longer have this environment for further testing and the suggestions above were to make UX for future users a better experience. Feel free to to close this bug report if the justification or resource is not sufficient to carry it through to implementation.
