### ISSUE TITLE
Signal Android is taking too much space 

### ISSUE THREAD

**Issue by Konotori** [signalapp/Signal-Android#8160]
- [x] I have searched to the best of my ability open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Android Signal app takes way too much space on the phone. After going through all my contacts one by one and deleting all media I managed to clear out 100MB, which left the app's data with 450MB (not including the 66.5MB of the app itself). I have used Signal for quite a while but this seems to me way excessive for just storing textual data.
In comparison, my desktop app takes 223MB (or 337MB; for some reason I have a second desktop signal folder), including everything (software + data). My history with the desktop app is somewhat shorter, but this storage includes that of the media which I haven't deleted, i.e, those pictures that on the mobile app took up 100MB of storage.
It seems to me that either the Android app uses a different and much less storage-efficient encryption than the desktop client, or otherwise mishandles storage allocation. Given that the app doesn't let one move the installation to an external storage (why not I don't understand, but that's another issue), and that my internal storage is rather sparse, that's a pretty big problem. 

Thank you.

### Device info
**Device:** Samsung J5
**Android version:** 6.0.1
**Signal version:** 4.24.8 (just upgraded from 4.20.X, if that matters)

**Comment by tuxayo** [comment]
How much space does the backup takes? Do a backup and check [internal_storage]/Signal/backup

**Comment by tuxayo** [comment]
Is your current install the result of an imported backup?

**Comment by tuxayo** [comment]
And how much data storage is reported in the app info?
You should see, Total, App, Data

**Comment by Konotori** [comment]
@tuxayo Ok, it's my bad. Before posting I had thought that maybe the backups were counted within the storage so I disabled the backuping. Toggling it off prompted a question, asking whether to disable and delete all backups, and I hit yes. I hadn't assumed that Signal might not have deleted them, but it was exactly the case (this might have to do with the blessed transition from the obvious "thoughtcrime" folder to the "Signal" folder). Deleting those backups now freed the quoted storage of the app, which was also a bit confusing since Signal is registered as being on the internal memory while the backups were on an external memory.
And speaking of which, the new backup I made upon your prompt was saved on the internal memory. I think I have read somewhere yesterday that Signal stopped putting the backups on the external card (is that the case?), but in the app the toggle reads "backup chats to external storage". But that's another issue.

**Comment by Konotori** [comment]
@tuxayo I guess this issue is settled, the data now is "108 MB". Is it the encryption that makes only text take so much storage?

**Comment by tuxayo** [comment]
> I have read somewhere yesterday that Signal stopped putting the backups on the external card (is that the case?),

yes

https://github.com/signalapp/Signal-Android/issues/7845#issuecomment-401479547

**Comment by tuxayo** [comment]
> Is it the encryption that makes only text take so much storage?

No :)

https://stackoverflow.com/questions/93451/does-aes-128-or-256-encryption-expand-the-data-if-so-by-how-much
