### ISSUE TITLE
very loud "gong" when call connects

### ISSUE THREAD

**Issue by ghosted17** [signalapp/Signal-Android#8165]
I am getting a very loud call connect sound like the issue closed in #4988

Version 4.25.6

**Comment by greyson-signal** [comment]
Can you tell me what device and OS version you're running? I've used Signal calling on many different phones, and I've never had a problem with the volume of the connection sound.

**Comment by ghosted17** [comment]
Device is Samsung Note8. I also tested it on my girlfriends Note8 and the same thing is happening.

There both on stock Oreo 8.1 with latest ota updates.

**Comment by greyson-signal** [comment]
The closest thing I have is the S9. It's true that, at max call volume, the 'gong' can be quite loud, but if I have the volume that high, even the sonar sound is uncomfortably loud. So I guess in that case, I just wouldn't want to have my phone at max call volume period.

What's your call volume?

**Comment by ghosted17** [comment]
I have tried with in call volume at lowest and it makes no difference to the ding sound. It's loud as f.

**Comment by TheBicPen** [comment]
I am having this issue as well, on a Samsung galaxy a8. Even with the call volume set to minimum, the sound is extremely loud.
Steps to reproduce: 
Call a signal contact.
When the call connects, the beep is extremely loud.

**Comment by TheBicPen** [comment]
Here's my [debug log](https://debuglogs.org/a0b80c431d248f61db39c32416bc09a77837a17e970a05a8a3df8fe9ef6b6115) . I just tested it with my media volume being set to almost the minimum, and all other volumes at minimum or off.

**Comment by ghosted17** [comment]
All media is low and not a settings problem. It's so loud that I have to always remember to hold the phone way away from my ear

**Comment by haffenloher** [comment]
A forum user reported having this issue with a Samsung S8+, apparently using the stock OS:

https://community.signalusers.org/t/signal-calling-connect-sound-way-too-loud/5833/4

**Comment by ghosted17** [comment]
I thought I would try signal again but this issue still persists. Please just add an option to make it vibrate instead of make a sound when connected

**Comment by TheBicPen** [comment]
I think the issue is present on all "call connect" sounds for any app on Samsung phones. I suspect this because it happens in WhatsApp as well. A workaround for this would be alternative notifications for a call connecting, like @ghosted17 suggested

**Comment by ghosted17** [comment]
Yeah like Wire, it just vibrates. sadly I have to move away again because my ears can't take this loud sound. I will recheck again in a few months. Or if anyone has a hack on how to remove the sound I'd be interested.

**Comment by greyson-signal** [comment]
I sat the ringing sound and the call connect/disconnect sound next to each other in audacity and lowered the amplitude of the connect sound to match the ringing sound. 

That means that if you're comfortable with the volume of the ringing sound, then the connect sound shouldn't be surprising.

**Comment by ghosted17** [comment]
@greyson-signal where is the file stored?

**Comment by greyson-signal** [comment]
@ghosted17 https://github.com/signalapp/Signal-Android/tree/master/res/raw (webrtc_completed.mp3 and webrtc_disconnected.mp3)

**Comment by ghosted17** [comment]
@greyson-signal I mean life after it's installed can you access it or I need root?

**Comment by greyson-signal** [comment]
There's no reasonable way to access it. It's a `raw` resource that's part of the APK. I also have no idea what you're trying to do. The change I made is in beta. I encourage you to try it.

**Comment by ghosted17** [comment]
@greyson-signal I'm in the latest beta. I'll give it a try. I was jist thinking maybe I could just delete the audio file after it's installed, makes updating easier.

**Comment by ghosted17** [comment]
After testing the latest betas the sound has improved and is not as loud as it used to be. It would be perfect if you could turn it down just a touch more. Say from 100% to 90%

**Comment by ghosted17** [comment]
@greyson-signal After testing the latest betas the sound has improved and is not as loud as it used to be. It would be perfect if you could turn it down just a touch more. Say from 100% to 90%

**Comment by ghosted17** [comment]
This issue is back again. It's bloody loud
