### ISSUE TITLE
Group-Messages not received until private messages sent on Huawei P20 Pro

### ISSUE THREAD

**Issue by 0xnor0** [signalapp/Signal-Android#8166]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages, which are sent from my OP5 (in groups) are not transported to the contacts device (Huawei P20 Pro) until i sent private messages. All other contacts (Galaxy S7, OP1) received all messages without delay.

### Steps to reproduce
- Sent some Messages to the contact via group-message
- the contacts device receives no messages/notifications (or with some delay, from time to time only after a few days!)
- sent a private message to the contact
- all previous messages get received by the other contacts device

**Actual result:** messages will not be transmitted to the contacts device
**Expected result:** messages will be received by the contacts device

### Device info
**Device:** Huawei P20 Pro
**Signal version:** 4.24.8

### Link to debug log
OP5: https://debuglogs.org/3e9343cdb841227873ddcdb36d40859636686e464fb767eea99e4ab3b8030840
P20Pro: https://debuglogs.org/1b15f5b7ec62bce5f91baa9e56e4af0293411edeb481443e3c24852b3d388905

**Comment by greyson-signal** [comment]
When another "problem message" occurs in your group chat, can you long-press the message and go to the message details screen by pressing the "i" button on the toolbar? From there, check the delivery status and report back what you see. This should help us determine if the problem is on the sending or receiving side. Thanks!

**Comment by greyson-signal** [comment]
I should emphasize that you want to check the delivery status after the message has been sent from your perspective, but before the recipient has received it from their perspective.

**Comment by 0xnor0** [comment]
Thanks for your reply @greyson-signal.

The delivery status in Signal Desktop shows no icon, in my Android App the delivery status shows one checkmark.
The receiver sometimes receives the message Not until i wrote another private message or some days eslapsed.

**Comment by 0xnor0** [comment]
The issue still exists. 
Messages will only be received if the receiver opens Signal.

**Comment by greyson-signal** [comment]
If the problem is that the receiver needs to open signal, then it's likely a system settings issue with overzealous battery optimizations. You can check out our support article for manufacturer-specific tips. 
https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications
