### ISSUE TITLE
Alerts playing on Signal-Android while actively using Signal-Desktop. Some alerts more than once per message received.

### ISSUE THREAD

**Issue by SingerGuy** [signalapp/Signal-Android#8167]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While using Signal Desktop (SD) in-focus on a specific contact I should not receive sound alerts in Signal for Android (SA) for messages received from that same contact. Sometimes this works correctly, but sometimes when I have a custom alert tone for a contact I will receive one or even two alerts on SA if the app is out-of-focus for that contact. I have even had it where the first, custom alert, is interrupted part way through the sound file and the default alert plays as the interrupting second sound. It is not consistent. I had my wife send me six messages in a row and saw (1) no alert on SA, (2) one custom alert, (3) double custom alerts, and (4) one custom alert interrupted by one default alert.

### Steps to reproduce
- Launch SD and click on contact so that person is active/in-focus.
- With SA out-of-focus (phone on, app not active) have contact send message. **OR**
- With SA in-focus but showing the list of contact messages, not inside the specific test contact, have contact send message.
- Monitor the type of alert displayed by SA.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Inconsistent results. Sometimes there is no alert, sometimes one alert, sometimes two alerts, sometimes two different alerts. (See bug description)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- With the contact active in SD, regardless of the state of SA, there should not be an alert tone on the phone. This was the way it has worked for the year or so I have been using SD (was a very early implementer).

### Device info
**Device:** samsung SM-G930V (heroqltevzw)
**Android version:** 8.0.0 (G930VVRS4CRG2, R16NW.G930VVRS4CRG2)
**Signal version:** 4.25.6

### Link to debug log
https://debuglogs.org/b113d79719a50f175cd72cc15e186b8abe55ff3ad8154b1058c4131a2e4b6e95

**Comment by SingerGuy** [comment]
##Second debug log
Had a message come in from a contact with a custom alert and captured the log immediately this time.
https://debuglogs.org/74a80f1d2f4da71ae657302c5d144fae2e680861d7ca9a2edebd7656222516da

**Comment by SingerGuy** [comment]
When I have a contact with no custom notification setting who replies to an MMS conversation (non-Signal but handled by Signal since it is my default messaging app) I get a double alert tone. I am guessing that the first alert is the message landing in their individual conversation and the second alert is when it is moved into the MMS group chat. I have a separate MMS group chat going on where one of the people in the group has a custom alert sound and with that person I hear their custom sound for a second or two of play time and then it is interrupted by the default alert sound that would occur for the group. Here is a log from immediately after one of these double MMS alerts:
https://debuglogs.org/b1f31cf257ab25916cc84ce0401259b21fae5759aa838739cbf50d01ecf50d1e

**Comment by jlund-signal** [comment]
This should be resolved in version 4.25.9. Thanks for the bug report!
