### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#8168]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When a new message arrives, my phone vibrates and for a few seconds the app's name "Signal" is shown on my phone's notification bar (albeit the icon is missing). The notification is not persisting in that there's no icon on the notification bar and when I pull down the notification bar there's no entry at all. 
When I open up the conversation list in Signal, the newly arrived message is displayed in bold to indicat an unread status.

### Steps to reproduce
- Use Signal 4.25.6
- Use Android 9
- Receive a message

**Actual result:** A notification is only shown for a few seconds, without an app icon. No noitification on expanded notification center.
**Expected result:** The notification should contain the app icon and the icon should be staying on the notification bar until the notification is discarded. When the notification bar is expanded, there should be a card with name, user image and content (depending on settings) which takes you to the converstation.

### Screenshots

Please note that in this screenshot there's the app icon missing from the notification in the top left corner.

![screenshot_20180903-121218](https://user-images.githubusercontent.com/206281/44982149-2ca75b80-af75-11e8-9fda-869aa79577da.png)

### Device info

**Device:** Google Pixel (sailfish)
**Android version:**  9 (4898911, PPR1.180610.009)
**Signal version:** 4.25.6

### Link to debug log
https://debuglogs.org/aceadbb7d973a0712cc700c8040251e7d77ec7a2e63732d5e764b89d7f347712

**Comment by greyson-signal** [comment]
Do you have a linked desktop instance that may be foregrounded? It's possible that the notification is being shown, but then immediately being marked read on desktop.

**Comment by jnns** [comment]
No, there's no linked desktop app which could consume the notifications.

I also noticed that when the display is off, it's normally waking up into a screensave-like mode which only shows the current time and the new notification. But now, when I reveive a new Signal message, the display is woken up to only display the time – nothing else.

**Comment by greyson-signal** [comment]
Just to be clear though, there is a linked desktop, yes? Your log shows that we're doing multi-device contact sync and stuff. Just verify by going to Settings > Linked Devices.

Next, can you check your channel settings for the Default messages channel? Maybe the priority got set to be lower somehow, which may cause it not to pop-up on your screen or make a sound?

**Comment by jnns** [comment]
Yes, there has been a linked device that hasn't been in use for a few weeks now. I now removed it from the list of linked devices to see if it changes anything. 

I didn't change any notification settings. Everything seems to be as it should. 

![screenshot_20180904-083632](https://user-images.githubusercontent.com/206281/45014360-90d22a00-b01e-11e8-8813-87d2b9983688.png)

![screenshot_20180904-083812](https://user-images.githubusercontent.com/206281/45014369-99c2fb80-b01e-11e8-90b9-71aad594b2d8.png)

**Comment by greyson-signal** [comment]
@jnss Did you previously have any custom notifications set for specific people? And then restore from a backup? There was a bug that was fixed that could cause you to miss notifications after a backup restore due to notification channels not being reconstructed properly.

**Comment by jaytheletterj** [comment]
Same issue as OP, worked perfect before the Android upgrade. Notifications from other apps working fine based on testing.

**Comment by jnns** [comment]
> Did you previously have any custom notifications set for specific people? And then restore from a backup?

No, I did not set any custom notifications although I did restore from a backup months ago. But the notification issue only appeared very recently.

Meanwhile the bug does not appear on my device again. A reboot and / or a Signal update seems to have fixed it (I am on the beta channel).

**Comment by rbclark** [comment]
I have not customized my signal notifications at all and I am seeing this behavior as well on a Pixel XL with Android 9. The application name flashes in the notification shade but no notification persists. If there is any more information I can provide I will be happy to.

**Comment by rbclark** [comment]
1. Pixel XL on Android 9 (fully up to date)
2. 4.25.10
3. No I do not
4. No I have not
5. Yes I do, however none of them are active when I have had the problem.
6. Restarting the device temporary fixes the problem however it re-manifests itself after a while.

**Comment by aaronshivers** [comment]
1. nokia 6.1, android 8.1.0
2. yes
3. no
4. no
5. yes, no
6. yes

**Comment by paul-chelarescu** [comment]
1. Xiaomi Mi5, Android 8.0.0
2. 4.26.2
3. No
4. No
5. No, even after connecting a desktop instance there is no difference
6. Yes, many times, notifications are never persistent

**Comment by greyson-signal** [comment]
@mborod When you notice the notification problems, can you snag and submit a debug log? Notification problems can have different root causes. If you have a linked desktop, it might be that you have the conversation open, and it's marking your messages as read as they come in, and maybe that's something we have to tweak on desktop. Or maybe you're having generic GCM issues that's causing push notifications not to be delivered at all. 

Hard to say without a debug log, so if you could send one that's taken within a couple hour of  you experiencing the problem, that'd be very helpful!

**Comment by Booteille** [comment]
I have the same issue. On LeEco LePro 3 AI (LEX657), Android 6.0.
Sound notifications are never played.

Here are the logs: https://debuglogs.org/fb37c7d95107a5a5688adca4e55952eba55c1fe40ac580c3afe47591f2dbf5bb

**Comment by gculling** [comment]
@greyson-signal I do not know if this issue was resolved elsewhere, but I am having this problem on my phone
1. What's your device and Android version? Pixel 3, Android 9(P)
2. Are you on the latest release? (4.25.10 at the time of posting) Yes, 4.30.8
3. Do you have custom notifications set for anyone? No
4. Did you do a backup-restore somewhat recently? Yes
5. Do you have a linked desktop instance? Is it active when you have this problem? No
6. Have you tried restarting the device? Helps but only temporarily, problem resumes after a few notifications.

Any suggestions?

**Comment by Booteille** [comment]
Can you provide logs please?

**Comment by gculling** [comment]
https://debuglogs.org/b490bd35151ece4f16915b3770da2116cd98d525960385a9edf231100e574468

**Comment by rogerkirkness** [comment]
1. Google Pixel 3, v9.1
2. Yes.
3. No.
4. No.
5. Yes, no.
6. Yes, doesn't help.

Logs: https://debuglogs.org/effaa0bee3cf6f274791f9b2a6015ca060dd16fb9c5d6d4b0120f15d345287d9

**Comment by burntcookie90** [comment]
Another case

https://debuglogs.org/3044a37e1d8ce3c4358cce342e4a04e43517f3586f91d10d263e4645f2e6c9ef

**Comment by torlarse** [comment]
Icon badge worked just fine on beta 4.31.4. Does not work in beta 4.31.5. 

My debug logs also seem to fail? Immediately after sending debug log, the link does not work in Firefox browser on device.

[https://debuglogs.org/f6a8df127125237ee84424f5386243be75c0be3bf0b10a46304a3ff6f32f304b](url)

**Comment by jnns** [comment]
The issue is back for me since a few days. It took me a while to notice it. When I receive a message, the display wakes up for a short period and displays the time but neither app icon nor message. When I unlock the screen and have a look at the notification center, there's no notification from Signal whatsoever. Only when I open the app I see that there's an unread message in the conversation list. 

It seems that this issue occurred again with one of the latest Signal updates. Since filling the issue three months ago I didn't have problems with Signal at all.

I didn't restart the phone yet but will do so after posting this. 

If you want to have a look at the debug log, please note that there should have been a notification for a message at 21:08 on Friday, 2018-12-14.
https://debuglogs.org/14db047795390bfbef93120891a27316e8407729fb20674ac81464fc1ddb0f59

**Comment by greyson-signal** [comment]
@jnns 

So I do see that we posted a notification at that time:

```java
2018-12-14 21:08:49.277 MEZ I MessageNotifier: Posted notification. Notification(channel=contact_+***********23_1539521335061 pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x201 color=0xff2090ea category=msg groupKey=messages actions=2 vis=PRIVATE)
```

(Don't read into the `sound=null` stuff -- all of the sounds and stuff are pulled from the notification channel instead of being set on the notification itself)

Are you able to see notifications from that contact in general, or did it just act funny this one time? Had you recently changed their custom notification sounds or anything?

**Comment by jnns** [comment]
The notification may be posted but the way it is displayed is very odd: 

> When a new message arrives, my phone vibrates and for a few seconds the app's name "Signal" is shown on my phone's notification bar (albeit the icon is missing). The notification is not persisting in that there's no icon on the notification bar and when I pull down the notification bar there's no entry at all.
When I open up the conversation list in Signal, the newly arrived message is displayed in bold to indicat an unread status.

When the phone is asleep when a message arrives, it either vibrates or rings and wakes up but there's no entry in the notification center. So notifications are posted but they don't appear to the user.

This behaviour is shown across all my Signal contacts, not just one contact in particular. It doesn't just act funny once; it's like that for at least four days now (since I posted to this issue again).

I didn't change any settings or set any custom notifications whatsoever. Apart from the recent Signal updates nothing changed. Although this isn't caused by a recent updated because it happened the first time in September.

A reboot does help and restores the expected notification behaviour.

**Comment by gculling** [comment]
@jnns Does the problem reoccur when you respond to a text message from the notification bar?

**Comment by jnns** [comment]
No, replying to a message via the notification doesn't cause the issue to re-appear. Everything's fine since the restart.

**Comment by burntcookie90** [comment]
Ok, so, this is a weird bug. I received a broken notification (no body, just the "Signal" in the top left) and opened the app to see the unread messages. I attempted to click on the top conversation in the list, but the click actually activated the system notification drop down. This leads me to believe the application is actually posting some sort of transparent notification that then clears itself.

**Comment by greyson-signal** [comment]
Please post a debug log.

**Comment by burntcookie90** [comment]
> Please post a debug log.

https://debuglogs.org/45f37a47d735c0f9e3d99e94f9c84177cc46227140633232b19896eeb7d78b91

nothing of value from when the message came in (~9AM EST)

**Comment by mborod** [comment]
Lots of requests for debug logs and suggestions that maybe people who said they weren't running the desktop app at the time actually were, and had the conversation in question open, so it snagged the notification.

First of all, if I have the desktop app open, even on the conversation in question, I still want the phone to make a notification sound, and the only way I don't is if you give me a preference setting for this circumstance and I set it to "off".

Second, there have been debug logs posted, and more than that, explanations of exact steps to reproduce the very problem reliably. Back when I was coding, developers / programmers were lucky to get that and were expected to solve problems before the weekend, not in whatever it's been now, like over a year I've seen this problem persist.

I'll check back on this issue again, eventually, but just want to say, I have a lot of cheaply produced apps on my phone that manage to produce push notifications without any problem. I think someone needs to take this module back to basics, start again maybe.

I hope Signal does work out this show-stopping issue, it would be nice to be able to use it. Heck I'd even pay something, if it worked reliably.

**Comment by bme13** [comment]
Hi,
To me this definitely seems to become a serious issue. I've had 2 conversations where I did only see a delivery status for several days and no read status. I also did not got a response to those messages. Just spoke one of them and he confirmed he only did see there was a message once he opened Signal. This afternoon I send a message to my SO and I also only see the delivered status and no read status. This lasted until we met and I checked the phone. The moment I unlocked the phone a notification sound was played and then there was a notification shown. I do realize this is not exactly the same behavior as others describe on this thread but it might be related. I've created a debug log and attached this. The message I send was at 15:13 and yes I see in the log on her phone a notification was generated. This was definitely not displayed until the phone was unlocked. My SO has android 8 device and the person I spoke to does also has android 8 on his phone. For the 2 other persons in the other conversation I'm not sure.
https://debuglogs.org/4d7b115458915b3fc79ee9eca80e214752316746f2b060c0e249a3bb818cfdbe

**Comment by bme13** [comment]
I've checked a few logs and with my little knowledge I was not able to find anything useful. Except in the log from burntcookie90 (https://debuglogs.org/3044a37e1d8ce3c4358cce342e4a04e43517f3586f91d10d263e4645f2e6c9ef) There I occasionally see the message "Empty notification state. Skipping". Based on the code I guess the cancelActiveNotifications is called since the bundled argument is false. From the description it seems that this cancelActiveNotifications also clears the current notifications. Is my understanding for that correct?
In order to provide additional information, would it be useful to add a notification logger e.g. as described [here](https://www.androidpit.com/how-to-recover-lost-notifications-on-android?c=2590754#comment2590754)

**Comment by cumber** [comment]
@lhassell For me, rebooting the phone seems to temporarily fix the issue. It seems to be a state the app gets into (once it starts happening it keeps happening), and it gets back into that state eventually, but restarting the phone makes notifications work normally again for at least a day or so (sometimes much longer).

**Comment by torlarse** [comment]
Consistently, Signal needs unread messages from more than one sender to trigger badge icon. No open desktop app.

Samsung Galaxy S8+
Signal 4.31.6 beta

https://debuglogs.org/cea7292c7b759da3bca76d8eaf71770c4879e732ca4e3fa569bf50ca25edd40b

**Comment by bme13** [comment]
Hi @torlarse. That is a different issue. See https://github.com/signalapp/Signal-Android/issues/7580. It will most likely be solved in the next release.

**Comment by TheGuad** [comment]
Had the problem again and after deleting the conversation, my alerts for all other conversations started working again.

**Comment by greyson-signal** [comment]
@TheGuad Did this just happen? Can you post a debug log?

**Comment by TheGuad** [comment]
I can't remember exactly when it happened and I have since deleted the conversation I was having when it did. I'll note date and time next time and submit another log. Deleting the conversation definitely fixed it for a long time though. 

https://debuglogs.org/74f46d2244013689c6126c2aea1047fa445179f9b6d58a25f8f49e6aea3e4ba8

**Comment by greyson-signal** [comment]
Since the discussion died down, there's been some work on Notification channels to add some new guarantees around channel accuracy and such. Also, anecdotally I had a friend tell me he was experiencing this, but he discovered it was happening with multiple apps on his phone and appeared to be an Android issue. He did a factory reset and his phone appeared to go back to normal. YMMV

**Comment by frdonn** [comment]
Hi,
I convinced my family to switch to Signal, unfortunatly, got the same pb on 2 smartphones both on Android 9 (Samsung & Pocophone).
