### ISSUE TITLE
Organic Android Photos Sent to iOS Do Not Render

### ISSUE THREAD

**Issue by mrgtreeskier** [signalapp/Signal-Android#8169]
- [X] I have searched open and closed issues for duplicates - Duplicates in iOS, request tracking in Android.
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See here for original thread: https://github.com/signalapp/Signal-iOS/issues/3654?_pjax=%23js-repo-pjax-container#issuecomment-418162458

Images taken with an Android phone in the native camera app then attached through Signal do not render in iOS. The user has to save the image and view it within Photos. Images downloaded from the internet render. Images taken with Signal render. Videos taken with Android's camera also render.

Bug has been replicated on 4 separate iOS instances. One group chat with 1 Android, 2 iOS users, both iOS users report same result. Another group chat with 2 Android users, 1 iOS user, the iOS reports same result but other Android user reports image rendering successfully. Android to Android does not replicate the problem. iOS to Android does not replicate the problem. iOS to iOS does not replicate the problem.

### Steps to reproduce
- Open camera
- Take photo
- Open Signal
- Attach photo to Signal thread
- Send

**Actual result:** Images are sent and downloaded to other signal user, but do not display within Signal. User has to download and use native iOS Photos app to view it.
**Expected result:** Images render within Signal and user can view full resolution.

### Screenshots

![](https://user-images.githubusercontent.com/11836366/44996929-bd336b00-af78-11e8-813f-53a3db987a40.jpeg)

### Device info
**Device:** Google Pixel XL
**Android version:** 9
**Signal version:** 4.25.7

### Link to debug log
Debug log from Android: https://debuglogs.org/28cca2f371dcbe5e60ff911b904f30fc55f8ce992f537039c53dcd6cc77d11a2

Debug log from iOS:
https://debuglogs.org/04629372e509f99354d56b710521eb9a2749fb1e6c17a53b0c1963525d8b79b1.zip

**Comment by greyson-signal** [comment]
Can you tell me specifically how you're attaching the photo? Are you attaching it by using the share button in the photos app, or are you initiating the attachment through signal? And if you're starting in signal, do you use the photo rail, or do you use the "gallery" option?

**Comment by mrgtreeskier** [comment]
@greyson-signal the problem arises regardless of how the image is attached. I just tried all three ways with replicated results.

**Comment by greyson-signal** [comment]
If this consistently happens with every photo, do you mind taking a test photo and posting it here? Then we can see if it's the photo itself or how it's being sent/read.

**Comment by slrideout** [comment]
I am experiencing this same issue. It is any image or video taken, attached by any method. My brother is experiencing the same thing as well.

**Comment by greyson-signal** [comment]
@slrideout  If you could also provide what phone, Android version, and Signal version you're running, that'd be great. It'd also be awesome if you could post a sample photo here that triggers the problem so we can try to reproduce it. Thanks!

**Comment by slrideout** [comment]
Samsung S7 Edge, Android version 8.0.0, Signal version 4.25.6, sample photo attached (taken through native camera app) 
![20180904_141327](https://user-images.githubusercontent.com/42976059/45055330-b7a75500-b04c-11e8-968a-f73eda95613f.jpg)

**Comment by brbike** [comment]
I have also encountered this problem, exactly as described, with one additional piece of information. Photos sent from Android to iOS a week or more ago, that were rendered correctly at the time, are now displayed as the jpg icon when you wind back to them.

From our rough tests it seems that the problem might be related to this, listed for Signal 1.29.1 for iOS:
 "Show generic file icon when encountering an image with excessively large dimensions"

What does "excessive" mean in this context?

**Comment by greveritt** [comment]
I'm having the same problem. I'm using a Moto G5 Plus running stock Android 7.0. Signal is at version 4.25.6. I'm also running Moto Camera 6.2.14.17, which I used to take the picture. So far one iOS user has complained about it being invisible.

The offending picture is below.

**Comment by greyson-signal** [comment]
This isn't a Signal-Android bug, so I'm going to close this issue.

@greveritt Great pics ;)

**Comment by greveritt** [comment]
Thank you, @greyson-signal . I'm very proud.

**Comment by slrideout** [comment]
Oh hi Mark

**Comment by Spindel** [comment]
@greyson-signal  When you close bugs like this, could you please reference the Signal iOS issue number?

**Comment by haffenloher** [comment]
@Spindel I think it's this one: signalapp/Signal-iOS#3860

**Comment by tuxracer** [comment]
Is https://github.com/signalapp/Signal-iOS/issues/3890 related?
