### ISSUE TITLE
Problem registering with Signal

### ISSUE THREAD

**Issue by twopossibility** [signalapp/Signal-Android#8170]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have disabled GMS using ADB. I have got the apk from website and trying to register for signal. But it says "Google Play Service is updating or temporarily unavailable. Please try again"
### Steps to reproduce
- Factory Reset Phone
- Disabled all Google Service Including GMS using ADB method
- Signal displays Google Play Service is updating or temporarily unavailable. Please try again. 
**Actual result:** Can't do anything after this. Just a warning description comes and stays there. 
**Expected result:** To run the app normally without getting warning. 

### Screenshot
https://postimg.cc/image/ngirjxwc1/

### Device info

**Device:** Honor 6x
**Android version:** 7.0
**Signal version:** 4.24.8

### Link to debug log
Can't get debug log as such.

**Comment by greyson-signal** [comment]
I don't know all of the details of disabling Google Play Services on a device. However you're doing it though, it makes it seem like the device _has_ Google Play Services, but that it's not up-to-date or whatever. I don't think this is a bug in Signal though. As a result, I recommend making a post on [the forum](https://community.signalusers.org/) where someone might be able to help you.
