### ISSUE TITLE
 Admin Feature for Groups

### ISSUE THREAD

**Issue by sonnenfeld269** [signalapp/Signal-Android#8171]
So many people really need Admin feature for groups. eg for deleting Single members from a group. 

And before you close this feature request please explain why you still don't want to add Admin Features.

**Comment by greyson-signal** [comment]
As noted in the issue template, we don't use Github for feature requests. If you want to discuss this, I encourage you to make a post on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
