### ISSUE TITLE
 Error - 505 on Google Pixel 2 XL... Unable to download and install Ansroid P

### ISSUE THREAD

**Issue by christiandjurberg** [signalapp/Signal-Android#8172]
- x I have searched open and closed issues for duplicates
- x I am submitting a bug report for existing functionality that does not work as intended
-  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- x This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to install from Google Play 

### Steps to reproduce

- Visit Google Play Signal app page ( on mobile or PC desktop "remote install")
- Hit install

**Actual result:**  I get "Error - 505" on Google Pixel 2 XL. 
Unable to download and install Ansroid P.
I use the Pixel 2 XL in Sweden
**Expected result:**
App should install

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 9
**Signal version:** 4.24.8

**Comment by greyson-signal** [comment]
That error can be caused by all sorts of things, none of which we have control over. I recommend using your search engine of choice to look for solutions.

**Comment by christiandjurberg** [comment]
Thanks for the support! 😂

How should I be able to install the app then?
Is there any apk install app I can find anywhere? Couldn't find any at your
github...

I haven't ever had any problems installing any app the last 7 years from
Google on their Play store...








Den tis 4 sep. 2018 17:04Greyson Parrelli <notifications@github.com> skrev:

**Comment by greyson-signal** [comment]
Sorry, what I'm trying to say is that the problem exists outside what I can control. It sounds like a problem between you and the Play Store. You can get our APK from [here](https://signal.org/android/apk/) if you can't get the Play Store working.

**Comment by christiandjurberg** [comment]
Hi again,

I give up...
I only get this attached message with the Android 9 standard package
instalation app when trying to install this APK...

Best regards,
Christian

Den tis 4 sep. 2018 21:36Greyson Parrelli <notifications@github.com> skrev:

**Comment by haffenloher** [comment]
@christiandjurberg did you mean to include a screenshot? You can upload one by dragging-and-dropping it onto the comment field on Github.

**Comment by christiandjurberg** [comment]
hmmm,

Im pretty sure I attached it in the email. Perhaps it's not possible to
attache in email to show up on Git hub?

I'll try attaching it again here in this email...


Den ons 5 sep. 2018 14:46haffenloher <notifications@github.com> skrev:
