### ISSUE TITLE
Missing French Translation for "Add to home screen" ?

### ISSUE THREAD

**Issue by dusscloud** [signalapp/Signal-Android#8173]
### Bug description
The "Add to home screen" text is not displayed in French on a French android phone running Signal

### Steps to reproduce
In any conversation in Signal Android app on a French Phone
- click on the menu (3 dots)
- the new feature "Add to home screen"  is displayed as it is (in english).

### Device info
**Device:**  Samsung Galaxy A5
**Android version:** 8.0
**Signal version:** 4.25.6 

**Device:**  Motorola G4 plus
**Android version:** 7.0
**Signal version:** 4.25.7

**Comment by greyson-signal** [comment]
We get all of our translations done through Transifex. The string you're talking about is relatively new and may not have been translated yet. I'm sure it'll be done in an upcoming release.

**Comment by dusscloud** [comment]
Fair enough, but I was not expected to see such issue in a production release.
