### ISSUE TITLE
Regular Signal messages sent with quick reply feature showing SIM indicator

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8176]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For two regular sent Signal messages, I just noticed that it shows the SIM indication (or whatever this is called) in the footer as if the message has been sent as SMS in a dual sim setting. 

### Steps to reproduce
- Have a look in the conversation history.
- Unfortunately, I have no idea how to reproduce this.

**Actual result:** Some regular Signal messages show up with a SIM indication
**Expected result:** Show as regular Signal message without SIM.

The phone runs in dual sim mode, but even if I deactivate the shown sim (or both), it still uses the same footer.
I also tried force closing the app, restarting the phone and clearing the cache without any success.
Doing some quick search, I could not find any other occasion of this behaviour, neither in the same nor in other conversations.
There should be nothing special about these two messages. They have just been sent with the phone (and successfully been received on the linked devices).

### Screenshots
![sim_indicator](https://user-images.githubusercontent.com/23025712/45078445-ef41eb80-b0a4-11e8-8f4d-4268939e367b.png)

### Device info

**Device:** Motorola Moto G5 
**Android version:** 7.0
**Signal version:** 4.25.9

### Link to debug log
https://debuglogs.org/106e97497a2b87c2d05e14622b768f8af66d076f7c395ae16d9ed27718c9e1b1
I hope the debug log is helpful at all as I just cleared the cache.

**Comment by greyson-signal** [comment]
First, just want to confirm that you do, in fact, have a dual SIM? Also,
did you send any real SMS messages earlier in this same conversation?

**Comment by minnmann** [comment]
Yes, I use the phone currently in dual SIM mode (two SIM cards plugged into the phone). Sorry for not making it clear enough.

I think that at some point I sent some SMS in that conversation, but that should be way back, I would assume at least several weeks or months, so probably a few hundred or even thousand messages back.

**Comment by minnmann** [comment]
And yet another update:
I think I found out what causes this behavior. It happens (reproducible) whenever I use the quick reply feature (replying from the message notification). The message sent via quick reply gets the sim indicator (even if the sim in question or both sims are deactivated).

Besides that, the quick reply has some other minor issue. Sometimes the notification is not removed even after having replied. At one point, even the text input did not vanish even though the message has been sent (resulting in me sending duplicate messages).
Should I open a separate issue for that as well?

Again, these are no big issues to me. From observing GitHub, I guess there are more troubling issues atm.

**Comment by greyson-signal** [comment]
Ahhh thank you for figuring out it was for quick-reply messages! I've fixed this in 4.26.

> Sometimes the notification is not removed even after having replied.

I notice this with every app on Android P, and I've found it quite annoying. I know you're running 7.0 though, so that's interesting. Feel free to open a ticket.
