### ISSUE TITLE
"Signal is unlocked" text instead "Signal is locked"

### ISSUE THREAD

**Issue by lupa18** [signalapp/Signal-Android#8177]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I should see "Signal is blocked" (in Spanish) and I see "Signal is unblocked" (in Spanish)

### Steps to reproduce
- wait that Signal get blocked
- open it
- you should see the wrong text

**Actual result:** you see "Signal is unblocked"
**Expected result:** you should see "Signal is blocked"

### Screenshots

![screenshot_20180905-164309](https://user-images.githubusercontent.com/463429/45120308-b9941580-b12b-11e8-960c-d78c809a63e2.png)

### Device info

**Device:** Motorola Moto G4
**Android version:** 7.1.2
**Signal version:** 4.25.6

**Comment by greyson-signal** [comment]
So I checked the strings.xml and can confirm that this is a translation issue, not a functionality issue. We'll fix the string. Thank you!
