### ISSUE TITLE
Long sim indicator cause bad user experience in SMS

### ISSUE THREAD

**Issue by dusscloud** [signalapp/Signal-Android#8178]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In dual sim phone, each SMS are labeled with SIM indicator (which is useful). Nevertheless, if SIM indicator is long, it causes a bad behavior in the look and feel because the message time is squeezed.

### Steps to reproduce
- insert two sim in your dual sim phone
- use a cellular operator with long name (eg : "Bouygue Telecom" in France) for one of the SIM
- set the dual sim mode to "personal / professional" (which add such info in SIM label)
- exchange SMS using the long name operator..

### Screenshots
![signal_dualsimissue](https://user-images.githubusercontent.com/31505866/45158049-24ecee80-b1e3-11e8-8207-b4d28f6c7477.jpg)

### Device info
**Device:** Motorola G4 plus
**Android version:** 7.0
**Signal version:** 4.25.7

**Comment by greyson-signal** [comment]
This should be mitigated by 946f76a44218da31fe95b06f2213db06547faff5. Thanks!
