### ISSUE TITLE
No more notifications

### ISSUE THREAD

**Issue by DorKeinath** [signalapp/Signal-Android#8179]
I disabled notifications for signal, then I enabled it again, but notifications in my tobar now stay away.
I wanted to check if it's possible to disable the hint for backgroundservice and enable new messages. Now without any notification its a kind of worse case. 

I'm using LOS 15.1.

**Comment by greyson-signal** [comment]
Hmm, can't seem to repro on my Nexus 5X running stock Android 8.1

Can you give me more details about

1. What device you're using.
1. What version of Signal you're using.
1. A debug log.
1. How you enabled notifications. Through the global Signal notification settings, through Signal conversation setttings, through the Android system settings?

Thanks!

**Comment by DorKeinath** [comment]
After rebooting my android it's working again. Even better than before: There is no permanent icon in my topbar any more, but at new messages the icon appears.

I switched off an on the global Signal notification settings (drawing down, pulling right, click on setting-symbol).
