### ISSUE TITLE
Final plea to fix "other user uninstalled but didn't unregister" bug

### ISSUE THREAD

**Issue by zacharycohn** [signalapp/Signal-Android#8181]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a final plea to address the "my friend/coworker uninstalled Signal but didn't know you had to also do this extra step it doesn't mention anywhere, and turns out they haven't been getting my messages for months because Signal decided to fail silently" bug (because a UX issue of this magnitude IS a bug).

You may be familiar with this bug from such threads as [this](https://github.com/signalapp/Signal-Android/issues/7188), [this](https://github.com/signalapp/Signal-Android/issues/6912), [this](https://github.com/signalapp/Signal-Android/issues/2285), [this](https://community.signalusers.org/t/remember-the-current-message-mode-sms-or-mms-for-each-contact/2382/17), [this](https://github.com/signalapp/Signal-Android/issues/6905), [this](https://github.com/signalapp/Signal-Android/issues/6718), [this](https://github.com/signalapp/Signal-Android/issues/5564), [this](https://github.com/signalapp/Signal-Android/issues/5171), [this](https://github.com/signalapp/Signal-Android/issues/4373), [this](https://github.com/signalapp/Signal-Android/issues/3790), or [this](https://github.com/signalapp/Signal-Android/issues/3457). (There are more, I just got tired of opening tabs and pasting links here).

It's a hard problem to solve. But people have been complaining about this bug for years. I personally run into this bug 2-3x a month. It has caused non-trivial disruptions to my life, missed business opportunities, and damage to friendships. 

Whenever I discover that I've run into this bug, I have an email saved that I send people that says "Hi. You used to use Signal. You don't anymore. Scary I know that, huh? Well here's how I know..."  100% of the time, those people respond back and thank me because they now know why they're not getting text messages from some of their friends, family, or coworkers.

I've stopped recommending Signal to people because of this bug. I'd like to go back to recommending Signal to people, because I believe in all the things you believe in. 

The most secure software is software no one uses. And that's what you're building right now, until you stop ignoring this bug.

**Comment by Dyras** [comment]
You can always tell them to go on the website and unregister there.

https://signal.org/textsecure/unregister/

**Comment by zacharycohn** [comment]
@Dyras Yes. That's what I tell them to do. After they miss 6 months of messages from my and I finally realize this bug struck again.

@minnmann No, it isn't. If I'm not logged into ICQ, IRC, AIM, MSN Messenger, gchat, etc, I show up as "unavailable" or "offline." So while I don't know if you use it still or not, at least I don't send you a message assuming it will get to you.

**Comment by minnmann** [comment]
Yes, but that seems to be somewhat use-case dependent. Some people only send messages while the other person is online, some also send offline messages (at least many old messenger also supported offline-messages and me and my friends used that quite a lot).
Nowadays, I think everybody tries to avoid the differentiation between "online" and "offline".

**Comment by rakenodiax** [comment]
@minnmann Kik will indicate when messages haven’t been delivered to a user for an extended period of time, indicating that the app is most likely uninstalled (or at least the server was unable to send a push notification to the device).

**Comment by minnmann** [comment]
@rakenodiax Thanks! That seems to be a reasonable feature request. 
Basically, I do this manually. If some contact does not receive the message (no double checkmark) in e.g. 1 week, I'll text him on a different channel. 

But I am not sure, if this would be an appropriate solution for @zacharycohn.

**Comment by moxie0** [comment]
@zacharycohn Thanks for writing, but we do not use GitHub for feature requests or for discussion topics. Opening issues here inappropriately does not make the work go any faster, it makes it go slower. As a reminder, nobody is "ignoring" anything; there is a single person working on this project, and much more than a single person amount of work to do. It's great that you want to help the project, but please try to use the communication channels we've setup in the way that we find the most helpful, and please try to be a little less judgmental/confrontational in assuming our motives.

As for users who silently uninstall, I'd love to see more discussion, including any ideas people may have, but please use the forums for that.

**Comment by mryellow** [comment]
@moxie0 Love your work. Ignoring this bug isn't helpful. It's a major blocker on your systems adoption and a complete UX failure on Android. It should be a top priority not something that gets sweap under the rug over and over again.

I have now been forced to stop using this software due to this failure of the systems UX.

It can't be continually ignore and no amount of working faster on other aspects of the software will win back all the goodwill you've lost in these endless issues posted on this subject.

**Comment by mryellow** [comment]
>  there is a single person working on this project, and much more than a single person amount of work to do

Would you like me to make the SMS button red and the Signal button blue?

Then allow it to retain the setting so that a user doesn't have to switch with every single message?

Surely that is enough of a UX fix without exposing anyone.

**Comment by kiplingw** [comment]
I don't know if Android APK packages support this the way Debian packages do, but in the latter it is possible to have uninstallation hooks that can run. All Signal needs to do is automatically unregister when it is uninstalled and problem solved.

**Comment by ristaloff** [comment]
Still not solved. I have lots of friends that have not received my messages. Got into all kinds of issues because of it. Uninstalled forever. 😡
