### ISSUE TITLE
Inconsistent timestamps

### ISSUE THREAD

**Issue by ba1ciu** [signalapp/Signal-Android#8187]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This might not be the best place for this issue, but I'll give it a try. Someone is texting to me from `Signal-Desktop` with wrong system time set. I get message with timestamps of his system time, so it tells me he texted 2h ago, while he did just now. Shouldn't timestamps come from external time server?

### Steps to reproduce
- have someone set wrong system time on PC and use `Signal-Desktop`
- send message to them from `Signal-Android`
- receive message from PC
- send message to PC user again

**Actual result:** Received messages have wrong timestamps.
**Expected result:** Consistent timestamps.

### Screenshots
![screenshot_20180907-105732](https://user-images.githubusercontent.com/39089377/45220511-9e054800-b2ae-11e8-9918-4c13c41cab0c.png)

### Device info

**Device:** Sony E6553
**Android version:** 7.1.1
**Signal version:** 4.24.8

### Link to debug log
https://debuglogs.org/5cbbffd88526559a087418ef6f8f41fd910a720e8437ecee4a081d60f6c0c945

**Comment by greyson-signal** [comment]
This is working at intended. We sort by received timestamp, but render the sent time on the messages. I know this results in some weird situations like this one, but we think it's better than the weird situations that come up when displaying/ordering messages using other timestamps. If you want to discuss this further, I encourage you to make a post on [the forum](https://community.signalusers.org/). Thanks!
