### ISSUE TITLE
Messages from starred contacts don't notify during "Do Not Disturb"

### ISSUE THREAD

**Issue by michaelsmoody** [signalapp/Signal-Android#8193]
On Android 9 Pie, on a Google Pixel XL, and when using Do Not Disturb (with starred contacts set to bypass Do Not Disturb), I find that Signal messages from starred contacts do not properly notify, and are instead silent. Contrasting this behavior to calls, and SMS/MMS received in other apps, like Hangouts (as we use Fi with Hangouts for SMS), or Messages (as the SMS app), or with incoming calls, with all of those applications, sounds and vibration happen when calls or messages are incoming from previously starred contacts.

I know that it is possible to globally allow Signal to override DND from the notifications area in the App Settings (in Android Settings), however, I'd like only my starred contacts to override, vs all Signal notifications. It seems this behavior is not properly obeying my Starred Contacts settings.

In truth, I'm not sure if this is a bug or a feature. Does Signal leverage the DND Access API?

Please let me know if more information is needed, and I haven't tested this behavior on earlier versions of Android to deteremine if this is a regression, but I potentially can (as I have a Nexus 5, a Nexus 6, a Nexus 6p, a Nexus 7 2013, and a Nexus 9, even though tablet support doesn't exist).

Thanks in advance.

**Comment by sykosoft** [comment]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

### Steps to reproduce
- Star a contact with which to message with Signal
- Turn on DND with exceptions for Starred Contacts
- Receive messages from the Starred Contact, but note no notification sounds or vibration when using DND

**Comment by devurandom** [comment]
Related issues: #2548 originally requested for this functionality and #5503 first reported it as broken.

**Comment by dsvk** [comment]
FWIW I have just now tested DND with both messages and calls (see https://github.com/signalapp/signal-android/issues/11055#issuecomment-1026275640) and have encountered no unexpected behavior with messages (incl. missed call notifications), these all respected DND rules on both my devices in all scenarios tested. Calls, on the other hand, _did_ exhibit multiple issues.

**Comment by holocronweaver** [comment]
General tracking issue: #9297 

Seems to affect all calls during Do Not Disturb, not just those for starred contacts.
