### ISSUE TITLE
dropped message in group 

### ISSUE THREAD

**Issue by benmayne** [signalapp/Signal-Android#8196]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a group message, the first message from my android to the group was not delivered to a member who had updated his safety number since my last message to him. My android reported the message as delivered (but not read), but my desktop application doesn't even report it as sent to him. The other two members got the message as expected. 

### Steps to reproduce
- have group
- member A update safety number (ios)
- member B sends message (android)

**Actual result:** the member with the new safety number doesn't get the message
**Expected result:** everyone gets the message

### Screenshots
![screenshot_20180910-102256](https://user-images.githubusercontent.com/3374110/45313687-6da6ef00-b4e4-11e8-8a2e-a21211c3ab36.png)

![screenshot_20180910-101411](https://user-images.githubusercontent.com/3374110/45313696-70a1df80-b4e4-11e8-951a-ad5ff2a1e8e4.png)

desktop message info: 

![screenshot from 2018-09-10 10-14-28](https://user-images.githubusercontent.com/3374110/45313726-831c1900-b4e4-11e8-802c-d640ccd84ad5.png)

### Device info

**Device:** Google Pixel 2
**Android version:** 9
**Signal version:** 4.25.10

### Link to debug log
android: https://debuglogs.org/8de16de769e27b23951335cc7aa0672919a7fa4ac7ed05909d498e0632ab0063

desktop: 
https://debuglogs.org/b2e7616383492c7e55455cdd6a084ebd2b089b04d5d68b61de4891f6f8d85dce

cc @jbaxter

**Comment by jeremymasters** [comment]
Those look like real names.  should you redact them from the screen shots?

**Comment by benmayne** [comment]
Happened again today in a different group. 

I sent the message from desktop (log https://debuglogs.org/273efe5a01c0c587c9adeb57ec3646ed86d40cd04418280e4d690f32a8560c65) 

One of the iOS members didn't get it, but then got the reply from another member.

**Comment by benmayne** [comment]
Today I'm on the receiving end of the drop

My log https://debuglogs.org/a48bbb2d8ea9fcabd78b8718fb58baf7390749173850e651fb053e3071551d89

iPhone user's log that got all the messages: 
https://debuglogs.org/7818309fe700ae33d701a82296747c685787c1dc01781a127d5e82ee0162058e.zip

**Comment by greyson-signal** [comment]
> https://debuglogs.org/a48bbb2d8ea9fcabd78b8718fb58baf7390749173850e651fb053e3071551d89

@benmayne I didn't see anything in the log to imply a message receive failure, so it was likely that the message was not sent.

Do you think the occurrences on 10/3/2018 and 11/17/2017 were also due to safety number changes in a group?

**Comment by benmayne** [comment]
I don't know about 10/3. 

Today (11/17) there's no safety number updates happening. I don't have a debug message from the sender, just me and someone who got both messages. I successfully received a message from that sender in the same thread yesterday.

The only thing I've done between yesterday and today's dropped message was de-activate and then re-activate a desktop client, but that device wasn't directly involved.

**Comment by benmayne** [comment]
This debug is from the sender's desktop app a couple hours after my report this morning 

https://github.com/signalapp/Signal-Android/issues/8196#issuecomment-439631115

https://debuglogs.org/d53f298a88d895060ce8cb697b014ba1ebd91a71ac0d7322a52e7ef09a4632c7

Doing some tests with and without desktop from him now. I can confirm that the original bug report from this issue didn't involve any desktop clients, but I'm currently experiencing a lot of problems that feel tied to the desktop, so there might be some overlapping problems.

**Comment by benmayne** [comment]
This is a couple logs from the sender's android app after lots of failed attempts to reach me on groups or directly: 

https://debuglogs.org/0af7cdd79e430d52b42c8dde87d174d48b2298f28f5960f3312152e4cef058e0
https://debuglogs.org/728ca4ee877efb7079ec935ffa0c3a528f6c8a3409bd6cdfae798bf58a10b753

Here's a couple from his desktop 

https://debuglogs.org/75e368b867279c586d8917654b1d9e79828d0798de9b33b928af6cd45457c9ab
https://debuglogs.org/bcb8060e2b67429b4ad82cc388c28948a994419dc8c8adbcf02631afe3ac2c28

Unfortunately, I think we're at the limit of my ability to remotely debug my dad's phone, so I probably can't get more detail on this incident unless it's still happening when I see him in person.

**Comment by benmayne** [comment]
Ok, just kidding. I'm back to being able to talk to him both directly and in a group after deactivating all 4 of my desktop clients and resetting the secure session. 

I had previously deactivated the clients I was using and reset the session unsuccessfully, but this seems to have gotten there. 

One last debug message from his android for good measure https://debuglogs.org/2cda421bc7ac96862ac527f5e89facb05a2e7716a52c84b48ed356c068ccea08

**Comment by benmayne** [comment]
happened again: 

User "S" (android) sent a message to a group that had been inactive for a while. User "Am" (iPhone) didn't get the first message, but did get the group update. 

I (user B, android), replied, A got that message and the second message from S. 

AM's logs and screenshot

https://debuglogs.org/d7f6ae101aff25b249628c3c4cd058cf3088911e021db902b4ae177e2300cf32.zip

![signal-2019-01-13-172536](https://user-images.githubusercontent.com/3374110/51093762-9f161c80-175b-11e9-8903-ccb24975c2ed.png)

B's (me) logs and screenshot

https://debuglogs.org/d5947e604813c3cceee0e13e53135d0a50e41bc5cfced9471f6cdda48a0b7877

![screenshot_20190113-172300](https://user-images.githubusercontent.com/3374110/51093772-be14ae80-175b-11e9-938c-157d9306178d.png)
