### ISSUE TITLE
Conversation shortcuts skip registration pin reminder.

### ISSUE THREAD

**Issue by jtracey** [signalapp/Signal-Android#8198]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you use a conversation shortcut, the periodic registration pin checks are bypassed. This could make these reminders less useful for people who make extensive use of conversation shortcuts.

### Steps to reproduce
- enable registration pin
- create conversation shortcut
- wait for registration pin check/reminder
- use conversation shortcut

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Registration check is avoided
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Registration pin entry should appear on conversation screen, or should redirect to main conversation selection screen.

### Device info

**Device:** Samsung Galaxy A5
**Android version:** Android 7.1.2 (lineageOS)
**Signal version:** 4.25.10

**Comment by greyson-signal** [comment]
Thanks for calling this out, but I think it's enough to remind people about their PIN when they visit the conversation list. Thanks!
