### ISSUE TITLE
Call possible when Signal is locked

### ISSUE THREAD

**Issue by sebaki** [signalapp/Signal-Android#8203]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
From a security point of view it should not be possible to initialize a encrypted call using Signal. When Signal is locked, any attempt to get in touch with data (chats + calls) should be stopped and the unlock screen should be displayed. Otherwise a person could call someone of my contacts and pretend to be me.
If you need screenshots, I can provide later.

### Steps to reproduce
- Lock Signal
- Open Contacts (LineageOS) and choose any with Signal installed
- Tap on Signal Call

**Actual result:** A call is possible even when Signal is locked.
**Expected result:** The initialisation of the call should be stopped, until Signal is unlocked.

### Device info
**Device:** Motorola Moto X Play
**Android version:** 7.1.2
**Signal version:** 4.25.10

**Comment by moxie0** [comment]
Thanks @sebaki, but this is the intended behavior. The screen lock is just designed to be a casual barrier which protects message history in the case where you hand an unlocked phone to a not-very-determined attacker. If someone is going to take your unlocked phone and call someone on Signal, they could also take your unlocked phone and install a rootkit, etc.

It's possible that there is some case for extending the screen lock to handle calls, but we try to use the forums for feature requests or that type of discussion, so please post there if you'd like to talk about it. Thanks!
