### ISSUE TITLE
Cannot set 'None' (silent) notification sound

### ISSUE THREAD

**Issue by astatine** [signalapp/Signal-Android#8206]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to set `None` (Silent) notification sound. To silence Signal, I have to completely turn off Notifications.

### Steps to reproduce
- Run Signal
- Go to `Settings` > `Notifications`
- From the `Sound` dropdown/list, note the selection. Now, choose `None`, then click OK.
- Go back to the main `Settings` page, and then go to `Notifications` again.

**Actual result:** The setting is changed back to the previous (Default/custom) selection.
**Expected result:** The `None` setting should persist.

### Device info

**Device:** LeEco Le 2
**Android version:** 8.1 (LineageOS 15.1)
**Signal version:** 4.25.10

**Comment by greyson-signal** [comment]
Fixed in 4.26
