### ISSUE TITLE
High resolution images are shrunk to miniature images on a low memory device

### ISSUE THREAD

**Issue by AndrewPy** [signalapp/Signal-Android#8207]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If someone wants to send me a picture from a Samsung Galaxy A3 2015 (SM-A300F), then it is impossible to send this in an appealing quality. e.g. a photographed piece of paper with 3264x1836 pixels turns into a picture with 408x230 pixels, so that the text on it becomes completely unreadable. Whether the picture is attached as a photo or as a file does not matter. 

It looks like Signal recognizes the device as a low memory device (96, low-mem device). 

(Currently the only way to keep the text readable is to create a PDF file from the image, but that's pretty cumbersome for quickly submitting a single image.)

### Steps to reproduce
- Use an android device with 1 GB RAM (?)
- Take a picture of a written text (resolution 3264x1836 pixels)
- Attach the picture to a signal message
- Send the message

**Actual result:** The picture is shrunk to a miniature image with 408x230 pixels with unreadable text.
**Expected result:** The text on the picture should be readable (for example with a resolution of 2400x1350 pixels).

### Device info

**Device:** Samsung Galaxy A3 2015 (SM-A300F)
**Android version:** 5.0.2
**Signal version:** 4.25.10

### Link to debug log

(Sorry, no debug log - the Samsung A300F is not my own device.)

**Comment by johanw666** [comment]
Is it sent as a Signal message or as a MMS? There are size limits to MMS messages.

**Comment by AndrewPy** [comment]
No we don't use MMS. The pictures are all sent as signal messages.

**Comment by greyson-signal** [comment]
We compress images for Signal messages as well. Low-memory devices have particularly stringent size restrictions to reduce the possibility of out-of-memory errors during compression. I think that's still the right thing to do. Unfortunately it's impossible to have a perfect limit for each individual device.

**Comment by PiCob** [comment]
Just as a technical question, not meant to raise any kind of discussion:
Compression is even used when pictures are attached as "File"? I always thought that in this case images don't get compressed at all (so any OOM during compression could be avoided)... seems I was wrong.
