### ISSUE TITLE
custom ring tone - application stopped working

### ISSUE THREAD

**Issue by MtaTech** [signalapp/Signal-Android#8208]
Custom ring tone change and stop working app

Xiaomi Mi 8
Android 8.1.0
Signal vers 4.25.10

**Comment by greyson-signal** [comment]
It's pretty hard to understand what this ticket means. Can you share additional information? Specifically, can you fill out the template that you deleted when making a new issue?

> - [ ] I have searched open and closed issues for duplicates
> - [ ] I am submitting a bug report for existing functionality that does not work as intended
> - [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
> - [ ] This isn't a feature request or a discussion topic
> 
> ----------------------------------------
> 
> ### Bug description
> Describe here the issue that you are experiencing.
> 
> ### Steps to reproduce
> - using hyphens as bullet points
> - list the steps
> - that reproduce the bug
> 
> **Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
> **Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
> 
> ### Screenshots
> 
> 
> 
> ### Device info
> 
> **Device:** Manufacturer Model XVI
> **Android version:** 0.0.0
> **Signal version:** 0.0.0
> 
> ### Link to debug log
>

**Comment by greyson-signal** [comment]
There's other issues regarding notifications that are open. I'll assume that this is covered by those. Feel free to re-open if you've confirmed there's no existing issue that matches your problem and are able to provide more details. Thanks!
