### ISSUE TITLE
Can't end or manipulate call function when navigating away from the call screen

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-Android#8210]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you navigate away from the call screen during a call there's no way to go back to the call screen or handle any on-call functionality like toggle speaker or camera.

### Steps to reproduce
- Accept a call
- Hit the home button
- Now you can't easily navigate back to the call/No notification that a call is in progress

**Actual result:** Accept an incoming phone call, navigate away and now you can't easily return to the call screen.
**Expected result:**  Have an easily accessible notification to return to the call.

### Device info

**Device:** Google Pixel 128GB
**Android version:** 9.0 Stock everything
**Signal version:** 4.25.10

**Comment by greyson-signal** [comment]
I have the exact same phone setup and can't reproduce the problem. There's a persistent notification showing that allows me to return back to the call.

Now, one way I _could_ reproduce it is if I went into the notification channel settings and disabled call notifications. Have you done that?

**Comment by 211217613** [comment]
In Apps & Notifications -> Signal -> Notifications. I have everything enabled.

In Signal app -> settings -> notifications. I have everything enabled.

**Comment by greyson-signal** [comment]
Does this happen consistently? If so, can you make a call and submit a debug log?

**Comment by greyson-signal** [comment]
Can you post a debug log then? To do so, simply go to Settings >  Advanced
> Submit debug log. You'll get a link that you can post here.

**Comment by 211217613** [comment]
Debug log here: https://debuglogs.org/cb6a90b9fb2da364c6c1a43b71ea7b622b988a42e4965949e0552c63628a68f0

**Comment by greyson-signal** [comment]
So I see logs that imply that we're definitely creating the foreground notification. Can you either post a screenshot of your "Apps & Notifications -> Signal -> Notifications" screen, or at least list all of the channels that are there? I'm wondering if somehow you're missing the "Calls" channel entirely.

Also, do you have any other notification-related system settings changed? Like do you have "do not disturb" enabled or something?

**Comment by 211217613** [comment]
![image](https://user-images.githubusercontent.com/7006850/45787651-372b4b80-bc2b-11e8-9f18-8538223424d5.png)

![image](https://user-images.githubusercontent.com/7006850/45787657-3e525980-bc2b-11e8-95bf-24f508a4a4dc.png)

**Comment by 211217613** [comment]
![image](https://user-images.githubusercontent.com/7006850/45787712-7eb1d780-bc2b-11e8-9246-30b62e03b4e4.png)


![image](https://user-images.githubusercontent.com/7006850/45787704-78bbf680-bc2b-11e8-82c3-39034351fbaa.png)

**Comment by greyson-signal** [comment]
Thanks a lot for posting those. They look exactly like they should. I'm pretty stumped at the moment to be honest. I did realize that you're using a Pixel, not a Pixel 2 like I tested on, so I'll test on that phone and see if I can repro. But I don't know why it'd make a difference. Hmm.

**Comment by 211217613** [comment]
I'd like to do a screen recording too. But don't know how to do that. 

@greyson-signal  Do you think a re-install might fix some of the issues I've been having...including this one?

**Comment by greyson-signal** [comment]
I wouldn't be able to say for sure. A reinstall is the equivalent of "turning it off and then back on again" for apps, and sometimes can fix things you wouldn't expect. All I can say is that I can't reproduce this problem, and don't see any immediate reasons as to why you're not getting an ongoing notification. My Pixel is in the middle of upgrading to P. After that's done, I can see if this is some device-specific problem.

If you do decide to reinstall, don't forget to make a backup in Settings > Chats and media.

**Comment by 211217613** [comment]
Just reinstalled and restored a backup. I'll do some testing and post any
updates.

**Comment by greyson-signal** [comment]
Yeah, just confirmed that I can't repro with my Pixel running P. Let me know if things got better for you.

**Comment by 211217613** [comment]
Reinstall fixed it. I get an in call icon during a call now.

**Comment by 211217613** [comment]
I'll post a screenshot later.

**Comment by 211217613** [comment]
I guess this can be closed out since a reinstall fixed it.
