### ISSUE TITLE
Length of voice message not visible

### ISSUE THREAD

**Issue by Hannnsen** [signalapp/Signal-Android#8211]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In comparism with the desktop app, the length of voice messages is not displayed in the app for Android.

### Steps to reproduce
- get a voice message or create one

**Actual result:** no length of the voice message visible
**Expected result:** voice message should be displayed, where some hint of the length is displayed (for example 0:18 for 18s of voice)

### Device info

**Device:** BlackBerry KEYone BBB100-2
**Android version:** 8.1
**Signal version:** 4.25.10

**Comment by greyson-signal** [comment]
This is a feature request. Please discuss this on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests).
