### ISSUE TITLE
dark mode: message window turns white when phone is rotated while keyboard is active

### ISSUE THREAD

**Issue by t1nux** [signalapp/Signal-Android#8212]
### Bug description
In dark mode, when the phone is in portrait mode and the keyboard is active, the message window is dark. If now the phone is rotated so that you end up in landscape mode, the message windows turns white. This only happens while the keyboard is active.

### Steps to reproduce
- use dark mode (message window should be dark)
- start in portrait mode, ie. phone is vertical
- tap on the message field so that the keyboard comes up
- rotate phone to get to landscape mode while keyboard is active

**Actual result:** 
The message window turns white. Meaning it has a white background, as if in normal (not dark) mode.

**Expected result:**
message window is dark

### Screenshots
![portrait](https://user-images.githubusercontent.com/4058407/45673802-f6004200-bb2b-11e8-9f4e-2f5adada1e90.jpg)

![landscape](https://user-images.githubusercontent.com/4058407/45673793-eed93400-bb2b-11e8-908f-8f5065c6a9bc.jpg)

### Device info
**Device:** Oneplus 5
**Android version:** 8.1.0
**Signal version:** 4.25.10

**Comment by t1nux** [comment]
This issue seems to be fixed in 4.30.8

**Comment by UserX404** [comment]
It is not fixed in 4.35.3
please re-open

**Comment by t1nux** [comment]
I'm using 4.36.2 and it seems to be working as it should be.

**Comment by t1nux** [comment]
It's broken again in 4.37.2.

**Comment by t1nux** [comment]
Yeah, this is still happening. It's not a major issue, more a glitch in the UI. But it certainly doesn't prevent any of the operation.

**Comment by alex-signal** [comment]
I'm not actually convinced we control this view's color, and I think it might be a setting on the input method. The same thing happens in, for example, Twitter.

**Comment by t1nux** [comment]
> I'm not actually convinced we control this view's color, and I think it might be a setting on the input method. The same thing happens in, for example, Twitter.

If this is indeed the case for other apps, it is most likely not an issue with signal. I did not manage to verify this, since I didn't find another app with the issue, but I take your word for it that twitter is doing the same. 
I'm closing this. Just reopen if necessary.
