### ISSUE TITLE
"Pop-up windows" terminate voice message recording, losing content

### ISSUE THREAD

**Issue by GeoffMaciolek** [signalapp/Signal-Android#8213]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When recording a voice message (ie holding down the microphone button), recording will end if a pop-up appears. Additionally, the content of the message will be lost, rather than being sent as-is, paused, or otherwise retained.

### Steps to reproduce
- Install an app (such as [Space](https://play.google.com/store/apps/details?id=mrigapps.andriod.breakfree.deux), designed to remind the user to put their phone down periodically) that will regularly interrupt the user
- (Optional) Set Space to a short Interruption interval for testing purposes
- Launch signal, open a conversation
- Tap & hold on the voice message recording button, and talk
- Continue holding, and wait for Space to interrupt the user

**Actual result:** signal stops recording the voice message, but does not retain it in any fashion. (This can be confusing for the user, as there is also no feedback that this has happened).
**Expected result:** The simplest "expected behavior" would be for signal to send the message as-is. This is how Voxer behaves in this situation (though Voxer does not have an option to cancel while recording).

Another, perhaps better option for expected behavior would be for the recording to simply be paused, and for the user interface to wait for the user to return to pressing and holding the record button to continue. (Visual feedback to draw the user's attention to the record button - blinking, throbbing, etc - would be a good idea here). I think this option would fulfill the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). the message is neither lost, nor unexpectedly sent.

A third option would be to provide a small amount of user interface feedback, such as a continue / cancel choice in those situations. as this would require creating additional user interface elements, I do not believe this would be the best choice.

### Screenshots
I will consider adding a screenshot, but I do not believe it offers much help in this.

### Device info
**Device:** Google Pixel 2 XL
**Android version:** 8.1.0
**Signal version:** 4.25.10

### Link to debug log
I will capture this the next time the issue occurs; I imagine knowing the specific Android events will help.

### Additional Thoughts
I believe the most relevant detail here is that this bug results in an unexpected behavior, and essentially data loss. I've used the example of "Space" as an application that interrupts the user with a pop-up, but I suspect any other apps or Services doing the same thing would trigger this issue. A background app requesting root, for example? An alarm clock pop up? Etc. Fortunately (from a user interface standpoint) pop ups do not occur frequently on Android. however, it is a supported Android behavior, and Signal should be able to handle it gracefully.

**Comment by DreamFlasher** [comment]
This bug occurs actually more often: I regularly get phone calls or Signal calls on my phone. These also interrupt voice messages. And yes, this means data loss, other apps such as Whatsapp send interrupted audio messages, or pause the recording.

**Comment by greyson-signal** [comment]
I think sending an incomplete audio message in response to some other application showing a popup would be the worst-case scenario. You're taking control away from the user as to when a message is sent. 

Supporting resumable audio messages is a non-trivial change that crosses the boundary into feature request IMO, in which case it can move to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests).

**Comment by DreamFlasher** [comment]
Well this is your opinion, from the people I know they consider data loss a way worse user experience than given away that control in this scenario. This still remains a bug and should not be closed.
