### ISSUE TITLE
Need to increase the API level in the build documentation 

### ISSUE THREAD

**Issue by kuala-lumpur1** [signalapp/Signal-Android#8218]
Google have sent this message to all developer.

This is a reminder that starting November 1, 2018, updates to apps and games on Google Play will be required to target Android Oreo (API level 26) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 26.

I have checked the build documentation and i see the targetSdkVersion is still on 25.

I tried to increase it to 26 and the app was working perfectly with all android versions except 8.0 and up.

**Comment by greyson-signal** [comment]
I'm very aware of the impending API 26 requirement :) It's a non-trivial amount of work that has been ongoing. See #8091 and other similar PR's.

This isn't a bug in the traditional sense though, so I'm closing it.
