### ISSUE TITLE
"Switch to other camera" button disapears during video call when multitasking in Signal

### ISSUE THREAD

**Issue by brs17** [signalapp/Signal-Android#8221]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During a video call, the "Switch to other camera" button disappears when switching to the home screen and opening a Signal message and then switching back to the video call. 

### Steps to reproduce
- Start video chat (notice that the option to switch cameras in present)
- Press the Android "Home" Button
- Open Signal from the home screen(to the home messaging screen)
- Pull down notification menu.
- Select Signal Video call (to return to the call)

**Actual result:** After doing the above steps, the option to switch cameras is no longer present in the video call.
**Expected result:** The same options(the ability to switch cameras) that were available to begin with should still be available.

### Screenshots

N/A

### Device info

My Device info:
**Device:** LG Nexus 5x
**Android version:** 8.1.0 (September 5th, 2018 Security Patch)
**Signal version:** 4.26.1

My good friend's device's info (who was able to recreate the issue as well)
**Device:** Moto G 5+
**Android version:** 7.0.0
**Signal version:** 4.25.10

### Link to debug log

https://debuglogs.org/0e10c3aae47a565f06e9d93aad1b6812d1be5cbe7c57610e972b14082c21abee

**Comment by minnmann** [comment]
Just want to add that my workaround in this case is to disable and enable the camera again. Then the switch button reappears for me (Moto G5).
(Seems to be a classic "Have you tried turning it off and on again?" :) )

**Comment by mikaseh** [comment]
I am able to reproduce this bug

My device info:
**Device**: Google Pixel 2
**Android version**: 9
**Android security patch**: November 5, 2018
**Signal version**: 4.30.8

My friend's device's info (who was able to recreate the issue as well)
**Device**: Google Pixel
**Android version**: 9
**Android security patch**: October 5, 2018
**Signal version**: 4.30.8
