### ISSUE TITLE
Can't Install app from Android Studio

### ISSUE THREAD

**Issue by rupinderjeet** [signalapp/Signal-Android#8226]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
Using latest code from here, I am unable to install the app.

### Steps to reproduce
- clone this repo
- Run
- Error occured: createProcess error=2 'git' Command not found
- replaced `buildConfigField "long", "BUILD_TIMESTAMP", getLastCommitTimestamp() + "L"` with `buildConfigField "long", "BUILD_TIMESTAMP", 1537774089000 + "L"`
- Run Debug
- app installed
- while debugging, removed app from device.
- disconnected device, then reconnected
- Run Debug
- `.RoutingActivity` not found. 
- Clean, Rebuild, Run
- `.RoutingActivity` not found.  Tried 10 times.

**Actual result:** Unable to install after "Installing APK" message
**Expected result:** Expected the app to be installed.

### Screenshots

This is the error:

```
09/27 18:09:01: Launching Signal-Android
$ adb install-multiple -r -t D:\xxxx\xxxx\Signal-Android\build\intermediates\split-apk\play\debug\slices\directories.apk D:\xxxx\xxxx\Signal-Android\build\outputs\apk\play\debug\Signal-play-debug-4.26.1.apk 
Split APKs installed in 6 s 79 ms
$ adb shell am start -n "org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Error while executing: am start -n "org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.thoughtcrime.securesms/.RoutingActivity }
Error type 3
Error: Activity class {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity} does not exist.

Error while Launching activity
```

### Device info
Moto G6 (unrelated)

### Link to debug log
unrelated

Sorry if I am making mistakes, but I learn. Thanks.

**Comment by johanw666** [comment]
The buildConfigField issue can be solved by putting git in your path. If you copy the apk to the device and open it in a file explorer, will it install?

**Comment by greyson-signal** [comment]
Hi, @rupinderjeet! Glad to see you're setting up a dev environment. However, we reserve Github issues exclusively for bugs. We have a docker image available for building the app ([wiki](https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds)), which also serves the purpose of ensuring our builds work. So whatever error you're having is environment-specific. Feel free to make a post on [the forum](https://community.signalusers.org/) to get more assistance. Thanks!
