### ISSUE TITLE
Fallback SMS not working

### ISSUE THREAD

**Issue by n00b42** [signalapp/Signal-Android#823]
[Issue]
The PUSH functionality works properly, when i wanted to test SMS fallback via disabling all data connections, my message gets green and shows "Sending.." and no SMS is sent. Message details show "SMS"

SMS service work, as i can sent an normal SMS from my default SMS app to the same person.

[Setup]
i9100, rooted, CM11-20140205-Nightly-i9100, latest TextSecure from AppStore, Germany

**Comment by ladyfair** [comment]
Please help, I have text secure, My friend then also got text secure, I can receive his messages, but he does not receive mine unless I unregister from text secure!!
