### ISSUE TITLE
[v4.27.2] Taking a picture causes uncaught exception

### ISSUE THREAD

**Issue by PiCob** [signalapp/Signal-Android#8232]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Taking a picture (more precise: hitting the shutter button) using the new camera flow causes Signal to stop running (uncaught exception).

### Steps to reproduce
- Open conversation
- Enter new camera flow to take picture within Signal
- Hit the shutter button

**Actual result:** Uncaught exception is thrown
**Expected result:** Picture is taken

### Device info

**Device:** Motorola Moto G (falcon)
**Android version:** 4.4.4
**Signal version:** 4.27.2

### Link to debug log
https://debuglogs.org/34418fc5f756cd06fecad6345ad5042e143036222952c489ec506e89dafe4329

`E/UncaughtExceptionLogger( 9027): java.lang.IllegalStateException: Hardware acceleration can only be used with a single UI thread.`

**Comment by greyson-signal** [comment]
Ah, looks like older versions Android need to have `TextureView#getBitmap()` called on the main thread. Thanks for catching this!
