### ISSUE TITLE
[4.27.2] Text in settings has different indentation

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8233]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The text for the individual settings has a different indentation than previous versions - at least as far as I can remember (but maybe I am mistaken).
I don't know if this is intendend behavior, but since I could not find any commit from 4.26.2 to 4.27.2 that sounds related, I assume this is a bug.

### Steps to reproduce
- Open settings dialog
- Select any sub-menu (other than "Linked devices")

**Actual result:** Indent of text is same as title
**Expected result:** No indentation (i.e. the same as before)

### Screenshots
![screenshot_20181001-220049](https://user-images.githubusercontent.com/23025712/46330271-ee7a7780-c5c6-11e8-87be-d9efae39700a.png)

### Device info

**Device:** Motorola Moto G5
**Android version:** 7.0
**Signal version:** 4.27.2

### Link to debug log
If one is needed, I will post one.

**Comment by greyson-signal** [comment]
Ah, this wasn't intended, but I'd guess this is a result of me updating all of the support libraries. I think the new recommended alignment on settings pages is to have the text aligned with the title in the toolbar, and they enforce this through the default settings stylings in the support library.

This can be verified by looking at the system "Display" settings on a stock Android 8 or 9 device. It looks the same as it does here, toggles and all. I'll get some feedback and then decide if we'll leave it like this or not.

Thank you for catching this!

**Comment by FeuRenard** [comment]
It also affects the recipient settings activity.
