### ISSUE TITLE
[v4.27.2] Tab switching still disabled after exiting multiselect

### ISSUE THREAD

**Issue by PiCob** [signalapp/Signal-Android#8234]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Introduced by commit https://github.com/signalapp/Signal-Android/commit/84c71fce16a3396374bc97a38c563082e136c61d, tab switching in media overview during multiselect is no more possible. Exiting multiselect should actually re-enable the tab switching. However, it doesn't work if you exit multiselect **by hitting [X] in the title bar** (next to the selected media count).

### Steps to reproduce
- Open conversation
- Open media overview
- Enter multiselect (by long-tapping)
- Exit multiselect (and hence unselect all media) **by hitting [X] in the title bar**

**Actual result:** Tab switching is still disabled
**Expected result:** Switching tabs is possible

### Device info
**Device:** Motorola Moto G (falcon)
**Android version:** 4.4.4
**Signal version:** 4.27.2

### Link to debug log
Can't upload it right now, but shouldn't be necessary anyway, since it's easily reproducible.

**Comment by greyson-signal** [comment]
Thanks for catching this!
