### ISSUE TITLE
Dark mode: default contact photo isn't dark

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#8240]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

### Bug description

In dark mode, the default contact photo for contacts with no image set isn't dark.

**Comment by greyson-signal** [comment]
Not sure specifically what you're referring to (screenshots are usually very helpful for UI bugs), but avatars were changed in the 4.28 branch, so I'll assume this bug is fixed in the upcoming release.

**Comment by jpds** [comment]
Sorry, for clarity, I'm referring to the image used in the call here: https://www.geekiest.net/post/Signal-video-calls-Android-iOS

**Comment by 948127524** [comment]
Still an issue with 4.30.8
