### ISSUE TITLE
Registration Lock gives "Error connecting to the service" if PIN is longer than 16 characters.

### ISSUE THREAD

**Issue by Forbo** [signalapp/Signal-Android#8242]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to use a PIN that was 32 digits, the Registration Lock PIN creation dialog would just return an "Error connecting to the service" message. Reducing this to 16 digits works as intended. There is no UI indication that there is a limit to PIN length.

### Steps to reproduce
- Go into Settings -> Privacy -> Registration Lock PIN
- Enter a PIN that exceeds the 16 digit limit, confirm it, then submit.
- Error message should appear.
- Reduce to 16 digits, submit. It works correctly.

**Actual result:** "Error connecting to the service" when using a PIN that is too long.
**Expected result:** If the PIN is too long, return an error message indicating that is the issue rather than a connection problem.

### Device info

**Device:** Google Pixel
**Android version:** 9
**Signal version:** 4.26.2

### Link to debug log
https://debuglogs.org/2b1651ed3efea7b051fd3299a166113ec78926cf8e18450ebfcaae36e862a8b8

**Comment by aunwin** [comment]
![error](https://user-images.githubusercontent.com/1859684/69054589-313a2180-0a0c-11ea-8e3b-fb0e8e38147a.png)

Still happening.

Device: HTC U11
Android: 9
Signal version: 4.50.3

**Comment by Sgn-32** [comment]
The registration lock PIN is/was replaced by the Signal PIN.
The issue should not be anymore with the Signal PIN.

**Comment by Sgn-32** [comment]
You should open a new issue. This was an old issue with the old registration pin and it's closed since 2 years.
Signal uses for some time the Signal PIN. And please add a debug log.

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug
