### ISSUE TITLE
Signal call conversation sent as voice message sent to 3rd party recipient

### ISSUE THREAD

**Issue by ldionmarcil** [signalapp/Signal-Android#8244]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While calling someone on my Android phone using the Signal app, and chatting using text with another person using the Chrome application, I had 5 minute of my (supposedly secret) conversation sent to the text-message recipient sent as voice message. The recording is sent as if I were holding the "voice message" button on that users' conversation, which I obviously was NOT. This is obviously frustrating, as my private conversation got leaked to my other contact. The recording is exactly 5 minute long, probably because it is an hardcoded limit for voice messages, but I'm not sure? I listened to the recording, and I'm not sure which device the recording came from, given that I was using "handheld mode" on my phone. I have signal desktop installed on my Chromebook, as well as on my Samsung Galaxy S8 Android phone. Neither devices are rooted, both running regular versions of the operating system.

### Steps to reproduce
- Call someone
- Conversation doesn't get sent to 3rd party contact as voice message
- The end

**Actual result:** 
- Call someone on Android device
- Chat with someone on the Chromebook, using TEXT ONLY, while not even having the application in focus (for most of the call, I was actively typing in the Chrome web browser on the Chromebook)
- At some point in the call, the conversation somehow started being recorded, and after 5 minutes, got sent to chat contact as a voice message
- Call gets recorded for 5 minute, being sent after that period of time, meaning it stopped recording prior to the end of the call
- Message gets sent at the 5 minute mark
- End call
- Nothing specific happens

**Expected result:** My PRIVATE conversation does not get sent as a voice message to a 3rd party contact

### Device info
Android:
**Device:** Samsung Galaxy S8
**Android version:** 8.0.0
**Signal version:** 4.26.2

Chromebook:
**Device:** ASUS C302a
**Signal version:** 0.46.6

### Link to debug log
Android: https://debuglogs.org/fecfb425698ccda4f2988bcedfd4e66885192ec77e6c4ffc186ea4d92388fe96
Chromebook: https://debuglogs.org/acb61f4a8af276a4f0f4248ec6dba1a568bf2eb6756f2f6bff3742d688a0fa85

**Comment by ldionmarcil** [comment]
Additional info, the voice message was sent at 8:55 PM October 3 2018 EST. The call started at 8:25 and I'm not sure when it ended. I think at around 9:00 PM.

**Comment by jlund-signal** [comment]
Signal Desktop has been updated so that audio recording for voice messages automatically stops if you switch away from the app or hit the five-minute limit. Sorry about the inconvenience.

**Comment by jazir5** [comment]
@jlund-signal 

>Signal Desktop has been updated so that audio recording for voice messages automatically stops if you switch away from the app or hit the five-minute limit. Sorry about the inconvenience.

Is that behavior disablable? I want to be able to record if i switch away from the app and record for longer than five minutes. Can it just break them up into multiple clips? I.e. a 7:30 recording sends as two recordings, one 5 minute and the second a 2:30 minute recording?
