### ISSUE TITLE
Conversation colors inverted

### ISSUE THREAD

**Issue by KommX** [signalapp/Signal-Android#8245]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Situation until yesterday:
Every contact/conversation has a specific color, meaning that my contact's messages are red/blue/... in the conversation view. My messages all have the same color.
After updating to 4.28.0 the colors in my conversations are inverted, now my messages have a different color in every conversation but my contacts' messages all have the same color.
I hope that's not intended?!

### Steps to reproduce
- Update to 4.28.0
- Open any conversation

**Actual result:** My messages are _colorful_.
**Expected result:** My contacts' messages are _colorful_.

### Screenshots
![1](https://user-images.githubusercontent.com/7859245/46459658-d28af780-c7b9-11e8-9f0a-1b827630900e.png)
![2](https://user-images.githubusercontent.com/7859245/46459659-d28af780-c7b9-11e8-911a-d1d94766072b.png)

### Device info

**Device:** HTC U11 life
**Android version:** 8.1.0
**Signal version:** 4.28.0

**Comment by kreativmonkey** [comment]
Same problem here. I hope the whole thing is not so desired. 

# Device Info

**Device**: OnePlus 3
**Android version**: 8.1.0 (lineageOS)
**Signal version**: 4.28.0

**Comment by rainerzufall** [comment]
unfortunately it is an intended change. :( 
See: https://support.signal.org/hc/en-us/articles/360016466812-Frequently-Asked-Questions-about-the-recent-changes-to-conversation-colors

> **Why do colors now appear on outgoing messages in Signal Android?**
In group conversations, the color of a particular message bubble was the primary visual indicator of who sent the message. This would sometimes work in small groups, but colors quickly started to overlap when new members joined the conversation. With a large enough number of colors, we also moved past the limits of working memory.
> By shifting colors to outgoing messages and adding new functionality to choose a color for group conversations, we were able to bring the sender's name and avatar to the top of the visual hierarchy while making it easier to quickly identify which group you are in based on the group color and group avatar.

**Comment by jpds** [comment]
I also found this to be a poor choice, if a person in a group quotes another person, that quote is displayed with the owner's colour and not the gray of the original message.

**Comment by TichyTichyTichy** [comment]
This is truly unfortunate. Reading group messages is so much more difficult now. Colors used to make it easy to associate messages with people across different conversations.

**Comment by dgx** [comment]
What a strange design change. And to make it without a configuration option to restore original behavior! Madness!!

**Comment by schmeat** [comment]
I don't quite follow the logic of the change. Colours overlapped for larger groups and they were taken away so that no group can utilitize it? That doesn't really make sense to me. Why not expand the colour pallet to be user selectable then, rather than predefined by the developer.

**Comment by moxie0** [comment]
Please use the forums for discussion, thanks everyone.
