### ISSUE TITLE
Multi-hop mesh networking

### ISSUE THREAD

**Issue by metafarion** [signalapp/Signal-Android#8249]
https://github.com/signalapp/Signal-Android/issues/5501

This feature was brought up a few years back and dismissed curtly with no explanation at all.  Since the ability to send messages without any carrier at all would make this app tremendously more useful, I would like to suggest it again.

Is it not implementable with the Signal protocol as it exists right now, or is it simply a matter of excessive work/cost that makes it unfeasible?  As far as I know, no messaging app sports a combination of FireChat's connectivity and Signal's security.

**Comment by haffenloher** [comment]
Hey, please read the contributing guidelines before posting and don't delete the issue template when opening an issue. This issue tracker is only used for tracking bugs; the community forum is the place for feature requests and discussion. Thanks!

**Comment by metafarion** [comment]
Oh, sorry, I didn't even realize there were forums; they don't appear to be linked from the Signal site anywhere.

**Comment by greyson-signal** [comment]
@metafarion It's at the beginning of the issue template :wink: 

> Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.
>
>If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org
