### ISSUE TITLE
[4.28.0] Message detail for group message does not show delivery status anymore.

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8251]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In previous versions long pressing a message that I send in a group showed a delivery status for that message for every person in the group. This is missing in 4.28.0.

### Steps to reproduce
- send message in group
- long press message
- check delivery status

**Actual result:** No message delivery status is shown.
**Expected result:** Message delivery status is shown for every person in the group.

### Screenshots

![screenshot1](https://user-images.githubusercontent.com/25846829/46490075-47385300-c807-11e8-9190-a827135bc0ea.png)

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.28.0

### Link to debug log

If needed I can provide one.

**Comment by greyson-signal** [comment]
Thanks for catching this!
