### ISSUE TITLE
4.28.0: Minor UI issues

### ISSUE THREAD

**Issue by ForestGu** [signalapp/Signal-Android#8252]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

I noticed three minor issues with the new design changes. I hope this is useful. If not, feel free to close this. In that case: sorry for the noise.

### Bug description 1
The conversation with myself is colored differently than my profile avatar in the status bar.
![screenshot_20181004-191020](https://user-images.githubusercontent.com/13498303/46491509-3984cc80-c80b-11e8-8afb-8601fe45afd9.png)

### Steps to reproduce 1
- have a conversation with yourself
- [I don't know if this is required. I did not do so, but I might have done in the past: Change the color of the conversation with yourself]
- See your system avatar next the "Signal" text in the action bar and the conversation color. Those colors differ.
**Actual result:** Conversation with myself (purple) and my avatar in action bar (green) have different colors
**Expected result:** Conversation with myself (purple) and my avatar in action bar (green) have the same color

### Possible reason against fix 1
- It might be that the system avatar color matches the color that users see, who install Signal freshly, when they view my contact.  Then it might be that this my action bar icon and their contact of me match in colors.

### Bug description 2
The footer of shared contacts is barely distinguishable from background under bad light conditions.
![screenshot_20181004-191041](https://user-images.githubusercontent.com/13498303/46491852-2faf9900-c80c-11e8-877e-138042059eca.png)

### Steps to reproduce 2
- Share a contact OR receive a contact
- Have dark theme enabled
- View the shared/received contact in bad light conditions

**Actual result:** Contact footer and background really hard to distinguish
**Expected result:** Contact footer and background should be distinguishable

### Bug description 3
SMS/Text contacts not stored in address book have small icon in contact settings page.
![screenshot_20181004-191152](https://user-images.githubusercontent.com/13498303/46492234-3a1e6280-c80d-11e8-914f-d81806c0e811.png)

### Steps to reproduce
- Receive Text from anyone not in your address book
- tab the action bar in the conversation with them
- see small "person" icon

**Actual result:** Icon is small
**Expected result:** Icon should be big

### Screenshots
See above.

### Device info
**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.28.0

### Link to debug log
I submit a debug log because this issues are easily and reliable reproducible.

**Comment by greyson-signal** [comment]
Fixed 'em all. Thanks for the reports!

Note: You may have to clear your cache in order to have your profile background color update in the conversation list.
