### ISSUE TITLE
Signal notifications ignores do not disturb on Samsung A5 2016

### ISSUE THREAD

**Issue by GAS85** [signalapp/Signal-Android#8257]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Samsung Galaxy A5(2016) since a few updates Signal ignores do not disturb option. Message notification will produce vibration and/or sound (depends on settings/profile). 
Tested with Samsung Galaxy A5 - Problem reproduced.
Tested with Huawei Nova - no problem seen.

### Steps to reproduce
- Put phone on do not disturb mode.
- Send Signal message to this phone.
- Hear vibration and/or notification sound

**Actual result:** Signal ignores Du not disturb. Whatsapp did it also, but since last update has no issue any more.
**Expected result:** As soon as do not disturb mode is on - Signal should not produce any vibration and sound notifications on incoming messages, except from starred contacts if it is set in do not disturb settings.

### Device info

**Device:** Samsung Galaxy A5 2016 - SM-A510F
**Android version:** 7.0
**Signal version:** 4.26.2

### Link to debug log
https://debuglogs.org/132e3fc8da15b0dd5b6c45d065ecefa09269e987886d3a10ddc251e8138e553a
Debug log contains - outgoing and incoming message and call for testing purpose.

**Comment by torlarse** [comment]
same problem on Galaxy S9

**Comment by MatthewSteeples** [comment]
Same problem on Nokia 8 / Android 9

**Comment by GAS85** [comment]
Same behavior on Huawei Nova (CAN-L01C432) with Andorid 7.0

**Comment by mdentremont** [comment]
This is also affecting Pixel 2 on Android 9

**Comment by MatthiasKunnen** [comment]
OnePlus One on Android 9 too

**Comment by GAS85** [comment]
Huawei P20 and P20 Pro with Android  9 are also affected...

**Comment by MatthiasKunnen** [comment]
This seems to be an Android Pie bug rather than a Signal bug

**Comment by P0werGirl** [comment]
Having this issue on a Samsung S10 running Android 9.

**Comment by mimkorn** [comment]
Samsung galaxy note 8, android 9 same issue

**Comment by DaveDubUK** [comment]
This issue has re-surfaced on Android Galaxy Tab S4 SM-T835N Android Version 10
 - Text message notifications sounding when DND is enabled
"Ignore Do Not Disturb" option ensured not enabled
Ensured Signal not added to DND exceptions
Extra info: Non default notification sound has been selected

**Comment by jonocodes** [comment]
Same here. Samsung Galaxy S7. Android 8

**Comment by seguri** [comment]
Same on Xiaomi Mi9T, Android 10

**Comment by PaulNacamuli** [comment]
OnePlus 6 and 6T.  Happened on Android 10.  Still happens on 11.

**Comment by saurabhs** [comment]
OnePlus Nord, Android 11

**Comment by Otiel** [comment]
Issue is still relevant.

**Comment by Mariusmssj** [comment]
Yep I'm also experiencing this on my pixel 7

**Comment by koyuawsmbrtn** [comment]
Still an issue, Nokia G21, Android 12

**Comment by hboetes** [comment]
I just woke up because of this bug, please fix it.

**Comment by nicholas-signal** [comment]
> I just woke up because of this bug, please fix it.

If you are still having this issue, please submit a new GitHub Issue with a debuglog URL. Thank you!
