### ISSUE TITLE
Dark theme background should be black, not gray

### ISSUE THREAD

**Issue by aibaraiduas** [signalapp/Signal-Android#8261]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The background of chats in the dark theme is gray, not black.

With all the color and UI changes of late I wasn't sure if this was actually a bug, but then I found that this bug had popped up before and was fixed ([see #3584](https://github.com/signalapp/Signal-Android/issues/3584)).

This is even more problematic now that in 4.28 the received messages are gray: the gray-on-gray makes them harder to identify and read than if they were on a black background.

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.28.1

**Comment by DonDino2** [comment]
Same with me, background in dark mode is not entirely black on S7 Edge.

**Comment by greyson-signal** [comment]
This is intentional. It's a subjective visual improvement, but it's one that I really appreciate. If you think the problem was made worse by the color swap change, then it should be improved by the recent commit that switched it back. 710fa4a6f08d1b3f974ccbfe3477351c42c0b9a0
