### ISSUE TITLE
Voice messages don't get downloaded automatically

### ISSUE THREAD

**Issue by mnns** [signalapp/Signal-Android#8262]
Each time a person sends a voice message, I need to manually download it. No matter the settings. No, I'm not roaming, it's also on WiFi.

**Comment by haffenloher** [comment]
When you open an issue, GitHub should show an issue template that lists all the info required for someone to investigate your problem. If you're using some third-party GitHub client that doesn't support issue templates, you can find the template [here](https://github.com/signalapp/Signal-Android/issues/new). Please fill it out and provide a debug log. Thanks!

**Comment by greyson-signal** [comment]
Is this person in your contacts? For security reasons, we don't auto-download attachments from people not in your contacts.
