### ISSUE TITLE
Screen Security not working on OnePlus 6 / OxygenOS 9.

### ISSUE THREAD

**Issue by matrix8967** [signalapp/Signal-Android#8263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While Screen Security is enabled I'm still able to take screenshots of the app. OnePlus 6 Oxygen OS 9.0

### Steps to reproduce
- Open Signal and enable Screen Security
- Attempt to take a screenshot of a conversation.

**Actual result:** Screenshot is successful.
**Expected result:** There should be a notification that the screenshot has been blocked.

### Device info

**Device:** OnePlus
**Android version:** 9.0 / OxygenOS 9.0
**Signal version:** 4.26.2

### Link to debug log

https://debuglogs.org/fbc2aab7cbc55d6504eba54fb8d8bcc32e03a26e4c25790d35c5b5a088cc90b3

**Comment by alpha14** [comment]
I have the same issue with the latest Signal version (4.29.7)

**Comment by matrix8967** [comment]
This looks like it's been fixed now. 4.31.6
