### ISSUE TITLE
Increase MMS Limit - FEATURE UPDATE

### ISSUE THREAD

**Issue by usmarine2141** [signalapp/Signal-Android#8264]
- [X ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------
Can the limit of GIFS and MMS Messages be increased greater than the 25mb limit? Unable to send some GIF's

**Comment by jlund-signal** [comment]
MMS size limits are typically enforced by the various carriers, and the Signal-Android issue tracker on GitHub is only used for bugs.

We use the [community forums](https://community.signalusers.org/c/feature-requests) to track and share other feature requests. Please feel free to discuss your idea in more detail there. Thanks!
