### ISSUE TITLE
Default to SMS when a friend had a Signal app but has deleted Signal

### ISSUE THREAD

**Issue by ryanpeach** [signalapp/Signal-Android#8265]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My friend had Signal installed, and now does not. I use signal as my default sms app. Signal has not detected that the user no longer has Signal installed, and keeps sending messages to his Signal, which he obviously does not get. I can send him SMS messages manually from the app, but I have to remember to make this change every time I open the app. I also can not make this choice when replying via notification actions. Either this behavior should be fixed, or defaulting to SMS should be an option between users.

### Steps to reproduce
- Install signal on a friends phone
- Send a message to him
- Delete it from his phone
- Send a message to him

**Actual result:** It goes to Signal and he does not receive it.
**Expected result:** It goes to SMS as Signal is no longer installed.

### Device info

His info is unknown. I believe in his case it is an iOS Phone. In my case it's Android, Galaxy S8+

**Comment by greyson-signal** [comment]
Have they unregistered? 
https://support.signal.org/hc/en-us/articles/360007061192-Unregister-or-Delete-Account

**Comment by ryanpeach** [comment]
So, the answer is no. But I still believe this is an issue. Because if you use the app as a primary texting platform and you have a friend that let's say is "uncooperative" that should not ruin the app for you. At the moment, I've had to switch back to my phones default texting platform because of this.

If unregistering is required, then I believe we need an option by contact to default send to SMS. Otherwise, because of more than one stubborn "tried it didnt like it" friends now I cant use the app.
________________________________

**Comment by greyson-signal** [comment]
Detecting uninstalls and deciding when to unregister an account is a tricky problem. We basically have the same problem as apps like iMessage. Right now, your best bet is to tell friends to unregister using the link in the support page I linked. Beyond that, potential solutions should be discussed in the forum. Thanks!

**Comment by radasbona** [comment]
A tricky problem? 
Auto switch to sms when a account is 7 or 10 days offline.
Auto delete an account when it is one year off. 

Tricky?
