### ISSUE TITLE
"See Full Conversation" text is difficult to read(low font color and background contrast) in light theme

### ISSUE THREAD

**Issue by brs17** [signalapp/Signal-Android#8266]
- [x] I have searched open and closed issues for duplicates by searching `is:issue "see full conversation" `
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The "See full conversation" button that appears when scrolling to the top of a large conversation is difficult to read in the light theme due to the grey background clashing with the white text. See screenshot below. This UX/UI bug is not present in the dark theme of the program.

### Steps to reproduce
- In a large conversation, scroll to "See full conversation" message.

### Screenshots
![seefullconversation](https://user-images.githubusercontent.com/7460774/46709450-15592f00-cc01-11e8-86b6-df21a0327966.png)

### Device info

**Device:** LG Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.28.1

**Comment by greyson-signal** [comment]
This should have been resolved in 710fa4a6f08d1b3f974ccbfe3477351c42c0b9a0 (recently pushed). Thanks!
