### ISSUE TITLE
Wrong Avatar Color in Action Bar

### ISSUE THREAD

**Issue by ForestGu** [signalapp/Signal-Android#8270]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Hello again, thanks for fixing the issues I reported last time. However, one of the issues did not get resolved fully.
### Bug description
The avatar color in the action bar is **sometimes** still wrong directly after swiping Signal out of the recent apps. It does not happen always, but it might be related to any deeper app-close from Android. Wrong means to me not equal to the conversation color set by myself.

After opening any other activity from the Signal home screen and going back, this bug does not appear (until closing Signal again by swiping it out of recent apps).

I did try to clear the cache. Then, the bug did not appear for a short time only.
See my legacy bug report #8252 and the fix #eb11d5c 
### Steps to reproduce
- Swipe Signal out of recent apps (close)
- Open Signal and view avatar (green instead of purple in my case)
- Go to any other activity (e.g. open a conversation)
- Go back and view avatar (purple as intended in my case)

**Actual result:** Step 2: Green instead of purple
**Expected result:** Step 2: Purple as set in conversation color.

### Screenshots
left to right: Open and go to activity and go back.
![screenshot_20181010-195202](https://user-images.githubusercontent.com/13498303/46756648-3afd3b80-ccc8-11e8-8bf6-1cca64767d7c.png)

If I'd take a guess, the line
180 Recipient     recipient     = Recipient.from(this, localAddress, true);
might give an "empty" recipient because the database loading is slow. In that case, there might not be any good way to prevent this.

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.28.1

### Link to debug log
https://debuglogs.org/da014b0bbd11f8f0389ab0b2615d3667f6329dcdad474156bc680a4612176751
I started the app at 20:21 when the bug occured. Closing before was 20:20.

**Comment by greyson-signal** [comment]
Fixed in 4.30.
