### ISSUE TITLE
recover (after reinstall) missed the file on external SD card !!

### ISSUE THREAD

**Issue by drandreaskrueger** [signalapp/Signal-Android#8271]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal did not find the backup 

### Steps to reproduce
- backup Signal on android 7.1.2
- wipe phone, install android 8.1.0
- install Signal

**Actual result:** it does not find the backup

**Expected result:** it finds the backup; after reinstalling and restoring, I can continue where I left off.

### Device info

**Device:** Samsung S5 
**Android version:** 8.1.0
**Signal version:** 4.26.2

---------

After a bit of panic, of having lost years of communications, I found this workaround:

* manually copy 
* the signal backup file 
* from `externalSDcard/Signal/Backups/signal-2018-10-....backup` 
* via my laptop, USB cable
* to `Internal shared storage/Signal/Backups/signal-2018-10-....backup`

then when reinstalling Signal, the backup could be restored. Very relieved.

------

Please consider to

* --> work on your backup/restore system, to recognize backup files on external SD.  
* --> show the exact file path of the written backup file on the screen, when the backup is finished.
* --> add a new function "restore from backup now", to trigger that without remove-reinstall
* --> when restoring, show the file path(s) where Signal is searching for backup files. 

Thanks.

**Comment by greyson-signal** [comment]
Support for backups on external SD cards was removed [back in 4.23](https://github.com/signalapp/Signal-Android/commit/18756aedf6c5bec1e8abd3789710cc5d59d7e090). Did Signal store a backup on the external SD card? If so, can you explain more about how you have your external SD card setup? Is it setup to mimic internal storage?

**Comment by drandreaskrueger** [comment]
> Support for backups on external SD cards was removed back in 4.23. 

Do people think through all consequences of their decisions? Probably not. How stupid ...

Yes, perhaps that was the cause of this problem then.

Perhaps like this: My old system stored the backup on external-SD, and then the new system then could not find the backup on the internal storage. Sounds likely, no?

And thus, years of communication just disappeared - had I not been clever enough to find this workaround.

Be aware, that 95% of other **users will have lost their backups** because you removed support for external SD cards.

My advice: DO NOT JUST REMOVE FEATURES WITHOUT CHECKING ALL POSSIBLE SITUATIONS AFTERWARDS,

> Did Signal store a backup on the external SD card?

Yes.

That is where I found it, and from where I copied it into the internal storage of the new phone - after hours of googling, and searching, and and and ...

> how you have your external SD card setup? Is it setup to mimic internal storage?

I don't know what that means. It's a large microSD card, in default setup.

**Comment by drandreaskrueger** [comment]
And again: Please consider to

* --> show the exact file path of the written backup file on the screen, when the backup is finished.
* --> when restoring, show the file path(s) where Signal is searching for backup files. 

Thanks.

**Comment by drandreaskrueger** [comment]
Plus:

* --> Show a help/info message in the "backup/restore" area of the settings "Support for backups on external SD cards was removed; please copy backup to internal storage via USB cable"

**Comment by drandreaskrueger** [comment]
Plus:

* --> document this problem in your FAQs!  

Most people won't read it, but some will. Then you can reduce the 95% of people losing their backup to perhaps 90% people losing their backup, which is already a big step forward. 

Thanks.

**Comment by UserX404** [comment]
Hello!
Uninstall your Signal, create a directory on your internal storage SIGNAL/Backups/ and copy your existing backup from SD to this directory. Afterwards install Signal and you should be able to restore.
cheers ;-)

**Comment by greyson-signal** [comment]
@drandreaskrueger Signal backups, once enabled, are set to routinely run every day. So the thought with removing external SD card support was that the backup would effectively be moved by itself. Here's some possible reasons I can think of where things may have gone wrong:

- You moved from an old  (< 4.23) client that was never updated to a newer client (>= 4.23).
- You enabled backups, created a single backup, then disabled it.

Based on your report, it sounds like it may be worthwhile to guard against this by supporting reading backups from external storage, even though we don't write to them.

@UserX404 Be sure to copy your backup _before_ doing that. The whole reason we moved away from using the external SD card is that we discovered that Android wipes that directory after an app uninstall.

**Comment by drandreaskrueger** [comment]
and?

**Comment by guillaumedc** [comment]
> @UserX404 Be sure to copy your backup _before_ doing that. The whole reason we moved away from using the external SD card is that we discovered that Android wipes that directory after an app uninstall.

It's not the case anymore. It probably depends on how you access external storage.
For example, I'm using OSMAnd and I store the maps files on external SD. Even if I remove the app, the files remain.

Can you consider to reintroduce backup/restore on external SD if app uninstallation does not wipe this storage anymore, please?

**Comment by marc-h38** [comment]
A great alternative to transfer files from phone to phone is Google's "Files Go" application. It makes peer to peer Wifi a breeze, zero configuration required.

Except for this weird issue which wasted my time and made me wrongly suspect Signal for hours:
https://support.google.com/files/thread/24804388?hl=en
"Warning: ".bin" file extension sneakily added on copies and moves"

You've been warned!

**Comment by drandreaskrueger** [comment]
Thanks everyone. And: Signal is still the greatest of them all. Very happy about this app. Have a good life.
