### ISSUE TITLE
Crashed by null object reference

### ISSUE THREAD

**Issue by biplabbh** [signalapp/Signal-Android#8272]
### Bug description
  Application is crashing at the time of start. it is throwing the following error:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.makeramen.roundedimageview.RoundedDrawable com.makeramen.roundedimageview.RoundedDrawable.setScaleType(android.widget.ImageView$ScaleType)' on a null object reference

### Steps to reproduce
- open the app
- see the crash
- does not crash all the times.

**Actual result:** App Crashed
**Expected result:** It should have opened the application properly. Sometimes it is getting crashed.

### Device info
**Device:** Xiaomi note 4
**Android version:** 7.0.0

**Comment by biplabbh** [comment]
any update sir?

**Comment by piratenpanda** [comment]
I suggest to provide a full log forthe developers. Also this is not a forum. So please refrain from asking after just one day.

**Comment by greyson-signal** [comment]
I'm unable to reproduce the crash on my 7.0 device. Please provide a debug log.
