### ISSUE TITLE
Relaunching the app after opening a conversation takes the user back to the conversation list activity

### ISSUE THREAD

**Issue by jpinsonault** [signalapp/Signal-Android#8273]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a user is in a conversation, leaves the app, and relaunches it from the Android launcher, the app reopens to the conversation list screen instead of resuming the conversation.

I waffled back and forth on whether this is a feature request or a bug. I decided on bug because I couldn't find any other messaging app with this behavior. I don't believe the app would be intended to work this way (happy to be told otherwise though). For example, hangouts, gmail and facebook messenger will all reopen to whatever screen the app had open instead of clearing the activity stack.

### Steps to reproduce
- Open Signal from the android app drawer
- Tap on a conversation
- Press the Android home button
- Open Signal from the android app drawer

**Actual result:** The app reopens to the conversation list screen (the main activity) instead of the conversation the user was just looking at. As if the app had been fully closed and re-launched
**Expected result:** The app reopens back to the conversation the user was looking at

### Device info

**Device:** Moto X4
**Android version:** 8.0.0
**Signal version:** 4.28.1

**Comment by five-c-d** [comment]
An important thing to improve methinks, although I am not positive the suggested pull request is the optimal way to implement the bugfix.  https://community.signalusers.org/t/made-clicking-the-app-from-the-home-screen-actually-return-to-the-conversations/4446 is where design-discussion is happening.  

* https://github.com/signalapp/Signal-Android/issues/1311#issuecomment-91658839 , this exact bugfix was suggested in 2015 
* https://github.com/signalapp/Signal-Android/issues/5725#issuecomment-250213029 , however not everybody agrees it needs fixing 
* see cautionary note here, https://github.com/signalapp/Signal-Android/pull/1322#issuecomment-43367935 , about the dangers of subtle backstack modifications 
* is it still the case that app-wide shared data is a design-constraint?  https://github.com/signalapp/Signal-Android/issues/1532#issuecomment-44493385  

Although #1311 was closed-by-bot earlier this year, it was still actually open and perhaps being worked on ("moxie0 assigned mcginty on Apr 7, 2014") but I am not sure if that is still the case ("mcginty removed their assignment on Nov 16, 2015"), nor whether any progress was made in terms of actual code being written back in 2014/2015.   Not sure whether I should '@' mention anybody, given the unclear status of this bugfix, so just linking to the old issues for now  :-)
