### ISSUE TITLE
Voice message recording stops, when screen orientation changes by (accidentally) tilting device

### ISSUE THREAD

**Issue by xuiqzy** [signalapp/Signal-Android#8276]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When recording a audio note / voice message and the screen orientation changes by tilting the device (e.g. accidentally while walking), the recording stops and the unfinished message is sent.
The old unresolved issue reporting this, that was closed in the spring cleanup is #6455.

### Steps to reproduce
- Start recording voice message to someone
- Tilt device so orientation changes

**Actual result:** Unfinished voice message gets sent as soon as the orientation changes, even though finger is not lifted from screen.
**Expected result:** Voice message recording continues normally until finger is lifted from screen.

### Device info

**Device:** OnePlus 3T
**Android version:** 8.1.0
**Signal version:** 4.28.1

**Comment by Pratiwir** [comment]
Yes, I can confirm the same in Signal 4.31.6. The annoying thing is that if you suddenly turn your body sideways it can trigger screen rotation. There is no sensing of rotation as opposed to sideways acceleration on phones. Finger off that screen point id the key.
 It is a fault on the same level as menu lists refreshing just before a press and then using the new list for a selection.

**Comment by xuiqzy** [comment]
@Pratiwir But I think in contrast to the general press after menu refreshing problem, here the fix is reasonably easy to implement, either lock the rotation or otherwise prevent the recording from stopping until the finger is lifted.

Still a problem in Signal version 4.39.2, same device and Android version.

**Comment by ant0nwax** [comment]
I also have the issue on Samsung Note 8 on Android 9...
I have an Idea for workaround... before recording starts you could LOCK TILT and after recording finished the TILT can be UNLOCKED.
The issue is that when you touch the recording microphone and phone screen tilts, your thumb or index finger does not touch that button anymore

**Comment by PockelHockel** [comment]
Yes, I can confirm everything from above

**Comment by ant0nwax** [comment]
i still have signal uninstalled and waiting for basic things like this
being fixed

**Comment by codeinabox** [comment]
Is there any update on this issue? I am still experiencing this with version 6.30.2

**Comment by lennartkloock** [comment]
> Is there any update on this issue? I am still experiencing this with version 6.30.2

It should be fixed since 3 years.

**Comment by cody-signal** [comment]
We made a change in 6.30.x that reintroduced this bug. It was revert in 6.30.4

**Comment by codeinabox** [comment]
I am experiencing this bug with version 7.26.1

**Comment by Mjng** [comment]
Me too: 7 25 2 Android

**Comment by Mjng** [comment]
Disable auto rotate on ur device will stop this annoying behavior

**Comment by lennartkloock** [comment]
Was it reintroduced again?

**Comment by Mjng** [comment]
Sadly yes, I know of three phones already.

**Comment by lennartkloock** [comment]
Can't reproduce on my device (Android 14) on version 7.27.0

**Comment by Mjng** [comment]
Voice recording start by press - release. Turn phone, then message  is vanishing.
Using s10e with 12 and SEE with 14 version, both same hiccup

**Comment by olebughouse** [comment]
I can also reproduce the issue on my Samsung Galaxy S23 (SM-S911B/DS) with Signal version 7.63.3 installed. It seems to be that the bug came up again an still persists.

**Comment by alexleonard** [comment]
Still happening Samsung Galaxy S25 Ultra and Galaxy S21 FE
