### ISSUE TITLE
Notification issue on OnePlus 3t latest update on official rom

### ISSUE THREAD

**Issue by Godmorgonsverige** [signalapp/Signal-Android#8277]
Is it the same issue that Huawei has on issue 
#5447 ? Or is it signal thats isn't working like it should notifications arrive when you open the app I have tried to disable battery optimization on the app mayby that it is fixing it I need to test more? Shouldn't signal tell effected phones to disable battery optimization or on Huawei side I think is called protected app or something

**Comment by greyson-signal** [comment]
I'm sorry, but I don't understand your issue. It doesn't follow our template at all. Following that template is very important -- we need to know things like Signal version, Android version, a debug log, etc. Please open a new issue and fill out the template. Thanks!
