### ISSUE TITLE
SMS messages received in airplane mode can be displayed out of order

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#8279]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS messages sent to the user while the phone was in airplane mode are shown in reverse chronological order in the conversation, even though the sent times are different.

### Steps to reproduce
- Phone in airplane mode for a few hours
- Receive 2 SMS messages from user on same network while in airplane mode.
- Re-enable network a few hours after messages were received (queued).

**Actual result:** Second (newer) message is displayed first, followed by the first (older) message.
**Expected result:** Older (first) message should be displayed first, then the newer (second) message.
The messages have different Sent times in the Message details, so it should be possible to filter the order based on the Sent time, not on which one downloads first.

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.26.2

**Comment by Viperized** [comment]
Hello, I've posted a comment about I think same issue here in this other thread:

https://github.com/signalapp/Signal-Android/issues/9088#issuecomment-585657478
