### ISSUE TITLE
Notification bar looses grey color in multiselect

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8282]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See "Steps to reproduce". This does not happen for multiselect in conversation list and media overview.

### Steps to reproduce
- Open one conversation
- Long click on message (Action bar and notification bar are now grey)
- Leave app with "Latest apps" button
- Select signal

**Actual result:** Action bar is grey, but notification bar has the conversation color.
**Expected result:** Action bar and notification bar should be grey

### Device info
**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.26.2

### Link to debug log
Not attached as it happens every time for me, but I can add one if needed.

**Comment by neunzehnachtneun** [comment]
With version 4.29.7 installed I can confirm this.

**Device:** Moto X Play
**Android version:** 7.1.2, LOS 14.1
**Signal version:** 4.29.7

**Comment by Sgn-32** [comment]
With version 4.55.6 this is reproducible.

**Comment by Sgn-32** [comment]
Tested again with 5.4.12. The different colors should be resolved.
