### ISSUE TITLE
In multiselect notification and action bar aren't colored at the same time

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8284]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The notification bar is colored noticeably earlier than the action bar. This applies to all multiselets (conversations, messages, media).

### Steps to reproduce
- Long click a conversation, message or media

**Actual result:** The notification bar is colored noticeably earlier than the action bar.
**Expected result:** The notification bar and action bar should be colored at the exact same time.

### Device info
**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.26.2

### Link to debug log
Not attached as it happens every time for me, but I can add one if needed.

**Comment by greyson-signal** [comment]
The notification bar color can't really fade, whereas the default behavior of the action bar is to do a fade transition. So they're set at the same time, the action bar color just fades in. 

This is consistent with other apps that have the same multi-select behavior (like Gmail), so I think it's fine.
