### ISSUE TITLE
Swipe-to-archive is difficult for left-handed users

### ISSUE THREAD

**Issue by frozencemetery** [signalapp/Signal-Android#8285]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Making the natural swiping motion doesn't perform the same thing when performed by the left or right hands.  The "swipe right and only right to archive" paradigm is unnatural for the left hand, and I'm sure is accidental.

### Steps to reproduce
- Open Signal to conversation view (e.g., from Android home screen)
- Press and slide left over a chat.

**Actual result:** Conversation/chat is selected.
**Expected result:** Conversation should be archived (i.e., what happens if I slide right).

### Device info

**Device:** Motorola moto G6
**Android version:** 8.0.0
**Signal version:** 4.26.2

**Comment by greyson-signal** [comment]
Hi there, we're currently hesitant to make archive accessible via both swipe directions in case we want to make right-to-left swipes to do something else. However, I encourage you to start a post on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests) to discuss this and any other feature changes. Thanks!
