### ISSUE TITLE
Car Control / Android Auto - Integration

### ISSUE THREAD

**Issue by ghosted17** [signalapp/Signal-Android#8286]
This app really needs basic car control or/and android auto integration. When you receive a phone call there is no way to reject or answer using steering control and it blocks the phone view until the car has ended. This makes it very unsafe when driving

**Comment by greyson-signal** [comment]
As noted in the issue template, Github is only for bug reports. Please discuss feature requests on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
