### ISSUE TITLE
Some long SMS (more than 160 characters) are received cut

### ISSUE THREAD

**Issue by todoesUno** [signalapp/Signal-Android#8289]
### Bug description
Some long SMS (more than 160 characters) are received cut (and unordered)

### Steps to reproduce
- Receiving long SMS (more than 160 characters)
- 2 or more long SMS at the same time
- The sender of the SMS is the same (I don't know if the requirement of the same sender is essential or not)

Actual result: Instead of receiving the whole long SMS, I receive several SMS cut

When I use the native SMS manager I receive the long SMS ok.

### Device info
**Device:** Fairphone FP1U
**Android version:** 4.2.2
**Signal version:** 4.26.2

Edited (**Update 21 Oct 2018** ) : 
I have noticed that, when long SMS messages are shown cut off, they are always in the wrong order. Other times SMS messages are shown complete in Signal.

So maybe it is not Signal's fault, but the SMS server, which sends the messages in the wrong order sometimes. (?)

Edited (**Update 26 Oct 2018** ) :

I think the problem might be related to this issue: https://github.com/signalapp/Signal-Android/issues/8279
("_SMS messages received in airplane mode can be displayed out of order_")

Maybe Signal does not receive the SMS messages in the correct order when there are several SMS in the queue.

**Comment by igor2x** [comment]
160 is max limit of SMS message. If message is larger then 160 characters then it is send with multiple SMSs. In this case first message is 153 characters long and the rest is in second message. For e.g. 161 characters, first message is 153 characters and second one is 8 characters.

Some of the native SMS applications supports this "dividing" messaging, some do not. Your native SMS app is probably capable of recognizing two SMS's belong together and display them like it is only single SMS.

But this is only true for English only characters. If text consists of one single non-English character (almost all places in the world) then the message is shorter, it can be only 67 characters long. Multiple SMS can be send way sooner then one may expect.

Maybe there is a way to check if message is 153 characters or 67 characters long and if it is, there is probably a text from multiple parts of larger logical message.

Don't know if this is official reason for being a bug or is maybe feature request. Lets wait if developers have something to say on this bug report.

**Comment by kyelbek** [comment]
@igor2x wow, man. Merging multiple SMS messages into one was introduced at least in polyphonic Nokia phones. Signal should be able to receive all parts and merge them with proper order. I'm not an expert but these messages should be properly tagged (like ethernet packets) so Signal and other SMS apps should recognise them properly (SMS = 160 chars but when splitted then first one is 153 so rest of remaining characters are probably used to tag them). We live in smartphone era so for me it is ridiculous if SMS app can't handle this properly. Correct me if I'm wrong.
