### ISSUE TITLE
Allow custom mute notification times and make the current ones more useful

### ISSUE THREAD

**Issue by grrrrr** [signalapp/Signal-Android#8291]
- [x] I have searched open and closed issues for duplicates
- [x]  read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

The current `mute notification` times come across as oddly chosen.  At the moment they are

* 1 hour
* 2 hour
* 1 day
* 7 days
* 1 year.

It would be useful to have a middle ground between 2 hours and 24 hours and a custom option.  In #5507 (closed as a result of #7598 cleanup)  I made the suggestion of

> Custom time would be great but I think the following would be useful
>
> 1 hours = meeting
> 2 hours = meeting
> 8 - 10 hours = over night (for me 12 is a little too long)
> 1 day = leave me alone.

And then have a custom option to cover other eventualities

**Comment by greyson-signal** [comment]
Hi there, thank you for the suggestion, but the original issue was cleaned up because we've moved to a model where github is exclusively used for tracking bugs. Please move this discussion to [the forums](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
