### ISSUE TITLE
Letters in contact circle might not be initials

### ISSUE THREAD

**Issue by bepaald** [signalapp/Signal-Android#8293]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since an update this morning, contacts with no avatar (99% of mine) have gotten an extra letter in their circle. In The Netherlands, it is extremely common for surnames to have a _tussenvoegsel_*, which is generally not capitalized and not really considered part of the surname (for example when indexing). A well known example would be Vincent van Gogh, who would be indexed under 'G', and his initials would be 'VvG', or, if there are size constraints, 'VG'.
Right now, with a large list of Dutch contacts, many appear as 'Lv', 'Pv', 'Wv', and 'Pd'. Using this (lowercase) first letter _tussenvoegsel_ as an identifier looks, at best, extremely weird, and possibly just plain wrong.
Obviously, this is only a bug if the intended behavior is to show a persons initials in that circle, if it is just to have more defining characteristics in that circle from any random letters from the name, then this report could probably simply be closed.

*Optional reading: [English wiki: tussenvoegsel](https://en.wikipedia.org/wiki/Tussenvoegsel)

Possible solutions:
- Don't care and ignore this. I'm serious, though it bothers me a great deal I have to admit it's a small issue.
- Ignore any lowercase letters. This would work for The Netherlands, but I don't know how capitalization is done in these cases in other countries (e.g. Belgian 'van Damme', German 'von Beethoven', Italian 'di Caprio', etc.), and wether it is acceptable as an initial if they do capitalize the _tussenvoegsel_.
- Just stick to one single letter and close this can of worms! This is my preferred solution, though I understand why the change was made.

Thanks for all your time and hard work!

### Steps to reproduce
- Add contact 'Ludwig von Beethoven', without avatar

**Actual result:**
Shows up as 'Lv'

**Expected result:**
All of 'LvB', 'LB', or just 'L', would be better than 'Lv'

### Device info
**Device:** Sony Xperia Z5C
**Android version:** 7.0
**Signal version:** 4.29.4

**Comment by PiCob** [comment]
Additionally it's worth to point out that if you have a contact without avatar named "Alice (Home)", you'll end up with initials like "A(" in the circle (which doesn't make sense).

**Comment by greyson-signal** [comment]
@bepaald After weighing the pros/cons of 1 vs 2 initials, we decided to stick with two. however, I appreciate you taking the time to explain this situation!

@PiCob Thanks for catching this! It was addressed in f164ac90dbd2d9f50b94f056bf7c8fe1f95e94b9.
