### ISSUE TITLE
[I would like to propose to re-open] Button to discard message #6548

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#8294]
I would like to propose to re-open one of the (several) proposals to add a "delete input" "X" button in the input line: https://github.com/signalapp/Signal-Android/issues/6548

(remark: the #6548 and other old proposals are "locked" for discussion, so this has to be filed newly. The former maintainer was very strict in closing this and further proposals, perhaps a new, more relaxed policy allows to re-open older proposals now and then. This would be very nice.)

**Comment by greyson-signal** [comment]
Our policy is to only use Github for bugs. I encourage you to bring this discussion to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
