### ISSUE TITLE
Possible to bypass the periodic PIN request

### ISSUE THREAD

**Issue by luontokoodaus** [signalapp/Signal-Android#8295]
I was able to bypass the periodic 4 digit PIN request by just pressing the back button on my HTC U11+

That allowed me to send my contacts messages, access settings and the rest of the app.

**Comment by moxie0** [comment]
You can dismiss it, but it will just prompt you for it more often as a result. As it says on the dialog, the purpose is to help you remember the PIN, not as a security feature.

In the future, please do not delete the issue template when filing issues, thanks!
