### ISSUE TITLE
Self-send messages are not synced to linked devices.

### ISSUE THREAD

**Issue by brad2014** [signalapp/Signal-Android#8300]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A message sent to myself on signal-android does not appear on signal-desktop.  Note that the reverse works: a message sent to myself on signal-desktop correctly gets synced to my signal-android app.

### Steps to reproduce
- link signal-desktop to signal-android
- On signal-desktop, send a message A to self.
- On signal-android, send another message B to self.

**Actual result:** 
- On signal-android, notice that the message A and B are both sent and received.
- On signal-desktop, notice that only message A is sent and received.

**Expected result:** 
- Message should be sent and received on all linked devices.  Linked devices should show identical message streams for each conversation, including self.

### Device info

**Device:** nextbit robin
**Android version:** 8.1.0
**Signal version:** 4.26.2

**Comment by greyson-signal** [comment]
FWIW Signal-Android has never synced self-sends.

**Comment by brad2014** [comment]
Just for the record, my use case for self sends is to securely transmit a note or attachment between desktop and phone.  Currently desktop->phone works, and phone->desktop doesn't.

**Comment by Xashyar** [comment]
> FWIW Signal-Android has never synced self-sends.

@greyson-signal 
not just self-sends but also other-sends aren't synced with desktop (**4.29.7**)

**Comment by hiqua** [comment]
Related: #4844.

**Comment by 2-4601** [comment]
c2a86fcc7480c417809302299f19689d1a717499
