### ISSUE TITLE
contact name of "self" number not appearing in linked devices

### ISSUE THREAD

**Issue by brad2014** [signalapp/Signal-Android#8301]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The contact list display name for my "self" phone number is not being displayed by linked devices, so my signal-desktop is incorrectly showing the sender profile name, when it should be showing the contact list display name (as it does with every other number).

I cannot tell if the contact list name is not being transmitted by signal-android, or it is being discarded by signal-desktop.

I believe this is a recent regression.

### Steps to reproduce
- In android contacts, create contact entry for self with full name and mobile number.
- In signal-android Settings->Profile Info, set self name to just first name ("brad"), and set photo.
- On signal-desktop, "Import all Signal groups and contacts from your mobile device."
- On signal-desktop, in search bar, type self mobile number, and notice profile info name.  Search any other number, and notice android contact list display name.

**Actual result:** 
- On signal-desktop, notice that search result has profile photo and just first name (*~brad*).
- For any other phone number, the contact list full name is presented (the sender profile name is only used if the contact list does not contain an entry).

**Expected result:** 
- Signal-desktop should receive and present the android contact list display name for the self number, just as it does with any other number.

### Device info

**Device:** nextbit robin
**Android version:** 8.1.0
**Signal version:** 4.26.2

**Comment by greyson-signal** [comment]
I think I fixed this during the note-to-self changes.
