### ISSUE TITLE
Loud hissing sound during calls

### ISSUE THREAD

**Issue by breversa** [signalapp/Signal-Android#8303]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When calling someone (we're both using the same devices/OS), a hissing sound is heard, getting progressively louder and making the experience so uncomfortable that we gave up calling using Signal altogether.

### Steps to reproduce
- Call the other person using Signal

**Actual result:** After a few seconds, the hissing starts and gets louder and louder. The hissing might get quieter but will eventually come again.
**Expected result:** No hissing, crystal-clear privacy-friendly voice call :)

### Screenshots
N/A

### Device info

**Device:** LG G4 H815 (both of us)
**Android version:** 7.1.2
**Signal version:** 4.29.4

Might it be linked to echo cancellation ?

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
