### ISSUE TITLE
China, no VPN, Pixel 2: can receive, but cannot send messages

### ISSUE THREAD

**Issue by bsblmn4** [signalapp/Signal-Android#8306]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can receive, but cannot send messages in China without a VPN from a Pixel 2

### Steps to reproduce
- Try to send a Signal message in China without a VPN from a Pixel 2 

**Actual result:** Message does not send, but the circle to the right of the text just keeps spinning.
**Expected result:** Message sends and the circle receives a check mark on the inside. 

### Device info

**Device:** Google Pixel 2
**Android version:** Both Android 8 and 9 had this issue.
**Signal version:** 4.29.5

### Link to debug log
 https://debuglogs.org/ea83085e8c86b468d4801b77822d72b54c1d7a9bb64dae568835ebaac6ecd715 

Additional information:
Above is the debuglog.  The log covers time when the the VPN was not connected and when it was connected.  When the VPN is connected, Signal works correctly.  When it is not connected, messages can be received, but cannot be sent.  For further comparison, here is the log from my Huawei phone.  It does not utilize a VPN, does not have Google Play Services, and Signal sends and receives messages without any problems.  Here is the Huawei log: (https://debuglogs.org/fe83cd09268c84f9a23240e9f7d08c3eda152272f4a56d5e2f3ff41b2afe5e5d)

**Comment by greyson-signal** [comment]
Interesting, so this is what I'm seeing. The PushTextSendJob with ID "766a1396-f52f-414b-9060-fb2c471cbcf0" is submitted, but is not executed for ~12 hours. By your description, I'm assuming that means you sent this while the VPN was off, and then you connected to the VPN ~12 hours later and it sent.

I also noticed that any other jobs that require network (like RetrieveProfileJob) weren't executed during this time frame either. Based on that, I can only assume that for some reason the underlying system JobScheduler framework didn't think it had network access while off of the VPN. This would result in it never even attempting to send the messages, which is what we saw.

The JobScheduler is kind of a black box, and it's implementation can change based on Android OS and manufacturer. I'm assuming that your Huawei phone has a different implementation of JobScheduler that doesn't have the same failings.

Lemme think on this. Maybe there's a test you can run to confirm this is the issue.

**Comment by greyson-signal** [comment]
Oh yeah, if the little 'x's are there, then it's definitely a network-detection problem at the system level, likely due to it trying to confirm internet through a blocked site, like what you mentioned. 

Receiving (while the app is opened) is handled through an open socket. Apparently in this environment you can make a network request, there's just situations where the system doesn't _think_ it has network access, so it doesn't try.

I don't know if there's anything Signal itself can do here, since this is a failing at the system level, and we rely on the JobScheduler framework to ensure messages get sent out.

**Comment by bsblmn4** [comment]
I greatly appreciate your help.  Would it be possible to go around this somehow (e.g., not use the JobScheduler framework) since other messenger apps that I have don't have this problem?
