### ISSUE TITLE
When no profile picture set a (random) letter and color is set on top of conversation overview

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8307]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On top of the conversations overview the users own profile picture is shown or if none is set the Signal logo was shown. However after updating to version 4.29.7 initially there was a red circle with the letter J in it. This happens to be the initial letter of the name which is set in the profile information. After opening a conversation and switching back this changed in a green circle with the letter O in it (or a zero..) which is not related to the profile name.

### Steps to reproduce
- update to 4.29.7
- open Signal
- check own avatar on top of conversation overview

**Actual result:** When no profile picture is set a color and letter is shown (which is not the initial letter of the profile name)
**Expected result:** Don't know if a color and initial is expected, but I liked the Signal logo more when no profile picture is set.

### Screenshots

![screenshot_20181026-084359_signal](https://user-images.githubusercontent.com/25846829/47551992-e54da380-d903-11e8-90df-d30a1dc40a7c.jpg)

### Device info

**Device:** Samsung SM-G960F
**Android version:** 8.0.0
**Signal version:** 4.29.7

### Link to debug log

https://debuglogs.org/dd6f0362d33eada25f8705d69f213928d0434719176a123f693252a8aeec91bb

Edit: Corrected the Signal versions.

**Comment by greyson-signal** [comment]
This is likely the result of a timing issue that was fixed in 1686d1fe9291c417a6df46ddcb6387101dde443c and will be in the next release. Thanks!
