### ISSUE TITLE
UX: Unable to make regular voice call from message screen

### ISSUE THREAD

**Issue by mryellow** [signalapp/Signal-Android#8308]
Being an SMS replacement this app should be able to initiate phone-calls from the SMS screen. It is only able to initiate Signal encrypted VoIP sessions. 

There appears to be no way to access standard phone feature of making a phone-call from this SMS replacement app.

**Comment by greyson-signal** [comment]
As noted in the new issue template, Github is for bug reports and not feature requests. Please move this to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests).

FWIW Signal will let you initiate a non-secure phone call if you're in an SMS conversation with a non-Signal user. Also, from the conversation list, if you click on someone's avatar, you'll be taken to their system contact page where you can start a non-secure call. 

But again, please move this to the forum. Thanks!

**Comment by mryellow** [comment]
> As noted in the new issue template, Github is for bug reports and not feature requests. Please move this to the forum.

Why have I put in a low effort here?

Could it be that Signal team have demonstrated they'll reply with such a low effort response? 

Could it be that Signal team have demonstrated they don't take UX seriously?

I do not wish to register with yet another forum when we have this here for **ISSUES**

UX failures are **BUGS**.

UX failures which have existed in the software and been reported as issues time and time again should **NOT BE IGNORED**.

Signal is failing here with these **CRITICAL UX FAILURES**

Stop diverting **REAL ISSUES** to an external forum.

**Comment by mryellow** [comment]
>  non-Signal user.

If I **KNOW** the user no longer has Signal installed there is **NO WAY** for me to call them.

**Comment by mryellow** [comment]
Either:

* Signals **STOPS PRETENDING** to be an **SMS REPLACEMENT APP**
* Fix the send buttons to remember state so ***KNOWN NON-SIGNAL USERS** can be contacted reliably.

**Comment by mryellow** [comment]
You'd get something more concise from me if you weren't wasting my time.
