### ISSUE TITLE
Forum locks people out automatically

### ISSUE THREAD

**Issue by mryellow** [signalapp/Signal-Android#8311]
I would continue the discussion however:

*You’ve reached the maximum number of replies a new user can create on their first day. Please wait 23 hours before trying again.*

*Account temporarily on hold*

So much for participating. I wonder why your team remains small.

**Comment by mryellow** [comment]
[quote="johanw666, post:6, topic:4596"]
It doesn’t work like that for no existing messenger.
[/quote]

How many existing messengers have a popup on install which asks to become default SMS app?

If Signal were just another encrypted chat app then this wouldn't be an issue, you'd just SMS them and they'd get your SMS.

If you're going to be default SMS app there are two things needs.

* The ability to make phones calls. 

It's crazy there is **NO** button to initiate a phonecall from a Signal (SMS) message. You can only initiate encrypted VoIP calls. There is no similar "Hold down for alternative" interface on the phone button. This should at the least off the ability to make a phonecall.

Currently users make exit Signal, open their phonebook, navigate to the same user and initiate the phonecall from this screen instead.

* The ability to choose what type of message to send.

I get that this is encrypted first as a paradigm and that the idea is to force all communication to "go dark". However this lack of **end user control** over the behaviour of the software they use is instead causing adverse outcomes. Without control over the software the user is not protected but instead potentially harmed.

**Comment by mryellow** [comment]
And once the thread started getting replies. Someone hide it.

Officially ignored a critical UX failure yet again.

**Comment by mryellow** [comment]
https://community.signalusers.org/t/ux-difficult-to-sms-users-known-to-not-have-signal-installed-anymore/4596

**Comment by greyson-signal** [comment]
@mryellow Discourse (our forum software) will prevent newly-registered users from posting too much as a spam-prevention technique. 

> Currently users make exit Signal, open their phonebook, navigate to the same user and initiate the phonecall from this screen instead.

As I mentioned in #8308, you can tap someone's avatar in the conversation list in order to be taken to their system contact page to make a phone call. So two taps, not too bad.

I understand that this is a point of frustration, but please be considerate of our bug reporting guidelines. A lot of people are subscribed to be notified of issue updates, so we want to keep issues productive.
