### ISSUE TITLE
Android keeps on restarting while creating back

### ISSUE THREAD

**Issue by rubin110** [signalapp/Signal-Android#8320]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal churns and slows down the phone for about 15 minutes while the create backup notification is on. After which my phone restarts. After giving it my unlock password, and Android fully boots up, Signal tries to make another backup.

### Steps to reproduce
- Install Signal.
- Have a Signal chat history as old as time (or as old as one can keep)
- Wait for a backup to kick in
- Observe

**Actual result:** Phone eventually reboots.

**Expected result:** Phone does not reboot, backup finishes creating.

### Device info

**Device:** Pixel 2 XL
**Android version:** Android 9
**Signal version:** 4.29.7

### Link to debug log
No debug log

### Notes
I went through and disabled backups, then re-enabled them. This didn't fix the issue, sadly.

And I'm not exaggerating. I've got a huge history of chat logs. This has become a bit of a problem for the stand alone desktop client, but currently that's running fine.

**Comment by rubin110** [comment]
Backups up number of messages gets up to around 152500, then whatever is printing it sometimes starts to flicker values from 152500-onwards and 150000-onward, with a gap of approximate 2000. Generally it's a few minutes later when it restarts.

**Comment by johanw666** [comment]
Is your phone running out of internal storage? Can you make a debug log?

**Comment by janvlug** [comment]
I have a similar issue, it looked like Signal kept starting over and over attempting to create a backup. I saw the messaged counter going up to above 87000. Then I saw a blinking 0. Unfortunately, Signal now also crashes when trying to create a debug log. Using Signal 4.29.7.

**Comment by janvlug** [comment]
Currently, Signal is backing up again. When I look at the progress of the backup, I see that the number of messages so far is not continuously increasing. It looks like there are two counters (backups) running at the same time that both print their number of messages to the same status line.

**Comment by janvlug** [comment]
The difference with the original reporter is that Signal does not restart in my case, and that I see a fast backup until around 84000 messages, then the slow down and 'different' counters start.

This is another debug log:
https://debuglogs.org/87d5f12f9eb1e6763769ded9b217faff0d81923167f292f59336a15c655c6b9a

**Comment by greyson-signal** [comment]
It looks like there was a bug in WorkManager that could allow multiple instances of a job to run simultaneously in some circumstances. That would explain the screwy counters, sluggish phone performance, etc. Maybe even cause enough disk thrashing to somehow cause the device to crash? That one's still a little odd, and I'd still like to see a log if possible @rubin110.

Normally the circumstances for creating these simultaneous runs are very rare, but for large backups it's easier to hit. Regardless, I have a fix ready for the next release. Thanks!

**Comment by rubin110** [comment]
Sorry for the delay. Attempting to capture a log now and it looks like the backup completed, without any weird multiple instances messing with the message count. Still running 4.29.7.

**Comment by greyson-signal** [comment]
Ah, 6.31 GB! I thought was a good test case for large backups at ~4.5 GB :) How's performance like now? Is it better? 

> Also I am wondering where to file bugs against the support site. The location of where backups are being saved seems incorrect...

I'll make sure that gets fixed, thanks!
