### ISSUE TITLE
Signal PIN lock password reminder doesn't seem compatible with Autofill

### ISSUE THREAD

**Issue by samueltardieu** [signalapp/Signal-Android#8322]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have set a PIN lock on my number to prevent registration of my Signal number by a third-party. When I launch Signal, from time to time, it requests the PIN to ensure it has not been forgotten. However, I chose a PIN which is registered in my password manager, and it looks like the PIN entry is not compatible with autofill : although my password manager (keepass2android) finds the entry, it does not autocomplete it like it does in other applications.

The problem is likely on Signal side because the autofill choice when I long press the PIN field is not shown by default by Android (like it is in other applications when a password is requested), I have to go to the 3 dots menu to get "Fill automatically" (just as in a regular input field).

### Steps to reproduce
- wait for Signal to request your PIN lock for reregistration at launch time ;
- long press the field, "...", "Fill automatically", "Keepass2Android" => entry is found in KP2A
- [nothing, field is not filled]

### Device info

**Device:** OnePlus 6
**Android version:** 9.0
**Signal version:** 4.9.27 (beta channel from Google play store)

**Comment by ProactiveServices** [comment]
I can't use PIN lock as I don't remember such a long set of digits: that's what my password manager is for. If every app and service required me to re-enter my password periodically, to "remind" me of the password, it would quickly make my devices unusable. If I also had to use memorable passwords, I would be inclined to use less-random passwords.

**Comment by Sgn-32** [comment]
Do the problems still exist?

The registration lock PIN was/is replaced with the Signal PIN.
The reminder for the Signal PIN can be deactivated.

https://support.signal.org/hc/en-us/articles/360007059792-Signal-PINs

**Comment by greyson-signal** [comment]
I added the hints to the PIN fields to make sure password managers can work with it, so shouldn't be a problem anymore. Thanks!
