### ISSUE TITLE
Please add slide to reply/forward

### ISSUE THREAD

**Issue by black-wolfie** [signalapp/Signal-Android#8323]
I think it would benefit the Android Signal greatly if "slide to reply/forward" feature is added. Currently, you have to long-press a comment to which you want to reply to select the comment, and then press the reply button. This isn't very convenient. I believe sliding a comment is much faster.

Could you please add "slide to reply / forward" feature? Thank you. It can be "slide to the left to reply", "slide to the right to forward"

Thank you.

**Comment by greyson-signal** [comment]
Hi there, we reserve Github exclusively for bugs. Please post about feature requests in [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
