### ISSUE TITLE
White flash during app launch when using dark theme.

### ISSUE THREAD

**Issue by 948127524** [signalapp/Signal-Android#8326]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

**Bug 1**
Cold opening the app gives a white flash for ~1-1.5 seconds. Very few, but some of the apps on my phone are affected by this even with a global dark Substratum theme (which fixes some opening white flashes).

### Steps to reproduce
* Cold open the app 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Gives a white flash of ~1-1.5 sec. Inconsistent with a completely dark theme and the contrast is unpleasant for the eyes.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Use the same color when opening the app as it appears elsewhere

[x] Leaving the foreground process in memory and opening from the launcher/switching windows is working as expected, no white flashes.

**Bug 2**
In-call screen is white, inconsistent with a dark theme which is featured elsewhere within the app, and is an unpleasant contrast for the eyes.

### Steps to reproduce
- Receive/make a call or be in an active call.

### Device info

**Device:** LG V20
**Android version:** 8.1.0
**Signal version:** 4.29.7

**Comment by jpds** [comment]
I also mentioned bug 2 in #8240.

**Comment by jdepypere** [comment]
Bug number 1 is (probably) due to the default theme being light. Not sure there is any way around this.

**Comment by 948127524** [comment]
@jdepypere check out the Calendar or Contacts apps on F-Droid. They have a light theme by default but manage to stay dark on opening the app if you will it.

**Comment by jdepypere** [comment]
@948127524 While this is possible I'm not sure this is the best approach to a splash screen. The point of a splash screen is to do as little as possible. At the very least this functionality would require reading a preference and setting the theme dynamically. I guess it is up to a Signal dev to decide what they have as preference.

**Comment by nioncode** [comment]
The proper way of doing this is adding a separate, dark splashscreen with the `-night` resource qualifier. Then, Android will automatically use this splashscreen when the system is running in dark mode and the default one otherwise.

This will at least fix the white splash for people that use dark mode on the whole system. It will still flash white for people that have a light system, but use dark mode only in Signal.

**Comment by emerson-pereira** [comment]
> The proper way of doing this is adding a separate, dark splashscreen with the `-night` resource qualifier. Then, Android will automatically use this splashscreen when the system is running in dark mode and the default one otherwise.
> 
> This will at least fix the white splash for people that use dark mode on the whole system. It will still flash white for people that have a light system, but use dark mode only in Signal.

I agree, I don't think it's too much of cost to do that and allow dark mode users no to go blind when they're messaging in a dark room.

I personally am stopped using Signal until this is fixed. I want to use Signal very much but I won't until that is fixed.
