### ISSUE TITLE
Sealed sender info link 404s

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#8328]
- [x] I have searched open and closed issues for duplicates
- [ x I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description

The beta app has a "Learn more" link that goes to: https://signal.org/blog/secret-sender/

It should go to https://signal.org/blog/sealed-sender/

**Comment by jpds** [comment]
And fixed in cfeee2548842027db0610c54d1349c284f60e897

**Comment by strugee** [comment]
@jpds can you close this bug since it's been fixed?
