### ISSUE TITLE
Sent messages being mysteriosuslyl opened 

### ISSUE THREAD

**Issue by helpmeimtrying** [signalapp/Signal-Android#8331]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by helpmeimtrying** [comment]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
So I have a friend who has deleted signal from his phone but when I send him encrypted messages they still get opened and the timer expires so it disappears. 

### Steps to reproduce
- Send encrypted self deleting message to "B" 
- "B" never opens signal message
- message stays locked indefinately or until user "B" resigns in and receives message
- 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- The signal message opens and self deletes without ever being recieved by user "B"

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- message stays encrypted and locked until the user "B" account is used again

**Comment by greyson-signal** [comment]
The disappearing message timer is local. It will begin for each person when they first see it for themselves.

In this case, after you send a disappearing message, _you've_ just seen it, so the timer will start for you. It'll start for the recipient when _they_ first see it.
