### ISSUE TITLE
SHA1 is not allowed in newer conscrypt versions

### ISSUE THREAD

**Issue by eholk** [signalapp/Signal-Android#8333]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Newer versions of Conscrypt no longer accept SHA1-signed keys: https://github.com/google/conscrypt/pull/463

Unfortunately, this means Signal will not be able to connect to the server in versions of Android that include the newer Conscrypt.

### Steps to reproduce
- Install Signal and try to register

**Actual result:** A message pops up that says "Unable to connect to service. Please check network connection and try again."
**Expected result:** I can register my account.

**Comment by greyson-signal** [comment]
We've updated our cert to use SHA2. Thanks!

**Comment by eholk** [comment]
Awesome! Thanks for updating this. I was just able to register using the
new certificate.
