### ISSUE TITLE
Registration not working in Belarus.

### ISSUE THREAD

**Issue by Aleh71** [signalapp/Signal-Android#8334]
problem with authorization. does not come sms. I'm from Belarus.
https://debuglogs.org/cb35b175f1bbfd8d142166ebaf32756e213409ff3a56f40fcf947327e3418f87

**Comment by Aleh71** [comment]
Устройство: Samsung Galaxy J5 2016 - версия для 
Android версии SM-A730F : 7.0 
Версия сигнала: Signal_v4.30.2_424

**Comment by Aleh71** [comment]
Samsung Galaxy J5 2016  SM-A730F
Android 7.0 
 Signal_v4.30.2_424

**Comment by Notatechdud3** [comment]
Благодарю вас, какой носитель телефона вы используете?

**Comment by Aleh71** [comment]
я не понимаю слова "носитель", поясните
I do not understand the word "carrier", explain

**Comment by Notatechdud3** [comment]
Опертор (e.g. MTS / Velacom / Life, ...)

**Comment by Aleh71** [comment]
Velcom

**Comment by Aleh71** [comment]
With this operator, the problems are not only with me. First, I went through authorization, then I accidentally made a way out. And after that I can not pass authorization. Several times deleted and installed the program.

**Comment by Notatechdud3** [comment]
No-one from Belarus is able to register because of some restrictions (see https://github.com/signalapp/Signal-Android/issues/6027)

Did you already mail to support@signal.org?

**Comment by dziaineka** [comment]
MTS.by carrier doesn't work too. I had a conversation with Twilio support, I sent it to support@signal.org.

**Comment by Notatechdud3** [comment]
Hello, 

I made a topic Signalusers. Maybe it is best to drop all information there as well, so we can have a look at it. 

https://community.signalusers.org/t/registering-in-belarus-all-providers/4827

**Comment by Aleh71** [comment]
Today made an authorization Signal.  Operator Velcom Belarus.
