### ISSUE TITLE
Audio recorded in app fails to play

### ISSUE THREAD

**Issue by justin-** [signalapp/Signal-Android#8335]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio recorded in the app fails to play. This bug is intermittently reproducible. If the bug occurs, the audio file will be broken for all parties in the conversation.

### Steps to reproduce
- Record audio using the in-app functionality
- Press play

**Actual result:** The audio does not play. The button changes from the play icon to the pause icon but the seekbar does not advance.
**Expected result:** The audio plays.

### Device info

**Device:** Google Pixel 3
**Android version:** 9
**Signal version:** 4.29.7

### Link to debug log
https://debuglogs.org/1c6fbb9728204facc5b8dc28326dba9527c87a880fae1b52fe943b5506c013e2

This might be related to #7748 but I only encountered this bug for the first time recently. Also, no error message appears and I have had the bug occur with short clips.

**Comment by greyson-signal** [comment]
Looks to be related to #8620
