### ISSUE TITLE
Volume keys don't mute ringing during call arrival

### ISSUE THREAD

**Issue by Konotorious** [signalapp/Signal-Android#8338]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Given a certain standard set by "regular" calling and calling through other messaging apps, I expect that hitting the "volume down" button while receiving a call would mute the ringing (sound). However, this is not what happens with Signal.

### Steps to reproduce
- Ensure your phone is not on mute (ringtone volume > 0).
- have someone call you on Signal.
- Wait for the ringing.
- Hit the volume down button.

**Expected result:** 
Ringing sound muted while the incoming call keeps on incoming (not dropped).

**Actual result:**
 The volume keys adjust the "call volume".
Alternatively, if one has the top-menu (the one holding the wifi/ location/ sound/ torch and so on toggle-buttons) pulled down, hitting the volume keys during an incoming call would adjust the "ringtone" volume, which would adjust the volume of the ringing.
Just to stress the point, however, in the latter case, even if the top-menu being down was not necessary, that (adjusting the ringing volume) is *not* the desired behaviour. Assuming that the ringing is there to bring to one's attention the fact that a call is being received and not to play music, there is no reason to adjust the volume of the ring in "real time". Supposedly the ring-muting is there in particular for those situation when one's phone starts ringing and it is a really, really bad time for it to ring. You want to kill the sound as quickly as possible. 

### Device info

**Device:** Samsung J5
**Android version:** 6.0.1
**Signal version:** 4.29.7

**Comment by haffenloher** [comment]
This feature request is being tracked here: https://community.signalusers.org/t/volume-buttons-to-mute-ringer/4663

**Comment by tariqc80** [comment]
Also noticed that the "Flip to shhh" gesture doesn't work with Signal calls either.

**Comment by Tursko** [comment]
I've also experienced this issue. Hopefully https://github.com/signalapp/Signal-Android/pull/9152 can solve the issue. Has anyone tested it?

**Comment by di72nn** [comment]
Still relevant.

**Comment by cody-signal** [comment]
Try on 5.33 where we've integrated with the Android telecom system, and made some changes to how we ring. Please post an updated debuglog if you try with that version and still encounter problems.

**Comment by cyclonejet** [comment]
I assume this hasn't been merged yet? https://github.com/signalapp/Signal-Android/pull/9152

**Comment by cyclonejet** [comment]
Inactivity shouldn't be the reason to close the issue

**Comment by nicholas-signal** [comment]
> I assume this hasn't been merged yet? #9152

The author never rebased their PR.

**Comment by di72nn** [comment]
> never rebased

I rebased it three times when I still cared.

**Comment by rajsinghUSA** [comment]
This is a pretty important and standard feature, and it should be fundamental to an app that values discretion.

**Comment by DaPutzy** [comment]
How is this still a thing 😢

**Comment by tylla** [comment]
I would suggest reopening this ticket as the problem is still unaddressed and kinda disturbing (tested in 7.73.2).
As I see #9152 is stale as the contributor and the reviewer were way out of phase with each other.
@di72nn is it remotely possible you could take a look at that PR and rebase it?

**Comment by di72nn** [comment]
How can I not do my part if the people ask? Rebased the PR and addressed the comments.

**Comment by wertzuz** [comment]
Guess it's no longer a wontfix

**Comment by tylla** [comment]
This is still ongoing on the other thread (#9152).

**Comment by anansefo** [comment]
Seconded (or rather more like nth-ed): can you please add this feature? Especially since there's already a patch available (thanks @di72nn !), and it just needs to be merged. A lot of users would like to use this feature, which is pretty common in other calling apps...

**Comment by binishjoshi** [comment]
I have been using Power button to silence the ring

**Comment by tylla** [comment]
This is still ongoing on the other thread (https://github.com/signalapp/Signal-Android/pull/9152), not finished yet.
