### ISSUE TITLE
If screen lock enabled, Signal's "while in active use" equals the time since last full charge / Signal shows battery notification

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8340]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After my phone has been updated from Android 7 to 8.1 several days ago, I am experiencing some odd behavior, if Signal's screen lock is enabled:
1. In the battery settings page, it shows "Signal used for X time", where X is the amount of time since the full last charge (see screenshots; i.e. I did _not_ use Signal actively for 6:34h).
2. If I disable the lock notification (with screen lock still enabled), I get a persistent notification that "Signal is using battery", when in background as long as the timeout has not expired.

### Steps to reproduce
For 1:
- Enable Signal's screen lock

Additionally for 2:
- Disable screen lock notification
- Put Signal to background, to foreground and to background again

**Actual result:** Battery settings page shows "Signal used for X time" (see screenshots). If screen lock notification is disabled, phone additionally shows the "Signal is using battery" notification. 
If the screen lock has a timeout, this notification disappears after the timeout and the "active use" seems also to work fine then.
I don't really feel like there is any additional (heavy) battery drain (several minutes of usage result in similar battery use as e.g. WhatsApp). But I also can't tell, if it's really the same, 

**Expected result:** Since I am on a GCM-enabeled device, I would expect no persistent notification and the "correct"/reasonable amount of active time in the battery settings page.

To check, if this is actually related to Signal at all, I started a [discussion](https://community.signalusers.org/t/general-question-regarding-battery-usage-on-android-8-1/4685) in the community forum before.
From the discussion:
- I tried to re-register my account (probably in order to ensure that the GCM registration is working).
- I have absolutely no issues with receiving messages or calls, when Signal is in the background.

### Screenshots
![](https://community.signalusers.org/uploads/db3609/original/2X/3/3c8bd7bad271e90ddd9b5db70a3b1d745efb449a.png)
![](https://community.signalusers.org/uploads/db3609/original/2X/e/e35d8fc730856a2d36f50f5c4115d77883786d85.png)

### Device info

**Device:** Motorola Moto G5
**Android version:** 8.1 (Stock Android (from Motorola) with Google Play Services; unrooted, no 3rd party ROM etc.)
**Signal version:** 4.30.2 (from PlayStore)

### Link to debug log
https://debuglogs.org/4143751f893439f1deb887bbcf75b21943e49db5464c97ae67af89f16199c83a
I captured the debug log after:
1. Fully charging the battery, disabling screen lock, force closing Signal and starting it again.
2. Using Signal for a few minutes and waiting a total of 30min --> "active use" is several minutes, last full charge is 30min.
3. Fully charging the battery again, enabling screen lock (without force closing Signal), enabling screen lock notification, putting Signal to background, to foreground and to background again.
4. Doing similar things as in 2 with the result: "active use" 25min, last full charge 25min. Phone does not show "Signal is using battery", it only shows "Signal is locked".
5. Fully charging the battery again, disabling lock notification, putting Signal to background, to foreground and to background again.
6. Doing similar things as in 2 with the result: "active use" 25min, last full charge 25min. Phone does show "Signal is using battery".

If anything is missing/unclear, I am happy to provide additional information.

**Comment by greyson-signal** [comment]
>  ...if Signal's screen lock is enabled:
> 
> In the battery settings page, it shows "Signal used for X time", where X is the amount of time since the full last charge (see screenshots; i.e. I did not use Signal actively for 6:34h).

This makes sense to me. The way the screen lock works is that Signal will consider the app "unlocked" as long as a certain key is in memory. Signal will try to keep that key in memory by showing a foreground notification ("Signal is unlocked"), which is the only way in Android to keep your process alive. If that notification is dismissed (either through the screen lock timeout or manually clicking "lock" in the notification), then the key will fall out of memory and you'll be presented with the screenlock when you next open the app.

The side effect of this, which you've stumbled upon, is that Android will consider an app in the foreground if it's running one of these foreground notifications. However, as you've also noticed, we don't *do* anything battery-heavy, so our battery usage is relatively normal.

> If I disable the lock notification (with screen lock still enabled), I get a persistent notification that "Signal is using battery", when in background as long as the timeout has not expired.

This is an Android thing. You're not allowed to hide foreground notifications via the system notification channel settings. Doing so will show this generic "Signal is using battery notification". The system does this so apps can't "cheat" and try to hide their own foreground notifications.

**Comment by minnmann** [comment]
I see. Thanks for the detailed explanation! And sorry for opening the ticket then.

**Comment by wesinator** [comment]
How do I dismiss the constant "Signal is using battery" notification ? It just started happening for me.
![signal_using_battery](https://user-images.githubusercontent.com/5124946/51433105-74bbd780-1c11-11e9-883f-bdcc6e50f2be.png)
It goes away when I open Signal, then comes back.
