### ISSUE TITLE
Google play store has a broken link to download the app.

### ISSUE THREAD

**Issue by andre-cunha** [signalapp/Signal-Android#8343]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Google play store has a broken link to download the app.
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

### Steps to reproduce
1) visit either android play store (https://play.google.com/) or signal official web-page (https://signal.org/)
2) Try to search for signal app
3) If you click on the image, you will be redirect to a broken link: https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

As you can see the id parameter has a super weird domain "org.thoughtcrime.securesms"

### Screenshots

![image](https://user-images.githubusercontent.com/10227514/48092270-4424ee00-e21d-11e8-8fe4-8158d2eef729.png)

![image](https://user-images.githubusercontent.com/10227514/48092211-1f307b00-e21d-11e8-9bf6-747aa76c1d77.png)

![image](https://user-images.githubusercontent.com/10227514/48092293-556dfa80-e21d-11e8-9de1-a265dcd707d8.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by greyson-signal** [comment]
All of the URL's you posted work fine for me. Could be either a transient Play Store issue or some Chrome extension you have installed.

> As you can see the id parameter has a super weird domain "org.thoughtcrime.securesms"

Signal wasn't always called "Signal". And once you pick a package name, that's the one you have forever. Think of it as a remnant of an earlier time :)
