### ISSUE TITLE
Dark theme archive icon displays on wrong layer (4.30.2)

### ISSUE THREAD

**Issue by mikaseh** [signalapp/Signal-Android#8344]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Bug description
On the dark theme when swiping on a conversation to archive, the archive icon is displayed on the wrong layer.

Steps to reproduce
- set theme to dark
- swipe on a conversation to archive
-  archive icon should be displayed on the wrong layer

**Actual result:** The archive icon displays under the conversation contact image and above the black layer
**Expected result:** The archive icon should be displayed on the lower green layer

### Screenshots
![signal archive overlay bug](https://user-images.githubusercontent.com/37028334/48104039-c4d4f180-e1ff-11e8-8abe-e0d62d4bd4a5.gif)

### Device info
**Device:** Google Pixel 2
**Android version:** 9
**Signal version:** 4.30.2

### Link to debug log
*not relevant

**Comment by PeterVanNostrand** [comment]
I can confirm the same behaviour, dark theme only
Device: OnePlus 5
Android version: 8.1.0
Signal version: 4.29.7 (latest for Android 8)

**Comment by Sixpawedstool** [comment]
I have the same behaviour too
Android version: 9
Signal version: 4.49.18
