### ISSUE TITLE
Signal state gets confused when accepting a picture from iOS "send to" 

### ISSUE THREAD

**Issue by wdormann** [signalapp/Signal-Android#8345]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal exposes itself as a recipient of "send to" capabilities in iOS.  For example, when viewing a picture, you can send it to Signal, where you can select a recipient to send it to.  The problem is that when using this capability, an already-running Signal instance seems to get confused about its state.  Symptoms include:
 - Signal doesn't show the picture you just sent
 - Signal doesn't show a message you just received 
 - Signal crashes.

### Steps to reproduce
- Have Signal open, and in a conversation with a contact.
- Switch to iOS Photos
- Share a picture to Signal, and select the current-conversation recipient
- Switch back to Signal
- Continue the conversation

**Actual result:** 
The picture that you just sent is often not present in the existing conversation.  Continuing the conversation often results in Signal crashing.

**Expected result:** 
The picture you sent is there, in the relevant position in the conversation thread.  Continuing the conversation doesn't result in a crash.

### Device info

**Device:** iPhone 6s
**iOS version:** 12.1
**Signal version:** 2.30.2.16

**Comment by greyson-signal** [comment]
Hi there, it looks like you intended to file this in [Signal-iOS](https://github.com/signalapp/Signal-iOS/issues/new). Please copy-paste this over there :) Thanks!
