### ISSUE TITLE
[Feature request] Make switching between data and SMS more obvious

### ISSUE THREAD

**Issue by imrekalo** [signalapp/Signal-Android#8346]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

it should be more obvious that you can switch. maybe as a message, tooltip or something after you first switch to signal as sms app.

background:

i've only recently found out that when sending a message, i can long press the send button to switch between data and sms. this is very handy, because some of my contacts have tried signal but uninstalled it, so they appear as signal users but obviously don't receive the message over data. also, sometimes i'm in countries where i don't have a cheap data plan, so i prefer sending an sms over turning on data roaming when wifi is not available. so "missing" this feature kept me from using signal as my sms app. i consider myself as an advanced techy, but only found out about this because, after a while, i couldn't believe that this feature is missing from an otherwise great app, so i googled it.

using version 4.29.7 on android, but i guess this also applies to ios

**Comment by igor2x** [comment]
@imrekalo, Signal/Android project uses GitHub **exclusively** for bug reporting. May I invite you to the [Signal Community forum](https://community.signalusers.org/) where is correct place to report feature requests and discuss them with huge number of community members.

Every post on bug tracker triggers e-mail sending to hundred of bug tracker subscribers, so please avoid sending any message here to be nice to subscribers e-mail boxes.
