### ISSUE TITLE
Backup taking to long and not restorable. Only 20 contacs with 50 messages

### ISSUE THREAD

**Issue by dorakas** [signalapp/Signal-Android#8347]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to backup my data so i can transfer it to my Pixel 3 phone. I have all permissions granted on the Nexus 6P. No SD CARD. Enought empty space. After writing down the numbers the backup process starts and takes hours. Don't know if it really finishes properly. But the notification is gone at some Point. I reduced all Messages to max 50. 
### Device info

**Device:** Nexus 6P**Android version:** 0.0.0
**Signal version:** Website Version. 4.29.7
### Link to debug log

https://debuglogs.org/271c2cc020a749c2fbadd6745433bb18a9960b94c427a0486a74d994c65b88e8

**Comment by greyson-signal** [comment]
It looks like you're hitting a known bug where multiple backups are running concurrently, which slows down all backups. Can you try updating to [the beta](https://play.google.com/apps/testing/org.thoughtcrime.securesms), which has a fix for this issue, and let me know if it improves?

**Comment by dorakas** [comment]
Ich have no googleplay. If you can provide me with an apk i would try

**Comment by alurasg** [comment]
I have the same issue. I updated to the beta, as suggested, but the issue remains exactly the same.

**Comment by dorakas** [comment]
This is not good. My Nexus 6P has a battery that only last like 45 min. I'm forced to stay on that phone as long as I can't backup. Sad

**Comment by dorakas** [comment]
Maybe there is a solution. @Greyson-signal has to approve it first. 

Greyson. Is it possbile to downgrade the official Website build, wich are all still available on the Signal Website so we can do a working backup? I assume if there wasn't any Major changes to the database. there shouldn't be a Problem.

**Comment by greyson-signal** [comment]
@dorakas I'm fairly confident that your specific backup issue has something to do with the fact that multiple backups are running simultaneously, which would be fixed in the beta. I can't downgrade the existing website release, but I can send you an APK of the latest beta. If you're interested, you can either [message me on the forum](https://community.signalusers.org/u/greyson-signal), or send a message to one of my test numbers (+1 610 549-1426) and I'll get it to you.

@alurasg I can't say if you're having the same problem without a debug log. Please post one :) Thanks!

**Comment by alurasg** [comment]
Hi, many thanks for your reply!

Please find my debug log here 
<https://debuglogs.org/fc840c99f84cadb7697c8e5caad3c767387149613b753fabef8ca020443f1705>. 


Again, I already installed the beta, but the issue remains the same.

I've already sent an email to support@signal.org, and also submitted an 
issue via their website (more than a month ago) but up until now, I 
didn't receive any response.

This was the explanation of my issue:
My question regards the Android app Signal 4.29.6.

Until a while ago, there was an option to backup via an export to xml. 
This worked perfectly fine for me.
However, this option has disappeared now, and instead, there is an 
option to backup and restore, but unfortunately, this option doesn't 
work. At first, I thought that I had unsufficient space on my phone, but 
now I cleaned up more than 1,5 GB (deleted all the pictures/movies from 
the attachments) and still it doesn't work. When I put the option on, it 
seems to start, I see the count of how many messages are being backed 
up, but after a while, it just stops, and the option for the backup is 
still on, but the last backup says 'never'. If I put the back-up off and 
on again, I can try again, but same story.

Would you please be so kind as to help me?

You'll find screenshots of the situation attached.

Thanks in advance and kind regards!

Greyson Parrelli <notifications@github.com> schreef op 9 november 2018 
18:59:22 CET:

    @dorakas <https://github.com/dorakas> I'm fairly confident that your
    specific backup issue has something to do with the fact that
    multiple backups are running simultaneously, which would be fixed in
    the beta. I can't downgrade the existing website release, but I can
    send you an APK of the latest beta. If you're interested, you can
    either message me on the forum
    <https://community.signalusers.org/u/greyson-signal>, or send a
    message to one of my test numbers (+1 610 549-1426) and I'll get it
    to you.

    @alurasg <https://github.com/alurasg> I can't say if you're having
    the same problem without a debug log. Please post one :) Thanks!

    —
    You are receiving this because you were mentioned.
    Reply to this email directly, view it on GitHub
    <https://github.com/signalapp/Signal-Android/issues/8347#issuecomment-437442530>,
    or mute the thread

**Comment by alurasg** [comment]
Hi, many thanks for your reply!

Please find my debug log [here](https://debuglogs.org/fc840c99f84cadb7697c8e5caad3c767387149613b753fabef8ca020443f1705). 

Again, I already installed the beta, but the issue remains the same.

I've already sent an email to support@signal.org, and also submitted an 
issue via their website (more than a month ago) but up until now, I 
didn't receive any response.

This was the explanation of my issue:
"My question regards the Android app Signal 4.29.6.

Until a while ago, there was an option to backup via an export to xml. 
This worked perfectly fine for me.
However, this option has disappeared now, and instead, there is an 
option to backup and restore, but unfortunately, this option doesn't 
work. At first, I thought that I had unsufficient space on my phone, but 
now I cleaned up more than 1,5 GB (deleted all the pictures/movies from 
the attachments) and still it doesn't work. When I put the option on, it 
seems to start, I see the count of how many messages are being backed 
up, but after a while, it just stops, and the option for the backup is 
still on, but the last backup says 'never'. If I put the back-up off and 
on again, I can try again, but same story.

Would you please be so kind as to help me?"

You'll find screenshots of the situation attached.

Thanks in advance and kind regards!
![screenshot_20181109-194652](https://user-images.githubusercontent.com/44026772/48283315-76705e80-e45c-11e8-84e8-937b197b8cb1.png)
![screenshot_20181109-195735](https://user-images.githubusercontent.com/44026772/48283316-76705e80-e45c-11e8-81d9-6201d8fc843c.png)

**Comment by dorakas** [comment]
@greyson-signal 

i send you a message on the number u provided

**Comment by alurasg** [comment]
@greyson-signal Did you find something? The problem still remains the same, and I really would like this solved. Another solution (such as the backup option from before the update this all started with) would also be great.
