### ISSUE TITLE
Conversation toolbar back button does not highlight when pressed.

### ISSUE THREAD

**Issue by glU79z** [signalapp/Signal-Android#8351]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not 100% sure whether this is a bug or an intended color choice. Please close if it's not a bug.

When opening a contact's profile page and clicking the "back" button in the upper left corner of the profile image, the on-touch color of the button is the signal blue. Clicking the "back" button opens the chat, which has a contact-specific accent color. I think therefore the "back" button should also use the contacts accent color because the blue signal color sometimes looks rather awkward dependending on the combination of the profile picture colors and the chosen contact accent color.

There is also an inconsistency with the "back" button in the chat itself. This "back" button has no on-touch color change at all.

### Steps to reproduce
- open a profile page
- click and hold the "back" button on the profile page
- look at the color change of the button
- quit holding the button 
- click and hold the "back" button on the chat page
- look at the (non-existing) color change of the button

**Actual result:** Consistency is missing and signal color sometimes looks awkward.
**Expected result:** Consistency in the UI and a non-awkward color choice.

### Device info

**Device:** Oneplus 3T
**Android version:** 8.1
**Signal version:**  4.30.2 (and at least all versions since the UI improvement)

### Link to debug log
Just UI --> no debug log

**Comment by greyson-signal** [comment]
I think the bug here is actually that the conversation page doesn't have a touch highlight around it. Back buttons on Toolbars should have a highlight when pressed.
