### ISSUE TITLE
[BUG] Self Sent Attachments from Desktop Aren't Openable/Savable/etc.

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8352]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Self sent attachment's Aren't Openable/Forwardable Directly from the app and saving them results in error:

![signal-attachment-2018-11-09-223419](https://user-images.githubusercontent.com/34171942/48282740-ca387300-e46f-11e8-843c-8bb817ea7407.png)

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.31.1

### Link to debug log
log does not seem to be needed.

**Comment by greyson-signal** [comment]
I think this got fixed during the note-to-self changes. Can't repro.
