### ISSUE TITLE
Stuttering and lag in conversation list

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#8357]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Massive lag and stuttering in conversation list and conversations

### Steps to reproduce
- Go to conversation list
- Scroll

**Actual result:** stuttering and lag
**Expected result:** smoothness

Everything was working great in 4.29.7. After I updated to 4.30.2 (didn't test 4.30.x versions before that) I noticed massive stuttering in the main conversation list. It is so bad that I literally stopped using the Android app because entering a conversation takes so long. Conversations are not as bad as the main conversation list. Is it the updated emoji set that's causing this? If I scroll in a conversation it does seem to stutter on messages that have several emojis. But it also stutters on images.

### Device info
**Device:** Moto G4 Play
**Android version:** 7.1.1
**Signal version:** 4.30.2, 4.30.3

### Link to debug log
4.30.2: https://debuglogs.org/6b26d7bd7876cce67e2f122ec66ba306b88edc24e083449ef7c177c7415f742c
4.30.3: https://debuglogs.org/01990fa9cf18d56d931291d5b26769eccc45ff4213a94a6dd2098fd0d93de833

**Comment by greyson-signal** [comment]
Hmm, I can't seem to reproduce this. I even have a Moto G4 (although not a Moto G4 _Play_). I tested with lots of emoji's and image thumbnails, and I haven't had any noticeable problems in the conversation list or individual conversations. I looked at the profiler and didn't notice anything weird either.

If you want to eliminate emoji changes as a cause (although fwiw none of the rendering logic changed for the new emoji, we just added more supported emoji to the list), you can toggle on Settings > Chats and media > Use system emoji. Then see if  you're still having perf issues.

**Comment by tbsn** [comment]
I'm experiencing the same issue since 4.30.* and it seems to be related to emojis from the faces pane, regardless of their multi-skintone capabilities.
Even worse, the app stutters heavily and restarts if selecting the faces emoji pane and swiping right or left and back.
These problems do not occur with system emojis selected.
https://debuglogs.org/691dded88b6d1ef3d8089d038b9b6cc599ebdfd17f4f0f3a9cf19483c72aa1f5

**Comment by synthgab** [comment]
I also have the same behavior: lags and delays when scrolling conversations with lots of messages with emojis, but also when inserting emojis (scrolling among panes in the emoji selector is not smooth, and when I choose one, it takes a long time to show up in the message).

Phone: Samsung Galaxy J5 (2016)
Android version: 7.1.1
Signal version: 4.30.2 , 4.30.3
Debug logs: https://debuglogs.org/f0f0763f3ec0c77ddebb395475e190c1079e444ab57ed5fe5d87b65ac5b41003

**Comment by greyson-signal** [comment]
Full disclosure: I haven't been able to repro any situation where the app becomes "unusably slow" (not even on [this phone](https://www.gsmarena.com/samsung_i8200_galaxy_s_iii_mini_ve-6190.php)!), so I can't be 100% sure that this resolves the issue until you folks get your hands on it. However, I can say that I've reduced the memory requirements of showing emoji, and I made some improvements to the speed at which the spritesheets are loaded. So hopefully those things combined will help out :)

**Comment by synthgab** [comment]
Hello Greyson,

I updated Signal on my phone this morning, and a quick test showed a huge improvement in the smoothness of the conversation scrolling and emoji panel selector. If the problem comes back in the long-run, I'll try to dig in.

Thank you for the quick solution, though.

**Comment by 2-4601** [comment]
Seems to have also helped my device. The only noticeable lag with 4.30.4 is in the emoji picker's recent tab. Other tabs are really fast. I remember I got Signal to crash (in the previous versions) when scrolling & selecting in the recents tab. Now it doesn't crash but is noticeably slow.
