### ISSUE TITLE
Can't delete expired MMS notifications in conversation

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#836]
in TextSecure v1 i could delete expired notifications about MMS messages from the conversation that i never bothered to actually download, while with v2 this seems not to be possible anymore.

**Comment by rhodey** [comment]
can anyone confirm this on 2.6.4?

**Comment by ap--** [comment]
Yes. I'm running 2.6.4, and I still can't select the mms messages. Long press does nothing.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
