### ISSUE TITLE
4.30.3 not on Play Store

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#8361]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

I noticed that 4.30.3 was tagged in the Git repo a few days ago, however this release isn't on the Play Store beta yet.

**Comment by greyson-signal** [comment]
Don't worry, I didn't forget :) It's up now (on the beta channel).
