### ISSUE TITLE
Transifex translation strings on "master" and "strings.xml" mostly duplicated

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#8366]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There seem to be two instances of translation strings for Signal Android on Transifex, "master" and "strings.xml", containing mostly the same strings, already translated and ones to translate.

### Steps to reproduce
- go to https://www.transifex.com/signalapp/signal-android/translate/
- choose your language
- compare "master" and "strings.xml"

**Actual result: translated strings and strings to translate are mostly duplicated
**Expected result: I think those shouldn't be duplicated.

### Screenshots
![sign_tr](https://user-images.githubusercontent.com/2994878/48483384-982e6480-e813-11e8-9e2d-7bbd35e61122.png)

**Comment by greyson-signal** [comment]
Sorry, this was an accident. The strings.xml resource has been removed.
