### ISSUE TITLE
Video attachment of 25MB incorrectly detected as "too large"

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8368]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot send videos that are 25 MB

### Steps to reproduce
- Send a video

**Actual result:** I get that it's too big 
**Expected result:** should be able to send it

### Device info

**Device:** Pixel 2 XL
**Android version:** 9
**Signal version:** latest

### Link to debug log

https://debuglogs.org/b0d820326c3de17112298a9fbf3eb5afb371412598d83ea8f2c8c3db7c6c4621

**Comment by leonardoporp** [comment]
A Signal message that's why I opened this issue . I cannot send videos of 25 MB...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by leonardoporp** [comment]
file extension is mp4
I click on + than gallery than camera and than the video.
I haven't understood the latest question where the video was taken? I used my pixel 2 XL

PS. If you gimme an email I can send you the video.

Sent from ProtonMail mobile

null

**Comment by greyson-signal** [comment]
You can just send it to support@signal.org -- thanks!

**Comment by leonardoporp** [comment]
I sent the video

-------- Original Message --------

**Comment by tailcode** [comment]
@leonardoporp I think you have "Don't keep activites" checked in developer options. I had similar problem and got resolved when I unchecked it

**Comment by weirleader** [comment]
Uncertain if it is better to revive this thread or start a new one -- very similar problem...  cannot send 21MB video file (*.mp4).  Tried enabling/disabling "Don't keep activities" in developer options, as described above, but it made no difference.  When attempting to send video, message received: "An item was removed because it exceeded the size limit".

File emailed to support@signal.org

**Comment by VahidTa** [comment]
Still this problem exist on Android platform. Nexus 5x android version 8. Error message is "an item was removed because it exceeded the size limit" when sending video files. I tried with iOS and it worked. But with android I get the error.
