### ISSUE TITLE
Voip calls notifications stopped

### ISSUE THREAD

**Issue by mnns** [signalapp/Signal-Android#8369]
Something is truly wrong with voice calls. It stopped notifying, calls are not getting through etc.
I can only see the call if I'm in the app at the exact moment someone calls me.

3 different devices approx. at the same time. Different networks (some WiFi, some 4g).

Android 7/8/9 on Samsung J7, S8 and A8.
Nothing changed on all devices.

**Comment by dorakas** [comment]
Can you submit debug logs. I think ows is not knowing how bad this issue really is. I know 5 of my friends that have Problem with this, all on different phones. greyson said this issue is a minority. but i think it is not

**Comment by mnns** [comment]
Well I only speak to 3 friends on Signal and 100% of them are experiencing the issue. 
This bug actually made us move to WhatsApp for calls. This is how bad it is.

**Comment by nnndnnn4** [comment]
same here, OnePlus 6 (P), no notifications at all.

**Comment by jpds** [comment]
This sounds like #8302 ?

**Comment by mawed** [comment]
Have this problem on this device.

Debug log here:
https://debuglogs.org/f19614a7e3609c436b0c2f5b0bdfebfbd1284ad73cb4ef444d19cdf7eaddaabd

Calling device is android beta. But the same problem appears when calling from Signal Desktop and Signal Desktop Beta.
