### ISSUE TITLE
Emoji spritesheet left visible on back action

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#8372]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

If one brings up the spritesheet, and then presses the back button, the emoji selection section goes away but the spritesheet is left in place instead of disappearing with the emojis.

### Device info
**Device:** Moto G6
**Android version:** 8.0.0
**Signal version:** 4.30.5

**Comment by greyson-signal** [comment]
I can't reproduce this, or really visualize it. Can you post a screenshot or video? Thanks!

**Comment by greyson-signal** [comment]
Oh wait I see now. By spritesheet you mean the pop-up you see to select a skin tone. I'll take a look, thanks!
