### ISSUE TITLE
Dark theme for AMOLED displays

### ISSUE THREAD

**Issue by husnanlateef** [signalapp/Signal-Android#8376]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The dark theme used to be #000, now it is some light shade, why the useless change in shade?

### Steps to reproduce
- install latest version as of now
- go to settings
- use dark theme

**Actual result:** the update has the dark theme in a slightly lighter shade.
**Expected result:** a full black theme as it was in the last version. AMOLED!

### Device info

**Device:** Samsung S5
**Android version:** 7.1.0
**Signal version:** 4.29.7

**Comment by greyson-signal** [comment]
As mentioned in our bug report template, we don't use Github for feature requests or discussion topics. Please move this to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!

**Comment by charsi** [comment]
forum theread discussing this feature is here - https://community.signalusers.org/t/restore-black-background-as-dark-theme/4571/17

**Comment by The-Hypervisor** [comment]
I don't know if I am allowed to share this but I made my own fork that has the AMOLED Dark instead of the old one.
https://github.com/The-Hypervisor/Signal-AMOLED
