### ISSUE TITLE
Support of multiple android devices for one account (i.e. tablet and smartphone)

### ISSUE THREAD

**Issue by szuetam** [signalapp/Signal-Android#8377]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by greyson-signal** [comment]
As mentioned in the bug template, Github is only for bugs, not feature requests. Please move this to [the forum](https://github.com/signalapp/Signal-Android). Thanks!

**Comment by Cerberus0** [comment]
@szuetam: Here is a link to the community forum: https://community.signalusers.org/

If you want, you can easily sign up / login with your existing GitHub account.

**Comment by hex-m** [comment]
For other who come here: the most relevant discussion in the forum seems to be [that one](https://community.signalusers.org/t/allow-android-ios-devices-e-g-tablets-to-be-linked-to-the-primary-device-i-e-used-as-secondary-device-like-the-desktop-app/2884).
