### ISSUE TITLE
Signal Permissions and new Google Play Developer Policy Updates

### ISSUE THREAD

**Issue by itdroiddev** [signalapp/Signal-Android#8380]
Hello,

Sorry for posting this here. This is not a bug report but more of a request for an opinion. If I was wrong to post this here, let me know and I will remove it.

Below is part of an email I received from google:

**In October, we [announced updates](https://www.google.com/appserve/mkt/p/ABMBUQOtAmNOjZxy_HaeN1QC4jchqumfjxInWRhIg8zEu_r1zW2PYzBXfvZCIHRE2xyHEIxcBxEMxM-iwke3UJoHAOrRbUsAUG7jEB7vRpZJ3CgRMIuxmZRk9xJkwe4II7a8op3HZaIFDYjqchPTkq_fW_4wTvostWxHYb0THBg) to our Permissions policy that will limit which apps are allowed to request Call Log and SMS permissions. This policy will impact one or more of your apps.
Only an app that has been selected as a user's default app for making calls or text messages, or whose core functionality is approved for one of the exception use cases, will be able to request access to Call Log or SMS permissions.**

Considering Signal requires permission for both SMS and Call Log, will the functionalities requiring these be removed or not. How will Signal comply with the new requirements from google?

**Comment by brownstic** [comment]
I think its best you take this topic to the signal community. Like you said this area is for issues with bugs and other errors that hinder the proper operation of the app.

LINK: https://community.signalusers.org

**Comment by itdroiddev** [comment]
Ok, thank you for posting it there.
