### ISSUE TITLE
Keyboard not responding when opening a message from the notification channel

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8384]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
----------------------------------------
Probably related to #8092
### Bug description
When you receive a message and you open it from the notification channel the keyboard is not responding, but if you press the "back" key and go to the conversation the keyboard is responding again.

### Steps to reproduce
- Receive a new message
- Open the message from the notification channel
- Try to write a new message

**Actual result:** The keyboard is not responding and you can not answer the message.
**Expected result:** The keyboard show up and you can write the answer.

### Screenshots

Don't needed

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.30.7

### Link to debug log

https://debuglogs.org/5faa9714fe59e191041529f79e042ad17237e4eb191e6b1dba27892de0e46247

**Edit:**

When the keyboard is not responding and you press the "Back" key one time it continue working.

**Comment by UserX404** [comment]
This issue also exist on Sony XZ2 compact (H8324) with Android 8.0.0.
I run into this several times.

**Comment by creideiki** [comment]
I have also seen this for a long time. Signal does it every time I open a conversation from a notification, but no other app does it.

One additional symptom: my keyboard (AnySoftKeyboard) is set to show and produce a capital letter for the first letter of a sentence. However, when in the non-responding state, the letters shown are lower case.

**Device:** Motorola Moto G5 Plus
**Android version:** 8.1.0 (LineageOS 15.1)
**Signal version:** 4.30.7
