### ISSUE TITLE
Messages aren't send and received

### ISSUE THREAD

**Issue by Dafnik** [signalapp/Signal-Android#8387]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After sending a message to a chat partner, the messages gets one tick but isn't sent to the other person. For the other person this bugs also appears. It a occurs much more often if both phones are in WLAN but also on GSM.
Important info: My chat partner is on the stable and I'm on the beta channel. For the time she hasn't received the sealed sender update this bug didn't occurred. Sometimes the message is sent but I'm still at only one tick. It's really strange.

### Steps to reproduce
Send messages to persons (sealed senders). I don't know when or how it occurs.

**Actual result:** Messages aren't sent
**Expected result:** Messages are sent like normal

### Device info

**Device:** Bq Aquaris X2 Pro
**Android version:** 8.1.0
**Signal version:** 4.31.0
My log: [Debug log](https://debuglogs.org/6c0cc0facc87428885a98a5f88a0f1029db3959f32c41f943fafa9d20ec39a91)

**Device:** Xiaomi Redmi 4X
**Android version:** 8.1.0
**Signal version:** 4.30.7
Partner log: [Debug log](https://debuglogs.org/85a1274d9f9765f0010aaefe4c119c5e137384d58f025bd556e943c4ab8b9308)

**Comment by PiCob** [comment]
Seems I am affected from this (at least the issue description reads exactly like that). My logs are here: https://github.com/signalapp/Signal-Android/issues/8305#issuecomment-440790047

**Comment by greyson-signal** [comment]
@Dafnik It looks like the receiver may have had a bout of poor network? Possibly hidden by the fact that they had cellular service (I see SMS sends go out), but things that require internet access are timing out for periods of 20min or so.

@PiCob It looks like you have a different issue. I'm going to DM you on the forum.

**Comment by Dafnik** [comment]
With other contacts I'm facing sometimes the same issues. Sometimes the messages take longer to send etc. But with this contact it's the worst. (I'm also writing the most messages to this contact)

**Comment by greyson-signal** [comment]
@PiCob Released 4.30.8 hotfix to beta + production to fix your issue. Let me know if it worked!

**Comment by Dafnik** [comment]
Can't tell yet if it fixed (didn't received the update yet) but the SMS were sent because normal messages weren't send but it was necessary to write to the other contact

**Comment by Dafnik** [comment]
Okay, after testing I found two things. First off all the push notifications didn't work anymore but messages were sent correctly. After I unregistered my phone and registered it back push notifications seem to work fine as normal.
Secondly, the encryption and sending of messages works fine.
Thank you for the really quick fix. It's a shame that no beta tester (I'm also one) found this bug.
