### ISSUE TITLE
Beta update 4.31 - > 4.30.8

### ISSUE THREAD

**Issue by sweah82** [signalapp/Signal-Android#8389]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After having installed version 4.31 yesterday (beta user), there was a new update today. I installed it... Now I have version 4.30.8 installed and typing indicator and the other changes of 4.31 are gone. I did not leave beta since yesterday. 

### Steps to reproduce

**Actual result:** Got back 4.30 after update to 4.31
**Expected result:** staying at 4.31

### Device info

**Device:** Samsung A3 2017 
**Android version:** 8.0
**Signal version:** 4.30.8

**Comment by greyson-signal** [comment]
This is intentional. There was a bug in production that needed to be patched, and with how the beta channel works, the only sane way to do it is to revert the current beta temporarily. After I've verified production is stable we'll get back to 4.31.x. Sorry for the confusion!

**Comment by PiCob** [comment]
This is actually intended (a hotfix was needed), see here:
https://community.signalusers.org/t/show-other-users-typing/2215/120
