### ISSUE TITLE
Screen does not wake on message received

### ISSUE THREAD

**Issue by tcannon91** [signalapp/Signal-Android#839]
It could just be my device (Galaxy S4) but the screen does not wake when I receive a message. It is inconvenient when I have my phone on silent sitting in front of me on my desk and the only notification is the LED blinking. Is there a way that it could be an option in the notification settings to enable waking the screen whenever a text/notification is received?

**Comment by Otiel** [comment]
Notification LEDs being more and more scarce, I believe it would be beneficial to review again this request.

I think most default messaging apps nowadays wake up the screen when there is a notification.

I don't think resorting to a 3rd party app is a recommendable way to fix this, as most of them come with unsupported devices.

**Comment by alan-signal** [comment]
@Otiel This was closed because some work was done. It would be best for you to start a new feature request thread over in the forum: https://community.signalusers.org/

**Comment by Otiel** [comment]
@alan-signal Thanks for the reply.

Found a [couple](https://community.signalusers.org/t/notifications-not-waking-lock-screen-samsung-s8/4244) of [threads](https://community.signalusers.org/t/edge-lighting-when-screen-is-off/7734) in the forum mentioning this issue already, for those who are looking for the same thing.
