### ISSUE TITLE
Signal downgrading from the Play Store

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8391]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you are a beta tester, you expect to have the most recent version and news features of Signal. When a "stable release" is launched after of a new beta release, Signal is downgraded to the "stable release".

### Steps to reproduce
- Upgrade from the play store to a new release (v4.31.0 in my case), that release have the Typing notifications support.
- Wait for a new "stable" release (v4.30.8)
- Signal downgrade from 4.31.0 to 4.30.8

 Please see https://github.com/signalapp/Signal-Android/releases

**Actual result:** Signal downgrade from a higger version to a minor version as a "Update".
**Expected result:** If the installed version is higger than the new "available release" Signal does not show a "update notification" in the Play Store.

### Screenshots

Not needed.

### Device info

**Device:** Samsung SM-G670M
**Android version:** 8.1.0
**Signal version:** 4.30.8 (after of the downgrade)

### Link to debug log

Non needed and probably useless.

**Comment by rainerzufall** [comment]
ducplicate of https://github.com/signalapp/Signal-Android/issues/8389

please close this issue, since:
>@greyson-signal: "This is intentional. There was a bug in production that needed to be patched, and with how the beta channel works, the only sane way to do it is to revert the current beta temporarily. After I've verified production is stable we'll get back to 4.31.x. Sorry for the confusion!"

**Comment by Edu4rdSHL** [comment]
@rainerzufall thanks.
