### ISSUE TITLE
Verification SMS received but not detected by Signal

### ISSUE THREAD

**Issue by imreagocs-epicycle** [signalapp/Signal-Android#8392]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After installing the app the SMS with verification code is received but is not detected by Signal. I am able to register once I manually enter the code, with previous versions the user did not have to do that.

### Steps to reproduce
- Install the app from the Play Store
- Enter the phone number
- SMS with verification code is received but is not detected by Signal

**Actual result:** SMS with verification code is received but is not detected by Signal
**Expected result:** Signal should have read that SMS and extracted the verification code from it, so that the user does not have to do that manually

### Device info

**Device:** HUAWEI P smart
**Android version:** 8.0.0
**Signal version:** 4.30.8

### Link to debug log

https://debuglogs.org/921baf20c8685a5eaa1bb517b1b632b97a61ed5b27d4a46b1848d37b015dbbf2

**Comment by greyson-signal** [comment]
I recently made changes that should address this in 4.32. Starting in 4.32, if you have Google Play Services on your device, the code should be automatically read. If you don't, you'll have to enter it manually.
