### ISSUE TITLE
The noise cancellation microphone is used instead of the voice microphone

### ISSUE THREAD

**Issue by ryanbytes** [signalapp/Signal-Android#8394]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video calls use the voice cancellation microphone as the call audio input for the video call.

### Steps to reproduce
- Create a voice call
- Turn on audio via the speaker

**Actual result:** Video call audio input is via the noise cancellation microphone.
**Expected result:** Video call audio input should be via the voice microphone.

### Device info

**Device:** Nokia 6.1 Hardware version: TA-1045
**Android version:** 9 Build: 00ww_3_260
**Signal version:** 4.30.8

### Link to debug log
https://debuglogs.org/411272ef47f08d8aeeabed372c8f3d0a3aa2ec9fd0c1f0aca3e8f9d683864188

**Comment by Le1b1** [comment]
Same here on a Nexus 4 and a Pixel 2.
Ist this a bug or a feature?
Maybe the reason why (IMHO) the audio quality in a video call is worse compared to e.g. Google Duo?
