### ISSUE TITLE
Proximity sensor is used during voice calls with external microphone

### ISSUE THREAD

**Issue by btlvr** [signalapp/Signal-Android#8396]
### Bug description
The proximity sensor is used to turn the screen on/off, even when the built-in microphone is not in use. 

### Steps to reproduce
* Make a voice call while using external speakers/microphone

**Actual result:** The proximity sensor is active, and sleeps/wakes the screen during the call. This makes it difficult to use the phone while on the call, because I have to make sure not to bring my hand too close to the top of the phone. It also makes it difficult to turn the screen off during the call. If I turn the screen off using the power button, it gets woken back up when something moves past the proximity sensor.

**Expected result:** The proximity sensor should not be used for anything when the built-in microphone is not in use. 

### Device info

**Device:** Google Pixel 1
**Android version:** 9
**Signal version:** 4.30.8

**Comment by btlvr** [comment]
REEEEEEEEEE

**Comment by laurencebgood** [comment]
This issue also occurs when using the built in microphone and speaker in "speakerphone" mode, which makes multitasking difficult and frustrating.
