### ISSUE TITLE
App crashes when placing a call using Blokada

### ISSUE THREAD

**Issue by fua47300** [signalapp/Signal-Android#8399]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using Blokada (ad blocker app) - Signal crashes when I try to make a call (even with no blocklists). Several versions ago - there was no issues. Other IM apps work flawlessly.

### Steps to reproduce
- Install Blokada
- Start Blokada
- Try to make a call using Signal

**Actual result:** Signal crashes
**Expected result:** Call is established

### Device info

**Android version:** 5
**Signal version:** 4.30.8

**Comment by greyson-signal** [comment]
Installed blokada, can't repro. Post a link to a debug long (Settings > Advanced > Submit debug log) if it's still happening.
