### ISSUE TITLE
Features suggestions

### ISSUE THREAD

**Issue by AlecClaire** [signalapp/Signal-Android#8412]
Hey devs

Few suggestions:
- chat heads like i devil's Facebook Messenger - it's extremely useful
- any web browser access (the PC app often freezes and it's heavy) -- it's easier just to pull a new tab
- fix for android app for non mobile network devices (tablets) so that it can work
- emoji recognition with well know shortcuts, e.g. when I type ":D" id doesn't convert into an image, similarly typing" : joy : " (without spaces of course) is quite burdensome, it would be nice as the emoji would pop up a a suggestion to use instead the typed word
- some GIF library would be nice as it it's in devil's Facebook Messenger
- link preview/thumbnails weather to websites or videos

As much as we all don't trust the devil's Facebook Messenger they have some useful features that can be imported to Signal.

Keep up the good work fellas!

**Comment by rainerzufall** [comment]
Hej @AlecClaire. While I agree with some of the feature request themselves, as mentioned in the bug report template, Signal devs don't use Github for feature requests or discussion topics. Please move this to the [forum ](https://community.signalusers.org/c/feature-requests/android-feature-requests) and close this thread. Thanks!
