### ISSUE TITLE
Registration Lock Pin was not verified on new install

### ISSUE THREAD

**Issue by daivat15** [signalapp/Signal-Android#8414]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Registration Lock Pin was not asked when I changed my phone and installed Signal on it.

**Actual result:** Sign up process went normally as though I was signing up on Signal with my phone number for the first time.
**Expected result:** Registration lock pin should have been asked and verified.

### Device info
**Device:** Redmi Note 4
**Android version:** 8.1.0
**Signal version:** 4.30.8

### Link to debug log
https://debuglogs.org/fef2866c23ea1fee166f99986d3c8ca7fdc3164ee803d094deac16061a9e4f7a

**Comment by jlund-signal** [comment]
Were you seeing [Registration Lock PIN reminders](https://support.signal.org/hc/en-us/articles/360007059792-Registration-Lock) on your old device? Registration Locks also expire after 7 days of inactivity.

**Comment by daivat15** [comment]
Yes, I was. I'm also quite sure there was not a phase of 7 days of inactivity, though I was unaware that the lock pin expires. Maybe show a notification or something so that the users know next time.
