### ISSUE TITLE
feature request: disappearing messages after 1,2,3,6,12? months

### ISSUE THREAD

**Issue by dddw** [signalapp/Signal-Android#8416]
ok not really a new feature. But I'd love to see the dissappearing messages threshold raised to a longer term

You could say this goes against the whole idea of dissappearing. But one weak is pretty short. For instance I wouldn't want to delete messages of my significant other after just 1 week. 3 months would work fine however.

I'd bet it helps a good scrub for the signal servers if there would be a max of 12 months of storage unless specified.

What do you think?

I would definitly

**Comment by greyson-signal** [comment]
As noted in the new issue template, we use Github for bug reports, not feature requests. Please move this to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
