### ISSUE TITLE
Unable to send large videos

### ISSUE THREAD

**Issue by bisherbas** [signalapp/Signal-Android#8421]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to send large videos to other Signal users. My device is stock OnePlus 5T.

### Steps to reproduce
- Take a 1-minute 1080p 30fps video on your Android phone (i.e. ~100 MB)
- Attempt to send the video to a Signal group or another Signal user (NOT MMS)
- Android notification appears at the bottom of the screen saying "Attachment exceeds size limits for the type of message you are sending"

**Actual result:** Video won't sent
**Expected result:** Video should send

### Screenshots
N/A

### Device info

**Device:** OnePlus 5T
**Android version:** 8.1.0
**Signal version:** 4.30.8

### Link to debug log
https://debuglogs.org/74958957450322a75cfdaff3d8fd78982a2858819d3137ab9fa278717434decb

**Comment by leonardoporpora** [comment]
What's the size of the video? If its larger than 100MB Signal won't send it

**Comment by bisherbas** [comment]
Yes it is more than 100 MB but a lot larger files could be sent from iphone. Cant Signal Android resize video before sending like whatsapp? And it already works fine on iphone.

**Comment by greyson-signal** [comment]
@bisherbas See [this forum post](https://community.signalusers.org/t/option-to-compress-video-record-video/3833/6) for more details around the difficulties of doing video transcoding on Android.

**Comment by ve2vdi** [comment]
Try SendClip from: 
<b>http://easyupload.io/om1100<b>

**Comment by HZY556-cloud** [comment]
I am using Signal. I was trying to post videos with filesize 50MB, 90MB, and 145MB respectively. My device(the Sender) can see the videos but the Receiver cannot. If max. file size 100 MB, those videos with 50MB and 90MB should be able to be seen. Any explanation?

**Comment by KnowMoreIT** [comment]
> I am using Signal. I was trying to post videos with filesize 50MB, 90MB, and 145MB respectively. My device(the Sender) can see the videos but the Receiver cannot. If max. file size 100 MB, those videos with 50MB and 90MB should be able to be seen. Any explanation?

This is still an issue today. 47MB video trying to send to Signal user and it can't send it. It's hit or miss rather videos send or not. Very frustrating

**Comment by pedroapero** [comment]
Same issue here, please settle on a clear file size limit. I lost time resizing my video to find out that even 70MB does not work.
