### ISSUE TITLE
All encrypted messages fail to send

### ISSUE THREAD

**Issue by gbear605** [signalapp/Signal-Android#8425]
- [ x ] I have searched open and closed issues for duplicates (read all relevant issues for "send failed" back to July 2015)
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently got my friend to install Signal for the first time on their Android. They created an account, but when they send any encrypted messages, it fails, saying "Send failed, tap for details." If you tap on it, it says "Some issues need your attention," and there is a resend button. Clicking the resend button does nothing. This applies for both sending messages to groups and to individual users. Receiving messages work fine. Sending unencrypted messages (non-Signal messages) works fine.

All the steps at https://support.signal.org/hc/en-us/articles/360009303072-Troubleshooting-sending-messages were checked and none are relevant.

### Steps to reproduce
- Install signal and create account
- Send message to anyone, including users that have already messaged you

**Actual result:** Get error message
**Expected result:** Send message successfully

### Device info
**Device:** Samsung Galaxy S8i
**Android version:** Stock Android 8.0.0
**Signal version:** 4.30.8

### Link to debug log
This debug log was made right after the issue happened: https://debuglogs.org/52ac068c7e5871bdd4403a1e3b241be4461789a029c6f56ebf7df9097357d384

**Comment by greyson-signal** [comment]
This user apparently registered in poor network conditions, causing them to never be able to fetch a sender certificate. In the short-term, try having them restart their device. I'm putting in a fix now.

**Comment by Pratiwir** [comment]
I've been getting a lot of message sending problems. Alert then have to open the failed message and resend, it usually goes the second or third time.
My complaint is wasting time doing this, it should try automatically a few times, I don't see why the user has to keep doing this.
