### ISSUE TITLE
Latest beta version (4.31.4) pauses multimedia reproduction on notification

### ISSUE THREAD

**Issue by kpuljek** [signalapp/Signal-Android#8428]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Starting with the latest Signal beta update, when I send or receive messages on Signal, it keeps pausing multimedia reproduction. At first I thought my bluetooth headphones are broken, but I tested it using wired headphones and it also kept pausing the music.

Tested on 2 different phones with two different headphone models, both phones updated to 4.31.4

### Steps to reproduce
- play music
- start sending and receiving messages on Signal

**Actual result:** Music will start pausing at random, probably when the notifications start playing. it happens even when the phone is in complete silent DND mode.
**Expected result:** Music should keep playing uninterrupted with random notifications.

### Screenshots
No relevant screenshots.

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0.0
**Signal version:** 4.31.4

**Device:** OnePlus X
**Android version:** Some Lineage 14 version, unfortunately I don't have the phone with me
**Signal version:** 4.31.4

### Link to debug log
I pulled this one as soon as the music stopped when I asked my friend to send me a message. Hope it helps:
https://debuglogs.org/a90a81f6e7ffe41f537de14a9b402752dd0e6c28182aeaecd4cf987474f1032a

**Comment by greyson-signal** [comment]
In my experience, if I'm playing music, receiving a notification from any app (including Signal) has always caused the music to at least be lowered so you can hear the notification. Specific handling has changed with OS updates. But I guess I don't find this behavior particularly surprising.

However, there was a notification change in 4.31.4 that will be reverted in 4.31.5, so let me know if this problem goes away in 4.31.5. Thanks!

**Comment by kpuljek** [comment]
Ok, I'll see if the update helps. Maybe I didn't make it clear enough - it doesn't interrupt the music, it pauses it, as in I have to press play again

**Comment by Heimo001** [comment]
this problem still exists. before the update 2 months ago, the music became quieter when a notification was received. Now the sound goes off completely (not paused) and only after a few minutes becomes loud again. This happens not only when receiving a message, but also when sending.

**Comment by greyson-signal** [comment]
Even when sending? We don't even have a sending sound. Are you referring to replying directly in a notification, maybe? OnePlus might have a sound they use in that situation.

But give you're both OnePlus users, this might be a OnePlus/OxygenOS-specific problem. Was there an OS update around the same time you started noticing this behavior change? Do other apps with audible notifications do the same thing? 

Honestly we don't do anything crazy with notifications and sound for message notifications -- we just specify the sound to play via the notification channel and then post a notification. Very standard.

**Comment by kpuljek** [comment]
I had this issue back on 4.31.4, and IIRC the next version had some audio-related rollback and I haven't had that issue since. Maybe this is something else, it works okay for me now. 0 OS updates as well.
