### ISSUE TITLE
Recipients who don't open Signal don't know they have messages.

### ISSUE THREAD

**Issue by travisfw** [signalapp/Signal-Android#8431]
### Bug description
People who have tried signal don't get my messages.

I'm stuck having to tell them to uninstall the app just to receive my messages.

### Steps to reproduce
- send anyone who has tried Signal a message

**Actual result:** No response until recipient opens the Signal app.

**Expected result:** Recipient gets notified they have messages.

### Screenshots
https://app.box.com/s/icw1p1mx68m3jyce88z47juwtor84ros

_(Sorry for the Box link. Github doesn't like my jpeg, saying "Something went really wrong". If I can figure out how to upload I'll edit and replace the Box link.)_

**Comment by piratenpanda** [comment]
Could you please post the smartphones and the Android version they are running? Also make sure the manufacturer doesn't automatically battery optimize signal so the app is hibernated when not active. That's what I would suggest first.

**Comment by greyson-signal** [comment]
There's a lot of questions here. Most of them could be answered if I could get a debug log from the recipient (Settings > Advanced > Submit debug log -- post the link you get here).

**Comment by stonecrusher** [comment]
I got the same problem.
The message has already been delivered to & read on Signal Desktop before.

On the phone the message only arrived after manually opening Signal for Android.
Debug log of receiving phone:
https://debuglogs.org/7e8cf48b0478eb8ef67ba37f9d57e243a755a2f4db77db67004b04dcf0f98597

**Comment by greyson-signal** [comment]
@stonecrusher If a message has been read on desktop, we explicitly won't notify the user on their mobile device. Otherwise, if you're sitting at your desk using desktop, you'll get tons of double-notifications on your phone.
