### ISSUE TITLE
Voice note seeking not working.

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8432]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you are playing an audio, if you tried to advance some seconds, the audio start reproducing the initial point always if the cursor is in another second (like the end of the audio). Basically if you start the audio in any point it start reproducing in the initial point instead of the real point.

### Steps to reproduce
- Receive a audio
- Start reproducing it
- Try to start it in another point of the audio
- Wait to hear the same content of the begin of the audio.

**Actual result:** The audio reproduce the same begin content in any point that you try to reproduce.
**Expected result:** The content is according to the point where the cursor is moved.

### Screenshots

Not needed.

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.31.5

### Link to debug log

https://debuglogs.org/e1dc1430ca1676401c7d90f28a873569b14915fca0b559f15f919a29c5417065

**Comment by greyson-signal** [comment]
I just want to restate the problem to make sure we're on the same page. Are you saying that if you seek in the audio player, it will always play from the beginning?

I tried on several different phones and was unable to reproduce this. I was voice notes that were ~15 seconds long. I know ExoPlayer said that AAC seeking is best-effort, so it could be related to that, but I also haven't been able to hit it.

Were you playing a random audio file, or were you playing a voice note that was recorded in-app?

**Comment by Edu4rdSHL** [comment]
> I just want to restate the problem to make sure we're on the same page. Are you saying that if you seek in the audio player, it will always play from the beginning?

Yes, I'm.

>Were you playing a random audio file, or were you playing a voice note that was recorded in-app?

I'm playing voice notes that was recorded in-app and I can reproduce the issue just now and including my own voice notes.

**Comment by greyson-signal** [comment]
I was able to reproduce this on a Huawei Mate 10 Lite running Android 8.0.

**Comment by PiCob** [comment]
I found a related (?) bug, maybe someone can confirm it:

- start playing a voice note
- pause it after some seconds
- turn the screen off and on again
- continue playback

--> For me, although the seeking cursor continues to move on from the pausing position, playback starts from the beginning (it was reproducable for me if I used an approx. 4 seconds voice note and paused after 1-2 seconds)

### Link to debug log
https://debuglogs.org/5e01aa471e1074824b80c0a87e4146f366e283cee97b98a4275108b52580e710
(for example, look for "2018-12-11 17:16:15.628")

**Comment by greyson-signal** [comment]
I'm no longer able to reproduce this on any of my phones after the fix. It's rolling out to beta and part of production right now. Lmk if you still see this problem after updating to 4.31.6. Thanks!

**Comment by Edu4rdSHL** [comment]
Thank you @greyson-signal, the commit fixed the issue for me.
