### ISSUE TITLE
exoplayer-core missing upon build

### ISSUE THREAD

**Issue by Woodzrul** [signalapp/Signal-Android#8434]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to build using Android Studio due exoplayer dependencies missing.

### Steps to reproduce
- Merge new changes within Android Studio (been doing this for months)
- Process does not complete at Configure build stage

### Device info
Microsoft Windows 10 Professional
Android Studio 3.2.1

### Issue
I am being presented with a lot of exoplayer dependencies missing when trying to build Signal.
Could not find com.google.android.exoplayer:exoplayer-core:2.9.1.

When I try browsing to one of the below links (from the log file) I am presented with a 404 Not Found page.
https://repo1.maven.org/maven2/com/google/android/exoplayer/exoplayer-core/2.9.1/exoplayer-core-2.9.1.pom
https://raw.github.com/signalapp/maven/master/preferencefragment/releases/com/google/android/exoplayer/exoplayer-core/2.9.1/exoplayer-core-2.9.1.pom

Is this a known issue? How do I download exoplayer and add to my Android Studio installation?

Thanks

**Comment by greyson-signal** [comment]
We build the app with a publicly-available docker image (see the [reproducible build guide](https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds)). This has been working, so you must have something misconfigured locally. Feel free to use the docker image as a guide. For more help, you're encourage to post on [the forum](https://community.signalusers.org/). Thanks!

**Comment by Woodzrul** [comment]
Maybe a potential issue globally as starting a fresh project (new build) also fails.

https://github.com/google/ExoPlayer/issues/5225
https://github.com/flutter/flutter/issues/25145

Apologies if I am mistaken.

**Comment by greyson-signal** [comment]
Apologies, yeah, looks like Google in general had a fun day today: https://www.reddit.com/r/androiddev/comments/a4wpuk/for_anyone_wondering_about_todays_failed_builds/

In which case all we can do is wait or use one of the several workarounds offered. I'm fortunate that I have all of the artifacts cached locally from previous builds.
