### ISSUE TITLE
Privacy options (including View Safety Number) missing in Conversation Settings

### ISSUE THREAD

**Issue by 2011** [signalapp/Signal-Android#8435]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Posted this on https://community.signalusers.org/ (thread 5145), and was told to file a bug report here. :) Basically, I have an Android emulator (which, admittedly, is running an older version of Android - 4.4.2), where, if I go into Conversation Settings, the Privacy section is simply not there (as it is on my phone), which gives me no way to view or verify safety numbers. I am running 4.30.8 on both devices. I believe the ability to display and verify safety numbers on this device was present in past versions of Signal.

### Steps to reproduce

See above.

### Screenshots

Not really much to see. The settings end with Call Settings / Ringtone (the emulator has no vibrate capability).

### Device info

**Device:** In the "About" section, the model number is listed as genymotion_vbox86tp_4.4.2_140326_033000
**Android version:** 4.4.2
**Signal version:** 4.30.8

### Link to debug log

https://debuglogs.org/152c9a3ae2babe920b87b87a0fbe310c15514842cc5ad7bff8509f0c6f3e4e16

Happy to provide any additional information you require.

**Comment by 2011** [comment]
Was offered (and accepted) an update to 4.31.6 on this device, as well. Again, the problem still exists on the newer version.

**Comment by greyson-signal** [comment]
Can you send a screenshot of what this looks like? The only reason we'd hide the "View Safety Number" button is if you're viewing the details of a group. I can't repro on any devices. And we'd never hide the  Privacy section as a whole.

**Comment by 2011** [comment]
This is scrolled down as far as it will go. Don't really know how it will help, though.

![image](https://user-images.githubusercontent.com/550150/50037838-c0c19e00-000d-11e9-9896-3d536b3d30bb.png)

**Comment by 2011** [comment]
Problem still exists in 4.33.5.

**Comment by greyson-signal** [comment]
Booted up a 4.4.2 emulator from Android Studio and can't repro this. From your screenshot, it's not that the sections are missing, it's that you apparently can't scroll down. But I can't repro it. No scroll issues on any device or emulator I have access to. Maybe it's your emulator, can't be sure.
