### ISSUE TITLE
No notification on Withings smartwatch

### ISSUE THREAD

**Issue by egvimo** [signalapp/Signal-Android#8437]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I receive messages with Signal, no notification is shown on the smartwatch (Withings Steel HR Sport).
Messages from other apps (Whatsapp, GMail, etc.) are showing up.
I also noticed that Signal does not appear in the system settings for notifications (but it does appear in the other settings linked via Signal).
As you can see from the screenshots, WhatsApp appears in the list. Signal not, although a notification came from both at almost the same time.
Also, I'm not the only one with this issue: https://www.reddit.com/r/withings/comments/a3a7qa/problem_with_signal_app_notifications/

### Steps to reproduce
- Connect the smartwatch with the device (using Health Mate app)
- Setup notifications for the smartwatch
- Activate notifications for Signal for the smartwatch
- Receive a message

**Actual result:** Smartwatch stays silent / Signal is not listed in the notification settings
**Expected result:** Notification pops up on the smartwatch / Signal appears in the notification settings list

### Screenshots
Google Pixel 2 (click to enlarge)
<img src="https://user-images.githubusercontent.com/5247100/49824881-601f3080-fd83-11e8-84d9-fd72219c7301.png" width="360" height="640"/>
<img src="https://user-images.githubusercontent.com/5247100/49824882-601f3080-fd83-11e8-8b5f-52e1209370ba.png" width="360" height="640"/>

On a Nokia 7 Plus (Android 9) it looks like this:
<img src="https://user-images.githubusercontent.com/5247100/49896965-1a329d00-fe55-11e8-8cd2-e5b27ce081f0.png" width="360" height="720"/>

### Device info
**Device:** Google Pixel 2
**Android version:** 9
**Signal version:** 4.31.6

**Comment by egvimo** [comment]
On a Nokia 7 Plus (Android 9) it looks like this:
![signal-2018-12-12-211232](https://user-images.githubusercontent.com/5247100/49896965-1a329d00-fe55-11e8-8cd2-e5b27ce081f0.png)

**Comment by egvimo** [comment]
I'm not the only one with this issue: https://www.reddit.com/r/withings/comments/a3a7qa/problem_with_signal_app_notifications/

**Comment by mctel** [comment]
I have exactly the same issue with my Suunto 9

**Comment by nwl** [comment]
Same for me with Pixel2, Steel HR and Signal 4.32.8.

**Comment by tom-mayer** [comment]
I have the same issue here. Weird thing is that once a week or once every two weeks a notification from signal makes it through to the watch.

**Comment by egvimo** [comment]
After today's update (4.34.8), the notifications now seem to work.

**Comment by nwl** [comment]
No change for me. Signal doesn't appear in Withings notifications app list and notifications are still not coming through.

**Comment by egvimo** [comment]
Do you use Signal as default SMS app?
I don't do that and it appears in my list. Because for the SMS app there is an entry at the top of the list in the Withings notification settings.

**Comment by tom-mayer** [comment]
For me it shows up in the list, and is also checked, just the notifications don't arrive.

**Comment by nwl** [comment]
Yes,  I use it as my default app.

**Comment by morphiumdeus** [comment]
I have the same problem. No notifications on Suunto Spartan WHR, Android 9. It is also my default SMS app. Any news on this?

**Comment by nwl** [comment]
Works fine for me now. Ticket can be closed from my perspective..

**Comment by ddddavidmartin** [comment]
I'm still seeing this issue with a Fossil watch. I can reproduce it not working every time, but I'm not entirely sure what to look for. 

Someone else created a similar issue just a short while ago as well: https://github.com/signalapp/Signal-Android/issues/9034

**Comment by ddddavidmartin** [comment]
> I have the same issue here. Weird thing is that once a week or once every two weeks a notification from signal makes it through to the watch. It's not completely dysfunctional for me (Sony xperia x xcompact with Android 7.1.1), but doesn't work 99% of the cases. Must have to do something with the way Signal handles it's usual notification.

I'm seeing the same where every once in a while it works. I'm not sure whether the fault is with Signal though. For example I extended someone's excellent NotificationListener example to try out what's going on:

https://github.com/ddddavidmartin/notification-listener-service-example

If you build and run that it will show a toast for every notification it intercepts. And it sees the Signal notifications every single time. So now I'm at a bit of loss what the problem is. Unfortunately in my case the Fossil app is closed source.

**Comment by anoteng** [comment]
Having the same issue on huawei watch gt2. It used to work reliably on my samsung watch on the same phone.

**Comment by jamfx** [comment]
I just got my new Huawei Watch GT2e and I have the same issue. I can not choose Signal from the Apps to get notifications from. So I can not even push the notifications to the clock. What's this bug about?

**Comment by MartinWallgren** [comment]
Try to give your smartwatch access to sms and enable sms notifications.
That gave me signal notifications for my Amazfit GTS.

**Comment by jamfx** [comment]
Of course I granted access to everything. I also reinstalled health app. I think, this is not an Si ignal issue. It MUST be an issue from Huawei. It works on a Honor 6x and Honor Band 5 like Charm. Sometimes I got notifications "accidentally". So it must be on Huaweis side.

**Comment by berni2288** [comment]
I also don't see the Signal app in the notifications list of the Huawei health app and the app has all permissions...
I also assume that it's a problem with Huawei. The app is also crashing often and looks cheap, guess I will not buy something from Huawei anymore...

**Comment by jamfx** [comment]
I finally managed to get it working. It's so bad easy and yet so stressful. My solution was: Go in Health App and activate "Messenger" and "Messages" to get notifications for Signal. Because Signal-App replaces the normal Messenger / Messages App, it's taking over their Notifications in the System. At least this solved the problem on my Huawei P20 Pro and on my One Plus 8 Pro and One Plus 9 Pro. Sidenote: On my OnePlus 9 Pro I had the Signal App also in the Health App shown... So crazy stuff with this Huawei-Health App. So solved for me.
