### ISSUE TITLE
Error recording/saving/sending voice note

### ISSUE THREAD

**Issue by PiCob** [signalapp/Signal-Android#8440]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A friend said she had trouble recording/sending a voice note:
- she recorded as usual (it was just a few seconds)
- after finishing, (according to her) the voice note message "somehow didn't get sent"
- a little later the message seemed it was sent, but when she clicked on the voice message, the seeking cursor jumped around to approx. 2 minutes (although the message was only a few seconds!) and wouldn't play on her phone (note: at no time was she affected by issue #7748). So it seems her voice note got corrupted during recording or preparation for sending.

She mentioned that she might have had a bad network connection at that moment.

### Steps to reproduce
- no idea... it hasn't happened since

**Actual result:** Voice note seemingly got corrupted during recording or preparation for sending
**Expected result:** Shouldn't happen - or at least the voice message shouldn't be sent in such a case

### Device info
**Device:** Sony Xperia Z3 (D6603)
**Android version:** 6.0.1
**Signal version:** 4.30.8

### Link to debug log
https://debuglogs.org/393f6c6a1a8fe463559578f3c4b0f5f3ce660a7a5b89e810f1c6fd8423b95ab7
(look for the string "startRecording")

**Comment by Leptopoda** [comment]
This should be fixed with version 4.31.
It started rolling out just a few days ago.

**Comment by tuxayo** [comment]
Related to #7748, I also have sometime problems with my own messages, aren't the two linked?
