### ISSUE TITLE
Users continue to receive some messages from a group after leaving

### ISSUE THREAD

**Issue by billius** [signalapp/Signal-Android#8443]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a user leaves a group conversation, it appears that in some cases there are members of the group that don't receive the "user has left the group" message. when these members subsequently send messages to the group, they are delivered to the user who has left.

There currently doesn't appear to be any method of group syncing in the case where there's a message delivery failure.

### Steps to reproduce
- a user leaves a group chat (generally in a large group)
- each member of that group receives a 'User has left the group message'
- one or more members never receive the 'User has left' message messages the group
- messages from that group member are delivered to the user who has left
- user is unable to stop receiving these messages

**Actual result:** 
Users who have left group chats receive messages from some other group members

**Expected result:** 
Users who have left group chats should not receive messages from the group chat

### Device info
Happens across all versions of signal, including signal desktop

### Link to debug log
Have not been able to catch this at the time someone leaves the group

**Comment by billius** [comment]
I also apologize for not adding screenshots, the groups where this has occurred have potentially sensitive information.

**Comment by greyson-signal** [comment]
Hey, so groups are definitely something we're looking at improving, and this is on our radar. In the meantime, if a user who left wants to stop getting added back in, they can block the group by going  to the group conversation -> three-dot menu -> Conversation settings -> Block. Hope that helps in the meantime, thanks!

**Comment by billius** [comment]
Thanks. 

is there another parent issue that tracks those group improvements?

**Comment by Cerberus0** [comment]
Feature requests are discussed and tracked on the community forum. There's at least one open thread that is tracking the improvement of group chats:

* https://community.signalusers.org/t/improving-signal-group-chats/979

You can easily join the forum with your existing GitHub account and receive email notifications when the thread is updated.
