### ISSUE TITLE
Profile photos not displayed

### ISSUE THREAD

**Issue by 2011** [signalapp/Signal-Android#8444]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Strangely enough, I also posted this on https://community.signalusers.org/ (thread 5145), as I did with bug #8435, but they appear completely unrelated. I mention that thread (and other bug) to explain that (in this case) the feature works fine on the emulator, but not on the real phone. These are independent (both 4.30.8) Signal installations (having different phone numbers, of course) with the same set of contacts. Profile photos appear on the emulator, but the phone just displays the colored circle with a letter inside.

### Steps to reproduce

Don't have to do anything to (re)produce it - it is just there.

### Screenshots

Don't see the usefulness of a screenshot in this case.

### Device info

**Device:** Blueboo Maya Max
**Android version:** 6.0.1 (ROM based on LineageOS 13.0 obtained on XDA-developers)
**Signal version:** 4.30.8

### Link to debug log

https://debuglogs.org/a428b540cd0742deac1c4ffa5dd67c8938b49d864083e03f70a730e34f8ceda1

Once again, happy to provide any additional information.

**Comment by 2011** [comment]
Problem still exists in 4.33.5.

**Comment by vpfaiz** [comment]
Photos are displayed but not the one set by the contact, but the one you have in your address book

**Comment by greyson-signal** [comment]
We currently prioritize your contact photo. We may change this in the future.
