### ISSUE TITLE
Typing indicators do not display when using gesture/swipe input

### ISSUE THREAD

**Issue by andrewazores** [signalapp/Signal-Android#8448]
Using Google Gboard keyboard, typing indicators are not displayed on the recipient's device if the sender inputs text using gesture/swipe typing (rather than tapping individual keys).

**Comment by greyson-signal** [comment]
In my testing, the typing indicator will show after you release your finger from a swipe and the text input is changed. I agree that it won't show *as* you're swiping, but this is intended behavior. We consider a user 'typing' if the text input content is changing.
