### ISSUE TITLE
Verification code (sms/call) not working in Cuba

### ISSUE THREAD

**Issue by davidpa9708** [signalapp/Signal-Android#8450]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

### Bug description
Not getting the verification sms/call in Cuba.

**Actual result:** Not getting the verification code.
**Expected result:** I should be able to recieve the verification code.

**Comment by riyapenn-signal** [comment]
Sorry to hear about registration issues with your number, David. We're still working with providers in Cuba to ensure the SMS will arrive and we're looking into issues with calls. Signal support (support@signal.org) has sent you an email to follow up with this.

**Comment by davidpa9708** [comment]
Ok, thank you, I'll check my email

**Comment by luisenrike** [comment]
This isn't working yet

**Comment by riyapenn-signal** [comment]
We're still waiting to hear back from ETECSA - CUBACEL to ensure the SMS will arrive. @luisenrike Signal Support has responded to your email as well.

**Comment by jromero2k** [comment]
Hi, is there any alternative way to verify a Signal installation? I changed phones and now I can't get my Signal back

**Comment by CCABFF** [comment]
Still not working sms registration in Cuba, please assist.

**Comment by luisenrike** [comment]
Same here for Cuba ✋

**Comment by chicoloquis** [comment]
Any way to get around ETECSA? They WILL NOT allow SMS confirmation since they're state-owned.

**Comment by riyapenn-signal** [comment]
You can now register for Signal in Cuba :) The verification code will come from SignalApp.

**Comment by raymand211092** [comment]
Again the same problem from cuba can not be registered

**Comment by jromero2k** [comment]
can confirm, a couple of friends had recently the same issue. I never understood what's the point of basing Signal identities on something you don't control. Anyone who owns a telco can kick you out of your account and there's nothing you can do about it 🤦🏽‍♂️
