### ISSUE TITLE
On phones with 2 SIM cards, signal ignore settings of default SIM card selected to send SMS

### ISSUE THREAD

**Issue by mr-gosh** [signalapp/Signal-Android#8452]
- [x] I have searched open and closed issues for duplicates (based on closed bug #7167 )
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a multi sim phone (in my case oneplus 5), signal does not respect the android sim configuration which sim card should be used for sending sms messages.
You can change the setting for every chat conversation by long pressing the send button but this can be forgotten, so signal should read out the setting in android or at least provide a configuration of the standard sender number.

### Steps to reproduce
- open signal chat with sumone not contacted before and ehatch which numner is selectwd by default (in my case sim2
- go to android sim config and select on message exchange the other sim card (in my case sim1)
- now signal should uae that number on new unconfigured message send requests

**Actual result:** 
- recognize that signal is still using sim2 by default and you can't change that behaviour in signal

**Expected result:** 
Signal should read out the standard message send simcard from the android config or providenits own configuration for selecting a standard sim

### Screenshots
Will follow

### Device info

**Device:** OnePlus 5
**Android version:** 9
**Signal version:** 4.31.6

**Comment by halb9** [comment]
I dont't know if this has something to do with it but like OP I live in germany, however my phone is set to english. 

### Screenshots
![01](https://user-images.githubusercontent.com/18451020/50056705-f377ad80-0157-11e9-80c7-502c36fd2642.jpeg)
![02](https://user-images.githubusercontent.com/18451020/50056712-fecad900-0157-11e9-8963-195f9f41ce73.jpeg)


### Device info

**Device:** OnePlus ONEPLUS A6003 (OnePlus6)
**Android version:** OxygenOS v 9.0.2
**Signal version:** Signal 4.31.6

### Link to debug log

https://debuglogs.org/e9a50d9826203801bfca5716d91c6656b81a4b79cd4b09df28f391d85f6d3cdc

### Additional Info
The 2nd SIM is a new number. Apart from one test call I did myself nobody has ever used it to call me.

**Comment by emadbagheri96** [comment]
have the same problem here
its described [in the community ](https://community.signalusers.org/t/dual-sim-active-sim-indication-while-typing-sms/2331/2)too.

**Comment by kurianjacob** [comment]
### Device info
**Device:OnePlus 5T
**Android version: 9.0.0  Security Patch December 1
**Signal version: 4.31.6

Workaround
Long press send button and it will allow you to send via the correct (default) SIM.

Issue happens only for new texts and not while responding to texts which arrived within the day. Responding to long dated (few weeks) texts still has the error.

**Comment by mr-gosh** [comment]
> Workaround
> Long press send button and it will allow you to send via the correct (default) SIM.

Yes - this works but is not an Workaround for the mentioned Bug: 

> signal ignore settings of default SIM card selected to send SMS

**Comment by dayanrosenman** [comment]
Having same issue. Default messaging SIM not honored on OP 6T / OxygenOS 9.0.12.
Related: even when I disable the SIM, it is still selected for messaging (and fails to send)

**Comment by muellert** [comment]
I have the same problem on LineageOS. The problem is exacerbated by the fact that I have SIM cards from different countries in my phone, and if I don't include the country prefix in the number, eg if replying to a text or phone call, and the number was presented without the country code, my text goes to the wrong country. My only consolation is that usually, the numbers don't exist in the respective other network, and I get a delivery failure. But if I use the country prefix, not only will my text incur hefty charges, but also leak a phone number to the wrong people.

**Comment by mr-gosh** [comment]
the last signal changelog mentioned some "love for dual sim setups" - perhaps this is fixed there?

**Comment by alan-signal** [comment]
No this was not addressed.
