### ISSUE TITLE
List of recently used emojies is sluggish

### ISSUE THREAD

**Issue by WalterFaber** [signalapp/Signal-Android#8453]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
List of recently used emojies is sluggish if you scroll up or down within it.
Other emoji views / lists provide good performance

### Steps to reproduce
- Open conversation
- Start typing
- Click emojie-Button
- Go to list of recently used emojies
- Scroll down, scroll up.

**Actual result:** 
Scrolling feels sluggish or sticky... it's not smooth

**Expected result:** 
Smooth scrolling like in other (standard) emojies lists

### Device info
**Device:** Moto G4 Play
**Android version:** 7.1.2 (Lineage 14.1)
**Signal version:** 4.31.6

**Comment by AndreazLattmann** [comment]
Lazy loading? 🤔
