### ISSUE TITLE
In call, name of other person is ellipsized / cut off very early

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#8455]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a call, the name of the other person is ellipsized eve though there is enough space to the right to write out their name.

### Steps to reproduce
- Start a call with someone with a long name
- Look at their name in the call screen

**Actual result:** Their name gets ellipsized at around 2/3 of screen width. (Yes some margin to left and right is good of course, but at the moment it’s way too much space on the right.)
**Expected result:** Their name should get properly displayed. 

### Screenshots
This is a small display / display size set to large, but happens for regular size as well. In this specific case only 3 letters are missing:
![signal call name ellipsis](https://user-images.githubusercontent.com/925062/50047786-bf9b7a00-00bc-11e9-8928-5763a605ad08.png)

### Device info
**Device:** Fairphone 2
**Android version:** 8.1 (Lineage OS 15.1)
**Signal version:** 4.30.8 (latest direct .apk release)

**Comment by Sgn-32** [comment]
Is this solved for you with the new calling UI introduced in 4.60?

**Comment by jancborchardt** [comment]
Yep, fixed now. :)
