### ISSUE TITLE
Notification "Retrieving a message" is shown. No message received.

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8460]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After unlocking my phone a notification "Bericht ophalen" (Dutch for retrieving a message) is briefly shown however after opening Signal there is no new message.
Some additional information although I'm not sure if this is related. At 14:07 I did send a message to a group. One of the members changes phones yesterday. I did spoke him yesterday and he asked me to 'add him to the group' again. I did so this morning by updating the group. That worked however if I check the details for the message I send to the group I noticed there is no sealed sender icon for him anymore (I've enabled this and it was shown before he changed phones) Based on the logfile the notification started at 15:07. Perhaps there was some background messaging for the profiles that triggered this notification? Just my guess though.

### Steps to reproduce
Unable to reproduce.

**Actual result:** No new message arrived although a notification showed 'Retrieving  a message'
**Expected result:** If a notification 'Retrieving a message' is shown a new message should arrive.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/7ce9bcd07abcf09fb75e88d63a9f22871043a19ba804904876eb28a21a75266e

**Comment by greyson-signal** [comment]
Signal doesn't know what kind of message has been received until it's downloaded and decrypted. It's likely that you were simply downloading what ended up being a read receipt or delivery receipt.
