### ISSUE TITLE
Auto-update mechanism is lagging behind google play store

### ISSUE THREAD

**Issue by neunzehnachtneun** [signalapp/Signal-Android#8463]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While Signal is already updated in Googles Appstore, the update is still missing for the auto update mechanism and for the [website](https://www.signal.org/android/apk/).

### Steps to reproduce
- Visit [google](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&referrer=utm_source%3DOWS%26utm_medium%3DWeb%26utm_campaign%3DNav)
- Visit [signal website](https://signal.org/android/apk/)
- Compare the versions

**Comment by johanw666** [comment]
That is always the case. Signal uses a staged rollout, if something serious is wrong with a new release this minimizes the amount of users affected. The fastest  (if they want) are those who compile from source, then gradually the beta testers in Google Play, after that even larger percentages of the normal play users and finally the download is the last to update.

**Comment by neunzehnachtneun** [comment]
@johanw666 Thanks for answering and explaining the details. So I will wait and this issue yould be closed.
