### ISSUE TITLE
Bricked phone

### ISSUE THREAD

**Issue by vrozkovec** [signalapp/Signal-Android#8468]
Hi, it happens sometimes with Signal that when I share photo from the Photos, it gets displayed in the message but when I press send, it disappears. Just FYI today it happened again and right after pressing send my phone went dark, got completely blocked and I cannot even boot to the recovery mode. It may or may not be related, can be only a coincidence, just letting you know in case this information is of any value to you.

**Comment by greyson-signal** [comment]
Thanks for the heads up. Unfortunately, I don't think there's anything we can do in an Android application to catastrophically break your phone. Sounds like a device issue. Best of luck!
