### ISSUE TITLE
Request: Please Add Signal To F-Droid

### ISSUE THREAD

**Issue by vxcamiloxv** [signalapp/Signal-Android#8469]
This is an intentionally duplicate Issue to claim to add or allow add signal in F-Droid, thanks

Related: #7505 #7988 #127

**Comment by greyson-signal** [comment]
As noted in our issue template, Github is reserved for bugs. Please move discussions to [the forum](https://community.signalusers.org/). Thanks!

**Comment by Dev-i-l** [comment]
@greyson-signal please consider this again

**Comment by vxcamiloxv** [comment]
For an app focus in privacy not have a build in Fdroid is a contradiction, promote Play Store that have several privacy issue is an oxymoron
