### ISSUE TITLE
Is setting Signal as default SMS app reliable?

### ISSUE THREAD

**Issue by emilmuller** [signalapp/Signal-Android#8471]
I have set Signal as my default SMS app in Android. There are a couple of things that seem unclear to me.

If I open a conversation with someone who has Signal, but I have only cellular and no data connection (data is turned off), how is the message sent? Will Signal wait until it has a data connection or will it send as SMS, or will it let me choose what happens?

I am myself an Android developer, and am therefor assuming Signal is at least using FCM to wake up the phone. However, being a developer, I know from experience that FCM is not reliable in this regard. Many a times it will not wake up the phone. Sometimes you will have to enable/disable WiFi to get it going again. I've had three phones over the last few years, and this has been the case with all of them. This is also the case for Facebook Messenger -- it is equally unreliable in regard to FCM. Maybe it has to do with the phone manufacturer, but I've used three different ones.

So, if I use Signal, and I encourage my friends to switch to Signal, and if they all choose to replace their default SMS app with Signal, I can expect that every message goes over the internet, which requires my phone to wake up if I want to receive instantly, which depends on FCM. How reliable will this be? I'm currently thinking I should not replace Signal as my default SMS app.

I saw it mentioned on Wikipedia that Websockets were used. However, that would require a WakeLock which would drain the battery faster.

I think it would be a good idea to clearly separate the SMS part from the encrypted part, and not to merge them, until FCM becomes reliable for most phones.

**Comment by calebTree** [comment]
I don't see use of FCM in Signal yet. I didn't know FCM is not reliable in that way. 

> I am myself an Android developer, and am therefor assuming Signal is at least using FCM to wake up the phone. However, being a developer, I know from experience that FCM is not reliable in this regard.

I see Signal using only GCM on version 4.31.6 from what I can tell so far.

**Comment by greyson-signal** [comment]
As noted in the issue template, Github is for bugs, not for questions. Please move this to [the forum](https://community.signalusers.org/). That said, there seems to be a lot of confusion here, and for the sake of people reading this later, I'll briefly try to address some it.

>Is setting Signal as default SMS app reliable?

I've been using it as my SMS app for years, and I consider it reliable.

>If I open a conversation with someone who has Signal, but I have only cellular and no data connection (data is turned off), how is the message sent?

We will always try to send Signal messages to Signal users. We use WorkManager to try to retry message sends over 24hrs. Signal will only send SMS messages to non-Signal users, or when explicitly told to do so by long-pressing the send button.

>So, if I use Signal, and I encourage my friends to switch to Signal, and if they all choose to replace their default SMS app with Signal, I can expect that every message goes over the internet

This is incorrect. Becoming the default SMS app _does not_ mean we send SMS over the internet. Being a default SMS app on Android just means the system sends you special broadcasts when SMS are received and you handle it, and that you get access to methods to send SMS. SMS messages are still transported through your carrier and whatnot.

>I saw it mentioned on Wikipedia that Websockets were used. However, that would require a WakeLock which would drain the battery faster.

Normally we only keep the websocket  open while the app is visible. However, if the user doesn't have Google Play Services, then we have to keep a websocket open as often as possible, which does increase battery drain, but there's not many good options in this scenario.

>I know from experience that FCM is not reliable in this regard. 
Android, particularly in newer versions, has done some silly things with notifications in the name of improving battery life. I agree it's not perfect, but at the end of the day it's the only reasonable tool developers are given to do push notifications.

Please direct any other discussion to the forum, where others will be happy to answer your questions.
