### ISSUE TITLE
After update to Android 9, cannot send SMS anymore on Pocophone

### ISSUE THREAD

**Issue by praetp** [signalapp/Signal-Android#8472]
See https://www.reddit.com/r/signal/comments/a711nu/cannot_send_sms_after_system_update_on_pocophone/

**Comment by greyson-signal** [comment]
Got a debug log from one of the affected users:
https://debuglogs.org/9de8a08ee5b769ac52d6bfdd464c31a776582357f26840bfc5a0d2d59afe32ab

**Comment by greyson-signal** [comment]
The log is filled with these:

```
2018-12-19 17:52:50.990 CET I SmsSentJob: Got SMS callback: org.thoughtcrime.securesms.SendReceiveService.SENT_SMS_ACTION , 4
2018-12-19 17:52:50.992 CET W SmsSentJob: Service connectivity problem, requeuing...
```
The limit we put in to prevent more than 15 retries is working, but for whatever reason the system is telling us that the SMS didn't sent due to network issues.

**Comment by greyson-signal** [comment]
The default SMS app could be using all sorts of otherwise-private API's. I'd be interested in how other non-stock SMS apps function on the devices.

**Comment by greyson-signal** [comment]
@praetp Textra is a popular one. I'm also curious if this is still happening.
