### ISSUE TITLE
Fix in PR # 8299 got lost/reverted

### ISSUE THREAD

**Issue by doctaweeks** [signalapp/Signal-Android#8473]
PR #8299 had a fix that has now been lost. It looks like it was (accidentally?) merged in fac56be49919aa3761c4a47b5edc53ca5472c31e and closed but was then reversed (accidentally?) a few days later in 2573900c30c2250207d4c576be6c63f1b7f5b2b4.

Regardless, the fix is necessary and should be revisited.

**Comment by greyson-signal** [comment]
Got it resolved. It'll be addressed in an upcoming release (I pull translations right before cutting a new version).
