### ISSUE TITLE
Link devices manually without QR

### ISSUE THREAD

**Issue by patrikhuber** [signalapp/Signal-Android#8474]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
#5153 got auto-closed and there's no way of continuing the discussion there. People are asking for this for good reasons: Privacy issues first and foremost (doesn't Signal stand for user privacy and regards it highly?).

### Steps to reproduce
Go read #5153.

**Comment by greyson-signal** [comment]
Feature requests should be made on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). If you're looking for a related bug, see #7967.
