### ISSUE TITLE
Unable to register: cannot connect to server

### ISSUE THREAD

**Issue by mistophiles** [signalapp/Signal-Android#8475]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Cannot register with Signal to receive the SMS verification code. I was using Signal successfully until I reset the phone (by unlocking the bootloader and then relocking it). Reinstalled Signal and cannot register. The error received is "Unable to connect to the service. Please check network connection and try again". I have waited a few days between tries but have not been successfully. I have tried VPN too.
EDIT: https://textsecure-service.whispersystems.org/v1/accounts/[sms/voice]/code/+971XXXXXXXX3 -> I was able to get a call from this number and sms from this url successfully on the same phone.

### Steps to reproduce
- Install Signal messenger
- Open the app
- Enter phone number and click "Register"
- Error received: Unable to connect to the service. Please check network connection and try again

**Actual result:** "
Unable to register - "Unable to connect to the service. Please check network connection and try again"
**Expected result:** 
Receive SMS verification code from Signal.

### Screenshots

![1954892202](https://user-images.githubusercontent.com/23460445/50274326-6afa5500-0456-11e9-9cca-44cf72f2850d.png)

### Device info

**Device:** Pixel 2 XL
**Android version:** 9 build PQ1A.181105.017.A1
**Signal version:** 4.31.6 (beta tester)

### Link to debug log
https://debuglogs.org/2c69c9c035d306bdb73519397a8ab579c8256cbde8de6ee75728bbf55330078b

**Comment by leonardoporpora** [comment]
Can you try with a VPN?

**Comment by leonardoporpora** [comment]
Connecting for example to Italy with the VPN

**Comment by mistophiles** [comment]
Yes I have tried VPN to the UK but no luck. Will try Italy now.

**Comment by mistophiles** [comment]
Tried various VPN optipns with no luck. Reset the phone 4 times so far . No luck.

**Comment by mistophiles** [comment]
I tried an Indian (+91) Sim in the phone and it worked successfully. Not sure what the issue at this time.

**Comment by mistophiles** [comment]
Hmmm...have read up on every possible post regarding not being able to register with no luck. A bit frustrating that there is no way to resolve this issue. I will wait a few more days and if it does not "automagically" resolve I will abandon Signal Messenger which is  a PIA given that it took me over a year to convince my F&F to convert from WhatsApp.

**Comment by mistophiles** [comment]
I cant believe it bit literally 10 secs after making the last post, I was able to register on signal. 

- I accidently entered the wrong phone number which then took me to the sms verification screen.

- clicked on "wrong number"

- entered the right number and I was able to successfully get to the sms verification screen!

Extremely relived!
