### ISSUE TITLE
Unable to zoom with in-app camera

### ISSUE THREAD

**Issue by sgowris2** [signalapp/Signal-Android#8476]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Open a conversation
- Click on camera button next to text input field.
- Try to zoom in and out by pinching the screen with two fingers.

**Actual result:** 
Zoom does not work.
**Expected result:** 
Zooms in and out

### Device info
**Device:** OnePlus 3 A3003
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/08cb3603d4ec7d82d8f4e0ac5258b993dc38920cd6cdaf04a4a3ff955d697bd0

**Comment by greyson-signal** [comment]
We don't currently support zoom in the in-app camera. Feature requests can be discussed on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
