### ISSUE TITLE
App info settings crashes when trying to access messages notification category

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#8477]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal App info settings crash when trying to access "Messages" notification category.

### Steps to reproduce
- Open Signal App info (settings)
- App notifications
- Under Messages category, touch "Default"

**Actual result:** "Settings has stopped"
**Expected result:** Opens detailed notification settings for Messages category.

### Screenshots

![signal_message_notification_settings_stopped](https://user-images.githubusercontent.com/5124946/50294408-d850ba80-0443-11e9-95b5-b23efd82f502.png)

### Device info

**Android version:** 8.1.0
**Signal version:** 4.31.6

**Comment by ianmcderp** [comment]
FYI: cannot reproduce with the following:
- Honor 7X
- Android 8.0.0
- Signal 4.31.6

**Comment by greyson-signal** [comment]
Updated ticket: #8546
