### ISSUE TITLE
No Registration Lock PIN Dialog Has Grammar Error when 1 day is remaining 

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#8482]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The dialog telling the user that they need to wait 7 days to register a number with Signal without having the previously set Registration PIN can have a slight grammatical error concerning pluralization. 

<img width="361" alt="screen shot 2018-12-23 at 8 37 38 pm" src="https://user-images.githubusercontent.com/22125581/50389069-bb8dde80-06f2-11e9-875b-43568cf51f3b.png">

If there is just 1 day remaining, the text will read "... You have **1 days** remaining"

It seems that the string with key `RegistrationActivity_registration_of_this_phone_number_will_be_possible_without_your_registration_lock_pin_after_seven_days_have_passed` should become a quantity string, and `handleForgottenPin(long)` in `RegistrationActivity` should be refactored accordingly.

**Comment by bitmold** [comment]
oh + also on this screen the title is "Registration lock PIN" and it seems that "lock" should be capitalized since throughout the app the feature is referred to as "Registration Lock" with a capital L.

**Comment by Sgn-32** [comment]
It seems that the string `RegistrationActivity_registration_of_this_phone_number_will_be_possible_without_your_registration_lock_pin_after_seven_days_have_passed`
isn't used anymore.
