### ISSUE TITLE
Signal desktop not syncing with signal messages received on the phone

### ISSUE THREAD

**Issue by vishnuquilon** [signalapp/Signal-Android#8483]
### Bug description

In the scenario where when we receive the message with attachment and the attachment is not downloaded fully in the signal app then the subsequent messages are not getting sync up.

Other mentions of, or related to this issue:

    in #5519, the original post isn't exactly about this, but this comment describes exactly this problem.
    #6273 is about the divider between old and new messages. I haven't had a chance to check how this works (and if), but it sounds like the divider illustrates how the desktop messages are treated as new even though they've been read.
    #6126 is this exact issue.
    in #4905 the poster mentions both apps receiving messages and notifications at the same time when they're both online, but particularly this reply is about the problem when coming back from offline state, and mentions the way it should be: "Can you fix the client to download and process all of the synced states before deciding whether to show any notifications?"
    #3165 is one of the earlier mentions of this, and doesn't explicitly talk about the circumstances, but it's probably the same problem.
    in #5410 it is pointed out that the issue is a duplicate of very similar ones. But that issue was posted over 2,5 years ago and it's still relevant. Not to mention the earlier issues.
    #5741 mentions the phone buzzing while using the desktop, but it's related.
    and finally #778, from February 2014, which may be the first mention of this problem. It describes the same thing: phone's been off while conversation continued on desktop, phone gets back online, cue many, many notifications. @moxie0 self-assigned also in 2014, no other actions there happened. More happened on #3165 instead (lots of mentions mostly), although there is no asignee or milestones there. Moxie closed that issue with this commit saying that it fixes two other issues, even though it doesn't fix the real problem of a LOT of notifications coming after a longer time offline, as opposed to while using the desktop and mobile at the same time.
Android app shows countless notifications rapidly for old messages, already read in the desktop app #8445

## Actual result: 
The Android app displays and sounds tens of notifications, getting every single message as if it were a new one, only later marking it as read. If download fails it is not getting sync. 

## Expected Result:
* User should be able to download contents send via desktop using mobile app.
* If download fails on mobile, either it should be failed or success. Notification should sync with desktop. 
* The messages that have already been read on the desktop app should be synced quietly and in the background, as they are already part of the conversation. If there are any new, unread messages, they can get a notification, either first (if syncing the newest, unread messages first) or after the earlier part has been updated (if syncing in chronological order).
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Device info

**Device:** Oneplus2
**Android version:** 6.0.1
**Signal version:** 4.31.6

**Device:** Vivo V3 Max
**Android version:** 5.1.1
**Windows Desktop version:** v1.19.0
**Signal version:** 4.31.6

**Device:** Asus Zenphone Max
**Android version:** 6.0.1
**Signal version:** 4.30.8

### Link to debug log

https://debuglogs.org/a3cba724f36eb7b8a8fbc5af886575c2eba39b4bfb793bdbf4545ca036f8cfda
https://debuglogs.org/d54f8d28d6cddc77914ad2388dab7d5f8d178b0b568332f20557b16ad7097cc8
https://debuglogs.org/1e9ff36391619693ae7bc30654a95f31995ef49808777880543d9c59feb03a83
https://debuglogs.org/f6054ff17f08174bac4a118c09ed8480775c07a1fc34815cc36741c8c393f42d

**Comment by 6lancmange** [comment]
Lol why did you... copy&paste almost all of this from my post? Judging from the first paragraph, it's a different issue?
