### ISSUE TITLE
Do you have the source code written in c++ or c  to compile library

### ISSUE THREAD

**Issue by wudirui** [signalapp/Signal-Android#8485]
### Bug description 
I am very interested in your project，but i have a problem that is how the So libs works, could you sent me the source code written in c++ or c. My email：1570266831@qq.com

**Comment by piratenpanda** [comment]
https://github.com/signalapp/libsignal-protocol-c ?

**Comment by wudirui** [comment]
I want to know where you deal with voice and video streams.

**Comment by wudirui** [comment]
> I want to know where you deal with voice and video streams.



> https://github.com/signalapp/libsignal-protocol-c ?
