### ISSUE TITLE
Errors, strange interaction between Signal for Android and Desktop

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#8492]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
I had a conversation on Signal Android with a contact without issues. At the same time Signal Desktop was open (maybe still synchronizing).  After I finished the conversation on Android I had a look at Signal Desktop.
Initially some messages on Signal Desktop arrived (which I already had read and responded to on Android) correctly when I clicked on the conversation of this contact. Then the message "Safety number has changed" appeared. The next three messages of the contact (that arrived correctly on Android) stated "Error handling incoming message". My own messages of this part of the conversation appeared correctly.
When I had a look after this on Signal Android, I saw that one of my own messages (that originally was correctly delivered)  had "Send failed, tap for details" below it. Directly after that a "Your security number with ... has changed" message was inserted.

### Device info
Device  : bq Aquaris X5 Plus (Aquaris_X5_Plus)
Android : 7.1.1 (684, 2.7.0_20181002-1711)
Memory  : 82M (14.16% free, 512M max)
Memclass: 192
OS Host : bqbot3
App     : Signal 4.31.6

### Link to debug log
Android:
https://debuglogs.org/78ae38136ddbe5adb6ebff0934e4eee81ac78a561a5e560886b6668cdc5bbdc6
Desktop:
https://debuglogs.org/b4fbc62111fc0aca1c815c75ac18f9d22f8953dd948d2224d9ad35e9c0f8332a

**Comment by janvlug** [comment]
I spoke to this contact, and she switched to a new phone. It was confirmed that my Signal messages arrived on her old iPhone that was still on, probably without SIM card, because Signal was not yet installed on her new iPhone. When she saw the messages arriving on the old iPhone she installed Signal on the new iPhone.

**Comment by m93a** [comment]
Related: #10887
