### ISSUE TITLE
Toast notifications popping up when already in Signal

### ISSUE THREAD

**Issue by vertigo220** [signalapp/Signal-Android#8494]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Frequently, toast notifications for a received message will pop up when I'm already in Signal, so instead of actually being able to look at and open the message, I have a notification for it blocking my view. Once Signal is open, toasts for previously received messages shouldn't be displayed, since it's safe to assume the user can see them since they're displayed on the screen.

### Steps to reproduce
- Receive text message
- Unlock phone
- Open Signal (Not sure if it's only when opened right after unlocking phone. I think it does it even if launching Signal after the phone's been unlocked for a while)

**Actual result:** You'll be in Signal, looking at a list of conversations, including seeing new messages, yet you'll be presented with an obnoxious toast notification telling you that you have a new message, which at this point is obvious.
**Expected result:** If I'm already in Signal, I can see that there are new messages, and don't need a toast notification popping up to tell me. So at that point it shouldn't show except for messages received while in Signal, and only then for ones received for other conversations than the one you're in.

### Device info

**Device:** Moto Z Play
**Android version:** 8.0.0
**Signal version:** 4.31.6

**Comment by JasonMFry** [comment]
I want to make sure I understand the issue as clearly as possible, so here's what I think you're saying, tell me if I'm right or wrong:

1. While your phone is locked, your phone displays a notification that you have received a message.
1. You unlock your phone, dismiss the notification, and open the Signal app.
1. Your phone displays the same notification for the same message.

Is that correct?

**Comment by vertigo220** [comment]
No, I never dismiss it. The first time I see it is after I've opened signal and am looking at the conversations list/screen. I'm sure the "normal" notification is there, though in these cases I'm not looking at it, and that's not the one I'm talking about. I'm referring to the toast notification, which pops up to tell me I have a message when I can already see that since I just opened signal, and it only serves to get in the way, since I'll be about to tap the message to open it when the notification will pop up and block me. So basically, my point is toast notifications shouldn't happen for "old" messages when in signal. They should only happen when a new message is received while actively using it. Does that make sense?

Sent from my phone

**Comment by vertigo220** [comment]
Almost two years and this annoying issue, which should be easily dealt with, hasn't been fixed...

All you have to do to replicate is receive a message and open Signal and it pops up. Go into another conversation then back to the main screen and it pops up again. How is such an easily duplicated, consistent, annoying issue that should be able to be resolved with a few lines of code still around two years later?? I love the idea of Signal, but if the most basic functionality of a messaging app can't be properly done, it's not going to bring the necessary amount of users on-board to be of any real use, which just makes it pointless. I've been using it for years and have only managed to get four people to use it. Of those, two gave up on it and two only use it with me. What's the point?
