### ISSUE TITLE
[Feature Request] Automatic pruning of images of certain age

### ISSUE THREAD

**Issue by kiplingw** [signalapp/Signal-Android#8498]
As time goes on my message database continues to increase in size. I would like to preserve messages because I doubt I could ever run out of memory for compressed text, but images and other attachments over time are what contribute the most to my database backup size of 2GB.

I am aware there is a feature to automatically prune messages beyond a certain age, but it would be great if there was a feature to automatically prune attachments beyond a certain age while preserving the texts themselves.

**Comment by piratenpanda** [comment]
This is an issue tracker. Please use the community forum for feature requests. Thank you!

**Comment by kiplingw** [comment]
Thanks @piratenpanda. Done.
