### ISSUE TITLE
Cannot send messages to device which had Signal before but not after factory reset

### ISSUE THREAD

**Issue by hkcorac** [signalapp/Signal-Android#8501]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

In the past I've installed Signal on my friend's device. The app worked well.

Later my friend's device has been reset. My friend doesn't know how to install Signal. Then from Signal I cannot send messages to them anymore. Unless when I unregister my number from Signal service, then I can send unencrypted messages to my friends.

### Device info

**Device:** OnePlus
**Android version:** 6.0.0
**Signal version:** 4.31.6

I think it might be a bug. Could you please check? I'm sorry I can't provide bug reports.

Thank you,

**Comment by greyson-signal** [comment]
Sounds like you might be in the situation where your friend no longer has Signal installed, but we haven't yet detected that they're installation isn't active. I'd recommend having your friend go to our unregister page. https://signal.org/signal/unregister/

Also, in the future, you can long-press the send button to switch to sending unencrypted SMS.

**Comment by hkcorac** [comment]
@greyson-signal 

Thank you very much for improvement of the Send button.
