### ISSUE TITLE
User verification over phone number insecure (35C3, talk #9383)

### ISSUE THREAD

**Issue by TheRealCuran** [signalapp/Signal-Android#8508]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

(Note: I do consider this a demonstrated bug, not a feature request, which is why I haven't checked the last box and reported it here.)

Signal uses the phone number to verify/identify a user. As https://media.ccc.de/v/35c3-9383-compromising_online_accounts_by_cracking_voicemail_systems shows, this is an insecure verification process, because an attacker could register for any phone number.

Apart from the privacy concerns of having to disclose the phone number to communication partners, this is now also a demonstrated security risk. Please provide an option to register for Signal with an anonymous pair of user name and password plus (optional or at least one-time "device verification") 2FA token (TOTP).
For existing users there needs to be an option to remove the phone number from the "account" and replace it with the chosen user name. Even better if all users are upgrade to that scheme.

Signal is mentioned at 24:38 in the video specifically.

**Comment by greyson-signal** [comment]
Hi, I consider this more of a discussion, which should be moved to the [forum](https://community.signalusers.org/). Thanks!
