### ISSUE TITLE
Cannot see every conversations in Android's notification channels

### ISSUE THREAD

**Issue by nagromc** [signalapp/Signal-Android#8509]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android's notification channels doesn't show as many conversations as in Signal. That prevents me from customizing notifications by conversation (e.g. muting or enable vibrations).

Not sure if the system limits the number of channels though.

### Steps to reproduce
- In Signal application, list and count every conversations you have
- Compare the list with the one in Android's notification channels (from Android 8, API 26):
    - Go in _Settings_ app > _Apps & notifications_ > _Signal_ > _App notifications_
    - In _Messages_ section, retrieve every customizable conversations

**Expected result:** In Android's notification channels, I was expecting to see **every** conversations seen in the Signal app, that is Signal one-to-one conversations, Signal group conversations, one-to-one SMS conversations, etc.

I've got something like thirty conversation in Signal:
- at least eight of them are one-to-one conversations
- at least four of them are group conversations
- the rest being SMS.

**Actual result:** Only four entries are shown:
- three conversations:
    - two SMS conversations
    - one Signal group conversation
- and _Default_ entry

**Additional information**

The weird thing is conversations shown in Android's notification channels are pretty old conversations:
1. First entry in Android's notification channel is conversation A in Signal:
    - First message: 3rd Nov 2017
    - Last message: 4th Jun 2018
2. Second entry in Android's notification channel is conversation B in Signal:
    - First message: 8th Sept 2017
    - Last message: 27th Feb 2018
3. Third entry in Android's notification channel is conversation C in Signal:
    - First message: before 23rd Aug 2017
    - Last message: 27th Nov 2018

I've got conversations much more recent, and other much more older than that.

Other thing: at the very bottom of Android's notification channel, the following message is displayed:

> 7 categories deleted

I've tried to backup the conversations, wipe app data, and import the backup. Same exact result, with the same three conversations I was talking to in _The weird thing_ part.

### Screenshots
In red: two SMS conversations
In green: one Signal group conversation

![screenshot_20190105-181315](https://user-images.githubusercontent.com/752443/50727563-f7766a00-111c-11e9-90ce-96a91d70e28e.png)
![screenshot_20190105-181321](https://user-images.githubusercontent.com/752443/50727594-53d98980-111d-11e9-82cc-1c8463080d87.png)

### Device info

**Device:** LGE H971 (a.k.a. Google Nexus 5X)
**Android version:** 8.1.0
**Signal version:** 4.31.6

### Link to debug log

Please confirm how to proceed as it is not related to an event.

**Comment by greyson-signal** [comment]
We only create notification channels for conversations with custom notifications enabled. To enable custom notifications for a conversation, go to the conversation -> three-dot menu -> conversation settings -> Custom notifications toggle. Thanks!
