### ISSUE TITLE
Static font size for quoted messaged (no adaptation to the font size setting)

### ISSUE THREAD

**Issue by codedust** [signalapp/Signal-Android#8512]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Adapting the font size in the settings does not effect quoted messages. When quoting a message, the font size of the quoted message always remains the same (see screenshots).

### Steps to reproduce
- set the "message font size" to anything other than "Normal" in "Chats and media" -> "Chats" -> "Message font size".
- Quote a message.

**Actual result:** The font size of the quoted messages is "Normal"
**Expected result:** The font size of the quoted messages should adapt to the chosen option in the settings.

### Screenshots
Font size setting:
![settings](https://user-images.githubusercontent.com/7175914/50780562-8ca36b00-12a3-11e9-9901-7cbcb03a8073.JPG)

Correct font size when font size is set to "Normal":
![font-size-normal](https://user-images.githubusercontent.com/7175914/50780317-e9eaec80-12a2-11e9-9e50-3e80f5024018.JPG)
Font size does not adapt when font size is set to "Small":
![font-size-small](https://user-images.githubusercontent.com/7175914/50780322-ec4d4680-12a2-11e9-8c39-ba203d9c68f1.JPG)
Font size does not adapt when font size is set to "Extra large":
![font-size-large](https://user-images.githubusercontent.com/7175914/50780334-ee170a00-12a2-11e9-948e-9191c5047d4a.JPG)

### Device info

**Device:** Fairphone 2
**Android version:** 7.1.2
**Signal version:** 4.31.6

### Link to debug log
n/a

**Comment by nst0022** [comment]
I second your report and like to extend: If a user chooses a larger font, s/he has a reason for that, so the larger font should be applied to the whole user interface, not just the message text.

**Comment by ss44** [comment]
Was this ever added?

**Comment by Otiel** [comment]
No, the pull request hasn't been merged

**Comment by greyson-signal** [comment]
This should be fixed now.

**Comment by Otiel** [comment]
👍 This is fixed for me. Thanks!
