### ISSUE TITLE
Outlook contacts not showing up when sending a text

### ISSUE THREAD

**Issue by skjarl** [signalapp/Signal-Android#8514]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my HTC U11 phone, when I create a new message, none of my contacts from Outlook are showing up.  The contacts are synced to both Google Contacts and the People app.  Sync is definitely turned on in Outlook.  When I send a text through Outlook to one of the missing contacts, it correctly opens Signal and populates the number.  Signal is able to resolve that number into the proper name at this point.  If I receive a text from someone whose contact doesn't show up, Signal correctly identifies them.  This worked just fine in the past.  Reinstallation of Signal did not resolve the issue.

### Steps to reproduce
- Open Signal
- Start a new message
- Type a name in the filter

**Actual result:** The name fails to show up.
**Expected result:** The name will show up and let me send a text.

### Screenshots
![image](https://user-images.githubusercontent.com/10904006/50807488-94293b00-12c8-11e9-86cf-a112ae217010.png)

### Device info
**Device:** HTC U11
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/38506b1b45294dfc534df43fc7996ad7606bf34e28cff779b44b02d1f9c72fdc

**Comment by m-wo** [comment]
Same on iOS

**Comment by skjarl** [comment]
Wiping my accounts from the device, re-installing Outlook, and forcing a re-sync of contacts resolved the problem.
