### ISSUE TITLE
Signal suddenly showing "Retrieving a message" notification and eating LOTS of battery

### ISSUE THREAD

**Issue by pjv** [signalapp/Signal-Android#8516]
Starting this morning, Signal (android) is showing me a persistent notification that says "Retrieving a message". Coincident with this notification, Signal is also using a huge amount of battery.

I have read this reddit post: https://www.reddit.com/r/signal/comments/9uxybo/strange_notification/

And this closed issue here: #8460

Neither of those tell me how to figure out what's going on, nor what to do about this situation. I could live with the notification (though it's annoying), but the battery drain is not workable.

Nothing that I am aware of has changed on my device (no recent Signal updates nor system updates) and nothing that I know of has changed in my network environment - I am sitting at home and the device is connected to my home wifi (same as every day).

Is there any additional information about what is likely to be happening on the device when Signal throws that notification so I can try to debug this and stop my battery from dying in a couple hours?

using adb shell to dump cpu usage gives me this:

```
payton_sprout:/ $ /system/bin/dumpsys cpuinfo
Load: 8.2 / 8.6 / 8.28
CPU usage from 129404ms to 117795ms ago (2019-01-08 11:58:25.085 to 2019-01-08 11:58:36.695) with 99% awake:
27% TOTAL: 15% user + 7.5% kernel + 2.7% iowait + 0.7% irq + 0.6% softirq
  103% 11219/org.thoughtcrime.securesms: 77% user + 26% kernel / faults: 22921 minor
```

What is Signal doing????

**Comment by greyson-signal** [comment]
Can you post a debug log? (Settings > Advance > Submit debug log -- post link here)

As a stopgap solution, you can always force-stop Signal via the system App Info settings screen for the app. This will stop the foreground notification. However, please capture a debug log before you force-stop.

**Comment by pjv** [comment]
@greyson-signal i just clicked the submit debug log button and it created a pretty huge thing that i don't have anywhere near the time to go through to see whether i am ok with posting it publicly. what is captured in that debug log?

**Comment by Dyras** [comment]
@pjv Nothing that could identify you in any way. The contents of your messages are **not** included.

**Comment by pjv** [comment]
@Dyras it has my wifi SSID in there. I don't trust there is not other identifying info and it's too long to read through it all.

**Comment by Dyras** [comment]
I had no clue the WiFi SSID was in there, I just checked and can confirm it. :s

**Comment by pjv** [comment]
Signal is probably the single most important app on my phone and I can't keep it running with it pegging the CPU > 100% continuously (which it still is).

I just took a backup of my chats and data and planning to uninstall / reinstall. Anyone have any other suggestions before I have to deal with notifying everyone on my contact list that, yes, I did reinstall Signal, and no, nobody is MITMing us...

**Comment by greyson-signal** [comment]
Looks like WorkManager (a Google-provided library we use) is logging the SSID in it's debug logs. I'll suppress it.

If you don't feel comfortable posting the debug log, you can send the link to one of my Signal test numbers: +1 (610) 549-1426

**Comment by pjv** [comment]
fwiw, i just force-stopped signal on the phone and started signal desktop on a mac where for a couple contacts it told me 400+ and 3500+ "error: unhandled message".

**Comment by pjv** [comment]
@greyson-signal The desktop app crashed when I tried to pull that log.

I understand you need the log, but I'm not ok with pressing the submit button and sending info from my phone that I have no idea the contents of to an endpoint that I have no control over.

I guess I'll be reinstalling.

**Comment by greyson-signal** [comment]
No worries, let me know if it happens again. This ticket has become inactionable though, so I'm just gonna close it.

I saw you were using ADB earlier, so if you ever want to go through the logs yourself and hand-pick anything that looks suspicious, you can post that here and then I can re-open this.

**Comment by pjv** [comment]
...or maybe not.

i turned signal android back on again and reset the secure session on the two conversations / contacts that were freaking out in the desktop app and that seems to have stopped the CPU usage.

until i reset those sessions, i was getting repeated "Error handling incoming message" messages in both of those chats at a rate of maybe 3-4 per second.

fingers crossed that might have fixed it.

**Comment by pjv** [comment]
I'm ok with sending it to you privately, but i don't know how to access it anymore. I assumed that if i clicked "submit" it was going to be uploaded somewhere so i clicked "don't submit". If i can access it now from the adb shell somehow, let me know and i will.

one of the contacts on the other side of the problem was also receiving endless error messages in his desktop signal.

**Comment by greyson-signal** [comment]
If you didn't uninstall/reinstall, you can still get the debug logs the same way. Submitting will upload to debuglogs.org. Alternatively you can do `adb logcat` from your computer and post snippets from there, but that's every app's logs, so that stuff you really do need to comb through.

I was talking to my co-worker and they suggested that you update your desktop version. This might be related to your desktop instance not supporting [sealed sender](https://signal.org/blog/sealed-sender/).

**Comment by pjv** [comment]
ok, here you go. Same thing happened again this morning - is happening right now, though not as severe. At the moment the CPU usage for signal on my phone is varying from 25% - 70%, but it's consistently sitting on top of top.

the same contact that had trouble with me last time this happened again also simultaneously also saw signal freaking out on them, though they are not technically inclined enough that i can get good data from them on what "freaking out" means exactly. I reset the secure session with them and that calmed things down, but then subsequent messages with them coincided with signal again ramping up CPU usage. I didn't reset for the sake of collecting some logs which i am appending below. Hope this helps you figure out what is happening... and if not and if there is something else i can give you, let me know and if i haven't reset things by then, i'll try to get it to you.

both i and my contact have the latest versions of signal desktop (1.19.0) and signal android (4.31.8).

logs: 
[adb logcat |grep thought.txt](https://github.com/signalapp/Signal-Android/files/2759475/adb.logcat.grep.thought.txt)
