### ISSUE TITLE
Messages not sent via mobile data

### ISSUE THREAD

**Issue by akinora** [signalapp/Signal-Android#8520]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal messages are neither sent nor received when connected via mobile data. As soon as WIFI is turned on messages are received/sent. This happens constantly with 1 specific contact in my list, for other contacts enabling and disabling WIFI solves the issue from time to time. I already did reinstall the app. 

Possibly relates to #8365 

### Steps to reproduce
- turn WIFI off
- send message
- message status stays unsent (with loading circle)
- turn WIFI on 
- message is being delivered

**Actual result:** Signal messages are not being sent/received
**Expected result:** Signal messages should be sent/received

### Device info

**Device:** Samsung Galaxy S6
**Android version:** 7.0
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/cfea889a9ac5a179cfad92665d9eaa876d004c753dff3f452231508df85f6f58
Log was generated immediately after the reproduction of the bug

**Comment by greyson-signal** [comment]
Merging similar issues together: #8602
