### ISSUE TITLE
Audio call on speaker triggers proximity sensor

### ISSUE THREAD

**Issue by badgooner** [signalapp/Signal-Android#8522]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio call on speaker triggers proximity sensor. If I move my hand near the proximity sensor, the screen turns off.

### Steps to reproduce
- make an audio call
- once the other person answers, turn on speaker mode (hands free mode)
- move your hand near the proximity sensor

**Actual result:** Screen turns off
**Expected result:** Screen should not turn off. It should only turn off when speaker mode is off and I put my hand near the proximity sensor (which works as expected) but not while speaker mode is on.

### Device info
**Device:** Samsung Galaxy S9+
**Android version:** 8.0 (Dec 2018 security patch)
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/388318e3f7f628a56f94e2b9d39d43c23ce08af9c39da734ef39d5120a5edfe5

**Comment by UserX404** [comment]
I noticed this behavior is only activ if the own camera is switched off.

**Comment by badgooner** [comment]
Is the above comment for requestor or resolver?
