### ISSUE TITLE
Contact picture doesn't get refreshed when it's changed

### ISSUE THREAD

**Issue by eauchat** [signalapp/Signal-Android#8523]
If I have a contact in my address book, and then add this contact in signal, everything is good, the contact avatar/image displays fine.
But let's say I add a picture for this contact after connecting with signal, then the picture doesn't appear in signal.

It would be cool that the app detects if contact pictures are modified in the address book.

And is there a way at the moment to refresh this manually?

**Comment by zznidar** [comment]
In my experiences, Signal refreshes contacts only every now and then. To refresh ("sync") them manually, open Signal, press the "New" button (bottom-right corner), then swipe up on the contact list to refresh it. This should update Signal's address book.

**Comment by 2-4601** [comment]
Issue seems to be solved.

**Comment by eauchat** [comment]
Well @zznidar suggested a way to refresh contact pictures, so it shows it can be manually achieved yes.
However I wouldn't say the issue is solved, shouldn't the app refresh contacts whenever they're changed, or maybe at least check for changes automatically on a regular basis. (Which is not the case at the moment. I assume the list is never updated automatically because I had some contacts pictures that weren't updated for months until I updated manually with the above suggestion.)
