### ISSUE TITLE
Can't run the app in Android Studio 

### ISSUE THREAD

**Issue by Ligandfas** [signalapp/Signal-Android#8524]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am getting an error while trying to run signal in Android Studio

### Steps to reproduce
-Clone the repository from github into Android Studio
-Run the project

Android resource compilation failed
Output:  L:\workSpace\signal\build\intermediates\incremental\mergePlayDebugResources\merged.dir\values-te\values-te.xml:901: error: unescaped apostrophe in string
"à°¸à°¾à°¦à°¾ à°¬à±�à°¯à°¾à°•à°ªà±� à°«à±†à±–à°²à±� à°¦à°¿à°—à±�à°®à°¤à°¿. 'à°Žà°¸à±�à°Žà°‚à°Žà°¸à±� à°¬à±�à°¯à°¾à°•à°ªà±� & amp à°…à°¨à±�à°•à±‚à°²à°‚à°—à°¾; à°ªà±�à°¨à°°à±�à°¦à±�à°§à°°à°¿à°‚à°šà±�. '".

### Screenshots

![capture](https://user-images.githubusercontent.com/18163788/51070381-8ebd4f00-1640-11e9-806d-f2f28d454512.PNG)

### Device info

**Device:** Google pixel2
**Android version:** 6.0.0
**Signal version:** Bump version to 4.31.6

**Comment by johanw666** [comment]
That's not a runtime error but a compile time error. Odd, I built 4.31.8 this morning without any issues.

**Comment by greyson-signal** [comment]
A translation was misformatted. It's been fixed and will be pushed the next time we update translations.

It's funny I never catch these. I make clean builds all the time, and I'm always able to compile.

**Comment by Ligandfas** [comment]
thanks , yeah I am error magnet :p
