### ISSUE TITLE
profile image not sync

### ISSUE THREAD

**Issue by marcorighi** [signalapp/Signal-Android#8527]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The profile image is not sync between android app and debian client.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

change the profile image in the app client

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** ASUS_X00TD
**Android version:** 8.1
**Signal version:** 4.31.8

**Comment by 2-4601** [comment]
I believe this is the same issue as https://github.com/signalapp/Signal-Desktop/issues/2846.
