### ISSUE TITLE
Multiple image sending don't work

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8531]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending multiple imagesit keep in the "sending" state.

### Steps to reproduce
- Open a chat and select + -> Gallery
- Select multiple images
- Add a comment
- Try to send

**Actual result:** Signal remain in the sending state and files are never delivered. 
**Expected result:** Signal send images.

### Screenshots

Not needed

### Device info

**Device:**  Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.32.0

### Link to debug log

https://debuglogs.org/07b859cd02f9386e12f4525adfec6b967a6872dd96fdeb312121585278f50d1c

**Comment by Edu4rdSHL** [comment]
Working with the latest release (about 1 hour ago)

**Comment by jost-s** [comment]
I have a similar problem. When in a chat I select multiple images to send, get the image slider with all selected images and the option to enter a comment, hit send, the screen is white for a moment and then the chat reappears without the images being sent, as it was before.

### Device info:
**Device:** Huawei P8
**Android version:** 6.0
**Signal version:** 4.43.8

Link to debug log:
https://debuglogs.org/b2bfcea58ebe8753e19c10e57344949026a8e5e062ce521f2af7974a81697482
