### ISSUE TITLE
Camera scribbles move around when rotating phone

### ISSUE THREAD

**Issue by subraizada3** [signalapp/Signal-Android#8533]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After taking a photo (either with the quick photo button inside the input box, or by pressing the 'add attachments' button and selecting the Camera option to use the system camera), scribbles/highlighter can be drawn onto the photo. The position of the drawn scribble (or highlight) is dependent upon the rotation of the device, and the scribble move when the device is rotated.

This is not the case with stickers/smileys or text that is placed onto the photo - those things stay when the phone is rotated.

### Steps to reproduce
- Start sending a picture with Signal
- In the Signal photo editor, draw a scribble or use the highlighter tool
- Rotate the phone (auto-rotate must be turned on, see #8515)
- The scribble or highlight will move on the photo

**Actual result:** The scribble moves
**Expected result:** It should not

## Example 1
![1](https://user-images.githubusercontent.com/3249268/51215999-d7029880-18f0-11e9-8348-9f12fc7d76b8.jpg)

### Device info
**Device:** Galaxy S9
**Android version:** 8.0.0
**Signal version:** 4.31.7

## Details:
The scribble stays in the same position in screen space. However, the photo is resized in screen space when the phone is rotated. E.g. a 1920x1440 photo could also take up that many pixels on the screen when the phone is horizontal, but when the phone is vertical the 1920x1440 photo will only take up 1440x1080 pixels on the screen. The scribble position seems to be fixed to the screen pixels, not image pixels:

![5](https://user-images.githubusercontent.com/3249268/51216099-3365b800-18f1-11e9-952b-2c513384786c.png)

In the above png, the image is 1920x1440. On the left side, a rectangle scribble was drawn with its top left corner at (105, 140) on the image and the screen. When rotated to vertical, the rectangle should stick to (105, 140) in the image, and be at a smaller (x, y) coordinate on the screen. But the opposite happens - the rectangle sticks to (105, 140) on the screen and ends up being at a different place in the image.

Example of the smileys and text decorations behaving correctly (they stick to the bottom left corner of the monitor in the photo):
![all](https://user-images.githubusercontent.com/3249268/51216145-54c6a400-18f1-11e9-855f-fb9c8ca27d0c.jpg)

And finally, some more examples of the scribbles moving:
![2](https://user-images.githubusercontent.com/3249268/51216164-6740dd80-18f1-11e9-9584-0852c2344628.jpg)
![3](https://user-images.githubusercontent.com/3249268/51216167-69a33780-18f1-11e9-879e-649057b444a2.jpg)
![4](https://user-images.githubusercontent.com/3249268/51216171-6c9e2800-18f1-11e9-85fc-139defbc776e.jpg)

**Comment by greyson-signal** [comment]
Thank you for the detailed bug report! This was fixed in 4.32.x, which is currently in beta.
