### ISSUE TITLE
Notifications during calls

### ISSUE THREAD

**Issue by mkevins** [signalapp/Signal-Android#8537]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

I found a few duplicates of this issue, with #4318 being the latest (I think), which was closed during the great autoclose purge of 2018 (#7598). I'm unsure whether this issue was resolved elsewhere, but I have not found a solution. My current workaround is to manually turn on "do not disturb" mode every time I'm in a Signal call. If I forget, I am usually abruptly reminded by an unpleasant vibration in my ear. :dizzy_face:

----------------------------------------

### Bug description
A notification will cause the phone to vibrate during a call.

### Steps to reproduce
- Be in a call (with the phone against your face)
- Receive an sms message (or other notification)
- Become startled by the violent vibration occurring on your face and in your ear

**Actual result:** Phone vibrates on your face
**Expected result:** Phone does not vibrate on your face (maybe uses another mechanism to notify if necessary, such as a soft tone instead?)

### Device info

**Device:** Motorola Nexus 6
**Android version:** 8.1.0
**Signal version:** 4.31.6

**Comment by error401de** [comment]
I had this now multiple times, it is **incredibly** annoying.

**Comment by smopucilowski** [comment]
This is a _very_ intrusive issue; confirming.

**Comment by error401de** [comment]
@alan-signal @greyson-signal Any chance you could have a look at this? The issue is > 2 years old, very intrusive and (to me) almost daily occurring...
Thanks!

**Comment by greyson-signal** [comment]
I don't think it's possible to handle all notifications this way. If you get a notification in some other app and your phone decides to vibrate, that's just going to happen. I imagine the best thing we could do is disable vibration for our own notifications.

**Comment by error401de** [comment]
Thanks for the reply @greyson-signal !
True. I just tested it with another app and it shows the same behaviour. Just never recognised it as I don't use any other app so frequently like I use signal...

This topic is connected and it would help a lot: https://github.com/signalapp/Signal-Android/issues/10831
Most intrusive are the notifications from groups.

Thanks for considering!
