### ISSUE TITLE
When a text is sent through Google Assistant the sent message is not shown in Signal/Updated into signal's SMS database.

### ISSUE THREAD

**Issue by snyfear** [signalapp/Signal-Android#8538]
When a text is sent through Google Assistant the sent message is not shown in Signal/Updated into signal's SMS database.
Steps to reproduce

    send text through Google Assitant
    open signal
    read messages
    notice sent text isn't there.

Actual result: Sent text not in text log
Expected result: Sent text should be shown in signal message logs
Device info

Device: Xiaomi Redmi Note 5
Android version: 8.1.0
Signal : 4.32.5

**Comment by johanw666** [comment]
That is to be expected, if Signal is the defaukt sms program it does not store messages in the system sms database because it is not protected.

**Comment by johanw666** [comment]
Sure, if you get the devolopers interested in the idea. Technically there is no problem with that.

**Comment by 2-4601** [comment]
Previous issues #8238, #8228, #8158, #7769, #7634, #7626, #5803, #4037, #218 which explain why this has not been implemented.

**Comment by tallison63** [comment]
What happens when you keep opening the same issue over and over?  This bug goes back years and it's always just closed despite it being a continued request.

**Comment by wizardofid** [comment]
I'm not sure what happens. Maybe several hundred people who get regularly a notification email for an useless issue report will think you are an ignorant moron?
Better try annoying Google-devs. They should implement an API that reliably notifies Signal or other apps of a new SMS.

**Comment by tallison63** [comment]
And this is how you get people to stop trying to give feedback but just
move on, because we are morons.

**Comment by greyson-signal** [comment]
Please keep discussion on Github civil. Name-calling isn't civil.

@tallison63 Here's the direct link to previous thoughts on the matter. https://github.com/signalapp/Signal-Android/issues/7627#issuecomment-378568313

At this point it's up to Google as to whether or not they want to provide a reliable way for us to do this.

**Comment by tallison63** [comment]
To that end I've attempted to contact Google.
It's the only option I see, bringing it up to them through enough customers
to maybe get their attention.
