### ISSUE TITLE
Pixel 3 to iPhone audio message plays at 2x

### ISSUE THREAD

**Issue by jshayden** [signalapp/Signal-Android#8543]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio messages sent from a Pixel 3 to an iPhone play at double speed (but without increased pitch). Messages to other Android phones are fine. Bug does not exist on Pixels 2 running the same OS version (9).

Playback of your own message on your Pixel 3 is normal; just not on recipient's device.

### Steps to reproduce
- Push and hold audio record button
- Release to finish and send message

**Actual result:** iPhone recipient hears the audio message at 2x (but seemingly pitch adjusted).
**Expected result:** Recipient should hear the audio message as recorded.

### Device info

**Device:** Google Pixel 3
**Android version:** 9
**Signal version:** 4.32.7

### Link to debug log

https://debuglogs.org/f4179a323bb2c24a776bbf81b8142c58ea9351ff13c5c3e9854fb2ba481e7b3d

**Comment by jshayden** [comment]
Other users reporting:
https://www.reddit.com/r/signal/comments/ab22ti/android_audio_message_bug/

**Comment by akalaj** [comment]
Hey. Love the app. Just confirming that this issue is still happening with Pixel 3 -> iPhone.

**Comment by jshayden** [comment]
> Hey. Love the app. Just confirming that this issue is still happening with Pixel 3 -> iPhone.

Yes, unfortunately.

**Comment by nick-atmosphereiot** [comment]
Still happening. Any movement on this?

**Comment by glomeg132** [comment]
I have the exact same issue.

**Comment by fredmbarros** [comment]
Also experiencing the exact same issue

**Comment by nutts0** [comment]
It is not usable at the moment 

Here is a debug log from the iPhone 7. The funny thing is if you send back the voice message to the pixel from the iPhone. It plays normal

https://debuglogs.org/5526e0c3fbc1190dcbc094f4a71ba2b2bf4c5bc68b3c93dbbbb760eba5ccfd86.zip

**Comment by nutts0** [comment]
Now I'm completely confused. I tried talking half the speed so my friend with the iPhone could here it as normal message. But the message arrives now as the original record. And I sound like a complete Idiot

**Comment by tixetsal** [comment]
I have the same issue. Pixel 3 to iPhone 8.

**Comment by rtsio** [comment]
:+1: experiencing this on Pixel 3a, friends on iPhone report all my voice messages play at comically increased speed

**Comment by Mlrt55** [comment]
It's been over 2 years... 

Same issue now as well with a Galaxy S21(exynos) since Android 12 and Signal 5.26.11 to an iOS device and the message is playing at 2x speed on iOS.

**Comment by stephenvsawyer** [comment]
Still happening just started happening between Galaxy 21 and iPhone 12 Pro Max after the Android 12 update installed. Please fix this.

**Comment by om-hb** [comment]
Same here, just switched to a Samsung Galaxy S21 (Exynos) and now contacts that are using iPhones are hearing my voice messages too fast. On my phone, messages sound correct, but the displayed duration is wrong. I'm using Singal 5.28.5.

**Comment by timmelot** [comment]
I can also confirm this behaviour on my device (S21).

**Comment by macomonaco** [comment]
I have the same issue: 

Samsung device on the one side. iPhone was the latest iOS 15.2 and latest signal version on the other side. Play back of voice messages on the iPhone is in double speed since few weeks. 

I’m not aware of any setting or work around to prevent this issue.

**Comment by greyson-signal** [comment]
Seems to all be manufacturer-specific problems. For instance, it used to be the case that Pixel 3 phones had this problem, but it no longer occurs, presumably fixed through Android OS updates. 

This new round of problems with Samsung phones started to happen after a Samsung OS update.

Regardless, we're in the process of trying to test some changes to address this. Unfortunately it's actually not easy for us to get a hold of the specific device with the specific software update, because Samsung is doing gradual rollouts of the update and it's not available everywhere. We'll see!
