### ISSUE TITLE
Unable to reply to messages through Android Auto

### ISSUE THREAD

**Issue by rubin110** [signalapp/Signal-Android#8545]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

Note: I'm sure not interested in arguing over the merits of using Signal through various Google services.

### Bug description
When I attempt to reply to a Signal message through Android Auto with my voice, Android Assistant responds with "Huh, looks like there's a problem." and the message doesn't get sent. I can reproduce this on both Android Auto stand alone (running the interface on your own phone), and with a head unit in a car.

### Steps to reproduce
- Install Signal, register, etc
- Install Android Auto, open it for the first time, agree to the TOS, etc
- Have a friend send you a message through Signal
- Tap that message listed in Android Auto's home screen
- After listening to the message, tell Android Assistant yes to replying to the message
- State the message
- Say send it when Android Assistant restates your message
- Observe

**Actual result:** Android Assistant responds with "Huh, looks like there's a problem." and the message doesn't get sent.
**Expected result:** Message gets sent.

Previously this worked flawlessly and was a welcomed featured. 

### Device info

**Device:** Pixel 3 XL
**Android version:** 9.0, Jan 2019 security patch
**Signal version:** 4.32.7
**Android Auto version:** 3.9.585064-release

### Link to debug log
I've got a logcat, however would like to email it to a dev instead of posting it.

**Comment by greyson-signal** [comment]
Hi @rubin110, you can email the log(s) to greyson@signal.org. Thanks!

**Comment by rubin110** [comment]
@greyson-signal: Emailed!

The log was taken in stand-alone mode for Android Auto, as I didn't want to drag my laptop out to the car. Also I've snipped the log to only when I start playback of the message through Android Auto and when it responds back with "Huh, looks like there's a problem."

Thanks! And let me know if you want anymore testing!

**Comment by jamesonp** [comment]
I can confirm same issue.

**Comment by rubin110** [comment]
Today I noticed that on the "Observe" step using my original repro steps, Android Auto replies back with a generic "I don't understand" response. This is a deviation from the "Huh, looks like there's a problem" response.

**Comment by justlurking** [comment]
Any updates on this issue? I'm experiencing something very similar. For me, replying to a Signal message via Android Auto's voice dictation appears to send successfully with a confirmation message from AA, but nothing is actually sent. In other words:

- AA dictates a Signal message to me and asks if I want to reply.
- I say "yes" and AA prompts me to dictate the reply. 
- I dictate the message and it reads it back to me, confirming that it heard me. AA asks if I want to Send.
- I say "yes" and AA responds, "OK, sent".

Result: No reply is sent.

I'm happy to take and submit logs, but I'm not happy to do so while I'm driving. How soon after the issue occurs does a log need to be taken? If it's taken a half hour (or even an hour or two) later, is that still useful? (If necessary maybe I can try and recreate the issue while parked.)
