### ISSUE TITLE
Changing group avatar shows default group avatar on group members device

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8547]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For a group that had a default group avatar I've changed the group avatar. This seems to work fine on my device. On the device of a group member though a message arrived that the group was changed however the changed group avatar was not shown. 
As a test I've changed the group avatar of a different group that already had a custom avatar. That also seems to work fine on my device however on a group member device the previous custom avatar was replaced with the default group avatar. When I went to the 'edit group' menu on the receiving device it still showed the previous avatar.

### Steps to reproduce
- Change group avatar
- Check group avatar on group member device

**Actual result:** Changing group avatar only changes group avatar on local device and changes the group avatar to the default group avatar on group members devices.
**Expected result:** Group avatar should change for all group members.

### Device info

**Device:** Samsung S6
**Android version:** 6.0.1
**Signal version:** 4.32.7

### Link to debug log
Log from my device (device that changes the group avatar)
https://debuglogs.org/a3d22ef0f46d7363fdc719d6d666cf1c9159eb92200905eac5eb714b3a892827
Log from group members device
https://debuglogs.org/b3ffc92e74d22c7b4886fb2543490a62ab6348edd3b2fb6ec7d9482788aca5bb

**Comment by greyson-signal** [comment]
Thank you for catching this! An unfortunate bug that was introduced when I changed the attachment upload flow. This will be resolved in 4.32.8. Thanks!
