### ISSUE TITLE
Signal crashes when listening to voice messages the first time

### ISSUE THREAD

**Issue by AnBusse** [signalapp/Signal-Android#8548]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to play newly received audio messages, the playback of the message stops and the device's screen switches off, needing the user to reactivate the screen manually and to tap the Play button again to re-start playing the message. This can happen several times in a row when playing a message for the first time. I had this issue on 2 different devices with different Android versions, see specs below. This only happens when a new message is played, if you listen to messages a second time, the issue does not occur.

### Steps to reproduce
- receive a new voice message in a Signal chat
- tap the Play button to play the message

**Actual result:**
The audio playback stops after a few seconds and the device's screen turns black.
**Expected result:** I can play received audio messages without having to manually turn the screen back on and tapping Play to resume the playback of the recording.

### Device info

**Device:** Nokia 7.1
**Android version:** 9
**Signal version:** 4.32.7

**Device:** Motorola Moto G3
**Android version:** 6.0.1
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/fc43acb9340934f27f30510426aa52629e67c2ff413fb0e1397f64cbee1c4bc9 The bug happened at ~15.24 system log time on the Nokia phone provided above.

**Comment by haffenloher** [comment]
There's no crash in that log. From your description, it sounds like your phone's proximity sensor (falsely) detects that you put your phone to your ear, so Signal turns off your screen and switches playback to the earpiece. Did you maybe cover the proximity sensor with your finger or something?

**Comment by AnBusse** [comment]
Thanks for the quick reply, it's appreciated!
I never thought of an issue with the proximity sensor, as I usually have my phone laying down on a surface when listening to messages. However, I did do a test where I deliberately covered the sensor, and it reproduced the issue. I will close the issue. Keep up the good work!
