### ISSUE TITLE
messages take too long before get send

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8552]
- [x]I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
From when I click send button to when the message get sent takes like 2/3 seconds and its not my connection problem cause I have 100 Mb/s. In fact if I receive a video on Signal the download is very fast...

### Steps to reproduce
Idk
**Actual result:** message takes too long before getting sent)
**Expected result:** message should take very short to get sent

### Device info

**Device:** pixel 2 xl
**Android version:** 9.0
**Signal version:** latest

### Link to debug log

https://debuglogs.org/17f25a93c893d2326f6f33b58e4a740253aaf968123c5919a974a2030863329f

**Comment by greyson-signal** [comment]
Looking at the log, jobs begin executing very quickly (<50ms), but the actual delivery of the message is taking around 500-800ms. On my device, sending usually takes 200-300ms. 

However, it's hard to say what the ideal speeds are for you, giving every phone and network configuration are different. Do you have any numbers to compare it to? i.e. did previous versions send faster, or do you get different speeds on different networks? 

The fact that you have 100 Mb/s down isn't necessarily the limiting factor here. Messages are small. You're likely not be limited by bandwidth. Instead, you're likely being limited by latency, which can be influenced by a multitude of factors, some as simple as your distance from our servers.

I agree with your sentiment that your current send times are on the longer side. Just trying to find out more information.

**Comment by leonardoporpora** [comment]
The speed is not different with different Network and yes I think that the
previous versions were a bit faster but I'm not 100% sure about it.

>

**Comment by leonardoporpora** [comment]
PS. I have the same problem :)

**Comment by greyson-signal** [comment]
I'm going to assume this is likely location-dominated latency that we can't do much about on the clients. I'm going to close this just because it's inactionable for me and will likely require longer term work at the service level.
