### ISSUE TITLE
Time stamp error

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8553]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I try to send a message on signal when I haven't got internet the message obviously is not sent but once it get back the Internet connection the message is sent with the WRONG timestamp (when I clicked and I had no internet connection)

**Actual result:** wrong timestamp
**Expected result:** correct timestamp

### Device info

**Device:** pixel 2 xl
**Android version:** 9
**Signal version:** latest

### Link to debug log

https://debuglogs.org/17f25a93c893d2326f6f33b58e4a740253aaf968123c5919a974a2030863329f

**Comment by greyson-signal** [comment]
This is a design choice. There's two times a message is "sent" from the user's perspective -- once when you click the 'send' button, and once when the message is sent to the service. There's value to knowing both of these, but we choose to highlight the timestamp when the user clicks the button. If you disagree, feel free to continue the discussion on [the forum](https://community.signalusers.org/). Thanks!
