### ISSUE TITLE
Cannot rotate images from camera 

### ISSUE THREAD

**Issue by owiuefiweytgt** [signalapp/Signal-Android#8555]
Images cannot be rotated after being taken, appearing flipped at the receiving end.

It would be great if images could be rotated and flipped as part of the new image editor. Thanks.

Platform Info

Signal Version:

4.31.8

Operating System:

Android 7.1.2 (5250158c4b, NJH47F release-keys)

Turns out this is an Android bug as per: https://github.com/signalapp/Signal-Desktop/issues/3076

**Comment by greyson-signal** [comment]
We only use github for bugs. Please discuss feature requests on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
