### ISSUE TITLE
Contacts info not being synced correctly

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#8557]
* [x] I have searched open and closed issues for duplicates
---

### Bug Description

Scott told me to create this over here instead of the desktop app repo.
Talking with someone via SMS.  I invited to Signal.  They installed and messaged with me.
During this course, my desktop instance was going.  They appeared there but have no colors (them light gray, my dark gray) and the username on the left has their phone number, a tilde, and then their contact name

### Steps to Reproduce
See above.  I don't know what they really did in order and won't be able to get a log/steps from them

Actual Result:

User never syncs colors nor name stuff over to desktop

Expected Result:

Colors and user info sync over correctly

### Screenshots

![image](https://user-images.githubusercontent.com/4967949/51554203-eecaa700-1e31-11e9-9067-e1e4b36f0fab.png)

### Platform Info

Signal Desktop Version:
1.20

Operating System:
Win10

Android Device Version:
Android 8.0 stock
Signal 4.32.7

Logs:
Desktop:
https://debuglogs.org/272416159894b87b1685c0708b9cfd235dca8851dbda2c52ca18652e07bcb4ca
Android
https://debuglogs.org/064d75822ce808686392e4dde410471ec6f73ea397b6bc117d8bccd851e57500

**Comment by jeremymasters** [comment]
More details https://github.com/signalapp/Signal-Desktop/issues/3077

**Comment by jeremymasters** [comment]
So at some point during the night last night, this resolved itself on the desktop client.  Not sure what changed.  @greyson-signal do you want this left open to look at?  If not feel free to close.

**Comment by greyson-signal** [comment]
Looks like a WorkManager issue. You submitted a MultiDeviceContactUpdateJob, and it likely failed initially (poor network), but was never rescheduled. I'm guessing this is a result of the bug that was in WorkManager beta02 that was present in Signal 4.32.7, but was reverted to beta01 in 4.32.8. So hopefully this bug has gone away for now. Thanks!
