### ISSUE TITLE
Sending SMS always fails

### ISSUE THREAD

**Issue by tomreyn** [signalapp/Signal-Android#8558]
- [x] I have searched open and closed issues for duplicates
  There are some possibly related bugs, but I am not qualified to tell whether they are identical. IMO it's better to file a new bug in this situation.
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal reproducilby and always fails to send SMS, including to myself, reporting "Versand gescheitert." ("sending failed", German localization). Resending also fails. Sending SMS with default Android app succeeds. Receiving SMS with Signal works.

Mobile network: O2 (Telefonica Germany); service reseller: maxxim.de

### Steps to reproduce
- install and run Signal
- set Signal as default SMS app
- send SMS to own (or any other) mobile number

**Actual result:** SMS delivery fails.
**Expected result:** SMS delivery succeeds

### Screenshots
Will be provided upon request - we have a simple GUI error and a debug log.

### Device info

**Device:** Samsung S5 (SM-G900F)
**Android version:** 7.1.2 (LineageOS 14.1, MicroG)
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/bf6b1f4dca3e0d26d958e53061103eb6aec5845e411e2a18833ccbf191945c2f

**Comment by greyson-signal** [comment]
For reference, we get back:

```java
2019-01-23 12:43:49.662 MEZ I SmsSentJob: Got SMS callback: org.thoughtcrime.securesms.SendReceiveService.SENT_SMS_ACTION , 1
```

Error code 1 is `RESULT_ERROR_GENERIC_FAILURE`.

**Comment by tomreyn** [comment]
Sorry, it seems this is actually a firmware issue. I can't seem to send SMS using the native app (after switching back to that as the systems' SMS app) either. So please consider closing this one. Sorry for wasting your time.

**Comment by greyson-signal** [comment]
No worries :)
