### ISSUE TITLE
Cannot send any messages

### ISSUE THREAD

**Issue by xoref** [signalapp/Signal-Android#8559]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All messages via Signal fail to send since last update (I think.. it started about a week ago). I do still receive messages, but when I reply I never get a check mark (or 2) that confirms the message is sent. It's also clear when I check the logs that something is wrong:
`01-19 16:42:20.323  6040 13910 E ActivityThread: Failed to find provider info for org.thoughtcrime.securesms`

### Steps to reproduce
- On LineageOS (Android 7.1.2), install Signal and send message..

**Actual result:** Message appears stuck in sending status.. 
**Expected result:** Receive a message sent check mark + read confirmation soon after..

### Device info
**Device:** LGE Nexus 5 (hammerhead)
**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/e495eceb0413ce509abfe2e528de6fda4c9cef79b8cb78985276cf4fd35cb584

**Comment by ashtrull** [comment]
Appears to to be the same issue for me but earlier version, just wanted to post my debug log and info as well:

**### Bug description**
Upon hitting send for secure messaging, the message gets stuck in "sending" status, sending icon persists indefinitely and other user never receives the message. Can still send in "insecure" mode. 

**### Device Info**
**Device**: Galaxy J7
**Android version**: 7.1.1
**Signal version**: 4.32.7

**### Steps to reproduce**
On Android 7.1.1, install Signal and send secure message to other signal user
Actual result: Message appears stuck in sending status with icon spinning indefinitely, other user never receives message
Expected result: See secure message sent check mark + read confirmation check mark soon after

### **Link to debug log**
[](https://debuglogs.org/7f6fe5a86b5121e90469c02e0c890b56001db7487c42e746bcb5d29a6b8ef9d3)

**Comment by xoref** [comment]
Quick update; 
As the app was useless to me, I decided to completely remove & reinstall it. This helped and my message work again now :tada: (eventhough I lost all the existing messages in the process)

**Comment by UserX404** [comment]
@xoref Why did you not make a backup?

**Comment by lassefolkersen** [comment]
**Bug Description**
I have the same issue - with one twist. It's only for *one* specific contact I have the problem. For my other contacts (~7 people), I don't have the problem. Receiver confirms nothing received, but curiously can see that I'm writing (ambient three dots). I'm in time-zone UTC+1 if that helps matching below screenshot with log, and "now" is 2019-01-26 03:41 (so 02:41 UTC) and the friday test messages were 2019-01-25 08:42 (so 07:42 UTC), with same result. I have been successfully communicating with other contacts in the mean-time, could help when going over the logs.

![20190126_034215](https://user-images.githubusercontent.com/1732847/51781758-832c5680-211d-11e9-8d14-7860fad58ea4.jpg)


**Steps to reproduce**
Actual result: Message appears stuck in sending status..
Expected result: Receive a message sent check mark + read confirmation soon after. 

**Device info**
Device: Samsung Galaxy S7 (SM-0930F)
Android version: 8.0.0
Signal version: 4.32.8

**Link to debug log**
https://debuglogs.org/f3a3c965cca0c1d852175279bdf38cef1f1f3b6ae456d69039112e93c950cf10

**Comment by lassefolkersen** [comment]
Restarting phone worked. How simple. Thanks @greyson-signal - still odd though. 

The first message that got stuck was sent 2019-01-22. Again only for one specific receiver, no other problems for my other contacts. Oddly, I'm quite sure my phone was restarted in the past 4 days.

**Comment by dosera** [comment]
Same issue here.
Reboot only helps for a while - then only another reboot helps.

This makes the app unusable..

**Comment by greyson-signal** [comment]
@dosera Can you please submit a debug log?

@lassefolkersen 4.32.7 had a known issue with failing to retry properly, which can back up messages in a single conversation. Given the timeframe, your message could have gotten stuck on 4.32.7. Let me know if there's any new occurrences in 4.32.8.

**Comment by lassefolkersen** [comment]
Could be. I haven't had issues since. Will report back if it comes up in the future. Thanks for a great app.

**Comment by xoref** [comment]
FYI My problems haven't come back since I reinstalled the app, all works well!

**Comment by dosera** [comment]
ok @ greyson-signal, here you go:

Link to debug log: https://debuglogs.org/68bcc4528375dbe09f7aa40ca67b2fd8ca8092affd57639c31afd257de1c5d89

Btw I tried to reinstall but that didnt help (except that my keys are gone)

**Comment by strybe** [comment]
The issue is related to #8536 and it started before 4.31.8, for me with 4.30.8. So the conclusion in https://github.com/signalapp/Signal-Android/issues/8536#issuecomment-456233289 that it might be introduced with WorkManager beta02 is not true.

Also, as noted in https://github.com/signalapp/Signal-Android/issues/8559#issuecomment-457797879

> FWIW the first message that got stuck was a picture, a quite large one. Could be of importance?

the first failed message was one with a picture or video file.

Restarting did not help in my case.

**Comment by greyson-signal** [comment]
Merging similar issues together: #8602
