### ISSUE TITLE
null Files Generated from Sharing Documents into Signal

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8561]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I encountered this mostly through sharing documents (PDFs, Docx, Xlsx etc.) from reader apps ([Xodo](https://play.google.com/store/apps/details?id=com.xodo.pdf.reader)) or file management apps ([Explorer](https://play.google.com/store/apps/details?id=com.speedsoftware.explorer
)) into Signal. 

### Steps to reproduce
- Open a Third Party PDF Reader, File Manager etc.
- Share, Send some files into Signal
- Watch it being renamed as null

**Actual result:** Clients have to manually rename the file with the correct extension so it would open.

### Screenshots

![signal-attachment-2019-01-23-224210](https://user-images.githubusercontent.com/34171942/51631841-048bb980-1f63-11e9-878f-d9ed8cde3439.png)

### Device info

**Device:** Nexus 5
**Android version:** 6.01
**Signal version:** 4.32.8

**Device:** Nokia 3
**Android version:** 8.1
**Signal version:** 4.32.8

**Comment by minnmann** [comment]
I reproduced this using [File Manager HD](https://play.google.com/store/apps/details?id=com.rhmsoft.fm.hd&hl=de) and captured a debug log right after that:
https://debuglogs.org/85475949228bd34a194d24509c8e87b5f2d70ab290e8469a87bd8c3d82b30d8c

**Device:** Motorola Moto G5
**Android version:** 8.1
**Signal version:** 4.32.8

**Comment by hanswundersam** [comment]
This also happens when sharing a PDF file out of the CamScanner app (https://www.camscanner.com).

**Device:** Google Pixel
**Android version:** 8.1 (LineageOS 15.1, Google-free)
**Signal version:** 4.32.8

**Comment by szotsaki** [comment]
Can reproduce it on (receiver side):

Device: Sony XPERIA X
Android version: 8.0.0
Signal version: 4.37.2

**Comment by meawoppl** [comment]
This also happens when you share a file from signal to signal 😂

**Comment by Xashyar** [comment]
This is still reproducible on API 23 devices.
