### ISSUE TITLE
Signal crashed

### ISSUE THREAD

**Issue by Moxiflox** [signalapp/Signal-Android#8567]
**Bug description** 

Signal crashed

**Steps to reproduce** 

open a chat window

can't remember the exact steps

**Actual result** : Signal crashed 

**Expected result** : it doesn't crash

**Device info** 

Device: Samsung Galaxy S7 

Android version: 8.1.0 (Lineage OS without GAPPS)

Signal version: 4.32.8

**Link to debug log** 

https://debuglogs.org/e57dff361ef76bd536e0e64f7fcefe38967ccfccd8af5e72bb42f857f73f19ff

**Comment by OliverGraetsch** [comment]
I'm having the same issue. Each time I try to open a chat window, Signal crashes. But only when I'm on a Wifi connection. When I switch off Wifi and use mobile data, the app won't crash.
Already tried to reinstall Signal with and without restoring Backup. It's always the same issue.

Device info

Device: Oneplus 6 (A6003)

Android version: 9.0 (OxygenOS 9.0.3 = Stock ROM without Root)

Signal version: 4.32.8

Link to debug log
https://debuglogs.org/4b6dd1385b7b45862698a08d37e9da2fe942f0016c9d0d6f7e822bbdecc218b6

**Comment by Moxiflox** [comment]
Signal hasn't crashed since. I'm using an unofficial but stable build from January 2019, it freezes probably once a week (or even less).
I'll let you know about new crashes, thank you for your help :)
