### ISSUE TITLE
Scrollbar doesn't work on Note8

### ISSUE THREAD

**Issue by andymartin** [signalapp/Signal-Android#8569]
s begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [*] I have searched open and closed issues for duplicates
- [*] I am submitting a bug report for existing functionality that does not work as intended
- [*] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [*] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Scrollbar appears when I scroll conversation, but I cannot "grab" it.

### Steps to reproduce
- Open conversation
- Begin scrolling normally
- Observe scroll bar appears
- Attempt to grab and drag scroll bar

**Actual result:** Display scrolls as though I an swiping the display, not dragging the scroll bar.
Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** The display should scroll in the direction of the scrollbar drag, not the direction of the swipe.

### Device info

**Device:** Samsung Galaxy Note8

**Comment by greyson-signal** [comment]
Our scrollbar isn't grab-able, but this isn't unintended. I'd consider this a feature request, not a bug. Feel free to discuss it on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
