### ISSUE TITLE
Reproducible build v4.32.8 fails: "Execution failed for task ':signProductionPlayRelease'."

### ISSUE THREAD

**Issue by oittaa** [signalapp/Signal-Android#8574]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was following the reproducible build guide at https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds to the letter except I used `4.32.8` as the version number. The building failed after `./gradlew clean assembleRelease` command.

### Steps to reproduce
- mkdir ~/reproducible-signal
- mkdir ~/reproducible-signal/apk-from-google-play-store
- mkdir ~/reproducible-signal/image-build-context

Let's skip the part where I pulled the apk from my phone as it doesn't affect the build.

- wget -O ~/reproducible-signal/image-build-context/Dockerfile_v4.32.8 \\
                    https://raw.githubusercontent.com/WhisperSystems/Signal-Android/v4.32.8/Dockerfile
- cd ~/reproducible-signal/image-build-context
- docker build --file Dockerfile_v4.32.8 --tag signal-android .
- cd ~/reproducible-signal/
- docker run \\
              --name signal \\
              --rm \\
              --interactive \\
              --tty \\
              --volume $(pwd)/apk-from-google-play-store:/signal-build/apk-from-google-play-store \\
              --workdir /signal-build \\
              signal-android

Now we're in the container.

- git clone https://github.com/WhisperSystems/Signal-Android.git
- cd Signal-Android
- git checkout --quiet v4.32.8
- ./gradlew clean assembleRelease

### Device info
The virtual machine, where I ran the commands, was Ubuntu 18.04 with 6 CPU cores and 12GB of ram. 

### log
```
...snip...
> Task :transformClassesWithDexForPlayRelease

Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 4608 MB (based on the dexOptions.javaMaxHeapSize = 4g).
To do this set org.gradle.jvmargs=-Xmx4608M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html


> Task :signProductionPlayRelease
Running calculateSignature()...


FAILURE: Build failed with an exception.

* Where:
Build file '/signal-build/Signal-Android/build.gradle' line: 446

* What went wrong:
Execution failed for task ':signProductionPlayRelease'.
> java.lang.reflect.InvocationTargetException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 34s
31 actionable tasks: 30 executed, 1 up-to-date
root@b63dedd151ee:/signal-build/Signal-Android# free -m
              total        used        free      shared  buff/cache   available
Mem:          12984        2812        7425          44        2745        9810
Swap:           947           0         947
root@b63dedd151ee:/signal-build/Signal-Android#
```

**Comment by oittaa** [comment]
Are you saying that the Wiki page has incorrect steps?

**Comment by oittaa** [comment]
Now I understood. The apk is built even though there's an error. The Wiki page should mention about the error.

Anyway the last part in the wiki also has issues:
```
 apkdiff/apkdiff.py \
                   build/outputs/apk/Signal-Android-release-unsigned.apk \
                   ../apk-from-google-play-store/Signal-4.32.8.apk
```

There are two issues.
1. The file is actualle located at `build/outputs/apk/play/release/Signal-play-release-unsigned-4.32.8.apk`
2. `apkdiff/apkdiff.py` is a Python 2 script and doesn't work in a container with Python 3.

**Comment by oittaa** [comment]
After fixing the apkdiff.py by adding parentheses around the print commands, the following prints out.

```
Manifest lengths differ!
Sorted manifests don't match, META-INF/android.arch.core_runtime.version vs META-INF/SIGNAL_S.RSA
APKs don't match!
```

Is my phone hacked by a three letter agency? Is the script still broken? What's going on?

**Comment by johanw666** [comment]
Strange that they compare those files because the only way to get those identical to the official client would be for you to have OWS's signing keys, which they (understandably) don't distrubute.

I never compiled via the commandline so I have no experience with the subtleties there.

**Comment by oittaa** [comment]
Signal claims that people can do reproducible builds, but are you saying that it actually isn't possible?

**Comment by johanw666** [comment]
You cannot copy the signature part, the check should be if the functional parts of the apk are the same as in the official client. I thought the scripts checked on that but I didn't study them in detail.

**Comment by oittaa** [comment]
Thanks for pointing me to the right direction, @johanw666. I was able to create an automated script that compares Signal from my phone to a freshly built one. https://github.com/oittaa/reproducible-signal

I'm just wondering if [apkdiff/apkdiff.py](https://github.com/signalapp/Signal-Android/blob/master/apkdiff/apkdiff.py) has been abandoned, because it doesn't work in the current container. If somebody from the Signal project wants to fix it, there's a working Python 3 version in my repo mentioned above.
