### ISSUE TITLE
Signal Android URL scheme support

### ISSUE THREAD

**Issue by mbootsman** [signalapp/Signal-Android#8578]
I have tested the latest version of the Signal Android app with URL schemes in the issue: https://github.com/signalapp/Signal-iOS/pull/95#issue-19255886, but none work, does this need to be built for the android app or am I using a the wrong URL scheme?

**Comment by greyson-signal** [comment]
We don't have any `sgnl://` link support.

**Comment by mbootsman** [comment]
Isn't it about time this is added to Signal on Android?
