### ISSUE TITLE
Not receiving notifications when phone is locked and connected through WIFI

### ISSUE THREAD

**Issue by ErwinDex** [signalapp/Signal-Android#8579]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I lock/sleep my phone (screen goes black) and when I am on wifi I do not get any messages from Signal. Only when I open my phone (I do not have to unlock it, just turn on the screen) I get a "retrieving message" pop up on the screen and after that the signal messages comes in. 

Whenever I am on data (4g) messages come through regardless of whether i have my phone locked or not. On Data it works fine.

IN the WIFI settings i have it set on keep wifi on during sleep. 
Signal is not being optimized for battery savings.

Whatsapp for example works fine on both wifi and data (messages give push notification when phone sleeps)

I followed this https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

And nothing seems to work.

### Steps to reproduce
- Turn on wifi
- Lock phone turn off screen
- make friend sent message
- Wait. 

**Actual result:** Not receiving the message, only when i turn on screen I get "retrieving message" and after that the message comes in.
**Expected result:** I should get a push notification of signal, even when my phone sleeps and its screen is turned off. Whatsapp ie works fine. 
I do get this notification on Data but not on Wifi. 

### Device info

**Device:** samsung j3 2016
**Android version:** 5.1.1
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/1399dff44e93155a45be8004c2daefbf42b066e492496f64ebd6b1d7b650b810

**Comment by billie80** [comment]
This should probably go to #8583!?

**Comment by greyson-signal** [comment]
@ErwinDex Unfortunately your logs show signs of Signal fighting against the restrictions some Android manufacturers put in their phones. 

1) Some manufacturer's will straight-up delay our push notifications, or batch them together, to save battery in various situations. These situations are manufacturer-specific.
2) Some devices will prevent or limit the use of network, even after we've received a high-priority push notification, which can delay us pulling down messages.

At the moment, I don't think there's much we can do. Signal itself does not treat mobile data differently from Wi-FI when processing notifications. It's your phone trying to optimize battery. There's a guide [here](https://dontkillmyapp.com/samsung) that I also like that you can check out. Also worth noting that a lot of manufacturers have secret whitelists for popular apps like WhatsApp, which is likely why that app is unaffected.

I'm going to keep thinking about this, but I don't think we have any actionable steps right now.

**Comment by Hkarimi561** [comment]
i have this issue with some non sumsung mobile and i didnt see the notfication

**Comment by Hkarimi561** [comment]
:open
