### ISSUE TITLE
Inconsistent display of date labels (landscape - portrait switching)

### ISSUE THREAD

**Issue by pankarlox** [signalapp/Signal-Android#8583]
- [ x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I click on a conversation with one of my contacts in Signal, the message dates are displayed correctly in the middle of the screen. After switching to landscape mode the dates are displayed on the side of the screen. If I return to portrait mode, the dates 'escape' from the screen. 

This issue has already been described [here](https://github.com/signalapp/Signal-Android/issues/6875#issue-250024792). Unfortunately, nothing has changed since then and the error still exists.

### Screenshots

1. I open conversations. Date is displayed correctly.

![signal-attachment2](https://user-images.githubusercontent.com/44022879/52167477-ddc84280-271b-11e9-9108-3b2fb5fe91ee.jpeg)

2. I turn my phone into landscape mode. The date is in the wrong place.

![signal-attachment3](https://user-images.githubusercontent.com/44022879/52167513-529b7c80-271c-11e9-8bbe-911894c04186.jpeg)

3. When I return to portrait mode the date 'escapes' from the screen.

![signal-attachment](https://user-images.githubusercontent.com/44022879/52167540-b32ab980-271c-11e9-8541-f71e4dbcd7c6.jpeg)

### Device info

**Device:** Samsung Galaxy S9
**Android version:** 9.0
**Signal version:** 4.32.8

AND
### Device info

**Device:** Samsung Galaxy A5 2016
**Android version:** 7.0
**Signal version:** 4.33.0 (beta)

**Comment by C-Higgins** [comment]
Can reproduce this on Galaxy S8, Signal 4.32.8, Android 8.0

**Comment by greyson-signal** [comment]
Fixed this in the next release branch. Thanks!

**Comment by siccovansas** [comment]
Great! Does this also fix #7846 (and the pull request and issue mentioned there)?
