### ISSUE TITLE
Spontaneous loss of registration

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#8585]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I lost registration a short time after I had a successfull Signal call. My phone didn’t know it was unregistered, I noticed because I got alerted by someone who tried to call me on Signal and got a “this number is not registered” error. I unregistered from the phone and re-registered. After that communication was restored, and resetting secure sessions was not necessary.

It sounde like this very old, closed issue: https://github.com/signalapp/Signal-Android/issues/4751

This is the second time in a short period I had this issue, see https://community.signalusers.org/t/i-suddenly-became-unregistered/5957

### Steps to reproduce
- register device on the Signal server and communicate
- wait?
- get a WhatsApp message from a contact that you can't be reaced on Signal because you're unregistered.

**Actual result:** Spontaneous loss of registration
**Expected result:** remain registered as long as you don't manually unregister.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.33.1

### Link to debug log
This is the debuglog of the device that lost registration: https://debuglogs.org/903eda0661d12c63ca70eaa998f2b9423d73a58357868aca5b0bb262ed17ee16

This is de debuglog of a device with an open session with the device that lost registration that tried to send a message: https://debuglogs.org/52afe5ca62c687bfa113fd57c446a1129961cbf8c2b2434680ceecc0e9272de9

**Comment by greyson-signal** [comment]
Ok, so just building an outline:

Your side:
```java
// Latest FCM token refresh
2019-02-03 09:43:06.223 GMT+01:00 I Job: [019c06bb-7f99-45f7-9bd4-c9b1cdc2c501] FcmRefreshJob :: Successfully completed. (Time since submission: 1392 ms, Run attempt: 0, isStopped: false)

// Call is initiated
2019-02-03 14:58:19.780 GMT+01:00 I WebRtcCallService: handleOutgoingCall...

// Manual unregister
2019-02-03 14:59:21.242 GMT+01:00 I TextSecurePreferences: Setting push registered: false

// Manual reregister
2019-02-03 14:59:58.560 GMT+01:00 I TextSecurePreferences: Setting push registered: true
```

On the other person's side:
```java
// Detects you as NOT_REGISTERED when they enter the conversation
2019-02-03 14:58:06.008 GMT+01:00 I ConversationActivity: onModifiedRun(): NOT_REGISTERED
```

**Comment by johanw666** [comment]
That seems to be as it is. After I detected I was unregistered at the server I re-regisytered, this time the sms verification worked the first time.

**Comment by greyson-signal** [comment]
In all likelihood, GCM/FCM sent us something indicating you no longer used the app, which caused you to be unregistered on the server. I've seen one other case of this happening. Out of curiosity, have you uninstalled the app, or maybe reinstalled the app under a different package name or signing key (like installing a custom build with a new package name or something) in the last month or so?

**Comment by johanw666** [comment]
I did not uninstall, and between those 2 instances I was running the same instance of my custom build (which does not change the package name). Last month I only upgraded from the 4.32 branch to the 4.33 branch but both were custom builds signed with the same signing key. For 4.33 I had to upgrade Android Studio to make it build.

I did have some network issues (wifi modem suddenly losing connection while not noticing the connected devices). Perhaps that was the cause?

**Comment by johanw666** [comment]
My modem crashed this night and I was again unregistered. I'm seeing a pattern here, it never happened when I'm on 4G or wifi on my work.

**Comment by greyson-signal** [comment]
Can you post another debug log?

**Comment by greyson-signal** [comment]
Just wanted to note that right before you unregister (within 30s), it looks like you're making authenticated network requests, received a message -- all stuff registered users do, so that's odd. And just to be clear, it's someone else that sees you as unregistered that causes you to do the  unregister-reregister?

**Comment by johanw666** [comment]
Yes, but last time I tested it with another device of my own. This morning (I live in the UTC+1 timezone) I was in a hurry and didn't test that, sorry.

Last message I received before I got a remark I was unregistered was 23:05 local time, this morning I saw an sms (not in Signal) on 00:31 that I was unregistered (but I was asleep when that one came in), I re-registered and sent on 6:24 a message I was registered again.

**Comment by johanw666** [comment]
I had it again, on the same device. The strange thing is that when I tried to send a message fro device 2 to the problematic device 1 I got a "send failed, tap for unsecured fallback". The debug log of device 2 is on https://debuglogs.org/631cd75467aea7c71f4283bbb557c555c1e8f73f54c91e2b5e649e73addd7b3b

On device 1 I could send a messagr to device 2 and it arrived OK. The debug log of that device is https://debuglogs.org/9242d7e2ce2cc55c873d6855d6b803c30656d6b14123587f811421a58f587a12 . And it does contain the "FcmRefreshJob: New token differs from the old token." message.

I do find it strange that it is always the same device that has this issue.

**Comment by greyson-signal** [comment]
I didn't want to log the actual tokens in the regular build, but since you have your own custom build, would you be able to add additional logging around what the tokens actually are? And then pull logs with ADB or something? It sounds strange to me that the tokens would be different, but you haven't hit the `FcmService#onNewToken()` callback.

**Comment by johanw666** [comment]
OK, I'll do that tomorrow after work.

**Comment by shuttle1987** [comment]
I wonder if I have run into the same thing, here's a log dump:
https://debuglogs.org/92bb54e50751593a1044b5c9d1243df8653ffce87850f8922e820dd1380d36c0

**Comment by johanw666** [comment]
I had it again: https://debuglogs.org/edc2433edcdec02feebde2e27209a7178a29d9270a7f57cbca9b7a74d984b436

**Comment by johanw666** [comment]
And again: https://debuglogs.org/1cf437a861ce4848c57e1f19fa0a63800e002efe40bef28a4f01670b6ecaa42b

**Comment by johanw666** [comment]
And again. The other side (iOS) reported that a message from me came in, I saw the status change from received to read, and immediately after that I lost registration. I checked with another device that I indeed did report as unregistered.

https://debuglogs.org/ec1152a1a6fb9e7f603917639e55927d92ddcde1d299793ba0d502282fce5601

**Comment by greyson-signal** [comment]
@johanw666 Would you consider trying out a production Signal build for a week to see if it happens there too? The only reasonable explanation is that FCM is telling our server that you've uninstalled the app or have otherwise become inactive. Historically we've always had a few instances of this happening, but it's usually only once or twice and then never again. Things we've attributed to bugs in GCM/FCM. I've never seen it happen so consistently to one person, and this doesn't appear to be happening any more frequently to other users (I've been keeping a close eye on support inquiries). Just trying to eliminate variables.

**Comment by johanw666** [comment]
I am testing something else now: this  started when I got a new job and I used the device that lost registration often as a hotspot for other devices that also had Signal installed (2nd phone I used as car navigator, and the the wifi quality here,, ehm, has room for improvement). Since I stopped tethering the issue did not occur again. Maybe something with several Signal installs going over the same connection?

**Comment by johanw666** [comment]
It went OK for a while but I lost registration again, I might try the original client for a while on that device.

https://debuglogs.org/b135ddb70437816f09f54b606c230811a4e4da96a00f17dada5f819937962437

**Comment by nutts0** [comment]
Sadly it looks like with the new jobmanager we still have this problem.

**Comment by johanw666** [comment]
My debuglog is at https://debuglogs.org/65a508ab98875e63f504e74a4516ce263f11a485b5f44a7266931d6c6a583b4b . Again the line
```
FcmRefreshJob: Token changed. oldLength: -1  newLength: 152
```

**Comment by greyson-signal** [comment]
@johanw666 I remember looking into the `oldLength: -1` thing, and I discovered it was normal. Basically `getFcmToken()` returns `null` after upgrades. Either way we're still setting the token to what we get from the system, so it doesn't change the behavior (reporting the current token length was just a debugging thing).

It could imply that for you, this is happening more frequently around app updates. At the end of the day what's almost certainly happening is that the FCM system is telling our server that you uninstalled Signal, which gets you marked as unregistered. Trying to think through the best mitigation.

**Comment by greyson-signal** [comment]
@johanw666 What might be interesting is if you altered your build to spit out the actual token before + after the refresh to see if there's any changes. You'd have to create a new method on TextSecurePreferences that's like `getFcmToken` but doesn't return null on new versions. Something like:

```java
public static String getRawFcmToken(Context context) {
  return getStringPreference(context, GCM_REGISTRATION_ID_PREF, null);
}
```

And then for logging:

```java
Log.d(TAG, "oldToken: " + TextsecurePreferences.getRawFcmToken(context));
```

**Comment by johanw666** [comment]
I will do that. Any reason why this is not put in the normal build? Is this information somehow privacy related?

**Comment by greyson-signal** [comment]
I actually don't think it's super-sensitive, but it's one of those better-safe-than sorry things.

**Comment by johanw666** [comment]
Oh, and btw, do you need the new token as well in the logs? Better log someting like
```
Log.i(TAG, "oldToken: " + TextSecurePreferences.getRawFcmToken(context) + ", newToken: " + token.get());
```

**Comment by greyson-signal** [comment]
Yep that makes sense to me :+1:

**Comment by johanw666** [comment]
It happened again, this time I could capture the tokens in the logfile: https://debuglogs.org/94017f1bd9e9ac8802bdc656e53dd8da0916012c525e6a42e6715216b27b292a
```
2019-04-25 07:50:15.155 GMT+02:00 I FcmRefreshJob: Token changed. oldLength: 152  newLength: 152
2019-04-25 07:50:15.155 GMT+02:00 I FcmRefreshJob: oldToken: c0zBXmykTPU:APA91bFRpiImfLtWT_kjsoEwOvzPQIONtboNO-jT-6atR-8bZ__x-99t3gR4jNqUmvnvTGzQoWZvAJhOVAOj7_jnpECzifYSH5L05K4PqlT0KwwipaGQdt-lOo9bL514_9aIqnXaDCav, newToken: c0zBXmykTPU:APA91bHjUpSzN4XPUrK5CpcHgGOMpUVBaAPAaqJjmd1UW0wyqvEklOhvanPANzQObUESdoF1k_JCQyWGu1UGvAbR9TcBs8YYxcFAFJApDD0XRpigX1xxpHs4gWlGZIw_UC3mRQlBRrF3
```

**Comment by johanw666** [comment]
And again: https://debuglogs.org/0d0ca00ede86c2302b0522d26b8f6c5b5abd994137d19dd87bcf801835262dc9

**Comment by johanw666** [comment]
Usefull debug log this time: https://debuglogs.org/199d7f6d291a2b28793327d1641f3937375453216a0804c37ed7d259be565f38

```
2019-04-29 12:21:55.408 GMT+02:00 I FcmRefreshJob: Token changed. oldLength: -1  newLength: 152
2019-04-29 12:21:55.409 GMT+02:00 I FcmRefreshJob: oldToken: dSUz3-tbh4E:APA91bEcNIJNC-ZLbe9vt_VVfA52gLZTFvSx3uoGaUi5BjYt2W6j_9Qp1am4T56NnYpCkChbxrjJB2-fQGZVfElh4cIijHX3ikhZW2ySZVWmBZx-4AHREQ03ppXuCw-sRkUkZIqw_mHC, newToken: dSUz3-tbh4E:APA91bEcNIJNC-ZLbe9vt_VVfA52gLZTFvSx3uoGaUi5BjYt2W6j_9Qp1am4T56NnYpCkChbxrjJB2-fQGZVfElh4cIijHX3ikhZW2ySZVWmBZx-4AHREQ03ppXuCw-sRkUkZIqw_mHC
```

**Comment by greyson-signal** [comment]
We've just launched a server change to help reduce the impact of the bad "unregistered" signals we're getting from FCM. Hopefully this will resolve the issues you've been having. Thank you very much for your efforts in helping debug this!
