### ISSUE TITLE
Mac OS Update (to 10.12.6) Signal Desktop fails to Message Older Contacts

### ISSUE THREAD

**Issue by debrazebra1209** [signalapp/Signal-Android#8587]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently updated my Mac to the 10.12.6 OS. Now, Signal desktop fails to send messages to contacts who were added before the update. Contacts added after the update can receive messages. This is the error I get when I try to message older contacts from signal Desktop:

Error received from SQL channel job 474 (getSessionsByNumber): Error: SQLITE_CORRUPT: database disk image is malformed

I can still receive messages from all contacts, and I can send and receive messages fine on my phone app (iPhone 8).

### Steps to reproduce
- attempt to send a message from Signal Desktop to a contact who was added prior to last week's update
- Get 'send failed' message 
- Click further info to get the following error:

Error received from SQL channel job 474 (getSessionsByNumber): Error: SQLITE_CORRUPT: database disk image is malformed

The message should send fine, and prior to the update it did. 

### Device info
**Mac Book Pro:** Mac OS Sierra 10.12.2
**Signal version:**  Desktop 1.20.0 

### Link to debug log
https://debuglogs.org/fdb5cd1fab2f94f0384ac8c710cec3f0c17af653f3c8976e2afefa3e3fcedaaa

**Comment by billie80** [comment]
This than should go to the Signal Desktop issue tracker! Here only issues of Signal for Android are tracked!

**Comment by 2-4601** [comment]
Oops... seems like you accidentally opened this on the Android app's issue tracker.

Could you please copy paste your bug report here: https://github.com/signalapp/Signal-Desktop/issues/new
