### ISSUE TITLE
Profile avatar appears rotated

### ISSUE THREAD

**Issue by cdenyar** [signalapp/Signal-Android#8588]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Setting avatar as images taken with Google Pixel 2 XL appears rotated.

Checking the image's exif data, I noticed the following attribute which seems is not applied: Image Orientation (Short): Rotated 90 CW.  If I send someone the same picture in Signal, it appears oriented corrected, it's only when setting the picture as my avatar that is not.

### Steps to reproduce
- Take photo with Google Pixel 2
- Attempt to set photo as avatar
- Observe photo appears to be rotated 90 counter clockwise

**Actual result:** Photo appears rotated counter clock wise.
**Expected result:** EXIF data is checked so avatar appears with correct orientation

### Screenshots
![screenshot_20190203-153141](https://user-images.githubusercontent.com/6653063/52182231-1b36d980-27c9-11e9-9002-547e715066db.png)

### Device info
**Device:** Google Pixel XL 2
**Android version:** 9
**Signal version:** 4.33.1

### Link to debug log
https://debuglogs.org/ecdc2bfcaad5bebcdfe66dd7e3294b89b3a96d9cce6dbedab65ed591c4572fbc

**Comment by five-c-d** [comment]
I cannot *fully* confirm this problematic behavior, but I do distinctly recall having trouble setting an avatar on a previous device... I would take the phone-cam picture, and then it would be turned 90degrees "unexpectedly" once it was saved as the signalapp avatar.  I worked around the problem by rotating the phone-cam physically during several attempts to re-take the avatar-photo, and eventually got what I wanted to happen, to happen.  At the time, I assumed it was an operator error   ;-)  

This was months ago, but the device in question was signal4android ZTE z557BL handset with stock ROM, android 7.1.1 probably
