### ISSUE TITLE
WebP files act as still images on Android, and as GIFs on Desktop

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8593]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I sent a WebP file created on [ezgif.com](https://ezgif.com/video-to-gif) from my desktop, the picture is clearly moving. Just like a GIF.

On my Pixel XL, however, the file is completely frozen like a picture.

### Steps to reproduce
1. Download this file
[Mob.zip](https://github.com/signalapp/Signal-Android/files/2841080/Mob.zip)
2. Unzip the .webp file inside of the .zip
3. Send that file
4. Look at your phone
5. The picture is completely frozen

**Actual result:** WebP files aren't acting the same way as they do on Desktop
**Expected result:** WebP files should play as GIFs just like on Desktop

### Device info
Pixel XL
Latest Android
Latest Beta

### Link to debug log
I don't think this is necessary, but ask me and I will upload a log.

**Comment by greyson-signal** [comment]
We support what Glide supports. Right now, Glide has no built-in webp support and defaults to the system. I don't know if they really support _animated_ webp at all. You can see this issue for reference: https://github.com/bumptech/glide/issues/571

There's some libraries out there that add webp support to Glide that Glide has acknowledged, but IMO if they're not good enough for Glide to merge in, they're probably not good enough for us either. Image decoding is a sensitive area.

Either way, not much action for us to take. Animated webp files will start working when Glide adds support.
