### ISSUE TITLE
old app shows deleted contacts when synced with new app on different device.

### ISSUE THREAD

**Issue by DCUplink** [signalapp/Signal-Android#8594]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Old clients pull up old contact chat sessions that were deleted from newer clients.  

Potential security risk:  The app should remove the contacts the new instance doesn't have.

### Steps to reproduce

1. Let an older signal client sit dormant while newer client continues to update.  
2. Delete contact old client and new had.  
3. Re add old client location to signal new client using QR scan method (old windows added into new android client)
4. Old app will show old contacts new app has had manually removed.

### Screenshots
N/A

### Device info
Windows client old version prior to update - november 2018
Windows client new version prior to adding to account - 1.21.0 (pulled down update today)
Android client - 4.32.8

### Link to debug log
N/A

**Comment by 2-4601** [comment]
> 2. Delete contact old client and new had.

By deleting a contact do you mean
1) deleting a contact from your phone's contact app or
2) deleting a Signal conversation with some contact?
