### ISSUE TITLE
Android 9 no notifications despite being fully enabled

### ISSUE THREAD

**Issue by ctradio-james** [signalapp/Signal-Android#8595]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Specifically on the PIXEL 2 XL device with standard AOSP firmware (Android 9/Pie).  At first just the Signal Messenger (encrypted messages) notifications would not work and messages actually would not come to Signal unless I opened it (suspect background service issue).

Recently in the last couple weeks or so, my device would not receive text messages at all (suspected carrier issue).  Got that to reset by removing Signal as default and then coming back to it from Messenger (stock messenger, not Facebook).  Now, as of the last week or so regardless of the type of message I am getting no notifications at all despite the Signal application having full notifications access.  Any ideas?  Everything worked fine on the same device when it was on Android 8.1 (Oreo).

### Steps to reproduce
- Having a Pixel 2 XL with AOSP Android 9.0

### Device info
Google/LG Pixel 2 XL
Android 9.0
Signal Version latest release channel as of this post (loaded Beta signal to test further as of now).

### Link to debug log
Suspect this is an issue related to Android 9.0 and how Signal integrates.  The application works as expected other than no private messages coming in when it is not foreground and no audible or visual notifications posted to OS notifications.

**Comment by greyson-signal** [comment]
Can you upload a debug log after you experience a missed message and post the link here? (Settings > Advanced > Submit debug log)

Also, can you take a look at your notification channels screen (System 'App Info' page for Signal > Notifications) and either describe it or post a screenshot of it if you're comfortable?

**Comment by ctradio-james** [comment]
Debug Log 
https://debuglogs.org/1f35ac9d67386c27d959d9c23c98dcc99d9837174f830a94fabbad5ab14839a7

**Comment by ctradio-james** [comment]
![screenshot_20190207-122938](https://user-images.githubusercontent.com/47425491/52430710-b6cf8f00-2ad4-11e9-937b-be63b337008f.png)
Screenshot of notifications panel.

**Comment by greyson-signal** [comment]
Hmm, so I see in the logs that we are posting notifications to the NotficationManager, i.e.

```java
2019-02-07 12:26:02.187 EST I MessageNotifier: Posted notification. Notification(channel=messages_1 pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x1 color=0xff2090ea category=msg groupKey=messages actions=2 vis=PRIVATE)
```

(You can ignore the sound=null and stuff -- that's normal because everything comes from the channel now)

I see you also have a lot of custom notifications for specific contacts.

1. Can you verify that all of the settings inside of those channels look correct?
2. Can you confirm whether or not you see notifications from people who _don't_ have custom notifications?
3. Can you confirm whether or not you get notifications if you receive a message while the app is foregrounded and you're looking at the conversation list?
4. When you say you're on 'AOSP', do you mean you have an off-the-shelf Pixel 2 XL that you upgraded to Android 9.0 using the build-in upgrade path, or do you flash Android yourself? Curious because I see some Google Play Services errors in your log, and that kind of thing could result in not getting FCM messages when the app is backgrounded.

**Comment by ctradio-james** [comment]
1) All the custom contact notifications are set to allow either "no sound" or several that have a different sound.  These have not changed in the last year or more.  The notifications inside of the Android settings for the contacts I looked at are set to "Make sound and pop on screen"
2) I do not see notifications from anyone, including my other phone which has been used for a lot of this troubleshooting.  There is no custom notifications for my other line.
3) Messages do not show or come in at all (signal or MMS/SMS) .  When I am on the conversation list I can see a message of any type arrive.  Outside the application nothing happens (just tested SMS/MMS and Signal message as well as custom notifications versus default notifications)
4) AOSP = Stock google ROM right from google for the device.  This device was flashed to 9.0 using standard ADB/Fastboot tools.  I am not sure what the google play services app is doing.  It has been updated beyond what came with the ROM.  I am on the October 2018 release and was contemplating ADB sideloading the latest.

**Comment by greyson-signal** [comment]
Just want to clarify this:

> 3\. When I am on the conversation list I can see a message of any type arrive.

Do you see actual notifications posted (a little popup at the top of the screen, gets added to the notification tray, etc), or do you just see the conversation list item summary update?

**Comment by ctradio-james** [comment]
I only see the conversation list update.  No pop-up or sound on the screen, top, banner or otherwise.

**Comment by greyson-signal** [comment]
Hmm, yeah, something doesn't seem right here. Like at a system level. We're definitely telling the system to show a notification. I would normally say that this sounds like a Notification Channel issue, but I just put additional checks in 4.33.x to ensure that we won't post notifications to non-existent channels. And if notifications don't even come in for people with non-custom notifications, then that makes me even more sure this isn't Notification Channel related.

Have you done testing with other apps after you upgraded? Sorry, wasn't clear with the timeline as to when you upgraded to 9.0 vs when you started experiencing the different issues you mentioned in your original post.

**Comment by ctradio-james** [comment]
Upgrade to 9.0 was done in October 2018 (no updates to the OS since then).  The issues here are on the same OS.  Tried to refresh my Google Play Services with no results so far.

**Comment by ctradio-james** [comment]
Honestly I think I will be wiping the phone and starting over!  The stock messenger app is not seeing MMS/SMS at all and another program I have notifications on for is not posting.  Going to try an ADB sideload update first before I blow it out completely!

**Comment by greyson-signal** [comment]
Gotcha, if it's not working for another app, then I'm gonna close this as being an issue with your device. Best of luck!

**Comment by haffenloher** [comment]
@ctradio-james judging from your screenshot, you have "Do Not Disturb" turned on. My guess would be that "Settings > Sound > Do Not Disturb > Notifications" is set to "No visuals or sound from notifications", which would cause your phone to not show notifications at all (or delay them until you disable DND).

**Comment by spider1163** [comment]
@ctradio-james I had the same problem and you solved it, thank you !

**Comment by ctradio-james** [comment]
Maybe I should open another issue.  On my new Moto Z4 (mind you they have tons of software bugs in the rom it seems) without DND being turned on or anything.  Signal messages are not coming though until I open the application.  Battery optimization is turned off. Am I missing something?  Is there a foreground service I need to turn on?  I am leaning towards a ROM issue only because this phone does other silly things like ignore screen rotation settings when it feels like it).
