### ISSUE TITLE
"Mark as read" feature from notification channel not working if there are multiples senders

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8598]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you have more than one message unread in Signal and you try to mark one as read from notification channel y doesn't work as expected and is showed in conjunt with the messages of other senders.

### Steps to reproduce
- Wait to receive messages from more than one senders.
- Open the channel notification and "Mark as read" the messages from one sender.
- Press the "Home" key.
- See the notifications again.

**Actual result:** Messages are showed in conjunt with another senders messages.
**Expected result:** Message is marked as read and disapeared from the notification channel.

### Screenshots

![imagen](https://user-images.githubusercontent.com/32582878/52448911-6d4a6880-2b03-11e9-982b-4b65f9c3c38d.png)

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.33.3

### Link to debug log

Not needed.

**Comment by greyson-signal** [comment]
Thanks for the report! Unfortunately this was a regression introduced in a0c1446e9ff283b6e77cceb79ee16ba4e3c089d9.

I've reverted the change in 45ddb7e1ad05a599a89cf84185a6087279483ee8.
