### ISSUE TITLE
Where do i find sources for gson and armeabi.jar?

### ISSUE THREAD

**Issue by ccoenen** [signalapp/Signal-Android#860]
I am currently evaluating the TextSecure app. I can compile it just fine, but there's two things i can't find sources for.

One thing is the WhisperSystems/gson (dependency in library subproject) and the other is the armeabi.jar.

I wonder if the [gson](https://github.com/WhisperSystems/maven/tree/master/gson) library is 100% based on google's code? If so, why are you packaging your own lib? The same goes for android-support-lib and the gcm libraries.

As for the armeabi.jar, i couldn't really track that one down. I would love to look into that, too. I hope, i'm not missing some obvious part of documentation or something. If I do, please just point me in the right direction.

Cheers!

**Comment by Inihood1** [comment]
hello there please  how do i handle the lib
