### ISSUE TITLE
off-topic: donate to Signal Foundation

### ISSUE THREAD

**Issue by tipuraneo** [signalapp/Signal-Android#8608]
Hello,

I'm using Signal/Textsecure nearly since birth and like to directly donate to the newly created Signal Foundation. When will that be possible? I don't want to donate through the Freedom of the Press Foundation.

https://signalfoundation.org/ tells just "Coming soon".

Kind Regards

**Comment by jlund-signal** [comment]
The Freedom of the Press Foundation is still graciously accepting donations on our behalf while our status is pending, and that's the only way to donate right now. We'll be sure to [update this documentation](https://support.signal.org/hc/en-us/articles/360007319831-How-can-I-contribute-to-Signal-) when something changes.

We only use GitHub for bug reports, so if you would like to discuss this further (or talk about anything else) please feel free to do so on the [community forum](https://community.signalusers.org/).

Thank you for being willing to help!
