### ISSUE TITLE
Suggestion to reduce message box height in user interface

### ISSUE THREAD

**Issue by bertolo1988** [signalapp/Signal-Android#8609]
Could messages have a bit less height? 
I feel like the time to delete below the text message could occupy a bit less.

If several messages are sent in a short time by the same person they should stack inside the same message box. This would create issues with the message status though.

**Comment by 2-4601** [comment]
Thanks for the feedback. These suggestions are better suited for the forum (you can sign up with your GitHub account).
See for example this topic: https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532/153
