### ISSUE TITLE
Can't have inbound messages in Mobile Network

### ISSUE THREAD

**Issue by GAS85** [signalapp/Signal-Android#861]
Hello dear TextSecure Team,
 I did install you app on my mobile phone and find out that if I’m using 2G/3G/LTE network – I will never receive any message. But I can send them.
 I will receive all messages since I got connected to WiFi, or if I establish VPN through mobile network. Could you please investigate this issue?
 I did check with provider and they are not blocking any ports for me,

Mobile Phone - Galaxy S3 LTE, Android 4.3.
Provider Telekom Deutschland.
Please let me know if you need more information.

Kind Regards.

**Comment by KommX** [comment]
Can someone post the exact solution for this problem?
A friend of mine has the same problem and just enabling and disabling "Restrict background data" in "Data usage" didn't do the trick.

**Comment by agrajaghh** [comment]
Please ask your question at the support center: http://support.whispersystems.org/
