### ISSUE TITLE
Image and video quality compression option

### ISSUE THREAD

**Issue by damianon** [signalapp/Signal-Android#8612]
This is probably related to #672 but as that issue is closed I'd like to open a new one.
Compression seems to be better now, but it's still there. 

Please add the option to turn off compression completely for images and videos (separate options).
I've seen this in other messengers and it results in me only sending small "preview" images to friends because I can't send the "real thing". Specifically videos are still compressed quite badly.

And for the bandwidth argument: Where I'm from data plans are really cheap so for me compression is more of a problem than data usage. Also I can use WiFi and thus not care about size at all.

As there are still people that have to care about it, I would suggest an option with default on compression but an option to turn it off and send the original file.

**Comment by 2-4601** [comment]
Feature requests are handled in the forum (you can sign up using your GitHub account).
Here's a request for compression: https://community.signalusers.org/t/option-to-compress-video-record-video/3833
You can add to that thread that you'd like to see an option to retain the original quality.
