### ISSUE TITLE
Signal Desktop constantly reconnecting

### ISSUE THREAD

**Issue by jasonwatkinspdx** [signalapp/Signal-Android#8614]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For several days not Signal Desktop on OSX has been constantly reconnecting. It reconnects every 10 seconds or so. I only receive only around 50% of incoming messages, and sending fails at a similar rate. While I'm receiving the missing messages on my phone, after enough errors the phone app begins responding with "too many failures with this contact, try again soon".

Additionally, attempting to open the debug log on signal desktop hangs indefinitely on "Loading".

### Steps to reproduce
- Open Signal Desktop
- Attempt to receive or send a message

**Actual result:** I only receive around 50% of inbound messages, and sending fails at a similar rate.
**Expected result:** Signal working as normal.

### Device info
**Device:** Apple Macbook Pro, current generation
**Signal version:** 1.21.2

### Link to debug log
I am unable to load a debug log.

**Comment by greyson-signal** [comment]
Hi there! There's actually a Signal-Desktop repo where you can report desktop bugs. Please move this issue over there. Thanks!

https://github.com/signalapp/Signal-Desktop
