### ISSUE TITLE
Webp image does not show on iOS

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#8616]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I sent a webp image from an Android device to a iOS device. On my Android phone the image showed as it should be, on iOS the receiver only sees a box with the text "webp".

### Steps to reproduce
- Send webp image from Android to iOS
- Look at te incomming message in iOS

**Actual result:** A box with the text "webp" is shown.
**Expected result:** The image is shown.

### Screenshots
![webpios](https://user-images.githubusercontent.com/8427572/52818997-7bbaf600-30a8-11e9-8382-090c38bf12a1.jpg)

### Device info
**Device:** Sony Z3 compact
**Android version:** 6.0.1
**Signal version:** 4.33.5

On Signal iOS a similar issue is already reported: https://github.com/signalapp/Signal-iOS/issues/1547

**Comment by greyson-signal** [comment]
iOS has more restrictions about what types of media are rendered in a conversation. WEBP isn't on their list, so it shows up as a regular file attachment. If you feel that WEBP should be added to the list, try opening a thread on the forum, or file an issue on [their Github](https://github.com/signalapp/Signal-iOS).
