### ISSUE TITLE
Font Size Setting Not Followed

### ISSUE THREAD

**Issue by stumpylog** [signalapp/Signal-Android#8617]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
At times when switching back to Signal, either through the app switcher or opening again, the font size in conversations will have changed from the set size (small) to something much larger (normal or large?).  At one point, I even saw a mix of sizes in one conversation.

### Steps to reproduce
- Force close Signal
- Open conversation (maybe reply)
- Use other apps on the phone
- Return to Signal

**Actual result:** Font size in conversation has changed
**Expected result:** Font size should remain the same

### Screenshots
![screenshot_20190215-083757_signal](https://user-images.githubusercontent.com/797416/52870872-ad11e100-30fd-11e9-9f55-0e90e22999fa.jpg)
Contrast the size of "Oh no" with previous texts from myself and the other person

![screenshot_20190215-082806_signal](https://user-images.githubusercontent.com/797416/52870915-ca46af80-30fd-11e9-83a5-9e090a23a9a7.jpg)
This is the normal size, based on my settings

### Device info
**Device:** Samsung Galaxy S7 (SM-G930V)
**Android version:** 8.0.0
**Signal version:** 4.33.5

### Link to debug log
https://debuglogs.org/0feebbd582a3c70618d67551610352c3d87541e69e4269a44ed3e23d4c2f0e2e

**Comment by 2-4601** [comment]
Could be #2815

**Comment by stumpylog** [comment]
Hmm, they may be related, though in my case, I'm not rotating the device (it's locked to portrait) and the system language matches the Signal (English and Default) respectively.

**Comment by 2-4601** [comment]
Some apps can still change rotation to landscape even if device is locked to portrait (e.g. YouTube, Camera). If you dare, try to change Signal's language to non-English and see if it changes at the same time as the font size.

**Comment by stumpylog** [comment]
I changed the Signal language to French and attempted to get the font size to change. Just changing the language and viewing a conversation had no effect.  When unlocking the rotation, and rotating conversations, the test size remained small.

But after relocking rotation and changing back to Default, I got stuck in large text.  Even forcing the app closed or changing font size in the setting, the size in a conversation remains large.  While in this state, I grabbed another log after doing the following:
- Force closed Signal
- Opened Signal, viewed conversation
- Changed font size from Small to Normal
- Viewed conversation
- Changed font size from Normal to Small
- Viewed conversation

In all cases of viewing the conversation, the text size remained large.  I actually had to restart the phone before it went back to small.

https://debuglogs.org/dc903bee368e63ed1a1edd62da8932b8ca8c562e3a6d8e8fee3f72289aefa27f

**Comment by sweah82** [comment]
Hi,
I do also see the problem with changing font sizes. Here is a debug log: 
https://debuglogs.org/90f20729f7fadb89bca0b1d7fe5a70636af8af199ada6db7152fbd20c5368a06
I start signal and everything is as it should be. After sending an attachement in one conversation and then switching to another, I have 'normal' font size instead of the configured 'small' size. It stays that way until I stop and reopen the App.
Greetings, Chris

**Comment by tentaclemoose** [comment]
This annoying bug still exists. It started for me when I switched from small size back to normal - conversations are now either small or normal or a mix of both, it seems to change pretty randomly whenever i open the app.
Force killing it makes it behave for a little while.
