### ISSUE TITLE
Disappearing message timers appear twice on Note to Self

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#8619]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Disappearing message timer appears twice when set on desktop's Note to Self conversation

### Steps to reproduce
- Open the Note to Self conversation on Desktop ([v1.22.0-beta.1](https://github.com/signalapp/Signal-Desktop/commit/552db647e5b0f6d272da608c2f3ed4cfa77b90e3))
- Set a disappearing message timer with the Desktop client

**Actual result:** You will get two status messages on Android:
1. `+8198008135` set the disappearing message timer to x
2. You set the disappearing message timer to x

**Expected result:** You will only get one status message on Android:
* You set the disappearing message timer to x

Not sure if this is the desktop's fault or Android's fault but desktop never displays the status message twice regardless where the timer was set.

### Screenshots
![screenshot_20190215-205557](https://user-images.githubusercontent.com/174176/52878537-88515400-3165-11e9-817d-4ae7532589ed.png)

### Device info

**Device:** Pixel XL
**Android version:** 9.0
**Signal version:** 4.34.0

**Comment by greyson-signal** [comment]
I see the problem, I'll address it.

Side question: did you get 4.34 from the play store, or did you build it yourself?

**Comment by 2-4601** [comment]
Self-built.

**Comment by greyson-signal** [comment]
I've confirmed this is a desktop bug that'll be fixed. I'll close this issue, but if it's still happening to you in a week or something, feel free to open an issue on Signal-Desktop. Thanks!
