### ISSUE TITLE
Spontaneous loss of today's messages

### ISSUE THREAD

**Issue by uspoma** [signalapp/Signal-Android#8621]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Just a few minutes ago my chat partner suddenly lost all messages from today. Timer was of course not set. On my side (I have Signal on my phone which is also linked to a desktop instance) the messages are still there. Strange thing is when my friend lost today's messages suddenly some messages I sent hours ago doubled in my Signal desktop instance.

### Steps to reproduce
- Not sure how to reproduce it.

**Actual result:** Messages disappeared
**Expected result:** Messages don't disappear

### Device info
My phone: Signal 4.33.5, Android 8.1
Friends Phone: Infinix Note 3, Signal 4.31.6, Android 6
My desktop version: 1.21.2

### Link to debug log
My friend submitted the log through the debug log submitting option in Signal. I have no idea where that log went to. But I could get another log if needed probably.

**Comment by greyson-signal** [comment]
Hi there! So when you submit a debug log, we don't get notified of it. We need the link we give you when a debug log is submitted. If you could get logs from both you and your friend and post the links here, that'd be great. Also, if you could get the logs from your desktop instance and post the link here as well, that'd be helpful. Thanks!

**Comment by uspoma** [comment]
Sure, here is the log from my chatpartner: https://debuglogs.org/5199beec413fa1c5515372189807fc6fead54132fc8000119bec5c03abba985d

I can provide a log from my desktop instance. How to get that?

**Comment by greyson-signal** [comment]
View > Debug Log > Submit

**Comment by uspoma** [comment]
Desktop instance: https://debuglogs.org/0e50618ad1eac3a235486711b8d756bbb392d9c4deff23293c5079fa28c5db87

@greyson-signal do you see a possible reason that could have lead to the spontaneous deletion?
