### ISSUE TITLE
Disable avatars feature request

### ISSUE THREAD

**Issue by marcinkorzycki** [signalapp/Signal-Android#8622]
### Bug description
It's rather a feature request. I want to disable all avatars in app. Most of my contacts has avatar which I want to disable because of security.

### Steps to reproduce
- Open Android App
- Look ad the contacts list

**Actual result:** Showing contacts avatar
**Expected result:** A switch in settings to disable avatars (show avatars, show only generic avatar, disable avatars at all)

### Device info
**Device:** OnePlus 5
**Android version:** 9.0
**Signal version:** 4.33.5

**Comment by greyson-signal** [comment]
Hi there! We only handle bug reports on Github. All feature requests should be discussed on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
