### ISSUE TITLE
GIFs cannot be added via Gboard

### ISSUE THREAD

**Issue by eugomat** [signalapp/Signal-Android#8626]
Same behavior as in #6187 except that no error message appears in portrait mode.
Signal version 4.33.5

**Comment by greyson-signal** [comment]
MMS messages have some pretty strict size limits. By default the size limit is 280kb, unless we can detect that your provider supports a higher limit. A lot of GIFs are going to be bigger than 280kb.

As far as the error not appearing, this was fixed in 4.34.x, which is currently in beta.

**Comment by the4ndy** [comment]
I also have this issue on a brand new Pixel 3 XL device, Google Fi is the carrier, Signal version is 4.37.2
I did NOT have this issue on my old Nexus 5x, same carrier / plan, same signal version
the android version on my Pixel 3 XL (9) is newer than the 5X (8.1.0)
