### ISSUE TITLE
SMS send via car voice system do not show up in signal message history

### ISSUE THREAD

**Issue by frogshaving** [signalapp/Signal-Android#8627]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My phone is connected to my car over bluetooth and it has to feature to use speech2text sms sending. I can use it by pushing a button and saying "send sms to $contact" and then add the text.
SMS send by this feature are send out correctly and received by the target.
But they will not appear in my signal SMS stream. All SMS send by car are invisble.

Signal messages and calls registered, SMS enabled, passphrase disabled

When I reset Google Messages as SMS app, these message are shown in the stream. Even if I change it back to Signal they do not appear.

### Steps to reproduce
- connect phone to car via bluetooth
- use car feature to send SMS (push button, say "send SMS to $contact" followed by $text
- SMS is send out, couterpart does even answer

**Actual result:** SMS send this way are not shown in Signal at all.
**Expected result:** SMS are shown in the contact's message stream like regular SMS send via phone directly.

### Screenshots
cannot make a screenshot of an invisible SMS

### Device info

**Device:** Blackberry KeyOne (BBB100-2)
**Android version:** 8.1.0
**Signal version:** 4.33.5

### Link to debug log
will attach if needed.

**Comment by greyson-signal** [comment]
There's a chain of these issue, see #8538.
