### ISSUE TITLE
Add message length (bytes) to the meta information in message context menu

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#863]
I cannot find the message data block size in the meta information, this should be added to the message context menu.

**Comment by McLoo** [comment]
As I just wanted to request for the media/attachment size info in message details, in stumbled upon this issue.

I don't think there is much use for a 'regular' user to have other information than the 
- attachment size 
- and maybe the character count

**Comment by Wikinaut** [comment]
perhaps also the 

* file creation date ?
