### ISSUE TITLE
Desktop Version 

### ISSUE THREAD

**Issue by Freudentaumel** [signalapp/Signal-Android#8631]
Probably this is not the right address for my request - then I would ask for indulgence:

Unfortunately I only have Windows 64-bit. What can I do to install the desktop version anyway? Maybe there is a workaround.

Many thanks for any help
Gerhard

**Comment by 2-4601** [comment]
Hi, yeah this tracker is for the Android client. To get help please come to the forum https://community.signalusers.org/c/support/desktop-support (you can sign up to the forum with your GitHub account)

**Comment by Freudentaumel** [comment]
I am sorry I cannot sign up to the forum with my GitHub account. What can be the reason for that?

**Comment by greyson-signal** [comment]
All Signal downloads can be found here: https://signal.org/download/
