### ISSUE TITLE
Single Character Contacts are not Included in Group Chat Contact Search

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#8632]
- [y] I have searched open and closed issues for duplicates
- [y] I am submitting a bug report for existing functionality that does not work as intended
- [y] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [y] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When starting a group conversation contacts with names that are one character long do not exist in the drop down list. You can still search for these contacts by entering their number or by bringing up the list of contacts that a user selects. 

### Steps to reproduce
- Create a contact `A` with a phone number.
- Search for `A` and see that no results are selectable.
- Repeat this process with `BC` instead of `A` and observe how `BC` is selectable.

**Actual result:** Contact `A` is not in the dropdown list. 
**Expected result:** `A` is immediately returned and the user can seamlessly add `A` to their group conversation.

**Comment by bitmold** [comment]
Ya

**Comment by greyson-signal** [comment]
I can't repro this. I set a single-letter name for a contact in the system contacts (in this case, 'G'), and that contact showed up in search results for 'G' everywhere I tested.
