### ISSUE TITLE
Audible indication missing during call.

### ISSUE THREAD

**Issue by arnSky** [signalapp/Signal-Android#8633]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While calling from Device A to Device B (using Signal),
there used to be a separate Sonar tone heard on `A` after dialing but before `B` started ringing,
this was very intuitive.

Now only single regular RingBack tone is heard, whether the other device is ringing or not.

and, ambiguous UI text does NOT help to determine the current call state.

### Steps to reproduce
Suppose calling target is `B` and caller is `A`
- Turn Off Internet on `B`
- call `B` from `A`

**Actual result:** 
Regular CallBack tone is heard with no audible indication on `A` that `B` is NOT ringing.

**Expected result:** 
Hear `Sonar` tone on device `A` as long as device `B` is NOT ringing,
and hear `Regular CallBack Tone` on `A` once device `B` starts ringing.

### Screenshots

N.A.

### Device info

**Device:** Moto X Play
**Android version:** 7.1.2
**Signal version:** 4.34.8

**Comment by 2-4601** [comment]
It was removed intentionally. See this post: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-33-release/5880/23

**Comment by arnSky** [comment]
@moxie0 @moxie-signal @2-4601 
this is still a regression.

Behaviorally `no one`(in my opinion)  looks at screen after making a call.
So currently the app is malfunctioning,
as it is not audibly informing the user that the other device is not ringing,

worse,

it is deceiving the user by audibly informing the caller that the other device is ringing.

**Comment by attila-lendvai** [comment]
discussion is at: https://community.signalusers.org/t/submarine-sound-gone-ring-sound-before-connection-made/6314/68
