### ISSUE TITLE
Add Day/Night theme

### ISSUE THREAD

**Issue by jony0008** [signalapp/Signal-Android#8634]
It is more pleasant to have a light theme during the day and a dark theme during the night. 

Please add a theme that will change depending on if it is day or night.

**Comment by greyson-signal** [comment]
Hi there, as mentioned in our issue template, we only use Github for bug reports. Please discuss feature requests in [the forum](https://community.signalusers.org/). Thanks!

**Comment by jony0008** [comment]
@greyson-signal I do not have time with this rule issue. I just wanted to make this request and this is how it is usually done on other Github projects. Sorry for not being interested in discussing this feature in another forum.
