### ISSUE TITLE
Addendum to Desktop Version #8631

### ISSUE THREAD

**Issue by Freudentaumel** [signalapp/Signal-Android#8635]
But this does not answer my question (see opening posting) in any way. 

My question about a workaround clearly indicates that. That's why I don't understand this answer at all.

**Comment by greyson-signal** [comment]
I'm confused. You said:

> Unfortunately I only have Windows 64-bit.

I sent you a link to a page where you can download Signal Desktop for Windows, and it supports 64-bit systems.

You can read more about this on [our support page](https://support.signal.org/hc/en-us/articles/360008216551-Installing-Signal).

If you misspoke and meant to say that _you_ don't have a 64-bit system, then maybe you can compile it yourself for 32-bit. I'm not sure. [Here's some instructions](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md). This is the Android repository, I'm the Android maintainer, and while I build my own Desktop distributions, I do so on Linux :)

Finally, as previously pointed out, Github is only for bug reports. For support inquiries, either ask your question on [the forum](https://community.signalusers.org/) or reach out to support@signal.org.

I'm closing and locking this issue. Please don't open another one (for this question, that is -- feel free to open an issue for an actual bug!). Use the channels I just mentioned.
