### ISSUE TITLE
Can't send message in groupchat

### ISSUE THREAD

**Issue by aliceell** [signalapp/Signal-Android#8636]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
Last night I tried to send a screenshot to a group chat of 2 other friends, both of whom use signal. The screenshot has been trying to send all night and still hasn't sent. 

Since I tried to send that screenshot, I haven't been able to send any other messages to that groupchat. They all get "stuck". I can send messages outside of that group chat, however. 

I made a new group chat and that ended up being a good workaround, but I thought this would still be good to report.

### Screenshots
Here's a screenshot of the picture I tried to send. I don't get any error message, just the "sending" circle symbol:
![image](https://user-images.githubusercontent.com/19187967/53354472-d3e9c780-38f4-11e9-99b6-2ea80177f3ed.png)

### Device info
**Device:** Samsung J7 Prime
**Android version:** 8.1.0
**Signal version:** 4.34.8

### Link to debug log
https://debuglogs.org/357cc7660c5fce169e0f0f67ff918b56b7ad6055167f69bbf13dfb0d3b38325d

**Comment by greyson-signal** [comment]
Merging this into #8602
