### ISSUE TITLE
Note to Self messages removed instantly if expire timer is set

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#8641]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending messages to Note to Self from the desktop client, messages are immediately removed from the phone (they are visible roughly ~100 ms, just flashing up very quickly). The same messages stay visible on other desktop clients, and also works as intended with the iOS app. This bug only appears if a message expire time is set; otherwise messages stay put as intended.

Same issue over at Signal-Desktop: https://github.com/signalapp/Signal-Desktop/issues/3142

Edit: A friend of mine have also confirmed the same behavior on Android 9.0 on a Oneplus 6T linked to a Windows 10 machine using the latest version of the Android and desktop client.

### Steps to reproduce
- Set the expire timer to any value (except off) in the Note to Self conversation.
- Send a message to the conversation from a desktop client.
- The message is removed right away on the Android client.

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.34.8

### Link to debug log
Android client debug log:
https://debuglogs.org/4d0c5def0b8c5ba2510cc64570deb50f6eb5c85920ee0e62582a3875b3c3af9e

Desktop client debug log:
https://debuglogs.org/56ca61d58a0b930398827c510d881d464a0960f2c87ebbb6dc626a48cc57f3f4

**Comment by greyson-signal** [comment]
I believe this is a desktop issue that's being worked on.

**Comment by greyson-signal** [comment]
Confirmed that this is a bug that's being fixed on desktop.

**Comment by petcap** [comment]
@greyson-signal Is this issue confirmed as a bug by someone working on the desktop client? I've done some debugging on the desktop client and the expire timer/read timestamp that is synced to the Android client seems fine. in addition, this is not a problem with the iOS client.
