### ISSUE TITLE
Sending photos prompt for permission to send/view SMS

### ISSUE THREAD

**Issue by pldg** [signalapp/Signal-Android#8642]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

---

### Bug description

When you try to send a photo to a contact, Signal prompt to *Allow Signal to send and view SMS messages*.

### Steps to reproduce

- Make sure Signal doesn't already have SMS permission enable
- Open a chat
- Click on the *Plus* icon on the bottom right corner
- Select *Gallery* or click on recent photos
- Select one or more photos
- Send the photo/s to your contact

**Actual result:** At this step Signal prompt for permission to send/view SMS.
**Expected result:** Signal should not ask for SMS permission to send photos. If this is the normal behavior can anyone explain me why?

### Device info

**Signal version:** 4.34.8

**Comment by greyson-signal** [comment]
Are you attempting to send an SMS message? The attachment/send button in the conversation screen would be grey. If so, we check at send time to verify that we're the SMS handler. Also, please post a link to a debug log (Settings > Advanced > Submit debug log).

**Comment by pldg** [comment]
I'm not sending an SMS, the *attachment* button is blue. There is a lot of data in the debug log. I'm not sure what kind of data I eventually share with you (I need time to inspect the log myself). I would like to select some text (or all text) inside the log but is not working. What's happen if I click the *submit* button? Is there an option to privately send the log to my email before make it public? Thanks!

**Comment by greyson-signal** [comment]
When you submit a log, it gets uploaded to a storage bucket, and you're provided a link to it. To find your specific log, we'd need the link. If you don't want to post this link on github, you can send it to greyson@signal.org.

As far as contents, the log describes what kind of things happen while excluding sensitive details. For example, the log would contain whether a message was successfully sent, but it wouldn't log the message contents, and all phone numbers are truncated to the last two digits.
