### ISSUE TITLE
When missing a phone, there is no log in the app. Only push notification.

### ISSUE THREAD

**Issue by nmacchitella** [signalapp/Signal-Android#8643]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When missing a call, there is no log to show that in the app. Only a push notification.

### Steps to reproduce
-miss a call on signal

### Device info
Pixel 3
**Device:** google

**Comment by greyson-signal** [comment]
Can you elaborate? When you miss a call, there's a "missed call" message that gets added to the conversation. Just tested it on my Pixel 3 and it worked. Are you not seeing this?
