### ISSUE TITLE
Muted Group Chats Receiving Sound & Notifications

### ISSUE THREAD

**Issue by phobes** [signalapp/Signal-Android#8647]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- After locking Signal, muted group chats continue to give sound and notifications intermittently
- Happens from unknown recipients as well as recipients in my contacts
- I have disabled the lock feature and will test to see if it persists
- All volumes on the phone are muted save for multimedia
- Phone is _never_ on vibrate/sound disabled

### Steps to reproduce
- Mute group chat
- Lock Signal
- Receive message in the group chat

**Actual result:**
**_Intermittent_** - Receive message in muted group chat, sound and visual notifications still occur

**Expected result:** 
Receive message in muted group chat, no sound or visual notification occurs

### Device info
**Device:** Samsung Galaxy S9 (SM-G960U)
**Android version:** 9
**Signal version:** 4.34.8

### Link to debug log
https://debuglogs.org/c0a902aab991302bf3bd1283fa25e79cfc9f8e2d685a4240a6d6a946d2823b3f

**Comment by jimbudarz** [comment]
I agree, this continues to be an issue. It appears that notification for the incoming message occurs before the app realizes it's an MMS as part of a group chat. When I click the notification, I'm brought to my conversation history with that individual sender, not the group chat conversation history.

**Comment by phobes** [comment]
> I agree, this continues to be an issue. It appears that notification for the incoming message occurs before the app realizes it's an MMS as part of a group chat. When I click the notification, I'm brought to my conversation history with that individual sender, not the group chat conversation history.

This appears to have been fixed for me, how about you @jimbudarz ?

**Comment by jimbudarz** [comment]
> > I agree, this continues to be an issue. It appears that notification for the incoming message occurs before the app realizes it's an MMS as part of a group chat. When I click the notification, I'm brought to my conversation history with that individual sender, not the group chat conversation history.
> 
> This appears to have been fixed for me, how about you @jimbudarz ?

I haven't noticed this bug in a long time.

**Comment by phobes** [comment]
Seems like this has been solved, closing!
