### ISSUE TITLE
Artifacts at some emoji icons

### ISSUE THREAD

**Issue by pankarlox** [signalapp/Signal-Android#8651]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some of the emoji available in Signal are displayed with the artifact on the left.
It was similar in the older editions of Signal. Closed issue [#5973](https://github.com/signalapp/Signal-Android/issues/5973#issue-196316979)
### Screenshots

1. Emoji in list selection

![signal-attachment3](https://user-images.githubusercontent.com/44022879/53699589-46254500-3dea-11e9-873c-a0ad3a4f7908.jpeg)

2. Emoji in conversation

![signal-attachment7](https://user-images.githubusercontent.com/44022879/53699702-8507ca80-3deb-11e9-8a1f-f8f3b45e2b9b.jpeg)

### Device info

**Device:** Samsung Galaxy S9
**Android version:** 9.0
**Signal version:** 4.34.8

**Device:** Samsung Galaxy A5 2016
**Android version:** 7.0
**Signal version:** 4.35.1 Beta

**Comment by u32i64** [comment]
Reproducible as well on:

**Device:** Pixel 3 XL
**Android version:** 10
**Signal version:** 4.59.1

It looks like there's some issue cutting the emojis from the spritesheet format in which they are distributed with the app.
