### ISSUE TITLE
Received date is earlier than Sent date on messages received from iPhone Signal user

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#8652]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Signal messages received from an iPhone user, the received date shown is earlier than the sent date.
#3289

### Steps to reproduce
Automatic date & time
Automatic time zone

- Received Signal message from iPhone user
- View message info

**Actual result:** Received date is earlier than sent time

**Expected result:** Received date should always be after sent date

### Screenshots
![signal_msg_received_earlier_sent](https://user-images.githubusercontent.com/5124946/53709270-3e3bc400-3e2f-11e9-979f-6428463a71e6.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 9
**Signal version:** 4.34.8

**Comment by danmazzella** [comment]
A Signal employee can correct me if I'm wrong, but I assume the "Sent" timestamp comes from the other user's device (in this case the iPhone) and the "Received" timestamp comes from your device.

If my assumption is correct, it could just be that the device time on either of the devices is a few seconds off from the other which results in the strangeness you are seeing.

**Comment by greyson-signal** [comment]
Yes, it is likely that your clocks differ.
