### ISSUE TITLE
Toolbar overlaps status bar on PassphrasePromptActivity (Pixel 3 XL)

### ISSUE THREAD

**Issue by danmazzella** [signalapp/Signal-Android#8653]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The device Pixel 3 XL has a larger status bar than most normal devices. When you lock the signal app, the lock screen toolbar doesn't have a large enough margin on top, and in return overlaps the status bar.

### Steps to reproduce
- Using a Pixel 3 XL (Or any Pie 9.0 device with "Simulate a display with a cutout" set to "Tall display cutout)
- Go to settings -> privacy -> enable "Screen lock"
- Lock the app either via inactivity timeout or notification
- Open the app and you should see the locked screen

**Actual result:**
The toolbar and status bar are overlapping with each other.
![image](https://user-images.githubusercontent.com/3845551/53747559-87146c80-3e71-11e9-8e79-8e9ae40bad0c.png)

**Expected result:**
The toolbar should be below the status bar.
![image](https://user-images.githubusercontent.com/3845551/53747595-9e535a00-3e71-11e9-8222-0bab0281d5c3.png)

### Screenshots
See above

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 9
**Signal version:** 4.35.1

### Link to debug log
N/A

**Comment by danmazzella** [comment]
This is also an issue on the RecipientPreferenceActivity:
![image](https://user-images.githubusercontent.com/3845551/53767356-944a4f00-3ea3-11e9-9bdc-b4236c609cf6.png)

**Comment by DuckyCrayfish** [comment]
I have fixed the RecipientPreferenceActivity in #9007. 

Your MR resolves status bar height in a deprecated way. A better way of resolving this issue could be to do away with the transparent status bar and navigation bar. I have this working in a private branch that I have yet to create a MR for. To keep it pretty, the navigation bar can be styled white or black, to match the theme. Thoughts?

**Comment by DuckyCrayfish** [comment]
This issue has been resolved on the Contact Settings activity (RecipientPreferenceActivity), but not the Signal Lock activity (PassphrasePromptActivity).

**Comment by DuckyCrayfish** [comment]
Issue no longer exists and can be closed.
