### ISSUE TITLE
Crash making or receiving calls since mandated upgrade to 4.33.5

### ISSUE THREAD

**Issue by BugScribe** [signalapp/Signal-Android#8655]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a forced upgrade to 4.33.5 about very recently (the Signal app announced it would no longer work otherwise), it has been impossible to make or receive voice calls with the Signal app.

The app has been used on the device for years prior. Same device no changes.

#### For crash on MAKING a call
- Open Signal
- Select a contact from conversation list
- Press call icon to initiate call to contact 

**Actual result:**
  - The dialing screen is displayed as usual with the status "DIALING"
  - Signal crashes and the "Unfortunately, Signal has stopped." message is displayed
  - "You called" notification is added to conversation history
  - Attempts to redial immediately result in a "BUSY" status on the dialing screen.
  - This "BUSY" behaviour persists for some time before reverting to the crashing again

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
  - The dialing screen is displayed as usual with the status "DIALING"
  - The dialing screen status changes to "RINGING" and starts to ring
  - Call is connected when contact answers

#### For crash on RECEIVING a call
- Place a call to the affected Signal device (ask a contact to do so)

**Actual result:**
  - Signal crashes and the "Unfortunately, Signal has stopped." message is displayed
  - Signal does not always crash curiously (perhaps related to "BUSY" state seen after calling crash)
  - Missed call notification is NOT added to conversation history

**Expected result:**
  - The incoming call screen is displayed
  - Call is connected when it is answered

### Device info

**Device:** Motorola Moto G xt1033
**Android version:** 4.4.4
**Signal version:** 4.33.5

### Link to debug log
https://debuglogs.org/c07848e47d96279a647ee3b7a9b6d161e22ca0fbde34cba5fe0e50b1a331f330

https://debuglogs.org/7bb11671b60636d1969f57d5f4790150113dc3768538988bae5f77c59cf0d545

**Comment by BugScribe** [comment]
Just tried the 4.34.8 update. Same result.

**Comment by danmazzella** [comment]
I'm testing 4.35.1 on an Emulator running 4.4.2 and I am unable to reproduce the issue. I will continue to see if I can reproduce it myself and see if I can determine the cause.

**Comment by danmazzella** [comment]
Seeing a few connection errors in the second debug log.

`2019-03-0304 17:16:00.144 GMT+00:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+**********08 
2019-03-0304 17:16:00.173 GMT+00:00 W WebRtcCallService: null 
2019-03-0304 17:16:00.173 GMT+00:00 W WebRtcCallService: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname 
`

`2019-03-0304 17:17:45.703 GMT+00:00 W RetrieveProfileJob: java.io.IOException: No connection! 
2019-03-0304 17:17:45.703 GMT+00:00 W RetrieveProfileJob: at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:154) 
`

@BugScribe Are you having any connection issues with other apps on the affected device?

**Comment by BugScribe** [comment]
> 
> Seeing a few connection errors in the second debug log.
> 
> [...]
> 
> @BugScribe Are you having any connection issues with other apps on the affected device?

@danmazzella : No. Signal text messaging works fine on device. As do other apps that rely on connectivity e.g. Firefox, Play Store etc

**Comment by BugScribe** [comment]
I'm seeing references to `Camera1Enumerator` in the logs despite the fact that I'm trying to make and receive Signal voice calls only.

Does Signal 4.33.5 and later access the camera before/during the call setup phase by any chance? Is this a change from previous versions?

**Comment by BugScribe** [comment]
Does there exist an instrumented debug version of Signal versions 4.33.5 or 4.34.8?

No surreptitious data submissions though. Local file that I manually submit.

**Comment by BugScribe** [comment]
The crash seems to be represented by these lines in the debug logs (from the second linked log above). 

```
I/WebRtcCallService( 2387): a=fingerprint:sha-256 D8:B6:58:48:56:6A:45:C4:B7:EB:6A:5F:9A:5C:86:03:E3:99:46:9A:24:F5:0B:FC:71:4E:91:81:FA:74:1B:F9
I/WebRtcCallService( 2387): a=setup:active 
I/WebRtcCallService( 2387): a=mid:data 
I/WebRtcCallService( 2387): a=sctpmap:5000 webrtc-datachannel 1024 
I/WebRtcCallService( 2387): 
I/UnidentifiedAccessUtil( 2387): Their access key present? true | Our access key present? true | Our certificate present? true 
D/IncomingMessageObserver( 2387): Network requirement: true, app visible: true, gcm disabled: false
I/WebRtcCallService( 2387): onSignalingChange: STABLE
I/IncomingMessageObserver( 2387): Reading message... 
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0 
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0 
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0 
I/org.webrtc.Logging( 2387): WebRtcAudioTrack: initPlayout(sampleRate=48000, channels=1) 
I/org.webrtc.Logging( 2387): WebRtcAudioTrack: byteBuffer.capacity: 960 
I/org.webrtc.Logging( 2387): WebRtcAudioTrack: AudioTrack.getMinBufferSize: 3840
W/WebSocketConnection( 2387): WSC onMessage() 
W/WebSocketConnection( 2387): Message Type: 1 
I/IncomingMessageObserver( 2387): Retrieved envelope! 
I/org.webrtc.Logging( 2387): WebRtcAudioTrack: AudioTrack: session ID: 12, channels: 1, sample rate: 48000, max gain: 1.0 
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0
I/OMXClient( 2387): Using client-side OMX mux. 
V/Cursor ( 2387): Filling cursor window with start position:0 required position:0 
E/OMXMaster( 2387): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one. 
I/OMXClient( 2387): Using client-side OMX mux.
I/OMXClient( 2387): Using client-side OMX mux. 
E/OMXMaster( 2387): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one. 
E/OMXNodeInstance( 2387): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
W/OMXNodeInstance( 2387): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed 
I/OMXClient( 2387): Using client-side OMX mux. 
E/OMXMaster( 2387): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
W/System.err( 2387): java.lang.IllegalArgumentException 
W/System.err( 2387): at android.media.MediaCodecList.getCodecCapabilities(Native Method) 
W/System.err( 2387): at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:291)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.isSupportedCodec(MediaCodecVideoDecoderFactory.java:122)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.findCodecForType(MediaCodecVideoDecoderFactory.java:106)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.createDecoder(MediaCodecVideoDecoderFactory.java:53)
W/System.err( 2387): at org.webrtc.HardwareVideoDecoderFactory.createDecoder(HardwareVideoDecoderFactory.java:16)
W/System.err( 2387): at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:45)
W/System.err( 2387): at dalvik.system.NativeStart.run(Native Method)
E/rtc ( 2387): 
E/rtc ( 2387): 
E/rtc ( 2387): # 
E/rtc ( 2387): # Fatal error in: gen/sdk/android/generated_base_jni/jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 38 
E/rtc ( 2387): # last system error: 2 
E/rtc ( 2387): # Check failed: !env->ExceptionCheck() 
E/rtc ( 2387): # 
F/libc ( 2387): Fatal signal 6 (SIGABRT) at 0x00000953 (code=-6), thread 3642 (worker_thread)
I/OMXClient( 2387): Using client-side OMX mux. 
W/WebSocketConnection( 2387): WSC onMessage() 
W/WebSocketConnection( 2387): Message Type: 1
D/ActivityThread( 3804): handleBindApplication:org.thoughtcrime.securesms 
D/ActivityThread( 3804): setTargetHeapUtilization:0.75 
D/ActivityThread( 3804): setTargetHeapMinFree:2097152 
I/MultiDex( 3804): VM with version 1.6.0 does not have multidex support 
I/MultiDex( 3804): Installing application
I/MultiDex( 3804): MultiDexExtractor(/data/app/org.thoughtcrime.securesms-2.apk, /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes)
I/MultiDex( 3804): Blocking on lock /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/MultiDex.lock
I/MultiDex( 3804): /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/MultiDex.lock locked 
I/MultiDex( 3804): MultiDexExtractor.load(/data/app/org.thoughtcrime.securesms-2.apk, false, ) 
I/MultiDex( 3804): loading existing secondary dex files
I/MultiDex( 3804): load found 1 secondary dex files
```


Any ideas why this has started happening with the newer releases of Signal?

These lines in particular seem to be implicated:

```
I/OMXClient( 2387): Using client-side OMX mux. 
E/OMXMaster( 2387): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one. 
E/OMXNodeInstance( 2387): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
W/OMXNodeInstance( 2387): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed 
I/OMXClient( 2387): Using client-side OMX mux. 
E/OMXMaster( 2387): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
W/System.err( 2387): java.lang.IllegalArgumentException 
W/System.err( 2387): at android.media.MediaCodecList.getCodecCapabilities(Native Method) 
W/System.err( 2387): at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:291)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.isSupportedCodec(MediaCodecVideoDecoderFactory.java:122)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.findCodecForType(MediaCodecVideoDecoderFactory.java:106)
W/System.err( 2387): at org.webrtc.MediaCodecVideoDecoderFactory.createDecoder(MediaCodecVideoDecoderFactory.java:53)
W/System.err( 2387): at org.webrtc.HardwareVideoDecoderFactory.createDecoder(HardwareVideoDecoderFactory.java:16)
W/System.err( 2387): at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:45)
W/System.err( 2387): at dalvik.system.NativeStart.run(Native Method)
E/rtc ( 2387): 
E/rtc ( 2387): 
E/rtc ( 2387): # 
E/rtc ( 2387): # Fatal error in: gen/sdk/android/generated_base_jni/jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 38 
E/rtc ( 2387): # last system error: 2 
E/rtc ( 2387): # Check failed: !env->ExceptionCheck() 
E/rtc ( 2387): # 
F/libc ( 2387): Fatal signal 6 (SIGABRT) at 0x00000953 (code=-6), thread 3642 (worker_thread)
```

It is worth iterating that voice calls worked fine until the forced update to 4.33.5. Unfortunately, I did not record the version I was using prior to the 4.33.5 upgrade. No reason to do so normally.

**Comment by danmazzella** [comment]
Yes, you're right. That is definitely what seems to be causing the crash.

I'm wondering if ExoPlayer or another library that is used for calling was upgraded to a newer version which is causing the issue. I looked through issues reported on the ExoPlayer GitHub and seems a few people have reported the same issue on older devices.

Possibly this change in v4.33.0
![image](https://user-images.githubusercontent.com/3845551/53894578-54e44580-3ffe-11e9-966f-d739484a8d63.png)

**Comment by BugScribe** [comment]
@danmazzella 

Is this ExoPlayer or other library also used for the GIF functionality?. I have also discovered that the GIF functionality is broken too. Merely opening up the GIF Activity and scrolling results in a crash. This was working prior to the forced upgrade to 4.33.5 too. 

Should I update the original bug report or create a new issue for the GIF crashing behaviour?

**Comment by greyson-signal** [comment]
Here's the crash:

```java
W/System.err( 2387): java.lang.IllegalArgumentException
W/System.err( 2387): 	at android.media.MediaCodecList.getCodecCapabilities(Native Method)
W/System.err( 2387): 	at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:291)
W/System.err( 2387): 	at org.webrtc.MediaCodecVideoDecoderFactory.isSupportedCodec(MediaCodecVideoDecoderFactory.java:122)
W/System.err( 2387): 	at org.webrtc.MediaCodecVideoDecoderFactory.findCodecForType(MediaCodecVideoDecoderFactory.java:106)
W/System.err( 2387): 	at org.webrtc.MediaCodecVideoDecoderFactory.createDecoder(MediaCodecVideoDecoderFactory.java:53)
W/System.err( 2387): 	at org.webrtc.HardwareVideoDecoderFactory.createDecoder(HardwareVideoDecoderFactory.java:16)
W/System.err( 2387): 	at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:45)
W/System.err( 2387): 	at dalvik.system.NativeStart.run(Native Method)
```

The relevant bit of code (MediaCodecVideoDecoderFactory#isSupportedCode):
```java
private boolean isSupportedCodec(MediaCodecInfo info, VideoCodecType type) {
    String name = info.getName();
    if (!MediaCodecUtils.codecSupportsType(info, type)) {
      return false;
    } else if (MediaCodecUtils.selectColorFormat(MediaCodecUtils.DECODER_COLOR_FORMATS, info.getCapabilitiesForType(type.mimeType())) == null) {
      return false;
    } else {
      return this.isWhitelisted(name) && !this.isBlacklisted(name);
    }
  }
```

The problem is that `MediaCodecUtils.codecSupportsType(info, type)` returns true, even though it doesn't _really_ support it. And because it doesn't _really_ support it, `info.getCapabilitiesForType(type.mimeType())` crashes with an IllegalArgumentException. 

The above snippet comes from the WebRTC library, so not our code. We can see if they've released a patch.

P.S. This has nothing to do with ExoPlayer. That's our media player, which isn't used during video calls. This is likely the result of us updating WebRTC, which is a different thing. That said, this crash isn't really showing up in the

**Comment by greyson-signal** [comment]
@BugScribe 

> I have also discovered that the GIF functionality is broken too. Merely opening up the GIF Activity and scrolling results in a crash.

Open a separate ticket with a debug log.

> Does Signal 4.33.5 and later access the camera before/during the call setup phase by any chance? Is this a change from previous versions?

We don't turn on or transmit any camera data if video isn't enabled, but as part of the setup process, WebRTC does check things like which Camera API's are supported and what video codecs are supported so that both members of the call can agree on what type of data will be transmitted. That's probably why you see logs related to the camera, and that's also why video codec capability checks are crashing. This isn't new -- it's likely the code that does the checks changed in the new WebRTC release.

Follow-up question though: Is your device rooted, or otherwise altered in some way? It's just interesting that low-level codec stuff like this would crash in a weirdly-inconsistent way.

**Comment by BugScribe** [comment]
> Here's the crash:
> 

Thank you @greyson-signal. Apologies for not replying earlier. Internet access issues.

> [...]
> 
> The problem is that `MediaCodecUtils.codecSupportsType(info, type)` returns true, even though it doesn't _really_ support it. And because it doesn't _really_ support it, `info.getCapabilitiesForType(type.mimeType())` crashes with an IllegalArgumentException.
> 
> The above snippet comes from the WebRTC library, so not our code. We can see if they've released a patch.

This looks like it needs some code added to catch that exception. Would it be presumptuous to hope that one of you fine people on the Signal team might contribute a fix to the WebRTC library project? Pretty please?

> P.S. This has nothing to do with ExoPlayer.

Ok, understood.

> Follow-up question though: Is your device rooted, or otherwise altered in some way? It's just interesting that low-level codec stuff like this would crash in a weirdly-inconsistent way.

Yes, it is rooted.

**Comment by BugScribe** [comment]
This issue is still present in the 4.38.3 update. Very frustrating as Signal is....well....basically just TextSecure now...

Does the Signal team plan to contribute a bug report or a fix to the WebRTC library project?

**Comment by BugScribe** [comment]
This issue #8676 from Mar 10 seems to be related.
