### ISSUE TITLE
A few small problems while searching for keywords in conversation

### ISSUE THREAD

**Issue by pankarlox** [signalapp/Signal-Android#8657]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

A few problems I came across while searching inside the conversation

### **1. No yellow marks**

- ### Bug description

The keywords, which has a special character at the beginning, even though it has found the keywords in the search results, is not marked yellow (e.g. &Signal, etc.)

- ### Screenshots
As shown in the screenshot below, after searching for "Signal", the search result shows 8 finds. They should mark all found results in yellow.

![signal1](https://user-images.githubusercontent.com/44022879/53726553-7a424980-3e6e-11e9-86fa-01ed7ba48c24.jpeg)

### **2. No search results for a keywords with a number at the beginning**

- ### Bug description

Does not find keywords that have a number at the beginning (e.g. 3Signal, etc.)

- ### Expected result

All keywords should be found and marked, also with a digit at the beginning of the keyword.

- ### Screenshots

![signal2](https://user-images.githubusercontent.com/44022879/53739403-f4d09080-3e91-11e9-8f9f-ca85d8193590.jpeg)

### **3. Infinite search**

- ### Bug description
When you touch the search icon on the keyboard, the application searches for a keywords indefinitely.

- ### Expected result
After some time, a message about the number of results found should appear or, if there is no matching keywords, display the message 'Not found'.

- ### Screenshots
In the screenshot below you can see the results search animation, which has no end.

![signal3](https://user-images.githubusercontent.com/44022879/53739782-edf64d80-3e92-11e9-8da6-8fe53bc6b3b4.jpeg)

### **4. No yellow marking of all searched keywords**

- ### Bug description
No underscore for more identical searched keywords in the message.

- ### Screenshots
![signal4](https://user-images.githubusercontent.com/44022879/53740055-960c1680-3e93-11e9-8ef4-760f1fd8f866.jpeg)

- ### Expected result:
Each keyword searched in the message should be underlined (the screenshot below shows the result of the search for the keywords 'Signal' in WhatsApp).

![signalvswhatsapp](https://user-images.githubusercontent.com/44022879/53804540-14c28b80-3f48-11e9-9a7e-f5297cd07f2d.jpeg)

### **5. Does not search for special characters**

- ### Bug description
When searching for special characters (e.g. #, @, / etc.), it does not display search results, but the results are highlighted in yellow. There is also no temporary underlining of the message when a keyword is found.

- ### Expected result:
Search engine knows the special characters in messages, highlights them and displays the number of keywords found.

- ### Screenshots
![signal5](https://user-images.githubusercontent.com/44022879/53916336-40d22f80-4062-11e9-9938-d22b4eb3b30c.jpeg)

### Device info

**Device:** Samsung Galaxy A5 2016 (SM-A510F)
**Android version:** 7.0
**Signal version:** 4.35.1 Beta

**Comment by Meteor0id** [comment]
I would add

6. Not possible to jump from last result to first result or vice versa

7. Numbering is inverted:
The numbering of results would give more clarity about which message you are viewing if the result from the most recent message had the highest number, and the result from the oldest message had the lowest number.
