### ISSUE TITLE
Add status symbols for messages

### ISSUE THREAD

**Issue by floville** [signalapp/Signal-Android#866]
Hello, 

if i send a message, i can´t see status of this message like "send", "receive" and "read". Can you at this feature in a future release?

Best regards from germany,
Florian

**Comment by SamHH** [comment]
@moxie0 I see you closed #2667 so I'm asking you here. What's the reasoning behind not doing this? Is it that it's not something you consider important enough to add right now, or something you're totally opposed to adding?

In trying to move friends and family away from alternatives a la WhatsApp the major hurdle has always been the lack of read receipts. Most people seem to like them and they're standard in most IM apps like WhatsApp, Facebook Messenger, et cetera. Why not add them, even if default is off?

**Comment by agrajaghh** [comment]
@SamHH please don't use github issues for discussions, you can have a look at the mailing list archive, there are already a lot of mails about this topic
