### ISSUE TITLE
Problem retrieving profile image from FireBaseDataBAse

### ISSUE THREAD

**Issue by senkuml** [signalapp/Signal-Android#8661]
Here is mine code. Mine picture is uploaded successfully inside database in users/image folder. But i can't get it back to profile view.

StorageReference filepath = UserProfileImageRef.child(currentUserId + ".jpg");
                filepath.putFile(resultUri).addOnCompleteListener(new OnCompleteListener<UploadTask.TaskSnapshot>() {
                    @Override
                    public void onComplete(@NonNull Task<UploadTask.TaskSnapshot> task)
                    {
                        if (task.isSuccessful())
                        {
                            Toast.makeText(SettingsActivity.this, "Profile picture uploaded successfully", Toast.LENGTH_SHORT).show();
                            final String downloadUrl = task.getResult().getStorage().getDownloadUrl().toString();
                            RootRef.child("Users").child(currentUserId).child("image")
                            .setValue(downloadUrl)
                            .addOnCompleteListener(new OnCompleteListener<Void>() {
                                @Override
                                public void onComplete(@NonNull Task<Void> task)
                                {
                                    if (task.isSuccessful())
                                    {
                                        Toast.makeText(SettingsActivity.this, "Image saved successfully", Toast.LENGTH_SHORT).show();
                                        loadingBar.dismiss();
                                    }
                                    else
                                        {
                                            String message = task.getException().toString();
                                            Toast.makeText(SettingsActivity.this, "Error :  " + message, Toast.LENGTH_SHORT).show();
                                            loadingBar.dismiss();
                                        }
                                }
                            });
                        }
                        else
                            {
                                String message = task.getException().toString();
                                Toast.makeText(SettingsActivity.this, "Error: " + message, Toast.LENGTH_SHORT).show();
                                loadingBar.dismiss();
                            }
                    }
                });
            }
        }
    }

**Comment by greyson-signal** [comment]
I don't think you're posting this on the correct repository. Signal doesn't use Firebase databases.
