### ISSUE TITLE
My SMS messages get converted to MMS

### ISSUE THREAD

**Issue by fact0real** [signalapp/Signal-Android#8664]
After updating Singal (4.35.1) when I try to send a long SMS (text only, no images, etc) it gets converted to MMS automatically. I do not see any options to disable this.

**Comment by mrenvoize** [comment]
Aha.. I think this is happening to me too now I look at the debug logs: https://debuglogs.org/e8abf93f6bc4bfbca679d260b1e9cdfcfeac21b9d393b4818534c7772c76d055

This fundamentally breaks the app for me, my contract does not support MMS at all and as such any message sent this way will fail forever with the horrible red exclamation mark and no details as to why the failure keeps happening.  I'm sure long text messages used to work properly.

**Comment by PiCob** [comment]
Thanks for fixing - too bad I didn't notice it on time. I just realized I already spent a few euros on MMS now... but I guess that's the price for being beta tester.
