### ISSUE TITLE
App crash all the time when trying to open conversation screen

### ISSUE THREAD

**Issue by iamnimnul** [signalapp/Signal-Android#8667]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crash all the time when trying to open chat window with a contact.

### Steps to reproduce
Scenario 1:
- Open app
- Click on any conversation on the main screen 
- App crash

Scenario 2:
After phone is restarted, android brought back notifications of incoming messages
- Slide down from top screen to see Notification List on android
- On the notification about new message for signal click "Mark as read"
- App crash

Yesterday app became crashing all the time. After night suddenly started working and I think it was until I received the first message in the morning, now crashing all the time again. I did a system update yesterday, might be related.

**Actual result:** App crash all the time.
**Expected result:** App must not crash ;)

### Screenshots
- no

### Device info
**Device:** One Plus 5
**Android version:** 9.0.4
**Signal version:** 4.34.8

### Link to debug log
https://debuglogs.org/6a8b9641544640ab5e9c7079dd3cd185df6cded6bb292bd3011a42a51a0ab286
https://debuglogs.org/876cb56aa9875edf9da59cfc2763c333dd80f4cc9a9a69e6729d926b60d5a7f8

**Comment by kpuljek** [comment]
This happened to me twice in the last 3 weeks, the application would just hang and I would have to force close it. The only thing that helped was rebooting the phone. (I also wiped the cache from the recovery, but that may have been unnecessary). Unfortunately I don't have any logs for it.

**Comment by iamnimnul** [comment]
@kpuljek I went to app info, "Forced stop", Cleared cache (not user data/storage) & restarted phone straight after this. Didn't help :/

**Comment by greyson-signal** [comment]
@iamnimnul Here's the relevant exception:

```java
03-06 23:58:40.930  6533  6533 E AndroidRuntime: Caused by: java.lang.SecurityException
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at com.android.internal.telephony.ISms$Stub$Proxy.isImsSmsSupportedForSubscriber(ISms.java:1422)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.telephony.SmsManager.isImsSmsSupported(SmsManager.java:1410)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.telephony.SmsMessage.useCdmaFormatForMoSms(SmsMessage.java:841)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.telephony.SmsMessage.useCdmaFormatForMoSms(SmsMessage.java:827)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:349)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:471)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.SmsCharacterCalculator.calculateCharacters(SmsCharacterCalculator.java:34)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOption.calculateCharacters(TransportOption.java:83)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.calculateCharactersRemaining(ConversationActivity.java:1895)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$9(ConversationActivity.java:1542)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.-$$Lambda$ConversationActivity$UINmr-72YWVkkq7TLW12rTkpE8Q.onChange(Unknown Source:2)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:182)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.reset(TransportOptions.java:52)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.SendButton.resetAvailableTransports(SendButton.java:76)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.handleSecurityChange(ConversationActivity.java:1203)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.initializeSecurity(ConversationActivity.java:1335)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.onCreate(ConversationActivity.java:344)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:51)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7149)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7140)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
03-06 23:58:40.930  6533  6533 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
```

Can you check if you have phone and/or sms permissions enabled in your system settings for Signal? If you don't, does enabling them stop the crash?

I believe OnePlus has a quirk where some methods (possibly `android.telephony.SmsMessage.calculateLength`) require phone/sms permissions, even though no other device does.

**Comment by kpuljek** [comment]
Signal has all the permissions and is the default/only SMS app on my phone

**Comment by iamnimnul** [comment]
@greyson-signal thanks! It fixed the issue on my phone after giving `SMS` and `Telephone` permissions!

**Comment by prateeknischal** [comment]
I had a similar issue, don't if it's entirely relevant. Sometimes the app crashes when i try to open a conversation. And then it will repeatedly crash for some time. Reboot, reinstallation nothing helps.. 

What has started helping me skip the bug Everytime is moving to a non-4G connection. When cell data moves to 3G the problem disappears. To immediately fix it, i just turn off the data.. enter the conversation and turn data back on.

**Comment by chatbarbie** [comment]
same problem as above described for me. (crashing when trying to enter any conversation)
all permissions granted (samsung s9+, march update)

can anyone help me?

https://debuglogs.org/d763929aa0b264271661747b8172dcdf3a214315326336374c329d68b9db0a54

**Comment by greyson-signal** [comment]
@chatbarbie Unfortunately I don't see any crashes in your logs.

**Comment by mqstout** [comment]
I've started getting this lately. (Maybe 2 weeks ago? Not most recent update as of this week, but one or two prior.)

I even crash if I'm at the signal home page and get a new SMS. I can read them fine, but I always have to mark everything as read first before I can get into any.

**Comment by greyson-signal** [comment]
@mqstout Please open a separate issue and include debuglogs. Thanks!
