### ISSUE TITLE
Include unsaved contact names/numbers in search results

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8668]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unsaved contact names `+Phone No. (~Contact Name)` don't appear in search results.

**Expected Result:**
Contacts must be searchable both by Phone No. & Name.

### Device info

**Signal version:** 4.35.2

**Comment by greyson-signal** [comment]
We now show contacts in search results if you've shared your profile with them.

**Comment by Xashyar** [comment]
@greyson-signal 
Hi, I tested this on **4.49.18**, and it simply doesn't work.

**Comment by greyson-signal** [comment]
We only include the unsaved contact if you have shared your profile with
them. If they aren't appearing, you might not have done that.

**Comment by Xashyar** [comment]
@greyson-signal 
There are some contacts which appear, and some which do **not**, in either case, I have sent the corresponding user a message (which should share my profile accordingly). I realize that there is no handler in the **Conversation settings** to do this manually. So what could be the solution in this scenarios?

Regards.
