### ISSUE TITLE
Tap & Hold for Insecure Calls

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Useful in conditions where either side (Caller or Recipient) don't have packet data as in **Insecure SMS** use cases.

**Expected result:** Tap & Hold the **Signal call** button for Insecure call.

### Device info

**Signal version:** 4.35.2

**Comment by greyson-signal** [comment]
As noted in the issue template, feature requests should be made on [the forum](https://community.signalusers.org/). Thanks!

**Comment by Xashyar** [comment]
@greyson-signal things happen really slow over there, just wanted to make sure it catches your attention.
