### ISSUE TITLE
Overlapping layers when editing Signal profile

### ISSUE THREAD

**Issue by pankarlox** [signalapp/Signal-Android#8670]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When setting up your Signal profile on smartphones **with smaller screens**, there is a problem of overlapping layers of text and graphics.

This problem does not happen on phones with larger screens. Issue occurs in the new registration process, as well as in the edition of the already registered Signal user.

### Steps to reproduce
- Go to 'Set up your profile'
- Select the edit field of the profile name

**Actual result:** When the keyboard appears, the layers of text and graphics overlap.
**Expected result:** There is no overlap between profile editing text and graphics.

### Screenshots

- Portrait mode

![signal3](https://user-images.githubusercontent.com/44022879/53990144-e26f8480-4127-11e9-9931-0f7842628356.png)

- Horizontal mode

![signal1](https://user-images.githubusercontent.com/44022879/53990160-ed2a1980-4127-11e9-9586-fb13416fedfa.png)

### Device info

**Device:** LG mini 2 (LG-D620r)
**Android version:** 5.0.2
**Signal version:** 4.35.2 Beta

**Device:** Alcatel OneTouch Idol 3 (4.7)
**Android version:** 6
**Signal version:** 4.35.2 Beta

**Comment by greyson-signal** [comment]
Also +1 for Adventure Time :)
