### ISSUE TITLE
[Meta proposal] Improve the Signalapp github repo: add a "[feature request]" report selection choice

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#8672]
Many other projects on Github offer - in addition to classic *bug* reporting - also ***feature request*** reporting.

Just one example:

![grafik](https://user-images.githubusercontent.com/1151915/54062875-225a6880-4209-11e9-8162-65e7f3cd925b.png)

The time is ripe to propose this improvement for the Signalapp repo, too.

It would be nice if you can drop your previous very strict policy and open your Github repo now also for feature requests.

**Comment by mlsxlist** [comment]
Is there a reason not to bring up this feature request at the signal community forum in the first place as the signal dev asked in the github issue template?

**Comment by Wikinaut** [comment]
@mlsxlist I placed my **meta** proposal to think again about a change in your previous very strict policy.

In my view there are many advantages using Github; it's much easier for everyone to have a single place of communication (github) for bugs *and* feature requests like in many other projects here like the shown nextcloud/server example and you can, a further bonus, quickly search for possibly related or already filed bugs (and features, once you open that here).

Here, on Github, you can simply cut & paste screenshots. link to commits and other bug or feature requests and get an auto-fill of usernames. Contributors can re-edit former postings to make a thread more concise. Many of these features are appears not to be available in the referred Signal Community Forum (SCF).

And Github unified login, markdown styling... I am very much used to that than to a different looking self-built tool (SCF). Yes, this is a personal view.

**Comment by greyson-signal** [comment]
I still believe that Github is best used as an issue tracker. Our forum is a much better place for discussion-heavy topics like feature requests. You're more than welcome to open a forum post there if you want to continue this discussion.
