### ISSUE TITLE
Switching language back to default switches the app to English, not to system default, until the app is restarted

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8673]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Switching language back to default switches the app to English, not to system default, until the app is restarted.

### Steps to reproduce
- My Android phone is set to Dutch as default language.
- I installed Signal, which assumes Dutch as its default language.
- In the language setting, the language is set to default (which means systemdefault)
- I switch the app language to English.
- The app is now English, I did not have to restart the app, the change was  applied immediately. So far so good.

- Leave the settings but stay within the app.
- Enter a group conversation and read some messages, no need to write any
- Now leave the conversation by going back to the conversation list.
- Open settings and navigate to language
- Switch the language back to default

- The app is still English! This is odd.
- I switch to Dutch
- The app is now in Dutch, I did not have to restart the app.
- I switch back to default.
- The app is now in English. Why?! My system default is Dutch. The app should be Dutch at this point.
- With the setting still on default, I restart the app. The app is now in Dutch.

**Important notice!**
If you don't leave settings before switching back to 'default', the bug does not occur, and the language does switch as expected. Only if you leave the setting and come back to them, does the language setting fail to apply on the next attempt.
I have been able to reproduce this bug on my device, but since I don't know exactly  what triggers it, I don't know if I will continue to be able to reproduce it when I advance my conversations.
Please let me know whether you have been able to reproduce this!

**Expected result:**
I expect the app language to immediately switch back to system default when I select default in the language menu. It is counter intuitive that switching to some options is applied immediately, but switching back to default takes a restart to take effect. This causes confusion.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9 (9.0?)
**Signal version:** 4.35.1

### Link to debug log
https://debuglogs.org/e07774d4e69b0e5244d44bd01c6855c9dc0b97f099cb919897f1418e183d3b93

**Comment by alan-signal** [comment]
4.36 included a rework of this whole language system. Please retry your steps to see if the issue is resolved.

**Comment by Meteor0id** [comment]
@alan-signal
Issue does not persist. Resolved.
