### ISSUE TITLE
Time of received message is shown in local time of sender instead of receiver

### ISSUE THREAD

**Issue by brakhane** [signalapp/Signal-Android#8674]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Time of a received message is shown in local time of the sender instead of local time of recipient

### Steps to reproduce
- Send a message to a person who is in a different time zone; for example, from CET to GMT
- Have the person reply to you

**Actual result:** Time of my message is shown as, eg. 13:00, and time of reply is shown as 12:01.

**Expected result:** Time of reply should be shown as 13:01

(The bug also exists on the Desktop App, where it's even more confusing at it will say that the reply to a message sent "1 minute ago" was received "1 hour ago")

**Comment by marcinadd** [comment]
I checked this issue and it exists. You can also set any date if you want and send message with this date. When you send message Signal add timestamp with System.currentTimeMillis() based on local time. I will try to fix it tomorrow. I think that the best way would be to get time from NTP Server and when phone is offline use fallback phone time.

**Comment by emilpaw** [comment]
> I think that the best way would be to get time from NTP Server and when phone is offline use fallback phone time.

Why is the senders time used? Wouldn't it be better if the receiver sets the time of the message when the message is actually received?

**Comment by greyson-signal** [comment]
"Sent timestamps" are created by the sender using a unix timestamp, which is timezone-independent. If it's showing as an hour in the past, the sender's clock is likely wrong. 

> Why is the senders time used? Wouldn't it be better if the receiver sets the time of the message when the message is actually received?

There's a lot of nuance to this, but basically we always order messages by their received timestamp, but show the sent timestamp on the bubble itself. You can also always access both in the message details.

>  I think that the best way would be to get time from NTP Server

Signal avoids trusting servers as much as possible -- I don't foresee us using an NTP server anytime soon.

**Comment by brakhane** [comment]
@greyson-signal Shouldn't the signal client trust it's own clock more than whatever timestamp the sender of a message claims?

IMO, Signal should show the time the message was received, not sent. Otherwise, a sender could claim he sent a message 5 hours in the past, and we would believe him.
