### ISSUE TITLE
"Retrieving a message" notification sometimes has the default icon

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8677]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The "Retrieving a message" notification sometimes has the default Signal icon:
![Screenshot_20190310-131116](https://user-images.githubusercontent.com/22525368/54085045-55037e80-4339-11e9-86bd-277c5b996fed.png)
This makes it undistinguishable from normal Signal notifications when using always-on displays where the notifications aren't colored and message content is replaced by "Content hidden".

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2
**Signal version:** 4.34.8

**Comment by greyson-signal** [comment]
The "sometimes" situation is shown in a different circumstance, and I don't think it's actually helpful in those situations. I'll probably just remove that stuff. Thanks :)
