### ISSUE TITLE
Sometimes the self-destruct timer doesn't start for messages high up in really long chats

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8679]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I didn't write any messages to a friend for about a day, and when I open the app I notice that two of her old messages are still around even though they are like a week old. It seems if you write enough messages, the timer doesn't start or perhaps resets if the messages are really high up in the chat.

Note that I've never seen this for a message that *I've* sent. Only for messages that *she* has sent.

### Steps to reproduce
I'm guessing something like
0. Set the SD-timer to 1 day
1. Write a lot of messages every day
2. Send a lot of pics every day
3. After about a week, wait for all messages to be deleted
4. You will now, if you're "lucky", see some old messages that are still around
5. The SD-timer will start for these messages and they will be deleted like 7 days too late

**Actual result:** The SD-timer seems to be stuck for some messages
**Expected result:** The SD-timer should *never* be stuck for any message

### Device info
Device : Google Pixel XL (marlin)
Android : 9 (5180536, PQ2A.190205.003) 
Memory : 36M (31.92% free, 512M max) 
Memclass: 256 
OS Host : wprf7.hot.corp.google.com 
App : Signal 4.35.2 

### Link to debug log
https://debuglogs.org/365685b203af81f5c29c8f3124f8250b6a98fa29cdc1dd59e389654408cd94f9
Message IDs:
Sent: 1551792031089
Received: 1551792708076

Sent: 1551801540752
Received: 1551804818455

Edit: Unless I'm doing something wrong, these IDs don't seem to be a part of the log at all :(
Pretty sure I saved the log right after I saw the old messages though.

### Related
https://github.com/signalapp/Signal-Android/issues/7356

**Comment by Dyras** [comment]
Update: A picture with text from March 12 has decided to permanently stay on my phone

https://debuglogs.org/be07e51b3c90b3b02d67cedb02a159bff838ad9acc028fb3c16cff54ac9d00e2
1552430395000

![image](https://user-images.githubusercontent.com/12563436/55275837-6e6e6980-52ec-11e9-9cb3-acce27e66c3a.png)

**Comment by Dyras** [comment]
Still happening

**Comment by Dyras** [comment]
@alex-signal I viewed them on Signal-Desktop. I would say that most of the time, I write on Signal-Desktop and the messages are only ever "stuck" on Signal-Android.

**Comment by alex-signal** [comment]
If you're at all able to get us fresh logs showing this, that'd be appreciated, the old logs have long since expired.

Desktop *should* be sending a read sync message out that should should start the timer on Android, regardless of whether you've viewed it on Android, so either that sync message isn't being sent or it's being dropped for some reason.

**Comment by Dyras** [comment]
Yes sir! Will close this and reopen if it happens again.
