### ISSUE TITLE
KeyStore exception - Hit a timeout waiting for the SMS verification

### ISSUE THREAD

**Issue by amandryka** [signalapp/Signal-Android#8680]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't register. The SMS validation code never comes through, nor does the robocall. The app doesn't display any error message.

### Steps to reproduce
- Launch Signal app
- Enter cell phone number
- Press the [Register] button
- Wait 5 minutes
- Press [Call me instead]
- Wait 5 minutes

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
No SMS comes though, no robocall comes through, no error message.
The debug log shows "KeyStore Exception" and doesn't show "Got SMS broadcast".
Note: I'm able to receive SMS from friends and validation codes from other apps.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
A SMS or a robocall., with the validation code should come through.

### Device info
**Device:** OnePlus 6T
**Android version:** OnePlus A6013_41_190123
**Signal version:** 4.34.8

### Link to debug log
Here is the log URL: https://debuglogs.org/0bc3bd2f38e4594ef8de266358cbce4c66e1999bd710b42b10442b9a993bddcb

Here is a thread on signalusers.org
https://community.signalusers.org/t/verification-registration-cant-get-sms-or-call-canada-bell/6672/4

**Comment by greyson-signal** [comment]
They KeyStore exception is a warning that's sometimes logged, but doesn't have any impact on the key generation.

The SMS broadcast log stuff is just whether or not Signal was able to detect (though some Google Play Services magic) the registration SMS. Regardless if we can detect it, it should still show up in your default SMS app, allowing you to manually enter the code. But it seems in this case you're not getting a code at all.

When it comes to not receiving SMS codes/calls, it's almost certainly a carrier-specific issue. @five-c-d has done a great job documenting a lot of stuff in #7980.

**Comment by amandryka** [comment]
I saw this thread and discussed it with escalated tech support from my carrier (Bell) but they said they never block SMS.

**Comment by five-c-d** [comment]
@amandryka , see comments in forum-thread here please, https://community.signalusers.org/t/verification-registration-cant-get-sms-or-call-canada-bell/6672/9 , we can see if we can further pin down the problem to the telco-phone-num, or to the handset.  

Also potentially related, there was a report from a OnePlus 5T enduser that, using a firewall-app, they were able to debug a registration problem where either their Qualcomm or their OnePlus portion of the android-OS, was blocking incoming SMS from twilio and/or signal-server, for some reason?  https://github.com/signalapp/Signal-android/issues/7980#issuecomment-471350594
