### ISSUE TITLE
Text panel and send button don't fit screen during sending images

### ISSUE THREAD

**Issue by chewiesGit** [signalapp/Signal-Android#8681]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The text panel and the send button when sending images do not fit the screen. They are only half visible at the bottom of the screen (with or without menu bar). It happens with every picture, so it is highly reproducible. 

### Steps to reproduce
- sending a picture 

**Actual result:** Text panel and send button are only half visible and do not fit the screen
**Expected result:** They should fit the screen to be fully visible

### Screenshots

![Capture+_2019-03-21-14-27-43](https://user-images.githubusercontent.com/37143576/54755178-acc9a180-4be5-11e9-9fe8-df87b19e3242.png)

### Device info

**Device:** LG G7 ThinQ LM-G710
**Android version:** 8.0.0
**Signal version:** 4.35.3

### Link to debug log

https://debuglogs.org/d65131e32916f477edecaee5cc035bfece9af195c923044451115fc1d5833cdf

**Comment by chewiesGit** [comment]
Here comes the screenshot:

![Capture+_2019-03-12-09-47-54](https://user-images.githubusercontent.com/37143576/54754272-63785280-4be3-11e9-85a5-6ca199752095.png)

**Comment by daltondr** [comment]
I'm having the same issue, with any attachment... but the problem is only in portrait screen orientation. Landscape displays correctly.

**Comment by chewiesGit** [comment]
Yes, can confirm that. In landscape orientation it displays correctly.

Do you also have a LG G7 ThinQ?

**Comment by daltondr** [comment]
Yep... LG G7. I'm currently on 4.40.3 version of Signal, but it's been happening for a few months. I'm not sure what update broke it.

**Comment by jlund-signal** [comment]
Does the LG G7 ThinQ have any notch-related settings that have been customized on a per-app basis or using the Developer options menu ("Display cutout")? Some phones like the Essential PH-1 have exhibited similar behavior in the past in non-default configurations.

**Comment by chewiesGit** [comment]
No, I dont use a different notch option for Signal. And I just checked wether it looks different for the other status bar option that is available on the G7, but it is the same behavior. Everything in Signal looks perfect except for the text panel for image descriptions.

**Comment by daltondr** [comment]
I don't think there is a per-app option to customize the notch area. There are settings, called the "new second screen", to customize the top of the screen. I verified that mine is set to "standard" vs "custom", but the problem persists either way.

**Comment by chewiesGit** [comment]
Now it works! Thanks!! The LG G7 Thinq also received an update to Android 9.0 recently. Maybe that is the reason why it works now? Anyway, very great!

**Comment by daltondr** [comment]
Still broken for me. Guess I have to wait for the update. :(
