### ISSUE TITLE
Media Gallery UI (Landscape Mode)

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

**Actual result:** The Header Toolbar Obfuscates the Full Screen View.
**Expected result:** Header Toolbar Should Fade Away with the Navigation Menu.
### Screenshots
![signal-attachment-2019-03-13-001821](https://user-images.githubusercontent.com/34171942/54235428-770e2400-4526-11e9-825e-46d9103cb5bf.png)

**Comment by jatinkumarg** [comment]
Hey, can I work on this?

**Comment by Xashyar** [comment]
> 
> 
> Hey, can I work on this?
👍

**Comment by jatinkumarg** [comment]
@Xashyar Just to be sure, do you want me to completely remove the Header Toolbar?

**Comment by Xashyar** [comment]
@jatinkumarg 
No, just that it should fade away by tapping on the underneath media (photo, video, etc.).

and I also suggest contacting @greyson-signal since the [PRs](https://github.com/signalapp/Signal-Android/pulls) rarely get merged.

**Comment by Xashyar** [comment]
@danmoop
Hi Danill, sorry for pinging you along, I thought this issue might be similar to #8915, would you mind taking a look as well? 

Thanks in Advance.

**Comment by danmoop** [comment]
@Xashyar Hello. Sure I checked the issue #8915. I think there is a solution to this problem, it will look like this:
``` java
@Override
  public void onConfigurationChanged(Configuration newConfig) {
    if(newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
      toolbar.hide(); // when landscape mode is on -> hide toolbar
    } else {
      toolbar.show(); // when we are back to portrait -> show toolbar
    }
  }
```
And the file that handles menu buttons is [this one](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/MediaPreviewActivity.java)
The problem is that I can't access toolbar. I can access buttons (save, forward, etc.) but **this box** I cannot. It wants to hide me :(

**Comment by Xashyar** [comment]
The issue no longer exists.
