### ISSUE TITLE
Back button doesn't work in forward view

### ISSUE THREAD

**Issue by jost-s** [signalapp/Signal-Android#8686]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Click on back arrow in forward view, nothing happens

### Steps to reproduce
- Tap and hold a conversation item (text or media)
- Tap forward arrow in appearing toolbar
- Tap back arrow

**Actual result:** nothing, not being taken back to conversation
**Expected result:** cancel forwarding and go back to conversation

### Device info

**Device:** Huawei P8
**Android version:** 6.0
**Signal version:** 4.34.8

### Link to debug log

https://debuglogs.org/863f942e016da173ee576f49e6020a5156deedb03194ce4b3b1693b11308d1dd

**Comment by greyson-signal** [comment]
This is fixed is an upcoming release. Thanks!
