### ISSUE TITLE
mtalk.google.com and signal

### ISSUE THREAD

**Issue by CrYpT0n1T3** [signalapp/Signal-Android#8687]
Question
Why does not it receive a message when it blocks calls to mtalk.google.com (firewall)?

**Comment by greyson-signal** [comment]
We don't make any calls to mtalk.google.com. I have no idea what your firewall rules are, but if you more broadly block google, you may be blocking [the url your Android distribution uses to check to make sure you _actually_ have internet](https://android.stackexchange.com/questions/123129/how-does-wifi-in-android-detect-if-the-device-has-to-sign-in-or-not). That could lead Signal to think that you have no network and therefore not make attempts to send/receive messages.
