### ISSUE TITLE
Unknown contact "is on Signal!" notifications

### ISSUE THREAD

**Issue by dbolton** [signalapp/Signal-Android#8688]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Very occasionally I get a message "[Name of person] is on Signal!" This is fine except at least 2 times it has been a person I don't know and that person is not in my normal phone contacts (I have searched by name and phone number).   

### Steps to reproduce
Use Signal for a year or two

**Actual result:** Random (unknown) people are announced as "on Signal!"
**Expected result:** I should only be notified if people in my contacts are "on Signal". 

### Device info

**Device:** LG G5
**Android version:** 8.0.0
**Signal version:** 4.35.3

### Link to debug log

https://debuglogs.org/8bf3a64f529a17cb2519488d6458c11fdbafc5da6ff5bcc3cb8af7a69567c2f3

**Comment by greyson-signal** [comment]
Those names are pulled from your contacts, not some remote location. If it shows a name, it means they're on your phone somewhere. Perhaps you have a corporate contacts directory linked to your phone?
