### ISSUE TITLE
SMS to friends who delete signal don't arrive

### ISSUE THREAD

**Issue by tgrrr** [signalapp/Signal-Android#8689]
Signal's great, kudos.

I'm using signal to manage my SMS.

## Steps to reproduce
1. I message friends using Signal, it works
2. My friend uninstalls signal on iOS and Android
3. I delete all messages from my friend
4. I send a new message to my friends, or reply to their SMS
5. The message is delivered to their Signal account, not their SMS inbox
6. They don't get the message

## expected action
- Detect when a user deletes Signal from their device
- Possibly email that user instructions if they change phones/no longer want to use signal
- Possibly provide an error notification to the sender
- Offer an option to send an insecure sms

**Comment by FeuRenard** [comment]
https://support.signal.org/hc/en-us/articles/360007321171-Can-I-send-SMS-MMS-with-Signal-#android_sms
You can long-press the send button and then choose to send an insecure SMS instead.

**Comment by greyson-signal** [comment]
It can take quite some time for FCM to tell us a user has uninstalled the app. Long-pressing to send SMS is the short-term solution, and you can also direct your friend to [unregister](https://signal.org/signal/unregister/).
