### ISSUE TITLE
Add option to add open contact in external contact manager and copy contact phone number

### ISSUE THREAD

**Issue by tgrrr** [signalapp/Signal-Android#8690]
I use Signal to open my sms

#### use case 1:

- I try to copy and share a contacts details
- I can't, so I use an external app

#### use case 2

1. I get an encrypted Signal message from a friend
2. I want to call them back without using Signal, because data means it can be a patchy call
3. Click on their avatar
4. I can only send them a message using Signal, or call them with signal
5. I try and copy their phone number to the clipboard, it isn't possible

So...

6. I open an external contact manager, search for my friend, and make the regular phone call.

## Expected behaviour

1. Click on a contact, there's an icon for an insecure phone call
2. Click and hold their phone number, and am presented with the ability to copy their number

**Comment by greyson-signal** [comment]
You can long-press their avatar in the conversation toolbar to go to their system contact page.
