### ISSUE TITLE
Quick Response Messages not sent via Signal

### ISSUE THREAD

**Issue by sybercorp** [signalapp/Signal-Android#8691]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Quick Response Messages, and messages sent via "alternative methods" are not displayed in Signal, or are not sent via Signal

### Steps to reproduce
- Send a message using an assistant app or as a response to an incoming call
- Check Signal for sent message (it won't be there)
- Check pretty much every other SMS messaging app installed for sent message (it WILL be there)

**Actual result:** Sent messages are not displayed in Signal
**Expected result:** ALL SMS messages should be shown in Signal (since it's the default messaging app)

### Device info

**Device:** Samsung Note 9
**Android version:** 9
**Signal version:** 4.35.3

### Link to debug log
https://debuglogs.org/ebd1b0b97f0c0e76c978da457b46735b1483cf714c9a29798860fff0a0ebaff0

**Comment by sybercorp** [comment]
I know this topic has been brought up a few previous times but none show any resolution or plans to fix this behavior (that I could find, at least).

**Comment by fajabird** [comment]
Hi, funny thing is that while signal is the default SMS app the quick replies will not show up in signal as mentioned above but when I open up the preinstalled SMS app, in my case google messages, and make it the default SMS-app after the fact, the quick reply SMS send previously will show up after some seconds. So its stored somethere and waiting for beeing picked up - right?

**Comment by Tursko** [comment]
Same issue here on a Note 8 running Signal 4.48.17.

I am an iPhone user so when he responds to my message via the Assistant, I get the message (so it sent correctly), but the message doesn't show in his thread. 

*On my iPhone I got a message from him that said 'Test' and I responded with 'Yes'. 'Test' was not shown on his thread.
![android-image-copy](https://user-images.githubusercontent.com/18274896/67637338-a2703400-f8a7-11e9-85af-32b3070202a8.png)


https://debuglogs.org/b8ab98b77254c573b632376b6bbd6bdd003ea2efc4ae75e026015436beba8472

**Comment by Tursko** [comment]
> Hi, funny thing is that while signal is the default SMS app the quick call response SMS will not show up in signal as mentioned above but when I open up the preinstalled SMS app, in my case google messages, and make it the default SMS-app after the fact, the quick call response SMS send previously will show up after some seconds. So its stored somethere and waiting for beeing picked up - right?

Have you tried it with another app like Textra? 

I hope they fix this bug soon, pretty essential for proper SMS support.

**Comment by Tursko** [comment]
Just picked up a pixel 4 and at the end of a call that wasn't answered you have the option to send them a quick message. The message sent also does not show up on the signal sms thread.

**Comment by a8underscore** [comment]
when i use google assitant to reply to a message it says that there was an error, it doesnt show up for signal message replys but scince signal is also used as my SMS app, reply shows up in sms threads, but assistant still says there was error, im not able to con firm if sms reply is actually sent though

**Comment by axman53** [comment]
Confirming that I am seeing the same issue with Quick Response Messages on my Samsung S21 Model SMG991U running Android 11, One UI v3.1, Signal 5.13.8.

**Comment by sybercorp** [comment]
Yes, it's still relevant.  And it's stale because no developers picked up the ticket to work the issue.

**Comment by Tursko** [comment]
> Yes, it's still relevant.  And it's stale because no developers picked up the ticket to work the issue.

You can reopen the issue.

**Comment by Tursko** [comment]
Closed again sadly.

**Comment by go2null** [comment]
Am a bit confused, it aeemsbit was implemented in TextSecure.
https://github.com/signalapp/Signal-Android/issues/299
