### ISSUE TITLE
"Error handling incoming message" error

### ISSUE THREAD

**Issue by alternativesurfer** [signalapp/Signal-Android#8693]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have one contact (who I have not sent messages to recently and whom has confirmed is not trying to send me messages) constantly have "Error handling incoming message" notices appear in my chat conversation with them.
ex. 
```
Error handling incoming message
SUN 1:36 PM

Error handling incoming message
SUN 1:38 PM

Error handling incoming message
SUN 2:21 PM

Error handling incoming message
SUN 2:25 PM

Error handling incoming message
SUN 2:30 PM

Error handling incoming message
SUN 3:45 PM

Error handling incoming message
SUN 4:43 PM

Error handling incoming message
SUN 5:05 PM

Error handling incoming message
SUN 8:54 PM

Error handling incoming message
```

### Steps to reproduce
Have Signal Messenger installed.
I literally do nothing to initiate, and neither does the other contact.

**Actual result:** 
Error is received
```
Error handling incoming message
SUN 8:54 PM
```
**Expected result:** 
Nothing should be received as no message is sent from either party

### Screenshots

![error handling message](https://user-images.githubusercontent.com/10135929/54565938-bf956980-498c-11e9-9f56-55ff494239d1.PNG)

### Device info
Device: Google Pixel (1)
Android version: 9 (eaf85d0306, lineage_sailfish-userdebug 9 PPR2.181005.003 eaf85d0306 test-keys) 
Signal version: 4.35.1
App state
Signal messages and calls registered, SMS disabled, passphrase disabled

### Link to debug log

https://debuglogs.org/c5e5c58a6b0de0b993eff246056141495e2b9427243bc52dda0de4d1ec5dac33

**Comment by greyson-signal** [comment]
Are you in a group with this person? I imagine that it could be that they're sending delivery receipts that aren't properly encrypted.

The short-term solution is to go to the conversation you have with this person > three dot menu > Reset secure session.

**Comment by megaturbo** [comment]
At least two of my contacts (I'm in group with them) have received a lot of these same messages. I also have two 

> Message encrypted for non-existing session

in my _Note to Self_ conversation.

I'm not sure, but this might be time correlated to when I opened [`signal-desktop-bin (1.25.1-1)`](https://aur.archlinux.org/packages/signal-desktop-bin/) on my computer (manjaro 4.19.45).

**Comment by lbehal** [comment]
I am also experiencing this on PC - together with high battery usage on mobile.

**Comment by DhruvaG2000** [comment]
> I am also experiencing this on PC - together with high battery usage on mobile.

+1 I am using signal on Pop OS 20.
