### ISSUE TITLE
Read receipts missing in SMS conversations

### ISSUE THREAD

**Issue by programjm** [signalapp/Signal-Android#8694]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Signal is the default SMS app, sent SMS messages never display delivered or read icons, even when the other person's phone allows read receipts. The problem does not occur when the other person is using Signal or when I am using another SMS app.

### Steps to reproduce
- Ensure Signal is the default SMS app
- Ensure read receipts are enabled in settings
- Open the app
- Send a SMS message to any person without Signal
- Verify through other means that the person has indeed opened the message in their messaging app

**Actual result:**

SMS messages always display the 'sent' icon, even when the message is delivered and explicitly read

**Expected result:** 

Each SMS message's icon changes to the delivered icon when the message is delivered and to the read icon when the message is read.

### Screenshots

Behaviour in **all** SMS conversations (i.e. with people with read receipts enabled):

![image](https://user-images.githubusercontent.com/1783464/54577442-db6b3080-49c9-11e9-9a8c-ba5cfea7ef18.png)

For reference, here is the behaviour when texting Signal users:
![image](https://user-images.githubusercontent.com/1783464/54577597-69dfb200-49ca-11e9-9776-4e3cd0074c75.png)

### Device info
**Device:** LGE LG-M320G (lv7_global_ca)
**Android version:** 8.1.0 (183371050e7a1, OPM1.171019.026)
**Signal version:** 4.35.3

### Link to debug log
https://debuglogs.org/3bf012ef6f3a2953c420098728e6a68776d28a053ef1284d357c9af3eae419e2

**Comment by greyson-signal** [comment]
SMS itself does not support the concept of read receipts. If the recipient does not have Signal or if you are not sending Signal messages, we do not have the ability to determine if a message is read.
