### ISSUE TITLE
Swipe message to cite it

### ISSUE THREAD

**Issue by ouzowtf** [signalapp/Signal-Android#8697]
I think it would be really handy if the citation of a message was also possible by right swiping the message.
That's what a lot of people I know found very handy when they were told this is possible in WhatsApp.

**Comment by Cerberus0** [comment]
Hi @ouzowtf,

Signal only uses GitHub for bug reports, not feature requests:

>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md

You can easily join the community forum with your existing GitHub account. This feature request is already being discussed and tracked here: https://community.signalusers.org/t/swipe-to-quote-and-reply/3654

**Comment by ouzowtf** [comment]
Thanks for clarifying and sorry for the inconveniences
