### ISSUE TITLE
forward button doesn't work

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8698]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I click forward button than I select the chat I want to forward it but it comes back to the first chat where I selected the photo I wanted to fwd. 

### Steps to reproduce
- select a photo in a chat
- click to forward the photo
- click the chat you want to fwd the photo to

**Actual result:** photo is sent to the person in the chat you took the photo
**Expected result:** photo should be sent to the chat you selected not to the one you selected the photo

### Device info

**Device:** pixel 2 XL
**Android version:** 9
**Signal version:** latest

### Link to debug log

Sent on Signal

**Comment by greyson-signal** [comment]
Can you be more specific with what flow you're using? List it out step by step. I have an identical device and can't repro.

I've tried forwarding text, images, albums, documents, etc. The forwarded message is always sent to the conversation that is selected in the "share with" screen.

**Comment by leonardoporp** [comment]
Sent you a video on signal

**Comment by greyson-signal** [comment]
I don't see it, but I have no idea which number you sent it to. I've posted test numbers on github in the past, but I swap them around and switch phones pretty frequently. You can send it to +1 610 839 7235.

**Comment by greyson-signal** [comment]
Talked offline - this is the side-effect of enabling "Don't keep activities", which is useful for catching certain classes of bugs, but I don't think this particular one is one of them. Thanks for your help @leonardoporp
