### ISSUE TITLE
Recent update to Signal makes it unclear who you're sending images to

### ISSUE THREAD

**Issue by reactionstudio** [signalapp/Signal-Android#8700]
Recently the UI for sending images to contacts on Signal has changed. Previously when sharing an image via signal, a thumbnail of an image you wanted to send would appear within the conversation you were posting it to, making it clear you were sending it to the correct person before you hit the send button.

Now the UI shows a full screen preview of the image with the option to enter text, if you select the wrong contact to send to by mistake in the previous step you will not realise your mistake until you hit the send button.

As a result, it makes it easier to send inappropriate or sensitive material to the wrong contact, the only way to resolve this is to delete the message before your image has finished uploading which can happen quickly in some cases.

This has happened to me twice now, a good solution would be to use the space in the upper left hand side of the full screen image preview which is currently blank to show the name, number and photo of the contact the image will be sent to, so you have the opportunity again to double check the contact and if you make a mistake you don't have to take the risk of not being able to delete the message in time.

**Comment by alan-signal** [comment]
Include Signal version information please.

**Comment by reactionstudio** [comment]
Signal v4.35.3

**Comment by greyson-signal** [comment]
This is addressed in the 4.36.x beta. The compose box will now be prefilled with "Send a message to {name}", which will help alleviate this problem.

**Comment by reactionstudio** [comment]
Thank you grayson, that sounds like it'll work. I'll wait for the new version to be released on play store.
