### ISSUE TITLE
Question "Do you wish to share your profile?" pop-up/banner suggest dismissing it is an option, but it is not.

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8701]
This bug has been reported a few times already and got closed every time:
#6927 was closed by an issue cleanup
#7605 was closed by Moxie after he simply stated that this is working as designed

I think the issue isn't that the message should be dismissable (it was consciously designed to not be dismissable) but the issue is that the text string is phrased as a question, making users think they are being asked a yes/no question. The text string is the issue, not the functionality. Don't ask people if they want chocolate and than only offer them the option to say yes.

So to clarify, yes, there have been similar reports before, but this one is different: I am suggesting to change the text string. I think the text string should be regarded as a bug, as it offers the user an option he doesn't have.

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

**Signal version:** 4.35.0

**Comment by Meteor0id** [comment]
Whether or not there should even be a pop-up is also open to debate.

The thing is: the user must have a saying whether and if yes when personally identifiable data will be shared with someone. If a stranger gets the users number, the users picture may not be shown as it confirms his identity. The user may not be able to reveal himself by accident as a consequence of adding the stranger to his address book.

So there should be some conscious user action to share the profile. Yet that choice should never fell forced.

The essence of the popup is: I trust this person to see my profile name and profile avatar. Sometimes that trust takes a few weeks to build, having the pop-up there all the time is annoying, and simply giving in to it to get rid of the banner before you trust that person might actually means the pop-up has pushed you to make a decision which compromises your identity.

**Comment by benboggart** [comment]
I'd like to support this request. 
I find it very irritating that throughout the years this has been criticised, moxie and others wrote plenty of formally dismissive responses, but the view of the developers on this became never clear to me:
Often this behaviour was considered a bug (rightfully I would say, as with my phone, the banner blocks about 1/5th of the screen ... permanently), but  at other instance it is apparently regarded a feature (e.g. https://github.com/signalapp/Signal-Android/issues/7605).

A fix would be greatly appreciated.

**Comment by Meteor0id** [comment]
Yup, its a clash between what users think they want, and how the developers want user to make use of Signal. There has to be a better way for the developers to guide users towards making their profile visible.

It is not ok to offer users a choice but put pressure on them by taking 1/5th of the screen hostage.

**Comment by mitchcieminski** [comment]
I strongly support this as well. I'm not sure if fixing the text string is the _only_ way to go about solving the problem, but it might be a start. Long-term, I would like this to be done as a feature request, which has been brought up several times [on the forums](https://community.signalusers.org/t/request-add-an-option-to-remove-the-nagging-make-your-profile-name-and-photo-visible-to-the-group-message/2311/7).

**Comment by donaldmorganjr** [comment]
I support this as well.

**Comment by I338** [comment]
Of course it would be better to have an actual choice other than the un-dismissable banner, but when I tested, it does work to just leave the profile blank and share that.

**Comment by Meteor0id** [comment]
This banner no longer exists (sadly). Your profile gets auto shared these days.
