### ISSUE TITLE
Upload document file have not process bar

### ISSUE THREAD

**Issue by FinderSig** [signalapp/Signal-Android#8703]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
upload document file have not process bar (Just document file, not picture etc.)

### Steps to reproduce
- every time when I share file

**Actual result:** have not process bar
**Expected result:** have process bar

### The code advice to change

add following code in file

`/src/org/thoughtcrime/securesms/components/DocumentView.java`

I found someone maybe forget to regisiter `EventBus` here

```java
  @Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    if (!EventBus.getDefault().isRegistered(this)) EventBus.getDefault().register(this);
  }

  @Override
  protected void onDetachedFromWindow() {
    super.onDetachedFromWindow();
    EventBus.getDefault().unregister(this);
  }
```

**Comment by Sgn-32** [comment]
File upload has a progress wheel (since ?).

![Screenshot_1607538150](https://user-images.githubusercontent.com/49990901/101670905-12ae2a80-3a54-11eb-9960-04f13fd1ab65.png)

**Comment by greyson-signal** [comment]
Yeah, I think this was fixed? Re-open if not
