### ISSUE TITLE
Blocked contact should not show in New Conversation dialog

### ISSUE THREAD

**Issue by loxK** [signalapp/Signal-Android#8704]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After blocking a contact it still shows in New Conversation dialog if it exists in phone's address book. I have a friend that removed Signal because of that. He has someone in his phone, he has to keep him in for security reasons, but it is upsetting him to see his name on top of the list each time he opens the new conversation dialog.

### Steps to reproduce
- block a contact
- create new conversation

**Actual result:** see the blocked contact in the dialog
**Expected result:** the blocked contact shouldn't show up

**Comment by hdeweirdt** [comment]
I'd like to try this out as a first contribution. Would this functionality be required for all places where a contact can be selected, not just when starting a new conversation?

**Comment by loxK** [comment]
Yes all places. A second friend uninstalled Signal because of this. Blocked contacts shoudln't appear to the eyes of the user, apart from the blocked contacts list.

**Comment by oznogon** [comment]
lost my most messaged contact from Signal because blocking a number requires adding it as a contact. being able to block numbers without adding them as contacts would also resolve this

**Comment by loxK** [comment]
@moxie0 any thoughts ?

**Comment by greyson-signal** [comment]
I think this was changed a while ago. Blocked contacts do not show up in the new conversation screen, nor in contact search results. If you had an existing conversation with them, the conversation will still show up in the conversation list, but you can archive it or delete it.

> being able to block numbers without adding them as contacts would also resolve this

That was added not too long ago as well. Settings > Privacy > Blocked users > Add blocked user
