### ISSUE TITLE
[QUESTION] Where I can find the CI service? 

### ISSUE THREAD

**Issue by gustavosizilio** [signalapp/Signal-Android#8707]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by greyson-signal** [comment]
1) Signal does not, nor has it ever, used CI.
2) As noted in the issue template, Github is only for bugs. In the future, please use [the forum](https://community.signalusers.org/) for questions like this.
