### ISSUE TITLE
When receiving multiple videos not all can be played from rail.

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#8710]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive multiple video's and I press one video from the received album this video is played. In that screen it also lists the other video's I received. When I press an other video in that list the list itself drops to the bottom of the screen so there are no video controls anymore (play, forward etc) and the video is not played. This does not happen with all video's though.
The only option to play the other video's is to go back to the conversation screen and then from the album select the other video. By doing so I can play that video but then again from the rail I can't play the other ones.
Below are some screenshots of what happens. First screenshot shows the situation when a video is selected from the album in the conversation view. The video plays correctly. The second screenshot shows when I selected a video from the rail. As can be seen the video control options are gone (and the video doesn't play)
One other thing that can be seen is that the previews of the videos in the rail are all empty. I think this is device specific and related to https://github.com/signalapp/Signal-Android/issues/5993. Perhaps this is the source of the problem and displaying the default video image if no preview can be generated solves it. That's just my guess though.

### Steps to reproduce
- receive multiple videos
- open a video from the album
- try to play an other video from the video rail (not reproducible with all videos)

**Actual result:** As described. With some videos the video controls are not displayed and the video doesn't play
**Expected result:** All videos can be played from the video rail.

### Screenshots

![Screenshot_1stvideo](https://user-images.githubusercontent.com/25846829/54918856-98481a80-4eff-11e9-9844-4379c633afba.png)
![Screenshot_2ndVideo](https://user-images.githubusercontent.com/25846829/54918875-a5650980-4eff-11e9-9d99-848602f409b7.png)

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.36.2

### Link to debug log

Started around 11:17. Conversation **74
https://debuglogs.org/29b97460cde93e176e131748d303ec625648d68e95eab1680fcae842ecb82258

**Comment by janvlug** [comment]
I have this issue as well. Here is a [debug log](https://debuglogs.org/6c71970999df85c7aad0f4043f41339d0a800b870c483f5c47357ded36df33ef).
