### ISSUE TITLE
No Wifi-only devices (tablets) support

### ISSUE THREAD

**Issue by raccoonfancy** [signalapp/Signal-Android#8711]
Similar issues keep getting closed due to being stale, but this is a needed feature.

You can still side-load the apk on a tablet, but this way you are still limited to one Android device as this breaks registration with the original device.

It may be less secure as there are duplicate devices out in the world, but the Signal desktop app exists, so that problem already exists. Allowing the app to be installed for both phones/tablets, and system like the Signal desktop master-slave relationship would be wonderful.

**Comment by greyson-signal** [comment]
As noted in the issue template, we reserve Github for bugs. To discuss new features, please visit [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests).
