### ISSUE TITLE
Update download should obey "Media auto-download" settings

### ISSUE THREAD

**Issue by wavexx** [signalapp/Signal-Android#8714]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
I disabled all kinds of media auto-download when using a mobile connection.

But signal will happily download an update for itself over the mobile connection anyway, which is way larger than your typical media file.

There should be a dedicated setting to prohibit signal to download updates over mobile connections. But *that* would be a feature request ;), so I expect signal to withhold any downloads of updates if media download from mobile connections is disabled.

### Steps to reproduce
- Disable media auto-download on mobile connection
- Disable wifi
- Watch signal download an update irregardless

### Device info
**Android version:** 7.1.2 (Lineage)
**Signal version:** 4.36.2

**Comment by fylmr** [comment]
Do I understand it correctly that you've disabled media auto-download _inside_ Signal but you are getting updates for an app from _Google Play_?
If so, is has nothing to do with Signal settings, so please disable auto-download in your Google Play settings.

**Comment by wavexx** [comment]
On Thu, Mar 28 2019, Philipp Maksimov wrote:
> Do I understand it correctly that you've disabled media auto-download
> inside Signal but you are getting updates for an app from Google Play?

No, I don't have google play. This is on Lineage-OS and signal.app was
installed manually using the apk.

Signal is checking and updating itself in this mode.

**Comment by rcamerous** [comment]
I have the same issue and it seems to be a bug. I have been having this issue for a while now.  When I first started using Signal, it would give you the option to download media files but then one day it just started downloading them automatically, no matter if I had it turned on or not, and has continued to do so.

**Comment by wavexx** [comment]
This is about signal downloading an update for itself. Media auto-download works as it should in my case.

**Comment by rcamerous** [comment]
Oh I see.  You stated media auto download so I thought you meant inside the signal app as far as downloading media files.  I think that's what's meant as far as media auto-downloading. This i s what I am having an issue with. As far as the issue you are having, the only way I know to stop apps from updating is disabling the option in settings in Google play store.

**Comment by wavexx** [comment]
Guys, please read carefully. This is without the google play store.

**Comment by rcamerous** [comment]
Yea I just read through the previous messages and see that.  I really don't know you would solve that problem I'm afraid.  I hope you figure it out.

**Comment by eb053049** [comment]
This bug also affects me.



### Bug description
I use the website apk since I have a non-gapps phone with limited data. Please show the new version prompt to the user before downloading, not after.

### Steps to reproduce
- Install website apk on android
- Get message notifying of new signal version
- Tapping this reveals that it has already been downloaded and is only prompting you before installing.

**Actual result:**  Tapping this reveals that it has already been downloaded and is only prompting you before installing.
**Expected result:** There should either be a setting to only update over wifi, or if not, show the update prompt before downloading, not after.

### Device info
**Android version:** lineageos 16 (Android Pie)
**Signal version:** 4.36.2

**Comment by quite** [comment]
I was also surprised to get a message from Signal itself that an update is available (Lineageos 16, Signal from an F-droid-repo). But mostly because I didn't know it was able to do that at all. Where can I read about that?

**Comment by wavexx** [comment]
I would be fine if signal would prompt me before attempting a download, at the very least.
Currently it tries to update itself over a 3g connection which has over 10% packet loss.
The update itself takes in the order of days and I cannot delay that until I'm connected to wifi.
