### ISSUE TITLE
Sending to wrong recipient + scrambled message history => Implementation of non regression tests?

### ISSUE THREAD

**Issue by liar666** [signalapp/Signal-Android#8716]
Again, I was faced with bugs in basic signal functionning:
- I was having a conversation with a friend within Signal, using non-encrypted SMSs, then I wanted to share a picture with another friend.  I switched to Android's Gallery, selected a picture, clicked on "Shared", then selected Signal, then selected my 2nd buddy. Everything went fine until I went back to my initial conversation and discovered the picture was sent to the 1rst buddy - the one of the initial conversation -, not the second one - the intended and actually selected recipient !!!! I've been confirmed the image was received by the 1rst - UNintended - recipient and never by the 2nd - INtended- recipient.

- Another time (after several reboots of my phone), I opened Signal, selected an intented recipient - a friend - , and discovered in the history of previous messages, many messages&pictures that I sent some time ago to another recipent - my sister -. I can confirm that my sister had received the intended message at the time, so it's "just" the history that was scrambled/assigned to the wrong recipient - this time (and is still wrongly assigned after the installation of the latest version of Signal)...

What is the point of using a "secured" cyphered messaging tool, if private/confidential messages are sent to random recipients instead of the selected one ?

PS: I think I've already talked about that in a previous bug report: it would be great (and is usually considered a mandatory&good programming practice these days) to jointly develop a set of unit/non-regression tests together with each piece of code, in order to ensure that basic functionality is NOT broken by any later code addition, for instance checking an updated version of the app BEFORE sending it into the wild PlayStore.
Would you consider respecting this good practice?

In order for this critics to remain constructive, here is a basic set of tests that I would consider mandatory to pass before releasing any new update of the Signal app:
- testing that non-cyphered call works (rings, calls the correct person, has 2-way working sound, call history is correctly appended)
- testing that cyphered call works (rings, calls the correct person, has 2-way working sound, is actually cyphered, call history is correctly appended)
- testing that non-cyphered SMS works (sends correct text, sends text to the correct person, message history is correctly appended)
- testing that cyphered SMS works (sends correct text, sends text to the correct person, is actually cyphered, message history is correctly appended)
- testing that non-cyphered MMS works (sends correct text & various media, sends text & various media to the correct person, message history is correctly appended)
- testing that cyphered MMS works (sends correct text & various media, sends text & various media to the correct person, is actually cyphered, message history is correctly appended)
- testing that history remains the same before/after any update of the app
- testing that configuration (MMS proxy, etc) is not touched after any update
- tseting that notifications appear when receiving calls/SMS/MMS

**Comment by greyson-signal** [comment]
Hi, do you have "Don't keep activities" turned on in the developer options?

**Comment by greyson-signal** [comment]
This behavior is consistent with having "Don't keep activities" turned on. This option is not a general use tool -- it is intended for testing specific scenarios, and causes the app to behave in ways that would actually be impossible when the setting is off. Closing this issue.

**Comment by liar666** [comment]
*One year later* I still have the problem of Signal sending MMSs to wrong persons....

I don't see how/why having this option would make the sharing of a picture from the gallery to a contact that is not the one that was selected from within Signal (no abandonned activity)... Nor why the transfering of a MMS from within Signal to another contact than the selected one within Signal would send to a "random" contact - generally the one that was the source of the forward and that will receive the MMS a second time (no abandonned activity either).

So IMHO the issue needs re-opening ...
