### ISSUE TITLE
"Note to self" shows real name in direct share

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8719]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In direct share the name of "Note to Self" entry is your real name and not "Note to Self".

### Steps to reproduce

- Make sure you have your number as contact in your address book.
- Send a note to self in Signal
- Open a different app and share something

**Actual result:** The name of "Note to Self" should be "Note to Self".
**Expected result:** It shows the name you have entered in your address book.

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2
**Signal version:** 4.36.2

**Comment by link2xt** [comment]
Besides this, I see my name in the list of potential group members whenever I create a new group. It has a "Note to self" icon and it does not matter whether I add myself or not to the group. I think it should not be displayed.

**Comment by Pentaphon** [comment]
I'm kind of shocked that little privacy details like this aren't already thought of.

**Comment by Laancelot** [comment]
Hi @mueller-ma, I hope everything's well. I was trying to recreate this error but to no avail - not in the note to self and not when I create a new group, either. However, I do see on the Signal home screen, an icon in the top-left corner with my initials, if my contact is saved in my address book. Is that what you mean?
I would truly appreciate it if you could confirm you are still having this(these) issue(s) on Signal 4.69.6. Many thanks in advance! Cheers

**Comment by mueller-ma** [comment]
I cannot reproduce this in 5.22.X anymore.
