### ISSUE TITLE
Can't type when opening conversation from notification 

### ISSUE THREAD

**Issue by chaoscommander** [signalapp/Signal-Android#8720]
- [x] I have searched open and closed issues for duplicates, there is one that hasn't been resolved, but locked: #5915
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening a conversation from the new message notification, in about 20% of the cases I cannot type anything. The keyboard shows up, typing leads to word suggestions within the keyboard, so it obviously accepts my input, but the input field stays empty. Only way to make it work again is to back out of the conversation to the chat list and reopen the conversation. Closing and reopening just the keyboard does not work, contrary to the description in #5915.

### Steps to reproduce
- while on homescreen or with screen off, receive message
- touch notification to open chat (don't use "reply") 
- try to type a reply 

**Actual result:** keyboard input is not accepted
**Expected result:** input is accepted

### Device info

**Device:** OnePlus 3T
**Android version:** 8.1.0 (LineageOS)
**Signal version:** 4.36.2

### Link to debug log

https://debuglogs.org/4987372b36f39ef371bd3e632ba1ba5c14cea21fce79b1165ba1c4c87d1ebcdc

**Comment by chaoscommander** [comment]
Added debug log. Can't add screenshot on mobile, it seems.

**Comment by Dyras** [comment]
This happened weekly for me on 8.1.0. Seems to have been fixed with Android 9.0 however. Maybe it's an Android issue?

Using Gboard btw.

I was collecting debug logs for this issue before it fixed itself, but for some reason they all look like this now:
https://debuglogs.org/89478cf22acdd5edf4e244a90357f4538dc121b4ed1f713630b2fdb660e07430

**Comment by kevincianfarini** [comment]
This happens every single time for me coming from a notification using the AOSP keyboard.

**Comment by kevincianfarini** [comment]
Interesting. This may be a device issue. I'm running LineageOS 8.1.0 on the Oneplus 5T

**Comment by chaoscommander** [comment]
After updating to Android 9 the problem has not occurred again. Won't close, since there might be people who can't update? Unless you feel differently, then feel free to close.

**Comment by austen-wade** [comment]
I am experiencing this running Android 10 (OxygenOS 10.3.0) on OnePlus 6

**Comment by greyson-signal** [comment]
I don't think there's much we can do here. This is a bug I've seen throughout the years in various apps -- just seems to be an Android system bug that pops up from time to time.
