### ISSUE TITLE
[Feature Request] Push Notifications API

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#8721]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------
Can you please add a push notification API so, Signal can be used for notifications or as a client for two factor authentication.

Similar to, telegrams push notification API but, text only as i think telegram supports things other than text, which could lead to security or privacy problems.
https://core.telegram.org/api/push-updates

Thanks

**Comment by mlsxlist** [comment]
In the issue templates it is clearly stated that github issues are not for feature requests. Please bring your feature request to the community forum as mentioned in the template.
