### ISSUE TITLE
Delivery/read receipts not consistently collapsed

### ISSUE THREAD

**Issue by cdenyar** [signalapp/Signal-Android#8722]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some contacts consistently show delivery/read receipts for each successive message even when sent within seconds and show 'NOW', others consistently combine/collapse the receipts for successive messages.

### Steps to reproduce
- Send contact several messages quickly
- Observe some contacts the receipt icons only show on the bottom message to indicate delivered/read for the set, others consistently show the receipt on every message.

**Actual result:** Receipt icons not always collapsed for quickly sent successive messages.
**Expected result:** Receipt icons for quickly sent successive messages with the same status combine/collapse the receipt status icon into the most recently sent message.

### Screenshots
Examples where contact messages consistently show receipt on each message:

![image](https://user-images.githubusercontent.com/6653063/55235854-e95c5500-5204-11e9-9192-66270c2a818e.png)

![image](https://user-images.githubusercontent.com/6653063/55236098-861ef280-5205-11e9-8da6-3cac674c2fee.png)

Example where successive messages share a receipt status:
![image](https://user-images.githubusercontent.com/6653063/55236087-7f907b00-5205-11e9-983e-ac61cdb41e6d.png)

### Device info
**Device:** Pixel 2 XL
**Android version:** 9
**Signal version:** 4.36.2

### Link to debug log
https://debuglogs.org/4448519c8eccc59f969a4da1edee3892bcf743a49d993b49b7c911e1cc17d735

**Comment by greyson-signal** [comment]
We only collapse footers when they would otherwise be the same. For disappearing messages, they're never the same -- each message has their own timer. Therefore, we can't collapse them.
