### ISSUE TITLE
"Safety number just changed" dialog shows "%d others" instead of a count

### ISSUE THREAD

**Issue by nelhage** [signalapp/Signal-Android#8724]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Safety numbers have changed" dialog displays "%d others"

### Steps to reproduce
- Join a group chat with members you have never contacted before
- Attempt to send a message to the chat

### Screenshots

![image](https://user-images.githubusercontent.com/16725/55269720-df157780-5253-11e9-8cc0-406800f6cfa7.png)

### Device info

**Device:** Google Pixel 3
**Android version:** 9
**Signal version:** 4.36.2

### Link to debug log

https://debuglogs.org/82fb77d025c8649c008f04375e6db647880ec9eb70802937b443e1daa0cb6046
I captured this just now, but the bug happened around 0900 PDT this morning

**Comment by Meteor0id** [comment]
Note it says other, not others. Might be an issue only with the singular form.

**Comment by Meteor0id** [comment]
Found which text strings are being used:

When 4 or more numbers have changed, the third variable of IdentityUtil_untrusted_dialog_many is not a number or name, but will insert the translated string with identity_others

When exactly 4, the singular form of identity_others is inserted. When more than 4, the plural form of identity_others is inserted.
