### ISSUE TITLE
Dual Sim Selector for SMS 

### ISSUE THREAD

**Issue by gleichda** [signalapp/Signal-Android#8725]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a SMS via Dual SIM I don't know to which number I send it because Signal just shows the Provider in selection and not the given name.

### Steps to reproduce
- Use DualSim with Signal as SMS App
- Have two Cards from the same Provider
- Try to select the Sim the SMS gets send from

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Signals shows the two SIM Card providers but with the same name and no way to be sure which SIM is which.
![Signal-DualSIM](https://user-images.githubusercontent.com/15176026/55273556-5804e580-52cd-11e9-9a8e-954c7089d9e7.jpg)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Signal should show the SIM by its name like defined in Android preferences
![AndroidSIMNames](https://user-images.githubusercontent.com/15176026/55273555-53d8c800-52cd-11e9-820d-9b9915832e50.jpg)

### Device info

**Device:** Samsung Galaxy S9
**Android version:** 8.0.0
**Signal version:** 4.36.2

**Comment by alan-signal** [comment]
Just a note to say that it's not problem in general, OnePlus:

![image](https://user-images.githubusercontent.com/48254818/55278480-b5a82a80-52eb-11e9-9d69-8090b89df00e.png)
![image](https://user-images.githubusercontent.com/48254818/55278484-bc36a200-52eb-11e9-93d5-e786514274d4.png)
![image](https://user-images.githubusercontent.com/48254818/55278495-dcfef780-52eb-11e9-8da4-afc4476da803.png)

**Comment by gleichda** [comment]
So might be a Samsung related Problem. Hopefully fixes with the the new Android Version then. I will see

**Comment by gleichda** [comment]
After upgrading to Android 9 finally vsame issue is still present.

**Comment by heuzef** [comment]
On my Huawei Mate 8. I named my two sim card, but i have only the "Telecom Name" :cry:

**Comment by alan-signal** [comment]
Please let us know how it looks for you now in 4.39 if you're on the Beta.

Where we can't get unique names for whatever reason, we now use the number. It should at least ensure you can tell them apart.

**Comment by gleichda** [comment]
Would like it better to have the SIM Name. But you are right at least I see now which SIM I'm using

**Comment by heuzef** [comment]
It's worse for me, now I have nothing at all :(

![dual_sim_bug](https://user-images.githubusercontent.com/1780479/57059902-a3892580-6cb7-11e9-99c1-a68916b931dd.png)

**Comment by gleichda** [comment]
This is what it looks for me now. FYI
![image](https://user-images.githubusercontent.com/15176026/57065764-be18ca00-6cca-11e9-80ea-04d1231359b7.png)

**Comment by heuzef** [comment]
In french, we don't have the calling codes, our "+33" is hidden by an output "zéro".

Exemple, the phone number **+33 612-345-678** is replaced by this format **0612345678**.

Maybe there is the problem ?

**Comment by UserX404** [comment]
> 
> 
> In french, we don't have the calling codes, our "+33" is hidden by an output "zéro".
> 
> Exemple, the phone number **+33 612-345-678** is replaced by this format **0612345678**.
> 
> Maybe there is the problem ?

This behavior exist in every county. Inside your county you call with a leading zero but it's the same as you start with 0033612.. or +33612.. or 0612...
0033 is just your country's area code.

**Comment by heuzef** [comment]
OK, so maybe my model phone is the problem. I have an Huawei Mate 8 on Android 7.0. please, let me know if I can be helpful to solve this bug ;)

**Comment by greyson-signal** [comment]
We switched to showing a simple index number instead of the phone number to hopefully get around some of these worries.

**Comment by heuzef** [comment]
> We switched to showing a simple index number instead of the phone number to hopefully get around some of these worries.

Yes it's Working for me :) Thank you :+1: 

I have "SIM 1" and "SIM 2" now.

**Comment by gleichda** [comment]
It is working for me now the same way. 
But... for me using SIM1 and SIM2 does not really look great, because it is not really easy to see which one is wich. At least on Samsung Phones. 
So maybe it would be possible to have two fallbacks: SIM Name -> Phone Numer -> SIM Index

**Comment by heuzef** [comment]
>  So maybe it would be possible to have two fallbacks: SIM Name -> Phone Numer -> SIM Index

I agree, it's a good compromise.

I think we should also add a SIM card icon with very different colors ?

**Comment by alan-signal** [comment]
Ideally I'd like to get to the point where we don't need any fallback and can get the user specified sim name for everyone. But step 1 is having everyone have a unique description to fall back to.

I don't think numbers were a good solution in retrospect because they are quite long and have to appear under every text message.

> because it is not really easy to see which one is wich

Are you saying the text "SIM 1" and "SIM 2" are just too similar to tell apart at a glance?

**Comment by gleichda** [comment]
> Are you saying the text "SIM 1" and "SIM 2" are just too similar to tell apart at a glance?

Yes and somehow difficult to differenciate which is which. To see which SIM is which you have to go to Preferences -> Phone Info... (as in every other place, because they are all from the system, I'm seeing the name I don't know which is which)

> Ideally I'd like to get to the point where we don't need any fallback and can get the user specified sim name for everyone. But step 1 is having everyone have a unique description to fall back to.

Would be definitely the best...

**Comment by OrpheeGT** [comment]
Hello,
I'm currently having the same issue on my Samsung S20 with Android 10.
I only have the operator/carrier name shown, no SIM card name, no phone number.
I named my cards Pro and Perso.
Currently I have 2 different carrier so I still know what is the good one.
But I plan to switch my personnal carrier to the same as pro, so I won't be able to know what phone is...
My phone language is in french for information...

![Screenshot_20200504-234457_Signal](https://user-images.githubusercontent.com/8038551/81016903-9e7a2b80-8e61-11ea-896e-fe7f1436886f.jpg)
![Screenshot_20200504-234603_Call settings](https://user-images.githubusercontent.com/8038551/81017072-e9943e80-8e61-11ea-9fba-bc22d6844354.jpg)

**Comment by alan-signal** [comment]
@OrpheeGT You will be able to tell them apart as once the names are the same, they will appear as "SIM 1" and "SIM 2". That is the fallback described in this issue and why it got closed.
