### ISSUE TITLE
[Feature Request] Custom vibration pattern

### ISSUE THREAD

**Issue by Ezile** [signalapp/Signal-Android#8727]
Something that I find missing in Signal is the possibility to set a custom vibration pattern.
I have my phone on Vibrate all the time and every time something happens on the phone it vibrates twice. It does this for everything, always that same vibration. This of course means that I have no way of knowing if it's something important or not.

Having a custom vibration pattern for Signal messages would be a huge quality-of-life improvement for me, and I imagine others as well.

I see many other apps with this feature and I miss it in Signal.

**Comment by piratenpanda** [comment]
This is an issue tracker. Feature requests should go here: https://community.signalusers.org/

**Comment by Ezile** [comment]
> This is an issue tracker. Feature requests should go here: https://community.signalusers.org/
Alright. How do I delete my issue?

**Comment by Cerberus0** [comment]
If you're using the GitHub web interface, you should be able to see a "close issue" button next to the "comment" button.

If you're new to this project, I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md). As @piratenpanda said, feature requests should go on the community forum. Note that you can easily join the community forum with your existing GitHub account.
