### ISSUE TITLE
Send button has a misleading contentDescription

### ISSUE THREAD

**Issue by ellenhp** [signalapp/Signal-Android#8732]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Send button has a misleading contentDescription.

### Steps to reproduce
- Turn on TalkBack
- Compose a message to a friend and tap once on the send button
- Observe what's verbalized

**Actual result:** "Signal" or "Insecure SMS" is verbalized.
**Expected result:** I would expect either "Send with signal"/"Send with insecure S M S" or "Send"/"Send with Insecure S M S" to be verbalized, depending on whether your friend also uses signal.

### Device info

**Device:** Pixel 2
**Android version:** 9
**Signal version:** built from HEAD

This is a tricky one, because while a reasonable contentDescription is set [here](https://github.com/signalapp/Signal-Android/blob/652306edd0df7e880b3da4897484f5686a3dada7/res/layout/conversation_input_panel.xml#L196), it's overwritten [here](https://github.com/signalapp/Signal-Android/blob/652306edd0df7e880b3da4897484f5686a3dada7/src/org/thoughtcrime/securesms/components/SendButton.java#L106) with the name of the TransportOption. My suggestion for fixing this would be to remove the misleading android:contentDescription xml attribute, and set the contentDescription in code based on the value of transportType.isSms(). My suggestion for the two strings would be "send" and "send with insecure S M S". The spaces in the contentDescription important to ensure that the TTS engine doesn't mangle the acronym by trying to turn it into a word.

I don't mind tackling this, but I'd like guidance from someone on the signal team as to whether this is an okay thing to do before I spend much time on it.

**Comment by Meteor0id** [comment]
> My suggestion for the two strings would be "send" and "send with insecure S M S".

I would say there need to be some contrasting meaning to it. So make it "send secure signal message" and "send insecure S M S".
These strings should of course also be translated.

**Comment by ellenpoe** [comment]
Ok, makes sense. Anything in particular I need to do to ensure they're translated? Not super familiar with your development/release process. This might also impact some PRs I've made.

**Comment by Meteor0id** [comment]
> Not super familiar with your development/release process.
It's up to the Signal team which I am not part of either.

Devs can merge this to I think a hidden beta project. It will than be translated by volunteers in Transifex. I've been doing some translating myself and I sometimes the context is necessary to avoid errors. In this case such context could be that these strings relate to the content description, which is why it might be a good idea to add that to the name of this text string (translators will see that too).

But this is just my input, I'm not part of the team.

BTW about those spaces, are you sure that will work? Have you tested that in other apps?

**Comment by Meteor0id** [comment]
Text strings rewritten in https://github.com/signalapp/Signal-Android/pull/8715
The issue with overwriting which string is used has not been solved in that PR.
