### ISSUE TITLE
Head of line blocking when sending a large video file

### ISSUE THREAD

**Issue by link2xt** [signalapp/Signal-Android#8734]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When I send large videofile (or probably any large file) to the chat, followed by some text messages, the messages stay in the queue until the file is uploaded.

### Steps to reproduce
- Create a large file, possibly by recording a 1 minute video
- Send video file to a chat (I tested with a group chat, should probably work for other types of chat as well)
- Send a text message while the video file is uploading (a circular progress bar is displayed on top of the videofile preview)

**Actual result:** Text message is waiting in the queue until the videofile is uploaded.
**Expected result:** Text message is sent immediately and the videofile contents is uploaded in the background

### Device info
**Signal version:** 4.36.2

I have not checked if there are technical limitations that prevent this kind of reordering. Maybe protocol changes are required. But given that it is possible not to download the file and still receive messages, I think it should be possible to send messages without actually uploading the whole content of the previously sent file.

**Comment by greyson-signal** [comment]
This is intended. Signal messages hold pointers to the attachments that are paired with them.

**Comment by link2xt** [comment]
I have looked a bit into libsignal-service-java. Isn't it possible to reserve AttachmentPointer before actually uploading the content? Key ratchet doesn't depend on the content of the attachment, so it should be possible to proceed without uploading the attachment itself, it would just not be available for download until upload is complete.

Clients can download attachments asynchronously, can't they upload them asynchronously too?

Was it considered and documented somewhere internally? Maybe I should submit a feature request to the support forum instead?
