### ISSUE TITLE
Links not clickable in long message detail view.

### ISSUE THREAD

**Issue by pldg** [signalapp/Signal-Android#8735]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When a message with more than 1000 chars is opened in the pop-up window, links are disabled (not-underlined) and therefor they cannot be clicked.

### Steps to reproduce

- Compose a message with a url link inside it.
- The message must have 1000 or more chars.
- Send the message.
- Read the sent message and check if the link works.
- Now at the bottom click on *Read More*.
- Once the pop-up is opened, inspect the text and check if the link works.

### Screenshots

In this screenshot, the link to Signal repository works fine:

![Screenshot_20190402-194509](https://user-images.githubusercontent.com/24630716/55424364-64fd2f80-5580-11e9-9334-c3e6cb4de93d.png)

But if I open the message I can't click on the link anymore:

![Screenshot_20190402-194520](https://user-images.githubusercontent.com/24630716/55424412-8100d100-5580-11e9-8acb-fc7e9eb4fc51.png)

**Comment by OfficialNSA** [comment]
Hi,
this issue persists in the Android App. Why didn't it make it into an official release?
