### ISSUE TITLE
Signal Is Down in Oman . Can't even register a new number.

### ISSUE THREAD

**Issue by raavanaX** [signalapp/Signal-Android#8736]
My Log.

https://debuglogs.org/cea8892b690b939f187e3d88bbf4c35f38ecccf9b2d46e7bb8d2e63e0b373225

https://debuglogs.org/f0b2a969792a7f5018dae3f9739f7d817f92fd05eb8c1b0ad3968bee61262167

**Comment by rwasef1830** [comment]
In Egypt as well, same error response 421

**Comment by rwasef1830** [comment]
Looks like Amazon followed through with their warning and pulled the plug on the domain front for souq cdn.

**Comment by raavanaX** [comment]
Yeah just went through iOS thread & came to know that. 
Any workaround on Domain Fronting or VPN routing or anything.

**Comment by ramast** [comment]
It's blocked for me also (Egypt).
I tried to pass all my traffic through VPN but still signal won't work.
Seems that signal app determine your location somehow and uses bypassing techniques relevant to your country.
Unfortunately there is no option - that I know of - to disable these bypassing techniques if you have a VPN. Hopefully one of the developers would give us a tip

**Comment by greyson-signal** [comment]
Can you [join the beta](https://play.google.com/apps/testing/org.thoughtcrime.securesms) and let me know if this is resolved? If not, can you post a debug log?

**Comment by ramast** [comment]
I don't have google play store, if you could provide link to the APK I'd be happy to test

**Comment by rwasef1830** [comment]
@greyson-signal new beta solved the problem, i see you're fronting through google now to a google cloud functions reflector, didn't google say they won't support it anymore ? I'm curious how you got it to work ?

**Comment by greyson-signal** [comment]
Glad to hear that it's working!

**Comment by raavanaX** [comment]
Hi @greyson-signal I'm not using any google services as of now. So is there any different link to download beta version of Signal-Android with google as domain Fronting.

**Comment by greyson-signal** [comment]
@raavanaX The version (4.37.2) is now available at https://signal.org/android/apk/
