### ISSUE TITLE
Dropping Jelly Bean Support? Android 4.0 --> Android 4.4 Required in 4.37 Beta

### ISSUE THREAD

**Issue by johnb-xp** [signalapp/Signal-Android#8737]
Looks like the latest beta requires Android KitKat. There are still millions of users happy with their Jelly Bean devices, including myself.

I'm wondering why this decision was made, other than "because Jelly Bean is old".

**Comment by Dyras** [comment]
It doesn't support the latest SDK

https://github.com/signalapp/Signal-Android/commit/975a121c551a06dc4d9efec0795d1284ed145459
"We'll be updating minSdk to 19 in 4.37. This lets these users continue
to use the app, but they'll be warned with a persistent banner saying
that they can't receive updates."

**Comment by Cerberus0** [comment]
Hi @johnb-xp,

Signal only uses GitHub for bug reports. Feature requests and non-bug discussions should go on the [community forum](https://community.signalusers.org/). I suggest closing this issue and continuing the conversation on the community forum, where there is already [a thread about this topic](https://community.signalusers.org/t/why-drop-ics-jelly-bean-support/6825). You can easily join the forum with your existing GitHub account.

If you're new to this project, I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md
