### ISSUE TITLE
painting on pictures is not possible behind text input

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#8738]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
painting inside pictures is not possible in the area of text input.

### Steps to reproduce
- take a picture or select an image and forward to any user
- click on the pencil icon on the top
- try to mark/paint anything behind text input

**Actual result:** 
not able to start drawing a line in the bottom area
**Expected result:** 
ability to paint on the whole canvas/picture

### Screenshots
![Screenshot_20190403-184017](https://user-images.githubusercontent.com/14954521/55497911-a0f8c900-5642-11e9-829e-c06fd6c5d8d9.png)

### Device info
**Device:** Sony Xperia XZ2 compact (XZ2c)
**Android version:** 9 (build 52.0.A.3.163)
**Signal version:** 4.36.2

### Link to debug log
It's full reproducable and i think it's clear what happens. Will append log if requested.

As possible solution, text input could be hidden by pressing pencil, brush and smiley icon.

**Comment by Meteor0id** [comment]
When using many colors, the color quick select buttons also extent behind that area, and although they are scrollable, the lower ones are always out of reach. It's a minor issue but it was just not meant to work that way.
![](https://community.signalusers.org/uploads/db3609/original/2X/c/c08b9646c57c7b2196ef26e53961086c93680325.jpeg)

**Comment by alan-signal** [comment]
This should be resolved by the new image editor in 4.40
