### ISSUE TITLE
Desktop-Version

### ISSUE THREAD

**Issue by Freudentaumel** [signalapp/Signal-Android#8739]
Hello, everybody,

I know that there is no desktop version for Windows 32-bit. 

Is there a workaround that allows me to install the desktop version on my 32-bit Windows?

Thanks a lot for helping!
Gerhard

**Comment by Cerberus0** [comment]
Hi @Freudentaumel,

Signal only uses GitHub for bug reports. Feature requests and non-bug discussions should go on the [community forum](https://community.signalusers.org/). I suggest closing this issue and continuing the conversation on the community forum. You can easily join the forum with your existing GitHub account.

If you're new to this project, I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md
