### ISSUE TITLE
Disable downloading MMS when roaming

### ISSUE THREAD

**Issue by lxgr** [signalapp/Signal-Android#874]
Some providers charge for receiving MMS messages while roaming abroad. We should provide an option that disables MMS downloading in that situation, just like the stock messaging application.

This is similar to what is already done when the APN settings are misconfigured (pending messages are enqueued in the database and the download is retried when the settings are changed); that mechanism could be generalized to also handle messages that arrive while roaming.

**Comment by 2-4601** [comment]
Signal has media download controls now that default to not downloading attachments automatically while roaming. But do they affect MMS also? @agrajaghh @McLoo can you confirm and close if true?

**Comment by McLoo** [comment]
For my self MMS tests, the 3 settings were ignored completely. 
Also I got the feeling, that I Sirius to McGinty avoid the auto mms download were I received  sth like "yeah,  esos work on that)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
