### ISSUE TITLE
New background activity start restrictions in Android Q

### ISSUE THREAD

**Issue by vt0r** [signalapp/Signal-Android#8740]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the Android Q developer preview, background starts will soon be blocked unless specific criteria are met (see below for link with full details on how to resolve).

### Steps to reproduce
- Upgrade to Android Q DP1 or DP2
- Open the Signal app
- Leave the Signal app
- Show running apps
- Swipe the Signal app away
- A toast will display that tells you the background activity start will be blocked in future Android Q builds, telling you to visit http://g.co/dev/bgblock
  - That link expands to https://developer.android.com/preview/privacy/background-activity-starts

### Device info

**Device:** Any device
**Android version:** 10.0.0 (Q)
**Signal version:** 4.37.1

**Comment by davideAng** [comment]
https://developer.android.com/preview/privacy/background-activity-starts

With Android Q Beta3 update we do not need to Mitigate by using notification-triggered activities because we have **an activity in the back stack of the foreground task.**

**Comment by NitzDKoder** [comment]
incoming call acivity is blocked too.

```
1561353582.493 1251-2818/? I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=org.thoughtcrime.securesms/.WebRtcCallActivity} from uid 10172
1561353582.494 1251-2818/? W/ActivityTaskManager: Background activity start [callingPackage: org.thoughtcrime.securesms; callingUid: 10172; isCallingUidForeground: false; isCallingUidPersistentSystemProcess: false; realCallingUid: 10172; isRealCallingUidForeground: false; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; isBgStartWhitelisted: false; intent: Intent { flg=0x10000000 cmp=org.thoughtcrime.securesms/.WebRtcCallActivity }; callerApp: ProcessRecord{3c8509c 8792:org.thoughtcrime.securesms/u0a172}]
```

https://developer.android.com/preview/privacy/background-activity-starts

Time to switch to ConnectionService.Whatsapp and Telegarm works that way.

https://developer.android.com/reference/android/telecom/ConnectionService

**Comment by rcidt** [comment]
As far as I'm aware, whatsapp _does not_ use ConnectionService. Do you have any info to back that up @NitzDKoder ?

**Comment by greyson-signal** [comment]
This should be resolved already.
