### ISSUE TITLE
Shared contact's phone number can't be copied

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#8742]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When someone shares a contact with me I expect to be able to long press on the contact info an copy their phone number into the clipboard. This isn't possible. The contact can only be added to the address book.

### Steps to reproduce
- have someone share a contact with you
- receive contact with option "add to address book"
- try to copy the number by long pressing on the message itself
- open the shared contact through a tap and try to copy the number again by long pressing in the opened contact.

**Actual result:** nothing happens. I cannot copy the contact phone number to the clipboard and have to add them to my address book although I don't want to add them. 

**Expected result:** I expect to be able to copy their number to the system clipboard.

### Device info

**Device:** Google Pixel 
**Android version:** 9
**Signal version:** 4.37.1

**Comment by mlsxlist** [comment]
For me that sounds like a feature request. It would be nice to have it, but it seems not been implemented.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
