### ISSUE TITLE
Not all send options selectable on Dual SIM Phone when composing media message

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#8744]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a conversation it is possible to select both SIM Cards as well as Signal to send the massage (Screenshot 1). However when adding an image or gif attachment only the second SIM Card and Signal shows up as an option (Screenshot 2). Whith a pre-selected SIM Card the two SIM Cards show up but Signal is missing as an option in the media composition dialog (Screenshot 3).

### Steps to reproduce
- click the plus icon within a conversation
- long press the send button 
- observe not all available options for sending the message are shown

**Actual result:** Not all options for sending insecure or secure messages are available in the media composition dialogue.
**Expected result:** All options for sending the message should be available in the media composition dialogue.

### Screenshots

1. Within conversation
![Screenshot_1](https://user-images.githubusercontent.com/9938306/55668137-8d797800-5865-11e9-9032-3b7c50942e3e.png)
2. Media composition dialogue
![Screenshot_2](https://user-images.githubusercontent.com/9938306/55668138-90746880-5865-11e9-94c1-4637db9c3245.png)
3. Media composition dialogue with pre selected SIM Card
![Screenshot_3](https://user-images.githubusercontent.com/9938306/55668140-936f5900-5865-11e9-82ee-51695849c649.png)

### Device info

**Device:** Samsung Galaxy S5 Mini  - SM-G800H (kmini3gxx)
**Android version:** 6.0.1
**Signal version:** 4.37.2

### Link to debug log

https://debuglogs.org/098283bdaf692cec261d43172d6c02b7eeabef8f964e77b5cab6db90dcc16091

**Comment by alan-signal** [comment]
Thank you for the report.

The bug here is actually that there should be zero SIM options when you enter this point.

**Comment by billie80** [comment]
So at this point in case of secure transport pre-selected it should not be possible to switch the method and when using the insecure transport option it should only be possible to switch SIM cards on a Dual SIM phone? This would make sense to me!
