### ISSUE TITLE
Impossible to save drafts including media

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#8745]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With the new media composition dialogue drafts including media are not saved any more. Previously when selecting an image and writing a text the draft including the image was saved when returning back to the main screen. For text only messages it is still possible to save as draft.

This is especially a problem when composing a long message text with multiple images including captions and maybe even use doodles, stickers, etc. Putting a lot of effort in a message and then finding it is not saved as a draft is somewhat annoying.

### Steps to reproduce
- use the plus icon to add media
- select image(s) and compose message text
- when returning to the conversation or main screen no draft is found 

**Actual result:** Not all messages are saved as a draft.
**Expected result:** All composed messages should be saved as a draft.

### Device info

**Device:** Samsung Galaxy S5 Mini - SM-G800H (kmini3gxx)
**Android version:** 6.0.1
**Signal version:** 4.37.2

**Comment by greyson-signal** [comment]
This is a side-effect of the recent changes we made to the media send flow. We were aware of the removal though, so I think this falls into the category of 'feature request', which means it should probably be moved to [the forum](https://community.signalusers.org/). Thanks!

**Comment by Ablesius** [comment]
How is an accidental breakage of a previously working feature not a bug? It is a regression. Please treat this as such.

**Comment by greyson-signal** [comment]
Because it wasn't accidental :) It was a trade-off we knowingly made with the new media send flow. Future design changes could bring it back, but for now this is working as intended.

**Comment by billie80** [comment]
Forgot to add a reference to the [post](https://community.signalusers.org/t/drafts-are-not-saved-anymore-with-the-new-media-send-flow/7204) I have opened at the forum. You can support this "feature request" by adding your like there.

**Comment by githubuser6000** [comment]
Was this tested in beta? I just find it sad that removal is so quick but adding it takes back takes half a decade.

**Comment by ghost** [comment]
@greyson-signal so you remove a feature without feedback and then we have to use the forum to wait decades for it? Can you please reopen this?
