### ISSUE TITLE
User's profile picture gets overridden by the user's contact 

### ISSUE THREAD

**Issue by pushkar-anand** [signalapp/Signal-Android#8749]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a contact picture of a user is set, the user's signal profile picture gets hidden.

### Steps to reproduce
- Open Signal
- Go to the main conversation list
- Find a contact with a profile picture.
- Close signal & open your contacts app.
- Set a contact picture for the contact.
- Open signal app.
- You will see the contact picture you just set instead of the profile picture.

**Actual result:** 
User profile picture gets overridden by the contact picture. 
**Expected result:** 
User's profile picture should be visible instead, even if the contact picture is set.

### Device info
**Device:** Motorola G5s
**Android version:** 8.1.0
**Signal version:** 4.37.2

### Link to debug log
https://debuglogs.org/af301bf48de5e152f1bd6ed1e47c12c71cd0184683dfc19cafc11fb08d7cf33d

**Comment by Cerberus0** [comment]
This is actually intended behavior in Signal. From [the blog post](https://signal.org/blog/signal-profiles-beta/) that introduced Signal Profiles:

>You will start to see more pictures and fewer colored letters in Signal, but the contact information that is stored on your device will always take precedence. If you saved someone’s picture to their contact card back in 2007 and it has traveled through time across the vast chasm of a decade of smartphone upgrades, you’ll continue to ride that wave of blurry nostalgia every time they call.

See also https://github.com/signalapp/Signal-Android/issues/6937.

**Comment by pushkar-anand** [comment]
So what's the point of someone having a profile picture if I can't see it.

**Comment by greyson-signal** [comment]
We've decided that if someone has set a contact photo for someone on their phone, that is the photo they want to see, so that takes precedence. If you disagree, feel free to discuss it on [the forum](https://community.signalusers.org/). Thanks!

**Comment by pr0gg3r** [comment]
There will be an option for this behavior https://github.com/signalapp/Signal-Android/issues/9833#issuecomment-760355636
