### ISSUE TITLE
Blackberry UEM Container, Android 8.0., longer start time

### ISSUE THREAD

**Issue by 90Dragon** [signalapp/Signal-Android#8751]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you have a Andoird 8 device with Blackberry UEM 12.9.1. with activation typ "Work and personal - privacy". The app start takes ~6 seconds to load.
According to Blackberry the issue is to changes in the API of Android 8.
https://developer.android.com/about/versions/oreo/android-8.0-changes
Screenshot from install Signal App in work Area appended. Second Screenshot is ~6 after the app is loaded.

### Steps to reproduce
- Activate Android 8 device with UEM 12.9.1 MDM Server. Activation type has to be "Work and personal -privacy"
- Asign the app Signal to the device
- Install the Signal app on the device
- start the Signal App in your work "area"

**Actual result:** App needs ~6 Seconds to start
**Expected result:** App should need 0-1 Seconds to start

### Device info

**Device:** Blackberry Motion 
**Android version:** 8.1.
**Signal version:** 4.37.2

### Link to debug log

https://debuglogs.org/6485b49bda3a96ddbdc02ced959e4875ad212ba91d0cb35adbef7f120c2ca415

![Work_area_with_Signal](https://user-images.githubusercontent.com/46529619/55782276-31546500-5aac-11e9-9398-cacd1e6b0452.png)
![Signal_opens_after_6seconds](https://user-images.githubusercontent.com/46529619/55782277-31ecfb80-5aac-11e9-9b71-3d121e4b35c5.png)

**Comment by greyson-signal** [comment]
As far as I'm aware, we're compliant with all of the Android 8.0/API 26 changes. This seems to be some blackberry-specific system?

> According to Blackberry

Do you have a link to the documentation where you read this?

**Comment by 90Dragon** [comment]
Thx for the input, i try to gather more Information via Blackberry.
I thought if i post this you could have an idear (or see somthing in your logs) what could cause this kind of behaviour.
I will post an update if Blackberry can find anything (will take some time probably).

Thx for your Time.
