### ISSUE TITLE
App screenshot remains in app switcher after locking signal

### ISSUE THREAD

**Issue by brandiniman** [signalapp/Signal-Android#8752]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
App switcher retains full app screenshot even after locking Signal

### Steps to reproduce
-open signal
-unlock signal
-open message
-leave signal using home button
-lock signal via notification action 'Lock Signal'
-bring up android app switcher

**Actual result:** See entire screen capture of signal app
**Expected result:** Not to see entire screen capture of signal app

### Screenshots
![image](https://user-images.githubusercontent.com/48254818/55826752-0f280a80-5adf-11e9-8509-8a19141521d0.png)

### Device info
**Device:** Pixel 2 XL
**Android version:** 9, April 5, 2019 security level
**Signal version:** 4.37.2

### Link to debug log
https://debuglogs.org/953b75f002f911590800b5e26e4ad233d62d963e051f75e05cb58d98b968fafd

**Comment by alan-signal** [comment]
The "Screen lock" feature is designed to lock your Signal screen so that you can't interact with the app. This is unrelated to the "Screen security" feature that can also be enabled or disabled independently in your Signal settings.

I presume you have "Screen security" off? Please confirm.

**Comment by brandiniman** [comment]
That was it. But if the setting isn't behind a lock isn't it semi-useless?
I have to two factor before editing my two factor settings at work for this
very reason.

**Comment by greyson-signal** [comment]
It's tricky. I don't think we can shut off the recents list screenshot if the app isn't focused because it's a window flag. One option could be that when you enable screen lock, we also enable screen security. But that would mean the screenshot would never show up in the recents list, even if signal is unlocked at the time. Either way, we can close this bug because we're entering the territory of new behavior.
