### ISSUE TITLE
TransactionTooLargeException when building notification

### ISSUE THREAD

**Issue by ByteHamster** [signalapp/Signal-Android#8759]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just got crashes that look very similar to #8580 but the stack trace is different. The app crashed every time I opened a conversation (I think Signal tried to update the notification). Please note that I have received a huge Signal message (~500kb of text, not an attachment file) before that.

### Device info
**Device:** OnePlus 3T
**Android version:** LineageOS 16.0
**Signal version:** 4.37.2

### Logs
```
04-12 20:13:35.997  1454  1499 E AndroidRuntime: FATAL EXCEPTION: FcmMessageProcessing
04-12 20:13:35.997  1454  1499 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 1454
04-12 20:13:35.997  1454  1499 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1085616 bytes
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:408)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:370)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:212)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:196)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.sendSingleThreadNotification(MessageNotifier.java:344)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:267)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:232)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:204)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleTextMessage(PushDecryptJob.java:784)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:244)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.processMessage(PushDecryptJob.java:200)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handleMessage(PushReceivedJob.java:56)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.processEnvelope(PushReceivedJob.java:48)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.lambda$pullAndProcessMessages$0(PushNotificationReceiveJob.java:57)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.-$$Lambda$PushNotificationReceiveJob$bVCZU2u82OKjX-kg33xXwRxvpyM.onMessage(Unknown Source:6)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:188)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.pullAndProcessMessages(PushNotificationReceiveJob.java:55)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.gcm.FcmService.lambda$handleReceivedNotification$1(FcmService.java:97)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at org.thoughtcrime.securesms.gcm.-$$Lambda$FcmService$7d6yllOHNf_Dilyjy8GhoL_fAuc.run(Unknown Source:14)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1085616 bytes
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1127)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1558)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:405)
04-12 20:13:35.997  1454  1499 E AndroidRuntime: 	... 21 more
```

**Comment by greyson-signal** [comment]
How did you receive a message with a 500kb body? Even with long-message sending, behind the scenes any text over 2kb is converted into an attachment. Are you using a modified client?

**Comment by ByteHamster** [comment]
I am not using a modified client (official Google Play release). The 500kb of text appear when tapping "show full message" but the app crashed even without tapping.

Additionally, while the huge message was displayed in the preview of the conversation list, the list was slow. When I scrolled the conversation off-screen and then scrolled back to the top, the list froze for a few seconds just before the conversation appeared on screen. This does not happen with regular media messages or 2000 character messages.

To me, this looks a bit like the huge message is displayed on the TextViews and notification as a whole instead of the first 2000 characters only. If you need that, I can try to reproduce the problem

**Comment by greyson-signal** [comment]
Yeah, so the confusing part is that 

1) Clients shouldn't be able to send more than 64kb of text. Do you know what device sent you the message? iOS, Android, Desktop, etc. (Sorry, when I asked if you were using a modified client, I meant to ask was your chat partner using a modified client)
2) Even if the client did send a message that large, the body of the message should only contain the first 2000 characters. Reading the rest requires the client to read a separate attachment. So things like the conversation list and stuff should never be dealing with > 2000 characters.

**Comment by ByteHamster** [comment]
> Do you know what device sent you the message? iOS, Android, Desktop, etc

The other person does not reply on Signal anymore but I am pretty sure it was sent from Desktop. When trying to copy the text on my phone, I get a Toast saying that there was an error while copying to clipboard. The text contains logcat output, so I doubt that it contains special chars.

> Even if the client did send a message that large, the body of the message should only contain the first 2000 characters. Reading the rest requires the client to read a separate attachment. So things like the conversation list and stuff should never be dealing with > 2000 characters.

I can reproduce the problem. I just sent a huge message from desktop v1.23.2 to my phone. The conversation list lags when this specific conversation is scrolled to. Additionally, the conversation needs many seconds to load. When sending another message, so that the long message no longer is previewed, the conversation list is fast again.

When sending a message with ~3kb, the conversation list does not lag. Also, the message list opens instantly. When scrolling up in the message list, the app freezes as soon as I reach the 500k message.

**Comment by greyson-signal** [comment]
So apparently the current version of desktop will just let you send arbitrarily long messages. I'll add some defensive things to chop off extra text.
