### ISSUE TITLE
Unable to play audio file attachments on both ends (acc, flac etc) 

### ISSUE THREAD

**Issue by eggsgent** [signalapp/Signal-Android#8761]
Unable to play audio file attachments on both ends (acc, flac etc), similar to  #8628, but not specific to audio format nor app creating the audio file.

1. A sends an audio file (tested with aac and flac) to B
2. B receives the file
3. A and B try to play back the audio file by pressing Play media button in Signal chat window

### Actual result: 
Neither party can play back the audio file, exporting the file proves that the file sent and received is not corrupt

### Expected result:
Both parties should be able to play back the attached audio file

### log:
https://debuglogs.org/e2ce0f44cabce4d45c032d0e31ccd6cd58caa8b60ac712aa0669de06b5166991

around here:

Header: user-agent : OWA 2019-04-13 14:16:03.780 CEST I AttachmentServer: range is: bytes=1516532346- 2019-04-13 14:16:03.782 CEST I AttachmentServer: range found!! 1516532346 2019-04-13 14:16:03.784 CEST I AttachmentServer: headers: HTTP/1.1 206 Partial Content Content-Type: audio/mp4 Accept-Ranges: bytes Content-Length: -1515833029 Content-Range: bytes 1516532346-699316/699317 Connection: Keep-Alive 2019-04-13 14:16:03.803 CEST W AudioSlidePlayer: MediaPlayer Error: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: byteCount < 0: -1515833029 2019-04-13 14:16:03.804

**Comment by junitas** [comment]
I just had this same bug happen, with the same` IllegalArgumentException: byteCount < 0`. Posting a link to entire debug log. Apologies for not parsing just the relevant parts; exporting to debuglogs.org makes the formatting screwy and I can't delineate very easily.

https://debuglogs.org/c55c675b04ed56ea5d7726aa7233629be44fbbe9b630736027cc007393da4f55

@greyson-signal This reminds me a bit of a bug from a while ago, #7482 where the byte offset couldn't properly be calculated. Just tagging it here in case it is helpful.

**Comment by breversa** [comment]
The issue persists as of version 5.3.7.1  :

https://debuglogs.org/b8f47f5e0bb66ebddcaa9fdefdc326cc7a0c10ed72ca5deca2409d6a3380b3c6
