### ISSUE TITLE
UI Glitch in Landscape Mode

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8762]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- flip the phone
- Start typing

### Screenshots
![signal-attachment-2019-04-12-060905](https://user-images.githubusercontent.com/34171942/56083257-ba1a2a80-5e37-11e9-9a97-f618ba205cad.png)

### Device info

**Android version:** 6.0.1
**Signal version:** 4.37.2

**Comment by alan-signal** [comment]
You have not specified the actual result and expected result from the template so it's unclear what you are reporting.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Closing for now.

**Comment by Xashyar** [comment]
@alan-signal done!
thought the screenshot was self-evident.
