### ISSUE TITLE
Inconvenience related to groups

### ISSUE THREAD

**Issue by notEvil** [signalapp/Signal-Android#8763]
Imagine you switch to a new phone number and forget to unregister from Signal before registering with your new number. There is no way to leave groups (old number) in this case, and nobody in those groups is able to remove you (old number) either. You are forced to force everyone into a new group (new number), additionally loosing a continuous history. And in case you are not successful and somebody is using an old group, the messages may get delivered to someone who gets assigned your old number and registers at Signal.

See https://github.com/signalapp/Signal-iOS/issues/1621

Imho this can't be ignored

**Comment by johanw666** [comment]
This is already extensively discussed on the user forum: https://community.signalusers.org/search?q=group%20administration

**Comment by notEvil** [comment]
Oh, you are right, my apologies! Seems like good ideas addressing this issue have been proposed there recently
