### ISSUE TITLE
Missing feature Re-Import System SMS Database 

### ISSUE THREAD

**Issue by smarek** [signalapp/Signal-Android#8765]
### Bug description
Once the Signal is set as default SMS application, there will be SystemSmsImportReminder shown, to do the system sms database migration to signal internal db.

It is impossible to invoke this step manually as far as I can tell, and option to re-import system sms does not appear again, once the import ran once.

It is possible to repeat the import process, only by deleting `shared_prefs/SecureSMS.xml` and restarting the app. Both DatabaseMigrationActivity.java and ApplicationMigrationService.java are non-invokable from the outside (not exported)

### Steps to reproduce
Change default SMS app to Signal
Import System SMS database
Change default SMS app to different app
Change default SMS app to Signal
Missing "import system sms" reminder

This also applies to cases, where you migrate to the new device, and set the Signal as default SMS app before system SMS backups are restored.

### Device info
**Device:** Nexus 5X 
**Android version:** 8.1
**Signal version:** 4.37.2

### Options

  1. Add the option to import system sms database manually to `Settings > SMS and MMS`
  2. Un-set migrated status from ApplicationMigrationService.java when the app is un-set as default system SMS app, to allow the reminder to re-appear

**Comment by pedroapero** [comment]
I used to have Signal alongside my regular SMS application. Since I can't invoke the restore feature manually, I'm unable to restore both my SMS and my Signal messages.
I had to play with xeals/signal-back and "SMS backup&restore" to merge them as regular SMS conversations before reinstalling Signal (I lost all my Signal conversation authentications).

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by jiemeb** [comment]
Hi,
How do you remove shared_prefs/SecureSMS.xml ?
Thanks
