### ISSUE TITLE
Change the shared message & link to be more useful

### ISSUE THREAD

**Issue by mariusa** [signalapp/Signal-Android#8767]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Try to get some friends to use Signal

### Steps to reproduce
- using Android app, probably iOS is the same:
- share icon
- see default message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Share signal text & link are confusing

I've shared the default text&link generated by Signal to a few friends via WhatsApp:
```
Let's switch to Signal: https://sgnl.link/1KpeYmF
```

Nobody understood what that is. On top of it, the link looks like a referral link, probably I get some benefits if they sign up.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Please change that to
```
Let's use Signal for our messaging: https://signal.org
```

People need to understand what Signal is and WHY is it better than WhatsApp, before considering to install it.

### Device info

**Device:** Xiaomi
**Android version:** 9.0.0
**Signal version:**  from today

**Comment by greyson-signal** [comment]
1. As noted in the issue template you filled out, Github is only for bug reports. Discussion about changes should take place in [the forum](https://community.signalusers.org/).
2. This text is just a suggestion. You're more than welcome to edit it before you send.

Thanks!
