### ISSUE TITLE
Textual attachments are not  handled properly

### ISSUE THREAD

**Issue by PositronicBrain** [signalapp/Signal-Android#8768]
## Bug description
When a textual (e.g. `.txt` `.json`) attachment in a Signal chat is opened with an external viewer the viewer receives empty content
### Steps to reproduce
- Attach a `.txt` file in a chat
- select open with Chrome

**Actual result:** Chrome opens an empty page
**Expected result:** Chrome should display the text (works in other messaging apps e.g. whatsapp)

### Device info
Android devices

**Comment by Genis-Sage** [comment]
just tried it, and send a .txt file as "note to self" from Signal Desktop to my Android device

Chrome opens an empty file
Firefox, HTML viewer, FX text viewer, OpenDocument Reader, Office Documents Viewer all show the content

**Comment by PositronicBrain** [comment]
It does not work for me with HTML viewer, but Firefox works. Any idea what might cause the problem? I am working on a react native app and I should be able to open json file in signal, but what I get are empty files.

**Comment by jensMF** [comment]
I have this error with gpx files and OsmAnd (https://github.com/osmandapp/Osmand) but it works with other apps (The Mantrailing App, GPX Viewer). I opened an issue https://github.com/osmandapp/Osmand/issues/7624 there, too. They try to fix this on their site, but when this gets more robust in Signal it would be great. Or if there where hints, what the problem could be.

**Comment by jensMF** [comment]
I tracked it down in OsmAnd. The file name is not retrieved correctly by the apps where it does not work and is `null`.
