### ISSUE TITLE
Attachment Button Disappears in Landscape Mode

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8769]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Related: #3623 & #5294
When the keyboard slides up in landscape mode the interface (either Dark or Light) broken as shown in the screenshots. 

### Steps to reproduce
- flip the phone
- Start typing

**Actual result:** The Interface gets disentangled:

![signal-attachment-2019-04-12-060905](https://user-images.githubusercontent.com/34171942/56083257-ba1a2a80-5e37-11e9-9a97-f618ba205cad.png)

**Expected result:** Screen Rotation must preserve the Signal send and attachment button as well as theme color.

![signal-attachment-2019-04-12-060905](https://user-images.githubusercontent.com/34171942/56318494-924aff80-6174-11e9-8b10-e525aaaffbfb.png)

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.38.2

**Comment by haffenloher** [comment]
> Same as: #3623 & #5294

I'm confused. Your screen shot shows no sign of the old bug you're referring to. The compose hint and the send button texts are the same. Did you mean to include a different screen shot?

Regarding your issue title: There has never been an attachment button in landscape compose mode; that's the expected behaviour.

**Comment by Xashyar** [comment]
@haffenloher, I updated the post with screenshots of how landscape mode should look like, in **Expected result:.**, I Know #3623 & #5294 refer to Insecure SMS sending, but I saw there the same visual glitch as well.

**Comment by greyson-signal** [comment]
I feel like this whole "landscape in text view takes over the whole screen" thing has annoyed me for quite a while, so I've turned it off :) I have no idea why Android made it the default behavior. Fixed in the 4.39 candidate branch.

**Comment by Xashyar** [comment]
Thanks! @greyson-signal

**Comment by Xashyar** [comment]
Perhaps the issue can be reopened upon: b5d37702f9cc88412a72e628d05be7bb1c61a9fb

**Comment by greysonp** [comment]
No, I think it's just gonna stay like this for the time being. Tested a bunch of other apps and it's actually pretty common. Most devices don't even have enough space to show multiple lines of text in landscape.

**Comment by greyson-signal** [comment]
No, I think it's just gonna stay like this for the time being. Tested a
bunch of other apps and it's actually pretty common. Most devices don't
even have enough space to show multiple lines of text in landscape.
