### ISSUE TITLE
Push messages not working with 4.38.2

### ISSUE THREAD

**Issue by djetzen** [signalapp/Signal-Android#8770]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since updating to version 4.38.2 I do not get any push messages. I checked that they are still enabled in the settings (both Android Pie and Signal itself) and they still are. Also did a restart of the phone.

### Device info
**Device:** HMD Global (Nokia) 5
**Android version:** Android 9 - Patch Level February 2019
**Signal version:** 4.38.2

### Link to debug log
https://debuglogs.org/2740e699fd7545f87f4a30aa99e52bfc40bc7e94a0cd4f1e776442326f535ce2

**Comment by greyson-signal** [comment]
Can you be more specific? I can see in the logs that you

1. Have received many messages over the last several hours
2. Have had notifications posted for many messages over the last several hours

I did notice that the most recent "messages" that you're getting are delivery receipts -- did take the debug log not long after you upgraded?

One possibility is that you got hit by a spurious deregistration. Can you try unregistering and then re-registering again? (Settings > Advanced > And then toggle off and on "Signal messages and calls)

**Comment by djetzen** [comment]
> Can you be more specific? I can see in the logs that you
> 
> 1. Have received many messages over the last several hours
> 2. Have had notifications posted for many messages over the last several hours
> 
> I did notice that the most recent "messages" that you're getting are delivery receipts -- did you take the debug log not long after you upgraded?
> 
> One possibility is that you got hit by a spurious deregistration. Can you try unregistering and then re-registering again? (Settings > Advanced > And then toggle off and on "Signal messages and calls)

You are right. After toggling off and on again it did work. Is this a known issue? And how can I see, whether this was happening? 

Besides of this, the notifications were only appearing at the desktop app and I did take the log immediately before creating this issue here. The upgrade I performed yesterday, if I remember correctly. And the lots of messages are correct, as Signal is my main messenger.

Thanks again for the hint with the toggle!

**Comment by greyson-signal** [comment]
We're tracking this unregistration issue here: #8585 

This is very much a bug and shouldn't be happening. There's no good way for you personally to know besides someone else telling you that messages aren't being delivered or you noticing that your desktop is getting them but not your Android device.

If this happens again, follow up in #8585
