### ISSUE TITLE
"Insecure SMS" setting won't stick; contacts don't get messages

### ISSUE THREAD

**Issue by iduno8912** [signalapp/Signal-Android#8771]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When "Insecure SMS" is selected for a certain contact, the app forgets the setting when navigating away from the message. This forces the user to re-select it every time. Many people who have signal but don't use it as the default messenger don't check their Signal messages often or at all. Most of these people forget they installed it. This forces me to select "Insecure SMS" every time I need to message one of these people. I consider it a glitch that Signal does not remember this setting once it is selected for a certain contact. Fixing this would make Signal a practical choice for a default messenger. Most people refuse to use signal as default because a lot of recipients don't receive/check the messages that are sent. I use it as default and countless times my messages go unanswered because I forgot to reset this setting.

### Steps to reproduce
- Open a conversation with someone who doesn't use signal as default or has signal notifications turned off.
- Long press the send button to select "Insecure SMS"
- Navigate away from that conversation and return to it.

**Actual result:** The "Insecure SMS" has reverted to "Signal"
**Expected result:** I expect Signal to remember the SMS setting for specific contacts to compensate for the large number of people who install the app and forget about it.

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 9
**Signal version:** 4.37.2

**Comment by westonal** [comment]
It's coming in 4.38.

**Comment by iduno8912** [comment]
> 
> 
> It's coming in 4.38.

I certainly hope so. I'm not sure how much longer I can keep it as my default messenger like this. I'll wait it out like a big boy.
