### ISSUE TITLE
Voice message playback paused without interaction

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8777]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I started a voice message while the phone laid on the table. Didn't touch it. The audio stopped in the middle.

### Device info

**Device:** Pixel 3
**Android version:** 9
**Signal version:** 4.38.2

### Link to debug log

https://debuglogs.org/7efad207815292ad3608d97e3f309a3d17ab4eecb03732f67ccd5996824a1fd8

**Comment by alan-signal** [comment]
> The audio stopped in the middle.

Please tell us more, such as how long it was recording for. Did anything happen to the phone, like did its screen turn off for example.

**Comment by nutts0** [comment]
No the screen didn't turn off. In this case it would go off. This is known behavior. But my phone was on the table. The message was not longer than 30 seconds. I must say I'm not talking about recording. It was playing a voice message I got from somebody.

**Comment by alan-signal** [comment]
How about repeatability? If you repeat it, does it consistently stop at the same point in the playback?

**Comment by nutts0** [comment]
Not with this message. But I encountered it with several other. I first thought that it might be some message I got while it played. But in this particular case. I received the message half an hour before I actually listened to it. The phone was on aeroplane mode. Screen was on and no other things interfered with it.
