### ISSUE TITLE
signal doesn't send messages anymore

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- send a big video in different chat
- when the upload finishes it won't be send you will see the circle that is rotating without sending the video even after hour

**Actual result:** video are not sent
**Expected result:** video should be sent

### Device info

**Device:** Pixel 2 XL
**Android version:** 9
**Signal version:** latest

### Link to debug log

t 

https://debuglogs.org/c6d2413343ff9711e696e6c85b2d6bab744c1aa8b3f049aa0f04f7102daa7d19

**Comment by leonardoporp** [comment]
Please help because I cannot even send any message to other contacts in Signal

**Comment by greyson-signal** [comment]
This is a bug that sometimes happened with our old message sending system
that was backed by a library called WorkManager. In the short term, try
restarting your phone or force-stopping and restarting Signal.

Alternatively, you can join the Android beta (4.38.x) where we just
replaced WorkManager with a different system that hopefully fixes this
issue.

**Comment by leonardoporp** [comment]
I have joined it right now but the problem seems to persist

**Comment by greyson-signal** [comment]
Can you please post another debug log?

**Comment by leonardoporp** [comment]
https://debuglogs.org/fdfd215e1718caa17b4398aac5ec78cfd77f5e5139273642a5f00d460e6db69d

**Comment by leonardoporpora** [comment]
Yes you are right now it's working it just took some time you can close the
issue. Thanks for the great work and support Greyson!

**Comment by greyson-signal** [comment]
Ah good to hear. You had several attachment uploads that were backed up, so it makes sense that it took a while. Glad it cleared up!
