### ISSUE TITLE
Accept call button not displayed when receiving signal call

### ISSUE THREAD

**Issue by dlhowell** [signalapp/Signal-Android#8782]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the incoming call screen is displayed, the green button to accept/answer the call is invisible. Interacting with the area the button would normally appear has no effect.

### Steps to reproduce
- go to home screen
- receive signal call from another signal user via mobile data

**Actual result:**
On initial receipt of an incoming call, no button is displayed or available on the incoming call screen to answer the call. Going to home screen and back to call via the incoming call push notification causes answer button to appear.

**Expected result:**
Answer button appears initially, allowing call to be answered.

### Device info

**Device:** SAMSUNG SM-N950U (Galaxy Note 8)
**Android version:** 8.0.0
**Signal version:** 4.37.2

### Link to debug log

https://debuglogs.org/81b763af6258d589f2fcd1c1a4cf2396a4e52b33c98fb207031ab19e2ab6dd26

**Comment by Sgn-32** [comment]
Should be solved with the new calling UI from 4.60.
