### ISSUE TITLE
"Insecure SMS" vs "Signal" toggle doesn't match message actually sent

### ISSUE THREAD

**Issue by blerrgh** [signalapp/Signal-Android#8783]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Even though the GUI setting for "Unsecured SMS" is sticky now when you leave and return to the app, Secure Signal messages are still sent instead.

### Steps to reproduce
- Press and hold the send button and select "Insecure SMS"
- Send a message.  It sends via SMS
- back out of the message or exit the app, then come back in
- GUI still says "Unsecured SMS" in the message window. 
- Send a message.  It sends via Signal (secure)

**Actual result:** Message send via Signal despite GUI indications
**Expected result:** Message should send via SMS

### Screenshots
![2019-04-27-13 56](https://user-images.githubusercontent.com/41206759/56855011-7a9e1480-68f4-11e9-97e5-d022cc5d44cf.png)

### Device info
**Device:** Motorola Moto x 2014
**Android version:** Lineage OS 7.1.2
**Signal version:** 4.38.2

### Link to debug log
https://debuglogs.org/ff6b290802d9d81ec5ca8e9b55234546c7fbbda90e671b41908b6d5ed39a7e25

**Comment by mueller-ma** [comment]
Thanks Greyson

**Comment by blerrgh** [comment]
Not sure exactly when this regressed, but I'm having the same issue again on 5.18.5.  It seems to always default to secure signal message even after someone SMSes me.
