### ISSUE TITLE
messages only arrive on open up signal app - FCM issue?

### ISSUE THREAD

**Issue by tipuraneo** [signalapp/Signal-Android#8786]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a few days I noticed that some messages arrive only when the app is opend. Talking to friends this happens across several android versions (4, 5 and 7).

### Steps to reproduce
- phone A is in standby for several minutes, screen locked
- phone B sends a message
- message does not arrive on phone A while it's in standby
- after opening Signal on phone A all messages are arriving

**Actual result:** Messages arrive just during open up Signal
**Expected result:** receiving messages in standby/background

### Device info

**Device:** Samsung Galaxy S4 mini
**Android version:** 4.4.4
**Signal version:** 4.38.2

### Link to debug log
https://debuglogs.org/e4f1622b9655f131c72e8aa4252659092c56d87e22cccd716e771ce8e9fbfcfd

Is this behavior related to FCM?

**Comment by tipuraneo** [comment]
syntax fixed

**Comment by greyson-signal** [comment]
Yeah, at minimum I see several examples in your logs of the system bunching up a long series of FCM messages. Not much we can do about it at the moment.
