### ISSUE TITLE
Disappearing Messages are retained (i.e. leak) through reply previews

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#8787]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a disappearing message is replied to in a non-disappearing message, the disappearing message content is leaked in the reply even after the original is gone.

### Steps to reproduce

1. Set disappearing messages in some conversation to e.g. 5 minutes (it doesn't really matter)
2. Send a message
3. Turn off disappearing messages
4. Send a new message with the first message set as the message being replied to
5. Wait for the first message to expire

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The text and (if applicable) picture of the first, now-disappeared message can be viewed in the reply.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The message should be truly gone (note that tapping on the reply _does_ say "original message not available"). I would suggest a "(message disappeared)" placeholder or something but it doesn't really matter.

### Screenshots

Not providing these since obviously I was using disappearing messages for a reason.

### Device info

**Device:** Pixel XL
**Android version:** 8.1.0 (LineageOS 15.1-20190309-NIGHTLY-marlin)
**Signal version:** 4.38.2 (I am on the beta channel)

### Link to debug log

If really wanted I can capture a debug log but it doesn't seem necessary and I don't have one handy because this happened a while ago.

**Comment by greyson-signal** [comment]
Quoting a message can be thought of as copy-pasting a message. Not too different from

> Quoting

in Github, or in an email. So this is working-as-intended.

**Comment by strugee** [comment]
@greyson-signal that makes sense now that you say it. However, the problem here is that users understand very well the semantics of copy and paste and they understand that it's making a _copy_ of the message. That's not the case with replies because replies - and disappearing messages (and how those features interact) - is not a universally understood UX metaphor. That kind of rich conversation element is too new.

I obviously can't speak for anyone else, but personally I thought of the reply feature as mostly just referencing an older message. Indeed that's how it's presented in the UI: a preview of the "referenced" message is shown and you can tap it to be taken to the full original. I understand that technically that may not be how it works but that's beside the point - I don't think it's at all clear in the UI that these messages will be retained.

Here's a couple other solutions I thought of to this problem:

* As suggested in the original report, quoted replies to disappearing messages could be erased along with the originals
* Non-disappearing replies to disappearing messages could be disallowed altogether.
* A warning could be shown when tapping the reply button on a disappearing message while the current setting is non-disappearing, stating that the reply will contain parts of the original message

However, I don't think the other two (especially the last one) are great UX, which is why I didn't suggest them to begin with.

Another argument in favor of making this change is the principle of least surprise: features should behave in a way that is least surprising. I argue that at least some users, possibly many users, will be surprised that disappearing messages do not disappear when quoted in replies. However, I doubt that any user would be surprised if they _did_ disappear in replies, so we should pick the latter since that surprises less users (and errs on the safe side too). Signal is about usable security and it should do the Right Thing™ by default, without users needing to know details like this. (This argument, of course, ignores the code maintainability cost, but I think that's a small price to pay.)

I do still regard this as a security bug, even if only a UI bug. However, if you still feel strongly that it's not, I can take this to the forums since I know you all don't like having discussions in GitHub issues.

**Comment by nutts0** [comment]
Hmmmm. I think this will be a very rare case that somebody quotes a disappearing message. When the timer is set off

**Comment by strugee** [comment]
> Hmmmm. I think this will be a very rare case that somebody quotes a disappearing message. When the timer is set off

This is easy to trigger if (like me) you tend to carry on conversations normally but will turn on disappearing messages for one or two sensitive messages only, and then immediately turn them off again. The disappearing message is natural to quote in a non-disappearing message if it's the only part of the conversation that's disappearing.

**Comment by nutts0** [comment]
Let's take this to https://community.signalusers.org/

I think you have a point.
