### ISSUE TITLE
Signal does not know about Dual SIM before it has been configured as default SMS app

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8789]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a Dual SIM phone Signal usually offers tho choose which number to use to send an SMS message. However, Signal does not show two SIM cards until it has been set as the default SMS app. If Signal is removed as the default SMS app, the dual SIM choice does persist though.

### Steps to reproduce
- Install one SIM card in your phone
- Install and register Signal, do not make it your default SMS app
- Add another SIM card to your phone
- Try to send a message as SMS. Note you don't get to choose which SIM card to use.
- Configure Signal as default SMS app.
- Now you see two SMS options when you try to send as SMS.
- Even if you choose an other SMS app to be the default, Signal will keep offering this choice.

**Expected result:**  Signal should discover Dual SIM even if it is not and never has been the default SMS app. Users who have not used Signal as default SMS app might still want to send SMS over either SIM card.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9
**Signal version:**  4.39.0 (and also seen in earlier versions)

### Link to debug log
https://debuglogs.org/85b96fd5f4ba2a34267ee007395eb555774a7d77d214e0512c089eedaeecf74c

**Comment by greyson-signal** [comment]
We can't do much with SMS if we're not the default handler due to Google Play Store policy. See:
https://play.google.com/about/privacy-security-deception/permissions/

**Comment by Meteor0id** [comment]
@greyson-signal I can't go back in time to test it, but does a user get to see an informational pop-up when he tries to send an SMS before setting the apps as default SMS app?
Purpose of such pop-up would be to advise the user that Signal needs to be the default SMS app in order to discover a second Sim card.

**Comment by greyson-signal** [comment]
We prompt the user in multiple locations to set Signal as the default SMS, including if they attempt to send and SMS when we're not the default handler. As far as the contents of the pop-up, I believe it's sufficient as-is.
