### ISSUE TITLE
Poor color contrast in information banner of "submit debug log" view.

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8790]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

**Actual result:** Words are difficult to read, especially when the phone dims during night time.
**Expected result:** Decent amount of contrast, even if the phone adjusts the color temperature during nightly hours.
### Screenshots
![signal-attachment-2019-05-01-005304](https://user-images.githubusercontent.com/34976212/56998555-f1186c00-6bab-11e9-81e1-952155993936.png)

**Comment by Meteor0id** [comment]
Do note that the text is quite readable here, but not so much on a small and phone DIM screen.

**Comment by alan-signal** [comment]
Thanks, are you aware of the [Accessibility Scanner app from Google]( https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)?

![image](https://user-images.githubusercontent.com/48254818/57020681-6e6dcc00-6c00-11e9-8910-c79d51d14941.png)

It agrees on this item.

These kind of reports would be useful to help choose where to spend the effort first.

**Comment by Meteor0id** [comment]
> These kind of reports would be useful

Why would you need such report? I just told you the contrast is insufficuent, didn't need this too for it. Obviously the text should not be brown, or at least darker.

But glad it agrees with me.

**Comment by greyson-signal** [comment]
> Why would you need such report? I just told you the contrast is insufficuent, didn't need this tool for it. Obviously the text should not be brown, or at least darker.

This tool shows mathematically that there's too little contrast, as opposed to someone saying there is. It helps avoid personal bias. Also, please remember to be polite.

**Comment by Meteor0id** [comment]
I think it is inpolite to not just say thank you for reporting this obvious contrast issue.

Sure, people might be biased. Dubble checking should always be done. But to assume a biased opinion, and to let a tool judge what your eyes can already confirm while a picture was included to, seems technocratic.

**Comment by greyson-signal** [comment]
We appreciate the report :) Alan was just suggesting a tool that can be used in the future. Instead of having to make comments like:

> Do note that the text is quite readable here, but not so much on a small and dimmed phone screen

you can post the screenshot like Alan did, showing the bad contrast ratio. And to be clear, it was given as a suggestion, not a requirement.

Also wanted to clear up that when I said the tool helps avoid personal bias, I wasn't trying to disqualify your issue saying that *you* are biased, I was just answering your question of "Why would you need such report?" in the general case.

Thanks!

**Comment by Sgn-32** [comment]
There have been some changes in the "submit debug log"area prior to some versions.
Didn't find the exact version and the commit. But should be solved.

**Comment by Meteor0id** [comment]
I firgot to check if this issus had been marked solved. Let's not bother with finding the commit, it's solved.
