### ISSUE TITLE
Signal constantly crashes, but in airplane mode everything is fine

### ISSUE THREAD

**Issue by tribut** [signalapp/Signal-Android#8791]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal constantly crashes every few seconds, even when not open (possibly every time it receives a message?). It also crashes immediately when opened.

However, when I turn on airplane mode before I open Signal, it opens fine and all messages appear to be there, even those that arrived after it started crashing.

### Steps to reproduce
- Wait a few seconds or open Signal

**Actual result:** Observe crash
**Expected result:** Work normally

### Device info

**Device:** Samsung S8
**Android version:** 9, Patch level 2019-3-1
**Signal version:** 4.39.0

### ADB log

~~~~
05-01 16:59:30.819  7151  7319 E AndroidRuntime: FATAL EXCEPTION: JobRunner-1
05-01 16:59:30.819  7151  7319 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7151
05-01 16:59:30.819  7151  7319 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.Util.copy(Util.java:273)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
05-01 16:59:30.819  7151  7319 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
~~~~

**Comment by greyson-signal** [comment]
This will be resolved in 4.39.1. Thanks!

**Comment by trapicki** [comment]
Have the same issue with 4.41.5 again:

Steps to reproduce, Actual & Expected result: like original post.

Bug description: 
After an update from a unknown working version, Signal would not start any more (opens blank screen, then back to launcher again). After reinstall it starts once, but then not any more. Notifications persists, but opening the app does not work. Like original post suggests switching to airplane mode makes it work again. Logcat shows a crash (see below).

App State:
Reinstalled after upgrade from unknown working version.
No Contacts access, no SMS integration.

Device Information:
Phone: Huawei INE-LX1 
Build: INE-LX1 8.2.0.132(C185)
Android Version: 8.1.0
Signal Version: 4.41.5

ADB Log:
06-10 20:51:18.834  6310  6427 E AndroidRuntime: FATAL EXCEPTION: JobRunner-2
06-10 20:51:18.834  6310  6427 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6310
06-10 20:51:18.834  6310  6427 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 20:51:18.834  6310  6427 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 20:52:08.897  7151  7179 E AndroidRuntime: FATAL EXCEPTION: JobRunner-3
06-10 20:52:08.897  7151  7179 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7151
06-10 20:52:08.897  7151  7179 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 20:52:08.897  7151  7179 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 20:55:00.397  8277  8307 E AndroidRuntime: FATAL EXCEPTION: JobRunner-1
06-10 20:55:00.397  8277  8307 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8277
06-10 20:55:00.397  8277  8307 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 20:55:00.397  8277  8307 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 20:55:03.259  8350  8378 E AndroidRuntime: FATAL EXCEPTION: JobRunner-4
06-10 20:55:03.259  8350  8378 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8350
06-10 20:55:03.259  8350  8378 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 20:55:03.259  8350  8378 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 21:20:11.103 10663 10693 E AndroidRuntime: FATAL EXCEPTION: JobRunner-2
06-10 21:20:11.103 10663 10693 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10663
06-10 21:20:11.103 10663 10693 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 21:20:11.103 10663 10693 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 21:20:12.105 10734 10761 E AndroidRuntime: FATAL EXCEPTION: JobRunner-2
06-10 21:20:12.105 10734 10761 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10734
06-10 21:20:12.105 10734 10761 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 21:20:12.105 10734 10761 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-10 21:20:14.600 10812 10840 E AndroidRuntime: FATAL EXCEPTION: JobRunner-3
06-10 21:20:14.600 10812 10840 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10812
06-10 21:20:14.600 10812 10840 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-10 21:20:14.600 10812 10840 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)

**Comment by greyson-signal** [comment]
@trapicki There's a handful of devices out there that refuse to use the AesGcmProvider we implemented to solve the initial crash. Do you mind posting a link to a full debuglog after an app restart? (Settings > Advanced > Submit debug log) Thanks.

**Comment by trapicki** [comment]
This is from when it worked exactly once after switching from airplane mode to normal (Wifi/Radio) connections on.

After closing (changing to launcher) and reopening, it would crash again. Obviously no full report accessible after that. I could not figure out how to reproduce the log part of the debug report with `adb logcat` without all the other stuff from the system and other apps.

https://debuglogs.org/2f1526903fcd55b65f5279c87f1465dee57dd1e1c62e6b0a67fe5580277f8125

**Comment by trapicki** [comment]
@greyson-signal Anything new on this? I report this on behalf of some other person and will soon not have any chance any more to draw debug logs. Please tell what I can use to dump a log even if signal is not starting any more.

**Comment by m5h1** [comment]
I have the same issue using version 4.43.4

I tried uninstalling the app, clearing cache and storage. Registration process goes smoothly. once I receive a message the app begins crashing again  
**ADB Log:**

`07-01 19:54:38.961  3647  3673 E AndroidRuntime: FATAL EXCEPTION: JobRunner-1
07-01 19:54:38.961  3647  3673 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3647
07-01 19:54:38.961  3647  3673 E AndroidRuntime: java.lang.AssertionError: Need: 12272 but only have: 8192
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
07-01 19:54:38.961  3647  3673 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: java.lang.AssertionError: Need: 12272 but only have: 8192
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
07-01 19:54:38.961  3647  3673 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
07-01 19:54:38.966  3647  3647 I PassphraseRequiredActionBarActivity: onPause()
07-01 19:54:38.974  3647  3673 I Process : Sending signal. PID: 3647 SIG: 9`
