### ISSUE TITLE
QuickReply always sends Signal message regardless if last message was SMS

### ISSUE THREAD

**Issue by blerrgh** [signalapp/Signal-Android#8792]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive an SMS from a contact, and use the "quick reply" function in the notification window to reply, it always replies with an encrypted signal message.  Even if my last selection in the chat window was SMS (which is a sticky option now)

### Steps to reproduce
- select "Insecure SMS" and send a message
- exit the app, wait for a response.  Use Quick Reply to reply.
- message sent will be Secure Signal instead of Insecure SMS.

**Actual result:** message sent will b e secure signal
**Expected result:** Message sent should match the sticky option in the chat window (or possibly even better, whatever kind of message you are replying to, e. g. if you quick reply to a secure message your message should be secure but if you quick reply to an sms your message should be sms)

### Device info

**Device:** Motorola Moto X 2014
**Android version:** Lineage OS 7.1.2
**Signal version:** 4.38.3

**Comment by adamparish** [comment]
I also verified this issue on:

**Device:** Google Pixel 3
**Android version:** 9
**Signal version:** 4.38.3

Nice bug find @blerrgh

**Comment by adamparish** [comment]
@greyson-signal I tested this on the beta channel with my Pixel 3 ver 4.40.1. Worked as expected. Thanks for fixing this! 

cc: @blerrgh thanks for filing this issue.

**Comment by greyson-signal** [comment]
Thank @alan-signal  :)
