### ISSUE TITLE
Signal and WireGuard delayed receiving and sending

### ISSUE THREAD

**Issue by Atrate** [signalapp/Signal-Android#8804]
- [x]   I have searched open and closed issues for duplicates
- [x]   I am submitting a bug report for existing functionality that does not work as intended
- [x]   I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]   This isn't a feature request or a discussion topic

-------

## Bug description

To be honest, I don't know if it's an actual bug, just something I've noticed on my 2 phones.

My friend has also reported that messages take longer to send, they do have gapps.

If a phone doesn't have Google Play Services and uses a Wireguard (userspace) VPN, Signal often delays notifications a lot (up to 30 mins), while other apps work perfectly fine.

Sometimes messages won't send, force stopping Signal helps alleviate that.

This didn't occur while using OpenVPN or StrongSwan.

Making Signal and WireGuard a priviledged system app didn't help, nor did allowing them to run in the background. 

## Steps to reproduce
- Use Signal without Gapps, with a WireGuard VPN
- Someone sends me a message while Signal isn't foreground
- Message takes a long time to arrive
- Sending messages sometimes doesn't work without killing Signal

## Device info

Device: LG G6
Android version: 9.0.0
Signal version: 4.38.3 
Wireguard version: 0.0.20190319
Wireguard Go Userspace Backend version: 0.0.20181222

## Screenshots
No screenshots necessary, I think, can still provide if necessary, but it's just delayed messages

## App state
Signal messages and calls registered, SMS disabled, passphrase enabled

## Link to debug log

https://debuglogs.org/816f1c1ac906ec2305d230ffae6f80482eef33b3642644e6ba4590aa3f7f6e7f

**Comment by greyson-signal** [comment]
Please fill out the issue template, especially a debuglog.

**Comment by MegaArthur** [comment]
Done

**Comment by MegaArthur** [comment]
Update:

The issue doesn't occur when WireGuard is integrated into a custom kernel.

**Comment by MegaArthur** [comment]
Update 2:

The issue also happens when WireGuard is integrated into a custom kernel, the delay is just smaller.
