### ISSUE TITLE
Hide number phone

### ISSUE THREAD

**Issue by dani230** [signalapp/Signal-Android#8805]
SMS messages from my phone numbers have been intercepted by malicious people several times revealing my number is unsafe (thanks to the mobile operator no my smartphone).

I do not want to facilitate that someone can see the number on the screen of my interlocutor.
People have already looked my wire nickname this way.
Whatsapp is safer in this regard :/ .

**Comment by Cerberus0** [comment]
Hi @dani230,

Signal only uses GitHub for bug reports. Feature requests and non-bug discussions should go on the [community forum](https://community.signalusers.org/). I suggest closing this issue and continuing the conversation on the community forum. You can easily join the forum with your existing GitHub account.

If you're new to this project, I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md
