### ISSUE TITLE
recurring crashes when opening group chat

### ISSUE THREAD

**Issue by stevens-signal** [signalapp/Signal-Android#8807]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
- Signal app crashes whenever group chat / conversation is opened (ie. conversation with 3+ people).
- Crash doesn't occur when opening normal conversations (ie. chats only between myself and one other person).
- Signal app has all permissions enabled.
- Crash happens on WiFi, mobile data connections (4G), and when internet access is disabled
- Clearing cache doesn't help
- Rebooting phone doesn't help
- Possibly related to bugs https://github.com/signalapp/Signal-Android/issues/8667 https://github.com/signalapp/Signal-Android/issues/6464 https://github.com/signalapp/Signal-Android/issues/6661

### Steps to reproduce
- Open app
- Click on group chat / conversation with 4 people
- App crash

**Actual result:** Can't open group chat / conversation

**Expected result:** Open group chat / conversation and read messages.

### Screenshots
N/A

### Device info

**Device:** Samsung S9 (model: SM-G960F)
**Android version:** 9 (security patch level: 1 April 2019)
**Signal version:** 4.39.4

### Link to debug log
https://debuglogs.org/2baa4f57daeea7fd6b0ac828f8a91113158ccbcb825ea89154e697a05cfbfc2d

**Comment by alan-signal** [comment]
No available transport options:

```
05-10 17:05:49.285 10307 10307 E AndroidRuntime: FATAL EXCEPTION: main
05-10 17:05:49.285 10307 10307 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10307
05-10 17:05:49.285 10307 10307 E AndroidRuntime: java.lang.AssertionError: No options of default type!
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.getSelectedTransport(TransportOptions.java:107)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:189)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.setDefaultTransport(TransportOptions.java:63)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.SendButton.setDefaultTransport(SendButton.java:86)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.handleSecurityChange(ConversationActivity.java:1184)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.initializeSecurity(ConversationActivity.java:1314)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.onCreate(ConversationActivity.java:343)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:52)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7326)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7317)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6981)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-10 17:05:49.285 10307 10307 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Please confirm, this affects all of your Signal (i.e. not SMS) group conversations? Or just some?

**Comment by stevens-signal** [comment]
Affects the single Signal group conversation that I'm part of. To my knowledge, I don't have any other group conversations (signal or SMS).

However, it's possible that an SMS (or MMS) message may have been sent to the group (not deliberately) either by me or by another participant.

The Signal group conversation started to crash soon after I sent a photo to it.  I have been unable to view the conversation since, even though other people are sending messages to it.

**Comment by alan-signal** [comment]
Signal version: 4.39.4 is the crash version, but do you think you saw it working in that version?

Does your device dual SIM by any chance?

**Comment by stevens-signal** [comment]
IIRC, it started crashing in 4.38.x.  I upgraded to 4.39.4 hoping it would fix things.

The device has only one SIM card installed.  As far as I can tell, the expansion slot has room for either a secondary SIM card, or an SD card.  Neither are installed.

**Comment by stevens-signal** [comment]
Possible further info: at the time of sending the photo to the group chat (before the crashing started to occur), mobile data may have been disabled on the phone.

**Comment by alan-signal** [comment]
4.40 contains the fix, please let me know if it works for you. It's in Beta now.

**Comment by stevens-signal** [comment]
@stevens-signal 4.40.1 (beta) seems to work correctly. Thanks for the fix!

**Comment by stevens-signal** [comment]
4.40.1 (beta) seems to work correctly. Thanks for the fix!
