### ISSUE TITLE
Use pgp to secure signal code and apk

### ISSUE THREAD

**Issue by gabegattis** [signalapp/Signal-Android#8808]
Currently the operations and software distribution mechanisms for Signal have a few "bugs" related to keys and signing.

It would be a good improvement of Signal operations to make use of pgp signatures on git commits. As you can see on https://github.com/signalapp/Signal-Android/commits/master, most of the commits are unsigned. Without making and checking signatures, everyone developing or running Signal is forced to trust Github and its employees and infrastructure partners etc to secure the code. I don't want to trust Github with that.

My team mandates pgp signature on all commits, including merges. It would be great if signal could do the same. Setting up commit signing is actually quite easy. See https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

Currently, the apk listed at https://signal.org/android/apk/ only uses the built in android apk signing mechanism. It would be an improvement to also include pgp signatures. This is the general purpose standard that is used by developers of operating systems and various other systems. It is much easier to check a pgp signature than the android apk signature, and gpg comes by default with almost every linux distro.

It would be good if the signing keys were available in other places. Having the signed apk and the signing certificate hosted on the same site does little to secure it from tampering. Anyone who can changed the hosted apk can replace the listed certificate. Web of trust for pgp keys helps with this. You can also share the keys/certificates on other platforms. Some of the members of the Signal team are public facing people. Having them share key fingerprints on github, social media, blogs, presentations, etc. helps build confidence that the keys are legitimate.

**Comment by greyson-signal** [comment]
I appreciate the time you've spent writing this, but as noted in our issue template, we use Github exclusively as a bug tracker, and not for general discussions. Please move this over to [the forum](https://community.signalusers.org/). Thank you!
