### ISSUE TITLE
Repeat alerts fail in Android 9

### ISSUE THREAD

**Issue by rustycanb** [signalapp/Signal-Android#8811]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Repeat alert function in Android 9 fails, same settings in Android 7.1.1 work as expected

### Steps to reproduce
Set repeat alerts to 3
Chose default alert sound from Android sound settings
Incoming message alert works once but no repeats are heard

### Device info
Google Pixel 3a
Android : 9 (5320088, PD2A.190115.029)
Signal Version 4.39.4
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log
https://debuglogs.org/96c49ea43f2250c8d87aab1c28bd94d7b8e20dc52303ef1728392a81215aa4f5

**Comment by rustycanb** [comment]
I really like Signal for it's advance privacy, but what is the point of reporting bugs -- even minor ones -- if no one monitors and responses on Gitub?

**Comment by greyson-signal** [comment]
Feel free to check the commit history to see how many people are working on the project. We have to constantly prioritize how we spend out time, and sometimes that means not responding to an issue right away. But consider this reply evidence that, at minimum, the Github issues are being monitored :)

**Comment by rustycanb** [comment]
Great, thanks for your response. I'll do as you advise and check the 'commits'. As I said, this is not a deal-breaker (I'm a big fan of open source) but a nice-to-have feature.

**Comment by junitas** [comment]
I might take some time to look into this over the weekend. If anyone else gets the jump on me though feel free to do it instead :)

**Comment by jakubgregorek** [comment]
I can confirm the issue on Motorola G6 Play running Android 9. The function does not work even if the battery optimization is disabled for Signal.

**Comment by bob46859** [comment]
I'm also experiencing this issue on my pixel 3 (latest update for Android 9, latest Signal release).

**Comment by eclipso13** [comment]
I, too, am having this issue. LG G6 (Android 8). Latest Signal release.

**Comment by bob46859** [comment]
This is also an issue on my friend's Blackberry keytwo phone running Android 8.1.  So it seems to affect Android 8 as well.

**Comment by OttoResponder** [comment]
Having the same issue on a Galaxy S7 sm-g930v with Android 8. Followed the recommended troubleshooting steps  (turning off battery optimization, etc), but no love.

**Comment by VideoPlayerCode** [comment]
Same on Huawei P30 (Android 10 via EMUI 10).

**Comment by rustycanb** [comment]
Bump. Still not fixed. This is a really useful feature...

**Comment by cody-signal** [comment]
Please retry in 4.64 as this should be fixed by https://github.com/signalapp/Signal-Android/commit/b687b1a4c552a63b9ab2249f4c49fceed48f77a2.

**Comment by rustycanb** [comment]
Fixed in 4.64. Thanks Signal team.
