### ISSUE TITLE
Calls not working after moving Signal from iOS to Android

### ISSUE THREAD

**Issue by ppwozniak** [signalapp/Signal-Android#8812]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I used Signal on iPhone 5s. App was working very good. One week ago I changed smartphone and now I am using Samsung Galaxy A7 with Android OS. I installed Signal on Android and registered it. 
Now I can't call to people from my contacts list. I can send all messages (text, audio, video), but calls not working. At screen I see "Dialling" and nothing else. 

### Steps to reproduce
- install Signal on iPhone (ie. 5s) and register Signal
- move SIM card to device Samsung Android A7 with Android and register app 
- try call to someone from contacts list

**Actual result:**
**Expected result:** 

### Device info
**Device:** Samsung Galaxy A7
**Android version:** 9.0
**Signal version:** 4.39.4

### Link to debug log
https://debuglogs.org/4406adfbba1485da902bf1c0b90deb30e655f6997eb08c84e376518d8e78e1ef

**Comment by ppwozniak** [comment]
This problem was described in #7733, @mattimac wrote comment: #7733 https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-406591981
The problem was a mobile operator and version of IP (IPv6 instead of IPv4)
So why Signal not working with IPv6?

**Comment by mattimac** [comment]
@ppwozniak i suspect that the issue can be connected to the implementation of my data network operator (Orange). Orange in Poland pushes default ipv6-only apn to the phone. You get ipv6 address that in theory should be routable to the world but i suspect Orange limited it meaning those addresses are not publicly accessible from outside. This would need some more investigation probably.

**Comment by ppwozniak** [comment]
@mattimac Yesterday I changed APN. I definied new APN with IPv4 settings and activated it. After this operation Signal was started calling normally. 
Soon I will test APN settings and I will write here about addresses.

**Comment by anoop-b** [comment]
I have a similar problem, my ISP uses cg-nat over ipv6, and AAAA type dns queries on text secure-service.whispersystems.org are returned as NOERROR(truncated)

**Comment by mattimac** [comment]
@ppwozniak @anoop-b  can you provide any more feedback and maybe merge with #7733 if needed?

**Comment by ppwozniak** [comment]
Issue #7733 describes the same situation.
