### ISSUE TITLE
Signal crashes when email address entered into phone number

### ISSUE THREAD

**Issue by Lothsahn** [signalapp/Signal-Android#8813]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time I search "clinic", Signal closes immediately and needs to be reopened.  Note: This is caused by bad data in one of my contacts.

### Steps to reproduce
1) Add a contact with a name of Clinic and a phone number (NOT email) of clinic@example.com.  This cannot be done through the Android UI--it has to be imported via an app, etc.
2) Open Signal
3) Click the search magnifying class
4) Select in the search box so the keyboard opens
5) Type clinic
6) Signal closes

Removing the invalid phone number resolves the situation and Signal no longer crashes.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Signal closes

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The search results would be displayed for "Clinic".

### Device info
Nexus 6 Shamu 32 GB
Android 7 & Android 8
Signal Version: 4.39.4

### Link to debug log
(I was able to get the logcat output, but I couldn't get the crash link)
--------- beginning of crash
05-14 15:00:22.414  2956  2956 E AndroidRuntime: FATAL EXCEPTION: main
05-14 15:00:22.414  2956  2956 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 2956
05-14 15:00:22.414  2956  2956 E AndroidRuntime: java.lang.AssertionError: Not e164: clinic@example.com
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:134)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationListItem.bind(ConversationListItem.java:203)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at org.thoughtcrime.securesms.search.SearchListAdapter$SearchResultViewHolder.bind(SearchListAdapter.java:176)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at org.thoughtcrime.securesms.search.SearchListAdapter.onBindViewHolder(SearchListAdapter.java:65)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at org.thoughtcrime.securesms.search.SearchListAdapter.onBindViewHolder(SearchListAdapter.java:23)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-14 15:00:22.414  2956  2956 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger: java.lang.AssertionError: Not e164: clinic@example.com
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:134)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at org.thoughtcrime.securesms.ConversationListItem.bind(ConversationListItem.java:203)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at org.thoughtcrime.securesms.search.SearchListAdapter$SearchResultViewHolder.bind(SearchListAdapter.java:176)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at org.thoughtcrime.securesms.search.SearchListAdapter.onBindViewHolder(SearchListAdapter.java:65)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at org.thoughtcrime.securesms.search.SearchListAdapter.onBindViewHolder(SearchListAdapter.java:23)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.View.layout(View.java:20672)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewGroup.layout(ViewGroup.java:6194)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.Choreographer.doFrame(Choreographer.java:696)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.os.Handler.handleCallback(Handler.java:873)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.os.Handler.dispatchMessage(Handler.java:99)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.os.Looper.loop(Looper.java:193)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at android.app.ActivityThread.main(ActivityThread.java:6718)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at java.lang.reflect.Method.invoke(Native Method)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-14 15:00:22.415  2956  2956 E UncaughtExceptionLogger:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by alan-signal** [comment]
> This cannot be done through the Android UI--it has to be imported via an app

Please elaborate on how you achieved the contact with email in phone number field.

**Comment by alan-signal** [comment]
I was able to recreate with this adb:

```
adb shell am start -a android.intent.action.INSERT -t vnd.android.cursor.dir/contact -e name EmailPhone -e phone a@b.com
```

**Comment by Lothsahn** [comment]
alan,

This was a very old contact.  I don't know the specific method I used to import the contact, but it likely was imported from my old palm pilot database in Android 2.3 on my Nexus S.

**Comment by alan-signal** [comment]
Not to worry, I was able to recreate and have a fix, thanks for the report.
