### ISSUE TITLE
CRITICAL org.thoughtcrime.securesms.transport.UndeliverableMessageException: Trying to send a secure SMS?

### ISSUE THREAD

**Issue by jmayday** [signalapp/Signal-Android#8816]
### Bug description
**UndeliverableMessageException: Trying to send a secure SMS?** 
This is being logged when you try to send a message. There are a couple of issues related to this exception and all of those tickets are closed. Unfortunately issue is still present and what's more - in my opinion it's critical and deserves attention.

### Steps to reproduce
- try sending SMS to non-Signal user

**Actual result:**
Message is not being sent. Exclamation mark appears. Trying to retry sending also fails. 
**Expected result:** 
Message is sent

### Screenshots
No screenshots needed.

### Device info
**Device:** Samsung Galaxy S7 Edge
**Android version:** 8.0.0
**Signal version:** 4.39.4 

### Link to debug log
https://debuglogs.org/eadf744f7aa91287c8bc4a64cd3cc19fcc5964769e17398358cf50db0006b71e

**Comment by alan-signal** [comment]
Does this affect certain contacts? Or all contacts?

Have you ever *not* seen this issue in previous versions, and can guess which version that was or a time that you first noticed the break?

**Comment by greyson-signal** [comment]
Looks like we're also trying (and failing) to send typing indicators in the same conversation, so it seems we may be incorrectly detecting a user as registered.

**Comment by jmayday** [comment]
> Does this affect certain contacts? Or all contacts?

I tried sending also to one Signal and one non-Signal contact - in both cases message has been sent successfully. I still fail to send message particular message to one particular contact (I was able to send him different message though, like "test").

> Have you ever _not_ seen this issue in previous versions, and can guess which version that was or a time that you first noticed the break?

I've never noticed this issue before.

**Comment by junitas** [comment]
@greyson-signal , I just encountered this issue as well. The only difference is that this happens when attempting to send an MMS to a non-Signal user. Exception is same, but from the MmsSendJob.
 Debug log is as follows:
 https://debuglogs.org/4aed19bf4b0cf322af865cc1fe90afac90e9f84d23126c4e870b038bcb8e4442

**Comment by junitas** [comment]
Forgot to parse out my device info. Sounds like an application bug but just in case :)

```
Device : motorola moto g(6)
Android : 8.0.0
App : Signal 4.40.4
```
