### ISSUE TITLE
Compose field is using autofill "Enter name or number"

### ISSUE THREAD

**Issue by nahuhh** [signalapp/Signal-Android#8817]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- tap the pencil

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- the "enter name or number" field is recognized for androids "autofill" feature  

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- it should use Autocorrect but not autofill

### Device info

**Device:** BlackBerry keyone
**Android version:** 8.1.0
**Signal version:** 4.40.1

**Comment by alan-signal** [comment]
> the "enter name or number" field is recognized for androids "autofill" feature

How does this manifest itself?

Screenshots would help.

**Comment by nahuhh** [comment]
![retr](https://user-images.githubusercontent.com/50635951/58265031-e84f2c00-7d4c-11e9-89d7-54e832d8fc18.jpg)

**Comment by alan-signal** [comment]
Does it also happen if you press the search on the main screen?

![image](https://user-images.githubusercontent.com/48254818/58266870-e4290b80-7d58-11e9-82ae-79cb7ee47114.png)

Or anywhere else?

**Comment by nahuhh** [comment]
No. Looks like the "enter name..." is the only place.
(Even the registration lock reminder popup doesn't use it)
