### ISSUE TITLE
Missing documentation on android proxy/client link preview user-agent

### ISSUE THREAD

**Issue by cmswalker** [signalapp/Signal-Android#8818]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Missing documentation on android proxy/client user-agent

what is the user-agent that is sent for the signal crawler for link previews? I was able to find the ios and desktop one but cannot find the android one anywhere, would love to add this to existing documentation when found https://github.com/signalapp/Signal-iOS/blob/e0bba32505896cdfd41c1a5c1a16bb22e4222f32/SignalServiceKit/src/Network/ContentProxy.swift#L56

Also asked here but not sure it is getting visibility anymore as it is closed https://github.com/signalapp/Signal-Android/issues/8796

**Comment by greyson-signal** [comment]
We don't set one, so it goes to the oktthp default: okhttp/3.12.1

**Comment by cmswalker** [comment]
Would you be opposed to it? It's nice to be able to differentiate signal crawls from others

**Comment by cmswalker** [comment]
it would also bring the android one inline with ios + desktop
