### ISSUE TITLE
Verification: "Call me instead" and "Wrong number" buttons obscured by keypad for larger fonts

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8822]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After entering a phone number for registration, the "Call me instead" and "Wrong number" buttons can be hidden by the irremovable keypad when using a larger font.

### Steps to reproduce
- Select a large font for the system
- Go to a new installation of Signal and enter a number for verification

**Actual result:** Unable to see "Call me instead" and "Wrong number" buttons. All that is visible is the entry area for the verification code.
**Expected result:** Able to see "Call me instead" and "Wrong number" buttons

#### Using the default Samsung font settings

<div align="center">
<img src="https://user-images.githubusercontent.com/26474149/57996500-5c70a200-7ab7-11e9-8eaf-c5ca9f5f1cfe.PNG" width="50%"/>
</div>

The buttons are partially obscured

<div align="center">
<img src="https://user-images.githubusercontent.com/26474149/57996540-99d52f80-7ab7-11e9-9a89-dfbb3d5518a4.PNG" width="40%"/>
</div>

---

#### Incrementing the Samsung font setting

<div align="center">
<img src="https://user-images.githubusercontent.com/26474149/57996666-4a433380-7ab8-11e9-95cb-a6e8ce029620.PNG" width="50%"/>
</div>

The buttons are not visible

<div align="center">
<img src="https://user-images.githubusercontent.com/26474149/57996691-67780200-7ab8-11e9-8114-78e84e1d29b1.PNG" width="50%"/>
</div>

### Device info

**Device:** Samsung Galaxy S6
**Android version:** 7.0
**Signal version:** 4.39.4

Using stock ROM and stock Samsung Keyboard, with all keyboard settings reset to default

### Link to debug log
Does not seem relevant

**Comment by greyson-signal** [comment]
This should be resolved.
