### ISSUE TITLE
Signal Notifications Get Eaten By Inactive Clients

### ISSUE THREAD

**Issue by IcyMidnight** [signalapp/Signal-Android#8824]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using Desktop Signal (Windows & OS X), if I leave a conversation open then I don't receive notifications on my phone.

I noticed this started happening a few months back. At first it was mysterious that my messages were somehow showing up unread, but I eventually started noticing that I'd go back to one of my computers with the desktop app on it and the conversation that was being silenced was open in the client. I have Signal Desktop installed on 3 machines, and I habitually leave the app open on all of them while they're on (i.e. Signal starts with the OS and never gets exited, even through the OS being put to sleep, etc) so that I don't have to wait forever for the message history to sync when I need to send a message. This failure mode is especially sinister because you will receive notifications for other conversations while one of them is being silenced. The other night I was waiting for a friend to respond to me about our impending plans while I chatted in another conversation, only to discover that while I had the Signal app open in my hand he'd messaged me a half hour earlier but the notifications hadn't shown up and his conversation was marked read.

It is good that Signal doesn't seem to spam every device if I'm active on one, but it should at some point notice when I go away, and then resurface any messages that showed up before it noticed. E.g. if I'm active at time X-1, got inactive at time X, Signal times out at X+timeout, any messages that arrived between X and X+timeout should be resurfaced on all clients.

I haven't grabbed logs because when this crops up, it's usually highly inconvenient, but it's possible that OS sleep is involved since the devices that I'm sure have cause the problems are both laptops that spend some portion of their life asleep.

### Steps to reproduce
- Initiate or respond to a conversation on a desktop version of Signal
- Walk away from the computer
- Have your contact send you a follow up message

**Actual result:** 1) My phone does not produce a notification letting me know I've received a follow up message. 2) When scrolling through my list of conversations, the conversation will be marked read.
**Expected result:** 1) If I have not read a message I should get a phone notification. 2) If I have not read a message, the conversation shouldn't be marked read.

### Device info

**Device:** Pixel 3 XL
**Android version:** 4.39.4
**Desktop version:** 1.24.1

**Comment by VersloB** [comment]
It seems that Signal has issues with devices 'sleeping' while the app remains 'active' - and the issue presents differently based on device and OS.  
See also: https://github.com/signalapp/Signal-Android/issues/8819
Those who can resolve the issue(s), do not appear to see this as a problem worthy of attention. 
'Support' is even less helpful.
So the work around appears to be 'keep on checkin!'
ymmv

**Comment by ramsonline** [comment]
I so have exactly the same Problem with my Pixel 1. It is a bad instant Messenger if you do not get noticed on new messages.

**Comment by ozgurakyazi** [comment]
#8604 is related, I believe.

**Comment by jonathanturcotte** [comment]
Happened to me as well, and it was tricky to narrow it down to the desktop clients. Unlinking them immediately solved the issue for me. I think there needs to be more logic around when to dismiss notifications on other devices

**Comment by greyson-signal** [comment]
The problem here is with the desktop client. If we receive a read receipt sync from desktop, we honor it. If it's sending read receipts when it shouldn't, we need to fix that on desktop. Feel free to open a ticket at https://github.com/signalapp/Signal-Desktop

Thanks!

**Comment by IcyMidnight** [comment]
@greyson-signal I'm pretty sure that I've seen this happen even when the machine that holds the Signal Desktop instance is sleeping. Is there a concept of "Hi, I'm Desktop client X and I have conversation Y open so you can assume all messages to conversation Y are automatically read"?

**Comment by greyson-signal** [comment]
No, there's only the concept of a linked device telling us "message X was read", at which point we will dismiss the notification. If your desktop OS is asleep and still sending read receipts, that's a bug. Desktop has to support various OS flavors, each of which has their own corner cases for the concept of "window focus", so if you open a ticket there, be sure to let them know your system details and stuff.
