### ISSUE TITLE
SMS on Dual SIM: Cannot see or select SIM, incoming SMS not received.

### ISSUE THREAD

**Issue by gjankowiak** [signalapp/Signal-Android#8826]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When Signal is seleced as the default SMS app, I cannot select the SIM used for sending SMS by a long press on the Send button. If I send a SMS and display the SMS details, the Via field is "SMS" so I don't know which SIM was used. This is regardless of the "Preferred SIM for SMS messages" setting.

It also seems that some incoming messages on the first SIM card (at least) are eaten away, i.e. never received, no notification is show, it doesn't show in Signal at all.

This used to work perfectly a few weeks ago.

Google's Messages app as the default SMS app doesn't have this problem: I can select the sending SIM and messages are received as expected.

### Steps to reproduce
- set Signal as the default app for SMS on a dual-SIM equipped phone
- try to select the originating SIM card before sending a message
- try to send a SMS to the number corresponding to the first SIM card.

**Actual result:** no SIM selector is show, no information is available on which SIM was used for sending, incoming SMS message is not received.
**Expected result:** SIM selector shown and working, incoming SMS messages are received.

### Screenshots
![Screenshot_2019-05-23-12-13-47](https://user-images.githubusercontent.com/6949106/58245277-b17d1400-7d54-11e9-8ff3-ccb44be247a5.png)

### Device info
**Device:** Oukitel K4000 Pro
**Android version:** 5.1
**Signal version:** 4.40.4

### Link to debug log
https://debuglogs.org/bc3fa19415028ca3f319e919bcc57fbeb77732ba3f3f2dd3af543194167eaa40

**Comment by alan-signal** [comment]
There are a lot of:
```
2019-05-16 18:58:45.126 CEST W SubscriptionManagerComp: Missing SubscriptionManager.
2
```
In the log.

**Comment by alan-signal** [comment]
Was there a version or time, that this worked for you?

**Comment by alan-signal** [comment]
We used to use:
```
SubscriptionManager.from(context);
```
But that is deprecated, so now we use:
```
ContextCompat.getSystemService(context, SubscriptionManager.class);
```
So I think I can switch to:
```
(SubscriptionManager) context.getSystemService(Context.TELEPHONY_SUBSCRIPTION_SERVICE);
```

Thanks for the report.

**Comment by alan-signal** [comment]
I've found the bug in android compat source:
```
  private static final class LegacyServiceMapHolder {
    static final HashMap<Class<?>, String> SERVICES = new HashMap();

    private LegacyServiceMapHolder() {
    }

    static {
      if (VERSION.SDK_INT > 22) {
        SERVICES.put(SubscriptionManager.class, "telephony_subscription_service");
        SERVICES.put(UsageStatsManager.class, "usagestats");
      }
```

So, it only manages to map `SubscriptionManager` for API > 22, but you have API 22.

**Comment by gjankowiak** [comment]
Thanks for the quick response. I'm not familiar with the code, so do you think that it is fixable?

**Comment by alan-signal** [comment]
Oh yes, fix is written. I can't say right now when that will be deployed. I will find out later.

**Comment by gjankowiak** [comment]
Great, I'm looking forward to try it.

**Comment by alan-signal** [comment]
Will be in 4.41

**Comment by OrpheeGT** [comment]
Hello,
I'm currently having the same issue on my Samsung S20 with Android 10.
I only have the operator/carrier name shown, no SIM card name, no phone number.
I named my cards Pro and Perso.
Currently I have 2 different carrier so I still know what is the good one.
But I plan to switch my personnal carrier to the same as pro, so I won't be able to know what phone is...
My phone language is in french for information...
