### ISSUE TITLE
Only part of ringtone

### ISSUE THREAD

**Issue by SigTestingTeam** [signalapp/Signal-Android#8828]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a message with attachment (picture, voice) arrives, i get only a small part of the ringtone.

### Steps to reproduce
Send me a message with attachment and hear the ringtone.

### Device info

**Device:** motorola Nexus 6
**Android version:** 7.1.1
**Signal version:** 4.40.4 

### Link to debug log
https://debuglogs.org/14cc133299e37419a4fceea6f6ed6a0f7d2a4628368ddc159bd1d7577540b77a

**Comment by Dyras** [comment]
Pretty sure this is an Android issue. It happens for me on my Pixel XL on both Messenger and Signal.

**Comment by greyson-signal** [comment]
All we can do is tell the system what sound to play. It's up to the system to play that. Perhaps the sounds is too long, and the system is deciding to only play the beginning? Couldn't say for sure.
