### ISSUE TITLE
Can't dele my account

### ISSUE THREAD

**Issue by rafaelmr2** [signalapp/Signal-Android#8833]
Hi,

The unregister website (https://signal.org/signal/unregister/) is not working. Since yesterday I'm trying to unregister but I put the SMS code and nothing happens.

Thanks.

**Comment by deadonek** [comment]
Hi, rafaelmr2 ! 
Have tried to unregister my acc right now. Successfully. Country Ukraine.

**Comment by rafaelmr2** [comment]
I'm in Brazil. I tried in many browsers and different networks. When I click "Unregister" nothing happens.

**Comment by deadonek** [comment]
> I'm in Brazil. I tried in many browsers and different networks. When I click "Unregister" nothing happens.

Have you tried to unregister via call? 
Btw, after the success unregister the blue header(with some text) should appear in your application.

**Comment by rafaelmr2** [comment]
I tried now. It's speaks the verification code. The problem is not receive the verfication code. When I put it on input and click "Unregister" nothing happens.

**Comment by petcap** [comment]
@rafaelmr2 Do you have registration lock enabled on your number? In that case, I've also noticed that you cannot unregister your number. Install the client and either unregister directly in it or remove the registration lock.

**Comment by rafaelmr2** [comment]
I installed the client again. The option lock was enabled. Now I'm using again the Signal, if I have this problem in future I come back. Thank you.
