### ISSUE TITLE
swarm of signal4android knockoffs (w/ GoogleAds) now in playStore

### ISSUE THREAD

**Issue by five-c-d** [signalapp/Signal-Android#8834]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a software firm near WashingtonDC which has created a way for programmers with minimal experience to generate a cloned Signal-Android APK, insert advertising trackers, and upload them to playStore. 

*  first 6 knockoff APKs == https://community.signalusers.org/t/signal-cloned-apps-in-playstore/3398/23
*  later, 9 more knockoff APKs == https://community.signalusers.org/t/signal-cloned-apps-in-playstore/3398/40
*  these are *NOT* the only ones, and many more are coming ("appsGeyser") 

### Steps to reproduce
- everyday enduser opens playStore 
- looks for Signal(TM) 
- might get tricked into installing one of the knockoffs instead 

**Actual result:** Endusers sad, signal.org/legal undefended 
**Expected result:** Endusers happy, signal.org/legal defended 

### Screenshots

N/A

### Device info

**Device:** all supported handsets 
**Android version:** all supported OS versions 
**Signal version:** first clone appeared ~19th March 2019 circa 4.34.2 

### Link to debug log

debuglogs N/A, forum thread is here == https://community.signalusers.org/t/signal-cloned-apps-in-playstore/3398/40 there are clear trademark and copyright violations (as well as presumably-unauthorized use of production signal-server nodes I very strongly suspect).  With this many "independent" APK uploads however, methinks the key is to stop the flood at the source, the APK-spawning firm

**Comment by greyson-signal** [comment]
Hey there! Thanks for bringing this up. I'll forward the information to the correct person. In the future, for forum stuff, you can just tag or DM me :)
