### ISSUE TITLE
Key Not Yet Valid Exception After Restore

### ISSUE THREAD

**Issue by agnostic-apollo** [signalapp/Signal-Android#8840]
### Bug description  
So I was trying to setup another account with my other sim for desktop pc usage and backed up the Signal app (v4.39.4) with Titanium Backup app, and then cleared the app data. I wasn't aware that keystore was being used since last year, i had long before restored a titanium backup of the signal app successfully, so the keystore thing didn't come to my mind. Clearing the app data also deleted the key from /data/misc/keystore/user_0 and once i had finished setting up the new account, and restored my previous backup, signal app started crashing with the expected key not found errors at startup. Thankfully (so I thought) I had a TWRP backup from Mar 8, 2019 that had the keystore key that was originally created on Feb 22, 2018. I extracted that from my TWRP backup and placed it in my keystore directory after renaming it with the signal app UID, and setting it to keystore ownership and the current signal app UID. I had hoped the key would be accepted and i could access my messages again but signal app still crashed on startup with "Key not yet valid" exceptions. I even extarcted the signal app (v.4.35.3) and its data from my Mar 8, 2019 TWRP backup and tried opening that but still the same error, Then I restored the entire TWRP backup as well, but still the same error. Anyways the key not yet valid error doesn't make sense. People on the internet who received the same error tried changing their timezones and that fixed it for them, and I did that too, moved it ahead, moved it back, changed the date to the future even back to Mar 8, 2019 and Feb 23, 2018 but nothing works.  

Note that after complete TWRP restore i had to delete my lockscreen pattern, key and fingerprint files from /data/system to unlock my screen... But they have been changed probably multiple times after Feb 23, 2018, and I have also restored full TWRP backups successfully after that date anyways with the signal app working, atleast once [here](https://forum.xda-developers.com/showpost.php?p=76772393&postcount=73). I also tried after deleting the pref_database_encrypted_secret and pref_log_encrypted_secret to no avail but that stage probably comes later.  

So I got to investigating and going through the signal app source code and tracing the issue I found it even weirder that in the [KeyStoreHelper.java](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/crypto/KeyStoreHelper.java) file, which most likely creates the initial keystore key (probably created mine in Feb, 2018), the [setKeyValidityStart function](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder.html#setKeyValidityStart(java.util.Date)) is never called for the KeyGenParameterSpec.Builder, and by default, the key is valid at any instance in time. So why would the exception be thrown? And if I am not mistaken, I checked the commit history of KeyStoreHelper.java and key validity was never set in earlier versions too.  

So do you have any thoughts about this or have I lost years of messages thanks to encryption which I wanted in the first place ;)

Thanks

### Device info  
**Device:** LG G5 RS988
**Android version:** 7.0
**Signal version:** 4.39.4

### Link to debug log  
```5626  5626 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5626
05-29 03:24:44.372  5626  5626 E AndroidRuntime: java.lang.AssertionError: android.security.keystore.KeyNotYetValidException: Key not yet valid
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:73)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:177)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:107)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: Caused by: android.security.keystore.KeyNotYetValidException: Key not yet valid
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:700)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:764)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:148)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1329)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1267)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:69)
05-29 03:24:44.372  5626  5626 E AndroidRuntime: 	... 19 more
```

**Comment by greyson-signal** [comment]
To start, I'm sorry about your message history. As someone who has a long message history myself, I can imagine that's really tough. However, Signal just doesn't support Titanium Backup, and anything that happens afterwards is pretty undefined.

A community member did make a forum post that describes a process of copying over the keystore -- sounds like you might have done something similar, but maybe there's some knowledge to be gained there. 

https://community.signalusers.org/t/howto-manual-backup-restore-if-full-backup-does-not-work/2462

Best of luck!

**Comment by agnostic-apollo** [comment]
Thanks for the reply.
Yeah, I have already seen that post and have done the same thing technically.
And I already know about the non-support for Titanium Backup and anyways technically that's not your domain so I understand, but since this was an exception related to Signal and I had technically not lost my encryption key, I just thought I should ask the signal devs who understand encryption way better than me. I guess I'll just have to look into this myself when I get the time.
