### ISSUE TITLE
Cannot send/receive MMS without turning on Mobile Data

### ISSUE THREAD

**Issue by archeryguru2000** [signalapp/Signal-Android#8844]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot send or receive MMS (messages with images, for example) without manually turning on Mobile Data.

### Steps to reproduce
- Begin new message
- Add an image
- Hit Send

**Actual result:**  If my Mobile Data is turned off and I'm not connected to Wifi, the message tries and tries to send but only drains the battery.  If, on the other hand, I turn on Mobile Data, _then_ the message is successfully sent.  A similar issue with receiving MMS messages.  I see that I have a message to open/download, but I cannot view anything until I turn on my Mobile Data.
**Expected result:** I have come to expect that the Signal App would simply use my data (as other apps do, Messages, etc.) to send/receive the MMS automatically; without me needing to connect all my other apps to the net.

### Device info
**Device:** Samsung Galaxy J3 Luna Pro
**Android version:** 6.0.1
**Signal version:** 4.40.4

**Comment by greyson-signal** [comment]
To start, sending MMS messages requires a data connection. No way around that. You can send SMS messages with just a cellular connection and no data connection, but MMS requires a data connection. Signal cannot turn your data on for you.

> the message tries and tries to send but only drains the battery

What indication do you have of this? If you see the spinning "pending" indicator on a message, that doesn't necessarily mean that we're *actively* trying, just that the message hasn't been sent yet. Looking at the codebase, we don't attempt to send MMS messages unless you have a network connection (WiFi or mobile data).

**Comment by greyson-signal** [comment]
I should follow up and say that if you create this situation again (turn off mobile data, no wifi, and send an MMS) and then capture a debug log and post the link here (Settings > Advanced > Submit debug log), then I can verify if we're actually attempting to send the MMS or not.

**Comment by archeryguru2000** [comment]
> I should follow up and say that if you create this situation again (turn off mobile data, no wifi, and send an MMS) and then capture a debug log and post the link here (Settings > Advanced > Submit debug log), then I can verify if we're actually attempting to send the MMS or not.

I will try this.

**Comment by archeryguru2000** [comment]
Thanks for the quick response, by the way.  It is much appreciated.
