### ISSUE TITLE
panic response feature no longer does anything

### ISSUE THREAD

**Issue by eighthave** [signalapp/Signal-Android#8845]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have had several users report to me that the panic response feature in Signal no longer works.  I confirmed this: Signal claims to support accepting a panic trigger, but it does nothing in response.  My guess is that this is because the Signal-specific PIN feature seems to have be removed, and now there is only something that is chained to the lockscreen.

Ideally, Signal would again lock itself, exit and hide as it was doing before.  Other possible lesser responses are:

* just exit and hide from Recents
* set the Signal view state to the front page, away from any active chat logs

Signal also seems well prepared to support some new "destructive" panic button responses like:

* wipe all disappearing messages (perhaps this could be an option when setting the timeframe for disappearing messages)
* entirely wipe itself and exit, if Signal backups are enabled
* wipe all backups

### Steps to reproduce
- install Ripple
- see Signal listed as an option (based on the entry in Signal's AndroidManifest.xml)
- trigger Ripple to send the trigger to Signal
- see that Signal is in the same state

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Signal claims to support a panic trigger, but seems to do absolutely nothing in response.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Before, Signal locked itself, then exited and hid itself from the "Recents".

FYI, the panic support was added in  #5550

**Comment by fishofivory** [comment]
Issue still occurring, unfortunately.

**Comment by eighthave** [comment]
yes this is still relevant.  It could be something as simple as quitting and 
removing itself from the "Recents".

**Comment by srgkoshelev** [comment]
Bump to reopen. This feature is needed and important. The fact that Signal shows as interacting with ripple but not actually reacting is disappointing.

**Comment by wertzuz** [comment]
@eighthave would really like to see this fixed
