### ISSUE TITLE
Asked about profile options in Note to Self

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8847]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Profile options (Block; Add to contacts; Don't add, but make profile visible)  appear if you send a Note to Self message and then delete the message.

### Steps to reproduce
- Make sure the device does not have your own number as a contact
- Go into Note to Self
- Type a message
- Delete the message

**Actual result:** Options for profile appear for Note to Self. There should not be any need to share yourself with yourself or block yourself.
**Expected result:** No profile options appear for Note to Self.

### Screenshots

<img src="https://user-images.githubusercontent.com/26474149/58738276-a8471380-83f4-11e9-9422-ca66e431c430.gif" width=50% />

### Device info
Signal version: 4.40.4

**Comment by Sgn-32** [comment]
Tested in 5.4.12. Should have been solved in some version from 4.40.4 to 5.4.12.
