### ISSUE TITLE
Profile options dialog is not in dark theme when dark theme is enabled

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8848]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When dark theme is on, profile options dialog (Block; Add to contacts; Don't add, but make profile visible) is not in dark theme

### Steps to reproduce
- Turn on dark theme
- Get a message from a user that is not in your contacts to get the profile options to appear

**Actual result:** The profile options dialog is not in dark theme.
**Expected result:** The profile options dialog is in dark theme.

### Screenshots

![Bug-ProfileDarktheme](https://user-images.githubusercontent.com/26474149/58738722-86e72700-83f6-11e9-9a01-bf74a9c65e72.PNG)

### Link to debug log
UI issue

**Comment by Xashyar** [comment]
This issue does not appear in the recent updates:

![image](https://user-images.githubusercontent.com/34171942/81500182-af092680-92e5-11ea-84a4-890d8d77c78c.png)
