### ISSUE TITLE
Trying to use large emoji as image stickers in the image editor doesn't work

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8850]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to use large emoji as image stickers doesn't work.
It seems like it affects Android 7 and up. An Android 6.0.1 device doesn't have this issue.

### Steps to reproduce
- Select an image to send to a contact
- Use the text option in the image editor to insert an emoji and stretch it out large like it is a sticker
- Send the image

**Actual result:** The emoji disappears from the image after it is sent
**Expected result:** The emoji stays on the image exactly as it appeared in the editor

### Screenshots
From Samsung S6, emoji as stickers does not work (above a certain size)

<img src="https://user-images.githubusercontent.com/26474149/58744321-b31f9980-8430-11e9-9aec-5117b7da6dbf.gif" width="45%" />

---

From Samsung S9+, emoji as stickers does not work above a certain size
Smaller emoji does work.
In this GIF, three sizes of an emoji are used

<img src="https://user-images.githubusercontent.com/26474149/58744603-866d8100-8434-11e9-9ded-8ab03713d5d0.gif" width="45%" />

---

From Moto G on Android version 7.1.2 (LineageOS 14.1) (so it doesn't seem to be limited to Samsung devices)

<img src="https://user-images.githubusercontent.com/26474149/58745365-a48cae80-843f-11e9-9f70-0da310549547.gif" width="45%" />

---

From LG K4, Android version 6.0.1 (stock ROM), emoji as stickers do work no matter the size

<img src="https://user-images.githubusercontent.com/26474149/58745344-57104180-843f-11e9-8374-d98469118038.gif" width="45%" />

### Device info
Devices where the bug was reproducible, i.e. emoji as stickers does not work
- Moto G (1st gen.), Android version 7.1.2 (LineageOS 14.1), Signal version 4.40.4
- Samsung Galaxy S6, Android version: 7.0.0, Signal version 4.39.4
- Samsung Galaxy S7 Edge, Android version 8.0.0, Signal version 4.40.4
- Samsung Galaxy S9+, Android version 8.0.0, Signal version 4.40.4

Device where it worked as intended, i.e. emoji as stickers do work
- LG K4, Android version 6.0.1, Signal version 4.40.4

### Link to debug log

For S6

https://debuglogs.org/1125034f4d700752d948197e49c64b86d8c8851c7e710fdbed1c94fe888b5db5

**Comment by alan-signal** [comment]
Thanks for report.

Seems to be a general android rendering bug:

https://stackoverflow.com/questions/50965784/canvas-drawtext-doesnt-render-large-emojis-on-android

https://bugs.chromium.org/p/chromium/issues/detail?id=501071

Weirdly, at some even large scales I have seen the emoji come back.

**Comment by greyson-signal** [comment]
Given the nature of the bug, there probably isn't much we can do about it.
