### ISSUE TITLE
Hardware echo cancellation revisited

### ISSUE THREAD

**Issue by letkan** [signalapp/Signal-Android#8852]
My device (ro.product.model): Xiaomi Mi A2 Lite with custom rom and no gapps.

This is in reference to #7635 which was closed. My video chat partners experience heavy echo while talking to me (aside from various background noises that are almost always present). https://github.com/signalapp/Signal-Android/issues/7635#issuecomment-447520059 dismissed the possibility of adding a setting to disable hardware noise cancellation if necessary which would make sense if there was a way to easily add a device to the hardware AEC blacklist, but there isn't. Please reconsider.

**Comment by alan-signal** [comment]
Please use the forum for feature requests. https://community.signalusers.org/
