### ISSUE TITLE
Retrieving messages dialogue and battery killer

### ISSUE THREAD

**Issue by 91rl** [signalapp/Signal-Android#8854]
### Bug description
Identical closed issue linked below as far as I can tell:

https://github.com/signalapp/Signal-Android/issues/8516

However the retrieving notification dissapears when connected to WIFI. However signal fails to upload the log when on WIFI, says no network connection detected straight away. When using cellular data attempts to upload but fails after a minute... 

### Steps to reproduce
Not sure. Just started up today, two friends recived italicised messages saying 'bad encrypted message' today as well.

### Device info

Galaxy Note 4
Android 7
Latest signal version

**Comment by shnorb** [comment]
Just did a complete reinstall and the issue returns.
