### ISSUE TITLE
Signal doesn't correctly interface with Contacts app

### ISSUE THREAD

**Issue by soulofmischief** [signalapp/Signal-Android#8857]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't let me save contacts to my contacts app.

I don't use the default contacts app, because my new Pixel's contacts app *only* allows saving contacts to Google's cloud, not the phone, which I find to be an extreme breach of privacy for me and others. It's simply not an option.

I disabled the app and installed an open source contacts app (OpenContacts) from F-Droid. However... Signal doesn't recognize it.

### Steps to reproduce
- Download an alternative contacts app.
- Find a conversation in Signal with a number not saved to your contacts.
- Select "Add to contacts"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Nothing happens. No UI, no warning, nothing.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

One or more of the following:

- Signal asks me which default Contacts app I would like to use (if this is possible and the default has not already been selected).

- Signal detects that it can't open the contacts app and presents a list of apps it thinks are compatible (If this is possible).

- Signal allows me to copy the number to my clipboard in the event that it cannot detect or open a contacts app.

### Device info

**Device:** Google Pixel 3a
**Android version:** 9
**Signal version:** 4.40.4

### Link to debug log

[Debug Log](https://debuglogs.org/07ff37ea5b1caf4f6a03c390a9f3c642240223af571f98d46c3dc93ffdca117f)

**Comment by Genis-Sage** [comment]
hey soulofmischief

i don't think that this is a bug of Signal, but rather the feature of Opencontacts (and a design flaw of Android)

the whole thing about access to contacts is always about the system contact database
and Opencontacts has a seperate database, similar as SIgnal does not use the system database for SMS

so even if you save contacts no Opencontacts, no other app will be able to access these contacts (neither read nor write)

so from the above options you gave, only the third one would be possible


if you want a more pleasent solution, there are two things you can do
1) simple deactivate the synchronisation of the contacts to Google in the Google settings. So they will be saved in the local Google address book but they are not synced to Google servers. (I think there is an additional system app called google-contacts sync or similar, which you should deactivate)
2) use an app that creates a local address book like Mylocalaccount (which is sadly rather old). They will also show up in the google contacts app, but also not synced to Google servers, independent of the contact sync settings

If you don't want to use the Google contacts app at all, you should go for an app like Simple Contacts which also uses the normal contact databse

**Comment by soulofmischief** [comment]
hi, thanks for the reply.

Mylocalaccount was not FOSS, but Simple Contacts is. Seems to work with Signal as well. Thanks for the recommendation. Think it's worth mentioning in the wiki?

**Comment by soulofmischief** [comment]
Well I did some more testing... And ran into a bug.

Selecting the icon for a contact which already existed in my gmail account works as expected, pulling up Simple Contacts.

However, selecting a contact created within Simple Contacts doesn't work. The name does appear correctly in Signal, but when selecting the contact's icon Simple Contacts flashes and closes within a few hundred milliseconds.

Unsure if this is a bug in Signal or Simple Contacts.

**Comment by alan-signal** [comment]
Please contact Simple Contacts. It appears to be a limitation of their app if this is it https://play.google.com/store/apps/details?id=com.simplemobiletools.contacts.pro.

![image](https://user-images.githubusercontent.com/48254818/59380136-65573b00-8d26-11e9-9c22-f29b9501ede6.png)
