### ISSUE TITLE
Typing indicators lead to incorrect quoted message link

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8858]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If the typing indicator is shown in a conversation and a quoted message is tapped, the view jumps to the message below the quoted one and also highlights the incorrect one.

This sounds like an off-by-one (incorrect counting during to typing animation) to me.
Maybe related: https://github.com/signalapp/Signal-Android/issues/8851

### Steps to reproduce
- Have typing indicators enabled for both you and your contact.
- Have a quoted message in the conversation.
- Contact types a message.
- During the animation, select the quoted message.

**Actual result:** The message below the quoted message is highlighted. If the typing animation is gone, the correct one is highlighted after tapping.
**Expected result:** Correct quoted message is highlighted.

The message that has been quoted is 1559756822612. The message that gets highlighted during  the typing animation is 1559756839375.

### Screenshots
Didn't manage to capture some, but I guess this issue should be easily reproducible.

### Device info
**Device:** Motorola Moto G5
**Android version:** 8.1
**Signal version:** 4.41.1

### Link to debug log
https://debuglogs.org/25d9c989555f4c6111d0ea8aed8ddd8cb67f817dc9aa9dcaca5a6b3947412d5e
Unfortunately, this bug happened to me yesterday and I only managed to capture the log right now. So maybe the issue is not contained in the log. In that case I will try to reproduce it and post a new one. Just let me know!

**Comment by inthewaves** [comment]
From S6, Android version 7.0, Signal version 4.41.6

<img src="https://user-images.githubusercontent.com/26474149/59394992-5cd82200-8d71-11e9-915b-0b278b25fb1a.gif" width="50%"/>
