### ISSUE TITLE
Problem with Profile Picture

### ISSUE THREAD

**Issue by sgerdi** [signalapp/Signal-Android#8859]
### Bug description
The Profile Picture can not be changed anymore

### Steps to reproduce
settings
set up your profile
profile photo

After I have selected a Photo and confirm the Change, the Loading Process stops and the Message signal stops apears...

### Device info

**Device:** Samsung Galaxy s4 GT-I9505
**Android version:** 5.0.1
**Signal version:** 4.40.4

**Comment by alan-signal** [comment]
Will need the debug log please.

**Comment by sgerdi** [comment]
https://debuglogs.org/9e8563567ace9648669ceb33da5ca30a08587b26d1388f9320a840e453dc9ef2

**Comment by sgerdi** [comment]
No Solution?

**Comment by forester9685** [comment]
I hava the same problem.

https://debuglogs.org/29d7e84b7d0bdcbc2380e09ace6cb43c5ae33d4b2096e1c6fbd3bf47c87ad7ea

**Comment by sivaraam** [comment]
This happens for me too on Samsung Galaxy J1 ace running Android 5.1.1.

Debug log: https://debuglogs.org/61a433358b846d68b2ca5e2e859bc85f090b9327f45cb753f32074a747a63af0

**Comment by sivaraam** [comment]
What makes this crash more interesting is the fact that the app crashes during registration after I try to set the profile name. That is the crash happens to a user during the registration phase itself. So, it might worth finding the root cause and fixing this.

**Comment by alan-signal** [comment]
@sgerdi Logs are not as expected:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Signal/1.25.1 Chrome/69.0.3497.128 Electron/4.2.2 Safari/537.36 node/10.11.0 env/production

I meant the debug log from the Signal app, go to Settings-> Advanced -> Submit debug log the next time you see it. And supply us the URL. The other logs are informative but I want to make sure you have the same issue and I'm interested in your device info which is all in the log.

**Comment by forester9685** [comment]
Hi all,

The issue still persist on my phone. I wanted to share debug logs once again if the previous one didn't work for to identify the issue.

https://debuglogs.org/b82ac573d4c458e0cf8e34cf6af02550f07d8a733dd1745136b9bba18b1766c3

**Comment by zrahmani** [comment]
I have the same problem. Android Version 5.0 

https://debuglogs.org/6efb5ebf243ef3d1b31380da82cb94f4c649cdba20e798392855b23fd30d33b8

**Comment by alan-signal** [comment]
Thanks all.

We have a solution now, we just have to wait for 4.44 to be released.

This is same issue as #8378

**Comment by sgerdi** [comment]
@alan-signal Now it works, thanks!

**Comment by forester9685** [comment]
@alan-signal The issue was solved after last update. Thank you so much for your support.
