### ISSUE TITLE
select the SIM card

### ISSUE THREAD

**Issue by asd2012** [signalapp/Signal-Android#8860]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

Missing the ability to select the desired SIM card to send ordinary unencrypted SMS.
Android 5.1

**Comment by alan-signal** [comment]
I need the version of Signal you are running.

It would also be helpful to know what the last version you remember this working for you was. Or a time when it worked.

**Comment by asd2012** [comment]
Thanks for participating!
Version 4.35.3 worked exactly, only it is outdated. Before this version, too, all versions worked.
Now it costs 4.40.4.

**Comment by alan-signal** [comment]
Sounds the same as #8826 
So please update to 4.41 and see if that is resolved for you.

**Comment by asd2012** [comment]
Ok, we are waiting for the release of version 4.41.

**Comment by asd2012** [comment]
and yes you are absolutely right # 8826

**Comment by asd2012** [comment]
Thank you, everything is fine!
