### ISSUE TITLE
Improve the "Reply to message" action

### ISSUE THREAD

**Issue by klemy** [signalapp/Signal-Android#8861]
Hello,

For now, the action "Reply to message" can be actionable by clicking on a message then push the button in the top bar.

This function is often used in group messages but this is really, really annoying with this UI.

Could it be possible to upgrade this behavior? We could imagine UI with a swipe a action, like WhatsApp, Telegram or Facebook Messenger.

Thank you by advance and keep the good work!

**Comment by alan-signal** [comment]
Please use the community forum for feature requests.

In this case, you might like to show support for this post: https://community.signalusers.org/t/swipe-to-quote-and-reply/3654

**Comment by Meteor0id** [comment]
Or https://github.com/signalapp/Signal-Android/pull/7727 to reply by selecting and starting to type.
