### ISSUE TITLE
Voice messages not auto downloading when they should

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8863]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I notice my voice messages on Signal Android show a download button instead of a play button. Odd, cause I am on WiFi, my data is off, and in preferences it clearly says that when on WiFi I want to download all 4 types of media (including audio).

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 9.0
**Signal version:** 4.41.5

### Link to debug log
https://debuglogs.org/bb45cabadaf0de8ea790a28da6b7df6df3d6f38c05e2372502295d2e4ba365d0

**Comment by nutts0** [comment]
Same here

https://debuglogs.org/0fffdc5a002cc78fce04e8ce49307bf4cd0b378327b0e10dfa120086954becba

**Comment by greyson-signal** [comment]
Are you receiving a voice note from someone who isn't in your contacts? For
security reasons, we don't auto-download media from non-contacts.

**Comment by Meteor0id** [comment]
That does indeed appear to be the case for me.

This security reason should definetly be explained on the support center, and it would be nice if there was also a hint about this within the app. It looks like a bug to me and Nuttso and probably will seem like a bug to others in the future if no hint is added.

Can you please explain this security reason?

**Comment by nutts0** [comment]
Same for me. I also think this should be explained.
