### ISSUE TITLE
Delay in connection to Signal Server when VPN connected and then disconnected

### ISSUE THREAD

**Issue by Phase121** [signalapp/Signal-Android#8865]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi
When user use VPN service like ( Speedify or etc). Signal can't connect to server and still waiting for send and after several minutes sometimes approximately 20 min connection to signal server established again. it's really wiered i saw this issue in another device and unfortunately only solution that i found is force stop signal and open it again.

### Steps to reproduce
1- Download and install VPN ( Speedify is a good choice)
2- At first open signal and send message to your friend.
3- Connect Speedify and wait for vpn connection to establish.
4- Send another message to your friend or wait for new message from them
5- Disconnect Speedify
6- Send message with signal (Ooops, no message send and received and your new sent messages be in Sending... mode)

**Actual result:** Messages are in queue for sending and can't connect
**Expected result:** Send and Received worked....

### Device info

**Device:** Samsung Galaxy Note 8.0 (N5100)
**Android version:** 5
**Signal version:** 4.39.4

### Link to debug log

https://debuglogs.org/cf795287b33a4e005a08b3340e8fc5a3bd95d346df60901e8998fd56bd8877e2

**Comment by alan-signal** [comment]
Please provide a debug log.

**Comment by Payam121** [comment]
> 
> 
> Please provide a debug log.

Done

**Comment by Payam121** [comment]
Please add important tag to this issue. because of heavy censorship in Iran many users must use VPN and cause of this issue, message delivering happens even at 24 hour.
This is very important that messaging system worked correctly in Signal.

**Comment by JJ4U** [comment]
It's really wired, signal team aware this problem from 27 days ago and No Action!!!!, but we should encountered to this problem every min, every hour, every day.
Please fix this issue, it's really really bad thing.
I'm form Iran, we need signal.
Thanks

**Comment by alan-signal** [comment]
@JJ4U which VPN provider do you use?

**Comment by alan-signal** [comment]
We have tested with two VPN providers, ExpressVPN + NordVPN and both work fine. I would suggest you also reach out to Speedify support (or any other provider that doesn't work). The issue appears to be provider specific at this time and they are in a much better position to diagnose.
