### ISSUE TITLE
Signal built-in camera not working

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8866]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when you try to take a photo with the Signal built in camera it doesn't work, you press the button to take the picture and it isn't taken.

### Steps to reproduce
- Use Signal built-in camera to take a photo.
- Press the camera button.
- See that the picture isn't taken.

**Actual result:** Signal doens't take photo when using the built-in camera.
**Expected result:** Signal take photo with the built-in camera.

### Screenshots

Not needed.

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.41.5

### Link to debug log

https://debuglogs.org/32140592f24561bb6d47c4c8121aa946a9ba7ff80ae8c943ea44f0b30b280884

**Comment by greyson-signal** [comment]
There's been a lot of camera changes since this. Probably works now.
