### ISSUE TITLE
Oneplus 7Pro camera activates on call start

### ISSUE THREAD

**Issue by BuckAMayzing** [signalapp/Signal-Android#8867]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Oneplus 7 pro camera pops up on receiving a new call

### Steps to reproduce
- Receive call from another party
- Answer phone call

**Actual result:** Front camera pops up briefly and then closes.
**Expected result:** The camera would not pop up unless I activate video.

### Screenshots
N/A in this instance.

### Device info

**Device:** OnePlus 7Pro
**Android version:** Oxygen OS 9.5.6.GM21AA
**Signal version:** 4.40.4

### Link to debug log
https://debuglogs.org/a283a013d8968c254f6a8ee5cdc9dfbaa2a4e365d8126bd5ea9dbfa34db36c19

### Notes:

This happens only briefly. Is the default state for the camera "on" and it sets to "off" when the phone call starts?

**Comment by maxwisecracks** [comment]
Same with Zenfone 6 and its pop up camera.

**Comment by BuckAMayzing** [comment]
Thanks, @greyson-signal! I thought it might be something along those lines.

**Comment by alan-signal** [comment]
![](https://media1.tenor.com/images/136173405a8066c2f1ac203f208125e8/tenor.gif?itemid=5280291)

**Comment by BuckAMayzing** [comment]
Haha! You're right, @alan-signal. How could I forget the author? Seriously though, thanks for the investigation.

**Comment by alan-signal** [comment]
hehe, you're welcome!
