### ISSUE TITLE
Signal Android unreliable in UAE

### ISSUE THREAD

**Issue by 3WfMeCuUqzgXBh** [signalapp/Signal-Android#8868]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android users in UAE are experiencing issues with Signal. Sending/Receiving is intermittent

### Steps to reproduce
- send messages back and forth, some succeed an some will take hours / days to be delivered.

### Device info

**Device:** Various devices
**Android version:** Various versions
**Signal version:** 4.41.5

### Link to debug log
Issue appears to be an incorrect fronting host in 'SignalServiceNetworkAccess.java'

'www.google.com.ae' appears in multiple lines of this code but this domain is invalid, google.ae is the correct domain for google in UAE. The Signal iOS code has implemented this correctly which I assume is why there don't see to be issues with iOS users.

Debug logs show errors 'unable to resolve" which is expected as the domain does not exist. I will post debug logs as soon as I can get my hands on them.

**Comment by greyson-signal** [comment]
Fix rolling out now. Thanks!

**Comment by subrayamallya** [comment]
Is this issue still there? One of our group members from Dubai still has this issue? he is getting messages delayed and coming to him a day later sometimes
