### ISSUE TITLE
Add Jumbomoji support for Unicode 11 (and 12)

### ISSUE THREAD

**Issue by SamLeatherdale** [signalapp/Signal-Android#8870]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the latest Unicode 11 emojis, such as 🥰 `U+1F970 (Smiling Face With Smiling Eyes and Three Hearts)` or 🥶 `U+1F976 (Cold Face)`, they are not displayed as Jumbomoji.

### Steps to reproduce
- Compose message consisting of a few Unicode 11 characters
- Send message

**Actual result:** 
- Emoji appears in small form

**Expected result:** 
- Emoji should be rendered as Jumbomoji

### Screenshots
![Signal bug (2)](https://user-images.githubusercontent.com/2122053/59310896-2d7ed200-8ceb-11e9-8e3c-dda9a9c8e864.png)

### Device info
**Device:** Xiaomi Mi A1
**Android version:** Stock Android 9.0
**Signal version:** 4.41.6

**Comment by johanw666** [comment]
On my device (Sony Z3 Compact Android 6.0.1) they are not displayed at all. An iPhone user sent them to me and all I saw was little squares.

**Comment by SamLeatherdale** [comment]
That's most likely because your operating system doesn't support those characters, which seems likely as Android 6 is older than Unicode 11. Still, if Signal added support for them, you might be able to see them, I think WhatsApp shows new emoji to older devices.

**Comment by johanw666** [comment]
So I think both issues (no jumbo and not showing on older Android) are caused by Signal not supporting them and falling back to the native OS support.

**Comment by SamLeatherdale** [comment]
@johanw666 I agree, unfortunately looks like there's no way for me to update the issue title to include that, but resolving one issue should resolve the other.

**Comment by SamLeatherdale** [comment]
I'm currently working on a fix for this issue myself, will submit a pull request as soon as I'm finished.

**Comment by SamLeatherdale** [comment]
This pull request fixes this issue; https://github.com/signalapp/Signal-Android/pull/8899
