### ISSUE TITLE
Incoming call screen is distorted

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#8871]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When there is an incoming call, sometimes the receiving screen is distorted. Like the green pull-up-phone-button is not moving, not visible, or the lower 20% of the screen is pure white.

### Steps to reproduce
- happens seemingly random, but on multiple types of Android 8+ phones.

**Actual result:** sometimes it's even impossible to answer the call because the green button is not visible.
**Expected result:** incoming call screen works as intended.

### Device info
**Device:** Sony XPERIA
**Android version:** 8.0.0
**Signal version:** 4.39.4

### Link to debug log

Made after the call ended:

https://debuglogs.org/03dcc2a7c322f7d4ddd67365a58090f4db5037e80ebcf071475bfa29c97620ca

**Comment by PeekFreansCDN** [comment]
Couldn't find the default avatar image for incoming calls

**Comment by Nesos-ita** [comment]
Same here, but happens always: the label "swipe up to answer" is moving up and down kind of "teleport" in fact in the screen you can see two labels, the answer button (green) usually is half covered but i can answer but this time it was invisible.
![photo_2019-07-12_20-29-39](https://user-images.githubusercontent.com/20688006/61150548-fb2be480-a4e3-11e9-833f-264e7bf1b529.jpg)

**Comment by petcap** [comment]
I'm also having this problem, and so does 4 of my friends who use Signal. We all use different devices (Nexus 5x, Moto G7 Power, Galaxy S9, Galaxy A5 2016, Oneplus 6T) with Android versions ranging from 8.0 to 9.0. I've done some testing and this problem generally shows up by simply calling someone in a quick succession 8-10 times.

It is still possible to answer the call successfully via the notification when this happens.

Here's a debug log that was produced by calling myself from another phone multiple times until the button didn't show up. Only the last call had the button missing.
https://debuglogs.org/9c9f21756ce3e2faf1f60f325b8caf3ef5c102d8b77c62cded162d8fb3ed1177

![signal-attachment-2019-08-20-140314](https://user-images.githubusercontent.com/8736529/63346004-57d8b580-c354-11e9-87d6-2fa64f088ea0.jpeg)

**Comment by Sgn-32** [comment]
Should be solved with the new calling UI from 4.60.
