### ISSUE TITLE
Signal drops PNG transparency for profile picture

### ISSUE THREAD

**Issue by yaomtc** [signalapp/Signal-Android#8875]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Uploading a PNG with a transparent background as a profile picture results in an image with a black background.

### Steps to reproduce
- Get a PNG that has a transparent background.
- Tap your icon to get to Settings.
- Tap your icon again.
- Tap your icon a third time, and choose the aforementioned PNG file.

**Actual result:** A black background is added to the PNG file.
**Expected result:** The PNG file is displayed with a transparent background as intended.

### Screenshots

The original file: 

![a.png](https://user-images.githubusercontent.com/5534045/59545162-a303c180-8ee8-11e9-9511-81fbda0df5c9.png)

The file on my desktop before sending it to my phone:

![a.png on desktop](https://user-images.githubusercontent.com/5534045/59545217-8c119f00-8ee9-11e9-9567-5c611cf10c19.png)

The file being cropped against black, for some reason:

![cropping](https://user-images.githubusercontent.com/5534045/59545348-02fb6780-8eeb-11e9-83f0-e2ab1af2951c.jpg)

The resulting image:

![result](https://user-images.githubusercontent.com/5534045/59545287-6769f700-8eea-11e9-80f1-fe2c5e335fdb.jpg)

### Device info

**Device:** Motorola Moto X4
**Android version:** 9.0
**Signal version:** 4.41.5

**Comment by alan-signal** [comment]
Avatars have always been jpegs, so they have never supported transparency.

Therefore this is a feature request rather than a bug. Please make feature requests on the forum https://community.signalusers.org.

**Comment by yaomtc** [comment]
By "dropped" I meant "removed the transparency of the image", not "it supported transparency and now it doesn't". I did not know whether this worked before, so I wasn't sure if it was a bug. Since I now know it converts everything to JPEG, I'll go make a request. Thanks.
