### ISSUE TITLE
Note to self disappears from contact list if all messages are gone

### ISSUE THREAD

**Issue by hehnope** [signalapp/Signal-Android#8876]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you delete all your messages in "note to self", then in the message list "note to self" will no longer be there. You will have to dial your own number to bring it back up for when you want to send yourself another note.

### Steps to reproduce
1. Add a note.
2. Delete that note.
3. Go to your message listing; Note to Self will not be there.

**Actual result:** Note to Self is gone from the message listing (where your contacts are right when you open the app)
**Expected result:** Note to Self should always exist even if there is no "note to self".

**Comment by greyson-signal** [comment]
This is expected. We only show conversations in the conversation list that have actual messages in them.

**Comment by hehnope** [comment]
@greyson-signal but it's inconsistent with signal-desktop. signal-desktop does what the expected result is.

**Comment by greyson-signal** [comment]
You're defining the "expected result" based what signal-desktop does, and I'm defining it by how it works in signal-android, which takes precedence in this case. The reason signal-desktop keeps empty conversations around is because there's no "contact list" on signal-desktop. Everything shows up as conversations. That's not how signal-android works. We only keep conversations for messages with contents.

**Comment by hehnope** [comment]
Well, I'm defining it from a user experience; as a user, when I'm done with a note I delete it. At some point, I will have no notes in the android app; and, during that time the "Not to Self" disappears from the messages UI. I then, have to re-type my number in to find it (this is a bad user experience). Sometimes, my number changes, I do not want to have to remember my number to send myself a note. I'm merely pointing out that signal-desktop/signal-android have a slightly different user experience in this regard. I had presumed it might have been a bug because of the inconsistency between signal-desktop/signal-android.

**Comment by greyson-signal** [comment]
You can always search for "note to self" and it should show up. No need to type your number.

I do consider the github-related discussion related to this closed, though. I understand your point, but the way it works now is intended. If you want to continue discussion, please open a thread on [the forum](https://community.signalusers.org/). Thanks!

**Comment by nahuhh** [comment]
Just adding my 2 cents. 
After reading this issue, I see where the OP is coming from.

I think a better solution would be to be able to "pin" chats. With a few additions/improvements to the overall experience. 

- chat pinning 
- settings>chats and media option for pinned chat sorting: "pin to top" vs "timestamp". Timestamp being default
- in chat option to clear chat history
