### ISSUE TITLE
Cannot send or receive images. Certificate on cdn.signal.org is not trusted.

### ISSUE THREAD

**Issue by jasonborchardt** [signalapp/Signal-Android#8880]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can not send or receive images.  Debug logs show ssl errors to cdn.signal.org, when I look at the cert for that site I see two different things intermittently.  I either get HSTS errors, or errors that the certificate expired 452 days ago (even though it appears to expire on March 12th 2029).

I am not using a proxy, I have reproduced this issue on multiple WiFi networks and also via Cellular.  I am getting the certificate issues on multiple devices.

### Steps to reproduce
- attempt to send a picture in signal

**Actual result:** Image fails to send or download
**Expected result:** Images should download or send.

### Device info

Device: iPhone (iPhone10,6)
iOS Version: 13.0 
Signal Version: 2.40.0.25 

### Link to debug log
https://debuglogs.org/83775bc15c88114389f018e959ecc78267709f77803012a2b50d5b46bf167de2.zip

**Comment by jasonborchardt** [comment]
I updated the app this morning and I’m betting that is related.

**Comment by greyson-signal** [comment]
First, this is the Android repository. You can open iOS issues over at the [iOS repository](https://github.com/signalapp/Signal-iOS) :)

However, I checked with the iOS folks, and apparently this is a known issue with iOS 13 (which isn't yet publicly released). They're working through it.

**Comment by pahrohfit** [comment]
Fix:

https://reddit.com/r/signal/comments/c2q6c6/_/erqv7y1/?context=1
