### ISSUE TITLE
Notifications not waking up screen

### ISSUE THREAD

**Issue by ayoits0913** [signalapp/Signal-Android#8881]
Galaxy S7 / Android 8.0

Signal app not waking up screen. Not sure what else i can say. Do not disturb isn't on and i've even added a custom exception for it.

How can i change this? Been looking all over, seeing several posts with no good answer

**Comment by greyson-signal** [comment]
Message notifications are posted with "high" priority, which is the highest we can set. You can check your system notification settings to make sure they haven't been downgraded (Signal System "App Info" settings > Notifications > Messages channel).
