### ISSUE TITLE
Android 4.1 compatibility removed

### ISSUE THREAD

**Issue by ka223** [signalapp/Signal-Android#8889]
The requirements changed from Android 4.1 to 4.4, is this unavoidable?

I can not upgrade these devices, manufacturer do not offer updates for older devices.

**Comment by johanw666** [comment]
That was done to be able to upgrade a library. It is discussed here: https://community.signalusers.org/t/why-drop-ics-jelly-bean-support/6825

**Comment by five-c-d** [comment]
> I cannot upgrade these devices

The workaround is to install the final version which WAS compatible with being installed onto android 4.1 / 4.2 / 4.3 devices, Signal-Android v4.36.2 stable-channel-playStore-release which is archived on various websites.  https://community.signalusers.org/t/why-drop-ics-jelly-bean-support/6825/44 and https://community.signalusers.org/t/cannot-re-install-signal-to-my-android-4-3-phone/7202 have details.  

*    `keytool -list -printcert -jarfile "D:\bxd\DKL Phone\Signal_APK\org.thoughtcrime.securesms_4.36.2-470_m inAPI14(armeabi,armeabi-v7a,x86)(nodpi)_apkmirror.com.apk" | grep SHA256`

*  presumably ought to produce something like this, from the March 2017 apk == 
`29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26`

The commands above will verify whether you have the signed-by-Signal-Foundation APK for your handsets.  Do note that this is **unofficial**, your v4.36.2 codebase will NOT be receiving further updates/fixes/etc.

**Comment by ka223** [comment]
@five-c-d
But this version is will only work for a limited time, right? 
Older releases are not working anymore.

**Comment by PiCob** [comment]
> But this version is will only work for a limited time?
> Older releases are not working anymore.

_Usually_, the official Signal builds expire after some weeks or months, but if you install **v4.36** on a **pre-Android-4.4.4-device**, Signal will detect this and should never expire.
If you have further questions, feel free to join the [Community](https://community.signalusers.org) (you can use your GitHub credentials to log in there), because GitHub is supposed to be used for bugs only.
Thanks!
