### ISSUE TITLE
Rapid taping selection buttons crashes Signal

### ISSUE THREAD

**Issue by zznidar** [signalapp/Signal-Android#8891]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tapping rapidly on any of the buttons at the top of the screen after selecting a message (Details, Delete, Copy, Forward, Save, Reply) results in a crash. 

### Steps to reproduce
- Open a conversation.
- Select a message.
- Rapidly keep tapping one of the buttons that appear at the top.

**Actual result:** Signal crashes.
**Expected result:** Signal should not crash.

### Device info

**Device:** Pocophone f1
**Android version:** 8.1.0
**Signal version:** 4.42.3

### Link to debug log

Happens every time, might be because the button is still there to be clicked while an animation is playing, but has actually already been clicked and should therefore disappear.

**Comment by alt0r** [comment]
I can confirm this bug.
Enclosed is the stacktrace when repeatedly tapping on message details after selecting a single message. 
App also crashes when selecting multiple messages and repeatedly tapping delete or copy.
 [signal_android_stacktrace_bug8891.log](https://github.com/signalapp/Signal-Android/files/3330976/signal_android_stacktrace_bug8891.log)
