### ISSUE TITLE
You have new messages" Notification keeps popping up when a message is unread.

### ISSUE THREAD

**Issue by burads** [signalapp/Signal-Android#8896]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notification: "You have new messages" keeps appearing when a message is unread.
 - Started in version "Signal 4.42.3"
 - Notification setting "Repeat Alams" is set to Never

### Steps to reproduce
- Leave a message unread
- Wait up to 5 minutes. Will keep making new notifications.
- If smart watch is configured for notifications from Signal. It will almost constantly vibrate with the "You have new messages" notification.

**Actual result:** Notification "You have new messages" appears.
**Expected result:** "You have new messages" should never appear when "Repeat Alams" is set to Never

### Device info

**Device:** Samsung Galaxy Note 8 (SM-N950F)
**Android version:** 9, 
**Kernel:** 4.4.111
**Signal version:** 4.42.3

**Comment by burads** [comment]
**Screenshots**
http://stiil.dk/images/signal.13-16.JPG
http://stiil.dk/images/signal.13-20.JPG

**Link to debug log**
https://debuglogs.org/53bb15b2ce1aa9d4e42749f461219bb5b8e67ec2105de7187da564fb2d3c5673

**Comment by greyson-signal** [comment]
Your message requests seem to be consistently timing out, which is sometimes what happens when the device is throttling an app’s network access. Did you used to see the “Retrieving messages” notification in previous releases?

This isn't really linked to whether or not you have an actively unread message. It just depends on you getting some sort of message (could be an 'invisible' message, like a read receipt) that we're unable to fetch.

Can you try killing the application (System App Info for Signal -> Force Stop) and let me know if that improves things? I'm trying to narrow down what kind of situations cause this to occur.

**Comment by burads** [comment]
@greyson-signal might be related. I have experienced the last "month ish" that it at times previously hade a  “Retrieving messages” that at times could be minutes to tens of minutes delayed compared to massages received in the signal desktop app.

Have tired the "Force Stop" and will see if it helps.
Though my wife also uses signal and have seen the same issue over the last "month ish" that messages can at times be minutes to tens of minutes delayed on the phone. 

Also the App just restarted this morning due to the update to "4.42.3"

**Comment by nikdale** [comment]
For me, the issue is that notification is popping up every 30-40 seconds if I read it. If I leave it in notification bar, no new notif occurs.


![2019-07-21 17-24-54](https://user-images.githubusercontent.com/13356513/61593350-b3d9de00-abde-11e9-8dfd-9cb9b5019913.JPG)

**Comment by greyson-signal** [comment]
I think this notification has been causing more trouble than it's worth. I'm going to be removing it in 4.44.x.

**Comment by Herohtar** [comment]
@greyson-signal Thank you! You have no idea how many times my family members have come to me with that notification asking, "why is Signal saying I have new messages, but when I open the app there aren't any??"

**Comment by tsambou** [comment]
Hello. Suddenly a few weeks ago I started getting this notification spamming while I have no new notifications in my Signal app except from groups that are muted and some unread messages. Any news on the topic?

**Comment by greyson-signal** [comment]
@tsambou A log would be helpful for us to help diagnose, but this notification means that we got a push notification, but we could not get enough information to render the content. 

Unfortunately, we do not have enough information from the push notification itself to know whether or not the group is muted. So it's possible to see this for messages to muted groups.

If we have a log (Settings > Help > Debug log), we might be able to figure out why this is happening to you so much.

**Comment by tsambou** [comment]
@greyson-signal   Unfortunately I could not find a Debug log on my android phone. What I did find is the "Additional message notifications" section which had ~4 notifications per day and seems to be the probable cause. I now muted these and hope the problem will go away! And thanks for the quick reply!
