### ISSUE TITLE
Soft keys not visible in dark mode

### ISSUE THREAD

**Issue by carlolars** [signalapp/Signal-Android#8897]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When selecting the dark theme the soft key bar goes all black and the soft keys are no longer visible, but tapping on their location is working.  
This was working as expected ~2-3 weeks ago but has not been working for the last two updates. Related to the fix for #8758?

### Steps to reproduce
- Switch to Dark theme

### Screenshots

![Signal-dark-50](https://user-images.githubusercontent.com/13761538/60364558-c9485780-99e6-11e9-923d-d117df85bf2b.png)

### Device info

**Device:** Sony Xperia XZ1    
**Android version:** 9.0
**Signal version:** 4.42.3

**Comment by UserX404** [comment]
I can report same issue for Sony Xperia XZ2c Andoid 9.
But softkeys are visible on HTC One Mini2 (Linage 14.1)

**Comment by greyson-signal** [comment]
I think this was addressed in 4.49.x.

**Comment by carlolars** [comment]
Just enabled dark mode and can confirm that it works, thanks!
