### ISSUE TITLE
Crash every time call made or received

### ISSUE THREAD

**Issue by signaltester** [signalapp/Signal-Android#8900]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When a call comes in (not even when it's answered), Signal crashes. Same when I try to place a call. In either case, I hear the appropriate sound just beforehand.

### Steps to reproduce

I suspect you need the most recent update (6/2019, I guess). I reinstalled factory settings, then installed only Signal and no other apps, and it still failed.

**Actual result:** 

"Unfortunately, Signal has stopped" 100% of the time. All other messaging functionality works.

**Expected result:**

Actually make and accept calls. Was working fine until a few days ago.

### Screenshots

Nothing to show.

### Device info

Device: Samsung Galaxy S5
 Android 5.0
Signal: 4.42.3

### Link to debug log

Maybe can provide.

**Comment by shuttle1987** [comment]
I have run into exactly the same issue with this version of signal (4.42.3), can also provide a debug log if that would help.

**Comment by signaltester** [comment]
@shuttle1987 Please attach it here if possible. That would expedite the solution to this problem, if it's going to happen at all. Just be aware that debug logs leak information about you, even if not overtly so. If you can provide the same device info as I did, that would help too.

**Comment by alternativesurfer** [comment]
Here is my debug log, same issue.

https://debuglogs.org/c2168ac75a6444ec3ee591828f8554a2c271d7962b4a4c28168fbb9afc00cbe8

Installed OS >> Can place phone calls
Installed Signal Messenger >> Can place phone calls
Made Signal Voice call >> Phone locked up for appx 90 seconds, then restarted itself
Now even placing a regular phone call causes the phone app to become unresponsive (doesn't reboot the phone, but the call never connects on the local end...remote end receives the call but no audio transmits).

**Comment by signaltester** [comment]
@alternativesurfer Thanks. What happens if you receive a call? In my case, it crashes the app without me doing anything.

**Comment by signaltester** [comment]
This seems to have been fixed by an upgrade from Android 5.0 to 6.0.1. However, alternativesurfer indicated that it still seems to occur under Android 9. Android 5.0 was working fine for months until calls got broken by Signal 4.42.3. Of course I don't know whether something about that Signal version inadvertently activated a bug in Android, or whether changing Android to 6.0.1 created different latencies that helped to hide a bug in Signal. I'll post back here if the call failure comes back. (It may well do so. The audio problem in #8904 did exactly that, shortly after being fixed by the same upgrade.)

**Comment by alternativesurfer** [comment]
@signaltester

Yes, receiving a call will also cause the app to crash without user intervention. 

Thank you for looking into this, it's obviously an annoying bug to have.

**Comment by signaltester** [comment]
@alternativesurfer @alan-signal So that means at least two of us have exactly the same symptoms on very different Android versions. Considering that users don't even know this Github repo exists, let alone want to post issues to it, there are probably many more out there.

**Comment by JLeo23** [comment]
Same problem. 

Device: Samsung Galaxy S5
Android 5.0 
Signal: 4.42.3

Downgrading to 4.41.6 resolved issue for me.

**Comment by alternativesurfer** [comment]
Issue still persists for me on 4.44.7

**Comment by alternativesurfer** [comment]
No one?

This is really disappointing...I can't use my telephone feature with Signal installed....

**Comment by badsignals** [comment]
I am having the same issue also, Past three versions - same issue; can text send and receive but incoming or outgoing phone crashes app.  Looks like java problem:  E/UncaughtExceptionLogger( 6188): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.WebRtcCallActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class org.thoughtcrime.securesms.components.webrtc.WebRtcCallScreen


Multiple tickets, ways to send logs etc, no response from anyone.  See happening here too.  Is probably something simple but what?  I reloaded OS and still have problem!!!!

**Comment by greyson-signal** [comment]
@badsignals You may have a different issue. Can you post a full debug log, or let us know more about your device (model, android version, etc)?

**Comment by badsignals** [comment]
https://debuglogs.org/4d09e69b8ef5a354c419a2c11a8623c13d91dbb7342d3cd03909ae0a234bd6a4

Galaxy S5, MOAR Rom, Last 3 updates fail same way, before old version was
cut off was able to use voice fine.  Had version, saved in Titanium backup
but re-restoring my phone.

**Comment by alan-signal** [comment]
@alternativesurfer Does this still happen for you? Can we get a fresh log please?

**Comment by badsignals** [comment]
Yes app updated today, still happens.

https://debuglogs.org/dac6ea06978810843d5d1dd4429097448a00842a957122a07214438546cd813b

**Comment by alan-signal** [comment]
@badsignals Thanks, but I was asking @alternativesurfer as the their debug log has expired, and I suspect it's a different issue.

In your case, I have been unable to recreate on Android 5 myself. Did it ever work on MOAR rom?

**Comment by badsignals** [comment]
Sorry,

This did work on MOAR 4.41.6 was last working then the developer expired it
forcing an upgrade. Voice has not worked since.  Sad.

**Comment by alan-signal** [comment]
The problem points to a ROM problem, the fact it started when MOAR forced an upgrade too I think it is worth asking them to look at. You could give them the same logs, the interesting part is:

```
E/UncaughtExceptionLogger(24888): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.WebRtcCallActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class org.thoughtcrime.securesms.components.webrtc.WebRtcCallScreen
E/UncaughtExceptionLogger(24888): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
E/UncaughtExceptionLogger(24888): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
E/UncaughtExceptionLogger(24888): 	at android.app.ActivityThread.access$900(ActivityThread.java)
E/UncaughtExceptionLogger(24888): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
E/UncaughtExceptionLogger(24888): 	at android.os.Handler.dispatchMessage(Handler.java)
E/UncaughtExceptionLogger(24888): 	at android.os.Looper.loop(Looper.java)
E/UncaughtExceptionLogger(24888): 	at android.app.ActivityThread.main(ActivityThread.java)
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Method.invoke(Native Method)
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/UncaughtExceptionLogger(24888): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/UncaughtExceptionLogger(24888): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
E/UncaughtExceptionLogger(24888): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class org.thoughtcrime.securesms.components.webrtc.WebRtcCallScreen
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createView(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
E/UncaughtExceptionLogger(24888): 	at android.app.Activity.setContentView(Activity.java)
E/UncaughtExceptionLogger(24888): 	at org.thoughtcrime.securesms.WebRtcCallActivity.onCreate(WebRtcCallActivity.java:77)
E/UncaughtExceptionLogger(24888): 	at android.app.Activity.performCreate(Activity.java)
E/UncaughtExceptionLogger(24888): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
E/UncaughtExceptionLogger(24888): 	... 11 more
E/UncaughtExceptionLogger(24888): Caused by: java.lang.reflect.InvocationTargetException
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/UncaughtExceptionLogger(24888): 	... 21 more
E/UncaughtExceptionLogger(24888): Caused by: android.view.InflateException: Binary XML file line #173: Error inflating class org.thoughtcrime.securesms.components.webrtc.WebRtcCallControls
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createView(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at org.thoughtcrime.securesms.components.webrtc.WebRtcCallScreen.initialize(WebRtcCallScreen.java:233)
E/UncaughtExceptionLogger(24888): 	at org.thoughtcrime.securesms.components.webrtc.WebRtcCallScreen.<init>(WebRtcCallScreen.java:96)
E/UncaughtExceptionLogger(24888): 	... 23 more
E/UncaughtExceptionLogger(24888): Caused by: java.lang.reflect.InvocationTargetException
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/UncaughtExceptionLogger(24888): 	... 32 more
E/UncaughtExceptionLogger(24888): Caused by: android.view.InflateException: Binary XML file line #52: Error inflating class <unknown>
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createView(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
E/UncaughtExceptionLogger(24888): 	at org.thoughtcrime.securesms.components.webrtc.WebRtcCallControls.initialize(WebRtcCallControls.java:59)
E/UncaughtExceptionLogger(24888): 	at org.thoughtcrime.securesms.components.webrtc.WebRtcCallControls.<init>(WebRtcCallControls.java:49)
E/UncaughtExceptionLogger(24888): 	... 34 more
E/UncaughtExceptionLogger(24888): Caused by: java.lang.reflect.InvocationTargetException
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/UncaughtExceptionLogger(24888): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/UncaughtExceptionLogger(24888): 	... 41 more
E/UncaughtExceptionLogger(24888): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/webrtc_camera_flip_button.xml from drawable resource ID #0x7f08025a
E/UncaughtExceptionLogger(24888): 	at android.content.res.Resources.loadDrawableForCookie(Resources.
```

**Comment by badsignals** [comment]
Problem is the last update made by moar Was over 2 years ago. No ota
upgrades. Signal is only app that stopped working unless I downgraded
signal app. Have tried two separate copies of moar, just in case.

Anyone have idea of cause?

**Comment by alan-signal** [comment]
> Signal is only app that stopped working unless I downgraded
signal app

What do you mean? you have downgraded signal and it worked? Finding the exact version that started causing the problem would give us a clue.

**Comment by badsignals** [comment]
4.41.6 was last working version. Then it was text only for any version
newer. Still same now.

Each time I restore the version above it worked voice and text as normal.
Any version above 4.41.6 was and still is text only.

See three protected versions? All worked until development forced switch to
new version.

Thanks

**Comment by badsignals** [comment]
So, is this possibly that Java versions upgraded for the new signal
4.47.6?  And since OTA update is not available - I did not get a new Java
Version; thus causing the failure?

If so, where as a non-developer do I get the Java?  Worth a try since its
already broke.  All other Application work fine.

Thank you all who are following this issue, I hope it helps others in the
field who may depend on Signal for life safety.

**Comment by badsignals** [comment]
https://debuglogs.org/e63e343b3f9f4ef57991c1f99fba1d4b2a621a8f6bc598c828adef7f77b02822

**Comment by badsignals** [comment]
Brand new room load last night. Still can text no voice calls. Someone help
and I will PayPal for time .

**Comment by alan-signal** [comment]
There is no need to keep sending us logs.

I would like to see fresh logs from other people/devices though.

**Comment by badsignals** [comment]
The product has not worked for voice calls for some time, If there are no
support resources, who knows when other logs will come in or if this is an
isolated incident because of another app.

So, I can buy a new phone and try your app,
Use another free app
or hope someone supplies suggestions because I do not read these logs often.

Again, this happened on a version change.  Until enough logs come in, can
the force upgrade be turned off?  If not tell me to get another
application.  I even offered to pay supporting the cause - Likely
developers see something simple - that I may be able to fix, or tell me a
reasonable cost to look at the problem.  To me someone made a significant
change during a version change and broke it.  And I am being punished for
it.

**Comment by The-Drake** [comment]
Hi all, here is a fresh log with nullpointer error calling or receiving calls. Both audio and video. Internal speaker or wired headset.

LG G6 - Android 9

https://debuglogs.org/41de8eec35ac7a9c4a3a9b814d33294b16ad8d1c17cb2566cb2c0e5fe1c604a7

**Comment by The-Drake** [comment]
> Hi all, here is a fresh log with nullpointer error calling or receiving calls. Both audio and video. Internal speaker or wired headset.
> 
> LG G6 - Android 9
> 
> https://debuglogs.org/41de8eec35ac7a9c4a3a9b814d33294b16ad8d1c17cb2566cb2c0e5fe1c604a7

Really fast fix, Thanks! 4.56.1 Fixed issue! :)

**Comment by badsignals** [comment]
Still have same issue with latest version.

Galaxy S5

https://debuglogs.org/69b8edb64c5295bc1199bc14df4090a256ec3242f47d4241d411abf2d8bf920b

**Comment by witekdev** [comment]
@greyson-signal @alan-signal 
This is still not working on the latest 4.56.1 beta with a galaxy S5 Android 5.0
I was wondering if you (or anyone else in the dev team) are making any progress with this?
Thank you

**Comment by witekdev** [comment]
I no longer experience this issue. I has not been an issue for quite sometime. Thank you
