### ISSUE TITLE
Audio messaging fails unil Signal storage is cleared

### ISSUE THREAD

**Issue by signaltester** [signalapp/Signal-Android#8904]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Bug description

Soon after installing Signal, audio messages fail to play. I can still send audio messages to others, and they can play them, but I can't play any of them, regardless of whether they were sent or received. This includes messages that previously played just fine.

Workaround is to clear Signal's memory in the Android Application Manager. That's hugely inconvenient, of course, because it deletes the entire message history and forces SIM reregistration. Definitely don't do it unless you're sure that you remember your registration lock PIN, if you ever set it up.

Actual result:

Error playing audio.

Expected result:

Play the audio.

Device info

Device: Samsung Galaxy S5
Android 5.0
Signal: 4.42.3

Link to debug log

Maybe can provide.

**Comment by signaltester** [comment]
Please consider buying a bunch of old phones and using them for regression testing.

**Comment by signaltester** [comment]
Perhaps this occurs because your storage gets corrupted when Signal crashes in the middle of a write operation. (It sounds like you're not doing atomic writes in the fashion of a journaling file system, so you have no ability to revert to the last-known-good storage image, should a crash occur in the middle of a write operation. Not doing so has potential security ramifications.) Lots of crashes lately due to https://github.com/signalapp/Signal-Android/issues/8900 This is only a theory, but it's consistent with evidence.

**Comment by alan-signal** [comment]
We will need the debug log after playback has failed.

Also, I am confused by "Soon after installing Signal, audio messages fail to play" and "This includes messages that previously played just fine.": How was it possible to play them before Signal was installed?

**Comment by alan-signal** [comment]
> Please consider buying a bunch of old phones and using them for regression testing.

We do have a Galaxy S5, only it's running 6.0.1 and I see no such issue on it.

**Comment by signaltester** [comment]
@alan-signal

Thanks for looking at this. What I meant was that I can send and receive and play voice messages for a while. Then after maybe tens of voice messages, it just says "Error playing audio!". From that point on, I can still send and receive them, but never play them until I clear Signal's storage. This even applies to voice messages that I previously received and played (in the current Signal instance prior to the failure).

I might add that I've seen this before on random occasions, and my peers have occasionally complained of similar phenomena, which seem to come and go with various updates. (It's severe enough, combined with other bugs, that it's materially affecting your adoption rate, if my own social network is any clue.) Unfortunately, I have no specific information on those failures. I do have this from my own log, however:
---------------------------------------------------
I ConversationActivity: updateReminders(false)
I ConversationActivity: updateDefaultSubscriptionId(null)
D AudioView: playbutton onClick
W AudioSlidePlayer: MediaPlayer Error:
com.google.android.exoplayer2.ExoPlaybackException:
com.google.android.exoplayer2.upstream.HttpDataSource
$InvalidResponseCodeException: Response code: 502
D AudioSlidePlayer: onPlayerStateChanged(true, 1)
W AttachmentServer: null
W AttachmentServer: java.net.SocketTimeoutException
W AttachmentServer: at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
W AttachmentServer: at java.net.PlainSocket.implAccept(ServerSocket.java:216)
W AttachmentServer: at java.net.PlainSocket.accept(ServerSocket.java:140)
W AttachmentServer: at org.thoughtcrime.securesms.attachments.AttachmentServer.run(AttachmentServer.java:82)
---------------------------------------------------

**Comment by alan-signal** [comment]
Was that a file that previously played?

**Comment by signaltester** [comment]
Not in this case, no. Although the failure is identical from the user's perspective, regardless.

**Comment by signaltester** [comment]
@alan-signal Upgrading to Android 6.0.1 from 5.0 temporarily fixed the problem, without the need to clear any Signal data. It broke again several voice messages later. Perhaps if you can think of what gets reset during such an upgrade, you might stumble upon the root cause.

**Comment by haffenloher** [comment]
@signaltester Could you provide a new log captured on Android 6 after failing to play back a file that previously used to work?

**Comment by signaltester** [comment]
@haffenloher At the moment, it's working again. This time, however, I'm virtually certain that it didn't fix itself as a result of an update, as I've received no notification of any update since the one which took me to 6.0.1. The only intervening event which might relate is the fact that I went into the phone settings and disabled all the bundled crapware that I possibly could. As you might expect, my telco ships a bunch of third party garbage with the phone. I'm not even able uninstall it. At most, I can just revert it to the factory version. All I can do is "force stop" on every app I can find.(Most insidiously, they seem to resume business when an upgrade occurs. I had done this all before, but forgot to do it again after the 6.0.1 update.) Just now I tried to supply your debug log, but discovered that my voicemail messages, which were definitely broken prior to my "force stop" modifications, are now working again. Perhaps a binary search of crapware subsets would reveal the source of problem, or the app which causes Signal to stumble upon its own problem.

**Comment by signaltester** [comment]
I would now say that this failure occurs, then undoes itself, rather randomly. Yesterday, I was able to play a message fine. Then I went to check for system updates (but not download any). When I returned to Signal, audio messages were suddenly broken. Then last night, they fixed themselves somehow. This morning, I repeated the experiment, but it didn't break the messages as before.

**Comment by signaltester** [comment]
I *might* have found a workaround. When it says "Error playing audio", go ahead and record a new voice message, and allow it to send (by lifting your finger). Let the send complete, along with the 2 checkmarks. Suddenly, just maybe, voice messages will start to play again.

**Comment by signaltester** [comment]
I *might* have found a workaround. When it says "Error playing audio", go ahead and record a new voice message, and allow it to send (by lifting your finger). Let the send complete, along with the 2 checkmarks. Suddenly, just maybe, voice messages will start to play again.

**Comment by signaltester** [comment]
Well, so much for my workaround. It doesn't actually work. This is a horrible problem that randomly breaks and fixes voice message playback for hours to days at a time. At the very least, it would be nice to have an option when a playback error, for example: "Error playing audio. Do you want to try to fix this problem by resetting the audio context with Android? Or resetting Signal's own audio interfaces? Or something like that because you're really desperate and this app is becoming less usable by the day?"

**Comment by alan-signal** [comment]
Can we have logs?

**Comment by signaltester** [comment]
Yep, the relevant section of the log was posted above. (Obviously you can't see "above" unless you're actualy logged in to Github.)

**Comment by alan-signal** [comment]
If you mean https://github.com/signalapp/Signal-Android/issues/8904#issuecomment-507698746

Are the logs always the same?

Do you have any issues playing back video?

**Comment by signaltester** [comment]
Yes 8904. Yes, the logs appear to consistently fail in the same way, starting with the "MediaPlayer Error". I've had sporadic video playback problems, but very rarely and always one-off. It's not like the audio problem, which affects all messages simultaneously, until it randomly fixes itself for a while. The video failure rate is frankly acceptable.

**Comment by signaltester** [comment]
I think I finally found a decent workaround. When the audio fails to play, you can hold your finger on the little audio player thing, and once it selects (highlights), tap the storage icon (usually a floppy disk) that comes up at the top of the screen. Then go to your music player, say Google Music, and play it there. Of course this is 100% insecure at that point, but sometimes you gotta do what you gotta do. Just don't forget to delete it from the music player when you're done. It would also be wise to completely disconnect from the network during the entire exercise, so probably it won't get uploaded to Big Data once you reconnect.

**Comment by greyson-signal** [comment]
@signaltester Can you test the 4.44.x beta and let me know if it fixes your problem? You can join the beta [here](https://play.google.com/apps/testing/org.thoughtcrime.securesms).

**Comment by signaltester** [comment]
@greyson-signal Well, the problem last occurred several days ago, so it would be difficult to determine whether or not it had actually ceased for good. I can't get the beta, but what I can do is ping back here once a month, starting when the next update comes down which is presumably based on that beta. If at some point a whole month goes by with no issue, then I suppose we can mark this as resolved. Any ETA for the next Android drop?

**Comment by signaltester** [comment]
It's been a while and this hasn't occurred again. Perhaps it was just a server problem, or perhaps I've just been lucky lately.

**Comment by greyson-signal** [comment]
Your logs indicated an error with the local http server that we used to use to stream-decrypt voice notes during playback. I removed that in favor of an actual ExoPlayer datasource, so I'm assuming that fixed the problem. Let me know if it happens again!
