### ISSUE TITLE
Auto-updating APK only works with WiFi / WLAN

### ISSUE THREAD

**Issue by micressor** [signalapp/Signal-Android#8905]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal should offer updates, no matter what connection (WiFi, Mobile Data, LAN) to the Internet exists. Currently the APK updater only updates if a Wifi connection exists.

Similar issues:
* [Can't update Signal standalone APK #6740
](https://github.com/WhisperSystems/Signal-Android/issues/6740)
* [Auto-updating APK works only sporadically #6740](https://github.com/signalapp/Signal-Android/issues/7189)
### Steps to reproduce
* Check [latest.json](https://updates.signal.org/android/latest.json) to be sure, that is a newer version available.
* Wait for maximal 24 hours to be prompted for the update.

**Actual result:**
* If I am connected to WiFi, the update will be offered.
* If I am connected to mobile data I do not get an update.

**Expected result:**
* I would like to have the possibility that an APK update is also offered with mobile data or LAN (USB2LAN adapter).

### Device info

**Device:** Fairphone 2 (FP2)
**Android version:** 8.1.0
**Signal version:** 4.41.5

### Link to debug log
The updater job seems to be limited to Wifi networks: [UpdateApkJob.java#L145](  https://github.com/signalapp/Signal-Android/blob/9b8719e2d56a098502475bb5b2295c7a376d4caa/src/org/thoughtcrime/securesms/jobs/UpdateApkJob.java#L145)

**Comment by alan-signal** [comment]
The WiFi restriction is deliberate as you point out.

```
downloadRequest.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_WIFI);
```

Which means this is not a bug but working as intended.

Please discuss feature requests on the community site: https://community.signalusers.org/

**Comment by nutts0** [comment]
If this is intended than it seems that it doesn't work on my pixel 3. I have the website version installed on my work profile and it updates itself.

**Comment by westonal** [comment]
Thanks @nutts0 I've found a similar report https://community.signalusers.org/t/please-dont-let-signal-use-my-limited-monthly-data-to-download-updates-in-the-background-then-prompt-me-to-install-them/7079

Could do with this as a GitHub issue if you fancy?

**Comment by micressor** [comment]
@westonal For me this is a mistake and not a feature. Users who don't have WiFi at home will never get updates via the APK version - therefore not usable.

How do I know it was intended? If everything in the source code is intended, then there would be no errors in the code according to this definition.

If it helps, I will post the same text in the https://community.signalusers.org forum.

**Comment by micressor** [comment]
Added [this](https://community.signalusers.org/t/auto-updating-apk-only-works-with-wifi-wlan/8288) also to the forum.

**Comment by Herohtar** [comment]
@micressor It's working as intended, so not a mistake or a bug. It's a feature you would like to have, thus a feature request. There are plenty of locations with free WiFi, so unless you're unable to leave your home it's really not a problem.

**Comment by alan-signal** [comment]
I would agree it is a mistake to assume people will always be able to get on to WiFi. (If you could elaborate on your use case on the community site it would be enlightening, i.e. why you are never on a WiFi connection). And it is also a mistake to assume WiFi is unmetered (and I'm assuming the original intention was to prevent large downloads over metered connections).

But I think it is possible for something to be both a mistake/error/oversight and at the same time not be a bug. The only bug in this area currently is that it [doesn't work for everyone](https://community.signalusers.org/t/please-dont-let-signal-use-my-limited-monthly-data-to-download-updates-in-the-background-then-prompt-me-to-install-them/7079).

We just need to discuss it first to find a change that would work for everyone.
