### ISSUE TITLE
Problems sending video file attachments / limits for sending video files way too low

### ISSUE THREAD

**Issue by Drag0nFly** [signalapp/Signal-Android#8907]
Everytime I try to send a video larger than a few seconds in Signal – using either the desktop version or the Android app – I get a "send failed."

This despite the fact that the video has been shrunk (significantly) using HandBrake or ffmpeg, and typically takes a few seconds to transfer to a cloud provider.

It appears that I am hitting a size-limit, although I am not being informed of such. However, the file is only 195mb.

If the attachment limit actually is this low, please consider increasing it. Videos captured directly on a phone typically are much larger than this.

- [x] I have searched open and closed issues for duplicates

Comment - only found old issues (mostly from 2015) and a case from 2018 relating to re-encoding the video while sending.

- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
Sending video files results in "SEND FAILED" from the Signal desktop application. If there is a size limit in place it should inform of such.

### Steps to reproduce
- Capture video on camera or cellphone
- Reduce its filesize to around 1/10th of the original using ffmpeg or handbrake, resulting in a file of less than 200mb
- Try to upload resulting (.mp4) file as an attachment

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** The video should upload or the interface should inform the user that the video is too large. However, *195mb* is not by any means large by today's standards, IMHO.

### Screenshots
n/a

### Device info
**Signal version:** 1.25.1, running on Linux

### Link to debug log

https://debuglogs.org/ee36b67cce0100c974d3ae7ff6a564c2997de964a802b6f90cf61e64bf2685bc

**Comment by alan-signal** [comment]
What is the duration of the 195MB video?

**Comment by Drag0nFly** [comment]
It's 4min 56s. Some details from mediainfo below

Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 195 MiB
Duration                                 : 4 min 56 s
Overall bit rate                         : 5 515 kb/s
Writing application                      : Lavf58.17.101

**Comment by johanw666** [comment]
I used to watch 45-minute episodes at 350MB avi's, mp4 is an even better compression. I'd say that Signal is not intended to exchange high resolution video's that don't make a difference on a phone screen. The size limit is 100MB.

**Comment by Drag0nFly** [comment]
@johanw666, can't help but feel sorry for you if that is the case. 100Mb is still arbitrarily low in 2019, and the world at large have moved to HD content on their smartphones. Most phones nowadays also have 4K recording capabilities, let alone 1080. And mine is several years old.

There are many instances where sending such content directly over Signal is extremely useful. And again, the file has been transcoded to a fraction of the original size in Quicktime (.MOV at 1.3Gb)

**Comment by johanw666** [comment]
1.3GB for less than 5 minutes video is just plain ridiculous if you're not in proffessional astrophysics or satellite imaging. And OWS's data bills do not cover such uses.

**Comment by Drag0nFly** [comment]
How is the original size of the video of any relevance? The actual transcoded video, which hits the limit, is 195Mb as mentioned earlier in the ticket.

**Comment by alan-signal** [comment]
@Drag0nFly This report seems to be two in one:

1. A report of a desktop bug: file too large but all you see is "send failed" rather than a file too large message. That should be reported on https://github.com/signalapp/Signal-Desktop
2. A feature request, to increase the attachment size, which you should put on https://community.signalusers.org

You also say the bug happens on Android, but I do get a too large message, though it doesn't say what the maximum is, it's not a "send failed" situation.

**Comment by Drag0nFly** [comment]
@alan-signal - allright, fair enough. I'll post a feature request to signalusers.org and log a bug with Signal-Desktop.

Didn't realize there were three separate places to log bugs or improvements for Signal. 
(maybe the Android version should also inform what the limit is, though.)

**Comment by Jau-Al** [comment]
> 1.3GB for less than 5 minutes video is just plain ridiculous if you're not in professional astrophysics or satellite imaging. And OWS's data bills do not cover such uses.

In France, you have 100GB per month for 20€ lol. So yes, some people might want to send huge files.
