### ISSUE TITLE
Auto updating website apk uses metered connection while it should use only unmetered

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8908]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Auto updating website apk uses metered connection while it should use only unmetered. For the record. It is installed in the work profile which shelter provides. Maybe this is related.

### Device info

**Device:** Pixel 3
**Android version:** 9
**Signal version:** 4.43.8

### Link to debug log

https://debuglogs.org/60c65077e409a5b77bc11f11e58e6bae3a364e382743bd5d9be6ca749701280e

**Comment by five-c-d** [comment]
Related forum-threads:  

*  https://community.signalusers.org/t/auto-updating-apk-only-works-with-wifi-wlan/8288 which links to the [relevant line of code](https://github.com/signalapp/Signal-Android/blob/9b8719e2d56a098502475bb5b2295c7a376d4caa/src/org/thoughtcrime/securesms/jobs/UpdateApkJob.java#L145) in UpdateApkJob.java that tries to use wifi-only 

*  https://community.signalusers.org/t/libre-licensed-WorkProfile-deviceManagerApp-called-Shelter/8273/14 explains a bit of background on what the Shelter app does, PeterCxy/Shelter is the github-mirror of the codebase, screenshot of nutts0 utilizing the workProfile to have multiple simultaneous signal4android master-device installations on the same physical handset (each with a dedicated distinct signal-num) are here == https://community.signalusers.org/t/samsung-secure-folder/5067/5 

My guess... NOT having tried Shelter on my own devices (the helpdocs warn that you CAN brick your handset if the handset-vendor failed to implement AndroidEnterprise APIs in a fashion that Shelter is compatible with) ... is that the apps in the workProfile-container are connecting to the internet via some kind of virtual-network-bridge ...and therefore signal4android *within* the workProfile is detecting that it is "on wifi" when in reality it is actually just "on virtual-network-bridge that is masking the dataplan-or-wifi of the primaryProfile which is the parent-container".  

In addition to use by people who install Shelter to get multiple installations of signal4android on a single handset, the more common scenario is where 

1.  the handset is a corporate-provided device 
2.  the firm has standardized on signalapp for employee comms 
3.  the firm is paying for an AndroidEnterprise EMM server subscription
4.  this is how they do corporate VPN and rollout of curated APKs to work-handsets 
5.  which means signal4android will be inside the workProfile for all employees 

Point being, although nutts0's specific use-case is a bit of a rare situation, there *is* a good reason to fix this bug (we want to encourage firms that have strong infosec requirements to be able to standardize on signalapp for all employees).  APK downloads from 99 employee handsets every month, half of which happen via dataplan and some of which cause the dataplan-cap to be exceeded and overage charges to result, will not make the CFO happy ;-)
