### ISSUE TITLE
Giphy "Nothing Found"

### ISSUE THREAD

**Issue by Gemisphere** [signalapp/Signal-Android#8909]
I have searched open and closed issues for duplicates

 I am submitting a bug report for existing functionality that does not work as intended

 I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

 This isn't a feature request or a discussion topic

Bug Description:
When trying to add a gif, message "Nothing Found" appears

Steps to reproduce
-open signal
-compose new text
-click plus sign ➕
-click "GIF"

Actual result:
Screen says "Nothing Found"

Expected result:
Should see gifs to insert into the message. 

Device HTC U11
Android version 8.0.0
Software 2.42.617.7
Signal 4.42.3

![Screenshot_20190704-134804](https://user-images.githubusercontent.com/7810203/60683846-28cfb880-9e68-11e9-8903-55eaf21de9a1.png)

https://debuglogs.org/28d33a2a0d53af9271c5207fd06ecbe06278cb81aa8e15d5e421c7d5c98e2efa

**Comment by Genis-Sage** [comment]
when i read the bug report, i could reproduce it
but after some hours, it worked again

additional information:
the giphy site was working all the time

**Comment by greyson-signal** [comment]
We had a brief outage in our Giphy proxy that was resolved quickly. Thanks!

**Comment by Gemisphere** [comment]
Thanks!
