### ISSUE TITLE
Signal crashes after video send 

### ISSUE THREAD

**Issue by hupsing** [signalapp/Signal-Android#8910]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tried to send a video file of 75 Mb. Signal crashes whike uploading the file (over wifi)
Now Signal does not start any more. It directly crashes at start up!!
Is there a way to fix without losing my conversations. Maybe reeinstalling the app and keeping the data base?!

### Steps to reproduce
- Since Signal is not functioning anymore I have no chance to reproduce

**Actual result:** 
Signal crashes directly at start up
**Expected result:** 
Sending out vids of 75Mb should be possible. Signal starts up as usual.

### Screenshots
Sorry no screenshot 

### Device info

**Device:** Samsung A3 2017
**Android version:** 8.0.0
**Signal version:** 4.43.8

### Link to debug log
 I think I cannot debug since Signal does not start up any more.

**Comment by hupsing** [comment]
I got a hint rom Haffenloher in the Signal community to delete the problematic message starting Signal when in airplane mode. Signal started. Message deleted. Everything is fine again Here is the debug log
https://debuglogs.org/041aff50cc551e3278c14508022d33980cb5d2df93c9fcbc1faa94e36dd205d9
P.S. it was the first time that I tried to send a video of this size(75 Mb)

**Comment by alan-signal** [comment]
Repeated crashes:

```
07-06 15:34:46.575  4257  4424 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
07-06 15:34:46.575  4257  4424 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4257
07-06 15:34:46.575  4257  4424 E AndroidRuntime: java.lang.AssertionError: Not e164, is group
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:136)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.getPushAddress(PushSendJob.java:109)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:203)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:136)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:85)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
07-06 15:34:52.264  5980  6141 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5980
07-06 15:34:52.264  5980  6141 E AndroidRuntime: java.lang.AssertionError: Not e164, is group
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:136)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.getPushAddress(PushSendJob.java:109)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:203)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:136)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:85)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
07-06 15:34:52.264  5980  6141 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
```
etc.

**Comment by greyson-signal** [comment]
@hupsing Was the message sent to a group, or was it sent in a one-on-one conversation?

**Comment by hupsing** [comment]
Hi Greyson. The video was sent to a group (9 members). Signal started the upload showing the information in the notification tray. Then it crashed, I restarted and I think the notification reappeared. But Signal didnt start up anymore and the system told me that signal has crashed.

I really appreciate your hard work on Signal.
Thanks a lot.

**Comment by exallium** [comment]
Having only looked at the code for the first time tonight:

I would start debugging here in `MessageSender` and analyze `Recipient`.  I believe that either the group is _supposed_ to be mms and fall through to the else or `isGroupPushSend` is erroneously failing.

```java
  private static void sendMediaMessage(Context context, Recipient recipient, boolean forceSms, long messageId, long expiresIn)
  {
    if (isLocalSelfSend(context, recipient, forceSms)) {
      sendLocalMediaSelf(context, messageId);
    } else if (isGroupPushSend(recipient)) {
      sendGroupPush(context, recipient, messageId, null);
    } else if (!forceSms && isPushMediaSend(context, recipient)) {
      sendMediaPush(context, recipient, messageId);
    } else {
      sendMms(context, messageId);
    }
  }
```

**Comment by hupsing** [comment]
For your information: I retried to send the video and it was successful the second time. I did not change anything. Both times I was on Wi-Fi.
Another hint. I realized that one group member has uninstalled Signal but is still member of the group. Nevertheless the retry worked fine. Cheers

**Comment by greyson-signal** [comment]
We've since made changes to prevent things like this from happening.

**Comment by stenver** [comment]
This occurred for me again, and I could not open the app anymore - Android, 150mb file, group conversation with 2 people.

Closing and reopening app didn't fix it

Restarting the phone fixed the issue though
