### ISSUE TITLE
Sending a video after playing it in the preview does not stop video playback

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8911]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending a video after playing it in the preview does not stop video playback as you can still hear the audio after pressing the send button.

### Steps to reproduce
- Select a video with sound to send
- Before pressing the blue send button, play the video
- Press the blue send button

**Actual result:** You can still hear the video after pressing the send button and the video uploads
**Expected result:** The video playback stops when you press the send button.

### Device info

**Device:** Samsung Galaxy S7 Edge and Samsung Galaxy S10
**Android version:** both 8.0.0
**Signal version:** both 4.42.3

### Link to debug log
Seems to be easily reproducible

**Comment by alan-signal** [comment]
Backgrounding the app (pressing home for example) also does not cause video to stop.

**Comment by greyson-signal** [comment]
This was fixed.
