### ISSUE TITLE
Image editor: Keyboard doesn't hide when you select highlighter, pen, or crop

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8912]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the image editor, having the keyboard active does not hide it when you use tools that do not use the keyboard.

### Steps to reproduce
1. Select some images to send
2. Make the keyboard show by tapping on composeText or "Add a caption..."
3. Press any of the highlighter, marker, or crop tools

**Actual result:** Keyboard does not hide for tools that don't use the keyboard
**Expected result:** Keyboard hides

### Device info

**Device:** Samsung Galaxy S7 Edge and Samsung Galaxy S10
**Android version:** both 8.0.0
**Signal version:** both 4.42.3

### Debug log
Seems easily reproducible

**Comment by danmoop** [comment]
[fixed](https://github.com/signalapp/Signal-Android/pull/8915)

**Comment by danmoop** [comment]
Hello Alan, I commited another change concerning what you advised me [here](https://github.com/signalapp/Signal-Android/pull/8915#discussion_r301583371).
Please have a look at the [changes](https://github.com/signalapp/Signal-Android/pull/8915/commits/ffb00421a682f14eb16989590759d03be6aced44)
