### ISSUE TITLE
Telemetry/Statistic informations which sending to server

### ISSUE THREAD

**Issue by veyebibice** [signalapp/Signal-Android#8914]
Hi,

What exatcly android app send to server?

- available wifi list
- my phone id
- as default google play telemetry informations
- my installed app list
- others...?...

Can you please define the list of them.

Thanks in advance

**Comment by u32i64** [comment]
This is the repository for the **Signal**'s Android client, and [**Signal**](https://signal.org/) is not the same as **Wire**.

Also, questions like this should have been asked on [community.signalusers.org](https://community.signalusers.org) instead, if they were about Signal. For Wire, you'll likely have better luck on Wire-specific forums/discussions/etc.

**Comment by veyebibice** [comment]
@u32i64 sorry. I just fixed my quesiton. I was asking for signal android app.

**Comment by veyebibice** [comment]
I will ask it on  community.signalusers.org . therefore I am closign this issue.
