### ISSUE TITLE
Person stuck in group, unable to send message or leave

### ISSUE THREAD

**Issue by jeroen7s** [signalapp/Signal-Android#8917]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
1 person in our group which has existed for years, has become unable to send messages in that group, after restarting the phone it was not fixed
I asked her to leave the group and re-join after I invite her, but after leaving on her phone she's still stuck in the group on my phone and the other participant's phones

### Steps to reproduce
No clue, sorry :/

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Person can't be re-invited because she's not left the group according to the other phones
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
We're able to detect she left and re-invite her in the group
### Device info
Pocophone

### Link to debug log
Not created immediately so not sure if usefull, but:
https://debuglogs.org/c2a18c0cfe0c09450de01d841c437feb74be264df0d04fef02483ad92388584d

**Comment by greyson-signal** [comment]
Looks like she's hitting a rate limit error. How many members are in the group?

In the short term, she could try putting her phone in airplane mode for while before opening signal again. That might get her out of the current rate limit scenario she's in.

**Comment by jeroen7s** [comment]
Well that would be weird. 
The group only contains 3 people, and there were only 10 messages sent in that group in total today, before she got this issue.
Also wouldn't you get rate-limited across signal? Sending messages outside of the group still works fine. Not sure why / how she'd hit a rate limit.

**Comment by jeroen7s** [comment]
just received 10-ish messages in the group (of which 7 were test messages) + the message that she has left the group, so it seems like it was a rate-limit thing.
Not sure what could have triggered it though.
Definitely needs better feedback for the user that has been rate-limited. Cause now you have 0 indication that you have been rate-limited.

**Comment by jeroen7s** [comment]
Think this issue can be closed since it's no longer an issue.
Maybe it's good to add a new issue for improving feedback for rate-limited users, as it is totally unclear to them that this is why they're unable to send messages,or maybe this has already been improved since this issue is now 9 months old.
