### ISSUE TITLE
Calling side volume level is too low

### ISSUE THREAD

**Issue by gaydenko** [signalapp/Signal-Android#8920]
At my (family) case the issue takes place when called side is Honor 7C only (running Android 8).

On _incoming_ call (that is somebody calls to that Honor 7C) a volume level is too low on the calling side (say, about 15 dB lower in comparison with expected level; and yes, I understand dB mean very-very well).

At these cases the problem doesn't take place:

1. On outgoing calls from that Honor 7C all is OK

2. If one switches to loud mode (tap speaker icon) on the Honor 7C, other side's audibility becomes great.

So, it seems as if Honor 7C selects wrong mic on incoming
Signal calls.

The issue doesn't take place on raw mobile cell calling and with other messengers.

**Comment by Imnotgoodathis** [comment]
Got similar issue from my one plus 3. If I call anyone on Signal they will barely be able to hear me (they have to put volume on maximum and its like im whispering). If people call me its working fine.

**Comment by hanlectin** [comment]
same here :/
Mi Mix 2S, latest firmware

**Comment by bristow** [comment]
I have the same issue with a CrossCall Core-M4.

The issue doesn't take place on raw mobile cell calling.

Perhaps we could have a microphone setting in Signal's advanced settings?

**Comment by ThomasTraineau** [comment]
Same issue here, using crDroid on android 11. I can hear people but they hear me like if I was whispering...
