### ISSUE TITLE
Phone calls getting rejected during signal calling without notifying.

### ISSUE THREAD

**Issue by itsakhileshh** [signalapp/Signal-Android#8921]
Hi, 
I have Redmi note 4 phone, I recently start using signal but there is a big problem for me. While i am on signal calling and some other person calls me on my main number then his calls get automatically rejected without any notification. I missed almost dozens of calls on my main number. They all say my phone was busy. I think its a big con. Kindly rectify it in future upadtes as soon as possible. I really love start loving this app. I am attaching screenshot. You can clearly see those calls were rejected but in reality i didn't even knew about it nor i was notified during or after call.

Phone model:- Redmi note 4 (snapdragon version)
Sim provider :- Reliance jio (4G
![IMG_20190712_190803](https://user-images.githubusercontent.com/52828039/61133615-64f3c080-a4db-11e9-879a-996133a15769.jpg)
)

**Comment by x80486** [comment]
Just in case this needs some _more weight_, the same happens to me...all the time.

**Comment by greyson-signal** [comment]
This was intended, but doesn't work on most devices. The fact that it's a silent rejection isn't great. Given that we've made it so that Signal calls terminate upon answering a non-secure phone call, I don't think we need this auto-rejection thing anymore, so I've taken it out.
