### ISSUE TITLE
Scroll position changes when a new message is received

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#8924]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I think this is about existing functionality, but it might be considered an enhancement if it was not previously part of a design consideration.

**Actual result** 
When I scroll up in some conversation (meaning, the most recent post is not on my screen) and I receive a new message, the scroll position changes with the height of the new message.
**Expected result:**
When I am viewing the most recent message, I expect any new message to reset my scroll position, but whenever I am not viewing the latest message, I expect the scroll position to stay completely unchanged. The vertical slider might change in length because the conversation is getting longer, but the scroll position should stay the same so I can continue to read or look at an image.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9.0
**Signal version:** 4.43.8

**Comment by greyson-signal** [comment]
Interesting, if this is happening, it's a bug. Is this 100% reproducible for you? I've tried on several devices and can't reproduce. We've had bugs in the past where this would happen in certain circumstances (specifically, if you were looking at a message that was taller than your screen, like a tall image), but I can't reproduce those either.

Oh also, when it happens, is it exactly equal to the message height? Like if someone sends you a tall photo, will your screen completely jump, or will it just move a little?

Thanks!

**Comment by Meteor0id** [comment]
After further testing I have the following answers to your questions:
I am able to reproduce the bug each and every time. If there is a certain circumstance at play, it seems to be happening on most or all of my conversations for most or all of my messages.

It does not evidently matter how tall the message is which I am looking at.

It does not only happen on the initial message once I open the conversation, it happens on every single message I receive.

Although typing indicators are enabled, it doesn't happen while I am typing, only when the message is actually received.

The scrolling seems to be a fixed amount, meaning it does not matter how tall the message is which is being received. On my screen, the scrolling seems to be the height of 2 or three message clouds from the same person, each containing a single line of text. That equals about one fifth or one third of my screen height.

Media messages, even without text added, also cause scrolling, again of the same fixed height.

**Comment by Meteor0id** [comment]
I remember very distinctly that I tested if the height of the incoming message had an effect on the amount of scrolling. I concluded it didn't, but when I test it now I see it actually does:
![signal-attachment-2019-07-20-012433](https://user-images.githubusercontent.com/34976212/61570492-3a7ea600-aa8d-11e9-817c-f02cee620463.gif)

**Comment by BKSpurgeon** [comment]
@Meteor0id excellent bug report. 

I am facing this exact situation everyday. It is absolutely infuriating and I wish to rip out the hair from my head each time it happens!

If I open the app and there are some 50 new messages, then the page scrolls down as each new message is received - the current position of your messages is not retained! Consequently, the user has to manually scroll up to the message that was last read (which may be a day or two earlier) to continue to seamless read the new messages which were just received.

This is not the case whether other messaging services such as Whatsapp or line. As new messages are received, the current position is retained.

**Comment by mmortal03** [comment]
Related to this, there doesn't seem to be a way to mute notifications on a conversation without first browsing into that conversation thread. I often want to be able to mute a conversation, *without* losing my last read spot or lose the unread message count.

**Comment by clothohk** [comment]
Same issues here. The problem is serious in group with hundreds messages per hour.

**Comment by Ennneerrrgggyyy** [comment]
This is definitely a bug and kind of annoying

**Comment by sverps** [comment]
It seems there's a [PR](https://github.com/signalapp/Signal-Android/pull/10676) to fix this issue.

**Comment by Meteor0id** [comment]
Should have been closed along with commit 95978f1
