### ISSUE TITLE
Crash when taking photo in group conversation

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#8926]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
I tried to take photo in a group conversation. After that I clicked the 'shutter' button Signal crashed.

### Steps to reproduce
I tried again after the crash, but that time everything went OK.

### Device info
Device: bq Aquaris X5 Plus (Aquaris_X5_Plus)
Android: 7.1.1 (684, 2.7.0_20181002-1711)
ABIs: armeabi-v7a, armeabi
Memory: 35M (0.00% free, 512M max)
Memclass: 192
OS Host: bqbot3
App: Signal 4.43.8 (5071)

### Link to debug log
https://debuglogs.org/06b08af7a6ec42f8169f488512d0310f6ae72954f0b553279959328c0d0c0c9f

### Additional info
The proximity sensor on my device is broken. Maybe this is related, as I see this exception in the debug log:
`2019-07-13 17:36:33.073 GMT+02:00 D WebRtcCallService: Uncaught exception - releasing proximity lock`

**Comment by PiCob** [comment]
![signal-2019-11-06-204600](https://user-images.githubusercontent.com/23237468/68332121-198aa100-00ce-11ea-80eb-e24b9444a785.jpg)
Dunno, if it's related, but I faced a crash in exactly the same situation. Looks like a different kind of exception, though. Running v4.49.13.
https://debuglogs.org/61237b8fc82b4d65af20e7cd3ec3ccc068c106ead9eace37d5d3f54277e9a0e8
