### ISSUE TITLE
[Issue] Dependency Issues on Android ROMs

### ISSUE THREAD

**Issue by jkhgvfgvsth** [signalapp/Signal-Android#8927]
**Description**: Umbrella issue for fixing the issues disabling users on free-software platforms like [Replicant](https://www.wikipedia.org/wiki/Replicant_(operating_system)) from using Signal. [[more info](https://archive.is/B4Og8)]

In relation to #7988

________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/76913782-issue-dependency-issues-on-android-roms)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=76913782)](https://www.bountysource.com/issues/76913782-issue-dependency-issues-on-android-roms)

**Comment by greyson-signal** [comment]
Hi there, we don't really do "umbrella issues". As noted in our guidelines, github issues are meant to report specific bugs. For discussions, please use [the forum](https://community.signalusers.org/). Thanks!
