### ISSUE TITLE
SMS sent in flight mode stay unsent after leaving flight mode

### ISSUE THREAD

**Issue by PhoenixIV** [signalapp/Signal-Android#8928]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS I send while in flight mode do not get send when going back online, but only after I restart Signal additionally.

### Steps to reproduce
- Enable flight mode
- Send SMS
- Disable flight mode

**Actual result:** The circular loading icon keeps circling
**Expected result:** The SMS is sent automatically

### Additional Info
- SMS was sent after closing and opening Signal again
- SMS was sent after I additionally enabled Wifi (Connection state change)

### Device info

**Device:** OnePlus Two
**Android version:** 8.1.0 (LineageOS 15.1)
**Signal version:** 4.43.8

### Link to debug log
[ Did not want to publish log. There was a contact name in it and I do not have time to check the entire log for data I do not want to share in public. ]

**Comment by greyson-signal** [comment]
@PhoenixIV If possible, could you send the debuglog link via Signal to one of my test devices? +1 610 549 1426. Thanks!

**Comment by PhoenixIV** [comment]
@greyson-signal Done 👍

**Comment by PhoenixIV** [comment]
I still see the problem. The last time flight mode was not even active (had connection) when sending, but now, five hours later, I see that the sending... symbol (rotating disk in main view) is still spinning. Restarting the App (Nothing else!) changed this to first one, then two checkmarks.

**Comment by Laancelot** [comment]
Hello @PhoenixIV , I was hoping to help you with this... I have tried to recreate the error but my text do sends after turning off flight mode. I was wondering, could you please tell me by any chance if you still have this issue on the current version (4.69.6)? Many thanks, cheers

**Comment by PhoenixIV** [comment]
Hi @Laancelot 
I am very sorry for the late reply. I wanted to update my LineageOS, too, since I read your post but still did not do it. I am currently on LineageOS 15.1-20200119-NIGHTLY / Android 8.1.0 and Signal v5.2.3.
I still experience this issue, which I solve by exiting the App (swiping it from my tasks list) and restarting it, after I exited flight-mode. If I manage to update Android/Lineage I will give you another update, of course.

Thanks for your interest. I am curious what causes this issue.
