### ISSUE TITLE
Lost messages on Android and "Message encrypted for non-existing session"

### ISSUE THREAD

**Issue by crimzor** [signalapp/Signal-Android#8930]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
Nothing looks to be the exact shape.
  

---

### Steps to Reproduce

1. I synced to my desktop a few days before the event (4 days before according to the app).
2. I was out of cell range and had no data
3. I came into cell range

Actual Result:

Coming into cell range, 99% of my messages and groups were gone and I was notified for a couple of messages with "Message encrypted for non-existing session".

Hours later, I checked that my Desktop which was synced previously had my messages. It did.

Minutes after checking the Windows box, messages about "x is on Signal!" started pouring in to my Android device. Looks like every contact in my phone book (who has Signal).

To be clear: the Desktop client seems to work as expected and the Android client has the issue.

Expected Result:

I expected Signal to keep working as usual and my messages to be retained.

### Screenshots
Example message (I saw 4-5 of this shape)
![Screenshot_20190715-172722](https://user-images.githubusercontent.com/5025722/61259232-2ace2d00-a72e-11e9-9522-3a6722830870.png)

All notifications incorrectly coming in for users joining Signal (they were previously on Signal)
![Screenshot_20190715-182338](https://user-images.githubusercontent.com/5025722/61259233-2ace2d00-a72e-11e9-8a31-05476cdb5b56.png)

### Platform Info

Desktop Signal Version: 1.25.3
Android Signal Version: 4.43.8

Operating System: Android 7.1.1

Linked Device Version: Windows 7 Ultimate SP1

### Link to Debug Log

Android: https://debuglogs.org/b6412ca09050a8cd50be80447c1a3fa9fc9b44798af2e36f4feb1cc387e28e3e
Windows PC (works as expected): https://debuglogs.org/84c3608870760c0333ce123cff9087ee48f1c4f4700f7fb18e8da163d12211dc

**Comment by marcelvb** [comment]
I had a similar issue, but I haven't tried Signal Desktop. I believe I got a Signal app update just before this happened. It's like the app update deleted the encryption keys?

**Comment by aaronjanse** [comment]
This just happened to me, too. Everyone who texted a friend of mine on Signal suddenly got a screenful of "Message encrypted for non-existing session" followed by one or more "Bad encrypted message."
