### ISSUE TITLE
Cannot search for €$£¥

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8931]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The conversation search doesn't produces results when searching for currency symbols (e.g. €$£¥).

### Steps to reproduce
- Send a message containing a currency symbol
- Search for this symbol

**Actual result:** For some symbols, the symbol is marked, but doesn't count as result.
**Expected result:** Search should work fine.

### Screenshots
![Screenshot_20190718-164159](https://user-images.githubusercontent.com/22525368/61467349-c0123100-a97b-11e9-9169-eb63f81be3ae.png)
![Screenshot_20190718-164224](https://user-images.githubusercontent.com/22525368/61467350-c0aac780-a97b-11e9-92c0-603264827e08.png)
![Screenshot_20190718-164228](https://user-images.githubusercontent.com/22525368/61467352-c0aac780-a97b-11e9-95ab-efa711d0a8c5.png)
![Screenshot_20190718-164233](https://user-images.githubusercontent.com/22525368/61467353-c0aac780-a97b-11e9-863f-8dc903b84841.png)

### Device info

**Device:** Oneplus X
**Android version:** 7
**Signal version:** 4.43.8

### Link to debug log

I can send you the link, if needed.

**Comment by pankarlox** [comment]
Related issue & more #8657

**Comment by greyson-signal** [comment]
We'll track this at #8657
