### ISSUE TITLE
Native Android app sometimes captures messages, but Signal is the default app

### ISSUE THREAD

**Issue by anLGuser** [signalapp/Signal-Android#8932]
- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is my default messaging app and has all access permissions, is excluded from battery optimization, has priority during Do not Disturb. The problem is that sometimes the native Android messaging app captures incoming messages, then they don't show up in Signal. This problem happens only occasionally, and I don't see a pattern (e.g., specific sender, time of day). I have not turned off the native messaging app's SMS permission because I get a warning, "If you deny this permission, basic features of your device may no longer function as intended." Is this the way to fix it?

### Steps to reproduce
I have no idea how to reproduce the problem.

### Device info

**Device:** LG ThinQ (LM-G710TM) 
**Android version:** 9
**Signal version:** 4.43.8

**Comment by anLGuser** [comment]
Update: I tried turning off SMS access in the native messaging app. Later, I got a notification, did I want to let Messaging send and receive messages. So I turned access back on and received an Alert from the Public Alert and Warning Systems for my area, about a Flash Flood Warning. So this message was intercepted by the native Messaging App rather than going to Signal. As I look through other messages intercepted by the native app, they include two Signal verification code messages. That's ironic, isn't it? Please advise how to fix this problem.

**Comment by fajabird** [comment]
I have kind of similar problem.  On my Android 9 phone sending a quick response SMS to reject a call results in not seeing this in Signal. Messages containing apn settings did also not show up in Signal but instead in Messages after making it the default SMS App.
