### ISSUE TITLE
"The sender is not in your contact list" for "Note to Self"

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#8942]
### Bug description
When the last message in "Note to Self" is removed, "The sender is not in your contact list" is shown. This does not make sense as:
1. You can't block yourself.
1. This is a really obscure way to get a "Me" contact in your contacts.
1. Sharing your profile with yourself doesn't make sense. 

### Steps to reproduce
- Have at least one message in the conversation with yourself.
- Delete all messages in the conversation **from inside of the conversation**.

**Actual result:** "The sender is not in your contact list".
**Expected result:** Empty conversation.

### Screenshot
![](https://user-images.githubusercontent.com/19972511/61731297-d822ef80-ad83-11e9-8e94-5950242791df.png)

### Device info
**Device:** Pixel 3 XL
**Android version:** Q Beta 5
**Signal version:** 4.44.1

**Comment by minnmann** [comment]
I am able to reproduce this on the same Signal version. 

Funnily enough, if you block yourself and send a message from a linked device, it is still delivered and shown on the phone.

**Comment by u32i64** [comment]
Ah, there is no "You can't block yourself." string in Signal Android.

Both in Android and iOS the Note to Self conversation settings don't even show an option to block. However, there is another place to block - from the Signal settings - and Signal iOS prevents you from "blocking" yourself using the mentioned string. The Android version does not have the possibility to block from settings afaik and so doesn't need the string, as long as this issue is fixed.

However even with this issue fixed I think it still makes sense to add a check (and corresponding string for the error message) so that you can't block yourself in Android just in case something like this issue happens, since as mentioned by @minnmann blocking doesn't even work properly in this case.

**Comment by u32i64** [comment]
I've noticed this prompt also appearing when starting a new conversation with yourself, however I don't know how to exactly reproduce that. But special-casing dialog with self should be enough to prevent it from appearing in any way, I think.

**Comment by u32i64** [comment]
Closing because this is a legacy prompt superseded by Message Requests, and they shouldn't appear for Note to Self as they're automatically considered "accepted" for Note to Self (see line 270):

https://github.com/signalapp/Signal-Android/blob/2be306867539ab1526f0e49d1aa7bd61e783d23f/app/src/main/java/org/thoughtcrime/securesms/recipients/RecipientUtil.java#L268-L278
