### ISSUE TITLE
Crash when viewing any photo

### ISSUE THREAD

**Issue by Noah-Huppert** [signalapp/Signal-Android#8943]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal either:

- Exits conversation screen and returns to conversations list
- Crashes and exists app completely

It usually does the later.

### Steps to reproduce
1. Send image to yourself
2. Wait to receive and download image
3. Click image in conversation
4. Signal crashes

**Actual result:** When I click on an image signal crashes
**Expected result:** Opens image in larger form so I could view image details

### Device info
**Device:** Pixel 2
**Android version:** 9
**Android build number:** PQ3A.190705.001
**Signal version:** 4.44.0

### Link to debug log
https://debuglogs.org/6d0044abb6586b3080b0ddc0fb05d401bd6c8d4428ada969d261dac467db66d4

**Comment by minnmann** [comment]
This issue should be resolved in 4.44.1. 

See also https://github.com/signalapp/Signal-Android/issues/8940 and https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-44-release/8572/10.
