### ISSUE TITLE
Signal Support Non-Existent

### ISSUE THREAD

**Issue by SoulSnatchr** [signalapp/Signal-Android#8945]
I have two issues:
1) Why would you possibly have an error message that says "Some issues need your attention" but not say what the issues are? Useless!
2) Why the hell isn't there an option to contact support on the Signal website? There's a section that says (misleadingly) "Support" but its NOT. It is support articles which, again, is NOT support. Useless!
Threema has support. You can contact Threema.
Yhreema is also funded by a small one timev fee for it's app by it's customers. Signal is predominantly funded by the US government who already spies on it's citizens and has good ol' Donald Trump leading the way which is disconcerting at best. So how secure and reliable can it really be? Then again, it's not like the US Government or companies they have funded completely lie to and deceive it's citizens or anything...

**Comment by greyson-signal** [comment]
Hi there, you can reach out to support@signal.org for assistance. There is also an option to "Submit a request" at the bottom of every article on the support site. Also, for more details of how we're funded, see the blog post introducing the [Signal Foundation](https://signal.org/blog/signal-foundation/). Thanks!
