### ISSUE TITLE
Feature request: Add an option for 'Delayed Sending'

### ISSUE THREAD

**Issue by siesing** [signalapp/Signal-Android#895]
I would like a 'Delayed Sending' option to be added to the settings. This is very useful in case you left an embarrassing typo, forgot something important or if you just change your mind and don't want to send the message.

Both Chomp SMS and Handcent SMS have this excellent feature.

Delay options from 1 to 5 seconds should be enough.

Thanks!

**Comment by bmintz** [comment]
:+1:

**Comment by moxie0** [comment]
@bmintz Please only post comments in issues if you have new information to add.

**Comment by bmintz** [comment]
@moxie0 Would a subscription be equivalent?

**Comment by xavihernandez** [comment]
Hi,
Nothing new from this 2 years later?

Thanks for this app!

**Comment by 2-4601** [comment]
@xavihernandez Just three comments above
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by xavihernandez** [comment]
Well it was just a question, plus you also added a comment to say nothing but "stop asking" while issue has been opened 2 years ago... yep I sais it 2 years ago, and there was nothing said on it.
Anyways you don't seem to have any clue on it. 
You could have told me that standard contributors has not planned to add this feature. You could have told me that feature is in development. You could have tell me lots of things, but you just told me "don't bump" which is a really poor answer.

**Comment by cneill** [comment]
This also has opsec benefits. Delaying and then stopping a text from sending could help with several security/privacy-related situations like:
- someone stealing your phone and immediately sending an embarrassing text (assuming you can get it back fast enough)
- convincingly fooling someone into thinking you've sent them a text message (and thus your number), and getting away from the person, leaving them thinking it was a network error
- removing sensitive information from copied/pasted text that you couldn't see before hitting send (i.e. if the message was long and hard to scroll through in the editing box)
- accidentally hitting "send" before properly redacting, or phrasing, your message

I'll admit, I'm mostly interested for the "fat-finger fix," but I definitely think this has more than convenience value.

**Comment by trymeouteh** [comment]
I would like this too. I use Textra as my main SMS app just for that reason since I am able to press send and look over my message before it actually sends it. This way if I see a type I can press cancel before it sends and fix my type and press send again.

I think a good way to make this feature work is to be able to set what the delay message timer is in seconds. And when you tap send the send button will turn into a timer and you can press the timer button to cancel it and you can hold the timer button to send it right away.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
