### ISSUE TITLE
Conversation list is redrawn when a read confirmation or status changes rendering the scrollbar without scrolling

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#8953]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in the conversation overview in dark mode, this "problem" is most noticeable. When a send status or read status changes the whole list obviously gets redrawn and the scrollbar is shown and faded out even when not scrolling.

### Steps to reproduce
- Wait in conversation overview until some status (read, received) changes
- Have enough conversations for a scroll bar
- Scroll bar gets redrawn without even scrolling

**Actual result:** 
Scroll bar gets redrawn without user interaction

**Expected result:**
Scroll bar should not get redrawn when not scrolling

### Device info
**Device:** Pixel2 XL
**Android version:** 9.0.0
**Signal version:** 4.43.8

**Comment by alan-signal** [comment]
Please update and verify issue exists on latest Signal.

**Comment by piratenpanda** [comment]
Sorry, typo here as well. 4.43.8

**Comment by piratenpanda** [comment]
This also happens when indicators changed that are in the conversation and not the last one which is shown in the messages overview.
