### ISSUE TITLE
Choose between send sms or signal message

### ISSUE THREAD

**Issue by bloodangel78** [signalapp/Signal-Android#8957]
Hi,

I do not see this feature, say me if i'm wrong.
I have put signal app as default sms application.

But I can not choose between sending an sms or a signal message for my contacts on signal.
I have some contacts that have data only with wifi, so when I know they have not data I want to send them a sms in place of a signal message they can not receive without data.

Do you think it is possible to add an option to choose to send a sms or a signal message?

**Comment by johanw666** [comment]
You have to press the send button long, then you get a choice how to send a message (if the contact also has Signal, otherwise only sms is available).

**Comment by bloodangel78** [comment]
Ok thanks I did not notice this.

Thanks you
