### ISSUE TITLE
Is it possible to integrate it with drupal to send and receive messages

### ISSUE THREAD

**Issue by ugintl** [signalapp/Signal-Android#8964]
I am using drupal 7 cms to create websites. I would like to integrate signal with my drupal site to send and receive messages from the website to user phone. It will be used as a gateway to send notifications and codes.

For example, a user enters mobile number on signup page and receives a code on his cell phone to confirm the number.  There are already modules on drupal which provide mobile number and all the functionality.

I just need something which can take that info from my website to user mobile. I am already using envaya sms app (It is installed on my phone and converts my phone to an sms gateway. Then there is a drupal module which integrates envaya with drupal) and its working, but the problem is that it uses my mobile carrier to send sms to the user and hence incurs cost which is ok if sending to local numbers, but international sms will cost higher and this solution becomes unfeasible.

So, I want something which can use internet to send message to the user.

**Comment by alan-signal** [comment]
This is for reporting issues with the android software only.

Please use the community forum for questions or discussions https://community.signalusers.org/
