### ISSUE TITLE
Choice between signal and non-signal out-going calls

### ISSUE THREAD

**Issue by flavi1** [signalapp/Signal-Android#8965]
Hello.
We can call without signal when contacts doesn't have signal, but we can't if they have.
It should be great if we can choice between signal and non-signal for out-going calls in any time, (by long press call button with the finger to get choice menu... like it's already possible with SMSs and MMSs).
Best regards

**Comment by Tursko** [comment]
Yes, I completely agree. I actually emailed them yesterday about this feature request. 

My friends use the android app and they always mistakenly call me via Signal voice, when they really want to call via the default phone app. Would be extremely nice to have the option between Signal calling & default calling.

**Comment by greyson-signal** [comment]
As noted in our contributing guidelines, Github is for bugs, not feature requests. Please discuss this on [the forum](https://community.signalusers.org/). Thanks!

(FYI if you tap someones avatar in the conversation list, or long-press their avatar at the top of a conversation, you'll be taken to their contact page where you can start an insecure call)
