### ISSUE TITLE
Can't switch between front and back camera

### ISSUE THREAD

**Issue by timatidg** [signalapp/Signal-Android#8966]
In most recent update and one before it, switching camera on Moto g5 plus results in black screen. User must leave media capture, return to message, reenter media capture to take photo with alternate camera.

### Steps to reproduce
- hit photo capture button
- switch cameras

**Actual result:** get black screen; can't take photo with other camera. Can switch back to one from last use and that one works.
**Expected result:** should be able to change between front and rear capture without exiting media capture.

### Device info

**Device:** motorola Moto G (5) Plus (potter)
**Android version:** 8.1.0 (21457, OPSS28.85-17-6)
**Signal version:4.44.7 (5151)

### Link to debug log

https://debuglogs.org/138b3fa00427ad2e8d04ad304b07b062a0cf2a2a4c6e1641f1ea4404ee87e1dd

**Comment by kolbma** [comment]
I can confirm this in **Signal version: 4.47.5** on **Samsung A3 2016**.

On clicking the camera front-back-switch circle button the new camera is not activated.
Screen stays black.
You can switch back to the first camera and this cam works again.
After clicking the shutter button in the black state, you can only use the back button. No cam switching.

If you use the back button in black state. And choose again the photo capture button, this time you have activated the other camera.

**Comment by kolbma** [comment]
A similar problem also exists in video phoning.
Once switching cameras the receiver end only sees black screen. The small picture-in-picture on transmitter side is working.

**Comment by kolbma** [comment]
Works for me now both with: https://github.com/signalapp/Signal-Android/releases/tag/v4.49.10
