### ISSUE TITLE
Conversation list: Contacts/Groups without avatar show wrong color and initials after scrolling

### ISSUE THREAD

**Issue by hwinnemoe** [signalapp/Signal-Android#8967]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After scrolling the conversation list to a position such that a whole new page of conversations is visible, scrolling back up, opening a conversation and returning to the conversation list reveals jumbled colors and initials for non-avatar contacts/groups. They still behave correctly and display the correct contact when tapping them. I also see this issue without scrolling, but I was only able to reproduce it using the following STR.

### Steps to reproduce
- have a number of contacts/groups without avatars long enough to fill your viewport twice
- in the conversation list, scroll down until you have a full new list of conversations
- scroll back up
- open a conversation
- return to the conversation list

**Actual result:** Some of the contacts/groups without an avatar now have the wrong color and initials.
**Expected result:** All contacts/groups without avatars have the correct color and initials.

### Screenshots

Before STR:
![before](https://user-images.githubusercontent.com/42788925/62240256-d89c3580-b3d6-11e9-9dd2-ba234aa46c1b.png)
----------------------------------------
After STR:
![after](https://user-images.githubusercontent.com/42788925/62240288-ee115f80-b3d6-11e9-9f55-90542496448e.png)

### Device info

**Device:** Sony Xperia Z2
**Android version:** 6.0.1
**Signal version:** 4.44.7

### Link to debug log
https://debuglogs.org/bc2ce0b77a0e4ef36e12a75e734bd011e487b74f241249833501520577a234bb

**Comment by mueller-ma** [comment]
Related issue: #8916?
