### ISSUE TITLE
Landscape Compose/Edit window reverted to "old" interface

### ISSUE THREAD

**Issue by HAndroidRage** [signalapp/Signal-Android#8968]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Composing a message/reply in Landscape mode has reverted to pre May 11, 2019 behavior (big, white box for composing messages).  I am not sure when the issue first started.  I thought someone else would report it and it would go away. Possibly related to #5040, which was closed by issue # creator, but did not reference other issue # for comparison.

### Steps to reproduce
- Open Signal App on your phone in either portrait or landscape orientation 
- Pick any conversation
- Touch the compose/edit space to make the touchscreen keyboard open
- If phone is already in landscape orientation, you'll see the big, white box
- If phone is in portrait orientation, rotate phone to landscape and you'll see the big, white box

**Actual result:** You have the big, white box, compose/edit area instead of the nice, small compose/edit area where you can still see your prior messages in that conversation
**Expected result:** You should see the nice, small compose/edit area where you can still see your prior messages and a small space to compose/edit your new message in that conversation

### Screenshots

![Inkedsignal-attachment-2019-08-01-123012_LI](https://user-images.githubusercontent.com/53577831/62316451-7c342700-b465-11e9-9e06-218633884e5f.jpg)
![signal-attachment-2019-08-01-140329](https://user-images.githubusercontent.com/53577831/62316463-822a0800-b465-11e9-9cf3-761bd8cb7f0b.png)

### Device info

**Device:** Google/LG Nexus 4
**Android version:** 8.1 (LineageOS)
**Signal version:** 4.44.7

**Comment by coltonJ2468** [comment]
It looks like your keyboard is going into a full screen editor while in landscape. If it does something similar when using the keyboard in landscape elsewhere you might just need to change a setting.

**Comment by HAndroidRage** [comment]
That was the answer, coltonJ2468!!!  Thank you!

**Comment by UserX404** [comment]
> 
> 
> It looks like your keyboard is going into a full screen editor while in landscape. If it does something similar when using the keyboard in landscape elsewhere you might just need to change a setting.

which setting??
I have the same problem with my xperia xz2c

**Comment by u32i64** [comment]
@UserX404 AFAIK you have to use the [Disable Fullscreen Keyboard](https://play.google.com/store/apps/details?id=com.shubhangrathore.xposed.disablefullscreenkeyboard) Xposed module unless your keyboard has an option to disable something like "Fullscreen keyboard in landscape".
