### ISSUE TITLE
Please, more themes, more theme color options, more config for colors.

### ISSUE THREAD

**Issue by jult** [signalapp/Signal-Android#8970]
Only Light or Dark. Really? Why?

_Originally posted by @FaizKhan5 in https://github.com/signalapp/Signal-Android/issues/6577#issuecomment-328271918_

@jult Post a screenshot or close this issue please :)

I don't see what good that does. What we need and would like to have is user config OPTIONS. Give us our own theme colors, please. Not some dictator-view of what our message-pane should look like. And honestly, in 2019, for android, how hard can this be?
Frankly, I was flabbergasted it wasn't in there in the first place. Can't even pick a contact's color, that's just weird.

**Comment by lauritzt** [comment]
You can pick a contact's color: Open the conversation, tap their name, and tap 'Color' under Chat settings.

**Comment by u32i64** [comment]
From [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
> 
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). [...]

Also note:

> ### Development Ideology
> Truths which we believe to be self-evident:
>
> - **The answer is not more options.** If you feel compelled to add a preference that's exposed to the user, it's very possible you've made a wrong turn somewhere.
> [...]
