### ISSUE TITLE
Camera exposure

### ISSUE THREAD

**Issue by Da0012** [signalapp/Signal-Android#8973]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

In the two last versions of Signal the camera does not adjust the exposure correctly, many times i need to use the smartphone camera.

### Screenshots
Camera App
![signal-attachment-2019-08-03-204417_002](https://user-images.githubusercontent.com/27793171/62418543-cfa6a080-b630-11e9-9e4b-8e732117b05e.jpeg)
Camera of Signal

![signal-attachment-2019-08-03-204417_001](https://user-images.githubusercontent.com/27793171/62418548-0c729780-b631-11e9-805f-dffc4c963f56.jpeg)

### Device info
**Device:** Asus Zenfone 4 max
**Android version:** 8.1
**Signal version:** 4.44.7

**Comment by nuchi** [comment]
Same.
**Device:** Moto G3
**Android version:** 6.0
**Signal version:** 4.44.7

**Comment by nuchi** [comment]
I looked around at this, and I think it might be related to [dark](https://stackoverflow.com/questions/38493000/camera2basic-app-has-very-dark-preview-in-android-6-0-lgg3) [previews](https://stackoverflow.com/questions/51617785/camera-preview-is-dark-using-camera2) with some cameras using the Camera2 API. The answers suggest explicitly setting `CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE` to be the widest range (ie largest difference `upper - lower`) returned by `characteristics.get(CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES)`. (Also see [this link](https://nickcullen.net/blog/flutter/camera-plugin-dark-preview-fix/).)

With the recent Signal switch to the CameraX api, it seems [this file](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/mediasend/camerax/CameraXModule.java) is the natural place for the changes.

Some digging into the CameraX api (and source) leads me to think that the way to do it is to initialize `mImageCaptureConfigBuilder` (ditto the preview config) with [`setDefaultCaptureConfig`](https://github.com/aosp-mirror/platform_frameworks_support/blob/b9cd83371e928380610719dfbf97c87c58e80916/camera/camera-core/src/main/java/androidx/camera/core/ImageCaptureConfig.java#L858), and that the `CaptureConfig` passed to that should be created with [`setImplementationOptions`](https://github.com/aosp-mirror/platform_frameworks_support/blob/b9cd83371e928380610719dfbf97c87c58e80916/camera/camera-core/src/main/java/androidx/camera/core/CaptureConfig.java#L252) which finally is created by a process [like this one](https://github.com/aosp-mirror/platform_frameworks_support/blob/b9cd83371e928380610719dfbf97c87c58e80916/camera/camera-camera2/src/main/java/androidx/camera/camera2/impl/Camera2CameraControl.java#L541-L543).

I haven't written any code for Android (nor spent much time in Java intricacies) so I'm a little worried about whether `@RestrictTo(Scope.LIBRARY_GROUP)` would prevent one from using `setDefaultCaptureConfig`? In any case I hope someone might be willing to take a closer look at this. This all seems pretty daunting to me but to someone who has just spent a lot of time digging into the CameraX api maybe it all looks a bit simpler.

**Comment by anspectrum** [comment]
Same issue with me. I just wonder how come it was working fine earlier but after updating App it broke this function.

**Device:** Xiaomi Redmi Note4
**Android version:** 7.0
**Signal version:** 4.47.5

**Comment by greyson-signal** [comment]
We'll track exposure problems here: #9108

**Comment by awsms** [comment]
> We'll track exposure problems here: [#9108](https://github.com/signalapp/Signal-Android/issues/9108)

Mind re-opening #9108 then? As this is still an issue.
