### ISSUE TITLE
Signal search crashes after typing `AND`, `OR`, or `NOT`

### ISSUE THREAD

**Issue by aaronjanse** [signalapp/Signal-Android#8975]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The keywords `AND`, `OR`, and `NOT` crash Signal search.

### Steps to reproduce
- open search bar (either global search or chat search)
- type in one of the following:
  - `AND`
  - `OR`
  - `NOT`

**Actual result:** Signal crashes, throwing what seems to be an SQL error
**Expected result:** The search terms are interpreted literally, without crashing.

### Device info

**Device:** Samsung S9
**Android version:** 9
**Signal version:** 4.45.2

### Link to debug log
https://debuglogs.org/a224cc04dd81a55b36bd243d0622977c4f7fbeceaf26727ba89e2d5fd9a3d6b1

---

SQL injection sounds like a security problem, but it doesn't sound [urgent and sensitive](https://support.signal.org/hc/en-us/articles/360007320791-How-can-I-report-a-security-vulnerability-) in this scenario. I hope I reported this to the right place.

The following code is probably relevant:

https://github.com/signalapp/Signal-Android/blob/af55cb0c03a77c843c7b02e73ef786964f3fd851/src/org/thoughtcrime/securesms/search/SearchRepository.java#L155-L172

**Comment by UserX404** [comment]
Can reproduce this issue.
Android 9
4.44.7

**Comment by aaronjanse** [comment]
> Can reproduce this issue.
Android 9
4.44.7

Me? Yes, and I've reproduced it on several of my friends' phones

**Comment by aaronjanse** [comment]
Hmmm, does downloading 4.44.7 mean that I'd have to build the APK myself?

**Comment by Da0012** [comment]
Same
Android 8.1
4.45.2
