### ISSUE TITLE
Wrong Contact in Header

### ISSUE THREAD

**Issue by ulrichsc** [signalapp/Signal-Android#8976]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Chat opens with wrong contact in header if provoked. Looks like a race condition.

### Steps to reproduce
- start Signal
- tap on chat 1, directly afterwards (before chat 1 opens) tap multiple times on chat 2
- if not successful repeat the previous step

**Actual result:** Chat 2 with header of chat 1
**Expected result:** Chat 1 with header of Chat 1

### Device info

**Device:** Motorola Moto G4
**Android version:** 8.1.0
**Signal version:** 4.44.7

### Link to debug log
https://debuglogs.org/e77a2364efc6fa78981b7ca1ab871500543e8598501a6aceef78a6105e640bf4

**Comment by alan-signal** [comment]
Confirmed, thanks

**Comment by greyson-signal** [comment]
I think I fixed this is a different bug I fixed. Let me know if you can still reproduce it.
