### ISSUE TITLE
Option to specify path/folder where media is saved

### ISSUE THREAD

**Issue by schneekluth** [signalapp/Signal-Android#8979]
Please provide an option to specify a path where all saved media from Signal app is stored. Currently all media files are saved to Pictures folder on Android. I'd love to have a dedicated folder e.g. Pictures/Signal/.

**Comment by u32i64** [comment]
This is not a bug report, but a feature request/discussion topic.

Quoting [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.
