### ISSUE TITLE
Incoming call buttons flicker and overlap

### ISSUE THREAD

**Issue by Trojgarb** [signalapp/Signal-Android#8980]
![signal flickering](https://user-images.githubusercontent.com/54016997/62851746-6b967300-bce7-11e9-94e3-fd6782916fb2.gif)

### Bug description
Buttons on Signal's incoming call screen flicker with high frequency (So high that it is almost impossible to diferrentiate theirs colors). Buttons descriptions flicker too. Buttons also overlap (similarly to the issue #7211)

### Steps to reproduce
- Being called on Signal Android

**Actual result:** It's difficult to receive/reject call, however it's feasible despite strange looking screen
**Expected result:** The receive/reject buttons and their captions should have stable visibility without flickering and overlapping.

### Device info
**Device:** Motorola Moto X Force, Wiko View
**Android version:** 7.0, 7.1.2 (respectively)
**Signal version:** 4.45.2 and older (since beginning of using Signal in 2018)

**Comment by alan-signal** [comment]
Thanks for the report and the gif, very helpful.

It's just one button jumping around where it should be animating instead. That is why there is no color difference and they appear to overlap.

**Comment by chrihu** [comment]
https://github.com/signalapp/Signal-Android/issues/7318

**Comment by alan-signal** [comment]
Thanks @chrihu .

@Trojgarb Have you also modified the animation scales inside developer options?

**Comment by Trojgarb** [comment]
Yes, I have animations disabled in developer options.

**Comment by alan-signal** [comment]
Developer options aren't something we're going to cater to.

However, if the same problem exists when `Accessibility->Remove animations` is on, that would be a different story. It doesn't exhibit a problem for me on Android 9, but I would be interested to know what happens on Android 7.

**Comment by chrihu** [comment]
> `Accessibility->Remove animations`

That's an Android 9+ feature.

**Comment by mueller-ma** [comment]
Many animations are disabled as well if battery saver is enabled.

**Comment by Sgn-32** [comment]
Is this solved for you with the new calling UI introduced in 4.60?
