### ISSUE TITLE
Video compression changing aspect ratio

### ISSUE THREAD

**Issue by wtangofoxtrot** [signalapp/Signal-Android#8982]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending videos with a 1920x1080 (16:9) resolution the recipients receive a 960 × 720 video (4:3) that is distorted from the original

### Steps to reproduce
- share a 1920x1080 video with a group/single user/notes to self
- the video in question was taken from sony alpha a6000 as is saved as a 1920x1080 h.264 encoded mp4
- to repo i shared the video with myself (notes to self) or to a user or group
- issue does not happen when sharing using the desktop apps

**Actual result:** The video in the chat has the wrong aspect ratio
**Expected result:** the aspect ratio is not tampered with

### Reproducable
100% reproducible when sharing videos from mobile

### Screenshots of file share for the same video
video shared using desktop app - aspect ratio is preserved:
![Screenshot_20190812-162033](https://user-images.githubusercontent.com/15003248/62904991-5d634980-bd1d-11e9-836f-9823e78fa9d2.jpg)

video then shared using android app - aspect ratio is changed:
![Screenshot_20190812-162042](https://user-images.githubusercontent.com/15003248/62904997-6227fd80-bd1d-11e9-967c-80c066a8e84e.jpg)

### Device info

**Device:** One Plus 6T
**Android version:** 9
**Signal version:** 4.45.2

### Link to debug log
https://debuglogs.org/35e7d3bfd0cb4e49f06ca8d0da236df60d6b28469e0b568214fe588c72c0221f

**Comment by alan-signal** [comment]
Would you please record a new, short video, upload the original to https://send.firefox.com and then email the link to me alan@signal.org

**Comment by wtangofoxtrot** [comment]
Attached a new sample video here https://send.firefox.com/download/e9498ba802a1b00f/#sM1renyGVibhinVNu-3PSQ

**Comment by alan-signal** [comment]
Somebody else has downloaded it (they can only be downloaded once), that's why I asked that you email the link :)

**Comment by wtangofoxtrot** [comment]
Bugher sorry, here's the link
https://send.firefox.com/download/185955eaebb85d8a/#nWk9HTXx89y6kRSZo_CkMQ

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by wtangofoxtrot** [comment]
@alan-signal Did you receive the video ?

**Comment by alan-signal** [comment]
Yes thank you and we have a fix which will come in the next version.
