### ISSUE TITLE
Camera lag - inApp record (sometimes) 

### ISSUE THREAD

**Issue by peterpanondrugs** [signalapp/Signal-Android#8983]
- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Taking a picture from the signal app gives back a lagging camera. 

### Steps to reproduce
- take picture from inside signal

**Actual result:** camera laggs when taking a picture. You press the button, the picture freezes for 1s and suddenly 1-2s later the picture freezes again with another image.  (because you moved the camera) 
**Expected result:** button press >> Picture immediately taken. 

### Device info

**Device:** Samsung S7
**Android version:** Android 8
**Signal version:** 4.45.2

### Link to debug log
https://debuglogs.org/85adf29c1722ec33a4f7b890c0d97f9b819f9afbfaaa6a0990e87496d478d38f

**Comment by greyson-signal** [comment]
So looking at your logs, it's the camera capture itself, not any of the processing that is taking extra time. To the best of my knowledge, we can't do much about that. We're using the API's provided to us by the system, and we're already using "minimum latency capture mode" for your device model. Maybe there will be improvements to the CameraX library we use or something, but I don't think there's much we can do ourselves.

```java
2019-08-13 09:42:14.942 MESZ D CameraXFragment: [Capture] captured: 2020  transformed: 187  total: 2207
```
