### ISSUE TITLE
Wrong phone number of Signal contact when creating group

### ISSUE THREAD

**Issue by AaronM04** [signalapp/Signal-Android#8985]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When creating a new group with a Signal user who is also in my contacts, if I add them by searching in the text field on the `New group` screen, their number is added as `+13xxxyyyyyyy` where xxx is the area code and yyyyyyy is the rest of the phone number (country code is +1 in all these examples). This is the wrong number! Also only the number shows up, not their name or profile photo. However, if I add them from the `(+)` button to the right of the text field, the number is correct and their name and profile photo show up.

This has caused me to send messages to a group that doesn't actually include all the recipients it should have.

### Steps to reproduce
- touch ... button on upper right of main signal screen
- touch `New group`
- leave the group name blank
- touch the text field labeled `Add members`
- type enough of the name of your contact (who is in Signal) for it to show up above or below
- tap the selected contact

**Actual result:** a number of the form `+13xxxyyyyyyy` shows up below, without a profile picture or name.
**Expected result:** the contact's correct number `+1xxxyyyyyyy` accompanied with their profile picture and name.

### Screenshots
TODO 

### Device info
**Device:** One Plus 3T
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 4.45.2

### Link to debug log
Not sure if I need this.

**Comment by Araevin** [comment]
I have also experienced this issue and have been able to reproduce it.
Specifically, this happens in the case where there is a '<' as part of the contact name. Any numbers or letters after the angle bracket are prepended to the number added to the group.

As is probably the most common case, "<3" causes a 3 to appear at the front of the number. Letters will show up as well.

**To reproduce:**
- Create a contact on your phone with a left angle bracket in the name and give it a phone number. "TestContact<4ABC" for example.
- Open signal
- Follow the rest of the reproduction steps listed by @AaronM04 

This has been my experience with the issue, @AaronM04, to make sure it is the same issue - did your contact name contain a left angle bracket?

**Comment by AaronM04** [comment]
@Araevin  Yes, the contact in question had `<3`.
