### ISSUE TITLE
backup doesn't backup to external storage

### ISSUE THREAD

**Issue by rubiksdot** [signalapp/Signal-Android#8987]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal does not backup to external storage even though the option says it will

### Steps to reproduce
- enable backups
- wait for it to do the first backup
- check with file manage where the backup happened

**Actual result:** 
Find backup on internal storage in Signal/Backups.

**Expected result:** 
Backup found on external storage as config option indicates.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.45.2

**Comment by greyson-signal** [comment]
We do not do backups on external SD cards, mostly because there's no good way (without some pretty hilariously difficult user flows) to write files to external SD cards that aren't deleted when you uninstall the app. Sorry about that. Thanks!

**Comment by wavexx** [comment]
This is a big problem for me currently. I need to move the storage to a different phone, but I don't have enough internal storage to perform the backup. And no, since the vast majority of space is taken by signal itself, I cannot free more space.

Can I just copy the Apps/Signal directory to the new phone?
