### ISSUE TITLE
Receiving lots of badly encrypted messages in a conversation

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#8989]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A contect of mine was for some time in an area with bad internet connection. We tried to exchange messages, but didn't work reliable. Now I'm receiving lots (>10 on Android, >300 on Desktop) of "badly encrypted messages" one after another. Not every faulty message corresponds to a real message which was (tried) to send. They just kept pouring in. Resetting the encryption didn't solve the problem.

### Steps to reproduce
Unfortunately, I don't know how to reproduce. Maybe having a bad internet connection?
**Actual result:** lots of "badly encrypted messages"
**Expected result:** After resetting the encryption there shouldn't be a problem anymore

### Device info
**Device:** Nokia (HMD Global) 6.1
**Android version:** 9
**Signal version:** 4.45.2

### Linked Desktop
**Device:** Windows 10 (64bit)
**Signal version:** 1.26.2

### Link to debug log
Android: [Android](https://debuglogs.org/943b4c4e837acb04738f87adf43f4d7d1f9d313c528e0538fd9bd9026518896e)
Desktop: [Desktop](https://debuglogs.org/b830120036572a7fe0a48e0b00c3c0b1c06a47f75cbdc1587ef7835eea7facd8)

Correspondig Android bug report: [https://github.com/signalapp/Signal-Desktop/issues/3520](https://github.com/signalapp/Signal-Desktop/issues/3520)

**Comment by tuxayo** [comment]
It's this issue: https://github.com/signalapp/Signal-Desktop/issues/2806
