### ISSUE TITLE
how to logout and switch to another phone number?

### ISSUE THREAD

**Issue by maincui** [signalapp/Signal-Android#8990]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sorry maybe it's a feature request. I have searched open/closed issues and support topics, but found no clue to how to logout and switch to another phone number. If it's by design, may I know why?

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by alan-signal** [comment]
Please use the community forum https://community.signalusers.org/ or email support@signal.org
