### ISSUE TITLE
Links only open in the home page of an app

### ISSUE THREAD

**Issue by thaman10** [signalapp/Signal-Android#8994]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A link pasted into a Signal conversation appears correct. However if the link is for a page that has an app already installed on the destination device, only the home page of the app is opened - not the page that was linked.

### Steps to reproduce
- Click the share button from an app (e.g. BBC Sport app) to copy a full page link
- e.g. https://www.bbc.com/sport/golf/49398360
- Paste into a Signal conversation - the link appears in full
- Send to a recipient.

**Actual result:** 
- If the recipient has the app installed (e.g. BBC Sport), only the home page of the app will open.
- Not the page that was linked directly.

**Expected result:**
- The page that was linked directly should open, even insde the app.
- e.g. Whatsapp works ok, so it does not seem an issue with the app.

### Device info
**Device:** Apple iPhone XR
**IOS version:** 12.3.1
**Signal version:** 2.41.1.2

### Link to debug log
https://debuglogs.org/f311f2e69c7cd4212ea446e242368b94f36c833fa590957fbc1e381e9e4a5775.zip

**Comment by charlesmchen-signal** [comment]
https://github.com/signalapp/Signal-iOS/issues/4249
