### ISSUE TITLE
 Registration lock PIN reminder has black text in dark theme

### ISSUE THREAD

**Issue by aibaraiduas** [signalapp/Signal-Android#8995]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The registration lock reminder has the words "Enter PIN" in the input field before the user begins to put their PIN in. When using the dark theme, it is extremely hard to see the words (especially when screen brightness is low), because the words are written in black text. 

Note that the numbers the user inputs is shown in white, I believe, so that's fine, as is the rest of the surrounding text.

### Steps to reproduce
- Set the theme to dark.
- Set up a registration lock.
- Wait for the registration lock PIN reminder to appear.

**Actual result:** 
The words "Enter PIN" in the input field are black and therefore hard to read.

**Expected result:** 
The words "Enter PIN" in the input field should be easy to read (probably match the rest of the instructional text); the underlining bar of the input field should (probably) also be that color.

### Screenshots
![Screenshot_20190822-181950](https://user-images.githubusercontent.com/5825551/63554281-0d4d6980-c50b-11e9-97df-4094dfe98821.png)

### Device info

**Device:** Google Pixel 3
**Android version:** 9
**Signal version:** 4.45.2

### Link to debug log
Didn't get one, but could get one next time if necessary.

**Comment by jdepypere** [comment]
Related issue that fixed the numbers that were also in a dark color: https://github.com/signalapp/Signal-Android/issues/7509
