### ISSUE TITLE
Signal crashes on opening

### ISSUE THREAD

**Issue by signalme** [signalapp/Signal-Android#8997]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open the app, it immediately displays a dialog box that it has stopped working. In the background of the screen I can see an unlock PIN screen even though I have never used a PIN with this installation, which seems odd. Was working fine a few days before. I am assuming there has been some sort of database corruption and my messages are lost? Do I need to uninstall and reinstall to fix? Just checking if there's anything that can be done before nuking it.
The issue that seems most similar to mine when searching was [8781](https://github.com/signalapp/Signal-Android/issues/8781).

### Steps to reproduce
- Open Signal app
- crash is immediate
- persists after device reboot

**Actual result:** Cannot access app at all
**Expected result:** App should open as usual to display the list of conversations

### Screenshots

![screencap](https://user-images.githubusercontent.com/54472925/63645192-a2e12880-c6c6-11e9-8183-b839c363f5e2.png)

### Device info

**Device:** HTC One M8
**Android version:** 6.0.0
**Signal version:** 4.45.2

### Link to debug log

Cannot capture log via signal, adb logcat output below. Hopefully I have done this correctly, never used logcat before:
````
08-24 22:27:41.068  5737  5761 E AndroidRuntime: FATAL EXCEPTION: signal-JobManager
08-24 22:27:41.068  5737  5761 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5737
08-24 22:27:41.068  5737  5761 E AndroidRuntime: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:44)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.init(JobController.java:66)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:59)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-24 22:27:41.068  5737  5761 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
````

**Comment by johanw666** [comment]
Sounds like a corrupt database.

**Comment by signalme** [comment]
Thanks johanw666, that was the impression I got also. Anything that can be done to fix it, or is starting from scratch my only option?

**Comment by johanw666** [comment]
Do you have a recent backup? Otherwise you might try to check if the database can be read with external tools on Windows or Linux, but that requires access to the database key.

To obtain that key with a crashing Signal you would need to install a custom adapted Signal over the current one, one that dumps the key. Such a version could be made, but to install it without uninstalling the current version (and thereby deleting all data) requires either root either Xposed / Xinstaller, or root + Lucky Patcher with the "Disable signature verification in the package manager" patch activated. And then you'd still need some luck to be able to recover the data.

It is a lot of hacking with an uncertain outcome. Depending on how valuable your massages are it might be worth a try or not, I can not judge that.

**Comment by signalme** [comment]
Thanks for the detailed response. It looks like rescuing the database may be beyond my abilities. I have a year-old backup so all is not lost, but I wish I knew what caused it. Maybe just an old phone...

Going to consider this closed. Thanks.
