### ISSUE TITLE
Video call own camera

### ISSUE THREAD

**Issue by rissilver** [signalapp/Signal-Android#9004]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In video call own camera is cube and is not real form how other person sees it.

### Device info

**Device:** Manufacturer :** Xiaomi redmi note 4
**Android version:** 8.1.0
**Signal version:** 4.46.2

**Comment by alan-signal** [comment]
cube?

**Comment by pabl0** [comment]
Square. So the framing/aspect ratio  you see on your local device is different the other party sees on his/her screen.

**Comment by rissilver** [comment]
Better said, thanks

**Comment by rainerzufall** [comment]
duplicate of: https://github.com/signalapp/Signal-Android/issues/8615

**Comment by greyson-signal** [comment]
Closing as dupe
