### ISSUE TITLE
[FR] Ability to lock Signal whilst still able to see text notification previews

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [signalapp/Signal-Android#9006]
Would be nice to be able to lock Signal, but have the option to still show the name and message preview in notifications of the person texting you.

I know it seems contradictory to want to lock the app, despite being able to see new messages anyways, but the reasons for this is:

1. It gives the option for people who want it, if you don't want previews you just don't enable the option.

2. You can keep ALL your messages secured behind the pin, without losing complete convenience of being able to see new previews (A good middle between convenience and security/privacy)

**Comment by u32i64** [comment]
Per [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) feature requests should be discussed on the [forum](https://community.signalusers.org/c/feature-requests) instead:

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.
