### ISSUE TITLE
Pixel USB-C earbuds button not answering/ending Signal calls

### ISSUE THREAD

**Issue by urbantrout** [signalapp/Signal-Android#9008]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the Pixel USB-C earbuds and an incoming Signal call rings, pressing the multifunction button on the earbuds does not answer the Signal call. Nor does a button press end an active Signal call.

This issue might be related to #7679 but with USB-C instead of Bluetooth.

### Steps to reproduce
- Use Pixel USB-C earbuds with your phone
- Receive a Signal call
- Click the middle button of the Pixel USB-C earbuds

**Actual result:** Nothing happens
**Expected result:** Call should be answered

### Device info

**Device:** Google Pixel 2 XL with Pixel USB-C earbuds
**Android version:** 10 QPP6.190730.005
**Signal version:** 4.46.2

**Comment by Burathar** [comment]
I have the same issue (on a pixel 3a), but with 3.5mm jack headphones. Instead of ending a call, the button turns on/of my google play music.

**Comment by herbig** [comment]
@urbantrout @Burathar is this still an issue?

**Comment by Burathar** [comment]
@herbig Yes, I just tried it out, and (using 3.5mm jack apple earpods, and the pixel 3a) pushing the central button still starts playing music instead of stopping the call

**Comment by sellth** [comment]
Well, it still annoys me regularly when receiving Signal calls while I'm on a bike. My earbuds can accept normal phone calls, but not the Signal variant. Maybe related: #9727

**Comment by alex-signal** [comment]
This *might* be a result of us not using the Call service google has for API 23 (24?) +.

**Comment by sellth** [comment]
If you mean Android's telecom framework, it would appear so. From what I gathered via Google, Android passes these earpiece signals only to things it considers true "calls" i.e. that use the telecom API. Signal presents itself as a media player to the OS.

This topic tries to collect all of the bugs related: https://community.signalusers.org/t/implement-android-telecom-api-for-calls/41280

**Comment by breversa** [comment]
This problem is not limited to USB-C headphones: I have 3,5mm Marshall Mode EQ (https://www.marshallheadphones.com/fr/fr/mode-eq.html) headphones whose button does neither work for answering incoming calls nor hanging up.
