### ISSUE TITLE
Camera preview / viewport looks stretched

### ISSUE THREAD

**Issue by kepler2** [signalapp/Signal-Android#9016]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The camera preview is stretched (diformed) in both Portrait and Landscape orienation.

### Steps to reproduce
- Launch the Signal App (4.46.2)
- Tap the Camera icon
- See the preview screen in Portrait / Landscape orientation.

**Actual result:** The camera preview is not respecting the proportions and the preview is diformed. Please see the attachments.

In Portrait the preview is stretched.
In Landscape the preview is tight.

**Expected result:** The preview should look ok.

### Screenshots
The preview looks stretched
![Screenshot_2019-08-07-13-46-06](https://user-images.githubusercontent.com/18610924/64167798-d18f9980-ce52-11e9-84c1-00f0b4ee3e98.png)

The photo looks ok after taking it:
![Screenshot_2019-08-07-13-48-11](https://user-images.githubusercontent.com/18610924/64167820-dfddb580-ce52-11e9-86ec-ca3aee392dbd.png)

### Device info

**Device:** HTC One M7
**Android version:** 5.0.2
**Signal version:** 4.46.2

**Comment by kepler2** [comment]
Hello.

Issue still occurs in the latest version: **4.47.6**

**Comment by nicolaus-hee** [comment]
Still in 5.0.8 but only in landscape mode. Maybe related to #10235 ?

**Comment by fabiannagel** [comment]
Unfortunately still relevant in 5.3.71
