### ISSUE TITLE
Signal can't be updated if the persistent "Background connection enabled" notification is hidden.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [signalapp/Signal-Android#9018]
Signal Android installed from signal.org provided apk on AOSP with no Google Play Services.

I saw a message that Signal would be disabled, because I didn't update it for a long time, but I wasn't prompted to update. This is due to the fact that the update prompts are the same notification type as the persistent "Background connection enabled" notification and I have hidden the persistent notification due to it being an annoyance. I consider this a standard behavior any user will do, especially that the OS encourages this (swipe the persistent notification and you'll see a prompt to hide it). There's no other way to update other than through the notification, the message telling me about Signal about to be disabled due to no updating it doesn't offer me an option to update it nor there is any option to do this in Signal settings.

Possible workarounds:
1. Make the new update notification a different notification type than the persistent notification.
2. Notify the user of new updates inside the app itself in addition to the standard notification.
3. Give the user an option to update through the settings' option and in the message telling the user about Signal about to be disabled.
4. Perform updates automatically.
5. Create F-Droid repository.

**Comment by greyson-signal** [comment]
What version of Android are you running? The app update notifications are in a separate notification channel from the persistent notification used to keep the websocket open. Did you somehow disable multiple channels? Or are you running pre-Android-8/Oreo?

**Comment by gerg5c42g542g2c54g52c** [comment]
@greyson-signal I'm running AOSP 9, it's a buggy build, but I can't remember a single time when I didn't get some notification, notifications don't seem buggy at all.

The only notification type that was disabled is "Other".

I see what you're talking about, there's a notification type "App updates". Was it introduced recently (I got that Signal is about to be disabled in 6 days notification about a week ago, so I didn't update for whatever the period of time that triggers this is)? If not, then that's really weird because I wouldn't disable that nor did I disable anything other than "Other". Unless Signal team didn't ship updates for a while and that caused the Signal is about to be disabled warning, it could be a bug. I can't remember the last time I had an update notification before this, it could be a month or even a few, but I remember updating Signal in past, at this point though I can't be certain if I did that also after disabling "Other" notifications.

**Comment by greyson-signal** [comment]
There was an issue with the versioning of our web apk builds where users weren't getting the update prompts in general (see #8936). Could that have been the issue? Closing and restarting the app would force an update check -- that might have been what happened?

> I see what you're talking about, there's a notification type "App updates". Was it introduced recently

Nope, always been there (since notification channels existed).

**Comment by gerg5c42g542g2c54g52c** [comment]
It's possible, but note that I regularly restart my phone (sometimes daily, sometimes maybe once a week) and usually will open Signal afterwards to make it receive notifications (not sure if that's even needed), I don't believe I didn't restart it for a long time. But from what I see the 'closing and restarting the app' workaround would only work if I did it during the last 9 days, and that's around the time I noticed the issue and people also report seeing the warning which I saw. Correct me if wrong.

I re-disabled the Other notifications and will try to keep an eye on whether I see Signal update notifications or not now.

**Comment by greyson-signal** [comment]
Ok, I checked again, and we're definitely not posting "update available" notification to the "Other" channel -- it's using "App updates". I feel like this is likely related to #8936. 

If you notice you're not getting update prompts again (there will likely be another web release within the next week), then:

- Close Signal (can just dismiss in the app switcher)
- Open it
- Wait 10s
- Capture a debug log (Settings > Advanced > Submit debug log)
- Post the link here and re-open the issue.

Thanks!
