### ISSUE TITLE
4.47.3: multi-photo send fails sometimes

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#9020]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when I go to send a couple photos, they fail.

### Steps to reproduce
- Send two photos (pick first one from rail, second after pressing +)
- tap the airplane

**Actual result:** Two photos sit there and the sending progress circle fills in ridiculously slowly and then it restarts at an empty circle and tries to fill again
**Expected result:** Photos just send as normal

### Screenshots
![Screenshot_20190905-161025_Signal](https://user-images.githubusercontent.com/4967949/64386982-d9d50980-cff7-11e9-8390-400c8f0954a4.jpg)

### Device info

**Device:** Samsung Galaxy S10+ Verizon stock rom
**Android version:** 9.0
**Signal version:** 4.47.3

### Link to debug log

https://debuglogs.org/38929d180117402ea2a28425d963f5b09a7abc876dc158ca00d433834bbe3471

**Comment by jeremymasters** [comment]
I turned off Wi-fi and then they would send.  Then I turned Wi-Fi back on and they would send.

**Comment by greyson-signal** [comment]
I'm a bit confused on your repro steps, particularly "tap the airplane". Are you saying that you entered airplane mode? In that case we definitely wouldn't be able to send, because we'd have no network.

In general, if you experience network difficulties, we will sometimes have to restart the upload. That might be why you see the progress circle reset. I do see you having some sort of network difficulty during upload:

```java
09-05 16:00:49.216  9984 10054 I BaseJob : [99b47ae9-bcd1-4c0d-8cf9-aded54ab98e8][AttachmentUploadJob] Encountered a retryable exception. (Time Since Submission: 23300 ms, Lifespan: 86400000 ms, Run Attempt: 2/Unlimited)
09-05 16:00:49.216  9984 10054 I BaseJob : org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: timeout
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:755)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:627)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:354)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:92)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
09-05 16:00:49.216  9984 10054 I BaseJob : Caused by: java.net.SocketTimeoutException: timeout
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:560)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:543)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okio.ForwardingSink.write(ForwardingSink.java:35)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at okio.RealBufferedSink$1.write(RealBufferedSink.java:201)
09-05 16:00:49.216  9984 10054 I BaseJob : 	at org.whispersystems.signalservice.api.crypto.DigestingOutputStream.write(DigestingOutputStream.java:29)
```

Also worth noting that in some situations, switching between wifi and mobile data can cause network connections to break, which could also require us to retry the upload.

**Comment by jeremymasters** [comment]
You mean to tell me Signal can't conquer no network?? :) Sorry I mean the paper airplane send button, not actual airplane mode.

To clarify the repro steps, I tried to send two photos multiple times on wifi.  AP is right outside my office so I know it's not signal strength (which I verified on the unifi controller too for my device).  After failing to send photo(s) to a group and single individuals as a test, I wrote this up.  Then afterward I turned off wifi and tried and a re-send of the same photos worked.  I turned wifi back on in the same spot and everything worked again.  I've had this happen one other time while on strong wifi.  Sounds like maybe Signal Android is doing what it's supposed to be doing and maybe there's a bug with the wifi system (phone and/or access points).  Sorry for the

**Comment by greyson-signal** [comment]
Ah sorry, I apparently just see an arrow when I look at the send button :)

That's good to know. I'll close the issue for now, but feel free to re-open if you find it happening more consistently, on particular types of networks, things like that. Thanks!
