### ISSUE TITLE
Allow different kinds of identifiers for registration

### ISSUE THREAD

**Issue by unbranched** [signalapp/Signal-Android#9025]
I reopen this important issue #1085 , because it was closed by a questionable "cleanup".
This should be one primary concern to everyone imho.

**Comment by u32i64** [comment]
> it was closed by a questionable "cleanup".

That's because this is not a bug report, but a feature request/discussion topic. There are [topics about this on the forum](https://community.signalusers.org/search?q=alternative%20identifier) already.

Quoting [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

**Comment by Cerberus0** [comment]
@unbranched: Different kinds of identifiers are currently not supported, which makes this a feature request. Feature requests belong on the [community forum](https://community.signalusers.org/c/feature-requests). Please close this issue and continue the discussion there. You can easily join the forum with your existing GitHub account.

**Comment by unbranched** [comment]
Ok
