### ISSUE TITLE
Cannot make/receive calls when using a Private DNS

### ISSUE THREAD

**Issue by x80486** [signalapp/Signal-Android#9027]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just recently updated to Android `9.x` (Pie). I noticed there is a `Private DNS` setting under `Settings > Network & Internet > Advanced` that if I set to some value (actually I'm not sure if _any_ value because I'm using `1dot1dot1dot1.cloudflare-dns.com`) I cannot make/receive any calls anymore – but I (and also the recipients) receive the "Missed Call" notification after I hang out or wait for the call to "timeout".

> Notice this is only an issue if I'm using the carrier's data plan. If I'm using any WiFi connection (or at least the one I have at home), it works fine.

### Steps to reproduce

- Install Android `9.x` (Pie) or have a phone with it preinstalled 
- Go to `Settings > Network & Internet > Advanced > Private DNS`, select the option to provide the hostname and insert `1dot1dot1dot1.cloudflare-dns.com`
- Open Signal app
- Make a call (or tell someone to call you)

**Actual result:** The call is not received/made
**Expected result:** Signal should be able to make/receive calls

### Device info

**Device:** Nokia 7.1
**Android version:** 9.x
**Signal version:** 4.46.2

**Comment by DonDino2** [comment]
Same issue here. I have also tested with Quad9 DNS and Google DNS, the issue also occurs with them if set in the Private DNS setting of Android. It also occurs if I use Cloudflare’s 1.1.1.1 app.
I’m on a Samsung S9 on stock Android 9.

**Comment by GeorgesPaul** [comment]
Same here. Android 8.1, Blackberry KEY2 using DnsChanger app to change the DNS (off topic: absolutely mind-blowing that previous Android versions don't support changing a DNS settings).

**Comment by Lion-box** [comment]
Similar behaviour here on Sony XZ2C stock Android 9 and "one.one.one.one" as private dns.
Outgoing calls seems to work almost reliably.
Incoming calls are behaving in a strange fashion: notification of a "connecting call" appears almost immediately, then the call screen almost always appears and the telephone rings.
As soon as i accept the call my telephone seems to enter the regular call screen but nothing can be heard.  On the other side the call screen is still "ringing" and never sees that my telephone answered the call.
As soon as I close the "empty received call" on my side, the caller is disconnected and signaled of the rejected call.

**Comment by alleyoopster** [comment]
Similar problem here, where our home router uses 1.1.1.1 and 1.0.0.1. With these settings none of the phones using the home network will receive calls. Switching back to ISP DNS incoming calls will ring on the phone. Samsung S9 9.0 and Sony Z1 custom ROM LineageOS 9.0

**Comment by synthetc82** [comment]
Another +1 here, also using cloudflare, was going crazy until this came up in a google search!

**Comment by Bit-Byte-Sys** [comment]
Also similar here with Cloudflare WARP VPN app which uses 1.1.1.1 aswell on Pixel XL 🤔
(Android 10 with Always-on mode "Active" + Private DNS set to "Automatic" in internet settings)
