### ISSUE TITLE
About configuration

### ISSUE THREAD

**Issue by 29395373** [signalapp/Signal-Android#9028]
Hello, do you have any instructions for configuring signal server? Difficulties encountered in the configuration process.

Hello, is there any instruction document for configuring signal server?Difficulties were encountered in the configuration process.

**Comment by Cerberus0** [comment]
Hello @29395373,

As stated in the [bug report template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) and [contribution guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues), this issue tracker is only meant for bug reports. It is not for questions, comments, or feature requests.

You're welcome to post questions, comments and feature requests on the community forum: https://community.signalusers.org  There are already several open threads about [configuring the Signal server](https://community.signalusers.org/c/development/server-development). I suggest closing this issue and continuing the discussion there. You can easily join the forum with your existing GitHub account.
