### ISSUE TITLE
Video does not show preview nor play button (but does play when pressed)

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#9029]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving a specific video it does not show a preview nor a play button. It just shows the generic video icon. The video does play however when pressing it. 
In addition to that when I tried to forward the video message I noticed that while I was in the compose window it did show a preview of the video. After sending it though I also got the generic video icon in the conversation.
Since I run LineageOS and thought it might be related to that I forwarded the video to a samsung s9 device running it's stock android and Signal version 4.47.4. On that device it was the same behaviour. So also no preview.
Now as a final test I first saved the video and after that I've send it. Here I noticed some different behaviour. First if I select the video by pressing the gallery button and than select the video I do not see a video preview however if I select the video by pressing the file attachment button it does show the video preview and play button.
I will send the video to the support mail.

### Steps to reproduce
- send specific video
- check both send and receive conversation

**Actual result:** No video preview is shown.
**Expected result:** Video preview and play button is shown.

### Device info

**Device:** Samsung S5
**Android version:** 9 (LineageOS 16)
**Signal version:** 4.47.4

### Link to debug log
link of initially receiving the video (around 2019-09-10 12:20)
https://debuglogs.org/c966554e0dffef4df658d55a20bf3a7a700a4ac05abc951a71f4453b24dacae8
link of log while sending it by gallery attachment button and file attachment button (around 2019-09-11 09:20)
https://debuglogs.org/4f4649faab61b2c7435bfc519a0c423ddad041188611cfcd2d79558885a76e9b

**Comment by alan-signal** [comment]
Is it possible to attach a partial screen shot.

**Comment by bme13** [comment]
![Screenshot_20190913-210710_Signal](https://user-images.githubusercontent.com/25846829/64888960-750b5600-d66c-11e9-8bd0-09e8c3bf88a7.png)
Note this is a screenshot after sending the video. Receiving the video shows the same preview.
The video in the middle is the same as both the top and bottom one however that's the preview I get by forwarding it or add as attachment by using the gallery button. The other ones (with the correct preview) are send by adding it as a file.
btw. Did you got the video I send to the support mail? I've tested this on several phones (3 Samsung devices and an Acer all running Signal 4.47.5. For these devices the behaviour was the same.

**Comment by bme13** [comment]
I'm not able to reproduce this anymore using 5.13.2.
