### ISSUE TITLE
Add Service Announcements

### ISSUE THREAD

**Issue by jbick** [signalapp/Signal-Android#903]
Please consider adding a service announcement system to the app. Users might be able to select which level of messages they want to receive.

Use cases:
- first of all **notes about security issues** (update available)
- infrastructure problems (requirement: external infrastructure)
- notes about updates which require a manual update ( #890 )
- notes about updates which are available for a long time but are not installed on the end users device because automatic updates are disabled ( #873 )
- inform about cases in which a government / organization starts to block textsecure messages
- notes about the availability of new features or services (iOS client, desktop client, ...)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
