### ISSUE TITLE
Unable to send SMS (SMS pending forever)

### ISSUE THREAD

**Issue by nekromoff** [signalapp/Signal-Android#9030]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
I am unable to send SMS after the latest update. SMS are shown as pending (status circle is turning forever)

### Steps to reproduce
- Create SMS to non-Signal contact
- Send it
- SMS is shown as pending forever

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
SMS not sent

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
SMS sent

### Device info
**Device:** Nokia 7 plus TA-1046
**Android version:** 9
**Signal version:** 4.46.2

### Link to debug log

https://debuglogs.org/34e9432119115233d14e961493df6f5c4cfc766a242410def74a6bd2ab677751

**Comment by crobibero** [comment]
I am also having this issue.

I'm running LineageOS + microG (https://lineage.microg.org/)

### Device info
Device: Essential PH-1
Android version: 9
Signal version: 4.46.2



### Link to debug log: 
https://debuglogs.org/e79ef4279c4db5a31f6c0983742a782c8e06b369d96da334ff0cc1e09c6054e7

**Comment by nekromoff** [comment]
Any tips what could be failing?

**Comment by crobibero** [comment]
I changed nothing and late last night everything sent all at once

**Comment by nekromoff** [comment]
Same for me. Today SMS sending works.

**Comment by nekromoff** [comment]
But I would still like to know the issue that somehow related to Signal
handling of messages via SMS or data...

**Comment by kangabell** [comment]
I'm having the same issue. Been going on for couple weeks. There was one day about 9 days ago where all my pending messages sent all at once, but the next day it was back to not working. I can _receive_ SMS fine, send+receive secure messages to other Signal users fine, but sending SMS to non-Signal users does not work, just shows the "sending" icon indefinitely.

### Device Info
LineageOS
LG Optimus L90
Signal v4.46.2

### Link to debug log
https://debuglogs.org/5400cd00ff13459270de0f59083242ec767068d8c50d25e7715ecfbfdba23834

**Comment by greyson-signal** [comment]
I see two different problems. 

In @nekromoff's log, the CellServiceConstraintObserver is indicating the constraint is met, but the SMS still aren't executing. Could be a possible thread visibility problem with updating the constraint status. I'll look into it and see if I can reproduce it.

In @kangabell's log, the phone never thinks it has cellular service. I'm assuming that because you're receiving SMS that you do have cell service though, yeah? Do you use SMS over wifi? If so, try enabling Settings > SMS and MMS > 'WiFi Calling' Compatibility mode. The way it's written, it won't affect currently enqueued SMS, but it should allow future SMS to send if a data connection is available. 

However it's also worth noting that messages are sent in order within a thread, so if older messages are enqueued waiting for cell service that it can't detect, then future messages in that thread won't send. So if this does end up being the problem, you can delete the stuck messages, restart signal, and then send a fresh message with wifi calling enabled. Sorry that's confusing, definitely something you shouldn't have to think about :) I'll see if there's a sane way to respect the wifi calling setting change on-the-fly.

**Comment by Tursko** [comment]
Would love to hear how you end up solving the issue @greyson-signal 
I have 1 friend who seems to have this same issue every once in a while.

**Comment by retroformat** [comment]
I'm currently having the exact same problem as OP with a Nexus 5 phone, Signal v. 4.47.6

here's my debug log:

https://debuglogs.org/e7d8c85ecd97b6588d814104073ffed17d81718748c1a66676dfac03f386858a

**Comment by kangabell** [comment]
@greyson-signal I don't use SMS over wifi, no.

I'm also able to use the stock Messaging app to both receive AND send SMS, so the phone doesn't seem to have an issue with the connection, _just Signal_.

An update: Shortly after my last post ([Sept 16](https://github.com/signalapp/Signal-Android/issues/9030#issuecomment-532007555)) there was a Signal app update. After I updated, my pending messages sent. However, the next day it stopped working again. After a couple days I decided to make Messaging my default app and not use Signal for SMS anymore until there is a solution.

**Comment by AuspeXeu** [comment]
I have the same issue and realised that after I force stop the signal app and start it again, the SMS would immediately send.

**Comment by nekromoff** [comment]
Version 4.47.7 seems to hav resolved this issue for me. I haven't encountered this issue since the update.

**Comment by AuspeXeu** [comment]
For me the error still persists, especially when coming out of airplane mode. @nekromoff can you confirm this?

1. Go airplane mode
2. Send an SMS
3. Leave airplane mode
4. SMS is stuck

**Comment by nekromoff** [comment]
Not happening to me, error was shown after leaving flight mode: "Unable to
send, tap for details". Following with sending retry worked fine.

**Comment by kangabell** [comment]
Just confirming that I'm still having the issue over here, even after the version update.

**Comment by dkm** [comment]
I'm having the same problem. This had happened few times in the past, but this week, it looks like I simply can't send SMS. I've tried rebooting the phone, using airplane mode, wifi on/off... Can't figure out what will cause Signal to send SMS. Using stock messaging app works correctly, no network coverage problem.

Here's a log: https://debuglogs.org/cce9b88b3c40bad8a7fccdf2a0e801a4e2189ebe9c8da71ba9c81f78f77673a5

**Comment by la99er** [comment]
I'm running version 4.48.17 and have the same issue. The status of an outgoing SMS stays on Pending ...
Funny fact is, that the SMS was received by my friend. So it looks like the SMS is working fine, but the status message does not update correctly. I already force stopped the app and restarted it. Messages still pending.

**Comment by Tursko** [comment]
Wifi Calling on is still giving us issues with MMS downloading on the most recent version of Signal.

Friend gets an MMS, says it can't download. Turns off Wifi Calling, waits a minute or so, clicks retry, downloads MMS successfully.

**Comment by Valiant70** [comment]
I don't seem able to send SMS through signal over wifi or cell. I think I was able to send a message or two this morning when I first installed the app, but now it doesn't work no matter how many times I restart the app. I turned on Wi-fi calling compatibility, but I still can't send anything. Receiving SMS works fine, but no one has tried to send me a picture today so I don't know if that works or not.

**Comment by retroformat** [comment]
In late Sept. I announced here (see above) I had this problem.  I recently tried my Signal app again, and now it is working fine.  I note that my version number has updated to v.4.48.17
Good news for me at least, THANKS!

**Comment by breversa** [comment]
Still persists for me with v.4.48.17.

As @AuspeXeu said, killing Signal (by long-pressing the "back" button, on custom ROMs) then starting it again sends the SMS at once, even if it was stuck for hours.

**Comment by Tursko** [comment]
My friend on a Moto G6 with Signal 4.49.15 is still encountering the problem. If he kills the app and reopens, the SMS will finally send.

**Comment by Drhaal** [comment]
I'm on 4.49.18 with Lineage Os + Micro G and the issue is still present. 
Turning OFF and ON Airplane mode or Wifi-call changes nothing but the SMS are still working on others app.

**Comment by nekromoff** [comment]
I can confirm it still happrns from time to time. I might post the debug
log if that helps again.

**Comment by janvlug** [comment]
I think that I have this issue as well. I am seldom using SMS. For a certain contact, I tried to send two SMS message yesterday. I noticed that the messages are still Pending according to their message info. The icon next to the messages is also a spinning circle.
I rebooted my phone, and the messages are still not sent.
[Here is a debug log](https://debuglogs.org/6de260a1f2eb59807a1e1b07c633e2f2a7eab7bb9fd812f9a0a96ad451308a36).

**Comment by janvlug** [comment]
I deleted both pending SMS messages and sent a new one. But this newly sent message also stays in the pending state. [Here is a debug log.](https://debuglogs.org/da479438bea36f562e9a0cb3ff6db25d47f2c83f20cdb77f4d843b6c14a2bfa7)

**Comment by janvlug** [comment]
I read the comment by AuspeXeu on 3 October. Also for me force stopping Signal and starting it again resulted in the pending SMS to be sent immediately. [Here is a debug log](https://debuglogs.org/ecb7bf4d32e1ea247595f9d0461f53843f4ca5594e6fc7da63a2175d9cb7fe20).

**Comment by Tursko** [comment]
Same issue here on my new Pixel 4. 

Deleting the pending message, restarting the phone, and killing the app did not fix it. BUT deleting the thread completely then sending the message made it send instantly. 

https://debuglogs.org/1e8731362ec350f50855773c6ee5aa8532735b18b3c4be3377ccf4677c39fc3b

**Comment by pikrzysztof** [comment]
Signal 4.50.6, messages take a lot of time to send. Reboot doesn't help but "Force stop" and restarting the app helps. LineageOS 14.1-20190224-NIGHTLY-sumire, Android 7.1.2, Sony Xperia Z5.

**Comment by D4nte** [comment]
Same issue https://debuglogs.org/5a39ddf157e6fec9940f9f2df530764e2b9bd57d8071af516dd903f2718ae206

**Comment by Tursko** [comment]
I now get the issue like once every couple threads but my messages always go through. It just shows pending.

**Comment by D4nte** [comment]
Messing around with the wifi connections somehow helps with that for some reason.

**Comment by tonio4open** [comment]
Hello,

I have the same random issue with the SMS sending.

### Bug description
Sometimes, after the boot of my smartphone, it's not possible to send SMS. The little dotted wheel rotates rotates rotates...

### Steps to reproduce
Maybe to have my smartphone ;-)

### Workaround
Reboot once or twice the smartphone.

### Device info
Device: Samsung Galaxy S4 mini GT-i9195i
Android version: 7.1.1
Signal version: 4.50.6

### Link to debug log
https://debuglogs.org/a8f422d1e1b1176e73e344b54224b2af9d4d68c6177f28783c97b2e29a462805

Thanks for your help.

Antoine

**Comment by janvlug** [comment]
Happened again. Force stop of Signal fixed it again as well:
[Debug log.](https://debuglogs.org/6710c6e89fca4acb98fa1f7dda7ad7d9a123e66f72d98043b17869fbce4f912f)

**Comment by janvlug** [comment]
Today, I ran into the issue again (I think this was the first time I sent an SMS since my previous comment.
Debug log taken when sending message is still pending is [here](https://debuglogs.org/e844ac3ebc9548278731cc62426e927af880abaf6638dad12fc45e8e3c38fc67).
Debug log just after force stop of Signal is [here](https://debuglogs.org/215af5a0889f52dae17c480e27cef47a5bdc414fcbe3b26b9fc803c4e036dea6).

**Comment by peterpanondrugs** [comment]
Same issue with stuck SMS. Its very annoying since its my main APP for sending SMS.
If i FC Signal, and restart it, the SMS is sent immediately.
https://debuglogs.org/1cdeb53b3ffd799fb31e80ee22bf816ed69a449516b11f764452b956bccc8eeb

**Comment by WarmongeringBeaver** [comment]
I periodically encounter the same problem.

The only workaround that I've been able to found is to stop the app process, and restart Signal.

**Comment by fiske-d** [comment]
This is still happening to me on LineageOS/MicroG over several updates

Send SMS and the wheel spins and spins

Solution, as others have also pointed out, seems to be kill the app and reopen. 

Problem returns with reboot

**Comment by iannongithub** [comment]
I faced the same issue several times the last months. This time I turn on WiFi Calling in Signal and every messages was sent a few second later.

Note that this issue appeared also in a area with no WiFi and a good phone network coverage..

I'm not skilled enought to dig deeper in WiFi Calling stuff so I just generated this debuglog *right after* turning on WiFi Calling in Signal and the messages was sent:

https://debuglogs.org/b58763df701b56b3b65f48e373cf9fb60414c06b3cd29421370970e86b9f6c17

My config:
- Signal  4.68.4 (6850)
- /e/OS (based on Lineage) 0.8-o-2020041649925-dev-j5nlte

Hope that help

**Comment by Jawshy** [comment]
### Bug description
I'm experiencing a similar issue. When I send unsecured SMS messages their status is pending and never changes to sent until I restart my phone. Before sending SMS messages I make sure flight mode is off and I do have sufficient phone credit. In Signal, _'WiFi Calling' compatibility mode_ is off because Wi-Fi calling is not provisioned on my phone. 

For the debug log below, check around 2020-08-30 11:48:41 because that's when the SMS was sent. 

### Steps to reproduce
- Send a unsecured SMS message to a non-Signal contact (flight mode is off and has sufficient phone credit)
- The message is never marked as sent so restart device
- Open Signal and the SMS message should now be sent

**Actual result:** The status of the SMS message is pending. 
**Expected result:** The SMS message is sent near instantly. 

### Device info

**Device:** Google Pixel 3a
**Android version:** 10
**Signal version:** 4.69.6

### Link to debug log

https://debuglogs.org/d345362866bd6774fe950adaf24785af5a22d9b217a57bc9e7708c1abb7d6cad

**Comment by breversa** [comment]
I just noticed the following :
- Single, < 160 characters SMS are sent without problems
- Multiple/long, > 160 characters SMS are problematic

**Comment by MichaelSMVogel** [comment]
Signal 5.0.1 & 5.0.2 short sms do not get sent. Force restart doesn't help

**Comment by Tursko** [comment]
> Signal 5.0.1 & 5.0.2 short sms do not get sent. Force restart doesn't help

Someone also mentioned that here
https://github.com/signalapp/Signal-Android/issues/10270

**Comment by therriault** [comment]
Had the same issue with SMS not sending, started yesterday and none of the usual fixes (deleting pending messages, clearing cache, force quitting, restarting phone) made any difference. Solved it by enabling the default Android messaging app (which I'd previously disabled) and the texts immediately caught up. No idea of the mechanism but easy thing to try.

**Comment by MichaelSMVogel** [comment]
nice catch, seems to work for me, too
Thank you

**Comment by thall** [comment]
Can't either send sms (receive works) with nokia 8, android 9. 

None of the above workarounds around works. 

Log: https://debuglogs.org/714c813335142e2704d64c9a43e33565ef25d4e0e896dab21568d71034a5dbab

**Comment by MuadDibIII** [comment]
Hello, I’m having a similar issue with SMS on my Android device (Samsung Galaxy S10e).

For 2 times now, when I tried to send a SMS it doesn’t leave. The “circle icon” stays turning forever.

The only way to make it work is to redefine the default SMS app (to the phone original app), redefine again Signal as default SMS app a 2nd time. Than the SMS starts working again.

Immediately after the error happens :
https://debuglogs.org/c4bf2cc7b34b7a52902c00f240380329068eb6d6dba4c406f471bead36357709

And after restating the default SMS app :
https://debuglogs.org/4fc4b985a2aabb024087df4fb06864efb427239bac7cb8865ec94d994e7971f4

Thanks for the help,
Marc

**Comment by alexbodn** [comment]
hello and a big thank for providing signal,

this bug does unfortunately happen to me too.
I turned internet off and tried to send with the only unlocked option, 
but the dotted circle was turning round for long, 
and the message was sent only when internet resumed.
later, it went off right away.
i'm commonly found in this condition since I'm hiking in areas with GSM service, but no internet.
however, sending the text may mean much to me in this conditions.

thanks a lot,
alex

**Comment by 015203087630** [comment]
Am 17.01.2021 10:06 schrieb "MuadDibIII" <notifications@github.com>:
>
> Hello, I’m having a similar issue with SMS on my Android device (Samsung
Galaxy S10e).
>
> For 2 times now, when I tried to send a SMS it doesn’t leave. The “circle
icon” stays turning forever.
>
> The only way to make it work is to redefine the default SMS app (to the
phone original app), redefine again Signal as default SMS app a 2nd time.
Than the SMS starts working again.
>
> Immediately after the error happens :
>
https://debuglogs.org/c4bf2cc7b34b7a52902c00f240380329068eb6d6dba4c406f471bead36357709
>
> And after restating the default SMS app :
>
https://debuglogs.org/4fc4b985a2aabb024087df4fb06864efb427239bac7cb8865ec94d994e7971f4

**Comment by breversa** [comment]
@alexbodn :
Please note that Signal *requires* an Internet connection to send encrypted messages. It will *not* automatically fall back to unencrypted SMS if you're out of Internet coverage.
In that case, you need to manually select "Send as unencrypted SMS" (by long-pressing the "send" button).

This here issue is about trying to send an SMS to a non-Signal user (in which case Signal has no other option but fall back to SMS), and said SMS stays pending.

**Comment by hakubo** [comment]
I'm experiencing the same issue. Xiaomi redmi note 7, latest signal app version 5.2.3.

Resetting default SMS app does resolve the issue temporarily.

**Comment by h4knet** [comment]
I can relate having the same issue. For a whole day, text messages would stay one waiting mode..
Force kill the app, reboot the phone doesn’t help. I had to copy/paste the messages again until they would be sent and delete the other ones.

I could wait a whole day and the messages would stay in waiting mode.

**Comment by searsaw** [comment]
Have the same issue on CalyxOS with microG. Running Signal v5.13.8. A force stop of the app solved my problem this time.

**Comment by ThisIsPaulDaily** [comment]
Same issue on: Lineage OS build number  lineage_lake-userdebug 11 RQ3A.210705.001 e305d45f4f

With a Moto G7+. It could possibly be related to carrier services, or something like that. Force stop and restart sent the texts. 
Version 5.16.3 of Signal app* 

I know commenting saying me too doesn't really help anyone, but it makes me wonder if it's Lineage playing a part.

**Comment by LaPeste** [comment]
Since this has been an issue for a little more than 2 years, would it be possible for the devs to spend at least 2 words on why this is such a complicated problem to solve? If that's not the case, meaning it's not a complicated one, then could you tell us why is the issue given such low priority?
As you, devs, can imagine, this is pure curiosity, nothing more. But, I think that me and all the other people in this thread would really appreciate hearing from you.

Of course, thank you for the crazy hard work you're putting into this app! ❤️

**Comment by greyson-signal** [comment]
Unfortunately all of the earlier debuglogs that were posted have expired :( I someone could post another log after having stuck SMS, I could take another look.

**Comment by LaPeste** [comment]
When it happens again to me I'll post the logs. Could you link a guide on how to extract the logs?

**Comment by martinklein0815** [comment]
> Unfortunately all of the earlier debuglogs that were posted have expired :( I someone could post another log after having stuck SMS, I could take another look.

my debug log:
https://debuglogs.org/030bf8ebfc8f89c78d9b60ae20a8a402d42c737d2c5dfba4bf76b23a74402512

Note that my environment seems slightly different from the above mentioned. Pixel 6, Android 12, Signal 5.28.8
- sending SMS stuck "forever"
- receiving SMS works 
- Signal chat, MMS, and group message works

**Comment by YannBrrd** [comment]
Same here
Signal 5.28.5
Android 11
Oneplus7T

Seems to happen when heavy using SMS,  like gattling

**Comment by greyson-signal** [comment]
@martinklein0815 In your case, your SMS were stuck because we did not believe you had cellular service. Note that this is separate from Wi-Fi or even cellular data -- this is just the connectivity that handles PSTN calls and SMS messages. If your service provider allows you to send SMS over Wi-Fi, you can enable this in Signal in Settings > Chats > SMS and MMS > 'WiFi Calling' compatibility mode. Let me know if that works!

@LaPeste To get logs, you can follow the instructions [here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports).

**Comment by joyfulsong11** [comment]
I have the same problem of the swirling "pending" sms on my LG Stylo 5. 
Here is the debug log from today.

I don't have any cellular connection, but wifi calling is enabled on the phone and in the Signal app.  Any tips would be appreciated ! 

[](https://debuglogs.org/834e2cff3f71d7f60f283ff6012f5b380c90916b05a7a933d799c04ad768ba6e)

**Comment by bdm310** [comment]
I don't know what the initial problem was that started this issue but anyone having pending forever SMS issues may be seeing https://github.com/signalapp/Signal-Android/issues/11898

**Comment by sempervictus** [comment]
It is - Signal can get into a state where outbound messages stick (spinning circle of dots indicating its being sent), requiring a system reboot to clear, and either then dumping a ton of pending message on the unsuspecting recipient or issuing a failure to send notice. Happens every couple of days, cause of most reboots for me (normally GrapheneOS and prior incarnations ran until an update required a reboot).

**Comment by LaPeste** [comment]
Yesterday night I sent an SMS before going to sleep and the SMS went through. I put my phone in flight mode, as every night. This morning I turned off flight mode and sent another SMS in response to what came during the flight mode was on. The SMS got stuck with the spinning circle. I rebooted the phone at which point the SMS got sent.
I collected the [logs](https://debuglogs.org/android/5.32.15/8d6a8047c7cb06f9600b130667142327bfa320e236931d3070a7ab7a73c808fb) before rebooted. I hope this time you can take a look at them before they expire.

**Comment by Tursko** [comment]
> I experience this occasionally on my Pixel 5. Experiencing it right now. Rebooting triggered a fail to send error. However, I still get spinners when I try to send SMS atm. 
> 
> Pictures go through every time. Even sometimes a spinning message goes through, but not all of them. Would love resolution for sure.

Can you attach a log?

**Comment by Tursko** [comment]
> How do I fetch the logs?

Here's the FAQ page on it. It's very easy. 

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by sdyarnell** [comment]
https://debuglogs.org/android/5.34.5/3bb41782b1d4b6635fa033a7088568442f98fa458dbdf43a165e3ff42adf438b

**Comment by ValentinDrean** [comment]
Only solution I found myself, is to enter airplane mode, force quit Signal, re-enter cellular data mode without wi-fi and re-open signal app, then sms messages are sending (not always, I have to do it again & again sometimes). Other people around me have same problem with different phones & carriers.

I have LG G5-H850 with `lineage_h850-userdebug 11 RQ3A.211001.001 10043176`, it never worked ;\

**Comment by hakubo** [comment]
This is still a problem for me. I had to switch to native messaging app because of this bug.

**Comment by sempervictus** [comment]
This issue is clearly affecting tons of users (for everyone filing a GH issue, you likely have hundreds who just give up and turn away from the app), and hampering adoption of E2E comms (alternatives being from mordor or too complicated for end-users). Could Signal please assign this ticket to an engineer for response and remediation? Stale-bot is only marking wontfix because nobody is assigned _to_ fix and despondent users arent going to keep updating the issue with nobody to address it.

**Comment by erik55** [comment]
Duplicates: #12382 and  #12218

**Comment by erik55** [comment]
I have had the same problem many times. It keeps sending (rotating ring) for several minutes, sometimes hours. Then there seems to be a timeout and I get a «SMS sent failed». I can then tap on the failed sms and resend, then it always works immediately.

**Comment by LaPeste** [comment]
It's happened again. I hope you can take a look at the [logs](https://debuglogs.org/android/5.44.3/f41cd6e23a93e9eaee671a7f196293e9877b917cbec5ad0bda2aa82e8e2745c3) as long as they are available.
Do you also need the logs for when the phone it's restarted and I try to re-send the message?

**Comment by hubyhuby** [comment]
Since about a week

**Comment by Tursko** [comment]
Constantly failing to resend. I notice that I have an MMS message from one of the contacts that is unable to download and any of the messages I try to send continue to fail.

https://debuglogs.org/android/5.51.7/ce244199ac7c70e37541b52d5000bc61e0b07a031ca85a03f6497cc49e2db32e

**Comment by sempervictus** [comment]
Can this get prioritized under the "its a security issue" banner?
This problem qualifies as a denial of service concern, so if developer resources are prioritized for those, then maybe its a way to get it some mind share from them on the problem.

**Comment by greyson-signal** [comment]
Hi there, given our future plans to [remove SMS support](https://signal.org/blog/sms-removal-android/), I'm gonna close this. Thanks!
