### ISSUE TITLE
please delete this issue

### ISSUE THREAD

**Issue by androclus** [signalapp/Signal-Android#9032]
please delete this issue. i do not seem to be able to.

**Comment by ahstro** [comment]
Don't know if issues can be deleted, but you, as the author, should be able to close it. There should be a button next to the Comment-button.

**Comment by u32i64** [comment]
> Don't know if issues can be deleted

@ahstro Organization members should be able to, for example here's what I can do in my own repos:

![image](https://user-images.githubusercontent.com/19972511/64865081-3318ea80-d641-11e9-84ed-96d1a5192f77.png)

**Comment by alan-signal** [comment]
Closing is sufficient.
