### ISSUE TITLE
No notification on huawei watch gt

### ISSUE THREAD

**Issue by EnFrogge** [signalapp/Signal-Android#9034]
Since a few updates ago no messages will be forwarded to huawai watch gt.

Notifications on healt app are set.

i tried reinstall of both apps with no success.

**Comment by ddddavidmartin** [comment]
I'm wondering if I'm seeing the same issue. I have a Fossil Hybrid watch and it does not vibrate  anymore when I get Signal text messages. When I switch to the default messaging app it works every time.

I think the way it works is that you can set certain apps in the Fossil app and it will vibrate the watch when it detects a notification from the set apps. In this case it does not seem to be able to detect Signal notifications anymore.

I'd much appreciate any insight into how to debug this further. Thanks!

**Comment by EnFrogge** [comment]
i figured out that the problem appears only if is signal set as sms messenger. without setting signal as standard sms messenger all chats in signal will be forwarded. 
it seems signal changed something after sms activation. in huawei healt, which is needed to forward messages to the watch, the signal icon changes in to a light blue sms-icon.
verry special.

**Comment by PablitoKarramba** [comment]
Issue is still present. I recieve no Signal notifications on my Huawei Watch GT 2 Pro and Signal is set as my default SMS app(smartphone is Honor 20, Android 10)
