### ISSUE TITLE
Regarding Signal Private Messenger App problem in Samsung S10 5G device

### ISSUE THREAD

**Issue by jongyunchoi742** [signalapp/Signal-Android#9035]
### Bug description
When we switch front<->rear camera during doing video call, video call suddenly is stopped. 

### Steps to reproduce
- We switch front/rear camera in several times during doing video call.
- Video call suddenly is stopped.

**Actual result:** Video call is stopped suddenly.
**Expected result:** Video call don't have to be stopped suddenly.

### Device info

**Device:** S10 5G(This device has ToF depth camera)
**Android version:** (Android 9.0 - P)
**Signal version:** 4.47.5

### Google Guide for fixing this issue.
We recommand that you can check depth camera with below condition.
https://medium.com/androiddevelopers/camera-enumeration-on-android-9a053b910cb5

### Link to debug log
--------- beginning of crash
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: FATAL EXCEPTION: WebRTC-SurfaceTextureHelper
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 14115
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Enumerator.convertSizes(Camera2Enumerator.java:231)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Enumerator.getSupportedSizes(Camera2Enumerator.java:146)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Session.findCaptureFormat(Camera2Session.java:327)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Session.start(Camera2Session.java:315)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Session.<init>(Camera2Session.java:298)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Session.create(Camera2Session.java:276)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.Camera2Capturer.createCameraSession(Camera2Capturer.java:35)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:270)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-23 13:56:36.463 10241 14115 14284 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Cerberus0** [comment]
Probably related to https://github.com/signalapp/Signal-Android/issues/8685
