### ISSUE TITLE
Remove conversation from the menu within

### ISSUE THREAD

**Issue by drws** [signalapp/Signal-Android#9037]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A whole conversation cannot be removed while viewing it (no option in the menu). The user has to return to the conversation list first and remove it from there or manually remove all messages. It is not a catastrophe not to have the option there in the menu, it only spares a tap here and there. But one would assume all possible options are there, especially since the menu also contains a very-rarely used Add to home screen option.  

### Steps to reproduce
- open a conversation in Signal
- try to remove it completely without going to the previous view or multi-selecting (think a very long conversation)

**Actual result:**
The user goes into an infinite loop.

**Expected result:**
The conversation should be removed so the user is able to continue.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
