### ISSUE TITLE
cannot re-register signal after attempting to move back to an android phone from an apple phone

### ISSUE THREAD

**Issue by jacobheric** [signalapp/Signal-Android#9038]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently moved signal to an iphone (7) after long time use on motox 4 running stock android (9) phone. Today, I moved my sim card back to my android phone and re-registered signal. Re-registration worked and I began receiving signals but the signal app still said I was not registered and asked me to register it. I tried to register it a few more times, each time signal loaded old codes which failed. Then signal thought I was a robot and asked me to prove I was not using reCAPTCHA, which I did. 

I uninstalled and re-installed signal and restarted the phone. Now, when I try to register signal on my android I get the "unable to connect to service error". 

Android is stock and the network is working fine as is the play store. I cannot register or use signal on my android phone.

### Steps to reproduce
- Register signal on Android
- Move sim to apple phone, register signal there
- Move sim back to android, re-register signal there
- Attempt to re-register signal a few more times to remove registration prompts
 
**Actual result:** 
Registrations fails with a network error.
**Expected result:** 
Registration works.

### Screenshots
![Screenshot (Sep 19, 2019 7_59_14 AM)](https://user-images.githubusercontent.com/191780/65242414-ed7e7680-dab3-11e9-80e5-350fbf074cee.png)

### Device info

**Device:** moto x4
**Android version:** android 9 (stock)
**Signal version:** 4.47.6

### Link to debug log
Happens during registration, so not sure how to get debug log.

**Comment by alan-signal** [comment]
I expect you're hitting anti-fraud rate limiting if you've been registering many times, try again tomorrow. The real concern is the thing that caused you to attempt to re-register so many times. Please supply screen shots of those "the signal app still said I was not registered and asked me to register it." messages.

**Comment by jacobheric** [comment]
Ok, I'll try again tomorrow and report back here if it works. 

Unfortunately, I did not take screenshots of the original problem. If it happens again I will file a new issue with screenshots. I'm not too eager to reproduce it though as I don't want to risk losing signal communications for another day! 

Another interesting corner case here is that if you are attempting to re-activate a signal install on android that is also set as the default sms app, signal will start auto-filling old codes that have become invalid. And there is no way to exit the registration screen, grab the current valid code and re-enter the registration screen.

**Comment by jacobheric** [comment]
I tried again today and was able to register on my android today without any issues.

If I get some time I will try to reproduce the original issue.

Thanks for your help.
