### ISSUE TITLE
 "Mark as read" feature from notification channel not working a reply has been written through the notification

### ISSUE THREAD

**Issue by jedix** [signalapp/Signal-Android#9042]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After answering a text through the notification channel it is no longer possible to mark the conversation as read.

### Steps to reproduce
- close signal
- receive a message
- view the notification, write an answer and hit reply
- try to mark the message(s) as read

**Actual result:** The notification does not disappear, the message is not marked as read.
**Expected result:** The notification disappears, the message is marked as read.

### Screenshots
![signal-screenshot](https://user-images.githubusercontent.com/211924/65376700-6abc0e00-dca3-11e9-8a90-61d864330321.png)

### Device info

**Device:** Oneplus 3 / Xiaomi Mi A2 Lite
**Android version:** 9
**Signal version:** 4.47.6

### Link to debug log
https://debuglogs.org/f7485d3c13b4cba48831f16beee57152b16d5cebcb43b136897139a758e206e7

**Comment by greyson-signal** [comment]
This is some android behavior. I don't know why they decided to make action buttons work like this, but it's made so that after you reply, the only way the notification goes away is by swiping it away. Other apps do the same thing, it's just an Android UX decision.

**Comment by reversesh3ll** [comment]
This doesn't seem to be the case anymore. At least for Android 10 with the stock Messages app. As you can responded to the notifications and then marked as read.
