### ISSUE TITLE
Signal fails to register with Google Play Services uninstalled for user 0 (using ADB)

### ISSUE THREAD

**Issue by MegaArthur** [signalapp/Signal-Android#9043]
- [x]   I have searched open and closed issues for duplicates
- [x]   I am submitting a bug report for existing functionality that does not work as intended
- [x]   I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]   This isn't a feature request or a discussion topic

Bug description

When Google Play services are unistalled for the active user (using adb [pm uninstall -k --user 0 com.google.*] without root access), Signal fails to register, throwing an error about Google Play Services being unavailable or updating.

Steps to reproduce
• uninstall all stuff related to Google using the ADB command
• install Signal
• try to register

Actual result: Signal throws an error about GooglePS being unavailable or updating.

Expected result: Signal should warn about GooglePS being unavailable and switch to WebSocket notifications.

**Comment by greyson-signal** [comment]
Unfortunately I have no idea what the ramifications are for uninstalling com.google.*. It sounds like you've removed play services in such a way where we think it's installed, but invalid? Either way, this sounds like an environment issue, not a Signal issue. You might be able to find some help on [the forum](https://community.signalusers.org/). Thanks!
