### ISSUE TITLE
Signal Android App on F-Droid store in 2020 or have specific wiki page or README section why not.

### ISSUE THREAD

**Issue by paulvi** [signalapp/Signal-Android#9044]
publish Signal Android App on F-Droid store in 2020  
or have specific wiki page or README section why not.

 - [x] I have searched open and closed issues for duplicates:  
#8469 #7505 #7988 #6292 #5995 #5853 #4430 #3954 #3435 #2858 #525 #281 
and of cause #127 and searched https://community.signalusers.org/search?q=F-droid

 - [ ] I am submitting a bug report for existing functionality that does not work as intended
 - [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
 - [ ] This isn't a feature request or a discussion topic

----------------------------------------

Major reason is that Google Play is not available in China.   
And with all proper warnings direct download https://signal.org/android/apk/ is also not what most users asked for.

There is no single point of reference what is holding publishing on F-Droid.
Some older things may be just outdated.

A wiki page or README section could be good to express authors view.
Making users create such issues again, closing it and referring  to forum is making waste of time. Most developers on GitHub just can wait for an issue to be resolved.

Pieces of good thought, old and newer problems are scattered within many places.
If authors here are busy to summarize situation, let me start the F-Droid page.

Hopefully this issue will be closed, when at least wiki page exists.

**Comment by greyson-signal** [comment]
Many of the reasons provided in the issues you linked to are still valid. 

Here's a simple one: We want to be able to sign releases with our own keys. This would require us to host our own F-Droid repository, at which point people would need to know to add our repository, at which point they might as well download our APK directly, which already has an auto-update mechanism built in, which is all we'd be getting from F-Droid at that point.

But as we've stated previously, we use the forum for discussions, not Github. Github is for tracking bugs. Thank you!

**Comment by paulvi** [comment]
Do you mind me starting wiki page here
https://github.com/signalapp/Signal-Android/wiki/F-Droid
?

**Comment by eighthave** [comment]
@greyson-signal I've been involved in these discussions since the beginning.  The only issue blocking  Signal from F-Droid is that it is not free software.  It includes proprietary Google libraries.  Any app can be signed by the developer's key and included in F-Droid as long as it is 100% free software and can be built reproducibly, like Briar, Bitcoin Wallet, Offi, etc.

**Comment by paulvi** [comment]
@eighthave Hans, could you point where exactly Google libraries are ?
https://github.com/signalapp/Signal-Android/blob/master/build.gradle#L56

**Comment by eighthave** [comment]
Last I checked the Signal library list was a year ago, when it contained GMS, etc.  We track inclusion issues in our RFP tracker, here's the one for Signal:
https://gitlab.com/fdroid/rfp/issues/451

We welcome updates there, like if all the proprietary libraries have been removed.

**Comment by paulvi** [comment]
https://gitlab.com/fdroid/rfp/issues/451 
is great reference point, but needs to be reopened (closed by bot)

https://f-droid.org/wiki/page/org.thoughtcrime.securesms says
> This app is disabled and does not appear in the repo

**Comment by paulvi** [comment]
Added wiki page https://github.com/signalapp/Signal-Android/wiki/F-Droid
as

## Signal Android App on F-Droid store / F-Droid status

The GitHub issues are only for bugs,
and feature request should go to forum.
https://community.signalusers.org/search?q=F-droid

Nevertheless user kept asking via issues:  
#9044 #8469 #7505 #7988 #6292 #5995 #5853 #4430 #3954 #3435 #2858 #525 #281 #127

There is already alternative to Google Play available   
as direct download from https://signal.org/android/apk/

Issue within F-Droid RFP tracker [ref](https://github.com/signalapp/Signal-Android/issues/9044#issuecomment-535425169)
https://gitlab.com/fdroid/rfp/issues/451




---
This page is created by non-project member, see #9044  
 
If you not project member, and don't have references for your knowledge, please add this below this line.
