### ISSUE TITLE
Voice message playback volume not adjustable when holding the phone to your ear

### ISSUE THREAD

**Issue by dcormier** [signalapp/Signal-Android#9045]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When listening to a voice message, you can hold the phone to your ear to play it back privately. When doing this, you cannot control the volume of the audio using the volume buttons on the phone.

The problem is that in this mode, the audio is being played back using the call volume setting, but the volume buttons control the media volume.

### Steps to reproduce
- Receive a voice message
- Press play
- Hold the phone to your ear to listen privately
- Use the volume buttons on the phone to attempt to adjust the volume

**Actual result:** The volume of the audio being played does not change.
**Expected result:** The volume of the audio being played would change.

### Device info

**Device:** Google Pixel 2
**Android version:** 10
**Signal version:** 4.47.6

**Comment by haffenloher** [comment]
Can confirm, this has always been an issue. Adjusting Signal's earpiece playback volume is possible through another app, though (e.g. while listening to a WhatsApp voice message & holding the phone to your ear).

**Comment by andreafeletto** [comment]
Same on Pixel 3a, Android 10, Signal 4.52.4.

**Comment by samueltsw** [comment]
Same on Pixel 3, Android 11, Signal 5.4.12

**Comment by MEPoss** [comment]
Same on Pixel 4, Android 11, Signal 5.4.12. Really annoying.

**Comment by jnnkB** [comment]
Some here on Xiaomi Mi 8, Signal 5.24.7. This is really annoying.

**Comment by haffenloher** [comment]
Yes, this is still relevant.

**Comment by cirelli94** [comment]
It's fixed on Google Pixel 3a

**Comment by samueltsw** [comment]
So do in my pixel 6

**Comment by olijg** [comment]
I'm still having this issue on my pixel 9. Also, when I take the phone away from my ear the audio doesn't go back to the original volume.
