### ISSUE TITLE
recurring crashes when opening group chat and one conversation

### ISSUE THREAD

**Issue by erik55** [signalapp/Signal-Android#9047]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- Signal app crashes whenever I try to open a special group chat (since two or three days) and when I try to open a special conversation/chat with one person (since today). That means: Only one single person to person chat affected as far as I know. And one group chat.
- Signal app has all permissions enabled.
- Crash happens on WiFi, mobile data connections (4G), and when internet access is disabled
- Clearing cache and uninstall and reinstall the app (restoring backup with the affected chats) doesn't help
- Rebooting phone doesn't help
- Possibly related to bugs #8807 #8667

### Steps to reproduce
- Open app
- Click on the affected group chat or the affected person to person chat
- App crash

**Actual result:** Can't open and read messages in any of the two affected chats. App asks if app should be restarted or bug report should be sent (I’ve choosen many times to sent the bug report).

**Expected result:** Chat/conversation should be opened and should show all the messages, that have been exchanged in this chat.

### Screenshots
N/A

### Device info

**Device:** Samsung Galaxy S6 (SM-G920F)
**Android version:** 7.0
**Signal version:** 4.47.6

### Link to debug log

https://debuglogs.org/a838818989f8a80f46b5fc4eda3183fcb926b2e6d6046690d78664406bf6a9ac

**Comment by erik55** [comment]
Additional info: I think the problem occurs because of a [vcard](https://en.wikipedia.org/wiki/VCard) was sent (first in the group chat, later in the person to person chat). It are two different vcards, the one has nothing to do with the other. It was also sent by different persons.

I’d like to paste the two contacts (vcards) somewhere, but I am not able to save the vcard file with Signal. The only option is to *add to contacts*. I could do that, but I guess when I import them, the vcard is altered (parsed). I could import the vcard of the group chat on another phone, that is also part of that group chat. Not on the affected phone, of course.

I will paste the vcard that was sent to the person to person chat here from the phone that it was sent.

**Comment by erik55** [comment]
One of the awards (sent in the person to person chat): 

    BEGIN:VCARD
    VERSION:2.1
    N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=4E=61=74=61=6C=69=65=20=61=75=73=20=C3=96=73=74=65=72=72=65=69=63=68=
    =20=28=54=6F=63=68=74=65=72=20=56=69=76=69=65=6E=20=32=30=31=39=20=38=
    =20=61=20=61=6C=74=29;;;
    FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=4E=61=74=61=6C=69=65=20=61=75=73=20=C3=96=73=74=65=72=72=65=69=63=68=
    =20=28=54=6F=63=68=74=65=72=20=56=69=76=69=65=6E=20=32=30=31=39=20=38=
    =20=61=20=61=6C=74=29
    TEL;CELL:+34617153822
    TEL;CELL:+34617153822
    END:VCARD

**Comment by alan-signal** [comment]
Thanks for the report. It looks like I can reproduce by putting device into Español (Canarias). This region does not have a 3 character region code which our code assumes.

We will fix shortly, but for now, put your device into another region and those conversations should load without a crash.

Alternatively, rather than changing your device locale, you can also just put Signal itself into Español as this uses the Spanish region. Ajustes -> Apariencia -> Idioma

**Comment by erik55** [comment]
Thank you, your workaround works. 

I hope for the fix for other people of the group who have the same problem.
