### ISSUE TITLE
Registration not working with Sim Telecom MVNO.

### ISSUE THREAD

**Issue by ivacom** [signalapp/Signal-Android#9049]
Unable to receive verification code either via sms or call. Not receiving any of them.
Sim Telecom Information:
CC: 7 MCC: 250 MNC: 47
NDC: 900 555 00 00 – 900 555 99 99 900 611 00 00 – 900 619 99 99 958 101 00 00 – 958 110 99 99 958 113 00 00 – 958 132 99 99

**Comment by alan-signal** [comment]
Please contact support@signal.org

**Comment by ivacom** [comment]
I tried to contact support two days ago but didn't received any feedback. Is there another channel to communicate with support?
