### ISSUE TITLE
Indicator active still when the reply was sent/canceled

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#9051]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal keeps the reply indicator still when the reply was cancelled/sent.

### Steps to reproduce
- Use the swipe to reply feature.
- Cancel or send the reply.
- The indicator is still there.

**Actual result:** Reply indicator remain after sending or cancelling the reply.
**Expected result:** Reply indicator disappear when the reply is sent or cancelled.

### Screenshots

![image](https://user-images.githubusercontent.com/32582878/65568185-736c4880-df1e-11e9-9870-69cc8b851143.png)

### Device info

**Device:** Samsung Galaxy SM-A705MN
**Android version:** 9.0
**Signal version:** 4.48.1

**Comment by aleb2000** [comment]
That happens when you don't activate "animation duration scale" from the developer options. Although I think it was supposed to go away even with that option disabled. Also in case you are replying to your own message, it will remain out of the screen and that can be very annoying.

**Comment by alex-signal** [comment]
Hi! Thanks for filing this bug report! Turns out `RecyclerView`'s `ItemTouchHelper` doesn't account for this case, but we can work around it.

@aleb2000 "Also in case you are replying to your own message, it will remain out of the screen and that can be very annoying."

^ Could you please elaborate on this? I think I know what you mean, but I just want to be 100% sure.

**Comment by Edu4rdSHL** [comment]
Hi @alex-signal, I'm sure that he mean it kind of behavior when part of the message is  cut off.

![image](https://user-images.githubusercontent.com/32582878/65602463-8eb07580-df69-11e9-8ce1-73d416485b12.png)
