### ISSUE TITLE
GIPHY GIFs don't work

### ISSUE THREAD

**Issue by vertigo220** [signalapp/Signal-Android#9052]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to send GIFs with GIPHY fails every time

### Steps to reproduce
- select GIF with GIPHY

**Actual result:**
Receive error that "An item was removed because it exceeded the size limit"
**Expected result:**
The GIF should attach so it can be sent

### Device info

**Device:** Moto Z Play
**Android version:** 8.0.0
**Signal version:** 4.47.6

### Link to debug log

https://debuglogs.org/f43857af50c0729b0d18724d63b2ab9386f0a868284d6273e5d9dddc0391015e

There are other issues that seem to be related to this, discussing the fact that Signal's built-in size limitation is much lower than that permitted by carriers. However, despite all the discussion and points made in favor of fixing the problem, all of these issues were closed without any indication of a fix or of why they were closed without a fix. And as was pointed out in those other issues, without basic functions like this working similarly to standard text messaging apps, it makes it a lot harder to get people to switch over. And it's frustrating when it wastes time by looking for a GIF only to have it not work. In addition to the fact the size limits should be raised to correspond with those of the carriers, there really should be no limit (or it should be quite high) when sending to another Signal user, since it uses the data connection and shouldn't be subject to carrier SMS/MMS size limitations.

**Comment by johanw666** [comment]
Do you try to send it by mms or by Signal message?

**Comment by vertigo220** [comment]
I assume Signal message. since it's in a Signal-Signal conversation between myself and a friend. I just called him to double-check, because he sends GIFs quite a bit, and he said he almost always sends them through Signal, so apparently he doesn't have the issue. So maybe it's something on my end. I also tried in a normal conversation, with someone without Signal, and it did the same thing there.

**Comment by Paradoxeuh** [comment]
I have exactly the same error, but only with a friend who had signal before, doesn't have it now. The strange thing is, texting is working correctly with him (through SMS as he doesn't have signal anymore), pictures can be sent, but not GIF...It only happens on my side. I use Signal as my main SMS app.
