### ISSUE TITLE
Contact icon color isn't updated after changing it

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9057]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating the color of a contact, there are two issues:
1. The letters in the default contact icon are still in the old color.
2. When going back to the conversation list, the default contact icon has the old color.

### Steps to reproduce
- Open a chat
- Open chat settings
- Change color
- Go back

**Actual result:** The old color is still used.
**Expected result:** The new color should be used everywhere.

### Screenshots
After opening a chat with grey color:
![Screenshot_20190926-095329](https://user-images.githubusercontent.com/22525368/65721019-81020980-e0a9-11e9-97a2-75908fadc72f.png)
After changing the color to purple and going back from chat settings:
![Screenshot_20190926-095325](https://user-images.githubusercontent.com/22525368/65721018-81020980-e0a9-11e9-810f-7e0196e8d1e1.png)

### Device info

**Device:** Oneplus X
**Android version:** 7
**Signal version:** 4.47.6

### Link to debug log
UI issue

**Comment by sarah541** [comment]
With which number should I login?
