### ISSUE TITLE
Feature Request: Add BTC/Crypto payment option to Signal.

### ISSUE THREAD

**Issue by mazieres** [signalapp/Signal-Android#9059]
Telegram and WhatsApp are planning on using the value of their user bases to promote their payment network/token. Wouldn't it be a powerful move to profit from BTC user base to promote Signal ?

Could be non-custodial, interfacing with HW or third-party wallets. No need for wannabee unicorn startup pouring, just a QR code to buy your coffee, and more Signal users !

I looked around and couldn't find any discussion about adding this feature.

**Comment by Trolldemorted** [comment]
The issue tracker is not for feature requests, but for bug reports - feature requests go into the community forum, and a [different kind of energy wasting proof-of-work pedopesos has been shilled there before](https://community.signalusers.org/t/add-dash-cryptocurrency/3581).

**Comment by mazieres** [comment]
Ok, ok, no need to insist it seems. :)
If you've admin rights, please delete this issue !
