### ISSUE TITLE
Built-in emoji are a bit blurry in emoji picker

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9062]
The built-in emoji picker has blurry emojis—perhaps their size is too small for a large screen?

This has been discussed in #3318 but that was 4 years ago and about system emoji.

This might be intended for smaller app size, assuming the screen is far enough emojis look good, just want to make sure that is indeed the case.

### Steps to reproduce
- Open built-in emoji picker.

**Actual result:** Emoji are  a bit blurry.
**Expected result:** Emoji have a greater resolution/quality so they aren't blurry.

### Screenshot

![Screenshot](https://user-images.githubusercontent.com/19972511/65936852-ae8ee000-e426-11e9-8db1-9b5fdb5b26a6.png)

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 10 (`QP1A.190711.020.C3`)
**Signal version:** 4.48.7

**Comment by my-tien** [comment]
For me the emojis are not only blurry, they also have artifacts. In the picker, the message input field and in the sent message.
![image](https://user-images.githubusercontent.com/3898364/103884563-0f53a080-50df-11eb-99cd-8bbd60c1b6ec.png)

I know this seems like an unimportant issue when this project is actually about secure messaging. But it is really hard to convince people to switch because of reasons like that.

**Comment by alan-signal** [comment]
What device is that on @my-tien ?

**Comment by alan-signal** [comment]
@u32i64 do you see this issue yourself still?

**Comment by my-tien** [comment]
Sorry for the missing info:

Device: Sony Xperia X Compact
Android version: 8.0.0
Signal version: 5.0.8

**Comment by u32i64** [comment]
> @my-tien 
> For me the emojis are not only blurry, they also have artifacts.

I think that is tracked in #8651. FWIW, I still observe that issue in Signal 5.1.0 on Android 11, Pixel 3 XL.

> @alan-signal
> do you see this issue yourself still?

To be fair, this issue is quite subjective... but for instance, when viewing an emoji in the original [`People_0.webp`](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/assets/emoji/People_0.webp) file (left) and in a Signal screenshot (right) side by side, the quality is lower in Signal:

![](https://user-images.githubusercontent.com/19972511/103911146-bacc1780-5116-11eb-9b4d-a41bdd0a1956.png)

**Comment by alan-signal** [comment]
This is the Pixel 5 when viewed 1:1

![image](https://user-images.githubusercontent.com/48254818/103916196-850d3b80-50e2-11eb-8611-b86555f46edf.png)

And slightly larger as seen in a message:

![image](https://user-images.githubusercontent.com/48254818/103917392-eeda1500-50e3-11eb-8728-c2ce45cff3a8.png)

Could definitely be sharper, but also very hard for me to notice IRL. Higher res will mean larger APK size, but still I will review when I next touch the emoji stuff.

**Comment by my-tien** [comment]
Tbh, it is very obvious to me every time I open the picker. And it is a problem that I encounter in no other messenger. So thanks for having a look at it!

I wonder why the APK size is of such concern, though. It’s not like you see blurry icons or avatars in other programs just because it saves space, no?

**Comment by bvedant** [comment]
I am having the same issue

Device: Samsung Galaxy S10e
Signal version 5.0.10

**Comment by SeerLite** [comment]
Mine are extremely blurry and the emoji picker is really small (3/4 size of keyboard). Also I think the emojis in the picker are way too big.

![signal-2021-01-14-160200](https://user-images.githubusercontent.com/21978144/104636879-c96c7e80-5682-11eb-8aa4-bbd2b880b673.jpeg)

Device: Huawei Y5 Lite 2017 (uncommon, probably region specific)
Android version: 6.0
Signal version: 5.0.8

**Comment by harry-hart** [comment]
Just adding that I am seeing the same blur as the Huawei above.

Device: Oppo Find X2 Pro
Android Version: 11
Signal version 5.1.9

**Comment by LukeeW** [comment]
Also experiencing this problem. Any updates on this issue?

Device: Samsung Galaxy S6
Android: 7.0
Singal: 5.3.7.1

**Comment by Baloo1** [comment]
Hi, I am also experiencing the problem with blurred emojis. Is there any way I can contribute to fixing this?

**Comment by phaabe** [comment]
I have a question: are emojis part of the APK? They aren't part of the OS?

**Comment by cody-signal** [comment]
There is a no res version in the APK and then we download a higher res version based on your device. I don't think this is still an issue, but if it is please post an updated debug log and screenshot.
