### ISSUE TITLE
No "Save" option available on Documents tab in Android

### ISSUE THREAD

**Issue by brianddk** [signalapp/Signal-Android#9065]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No **Save** buttton available on the Documents tab under Shared Media

### Steps to reproduce
- Open a chat with an attached document (not media)
- Click the triple-dot menu in top right
- Select **All Media**
- Click **Documents** tab
- Tap or long-tap on document, neither produce a **Save** button

**Actual result:** The Android OS attempts to launch an app associated by file type

**Expected result:** According to [the documentation](https://support.signal.org/hc/en-us/articles/360007317471-View-all-media-or-files#android_view_save) there should be a way to produce a **Save** option for un-associated file types.

### Device info

**Device:** LG G6 phone
**Android version:** 8.0.0
**Signal version:** 4.47.7

### Documentation Snapshot
* [As of Oct 2, 2019](https://web.archive.org/web/20191003010017/https://support.signal.org/hc/en-us/articles/360007317471-View-all-media-or-files#android_view_save)

### Similar Issues
* [Add option to store all media elsewhere](https://github.com/signalapp/Signal-Android/issues/8979)
* [Attachments from Desktop Aren't Savable](https://github.com/signalapp/Signal-Android/issues/8352)

**Comment by yasharya2901** [comment]
Where the received are stored? For Telegram and WhatsApp, there's a dedicated folder where everything's stored. I couldn't find the same for Signal.

**Comment by brianddk** [comment]
Looks to be fixed Signal-Android 5.29.7
