### ISSUE TITLE
Signal SMS not handling VCF (Contact Card) sent from iPhone

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#9066]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal SMS isn't handling VCFs sent from iPhone

### Steps to reproduce
- Grab an iPhone that doesn't have a signal. 
- From the iPhone share a contact to an android user who uses Signal as their default SMS/MMS

**Actual result:** You get the file as text, not as a proper contact card.
**Expected result:** Should display as a proper Signal contact card. 
### Note
- If you change your SMS app back to Google Messages the contact translates properly. 

### Screenshots
![wcFTBxH](https://user-images.githubusercontent.com/18274896/66095557-92418f00-e55d-11e9-8889-600c2d4d75a1.jpg)

### Device info

**Device:** Samsung Galaxy Note 8
**Android version:** 9
**Signal version:** 4.47.7

### Link to debug log
https://debuglogs.org/17cedc8fafb3a236cd7bce1bb7c7c6a6e18b96b5059ba472bfc29562a5f03208

**Comment by mlsxlist** [comment]
Looks like a feature request. For Signal messages this has been implemented. For SMS not.

**Comment by Tursko** [comment]
> Looks like a feature request. For Signal messages this has been implemented. For SMS not.

I made this bug report for a friend and he said when he gets an contact card via SMS from an Android user is displays properly.
