### ISSUE TITLE
Cannot receive MMS from non-Signal users

### ISSUE THREAD

**Issue by junitas** [signalapp/Signal-Android#9069]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to receive media messages at all from non-Signal users from within the Signal app. When I set the Android Messages app to be the default SMS app, I *can* receive media messages.

### Steps to reproduce
- Have a non-Signal user send a picture to you
- Have Signal be your default SMS app
- Notice that you can't see any picture

### Device info

**Device:** Moto g6
**Android version:** 9
**Signal version:** 4.48.8

### Link to debug log

https://debuglogs.org/883b3fd08635c07e57773c76a2b3f75039008a155cb8ab50e9721aeaee5778ba

**Comment by junitas** [comment]
Did an uninstall and installed version 4.48.12, issue persists.

**Comment by kikifreena** [comment]
I've also noticed this issue.

**Comment by junitas** [comment]
A few days ago I received a large batch of MMS (pictures and group chats with non-Signal users) that apparently had been sent during the time I was seeing this issue. I can now receive images from non-Signal users.

**Comment by Magent02** [comment]
I've had the same problem for a few weeks not. I am running a Google Pixel 3a on GoogleFi.
I'll get the past few days of incoming group texts in a matter of 2 mins, and then my conversations are out of order and I've missed the timeliness of the message.

**Comment by junitas** [comment]
A few days ago I received another "burst" of these previously un-received MMS messages. This is the debug log from right after:

https://debuglogs.org/d5191396871492b1c1d9edd8acbd144fa01576e942385da67267b17c89c6dde5

I am also on Project FI. 

I'm not sure if this is worth mentioning, but my entire device has been very slow and stuttering recently. After I did a total delete and re-install of Signal, per my comment 13 days ago, the slowness and stuttering went away only to come back the next day. Just mentioning in case this could be a side effect of MMS messages being queued up by the system or Signal?

**Comment by keith24** [comment]
I'm also having this issue on a pixel 2 with Fi.  If I switch to another default SMS app, I don't have the problem, which indicates that it is signal.  I've also noticed messages arriving in bursts, usually a day or so later.

**Comment by ThatGeoGuy** [comment]
I am likewise having issues with a pixel 3 on Fi. However, it seems that #8571 is the same as this issue. Perhaps we should close this one and add more support there.

**Comment by junitas** [comment]
#8571 seems to show in the conversation that an MMS message has been received, but it can't be downloaded/opened. The debug logs on that issue also show `FileNotFoundException` and `MmsException`

**Comment by geoffro10** [comment]
#9013 has identified a problem but no solution as of yet. Appears to be limited to Google Fi. Forcing on to the T-mobile network seems to resolve but is certainly not a permanent fix.

**Comment by AndraSays** [comment]
**I do not have Google Fi** and have this same issue. This has been an issue for me since the beginning of this month at least- complete inability to send or receive MMS from any and all non-signal users. 

I've gone through everything on the troubleshooting page: https://support.signal.org/hc/en-us/articles/360007320211-MMS-Troubleshooting

- Device: Google Pixel XL
- Signal version 4.48.17 (5462)

For me, the timeline correlates to when I updated my phone to Android 10. I know there's another thread about this, but I'm commenting here because it's higher on the list of bugs.

**Comment by junitas** [comment]
Closing as this seems to be a duplicate of #9013, thx for linking @geoffro10!
