### ISSUE TITLE
New messages in muted conversations cause notifications

### ISSUE THREAD

**Issue by mejo-** [signalapp/Signal-Android#9071]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive new messages in muted conversationgs/groups, they cause a notification on my phone *if* I still have other unread messages at that time. In other words, the notification due to unread messages (from non-muted conversations/groups) again pops up and causes a sound/vibration, everytime Signal receives a new message, even though the new message is to a muted conversation/group.

That's particularly annoying if you're in large and noisy groups, muted on purpose but then your phone still keeps vibrating just because you have other unread messages left.

### Steps to reproduce
- Mute a conversation/group
- Receive message in non-muted conversation/group, keep it unread
- Receive message in muted converstion/group
- Watch the notification popping up and your phone vibrating

**Expected result:** Messages to muted conversations/groups should not cause a notification whatsoever

### Device info
**Device:** Xiaomi MI A2 Lite
**Android version:** 9
**Signal version:** 4.48.12

### Link to debug log
It happened plenty of times in the timespan of the following debug log:
https://debuglogs.org/905592d53c6c64f9e94fa64dac4c07f4870e624c4543aca9487a8e10d2aad71fManufacturer

**Comment by chaoscommander** [comment]
I can confirm.

**Comment by ahelwer** [comment]
Reproduced for me too, Android Moto X4 with Signal 4.52.4

**Comment by davidfuhry** [comment]
Still happens on Android 10 (Xiaomi MI A2)
