### ISSUE TITLE
Forwarding attachments that aren't downloaded does nothing

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9072]
If you forward an attachment you haven't yet downloaded (I reproduced with an image) and choose recipient, nothing happens.

Similar behavior is experienced when trying to save the attachment to external storage, but a generic error message is shown instead of saying something like "Download this attachment before saving it to external storage".

### Steps to reproduce
- receive an attachment that is not automatically downloaded (use Signal settings to disable auto download or not have sender in your contacts)
- without tapping the download button, hold to select the media message
- tap "forward"/"save" button on the top of the screen
- choose recipient (if using "forward")

**Actual result:**
- "forward": nothing happens
- "save": generic error message

**Expected result:** Either these buttons should not be present at all, or a specific error message should be shown.

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 10
**Signal version:** 4.48.12

**Comment by riotbib** [comment]
I can confirm this issue.

### Device info
**Device:** Google Pixel 3a
**Android version:** 10
**Signal version:** 4.55.8

**Comment by u32i64** [comment]
Forwarding pending media is now prevented by https://github.com/signalapp/Signal-Android/commit/c6008a4f907151fa47f8307782d4f65cd036be0d, but the "save" button is still present and presents a generic error when used.

**Comment by greyson-signal** [comment]
Fixed in 5.3.3
