### ISSUE TITLE
Signal without Google play services: unreliable receiving of messages

### ISSUE THREAD

**Issue by klues** [signalapp/Signal-Android#9073]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using Signal on LineageOS 16 on a Samsung Galaxy S4. I don't have any Google Services installed, so notifications are running without Google push notifications.

The problem is that receiving of messages is very unreliable. Sometimes it works very well, sometimes not. It seems that Signals fails to receive messages more often after activating and de-activating flight mode, but it's not always the case.

Today (4.10.2019) there were some situations were I wrote a message, my conversation partner replied within a very short time (were I almost certainly had Signal App still open), but I didn't receive the reply! This is very frustrating.

I've followed all steps of https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

I'm sorry that I can't provide "steps to reproduce" since the issue isn't really reliably reproduceable.

### Device info
see debug logs.

### Link to debug log
https://debuglogs.org/20975a7a43acb1ef9f5928863335324d27a782b11141b833ae182f91112bb83c

**Comment by jtracey** [comment]
Likely a dup of #7638. Several community PRs to fix the issue have been left to languish by the Signal devs, unfortunately.

**Comment by klues** [comment]
Yes, seems to be true, thanks for linking.
In fact on my Samsung Galaxy S4 mini, LineageOS 16, no GApps everything works fine.
On Samsung my wife's Galaxy S4, LineageOS 16, no GApps the bug occurs.

I've now installed Open GApps pico on the Galaxy S4, now everything seems to work. But it's a pity that GApps are needed.

**Comment by greyson-signal** [comment]
I believe this was resolved in e3b66dc7e8906b678576c71d01d98aff17c6aefc.
