### ISSUE TITLE
Crash loop on opening

### ISSUE THREAD

**Issue by Foaly** [signalapp/Signal-Android#9074]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal suddenly stopped opening and keep crashing immediately after tapping the app icon. This happened with no apparent cause. The only thing I could see that happened at the time was that I received a lot of messages from a group chat (I saw it later on a paired computer which still works). This behaviour stays even after reboot, forcing the app to close or clearing the cache.

### Steps to reproduce
- tap the app icon to start Signal

**Actual result:** The screen flashes white briefly. The app crashes immediately afterwards
**Expected result:** Signal starts

### Device info

**Device:** HTC One M9
**Android version:** 7.0
**Signal version:** 4.47.7

### Link to debug log
    10-02 23:29:39.030 E/AndroidRuntime(29506): FATAL EXCEPTION: signal-JobManager
    10-02 23:29:39.030 E/AndroidRuntime(29506): Process: org.thoughtcrime.securesms, PID: 29506
    10-02 23:29:39.030 E/AndroidRuntime(29506): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    10-02 23:29:39.030 E/AndroidRuntime(29506): 	at java.lang.Thread.run(Thread.java:761)
    10-03 08:00:35.915 E/AndroidRuntime(10467): FATAL EXCEPTION: signal-JobManager
    10-03 08:00:35.915 E/AndroidRuntime(10467): Process: org.thoughtcrime.securesms, PID: 10467
    10-03 08:00:35.915 E/AndroidRuntime(10467): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    10-03 08:00:35.915 E/AndroidRuntime(10467): 	at java.lang.Thread.run(Thread.java:761)

The crash log goes on like this.

I saw that #8997 and #8781 have very similar crash logs. Just wanted to point out, this issue still exists.

**Comment by brs17** [comment]
I run the beta version of Signal on Android (8.1.0) and after updating this afternoon (4.48.15), just had the same issue start happening to me. This is on a Nexus 5x. The closed issues mentioned by @Foaly suggest that the database has become corrupt. How does this just happen? Is there anything that can be done to help better diagnose this issue? It obviously isn't great if databases are just becoming corrupt on app updates.

**Comment by pankarlox** [comment]
The same thing happened to me today. Everything worked well and suddenly the application stopped working.

### **Device info**

**Device:** Samsung Galaxy A3 2016
**Android version:** 7.0
**Signal version:** 4.47.7
 
### **Link to debug log**

I'm afraid I don't have access to the log.

**Comment by pankarlox** [comment]
> 
> 
> The same thing happened to me today. Everything worked well and suddenly the application stopped working.
> ### **Device info**
> 
> **Device:** Samsung Galaxy A3 2016
> **Android version:** 7.0
> **Signal version:** 4.47.7
> ### **Link to debug log**
> 
> I'm afraid I don't have access to the log.

That's interesting. Signal automatically picked up after the update to the latest version 4.48.17

**Comment by greyson-signal** [comment]
@pankarlox Posting a log could be helpful to verify. Crashes usually stick around longer in the ADB logs.

**Comment by pankarlox** [comment]
@greyson-signal 

https://debuglogs.org/9153903341cfac71c4e5c748a61b8b40e42e04a15365b664bfc00a1898b9abd1

**Comment by greyson-signal** [comment]
@pankarlox Unfortunately looks like we missed the window. I'd say "maybe next time", but obviously I hope that there is no next time :)
