### ISSUE TITLE
Fails when sending SMS to numbers starting with zero

### ISSUE THREAD

**Issue by kjellskogsrud** [signalapp/Signal-Android#9075]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending SMS to short numbers beginning with zero I get "Send Failed, tap for Details"
Many SMS services in Norway uses short 5 digit numbers that begin with a zero (like checking  my bank balance)

### Steps to reproduce
- Open Signal
- Send an SMS to a number starting with 0 (zero)

**Actual result:** Message fails to send
**Expected result:** Message should send normally 

### Device info
**Device:** LG G6 (LG-H870)
**Android version:** 9 Kernel 3.18.120
**Signal version:** 4.47.7

### Link to debug log
https://debuglogs.org/5119888d8fd6dece80efec3b3152a9390a014a3628170595ef8e070d4e57b189

**Comment by igor2x** [comment]
There is limitation in Signal that phone numbers have to be some minimal length.

Can you please as work-around try entering full international format: + 47 + phone number. You may need to remove leading zero. Does this work, maybe not as final solution, but as work-around?

**Comment by kjellskogsrud** [comment]
I have tested these formats and they all fail:
04800
+4704800
004704800

Also I have found that other SMS services that use 4 digit numbers work fine.

**Comment by bme13** [comment]
Normally when you use the international format one needs to remove the leading zero (as igor2x stated) 04800 would then become +474800. Does that work?

**Comment by kjellskogsrud** [comment]
No that does not work. 4800 would be probably be a different service. We use both five and four digit numbers for sms services I Norway. The 5 digit range is 02000 to 09999, so they will always start with a 0.

**Comment by volucris** [comment]
I have the same issue, which also occurs with short Norwegian numbers starting with a 1 (e.g. 19182 for the local blood bank). The +47 is appended and sending fails.

**Comment by kjellskogsrud** [comment]
I tested this again now, and it seems to be fixed, or at least working on my phone.

**Device Info:**
Device: Galaxy S20 FE 5G ( SM-G781B/DS)
Android version: 12 Kernel 4.19.11-23204498
Signal version: 5.28.10

Don't know if it's relevant but I had this issue in other messaging apps that does SMS as well. And most recently I had to text an "OK" back to a cell vendor to confirm that the could move my number. This failed and an I called their support for help. Their tip was to turn of Wi-Fi on my phone and try again. I though that sounded like BS, but it actually worked. That was  a little while ago now, and as I said it seems to work fine in Signal now even with Wi-Fi on. 

I leave this here for info but this issue should probably just be closed.

**Comment by TimoTaikuri** [comment]
I stumbled upon this article because I couldn't send an SMS to a service starting with 0 (020202, a caller/licence plate/whatnot lookup service in Finland) with any SMS capable app, including the one that came with the phone. 

Unbelievably, turning off WiFi worked. I'm using OnePlus Nord 5G today, but this was a problem in my previous phones too. Finally I found a solution! Thanks!

**Comment by manavnagpal08** [comment]
I’m glad to hear that you found a solution! Yes, in some cases, WiFi can
interfere with sending SMS to short codes, as certain carriers route
messages differently over WiFi. Turning it off forces the message to go
through the mobile network, which often resolves the issue.


If you ever run into similar problems, checking with your carrier might
help, as some have specific restrictions on short code SMS.


Thanks for sharing your experience! Let us know if you need any further
assistance.
