### ISSUE TITLE
Signal keeps crashing every time I try to download MMS

### ISSUE THREAD

**Issue by vertigo220** [signalapp/Signal-Android#9081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I keep getting mostly blank bubbles (with the exception of "MMS" next to a down arrow indicating the MMS needs to be downloaded and the text "Error downloading MMS message, tap to retry") when someone sends pictures, since my cell connection is often weak or nonexistent, so the images don't come through. The problem is, earlier when I would tap it to download it, Signal kept crashing, over and over and over. The first time it just crashed silently, sending me back to my home screen. The other times I was presented with the Google crash feedback page, which I submitted a few times. I also captured a debug log (below).

In addition to this issue, Signal should automatically download the messages whenever possible, so if I have reception but don't think to open it and manually download them all (not to mention doing so one-by-one is slow, though I'm still not sure if that's necessary, since I *think* manually downloading one makes them all download), they'll be viewable later. Another issue I have related to this is that when people send messages in a group chat, they often show in a separate conversation just with that person first, then later (I assume once I get good enough reception for Signal to be able to recognize the message was sent as part of the group chat) it will merge into the group chat. This is especially problematic because if I mute the group chat to keep my phone from blowing up, I'll still get notifications from the messages that aren't immediately included in it. I'm not sure if this is an issue with Signal, though, or simply a limitation any app would have with having limited reception.

### Steps to reproduce
- Get MMS while phone has poor signal
- Go to area with good signal and tap download button on MMS bubble

**Actual result:** 
MMS should download, preferably in background and allowing multiple messages to be downloaded simultaneously.
**Expected result:**
Signal crashes. Note this is the first time this has happened, despite having to manually download MMS messages multiple times previously.

### Device info

**Device:** Moto Z Play
**Android version:** 8.0.0
**Signal version:** 4.47.7

### Link to debug log

https://debuglogs.org/c0b19775d5dcc57aa2b5097f8a61ef275bd57f9a30aa432662fb58037d7d22b5

**Comment by vertigo220** [comment]
I just tried this again hoping it was resolved as part of issue #9173, but it's still crashing. Here's the debug log:

https://debuglogs.org/4b4286f4484b189a3cf652086b8d860ed45afe1e5e76a66d5e6248c6fabd604f

**Comment by yate** [comment]
It seems like it's crashing trying to parse the content disposition header in the PDU. This is apparently a [known issue for some MMSC servers](https://github.com/klinker41/android-smsmms/blob/71e3f39c31c6a350eb8c9b8e8600faad42b433b0/library/src/main/java/com/google/android/mms/pdu_alt/PduParser.java#L1682)? There might potentially be a fix by checking the carrier config value`SmsManager.MMS_CONFIG_SUPPORT_MMS_CONTENT_DISPOSITION` [before creating the PduParser](https://github.com/klinker41/android-smsmms/blob/71e3f39c31c6a350eb8c9b8e8600faad42b433b0/library/src/main/java/com/google/android/mms/pdu_alt/PduParser.java#L99)

Alternatively @vertigo220, you could try to update your APN settings to use a different server.

**Comment by vertigo220** [comment]
No option to update it, only to reset to default, which it already is, or add a new one.

**Comment by vertigo220** [comment]
Not sure why this was closed, but it's still doing it. I've had it crash multiple times in the last few days. Very annoying.

**Comment by ToastedBagel** [comment]
Also experiencing crashing when clicking to download MMS messages. Had to switch back to the 'Messages' app to handle SMS/MMS. Using an Android phone, Android 10, Teracube 2e

**Comment by UserX404** [comment]
@ToastedBagel 
Please append a debug log.

**Comment by ToastedBagel** [comment]
https://debuglogs.org/41cf8107c562f4c80fb4afab5b6335a8c75aa2dc2d2355b07f7b6f846a91feb6
Here a debug log
Thanks
