### ISSUE TITLE
Call connection lost when phone switches from wifi to 4G

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9089]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I make a (only tested with audio) while on wifi call and lose wifi, the phone switches to 4G but the call loses connection.

### Steps to reproduce
- Make sure phone is on wifi but has a data plan
- Make a call
- move out of wifi range

**Actual result:** connection lost.
**Expected result:** Connection tranfered from wifi to 4G.

### Device info

**Device1:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.48.16

Device 2: Apple iPhone 8
Signal and iOS version unknown (but I can find out if this is important).

### Link to debug log
https://debuglogs.org/082b5d7c56f9579a706d9869d49bf8d0637cc9e6c59720d6b324ad2a13d50bb9

**Comment by KyleNie** [comment]
Currently Signal's video and voice call don't support IP switch. Same case also happens when you enable/disable a VPN when a call is in progress.
