### ISSUE TITLE
Disappearing "About" section in group conversations

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#9092]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the conversation settings for a group chat, the "About" section is initially visible on the screen, but very quickly vanishes, and the rest of the controls animate up to close the gap. The "About" section will also reappear/revanish if you use something on the settings screen that opens a new window (Notification sound, for example) and then navigate back.

### Steps to reproduce
- Open a group chat
- Tap the overflow menu icon in the top right
- Tap **Conversation settings**

**Actual result:** "About" section is visible for a few milliseconds, then disappears and the controls below animate up.
**Expected result:** "About" section is not visible when conversation settings are opened for a group chat

### Device info
**Device:** Pixel 2 XL
**Android version:** 10
**Signal version:** 4.47.7

**Comment by greyson-signal** [comment]
I don't think there is supposed to be an "about" section, so we hide it. I think you're seeing the animation that results from that. We should probably disable the animation in this case.

**Comment by Herohtar** [comment]
Correct, the section has your contact's phone number in one-on-one conversations, but while it's visible briefly in the group chat it's blank except for the message and call buttons. It shouldn't show at all in that case; it looks bad to be animating away every time the page is navigated to.
