### ISSUE TITLE
Signal keeps stopping repeatedly on Nokia 1

### ISSUE THREAD

**Issue by Mikaela** [signalapp/Signal-Android#9094]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I cannot use Signal at all as Android keeps prompting up "Signal keeps stopping". I have experienced this for past few days ~~and finally through the community forum learned that I may get it to open in Airplane mode and testing various options (WLAN on, mobile off, reverse and clicking the options) I found out that WiFi Calling causes the issue. I do have VoLTE and VoWiFi from my operator and as I am typing this, I see "VoWiFi" logo on top right of the screen.~~

### Steps to reproduce

* Open Signal ~~with Settings --> SMS & MMS --> WiFi Calling -compatible mode enabled~~ 
    * ~~(however I cannot reproduce typing this, maybe because I have gotten the message history for past few days?)~~

**Actual result:** I get a notification on Signal stopping every time I try to open it or receive a push notification.
**Expected result:**  Signal works normally

### Screenshots

\-

### Device info

**Device:** Nokia 1 (TA-1047)
**Android version:** 9 Go Edition
**Signal version:** 4.47.7

### Link to debug log

* https://debuglogs.org/902585c3897c8468b98bcccea24b6860c69107ddce5195c3360bd3e85f2d3f85

I hope it contains the crash. I tried to copy the debug logs in airplane mode, but "select all" selected only the single line and I naturally didn't have network connectivity in airplane mode.

**Comment by Mikaela** [comment]
I edited the issue title and description, because now I appear to have this regardless of the WiFi Calling option state.

**Comment by greyson-signal** [comment]
This will be fixed in 4.50. Thanks!
