### ISSUE TITLE
Progress bar of wrong voice message moves after scrolling in chat

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9096]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While a voice message is playing and the user scrolls up or down, the progress bars of other voice messages move as well.
My guess is, that the "voice message view" is recycled by Android and used again.

### Steps to reproduce
- Have at least two voice message. They must be at least one screen height apart.
- Play the first message
- Scroll to the second
- You still hear the sound of the first message, but the progress bar of the second is moving.

**Actual result:** While a voice message is playing and the user scrolls up or down, the progress bars of other voice messages move as well.
**Expected result:** While a voice message is playing and the user scrolls up or down, the progress bars of other voice messages must not move.

### Device info

**Device:** Oneplus X
**Android version:** 7
**Signal version:** 4.47.7

**Comment by severus-tux** [comment]
This bug is still unaddressed. Signal beta 4.61

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-61-release/14547/60?u=severus-tux
![randomly_changing](https://user-images.githubusercontent.com/21301040/83347644-d763ce00-a343-11ea-9b24-a9e6d3b20aa7.gif)

**Comment by FeuRenard** [comment]
maybe related to #4655

**Comment by mueller-ma** [comment]
Yes, that's exactly what I meant. I didn't find this old issue when opening this one.

**Comment by mueller-ma** [comment]
Fixed in 4.61.X

**Comment by mueller-ma** [comment]
@FeuRenard @severus-tux If you can still reproduce this issue, I'll reopen it again.

**Comment by mueller-ma** [comment]
I can still reproduce this on 4.61.6.

**Comment by mueller-ma** [comment]
Seems to be fixed.
