### ISSUE TITLE
Images from front camera very low resolution from Huawei P20

### ISSUE THREAD

**Issue by ajsteele** [signalapp/Signal-Android#9098]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images taken using the front (ie selfie) camera through Signal are sent at a resolution of 320x640 and display nasty moiré, as though resized with nearest-neighbour.

### Steps to reproduce
- (With a Huawei P20)
- Open the messages with a contact
- Take picture with front-facing camera
- Send

**Actual result:** Recipient phone will display extremely low-res image
**Expected result:** Recipient phone should display image with moderate resolution and quality

### Device info
**Device:** Huawei P20
**Android version:** 9.1
**Signal version:** 4.47.7

**Comment by alex-signal** [comment]
Hi! We did some work on this feature in v 4.49 that will hopefully help your situation.  Please be on the lookout for that version over the next bit and see if it makes an improvement :)

If it doesn't, feel free to say so!

Thanks,
Alex.
