### ISSUE TITLE
Sending location to a contact fails when using microg

### ISSUE THREAD

**Issue by mpatey** [signalapp/Signal-Android#9101]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I tap to send a location, the map appears and allows me to select a location; the selected location then appears in a box ready to send, but there is no "send" button, only a "+" button. I can _almost_ work around the issue by tapping the + and then attempting to send a location again, without having first deleted the draft location. This second time the send button is available, but if you tap it to send only an empty message is sent.

### Steps to reproduce
- Open signal and a conversation
- Tap the blue "+" button and select "Location"
- Choose any location and tap the tick

**Actual result:** Draft image showing location appears ready to send, but the button to send it is not available:

![Screenshot_20191015-212419_Signal](https://user-images.githubusercontent.com/25107300/66869849-2537eb80-ef98-11e9-842d-927894d815ef.png)

### Further steps
- Without deleting draft map of location tap the "+"
- Tap Location and try to send a location again

**Actual result:** This time a send button is available:

![Screenshot_20191015-212503_Signal](https://user-images.githubusercontent.com/25107300/66870122-a2636080-ef98-11e9-9b1a-55c4f3304173.png)

**Actual result:** But if you try to send it a blank message is sent:

![Screenshot_20191015-212513_Signal](https://user-images.githubusercontent.com/25107300/66870161-bf982f00-ef98-11e9-8a5d-5101e678288b.png)

**Expected result:** There should be a right arrow button to allow me to send the location and this button should send the location rather than a blank message

### Device info

**Device:** OnePlus One
**Android version:** Lineage4microg (lineage-16.0-20191007-microG-bacon)
**Signal version:** 4.47.7

### Link to debug log
https://debuglogs.org/9e151dc60daeb28a7b613c80b87d9407659bf733914c2e42b5ad70d78e0d19ff

**Comment by bme13** [comment]
This seems to be caused by microg. Not all required functionality is implemented (yet?). I have the same issue and here's the related response from the developers. https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-43-release/8242/36?u=bme13. Briefly checked your logfile and found the same 'unimplemented Method' message.

**Comment by mpatey** [comment]
I wasn't sure whether to raise the issue here, but I did in the end because sending location works in WhatsApp. In Whatsapp the UI is a bit different in that as soon as the location is chosen it is sent without further user interaction but it works without any problem.

**Comment by greyson-signal** [comment]
As indicated in the linked forum post, not much we can do. Feel free to file an issue with microg.
