### ISSUE TITLE
Time delay buildup during calls, faster during videocalls

### ISSUE THREAD

**Issue by bklebel** [signalapp/Signal-Android#9102]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a time delay which builds up over the course of signal calls. Depending on the nature of the call, it might be noticeable fast, or only later. Delay develops faster in videocalls than voice calls, and also across continents (US, europe) it comes in faster than within europe (inside Austria). I am not quite sure whether I encountered it really within the one country. The magnitude is hard to measure, especially since it is usually not noticed until it is rather big, but it can amount to a few minutes after an hour of calling, in a voice call. in a videocall, things can become much delayed after a few minutes. 
It is not a latency which has a static magnitude, but builds up, terminating and reopening a connection solves the problem just fine, it starts at 0. 
My guess would be that it is device dependet, possibly on the CPU/GPU: Usually, when we notice that the video is quite delayed, switching back to audio only also helps. In this case, one recipient might get all that he missed until then in sort of a 'fast-forward' manner, too fast to coherently follow, but still somehow intelligible, depending on the magnitude of what had already developed. 

### Steps to reproduce
Make a signal call, may be video or voice (faster noticable in video call)
**Actual result:** After some time, considerable delay builds up, it may take a few minutes for one party to hear what the other party has said (and vice versa), however, all that is being said is transmitted, and there is now apparent slowdown noticeable in the talking of a person. 

**Expected result:** no delay, sound and video are transmitted in near real-time, with some occuring latency below one second, comparable to a normal phone call

**accurately measuring it:** I do not have the time/means to do sth like this, but I can imagine one could set up a call, and a metronome on one side, or some slow frequency stuff, and see whether the frequency is exactly the same on the other side, and how much they differ/run away from each other. in the end it is a small frequency shift, which destroys coherence over time. 

### Device info
Party 1:
**Device:** Sony Xperia Z4/Z3+ (E6533)
**Android version:** 7.1.1
**Signal version:** 4.47.7

Party 2
**Device:** Galaxy A7 (2018) - model number: AM-A750 FN/DS
**Android version:** 9
**Signal version:** 4.47.7

### Link to debug log
Party 1:
https://debuglogs.org/13cab77bc52f19b9c560b38dbeb39dc0b77ae0fe116356326e893ae5b1452b9e

Party 2:
https://debuglogs.org/c7db09c180a8dfa87eb809a1df1f691c8e9e6240f50c35abd566139bd74cfea9

One respective videocall happens at approximately GMT+1 23:36  (immediately start with call, timezone of party 1) on 2019-10-13, the delay amounted in the end to a few minutes, (1-4 min, bad estimate)

**Comment by azzizzi** [comment]
It seems I have the same issue but the problem is that the other phone seems ti see the incoming call on the top of the phone but the connection is not done and in fact the caller doesn't even see the other phone is ringing and so the call times-out....

**Comment by bklebel** [comment]
I am not sure we have the same issue - in my case, the call is correctly established, and nothing times out at any point. My problem is rather that the call does NOT time out (or any party is notified in any way), when the app could detect that the other party is lagging behind significantly

**Comment by jonconwayuk** [comment]
I have this issue as well calling between Samsung Galaxy S20 Plus and an iPhone 7. Call stutters then replays content in a "fast forward" manner.
