### ISSUE TITLE
Issues with Signal calls btw android

### ISSUE THREAD

**Issue by azzizzi** [signalapp/Signal-Android#9103]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi @greyson-signal there is some issues with SIgnal calls btw android phone. If I start a call with the other person the other person sees from the top of the phone (the part where there is the clock and the battery level) that someone is calling, but 
1. the phone doesn't ring 
2. we cannot answer and if I answer it writes answering, but nothing happens..

### Steps to reproduce
- call someone

**Actual result:** I cannot speak with this person
**Expected result:** should be able to call this person and speak with him

### Device info
I will send you on Signal can you drop me a phone number?

### Link to debug log
Same here I will send both of debug logs on Signal

**Comment by westonal** [comment]
Can you at least put the version of signal here?

**Comment by greyson-signal** [comment]
There's some active development in this area recently. Please re-open if this is still an issue. You can send a debuglog to greyson@signal.org.
