### ISSUE TITLE
Allow to send and receive payments

### ISSUE THREAD

**Issue by onny** [signalapp/Signal-Android#9104]
Hey Signal-Devs,
it would be cool to be able to send and receive payments with Signal. I'm not sure which open standards or APIs could be used in the banking system.
On the other side, in Europe we now have PSD2 directive and I could send money with my bank account instantly and without second factor (for amounts up to 30€).
Sending small amounts to other users who also enabled the banking feature would be really cool. I guess all other messaging eco-systems will implement this feature sooner or later.

Best regards,
Jonas

**Comment by Tursko** [comment]
This is for issues and not feature requests. Go to the forums if you'd like to request a new feature.
