### ISSUE TITLE
Signal crashes when clicking camera icon

### ISSUE THREAD

**Issue by lwesterhof** [signalapp/Signal-Android#9106]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Clicking the camera icon in a conversation crashes Signal.

### Steps to reproduce
- Open conversation
- Click camera icon

**Actual result:** Crash
**Expected result:** Open camera

### Device info

**Device:** Xiaomi Mi A2 Lite (daisy)
**Android version:** 9 (V10.0.14.0.PDLMIXM, PKQ1.180917.001.V10.0.14.0.PDLMIXM)
**Signal version:** 4.49.0 (5472)

### Link to debug log
https://debuglogs.org/d988e69d1ecec633de7eb18f23839cda9eed0afeb59c075aa8e29f808e8c9304

`2019-10-18 08:30:04.674 CEST E UncaughtExceptionLogger: java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases.`

**Comment by minnmann** [comment]
Same exception here, also with newest beta 4.49.2.
https://debuglogs.org/7202a49a52882ea4f967fdeb7567f9434740689f49b4b1356c2d8526b412b94a

Moto G5, Android 8.1

**Comment by RiseT** [comment]
Still crashing with 4.49.3,
https://debuglogs.org/54e7f2ccab46216eeca502169e27bd82a66e958e81c18c993ae8e2aba5ce8d5c

Moto G5, Android 8.1.0
