### ISSUE TITLE
Consider adding a black theme or making the dark theme black.

### ISSUE THREAD

**Issue by NANASHI0X74** [signalapp/Signal-Android#9107]
This was something I was considering doing a PR for (also for Hacktoberfest :p) but I discovered that there has already been one for that which was rejected (#8466). This is disappointing - many people including me have oled displays which would benefit from black pixels because those areas in the display would not be illuminated thus saving power and looking nicer. Please reconsider that decision.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by charsi** [comment]
Forum thread here - 
https://community.signalusers.org/t/restore-black-background-as-dark-theme/4571/17
