### ISSUE TITLE
Photos in the dark overexposed

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9108]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I take a picture in a dark room with the flash enabled, The preview looks good, but the picture is overexposed. This is a reproducible and consisted outcome. All pictures taken in the dark are severely affected, and thus pretty useless.

### Steps to reproduce
- Turn on flash on either automatic or always on.
- Take a picture in a completely dark room with a lot of white objects or with white walls

**Actual result:** The flashlight turns on to start focusing and to show a preview. Initially the preview seems overexposed, but in less than a second the preview is adjusted and the picture looks good. The flashlight now turns off, and than on again to take the actual picture. This time however the camera starts all over again, but the picture is taken before the adjustment takes place. The result is an overexposed image, while the preview looked just fine.
**Expected result:** Signal should remember the adjustment made for the preview and immediately apply them when taking the picture. 

I can imagine there are some API calls involved, but the preview proofs a good picture should be perfectly possible if the timing is different or if the camera configuration is preserved crossing that dark moment.

I also wonder why the light stays on so long.

### Screen captures
Following below is the resulting camera image Signal sends to my contacts
![The resulting camera image Signal sends to my contacts](https://user-images.githubusercontent.com/34976212/67626966-d0c42400-f853-11e9-9e40-4f1e201c826c.png)

Following below is a screen capture of the preview taken when the camera was in the process of taking a picture. Right after this screen capture the flashlight turns on, than turn on again and then the images is captured. Right before this screen capture I had just pressed the capture button and initially the previews was overly bright but it quickly tuned to a proper brightness
![A screen capture of the preview taken when the camera was in the process of taking a picture. Right after this screen capture the flashlight turns on, than turn on again and then the images is captured. Right before this screen capture I had just pressed the capture button and initially the previews was overly bright but it quickly tuned to a proper brightness](https://user-images.githubusercontent.com/34976212/67626967-d15cba80-f853-11e9-964e-90e10d8f2915.jpeg)

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9.0
**Signal version:** 4.49.1

**Comment by Meteor0id** [comment]
I am not seeing the light stay on this time, but the overexposure still happens.
https://debuglogs.org/266e603500bed79b2958b931e99517da761bd37f5e2fc76b9394eebc827c325f

**Comment by alex-signal** [comment]
Thanks! I've filed a bug here, feel free to star or add any other information you think is relevant. https://issuetracker.google.com/issues/143523403

**Comment by alex-signal** [comment]
Hey @Meteor0id, Google Issues people are asking for a full bug report.  Is this something you'd feel comfortable adding to the issuetracker bug? Details are here: https://issuetracker.google.com/issues/143523403#comment5

**Comment by Meteor0id** [comment]
Hi, I am already on it. Sadly these logs contain some personal information (a list of apps I use etc). But that's how this goes I guess.

Alex Hart <notifications@github.com> schreef op 1 november 2019 14:58:57 CET:

**Comment by Meteor0id** [comment]
Very disappointed with the guys at Android. They expect me to disclose a full debug log on a public issue tracker under questionable terms about its storage and usage. This would be a significant violation of my privacy. This log by default contains my exact location, my wifi networks, a list of all my apps and more. Although I am very willing to provide help to resolve this issue, I do not have a device which I can comfortably take a debug log from.

My hope is maybe someone here can reproduce this issue on a test device, or knows how to redact their own Android log before submitting it.

I have carefully studied what it would mean for me to upload the debug log, but concluded it really does go too far since I don't posses the knowledge to properly audit what I am uploading.

**Comment by alex-signal** [comment]
It's all good, you should do what you feel is in your best interests.  Looking through their issue browser, I can see other people complaining that the flash is happening too early and other issues.  The beta is out in December, so hopefully that improves things.  Thanks for your time!

**Comment by giupardeb** [comment]
Hi guys, I have two devices: Redmi note 4x and Redmi note 9S, both with signal 4.76.3. The first one has Android11(with ArrowOS custom rom) the second one has Android10(Stock miui ROM). This is the photo taken in the dark with flash on Note9s:
![image](https://user-images.githubusercontent.com/4471950/99231784-616bfa00-27f1-11eb-8a11-5c68ec49b008.png)
 totally white! 
On the Redmi note 4x, I don't see the problem, (maybe little overexposed, but acceptable)
