### ISSUE TITLE
Send action fails (error) when selecting an image from Gallery which has already been sent

### ISSUE THREAD

**Issue by Wikinaut** [signalapp/Signal-Android#9109]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending error when selecting an image from Gallery which has already been sent

### Steps to reproduce
1. send an image to a contact (ok)
2. send this image a second time to this contact, or a different contact or group: **send action fails**

### Device info

**Device:** Huawei P smart 2019
**Android version:** 9
**Signal version:** 4.49.2

**Comment by greyson-signal** [comment]
Can you please post a debug log? I'm having trouble reproducing this.

**Comment by Wikinaut** [comment]
How to send that address to you in a secure way?

**Comment by greyson-signal** [comment]
Most people (including myself) feel comfortable posting them publicly, as they don't contain anything like phone numbers or message, but you can also send it via Signal to one of my test numbers: 1 610 549 1426

**Comment by Wikinaut** [comment]
This is the effect when I try to send an image from my gallery a second time. I does not matter whether the recipient is the same or a different one, it only matters if or if not the image is present in any communication.

* After deletion of the all sent images, sending works, always only for the first send action.
* Effect is strictly reproducible.
* Please also notice the **incomplete** (partial) image -- I noticed this now and then before filing this issue; it may be a related problem, perhaps a memory corruption/NPE.

![Screenshot_20191019_200648](https://user-images.githubusercontent.com/1151915/67149502-393b6000-f2ac-11e9-8df3-46e14f98944f.jpg)

**Comment by PiCob** [comment]
I guess I reproduced it:
https://debuglogs.org/ff64644a64f707ebb8de67f8231e08547fc492d9ffd2fb76074fe7d6359374ff

**Comment by chynric** [comment]
I can also reproduce the same like Wikinaut. 

- Only forwarding of an already sent image or images without adding additional pictures works 
- Choosing already sent images with the image picker sending will fail

### Device info
**Android version:** 9 
**Signal version:** 4.49.3

### Link to debug log
https://debuglogs.org/d185cee5844b9103175bdb4dbcea15df6ac404743cbc692dba0b15a3c01c65f6

**Comment by Wikinaut** [comment]
Still present in Signal 4.94.4 (should be fixed in that version, shouldn't it?).

**Comment by greyson-signal** [comment]
@Wikinaut Is this happening with the same photo you already had problems with, or are you trying this with a fresh photo? If it's the same photo from before, it may be in a bad state from the previous bug (in which case I could push a migration in the next release). If it's a completely new photo you've never sent before, then, well... I didn't fix the original bug then :) Either way, can you send me another debuglog?

**Comment by PiCob** [comment]
I, for one, can't reproduce it anymore. The only thing I noticed, is, however, that the "All media" gallery contains images twice (shouldn't they get de-duped there, too?).

**Comment by chynric** [comment]
Can't reproduce it either with fresh photos. Thanks for the fast fix greyson.

**Comment by Wikinaut** [comment]
@ all, yes, may be, it's a problem with images which has been sent elsewhere. I have noticed - but for already a while - another problem with only the local view (at sender's site) of sent images - now and then the local "copy" is cropped in the lower half or lower quarter:

Please can someone let me know, if you have seen such an effect? I think, I have to file a new issue for this (older) problem:

(image is redacted in the upper part):
![grafik](https://user-images.githubusercontent.com/1151915/67277275-c65a0100-f4c6-11e9-9ead-ad4c80abd929.png)

**Comment by aleb2000** [comment]
@Wikinaut I also see the glitch of the previews sometimes.

**Comment by Wikinaut** [comment]
@greyson-signal I wanted to contact you and to send you a recent debug log after a recent "image glitch" - but your test signal number appears to be disconnected from Signal. Pls. advice.
