### ISSUE TITLE
Video recording not working if animations are disabled

### ISSUE THREAD

**Issue by aleb2000** [signalapp/Signal-Android#9110]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With animation disabled through accessibility options, video recording with Signal camera doesn't work (if I enable the animator duration scale the video is correctly recorded).

### Steps to reproduce
- Select "Remove animations" from Accessibility options
- Record a video with Signal camera

**Actual result:** After some seconds a blank video (0 s length) screen appear.
**Expected result:** The video recording is started.

### Device info
**Device:** Samsung S7
**Android version:** 8.0
**Signal version:** 4.49.2

### Link to debug log
https://debuglogs.org/19c5227b1f381857369903cccc8b72bc26bb0b6f322d2f933d0fff373341d555

**Comment by Edu4rdSHL** [comment]
I have exactly the same issue.

Device: Samsung A70
Android version: 9.0
Signal version: 4.49.3

Link to debug:

https://debuglogs.org/607d152a56f9ee8fc8b8404794f664d516829cb6de5ea1ccba922df52cb0e25f

**Comment by alan-signal** [comment]
We do not support developer options. But I recreated with Accessibility options. Updated the report to reflect that.

**Comment by aleb2000** [comment]
Fixed in 4.49.5
