### ISSUE TITLE
Album thumbnails show on other images

### ISSUE THREAD

**Issue by aleb2000** [signalapp/Signal-Android#9111]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If the older media of a conversation is an album, the thumbnails of this album are shown the first time I open any photos from this conversation.

### Steps to reproduce
- send an album (multiple photos at once, must be the older media of the conversation)
- send another picture (single or album)

**Actual result:** The thumbnails of the first album are shown in the bottom left.
**Expected result:** No thumbnail (or the correct thumbnails of the new album) are shown.

### Device info
**Device:** Samsung S7
**Android version:** 8.0
**Signal version:** 4.49.2

**Comment by PiCob** [comment]
Probably related: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-49-release/9724/81

**Comment by jpds** [comment]
I noticed this started happening after 4.49.0.
