### ISSUE TITLE
Home screen shortcuts missing

### ISSUE THREAD

**Issue by fastest963** [signalapp/Signal-Android#9112]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Long pressing on the Signal icon on my home screen no longer offers conversation shortcuts. Existing home screen shortcuts open Signal and an "Invalid Shortcut" toast message appears. 

### Steps to reproduce
- Long press Signal icon on home screen

**Actual result:** I only see options to Pause App and App Info.
**Expected result:** I expected conversation shortcuts to appear and for existing shortcuts to work. 

### Screenshots

![Screenshot_20191019-134718](https://user-images.githubusercontent.com/112555/67149931-0034c880-f277-11e9-9922-eb3ab2fd8e7e.png)

### Device info

**Device:** Google Pixel 3
**Android version:** 10 (QP1A.191005.007)
**Signal version:** 4.48.17
**Google version:** 10.73.7.21.arm64

### Link to debug log

Unfortunately I deleted the conversation shortcut before realizing they were gone and I couldn't recreate it so I can't get a debug log.

**Comment by alan-signal** [comment]
You can add a conversation shortcut from the menu inside the conversation.

**Comment by alan-signal** [comment]
> Existing home screen shortcuts open Signal and an "Invalid Shortcut" toast message appears.

Reopening for this.

**Comment by fastest963** [comment]
> You can add a conversation shortcut from the menu inside the conversation.

Ah, so long pressing Signal icon should no longer show recent conversations?

Also, to clarify, if I add a shortcut via the (new?) "Add to Home Screen" option in a conversation the shortcut works. But, shortcuts made via the Signal icon method didn't work.

**Comment by greyson-signal** [comment]
What do you mean "shortcuts made via the Signal icon method"?
To the best of my knowledge, we never had launcher shortcuts. Were you using any custom launcher before?

**Comment by johanw666** [comment]
The only thing I notice is that clicking on an existing shortcut now opens Signal but does not go to the conversation. Re-creating the shortcut works.

**Comment by greyson-signal** [comment]
Will be fixed in 4.50.
