### ISSUE TITLE
Ask separately for Microphone and Camera permissions

### ISSUE THREAD

**Issue by gopherit** [signalapp/Signal-Android#9113]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot simply make a secure Signal audio phone call without also granting the Camera permission.

### Steps to reproduce
- Open a conversation thread in Signal.
- Tap on the phone icon.
- Observe prompt asking for both Camera and Microphone permissions before the call can be placed.

**Actual result:**
Placing an audio-only call becomes impossible without also granting the camera permission.

**Expected result:**
The camera permission should only be asked when either 1)  an audio call is turned into a video call by pressing the camera button or 2)  a video call is placed from the get-go.

### Device info
**Device:** Google Pixel 2 (everything stock)
**Android version:** 10, October 2019 security patch
**Signal version:** 4.48.17

**Comment by u32i64** [comment]
There is already a [feature request](https://community.signalusers.org/t/cryptocalls-should-not-demand-video-permission-just-audio/1759?u=u32i64) for this on the forum.

In short, this limitation is caused by WebRTC, which Signal currently uses for calling.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
