### ISSUE TITLE
Enhanced camera video recording not work on Xiaomi 4X

### ISSUE THREAD

**Issue by ikino** [signalapp/Signal-Android#9117]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Enhanced camera video recording not work on Xiaomi 4X, only take photo. On Samsung S7 and Motorola g5s+ it work ok.

### Steps to reproduce
- open conversation
- click camera icon
- hold shoot button

**Actual result:** after second it take picture while shoot button still hold

**Expected result:** record video

### Device info
**Device:** Xiaomi 4X
**Android version:** 7.1.2
**Signal version:** 4.94.4

**Comment by Genis-Sage** [comment]
Hey @ikino

I think this is the reason
Build.VERSION.SDK_INT >= 26 && MemoryFileDescriptor.supported();

When i understand it right, the feature is only supported on Android 8 (which is API 26) is and onwards.

**Comment by greyson-signal** [comment]
Yes, apologies, we don't currently support video recording on your device.
