### ISSUE TITLE
[Beta] Clicking on image briefly shows previous image

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#9121]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Clicking on an image in a chat with multiple images (not album) causes Signal to briefly slide the previous image to the left.

### Device info

**Device:** Moto G6
**Android version:** 9
**Signal version:** 4.49.5

**Comment by guimspace** [comment]
I have the same issue and made [this video](https://imgur.com/a/U6GjbQ7) to illustrate it.  

- [debug log](https://debuglogs.org/158dec33046fbdefaef66eed75999e73b960ae7ec3a479e898413070f176fa59)
