### ISSUE TITLE
URI parsing differs between Android and Desktop app

### ISSUE THREAD

**Issue by Drumstickx** [signalapp/Signal-Android#9122]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages that contain a URI with a trailing parenthesis are handled differently by the Android and the Desktop app.

### Steps to reproduce
- Compose and send a message that contains a URI with a trailing parenthesis to yourself via the note to self feature (irrelevant whether it is sent from the Android or the Desktop app)
- Open the note to self conversation in the Android and in the Desktop app
- View and open the URI

**Actual result:** The behaviour differs between the Android and the Desktop app. For instance, when sending `Test (https://github.com/signalapp/Signal-Android/)`, the URI is detected and opened as follows:
- Android: `https://github.com/signalapp/Signal-Android/)`
- Desktop: `https://github.com/signalapp/Signal-Android/`

**Expected result:** The behaviour of both apps should be the same.

I presume that trailing parentheses could be used for detecting the end of the URI as they should by [RFC3986](https://tools.ietf.org/html/rfc3986) be percent-encoded in URIs. However, this is open for discussion.

### Screenshots
Android:
![signal-android](https://user-images.githubusercontent.com/9080610/67374527-91f74b00-f581-11e9-9c97-e18e36c1a629.png)
Desktop:
![signal-desktop](https://user-images.githubusercontent.com/9080610/67374780-f914ff80-f581-11e9-9367-d7e96aed58f4.png)

### Device info
**Device:** Xiaomi Mi A2
**Android version:** Android 9.0
**Signal Android version:** 4.48.17
**Signal Desktop version:** 1.27.4

**Comment by greyson-signal** [comment]
We use Android's built-in link identifier. I don't think it's a necessity for Android + Desktop to be identical around link edge cases like this.
