### ISSUE TITLE
Scrolling text input field causes keyboard to open

### ISSUE THREAD

**Issue by vertigo220** [signalapp/Signal-Android#9123]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a conversation, if you type a long message so it overflows the message text field, then close the keyboard so you can see more of the conversation and try to scroll through the message you've typed, ~90% of the time the scrolling activates the text box, which causes the keyboard to pop back up, which makes everything jump around, causing you to not be able to see much of the conversation anymore and often causing accidental typing in the box if you quickly try to scroll again and end up swiping on the keyboard when it pops up.

BTW, I wasn't sure if this would be considered a bug or not, and it may not even have anything to do with Signal and might just be an Android issue.

### Steps to reproduce
- open a conversation
- type a long message
- close the keyboard
- swipe up/down in the text field to scroll it

**Actual result:** 
Keyboard opens as if text field was tapped.
**Expected result:** 
Text field should scroll without opening keyboard, since field wasn't tapped.

### Device info

**Device:** Moto Z Play
**Android version:** 8.0.0
**Signal version:** 4.48.17

**Comment by greyson-signal** [comment]
This is just standard Android TextView behavior, sorry. Confirmed the same type of thing will happen in other apps. On my Pixel 3 it isn't as easy to trigger as you described, but each manufacturer could alter the behavior.
