### ISSUE TITLE
issue receiving messages over cellular network

### ISSUE THREAD

**Issue by gbiagomba** [signalapp/Signal-Android#9128]
Hello,

So I've had an issue with signal and a few colleagues have experienced this too. I posted the issue once before and am back again. But I've noticed signal doesn't always receive messages over the cellular network even when I have good signal. However if am on WiFi signal will receive messages as soon as the user sends them. I have Verizon, my colleagues are on AT&T and Sprint respectively. They too have noticed the same observations. I believe I am running the latest version of signal 4.48.17 (5462). Below is a link to my log file.

https://debuglogs.org/dc1d2c03a333dcc8160cf0e84691b7b27933e2a94e8d204a44a1081340c87bbd

**Comment by Meteor0id** [comment]
please change the title to "issue receiving messages over cellular network"

**Comment by gbiagomba** [comment]
@Meteor0id understood
