### ISSUE TITLE
In-App video capture doesn't work 

### ISSUE THREAD

**Issue by sweah82** [signalapp/Signal-Android#9129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I try to take a video with the new feature, I get a freeze frame right after starting to press the video/picture button. After releasing the button and waiting some seconds, I see the ‘send video’ screen, but the video is empty and there is nothing sent when I hit the button. After the first try, the picture/video screen stays BLACK. But there are all buttons visible. 

### Steps to reproduce
- go to a conversation
- hit the in-app camera button
- press and hold the shutter
**Actual result:**
I get a freeze frame and after releasing the shutter, there is a pause, then I see the 'send video/picture' screen. If I hit send, I am back in the conversation, no video sent. 
**Expected result:**
A video should be recorded and sent

### Device info

**Device:** Samsung A3 2017 
**Android version:** 8.0.0
**Signal version:** 4.49.9

### Link to debug log ###
https://debuglogs.org/db1102bcff762d782e10adbd5e58a9933550c9f7fc451eae1d6dbc02d90c8b08

**Comment by greyson-signal** [comment]
So your camera is in a "legacy" state where we can't use a mixed image/video stream. That means we have to switch to video mode when recording starts, which can take some time, hence the black screen. I realize this may cause a lot of confusion, and we aren't doing a good job supporting that mode, so for now we're just going to disable video recording for devices like this. Apologies, I'm sure this isn't how you wanted us to fix it :) But if I'm being honest, to properly support these devices would require a totally different UX with a separate image/video toggle. Hopefully we'll be able to improve support down the line :)
