### ISSUE TITLE
Phone back button does not work after contact is created

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#9131]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a contact is created the 'back/return' button on the phone does not work. 

### Steps to reproduce
- have a user who is not in your address book send you a message
- receive the message. a popup within signal appears with three options. choose to add the new number to your contacts. 
- follow the flow to the end. When trying to go back to the chat window the back/return button on the phone does not work. 

**Actual result:** I'm kinda stuck. The back/return function within the Signalapp itself works though (I believe)
**Expected result:** Button should work

### Device info

**Device:** Xiaomi Mi A1
**Android version:** lineage_tissot (Android 9)
**Signal version:** Signal 4.49.9

### Link to debug log

https://debuglogs.org/866d5a0927689654649a0ebe79f74047251724cb70dc1449ad92c089fc49c313

**Comment by alan-signal** [comment]
> When trying to go back to the chat window the back/return button on the phone does not work.

When you add to contacts that launches your phones contacts app. If you are stuck in there, that is a problem with your contacts app.

**Comment by halb9** [comment]
Here is the workflow. 
![01](https://user-images.githubusercontent.com/18451020/68018469-230ca700-fc91-11e9-9831-0ba14b2bbcfe.jpg)
Get a message from someone who is not in the contact list. Click 'Add to contacts'. 

![02](https://user-images.githubusercontent.com/18451020/68018537-459ec000-fc91-11e9-95f0-1724d81b0c39.jpg)
Click 'Create new contact'

![03](https://user-images.githubusercontent.com/18451020/68018603-6d8e2380-fc91-11e9-8d67-f75b545666d3.jpg)
Enter name etc and click save in the top right. 

![04](https://user-images.githubusercontent.com/18451020/68018860-1b013700-fc92-11e9-80e3-d0631c5911a0.jpg)
The circled button is now dead. The back button in the top left works though. 

https://debuglogs.org/0b3a2304ea0f80768cd51fb4469044a6b6b37a25c0388174e31a88f9cd426853
