### ISSUE TITLE
Duplicate contacts shown in 'message details'

### ISSUE THREAD

**Issue by an0n7mous3** [signalapp/Signal-Android#9132]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm in a group chat with 4 other people. One of these people is someone I do not have in my contacts list. So instead of their name, only their phone number is displayed. When clicking on "message details" for any message I've sent, there is a list of the contacts in the chat who have read the message. The contact which I do not have in my address book is on the second slot of this list. 

The problem is this: When opening this "message details" page for the first time, the first contact on this list will not have his name displayed. Instead, it displays the phone number of the second contact. Thus, the list will show two instances of the same contact in both slot one and two, while the 3rd and 4th slots display the other contacts normally. 

When exiting this page, and again re-opening it, then problem fixes itself and the first contact is displayed normally in the list. This problem remains fixed until exiting the app and re-opening it, where this error can be re-discovered.

### Steps to reproduce
- Enter a group chat in which one of the users is a person who you do not have in your contact list
- Open "message details" for any message you've sent
- Observe the list of names of users who have seen the message

**Actual result:** Slot 1 and 2 display the same phone number, until exiting and then reopening the "message details" page.

**Expected result:** Slot 1 should show a different contact, and slot 2 should be the one with just the phone number

### Device info

**Device:** Google Pixel 2
**Android version:** 10
**Signal version:** 4.48.17

**Comment by greyson-signal** [comment]
This is fixed in 4.49.x, which is in beta/rolling out to production. Thank you!
