### ISSUE TITLE
unexpected behavior when making attempt to contact a blocked contact

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9140]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you have blocked someone (but you have not been blocked) and you still attempt to reach that person, some unexpected things can hapoen which can lead to the idea that blocking only works one way. These are hiwever bugs, it only seems like blocking can be circumvented, but in fact if you have blocked someone, he also won't receive anything from you.

This report actually covers two bugs:
1. If you call the blocked person, it seems to work but doesn't. The call starts and keeps attempting to connect witjout a warning that it never will connect.
2. If you select a message, the composebar is no longer hidden and you can attempt yo send a message. Even worse, it looks like the message was both delivered and read, while in fact you have blocked this person and that also means you cannot send to this person. That message had not been send.

Additionally one tester (Johan) mentions that he still gets a notification after being called telling him he was called, even though he was blocked. We will attempt to reproduce and add a debug log of his as well if we can.

### Steps to reproduce
- Block John
- call John
- select a message in the chat, and note your composebar is back. Even after unselecting.
- write a messege and send. Note it shows as read. It can't be read, it wasn't even send.

### Screenshots

![signal-2019-10-29-214929](https://user-images.githubusercontent.com/34976212/67810090-3570c000-fa9a-11e9-93de-8c3756279ec8.png)
![1572384215541](https://user-images.githubusercontent.com/34976212/67810395-d2cbf400-fa9a-11e9-9d0b-855d01496387.jpg)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 9.0
**Signal version:** 4.49.11

### Link to debug log

https://debuglogs.org/c438fdd62eda32cdd45363fca306f4a5ef77ef22b6dc861a16f54c618e63335f

**Comment by johanw666** [comment]
> Additionally one tester (Johan) mentions that he still gets a notification atter being calked telling him he was called, even though he was blocked

Perhaps worth mentioning that I was calling from an Android 6.0.1 device, the blocked device was running Android 5.

**Comment by u32i64** [comment]
> 1. If you call the blocked person, it seems to work but doesn't. The call starts and keeps attempting to connect witjout a warning that it never will connect.

I think it is worth mentioning that this works "correctly" in Signal iOS, which prompts unblocking 
the callee before attempting to call.

> write a messege and send. Note it shows as read. It can't be read, it wasn't even send.

During my testing, when Signal Android `4.49.11` sent a message this way to Signal iOS `2.45.0.24`, it was sent, received, and could be read just as usual.

**Comment by Sgn-32** [comment]
There was a change in a newer version as 4.49. I didn't found the commit for this, but the audio call button, the video call button isn't disabled when a contact is blocked, also no possibility for text input.
