### ISSUE TITLE
[Brazil] Verification SMS never arrives for numbers of a specific carrier

### ISSUE THREAD

**Issue by o-alquimista** [signalapp/Signal-Android#9141]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The SMS that carries the verification code for registration never arrives on my number, which belongs to the Correios phone carrier. On TIM carrier phone numbers, the SMS arrives instantly. A friend of mine cannot register because their number is Correios too.

I've tested 2 Correios numbers and 2 TIM numbers.

The Correios numbers commonly start with 92000 or 92001. TIM numbers are more diverse, but normally 99xxx, 98xxx, 97xxx...

**Actual result:** The SMS never arrives
**Expected result:** The SMS should arrive

### Device info

**Device:** Motorola Moto G4 Play (Codename: Harpia)
**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.48.17

### Link to debug log

Cannot access that. Problem keeps me from creating an account.

**Comment by o-alquimista** [comment]
I no longer use the affected carrier (Correios), so I can't provide any further information.

**Comment by lalongooo** [comment]
Should this be closed @greyson-signal ?
