### ISSUE TITLE
Disappearing messages don't disappear when quoted in a non disappearing message.

### ISSUE THREAD

**Issue by VB2095** [signalapp/Signal-Android#9142]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Disappearing messages don't disappear when quoted in a non disappearing message.

### Steps to reproduce
- Set disappearing message for any time
- Send a message
- Unset disappearing message
- Quote (slide to answer, on click answer) the disappearing message (before it disappear)
- Answer it
- Send

**Actual result:** The disappeared message is still in quote of the answer with a message (when in french, not in english) saying that the original message is not possible to be found but still appearing in the quote. 

**Expected result:** The disappeared message should not be appearing. Only the "not possible to find original" should be there.

### Screenshots

![20191030_092359](https://user-images.githubusercontent.com/15260535/67841109-9b3f6500-faf7-11e9-9008-ca2733f34902.jpg)

![20191030_092334](https://user-images.githubusercontent.com/15260535/67841086-9084d000-faf7-11e9-8cc6-cf3a129327cc.jpg) 

### Device info

**Device:** Samsung Galaxy S7 Edge
**Android version:**  8.0.0
**Signal version:** 4.48.17

**Comment by VB2095** [comment]
It has already been issued there https://github.com/signalapp/Signal-Android/issues/8831 but it doesn't look like it has been fixed yet.

**Comment by greyson-signal** [comment]
We consider quotes to be the equivalent of copy+paste. If you quote a message, it has effectively been copied into the new message. So this is working as intended.
