### ISSUE TITLE
iPhone and iOS

### ISSUE THREAD

**Issue by ka-efe** [signalapp/Signal-Android#9143]
I found.

https://forums.macrumors.com/threads/ios-is-terrible-about-privacy.2205813/

1. You can't set up and use iPhone offline. You always have to do an internet activation in the setup window first. If you reset the software, internet activation is required again. iPad, iPod touch, Apple TV and Apple Watch same problem. The worst thing is if Apple shuts down the servers then you will never be able to use the iOS devices again.

2. Also when installing apps (locally installed by PC) you have to connect to the App Store the first time you start it. You are completely bound to Apple. Offline use is not possible.

3. During use it can connect over 100 undocumented Apple domains.

-- my $150 or High-End Android device does not have this limitation. Can always set up and use offline.

4. Not to forget, iOS has a built-in remote keylogger from Apple. Every keypass is sent to Apple server!

In general, developers don't like iOS. It is extremely limited and always set against the user.
Best Signal iOS will no longer support, because iOS and the other Apple systems are harmful platform for developers and users.

It is better to support Android or Android without google service and Linux than iOS. Users always benefit first and it is the most sustainable solution.

Please will not support iOS devices and the Apple platform again. It is really a harmful platform.

**Comment by alan-signal** [comment]
Please use the community forum for discussions https://community.signalusers.org/
