### ISSUE TITLE
A contact whose phone number includes spaces does not appear in Signal

### ISSUE THREAD

**Issue by mallet** [signalapp/Signal-Android#9145]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal does not seem to include contacts (that is, people found in Android "Contacs" application) whose phone numbers include spaces. 

### Steps to reproduce

Assuming you can convince someone to install Signal for the first time:
- Add this person to your contacts, if they are not there yet.
- Add spaces in their phone number.
- Tell them to install Signal.
- Verify that you do not find them in Signal.
- Remove the spaces from their number.
- See that they now appear in Signal.

### Device info

**Device:** Samsung Galaxy Note 4
**Android version:** 7.1.2
**Signal version:** 4.49.13 (but also present in previous versions)

### Comments

The application Contacts supports numbers with spaces in it. It is common practice in certain countries. E.g., in France, numbers are often presented in the form 06 XX XX XX XX, and can potentially be input like so. In other countries, people may add dashes in the phone numbers---maybe this is already supported by Signal. I suppose phone numbers from Contacts should be filtered to remove spaces, dashes, and possibly any character that is not a number (except for the leading '+').

**Comment by TeknoCepni** [comment]
Excuse me, I didn't reproduce this bug. Please explain more?
