### ISSUE TITLE
Contact shortcut got invalidated with recent update

### ISSUE THREAD

**Issue by WhiteHatTux** [signalapp/Signal-Android#9146]
I just installed the latest update and now the shortcut I had created for a contact on my home screen stopped working. When clicking it, signal opens on the conversations overview and shows a toast message: "Invalid shortcut"

**Comment by WhiteHatTux** [comment]
On mobile I didn't get the template for filing a bug. I will complete this later.

**Comment by greyson-signal** [comment]
For what it's worth this will be resolved in 4.50, but I also understand that by now you've probably just recreated the shortcut.
