### ISSUE TITLE
Issues sending photos on Android 4.4

### ISSUE THREAD

**Issue by baalpeteor** [signalapp/Signal-Android#9149]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can only accept MMS messages, but can't send ANY pictures, mms, or gifs. Only way to send a picture is to use the camera button for a live picture on signal first page, and select a contact, but I can't send actual old pictures (or live pictures) if i am in a conversation. It just stopped working one day out of the blue (maybe was a signal update) and hasn't since. I can send MMS normally as expected using the built-in messenger of Android.

### Steps to reproduce
- Open signal
- open existing conversation
- try to send anything using the "+" button (recent picture carousel, gallery button, gif button, etc)

**Actual result:** nothing happens
**Expected result:** asset (picture, gif, etc) would send

### Device info

**Device:** Samsung Galaxy Note 3
**Android version:** 4.4.2
**Signal version:** 4.49.11

### Link to debug log
https://debuglogs.org/6541deddb0b3f87ecb9ce8e56f182458c047972b1737249472061db9b96c42b0

**Comment by bill-mcgonigle** [comment]
I am seeing this on Pie for both MMS and Signal.  Log says:

```
10-31 17:51:00.775  3921  5027 D skia    : --- Failed to create image decoder with message 'unimplemented'
10-31 17:51:00.776  3921  5027 W MediaConstraints: Failed to determine if media's constraints are satisfied.
10-31 17:51:00.776  3921  5027 W MediaConstraints: java.io.IOException: org.thoughtcrime.securesms.util.BitmapDecodingException: Failed to decode image dimensions: -1, -1

```
Though the images show OK in the conversation window ("failed to send" message).

https://debuglogs.org/3feee7619b3b2cbe092c057d939e7931dd4ceeb919e3915818174389c364c0a8

**Comment by osmgit** [comment]
Same problem here, can't send photos in Signal Messenger. You select a photo and then send it and nothing happens, nothing appears in the messaging log. It can still accepts photos though.

Device info

**Device:** Samsung Galaxy S4 Mini
**Android version:** 4.4.4
**Signal version:** 4.49.13

https://debuglogs.org/18ca02ae0fa7f11b1bad664d5d4001c59f2ce9a756cae19f0b457dc2c365a49e

**Comment by tipuraneo** [comment]
+1

Unfortunatelly I saw this thread to late, that's why I opened
https://github.com/signalapp/Signal-Android/issues/9155

Device+version is similar to osmgit

**Comment by osmgit** [comment]
There was a signal update today but nothing has changed, I still can't send pics.

**Comment by bme13** [comment]
Friend has similar experience and created a debug log. Problem with Signal messages.
https://debuglogs.org/fbe889e875744ca25d440048edc3dd7d74047ed6d146c3a0fcd3fc063e3a167a
Device: samsung GT-I9060I
Android 4.4.4
Signal 4.49.14

**Comment by stephanborn** [comment]
I also cannot send pictures. But still can receive.

Device       : samsung GT-I9301I (s3ve3gxx)
Android      : 4.4.2 (I9301IXXSAQA1, KOT49H.I9301IXXSAQA1)
App          : Signal 4.49.15 (5621)

**Comment by greyson-signal** [comment]
Please try again in 4.49.16 with new photos that you have not previously sent. Might have been related to 544511905adf24779785fdeea6484a5ef969519c. If you're still experiencing issues for new photos in 4.49.16, please post a debug log here. Thanks!

**Comment by Trombonista** [comment]
Does not work for me on S4mini with 4.49.16, neither with saved photo nor from in-app camera.

**Comment by bme13** [comment]
Unfortunately no luck here either with 4.49.16. Here's the debug log.
 https://debuglogs.org/7951e91ba39dd221cf7cd9187c1f09243e26b3a83a0069f9102177e8f2bbd862
Think she tried to send a picture around 8:06
```
2019-11-07 08:06:04.483 CET W GiphyAdapter: null
2019-11-07 08:06:04.483 CET W GiphyAdapter: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2019-11-07 08:06:04.483 CET W GiphyAdapter: There was 1 cause:
2019-11-07 08:06:04.483 CET W GiphyAdapter: java.io.IOException(Unsupported size: 790)
2019-11-07 08:06:04.483 CET W GiphyAdapter:  call GlideException#logRootCauses(String) for more detail
2019-11-07 08:06:04.483 CET W GiphyAdapter:   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
2019-11-07 08:06:04.483 CET W GiphyAdapter: There was 1 cause:
2019-11-07 08:06:04.483 CET W GiphyAdapter: java.io.IOException(Unsupported size: 790)
2019-11-07 08:06:04.483 CET W GiphyAdapter:  call GlideException#logRootCauses(String) for more detail
2019-11-07 08:06:04.483 CET W GiphyAdapter:     Cause (1 of 1): class java.io.IOException: Unsupported size: 790
```

**Comment by Trombonista** [comment]
Tried to help out with testing older releases, but could not build from sources, error "No dependency for integrity assertion found: androidx.activity:activity". Am a noob to Android so giving up for now, assuming build instructions are outdated.

**Comment by stephanborn** [comment]
> I also cannot send pictures. But still can receive.
> 
> Device : samsung GT-I9301I (s3ve3gxx)
> Android : 4.4.2 (I9301IXXSAQA1, KOT49H.I9301IXXSAQA1)
> App : Signal 4.49.15 (5621)

After updating Signal today to 4.49.17 it still failed sending images - see logs:
https://debuglogs.org/e7a42f4e3736b2804e408b4ceb5530d3e070a03b7746729b1e8226dafb130dbb

**Comment by igor2x** [comment]
**Device:** Samsung Galaxy J
**Android version:** 4.4.4
**Signal version:** 4.49.18
**Debug:** https://debuglogs.org/3c09239c800409fd69506a93af13e5321fa3bd756d9cf716db815e2f6fc53f7e

Updated Signal from Play Store right now and with Signal protocol tried to forward a picture which is having a text bellow it. Only text was forwarded with no picture. I tried to send a picture that was never send before.

Looking at devices at this bug report and it looks related to Android 4.4.x.

P.S. May I suggest to rename bug report title e.g. to just remove "mms" from it, because problem also appears with Signal protocol.

**Comment by eikel** [comment]
I have the same problem since updating Signal to 4.49.x.

### Device info
**Device:** Sony Xperia X
**Sailfish OS version:** 3.2.0.12 “Torronsuo”
**Android version:** [4.4 (aliendalvik)](https://jolla.zendesk.com/hc/en-us/articles/201440787#2)
**Signal version:** 4.49.18

**Comment by tipuraneo** [comment]
Updated to 4.49.18. Issue remains:
* photos taken by Signal and
* recently unsent pictures
disappear after pressing 'send'. Messages were not sent.

**Device:** Samsung Galaxy S4mini
**OS:** Android 4.4.4
**Signal version:** 4.49.18
[debug logs](https://debuglogs.org/fc3d468f34b4a6b84f2e7f7550fe46d362dc5ecd3a17ed31422822e43c49540b)

How can I help to get this fixed?

**Comment by stephanborn** [comment]
Yessss! It works again - thanks for the help!

**Comment by Trombonista** [comment]
When is a new version scheduled for play store? Play store/APK are still at 4.49.18.
@stephanborn did you build from sources?

**Comment by stephanborn** [comment]
> When is a new version scheduled for play store? Play store/APK are still at 4.49.18.
> @stephanborn did you build from sources?

No, I got the update today in Play Store

**Comment by greyson-signal** [comment]
We do production rollouts over time, so we can catch issues before everyone gets it. If you'd like to get the release immediately, you can [join the beta](https://play.google.com/apps/testing/org.thoughtcrime.securesms) :)
