### ISSUE TITLE
Signal 4.49.14 universal/website version fails to verify (apksigner verify)

### ISSUE THREAD

**Issue by EmberHeartshine** [signalapp/Signal-Android#9151]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When checking the website APK downloaded from the Signal website using `apksigner verify Signal-website-universal-release-4.49.13.apk`, I receive the following error:
```
DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: Malformed additional attribute #1
WARNING: APK Signature Scheme v2 signer #1: Unknown signature algorithm: 0x421
```
Because of this error, my personal F-Droid server reports that Signal "[contains a known security vulnerability](https://f-droid.org/wiki/page/AntiFeature:KnownVuln)" and "[has a weak security signature](https://f-droid.org/wiki/page/AntiFeature:DisabledAlgorithm)". (See [screenshot](https://user-images.githubusercontent.com/50666308/67972540-48dc7200-fbe5-11e9-85b4-84f1126c3848.png).) I have no control over this report. This is a simple binary server, which does not compile the APK or sign it but rather simply hosts the APK and serves it through the F-Droid client. The infrequency and irregularity of the Universal APK update makes it difficult to pin down which version this error started occurring in, since the most recent website release was 4.47.7. (I am unsure why this is not an automated process, releasing alongside the [regular staged releases](https://github.com/signalapp/Signal-Android/releases).)

When I check the previous website version I have (using `apksigner verify Signal-website-universal-release-4.47.7.apk`), I get a warning, but not an error (this version is not a concern; it worked fine):
```
WARNING: APK Signature Scheme v2 signer #1: Unknown signature algorithm: 0x9901
```
I verified the SHA256 checksum from `latest.json` (`15842d89cfd4fc7710d3ce7d4dcd9dba205d6754f336c14b1fab46e2c2239cfb`), and the APK is not corrupt. 

### Steps to reproduce
- `wget https://updates.signal.org/android/Signal-website-universal-release-4.49.13.apk` (or download using your browser of choice)
- `apksigner verify Signal-website-universal-release-4.49.13.apk`

**Actual result:** Error message described above.
**Expected result:** No error.

### Update
This error persists across to the new 4.49.14 update released over the weekend.

**Comment by Hualingfeng** [comment]
Thank you very much for the download link, because I can't access the Google App Store in China.

**Comment by alex-signal** [comment]
Hello! Thanks for filing this issue.  It turns out older versions of `apksigner` had some issues with v3 signing scheme.  Please see this StackOverflow link for discussion:

https://stackoverflow.com/questions/54782328/apksigner-does-not-verify-signature

Running verification of the posted APK utilizing the 29.0.2 version of build-tools, I see:

```
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true
Number of signers: 1
[ truncated warnings ]
```

Please download the newer build tools version through your SDK manager and try verification again.

~Alex.
