### ISSUE TITLE
Failure to retrieve MMS messages on AT&T

### ISSUE THREAD

**Issue by thinkbrown** [signalapp/Signal-Android#9153]
- [:heavy_check_mark:] I have searched open and closed issues for duplicates
- [:heavy_check_mark:] I am submitting a bug report for existing functionality that does not work as intended
- [:heavy_check_mark:] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [:heavy_check_mark:] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting recently, I have been unable to receive a majority of MMS messages I recieve. They display "Error downloading MMS message, tap to retry", but never successfully complete on retry. The symptoms appear similar to [bug 9013](https://github.com/signalapp/Signal-Android/issues/9013), but the error in the logs appears to be different. It appears as though signal is failing to save the message body correctly, as the java stacktrace fails with an `java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)`

### Device info
Device       : asus ASUS_I001DC (WW_I001D) _[Asus ROG Phone II]_
Android      : 9 (16.0631.1908.21-0, PKQ1.190414.001.WW_Phone-16.0631.1908.21-0)
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 21M (47.09% free, 768M max)
Memclass     : 560
OS Host      : mcrd1-28
First Version: 542
App          : Signal 4.49.13 (5602)

### Link to debug log
https://debuglogs.org/e23f24d396f05ad7af95f416807d1cac7d4a51cf737056cd7d7dfce7b1324ece

**Comment by thinkbrown** [comment]
Started exploring the signal codebase and found that this appears to be a duplicate of [8571](https://github.com/signalapp/Signal-Android/issues/8571). Gonna close and add my logs to that issue.

**Comment by thinkbrown** [comment]
Reopening based on a request in #8571

**Comment by paxperscientiam** [comment]
@thinkbrown thank you.

Device       : Motorola MotoG3 (lineage_osprey)
Network: Virgin Mobile USA, which is a MVNO on Sprint


My log: https://debuglogs.org/856a53c625fa5eb2d04193f44f906c185db315bb213e325dc288dfd795c9f0f2

**Comment by myersjustinc** [comment]
Should AT&T users who commented in #8571 copy their debug logs and related info to this thread? What would be most useful to devs and others who are helping to sort this out?

**Comment by myersjustinc** [comment]
Following up on the above, here's what I see in the other thread from AT&T users from the past couple of weeks:

*   @angela-d: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-548634069
*   Me: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-549084331
*   @mrnohr: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-549603342
*   @EngineerFaunce: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-550302667
*   @agmlego: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-551100799
*   @amcnicho: https://github.com/signalapp/Signal-Android/issues/8571#issuecomment-551177642

as well as everything in #9173, I assume.

**Comment by jeinstei** [comment]
I'm ATT as well. I'm seeing a null object being passed in the debug look, but am still working on editing them down

**Comment by greyson-signal** [comment]
Let's merge this into #9173, which has some more information.

**Comment by dizz1s4u** [comment]
same issue here for months
AT&T
Samsung Galaxy 9+
SM-G965U
Android v9
Kernel 4.9.112-16352124
Signal 4.49.18
