### ISSUE TITLE
Camera flash not working in direct capture mode

### ISSUE THREAD

**Issue by erik55** [signalapp/Signal-Android#9156]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I take a photo from within the Signal app, I am not able to use the flash. I am able to change the flash icon between always-off, always-on and automatic by tapping on it. Flash light during capture of photo is not working in none of the three modes. 

### Steps to reproduce
- open signal app
- tap on the camera icon on the lower right side of my shown contacts (main screen). 
- take a photo in a dark environment (tap on the circular button on the lower center of the screen) when the flash icon (a flash symbol) on the upper right side of the screen is in always-on mode (filled) or automatic (has a small A besides the flash icon). 

**Actual result:** A dark picture is taken. Without use of the flash light. 
**Expected result:** The flash light should lighten the scene, it should flash when taking a picture in a dark ambient when in automatic flash mode or should always flash when in always-on-mode. 

### Device info

**Device:** Samsung Galaxy S9 SM-G960F (but I've asked friends, and with the Galaxy S7 and an IPhone it doesn't work neither) 
**Android version:** 9
**Kernel version:** 4.9.59
**Signal version:** 4.49.13

### Link to debug log
In the debug log I can't find any hints on my tapping of the flash icon, which I used to change from always-on to automatic flash mode. 

https://debuglogs.org/7739563513cd3a4371c4261d105d1c8d2b08e8c405679b6b59892ca97de40fba

### Related old bug descriptions
- #3590
- https://www.reddit.com/r/signal/comments/81ty85/camera_flash_not_working/

**Comment by Tursko** [comment]
Currently having this same issue. Noticed this in 4.52.4 and now 5.53.6.

**Comment by pankarlox** [comment]
I confirm the same problem on Samsung Galaxy s10e, Android 10; Signal 4.53.6, and Samsung Galaxy s9, Android 9; Signal 4.53.6.
But everything works properly on Alcatel OneTouch Idol, Android 5; Signal 4.53.6.

**Comment by Tursko** [comment]
Another friend on 4.53.7 is having the same issue on his Pixel 4 XL.

**Comment by bme13** [comment]
After changing the os of my S9 to some LineageOS flavor I now use OpenCamera. In the settings I noticed an option to change to change camera api. If I use the default the flash in OpenCamera works. If I change to camera2 the flash does not work in OpenCamera however then there's an option called 'Use alternative flash method' If I enable that option the flash works. It seems they work around the flash problem. I really don't know if it would be feasible to use something like that in Signal as well but thought I just share it here.
Some references to the code where that options is used.
https://sourceforge.net/p/opencamera/code/ci/master/tree/app/src/main/java/net/sourceforge/opencamera/MainActivity.java#l585
https://sourceforge.net/p/opencamera/code/ci/master/tree/app/src/main/java/net/sourceforge/opencamera/cameracontroller/CameraController.java#l425

**Comment by error401de** [comment]
Same issue on Galaxy S9. Is there any progress on the topic? It's open since over a year...

**Comment by ravtakhar** [comment]
Having the same issue with the Pixel 4. Is there a way to launch the native camera app for taking pictures?

**Comment by erik55** [comment]
Still not working on my Samsung Galaxy S9, had the same problem with my Galaxy S7: 

https://debuglogs.org/2d0f238e9cc96a43d3b53c53c71a0adb6311ac1fa88e3d9f94af2edc48d50748

**Comment by error401de** [comment]
It's working on my new S21, so I guess it's dependent on the model.

**Comment by erik55** [comment]
Or the Android version. 

* Works with Oukitel C15pro: works (Android 9)
* Samsung S21: works (Android 12)
* Samsung S7: works (Android 8)
* Samsung S9plus: **NOT WORKING** (Android 9)
* Samsung S9: **NOT WORKING** (Android 9)
* Razer Phone: works
* Poco Phone: works

Ok, any other phones except for the S9 and S9plus which don’t work? Or are those the only ones?

**Comment by gbright89** [comment]
@erik55 you can add the one plus 9 to that list. Just downloaded the app this evening and it's an issue on my phone too. 
Weird too because the flash does go off, I did see the light up picture, but once it was taken it was dark. 

I tried a bunch of times in a row and it did manage to get 1 or 2 correct. As for the majority, not so much.

**Comment by Tursko** [comment]
Still applies

**Comment by erik55** [comment]
Finally works for me. Please close.
