### ISSUE TITLE
image not shown any more

### ISSUE THREAD

**Issue by dusscloud** [signalapp/Signal-Android#9157]
### Bug description
One Signal contact (let's say Bob) sent a picture, which I received and was displayed well.
Few minutes later I forwarded that picture to another contact (let's say Alice), without any noticeable issue.
Some hours later, going into the discussion feed of Bob, I notice that the picture is not displayed any more (in the feed or in "all medias" explorer). A error logo is shown instead.
In Alice discussion feed, the forwarded picture is still there.

### Steps to reproduce
I didn't succeed to reproduce the issue.

### Screenshots
![Screenshot_20191103-121052](https://user-images.githubusercontent.com/31505866/68086125-a3293d00-fe48-11e9-8355-bfc187249865.png)

### Device info
**Device:** Moto G6 XT1925-5
**Android version:** 9
**Signal version:** 4.49.14

**Comment by AndrewPy** [comment]
I had the same Issue about a week ago with Signal 4.49.13 and Android 5.1. But if I remember correctly, I deleted the forwarded image and after that the original image was gone too.

**Comment by greyson-signal** [comment]
This should be fixed in 544511905adf24779785fdeea6484a5ef969519c.
