### ISSUE TITLE
Registration Lock Password is truncated to 3 characters

### ISSUE THREAD

**Issue by cbreak-black** [signalapp/Signal-Android#9159]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to add a Registration Lock, my Password (20 characters) is truncated to 3 characters, and not accepted with the complaint that 3 characters is too short. But I pasted 20 characters directly from 1Password.

Normally, I'd expect autofill to work, but https://github.com/signalapp/Signal-Android/issues/8322 is already open, so it is already known that autofill is buggy in signal. But to circumvent that bug, I tried copy & pasting.

### Steps to reproduce
- Copy Password from 1Password (20 character random, the maximal permitted length by Signal according to documentation)
- Paste into the registration lock password fields
- Try to enable the lock

**Actual result:** The password is truncated and rejected
**Expected result:** Registration of my account is locked to only people that know my password (myself)

### Device info

**Device:** Sony G8441 (G8441)
**Android version:** 9 (3311891731, 47.2.A.11.228)
**Signal version:** Signal 4.49.14 (5612)

### Link to debug log
https://debuglogs.org/a62ea4861db372f7eaf204de625fef06117e81f88e600b82295e7708e2eb853a

**Comment by alan-signal** [comment]
A registration lock is a numeric field of 4 or more digits. Your random characters probably only include 3 digits.

![image](https://user-images.githubusercontent.com/48254818/68307870-e8808100-0079-11ea-830e-56de70baf93a.png)
