### ISSUE TITLE
Typing indicator does not change color

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9160]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I am chatting with someone and change the contact color, the typing indicator does not change with it.

### Steps to reproduce
- Engage in a chat
- Change the contact color of the person you're chatting with
- See next typing indicator

**Actual result:** The typing indicator has the old color
**Expected result:** The typing indicator has the new color

### Screenshots
![Signal_20191104-183657](https://user-images.githubusercontent.com/8427572/68148292-f4662900-ff3b-11e9-8176-998553edc3ef.png)

### Device info
**Device:** Sony Z3 compact
**Android version:** 6.0.1
**Signal version:** 4.49.14

**Comment by primarto** [comment]
Confirm, same with me.
**Signal version:** 4.58.5

**Comment by yparam98** [comment]
still open/broken?
