### ISSUE TITLE
Can sent picture

### ISSUE THREAD

**Issue by mlsxlist** [signalapp/Signal-Android#9164]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have an image that I can't send with Signal. Whenever I try to send it Signal reports **Send fail, tap for details**

### Steps to reproduce
- Go into a conversation
- Add the picture to a new message and send it
- Signal reports **Send fail, tap for details**

**Actual result:** When sending the picture Signal reports Signal reports **Send fail, tap for details**
**Expected result:** The picture should be send

### Screenshots
![Screenshot_20191105_053517_org thoughtcrime securesms](https://user-images.githubusercontent.com/6071818/68179053-8eef5800-ff8e-11e9-953e-9ce41d1a39f0.jpg)

### Device info

**Device:** HUAWEI MHA-L29
**Android version:** 9.1.0.252
**Signal version:** 4.49.15

### Link to debug log
https://debuglogs.org/2d04b9941032fcb3401d850bc1f461e87f222e1751eaa45f36bd02bb9a7cc89c
The error happened after 2019-11-05 05:01:39.088

**Comment by sadan23** [comment]
Same issue on a sony Xperia.
But on second time it works in normal converations. But not in groups. There is always the same issue.
Here is the report:
https://debuglogs.org/795b8ccac45767613d0f09f7777f4100d887ecb36fe3b3f75bd2103ea3d95b77

**Comment by Trombonista** [comment]
Maybe related to #9149, but on #9149 no error message appears. #9149 seems to be related to old Android (ca. 4.4)

**Comment by greyson-signal** [comment]
This should be resolved in 4.49.16 (544511905adf24779785fdeea6484a5ef969519c), which is currently rolling out. Unfortunately, pictures that have already failed to send cannot be fixed, but new pictures should work after updating.

**Comment by mlsxlist** [comment]
Thanks @greyson-signal.Just for looking into this issue. Just updated to 4.49.16.For me the issue still happens.
https://debuglogs.org/df61df4300c20c1faa2a685776e454cafb8be2ad83150b97f5c7e62f62736af5

**Comment by mlsxlist** [comment]
Debug log from 4.49.17:
https://debuglogs.org/1ea8baef2036d221571572fcd4218f94c1f582c39d3fccf941c129c9a5b05d40

**Comment by greyson-signal** [comment]
@mlsxlist Is this a new, never-before-forwarded image?

**Comment by mlsxlist** [comment]
No. If I remember correctly I received it. Then forwarded it. Then saved it locally. When I now try to send the locally saved picture I get the error.

**Comment by mlsxlist** [comment]
With  4.49.18 the issue is fixed. Thanks @greyson-signal
