### ISSUE TITLE
Cannot record video with built-in camera on some phones

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#9166]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On some phones, pressing and holding the shutter button only renders Signal taking a picture and not recording video. In my case, this holds true for an older Nexus 5X which I still use as an extra phone. Two friends does however have the same problem, both of them are on Android 8.1 just as my Nexus phone.

On my newer phone running Android 9, the video is captured as intended.

Short video demonstrating me pressing and holding the shutter button:
https://caprioli.se/d/VID_20191107_112234.mp4

Debug log, from the above video:
https://debuglogs.org/4266165d79249258ff9be715ec6bdc5e4108f614794d6aaac36c1a1804324c90

### Device info

**Device:** Google Nexus 5X
**Android version:** 8.1.0, Lineage OS
**Signal version:** 4.49.16

**Comment by jonalmeida** [comment]
I can reproduce this on a Pixel 4 as well, but it works fine on a Pixel 2.

**Comment by Genis-Sage** [comment]
hey @petcap 
welcome

you have the problem already mentioned in #9117 

for using the video recording function, there are two prerequisites:
> Build.VERSION.SDK_INT >= 26 && MemoryFileDescriptor.supported();

in your debuglog, you can find the line
> 2019-11-07 02:12:25.879 GMT+01:00 W MemoryFileDescriptor: MemoryFileDescriptor is not available.

so right now, the beheviour is expectable

@jonalmeida 
you should also post a debug log, or look into it youself,
if you find a similar line

**Comment by greyson-signal** [comment]
We're aware that not all device support video capture. Signal never writes unencrypted bytes to disk, so our only realistic option at the moment is to record the video in native memory. Unfortunately not all devices support that.

In the case of the Pixel 4, there's actually a multitude of bugs in CameraX (the Google-made camera library we use) that forced us to fall back to our old legacy camera for that device. We're hoping these bugs get fixed soon.
