### ISSUE TITLE
Unable to retrieve MMS messages, Verizon

### ISSUE THREAD

**Issue by jscott0** [signalapp/Signal-Android#9174]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is unable to retrieve MMS messages. It times out and doesn't fetch them. My log differs substantially from the most similar issues, and was not fixed by the most recent beta.

### Steps to reproduce
- get MMS from non-Signal user
- smash the ↓ MMS button
- times out after a minute or so

**Actual result:** The message isn't downloaded.
**Expected result:** It should be downloaded.

### Device info
**Device:** Motorola moto g⁷ power
**Android version:** 9
**Signal version:** 4.49.18
**Carrier:** Xfinity Mobile/Verizon

### Link to debug log
https://debuglogs.org/a7a6f7df695161fa7faf2f73b4af34a5f176aa9bc1e0ef9b92d6e50325b0d8bf

**Comment by Cerberus0** [comment]
It might be helpful if you could include your carrier in the title and device info section. Thanks!

**Comment by Tursko** [comment]
Do you use WiFi Calling?

**Comment by JohnScott623** [comment]
@Tursko My phone supports it, but I don't use it and have it disabled.

**Comment by JustDerb** [comment]
Device: Pixel 2 XL
Android version: 10
Signal version: 4.49.18
Carrier: AT&T

https://debuglogs.org/c3d3f0d2fc18d690c8062c31598265d0ac9d091205739573f7bc2630d75310ca

**Comment by mkelandis** [comment]
Same Issue here (afaict):

Device: Oneplus 8
Android Version: 11
Signal version: 5.0.8
Carrier: Total Wireless

https://debuglogs.org/95286a3c570e0547c827c9178d9c457d770c8ca8293dac8ab4951a07c15f6db5

**Comment by mkelandis** [comment]
I switched carriers and stopped using this app - so I don't have any updates.
