### ISSUE TITLE
Suggestion: ViewModel support

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#9180]
Conversation and ConversationList is using LoaderManager. But it is deprecated and ViewModel structure is better than loadermanager. Please do it in Conversation and ConversationList models.

**Comment by greyson-signal** [comment]
As noted in our issue template, Github is only for tracking bugs. To briefly address the suggestion: all of our new work is done using ViewModels and LiveData, but rewriting (very) large, functioning portions of the app just for the sake of refactoring isn't my idea of fun :) It'll likely be moved over when there's some other necessary large refactor in that area.
