### ISSUE TITLE
Location links starting with geo: not working.

### ISSUE THREAD

**Issue by jensMF** [signalapp/Signal-Android#9189]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Location links with geo: at the beginning are not usable.

### Steps to reproduce
- send or receive a message containing a geo: link (e.g.: geo:0.0,0.0?z=10)

**Actual result:** The coordinates are getting clickable but are opened like phone numbers.
**Expected result:** The geo: link gets clickable and can be opened in an app supporting it.
### Device info

**Device:** Moto G5 Plus
**Android version:** 8.1.0
**Signal version:** 4.49.18

### Link to debug log
I don't know when the bug exactly happens, so I don't know when to capture the log ...

Probably has something to do with #4206 and #6351

**Comment by StyXman** [comment]
It's really useful for sharing location information with apps that are _not_ gmaps, specially those based on OSM like OsmAnd, MyTracks, etc.

**Comment by StyXman** [comment]
> Is this still relevant?

Yes.

> If so, what is blocking it?

Developer time, I guess.

> Is there anything you can do to help move it forward?

No, not really, sorry.

**Comment by StyXman** [comment]
this stale/close workflow is not very good if the reported issues never get any activity

**Comment by greyson-signal** [comment]
Hi there, we use the stock android linkifier. I don't anticipate we'll make a custom one to support geo: links anytime soon, apologies.

**Comment by StyXman** [comment]
Can you point me to the project? Maybe I can open a issue with them.

**Comment by nicholas-signal** [comment]
> Can you point me to the project? Maybe I can open a issue with them.

You can see our usage here: https://github.com/signalapp/Signal-Android/blob/bc1c8032c1233dad40bfa5d242cf8bec1e102d82/app/src/main/java/org/thoughtcrime/securesms/conversation/v2/items/V2ConversationItemUtils.kt#L32

As you can see, we rely on `androidx.core.text.util.LinkifyCompat`. The place to report bugs in `androidx.core` is here: https://issuetracker.google.com/issues/new?component=460834&template=1418393

**Comment by UserX404** [comment]
This is still a long runner.
https://github.com/signalapp/Signal-Android/pull/4790

**Comment by mbartlett21** [comment]
Created an issue there: https://issuetracker.google.com/issues/318207510

**Comment by StyXman** [comment]
Now that I think of it, I would say "good luck with that". Even if putatively Android is not owned or gatekeept by Google, I don't think it will go anywhere if it undermines they locking in on the platform :( I hope I'm wrong.

**Comment by anaxonda** [comment]
Bummer on the lack of interest for this!  Especially for a privacy app like Signal. 

Whatsapp at least used to support linkifying latitude longitudes, but recently that stopped working. Would love a way to share clickable location links that are not tied to one app.

**Comment by uzantome** [comment]
> Hi there, we use the stock android linkifier. I don't anticipate we'll make a custom one to support geo: links anytime soon, apologies.

hi @greyson-signal , I found your Commit [5655fcf](https://github.com/uzantome/Signal-Android/commit/5655fcf9733e1594c5e9abe2b144520aa3356823) "Create new linkifier."

It seems like that would allow linkification of `geo:` URIs now. I would be happy to draft a PR if that was welcomed.

Edit: i opened a PR, see #14838
