### ISSUE TITLE
JobSchedulerScheduler$SystemService NET PERSISTED failures and not get notification

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#9190]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

### Bug description
I have Xiaomi phone and when Signal app is killed, I gave this error log and notification is not coming.

### Steps to reproduce
- I killing app from recent apps.
- Send new message from this phone.
- My phone has these errors and Mi can't get notification.

**Actual result:** I can't get notification and when app is killed, I'm giving this error.
**Expected result:** I can get notification

### Device info
**Device:** Xiaomi 8
**Android version:** 9.0
**Signal version:** 4.49.18

### My error log
```
2019-11-14 12:18:25.710 1499-2605/? I/AutoStartManagerService: MIUILOG- Reject service :Intent { JobSchedulerScheduler$SystemService } userId : 0 uid : 10248
2019-11-14 12:18:25.711 1499-2605/? D/JobScheduler: Error executing JobStatus{4c823de #u0a248/45 JobSchedulerScheduler$SystemService u=0 s=10248 TIME=-2s625ms:none NET PERSISTED failures=1 READY}

```

**Comment by greyson-signal** [comment]
Some devices have the unfortunate behavior that when you kill the app from the recent apps, it actually "force closes" apps, which can prevent things like system JobScheduler jobs from being run. I can't say for sure if that's happening here, but it could be.

But in general, if Xiaomi's OS is deciding that it no longer wants to run our JobScheduler jobs, there's not much we can do. While the app is open, we will do all we can, but if the app isn't open, the only tool we have to do work on Android 8+ is the JobScheduler.

I'm just gonna say that this is crappy behavior from Xiaomi, without anything actionable on our end.

Btw I think the "NET PERSISTED" thing is just saying that our job both requires network (NET) and is will survive reboots (PERSISTED).
