### ISSUE TITLE
Screen lock reminder activates after screen lock is turned off

### ISSUE THREAD

**Issue by jamesjahraus** [signalapp/Signal-Android#9191]
----------------------------------------

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After setting Settings > Privacy > Screen lock to ON, I get occasional reminders to enter my screen lock pin, to train me to remember it. After setting Settings > Privacy > Screen lock to OFF, I still get occasional reminders to enter my screen lock pin, to train me to remember it. I am expecting that if I turn the Screen lock to OFF the reminders will also turn off.
 
### Steps to reproduce
- Settings > Privacy > Screen lock ON
- Sometimes get Screen lock pin reminders
- Settings > Privacy > Screen lock ON
- Still sometimes get Screen lock pin reminders

**Actual result:** 
- When I turn off Screen lock, I keep getting screen lock pin reminders.

**Expected result:**
- When I turn off Screen lock, screen lock pin reminders stop.

### Device info
**Device:** motorola Moto G (4) (athene)
**Android:** 7.0 (6, NPJS25.93-14.7-8)
**App:** Signal 4.49.18 (5651)

Note: I also logged https://github.com/signalapp/Signal-Android/issues/9182 and from searching through the issues there seems to be many bugs around the screen lock feature. I could be helpful to look at the screen lock systemically and perhaps simplify it generally. See also
https://github.com/signalapp/Signal-Android/issues/8603
https://github.com/signalapp/Signal-Android/issues/7962

Suggestion:
Authy's implementation is quite simple, i.e. whenever Authy is opened must enter pin lock code. This could work for Signal. It could be helpful to simplify this feature as a general solution to all these bugs.

As a user this is my experience of the screen lock feature:
I noticed when Screen lock is ON it wasn't locking as I expected, the inactivity timeout could not be set, nor work as I expected, then when I turned it off Screen lock reminder continues to activate. Generally the feature seems too complex to use, and that complexity seems to be causing bugs.

**Comment by bme13** [comment]
Are you sure this is a screen lock reminder and not the registration lock reminder? Why would there be such a thing as a screen lock reminder. I mean once you're able to provide that you're already logged in so proved you still know it :smiley:

**Comment by alan-signal** [comment]
Yes, this sounds like it must be your registration lock pin.

![image](https://user-images.githubusercontent.com/48254818/68884091-6b3fb680-06e0-11ea-8821-debf2814558c.png)

The screen lock pin is an OS level pin that we have no knowledge of, so we couldn't test it even if we wanted to.

If it doesn't look like above, comment and I'll reopen.
