### ISSUE TITLE
Infinitely trying to send failing SMS on bad connection.

### ISSUE THREAD

**Issue by cladmi** [signalapp/Signal-Android#9192]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

On some conditions, I guess bad network conditions signal keeps indefinitely trying to send SMS but says they fail.
It even brings android complaining about the app sending too many messages and asking if it should be stopped but keeps going.
No solution found except force killing the app. It even comes back after.

Sometime the SMS is still sent even if it has fail send status.

### Steps to reproduce

- Send a SMS when with bad network
- Be unlucky
- receive an infinite amount of failed sent messages

Even a reboot keeps the same behavior.

I had this in the past and killed the phone for a long time before it could work again.

**Comment by alan-signal** [comment]
Please send a debug log. Can you tell us how long you have experienced this and whether it is a new thing or new to a particular version?

**Comment by PBMacros** [comment]
I can confirm this issue. I never experienced it in the past, but for the first and only time last week. 
My device is a Motorola Droid 4 and has Lineage OS 14.1 (Android 7.1.2) without Google Services.
I will try to provide a debug log when the issue arises again.

**Comment by charltonstanley** [comment]
i have experienced this issue as well, and will also try to provide a debug log when it happens.  I have a db though with over 50000 messages...my debug log is a mile log. is there any way to clear the debug log so that i can provide less information, and make the debug log more relevant to you guys?

**Comment by cladmi** [comment]
I have a logcat that I got with `adb` on another time. I did not know about the app integrated feature when I took it.

On that time, I got the alert only a few times and got network back again and the message got sent.

[logcat_signal_fail_to_send_multiple_errors_reported.txt](https://github.com/signalapp/Signal-Android/files/3907526/logcat_signal_fail_to_send_multiple_errors_reported.txt)

**Comment by PiCob** [comment]
FWIW, I faced this a few weeks ago (so no log available anymore): I didn't notice my phone was in flight mode. I guess you can easily repro by simply activating flight mode and sending a SMS.

**Comment by lovemadethis** [comment]
I'm very sorry to see this problem still persists. Several of us experienced the same issue well over a year ago. After uninstalling Signal, a large number of duplicate messages were found in the Android stock messaging app waiting to be sent, which explains why the mass sending would start as soon as the phone connected again, even though the original failed message had been deleted from Signal. It's a shame there is no way of setting the amount of tries Signal is allowed when sending a message. We live in an area with unreliable phone connectivity, so Signal had to go :-(

**Comment by LDuncAndroid** [comment]
Just had the same issue with a connection that dropped after a phone call. No logs I'm afraid.

**Comment by i7u** [comment]
Family member is reporting the same issue. She received a massive monthly bill from her service provider. The detailed transaction log shows many instances of tens of SMS messages being sent in short succession (within a timeframe of maybe 10 minutes). In the Signal app, only one message is visible. Obviously this happened during the previous billing period, but here are the current logs in case they help: https://debuglogs.org/abc939e025ccef86ee3f5e680d99a5646b08265249de6016c91629aa710bc945

**Comment by peterpanondrugs** [comment]
Same here. Bad connection. Signal symbol for pending messages keeps spinning, but SMS are despite this sent to the recipient endlessly. It just took my whole money of my phone. So i cleared cache and started phone anew, to stop this madness.

In general, i have to stop signal working, so the SMS is sent after Signals restart. Otherwise SMS stays (mostly) in pending mode and wont get sent in good or bad connection.

**Comment by greyson-signal** [comment]
Let's centralize discussion here: #8390
