### ISSUE TITLE
RCS is now a thing

### ISSUE THREAD

**Issue by lazerhawk** [signalapp/Signal-Android#9193]
thanks but we're not going to do this before it becomes a thing

_Originally posted by @moxie0 in https://github.com/signalapp/Signal-Android/issues/4837#issuecomment-162923631_

[https://www.blog.google/products/rcs/upgrading-messaging-android-us-rcs/](url)

**Comment by greyson-signal** [comment]
(1) As stated in the template, issues are for bugs, not feature requests. Feel free to discuss this in [the forum](https://community.signalusers.org/t/rcs-support-feature-request/3887/23).
(2) Android has provided no API's for RCS, meaning no 3rd party app can support it; i.e. we couldn't support RCS even if we wanted to.
