### ISSUE TITLE
Notification Sound always played 

### ISSUE THREAD

**Issue by metal-walker-smell** [signalapp/Signal-Android#9195]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The notification sound will always play when you receive messages when actively on a chat. Ideally, the notification sound should only play if you're are not currently on the Signal app and you receive a notification, not with each new message in a chat. This issue is present on the iOS version too.
 
### Steps to reproduce
- open the signal app and go into any chat.
- make sure your phone is on sound mode.
- chat with the person, and replies received will trigger the notification sound even when in the chat. 

**Actual result:** Notification sound plays with each new message.
**Expected result:** Notifcation sound should only play when not on the Signal app.

### Device info

**Device:** Samsung Galaxy J7 2017
**Android version:** 9.0.0
**Signal version:** latest

**Comment by greyson-signal** [comment]
Settings > Notifications > In-chat sounds :wink:
