### ISSUE TITLE
led doesn't turn on when receiving signal notification

### ISSUE THREAD

**Issue by hugodu69** [signalapp/Signal-Android#9199]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when i receive a message in signal it doesn't turn the led on, no matter if sound and vibration are on or off both in general settings or signal settings, and the led works fine with other apps. I didn't have the opportunity to test with a real signal message, i just installed the app and only noticed it with sms messages from people not using signal

### Steps to reproduce
- receiving a sms with signal
- notification appears

**Actual result:** led doesn't turn on
**Expected result:** led should turn on like it does with other apps

### Device info

**Device:** Lenovo A6020a46
**Android version:** 5.1.1
**Signal version:** 4.49.18

### Link to debug log

https://debuglogs.org/4871170d6f019b1a897d3b6d4262278284f2a71dca28bb1f16026eb2239f1cff

**Comment by charltonstanley** [comment]
This could be a device specific issue.  i just tested this on a Google Pixel running android 10, and it works.

**Comment by cjaverliat** [comment]
Hi,
I encountered the same issue on two devices, I had the vibration and sound but no blinking LED as well. However, I managed to make it work by enabling some permissions. This might also work for issue #8675.

## Fix

It appears that there are two permissions you need to allow for the LED notification to work:
- **In Signal:** Settings > Notifications > Priority > Enable "LED Light"
- **In Android parameters:** Settings > Notifications > Search for Signal and open it > Enable "Allow using LED light" (disabled by default in my case)

I wonder why the internal Android permission is not enabled by default.

## Device info

I tested this on two phones: 

Device: Xiaomi Redmi Note 5
Android version: 9 PKQ1.180904.001
Signal version: 5.2.3
MIUI Version: 12.0.2 Stable

Device: Xiaomi Redmi Note 6 Pro
Android version: 9 PKQ1.180904.001
Signal version: 5.2.3
MIUI Version: 12.0.1 Stable

I hope this will solve your LED problem as it did for me 😄

**Comment by hugodu69** [comment]
hi  @cjaverliat thanks for the reply, also @charltonstanley 

Your fix doesn't work for me unfortunately, but i discovered that signal is not the only app with this bug. I think it could works because it does with the default message app, but in the same time my device is old and i cannot update to the latest android version, so i think it's the reason and it's to bad but it's not a big issue anyway :/

**Comment by cjaverliat** [comment]
Imo this is pretty important bug as many users might encounter it, leading to missed messages. In my case I was unable to see that I received a message without unlocking the phone before my changes in permissions. For a messaging app, I consider it important. For your specific case, do you have applications that can use the LED successfully ? If so, could you provide an example ? Thanks.

**Comment by hugodu69** [comment]
I now have signal 5.0.8, it still doesn't work. My led works, for exemple when charging it's red, when charged and plug it's green. The only app that seems to be able to use the led successfully is the "native" text message app, every other apps (protonmail, signal, silence) do not success in using the led
