### ISSUE TITLE
Signal Voice Calls Do Not Connect with DNSfilter Application Enabled

### ISSUE THREAD

**Issue by eviljoel** [signalapp/Signal-Android#9200]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal does not connect to voice calls with the F-Droid application DNSfilter (https://github.com/IngoZenz/personaldnsfilter) enabled.

### Steps to reproduce
- Install DNSfilter (https://github.com/IngoZenz/personaldnsfilter) on one of the two phones.
- Run DNSfilter with it default settings.
- Attempt to make or receive a voice call.

**Actual result:** If DNSfilter is enabled on the phone making the call, the calling phone rings several times and eventually the "RECIPIENT UNAVAILABLE" message is displayed on the calling phone and a missed call notification is displayed on the receiving phone. If DNSfilter is enabled on the phone receiving the call, the receiving phone creates a receiving call notification but does not have an audible ring nor does the phone automatically bring up the answer screen. Clicking the call notification brings up the answer screen but answering (by swiping up) does not result in an audio connection.
**Expected result:** In either case, a voice call should be established.

### Screenshots
Please ask if you feel they will be useful.

### Device info
Describing the device with DNSfilter enabled:

**Device:** Samsung Galaxy S5
**Android version:** LineageOS with MicroG (Nightly Build from November 13, 2019) (Android 9)
**Signal version:** 4.49.18 (Website Universal Build)

### Link to debug log
I have attached 2 logs from each phone. One set for receiving a call with DNSfilter enabled. Another set for making a call with DNS filter enabled.

These two are for receiving a call with DNSfilter enabled:
Caller (DNSfilter disabled): https://debuglogs.org/171b5983745a6a253cbf45bd0d43ce31e0846b86fcb9c913f85ca0f4d79d6169
Receiver (DNSfilter enabled): https://debuglogs.org/fba7ef45f4f7d642b41d5124da52784337d11cd6a853e6ed6ff79af7e31d990b

These to are for sending a call with DNSfilter enabled:
Caller (DNSfitler enabled): https://debuglogs.org/dcf036e4092251665271efc19f011deee36037cbdb780c702879c49910f7468a
Receiver (DNSfilter disabled): https://debuglogs.org/189bb653952de9855193c3499663ae48b53a2cb214499ca429c2c5bfeaeb3985

### Other comments:
I have two phones. One is a Galaxy S4 and the other is a Galaxy S5. Both devices are configured in about the same way. The problem is reproducible with both devices. The network does not matter; the problem occurs on both WiFi and LTE.

```
This messages shows up several times in the logs and I believe is the exception related to the failure:
2019-11-17 14:34:11.283 CST W SignalServiceMessageSender: Transmitting over unidentified pipe...
2019-11-17 14:34:11.284 CST W SignalServiceMessageSender: java.io.IOException: No connection!
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:157)
	at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:139)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:941)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendCallMessage(SignalServiceMessageSender.java:204)
	at org.thoughtcrime.securesms.ringrtc.MessageRecipient.sendMessage(MessageRecipient.java:62)
	at org.thoughtcrime.securesms.ringrtc.MessageRecipient.sendAnswerMessage(MessageRecipient.java:84)
	at org.signal.ringrtc.CallConnection.sendSignalServiceAnswer(CallConnection.java:339)

2019-11-17 14:34:11.285 CST W SignalServiceMessageSender: Falling back to new connection...
2019-11-17 14:34:11.285 CST W SignalServiceMessageSender: Not transmitting over pipe...
```

Let me know if you feel this bug should be filed against DNSfilter instead.

**Comment by greyson-signal** [comment]
It's unclear exactly what DNSFilter is blocking. If everything works with DNSFilter disabled, then I'd reach out to DNSFilter, or feel free to discuss it in [the forums](https://community.signalusers.org/). Thanks!
