### ISSUE TITLE
Profile not updated correctly, e.g. avatar

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#9201]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After restoring a backup, changes to the profile are not synced correctly to my contacts anymore. However, no error message is displayed on my device, but their's have exceptions in the logs.

### Steps to reproduce
- make profile and trigger a backup
- uninstall signal, reinstall signal
- restore backup and update profile avatar

**Actual result:**  Profile (picture) not updated for my contacts.

**Expected result:** Profile should be updated after reasonable amount of time.

### Device info
**Device:** Xiaomi Redmi Note 7
**Android version:** 9.x.x
**Signal version:** 4.49.18

### Link to debug log
Logs from contact devices.

Android:
https://debuglogs.org/4e325d2c9f62e1e9f1dafee576aa7db934af86e8cf446fef24a4b43ff5b38496

Desktop:
ERROR 2019-11-18T08:34:49.810Z getProfile decryption error: +[REDACTED]891 ProfileDecryptError: Failed to decrypt profile data. Most likely the profile key has changed.
    at Object.decryptProfile (file://[REDACTED]/app.asar/js/libtextsecure.js:36925:21)
    at Object.decryptProfileName (file://[REDACTED]/app.asar/js/libtextsecure.js:36956:32)
    at child.setProfileName (file://[REDACTED]/app.asar/js/models/conversations.js:1780:49)
    at getProfile (file://[REDACTED]/app.asar/js/models/conversations.js:1741:17)
    at async Promise.all (index 0)

**Comment by Meteor0id** [comment]
This issue of profiles not updating is not only related to backups, but also to group chats:
If you're in a group chat, profile names will not update for group members even if they send a message in the group. The profile name updates exclusively upon opening a new or existing one-on-one conversation.


This issue even applies to regular chats, with people whom you are not in a group with:
If you don't chat with someone from an extended period of time and thus don't open the on-on-one conversation for and extended period of time, the profile avatar and profile name will not update either. One may expect them to update every once in a while even if the chats are not opened.

Note that there might also be a privacy issue with the current behavior:
If my client only checks for a profile update whenever I open the conversation, does that mean that my contact could theoretically monitor when I ask for a profile update, and derive from that when I am opening the conversation?

Hoping to see this issue get addressed soon.
