### ISSUE TITLE
contact do not update

### ISSUE THREAD

**Issue by stefanschauer** [signalapp/Signal-Android#9203]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ]x I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I want to update or add contacts, the contacts are not synchronized to signal even when following the instruction on the signal website and delete the signal account on the mobile. I try to keep my mobile googlefree so I am not using the preinstalled contact app but simple contact from fdroid and I installed signal directly from the apk

### Steps to reproduce
- click on a contact
- add the contact to list

**Actual result:** contact still remains unnamed
**Expected result:** contact changes to given name

### Device info

**Device:** FP3
**Android version:** 9
**Signal version:** 4.49.18 (install via apk)

**Comment by greyson-signal** [comment]
When you edit system contacts, we'll eventually be told about changes and refresh, but it can be a few minutes before the system lets us know. If  you want to manually sync them, pull down while you're in the "new conversation" screen. 

If that still doesn't work, grab a debug log (Settings > Advanced > Submit debug log) and post the link here.

**Comment by stefanschauer** [comment]
i did that multiple times. 
here the debug log
https://debuglogs.org/cf831cf553b4f64e0f321a8dcece83f55fd0e35b8eb89dd7d0d1ee057595dbba

**Comment by greyson-signal** [comment]
Logs indicate that we're definitely syncing contacts. What is your problem specifically? Is it that a specific contact isn't updating? Contacts not showing up?

**Comment by stefanschauer** [comment]
the new contact that I added is not showing up in signal.

**Comment by greyson-signal** [comment]
Is this contact a Signal user? You will only see non-Signal users in the app if Signal is your default SMS app.

**Comment by stefanschauer** [comment]
the user independent if it is a signal or a "normal" contact is not shown with the given name in signal. i use signal for sms as well. only contact stored on my sim card are shown correctly.

**Comment by dmhowcroft** [comment]
If you're talking about [SimpleContacts from Simple Mobile Tools](https://github.com/SimpleMobileTools/Simple-Contacts), they explicitly state in their promotional materials "Hide contacts from other apps" (see [this image](https://github.com/SimpleMobileTools/Simple-Contacts/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/app_3.jpg)).

If this is anything like the Open Contacts app on F-Droid, this is intended behavior to ensure that your contacts don't leak to other messaging apps unintentionally. You can probably trigger a Signal message from *within* that contacts app and then add the contact to Signal manually. I'm not super familiar with this app, though; perhaps there is a way to make contacts visible by default or to particular apps.

**Comment by stefanschauer** [comment]
ok thanks a lot for your answer: that seems to be the case. thanks a lot!
