### ISSUE TITLE
Searching Punctuation

### ISSUE THREAD

**Issue by dwong** [signalapp/Signal-Android#9205]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Searching for strings containing punctuation (tried comma and period but not sure if more are affected)

### Steps to reproduce
- Have string "12345.67" in a message
- Search for that string by typing "12345.67"

**Actual result:** Does not find message
**Expected result:** Finds message

### Screenshots

![1](https://user-images.githubusercontent.com/367976/69093329-12835d00-0a03-11ea-8771-c04a692e270c.jpeg)
![2](https://user-images.githubusercontent.com/367976/69093331-12835d00-0a03-11ea-9c60-618d7cfa6cbd.jpeg)
![3](https://user-images.githubusercontent.com/367976/69093332-12835d00-0a03-11ea-8c0a-4da4f879c743.jpeg)

### Device info

**Device:** Samsung Galaxy S9
**Android version:** 9
**Signal version:** 4.49.18

### Link to debug log

Looked at it, but it seemed to contain nothing interesting.

**Comment by pankarlox** [comment]
On the subject #8657

**Comment by dwong** [comment]
Thanks, @pankarlox.  I'll close this one in favor of #8657.
