### ISSUE TITLE
Signal isn't an 'open with' option when intent is to share a group of items

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9206]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal isn't an 'open with' option when intent is to share a group of items

### Steps to reproduce
- open some app which can share media with other apps
- select more than one item
- press the share button
- Signal is not lised as an option

If you try this with only one item Signal is an option.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 9.0
**Signal version:** 4.50.3

**Comment by u32i64** [comment]
@Meteor0id I think this can be closed as sharing of multiple media from outside Signal was implemented in `4.56.*` (currently in beta).
