### ISSUE TITLE
backup to FAT card

### ISSUE THREAD

**Issue by rhetr** [signalapp/Signal-Android#9207]
### Bug description
I have an LG-K428 that for whatever dumb reason only allows FAT-formatted sdcards (ext4, ntfs, exfat all don't work). My internal storage is also almost entirely taken up by Signal so any backups normally crash from a full disk due to the temp backup file in the internal sd cache at around 1GB. With root I was able to symlink the caches folder to a data folder on the external card:

    cd /storage/[external_sdcard]/Android/data/org.thoughtcrime.securesms
    mkdir cache.1
    cd /data/data/org.thoughtcrime.securesms
    mv cache cache.real
    ln -s /storage/[external_sdcard]/Android/data/org.thoughtcrime.securesms/cache.1 /data/data/org.thoughtcrime.securesms/cache
    xid=$(ls -ld . | awk '{print $3}')
    chown -h $xid:$xid cache # not sure if this is necessary

I was pretty satisfied that I figured this out, but I'm stuck and crashing again because FAT32 only allows up to 4GB files, now I crash at 4GB instead of 1GB. Is there a way to detect FAT32 sdcards and chunk the backup db accordingly?

### Device info
**Device:** LG K428
**Android version:** 6.0.1
**Signal version:** 4.49.18

**Comment by greyson-signal** [comment]
Hi there, we use Github for bug tracking, and this is venturing into functionality outside the scope of the app. Feel free to discuss this on [the forum](https://community.signalusers.org/). Thanks!
