### ISSUE TITLE
Idea: Ability to create a conversation group without communicating its number

### ISSUE THREAD

**Issue by ValentinGratz** [signalapp/Signal-Android#9208]
My idea would be to invite a person or a group of people to communicate with us on Signal, without communicating our number. And without the people can see it on the interface.

**Comment by greyson-signal** [comment]
Hi there, as noted in the issue template, we only use Github for bugs, not feature requests. Feel free to discuss ideas on [the forum](https://community.signalusers.org/). Thanks!
