### ISSUE TITLE
Signal modifies/compresses/resizes images sent in chat and then saved back to phone memory

### ISSUE THREAD

**Issue by qubecub** [signalapp/Signal-Android#9211]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Original photos/images sent via Signal chat are modified in the background without a warning by the app!

The same photograph extracted/downloaded/saved from Signal chat back to the phone memory are only a fraction of the size, e.g:

    orinigal size of the photo before posting on Signal: 1.5MB
    size of the same photo extracted/saved from Signal chat: 300KB (!!!)

What happened?

This is unacceptable to modify any user files without a warning or option to "keep original file size" vs "compress / modify".

Be aware that many files contain extra data, e.g. metadata or even steganography embedded information. When Signal modifies the files it damages them irreversibly.

Signal app should not be tempted to shrink/compress images to optimize memory usage. Such action not only damages file/image quality (resolution,compression factor) but also damages metadata and embedded steganography files.

Please keep all the files, including images/photos, unchanged when posting and saving to/from Signal, regardless of their original size.

### Steps to reproduce
The same photograph extracted/downloaded/saved from Signal chat back to the phone memory are only a fraction of the size, e.g:

    step one: orinigal size of the photo (JPG) before posting on Signal: 1.5MB
    step two: send that file using Signal chat.
    step three: extract/save that photo from Signal chat back to phone memory: size shrunk to 300KB (!!!)

What happened to the file? Why did it shrink? How? What's the compression algorithm? Where is warning to users about such background modification?

**Actual result:** 

Photo/image (JPG) extract / saved from Signal chat back to the phone memory is modified to a fraction of its original size (300KB vs 1.5MB of the original size).

**Expected result:** 

Signal app should not be tempted to shrink/compress images to optimize memory usage. Such action not only damages file/image quality (resolution,compression factor) but also damages metadata and embedded steganography files.

Please keep all the files, including images/photos, unchanged when posting and saving to/from Signal, regardless of their original size.

### Device info

**Device:** Samsung Galaxy S7  / herolte / 
**Android version:** 7.1.2
**Signal version:** 4.49.18

**Comment by qubecub** [comment]
This is not just Android specific issue but also Signal Desktop issue. 

I have tested it on Signal Desktop only scenario and the issue persists.
Here is an example:

    open Signal Desktop and send yourself a photograph in a chat (e.g. 1.5MB)
    the photograph appears in a chat.
    hover over the photograph in Signal Desktop and select 'download'/'save' option to extract the image from the chat to a disk.
    Photograph gets extracted but the size of it is oly 300KB (!)

As you can see the photo gets compressed/resized without a warning.

Please investigate and solve the issue. 
Thank you.

**Comment by johanw666** [comment]
AFAIK this is the intended behaviour. Try any other message app, it will probably do the same to prevent excessive use of bandwidth and storage. If you want to send the image unaltered you can send it as document,

**Comment by greyson-signal** [comment]
This is intentional. We compress most things that we can in order to make sending messages faster. We also *explicitly* strip revealing metadata from photos. Most people are unaware that many photos contain GPS data, and so we choose to strip it rather than preserve it. 

These practices are very standard across messaging apps.

> When Signal modifies the files it damages them irreversibly.

To be clear, we only change the copy that we send. The original image in your photo gallery (or wherever the original image is from) is unaltered.

**Comment by qubecub** [comment]
Thank you for your comments.
Could Signal App at least allow for this setting to be customized by users? 
If I wish to preserve original file size for all images sent via Signal all it takes is one 'enable' switch in chat settings. 
At least users could decide themselves whatever is better for them. With memory/disk space constantly growing it's prudent to be able to keep original/unmodified files. 
Signal app should not interfere with the content of the files sent, should not be stripping metadata if not asked to do so. Signal could have a setting to enabling metadata stripping but should not do it without warning. 
Please consider my suggestion for the enhancements and future releases of Signal app. 
Which I like a lot and use all the time. 
I'm grateful you guys work on it, designing and implementing for secure communication. 
Many thanks !

**Comment by KeithCu** [comment]
I use Signal because I want to securely send large images. I hate how many other apps shrink them down. The reason why the other companies do that is because they save them on their servers and use them for their own nefarious purposes later. It's about as crazy as deciding you were going to convert my sentences to using abbreviations to save space ;-) 
R U sure resizn my imgs is a gud idea?
It should definitely be an option, and not the default, and it should probably be configurable such as max resolution, quality, etc.

**Comment by widardd** [comment]
Make this configurable at least, please. "Other Projects do this aswell" is just embarassing as a statement TBH, even If it was true.

**Comment by tijlleenders** [comment]
I realize there's a workaround by renaming the file extension - but if data transfer costs are a real concern (please be open about this) why not make this a paid/sponsors-only feature turned off by default or on-prompt selection when attaching with a "don't ask again"?  
Of course, set a reasonable limit with fair use.
