### ISSUE TITLE
Messages are not showing the time and date in which they were sent

### ISSUE THREAD

**Issue by ValentinaChaconBuitrago** [signalapp/Signal-Android#9216]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a message is sent it only appears how many minutes ago it was created, but not the date and time in which they were sent. There are cases in which due to connectivity issues the messages are not received in order, and showing just minutes may lead to a wrong order in the conversation thread.
 
### Steps to reproduce
- Send several messages
- Experience connectivity issues
- Compare the two conversations on the phone
- Send a message and check the information provided on the lower right corner. 

**Actual result:** The messages are sent in a wrong order and the user receiving the messages doesn't know which is the right order in the conversation thread. 

**Expected result:**  Even when there are mistakes in the conversation thread, having detailed information of the message should help the receiver to understand the order of the conversation. 

### Device info

**Device:** Samsung model SM-A520F
**Android version:** 8.0.0
**Signal version:** 4.49.18

**Comment by greyson-signal** [comment]
We always order messages by the time they were received, but the timestamp on the message will be the time it was sent. We think this is preferable to new messages suddenly appearing in the middle of a conversation.

The timestamps on the message are rendered to be useful in the most common cases. However, if you want to see the full timestamp of any message, you can long press and tap the info icon in the toolbar. You'll see full timestamps of when it was sent and received.
