### ISSUE TITLE
If phone is on DND, incoming Signal calls crash Signal app

### ISSUE THREAD

**Issue by rosejasperfox** [signalapp/Signal-Android#9217]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When phone is in Do Not Disturb (DND) mode, incoming Signal calls crash the Signal app.

### Steps to reproduce
- Turn on Do Not Disturb mode.
- Receive a Signal call.

**Actual result:** The Signal app crashes, and later registers a missed call.
**Expected result:** The Signal app shows an incoming call on the screen without any noise or vibration, permits it to be picked up, and registers it as a missed call if it is not picked up. The Signal app does not crash.

This behavior persists regardless of whether call notifications are turned on within Signal's notification settings.

I originally posted this on #7828 because I had been having the "calls are not silent in DND mode" issue and wanted to test it now that it was reportedly fixed. Technically, the app crashing means calls are silent in DND mode, so I no longer have that problem... but I have this problem now instead.

### Screenshots
None.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.50.5

### Link to debug log
https://debuglogs.org/73c7d619d4dfb3179c8caba9f1648e81236eaebc035fbd11d9400f08878fa8e8

**Comment by ebm539** [comment]
Have reproduced this, only when Do Not Disturb is set to "Priority only".
Alarms only and total silence do not cause Signal to crash.

Running Signal 4.50.6

**Comment by rosejasperfox** [comment]
OP here. I do indeed have DND set to allow the following custom exceptions:

- Repeat callers
- Calls from favorite contacts

**Comment by perdoler** [comment]
Can reproduce the crash. LineageOS 15.1 Official, Signal 4.50.6. DND is "Priority Only", for Calls notification " Override DND" enabled.
