### ISSUE TITLE
Proximity sensor is overly sensitive during voice calls

### ISSUE THREAD

**Issue by moozhub** [signalapp/Signal-Android#9219]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using signal during voice and video calls, the proximity sensor is overly sensitive to the point when having your finger several inches away from the screen will cause the screen to go black. This behavior is noticeable even if the application is out of focus or placed in the android app dock.

### Steps to reproduce
- place a signal call
- when the app is in focus or when docked and minimized in the android dock place your finger over the front of the screen in the general vicinity of the proximity sensor, on two different devices this was reproduced a couple inches (3-4) away from the screen

**Actual result:** Screen will go black until sensor is no longer obstructed. In some cases when the application is docked, the screen will never go to sleep in accordance with what is configured in the Android system settings and will only go to sleep when the proximity sensor is obstructed. The power button in this case is non-functional when attempting to use it to shut the screen off.
**Expected result:** The sensor should not be so sensitive, the sensor should also not be honored when the application is docked which would result in accidentally tripping the sensor when doing other tasks on the phone. Instead, when the application is out of focus the system should fallback to the screens power settings configured in the Android system settings. In it's current state, these sleep settings don't appear to be honored at all during a signal call.

### Screenshots

N/A

### Device info

**Device:** Sony Xperia XZ1 Compact
**Android version:** Android 9 (47.2.A.11.228)
**Signal version:** 4.50.5

Issue was also reproducible on a Google Pixel 2 using the latest version of Android and Signal available for that device.

### Link to debug log

N/A

**Comment by GeorgesPaul** [comment]
Can reproduce (for years now). Using Blackberry KEY2.

**Comment by davidbtc2009** [comment]
Still a problem in 5.42.8
