### ISSUE TITLE
Sha256 missmatch v4.50.5

### ISSUE THREAD

**Issue by mottla** [signalapp/Signal-Android#9223]
The homepage states
29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0 EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26 
Ubuntu sha256sum gives 
70a77c00cc477a5be51e68c66ddec28df582cac4a55cd7fab9f69b8fecc2b1d0

**Comment by bme13** [comment]
Hi. Think this is described here: https://github.com/signalapp/Signal-Android/issues/6478

**Comment by mottla** [comment]
great that solves it, thanks!!
