### ISSUE TITLE
Message draft lost on incomming message

### ISSUE THREAD

**Issue by neumde** [signalapp/Signal-Android#9228]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when writing a message I will start the message switch to some other app and then resume writing before finally sending the message. If I recieve a message while signal is in the backround (still having an unfinished message draft in signal) the draft is lost when I resume signal.

### Steps to reproduce
- open signal
- open a chat
- start typing a message (dont send)
- switch to another app
- recieve a message in the chat with the message draft
- switch back to signal
**Actual result:** The message draft is lost. Somehow the incomming message has "deleted" the draft
**Expected result:** The draft should still be there just like one left it.

### Device info
**Device:** HTC U11
**Android version:** 9
**Signal version:** 4.50.6

**Comment by Viveur** [comment]
Also experiencing this. Happens even when typing a message with Signal in the foreground. If a message is received during composition it causes Signal to 'reload' and lose the draft that was being written.

**Comment by haffenloher** [comment]
As a workaround, you can go back to Signal's inbox and re-enter the conversation, at which point the draft should re-appear (if I remember correctly).

**Comment by danieldjewell** [comment]
Possibly related to #7612 ?

**Comment by shreve** [comment]
I have experienced this same thing, but I'm also having a different effect when it's compounded.

1. Go into convo and type draft
2. Leave app
3. Receive another message, draft is gone
3. Type another draft at a later time
4. Leave app until it refreshes, come back, new draft is gone, old draft is back.

**Comment by haffenloher** [comment]
Yeah, I'm still losing drafts to this sometimes.
