### ISSUE TITLE
Incoming call notifications not working via Bluetooth

### ISSUE THREAD

**Issue by charltonstanley** [signalapp/Signal-Android#9231]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving an incoming signal call, bluetooth enabled devices that are connected to the phone (such as a fitbit, pebble watch, Subaru vehicle bluetooth,) do not get the notification that an incoming call is occurring. This could be related to #3944 or #7679

### Steps to reproduce
- Connect your phone to a bluetooth device that receives notifications
- Have a friend initiate a signal call to your phone
- Signal call is received by your phone, let it ring
- Observe that no notification is received on your bluetooth device that there is an incoming signal call
- Your friend ends the call attempt because there is no answer
- Observe that a notification is now displayed on your bluetooth device showing you that there was a missed call.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Phone calls are missed and you are constantly having to return phone calls.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
-  Notifications should be sent to your bluetooth device when an incoming Signal call is received

### Device info

**Device:** Google Pixel
**Android version:** 10 | Security patch level: Oct 6, 2019
**Signal version:** 4.50.6

### Link to debug log
I wanted to be able to help you guys diagnose this, so I created 3 different captures. 
1. Before the bug
[https://debuglogs.org/8730384b382f0ec924e44f0051e92d4949586c1558be67ff35c91d9073c77064](https://debuglogs.org/8730384b382f0ec924e44f0051e92d4949586c1558be67ff35c91d9073c77064)
2. After a successful notification to a bluetooth device of an incoming **text message** occurs
[https://debuglogs.org/1fe02cb9f218642a48fd6c54bac8318c700741adc6f4c79cda937dbe4b17065f](https://debuglogs.org/1fe02cb9f218642a48fd6c54bac8318c700741adc6f4c79cda937dbe4b17065f)
3. When the bug occurs (failed to send notification to a bluetooth device of an incoming phone call)
[https://debuglogs.org/65df35ed18c20e051e95d832f0edac16e5344359be6eb755be239c37dae0ba13](https://debuglogs.org/65df35ed18c20e051e95d832f0edac16e5344359be6eb755be239c37dae0ba13)

**Comment by refresher** [comment]
Although it is completely my fault trying to pull my phone out of my pocket while driving - I was trying to do so because the I wasn't able to pick up the phone call over Signal with my Bose headset as I usually do - I scratched the paint my front bumper into another car. 
Instead of opening a new issue - I'd just drop a few lines to say that I'd like to bump this issue too.

**Comment by charltonstanley** [comment]
@torxt @dpociu Do either of you have this issue as well by chance?

**Comment by dpociu** [comment]
I certainly do.

Galaxy S10, latest upgrades.

**Comment by LOOHP** [comment]
I can confirm that this is still an issue on the new Galaxy Watch 4 with signal version 5.23.2 on a Samsung phone.

**Comment by new-mikha** [comment]
Same story here. Interesting that two very different types of smartwatches have the same problem: Garmin Fenix S5 and Amazfit GTS 2 mini. 
The phone is Galaxy S7, Android 8.0.0
I recently reset the phone to factory settings, didn't help at all.

I saw posts that were saying it's an Android/Bluetooth/etc issue (e.g. [this one](https://www.reddit.com/r/signal/comments/pkr5ne/signal_calls_notification_on_the_galaxy_watch_4/)). However, WhatsApp somehow manages to work around it. So seems to be a Signal issue to me.

**Comment by LOOHP** [comment]
Pretty sure this is still a bug in the current version.

**Comment by matry-ny** [comment]
I can confirm that this is still an issue on the new Galaxy Watch 5 Pro with Signal version 6.29.2 on a Samsung S22 phone.

**Comment by cody-signal** [comment]
To clarify, are you talking about a call notification like you receive when a regular phone call comes in or the Signal notification that looks like a call notification on the device isn't showing also on the phone? Do other Signal notifications show on the watch?

To add context, it's currently not possible to active the same bluetooth phone call flow from a 3rd party app without some serious baggage. We've tried numerous times, but as of yet, getting a "Call from <blah blah blah>" like you would on a bluetooth headset, car headunit, etc. isn't possible.

**Comment by LOOHP** [comment]
For me, there are no signal call notifications on the watch. All I get on the watch is a "Missed call" notification after the call has dropped.

**Comment by cody-signal** [comment]
Interesting. Thanks for the clarification.

**Comment by schiessle** [comment]
I have the same problem with my Galaxy Watch 4.

Sorry if this is a stupid idea, but if Android doesn't allow third party apps to send call notifications to a wearable device. Maybe sending a normal "text notification" like "John Doe calls you" would be possible? Of course it is not the same like a real call notification, but better than nothing.

**Comment by benner** [comment]
could we reopen this?

**Comment by Stewart8** [comment]
>  it's currently not possible to active the same bluetooth phone call flow from a 3rd party app without some serious baggage. 
Can you please provide some details?  Is the baggage legal (licensing, patents, etc.), technical (hard to do without compromising security, reliability or performance), or something else?  In addition to WhatsApp, Acrobits Groundwire (SIP app) does work correctly in this regard, but I'm not aware of any open source projects that do.

**Comment by cody-signal** [comment]
Mostly reliability. The things we've tried always end up not working on various devices, work but do so poorly/inconsistent, or work so bad folks think there's a security issue when it's just faulty OS behavior.

It's something we also want, and regularly revisit and would welcome any help from the community.

**Comment by rom4nik** [comment]
This probably won't help in all cases, but I'd like to note that after enabling VoIP calls in Gadgetbridge notifications settings I now get Signal call notifications on Pebble Time. Caller ID works, rejecting calls doesn't - notification on watch disappears with success but phone keeps ringing. Still, a noticeable improvement in my case.

![Screenshot_20240821-225609](https://github.com/user-attachments/assets/9a71f81c-7c03-4386-9bb3-9508f151275b)

Signal v7.14.1, Gadgetbridge v0.81.0, Pebble Time on firmware v4.4.0-rbl, Pixel 7 Pro on GrapheneOS 2024080600 (Android 14).

**Comment by ArtjomSchwenk** [comment]
Wanted to bump this issue again, since pebble came back and I'm experience this issue now too. The last comment is now two years old and I was wondering if there where some improvements on androids side that could potentially help with this issue and I found this one: https://android-developers.googleblog.com/2026/05/voip-native-visibility-telecom-alpha.html?m=1

Maybe it's worth to look over this again and see if this can be the fix.
