### ISSUE TITLE
Signature APK Hash (SHA-256) Verification Help - Locking Method Using PIN/Password

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#9234]
This is not really a bug but a feature request to improve security of the app.

Request 1:
Verifying APK Certificate requires complex steps for a users who does not know about all this. But verifying hash of APK itself is really easy. This by no means is a request to choose one over the other. But rather to have both. One hash for APK and the other for Certificate.

Request 2:
Provide an option to lock the app with a PIN/Password/Phrase as an option to/with Fingerprint. This will help users in a variety of situations as you can imagine. For example, someone can easily place target's fingerprint without a user's awareness. While, above options mitigate this case and a user has to be attentive all the time. Downside is the method itself as having access to codes can grant an easy access to anyone.

But user can be advised to use a different code than android's lock screen code to overcome or at least lower the drawbacks of the method.

This is also helpful when the fingerprint sensor itself gets damaged and won't recognize it. Above method therefore will be able to grant user the access with security.

Thank you guys!

**Comment by haffenloher** [comment]
Hey @desmonk, are you using some third-party GitHub client that doesn't display the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md)? In any case, please fill it out when opening an issue. As mentioned in the template, to submit a feature request, please visit the community forums: https://community.signalusers.org/ (you can log in with your GitHub account).
