### ISSUE TITLE
Can’t set Note To Self color

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9235]
This has already been reported in the user forum but because it is really a bug I'll make an issue here.

### Bug description
Since 4.50.6, it is not possible any more to change the color of note to self. Existing settings remain the same but they can not be changed anymore. Further the color palette seems different for note to self.

See user forum issue https://community.signalusers.org/t/cant-set-note-to-self-color/10321

**Comment by greyson-signal** [comment]
This will be fixed in 4.51. Thanks!
