### ISSUE TITLE
Can't share multiple photos from the Google Photos app

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#9237]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When sharing photos from the Google Photos app, I'm not able to share the images directly - only a link that goes through Google Photos.

### Steps to reproduce

* Open an album in Google Photos
* Select two or more images
* Tap Share
* Tap Signal in the list of apps

**Actual result:** Google Photos only offers "Create link" or "Shared album" options
**Expected result:** Google Photos directly shares all the selected images with Signal as it does for some other apps (e.g. Nextcloud)

### Device info

**Device:** Pixel 3a XL
**Android version:** 10 (build number QP1A.191105.003)
**Signal version:** 4.50.6

### Link to debug log

Omitting because AFAIK this is a problem with how Signal's manifests or something so the debug log is irrelevant. If that's incorrect I would be more than happy to provide one, it's just a bit of a hassle.

**Comment by greyson-signal** [comment]
This is known and on our radar. But it's not so much a bug as it is a feature request, since it's additional behavior the app currently doesn't support. But thanks!

**Comment by strugee** [comment]
Hm, okay. I thought it was a bug because it seemed like something that I expected to be working in the current share functionality that wasn't. I guess you're considering it a feature request because it would require new code to handle that situation? I'm just asking so I can better judge where to file things in the future.

Also, is there anywhere where what's on your radar is documented? If so you could point contributors to there so they don't waste their time and yours filing things you already know about.
