### ISSUE TITLE
MMS Downloads not working on AT&T

### ISSUE THREAD

**Issue by erichkeane** [signalapp/Signal-Android#9241]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
MMS photos hit a situation where they get to Error downloading MMS message, tap to retry, and always fail.  I've confirmed here: https://www.att.com/esupport/article.html#!/wireless/KM1218306 that the values are correct.  I note that the server is responding with HTTP412 (precondition failed in the error message), but I have no real way to figure out what that means.

The Proxy setting looks correct, though I have no idea where the IP address comes from (in the log, 166.216.198.5[53]).  All the APN info looks accurate.

I've attempted to reboot the phone, and that doesn't change anything.

### Steps to reproduce
- Unsure how to arrive in this state.

**Actual result:** Photo isn't downloaded
**Expected result:** Photo would download

### Device info

**Device:** Pixel 3XL
**Android version:** 10, Security patch level Nov 5, 2019, Build # QP1A191105.003
**Signal version:** 4.50.6

### Link to debug log

12-02 12:57:10.199  1378  4397 D MmsServiceBroker: downloadMessage() by org.thoughtcrime.securesms
12-02 12:57:10.202  2141 11219 D MmsService: downloadMessage: http://166.216.198.5[53]
12-02 12:57:10.205  2141 11219 D MmsService: Current running=0, current subId=-1, pending=0
12-02 12:57:10.205  2141 11219 D MmsService: Add request to running queue for subId 1
12-02 12:57:10.205  2141 11124 I MmsService: [DownloadRequest@5489654] Executing...
12-02 12:57:10.205  2141 11124 I MmsService: mms config for sub 1: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=-1, enableSMSDeliveryReports=false, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=false, aliasEnabled=false,
supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=20, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true,
maxSubjectLength=0, httpParams=, enableGroupMms=true, emailGatewayNumber=, maxMessageSize=1048576, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false,
enableMultipartSMS=true}]
12-02 12:57:10.207  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: start new network request
12-02 12:57:10.210  2141  2284 I MmsService: NetworkCallbackListener.onAvailable: network=133
12-02 12:57:10.211  2141 11124 D MmsService: [DownloadRequest@5489654] APN name is nxtgenphone
12-02 12:57:10.211  2141 11124 I MmsService: [DownloadRequest@5489654] Loading APN using name nxtgenphone
12-02 12:57:10.221  2141 11124 I MmsService: [DownloadRequest@5489654] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 12:57:10.221  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 12:57:10.223  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: IPv4 provisioned
12-02 12:57:10.224  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: User-Agent=
12-02 12:57:10.445  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: 412 Precondition Failed
12-02 12:57:10.446  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: release, count=0
12-02 12:57:10.446  2141 11124 E MmsService: [DownloadRequest@5489654] HTTP or network I/O failure
12-02 12:57:10.446  2141 11124 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 12:57:10.446  2141 11124 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 12:57:10.446  2141 11124 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 12:57:10.446  2141 11124 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 12:57:10.446  2141 11124 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 12:57:10.446  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 12:57:10.446  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 12:57:10.446  2141 11124 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 12:57:12.446  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: already available
12-02 12:57:12.449  2141 11124 D MmsService: [DownloadRequest@5489654] APN name is nxtgenphone
12-02 12:57:12.449  2141 11124 I MmsService: [DownloadRequest@5489654] Loading APN using name nxtgenphone
12-02 12:57:12.472  2141 11124 I MmsService: [DownloadRequest@5489654] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 12:57:12.473  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 12:57:12.477  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: IPv4 provisioned
12-02 12:57:12.477  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: User-Agent=
12-02 12:57:12.725  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: 412 Precondition Failed
12-02 12:57:12.727  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: release, count=0
12-02 12:57:12.727  2141 11124 E MmsService: [DownloadRequest@5489654] HTTP or network I/O failure
12-02 12:57:12.727  2141 11124 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 12:57:12.727  2141 11124 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 12:57:12.727  2141 11124 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 12:57:12.727  2141 11124 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 12:57:12.727  2141 11124 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 12:57:12.727  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 12:57:12.727  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 12:57:12.727  2141 11124 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 12:57:16.727  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: already available
12-02 12:57:16.729  2141 11124 D MmsService: [DownloadRequest@5489654] APN name is nxtgenphone
12-02 12:57:16.729  2141 11124 I MmsService: [DownloadRequest@5489654] Loading APN using name nxtgenphone
12-02 12:57:16.748  2141 11124 I MmsService: [DownloadRequest@5489654] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 12:57:16.749  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 12:57:16.752  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: IPv4 provisioned
12-02 12:57:16.752  2141 11124 I MmsService: [DownloadRequest@5489654] HTTP: User-Agent=
12-02 12:57:17.005  2141 11124 D MmsService: [DownloadRequest@5489654] HTTP: 412 Precondition Failed
12-02 12:57:17.007  2141 11124 D MmsService: [DownloadRequest@5489654] MmsNetworkManager: release, count=0
12-02 12:57:17.008  2141 11124 E MmsService: [DownloadRequest@5489654] HTTP or network I/O failure
12-02 12:57:17.008  2141 11124 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 12:57:17.008  2141 11124 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 12:57:17.008  2141 11124 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 12:57:17.008  2141 11124 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 12:57:17.008  2141 11124 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 12:57:17.008  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 12:57:17.008  2141 11124 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 12:57:17.008  2141 11124 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 12:57:25.015  2141 11124 D MmsService: Schedule requests pending on SIM
12-02 13:02:39.540  1378  2019 D MmsServiceBroker: getCarrierConfigValues() by org.thoughtcrime.securesms
12-02 13:02:39.540  2141  2369 D MmsService: getCarrierConfigValues
12-02 13:02:39.540  2141  2369 I MmsService: mms config for sub 1: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=-1, enableSMSDeliveryReports=false, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=false, aliasEnabled=false,
supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=20, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true,
maxSubjectLength=0, httpParams=, enableGroupMms=true, emailGatewayNumber=, maxMessageSize=1048576, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false,
enableMultipartSMS=true}]
12-02 13:02:39.540  1378  2019 D MmsServiceBroker: downloadMessage() by org.thoughtcrime.securesms
12-02 13:02:39.543  2141  2369 D MmsService: downloadMessage: http://166.216.198.5[53]
12-02 13:02:39.547  2141  2369 D MmsService: Current running=0, current subId=-1, pending=0
12-02 13:02:39.547  2141  2369 D MmsService: Add request to running queue for subId 1
12-02 13:02:39.554  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Executing...
12-02 13:02:39.554  2141 11744 I MmsService: mms config for sub 1: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=-1, enableSMSDeliveryReports=false, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=false, aliasEnabled=false,
supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=20, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true,
maxSubjectLength=0, httpParams=, enableGroupMms=true, emailGatewayNumber=, maxMessageSize=1048576, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false,
enableMultipartSMS=true}]
12-02 13:02:39.557  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: start new network request
12-02 13:02:39.560  2141  2284 I MmsService: NetworkCallbackListener.onAvailable: network=133
12-02 13:02:39.560  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] APN name is nxtgenphone
12-02 13:02:39.560  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Loading APN using name nxtgenphone
12-02 13:02:39.573  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 13:02:39.573  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 13:02:39.612  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: IPv4 provisioned
12-02 13:02:39.618  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: User-Agent=
12-02 13:02:39.844  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: 412 Precondition Failed
12-02 13:02:39.845  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: release, count=0
12-02 13:02:39.845  2141 11744 E MmsService: [DownloadRequest@ea2b4c8] HTTP or network I/O failure
12-02 13:02:39.845  2141 11744 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 13:02:39.845  2141 11744 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 13:02:39.845  2141 11744 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 13:02:39.845  2141 11744 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 13:02:39.845  2141 11744 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 13:02:39.845  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 13:02:39.845  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 13:02:39.845  2141 11744 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 13:02:41.846  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: already available
12-02 13:02:41.847  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] APN name is nxtgenphone
12-02 13:02:41.847  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Loading APN using name nxtgenphone
12-02 13:02:41.871  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 13:02:41.871  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 13:02:41.875  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: IPv4 provisioned
12-02 13:02:41.876  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: User-Agent=
12-02 13:02:42.124  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: 412 Precondition Failed
12-02 13:02:42.126  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: release, count=0
12-02 13:02:42.127  2141 11744 E MmsService: [DownloadRequest@ea2b4c8] HTTP or network I/O failure
12-02 13:02:42.127  2141 11744 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 13:02:42.127  2141 11744 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 13:02:42.127  2141 11744 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 13:02:42.127  2141 11744 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 13:02:42.127  2141 11744 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 13:02:42.127  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 13:02:42.127  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 13:02:42.127  2141 11744 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 13:02:46.127  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: already available
12-02 13:02:46.129  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] APN name is nxtgenphone
12-02 13:02:46.129  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Loading APN using name nxtgenphone
12-02 13:02:46.154  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] Using APN [type=default,mms,supl,hipri,fota mmsc=http://mmsc.mobile.att.net mmsproxy=proxy.mobile.att.net mmsport=80 name=ATT Nextgenphone apn=nxtgenphone bearer_bitmask=0 protocol=IPV4V6
roaming_protocol=IPV4V6 authtype=-1]
12-02 13:02:46.155  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: GET http://166.216.198.5[53], proxy=proxy.mobile.att.net:80, PDU size=0
12-02 13:02:46.160  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: IPv4 provisioned
12-02 13:02:46.160  2141 11744 I MmsService: [DownloadRequest@ea2b4c8] HTTP: User-Agent=
12-02 13:02:46.373  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] HTTP: 412 Precondition Failed
12-02 13:02:46.375  2141 11744 D MmsService: [DownloadRequest@ea2b4c8] MmsNetworkManager: release, count=0
12-02 13:02:46.375  2141 11744 E MmsService: [DownloadRequest@ea2b4c8] HTTP or network I/O failure
12-02 13:02:46.375  2141 11744 E MmsService: com.android.mms.service.exception.MmsHttpException: Precondition Failed
12-02 13:02:46.375  2141 11744 E MmsService:    at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:216)
12-02 13:02:46.375  2141 11744 E MmsService:    at com.android.mms.service.DownloadRequest.doHttp(DownloadRequest.java:79)
12-02 13:02:46.375  2141 11744 E MmsService:    at com.android.mms.service.MmsRequest.execute(MmsRequest.java:172)
12-02 13:02:46.375  2141 11744 E MmsService:    at com.android.mms.service.MmsService$2.run(MmsService.java:471)
12-02 13:02:46.375  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-02 13:02:46.375  2141 11744 E MmsService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-02 13:02:46.375  2141 11744 E MmsService:    at java.lang.Thread.run(Thread.java:919)
12-02 13:02:54.383  2141 11744 D MmsService: Schedule requests pending on SIM

**Comment by Cerberus0** [comment]
Could be related to https://github.com/signalapp/Signal-Android/issues/9173?

**Comment by erichkeane** [comment]
The logs in that bug seem to show it is related to java.io.FileNotFoundException: open failed: ENOENT (No such file or directory) rather than the server responding with a precondition error.

**Comment by erichkeane** [comment]
Actually, huh... I used the signal setting to submit the log and see I'm getting a similar issue (instead of using ADB). https://debuglogs.org/1ebe6780c56147cb85f0c602475d9f2dfcfed4e88f729a13b7d2a704f48f45d4
