### ISSUE TITLE
Can't Access App When Fingerprint Sensor Gets Damaged

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#9242]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No option to use PIN/Password/Phrase as a fallback, if fingerprint sensor stops working.

### Steps to reproduce
- Install Signal App 4.50.5
- Enable fingerprint lock
- Can't access app when fingerprint sensor is non functional

**Actual result:** Unable to access the app when phone's fingerprint sensor does not work. And user gets locked out as there is no option to use PIN/Password/Phrase in such case.
**Expected result:** App should allow user to create a separate fallback code in addition to fingerprint lock. So when fingerprint sensor gets damaged or become non functional, this will grant user ability to use the app.

### Device info

**Device:** Motorola G5 Plus
**Android version:** 8.0.1
**Signal version:** 4.50.5

**Comment by alan-signal** [comment]
If you damage your fingerprint reader (or finger) you can remove that fingerprint from your system.

If there are no more fingerprints in the system, then the system pin will be used for the lock.

**Comment by desmonk** [comment]
Thank you @alan-signal for the info. But won't you think having a secondary and a different PIN/Phrase would add additional security to the app? I mean one lock for all is quite dangerous.

**Comment by alan-signal** [comment]
> don't you think having a secondary and a different PIN/Phrase would add additional security to the app?

Adding more ways to get into the app would not add additional security, it would actually make it less secure.

> ...one lock for all is quite dangerous.

The only benefit to adding an alternative way in would be to ensure people are not locked out, but I have shown that it is possible to get around a broken fingerprint reader. So you would have to expand on why it is dangerous. We are using whatever lock is set up on the system, if you're locked out of Signal, then you're also locked out of your phone in the first place anyway.

**Comment by nutts0** [comment]
There is more than just broken fingerprint why a fallback makes sense. It simply the option to enter the system password. This would not make the app less secure. Briar has on the log in screen the fingerprint and a little button that takes you to the system password entry. For example when you took a long shower you can't use the fingerprint sensor. U have to wait till the finger dries and the sensor could reconize it again.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests and discussions https://community.signalusers.org/

**Comment by desmonk** [comment]
@nutts0 That would make much more sense. Right now there is no other way around fingerprint lock.

@alan-signal I am sorry to say but you are not getting the gravity of the situation here. A compromised phone lock should not get past additional layer of app lock. This is why I suggested to have a separate mechanism in place. After all, Signal was born out of requirement of security for all for free. One fine example is Robinhood (and similar) app. Nobody can access it without a separate PIN.

This will only help secure the app further. And this discussion is already live on forum.

**Comment by theprojectsomething** [comment]
@alan-signal possibly a slightly different issue but removing fingerprints does not work. I am being asked for a pass phrase on the lock screen having setup only a pin. Tried removing fingerprints and am still asked to enter a non-existent passphrase. Reinstalled the app which deleted my entire chat history and the fingerprint scanner is now available on the lock screen.

**Comment by gessel** [comment]
At least with Android 7, there's no way to delete fingerprints if you can't use the reader once they've been created without root.
