### ISSUE TITLE
APK Hash Needed In addition to Certificate Hash

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#9243]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sorry, but this not a bug. Just a request to ease the verification of APK hash. Certificate verification is more complex than APK hash verification. I understand the importance to verify certificate but it is a not that easy for an average Joe, unless there is an option to do so, please let me know.

### Steps to reproduce
- Goto Signal Website and Download APK
- There is on hash for the APK
- Only hash are of certificate used

**Actual result:** No option to get hash of APK.
**Expected result:** Need hash of APK.

### Device info

**Device:** Motorola G5 Plus
**Android version:** 8.0.1
**Signal version:** 4.50.5

**Comment by alan-signal** [comment]
Please use the community forum for help or discussions https://community.signalusers.org/
