### ISSUE TITLE
Signal 4.50.5 (no-google-version) not possible to install on Android 10

### ISSUE THREAD

**Issue by natrius** [signalapp/Signal-Android#9244]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to install 4.50.5 i get prompted with "Error" without further info. Signal was installed before, uninstalled it so i can import a backup (it should be possible to do without the need to install again...) 

### Steps to reproduce
- Download Signal 4.50.5 from https://signal.org/android/apk/ 
- Open with file browser "Amaze" and klick "install"
- getting prompted with "Error" instead of installation screen

### Device info
**Device:** Xiaomi Mi 9
**Android version:** 10
**MIUI version:** MIUI by xiaomi.eu 11.0.4
**Signal version:** 4.50.5
Google-Apps are installed but i'm still using the website-version of signal. No Google-Account available.

### Link to debug log
Cannot deliver a log through the app. 

I don't have an old version of the APK to try it. No old version available through here https://signal.org/android/apk/ or https://github.com/signalapp/Signal-Android/releases/tag/v4.50.0 here unfortunately :(

EDIT: Added a detail about googleApps

**Comment by natrius** [comment]
Restored a backup and seems like i had 4.50.5 already installed, it just closes immediately when opening after the update to Android10. My old phone, a OnePlus3 (Android9) with lineageos, without GoogleApps 4.50.5 is working meanwhile. 
Could try to provice logcat when needed. 

Right now creating internet for my old phone when needed and no WLAN is available.

**Comment by natrius** [comment]
![Screenshot_2019-12-04-11-35-59-341_com miui bugreport](https://user-images.githubusercontent.com/7243447/70135572-9cc9f300-168a-11ea-825e-ddf149a5dbc9.jpg)

![Screenshot_2019-12-04-11-36-29-112_com miui bugreport](https://user-images.githubusercontent.com/7243447/70135573-9d628980-168a-11ea-8865-b5ba79d49761.jpg)

Unfortunately it is not possible to copy the miui bugreport, so i screenshotted it. Maybe it helps.

**Comment by haffenloher** [comment]
> Restored a backup and seems like i had 4.50.5 already installed, it just closes immediately when opening

This sounds like you restored Signal from an unsupported backup method (i.e. something else than Signal's own backup). That's not going to work. You'll need to uninstall and reinstall Signal, at which point Signal should offer you to restore from any Signal backup you put in the Signal/Backups/ folder on your phone's internal storage. If you need further assistance, please open a thread in the [community forums](https://community.signalusers.org/) and we'll be happy to help (you can log in with your GitHub account).

**Comment by natrius** [comment]
Seems like i miscommuncated. I made a backup via TWRP, i backuped the signal-messages via the signal-app-backup, i updated my xiaomi mi 9, was not able to import the backup because its just possible when reinstalling. So i uninstalled signal, downloaded the APK from the homepage and tried to install again. Mentioned error occured. I restored the TWRP backup (made some problems, would not boot properly), updated android again, Android is booting again, Signal is still installed but won't open anymore. Error from the screenshots appears. 

Hope its clear now.

**Comment by haffenloher** [comment]
> I restored the TWRP backup [...], Signal is still installed but won't open anymore

That's what I was trying to say: If you backup and restore Signal using something like TWRP, it will crash on start due to missing keystore data. You could clear Signal's app data to stop it from crashing.

> downloaded the APK from the homepage and tried to install again. Mentioned error occured.

Sounds like either your APK download got corrupted or you didn't allow installation of APKs from unknown sources in your phone's settings.

Anyway, none of this is about a bug in Signal, so we shouldn't be discussing this in the bug tracker :) let's continue in the [forums](https://community.signalusers.org/)!

**Comment by natrius** [comment]
> That's what I was trying to say: If you backup and restore Signal using something like TWRP, it will crash on start due to missing keystore data. **You could clear Signal's app data to stop it from crashing.**

That was something i did not think about, but i seemed to help. I will make a backup on my other cellphone and import it on the phone where i cleared all the data. 

It should really be available via f-droid, if not via official repository then via a signal-repository. *sigh* But Moxie is stubborn about that :)

Thanks anyway!
