### ISSUE TITLE
Signal crashes on incoming calls of muted contacts

### ISSUE THREAD

**Issue by guimspace** [signalapp/Signal-Android#9246]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal will crash on incoming calls of muted contacts when  
- trying to launch the app
- navigating in the app (selecting a chat or going to settings, for example).

It occurs with muted contacts, and when the call is **still** connecting (BEFORE start ringing).

### Steps to reproduce
1. Signal shows an incoming call notification.
2. Launch the app or, if the app is open, go to settings/select a chat.

**Actual result:** Signal crashes and close. There is no button to Send feedback.
**Expected result:** Signal launches or starts ringing normally.

### Device info

**Device:** ASUS ZenFone3 ZE520KL
**Android version:** 8.0.0
**Signal version:** 4.50.6 - the issue started before at some point in 4.50.x

### Link to debug log
A few seconds after the crash:  
- https://debuglogs.org/8221e15920683f874999a83b388737a29f731a84d835b14609541fbc03f3617a

Immediately after the crash:
- https://debuglogs.org/af71745a26a6e744bdc4feec3c3fd7e7cd4ee7cf6827e381048c44d7affeca82
- https://debuglogs.org/956247e8f33ee6ffdede62aae402256a9d8684d4119494a225a990f5291afa58
- https://debuglogs.org/69656b1c6d773ead1a60b8ff9e4814e7fa642f2504e96c501935682ed02655e5

**Comment by greyson-signal** [comment]
This should be fixed in 4.51.x, which is currently in beta. Thanks!
