### ISSUE TITLE
Bad encrypted message in Android but not in Desktop

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9252]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I had a strange issue: my conversation partner often got "Error handling incoming message" errors in his desktop while the Android client worked OK. He then reset his secure session, and after that I got one "Bad encrypted message" in Android but not in my desktop. After that, everything seems to work OK.

### Steps to reproduce
I have no idea so I realize this might not get sorted out any time soon. ;-)

### Device info
**Device:** Sony Z3 compact
**Android version:** 6.0.1
**Signal version:** 4.51.2

### Link to debug log
My deboglogs:
Android: https://debuglogs.org/b6de300e6dc6250dad6feb2d643ea317cc8d60656ac668d7015829dd68dfe019

Desktop: https://debuglogs.org/67dba573fcd2be4ec07c54476bc62d45e072eb69785f45f07aa3563ab34ed93e

My conversation partner's log:
Desktop: https://debuglogs.org/5d27507b20ba0690698038fb1883acca1e61cff2885f879a07d1b75863d11d2b

Android: https://debuglogs.org/1ac6bae4aedeaf34b55448b3030de6a89399e2910a360d857573cea98041004e

I notice this error in my contact's desktop log:
```
INFO  2019-12-04T13:18:57.251Z received unidentified sender message
ERROR 2019-12-04T13:18:57.251Z queueEnvelope error handling envelope +[REDACTED]425.3 1575410190182 (95e0b1a8-d7b4-4c67-91a2-537b0877312e) : Error: Over 5000 messages into the future! New: 4294967295, Existing: 0
    at SessionCipher.fillMessageKeys (file://[REDACTED]/app.asar/js/libtextsecure.js:36475:17)
    at SessionCipher.<anonymous> (file://[REDACTED]/app.asar/js/libtextsecure.js:36506:27)
```

**Comment by u32i64** [comment]
So I am the conversation partner @johanw666 is speaking about.

---

> my conversation partner often got "Error handling incoming message" errors in his desktop while the Android client worked OK.

Not quite correct, my Android client does **not** show the affected messages at all.

---

To somewhat clear the confusion, below is what I see in Signal Desktop.
In Signal Android I see the same except errored messages aren't present at all.

1 | 2
---|---
Errors like `Over 5000 messages into the future! New: 4294967295, Existing: 0` | Error: `Bad MAC`
[![1]][1] | [![2]][2]

[1]: https://user-images.githubusercontent.com/19972511/70237781-fa3c6d80-1778-11ea-9a03-e611dcec9197.png
[2]: https://user-images.githubusercontent.com/19972511/70237782-fad50400-1778-11ea-9123-c5642e09e5e6.png
