### ISSUE TITLE
Contacts not find, not sync on android version

### ISSUE THREAD

**Issue by jas01** [signalapp/Signal-Android#9253]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After adding a new contacts on my phone this contact is unknown from signal. I'm using signal as signal..but also as sms app, event for the sms I still get the number instead of the name of the contact. This contact install signal also, and I'm able to send him a signal message, but still the name doesn't show.

I'm also unable to find the contact (by name or by number) when I search inside signal.

But with the desktop version (Linux 1.28.0), it's working, I can see the contact name instead of the phone number, so I don't think this is related to some acl matters.

### Steps to reproduce
- Create a contact
- Try to find it from inside signal

**Actual result:** Don't find the new contact as they should
**Expected result:** Well...find the contact ;-)
### Device info

**Device:** Samsung Note 8 
**Android version:** 9
**Contacts software**: Samsung Contacts
**Contacts version**: 10.2.20.25
**Signal version:** 4.51.2

**Comment by bme13** [comment]
Currently I'm also struggling with this. When updating the contacts Signal should be informed and updates it's contacts. If that doesn't happen one can force that manually. Did you already follow the support article about this?
https://support.signal.org/hc/en-us/articles/360007319011-Edit-or-Update-Contacts

**Comment by jas01** [comment]
>  If that doesn't happen one can force that manually. Did you already follow the support article about this?
> https://support.signal.org/hc/en-us/articles/360007319011-Edit-or-Update-Contacts

Sorry, forget to say, Yes I already sync that, I also try every «sync» I find in the phone.

Inside the Contacts App, I can see the signal link, so (as usual) I can send a signal message from Contacts to this contact but not from inside Signal. 

And even I'm not a expert, the fact I can see the contact name from desktop version make me think it's not really a sync problem. As I understand the desktop version pass through the android version to find the contacts

**Comment by bme13** [comment]
Ok.  I forgot to mention that you should be careful with uploading a logfile because it might contain the phone numbers. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-51-release/10430/71

**Comment by jas01** [comment]
> Ok. I forgot to mention that you should be careful with uploading a logfile because it might contain the phone numbers. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-51-release/10430/71

Sorry....I'm not sure to understand you....do you ask me to send the log file ? Or do you ask me to try to delete the contact and resync with nextcloud ? Because I can't do that, event I have backup to a nextcloud I can't delete the contact, I'm using signal for my work 1000 times by day...

If you ask me to send the log file. I still want to take a look and maybe edit the log file,and I don't see how to do that....

**Comment by bme13** [comment]
Sorry, Not trying to confuse you. I don't ask you to delete the contacts or anything.

Normally if you create a ticket one also provides a logfile to give the developers some additional information and I just wanted to warn you that if you were planning to upload a logfile this logfile might contain full phone numbers. Normally that should not happen but I just found out that with this beta version it could happen.

**Comment by greyson-signal** [comment]
I think this should be fixed in 4.51.3. Please try again on that release and let me know. Thanks!

**Comment by jas01** [comment]
> I think this should be fixed in 4.51.3. Please try again on that release and let me know. Thanks!

Absolutely. Everything work fine again. 

Thanks *a lot* for your work.
