### ISSUE TITLE
Crash when attaching photo via [+] button in conversation

### ISSUE THREAD

**Issue by nuchi** [signalapp/Signal-Android#9254]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a conversation, when I click the [+] button to add an attachment, then click "Camera", when I take a picture and have accepted the picture, Signal crashes.

### Steps to reproduce
- Open a conversation (I reproduced with two different ones)
- Click the [+] button
- Choose "Camera"
- Take a picture with any camera app (I reproduced with two different ones)
- Accept the picture

**Actual result:** Signal crashes
**Expected result:** The accepted photo is placed in the photo editing screen just as if I had taken a photo with Signal's built-in camera functionality.

(Worked as of v4.47.7 — updated to the current version yesterday)
(Maybe related to this commit? https://github.com/signalapp/Signal-Android/commit/adc0907906b709a56b4109ceed1340ccf0208159)

### Screenshots
n/a

### Device info

**Device:** motorola MotoG3
**Android version:** 6.0
**Signal version:** 4.50.6

### Link to debug log
https://debuglogs.org/5767b92fd38b466c8f164f74da15af17eb276206e7b2d308228646ade41670e6

**Comment by greyson-signal** [comment]
Strange indeed. Here's the error for reference:

```java
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7, result=-1, data=null} to activity {org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}: java.lang.IllegalArgumentException: Unknown URL file:///storage/emulated/0/Android/data/org.thoughtcrime.securesms/cache/1575564445169.jpg
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:148)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: Caused by: java.lang.IllegalArgumentException: Unknown URL file:///storage/emulated/0/Android/data/org.thoughtcrime.securesms/cache/1575564445169.jpg
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.content.ContentResolver.delete(ContentResolver.java:1321)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.handleImageFromDeviceCameraApp(ConversationActivity.java:637)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.onActivityResult(ConversationActivity.java:547)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.Activity.dispatchActivityResult(Activity.java:6442)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
12-05 08:47:40.561 21807 21807 E UncaughtExceptionLogger: 	... 9 more
```

**Comment by greyson-signal** [comment]
Also, in your logs I saw issues with the APK updater:

```java
11-28 15:51:01.660 16345 16384 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/5478 from pid=16345, uid=10048 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1103)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:795)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:749)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at android.app.DownloadManager.openDownloadedFile(DownloadManager.java:1018)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.getDigestForDownloadId(UpdateApkJob.java:181)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.getDownloadStatus(UpdateApkJob.java:133)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.onRun(UpdateApkJob.java:85)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
11-28 15:51:01.660 16345 16384 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```

Given the history of this permission, I feel like your OS might have some funky stuff going on with it? Seems like it's having problems that should have been solved back in 2013.
https://issuetracker.google.com/issues/36923481

**Comment by nuchi** [comment]
Very bizarre, thanks for digging that up. For what it's worth, until a few weeks ago I was on 4.47.7 Play Store (where I never noticed crashes), then installed 4.47.7 Website. At that point I started noticing sporadic crashes but nothing reproducible. Yesterday I updated to 4.50.6 Play Store and noticed the reproducible crash.

I've been messing with formatting my sdcard as portable and non-portable (though nothing to do with Signal) so maybe something there is weird.

**Comment by nuchi** [comment]
So the crash is caused by trying and failing to delete the image file which was just created and saved to the external cache directory. The stacktrace points to [0].

It looks like the image file is represented by a `captureUri` which is created by `DeprecatedPersistentBlobProvider.createForExternal`[1], which creates a Uri from the external cache directory[2]. That's what's showing up as a `file:///` url. However, it is deleted by `ContentResolver.delete`[0], which it seems (I searched for this error) should only be used to delete files which were created by the `ContentResolver` — I think maybe it should be deleted by something like `new File(attachmentManager.getCaptureUri().getPath()).delete()` instead.[3, 4]

Does that sound right to you? From seeing other people post about this on stackoverflow I'm surprised that the current delete code works at all, but maybe it's the kind of thing that varies by device and some devices are able to call `ContentResolver.delete` on `file:///` URLs and some aren't.

[0] https://github.com/signalapp/Signal-Android/blob/v4.50.6/src/org/thoughtcrime/securesms/conversation/ConversationActivity.java#L637
[1] https://github.com/signalapp/Signal-Android/blob/v4.50.6/src/org/thoughtcrime/securesms/mms/AttachmentManager.java#L446
[2] https://github.com/signalapp/Signal-Android/blob/v4.50.6/src/org/thoughtcrime/securesms/providers/DeprecatedPersistentBlobProvider.java#L77
[3] https://stackoverflow.com/questions/10716642/android-deleting-an-image/10716773
[4] https://stackoverflow.com/questions/26278748/java-lang-illegalargumentexception-unknown-url-file-at-android-content-contentr

**Comment by nuchi** [comment]
No longer relevant
