### ISSUE TITLE
Linking to Desktop 1.29 causes Android 4.50.5 app crash 

### ISSUE THREAD

**Issue by alternativesurfer** [signalapp/Signal-Android#9255]
I don't know whether this should be submitted under Android or Desktop.
Environment....
Desktop 1: Signal v1.28.0
-- Windows 10, 1909
Desktop 2: Signal v.1.29.0
-- Windows 10, 1909

Android 10: Pixel 3
-- Build QD1A.190821.011
Signal: 4.50.5

I have 2 computers linked to Signal (desktop 1 & 2)
Yesterday Desktop 2 updated its Signal to 1.29.0
As soon as that occurred my Signal Android began app crashing, over and over. It wouldn't come up again.

I cleared all app data, restored from a backup Signal made a few hours before.
Signal on Android worked again.
I linked to Desktop 1 (v1.28.0)
Success.
I linked to Desktop 2 (v1.29.0)
Immediate app crash of Signal on my Android.

I restored once more
Linked to Desktop 2.
Immediate app crash

I restored a final time.
Only linked to Desktop 1
No issues all day.

I can't provide a log file for Android as I am never able to open the app again...once the link to 1.29 desktop occurs.

Desktop 2 (1.29) Debug log: https://debuglogs.org/15d3cf339fb9966084145809d5939ad00cf63430de03410d13ef701fe337be78

**Comment by greyson-signal** [comment]
Hey there! Android dev here. So given that you're running 4.50.5, is it safe to assume you're using the website build? If so, there's no crash reporting there, so I don't currently have any means to know what crash is happening on your device. 

One thing you could do, if you're interested, it download a tool called `adb`, which can let you pull logs yourself. Instructions are here: https://developer.android.com/studio/command-line/adb

Once you have adb going, you can run `adb logcat`, open signal, save the logs that come up, and post them here. Thanks!

**Comment by alternativesurfer** [comment]
@greyson-signal 

I linked signal to Desktop 2.
logcat attached.
log records from Signal process not running, I tapped the app to launch, within seconds had the app crash at which point I ended the log.

[signal-crash.txt](https://github.com/signalapp/Signal-Android/files/3933141/signal-crash.txt)

Thanks!

**Comment by Typhic** [comment]
Using 4.50.6 and attempting to link my Android device to Desktop first fails by showing 'device approved', but then when finalizing on the Desktop it says 'Something went wrong'. Every attempt following this shows 'network error'. The QR scan lasts only a fraction of a second--not sure if that's related because my camera isn't all that great quality and may not have time to focus.

**Comment by alternativesurfer** [comment]
@greyson-signal 

I linked signal to Desktop 2.
logcat attached.
log records from Signal process not running, I tapped the app to launch, within seconds had the app crash at which point I ended the log.

[signal-crash.txt](https://github.com/signalapp/Signal-Android/files/3933141/signal-crash.txt)

Thanks!


> 
> 
> Using 4.50.6 and attempting to link my Android device to Desktop first fails by showing 'device approved', but then when finalizing on the Desktop it says 'Something went wrong'. Every attempt following this shows 'network error'. The QR scan lasts only a fraction of a second--not sure if that's related because my camera isn't all that great quality and may not have time to focus.

Yeah, my 4.50.5 is now doing this when trying to link back to my "desktop 1: v.1.28"
It doesn't cause an app crash going to 1.28 but fails to link.
Linking to 1.29 still causes the app crash for me.

**Comment by alternativesurfer** [comment]
@greyson-signal 

Wanted to make sure you saw this: https://github.com/signalapp/Signal-Android/issues/9255#issuecomment-562648540
