### ISSUE TITLE
Android 4.51.0 installed via Play Store (Aurora Store) causes constant crashes

### ISSUE THREAD

**Issue by mfc** [signalapp/Signal-Android#9256]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android 4.51.0 installed Thursday/Friday via Play Store (through Aurora Store) causes constant crashes making Signal unusable. [Normal play store](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms) only has 4.50.6 and the [website apk is 4.50.5](https://signal.org/android/apk) so I assume this release was briefly available via Play Store or is the beta channel (not sure why would show up on Aurora Store)?

the APK has been [previously submitted to Virustotal](https://www.virustotal.com/gui/file/134ec11dad6a0b7b34c9924edc3351ca4909a29b6b1a09ea0ae9eacd3b6e873f/details) and there is no detection of it as malicious. 

I accidentally installed Android 4.51 from play store over an installation of [Signal via website channel APK](https://signal.org/android/apk). I am assuming this is the core of the constant crashes. 

### Steps to reproduce
- be served Android version 4.51 through Play Store
- previously have Signal website APK installed

**Actual result:**
constant crashes, unable to open Signal, send or receive messages. Crash notifications need to be muted to allow use of rest of phone.

**Expected result:**
Signal get updated, or Signal doesn't install update because it is from different update stream (Play Store vs. website APK channel).

### Device info
**Device:** Google Nexus 5X
**Android version:** 0.7-o-2019112632032-dev-bullhead (Android 8.1.0) https://e.foundation
**Signal version:** 4.51.0

**Comment by johanw666** [comment]
4.51 is the current beta channel, to get it via Aurora you need to register as a beta tester at Google. Which 4.51.x have you installed?

**Comment by mfc** [comment]
4.51.0. i guess one of the Aurora Store users used to download is signed up as beta tester? the email address used was `auroraoss@gmail.com`

**Comment by greyson-signal** [comment]
The crashes you're likely experiencing were resolved in later versions of 4.51.x. We don't support the Aurora Store. We're rolling out 4.51.6 right now through the Play Store (we do staged rollouts, but it's in progress).

**Comment by mfc** [comment]
ok great to hear that was a common problem. even better would be updating the APK on the [website](https://signal.org/android/apk/) which is still on `4.50.5` as I have a non-GSF phone. many thanks!

**Comment by mfc** [comment]
`4.51.6` from Play Store (through Aurora Store) fixes the problem. many thanks!
