### ISSUE TITLE
Signal rebuild Android Crash

### ISSUE THREAD

**Issue by noellaby** [signalapp/Signal-Android#9257]
Hello

I wanted to have two signal installations on my phone, so I installed the google play version and I changed the package name of the android and rebuild source code to allow a second install on the same phone so that it does not overlap the storage space. but unfortunately I encounter a problem with the version I changed the package and compile, because the application crash at launch and I do not know do'u come the error. below the logcat:

`12-08 17:24:28.986   729  1848 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ayolaa.messenger/.RoutingActivity (has extras)} from uid 1000 from pid 1443 on display 0
12-08 17:24:28.995   729  1848 V WindowManager: Set focused app to: AppWindowToken{f73b362 token=Token{5068d0a ActivityRecord{3bf7975 u0 com.ayolaa.messenger/.RoutingActivity t531}}} old focus=AppWindowToken{2ec2af2 token=Token{178da54 ActivityRecord{44e5a7 u0 com.android.launcher3/.Launcher t386}}} moveFocusNow=true
12-08 17:24:28.996   729  1848 V WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{f73b362 token=Token{5068d0a ActivityRecord{3bf7975 u0 com.ayolaa.messenger/.RoutingActivity t531}}}
12-08 17:24:28.997   729   777 D ViewRootImpl: hardware acceleration is disabled, fakeHwAccelerated = true, HardwareRenderer.sRendererDisabled = false, forceHwAccelerated = false, HardwareRenderer.sSystemRendererDisabled = false, this = ViewRoot{267f429 Starting com.ayolaa.messenger,ident = 119}
12-08 17:24:28.999   729   777 D WindowManager: addWindowToListInOrderLocked: win=Window{d51e54f u0 Starting com.ayolaa.messenger} Callers=com.android.server.wm.WindowManagerService.addWindow:2778 com.android.server.wm.Session.addToDisplay:181 android.view.ViewRootImpl.setView:645 android.view.WindowManagerGlobal.addView:319 
12-08 17:24:28.999   729   777 V WindowManager: Based on layer: Adding window Window{d51e54f u0 Starting com.ayolaa.messenger} at 3 of 9
12-08 17:24:29.003   198   198 D BufferQueueDump: [Starting com.ayolaa.messenger] this:0xb35533c0, value:0xbeb856b8, iLen:6
12-08 17:24:29.003   198   198 I BufferQueueConsumer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:0,p:-1,c:198) setConsumerName: Starting com.ayolaa.messenger
12-08 17:24:29.003   198   198 I BufferQueueConsumer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:0,p:-1,c:198) setDefaultBufferSize: width=1 height=1
12-08 17:24:29.005   729   777 V WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{f73b362 token=Token{5068d0a ActivityRecord{3bf7975 u0 com.ayolaa.messenger/.RoutingActivity t531}}}
12-08 17:24:29.011   198   198 I BufferQueueConsumer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:0,p:-1,c:198) setDefaultBufferSize: width=720 height=1280
12-08 17:24:29.017   729  1750 D ActivityManager: packageName = com.ayolaa.messenger,state = 0,isFrozen = false
12-08 17:24:29.017   729  1750 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.017   729  1750 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.017   198   391 I BufferQueueProducer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:729,c:198) connect(P): api=2 producer=(729:system_server) producerControlledByApp=false
12-08 17:24:29.018   198  2008 I BufferQueueProducer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:729,c:198) new GraphicBuffer needed
12-08 17:24:29.036   729  1750 I ActivityManager: Start proc 1298:com.ayolaa.messenger/u0a153 for activity com.ayolaa.messenger/.RoutingActivity
12-08 17:24:29.037   729  1750 D SettingsInterface: putStringForUser, name = ITEL_AMS_StartProcessLocked, value = {"Uid":10153,"HostingType":"activity","PackageName":"com.ayolaa.messenger","Pid":1298,"HostingNameStr":"com.ayolaa.messenger/.RoutingActivity"}, for user : 0
12-08 17:24:29.045   729  1847 V SettingsProvider: packageValueForCallResult, name = ITEL_AMS_StartProcessLocked, value : {"Uid":10153,"HostingType":"activity","PackageName":"com.ayolaa.messenger","Pid":1298,"HostingNameStr":"com.ayolaa.messenger/.RoutingActivity"}
12-08 17:24:29.174   729   906 I libPerfService: [perfNotifyAppState] pack:com.ayolaa.messenger, com:.MainActivity, state:1, pid:1298, last_boost_tid:1298
12-08 17:24:29.266  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.345  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.346  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.348  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.349  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.350  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.356  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.358  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.359  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.370   729   951 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.370   729   951 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.376   729  1390 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.376   729  1390 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.385   729  1750 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.386   729  1750 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.391   729  1390 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.391   729  1390 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.397   729  1458 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.397   729  1458 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.400   729  1748 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.400   729  1748 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.409   729  1044 D AppOps  : noteOperation: allowing code 59 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.409   729  1044 D AppOps  : noteOperation: allowing code 60 uid 10153 package com.ayolaa.messenger
12-08 17:24:29.414  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.416  1298  1298 D ActivityThread: installProvider: context.getPackageName()=com.ayolaa.messenger
12-08 17:24:29.649  1852  1854 D GasService: FG app changed: from com.android.launcher3 to com.ayolaa.messenger
12-08 17:24:30.309  1298  1298 E AndroidRuntime: Process: com.ayolaa.messenger, PID: 1298
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.util.JsonUtils.<clinit>(JsonUtils.java:17)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.crypto.KeyStoreHelper$SealedData.serialize(KeyStoreHelper.java:149)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.logging.LogSecretProvider.createAndStoreSecret(LogSecretProvider.java:49)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.logging.PersistentLogger.<init>(PersistentLogger.java:49)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.ApplicationContext.initializeLogging(ApplicationContext.java:209)
12-08 17:24:30.309  1298  1298 E AndroidRuntime: 	at com.ayolaa.messenger.ApplicationContext.onCreate(ApplicationContext.java:113)
12-08 17:24:30.312   729  1390 W ActivityManager:   Force finishing activity com.ayolaa.messenger/.RoutingActivity
12-08 17:24:30.316   729  1390 V WindowManager: Set focused app to: AppWindowToken{2ec2af2 token=Token{178da54 ActivityRecord{44e5a7 u0 com.android.launcher3/.Launcher t386}}} old focus=AppWindowToken{f73b362 token=Token{5068d0a ActivityRecord{3bf7975 u0 com.ayolaa.messenger/.RoutingActivity t531}}} moveFocusNow=true
12-08 17:24:30.317   729  1390 D ActivityManager: isAppLock being paused pacakge =  com.ayolaa.messenger
12-08 17:24:30.323   729  1334 D AES     :     process : com.ayolaa.messenger
12-08 17:24:30.323   729  1334 D AES     :      module : com.ayolaa.messenger v10 (1.0.0)
12-08 17:24:30.323   729  1334 D AEE/LIBAEE: shell: raise_exp(4, 1298, -1361051648, com.ayolaa.messenger, 0x0x993fbce0, 0x0x0)
12-08 17:24:30.327  1335  1335 I AEE/AED : [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 1298, tid: -1361051648, name: UNKNOWN  >>> com.ayolaa.messenger <<<
12-08 17:24:30.327  1335  1335 V AEE/AED : dashboard_record_update() : rec->module = com.ayolaa.messenger 
12-08 17:24:30.618   729  1390 I WindowManager: Screenshot max retries 4 of Token{5068d0a ActivityRecord{3bf7975 u0 com.ayolaa.messenger/.RoutingActivity t531 f}} appWin=Window{d51e54f u0 Starting com.ayolaa.messenger} drawState=4
12-08 17:24:30.618   729  1390 D ActivityManager:  isAppLocked screenshotActivities packageName = com.ayolaa.messenger
12-08 17:24:30.618   729  1390 D EnjoyosServerFacade_enjoyos: packageName = com.ayolaa.messengerisAppLockedIgnoreHasUnlocked = false
12-08 17:24:30.651  1852  1854 D GasService: FG app changed: from com.ayolaa.messenger to com.android.launcher3
12-08 17:24:30.699   729  1749 I ActivityManager: Process com.ayolaa.messenger (pid 1298) has died
12-08 17:24:30.699   729  1749 D ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{c8f82d1 1298:com.ayolaa.messenger/u0a153}, app.pid = 1298
12-08 17:24:30.699   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{19c9136 u0 com.ayolaa.messenger/com.google.firebase.provider.FirebaseInitProvider} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{9ac7837 u0 com.ayolaa.messenger/.database.DatabaseContentProviders$Sticker} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{c9a21a4 u0 com.ayolaa.messenger/.providers.MmsBodyProvider} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{cb87b0d u0 com.ayolaa.messenger/androidx.core.content.FileProvider} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{9188ac2 u0 com.ayolaa.messenger/com.klinker.android.send_message.MmsFileProvider} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{dc660d3 u0 com.ayolaa.messenger/.providers.PartProvider} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{529b410 u0 com.ayolaa.messenger/androidx.lifecycle.ProcessLifecycleOwnerInitializer} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{bfebb09 u0 com.ayolaa.messenger/.database.DatabaseContentProviders$StickerPack} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{a68910e u0 com.ayolaa.messenger/.database.DatabaseContentProviders$Attachment} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{98c372f u0 com.ayolaa.messenger/.database.DatabaseContentProviders$ConversationList} always=false inLaunching=false
12-08 17:24:30.700   729  1749 D ActivityManager: removeDyingProviderLocked: cpr=ContentProviderRecord{6de013c u0 com.ayolaa.messenger/.database.DatabaseContentProviders$Conversation} always=false inLaunching=false
12-08 17:24:30.705   198   393 I BufferQueueProducer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:-1,c:198) disconnect(P): api 2
12-08 17:24:30.705   198   393 I BufferQueueConsumer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:-1,c:198) getReleasedBuffers: returning mask 0xffffffffffffffff
12-08 17:24:30.706   198   198 I BufferQueueConsumer: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:-1,c:-1) disconnect(C)
12-08 17:24:30.711   198   881 I BufferQueue: [Starting com.ayolaa.messenger](this:0xb3551400,id:956,api:2,p:-1,c:-1) ~BufferQueueCore
`
Thanks

**Comment by greyson-signal** [comment]
Hi there, we reserve Github for bugs. If you want to ask general development questions, please use [the forum](https://community.signalusers.org/). Thanks!
