### ISSUE TITLE
Archiving animation in dark theme has jarring light aspects

### ISSUE THREAD

**Issue by brs17** [signalapp/Signal-Android#9258]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using dark theme:

When right swiping to archive a message, a white bar (the size of the message) is shown as part of the archive animation. This feels very jarring in the dark theme.

### Steps to reproduce
- Have a message in the inbox
- Right swipe to archive the message

**Actual result:** 
Archiving animation shows white bar which is quite jarring when using the dark theme.

**Expected result:**
Animation archiving the message should be consistent with the dark theme.

### Screenshots
![signal](https://user-images.githubusercontent.com/7460774/70392939-34d51e80-19a2-11ea-9d32-044d0dd41c77.png)

### Device info
**Device:** Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.51.6

**Comment by ceiphr** [comment]
Same issue. Tested with Android 11 on a Pixel 3XL and Pixel 5. Signal version 5.1.1.

**Comment by fumiakiy** [comment]
This is no longer reproducing as of 5.27.0 (perhaps fixed by other means way before).

**Comment by brs17** [comment]
I can confirm this issue no longer appears to be present in 5.27.3. Going to close this issue. Thank you @fumiakiy for noticing!
