### ISSUE TITLE
Sometimes I don't receive Signal Messages until I open the app

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#9259]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes I won't get Signal IM Messages until I open up the app (then they will all flood in). It might only happen when you haven't used your phone in a while.

**NOTE: I also want to mention that I have Adaptive Battery on BUT the app is NOT optimized and data saver is not on. (I've followed the troubleshooting steps). Signal is also my default for SMS.

### Steps to reproduce
- Don't have app open (and maybe don't use phone for an hour or maybe just go to bed)
- Have someone send you a message

**Actual result:** You won't get the notification/message until you open the app (all msgs flood in).
**Expected result:** You should always get the notification.

### Device info

**Device:** Google Pixel 4
**Android version:** 10
**Signal version:** 4.50.6

### Link to debug log
https://debuglogs.org/fcff22cc7d9d462ad5d4e5c87eeb0d080bd5ee2834ba03d49dabce849b184154

**Comment by UserX404** [comment]
Try this:
Android 8 and above

Follow steps for Android 6 above.

Enable Signal to run in the background.

Android phone Settings > Apps > App Info > tap our app > Battery > turn on the 'Background activity' option.

Android phone Settings > Data usage > Data saver > If data saver is disabled, stop here. If data saver is enabled go to Unrestricted data access > Enable Signal.

https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#android_notifications_troubleshooting_phone

**Comment by Tursko** [comment]
I mentioned in my note that the app isn't optimized and data saver is not on.

**Comment by greyson-signal** [comment]
To the best of my knowledge, you just straight-up aren't getting FCM messages. I can see in your logs that no FCM messages were retrieved for a long time, then you opened the app, and messages were retrieved. There's not a ton we can do right now if the system won't deliver our FCM messages.

**Comment by dwkra** [comment]
I've had the same issue lately. SMS/MMS seem to all arrive on time, but Signal messages are delayed until i open the app. Same battery and data settings as OP, Android 10, just a different phone.

**Comment by siccovansas** [comment]
I'm having the same issue on a Samsung Galaxy S10 with Android 10 since a few weeks. My Signal versions is 4.52.4, but it happened on the previous version as well.

I haven't had this issue before (i.e. the past years) and I double checked that all my background activity/power/data saving settings are correct.

Seeing that @dwkra and @Tursko both also have this issue on Android 10, I guess it might be related to that, possibly in combination with FCM as @greyson-signal suggests.

**Comment by IanSpam** [comment]
I was a big fan of Signal.
447 open issues in Signal/Android at the time I write this seems a lot. Some seem less pressing than others. Delay in getting notification of incoming messages in an "instant" message app seems like it should be near top of list. 
Some answers to this thread seem to talk about the battery comment. Is that related to latency of notifications? Please let me know if it is.
Not getting notified of instant message arrival is a show stopper. I used to think this was the best most secure IM app around. Any responses or comment are most welcome. Please offer some explanation of "_

> There's not a ton we can do right now if the system won't deliver our FCM messages.

_"

**Comment by Tursko** [comment]
> I was a big fan of Signal.
> 447 open issues in Signal/Android at the time I write this seems a lot. Some seem less pressing than others. Delay in getting notification of incoming messages in an "instant" message app seems like it should be near top of list.
> Some answers to this thread seem to talk about the battery comment. Is that related to latency of notifications? Please let me know if it is.
> Not getting notified of instant message arrival is a show stopper. I used to think this was the best most secure IM app around. Any responses or comment are most welcome. Please offer some explanation of "_
> 
> > There's not a ton we can do right now if the system won't deliver our FCM messages.
> 
> _"

My issue RARELY happens. If this issue is happening to you constantly then it's most likely a power management issue. Wdo

**Comment by IanSpam** [comment]
Thanks I see also similar issue talked about in "Messages sometimes show up late and/or in bunches #8692." It is not the same though, because no battery optimisation changes were made on my device.
BIG ISSUE if instant message app is not instant.

**Comment by IanSpam** [comment]
> My issue RARELY (2-3 times since I started using signal 5 montha ago) happens. If this issue is happening to you constantly then it's most likely a power management issue. What phone do you have?

Not a battery optimisation issue. Unless there is something that is not a user setting.
Phone: HTC Desire 530
Android: 6.0.1
Signal: 4.53.7

**Comment by lilsebastian500** [comment]
I went through the checklist, disabled optimization, which was the only thing that wasn't adjusted as required. I still don't receive push notifications from signal. I have 2 other IMs, notifications work just fine there. I hope someone here can enlighten me as to what I am supposed to do now if I want to get signal to send me proper push notifications once someone sends me a message.

Phone: Fairphone 3+
Android: 10
signal: 5.0.4

**Comment by rattkin** [comment]
This is a big problem for me as well. My signal messages and calls never appear, unless i open the app. This is unusable.
Essential ph-1, android 10.

**Comment by rattkin** [comment]
> This is a big problem for me as well. My signal messages and calls never appear, unless i open the app. This is unusable.
> Essential ph-1, android 10.

As soon as I disabled the "adaptive battery" feature completely, i received a batch of signal messages. Seems like the culprit.
Why WhatsApp didn't have this problem?

**Comment by lilsebastian500** [comment]
At the time I disabled the battery optimization, signal was apparently having server problems (probably because whatsapp is making itself very unpopular now and signal is one of the go-to apps that are sought to replace whatsapp but couldn't handle so much traffic at once). Now I do receive notification messages but what I still don't receive (even though I activated the option) are notifications about contacts joining the app and that sucks a bit because I don't know who I can contact via signal and who I have to use whatsapp for

**Comment by lilsebastian500** [comment]
> > This is a big problem for me as well. My signal messages and calls never appear, unless i open the app. This is unusable.
> > Essential ph-1, android 10.
> 
> As soon as I disabled the "adaptive battery" feature completely, i received a batch of signal messages. Seems like the culprit.
> Why WhatsApp didn't have this problem?

And I so don't get this either. No messenger has this problem and why should it? It doesn't make sense. That this feature would prevent me from receiving notifications while my battery is low, okay. But all the time? I can only smh

**Comment by Tursko** [comment]
Hey everyone. The team is trying to solve this issue right now and they are looking for people willing to send in Android debug logs. 

https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

**Comment by mhandlon** [comment]
I'm having the same issue on a Google Pixel 5
Android 11
Signal 5.4.7

**Comment by abhilashkrishn** [comment]
This issue is still there. There is no battery optimization  or data saver for Signal. I confirmed that this issue is happening only for Signal, other apps are instantaneous. I am on latest signal version and already sent debug logs, but still issue is there.

**Comment by HalfWhitt** [comment]
I am now experiencing this as well. (Just got a new Android 10 phone, was on 5 previously.) Signal isn't battery-optimized, it's allowed to use background data, and data saver and battery saver are both entirely turned off.

**Comment by dkolan** [comment]
I just recently started experiencing this issue after reinstalling Signal.

Phone: Samsung Galaxy S10e
Android: 11
Signal: 5.24.7.1

**Comment by hardhub** [comment]
Why is closed if it does not work?

It happens only on Android 10 devices for me. Whatsapp gets notifications fine on the same devices.

**Comment by michaelbutler** [comment]
I use SMS on this phone mostly for PIN verifications from various websites. With signal, I don't receive these messages until I go into the app and send a test message to someone. Even opening the app doesn't seem to receive the SMS. I could go 60 seconds with receiving nothing and then as soon as I send an outgoing SMS I instantly receive the website's PIN verification text.

It's an annoying problem and might not be Signal's fault; it could be something with Android or Google not delivering the messages until user interaction.

**Comment by vincelord** [comment]
I am having this problem since the day I installed Signal. For other people it seems to work, but for me it doesn't - I get no notifications. I would have to open the app in 15 minute intervals to not miss out on something that could be very important.
I did not restrict the app in any way in App Settings, Network Settings or Power Saving Settings and for Telegram and Whatsapp it works flawless.

**Comment by benjastudio** [comment]
Just a follow-up because one of my friend solved the issue on my phone (android) :partying_face:  

In my case, it was due to an unexpected parameter related to power saving. Here is the trick:

(Translation from my french interface)

> Go to Settings > Battery/Power > App launch > found "Signal" > Uncheck the button

In french:
> Aller dans les Paramètres > Batterie > Lancement d'application > trouver "Signal" > décocher le bouton

![Screenshot](https://user-images.githubusercontent.com/9527672/150118853-3b635d56-420d-49e9-9a35-6b78bef08a64.jpg)


The description of the settings (explicitly) tells that when activated the option may delay messages reception... Unfortunately, this option was auto-activated for Signal without me knowing it.  :man_facepalming:

**Comment by DieKoet** [comment]
I've also now run into this issue.  OnePlus 6 with latest official OOS.  Battery optimisation disabled and unrestricted background data enabled for Signal.  All other suggested fixes tried but still the issue persists.  Even unregistered and reregistered my phone number with Signal without success.

**Comment by ilcapatina** [comment]
@DieKoet , the notifications started to work on my OnePlus after I disabled the ‘Deep clear’ option in ‘Recent app management’ and rebooted the device: 

Settings > System > Recent app management > use ‘Normal clear’ instead of ‘Deep clear’

**Comment by Crankle437** [comment]
I've the same problem on Xiaomi EMUI 13 (Android 11). I've followed the troubleshooting steps but it does not help: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

I can receive SMS in time but I don't receive Signal messages at all when the app is closed.

**Comment by oskbor** [comment]
I had this issue on the Unihertz Jelly 2. I found that it had an app blocker that was constantly killing the signal app. To disable it I went Settings -> Intelligent Assistance -> App blocker -> Signal -> disabled all restrictions. Now messages seems to arrive as they should 👍

**Comment by ir33k** [comment]
@oskbor Thanks a lot. I had exactly the same issue on my Unihertz Jelly 2.  Your solution works like a charm.

**Comment by alexpetros** [comment]
@oskbor solution also applies to the Unihertz Jelly Star!

**Comment by dwfmba** [comment]
Fixed this on my daughter's Nokia G10 after changing a dozen settings... It was adaptive battery, toggle off. Battery life is identical, signal delivers immediately now.
