### ISSUE TITLE
Messages sent while desktop app is opening are not received

### ISSUE THREAD

**Issue by uUJsd7PX** [signalapp/Signal-Android#9262]
### Bug description
Messages that are sent during the moment desktop app is opening and loading messages, are not received. They are received on mobile app though during same time.

### Steps to reproduce
- Have mobile app open (not sure if this is required)
- Have another person with mobile app open and ready to write
- Have desktop app linked with same number as your mobile app
- Preferably have some conversation history with a person, so the desktop app takes longer to load messages
- Have a person start sending different messages every second or so (to kep track which ones are received)
- Click to open desktop app
- Keep sending messages until desktop app loads

**Actual result:** Messages sent during loading of desktop app are lost on desktop, even though they are received in mobile app
**Expected result:** Same messages are received in desktop as are in mobile app.

### Device info

**Device:** Desktop, Windows Signal version v1.29.0
**Device:** Iphone, Ios Signal version 3.0.6
**Device (that messages are sent from):** Android

**Comment by dani230** [comment]
Yeah, I have this problem, too.
But you should report it on issues of signal desktop. I think.
