### ISSUE TITLE
Backup issues on device with limited space

### ISSUE THREAD

**Issue by knusprjg** [signalapp/Signal-Android#9264]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The backup feature does not what I would expect.
- It does not save it the external storage (= SD card), as advertised
- The (partial) backup is not erased if it fails generating (e.g. due too low memory)

### Steps to reproduce
- Get an old device with little internal memory
- Send and receive a lot of stuff via Signal
- Get notification from Android that (internal) memory is almost full
- Think that it would be a good idea to do a Signal backup to SD card before truncating chats
- Create backup...

**Actual result:** Despite the description (Backup chats to external storage), Signal creates the backup on the internal memory, which fails soon afterwards due too memory running out.
**Expected result:** Signal creates backup on external storage (= SD card), or let's the user decide where to store the backup. If the backup process fails, Signal purges the partial backup.

### Device info

**Device:** Motorola Moto X Play
**Android version:** 7.1.1
**Signal version:** 4.50.6

### Link to debug log
(I don't think there was a proper debug log created. Anyways, it was probably overwritten during my attempts to free memory.)

**Comment by guillaumedc** [comment]
I'm facing quite the same issue.
Appart that the partial file is removed.
But the backup drains the battery and does not end correctly.

To me, it's secure enought to backup on SD card since the backup file is encrypted.

**Comment by greyson-signal** [comment]
We don't currently support backups to the external SD card for reasons that have been discussed in similar issues in the past. For now we only support backups to internal storage. Selecting storage location would be a feature request, which we handle on [the forum](https://community.signalusers.org/). Thanks!
