### ISSUE TITLE
Airpods - major audio quality issues

### ISSUE THREAD

**Issue by Nykoskos** [signalapp/Signal-Android#9265]
Hi,

I'm using Airpods with Android at it works like a charm with my other apps: phone, FB messenger, Roku etc.
With Signal, when i'm calling with Airpods, people complain to me that the quality is pretty bad, forcing me to switch back to earpods on jack (and then people tell me they can hear me clearly).

Thanks in advance for looking into this issue!

Nico

**Comment by Tursko** [comment]
Please make sure you follow the proper Issue reporting format and also include a debug log.

**Comment by nicotriballier** [comment]
I longer have the problem (i upgraded my phone/hardware + the android version since then). thx!

**Comment by Nykoskos** [comment]
I longer have the problem (i upgraded my phone/hardware + the android version since then). thx!
