### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by cyagit** [signalapp/Signal-Android#9271]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on startup. Gave Signal all the app permissions that it needs. Former version 4.49.X worked. Did an update to 4.51.6 and now it is crashing. 

### Steps to reproduce
- Start Signal

**Actual result:** Crash
**Expected result:** Signal works as expected

### Device info
**Device:** S3 Mini
**Android version:** 4.4.4
**Signal version:** 4.51.6

### Debug Log:
````adb logcat
--------- beginning of /dev/log/main
D/BluetoothAdapter( 2353): 1107645160: getState() :  mService = null. Returning STATE_OFF
I/libblt_hw( 1679): Library opened (handle = 8, fd = 53)
I/libblt_hw( 1679): Library opened (handle = 9, fd = 49)
I/libblt_hw( 1679): Library closed (handle = 6, fd = 62)
I/libblt_hw( 1679): Library closed (handle = 8, fd = 53)
I/libblt_hw( 1679): Library closed (handle = 4, fd = 51)
I/libblt_hw( 1679): Library closed (handle = 0, fd = 50)
--------- beginning of /dev/log/system
I/ActivityManager( 2096): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity} from pid 2323
I/libblt_hw( 1679): Library opened (handle = 0, fd = 50)
I/libblt_hw( 1679): Library opened (handle = 4, fd = 51)
I/libblt_hw( 1679): Library opened (handle = 6, fd = 53)
V/Zygote  (16405): Switching descriptor 32 to /dev/null
V/Zygote  (16405): Switching descriptor 9 to /dev/null
I/ActivityManager( 2096): Start proc org.thoughtcrime.securesms for activity org.thoughtcrime.securesms/.RoutingActivity: pid=16405 uid=10059 gids={50059, 1028, 1015, 1023, 3003, 3002}
W/dalvikvm(16405): Unable to resolve superclass of Lorg/thoughtcrime/securesms/gcm/FcmJobService; (74)
W/dalvikvm(16405): Link of class 'Lorg/thoughtcrime/securesms/gcm/FcmJobService;' failed
I/dalvikvm(16405): Could not find method org.thoughtcrime.securesms.gcm.FcmJobService.schedule, referenced from method org.thoughtcrime.securesms.ApplicationContext.initializePendingMessages
W/dalvikvm(16405): VFY: unable to resolve static method 62728: Lorg/thoughtcrime/securesms/gcm/FcmJobService;.schedule (Landroid/content/Context;)V
D/dalvikvm(16405): VFY: replacing opcode 0x71 at 0x0013
I/dalvikvm(16405): Could not find method android.content.res.Configuration.getLocales, referenced from method androidx.core.os.ConfigurationCompat.getLocales
W/dalvikvm(16405): VFY: unable to resolve virtual method 787: Landroid/content/res/Configuration;.getLocales ()Landroid/os/LocaleList;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
E/dalvikvm(16405): Could not find class 'android.os.LocaleList', referenced from method androidx.core.os.LocaleListCompat.create
W/dalvikvm(16405): VFY: unable to resolve new-instance 382 (Landroid/os/LocaleList;) in Landroidx/core/os/LocaleListCompat;
D/dalvikvm(16405): VFY: replacing opcode 0x22 at 0x0006
W/dalvikvm(16405): VFY: unable to find class referenced in signature (Landroid/os/LocaleList;)
W/dalvikvm(16405): VFY: unable to find class referenced in signature (Landroid/os/LocaleList;)
D/dalvikvm(16405): DexOpt: unable to opt direct call 0x07fc at 0x08 in Landroidx/core/os/LocaleListCompat;.create
I/MultiDex(16405): VM with version 1.6.0 does not have multidex support
I/MultiDex(16405): Installing application
I/MultiDex(16405): MultiDexExtractor(/data/app/org.thoughtcrime.securesms-1.apk, /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes)
I/MultiDex(16405): Blocking on lock /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/MultiDex.lock
I/MultiDex(16405): /data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/MultiDex.lock locked
I/MultiDex(16405): MultiDexExtractor.load(/data/app/org.thoughtcrime.securesms-1.apk, false, )
I/MultiDex(16405): loading existing secondary dex files
I/MultiDex(16405): load found 1 secondary dex files
I/MultiDex(16405): install done
I/dalvikvm(16405): Could not find method android.content.Context.createDeviceProtectedStorageContext, referenced from method androidx.core.content.ContextCompat.createDeviceProtectedStorageContext
W/dalvikvm(16405): VFY: unable to resolve virtual method 566: Landroid/content/Context;.createDeviceProtectedStorageContext ()Landroid/content/Context;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getColor, referenced from method androidx.core.content.ContextCompat.getColor
W/dalvikvm(16405): VFY: unable to resolve virtual method 573: Landroid/content/Context;.getColor (I)I
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getColorStateList, referenced from method androidx.core.content.ContextCompat.getColorStateList
W/dalvikvm(16405): VFY: unable to resolve virtual method 574: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getDrawable, referenced from method androidx.core.content.ContextCompat.getDrawable
W/dalvikvm(16405): VFY: unable to resolve virtual method 578: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getNoBackupFilesDir, referenced from method androidx.core.content.ContextCompat.getNoBackupFilesDir
W/dalvikvm(16405): VFY: unable to resolve virtual method 586: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getSystemService, referenced from method androidx.core.content.ContextCompat.getSystemService
W/dalvikvm(16405): VFY: unable to resolve virtual method 593: Landroid/content/Context;.getSystemService (Ljava/lang/Class;)Ljava/lang/Object;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.getSystemServiceName, referenced from method androidx.core.content.ContextCompat.getSystemServiceName
W/dalvikvm(16405): VFY: unable to resolve virtual method 595: Landroid/content/Context;.getSystemServiceName (Ljava/lang/Class;)Ljava/lang/String;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.isDeviceProtectedStorage, referenced from method androidx.core.content.ContextCompat.isDeviceProtectedStorage
W/dalvikvm(16405): VFY: unable to resolve virtual method 598: Landroid/content/Context;.isDeviceProtectedStorage ()Z
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(16405): Could not find method android.content.Context.startForegroundService, referenced from method androidx.core.content.ContextCompat.startForegroundService
W/dalvikvm(16405): VFY: unable to resolve virtual method 614: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x0006
D/FirebaseApp(16405): com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseApp(16405): com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
D/FirebaseApp(16405): com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
I/FirebaseInitProvider(16405): FirebaseApp initialization successful
I/dalvikvm(16405): Could not find method android.content.Context.getExternalMediaDirs, referenced from method androidx.core.content.FileProvider.parsePathStrategy
W/dalvikvm(16405): VFY: unable to resolve virtual method 583: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;
D/dalvikvm(16405): VFY: replacing opcode 0x6e at 0x009d
E/cutils  ( 1675): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(16405): Failed to ensure directory: /storage/sdcard1/Android/data/org.thoughtcrime.securesms/cache
W/Vold    ( 1675): Returning OperationFailed - no handler for errno 30
E/cutils  ( 1675): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/Vold    ( 1675): Returning OperationFailed - no handler for errno 30
W/ContextImpl(16405): Failed to ensure directory: /storage/sdcard1/Android/data/org.thoughtcrime.securesms/files
I/PartProvider(16405): onCreate()
I/ApplicationContext(16405): onCreate()
W/dalvikvm(16405): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/signal/aesgcmprovider/AesGcmProvider;
D/AndroidRuntime(16405): Shutting down VM
W/dalvikvm(16405): threadid=1: thread exiting with uncaught exception (group=0x41a0cc08)
I/libblt_hw( 1679): Library closed (handle = 9, fd = 49)
E/AndroidRuntime(16405): FATAL EXCEPTION: main
E/AndroidRuntime(16405): Process: org.thoughtcrime.securesms, PID: 16405
E/AndroidRuntime(16405): java.lang.UnsatisfiedLinkError: Couldn't load aesgcm from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-1.apk", zip file "/data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/org.thoughtcrime.securesms-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/org.thoughtcrime.securesms-1, /vendor/lib, /system/lib, /system/lib/ste_omxcomponents]]]: findLibrary returned null
E/AndroidRuntime(16405): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime(16405): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(16405): 	at org.signal.aesgcmprovider.AesGcmProvider.<clinit>(AesGcmProvider.java:25)
E/AndroidRuntime(16405): 	at org.thoughtcrime.securesms.ApplicationContext.initializeSecurityProvider(ApplicationContext.java:192)
E/AndroidRuntime(16405): 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:112)
E/AndroidRuntime(16405): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(16405): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4340)
E/AndroidRuntime(16405): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(16405): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(16405): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16405): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(16405): 	at android.app.ActivityThread.main(ActivityThread.java:5013)
E/AndroidRuntime(16405): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16405): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16405): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(16405): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime(16405): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2096):   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
W/AudioService( 2096): stream was not muted by this client
E/AudioService( 2096): Could not get client death handler for stream: 3
W/AudioService( 2096): stream was not muted by this client
E/AudioService( 2096): Could not get client death handler for stream: 3
I/WindowManager( 2096): Screenshot max retries 4 of Token{423a1f08 ActivityRecord{4245fa38 u0 org.thoughtcrime.securesms/.RoutingActivity t46 f}} appWin=Window{42300058 u0 Starting org.thoughtcrime.securesms} drawState=4
W/WindowManager( 2096): Screenshot failure taking screenshot for (480x800) to layer 21010
I/libblt_hw( 1679): Library opened (handle = 8, fd = 31)
W/ActivityManager( 2096): Activity pause timeout for ActivityRecord{4245fa38 u0 org.thoughtcrime.securesms/.RoutingActivity t46 f}
I/libblt_hw( 1679): Library opened (handle = 9, fd = 58)
I/Process (16405): Sending signal. PID: 16405 SIG: 9
W/InputMethodManagerService( 2096): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@422c4498 attribute=null, token = android.os.BinderProxy@420d1580
I/ActivityManager( 2096): Process org.thoughtcrime.securesms (pid 16405) has died.
````

**Comment by cyagit** [comment]
A quick fix would be highly appreciated because of this crash I cannot communicate via Signal at the moment.

**Comment by 2011** [comment]
I have the same problem. Version 4.50.6 worked fine, but 4.51.6 is a complete disaster. It crashes within seconds of startup (running Android 4.4.2).

**Comment by 2011** [comment]
Problem still exists in 4.52.4. :(

**Comment by cyagit** [comment]
Yes, and it is quite disappointing that the developers do not comment on that bug report nor fix it. As of now I cannot use Signal. Honestly, I expected them to have that already fixed because this is severe. I understand that they have a lot to do but if you push an update on Playstore I expect it to work and not messing up my messenger.

**Comment by dglinder** [comment]
What happens if you go under the app and clear the storage and cache?  This link might help: https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android

**Comment by 2011** [comment]
> What happens if you go under the app and clear the storage and cache? This link might help: https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android

Clearing cache does nothing (same behavior).

I don't understand how you can even suggest clearing storage (losing my private key and my entire message history) as a real solution (meaning other than a debugging step). But I have tried it to locate the problem, with incredibly poor results. The first time I start Signal (with all data deleted) it crashes right away. The second time I start it, the program tells me "Signal is locked," and asks for a passphrase (I have never used a passphrase to lock Signal). A blank passphrase does not work, and thus I can not get beyond that screen to setup Signal from scratch.

Signal has worked perfectly for many years up to and including version 4.50.6. This problem comes from some change(s) to the program by the developers after 4.50.6, but before (or including) 4.51.6.

I have become increasingly disappointed in the direction of Signal recently, with the developers appearing to priorityze adding unnecessary (for private communication) features ("stickers" serving as the most recent example) over the basic functionality of the program. I can not use Signal AT ALL, yet none of the developers have even bothered to reply to this thread.

**Comment by cyagit** [comment]
> What happens if you go under the app and clear the storage and cache?

This suggestion clearly reflects that you don't know what you're talking about. I really wonder why you suggest such a thing...

Anyways, @2011 I totally agree that this situation is highly disappointing. @alan-signal, @greyson-signal: If I may ask - what's your take on that bug?

**Comment by jcollum** [comment]
>This suggestion clearly reflects that you don't know what you're talking about.

A little belligerent there. Have you considered backing up your messages (not the same as cache) and then clearing cache and reinstalling?

**Comment by 2011** [comment]
> A little belligerent there. Have you considered backing up your messages (not the same as cache) and then clearing cache and reinstalling?

Have you read this thread at all? How do you backup messages if the program always **crashes on start**?

I agree that the comment from @cyagit sounds harsh, but I completely understand (and share) the frustration of being completely locked out of Signal (for a month now) with absolutely no comment from the maintainers. I realize the holidays have interrupted the normal routines, but I feel they at least owe us an acknowledgement of the problem.

**Comment by jcollum** [comment]
You can explain why the comment is wrong without "you don't know what you're talking about".

**Comment by greyson-signal** [comment]
@cyagit @2011 This appears to be a device-specific issue, as I can't reproduce it in on my 4.4.4 device. You're hitting some low-level native library loading crash, so I don't have much information to go on. There's no suspicious commits in between 4.50.6 and 4.51.6, so without a physical device that reproduces that crash I can't make headway on this at the moment.

@cyagit Funnily enough, I *do* have a Galaxy S3 Mini in my possession, but it only had official updates until 4.2.2 (and therefore can no longer run Signal, since our minSdk is 4.4).

Are you running a custom ROM? Lineage or something similar? If so, given the nature of the crash, I'd be inclined to say the error lies with the ROM.

**Comment by cyagit** [comment]
Apologies to @dglinder if my comment was a bit harsh. I just wanted to make clear that it can have rather bad consequences to suggest such a solution.

@greyson-signal Thanks for looking into that. Could it have been a commit between 4.49.X and 4.50.6? Because I updated directly from 4.49.X (dont know the exact last version) to 4.51.6. 

Yeah, funny that you own one too - quite an old device. Well, you are right, I run Lineage on it. If the rom is the reason for the crash I get your point that there's not much to be done here. However, I wonder how an update could get wrong like it did in my case.

**Comment by 2011** [comment]
Is there any way to get the debug log out of the app (is it stored somewhere) to post it directly? I have sent two reports after crashes (haven't received any replies).

I know that in the app, the "Submit debug log" function comes up with "The log will be posted publicly online for contributors to view, you may examine and edit it before submitting." How are we supposed to do that? I could never select more than one line (I would like to make certain that only the most relevant parts get included, and I would like to know that someone has at least seen the logs)?

**Comment by greyson-signal** [comment]
> Is there any way to get the debug log out of the app (is it stored somewhere) to post it directly? I have sent two reports after crashes (haven't received any replies).

When you upload a log, it generates a random URL. That isn't reported to us automatically -- you have to send us the link (via Github or support@signal.org). However, if you're experiencing a crash *after* launch, that sounds like a different issue and should be reported as such. This issue prevents the app from opening at all.

> I could never select more than one line

That's an unfortunate limitation at the moment. Our logs are big enough that if we try to use one giant EditText, some Android devices will crash. So we have to render it line-by-line until we can figure out something else. Apologies.

**Comment by greyson-signal** [comment]
> Could it have been a commit between 4.49.X and 4.50.6? Because I updated directly from 4.49.X (dont know the exact last version) to 4.51.6.

I looked through and nothing is standing out to me. I'd need some device to reproduce the crash to do anything else. If you ever had a free afternoon and wanted to install Signal from source and learn about `git bisect` you could probably figure out the exact commit ;)
