### ISSUE TITLE
Errors receiving MMS from non-Signal users (Verizon)

### ISSUE THREAD

**Issue by legaresmith** [signalapp/Signal-Android#9275]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am suddenly have issues receiving all forms of MMS from non-Signal users: videos cannot display/play, GIFs are not animated, and pictures are very compressed/blurry. This all used to work just wonderfully, but it suddenly broke several weeks ago. Videos appear to just be an audio clip (see image below), but upon pressing Play, I get a toast message that says "Error playing audio!" GIFs come through as a static image, no animation. Pictures seem very compressed/blurry. If I switch my default messaging app to Android's Messages, I receive all MMS just fine (videos play and download, GIFs are animated, pictures are not super compressed). Turning Wifi calling has no affect (actually it made GIFs come through as static _black and white_ images?). Turning WiFi off has no affect. Going into airplane mode and enabling mobile data has no affect. I have exhausted my searching and there seem to be some similar issues, like https://github.com/signalapp/Signal-Android/issues/8571 (which is closed), but nothing that fits exactly. Most related issues seem to display an 'Error downloading MMS' message, but I get no such thing.

### Steps to reproduce
- Ask a friend to send me a video, GIF, or picture using any app other than Signal (for example an iPhone user using iMessages)
- Wait for the Signal notification on my phone
- Open the message

**Actual result:** The video appears as an audio clip and upon pressing play, a toast is displayed that says "Error playing audio!", the GIF doesn't animate, or the picture is very compressed/blurry.
**Expected result:** The video has a thumbnail and plays, the GIF is animated, and the picture has a much higher resolution.

### Screenshots
![Screenshot_20191214-133850](https://user-images.githubusercontent.com/17731026/70853256-74f04180-1e79-11ea-8bea-799d992994ac.png)

### Device info
**Device:** Google Pixel 2 (walleye)
**Android version:** 10 (5974827, QQ1A.191205.008)
**Signal version:** 4.51.6 (5792)
**Carrier:** Verizon Wireless

### Access Point
NOTE: I cannot edit my access point because Verizon has locked it down. Everything is dithered (uneditable) except for the APN name. If I delete the access point, I cannot add a new one, the only option is to "Reset to Default" which puts all of this information back to the state listed below.
- Name: Verison
- APN: VZWINTERNET
- Proxy: Not set
- Port: Not set
- Username: Not set
- Password: Not set
- Server: Not set
- MMSC: Not set
- MMS proxy: Not set
- MMS port: Not set
- MCC: 311
- MNC: 480
- Authentication type: None
- APN type: default,supl,dun
- APN protocol: IPv4/IPv6
- APN roaming protocol: IPv4
- APN enable/disable: APN enabled
- Bearer: HSPA, GPRS, EDGE, eHRPD, UMTS, LTE, HSPAP, HSPDA, HSUPA
- MNVO type: None
- MVNO value: Not set

### App State (settings)
- Media auto-download when using mobile data: Images, Audio, Video, Documents
- Media auto-download when using WiFi: Images, Audio, Video, Documents
- 'WiFi Calling' compatibility mode: OFF - I have tried enabling it along with enabling wifi calling on my phone, and it had no effect.

### Link to debug log
https://debuglogs.org/9b4a60daeba75f36ece27ae66e0efeb9e2455c1feaa763d75dd9c7364cde71c6
NOTE: Video/photo/GIF were received on DEc 14, 2019 around 13:30, right at the end of the log.

**Comment by legaresmith** [comment]
Well as of update 4.52.4 I am no longer experiencing this issue!! 🎉 I'm going to close the issue.

**Comment by jbaker6953** [comment]
Still experiencing this issue with Signal 4.52.4. 

https://debuglogs.org/709804ab10fae4175f21a1fab1832abe43e55e4367a8c4dd98e8253966dfb32e

`12-24 17:31:41.058 30011 30208 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.`

**Comment by jbaker6953** [comment]
Opened https://github.com/signalapp/Signal-Android/issues/9300
