### ISSUE TITLE
Crash on startup after updating to 4.50.5

### ISSUE THREAD

**Issue by lealanko** [signalapp/Signal-Android#9281]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to version 4.50.5, Signal crashes on startup. The debug logs and version numbers make me suspect that this is a different issue from #9271.

### Steps to reproduce
I don't know how to reproduce this in any other environment, but here is what I did:

- install Signal from the bare apk file distributed on signal.org on 2019-07-04
- update Signal several times successfully from apk files as newer versions come up
- update Signal from apk file to 4.50.5
- run Signal

**Actual result:** The UI comes up for a moment, but then disappears and a system message informs me that Signal has stopped
**Expected result:** The UI should stay up and allow me to read and write messages.

### Device info

**Device:** Sony Ericsson Xperia Ray
**Android version:** 4.4.4 (CyanogenMod 11)
**Signal version:** 4.50.5

The system does not have Google Cloud Messaging installed.

### Link to debug log

I cannot access Signal's advanced settings, but attached is the `adb logcat` output after attempting to run Signal:

[signal.log](https://github.com/signalapp/Signal-Android/files/3966877/signal.log)

**Comment by Tursko** [comment]
4.51.6 is currently the most up to date version. Maybe give that a try?

**Comment by lealanko** [comment]
The new version is not yet available as an APK, and anyway I'm wary of blindly doing any further updates when it's possible that some sort of data migration has failed.

**Comment by greyson-signal** [comment]
Looks like the crash is here:

```java
12-16 10:52:04.595 W/MigrationJob( 4690): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
12-16 10:52:04.595 W/MigrationJob( 4690): 	at android.app.ContextImpl.getExternalCacheDir(ContextImpl.java:969)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:235)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at org.thoughtcrime.securesms.migrations.CachedAttachmentsMigrationJob.performMigration(CachedAttachmentsMigrationJob.java:35)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at org.thoughtcrime.securesms.migrations.MigrationJob.run(MigrationJob.java:40)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at org.thoughtcrime.securesms.migrations.CachedAttachmentsMigrationJob.run(CachedAttachmentsMigrationJob.java:14)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
12-16 10:52:04.595 W/MigrationJob( 4690): 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```

Looks like your ROM likely has some buggy implementation of a system method. It's possible that `Context#getExternalCacheDir()` returns null, which we guard against. However, the call itself should not crash with an index out of bound exception, which is what's happening. I'd open a bug against Cyanogen.

Unfortunately this is going continue to be an issue for you, even if you update. Best I could offer is a custom build that skips this migration for you. Feel free to email greyson@signal.org if you're interested.
