### ISSUE TITLE
Member deleted signal account but stays in group chat

### ISSUE THREAD

**Issue by neunzehnachtneun** [signalapp/Signal-Android#9282]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In one of my group chats, which is encrypted, there is a person left without signal installed. The person has a new phone number and thus cannot leave the group on his own. It is also not allowed to any other person to remove the contact from the group.
I expected, the person to leave the group automatically, when there is no signal account linked to the phone number. Like it's happening in encrypted chats. When a contact uninstalls signal, encrypted chats are not possible anymore. But in group chats this is not the case.

### Steps to reproduce
- Create encrypted group chat
- Wait until one person deletes signal
- Look into group details and see a person without signal in your encrypted chat.

### Device info

**Device:** Motorola Moto X Play
**Android version:** 7.1.2 / LOS 14.1 without google services
**Signal version:** 4.50.5

**Comment by guimspace** [comment]
Uninstalling the app is not the same as [unregistering/deleting the account](https://support.signal.org/hc/en-us/articles/360007061192-Unregister-or-Delete-Account).

**Comment by neunzehnachtneun** [comment]
Thank you. You are totally right. I need to add: The group member uninstalled signal months ago and also deleted his account.
So one cannot send messages to the person via signal, but nevertheless he is a group member.

**Comment by greyson-signal** [comment]
This is a limitation of groups right now. I don't have a log from you, but it's likely that messages are sending, and they're just kind of being black-holed for that unregistered user. 

We're working on improving groups, which you can read about here:
https://signal.org/blog/signal-private-group-system/
