### ISSUE TITLE
Published version on signal.org/android/apk is outdated

### ISSUE THREAD

**Issue by Glotzon** [signalapp/Signal-Android#9283]
<!-- This is a bug report template. By following the instructions below and filling out the sections with your information, you will help the developers get all the necessary data to fix your issue.
You can also preview your report before submitting it. You may remove sections that aren't relevant to your particular case.

Before we begin, please note that this tracker is only for issues. It is not for questions, comments, or feature requests.

If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

### Steps to reproduce
https://signal.org/android/apk pulished version  4.50.5 whereas Google Play store publishes 4.51.6

**Actual result:** signal.org publishes 4.50.5

**Expected result:** signal.org publishes 4.51.6

### Device info
Any Android device without Google Services

### Link to debug log
not applicable

I fully understand this is an issue not of the actual application, but the web page, but I am not sure where to put the bug other than here. If you close due to wrong location of the bug being raised, please point to the right location.

**Comment by Glotzon** [comment]
Ok, something went wrong, hence one again:

Issue: Signal.org under signal.org/android/apk provides Signal Android application version 4.50.5 which is outdated.

Expected behaviour: Signal.org/android/apk should publish the same version as the Google Play store which is 4.51.6

How to reproduce: Check on Google Play Store and signal.org

Impacted devices: Any Android device without Google Play Services.

**Comment by igor2x** [comment]
Unfortunately this ticket is not bug report. Signal is using Github exclusively for bug reports. And bug reports are counted only the reports that can fully fulfil the bug template.

On this topic there is vibrant discussion on forum. Please join in the forum chat at: https://community.signalusers.org/t/apk-should-be-updated-or-removed/10606

**Comment by Glotzon** [comment]
Thank you Igor2x, much appreciate your feedback, This was my only way to document it.
I will close the issue.
