### ISSUE TITLE
don't show "rate this app" pop-up on first startup for other Android accounts on the same phone

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9285]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
the rate this app pop-up shows immediately after registration and setting up profile, before the user has even seen the conversation overview. He is also offered a choice to permanently dismiss the pop-up. Obviously this will not lead to many useful reviews.

### Device info

**Android version:** 9.0
**Signal version:** 4.51.6

**Comment by alan-signal** [comment]
It should show no earlier than 7 days after app install.

So, you might have seen this happening when you:

 - waited >= 7 days to register.
 - after 7 days, cleared app data and reregistered.

Does that sound likely?

**Comment by Meteor0id** [comment]
In my case this happened directly after first install for a new user on a phone where another user already uses Signal.

**Comment by Meteor0id** [comment]
I see a lot of complaints about thos in app store reviews still in 2021.
