### ISSUE TITLE
Can't reply message using sticker as reply. 

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#9286]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you try to reply a message using an sticker the sticker is sent but no the quoted message.

### Steps to reproduce
- Reply a message.
- Try to send an sticker as reply.

**Actual result:** Sticker is sent but quoted message isn't.
**Expected result:** Message is replied with the sticker.

### Device info

**Device:** Samung Galaxy A70
**Android version:** 9
**Signal version:** 4.52.0

**Comment by haffenloher** [comment]
This is [by design](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-52-release/10643/11?u=haffenloher) (for now).

**Comment by Edu4rdSHL** [comment]
Thanks for the heads up.

**Comment by j-lakeman** [comment]
Hey guys, really appreciate your work on Signal!

Has anything changed since this issue was closed which would make it easier to roll out this feature?

**Comment by greyson-signal** [comment]
It's on our list of things to build 👍

**Comment by j-lakeman** [comment]
Awesome! Looking forward to it!
