### ISSUE TITLE
Put reply button at the end of message actions list

### ISSUE THREAD

**Issue by parkerjm** [signalapp/Signal-Android#9290]
The last official update moved the reply to message button from the last action on the list (the closest to the thumb) to the second from the last, putting the forward message action to the end of the list. This has caused frustration to everyone I've asked about it. No one forwards messages as much as they reply to them, and the most common action should be at the end of the action list as it's closest to the thumb. Please make the reply action the last action. It would make your users happier.

**Comment by greyson-signal** [comment]
We reserve github for bugs. You can make feature requests on [the forum](https://community.signalusers.org/). Also, I suggest that you and your friends use swipe-to-reply, it's much faster :)

**Comment by parkerjm** [comment]
Thank you for the response, didn't realize swipe existed :)
