### ISSUE TITLE
As long as we can't reply with stickers, quote preview should get dismissed when attempting to reply with a sticker

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9291]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is not posdible to quote reply on any message with a sticker. Although it would have been nice to be able to do so, the developers have made clear they choose not yo make this possible for the time being.

Greyson in [a post on the beta feedback didcussion](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-52-release/10643/11?u=meteor0id) :
> Disallowing replies with stickers was an intentional choice due to some design/UX difficulties. Adding support for replying with stickers would require another rollout similar to a lot of our features, where we ship receive support before send support. So no changes on that front in this beta, but maybe in a future release

Meanwhile quote replies with stickers are not handled very well, allowing usrrs to fall into the trap of thinking they can quote reply with a sticker, but ending with the annoying realization that you ended up only sending the sticker eithout the quoted reply.

I am calling this a bug because it seems it was simply forgotten to design an appropriate way to handle replying with stickers.

### Steps to reproduce
- swipe a message to start quote reply
- open the sticker menu and choose a sticker

**Actual result:** 
The sticker sends, but not as a reply. The quoted message preview remains open even after sending.

**Expected result:**
**Assuming replying with stickers (which would be preferable) will not be implemented at this time, the following is expected meanwhile**:
The sticker should not send at all when a quote is being previewed. Instead of sending the sticker, the quote preview should get dismissed and the sticker menu should remain open. If the user still wishes to send the sticker he can simply press it again.
Furthermore there could also be a toast message “You can’t use stickers as a reply” to make even more clear to users why this is happening.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9.0
**Signal version:** 4.52.1

**Comment by tanuki-bellydrum** [comment]
Same problem here, but I don't agree with the expected result.

Shouldn't it behave just like replying with text, images or videos? Afterall, the main purpose of stickers is to react to a message and should therefore be expected to work with the "quote" or "response" feature.

**Comment by Meteor0id** [comment]
The eecelopers had already expressed that tehy do not want stickers to be used as a quote response. I based my expected result on the presumption they want to keep it that way.

Because the quote preview leads tge user to an expectation that he is about to send a quote, he first needs to be shown that he won't be able to do that, before he makes the final desicion to send anyway. Simply sending the sticker and dismissing the preview will lead to an outcome the user could not reasonably expect, he is likely to think it was a bug that the qoutation is missing on his sticker message.

**Comment by pericleskb** [comment]
Would a better option be to display the icon as disabled when quoting? When pressed, a floating message could show.

**Comment by Meteor0id** [comment]
A friend in a group chat just now:
> That sticker went to this message (momentarily forgot you can’t use a sticker when quoting)

That is EXACTLY why I write this GitHub issue.

**Comment by DonDino2** [comment]
Yes this is a bug as I would logically expect my sticker to include the quoted message. Instead it makes me have to type an extra message to explain.
The ideal 'expected result' for me would be to have stickers work as replies to quoted messages.

**Comment by Meteor0id** [comment]
@pericleskb if the stickers are disabled, you can't or won't try to press them and thus also won't get the information why they are not available. I prefer to allow the user to try it but make it visually obvious that he won't be able to send the quoted reply along, as proposed in the expected result in the top post.

**Comment by sivaraam** [comment]
> Meanwhile quote replies with stickers are not handled very well, allowing usrrs to fall into the trap of thinking they can quote reply with a sticker, but ending with the annoying realization that you ended up only sending the sticker eithout the quoted reply.

I fell for this trap, recently. My case was a little different, though. I quoted a message and was about to send an emoji as a reply. That's when the sticker suggestions related to that emoji came up. I clicked on one of the sticker suggestions. The sticker was sent but the message was not quoted. I was confused. Only after sometime did I realise that stickers can't be sent for a quoted message.

It would be nice if you don't show the sticker suggestions, at the least, when someone is about to send an emoji as a response to a quoted message.

**Comment by chompshock** [comment]
I came here to write this exact issue. Thought I could send a sticker as a reply to another message since the preview comes up only to realize this was not possible.

Not good for UX.

**Comment by AmaaniGoose** [comment]
Same here, had this same issue. Stickers should be able to be used to react to messages but if the developers don't want it, there should be a popup informing us.

**Comment by sivaraam** [comment]
Keep open please.

**Comment by eldiosx** [comment]
We have been waiting for this for more than 2 years, the people I bring from other systems like whatsapp are very upset about this and they leave.

**Comment by UserX404** [comment]
Staff is using Github as bug tracker.
Please keep freature requsts and discussion in the forum.
https://community.signalusers.org/t/send-stickers-as-a-reply-to-a-quoted-message/12919

**Comment by cody-signal** [comment]
What @UserX404 said
