### ISSUE TITLE
"Can't open Signal" when switching to app.

### ISSUE THREAD

**Issue by dscotese** [signalapp/Signal-Android#9292]
- [x] I have searched open and closed issues for duplicates
***This looks like a dupicate of #4938, but rebooting the device is NOT a reasonable expectation for users to employ***
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If my Android is using enough memory, then I can't switch to Signal.  When I select it from the list of "recently open apps" it responds with "Can't open Signal."

### Steps to reproduce
- Reboot your Android
- Open Signal
- Open some (more) apps that use some memory (I only had to use Chrome but I have a lot of tabs open)
- Switch between apps, and if it doesn't say "Can't open Signal" when you choose Signal, then go back to the third step.

**Actual result:** System message "Can't open Signal" appears on the home screen or other page of icons.
**Expected result:** Signal should catch the problem and arrange itself to work, (possibly by allocating more memory?)

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.51.6

### Link to debug log
https://debuglogs.org/27ed4fc37e6cd64e8aaeafdaa58f4c16ac9f7df4e19a1b4c39f233e4661afea8

**Comment by shreyasminocha** [comment]
Can reproduce with:

- **Device**: Oneplus X (onyx) 
- **OS**: Android 9 (Resurrection Remix 7.0.2) 
- **Signal**: 4.52.4

**Comment by supermar1010** [comment]
For me if I leave the app it immediately disappears the open app view. And u have to go to my home screen to start it again.
It always starts in the main page even though seconds before I was in a chat.
But it starts much faster then it does normally, so it seems like it is in between two states or something like this
Device: OnePlus 3t
OS: oxygenOS 9.0.6, android 9
Signal version: 4.52.4

**Comment by ondondil** [comment]
Same issue here
**Device:** Nokia 6.1
**OS:** Android 9
**Signal version:** 4.52.4
### Link to debug log: 
https://debuglogs.org/e71788ea70dc1b93a11aad99c8663e676837778b2f3afb2e0743f2fe3ea57627

**Comment by sivaraam** [comment]
I also faced this issue but for a different "Steps to reproduce". I [initially reported](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-52-release/10643/77) it in the Signal community. For the sake of completeness, the steps I followed is given below:

1. Open Signal
1. Ensure that you are in conversation list view
1. Tap on ‘Back’ button (to exit Signal)
1. Tap on ‘Recent apps’ button
1. Tap on Signal

**Comment by ondondil** [comment]
Since I updated to Android 10 I can no longer reproduce the issue.

**Comment by billie80** [comment]
Can reproduce with the steps @sivaraam mentioned.

The error message I get is "Could not start Signal"

https://debuglogs.org/406c6528d547067fdcd708c16ba5a0864853f3ad722d4da4bc2f49a15c5c798a

**Comment by greyson-signal** [comment]
@billie80 Unfortunately I see not crashes in that log at all. Signal's logs cover around 3 hours, and the system logs cover ~4min. Out of curiosity, how long after the crash did you wait before taking a log?

**Comment by billie80** [comment]
Hm I think I did it immediately after it crashed. I can try again however!

**Comment by billie80** [comment]
This debug log is created immediately after the "crash"

Maybe however there is no crash at all. It just says "Could not start Signal". So maybe it is not a crash causing this issue.

https://debuglogs.org/60ab526fed9877074496932673e0f837d3ec3a7fdf8b6645e9e6700f44e426be

**Comment by billie80** [comment]
Just FYI I am now on Android 10 where I also can not reproduce the issue!

**Comment by bme13** [comment]
Following the steps provided by @sivaraam I'm able to reproduce this. Unfortunately the log also doesn't give additional information so I checked with adb. I then see the next output:
```
07-25 20:13:28.683  4340  4789 W ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.thoughtcrime.securesms/.MainActivity } from null (pid=-1, uid=10107) not exported from uid 10150
07-25 20:13:28.688  4568  4669 E SystemServicesProxy: Kan Signal niet starten.
07-25 20:13:28.688  4568  4669 E SystemServicesProxy: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.thoughtcrime.securesms/.MainActivity } from null (pid=-1, uid=10107) not exported from uid 10150
```
Googled that and based on the result I added 
android:exported="true" in the MainActivity section of AndroidManifest.xml
That solved it for me. 
The MainActivity now looks like:
```
  <activity android:name=".MainActivity"
              android:theme="@style/Theme.Signal.DayNight.NoActionBar"
              android:launchMode="singleTask"
              android:exported="true"
              android:configChanges="touchscreen|keyboard|keyboardHidden|orientation|screenLayout|screenSize" />
```
My device details (copied from a debug file header):
Phone: SM-G960F
Product : lineage_starlte
Android 8.1.0
App Signal 4.67.2

**Comment by dscotese** [comment]
I haven't noticed it recently, so probably not.  Anyone else?
