### ISSUE TITLE
Occasionally a picture is not completely rendered on sending device.

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#9294]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Occasionally when sending a picture it is not completely rendered on the sending device. Half of the image is shown while the rest remains gray. On the receiving device the picture is shown correctly and also in the conversation overview the image is showed correct. After a forced restart of Signal the image is displayed correct in the conversation.

### Steps to reproduce
Unable to reproduce. Seems to happen randomly and rare.

**Actual result:** See screenshot
**Expected result:** Full image is shown

### Screenshots

![Screenshot_20191219-215845_Signal](https://user-images.githubusercontent.com/25846829/71269283-4548aa00-234f-11ea-9a5f-217da997a904.jpg)

### Device info

**Device:** Samsung SM-G960F
**Android version:** 9
**Signal version:** 4.52.1

### Link to debug log

https://debuglogs.org/e07eedf49d04e2467f6bd84c2c2fb95fc32ca984ca74aa0d0c9392d887471e09

**Comment by centromere** [comment]
I am having the same issue.

![signal-2019-12-22-080240](https://user-images.githubusercontent.com/543423/71327240-26275500-24d4-11ea-853f-a5b770c8322e.jpg)

![Screenshot from 2019-12-22 15-46-39](https://user-images.githubusercontent.com/543423/71327243-33444400-24d4-11ea-8f49-9cd608cbcaf6.png)

**Comment by centromere** [comment]
![Screenshot from 2019-12-22 16-01-17](https://user-images.githubusercontent.com/543423/71327261-57a02080-24d4-11ea-992f-3460d43cb39f.png)

**Comment by Kevinmartin007** [comment]
I can't even send/receive mms so at least you can send and receive

**Comment by Tursko** [comment]
This is a known issue and has to do with the thumbnail generation. Clearing the cache will make them auto generate.

**Comment by centromere** [comment]
I am not certain that's the case. It seems the issue is with the file itself, not a thumbnail, as the evidence above shows.

**Comment by Tursko** [comment]
> I am not certain that's the case. It seems the issue is with the file itself, not a thumbnail, as the evidence above shows.

Yours might be different because the OP says after a force restart it shows properly
