### ISSUE TITLE
Crash on startup on 4.52.4 or any older builds

### ISSUE THREAD

**Issue by undeFX91** [signalapp/Signal-Android#9296]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on startup. Signal has all the app permissions that it needs. Re-installing, trying older versions, installing without Chat-backup, updating to latest version, clearing cache and wipe system cache all didn't help.  When network-connections are disabled the App is opening, when re-enabling WiFi or mobile network it is crashing again.

### Steps to reproduce
- Start Signal

**Actual result:** Crash
**Expected result:** Signal works as expected

### Device info

**Device:** Galaxy S8+ SM-G955F
**Android version:** 9
**Signal version:** 4.52.4

### Link to debug log
I cannot access Signal's advanced settings, but attached is the adb logcat output after attempting to run Signal:
[log.txt](https://github.com/signalapp/Signal-Android/files/3991299/log.txt)

**Comment by johanw666** [comment]
```
java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.SecurityException: uid 10357 cannot explicitly add accounts of type: org.thoughtcrime.securesms
```
Clumsy to handle this via an assertion instead of giving at least a popup or toast and then exiting graceful.  But I've never seen this error before - perhaps such an account already exist?

**Comment by undeFX91** [comment]
I didn't install non-official builds.
I am using Signal over a year now with this account. And this crashes started like just a week ago and I have no idea why.

**Comment by software4future** [comment]
Hi Folks,
same problem here.  Up to now no problems with Signal app on Lineage OS 14 => Android 7. Two days ago I have upgraded all devices to Lineage OS 16 => Android 9. Today two devices are having an issue. Signal crashes after start, no window, no error, no message. All devices are running 4.52.4. Two are still working. Reinstalling Signal (apk-download from signal.org version 4.52.4) doesn't change anything. We are now loosing communication ... any ideas? I am already waiting for the other two also start crashing.

**Comment by undeFX91** [comment]
Is there any way to get feedback and help with my issue? 
I still can't use Signal.
I noticed if I am on a WiFi Connection with my smartphone and disable the InternetAccess on the WiFi-Router ( so that my phone has a WiFi Connection without Internet) I can open Signal without crashing. If I then re-enable the Connection to the Internet on my Router Signal is working with Network-Connection and I can use it like normal. But after like one hour, the same old Issue appears again and it crashs like before

**Comment by elye** [comment]
This might be an increasing trend of such crash on Android 9 and Android 10? https://stackoverflow.com/q/62656740/3286489

**Comment by greyson-signal** [comment]
I think we discovered this was a result of people installing forks of Signal that didn't properly switch to a new account name constant. If you have any other Signal forks installed, the solution would be to uninstall them.

**Comment by AceyIo** [comment]
@greyson-signal What has to be changed actually? What do you mean by "new account name constant"?

**Comment by greyson-signal** [comment]
@AceyIo This: https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/contacts/sync/DirectoryHelper.java#L318

This used to be a static string that was the same as the application ID, and we have since changed it reference `BuildConfig.APPLICATION_ID`.

**Comment by AceyIo** [comment]
We already has this in our BuildConfig, configured to our own app id, but still keeps crashing. I bet it should be our own app id, right?

**Comment by greyson-signal** [comment]
@AceyIo I don't know what your specific setup is. If you registered an account with a unique string it should be fine. We use github for bugs though, not support. Feel free to discuss this further on the [forum](https://community.signalusers.org/). Thanks!
