### ISSUE TITLE
MMS won't send or receive

### ISSUE THREAD

**Issue by Kevinmartin007** [signalapp/Signal-Android#9299]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

MMS will not send nor can I receive MMS messages 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

Send/receive MMS message 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

MMS shows error downloading

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The MMS message should download and present picture.

### Device info

**Device:** Samsung 10 plus 
**Android version:** 10 (Q)
**Signal version:** 4.52.4

### Link to debug log

https://debuglogs.org/98cd13ae6d5ddaa1fb88be369a1342087446fc4172c896246f2d3417383455ca

**Comment by Cerberus0** [comment]
It might be helpful if you could include your carrier in the title and device info section. Thanks!

**Comment by Kevinmartin007** [comment]
Sorry. It's T-Mobile

**Comment by dlemire60** [comment]
Having similar issues here with two different Moto G5s Plus phones.  Our phones are on Spring (via Ting). Four other correspondents are a mixture of Android phones and carriers, including Google Fi. Having both failures downloading and sending MMS.

Signal version 4.52.5 (5841)
Android version:  8.1.0, security patch level is 01-Aug-2019

Debug log link (for one phone):  https://debuglogs.org/ed78abf9de97c9bcfdaeb1aa1166976b6becc2eaa3510d4ddf6db7d4d3d66447

Log file may be foreshortened as I restarted the phone.

**Comment by Toniob** [comment]
Hi,
Same issue here. On a Xiaomi Mi 8, under Lineage OS 16 without gapps. On two different carriers : Orange and Free Mobile. Signal version is 4.52.4.

**Comment by usmarine2141** [comment]
I have same issue 

samsung note 10 
droid version 10
carrier ATT
signal version 4.52.4

**Comment by Kevinmartin007** [comment]
Any movement on this issue? Its really annoying.

**Comment by Z3ROGRAV1TYx** [comment]
I was screwing around with Netguard settings and disabling a few apps the other day, including some google ones.. about a day later I started having issues with MMS and Notifications. So I started allowing basically all google apps through, and reenabling, and now I still can't get MMS to come through. It comes, but doesn't download. I can send to SOME PEOPLE (non signal) but also some people error when sending. Literally disable netguard and still having issues.

On a sidenote, also having issues with notifications from people who use signal not pushing unless I open the app. SMS/MMS notifications come through mostly all the time it seems while in background, it just seems to be a signal user thing. I've tried reinstalling signal, didn't fix either of these issues for me. Not sure what's going on. Been working fine for the past year.

lgv40 (tmobile), tmobile, signal 4.53.6, android 9

**Comment by gab12** [comment]
I confirm, I have the same problem with Orange/SoSh (First operator in France). Impossible to receive the MMS on my Samsung Android 7.1.1 :'(

**Comment by UserX404** [comment]
I also noticed this behavior. After deleting all APNs and only setting up mms APN i was able to send and receive mms. But after adding my mobile data APN (default apn) i stuck in this behavion again.
@greyson-signal  Sent you a PM in the forum with logs.

**Comment by JCDetwiler** [comment]
I have this issue too---I can't send and receive MMS (with non-Signal users). However, it goes through when I turn off WiFi.

Using a OnePlus 7T Pro 5G McLaren, Android 10.0.27.HD61CB, T-Mobile, and Signal 4.57.1.

**Comment by Kevinmartin007** [comment]
Enable wifi calling within the settings on signal

 

 

 

 

 

 

 

 

Kevin Martin │ Systems Engineer 
Triencon Services, Inc. | 1000 Post & Paddock Ste. 200│ Grand Prairie, TX 75050 
P:  <nxphone:817.703.4642> 817.703.4642 │ F:  <nxphone:817.887.2948> 817.887.2948 
Email:  <mailto:kevin.martin@triencon.com> kevin.martin@triencon.com

 

THIS ELECTRONIC MESSAGE CONTAINS INFORMATION FROM TSI GROUP, WHICH MAY BE COMPANY SENSITIVE, PROPRIETARY, PRIVILEGED OR OTHERWISE PROTECTED FROM DISCLOSURE.   THE INFORMATION IS INTENDED TO BE USED SOLELY BY THE RECIPIENTS NAMED ABOVE.  IF YOU ARE NOT AN INTENDED RECIPIENT, BE AWARE THAT ANY REVIEW, DISCLOSURE, COPYING, DISTRIBUTION OR USE OF THIS TRANSMISSION OR ITS CONTENTS IS PROHIBITED.  IF YOU HAVE RECEIVED THIS TRANSMISSION IN ERROR, PLEASE NOTIFY SENDER IMMEDIATELY AND DELETE THIS MESSAGE

**Comment by UserX404** [comment]
Another   [url=https://debuglogs.org/37ad90a01d5af07dc982d4cdc2a44618ec16b699d3b3929696cb1f94dd7039ec]Debug Log[/url]

**Comment by figurecasualty** [comment]
MMS  can't Send or Receive to Non Signal Users only.

I have had Signal for years and have never been able to Send MMS to or Receive MMS from a non-user.

Using 2 Androids with Android 6.0

This has occurred over several carriers (definitely Sprint in the USA, possibly also Verizon), countries, and continents, so it is clearly a Signal issue, as also shown by the Github's.

Numerous Github's have been opened over the last 4 + years, but they get closed  without solving the Signal issue.

I had falsely assumed it is something Signal does purposely to encourage users to recruit other users vigorously so they can send/receive pix, but I realize now this is not the case.

Today it caused me a serious delay with a very important time-sensitive issue which could have caused me a great deal of serious problems, as someone sent me several pix which as always 
resulted in 4 non-images.
I wasn't able to get them resent via email for hours.

I am regretfully going to have to leave Signal if nothing will be done about this.

Most people who are downloading Signal are not aware of Github and even if they are, they will simply delete and look elsewhere.

For that matter, no solution has been found when there is a Github opened.

A serious failing of this app.

**Comment by seniorm0ment** [comment]
relevant

**Comment by seniorm0ment** [comment]
relevant

**Comment by UserX404** [comment]
@UserX404 
Would report this issue has been solved for me since ~2021(?)
