### ISSUE TITLE
Cannot receive video MMS from non-Signal iPhone users

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#9300]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video and/or audio MMS sent from non-Signal iPhone users will not play. Always reports "Error playing audio."

### Steps to reproduce
- Have an iPhone user send a video or audio by MMS using a non-Signal messaging app
- Press the play button in Signal

**Actual result:** "Error playing audio file"

**Expected result:** Video or audio plays

### Device info

**Device:** Google Pixel XL
**Android version:** 7.1.2
**Signal version:** 4.52.4

### Link to debug log

https://debuglogs.org/709804ab10fae4175f21a1fab1832abe43e55e4367a8c4dd98e8253966dfb32e

**Comment by jbaker6953** [comment]
I believe the relevant part of the log is here:

```
12-24 17:31:41.053 30011 30210 E WavHeaderReader: Unsupported RIFF format: 1363952461
12-24 17:31:41.058 30011 30208 E ExoPlayerImplInternal: Source error.
12-24 17:31:41.058 30011 30208 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
```

**Comment by jbaker6953** [comment]
Looks like it is a long-standing Exo player issue.

https://github.com/google/ExoPlayer/issues/2092

I don't believe it's feasible to ditch support for MMS from iPhone users.

**Comment by yate** [comment]
This seems like it should be an isolated incident. The RIFF format converted to text is `QLCM` which is this container format https://en.wikipedia.org/wiki/QCP. 

Are you sure you're having problems with all media sent from iPhone users via MMS, or are you having trouble with this one file?

**Comment by jbaker6953** [comment]
This happens any time an iPhone user sends a video message.

**Comment by jbaker6953** [comment]
Is it possible that it's QLCM audio embedded in the video?

**Comment by yate** [comment]
It seems like this a somewhat common problem, if you search https://www.google.com/search?client=firefox-b-1-d&q=qcp+mms. The MMS service is splitting the video/audio into these QCP files. 

Who is your cell provider, and can you upload your APN settings?

**Comment by jbaker6953** [comment]
I just tried to play another one from a different iPhone user: same story.

https://debuglogs.org/7ec0d1c430e46907aa2e4029fa940aae1b31c5145dcc4b5904e09b7df852af7f
```
12-26 17:28:42.033 30011 30011 D AudioView: playbutton onClick
12-26 17:28:42.050 30011 30011 I ExoPlayerImpl: Init b3e9075 [ExoPlayerLib/2.9.1] [marlin, Pixel XL, Google, 25]
12-26 17:28:42.077 30011 24962 V Cursor  : Filling cursor window with start position:0 required position:0
12-26 17:28:42.083 30011 24962 V Cursor  : Filling cursor window with start position:0 required position:0
12-26 17:28:42.185 30011 24962 E WavHeaderReader: Unsupported RIFF format: 1363952461
12-26 17:28:42.198 30011 24961 E ExoPlayerImplInternal: Source error.
12-26 17:28:42.198 30011 24961 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
```

**Comment by jbaker6953** [comment]
I am on Verizon Wireless. APN settings (typed manually because they are read-only):

```
Name: Verizon
APN: VZWINTERNET
Proxy:
Port:
Username:
Password:
Server:
MMSC:
MMS Proxy:
MMS Port:
MCC: 311
MNC: 480
Authentication type: 
APN type: default.dun.supl
APN protocol: IPv4/IPv6
APN roaming protocol: IPv4
APN enable/disable: enabled
Bearer: GPRS, eHRPD, HSUPA, HSPAP, HSPA, HSDPA, LTE, UMTS, EDGE
MVNO type:
MVNO value:
```

**Comment by yate** [comment]
Are you able to create a new APN entry? If so, can you try these settings and see what happens?
```
carrier=Verizon Internet
mcc=310
mnc=012
apn=VZWINTERNET
type=default,dun,mms
mmsc=http://mms.vtext.com/servlets/mms
protocol=IPV4V6
roaming_protocol=IPV4V6
```
Does this happen with the stock messaging app as well?

**Comment by jbaker6953** [comment]
Verizon phones are locked down tight. Cannot add a new APN nor edit the existing. I have to test, but I believe this does not happen with the stock messaging (it's been a few years).

**Comment by ajknows** [comment]
Anything further on this?  VZ does not allow dun APN additions.  Message+ has not problems with MMS messages from iPhones.
