### ISSUE TITLE
Sending video to a chat via the Android Camera App sends it as a downloadable file

### ISSUE THREAD

**Issue by an0n7mous3** [signalapp/Signal-Android#9301]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I add a video to the chat via the 'Plus' sign, or the 'camera' icon in the chat box, the video will send normally. That is, there will be a preview of the video in the chat that anyone can play.

However, if I send a video via the stock Google Camera app (which opens Google Photos to view the library with), it will send that exact same video as a downloadable file, without the preview.

### Steps to reproduce
- Open Google Camera app
- Scroll to library of photos and videos
- Select a video to send
- Click the "Share" icon and select Signal app
- Select a particular chat 
- If prompted to decide "Share as", choose "Actual size"

**Actual result:** 
Video appears as downloadable link with the .mpeg file in the chat, and is not playable in chat.

**Expected result:** The video should display as a preview in the chat and be playable

### Device info
**Device:** Google Pixel 4
**Android version:** 10.0
**Signal version:** 4.52.4

**Comment by an0n7mous3** [comment]
To clarify: On my phone, the video can play normally. But when viewing on desktop, it appears only as a downloadable file.

**Comment by greyson-signal** [comment]
Feel free to open this bug on https://github.com/signalapp/Signal-Desktop/issues.
