### ISSUE TITLE
Execution failed for task ':libsignal-service:test'

### ISSUE THREAD

**Issue by IhsanBhee** [signalapp/Signal-Android#9303]
Hi Mrs/Mr/Sir
in Pleace,

I was build the project Signal for Android and i found error with this condition :

C:\Users\dsi\Documents\D'ProMaster\000\Signal\Signal-Android-master>gradlew.bat build

> Configure project :libsignal-service
Verifying com.fasterxml.jackson.core:jackson-annotations
Verifying com.fasterxml.jackson.core:jackson-core
Verifying com.fasterxml.jackson.core:jackson-databind
Verifying com.google.protobuf:protobuf-javalite
Verifying com.googlecode.libphonenumber:libphonenumber
Verifying com.squareup.okhttp3:okhttp
Verifying com.squareup.okio:okio
Verifying org.signal:signal-metadata-java
Verifying org.threeten:threetenbp
Verifying org.whispersystems:curve25519-java
Verifying org.whispersystems:signal-protocol-java

> Configure project :Signal-Android
The com.google.protobuf plugin was already applied to the project: :Signal-Android and will not be applied again after plugin: android
Verifying androidx.activity:activity
Verifying androidx.annotation:annotation
Verifying androidx.appcompat:appcompat-resources
Verifying androidx.appcompat:appcompat
Verifying androidx.arch.core:core-common
Verifying androidx.arch.core:core-runtime
Verifying androidx.asynclayoutinflater:asynclayoutinflater
Verifying androidx.camera:camera-camera2
Verifying androidx.camera:camera-core
Verifying androidx.cardview:cardview
Verifying androidx.collection:collection
Verifying androidx.concurrent:concurrent-futures
Verifying androidx.constraintlayout:constraintlayout-solver
Verifying androidx.constraintlayout:constraintlayout
Verifying androidx.coordinatorlayout:coordinatorlayout
Verifying androidx.core:core
Verifying androidx.cursoradapter:cursoradapter
Verifying androidx.customview:customview
Verifying androidx.documentfile:documentfile
Verifying androidx.drawerlayout:drawerlayout
Verifying androidx.exifinterface:exifinterface
Verifying androidx.fragment:fragment
Verifying androidx.gridlayout:gridlayout
Verifying androidx.interpolator:interpolator
Verifying androidx.legacy:legacy-preference-v14
Verifying androidx.legacy:legacy-support-core-ui
Verifying androidx.legacy:legacy-support-core-utils
Verifying androidx.legacy:legacy-support-v13
Verifying androidx.legacy:legacy-support-v4
Verifying androidx.lifecycle:lifecycle-common-java8
Verifying androidx.lifecycle:lifecycle-common
Verifying androidx.lifecycle:lifecycle-extensions
Verifying androidx.lifecycle:lifecycle-livedata-core
Verifying androidx.lifecycle:lifecycle-livedata
Verifying androidx.lifecycle:lifecycle-process
Verifying androidx.lifecycle:lifecycle-runtime
Verifying androidx.lifecycle:lifecycle-service
Verifying androidx.lifecycle:lifecycle-viewmodel-savedstate
Verifying androidx.lifecycle:lifecycle-viewmodel
Verifying androidx.loader:loader
Verifying androidx.localbroadcastmanager:localbroadcastmanager
Verifying androidx.media:media
Verifying androidx.multidex:multidex
Verifying androidx.navigation:navigation-common
Verifying androidx.navigation:navigation-fragment
Verifying androidx.navigation:navigation-runtime
Verifying androidx.navigation:navigation-ui
Verifying androidx.preference:preference
Verifying androidx.print:print
Verifying androidx.recyclerview:recyclerview
Verifying androidx.savedstate:savedstate
Verifying androidx.slidingpanelayout:slidingpanelayout
Verifying androidx.swiperefreshlayout:swiperefreshlayout
Verifying androidx.transition:transition
Verifying androidx.vectordrawable:vectordrawable-animated
Verifying androidx.vectordrawable:vectordrawable
Verifying androidx.versionedparcelable:versionedparcelable
Verifying androidx.viewpager:viewpager
Verifying cn.carbswang.android:NumberPickerView
Verifying com.airbnb.android:lottie
Verifying com.amulyakhare:com.amulyakhare.textdrawable
Verifying com.annimon:stream
Verifying com.codewaves.stickyheadergrid:stickyheadergrid
Verifying com.davemorrissey.labs:subsampling-scale-image-view
Verifying com.fasterxml.jackson.core:jackson-annotations
Verifying com.fasterxml.jackson.core:jackson-core
Verifying com.fasterxml.jackson.core:jackson-databind
Verifying com.github.bumptech.glide:annotations
Verifying com.github.bumptech.glide:disklrucache
Verifying com.github.bumptech.glide:gifdecoder
Verifying com.github.bumptech.glide:glide
Verifying com.github.chrisbanes:PhotoView
Verifying com.github.dmytrodanylyk.circular-progress-button:library
Verifying com.google.android.exoplayer:exoplayer-core
Verifying com.google.android.exoplayer:exoplayer-ui
Verifying com.google.android.gms:play-services-auth-api-phone
Verifying com.google.android.gms:play-services-auth-base
Verifying com.google.android.gms:play-services-auth
Verifying com.google.android.gms:play-services-base
Verifying com.google.android.gms:play-services-basement
Verifying com.google.android.gms:play-services-maps
Verifying com.google.android.gms:play-services-stats
Verifying com.google.android.gms:play-services-tasks
Verifying com.google.android.material:material
Verifying com.google.android:flexbox
Verifying com.google.auto.value:auto-value-annotations
Verifying com.google.firebase:firebase-common
Verifying com.google.firebase:firebase-iid-interop
Verifying com.google.firebase:firebase-iid
Verifying com.google.firebase:firebase-messaging
Verifying com.google.guava:listenablefuture
Verifying com.google.protobuf:protobuf-javalite
Verifying com.google.zxing:android-integration
Verifying com.google.zxing:core
Verifying com.googlecode.ez-vcard:ez-vcard
Verifying com.googlecode.libphonenumber:libphonenumber
Verifying com.jpardogo.materialtabstrip:library
Verifying com.klinkerapps:android-smsmms
Verifying com.klinkerapps:logger
Verifying com.makeramen:roundedimageview
Verifying com.melnykov:floatingactionbutton
Verifying com.nineoldandroids:library
Verifying com.pnikosis:materialish-progress
Verifying com.squareup.okhttp3:okhttp
Verifying com.squareup.okio:okio
Verifying com.takisoft.fix:colorpicker
Verifying com.theartofdev.edmodo:android-image-cropper
Verifying com.tomergoldst.android:tooltips
Verifying me.leolin:ShortcutBadger
Verifying mobi.upod:time-duration-picker
Verifying org.apache.httpcomponents:httpclient-android
Verifying org.conscrypt:conscrypt-android
Verifying org.greenrobot:eventbus
Verifying org.jsoup:jsoup
Verifying org.signal:aesgcmprovider
Verifying org.signal:android-database-sqlcipher
Verifying org.signal:ringrtc-android
Verifying org.signal:signal-metadata-java
Verifying org.threeten:threetenbp
Verifying org.whispersystems:curve25519-java
Verifying org.whispersystems:signal-protocol-java
Verifying pl.tajchert:waitingdots
Verifying se.emilsjolander:stickylistheaders

> Task :libsignal-service:test

org.whispersystems.signalservice.internal.registrationpin.PinStretchTest > stretch_pin[2] FAILED
    org.whispersystems.signalservice.internal.registrationpin.InvalidPinException at PinStretchTest.java:111

org.whispersystems.signalservice.internal.registrationpin.PinStretchTest > stretch_pin[6] FAILED
    org.whispersystems.signalservice.internal.registrationpin.InvalidPinException at PinStretchTest.java:111

36 tests completed, 2 failed

> Task :libsignal-service:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libsignal-service:test'.
> There were failing tests. See the report at: file:///C:/Users/dsi/Documents/D'ProMaster/000/Signal/Signal-Android-master/libsignal/service/build/reports/tests/test/index.h
tml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 11s
15 actionable tasks: 7 executed, 8 up-to-date

Can help what must i do for this issue.

Thanks,

Febry

**Comment by Genis-Sage** [comment]
hey @IhsanBhee 

you should look into [building.md](https://github.com/signalapp/Signal-Android/blob/master/BUILDING.md)
it mentions the file about the gradle versions
and the last update was to version 5.6.2

so i think it can be expected that the building does not work with Gradle 6.0


I guess, that you're best option is to go to the [community forum](https://community.signalusers.org/), since your problem is not really a bug

best regards
