### ISSUE TITLE
Crashes when opening Signal or switching conversations (SIGABRT)

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#9304]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For the past few versions Signal has been crashing often when being opened from background, or when switching between conversations.

### Steps to reproduce
- Intermittent. No reliable way to reproduce.

### Device info

**Device:** Google Pixel XL
**Android version:** 7.1.2
**Signal version:** 4.52.4 (5842)

### Link to debug log

https://debuglogs.org/3081febc7efc8829b9d89584be671c1838805dbea4a66093a729ac5624a8e55f

**Comment by jbaker6953** [comment]
Another.
https://debuglogs.org/e9a7bf7febeaf615b95bccfb10126c5987f8e47940fc1fe2f9095fe3d40080b3

**Comment by greyson-signal** [comment]
So strange, I don't see any crashes in the logs :( Maybe the crash logs are happening at a system level, and we don't get them.

If you ever get the time, would you be able to install ADB and get logs from there?
https://developer.android.com/studio/command-line/adb

**Comment by jbaker6953** [comment]
You don't see the lines that read something like:

`12-27 00:30:00.944 30011 30011 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 30011 (crime.securesms)`

In the logs I posted, or in something else? That's pasted from the logs I linked.

**Comment by jbaker6953** [comment]
Searching leads me to believe this is a common crash on Android when the OS thinks the UI is hanging.

**Comment by daivat15** [comment]
Faced the same issue.

Device: Redmi Note 4
Android Version: 9
Signal Version: 4.52.4
Debug Logs: https://debuglogs.org/a5e03dd811ce7d3be5875b9796a110d0102a733a4fe2fbacc09732bee8678ede

**Comment by greyson-signal** [comment]
@jbaker6953 Yeah, I guess I normally look for java stack traces. That's some native crash with no useful logs surrounding it. Unless you experienced 5-10 seconds of UI hang when opening signal, it's unlikely that the OS thinks the app is hanging.

**Comment by jbaker6953** [comment]
Another crash: https://debuglogs.org/d00487b54f227bb805145f2db965e932c07bbde302cb9b079983a5f93f6ec7b1

**Comment by jbaker6953** [comment]
Had another one I didn't capture, and another one today.

https://debuglogs.org/deeb50a119fbb9b416ae5d1cfb25bac57a41688ae9c21a837fc4bc9bb34ee225

Today's happened when I tapped a picture I had sent earlier in a conversation.

**Comment by jbaker6953** [comment]
Another one switching conversations.

https://debuglogs.org/e0154e8754814e4d60b243166a4d6741ef0f0e6d8aefd853a51071008c5c6611

**Comment by jbaker6953** [comment]
Crashed while screen was off and phone was sitting on the desk.

https://debuglogs.org/12f1a2759530cc661580c0fc01276bd4be4a5447c505f7ee6500401188b54b1d

**Comment by jbaker6953** [comment]
Crashed turning on screen and Signal had focus:
https://debuglogs.org/5f10d12cdceef56d9a8e816e3cb7cec3c45c018e0cad8f59cca9b451857912db

I think I'll stop posting these unless someone thinks more will be useful. I think it establishes that Signal crashes on a regular basis for some reason.

**Comment by jbaker6953** [comment]
Still happening with 4.53.7

**Comment by sivaraam** [comment]
I'm observing this often these days. I use a Samsung SM-J111F with Android 5.1.1 running Signal v5.3.9. I reported many of these crashes via the built-in Android crash reporting dialog. Let me know if any information would be helpful for debugging this issue.
