### ISSUE TITLE
No notification badge icon or LED blink on incoming messages

### ISSUE THREAD

**Issue by whaco1** [signalapp/Signal-Android#9309]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Incoming signal messages (single message from single user or multiple messages from different users) do not cause the notification badge icon to show up on the start screen nor the LED to light up when the screen is off (on standby). I only see the unread messages marked when I enter the app, which is annoying. Sometimes when I am in the app I do receive messages instantly but not when I am not using the app.
App message priority is set to "urgent/critical". I have not changed anything in the settings and I wonder if this has anything to with closed #7580, which I also experienced back then.

### Steps to reproduce
- Wait for messages to arrive on my phone and then bug occurs

**Actual result:** 
I wake up my phone from standby - no LED is blinking nor notification badge icon is showing on signal app - assume no new messages are there - I enter signal app and realize there are one or more unread messages.
My memory is that this bug was not there until 2-3 months or so.

**Expected result:** 
I expect the LED to light up and keep blinking once a new message has arrived. I expect the notification badge icon to display and show the number of unread messages in the app.

### Device info
Device: Samsung Galaxy S7
Android version: 8.0.0
Signal version: 4.52.4

**Comment by Kevinmartin007** [comment]
Have you checked your notification settings within the phone itself (not in signal)

**Comment by whaco1** [comment]
I have. For Signal everything is set to receive and notifications to be displayed. Only sound is muted but was also before the bug.

**Comment by IanSpam** [comment]
I started getting similar issue with 4.53.7. Just noticed when I am using the PC Signal. My phone notifies me quite fast. Otherwise no notifications arrive until I open app on phone. Seems odd, hope it helps...

**Comment by Safari77** [comment]
I had to select Android setting `Override Do not disturb` to get Signal to show notifications in lock screen and when unlocked, WHEN `Do not disturb` is active.
I also changed Sound to `Silent` and disabled vibration in Signal to make it less annoying.

**Comment by whaco1** [comment]
Any developments on this?
I don't use the "Do not disturb"-mode. Has anything changed in the notification code section? As stated above, there were some issues a while back but ultimately had been fixed. It is sad, as it used to be my go-to app but now is really starting to annoy me.

**Comment by lutoma** [comment]
@whaco1 Do you have "Mobile data saver" enabled? This sounds somewhat similar to #9438

**Comment by whaco1** [comment]
hi there, 
no - no mobile data saver enabled...

**Comment by greyson-signal** [comment]
I'm centralizing all notification timeliness issues at #8692.
