### ISSUE TITLE
4.52.4 unusable on Android 10 after fresh install, immediate crash on start

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#9311]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes immediately on start after post-install setup (permissions checks etc). I have reinstalled the app twice, cleared my storage/cache and rebooted the phone twice. 

### Steps to reproduce
- install app
- go through permissions checks (yes to all) and SMS code check
- get directed to message list screen

or

- after installing app
- open app
- get directed to message list screen

**Actual result:** App crashes every time
**Expected result:** App does not crash 

### Device info

**Device:** Pixel 3a XL
**Android version:** 10 baseband g670-00030-etc
**Signal version:** 4.52.4

### Link to debug log

Edit: the app is now working so I captured the debug log. No idea what I did to fix it. 

https://debuglogs.org/afa5c915379a36dae3891a76901f024c2f04500b5850eab7d832024624355da2

**Comment by greyson-signal** [comment]
Looks like the issue was:

```java
12-31 12:54:38.352 15212 15275 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
12-31 12:54:38.352 15212 15275 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 15212
12-31 12:54:38.352 15212 15275 E AndroidRuntime: java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.SecurityException: uid 10306 cannot explicitly add accounts of type: org.thoughtcrime.securesms
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.refreshDirectory(DirectoryHelperV1.java:109)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.refreshDirectory(DirectoryHelperV1.java:73)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:24)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:70)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: uid 10306 cannot explicitly add accounts of type: org.thoughtcrime.securesms
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.refreshDirectory(DirectoryHelperV1.java:99)
12-31 12:54:38.352 15212 15275 E AndroidRuntime: 	... 6 more
```

Unclear why this would happen at all. Was there a system update or something? That code hasn't changed in forever. Seems to imply that we were unable to create an account in the system.

**Comment by jcollum** [comment]
It doesn't look like this was fixed so why was it closed?

**Comment by greyson-signal** [comment]
You said the crash went away, and the original crash looks like it was a system bug that was out of our control.

**Comment by jcollum** [comment]
But I reinstalled the app because it was constantly crashing.

**Comment by greyson-signal** [comment]
But it wasn't the reinstall that fixed it, or the crash wouldn't be in your debuglogs. Something you did outside of signal fixed it, and I'm assuming that it had to do with some system bug that might have been patched for all I know. I can see in the Play Console crash reports that this isn't something that's widespread. So I'm writing this off as a system bug that is out of our control.
