### ISSUE TITLE
Input field and send button half covered by Android buttons after picture is taken

### ISSUE THREAD

**Issue by igor2x** [signalapp/Signal-Android#9312]
### Bug description
After taking a photo input text field and send button are half displayed, so text can't be inserted under the picture and send button very hard to use.

### Steps to reproduce
- Tap on what ever conversation (e.g. Note to Self)
- On the bottom right tap on photo icon.
- Take a photo.
- Photo is taken and small picture preview displayed in bottom left. Now problem appears.

**Actual result:**
The bottom input field and send button is half displayed. It is covered by Android buttons. It is impossible to type text to be displayed when picture is sent and send button is very hard to press.

**Expected result:**
Text input field and send buttons fully displayed and not covered by Android buttons.

### Screenshots
![pic](https://user-images.githubusercontent.com/10895030/71643154-e15ea380-2cb5-11ea-9617-9c0895289cf7.jpg)

### Device info
**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** 4.52.4

### Link to debug log
https://debuglogs.org/21ad53545b209f3f6a7df0e9ec3d12540b05279ec9265a6374cd1778605d3465

**Comment by igor2x** [comment]
Additional info... I can even reproduce the crash.

1. Do the same steps as in bug report. Tap on three vertical lines Android icon.
![1](https://user-images.githubusercontent.com/10895030/71713621-c5204b00-2e0a-11ea-8284-5dfdfe375de4.jpg)
 2. Tap on Signal icon on top of window.
![2](https://user-images.githubusercontent.com/10895030/71713644-dbc6a200-2e0a-11ea-8f4c-467510c8b932.jpg)
3. Select 'Open in pop-up view'.
![3](https://user-images.githubusercontent.com/10895030/71713658-ed0fae80-2e0a-11ea-89d6-403c7d153566.jpg)
4. On top of displayed window tap on second icon from the right to expand window to full screen.
![4](https://user-images.githubusercontent.com/10895030/71713688-116b8b00-2e0b-11ea-9a93-7055c0c62bb5.jpg)
5. In the bottom type some text into text input field e.g. "Test". Right of the text input field Signal send button is in white color, taping on it and nothing happens.
![5](https://user-images.githubusercontent.com/10895030/71713727-3a8c1b80-2e0b-11ea-8834-f3b19492331e.jpg)
 6. (from previous image) Tap on pencil button and crash appears. Debug log after the crash: https://debuglogs.org/57434df8bc6a8ea421467c18e888dca4872e57cfab0b9472c65113b0d6de6cf6

**Comment by igor2x** [comment]
I have solved the problem in first post. It is actually Android setting.
1. Tap on three vertical lines icon (bottom left).
2. Tap on _Change app aspect ration_ toggle selection.
![android_1](https://user-images.githubusercontent.com/10895030/72087653-1fd50d80-3309-11ea-9cb8-13b84d6d141a.jpg)
and problem is solved. I can clearly see the image in Signal 4.53.3:
![android_2](https://user-images.githubusercontent.com/10895030/72087747-47c47100-3309-11ea-9d32-81222b9ae1c2.jpg)

Perfect, problem solved. I fixed the problem, because I am currious and not afraid to set some setting. I am afraid less tech people would probably never figure this out.

It would be excellent if there is something Signal developers can do about this problem for less tech people.

By the way, problem in second post still persist including Signal crash.

**Comment by greyson-signal** [comment]
Ah yep, figured it was some system setting, because I couldn't repro it with the notch simulator in the android dev settings. Not much we can do. Too many weird phone-specific problems.

You can open another bug for the other crash, which is a separate issue.
