### ISSUE TITLE
When Signal app is killed, incoming call screen is not coming to foreground

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#9314]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]  This isn't a feature request or a discussion topic

### Bug description
I have Xiaomi phone and when Signal app is killed, incoming call screen is not coming to foreground.

### Steps to reproduce
- I'm killing app from recent apps.
- Another phone is calling Xiaomi.
- Mi couldn't show call screen.

**Actual result:** I can't show call screen and when app is killed.
**Expected result:** I can show call screen.

### Device info
**Device:** Xiaomi 8
**Android version:** 9.0
**Signal version:** 4.49.18

**Comment by Genis-Sage** [comment]
hey @gelbertgel 

do you get messages, when you remove Signal from last used apps?

did you try out any troubleshooting from the [support articles](https://support.signal.org/hc/en-us/categories/360000674831-Troubleshooting)?

For example, deactivating battery optimization?


Also it would be good, if you can post a debug log

best regards

**Comment by gelbertgel** [comment]
Mi has shown call notification but not shown call screen when app is killed or background. I get messages and incoming calls but not show call screen.

**Comment by gelbertgel** [comment]
do you get messages, when you remove Signal from last used apps?
-Yeap I get messages and incoming calls but not show call screen

Mi has shown call notification but not shown call screen when app is killed or background. I get messages and incoming calls but not show call screen.

**Comment by Aquaplast** [comment]
same problem, samsung phone

**Comment by greyson-signal** [comment]
> -When I click "show lock screen and work on background" at Mi preferences, this problem is solving.

Yep, sounds like a battery optimization issue. Glad you were able to fix it!

**Comment by simonsso** [comment]
I would like to reopen this issue:

> > -When I click "show lock screen and work on background" at Mi preferences, this problem is solving.
> 
> Yep, sounds like a battery optimization issue. Glad you were able to fix it!


When permissions for draw on lock-screen and open popup in background are denied, the app rings but is not able to answer, not even if the app UI is activated. A real fix would be for the app to detect the denied permissions alert the user when back in the app.

Here is a logcat when denied:

https://gist.github.com/simonsso/9e03f3526223b037f64ee52a05eaa3cd
