### ISSUE TITLE
I figured out the problem and was able to install signal-desktop successfully. It turned out that my system was in a weird state after upgrading from Debian `jessie` to `stretch`. So nothing was or is wrong with signal-desktop and I'm sorry for the noise.

### ISSUE THREAD

**Issue by ukron-ai** [signalapp/Signal-Android#9315]
I figured out the problem and was able to install signal-desktop successfully. It turned out that my system was in a weird state after upgrading from Debian `jessie` to `stretch`. So nothing was or is wrong with signal-desktop and I'm sorry for the noise.

In case someone runs into a similar problem, here's what had happened and how I fixed it:

Similar to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834724#15 I had an old package `libgnutls-deb0-28` installed, which seemed to cause the above error. However, when I tried to remove it, it would have also removed half of all my packages, many of which seemed totally unrelated (similar to what was reported here: https://superuser.com/questions/1334780/git-clone-and-apt-error-gnutls-handshake-failed).

According to https://packages.debian.org/search?searchon=names&keywords=libgnutls-deb0-28 that package shouldn't even exist in `stretch`, but it turned out that I had `librtmp1` version `2.4~20160119.gitfa8646dae-dmo3~bpo8+2` installed, which depended on `libgnutls-deb0-28`. That particular version of `librtmp1` was left over from deb-multimedia (http://www.deb-multimedia.org/dists/oldstable-backports/main/binary-mips/package/librtmp1.php) which I had used while still on `jessie`. Because that version of `librtmp1` was **newer** than the one in the official Debian repos for `stretch`, (version `2.4+20151223.gitfa8646d.1-1` according to https://packages.debian.org/stretch/librtmp1), it wasn't upgraded with `apt-get upgrade` or `apt-get dist-upgrade`.

So the solution was to **downgrade** `librtmp1` to the version number from the official Debian repos:

```
apt-get install librtmp1=2.4+20151223.gitfa8646d.1-1+b1
```

After that I could remove `libgnutls-deb0-28` without too many things removed together with it, like this:

```
apt-get remove libgnutls-deb0-28
```

With `libgnutls-deb0-28` gone, the installation instructions for signal-desktop went through without problems.

_Originally posted by @dietmar in https://github.com/signalapp/Signal-Desktop/issues/2483#issuecomment-401047201_

**Comment by Genis-Sage** [comment]
hey  @ukron-ai 

what's the background of you opening or copying this here?
Github should be kept for bug reports

Especially this is nothign related to Signal Android

if you need any help with this, you should go to the [community forum](https://community.signalusers.org/)

**Comment by Anoos97** [comment]
- [ ]
