### ISSUE TITLE
Option to hide stickers button to give more horizontal typing space

### ISSUE THREAD

**Issue by Cheap-Skate** [signalapp/Signal-Android#9316]
I'll never use stickers. The stickers button hangs around when I'm typing and uses valuable horizontal screen real estate. 

So my messages
end up being typed
in a small horizontal
space. Like this

Could there be an option to not have stickers, or hide the button when typing, so I get the screen real estate back

Thanks

**Comment by Genis-Sage** [comment]
hey @Cheap-Skate 
thanks for you thoughts, but Github is reserved for bugs

for feature discussion, please go to the [community forum](https://community.signalusers.org/)
