### ISSUE TITLE
Mexican contacts registered prior to phone number change only show up as non-signal contacts

### ISSUE THREAD

**Issue by lem503** [signalapp/Signal-Android#9317]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Mexico has recently [changed their phone numbers](https://www.mexperience.com/mexico-simplifies-telephone-dialing-rules/) by removing a trailing 1 after the country code. When re-installing signal, Mexican contacts that were registered prior to the number change (with 1 in their number) can no longer be added to signal and can't be found in contacts on signal.

A possible reason might be that google seems to modify existing numbers internally to reflect the removal of the 1, e.g. if you try to call an old Mexican number google will dial the new number without the 1 instead.

For existing conversations this causes strange in-between states where my Mexican contact has an existing and active signal conversation with me and can send messages on their end, but these appear as bad encrypted messages on my end where the conversation is treated as non-signal (only possible to send SMS messages and get the prompt to invite contact to signal). After reinstalling signal, my contact even received a notification for a change in my security number. Resetting secure connection on their end has no effect (the option is not visible on my end).
 
### Steps to reproduce
- Have an existing signal conversation with a Mexican contact
- Edit number of Mexican contact in contacts app (remove 1)
- Reinstall signal (restoring messages from backup does not affect bug)
- Mexican contact cannot be found in signal (this is perhaps expected)
- Add old contact number (with 1) or undo change from step 2
- Refresh contacts in signal

**Actual result:** Mexican contact cannot be found (only displayed as non-signal contact without 1 in their number).
**Expected result:** Mexican contact should be found

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** 4.52.4 (5842) 

### Link to debug log

https://debuglogs.org/f5152230ab6bec96d29e2c28580b0a2ba1b922ac367db695da0732a3fd0d1bd3

**Comment by Genis-Sage** [comment]
hey @lem503 
right now, Signal conversations are always linked to the phone number
so when you change the number of a contact with his new number, a new conversation will popup

so i guess, you will have two conversations at the end, one with the leading 1, and one without it

also i don't get the point of you mentioning google
does Google change your phone book entries automatically, or only when calling people (which has nothing to do with signal)

and even if you use a backup, you have to register for SIgnal again

so the question is, what number does your friend use to register to Signal

**Comment by lem503** [comment]
Hi the issue is that I cannot start a new conversation. The contact still is registered with the 1. Even when I add this number to my contacts Signal does not see it, so I cannot start a new Signal conversation with them. I thought that this might be related to #8639 but I do not have any issues with any other contacts.

I mention google because I noticed that when I go to contacts.google.com the old and new number get combined as shown in the pictures below. Perhaps this is not relevant but I thought I should mention this as it is strange that 2 different numbers are combined.

1st picture is the separate numbers as I add them to the contact.
![Separate Numbers](https://user-images.githubusercontent.com/10457248/71769788-4831c600-2f1d-11ea-9618-a19d7541a570.jpg)

2nd picture is how google displays them, as if they were identical.
![Combined](https://user-images.githubusercontent.com/10457248/71769787-4831c600-2f1d-11ea-9f09-5dae03ad6c9f.jpg)

3rd picture shows the view in Signal. Notice number is `main old (1)` but is displayed without 1.
![Signal_view](https://user-images.githubusercontent.com/10457248/71770203-e45dcc00-2f21-11ea-8c1b-33d49b9f83e2.jpeg)

As a test I have added a new contact with a random (old) Mexican number, perhaps you can try this too. Format is: +52 1 55 XXXXXXXX (8 random digits).
When I add such a number to my contacts and start a conversation with the contact on Signal the 1 is missing.

**Comment by Genis-Sage** [comment]
just a guess for the reason
Starting with 4.51.0, Signal uses [lib phone number 8.11.0](https://github.com/signalapp/Signal-Android/commit/2ada7f87f28cc797a8602dbc6e704b91b29fc4a6)

i looked up the commits for [com.googlecode.libphonenumber](https://github.com/google/libphonenumber/commits/master)
and found this commit:
[Abolish MX's international mobile token (1)](https://github.com/google/libphonenumber/commit/3ac88c7106e7dcb553bcc794b15f19185928a1c6)

so i guess, your friend should try to register his number without the 1, and it should work

**Comment by greyson-signal** [comment]
@lem503 I'm working on fixing our handling of Mexican phone numbers. If you're interested, I'd like to send you a build with our potential fix, and you can let me know if things are working better. To do so, reach out to my test number: +1 610 708 0800
