### ISSUE TITLE
Forwarding an SMS to a Signal Recipient sends as insecure SMS 

### ISSUE THREAD

**Issue by gfs** [signalapp/Signal-Android#9319]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When you forward a message originally sent in an SMS conversation to a contact that uses signal it changes the default conversation security for that conversation from Secure to Insecure.

### Steps to reproduce
- Send an SMS message to a contact
- Select the message and press the Forward action
- Select a contact that can receive Secure messages 

**Actual result:** Message is prepped to be sent as SMS.
**Expected result:** Message is prepped to be send as Signal message whenever possible (or at least the previous setting in that conversation).

### Device info

**Signal version:** 4.52.4

**Comment by Tursko** [comment]
This does not happen to me on version 4.52.4. When forwarding an SMS message to a Signal user it defaults to Signal IM.

**Comment by gfs** [comment]
I’m having trouble reproducing it now but it was reliable yesterday.
