### ISSUE TITLE
NullPointerException: Unable to start SharedContactDetailsActivity

### ISSUE THREAD

**Issue by anlalalu** [signalapp/Signal-Android#9320]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

###### Reproduction Steps
This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am start -n org.thoughtcrime.securesms/org.thoughtcrime.securesms.contactshare.SharedContactDetailsActivity

###### Stack Trace

E/AndroidRuntime(24831): FATAL EXCEPTION: main
E/AndroidRuntime(24831): Process: org.thoughtcrime.securesms, PID: 24831
E/AndroidRuntime(24831): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.contactshare.SharedContactDetailsActivity}: java.lang.IllegalStateException: You must supply a contact to this activity. Please use the #getIntent() method.
E/AndroidRuntime(24831): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime(24831): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime(24831): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime(24831): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime(24831): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24831): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(24831): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(24831): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24831): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(24831): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(24831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(24831): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(24831): Caused by: java.lang.IllegalStateException: You must supply a contact to this activity. Please use the #getIntent() method.
E/AndroidRuntime(24831): 	at org.thoughtcrime.securesms.contactshare.SharedContactDetailsActivity.onCreate(SharedContactDetailsActivity.java:91)
E/AndroidRuntime(24831): 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:51)
E/AndroidRuntime(24831): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(24831): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(24831): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime(24831): 	... 11 more

###### Debug info

Android Version = 7.1.0

**Comment by greyson-signal** [comment]
The crash your experiencing has helpful text in the exception itself:

```java
 java.lang.IllegalStateException: You must supply a contact to this activity. Please use the #getIntent() method.
```

This activity expects arguments in the intent, and you are not passing any.
