### ISSUE TITLE
Exclude .dng files from image rail

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#9321]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
raw files (.dng) also show up in the quick send rail and in my opinion should not signal doesn't support raw files and shows a low resolution image instead

### Steps to reproduce
- send image from quick image rail

**Actual result:** 
dng files appear as well next to jpg files

**Expected result:**
only non-raw images should appear

### Device info

**Device:** Pixel 2XL
**Android version:** 10.0
**Signal version:** 4.52.4

**Comment by greyson-signal** [comment]
That rail is rendered by asking the system "what photos have been added recently system-wide?". What's the experience with sending raw files? Are they attached as images (i.e. when you tap them do you go to the full-screen image editor), or as files?

**Comment by piratenpanda** [comment]
It's loading the full-screen image editor. The resolution is extremely low though, most likely the embedded preview jpeg or something similar.

**Comment by piratenpanda** [comment]
This still happens with 5.4.12 and is still annoying. Maybe a dng or raw indicator would help to differentiate the pictures

**Comment by piratenpanda** [comment]
Can we please reopen this? It just does not make sense to show dngs
