### ISSUE TITLE
Overlapping toolbar with statusbar on devices with a notch

### ISSUE THREAD

**Issue by jo8558** [signalapp/Signal-Android#9323]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a device that contains a notch like the Pixel 3 XL, in the recipient view, the notch and the transparent statusbar causes that some elements are overlapped

### Steps to reproduce
- Pick a phone with a notch
- Select any chat
- Click on the name in the toolbar

**Actual result:** The back button is partly hidden behind the statusbar
**Expected result:** The back button is not hidden

### Screenshots

![signal-attachment-2020-01-07-101605](https://user-images.githubusercontent.com/16705542/71884200-22343d80-3138-11ea-94e5-ffa4044e3d45.png)
![signal-attachment-2020-01-07-101611](https://user-images.githubusercontent.com/16705542/71884201-22343d80-3138-11ea-9780-0fc009a68651.png)

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 10
**Signal version:** 4.52.4

**Comment by igor2x** [comment]
I have tested this problem with my phone Samsung Galaxy S10, but overlapping does not appear.

But there is similar problem in #9312, I have reported few days ago, also **overlapping** problem but in that case the bottom of the phone. Can you please test that problem if it appears with your phone and if it does, please take debug log and type other info in that bug report. Thanks.
