### ISSUE TITLE
Right-swipe quoting while searching results in invisible text box

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#9325]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If you swipe right to quote while searching, you end up with an invisible text input box.

### Steps to reproduce

- Pick a chat
- Search for something within the chat
- Swipe right on a message
- Start typing a reply to said message
- Click back a few times to get back to the input field

### Device info
**Device:** Nokia 7.2
**Android version:** 9
**Signal version:** 3.53.1

**Comment by igor2x** [comment]
Is it really Signal version **3.** 53.1? Or is it 4.53.1 beta?

If it is beta, did this problem appear only in latest beta or you have noticed this problem before?

Can you please reproduce a problem and take a debug log (humburger menu at top right | Settings | Advanced | Submit debug log) and post the URL to debug log. Without debug log developers usually have no clue what is going on.
