### ISSUE TITLE
restoring backup

### ISSUE THREAD

**Issue by omnislash79** [signalapp/Signal-Android#9327]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Restore backup does not work

### Steps to reproduce
Fresh signal install 
Follow steps
Enter 30 digit backup code
Gives error 

**Actual result:** Describe here what happens after you 
Screen stays at restore/skip backup

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour

It should go to phone number verification

### Device info

**Device:** Oneplus 6t
**Android version:** 10 *oxygenOS 10.3.0
**Signal version:** 4.52.4 

### Link to debug log
https://debuglogs.org/96ab135f067b857be3eff3c4a78d0641d5adbd0542b972f5cf42a1355786c699

**Comment by Sgn-32** [comment]
Seems to try to restore from a backup of a never version of signal than now installed.

`01-08 18:04:37.837 15446 15503 W RestoreBackupFragment: org.thoughtcrime.securesms.backup.FullBackupImporter$DatabaseDowngradeException: Tried to import a backup with version 40 into a database with version 39`

In the debuglog:
**App          : Signal 4.51.6 (5792)**

Try to restore the backup with signal version 4.52.4

**Comment by omnislash79** [comment]
> Seems to try to restore from a backup of a never version of signal than now installed.
> 
> `01-08 18:04:37.837 15446 15503 W RestoreBackupFragment: org.thoughtcrime.securesms.backup.FullBackupImporter$DatabaseDowngradeException: Tried to import a backup with version 40 into a database with version 39`
> 
> In the debuglog:
> **App : Signal 4.51.6 (5792)**
> 
> Try to restore the backup with signal version 4.52.4

Same result

**Comment by johanw666** [comment]
Database version 40 is for Signal 4.53, see SQLCipherOpenHelper.java:
````
private static final int RESUMABLE_DOWNLOADS = 40;
```

**Comment by omnislash79** [comment]
> Database version 40 is for Signal 4.53, see SQLCipherOpenHelper.java:
> 
> ```java
> private static final int RESUMABLE_DOWNLOADS = 40;
> ```

So am i SOL? The latest version is 4.52.4

**Comment by u32i64** [comment]
@omnislash79 You can restore this backup on the same or newer version of Signal. You have created this backup with Signal 4.53. Install that version just like you got it on the device which created the backup (Signal 4.53 is currently beta).

**Comment by omnislash79** [comment]
> @omnislash79 You can restore this backup on the same or newer version of Signal. You have created this backup with Signal 4.53. Install that version just like you did on the device which created the backup (Signal 4.53 is currently beta).

Fresh install  
 backup restore.  
Click on the mms arrow 
And  i get this error 

![Screenshot_20200109-152716__01](https://user-images.githubusercontent.com/29907986/72067770-a29f9d80-32f4-11ea-862b-7e2e67a9e4c9.jpg)

![Screenshot_20200109-152443](https://user-images.githubusercontent.com/29907986/72067673-62d8b600-32f4-11ea-87f2-b22e1ec13180.jpg)


https://debuglogs.org/115d3626d8f925e61383b73ca729163581fb40794140d7bca5a718e97f005f53

**Comment by johanw666** [comment]
> So am i SOL? The latest version is 4.52.4

No, 4.53.3 is the latest beta version.

**Comment by Sgn-32** [comment]
Signal hasn\`t the permission for MMS.

`android.permission.RECEIVE_MMS: NO`
`...`
`2020-01-09 15:22:27.196 GMT+03:00 E UncaughtExceptionLogger: java.lang.SecurityException: Download MMS message: uid 10311 does not have android.permission.RECEIVE_MMS.`

**Comment by omnislash79** [comment]
> Signal hasn`t the permission for MMS.
> 
> `android.permission.RECEIVE_MMS: NO`
> `...`
> `2020-01-09 15:22:27.196 GMT+03:00 E UncaughtExceptionLogger: java.lang.SecurityException: Download MMS message: uid 10311 does not have android.permission.RECEIVE_MMS.`

How do i fix this? On the permission its all allowed. 

![Screenshot_20200110-074310](https://user-images.githubusercontent.com/29907986/72126392-fe156e00-337c-11ea-8d49-05247382f2ee.jpg)

**Comment by omnislash79** [comment]
Sorry this have digress from the main issue
