### ISSUE TITLE
SMS doesn't Send, Image Message Sends, No Problem Receiving.

### ISSUE THREAD

**Issue by SteveScott** [signalapp/Signal-Android#9328]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send an text, it hangs indefinately. However, when I attach an image, the text sends immediately. I am having no trouble receiving messages. I am in Lower Manhattan using TMobile.

### Steps to reproduce
-send an sms
-wait several hours.
-send image message

**Actual result:** 

sms message does not send.
image message sends immediately.

**Expected result:** 
both text and image messages should send immediately.

### Device info

**Device:** Pixel 3A
**Android version:** 10
**Signal version:** 4.52.4

### Link to debug log

https://debuglogs.org/4c3fd1f40e75b90c6753754e98002e4c9e2a163b60fe9ec75603abc84a51699f

**Comment by Tursko** [comment]
Can you confirm that the person your messaging doesn't receive the text? I've had an issue for a while now where the SMS will show that its pending, but in reality it was sent successfully.

**Comment by saratheneale** [comment]
Something similar started happening on my Pixel 2 today.
 I cannot send SMS. I can send Signal messages to other Signal contacts. I can receive SMS. I cannot send MMS either after trying to send to a Signal contact. 

I had to change my default SMS app to the stock Messages in order to send SMS once more. 

Pixel 2
Android 10
Signal version: 4.55.8

**Comment by SteveScott** [comment]
My problem was the network. After I left lower Manhattan messaging worked
again.

**Comment by saratheneale** [comment]
It resolved itself this morning! I tested Signal as my deafult SMS app and insecure + secure messages, and things work as expected again. It doesn't make sense to me why switching to Messages as my default SMS app was the workaround, but so be it! 

In case its helpful, my network is T-mobile.

**Comment by DavidWellsTheDeveloper** [comment]
It sounds like this was resolved, and this issue is no longer relevant. If this is the case, can someone close this issue please?

**Comment by Tursko** [comment]
I also haven't encountered the issue in a long time.
