### ISSUE TITLE
Signal crashes upon sending or receiving any message

### ISSUE THREAD

**Issue by 2011** [signalapp/Signal-Android#9330]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

It appears that this is a slightly different issue than the one described in #9271, so I am opening a new issue.

Signal crashes upon any communication with another user. It will sit there doing nothing, but as soon as I either send (or receive) a message, it will crash four or five times.

I have edited the debug log (removing everything from a month ago) to only show events from a ten minute period (which includes about ten crashes). I will send that file to support@signal.org with this issue number in the name of the attachment.

I sent the file issue_9330_debug.log.xz to support@signal.org (I guess I should have specified Signal-Android). Can you take a look at it @greyson-signal ?

**Comment by alan-signal** [comment]
What version are you running?

**Comment by alan-signal** [comment]
OK, I have your logs now.

I see you are seeing this issue on a Genymotion API 19 emulator. We can't really offer support for that, do you see it on other API19 devices or any other device?

**Comment by 2011** [comment]
Forked version of which code? Not Signal - I have downloaded it from the Play Store (and I started using it when it was still known as TextSecure). I have never had a crash ever until the upgrade from 4.50.6 to 4.51.6.

**Comment by alan-signal** [comment]
That was a guess because people using emulator services are usually doing development.

Can you tell me more about your usecase, why and how you use an emulator. alan@signal.org if you  rather.

**Comment by 2011** [comment]
The biggest reason is simply that I prefer to type with a keyboard rather than with my fingers (I often send relatively long messages). I am not much of a "device" person to begin with (I remain suspicious of the overall securtiy on mobile devices relative to desktops), and the emulator runs continuously (and always has a gigabit connection :) ), so I never miss anything. I actually run very little else on the emulator (maybe another messaging app with a virtual number to receive SMS messages for people I have yet to convince to use Signal and a card game).

**Comment by 2011** [comment]
@alan-signal do you have any information about the cause of these crashes? It seems a lot of people have started having crashes with the most recent releases.
