### ISSUE TITLE
cannot zoom into one time media pictures

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#9333]
Pixel 3 

Android 10 (6031801, QQ1A.200105.002)

Signal 4.53.4 (5892)

https://debuglogs.org/cce60fc504bcd3c00bcf1a143e9abe2295dbf3ce2bf9f1d609140c0e8a419d36

**Comment by alan-signal** [comment]
Please use the community forum for feature requests and Beta feature feedback https://community.signalusers.org/

**Comment by Meteor0id** [comment]
Topic created for this here:
https://community.signalusers.org/t/pinch-zoom-on-view-once-images/11150
