### ISSUE TITLE
Deactivate vibration in group chat does not take effect

### ISSUE THREAD

**Issue by androideo** [signalapp/Signal-Android#9337]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I still receive vibrating notification, altough I have deactivated the vibration for a group conversation. 

### Steps to reproduce
- Open a group chat
- Click on detailed settings
- Open Group chat settings
- Activate custom notification sound
- Choose Vibration: "Deactivated"

**Actual result:** My notifcations for the group are still vibrating
**Expected result:** When a notification arrives for this group chat, no vibration should be executed

### Screenshots
No visible error

### Device info

**Device:** Motorola G4 Plus
**Android version:** 8.1.0
**Signal version:** 4.42.0

### Link to debug log
Bug happen around 10 Minutes bevor Debug Log was created
https://debuglogs.org/5099c552ef76fe9113dc20ddab3864dcdf08a90b346914734c941849961c57c7

**Comment by greyson-signal** [comment]
I believe this will be resolved in 4.53.x, which is currently in beta. Feel free to reopen if it isn't fixed in that version.
