### ISSUE TITLE
Should not ask storage permission to disable chat backups

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9338]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Descriptions
Permissions should never be required to disable anything. Only check and ask permission when enabling.

### Steps to reproduce
- enable backups
- withdraw storage permission from Signal using Android permission management
- attempt to disable chat backups

### Device info

**Android version:** 9.0
**Signal version:** 4.53.5

**Comment by johanw666** [comment]
Any existing backups are automatically removed if you disable backups,, so Signal does need that permission.

**Comment by alan-signal** [comment]
That's correct, thanks Johan.
