### ISSUE TITLE
No signal notifications when connected to wifi. Huawei Mate 20 pro

### ISSUE THREAD

**Issue by bitwit42** [signalapp/Signal-Android#9339]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ]x This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As others i have problems with reciving notifications from Signal on android.
After a lot of testing I have found that notifications work when using a mobile data connection, but not when connected to wifi.
I have thouroughly checked my wifi setup and i have found nothing that could cause such a problem. I have observed the same problem when on other wifi networks.

I have gone through all settings in the support page for notification troubleshooting signal on android 

The recommended settings are applied.

The problem occurred several updates back. Dont know the last signal version that worked.
 

### Steps to reproduce
- Connect phone to wifi network
- send a signal message from another device.
- No notification. Start the signal appp and the notification and message is received

- Turn of wifi in the phone, leaving mobile data connection on.
- close signal app
- send a signal message from another device
- Notification is received.
- Open signal and read message.

**Actual result:** 
No notifications when phone is connected to wifi.

**Expected result:** 
I would expect notifications to be received  when connected to wifi

### Device info

**Device:** Huawei mate 20 pro
**Android version:** 10
**Signal version:** 4.53.5

**Comment by bitwit42** [comment]
Additionl findings. Running on mobile data does not always result in receiving notifications.
But when connected to wifi and turning of wifi and thus switching to mobile data always trigger a notification if there is one waiting.

**Comment by Sgn-32** [comment]
please send a debug log so that any problems can be identified.

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by bitwit42** [comment]
Installed the latest beta from google play today and the problem seem to be solved. I have made no changes to the phones config so the update seems to have solved the issue.
Great!
