### ISSUE TITLE
Crash on Review Storage.

### ISSUE THREAD

**Issue by FaizKhan5** [signalapp/Signal-Android#9340]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Bug description
Signal crashes on 'Review Storage' option.

Steps to reproduce
- When i touch 'Review Storage' option in Storage settings, Signal crashes.

Actual result: Signal crashes on 'Review Storage' option.
Expected result: Signal show details when i touch 'Review Storage' option.

Device info
Device: Huawei Mate 10lite
Android version: 8.0.0
Signal version: 4.53.6

Link to debug log
https://debuglogs.org/9f7454ebcd8f5c0c562b817a1ec8e38ce2f87649f0c9d8d4dc413cf7d7669d78

**Comment by johanw666** [comment]
```
android.permission.READ_EXTERNAL_STORAGE: NO
```
Should this work with storage at all?

**Comment by FaizKhan5** [comment]
The problem is fixed now.
