### ISSUE TITLE
Upper- and lowercase accentuated characters are considered different when searching for a contact

### ISSUE THREAD

**Issue by breversa** [signalapp/Signal-Android#9341]
- [x] I have searched open and closed issues for duplicates
  

---

### Bug Description

As in the title : when either searching for a term in a conversation, or a recipient to send a message to, accentuated uppercase charactres (e.g. "É") are considered different than the same accentuated but lowercase character (e.g. "é").

Language is french.

### Steps to Reproduce

1.  Open Signal
2.  Tap the "Search field"
3.  Type (for instance) "éric"

Actual Result:

My contact "Éric" is not shown.

Expected Result:

My contact "Éric" is shown.
I need to explicitely type "Éric" (or "ÉRIC", or any other upper/lowercase combination except for "É")
Also, typing "eric" or "Eric" or "ERIC" (etc.) should also display "Éric".

### Platform Info

Signal Version:

Signal 4.52.4
Not sure about Signal Desktop.

Operating System:

Android 9 (LineageOS 16)

Linked Device Version:

**Comment by pericleskb** [comment]
This must have to do with SQLite. As it says here https://www.sqlite.org/lang_expr.html#like

> SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE.

**Comment by i7u** [comment]
This bug occurs for any non-ASCII search term, breaking search in most non-English languages. Seeing the same with non-accented characters.

**Comment by second-reality** [comment]
I tried to notify dev who closed this MR so he can integrate this as well:

https://github.com/signalapp/Signal-Android/pull/9692#issuecomment-727223772

Indeed, that would make contact search much more usable in french (and any language with accented names).

**Comment by chtixof** [comment]
I confirm that in French, characters with accents should be sorted in the same place as normal characters and, sure, be found if searched without accent. The correction of this bug will make the app a lot easier for French users. Thanks.

**Comment by Booteille** [comment]
Is there any plan to improve usability of search, in French and other languages having a lot of accents, by considering accentuated characters as the same as non-accentuated characters?
It's always a bit frustrating to searching for "etienne" and that Signal is not finding "étienne"...

**Comment by Caerbannog** [comment]
This issue was solved by https://github.com/signalapp/Signal-Android/pull/10202 and released in 5.9.1.
It can be closed.

**Comment by Booteille** [comment]
Thanks for taking us involved here!

I noticed it's not working when searching with a "é". I am founding Etienne and Étienne when I type "e" but only Étienne when I type "é".

**Comment by breversa** [comment]
I guess it's actually fixed now. The "wontfix" label can go.
