### ISSUE TITLE
Copy / Paste not working 

### ISSUE THREAD

**Issue by hyde-stevenson** [signalapp/Signal-Android#9342]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to paste a copied text and got only the little icon (the littie drop shape that allows you to select text) and the "paste" bubble never appears ... 

### Steps to reproduce
- select text 
- use the copy button 
- paste it 

**Actual result:** nothing happens ... the cursor is just waiting 
**Expected result:**  It's supposed to paste the content ... 

### Screenshots

![IMG_20200115_112744](https://user-images.githubusercontent.com/28647553/72427077-453f9c80-378b-11ea-90e7-573d05c6c44f.jpg)

### Device info

**Device:** Oneplus Pro 7 with /e/ 
**Android version:** 9
**Signal version:** 4.52.4

### Link to debug log

https://debuglogs.org/305c16ac16055e90df4595e7429d593923e380bd7ca4b5726c97ac3c624f66d1

**Comment by greyson-signal** [comment]
We're using a standard EditText there. The copy-paste dialog is handled by the system -- we don't have any control over it. If you're having a problem, it's likely a problem with your OS. FWIW on most phones you have to long-press to show the "paste" button.

**Comment by hyde-stevenson** [comment]
I know it used to work but it stopped  just with signal ... the long press works with all other apps :/

**Comment by Trolldemorted** [comment]
Did you check your signal's privacy settings on your device?

**Comment by hyde-stevenson** [comment]
> Did you check your signal's privacy settings on your device?

Havent seen anything special on that side ...

**Comment by Trolldemorted** [comment]
Are "read clipboard" and "write clipboard" allowed or are they not? :)

**Comment by hyde-stevenson** [comment]
@Trolldemorted I dont have these in my signal settings :/

**Comment by Trolldemorted** [comment]
Those are not signal's settings, but your device's settings. You should ask in the [community forum](https://community.signalusers.org/) or a friend, we shouldn't use the issue tracker for tech support.

**Comment by hyde-stevenson** [comment]
I do agree but I don't see why it's not working with signal ... the copy/paste work for all other apps.

**Comment by abc162** [comment]
Hi there i have the same issue. When i press and  guild to paste into the message text area in signal nothing happens.  its an old phone, Samsung j5, but  copying and pasting works everywhere else in the phone and in whatsapp etc.
