### ISSUE TITLE
Equal characters "=" are not recognised as part of a link if the link is followed by other characters

### ISSUE THREAD

**Issue by lschmierer** [signalapp/Signal-Android#9343]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Equal characters "=" are not recognised as part of a link if the link is followed by other characters.

### Steps to reproduce
Write a message containing a link appended by space (or new line) and any other content.

**Actual result:** The "=" character is not underlined. Clicking the link does not open the complete link.
**Expected result:** Whole link should be underlined. Clicking the link should open correct website

### Screenshots

![Screenshot_20200115-153103](https://user-images.githubusercontent.com/2204708/72442894-a11b1d00-37ad-11ea-9a98-57370cca420d.png)

### Device info

**Device:** HUAWEI Mate 9 lite
**Android version:** 7.0
**Signal version:** 4.52.4

Reproducible on other phones and Android versions.

### Link to debug log

https://debuglogs.org/6bced7eff18985e28556574e0630379f58391eff700285901c1c464261ffee3d

**Comment by codethief** [comment]
To add to this, equal signs are perfectly valid characters in a URL's [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier).

**Comment by codethief** [comment]
Yes, this is still relevant.

**Comment by lschmierer** [comment]
This is still an issue.
![Screenshot_20220404-092517](https://user-images.githubusercontent.com/2204708/161494572-99001643-8cf5-43a4-b532-d382e299c723.png)

**Comment by greyson-signal** [comment]
Hi there, we use the standard Android linkifier. I don't anticipate writing a custom linkifier in the near future. But thanks for the detailed report!
