### ISSUE TITLE
CANNOT BUILD THE PROJECT 

### ISSUE THREAD

**Issue by Mosta-777** [signalapp/Signal-Android#9345]
Following the instructions in BUILDING.md results in build fail using the command
./gradlew build

results in the following output

Execution failed for task ':libsignal-service:test'. I tried searching the support community and the issues here and found no answer

**Comment by strugee** [comment]
This is an issue tracker; please don't post support requests here that aren't bugs. You could post on the forum instead: https://community.signalusers.org/
