### ISSUE TITLE
Forced  update / expiry

### ISSUE THREAD

**Issue by kreil** [signalapp/Signal-Android#9346]
- [x ] I have searched open and closed issues for duplicates
There are discussions about o/s specific auto-update issues but that's not my point.
I have submitted a related issue as #3882 for the Desktop app, as it affects both.
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

I am reporting an issue, not a bug, in that the behaviour is likely by design, but it breaks usability.

### Steps to reproduce
- run Signal
- refuse updates for several days

**Actual result:** app stops working. This would make sense if the old version had security issues. Often it does not, and the update is either just cosmetic, or adds a language, or perhaps a new feature.
**Expected result:** app should offer to fall-back to running with the features of the current version; if security permits.

### Device info
**Device:** Samsung S7 edge
**Android version:** 8.0.0
**Signal version:** 4.5.2

### Link to debug log
As the issue is likely by design I doubt you need to debug it.

**Comment by greyson-signal** [comment]
Hi there, as you noted, this isn't a bug. Feel free to discuss this on the [forum](https://community.signalusers.org/). Thanks!

**Comment by hacxman** [comment]
There is nothing to discuss. Application "expiring" for no reason is a problem.

**Comment by kreil** [comment]
Indeed.

I would understand and support a forced update policy for security critical
updates that need to be installed to avoid compromising others in a
conversation.

Disabling the Signal client for cosmetic or feature updates, however, is
dangerous to users in internet restricted environments and generally
unnecessary and unpleasant.
