### ISSUE TITLE
Screenshots folder does not show when attaching photos

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#9347]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When tapping "Gallery" when attaching something, the Screenshots folder does not show.

### Steps to reproduce

1. Take a few screenshots
2. Open a Signal conversation
3. Tap the "+" button to attach something (note that in the strip of recent photos at the top, recent screenshots _do_ actually show)
4. Tap "Gallery"
5. Look for the Screenshots folder

**Actual result:** the Screenshots folder does not appear.
**Expected result:** It appears.

### Device info

**Device:** Pixel 3a XL
**Android version:** 10
**Signal version:** 4.53.7

On my device screenshots are stored at `/sdcard/Pictures/Screenshots`. Interestingly, other folders in there are not shown either (for example, `/sdcard/Pictures/Raw` is not shown in Signal's gallery view) although raw images _do_ show up in the "All media" view.

### Link to debug log

https://debuglogs.org/f75718cc95e6422cc22d6fdb4a72721050693a644e27ae39d210e28eebabe465

**Comment by greyson-signal** [comment]
I don't have a 3a, but I do have Pixel 3 and a Pixel 4, and both of them are showing the screenshots folder. 

We generate the list of folders by querying for all media, iterating over that media, and making note of all of the unique folders. The folders don't necessarily correlate to folders in the file system though -- it's whatever logical folder grouping Android tells us it is. That might be why `/Pictures/Raw` isn't there. Android might just tell us they're "Pictures".

Curious about screenshots though. I remember a while back (I think in the Q beta?), the screenshots folder was missing for me too, but then it was fixed via an Android system update. I'm wondering if you're seeing a similar problem.

**Comment by Tursko** [comment]
I have the same behavior as greyson. I have a Pixel 4 and my screenshots show.

**Comment by strugee** [comment]
Hm, interesting. So maybe this is a system bug? Can you link me to the part of the source code where that API is called? I could try to reproduce a smaller test case.

I will say that, to be perfectly frank, I've noticed that since upgrading to Android 10 there have been a number of rather obvious (UI) bugs I've hit now and then. Maybe QA on this release was just lacking, who knows. But it wouldn't terribly surprise me if some bug like that didn't get caught. I also noticed while looking into this ticket that for some reason my device didn't automatically pick up the January security patches and I had to manually install them. I haven't rebooted into the new system image yet but I'll do that soon and see if that affects the Signal problem reported here.

**Comment by strugee** [comment]
Looks like this bug doesn't exist after all, my Screenshots folder just got buried waaaaaaay down the gallery display whereas before it displayed right at the top. Maybe the API got changed so it got sorted alphabetically instead of by date or something? Who knows. But anyway, closing since this report is invalid.
