### ISSUE TITLE
Signal prefers SIM Contacts

### ISSUE THREAD

**Issue by Ganneff** [signalapp/Signal-Android#9350]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is prefering contact data from the sim card over the "real" contacts from the phone.

### Steps to reproduce
- "export" contacts to your sim (there are multiple sim management tools available that can help with it)
- wait a bit (until Signal refreshes its knowledge about contacts, whatever time interval that is)

Now, the interesting part here is: SIM contacts are very limited in length (16 characters), so longer names get truncated.

And Signal shows truncated names all of a sudden.

Also, when you exported contacts a while ago, it may happen you change the name of one of your contacts using the usual android ways. With a usual setup, thats a local phonebook or a google addressbook. Whatever. Name is changed. Default Android Contact app shows changed name.

Signal won't. Ever. It uses the (possibly truncated or by now just wrong) name from the SMS.

Android also allows you to select "Which contacts to display" (in contacts app settings, slightly different where exactly, depending on the app) and about all of Android then follows this. Say, you select Google and Phone Contacts only, disabling SMS. You wont see the SMS stored ones - except in Signal.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Follow the same as the rest, honor the "addressbooks to display". Wherever that setting ends up, it appears to be central (using multiple different dialers, they all follow what any of them set).
Or add an own option that lets one disable some sources for contacts.

### Device info
**Signal version:** According to play store, 4.53.6 from 13. January 2020

**Comment by Ganneff** [comment]
Of course it is, the devs are just ignoring it, instead adding useless crypto currency crap.

**Comment by Ganneff** [comment]
Of course its still valid, stupid useless bot.

**Comment by Ganneff** [comment]
No, you lying bot.

**Comment by cody-signal** [comment]
We made a change recently with how we import contacts. Can you install the latest app and then reproduce the issue? The quickest way to force a contact refresh is to pull to refresh on the new conversation contact selection screen (after tapping the pencil from the main screen)
