### ISSUE TITLE
Add Xiaomi Mi A2 to echo cancellation blacklist

### ISSUE THREAD

**Issue by JoaquimCSantos** [signalapp/Signal-Android#9351]
The problem was resolved a few weeks ago and came back in the latest versions. The two links below are reggarding the same issue that was closed before but has now returned in the most recent updates.

Thank you!

https://github.com/signalapp/Signal-Android/pull/9198

https://github.com/signalapp/Signal-Android/issues/7635

**Comment by igor2x** [comment]
It reappears in 4.53.6-beta in commit https://github.com/signalapp/Signal-Android/commit/29d6d3c041d857bfc5f94b4631f2f7587f599c06

When new stable release is released probably in few days interval, this problem is going to be fixed.

**Comment by letkan** [comment]
It's there in v4.53.7 but Mi a2 Lite is still missing, I filed an issue on this months ago

**Comment by msavara** [comment]
When this will be resolved ? I still have an problem with echo on Xiaomi Mi A2.

**Comment by fklrx345** [comment]
Please also add ro.product.model = "Moto G4 Plus" to the HARDWARE_AEC_BLACKLIST. The "Moto G4" is on the list but the Moto G4 Plus is also affected with echos. Thank you!

**Comment by ozgurakyazi** [comment]
Xiaomi Redmi Note 7 has the same issue for months. Please also add that.

**Comment by AlessioGiambrone** [comment]
Also Xiaomi Mi A3 .

**Comment by ozgurakyazi** [comment]
Can anybody from the team label this issue as "calling"? Opened 3 years ago, comments are coming since months and no response.

Thank you :)

**Comment by CaptainTyphoo** [comment]
I have the same issue on Sony Xperia X compact (Lineage OS 16.0)

**Comment by rpl2020** [comment]
@greyson-signal Please also add model "OPPO A37m" to the HARDWARE_AEC_BLACKLIST. The other end is hearing a loud screeching noise when speaker phone is on. Thank you!

**Comment by JoaquimCSantos** [comment]
I'm opening this issue again, with the bug report that is now requested

**Comment by maymage** [comment]
@JoaquimCSantos 

Echoing is back on Xiaomi Mi A2..
