### ISSUE TITLE
Error signing release -self build

### ISSUE THREAD

**Issue by letkan** [signalapp/Signal-Android#9358]
I'm building Signal Android 4.53.7 myself (./gradlew build) on Arch Linux and at the very end I get this error:

>Signal-Android/app/build.gradle' line: 396

>\* What went wrong:
?Execution failed for task ':Signal-Android:signProductionPlayRelease'.
java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.\<init\>(java.lang.String)

How can I deal with this? Thanks

**Comment by greyson-signal** [comment]
That's how we sign release builds. If you want an unsigned build, just run ./gradlew assemblePlayDebug. If you want a build signed with some other key, direct questions to [the forum](https://community.signalusers.org/).
