### ISSUE TITLE
SMS Verification Code not received

### ISSUE THREAD

**Issue by jetlirizairi** [signalapp/Signal-Android#9364]
[ x ] I have searched open and closed issues for duplicates
    [ x ] I am submitting a bug report for existing functionality that does not work as intended
    [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
    [ x ] This isn't a feature request or a discussion topic

**Bug description**

The SMS that carries the verification code for registration never arrives on my number, which belongs to the Telekom Albania phone carrier. I do receive verification codes from other apps.

Also I am pretty sure that around 10 months ago I did he verification with the same number. Only thing that changes is I did a format a week ago.

Number starts with:
+355 68 .... 

Actual result: The SMS never arrives
Expected result: The SMS should arrive
Device info

Device: LG V20 H990DS
Android version: 8.0
Signal version: 4.53.7

Link to debug log:
Cannot access that. Problem keeps me from creating an account.

**Comment by alan-signal** [comment]
If you wait for the code for about 90 seconds, a "call me" option appears.

Alternatively please contact support@signal.org

**Comment by jetlirizairi** [comment]
> If you wait for the code for about 90 seconds, a "call me" option appears.
> Alternatively please contact [support@signal.org](mailto:support@signal.org)

Yeah I had tried call me as well, it doesn't work either.
I contacted support.

**Comment by saurabhgupta050890** [comment]
Same issue for me. Never received the SMS. Received call though. 

Logged in with Indian Number (+91) on MI Note 5 pro with MIUI 11 (Android 9 PKQ1.180904.001)

**Comment by jetlirizairi** [comment]
Issue fixed from Signal by contacting the sim card provider in Albania, they fixed it and now it works.

**Comment by happycamper1129** [comment]
I want to receive sms verification code by email.
