### ISSUE TITLE
Temporary Backup file not deletet

### ISSUE THREAD

**Issue by Chatron** [signalapp/Signal-Android#9365]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Most of the time when Signal creates it's backup file, it creates a tmp file in Android/data/org.thoughtcrime.securesms/cache/ named something like backup123456789tmp.
Most of the time, this tmp file will not be deleted after the backup has completed/failed. So there are many of this files with an size (in my case) of about 1GB each. So my devices runs out of memory because of this tmp files. 
This is happen also with versions before 4.53.7

### Steps to reproduce
- Activate Backups in Signal App
- Let Signal do some Backups or fail some

**Actual result:** 
The tmp file is not deleted as it should when backup failed/terminated
**Expected result:** 
The tmp file should be deleted

### Device info
**Device:** Huawei Mate 9
**Android version:** 9.0.0
**Signal version:** 4.53.7

**Comment by johanw666** [comment]
There have been changes in 4.54 to cope with this, do they help? If your device is running out of space you can of course clear the app cache as a temporary measure.

**Comment by alan-signal** [comment]
Yes, clear the app cache to get back on track, then this should not re-occur.

**Comment by Chatron** [comment]
So I'll waiting for the Playstore to push me version 4.54 and then I'll report. 

I've cleared the app cache a lot of time, but the problem is still there.
I will report back as soon i've get pushed v>= 4.54 from playstore.

Thanks

**Comment by Chatron** [comment]
OK, seems that the problem is solved for v>= 4.54.

Thank you guys
