### ISSUE TITLE
[feature request]: extreme mute

### ISSUE THREAD

**Issue by Rik44444** [signalapp/Signal-Android#9366]
i have a feature request:

an 'extreme mute' function, whereby you 1) do not receive notifications of the group or chat (as in normal mute), but also as an extra for the extreme mute **2) the group or chat also does not end up on the top of your list of messages when something is posted in that group or chat, but just stays either completely on the bottom or is ranked in your message list based on YOUR last post.** Use case: i have several groups that i cannot leave (eg some work groups) but where my input is not needed on a daily or even weekly basis. I'd like to be able to check this group every once in a while, when i feel like it, instead of being prompted every time that this group exists.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
