### ISSUE TITLE
android not waking up at incoming calls /missed calls

### ISSUE THREAD

**Issue by signaluser111** [signalapp/Signal-Android#9368]
calls from signal user (latest version) or messages don't wake up android (9) with locked screen. after unlocking phone and opening signal there are missed calls/ messages notifications.

this only happens.when signal is closed before the screen lock. I discovered when signal is closed there is no signal background task running!

there should be a small signal service always running in the background (incl. autostart of signal, at least optional in the settings) ..is this intended? a bug?

**Comment by Aquaplast** [comment]
same

**Comment by Ryan-Estwick** [comment]
This does not follow the Signal issue template. Please use the issue template at https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
