### ISSUE TITLE
Conversation View: Consistent message order

### ISSUE THREAD

**Issue by martinlablans** [signalapp/Signal-Android#937]
Please correct me, but as far as I can tell, messages are sorted by time of arrival. However, since the messages are transported either via SMS or via Google Cloud Messaging, both of which don't guarantee ordering, messages may appear in the wrong order. This means that chat participants may see deviating orders of messages, replies to messages they don't even see. In theory, it's even possible that several messages from the same sender arrive and are displayed in wrong order.
- Idea 1: Sort the conversation view by "sent" timestamp. See also #806. Problem: What is the "sent" date? Is it reliable? Is it set by the client or the TS server (farm)?
- Idea 2: Give each message a sequence number generated by the TextSecure server. Sort conversation view according to those numbers. Problem: Many, but not all messages go through the TS server.
- Idea 3: Employ vector clocks.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/message-ordering/2581).
