### ISSUE TITLE
timestamps on message bubbles are not updated as long as no new message is send or received

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9370]
- [x] I have searched open and closed issues for duplicates
- [?] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
timestamps on message bubbles are not updated while composing a new message

### Steps to reproduce
- open a chat in which a message was recently send or received (It shows as now, x min ago or x h ago)
- start typing a message, but don't send it.

While you are typing, but also when you stop typing, and even when you close the keyboard but leave your text as a concept, the timestamp on the message bubbles above will no longer update.

### Device info

**Device:** Motoroal Moto G7 Plus
**Android version:** 9.0
**Signal version:** 4.54.1

**Comment by pericleskb** [comment]
It looks like composing a message or not does not matter. It just won't update until a new message is sent in the conversation.

**Comment by Meteor0id** [comment]
This could be by design because @greyson-signal mentioned before he doesn't like 'jittery timestamps' which change while you look at them. Yet if this is by design maybe it should be reconsidered?

For people with a screen deactivation timer set to a long time period or who browse through conversation history for a while it can be quite weird (even confusing) if the message at the bottom still reads "now" 15 minutes later.

**Comment by TheWorstSaint** [comment]
Jittery timestamps are one thing but having timestamps that never update until you do something in the app is another.

Perhaps this is a different issue but here are the steps to reproduce:
1. Open any chat to anyone (SMS or Secure messages) in Signal messenger
2. Leave your phone for any duration of time (e.g. 10 minutes) and, in my case, allow it to lock after 30 seconds
3. Return to your phone and unlock it

Expected results:
- Timestamp for messages (i.e. the "Xm" representing the number of minutes ago the message was sent or received) in the chat bubbles are relative to now
- The "Xm" reflects how long ago the messages was sent or received

Actual results:
- Timestamps are incorrect
- Timestamps are relative to the time you opened the chat in step 1. 

Device: Samsung S10
Android version: 10
Signal version: 4.68.8

**Comment by floscher** [comment]
If the timestamps shouldn't change, they probably should not be relative. With absolute timestamps this would not be a problem.

Or if you want to cater to both people who want relative timestamps and those who dislike jittery timestamps, offer an option in the settings:
* to either show relative timestamps that update over time
* or to show absolute timestamps that don't change

**Comment by infinitewaveparticle** [comment]
Honestly, if timestamps were in seconds we should be able to watch them change like a stopwatch.

**Comment by greyson-signal** [comment]
I believe we fixed this a few weeks ago :+1:
