### ISSUE TITLE
How to solve

### ISSUE THREAD

**Issue by yangxp108** [signalapp/Signal-Android#9373]
How to solve
![Screenshot_20200130_193509_org thoughtcrime securesms](https://user-images.githubusercontent.com/6278830/73453874-e5124280-43a7-11ea-99db-f846b4c0dd9f.jpg)

**Comment by greyson-signal** [comment]
You must update Signal to the latest version.

**Comment by yangxp108** [comment]
Can I change to the latest version in the code

**Comment by yangxp108** [comment]
> 您必须将Signal更新为最新版本。
我可以将代码更改为最新版本吗

**Comment by yangxp108** [comment]
canonicalVersionName

**Comment by yangxp108** [comment]
canonicalVersionName
