### ISSUE TITLE
Profile leak?

### ISSUE THREAD

**Issue by cyrusadkisson** [signalapp/Signal-Android#9374]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Received an SMS from a non-signal user and hit "reply" in the drop down notification. Alarmingly, my picture showed up (which I've never added to Signal) and my name showed ("A Guy") which I never set as my profile name. I happen to know that my ex-girlfriend used that picture and that name in her phone for me. So WTF am I seeing it?

Does this mean that the images and names I've put in my phone for others are leaking out to them?

### Steps to reproduce
- Install signal
- Get some contacts
- Have a contact change your profile picture and name
- See if they appear that way on your phone too
- (Unfortunately, I don't have multiple phones to reproduce exactly)

**Actual result:** No image should show up and my name should be what I set it to.
**Expected result:** An image someone else used in their phone for me is showing up and the name they set for me is also on my phone.

### Screenshots
![Screenshot_20200131-084830_Signal](https://user-images.githubusercontent.com/2284720/73544455-2f76dc00-4407-11ea-83f9-426c0e8646b3.png)

### Device info
**Device:** OnePlus A5010
**Android version:** 9
**Signal version:** 4.53.7

### Link to debug log
none

**Comment by Meteor0id** [comment]
Please generate a debug log! I assume this happened just now?

**Comment by cyrusadkisson** [comment]
It's possible I set my profile pic and name to "A Guy" at some point (possibly late at night...etc) and then forgot. I'd just never seen it in Signal before as I did today, so it was a bit jarring. I guess there was a change recently that would make the profile visible to oneself. 

If no one else can confirm, then I'm going to close and consider it pilot error.

My bad.
