### ISSUE TITLE
Icon in Play Store not compliant with latest guidelines

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9377]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is not a bug of the app itself, but of the Play Store listing.
Google has some new guidelines how icons must look like and old icons have been migrated. The icon of Signal is now smaller than the other icons and looks bad this way.

> Original icon assets that have not been updated per the new specifications will eventually be migrated to legacy mode and scaled down 75% to the keyline grid size (512 * 0.75 = 384px).

https://developer.android.com/google-play/resources/icon-design-specifications

I posted this in the forum two months ago: https://community.signalusers.org/t/icon-in-play-store-not-compliant-with-latest-guidelines/10490

### Steps to reproduce
- Open Signal in Play Store

### Screenshots
https://community.signalusers.org/t/icon-in-play-store-not-compliant-with-latest-guidelines/10490/7

**Comment by greyson-signal** [comment]
We’ve submitted an updated icon to the Play Store. I imagine it’ll take time to propagate. Thanks!
