### ISSUE TITLE
What's the max amount of people that can be in the same group

### ISSUE THREAD

**Issue by developerfromjokela** [signalapp/Signal-Android#9379]
Hello,

I've googled alot this one question: **How many people can be in same group chat?** 

I wish someone can answer my question :grinning:

**Comment by u32i64** [comment]
This issue tracker is reserved for bug reports; questions like this should be asked on the [community forum](https://community.signalusers.org/) instead. An answer already exists in [this topic](https://community.signalusers.org/t/what-is-the-maximum-size-for-a-group-chat/2316/4?u=u32i64) though.
