### ISSUE TITLE
Image viewer shows received images in reverse order

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#9381]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you receive a message that has multiple images attached, the image viewer lists them in reverse order from how they were sent and are displayed in the message. This is easier to understand by looking at the attached screenshots.

The bug only seems to happen for *received* multi-image messages. The images in *sent* messages appear in the correct order. You can also reproduce it using Note To Self, but you have to send the original message using another linked client (eg, Signal Desktop).

### Steps to reproduce
1. Receive a message containing multiple image attachments
2. Tap on the first (left-most, top left, etc) image in the attachment preview
3. See bug

**Actual result:** The image opens and is the *last* image in the set, and you have to scroll to the left to see the others.
**Expected result:** The image should be the *first* image in the set, and scroll to the right to see more.

### Screenshots
This is the "received" message in the Signal Android client -- the original message was sent to Note To Self using Signal Desktop. This is the same order they were added in the Desktop client and I have numbered them to help with the comparison:
![signal-2020-02-05-124729](https://user-images.githubusercontent.com/10427164/73905198-21401a00-4864-11ea-9654-a0cecd571234.jpg)

Now I have tapped on image 1, which I would expect to be the first image in the set. Instead, it is the last image, and the set is in reverse order:
![signal-2020-02-05-124729-1](https://user-images.githubusercontent.com/10427164/73905208-2735fb00-4864-11ea-9354-0f7bdb4eda13.jpg)

### Device info
**Device:** Pixel 2 XL
**Android version:** 10
**Signal version:** 4.54.3

Related topic on the forum:
https://community.signalusers.org/t/received-multi-image-messages-have-reverse-ordering/11631?u=herohtar

**Comment by u32i64** [comment]
As I said in [my post](https://community.signalusers.org/t/received-multi-image-messages-have-reverse-ordering/11631/3?u=u32i64) on the forum:
> I think I saw it be correct one time (i.e. in normal and not reversed order).
> 
> But overall it is reproducible for me in at least:
> 
> - 4 received group messages (each has 2–19 media).
> - 1 sent group message (6 media).
> - 1 Note to Self message sent from the main device.
> 
> Signal 4.55.3, Pixel 3 XL, Android 10

I'm still being able to reproduce this bug on new messages in Signal 4.55.6.
