### ISSUE TITLE
Notifications not appearing on Active Display [FIX INCLUDED]

### ISSUE THREAD

**Issue by cdebavel** [signalapp/Signal-Android#9384]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The notifications appear everywhere they're expected, except for the Moto Z screen when it's locked and the screen is off. The notifications only appear when I have unread messages from multiple contacts. This was an issue a year ago and was fixed, and now recently reintroduced.

### Steps to reproduce
- Lock phone (so display is off), with no unread messages
- Receive a single message

**Actual result:** A notification sound is played, but no notification appears on the Active Display
**Expected result:** Active Display should show that there is a Signal notification (which it does if there are notifications from multiple conversations)

### Device info

**Device:** Moto Z Play
**Android version:** 6.0.1
**Signal version:** Latest beta

### Solution
Commented here: https://github.com/signalapp/Signal-Android/commit/3bd8aa8a86cfb69331af2b79b544f24fb648cd62#commitcomment-37027517

### More info
I've identified the changes that broke the notifications. The problem is the changes to MessageNotifier.java in commit 3bd8aa8a86cfb69331af2b79b544f24fb648cd62 (Apply MessageStyle and fix chronology issues.

This line *must* be present for notifications to work properly on Moto Z:
builder.setGroupAlertBehavior(NotificationCompat.GROUP_ALERT_SUMMARY);

This happened a year ago too. Notifications were broken by this change:
https://github.com/signalapp/Signal-Android/commit/a0c1446e9ff283b6e77cceb79ee16ba4e3c089d9#diff-e58de40942d2bd2d9edf608320b23cdb

and then were fixed by this change:
https://github.com/signalapp/Signal-Android/commit/45ddb7e1ad05a599a89cf84185a6087279483ee8#diff-e58de40942d2bd2d9edf608320b23cdb

This recent commit is responsible for the currently broken notifications:
https://github.com/signalapp/Signal-Android/commit/3bd8aa8a86cfb69331af2b79b544f24fb648cd62

**Comment by ozgurakyazi** [comment]
Could this be somehow related to #9414 . Good Work!!
