### ISSUE TITLE
No mandatory pins

### ISSUE THREAD

**Issue by mitomenai** [signalapp/Signal-Android#9385]
Please reconsider forcing mandatory pins onto users. Not all of us need a tank when we are shopping for a car. The inherent risks and decision should be left up to the user.

The recurring prompts are especially annoying. 7 day reminders are too much for a pin you'd only need once every two years and are likely to write down along with your backup key anyways. With no way to turn off these prompts, I would unfortunately have to move on to a different platform.

**Comment by Genis-Sage** [comment]
hey @mitomenai 
thanks for you input,
but Guthub is reserved for bug reports

feature requests and design discussion belong in the community forum
https://community.signalusers.org/

addiotionally, as mentioned in the community forum, in the beta feedback,
starting with 4.55.4, the PIN is not mandatory anymore
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-55-release/11569/122

so you can directly close this ticket again

best regards
