### ISSUE TITLE
sealed sender icons not displayed only on some group messages

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9387]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Display status indicators is enabled, and they do show on Saturday me of my send messages, but in a group chat they do not show on all of my send messages.

By the way, I still wonder why there is a switch to turn on or off just the indicators. Isn't it about time to remove that setting and just turn them on by default? This is an unnecessary switch to bother users with.

### Steps to reproduce
- enable the indicators using that silly toggle switch in Privacy options
- look at the message details on a number of your send messages in a group chat
- note that on some the indicators are displayed, but on some there are no indicators displayed
- scratch your head, and wonder if this is merely the indicator not showing or some kind of deeper issue with sealed senders

**Actual result:**
Indicators not showing on all send messages
**Expected result:** 
Indicators should show on all send messages

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 9.0.0
**Signal version:** 4.55.4

### Link to debug log

https://debuglogs.org/16501890c8614eb38c9f78c544df1b23d1e06ee31d13204b69d7e2bb9451d380

One of these messages wad one I send
7 feb @ 15:28:22 CET

**Comment by Sgn-32** [comment]
The sealed sender indicators are only shown on contacts, which you have interacted before.
