### ISSUE TITLE
heic not showing as preview

### ISSUE THREAD

**Issue by aquatic7** [signalapp/Signal-Android#9395]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending and receiving image files to and from contacts I do not see the image when it is in .heic format. Other image types render correctly. **Same apply to Desktop version.**

### Steps to reproduce
- On android phone, select heic file from gallery
- Send with signal to another android contact

**Actual result:**  Image preview is not rendered inline. Downloading the image and viewing it in another app works fine.
**Expected result:** Image is shown in chat

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 10
**Signal version:** 4.55.8

Same issue noted for IOS: https://github.com/signalapp/Signal-iOS/issues/4374

**Comment by u32i64** [comment]
This should be closed as https://github.com/signalapp/Signal-Android/commit/47128338534482a7a92610b5ec6c690925727be1 was merged?
