### ISSUE TITLE
New message reactions feature does not respect emoji setting

### ISSUE THREAD

**Issue by krathalan** [signalapp/Signal-Android#9396]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The new "react to a message with an emoji" feature is great, but it does not respect the "Use system emoji" setting -- it uses iOS style emoji. I strongly prefer the Android emoji to iOS emoji, and it was very jarring to see iOS emoji where I did not expect them, as I had told Signal to use the system emoji.

### Steps to reproduce
- long-press a received message to react to it

**Actual result:** iOS emoji reactions are displayed
**Expected result:** When the "Use system emoji" setting is toggled on, the emoji reactions should be Android-styled

### Screenshots

![Screenshot_20200214-081715_Signal](https://user-images.githubusercontent.com/25400030/74548484-dc903f00-4f45-11ea-8ace-2b82b2b89f0e.png)

As you can see, the messages displayed by Signal respect the "Use system emoji" setting, but the reaction emojis do not.

### Device info

**Device:** Xiaomi Poco F1
**Android version:** Android 9 Lineage 16.0 No GApps
**Signal version:** 4.55.8

**Comment by greyson-signal** [comment]
This behavior is intended for various technical reason, but we may change it in the future.
