### ISSUE TITLE
Restoring backup FCs app.

### ISSUE THREAD

**Issue by DevMashru** [signalapp/Signal-Android#9398]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal force closes just after restoring most/all messages.

### Steps to reproduce
- Fresh install of signal.
- Open app and grant all permissions.
- Enter the passphrase.

**Actual result:** FCs after restoring most/all messages.
**Expected result:** Should ask you to enter the phone number.

### Device info

**Device:** Xiaomi Poco F1
**Android version:** 10.0 (Pixel Experience)
**Signal version:** 4.56.0

### Link to debug log
https://hastebin.com/cuyicaxiso.md

**Comment by DevMashru** [comment]
Issue persists with v4.56.1 as well.

**Comment by DevMashru** [comment]
I restored an older backup and it seemed to work just fine. Maybe the backup was bad and hence it wasn't working as intended.

**Comment by djilke** [comment]
Sadly, I am having this exact problem, tested with both available backups.
Backup is ~2.2GB in size, Signal FCs at ~17.000 messages.
The debug log points at an error occurring when trying to do something in the background.
Display is on the entire time.

https://debuglogs.org/79a737ef3c2c70d26a14d6404cb449113c95f673c3e0fd6a06a310083a68334f
