### ISSUE TITLE
Emoji Waffle Missing

### ISSUE THREAD

**Issue by akissz** [signalapp/Signal-Android#9399]
The Emoji Waffle icon is missing in Android but is shown in the Mac desktop version. If you type the Waffle in Mac version in Android version you see a box with X inside, the missing Character symbol.

**Comment by shreve** [comment]
I believe that's your phone and not Signal. Signal should be using the emoji font available on the system. Your mac likely has a newer version than your phone. Are you able to type the waffle emoji in any other app on your phone?

**Comment by akissz** [comment]
Correct. Seems to be the system font in the device. But why is Waffle included with Signal but not WhatsApp? Seems unusual. Is the addition in Signal newer than WhatsApp? Seems to be a larger conflict than only the font on one system or another.

**Comment by greyson-signal** [comment]
Signal has it's own custom emoji. That set can get out of date. When we're missing one, it falls back to the system emoji, which you also seem to be missing. 4.57 will have the waffle emoji.

**Comment by Sgn-32** [comment]
Waffle emoji and more were added with 4.57. https://github.com/signalapp/Signal-Android/commit/44e845c8757b1671b791104e1803fac614cca969
