### ISSUE TITLE
Disable reactions

### ISSUE THREAD

**Issue by reetp** [signalapp/Signal-Android#9400]
The latest 'enhancement' with reactions is awful.

Inaccurate and annoying with no apparent way to disable it.

Not only that but something or someone is reading my messages to provide a response. That is a privacy concern for me.

Please at least provide a method to disable this nonsense.

**Comment by alan-signal** [comment]
"Reactions" is a new feature whereby you and your chat partners can respond to messages with an emoji.

https://signal.org/blog/reactions/

But it sounds like you are actually describing Android 10's "Smart Reply" feature. Where a couple of reply options are given in the notifications. Please read this forum discussion if that is the case:

 https://community.signalusers.org/t/android-10-smart-reply/9142

**Comment by reetp** [comment]
Thanks for the response.

Seems that yes it is 'Smart(?) Reply' but it is non obvious.

On this S9 with Android 10 it seems you can disable globally with:

Settings, Notifications, Suggest actions and replies

Although there is zero indication of what else this actually affects.

I am surprised that with there being an API setting to disable this in the app you didn't take advantage to add a switch.

**Comment by alan-signal** [comment]
Feel free to continue the discussion on the community thread.
