### ISSUE TITLE
Reactions emoji design does not match message emoji design

### ISSUE THREAD

**Issue by gartenriese2** [signalapp/Signal-Android#9402]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the new reactions, the design of the emojis does not match the design of the regular emojis, i.e. the emojis shown in the messages.

### Steps to reproduce
- The option to use system emojis is checked
- Write a message with a thumbs up emoji
- Set a thumbs up reaction to that message

**Actual result:** The emojis in the reaction selection menu and the actual reaction emoji look different to the emoji written in the message.
**Expected result:** All emojis should use the same design and are conform with the emoji setting in the option menu.

### Device info

**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 4.56.1

**Comment by greyson-signal** [comment]
We intentionally use the custom emoji for reactions for various technical reasons. We may look into changing this in the future.
