### ISSUE TITLE
Multiple selection removed by "Reactions" : feature lost

### ISSUE THREAD

**Issue by klorydryk** [signalapp/Signal-Android#9406]
Now that a long click is used for "Reaction", it is not possible anymore to do a multiple selection, of messages, to copy or remove, as it is still possible in "normal" sms.
It is an handy feature lost.
If you want to apply this "Reaction", you could use another gesture, like swipe to the left, for example.

v4.55.8, Android 9

**Comment by bug1303** [comment]
Why was this immediately closed? I'm feeling the same about this, a great feature lost!
I'd gladly give up on reactions to have the multiple selection feature back, but ideally one could have both at the same time.

**Comment by rainerzufall** [comment]
@bug1303 it is not lost. it is just one click more now. 
![signal-attachment-2020-03-24-110550](https://user-images.githubusercontent.com/12666598/77413367-8671af80-6dbf-11ea-9442-2a44d42bc970.jpeg)

steps:
1. long press on the first message you want to select
2. click on the multi-select button (highlighted in yellow in the picture above)
3. then long press the second, third, etc message you want to select.

For questions like this please come to the Signal community forum (https://community.signalusers.org/) first and only to github when you are certain it is a bug

**Comment by S3NTYN3L** [comment]
These features should be swapped.
Multi-select is MUCH more useful.
Make the silly and nearly useless Reaction feature involve the extra click.
