### ISSUE TITLE
Sticker Previews cannot be Dismissed

### ISSUE THREAD

**Issue by mikeymop** [signalapp/Signal-Android#9411]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you long press on a sticker, it will open a large format sticker preview on the screen. If you are in the activity that shows the sticker pack you can simply back out of the activity in order to hide the sticker preview.

If you are in a conversation, and have the sticker selector open and you long press on a sticker you will be unable to exit the sticker preview. And it will cover the signal ui until you pause or close the app.

Because this doesn't disappear, it can be hard to pick or preview another sticker after previewing one. 
Additionally you will have to exit a conversation in order to continue to use the conversation.

### Steps to reproduce
- Open a conversation, then the sticker choose OR open a sticker pack from the add stickers page
- Long Press on a sticker to preview it in full size and see the emoji tied to it

**Actual result:** 
The sticker preview opens, however tapping on the sticker preview and/or hitting back will not make the preview go away.

**Expected result:** 
When the sticker preview is open, I expect to be able to tap on the sticker preview which would call an onClick that would hide the sticker preview.

I also expect to be able to hit the back button to hide the sticker preview for sake of discover-ability (and the trust Android users have in the back button).

### Screenshots

I would have to edit one in order to obfuscate

![Screenshot_20200220-094204](https://user-images.githubusercontent.com/4002969/74945171-45077200-53c5-11ea-9d71-f73f9c19ffd2.png)

### Device info

**Device:** Essential PH1
**Android version:** 10.0
**Signal version:** 4.55.8

**Comment by greyson-signal** [comment]
Interesting, the preview is supposed to appear when you long press, and disappear when you lift your finger. Sounds like it's getting stuck somehow. I do have an Essential Phone, so I'll try it out and see if it's a device-specific issue.

**Comment by mueller-ma** [comment]
I had this twice on a Honor 6X, but am unable to reproduce. Because this was some time ago, I don't have a debug log.

**Comment by Sgn-32** [comment]
it is highly likely to be reproducible if the "preview" is repeated several times on the same sticker.
Long press and lift the first time the sticker disappear. Long press and lift on the same sticker a second or maybe a third time the sticker doesn't disappear.

It's dissappears after a slow double-click on the small sticker or with left/right swip.
If you hit in the middle of the sticker and get the hidden emoji switch, it's look like: 

![Screenshot_20200221-121336](https://user-images.githubusercontent.com/49990901/75036384-06031a80-54b2-11ea-89c5-cbf9d5612b1e.png)

The sticker image disappears but the emoji representation of the sticker stays.

**Comment by primarto** [comment]
If you long press on a sticker, it will open a large format sticker preview on the screen, and sticker It remains frozen on screen, in the background can continuie with normal use and until I get out of the conversation, sticker preview is on sceeen.

Sticker preview will close when with finger move left or right on some sticker.
