### ISSUE TITLE
Sync Bidirectional with Delete

### ISSUE THREAD

**Issue by akissz** [signalapp/Signal-Android#9412]
I hope there are plans to solve the Sync Bidirectional with mobile app and desktop app. Currently syncing only functions correct with the sending and receiving data. I want the removal of data to be in sync also like other apps like WhatsApp sync is much better. If you delete a text or image on the mobile app it should sync with the desktop, but it does not currently sync. If someone likes it this way then is there a plan to make settings available to turn this off so Sync Bidirectional is possible. Maybe Bidirectional is the incorrect word, but I hope you understand what I am talking about. Perhaps 4 way sync would be more correct wording. Also syncing should be full no mater what time you started the sync with the desktop. It should sync the whole chat or give option to scroll up, etc. It would seem this is all old functions, but they sure don't work good with Signal now. WhatsApp is much better with sync. (Sorry to even write the word WhatsApp here.)

**Comment by greyson-signal** [comment]
As noted in the issue template, github is not for feature requests. You can discuss this on [the forum](https://community.signalusers.org/). Thanks!

**Comment by derMart** [comment]
since when is github not a place for feature requests?? Please reopen this issue!

**Comment by akissz** [comment]
This is not a feature request. It is currently a feature that is broken badly. That is all. Yes, please reopen the issue.

**Comment by greyson-signal** [comment]
> since when is github not a place for feature requests??

Every Github repo has the right to run things how they like. We feel that the forum is a much better tool to discuss feature requests. We use Github exclusively as a bug tracker, and say as much in the issue template.

> This is not a feature request. It is currently a feature that is broken badly.

I define a bug as something that is not working as intended. What you describe is, in fact, working as we intend.
