### ISSUE TITLE
Images taken on a Huawei P20 Pro can't be saved on Android, and aren't displayed properly on Desktop

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#9415]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Taking a picture on Huawei P20 Pro and then sending it results in the picture looking fine on Signal-Android, however, if you try to save it, you can't with no apparent error message saying anything went wrong.

Also, it looks like an unnamed file with ".*" as file type.

### Steps to reproduce
1. Take a picture with the camera app on Huawei P20 Pro. Here's an example you can download and send:
https://www.dropbox.com/s/7i54fsxzw797yua/2020-02-22%2023.00.07.jpg?dl=0
2. Send it in Signal-Android. Sending it in Signal-Desktop seems to work fine, which is why I think this is a Signal-Android issue and not a Signal-Desktop issue.
3. Try to save it on the receiving end, in my case, Google Pixel 3a XL. Nothing is saved.
4. Look at the picture on Signal-Desktop. It should look like the picture attached below.
5. If you save the picture on Signal-Desktop (the latest beta), it works fine, but you have to choose your own file type as the file type is ".*" by default.

**Actual result:** The image doesn't seem to be converted properly... maybe?
**Expected result:** The image works fine, as it did just a few days ago

### Screenshots

![image](https://user-images.githubusercontent.com/12563436/75100105-d21b1880-55c9-11ea-8be2-93bc6d83c47b.png)

### Device info
Time         : 1582409742866
Device       : HUAWEI CLT-L29 (CLT-L29)
Android      : 9 (9.1.0.380C432, CLT-L29 9.1.0.380(C432E8R1P11))
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 63M (36.13% free, 512M max)
Memclass     : 384
OS Host      : cn-central-1b-9b39abfb61577946835141-3505357959-n3j1q
Refresh Rate : 60.00 hz
Average FPS  : 59.60
First Version: 552
App          : 4.56.1

### Link to debug log
https://debuglogs.org/7a2c440fa9cef476bc663b627bf340ea6c994880c7d98201e4ea9784fbec2bb6

**Comment by asim-vax** [comment]
This is also happening to a friend of mine using a Samsung S9 Note

Extra notes:
Other android users can see the image, but no signal desktop or signal iOS can view the image.

Confirm the below:
Signal desktop doesn't recognise it's file type - tries to save it as:
signal-attachment-2020-02-23-155723.*

**Comment by Dyras** [comment]
@asim-vax When did it start happening?

**Comment by Wikinaut** [comment]
I have the same starting here about 7 days ago.

System data:

* Signal Beta 4.56.1
* HUAWEI P8 LITE 2019
* Android 10
* EMUI-Version 10.0.0

Additional information:
* The telephone software received recently an update.
* Some media files - when sent as "not to myself" and then locally saved have ```.attach``` as filetype which makes them unprocessable even locally.
* I found that these files have - on the desktop - ```.*``` as ending
* It appears that larger media files (images and especially mp4 files) cannot be transported reliably via Signal anymore to recipients, very small files appear still to work.

**Comment by asim-vax** [comment]
@Dyras i can only say that it started happening yesterday (23/02/20) - but that is because the chat isn't insanely active, and not many images get added - so we only noticed it from yesterday

**Comment by greyson-signal** [comment]
The fix for this will go out in 4.56.2.

**Comment by Wikinaut** [comment]
Great, thanks.
