### ISSUE TITLE
Signal crashes when registering if Signal is already the default SMS app

### ISSUE THREAD

**Issue by matt18224** [signalapp/Signal-Android#9417]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes if it is already the default SMS app when attempting to register one's phone number.

### Steps to reproduce
- Open Signal and register
- Get to Signal message threads main screen
- Make Signal the default SMS app
- Clear Signal's stored data via system settings
- Open Signal and attempt to register again

**Actual result:** Signal crashes after beginning to automatically input the SMS verification code
**Expected result:** The verification code should be automatically inserted and confirmed. It worked as expected when the default SMS app was changed back to the Messages app before attempting the above steps.

### Screenshots
N/a

### Device info
**Device:** Huawei Nexus 6P
**Android version:** 9
**Signal version:** 4.56.1

### Link to debug log
https://debuglogs.org/10bf944503bae8df166fdf2b7bdef784cd2422ba0197c894d1587351e9f07b8e

Crash appears to begin somewhere around time 09:09:00

**Comment by sivaraam** [comment]
I observe the same behaviour in Signal 4.56.2 running on a Samsung SM-J111F with Android 5.1.1. This used to work (registering for Signal with Signal as default SMS app) without issues in older versions.

**Comment by zmni** [comment]
This happened to me to. Signal v4.55.8, Android 9, Nokia 5 TA-1053. Uninstalled buitlin sms app (Message), and set Signal as the default sms app. Signal gets killed by it's own verification sms.

The crash:
```
03-02 22:51:23.640  5138  5191 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
03-02 22:51:23.640  5138  5191 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5138
03-02 22:51:23.640  5138  5191 E AndroidRuntime: org.thoughtcrime.securesms.jobs.SmsReceiveJob$NotReadyException
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:75)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```
[Full logcat](https://gist.github.com/zmni/55e87cf982531e20f202156193326981/raw/617e1ac8d8079f98b076f66dfc6f0fe34717c9c2/logcat.log).

**Comment by GerritBergen** [comment]
This just happened to a friend of mine. Any updates?

**Comment by 015203087630** [comment]
Am 19.01.2021 19:37 schrieb "Gerrit Bergen" <notifications@github.com>:

**Comment by 015203087630** [comment]
Am 19.01.2021 20:34 schrieb "Sabrina die Liesel" <grandasabrina@gmail.com>:

**Comment by sivaraam** [comment]
The app doesn't crash these days which is nice but it appears to be incorrectly auto-filling the verification code when Signal is the SMS app during registration. Manually entering the received verification code works, though.

I suppose this is a different issue. I'll open another and close this one when I find the time.
