### ISSUE TITLE
Messages are not arranged by timestamp

### ISSUE THREAD

**Issue by gfs** [signalapp/Signal-Android#9418]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages sent from Signal Desktop may appear in a different order on Signal Android

### Steps to reproduce
- send a message using signal desktop linked to signal Android
- have the recipient, at approximately the same time send you a message 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The messages appear to be ordered by the order in which they arrive to the device. Not their timestamp order. The message sent from Signal Desktop, when sent first, may appear second. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Messages sorted by the displayed (I assume server) timestamp.

### Screenshots

![Screenshot_20200224-120835__01](https://user-images.githubusercontent.com/98900/75187344-b8c7b880-56fe-11ea-96d2-98132922229f.jpg)

### Device info

**Device:** OnePlus 7 Pro
**Android version:** 10.3.0
**Signal version:** 4.56.1

### Link to debug log

[https://debuglogs.org/a587faffa5264b7f82ef3b3563b10955b6c05c1d06b651b2ab4c3e0d4cf6c6df](https://debuglogs.org/a587faffa5264b7f82ef3b3563b10955b6c05c1d06b651b2ab4c3e0d4cf6c6df)

**Comment by u32i64** [comment]
I think this is by design: messages are shown [in the order they are delivered](https://community.signalusers.org/t/2581?u=u32i64).

**Comment by gfs** [comment]
I can restate the bug then and arrive at the same undesirable behavior. 

The server gave my device messages in an order other than their true timestamp order. 

Or alternately:

The same conversation viewed on signal desktop and signal Android becomes desynced and messages aren't displayed in the same order. 

Those all feel like subversions of user expectation.

**Comment by greyson-signal** [comment]
The reason messages must be displayed in received order is simple: new messages should always appear as the bottom-most message in a conversation. If they don't, that means that a new message could appear at an arbitrary location in your conversation history, which is bad, because not only could it cause people to miss messages, but it opens up different avenues for attacks and other deceptive behaviors.

Our solution is to display in received order, but render the sent time as the timestamp on the message.
