### ISSUE TITLE
Issue with compilation of Signal on windows despite following given instructions

### ISSUE THREAD

**Issue by ghu1234** [signalapp/Signal-Android#9420]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am trying to compile signal from the source code using the instructions given at

https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources

I am using windows. 

### Steps to reproduce
- Simply follow above link. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

a) First run 
I got build successful, but could not locate the apk (please see the screenshot1, Signal_BuildSuccessful_NoApk.jpg)
b) Second run
I got build failed please see the Signal_BuildSuccessful_NoApk.jpg and the log file, Signal-Android_a.txt (of what is shown on the command window)
![Signal_BuildSuccessful_NoApk](https://user-images.githubusercontent.com/60844318/75269812-8792d980-581f-11ea-9f5b-d30b4c49156d.jpg)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
I expected "BUILD SUCCESSFUL" AND apk showing up as given in the link above.
Instead I don't even see the directory called builds in the path suggested in the link above
Signal-Android\build\outputs

### Screenshots

![Signal_BuildSuccessful_NoApk](https://user-images.githubusercontent.com/60844318/75269830-8feb1480-581f-11ea-9b89-dcf05ae5fd3d.jpg)
![Signal_BuildFailed](https://user-images.githubusercontent.com/60844318/75269836-91b4d800-581f-11ea-9c97-db6c9dc306d0.jpg)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

I am not running any apk. This is not relevant to me.

### Link to debug log

Issue is with compilation, whose log has been put below. 
[Signal-Android_a.txt](https://github.com/signalapp/Signal-Android/files/4251162/Signal-Android_a.txt)

**Comment by greyson-signal** [comment]
You're experiencing some unknown AAPT issue. It's directing you to file an issue against AOSP. We literally ship new releases with the docker image in our reproducible build steps, so I'm confident our build works.

Any other questions can be directed to [the forum](https://community.signalusers.org/).

```bash
* What went wrong:
Execution failed for task ':Signal-Android:mergePlayDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #2: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #0: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #1: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #3: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #4: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #6: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #5: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.
Workers$ActionFacade
      > AAPT2 aapt2-3.5.1-5435860-windows Daemon #7: Daemon startup failed
        This should not happen under normal circumstances, please file an issue
if it does.
```

**Comment by Sagar0-0** [comment]
@ghu1234 I was facing the same issue, and after spending some time on it. The solution is to make your gradle generate the missing metadata of the artifact in the `grade/verification-metadata.xml`.

I also tried different ways mentioned in Wiki or docs or logs, but a combination of the following commands helped me generate it.
```
gradlew build

gradle --write-verification-metadata sha256 help

gradlew --write-verification-metadata sha256 qa --rerun-tasks

gradlew.bat clean
```
Clean also failed bcz of some lint(you can also try Invalidating cache) but After clean it generated the metadata.

I have tried in both Android Studio Terminal and Windows Cmd. 
> Make sure you have JAVA_HOME set with the correct version, I am using java 17.0.12 rn.
