### ISSUE TITLE
Upscaling on small images

### ISSUE THREAD

**Issue by bitboy85** [signalapp/Signal-Android#9424]
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

### Bug description
Small images are upscaled and thus looking blurry.

### Steps to reproduce
Select camera -> galerie and choose a small image like a 32x32 icon and send it.

**Actual result:** 
Image is upscaled and looks blurry

### Screenshots
![grafik](https://user-images.githubusercontent.com/6197580/75450252-bd92a380-596e-11ea-8709-bc2456a22cd7.png)

### Device info
**Device:** Samsung J5
**Android version:** 9
**Signal version:** 4.55.8

**Comment by greyson-signal** [comment]
We have certain minimum display sizes for images. This isn't unintended.

**Comment by iago-lito** [comment]
Out of curiosity, what is the rationale for the minimum display size?

**Comment by greyson-signal** [comment]
So people can see it. 

Once you get below a certain size, it gets difficult to decide how you want to render something. Right now we do the easy thing. Maybe the right thing is to switch to a different scaling mode (that doesn't smooth) below some size, but it's hard to say. There will always be problem cases.
