### ISSUE TITLE
Signal "updates" existing contacts phone type

### ISSUE THREAD

**Issue by nightflame2** [signalapp/Signal-Android#9431]
### Bug description
New users are reporting that when they install Signal it is modifying their contacts information.
Specifically "phone type"

### Steps to reproduce
Have an existing contact (who is a Signal user) on the phone with phone type "Work Mobile".

![before](https://user-images.githubusercontent.com/19812968/75524142-37756c00-5a05-11ea-8755-70699a9b0ee0.png)

Install Signal
Check contact - contact's phone type and it will now be set to "Other"

![after](https://user-images.githubusercontent.com/19812968/75524076-190f7080-5a05-11ea-90eb-4eaab629a789.png)

This is really confusing new users.
Whats actually happening is that Signal looks through the users existing contacts, and any which are Signal users it creates a new raw contact in the account Signal. These are all given the fixed phone number type of ContactsContract.CommonDataKinds.Phone.TYPE_OTHER.

When Android does Contact Aggregation it uses the phone type "other" from the Signal raw contact rather than the phone type from the original raw contact. (Note for some types such as "mobile" the aggregation seems to keep the existing type).

But to the average user who probably does not understand raw contacts and contact aggregation linked view this looks like Signal is over writing contact information. It would be better if when Signal creates its copy of the contacts if it copied the phone type rather than using "other" all the time.

**Comment by KnightAzul** [comment]
Hey I get exactly that problem, Signal changes my contacts! 
I was going to uninstall Signal as I didn't want apps messing around with my contact entries and changing fields.

Can this be fixed?

KnightAzul

**Comment by breversa** [comment]
In addition to Signal NOT changing the phone type for the contacts, would it be possible to display the (not updated ;-) ) phone type next/below the contact's name in the conversations list (and also the conversation thread).

My use case is the following :
My friend Bob has two phones (and hence two phone numbers) : a personal one, and a work one.

When I want to send him a message, I more often than not send to his work number (which I'm not supposed to do) instead of his personal number, since I can't readily tell which one it is unless I first open his information page.

**Comment by nightflame2** [comment]
Disappointingly this is still an issue.

A fix #9431 was submitted by the community nearly a year ago:

https://github.com/signalapp/Signal-Android/pull/9434

However this has not even been looked at by the project. I guess they are overwhelmed fixing other more important stuff. But does make you wonder if they have the resources to support a global messaging app, even with the community contributing :-(

**Comment by KnightAzul** [comment]
I can't believe it, almost 1 year and no fix or view/comment from the developers. Something a simple as this with the fix already having been provided by the community.

I would like to change to Signal, but stable and secure messaging is very important to me, and quick bug fixing forms a part of this. 

KnightAzul

**Comment by nightflame2** [comment]
I have done a bit more digging on this one and there are two compounding problems really.

1) As per the bug report, Signal simply puts "other" for all contacts it copies from your contacts (WhatsApp, Telegram etc copy the value thats in your contact).

2) Android contact aggregation is picking "other" over "work mobile".

I have submitted a fix for this #9431 for point 1) nearly a year ago, so don't hold your breath waiting for the Signal team to accept this Community fix. Kind of feel like I wasted my time. 

For point 2) why would Android contact aggregation take "other" in precedence over "work mobile"? After a bit of experimenting and then looking at the Android code, here's why:

In ContactsContract.CommonDataKinds.Phone each type has a numerical constant:

TYPE_HOME 1
TYPE_MOBILE 2
TYPE_WORK 3
TYPE_FAX_WORK 4
TYPE_FAX_HOME 5
TYPE_PAGER 6
TYPE_OTHER 7
TYPE_CALLBACK 8
TYPE_CAR 9
TYPE_COMPANY_MAIN 10
TYPE_ISDN 11
TYPE_MAIN 12
TYPE_OTHER_FAX 13
TYPE_RADIO 14
TYPE_TELEX 15
TYPE_TTY_TDD 16
TYPE_WORK_MOBILE 17
TYPE_WORK_PAGER 18
TYPE_ASSISTANT 19
TYPE_MMS 20

It turns out that Android's supposedly smart contact aggregation algorithm is not so smart! For phone type label it just uses the lowest value!

Other (TYPE_OTHER) is 7, and Work Mobile (TYPE_WORK_MOBILE) = 17 so Other gets displayed.

In fact if you plan to use Signal and want a meaningful phone label for your contacts you can only use labels with a value lower than 7 otherwise you will always get Other displayed:

So you need to use one of these:

TYPE_HOME 1
TYPE_MOBILE 2
TYPE_WORK 3
TYPE_FAX_WORK 4
TYPE_FAX_HOME 5
TYPE_PAGER 6
TYPE_OTHER 7

Unfortunately in 2021 FAX and PAGER are not that useful. Seems a strange choice of precedence to me.

With neither Signal or Android planning to fix these issues, we are stuck with trying workarounds.

1) Try to only use Home, Mobile, Work :-(

2) Another workaround is to unlink contacts in your Contacts App to stop Contact Aggregation - this cannot be done as a batch but has to be done contact by contact :-(

**Comment by KnightAzul** [comment]
Why doesn't Signal do what other messaging apps like WhatsApp do. When creating a new raw contact in the account Signal, just copy the phone number type from the main contact. Don't just lazy default it to ContactsContract.CommonDataKinds.Phone.TYPE_OTHER.

Seems pretty obvious to me, especially when the other messaging apps do it that way.

KnightAzul

**Comment by nightflame2** [comment]
> Why doesn't Signal do what other messaging apps like WhatsApp do. 

Turns out that open source is not that open!

**Comment by uok** [comment]
@nightflame2,  I also found this bug. Thanks for digging into contact aggregation, it is now clear why all signal friends show as "other" in system contacts. It's annoying because I don't know which number it is if person has more than one phone.

I'm using my own custom labels for phone numbers which work perfectly in Nextcloud and Android phonebook. But for signal users they are also "overwritten" by this bug. In vcard it looks like this

```
APHONE.X-ABLABEL:Mobile 1
APHONE.TEL;TYPE=HOME,CELL,PREF:12345
BPHONE.X-ABLABEL:Mobile 2
BPHONE.TEL;TYPE=WORK,CELL:67890
```

I will look into the workarounds and see if they help.
I hope your PR gets merged soon!

**Comment by nightflame2** [comment]
> Stale, Won't fix

???

Huh, yes this is still a very real problem.

A fix has been provided over a year ago:

https://github.com/signalapp/Signal-Android/pull/9434

And ignored, still waiting to be reviewed, merged who knows?

Not sure what sort of best practice Software Engineering this is, to wait until bugs are old then close with no fix!

**Comment by nightflame2** [comment]
Fix provided still not reviewed/merged:

https://github.com/signalapp/Signal-Android/pull/9434

**Comment by uok** [comment]
Thanks for merging the fix!

If I open an entry in Android contacts, it still shows "other"
Are there any additional steps required to force Signal to re-read the contact list and respect the custom labels?

**Comment by uok** [comment]
reinstallation did the trick, but it would be great if this works without
