### ISSUE TITLE
RSA security risk of apk's certificate

### ISSUE THREAD

**Issue by giupardeb** [signalapp/Signal-Android#9432]
Hi guys, I download the last apk from this link https://signal.org/android/apk/. I verified the certificates of apk with this command:

`keytool -list -printcert -jarfile Signal-website-universal-release-4.55.8.apk`

the output got a Warning of RSA:

```
Signer #1:
Signature:

Owner: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Issuer: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Serial number: 4bfbebba
Valid from: Tue May 25 17:24:42 CEST 2010 until: Tue May 16 17:24:42 CEST 2045
Certificate fingerprints:
	 MD5:  D9:0D:B3:64:E3:2F:A3:A7:BD:A4:C2:90:FB:65:E3:10
	 SHA1: 45:98:9D:C9:AD:87:28:C2:AA:9A:82:FA:55:50:3E:34:A8:87:93:74
	 SHA256: 29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 1024-bit RSA key (weak)
Version: 3


Warning:
The certificate uses a 1024-bit RSA key which is considered a security risk.
``` 

## UPDATE
P.S I think that is useful added in https://signal.org/android/apk/ the instructions to allow us to verify the fingerprint

**Comment by jeremy21212121** [comment]
I think it is safe to say this is a dupe of #9362 . See also [closed issue #6833](https://github.com/signalapp/Signal-Android/issues/6833).

Long story short, there is no[*] easy way to migrate an existing app to a new cert and not all devices support longer key lengths.

> [*] [APK Signature Scheme v3](https://source.android.com/security/apksigning/v3) adds the ability to migrate to a new cert while still supporting older devices.

> According to [android observatory](https://androidobservatory.org/stats), 64% of play store apps are signed with a 1024 bit RSA key.

NB - I'm neither an android dev nor affiliated with this project. Just passing through.

**Comment by giupardeb** [comment]
Okay, I understand... thank you.

**Comment by guimspace** [comment]
You may ignore the RSA warning. Instead, you should verify that the SHA256 part matches with the value in the website.
```
Certificate fingerprints:
	 ...
	 **SHA256: 29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26**
```
> you've verified that the signing certificate inside the APK matches the one that Signal expects you to see https://security.stackexchange.com/a/178939

For more on the subject, see  
- [How to verify SHA256 fingerprint of APK](https://security.stackexchange.com/questions/178936/how-to-verify-sha256-fingerprint-of-apk)
- [Request: Google Play signed download alternative](https://github.com/signalapp/Signal-Android/issues/127#issuecomment-13335689)

**Comment by mottla** [comment]
> You may ignore the RSA warning. Instead, you should verify that the SHA256 part matches with the value in the website.

This is not a professional advice. RSA knows why they decided to finally add this warning, after the crypto community is crying this out loud for years now.

> Okay, I understand... So can I trust of apk on site, right?

Technically speaking, no. If a weak Signature scheme is applied, neither integrity nor authenticity can be guaranteed

> Long story short, there is no[*] easy way to migrate an existing app to a new cert and not all devices support longer key lengths.

This was years before v3 was introduced. Mitigating to a more secure distribution mechanism was and still is manageable. Some argue this cant be done, since old devices then might not be able to run signal. This is a terrible argument (and I’m not even sure if its correct) considering the purpose and promise of signal. Security starts with the weakest link in a chain. 

> According to [android observatory](https://androidobservatory.org/stats), 64% of play store apps are signed with a 1024 bit RSA key.

Interesting and somehow scary, I must admit. The least thing you want is malicious software on your phone.

**Comment by giupardeb** [comment]
is not possible create two apk of signal with different certificates? The first one signed with certificate 1024-bit RSA(for old devices) and the second one with, for example, 4096-bit RSA (for new devices)
