### ISSUE TITLE
Never selected a PIN (I think) but asking for one on the new phone, no access to the account on the old one

### ISSUE THREAD

**Issue by KindHuman** [signalapp/Signal-Android#9435]
Hi,
I installed Signal on a new phone, and since no PIN was put on the old one it was working and unregistered the old one. For some reason, I uninstalled it on the new one, and now a PIN is asked. I tried some that perhaps I would use, but none worked and I have only one more try. I use Signal on computer too. Re-register the old phone is not possible since a PIN is asked now. I have a backup of the conversation of my old phone. I would like to use it on the new one now.
_Is there a way do edit the PIN from the computer?_
Does the use of Signal on computer prevent to renew the PIN on the phone?
Does put a tenth try block the use of Signal on the computer?
Is there a default Signal pin?
Is there anything I can do to be able to use it?
Is there a way do edit the PIN from the computer?
Thanks!

**Comment by jeremy21212121** [comment]
You will probably have better luck over at the [signal community forums](https://community.signalusers.org/). That is the place to go for support.

A quick search there turned up [this post](https://community.signalusers.org/t/pin-not-migrated-saved-properly/11996), which appears to be relevant to your questions. Hopefully that points you in the right direction!

So you are aware, I have nothing to do with this project. I'm just a random programmer passing through.

Best of luck!

**Comment by KindHuman** [comment]
Thanks, Jeremy, Done! 
https://community.signalusers.org/t/no-known-pin-but-asked-for-one-to-register-it-on-new-phone-only-computer-use-possible-for-now/12196
