### ISSUE TITLE
Cannot open Signal from the recents screen if it closed using the back hardware button

### ISSUE THREAD

**Issue by zmni** [signalapp/Signal-Android#9436]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### **Bug description**
Cannot open Signal from the recents screen if Signal is closed using the back hardware button.

### **Steps to reproduce**
- Open Signal app.
- Close Signal using back hardware button.
- Access recents screen, click on Signal.

**Actual result:** Signal does not open. A message shown: `Application is not available`.  
**Expected result:** Signal should open.

### **Screenshots**

![signal](https://user-images.githubusercontent.com/841523/75625145-db217080-5bed-11ea-8c34-fa35ff7e1dc6.png)
![signal](https://user-images.githubusercontent.com/841523/75625512-6bad8000-5bf1-11ea-8c26-33727927a0ec.gif)

### **Device info**

**Device:** `HMD Global TA-1053 (TA-1053_00WW)`  
**Android version:** `9 (00WW_6_19C, 00WW_6_19C)`  
**Signal version:** `4.55.8`

### **Link to debug log**

https://debuglogs.org/c79297754ea91bdf4dfe833b9991c09a98682cd387641ac3ee9da853ad41f8c5

**Comment by bme13** [comment]
Hi, this seems to be a duplicate of https://github.com/signalapp/Signal-Android/issues/9292.

**Comment by zmni** [comment]
My bad. Sorry for my limited english for searching with the wrong keywords. Closing this issue in favor of the linked issue.
