### ISSUE TITLE
Signal on Android may silently fail to alert user to new messages after receiving push notification

### ISSUE THREAD

**Issue by brianr2600** [signalapp/Signal-Android#9438]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If Signal is unable to make a background data connection, or unable to execute in the background, it will silently fail to notify the user of new messages until the app is brought into the foreground.

When the app is eventually opened, messages will arrive in rapid succession. This behavior creates the appearance that the timeliness of the signal service is unreliable, and is an obstacle for non-technical users who don't understand concepts like background execution and data saver.  

### Steps to reproduce
- On Android device A, enable "mobile data saver"
- Make sure Signal does not have unrestricted mobile data access
- Disable WiFi
- Close signal app
- Use power button to put device to sleep
- On device B, send a message to the number registered on device A

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- Message status will show only one checkmark on sender's device.
- Recipient's device will receive a push notification, but will not display any notification. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

If Signal has received a push notification, but cannot connect because data saver or a related feature prevents background data use, it should display a generic notification to entice the user to bring the application into the foreground so it can connect and retrieve messages.

### Device info

**Device:** Google Pixel XL
**Signal version:** 4.55.8

**Comment by brianr2600** [comment]
app/src/main/java/org/thoughtcrime/securesms/gcm/MessageRetriever.java around line 87 records this class of failure in the log, but does nothing to alert the user. 

`
          Log.w(TAG, "All strategies failed!" + logSuffix(startTime));
`

**Comment by greyson-signal** [comment]
There's multiple types of restricted access. Some phones won't deliver FCM messages *at all*, meaning there's literally nothing we can do. We have no idea that anything is happening at all.

The other type is that we're given the FCM message, but we don't have network access. In this case, we *could* show a message like "You may have new messages." And in fact, we used to! And turns out it's not a great idea. Because we don't know what *kind* of message it is. It could be a read receipt, or a delivery receipt, or something else invisible. And then people get very confused.

If you post a log, I could tell you which type of restriction you're falling under.

**Comment by brianr2600** [comment]
I'm referring to the case where signal is able to receive the FCM message, and can execute in the background, but cannot make a network connection. With data saver on newer android devices, it's a pretty common misconfiguration. Here's a debug log from my test device:

https://debuglogs.org/092c1aa46c3e9547ca7cfe8f5dfb864ac97a2a5bd19491813291552442f52dce

We discovered this problem on my daughter's Pixel with the latest stock android and data saver enabled. Everything was fine until she wandered away from WiFi. Adding "unrestricted mobile data" for Signal fixed the problem, but not something a non-technical user would be likely to figure out on their own.  

I realize UX is likely to be poor if the user is unable to fix the misconfiguration, but it's my position that a notification for uninteresting messages like reactions or receipts is preferable to no notification at all when real messages are waiting.

**Comment by brianr2600** [comment]
I'll concede that the old message "Unlock to view pending messages" was likely to confuse users, particularly if the pending message was a receipt or other "invisible" message. It would also fail to suggest that something is amiss with the device configuration. I would suggest something along the lines of "New Message Notifications May Be Delayed / Retrieving messages in the background failed"

Given that this is largely a UX issue, I've created a discussion thread at https://community.signalusers.org/t/better-handling-of-common-push-network-issues/12234/3 to see if some consensus can be built before I work up a patch. I've also invited folks to discuss the other case, where FCM messages are delayed or discarded.

**Comment by greyson-signal** [comment]
Yeah, I mean it's one of those things where the work is trivial -- just need to post a notification when a specific strategy fails. It's just that we used to do it, and people really didn't like it. That's why we took it out :)

It looks like we may be able to detect specifically when battery save mode is enabled ([link](https://stackoverflow.com/a/25018953)) and when data saver mode is enabled ([link](https://developer.android.com/training/basics/network-ops/data-saver)), but I'd want to do more testing to make sure that the APIs are working as expected. 

There may be a world then where we could give more guidance if we fail to download and see they're in power saver/data saver mode or something. But even then, you have to be careful, because we don't know if the message is "invisible" or not, so it can still be confusing to non-technical users.

**Comment by brianr2600** [comment]
I agree with the idea of using the power manager and connectivity manager APIs to detect those two common problems and offering a link directly to related instructions or even offering a place where the user can tap to startActivity() the related settings page.

I maintain that notifying the user of device or network conditions which might cause incoming messages to be delayed is categorically different from displaying an alert implying that new messages are "pending" or available, even if the underlying mechanism for discovering the problem is similar. Notifying the user is particularly important in the case of problems beyond the user's device, like a WiFi or mobile network where the signal servers are blocked or unreachable. Even if the app is open, Signal still seems to fail silently for these cases and the user doesn't find out they've been unable to receive messages until they connect to more usable data service and the stale messages start rolling in.

**Comment by brianr2600** [comment]
We saw this problem again on my daughter's phone last week. In that instance, battery saver was off, and unrestricted data was enabled for Signal. Sent messages  showed a single check on the sender's phone. Opening the app resulted in a bunch of delayed messages being delivered in rapid succession. This time, upon opening the app I noted that the registration pin prompt was being shown and realized the PIN prompt was a common element with the very first time we saw this problem. 

The PIN prompt wasn't showing on the phone used to create the debug log I posted above.  I'll make a point to grab a debug log if this happens again.

**Comment by bozicm** [comment]
I have the same issue with two of my friends that have recently installed the app. I guess they also didn't set the app as primary SMS app.

**Comment by bozicm** [comment]
> Yeah, I mean it's one of those things where the work is trivial -- just need to post a notification when a specific strategy fails. It's just that we used to do it, and people really didn't like it. That's why we took it out :)
> 
> It looks like we may be able to detect specifically when battery save mode is enabled ([link](https://stackoverflow.com/a/25018953)) and when data saver mode is enabled ([link](https://developer.android.com/training/basics/network-ops/data-saver)), but I'd want to do more testing to make sure that the APIs are working as expected.
> 
> There may be a world then where we could give more guidance if we fail to download and see they're in power saver/data saver mode or something. But even then, you have to be careful, because we don't know if the message is "invisible" or not, so it can still be confusing to non-technical users.

What about expanding the [battery troubleshooting docs](https://support.signal.org/hc/en-us/articles/360027913252-Troubleshoot-receiving-messages) something like https://dontkillmyapp.com website, or at least referencing it?
