### ISSUE TITLE
Chat icon click

### ISSUE THREAD

**Issue by stijnbollen** [signalapp/Signal-Android#9441]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This might a feature request or a discussion topic, I don't know
----------------------------------------

### Bug description

On Android, on the screen listing all chats, and groups, when you click on a profile image of a personal chat it opens the users profile. I'd expect a similar behaviour when clicking on the icon of a group chat. Right now in 4.55.8, this does nothing, except highlight the image when clicking. It should either open the chat settings or the group chat itself.

### Steps to reproduce
Click on the image of a group chat.

**Actual result:** Group chat icon is highlighted, apart from this, it does nothing.
**Expected result:** Open either the group chat or the group chat settings.

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.55.8

**Comment by u32i64** [comment]
This has been fixed in fd2a464, which is in version `4.56.4`, which is currently in beta. Specifically, Signal shows conversation preferences when an avatar tapped.
