### ISSUE TITLE
anble to bypass pin

### ISSUE THREAD

**Issue by alexparker70** [signalapp/Signal-Android#9443]
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/61779719/75865046-32e4f500-5e03-11ea-9504-c70670667f09.gif)

- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open the Signal App on LineageOS, I am presented with my pin unlock screen. However, if I just poke anywhere on the screen outside of that dialogue box, it completely bypasses the pin check procedure.

### Steps to reproduce
- open signal app
- click outside dialogue box for entering pin
- access messages
- profit

**Actual result:** able to read/write messages without entering pin
**Expected result:** should not be able to read/write messages without entering pin

### Device info

**Device:**  Huawei Nexus 6P
**Android version:** 8.1.0
**Signal version:** 4.55.8

**Comment by pgerber** [comment]
This PIN is there so no one else can register with Signal using your phone number. See [these support page](https://support.signal.org/hc/en-us/articles/360007059792-Registration-Lock). If you want to have the application locked, have a look at [the Screen Lock support page](https://support.signal.org/hc/en-us/articles/360007059572).

BTW, at least in the beta version this screen has been redesigned and the intention should be clearer now; it's just there to help you memorize the pin:

![signal-attachment-2020-03-04-124301](https://user-images.githubusercontent.com/11895833/75876484-b0adfe00-5e0d-11ea-9da4-5b41124403f3.png)

**Comment by Cerberus0** [comment]
I think this issue is a duplicate of https://github.com/signalapp/Signal-Android/issues/8699. In that thread, one of Signal's developers has said:

>The "registration lock" pin is separate from the "lock screen" in. The registration lock doesn't block your day-to-day usage of Signal -- it's only meant to be required during registration to prevent someone else registering your same number. The pop-ups are simply reminders to help you remember you PIN.
>
>The "lock screen" can be enabled independently in Settings > Privacy, and that will have the behavior I think you're looking for.

**Comment by alexparker70** [comment]
thanks! I feel like an idiot but that explains it. :)
