### ISSUE TITLE
Unable to select text within message

### ISSUE THREAD

**Issue by cruxcoder** [signalapp/Signal-Android#9444]
### Bug description
Can no longer select / highlight text within a message, I think since reactions? were introduced.  One can only copy entire message. Previously one could select / highlight individual portions of a message for copying etc, just as you normally can in android within most apps.

### Steps to reproduce
Attempt to highlight text in message via press

**Actual result:** 
Reaction gui and top message gui pop up

**Expected result:**
Some facility to select / highlight text within the message itself, not just copy entire message only.

### Device info
**Device:** HTC 10 Lineage OS
**Android version:** Nougat
**Signal version:** 4.55.8 (latest)

**Comment by greyson-signal** [comment]
I don't think we've had message sub-text-selection for quite some time. Kinda just a consequence of how long-press enters a different mode. Most messaging apps work this way.
