### ISSUE TITLE
layout issue - forwarding voice notes with additional text

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#9445]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
forwarding a voice note with additional text, delivery/read indicator and date aren't right aligned in message bubble

### Steps to reproduce
- forwarding a voice note
- write additional (long) text
- send the voice note with text

**Actual result:**
delivery/read indicator and date isn't right aligned in message bubbles on sender's side
**Expected result:** 
delivery/read indicator and date is right aligned in message bubbles on sender's side

### Screenshots
![IMG_20200304_124750](https://user-images.githubusercontent.com/49990901/75897867-87a36280-5e39-11ea-9961-14d250e226d7.jpg)

### Device info
**Signal version:** 4.55.8 and 4.56.4 beta

**Comment by frankvollebregt** [comment]
I checked into this issue, and found a solution. I'll push it and create a pull request by monday: Since I'm a first-time contributor and just applied for the contributor license, I cannot push to the repository yet..

This is how it looks in the resolved version.
![image](https://user-images.githubusercontent.com/23523399/76116892-07246380-5feb-11ea-98ee-2f8e469f40e0.png)

**Comment by Sgn-32** [comment]
Seems that the additional voice message duration has "fixed it" partially.
But still an issue in 4.77.3.

![signal-2020-11-16-191451](https://user-images.githubusercontent.com/49990901/99291651-6f953700-2840-11eb-90a1-0eb8ea412018.jpg)

**Comment by Sgn-32** [comment]
Voice message and additional text are splitted in two message bubbles.
