### ISSUE TITLE
Actions on marked message do nothing

### ISSUE THREAD

**Issue by patterchon** [signalapp/Signal-Android#9450]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I select a message in a chat by tapping on it long, the top menu and reactions menu appears. When I choose any action from the top menu - e.g. info, delete, copy, reply, forward ... - the menu dissapears and nothing happens. (The message itself is not selected anymore)

### Steps to reproduce
- Mark message in chat
- Choose an action from the top menu 

**Actual result:** Menu closes, message is not marked anymore.

**Expected result:** There should be an information when I click on info; there should be a dialog to whom I like to forward the message; or the message should be deleted when I click on delete etc.

### Device info
**Device:** Nokia 8.1 (TA-1119)
**Android version:** 10 (incl. security updates 1.02.2020)
**Signal version:** 4.56.4

### Link to debug log
https://debuglogs.org/f6cdc9a5a1f312de6d3acbacc43ba7bd3059b576164ac6852223ac15c49d1aca

**Comment by philipreimer** [comment]
I have the same problem.
I think it started when reactions were introduced.
Nokia 8.1
Android 10
Signal 4.56.4

**Comment by toreanderson** [comment]
Same problem here. When long-pressing on an individual message in a thread, both the reactions pop-up and the action bar show up, as shown in the screenshot below.

However, it would appear that any finger tap outside of the reactions pop-up is interpreted as a command to dismiss the reactions pop-up, *even though* the finger tap is done on an icon inside the action bar (such as info, delete, forward etc.). Unfortunately, that tap also dismisses the action bar and de-selects the message.

Occasionally it works, though. Not exactly sure what causes it to work, however I've found that quickly double-tapping the icons in the action bar increases my chance of of performing the action I want.

![signal-attachment-2020-03-21-115102_002](https://user-images.githubusercontent.com/4557060/77224947-bbd18f80-6b6a-11ea-8bd9-63254a2c605e.png)

**Comment by alex-signal** [comment]
Hey @toreanderson, could you let me know which Android device you're experiencing this issue on?

**Comment by toreanderson** [comment]
It's a Nokia (HMD Global) 8.1 running Android 10. Note that is an Android One device, so it is pretty much stock Android with no vendor modifications.

**Comment by alex-signal** [comment]
@toreanderson Thanks! I'm just starting to see a pattern here :)

**Comment by philipreimer** [comment]
@toreanderson the double-tap (rule #2) workaround seems to work for me, too.

**Comment by shining-cat** [comment]
exact same problem here
thank's to @toreanderson for the working double-tap workaround! 

**Device info**
Device: Nokia 8.1
Android version: Android 10 / Android security patch : 1 February 2020 / Build : 00WW_4_15B_SP05
Signal version: 4.57.2

### Link to debug log
https://debuglogs.org/56f2c2ebb92738df25d9e601dbfff288530219724d1393ac872f918731038d3a

**Comment by huaracheguarache** [comment]
I'm having the same issue on my Nokia 8.1.

Android version: 10 
Security patch: 1 March 2020
Build number: 00WW_4_30B
Signal version: 4.58.5

**Comment by philipreimer** [comment]
The issue still exists in Signal 4.59.9

**Comment by philipreimer** [comment]
Any update? The issue still exists in Signal 4.64.4

**Comment by char32** [comment]
Just wanted to confirm: Same issue here with a Nokia (HMD Global) 8.1 running Android 10 (seems to be related to that combination).
Signal Version: 4.67.1
Android build number: 00WW_4_30B_SP04 (01. July 2020)

**Comment by philipreimer** [comment]
This seems to have been fixed. At least in my case, using Signal version 4.71.5, the "double-tap workaround" is not necessary any more.
