### ISSUE TITLE
Update profile full name megaphone does not use gender neutral icon

### ISSUE THREAD

**Issue by TeffenEllis** [signalapp/Signal-Android#9456]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The addition of full name support comes with a megaphone informing the user they may add a last name to their profile. This megaphone uses to a bearded person regardless of the user's gender. Seeing as we don't collect that information, it might be better to default to a gender neutral person.

Commit introducing the behavior:

3ea1492d672409d6018568b2f8b81d886ced1448

Bearded person asset:

https://github.com/signalapp/Signal-Android/blob/master/app/src/main/res/drawable-mdpi/profile_megaphone.png

### Steps to reproduce
- Open Signal
- Trigger full name megaphone
- Observe

**Comment by Meteor0id** [comment]
Conchita had a beard tho. Can't assume gender based on a beard. Just saying.

**Comment by TeffenEllis** [comment]
@Meteor0id agreed. We can't assume gender with a beard, but we can probably make a good guess that the folks who enjoy Signal don't all have beards. We wouldn't want to [repeat history](https://youtu.be/2q9ugg9i0cQ) and offend anyone here :wink:
