### ISSUE TITLE
Group chats look very similar to private chats

### ISSUE THREAD

**Issue by k3anton** [signalapp/Signal-Android#9458]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a user has engaged in both private and group chats, it is easy to mistakenly write a private message in a group chat because they look very much a like. This can cause involuntary privacy breaches and can have serious consequences depending on the users threat model.

I have only observed users in my surrounding, both admitting to sending the message in the wrong chat but also being "caught" doing so. 

I think this can be usability tested or investigated through a survey to see the magnitude of the problem. 

**Actual result:** N/A
**Expected result:** 

### Device info

**Device:** Pixel 3a XL
**Android version:** 10
**Signal version:** 4.56.4

**Comment by Genis-Sage** [comment]
hey @k3anton 

i understand your intent, and that it can be annoying
it happened once for me in the past... sadly

but i still guess, that the topic is not really a bug, but more a design discussion

would you be so nice and serach / open a thread in the forum https://community.signalusers.org/ ?

**Comment by k3anton** [comment]
> hey @k3anton
> 
> i understand your intent, and that it can be annoying
> it happened once for me in the past... sadly
> 
> but i still guess, that the topic is not really a bug, but more a design discussion
> 
> would you be so nice and serach / open a thread in the forum https://community.signalusers.org/ ?

Hi @Genis-Sage ,

OK, I will do that.
