### ISSUE TITLE
SSL: Self-signed certificate in Certificate Chain - textsecure-service.whispersystems.org

### ISSUE THREAD

**Issue by TravisDean** [signalapp/Signal-Android#9460]
Having the app installed causes my IDS to generate alerts about a self-signed cert for https://textsecure-service.whispersystems.org/ .

![image](https://user-images.githubusercontent.com/3077602/76185258-38489380-61a5-11ea-81e9-8f0e575fe705.png)

I know that this isn't a problem in terms of being an actual vulnerability (assuming that additional verification is done in app..? Didn't check the code, so I'm not sure what that URL actually serves other than a login page). It does seem unprofessional, especially considering that other publicly accessible interfaces to Signal choose to get their certificates signed by a known root CA.

Is there a reason for this?

I did find [this](https://github.com/signalapp/Signal-Desktop/issues/3481) page about a similar issue, but since this comes from my phone and it's a different URL, I thought it worthwhile to open a new issue.

**Comment by u32i64** [comment]
> Is there a reason for this?

See Moxie's [Your app shouldn't suffer SSL's problems](https://moxie.org/blog/authenticity-is-broken-in-ssl-but-your-app-ha/) blog post.

**Comment by Cerberus0** [comment]
This looks like a duplicate of https://github.com/signalapp/Signal-Android/issues/5100.

**Comment by TravisDean** [comment]
Thank you both, I learned something today.

One last question: What's the point of the login page at https://textsecure-service.whispersystems.org/v1/messages ? I'm assuming it's for internal debug?
