### ISSUE TITLE
Can't find the location of crypto libraries

### ISSUE THREAD

**Issue by YValeri** [signalapp/Signal-Android#9467]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to check the code behind the crypto used in the app, the key generation for instance, but i can't find it anywhere in the repository.

### Steps to reproduce
- Go to app/src/main/java/org/thoughtcrime/securesms/crypto
- Go into any file, for instance "IdentityKeyUtils.java"
- One of the import is "org.whispersystems.libsignal.ecc.Curve", but there nothing like that is the whole repository

**Actual result:** I am unable to find any protocol related file in the repository, i found the corresponding file in the libsignal-protocol-java, but then i cannot find the import "org.whispersystems.curve25519.Curve25519". From what i undertstand after checking the files and gradle, it's considered to be a library, but it isn't in my own libraries not the one in docker, so I don't know where to find the complete crypto files.
**Expected result:** We should see the code directly in the repository, and not have to search in other repositories if they are there and gathered when building.

### Device info

**Device:** HUawei Mate 9
**Android version:** 9.1.0
**Signal version:** 4.55.8

**Comment by u32i64** [comment]
> i cannot find the import "org.whispersystems.curve25519.Curve25519"

https://github.com/signalapp/curve25519-java/blob/70fae57d6dccff7e78a46203c534314b07dfdd98/common/src/main/java/org/whispersystems/curve25519/Curve25519.java#L15

**Comment by YValeri** [comment]
> 
> 
> > i cannot find the import "org.whispersystems.curve25519.Curve25519"
> 
> https://github.com/signalapp/curve25519-java/blob/70fae57d6dccff7e78a46203c534314b07dfdd98/common/src/main/java/org/whispersystems/curve25519/Curve25519.java#L15

Thanks for the link, though i still don't see how this repository is pulled from the the Signal-Android one

**Comment by alan-signal** [comment]
Please use the community forum for discussion https://community.signalusers.org/
