### ISSUE TITLE
unencrypted SMS warning loo long

### ISSUE THREAD

**Issue by rubo77** [signalapp/Signal-Android#9469]
If you send a message to a contact without signal the hint-message in the textarea is too long (at leas in german) it should contain at least the word "SMS" without having to turn the device 

here is a screenshot

![20200312_111121](https://user-images.githubusercontent.com/1591563/76511030-d1e89d00-6452-11ea-988d-89eee0fbaeee.jpg)

maybe set it to "SMS unverschlüsselt senden" instead

**Comment by Genis-Sage** [comment]
hey @rubo77 
for the, the warning is completely fine on my Nokia 7 Plus
but this could also be because i'm using it with two sim cards

what phone are you using?
what Android version?
what Signal version?

**Comment by rubo77** [comment]
I use a Samsung Galaxy a6 with Android 9, latet Signal Version.

Maybe because my screen ratio is different than yours.

I can only see 

    Unverschlüsselte S...
