### ISSUE TITLE
Contact Chips on inbox dont open Android Native Contacts

### ISSUE THREAD

**Issue by mikeymop** [signalapp/Signal-Android#9470]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Traditionally, tapping a contact chip in Inbox view would open a Contacts card from the Contacts app.
When tapping a contact chip in a conversation, it would open the Signal Contact card.

Now, no matter what, tapping on either chip opens the Signal Contact card

### Steps to reproduce
- Tap on a contact chip on inbox
- Tap on a contact chip in conversation view

**Actual result:** 

In both instances, the Signal Contact card will appear. This is not as useful as the Android Native Contact card as it does not include other saved fields that a contact may have (such option to call via mobile network or the contact's address/email)

**Expected result:** 

Tapping on the contact chip in Inbox opens the Android Native Contact card.
Tapping on the contact chip in converstaion view opens the Signal Contact card.

### Device info

**Device:** Essential PH-1
**Android version:** 10
**Signal version:** 4.56.4

**Comment by Genis-Sage** [comment]
hey @mikeymop 

i see the same behaviour, but as far as i understand the commits to the code of the last two or three versions, that behaviour change was intended, so that from conversation overview, the behaviour is the same for all conversations

if you are in a 1on1 conversation, you can still longpress on the name to open the native contact card

if you would like to discuss about the behaviour change, the forum https://community.signalusers.org/ is a better place

**Comment by mikeymop** [comment]
> if you are in a 1on1 conversation, you can still longpress on the name to open the native contact card

Considering the change is intended, and that the long press option is there I will proceed to use that.

Thank you. I apologise for the erroneous issue report.

**Comment by Lion-box** [comment]
@mikeymop 
I'd suggest to  Close  this issue.
(use the red button in comment section)
