### ISSUE TITLE
Sticker suggestion not appearing when associated emoji entered in chat

### ISSUE THREAD

**Issue by sig432** [signalapp/Signal-Android#9471]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For some stickers within a given sticker pack, if you enter a chat and type the emoji associated with that sticker, that sticker will not appear as a suggested sticker.

### Steps to reproduce
- Install Dog sticker pack (https://signal.art/addstickers/#pack_id=06457ac861ba340b1ba2195cb53beb36&pack_key=733d7b3ea26e5c3dd13079d24f3a16a7322ff349499e6bdf83486579f0348b81)
- Note that the airplane emoji is associated with one of the stickers in this pack
- Open a chat
- Use keyboard to enter airplane emoji

**Actual result:** The dog sticker associated with the airplane emoji doesn't appear as a suggestion
**Expected result:** The dog sticker associated with the airplane emoji appears as a suggestion

### Screenshots

![Screenshot_20200313-115927](https://user-images.githubusercontent.com/62155993/76652711-6111b580-6524-11ea-8156-b20a849b064b.png)
![Screenshot_20200313-120524](https://user-images.githubusercontent.com/62155993/76653099-44c24880-6525-11ea-92ae-8fd14ceeeb34.png)

### Device info

**Device:** Essential PH-1
**Android version:** 10
**Signal version:** 4.56.4

### Link to debug log
https://debuglogs.org/b834b5f87d02c4967085387b11a9e0da4685963e746f12e9abb995acf66eb400

### Additional examples
- Download Lovers sticker pack (https://signal.art/addstickers/#pack_id=29a2d659f61e1bc0d877ef715e84e9eb&pack_key=c818f967e1467c6b7b9c1d4fe2f4c608b99b3ed51adba5a0406d29c4a27cb824)
- Note stickers associated with "couple" emoji and "couple kissing" emoji
- Try entering those emoji in a chat to get suggestions
- Note lack of sticker suggestions

![Screenshot_20200313-115935](https://user-images.githubusercontent.com/62155993/76652720-67079680-6524-11ea-9abf-dca822393639.png)
![Screenshot_20200313-115942](https://user-images.githubusercontent.com/62155993/76652728-6a9b1d80-6524-11ea-87e6-2c5358d71f1e.png)
![Screenshot_20200313-120622](https://user-images.githubusercontent.com/62155993/76653266-9c60b400-6525-11ea-9a9e-92dab68698ad.png)
![Screenshot_20200313-120631](https://user-images.githubusercontent.com/62155993/76653282-a2ef2b80-6525-11ea-97d6-ab0875ad9a38.png)

**Comment by greyson-signal** [comment]
I've fixed the issues with the kissing faces, but the airplane is interesting. It seems that the airplane emoji for that sticker pack is formatted slightly differently than any of the airplane emoji in our apps.

The sticker is tagged with:
https://apps.timwhitlock.info/unicode/inspect?s=%E2%9C%88

But we use:
https://apps.timwhitlock.info/unicode/inspect?s=%E2%9C%88%EF%B8%8F

Note the extra variation selector on our version. It'd obviously be easy to special-case this or something, but I'm interested in looking into it more to solve it more generically.

**Comment by sig432** [comment]
Interesting! Thank you very much for those fixes :)

Maybe having more examples would help with coming up with a generic solution? Here are a couple more:

### Example 1:
Screenshot:
![Screenshot_20200317-203128](https://user-images.githubusercontent.com/62155993/76922946-4f673f80-688f-11ea-8c2d-6257f4af2ed8.png)
Sticker pack: https://signalstickers.com/pack/bad7105b3b3a2c20e841a9d7275b3aca
Emoji that should generate suggestion but doesn't: Running man


### Example 2
Screenshot:
![Screenshot_20200317-203059](https://user-images.githubusercontent.com/62155993/76922975-66a62d00-688f-11ea-8a16-ef0d90aa9fe4.png)
Sticker pack: https://signalstickers.com/pack/b49aa220d21668d32690fd4a6db4768f
Emoji that should generate suggestion but doesn't: Red heart

(let me know if more info is desired for these)

**Comment by sig432** [comment]
The "red heart" emoji definitely has something systemic going on. I imagine it's similar to the airplane example where there are slight variations of the red heart emoji. Two more red heart emoji examples:

Screenshot:
![Screenshot_20200319-071635](https://user-images.githubusercontent.com/62155993/77077593-aa458780-69b2-11ea-93df-a38366de82aa.png)
Sticker pack: https://signal.art/addstickers/#pack_id=12ec591a53251dcf11e489d095ce402b&pack_key=581d44b25b365b9a2cb88dd6c07e1aa71d57ad9ed9b4f26a8e458cebf5fcd374

Screenshot:
![Screenshot_20200319-072037](https://user-images.githubusercontent.com/62155993/77077572-a1ed4c80-69b2-11ea-8671-564095eda154.png)
Sticker pack: https://signal.art/addstickers/#pack_id=1946f4712073fadcf52b031249131e3d&pack_key=71585d0a3b535fa9e94751c568c128bb497de91b1205a6637d220d4555cb33a8

I also tried with the other red heart emoji in Signal app (the one in the "sports" section next to the club, diamond, and spade emoji) just to see if they would appear. They don't appear with that one either. Though just to be clear I don't think they're intended to appear with the sports one because it looks slightly different and is related to playing cards rather than the red heart in the "smiley face" section with all the other colored hearts.

**Comment by adotey** [comment]
This is nearly 100% fixed now (thank you very much), but one of the examples I mentioned previously still repros (the red heart emoji still doesn't suggest the cat sticker):

Image: https://user-images.githubusercontent.com/62155993/76922975-66a62d00-688f-11ea-8a16-ef0d90aa9fe4.png

Sticker pack: https://signal.art/addstickers/#pack_id=b49aa220d21668d32690fd4a6db4768f&pack_key=8cd5324688b3b7e9d93d20c9c77a9a9b4157e934c96b8c7825de513be49a05b1

Emoji that should generate suggestion but doesn't: Red heart

Using Signal 4.59.9

**Comment by sig432** [comment]
This is nearly 100% fixed now (thank you very much), but one of the examples I mentioned previously still repros (the red heart emoji still doesn't suggest the cat sticker):

Image: https://user-images.githubusercontent.com/62155993/76922975-66a62d00-688f-11ea-8a16-ef0d90aa9fe4.png

Sticker pack: https://signal.art/addstickers/#pack_id=b49aa220d21668d32690fd4a6db4768f&pack_key=8cd5324688b3b7e9d93d20c9c77a9a9b4157e934c96b8c7825de513be49a05b1

Emoji that should generate suggestion but doesn't: Red heart

Using Signal 4.59.9
