### ISSUE TITLE
Remind Me Never

### ISSUE THREAD

**Issue by DaveJarvis** [signalapp/Signal-Android#9475]
When opening Signal, it has started reminding me to enter my name or some such.

The options on the dialog prompt me to enter my name now or remind me later.

I would like a "remind me never" option.

Is there a way to make the reminder go away? If not, I'd like to request a feature whereby I can dismiss that dialog (or any pesky dialog) with a "do not remind me again" option.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
