### ISSUE TITLE
Enabling video on caller does not enable speakerphone, accepting video call does

### ISSUE THREAD

**Issue by bentolor** [signalapp/Signal-Android#9476]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On initiating a video call and local video (without any attached audio device like headset) the external speaker / speakerphone is not automatically enabled. I'm pretty sure that this was the behavior a few versions age.

More confusing: On receiving a video call and enabling local video, speakerphone is automatically enabled.

I do not anticipate a rationale to not enable speakerphone on enabling camera, except with attached headphones/external audio device.

### Steps to reproduce
- Select contact
- trigger video call by enabling local video
- after successful connection: No audio.

On receiver side
- accept an incoming video call
- enable local video
- speakerphone is immediately enabled, too

**Expected result:** 
If no external audio headset is attached, enabling video should always enable speakerphone.

### Device info
**Device:** OnePlus 3 T
**Android version:** 9 / LineageOS 16.0
**Signal version:** 4.56.4

**Comment by Sgn-32** [comment]
Should be solved with the new calling UI from 4.60.

**Comment by bentolor** [comment]
Can confirm @Sgn-32 : This issue seems to be solved in the new UI!
