### ISSUE TITLE
Quoted reply sent to incorrect conversation

### ISSUE THREAD

**Issue by jonpavelich** [signalapp/Signal-Android#9478]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Quoted replies (left as drafts) are incorrectly attached to different conversations when sharing to Signal from another app.

### Steps to reproduce

1. Quote a message, leave as draft and leave the app
2. Share text or image to another conversation from an external app (like gallery)
3. Type any message you want and send the message

**Actual result:** The quoted reply is included, even though the original message does not exist in that conversation. When sharing a photo the quote isn't visible until sent, when sharing text the quote is visible and can be removed. The quoted message reveals the quoted user's phone number and the beginning of their message to the recipient.

**Expected result:** The message should not have a quoted reply attached to it.

_(Edit: completed the steps, thanks @RaghavRao)_

#### My Device
![local-end](https://user-images.githubusercontent.com/1972632/76694136-4460a500-662c-11ea-920b-bef5964d5876.png)

#### Other Device
![remote-end](https://user-images.githubusercontent.com/1972632/76694141-5c382900-662c-11ea-8a73-bf7a133d484a.png)

### Device info

**Device:** Samsung S8
**Android version:** 9.0
**Signal version:** 4.57.1

### Link to debug log

https://debuglogs.org/29e62540ef8d5436cd583f558d3ad243706e8aed0483429eb3e9a0a5ef1069fe

### Notes
This behaviour appears to be somewhat similar to #7935 (different steps, same result).

**Comment by RaghavRao** [comment]
I am able to reproduce this with the following steps:

1. Quote a message, leave as draft and leave the app
2. Share text or image to another conversation from an external app (like gallery)
3. The quote is included without the option to remove it, the message can be edited to whatever you want.

**Comment by jonpavelich** [comment]
I am also able to reproduce the issue using the steps @RaghavRao described. I sent photos when this happened originally and I've confirmed choosing photos from within Signal does not reproduce the issue.

I've updated the issue description to include these steps.

**Comment by alan-signal** [comment]
Thanks, will be fixed in 4.58
