### ISSUE TITLE
Share same photos with several contacts at once

### ISSUE THREAD

**Issue by epawlowska** [signalapp/Signal-Android#9483]
Could you please add a way to easily share photos with several contacts as we can do it in WhatsApp? This stops me from using Signal daily. The scenario on Android would be:
1. Select photos on your phone e.g. from Google Photos gallery.
2. Click option to share
3. Choose Signal app
4. Select contacts (Right now I can select only 1 contact, I would like to have a way to select more contacts, and send the same set of photos with the same descriptions to several people at once, as I can do it in WhatsApp or Messenger)
5. Add description and send.

**Comment by greyson-signal** [comment]
Hi there, we only use Github for bug tracking, not feature request. You can discuss feature request on [the forum](https://community.signalusers.org/). Thanks!
