### ISSUE TITLE
Registration lock reminder not accepting PIN shorter than 6-digit

### ISSUE THREAD

**Issue by rabner** [signalapp/Signal-Android#9484]
### Bug description
Registration lock reminder not accepting PIN shorter than 6-digits that I could set just few hours earlier.

**Actual result:** I was migrating to new phone and I've stetup 4-digit Registration PIN. Now it seems application not accepting PIN shorter than 6-digit. I cannot close "Verify your Signal PIN" reminder. The same behaviour going through Settings > Privacy > Signal PIN. Don't remember on whitch device I've set this PIN up.

**Expected result:** User should be able to use PIN he set up.

### Device info

**Device:** Pixel 3a
**Android version:** GrapheneOS 10
**Signal version:** 4.56.4 (web download apk)

**Comment by alan-signal** [comment]
Thanks for the report, it has now been fixed in 4.57.2
