### ISSUE TITLE
Signal doesn't show up for wifi-only tablet in Play store, but is installable there

### ISSUE THREAD

**Issue by hzulla** [signalapp/Signal-Android#9486]
Hi there,

to get an 80yr old senior citizen in my family ready for her Corona lockdown, I bought an Android tablet for video calls and wanted to install Signal on it.

To clarify, unlike previous similar issues in github, I did not want to install Signal on a tablet as a secondary installation and companion device to the phone. This is a deliberate attempt to use the landline number as Signal's user identifier for a person who won't be able to leave her home for the coming weeks or months.

The app did not show in the Play store. Sideloading the APK worked and setup was easy, linking the landline phone number to the Signal app worked by using the voice call feature for verification number. The Corona quarantinee in my family can now do video calls with her grandkids.

Please make this easier.

- allow installation on devices without a SIM slot through the Play store
- do not try to send an SMS when there is no SIM slot, but only offer the voice call verification instead
- do not offer to be the default SMS app when there is no SIM slot

Thank you so much.

**Comment by u32i64** [comment]
> - do not try to send an SMS when there is no SIM slot, but only offer the voice call verification instead

This point doesn't make sense to me. You could totally be registering with a phone number you got online, or that is on a SIM that's in a different device.

**Comment by hzulla** [comment]
> You could totally be registering with a phone number you got online, or that is on a SIM that's in a different device.

True, I'm taking that suggestion back.

**Comment by Genis-Sage** [comment]
hey @hzulla 
i totally get your point here in terms of the social aspects of your request

but i guess, it would be better to got to https://community.signalusers.org/ to discuss the idea,
since the Signallapp android repositoy here should only be used for bug reports, not feature or design requests

**Comment by palto42** [comment]
Hi @hzulla
I have excatly the same issue / use case.
To hopefully get this moving I just posted a comment on https://community.signalusers.org/t/android-tablet-support/5590

**Comment by hzulla** [comment]
> since the Signallapp android repositoy here should only be used for bug reports

Thanks. The app offers all features to be installed on a device without a SIM slot, but it was chosen to distribute it with a Manifest that excludes these devices. I'd argue that this is a bug, not just a feature request.

**Comment by alan-signal** [comment]
It's not a bug. This is intentional as the app is not optimized for tablets.
