### ISSUE TITLE
[Video Call] Screen aspect ratio shown to recipient not the same as in sender selfie picture

### ISSUE THREAD

**Issue by GenosseFlosse** [signalapp/Signal-Android#9487]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video aspect ratio on recipients screen doesn't match the video aspect ratio in selfie picture. It is cropped in some way. In my case the width is smaller than in the selfie picture.

### Steps to reproduce
- start video call
- compare video shown on recipients phone with picture in small selfie-picture

**Actual result:** Aspect ratios do not match, part of video visible in selfie picture not visible on recipients screen.
**Expected result:** Video shown to the recipient is an exact match of video shown in selfie picture.

### Screenshots

![signal-2020-03-20-144548](https://user-images.githubusercontent.com/59205524/77169867-7f465b00-6aba-11ea-99a3-33878f1a86ce.png)
![signal-attachment-2020-03-20-144702](https://user-images.githubusercontent.com/59205524/77169869-80778800-6aba-11ea-8cfb-e3932922499e.jpeg)

### Device info

1st Device:
**Device:** Pocophone F1
**Android version:** 10
**Signal version:** 4.57.1

2nd Device
**Device:** iPhone 8
**iOS version:** 13.3.1
**Signal version:** 3.6.1.4

### Link to debug log
https://debuglogs.org/e088a9aa58c4901f2060e5608e42c4862a57fdba8d62161d936d88ae602bd2f9

**Comment by jahed** [comment]
This makes desktop calls to mobile devices (horizontal video cropped to vertical) impractical as you're never sure what's on camera and how cropped/zoomed it is.
