### ISSUE TITLE
 Contacts show phone numbers instead of names but only in the list

### ISSUE THREAD

**Issue by wheelseal** [signalapp/Signal-Android#9492]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 Contacts show phone numbers instead of names but only in the chat-list. The Memberlist of a Group-chat are show the User-Names Correctly. Also in the overview of the Reactionbar.

### Steps to reproduce
I Don't know. I used the AlienDalvik Android runtime (Android 8.1). I knowSignal changed the type of access to the address book. But I know also that other Dalvik users have no problems like that.

**Actual result:** Phone numers are shown instead the username in the chat list. But in the Memberlist of a Group chat or in the Overview of the reactionbar the username are shown correctly.
**Expected result:** Usernames will shown correctly erverywhere.

### Screenshots

Part of my contact-List: show only phone numbers
![contact2](https://user-images.githubusercontent.com/61382908/77227852-54740980-6b83-11ea-90d4-216b1c1c9c0e.png)

Part of a chatgroup-list: show Contact names
![contact3](https://user-images.githubusercontent.com/61382908/77227808-25f62e80-6b83-11ea-8e79-b68ae7d9a419.jpg)

Overview of the Reaction bar: show contact names.
![contact](https://user-images.githubusercontent.com/61382908/77227919-f98ee200-6b83-11ea-8f1e-d71806508b22.jpg)

### Device info

**Device:** Sony Xperia XA2
**Android version:** 8.1
**Signal version:** 4.57.2

### Link to debug log
https://debuglogs.org/b38ca5ce19443e40a10bd3a78576a664e0176b5284a20c6683a4389382eb5861

**Comment by wheelseal** [comment]
I don't know why but now I see all of my Contacts by its name. Very Strange

**Comment by u32i64** [comment]
As far as I understand, that's because in the future the system contact name or profile name will be preferred over phone numbers, UUIDs, etc. So it's just a glimpse into the future...
