### ISSUE TITLE
Sending video files larger than 50MB would fail silently, and appears as empty message for the receiver

### ISSUE THREAD

**Issue by PlutoniumHeart** [signalapp/Signal-Android#9495]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending video files larger than 50MB would fail silently, and appears as empty message for the receiver

### Steps to reproduce
- Open signal app
- Attach a video file larger than 50MB
- Send the attached video file

**Actual result:** Notification area shows notification of "compressing video..." and the notification later disappears and the video shows on signal as sent, but was never uploaded. For the receiver, an empty message appears in the conversation.
**Expected result:** The attached video should be uploaded and sent, the receiver should receive the actual video instead of an empty message.

### Screenshots
3 videos sent, 2 are larger than 50MB. Only the one smaller than 50MB was successfully sent

![Screenshot_20200321_235623](https://user-images.githubusercontent.com/3313110/77244178-9cb91900-6bcf-11ea-9345-971f23713660.png)

### Device info

**Device:** OnePlus 6
**Android version:** 10.3.1
**Signal version:** Latest play store version

**Comment by alan-signal** [comment]
Please provide the debug log. Email alan@signal.org if you prefer.
