### ISSUE TITLE
Chooses multiple recipients from contacts sends only to a single recipient.

### ISSUE THREAD

**Issue by deepskydiver** [signalapp/Signal-Android#9496]
### Bug description
Attempting to send a message to a number of contacts sends the message to only the recipient with the lowest number. I am in Australia on Optus.

### Steps to reproduce
- Select multiple contacts in contacts (25 in my case)
-  Choose send message from menu
- Choose signal (signal is my default)
- type message in, simple text less than 160 characters
- send message

**Actual result:** 
The only person to receive the message is the one who has the lowest mobile number. In my case they are alphabetically towards the end of the list of those selected. 

**Expected result:** 
All recipients will receive the message.

### Device info

**Device:** Google Pixel 4XL
**Android version:** 10
**Signal version:** 4.57.1

### Link to debug log
No debug log attached (I can't repeat messages to that many people in my team for nothing.)

**Comment by alan-signal** [comment]
Is this SMS then?

> I can't repeat messages to that many people in my team for nothing.

Not sure what that means, you don't need to repeat it to supply the log.

**Comment by deepskydiver** [comment]
Thanks for replying.

I don't know where the logs are stored. Have googled it, can't find it. Ideally that would be in the bug template. On re-sending the message: I can only really send messages to everyone in my team for a reason - not to run diagnostics. So I don't have the option of repeating it unfortunately (it might arise later).

**Comment by rainerzufall** [comment]
@deepskydiver 
https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug

**Comment by UserX404** [comment]
@deepskydiver 
What you are meaning is SMS-broadcasting which is still not supported by Signal.

**Comment by deepskydiver** [comment]
Ahh @UserX404  - I did not know that, thanks. 
Presumably you can send to more than one person - what are the limits?
(Is there a reference?)

**Comment by alan-signal** [comment]
> I don't know where the logs are stored. Have googled it, can't find it. Ideally that would be in the bug template.

The instructions are not very in depth, but it is in the bug template:

```
### Link to debug log
<!-- immediately after the bug has happened capture a
debug log via Signal's advanced settings and paste the link below -->
```

> On re-sending the message: I can only really send messages to everyone in my team for a reason - not to run diagnostics. So I don't have the option of repeating it unfortunately (it might arise later).

But I said: "you don't need to repeat it to supply the log." but at this point, it is probably best to wait till the next occurrence.
