### ISSUE TITLE
Feature Request: Link previews for Twitter

### ISSUE THREAD

**Issue by astubbs** [signalapp/Signal-Android#9499]
Feature Request: Link previews for Twitter.

Currently Signal allows Link previews for several sites, including instagram, reddit, and pinterest. Twitter would be a good addition!

ios feature request: https://github.com/signalapp/Signal-iOS/issues/4414

**Comment by astubbs** [comment]
root feature request: https://community.signalusers.org/t/twitter-message-preview/12040

**Comment by alan-signal** [comment]
Please use the community forum only for feature requests https://community.signalusers.org/
