### ISSUE TITLE
Reaction emoji does not use system emoji when enabled

### ISSUE THREAD

**Issue by gtsiolis** [signalapp/Signal-Android#9500]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

[Reaction emoji](https://signal.org/blog/reactions/) does not use system emoji when enabled.

### Steps to reproduce
1. Go to _Settings_, _Chats and media_, and turn on _Use system emoji_.
1. Try to add a reaction to a message.
1. Send a message that inludes the same emoji.

**Actual result:** The emoji within the message sent is different from the emoji used for the reaction.
**Expected result:** Both emojis should be the same.

### Screenshots

Example 1 | Example 2
------------ | -------------
![text-1](https://user-images.githubusercontent.com/120486/77426866-0a3a9480-6dde-11ea-801f-b0e8bd986159.png) | ![text-2](https://user-images.githubusercontent.com/120486/77426876-0e66b200-6dde-11ea-8639-e9bab48a6434.png)

### Device info
**Device:** Pixel 3a
**Android version:** 10
**Signal version:** 4.67.1

**Comment by gtsiolis** [comment]
@greyson-signal I just found two duplicate issues (https://github.com/signalapp/Signal-Android/issues/9402, https://github.com/signalapp/Signal-Android/issues/9396) about this!

**Question:** Since a) those were closed for technical reasons (https://github.com/signalapp/Signal-Android/issues/9402#issuecomment-586780340, https://github.com/signalapp/Signal-Android/issues/9396#issuecomment-586406318), b) this issue affects the user experience of the app negatively, and c) there are multiple issues for this, do you think it's worth keeping one of these issues open to track further demand or track possible future issue resolution? 🏀

**Comment by Tursko** [comment]
You should move the discussion to the forums and close this since its technically not an issue.

**Comment by greyson-signal** [comment]
> do you think it's worth keeping one of these issues open

Nope, I'll close this one for the same reasons I closed the others :)

**Comment by gtsiolis** [comment]
Thanks @greyson-signal @Tursko! I've moved this to the community forum (see [topic](https://community.signalusers.org/t/reaction-emoji-does-not-use-system-emoji-when-enabled/12715?u=gtsiolis)) for input. Feel free to close if needed since I'm not familiar with the product development flow used. 🥝
