### ISSUE TITLE
Sharing via Signal doesn’t work

### ISSUE THREAD

**Issue by leofleury** [signalapp/Signal-Android#9504]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Impossible to share anything with the sharing options on my iPhone 7 Plus .

### Steps to reproduce
- Making screenshot
- Tap on screenshot 
- Tap sharing icon
- Find signal icon app and tap on it
- Signal page close it self

**Actual result:** The sharing window coming up from the bottom close itself and go back to sharing options of the OS
**Expected result:** i would be expected to be able to chose the contact in signal I want to send the screenshot to. Send the screenshot.

### Screenshots

![2AD5861C-0B7B-48F8-A4F8-71F8774FE273](https://user-images.githubusercontent.com/18571468/77567119-fcad0980-6ec6-11ea-994f-bdf1237c555a.jpeg)
![2BA75634-FDB9-4832-BEA7-AB005AA382DC](https://user-images.githubusercontent.com/18571468/77567125-fe76cd00-6ec6-11ea-872a-02b901a3537b.jpeg)
![3A86CD8F-1B05-4C07-BB8F-8A3E71974BC7](https://user-images.githubusercontent.com/18571468/77567126-ff0f6380-6ec6-11ea-8b47-7261a8bd74a0.png)

### Device info

**Device:** IPhone 7 Plus
**Android version:** IOS 13.4 (sorry no android)
**Signal version:** 3.6.1

### Link to debug log

https://debuglogs.org/2d5452ae7d6229eb420b8d22d55e95ac95cd1916c7acd482341be8bea5080376.zip
Not sure that’s right

**Comment by u32i64** [comment]
Why don't you create an issue in [signalapp/Signal-iOS](https://github.com/signalapp/Signal-iOS) instead?
