### ISSUE TITLE
Intermittent non-necessary ellipsis of text with missing "Read More" button

### ISSUE THREAD

**Issue by hwinnemoe** [signalapp/Signal-Android#9506]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While using Signal, sometimes a short message's content gets shortened using ellipsis without the need for shortening it. Also, no "Read More" button is visible. This issue is resolved by reopening the conversation. Copying the message yields the full text.

### Steps to reproduce
- use Signal

**Actual result:** A short message gets shortened using ellipsis without the need for it, no "Read More" is visible. The full message's content cannot be read.
**Expected result:** A short message is displayed normally containing the full text in visible form.

### Screenshots

actual (here "from" was shortened to "...m":
![actual](https://user-images.githubusercontent.com/42788925/77741619-7c48ee80-7015-11ea-82c2-55c6bc7b672e.png)
expected:
![expected](https://user-images.githubusercontent.com/42788925/77741647-87038380-7015-11ea-926a-57d5c1e90c8a.png)

### Device info

**Device:** HTC One M7
**Android version:** 7.1.2
**Signal version:** 4.57.2

### Link to debug log

[can be sent upon request]

**Comment by hwinnemoe** [comment]
Seems to not occur anymore.

**Comment by Whatnoww** [comment]
This issue still occurs. It seems to happen randomly. It persisted up to 5.25 when I reported it here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-25-release/38129/314?u=whatnoww

And another user on reddit has also reported it happening to him too as seen here:
https://old.reddit.com/r/signal/comments/r2c7ar/ellipsis_appear_for_no_reason_in_the_middle_of/

**Comment by hwinnemoe** [comment]
Feel free to open a new issue if you're still seeing this specific problem.
