### ISSUE TITLE
Cannot delete draft of answer to message (quoted message)

### ISSUE THREAD

**Issue by sseide** [signalapp/Signal-Android#9507]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Open the list of a conversation. Than pick a message to answer to (i really dont know how this happens, some swipe magic i belief and i really do not like this feature at all but does not matter here). Now this message is directly on top of the text input box to include in the next message to send.

This draft cannot be deleted anymore. I can input my own message in the text field and delete my own text but i cannot delete the old message signal wants to answer to. To get rid if it i _must_ send the message.

### Steps to reproduce
- open message list of a conversation
- swipe somehow(?) to answer to a message from the list
- now this message is stacked on top of text input field
- delete this draft is impossible, no long-press, swipe or menu entry to stop answering with this message quoted

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Message quote cannot be deleted, quoted message must be send to get rid of it.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Quoted message can be delete, there should be an obvious / easy to find way to delete the draft (e.g. menu entry in top menu or similiar). I should not be forced to send the quote. There should be more ways to do this  than some hidden swipe actions no one knows

### Device info

**Device:** Fairphone 2 
**Android version:** 9 build from 19.03.2020
**Signal version:** 4.57.2

### Link to debug log
none

### Side note ###
How can this answering feature be disabled?

**Comment by u32i64** [comment]
👀 [Deleting a draft](https://community.signalusers.org/t/deleting-a-draft/12547/2?u=u32i64)

**Comment by greyson-signal** [comment]
There is an X there in the top right of the quote. If you're in dark theme, it's very difficult to see, so I've made a change to make it more visible in that case. That'll go out in 4.58.1.

**Comment by sseide** [comment]
Ok - thanks - but this X is not visible on pictures in dark mode. I had this issue three times and never seen the X. Now the last one (where i wrote this issue) was waiting to be delete and there i looked really really hard but no X visible over the picture on the draft...

The UI should defenitly reworked (dark mode only?) in regard to this case.

blindly pointing to the upper corner where it should be deleted the draft.

**Comment by sseide** [comment]
ok, its better to see now.

But you should really think about moving the (x) outside the images. You cannot control the images. For some lighter and turbulent images is it hard to see even with the small semi-transparent circle around. It may work for most images but not for all and user using this delete feature the first time wont see it...

There is more than enough space right of the image to place the (x) there and there is a solid background you control, therefor you can choose colors with good contrast on dark and light theme.
