### ISSUE TITLE
Photos get cropped and rotated when sending via in-app camera

### ISSUE THREAD

**Issue by AuspeXeu** [signalapp/Signal-Android#9509]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using the in-app camera to send a photo unintentionally crops it when taken in portrait mode, this does not happen while in landscape mode!

### Steps to reproduce
- Open a chat
- Make sure you are in portrait mode
- Use the camera button to take a picture
- See that the picture is rotated by 90 degrees and cropped, i.e. missing a third of the original size.

**Actual result:** Cropped and rotated image
**Expected result:** Have a normal portrait mode photo

### Screenshots
1. Inside the camera app.
2. Result of the picture taken.

![Screenshot_20200328-153650](https://user-images.githubusercontent.com/2115696/77832194-8862a800-710a-11ea-935c-f35242f1de6c.png)
![Screenshot_20200328-153710](https://user-images.githubusercontent.com/2115696/77832196-8a2c6b80-710a-11ea-95e3-0ddcc8c6460f.png)

### Device info

**Device:** Google Pixel 1 XL
**Android version:** 10
**Signal version:** 4.58.1

### Link to debug log
https://debuglogs.org/67ae10d9ef57207d178e6264abf998cc0976e97aa3943687775f39588bdfc32d

**Comment by mrgtreeskier** [comment]
I can duplicate this.

Device info

Device: Google Pixel XL

Android version: stock Android 10

Signal version: 4.58.1 

Link to debug log:
https://debuglogs.org/5a128ecced1efcfc433b30e6a31c7396f55a9c9c73c23ca94e00b13a2c32fec3

**Comment by alex-signal** [comment]
Thanks for the report! If people could please respond with what device they're seeing the issue on (as these two did) that'd be tremendously helpful! I'm unable to reproduce on a Pixel 4 but will give the other devices I have available to me a whirl.

**Comment by AuspeXeu** [comment]
My partner's Pixel 2 also does *not* have this problem.

**Comment by alex-signal** [comment]
Similar issue found here: https://issuetracker.google.com/issues/148962652

**Comment by rainerzufall** [comment]
> If people could please respond with what device they're seeing the issue on (as these two did) that'd be tremendously helpful!

**Device:** Fairphone 3 (FP3)
**Android version:** 9
**Signal version:** 4.58.1
