### ISSUE TITLE
Can't set Signal as default SMS app, Act 2

### ISSUE THREAD

**Issue by Restless-mind** [signalapp/Signal-Android#9515]
### Bug description

Hi !
As said, I can't set signal as default app since I updated Rom. In the device options, Signal is default app, but when I try to write a SMS to someone who doesn't have signal, I can't text because the app proposes me to set Signal as default app...

https://debuglogs.org/52a8cbf2b7d6e492c4f6ea33f182c07063aee4f0e92103c03a9ead604489fa15

### Screenshots

![signal-attachment-2020-04-02-110256_001](https://user-images.githubusercontent.com/63042783/78230431-9aa96100-74d1-11ea-9b11-11a87868171f.jpeg)
![signal-attachment-2020-04-02-110256_002](https://user-images.githubusercontent.com/63042783/78230436-9bda8e00-74d1-11ea-966d-7a0579e9defb.jpeg)

Manufacturer : Xiaomi
Model        : POCO F1
Android      : 10
App          : Signal 4.58.4 (6181)

**Comment by greyson-signal** [comment]
Given that this appears to work on every other device, but not what appears to be some bleeding-edge version of lineage (eng.sergio.20200324.193056, lineage_beryllium-userdebug 10 QQ2A.200305.003 eng.sergio.20200324.193056 test-keys), I'm going to assume this is a ROM issue.
