### ISSUE TITLE
Swipe Delete Sensitivity BAD

### ISSUE THREAD

**Issue by akissz** [signalapp/Signal-Android#9517]
This happens to me a lot so it must be a issue. The swipe delete feature is too sensitive. I brush my palm on the phone to remove a tiny piece of dust on the screen and messages are deleted also. So quickly tap the undo button. There needs to be a better method to make swipe delete function better. Maybe a confirmation feature. Or maybe make the swipe require 2 swipes to delete. Like swipe swipe and that deletes a message. I kind of like that idea!

**Comment by alan-signal** [comment]
Are you referring to swipe to archive a conversation?

**Comment by greyson-signal** [comment]
I believe the feature you're talking about is swipe-to-archive, which is on the conversation list. Keep in mind that those chats aren't deleted, merely "archived". You can scroll to the bottom of the conversation list, tap "Archived", and unarchive them if you wish by swiping again.

In addition, after the swipe-to-archive action occurs, a snackbar appears at the bottom of the screen allowing you to undo.

We're also using the standard list-swiping-sensitivity setup, so our swipe should be the same sensitivity as most apps that offer similar features.

Put all that together, and I think what we have is just fine. But thanks!
