### ISSUE TITLE
App crashes on start when new received message is waiting 

### ISSUE THREAD

**Issue by stephanborn** [signalapp/Signal-Android#9519]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal app crashes immediately after start and login of passcode if new message has been received. This behavior started after I have updated app today to latest version 4.58.4.

### Steps to reproduce
- App not started
- Message received, app icon shows numbers of new messages
- start app
- enter passcode

**Actual result:** 
The chats screen is shown for a second or so. Then app crashes. No chance to create debug logs.

**Expected result:** 
The chat screen is shown and I could open chat with new messages.

### Device info
**Device:** Samsung S3 Neo GT-I9301I
**Android version:** 4.4 2
**Signal version:** 4.58.4

### Link to debug log
Cannot create debug log as app crashes after login. Send logs on login screen can be selected but after login it crashes and no logs.

**Comment by stephanborn** [comment]
Screenshot of stacktrace I could take from Google Play feedback system:
![Screenshot_2020-04-03-21-53-43](https://user-images.githubusercontent.com/1429312/78399704-b3129c00-75f5-11ea-9de1-24fd36bc1e70.png)

**Comment by BhaktaOm** [comment]
Exact same problem since upgrading to 4.58.4 today.

**Device:** Samsung S4 Mini SGH-I257M
**Android version:** 4.4 2
**Signal version:** 4.58.4

**Comment by greyson-signal** [comment]
This is fixed in 4.58.5, which is already rolling out. Thanks!

**Comment by stephanborn** [comment]
Just updated and it works again. Thanks for the quick help!
