### ISSUE TITLE
Unable to Import Older Plaintext Backups

### ISSUE THREAD

**Issue by xcjs** [signalapp/Signal-Android#9520]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have some plaintext Signal backups that I'd like to import. I understand the justification for not exporting plaintext backups, but I would like to import my "legacy" plaintext backups and add them to my encrypted backup.

Unfortunately this feature was removed.

**Comment by alan-signal** [comment]
Somebody might be able to advise on the forum https://community.signalusers.org/
