### ISSUE TITLE
Documentation is widely out of date

### ISSUE THREAD

**Issue by crypticalcynical** [signalapp/Signal-Android#9523]
This is actually an issue with https://github.com/signalapp/Signal-Server/wiki/API-Protocol but there is no Issue tracker there.

The API Protocol page has not been modified since 2014, meanwhile the API seems to have changed. Better documentation for the protofbufs would also be nice.

**Comment by greyson-signal** [comment]
Hi there, these issues are reserved specifically for bugs on the Android app. Thanks!
