### ISSUE TITLE
Emoji Quick Search Using Colons 

### ISSUE THREAD

**Issue by collinarnett** [signalapp/Signal-Android#9527]
Is it possible to get a inline emoji search method using colons similar to how other apps handle typing emojis? I personally find it easier than selecting and searching for emojis every time.

Eg.
```
:wink: 
:smile: 
```
Renders as 
:wink: 
:smile:

**Comment by UserX404** [comment]
Check the Forum! It's already discussed there.

**Comment by collinarnett** [comment]
https://community.signalusers.org/t/emoji-autocomplete-type-ahead-support/5273/13 <-- Seems like there hasn't been any activity for a while except for you @UserX404

**Comment by Tursko** [comment]
The issue tracker is for tracking issues. You should move this discussion over to the forums and close this 'issue'.

**Comment by UserX404** [comment]
@collinarnett you are free to support this feature and attend this discussion but Github isn't the right place.
