### ISSUE TITLE
provide textsecure pc client

### ISSUE THREAD

**Issue by mfuhrmann** [signalapp/Signal-Android#953]
I know, it is planned, but I didn't find an issue for this topic.
I recommend to provide a multi OS version.

**Comment by r-ku** [comment]
@jedie would you mind sharing your PyTextSecure code? Maybe it was possible to pick it up. I am mainly interested in lib that handles the protocol.

**Comment by jedie** [comment]
There was nothing to share ;)

Maybe https://github.com/TerrorM/pytextsecure is a good place?

**Comment by r-ku** [comment]
Thank you!
