### ISSUE TITLE
Conversation partners hear own voice while Signal calls when using headset

### ISSUE THREAD

**Issue by 0av** [signalapp/Signal-Android#9530]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversation partner (_B_) can hear his/her own voice while Signal calls when the caller (_A_) is using headsets. _B_ hears his/her own voice with the same volume like _A_'s voice (not like a background noise).

### Steps to reproduce
- Plug in headsets
- Start a Signal voice call
- Let _B_ speak something

**Actual result:** _B_ can hear his/her own voice. _B_ hears his/her own voice with the same volume like _A_'s voice (not like a background noise). This problem is only appearing in Signal calls (also tested: Normal phone calls, WhatsApp calls, Telegram calls).
**Expected result:** _B_ should only hear _A_'s voice.

### Device info

**Device:** HUAWEI KIW-L21
**Android version:** 9 (LineageOS 16.0-20200402-NIGHTLY-kiwi)
**Signal version:** 4.58.5

**Comment by JonasNord** [comment]
Likewise
Device: ONEPLUS A5000
Android version: 9 (OxygenOS 9.0.11)
Signal version: 4.58.5

**Comment by primarto** [comment]
Same problem with me

Device: Xiaomi redmi note 4X
Android version: 7.0
Signal version: 4.58.5

**Comment by 0x0frmbl** [comment]
I have the same problem without Headset.

Device: Mi 9 Lite
Android version: 10 (LineageOS 17.1)
Signal version: 4.58.5

**Comment by szotsaki** [comment]
Yes, it's still an issue with loudspeakers on the other end on certain Chinese phones.
