### ISSUE TITLE
No Notifications when Receiving a Signal Message

### ISSUE THREAD

**Issue by osmgit** [signalapp/Signal-Android#9533]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications are not received for new Signal messages. There is no indication that a new message has been received. You basically have to open Signal to check for new messages (kind of like opening your email account to check for new emails.)

When opening Signal, the new messages and notifications are received all at once.

This generally happens when Signal hasn't been used for a while. Once we start using Signal again, the notifications work OK. Until... we don't use Signal again for a while, then the notifications stop working again.

So you end up messaging someone on Signal, and then alerting them by SMS or email to check their Signal messages.

This is happening to 5 people I know who are using Signal all on different devices. The fact is that no one would else would report this bug here, most people just use alternative messaging apps instead eg. Whatsapp. 

I fear that this bug is really hurting Signal messenger.

### Steps to reproduce
- Someone sends a signal message

**Actual result:** No new message notification is received - no sounds, no vibration, no lights, nothing. There is not even an indication on the App Icon, nothing to tell them that a new Signal message has been received.

**Expected result:** Phone should make a sound, vibrate, turn on the new message light or at the very least show an indication on the App Icon that a new Signal message has been received.

### Device info

**Device:** Samsung Galaxy S4
**Android version:** 6.0.1
**Signal version:** 4.57.2

### Device info
**Device:** Samsung Galaxy S4 Mini
**Android version:** 4.4.4
**Signal version:** 4.57.2

### Device info
**Device:** Redmi Note ?
**Android version:** ???
**Signal version:** 4.57.2

**Comment by bertlebbert** [comment]
Same here, on rooted Galaxy S7 running Oreo 8.0.0,  but only sometimes. For some messages I receive notifications, but for some I don't... a couple of contacts mentioned they also have this same issue.

**Comment by osmgit** [comment]
Does it happen to you when Signal hasn't been used in a while? 

We only message occasionally between ourselves and it seems like Signal goes into some sort of hibernation or something and then the first message sent after a few days of no contact never alerts the receiver.

**Comment by bertlebbert** [comment]
Yes, in fact... miss notifications ONLY when Signal has been idle for a while.

**Comment by primarto** [comment]
Exactly the same problem as OSMGIT said happens to me. I just wanted to report this problem, too.

Device info

Device: Xiaomi redmi note 4X
Android version: 7.0
Signal version: 4.58.5

and another person i know

Device info

Device: Xiaomi redmi note 7
Android version: 9.0
Signal version: 4.58.5

**Comment by Genis-Sage** [comment]
hey @osmgit 

from what you describe, i guess it's the same issue as
#9356 and #8692 and #9438

to identify, if it's the same behaviour, you should post a debug log,
so the Signal devs can see, if they get the wake up messages


you and your friends can also try out the troubleshooting here:
[Phone specific troubleshooting](https://support.signal.org/hc/en-us/articles/360028198711-Phone-Specific-Troubleshooting#h_d4792124-53e5-4949-8b41-e2ef2aae455e)

background:
different venders implement different battery saving technologies, which can be quite accressive and kill background apps (sometimes big apps are whitelisted, and therefore don't show this behaviour)

**Comment by Neurogami** [comment]
I have the same issue.  Been missing messages from family because of this.  Rebooting the phone did not help, so at least in my case it does not seem to be a sleep or idle condition.  I also get regular messages from assorted monitoring programs so signal is rarely inactive for more than 30 minutes

Really maddening.

**Comment by Neurogami** [comment]
I just send myself a test message that should have resulted in a notification sound, but it did not.  

Here's the debug log right after that test

https://debuglogs.org/e7d499a5e60ee38fe0b67ce22cabfaa4fc425254c38016528f4f3222d6205e3e

**Comment by Neurogami** [comment]
An update:  Frustrated at missng messages I decide to check the app settings, to see if there was something odd about alerts there.  And there was.  The app was set to "No notifications".  I have zero idea how this  happened; I'll cop to screwing it up myself, but honestly  I would never ordinarily have a reason to even look a this.  So, bug someplace, brain-fart, whatever, I set it to allow notifications, and even set it to take priority for notifications.

I then send myself a text messages, and don't get a notification sound.
But shortly after, I do get sounds from incoming messages.

As best I can tell now, I mostly get notification sounds but there seem to be times when I don't.

Today, while reading a message, two new messages from different senders arrived at the exact same time.  That seemed really unlikely, and there was no notification sound when this happened. 

So, anecdotally, I believe I am still missing some notification sounds but do not know under what specific circumstances.

**Comment by ankushdas9** [comment]
I can confirm this happening to my friends as well. Will try to get a debug log from them.

But, imo, these issues should be treated as a priority considering that it prevents users to use Signal in the first place.

But, I guess, we'll have to end up waiting for a long time considering the long backlog list of issues that they still need to address :/

**Comment by caco13** [comment]
Same issue for me. I've tested with some friends and they do not receive notifications. As many related here I also think this is a big, if not the biggest problem in Signal adoption for regular people. And I really, really want to use Signal in as my primary message app.

**Device info**:

Device: Semp GO5E
Android version: 8.1.0
Signal version: 4.58.5

**Comment by ioogithub** [comment]
I have this issue as well, no notifications and calls go to missed call immediately.

3 users, 4 ohones.

Moto G7 with LineageOS
iPhone 7 and iPhone 11, same user upgraded his phone, same bug, no notifications.
Samsung Galaxy A8

These are non technical users and I won't be troubleshooting with them. We have given Signal a try but it is not functional. I will not try to move users to the platform any longer.

**Comment by osmgit** [comment]
> I have this issue as well, no notifications and calls go to missed call immediately.
> 
> 3 users, 4 phones.
> 
> Moto G7 with LineageOS
> iPhone 7 and iPhone 11, same user upgraded his phone, same bug, no notifications.
> Samsung Galaxy A8
> 
> These are non technical users and I won't be troubleshooting with them. We have given Signal a try but it is not functional. I will not try to move users to the platform any longer.

Ah yes we've had this problem too in the past - Signal doesn't ring on the persons phone who you are trying to call. It just leaves a missed call notification but never rings!

Unfortunately most people don't report bugs these days, they just go to a new app. I wish it wasn't so hard to report bugs. My partner and her friend gave up on Signal and went back to Whatsapp. I'll be damned if I ever use Whatsapp again, that's why I made this bug report!

**Comment by greyson-signal** [comment]
Centralizing "late/no notification" issues to #8692

**Comment by Neurogami** [comment]
Unclear why this is getting lumped into another issue.  I get messages on time, but I often get no notification sound. Looking at that other issue it seems concerned with delayed messages, not an absence of a notification sound for messages delivered on-time.   

Similar perhaps but not the same.

In any event it makes Signal close to unusable for me.

**Comment by greyson-signal** [comment]
@Neurogami You're not the only person who's describing a problem in this thread, and your problem seems to be unique from the rest of this thread, including OP's original issue. If you're having problems with notification sounds that you think is separate from the issue I linked, please open a new issue.

**Comment by Neurogami** [comment]
The bug description is _exactly_ what I'm experiencing.  Messages arrive, but often there is no notification sound.   People may be describing variations of this in the thread, but the description at the top of the ticket is my problem, not delayed/bunched messages.

**Comment by greyson-signal** [comment]
From the original issue description:

> Notifications are not received for new Signal messages. There is no indication that a new message has been received. You basically have to open Signal to check for new messages (kind of like opening your email account to check for new emails.)
>
>When opening Signal, the new messages and notifications are received all at once.

OP is describing that they have no notifications *at all*, which is just another way of saying that notifications are late. You seem to be describing that you're receiving notifications, but there's no sound. If you're not receiving notifications at all, then the issue I linked is for you.
