### ISSUE TITLE
I see corrupt video in video call while people on the other end sees my video clearly

### ISSUE THREAD

**Issue by free-libre-software** [signalapp/Signal-Android#9535]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During video calls, I see video of people on the other side corrupted while others see my video clearly. This happens with every call and not specific to one person. Switching and toggling camera on the other end does not solve the issue. I also faced this issue when I was using Android 7 but after upgrading to Android 8, this issue went away. Now with Android 9, I am again facing this issue. From glancing at log, I think possible cause of it could be either using hardware decoder or some bug with RingRTC/WebRTC. If required to test app after some changes to code, I can compile and test it.

### Steps to reproduce
- Start video call
- Recipient picks up the call
Or
- The other person video calls
- I pick up call

**Actual result:** I see recipient's video as corrupt while recipient can see my video clearly
**Expected result:** I should see the video of people on the other end clearly

### Screenshots
![2](https://user-images.githubusercontent.com/62927033/78986050-b1a12080-7b6d-11ea-9a05-a5b45f06a3a3.png)

### Device info

**Device:** ZUK Z1
**Android version:** 9 (d6c3212c33, lineage_ham-userdebug 9 PQ3A.190801.002 d6c3212c33)
**Signal version:** Signal 4.58.5 (6191)

### Link to debug log

https://debuglogs.org/f46939e308ac704a3cd269bfaa16bbd0cf48632a703d50ac84732169c50f881c

**Comment by arnowi** [comment]
It had been a while since I did a video call and when I received a video call yesterday I had a similar issue. The left half of the screen looked pixelated and distorted and, at least initially, the right half of the screen was fairly decent but that soon gave up as well and turned into a distorted mess.
