### ISSUE TITLE
crash on 4.58.5 in conversation with new contact after enabling disappearing messages before first message exchange

### ISSUE THREAD

**Issue by rainerzufall** [signalapp/Signal-Android#9537]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description + Steps:
I experienced a crash on 4.48.5:
- in a conversation with a new Signal user. 
- Before the first messages are exchanged in the thread the disappearing message timer is set to one minute (by me)
- then a few message are exchanged (first message from me)
- most probably the first message disappears, while message exchange is still happening
- crash
- (not hundred percent sure - I think I was thrown back to conversation overview and could go back to the conversation and carry on)
- no complaints from the other person (although I did not ask, because I strongarmed this person to use Signal - I did not want to ask if it crashed on his side with his first conversation with me ;) )

```
--------- beginning of crash
04-07 22:18:53.718 18705 18705 E AndroidRuntime: FATAL EXCEPTION: main
04-07 22:18:53.718 18705 18705 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18705
04-07 22:18:53.718 18705 18705 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{b572684 position=9 id=7123413091263581814, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{b8955b8 VFED.V... ........ 0,0-1080,873 #102000a android:id/list}, a...@... l...@... c...@...
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6746)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-07 22:18:53.718 18705 18705 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-07 22:20:37.675  7664  7664 D TextClassifierService: No configured system TextClassifierService
04-07 22:20:37.678  7664  7664 D TextClassifierService: No configured system TextClassifierService
04-07 22:20:37.720  7664  7693 D TextClassifierService: No configured system TextClassifierService
04-07 22:20:37.781  7664  7693 D androidtc: Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=609 locales=en }
04-07 22:20:37.888  7664  7693 D TextClassifierService: No configured system TextClassifierService
04-07 22:20:39.712  7664  7664 D TextClassifierService: No configured system TextClassifierService
04-07 22:20:39.714  7664  7723 D TextClassifierService: No configured system TextClassifierService

```

### Device info
**Device:** Fairphone 3
**Android version:** 9
**Signal version:** 4.58.5

### Link to debug log
https://debuglogs.org/04b9fbb6ad3b9662f4393bd47470ceea4581733d23dd8d691554326b1ba98538

**Comment by bbinoy** [comment]
I suspect I have the same issue.

* Group with 3 people was created
* Disappearing message was enabled before first message send
* Some messages exchanged, disappearing messages disabled, some more messages sent
* Signal on Android keeps crashing when opening the app
* In flight mode it doesn't crash
* Signal Desktop doesn't crash
* For one other participant of the group the same happens, but apparently not for the one who created the group
* I managed to exit and delete the group while in flight mode, but it still keeps crashing

## Device Info
Device: Fairphone 2
Android version: 7.1.2
Signal version: 4.59.4

## Logs
Unfortunately, I can't get the logs because of the crash. In flight mode I can't submit them, turning off flight mode makes the app crash immediately. I submitted feedback including logs through the google service though. And here is a screenshot of the (I think) relevant part:
![signal-attachment-2020-05-01-091657](https://user-images.githubusercontent.com/11409025/80789645-dbf26680-8b8c-11ea-8a3f-8d033cf6c4ba.png)

**Comment by bbinoy** [comment]
Updating to 4.59.6 fixed it. So maybe this issue can be resolved.
