### ISSUE TITLE
Behvior of the proximity sensor does not return to normal after listening to audio message.

### ISSUE THREAD

**Issue by 7heo** [signalapp/Signal-Android#9538]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The proximity sensor is active (e.g. blacks the screen when triggered) during audio message playback, and after the playback ends, is left active. When returning to the phone home app, it is still active.

### Steps to reproduce
- play an audio message
- trigger the proximity sensor
- wait for the audio message to end
- trigger the proximity sensor again (in signal or in an other app)

**Actual result:** The screen turns off every time the proximity sensor is triggered.
**Expected result:** The proximity sensor should be inoperant, and the screen should remain active.

### Device info
**Device:** LG Nexus 5X
**Android version:** 8.1.0 (LOS 15.1-20200217-NIGHTLY-bullhead, no gapps)
**Signal version:** 4.58.5

### App state

Signal messages and calls registered, SMS disabled, registeration lock PIN enabled, screen lock / fingerprint enabled, screen security enabled, incognito keyboard enabled, permissions: camera (only), notifications on.

### Link to debug log
I unfortunately did not think of saving the debug log when the problem happened.

### Additional information
It is worth noting that while experiencing this bug, the bug #7576 was also experienced.

**Comment by andreafeletto** [comment]
Same bug on Google Pixel 3a with Android 11.
I may add that when Signal is closed from the multitasking, the bug stops and the proximity sensor behavior gets back to default.

**Comment by vertigo220** [comment]
I wonder if this is why my proximity sensor keeps getting stuck on. I use KinScreen to keep my screen on when using it and every once in a while the screen will start turning off when it shouldn't because of this, and I have to reboot to fix it. Just tried testing it by recording a message and listening to it and by placing a call and triggering the sensor then hanging up and didn't have any issues, but maybe it takes something more specific.
