### ISSUE TITLE
[UI] Call icons state difficult perceptibility due to poor color contrast and size

### ISSUE THREAD

**Issue by marscher** [signalapp/Signal-Android#9539]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The icons in audio/video calls for toggling microphone, speaker, camera indicate activation by a minor darker blue tone. For elder people (50+) this is close to invisible, leading to user confusion (e.g. I can barely hear my conversation partner - do you have the speakers turned on?).
Even for younger folks this low contrast indicator is confusing (<35).

### Steps to reproduce
- Initiate a video/audio call.
- Hope, that your partner:
   - knows how to enable speakers 
   - does not accidentally turns of the microphone
   - toggles the video on/off button over and over again (this would just waste resources I guess, at least the result is clearly visible).

**Actual result:** (Elder) users do not easily understand the state of the calls buttons. 
**Expected result:** By increasing the contrast or the colored frame (or even its size) behind the icons would greatly increase the visibility of the state. I think these changes would render the UI more understandable/usable.

### Screenshots
The screenshot has been taken with googles accessibility scanner. If desired I can also try to attach the full report, but the essential information is that the icon size should be increased to at least 48x48 px. It didn't pick up the poor contrast of the state toggling though.   
![Screenshot_20200411-155015_Accessibility_Scanner](https://user-images.githubusercontent.com/170287/79045779-21b2b380-7c0d-11ea-87ee-661eaf0db88b.png)

### Device info
**Signal version:** 4.58.5

**Comment by Sgn-32** [comment]
New Calling UI was introduced with 4.60.
Issue should be solved.(?)

**Comment by marscher** [comment]
I haven't had the chance to test the new version yet, soit could be resolved already.

**Comment by marscher** [comment]
new design is just perfect! Thanks!
