### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [signalapp/Signal-Android#9540]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
Of course, it is very important to solve all vulnerabilities, CVEs.

**Comment by Neustradamus** [comment]
Dear Signal team, @Imperiopolis-Signal, @indutny-signal, @jrose-signal, @michelle-signal, @moxie0, @scottnonnenberg-signal,

In first, I wish you a Happy New Year!

Soon 2 years of the ticket, have you progressed to solve vulnerabilities, CVEs?

Thanks in advance.

**Comment by ehrenkret-signal** [comment]
commit 11df2bc51f9c5682c648996efec6b6fa59a3ffcc removed the last dependencies on spongycastle; there's still a couple of places where spongy proguard files and some excludes are in the current build.gradle that need to get cleaned out, but there's no dependency on spongycastle anymore it appears

**Comment by cody-signal** [comment]
This is the output of `gradlew Signal-Android:dependencies` 

[dependencies.txt](https://github.com/signalapp/Signal-Android/files/7952776/dependencies.txt)

**Comment by Neustradamus** [comment]
@ehrenkret-signal, @cody-signal: Thanks for your reply!

It will be nice to remove last lines about spongycastle:
- https://github.com/signalapp/Signal-Android/search?q=spongycastle

And I see Bouncy Castle 1.56 and 1.65 in dependencies.txt, a lot of CVEs here...

**Comment by Neustradamus** [comment]
Time to solve it?

**Comment by greyson-signal** [comment]
> And I see Bouncy Castle 1.56 and 1.65 in dependencies.txt, a lot of CVEs here...

We do not have a direct dependecy on these versions. They're indirect dependencies from official android libraries, all of which seem to be up-to-date on our end, so it's gonna be on them to resolve them.

**Comment by Neustradamus** [comment]
Time to remove this old files:
- https://github.com/signalapp/Signal-Android/search?q=spongycastle

And update?
- https://github.com/signalapp/Signal-Android/search?q=bouncycastle

Very old:
- https://github.com/signalapp/Signal-Android/blob/master/NOTICE
- https://github.com/signalapp/Signal-Android/blob/be21b9e163b04947b4187649a95e4c9a83da7e95/gradle/verification-metadata.xml#L2514

**Comment by Neustradamus** [comment]
There is too here:
- https://github.com/signalapp/curve25519-java/blob/70fae57d6dccff7e78a46203c534314b07dfdd98/j2me/build.gradle#L24

I suppose here, not sure the version:
- https://github.com/signalapp/webrtc/blob/00d215f59c9094a893e6b6c6a8f04a9467035f73/DEPS#L309

**Comment by Neustradamus** [comment]
@greyson-signal: Thanks for this removal :)
