### ISSUE TITLE
Changelog in releases

### ISSUE THREAD

**Issue by NoxInmortus** [signalapp/Signal-Android#9543]
Hello,

I would like to ask for the changelog to be added/deported to the releases as it can then be used for RSS news.

If it wasnt known : https://github.com/signalapp/Signal-Android/releases.atom provides an rss compatible flux that can be read easily with any RSS agregator supporting this format.

**Comment by NoxInmortus** [comment]
Hello, is this issue being considered ?

I also noticed that there is no changelog file in the repository, neither on the signal website. so I dont see any easy way to review the changes made. I dont really feel well about this lack of...transparency?readability?

**Comment by Go-rom** [comment]
As a RSS user, i think it's a good suggestion.

For now, you can find all the changelogs on the community forum (beta release section) : https://community.signalusers.org/c/beta-feedback/25

**Comment by dsvk** [comment]
Yes, this is still relevant. Not everyone here is a beta tester and the non-existence of the stable version's changelog _anywhere_ makes it impossible to follow stable version's development, know which features or bugfixes to look for or test etc. As mentioned by others already, RSS - which both GitHub releases and the forum software _do_ support - would be ideal for painless consumption.

The desktop version at least provides some rudimentary changelogs outlining new features and fixes of enough importance, attached to its [GitHub releases](https://github.com/signalapp/Signal-Desktop/releases) ([RSS feed](https://github.com/signalapp/Signal-Desktop/releases.atom)).

**Comment by cody-signal** [comment]
We take great care in how we write our git commit messages. We also tag every release. You should be easily able to compare two and read the history.

https://github.com/signalapp/Signal-Android/compare/v5.29.7...master

If someone from the community wanted to set something up to republish these as an RSS that would be awesome, but it's not something I see us doing.

**Comment by dsvk** [comment]
Well if that's the only source of data, GitHub already provides native per-branch RSS commit feeds.

This repo only has a `master` branch so append `.atom` to the relevant web URI, i. e. `https://github.com/signalapp/Signal-Android/commits/master` has an [RSS feed](https://github.com/signalapp/Signal-Android/commits/master.atom) on `https://github.com/signalapp/Signal-Android/commits/master.atom`.

Not as convenient to follow as a proper formatted changelog with a single feed entry per release but it's something, I guess.

**Comment by frmayall1978** [comment]
Looks like some developers think a changelog is some kind of favor or an optional thing to do, and that just looks nasty. I don't care how well-written your commit messages are - I **need** an actual changelog, even if neither me, nor anyone else on this planet will read them. It also looks like only the beta testers earned the right to take a glance at that changelog (although I suspect that beta changelog is just commit messages properly formatted). I know it's been 3 years, but the problem with missing changelog and thus users perceived as morons still persists. I guess it's a problem of many [opensource and not] services, programs, apps that have a cool and fancy website that features a PlayStore and AppStore URL and an obscure and mysterious way to download the APK file. One day I will refuse to use any project that doesn't have a conveniently placed changelog, even if it is open source.

**Comment by jayfan0** [comment]
I just spent 20 minutes trying to find a changelog for the latest android version and eventually came across this "closed" issue.

Desktop - changelog right here https://github.com/signalapp/Signal-Desktop/releases
iOS, here https://github.com/signalapp/Signal-iOS/releases

Android, no releases, no changelogs...,  https://github.com/signalapp/Signal-Android/releases
Playstore web, nothing https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

Eventually found a summary on play store mobile but why this is the only place it exists is beyond me when the other platform teams manage to do it. Surely something somewhere on Signals own platform should mention  something? It's not on github (and the tags are just "tagging x for release"), signal.org, signal support, signal community or the signal chat on the app.

I understand its not exactly a functional priority when there may more pressing other bugs and such to address and I really do appreciate the work gone in to this app and what it stands for (thank you!), but this was far too long winded to just see what the latest new features are...

**Comment by frmayall1978** [comment]
> I just spent 20 minutes trying to find a changelog for the latest android version and eventually came across this "closed" issue.
> 
> Desktop - changelog right here https://github.com/signalapp/Signal-Desktop/releases iOS, here https://github.com/signalapp/Signal-iOS/releases
> 
> Android, no releases, no changelogs..., https://github.com/signalapp/Signal-Android/releases Playstore web, nothing https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms
> 
> Eventually found a summary on play store mobile but why this is the only place it exists is beyond me when the other platform teams manage to do it. Surely something somewhere on Signals own platform should mention something? It's not on github (and the tags are just "tagging x for release"), signal.org, signal support, signal community or the signal chat on the app.
> 
> I understand its not exactly a functional priority when there may be more pressing bugs and such to address, and I really do appreciate the work gone in to this app and what it stands for (thank you!), but this was far too long winded to just see what the latest new features are...

It makes little sense to write "What's New" on playstore, but not in the place where the source code is stored and is worked on. Every time an update comes out, you are expected to download 90 MB of cat in the bag. What incentive does one have to download the app AGAIN, if nothing seems to have changed? I wrote several e-mails to support@signal.org regarding this (asking not saying), but never received a response. It's been a month.

> I understand its not exactly a functional priority when there may be more pressing bugs and such to address

But the changelog IS on playstore, so there is someone working on it, they just choose to not copy it to the place where all the magic happens.

**Comment by grtcdr** [comment]
Everyone in this thread has brought forth so many reasons to ship a changelog along with the source code, I'm not going to reiterate their points, it would serve no purpose.

But I'd like to express my worry as to the current situation, and my support to see a changelog shipped along the source code. 

I have my own package update workflow and I don't use any app stores, this means that I rely on the *transparency* of the vendor to announce their changes and going out of my way to diff changes manually is extra work that is better done upstream.

**Comment by greyson-signal** [comment]
We've started using [github releases](https://github.com/signalapp/Signal-Android/releases). Cody already wrote how to view the commits that take place in-between tags, but the releases page makes it even easier. Here's how you can compare two releases.

![Image](https://github.com/user-attachments/assets/fd5b5a5a-4a33-4cb6-8a91-ceff7d03c28e)

Our commit histories are very readable. We don't have merge commits, we don't split features across 15 commits with nonsense-inscrutable commits. Every commit is given a readable message and represents a notable change. Unlike a handwritten changelog, the commits also represent the entirety of the changes. It's not some filtered view of what I think is important, but rather a readable list of all of the changes that went into the app in-between releases. We have no other plans for a more stripped-down changelog.
