### ISSUE TITLE
Unable to register on new device: Rate limiting

### ISSUE THREAD

**Issue by charsi** [signalapp/Signal-Android#9544]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Getting a "unable to connect to service" message while trying to register my number on a new phone. This message is not accurate as if I change the number to something else it proceeds to send the confirmation sms.

### Steps to reproduce
- Install signal
- Register your number
- Uninstall app or delete app data
- Repeat above two steps 5-6 times

**Actual result:** After a few successful registrations the app eventually displays an error "unable to connect to service" even though connectivity is not the issue
**Expected result:** Signal should tell the user why the registration isn't working. How long they need to wait before trying again.

### Device info

**Device:** Samsung A5 2017
**Android version:** 9
**Signal version:** 4.58.5

### Link to debug log
Can't see a way to access logs. I'll get them via adb if required.

## Further testing
- Tried unregistering the number from signal using https://signal.org/signal/unregister/. Still unable to register.
- Tried registering again on the old phone which is also running same version of signal. On it the SMS method goes one step further. The message gets sent and I can enter it but I get the same "unable to connect to service" as a toast message after that. Switching to call verification works however.
- Took about two hours for the new phone to finally be able to proceed with the registration. 

So a specific combination of phone+number seems to get banned.

**Comment by issteve** [comment]
Got the same problem, but in German it's even worse cause it doesn't tell to wait, it forces the people to try it again at once and again and again...

**Comment by cascheberg** [comment]
Same issue as #7819, pending pull request #7872

**Comment by charsi** [comment]
Closing as this is duplicated.
