### ISSUE TITLE
Calls constitently fail to go through when call partner is on mobile network

### ISSUE THREAD

**Issue by happychameleon** [signalapp/Signal-Android#9546]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Regularly when trying to call someone or when someone is trying to call me all I receive is a "missed call" message, while never having the opportunity to pick up the call.

### Steps to reproduce
- open signal
- have someone try to call you who is on mobile network
- watch the missed call message appear, without ever being able to pick up the call
 
**Actual result:** 
I get a message that I missed a call without ever having the call go through

**Expected result:** 
I expect to get the screen where I can pick up the call when someone tries to call me and not only receive a message that I missed their call

### Screenshots

![signal-attachment-2020-04-16-154310](https://user-images.githubusercontent.com/15697729/79499968-bb0d0b80-7ff9-11ea-9714-876dd0772d3a.jpeg)

### Device info

**Device:** Samsung SM-G970U
**Android version:** 10
**Signal version:** 4.58.5

### Link to debug log
My Debug logs
https://debuglogs.org/86e6a9833720dc2c3bf67df6db4fbe80ca6fd7282bdbc626a2ee20bb803e8c30
Call Partners logs
https://debuglogs.org/bf778cdabb311c1e1e2541b8304e42120e9c0a8a6c2c8789613b5d87fdfec488

**Comment by happychameleon** [comment]
Just saw that ringrtc was Bumped to version to v1.3.1, supposedly "Fix issue preventing some calls from ringing" so perhaps that may fix my issue?!

**Comment by szotsaki** [comment]
This is most likely a duplicate of https://github.com/signalapp/Signal-Android/issues/7733. Could you please close this one in favour of that? Thank you.

**Comment by happychameleon** [comment]
Actually this bug has been fixed for me (There were some issues with other people on British mobile network, which i think had something to do with ipv6 not sure if this is why its solved for me), anyhow will gladly close the report
