### ISSUE TITLE
"Save to storage" does not use a Device Folder

### ISSUE THREAD

**Issue by alugowski** [signalapp/Signal-Android#9547]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Save feature dumps photos into the `Pictures/` directory without using a Device Folder.

Other apps self-organize by using a subdirectory with their own name, aka Device Folders. Photos saved from Signal do not follow this pattern, resulting in a mess.

The solution is to simply add `Signal/` to the path for saved attachments: `Pictures/Signal/`.

### Steps to reproduce
- Select a photo in a signal message.
- Select "Save" from the hamburger menu
- Accept the warning that the saved file will be unencrypted

**Actual result:** The individual photo is saved as `/storage/emulated/0/Pictures/signal-{datetime}.jpg`
**Expected result:** The saved photo should be located in `/storage/emulated/0/Pictures/Signal/signal-{datetime}.jpg` instead. 

### Screenshots

![Screenshot_20200416-214258](https://user-images.githubusercontent.com/2730364/79533687-54094a00-802d-11ea-8f08-2725ab3934af.png)

### Device info

**Device:** Pixel XL
**Android version:** 10 (stock)
**Signal version:** 4.58.5

**Comment by Valeryan24** [comment]
Hi,
I use Signal and make a monthly donation, thanks for your good work !

I fully agree with this issue and would like if possible that you add a feature to choose in which folder we can save a picture on Android.

On a chat, when I launch a picture sent and want to store it on my phone - I understand it will decrypt it - the image is automatically saved in "Pictures" folder.
But I don't like that, it pollutes my folder, then I have to move all of them with my Gallery app.

I'd rather prefer :
- have a permanent option in the Settings of Signal app to choose another one, for example a sub-folder "Signal" inside "Pictures"
- or being prompted to choose on which folder I want to save it, then keep the same choice for the next save

I know you want an application as simple and secure as possible, and Signal is meant to protect data - but as the possibility exists to save media on the phone, we should be able to decide in which default folder !

**Comment by alugowski** [comment]
Yes this is still relevant.

It should also be a super quick and easy change. Just change the save path from "Pictures" to "Pictures/Signal", possibly with an mkdir call.

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by Valeryan24** [comment]
Hi, already done… since 4 years, without any answer nor implementation from Signal ! ;)

https://community.signalusers.org/t/save-pictures-to-pictures-signal-instead-of-pictures-or-configure-where-media-attachments-are-saved/2699

**Comment by alugowski** [comment]
> Please use the community forum for feature requests https://community.signalusers.org/

Hi Alex,

This was a bug report. Signal is the only app that scatters photos all over the Pictures directory without any organization. No complicated features needed, just change the default path to match what every other app does.

A quick glance suggests simply replacing "Pictures" with "Pictures/Signal" and "Movies" with "Movies/Signal" in `file_provider_paths.xml` would fix this. I don't have a way to test this change hence why I'm not submitting a PR.

https://github.com/signalapp/Signal-Android/blob/44d014c4459e9ac34b74800002fa86b402d0501c/app/src/main/res/xml/file_provider_paths.xml
