### ISSUE TITLE
In notifications and in conversation emoji are different

### ISSUE THREAD

**Issue by primarto** [signalapp/Signal-Android#9553]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In notifications and in conversation emoji are different

### Steps to reproduce
Receive emoji, open notifications and and after open conversation you will see the difference

**Actual result:** emoji are different
**Expected result:** emojis are the same

### Screenshots

![10](https://user-images.githubusercontent.com/62907157/79899894-555bbd80-8405-11ea-9ab7-96398908b3e7.jpg)
![9](https://user-images.githubusercontent.com/62907157/79899910-58ef4480-8405-11ea-88aa-63473f8965b5.jpg)

### Device info

**Device:** Xiaomi Redmi Note 4X
**Android version:** 7.0
**Signal version:** 4.58.5

### Link to debug log
 Not required

**Comment by u32i64** [comment]
This doesn't look like a bug to me. AFAIK Signal can't control the emoji font in notifications, so your system one is always used. Inside of Signal, the situation is different. See [Why are the emoji on Signal Android different from the other apps on my phone?](https://support.signal.org/hc/en-us/articles/360017561992-Why-are-the-emoji-on-Signal-Android-different-from-the-other-apps-on-my-phone-) for details.
