### ISSUE TITLE
[Feature request] Multi-forward

### ISSUE THREAD

**Issue by darkman088** [signalapp/Signal-Android#9554]
Hello,

please apologize, if this is not in the right section, but I really need to submit this feature request.
Currently, forwarding a message in Signal is a one to one relationship.
Meaning, you can forward ONLY one message, to ONLY one of your contacts.
However, in real life, it is oftentimes necessary to "broadcast" many messages to a couple of
contacts. Hence, I REALLY don't see a reason, why when I select more than 1 message, the forward
button just disappears !!!
So, PLEASE implement a simple feature - the possibility to select several messages, then FORWARD
them by clicking the button and selecting numerous contacts, to which you would like to forward the message.
Several messengers have this option since quite some time, so I see no reason why THE BEST messenger app still doesn't have it !!

Many thanks in advance!

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
