### ISSUE TITLE
[Feature request] Visible notifications from another contact

### ISSUE THREAD

**Issue by darkman088** [signalapp/Signal-Android#9555]
Hello,

please apologize, if this is not in the right section, but I really need to submit this feature request.
Actually, I ALREADY have submitted this request about 2 years ago, but nobody paid attention to me!
I have the problem, that when I am chatting with somebody and I have banners and sound turned off,
I can NEVER realize, that somebody else has sent me a message !!
I have noticed, that other messengers are showing a number for the amount of new messages
received from other contacts on the top left, together with the arrow to go one screen back (to the contact list).
This should be a quick cosmetic job, so I see no reason why THE BEST messenger app still doesn't have this feature !!

Many thanks in advance!

**Comment by alex-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/
