### ISSUE TITLE
Call cancels if local mic muted before call is answered

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9558]
If local user mutes the microphone before remote answers the call, the call is cancelled.

### Steps to reproduce
- Start call via voice or video button (I tested calling to Signal iOS).
- Mute microphone before remote answers the call.

**Actual result:** Call ends.
**Expected result:** Call connecting/ringing continues. Notably Signal iOS behaves this way (e.g. when calling Signal iOS -> Signal Android).

### Device info
**Device:** Google Pixel 3 XL
**Android version:** 10
**Signal version:** 4.59.0

### Link to debug log
https://debuglogs.org/f980f9f34226bcb5aab22066128ac2e9f1960da01f0a692aae88d1be55e44ac3

**Comment by cascheberg** [comment]
Same issue as #9421, has pending pull request #9464

**Comment by alex-signal** [comment]
Hi, a fix for this was put into place in `4.59.1` which should be making its way to beta users fairly soon. Please check against that build to verify proper behavior. (Note of course this will only fix the issue for outgoing calls from an Android device)

**Comment by u32i64** [comment]
Looks like it has indeed been fixed. Thanks!
