### ISSUE TITLE
Disappear contact photos

### ISSUE THREAD

**Issue by ikanakova** [signalapp/Signal-Android#9560]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since update to version 4.59.0 photos of contact with Signal disappeared and there is circle with letters instead.

### Steps to reproduce
- updated to 4.59.0
- open Signal
- search contacts

**Actual result:** Missing photos set in Google contacts.
**Expected result:** Restore photos.

### Device info

**Device:** Nokia 6.1
**Android version:** 10
**Signal version:** 4.59.0

**Comment by ikanakova** [comment]
4.59.1 seems fixed this issue.

**Comment by u32i64** [comment]
4.59 switches to prefer contacts' profile pictures over system contact ones. There was a bug where in some cases if a profile picture was missing, the system contact one wasn't used, so the initials fallback was used instead. That has been fixed in 4.59.1.

**Comment by corrupt** [comment]
Sorry to comment on a closed issue, but will there be an option to choose, which photos we prefer? Suddenly seeing people's signal profile pictures over my carefully selected ones in the contacts app was really bugging me out for a couple of days. Now things seem to have reverted to the old system of showing system-wide contacts pictures first. But if you plan to go back to displaying signal contact photos, please give us an option to switch back to system-wide ones.
