### ISSUE TITLE
Emojis in emoji picker cut slightly off

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9561]
It looks like there's some issue in cutting the emojis. Notice the thin line:

![](https://user-images.githubusercontent.com/19972511/80126188-69d1be80-859b-11ea-979c-a9f5268e9e1c.png)

Here the rounded square-shaped emojis also don't look quite right (in addition to the line as well):

![](https://user-images.githubusercontent.com/19972511/80126223-748c5380-859b-11ea-905d-cff88a375229.png)

These issues can also be seen in other emojis, but it looks like it is a generic issue that affects every one of them?

### Device info

**Device:** Pixel 3 XL
**Android version:** 10
**Signal version:** 4.59.1

**Comment by pankarlox** [comment]
https://github.com/signalapp/Signal-Android/issues/8651# A small flaw, but it has been annoying me for over a year, unfortunately. 🙄

**Comment by u32i64** [comment]
Closing in favor of #8651.
