### ISSUE TITLE
[Feature Request] It would be great to optimize the app layout for landscape mode

### ISSUE THREAD

**Issue by alien2003** [signalapp/Signal-Android#9563]
It would be great to be able to see both roster and chat window at the same time in landscape mode, like in Conversations messenger.
![image](https://user-images.githubusercontent.com/11610652/80281078-5a748180-8711-11ea-989c-0c45d2f82541.png)

It would be veeery nice addition for landscape-only devices (Cosmo Communicator, Gemini PDA)

**Comment by Tursko** [comment]
Please put feature requests on the forums. This is only for issue tracking. 

`
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
**- [ ] This isn't a feature request or a discussion topic**
`

https://community.signalusers.org/c/feature-requests/android-feature-requests/18
