### ISSUE TITLE
Call audio not automatically switched to speaker when turning on video.

### ISSUE THREAD

**Issue by Salt505** [signalapp/Signal-Android#9565]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you start a video call, or when you turn on your camera during a call, the call audio doesn't automatically switch to the speaker. 

### Steps to reproduce
- Answer a video call
- Notice that call audio is still coming through earpiece
or
- Turn on video during normal call
- Notice that call audio is still coming through earpiece

**Actual result:** Call audio still comes through the earpiece when you enable video
**Expected result:** When accepting a video call or enabling video during a call, the call audio should automatically switch to the speaker, not the ear piece.

### Device info
**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 4.59.3

**Comment by Sgn-32** [comment]
Should be solved with the new calling UI from 4.60.
