### ISSUE TITLE
Specific images don't send properly

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9570]
Devices:
- **A.0**: Google Pixel 3 XL, Android 10, Signal `4.59.5`. [Debug log](https://debuglogs.org/5883fb59ec56cefdd308d132f53229d9bbbcdd8b1afc6fd1a4665650a93078da).
    - **A.1**: Arch Linux, Signal Desktop `v1.34.0-beta.1`. [Debug log](https://debuglogs.org/60547e5dedcf1af67d0eae1894bb8459d5d775e678631186483c26c44f87d678).
- **B.0**: iPhone SE, iOS 13.5 public beta 2, Signal `3.8.0.34`.
- **C.0**: iPhone
    - not sure if there are linked devices

Conversations:
- **X**: 1:1 **A** with **C**. DM disabled.
- **G**: Group (v1), members: **A**, **B**. DM timer 1 hour.

Media album sent from **A.0** doesn't show on **C** and on **A.1**. It happens only with 6 specific images. They fail to send properly in any way, while the same images sent via **A.1** (uploaded to and downloaded from Firefox Send or Google Photos) work as expected.

How I got these images:
- Captured with Signal camera on **B.0**.
- Sent in a media album from **B.0** to **A** via **G**.
- Tapped "Download" icon manually because sender is not in system contacts.

Actual sending:
- Forwarded the media from **A.0** to **C** (in **X**).
- Also in **G** I tried saving images on **A.0** and sending (all, some, or by one — not all of this is captured in logs) by choosing them from system gallery.

**Actual result:** The sent media album is invisible (or no message at all if there's no more content).
**Expected result:** Media visible on all devices.

<details><summary>A.0 Screenshots of X</summary>

![](https://user-images.githubusercontent.com/19972511/80723137-e834e000-8b08-11ea-83ed-76db9e1084f5.png)
![](https://user-images.githubusercontent.com/19972511/80723061-c9cee480-8b08-11ea-83dd-38d811fa861f.png)

</details>

<details><summary>A.1 Screenshot of X + message timestamps</summary>

Human-readable time is in UTC+3:

Message # | Sent | Received
---|---|---
1 | `11:18 AM (1588234681825)` | `11:19 AM (1588234746141)`
2 | `4:09 PM (1588252165503)` | `4:09 PM (1588252170271)`
3 | `4:12 PM (1588252324055)` | `4:12 PM (1588252371888)`
4 | `4:13 PM (1588252401040)` | `4:13 PM (1588252401022)`
5 | `4:18 PM (1588252707120)` | `4:18 PM (1588252707120)`

![](https://user-images.githubusercontent.com/19972511/80717873-17941e80-8b02-11ea-9687-9bc19f041eda.png)

</details>

**Comment by greyson-signal** [comment]
Thank you for the very detailed bug report! Knowing that the media was forwarded was able to help me track down the bug. It should be fixed in the upcoming 4.59.6 release.
