### ISSUE TITLE
[Beta] Alphanumeric Pin is always invalid

### ISSUE THREAD

**Issue by TheJoYo** [signalapp/Signal-Android#9576]
The android app has been constantly reminding me to validate my alphanumeric pin.
On correct entry it always fails.

Changing the pin to numeric fixes the issue.

https://debuglogs.org/1afd5d7551b0ce9272de9d67f4dc4445f08945b5661f31cbb083a87fd7af8f60

**Comment by greyson-signal** [comment]
Are you using the stock keyboard? I'm unable to reproduce this on the same device.

**Comment by alan-signal** [comment]
We believe this is resolved now, can you please confirm?
