### ISSUE TITLE
Cannot switch back to Bluetooth headset

### ISSUE THREAD

**Issue by samhatoum** [signalapp/Signal-Android#9581]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When connected to a headset and I answer a call, Bluetooth works. If switch to speaker and then back to Bluetooth, the call stays on speaker. I have to hang up and call again to resume Bluetooth connectivity.

I'm using Google buds 2. Had the same issue with Google buds 1, and a Bose QC3 headset. Same issue happened with my Pixel 3 XL and now this Pixel 4 XL. Could be Pixel specific, I haven't tried another Android phone.

### Steps to reproduce
- connect Bluetooth headset
- call someone
- talk on Bluetooth for a few seconds
- click speaker icon
- talk on speaker for a few seconds
- click the Bluetooth icon

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The call stays on speaker even though the Bluetooth icon is selected.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The call should switch back to the Bluetooth headset.

### Screenshots

![Screenshot_20200503-081016~2](https://user-images.githubusercontent.com/2021955/80913853-c2305b00-8d15-11ea-8abd-f46185948974.png)

### Device info

**Device:** Pixel 4 XL
**Android version:** 10 (build QQ2A.200405.005)
**Signal version:** 4.58.5

### Link to debug log
I tried to do this but it said "failed to submit debug log". Tried to copy/paste manually but no option to do so.

**Comment by Sgn-32** [comment]
With 4.60.8 there was a new [commit](https://github.com/signalapp/Signal-Android/commit/cd1bad0718fb23ddcab06f445a8e9502170e4069) for bluetooth behavior.
Does this solve the problem for you?

**Comment by samhatoum** [comment]
Yes it did thank you, though I found a new issue with switching when connected to multiple devices. So if I'm in the car and I have both my headset and car connected, I can't seem to switch between bluetooth devices. I'll raise a new ticket
