### ISSUE TITLE
Always 2 backup files

### ISSUE THREAD

**Issue by diogodh** [signalapp/Signal-Android#9582]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal always has 2 backup files in Backup folder, from day 0 and day -1

### Steps to reproduce
Just create an automatic backup and check the number of backup files after 24h

**Actual result:** 2 backup files from day 0 and day -1
**Expected result:** 1 backup file from day 0

### Device info
**Device:** OnePlus6 (8GB)
**Android version:** 10 (OxygenOS 10.3.3)
**Signal version:** 4.59.6 (happened in every single version I used before)

### Link to debug log
Not needed

**Comment by Genis-Sage** [comment]
hey @diogodh 
that's not a bug but intended behaviour

also, this is more or less a duplicate of #7650

**Comment by diogodh** [comment]
You are right. My bad on the search, I did the search but someone i missed that. Maybe cause i was looking for duplicate and backup and missed that one.
Solved. Thank you
