### ISSUE TITLE
Sent Video with low frame rate and high contrast

### ISSUE THREAD

**Issue by diogodh** [signalapp/Signal-Android#9583]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sent videos appear with very low frame rate, pixelated and high contrast.
A simple video of plants moving with the wind is transformed in a low frame rate pixelated video, and increases contrast.

### Steps to reproduce
- Send a video with significant movement to yourself, it can be a simple 10Mb video, 720p (as example). After sending, watch it and will be as said before.
If you watch the same video on your gallery, it will be perfect.

**Actual result:** 
Very low frame rate, pixelated and high contrast.

**Expected result:** See the video just as you see in your gallery.

### Screenshots
Signal:
![Screenshot_20200503-181413](https://user-images.githubusercontent.com/18470550/80920842-52988b00-8d6a-11ea-83a6-2bd6edc555fb.jpg)

Gallery:
![Screenshot_20200503-181434](https://user-images.githubusercontent.com/18470550/80920846-57f5d580-8d6a-11ea-9f1a-fb67c65c29cb.jpg)

### Device info
**Device:** OnePlus6 (8GB)
**Android version:** 10 (OxygenOS 10.3.3)
**Signal version:** 4.59.6 (this problem only appeared a few weeks ago, before that was ok)

### Link to debug log
https://debuglogs.org/205d99bf078fdcf88a7ed05a2984b386920f0064fff34ab71345a106aa79ae7f

**Comment by repentsinner** [comment]
Agreed that video sending has changed to a more compressed format in a recent (~2020 sometime) version of Signal. I'm not sure the best way to roll back versions via the Play Store to figure out which.
