### ISSUE TITLE
Why sending text messages over internet delayed until photos are sent

### ISSUE THREAD

**Issue by aminevsaziz** [signalapp/Signal-Android#9585]
I would like to know why signal doesn't send messages I mean text based using internet to recipient until media such as video/gif/images are sent first. Don't you think that defy the purpose of one thing at time and keep waiting for 15min until video is done uploading (assuming that 4G internet is garbage in some locations on Earth)

**Comment by Genis-Sage** [comment]
hey @aminevsaziz 

the Github issue tracker is reserved for bug reports

if you want to discuss such things, you should go to the community forum:
https://community.signalusers.org/

you could also post in this existing thread, even if it's on receiving side:
https://community.signalusers.org/t/stuck-blocked-messages/3394

**Comment by sirius-c** [comment]
A friend of mine has a similar issue, sending a large file blocked messaging with Signal until the file was sent (two hours), and there is apparently no 'Cancel sending' button. I consider this a substantial usability flaw, as good as a bug.

**Comment by aminevsaziz** [comment]
@sirius-c this issue always bothered me. I searched for long time but I didn't find the reason why such thing is happening.

**Comment by Genis-Sage** [comment]
but still, Github is the wrong place for discussions

discussion should happen on the community forum
