### ISSUE TITLE
Messages Only arriving on Desktop

### ISSUE THREAD

**Issue by storrgie** [signalapp/Signal-Android#9586]
As of 2020/05/01 I'm only seeing messages on signal-desktop (Fedora 32, signal desktop via flathub). My phone (Android Pixel 3, Signal 4.59.6) can send messages to other signal users, and I can see those messages on signal-desktop, but any response to those messages only arrives on signal desktop.

Restated:
 - signal-android can __send__ messages (confirmed receipt by other users)
 - signal-desktop can __send__ and __receive__ messages (confirmed receipt by other users)
 - signal-android seems to not __receive__ any messages unless they are SMS
 - __no signal messages arrive on phone__, both 1:1 and group

Wife is on same platform (Fedora 32, signal-desktop via flathub) and phone (android pixel 4, signal 4.59.6) and is not seeing the same issues.

Troubleshooting:
 - I have tried to disable and re-enable messages and calling on my number (which triggered re-linking signal-desktop). 
 - I have also reset secure session on both mobile and desktop.

I am noticing that signal-android is crashing periodically, it's not allowing me to back up my messages (crashes while backing up). Which is preventing me from clearing the data/cache for signal on my phone. Please see attached logs

Desktop Debug Log: https://debuglogs.org/78a6370755f191994d5f6ce3f2a292eada43bbe3b6abb9441d287bbf7db8833f

Mobile debug Log: https://debuglogs.org/c854612749aad7340abd320ab9beb269b11ff92c012fada3361864b2a34928b1

**Comment by guimspace** [comment]
I started experiencing this issue with version 4.59.9. Could it be related with DNS settings? I use 1.1.1.1 and a few hours before the update to 4.59.9, 1.1.1.1 received an updated (5.3 977). Adding Signal to the exception list of 1.1.1.1 (with Warp) solves the issue.

Debug log: https://debuglogs.org/a0529207bc3ba845ee434c941ed1302483fc2730ceb86718aa164fd4b1b22c75

**Comment by storrgie** [comment]
I moved from LTE (google fi, whatever mvno they were backing me with at the time) to my own network several times (1.1.1.1)

**Comment by jeremymasters** [comment]
I'm starting to get this too where messages don't show up on my android client sometimes. Was chatting on the desktop and three messages just don't show up on Android but are fine on desktop. 

Android log
https://debuglogs.org/8606bcdfced652d3dd49f4c4c52213682eea1823384473e3ce8578475527b5e7

**Comment by jeremymasters** [comment]
This is happening more now...
https://debuglogs.org/e27aea04a3eab97d16eb024b04d9a76ac3e3fdbf0fc7291902eded8db0e95911

**Comment by greyson-signal** [comment]
@storrgie Your specific issue should be solved in 4.59.9. It had to do with getting stuck processing a bunch of backed up read receipts.

For those of you experiencing issues related to 1.1.1.1, I find that slightly strange, given the DNS changes we made only change network behavior if we fail using the default system DNS, so nothing should really be changing unless you were having network problems before. But I can try to dig into it more.

@jeremymasters Let me know if this is still happening on 4.59.9.

**Comment by jeremymasters** [comment]
@greyson-signal I don't see it happening but I think it might have had to do with thread trimming too perhaps.  I also turned that off and it's not happening so far.  Certainly a confusing thing.

**Comment by jeremymasters** [comment]
The problem seems to have gone away for me as of 4.60.6 I believe
