### ISSUE TITLE
Signal gets laggy and crash until force closes

### ISSUE THREAD

**Issue by diogodh** [signalapp/Signal-Android#9588]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For the second time in 2 days, suddenly at about 01:00 (backup time is nearly at 23:00, takes 7gb and it's finished at 23.05), while chatting, not charging, signal becames slower and slower untill gets totally unresponsive and only solves a force close (not a normal close).

### Steps to reproduce
- while chatting
- at about 01:00

**Actual result:** slower and slower (laggy) until becomes totally unresponsive.

**Expected result:** working normally as it does normally during the day

### Device info
**Device:** OnePlus 6 (8Gb)
**Android version:** 10 (OxygenOS 10.3.3)
**Signal version:** 4.59.6

### Link to debug log
https://debuglogs.org/918b568d880f441e171c654f65f2cc7fddda267dab20e230f1c25cbce84a23d9

**Comment by EukalyptusX** [comment]
Yes, we need more of those issues!
The devs ignore this issue for months already.

See
https://github.com/signalapp/Signal-Android/issues/9240
https://github.com/signalapp/Signal-Android/issues/9251
https://github.com/signalapp/Signal-Android/pull/9221

**Comment by diogodh** [comment]
Btw, In OnePlus, disdabling the feature RAM Boost, improved the problem

**Comment by EukalyptusX** [comment]
![Screenshot_20220128-193455](https://user-images.githubusercontent.com/42608576/151603172-86ec1c03-1adb-46f0-9828-0038649daa3f.png)

**Comment by EukalyptusX** [comment]
Still not fixed.

**Comment by alex-signal** [comment]
Hi! This is likely something slowly eating away at memory. Do you mind posting new logs? The old logs have expired and no longer exist on the server.

Unfortunately, memory issues are hard to sus out due to a lot of device or usage specific issues that could be causing them. However, we did recently add in some changes to hopefully reduce some memory usage (making sure some references were cleared up).
