### ISSUE TITLE
Signal 4.58.5 creates backups it cannot restore: "Cannot restore backup from newer version of Signal"

### ISSUE THREAD

**Issue by yareckon** [signalapp/Signal-Android#9590]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal for Android 4.58.5 currently creates Backup archives that cannot be restored by the same version.

### Steps to reproduce
 - I created a backup at 22:43 European Central Time to my Internal Storage on Signal 4.58.5, and uninstalled Signal to try to fix notification issues.  I also backed up the file to an external drive.  
- When reinstalling and importing the file, the app accepts the password I type, then returns to the restore screen with the (fading in an out) message "Cannot restore backup from a newer version of Signal".  This string may not be verbatim, as I haven't been able to copy the fading toast.

Perhaps some code / version numbers from the Beta version got into the Production release?

The Exception in the debug log is: 
FullBackupImpoter$DatabaseDowngradeException: Tried to import a backup with version 61 into a database with version 55

### Device info
**Android version:** 9.0.0 / LineageOS 16.0
**Signal version:** 4.58.5

### Link to debug log
Debug logs are currently failing to submit from the device.  However the relevant lines state: 
FullBackupImpoter$DatabaseDowngradeException: Tried to import a backup with version 61 into a database with version 55

**Comment by yareckon** [comment]
What is odd is that those two Database structure versions correspond to the DATABASE_VERSION constant in version 4.58.5 and in master as of right now -- is this too much of a coincidence?  Do I just have a bad backup with the strangest cooincidence that it was written with a version that exists only in the current master code?

**Comment by yareckon** [comment]
Aha, or are people being opted into the Beta channel on Google Play without signing up consciously?  Could it be that my phone was updated earlier today to a beta version that had database version 61?  I didn't know the beta program existed before 5 minutes ago...so it wasn't purposeful.  Maybe someone should check if the beta versions are leaking into the main population, or the main population is being signed up by accident?

**Comment by yareckon** [comment]
After joining the Beta program on Google Play, restore works fine.  I can only conclude somehow that the Beta program on Google Play is leaky...
  
While my issue is closed, it might make sense for a developer to think about the implications of that for a sec in case you need to check something.

Thanks for all of your work.

**Comment by uncebobo** [comment]
Verified here also. Lost all data with this latest update. backup is missing

**Comment by yareckon** [comment]
I'm not sure that is the same issue, frankly.

**Comment by greyson-signal** [comment]
@yareckon We do staged rollouts for production releases through the Play Console. So we release to, say, 2% of users, then 10%, 25%, etc. It's possible that you were upgraded, then uninstalled, then reinstalled to an older version. The weird thing is that the Play Store is supposed to make sure you get the same version if you're signed in with the same google account. Maybe you re-downloaded the app with a different account? Couldn't say. But glad you got it sorted out!

**Comment by philipmobrien** [comment]
> After joining the Beta program on Google Play, restore works fine. I can only conclude somehow that the Beta program on Google Play is leaky...
> 
> While my issue is closed, it might make sense for a developer to think about the implications of that for a sec in case you need to check something.
> 
> Thanks for all of your work.

Yes, worked for me too, thanks.

**Comment by yareckon** [comment]
Yes, there was a different google account in use on the new phone, so restoring backups is going to intermittently be a problem for folks who change google accounts and get an older version than their old phone had.  Maybe worth documenting deep in a FAQ.

**Comment by philipmobrien** [comment]
Maybe worth documenting less deeply ;-)

I used two Google accounts on my old phone, but only one on the new - clearly not the one linked to my Signal installation.

But that said, your bug report here came up with a very quick search, so that's a good start.

**Comment by goretkin** [comment]
I am running into this now. Despite being logged into the same Google account, I am not seeing the same app information, and I'm trying to restore a backup from

(output of [`adb dumpsys`](https://stackoverflow.com/a/11943078/415404))

```
  Package [org.thoughtcrime.securesms] (c26e2b6):
    userId=10079
    pkg=Package{4662bb7 org.thoughtcrime.securesms}
    [...]
    versionCode=93702 minSdk=19 targetSdk=30
    versionName=5.24.17
```
to

```
  Package [org.thoughtcrime.securesms] (855d5fa):
    userId=10255
    pkg=Package{d1a77ab org.thoughtcrime.securesms}
    [...]
    versionCode=93402 minSdk=19 targetSdk=30
    versionName=5.24.14
```

**Comment by kgollmer** [comment]
I had the same problem too, joining beta fixed this also. I didn't change google accounts, there seen to be pixies at work.

**Comment by Peeeet** [comment]
Having the same problem now.  Also WiFi direct transfer method didn't work, probably for the same reason.  There should be a warning when using the WiFi direct transfer method if the versions don't match.

**Comment by Peeeet** [comment]
Using the beta signup idea did not work.  Can not currently transfer my Signal app history / backup between a Samsung Galaxy S21 and a Galaxy S23 sitting right next to eachother.  Tried uninstalling and re-installing Signal on the new phone but the new phone only gets version 6.11.7 from the Google Play Store no matter what I do despite the old phone already having 6.12.5 installed also from the Google Play Store on it.  This is a pretty serious bug IMHO.

**Comment by nicholas-signal** [comment]
>  the new phone only gets version 6.11.7 from the Google Play Store no matter what I do 

We share your frustration in inconsistency of delivery by the Google Play Store. With any luck, 6.12.6 should be available on the Play Store. However it is also available immediately and directly from our official website: https://signal.org/android/apk/

**Comment by crasm** [comment]
I was just affected by this when I had to reinstall today. Updating to the beta resolved it.
