### ISSUE TITLE
Signal asking for registration again, verification code not working

### ISSUE THREAD

**Issue by Booteille** [signalapp/Signal-Android#9596]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just updated Signal to the last version (4.59.8) and the app told me the app is not more registered and I need to register it again.
Unfortunately, I was unable to register. Each time I was typing the code received by SMS, Signal didn't recognize it and finally said I should try again next day.
Now, Signal is saying it can't connect to the service when I am asking to send a verification code.

### Steps to reproduce
- Update Signal to 4.59.8
- Try to register again
- Ask for the verification code
- Fill the code and validate

**Actual result:** Signal does not recognize the verification code and is no longer able to connect to verification services
**Expected result:** I would expect to verify properly the code or to just don't have to register again my device.

### Device info

**Device:** One Plus 3T
**Android version:** 9 - MicroG LineageOS 16
**Signal version:** 4.59.8

### Link to debug log
https://debuglogs.org/18fd53d977c71a9d033870600981bfe5de87f80307823dadeb6471f4c9e4538f

**Comment by Booteille** [comment]
I just tried again and I was able to register properly.

I keep the issue open so you can investigate what happened.

**Comment by uncebobo** [comment]
Verified. Same here. Complains about google play service. Signal has become useless to me now.
I DON'T USE GOOGLE PLAY! I REFUSE!
Can not use desktop app.
A supposedly secure message app should surely not be dependent on  google

**Comment by uncebobo** [comment]
App updated. Registered again but now All data is now gone!

**Comment by ronidee** [comment]
Confirmed on LOS17.1 with no play GSF installed.

SMS activation didn't work, **but calling did**. Maybe it helps others

**Comment by Booteille** [comment]
Just to keep informed. 
Since the last update, I don't get notified by new messages if I don't open the application. The application is running in background. Battery optimizations are disabled.
Nothing changed on my phone except I updated Signal.

**Comment by greyson-signal** [comment]
Merging discussion into #8992
