### ISSUE TITLE
Importing SMS from Default app sends all failed messages in old threads

### ISSUE THREAD

**Issue by Armestam** [signalapp/Signal-Android#960]
My friend installed TextSecure today, and imported his threads from his stock messaging app.  TextSecure went ahead and re-sent every failed text message from this history of his previous app, resulting in a hilarious spamming of many people he is in contact with. 

Maybe a flag should be added when importing threads to not attempt to send failed messages?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
