### ISSUE TITLE
Unsafe cryptographic encryption patterns in method deriveAccessKeyFrom

### ISSUE THREAD

**Issue by muncescu1** [signalapp/Signal-Android#9600]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have built and uploaded the Signal app to google play for testing purposes. After analysis the google play console issues the following alert.

```
Security alert

Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

Vulnerable classes:

org.whispersystems.signalservice.api.crypto.UnidentifiedAccess.deriveAccessKeyFrom
```
It seems according to the google link [https://support.google.com/faqs/answer/9450925](url), 
that the issue is because of the statically computed salt or initialization vector. Which is true if we look over the code:

```
public static byte[] deriveAccessKeyFrom(ProfileKey profileKey) {
    try {
      byte[]         nonce  = new byte[12];
      byte[]         input  = new byte[16];

      Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(profileKey.serialize(), "AES"), new GCMParameterSpec(128, nonce));

      byte[] ciphertext = cipher.doFinal(input);

      return ByteUtil.trim(ciphertext, 16);
    } catch (NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | InvalidAlgorithmParameterException | BadPaddingException | IllegalBlockSizeException e) {
      throw new AssertionError(e);
    }
}
```

### Steps to reproduce
 Upload the signed apk to play store.

My question is how did you publish the app ? Since this does not allow you to do this, and how can you circumvent this, because the code just masks the profile key, and you can't rely get around it.

**Comment by muncescu1** [comment]
Bump!!! Any thoughts on this issue ?

**Comment by alan-signal** [comment]
Please do not [bump issues](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues).

> uploaded the Signal app to google play for testing purposes

You should be able to do all the testing you want locally **without** uploading to the playstore.

Closing because this is not a bug report but a question. Please feel free to ask questions on the [forum](https://community.signalusers.org/).

**Comment by muncescu1** [comment]
So what you are saying is that the warning from google "Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details." is not an issue ?

**Comment by alan-signal** [comment]
This function is used for key derivation from the profile key, which is used with AES-GCM elsewhere. The nonce is fixed so that the derivation is deterministic.

The alert is a false positive.
