### ISSUE TITLE
Reduce/mute music volume when recording voice message

### ISSUE THREAD

**Issue by kobelobster** [signalapp/Signal-Android#9601]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

This issue https://github.com/signalapp/Signal-Android/issues/5914 was closed when you guys did the issue clean-up and closed many issues. It was also referenced in https://github.com/signalapp/Signal-Android/issues/7569

The issues in there contain information what is required. I can provide some extra information, however, this issue is merely for showing that this is a feature that is still requested by some users and I would like to add it to the feature requests.

I could volunteer to look at this issue, however I don't have any experience in android development (only 6-12 months) and am more active in the field of c# (professional) and php (formely professional)

**Comment by Genis-Sage** [comment]
hey @kobelobster 

thanks for your interest

you don't need any allowvance from Signal devs to make a pull request about this


but if you want to discuss this feature request, please create a new feature request on the community forum, if there is no existing thread about it:
https://community.signalusers.org/

the Github repo for SIgnal-Android is only for bug reports as the template states
