### ISSUE TITLE
Default country code added to SMS numbers

### ISSUE THREAD

**Issue by werfive** [signalapp/Signal-Android#9602]
Let's begin with a checklist: 
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using Signal to send an SMS to a local mobile number, I enter the number without country code. The app automatically adds my country code to the local number. When I am not in my home country the SMS is sent to some wrong number in my home country.  This is insecure and costs additional mobile phone charges.

### Steps to reproduce
- click on pen icon to start new SMS
- enter the local mobile phone number, such as 0195xxxxxx
- select "New message to..."
- At this point my home country code to added to the number displayed at top of screen.
- type message, press send icon

**Actual result:** SMS is sent to +44195xxxxxx
**Expected result:** SMS is sent to 0195xxxxxx

### Device info
your info -->
**Device:** Blackview BV9500 PRO
**Android version:** 8.1.0
**Signal version:** 4.59.8

**Comment by igor2x** [comment]
Signal does not know in which country you are, it does not spy on your location, so it can't know where should it send the message, so it appends your registered country code.

You have two options:
1. Always prepend country code (I have all of my contacts saved with country code prefix).
2. Use some other SMS messenger that actually has access to your location.

**Comment by alan-signal** [comment]
> At this point my home country code to added to the number displayed at top of screen.

I am presuming your home code is +44.

So are you saying the app showed you `+44195xxxxxx` **before** you actually sent the SMS?

**Comment by Genis-Sage** [comment]
hey @werfive 
just wondering, what SIM card do you use?
are you changing your SIM card to a local vender when you are outside of UK, or do you keep your UK sim card?

**Comment by werfive** [comment]
Thanks igor2x, thanks alan-signal, thanks Genis-Sage
My home code is +44.
My phone has 2 SIM cards - I just set the default for sending SMSs according to where I am.
I've stopped using Signal for SMSs. Most of my contacts' details include their country codes, but not all. If I'm in a country and I send an SMS to a national number, SMS apps usual default to the local country. If I forget that Signal is different, my message may be misdirected without warning. So in this scenario, the default Google SMS app is more secure!
Thanks again for your responses.

**Comment by rasmus-pagh** [comment]
I think the app should be explicit about what country code is added, and ideally allow you to change the default country code. I started using Signal while living in the US, and did not notice that SMSs were not being delivered when I did not include a local country code for several months. How about simply expanding phone numbers to always include the country code?

**Comment by Eothred** [comment]
Is it correct behaviour to add country code at all though? This causes several issues for me.

Firstly I have a SIM card from my home country but live in another country, so the prefix added is always wrong. This is rather common in Europe in areas close to borders I believe. Numerous times I've made this mistake, most notably a problem if I have the contact registered without country prefix (then it says name so all looks correct in UI)

Second, in the country I live (Sweden) there is a concept called "short numbers" on the form 70123. Typically used for company advertisements etc. You can only send to these within the country and cannot add country code to it afaik. Only solution I came across is to temporarily switch SMS app, which is a shame considering how excellent Signal is for everything else.
