### ISSUE TITLE
Not working: Persistent background notification (non-GSF device) 

### ISSUE THREAD

**Issue by ronidee** [signalapp/Signal-Android#9605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The persistent notification, designed for non-GSF devices doesn't show up anymore, hence I don't receive any messages while the app is not open

### Steps to reproduce
- Update to version 4.59.8

**Actual result:** The persistent notification isn't being shown, no background messages are received.

**Expected result:** The persistent background notification gets created, enabling one to receive messages while Signal is not open.

### Device info
**Device:** Xiaomi RN-7
**Android version:** 10 (LineageOS17.1, no GApps/GSF)
**Signal version:** 4.59.8

### Link to debug log
I force closed the application and opened it again to make it try to create the notification. Hope it's in the log: https://debuglogs.org/dd3fc270c89b7726f302d05db42220fb844a43e3604731e6a91a923034ae6b4e

**Comment by quaxalber** [comment]
I am seeing exactly the same behavior. No more background / push notifications after updating Signal to 4.59.8. Completely reinstalled Signal several times. Only after a fresh install, I receive push notifications for a short time. But as soon as the background notification appears, I stop receiving new messages until i re-open Signal.

### Device info
**Device:** Xiaomi Mi Mix 2S (polaris)
**Android version:** 9 (LineageOS for microG 16.0 [16.0-20200319-microG-polaris], no GApps/GSF)
**Signal version:** 4.59.8

**Comment by ProjectMoon** [comment]
See #9578

**Comment by ronidee** [comment]
> See #9578

Hey sorry. I actually searched the issues for this but didn't see your issue. Again, I'm sorry for the duplicate. 🙈
