### ISSUE TITLE
Unread message get's read on archiving conversation, even when blocked

### ISSUE THREAD

**Issue by norpol** [signalapp/Signal-Android#9610]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If a contact sends you a message and instead of reading, you block them straight away, I would not expect them to receive a read notification in any case. What is worse: If you just "Archive" the conversation, the blocked sender sees the "read" check symbol, even though the message never got read.

### Steps to reproduce
- Alice sends message to Bob
- Bob blocks Alice by clicking onto the user profile picture => Block
- Bob archives conversation (without ever opening the Conversation)

**Actual result:** Alice sees a "read" notification for their message in the conversation with Bob
**Expected result:** Alice should not receive a read notification

**Comment by ronidee** [comment]
bump

**Comment by norpol** [comment]
I didn't know what the behavior was so I tried it out so yes I am sure.

**Comment by greyson-signal** [comment]
It's correct that we mark as read when archiving in general, but we shouldn't be sending read receipts to blocked contacts. We'll fix it, thanks!

**Comment by norpol** [comment]
Thank you, very much appreciated. Should I open another issue about mark as read when archiving in general? I think get why it is this way, though I believe that shouldn't be the case.

**Comment by norpol** [comment]
Thank you!
