### ISSUE TITLE
Ability to dismiss in app notifications such as "Create a PIN"

### ISSUE THREAD

**Issue by konomikitten** [signalapp/Signal-Android#9611]
Currently I see no way to dismiss the notifications in the contact list such as "Create a PIN" "Add a profile picture". Please add the ability to permanently dismiss these or disable them entirely.

**Comment by greyson-signal** [comment]
These are mandatory actions and cannot be dismissed by design.

**Comment by konomikitten** [comment]
> These are mandatory actions and cannot be dismissed by design.

Are you saying in the future it will be "mandatory" to set an individual pin for Signal rather than just using your phones security? Will the app eventually stop working if we don't follow these "mandatory" notifications?

**Comment by u32i64** [comment]
@konomikitten Setting up a Signal PIN will be mandatory, but it won't be used for accessing the app. For more information, see [the support article about Signal PINs](https://support.signal.org/hc/en-us/articles/360007059792).
