### ISSUE TITLE
Cannot read the SMS with verification code in signal during the registration process.

### ISSUE THREAD

**Issue by cladmi** [signalapp/Signal-Android#9614]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

After the last update I had to re-register my device with signal with an SMS.
But when reading the SMS with the verification code in signal, I cannot go back to the screen where I should type it.

So reading the sms in signal prevents me from typing the code.

### Steps to reproduce

- Have notification showing only name or nothing, or just do not read them as it is a workaround
- Signal is default SMS app
- Get in a state where you need to re-register your device
- Start the register procedure via SMS
- Read the verification from the SMS in signal
- Go back to the registration screen to type the verification code

**Actual result:** I can go back to the screen to enter the verification code
**Expected result:** Cannot go back to that screen

My workaround was to enable notifications with message content and read it from the notification bar.

**Comment by floss-birdy** [comment]
same here, i re-enabled stock messaging app and set it as default as a work around. if signal was the sms  app then it should have auto fill the otp .
