### ISSUE TITLE
"Create a PIN" prompt

### ISSUE THREAD

**Issue by ashafer01** [signalapp/Signal-Android#9617]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I got a large "Create a PIN" box unexpectedly today not correlating with an app update. This is very large and covers too much of my screen, unwanted, and not dismissable.

### Steps to reproduce
- Don't set a PIN
- Continue not setting a PIN for 2 days

**Actual result:** A large undismissable "Create a PIN" prompt appears
**Expected result:** The prompt should not appear or at least be dismissable.

### Device info

**Device:** Pixel 1
**Android version:** 8.1.0
**Signal version:** 4.59.9

### Link to debug log
n/a

### Other Findings

https://github.com/signalapp/Signal-Android/commit/bdd48fd2dfec4ea28352902c3811769d716b4ef8

I believe this is the result of a logic bug introduced here. See my comment on the commit.

**Comment by greyson-signal** [comment]
Hi there, this isn't a logic bug. I replied to the comment on bdd48fd.

Moving forward, everyone will have a PIN. That's why you're getting prompted to create one. You can learn more about PINs here: https://support.signal.org/hc/en-us/articles/360007059792-Signal-PINs

**Comment by ashafer01** [comment]
That's extremely tedious, and as I said, unwanted. If you insist on this please add biometric support.

**Comment by ashafer01** [comment]
Perhaps the document you linked just needs updating? Or maybe the feature just needs a better name? The document's description of what this feature is, how it's used, and how it works is very terse. And when I see "PIN" I think a small, re-used 4-digit number that I need in order to do _anything_.
