### ISSUE TITLE
Search fields always use system emojis

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9619]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The search fields (the one for one chat and the one for all chats) always use system emojis

### Steps to reproduce
- In a chat, click on the three dot menu and then on search
- Paste an emoji

**Actual result:** It's rendered as system emoji, even if system emojis are turned off in the settings.
**Expected result:** It's rendered as system emoji or Signal one, depending of the setting.

### Device info

**Android version:** 9
**Signal version:** 4.58.5

**Comment by u32i64** [comment]
Can confirm. Also, same behavior (always system emoji regardless of setting) is seen in the profile name of a user in a group chat (i.e. `+1 234 567 89 01 ~ ProfileNameWith👍` above member's message).

**Android version:** 10
**Signal version:** 4.59.9

**Comment by u32i64** [comment]
Same thing with the contact's name in the new calling UI.

**Android version:** 10
**Signal version:** 4.60.0

**Comment by mueller-ma** [comment]
Seems to be fixed.
