### ISSUE TITLE
Cannot get ride of the "Create a NIP" popup

### ISSUE THREAD

**Issue by hubyhuby** [signalapp/Signal-Android#9620]
### Bug description
As per the picture the "Create a NIP" popup cannot be removed.
It appeared yesterday and seems to want to stay here !
Please give us a button to kill it.

### Steps to reproduce
Install the app
Wait for ~1 month
Get stucked with the popup

### Screenshots
![signal-attachment-2020-05-13-085501](https://user-images.githubusercontent.com/26340942/81781332-3d54f680-94f8-11ea-905b-a761d165a864.jpeg)

### Device info
Android 8.0 Samsung a3 2017

**Comment by flaphoschi** [comment]
![Signal PIN](https://i.imgur.com/SOVH4Jf.png)

Do you mean that PIN stuff? I suggest, changing the title of the issue therefore, so it is discoverable in english language. First and foremost, I understand that there some people maybe want use that feature. Currently I don't want use it:  

- This message is not removable. It remains on my screen like an aggressive advertisement from a snake oil vendor
- If I got it right, Signal will ask me at random intervals about the PIN. That's sounds as bad as PSD2. people from europe maybe know what I mean. Suddenly your banking ask for TANs out of nowhere and you got scared to death.
- Purpose of the PIN is not explained in the client. And not well explained on the website. Signal is using SMS verification and doesn't provide a login. But now we have some kind of login?
- Good laptops and phones provide hard disk encryption, mine is already encrypted. So adding layers of encryption above it sound really paranoid
- Login to the device should be enough to use and unlock stored keys by system
- No mention in release not on Google Play

I see already people downvoting Signal on the Google Play.

**Comment by isaacnorman82** [comment]
Yeah this is really awful UI design, also the feature should be optional and better explained.  

I unlock my phone, which has encrypted storage, with a fingerprint, I don't need a daily recurring PIN request.

**Comment by alan-signal** [comment]
Hi,

This is not a bug but it is by design. Moving forward, everyone will have a PIN. That's why you're getting prompted to create one with no way to dismiss.

Thank you all for the feedback on this feature, the preferred place (because it's more visible) for that feedback would be the forum https://community.signalusers.org/

Related #9617

**Comment by marhry** [comment]
@alan-signal, could you please rethink the decision to make this mandatory? 
It's good to know that you are monitoring the forum. The influx of new users and especially high volume of replies in this thread: https://community.signalusers.org/t/mandatory-pin-without-clear-explanation-within-the-app-might-cause-significant-number-of-users-to-quit-using-signal

It looks to me like you got your user testing wrong and will upset a large part of your very loyal power user base while alienating the "normal" users they onboarded onto your platform. Please make the PIN and the cloud storage opt-in and not opt-out.

**Comment by hubyhuby** [comment]
@alan-signal 
I am un installing signal aswell.
I dont see the point in forcing people to use PIN if they don t want.
Whatsapp got popular BECAUSE you didn t need a password... I think your missing a point...your users.
Let me know if you rollback some day. Very sade for this project

**Comment by ckujau** [comment]
Unfortunately the answer here does not elaborate on the rationale behind this mandatory option. I understand that some people may want to have have this option, while others are clearly put off by the thought of remembering yet another PIN. No other chat program has a similar **mandatory** PIN dialog, only Signal does, and **without explaining why it's mandatory.**

And bug reports like this are exactly this: people consider this decision a bug. Closing it and [declaring it a feature](https://en.wikipedia.org/wiki/It's_not_a_bug_it's_a_feature "It's not a bug it's a feature") may not be a great way forward. So, **please** reconsider and either explain why this needs to be mandatory or reconsider and provide an option to make this popup go away.

**Comment by hubyhuby** [comment]
> Unfortunately the answer here does not elaborate on the rationale behind this mandatory option. I understand that some people may want to have have this option, while others are clearly put off by the thought of remembering yet another PIN. No other chat program has a similar **mandatory** PIN dialog, only Signal does, and **without explaining why it's mandatory.**
> 
> And bug reports like this are exactly this: people consider this decision a bug. Closing it and [declaring it a feature](https://en.wikipedia.org/wiki/It's_not_a_bug_it's_a_feature) may not be a great way forward. So, **please** reconsider and either explain why this needs to be mandatory or reconsider and provide an option to make this popup go away.

Dear @ckujau ,
I think it is even worst than that actually !
Signal and others are trying to make people migrate from whatsapp, facebook and others ....
Adding a PIN is killing any hope to bring the mainstream to SIgnal.
You are basically deciding to divide your base users by a factor 10X or 100X

Look any any of the booming technology its all about usability: Iphone, Wii, Whatsapp ... They are all increasing the number of people that can access the technology by a tremendouse factor.

I am unsubscibing this Bug; it makes me so sade. Have fun.

**Comment by greyson-signal** [comment]
All of this stuff has been discussed at length in the forum (with plenty of posts made by me and other employees), both in the [4.59 beta feedback thread](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-59-release/13409), as well as other separate threads I'm sure you'll find. I still hold that github is a bad place to hold discussions and notifies way too many people. So I'm locking this, but feel free to discuss more on the forum.
