### ISSUE TITLE
Signal crash on startup  (Recipient$UuidRecipientError)

### ISSUE THREAD

**Issue by JocelynDelalande** [signalapp/Signal-Android#9621]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal briefly displays the main menu (contacts list) and then crashes immediately.

### Steps to reproduce

- open signal App (cold start)

**Actual result:** Signal briefly displays the main menu (contacts list), then crashes immediately
**Expected result:** contacts list remains visible, new message gets received (I have the time to see that latest messages I can see on desktop are not present on the interface before the crash.

### Device info

**Device:** Fairphone 2
**Android version:**  AOSP 7.1.2 (Fairphone open), no google services nor MicroG
**Signal version:** 4.58.5 (installed via .apk)

### Link to debug log

https://outils.crapouillou.net/zerobin/?5470ca7e03f145a8#MTCuLBeyS4CiL/1RK1RNND9dpr40Yc5klBqWVsMlfvc=

(gathered via adb, as I cannot access any settings menu from Signal app)

**Comment by JocelynDelalande** [comment]
Thanks @greyson-signa, how fastl <3. 

Any idea on when a new APK will be released on https://signal.org/android/apk/ ?

**Comment by greyson-signal** [comment]
Ah shoot, we were avoiding release 4.59.x on the website because of some changes that we were fixing related to non-play-services devices. So we were gonna skip that and publish 4.60.x on the website when we were ready. That might take a week.

In the meantime, if you need a build, you can reach out to me via one of my test numbers at +1 610-708-0800, and I can get you one.

**Comment by JocelynDelalande** [comment]
Thanks for your offer !
Signal is currently unusable on my phone, that is what I am here. So I cannot contact you via Signal :).

I sent you an email, is that ok for you to send me back the apk replying to it ? (please gpg-sign the email).

Thanks by advance,

Jocelyn

**Comment by greyson-signal** [comment]
@JocelynDelalande I don't believe I ever received an email, sorry. Did you send it to greyson@signal.org? If not, try that one :)

**Comment by JocelynDelalande** [comment]
Thanks, just dropped you an email, this time with your @signal.org :-).
