### ISSUE TITLE
Strange Calling Issue

### ISSUE THREAD

**Issue by abcDontCare** [signalapp/Signal-Android#9622]
I can call all my Signal contacts except one and the same is true for the other party. However, we're both able to exchange messages just fine. The issue is that whenever anyone of us tries to call the other, all we see on our screens is dialing...dialing...dialing...and then "network failed". After this, the callee gets a missed call notification. We've tried multiple cellular and WiFi networks but it made no difference to our situation. Then we performed the following steps to no avail:-

1. Create chat backup.
2. Unregistered our numbers from Signal.
3. Uninstall Signal app.
4. Reinstall Signal app.
5. Restore chats from backup.
6. Register our numbers with Signal again.

We're both on Android and running Signal 4.59.9 version.

Here's what my debug log looks like when I try calling my problematic contact:- https://debuglogs.org/219647a9d32910a472f194a16bed652f6d5911ae23097113fcd288d418a90541

Please provide a solution of this problem ASAP.

**Comment by Genis-Sage** [comment]
hey  @abcDontCare 
can you also provide a debug log of the this one person, for which it does not work?
what devices are you both using?

can this one person call other persons? or does he face problems with all people?


just a guess, i did not look and the logs:
https://community.signalusers.org/t/non-synchronzied-clock-causes-voice-calls-to-fail/13694

so you both, but especially the other person should check if the phone clock is set to automatic...

**Comment by abcDontCare** [comment]
@Genis-Sage 

I'll try getting the time synchronized on both devices before I ask my contact to submit their debug log.

Yes, this person is able to call everyone else and so am I. I've mentioned it very clearly at the very beginning of my post.

Actually, my issue seems to be a more potent variant of this one: https://github.com/signalapp/Signal-Android/issues/9546

**Comment by abcDontCare** [comment]
Synchronizing time between the two devices has solved this issue! :-)

Thanks for the help @Genis-Sage

**Comment by gab81** [comment]
hello, i have the same problem https://github.com/signalapp/Signal-Android/issues/10281 and our 2 phones that call each other have the very same time setting (although i think using this to make it work is a bit crazy), so that does not work.
