### ISSUE TITLE
"Create Alphanumeric PIN" not colored properly in dark theme.

### ISSUE THREAD

**Issue by iamjodiann** [signalapp/Signal-Android#9623]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On pin creation there's text saying "CREATE ALPHANUMERIC PIN" but other text says "Pin must be at least 4 digits". Also, when either prompted to create a pin or input pin only the number keyboard displays even though on creation it says the pin can be alphanumeric. It's not clear which is correct (I'm assuming only numbers are allowed).

### Steps to reproduce
Create a new pin via the settings menu.

**Actual result:** Misleading text is displayed
**Expected result:** Either remove "CREATE ALPHANUMERIC PIN" or make the full keyboard display when entering your pin.

### Screenshots

![Screenshot_20200513-163131](https://user-images.githubusercontent.com/64506805/81862477-c93a4300-9537-11ea-834a-838547fae757.png)
![Screenshot_20200512-132812](https://user-images.githubusercontent.com/64506805/81862487-cc353380-9537-11ea-9ce1-cf0ab4d0ec83.png)

### Device info
**Device:** Google Pixel 3
**Android version:** 10
**Signal version:** 4.59.9

**Comment by eike-fokken** [comment]
On my device i can tap on "create alpha-numeric pin" to get an an alpha-numeric keyboard. Have you tried that?

**Comment by iamjodiann** [comment]
I didn't try that, it wasn't obvious to me that that was a button. I thought it was just text. Maybe that's the real issue?

**Comment by iamjodiann** [comment]
> On my device i can tap on "create alpha-numeric pin" to get an an alpha-numeric keyboard. Have you tried that?

I didn't try that, it wasn't obvious to me that that was a button. I thought it was just text. Maybe that's the real issue?

**Comment by igor2x** [comment]
This looks like a defect in Dark Theme. White Theme has "create alpha-numeric pin" string in blue colour to be obvious that it can be tapped, but Dark Theme uses white colour. As seen from bellow screens "Learn more" links are blue in both themes, so should it be "create alpha-numeric pin".

![pin_theme_comparison](https://user-images.githubusercontent.com/10895030/81935594-2e05a400-95f1-11ea-944e-aecac478adb4.png)

**Comment by greyson-signal** [comment]
I'll update the title to reflect the problem is a theming issue.

**Comment by Sgn-32** [comment]
The theming issue affects the two buttons
-'android:id="@+id/kbs_lock_keyboard_toggle"'
-'android:id="@+id/pin_restore_keyboard_toggle"'

The specific color 'android:textColor="@color/core_ultramarine"' is missing in the definition.

**Comment by AyusPokhriyal-18** [comment]
yeah, i saw this yesterday. Already done this)

**Comment by AyusPokhriyal-18** [comment]
guyz, i have solved this problem. But, in pull request section, its showing gradle problem. can anyone plz helpme out why its happening

**Comment by alan-signal** [comment]
You want to back out the last two commits, do not merge master if you need to rebase, do that instead. And do not delete `build.gradle`, need that!

By the way it is much easier to discuss a PR on the PR itself.

**Comment by AyusPokhriyal-18** [comment]
Sorry, it's just a week, I started github. And thanks for helping)

**Comment by vallividhya** [comment]
Does this issue still need help?

**Comment by AyusPokhriyal-18** [comment]
No, thank you)

**Comment by fumiakiy** [comment]
I think this issue was solved by [this commit](https://github.com/signalapp/Signal-Android/commit/707e238e5cdece76187d63fb17ac090e70844d4f#diff-2450f02476305bf9dc67a46f795f9cc3).

I don't see the issue any more in the build from the master.

**Comment by cody-signal** [comment]
Thanks @fumiakiy, can confirm that commit should fix the issue.

**Comment by Cerberus0** [comment]
This issue can now be closed:

https://github.com/signalapp/Signal-Android/pull/9649#issuecomment-692016225
