### ISSUE TITLE
I need APK file，I am in China

### ISSUE THREAD

**Issue by Hualingfeng** [signalapp/Signal-Android#9624]
I can’t access Google play, can anyone share a download link for me，thank you！

**Comment by rainerzufall** [comment]
https://signal.org/android/apk/

In the future please come to the forum (https://community.signalusers.org/) for questions like this. GitHub is solely meant for bugs.

**Comment by Hualingfeng** [comment]
> https://signal.org/android/apk/
> 
> In the future please come to the forum (https://community.signalusers.org/) for questions like this. GitHub is solely meant for bugs.

Thank you very much！
