### ISSUE TITLE
Option to disable "Verify Pin" Prompt

### ISSUE THREAD

**Issue by Krafting** [signalapp/Signal-Android#9631]
### Bug description
I totally understand the use of PIN, what I don't understand is Signal being your stupid dad always asking you for your PIN, I have a password manager where I store my Pins and Password, and 80% of Signal users do the exact same, because people who use signal cares about privacy and security.

Allow us to disable the Verify PIN prompt, it just take screen space for nothing.

Meanwhile, I'll stay on Signal 4.58.5 (If people want the APK, you can find it on apkpure)

### Steps to reproduce
- Set a Pin
- Suffer.

**Comment by jameswilliams1** [comment]
Seconded; this feature should be optional, not forced.

**Comment by alan-signal** [comment]
Thank you for the feedback on this feature, the preferred place for that feedback is the forum https://community.signalusers.org/ where this issue has been discussed on several threads you can contribute to further if you wish. We reserve Github issues for bug reports which is why I am closing this.

Additionally, I recommend you only get the APK from official sources, that's the play store or our website.

Duplicate #9611
Related #9617 #9620

**Comment by ezzra** [comment]
just because this is at top of google results: there is now an option to disable the pins in `settings->privacy->pins` from android 4.60.5 or iOS 3.9.0.6

**Comment by xela74** [comment]
For completeness, as this is still reported within the first Google search results: There also is an option to disable reminders, while keeping the PIN feature active (introduced with version 4.60.5 of the Android app). Maybe close this issue?

**Comment by ezzra** [comment]
@xela74 it actually _is_ closed, just google still linking to here :-)

**Comment by xela74** [comment]
@ezzra My bad, somehow missed it... Thanks.

**Comment by matkoniecz** [comment]
> just because this is at top of google results: there is now an option to disable the pins in settings->privacy->pins from android 4.60.5 or iOS 3.9.0.6

It seems that this setting is now sadly gone

> Additionally, I recommend you only get the APK from official sources, that's the play store or our website.

Speaking of these: is anyone of Signal app fork which has no popups related to rating app, donations, PIN reminders (I have password manager, I do not need these) etc?
