### ISSUE TITLE
Signal silently fails on establishing calls when time is de-synchronised

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#9633]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Symptoms are very similar to #7733: caller calls the other party when the time on their phones are some minutes drifted away and callee sees only  "You have a missed call" notification in the chat. The caller can continuously observe that Signal tries to connect but it won't succeed in the end.

The issue is the silent failure. A user cannot be expected to figure out that their call failed because of some minute deviance from atomic clock.

### Steps to reproduce
- Have two phones with their clock set some minutes off in both directions.
- Try to call each other.

**Actual result:** Signal is just trying to connect but after a minute of trying the other party receives a chat message that they had a missed call.
**Expected result:** Signal warns the users that establishing this call is not possible because of the drifted time.

### Device info
Device independent based on previous comments.

Comments which describe this behaviour:
- https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-603991568
- https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-605493072
- https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-605515909
- https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-628516597
- https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-629848918

**Comment by gab81** [comment]
hello, i have the same problem https://github.com/signalapp/Signal-Android/issues/10281 and our 2 phones that call each other have the very same time setting (although i think using this to make it work is a bit crazy), so that does not work.

**Comment by jknockaert** [comment]
Does anyone have an indication as to what the tolerance is for system clock accuracy? Android phones sync to cellular network provided clocks. Perhaps the tolerance limits used in Signal could be increased a bit to account for lazy syncing by android (and by cellular network opps)?

**Comment by Xashyar** [comment]
Has this issue been solved via c591ec31859965f88e6c1fd8c9dfe680cc03642d?

**Comment by szotsaki** [comment]
It's possibly a fix for a new beta issue only: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-4-release/27904/201

**Comment by cody-signal** [comment]
Hey Folks, thanks for sticking with us. We recently pushed some fixes and hopeful changes to calling in the [latest 5.6 beta](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-6-release/30590).

I'm hopeful it'll fix some issues for some of you but I believe gremlins are still lurking in calling. So, after updating to the beta, if you are still encountering the issues above please provide updated debug logs and anything interesting about your calling situation. Examples of things that are interesting: phone has non-standard hardware (like no camera), using bluetooth, in a region that has internet restrictions, using a VPN, etc.
