### ISSUE TITLE
Storage usage: numbers in settings twice as high as in app

### ISSUE THREAD

**Issue by klues** [signalapp/Signal-Android#9634]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
* Storage usage in app shows 3.7 GB: http://prntscr.com/sirw7n
* Storage usage in systems settings shows 6.9 GB: http://prntscr.com/sirwxn

**Expected result:** The numbers should be (at least roughly) equal.

### Device info

**Device:** Samsung Galaxy S4
**Android version:** 9.0.0 (LineageOS 16)
**Signal version:** 4.58.5

### Link to debug log
Unfortunately sending debug logs on device aborts with error.

**Comment by ikino** [comment]
Hello
Samsuns S7, Android 8.0
Signal: 4.59.9

System usage: 8.36GB

**Comment by nescio007** [comment]
Same issue here,

* Storage usage in app shows 3.1 GB
* Storage usage in systems settings shows 6.18 GB (user data only!)

#### Device info

**Device:** Sony Xperia X Compact (F5321)
**Android version:** 8.0.0
**Signal version:** 4.66.8


![Screenshot_20200728-103347](https://user-images.githubusercontent.com/7250294/88640576-62e8a980-d0be-11ea-8d9d-818f7c031db3.png)

![Screenshot_20200728-103426](https://user-images.githubusercontent.com/7250294/88640610-6bd97b00-d0be-11ea-9316-2496c34d4c49.png)

**Comment by cascheberg** [comment]
It seems like this issue has been fixed in Signal 4.72 by actually reducing storage usage. Can you confirm that?

**Comment by ikino** [comment]
> It seems like this issue has been fixed in Signal 4.72 by actually reducing storage usage. Can you confirm that?

yes, in 4.72.6 seems be ok +/-
