### ISSUE TITLE
Regression: cannot send/preview portrait-mode photos

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#9636]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- For photos taken in portrait mode, no preview is shown.
- Sending such a photo to connected desktop instance results in an empty message being received.
- This used to work flawlessly a few weeks ago. Unfortunately, I cannot pinpoint which release brought the regression.
- Edit: After the attempt to send such a photo, Signal eats the battery.

### Steps to reproduce
- Take a photo in portrait mode, preferably with Motorola Camera.
- Switch to a conversation in Signal.
- Press (+) to add an attachment.
- Notice that no preview is shown, select "black" photo and send.

**Actual result:**
No preview is shown in both, photo selection and for the outgoing message. An empty message is sent. Curiously, tapping the outgoing message brings up the photo. After leaving the conversation, a brocken image icon is shown in the message.

**Expected result:**
I expect preview to be shown for portrait mode photos.
I expect that an attachment is sent.

### Device info

**Device:** Motorola Moto G7 plus
**Android version:** 10 Patch-Level 1.4.2020
**Signal version:** 4.59.10

### Link to debug log
https://debuglogs.org/ec4b84a5432b20d1eaeada0d848c635291a5953717457d4088a3601b04bb9b6f

**Comment by merkste** [comment]
If necessary, I can provide a sample photograph.

**Comment by merkste** [comment]
Any news on this issue?

**Comment by aaronjanse** [comment]
I can also reproduce this. I've been having this issue for at least a month :-/
