### ISSUE TITLE
Camera function uses wrong app.

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#9637]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I know I used to be able to open my default camera app (OpenCamera) from Signal, for taking a picture. But now, that button seems to be missing since the redesign. I only get Gallery, GIF, File, Contact and Location.
The photo button in the text input only uses a really bad camera preview (?) with almost zero functionality, that is pretty much unusable. As it always did. There seems to be no way, to take a proper photo, like there used to. (E.g. if I want to take a macro photo with color correction, forced brightness, and manual fixed focus, like I often to, to photograph insects or flowers.

### Steps to reproduce
- Chat with somebody.
- Tap the (+) button.
- Find no Camera button.
- Tap the camera button that strangely resides in the text field above.

**Actual result:** Some weird featureless camera preview snapshot thingie opens.

**Expected result:** OpenCamera should open, or whatever the user configured. So a proper photo can be taken.

### Device info

**Device:** Huawei ALE-L21
**Android version:** 6.0
**Signal version:** 4.59.10

### Addendum
- The Gallery button leads to a screen that also has the same camera button leading to the same bad camera preview thingie.
- As does the camera button in Signal’s contacts list.

**Comment by greyson-signal** [comment]
Hi there, linking out to the external camera was always a compromise. The contract with working with the external camera required allowing it to write the image it captured to a folder on disk that we'd then have to immediately remove. Once we had an in-app camera with basic features like tap-to-focus, zoom, and flash, we removed the reference to the external system camera. You can always take a picture with the camera app and share it into Signal.
