### ISSUE TITLE
No notifications without Play Services

### ISSUE THREAD

**Issue by mmBesar** [signalapp/Signal-Android#9638]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Running Lineage 17.1 without Google Play Services or microG, The "Background connection enabled" is shown in the notification area after restart but still I have to open the APP to get the notifications and massages, while Telegram FOSS working out of the box!

I left WhatsApp and Google, guided my family and friends to contact me only via Signal, it's a shame I still need google to use Signal!

### Steps to reproduce
- Clean Installation without Play Services or microG then restart.

**Actual result:** The "Background connection enabled" is shown in the notification area after restart but still I have to open the APP to get the notifications and massages.
**Expected result:** It should give me the notifications to the massages without opening the APP

### Screenshots
![photo_2020-05-19_02-06-39](https://user-images.githubusercontent.com/35855690/82270539-6b618d00-9975-11ea-91ba-2e99a674c443.jpg)

### Device info

**Device:** Manufacturer Model XT1676
**Android version:** 10
**Signal version:** 4.58.5 website - 4.59.10 play store - 4.60.1 apkmirror

### Link to debug log
for 4.60.1 apkmirror
https://debuglogs.org/9c223308e1f217d4aa37c57bd964e9aba48722a33259246e55ef90ceb534bb9c

**Comment by jod-didi** [comment]
I'm from Qatar and I have the same problem but Signal was never able to submit a debug log on my phone. I've opened this thread on the forum discussing this problem.

https://community.signalusers.org/t/government-circumvention-doesnt-work-without-google-services-in-qatar/13886

I can tell you that the problem is caused by Censorship Circumvention and not using Play Services in the same time.

The evidence I have for this is something you can try yourself:

1-Unregister your local number.
2-Connect to a VPN so Signal can reach its servers as they're being blocked in your country since Signal is connecting to Google domain fronting instead.
3-Register Signal on your same phone that has the problem with a number from any virtual number website.

After registering with the virtual number (in a country that doesn't block Signal), go ahead and test Signal, you'll find that it works like it should be.

Now take a debug log and compare it, you'll find that the following difference:
Using your own number (in a country where Signal is blocked) Signal will connect to "google.com" or any other Google url to reach Signal servers.

Using the virtual number, Signal will connect to its own servers "https://textsecure-service.whispersystems.org" and notifications will work normally.

**Comment by mmBesar** [comment]
I'm suspecting something like that, it has to do my provider and region! but Telegram FOSS is working just fine!
Hopefully the Signal team will find away.

**Comment by TjrGithub** [comment]
I have this problem, too. It used to work two weeks ago on the same ROM, but now the background connection somehow got lost.

The "Background connection enabled" is not shown in the notification area.
I still I have to open the APP to get the notifications and messages.

OS: LineageOS 16.0 Microg (no Google account logged in)
https://download.lineage.microg.org/beryllium/lineage-16.0-20200331-microG-beryllium.zip

Debuglog:
https://debuglogs.org/425a9a3244c28fe37379550f4e384ad99074db1c2eaf87baf3b54446972e223d

**Comment by ronidee** [comment]
@TjrGithub @mmBesar Are you sure you're not describing #9578 ?

It got fixed in 4.60.0. However as [greyson mentioned in his  reply](https://github.com/signalapp/Signal-Android/issues/9578#issuecomment-628734884), you need to **unregister** and go through **registration again** for it to take effect.

(It's working for everybody who commented on #9578 , including me)

**Comment by mmBesar** [comment]
> @TjrGithub @mmBesar Are you sure you're not describing #9578 ?
> 
> It got fixed in 4.60.0. However as [greyson mentioned in his reply](https://github.com/signalapp/Signal-Android/issues/9578#issuecomment-628734884), you need to **unregister** and go through **registration again** for it to take effect.
> 
> (It's working for everybody who commented on #9578 , including me)

As I mentioned above, I have this problem with 4.60.1 clean installation and the debug log for it included.

**Comment by ronidee** [comment]
> > @TjrGithub @mmBesar Are you sure you're not describing #9578 ?
> > It got fixed in 4.60.0. However as [greyson mentioned in his reply](https://github.com/signalapp/Signal-Android/issues/9578#issuecomment-628734884), you need to **unregister** and go through **registration again** for it to take effect.
> > (It's working for everybody who commented on #9578 , including me)
> 
> As I mentioned above, I have this problem with 4.60.1 clean installation and the debug log for it included.

Oh I see. I assumed the 4.60.1 version was not a clean install but an update in your case.
But if it is, that means my previous comment is obsolete of course.

**Comment by TjrGithub** [comment]
I fixed the problem this way:
make a backup of Signal (from inside the app), uninstall, install the latest version 4.59.11, import the backup (enter all kinds of passwords in the process), reboot.
From then on, it seems to works for me. I'm sorry I can't help with the bug anymore.

**Comment by mmBesar** [comment]
> I fixed the problem this way:
> make a backup of Signal (from inside the app), uninstall, install the latest version 4.59.11, import the backup (enter all kinds of passwords in the process), reboot.
> From then on, it seems to works for me. I'm sorry I can't help with the bug anymore.
I've tried 4.60.1 clean installation!

**Comment by mmBesar** [comment]
> The "Background connection enabled" is not shown in the notification area.
> I still I have to open the APP to get the notifications and messages.

You have a different problem, I do get the "Background connection enabled" in the notification area but no notifications.

**Comment by floss-birdy** [comment]
signal being a privacy focused software a big part of its user base should be having no google play services .  so it should be better optimised for them . I don't have google play services but notification and background services are working on one of my device(android 10-stock) on the other (android 6-asus-zen ui)  it never gets notifications without play services .

**Comment by aelisya** [comment]
Any news on the un-playservices the app ?

**Comment by mmBesar** [comment]
> Any news on the un-playservices the app ?

Nothing! They don't care about us!

**Comment by aelisya** [comment]
@ronidee @mmBesar Actually i think it's better to do like telegram or tutanota, the app is always on with a notification (opt-in), and you do that as a switch in settings the default rest play services.
Like that all people who have play services (google's one) enabled don't change anything, and other can enable the other way (drain more the battery but at least it work).

**Comment by mmBesar** [comment]
> @ronidee @mmBesar Actually i think it's better to do like telegram or tutanota, the app is always on with a notification (opt-in), and you do that as a switch in settings the default is play services.
> Like that all people who have play services (google's one) enabled don't change anything, and other can enable the other way (drain more the battery but at least it work).

This is the way it should work, but it doesn't!

**Comment by mmBesar** [comment]
I don't understand, it has been months now, and no feedback from Signal to this issue!
Please, give me something! It's a shame really, I have microG installed only for Signal, the privacy app forces me to use Google Play Service!

**Comment by ronidee** [comment]
Which version do you have? And which Android version and which vendor? 
For me there is no issue at all. Could it be that your vender has a specially aggressive background killer?

**Comment by mmBesar** [comment]
> Which version do you have? And which Android version and which vendor?
> For me there is no issue at all. Could it be that your vender has a specially aggressive background killer?

I'm the OP of this issue, I've submitted a full log.
Now I'm on Android 10 and version 4.71.5 from the site.

**Comment by mmBesar** [comment]
The problem not resolved yet!

**Comment by mmBesar** [comment]
The problem not resolved yet!

**Comment by cody-signal** [comment]
@mmBesar can you update to the latest version and submit a new debuglog?

**Comment by mmBesar** [comment]
@cody-signal sorry for the late response.  
Now I'm using microG for signal, I will try again soon and get back to you.  
Thanks

**Comment by mmBesar** [comment]
I will update it soon!

**Comment by mmBesar** [comment]
I've been testing Signal without Google Play Services for days now, and it's working just fine.
I'll give it a week or two and post my update here.
Thanks.

**Comment by mmBesar** [comment]
All good now, thanks.

**Comment by beatjost** [comment]
@mmBesar On which App-version was this fixed? I use Signal v6.6.1 with an Huawei P40 and the notifications are not working (even though in the notification there is always the "background connection" activated). I need always to open the app to check for new messages... 😢

**Comment by nicholas-signal** [comment]
> @mmBesar On which App-version was this fixed? I use Signal v6.6.1 with an Huawei P40 and the notifications are not working (even though in the notification there is always the "background connection" activated). I need always to open the app to check for new messages... 😢

Happy to take a look. We'll need a debug log for when a message came in and you were not notified. You can submit a debug log by following these instructions: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by mmBesar** [comment]
@beatjost I used to use microG for Signal, but when I formatted my phone in last November, I didn't install microG, and it has been working fine since. Now I'm on the latest 6.5.6.
