### ISSUE TITLE
Website APK version at "Danger Zone" significantly outdated

### ISSUE THREAD

**Issue by beantaco** [signalapp/Signal-Android#9639]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The APK that is available at the "Danger Zone" is significantly outdated.
Version 4.58.5 was released April 3, about 1.5 months ago.
I have been unable to update the Signal app since then.

### Steps to reproduce
 1. Go to https://signal.org/android/apk/
 2. See what version the website APK is. \
*Note: it takes a few seconds for the version number to appear.*

**Actual result:** 4.58.5
**Expected result:** version of the most recent Android app (currently 4.60.3)

**Comment by u32i64** [comment]
`4.60.*` is still in beta. `4.59.*` is [purposefully not being released on the website](https://github.com/signalapp/Signal-Android/issues/9621#issuecomment-628760855) because of a bug.

**Comment by mueller-ma** [comment]
Today I received 4.59.11 via the website: https://github.com/signalapp/Signal-Android/commits/4.59.11

**Comment by beantaco** [comment]
I also see there is 4.59.11 on the website.

> `4.60.*` is still in beta. `4.59.*` is [purposefully not being released on the website](https://github.com/signalapp/Signal-Android/issues/9621#issuecomment-628760855) because of a bug.

If 4.59.11 is available on the website, does it mean the bug in 4.59.* (#9621?) is resolved?
