### ISSUE TITLE
after viewing an image, scroll position is lost (jump to bottom)

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9640]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- scroll up and find a message with images
- tap an image to view it full screen
- back out either using Androids back button or by using Signals own back button

**Actual result:** 
After a split second you jump to the latest message in the conversation
**Expected result:** 
Stay at the scroll position you had before you tapped the image

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0
**Signal version:** 4.60.2

**Comment by AyusPokhriyal-18** [comment]
Sorry, to say but nothing happening like what you stated above in my huawei honor8x. Are sure about the steps to reproduce problem??

**Comment by Meteor0id** [comment]
Unable to reproduce in 4.60.3

🤷🏼‍♂️
