### ISSUE TITLE
Photos in landscape mode are not rotated

### ISSUE THREAD

**Issue by skorokithakis** [signalapp/Signal-Android#9641]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Taking photos in landscape results in photos being sent in portrait, 90 degrees off.

### Steps to reproduce

- Click camera icon.
- Take photo in landscape.
- Send photo.

**Actual result:** The photo is in portrait and in the wrong orientation.
**Expected result:** The photo should be rotated with information from the accelerometer.

### Device info
**Device:** Xiaomi 9T
**Android version:** 10
**Signal version:** 4.60.3

**Comment by primarto** [comment]
This only happens when it is 'Auto-rotate screen' is **off**, when turned on it is OK.
However, it should be fine in both cases.

**Device:** Xiaomi redmi note 4X
**Android version:** 7.0
**Signal version:** 4.59.10

**Comment by skorokithakis** [comment]
Ahh, I do have auto-rotate off, you're right.

**Comment by greyson-signal** [comment]
It's working as expected now. Eventually we do want to support landscape photos when the device is locked to portrait, but I'd consider that a separate feature.

**Comment by skorokithakis** [comment]
This bug is about that separate feature, please reopen @greyson-signal. I would absolutely expect photos to be rotated correctly, regardless of screen lock, which is irrelevant to the photo orientation.

**Comment by SuperSamus** [comment]
This issue is still not fixed (though the title should specify that it only happens with Auto-rotate off).

**Comment by skorokithakis** [comment]
Done, though I don't think anyone will notice, @SuperSamus.

**Comment by Vinnl** [comment]
For those coming across this later (e.g. via Hacker News, like me just now), this seems to be the issue for the "separate feature": https://github.com/signalapp/Signal-Android/issues/8611

**Comment by skorokithakis** [comment]
Thanks @Vinnl, I missed that!
