### ISSUE TITLE
Receiving messages from groups left months ago after installing Signal on a new Phone

### ISSUE THREAD

**Issue by icescalar** [signalapp/Signal-Android#9642]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After we installed Signal on a new device (old one was broken), we started to receive messages from groups we left month ago. Sometimes we don't receive the messages of everyone in the group, but of some. We can also write in them, but we are not visible in the "members"-list of the groups from the other devices.

Could be related to https://github.com/signalapp/Signal-Desktop/issues/1115, but since here its Android without the use of a Desktop Client (The other devices in the groups we don't know...) we decided to open a new issue.

### Steps to reproduce
We didn't try to reproduce this behavior but still wanna say the steps
- old phone broke, so no deinstallation or logout possible
- installed and activated signal on a new phone

**Actual result:** Receiving and being able to write to several groups left months ago. Not visible in the members list on the other devices inside the group.
**Expected result:** Never receive any more messages from left groups. Not visible in the members list on the other devices of left groups.

### Device info

**Device:** Samsung S5neo (old phone was Samsung S4 Mini)
**Android version:** 9.0.0 (LineageOS 16.0)
**Signal version:** 4.8.5

### Link to debug log

Submitting the debug log is not possible. Says that it fails. Lineageos without GApps?

**Comment by Sgn-32** [comment]
Sounds that the "leave group"-message wasn't received by all group members. For a subset of members you are still in the group and by receiving a message of one of them, you was "readded" to the (sub-)group.
Is there an entry "Leave group" in the settings of the group?

**Comment by greyson-signal** [comment]
Yep, @Sgn-32 is probably correct. If you can re-leave the group, that's probably best. Otherwise, you can block the group.

**Comment by peterthomassen** [comment]
This is a security issue, as it is not clear to group members who will be able to read their messages. The list of group members displayed is not indicative, as people who have been in the group in the past *may* still be able to read new messages.

Should this not be reopened and assigned a security tag?

**Comment by greyson-signal** [comment]
@peterthomassen The solution is [Groups V2](https://signal.org/blog/signal-private-group-system/), which is the foundation for all newly-created groups. We're also going to be migrating existing V1 groups to V2 in the near future.
