### ISSUE TITLE
Create / Edit contact button appears to be gone in 4.59.10 

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#9643]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There used to be a way to create a new contact from Signal (when a message was received from a new number). Either that's gone or it's super hard to find because I've been hunting around and I can't find it. 

Same for an existing contact: there used to be a way to get to the "Contact" screen from Signal. Appears to be gone. 

There **definitely** used to be a way to do this. If it's gone it should be brought back. 

### Steps to reproduce
- Get a text from a new number
- long press on the message, no way to create a new contact
- go to the Signal settings for that contact/conversation, no way to create a new contact

**Actual result:** no way to create a new contact 
**Expected result:** A button of some sort that will take you to the new contact screen in the Android phonebook. Or a button that takes you to the existing contact. 

### Device info

**Device:** Pixel 3XL
**Android version:** 10 
**Signal version:** 4.59.10

**Comment by Sgn-32** [comment]
There should be a menu entry for "add to contacts" in the contact settings.

![Screenshot_20200519-213429](https://user-images.githubusercontent.com/49990901/82370887-92719a80-9a19-11ea-99e1-ec34f809d392.png)

**Comment by jcollum** [comment]
Yes, that's there. But there used to be a create contact button on the conversation settings screen. And there used to be a link (button) to the contact for existing contacts. It was handy.

**Comment by Genis-Sage** [comment]
hey @jcollum 

as i guess, Signal devs changes the GUI not by accident, 
this is not a real bug report, but should be a discussion in the community forum:
https://community.signalusers.org/

and just about "link button": simple go into a conversation and click long on the name / picture of the contact

**Comment by jcollum** [comment]
>and just about "link button": simple go into a conversation and click long on the name / picture of the contact

That doesn't get you to the phone contact screen.

**Comment by jcollum** [comment]
If you're going to close a ticket at least explain why. Just hitting "Close" with no comment is lame.
