### ISSUE TITLE
Opening anything other than settings crashes the app.

### ISSUE THREAD

**Issue by EarthToFatt** [signalapp/Signal-Android#9646]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crashes whenever trying to open a message, making the app unusable.

### Steps to reproduce
On any of the Oxygen OS Android 10 Beta builds for the OnePlus 5T, open Signal, and try to open a message.

Actual result: App crashes
Expected result: App...doesn't crash?

### Device info

**Device:** OnePlus 5T 6gb 64gb
**Android version:** 10
**Signal version:** 4.60.4 (occurs on latest non beta build as well)

### Link to debug log

https://debuglogs.org/a957683d78267e1fcef629aefbccd499d76c760fa55cdf8275cc36de96ef4e92

**Comment by alan-signal** [comment]
I'll TAL, but you might want to also raise with the Oxygen OS developers seeing how you're running a Beta.

**Comment by EarthToFatt** [comment]
Apparently it was just fixed in yesterday's beta update that came out AS I
POSTED the thing on GitHub. My bad.

-Matt

**Comment by alan-signal** [comment]
No problem at all. Are you saying this was an Oxygen bug and they have fixed this? And so we can close this?

**Comment by EarthToFatt** [comment]
At the moment, I believe so. You can go ahead and close it.

-Matt
