### ISSUE TITLE
Pin wont stop ask for verification.

### ISSUE THREAD

**Issue by WSLUser** [signalapp/Signal-Android#9648]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
install signal.  Get prompted to create pin. No way to ignore it 🖕 
So you create it. Now see it ask every day to verify, sometimes multiple times a day. Great work...NOT.
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Not only do I expect to ignore pins but I also expect to not be prompted all the time to verify it if I do decide to add one. Its not adding security if you're messing with the user experience to bring availability down. So here's some more of how I feel about the devs who added this stupid "feature" : 🖕🤬🖕🤬🖕🤬🖕
### Device info

Device: Samsung Galaxy S10

**Android version:** 10
**Signal version:** latest

**Comment by greyson-signal** [comment]
Hi there, couple of things:

1. If you complete the reminders, they become less frequent. The pattern is you'll see a reminder after 1 day, then 3 days, then 7 days, then every 14 days after that.
2. The latest 4.60.5 release (currently in beta) adds a setting to disable reminders.
