### ISSUE TITLE
Can't re-enter alphanumeric PIN to confirm it

### ISSUE THREAD

**Issue by mattcen** [signalapp/Signal-Android#9650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was prompted by Signal to create a PIN. I tapped the "CREATE ALPHANUMERIC PIN" link (which isn't coloured as a link in dark mode, but allegedly will be fixed by #9649), and entered my chosen alphanumeric PIN, before saving it in my password manager. When I am prompted to "Verify your Signal PIN", and I tap "VERIFY PIN", I am shown a numeric keypad with no option to switch to a full keyboard to enter my alphanumeric PIN, though I *can* paste in an alphanumeric PIN or auto-fill it with my password manager.

### Steps to reproduce
- When prompted by Signal to create a PIN, choose the "CREATE ALPHANUMERIC PIN" option and create an alphanumeric PIN
- Wait until prompted to "Verify your Signal PIN" and tap "VERIFY PIN"

**Actual result:** There is no provision to enter a non-numeric PIN on the resulting form - only a numeric keypad is shown
**Expected result:** There is an option to display a full keyboard to enter an alphanumeric PIN

### Screenshots
![image](https://user-images.githubusercontent.com/4273659/82647148-1cf40d00-9c59-11ea-865f-e38128ea4b23.png)

![image](https://user-images.githubusercontent.com/4273659/82647331-62183f00-9c59-11ea-9aca-5bffa8738ab3.png)

### Device info
**Device:** Google Pixel 4
**Android version:** 10
**Signal version:** 4.59.10

Possibly related: #9576, #9623

**Comment by alan-signal** [comment]
I have been unable to recreate this.

Is there anything else you can tell me about how you got to this point?

And I have to ask the obvious I'm afraid: are you certain that you did set an alpha-numeric pin successfully?

Please include logs next time you make a report, I think it's probably too late to see what happened now.

**Comment by mattcen** [comment]
Ah, bother. OK, I'll see if I can reproduce it again next time I'm asked for my pin and try to get a log sent through. And yes, I'm absolutely positive that the pin I set is alphanumeric. If I type the text of the PIN elsewhere and copy/paste it into the text area, it gets accepted.

**Comment by mattcen** [comment]
Well, I changed my PIN to the same text string it was already set to, and now it's prompted me to re-enter it and shows me an alphanumeric keyboard as expected, so I guess I hit an edge-case or something. Will close this issue for now given I can't reproduce it.

**Comment by spagy** [comment]
I have the same issue.

When setting up Signal, I used an alphanumeric PIN. PIN reminders used the alphanumeric keyboard.
Then I created a backup and restored to a new phone (technically same phone new, fresh OS installation).
On the new phone PIN reminders now use the numeric keyboard, though, as @mattcen says, I can use my password manager to complete the alphanumeric PIN.

**Comment by UserX404** [comment]
Due to I performed the same steps as mentioned by @spagy a few days ago: 
Switched for Stock A10 to LOS 17.1 on Sony Xperia XZ2c and also use a alphanumeric PIN.
I don't ran into any issues with Signal 5.7.6

@spagy Please append debug log or logcat.

**Comment by spagy** [comment]
Can't say what version of Signal I was on before. I'm also currently on 5.7.6.

Here's a debug log: https://debuglogs.org/855f6109ea9c82759b1fda95e34f5f75cc6fbe4a897678f931724f50e2432b43

**Comment by UserX404** [comment]
This is a really awful log. A lot of connection problems.
`SignalServiceMessageSender: java.io.IOException: No connection!`
Do you have any VPN or bad internet connection?
It's maybe related to your Linage ROM which is maybe also responsible for some other crashes.
There were some exceptions on 13.Apr. and the main log starts from 19.Apr.
When did you run into your pin-issue?

**Comment by spagy** [comment]
I do have a VPN but wasn't using it on 2021-04-19. Yet there still seem to be those connection issues. It could well be related to the ROM. It's not an official release.

In any case, I've had the PIN issue since first using Signal on this OS installation. It happens every time the PIN reminder appears.

**Comment by greyson-signal** [comment]
I tried but couldn't repro :(
(also feel free to disregard the 'connection problems' -- some of those are expected just with how the pipe works, we should try to reduce the noisy logs)

**Comment by spagy** [comment]
I'd be happy to have a bit of a prod myself but I'm not really sure where to start.

Is there anything I could do to help someone else debugging this or does anyone have pointers for how I could try debugging this myself?

**Comment by greyson-signal** [comment]
It must be the case that, for whatever reason, we have your keyboard type saved as numeric. I don't see how that would happen with the flow you went through, but it must have.

If you'd like to fix it for yourself, you can probably just go to Settings > Privacy > Change your PIN and just set the same PIN again. That should update your keyboard setting.

**Comment by spagy** [comment]
Alright, I'll give that a go. Thanks :)
