### ISSUE TITLE
Not able to delete account Can't receive Call or SMS

### ISSUE THREAD

**Issue by Msouza91** [signalapp/Signal-Android#9651]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm not able to delete my account using https://whispersystems.org/textsecure/unregister/ In my country the phone format is 9xxxx-xxxx I had to subtract the first nine to be able to use the buttons to Call or Send Message, but even then, the system returns a "failed to connect to the server" error

### Steps to reproduce
- Go to https://whispersystems.org/textsecure/unregister/
- Type info to delete an account number in Brazil
- Supress one "Extra digit" that was introduced in all cell numbers a few years ago in Brazil to comply to the form's number formatting

**Actual result:** "Failed to connect to the server" message below the Unregister Button, not able to delete account.
**Expected result:** Receive the PIN e terminate account.
### Screenshots

https://imgur.com/a/JYjZIpb

### Device info
Irrelevant, since I already deleted the app

### Link to debug log
See Device Info

**Comment by alan-signal** [comment]
Would you please contact support@signal.org who will be able to assist you further.
