### ISSUE TITLE
Mandatory PIN screen blocks access to SMS

### ISSUE THREAD

**Issue by delxg** [signalapp/Signal-Android#9652]
Hi @greyson-signal,

Thanks for your reply on #9632. Since that issue is now locked I'll fully explain my concern here.

I have several relatives who were previously using the builtin Android "Messaging" app for SMS. Their primary concern about installing Signal was that it would be difficult for them to manage two apps. I took advantage of the fact that Signal can seamlessly handle both insecure SMS and opportunistically encrypt messages to other Signal users. This seemed like a perfect solution.

Well no. Now I'm receiving many complaints from these relatives that their messages are locked up behind a PIN. I understand what Signal is aiming for, but the goal of usernames, groups v2, etc matter less to me than the perception of these users that Signal is no longer trustworthy.

My primary concern is that these relatives of mine believed that they had lost access to all their SMS messages and SMS contacts. The blame for this is in their mind is on both Signal and myself. At this point they just want to go back to good old SMS, which is perceived as less troublesome.

I believe I can still trust Signal to be secure and private, but for many people these factors are less important than simplicity and predictability.

I believe the PIN should be introduced the first time a user tries to use one of the new features that will require it.

In particular there should never be a requirement of entering a PIN in order to send or receive SMS messages. I also cannot think of a justification for requiring a PIN to read existing Signal messages. Perhaps you could force a PIN creation in order to send new Signal messages, do group management, or add a non-phone-number contact.

For the record I managed to convince them to stick with Signal, however the app has sadly lost a lot of good-will in the minds of many :(

Thanks for your consideration.

**Comment by alan-signal** [comment]
> their messages are locked up behind a PIN

I believe you mean they are at the point where the are being asked to set a PIN. If they do so they will be able to continue.

> In particular there should never be a requirement of entering a PIN in order to send or receive SMS messages. I also cannot think of a justification for requiring a PIN to read existing Signal messages.

That PIN is never used to restrict access to messages.

You can read more on our pins blog: https://signal.org/blog/signal-pins/

If you like, you can use the community forum to discuss further https://community.signalusers.org/

**Comment by delxg** [comment]
Hi @alan-signal, thanks for your reply.

I have read the documentation about PINs and I have a high-level understanding of how they are used by the server-side Intel SGX enclave to guard access to a strong key which encrypts the user's data. I also understand that once the user creates a PIN they regain full access to their data on their device.

I understand the necessity of having a PIN to implement the new features you're working on. I also fully appreciate the desire to quickly migrate your user-base to a consistent state. Managing multiple dark features is a pain!

However I know multiple people who were unable or unwilling to proceed on their own past this create-PIN prompt. For them this had the effect of appearing to lock up both their Signal messages and SMS messages.

It was of particular concern to many of these users that access to their SMS messages was blocked by the create-PIN prompt. Hypothetically if one unregistered the Signal app and wished to use it only for Android SMS then a PIN should never be necessary right?

Given the migration is still on-going I thought it appropriate to discuss this as a design bug on GitHub. If you disagree that this is a design bug then I'll just leave you with a reminder that multiple people were ready to uninstall Signal and return to the regular Android messaging app because of their confusion over this issue.

Thanks again for your time :)

**Comment by alan-signal** [comment]
> Hypothetically if one unregistered the Signal app and wished to use it only for Android SMS then a PIN should never be necessary right?

Correct, if you know of a prompt appearing in such an instance, please let us know in a new bug report.

> I thought it appropriate to discuss this as a design bug on GitHub.

I understand you don't like it, but it is working as intended. Furthermore, these github issues are for Android specific bugs, and mainly it's only the Android team are looking regularly at these, where as PINs applies to all platforms. So you need to add to the forum discussions for greater visibility.

**Comment by delxg** [comment]
> I understand you don't like it, but it is working as intended. Furthermore, these github issues are for Android specific bugs, and mainly it's only the Android team are looking regularly at these, where as PINs applies to all platforms. So you need to add to the forum discussions for greater visibility.

For myself I have no particular opinion. I didn't even experience the forced create-PIN because I already had a registration lock. In my case the migration was seamless :)

I do think this is an Android specific issue as to my knowledge the iOS app doesn't handle SMS at all.

I created this issue not for myself, but with the hope that the Signal team would be receptive to developing a more user-friendly migration strategy. I just had a look at the forums and I can see that there are many people who have had a strong reaction to the introduction of mandatory PINs. It seems like there's plenty of feedback and noise there, so I won't be bothering to sign up and add my voice.

I do hope the Signal team is reflecting on how this change could have been introduced with less stress and upset on the population of Signal users. I had a couple of ideas which I mentioned in my first post to this issue ;-)

Thanks again for your time.

**Comment by cascheberg** [comment]
> > Hypothetically if one unregistered the Signal app and wished to use it only for Android SMS then a PIN should never be necessary right?
> 
> Correct, if you know of a prompt appearing in such an instance, please let us know in a new bug report.

In fact it does happen that Signal asks to verify the PIN even for unregistered users. I created #9657.
