### ISSUE TITLE
Cloud storage is mandatory

### ISSUE THREAD

**Issue by derMart** [signalapp/Signal-Android#9655]
somehow the original issue to this got closed AND BLOCKED!!!
https://github.com/signalapp/Signal-Android/issues/9632

But unfortunately it did not get resolved. So please get rid of the need for a mandatory cloud storage please, please, please!
Please guys, don't be so dictatorous and listen to the needs of your community!

**Comment by piratenpanda** [comment]
You wanted to say "your needs". Please use the community forum for discussion. This is a bug/issue tracker. Thank you

**Comment by derMart** [comment]
No, this is the need of a lot of people, as you can read in the community forum / reddit and on this issue tracker. And yes, it is a bug, as it supposed to work without beforehand!

**Comment by alan-signal** [comment]
Please use the community forum for discussions, we do read it https://community.signalusers.org/

**Comment by derMart** [comment]
@alan-signal well sorry, but this mandatory feature proves you wrong, you do not read them ... :-(

**Comment by delxg** [comment]
Hi @derMart. I'm not associated with Signal, just a mostly-happy user :)

So far the server-side storage seems to only be used for a few bits of data:
- User profile -- not really a concern, you don't have to put anything sensitive here if you don't wish
- Settings -- this also doesn't seem like a huge problem if it leaks
- Contacts -- this is of course potentially sensitive, but Signal has already been doing something similar to this for [private contact discovery](https://signal.org/blog/private-contact-discovery). It's worth noting that this is not a new issue

I think the Signal team has carefully thought through this new feature which they are currently launching. There are certainly pros and cons to the implementation choices that have been made.

I think if you wish to change their mind about it you'll need to come up with a specific problem with the implementation. A vague request like "Get rid of mandatory cloud storage" is not going to be received well. If they followed that request then the Signal service would not even be able to relay messages to your contacts. That process almost certainly uses cloud storage to buffer messages :)

Hypothetically you may wish to have an option to disable storing encrypted contacts on the Signal server? In this case you would need to justify the extra complexity on the client and server that would necessitate. You'd also need to explain why such an option would improve your privacy and/or security.

I hope that helps :)
