### ISSUE TITLE
Signal first-time-start crashes after updating to 4.59.11

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#9656]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgraded from 4.58 to 4.59.11 on the first start after showing white screen for 2-3 secs, Signal crashed.

### Device info

**Device:** Sony F5121
**Android version:** 8.0.0
**Signal version:** 4.59.11

### Link to debug log
The second time I started Signal, it started up successfully and could retrieve the debug log.

https://debuglogs.org/937aacbb778476befcea32d9387ab2d38140cd43f3e541c06a66466c130effae

**Comment by greyson-signal** [comment]
Thank you for the report, but unfortunately there don't appear to be any crashes captured in the logs, so I don't have anything to go off of :( Let me know if it happens again!
