### ISSUE TITLE
Bluetooth calls do not properly terminate on 4.60.5 Android 10

### ISSUE THREAD

**Issue by mmirg** [signalapp/Signal-Android#9658]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Bluetooth calls do not terminate properly when a Signal call ends. Two different Bluetooth headsets continue to be in their "phone call" state and do not automatically disconnect and transition back to "media state". Manual intervention by pressing a physical call termination button sometimes terminates the call from the phone's perspective, at other times the only way to rectify the situation is by placing a call with another properly functioning application (which will show the Bluetooth device as still set to phone) and then terminating the call properly at which time the Bluetooth device will be able to act as a media sink again..

### Steps to reproduce
- Place a voice call and connect to a Bluetooth headset
- Terminate the call
- Try to play media through the headset

**Actual result:** Audio is not heard on the Bluetooth device even if "play media to" under sound settings is set to the Bluetooth device. Attempting to adjust volume will indicate a call volume widget and grayed out media audio widget.

**Expected result:** The headset should disconnect from call audio when the signal audio call is terminated and be able to act as a sink for media and other audio without manual interaction.

### Screenshots

https://debuglogs.org/9976d1d7514a50c34a519e93e4fa5325052e9364c6417e2ff4bc45b2a371faf5
![signal-attachment-2020-05-25-004058_001](https://user-images.githubusercontent.com/4317194/82767782-f6350280-9e21-11ea-87d8-15df912e029a.jpeg)
The phone believes it is outputting media audio to the Bluetooth device (but is not).

![signal-attachment-2020-05-25-004058_002](https://user-images.githubusercontent.com/4317194/82767789-faf9b680-9e21-11ea-9cd3-139c64b0a486.jpeg)
The volume widget is incorrect and shows a null call in progress and no indication of Bluetooth connectivity.

![signal-attachment-2020-05-25-004058_003](https://user-images.githubusercontent.com/4317194/82767791-fdf4a700-9e21-11ea-9969-ae4206dd58dd.png)

The Bluetooth device appears under "call" even though the call has been disconnected.

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 10
**Signal version:** 4.60.5

**Comment by Edu4rdSHL** [comment]
Please rename this removing the "bluetooth" word. Calls aren't properly terminated in any way.

Device: Samsung Galaxy A70 (SM-A705MN)
Signal version: 4.60.7
Android version: 9

**Comment by alekna** [comment]
I'm having same problem with Pixel 1 XL on Android 10

**Comment by Edu4rdSHL** [comment]
I confirm that this was fixed in 4.60.8 with https://github.com/signalapp/Signal-Android/commit/cd1bad0718fb23ddcab06f445a8e9502170e4069 commit.

**Comment by mmirg** [comment]
https://github.com/signalapp/Signal-Android/issues/9658#issuecomment-635738770
