### ISSUE TITLE
Signal crashes when recipient replies while you are

### ISSUE THREAD

**Issue by skyhiflyguy** [signalapp/Signal-Android#9664]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Many times this app has crashed when I have been having a text conversation and the other person replies as I am typing 

### Steps to reproduce
-start a conversation
-have recipient reply and press enter after they finish

- if you are typing and they send,  signal crashes

**signal crashes** 
**messages should post in order of reciept**

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10
**Signal version:** 4.60.5

**Comment by Salt505** [comment]
Your post says that your Signal version is only 4.60.5... have you tried updating to 4.60.7? Does this issue still occur in 4.60.7?

**Comment by skyhiflyguy** [comment]
My google app store gives me no furthr options to download a later version, I will check on  F droid 

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
