### ISSUE TITLE
Restore with alphanumeric pin not available

### ISSUE THREAD

**Issue by larrydewey** [signalapp/Signal-Android#9665]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to restore a backup, the backup was secured with my pin. When reloading signal, the section "Enter backup passphrase" only accepts numeric values, preventing me from opening the backup.

### Steps to reproduce
- On previous device create a backup of existing messages.
- Copy the backup to a computer.
- Copy the backup to the new device to restore the backup
- Attempt to enter the passphrase to open the backup.

**Actual result:** 
Only numeric keyboard entry is displayed.

**Expected result:**
Full keyboard access for alphanumeric/symbol entry should be accessible.

### Screenshots
![Screenshot_20200527-120530](https://user-images.githubusercontent.com/41640198/83056502-c436c280-a012-11ea-8e94-a9808d490ec4.png)

### Device info

**Device:** Google Pixel 3
**Android version:** 10.0.0
**Signal version:** 4.59.11

**Comment by u32i64** [comment]
You couldn't have set an alphanumeric password for the backup. The backup passphrase is generated automatically and presented to you by Signal, and it's always numeric. Looks like you're confusing [Signal PINs](https://support.signal.org/hc/en-us/articles/360007059792) with [Backups](https://support.signal.org/hc/en-us/articles/360007059752).

**Comment by greyson-signal** [comment]
Correct, the backup passphrase is still a separate thing.

**Comment by git-warrior** [comment]
It doesn't appear as if either of the two responses clearly read the question. I too am having the same issue. When I try to restore a signal backup file on a new device, it asks for the backup recovery phrase. However, when you go to type in the recovery phrase field, the numeric-only pad shows up. You are also unable to paste any text into the field. This is clearly something that needs to be looked at
