### ISSUE TITLE
Contact name is displayed separate to contact UUID after secure session reset

### ISSUE THREAD

**Issue by Beaverkilla** [signalapp/Signal-Android#9666]
### Bug description
I recently reset the secure session on my Signal Windows desktop client and it reset fine, I then went to my phone and the contact's name is now displayed as a UUID which I assume is their contact id. The entry in the message list is duplicated, I have the existing contact's name as an entry (currently at position 5) and the new entry (at pos 2). 

### Steps to reproduce
- Reset secure session on windows desktop client
- Go to Signal on your phone
- Find the contact you've reset the secure session for

**Actual result:**
The contact was duplicated and the second entry created with their contact id (I'm assuming).
**Expected result:** 
The contact should only have one entry and it should notify me that the session has been reset in that chat.

### Screenshots
![signal-attachment-2020-05-28-135156_edit](https://user-images.githubusercontent.com/8328061/83097338-35e23f80-a0eb-11ea-93df-8c2e2e8f92ca.png)

### Device info
Windows 10 Signal desktop client v1.34.1
**Device:** Sony Xperia Z5P
**Android version:** 7.1.2
**Signal version:** 4.59.11

### Link to debug log
Not available yet

**Comment by kenpowers-signal** [comment]
Hi, @Beaverkilla. Did you ever downgrade your Desktop instance? Do you have a Desktop debug log available?

**Comment by Beaverkilla** [comment]
I have not, there's a chance it was a version behind or hadn't updated but it has never been more than a week or two until I've updated everything. Unfortunately I don't have the desktop debug log either.
