### ISSUE TITLE
Signal calls do not work with my bluetooth headset

### ISSUE THREAD

**Issue by delxg** [signalapp/Signal-Android#9668]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It seems that calls do not work with my bluetooth headset anymore. I had no trouble using the in the past, I think this happened with the update from 4.59.x to 4.60.7 today.

### Steps to reproduce
- Connect my bluetooth headset to my Android phone
- Start a Signal voice or video call
- Select bluetooth from the speaker menu within Signal
- Listen and talk with the headset

**Actual result:** Signal indicates that it is using the bluetooth headset, Android sound prefs says that the headset is active and call audio is going to the headset. However Signal actually uses the phone speaker and microphone
**Expected result:** Signal should use the bluetooth headset

### Device info
I have tested on two different phones with two different bluetooth devices:
**Device:** Nokia 6.2
**Android version:** 10 (Stock ROM)
**Signal version:** 4.60.7

**Device:** Samsung Galaxy S4
**Android version:** 10 (LineageOS)
**Signal version:** 4.60.7

**Comment by Sgn-32** [comment]
With 4.60.8 there was a new [commit](https://github.com/signalapp/Signal-Android/commit/cd1bad0718fb23ddcab06f445a8e9502170e4069) for bluetooth behavior.
Does this solve the problem for you?

**Comment by delxg** [comment]
Yes this is gone in the latest version.
