### ISSUE TITLE
Disabling PIN reminders leaves a reminder on the screen

### ISSUE THREAD

**Issue by delxg** [signalapp/Signal-Android#9669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgrading to 4.60.7 today I was thrilled to see that I could disable PIN reminders. I keep my 16-digit randomly generated alphanumeric "PIN" in a password manager that is not accessible from my phone, so the reminders were a huge pain. Thanks.

While turning off reminders I noticed this bug on a couple of devices.

### Steps to reproduce
- A reminder is visible on the main screen. In 4.59.x there was always a reminder visible as I just ignored them.
- Ignore the reminder and go into Settings -> Privacy
- Turn off the "PIN reminders" option
- Press back to return to the Signal main screen
- Notice that the reminder is still visible
- Go to the Android home screen
- Open Signal again and notice that the reminder is now gone

**Actual result:** Disabling reminders leaves a reminder on the Signal main screen until the app is closed and reopened
**Expected result:** Disabling reminders should hide any current reminder boxes on the Signal main screen

### Device info

**Device:** Nokia 6.2
**Android version:** 10
**Signal version:** 4.60.7

**Comment by securitybryan** [comment]
Excellent write-up  Thank you!

The Pin reminders are very poorly thought out.  We have Pins on our mobile phones and are not nagged to death by our phone vendors.  Enough already!

**Comment by wrengr** [comment]
Cool, I never new I could disable those stupid reminders. Following the above steps I can reproduce the problem. Fwiw I got rid of the stale reminder it by quitting then reopening the app; though the underlying bug still needs to be fixed, of course.
