### ISSUE TITLE
Signal "keeps closing"

### ISSUE THREAD

**Issue by meladoro** [signalapp/Signal-Android#9671]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I open Signal, the app crashes (Android tells me that it "keeps closing"). This began happening suddenly. To my knowledge, I did not do anything relevant between the last time the app opened correctly and the first time it failed to open. It is possible that the app was updated in the background (i.e. without my knowledge or explicit consent to the updating of this particular version, though I routinely install new versions of apps whenever they are available, and so I most likely would have given such consent) but I have reason to believe this was not the case (I was on mobile data, with Android settings saying that updates should not happen automatically unless on WiFi, plus other reasons, upon which I could elaborate if necessary).

### Steps to reproduce
- Attempt to open Signal on my Moto G5 Plus.
**Actual result:** Signal fails to open, and on the second attempt to open it I receive an Android error message to the effect that "Signal keeps closing"
**Expected result:** Signal should open and its functionality become available as expected

### Device info

**Device:** Moto G5 Plus
**Android version:** 8.1.0
**Signal version:** 4.60.8

### Link to debug log

I do not know how to do this, and if I did, it seems like this would require successfully opening Signal, which in my scenario is not possible.

**Comment by alan-signal** [comment]
4.60.8 is about 12 hours old, so you certainly have recently updated.

I'm going to try and find your crashes in the play store logs. (Presuming you installed from the google play store?)

**Comment by meladoro** [comment]
> 4.60.8 is about 12 hours old, so you certainly have recently updated.
> 
> I'm going to try and find your crashes in the play store logs. (Presuming you installed from the google play store?)

Thank you. Play Store, yes.

**Comment by meladoro** [comment]
I'm sorry for omitting this earlier: I think I should say that the issue was happening before the last update. That is to say: I'm pretty sure this issue was happening before happening to 4.60.8... So I was running another, earlier version of Signal, and experiencing the same issue. Again, I can elaborate if necessary. Thanks.

**Comment by meladoro** [comment]
Any help would be massively appreciated. I rely on this app (maybe too much, apparently) and this is a major disruption

**Comment by meladoro** [comment]
I was able to replicate the issue on a different phone (Galaxy S7) with a fresh install of Signal. Signal asks me to confirm my PIN, and when I do, the app immediately crashes. Then it crashes again whenever I attempt to reopen it, until Android tells me "Signal keeps closing". I know that the PIN was correct however, because Android tells me I am logged into my Signal account, and I see messages coming into my notification area, I just can't open the app to view them in full and reply to them. I have made sure to send a crash report to Google Play, with the same title as this open issue in the description field. Again, I could really use some support. Thank you very much.

**Comment by alan-signal** [comment]
Would you be able to try to use adb to get the logs?

https://developer.android.com/studio/releases/platform-tools

And email me alan@signal.org

**Comment by meladoro** [comment]
> Would you be able to try to use adb to get the logs?
[...]
> And email me [alan@signal.org](mailto:alan@signal.org)

Thank you very much. I have now emailed you.

**Comment by meladoro** [comment]
This appears to be fixed for now. I'm closing the issue accordingly.
