### ISSUE TITLE
Unable to send image no a non-signal user

### ISSUE THREAD

**Issue by saraocean** [signalapp/Signal-Android#9673]
I have:

- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Cannot send MMS to non signal users

### Steps to reproduce
- Set up signal on mobile device
- Send image to non-signal user
- Image fails to send 
Message 'Send failed, tap for details'
Details: Some issues need your attention.

**Actual result:** Image is not sent to non-signal user
**Expected result:** Image successfully sent to signal user

### Device info
**Device:** Sony Xperia AX1 Ultra
**Android version:** 8.0.0
**Signal version:** 4.59.11

### Link to debug log
https://debuglogs.org/c2cfdd559de5acf89a6d6d36d3d6cd1fe4630a457400c6a95db75776da340dbf

**Comment by grravity** [comment]
Same issue as of lately

**Comment by jayMech47** [comment]
I am experiencing the same issue.

Added detail for my experience:
Phone: Pixel 2
Android Version: 10, Security Patch November 5, 2019
Signal: 4.65.2

My issue seems to be that Signal is not adhering to the mms carrier limit (1MB on my network). I've tested a number of pictures and one in particular keeps failing, with a size of 1.5MB. Other's that are larger (~5MB) get compressed down to <1MB.
The default sms app, Google Messages, compresses to the same picture (1.5MB) to 0.99MB.
It seems that Google Messages is aware of the 1MB carrier limit, but Signal has a different limit 1.5MB<x<5MB.

**Comment by grravity** [comment]
That actually might be related to the issue I've been having? I can send some pictures but not others, but I am having trouble receiving pictures sometimes too.

**Comment by greyson-signal** [comment]
Can you share what cellular network you're on? We have a ton of MMS configs we import, sounds like one of them is wrong or out-of-date.

**Comment by jayMech47** [comment]
Cricket Wireless

**Comment by grravity** [comment]
> 
> 
> Can you share what cellular network you're on? We have a ton of MMS configs we import, sounds like one of them is wrong or out-of-date.

Sorry, I'm on T-Mobile USA
Android 10, LGv40
Signal 4.64.7

I've already tried deleting and readding the APN they suggest multiple times, and also verified the entries are correct.
I'm not sure if it's a mix between their servers having trouble with MMS and Signal not following file size limitations, or just one, or both idk. But sometimes photos work, then they randomly don't work. I have trouble recieving photos lately, but some photos come through. The ones that have trouble usually just say "Error downloading MMS, tap to retry" and it just keeps erroring.
This is only as of the past few months, things used to work fine.

**Comment by CANADIANPIG** [comment]
I have submitted a report and am having the same issue, particularly when forwarding an image from a signal user to a non-signal user. 

**Link to debug log**
https://debuglogs.org/7e3a67ff923b3b0d4ca3b78b04ed0410504ce5140dc023c538bfb3647fd65ab2

**Comment by grravity** [comment]
I'm thinking it has to do with not compressing file sizes sometimes. Not sure why. I seem to have trouble with photos I take with my camera usually in 4k. I think I don't have issue when sending to other Tmobile users, but sending to other network users It has issues.
Could be wrong but it seems like this may be the issue.

**Comment by colin-axner** [comment]
I have encountered the same issue

Notes:
- Dual Sim, providers: Tele2, Google Fi
- works with google fi but not tele2
- works with basic messaging app 

[debug log](https://debuglogs.org/f87626e29819855b685dd24c384a68f860f840a7a0ac7ea06a0455c35b432037)

**Comment by caitsith01** [comment]
I am also experiencing this problem, especially when trying to send images taken with another device (e.g. a DSLR) to a non-Signal user.  Signal seems to make no attempt to resize the file and just fails instantly when you hit send.

**Comment by seniorm0ment** [comment]
relevant
