### ISSUE TITLE
Crash on scrolling to sound message

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9674]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I scroll to a sound message Signal crashes.

According to the debug log it crashes in AudioWaveForm.java line 136 line with a divide by zero error:
```java
int barSampleIndex = (int) (SAMPLES_PER_BAR * (wave.length * extractor.getSampleTime()) / totalDurationUs);
```
So I assume totalDurationUs == 0.  I'll put checks in place to test this.

### Steps to reproduce
- Scroll to a sound message

**Actual result:** Crash.
**Expected result:** No crash.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.61.0

### Link to debug log
https://debuglogs.org/6071a1d40614cbfa0c59fee8a209eb32e70776d522a2390b428a431076414666

**Comment by johanw666** [comment]
I tested a solution, this PR fixes the crash: https://github.com/signalapp/Signal-Android/pull/9675

**Comment by alan-signal** [comment]
Please only raise issues in one place. Beta feedback thread is preferred which I see you did already.
