### ISSUE TITLE
Gboard (keyboad): Enter-button has been replaced by Send-button (4.60.9)

### ISSUE THREAD

**Issue by MartinEismann** [signalapp/Signal-Android#9679]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After upgrade to version 4.60.9 while typing text, messages, the Enter-button (CR LF) has been "replaced" by Send-button. This happens currently only in Signal App. I'm using the default GBoard keyboard.

### Steps to reproduce
Simply write any message to any contact; it always happens.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20200601_193030](https://user-images.githubusercontent.com/66269926/83436596-6c4af200-a43e-11ea-9013-c5b885542cdd.png)

### Device info

**Device:** Doogee S80
**Android version:** 8.1.0 (Oreo)
**Signal version:** 4.60.9

### Link to debug log
n.a.

**Comment by alan-signal** [comment]
There's a setting in Settings->Chats and media->Enter key sends.

It just looks like you've enabled this.

**Comment by MartinEismann** [comment]
Hello Alan,
Your right. Thus setting solved the issued. I wonder why this changed after last update? 
Kind Regards, Martin
