### ISSUE TITLE
Pop-up camera doesn't lower after closing the built-in camera

### ISSUE THREAD

**Issue by juliusBaranauskas** [signalapp/Signal-Android#9682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening front camera (which is pop-up) opening the Signal built-in camera using button inside chat text-input area and going back to the chat doesn't immediately lower the camera.

### Steps to reproduce
- Use a device with a pop-up front camera
- Open Signal chat
- Click on a camera button next to the microphone button inside the text-input area
- Switch to front-camera (if not already using it)
- Camera pops up
- Go back to the chat using back button/gesture

**Actual result:** The camera stays popped-out for a while (probably system setting causes it to close after about five seconds of inactivity)
**Expected result:** Pop-up camera should slide back in immediately after closing the built-in camera screen

### Device info
**Device:** Xiaomi Redmi K20/Mi 9T
**Android version:** 10
**Signal version:** 4.60.9
### Link to debug log
https://debuglogs.org/54edfad8d76ec272a5980c2447f30b452527dc934f0c6239e7f6b26fd4157384

**Comment by Nisc3d** [comment]
I have a Asus Zenfone 6, which has a Flip Camera and it immediately flips the camera back, when I use the back button/gesture. I know it's not the same as pop-up, but maybe it's device-specific?

**Comment by siburny** [comment]
I have OnePlus 6 Pro with pop-up selfie cam, and I don't have this issue. When I hit Back pop-up camera hides immediately.

**Comment by juliusBaranauskas** [comment]
It probably is device specific, maybe the closing action on MIUI is not hooked on some events, since navigating to gallery in GCam does lower the camera immediately.
