### ISSUE TITLE
In Groups, the topbar members-preview not using language string

### ISSUE THREAD

**Issue by fm-sys** [signalapp/Signal-Android#9688]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

![Screenshot_20200603_140139](https://user-images.githubusercontent.com/64581222/83639555-22334f00-a5ab-11ea-9ff6-b09ca37b974f.jpg)

Also in the top bar should be the German (or other language) translation and not only the English word ("You")

=== SYSINFO ===
Device: SNE-LX1
Android: 10 (10.0.0.203C432) 
Version: Signal 4.61.0 (6412)

**Comment by Sgn-32** [comment]
Fixed with 4.61.5

**Comment by fm-sys** [comment]
is now fixed!
