### ISSUE TITLE
Error when I trying to build myself

### ISSUE THREAD

**Issue by giupardeb** [signalapp/Signal-Android#9691]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I followed this [wiki](https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources) for build Signal myself. When I executed this istruction:
`./gradlew build` after a few minute, I got this error:
```> Task :Signal-Android:stripPlayDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Signal-Android:stripPlayDebugDebugSymbols'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.1.6352462
```
How can I downgrade NDK?
### Steps to reproduce

1. clone repository
2. cd Signal-Android
3. execute in the terminal: `export ANDROID_SDK_ROOT=/mnt/17f03db7-3f5c-41e5-b85f-1d26f43f4015/commandlinetools-linux-6200805_latest`
4. `./gradlew build`

**Actual result:** BUILD FAILED

**Expected result:** BUILD SUCCESSFUL

**Comment by fumiakiy** [comment]
You can install the specific version of NDK by this command (ref [Install the NDK from the command line](https://developer.android.com/studio/projects/install-ndk#command-line))

`sdkmanager --install "ndk;20.0.5594570"`

If you have Android Studio too, you can just use it and open the directory you cloned the repository to. There in most errors like this you would have the option to resolve the issue by clicking an instruction.

**Comment by greyson-signal** [comment]
We have a reproducible build system (and now github actions) that verifies that app is building properly. If you're having issues beyond that, please use [the forum](https://community.signalusers.org/). Thanks!

**Comment by giupardeb** [comment]
Ok, Thank you @greyson-signal @fumiakiy
