### ISSUE TITLE
Upload media file does not succeed (starting over and over again)

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#9696]
### Bug description
In a conversation I tried to upload a movie media file. The file starts uploading (I also see the notification that an upload is in progress). The upload seems (nearly) finished, but starts over and over again.

### Steps to reproduce
I only saw this once

### Device info
Time         : 1591306262725
Manufacturer : bq
Model        : Aquaris X5 Plus
Product      : Aquaris_X5_Plus
Screen       : 1080x1920, xxxhdpi (480), 60.00 hz
Font Scale   : 1.0
Android      : 7.1.1 (684, 2.7.0_20181002-1711)
ABIs         : armeabi-v7a, armeabi
Memory       : 76M (4.82% free, 512M max)
Memclass     : 192
OS Host      : bqbot3
Censored     : false
Play Services: true
FCM          : true
First Version: 546
App          : Signal 4.61.6 (6471)
Package      : org.thoughtcrime.securesms (doDiFGKPO1r)

### Link to debug log
https://debuglogs.org/488bb173dfaaecdb0e260cfcc88ad5541bdc5b5f0501f425161834ef9817a351

**Comment by janvlug** [comment]
I force stopped Signal to see if that would help. But Signal kept trying over and over again to upload the media messages, without success. Then I deleted the media message. That worked. Next I tried sending it again, but again Signal cannot successful send the media message. Again, Signal keeps trying to send it over and over again.

Debug log:
https://debuglogs.org/811ccb2d43dfdfe347f0bd6fbbbd5536cd71376e2ef9cf7f7c13a48f57d767bd

**Comment by janvlug** [comment]
A maybe related other observation: Uploading both debug logs (that are in this issue) did not succeed in the first attempt. The second attempt succeeded for both debug logs.

**Comment by janvlug** [comment]
I now tried to upload the file from Signal Desktop.
There I got this error message:
"Sorry the selected file exceeds message size restrictios (100MB)"

According to my file manager is the size: 103.3 MB (103,293,606 bytes)

$ ls -sh VID_20200604_221248_669.mp4
99M VID_20200604_221248_669.mp4

So, maybe this is an edge case where size calculation is not completely correct.

**Comment by DanChristos** [comment]
I get this same issue and it definitely because of the file size. When I cut the video in half and send them separately they succeed. Seems Signal does not check the file size for it's upper limit before uploading.
