### ISSUE TITLE
Silence in call (micrphone) on Sony Xperia 10 and 10 Plus phones

### ISSUE THREAD

**Issue by developerfromjokela** [signalapp/Signal-Android#9699]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When calling voice or video, (the other end of the call is using Sony Xperia 10 Plus and mine is Xperia 10) signal gets no voice on both Xperia 10 and Xperia 10 Plus

### Steps to reproduce
- Open Signal app
- Call someone
- And no one hears you

**Actual result:** Audio from microphone is not tramsitted to the other end of the call
**Expected result:** Other end should be able to hear me

### Screenshots

Nothing looks wrong in the UI, in-call screen shows the mic icon, but no audio is transmitted whatsoever

### Device info

**Device:** Sony Xperia 10 (other end: Sony Xperia 10 Plus)
**Android version:** 10
**Signal version:** 4.62.0
(Edit: oh, I forgot to include the version)

### Link to debug log

[https://debuglogs.org/98553c76787176bac6452572e6e4bd51dbabedf1a93ce6deec6a0ec3aef81928](https://debuglogs.org/98553c76787176bac6452572e6e4bd51dbabedf1a93ce6deec6a0ec3aef81928)

**Comment by developerfromjokela** [comment]
So, nobody is helping? :disappointed:

**Comment by developerfromjokela** [comment]
I tried, and problem still exists on version 4.63.3. All permissions are granted, except for SMS. Microphone is also granted.

**Comment by developerfromjokela** [comment]
??? So how's bugfix going?

**Comment by developerfromjokela** [comment]
@moxie0 Could someone look at this issue?

**Comment by ljpp** [comment]
This could be the same permission issue I am now seeing on an Mi A3.

https://github.com/signalapp/Signal-Android/issues/11378

**Comment by developerfromjokela** [comment]
Possible. Mine also running Android 11.

Yet I haven't encountered this on any other Android 11 phone.

**Comment by UESCTerm** [comment]
Moved from lineage 17.1 android 10 to lineage 18.1 android 11 and transfer went OK, but audio does not work.  Video works, no audio.
