### ISSUE TITLE
No profile picture after update to 4.61.6

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#9700]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to 4.61.6 the profile picture is removed. This did not happen to my device during the beta however my wife's phone received 4.61.6 through the stable channel and has this as a result. In the 4.61.6 beta thread this was also reported by one person. Note this only seem to happen on the device itself. If I send a message the profile picture on the receiving device remains.

Edit: Apparently this was already reported on the community forum as well: https://community.signalusers.org/t/lost-signal-profile-picture/14751

### Steps to reproduce
- Unable. Happens after update.

**Actual result:** Profile picture is gone after update.
**Expected result:** Profile picture remains after update.

### Device info

**Device:** Samsung S9
**Android version:** 10
**Signal version:** 4.61.6

### Link to debug log

https://debuglogs.org/747679e31f89556ef8fbd0c4d178d1134f3fa2f856159e78349f0597ce942d47

**Comment by Herohtar** [comment]
This happened to me as well after the update to 4.61.6 happened overnight. Here is a debug log from shortly after I noticed it was missing:
https://debuglogs.org/e137e7b1648162647dddc34dc7bd677e21006cba2179b175cbc9a3c91fb115a7

**Comment by Nisc3d** [comment]
Someone in my contacts had the same error. The profile picture was just grey for other people. Setting a new picture fixed it. Unfortunately I don't have a debug log.

**Comment by greyson-signal** [comment]
Hi there, we believe we understand what caused this issue, and while we can't reverse what's already happened, it shouldn't happen moving forward. Thanks!
