### ISSUE TITLE
Feature Request: Schedule a timed message

### ISSUE THREAD

**Issue by mkrupczak3** [signalapp/Signal-Android#9703]
Hello,

I'm a bit of a night owl, and one of the features that I really miss from my old Samsung phone's texting app was the ability to schedule text messages to be sent at a certain time. 

This worked well for me because I could schedule certain messages to appear early in the day for people I communicated with frequently. 

It may also be very useful for people who work/travel/communicate across timezones, or otherwise wish to schedule messages around other's busy schedules.

**Comment by mkrupczak3** [comment]
A dialog for "timed message" could be added to the pop-up menu that appears upon long-pressing the send button.

**Comment by Cerberus0** [comment]
Hi @mkrupczak3,

That sounds like a good idea, but this is not the right place for feature requests. As stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

Your feature request is already being discussed and tracked on the community forum:

* https://community.signalusers.org/t/scheduled-send-of-messages/2568

If you want, you can easily join the discussion on the forum by signing up with your existing GitHub account. You can also show your support for individual feature requests on the forum by using the "like" button.

**Comment by mkrupczak3** [comment]
:+1:
