### ISSUE TITLE
Blurring faces in images takes lots of steps [feature]

### ISSUE THREAD

**Issue by longride** [signalapp/Signal-Android#9705]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic [maybe?]

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When sending a picture with strangers on it I think it is best practice to use the new blur faces feature. Currently I have to tap on the blur icon, then the switch, then confirm.

This many steps can be shortened by long pressing the blur icon.

**Comment by u32i64** [comment]
This is not a bug report, but a feature request/discussion topic.

Quoting [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.
