### ISSUE TITLE
Private contacts are visible in the direct share menu.

### ISSUE THREAD

**Issue by lbdroid** [signalapp/Signal-Android#9709]
- [X ] I have searched open and closed issues for duplicates:
Identified unresolved but locked duplicate:
https://github.com/signalapp/Signal-Android/issues/6073
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Evidence of communication with private contacts (possibly just phone number of no system contact exists) are visible in the direct share menu. This violates privacy and security of the device.

### Steps to reproduce
- send a message to a private contact with signal.
- try to share something from another program

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Private contacts are visible in the direct share menu.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

No contact through signal should be visible in the direct share menu unless you explicitly opt-in for that contact.

### Screenshots
Not possible for privacy reasons.

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 10.0.0
**Signal version:** current play store

### Link to debug log
Not applicable, it's not a crash.

**Comment by greyson-signal** [comment]
Hi there, this is working as intended.

**Comment by lbdroid** [comment]
So Signal "Private Messenger" is intended to be NOT private at all? Might want to rename it then.
