### ISSUE TITLE
"Mark as unread" isn't synced to desktop

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9713]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a chat is marked as unread, the unread status isn't synced to desktop.

### Steps to reproduce
- Receive a message
- Read it
- Mark the chat as unread
- Open linked Desktop app

**Actual result:** The unread status isn't synced to desktop.
**Expected result:** The unread status is synced across all linked clients.

### Device info

**Device:** Fairphone 3
**Android version:** 9
**Signal version:** 4.61.6
**Signal Desktop version:** 1.34.0-beta.3

**Comment by Tursko** [comment]
Do you have a PIN set? For the desktop to sync the unread status you must have a PIN set.

**Comment by mueller-ma** [comment]
Yes, I have a pin set.

**Comment by Tursko** [comment]
Actually sorry. Syncing unread status is only available on iOS devices right now. 

It should be added to Android soon.

**Comment by mueller-ma** [comment]
Thanks for the link
