### ISSUE TITLE
Noticable load time for long conversations

### ISSUE THREAD

**Issue by julKali** [signalapp/Signal-Android#9716]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I don't think this is an urgent issue, however, I would still like to point it out. Since 4.62.2, I noticed that one of my group which has a very long chat history takes a noticable time to load when opening it in the app. It's not critical, but I was wondering ... why is this even possible? Are conversations completely loaded when you click on them? Wouldn't it be possible to only load the last few messages?
I'm also not sure if this is caused by the updates to the group chat UI that came with 4.62.2, but I never noticed a signifantly longer load time before.
Please watch the screen cap below, I had to blur the whole thing, but you can clearly distinguish the panels/activities and you can also clearly see that the top-most conversation takes a split-second to load, while the other chat loads instantly.
I think that now that Signal gets a lot of traction and the general feeling/UX got so much better, it is time to also pay attention to little details that may be minor but are nevertheless present.

### Video link
https://streamable.com/vamjdw

### Device info
**Device:** Nokia 8 TA-1012
**Android version:** 9
**Signal version:** 4.62.2

**Comment by greyson-signal** [comment]
We page our database queries, yes. However, our schema has some quirks where even though the queries are paged, some conversations can take longer to load. This is something we're actively and continually working on :+1:
