### ISSUE TITLE
Group info screen: Picture overlaps with name on scroll

### ISSUE THREAD

**Issue by julKali** [signalapp/Signal-Android#9717]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When scrolling down in the group info screen, the group picture as well as the group name slide into a horizontal layout. I really love the idea, however, on the way "up", the two objects overlap each other, at least on my screen dimensions (see device). 

### Screenshots
1) transition starts
![Screenshot_20200608-221001](https://user-images.githubusercontent.com/17690423/84076517-307fd180-a9d6-11ea-99b7-48826af39422.png)
2) picture and text overlap
![Screenshot_20200608-221011](https://user-images.githubusercontent.com/17690423/84076417-fadae880-a9d5-11ea-93c4-ced7aff47d17.png)
3) transition end
![Screenshot_20200608-221018](https://user-images.githubusercontent.com/17690423/84076322-d2eb8500-a9d5-11ea-95ae-cecddbc35c19.png)

### Device info

**Device:** Nokia 8 (TA-1012)
**Android version:** 9
**Signal version:** 4.62.2

**Comment by greyson-signal** [comment]
Yeah, it's tricky. Given the positions and the fact the thing above it is a circle, there's going to be some overlap in the transition. Otherwise you'd have some strange arc that would have to change based on the width of the text.
