### ISSUE TITLE
(FR) Option to disable automatic reply suggestions in notification panel

### ISSUE THREAD

**Issue by SCassidy-UK** [signalapp/Signal-Android#9721]
Hi. I understand why automatic reply suggestions that appear in the notifications panel are useful to some people. However, even though it is optional to use them, I feel that the app is suggesting to me how I should respond to the message. It is in some sense steering the conversation, either by tempting me to automate the reply or planting the idea for the reply in my head. This is a trend in communications technology that I would like to resist. However, I can't find any option to disable this feature. Please considering adding one.

**Comment by Cerberus0** [comment]
Hi @SCassidy-UK,

These reply suggestions are generated by Android, not Signal. They can be disabled in Settings > Apps & notifications > Notifications > Advanced > Suggested actions and replies.

Please note that this is not the right place for feature requests. As stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

If you want, you can easily join the forum by signing up with your existing GitHub account.

**Comment by stampycode** [comment]
Looks like Android is ignoring my settings...
Any idea where I should report this to Android?

![Screenshot_20211116-215944](https://user-images.githubusercontent.com/5627756/142072870-bae4a684-1fde-4b03-85f1-d26330ce6c23.png)
![Screenshot_20211116-215800](https://user-images.githubusercontent.com/5627756/142072873-83530c37-9cc6-48b0-968c-c032f49096d2.png)
