### ISSUE TITLE
Heavy Battery drain Issue

### ISSUE THREAD

**Issue by teynav** [signalapp/Signal-Android#9724]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Too much battery drain while on being on signal compare to other IM

### Steps to reproduce
- Signal running in background or foreground

**Actual result:** Battery drain large 
**Expected result:** Brain drain Should be in range of other IM

### Device info

**Device:** Samsung m30s
**Android version:** 10
**Signal version:** 4.62.3

### Link to debug log

https://debuglogs.org/2ca9ac45c24e26054b987057f8e0286f15706b1302a3c57332e79c2b647c9d81

**Comment by teynav** [comment]
![Screenshot_20200609-212146_Device care](https://user-images.githubusercontent.com/40721108/84171341-3de69b80-aa6a-11ea-8f83-8f1fd146a315.jpg)
![Screenshot_20200609-212050_Device care](https://user-images.githubusercontent.com/40721108/84171403-4ccd4e00-aa6a-11ea-8d70-3e2a2cda09eb.jpg)
![20200609_212132](https://user-images.githubusercontent.com/40721108/84171431-53f45c00-aa6a-11ea-8eeb-e654291c8864.jpg)

**Comment by merkste** [comment]
Could this be related to ##9636 where the battery drain occurs right after (not) sending a picture?

**Comment by Edu4rdSHL** [comment]
Please try disabling battery optimizations for the Signal app. That battery drain issue is mostly caused because the "battery optimizer" kill the app in the background, then the app try to start again resulting in a kill/start loop. See https://dontkillmyapp.com/ for more info.

**Comment by mu-hi** [comment]
I also have this issue but noticed it's doing this only while using mobile data instead of Wi-Fi. I'm using the separate app because I don't use Google Play by the way. The battery optimization is already disabled but checking the battery usage the app is always running since the last charge and drained the 22% of battery singlehandedly and I didn't even use the app for 2 days.
