### ISSUE TITLE
Android app crashes after recieving VCF SMS

### ISSUE THREAD

**Issue by kaseyc** [signalapp/Signal-Android#9726]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After receiving an SMS containing VCF data from an iPhone user, Signal crashes upon opening due to a TransactionTooLargeException.

This seems related to #9453 except that the app crashes immediately rather than hanging. Other potentially relevant issues are #8759 and #7280.

Since the stack trace seemed to indicate that the issue came from notifications I tried disabling notifications for Signal system wide and rebooting, but this did not fix the issue.

### Steps to reproduce
- use Signal as default SMS client on Android
- Receive large SMS message (such as VCF)
- Attempt to open the app by tapping the icon.

**Actual result:** App shows the conversations overview for ~500ms before crashing.
**Expected result:** App opens without crashing and I am able to open the conversation containing the unread VCF data.

### Screenshots

![image](https://user-images.githubusercontent.com/2405952/84238901-9a6ca980-aab0-11ea-8b56-6814c42f0f7e.png)

- Signal is not the default app because I switched to the default Messages app in hopes of maybe deleting the offending SMS and to be able to use SMS functionality

### Device info

**Device:** Google Pixel 4 XL 
**Android version:** 10, security patch level April 5, 2020
**Signal version:** 4.61.6

### Link to debug log
Debug log was captured via ADB as the app does not open.
```
--------- beginning of crash
06-09 23:21:24.122  4887  5177 E AndroidRuntime: FATAL EXCEPTION: signal-unbounded-0
06-09 23:21:24.122  4887  5177 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4887
06-09 23:21:24.122  4887  5177 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1137024 bytes
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:497)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:444)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:215)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:199)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.sendSingleThreadNotification(DefaultMessageNotifier.java:401)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.updateNotification(DefaultMessageNotifier.java:315)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.updateNotification(DefaultMessageNotifier.java:228)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.OptimizedMessageNotifier.updateNotification(OptimizedMessageNotifier.java:60)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.messages.InitialMessageRetriever.begin(InitialMessageRetriever.java:105)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.lambda$catchUpOnMessages$2(ApplicationContext.java:391)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$ApplicationContext$VK9QLxgYFdkGxnAvWM7hmkqYb6I.run(Unknown Source:2)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1137024 bytes
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2791)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:494)
06-09 23:21:24.122  4887  5177 E AndroidRuntime: 	... 13 more
```

**Comment by kaseyc** [comment]
**Update:**

I received another sms from the same contact and got an Android notification. 

I am now able to open Signal without issue. 
Attempts to open the specific conversation will hang for a period of time and sometimes crash (not always). 

From inspecting the VCard data I see it contains an encoded 'profile image'. 

**Updated debug log:** https://debuglogs.org/fd9918dacb48d1ca61e3ad20e29ab606eccef57135867104966e0eab6a1c1410

**Comment by cafeTechne** [comment]
Bump. I came here to report this issue. @kaseyc have you had any luck with this?
