### ISSUE TITLE
BUG impossible to change photo in a group

### ISSUE THREAD

**Issue by xpwd-lab** [signalapp/Signal-Android#9730]
Good morning, everyone,
Since the last signal updates, it's impossible for me to change the photo in a group, when I click on the photo to modify it, then choose in the gallery, it closes immediately

You can find the Debuglogs at this address : https://debuglogs.org/e8538a20832e5b4fe4e18e51e181a7c738317b1dcaa96c94e8c5500fafb7c7ce

Installed Signal Version : 4.63.2

Phone : Samsung galaxy S8

Android version: 9

![Screenshot_20200612-075519_Signal](https://user-images.githubusercontent.com/63072894/84470319-63022680-ac83-11ea-8840-81aaa25e1cba.jpg)

**Comment by brownstic** [comment]
Please attach your debuglogs to make it easier for the developers to find out what's wrong 🙂

**Comment by xpwd-lab** [comment]
> Please attach your debuglogs to make it easier for the developers to find out what's wrong 🙂

Thanks !
You can find the Debuglogs at this address : https://debuglogs.org/e8538a20832e5b4fe4e18e51e181a7c738317b1dcaa96c94e8c5500fafb7c7ce

**Comment by xpwd-lab** [comment]
The bug has been fixed following the recent update deployed!  Thanks a lot to the developers, good work
