### ISSUE TITLE
Regression: Cannot See SMS/MMS Group Members

### ISSUE THREAD

**Issue by LucasMayeur** [signalapp/Signal-Android#9731]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
User can no longer see a list of members in an SMS/MMS (non-signal) group thread.

### Steps to reproduce
Be in SMS/MMS group
Open Group thread
Click on title bar of Group thread
Attempt to see all members of group thread

**Actual result:** 
If the names of group members or the number of group members is long enough to run off the screen or wrap, there is no way to see the full list.

Clicking on Group Name, Group Avatar, or group title does nothing.

In practice this happens with almost any group larger than 3 - you will not be able to see the 4th, 5th, etc member name.

**Expected result:** 
Previously there was a dialog / popup that would show all group members in the SMS/MMS thread. This is clearly a regression.

### Device info

**Device:** Nexus 6
**Android version:** 8.1
**Signal version:** 4.62.4

**Comment by Genis-Sage** [comment]
hey @LucasMayeur 
this seems to be a duplicate of #9725 
and that issue is fixed in the commit [Show group participants menu item on a MMS group](https://github.com/signalapp/Signal-Android/commit/559aa687a5c73de31a52ee252a58849b65cd1404)

**Comment by LucasMayeur** [comment]
@Genis-Sage - You are correct, thank you, Closing now.

**Comment by LucasMayeur** [comment]
Duplicate of #9725
