### ISSUE TITLE
Not entirely uppercased changelog heading in french

### ISSUE THREAD

**Issue by GuillaumeAmat** [signalapp/Signal-Android#9732]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The heading of the changelog section, in Play store updates for instance, is not entirely uppercased in french.

It displays "NOUVEAUTéS" instead of "NOUVEAUTÉS".

### Screenshots

![Screenshot_20200612-080313_Google Play Store](https://user-images.githubusercontent.com/1179174/84529807-65479d80-ace2-11ea-9986-f6f52cba731e.jpg)

**Comment by brownstic** [comment]
Hey, this isn't an issue with the app. This section is for issues with the functionality of the Signal app.

The text issue is actually an issue with Google and not Signal. Try checking changelogs of other apps, you will see that the text "NOUVEAUTéS" is also shown.

Please close this issue 🙂

**Comment by GuillaumeAmat** [comment]
Oh! My bad, I only saw that for Signal but you're right, it is a Play Store issue.
