### ISSUE TITLE
Andriod call bug

### ISSUE THREAD

**Issue by XxBlackHatxX** [signalapp/Signal-Android#9733]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For the longest time my android phone running android 4.4.4 And the signal app has not allowed me to receive any phone calls. But with the newest update as of June 4. 2020 I am now able to receive calls just fine. The only thing is when I speak to the person my voice is sped up and sounds like a chipmunk to the caller(they use iPhone 11). I’ve tried this on both Wi-Fi and cellular. They sound normal and clear to me. When that person calls other people it’s sounds normal for them.

### Steps to reproduce
- receive/initiate a call with someone that is on iPhone.

 while talking...
- Android user sounds like a chipmunk and sped up to the iPhone user.
- iPhone user sounds normal to the android person.

### Screenshots
N/A

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 4.4.4
**Signal version:**

**Comment by MrWaste** [comment]
I am having the same problem but when trying to call the android phone, they don't even know I am calling at all.

**Comment by XxBlackHatxX** [comment]
In the newest update the issue was fixed for calling not only works but the voices are not sped up like before.
