### ISSUE TITLE
Verification SMS not received

### ISSUE THREAD

**Issue by MSA2222** [signalapp/Signal-Android#9734]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using an old private build of Signal Android, verification SMS is not received. Another SMS is received asking to upgrade Signal instead.

### Steps to reproduce
- Build an older version of Signal Android
- Enter phone number in Registration screen
- Wait for verification SMS

**Actual result:** 
Verfication SMS is not Received.
The following SMS is received instead:
To continue installing, update to Signal: https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

**Expected result:** 
Verification SMS is received to login/register to Signal

### Device info
**Signal version:** 4.43.5

**Comment by Genis-Sage** [comment]
hey @MSA2222 
the version you mention is nearly a year old, so i guess, it's expected to not be working / registerable anymore
if an update to the current version solves the problem, then the update is the solution

also, even if you could register, the version would be shown as outdated (a build experies after 90 days)

**Comment by mshawkyee** [comment]
Merging my changes to the latest code will be too complex for me. Is there a quick fix for an old version, to get it to work temporarily until an upgrade is possible?

**Comment by MatejKovacic** [comment]
I have the similar problem. I have the latest Signal installed (from June, 24th) and tried to register with my mobile number (mobile operator is Hofer Telekom from Slovenia, Europe (mobile number is +386 69 xxx xxx), but I never receive SMS message.

However, I can receive SMS messages from other numbers (and can also send SMS). I also tried to initiate a verification via voice call, but it is not working also.

Anyway, I remember, that in the past similar problem existed, and some Signal servers needed to be restarted...

**Comment by greyson-signal** [comment]
@MSA2222 The solution is to update the version of Signal you're using.
@MatejKovacic Please reach out to support@signal.org. Our support team is setup better to handle issues around SMS not being received from our SMS provider.

**Comment by MatejKovacic** [comment]
They are very unresponsive... last time it took several months, only to get some generic answer from them. Are there any other means to contact them?

(Via Signal maybe :) )

**Comment by greyson-signal** [comment]
@MatejKovacic I reached out to our support team, and unfortunately there is no quick fix for this situation. Support is still working with your provider and our SMS service to get this resolved so you can get started.
