### ISSUE TITLE
Messages being sent out of order

### ISSUE THREAD

**Issue by SigmaWP** [signalapp/Signal-Android#9735]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you send messages, they are not being delivered in the right order.

### Steps to reproduce
- Send large media file ("one")
- While the file is uploading, send a textual message ("two")

**Actual result:** "two" gets delivered and read by the other conversation party before "one" even gets sent to them.
**Expected result:** "one" should get delivered before "two" does

### Screenshots
![bug](https://user-images.githubusercontent.com/2367611/84584997-9649d000-adbf-11ea-8b3a-af5640bce681.jpg)

### Device info

**Device:** Pixel 3
**Android version:** 10
**Signal version:** 4.62.4

### Link to debug log
"Failed to submit logs" :thinking:

**Comment by u32i64** [comment]
This behavior is intended, see [this topic](https://community.signalusers.org/t/non-blocking-media-message-sending/14849?u=u32i64) on the community forum for more details.

**Comment by SigmaWP** [comment]
This "feature" introduces discontinuity between clients which has the potential to create a lot of broken conversations.

Here's a second case:
- Enable disappearing messages
- Send large image file ("one")
- Disable disappearing messages
- Send text ("two"; intended to be non-disappearing)

The other party will receive "two" as a disappearing message, *which was not intended by the sender.* Then if the other party replies, disappearing messages are turned back on on my client, which adds further discontinuity between the clients.

**Comment by SigmaWP** [comment]
Upon further investigation, it seems that quoted messages are blocked by media messages too. Here's a third case:

- Send large image file ("one")
- Quote an earlier text, add some more text, and send it ("two")
- Send text ("three")

The other party will receive "three", then "one", then "two".
