### ISSUE TITLE
Language setting isn't reflected

### ISSUE THREAD

**Issue by a2y4** [signalapp/Signal-Android#9736]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Language setting isn't reflected until Signal will resume.

### Steps to reproduce
- Open Signal
- Go to Settings -> Appearance -> Language
- Change language to something (e.g. English to Japanese)

**Actual result:** Menu is shown in new language, but Search Box and Inbox is shown in old language.
**Expected result:** All text will be shown in new language.
### Screenshots

<img src="https://user-images.githubusercontent.com/53612225/84586032-a8c01a00-ae50-11ea-884f-907c9a840ba0.jpg" width="260"><img src="https://user-images.githubusercontent.com/53612225/84586035-ac53a100-ae50-11ea-9e24-03e40328b13e.jpg" width="260">

### Device info

**Device:** Samsung Galaxy S9 (SCV38)
**Android version:** 10
**Signal version:** 4.63.2

**Comment by brownstic** [comment]
Hey, there are some languages where not all strings have been translated. Also, please attach your debuglogs to make it easier for the developers to find out what's wrong 🙂

**Comment by fumiakiy** [comment]
Fixed by https://github.com/signalapp/Signal-Android/pull/9750
