### ISSUE TITLE
Drafts are getting deleted

### ISSUE THREAD

**Issue by diligentlystereotypedinvestment** [signalapp/Signal-Android#9740]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Drafts are being deleted.

### Steps to reproduce
- Type a draft to any contact (SMS or Signal)
- While viewing your draft, close Signal (using the menu navigator button)
- Enter Signal again
- Try to view your draft

**Actual result:** Right now the draft is getting deleted after performing those steps.
**Expected result:** What should be happening is that the draft should be displayed to use.

### Device info
**Device:** LG G7 ThinQ T-Mobile Variant
**Android version:** 10
**Signal version:** 4.63.3

### Link to debug log
[https://debuglogs.org/99735cc472c13975cc760dd6e63871a8bea8d4a79a2499c3290c576cbe7f70a4](url)

**Comment by deepfighter** [comment]
I can verify this behaviour.

### Device info
**Device:** Nokia 8 (TA-1004)
**Android version:** 9
**Signal version:** 4.63.3

**Comment by billie80** [comment]
Don't know what you mean 'menu navigator button'?
Do your drafts include media? Currently drafts are saved for text messages only.

**Comment by diligentlystereotypedinvestment** [comment]
The menu navigator button that is next to the home button. It pulls up running apps. My drafts are not including media. They are pure text drafts.

**Comment by billie80** [comment]
I see you are force closing the App. I wouldn't expect Signal to save drafts that way! Don't know if it is possible to save them when doing so.

**Comment by diligentlystereotypedinvestment** [comment]
Can't Signal save a draft every time you type a character? Right now it looks like it only saves a draft when pressing the go back button.

**Comment by billie80** [comment]
I think this is no longer an issue.
When I type something in a conversation and switch between Apps the draft remains available. Even if I swipe Signal away from the recently used Apps the draft is still there when opening Signal again.
