### ISSUE TITLE
Very high mobile data consumption while video call

### ISSUE THREAD

**Issue by teynav** [signalapp/Signal-Android#9741]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
High data consumption while video calls

### Steps to reproduce
- Just video call
**Actual result:** For other messenger it's 1mb/min to 3mb/min signal took 3gb in 3 hour and I am on mobile data 16mb/min which is too high
**Expected result:** Less data consumption atleast 3-5mb/min

### Screenshots

![Screenshot_20200617-014640_Settings](https://user-images.githubusercontent.com/40721108/84824206-144fe600-b00f-11ea-8c33-f00b06d1c034.jpg)

### Device info

**Device:** Samsung M30s
**Android version:** 10.0
**Signal version:** 4.63.3

**Comment by Sgn-32** [comment]
Can you please add a debug log after a long video call.

**Comment by teynav** [comment]
This from today's call although only 7 min I lost 100mb+ data 
My phone's log
https://debuglogs.org/fd5f7046cbf729b83faf3f02cefea2cc219ce5dd1954497cc9a03cd58ade06f6

The one whom i called
https://debuglogs.org/2c5d5d0846f46f4976267732a516bbe6ad25e74485f3a1c700607cfd5bd1f5b1

Reason to end call was the whom i called would see nothing but white screen on his camera and on my side his video feed was frozen, this is ss from his phone showing white screen 
![signal-2020-06-17-191115](https://user-images.githubusercontent.com/40721108/84906516-92f56380-b0a1-11ea-8b9a-6037ce8670a1.jpg)

**Comment by teynav** [comment]
https://debuglogs.org/9a41cfca8a7b6e08523c25685a293a4a0eae26b4b442321d35e50c6f239c2a07


https://debuglogs.org/92a49e96667ba2044bfc29daec91cfbde18d3eee4dce855e2ba1b7b6e10a63b7

**Comment by teynav** [comment]
https://debuglogs.org/cb17285240c7115dbb33f289d40e98ff40638c09de72ed785e22b7e350520998
