### ISSUE TITLE
Signal crashes

### ISSUE THREAD

**Issue by n0sign4l-official** [signalapp/Signal-Android#9749]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when I try to upload a video. I'm using the website APK so you do not probably see anything on your side

### Steps to reproduce
- upload a video
- signal crashes

**Actual result:** Signal crashes
**Expected result:** should not crash

### Device info

**Device:** pixel 3
**Android version:** 10.0
**Signal version:** 4.63.3

### Debug logs

https://debuglogs.org/4457b85222a44761680b22b5af7348cecf5c468939d41a1cbd384fdc9649d536

**Comment by alan-signal** [comment]
Any video?

How are you trying to send it?

**Comment by n0sign4l-official** [comment]
Not any video, it's a quite big one, 80MB. I'm just click on the + button select it and send

**Comment by n0sign4l-official** [comment]
Hi Alan after updating to latest version with the same video I encounter the same issue.
Logs: 
`
06-24 19:01:07.698  9844  4106 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #576
06-24 19:01:07.698  9844  4106 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9844
06-24 19:01:07.698  9844  4106 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at android.media.MediaCodec.native_stop(Native Method)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at android.media.MediaCodec.stop(MediaCodec.java:2148)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsExtractor.extractThumbnails(VideoThumbnailsExtractor.java:108)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:185)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:165)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-24 19:01:07.698  9844  4106 E AndroidRuntime: 	... 4 more
`

**Comment by n0sign4l-official** [comment]
new debug log, https://debuglogs.org/f0d42d79b1471f0668680f933fcfd6ba75924ab185d178a6f94c548329287961 the issue persist, I only need to click on + button in the chat to get the app crash with any video larger than 50MB that with a pixel 3a is something like 20 seconds of video..
