### ISSUE TITLE
In a group chat, the "delivered" tick shows up although not all messages have been delivered yet

### ISSUE THREAD

**Issue by l3u** [signalapp/Signal-Android#9755]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using a group chat, the "delivered" tick shows up even if not all participants of the chat have received the respective message yet. As an example: Yesterday, one message of a group chat of mine wasn't delivered to one of the participants and isn't until now (for whatever reason, but this is a problem of it's own, as e. g. already filed in Bug #9580 … all following messages were delivered normally), but the message's status is displayed as "delivered".

### Steps to reproduce
Chat in a group chat until the problem hits you that one participant doesn't receive a message.

**Actual result:** The Message is marked as "delivered"

**Expected result:** it shouldn't be ;-)

### Screenshots
Here's a screenshot of the chat, the message is marked both as "sent" and "delivered":
![Screenshot_20200618-123458](https://user-images.githubusercontent.com/6770781/85014331-5a6b8d80-b166-11ea-95be-6ae05adaf4eb.png)

And here's a screenshot of the message info, notice the one participant that didn't receive the message:
![Screenshot_20200618-123518](https://user-images.githubusercontent.com/6770781/85014420-871fa500-b166-11ea-90b0-2921df570712.png)

### Device info
**Device:** Nokia 4.2
**Android version:** 9
**Signal version:** 4.63.3

### Proposed solution
Apart from fixing the issue that sometimes, not all group members receive a message, I would propopse some progress indicator for the "delivered" tick (maybe also for the "sent" one):

One could e. g. add some "1/6", "2/6" and so on beside the respective tick and remove it if all is done, or – more sophisticated and unobtrusive – a circled progress bar around the tick displayed in red as long as not all messages have been sent/received and a green complete circle if all is done. For the "read" notification, I would propose to introduce a third tick for group chats.

The data is already there, one can see this in the message details. But it should be displayed in the chat window, so that one actually knows if everything is okay with a message. As of now, one would have to check the message details of each and every message for this information.

**Comment by l3u** [comment]
This would also lessen the problem of messages being displayed in the wrong order described in Bug #9580 a bit, as one can wait for all messages being actually delivered before continue to type/chat.

**Comment by greyson-signal** [comment]
It's a purposeful decision to show the 'highest' status of a message -- i.e. one delivery receipt shows delivered, one read receipt shows read. You can always go to the details screen if you need more info.
