### ISSUE TITLE
Make screen security mandatory for all users

### ISSUE THREAD

**Issue by Imran4424** [signalapp/Signal-Android#9758]
It's a general issue for all devices

**issue name - screen security is optional**

screen security is really important for better security.

screen security prevents taking **screenshots** and **screen recording.**
but signal needs both party to turn it on manually for this security.

If signal can make it mandatory for all users then it will huge step up in security for signal.
Everyone can feel more safe in signal about their data.

I know, there's a drawback that - some people may not like it.
but we have plenty of messenger app for that kind of stuff.

So, let's make signal most secure and reliable messenger app
by making
**Screen security mandatory for all users**

**Comment by mueller-ma** [comment]
From the issue template:

> - [ ] This isn't a feature request or a discussion topic

Please use the forum for discussion and feature requests.
