### ISSUE TITLE
Typing indicator almost invisible in dark mode

### ISSUE THREAD

**Issue by SinTan1729** [signalapp/Signal-Android#9760]
The typing indicator should also change to white to match the texts while in dark mode. The current implementation is almost invisible.
Signal version : 4.64.2
Device : Redmi K20 (Android 10)
[Screenshot](https://i.imgur.com/j64o9Gd.jpg)

**Comment by MorgeMoensch** [comment]
There's something wrong. The + Button should be in a much lighter blue than it is in your screenshot. This is how it should look like:

![Screenshot-SignalButton](https://user-images.githubusercontent.com/62468040/85257218-c18a8a00-b465-11ea-8366-2fbf300e915b.jpg)


Are you sure you're using Signals Dark Theme and not some phone setting that 'converts' everything to a 'darkmode'?

**Comment by SinTan1729** [comment]
> There's something wrong. The + Button should be in a much lighter blue than it is in your screenshot. This is how it should look like:
> 
> ![Screenshot-SignalButton](https://user-images.githubusercontent.com/62468040/85257218-c18a8a00-b465-11ea-8366-2fbf300e915b.jpg)
> 
> 
> Are you sure you're using Signals Dark Theme and not some phone setting that 'converts' everything to a 'darkmode'?

You're right. I turned that off and now it's fine. Sorry for the confusion.

**Comment by MorgeMoensch** [comment]
Glad I could help. Have a nice day
