### ISSUE TITLE
[Feature request] 'Follow device theme' in the theme section

### ISSUE THREAD

**Issue by Oymate** [signalapp/Signal-Android#9769]
I like to see light mode in day and dark mode in night.  :)

**Comment by greyson-signal** [comment]
We do this, but only on Android 10, when they started truly supporting system-wide dark theme (and some devices allow you to auto-turn-on dark theme at sunset). However, for future reference, we only use Github for bug reports, not feature requests. You can talk about feature requests on the [forum](https://community.signalusers.org/). Thanks!
