### ISSUE TITLE
Height of new message window too small

### ISSUE THREAD

**Issue by 7wells** [signalapp/Signal-Android#9772]
Hello,

The height of the message window is too small, e.g. on a Samsung S7 half of the device display height is covered by the keyboard. Instead of using the remaining height of the device display, Signal shows a part of the previous message of the conversation. As a result, only a tiny (height-wise) portion of the device display is available for the new message, which forces the user to scroll up and down a lot.

Proposal for a possible solution:
Make the window height for a new message dynamic, i.e. maximise it to use the device display height that remains (not covered by the keyboard).

Is that possible? Anyway, thanks a lot for a great messenger and for all your time you invest in this. 👍

**Comment by greyson-signal** [comment]
Hi there, I'm having trouble understanding your problem and solution. Is it that you want a taller text box for composing your message? If so, I imagine that falls into 'feature request' territory, which isn't something we handle on Github. For that, I suggest you open a discussion on [the forum](https://community.signalusers.org/). Thanks!
