### ISSUE TITLE
"Create a PIN" dialog stuck on "Creating PIN..."

### ISSUE THREAD

**Issue by drduh** [signalapp/Signal-Android#9775]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Create a PIN - PINs keep information that's stored with Signal encrypted" dialog message is permanently overlaid my chat threads and can't be dismissed. If I try to create a PIN, the app just sits at "Creating PIN..." indefinitely with no feedback.

I previously had set an inactivity PIN in Signal that would prompt after 20 hours. Doesn't seem like that works anymore, either.

### Steps to reproduce
- Use Signal 4.62.4 on Android 8.1.0

**Comment by drduh** [comment]
The dialog also seems to imply Signal stores my personal information unencrypted - "PINs keep information stored with Signal encrypted so only you can access it". It's not clear what the implications of not having a PIN are.

**Comment by alan-signal** [comment]
> Use Signal 4.62.4 on Android 8.1.0

Please update the app and see if this still occurs.

Afterward updating, please try to get us logs if it does happen again https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

I'm going to change the title of this issue as well as the issue seems to be the stuck on "Creating PIN..."

> I previously had set an inactivity PIN in Signal that would prompt after 20 hours. Doesn't seem like that works anymore, either.

Please make a separate issue for that.

**Comment by drduh** [comment]
Updating to the latest app version has made things worse: now I can't even open the app - a full screen "Introducing PINs" modal dialog appears and can't be dismissed to see my chat/contacts list. I can still reply to messages through the on-screen notification, though.

I'll try to collect some logs and debug what's happening, but I'm willing to bet it has to do with my very poor network reception timing out the PIN registration process. If so, I'm even more confused why a remote server needs to store my PIN credential, especially as I already have screen lock inactivity enabled with PIN.

**Comment by anto-1** [comment]
Had the same problem a couple weeks ago trying to install Signal for someone else. Entering the pin did nothing for several attempts. Then waited half an hour and it worked. 

Maybe the connection was a bit dubious. But you should at least inform the user if there is something wrong with the underlying process.

**Comment by drduh** [comment]
This PIN makes no sense. When I launch Signal, I get a full-screen modal dialog asking me to unlock the app, as I always have. After I do that, I have an in-app notification to "Verify your Signal PIN". What is the actual point of this?

**Comment by drduh** [comment]
Can this PIN "feature" be disabled, please? It serves no point other than to take up screen space. I honestly don't understand the justification for adding this.

**Comment by greyson-signal** [comment]
@drduh You can read more about PINs on our support page: https://support.signal.org/hc/en-us/articles/360007059792-Signal-PIN
