### ISSUE TITLE
Adding jpg without file extension crashes app in beta

### ISSUE THREAD

**Issue by jrabbit** [signalapp/Signal-Android#9778]
Downloaded an image from Tumblr via firefox that didn't have a file extension, it shows up in the selector, it also crashes if it's shared "to" signal. I can dig out any header info you need it's a meme.
Android build #: QQ3A.200605.002 (it's 10 or whatever)

**Comment by piratenpanda** [comment]
Please use the issue template for submitting bugs. Also ppase provide a log of the crash. You can find this under settings, advanced or further don't know how it's called in your locale and then you find a menu item to submit a log. copy the link to this issue here
