### ISSUE TITLE
Different Notification Icon for Notification & Backup Notification

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#9779]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Not quite sure, whether this is a bug but the Signal-Icon Shape is different for the Backup Notification and normal Notifications.

**Actual result:** Different Signal-Logo
**Expected result:** Same Signal Logo

### Screenshots
![grafik](https://user-images.githubusercontent.com/62468040/85386998-932fac00-b544-11ea-8215-8ea719f732a6.png)
The Backup-One seems like the old logo (Notice the different position of the apex and slightly different 'dotted' line around the bubble)

### Device info
**Device:** OnePlus 5T
**Android version:** 10, OxygenOS 10.0.0
**Signal version:** 4.64.5

**Comment by MrWaste** [comment]
Not sure if this is a bug, might be.
