### ISSUE TITLE
Verify PIN misfeature is annoying, makes incorrect assumptions about intended use

### ISSUE THREAD

**Issue by denisbider** [signalapp/Signal-Android#9783]
The misfeature that requires the user to verify their PIN *every few days* is not only annoying, but assumes the user wants to use a PIN that could be remembered.

I did not use a PIN I can remember. I randomly generated a miles-long PIN and stored it in a password manager.

The PIN is safe. The password manager is going to remember it. It has backups. It is inappropriate for Signal to keep asking to verify the PIN.

**Comment by alan-signal** [comment]
You can disable reminders in Settings->Privacy->PIN reminders.
