### ISSUE TITLE
Human emojis lack a) person without hair and b) (elderly) person with grey hair

### ISSUE THREAD

**Issue by scoder** [signalapp/Signal-Android#9784]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The differently coloured emojis do not just give a skin colour, they also give a certain (corresponding) hair colour. However, not everyone (regardless of gender) has hair, be it for personal preference, genetic, age, health or whatever reasons. Some health reasons are also temporary, in which case it might not be helpful/nice/empathic to send the person a reminder of what is missing or how that person "should" look.

Similarly, grey hair variants are missing entirely, although a large part of the world population, most notably elderly people, actually has grey hair. Most of the professions represented in the set of emojis do not prevent elderly people from doing them, but the set of emoji variants excludes them visibly.

I personally find it sad that a set of emoji variants that explicitly and clearly strives for inclusion in fact excludes so many people.

**Comment by greyson-signal** [comment]
Are these emojis just missing from Signal, or are they missing from the emoji standard entirely?

**Comment by scoder** [comment]
Good question. Looks like the Unicode standard has at least something to say on that topic:
https://unicode.org/emoji/charts/full-emoji-list.html#1f469_200d_1f9b3
https://unicode.org/emoji/charts/full-emoji-list.html#1f474
https://unicode.org/emoji/charts/full-emoji-list.html#1f475
https://unicode.org/emoji/charts/full-emoji-list.html#1f9d3

Don't know how the diversity variations are done in general, though.

**Comment by scoder** [comment]
Ok, learned something. The skin colour variation is done with "Fitzpatrick modifiers".
https://en.wikipedia.org/wiki/Emoji#Skin_color
Hair type/colour is not an option there.

**Comment by greyson-signal** [comment]
It looks like we do have the bald and elderly emojis available in our keyboard. We should be up-to-date with unicode 13 in general. If you see any missing, let us know :+1:. If you're specifically asking about reactions, we're tracking that work at #9776. Thanks!

**Comment by scoder** [comment]
Yeah, I think it's a general emoji standard issue, not Signal specific.

To clarify, I was not referring to the Unicode characters. Referring to people as specifically being elderly or bald has its context in conversations, but not when you are trying to refer to a bald programmer or grey haired gardener. Implicitly expecting humans to a) have hair that is b) not grey is still wrong.
