### ISSUE TITLE
Keyboard is rendered above messages / message view is not scrolled up some times when opening keyboard

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#9787]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes the keyboard (here gboard) is rendered about the latest messages and hides them needing manual intervention

### Steps to reproduce
- I don't know how to reproduce unfortunately

**Actual result:** Messages are hidden behind keyboard 
**Expected result:** Message view is scrolled up to the latest message when opening keyboard

### Device info

**Device:** Pixel 2XL and Pixel 3a
**Android version:** 10.0.0
**Signal version:** 4.64.7

**Comment by piratenpanda** [comment]
Since when does Signal save the scroll position when leaving the chat? I think this is what's confusing me here

**Comment by trahman-nep** [comment]
I am also having the same issue on iOS / iPhone 12 Pro Max

**Comment by piratenpanda** [comment]
Seems to be intended behaviour
