### ISSUE TITLE
6 Major Problems with Signal

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-Android#9788]
(From the latest update this broke my phone and now it over heats.

The android signal app isn’t working right. My phone is over heating because of signals last update. When will there we a fix anytime soon?

My phone says “Apps are over loading the cpu.”
25% on signal…
My phone is getting way to hot! and draining my battery like crazy.
Phone: Samsung Galaxy 7)

- A few weeks ago, posted here: 
https://community.signalusers.org/t/overheating-phone-after-update-on-2020-06-05/14764

Edit:
Just updated my phone last night, fixed most of over heating but is still warm and so what hot.
All Problems with Signal with the LASTEST UPDATE:
- 1 Messages are slow and don’t receive them right away. (Delayed) MAX of 7 Mins Delayed I have ever seen.
- 2 Calls don’t pop up when someone is calling you. There is no indication that someone is calling what’s so ever. ONLY on Android (Months of this being broken, not joking) Says Connecting on ios but never rings on when trying to call the Android phone.
ios to Android. NOT - Android to ios. (Incoming calls ios calling to Android) (Using Android)
- 3 After a call fails you don’t see a pop up (somewhat like 2 but different), you don’t even see a notification message at all.
- 4 Video calls over heating the phone now. Check the over heating problem again because its not fixed fully ever after the update fix it somewhat, not fixed.
- 5 Normal Calls leave your phone warm/ some what hot. (They fixed the overheating somewhat from the update last night but my phone is still getting warm without even charging it and I need to charge it…) I don’t want my phone to hurt itself when charging and leaving it signal on. The phone starts to get warm/hot again with charging and signal on.

- 2 Picture Proof:
This is the only thing you get after call fails (When someone is trying to call you get no notification message at all but this in the app it self.) fix this
https://community.signalusers.org/uploads/db3609/original/2X/9/91f29b810d4f5687b077df3a533adbc6e6a940af.jpeg

These things need to get fixed because I am done using this app until its fixed.
There is so many bugs and I can’t quite be on a call without these bugs pissing me off everyday!
Please do something soon.

Mr. Waste

Edit:
- 6
I forgot to share 1 more bug I have ran into is when signal is running on a call. It uses my mobile data and not the wifi even tho I have wifi connected, it still uses my mobile data by default and calls lag because of being in door of my house. (Samsung Galaxy 7s)

https://debuglogs.org/f2e82abcc7d9aa470299a1c12bc71ea8d6694aff4dc012803ca6431a3efdbf7b

**Comment by piratenpanda** [comment]
This is a very hard to read bug report. Why did you delete the template? Please use the template for the individual bugs you experience. Also this is not a discussion forum

**Comment by alan-signal** [comment]
Edited to remove `#`, as that causes issues to be linked on github.

**Comment by stefan8661** [comment]
I also faced overheating and battery drain during video call. Battery runs down so fast. Here is debug log. Device: Xiaomi mi 9t, Miui 11, Android 10. Didn't have these issues with spy app (WhatsApp)

https://debuglogs.org/4bbd326c52c0ee76570cd265e9b9b1f8a1d0865ad1deb70011aca1c6cd083e4e
