### ISSUE TITLE
Restored backup, Note to self shows up as conversation with old number

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9789]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

 -  I restored a backup of my main device (1) on a test device (2) and re-registered the test device with its own number. (1) and (2) have a different phone number.
 -  Note to Self was restored, but it now shows on the test device as a normal conversation with the number of (1) were all messages were sent by (1).
-  The chat I aleady had between (1) and (2) is now labeled “Note to self” on (2).

### Steps to reproduce
- Have 2 devices, (1) and (2).
- Exchange some messages
- Put something in Note to self on (1)
- Make a backup on (1)
- Delete all Signal data on (2) and restore the backup you made on (1) on (2) using the phone number of (2)

**Actual result:** Note to self and the chat with (2) seem to have switched place
**Expected result:** Note to self would be restored to note to self. I'm not entirely sure what to expect of the chat between (1) and (2), to put it in a chat with the number of (2) would probably give issues.

### Device info
**Device: 1** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.64.7

**Device: 2** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.64.7

**Comment by greyson-signal** [comment]
"Note to self" is detected by whether a conversation is with the number that is registered for this installation, so this behavior isn't unexpected. 

I don't think we're going to make any changes here for the time being.
