### ISSUE TITLE
Signal Message are delayed and don't give a notification pop up

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-Android#9793]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages are slow and don’t receive them right away when sending a message to android from my iphone. (Delayed) MAX of 7 Mins Delayed I have ever seen. 

### Steps to reproduce
- Open Signal Normally 
- Send a message to the android from my iPhone, the android phone doesn't receive the message instantly. Like there is a delay. 
- This happens not every time but happens quite a while. 15-20 times opening signal normally and closing of normal uses. Then this will happen. 

**Actual result:** 
- On the Android phone you could be not using it and the messages don't go through
(OR)
- Your using the phone and don't even know you have text message go through and there is sometimes a notifications that pop up all the messages at once or you don't even get a notification when all the messages go through

**Expected result:** Messages should have a delay or not send a notification at all when they do go through to the android phone. It should let the signal know there is text messages waiting for you. But no notifications! and its same with calls as well but I am sending more bugs reports after this one about the call problems.

### Screenshots

This happens with text messages exactly as with normal calls nofications. (sent to the android phone from my iphone)
![91f29b810d4f5687b077df3a533adbc6e6a940af](https://user-images.githubusercontent.com/49108816/85894822-52d16780-b7aa-11ea-9dc3-8e9e6dbdfcd1.jpeg)

### Device info

**Device:** Samsung Galaxy 7s
**Android version:** 8.0.0
**Signal version:** 4.64.7

### Link to debug log

https://debuglogs.org/f2e82abcc7d9aa470299a1c12bc71ea8d6694aff4dc012803ca6431a3efdbf7b
https://debuglogs.org/69a7dcaff3f58d44cc67fffdbafe19b2d1ed2e951bac4dd9b1c74e23b76ec470

**Comment by MrWaste** [comment]
Please let me know if the Debug Logs even work, they are a few weeks old but still show the problems.

**Comment by Nisc3d** [comment]
This sounds almost exactly like the issue I had.
One possible cause is the Android Battery Optimization. It kills the app in the Background, so it can't send Notifications.
Please make sure, you follow this guide and disable all Battery Optimizations for Signal: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications
Sometimes there still are problems, even after you disable the Optimizations, but it certainly helps.
Also there is already an issue for this, which is #8692.

**Comment by MrWaste** [comment]
@ Nisc3dIt happens sometimes but not happening all the time, will check it out and message back to you.
