### ISSUE TITLE
Signal Video Call not properly using speaker

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#9796]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I start a video call using the video call button, it won't properly use my phone's speaker. The volume is extremely low. You cannot fix it without hanging up and starting with a regular Signal call.

If I start a regular call first and then transition to video, I can then use the speaker properly.

### Steps to reproduce
- Start a video call using the video call icon

**Actual result:** Speaker isn't properly used or the volume is low.
**Expected result:** Should properly use the speaker.

### Device info
**Device:** Pixel 4
**Android version:** 10
**Signal version:** 4.64.7

### Link to debug log
https://debuglogs.org/b6abe360b273922475e592feb5331393ac026bf92769a46479d91cc2814e2b17

**Comment by szotsaki** [comment]
This is also the case with Sony XPERIA X, Android 8,0.0, Signal 5.0.8 both with normal and group video calls.

**Comment by DML38** [comment]
The same with huawei mate 20x

**Comment by victor-perez** [comment]
Same problem with the `Pixel 3a`, `Android 11` and Signal version `5.9.3`. the fastest way to fix it is to turn off video then click on audio and now you will have 3 options where from  **earphone** is selected. You can now select **speaker** and then turn on you video and now it works with both video and speaker

**Comment by Tursko** [comment]
I’m still encountering this issue. Had a group video call and the speaker audio was so low when compared to other apps/music.

**Comment by JoseAntonio4621** [comment]
So, I have a Galaxy A55 in whihc this issue is still present. There's no way (not even the workaround mentioned) to make the phone speakers work when video call is on. Was this already raised soon?

**Comment by hozza** [comment]
This is still an issue on older Pixel phones. Absolutely hate stalebot.
