### ISSUE TITLE
Hard to use built in emoji in image descriptions

### ISSUE THREAD

**Issue by billie80** [signalapp/Signal-Android#9800]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When editing image descriptions in messages with multiple images the built-in emojis are not directly accessible.

### Steps to reproduce
- attach more than one image to a signal message
- in the message input field both built-in and system emojis are available and it is possible to switch back and forth
![01](https://user-images.githubusercontent.com/9938306/85945695-d83a5080-b93f-11ea-9208-8a916119c71c.png)
- in the image description input field only system emojis are available
![02](https://user-images.githubusercontent.com/9938306/85945698-dcff0480-b93f-11ea-808c-aa84f58d26e2.png)
- however it is possible to work around this by closing the keyboard using the back button, leave the image description input field active and click on the built-in emoji picker from the message input field
![03](https://user-images.githubusercontent.com/9938306/85945953-5f3bf880-b941-11ea-8e11-b57f2b41e636.png)
- then it is possible to add built-in emojis to the image description
![04](https://user-images.githubusercontent.com/9938306/85946200-f6ee1680-b942-11ea-80c3-7521a0b0e04c.png)
- once switched to the normal keyboard the workaround needs to be used again to get beck to the built-in emoji picker, so switching back and forth between normal keyboard and emoji keyboard is not possible

### Notes
There is already pull request #9720 which adds the possibility to use built-in emojis in more places but the image description input field is not addressed there.

**Actual result:** Using the built in emojis is only possible using workarounds
**Expected result:** Emojis should be accessible directly.

### Device info

**Device:** Samsung Galaxy S5 Mini
**Android version:** 6.0.1
**Signal version:** 4.64.7 (6641)

### Link to debug log

https://debuglogs.org/7bc3a71380367d84fe9c1b5bd8d5ce7f6a31c4f23b7f54d120c8c3cab4ea2a2a

**Comment by billie80** [comment]
Probably this is obsolete with the new media send flow as for now there are no individual captions allowed anymore. Hopefully they are coming back though.

**Comment by greyson-signal** [comment]
Yeah, I think this issue is moot for now.
