### ISSUE TITLE
Signal doesn't jump to first unread message, scrolls position to bottom of chat

### ISSUE THREAD

**Issue by piramiday** [signalapp/Signal-Android#9801]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when opening a chat with unread messages, quite often Signal will jump to __the last message__ in the chat, as opposed to **the first unread message**.

I've also witnessed the opposite, although quite rarely.
in such a case I have a _fully read_ chat, and Signal jumps to what _used to be_ the first unread message, as opposed to jumping to the last message.

this bug seems to be introduced in one of the last versions, since this workflow has always worked quite smoothly for me (apart from #8924).

### Steps to reproduce
I'm not sure this can be reproduced all the time, but something like:
- have a chat with unread messages
- from the main Signal screen, click on the chat
- notice at what point of the chat Signal is putting you.

**Actual result:** Signal puts you at the very bottom of the chat, at the last message, making you scroll your way up to find your first unread message.
**Expected result:** Signal should put you at the halfway-through scrolling position, exactly where the first unread message is.

### Device info
Verified on several devices: Nexus 5X, Pixel 2, and Sony Xperia XA1, all with the latest Google Play Signal version, 4.64.7.

**Comment by jimmycasey** [comment]
This is a deal breaker for large group chats.

**Comment by superhadoken** [comment]
Currently in a group chat with multiple users that have migrated from WhatsApp and they're now complaining this is a deal breaking issue for them and makes catching up with the conversation very difficult.

**Comment by jonoc4** [comment]
Same issue here on android. My friends are constantly bringing it to my attention. They cant catch up on previous messages in the group chat because it is automatically scrolling to the latest message as soon as one comes in. These are new users in the last two weeks. I don’t have the issue either do others who i chat with that have had the app installed already since before the influx. All on android.

**Comment by Steven0054** [comment]
I have a replicable report from a friend I recently moved to Signal from whatsapp:

Samsung Galaxy Note9 (SM-N960W)
Android 10 - OneUI 2.5
Signal 5.3.7.1 (Downloaded through signal.org/android/apk though it was also occurring on the play store version also.)

This is making migration from Whatsapp so difficult..

**Comment by greyson-signal** [comment]
Hi there, we have a hopeful fix for this in 5.3.12 (in beta, currently rolling out to prod). Please re-open if it's still a problem in that release. Thanks!

**Comment by jimmycasey** [comment]
Great stuff @greyson-signal , thanks for update.
