### ISSUE TITLE
ConversationListFragment Empty State is Visible While Messages are Loading

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#9803]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you have no messages in Signal, you see an empty view like the one pasted below.

One thing I've noticed recently is that on my phone that I regularly use for Signal, there's a bit of a delay where it takes the app a second or two to load all of my conversations. During this period, for a split second, the empty state is displayed until is is quickly replaced with the list of conversations.

### Steps to reproduce
I'm unable to reproduce this in an Android Emulator, I suspect that maybe this is because I have a lot of conversation data on my primary device. 

**Actual result:** Empty state is displayed, then is quickly replaced with my conversations 
**Expected result:** I would expect a blank screen to be displayed while it is unknown whether or not I have conversations, and once that is determined either my conversations or the empty state.

### Screenshots

![image](https://user-images.githubusercontent.com/22125581/85969945-17e05700-b997-11ea-907e-9d23ad3c8de2.png)

### Device info
**Signal version:** 4.64.7

**Comment by greyson-signal** [comment]
Hi there, is it possible for you to post a debuglog link (Settings > Advanced > Submit debug log)? I'm unable to reproduce the issue.

**Comment by bitmold** [comment]
Is there a way I can privately send that log to you?

Also I was wondering if there's an easy way to add a lot of test conversation data in the Android Emulator. I'm seeing this issue often on my device, I wish I didn't have the release version right now so I could use the debugger :/

**Comment by Tursko** [comment]
Just encountered the issue. 
https://debuglogs.org/149ad0f261ea11be3bcc0ff6606463b76c541e5ba996e108567def8d71120892

**Comment by bitmold** [comment]
@Tursko if you can could you please explain which parts of those logs point to the bug - thanks

**Comment by Tursko** [comment]
Time was 17:08 / 17:09

**Comment by Nisc3d** [comment]
I experience this bug several times a day. Here is a debug log: https://debuglogs.org/124bb9e36ce5a5574a64ee83a87bd8b2108e53719d72a9d6e15cf5455617b517

**Comment by Nisc3d** [comment]
Another one, right after it happened: https://debuglogs.org/d4ee97dcb6218040a6bb020e034a30c04dae707eab1a6fd09ae7c7507a7de859

**Comment by greyson-signal** [comment]
I finally think I figured out what was causing this, and I've hopefully fixed this in the 4.68.x beta. If you get a chance, try it and let me know if it's still happening :+1:
