### ISSUE TITLE
Signal slow, cannot send messages, phone overheating, battery draining, no debug log

### ISSUE THREAD

**Issue by equaeghe** [signalapp/Signal-Android#9805]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
* Signal is slow (the message lists open with a delay of more than ten seconds; previously it was essentially instantaneous).
* I cannot send messages (including SMS, and I'm not receiving any either); I get a spinning circle when I try (Note to self worked, but very slowly.)
* My phone overheats while Signal is active (I need to kill it)
* My battery is drained while Signal is active (I need to kill it)
* There is no debug log (or it is empty) and I get an error when I hit the upload button

I have a feeling this is related to the 4.64.7 update. I'll give a descriptive account of what happened before and at the beginning of when the issues manifested themselves:

*A little before I updated to Signal 4.64.7, I got a “Message could not be decrypted” messages from one contact. I fixed that by resetting the secure session. However, the “Message could not be decrypted” messages started to appear again soon after that. (In the mean time, I had updated Signal to 4.64.7 myself.)*

*After the update, I’ve had the issues with Signal described above. One of my contacts has similar problems on a different device. Another one I've not been able to reach; I assume they may have a similar issue.*

*Regarding the battery drain: this is really reproducible: after restarting Signal it starts again. However, my battery monitor doesn’t show Signal as the one responsible.*

### Steps to reproduce
- start Signal

**Actual result:** Issues described above.
**Expected result:** No issues, as before.

### Device info

**Device:** Samsung S4 Mini Duos (serranods; GT-I9192)
**Android version:** 8.1.0 (LineageOS 15.1)
**Signal version:** 4.64.7

### Link to debug log
Unavailable!

**Comment by equaeghe** [comment]
I have uninstalled and reinstalled Signal. That fixed the issue. Nevertheless, I think there is a bad bug here, as Signal shouldn't be behaving like what I encountered under any circumstances. Its CPU time usage which I guess caused the overheating and drainage should be bounded in some way.

**Comment by codethief** [comment]
I haven't experienced any of the overheating issues but Signal has become a lot slower for me, too, in recent versions. While it's not sluggish *all the time*, I still sometimes need to wait for 5 seconds until a conversation is shown or till I get to see my list of conversations.

**Comment by greyson-signal** [comment]
@codethief Feel free to share a debuglog taken after a long conversation open.

**Comment by codethief** [comment]
I haven't run into this issue in a while – recent Signal versions seem quite responsive, even though my message database has grown significantly. So I suppose this can be closed.
