### ISSUE TITLE
Echo when calling from Galaxy A5 2017 to Iphone 6S

### ISSUE THREAD

**Issue by MattRGX** [signalapp/Signal-Android#9809]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A lot of echo on my GF side when i call her. She has an iPhone 6S and i have a Galaxy A5 2017. She has echo when i call her in normal call, when speaker is ON and also in video call. Actually, she always has echo when i call her.

### Steps to reproduce
- Call an iphone 6S from a Galaxy A5 2017
- Video call an iphone 6S from a Galaxy A5 2017

**Actual result:** Echo on iphone 6S side
**Expected result:** No echo

### Device info

**Device:** Samsung Galaxy A5 2017
**Android version:** 9 (PIE)
**Signal version:** 4.63.3

**Comment by ozgurakyazi** [comment]
Welcome to the club, #9351 ,  #9817 . You are either lucky or have still months ahead. My solution to this, let the other side call you. It is working for me. Even though it is not the best solution, we got used to it. Seems like the team has not been caring about this a lot.

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5
