### ISSUE TITLE
Restoring settings from pin backup causes signal to crash

### ISSUE THREAD

**Issue by ashmastaflash** [signalapp/Signal-Android#9811]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On PIN entry, after reinstalling Signal, Signal crashes repeatedly and never recovers. It seems like Signal is trying to load the contacts backup and encounters some inconsistency which it can't handle. missingRecipientException.

### Steps to reproduce
- Install Signal
- Set a PIN
- remove and reinstall Signal
- Enter PIN
- Signal dies within seconds of starting.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Signal dies within seconds of starting. However, if the phone is in airplane mode, it does not die until connectivity is restored. This situation also prevents the submission of error reports from the app.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Signal should not die.

### Device info

**Device:** Samsung Galaxy S9+
**Android version:** 10
**Signal version:** 4.64.7

**Comment by greyson-signal** [comment]
Since it seems like you see an exception, can you post a stacktrace or adb log?

**Comment by ashmastaflash** [comment]
I can't transmit a debug log because Signal dies before it's sent. But I can do screenshots with the network switched off...

![Screen Shot 2020-07-01 at 10 48 19 AM](https://user-images.githubusercontent.com/5561645/86275756-9fd98300-bb88-11ea-9f39-83fdf958be26.png)
![Screen Shot 2020-07-01 at 10 48 29 AM](https://user-images.githubusercontent.com/5561645/86275779-abc54500-bb88-11ea-8b48-1db0ad4e9d8c.png)
![Screen Shot 2020-07-01 at 10 48 53 AM](https://user-images.githubusercontent.com/5561645/86275795-b1bb2600-bb88-11ea-9af3-c3e3f9eb04b6.png)

**Comment by greyson-signal** [comment]
While I can't personally reproduce this, I *think* I know what may be happening. I've put a potential fix into 4.66, which will likely go to beta in a couple days.

**Comment by greyson-signal** [comment]
If you're interested, you can email me at greyson@signal.org and I could get you a build with the potential fix sooner, and we could see if that fixes it :+1:
