### ISSUE TITLE
Feature suggestions for stronger privacy

### ISSUE THREAD

**Issue by MrYingNYang** [signalapp/Signal-Android#9818]
I wonder if a tor integration would make the communication between two users more privat when the default relay server is used since it would be almost impossible to correlate if two Users are communicating or not.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by MrYingNYang** [comment]
> 
> 
> Please use the community forum for feature requests https://community.signalusers.org/

Thanks buddy will do!
