### ISSUE TITLE
Signal forcing PIN creation

### ISSUE THREAD

**Issue by bulgyharriet** [signalapp/Signal-Android#9819]
Title.

**Comment by grandchild** [comment]
Duplicate of #9812.

**Comment by bsteindl** [comment]
But it's not fixed yet

**Comment by cpmcgrath** [comment]
I'm not sure if the developers are still looking at 9812, but there's been a lot of constructive comments since it was closed. Please read and reconsider.

**Comment by najtin** [comment]
this is a total deal breaker for me. I use signal because i do not want a cloud backup of anything. I will migrate to https://github.com/matrix-org where i means my entire family and me.

**Comment by greyson-signal** [comment]
Closing as duplicate of #9812
