### ISSUE TITLE
Image is half black when/after sending

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#9825]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending an image it sometimes becomes half black, even when you open it in fullscreen. For other people the image is shown normally.

### Steps to reproduce
- share in image to a signal contact or group over the gallery or over signal itself
- press the send button
- while sending it is half black and stays so after sending is finished

**Actual result:** The image is half black
**Expected result:** The image should be normal, like in the Android gallery

### Screenshots
![blackimage](https://user-images.githubusercontent.com/7361310/86614846-e3caee80-bfb3-11ea-9dee-e4db09103ef4.png)

### Device info
**Device:** Nokia 6
**Android version:** 9
**Signal version:** 4.65.2

### Link to debug log
https://debuglogs.org/b9d59ca33915df233e0d645d585c350ad04e88f9cdbb9bbf8071aac6e781a086

**Comment by Larx** [comment]
Similar problem, Samsung S7, Lineage 17.1: Here image is partially blurry, not black. Happens sometimes, not always.

**Comment by robo2bobo** [comment]
Same problem here. Its not consistent, it happens sometimes but not always.

I've asked my contacts if the image was received and they tell me its ok on their side. Maybe its just the thumbnail creation on the sending side that is broken.

**Comment by greyson-signal** [comment]
There's a duplicate somewhere of this, but I can't find it :/ But basically this is an issue with glide (our image library) mis-rendering something, and then caching that bad image. The image is sent correctly, just not rendered properly on the send side. You can go to the sysem app settings, clear your cache, and restart the app to see that it gets fixed. But yeah, gotta figure out what's happening here.

**Comment by bme13** [comment]
Think this is the one: #9082
