### ISSUE TITLE
SMS contact's name is not centered in message view

### ISSUE THREAD

**Issue by elya5** [signalapp/Signal-Android#9829]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The contact name for SMS contacts is not centered any more but the phone number that was previously below is also not shown. Now it is inconsistent with Signal contacts.

### Steps to reproduce
- Open conversation with SMS contact

**Actual result:** Contact name not vertically centered
**Expected result:** Centered name

### Screenshots
![Screenshot_20200707-133609](https://user-images.githubusercontent.com/4464481/86776398-77ee9180-c058-11ea-91fc-d80a5561e897.png)

### Device info
**Device:** Moto G6 Plus
**Android version:** 9
**Signal version:** 4.65.2

**Comment by Sgn-32** [comment]
Fixed in 4.77.0 with https://github.com/signalapp/Signal-Android/commit/8e39267c42f23759334ac72b7e272e84749439ab
