### ISSUE TITLE
No indication of newly added group user for the person who added the user

### ISSUE THREAD

**Issue by christianfl** [signalapp/Signal-Android#9830]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When adding a group member to a Signal group there is no indication that a user has been added on the device which added the user. However, there are infos that a new user has been added to the group for other users of the group.

I accidentially added a group member and could not reporoduce that I added him afterwards on my device. This led to a user we didn't want in our small group for a short period of time until I luckily opeded our group details again.

### Steps to reproduce
- Go to a group
- Click on the group name from within the group
- Tap on "Add member"
- Add a member and click the checkmark

**Actual result:** Member gets added. On the device where a user adds another member there is no hint that a user has been added. Only "You updated the group".
**Expected result:** There should be a message indicating that a user has been added to the group.

### Screenshots

From within the account that added a group member ("You have updated the group"):

![my-view](https://user-images.githubusercontent.com/11208965/86785086-88a40500-c062-11ea-9068-fd6496c3e7ff.png)

From another group member ("XXXX has updated the group. XXXX has been added"):

![other-view](https://user-images.githubusercontent.com/11208965/86785124-9194d680-c062-11ea-8ed1-e21701fc5f28.png)

### Device info

**Device:** Google Pixel 2
**Android version:** 10
**Signal version:** 4.65.2

**Comment by Sgn-32** [comment]
In the "New Groups" (group version 2) are more hints. Also "You added XXXX".

**Comment by christianfl** [comment]
Tried it, you are right @Sgn-32 ! Can't wait to have the possibility to convert old groups to v2.
