### ISSUE TITLE
Voice message can't play in the background which working great on ios 

### ISSUE THREAD

**Issue by jinhuaxinxi** [signalapp/Signal-Android#9839]
Many times I need listen very long voice message , but after the phone is locked , it will stop , I really need that it can play in the background , Please add the little function , thanks !

**Comment by igor2x** [comment]
Signal project is using Github for bug reports only. Feature request should be opened and discussed in very vibrant forum. Please joing: https://community.signalusers.org/ publish and discuss feature request.

Please also close down this report in Github or developers will.

**Comment by jinhuaxinxi** [comment]
Thanks
