### ISSUE TITLE
Getting Blocked and Unblocked. No Message/Call. Very Slow Operation. Huge Power Consumption

### ISSUE THREAD

**Issue by ozgurakyazi** [signalapp/Signal-Android#9844]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After getting **blocked** and **unblocked**, I cannot exchange messages or call with the person on my phone (Messages in desktop app is working). Signal started to consume huge power, and sending messages are significantly slowed down to all other recipients. It was faster. My sent messages and the counterpart's messages look like they are delivered but I never get a read receipt on my phone. When I send a message, and I check my desktop app, I see the read receipts. 
### Steps to reproduce
- A blocks B.
- B sends message to A.
- A unblocks B.
- A/B sends message to B/A.

**Actual result:** The messages do not arrive on phone A nor B. Calls do not work between A and B, but others are ok. Power consumption of Signal is huge. Sending messages to other people work (but slow).
**Expected result:** Messages and calls are successful. Signal consumes power as it used to do. Messages are fast as before.

Debug Logs:
Person A: https://debuglogs.org/14e6c0de0d52ff3ef0c8763e06ca5972d54c9c72d78796651a4e9d3a80de037e

Person B: https://debuglogs.org/105a806cb21919f8606502aedf60455e8a25bcd6a6b57591d5dc6d499e3f37fb

**Comment by greyson-signal** [comment]
Are you able to get a debuglog from the person you're talking to? Do you also know if they're an iOS or Android user?  Your logs indicate that you're getting blasted with tons and tons of read receipts, so many that your phone is having difficulty processing them all (hence why you'd see increased power usage).

**Comment by ozgurakyazi** [comment]
There are 2  debug logs and A is Person A. The person I am talking to.    Do you want debug logs from person C or D (with successful message exchange but not related to block/unblock stuff).
In the debug log, I can see it is an android 8.1.0. I am confused with your questions.

Thank you for your help :)

**Comment by greyson-signal** [comment]
Sorry, I didn't interpret A/B as two different people at first, but I understand now :+1: I've got all I need, thank you!

**Comment by njmdietrich** [comment]
I can report that blocking/unblocking creates issues with messages and calls not coming through anymore. This is using the android version. I have not observed increased power consumption or slowdown though. Would it help to provide another debug log?

**Comment by armsp** [comment]
Same issue here

**Comment by Chatron** [comment]
Hello, 
Can confirm the iusse. Can't write anymore with persons ho were blocked an unblocked.

**Comment by greyson-signal** [comment]
@armsp @Chatron Can you share your logs?

**Comment by Chatron** [comment]
@greyson-signal thanks for responding.
The two logs from the two devices are:

https://debuglogs.org/82173b8040a11da81075eb49db143a7f5d6bb248cb1a7a18038415f6e8508468

https://debuglogs.org/a90bdfa7dae172b553e329a2209ecda303faac910fa0e9eb047a462ff6a2975b

Hope this will help resolve the problem. I don't wanna use another messenger app.

**Comment by Chatron** [comment]
Update:  seems that uninstall and reinstall Signal on booth devices resolves the problem until the next block.
