### ISSUE TITLE
Not Importing android studio

### ISSUE THREAD

**Issue by MilanSorathiya** [signalapp/Signal-Android#9845]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by johanw666** [comment]
You should open the Signal repository as an existing app in Android studio, not import it.

**Comment by MilanSorathiya** [comment]
but in many error generated while open it

**Comment by MilanSorathiya** [comment]
can you mail me wall project as zip

**Comment by johanw666** [comment]
If you clone the repository and build you need to have Git installed AND in the search path. And you always get a signing error with the current build.gradle, you can ignore that.

**Comment by greyson-signal** [comment]
Hi there, we only use github for tracking bugs. For technical support, please ask [the forum](https://community.signalusers.org/). Thanks!
