### ISSUE TITLE
Acknowledgement about 5 fixed values in BitmapUtil.java

### ISSUE THREAD

**Issue by shaswata56** [signalapp/Signal-Android#9848]
Hey, can you tell me how these values are related to Image compression?

```java
  private static final int MAX_COMPRESSION_QUALITY          = 90;
  private static final int MIN_COMPRESSION_QUALITY          = 45;
  private static final int MAX_COMPRESSION_ATTEMPTS         = 5;
  private static final int MIN_COMPRESSION_QUALITY_DECREASE = 5;
  private static final int MAX_IMAGE_HALF_SCALES            = 3;
````

Especially "MIN_COMPRESSION_QUALITY_DECREASE". And what should be the value of those respectively if I want to disable compression?

https://github.com/signalapp/Signal-Android/blob/6515a6188bb5ac025d8a242adc9fe88f5fab621b/app/src/main/java/org/thoughtcrime/securesms/util/BitmapUtil.java#L43

**Comment by alan-signal** [comment]
Please use the community forum for development queries https://community.signalusers.org/

These constants control what value is eventually passed to the android function `Bitmap.compress`. So their meaning is covered in android documentation.
