### ISSUE TITLE
Crash after receiving code 

### ISSUE THREAD

**Issue by jhlochner** [signalapp/Signal-Android#9851]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I received the following message and now the app always crashes if I open the conversation with the message.
Message:
```
pdf(z) = \begin{cases}
    (1 + \xi z)^{-\frac{\xi +1}{\xi}}&\hspace{.5cm}\xi\neq 0  \;, \\
	\exp{-z}&\hspace{.5cm}  \xi= 0\;.
    \end{cases}
```

### Steps to reproduce
- send the message above from phone A to phone B
- open the conversation in phone B
- experience crash

**Actual result:** Crash
**Expected result:** display the conversation with the sender of the message

### Screenshots
nothing to see. signal just closes. no error message or similar things.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 9 
**LinageOS:** 16.0
**Signal version:** 4.66.3

### Link to debug log
Signal Crashes as well when I try to send the debug log.

**Comment by greyson-signal** [comment]
Given that we don't parse message contents or anything, the crash is likely incidental. Alternatively, your OS could be parsing on-screen text to provide suggestions and stuff, unclear. Regardless, hard to do much with a crash log, and as a sanity check I've tried sending that text to several devices and have been unable to reproduce it.

If you're up for it, you could use `adb` to retrieve logs from your device:
- Download [here](https://developer.android.com/studio/releases/platform-tools)
- Run `adb logcat > mylogs.txt`
- Reproduce crash
- Stop adb command and send me the logs

**Comment by 0TWAIN0** [comment]
Thank you for your reply. The problematic message moved up in the conversation timeline, so now the crash only happens, when I scroll up till the message should be displayed. 

Here is the log file: [androidlogs.txt](https://github.com/signalapp/Signal-Android/files/4930354/androidlogs.txt)

Seem to be this one: 
`
07-16 10:43:19.922 18643 18643 E SignalUncaughtExceptionHandler: java.lang.ArrayIndexOutOfBoundsException: length=34; index=34
`
