### ISSUE TITLE
Cannot remove Signal contacts and legacy group association, group info and member IDs; Signal is exposing metadata forever.

### ISSUE THREAD

**Issue by jos128** [signalapp/Signal-Android#9852]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There seems to be no way to really delete a Signal contact. Dead contacts are messing up my contact list. Fall-back to user's display name allows for impersonating other contacts. 

### Steps to reproduce
- Delete contact from Android contacts app 1.7.21.
- Get warning: "Read-only accounts in this contact will be hidden, not deleted."
- Click "Ok".
- Go to Signal's contact list.

**Actual result:** The deleted contacts still appear in Signal's contact list, but with *display name only*. On *newly* linked devices, these contacts appear as numbers only. This falls together with the reappearance of long deleted groups and conversations *on newly linked devices*, both iPadOS client and desktop.  

**Expected result:** Gone, what I want gone: Contacts, groups, conversations.

### Device info
**Signal version:** 4.65.2

**Comment by jos128** [comment]
Basically the same issue: #4678

How is this still a thing since 2016?

How do I get rid of the zombie numbers in my Signal contacts list?

I am starting to feel really bad about Signal. Which data gets saved *forever*, the possibility to use this for identity fraud, ... Not good.

**Comment by jos128** [comment]
Just saying, this is still a thing in **Signal 5.0.8**.

**Comment by julianfairfax** [comment]
I wrote a forum post that addresses this issue. If you're a user with feedback or experiences to share, or a developer who can actually take a look at implementing this, please check out the post: https://community.signalusers.org/t/handle-contacts-properly/36807
