### ISSUE TITLE
[BUG] Endless respawns of new installers when doing update. Results in hard crash. (Windows 10)

### ISSUE THREAD

**Issue by demux4555** [signalapp/Signal-Android#9854]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have seen this happen enough times now for me to decide to create a bug report. I think this is the fourth time in the last year.

Sometimes when clicking the update button in the client, nothing will happen for several minutes. No abnormal CPU usage or anything like that. The client is still running normally, it simply seems to not initiate the update process.

Then suddenly after several minutes (perhaps two or three), the client will close, and two or three Signal Setup will show on the task bar. The CPU usage goes to 100%, and the system becomes extremely sluggish, to a point where it's quickly impossible to even right click the task bar to open Task Manager. After a while there will be spawned more and more installers, filling up the task bar. The system will now becomes totally unresponsive. Mouse pointer cannot be moved, Ctrl Alt Del doesn't work. But more installers are still being produced on the task bar. In the end there might be perhaps 30-40 installers running, and it's obvious it's impossible to recover from this situation, so I have to hold the power button on the system to force a power off. (After the restart, I just manually download the newest installer and do it this way instead.)

### Steps to reproduce
- hit Update button in client when there is a request to do so.
- Wait while you wonder why nothing is happening.
- Wait.
- Wait until you forget that you actually are updating the Signal client.
- Client suddenly closes.
- Several installers show up on task bar.
- Sit back and observe as your system quickly sinks further and further down into The Bog of Unresponsiveness.
- Give up and hit power button.

**Actual result:** System crashes hard.
**Expected result:** Signal client should close, run the installer to do its update. Signal restarts. All done.

### Screenshots
Impossible to do screenshots wile this is happening.

### Device info
Windows 10 Pro, English [Version 10.0.18363.900]

### Link to debug log
https://debuglogs.org/e366444d19a229b3d8909d5b0463911d0a064f2fbcf175d1d598c06a275e6b60

**Comment by Nisc3d** [comment]
This is the wrong place. Issues for the Desktop App are here: https://github.com/signalapp/Signal-Desktop/issues

**Comment by demux4555** [comment]
Oops, I never looked at the path of this github. If anyone in charge reads this, feel free to delete the post :)
