### ISSUE TITLE
Message is empty

### ISSUE THREAD

**Issue by primarto** [signalapp/Signal-Android#9857]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When we type a message to someone, and when we press the "send" button two or three times very quickly, the message "Message is empty" appears.

### Steps to reproduce
- Press "send" button several time very quickly

**Actual result:** Appears "Message is empty"
**Expected result:** "Message is empty" It should only appear when we try to type only a blank space and click the "send" button
### Device info

**Device:** /
**Android version:** 10
**Signal version:** 4.66.5

### Link to debug log
 /

**Comment by primarto** [comment]
It also continues in 4.78.5v.


@cody-signal

**Comment by greyson-signal** [comment]
Seems perfectly acceptable to say 'Message is empty' when there's nothing there, whether it's a space or literally no content. At minimum, this seems like less of a bug and more of a preference. I'm gonna close this, but feel free to discuss on the [forum](https://community.signalusers.org/).
