### ISSUE TITLE
on start Signal requests location without cause

### ISSUE THREAD

**Issue by JanZerebecki** [signalapp/Signal-Android#9859]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On start Signal requests location without cause.

### Steps to reproduce
- Did this quite a few versions ago, maybe not needed for reproduction: Share a location once, allow once with Privacy Guard, have it crash because of https://github.com/signalapp/Signal-Android/issues/9101
- Start Signal
- Click deny in Privacy Guard popup asking to allow location request

**Actual result:** On start of Signal makes a location request that is noticed because of LinageOS Privacy Guard
**Expected result:** Signal should only request location when it is shared

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0 Linageos with microg
**Signal version:** 4.66.5

**Comment by ristein** [comment]
also experiencing this since latest (same) version.
Signal requests location, which is shown in statusbar, without any reason

**Comment by tretkowski** [comment]
This issue should be reopened, it happens with 5.39.3.
