### ISSUE TITLE
Signal doesn't send insecure SMS when secure message pending

### ISSUE THREAD

**Issue by redfast00** [signalapp/Signal-Android#9864]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I'm offline, I tried to send a message with Signal. This of course did not work, because I didn't have internet. I then tried to send an insecure SMS with Signal, but this SMS stayed in the "pending" state and did not get delivered.

### Steps to reproduce
- Disable internet
- Send a regular message to a person, this should not get delivered
- Long-press the send button to select "insecure SMS", then send using that method

**Actual result:** Both the regular message and the SMS don't get delivered
**Expected result:** The regular message stays pending, the SMS gets sent

### Device info

**Device:** Oneplus 2
**Android version:** 10
**Signal version:** 4.66.5

**Comment by pmiossec** [comment]
Got it also with:

**Device info**

**Device**: Oneplus 5T
**Android** version: 10
**Signal version**: 4.77.3

Very frustrating!

Perhaps it could be interesting to fallback by default to "insecure SMS" when phone is offline (there is no internet connection)...

**Comment by greyson-signal** [comment]
Oh this is interesting, I do like the suggestion and understand the frustration. In areas with poor service, a data message can get stuck but an SMS can go through. The reason they currently block each other is because we take great care to ensure the message sends are done sequentially within a conversation, but it shouldn't be hard to put SMS and Signal messages in different "queues".

**Comment by pmiossec** [comment]
Just to add that the problem is the same if the receiver is also offline and that's even more problematic because you can no more send him SMS messages until he goes online again.

You can't even use another SMS application to send a SMS because android don't let you do it until you set it as the default one 😢 

So this bug makes Signal pretty unreliable as a SMS application 😭 

@greyson-signal Is something planned to work on a fix?

**Comment by tomjennings** [comment]
I had opened a ticket on this problem some time back (#9947), merged with this.

I have noticed since then that iPhones/iOS allows its native Messages to coexist with Signal, where Android requires choosing either/or. This could be diluting problem reports.

**Comment by Tursko** [comment]
> Oh this is interesting, I do like the suggestion and understand the frustration. In areas with poor service, a data message can get stuck but an SMS can go through. The reason they currently block each other is because we take great care to ensure the message sends are done sequentially within a conversation, but it shouldn't be hard to put SMS and Signal messages in different "queues".

This issue becomes very apparent during Signal outages. All my SMS messages are pending since I had sent Signal messages before hand.

**Comment by tomjennings** [comment]
> In areas with poor service, a data message can get stuck but an SMS can go through. The reason they currently block each other is because we take great care to ensure the message sends are done sequentially within a conversation...

Then there is an attack surface. Kill one data packet, and _all future messages_ are effectively stopped. Kill the data path or one packet at the target.

Even a time out would help. 100 hours? Or have re-registering clear out state.

That Signal only works in urban areas is not heartening.

**Comment by major-mayer** [comment]
It's a pity that this issue is still present 😞

**Comment by Tursko** [comment]
This commit should hopefully solve this issue. 

https://github.com/signalapp/Signal-Android/commit/e72be42eff17cd441707724d46dc88e484b2259e

**Comment by redfast00** [comment]
Cool, will reopen if issue is still present in a few weeks.

**Comment by Tursko** [comment]
The fix is now in production. Just tested it out and it worked perfectly.
