### ISSUE TITLE
Video call orientation wrong with back camera

### ISSUE THREAD

**Issue by blaueente** [signalapp/Signal-Android#9865]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I switch to back camera during a video call, the other party sees the picture upside down.

### Steps to reproduce
- Have Video Call with front camera
- Switch to back camera during call

**Actual result:** the receiving party sees an upside down video
**Expected result:** the receiving party sees a correctly oriented video.

### Device info

**Device:** bq Aquaris X2 Pro
**Android version:** 10
**Signal version:** 4.66.8

### Link to debug log
https://debuglogs.org/5a59c9e39b34520e4ded69e8d8ae30644f88218afca41aa55d997e88ad2d6155

**Comment by akuehntopf** [comment]
I'm having the same issue here. Is there anything we can do to help debug this?

**Comment by cody-signal** [comment]
> I'm having the same issue here. Is there anything we can do to help debug this?

What device do you have and could you provide debug logs.

**Comment by akuehntopf** [comment]
Hi Cody,
I'm seeing this on the following Devices:

- Pixel 4a (Android 11)
- Xiaomi Mi A2 (Android 10)
- Moto G5 (Android 8)

I'm happy to help tackle this issue and will follow the steps mentioned in the Wiki regarding debug logs.

**Comment by cody-signal** [comment]
Thanks for getting back to @akuehntopf 

> I did the following steps:

During a call if you change the orientation of the device we don't change anything about the video feed (sending or receiving). Not saying we shouldn't, just that we don't currently. Your repro steps make sense to me as turning 90 degrees on both devices (if you turn the same direction) would result in a 180 degree rotated image. If you rotate opposite, it'll cancel out and appear correct but the app isn't really doing anything, it's just optics.

Your repro steps also seem different to what the original issue is about where the image is inverted by switching to the back camera and has nothing to do with device rotation. Let me know if I'm misunderstanding something.

**Comment by akuehntopf** [comment]
Thanks for your reply @cody-signal.

So basically an orientation change handler that reorientates the video stream would need to be implemented?
Are there any plans for that yet?

Sorry if i hijacked this issue, it kinda sounded like a similar problem. 
Do you want me to open another issue?

**Comment by cody-signal** [comment]
@akuehntopf There have been brief conversations about handling rotation with media differently than we do currently, but nothing concrete yet.

At this point we've left bug territory and entered feature behavior changes. I'd recommend taking this over to our [community forums](https://community.signalusers.org/) and discussing the changes you'd like to see there and see if anyone else feels similarly. We use GitHub Issues only for bugs. Our product and UX research teams browse the forums for these types of requests.

**Comment by blaueente** [comment]
> Thanks for getting back to me @akuehntopf
> 
> > I did the following steps:
> 
> During a call if you change the orientation of the device we don't change anything about the video feed (sending or receiving). Not saying we shouldn't, just that we don't currently. Your repro steps make sense to me as turning 90 degrees on both devices (if you turn the same direction) would result in a 180 degree rotated image. If you rotate opposite, it'll cancel out and appear correct but the app isn't really doing anything, it's just optics.
> 
> Your repro steps also seem different to what the original issue is about where the image is inverted by switching to the back camera and has nothing to do with device rotation. Let me know if I'm misunderstanding something.

I now saw that I forgot to mention that the original concerns landscape only. With both ends in portrait there is no problem.

Therefore I now carefully re-tested this, and found that it is simply an unintuitive geometric property that should be compensated and isn't:
1. If both ends use front cameras and landscape, and orientation is wrong, one end can rotate the phone by 180° such that transmission is correct for everybody. (so, no real problem, even if it would be a nice feature not having to rotate the phone)
2. If both use back cameras, and orientation is wrong, one partner can rotate the phone such that transmission is correct. Same as 1.
3. The problem occurs if both use different cameras, one front camera and one back camera. Then there is no way the any of the two phones can be rotated such that the transmission would be correct in both ways. And this should definitely be fixed.

**Comment by hiisukun** [comment]
Experienced this a couple of days ago, exactly as in point (3) above in blaueente.
Also experienced #10178 which seems related to the same video orientation logic.

Signal: 5.1.9
Android: 11 (2021 01 05)

**Comment by gab81** [comment]
These are my observations, Android 5.4.7

the new video mode where it rotates the video is not great. it only works on one side. if you test it with 2 phones in front of you (for seeing what the other person would see in the wild), they need to be facing each other on the side of the usb port, that way both videos are properly orientated, otherwise not, one it's upside down, and it’s not really intuitive if both are right handed so you would normally rotate holding with your right hand right? **so the usb port is on the right - your earpiece on the left, etc.**

**I do not really understand why such basic things are wrong. seriously can you just “check” Whatsapp before doing these functionalities?** they start from great ideas but the UX and output has always small but very irritating issues,.

please fix proper orientation or automatic.

**Comment by kierun** [comment]
I tried the following set up, all failed:

+ Called front camera then switched to back.
+ Called back camera.
+ Both phones in landscape then in portrait then alternating.

All these resulted in the back camera - front camera to be up side down. If this helps:

+ Signal: 5.10.1
+ Phones: Pixel 4a and Noikia 8

**Comment by gerroon** [comment]
I have the same issue with the back camera in landscape mode. Both sides see the video upside  down no matter which side is up in the landscape mode.

I am using it with  Signal 5.9.7 LineageIO 18.1
