### ISSUE TITLE
Signal 4.66.8 crash during backup restoration and subsequent attempt to register number

### ISSUE THREAD

**Issue by mmirg** [signalapp/Signal-Android#9867]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am trying to restore a backup and register Signal 4.66.8 on a new device. Signal crashes towards the end of the backup restoration process. The next time I open Signal, it prompts me to register but not restore a backup again (the size increase of the Signal application suggests that the backup has nominally been restored). However, Signal crashes again after it attempts to send a text message to verify my number. I never receive the text and I am not able to request a call as Signal crashes before that is possible. I periodically get rate limited and locked out of registration as a result. I'm using an ordinary mobile number with the associated SIM card inserted in my phone and not a VOIP number or any other unusual registration mechanism. I've been using this same phone number to register since TextSecure was first released.

### Steps to reproduce
- Install Signal on new device
- Follow prompts to restore backup
- Re-open Signal after Signal crashes towards the end of backup restoration
- Attempt to register number

**Actual result:** Signal crashes during backup restoration, Signal then crashes again while ostensibly waiting for a verification SMS to be sent to the specified phone number. 
**Expected result:** The backup is restored properly and Signal can be re-registered to my phone number

### Device info

**Device:** Pixel 3 XL
**Android version:** 10
**Signal version:** 4.66.8

### Link to debug log

I've attached a logcat dump as I'm unable generate a debug log in Signal due to its crashing. There appears to be some superficial similarities to bug #9837 but that person was able to ultimately have Signal working again whereas I am not.
[signal-logcat.txt](https://github.com/signalapp/Signal-Android/files/4944333/signal-logcat.txt)

**Comment by thetaurean** [comment]
I am having this identical issue on an S9+.

@mmirg here is the snippet of the log that seems relevant
```
07-19 17:21:58.303 21637 21670 E AndroidRuntime: FATAL EXCEPTION: signal-notifier
07-19 17:21:58.303 21637 21670 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 21637
07-19 17:21:58.303 21637 21670 E AndroidRuntime: java.lang.IllegalStateException: Tried to call getSelf() before local data was set!
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:128)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:303)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.constructNotificationState(DefaultMessageNotifier.java:538)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.updateNotification(DefaultMessageNotifier.java:290)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.DefaultMessageNotifier.updateNotification(DefaultMessageNotifier.java:225)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.OptimizedMessageNotifier.lambda$updateNotification$0$OptimizedMessageNotifier(OptimizedMessageNotifier.java:54)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.-$$Lambda$OptimizedMessageNotifier$RuFLBru2kWXWULnOeyRPmNPC_LI.run(Unknown Source:4)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-19 17:21:58.303 21637 21670 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by thetaurean** [comment]
**Possible workaround** (can't test until I'm not rate limited)
Remove signal's permissions for sms and phone and ensure signal is not your default messaging app and try again. This time Signal should require you to input your security code or whatever rather than reading it directly from a notification.

**Comment by subithacs7** [comment]
I have similar issue. My backup key is right, i have the backup file, i am trying to restore it goes till 100% then fails with an error:

Restore failed

Tried to call getSelf() before local data was set!

Try again

Cancel

**Comment by wucke13** [comment]
I hit this problem with 8.26.4, while in another country on roaming. Disabling permissions for phone and SMS off the Signal app unblocked the workflow for me, by allowing the manual entry of the verification SMS code.
