### ISSUE TITLE
German string on contact page

### ISSUE THREAD

**Issue by KommX** [signalapp/Signal-Android#9872]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the conact page there is the German string "Keine gemeinsamen Gruppen"/"2 gemeinsame Gruppen". My app is set to English, but the phone to German.
There is a temporary workaround: Just set Signal's language to German and back to English. But the next day the bug was there again.

### Steps to reproduce
- Go to a 1:1 conversation
- touch the name/image at the top
- scroll down to the bottom

**Actual result:** Just above "Add to a group" there is the German string "Keine gemeinsamen Gruppen".
**Expected result:** The string should be in English.

### Screenshots
![signal](https://user-images.githubusercontent.com/7859245/88338936-718b3580-cd39-11ea-9f36-a5579b07c143.png)

### Device info

**Device:** Google Pixel 3a
**Android version:** 10
**Signal version:** 4.67.1

### Link to debug log

https://debuglogs.org/26cc2969cc206d7e9e34d8fa98714668231afbac437de422c2eaa17cd9910c22

**Comment by Sgn-32** [comment]
In addition:

strings for disappearing message timer doesn't use the in-app language setting.
(for details see [#9999 ](https://github.com/signalapp/Signal-Android/issues/9999))

**Comment by KommX** [comment]
This one seems to be fixed.
