### ISSUE TITLE
No ring on tablet

### ISSUE THREAD

**Issue by kmm2** [signalapp/Signal-Android#9875]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You do not support tablets officially but the upcoming non-phone-number addressing will change that. It seems that ringing is dependent on phone ring API which presumably does not work or exist on tablets, so is it possible to also ring incoming calls with direct Signal app media sound?

### Device info
**Device:** Google Nexus 7 2013
**Android version:** 7.1.2
**Signal version:** 4.66.8

**Comment by greyson-signal** [comment]
RingRTC (our calling library) supports ringing multiple linked devices (for example, iPhone + iPad). Android does not currently support being added as a linked device, but if we ever added support, I see no reason to believe our current ringing methods wouldn't work there.
