### ISSUE TITLE
"Blur faces" doesn't work when the person is wearing a mask

### ISSUE THREAD

**Issue by kyleedwardsny** [signalapp/Signal-Android#9880]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Blur faces" doesn't work when the person is wearing a mask.

### Steps to reproduce
- Take a picture of someone wearing a mask, with eyes visible
- Try sending it with the "blur faces" feature

**Actual result:** Mask wearer's face should still be blurred
**Expected result:** Mask wearer is not recognized as a face and is not blurred

### Screenshots
As you can see, the mask wearer's face is not blurred, but Kenobi's face is.

![signal-2020-07-27-165723](https://user-images.githubusercontent.com/7741429/88592424-00df6400-d02c-11ea-9f7e-26784923fcce.jpg)

**Comment by greyson-signal** [comment]
Hi there, thanks for the report, but not a ton we can do here. We use the Firebase ML Vision library and rely on those models. After you click the 'blur faces' toggle, we encourage users to blur addition faces, because we know facial recognition is not perfect, and the case you highlighted here is a good example.

**Comment by kyleedwardsny** [comment]
Thanks for the response. My thinking was that masks are becoming common enough that face-blur tools should work with them... but if the AI model is coming from a third party then there's obviously not much we can do, other than requesting this from upstream (or, as you said, blurring the face manually.)
