### ISSUE TITLE
Messages take a long time to appear on the phone but seem to be delivered correctly

### ISSUE THREAD

**Issue by I-Al-Istannen** [signalapp/Signal-Android#9881]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Setting: I have a quite large conversation (probably around 70.000 messages with images, videos and files).  
*In this conversation* messages take a long time to appear, when
- I am writing them on my phone and sending them
- I am writing them on my connected desktop and sending them
- The other person writes a message

The messages appear relatively quickly with a "loading" indicator, take a few seconds to show a single checkmark (wifi connection, same my desktop uses). Then my connected desktop overtakes my phone, shows a single tick and a double tick while the phone is still displaying the loading icon. It seems like every single message action is 3-4 seconds delayed and those delays *add up*. (I included a video further down)

Sometimes it is so bad, that I can effectively no longer text on my phone -- waiting a minute for every message to send just makes for a very frustrating experience.

This conversation also takes a few seconds to initially display anything besides a blank screen.

All other conversations (which are *a lot* smaller) work normally.

### My limited debugging
Watching the logcat output in android studio, I noticed an interesting pattern:
```
2020-07-28 10:13:45.549 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 2115 ms | thread: 9, start: 0, size: 50
2020-07-28 10:13:51.314 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 5460 ms | thread: 9, start: 0, size: 50 -- invalidated
2020-07-28 10:13:53.097 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 1780 ms | thread: 9, start: 0, size: 50
2020-07-28 10:13:55.321 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 1790 ms | thread: 9, start: 0, size: 50
2020-07-28 10:14:00.643 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 3086 ms | thread: 9, start: 0, size: 50 -- invalidated
2020-07-28 10:14:02.816 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 2167 ms | thread: 9, start: 0, size: 50
2020-07-28 10:14:08.896 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 6070 ms | thread: 9, start: 0, size: 50
2020-07-28 10:14:12.793 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 1688 ms | thread: 9, start: 0, size: 50
2020-07-28 10:14:16.753 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 2009 ms | thread: 9, start: 0, size: 50 -- invalidated
2020-07-28 10:14:20.181 30461-30948/org.thoughtcrime.securesms D/ConversationDataSource: [Initial Load] 3422 ms | thread: 9, start: 0, size: 50
```
Each load from the `ConversationDataSource` takes 2-6 seconds in the slow conversation but just a couple milliseconds in the fast ones. Additionally, each time a (not invalidated) "Initial load" line is printed, another message shows up in my signal client. The time between the messages in the log quite closely matches the time they say they took.

Based on that it feels like signal queues up the inserts somehow, waits for the load to finish and then commits the next message. Something along those lines would also explain the "falling behind". If I write a few messages, signal needs to wait for `~3s * message count` until it reaches the up-to-date position again.

I have never looked at the signal code much more than needed to figure out what that method is doing, so that is completely baseless speculation.

### Further information
I am currently running a self-compiled version of signal (4.66.4 tag) to debug this so I could measure and adjust the code as you see fit.

### Another maybe interesting observation
Last night my phone was a whole day behind (probably unrelated syncing problems) and I opened the signal client. This prompted signal to slowly display the messages over the next minutes, but I gave up quite quickly and put the phone in airplane mode.
The next morning, *all my messages were displayed correctly*. Apparently Signal was able to process and display them and *that* is what took time. All messages were already received, otherwise they would have been missing as airplane mode does not allow any data connection.

### Steps to reproduce
- have a very large conversation with images and files and lots of messages
- open the conversation and wait a few seconds for anything to appear
- write a message and watch it not being send or registered for a few seconds
- write a message on your connected desktop or ask the other party and notice a few seconds delay
- just spam a few messages and watch the phone *hopelessly* fall behind

**Actual result:** The phone hopelessly falls behind in the conversation
**Expected result:** The phone should show me the messages in a timely manner

### Screenshots
Won't really help, I think. But here is a video. All messages were sent in rapid succession (maybe a second total) and appeared in a similar timeframe on the connected desktop where they were written.
https://imgur.com/gYfcWv9

### Device info
**Device:** Fairphone 2
**Android version:** 8.1.0
**Signal version:** Tag 4.66.4, but also happens with the newest playstore version and every other version I tried in the last year or so. The problem just got progressively worse over time probably because the conversation grew.

### Link to debug log
[Log](https://debuglogs.org/d270228fc66384bfa42bc387a3c97dc522db7e7dc5ed5f11cf2eb2173b79c010)

**Comment by richardddd98** [comment]
Same issue on Huawei Honor 9 (Android 9), Xiaomi Mi A1 (Android 9) and Huawei P40 Lite 5G (Android 10).

**Comment by I-Al-Istannen** [comment]
It has gotten even cooler now: I can't start the app because android force kills it saying a foreground service should call `startForeground`. If I comment out the line
```java
ContextCompat.startForegroundService(context, new Intent(context, ForegroundService.class));
```
in the IncomingMessageObserver it stops crashing at startup. I guess the startup is so slow, that before the service's onStartCommand is called, the 5 second grace period has passed and Android kills the service and ANRs the app.

My extremly ugly hack to at least be able to open Signal is
```patch
     if (TextSecurePreferences.isFcmDisabled(context)) {
-      ContextCompat.startForegroundService(context, new Intent(context, ForegroundService.class));
+      new Thread(() -> {
+        try {
+          Thread.sleep(5000);
+        } catch (InterruptedException e) {
+          e.printStackTrace();
+        }
+        android.util.Log.w(TAG, "IncomingMessageObserver: REALLY STARTED");
+        ContextCompat.startForegroundService(context, new Intent(context, ForegroundService.class));
+      }).start();
     }
```

That's probably not relevant as the performance issues are known by now, but not even *starting up at all* was a new one for me.

**Comment by ProactiveServices** [comment]
I have somewhat different symptoms - it affects all incoming messages, even in Note to Self (tiny history), and new PMs, as well as incoming calls (which effectively means I cannot receive incoming calls) and attempts at using airplane mode have not helped at all.
[Forum thread](https://community.signalusers.org/t/handset-android-message-retrieval-extremely-slow/18158/5) with details.

Debug log from around the time the problem first appeared [here](https://debuglogs.org/989c67de285faee7b4c78df941030711e6b665ee6881878be12de14047eeacd9) as well as from another user around the same time [here](https://debuglogs.org/c96a3876cfafea80431638944478b3e9b266089c7915f45aee127434fb5f2bde).

Another [debug log](https://debuglogs.org/3c18ba4934d8c9de1f9e763e4c53dae3f7028ed3abc74774a1a27dafe98f94e9) after 12 hours of the phone being left active with a WiFi connection, where it managed to process about one message every 30-60 minutes.

**Comment by Frivolous2** [comment]
I think it's not about strict number of messages, I think it's down to the phone's CPU. My aging Galaxy breezes through fresh chats, but in my group chat I often see the Spinning Circle of Wait for up to 10 seconds sometimes, and if people chat in between, on their screens the chat will be shuffled, with my spree of messages interspersing theirs, even though on my device they appear consecutive...
