### ISSUE TITLE
Android 11 conversation features

### ISSUE THREAD

**Issue by duchampdev** [signalapp/Signal-Android#9890]
Signal currently does not support Android 11's conversation features. This way, the new bubble UI cannot be used, which would definitely be a big advantage for many users. Are you planning to implement the necessary changes for supporting the conversation features?
And if so, is there already somebody occupied with that or can I help out?

**Comment by Cerberus0** [comment]
Hi @duchampdev,

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this over to the [community forum](https://community.signalusers.org)'s Feature Requests category. Thanks!

**Comment by duchampdev** [comment]
I'd have said that it is, with Android 11 upcoming, more a functionality which has to be updated for a messenger and not a feature request. But I partly see your point and will move this over to the forum.
