### ISSUE TITLE
App crash on startup, could not open database

### ISSUE THREAD

**Issue by adrianroth10** [signalapp/Signal-Android#9891]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app crashes on startup, might be because of an update that happened somewhere in May since this was when I first started to experience the issue. I have tried reinstalling the app twice with the same crashing result.

### Steps to reproduce
- Start the app

**Actual result:** Crash on startup
**Expected result:** Should not crash on startup

### Device info
**Device:** Samsung Galaxy S2
**Android version:** 7.1.2
**Signal version:** 4.67.3

### Link to debug log
Since the app will not start I can not get a signal debug log but I have the adb log:

07-31 12:17:19.979 16767 16793 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
07-31 12:17:19.979 16767 16793 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16767
07-31 12:17:19.979 16767 16793 E AndroidRuntime: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(com.google.android.datatransport:transport-runtime@@2.2.0)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(com.google.android.datatransport:transport-runtime@@2.2.0:456)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(com.google.android.datatransport:transport-runtime@@2.2.0:80)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(com.google.android.datatransport:transport-runtime@@2.2.0:488)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(com.google.android.datatransport:transport-runtime@@2.2.0:54)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.run(com.google.android.datatransport:transport-runtime@@2.2.0)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-31 12:17:19.979 16767 16793 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)

If there is any more information that would be useful I will try to get it!

**Comment by greyson-signal** [comment]
Huh, so the crash doesn't seem to be from any of our code, but rather some system code (possibly the JobScheduler) that is trying to open a database connection and failing. But it's not our database.

Looking at your device + android version, I don't believe the Galaxy SII ever got official upgrades to Android 7.1.2, so I'm guessing you're running Lineage or some other unofficial distribution? My guess is that something is up there, and t hey may have some bug in their implementation.

**Comment by adrianroth10** [comment]
TMy guess is that your guess is correct and that sucks, well thanks for your support!
