### ISSUE TITLE
[RTL] Audio playback button does not get mirrored

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#9893]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Playback icon does not get mirrored:

![image](https://user-images.githubusercontent.com/34171942/89078567-e396f680-d399-11ea-9e1d-dd23a8366ee5.png)

### Steps to reproduce
1. Choose an RTL language from Signal settings
2. Record a voice note to see the playback icon

**Comment by Xashyar** [comment]
Related: https://github.com/signalapp/Signal-Android/issues/9823

**Comment by fumiakiy** [comment]
After reading documents that describes when to and when not to mirror elements in Material UI document [[1](https://material.io/design/usability/bidirectionality.html#:~:text=Do%20not%20mirror%20media%20playback%20buttons%20and%20the%20media%20progress%20indicator%20as%20they%20refer%20to%20the%20direction%20of%20tape%20being%20played,%20not%20the%20direction%20of%20time.)] and in Mozilla RTL guidelines [[2](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_Guidelines#:~:text=What%20NOT%20to%20mirror)], I understood that the audio playback controls and the associated progress bar (in our case the waveform) should appear the same as in LTR languages.

I know that Signal does not necessarily a Material UI product, and Mozilla documents are not necessarily for Android apps. And I am not native to any RTL languages either. But from what I read, the current implementation with the fix to #9823 is also sort of wrong, and it should appear the same as in LTR language so the playback button is placed in the left of audio wave form and the wave form should progress from left to right, but only the bubble that holds those elements are aligned to the right if you received it. If you are the sender of the audio, the bubble should appear in the left column, which has the playback button to the left and the waveform to the right (the same as the one you received). What do you think? Is that what you normally see in other apps?

**Comment by Xashyar** [comment]
> What do you think? Is that what you normally see in other apps?

I think, it makes sense both ways, here's how received-voice-messages are shown in WhatsApp for instance:

![image](https://user-images.githubusercontent.com/34171942/94745238-2ae43800-0387-11eb-8044-222cf825e9db.png)

Whereas in some others they're shown in exactly the same way you've described above with the playback button being on the left, in every language setting.

Also, since, the timer shows the "remaining" time and not the "elapsed" time, this even makes sense mathematically, that the seek bar moves in the negative direction...

**Comment by Xashyar** [comment]
> What do you think? Is that what you normally see in other apps?

I think, it makes sense both ways, here's how received-voice-messages are shown in WhatsApp for instance:

![image](https://user-images.githubusercontent.com/34171942/94745238-2ae43800-0387-11eb-8044-222cf825e9db.png)

Whereas in some others they're shown in exactly the same way you've described above with the playback button being on the left, in every language setting.

Nonetheless, since for videos the seek bar and playback buttons, retain their orientations in RTL as in an LTR language setting, it might be a good idea to unify those behaviors, by moving the audio-message-playback-button to the left and adjust the seek bar behavior accordingly.

**Comment by Xashyar** [comment]
> What do you think? Is that what you normally see in other apps?

Here's how received-voice-messages are shown in WhatsApp for instance:

![image](https://user-images.githubusercontent.com/34171942/94745238-2ae43800-0387-11eb-8044-222cf825e9db.png)

Whereas in some others they're shown in exactly the same way you've described above with the playback button being on the left, in every language setting.

So I think, since for videos the seek bar and playback buttons, retain their orientations in RTL as in an LTR language setting, it might be a good idea to unify the two behaviors, by moving the audio-message-playback-button to the left and adjust the seek bar behavior accordingly.

**Comment by Xashyar** [comment]
As per https://material.io/design/usability/bidirectionality.html#mirroring-elements, Playback elements should not be mirrored.
