### ISSUE TITLE
Message timestamps do not update unless conversation view is exited

### ISSUE THREAD

**Issue by jalseth** [signalapp/Signal-Android#9897]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send messages and then lock my phone, when I unlock the phone and Signal is displayed because it was the last app open, the timestamp on my last sent messages always shows "Now". This can also happen if I switch between apps as long as I leave the conversation up in Signal and do not return to the conversations list. If I hit back to the conversations list and then re-open the same message thread, the timestamps are updated and display correctly. This issue has been going on for a few weeks now. 

### Steps to reproduce
- Send message and lock phone without switching away from Signal
- Wait a few minutes
- Unlock phone

**Actual result:** Timestamps messages sent multiple minutes ago show "Now"
**Expected result:** Timestamps show the actual difference in time between when they were sent and now

### Screenshots
N/A

### Device info
**Device:** Samsung Galaxy S8
**Android version:** 9
**Signal version:** 4.67.3

### Link to debug log
https://debuglogs.org/dca5c973b3e6264ac6527e5e6eda679b362c1479c192d7fcd6ba22770700acad

**Comment by mejo-** [comment]
I can confirm this bug and I'm pretty sure that it's a recently introduced regression. I'm running 4.68.2 (from the beta channel).

**Comment by mejo-** [comment]
Seems to be a duplicate of #9884 btw.

**Comment by jalseth** [comment]
Apologies, I didn't find that in my search for related issues. Closing this in favor of the earlier opened issue.
