### ISSUE TITLE
Issues when importing backup on new phone

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#9899]
- [x] I have searched open and closed issues for duplicates
  As I did not see an issue that is exactly what I encountered, I decided to create a new one to prevent cluttering up other issues.
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I made a Signal backup on my old phone (when it was in flight mode). I transferred the backup file to a new phone (where my SIM-card, from the old phone was already active). On the new phone (Nokia 4.2) I installed Signal from the Play Store.
Signal detected the backup and asked for the passphrase (6x5 digits). The passphrase was accepted and Signal started importing the backup. For some reason Signal crashed. I tried again (I forgot what I exactly did) and in the end Signal was trying to register without that the backup had been restored.
I uninstalled Signal, and did the whole procedure again, closely monitoring the import process. This time the import went well (the phone was not locked during the import process, during the first attempt it was locked).

I see several stack traces in the [debug log](https://debuglogs.org/3ce354812f70f235b352486c32d4ed68b940667cda56fbbb9fb5899f029dbd9a).

The size of the backup file is 5.7G. I am a long term Signal (TextSecure) user, so maybe the database contains old style information. For some parts of the import the message count of imported messages went very quickly, for other parts very slow. The slow part was around message 125,000 to 129,000. After this thousands of messages were very quickly imported. It went so quick that I could not write down the final number of messages imported. But I guess it will be around 150,000 messages.

During the time that I was doing the migration the old phone was in flight mode all the time. However, I did receive and send messages with Signal desktop. These messages, sent by Signal desktop were not loaded on the new phone, when it came online. So they seem to be lost for the Signal database on the new phone.

My old phone is still in flight mode (with Signal installed). I did not want to take the risk to break the Signal setup on the new phone, and desktops by bringing it online again. I'm wondering whether it would load the messages that I miss on the new phone, but that I do have on Signal desktop. If you would like, I could enable networking on the old phone again to test.

### Device info
========= SYSINFO =========
Time         : 1596278005309
Manufacturer : HMD Global
Model        : Nokia 4.2
Product      : Panther_00EEA
Screen       : 720x1370, xhdpi (300), 60.00 hz
Font Scale   : 1.0
Android      : 10 (00EEA_2_29C, 00EEA_2_290_SP03)
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 43M (44.13% free, 512M max)
Memclass     : 192
OS Host      : R740
Censored     : false
Play Services: true
FCM          : true
First Version: 680
App          : Signal 4.67.3 (6802)
Package      : org.thoughtcrime.securesms (doDiFGKPO1r)

### Link to debug log
https://debuglogs.org/3ce354812f70f235b352486c32d4ed68b940667cda56fbbb9fb5899f029dbd9a

**Comment by johanw666** [comment]
> so maybe the database contains old style information.

That used to be a problem when the new style backups were just introduced in 4.16 (export crashed because it found tables it didn't expect) but that is no longer the case. This backup does not contain the structure of the existing database  anymore, any obsolete tables will not be there when you restore it anyway.

You logs contain an awful lot of these exceptions:
```
W CascadingFuture: java.io.IOException: No pipe available!
	at org.thoughtcrime.securesms.util.ProfileUtil.getPipeRetrievalFuture(ProfileUtil.java:113)
	at org.thoughtcrime.securesms.util.ProfileUtil.lambda$retrieveProfile$0(ProfileUtil.java:76)
...
```
the size of your backup might have something to do with that.

> I did receive and send messages with Signal desktop. These messages, sent by Signal desktop were not loaded on the new phone, when it came online. So they seem to be lost for the Signal database on the new phone.

That is to be expected, if you re-register all "old" messages in the queue for that number are purged. Your session keys are not in the backup so you would not have been able to decrypt them anyway.

**Comment by janvlug** [comment]
I cannot really say if this is still a relevant bug. I'm not switching phones that often :-)
So I will close this issue, as I cannot really provide additional information.
