### ISSUE TITLE
Allow linking two phones to one account

### ISSUE THREAD

**Issue by aevw** [signalapp/Signal-Android#9900]
I have a phone with only wifi working and use it at home. The other one use at work but would like to link those two devices and use phone interchangeably with one signal account.

**Comment by Cerberus0** [comment]
Hi @aevw,

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this over to the [community forum](https://community.signalusers.org/). Thanks!

**Comment by aevw** [comment]
Yes, you're right I see discussion about it on signal's forum. I'll follows that thread for updates on that.


[I'm an inline-style link](https://www.google.com)

**Comment by aevw** [comment]
Yes, you're right I see discussion about it on signal's forum. I'll follows that [thread](https://community.signalusers.org/t/allow-android-ios-devices-e-g-tablets-to-be-linked-to-the-primary-device-i-e-used-as-secondary-device-like-the-desktop-app/2884/101) for updates on that. Thanks @Cerberus0
