### ISSUE TITLE
Roboting-sounding voicenotes - Mi 9T

### ISSUE THREAD

**Issue by cipavlou** [signalapp/Signal-Android#9903]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending voicenotes (using the Mi 9T), the sound quality is "robotic" when played back by both the sender and the receipient.  There are no such issues with received voicenotes, and this seems to only apply to Signal (not WhatsApp, etc)

### Steps to reproduce
- Record new voicenote in Signal using Mi 9T
- Send to recipient
- Play back (or have recipient play back)

**Actual result:** The audio of the voicenote sounds "robotic" - as if it's gone through a filter 
**Expected result:** The audio of the voicenote should sound relatively similar to that recorded (no such issues with WhatsApp).

### Screenshots
N/A

### Device info

**Device:** Xiaomi Mi 9T (Global)
**Android version:** 10.0 (bug appears on MIUI 11 and 12)
**Signal version:** 4.67.3

### Link to debug log
https://debuglogs.org/5110bc29cf493aec233e6d1bfc9fd76a1e1207951e08a627fece3cddb6133eb2

**Comment by silgrandi** [comment]
I have the same issue on my Xiaomi MI 8T with Android 10 on MIUI 12, on Signal version 4.79.3
