### ISSUE TITLE
Ringing word without tripple dots

### ISSUE THREAD

**Issue by igor2x** [signalapp/Signal-Android#9904]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Ringing word without triple dots
After executing call there is first "Calling..." (triple dots) and then it changes to "Ringing" (without triple dots). Triple dots indicate there is something in progress. The bug is, missing triple dots after Ringing word.

### Steps to reproduce
- On conversations list tap on specific user.
- In top right tap on icon "Signal Call".
Now first string "Calling..." (with triple dots) appears, then "Ringing" (without triple dots) appears. This is inconsistent. The bug is "Ringing" should be added triple dots.

**Actual result:** String "Ringing" without triple dots.
**Expected result:** There should be string "Ringing..."

### Screenshots
![pic](https://user-images.githubusercontent.com/10895030/89212228-677ff700-d5c3-11ea-9b17-37ae416acc97.jpg)

### Device info
**Device:** Samsung S10
**Android version:** 10
**Signal version:** 4.67.3

### Link to debug log
It is visual problem, so debug log is not needed.

Just make sure, fix for this problem is added at the beginning of beta program, because translators probably need to translate this new triple dot string.

**Comment by mueller-ma** [comment]
Duplicate of #9711
