### ISSUE TITLE
Forward message and multi selection menu items non-functional

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#9908]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For messages with media attachments, Signal used to put the forward and the the mulit-select button into the three-dot menu in the upper right. The entries are "unclickable" now.

### Steps to reproduce
- Select a message with media attachments
- Tab the three-dote menu
- Try to tap either forward, or multi-select

**Actual result:** Nothing happens
**Expected result:** I should be taken to either selecting more messages or to the selection of a recipient.

### Screenshots
![Screenshot_20200806-100450](https://user-images.githubusercontent.com/1287825/89507603-03c91a00-d7cd-11ea-8ebf-a0b4c144a4f3.png)
(German, but same behavior with other languages)

### Device info
**Device:** Motorola Moto G7 plus (XT1965-3)
**Android version:** 10, patch-level June 1.
**Signal version:** 4.68.4

**Comment by basvdijk** [comment]
I have the same problem on my Huawei P30 Pro
Android version: 10, path-level June 1
Signal version: 4.68.4

**Comment by benjertho** [comment]
I have the same problem on an LG G6+
Android version: 9, security patch level: May 1 2019
Signal version: 4.68.4

**Comment by pgerber** [comment]
There appears to be a workaround to be able to forward an affected message anyway:

1. Select any unaffected message
2. Enable multiselect mode
3. Select the message you want to forward
4. Unselect the message selected in step 1
5. Forward the message

Interestingly, forwarding doesn't get moved to the overflow menu when I do this.

**Comment by merkste** [comment]
Thanks for the workaround. @greyson-signal Do you need logs to pin down the issue?

**Comment by merkste** [comment]
Thanks!
