### ISSUE TITLE
Reaction notification not dropped on phone once read on desktop.

### ISSUE THREAD

**Issue by iago-lito** [signalapp/Signal-Android#9909]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Say I have signal opened both on desktop and on my phone.
Whenever I receive a new **message**:
- ✔ a notification pops on the desktop
- ✔ a notification pops on the phone

Then, when I read the message on desktop:
- ✔ the notification is dropped on the desktop.
- ✔ the notification is also dropped on the phone, I am glad with this.

But this does not work the same when I receive a new "**reaction** emoji" notification. In this situation:
- ✔ a notification pops on the desktop
- ✔ a notification pops on the phone, alright so far..

But then, when I read the message on desktop:
- ✔ the notification is dropped on the desktop.
- ❌.. but it is not dropped on the phone. It stays around as long as I have not  also handled it on my phone.

I think this is unexpected. I would expect the "reaction" notification to be dropped on my phone as well at this point, just like the message notifications.

### Device info

**Device:** Samsung Galaxy GT-I9505
**Android version:** 9 (LineageOS 16.0)
**Signal version:** 4.68.4

### Link to debug log
(can't reproduce on my own :( )

**Comment by KommX** [comment]
I guess, this is the same as #9501, right?

**Comment by iago-lito** [comment]
@KommX Yikes, yupe. Sorry for the dupe.
