### ISSUE TITLE
Play Store translation makes version change infos inaccessible

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#9912]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
I’m not sure if this goes here. Feel free to move it, if necessary.

### Bug description
Since the info texts for the Signal App in the Play Store got translated, it is impossible to reach the actual version change infos. The text that says what actually changed (and the whole reason to update.)
Please make it accessible again, even if just by appending the English version change infos below the static German app description.

My language: German

**Comment by piratenpanda** [comment]
For me the changelog is under "Neue Funktionen". Isn't it for you?

**Comment by navid-zamani** [comment]
There is a ”Neue Funktionen“, with 1½ bullet points, in English, under it, and arrow right of it. Unfortunately, if I tap on the arrow, instead of the full list, I get the generic German info text about Signal. (Starting with ”Sag »Hallo« zu Privatsphäre.“)

**Comment by navid-zamani** [comment]
I just realized I could check the Play Store *website*, instead of the app. And there, the ”Neue Funktionen“ list is complete, as expected.

**Comment by piratenpanda** [comment]
> There is a ”Neue Funktionen“, with 1½ bullet points, in English, under it, and arrow right of it. Unfortunately, if I tap on the arrow, instead of the full list, I get the generic German info text about Signal. (Starting with ”Sag »Hallo« zu Privatsphäre.“)

For me the complete changelog is above that text

**Comment by navid-zamani** [comment]
Here’s a screenshot of my situation:

![IMG_20200808_152353](https://user-images.githubusercontent.com/58148887/89711568-505a5400-d98b-11ea-826b-eb067574e0ed.jpg)

**Comment by greyson-signal** [comment]
Clicking the arrow to the right of 'What's New' just shows you the same bullet points along with the full app description. The screenshot you shared looks to be what I would expect. If you're not seeing the full list after tapping the arrow, then that sounds like a bug in the play store. We've definitely uploaded the notes and such.

**Comment by navid-zamani** [comment]
Could you *please* fully read what I said? At least before closing the bug?

This appeared right after the app description translations got added.

**You need to add the ”what new“ section to all the translations too!** You forgot them when translating.

> Clicking the arrow to the right of 'What's New' just shows you the same bullet points along with the full app description.

_**No. It. doesn’t!**_ It shows this:

![Screenshot_20200810_205727_com android vending](https://user-images.githubusercontent.com/58148887/89819732-2e5bff80-db4c-11ea-9004-f94722653e75.jpg)

As you can see: No ”whats new“ in there. Only the translated app description.

**You need to add the ”what new“ section to all the translations too!** Otherwise, we only gain access to the information again, by removing the translations.

**Comment by UserX404** [comment]
For reference:
No problem except missing translation.
 ![](https://i.imgur.com/M9IF9Sb.png)
