### ISSUE TITLE
Always error when compile from source code

### ISSUE THREAD

**Issue by senyung** [signalapp/Signal-Android#9916]
- [X] I have searched open and closed issues for duplicates
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Always error when compile from source code. I am using android studio version 4.01 Android SDK Build Tools 29.0.2 allways got error "  public static final long BUILD_TIMESTAMP = Microsoft Windows [Version 10.0.18363.959]"  and can not continue, the source code in GitHub is not complete or not compatible with latest android version  

### Steps to reproduce
- Always happen when compile using android studio version 4.01 SDK Build Tools 29.0.2 

**Actual result:** Show not error when compile from source code 
**Expected result:** Show not error when compile from source code using android studio version 4.01 SDK Build Tools 29.0.2 

### Screenshots
![image](https://user-images.githubusercontent.com/22725577/89790664-74b15e80-db4c-11ea-81d5-b4d6489029be.png)

### Device info
**Device:** Xiaomi Redmi 7
**Android version:** 10
**Signal version:** 4.68.6

### Link to debug log

the error not from signal, but happen when compile the source code

**Comment by greyson-signal** [comment]
The source code is complete, passes Github CI, and can be built using our reproducible build instructions on our wiki. You likely have some other build configuration issue. Feel free to discuss it on the (forum)[https://community.signalusers.org/].
