### ISSUE TITLE
Member does not support new groups still when using the same beta version

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#9917]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The message "1 member does not support New Groups, so this will be a legacy group. Learn more" appears when trying to create a new group still when both are using the latest Android beta version 4.68.6.

### Steps to reproduce
- Use the Android beta release in two phones.
- Try to create a new group.
- See the warning.

**Actual result:** It creates a legacy group still when both Signal versions are the latest beta but it's recognizing your contact as using a older Signal version.
**Expected result:** It creates a new group with the "New groups" features.

### Device info

**Device:** Samsung Galaxy A70 / Samsung Galaxy A50 (my contact)
**Android version:** 10 in both phones.
**Signal version:** 4.68.6

### Link to debug log

https://debuglogs.org/7ba87a5e88a363bb9aeb605644e090bd91877039a4b233dad147943b4a5fc1e9

**Comment by Edu4rdSHL** [comment]
Now the warning has dissapeared but still we can't use new features like mentioning. :(

**Comment by Nisc3d** [comment]
Mentioning is part of Groups V2 which is not activated yet.
