### ISSUE TITLE
Message reactions from another user show up in my reaction menu on the same message

### ISSUE THREAD

**Issue by kyleedwardsny** [signalapp/Signal-Android#9918]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open the reaction menu for a message and browse through the available reaction emojis, if someone else adds a reaction to the same message while I'm in the menu, the emoji they added shows up in my reaction menu.

### Steps to reproduce
- Open the react menu for a message
- Select one of the sub-categories and browse through
- Wait for someone else to add a reaction to the same message

**Actual result:** The other person's reaction shows up in my reaction menu
**Expected result:** The other person's reaction should have no effect on my reaction menu

### Screenshots

This is what I see when I first open the reaction menu and open the "food" category. This is how I expect it to look the entire time.
![signal_bug_1](https://user-images.githubusercontent.com/7741429/89827790-16718500-db26-11ea-8566-2d67173265aa.png)

This is what I see right after someone adds a caterpillar reaction to the message I'm trying to react to. I did not expect this to happen.
![signal_bug_2](https://user-images.githubusercontent.com/7741429/89827909-44ef6000-db26-11ea-9b39-6778492a25f1.png)

After returning to the chat, we can see that someone added a caterpillar emoji to my message.
![signal_bug_3](https://user-images.githubusercontent.com/7741429/89827933-50db2200-db26-11ea-9d5c-bd0ec4f3ca2f.png)

(Some parts of the screenshots have been blacked out for privacy of course.)

### Device info

**Signal version:** 4.68.4

**Comment by TheAxThatSlayedMe** [comment]
+1

**Comment by greyson-signal** [comment]
We recently added a section for reactions on "This message", and I bet it's getting screwed up when the reactions change while you're actively looking at the picker. We'll take a look.
