### ISSUE TITLE
Deleting old messages crashes app - Video

### ISSUE THREAD

**Issue by condemnedmeat** [signalapp/Signal-Android#9920]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

I try to manually delete messages, perhaps my 80 or so oldest in a given conversation, they will be about a month old. Usually the app deletes a couple or a handful then throws me back to the list of conversations. This has been happening for a couple of months, since I updated at the beginning of this month it is worse. Usually, if I persevere, I have been able to delete the selected messages, as interspersed with throwing me out the app occasionally does what I'm asking it to do. At the moment the app is very unreliable in this regard. [Here](https://vimeo.com/446673206) are two examples.

I think this is the relevant section from the debug log.

![log](https://user-images.githubusercontent.com/42522540/89851858-0a64e200-db7d-11ea-8ca1-3a1c6d71cf3d.png)

**Device:** Pixel 2 XL
**Android version:** 10
**Signal version:** 4.68.4

**Comment by condemnedmeat** [comment]
Still an issue in 4.68.8

**Comment by bme13** [comment]
Same here while I only removed one (the latest) item. Not sure if relevant but this was a gif image. This happened yesterday evening on the 'Note to self' conversation and this morning I noticed the 'Note to self' was completely empty.
https://debuglogs.org/2b2e641021d2b1dbb545919c1cd3366c91b29af387f1cb8d62c813deaf96cc77

**Comment by condemnedmeat** [comment]
I've setup signal to delete messages automatically when a conversation reaches a certain number of messages. Of course I was worried about whether it would delete my notes, no one, correct me if I'm wrong, has thought to mention that in any of the online help. I'd prefer to manually delete messages in case there is anything I would like to keep!

**Comment by condemnedmeat** [comment]
I believe this issue has been reported previously. #9690
