### ISSUE TITLE
Signal sucks for contacting people recently deleted signal or don't want to make it default app

### ISSUE THREAD

**Issue by tr0798** [signalapp/Signal-Android#9921]
Im linking to another thread, because it was closed because there is [supposedly a solution](https://github.com/signalapp/Signal-Android/issues/7210). 

I am a user who is currently pissed about this problem, because it's fucking up me trying to talk to this girl I'm trying to date. This is not a good way to start dating someone, having a technical error that makes it so she can't see my texts I am sending and having her think I don't have interest and am ignoring her messages. And also it has been a problem in the past with other people I know who downloaded the app, only to delete it later, and being unable to contact them through texts at all. It's a bug that makes texting impossible when someone removes the app and stops using it. Not everyone wants to set the signal app as their default, and neither should they be expected to for a single or a few secured messages. 

So the linked thread above says the solution is: if you hold the button it allows you to send an insecure text. I call BS as that being a solution. It is massively inconvenient to have to do that for EVERY SINGLE TEXT, not to mention it is not remotely obvious that that is even an option on the user interface of the text thread. I had no idea until I researched the problem. There needs to be a way to delete the safety number OR toggle it. Or at least toggle it while the text thread is up on the screen until you leave the screen. 

I realize the very serious reasons for trying to make sure people don't accidentally send insecure texts, but you guys are fucking up my dating life with this glaring problem in the app. I have to research the solution (more time passes, she thinks I'm ignoring her), ask her to go to whisper systems website and delete the account herself for us to be able to communicate normally without secured messaging. Really awkward and makes me look bad, and first impressions are everything. I should have never asked her to download the app for a single secured communication I wanted to send. If no change is made, this is the last time I will ask someone to download the app.... 

Please fix this!!!

**Comment by tr0798** [comment]
I realized that it can be toggled. It's still not an obvious feature. Sorry for my explosive rage about it, my dating life is important, but also the app is not intuitive or obvious that you can do that.

**Comment by greyson-signal** [comment]
Sorry for the confusion. We do have to be very careful to make sure people don't accidentally send SMS when they think they're sending secure messages, so we have a strong bias towards sending Signal messages to Signal users. As you mentioned though, long-pressing and switching to SMS is a 'sticky' setting, meaning it will stay as SMS until the other person starts sending Signal messages again. Hope everything worked out ok :heart:
