### ISSUE TITLE
blocking contact

### ISSUE THREAD

**Issue by jerryyhom** [signalapp/Signal-Android#9923]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Blocking a contact results in crash.

P.S. I received spam from a contact whose number appears as an email address.  I am not expecting a reply, but I wonder how this is possible?

### Steps to reproduce
- From conversations list, click a conversation.
- In navigation bar at top, click on contact(s) for "Conversation settings."
- Assuming conversation with one contact, click on "Block."
- In confirmation dialog box, click on "Block."

**Actual result:** Signal crashes.
**Expected result:** Contact should be added to block list.

### Device info

**Device:** LG Stylo 5
**Android version:** 9
**Signal version:** 4.68.8

### Link to debug log

https://debuglogs.org/2c29dde62a38e06b1c95cc5411dd7047f57a7a446162822d927a65e82b2d2679

**Comment by grandchild** [comment]
Could it be that that spam message was an SMS? SMS senders can appear as strings: https://messente.com/blog/messente/what-is-sms-sender-id

Also a debug log would be very helpful for the devs in debugging the issue.

**Comment by jerryyhom** [comment]
Ah, thank you very much!  I learned a few things today.

I will try getting a debug log.

**Comment by rue-jw** [comment]
I experience this bug. Steps to reproduce are identical.

Debug log: https://debuglogs.org/a5d1a0907577bcaf945a4c205526ded1877c5063928cb0cafc672e6d084f0d02

SMS that indicates an email address as the sender is email over SMS. I am a Verizon customer. See: https://www.verizon.com/about/news/vzw/2013/06/computer-to-phone-text-messaging

Attempting to block a sender in this case results in a hard crash. Stack trace indicates contact not blockable, and that may be true, but at least it should be handled more gracefully.

This is an increasing category of spam texts for me.

**Comment by jerryyhom** [comment]
Hm, the bug seems to be fixed as of at least v5.3.12.  Thanks!
