### ISSUE TITLE
Non-Signal stickers can be used to reply

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#9924]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can reply to a message with a non-signal sticker (like a sticker from Gboard).

### Steps to reproduce
- reply to someone's message
- use a sticker from your keyboaed

**Actual result:** Sticker sends as a reply.

**Expected result:** Sticker should send independently.

### Screenshots

![Screenshot_20200827-084038~2](https://user-images.githubusercontent.com/18274896/91449731-13bea180-e841-11ea-9f2e-faaf17118417.png)

### Device info

**Device:** Google Pixel 4
**Android version:** 10
**Signal version:** 4.68.8

**Comment by Edu4rdSHL** [comment]
It's an expected behavior. See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-52-release/10643/11?u=meteor0id

**Comment by Tursko** [comment]
> It's an expected behavior.

I'm aware, but this is an example of the sticker actually being used to reply and it shouldn't as you mentioned.

**Comment by Edu4rdSHL** [comment]
My bad. Sorry.

**Comment by Tursko** [comment]
> My bad. Sorry.

All good! Thank you for linking the thread for others to look at if they are confused 👍

**Comment by BeSanidhya** [comment]
Do you mean that Signal stickers cannot be used to reply ? Because this seems to be working as it is supposed to

**Comment by Tursko** [comment]
> Do you mean that Signal stickers cannot be used to reply ? Because this seems to be working as it is supposed to

Stickers in general should never be sent as a reply, they are always an independent message. They introduced the ability to send Non-Signal stickers (for example: stickers from gboard, memoji etc.) but they can be used to reply. This seems to be unexpected behavior.

**Comment by Taeluf** [comment]
For comparison to Signal stickers, screenshot shows: I had the "reply" open & selected a sticker from there. The sticker sent immediately without being shown as a "reply". This functionality is different from what @Tursko screenshot shows when using non-signal stickers

![Capture+_2020-09-21-21-36-04](https://user-images.githubusercontent.com/8450080/93839550-e81db400-fc52-11ea-87ee-79cccdc29da9.png)

**Comment by Edu4rdSHL** [comment]
For me it's a nonsense restriction, if we can use other stickers to reply and it doesn't cause any kind of problem why we can't use the Signal ones?

**Comment by Taeluf** [comment]
@Edu4rdSHL, Personally, I agree. But I think that discussion belongs on the community forum. There is already a feature request from Apr 2, 2020 at https://community.signalusers.org/t/send-stickers-as-a-reply-to-a-quoted-message/12919

**Comment by Tursko** [comment]
Sending stickers as a reply would be a feature request. But sending a 'non-signal' sticker is unexpected behavior and has formatting bugs.

**Comment by Edu4rdSHL** [comment]
Where are the "formatting bugs", can you give an example? I see that they're sent perfectly.

**Comment by Tursko** [comment]
Here you go. Look how the reply bubble is rendered. 
![Screenshot_20200922-230448~2](https://user-images.githubusercontent.com/18274896/93965659-4bc5e100-fd28-11ea-8703-73e61412da26.png)

![Screenshot_20200922-230523~2](https://user-images.githubusercontent.com/18274896/93965667-508a9500-fd28-11ea-9819-8f931e629227.png)

**Comment by greyson-signal** [comment]
Notably the other platforms also don't render these well. Not knowing the best way to render quotes above stickers was the original reason we decided to delay this (although in classic fashion, it's sort of been forgotten about), so I should look at preventing this scenario that's happening. I'll also poke our designers to schedule some time to think about how we want stickers+quotes to look :)
