### ISSUE TITLE
"Enter your PIN" screen can be revisited after skipping an already-present PIN during registration

### ISSUE THREAD

**Issue by jisckim23** [signalapp/Signal-Android#9927]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Enter your PIN" screen can be revisited using the back button after registration while skipping an already-present PIN. Unknown if this is also present if setting up a new PIN or if opting out of PIN creation during registration.

### Steps to reproduce
- Have a normal Signal install with a PIN, and the registration lock turned off.
- Clear the app data or use another phone in order to be able to register the phone number again. (I cleared the app data.)
- Register phone number
- When it tells you to "Enter your PIN", press the SKIP button in the top right
- Enter a new PIN. (I did an alphanumeric one.)
- After PIN is entered and taken to the conversation list, press the back button to go to "Enter your PIN" screen. 

**Actual result:** Pressing the back button lets us go back to "Enter your PIN" screen.
**Expected result:** Pressing back button exits the app.

### Device info

**Device:** Pixel 3a
**Android version:** 10
**Signal version:** 4.68.8

**Comment by jisckim23** [comment]
Should also mention: If you press the SKIP button, and then press back two times to close the app, and then open Signal again, you will be taken to the conversation list, but the app thinks that no PIN was set and lets you create a new PIN in Settings. I don't know what happens if you don't press the SKIP button, rate limited so can't see.

**Comment by bme13** [comment]
This also seems to happen temporarily if you run out of PIN guesses. Pressing back brings you to the 'Create your PIN' screen again.

![signal-2020-10-21-134401](https://user-images.githubusercontent.com/25846829/96715727-4ea60700-13a4-11eb-9d0e-dcc4255f8cc1.png)
After a while this was resolved. 
Here's also a logfile taken while this behaviour still occured.
https://debuglogs.org/0440b92cf8e3ed76d8be2438f584167399658978756d4fa08142f4a06b7d9025
