### ISSUE TITLE
Reply to notification when no Text is shown

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#9928]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications allow to directly reply to a message, even when no text content is shown.

### Steps to reproduce
- Settings -> Notifications -> Show: Name only
- Someone sends you a message

**Actual result:** I get a notification with the option to mark it as read and directly reply to it.
**Expected result:** Only see a Notification; without the option to reply (since it does not make much sense to reply to something you were not able to read)

### Screenshots
![grafik](https://user-images.githubusercontent.com/62468040/90309794-d1fe3480-deeb-11ea-87fb-2b3e6e8bbfa5.png)
Android is in German, left is '(Mark as?) read', right one is 'reply'

### Device info
**Device:** OnePlus 5T
**Android version:** 10
**Signal version:** 4.69.0

**Comment by bme13** [comment]
Hi. This currently seems to be the expected behaviour so it's not a bug. Personality this also seems strange to me so created a feature request for it. See https://community.signalusers.org/t/disable-mark-as-read-option-in-notification-if-message-is-hidden/11395

**Comment by quite** [comment]
I agree. The generated "smart replies" (Android 10) should probably also be disabled in these kind of cases. Seeing an "Okay" button (as in my case), but no name and no message is just annoying. @alan-signal agrees in https://community.signalusers.org/t/annoying-okay-button-in-notification/16618/7
