### ISSUE TITLE
The options button on the top right corner (3 dots) remains white after changing from dark to light theme

### ISSUE THREAD

**Issue by Altonss** [signalapp/Signal-Android#9932]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my android phone I switched from the dark theme to the light theme and realized that the option button on the top right corner remains white. Therefore the 3 dots are invisible because they are white on a white background.

### Steps to reproduce
- open the signal in dark mode
- set in light mode
- go to the home screen of signal

**Actual result:** The options button on the top right corner is invisible because of being white on a white background.
**Expected result:** I expected the button to be in a dark colour in order to have a good contrast to see the 3 dots.

### Device info

**Device:** Samsung Galaxy Core Prime
**Android version:** 5.0.2
**Signal version:** 4.68.8

### Link to debug log
https://debuglogs.org/cbe6a607e3d70aa092cb17714c9421c3fae336d9549052c3c253d7371840d69f

**Comment by sachin-0102** [comment]
Can I work on this issue
