### ISSUE TITLE
Trying to call a contact that had a safety number change gives oddly displayed message

### ISSUE THREAD

**Issue by jisckim23** [signalapp/Signal-Android#9940]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to call a contact that had a safety number change gives oddly displayed message

### Steps to reproduce
- Have a contact with Verified status.
- Have that contact reinstall Signal while creating a new PIN and not restoring from backup (i.e. do anything to trigger the warning about safety numbers before sending any new messages to them)
- Try to call that contact once you get that "Your safety number with X has changed" and the blue banner of "Your safety number with X has changed and is no longer verified"

**Actual result:** The call seems to start to initiate, but then we see a weird dialog box, and a "Network failed!" error. This dialog box disappears by itself quickly and the call UI disappears and we return back to the conversation list.
**Expected result:** No strange dialog, and some sane way to handle this case. For example, show the normal Safety Number Changes dialog when the calling buttons are pressed to prompt the user to verify/acknowledge before placing a call

### Screenshots

![safe-calls](https://user-images.githubusercontent.com/56524388/90724016-a627d980-e272-11ea-81ba-f86813293e87.jpeg)

### Device info
**Android version:** 10
**Signal version:** 4.69.4

**Comment by mueller-ma** [comment]
This has been fixed by https://github.com/signalapp/Signal-Android/commit/b3555f2f9498ff75944cdb19e032ca6a239773ae.
