### ISSUE TITLE
Registering with correct PIN crashes

### ISSUE THREAD

**Issue by cloehle** [signalapp/Signal-Android#9949]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A PIN is set, the correct PIN is entered but the app crashes without (displayed) error.

### Steps to reproduce
- enter phone number
- receive SMS and enter code
- enter correct PIN code to restore

**Actual result:** App crash without error and reopening goes back to terms of service dialog.
**Expected result:** Registering completes.

### Device info

**Device:** Moto G 5
**Android version:** 9
**Signal version:** 4.69.4

### Link to debug log
https://debuglogs.org/bd2217781011d58da1fd8e30b57068e093111c5cf98af009348edc5b12fea5d4

**Comment by akshatishere** [comment]
Hello there , if this issue is still open , I would like to work on it.

**Comment by cloehle** [comment]
Do you have the same issue?
It is still open, in fact I updated to 4.69.6 and the same crash occurs.
The exception is clearly thrown @
`app/src/main/java/org/thoughtcrime/securesms/registration/service/CodeVerificationRequest.java:105`
So there is where I would start, but I haven't looked into it myself.
It also might be hard to find an error without the backend.
