### ISSUE TITLE
Restored backup, password accepted, requests text code, initiates 30-40 CAPCHAs, finally accepts Capcha, returns to blank phone number entry screen, crashes. 

### ISSUE THREAD

**Issue by LafinJack** [signalapp/Signal-Android#9950]
Cannot acces any bug reports from within app. Signal folder contains no bug reports.

Scott

**Comment by alex-signal** [comment]
Hi! Can you check if you can use the "Steps to share a debug log from Signal's registration or PIN flow" to get a debug log?

Details here: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by LafinJack** [comment]
Unbugged itself by itself, sorry for the trouble!
