### ISSUE TITLE
Gradient at the top of video call doesn't disappear when tapping an empty part of the screen

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-Android#9951]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a video call with another Signal user, the semitransparent black to transparent gradient at the top of the screen does not hide when tapping on an empty part of the screen, even though the text on top of it disappears.

This leaves the top portion of the video call darker than is actually being captured by the other user's camera.

### Steps to reproduce
- initiate video call with another user
- once the user has picked up, tap the screen

**Actual result:** 
The text and button UI elements disappear, but the gradient at the top of the screen does not. 

**Expected result:**
The top gradient disappears on tapping the screen, in the same way as the text, buttons and bottom gradient.

### Screenshots
![signal-2020-08-23-221513](https://user-images.githubusercontent.com/18142893/90978073-2cebf780-e58e-11ea-886c-8467ae962ebb.jpg)
![Screenshot_20200823-221426](https://user-images.githubusercontent.com/18142893/90978074-307f7e80-e58e-11ea-867b-34aac56267ee.jpg)

### Device info
**Device:** Huawei P8 Lite 2017
**Android version:** 8.0.0
**Signal version:** 4.69.4

### Link to debug log
https://debuglogs.org/3403d6d028e2ea6a9347439369244e6d9faaa3e07d4a3b5b5b9e17e1d03e4b87

**Comment by jlund-signal** [comment]
That has been fixed in version 4.70.2 which is currently in beta and will be rolling out to production users sometime soon.
