### ISSUE TITLE
Unable to select voice message in multi select

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9952]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in multi select mode the user cannot select voice messages when clicking on the message bubble. Clicking next to the bubble selects the message.

### Steps to reproduce
- Open a chat
- Enter multi select mode

**Actual result:** See above
**Expected result:** The hitbox should be the complete message bubble.

### Device info

**Device:** Fairphone 3
**Android version:** 9
**Signal version:** 4.69.4

**Comment by akshatishere** [comment]
I would like to work on this issue, please assign this issue to me.

**Comment by mueller-ma** [comment]
Seems to be fixed.
