### ISSUE TITLE
Why is UserAgentInterceptor "WhatsApp" instead of "Signal"?

### ISSUE THREAD

**Issue by garrettboone** [signalapp/Signal-Android#9958]
https://github.com/signalapp/Signal-Android/blob/343b7faf9869adf3d319bb99585b84866f91c1b4/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewRepository.java#L78

Freaked out when I saw WhatsApp looking up a link on my server today....from my internal IP! I don't use WhatsApp and thought I was hacked.

Why doesn't it read "Signal" instead?

**Comment by johanw666** [comment]
Probably to prevent the rate limiting issues Signal faced before, assuming they don't dare to do that to WhatsApp. 🤣

**Comment by alex-signal** [comment]
WhatsApp isn't rate-limited. This is to allow previews for specific sites like Twitter. It's funny that we need to do this yet here we are.

**Comment by garrettboone** [comment]
Considering the domain was not even one that would produce previews (it's a local business site, served locally, and I was communicating with the owner on development issues), should it even be doing this at all?
```
192.168.10.2 - - [25/Aug/2020:15:10:13 -0400] "GET / HTTP/1.0" 200 2761 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:16 -0400] "GET / HTTP/1.0" 200 2761 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:16 -0400] "GET /a HTTP/1.0" 200 2761 "-" "WhatsApp"
127.0.0.1 - - [25/Aug/2020:15:10:17 -0400] "GET /api HTTP/1.0" 404 1552 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:17 -0400] "GET /api HTTP/1.0" 404 1552 "-" "WhatsApp"
127.0.0.1 - - [25/Aug/2020:15:10:18 -0400] "GET /api/ HTTP/1.0" 404 1552 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:18 -0400] "GET /api/ HTTP/1.0" 404 1552 "-" "WhatsApp"
127.0.0.1 - - [25/Aug/2020:15:10:19 -0400] "GET /api/s HTTP/1.0" 404 1552 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:19 -0400] "GET /api/s HTTP/1.0" 404 1552 "-" "WhatsApp"
127.0.0.1 - - [25/Aug/2020:15:10:19 -0400] "GET /api/sm HTTP/1.0" 404 1552 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:19 -0400] "GET /api/sm HTTP/1.0" 404 1552 "-" "WhatsApp"
127.0.0.1 - - [25/Aug/2020:15:10:20 -0400] "GET /api/sms HTTP/1.0" 405 630 "-" "WhatsApp"
192.168.10.2 - - [25/Aug/2020:15:10:20 -0400] "GET /api/sms HTTP/1.0" 405 630 "-" "WhatsApp" **sadness**
```

Seems a bit off since the [documentation ](https://support.signal.org/hc/en-us/articles/360022474332-Link-Previews)is suggesting there's a featured domain list. The one above serves as a Plivo callback for a small business. The app was sad when it finally was told this.

**Comment by alex-signal** [comment]
@garrettboone The documentation states "Android: Link previews are available for all sites that explicitly start with `https`."

**Comment by garrettboone** [comment]
@alex-signal Ok thanks - I missed that. Please oblige me once more, although I do not have anything helpful to offer other than awareness, probably:

Tried to turn it off just now...appears it is disabled but attempting previews anyway. I have not touched the settings.
![image](https://user-images.githubusercontent.com/47018474/91306072-0ee2ea80-e77a-11ea-8955-835db581990d.png)

Last night after seeing the requests in the log, I attempted to repeat the request to the same URL but nothing showed up in the logs. I then typed out (in Signal) a different subdomain that is also served locally, but nothing happened there either. I tried a different domain, assuming the first domain was blacklisted as a non-preview site...but nothing.

This was all from my Android device, but I was also logged into desktop at the same time. I've tried this morning a third domain, only from Android, but nothing.

It didn't work from desktop and it didn't work from the business owner's iPhone. (Which now both makes sense why, given the device difference.)

I guess it's fine now, but I can't explain why it was doing it yesterday, given the settings. There was no restart of the device or app in between testing. 

I would test more but out of ideas.

**Comment by alex-signal** [comment]
> Tried to turn it off just now...appears it is disabled but attempting previews anyway. I have not touched the settings.

If you're generating link previews and the option is disabled, that would be a pretty glaring bug :)

> I guess it's fine now, but I can't explain why it was doing it yesterday, given the settings. There was no restart of the device or app in between testing.

Are you a beta tester? We've had some fairly recent changes and fixes to linked previews, as it's a brand new feature. If not, I did also just push the latest release to 100% roll out in production this morning.

**Comment by garrettboone** [comment]
No, not beta. v4.69.4

**Comment by garrettboone** [comment]
I'm dumping a device bugreport right now. I'll post back if I find anything. Thanks @alex-signal
