### ISSUE TITLE
Groups are lost after reinstalling Signal on new phone (despite Signal PIN?!)

### ISSUE THREAD

**Issue by klues** [signalapp/Signal-Android#9959]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After reinstalling Signal on a new phone, all groups are lost, similar as mentioned in old issues like https://github.com/signalapp/Signal-Android/issues/1254
Signal PIN was active and correctly entered to the new phone. As far as I understood it, one purpose of the PIN is to store and recover information about contatcs/groups?!

**Actual result:** Groups are missing on freshly installed and registered Signal instance on new phone
**Expected result:** Groups should be still available, recovered using encrypted data stored on signal servers (Signal PIN)

### Device info
**Device:** Galaxy A41
**Android version:** 10
**Signal version:** current (26.8.2020)

**Comment by riyapenn-signal** [comment]
Your [PIN can recover your profile, settings, contacts, and who you’ve blocked if you ever lose or switch devices](https://support.signal.org/hc/articles/360007059792). Groups are not included. 

You can send a one-on-one message to another member of the group and ask them to send a couple of messages in the group from their mobile phone or ask them to update the group name or avatar.

**Comment by klues** [comment]
OK, thanks for the answer. Why groups are not recovered?! To my mind it's the set of data that would make most sense to recover. Profile, settings and other contacts are not that important (because my contacts are transferred to a new phone anyway).
