### ISSUE TITLE
"Signal message" placeholder gone

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9960]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes the text box for new messages is completly empty, not even the "Signal message" placeholder text is shown.

### Steps to reproduce
- Set "Background process limit" in developer settings of your device to "No background processes"
- Open a Signal chat and leave the text box empty. It says "Signal message".
- Press the home button
- Go back to Signal via latest apps view

**Actual result:** "Signal message" placeholder is gone
**Expected result:** "Signal message" placeholder is shown

### Device info

**Device:** Fairphone 3
**Android version:** 9
**Signal version:** 4.69.6

PS: I reported this for 4.68.X already: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-68-release/15955/62

**Comment by alex-signal** [comment]
Hi! Are you able to provide (redacted) screenshots of this? I'm having a hard time visualizing exactly what you mean.

**Comment by mueller-ma** [comment]
![Screenshot_20200826-164106](https://user-images.githubusercontent.com/22525368/91318925-0d3a1680-e7bc-11ea-9892-9ea1ff7a007b.png)

**Comment by alex-signal** [comment]
Thanks a lot!

**Comment by pankarlox** [comment]
I have exactly the same case

Device: Samsung Galaxy S9
Signal version: 4.69.6

https://debuglogs.org/b84cbec3a831bf1222bfd21d60bac5feb488757304d2baef7961b734fcfdc60

**Comment by mejo-** [comment]
I experience the same issue quite a lot since 4.69 and still on 4.70.2.

**Comment by sivaraam** [comment]
I also face the same issue on a Samsung SM-J111F running Android 5.1.1. This happens when I open the conversation by tapping on a message notification (or) via the action in the device's contact app.
