### ISSUE TITLE
Signal makes requests to websites although link preview is disabled

### ISSUE THREAD

**Issue by 123quhiwiwk** [signalapp/Signal-Android#9963]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal makes requests to websites when link preview is disabled.

### Steps to reproduce
- Deactivate Link preview in Signal settings
- Paste URL in chat where you can see the requests (eg Burp Collaborator or just https://webhook.site)

**Actual result:** Signal still makes requests to websites
**Expected result:** If the link preview is disabled, there must be no requests to websites.

### Screenshots

![Signal settings](https://user-images.githubusercontent.com/70281681/91328416-3c09ba00-e7c7-11ea-9a60-7c649cf7c46a.png)
![send url](https://user-images.githubusercontent.com/70281681/91328456-46c44f00-e7c7-11ea-9594-80a77e52132a.jpeg)
![signal make request](https://user-images.githubusercontent.com/70281681/91328481-4deb5d00-e7c7-11ea-83e4-92b7cfcab099.png)
![send extended url](https://user-images.githubusercontent.com/70281681/91328497-5479d480-e7c7-11ea-81cb-ab0f2ea5144a.jpeg)
![signal still send requests](https://user-images.githubusercontent.com/70281681/91328532-5ba0e280-e7c7-11ea-81d7-c57891c6cf75.png)

### Device info

**Device:** Xiaomi Redmi Note 4
**Android version:** 10
**Signal version:** 4.69.4 (same issue in 4.69.6)

### Link to debug log

https://debuglogs.org/f39aa4a1dee5f9dabfe587bba3a0ac0454fcaf06e7a6035cd7329c5d49cc064d

**Comment by garrettboone** [comment]
https://github.com/signalapp/Signal-Android/issues/9958#issuecomment-680864182

Same here.
Honor5x, LineageOS16, v4.64.4

**Comment by garrettboone** [comment]
After update to v4.70.0, I'm confirming bug behavior exists in that version as well.

**Comment by 123quhiwiwk** [comment]
I can even reproduce this behaviour with a manually entered URL (in Signal 4.69.6). 
It even creates a link preview. (Yes, link preview is still disabled in settings.)

https://debuglogs.org/c75b664d570098cdf8a439782246b71d60f63b5471884f199b61ed27de1cceaa




![manually typing](https://user-images.githubusercontent.com/70281681/91530288-27363f00-e90b-11ea-91c8-b9846af31ebd.jpeg)
![link preview is created](https://user-images.githubusercontent.com/70281681/91530311-2e5d4d00-e90b-11ea-8f1c-d52cd2d3edac.jpeg)
![url request overview](https://user-images.githubusercontent.com/70281681/91530335-361cf180-e90b-11ea-9ce1-7e6448f1e79c.png)
![url request](https://user-images.githubusercontent.com/70281681/91530341-37e6b500-e90b-11ea-98d8-5eda71b67df4.png)

**Comment by 123quhiwiwk** [comment]
Version v4.70.0 seems to fix URL calling, when URL is typed from scratch: https://github.com/signalapp/Signal-Android/blob/8634289b7a8e2f78813635b933ecea03f3523459/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewViewModel.java#L40 https://github.com/signalapp/Signal-Android/blob/8634289b7a8e2f78813635b933ecea03f3523459/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewViewModel.java#L65-L67 and https://github.com/signalapp/Signal-Android/blob/8634289b7a8e2f78813635b933ecea03f3523459/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewViewModel.java#L161-L162

---
But if the URL is pasted then it is still called.
While debugging I see that the variable "enabled" of linkPreviewViewModel is true, when the method onTextChanged() is called (in onCursorPositionChanged() inside ConversationActivity.java). So in the method onTextChanged() all code is executed as if the link preview is enabled.

![enabled is true](https://user-images.githubusercontent.com/70281681/91581736-1f988980-e94f-11ea-87f2-833a19b9f62c.png)

Maybe it has something to do with this, because if SMS is false, "enabled" will be set to true: https://github.com/signalapp/Signal-Android/blob/c09dbfa47c50b2d316705b49d759eb492af4813b/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewViewModel.java#L140-L141

If I remove this line (141), I currently cannot reproduce this bug and no more URLs are called.

Can you please double check if this line causes the bug?

**Comment by 123quhiwiwk** [comment]
Okay seems to be fixed in https://github.com/signalapp/Signal-Android/commit/0c332b6adb316c2d09cf66d855681852d38a423d

**Comment by greyson-signal** [comment]
This was a bit nuanced. Prior to 4.70.x, this bug I believe required pasting, deleting, then pasting the link again. After 4.70.x, it could happen due to the `onTransportChanged()` issue that was called out. This has been addressed in 4.70.3, which is beginning a production rollout. Thanks!
