### ISSUE TITLE
Extremely slow to delete chats, especially if they are large.

### ISSUE THREAD

**Issue by fernando-villalba** [signalapp/Signal-Android#9969]
On a Pixel 1 Android 10, Signal 4.69.4

When I delete a chat it takes a really, really long time to delete, especially if it is large with multiple pictures, sometimes it can take up to an hour.

Surely this should not be the case.

**Comment by trad01** [comment]
Same problem here, especially if there is many messages, and many pictures and videos. 

How many messages are being deleted?

**Comment by greyson-signal** [comment]
As of 4.71 (which is currently rolling out), this should be an order of magnitude faster. Still not instantaneous, but if you were seeing large deletes taking 10 minutes, they should now take < 10sec. We'll continue to look for more improvments.
