### ISSUE TITLE
Unable to invite a single person 

### ISSUE THREAD

**Issue by BeSanidhya** [signalapp/Signal-Android#9970]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to invite a single person as the number of the selected persons is 1 less than the actual.

### Steps to reproduce
- Click on the "Invite friends" option from the Options menu
- Click on "share with contacts" option
- Select any contact

**Actual result:** SEND SMS TO 0 FRIENDS
**Expected result:** SEND SMS TO 1 FRIEND

### Screenshots
Screenshot mentioned below

### Device info

**Device:** OnePlus 6
**Android version:** 10.0.0
**Signal version:** 4.69.6

### Link to debug log

https://debuglogs.org/b07cdf7c9e510bf1cacad29a28f3622bde0e0389653ad6e5b6416957be0326c0
![signal-bug1](https://user-images.githubusercontent.com/42599808/91600190-2b06a780-e985-11ea-8e4b-fa0552a9b2e9.jpg)

**Comment by BeSanidhya** [comment]
I could solve this issue, please assign it to me.

**Comment by alan-signal** [comment]
@BeSanidhya Appreciate the offer, but we're going to do this one thanks
