### ISSUE TITLE
Unable to send stickers as a reply to a message.

### ISSUE THREAD

**Issue by Heisenberg399** [signalapp/Signal-Android#9971]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to send apps inbuild stickers as a reply to a message. It is possible to do the same via other keyboards inbuild stickers such as GBoard. This system of sticker replying is widely used in other messaging applications.

### Steps to reproduce
- Take a message in a chat for replying
- Select an inbuild sticker from Signal app

**Actual result:** Message Doesn't get pinned and the sticker is sent as an individual message, not as a reply.
**Expected result:** Message should get pinned as it does in a text reply

### Screenshots

![Signal-App-Bug](https://user-images.githubusercontent.com/26642394/91603155-1bd62880-e98a-11ea-9bf7-d231e1fb893d.jpg)

### Device info

**Device:** Poco F1
**Android version:** 10 QKQ1.190828.002
**Signal version:** 4.69.6

**Comment by akshatishere** [comment]
I could solve this issue, please assign it to me.

**Comment by Tursko** [comment]
This is actually intended behavior. This is not a bug.

**Comment by Algebr4** [comment]
If you can reply with an image there's no reason you can't reply with a sticker. I don't know if it's a bug or an unimplemented feature but I lack it almost everyday, mainly in group chats

**Comment by greyson-signal** [comment]
There's questions around how we want stickers to look with quotes, which is why we don't currently allow stickers with quotes. We're thinking about it :+1:

**Comment by sindastra** [comment]
You had 3 years now to think about it... what's your conclusion? 🙂

**Comment by sindastra** [comment]
@greyson-signal @greysonp 

I commend you for taking your time to think about this so thoroughly. It's been almost five years of thinking!

But in all seriousness, you may not realize this but replying with stickers is actually an accessibility feature for me.

I'm autistic, and sometimes I am nonverbal – where I lose the ability to use words, no matter if spoken or written – but I still understand others and can respond with simple signs, including stickers.

As difficult as it already is to be understood; not being able to quote reply with a sticker makes it even more difficult to convey meaning.

Therefore I ask you to please give this issue serious consideration and implement a means to respond with a sticker; it doesn't have to be perfect, making it like responding with a photo would be good enough.

The important part is that I'll still be able to communicate with my loved ones when I go nonverbal. Thank you. (:

**Comment by Bharath1910** [comment]
is there any updates on this? 👀

**Comment by stiermid** [comment]
Hi, I’d like to gently bring attention back to this issue.

This seems to be a missing feature that we would find useful — it’s currently not possible to reply to a message using a sticker.

It would be really useful to have this functionality, as it improves the overall messaging experience.

Is this something that might be considered in the future?

**Comment by asandikci** [comment]
Hello, I need this feature too. I will look into codebase and try to implement a draft PR in this summer. Could we please re-open this issue @greyson-signal ?

**Comment by Resutrox** [comment]
Every Signal user I know is waiting for this feature.. It's really annoying replying with a dot just to send the sticker afterwards. Please give an update about the situation

**Comment by 8m0** [comment]
Thanks for fixing JPEG format
(**literally adding one extra letter in the code**), 
and do not care about such obvious and important thing like this for 6 years.

**Comment by greyson-signal** [comment]
We fully intend on building this, hopefully sooner rather than later.

**Comment by talperets** [comment]
> We fully intend on building this, hopefully sooner rather than later.

Hey, if it's still relevant I would be happy to help
