### ISSUE TITLE
Messages not ordered correctly 

### ISSUE THREAD

**Issue by n0sign4l-official** [signalapp/Signal-Android#9978]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
What happened is that I receiver messages not in order, when they were displayed I saw something like the 10m messages than the 2m one than the 9m one and so i couldn't understand anything since the order of the messages was wrong. See the screenshot 

### Steps to reproduce
N/a

**Actual result:** messages not displayed in the right order
**Expected result:** messages should be displayed in right order
### Screenshots
![signal-2020-08-30-1720121](https://user-images.githubusercontent.com/64698819/91741397-ee20f780-ebb4-11ea-94c2-3aba8509d8da.png)

### Device info

**Device:** HUAWEI VNS-L31
**Android version:** 6.0
**Signal version:** 4.69.6

### Link to debug log

https://debuglogs.org/643873cf848f776ab4d2e4916ade159087a08087cf5b4af11347f1a688d0967b

**Comment by bme13** [comment]
This seems related to #9088.

**Comment by rosenpin** [comment]
Happens to me too, without battery saver enabled
![screenshot-2021-03-24_22_53_40](https://user-images.githubusercontent.com/5289630/112382900-19a43480-8cf5-11eb-9dfb-dca0c6b8301f.jpg)

I'm using a samsung device so it might be killing the app in the background, creating circumstances similar to when battery saver is enabled
