### ISSUE TITLE
Notification 'Mark Read' Button Does Not Work After Replying to Message from Notification

### ISSUE THREAD

**Issue by dabat** [signalapp/Signal-Android#9979]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The 'Mark Read' button on the message notification does not work after replying to the message from the notification. The button works as expected if you tap it and have not replied to the message.
This behavior occurs with both signal and SMS messages, as I have Signal set as the default SMS app on my phone.

### Steps to reproduce
- receive a message from a friend
- tap the 'Reply' button and send a response to your friend
- tap the 'Mark Read' button

**Actual result:** The message is not marked read and the notification for the message persists.
**Expected result:** The message is marked read and the notification for the message is dismissed.

### Device info

**Device:** Google Pixel 2, running on Google Fi service
**Android version:** 10
**Signal version:** 4.70.3

**Comment by bme13** [comment]
Hi. This seems to be a duplicate of #9410.

**Comment by dabat** [comment]
wow, yeah. sorry about that.
I searched and did not find this one before posting.
i will close this as a duplicate.
thanks @bme13
