### ISSUE TITLE
Messages from Android device do not arrive on desktop groupschat

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9981]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
Since I upgraded to 4.70.5 (but it might have happened before, I usually send from desktop in this groupchat), messages posted from my Android phone in a groupchat do not arrive anymore in the groupchat on the desktop. Messages from desktop do arrive on Android, and there is no problem in one on one chats. The desktop shows as coupled on the Android device.

### Steps to reproduce
- Postmessage from Android device with acoupoled device in a groupchat
- It does not arrive

**Actual result:** It does arrive.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.70.5

### Link to debug log
Android logfile: https://debuglogs.org/ee375569c8971f220f41e363d9b412120fb2f33cfcd5bfbdc15bfd2fd7e78958

desktop logfile: https://debuglogs.org/62bc21c620b9a6fab354372f9e60c0638303447647c4a147982cc28b963948b7

**Comment by wizardofid** [comment]
I'm experiencing the same behaviour. Seems that only groups are affected that contain invalid members.

**Comment by cody-signal** [comment]
@johanw666 Thanks for the bug report and including logs for both devices. Do you have any other additional reproduction steps or state information about your group? This is a difficult one to reproduce so any extra information is helpful.

>invalid members

@wizardofid could you elaborate on what you mean by invalid members?

**Comment by wizardofid** [comment]
> > invalid members
> 
> @wizardofid could you elaborate on what you mean by invalid members?
Sure. By invalid members i'm thinking of group members who left Signal or changed number without leaving the group before doing so.

**Comment by johanw666** [comment]
There are indeed members in this group who have since unregistered and can't be removed (maybe by hand using a database query directly?)
