### ISSUE TITLE
Most Characters in the app vanished 

### ISSUE THREAD

**Issue by severus-tux** [signalapp/Signal-Android#9982]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening signal to see most characters vanished 

### Steps to reproduce
(I am not sure what causes it. It happens sometime)
- Enable fingerprint lock.
- Use android 9's capsule home button.
- switch between signal and other apps using the capsule. 
- It also happens when I receive a message while signal is minimized, I click on the notification. Signal goes blank. I press home button, clear signal, open it again. Now, it goes all wild.

**Actual result:** Normal behaviour 
**Expected result:** See Screenshots 

### Screenshots
![signal-2020-08-24-115010](https://user-images.githubusercontent.com/21301040/91982851-75eb3b00-ed48-11ea-9ed7-347ea6cd51fb.jpg)
![signal-2020-09-02-180820](https://user-images.githubusercontent.com/21301040/91982859-784d9500-ed48-11ea-92db-9b4cbf00d8ee.jpg)
![signal-2020-09-02-180820](https://user-images.githubusercontent.com/21301040/91982864-7a175880-ed48-11ea-8998-537b7e50386e.png)
![signal-2020-09-02-180820-1](https://user-images.githubusercontent.com/21301040/91982867-7be11c00-ed48-11ea-8653-6b422d0697a4.jpg)
![signal-2020-09-02-180820-2](https://user-images.githubusercontent.com/21301040/91982872-7d124900-ed48-11ea-8754-1cb96fd7dadc.jpg)

### Device info

**Device:**Asus Zenfone Max Pro M1
**Android version:** Lineage OS 16 (Android 9)
**Signal version:** 4.70.3

### Link to debug log
https://debuglogs.org/bfd544cb2e39f53d45d0698fdb620453815cba21236436d09f740a9b5384b3f9

**Comment by Genis-Sage** [comment]
Hey @severus-tux 
do you remember which version of Signal you had before 4.70.3?

did you already try to clear the cache?

**Comment by severus-tux** [comment]
> Hey @severus-tux
> do you remember which version of Signal you had before 4.70.3?
> 
> did you already try to clear the cache?

I was running 4.69.4. The issue existed in that version too. 

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-68-release/15955/65?u=severus-tux
