### ISSUE TITLE
can't unblock user

### ISSUE THREAD

**Issue by andreib1** [signalapp/Signal-Android#9983]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to contact previously blocked user

### Steps to reproduce
- have linked pc desktop device
- block signal contact
- unblock signal contact

**Actual result:** Incoming signal encrypted messages are received correctly, but the sender is not notified of receipt (one tick).  Outgoing messages are sent to signal server, but never  reach the recipient (one tick).
**Expected result:** Message transmission should resume as per normal operation

### Log

https://debuglogs.org/621a58d69d5420cd9f19d5daefa5109806dda2a3f7cd3441e729420f9545898a

**Comment by andreib1** [comment]
Additional Information:  The recipient blocked and then unblocked me, and now my messages are showing as reaching the sender (two ticks), but they never see them.  Their messages arrive to me, but are still not showing as received.

**Comment by cody-signal** [comment]
Fixed in https://github.com/signalapp/Signal-Android/commit/1ee747f3e

**Comment by andreib1** [comment]
@cody-signal thank you 🙂
