### ISSUE TITLE
Disabling "Use system emoji" doesn't bring back Signal's emoji keyboard

### ISSUE THREAD

**Issue by bhautik008** [signalapp/Signal-Android#9985]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by bhautik008** [comment]
I enabled "Use System emoji" and after that disabling that doesn't bring back emoji button in conversation edit text. Therefore, cannot access emoji keyboard.

**Comment by alan-signal** [comment]
Can't reproduce. What version are you on?

**Comment by UserX404** [comment]
Maybe you have to use the keyboards emoji functionality. I noticed same behavior a few month (and versions) ago.

**Comment by bhautik008** [comment]
I am on 4.70.5 version. I don't think so device model can affect but using Sony smartphones. I tried multiple times, even doing Force Stop to app to check if it able to pull out new settings.

**Comment by Genis-Sage** [comment]
hey @bhautik008 
just to get sure, there is no misunderstanding.

do you see the sticker button in the edit window?

if yes, click on the sticker button and then change to emojies
(then also the sticker button will again use the emojy symbol)

**Comment by bhautik008** [comment]
Thanks but I just re-installed before viewing your comment. I will try and check again.
