### ISSUE TITLE
Signal spontaneously exits full screen video chat mode 

### ISSUE THREAD

**Issue by benjertho** [signalapp/Signal-Android#9986]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While in full screen (normal) video chat, the video spontaneously exits full screen into picture-in-picture mode. The picture in picture window must then be selected to re-enter full screen. This happens repeatedly with intervals ranging from 1 minute to 10 minutes. 

### Steps to reproduce
- use video chat
- wait for spontaneous exit

**Actual result:** Full screen mode is replaced by pic-in-pic mode
**Expected result:** Full screen mode unaltered. 

### Device info

**Device:** LG G6+
**Android version:** 9
**Signal version:** 4.70.5

**Comment by cody-signal** [comment]
Could you provide logs and any other reproduction steps? I am unable to reproduce.

**Comment by benjertho** [comment]
https://debuglogs.org/b91d5cf74dc185f33b61c34b4e7130212f01b66020a49fce5bca7d59b5655379

The spontaneous exits happened around 4-5 times between 10:15 and 10:45. I didn't think to record the times for the logs, but when/if it happens again I can update this thread with better debug info.

**Comment by benjertho** [comment]
https://debuglogs.org/6353827b9131044e6905ffa96e1745b07660dd8ab296f36a3e9e0dd6776f8e4d
A singular spontaneous exit occurred at 16:13

**Comment by benjertho** [comment]
https://debuglogs.org/f699dd8568dcb0cffa193daf1010c775b326374ea80591fc771fc1844550c026
A singular spontaneous exit occurred at 16:21

**Comment by cody-signal** [comment]
Thanks @benjertho for continuing with providing logs, you've got a weird one, so any info is helpful. Thanks.

**Comment by benjertho** [comment]
I no longer experience this issue. I am not certain with what update it stopped happening, though.
