### ISSUE TITLE
Will Signal merge some new features of the Session messenger?

### ISSUE THREAD

**Issue by Pingmin** [signalapp/Signal-Android#9987]
Sorry for this is just a feature discussion.

I want to know what Signal will do when I click "Reset session", so I just searched "Signal messenger reset session" yesterday(20200903), and then I just found the [Session messenger](https://getsession.org) accidentally. It's [forked from Signal messenger](https://github.com/loki-project/session-android), but with some new features, such as it doesn't need a phone number, and uses the onion routing...

So I just want to know:

Will Signal messenger **MERGE** some new features of the Session messenger(e.g.: no phone number, onion routing), even though this will impact on user experience in someway?

Thanks!

@greyson-signal @alan-signal

**Comment by greyson-signal** [comment]
We have no plans to merge any code from Session. We do have similar goals we're working towards regarding reducing dependencies on phone numbers. Of course that's a much more involved process when you already have many users registered via phone number.

In the future, as mentioned in our issue template, please discuss non-bugs on the forum. Thanks!
