### ISSUE TITLE
"Background Connection Enabled" Notification Despite Installing from Play Store

### ISSUE THREAD

**Issue by Platzk** [signalapp/Signal-Android#9990]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Despite being downloaded from the Google Play Store (and Play Services being listed as 'True' in the debug log), Signal displays a persistent "Background Connection Enabled" notification at all times while active. It's my understanding that this shouldn't be the case for the Play Store version of the app. I've tried reinstalling Signal, clearing the Play Services and Store cache etc.

### Steps to reproduce
- Download Signal from the Google Play Store on a Pixel 2 XL running stock Android 10.
- Set it up.

**Actual result:** Persistent "Background Connection Enabled" notification.
**Expected result:** No notification because the app is using Play Services.

### Screenshots

![Screenshot_20200905-140324](https://user-images.githubusercontent.com/47435862/92305975-f053cf00-ef83-11ea-8eba-af471dba6dff.png)
![Screenshot_20200905-143103](https://user-images.githubusercontent.com/47435862/92306107-a4555a00-ef84-11ea-8926-f63cf406882c.png)

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 10
**Signal version:** 4.70.5

### Link to debug log

https://debuglogs.org/24362cc63fef6e0c30701f9c93e0bffedfb739e634100936ad0de1588a72d5cf

**Comment by Genis-Sage** [comment]
hey @Platzk 
the important line in your log in the FCM line, which says false

what kind of registration did you use? SMS or call?

did you VPN run during the registration process, as it seems, that Google does not offer FCM for all regions:
https://stackoverflow.com/questions/41776992/google-restricts-fcm-service-based-on-ip-address-is-there-any-other-free-androi

**Comment by Platzk** [comment]
Well, to the surprise of no one, I'm an idiot. Turning off the VPN completely and reinstalling fixed it. I tried pausing the VPN and reinstalling when it first happened, but it must have reactivated part way through the process. My bad! Thanks!
