### ISSUE TITLE
"Signal keeps stopping" 

### ISSUE THREAD

**Issue by thijs818** [signalapp/Signal-Android#9991]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doens't start and the message "Signal keeps stopping" appears.

### Device info

**Device:** Oneplus 5T (dumpling)
**Android version:** Lineage 16.0 with MicroG 
**Signal version:** 4.69.6

### Link to debug log

09-05 20:47:57.550 16454 16454 D AndroidRuntime: Shutting down VM
09-05 20:47:57.550 16454 16454 E AndroidRuntime: FATAL EXCEPTION: main
09-05 20:47:57.550 16454 16454 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16454
09-05 20:47:57.550 16454 16454 E AndroidRuntime: java.lang.AssertionError: javax.crypto.AEADBadTagException
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:75)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:51)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:217)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:111)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: Caused by: javax.crypto.AEADBadTagException
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:73)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	... 15 more
09-05 20:47:57.550 16454 16454 E AndroidRuntime: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:850)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
09-05 20:47:57.550 16454 16454 E AndroidRuntime: 	... 17 more
09-05 20:47:57.552  1319  2197 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
09-05 20:47:57.555  1319  1335 I ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0

I could supply more debugging if necessary, but I was careful to add too much because there are maybe security issues with sharing debug logs

**Comment by Genis-Sage** [comment]
hey @thijs818 
Did you do anything special before the crash happened?
Updated Signal, updating OS, etc?

**Comment by thijs818** [comment]
Yesterday I installed the OS and today I used titanium backup to get everything, including signal, back on my phone again. First it worked for some time, but at some point it started to fail me.

**Comment by thijs818** [comment]
I tried to reinstall it, after which I was able to fill in my phone number. After filling in my phone number, however, I got the same message "Signal keeps stopping".

**Comment by Genis-Sage** [comment]
@thijs818 
Signal is not compatible with titanium backup
there are already old bug reports, where Titanium caused this, for example #9943 

but since the same problems occurs after you deleted signal and installed it wihtout the help of titanium,
can you provide a new debug log?
