### ISSUE TITLE
Media controls and navbar invisible in full-screen media view

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-Android#9993]
Media controls and navigation bar are invisible in full-screen media view.

### Steps to reproduce
- Open any photo or video in Signal in any way:
  - from a conversation
  - from Signal Settings > Storage > Review Storage
  - from a conversation's "All media"
  - etc.

**Actual result:** Media controls and navigation bar appear normally for a short time, but shortly become invisible. However, all of them still remain interactable.

- Tap on the video/photo, which usually *hides* the controls.

**Actual result:** Android's navigation is indeed hidden, but media controls and navigation bar remain interactable, although they should be *really hidden* in this case.

**Expected result:** Media controls and navigation bar should be visible when they can be interacted with. Probably, they should also be not interactable when they are hidden, although the opposite behavior could be a design decision.

### Screenshots

- **A:** (Invisible, interactable) or (when interacted with in state **B**).
- **B:** Invisible, hidden, interactable.

A | B
---|---
![](https://user-images.githubusercontent.com/19972511/92320634-9eff1a80-f02b-11ea-9aea-28f1b1977e7f.jpeg) | ![](https://user-images.githubusercontent.com/19972511/92320637-acb4a000-f02b-11ea-88f4-e88bdaa42949.jpeg)

### Device info

**Device:** Pixel 3 XL
**Android version:** 11 (`6705141, RPB3.200720.005`)
**Signal version:** 4.70.5

### Link to debug log

https://debuglogs.org/92a009e7ccea48d72353b75cbb89564844fb3bfbf801b2cfc64b91c2813d2740

**Comment by riggs-** [comment]
Confirming the same issue exists on Android 11 final (RP1A.200720.009).

**Comment by Herohtar** [comment]
I'm having this issue as well. Videos have no playback controls and can't be stopped/paused. Tapping the screen during playback has no effect.

Phone: Pixel 2 XL
OS: Android 11

https://debuglogs.org/0070803c5ffd430634c62cbb5ad62a96af20ff0fd6e7751bdaa0ce0a87a8fb02

**Comment by riggs-** [comment]
@Herohtar When playing a video, can you try to tap at the very bottom of the screen in the middle? That should play / pause. (It seems the controls are in fact there, but invisible ...)

**Comment by Herohtar** [comment]
@riggs- You're right, I can pause/resume in the area where the control should be.
