### ISSUE TITLE
Feature request voting and feedback

### ISSUE THREAD

**Issue by user849651** [signalapp/Signal-Android#9994]
This is not specific to the Android platform, but rather Signal as a whole.

I believe it's important for users to be able to publicly request feature requests, and to be able to vote and provide feedback on other feature requests, without the need for doing so through Github.

Services like UserVoice, or any of its dozens of competitors, provide boards where users can vote on other previously-made feature requests, create their own feature requests, or provide feedback and further details on an existing feature request.

https://i.imgur.com/rTVBTb1.png

In my experience, feature requests are a bit convoluted now in that the user must either create a Github account and familiarize themselves with Github before making a request, or they must provide feedback through the [Signal support site](https://support.signal.org/hc/en-us/requests/new), where it's not clear whether or not their request will even be seen, read, or replied to.

There's also the issue that feature requests don't typically apply to a specific platform, but rather to Signal as a whole, which makes it even more confusing for me to be posting this here, in the Android repo, rather than elsewhere where it would make more sense.

The advantage of this is:

1. Users can see what's been previously requested (fewer duplicates)
2. Users can vote on what's most important to them
3. Users can provide feedback and additional details on existing requests (to flesh out the feature)
4. Users get to see what the team at Signal may or may not be considering as a feature
5. Users don't need Github accounts, or need to familiarize themselves with Github, before making a feature request
6. It encourages users to take part the in feature process, including design, feedback, etc.

Let me know what you think!

**Comment by Cerberus0** [comment]
Hi @user849651,

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this over to the [community forum](https://community.signalusers.org/). Thanks!
