### ISSUE TITLE
Echo when calling from Oneplus 5

### ISSUE THREAD

**Issue by Salokyn** [signalapp/Signal-Android#9996]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Echo on Oneplus 5 when Oneplus 5 calls a Oneplus 3. No problem when Oneplus 3 calls Oneplus 5.

(I already added a comment on this closed issue: https://github.com/signalapp/Signal-Android/issues/7635#issuecomment-688158384)

### Steps to reproduce
- Call from a Oneplus 5
- Listen to your own voice

**Actual result:** I can hear my own voice
**Expected result:** Clear call

### Calling Device info
**Device:** ONEPLUS A5010
**Android version:** OxygenOS 9.0.10
**Signal version:** 4.70.5 (though it did it before)

### Called Device info (is it relevant?)
**Device:** ONEPLUS A3003
**Android version:** OxygenOS 9.0.6
**Signal version:** 4.70.5

**Comment by Genis-Sage** [comment]
hey @Salokyn 
does this happen only with this one contact or also with other contacts?

if it also happens with other contacts, what phones do they use?

what kind of network do you use? mobile or wifi?

**Comment by 12people** [comment]
Having the same problem with the OnePlus 3T, which a friend of mine uses. (I use a Fairphone 3.)
If I call her, I hear an echo. If she calls me, she hears an echo.
When I call a different friend in Signal, this doesn't happen.

**Comment by KruyKaze** [comment]
Issue exists when calling TO oneplus 5 that has stock android no custom rom.
To be clear I am the one hearing the echo coming back from the oneplus 5.
Please add to blacklist . Thank you !

**Comment by PierreGranger** [comment]
+1 : everytime I call someone, on the first 10 seconds they hear themselves.
It's not with a particular app, it's the regular Phone app on stock version.
It stops after a few seconds of when I talk a bit, it's like the mic was too sensitive at first, and listen to the caller, and when I start talking it "realise" he was too sensitive and no longer echo the caller ?

**Comment by KruyKaze** [comment]
Yes the issue still exists.

**Comment by jimio-signal** [comment]
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5

**Comment by Salokyn** [comment]
I changed my OP3 for a Fairphone3. There's no more echo when calling or beeing called from the OP5.
